libMesh: libMesh::GhostPointNeighbors Class Reference
SomeWebsiteLogo
libMesh::GhostPointNeighbors Class Reference
#include <ghost_point_neighbors.h>
Public Types
typedef LIBMESH_BEST_UNORDERED_MAP< const Elem *, const CouplingMatrix * > map_type
Public Member Functions
GhostPointNeighbors (const MeshBase &mesh)
virtual void operator() (const MeshBase::const_element_iterator &range_begin, const MeshBase::const_element_iterator &range_end, processor_id_type p, map_type &coupled_elements)
virtual void mesh_reinit ()
virtual void dofmap_reinit ()
virtual void redistribute ()
virtual void delete_remote_elements ()
Static Public Member Functions
static std::string get_info ()
static void print_info (std::ostream &out=libMesh::out)
static unsigned int n_objects ()
static void enable_print_counter_info ()
static void disable_print_counter_info ()
Protected Types
typedef std::map< std::string, std::pair< unsigned int, unsigned int > > Counts
Protected Member Functions
void increment_constructor_count (const std::string &name)
void increment_destructor_count (const std::string &name)
Static Protected Attributes
static Counts _counts
static Threads::atomic< unsigned int > _n_objects
static Threads::spin_mutex _mutex
static bool _enable_print_counter = true
Private Attributes
const MeshBase & _mesh
Detailed Description
This class implements the default geometry ghosting in libMesh: point neighbors and interior_parent elements are ghosted.
Author
Roy H. Stogner
Date
2016
Definition at line 36 of file ghost_point_neighbors.h.
Member Typedef Documentation
typedef std::map<std::string, std::pair<unsigned int, unsigned int> > libMesh::ReferenceCounter::Counts protected inherited
Data structure to log the information. The log is identified by the class name.
Definition at line 119 of file reference_counter.h.
typedef LIBMESH_BEST_UNORDERED_MAP<const Elem*, const CouplingMatrix*> libMesh::GhostingFunctor::map_type inherited
What elements do we care about and what variables do we care about on each element?
Definition at line 140 of file ghosting_functor.h.
Constructor & Destructor Documentation
libMesh::GhostPointNeighbors::GhostPointNeighbors (const MeshBase & mesh) inline
Constructor.
Definition at line 43 of file ghost_point_neighbors.h.
References operator()().
 : _mesh(mesh) {}
Member Function Documentation
virtual void libMesh::GhostingFunctor::delete_remote_elements () inline virtual inherited
GhostingFunctor subclasses with relatively long-lasting caches may want to delete the no-longer-relevant parts of those caches after a redistribution is complete.
Reimplemented in libMesh::PointNeighborCoupling, and libMesh::DefaultCoupling.
Definition at line 190 of file ghosting_functor.h.
Referenced by libMesh::MeshCommunication::delete_remote_elements().
 {};
void libMesh::ReferenceCounter::disable_print_counter_info () static inherited
Definition at line 107 of file reference_counter.C.
References libMesh::ReferenceCounter::_enable_print_counter.
Referenced by libMesh::LibMeshInit::LibMeshInit(), and libMesh::ReferenceCounter::n_objects().
 {
   _enable_print_counter = false;
   return;
 }
virtual void libMesh::GhostingFunctor::dofmap_reinit () inline virtual inherited
For algebraic ghosting or coupling functors we also call dofmap_reinit() later, after dofs have been distributed on the new mesh but before the functors have been queried for send_list or sparsity pattern calculations.
Definition at line 171 of file ghosting_functor.h.
Referenced by libMesh::DofMap::distribute_dofs().
 {};
void libMesh::ReferenceCounter::enable_print_counter_info () static inherited
Methods to enable/disable the reference counter output from print_info()
Definition at line 101 of file reference_counter.C.
References libMesh::ReferenceCounter::_enable_print_counter.
Referenced by libMesh::ReferenceCounter::n_objects().
 {
   _enable_print_counter = true;
   return;
 }
std::string libMesh::ReferenceCounter::get_info () static inherited
Gets a string containing the reference information.
Definition at line 47 of file reference_counter.C.
References libMesh::ReferenceCounter::_counts, and libMesh::Quality::name().
Referenced by libMesh::ReferenceCounter::print_info().
 {
 #if defined(LIBMESH_ENABLE_REFERENCE_COUNTING) && defined(DEBUG)
   std::ostringstream oss;
   oss << '\n'
       << " ---------------------------------------------------------------------------- \n"
       << "| Reference count information                                                |\n"
       << " ---------------------------------------------------------------------------- \n";
   for (Counts::iterator it = _counts.begin();
        it != _counts.end(); ++it)
     {
       const std::string name(it->first);
       const unsigned int creations    = it->second.first;
       const unsigned int destructions = it->second.second;
       oss << "| " << name << " reference count information:\n"
           << "|  Creations:    " << creations    << '\n'
           << "|  Destructions: " << destructions << '\n';
     }
   oss << " ---------------------------------------------------------------------------- \n";
   return oss.str();
 #else
   return "";
 #endif
 }
void libMesh::ReferenceCounter::increment_constructor_count (const std::string & name) inline protected inherited
Increments the construction counter. Should be called in the constructor of any derived class that will be reference counted.
Definition at line 185 of file reference_counter.h.
References libMesh::ReferenceCounter::_counts, libMesh::Quality::name(), and libMesh::Threads::spin_mtx.
Referenced by libMesh::ReferenceCounter::n_objects(), and libMesh::ReferenceCountedObject< RBParametrized >::ReferenceCountedObject().
 {
   Threads::spin_mutex::scoped_lock lock(Threads::spin_mtx);
   std::pair<unsigned int, unsigned int> & p = _counts[name];
   p.first++;
 }
void libMesh::ReferenceCounter::increment_destructor_count (const std::string & name) inline protected inherited
Increments the destruction counter. Should be called in the destructor of any derived class that will be reference counted.
Definition at line 198 of file reference_counter.h.
References libMesh::ReferenceCounter::_counts, libMesh::Quality::name(), and libMesh::Threads::spin_mtx.
Referenced by libMesh::ReferenceCounter::n_objects(), and libMesh::ReferenceCountedObject< RBParametrized >::~ReferenceCountedObject().
 {
   Threads::spin_mutex::scoped_lock lock(Threads::spin_mtx);
   std::pair<unsigned int, unsigned int> & p = _counts[name];
   p.second++;
 }
virtual void libMesh::GhostingFunctor::mesh_reinit () inline virtual inherited
GhostingFunctor subclasses which cache data will need to initialize that cache. We call mesh_reinit() whenever the relevant Mesh has changed, but before remote elements on a distributed mesh are deleted.
Reimplemented in libMesh::PointNeighborCoupling, and libMesh::DefaultCoupling.
Definition at line 163 of file ghosting_functor.h.
Referenced by libMesh::UnstructuredMesh::contract(), and libMesh::MeshBase::prepare_for_use().
 {};
static unsigned int libMesh::ReferenceCounter::n_objects () inline static inherited
Prints the number of outstanding (created, but not yet destroyed) objects.
Definition at line 85 of file reference_counter.h.
References libMesh::ReferenceCounter::_n_objects, libMesh::ReferenceCounter::disable_print_counter_info(), libMesh::ReferenceCounter::enable_print_counter_info(), libMesh::ReferenceCounter::increment_constructor_count(), libMesh::ReferenceCounter::increment_destructor_count(), and libMesh::Quality::name().
Referenced by libMesh::System::hide_output(), and libMesh::LibMeshInit::LibMeshInit().
   { return _n_objects; }
void libMesh::GhostPointNeighbors::operator() (const MeshBase::const_element_iterator & range_begin, const MeshBase::const_element_iterator & range_end, processor_id_type p, GhostPointNeighbors::map_type & coupled_elements) virtual
For the specified range of active elements, find their point neighbors and interior_parent elements, ignoring those on processor p.
Implements libMesh::GhostingFunctor.
Definition at line 33 of file ghost_point_neighbors.C.
References libMesh::Elem::active(), libMesh::Elem::active_family_tree_by_neighbor(), libMesh::Elem::dim(), libMesh::Elem::interior_parent(), libmesh_nullptr, libMesh::Elem::n_nodes(), libMesh::Elem::n_sides(), libMesh::Elem::neighbor_ptr(), libMesh::Elem::node_ptr(), libMesh::processor_id(), libMesh::DofObject::processor_id(), and libMesh::remote_elem.
Referenced by GhostPointNeighbors().
 {
   // Using the connected_nodes set rather than point_neighbors() gives
   // us correct results even in corner cases, such as where two
   // elements meet only at a corner.  ;-)
   std::set<const Node *> connected_nodes;
   // Links between boundary and interior elements on mixed
   // dimensional meshes also give us correct ghosting in this way.
   std::set<const Elem *> interior_parents;
   // We also preserve neighbors and their neighboring children for
   // active local elements - in most cases this is redundant with the
   // node check, but for non-conforming Tet4 meshes and
   // non-level-one-conforming 2D+3D meshes it is possible for an
   // element and its coarse neighbor to not share any vertices.
   //
   // We also preserve interior parents for active pid elements
   // This code is just for geometric coupling, so we use a null
   // CouplingMatrix pointer.  We'll declare that here so as to avoid
   // confusing the insert() calls later.
   CouplingMatrix * nullcm = libmesh_nullptr;
   for (MeshBase::const_element_iterator elem_it = range_begin;
        elem_it!=range_end; ++elem_it)
     {
       const Elem * elem = *elem_it;
       if (elem->processor_id() != p)
         coupled_elements.insert (std::make_pair(elem,nullcm));
       for (unsigned int s=0; s != elem->n_sides(); ++s)
         {
           const Elem * neigh = elem->neighbor_ptr(s);
           if (neigh && neigh != remote_elem)
             {
 #ifdef LIBMESH_ENABLE_AMR
               if (!neigh->active())
                 {
                   std::vector<const Elem*> family;
                   neigh->active_family_tree_by_neighbor(family, elem);
                   for (std::size_t i=0; i!=family.size(); ++i)
                     if (family[i]->processor_id() != p)
                       coupled_elements.insert
                         (std::make_pair(family[i], nullcm));
                 }
               else
 #endif
                 if (neigh->processor_id() != p)
                   coupled_elements.insert
                     (std::make_pair(neigh, nullcm));
             }
         }
       // It is possible that a refined boundary element will not
       // touch any nodes of its interior_parent, in TRI3/TET4 and in
       // non-level-one rule cases.  So we can't just rely on node
       // connections to preserve interior_parent().  However, trying
       // to preserve interior_parent() manually only works if it's on
       // the same Mesh, which is *not* guaranteed!  So we'll
       // double-check later to make sure our interior parents are in
       // the mesh before we connect them.
       if (elem->dim() < LIBMESH_DIM &&
           elem->interior_parent() &&
           elem->interior_parent()->processor_id() != p)
         interior_parents.insert (elem->interior_parent());
       // Add nodes connected to active local elements
       for (unsigned int n=0; n<elem->n_nodes(); n++)
         connected_nodes.insert (elem->node_ptr(n));
     }
   // Connect any interior_parents who are really in our mesh
   {
     MeshBase::const_element_iterator       elem_it  = _mesh.elements_begin();
     const MeshBase::const_element_iterator elem_end = _mesh.elements_end();
     for (; elem_it != elem_end; ++elem_it)
       {
         const Elem * elem = *elem_it;
         std::set<const Elem *>::iterator ip_it =
           interior_parents.find(elem);
         if (ip_it != interior_parents.end())
           {
             coupled_elements.insert
               (std::make_pair(elem, nullcm));
             // Shrink the set ASAP to speed up subsequent searches
             interior_parents.erase(ip_it);
           }
       }
   }
   // Connect any active elements which are connected to our range's
   // elements' nodes
   {
     MeshBase::const_element_iterator       elem_it  = _mesh.active_elements_begin();
     const MeshBase::const_element_iterator elem_end = _mesh.active_elements_end();
     for (; elem_it!=elem_end; ++elem_it)
       {
         const Elem * elem = *elem_it;
         // Add elements connected to nodes on active local elements
         if (elem->processor_id() != p)
           for (unsigned int n=0; n<elem->n_nodes(); n++)
             if (connected_nodes.count(elem->node_ptr(n)))
               coupled_elements.insert
                 (std::make_pair(elem, nullcm));
       }
   }
 }
void libMesh::ReferenceCounter::print_info (std::ostream & out = libMesh::out) static inherited
Prints the reference information, by default to libMesh::out.
Definition at line 88 of file reference_counter.C.
References libMesh::ReferenceCounter::_enable_print_counter, and libMesh::ReferenceCounter::get_info().
Referenced by libMesh::LibMeshInit::LibMeshInit().
 {
   if (_enable_print_counter)
     out_stream << ReferenceCounter::get_info();
 }
virtual void libMesh::GhostingFunctor::redistribute () inline virtual inherited
GhostingFunctor subclasses with relatively long-lasting caches may want to redistribute those caches whenever the relevant Mesh is redistributed; we will give them an opportunity when that happens. At the point in the code where this is called, element processor ids have been set to their new destinations, and those elements have been copied to their new destinations, but the elements have not yet been deleted by the processors which previously held them..
Reimplemented in libMesh::PointNeighborCoupling, and libMesh::DefaultCoupling.
Definition at line 183 of file ghosting_functor.h.
Referenced by libMesh::MeshCommunication::redistribute().
 {};
Member Data Documentation
ReferenceCounter::Counts libMesh::ReferenceCounter::_counts static protected inherited
Actually holds the data.
Definition at line 124 of file reference_counter.h.
Referenced by libMesh::ReferenceCounter::get_info(), libMesh::ReferenceCounter::increment_constructor_count(), and libMesh::ReferenceCounter::increment_destructor_count().
bool libMesh::ReferenceCounter::_enable_print_counter = true static protected inherited
Flag to control whether reference count information is printed when print_info is called.
Definition at line 143 of file reference_counter.h.
Referenced by libMesh::ReferenceCounter::disable_print_counter_info(), libMesh::ReferenceCounter::enable_print_counter_info(), and libMesh::ReferenceCounter::print_info().
const MeshBase& libMesh::GhostPointNeighbors::_mesh private
Definition at line 57 of file ghost_point_neighbors.h.
Threads::spin_mutex libMesh::ReferenceCounter::_mutex static protected inherited
Mutual exclusion object to enable thread-safe reference counting.
Definition at line 137 of file reference_counter.h.
Threads::atomic< unsigned int > libMesh::ReferenceCounter::_n_objects static protected inherited
The number of objects. Print the reference count information when the number returns to 0.
Definition at line 132 of file reference_counter.h.
Referenced by libMesh::ReferenceCounter::n_objects(), libMesh::ReferenceCounter::ReferenceCounter(), and libMesh::ReferenceCounter::~ReferenceCounter().
The documentation for this class was generated from the following files:
ghost_point_neighbors.h
ghost_point_neighbors.C