libMesh: libMesh::WeightedPatchRecoveryErrorEstimator Class Reference
SomeWebsiteLogo
libMesh::WeightedPatchRecoveryErrorEstimator Class Reference
#include <weighted_patch_recovery_error_estimator.h>
Classes
class EstimateError
Public Types
typedef std::map< std::pair< const System *, unsigned int >, ErrorVector * > ErrorMap
Public Member Functions
WeightedPatchRecoveryErrorEstimator ()=default
WeightedPatchRecoveryErrorEstimator (const WeightedPatchRecoveryErrorEstimator &)=default
WeightedPatchRecoveryErrorEstimator (WeightedPatchRecoveryErrorEstimator &&)=default
WeightedPatchRecoveryErrorEstimator & operator= (const WeightedPatchRecoveryErrorEstimator &)=default
WeightedPatchRecoveryErrorEstimator & operator= (WeightedPatchRecoveryErrorEstimator &&)=default
virtual ~WeightedPatchRecoveryErrorEstimator ()=default
virtual void estimate_error (const System &system, ErrorVector &error_per_cell, const NumericVector< Number > *solution_vector=nullptr, bool estimate_parent_error=false) override
virtual ErrorEstimatorType type () const override
void set_patch_reuse (bool)
virtual void estimate_errors (const EquationSystems &equation_systems, ErrorVector &error_per_cell, const std::map< const System *, SystemNorm > &error_norms, const std::map< const System *, const NumericVector< Number > *> *solution_vectors=nullptr, bool estimate_parent_error=false)
virtual void estimate_errors (const EquationSystems &equation_systems, ErrorMap &errors_per_cell, const std::map< const System *, const NumericVector< Number > *> *solution_vectors=nullptr, bool estimate_parent_error=false)
Public Attributes
std::vector< FEMFunctionBase< Number > * > weight_functions
unsigned int target_patch_size
Patch::PMF patch_growth_strategy
SystemNorm error_norm
Protected Member Functions
void reduce_error (std::vector< ErrorVectorReal > &error_per_cell, const Parallel::Communicator &comm) const
Static Protected Member Functions
static std::vector< Real > specpoly (const unsigned int dim, const Order order, const Point p, const unsigned int matsize)
Protected Attributes
bool patch_reuse
Friends
class EstimateError
Detailed Description
This class implements the Patch Recovery error indicator.
Author
Vikram Garg
Date
2012
Definition at line 48 of file weighted_patch_recovery_error_estimator.h.
Member Typedef Documentation
ErrorMap
typedef std::map<std::pair<const System *, unsigned int>, ErrorVector *> libMesh::ErrorEstimator::ErrorMap inherited
When calculating many error vectors at once, we need a data structure to hold them all
Definition at line 124 of file error_estimator.h.
Constructor & Destructor Documentation
WeightedPatchRecoveryErrorEstimator() [1/3]
libMesh::WeightedPatchRecoveryErrorEstimator::WeightedPatchRecoveryErrorEstimator () default
Constructor. Defaults to H1 seminorm. All Hilbert norms and seminorms should be supported now. W1,p and W2,p norms would be natural to support if any contributors make the effort.
WeightedPatchRecoveryErrorEstimator() [2/3]
libMesh::WeightedPatchRecoveryErrorEstimator::WeightedPatchRecoveryErrorEstimator (const WeightedPatchRecoveryErrorEstimator &) default
Copy/move ctor, copy/move assignment operator, and destructor are all explicitly defaulted for this class.
WeightedPatchRecoveryErrorEstimator() [3/3]
libMesh::WeightedPatchRecoveryErrorEstimator::WeightedPatchRecoveryErrorEstimator (WeightedPatchRecoveryErrorEstimator &&) default
~WeightedPatchRecoveryErrorEstimator()
virtual libMesh::WeightedPatchRecoveryErrorEstimator::~WeightedPatchRecoveryErrorEstimator () virtual default
Member Function Documentation
estimate_error()
void libMesh::WeightedPatchRecoveryErrorEstimator::estimate_error (const System & system, ErrorVector & error_per_cell, const NumericVector< Number > * solution_vector = nullptr, bool estimate_parent_error = false) override virtual
This function uses the Patch Recovery error estimate to estimate the error on each cell. The estimated error is output in the vector error_per_cell
Reimplemented from libMesh::PatchRecoveryErrorEstimator.
Definition at line 55 of file weighted_patch_recovery_error_estimator.C.
References libMesh::ParallelObject::comm(), EstimateError, libMesh::System::get_mesh(), mesh, libMesh::Threads::parallel_for(), libMesh::ErrorEstimator::reduce_error(), libMesh::System::solution, and libMesh::NumericVector< T >::swap().
 {
   LOG_SCOPE("estimate_error()", "WeightedPatchRecoveryErrorEstimator");
   // The current mesh
   const MeshBase & mesh = system.get_mesh();
   // Resize the error_per_cell vector to be
   // the number of elements, initialize it to 0.
   error_per_cell.resize (mesh.max_elem_id());
   std::fill (error_per_cell.begin(), error_per_cell.end(), 0.);
   // Prepare current_local_solution to localize a non-standard
   // solution vector if necessary
   if (solution_vector && solution_vector != system.solution.get())
     {
       NumericVector<Number> * newsol =
         const_cast<NumericVector<Number> *>(solution_vector);
       System & sys = const_cast<System &>(system);
       newsol->swap(*sys.solution);
       sys.update();
     }
   //------------------------------------------------------------
   // Iterate over all the active elements in the mesh
   // that live on this processor.
   Threads::parallel_for (ConstElemRange(mesh.active_local_elements_begin(),
                                         mesh.active_local_elements_end(),
                                         200),
                          EstimateError(system,
                                        *this,
                                        error_per_cell)
                          );
   // Each processor has now computed the error contributions
   // for its local elements, and error_per_cell contains 0 for all the
   // non-local elements.  Summing the vector will provide the true
   // value for each element, local or remote
   this->reduce_error(error_per_cell, system.comm());
   // If we used a non-standard solution before, now is the time to fix
   // the current_local_solution
   if (solution_vector && solution_vector != system.solution.get())
     {
       NumericVector<Number> * newsol =
         const_cast<NumericVector<Number> *>(solution_vector);
       System & sys = const_cast<System &>(system);
       newsol->swap(*sys.solution);
       sys.update();
     }
 }
estimate_errors() [1/2]
void libMesh::ErrorEstimator::estimate_errors (const EquationSystems & equation_systems, ErrorVector & error_per_cell, const std::map< const System *, SystemNorm > & error_norms, const std::map< const System *, const NumericVector< Number > *> * solution_vectors = nullptr, bool estimate_parent_error = false) virtual inherited
This virtual function can be redefined in derived classes, but by default computes the sum of the error_per_cell for each system in the equation_systems.
Currently this function ignores the error_norm member variable, and uses the function argument error_norms instead.
This function is named estimate_errors instead of estimate_error because otherwise C++ can get confused.
Reimplemented in libMesh::UniformRefinementEstimator.
Definition at line 47 of file error_estimator.C.
References libMesh::ErrorEstimator::error_norm, libMesh::ErrorEstimator::estimate_error(), libMesh::EquationSystems::get_system(), libMesh::index_range(), and libMesh::EquationSystems::n_systems().
 {
   SystemNorm old_error_norm = this->error_norm;
   // Sum the error values from each system
   for (unsigned int s = 0; s != equation_systems.n_systems(); ++s)
     {
       ErrorVector system_error_per_cell;
       const System & sys = equation_systems.get_system(s);
       if (error_norms.find(&sys) == error_norms.end())
         this->error_norm = old_error_norm;
       else
         this->error_norm = error_norms.find(&sys)->second;
       const NumericVector<Number> * solution_vector = nullptr;
       if (solution_vectors &&
           solution_vectors->find(&sys) != solution_vectors->end())
         solution_vector = solution_vectors->find(&sys)->second;
       this->estimate_error(sys, system_error_per_cell,
                            solution_vector, estimate_parent_error);
       if (s)
         {
           libmesh_assert_equal_to (error_per_cell.size(), system_error_per_cell.size());
           for (auto i : index_range(error_per_cell))
             error_per_cell[i] += system_error_per_cell[i];
         }
       else
         error_per_cell = system_error_per_cell;
     }
   // Restore our old state before returning
   this->error_norm = old_error_norm;
 }
estimate_errors() [2/2]
void libMesh::ErrorEstimator::estimate_errors (const EquationSystems & equation_systems, ErrorMap & errors_per_cell, const std::map< const System *, const NumericVector< Number > *> * solution_vectors = nullptr, bool estimate_parent_error = false) virtual inherited
This virtual function can be redefined in derived classes, but by default it calls estimate_error repeatedly to calculate the requested error vectors.
Currently this function ignores the error_norm.weight() values because it calculates each variable's error individually, unscaled.
The user selects which errors get computed by filling a map with error vectors: If errors_per_cell[&system][v] exists, it will be filled with the error values in variable v of system
FIXME: This is a default implementation - derived classes should reimplement it for efficiency.
Reimplemented in libMesh::UniformRefinementEstimator.
Definition at line 93 of file error_estimator.C.
References libMesh::ErrorEstimator::error_norm, libMesh::ErrorEstimator::estimate_error(), libMesh::EquationSystems::get_system(), libMesh::EquationSystems::n_systems(), n_vars, libMesh::System::n_vars(), and libMesh::SystemNorm::type().
 {
   SystemNorm old_error_norm = this->error_norm;
   // Find the requested error values from each system
   for (unsigned int s = 0; s != equation_systems.n_systems(); ++s)
     {
       const System & sys = equation_systems.get_system(s);
       unsigned int n_vars = sys.n_vars();
       for (unsigned int v = 0; v != n_vars; ++v)
         {
           // Only fill in ErrorVectors the user asks for
           if (errors_per_cell.find(std::make_pair(&sys, v)) ==
               errors_per_cell.end())
             continue;
           // Calculate error in only one variable
           std::vector<Real> weights(n_vars, 0.0);
           weights[v] = 1.0;
           this->error_norm =
             SystemNorm(std::vector<FEMNormType>(n_vars, old_error_norm.type(v)),
                        weights);
           const NumericVector<Number> * solution_vector = nullptr;
           if (solution_vectors &&
               solution_vectors->find(&sys) != solution_vectors->end())
             solution_vector = solution_vectors->find(&sys)->second;
           this->estimate_error
             (sys, *errors_per_cell[std::make_pair(&sys, v)],
              solution_vector, estimate_parent_error);
         }
     }
   // Restore our old state before returning
   this->error_norm = old_error_norm;
 }
operator=() [1/2]
WeightedPatchRecoveryErrorEstimator& libMesh::WeightedPatchRecoveryErrorEstimator::operator= (const WeightedPatchRecoveryErrorEstimator &) default
operator=() [2/2]
WeightedPatchRecoveryErrorEstimator& libMesh::WeightedPatchRecoveryErrorEstimator::operator= (WeightedPatchRecoveryErrorEstimator &&) default
reduce_error()
void libMesh::ErrorEstimator::reduce_error (std::vector< ErrorVectorReal > & error_per_cell, const Parallel::Communicator & comm) const protected inherited
This method takes the local error contributions in error_per_cell from each processor and combines them to get the global error vector.
Definition at line 32 of file error_estimator.C.
References libMesh::Parallel::Communicator::sum().
Referenced by libMesh::UniformRefinementEstimator::_estimate_error(), estimate_error(), libMesh::PatchRecoveryErrorEstimator::estimate_error(), libMesh::JumpErrorEstimator::estimate_error(), libMesh::AdjointRefinementEstimator::estimate_error(), and libMesh::ExactErrorEstimator::estimate_error().
 {
   // This function must be run on all processors at once
   // parallel_object_only();
   // Each processor has now computed the error contributions
   // for its local elements.  We may need to sum the vector to
   // recover the error for each element.
   comm.sum(error_per_cell);
 }
set_patch_reuse()
void libMesh::PatchRecoveryErrorEstimator::set_patch_reuse (bool patch_reuse_flag) inherited
Definition at line 58 of file patch_recovery_error_estimator.C.
References libMesh::PatchRecoveryErrorEstimator::patch_reuse.
 {
   patch_reuse = patch_reuse_flag;
 }
specpoly()
std::vector< Real > libMesh::PatchRecoveryErrorEstimator::specpoly (const unsigned int dim, const Order order, const Point p, const unsigned int matsize) static protected inherited
Returns
The spectral polynomial basis function values at a point (x,y,z).
Definition at line 76 of file patch_recovery_error_estimator.C.
References libMesh::Real.
Referenced by libMesh::WeightedPatchRecoveryErrorEstimator::EstimateError::operator()(), and libMesh::PatchRecoveryErrorEstimator::EstimateError::operator()().
 {
   std::vector<Real> psi;
   psi.reserve(matsize);
   unsigned int npows = order+1;
   std::vector<Real> xpow(npows,1.), ypow, zpow;
   {
     Real x = p(0);
     for (auto i : IntRange<int>(1, npows))
       xpow[i] = xpow[i-1] * x;
   }
   if (dim > 1)
     {
       Real y = p(1);
       ypow.resize(npows,1.);
       for (auto i : IntRange<int>(1, npows))
         ypow[i] = ypow[i-1] * y;
     }
   if (dim > 2)
     {
       Real z = p(2);
       zpow.resize(npows,1.);
       for (auto i : IntRange<int>(1, npows))
         zpow[i] = zpow[i-1] * z;
     }
   // builds psi vector of form 1 x y z x^2 xy xz y^2 yz z^2 etc..
   // I haven't added 1D support here
   for (unsigned int poly_deg=0; poly_deg <= static_cast<unsigned int>(order) ; poly_deg++)
     { // loop over all polynomials of total degree = poly_deg
       switch (dim)
         {
           // 3D spectral polynomial basis functions
         case 3:
           {
             for (int xexp=poly_deg; xexp >= 0; xexp--) // use an int for xexp since we -- it
               for (int yexp=poly_deg-xexp; yexp >= 0; yexp--)
                 {
                   int zexp = poly_deg - xexp - yexp;
                   psi.push_back(xpow[xexp]*ypow[yexp]*zpow[zexp]);
                 }
             break;
           }
           // 2D spectral polynomial basis functions
         case 2:
           {
             for (int xexp=poly_deg; xexp >= 0; xexp--) // use an int for xexp since we -- it
               {
                 int yexp = poly_deg - xexp;
                 psi.push_back(xpow[xexp]*ypow[yexp]);
               }
             break;
           }
           // 1D spectral polynomial basis functions
         case 1:
           {
             int xexp = poly_deg;
             psi.push_back(xpow[xexp]);
             break;
           }
         default:
           libmesh_error_msg("Invalid dimension dim " << dim);
         }
     }
   return psi;
 }
type()
ErrorEstimatorType libMesh::WeightedPatchRecoveryErrorEstimator::type () const override virtual
Returns
The type for the ErrorEstimator subclass.
Reimplemented from libMesh::PatchRecoveryErrorEstimator.
Definition at line 48 of file weighted_patch_recovery_error_estimator.C.
References libMesh::WEIGHTED_PATCH_RECOVERY.
 {
   return WEIGHTED_PATCH_RECOVERY;
 }
Friends And Related Function Documentation
EstimateError
friend class EstimateError friend
Definition at line 119 of file weighted_patch_recovery_error_estimator.h.
Referenced by estimate_error().
Member Data Documentation
error_norm
SystemNorm libMesh::ErrorEstimator::error_norm inherited
When estimating the error in a single system, the error_norm is used to control the scaling and norm choice for each variable. Not all estimators will support all norm choices. The default scaling is for all variables to be weighted equally. The default norm choice depends on the error estimator.
Part of this functionality was supported via component_scale and sobolev_order in older libMesh versions, and a small part was supported via component_mask in even older versions. Hopefully the encapsulation here will allow us to avoid changing this API again.
Definition at line 161 of file error_estimator.h.
Referenced by libMesh::UniformRefinementEstimator::_estimate_error(), libMesh::AdjointRefinementEstimator::AdjointRefinementEstimator(), libMesh::DiscontinuityMeasure::boundary_side_integration(), libMesh::KellyErrorEstimator::boundary_side_integration(), libMesh::DiscontinuityMeasure::DiscontinuityMeasure(), libMesh::JumpErrorEstimator::estimate_error(), libMesh::AdjointResidualErrorEstimator::estimate_error(), libMesh::ExactErrorEstimator::estimate_error(), libMesh::ErrorEstimator::estimate_errors(), libMesh::ExactErrorEstimator::ExactErrorEstimator(), libMesh::ExactErrorEstimator::find_squared_element_error(), libMesh::LaplacianErrorEstimator::init_context(), libMesh::DiscontinuityMeasure::init_context(), libMesh::KellyErrorEstimator::init_context(), libMesh::LaplacianErrorEstimator::internal_side_integration(), libMesh::DiscontinuityMeasure::internal_side_integration(), libMesh::KellyErrorEstimator::internal_side_integration(), libMesh::KellyErrorEstimator::KellyErrorEstimator(), libMesh::LaplacianErrorEstimator::LaplacianErrorEstimator(), libMesh::WeightedPatchRecoveryErrorEstimator::EstimateError::operator()(), libMesh::PatchRecoveryErrorEstimator::EstimateError::operator()(), libMesh::PatchRecoveryErrorEstimator::PatchRecoveryErrorEstimator(), libMesh::JumpErrorEstimator::reinit_sides(), and libMesh::UniformRefinementEstimator::UniformRefinementEstimator().
patch_growth_strategy
Patch::PMF libMesh::PatchRecoveryErrorEstimator::patch_growth_strategy inherited
The PatchErrorEstimator will use this pointer to a Patch member function when growing patches. The default strategy used is Patch::add_local_face_neighbors. Patch::add_local_point_neighbors may be more reliable but slower.
Definition at line 99 of file patch_recovery_error_estimator.h.
Referenced by libMesh::WeightedPatchRecoveryErrorEstimator::EstimateError::operator()(), and libMesh::PatchRecoveryErrorEstimator::EstimateError::operator()().
patch_reuse
bool libMesh::PatchRecoveryErrorEstimator::patch_reuse protected inherited
Definition at line 115 of file patch_recovery_error_estimator.h.
Referenced by libMesh::WeightedPatchRecoveryErrorEstimator::EstimateError::operator()(), libMesh::PatchRecoveryErrorEstimator::EstimateError::operator()(), and libMesh::PatchRecoveryErrorEstimator::set_patch_reuse().
target_patch_size
unsigned int libMesh::PatchRecoveryErrorEstimator::target_patch_size inherited
The PatchErrorEstimator will build patches of at least this many elements to perform estimates
Definition at line 91 of file patch_recovery_error_estimator.h.
Referenced by libMesh::WeightedPatchRecoveryErrorEstimator::EstimateError::operator()(), and libMesh::PatchRecoveryErrorEstimator::EstimateError::operator()().
weight_functions
std::vector<FEMFunctionBase<Number> *> libMesh::WeightedPatchRecoveryErrorEstimator::weight_functions
Vector of fem function base pointers, the user will fill this in with pointers to the appropriate weight functions.
Definition at line 84 of file weighted_patch_recovery_error_estimator.h.
Referenced by libMesh::WeightedPatchRecoveryErrorEstimator::EstimateError::operator()().
The documentation for this class was generated from the following files:
weighted_patch_recovery_error_estimator.h
weighted_patch_recovery_error_estimator.C