libMesh: libMesh::OldSolutionBase< Output, point_output > Class Template Reference
SomeWebsiteLogo
libMesh::OldSolutionBase< Output, point_output > Class Template Reference
#include <generic_projector.h>
Public Member Functions
OldSolutionBase (const libMesh::System &sys_in)
OldSolutionBase (const OldSolutionBase &in)
void init_context (FEMContext &c)
bool is_grid_projection ()
template<>
void get_shape_outputs (FEBase &fe)
template<>
void get_shape_outputs (FEBase &fe)
template<>
void get_shape_outputs (FEBase &fe)
template<>
void get_shape_outputs (FEBase &fe)
Static Public Member Functions
static void get_shape_outputs (FEBase &fe)
Protected Member Functions
void check_old_context (const FEMContext &c)
bool check_old_context (const FEMContext &c, const Point &p)
template<>
const Real out_of_elem_tol
template<>
const Real out_of_elem_tol
template<>
const Real out_of_elem_tol
template<>
const Real out_of_elem_tol
Protected Attributes
const Elem * last_elem
const System & sys
FEMContext old_context
std::vector< unsigned int > component_to_var
Static Protected Attributes
static const Real out_of_elem_tol
Detailed Description
template<typename Output, void(FEMContext::*)(unsigned int, const Point &, Output &, const Real) const point_output>
class libMesh::OldSolutionBase< Output, point_output >
The OldSolutionBase input functor abstract base class is the root of the OldSolutionValue and OldSolutionCoefs classes which allow a GenericProjector to read old solution values or solution interpolation coefficients for a just-refined-and-coarsened mesh.
Author
Roy H. Stogner
Date
2016
Definition at line 206 of file generic_projector.h.
Constructor & Destructor Documentation
OldSolutionBase() [1/2]
template<typename Output , void(FEMContext::*)(unsigned int, const Point &, Output &, const Real) const point_output> libMesh::OldSolutionBase< Output, point_output >::OldSolutionBase (const libMesh::System & sys_in) inline
Definition at line 209 of file generic_projector.h.
                                                 :
     last_elem(nullptr),
     sys(sys_in),
     old_context(sys_in)
   {
     // We'll be queried for components but we'll typically be looking
     // up data by variables, and those indices don't always match
     for (auto v : IntRange<unsigned int>(0, sys.n_vars()))
       {
         const unsigned int vcomp = sys.variable_scalar_number(v,0);
         if (vcomp >= component_to_var.size())
           component_to_var.resize(vcomp+1, static_cast<unsigned int>(-1));
         component_to_var[vcomp] = v;
       }
   }
OldSolutionBase() [2/2]
template<typename Output , void(FEMContext::*)(unsigned int, const Point &, Output &, const Real) const point_output> libMesh::OldSolutionBase< Output, point_output >::OldSolutionBase (const OldSolutionBase< Output, point_output > & in) inline
Definition at line 225 of file generic_projector.h.
                                               :
     last_elem(nullptr),
     sys(in.sys),
     old_context(sys),
     component_to_var(in.component_to_var)
   {
   }
Member Function Documentation
check_old_context() [1/2]
template<typename Output , void(FEMContext::*)(unsigned int, const Point &, Output &, const Real) const point_output> void libMesh::OldSolutionBase< Output, point_output >::check_old_context (const FEMContext & c) inline protected
Definition at line 259 of file generic_projector.h.
References libMesh::FEMContext::get_elem(), libMesh::Elem::JUST_COARSENED, libMesh::Elem::JUST_REFINED, libMesh::DofObject::old_dof_object, libMesh::Elem::parent(), and libMesh::Elem::refinement_flag().
   {
     LOG_SCOPE ("check_old_context(c)", "OldSolutionBase");
     const Elem & elem = c.get_elem();
     if (last_elem != &elem)
       {
         if (elem.refinement_flag() == Elem::JUST_REFINED)
           {
             old_context.pre_fe_reinit(sys, elem.parent());
           }
         else if (elem.refinement_flag() == Elem::JUST_COARSENED)
           {
             libmesh_error();
           }
         else
           {
             if (!elem.old_dof_object)
               {
                 libmesh_error();
               }
             old_context.pre_fe_reinit(sys, &elem);
           }
         last_elem = &elem;
       }
     else
       {
         libmesh_assert(old_context.has_elem());
       }
   }
check_old_context() [2/2]
template<typename Output , void(FEMContext::*)(unsigned int, const Point &, Output &, const Real) const point_output> bool libMesh::OldSolutionBase< Output, point_output >::check_old_context (const FEMContext & c, const Point & p) inline protected
Definition at line 292 of file generic_projector.h.
References libMesh::Elem::child_ref_range(), libMesh::FEMContext::get_elem(), libMesh::Elem::hmax(), libMesh::Elem::JUST_COARSENED, libMesh::Elem::JUST_REFINED, libMesh::DofObject::old_dof_object, libMesh::Elem::parent(), libMesh::Real, and libMesh::Elem::refinement_flag().
   {
     LOG_SCOPE ("check_old_context(c,p)", "OldSolutionBase");
     const Elem & elem = c.get_elem();
     if (last_elem != &elem)
       {
         if (elem.refinement_flag() == Elem::JUST_REFINED)
           {
             old_context.pre_fe_reinit(sys, elem.parent());
           }
         else if (elem.refinement_flag() == Elem::JUST_COARSENED)
           {
             // Find the child with this point.  Use out_of_elem_tol
             // (in physical space, which may correspond to a large
             // tolerance in master space!) to allow for out-of-element
             // finite differencing of mixed gradient terms.  Pray we
             // have no quadrature locations which are within 1e-5 of
             // the element subdivision boundary but are not exactly on
             // that boundary.
             const Real master_tol = out_of_elem_tol / elem.hmax() * 2;
             for (auto & child : elem.child_ref_range())
               if (child.close_to_point(p, master_tol))
                 {
                   old_context.pre_fe_reinit(sys, &child);
                   break;
                 }
             libmesh_assert
               (old_context.get_elem().close_to_point(p, master_tol));
           }
         else
           {
             if (!elem.old_dof_object)
               return false;
             old_context.pre_fe_reinit(sys, &elem);
           }
         last_elem = &elem;
       }
     else
       {
         libmesh_assert(old_context.has_elem());
         const Real master_tol = out_of_elem_tol / elem.hmax() * 2;
         if (!old_context.get_elem().close_to_point(p, master_tol))
           {
             libmesh_assert_equal_to
               (elem.refinement_flag(), Elem::JUST_COARSENED);
             for (auto & child : elem.child_ref_range())
               if (child.close_to_point(p, master_tol))
                 {
                   old_context.pre_fe_reinit(sys, &child);
                   break;
                 }
             libmesh_assert
               (old_context.get_elem().close_to_point(p, master_tol));
           }
       }
     return true;
   }
get_shape_outputs() [1/5]
template<typename Output , void(FEMContext::*)(unsigned int, const Point &, Output &, const Real) const point_output> static void libMesh::OldSolutionBase< Output, point_output >::get_shape_outputs (FEBase & fe) static
get_shape_outputs() [2/5]
template<> void libMesh::OldSolutionBase< Number, &FEMContext::point_value >::get_shape_outputs (FEBase & fe) inline
Definition at line 451 of file generic_projector.h.
References libMesh::FEGenericBase< OutputType >::get_phi().
 {
   fe.get_phi();
 }
get_shape_outputs() [3/5]
template<> void libMesh::OldSolutionBase< Gradient, &FEMContext::point_gradient >::get_shape_outputs (FEBase & fe) inline
Definition at line 459 of file generic_projector.h.
References libMesh::FEGenericBase< OutputType >::get_dphi().
 {
   fe.get_dphi();
 }
get_shape_outputs() [4/5]
template<> void libMesh::OldSolutionBase< Real, &FEMContext::point_value >::get_shape_outputs (FEBase & fe) inline
Definition at line 468 of file generic_projector.h.
References libMesh::FEGenericBase< OutputType >::get_phi().
 {
   fe.get_phi();
 }
get_shape_outputs() [5/5]
template<> void libMesh::OldSolutionBase< RealGradient, &FEMContext::point_gradient >::get_shape_outputs (FEBase & fe) inline
Definition at line 476 of file generic_projector.h.
References libMesh::FEGenericBase< OutputType >::get_dphi().
 {
   fe.get_dphi();
 }
init_context()
template<typename Output , void(FEMContext::*)(unsigned int, const Point &, Output &, const Real) const point_output> void libMesh::OldSolutionBase< Output, point_output >::init_context (FEMContext & c) inline
Definition at line 237 of file generic_projector.h.
References libMesh::FEMContext::DOFS_ONLY, and libMesh::FEMContext::set_algebraic_type().
   {
     c.set_algebraic_type(FEMContext::DOFS_ONLY);
     // Loop over variables, to prerequest
     for (unsigned int var=0; var!=sys.n_vars(); ++var)
       {
         FEBase * fe = nullptr;
         const std::set<unsigned char> & elem_dims =
           old_context.elem_dimensions();
         for (const auto & dim : elem_dims)
           {
             old_context.get_element_fe(var, fe, dim);
             get_shape_outputs(*fe);
           }
       }
   }
is_grid_projection()
template<typename Output , void(FEMContext::*)(unsigned int, const Point &, Output &, const Real) const point_output> bool libMesh::OldSolutionBase< Output, point_output >::is_grid_projection () inline
Definition at line 256 of file generic_projector.h.
 { return true; }
out_of_elem_tol() [1/4]
template<> const Real libMesh::OldSolutionBase< Number, &FEMContext::point_value >::out_of_elem_tol () protected
Definition at line 565 of file generic_projector.h.
out_of_elem_tol() [2/4]
template<> const Real libMesh::OldSolutionBase< Gradient, &FEMContext::point_gradient >::out_of_elem_tol () protected
Definition at line 568 of file generic_projector.h.
out_of_elem_tol() [3/4]
template<> const Real libMesh::OldSolutionBase< Real, &FEMContext::point_value >::out_of_elem_tol () protected
Definition at line 572 of file generic_projector.h.
out_of_elem_tol() [4/4]
template<> const Real libMesh::OldSolutionBase< RealGradient, &FEMContext::point_gradient >::out_of_elem_tol () protected
Definition at line 575 of file generic_projector.h.
Member Data Documentation
component_to_var
template<typename Output , void(FEMContext::*)(unsigned int, const Point &, Output &, const Real) const point_output> std::vector<unsigned int> libMesh::OldSolutionBase< Output, point_output >::component_to_var protected
Definition at line 363 of file generic_projector.h.
last_elem
template<typename Output , void(FEMContext::*)(unsigned int, const Point &, Output &, const Real) const point_output> const Elem* libMesh::OldSolutionBase< Output, point_output >::last_elem protected
Definition at line 360 of file generic_projector.h.
old_context
template<typename Output , void(FEMContext::*)(unsigned int, const Point &, Output &, const Real) const point_output> FEMContext libMesh::OldSolutionBase< Output, point_output >::old_context protected
Definition at line 362 of file generic_projector.h.
out_of_elem_tol
template<typename Output , void(FEMContext::*)(unsigned int, const Point &, Output &, const Real) const point_output> const Real libMesh::OldSolutionBase< Output, point_output >::out_of_elem_tol static protected
Definition at line 365 of file generic_projector.h.
sys
template<typename Output , void(FEMContext::*)(unsigned int, const Point &, Output &, const Real) const point_output> const System& libMesh::OldSolutionBase< Output, point_output >::sys protected
Definition at line 361 of file generic_projector.h.
The documentation for this class was generated from the following file:
generic_projector.h