libMesh: libMesh::TetGenIO Class Reference
SomeWebsiteLogo
libMesh::TetGenIO Class Reference
#include <tetgen_io.h>
Public Member Functions
TetGenIO (MeshBase &mesh)
TetGenIO (const MeshBase &mesh)
virtual void read (const std::string &) override
virtual void write (const std::string &) override
virtual void write_equation_systems (const std::string &, const EquationSystems &, const std::set< std::string > *system_names=nullptr)
virtual void write_discontinuous_equation_systems (const std::string &, const EquationSystems &, const std::set< std::string > *system_names=nullptr)
virtual void write_nodal_data (const std::string &, const std::vector< Number > &, const std::vector< std::string > &)
virtual void write_nodal_data (const std::string &, const NumericVector< Number > &, const std::vector< std::string > &)
virtual void write_nodal_data_discontinuous (const std::string &, const std::vector< Number > &, const std::vector< std::string > &)
unsigned int & ascii_precision ()
Public Attributes
std::vector< std::vector< Real > > node_attributes
std::vector< std::vector< Real > > element_attributes
Protected Member Functions
MeshBase & mesh ()
void set_n_partitions (unsigned int n_parts)
void skip_comment_lines (std::istream &in, const char comment_start)
const MeshBase & mesh () const
Protected Attributes
std::vector< bool > elems_of_dimension
const bool _is_parallel_format
const bool _serial_only_needed_on_proc_0
Private Member Functions
void read_nodes_and_elem (std::istream &node_stream, std::istream &ele_stream)
void node_in (std::istream &node_stream)
void element_in (std::istream &ele_stream)
Private Attributes
std::map< dof_id_type, dof_id_type > _assign_nodes
dof_id_type _num_nodes
dof_id_type _num_elements
Detailed Description
This class implements reading and writing meshes in the TetGen format. Format description: cf. TetGen home page.
Author
Benjamin S. Kirk
Date
2004
Definition at line 47 of file tetgen_io.h.
Constructor & Destructor Documentation
TetGenIO() [1/2]
libMesh::TetGenIO::TetGenIO (MeshBase & mesh) inline explicit
Constructor. Takes a writable reference to a mesh object. This is the constructor required to read a mesh.
Definition at line 151 of file tetgen_io.h.
                                    :
   MeshInput<MeshBase> (mesh),
   MeshOutput<MeshBase>(mesh)
 {
 }
TetGenIO() [2/2]
libMesh::TetGenIO::TetGenIO (const MeshBase & mesh) inline explicit
Constructor. Takes a read-only reference to a mesh object. This is the constructor required to write a mesh.
Definition at line 160 of file tetgen_io.h.
                                          :
   MeshOutput<MeshBase>(mesh)
 {
 }
Member Function Documentation
ascii_precision()
unsigned int & libMesh::MeshOutput< MeshBase >::ascii_precision () inline inherited
Return/set the precision to use when writing ASCII files.
By default we use numeric_limits<Real>::digits10 + 2, which should be enough to write out to ASCII and get the exact same Real back when reading in.
Definition at line 244 of file mesh_output.h.
Referenced by libMesh::TecplotIO::write_ascii(), libMesh::GMVIO::write_ascii_new_impl(), and libMesh::GMVIO::write_ascii_old_impl().
 {
   return _ascii_precision;
 }
element_in()
void libMesh::TetGenIO::element_in (std::istream & ele_stream) private
Method reads elements and stores them in vector<Elem *> elements in the same order as they come in. Within TetGenMeshInterface, element labels are ignored.
Definition at line 170 of file tetgen_io.C.
References _assign_nodes, _num_elements, libMesh::MeshBase::add_elem(), libMesh::MeshInput< MeshBase >::mesh(), libMesh::MeshInput< MT >::mesh(), n_nodes, and libMesh::MeshBase::node_ptr().
Referenced by read_nodes_and_elem().
 {
   // Check input buffer
   libmesh_assert (ele_stream.good());
   // Get a reference to the mesh
   MeshBase & mesh = MeshInput<MeshBase>::mesh();
   // Read the elements from the ele_stream (*.ele file).
   unsigned int element_lab=0, n_nodes=0, region_attribute=0;
   ele_stream >> _num_elements // Read the number of tetrahedrons from the stream.
              >> n_nodes       // Read the number of nodes per tetrahedron from the stream (defaults to 4).
              >> region_attribute; // Read the number of attributes from stream.
   // According to the Tetgen docs for .ele files:
   // http://wias-berlin.de/software/tetgen/1.5/doc/manual/manual006.html#ff_ele
   // region_attribute can either 0 or 1, and specifies whether, for
   // each tetrahedron, there is an extra integer specifying which
   // region it belongs to. Normally, this id matches a value in a
   // corresponding .poly or .smesh file, but here we simply use it to
   // set the subdomain_id of the element in question.
   if (region_attribute > 1)
     libmesh_error_msg("Invalid region_attribute " << region_attribute << " specified in .ele file.");
   // Vector that assigns element nodes to their correct position.
   // TetGen is normally 0-based
   // (right now this is strictly not necessary since it is the identity map,
   //  but in the future TetGen could change their numbering scheme.)
   static const unsigned int assign_elm_nodes[] = { 0, 1, 2, 3, 4, 5, 6, 7, 8, 9};
   for (dof_id_type i=0; i<_num_elements; i++)
     {
       libmesh_assert (ele_stream.good());
       // TetGen only supports Tet4 and Tet10 elements.
       Elem * elem;
       if (n_nodes==4)
         elem = new Tet4;
       else if (n_nodes==10)
         elem = new Tet10;
       else
         libmesh_error_msg("Elements with " << n_nodes << " nodes are not supported in the LibMesh tetgen module.");
       elem->set_id(i);
       mesh.add_elem (elem);
       libmesh_assert(elem);
       libmesh_assert_equal_to (elem->n_nodes(), n_nodes);
       // The first number on the line is the tetrahedron number. We
       // have previously ignored this, preferring to set our own ids,
       // but this could be changed to respect the Tetgen numbering if
       // desired.
       ele_stream >> element_lab;
       // Read node labels
       for (dof_id_type j=0; j<n_nodes; j++)
         {
           dof_id_type node_label;
           ele_stream >> node_label;
           // Assign node to element
           elem->set_node(assign_elm_nodes[j]) =
             mesh.node_ptr(_assign_nodes[node_label]);
         }
       // Read the region attribute (if present) and use it to set the subdomain id.
       if (region_attribute)
         {
           unsigned int region;
           ele_stream >> region;
           // Make sure that the id we read can be successfully cast to
           // an integral value of type subdomain_id_type.
           elem->subdomain_id() = cast_int<subdomain_id_type>(region);
         }
     }
 }
mesh() [1/2]
MeshBase & libMesh::MeshInput< MeshBase >::mesh () inline protected inherited
Returns
The object as a writable reference.
Definition at line 169 of file mesh_input.h.
Referenced by libMesh::GMVIO::_read_one_cell(), libMesh::VTKIO::cells_to_vtk(), element_in(), libMesh::UNVIO::elements_in(), libMesh::UNVIO::elements_out(), libMesh::UNVIO::groups_in(), node_in(), libMesh::UNVIO::nodes_in(), libMesh::UNVIO::nodes_out(), libMesh::VTKIO::nodes_to_vtk(), libMesh::Nemesis_IO::prepare_to_write_nodal_data(), libMesh::Nemesis_IO::read(), libMesh::ExodusII_IO::read(), libMesh::GMVIO::read(), libMesh::XdrIO::read(), libMesh::CheckpointIO::read(), libMesh::VTKIO::read(), libMesh::CheckpointIO::read_bcs(), libMesh::CheckpointIO::read_connectivity(), libMesh::CheckpointIO::read_header(), libMesh::XdrIO::read_header(), libMesh::UCDIO::read_implementation(), libMesh::UNVIO::read_implementation(), libMesh::GmshIO::read_mesh(), libMesh::CheckpointIO::read_nodes(), libMesh::CheckpointIO::read_nodesets(), libMesh::CheckpointIO::read_remote_elem(), libMesh::XdrIO::read_serialized_bcs_helper(), libMesh::XdrIO::read_serialized_connectivity(), libMesh::XdrIO::read_serialized_nodes(), libMesh::XdrIO::read_serialized_nodesets(), libMesh::XdrIO::read_serialized_subdomain_names(), libMesh::OFFIO::read_stream(), libMesh::MatlabIO::read_stream(), libMesh::CheckpointIO::read_subdomain_names(), write(), libMesh::Nemesis_IO::write(), libMesh::ExodusII_IO::write(), libMesh::XdrIO::write(), libMesh::CheckpointIO::write(), libMesh::GMVIO::write_ascii_new_impl(), libMesh::GMVIO::write_ascii_old_impl(), libMesh::GMVIO::write_binary(), libMesh::GMVIO::write_discontinuous_gmv(), libMesh::Nemesis_IO::write_element_data(), libMesh::ExodusII_IO::write_element_data(), libMesh::UCDIO::write_header(), libMesh::UCDIO::write_implementation(), libMesh::UCDIO::write_interior_elems(), libMesh::GmshIO::write_mesh(), libMesh::VTKIO::write_nodal_data(), libMesh::UCDIO::write_nodal_data(), libMesh::ExodusII_IO::write_nodal_data(), libMesh::ExodusII_IO::write_nodal_data_common(), libMesh::ExodusII_IO::write_nodal_data_discontinuous(), libMesh::UCDIO::write_nodes(), libMesh::CheckpointIO::write_nodesets(), libMesh::XdrIO::write_parallel(), libMesh::GmshIO::write_post(), libMesh::XdrIO::write_serialized_bcs_helper(), libMesh::XdrIO::write_serialized_connectivity(), libMesh::XdrIO::write_serialized_nodes(), libMesh::XdrIO::write_serialized_nodesets(), libMesh::XdrIO::write_serialized_subdomain_names(), libMesh::UCDIO::write_soln(), and libMesh::CheckpointIO::write_subdomain_names().
 {
   if (_obj == nullptr)
     libmesh_error_msg("ERROR: _obj should not be nullptr!");
   return *_obj;
 }
mesh() [2/2]
const MeshBase & libMesh::MeshOutput< MeshBase >::mesh () const inline protected inherited
Returns
The object as a read-only reference.
Definition at line 234 of file mesh_output.h.
Referenced by libMesh::FroIO::write(), libMesh::TecplotIO::write(), libMesh::MEDITIO::write(), libMesh::PostscriptIO::write(), libMesh::EnsightIO::write(), libMesh::TecplotIO::write_ascii(), libMesh::TecplotIO::write_binary(), libMesh::TecplotIO::write_nodal_data(), libMesh::MEDITIO::write_nodal_data(), and libMesh::GnuPlotIO::write_solution().
 {
   libmesh_assert(_obj);
   return *_obj;
 }
node_in()
void libMesh::TetGenIO::node_in (std::istream & node_stream) private
Method reads nodes from node_stream and stores them in vector<Node *> nodes in the order they come in. The original node labels are being stored in the map _assign_nodes in order to assign the elements to the right nodes later.
Definition at line 112 of file tetgen_io.C.
References _assign_nodes, _num_nodes, libMesh::MeshBase::add_point(), libMesh::MeshInput< MT >::mesh(), libMesh::MeshInput< MeshBase >::mesh(), node_attributes, and libMesh::Real.
Referenced by read_nodes_and_elem().
 {
   // Check input buffer
   libmesh_assert (node_stream.good());
   // Get a reference to the mesh
   MeshBase & mesh = MeshInput<MeshBase>::mesh();
   unsigned int dimension=0, nAttributes=0, BoundaryMarkers=0;
   node_stream >> _num_nodes       // Read the number of nodes from the stream
               >> dimension        // Read the dimension from the stream
               >> nAttributes      // Read the number of attributes from stream
               >> BoundaryMarkers; // Read if or not boundary markers are included in *.node (0 or 1)
   // Read the nodal coordinates from the node_stream (*.node file).
   unsigned int node_lab=0;
   Point xyz;
   Real dummy;
   // If present, make room for node attributes to be stored.
   this->node_attributes.resize(nAttributes);
   for (unsigned i=0; i<nAttributes; ++i)
     this->node_attributes[i].resize(_num_nodes);
   for (unsigned int i=0; i<_num_nodes; i++)
     {
       // Check input buffer
       libmesh_assert (node_stream.good());
       node_stream >> node_lab  // node number
                   >> xyz(0)    // x-coordinate value
                   >> xyz(1)    // y-coordinate value
                   >> xyz(2);   // z-coordinate value
       // Read and store attributes from the stream.
       for (unsigned int j=0; j<nAttributes; j++)
         node_stream >> node_attributes[j][i];
       // Read (and discard) boundary marker if BoundaryMarker=1.
       // TODO: should we store this somehow?
       if (BoundaryMarkers == 1)
         node_stream >> dummy;
       // Store the new position of the node under its label.
       //_assign_nodes.insert (std::make_pair(node_lab,i));
       _assign_nodes[node_lab] = i;
       // Add this point to the Mesh.
       mesh.add_point(xyz, i);
     }
 }
read()
void libMesh::TetGenIO::read (const std::string & name) override virtual
This method implements reading a mesh from a specified file in TetGen format.
Implements libMesh::MeshInput< MeshBase >.
Definition at line 33 of file tetgen_io.C.
References libMesh::MeshInput< MT >::mesh(), libMesh::Quality::name(), libMesh::out, read_nodes_and_elem(), and libMesh::MeshInput< MeshBase >::skip_comment_lines().
Referenced by libMesh::NameBasedIO::read().
 {
   // This is a serial-only process for now;
   // the Mesh should be read on processor 0 and
   // broadcast later
   libmesh_assert_equal_to (MeshOutput<MeshBase>::mesh().processor_id(), 0);
   std::string name_node, name_ele, dummy;
   // tetgen only works in 3D
   MeshInput<MeshBase>::mesh().set_mesh_dimension(3);
 #if LIBMESH_DIM < 3
   libmesh_error_msg("Cannot open dimension 3 mesh file when configured without 3D support.");
 #endif
   // Check name for *.node or *.ele extension.
   // Set std::istream for node_stream and ele_stream.
   //
   if (name.rfind(".node") < name.size())
     {
       name_node            = name;
       dummy                = name;
       std::size_t position = dummy.rfind(".node");
       name_ele             = dummy.replace(position, 5, ".ele");
     }
   else if (name.rfind(".ele") < name.size())
     {
       name_ele = name;
       dummy    = name;
       std::size_t position = dummy.rfind(".ele");
       name_node    = dummy.replace(position, 4, ".node");
     }
   else
     libmesh_error_msg("ERROR: Unrecognized file name: " << name);
   // Set the streams from which to read in
   std::ifstream node_stream (name_node.c_str());
   std::ifstream ele_stream  (name_ele.c_str());
   if (!node_stream.good() || !ele_stream.good())
     libmesh_error_msg("Error while opening either "     \
                       << name_node                      \
                       << " or "                         \
                       << name_ele);
   libMesh::out<< "TetGenIO found the tetgen files to read " <<std::endl;
   // Skip the comment lines at the beginning
   this->skip_comment_lines (node_stream, '#');
   this->skip_comment_lines (ele_stream, '#');
   // Read the nodes and elements from the streams
   this->read_nodes_and_elem (node_stream, ele_stream);
   libMesh::out<< "TetGenIO read in nodes and elements " <<std::endl;
 }
read_nodes_and_elem()
void libMesh::TetGenIO::read_nodes_and_elem (std::istream & node_stream, std::istream & ele_stream) private
Reads a mesh (nodes & elements) from the file provided through node_stream and ele_stream.
Definition at line 94 of file tetgen_io.C.
References _assign_nodes, _num_elements, _num_nodes, element_in(), and node_in().
Referenced by read().
 {
   _num_nodes    = 0;
   _num_elements = 0;
   // Read all the datasets.
   this->node_in    (node_stream);
   this->element_in (ele_stream);
   // some more clean-up
   _assign_nodes.clear();
 }
set_n_partitions()
void libMesh::MeshInput< MeshBase >::set_n_partitions (unsigned int n_parts) inline protected inherited
Sets the number of partitions in the mesh. Typically this gets done by the partitioner, but some parallel file formats begin "pre-partitioned".
Definition at line 91 of file mesh_input.h.
References libMesh::MeshInput< MT >::mesh().
Referenced by libMesh::Nemesis_IO::read(), and libMesh::XdrIO::read_header().
 { this->mesh().set_n_partitions() = n_parts; }
skip_comment_lines()
void libMesh::MeshInput< MeshBase >::skip_comment_lines (std::istream & in, const char comment_start) protected inherited
Reads input from in, skipping all the lines that start with the character comment_start.
Definition at line 179 of file mesh_input.h.
Referenced by read(), and libMesh::UCDIO::read_implementation().
 {
   char c, line[256];
   while (in.get(c), c==comment_start)
     in.getline (line, 255);
   // put back first character of
   // first non-comment line
   in.putback (c);
 }
write()
void libMesh::TetGenIO::write (const std::string & fname) override virtual
This method implements writing a mesh to a specified ".poly" file. ".poly" files defines so called Piecewise Linear Complex (PLC).
Implements libMesh::MeshOutput< MeshBase >.
Definition at line 259 of file tetgen_io.C.
References libMesh::MeshBase::active_element_ptr_range(), libMesh::MeshInput< MeshBase >::mesh(), libMesh::MeshOutput< MT >::mesh(), libMesh::MeshBase::n_elem(), libMesh::MeshBase::n_nodes(), and libMesh::MeshBase::point().
Referenced by libMesh::NameBasedIO::write().
 {
   // libmesh_assert three dimensions (should be extended later)
   libmesh_assert_equal_to (MeshOutput<MeshBase>::mesh().mesh_dimension(), 3);
   if (!(fname.rfind(".poly") < fname.size()))
     libmesh_error_msg("ERROR: Unrecognized file name: " << fname);
   // Open the output file stream
   std::ofstream out_stream (fname.c_str());
   // Make sure it opened correctly
   if (!out_stream.good())
     libmesh_file_error(fname.c_str());
   // Get a reference to the mesh
   const MeshBase & mesh = MeshOutput<MeshBase>::mesh();
   // Begin interfacing with the .poly file
   {
     // header:
     out_stream << "# poly file output generated by libmesh\n"
                << mesh.n_nodes() << " 3 0 0\n";
     // write the nodes:
     for (dof_id_type v=0; v<mesh.n_nodes(); v++)
       out_stream << v << " "
                  << mesh.point(v)(0) << " "
                  << mesh.point(v)(1) << " "
                  << mesh.point(v)(2) << "\n";
   }
   {
     // write the connectivity:
     out_stream << "# Facets:\n"
                << mesh.n_elem() << " 0\n";
     for (const auto & elem : mesh.active_element_ptr_range())
       out_stream << "1\n3 " // no. of facet polygons
         //  << elem->n_nodes() << " "
                  << elem->node_id(0)   << " "
                  << elem->node_id(1)   << " "
                  << elem->node_id(2)   << "\n";
   }
   // end of the file
   out_stream << "0\n"; // no holes output!
   out_stream << "\n\n# end of file\n";
 }
write_discontinuous_equation_systems()
void libMesh::MeshOutput< MeshBase >::write_discontinuous_equation_systems (const std::string & fname, const EquationSystems & es, const std::set< std::string > * system_names = nullptr) virtual inherited
This method implements writing a mesh with discontinuous data to a specified file where the data is taken from the EquationSystems object.
Definition at line 92 of file mesh_output.C.
References libMesh::EquationSystems::build_discontinuous_solution_vector(), libMesh::EquationSystems::build_variable_names(), libMesh::EquationSystems::get_mesh(), and libMesh::out.
Referenced by libMesh::ExodusII_IO::write_timestep_discontinuous().
 {
   LOG_SCOPE("write_discontinuous_equation_systems()", "MeshOutput");
   // We may need to gather and/or renumber a DistributedMesh to output
   // it, making that const qualifier in our constructor a dirty lie
   MT & my_mesh = const_cast<MT &>(*_obj);
   // If we're asked to write data that's associated with a different
   // mesh, output files full of garbage are the result.
   libmesh_assert_equal_to(&es.get_mesh(), _obj);
   // A non-renumbered mesh may not have a contiguous numbering, and
   // that needs to be fixed before we can build a solution vector.
   if (my_mesh.max_elem_id() != my_mesh.n_elem() ||
       my_mesh.max_node_id() != my_mesh.n_nodes())
     {
       // If we were allowed to renumber then we should have already
       // been properly renumbered...
       libmesh_assert(!my_mesh.allow_renumbering());
       libmesh_do_once(libMesh::out <<
                       "Warning:  This MeshOutput subclass only supports meshes which are contiguously renumbered!"
                       << std::endl;);
       my_mesh.allow_renumbering(true);
       my_mesh.renumber_nodes_and_elements();
       // Not sure what good going back to false will do here, the
       // renumbering horses have already left the barn...
       my_mesh.allow_renumbering(false);
     }
   MeshSerializer serialize(const_cast<MT &>(*_obj), !_is_parallel_format, _serial_only_needed_on_proc_0);
   // Build the list of variable names that will be written.
   std::vector<std::string> names;
   es.build_variable_names  (names, nullptr, system_names);
   if (!_is_parallel_format)
     {
       // Build the nodal solution values & get the variable
       // names from the EquationSystems object
       std::vector<Number> soln;
       es.build_discontinuous_solution_vector (soln, system_names);
       this->write_nodal_data_discontinuous (fname, soln, names);
     }
   else // _is_parallel_format
     {
       libmesh_not_implemented();
     }
 }
write_equation_systems()
void libMesh::MeshOutput< MeshBase >::write_equation_systems (const std::string & fname, const EquationSystems & es, const std::set< std::string > * system_names = nullptr) virtual inherited
This method implements writing a mesh with data to a specified file where the data is taken from the EquationSystems object.
Reimplemented in libMesh::NameBasedIO.
Definition at line 31 of file mesh_output.C.
References libMesh::EquationSystems::build_parallel_solution_vector(), libMesh::EquationSystems::build_solution_vector(), libMesh::EquationSystems::build_variable_names(), libMesh::EquationSystems::get_mesh(), and libMesh::out.
Referenced by libMesh::Nemesis_IO::write_timestep(), and libMesh::ExodusII_IO::write_timestep().
 {
   LOG_SCOPE("write_equation_systems()", "MeshOutput");
   // We may need to gather and/or renumber a DistributedMesh to output
   // it, making that const qualifier in our constructor a dirty lie
   MT & my_mesh = const_cast<MT &>(*_obj);
   // If we're asked to write data that's associated with a different
   // mesh, output files full of garbage are the result.
   libmesh_assert_equal_to(&es.get_mesh(), _obj);
   // A non-renumbered mesh may not have a contiguous numbering, and
   // that needs to be fixed before we can build a solution vector.
   if (my_mesh.max_elem_id() != my_mesh.n_elem() ||
       my_mesh.max_node_id() != my_mesh.n_nodes())
     {
       // If we were allowed to renumber then we should have already
       // been properly renumbered...
       libmesh_assert(!my_mesh.allow_renumbering());
       libmesh_do_once(libMesh::out <<
                       "Warning:  This MeshOutput subclass only supports meshes which are contiguously renumbered!"
                       << std::endl;);
       my_mesh.allow_renumbering(true);
       my_mesh.renumber_nodes_and_elements();
       // Not sure what good going back to false will do here, the
       // renumbering horses have already left the barn...
       my_mesh.allow_renumbering(false);
     }
   MeshSerializer serialize(const_cast<MT &>(*_obj), !_is_parallel_format, _serial_only_needed_on_proc_0);
   // Build the list of variable names that will be written.
   std::vector<std::string> names;
   es.build_variable_names  (names, nullptr, system_names);
   if (!_is_parallel_format)
     {
       // Build the nodal solution values & get the variable
       // names from the EquationSystems object
       std::vector<Number> soln;
       es.build_solution_vector (soln, system_names);
       this->write_nodal_data (fname, soln, names);
     }
   else // _is_parallel_format
     {
       std::unique_ptr<NumericVector<Number>> parallel_soln =
         es.build_parallel_solution_vector(system_names);
       this->write_nodal_data (fname, *parallel_soln, names);
     }
 }
write_nodal_data() [1/2]
virtual void libMesh::MeshOutput< MeshBase >::write_nodal_data (const std::string & , const std::vector< Number > & , const std::vector< std::string > &) inline virtual inherited
This method implements writing a mesh with nodal data to a specified file where the nodal data and variable names are provided.
Reimplemented in libMesh::ExodusII_IO, libMesh::Nemesis_IO, libMesh::UCDIO, libMesh::NameBasedIO, libMesh::GmshIO, libMesh::GMVIO, libMesh::VTKIO, libMesh::MEDITIO, libMesh::GnuPlotIO, and libMesh::TecplotIO.
Definition at line 105 of file mesh_output.h.
   { libmesh_not_implemented(); }
write_nodal_data() [2/2]
void libMesh::MeshOutput< MeshBase >::write_nodal_data (const std::string & fname, const NumericVector< Number > & parallel_soln, const std::vector< std::string > & names) virtual inherited
This method should be overridden by "parallel" output formats for writing nodal data. Instead of getting a localized copy of the nodal solution vector, it is passed a NumericVector of type=PARALLEL which is in node-major order i.e. (u0,v0,w0, u1,v1,w1, u2,v2,w2, u3,v3,w3, ...) and contains n_nodes*n_vars total entries. Then, it is up to the individual I/O class to extract the required solution values from this vector and write them in parallel.
If not implemented, localizes the parallel vector into a std::vector and calls the other version of this function.
Reimplemented in libMesh::Nemesis_IO.
Definition at line 150 of file mesh_output.C.
References libMesh::NumericVector< T >::localize().
 {
   // This is the fallback implementation for parallel I/O formats that
   // do not yet implement proper writing in parallel, and instead rely
   // on the full solution vector being available on all processors.
   std::vector<Number> soln;
   parallel_soln.localize(soln);
   this->write_nodal_data(fname, soln, names);
 }
write_nodal_data_discontinuous()
virtual void libMesh::MeshOutput< MeshBase >::write_nodal_data_discontinuous (const std::string & , const std::vector< Number > & , const std::vector< std::string > &) inline virtual inherited
This method implements writing a mesh with discontinuous data to a specified file where the nodal data and variables names are provided.
Reimplemented in libMesh::ExodusII_IO.
Definition at line 114 of file mesh_output.h.
   { libmesh_not_implemented(); }
Member Data Documentation
_assign_nodes
std::map<dof_id_type,dof_id_type> libMesh::TetGenIO::_assign_nodes private
stores new positions of nodes. Used when reading.
Definition at line 133 of file tetgen_io.h.
Referenced by element_in(), node_in(), and read_nodes_and_elem().
_is_parallel_format
const bool libMesh::MeshOutput< MeshBase >::_is_parallel_format protected inherited
Flag specifying whether this format is parallel-capable. If this is false (default) I/O is only permitted when the mesh has been serialized.
Definition at line 159 of file mesh_output.h.
Referenced by libMesh::FroIO::write(), libMesh::PostscriptIO::write(), and libMesh::EnsightIO::write().
_num_elements
dof_id_type libMesh::TetGenIO::_num_elements private
total number of elements. Primarily used when reading.
Definition at line 143 of file tetgen_io.h.
Referenced by element_in(), and read_nodes_and_elem().
_num_nodes
dof_id_type libMesh::TetGenIO::_num_nodes private
total number of nodes. Primarily used when reading.
Definition at line 138 of file tetgen_io.h.
Referenced by node_in(), and read_nodes_and_elem().
_serial_only_needed_on_proc_0
const bool libMesh::MeshOutput< MeshBase >::_serial_only_needed_on_proc_0 protected inherited
Flag specifying whether this format can be written by only serializing the mesh to processor zero
If this is false (default) the mesh will be serialized to all processors
Definition at line 168 of file mesh_output.h.
element_attributes
std::vector<std::vector<Real> > libMesh::TetGenIO::element_attributes
Data structure to hold element attributes read in from file.
Note
This vector is no longer filled or used for anything. If region attributes are present in the .ele file, they are used to set the subdomain ids of the elements as they are created.
Deprecated:
This member, since it was originally a part of the public interface, remains for now, but will be removed some time in the near future.
Definition at line 95 of file tetgen_io.h.
elems_of_dimension
std::vector<bool> libMesh::MeshInput< MeshBase >::elems_of_dimension protected inherited
A vector of bools describing what dimension elements have been encountered when reading a mesh.
Definition at line 97 of file mesh_input.h.
Referenced by libMesh::GMVIO::_read_one_cell(), libMesh::UNVIO::elements_in(), libMesh::UNVIO::max_elem_dimension_seen(), libMesh::AbaqusIO::max_elem_dimension_seen(), libMesh::AbaqusIO::read(), libMesh::Nemesis_IO::read(), libMesh::ExodusII_IO::read(), libMesh::GMVIO::read(), libMesh::VTKIO::read(), libMesh::AbaqusIO::read_elements(), libMesh::UCDIO::read_implementation(), libMesh::UNVIO::read_implementation(), and libMesh::XdrIO::read_serialized_connectivity().
node_attributes
std::vector<std::vector<Real> > libMesh::TetGenIO::node_attributes
Data structure to hold node attributes read in from file. What you do with these is up to you!
Definition at line 82 of file tetgen_io.h.
Referenced by node_in().
The documentation for this class was generated from the following files:
tetgen_io.h
tetgen_io.C