libMesh: libMesh::QoISet Class Reference
SomeWebsiteLogo
libMesh::QoISet Class Reference
Used to specify quantities of interest in a simulation.
#include <qoi_set.h>
Classes
class iterator
Public Member Functions
QoISet ()
QoISet (const System &sys)
QoISet (const std::vector< bool > &indices)
QoISet (const std::vector< unsigned int > &indices)
void clear ()
unsigned int size (const System &sys) const
void add_indices (const std::vector< unsigned int > &indices)
void add_index (unsigned int)
void remove_indices (const std::vector< unsigned int > &indices)
void remove_index (unsigned int)
void set_weight (unsigned int, Real)
Real weight (unsigned int) const
bool has_index (unsigned int) const
iterator begin () const
Private Attributes
std::vector< bool > _indices
std::vector< Real > _weights
Detailed Description
Used to specify quantities of interest in a simulation.
Data structure for specifying which Quantities of Interest should be calculated in an adjoint or a parameter sensitivity calculation.
Author
Roy Stogner
Date
2009
Definition at line 45 of file qoi_set.h.
Constructor & Destructor Documentation
libMesh::QoISet::QoISet () inline
Empty constructor: "calculate all QoIs in the System"
No further changes to this special QoISet should be made; it doesn't even know how many QoIs your system has, it just knows to instruct a function to use all of them.
Definition at line 97 of file qoi_set.h.
References libMesh::sys.
Referenced by QoISet().
 : _indices(), _weights() {}
libMesh::QoISet::QoISet (const System & sys) explicit
Default constructor: "calculate all QoIs in the System", "give every QoI weight 1.0"
Definition at line 31 of file qoi_set.C.
 : _indices(sys.qoi.size(), true) {}
libMesh::QoISet::QoISet (const std::vector< bool > & indices) inline explicit
Constructor-from-vector-of-bool: "calculate the QoIs for which \p indices[q] is true"
Definition at line 111 of file qoi_set.h.
References QoISet().
                                           :
     _indices(indices), _weights() {}
libMesh::QoISet::QoISet (const std::vector< unsigned int > & indices) inline explicit
Constructor-from-vector: "calculate the listed QoIs", "give every QoI weight 1.0"
Definition at line 192 of file qoi_set.h.
References add_indices().
                                                       :
   _indices(), _weights()
 {
   this->add_indices(indices);
 }
Member Function Documentation
void libMesh::QoISet::add_index (unsigned int i) inline
Add this index to the set to be calculated
Definition at line 201 of file qoi_set.h.
References _indices.
Referenced by clear().
 {
   if (i >= _indices.size())
     _indices.resize(i+1, true);
   _indices[i] = true;
 }
void libMesh::QoISet::add_indices (const std::vector< unsigned int > & indices)
Add this indices to the set to be calculated
Definition at line 46 of file qoi_set.C.
References _indices, and std::max().
Referenced by clear(), and QoISet().
 {
   unsigned int max_size = 0;
   for (std::vector<unsigned int>::const_iterator i = indices.begin();
        i != indices.end(); ++i)
     max_size = std::max(max_size, *i + 1);
   _indices.resize(max_size);
   for (std::vector<unsigned int>::const_iterator i = indices.begin();
        i != indices.end(); ++i)
     _indices[*i] = true;
 }
iterator libMesh::QoISet::begin () const inline
Return an iterator pointing to the first index in the set
Definition at line 170 of file qoi_set.h.
References _indices, and libMesh::QoISet::iterator::iterator().
 { return iterator(0, _indices); }
void libMesh::QoISet::clear () inline
Resets to "calculate all QoIs, give every QoI weight 1.0"
Definition at line 124 of file qoi_set.h.
References _indices, _weights, add_index(), add_indices(), has_index(), libMesh::Real, remove_index(), remove_indices(), set_weight(), size(), and weight().
 { _indices.clear(); _weights.clear(); }
bool libMesh::QoISet::has_index (unsigned int i) const inline
Return whether or not this index is in the set to be calculated
Definition at line 221 of file qoi_set.h.
References _indices.
Referenced by libMesh::ImplicitSystem::adjoint_qoi_parameter_sensitivity(), libMesh::ImplicitSystem::adjoint_solve(), libMesh::SensitivityData::allocate_data(), libMesh::SensitivityData::allocate_hessian_data(), libMesh::ExplicitSystem::assemble_qoi(), libMesh::FEMSystem::assemble_qoi(), libMesh::ExplicitSystem::assemble_qoi_derivative(), libMesh::FEMSystem::assemble_qoi_derivative(), clear(), libMesh::AdjointRefinementEstimator::estimate_error(), libMesh::AdjointResidualErrorEstimator::estimate_error(), libMesh::ImplicitSystem::forward_qoi_parameter_sensitivity(), libMesh::ImplicitSystem::qoi_parameter_hessian(), libMesh::ImplicitSystem::qoi_parameter_hessian_vector_product(), size(), and libMesh::ImplicitSystem::weighted_sensitivity_adjoint_solve().
 {
   return (_indices.size() <= i || _indices[i]);
 }
void libMesh::QoISet::remove_index (unsigned int i) inline
Remove this index from the set to be calculated
Definition at line 211 of file qoi_set.h.
References _indices.
Referenced by clear().
 {
   if (i >= _indices.size())
     _indices.resize(i+1, true);
   _indices[i] = false;
 }
void libMesh::QoISet::remove_indices (const std::vector< unsigned int > & indices) inline
Remove these indices from the set to be calculated
Definition at line 63 of file qoi_set.C.
References _indices.
Referenced by clear().
 {
   for (std::vector<unsigned int>::const_iterator i = indices.begin();
        i != indices.end(); ++i)
     _indices[*i] = false;
 }
void libMesh::QoISet::set_weight (unsigned int i, Real w) inline
Set the weight for this index
Definition at line 229 of file qoi_set.h.
References _weights.
Referenced by clear().
 {
   if (_weights.size() <= i)
     _weights.resize(i+1, 1.0);
   _weights[i] = w;
 }
unsigned int libMesh::QoISet::size (const System & sys) const
Returns
The number of QoIs that would be computed for the System sys
Definition at line 35 of file qoi_set.C.
References has_index(), and libMesh::System::qoi.
Referenced by clear(), and libMesh::System::qoi_parameter_sensitivity().
 {
   unsigned int qoi_count = 0;
   for (std::size_t i=0; i != sys.qoi.size(); ++i)
     if (this->has_index(i))
       qoi_count++;
   return qoi_count;
 }
Real libMesh::QoISet::weight (unsigned int i) const inline
Get the weight for this index (default 1.0)
Definition at line 240 of file qoi_set.h.
References _weights.
Referenced by clear(), libMesh::AdjointRefinementEstimator::estimate_error(), and libMesh::AdjointResidualErrorEstimator::estimate_error().
 {
   if (_weights.size() <= i)
     return 1.0;
   return _weights[i];
 }
Member Data Documentation
std::vector<bool> libMesh::QoISet::_indices private
Interpret _indices.empty() to mean "calculate all indices"
Definition at line 176 of file qoi_set.h.
Referenced by add_index(), add_indices(), begin(), clear(), has_index(), remove_index(), and remove_indices().
std::vector<Real> libMesh::QoISet::_weights private
Interpret _weights.size() <= i to mean "weight i = 1.0"
Definition at line 181 of file qoi_set.h.
Referenced by clear(), set_weight(), and weight().
The documentation for this class was generated from the following files:
qoi_set.h
qoi_set.C