libMesh: libMesh::Parallel::StandardType< TensorValue< T > > Class Template Reference
SomeWebsiteLogo
libMesh::Parallel::StandardType< TensorValue< T > > Class Template Reference
#include <parallel_algebra.h>
Public Member Functions
StandardType (const TensorValue< T > *example=NULL)
~StandardType ()
operator const data_type & () const
operator data_type & ()
void commit ()
void free ()
Protected Attributes
data_type _datatype
Detailed Description
template<typename T>
class libMesh::Parallel::StandardType< TensorValue< T > >
Definition at line 311 of file parallel_algebra.h.
Constructor & Destructor Documentation
template<typename T > libMesh::Parallel::StandardType< TensorValue< T > >::StandardType (const TensorValue< T > * example = NULL) inline explicit
Definition at line 315 of file parallel_algebra.h.
                                                    :
     DataType(StandardType<T>(example ?  &((*example)(0,0)) : NULL), LIBMESH_DIM*LIBMESH_DIM) {}
template<typename T > libMesh::Parallel::StandardType< TensorValue< T > >::~StandardType () inline
Definition at line 318 of file parallel_algebra.h.
References libMesh::Parallel::DataType::free().
 { this->free(); }
Member Function Documentation
void libMesh::Parallel::DataType::commit () inline inherited
Definition at line 278 of file parallel.h.
References libMesh::Parallel::DataType::_datatype.
Referenced by libMesh::Parallel::DataType::DataType().
   {
 #ifdef LIBMESH_HAVE_MPI
     MPI_Type_commit (&_datatype);
 #endif
   }
void libMesh::Parallel::DataType::free () inline inherited
Definition at line 285 of file parallel.h.
References libMesh::Parallel::DataType::_datatype.
Referenced by libMesh::Parallel::StandardType< std::pair< T1, T2 > >::~StandardType(), libMesh::Parallel::StandardType< std::complex< T > >::~StandardType(), libMesh::Parallel::StandardType< TypeTensor< T > >::~StandardType(), and ~StandardType().
   {
 #ifdef LIBMESH_HAVE_MPI
     MPI_Type_free (&_datatype);
 #endif
   }
libMesh::Parallel::DataType::operator const data_type & () const inline inherited
Definition at line 266 of file parallel.h.
References libMesh::Parallel::DataType::_datatype.
   { return _datatype; }
libMesh::Parallel::DataType::operator data_type & () inline inherited
Definition at line 269 of file parallel.h.
References libMesh::Parallel::DataType::_datatype.
   { return _datatype; }
Member Data Documentation
data_type libMesh::Parallel::DataType::_datatype protected inherited
Definition at line 294 of file parallel.h.
Referenced by libMesh::Parallel::DataType::commit(), libMesh::Parallel::DataType::DataType(), libMesh::Parallel::DataType::free(), libMesh::Parallel::DataType::operator const data_type &(), libMesh::Parallel::DataType::operator data_type &(), libMesh::Parallel::DataType::operator=(), libMesh::Parallel::StandardType< Hilbert::HilbertIndices >::StandardType(), libMesh::Parallel::StandardType< TypeVector< T > >::StandardType(), libMesh::Parallel::StandardType< std::pair< T1, T2 > >::StandardType(), libMesh::Parallel::StandardType< VectorValue< T > >::StandardType(), and libMesh::Parallel::StandardType< Point >::StandardType().
The documentation for this class was generated from the following file:
parallel_algebra.h