libMesh: libMesh::MeshOutput< MT > Class Template Reference
SomeWebsiteLogo
libMesh::MeshOutput< MT > Class Template Reference abstract
#include <mesh_output.h>
Public Member Functions
virtual ~MeshOutput ()
virtual void write (const std::string &)=0
virtual void write_equation_systems (const std::string &, const EquationSystems &, const std::set< std::string > *system_names=nullptr)
virtual void write_discontinuous_equation_systems (const std::string &, const EquationSystems &, const std::set< std::string > *system_names=nullptr)
virtual void write_nodal_data (const std::string &, const std::vector< Number > &, const std::vector< std::string > &)
virtual void write_nodal_data_discontinuous (const std::string &, const std::vector< Number > &, const std::vector< std::string > &)
virtual void write_nodal_data (const std::string &, const NumericVector< Number > &, const std::vector< std::string > &)
unsigned int & ascii_precision ()
Protected Member Functions
MeshOutput (const bool is_parallel_format=false, const bool serial_only_needed_on_proc_0=false)
MeshOutput (const MT &, const bool is_parallel_format=false, const bool serial_only_needed_on_proc_0=false)
const MT & mesh () const
Protected Attributes
const bool _is_parallel_format
const bool _serial_only_needed_on_proc_0
Private Attributes
const MT *const _obj
unsigned int _ascii_precision
Detailed Description
template<class MT>
class libMesh::MeshOutput< MT >
This class defines an abstract interface for Mesh output. Specific classes derived from this class actually implement writing various mesh formats.
Author
Benjamin S. Kirk
Date
2004
Definition at line 53 of file mesh_output.h.
Constructor & Destructor Documentation
MeshOutput() [1/2]
template<class MT > libMesh::MeshOutput< MT >::MeshOutput (const bool is_parallel_format = false, const bool serial_only_needed_on_proc_0 = false) inline explicit protected
Default constructor. Will set the _obj to nullptr, effectively rendering this object useless.
Definition at line 194 of file mesh_output.h.
                                                                                                   :
   _is_parallel_format(is_parallel_format),
   _serial_only_needed_on_proc_0(serial_only_needed_on_proc_0),
   _obj(nullptr),
   _ascii_precision (std::numeric_limits<Real>::digits10 + 2)
 {}
MeshOutput() [2/2]
template<class MT> libMesh::MeshOutput< MT >::MeshOutput (const MT & obj, const bool is_parallel_format = false, const bool serial_only_needed_on_proc_0 = false) inline explicit protected
Constructor. Takes a reference to a constant object. This constructor will only allow us to write the object.
Definition at line 205 of file mesh_output.h.
                                                                                                                   :
   _is_parallel_format(is_parallel_format),
   _serial_only_needed_on_proc_0(serial_only_needed_on_proc_0),
   _obj (&obj),
   _ascii_precision (std::numeric_limits<Real>::digits10 + 2)
 {
   if (!_is_parallel_format && !this->mesh().is_serial())
     {
       if (this->mesh().processor_id() == 0)
         {
           libmesh_do_once(libMesh::out <<
                           "Warning:  This MeshOutput subclass only supports meshes which have been serialized!"
                           << std::endl;);
         }
     }
 }
~MeshOutput()
template<class MT > libMesh::MeshOutput< MT >::~MeshOutput () inline virtual
Destructor.
Definition at line 226 of file mesh_output.h.
 {
 }
Member Function Documentation
ascii_precision()
template<class MT > unsigned int & libMesh::MeshOutput< MT >::ascii_precision () inline
Return/set the precision to use when writing ASCII files.
By default we use numeric_limits<Real>::digits10 + 2, which should be enough to write out to ASCII and get the exact same Real back when reading in.
Definition at line 244 of file mesh_output.h.
 {
   return _ascii_precision;
 }
mesh()
template<class MT > const MT & libMesh::MeshOutput< MT >::mesh () const inline protected
Returns
The object as a read-only reference.
Definition at line 234 of file mesh_output.h.
Referenced by libMesh::VTKIO::cells_to_vtk(), libMesh::TecplotIO::elem_dimension(), libMesh::UNVIO::elements_out(), libMesh::UNVIO::nodes_out(), libMesh::VTKIO::nodes_to_vtk(), libMesh::Nemesis_IO::prepare_to_write_nodal_data(), libMesh::FroIO::write(), libMesh::PostscriptIO::write(), libMesh::TetGenIO::write(), libMesh::Nemesis_IO::write(), libMesh::ExodusII_IO::write(), libMesh::XdrIO::write(), libMesh::CheckpointIO::write(), libMesh::MEDITIO::write_ascii(), libMesh::TecplotIO::write_ascii(), libMesh::GMVIO::write_ascii_new_impl(), libMesh::GMVIO::write_ascii_old_impl(), libMesh::TecplotIO::write_binary(), libMesh::GMVIO::write_binary(), libMesh::GMVIO::write_discontinuous_gmv(), libMesh::Nemesis_IO::write_element_data(), libMesh::ExodusII_IO::write_element_data(), libMesh::EnsightIO::write_geometry_ascii(), libMesh::UCDIO::write_implementation(), libMesh::GmshIO::write_mesh(), libMesh::VTKIO::write_nodal_data(), libMesh::UCDIO::write_nodal_data(), libMesh::ExodusII_IO::write_nodal_data(), libMesh::ExodusII_IO::write_nodal_data_common(), libMesh::ExodusII_IO::write_nodal_data_discontinuous(), libMesh::CheckpointIO::write_nodesets(), libMesh::XdrIO::write_parallel(), libMesh::GmshIO::write_post(), libMesh::EnsightIO::write_scalar_ascii(), libMesh::XdrIO::write_serialized_bcs_helper(), libMesh::XdrIO::write_serialized_connectivity(), libMesh::XdrIO::write_serialized_nodes(), libMesh::XdrIO::write_serialized_nodesets(), libMesh::XdrIO::write_serialized_subdomain_names(), libMesh::GnuPlotIO::write_solution(), libMesh::CheckpointIO::write_subdomain_names(), and libMesh::EnsightIO::write_vector_ascii().
 {
   libmesh_assert(_obj);
   return *_obj;
 }
write()
template<class MT> virtual void libMesh::MeshOutput< MT >::write (const std::string &) pure virtual
This method implements writing a mesh to a specified file.
Implemented in libMesh::EnsightIO, libMesh::CheckpointIO, libMesh::VTKIO, libMesh::XdrIO, libMesh::UCDIO, libMesh::ExodusII_IO, libMesh::UNVIO, libMesh::GmshIO, libMesh::Nemesis_IO, libMesh::GMVIO, libMesh::TetGenIO, libMesh::NameBasedIO, libMesh::PostscriptIO, libMesh::MEDITIO, libMesh::GnuPlotIO, libMesh::TecplotIO, and libMesh::FroIO.
write_discontinuous_equation_systems()
template<class MT > void libMesh::MeshOutput< MT >::write_discontinuous_equation_systems (const std::string & fname, const EquationSystems & es, const std::set< std::string > * system_names = nullptr) virtual
This method implements writing a mesh with discontinuous data to a specified file where the data is taken from the EquationSystems object.
Definition at line 92 of file mesh_output.C.
 {
   LOG_SCOPE("write_discontinuous_equation_systems()", "MeshOutput");
   // We may need to gather and/or renumber a DistributedMesh to output
   // it, making that const qualifier in our constructor a dirty lie
   MT & my_mesh = const_cast<MT &>(*_obj);
   // If we're asked to write data that's associated with a different
   // mesh, output files full of garbage are the result.
   libmesh_assert_equal_to(&es.get_mesh(), _obj);
   // A non-renumbered mesh may not have a contiguous numbering, and
   // that needs to be fixed before we can build a solution vector.
   if (my_mesh.max_elem_id() != my_mesh.n_elem() ||
       my_mesh.max_node_id() != my_mesh.n_nodes())
     {
       // If we were allowed to renumber then we should have already
       // been properly renumbered...
       libmesh_assert(!my_mesh.allow_renumbering());
       libmesh_do_once(libMesh::out <<
                       "Warning:  This MeshOutput subclass only supports meshes which are contiguously renumbered!"
                       << std::endl;);
       my_mesh.allow_renumbering(true);
       my_mesh.renumber_nodes_and_elements();
       // Not sure what good going back to false will do here, the
       // renumbering horses have already left the barn...
       my_mesh.allow_renumbering(false);
     }
   MeshSerializer serialize(const_cast<MT &>(*_obj), !_is_parallel_format, _serial_only_needed_on_proc_0);
   // Build the list of variable names that will be written.
   std::vector<std::string> names;
   es.build_variable_names  (names, nullptr, system_names);
   if (!_is_parallel_format)
     {
       // Build the nodal solution values & get the variable
       // names from the EquationSystems object
       std::vector<Number> soln;
       es.build_discontinuous_solution_vector (soln, system_names);
       this->write_nodal_data_discontinuous (fname, soln, names);
     }
   else // _is_parallel_format
     {
       libmesh_not_implemented();
     }
 }
write_equation_systems()
template<class MT > void libMesh::MeshOutput< MT >::write_equation_systems (const std::string & fname, const EquationSystems & es, const std::set< std::string > * system_names = nullptr) virtual
This method implements writing a mesh with data to a specified file where the data is taken from the EquationSystems object.
Reimplemented in libMesh::NameBasedIO.
Definition at line 31 of file mesh_output.C.
Referenced by libMesh::ErrorVector::plot_error(), and libMesh::NameBasedIO::write_equation_systems().
 {
   LOG_SCOPE("write_equation_systems()", "MeshOutput");
   // We may need to gather and/or renumber a DistributedMesh to output
   // it, making that const qualifier in our constructor a dirty lie
   MT & my_mesh = const_cast<MT &>(*_obj);
   // If we're asked to write data that's associated with a different
   // mesh, output files full of garbage are the result.
   libmesh_assert_equal_to(&es.get_mesh(), _obj);
   // A non-renumbered mesh may not have a contiguous numbering, and
   // that needs to be fixed before we can build a solution vector.
   if (my_mesh.max_elem_id() != my_mesh.n_elem() ||
       my_mesh.max_node_id() != my_mesh.n_nodes())
     {
       // If we were allowed to renumber then we should have already
       // been properly renumbered...
       libmesh_assert(!my_mesh.allow_renumbering());
       libmesh_do_once(libMesh::out <<
                       "Warning:  This MeshOutput subclass only supports meshes which are contiguously renumbered!"
                       << std::endl;);
       my_mesh.allow_renumbering(true);
       my_mesh.renumber_nodes_and_elements();
       // Not sure what good going back to false will do here, the
       // renumbering horses have already left the barn...
       my_mesh.allow_renumbering(false);
     }
   MeshSerializer serialize(const_cast<MT &>(*_obj), !_is_parallel_format, _serial_only_needed_on_proc_0);
   // Build the list of variable names that will be written.
   std::vector<std::string> names;
   es.build_variable_names  (names, nullptr, system_names);
   if (!_is_parallel_format)
     {
       // Build the nodal solution values & get the variable
       // names from the EquationSystems object
       std::vector<Number> soln;
       es.build_solution_vector (soln, system_names);
       this->write_nodal_data (fname, soln, names);
     }
   else // _is_parallel_format
     {
       std::unique_ptr<NumericVector<Number>> parallel_soln =
         es.build_parallel_solution_vector(system_names);
       this->write_nodal_data (fname, *parallel_soln, names);
     }
 }
write_nodal_data() [1/2]
template<class MT> virtual void libMesh::MeshOutput< MT >::write_nodal_data (const std::string & , const std::vector< Number > & , const std::vector< std::string > &) inline virtual
This method implements writing a mesh with nodal data to a specified file where the nodal data and variable names are provided.
Reimplemented in libMesh::ExodusII_IO, libMesh::Nemesis_IO, libMesh::UCDIO, libMesh::NameBasedIO, libMesh::GmshIO, libMesh::GMVIO, libMesh::VTKIO, libMesh::MEDITIO, libMesh::GnuPlotIO, and libMesh::TecplotIO.
Definition at line 105 of file mesh_output.h.
   { libmesh_not_implemented(); }
write_nodal_data() [2/2]
template<class MT > void libMesh::MeshOutput< MT >::write_nodal_data (const std::string & fname, const NumericVector< Number > & parallel_soln, const std::vector< std::string > & names) virtual
This method should be overridden by "parallel" output formats for writing nodal data. Instead of getting a localized copy of the nodal solution vector, it is passed a NumericVector of type=PARALLEL which is in node-major order i.e. (u0,v0,w0, u1,v1,w1, u2,v2,w2, u3,v3,w3, ...) and contains n_nodes*n_vars total entries. Then, it is up to the individual I/O class to extract the required solution values from this vector and write them in parallel.
If not implemented, localizes the parallel vector into a std::vector and calls the other version of this function.
Reimplemented in libMesh::Nemesis_IO.
Definition at line 150 of file mesh_output.C.
 {
   // This is the fallback implementation for parallel I/O formats that
   // do not yet implement proper writing in parallel, and instead rely
   // on the full solution vector being available on all processors.
   std::vector<Number> soln;
   parallel_soln.localize(soln);
   this->write_nodal_data(fname, soln, names);
 }
write_nodal_data_discontinuous()
template<class MT> virtual void libMesh::MeshOutput< MT >::write_nodal_data_discontinuous (const std::string & , const std::vector< Number > & , const std::vector< std::string > &) inline virtual
This method implements writing a mesh with discontinuous data to a specified file where the nodal data and variables names are provided.
Reimplemented in libMesh::ExodusII_IO.
Definition at line 114 of file mesh_output.h.
   { libmesh_not_implemented(); }
Member Data Documentation
_ascii_precision
template<class MT> unsigned int libMesh::MeshOutput< MT >::_ascii_precision private
Precision to use when writing ASCII files.
Definition at line 182 of file mesh_output.h.
_is_parallel_format
template<class MT> const bool libMesh::MeshOutput< MT >::_is_parallel_format protected
Flag specifying whether this format is parallel-capable. If this is false (default) I/O is only permitted when the mesh has been serialized.
Definition at line 159 of file mesh_output.h.
_obj
template<class MT> const MT* const libMesh::MeshOutput< MT >::_obj private
A pointer to a constant object. This allows us to write the object to file.
Definition at line 177 of file mesh_output.h.
_serial_only_needed_on_proc_0
template<class MT> const bool libMesh::MeshOutput< MT >::_serial_only_needed_on_proc_0 protected
Flag specifying whether this format can be written by only serializing the mesh to processor zero
If this is false (default) the mesh will be serialized to all processors
Definition at line 168 of file mesh_output.h.
The documentation for this class was generated from the following files:
mesh_output.h
mesh_output.C