libMesh: libMesh::SystemSubsetBySubdomain::SubdomainSelection Class Reference
SomeWebsiteLogo
libMesh::SystemSubsetBySubdomain::SubdomainSelection Class Reference abstract
#include <system_subset_by_subdomain.h>
Public Member Functions
SubdomainSelection ()
virtual ~SubdomainSelection ()
virtual bool operator() (const subdomain_id_type &subdomain_id) const =0
Static Public Member Functions
static std::string get_info ()
static void print_info (std::ostream &out=libMesh::out)
static unsigned int n_objects ()
static void enable_print_counter_info ()
static void disable_print_counter_info ()
Static Protected Attributes
static Threads::atomic< unsigned int > _n_objects
static Threads::spin_mutex _mutex
static bool _enable_print_counter = true
Private Member Functions
SubdomainSelection (const SubdomainSelection &)
SubdomainSelection & operator= (const SubdomainSelection &)
Detailed Description
Subclass for user-specified selection of subdomain ids to be included in a SystemSubset.
Definition at line 54 of file system_subset_by_subdomain.h.
Constructor & Destructor Documentation
libMesh::SystemSubsetBySubdomain::SubdomainSelection::SubdomainSelection (void)
Constructor.
Definition at line 35 of file system_subset_by_subdomain.C.
 {
 }
libMesh::SystemSubsetBySubdomain::SubdomainSelection::~SubdomainSelection (void) virtual
Destructor.
Definition at line 40 of file system_subset_by_subdomain.C.
 {
 }
libMesh::SystemSubsetBySubdomain::SubdomainSelection::SubdomainSelection (const SubdomainSelection &) private
This isn't a copyable object, so let's make sure nobody tries.
We won't even bother implementing this; we'll just make sure that the compiler doesn't implement a default.
Member Function Documentation
void libMesh::ReferenceCounter::disable_print_counter_info () static inherited
Definition at line 106 of file reference_counter.C.
References libMesh::ReferenceCounter::_enable_print_counter.
Referenced by libMesh::LibMeshInit::LibMeshInit().
 {
   _enable_print_counter = false;
   return;
 }
void libMesh::ReferenceCounter::enable_print_counter_info () static inherited
Methods to enable/disable the reference counter output from print_info()
Definition at line 100 of file reference_counter.C.
References libMesh::ReferenceCounter::_enable_print_counter.
 {
   _enable_print_counter = true;
   return;
 }
std::string libMesh::ReferenceCounter::get_info () static inherited
Gets a string containing the reference information.
Definition at line 47 of file reference_counter.C.
References libMesh::Quality::name().
 {
 #if defined(LIBMESH_ENABLE_REFERENCE_COUNTING) && defined(DEBUG)
   std::ostringstream oss;
   oss << '\n'
       << " ---------------------------------------------------------------------------- \n"
       << "| Reference count information                                                |\n"
       << " ---------------------------------------------------------------------------- \n";
   for (Counts::iterator it = _counts.begin();
        it != _counts.end(); ++it)
     {
       const std::string name(it->first);
       const unsigned int creations    = it->second.first;
       const unsigned int destructions = it->second.second;
       oss << "| " << name << " reference count information:\n"
           << "|  Creations:    " << creations    << '\n'
           << "|  Destructions: " << destructions << '\n';
     }
   oss << " ---------------------------------------------------------------------------- \n";
   return oss.str();
 #else
   return "";
 #endif
 }
static unsigned int libMesh::ReferenceCounter::n_objects () inline static inherited
Prints the number of outstanding (created, but not yet destroyed) objects.
Definition at line 75 of file reference_counter.h.
References libMesh::ReferenceCounter::_n_objects.
Referenced by libMesh::LibMeshInit::~LibMeshInit().
   { return _n_objects; }
virtual bool libMesh::SystemSubsetBySubdomain::SubdomainSelection::operator() (const subdomain_id_type & subdomain_id) const pure virtual
Method that decides whether a given subdomain id is included in the subset or nor.
Implemented in libMesh::SystemSubsetBySubdomain::SubdomainSelectionByList.
SubdomainSelection& libMesh::SystemSubsetBySubdomain::SubdomainSelection::operator= (const SubdomainSelection &) private
This isn't a copyable object, so let's make sure nobody tries.
We won't even bother implementing this; we'll just make sure that the compiler doesn't implement a default.
void libMesh::ReferenceCounter::print_info (std::ostream & out = libMesh::out) static inherited
Prints the reference information, by default to libMesh::out.
Definition at line 95 of file reference_counter.C.
Referenced by libMesh::LibMeshInit::~LibMeshInit().
 {}
Member Data Documentation
bool libMesh::ReferenceCounter::_enable_print_counter = true static protected inherited
Flag to control whether reference count information is printed when print_info is called.
Definition at line 133 of file reference_counter.h.
Referenced by libMesh::ReferenceCounter::disable_print_counter_info(), and libMesh::ReferenceCounter::enable_print_counter_info().
Threads::spin_mutex libMesh::ReferenceCounter::_mutex static protected inherited
Mutual exclusion object to enable thread-safe reference counting.
Definition at line 127 of file reference_counter.h.
Threads::atomic< unsigned int > libMesh::ReferenceCounter::_n_objects static protected inherited
The number of objects. Print the reference count information when the number returns to 0.
Definition at line 122 of file reference_counter.h.
Referenced by libMesh::ReferenceCounter::n_objects(), libMesh::ReferenceCounter::ReferenceCounter(), and libMesh::ReferenceCounter::~ReferenceCounter().
The documentation for this class was generated from the following files:
system_subset_by_subdomain.h
system_subset_by_subdomain.C