libMesh: libMesh::DTKAdapter Class Reference
SomeWebsiteLogo
libMesh::DTKAdapter Class Reference
#include <dtk_adapter.h>
Public Types
typedef DataTransferKit::MeshContainer< int > MeshContainerType
typedef DataTransferKit::FieldContainer< double > FieldContainerType
typedef DataTransferKit::MeshTraits< MeshContainerType >::global_ordinal_type GlobalOrdinal
typedef DataTransferKit::FieldEvaluator< GlobalOrdinal, FieldContainerType > EvaluatorType
typedef Teuchos::RCP< EvaluatorType > RCP_Evaluator
Public Member Functions
DTKAdapter (Teuchos::RCP< const Teuchos::Comm< int > > in_comm, EquationSystems &in_es)
Teuchos::RCP< DataTransferKit::MeshManager< MeshContainerType > > get_mesh_manager ()
RCP_Evaluator get_variable_evaluator (std::string var_name)
Teuchos::RCP< DataTransferKit::FieldManager< MeshContainerType > > get_target_coords ()
Teuchos::RCP< DataTransferKit::FieldManager< FieldContainerType > > get_values_to_fill (std::string var_name)
void update_variable_values (std::string var_name)
Protected Member Functions
System * find_sys (std::string var_name)
DataTransferKit::DTK_ElementTopology get_element_topology (const Elem *elem)
void get_semi_local_nodes (std::set< unsigned int > &semi_local_nodes)
Protected Attributes
Teuchos::RCP< const Teuchos::Comm< int > > comm
EquationSystems & es
const MeshBase & mesh
unsigned int dim
unsigned int num_local_nodes
Teuchos::ArrayRCP< int > vertices
Teuchos::RCP< DataTransferKit::MeshManager< MeshContainerType > > mesh_manager
RCP_Evaluator field_evaluator
Teuchos::RCP< DataTransferKit::FieldManager< MeshContainerType > > target_coords
std::map< std::string, Teuchos::RCP< DataTransferKit::FieldManager< FieldContainerType > > > values_to_fill
Map of variable names to arrays to be filled by a transfer.
std::map< std::string, RCP_Evaluator > evaluators
Map of variable names to RCP_Evaluator objects.
Detailed Description
The DTKAdapter is used with the DTKSolutionTranfer object to adapt libmesh data to the DTK interface.
Author
Derek Gaston
Date
2013
Definition at line 52 of file dtk_adapter.h.
Member Typedef Documentation
typedef DataTransferKit::FieldEvaluator<GlobalOrdinal,FieldContainerType> libMesh::DTKAdapter::EvaluatorType
Definition at line 60 of file dtk_adapter.h.
typedef DataTransferKit::FieldContainer<double> libMesh::DTKAdapter::FieldContainerType
Definition at line 58 of file dtk_adapter.h.
typedef DataTransferKit::MeshTraits<MeshContainerType>::global_ordinal_type libMesh::DTKAdapter::GlobalOrdinal
Definition at line 59 of file dtk_adapter.h.
typedef DataTransferKit::MeshContainer<int> libMesh::DTKAdapter::MeshContainerType
Definition at line 57 of file dtk_adapter.h.
typedef Teuchos::RCP<EvaluatorType> libMesh::DTKAdapter::RCP_Evaluator
Definition at line 61 of file dtk_adapter.h.
Constructor & Destructor Documentation
libMesh::DTKAdapter::DTKAdapter (Teuchos::RCP< const Teuchos::Comm< int > > in_comm, EquationSystems & in_es)
Member Function Documentation
System* libMesh::DTKAdapter::find_sys (std::string var_name) protected
Small helper function for finding the system containing the variable.
Note
This implies that variable names are unique across all systems!
Referenced by get_target_coords().
DataTransferKit::DTK_ElementTopology libMesh::DTKAdapter::get_element_topology (const Elem * elem) protected
Returns
The DTK ElementTopology for a given Elem.
Referenced by get_target_coords().
Teuchos::RCP<DataTransferKit::MeshManager<MeshContainerType> > libMesh::DTKAdapter::get_mesh_manager () inline
Definition at line 64 of file dtk_adapter.h.
References get_variable_evaluator(), and mesh_manager.
 { return mesh_manager; }
void libMesh::DTKAdapter::get_semi_local_nodes (std::set< unsigned int > & semi_local_nodes) protected
Helper function that fills the std::set with all of the node numbers of nodes connected to local elements.
Referenced by get_target_coords().
Teuchos::RCP<DataTransferKit::FieldManager<MeshContainerType> > libMesh::DTKAdapter::get_target_coords () inline
Definition at line 66 of file dtk_adapter.h.
References find_sys(), get_element_topology(), get_semi_local_nodes(), get_values_to_fill(), target_coords, and update_variable_values().
 { return target_coords; }
Teuchos::RCP<DataTransferKit::FieldManager<FieldContainerType> > libMesh::DTKAdapter::get_values_to_fill (std::string var_name)
Referenced by get_target_coords().
RCP_Evaluator libMesh::DTKAdapter::get_variable_evaluator (std::string var_name)
Referenced by get_mesh_manager().
void libMesh::DTKAdapter::update_variable_values (std::string var_name)
After computing values for a variable in this EquationSystems we need to take those values and put them in the actual solution vector.
Referenced by get_target_coords().
Member Data Documentation
Teuchos::RCP<const Teuchos::Comm<int> > libMesh::DTKAdapter::comm protected
Definition at line 94 of file dtk_adapter.h.
unsigned int libMesh::DTKAdapter::dim protected
Definition at line 97 of file dtk_adapter.h.
EquationSystems& libMesh::DTKAdapter::es protected
Definition at line 95 of file dtk_adapter.h.
std::map<std::string, RCP_Evaluator> libMesh::DTKAdapter::evaluators protected
Map of variable names to RCP_Evaluator objects.
Definition at line 110 of file dtk_adapter.h.
RCP_Evaluator libMesh::DTKAdapter::field_evaluator protected
Definition at line 103 of file dtk_adapter.h.
const MeshBase& libMesh::DTKAdapter::mesh protected
Definition at line 96 of file dtk_adapter.h.
Teuchos::RCP<DataTransferKit::MeshManager<MeshContainerType> > libMesh::DTKAdapter::mesh_manager protected
Definition at line 102 of file dtk_adapter.h.
Referenced by get_mesh_manager().
unsigned int libMesh::DTKAdapter::num_local_nodes protected
Definition at line 99 of file dtk_adapter.h.
Teuchos::RCP<DataTransferKit::FieldManager<MeshContainerType> > libMesh::DTKAdapter::target_coords protected
Definition at line 104 of file dtk_adapter.h.
Referenced by get_target_coords().
std::map<std::string, Teuchos::RCP<DataTransferKit::FieldManager<FieldContainerType> > > libMesh::DTKAdapter::values_to_fill protected
Map of variable names to arrays to be filled by a transfer.
Definition at line 107 of file dtk_adapter.h.
Teuchos::ArrayRCP<int> libMesh::DTKAdapter::vertices protected
Definition at line 100 of file dtk_adapter.h.
The documentation for this class was generated from the following file:
dtk_adapter.h