libMesh: libMesh::TaoOptimizationSolver< T > Class Template Reference
SomeWebsiteLogo
libMesh::TaoOptimizationSolver< T > Class Template Reference
#include <tao_optimization_solver.h>
Public Types
typedef OptimizationSystem sys_type
Public Member Functions
TaoOptimizationSolver (sys_type &system)
~TaoOptimizationSolver ()
virtual void clear () libmesh_override
virtual void init () libmesh_override
Tao tao ()
virtual void solve () libmesh_override
virtual void get_dual_variables () libmesh_override
virtual void print_converged_reason () libmesh_override
virtual int get_converged_reason () libmesh_override
bool initialized () const
const sys_type & system () const
sys_type & system ()
const Parallel::Communicator & comm () const
processor_id_type n_processors () const
processor_id_type processor_id () const
Static Public Member Functions
static UniquePtr< OptimizationSolver< T > > build (sys_type &s, const SolverPackage solver_package=libMesh::default_solver_package())
static std::string get_info ()
static void print_info (std::ostream &out=libMesh::out)
static unsigned int n_objects ()
static void enable_print_counter_info ()
static void disable_print_counter_info ()
Public Attributes
OptimizationSystem::ComputeObjective * objective_object
OptimizationSystem::ComputeGradient * gradient_object
OptimizationSystem::ComputeHessian * hessian_object
OptimizationSystem::ComputeEqualityConstraints * equality_constraints_object
OptimizationSystem::ComputeEqualityConstraintsJacobian * equality_constraints_jacobian_object
OptimizationSystem::ComputeInequalityConstraints * inequality_constraints_object
OptimizationSystem::ComputeInequalityConstraintsJacobian * inequality_constraints_jacobian_object
OptimizationSystem::ComputeLowerAndUpperBounds * lower_and_upper_bounds_object
unsigned int max_objective_function_evaluations
Real objective_function_relative_tolerance
bool verbose
Protected Types
typedef std::map< std::string, std::pair< unsigned int, unsigned int > > Counts
Protected Member Functions
void increment_constructor_count (const std::string &name)
void increment_destructor_count (const std::string &name)
Protected Attributes
Tao _tao
TaoConvergedReason _reason
sys_type & _system
bool _is_initialized
const Parallel::Communicator & _communicator
Static Protected Attributes
static Counts _counts
static Threads::atomic< unsigned int > _n_objects
static Threads::spin_mutex _mutex
static bool _enable_print_counter = true
Friends
PetscErrorCode __libmesh_tao_objective (Tao tao, Vec x, PetscReal *objective, void *ctx)
PetscErrorCode __libmesh_tao_gradient (Tao tao, Vec x, Vec g, void *ctx)
PetscErrorCode __libmesh_tao_hessian (Tao tao, Vec x, Mat h, Mat pc, void *ctx)
PetscErrorCode __libmesh_tao_equality_constraints (Tao tao, Vec x, Vec ce, void *ctx)
PetscErrorCode __libmesh_tao_equality_constraints_jacobian (Tao tao, Vec x, Mat J, Mat Jpre, void *ctx)
PetscErrorCode __libmesh_tao_inequality_constraints (Tao tao, Vec x, Vec cineq, void *ctx)
PetscErrorCode __libmesh_tao_inequality_constraints_jacobian (Tao tao, Vec x, Mat J, Mat Jpre, void *ctx)
Detailed Description
template<typename T>
class libMesh::TaoOptimizationSolver< T >
This class provides an interface to the Tao optimization solvers.
Author
David Knezevic
Date
2015
Definition at line 58 of file tao_optimization_solver.h.
Member Typedef Documentation
typedef std::map<std::string, std::pair<unsigned int, unsigned int> > libMesh::ReferenceCounter::Counts protected inherited
Data structure to log the information. The log is identified by the class name.
Definition at line 110 of file reference_counter.h.
template<typename T> typedef OptimizationSystem libMesh::TaoOptimizationSolver< T >::sys_type
The type of system that we use in conjunction with this solver.
Definition at line 65 of file tao_optimization_solver.h.
Constructor & Destructor Documentation
template<typename T > libMesh::TaoOptimizationSolver< T >::TaoOptimizationSolver (sys_type & system) explicit
Constructor. Initializes Tao data structures.
Definition at line 401 of file tao_optimization_solver.C.
                                                                                :
   OptimizationSolver<T>(system_in),
   _reason(TAO_CONVERGED_USER) // Arbitrary initial value...
 {
 }
template<typename T > libMesh::TaoOptimizationSolver< T >::~TaoOptimizationSolver ()
Destructor.
Definition at line 410 of file tao_optimization_solver.C.
References libMesh::TaoOptimizationSolver< T >::clear().
 {
   this->clear ();
 }
Member Function Documentation
template<typename T > UniquePtr< OptimizationSolver< T > > libMesh::OptimizationSolver< T >::build (sys_type & s, const SolverPackage solver_package = libMesh::default_solver_package()) static inherited
Builds an OptimizationSolver using the package specified by solver_package
Definition at line 62 of file optimization_solver.C.
References libMesh::libmesh_ignore(), libMesh::NLOPT_SOLVERS, and libMesh::PETSC_SOLVERS.
 {
   // Prevent unused variables warnings when Tao is not available
   libmesh_ignore(s);
   // Build the appropriate solver
   switch (solver_package)
     {
 #if defined(LIBMESH_HAVE_PETSC_TAO) && !defined(LIBMESH_USE_COMPLEX_NUMBERS)
     case PETSC_SOLVERS:
       return UniquePtr<OptimizationSolver<T> >(new TaoOptimizationSolver<T>(s));
 #endif // #if defined(LIBMESH_HAVE_PETSC_TAO) && !defined(LIBMESH_USE_COMPLEX_NUMBERS)
 #if defined(LIBMESH_HAVE_NLOPT) && !defined(LIBMESH_USE_COMPLEX_NUMBERS)
     case NLOPT_SOLVERS:
       return UniquePtr<OptimizationSolver<T> >(new NloptOptimizationSolver<T>(s));
 #endif // #if defined(LIBMESH_HAVE_NLOPT) && !defined(LIBMESH_USE_COMPLEX_NUMBERS)
     default:
       libmesh_error_msg("ERROR:  Unrecognized solver package: " << solver_package);
     }
   libmesh_error_msg("We'll never get here!");
   return UniquePtr<OptimizationSolver<T> >();
 }
template<typename T > void libMesh::TaoOptimizationSolver< T >::clear () virtual
Release all memory and clear data structures.
Reimplemented from libMesh::OptimizationSolver< T >.
Definition at line 418 of file tao_optimization_solver.C.
References libMesh::OptimizationSolver< T >::_is_initialized, libMesh::TaoOptimizationSolver< T >::_tao, ierr, and libMesh::OptimizationSolver< T >::initialized().
Referenced by libMesh::TaoOptimizationSolver< T >::~TaoOptimizationSolver().
 {
   if (this->initialized())
     {
       this->_is_initialized = false;
       PetscErrorCode ierr=0;
       ierr = TaoDestroy(&_tao);
       LIBMESH_CHKERR(ierr);
     }
 }
const Parallel::Communicator& libMesh::ParallelObject::comm () const inline inherited
Returns
a reference to the Parallel::Communicator object used by this mesh.
Definition at line 87 of file parallel_object.h.
References libMesh::ParallelObject::_communicator.
Referenced by libMesh::__libmesh_petsc_diff_solver_monitor(), libMesh::__libmesh_petsc_diff_solver_residual(), libMesh::__libmesh_petsc_snes_jacobian(), libMesh::__libmesh_petsc_snes_postcheck(), libMesh::__libmesh_petsc_snes_residual(), libMesh::__libmesh_tao_equality_constraints(), libMesh::__libmesh_tao_equality_constraints_jacobian(), libMesh::__libmesh_tao_gradient(), libMesh::__libmesh_tao_hessian(), libMesh::__libmesh_tao_inequality_constraints(), libMesh::__libmesh_tao_inequality_constraints_jacobian(), libMesh::__libmesh_tao_objective(), libMesh::MeshRefinement::_coarsen_elements(), libMesh::ExactSolution::_compute_error(), libMesh::ParmetisPartitioner::_do_repartition(), libMesh::UniformRefinementEstimator::_estimate_error(), libMesh::BoundaryInfo::_find_id_maps(), libMesh::PetscLinearSolver< T >::_petsc_shell_matrix_get_diagonal(), libMesh::SlepcEigenSolver< T >::_petsc_shell_matrix_get_diagonal(), libMesh::PetscLinearSolver< T >::_petsc_shell_matrix_mult(), libMesh::SlepcEigenSolver< T >::_petsc_shell_matrix_mult(), libMesh::PetscLinearSolver< T >::_petsc_shell_matrix_mult_add(), libMesh::EquationSystems::_read_impl(), libMesh::MeshRefinement::_refine_elements(), libMesh::MeshRefinement::_smooth_flags(), libMesh::ImplicitSystem::add_matrix(), libMesh::System::add_vector(), libMesh::EigenSparseLinearSolver< T >::adjoint_solve(), libMesh::UnstructuredMesh::all_second_order(), libMesh::MeshTools::Modification::all_tri(), libMesh::LaplaceMeshSmoother::allgather_graph(), libMesh::FEMSystem::assemble_qoi(), libMesh::MeshCommunication::assign_global_indices(), libMesh::ParmetisPartitioner::assign_partitioning(), libMesh::DofMap::attach_matrix(), libMesh::Parallel::BinSorter< KeyType, IdxType >::binsort(), libMesh::Parallel::Sort< KeyType, IdxType >::binsort(), libMesh::MeshTools::bounding_box(), libMesh::MeshCommunication::broadcast(), libMesh::SparseMatrix< T >::build(), libMesh::MeshTools::Generation::build_extrusion(), libMesh::Parallel::Histogram< KeyType, IdxType >::build_histogram(), libMesh::PetscNonlinearSolver< T >::build_mat_null_space(), libMesh::BoundaryInfo::build_node_list_from_side_list(), libMesh::EquationSystems::build_parallel_solution_vector(), libMesh::MeshBase::cache_elem_dims(), libMesh::System::calculate_norm(), libMesh::DofMap::check_dirichlet_bcid_consistency(), libMesh::DistributedVector< T >::clone(), libMesh::EigenSparseVector< T >::clone(), libMesh::LaspackVector< T >::clone(), libMesh::EpetraVector< T >::clone(), libMesh::PetscVector< T >::clone(), libMesh::EpetraVector< T >::close(), libMesh::Parallel::Sort< KeyType, IdxType >::communicate_bins(), libMesh::Nemesis_IO_Helper::compute_num_global_elem_blocks(), libMesh::Nemesis_IO_Helper::compute_num_global_nodesets(), libMesh::Nemesis_IO_Helper::compute_num_global_sidesets(), libMesh::Problem_Interface::computeF(), libMesh::Problem_Interface::computeJacobian(), libMesh::Problem_Interface::computePreconditioner(), libMesh::MeshTools::correct_node_proc_ids(), libMesh::MeshRefinement::create_parent_error_vector(), libMesh::MeshCommunication::delete_remote_elements(), libMesh::DofMap::distribute_dofs(), DMlibMeshFunction(), DMlibMeshJacobian(), DMlibMeshSetSystem_libMesh(), DMVariableBounds_libMesh(), libMesh::MeshRefinement::eliminate_unrefined_patches(), libMesh::EpetraVector< T >::EpetraVector(), libMesh::WeightedPatchRecoveryErrorEstimator::estimate_error(), libMesh::PatchRecoveryErrorEstimator::estimate_error(), libMesh::JumpErrorEstimator::estimate_error(), libMesh::AdjointRefinementEstimator::estimate_error(), libMesh::ExactErrorEstimator::estimate_error(), libMesh::MeshRefinement::flag_elements_by_elem_fraction(), libMesh::MeshRefinement::flag_elements_by_error_fraction(), libMesh::MeshRefinement::flag_elements_by_nelem_target(), libMesh::MeshCommunication::gather(), libMesh::MeshCommunication::gather_neighboring_elements(), libMesh::CondensedEigenSystem::get_eigenpair(), libMesh::DofMap::get_info(), libMesh::ImplicitSystem::get_linear_solver(), libMesh::EquationSystems::get_solution(), libMesh::LocationMap< T >::init(), libMesh::PetscDiffSolver::init(), libMesh::TimeSolver::init(), libMesh::TopologyMap::init(), libMesh::TaoOptimizationSolver< T >::init(), libMesh::PetscNonlinearSolver< T >::init(), libMesh::DistributedVector< T >::init(), libMesh::EpetraVector< T >::init(), libMesh::PetscVector< T >::init(), libMesh::SystemSubsetBySubdomain::init(), libMesh::EigenSystem::init_data(), libMesh::EigenSystem::init_matrices(), libMesh::ParmetisPartitioner::initialize(), libMesh::OptimizationSystem::initialize_equality_constraints_storage(), libMesh::OptimizationSystem::initialize_inequality_constraints_storage(), libMesh::MeshTools::libmesh_assert_parallel_consistent_procids< Elem >(), libMesh::MeshTools::libmesh_assert_parallel_consistent_procids< Node >(), libMesh::MeshTools::libmesh_assert_topology_consistent_procids< Node >(), libMesh::MeshTools::libmesh_assert_valid_boundary_ids(), libMesh::MeshTools::libmesh_assert_valid_dof_ids(), libMesh::MeshTools::libmesh_assert_valid_neighbors(), libMesh::DistributedMesh::libmesh_assert_valid_parallel_flags(), libMesh::DistributedMesh::libmesh_assert_valid_parallel_object_ids(), libMesh::DistributedMesh::libmesh_assert_valid_parallel_p_levels(), libMesh::MeshTools::libmesh_assert_valid_refinement_flags(), libMesh::MeshTools::libmesh_assert_valid_unique_ids(), libMesh::MeshRefinement::limit_level_mismatch_at_edge(), libMesh::MeshRefinement::limit_level_mismatch_at_node(), libMesh::MeshRefinement::limit_overrefined_boundary(), libMesh::MeshRefinement::limit_underrefined_boundary(), libMesh::MeshRefinement::make_coarsening_compatible(), libMesh::MeshCommunication::make_elems_parallel_consistent(), libMesh::MeshRefinement::make_flags_parallel_consistent(), libMesh::MeshCommunication::make_new_node_proc_ids_parallel_consistent(), libMesh::MeshCommunication::make_new_nodes_parallel_consistent(), libMesh::MeshCommunication::make_node_ids_parallel_consistent(), libMesh::MeshCommunication::make_node_proc_ids_parallel_consistent(), libMesh::MeshCommunication::make_node_unique_ids_parallel_consistent(), libMesh::MeshCommunication::make_nodes_parallel_consistent(), libMesh::MeshCommunication::make_p_levels_parallel_consistent(), libMesh::MeshRefinement::make_refinement_compatible(), libMesh::DistributedVector< T >::max(), libMesh::FEMSystem::mesh_position_set(), libMesh::MeshSerializer::MeshSerializer(), libMesh::DistributedVector< T >::min(), libMesh::DistributedMesh::n_active_elem(), libMesh::MeshTools::n_active_levels(), libMesh::BoundaryInfo::n_boundary_conds(), libMesh::BoundaryInfo::n_edge_conds(), libMesh::CondensedEigenSystem::n_global_non_condensed_dofs(), libMesh::MeshTools::n_levels(), libMesh::BoundaryInfo::n_nodeset_conds(), libMesh::MeshTools::n_p_levels(), libMesh::BoundaryInfo::n_shellface_conds(), libMesh::DistributedMesh::parallel_max_elem_id(), libMesh::DistributedMesh::parallel_max_node_id(), libMesh::ReplicatedMesh::parallel_max_unique_id(), libMesh::DistributedMesh::parallel_max_unique_id(), libMesh::DistributedMesh::parallel_n_elem(), libMesh::DistributedMesh::parallel_n_nodes(), libMesh::SparsityPattern::Build::parallel_sync(), libMesh::MeshTools::paranoid_n_levels(), libMesh::Partitioner::partition(), libMesh::MetisPartitioner::partition_range(), libMesh::Partitioner::partition_unpartitioned_elements(), libMesh::petsc_auto_fieldsplit(), libMesh::System::point_gradient(), libMesh::System::point_hessian(), libMesh::System::point_value(), libMesh::MeshBase::prepare_for_use(), libMesh::SparseMatrix< T >::print(), libMesh::MeshTools::processor_bounding_box(), libMesh::Nemesis_IO::read(), libMesh::XdrIO::read(), libMesh::XdrIO::read_serialized_bc_names(), libMesh::XdrIO::read_serialized_bcs_helper(), libMesh::XdrIO::read_serialized_connectivity(), libMesh::XdrIO::read_serialized_nodes(), libMesh::XdrIO::read_serialized_nodesets(), libMesh::XdrIO::read_serialized_subdomain_names(), libMesh::MeshBase::recalculate_n_partitions(), libMesh::MeshCommunication::redistribute(), libMesh::DistributedMesh::renumber_dof_objects(), libMesh::MeshCommunication::send_coarse_ghosts(), libMesh::Partitioner::set_node_processor_ids(), libMesh::DofMap::set_nonlocal_dof_objects(), libMesh::Partitioner::set_parent_processor_ids(), libMesh::LaplaceMeshSmoother::smooth(), libMesh::Parallel::Sort< KeyType, IdxType >::sort(), libMesh::MeshTools::subdomain_bounding_box(), libMesh::MeshBase::subdomain_ids(), libMesh::BoundaryInfo::sync(), libMesh::Parallel::sync_element_data_by_parent_id(), libMesh::Parallel::sync_node_data_by_element_id(), libMesh::MeshRefinement::test_level_one(), libMesh::MeshRefinement::test_unflagged(), libMesh::MeshTools::total_weight(), libMesh::NameBasedIO::write(), libMesh::XdrIO::write(), libMesh::XdrIO::write_serialized_bcs_helper(), libMesh::XdrIO::write_serialized_connectivity(), libMesh::XdrIO::write_serialized_nodes(), libMesh::XdrIO::write_serialized_nodesets(), libMesh::DistributedVector< T >::zero_clone(), libMesh::LaspackVector< T >::zero_clone(), libMesh::EigenSparseVector< T >::zero_clone(), libMesh::EpetraVector< T >::zero_clone(), and libMesh::PetscVector< T >::zero_clone().
   { return _communicator; }
void libMesh::ReferenceCounter::disable_print_counter_info () static inherited
Definition at line 106 of file reference_counter.C.
References libMesh::ReferenceCounter::_enable_print_counter.
Referenced by libMesh::LibMeshInit::LibMeshInit(), and libMesh::ReferenceCounter::n_objects().
 {
   _enable_print_counter = false;
   return;
 }
void libMesh::ReferenceCounter::enable_print_counter_info () static inherited
Methods to enable/disable the reference counter output from print_info()
Definition at line 100 of file reference_counter.C.
References libMesh::ReferenceCounter::_enable_print_counter.
Referenced by libMesh::ReferenceCounter::n_objects().
 {
   _enable_print_counter = true;
   return;
 }
template<typename T > int libMesh::TaoOptimizationSolver< T >::get_converged_reason () virtual
Returns the currently-available (or most recently obtained, if the Tao object has been destroyed) convergence reason. Refer to Tao docs for the meaning of different TaoConvergedReason.
Reimplemented from libMesh::OptimizationSolver< T >.
Definition at line 623 of file tao_optimization_solver.C.
References libMesh::TaoOptimizationSolver< T >::_reason, libMesh::TaoOptimizationSolver< T >::_tao, ierr, and libMesh::OptimizationSolver< T >::initialized().
Referenced by libMesh::TaoOptimizationSolver< T >::print_converged_reason(), and libMesh::TaoOptimizationSolver< T >::tao().
 {
   PetscErrorCode ierr=0;
   if (this->initialized())
     {
       ierr = TaoGetConvergedReason(_tao, &_reason);
       LIBMESH_CHKERR(ierr);
     }
   return static_cast<int>(_reason);
 }
template<typename T > void libMesh::TaoOptimizationSolver< T >::get_dual_variables () virtual
Get the current values of dual variables associated with inequality and equality constraints. The variables will be stored in _system.lambda_eq and _system.lambda_ineq.
Reimplemented from libMesh::OptimizationSolver< T >.
Definition at line 593 of file tao_optimization_solver.C.
References libMesh::TaoOptimizationSolver< T >::_tao, ierr, libMesh::OptimizationSystem::lambda_eq, libMesh::OptimizationSystem::lambda_ineq, libMesh::OptimizationSolver< T >::system(), and libMesh::PetscVector< T >::vec().
Referenced by libMesh::TaoOptimizationSolver< T >::tao().
 {
   LOG_SCOPE("get_dual_variables()", "TaoOptimizationSolver");
   PetscVector<T> * lambda_eq_petsc =
     cast_ptr<PetscVector<T> *>(this->system().lambda_eq.get());
   PetscVector<T> * lambda_ineq_petsc =
     cast_ptr<PetscVector<T> *>(this->system().lambda_ineq.get());
   Vec lambda_eq_petsc_vec = lambda_eq_petsc->vec();
   Vec lambda_ineq_petsc_vec = lambda_ineq_petsc->vec();
   PetscErrorCode ierr = 0;
   ierr = TaoGetDualVariables(_tao,
                              &lambda_eq_petsc_vec,
                              &lambda_ineq_petsc_vec);
   LIBMESH_CHKERR(ierr);
 }
std::string libMesh::ReferenceCounter::get_info () static inherited
Gets a string containing the reference information.
Definition at line 47 of file reference_counter.C.
References libMesh::ReferenceCounter::_counts, and libMesh::Quality::name().
Referenced by libMesh::ReferenceCounter::print_info().
 {
 #if defined(LIBMESH_ENABLE_REFERENCE_COUNTING) && defined(DEBUG)
   std::ostringstream oss;
   oss << '\n'
       << " ---------------------------------------------------------------------------- \n"
       << "| Reference count information                                                |\n"
       << " ---------------------------------------------------------------------------- \n";
   for (Counts::iterator it = _counts.begin();
        it != _counts.end(); ++it)
     {
       const std::string name(it->first);
       const unsigned int creations    = it->second.first;
       const unsigned int destructions = it->second.second;
       oss << "| " << name << " reference count information:\n"
           << "|  Creations:    " << creations    << '\n'
           << "|  Destructions: " << destructions << '\n';
     }
   oss << " ---------------------------------------------------------------------------- \n";
   return oss.str();
 #else
   return "";
 #endif
 }
void libMesh::ReferenceCounter::increment_constructor_count (const std::string & name) inline protected inherited
Increments the construction counter. Should be called in the constructor of any derived class that will be reference counted.
Definition at line 160 of file reference_counter.h.
References libMesh::ReferenceCounter::_counts, libMesh::Quality::name(), and libMesh::Threads::spin_mtx.
Referenced by libMesh::ReferenceCounter::n_objects(), and libMesh::ReferenceCountedObject< RBParametrized >::ReferenceCountedObject().
 {
   Threads::spin_mutex::scoped_lock lock(Threads::spin_mtx);
   std::pair<unsigned int, unsigned int> & p = _counts[name];
   p.first++;
 }
void libMesh::ReferenceCounter::increment_destructor_count (const std::string & name) inline protected inherited
Increments the destruction counter. Should be called in the destructor of any derived class that will be reference counted.
Definition at line 173 of file reference_counter.h.
References libMesh::ReferenceCounter::_counts, libMesh::Quality::name(), and libMesh::Threads::spin_mtx.
Referenced by libMesh::ReferenceCounter::n_objects(), and libMesh::ReferenceCountedObject< RBParametrized >::~ReferenceCountedObject().
 {
   Threads::spin_mutex::scoped_lock lock(Threads::spin_mtx);
   std::pair<unsigned int, unsigned int> & p = _counts[name];
   p.second++;
 }
template<typename T > void libMesh::TaoOptimizationSolver< T >::init () virtual
Initialize data structures if not done so already.
Implements libMesh::OptimizationSolver< T >.
Definition at line 434 of file tao_optimization_solver.C.
References libMesh::OptimizationSolver< T >::_is_initialized, libMesh::TaoOptimizationSolver< T >::_tao, libMesh::ParallelObject::comm(), ierr, and libMesh::OptimizationSolver< T >::initialized().
Referenced by libMesh::TaoOptimizationSolver< T >::solve(), and libMesh::TaoOptimizationSolver< T >::tao().
 {
   // Initialize the data structures if not done so already.
   if (!this->initialized())
     {
       this->_is_initialized = true;
       PetscErrorCode ierr=0;
       ierr = TaoCreate(this->comm().get(),&_tao);
       LIBMESH_CHKERR(ierr);
     }
 }
template<typename T > bool libMesh::OptimizationSolver< T >::initialized () const inline inherited
Returns
true if the data structures are initialized, false otherwise.
Definition at line 82 of file optimization_solver.h.
References libMesh::OptimizationSolver< T >::_is_initialized.
Referenced by libMesh::TaoOptimizationSolver< T >::clear(), libMesh::NloptOptimizationSolver< T >::clear(), libMesh::TaoOptimizationSolver< T >::get_converged_reason(), libMesh::TaoOptimizationSolver< T >::init(), and libMesh::NloptOptimizationSolver< T >::init().
 { return _is_initialized; }
static unsigned int libMesh::ReferenceCounter::n_objects () inline static inherited
Prints the number of outstanding (created, but not yet destroyed) objects.
Definition at line 76 of file reference_counter.h.
References libMesh::ReferenceCounter::_n_objects, libMesh::ReferenceCounter::disable_print_counter_info(), libMesh::ReferenceCounter::enable_print_counter_info(), libMesh::ReferenceCounter::increment_constructor_count(), libMesh::ReferenceCounter::increment_destructor_count(), and libMesh::Quality::name().
Referenced by libMesh::System::hide_output(), and libMesh::LibMeshInit::LibMeshInit().
   { return _n_objects; }
processor_id_type libMesh::ParallelObject::n_processors () const inline inherited
Returns
the number of processors in the group.
Definition at line 93 of file parallel_object.h.
References libMesh::ParallelObject::_communicator, and libMesh::Parallel::Communicator::size().
Referenced by libMesh::ParmetisPartitioner::_do_repartition(), libMesh::BoundaryInfo::_find_id_maps(), libMesh::DistributedMesh::add_elem(), libMesh::DistributedMesh::add_node(), libMesh::LaplaceMeshSmoother::allgather_graph(), libMesh::FEMSystem::assembly(), libMesh::ParmetisPartitioner::assign_partitioning(), libMesh::AztecLinearSolver< T >::AztecLinearSolver(), libMesh::MeshCommunication::broadcast(), libMesh::BoundaryInfo::build_node_list_from_side_list(), libMesh::DistributedMesh::clear(), libMesh::Nemesis_IO_Helper::compute_border_node_ids(), libMesh::Nemesis_IO_Helper::construct_nemesis_filename(), libMesh::MeshTools::correct_node_proc_ids(), libMesh::UnstructuredMesh::create_pid_mesh(), libMesh::DofMap::distribute_dofs(), libMesh::DofMap::distribute_local_dofs_node_major(), libMesh::DofMap::distribute_local_dofs_var_major(), libMesh::DistributedMesh::DistributedMesh(), libMesh::EnsightIO::EnsightIO(), libMesh::MeshCommunication::gather(), libMesh::MeshCommunication::gather_neighboring_elements(), libMesh::MeshBase::get_info(), libMesh::EquationSystems::get_solution(), libMesh::DistributedVector< T >::init(), libMesh::SystemSubsetBySubdomain::init(), libMesh::ParmetisPartitioner::initialize(), libMesh::Nemesis_IO_Helper::initialize(), libMesh::DistributedMesh::insert_elem(), libMesh::MeshTools::libmesh_assert_parallel_consistent_procids< Elem >(), libMesh::MeshTools::libmesh_assert_parallel_consistent_procids< Node >(), libMesh::MeshTools::libmesh_assert_topology_consistent_procids< Node >(), libMesh::MeshTools::libmesh_assert_valid_boundary_ids(), libMesh::MeshTools::libmesh_assert_valid_dof_ids(), libMesh::MeshTools::libmesh_assert_valid_neighbors(), libMesh::MeshTools::libmesh_assert_valid_refinement_flags(), libMesh::DofMap::local_variable_indices(), libMesh::MeshBase::n_active_elem_on_proc(), libMesh::MeshBase::n_elem_on_proc(), libMesh::MeshBase::n_nodes_on_proc(), libMesh::SparsityPattern::Build::parallel_sync(), libMesh::Partitioner::partition(), libMesh::MeshBase::partition(), libMesh::Partitioner::partition_unpartitioned_elements(), libMesh::PetscLinearSolver< T >::PetscLinearSolver(), libMesh::System::point_gradient(), libMesh::System::point_hessian(), libMesh::System::point_value(), libMesh::SparseMatrix< T >::print(), libMesh::MeshTools::processor_bounding_box(), libMesh::NameBasedIO::read(), libMesh::Nemesis_IO::read(), libMesh::XdrIO::read(), libMesh::MeshCommunication::redistribute(), libMesh::DistributedMesh::renumber_dof_objects(), libMesh::Partitioner::repartition(), libMesh::MeshCommunication::send_coarse_ghosts(), libMesh::Partitioner::set_node_processor_ids(), libMesh::DofMap::set_nonlocal_dof_objects(), libMesh::Parallel::Sort< KeyType, IdxType >::sort(), libMesh::DistributedMesh::update_parallel_id_counts(), libMesh::GMVIO::write_binary(), libMesh::GMVIO::write_discontinuous_gmv(), libMesh::XdrIO::write_serialized_bcs_helper(), libMesh::XdrIO::write_serialized_connectivity(), libMesh::XdrIO::write_serialized_nodes(), and libMesh::XdrIO::write_serialized_nodesets().
   { return cast_int<processor_id_type>(_communicator.size()); }
template<typename T > void libMesh::TaoOptimizationSolver< T >::print_converged_reason () virtual
Prints a useful message about why the latest optimization solve con(di)verged.
Reimplemented from libMesh::OptimizationSolver< T >.
Definition at line 614 of file tao_optimization_solver.C.
References libMesh::TaoOptimizationSolver< T >::get_converged_reason(), and libMesh::out.
Referenced by libMesh::TaoOptimizationSolver< T >::tao().
 {
   libMesh::out << "Tao optimization solver convergence/divergence reason: "
                << TaoConvergedReasons[this->get_converged_reason()] << std::endl;
 }
void libMesh::ReferenceCounter::print_info (std::ostream & out = libMesh::out) static inherited
Prints the reference information, by default to libMesh::out.
Definition at line 88 of file reference_counter.C.
References libMesh::ReferenceCounter::_enable_print_counter, and libMesh::ReferenceCounter::get_info().
Referenced by libMesh::LibMeshInit::LibMeshInit().
 {
   if( _enable_print_counter ) out_stream << ReferenceCounter::get_info();
 }
processor_id_type libMesh::ParallelObject::processor_id () const inline inherited
Returns
the rank of this processor in the group.
Definition at line 99 of file parallel_object.h.
References libMesh::ParallelObject::_communicator, and libMesh::Parallel::Communicator::rank().
Referenced by libMesh::BoundaryInfo::_find_id_maps(), libMesh::EquationSystems::_read_impl(), libMesh::DistributedMesh::add_elem(), libMesh::BoundaryInfo::add_elements(), libMesh::DofMap::add_neighbors_to_send_list(), libMesh::DistributedMesh::add_node(), libMesh::MeshRefinement::add_node(), libMesh::MeshTools::Modification::all_tri(), libMesh::FEMSystem::assembly(), libMesh::ParmetisPartitioner::assign_partitioning(), libMesh::MeshCommunication::broadcast(), libMesh::EquationSystems::build_discontinuous_solution_vector(), libMesh::Nemesis_IO_Helper::build_element_and_node_maps(), libMesh::ParmetisPartitioner::build_graph(), libMesh::InfElemBuilder::build_inf_elem(), libMesh::BoundaryInfo::build_node_list_from_side_list(), libMesh::DofMap::build_sparsity(), libMesh::DistributedMesh::clear(), libMesh::ExodusII_IO_Helper::close(), libMesh::Nemesis_IO_Helper::compute_border_node_ids(), libMesh::Nemesis_IO_Helper::compute_communication_map_parameters(), libMesh::Nemesis_IO_Helper::compute_internal_and_border_elems_and_internal_nodes(), libMesh::Nemesis_IO_Helper::compute_node_communication_maps(), libMesh::Nemesis_IO_Helper::compute_num_global_elem_blocks(), libMesh::Nemesis_IO_Helper::compute_num_global_nodesets(), libMesh::Nemesis_IO_Helper::compute_num_global_sidesets(), libMesh::Nemesis_IO_Helper::construct_nemesis_filename(), libMesh::MeshTools::correct_node_proc_ids(), libMesh::ExodusII_IO_Helper::create(), libMesh::DistributedMesh::delete_elem(), libMesh::DistributedMesh::delete_node(), libMesh::MeshCommunication::delete_remote_elements(), libMesh::DofMap::distribute_dofs(), libMesh::DofMap::distribute_local_dofs_node_major(), libMesh::DofMap::distribute_local_dofs_var_major(), libMesh::DistributedMesh::DistributedMesh(), libMesh::EnsightIO::EnsightIO(), libMesh::MeshFunction::find_element(), libMesh::MeshFunction::find_elements(), libMesh::UnstructuredMesh::find_neighbors(), libMesh::MeshCommunication::gather(), libMesh::MeshCommunication::gather_neighboring_elements(), libMesh::Nemesis_IO_Helper::get_cmap_params(), libMesh::Nemesis_IO_Helper::get_eb_info_global(), libMesh::Nemesis_IO_Helper::get_elem_cmap(), libMesh::Nemesis_IO_Helper::get_elem_map(), libMesh::MeshBase::get_info(), libMesh::DofMap::get_info(), libMesh::Nemesis_IO_Helper::get_init_global(), libMesh::Nemesis_IO_Helper::get_init_info(), libMesh::Nemesis_IO_Helper::get_loadbal_param(), libMesh::Nemesis_IO_Helper::get_node_cmap(), libMesh::Nemesis_IO_Helper::get_node_map(), libMesh::Nemesis_IO_Helper::get_ns_param_global(), libMesh::EquationSystems::get_solution(), libMesh::Nemesis_IO_Helper::get_ss_param_global(), libMesh::SparsityPattern::Build::handle_vi_vj(), libMesh::DistributedVector< T >::init(), libMesh::SystemSubsetBySubdomain::init(), libMesh::ParmetisPartitioner::initialize(), libMesh::ExodusII_IO_Helper::initialize(), libMesh::ExodusII_IO_Helper::initialize_element_variables(), libMesh::ExodusII_IO_Helper::initialize_global_variables(), libMesh::ExodusII_IO_Helper::initialize_nodal_variables(), libMesh::DistributedMesh::insert_elem(), libMesh::DofMap::is_evaluable(), libMesh::SparsityPattern::Build::join(), libMesh::MeshTools::libmesh_assert_parallel_consistent_procids< Elem >(), libMesh::MeshTools::libmesh_assert_parallel_consistent_procids< Node >(), libMesh::MeshTools::libmesh_assert_valid_neighbors(), libMesh::DistributedMesh::libmesh_assert_valid_parallel_object_ids(), libMesh::DofMap::local_variable_indices(), libMesh::MeshRefinement::make_coarsening_compatible(), libMesh::MeshBase::n_active_local_elem(), libMesh::BoundaryInfo::n_boundary_conds(), libMesh::BoundaryInfo::n_edge_conds(), libMesh::System::n_local_dofs(), libMesh::MeshBase::n_local_elem(), libMesh::MeshBase::n_local_nodes(), libMesh::BoundaryInfo::n_nodeset_conds(), libMesh::BoundaryInfo::n_shellface_conds(), libMesh::WeightedPatchRecoveryErrorEstimator::EstimateError::operator()(), libMesh::SparsityPattern::Build::operator()(), libMesh::PatchRecoveryErrorEstimator::EstimateError::operator()(), libMesh::SparsityPattern::Build::parallel_sync(), libMesh::MetisPartitioner::partition_range(), libMesh::System::point_gradient(), libMesh::System::point_hessian(), libMesh::System::point_value(), libMesh::SparseMatrix< T >::print(), libMesh::NumericVector< T >::print_global(), libMesh::Nemesis_IO_Helper::put_cmap_params(), libMesh::Nemesis_IO_Helper::put_elem_cmap(), libMesh::Nemesis_IO_Helper::put_elem_map(), libMesh::Nemesis_IO_Helper::put_loadbal_param(), libMesh::Nemesis_IO_Helper::put_node_cmap(), libMesh::Nemesis_IO_Helper::put_node_map(), libMesh::NameBasedIO::read(), libMesh::Nemesis_IO::read(), libMesh::XdrIO::read(), libMesh::ExodusII_IO_Helper::read_elem_num_map(), libMesh::ExodusII_IO_Helper::read_node_num_map(), libMesh::XdrIO::read_serialized_bc_names(), libMesh::XdrIO::read_serialized_bcs_helper(), libMesh::XdrIO::read_serialized_connectivity(), libMesh::XdrIO::read_serialized_nodes(), libMesh::XdrIO::read_serialized_nodesets(), libMesh::XdrIO::read_serialized_subdomain_names(), libMesh::MeshCommunication::redistribute(), libMesh::DistributedMesh::renumber_dof_objects(), libMesh::MeshCommunication::send_coarse_ghosts(), libMesh::Partitioner::set_node_processor_ids(), libMesh::DofMap::set_nonlocal_dof_objects(), libMesh::LaplaceMeshSmoother::smooth(), libMesh::MeshTools::total_weight(), libMesh::Parallel::Packing< Node * >::unpack(), libMesh::Parallel::Packing< Elem * >::unpack(), libMesh::DistributedMesh::update_parallel_id_counts(), libMesh::MeshTools::weight(), libMesh::NameBasedIO::write(), libMesh::XdrIO::write(), libMesh::EquationSystems::write(), libMesh::GMVIO::write_discontinuous_gmv(), libMesh::ExodusII_IO::write_element_data(), libMesh::ExodusII_IO_Helper::write_element_values(), libMesh::ExodusII_IO_Helper::write_elements(), libMesh::ExodusII_IO::write_global_data(), libMesh::ExodusII_IO_Helper::write_global_values(), libMesh::ExodusII_IO::write_information_records(), libMesh::ExodusII_IO_Helper::write_information_records(), libMesh::ExodusII_IO_Helper::write_nodal_coordinates(), libMesh::UCDIO::write_nodal_data(), libMesh::ExodusII_IO::write_nodal_data(), libMesh::ExodusII_IO::write_nodal_data_discontinuous(), libMesh::ExodusII_IO_Helper::write_nodal_values(), libMesh::Nemesis_IO_Helper::write_nodesets(), libMesh::ExodusII_IO_Helper::write_nodesets(), libMesh::XdrIO::write_serialized_bc_names(), libMesh::XdrIO::write_serialized_bcs_helper(), libMesh::XdrIO::write_serialized_connectivity(), libMesh::XdrIO::write_serialized_nodes(), libMesh::XdrIO::write_serialized_nodesets(), libMesh::XdrIO::write_serialized_subdomain_names(), libMesh::Nemesis_IO_Helper::write_sidesets(), libMesh::ExodusII_IO_Helper::write_sidesets(), libMesh::ExodusII_IO::write_timestep(), and libMesh::ExodusII_IO_Helper::write_timestep().
   { return cast_int<processor_id_type>(_communicator.rank()); }
template<typename T > void libMesh::TaoOptimizationSolver< T >::solve () virtual
Call the Tao solver.
Implements libMesh::OptimizationSolver< T >.
Definition at line 449 of file tao_optimization_solver.C.
References libMesh::TaoOptimizationSolver< T >::__libmesh_tao_equality_constraints, libMesh::TaoOptimizationSolver< T >::__libmesh_tao_equality_constraints_jacobian, libMesh::TaoOptimizationSolver< T >::__libmesh_tao_gradient, libMesh::TaoOptimizationSolver< T >::__libmesh_tao_hessian, libMesh::TaoOptimizationSolver< T >::__libmesh_tao_inequality_constraints, libMesh::TaoOptimizationSolver< T >::__libmesh_tao_inequality_constraints_jacobian, libMesh::TaoOptimizationSolver< T >::__libmesh_tao_objective, libMesh::TaoOptimizationSolver< T >::_reason, libMesh::TaoOptimizationSolver< T >::_tao, libMesh::OptimizationSystem::C_eq, libMesh::OptimizationSystem::C_eq_jac, libMesh::OptimizationSystem::C_ineq, libMesh::OptimizationSystem::C_ineq_jac, libMesh::OptimizationSolver< T >::equality_constraints_jacobian_object, libMesh::OptimizationSolver< T >::equality_constraints_object, libMesh::System::get_vector(), libMesh::OptimizationSolver< T >::gradient_object, libMesh::OptimizationSolver< T >::hessian_object, ierr, libMesh::OptimizationSolver< T >::inequality_constraints_jacobian_object, libMesh::OptimizationSolver< T >::inequality_constraints_object, libMesh::TaoOptimizationSolver< T >::init(), libMesh::libmesh_assert(), libMesh::OptimizationSystem::ComputeLowerAndUpperBounds::lower_and_upper_bounds(), libMesh::OptimizationSolver< T >::lower_and_upper_bounds_object, libMesh::PetscMatrix< T >::mat(), libMesh::ImplicitSystem::matrix, libMesh::OptimizationSolver< T >::max_objective_function_evaluations, libMesh::OptimizationSolver< T >::objective_function_relative_tolerance, libMesh::OptimizationSolver< T >::objective_object, libMesh::System::solution, libMesh::OptimizationSolver< T >::system(), libMesh::x, and libMesh::PetscVector< T >::zero().
Referenced by libMesh::TaoOptimizationSolver< T >::tao().
 {
   LOG_SCOPE("solve()", "TaoOptimizationSolver");
   this->init ();
   this->system().solution->zero();
   PetscMatrix<T> * hessian  = cast_ptr<PetscMatrix<T> *>(this->system().matrix);
   // PetscVector<T> * gradient = cast_ptr<PetscVector<T> *>(this->system().rhs);
   PetscVector<T> * x         = cast_ptr<PetscVector<T> *>(this->system().solution.get());
   PetscVector<T> * ceq       = cast_ptr<PetscVector<T> *>(this->system().C_eq.get());
   PetscMatrix<T> * ceq_jac   = cast_ptr<PetscMatrix<T> *>(this->system().C_eq_jac.get());
   PetscVector<T> * cineq     = cast_ptr<PetscVector<T> *>(this->system().C_ineq.get());
   PetscMatrix<T> * cineq_jac = cast_ptr<PetscMatrix<T> *>(this->system().C_ineq_jac.get());
   PetscVector<T> * lb        = cast_ptr<PetscVector<T> *>(&this->system().get_vector("lower_bounds"));
   PetscVector<T> * ub        = cast_ptr<PetscVector<T> *>(&this->system().get_vector("upper_bounds"));
   // Set the starting guess to zero.
   x->zero();
   PetscErrorCode ierr = 0;
   // Workaround for bug where TaoSetFromOptions *reset*
   // programmatically set tolerance and max. function evaluation
   // values when "-tao_type ipm" was specified on the command line: we
   // call TaoSetFromOptions twice (both before and after setting
   // custom options programatically)
   ierr = TaoSetFromOptions(_tao);
   LIBMESH_CHKERR(ierr);
   // Set convergence tolerances
   // f(X) - f(X*) (estimated)            <= fatol
   // |f(X) - f(X*)| (estimated) / |f(X)| <= frtol
   // ||g(X)||                            <= gatol
   // ||g(X)|| / |f(X)|                   <= grtol
   // ||g(X)|| / ||g(X0)||                <= gttol
   // Command line equivalents: -tao_fatol, -tao_frtol, -tao_gatol, -tao_grtol, -tao_gttol
   ierr = TaoSetTolerances(_tao,
 #if PETSC_RELEASE_LESS_THAN(3,7,0)
                           // Releases up to 3.X.Y had fatol and frtol, after that they were removed.
                           // Hopefully we'll be able to know X and Y soon. Guessing at 3.7.0.
                           /*fatol=*/PETSC_DEFAULT,
                           /*frtol=*/PETSC_DEFAULT,
 #endif
                           /*gatol=*/PETSC_DEFAULT,
                           /*grtol=*/this->objective_function_relative_tolerance,
                           /*gttol=*/PETSC_DEFAULT);
   LIBMESH_CHKERR(ierr);
   // Set the max-allowed number of objective function evaluations
   // Command line equivalent: -tao_max_funcs
   ierr = TaoSetMaximumFunctionEvaluations(_tao, this->max_objective_function_evaluations);
   LIBMESH_CHKERR(ierr);
   // Set the max-allowed number of optimization iterations.
   // Command line equivalent: -tao_max_it
   // Not implemented for now as it seems fairly similar to
   // ierr = TaoSetMaximumIterations(_tao, 4);
   // LIBMESH_CHKERR(ierr);
   // Set solution vec and an initial guess
   ierr = TaoSetInitialVector(_tao, x->vec());
   LIBMESH_CHKERR(ierr);
   // We have to have an objective function
   libmesh_assert( this->objective_object );
   // Set routines for objective, gradient, hessian evaluation
   ierr = TaoSetObjectiveRoutine(_tao, __libmesh_tao_objective, this);
   LIBMESH_CHKERR(ierr);
   if ( this->gradient_object )
     {
       ierr = TaoSetGradientRoutine(_tao, __libmesh_tao_gradient, this);
       LIBMESH_CHKERR(ierr);
     }
   if ( this->hessian_object )
     {
       ierr = TaoSetHessianRoutine(_tao, hessian->mat(), hessian->mat(), __libmesh_tao_hessian, this);
       LIBMESH_CHKERR(ierr);
     }
   if ( this->lower_and_upper_bounds_object )
     {
       // Need to actually compute the bounds vectors first
       this->lower_and_upper_bounds_object->lower_and_upper_bounds(this->system());
       ierr = TaoSetVariableBounds(_tao,
                                   lb->vec(),
                                   ub->vec());
       LIBMESH_CHKERR(ierr);
     }
   if ( this->equality_constraints_object )
     {
       ierr = TaoSetEqualityConstraintsRoutine(_tao, ceq->vec(), __libmesh_tao_equality_constraints, this);
       LIBMESH_CHKERR(ierr);
     }
   if ( this->equality_constraints_jacobian_object )
     {
       ierr = TaoSetJacobianEqualityRoutine(_tao,
                                            ceq_jac->mat(),
                                            ceq_jac->mat(),
                                            __libmesh_tao_equality_constraints_jacobian,
                                            this);
       LIBMESH_CHKERR(ierr);
     }
   // Optionally set inequality constraints
   if ( this->inequality_constraints_object )
     {
       ierr = TaoSetInequalityConstraintsRoutine(_tao, cineq->vec(), __libmesh_tao_inequality_constraints, this);
       LIBMESH_CHKERR(ierr);
     }
   // Optionally set inequality constraints Jacobian
   if ( this->inequality_constraints_jacobian_object )
     {
       ierr = TaoSetJacobianInequalityRoutine(_tao,
                                              cineq_jac->mat(),
                                              cineq_jac->mat(),
                                              __libmesh_tao_inequality_constraints_jacobian,
                                              this);
       LIBMESH_CHKERR(ierr);
     }
   // Check for Tao command line options
   ierr = TaoSetFromOptions(_tao);
   LIBMESH_CHKERR(ierr);
   // Perform the optimization
   ierr = TaoSolve(_tao);
   LIBMESH_CHKERR(ierr);
   // Store the convergence/divergence reason
   ierr = TaoGetConvergedReason(_tao, &_reason);
   LIBMESH_CHKERR(ierr);
 }
template<typename T > const sys_type& libMesh::OptimizationSolver< T >::system () const inline inherited
Returns
a constant reference to the system we are using to define the optimization problem.
Definition at line 171 of file optimization_solver.h.
References libMesh::OptimizationSolver< T >::_system.
Referenced by libMesh::__libmesh_nlopt_equality_constraints(), libMesh::__libmesh_nlopt_inequality_constraints(), libMesh::__libmesh_nlopt_objective(), libMesh::__libmesh_tao_equality_constraints(), libMesh::__libmesh_tao_equality_constraints_jacobian(), libMesh::__libmesh_tao_gradient(), libMesh::__libmesh_tao_hessian(), libMesh::__libmesh_tao_inequality_constraints(), libMesh::__libmesh_tao_inequality_constraints_jacobian(), libMesh::__libmesh_tao_objective(), libMesh::TaoOptimizationSolver< T >::get_dual_variables(), libMesh::TaoOptimizationSolver< T >::solve(), and libMesh::NloptOptimizationSolver< T >::solve().
 { return _system; }
template<typename T > sys_type& libMesh::OptimizationSolver< T >::system () inline inherited
Returns
a writeable reference to the system we are using to define the optimization problem.
Definition at line 177 of file optimization_solver.h.
References libMesh::OptimizationSolver< T >::_system.
 { return _system; }
template<typename T> Tao libMesh::TaoOptimizationSolver< T >::tao () inline
Returns the raw PETSc Tao context pointer.
Definition at line 91 of file tao_optimization_solver.h.
References libMesh::TaoOptimizationSolver< T >::_tao, libMesh::TaoOptimizationSolver< T >::get_converged_reason(), libMesh::TaoOptimizationSolver< T >::get_dual_variables(), libMesh::TaoOptimizationSolver< T >::init(), libMesh::TaoOptimizationSolver< T >::print_converged_reason(), and libMesh::TaoOptimizationSolver< T >::solve().
 { this->init(); return _tao; }
Friends And Related Function Documentation
template<typename T> PetscErrorCode __libmesh_tao_equality_constraints (Tao tao, Vec x, Vec ce, void * ctx) friend
Definition at line 198 of file tao_optimization_solver.C.
Referenced by libMesh::TaoOptimizationSolver< T >::solve().
   {
     LOG_SCOPE("equality_constraints()", "TaoOptimizationSolver");
     PetscErrorCode ierr = 0;
     libmesh_assert(x);
     libmesh_assert(ce);
     libmesh_assert(ctx);
     // ctx should be a pointer to the solver (it was passed in as void *)
     TaoOptimizationSolver<Number> * solver =
       static_cast<TaoOptimizationSolver<Number> *> (ctx);
     OptimizationSystem & sys = solver->system();
     // We'll use current_local_solution below, so let's ensure that it's consistent
     // with the vector x that was passed in.
     PetscVector<Number> & X_sys = *cast_ptr<PetscVector<Number> *>(sys.solution.get());
     PetscVector<Number> X(x, sys.comm());
     // Perform a swap so that sys.solution points to X
     X.swap(X_sys);
     // Impose constraints on X
     sys.get_dof_map().enforce_constraints_exactly(sys);
     // Update sys.current_local_solution based on X
     sys.update();
     // Swap back
     X.swap(X_sys);
     // We'll also pass the constraints vector ce into the assembly routine
     // so let's make a PETSc vector for that too.
     PetscVector<Number> eq_constraints(ce, sys.comm());
     // Clear the gradient prior to assembly
     eq_constraints.zero();
     if (solver->equality_constraints_object != libmesh_nullptr)
       solver->equality_constraints_object->equality_constraints(*(sys.current_local_solution), eq_constraints, sys);
     else
       libmesh_error_msg("Constraints function not defined in __libmesh_tao_equality_constraints");
     eq_constraints.close();
     return ierr;
   }
template<typename T> PetscErrorCode __libmesh_tao_equality_constraints_jacobian (Tao tao, Vec x, Mat J, Mat Jpre, void * ctx) friend
Definition at line 249 of file tao_optimization_solver.C.
Referenced by libMesh::TaoOptimizationSolver< T >::solve().
   {
     LOG_SCOPE("equality_constraints_jacobian()", "TaoOptimizationSolver");
     PetscErrorCode ierr = 0;
     libmesh_assert(x);
     libmesh_assert(J);
     libmesh_assert(Jpre);
     // ctx should be a pointer to the solver (it was passed in as void *)
     TaoOptimizationSolver<Number> * solver =
       static_cast<TaoOptimizationSolver<Number> *> (ctx);
     OptimizationSystem & sys = solver->system();
     // We'll use current_local_solution below, so let's ensure that it's consistent
     // with the vector x that was passed in.
     PetscVector<Number> & X_sys = *cast_ptr<PetscVector<Number> *>(sys.solution.get());
     PetscVector<Number> X(x, sys.comm());
     // Perform a swap so that sys.solution points to X
     X.swap(X_sys);
     // Impose constraints on X
     sys.get_dof_map().enforce_constraints_exactly(sys);
     // Update sys.current_local_solution based on X
     sys.update();
     // Swap back
     X.swap(X_sys);
     // Let's also wrap J and Jpre in PetscMatrix objects for convenience
     PetscMatrix<Number> J_petsc(J, sys.comm());
     PetscMatrix<Number> Jpre_petsc(Jpre, sys.comm());
     if (solver->equality_constraints_jacobian_object != libmesh_nullptr)
       solver->equality_constraints_jacobian_object->equality_constraints_jacobian(*(sys.current_local_solution), J_petsc, sys);
     else
       libmesh_error_msg("Constraints function not defined in __libmesh_tao_equality_constraints_jacobian");
     J_petsc.close();
     Jpre_petsc.close();
     return ierr;
   }
template<typename T> PetscErrorCode __libmesh_tao_gradient (Tao tao, Vec x, Vec g, void * ctx) friend
Definition at line 92 of file tao_optimization_solver.C.
Referenced by libMesh::TaoOptimizationSolver< T >::solve().
   {
     LOG_SCOPE("gradient()", "TaoOptimizationSolver");
     PetscErrorCode ierr = 0;
     libmesh_assert(x);
     libmesh_assert(g);
     libmesh_assert(ctx);
     // ctx should be a pointer to the solver (it was passed in as void *)
     TaoOptimizationSolver<Number> * solver =
       static_cast<TaoOptimizationSolver<Number> *> (ctx);
     OptimizationSystem & sys = solver->system();
     // We'll use current_local_solution below, so let's ensure that it's consistent
     // with the vector x that was passed in.
     PetscVector<Number> & X_sys = *cast_ptr<PetscVector<Number> *>(sys.solution.get());
     PetscVector<Number> X(x, sys.comm());
     // Perform a swap so that sys.solution points to X
     X.swap(X_sys);
     // Impose constraints on X
     sys.get_dof_map().enforce_constraints_exactly(sys);
     // Update sys.current_local_solution based on X
     sys.update();
     // Swap back
     X.swap(X_sys);
     // We'll also pass the gradient in to the assembly routine
     // so let's make a PETSc vector for that too.
     PetscVector<Number> gradient(g, sys.comm());
     // Clear the gradient prior to assembly
     gradient.zero();
     if (solver->gradient_object != libmesh_nullptr)
       solver->gradient_object->gradient(*(sys.current_local_solution), gradient, sys);
     else
       libmesh_error_msg("Gradient function not defined in __libmesh_tao_gradient");
     gradient.close();
     return ierr;
   }
template<typename T> PetscErrorCode __libmesh_tao_hessian (Tao tao, Vec x, Mat h, Mat pc, void * ctx) friend
Definition at line 142 of file tao_optimization_solver.C.
Referenced by libMesh::TaoOptimizationSolver< T >::solve().
   {
     LOG_SCOPE("hessian()", "TaoOptimizationSolver");
     PetscErrorCode ierr = 0;
     libmesh_assert(x);
     libmesh_assert(h);
     libmesh_assert(pc);
     libmesh_assert(ctx);
     // ctx should be a pointer to the solver (it was passed in as void *)
     TaoOptimizationSolver<Number> * solver =
       static_cast<TaoOptimizationSolver<Number> *> (ctx);
     OptimizationSystem & sys = solver->system();
     // We'll use current_local_solution below, so let's ensure that it's consistent
     // with the vector x that was passed in.
     PetscVector<Number> & X_sys = *cast_ptr<PetscVector<Number> *>(sys.solution.get());
     PetscVector<Number> X(x, sys.comm());
     // Perform a swap so that sys.solution points to X
     X.swap(X_sys);
     // Impose constraints on X
     sys.get_dof_map().enforce_constraints_exactly(sys);
     // Update sys.current_local_solution based on X
     sys.update();
     // Swap back
     X.swap(X_sys);
     // Let's also wrap pc and h in PetscMatrix objects for convenience
     PetscMatrix<Number> PC(pc, sys.comm());
     PetscMatrix<Number> hessian(h, sys.comm());
     PC.attach_dof_map(sys.get_dof_map());
     hessian.attach_dof_map(sys.get_dof_map());
     if (solver->hessian_object != libmesh_nullptr)
       {
         // Following PetscNonlinearSolver by passing in PC. It's not clear
         // why we pass in PC and not hessian though?
         solver->hessian_object->hessian(*(sys.current_local_solution), PC, sys);
       }
     else
       libmesh_error_msg("Hessian function not defined in __libmesh_tao_hessian");
     PC.close();
     hessian.close();
     return ierr;
   }
template<typename T> PetscErrorCode __libmesh_tao_inequality_constraints (Tao tao, Vec x, Vec cineq, void * ctx) friend
Definition at line 297 of file tao_optimization_solver.C.
Referenced by libMesh::TaoOptimizationSolver< T >::solve().
   {
     LOG_SCOPE("inequality_constraints()", "TaoOptimizationSolver");
     PetscErrorCode ierr = 0;
     libmesh_assert(x);
     libmesh_assert(cineq);
     libmesh_assert(ctx);
     // ctx should be a pointer to the solver (it was passed in as void *)
     TaoOptimizationSolver<Number> * solver =
       static_cast<TaoOptimizationSolver<Number> *> (ctx);
     OptimizationSystem & sys = solver->system();
     // We'll use current_local_solution below, so let's ensure that it's consistent
     // with the vector x that was passed in.
     PetscVector<Number> & X_sys = *cast_ptr<PetscVector<Number> *>(sys.solution.get());
     PetscVector<Number> X(x, sys.comm());
     // Perform a swap so that sys.solution points to X
     X.swap(X_sys);
     // Impose constraints on X
     sys.get_dof_map().enforce_constraints_exactly(sys);
     // Update sys.current_local_solution based on X
     sys.update();
     // Swap back
     X.swap(X_sys);
     // We'll also pass the constraints vector ce into the assembly routine
     // so let's make a PETSc vector for that too.
     PetscVector<Number> ineq_constraints(cineq, sys.comm());
     // Clear the gradient prior to assembly
     ineq_constraints.zero();
     if (solver->inequality_constraints_object != libmesh_nullptr)
       solver->inequality_constraints_object->inequality_constraints(*(sys.current_local_solution), ineq_constraints, sys);
     else
       libmesh_error_msg("Constraints function not defined in __libmesh_tao_inequality_constraints");
     ineq_constraints.close();
     return ierr;
   }
template<typename T> PetscErrorCode __libmesh_tao_inequality_constraints_jacobian (Tao tao, Vec x, Mat J, Mat Jpre, void * ctx) friend
Definition at line 348 of file tao_optimization_solver.C.
Referenced by libMesh::TaoOptimizationSolver< T >::solve().
   {
     LOG_SCOPE("inequality_constraints_jacobian()", "TaoOptimizationSolver");
     PetscErrorCode ierr = 0;
     libmesh_assert(x);
     libmesh_assert(J);
     libmesh_assert(Jpre);
     // ctx should be a pointer to the solver (it was passed in as void *)
     TaoOptimizationSolver<Number> * solver =
       static_cast<TaoOptimizationSolver<Number> *> (ctx);
     OptimizationSystem & sys = solver->system();
     // We'll use current_local_solution below, so let's ensure that it's consistent
     // with the vector x that was passed in.
     PetscVector<Number> & X_sys = *cast_ptr<PetscVector<Number> *>(sys.solution.get());
     PetscVector<Number> X(x, sys.comm());
     // Perform a swap so that sys.solution points to X
     X.swap(X_sys);
     // Impose constraints on X
     sys.get_dof_map().enforce_constraints_exactly(sys);
     // Update sys.current_local_solution based on X
     sys.update();
     // Swap back
     X.swap(X_sys);
     // Let's also wrap J and Jpre in PetscMatrix objects for convenience
     PetscMatrix<Number> J_petsc(J, sys.comm());
     PetscMatrix<Number> Jpre_petsc(Jpre, sys.comm());
     if (solver->inequality_constraints_jacobian_object != libmesh_nullptr)
       solver->inequality_constraints_jacobian_object->inequality_constraints_jacobian(*(sys.current_local_solution), J_petsc, sys);
     else
       libmesh_error_msg("Constraints function not defined in __libmesh_tao_inequality_constraints_jacobian");
     J_petsc.close();
     Jpre_petsc.close();
     return ierr;
   }
template<typename T> PetscErrorCode __libmesh_tao_objective (Tao tao, Vec x, PetscReal * objective, void * ctx) friend
Definition at line 49 of file tao_optimization_solver.C.
Referenced by libMesh::TaoOptimizationSolver< T >::solve().
   {
     LOG_SCOPE("objective()", "TaoOptimizationSolver");
     PetscErrorCode ierr = 0;
     libmesh_assert(x);
     libmesh_assert(objective);
     libmesh_assert(ctx);
     // ctx should be a pointer to the solver (it was passed in as void *)
     TaoOptimizationSolver<Number> * solver =
       static_cast<TaoOptimizationSolver<Number> *> (ctx);
     OptimizationSystem & sys = solver->system();
     // We'll use current_local_solution below, so let's ensure that it's consistent
     // with the vector x that was passed in.
     PetscVector<Number> & X_sys = *cast_ptr<PetscVector<Number> *>(sys.solution.get());
     PetscVector<Number> X(x, sys.comm());
     // Perform a swap so that sys.solution points to X
     X.swap(X_sys);
     // Impose constraints on X
     sys.get_dof_map().enforce_constraints_exactly(sys);
     // Update sys.current_local_solution based on X
     sys.update();
     // Swap back
     X.swap(X_sys);
     if (solver->objective_object != libmesh_nullptr)
       (*objective) = solver->objective_object->objective(*(sys.current_local_solution), sys);
     else
       libmesh_error_msg("Objective function not defined in __libmesh_tao_objective");
     return ierr;
   }
Member Data Documentation
const Parallel::Communicator& libMesh::ParallelObject::_communicator protected inherited
Definition at line 105 of file parallel_object.h.
Referenced by libMesh::EquationSystems::build_parallel_solution_vector(), libMesh::ParallelObject::comm(), libMesh::EquationSystems::get_solution(), libMesh::ParallelObject::n_processors(), libMesh::ParallelObject::operator=(), and libMesh::ParallelObject::processor_id().
ReferenceCounter::Counts libMesh::ReferenceCounter::_counts static protected inherited
Actually holds the data.
Definition at line 115 of file reference_counter.h.
Referenced by libMesh::ReferenceCounter::get_info(), libMesh::ReferenceCounter::increment_constructor_count(), and libMesh::ReferenceCounter::increment_destructor_count().
bool libMesh::ReferenceCounter::_enable_print_counter = true static protected inherited
Flag to control whether reference count information is printed when print_info is called.
Definition at line 134 of file reference_counter.h.
Referenced by libMesh::ReferenceCounter::disable_print_counter_info(), libMesh::ReferenceCounter::enable_print_counter_info(), and libMesh::ReferenceCounter::print_info().
template<typename T > bool libMesh::OptimizationSolver< T >::_is_initialized protected inherited
Flag indicating if the data structures have been initialized.
Definition at line 204 of file optimization_solver.h.
Referenced by libMesh::TaoOptimizationSolver< T >::clear(), libMesh::NloptOptimizationSolver< T >::clear(), libMesh::TaoOptimizationSolver< T >::init(), libMesh::NloptOptimizationSolver< T >::init(), and libMesh::OptimizationSolver< T >::initialized().
Threads::spin_mutex libMesh::ReferenceCounter::_mutex static protected inherited
Mutual exclusion object to enable thread-safe reference counting.
Definition at line 128 of file reference_counter.h.
Threads::atomic< unsigned int > libMesh::ReferenceCounter::_n_objects static protected inherited
The number of objects. Print the reference count information when the number returns to 0.
Definition at line 123 of file reference_counter.h.
Referenced by libMesh::ReferenceCounter::n_objects(), libMesh::ReferenceCounter::ReferenceCounter(), and libMesh::ReferenceCounter::~ReferenceCounter().
template<typename T> TaoConvergedReason libMesh::TaoOptimizationSolver< T >::_reason protected
Store the reason for Tao convergence/divergence for use even after _tao has been cleared. Note that print_converged_reason() will always try to get the current reason with TaoGetConvergedReason(), but if the Tao object has already been cleared, it will fall back on this stored value. Note that this value is therefore necessarily not cleared by the clear() function.
Definition at line 132 of file tao_optimization_solver.h.
Referenced by libMesh::TaoOptimizationSolver< T >::get_converged_reason(), and libMesh::TaoOptimizationSolver< T >::solve().
template<typename T > sys_type& libMesh::OptimizationSolver< T >::_system protected inherited
A reference to the system we are solving.
Definition at line 199 of file optimization_solver.h.
Referenced by libMesh::OptimizationSolver< T >::system().
template<typename T> Tao libMesh::TaoOptimizationSolver< T >::_tao protected
Optimization solver context
Definition at line 123 of file tao_optimization_solver.h.
Referenced by libMesh::TaoOptimizationSolver< T >::clear(), libMesh::TaoOptimizationSolver< T >::get_converged_reason(), libMesh::TaoOptimizationSolver< T >::get_dual_variables(), libMesh::TaoOptimizationSolver< T >::init(), libMesh::TaoOptimizationSolver< T >::solve(), and libMesh::TaoOptimizationSolver< T >::tao().
template<typename T > OptimizationSystem::ComputeEqualityConstraintsJacobian* libMesh::OptimizationSolver< T >::equality_constraints_jacobian_object inherited
Object that computes the Jacobian of C_eq(X).
Definition at line 149 of file optimization_solver.h.
Referenced by libMesh::__libmesh_nlopt_equality_constraints(), libMesh::__libmesh_tao_equality_constraints_jacobian(), and libMesh::TaoOptimizationSolver< T >::solve().
template<typename T > OptimizationSystem::ComputeEqualityConstraints* libMesh::OptimizationSolver< T >::equality_constraints_object inherited
Object that computes the equality constraints vector C_eq(X). This will lead to the constraints C_eq(X) = 0 being imposed.
Definition at line 144 of file optimization_solver.h.
Referenced by libMesh::__libmesh_nlopt_equality_constraints(), libMesh::__libmesh_tao_equality_constraints(), libMesh::TaoOptimizationSolver< T >::solve(), and libMesh::NloptOptimizationSolver< T >::solve().
template<typename T > OptimizationSystem::ComputeGradient* libMesh::OptimizationSolver< T >::gradient_object inherited
Object that computes the gradient grad_f(X) of the objective function at the input iterate X.
Definition at line 132 of file optimization_solver.h.
Referenced by libMesh::__libmesh_nlopt_objective(), libMesh::__libmesh_tao_gradient(), and libMesh::TaoOptimizationSolver< T >::solve().
template<typename T > OptimizationSystem::ComputeHessian* libMesh::OptimizationSolver< T >::hessian_object inherited
Object that computes the Hessian H_f(X) of the objective function at the input iterate X.
Definition at line 138 of file optimization_solver.h.
Referenced by libMesh::__libmesh_tao_hessian(), and libMesh::TaoOptimizationSolver< T >::solve().
template<typename T > OptimizationSystem::ComputeInequalityConstraintsJacobian* libMesh::OptimizationSolver< T >::inequality_constraints_jacobian_object inherited
Object that computes the Jacobian of C_ineq(X).
Definition at line 160 of file optimization_solver.h.
Referenced by libMesh::__libmesh_nlopt_inequality_constraints(), libMesh::__libmesh_tao_inequality_constraints_jacobian(), and libMesh::TaoOptimizationSolver< T >::solve().
template<typename T > OptimizationSystem::ComputeInequalityConstraints* libMesh::OptimizationSolver< T >::inequality_constraints_object inherited
Object that computes the inequality constraints vector C_ineq(X). This will lead to the constraints C_ineq(X) >= 0 being imposed.
Definition at line 155 of file optimization_solver.h.
Referenced by libMesh::__libmesh_nlopt_inequality_constraints(), libMesh::__libmesh_tao_inequality_constraints(), libMesh::TaoOptimizationSolver< T >::solve(), and libMesh::NloptOptimizationSolver< T >::solve().
template<typename T > OptimizationSystem::ComputeLowerAndUpperBounds* libMesh::OptimizationSolver< T >::lower_and_upper_bounds_object inherited
Object that computes the lower and upper bounds vectors.
Definition at line 165 of file optimization_solver.h.
Referenced by libMesh::TaoOptimizationSolver< T >::solve(), and libMesh::NloptOptimizationSolver< T >::solve().
template<typename T > unsigned int libMesh::OptimizationSolver< T >::max_objective_function_evaluations inherited
Maximum number of objective function evaluations allowed.
Definition at line 182 of file optimization_solver.h.
Referenced by libMesh::TaoOptimizationSolver< T >::solve(), and libMesh::NloptOptimizationSolver< T >::solve().
template<typename T > Real libMesh::OptimizationSolver< T >::objective_function_relative_tolerance inherited
Required change in objective function which signals convergence.
Definition at line 187 of file optimization_solver.h.
Referenced by libMesh::TaoOptimizationSolver< T >::solve(), and libMesh::NloptOptimizationSolver< T >::solve().
template<typename T > OptimizationSystem::ComputeObjective* libMesh::OptimizationSolver< T >::objective_object inherited
Object that computes the objective function f(X) at the input iterate X.
Definition at line 126 of file optimization_solver.h.
Referenced by libMesh::__libmesh_nlopt_objective(), libMesh::__libmesh_tao_objective(), libMesh::TaoOptimizationSolver< T >::solve(), and libMesh::NloptOptimizationSolver< T >::solve().
template<typename T > bool libMesh::OptimizationSolver< T >::verbose inherited
Control how much is output from the OptimizationSolver as it's running.
Definition at line 192 of file optimization_solver.h.
Referenced by libMesh::__libmesh_nlopt_objective().
The documentation for this class was generated from the following files:
tao_optimization_solver.h
tao_optimization_solver.C