libMesh: libMesh::QBase Class Reference
SomeWebsiteLogo
libMesh::QBase Class Reference abstract
Base class for all quadrature families and orders.
#include <quadrature.h>
Public Member Functions
virtual ~QBase ()
virtual QuadratureType type () const =0
ElemType get_elem_type () const
unsigned int get_p_level () const
unsigned int n_points () const
unsigned int get_dim () const
const std::vector< Point > & get_points () const
std::vector< Point > & get_points ()
const std::vector< Real > & get_weights () const
std::vector< Real > & get_weights ()
Point qp (const unsigned int i) const
Real w (const unsigned int i) const
virtual void init (const ElemType type=INVALID_ELEM, unsigned int p_level=0)
virtual void init (const Elem &elem, const std::vector< Real > &vertex_distance_func, unsigned int p_level=0)
Order get_order () const
void print_info (std::ostream &os=libMesh::out) const
void scale (std::pair< Real, Real > old_range, std::pair< Real, Real > new_range)
virtual bool shapes_need_reinit ()
Static Public Member Functions
static std::unique_ptr< QBase > build (const std::string &name, const unsigned int dim, const Order order=INVALID_ORDER)
static std::unique_ptr< QBase > build (const QuadratureType qt, const unsigned int dim, const Order order=INVALID_ORDER)
static std::string get_info ()
static void print_info (std::ostream &out=libMesh::out)
static unsigned int n_objects ()
static void enable_print_counter_info ()
static void disable_print_counter_info ()
Public Attributes
bool allow_rules_with_negative_weights
Protected Types
typedef std::map< std::string, std::pair< unsigned int, unsigned int > > Counts
Protected Member Functions
QBase (const unsigned int _dim, const Order _order=INVALID_ORDER)
virtual void init_0D (const ElemType type=INVALID_ELEM, unsigned int p_level=0)
virtual void init_1D (const ElemType type=INVALID_ELEM, unsigned int p_level=0)=0
virtual void init_2D (const ElemType, unsigned int=0)
virtual void init_3D (const ElemType, unsigned int=0)
void tensor_product_quad (const QBase &q1D)
void tensor_product_hex (const QBase &q1D)
void tensor_product_prism (const QBase &q1D, const QBase &q2D)
void increment_constructor_count (const std::string &name)
void increment_destructor_count (const std::string &name)
Protected Attributes
const unsigned int _dim
const Order _order
ElemType _type
unsigned int _p_level
std::vector< Point > _points
std::vector< Real > _weights
Static Protected Attributes
static Counts _counts
static Threads::atomic< unsigned int > _n_objects
static Threads::spin_mutex _mutex
static bool _enable_print_counter = true
Friends
std::ostream & operator<< (std::ostream &os, const QBase &q)
Detailed Description
Base class for all quadrature families and orders.
The QBase class provides the basic functionality from which various quadrature rules can be derived. It computes and stores the quadrature points (in reference element space) and associated weights.
Author
Benjamin S. Kirk
Date
2002
Definition at line 54 of file quadrature.h.
Member Typedef Documentation
typedef std::map<std::string, std::pair<unsigned int, unsigned int> > libMesh::ReferenceCounter::Counts protected inherited
Data structure to log the information. The log is identified by the class name.
Definition at line 119 of file reference_counter.h.
Constructor & Destructor Documentation
libMesh::QBase::QBase (const unsigned int _dim, const Order _order = INVALID_ORDER) inline protected
Constructor. Protected to prevent instantiation of this base class. Use the build() method instead.
Definition at line 351 of file quadrature.h.
                             :
   allow_rules_with_negative_weights(true),
   _dim(d),
   _order(o),
   _type(INVALID_ELEM),
   _p_level(0)
 {
 }
virtual libMesh::QBase::~QBase () inline virtual
Destructor.
Definition at line 70 of file quadrature.h.
References build(), libMesh::INVALID_ORDER, libMesh::Quality::name(), and type().
 {}
Member Function Documentation
std::unique_ptr< QBase > libMesh::QBase::build (const std::string & name, const unsigned int dim, const Order order = INVALID_ORDER) static
Builds a specific quadrature rule based on the name string. This enables selection of the quadrature rule at run-time. The input parameter name must be mappable through the Utility::string_to_enum<>() function.
This function allocates memory, therefore a std::unique_ptr<QBase> is returned so that the user does not accidentally leak it.
Definition at line 39 of file quadrature_build.C.
Referenced by libMesh::InfFE< Dim, T_radial, T_map >::attach_quadrature_rule(), and ~QBase().
 {
   return QBase::build (Utility::string_to_enum<QuadratureType> (type),
                        _dim,
                        _order);
 }
std::unique_ptr< QBase > libMesh::QBase::build (const QuadratureType qt, const unsigned int dim, const Order order = INVALID_ORDER) static
Builds a specific quadrature rule based on the QuadratureType. This enables selection of the quadrature rule at run-time.
This function allocates memory, therefore a std::unique_ptr<QBase> is returned so that the user does not accidentally leak it.
Definition at line 50 of file quadrature_build.C.
References _dim, _order, libMesh::FIRST, libMesh::FORTYTHIRD, libMesh::out, libMesh::QCLOUGH, libMesh::QCONICAL, libMesh::QGAUSS, libMesh::QGAUSS_LOBATTO, libMesh::QGRID, libMesh::QGRUNDMANN_MOLLER, libMesh::QJACOBI_1_0, libMesh::QJACOBI_2_0, libMesh::QMONOMIAL, libMesh::QSIMPSON, libMesh::QTRAP, libMesh::THIRD, and libMesh::TWENTYTHIRD.
 {
   switch (_qt)
     {
     case QCLOUGH:
       {
 #ifdef DEBUG
         if (_order > TWENTYTHIRD)
           {
             libMesh::out << "WARNING: Clough quadrature implemented" << std::endl
                          << " up to TWENTYTHIRD order." << std::endl;
           }
 #endif
         return libmesh_make_unique<QClough>(_dim, _order);
       }
     case QGAUSS:
       {
 #ifdef DEBUG
         if (_order > FORTYTHIRD)
           {
             libMesh::out << "WARNING: Gauss quadrature implemented" << std::endl
                          << " up to FORTYTHIRD order." << std::endl;
           }
 #endif
         return libmesh_make_unique<QGauss>(_dim, _order);
       }
     case QJACOBI_1_0:
       {
 #ifdef DEBUG
         if (_order > FORTYTHIRD)
           {
             libMesh::out << "WARNING: Jacobi(1,0) quadrature implemented" << std::endl
                          << " up to FORTYTHIRD order." << std::endl;
           }
         if (_dim > 1)
           {
             libMesh::out << "WARNING: Jacobi(1,0) quadrature implemented" << std::endl
                          << " in 1D only." << std::endl;
           }
 #endif
         return libmesh_make_unique<QJacobi>(_dim, _order, 1, 0);
       }
     case QJACOBI_2_0:
       {
 #ifdef DEBUG
         if (_order > FORTYTHIRD)
           {
             libMesh::out << "WARNING: Jacobi(2,0) quadrature implemented" << std::endl
                          << " up to FORTYTHIRD order." << std::endl;
           }
         if (_dim > 1)
           {
             libMesh::out << "WARNING: Jacobi(2,0) quadrature implemented" << std::endl
                          << " in 1D only." << std::endl;
           }
 #endif
         return libmesh_make_unique<QJacobi>(_dim, _order, 2, 0);
       }
     case QSIMPSON:
       {
 #ifdef DEBUG
         if (_order > THIRD)
           {
             libMesh::out << "WARNING: Simpson rule provides only" << std::endl
                          << " THIRD order!" << std::endl;
           }
 #endif
         return libmesh_make_unique<QSimpson>(_dim);
       }
     case QTRAP:
       {
 #ifdef DEBUG
         if (_order > FIRST)
           {
             libMesh::out << "WARNING: Trapezoidal rule provides only" << std::endl
                          << " FIRST order!" << std::endl;
           }
 #endif
         return libmesh_make_unique<QTrap>(_dim);
       }
     case QGRID:
       return libmesh_make_unique<QGrid>(_dim, _order);
     case QGRUNDMANN_MOLLER:
       return libmesh_make_unique<QGrundmann_Moller>(_dim, _order);
     case QMONOMIAL:
       return libmesh_make_unique<QMonomial>(_dim, _order);
     case QGAUSS_LOBATTO:
       return libmesh_make_unique<QGaussLobatto>(_dim, _order);
     case QCONICAL:
       return libmesh_make_unique<QConical>(_dim, _order);
     default:
       libmesh_error_msg("ERROR: Bad qt=" << _qt);
     }
 }
void libMesh::ReferenceCounter::disable_print_counter_info () static inherited
Definition at line 107 of file reference_counter.C.
References libMesh::ReferenceCounter::_enable_print_counter.
Referenced by libMesh::LibMeshInit::LibMeshInit(), and libMesh::ReferenceCounter::n_objects().
 {
   _enable_print_counter = false;
   return;
 }
void libMesh::ReferenceCounter::enable_print_counter_info () static inherited
Methods to enable/disable the reference counter output from print_info()
Definition at line 101 of file reference_counter.C.
References libMesh::ReferenceCounter::_enable_print_counter.
Referenced by libMesh::ReferenceCounter::n_objects().
 {
   _enable_print_counter = true;
   return;
 }
unsigned int libMesh::QBase::get_dim () const inline
Returns
The spatial dimension of the quadrature rule.
Definition at line 123 of file quadrature.h.
References _dim.
Referenced by libMesh::InfFE< Dim, T_radial, T_map >::attach_quadrature_rule(), libMesh::QConical::conical_product_pyramid(), libMesh::QConical::conical_product_tet(), and libMesh::QConical::conical_product_tri().
 { return _dim; }
ElemType libMesh::QBase::get_elem_type () const inline
Returns
The element type we're currently using.
Definition at line 104 of file quadrature.h.
References _type.
 { return _type; }
std::string libMesh::ReferenceCounter::get_info () static inherited
Gets a string containing the reference information.
Definition at line 47 of file reference_counter.C.
References libMesh::ReferenceCounter::_counts, and libMesh::Quality::name().
Referenced by libMesh::ReferenceCounter::print_info().
 {
 #if defined(LIBMESH_ENABLE_REFERENCE_COUNTING) && defined(DEBUG)
   std::ostringstream oss;
   oss << '\n'
       << " ---------------------------------------------------------------------------- \n"
       << "| Reference count information                                                |\n"
       << " ---------------------------------------------------------------------------- \n";
   for (Counts::iterator it = _counts.begin();
        it != _counts.end(); ++it)
     {
       const std::string name(it->first);
       const unsigned int creations    = it->second.first;
       const unsigned int destructions = it->second.second;
       oss << "| " << name << " reference count information:\n"
           << "|  Creations:    " << creations    << '\n'
           << "|  Destructions: " << destructions << '\n';
     }
   oss << " ---------------------------------------------------------------------------- \n";
   return oss.str();
 #else
   return "";
 #endif
 }
Order libMesh::QBase::get_order () const inline
Returns
The order of the quadrature rule.
Definition at line 190 of file quadrature.h.
References _order, _p_level, operator<<, libMesh::out, print_info(), and scale().
Referenced by libMesh::InfFE< Dim, T_radial, T_map >::attach_quadrature_rule().
 { return static_cast<Order>(_order + _p_level); }
unsigned int libMesh::QBase::get_p_level () const inline
Returns
The p-refinement level we're currently using.
Definition at line 109 of file quadrature.h.
References _p_level.
 { return _p_level; }
const std::vector<Point>& libMesh::QBase::get_points () const inline
Returns
A std::vector containing the quadrature point locations in reference element space.
Definition at line 129 of file quadrature.h.
References _points.
Referenced by libMesh::FESubdivision::attach_quadrature_rule(), libMesh::QClough::init_1D(), libMesh::QConical::init_1D(), libMesh::QMonomial::init_1D(), libMesh::QGrundmann_Moller::init_1D(), libMesh::QClough::init_2D(), libMesh::QGauss::init_2D(), libMesh::QMonomial::init_2D(), libMesh::QGauss::init_3D(), and libMesh::QMonomial::init_3D().
 { return _points; }
std::vector<Point>& libMesh::QBase::get_points () inline
Returns
A std::vector containing the quadrature point locations in reference element space as a writable reference.
Definition at line 135 of file quadrature.h.
References _points.
 { return _points; }
const std::vector<Real>& libMesh::QBase::get_weights () const inline
Returns
A constant reference to a std::vector containing the quadrature weights.
Definition at line 141 of file quadrature.h.
References _weights.
Referenced by libMesh::FESubdivision::attach_quadrature_rule(), libMesh::QClough::init_1D(), libMesh::QConical::init_1D(), libMesh::QMonomial::init_1D(), libMesh::QGrundmann_Moller::init_1D(), libMesh::QClough::init_2D(), libMesh::QGauss::init_2D(), libMesh::QMonomial::init_2D(), libMesh::QGauss::init_3D(), and libMesh::QMonomial::init_3D().
 { return _weights; }
std::vector<Real>& libMesh::QBase::get_weights () inline
Returns
A writable references to a std::vector containing the quadrature weights.
Definition at line 147 of file quadrature.h.
References _weights.
 { return _weights; }
void libMesh::ReferenceCounter::increment_constructor_count (const std::string & name) inline protected inherited
Increments the construction counter. Should be called in the constructor of any derived class that will be reference counted.
Definition at line 185 of file reference_counter.h.
References libMesh::ReferenceCounter::_counts, libMesh::Quality::name(), and libMesh::Threads::spin_mtx.
Referenced by libMesh::ReferenceCounter::n_objects(), and libMesh::ReferenceCountedObject< RBParametrized >::ReferenceCountedObject().
 {
   Threads::spin_mutex::scoped_lock lock(Threads::spin_mtx);
   std::pair<unsigned int, unsigned int> & p = _counts[name];
   p.first++;
 }
void libMesh::ReferenceCounter::increment_destructor_count (const std::string & name) inline protected inherited
Increments the destruction counter. Should be called in the destructor of any derived class that will be reference counted.
Definition at line 198 of file reference_counter.h.
References libMesh::ReferenceCounter::_counts, libMesh::Quality::name(), and libMesh::Threads::spin_mtx.
Referenced by libMesh::ReferenceCounter::n_objects(), and libMesh::ReferenceCountedObject< RBParametrized >::~ReferenceCountedObject().
 {
   Threads::spin_mutex::scoped_lock lock(Threads::spin_mtx);
   std::pair<unsigned int, unsigned int> & p = _counts[name];
   p.second++;
 }
void libMesh::QBase::init (const ElemType type = INVALID_ELEM, unsigned int p_level = 0) virtual
Initializes the data structures for a quadrature rule for an element of type type.
Definition at line 28 of file quadrature.C.
References _dim, _p_level, _type, init_0D(), init_1D(), init_2D(), and init_3D().
Referenced by libMesh::FESubdivision::attach_quadrature_rule(), init(), libMesh::QClough::init_1D(), libMesh::QMonomial::init_1D(), libMesh::QClough::init_2D(), libMesh::QGaussLobatto::init_2D(), libMesh::QTrap::init_2D(), libMesh::QGrid::init_2D(), libMesh::QSimpson::init_2D(), libMesh::QGauss::init_2D(), libMesh::QMonomial::init_2D(), libMesh::QGaussLobatto::init_3D(), libMesh::QTrap::init_3D(), libMesh::QGrid::init_3D(), libMesh::QGauss::init_3D(), libMesh::QSimpson::init_3D(), libMesh::QMonomial::init_3D(), libMesh::QGauss::QGauss(), libMesh::QGaussLobatto::QGaussLobatto(), libMesh::QJacobi::QJacobi(), libMesh::QSimpson::QSimpson(), libMesh::QTrap::QTrap(), and w().
 {
   // check to see if we have already
   // done the work for this quadrature rule
   if (t == _type && p == _p_level)
     return;
   else
     {
       _type = t;
       _p_level = p;
     }
   switch(_dim)
     {
     case 0:
       this->init_0D(_type,_p_level);
       return;
     case 1:
       this->init_1D(_type,_p_level);
       return;
     case 2:
       this->init_2D(_type,_p_level);
       return;
     case 3:
       this->init_3D(_type,_p_level);
       return;
     default:
       libmesh_error_msg("Invalid dimension _dim = " << _dim);
     }
 }
void libMesh::QBase::init (const Elem & elem, const std::vector< Real > & vertex_distance_func, unsigned int p_level = 0) virtual
Initializes the data structures for an element potentially "cut" by a signed distance function. The array vertex_distance_func contains vertex values of the signed distance function. If the signed distance function changes sign on the vertices, then the element is considered to be cut.) This interface can be extended by derived classes in order to subdivide the element and construct a composite quadrature rule.
Definition at line 72 of file quadrature.C.
References init(), and libMesh::Elem::type().
 {
   // dispatch generic implementation
   this->init(elem.type(), p_level);
 }
void libMesh::QBase::init_0D (const ElemType type = INVALID_ELEM, unsigned int p_level = 0) protected virtual
Initializes the 0D quadrature rule by filling the points and weights vectors with the appropriate values. Generally this is just one point with weight 1.
Definition at line 82 of file quadrature.C.
References _points, and _weights.
Referenced by init().
 {
   _points.resize(1);
   _weights.resize(1);
   _points[0] = Point(0.);
   _weights[0] = 1.0;
 }
virtual void libMesh::QBase::init_1D (const ElemType type = INVALID_ELEM, unsigned int p_level = 0) protected pure virtual
Initializes the 1D quadrature rule by filling the points and weights vectors with the appropriate values. The order of the rule will be defined by the implementing class. It is assumed that derived quadrature rules will at least define the init_1D function, therefore it is pure virtual.
Implemented in libMesh::QGrundmann_Moller, libMesh::QMonomial, libMesh::QJacobi, libMesh::QGauss, libMesh::QSimpson, libMesh::QGrid, libMesh::QTrap, libMesh::QConical, libMesh::QGaussLobatto, and libMesh::QClough.
Referenced by init().
virtual void libMesh::QBase::init_2D (const ElemType , unsigned int = 0) inline protected virtual
Initializes the 2D quadrature rule by filling the points and weights vectors with the appropriate values. The order of the rule will be defined by the implementing class. Should not be pure virtual since a derived quadrature rule may only be defined in 1D. If not redefined, gives an error (when DEBUG is defined) when called.
Reimplemented in libMesh::QGrundmann_Moller, libMesh::QMonomial, libMesh::QGauss, libMesh::QSimpson, libMesh::QConical, libMesh::QGrid, libMesh::QTrap, libMesh::QGaussLobatto, and libMesh::QClough.
Definition at line 264 of file quadrature.h.
Referenced by init().
   {
 #ifdef DEBUG
     libmesh_error_msg("ERROR: Seems as if this quadrature rule \nis not implemented for 2D.");
 #endif
   }
virtual void libMesh::QBase::init_3D (const ElemType , unsigned int = 0) inline protected virtual
Initializes the 3D quadrature rule by filling the points and weights vectors with the appropriate values. The order of the rule will be defined by the implementing class. Should not be pure virtual since a derived quadrature rule may only be defined in 1D. If not redefined, gives an error (when DEBUG is defined) when called.
Reimplemented in libMesh::QGrundmann_Moller, libMesh::QMonomial, libMesh::QConical, libMesh::QGauss, libMesh::QSimpson, libMesh::QGrid, libMesh::QTrap, libMesh::QGaussLobatto, and libMesh::QClough.
Definition at line 280 of file quadrature.h.
References tensor_product_hex(), tensor_product_prism(), and tensor_product_quad().
Referenced by init().
   {
 #ifdef DEBUG
     libmesh_error_msg("ERROR: Seems as if this quadrature rule \nis not implemented for 3D.");
 #endif
   }
static unsigned int libMesh::ReferenceCounter::n_objects () inline static inherited
Prints the number of outstanding (created, but not yet destroyed) objects.
Definition at line 85 of file reference_counter.h.
References libMesh::ReferenceCounter::_n_objects, libMesh::ReferenceCounter::disable_print_counter_info(), libMesh::ReferenceCounter::enable_print_counter_info(), libMesh::ReferenceCounter::increment_constructor_count(), libMesh::ReferenceCounter::increment_destructor_count(), and libMesh::Quality::name().
Referenced by libMesh::System::hide_output(), and libMesh::LibMeshInit::LibMeshInit().
   { return _n_objects; }
unsigned int libMesh::QBase::n_points () const inline
Returns
The number of points associated with the quadrature rule.
Definition at line 114 of file quadrature.h.
References _points.
Referenced by libMesh::ExactSolution::_compute_error(), libMesh::System::calculate_norm(), libMesh::FirstOrderUnsteadySolver::compute_second_order_eqns(), libMesh::QConical::conical_product_pyramid(), libMesh::QConical::conical_product_tet(), libMesh::QConical::conical_product_tri(), print_info(), tensor_product_hex(), tensor_product_prism(), and tensor_product_quad().
   {
     libmesh_assert (!_points.empty());
     return cast_int<unsigned int>(_points.size());
   }
void libMesh::ReferenceCounter::print_info (std::ostream & out = libMesh::out) static inherited
Prints the reference information, by default to libMesh::out.
Definition at line 88 of file reference_counter.C.
References libMesh::ReferenceCounter::_enable_print_counter, and libMesh::ReferenceCounter::get_info().
Referenced by libMesh::LibMeshInit::LibMeshInit().
 {
   if (_enable_print_counter)
     out_stream << ReferenceCounter::get_info();
 }
void libMesh::QBase::print_info (std::ostream & os = libMesh::out) const inline
Prints information relevant to the quadrature rule, by default to libMesh::out.
Definition at line 365 of file quadrature.h.
References _points, _weights, n_points(), and libMesh::Real.
Referenced by get_order(), and libMesh::operator<<().
 {
   libmesh_assert(!_points.empty());
   libmesh_assert(!_weights.empty());
   Real summed_weights=0;
   os << "N_Q_Points=" << this->n_points() << std::endl << std::endl;
   for (unsigned int qpoint=0; qpoint<this->n_points(); qpoint++)
     {
       os << " Point " << qpoint << ":\n"
          << "  "
          << _points[qpoint]
          << "\n Weight:\n "
          << "  w=" << _weights[qpoint] << "\n" << std::endl;
       summed_weights += _weights[qpoint];
     }
   os << "Summed Weights: " << summed_weights << std::endl;
 }
Point libMesh::QBase::qp (const unsigned int i) const inline
Returns
The quadrature point in reference element space.
Definition at line 152 of file quadrature.h.
References _points.
Referenced by libMesh::QConical::conical_product_pyramid(), libMesh::QConical::conical_product_tet(), libMesh::QConical::conical_product_tri(), tensor_product_hex(), tensor_product_prism(), and tensor_product_quad().
   {
     libmesh_assert_less (i, _points.size());
     return _points[i];
   }
void libMesh::QBase::scale (std::pair< Real, Real > old_range, std::pair< Real, Real > new_range)
Maps the points of a 1D quadrature rule defined by "old_range" to another 1D interval defined by "new_range" and scales the weights accordingly.
Definition at line 93 of file quadrature.C.
References _dim, _points, _weights, and libMesh::Real.
Referenced by libMesh::QConical::conical_product_tet(), libMesh::QConical::conical_product_tri(), and get_order().
 {
   // Make sure we are in 1D
   libmesh_assert_equal_to (_dim, 1);
   Real
     h_new = new_range.second - new_range.first,
     h_old = old_range.second - old_range.first;
   // Make sure that we have sane ranges
   libmesh_assert_greater (h_new, 0.);
   libmesh_assert_greater (h_old, 0.);
   // Make sure there are some points
   libmesh_assert_greater (_points.size(), 0);
   // Compute the scale factor
   Real scfact = h_new/h_old;
   // We're mapping from old_range -> new_range
   for (std::size_t i=0; i<_points.size(); i++)
     {
       _points[i](0) = new_range.first +
         (_points[i](0) - old_range.first) * scfact;
       // Scale the weights
       _weights[i] *= scfact;
     }
 }
virtual bool libMesh::QBase::shapes_need_reinit () inline virtual
Returns
true if the shape functions need to be recalculated, false otherwise.
This may be required if the number of quadrature points or their position changes.
Definition at line 218 of file quadrature.h.
 { return false; }
void libMesh::QBase::tensor_product_hex (const QBase & q1D) protected
Computes the tensor product quadrature rule [q1D x q1D x q1D] from the 1D rule q1D. Used in the init_3D routines for hexahedral element types.
Definition at line 154 of file quadrature.C.
References _points, _weights, n_points(), qp(), and w().
Referenced by libMesh::QGaussLobatto::init_3D(), libMesh::QGrid::init_3D(), libMesh::QTrap::init_3D(), libMesh::QGauss::init_3D(), libMesh::QSimpson::init_3D(), and init_3D().
 {
   const unsigned int np = q1D.n_points();
   _points.resize(np * np * np);
   _weights.resize(np * np * np);
   unsigned int q=0;
   for (unsigned int k=0; k<np; k++)
     for (unsigned int j=0; j<np; j++)
       for (unsigned int i=0; i<np; i++)
         {
           _points[q](0) = q1D.qp(i)(0);
           _points[q](1) = q1D.qp(j)(0);
           _points[q](2) = q1D.qp(k)(0);
           _weights[q] = q1D.w(i) * q1D.w(j) * q1D.w(k);
           q++;
         }
 }
void libMesh::QBase::tensor_product_prism (const QBase & q1D, const QBase & q2D) protected
Computes the tensor product of a 1D quadrature rule and a 2D quadrature rule. Used in the init_3D routines for prismatic element types.
Definition at line 181 of file quadrature.C.
References _points, _weights, n_points(), qp(), and w().
Referenced by libMesh::QGrid::init_3D(), libMesh::QTrap::init_3D(), libMesh::QSimpson::init_3D(), libMesh::QGauss::init_3D(), and init_3D().
 {
   const unsigned int n_points1D = q1D.n_points();
   const unsigned int n_points2D = q2D.n_points();
   _points.resize  (n_points1D * n_points2D);
   _weights.resize (n_points1D * n_points2D);
   unsigned int q=0;
   for (unsigned int j=0; j<n_points1D; j++)
     for (unsigned int i=0; i<n_points2D; i++)
       {
         _points[q](0) = q2D.qp(i)(0);
         _points[q](1) = q2D.qp(i)(1);
         _points[q](2) = q1D.qp(j)(0);
         _weights[q] = q2D.w(i) * q1D.w(j);
         q++;
       }
 }
void libMesh::QBase::tensor_product_quad (const QBase & q1D) protected
Constructs a 2D rule from the tensor product of q1D with itself. Used in the init_2D() routines for quadrilateral element types.
Definition at line 127 of file quadrature.C.
References _points, _weights, n_points(), qp(), and w().
Referenced by libMesh::QGaussLobatto::init_2D(), libMesh::QGrid::init_2D(), libMesh::QTrap::init_2D(), libMesh::QGauss::init_2D(), libMesh::QSimpson::init_2D(), and init_3D().
 {
   const unsigned int np = q1D.n_points();
   _points.resize(np * np);
   _weights.resize(np * np);
   unsigned int q=0;
   for (unsigned int j=0; j<np; j++)
     for (unsigned int i=0; i<np; i++)
       {
         _points[q](0) = q1D.qp(i)(0);
         _points[q](1) = q1D.qp(j)(0);
         _weights[q] = q1D.w(i)*q1D.w(j);
         q++;
       }
 }
virtual QuadratureType libMesh::QBase::type () const pure virtual
Returns
The quadrature type in derived classes.
Implemented in libMesh::QGrundmann_Moller, libMesh::QJacobi, libMesh::QMonomial, libMesh::QGauss, libMesh::QSimpson, libMesh::QTrap, libMesh::QGrid, libMesh::QConical, libMesh::QGaussLobatto, and libMesh::QClough.
Referenced by libMesh::InfFE< Dim, T_radial, T_map >::attach_quadrature_rule(), w(), and ~QBase().
Real libMesh::QBase::w (const unsigned int i) const inline
Returns
The quadrature weight.
Definition at line 161 of file quadrature.h.
References _weights, init(), libMesh::INVALID_ELEM, and type().
Referenced by libMesh::QConical::conical_product_pyramid(), libMesh::QConical::conical_product_tet(), libMesh::QConical::conical_product_tri(), tensor_product_hex(), tensor_product_prism(), and tensor_product_quad().
   {
     libmesh_assert_less (i, _weights.size());
     return _weights[i];
   }
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & os, const QBase & q) friend
Same as above, but allows you to use the stream syntax.
Definition at line 208 of file quadrature.C.
Referenced by get_order().
 {
   q.print_info(os);
   return os;
 }
Member Data Documentation
ReferenceCounter::Counts libMesh::ReferenceCounter::_counts static protected inherited
Actually holds the data.
Definition at line 124 of file reference_counter.h.
Referenced by libMesh::ReferenceCounter::get_info(), libMesh::ReferenceCounter::increment_constructor_count(), and libMesh::ReferenceCounter::increment_destructor_count().
const unsigned int libMesh::QBase::_dim protected
The spatial dimension of the quadrature rule.
Definition at line 312 of file quadrature.h.
Referenced by build(), get_dim(), init(), libMesh::QGaussLobatto::QGaussLobatto(), and scale().
bool libMesh::ReferenceCounter::_enable_print_counter = true static protected inherited
Flag to control whether reference count information is printed when print_info is called.
Definition at line 143 of file reference_counter.h.
Referenced by libMesh::ReferenceCounter::disable_print_counter_info(), libMesh::ReferenceCounter::enable_print_counter_info(), and libMesh::ReferenceCounter::print_info().
Threads::spin_mutex libMesh::ReferenceCounter::_mutex static protected inherited
Mutual exclusion object to enable thread-safe reference counting.
Definition at line 137 of file reference_counter.h.
Threads::atomic< unsigned int > libMesh::ReferenceCounter::_n_objects static protected inherited
The number of objects. Print the reference count information when the number returns to 0.
Definition at line 132 of file reference_counter.h.
Referenced by libMesh::ReferenceCounter::n_objects(), libMesh::ReferenceCounter::ReferenceCounter(), and libMesh::ReferenceCounter::~ReferenceCounter().
const Order libMesh::QBase::_order protected
The polynomial order which the quadrature rule is capable of integrating exactly.
Definition at line 318 of file quadrature.h.
Referenced by build(), libMesh::QConical::conical_product_pyramid(), libMesh::QConical::conical_product_tet(), libMesh::QConical::conical_product_tri(), get_order(), libMesh::QClough::init_1D(), libMesh::QGaussLobatto::init_1D(), libMesh::QConical::init_1D(), libMesh::QGrid::init_1D(), libMesh::QGauss::init_1D(), libMesh::QJacobi::init_1D(), libMesh::QMonomial::init_1D(), libMesh::QGrundmann_Moller::init_1D(), libMesh::QClough::init_2D(), libMesh::QGaussLobatto::init_2D(), libMesh::QGrid::init_2D(), libMesh::QGauss::init_2D(), libMesh::QMonomial::init_2D(), libMesh::QGrundmann_Moller::init_2D(), libMesh::QGaussLobatto::init_3D(), libMesh::QGrid::init_3D(), libMesh::QGauss::init_3D(), libMesh::QMonomial::init_3D(), and libMesh::QGrundmann_Moller::init_3D().
unsigned int libMesh::QBase::_p_level protected
The p-level of the element for which the current values have been computed.
Definition at line 330 of file quadrature.h.
Referenced by get_order(), get_p_level(), and init().
std::vector<Point> libMesh::QBase::_points protected
The locations of the quadrature points in reference element space.
Definition at line 336 of file quadrature.h.
Referenced by libMesh::QConical::conical_product_pyramid(), libMesh::QConical::conical_product_tet(), libMesh::QConical::conical_product_tri(), libMesh::QGauss::dunavant_rule(), libMesh::QGauss::dunavant_rule2(), get_points(), libMesh::QGrundmann_Moller::gm_rule(), init_0D(), libMesh::QClough::init_1D(), libMesh::QGaussLobatto::init_1D(), libMesh::QConical::init_1D(), libMesh::QTrap::init_1D(), libMesh::QGrid::init_1D(), libMesh::QSimpson::init_1D(), libMesh::QGauss::init_1D(), libMesh::QJacobi::init_1D(), libMesh::QMonomial::init_1D(), libMesh::QGrundmann_Moller::init_1D(), libMesh::QClough::init_2D(), libMesh::QTrap::init_2D(), libMesh::QGrid::init_2D(), libMesh::QSimpson::init_2D(), libMesh::QGauss::init_2D(), libMesh::QMonomial::init_2D(), libMesh::QGrid::init_3D(), libMesh::QTrap::init_3D(), libMesh::QGauss::init_3D(), libMesh::QSimpson::init_3D(), libMesh::QMonomial::init_3D(), libMesh::QGrundmann_Moller::init_3D(), libMesh::QGauss::keast_rule(), libMesh::QMonomial::kim_rule(), n_points(), print_info(), qp(), scale(), libMesh::QMonomial::stroud_rule(), tensor_product_hex(), tensor_product_prism(), tensor_product_quad(), and libMesh::QMonomial::wissmann_rule().
ElemType libMesh::QBase::_type protected
The type of element for which the current values have been computed.
Definition at line 324 of file quadrature.h.
Referenced by get_elem_type(), init(), libMesh::QClough::type(), libMesh::QGaussLobatto::type(), libMesh::QConical::type(), libMesh::QGrid::type(), libMesh::QTrap::type(), libMesh::QGauss::type(), libMesh::QSimpson::type(), libMesh::QMonomial::type(), and libMesh::QGrundmann_Moller::type().
std::vector<Real> libMesh::QBase::_weights protected
The quadrature weights. The order of the weights matches the ordering of the _points vector.
Definition at line 342 of file quadrature.h.
Referenced by libMesh::QConical::conical_product_pyramid(), libMesh::QConical::conical_product_tet(), libMesh::QConical::conical_product_tri(), libMesh::QGauss::dunavant_rule(), libMesh::QGauss::dunavant_rule2(), get_weights(), libMesh::QGrundmann_Moller::gm_rule(), init_0D(), libMesh::QClough::init_1D(), libMesh::QGaussLobatto::init_1D(), libMesh::QConical::init_1D(), libMesh::QTrap::init_1D(), libMesh::QGrid::init_1D(), libMesh::QSimpson::init_1D(), libMesh::QGauss::init_1D(), libMesh::QJacobi::init_1D(), libMesh::QMonomial::init_1D(), libMesh::QGrundmann_Moller::init_1D(), libMesh::QClough::init_2D(), libMesh::QTrap::init_2D(), libMesh::QGrid::init_2D(), libMesh::QGauss::init_2D(), libMesh::QSimpson::init_2D(), libMesh::QMonomial::init_2D(), libMesh::QGrid::init_3D(), libMesh::QTrap::init_3D(), libMesh::QSimpson::init_3D(), libMesh::QGauss::init_3D(), libMesh::QMonomial::init_3D(), libMesh::QGrundmann_Moller::init_3D(), libMesh::QGauss::keast_rule(), libMesh::QMonomial::kim_rule(), print_info(), scale(), libMesh::QMonomial::stroud_rule(), tensor_product_hex(), tensor_product_prism(), tensor_product_quad(), w(), and libMesh::QMonomial::wissmann_rule().
bool libMesh::QBase::allow_rules_with_negative_weights
Flag (default true) controlling the use of quadrature rules with negative weights. Set this to false to require rules with all positive weights.
Rules with negative weights can be unsuitable for some problems. For example, it is possible for a rule with negative weights to obtain a negative result when integrating a positive function.
A particular example: if rules with negative weights are not allowed, a request for TET,THIRD (5 points) will return the TET,FIFTH (14 points) rule instead, nearly tripling the computational effort required!
Definition at line 233 of file quadrature.h.
Referenced by libMesh::QGrundmann_Moller::init_2D(), libMesh::QGauss::init_3D(), libMesh::QMonomial::init_3D(), and libMesh::QGrundmann_Moller::init_3D().
The documentation for this class was generated from the following files:
quadrature.h
quadrature.C
quadrature_build.C