libMesh: libMesh::NumericVector< T > Class Template Reference
SomeWebsiteLogo
libMesh::NumericVector< T > Class Template Reference abstract
#include <diff_context.h>
Public Member Functions
NumericVector (const Parallel::Communicator &comm_in, const ParallelType ptype=AUTOMATIC)
NumericVector (const Parallel::Communicator &comm_in, const numeric_index_type n, const ParallelType ptype=AUTOMATIC)
NumericVector (const Parallel::Communicator &comm_in, const numeric_index_type n, const numeric_index_type n_local, const ParallelType ptype=AUTOMATIC)
NumericVector (const Parallel::Communicator &comm_in, const numeric_index_type N, const numeric_index_type n_local, const std::vector< numeric_index_type > &ghost, const ParallelType ptype=AUTOMATIC)
virtual ~NumericVector ()
virtual bool initialized () const
ParallelType type () const
ParallelType & type ()
virtual bool closed () const
virtual void close ()=0
virtual void clear ()
virtual void zero ()=0
virtual UniquePtr< NumericVector< T > > zero_clone () const =0
virtual UniquePtr< NumericVector< T > > clone () const =0
virtual void init (const numeric_index_type, const numeric_index_type, const bool=false, const ParallelType=AUTOMATIC)=0
virtual void init (const numeric_index_type, const bool=false, const ParallelType=AUTOMATIC)=0
virtual void init (const numeric_index_type, const numeric_index_type, const std::vector< numeric_index_type > &, const bool=false, const ParallelType=AUTOMATIC)=0
virtual void init (const NumericVector< T > &other, const bool fast=false)=0
virtual NumericVector< T > & operator= (const T s)=0
virtual NumericVector< T > & operator= (const NumericVector< T > &V)=0
virtual NumericVector< T > & operator= (const std::vector< T > &v)=0
virtual Real min () const =0
virtual Real max () const =0
virtual T sum () const =0
virtual Real l1_norm () const =0
virtual Real l2_norm () const =0
virtual Real linfty_norm () const =0
virtual Real subset_l1_norm (const std::set< numeric_index_type > &indices) const
virtual Real subset_l2_norm (const std::set< numeric_index_type > &indices) const
virtual Real subset_linfty_norm (const std::set< numeric_index_type > &indices) const
virtual numeric_index_type size () const =0
virtual numeric_index_type local_size () const =0
virtual numeric_index_type first_local_index () const =0
virtual numeric_index_type last_local_index () const =0
virtual T operator() (const numeric_index_type i) const =0
virtual T el (const numeric_index_type i) const
virtual void get (const std::vector< numeric_index_type > &index, T *values) const
void get (const std::vector< numeric_index_type > &index, std::vector< T > &values) const
virtual NumericVector< T > & operator+= (const NumericVector< T > &V)=0
virtual NumericVector< T > & operator-= (const NumericVector< T > &V)=0
NumericVector< T > & operator*= (const T a)
NumericVector< T > & operator/= (const T a)
virtual NumericVector< T > & operator/= (NumericVector< T > &)=0
virtual void reciprocal ()=0
virtual void conjugate ()=0
virtual void set (const numeric_index_type i, const T value)=0
virtual void add (const numeric_index_type i, const T value)=0
virtual void add (const T s)=0
virtual void add (const NumericVector< T > &V)=0
virtual void add (const T a, const NumericVector< T > &v)=0
virtual void add_vector (const T *v, const std::vector< numeric_index_type > &dof_indices)
void add_vector (const std::vector< T > &v, const std::vector< numeric_index_type > &dof_indices)
virtual void add_vector (const NumericVector< T > &V, const std::vector< numeric_index_type > &dof_indices)
void add_vector (const DenseVector< T > &V, const std::vector< numeric_index_type > &dof_indices)
virtual void add_vector (const NumericVector< T > &, const SparseMatrix< T > &)=0
void add_vector (const NumericVector< T > &v, const ShellMatrix< T > &a)
virtual void add_vector_transpose (const NumericVector< T > &, const SparseMatrix< T > &)=0
virtual void insert (const T *v, const std::vector< numeric_index_type > &dof_indices)
void insert (const std::vector< T > &v, const std::vector< numeric_index_type > &dof_indices)
virtual void insert (const NumericVector< T > &V, const std::vector< numeric_index_type > &dof_indices)
void insert (const DenseVector< T > &V, const std::vector< numeric_index_type > &dof_indices)
void insert (const DenseSubVector< T > &V, const std::vector< numeric_index_type > &dof_indices)
virtual void scale (const T factor)=0
virtual void abs ()=0
virtual T dot (const NumericVector< T > &) const =0
virtual void localize (std::vector< T > &v_local) const =0
virtual void localize (NumericVector< T > &v_local) const =0
virtual void localize (NumericVector< T > &v_local, const std::vector< numeric_index_type > &send_list) const =0
virtual void localize (std::vector< T > &, const std::vector< numeric_index_type > &) const =0
virtual void localize (const numeric_index_type first_local_idx, const numeric_index_type last_local_idx, const std::vector< numeric_index_type > &send_list)=0
virtual void localize_to_one (std::vector< T > &v_local, const processor_id_type proc_id=0) const =0
virtual int compare (const NumericVector< T > &other_vector, const Real threshold=TOLERANCE) const
virtual int local_relative_compare (const NumericVector< T > &other_vector, const Real threshold=TOLERANCE) const
virtual int global_relative_compare (const NumericVector< T > &other_vector, const Real threshold=TOLERANCE) const
virtual void pointwise_mult (const NumericVector< T > &vec1, const NumericVector< T > &vec2)=0
virtual void print (std::ostream &os=libMesh::out) const
virtual void print_global (std::ostream &os=libMesh::out) const
virtual void print_matlab (const std::string &="") const
virtual void create_subvector (NumericVector< T > &, const std::vector< numeric_index_type > &) const
virtual void swap (NumericVector< T > &v)
template<>
void print (std::ostream &os) const
template<>
void print_global (std::ostream &os) const
const Parallel::Communicator & comm () const
processor_id_type n_processors () const
processor_id_type processor_id () const
Static Public Member Functions
static UniquePtr< NumericVector< T > > build (const Parallel::Communicator &comm, const SolverPackage solver_package=libMesh::default_solver_package())
static UniquePtr< NumericVector< T > > build (const SolverPackage solver_package=libMesh::default_solver_package())
static std::string get_info ()
static void print_info (std::ostream &out=libMesh::out)
static unsigned int n_objects ()
static void enable_print_counter_info ()
static void disable_print_counter_info ()
Protected Types
typedef std::map< std::string, std::pair< unsigned int, unsigned int > > Counts
Protected Member Functions
void increment_constructor_count (const std::string &name)
void increment_destructor_count (const std::string &name)
Protected Attributes
bool _is_closed
bool _is_initialized
ParallelType _type
const Parallel::Communicator & _communicator
Static Protected Attributes
static Counts _counts
static Threads::atomic< unsigned int > _n_objects
static Threads::spin_mutex _mutex
static bool _enable_print_counter = true
Friends
std::ostream & operator<< (std::ostream &os, const NumericVector< T > &v)
Detailed Description
template<typename T>
class libMesh::NumericVector< T >
Numeric vector. Provides a uniform interface to vector storage schemes for different linear algebra libraries.
Author
Benjamin S. Kirk
Date
2003
Definition at line 39 of file diff_context.h.
Member Typedef Documentation
typedef std::map<std::string, std::pair<unsigned int, unsigned int> > libMesh::ReferenceCounter::Counts protected inherited
Data structure to log the information. The log is identified by the class name.
Definition at line 110 of file reference_counter.h.
Constructor & Destructor Documentation
template<typename T > libMesh::NumericVector< T >::NumericVector (const Parallel::Communicator & comm_in, const ParallelType ptype = AUTOMATIC) inline explicit
Dummy-Constructor. Dimension=0
Definition at line 728 of file numeric_vector.h.
                                                            :
   ParallelObject(comm_in),
   _is_closed(false),
   _is_initialized(false),
   _type(ptype)
 {
 }
template<typename T > libMesh::NumericVector< T >::NumericVector (const Parallel::Communicator & comm_in, const numeric_index_type n, const ParallelType ptype = AUTOMATIC) inline explicit
Constructor. Set dimension to n and initialize all elements with zero.
Definition at line 741 of file numeric_vector.h.
                                                            :
   ParallelObject(comm_in),
   _is_closed(false),
   _is_initialized(false),
   _type(ptype)
 {
   libmesh_not_implemented(); // Abstract base class!
   // init(n, n, false, ptype);
 }
template<typename T > libMesh::NumericVector< T >::NumericVector (const Parallel::Communicator & comm_in, const numeric_index_type n, const numeric_index_type n_local, const ParallelType ptype = AUTOMATIC) inline
Constructor. Set local dimension to n_local, the global dimension to n, and initialize all elements with zero.
Definition at line 757 of file numeric_vector.h.
                                                            :
   ParallelObject(comm_in),
   _is_closed(false),
   _is_initialized(false),
   _type(ptype)
 {
   libmesh_not_implemented(); // Abstract base class!
   // init(n, n_local, false, ptype);
 }
template<typename T > libMesh::NumericVector< T >::NumericVector (const Parallel::Communicator & comm_in, const numeric_index_type N, const numeric_index_type n_local, const std::vector< numeric_index_type > & ghost, const ParallelType ptype = AUTOMATIC) inline
Constructor. Set local dimension to n_local, the global dimension to n, but additionally reserve memory for the indices specified by the ghost argument.
Definition at line 774 of file numeric_vector.h.
                                                            :
   ParallelObject(comm_in),
   _is_closed(false),
   _is_initialized(false),
   _type(ptype)
 {
   libmesh_not_implemented(); // Abstract base class!
   // init(n, n_local, ghost, false, ptype);
 }
template<typename T > libMesh::NumericVector< T >::~NumericVector () inline virtual
Destructor, deallocates memory. Made virtual to allow for derived classes to behave properly.
Definition at line 792 of file numeric_vector.h.
References libMesh::NumericVector< T >::clear().
 {
   clear ();
 }
Member Function Documentation
template<typename T> virtual void libMesh::NumericVector< T >::abs () pure virtual
v = abs(v)... that is, each entry in v is replaced by its absolute value.
Implemented in libMesh::PetscVector< T >, libMesh::EpetraVector< T >, libMesh::DistributedVector< T >, libMesh::EigenSparseVector< T >, and libMesh::LaspackVector< T >.
Referenced by libMesh::NumericVector< Number >::operator/=().
template<typename T> virtual void libMesh::NumericVector< T >::add (const numeric_index_type i, const T value) pure virtual
v(i) += value
Implemented in libMesh::PetscVector< T >, libMesh::EpetraVector< T >, libMesh::EigenSparseVector< T >, libMesh::LaspackVector< T >, and libMesh::DistributedVector< T >.
Referenced by libMesh::NewmarkSolver::advance_timestep(), libMesh::EquationSystems::build_parallel_solution_vector(), libMesh::ContinuationSystem::continuation_solve(), libMesh::ContinuationSystem::initialize_tangent(), libMesh::NewtonSolver::line_search(), libMesh::NumericVector< Number >::operator/=(), libMesh::NewtonSolver::solve(), libMesh::ContinuationSystem::solve_tangent(), libMesh::NewmarkSystem::update_rhs(), libMesh::ContinuationSystem::update_solution(), libMesh::NewmarkSystem::update_u_v_a(), and libMesh::TensorShellMatrix< T >::vector_mult_add().
template<typename T> virtual void libMesh::NumericVector< T >::add (const T s) pure virtual
. Addition of s to all components. Note that s is a scalar and not a vector.
Implemented in libMesh::PetscVector< T >, libMesh::EpetraVector< T >, libMesh::EigenSparseVector< T >, libMesh::LaspackVector< T >, and libMesh::DistributedVector< T >.
template<typename T> virtual void libMesh::NumericVector< T >::add (const NumericVector< T > & V) pure virtual
: Simple vector addition, equal to the operator +=.
Implemented in libMesh::PetscVector< T >, libMesh::EpetraVector< T >, libMesh::EigenSparseVector< T >, libMesh::LaspackVector< T >, and libMesh::DistributedVector< T >.
template<typename T> virtual void libMesh::NumericVector< T >::add (const T a, const NumericVector< T > & v) pure virtual
. Simple vector addition, equal to the operator +=.
Implemented in libMesh::PetscVector< T >, libMesh::EpetraVector< T >, libMesh::EigenSparseVector< T >, libMesh::LaspackVector< T >, and libMesh::DistributedVector< T >.
template<typename T> void libMesh::NumericVector< T >::add_vector (const T * v, const std::vector< numeric_index_type > & dof_indices) virtual
where v is a pointer and each dof_indices[i] specifies where to add value v[i]
This should be overridden in subclasses for efficiency
Reimplemented in libMesh::PetscVector< T >, and libMesh::EpetraVector< T >.
Definition at line 383 of file numeric_vector.C.
Referenced by libMesh::NumericVector< T >::add_vector(), libMesh::LinearImplicitSystem::assembly(), libMesh::NumericVector< Number >::operator/=(), libMesh::NewmarkSystem::update_rhs(), and libMesh::SparseMatrix< T >::vector_mult_add().
 {
   int n = dof_indices.size();
   for (int i=0; i<n; i++)
     this->add (dof_indices[i], v[i]);
 }
template<typename T> void libMesh::NumericVector< T >::add_vector (const std::vector< T > & v, const std::vector< numeric_index_type > & dof_indices) inline
where v is a std::vector and each dof_indices[i] specifies where to add value v[i]
Definition at line 840 of file numeric_vector.h.
References libMesh::NumericVector< T >::add_vector(), and libMesh::libmesh_assert().
 {
   libmesh_assert(v.size() == dof_indices.size());
   if (!v.empty())
     this->add_vector(&v[0], dof_indices);
 }
template<typename T> void libMesh::NumericVector< T >::add_vector (const NumericVector< T > & V, const std::vector< numeric_index_type > & dof_indices) virtual
where v is a NumericVector and each dof_indices[i] specifies where to add value v(i)
Definition at line 394 of file numeric_vector.C.
References libMesh::NumericVector< T >::size().
 {
   int n = dof_indices.size();
   libmesh_assert_equal_to(v.size(), static_cast<unsigned>(n));
   for (int i=0; i<n; i++)
     this->add (dof_indices[i], v(i));
 }
template<typename T> void libMesh::NumericVector< T >::add_vector (const DenseVector< T > & V, const std::vector< numeric_index_type > & dof_indices) inline
where v is a DenseVector and each dof_indices[i] specifies where to add value v(i)
Definition at line 852 of file numeric_vector.h.
References libMesh::NumericVector< T >::add_vector(), libMesh::DenseVector< T >::empty(), libMesh::libmesh_assert(), and libMesh::DenseVector< T >::size().
 {
   libmesh_assert(v.size() == dof_indices.size());
   if (!v.empty())
     this->add_vector(&v(0), dof_indices);
 }
template<typename T> virtual void libMesh::NumericVector< T >::add_vector (const NumericVector< T > & , const SparseMatrix< T > &) pure virtual
, add the product of a SparseMatrix A and a NumericVector V to this, where this=U.
Implemented in libMesh::PetscVector< T >, libMesh::EpetraVector< T >, libMesh::EigenSparseVector< T >, libMesh::LaspackVector< T >, and libMesh::DistributedVector< T >.
template<typename T> void libMesh::NumericVector< T >::add_vector (const NumericVector< T > & v, const ShellMatrix< T > & a)
, add the product of a ShellMatrix A and a NumericVector V to this, where this=U.
Definition at line 406 of file numeric_vector.C.
References libMesh::ShellMatrix< T >::vector_mult_add().
 {
   a.vector_mult_add(*this,v);
 }
template<typename T> virtual void libMesh::NumericVector< T >::add_vector_transpose (const NumericVector< T > & , const SparseMatrix< T > &) pure virtual
, add the product of the transpose of a SparseMatrix A_trans and a NumericVector V to this, where this=U.
Implemented in libMesh::PetscVector< T >, libMesh::EpetraVector< T >, libMesh::DistributedVector< T >, libMesh::EigenSparseVector< T >, and libMesh::LaspackVector< T >.
Referenced by libMesh::NumericVector< Number >::operator/=().
template<typename T > UniquePtr< NumericVector< T > > libMesh::NumericVector< T >::build (const Parallel::Communicator & comm, const SolverPackage solver_package = libMesh::default_solver_package()) static
Builds a NumericVector on the processors in communicator comm using the linear solver package specified by solver_package
Definition at line 46 of file numeric_vector.C.
References libMesh::AUTOMATIC, libMesh::EIGEN_SOLVERS, libMesh::LASPACK_SOLVERS, libMesh::PETSC_SOLVERS, and libMesh::TRILINOS_SOLVERS.
Referenced by libMesh::ExactSolution::_compute_error(), libMesh::UniformRefinementEstimator::_estimate_error(), libMesh::System::add_vector(), libMesh::NumericVector< T >::build(), libMesh::EquationSystems::build_parallel_solution_vector(), libMesh::System::calculate_norm(), libMesh::AdjointRefinementEstimator::estimate_error(), libMesh::ExactErrorEstimator::estimate_error(), libMesh::CondensedEigenSystem::get_eigenpair(), libMesh::EquationSystems::get_solution(), and libMesh::System::project_vector().
 {
   // Build the appropriate vector
   switch (solver_package)
     {
 #ifdef LIBMESH_HAVE_LASPACK
     case LASPACK_SOLVERS:
       return UniquePtr<NumericVector<T> >(new LaspackVector<T>(comm, AUTOMATIC));
 #endif
 #ifdef LIBMESH_HAVE_PETSC
     case PETSC_SOLVERS:
       return UniquePtr<NumericVector<T> >(new PetscVector<T>(comm, AUTOMATIC));
 #endif
 #ifdef LIBMESH_TRILINOS_HAVE_EPETRA
     case TRILINOS_SOLVERS:
       return UniquePtr<NumericVector<T> >(new EpetraVector<T>(comm, AUTOMATIC));
 #endif
 #ifdef LIBMESH_HAVE_EIGEN
     case EIGEN_SOLVERS:
       return UniquePtr<NumericVector<T> >(new EigenSparseVector<T>(comm, AUTOMATIC));
 #endif
     default:
       return UniquePtr<NumericVector<T> >(new DistributedVector<T>(comm, AUTOMATIC));
     }
   libmesh_error_msg("We'll never get here!");
   return UniquePtr<NumericVector<T> >();
 }
template<typename T > UniquePtr< NumericVector< T > > libMesh::NumericVector< T >::build (const SolverPackage solver_package = libMesh::default_solver_package()) static
Builds a NumericVector on the processors in communicator CommWorld using the linear solver package specified by solver_package. Deprecated.
Definition at line 84 of file numeric_vector.C.
References libMesh::NumericVector< T >::build(), and libMesh::CommWorld.
 {
   libmesh_deprecated();
   return NumericVector<T>::build(CommWorld, solver_package);
 }
template<typename T > void libMesh::NumericVector< T >::clear () inline virtual
Returns
the NumericVector<T> to a pristine state.
Reimplemented in libMesh::PetscVector< T >, libMesh::EpetraVector< T >, libMesh::EigenSparseVector< T >, libMesh::LaspackVector< T >, and libMesh::DistributedVector< T >.
Definition at line 801 of file numeric_vector.h.
References libMesh::NumericVector< T >::_is_closed, and libMesh::NumericVector< T >::_is_initialized.
Referenced by libMesh::UniformRefinementEstimator::_estimate_error(), libMesh::NumericVector< Number >::closed(), libMesh::AdjointRefinementEstimator::estimate_error(), libMesh::System::project_vector(), and libMesh::NumericVector< T >::~NumericVector().
 {
   _is_closed      = false;
   _is_initialized = false;
 }
template<typename T> virtual UniquePtr<NumericVector<T> > libMesh::NumericVector< T >::clone () const pure virtual
Creates a copy of this vector and returns it in an UniquePtr. This must be overloaded in the derived classes.
Implemented in libMesh::PetscVector< T >, libMesh::EpetraVector< T >, libMesh::EigenSparseVector< T >, libMesh::LaspackVector< T >, and libMesh::DistributedVector< T >.
Referenced by libMesh::NewmarkSolver::advance_timestep(), libMesh::NumericVector< Number >::closed(), libMesh::System::project_vector(), libMesh::TwostepTimeSolver::solve(), and libMesh::ImplicitSystem::weighted_sensitivity_solve().
template<typename T> virtual void libMesh::NumericVector< T >::close () pure virtual
Call the assemble functions
Implemented in libMesh::PetscVector< T >, libMesh::EpetraVector< T >, libMesh::EigenSparseVector< T >, libMesh::LaspackVector< T >, and libMesh::DistributedVector< T >.
Referenced by libMesh::ImplicitSystem::assemble_residual_derivatives(), libMesh::FEMSystem::assembly(), libMesh::LinearImplicitSystem::assembly(), libMesh::System::boundary_project_vector(), libMesh::EquationSystems::build_parallel_solution_vector(), libMesh::NumericVector< Number >::closed(), libMesh::ContinuationSystem::continuation_solve(), libMesh::DofMap::enforce_adjoint_constraints_exactly(), libMesh::DofMap::enforce_constraints_exactly(), libMesh::AdjointRefinementEstimator::estimate_error(), libMesh::ImplicitSystem::forward_qoi_parameter_sensitivity(), libMesh::EquationSystems::get_solution(), libMesh::ContinuationSystem::initialize_tangent(), libMesh::NewtonSolver::line_search(), libMesh::System::project_vector(), libMesh::ImplicitSystem::qoi_parameter_hessian(), libMesh::ImplicitSystem::qoi_parameter_hessian_vector_product(), libMesh::System::read_serialized_vector(), libMesh::NewtonSolver::solve(), libMesh::NoxNonlinearSolver< T >::solve(), libMesh::ContinuationSystem::solve_tangent(), libMesh::ContinuationSystem::update_solution(), libMesh::ImplicitSystem::weighted_sensitivity_adjoint_solve(), and libMesh::ImplicitSystem::weighted_sensitivity_solve().
template<typename T> virtual bool libMesh::NumericVector< T >::closed () const inline virtual
Returns
true if the vector is closed and ready for computation, false otherwise.
Definition at line 148 of file numeric_vector.h.
Referenced by libMesh::DofMap::enforce_adjoint_constraints_exactly(), libMesh::DofMap::enforce_constraints_exactly(), libMesh::DofMap::max_constraint_error(), libMesh::EigenSparseVector< T >::operator=(), libMesh::LaspackVector< T >::operator=(), libMesh::PetscVector< T >::operator=(), libMesh::EigenSparseVector< T >::zero(), libMesh::LaspackVector< T >::zero(), libMesh::EpetraVector< T >::zero(), and libMesh::PetscVector< T >::zero().
 { return _is_closed; }
const Parallel::Communicator& libMesh::ParallelObject::comm () const inline inherited
Returns
a reference to the Parallel::Communicator object used by this mesh.
Definition at line 87 of file parallel_object.h.
References libMesh::ParallelObject::_communicator.
Referenced by libMesh::__libmesh_petsc_diff_solver_monitor(), libMesh::__libmesh_petsc_diff_solver_residual(), libMesh::__libmesh_petsc_snes_jacobian(), libMesh::__libmesh_petsc_snes_postcheck(), libMesh::__libmesh_petsc_snes_residual(), libMesh::__libmesh_tao_equality_constraints(), libMesh::__libmesh_tao_equality_constraints_jacobian(), libMesh::__libmesh_tao_gradient(), libMesh::__libmesh_tao_hessian(), libMesh::__libmesh_tao_inequality_constraints(), libMesh::__libmesh_tao_inequality_constraints_jacobian(), libMesh::__libmesh_tao_objective(), libMesh::MeshRefinement::_coarsen_elements(), libMesh::ExactSolution::_compute_error(), libMesh::ParmetisPartitioner::_do_repartition(), libMesh::UniformRefinementEstimator::_estimate_error(), libMesh::BoundaryInfo::_find_id_maps(), libMesh::PetscLinearSolver< T >::_petsc_shell_matrix_get_diagonal(), libMesh::SlepcEigenSolver< T >::_petsc_shell_matrix_get_diagonal(), libMesh::PetscLinearSolver< T >::_petsc_shell_matrix_mult(), libMesh::SlepcEigenSolver< T >::_petsc_shell_matrix_mult(), libMesh::PetscLinearSolver< T >::_petsc_shell_matrix_mult_add(), libMesh::EquationSystems::_read_impl(), libMesh::MeshRefinement::_refine_elements(), libMesh::MeshRefinement::_smooth_flags(), libMesh::ImplicitSystem::add_matrix(), libMesh::System::add_vector(), libMesh::EigenSparseLinearSolver< T >::adjoint_solve(), libMesh::UnstructuredMesh::all_second_order(), libMesh::MeshTools::Modification::all_tri(), libMesh::LaplaceMeshSmoother::allgather_graph(), libMesh::FEMSystem::assemble_qoi(), libMesh::MeshCommunication::assign_global_indices(), libMesh::ParmetisPartitioner::assign_partitioning(), libMesh::DofMap::attach_matrix(), libMesh::Parallel::BinSorter< KeyType, IdxType >::binsort(), libMesh::Parallel::Sort< KeyType, IdxType >::binsort(), libMesh::MeshTools::bounding_box(), libMesh::MeshCommunication::broadcast(), libMesh::SparseMatrix< T >::build(), libMesh::MeshTools::Generation::build_extrusion(), libMesh::Parallel::Histogram< KeyType, IdxType >::build_histogram(), libMesh::PetscNonlinearSolver< T >::build_mat_null_space(), libMesh::BoundaryInfo::build_node_list_from_side_list(), libMesh::EquationSystems::build_parallel_solution_vector(), libMesh::MeshBase::cache_elem_dims(), libMesh::System::calculate_norm(), libMesh::DofMap::check_dirichlet_bcid_consistency(), libMesh::DistributedVector< T >::clone(), libMesh::EigenSparseVector< T >::clone(), libMesh::LaspackVector< T >::clone(), libMesh::EpetraVector< T >::clone(), libMesh::PetscVector< T >::clone(), libMesh::EpetraVector< T >::close(), libMesh::Parallel::Sort< KeyType, IdxType >::communicate_bins(), libMesh::Nemesis_IO_Helper::compute_num_global_elem_blocks(), libMesh::Nemesis_IO_Helper::compute_num_global_nodesets(), libMesh::Nemesis_IO_Helper::compute_num_global_sidesets(), libMesh::Problem_Interface::computeF(), libMesh::Problem_Interface::computeJacobian(), libMesh::Problem_Interface::computePreconditioner(), libMesh::MeshTools::correct_node_proc_ids(), libMesh::MeshRefinement::create_parent_error_vector(), libMesh::MeshCommunication::delete_remote_elements(), libMesh::DofMap::distribute_dofs(), DMlibMeshFunction(), DMlibMeshJacobian(), DMlibMeshSetSystem_libMesh(), DMVariableBounds_libMesh(), libMesh::MeshRefinement::eliminate_unrefined_patches(), libMesh::EpetraVector< T >::EpetraVector(), libMesh::WeightedPatchRecoveryErrorEstimator::estimate_error(), libMesh::PatchRecoveryErrorEstimator::estimate_error(), libMesh::JumpErrorEstimator::estimate_error(), libMesh::AdjointRefinementEstimator::estimate_error(), libMesh::ExactErrorEstimator::estimate_error(), libMesh::MeshRefinement::flag_elements_by_elem_fraction(), libMesh::MeshRefinement::flag_elements_by_error_fraction(), libMesh::MeshRefinement::flag_elements_by_nelem_target(), libMesh::MeshCommunication::gather(), libMesh::MeshCommunication::gather_neighboring_elements(), libMesh::CondensedEigenSystem::get_eigenpair(), libMesh::DofMap::get_info(), libMesh::ImplicitSystem::get_linear_solver(), libMesh::EquationSystems::get_solution(), libMesh::LocationMap< T >::init(), libMesh::PetscDiffSolver::init(), libMesh::TimeSolver::init(), libMesh::TopologyMap::init(), libMesh::TaoOptimizationSolver< T >::init(), libMesh::PetscNonlinearSolver< T >::init(), libMesh::DistributedVector< T >::init(), libMesh::EpetraVector< T >::init(), libMesh::PetscVector< T >::init(), libMesh::SystemSubsetBySubdomain::init(), libMesh::EigenSystem::init_data(), libMesh::EigenSystem::init_matrices(), libMesh::ParmetisPartitioner::initialize(), libMesh::OptimizationSystem::initialize_equality_constraints_storage(), libMesh::OptimizationSystem::initialize_inequality_constraints_storage(), libMesh::MeshTools::libmesh_assert_parallel_consistent_procids< Elem >(), libMesh::MeshTools::libmesh_assert_parallel_consistent_procids< Node >(), libMesh::MeshTools::libmesh_assert_topology_consistent_procids< Node >(), libMesh::MeshTools::libmesh_assert_valid_boundary_ids(), libMesh::MeshTools::libmesh_assert_valid_dof_ids(), libMesh::MeshTools::libmesh_assert_valid_neighbors(), libMesh::DistributedMesh::libmesh_assert_valid_parallel_flags(), libMesh::DistributedMesh::libmesh_assert_valid_parallel_object_ids(), libMesh::DistributedMesh::libmesh_assert_valid_parallel_p_levels(), libMesh::MeshTools::libmesh_assert_valid_refinement_flags(), libMesh::MeshTools::libmesh_assert_valid_unique_ids(), libMesh::MeshRefinement::limit_level_mismatch_at_edge(), libMesh::MeshRefinement::limit_level_mismatch_at_node(), libMesh::MeshRefinement::limit_overrefined_boundary(), libMesh::MeshRefinement::limit_underrefined_boundary(), libMesh::MeshRefinement::make_coarsening_compatible(), libMesh::MeshCommunication::make_elems_parallel_consistent(), libMesh::MeshRefinement::make_flags_parallel_consistent(), libMesh::MeshCommunication::make_new_node_proc_ids_parallel_consistent(), libMesh::MeshCommunication::make_new_nodes_parallel_consistent(), libMesh::MeshCommunication::make_node_ids_parallel_consistent(), libMesh::MeshCommunication::make_node_proc_ids_parallel_consistent(), libMesh::MeshCommunication::make_node_unique_ids_parallel_consistent(), libMesh::MeshCommunication::make_nodes_parallel_consistent(), libMesh::MeshCommunication::make_p_levels_parallel_consistent(), libMesh::MeshRefinement::make_refinement_compatible(), libMesh::DistributedVector< T >::max(), libMesh::FEMSystem::mesh_position_set(), libMesh::MeshSerializer::MeshSerializer(), libMesh::DistributedVector< T >::min(), libMesh::DistributedMesh::n_active_elem(), libMesh::MeshTools::n_active_levels(), libMesh::BoundaryInfo::n_boundary_conds(), libMesh::BoundaryInfo::n_edge_conds(), libMesh::CondensedEigenSystem::n_global_non_condensed_dofs(), libMesh::MeshTools::n_levels(), libMesh::BoundaryInfo::n_nodeset_conds(), libMesh::MeshTools::n_p_levels(), libMesh::BoundaryInfo::n_shellface_conds(), libMesh::DistributedMesh::parallel_max_elem_id(), libMesh::DistributedMesh::parallel_max_node_id(), libMesh::ReplicatedMesh::parallel_max_unique_id(), libMesh::DistributedMesh::parallel_max_unique_id(), libMesh::DistributedMesh::parallel_n_elem(), libMesh::DistributedMesh::parallel_n_nodes(), libMesh::SparsityPattern::Build::parallel_sync(), libMesh::MeshTools::paranoid_n_levels(), libMesh::Partitioner::partition(), libMesh::MetisPartitioner::partition_range(), libMesh::Partitioner::partition_unpartitioned_elements(), libMesh::petsc_auto_fieldsplit(), libMesh::System::point_gradient(), libMesh::System::point_hessian(), libMesh::System::point_value(), libMesh::MeshBase::prepare_for_use(), libMesh::SparseMatrix< T >::print(), libMesh::MeshTools::processor_bounding_box(), libMesh::Nemesis_IO::read(), libMesh::XdrIO::read(), libMesh::XdrIO::read_serialized_bc_names(), libMesh::XdrIO::read_serialized_bcs_helper(), libMesh::XdrIO::read_serialized_connectivity(), libMesh::XdrIO::read_serialized_nodes(), libMesh::XdrIO::read_serialized_nodesets(), libMesh::XdrIO::read_serialized_subdomain_names(), libMesh::MeshBase::recalculate_n_partitions(), libMesh::MeshCommunication::redistribute(), libMesh::DistributedMesh::renumber_dof_objects(), libMesh::MeshCommunication::send_coarse_ghosts(), libMesh::Partitioner::set_node_processor_ids(), libMesh::DofMap::set_nonlocal_dof_objects(), libMesh::Partitioner::set_parent_processor_ids(), libMesh::LaplaceMeshSmoother::smooth(), libMesh::Parallel::Sort< KeyType, IdxType >::sort(), libMesh::MeshTools::subdomain_bounding_box(), libMesh::MeshBase::subdomain_ids(), libMesh::BoundaryInfo::sync(), libMesh::Parallel::sync_element_data_by_parent_id(), libMesh::Parallel::sync_node_data_by_element_id(), libMesh::MeshRefinement::test_level_one(), libMesh::MeshRefinement::test_unflagged(), libMesh::MeshTools::total_weight(), libMesh::NameBasedIO::write(), libMesh::XdrIO::write(), libMesh::XdrIO::write_serialized_bcs_helper(), libMesh::XdrIO::write_serialized_connectivity(), libMesh::XdrIO::write_serialized_nodes(), libMesh::XdrIO::write_serialized_nodesets(), libMesh::DistributedVector< T >::zero_clone(), libMesh::LaspackVector< T >::zero_clone(), libMesh::EigenSparseVector< T >::zero_clone(), libMesh::EpetraVector< T >::zero_clone(), and libMesh::PetscVector< T >::zero_clone().
   { return _communicator; }
template<typename T> int libMesh::NumericVector< T >::compare (const NumericVector< T > & other_vector, const Real threshold = TOLERANCE) const virtual
Returns
-1 when this is equivalent to other_vector, up to the given threshold. When differences occur, the return value contains the first index i where the difference (a[i]-b[i]) exceeded the threshold. When no threshold is given, the libMesh TOLERANCE is used.
Definition at line 116 of file numeric_vector.C.
References std::abs(), libMesh::NumericVector< T >::first_local_index(), libMesh::NumericVector< T >::initialized(), libMesh::initialized(), libMesh::NumericVector< T >::last_local_index(), libMesh::libmesh_assert(), and std::max().
Referenced by libMesh::NumericVector< Number >::operator/=().
 {
   libmesh_assert (this->initialized());
   libmesh_assert (other_vector.initialized());
   libmesh_assert_equal_to (this->first_local_index(), other_vector.first_local_index());
   libmesh_assert_equal_to (this->last_local_index(), other_vector.last_local_index());
   int first_different_i = std::numeric_limits<int>::max();
   numeric_index_type i = first_local_index();
   do
     {
       if ( std::abs( (*this)(i) - other_vector(i) ) > threshold )
         first_different_i = i;
       else
         i++;
     }
   while (first_different_i==std::numeric_limits<int>::max()
          && i<last_local_index());
   // Find the correct first differing index in parallel
   this->comm().min(first_different_i);
   if (first_different_i == std::numeric_limits<int>::max())
     return -1;
   return first_different_i;
 }
template<typename T> virtual void libMesh::NumericVector< T >::conjugate () pure virtual
Replace each entry v_i = real(v_i) + imag(v_i) of this vector by its complex conjugate, real(v_i) - imag(v_i)
Implemented in libMesh::PetscVector< T >, libMesh::EpetraVector< T >, libMesh::EigenSparseVector< T >, libMesh::LaspackVector< T >, and libMesh::DistributedVector< T >.
Referenced by libMesh::NumericVector< Number >::operator/=().
template<typename T> virtual void libMesh::NumericVector< T >::create_subvector (NumericVector< T > & , const std::vector< numeric_index_type > &) const inline virtual
Creates the subvector "subvector" from the indices in the "rows" array. Similar to the create_submatrix routine for the SparseMatrix class, it is currently only implemented for PetscVectors.
Reimplemented in libMesh::PetscVector< T >, and libMesh::EpetraVector< T >.
Definition at line 688 of file numeric_vector.h.
   {
     libmesh_not_implemented();
   }
void libMesh::ReferenceCounter::disable_print_counter_info () static inherited
Definition at line 106 of file reference_counter.C.
References libMesh::ReferenceCounter::_enable_print_counter.
Referenced by libMesh::LibMeshInit::LibMeshInit(), and libMesh::ReferenceCounter::n_objects().
 {
   _enable_print_counter = false;
   return;
 }
template<typename T> virtual T libMesh::NumericVector< T >::dot (const NumericVector< T > &) const pure virtual
Computes the dot product, p = U.V
Implemented in libMesh::PetscVector< T >, libMesh::EpetraVector< T >, libMesh::DistributedVector< T >, libMesh::EigenSparseVector< T >, and libMesh::LaspackVector< T >.
Referenced by libMesh::ImplicitSystem::adjoint_qoi_parameter_sensitivity(), libMesh::ContinuationSystem::continuation_solve(), libMesh::AdjointRefinementEstimator::estimate_error(), libMesh::ImplicitSystem::forward_qoi_parameter_sensitivity(), libMesh::NumericVector< Number >::operator/=(), libMesh::ImplicitSystem::qoi_parameter_hessian(), libMesh::ImplicitSystem::qoi_parameter_hessian_vector_product(), libMesh::ContinuationSystem::solve_tangent(), and libMesh::ContinuationSystem::update_solution().
template<typename T> virtual T libMesh::NumericVector< T >::el (const numeric_index_type i) const inline virtual
Returns
the element U(i)
Definition at line 345 of file numeric_vector.h.
 { return (*this)(i); }
void libMesh::ReferenceCounter::enable_print_counter_info () static inherited
Methods to enable/disable the reference counter output from print_info()
Definition at line 100 of file reference_counter.C.
References libMesh::ReferenceCounter::_enable_print_counter.
Referenced by libMesh::ReferenceCounter::n_objects().
 {
   _enable_print_counter = true;
   return;
 }
template<typename T> virtual numeric_index_type libMesh::NumericVector< T >::first_local_index () const pure virtual
Returns
the index of the first vector element actually stored on this processor. Hint: the minimum for this index is 0.
Implemented in libMesh::PetscVector< T >, libMesh::EpetraVector< T >, libMesh::EigenSparseVector< T >, libMesh::LaspackVector< T >, and libMesh::DistributedVector< T >.
Referenced by libMesh::NumericVector< Number >::closed(), libMesh::NumericVector< T >::compare(), libMesh::DofMap::extract_local_vector(), libMesh::NumericVector< T >::global_relative_compare(), libMesh::VectorSetAction< Val >::insert(), libMesh::NumericVector< T >::local_relative_compare(), libMesh::DofMap::max_constraint_error(), libMesh::NumericVector< T >::print(), libMesh::System::read_serialized_blocked_dof_objects(), and libMesh::System::write_serialized_blocked_dof_objects().
template<typename T> void libMesh::NumericVector< T >::get (const std::vector< numeric_index_type > & index, T * values) const inline virtual
Access multiple components at once. values will not be reallocated; it should already have enough space. The default implementation calls operator() for each index, but some implementations may supply faster methods here.
Reimplemented in libMesh::PetscVector< T >.
Definition at line 811 of file numeric_vector.h.
Referenced by libMesh::DofMap::enforce_adjoint_constraints_exactly(), libMesh::DofMap::enforce_constraints_exactly(), libMesh::FEMContext::pre_fe_reinit(), and libMesh::System::project_vector().
 {
   const std::size_t num = index.size();
   for(std::size_t i=0; i<num; i++)
     {
       values[i] = (*this)(index[i]);
     }
 }
template<typename T> void libMesh::NumericVector< T >::get (const std::vector< numeric_index_type > & index, std::vector< T > & values) const inline
Access multiple components at once. values will be resized, if necessary, and filled. The default implementation calls operator() for each index, but some implementations may supply faster methods here.
Definition at line 825 of file numeric_vector.h.
 {
   const std::size_t num = index.size();
   values.resize(num);
   if (!num)
     return;
   this->get(index, &values[0]);
 }
std::string libMesh::ReferenceCounter::get_info () static inherited
Gets a string containing the reference information.
Definition at line 47 of file reference_counter.C.
References libMesh::ReferenceCounter::_counts, and libMesh::Quality::name().
Referenced by libMesh::ReferenceCounter::print_info().
 {
 #if defined(LIBMESH_ENABLE_REFERENCE_COUNTING) && defined(DEBUG)
   std::ostringstream oss;
   oss << '\n'
       << " ---------------------------------------------------------------------------- \n"
       << "| Reference count information                                                |\n"
       << " ---------------------------------------------------------------------------- \n";
   for (Counts::iterator it = _counts.begin();
        it != _counts.end(); ++it)
     {
       const std::string name(it->first);
       const unsigned int creations    = it->second.first;
       const unsigned int destructions = it->second.second;
       oss << "| " << name << " reference count information:\n"
           << "|  Creations:    " << creations    << '\n'
           << "|  Destructions: " << destructions << '\n';
     }
   oss << " ---------------------------------------------------------------------------- \n";
   return oss.str();
 #else
   return "";
 #endif
 }
template<typename T> int libMesh::NumericVector< T >::global_relative_compare (const NumericVector< T > & other_vector, const Real threshold = TOLERANCE) const virtual
Returns
-1 when this is equivalent to other_vector, up to the given local relative threshold. When differences occur, the return value contains the first index where the difference (a[i]-b[i])/max_j(a[j],b[j]) exceeded the threshold. When no threshold is given, the libMesh TOLERANCE is used.
Definition at line 181 of file numeric_vector.C.
References std::abs(), libMesh::NumericVector< T >::first_local_index(), libMesh::NumericVector< T >::initialized(), libMesh::initialized(), libMesh::NumericVector< T >::last_local_index(), libMesh::libmesh_assert(), libMesh::NumericVector< T >::linfty_norm(), std::max(), and libMesh::Real.
Referenced by libMesh::NumericVector< Number >::operator/=().
 {
   libmesh_assert (this->initialized());
   libmesh_assert (other_vector.initialized());
   libmesh_assert_equal_to (this->first_local_index(), other_vector.first_local_index());
   libmesh_assert_equal_to (this->last_local_index(), other_vector.last_local_index());
   int first_different_i = std::numeric_limits<int>::max();
   numeric_index_type i = first_local_index();
   const Real my_norm = this->linfty_norm();
   const Real other_norm = other_vector.linfty_norm();
   const Real abs_threshold = std::max(my_norm, other_norm) * threshold;
   do
     {
       if ( std::abs( (*this)(i) - other_vector(i) ) > abs_threshold )
         first_different_i = i;
       else
         i++;
     }
   while (first_different_i==std::numeric_limits<int>::max()
          && i<last_local_index());
   // Find the correct first differing index in parallel
   this->comm().min(first_different_i);
   if (first_different_i == std::numeric_limits<int>::max())
     return -1;
   return first_different_i;
 }
void libMesh::ReferenceCounter::increment_constructor_count (const std::string & name) inline protected inherited
Increments the construction counter. Should be called in the constructor of any derived class that will be reference counted.
Definition at line 160 of file reference_counter.h.
References libMesh::ReferenceCounter::_counts, libMesh::Quality::name(), and libMesh::Threads::spin_mtx.
Referenced by libMesh::ReferenceCounter::n_objects(), and libMesh::ReferenceCountedObject< RBParametrized >::ReferenceCountedObject().
 {
   Threads::spin_mutex::scoped_lock lock(Threads::spin_mtx);
   std::pair<unsigned int, unsigned int> & p = _counts[name];
   p.first++;
 }
void libMesh::ReferenceCounter::increment_destructor_count (const std::string & name) inline protected inherited
Increments the destruction counter. Should be called in the destructor of any derived class that will be reference counted.
Definition at line 173 of file reference_counter.h.
References libMesh::ReferenceCounter::_counts, libMesh::Quality::name(), and libMesh::Threads::spin_mtx.
Referenced by libMesh::ReferenceCounter::n_objects(), and libMesh::ReferenceCountedObject< RBParametrized >::~ReferenceCountedObject().
 {
   Threads::spin_mutex::scoped_lock lock(Threads::spin_mtx);
   std::pair<unsigned int, unsigned int> & p = _counts[name];
   p.second++;
 }
template<typename T> virtual void libMesh::NumericVector< T >::init (const numeric_index_type , const numeric_index_type , const bool = false, const ParallelType = AUTOMATIC) pure virtual
Change the dimension of the vector to N. The reserved memory for this vector remains unchanged if possible, to make things faster, but this may waste some memory, so take this in the back of your head. However, if N==0 all memory is freed, i.e. if you want to resize the vector and release the memory not needed, you have to first call init(0) and then init(N). This cited behaviour is analogous to that of the STL containers.
On fast==false, the vector is filled by zeros.
Implemented in libMesh::PetscVector< T >, libMesh::EpetraVector< T >, libMesh::EigenSparseVector< T >, libMesh::LaspackVector< T >, and libMesh::DistributedVector< T >.
Referenced by libMesh::System::add_vector(), libMesh::EquationSystems::build_parallel_solution_vector(), libMesh::DistributedVector< T >::clone(), libMesh::EigenSparseVector< T >::clone(), libMesh::LaspackVector< T >::clone(), libMesh::EpetraVector< T >::clone(), libMesh::PetscVector< T >::clone(), libMesh::NumericVector< Number >::closed(), libMesh::AdjointRefinementEstimator::estimate_error(), libMesh::EquationSystems::get_solution(), libMesh::System::project_vector(), libMesh::DistributedVector< T >::zero_clone(), libMesh::LaspackVector< T >::zero_clone(), libMesh::EigenSparseVector< T >::zero_clone(), libMesh::EpetraVector< T >::zero_clone(), and libMesh::PetscVector< T >::zero_clone().
template<typename T> virtual void libMesh::NumericVector< T >::init (const numeric_index_type , const bool = false, const ParallelType = AUTOMATIC) pure virtual
call init with n_local = N,
Implemented in libMesh::PetscVector< T >, libMesh::EpetraVector< T >, libMesh::EigenSparseVector< T >, libMesh::LaspackVector< T >, and libMesh::DistributedVector< T >.
template<typename T> virtual void libMesh::NumericVector< T >::init (const numeric_index_type , const numeric_index_type , const std::vector< numeric_index_type > & , const bool = false, const ParallelType = AUTOMATIC) pure virtual
Create a vector that holds tha local indices plus those specified in the ghost argument.
Implemented in libMesh::PetscVector< T >, libMesh::EpetraVector< T >, libMesh::EigenSparseVector< T >, libMesh::LaspackVector< T >, and libMesh::DistributedVector< T >.
template<typename T> virtual void libMesh::NumericVector< T >::init (const NumericVector< T > & other, const bool fast = false) pure virtual
Creates a vector that has the same dimension and storage type as other, including ghost dofs.
Implemented in libMesh::PetscVector< T >, libMesh::EpetraVector< T >, libMesh::EigenSparseVector< T >, libMesh::LaspackVector< T >, and libMesh::DistributedVector< T >.
template<typename T> virtual bool libMesh::NumericVector< T >::initialized () const inline virtual
Returns
true if the vector has been initialized, false otherwise.
Definition at line 132 of file numeric_vector.h.
Referenced by libMesh::DistributedVector< T >::add(), libMesh::EigenSparseVector< T >::add(), libMesh::LaspackVector< T >::add(), libMesh::ImplicitSystem::assemble(), libMesh::LaspackVector< T >::clear(), libMesh::EpetraVector< T >::clear(), libMesh::PetscVector< T >::clear(), libMesh::DistributedVector< T >::close(), libMesh::EigenSparseVector< T >::close(), libMesh::LaspackVector< T >::close(), libMesh::EpetraVector< T >::close(), libMesh::NumericVector< T >::compare(), libMesh::PetscVector< T >::create_subvector(), libMesh::DistributedVector< T >::first_local_index(), libMesh::EigenSparseVector< T >::first_local_index(), libMesh::LaspackVector< T >::first_local_index(), libMesh::EpetraVector< T >::first_local_index(), libMesh::PetscVector< T >::first_local_index(), libMesh::NumericVector< T >::global_relative_compare(), libMesh::DistributedVector< T >::init(), libMesh::EigenSparseVector< T >::init(), libMesh::PetscVector< T >::init(), libMesh::DistributedVector< T >::last_local_index(), libMesh::EigenSparseVector< T >::last_local_index(), libMesh::LaspackVector< T >::last_local_index(), libMesh::EpetraVector< T >::last_local_index(), libMesh::PetscVector< T >::last_local_index(), libMesh::NumericVector< T >::local_relative_compare(), libMesh::DistributedVector< T >::local_size(), libMesh::EigenSparseVector< T >::local_size(), libMesh::LaspackVector< T >::local_size(), libMesh::EpetraVector< T >::local_size(), libMesh::PetscVector< T >::local_size(), libMesh::PetscVector< T >::map_global_to_local_index(), libMesh::DistributedVector< T >::max(), libMesh::EpetraVector< T >::max(), libMesh::DistributedVector< T >::min(), libMesh::EpetraVector< T >::min(), libMesh::DistributedVector< T >::operator()(), libMesh::LaspackVector< T >::operator()(), libMesh::EigenSparseVector< T >::operator()(), libMesh::EpetraVector< T >::operator()(), libMesh::NumericVector< T >::print(), libMesh::NumericVector< T >::print_global(), libMesh::DistributedVector< T >::set(), libMesh::EigenSparseVector< T >::set(), libMesh::LaspackVector< T >::set(), libMesh::DistributedVector< T >::size(), libMesh::LaspackVector< T >::size(), libMesh::EigenSparseVector< T >::size(), libMesh::EpetraVector< T >::size(), libMesh::PetscVector< T >::size(), libMesh::DistributedVector< T >::zero(), libMesh::LaspackVector< T >::zero(), libMesh::EigenSparseVector< T >::zero(), libMesh::EpetraVector< T >::zero(), and libMesh::LaspackVector< T >::~LaspackVector().
 { return _is_initialized; }
template<typename T> void libMesh::NumericVector< T >::insert (const T * v, const std::vector< numeric_index_type > & dof_indices) virtual
where v is a T[] or T * and you want to specify WHERE to insert it
Reimplemented in libMesh::PetscVector< T >, and libMesh::EpetraVector< T >.
Definition at line 94 of file numeric_vector.C.
Referenced by libMesh::NumericVector< T >::insert(), and libMesh::NumericVector< Number >::operator/=().
 {
   for (numeric_index_type i=0; i<dof_indices.size(); i++)
     this->set (dof_indices[i], v[i]);
 }
template<typename T> void libMesh::NumericVector< T >::insert (const std::vector< T > & v, const std::vector< numeric_index_type > & dof_indices) inline
where v is a std::vector<T> and you want to specify WHERE to insert it
Definition at line 864 of file numeric_vector.h.
References libMesh::NumericVector< T >::insert(), and libMesh::libmesh_assert().
 {
   libmesh_assert(v.size() == dof_indices.size());
   if (!v.empty())
     this->insert(&v[0], dof_indices);
 }
template<typename T> void libMesh::NumericVector< T >::insert (const NumericVector< T > & V, const std::vector< numeric_index_type > & dof_indices) virtual
, where U and V are type NumericVector<T> and you want to specify WHERE to insert the NumericVector<T> V
Definition at line 104 of file numeric_vector.C.
References libMesh::NumericVector< T >::size().
 {
   libmesh_assert_equal_to (V.size(), dof_indices.size());
   for (numeric_index_type i=0; i<dof_indices.size(); i++)
     this->set (dof_indices[i], V(i));
 }
template<typename T> void libMesh::NumericVector< T >::insert (const DenseVector< T > & V, const std::vector< numeric_index_type > & dof_indices) inline
where U and V are type DenseVector<T> and you want to specify WHERE to insert the DenseVector<T> V
Definition at line 876 of file numeric_vector.h.
References libMesh::DenseVector< T >::empty(), libMesh::NumericVector< T >::insert(), libMesh::libmesh_assert(), and libMesh::DenseVector< T >::size().
 {
   libmesh_assert(v.size() == dof_indices.size());
   if (!v.empty())
     this->insert(&v(0), dof_indices);
 }
template<typename T> void libMesh::NumericVector< T >::insert (const DenseSubVector< T > & V, const std::vector< numeric_index_type > & dof_indices) inline
where V is a DenseSubVector<T> and you want to specify WHERE to insert it
Definition at line 888 of file numeric_vector.h.
References libMesh::DenseSubVector< T >::empty(), libMesh::NumericVector< T >::insert(), libMesh::libmesh_assert(), and libMesh::DenseSubVector< T >::size().
 {
   libmesh_assert(v.size() == dof_indices.size());
   if (!v.empty())
     this->insert(&v(0), dof_indices);
 }
template<typename T> virtual Real libMesh::NumericVector< T >::l1_norm () const pure virtual
Returns
the -norm of the vector, i.e. the sum of the absolute values.
Implemented in libMesh::PetscVector< T >, libMesh::EpetraVector< T >, libMesh::EigenSparseVector< T >, libMesh::LaspackVector< T >, and libMesh::DistributedVector< T >.
Referenced by libMesh::FEMSystem::assembly(), libMesh::System::calculate_norm(), and libMesh::NumericVector< Number >::closed().
template<typename T> virtual Real libMesh::NumericVector< T >::l2_norm () const pure virtual
Returns
the -norm of the vector, i.e. the square root of the sum of the squares of the elements.
Implemented in libMesh::PetscVector< T >, libMesh::EpetraVector< T >, libMesh::EigenSparseVector< T >, libMesh::LaspackVector< T >, and libMesh::DistributedVector< T >.
Referenced by libMesh::System::calculate_norm(), libMesh::NumericVector< Number >::closed(), libMesh::ContinuationSystem::continuation_solve(), libMesh::ContinuationSystem::initialize_tangent(), libMesh::NewtonSolver::line_search(), libMesh::NewtonSolver::solve(), libMesh::ContinuationSystem::solve_tangent(), and libMesh::ContinuationSystem::update_solution().
template<typename T> virtual numeric_index_type libMesh::NumericVector< T >::last_local_index () const pure virtual
Returns
the index+1 of the last vector element actually stored on this processor. Hint: the maximum for this index is size().
Implemented in libMesh::PetscVector< T >, libMesh::EpetraVector< T >, libMesh::EigenSparseVector< T >, libMesh::LaspackVector< T >, and libMesh::DistributedVector< T >.
Referenced by libMesh::NumericVector< Number >::closed(), libMesh::NumericVector< T >::compare(), libMesh::DofMap::extract_local_vector(), libMesh::NumericVector< T >::global_relative_compare(), libMesh::VectorSetAction< Val >::insert(), libMesh::NumericVector< T >::local_relative_compare(), libMesh::DofMap::max_constraint_error(), libMesh::NumericVector< T >::print(), libMesh::System::read_serialized_blocked_dof_objects(), and libMesh::System::write_serialized_blocked_dof_objects().
template<typename T> virtual Real libMesh::NumericVector< T >::linfty_norm () const pure virtual
Returns
the maximum absolute value of the elements of this vector, which is the -norm of a vector.
Implemented in libMesh::PetscVector< T >, libMesh::EpetraVector< T >, libMesh::EigenSparseVector< T >, libMesh::LaspackVector< T >, and libMesh::DistributedVector< T >.
Referenced by libMesh::System::calculate_norm(), libMesh::NumericVector< Number >::closed(), and libMesh::NumericVector< T >::global_relative_compare().
template<typename T> int libMesh::NumericVector< T >::local_relative_compare (const NumericVector< T > & other_vector, const Real threshold = TOLERANCE) const virtual
Returns
-1 when this is equivalent to other_vector, up to the given local relative threshold. When differences occur, the return value contains the first index where the difference (a[i]-b[i])/max(a[i],b[i]) exceeded the threshold. When no threshold is given, the libMesh TOLERANCE is used.
Definition at line 148 of file numeric_vector.C.
References std::abs(), libMesh::NumericVector< T >::first_local_index(), libMesh::NumericVector< T >::initialized(), libMesh::initialized(), libMesh::NumericVector< T >::last_local_index(), libMesh::libmesh_assert(), and std::max().
Referenced by libMesh::NumericVector< Number >::operator/=().
 {
   libmesh_assert (this->initialized());
   libmesh_assert (other_vector.initialized());
   libmesh_assert_equal_to (this->first_local_index(), other_vector.first_local_index());
   libmesh_assert_equal_to (this->last_local_index(), other_vector.last_local_index());
   int first_different_i = std::numeric_limits<int>::max();
   numeric_index_type i = first_local_index();
   do
     {
       if ( std::abs( (*this)(i) - other_vector(i) ) > threshold *
            std::max(std::abs((*this)(i)), std::abs(other_vector(i))))
         first_different_i = i;
       else
         i++;
     }
   while (first_different_i==std::numeric_limits<int>::max()
          && i<last_local_index());
   // Find the correct first differing index in parallel
   this->comm().min(first_different_i);
   if (first_different_i == std::numeric_limits<int>::max())
     return -1;
   return first_different_i;
 }
template<typename T> virtual numeric_index_type libMesh::NumericVector< T >::local_size () const pure virtual
Returns
the local size of the vector (index_stop-index_start). In ghost cell mode, this does not include the ghost cells.
Implemented in libMesh::PetscVector< T >, libMesh::EpetraVector< T >, libMesh::EigenSparseVector< T >, libMesh::LaspackVector< T >, and libMesh::DistributedVector< T >.
Referenced by libMesh::PetscLinearSolver< T >::adjoint_solve(), libMesh::NumericVector< Number >::closed(), libMesh::DistributedVector< T >::init(), libMesh::EigenSparseVector< T >::init(), libMesh::LaspackVector< T >::init(), libMesh::EpetraVector< T >::init(), libMesh::NumericVector< T >::print(), libMesh::System::project_vector(), and libMesh::PetscLinearSolver< T >::solve().
template<typename T> virtual void libMesh::NumericVector< T >::localize (std::vector< T > & v_local) const pure virtual
Creates a copy of the global vector in the local vector v_local.
Implemented in libMesh::PetscVector< T >, libMesh::EpetraVector< T >, libMesh::DistributedVector< T >, libMesh::EigenSparseVector< T >, and libMesh::LaspackVector< T >.
Referenced by libMesh::UnsteadySolver::adjoint_advance_timestep(), libMesh::NewmarkSolver::advance_timestep(), libMesh::UnsteadySolver::advance_timestep(), libMesh::System::calculate_norm(), libMesh::DofMap::enforce_adjoint_constraints_exactly(), libMesh::DofMap::enforce_constraints_exactly(), libMesh::AdjointRefinementEstimator::estimate_error(), libMesh::NumericVector< Number >::operator/=(), libMesh::NumericVector< T >::print_global(), libMesh::System::project_vector(), libMesh::SecondOrderUnsteadySolver::reinit(), libMesh::UnsteadySolver::reinit(), libMesh::UnsteadySolver::retrieve_timestep(), libMesh::MeshOutput< MT >::write_nodal_data(), and libMesh::Nemesis_IO_Helper::write_nodal_solution().
template<typename T> virtual void libMesh::NumericVector< T >::localize (NumericVector< T > & v_local) const pure virtual
Same, but fills a NumericVector<T> instead of a std::vector.
Implemented in libMesh::PetscVector< T >, libMesh::EpetraVector< T >, libMesh::DistributedVector< T >, libMesh::EigenSparseVector< T >, and libMesh::LaspackVector< T >.
template<typename T> virtual void libMesh::NumericVector< T >::localize (NumericVector< T > & v_local, const std::vector< numeric_index_type > & send_list) const pure virtual
Creates a local vector v_local containing only information relevant to this processor, as defined by the send_list.
Implemented in libMesh::PetscVector< T >, libMesh::EpetraVector< T >, libMesh::DistributedVector< T >, libMesh::EigenSparseVector< T >, and libMesh::LaspackVector< T >.
template<typename T> virtual void libMesh::NumericVector< T >::localize (std::vector< T > & , const std::vector< numeric_index_type > &) const pure virtual
Fill in the local std::vector "v_local" with the global indices given in "indices". Note that indices can be different on every processor, and the same index can be localized to more than one processor. The resulting v_local can be shorter than the original, and the entries will be in the order specified by indices.
Example: On 4 procs *this = {a, b, c, d, e, f, g, h, i} is a parallel vector. On each proc, the indices arrays are set up as: proc0, indices = {1,2,4,5} proc1, indices = {2,5,6,8} proc2, indices = {2,3,6,7} proc3, indices = {0,1,2,3}
After calling this version of localize, the v_local vectors are: proc0, v_local = {b,c,e,f} proc1, v_local = {c,f,g,i} proc2, v_local = {c,d,g,h} proc3, v_local = {a,b,c,d}
This function is useful in parallel I/O routines, when you have a parallel vector of solution values which you want to write a subset of.
Implemented in libMesh::PetscVector< T >, libMesh::EpetraVector< T >, libMesh::DistributedVector< T >, libMesh::EigenSparseVector< T >, and libMesh::LaspackVector< T >.
template<typename T> virtual void libMesh::NumericVector< T >::localize (const numeric_index_type first_local_idx, const numeric_index_type last_local_idx, const std::vector< numeric_index_type > & send_list) pure virtual
Updates a local vector with selected values from neighboring processors, as defined by send_list.
Implemented in libMesh::PetscVector< T >, libMesh::EpetraVector< T >, libMesh::DistributedVector< T >, libMesh::EigenSparseVector< T >, and libMesh::LaspackVector< T >.
template<typename T> virtual void libMesh::NumericVector< T >::localize_to_one (std::vector< T > & v_local, const processor_id_type proc_id = 0) const pure virtual
Creates a local copy of the global vector in v_local only on processor proc_id. By default the data is sent to processor 0. This method is useful for outputting data from one processor.
Implemented in libMesh::PetscVector< T >, libMesh::EpetraVector< T >, libMesh::DistributedVector< T >, libMesh::LaspackVector< T >, and libMesh::EigenSparseVector< T >.
Referenced by libMesh::EquationSystems::get_solution(), and libMesh::NumericVector< Number >::operator/=().
template<typename T> virtual Real libMesh::NumericVector< T >::max () const pure virtual
Returns
the maximum element in the vector. In case of complex numbers, this returns the maximum Real part.
Implemented in libMesh::PetscVector< T >, libMesh::EpetraVector< T >, libMesh::EigenSparseVector< T >, libMesh::LaspackVector< T >, and libMesh::DistributedVector< T >.
Referenced by libMesh::NumericVector< Number >::closed().
template<typename T> virtual Real libMesh::NumericVector< T >::min () const pure virtual
Returns
the minimum element in the vector. In case of complex numbers, this returns the minimum Real part.
Implemented in libMesh::PetscVector< T >, libMesh::EpetraVector< T >, libMesh::EigenSparseVector< T >, libMesh::LaspackVector< T >, and libMesh::DistributedVector< T >.
Referenced by libMesh::NumericVector< Number >::closed().
static unsigned int libMesh::ReferenceCounter::n_objects () inline static inherited
Prints the number of outstanding (created, but not yet destroyed) objects.
Definition at line 76 of file reference_counter.h.
References libMesh::ReferenceCounter::_n_objects, libMesh::ReferenceCounter::disable_print_counter_info(), libMesh::ReferenceCounter::enable_print_counter_info(), libMesh::ReferenceCounter::increment_constructor_count(), libMesh::ReferenceCounter::increment_destructor_count(), and libMesh::Quality::name().
Referenced by libMesh::System::hide_output(), and libMesh::LibMeshInit::LibMeshInit().
   { return _n_objects; }
processor_id_type libMesh::ParallelObject::n_processors () const inline inherited
Returns
the number of processors in the group.
Definition at line 93 of file parallel_object.h.
References libMesh::ParallelObject::_communicator, and libMesh::Parallel::Communicator::size().
Referenced by libMesh::ParmetisPartitioner::_do_repartition(), libMesh::BoundaryInfo::_find_id_maps(), libMesh::DistributedMesh::add_elem(), libMesh::DistributedMesh::add_node(), libMesh::LaplaceMeshSmoother::allgather_graph(), libMesh::FEMSystem::assembly(), libMesh::ParmetisPartitioner::assign_partitioning(), libMesh::AztecLinearSolver< T >::AztecLinearSolver(), libMesh::MeshCommunication::broadcast(), libMesh::BoundaryInfo::build_node_list_from_side_list(), libMesh::DistributedMesh::clear(), libMesh::Nemesis_IO_Helper::compute_border_node_ids(), libMesh::Nemesis_IO_Helper::construct_nemesis_filename(), libMesh::MeshTools::correct_node_proc_ids(), libMesh::UnstructuredMesh::create_pid_mesh(), libMesh::DofMap::distribute_dofs(), libMesh::DofMap::distribute_local_dofs_node_major(), libMesh::DofMap::distribute_local_dofs_var_major(), libMesh::DistributedMesh::DistributedMesh(), libMesh::EnsightIO::EnsightIO(), libMesh::MeshCommunication::gather(), libMesh::MeshCommunication::gather_neighboring_elements(), libMesh::MeshBase::get_info(), libMesh::EquationSystems::get_solution(), libMesh::DistributedVector< T >::init(), libMesh::SystemSubsetBySubdomain::init(), libMesh::ParmetisPartitioner::initialize(), libMesh::Nemesis_IO_Helper::initialize(), libMesh::DistributedMesh::insert_elem(), libMesh::MeshTools::libmesh_assert_parallel_consistent_procids< Elem >(), libMesh::MeshTools::libmesh_assert_parallel_consistent_procids< Node >(), libMesh::MeshTools::libmesh_assert_topology_consistent_procids< Node >(), libMesh::MeshTools::libmesh_assert_valid_boundary_ids(), libMesh::MeshTools::libmesh_assert_valid_dof_ids(), libMesh::MeshTools::libmesh_assert_valid_neighbors(), libMesh::MeshTools::libmesh_assert_valid_refinement_flags(), libMesh::DofMap::local_variable_indices(), libMesh::MeshBase::n_active_elem_on_proc(), libMesh::MeshBase::n_elem_on_proc(), libMesh::MeshBase::n_nodes_on_proc(), libMesh::SparsityPattern::Build::parallel_sync(), libMesh::Partitioner::partition(), libMesh::MeshBase::partition(), libMesh::Partitioner::partition_unpartitioned_elements(), libMesh::PetscLinearSolver< T >::PetscLinearSolver(), libMesh::System::point_gradient(), libMesh::System::point_hessian(), libMesh::System::point_value(), libMesh::SparseMatrix< T >::print(), libMesh::MeshTools::processor_bounding_box(), libMesh::NameBasedIO::read(), libMesh::Nemesis_IO::read(), libMesh::XdrIO::read(), libMesh::MeshCommunication::redistribute(), libMesh::DistributedMesh::renumber_dof_objects(), libMesh::Partitioner::repartition(), libMesh::MeshCommunication::send_coarse_ghosts(), libMesh::Partitioner::set_node_processor_ids(), libMesh::DofMap::set_nonlocal_dof_objects(), libMesh::Parallel::Sort< KeyType, IdxType >::sort(), libMesh::DistributedMesh::update_parallel_id_counts(), libMesh::GMVIO::write_binary(), libMesh::GMVIO::write_discontinuous_gmv(), libMesh::XdrIO::write_serialized_bcs_helper(), libMesh::XdrIO::write_serialized_connectivity(), libMesh::XdrIO::write_serialized_nodes(), and libMesh::XdrIO::write_serialized_nodesets().
   { return cast_int<processor_id_type>(_communicator.size()); }
template<typename T> virtual T libMesh::NumericVector< T >::operator() (const numeric_index_type i) const pure virtual
Access components, returns U(i).
Implemented in libMesh::PetscVector< T >, libMesh::EpetraVector< T >, libMesh::EigenSparseVector< T >, libMesh::LaspackVector< T >, and libMesh::DistributedVector< T >.
Referenced by libMesh::NumericVector< Number >::closed().
template<typename T> NumericVector<T>& libMesh::NumericVector< T >::operator*= (const T a) inline
Multiplication operator. Equivalent to U.scale(a)
Definition at line 381 of file numeric_vector.h.
 { this->scale(a); return *this; }
template<typename T> virtual NumericVector<T>& libMesh::NumericVector< T >::operator+= (const NumericVector< T > & V) pure virtual
Addition operator. Fast equivalent to U.add(1, V).
Implemented in libMesh::PetscVector< T >, libMesh::EpetraVector< T >, libMesh::EigenSparseVector< T >, libMesh::LaspackVector< T >, and libMesh::DistributedVector< T >.
Referenced by libMesh::NumericVector< Number >::el().
template<typename T> virtual NumericVector<T>& libMesh::NumericVector< T >::operator-= (const NumericVector< T > & V) pure virtual
Subtraction operator. Fast equivalent to U.add(-1, V).
Implemented in libMesh::PetscVector< T >, libMesh::EpetraVector< T >, libMesh::EigenSparseVector< T >, libMesh::LaspackVector< T >, and libMesh::DistributedVector< T >.
Referenced by libMesh::NumericVector< Number >::el().
template<typename T> NumericVector<T>& libMesh::NumericVector< T >::operator/= (const T a) inline
Division operator. Equivalent to U.scale(1./a)
Definition at line 387 of file numeric_vector.h.
Referenced by libMesh::NumericVector< Number >::operator/=().
 { this->scale(1./a); return *this; }
template<typename T> virtual NumericVector<T>& libMesh::NumericVector< T >::operator/= (NumericVector< T > &) pure virtual
Pointwise Division operator. ie divide every entry in this vector by the entry in v
Implemented in libMesh::PetscVector< T >, libMesh::EpetraVector< T >, libMesh::EigenSparseVector< T >, libMesh::LaspackVector< T >, and libMesh::DistributedVector< T >.
template<typename T> virtual NumericVector<T>& libMesh::NumericVector< T >::operator= (const T s) pure virtual
: fill all components.
Implemented in libMesh::PetscVector< T >, libMesh::EpetraVector< T >, libMesh::EigenSparseVector< T >, libMesh::LaspackVector< T >, and libMesh::DistributedVector< T >.
Referenced by libMesh::NumericVector< Number >::closed().
template<typename T> virtual NumericVector<T>& libMesh::NumericVector< T >::operator= (const NumericVector< T > & V) pure virtual
: copy all components.
Implemented in libMesh::PetscVector< T >, libMesh::EpetraVector< T >, libMesh::EigenSparseVector< T >, libMesh::LaspackVector< T >, and libMesh::DistributedVector< T >.
template<typename T> virtual NumericVector<T>& libMesh::NumericVector< T >::operator= (const std::vector< T > & v) pure virtual
: copy all components.
Implemented in libMesh::PetscVector< T >, libMesh::EpetraVector< T >, libMesh::EigenSparseVector< T >, libMesh::LaspackVector< T >, and libMesh::DistributedVector< T >.
template<typename T> virtual void libMesh::NumericVector< T >::pointwise_mult (const NumericVector< T > & vec1, const NumericVector< T > & vec2) pure virtual
Computes the pointwise (i.e. component-wise) product of vec1 and vec2 and stores the result in *this.
Implemented in libMesh::PetscVector< T >, libMesh::EpetraVector< T >, libMesh::DistributedVector< T >, libMesh::LaspackVector< T >, and libMesh::EigenSparseVector< T >.
Referenced by libMesh::TensorShellMatrix< T >::get_diagonal(), and libMesh::NumericVector< Number >::operator/=().
template<typename T > void libMesh::NumericVector< T >::print (std::ostream & os = libMesh::out) const inline virtual
Prints the local contents of the vector, by default to libMesh::out
Definition at line 921 of file numeric_vector.h.
References libMesh::NumericVector< T >::first_local_index(), libMesh::NumericVector< T >::initialized(), libMesh::NumericVector< T >::last_local_index(), libMesh::libmesh_assert(), libMesh::NumericVector< T >::local_size(), and libMesh::NumericVector< T >::size().
Referenced by libMesh::NumericVector< Number >::operator/=().
 {
   libmesh_assert (this->initialized());
   os << "Size\tglobal =  " << this->size()
      << "\t\tlocal =  " << this->local_size() << std::endl;
   os << "#\tValue" << std::endl;
   for (numeric_index_type i=this->first_local_index(); i<this->last_local_index(); i++)
     os << i << "\t" << (*this)(i) << std::endl;
 }
template<> void libMesh::NumericVector< Complex >::print (std::ostream & os) const inline
Definition at line 903 of file numeric_vector.h.
References libMesh::NumericVector< T >::first_local_index(), libMesh::NumericVector< T >::initialized(), libMesh::NumericVector< T >::last_local_index(), libMesh::libmesh_assert(), libMesh::NumericVector< T >::local_size(), and libMesh::NumericVector< T >::size().
 {
   libmesh_assert (this->initialized());
   os << "Size\tglobal =  " << this->size()
      << "\t\tlocal =  " << this->local_size() << std::endl;
   // std::complex<>::operator<<() is defined, but use this form
   os << "#\tReal part\t\tImaginary part" << std::endl;
   for (numeric_index_type i=this->first_local_index(); i<this->last_local_index(); i++)
     os << i << "\t"
        << (*this)(i).real() << "\t\t"
        << (*this)(i).imag() << std::endl;
 }
template<typename T > void libMesh::NumericVector< T >::print_global (std::ostream & os = libMesh::out) const inline virtual
Prints the global contents of the vector, by default to libMesh::out
Definition at line 958 of file numeric_vector.h.
References libMesh::NumericVector< T >::initialized(), libMesh::libmesh_assert(), libMesh::NumericVector< T >::localize(), libMesh::ParallelObject::processor_id(), and libMesh::NumericVector< T >::size().
Referenced by libMesh::NumericVector< Number >::operator/=().
 {
   libmesh_assert (this->initialized());
   std::vector<T> v(this->size());
   this->localize(v);
   // Right now we only want one copy of the output
   if (this->processor_id())
     return;
   os << "Size\tglobal =  " << this->size() << std::endl;
   os << "#\tValue" << std::endl;
   for (numeric_index_type i=0; i!=v.size(); i++)
     os << i << "\t" << v[i] << std::endl;
 }
template<> void libMesh::NumericVector< Complex >::print_global (std::ostream & os) const inline
Definition at line 936 of file numeric_vector.h.
References libMesh::NumericVector< T >::initialized(), libMesh::libmesh_assert(), libMesh::NumericVector< T >::localize(), libMesh::ParallelObject::processor_id(), and libMesh::NumericVector< T >::size().
 {
   libmesh_assert (this->initialized());
   std::vector<Complex> v(this->size());
   this->localize(v);
   // Right now we only want one copy of the output
   if (this->processor_id())
     return;
   os << "Size\tglobal =  " << this->size() << std::endl;
   os << "#\tReal part\t\tImaginary part" << std::endl;
   for (numeric_index_type i=0; i!=v.size(); i++)
     os << i << "\t"
        << v[i].real() << "\t\t"
        << v[i].imag() << std::endl;
 }
void libMesh::ReferenceCounter::print_info (std::ostream & out = libMesh::out) static inherited
Prints the reference information, by default to libMesh::out.
Definition at line 88 of file reference_counter.C.
References libMesh::ReferenceCounter::_enable_print_counter, and libMesh::ReferenceCounter::get_info().
Referenced by libMesh::LibMeshInit::LibMeshInit().
 {
   if( _enable_print_counter ) out_stream << ReferenceCounter::get_info();
 }
template<typename T> virtual void libMesh::NumericVector< T >::print_matlab (const std::string & = "") const inline virtual
Print the contents of the matrix in Matlab's sparse matrix format. Optionally prints the matrix to the file named name. If name is not specified it is dumped to the screen.
Reimplemented in libMesh::PetscVector< T >.
Definition at line 677 of file numeric_vector.h.
   {
     libmesh_not_implemented();
   }
processor_id_type libMesh::ParallelObject::processor_id () const inline inherited
Returns
the rank of this processor in the group.
Definition at line 99 of file parallel_object.h.
References libMesh::ParallelObject::_communicator, and libMesh::Parallel::Communicator::rank().
Referenced by libMesh::BoundaryInfo::_find_id_maps(), libMesh::EquationSystems::_read_impl(), libMesh::DistributedMesh::add_elem(), libMesh::BoundaryInfo::add_elements(), libMesh::DofMap::add_neighbors_to_send_list(), libMesh::DistributedMesh::add_node(), libMesh::MeshRefinement::add_node(), libMesh::MeshTools::Modification::all_tri(), libMesh::FEMSystem::assembly(), libMesh::ParmetisPartitioner::assign_partitioning(), libMesh::MeshCommunication::broadcast(), libMesh::EquationSystems::build_discontinuous_solution_vector(), libMesh::Nemesis_IO_Helper::build_element_and_node_maps(), libMesh::ParmetisPartitioner::build_graph(), libMesh::InfElemBuilder::build_inf_elem(), libMesh::BoundaryInfo::build_node_list_from_side_list(), libMesh::DofMap::build_sparsity(), libMesh::DistributedMesh::clear(), libMesh::ExodusII_IO_Helper::close(), libMesh::Nemesis_IO_Helper::compute_border_node_ids(), libMesh::Nemesis_IO_Helper::compute_communication_map_parameters(), libMesh::Nemesis_IO_Helper::compute_internal_and_border_elems_and_internal_nodes(), libMesh::Nemesis_IO_Helper::compute_node_communication_maps(), libMesh::Nemesis_IO_Helper::compute_num_global_elem_blocks(), libMesh::Nemesis_IO_Helper::compute_num_global_nodesets(), libMesh::Nemesis_IO_Helper::compute_num_global_sidesets(), libMesh::Nemesis_IO_Helper::construct_nemesis_filename(), libMesh::MeshTools::correct_node_proc_ids(), libMesh::ExodusII_IO_Helper::create(), libMesh::DistributedMesh::delete_elem(), libMesh::DistributedMesh::delete_node(), libMesh::MeshCommunication::delete_remote_elements(), libMesh::DofMap::distribute_dofs(), libMesh::DofMap::distribute_local_dofs_node_major(), libMesh::DofMap::distribute_local_dofs_var_major(), libMesh::DistributedMesh::DistributedMesh(), libMesh::EnsightIO::EnsightIO(), libMesh::MeshFunction::find_element(), libMesh::MeshFunction::find_elements(), libMesh::UnstructuredMesh::find_neighbors(), libMesh::MeshCommunication::gather(), libMesh::MeshCommunication::gather_neighboring_elements(), libMesh::Nemesis_IO_Helper::get_cmap_params(), libMesh::Nemesis_IO_Helper::get_eb_info_global(), libMesh::Nemesis_IO_Helper::get_elem_cmap(), libMesh::Nemesis_IO_Helper::get_elem_map(), libMesh::MeshBase::get_info(), libMesh::DofMap::get_info(), libMesh::Nemesis_IO_Helper::get_init_global(), libMesh::Nemesis_IO_Helper::get_init_info(), libMesh::Nemesis_IO_Helper::get_loadbal_param(), libMesh::Nemesis_IO_Helper::get_node_cmap(), libMesh::Nemesis_IO_Helper::get_node_map(), libMesh::Nemesis_IO_Helper::get_ns_param_global(), libMesh::EquationSystems::get_solution(), libMesh::Nemesis_IO_Helper::get_ss_param_global(), libMesh::SparsityPattern::Build::handle_vi_vj(), libMesh::DistributedVector< T >::init(), libMesh::SystemSubsetBySubdomain::init(), libMesh::ParmetisPartitioner::initialize(), libMesh::ExodusII_IO_Helper::initialize(), libMesh::ExodusII_IO_Helper::initialize_element_variables(), libMesh::ExodusII_IO_Helper::initialize_global_variables(), libMesh::ExodusII_IO_Helper::initialize_nodal_variables(), libMesh::DistributedMesh::insert_elem(), libMesh::DofMap::is_evaluable(), libMesh::SparsityPattern::Build::join(), libMesh::MeshTools::libmesh_assert_parallel_consistent_procids< Elem >(), libMesh::MeshTools::libmesh_assert_parallel_consistent_procids< Node >(), libMesh::MeshTools::libmesh_assert_valid_neighbors(), libMesh::DistributedMesh::libmesh_assert_valid_parallel_object_ids(), libMesh::DofMap::local_variable_indices(), libMesh::MeshRefinement::make_coarsening_compatible(), libMesh::MeshBase::n_active_local_elem(), libMesh::BoundaryInfo::n_boundary_conds(), libMesh::BoundaryInfo::n_edge_conds(), libMesh::System::n_local_dofs(), libMesh::MeshBase::n_local_elem(), libMesh::MeshBase::n_local_nodes(), libMesh::BoundaryInfo::n_nodeset_conds(), libMesh::BoundaryInfo::n_shellface_conds(), libMesh::WeightedPatchRecoveryErrorEstimator::EstimateError::operator()(), libMesh::SparsityPattern::Build::operator()(), libMesh::PatchRecoveryErrorEstimator::EstimateError::operator()(), libMesh::SparsityPattern::Build::parallel_sync(), libMesh::MetisPartitioner::partition_range(), libMesh::System::point_gradient(), libMesh::System::point_hessian(), libMesh::System::point_value(), libMesh::SparseMatrix< T >::print(), libMesh::NumericVector< T >::print_global(), libMesh::Nemesis_IO_Helper::put_cmap_params(), libMesh::Nemesis_IO_Helper::put_elem_cmap(), libMesh::Nemesis_IO_Helper::put_elem_map(), libMesh::Nemesis_IO_Helper::put_loadbal_param(), libMesh::Nemesis_IO_Helper::put_node_cmap(), libMesh::Nemesis_IO_Helper::put_node_map(), libMesh::NameBasedIO::read(), libMesh::Nemesis_IO::read(), libMesh::XdrIO::read(), libMesh::ExodusII_IO_Helper::read_elem_num_map(), libMesh::ExodusII_IO_Helper::read_node_num_map(), libMesh::XdrIO::read_serialized_bc_names(), libMesh::XdrIO::read_serialized_bcs_helper(), libMesh::XdrIO::read_serialized_connectivity(), libMesh::XdrIO::read_serialized_nodes(), libMesh::XdrIO::read_serialized_nodesets(), libMesh::XdrIO::read_serialized_subdomain_names(), libMesh::MeshCommunication::redistribute(), libMesh::DistributedMesh::renumber_dof_objects(), libMesh::MeshCommunication::send_coarse_ghosts(), libMesh::Partitioner::set_node_processor_ids(), libMesh::DofMap::set_nonlocal_dof_objects(), libMesh::LaplaceMeshSmoother::smooth(), libMesh::MeshTools::total_weight(), libMesh::Parallel::Packing< Node * >::unpack(), libMesh::Parallel::Packing< Elem * >::unpack(), libMesh::DistributedMesh::update_parallel_id_counts(), libMesh::MeshTools::weight(), libMesh::NameBasedIO::write(), libMesh::XdrIO::write(), libMesh::EquationSystems::write(), libMesh::GMVIO::write_discontinuous_gmv(), libMesh::ExodusII_IO::write_element_data(), libMesh::ExodusII_IO_Helper::write_element_values(), libMesh::ExodusII_IO_Helper::write_elements(), libMesh::ExodusII_IO::write_global_data(), libMesh::ExodusII_IO_Helper::write_global_values(), libMesh::ExodusII_IO::write_information_records(), libMesh::ExodusII_IO_Helper::write_information_records(), libMesh::ExodusII_IO_Helper::write_nodal_coordinates(), libMesh::UCDIO::write_nodal_data(), libMesh::ExodusII_IO::write_nodal_data(), libMesh::ExodusII_IO::write_nodal_data_discontinuous(), libMesh::ExodusII_IO_Helper::write_nodal_values(), libMesh::Nemesis_IO_Helper::write_nodesets(), libMesh::ExodusII_IO_Helper::write_nodesets(), libMesh::XdrIO::write_serialized_bc_names(), libMesh::XdrIO::write_serialized_bcs_helper(), libMesh::XdrIO::write_serialized_connectivity(), libMesh::XdrIO::write_serialized_nodes(), libMesh::XdrIO::write_serialized_nodesets(), libMesh::XdrIO::write_serialized_subdomain_names(), libMesh::Nemesis_IO_Helper::write_sidesets(), libMesh::ExodusII_IO_Helper::write_sidesets(), libMesh::ExodusII_IO::write_timestep(), and libMesh::ExodusII_IO_Helper::write_timestep().
   { return cast_int<processor_id_type>(_communicator.rank()); }
template<typename T> virtual void libMesh::NumericVector< T >::reciprocal () pure virtual
Replace each entry v_i of this vector by its reciprocal, 1/v_i.
Implemented in libMesh::PetscVector< T >, libMesh::EpetraVector< T >, libMesh::EigenSparseVector< T >, libMesh::LaspackVector< T >, and libMesh::DistributedVector< T >.
Referenced by libMesh::NumericVector< Number >::operator/=().
template<typename T> virtual void libMesh::NumericVector< T >::scale (const T factor) pure virtual
Scale each element of the vector by the given factor.
Implemented in libMesh::PetscVector< T >, libMesh::EpetraVector< T >, libMesh::DistributedVector< T >, libMesh::EigenSparseVector< T >, and libMesh::LaspackVector< T >.
Referenced by libMesh::ContinuationSystem::continuation_solve(), libMesh::ContinuationSystem::initialize_tangent(), libMesh::NumericVector< Number >::operator*=(), libMesh::NumericVector< Number >::operator/=(), libMesh::ContinuationSystem::solve_tangent(), libMesh::NewmarkSystem::update_u_v_a(), and libMesh::TensorShellMatrix< T >::vector_mult().
template<typename T> virtual void libMesh::NumericVector< T >::set (const numeric_index_type i, const T value) pure virtual
v(i) = value
Implemented in libMesh::PetscVector< T >, libMesh::EpetraVector< T >, libMesh::EigenSparseVector< T >, libMesh::LaspackVector< T >, and libMesh::DistributedVector< T >.
Referenced by libMesh::DofMap::enforce_adjoint_constraints_exactly(), libMesh::DofMap::enforce_constraints_exactly(), libMesh::EquationSystems::get_solution(), libMesh::VectorSetAction< Val >::insert(), libMesh::System::project_vector(), libMesh::System::read_SCALAR_dofs(), libMesh::System::read_serialized_blocked_dof_objects(), and libMesh::System::zero_variable().
template<typename T> virtual numeric_index_type libMesh::NumericVector< T >::size () const pure virtual
Returns
dimension of the vector. This function was formerly called n(), but was renamed to get the NumericVector<T> class closer to the C++ standard library's std::vector container.
Implemented in libMesh::PetscVector< T >, libMesh::EpetraVector< T >, libMesh::EigenSparseVector< T >, libMesh::LaspackVector< T >, and libMesh::DistributedVector< T >.
Referenced by libMesh::NumericVector< T >::add_vector(), libMesh::System::calculate_norm(), libMesh::NumericVector< Number >::closed(), libMesh::DofMap::enforce_adjoint_constraints_exactly(), libMesh::DofMap::enforce_constraints_exactly(), libMesh::DofMap::extract_local_vector(), libMesh::DistributedVector< T >::init(), libMesh::LaspackVector< T >::init(), libMesh::EigenSparseVector< T >::init(), libMesh::EpetraVector< T >::init(), libMesh::NumericVector< T >::insert(), libMesh::DistributedVector< T >::operator/=(), libMesh::LaspackVector< T >::operator/=(), libMesh::EigenSparseVector< T >::operator/=(), libMesh::EpetraVector< T >::operator/=(), libMesh::NumericVector< T >::print(), libMesh::NumericVector< T >::print_global(), libMesh::System::project_vector(), libMesh::PetscLinearSolver< T >::solve(), and libMesh::System::write_serialized_vector().
template<class T > Real libMesh::NumericVector< T >::subset_l1_norm (const std::set< numeric_index_type > & indices) const virtual
Returns
the -norm of the vector, i.e. the sum of the absolute values for the specified entries in the vector.
Note that the indices must necessary live on this processor.
Definition at line 323 of file numeric_vector.C.
References std::abs(), and libMesh::Real.
Referenced by libMesh::NumericVector< Number >::closed(), and libMesh::System::discrete_var_norm().
 {
   const NumericVector<T> & v = *this;
   std::set<numeric_index_type>::const_iterator it = indices.begin();
   const std::set<numeric_index_type>::const_iterator it_end = indices.end();
   Real norm = 0;
   for(; it!=it_end; ++it)
     norm += std::abs(v(*it));
   this->comm().sum(norm);
   return norm;
 }
template<class T > Real libMesh::NumericVector< T >::subset_l2_norm (const std::set< numeric_index_type > & indices) const virtual
Returns
the -norm of the vector, i.e. the square root of the sum of the squares of the elements for the specified entries in the vector.
Note that the indices must necessary live on this processor.
Definition at line 341 of file numeric_vector.C.
References libMesh::TensorTools::norm_sq(), and libMesh::Real.
Referenced by libMesh::NumericVector< Number >::closed(), and libMesh::System::discrete_var_norm().
 {
   const NumericVector<T> & v = *this;
   std::set<numeric_index_type>::const_iterator it = indices.begin();
   const std::set<numeric_index_type>::const_iterator it_end = indices.end();
   Real norm = 0;
   for(; it!=it_end; ++it)
     norm += TensorTools::norm_sq(v(*it));
   this->comm().sum(norm);
   return std::sqrt(norm);
 }
template<class T > Real libMesh::NumericVector< T >::subset_linfty_norm (const std::set< numeric_index_type > & indices) const virtual
Returns
the maximum absolute value of the specified entries of this vector, which is the -norm of a vector.
Note that the indices must necessary live on this processor.
Definition at line 359 of file numeric_vector.C.
References std::abs(), and libMesh::Real.
Referenced by libMesh::NumericVector< Number >::closed(), and libMesh::System::discrete_var_norm().
 {
   const NumericVector<T> & v = *this;
   std::set<numeric_index_type>::const_iterator it = indices.begin();
   const std::set<numeric_index_type>::const_iterator it_end = indices.end();
   Real norm = 0;
   for(; it!=it_end; ++it)
     {
       Real value = std::abs(v(*it));
       if(value > norm)
         norm = value;
     }
   this->comm().max(norm);
   return norm;
 }
template<typename T> virtual T libMesh::NumericVector< T >::sum () const pure virtual
returns the sum of the elements in a vector
Implemented in libMesh::PetscVector< T >, libMesh::EpetraVector< T >, libMesh::EigenSparseVector< T >, libMesh::LaspackVector< T >, and libMesh::DistributedVector< T >.
Referenced by libMesh::NumericVector< Number >::closed().
template<typename T> void libMesh::NumericVector< T >::swap (NumericVector< T > & v) inline virtual
Exchanges the values/sizes of two vectors. There should be enough indirection in subclasses to make this an O(1) header-swap operation.
Reimplemented in libMesh::PetscVector< T >, libMesh::EpetraVector< T >, libMesh::DistributedVector< T >, libMesh::LaspackVector< T >, and libMesh::EigenSparseVector< T >.
Definition at line 979 of file numeric_vector.h.
References libMesh::NumericVector< T >::_is_closed, libMesh::NumericVector< T >::_is_initialized, libMesh::NumericVector< T >::_type, and swap().
Referenced by libMesh::UniformRefinementEstimator::_estimate_error(), libMesh::NumericVector< Number >::create_subvector(), libMesh::WeightedPatchRecoveryErrorEstimator::estimate_error(), libMesh::JumpErrorEstimator::estimate_error(), libMesh::PatchRecoveryErrorEstimator::estimate_error(), libMesh::AdjointRefinementEstimator::estimate_error(), libMesh::ExactErrorEstimator::estimate_error(), libMesh::EpetraVector< T >::swap(), and libMesh::PetscVector< T >::swap().
 {
   std::swap(_is_closed, v._is_closed);
   std::swap(_is_initialized, v._is_initialized);
   std::swap(_type, v._type);
 }
template<typename T> ParallelType libMesh::NumericVector< T >::type () const inline
Returns
the type (SERIAL, PARALLEL, GHOSTED) of the vector.
Definition at line 137 of file numeric_vector.h.
Referenced by libMesh::PetscVector< T >::clone(), libMesh::PetscVector< T >::close(), libMesh::DofMap::enforce_adjoint_constraints_exactly(), libMesh::DofMap::enforce_constraints_exactly(), libMesh::EpetraVector< T >::EpetraVector(), libMesh::MeshFunction::find_element(), libMesh::MeshFunction::find_elements(), libMesh::PetscVector< T >::get(), libMesh::DistributedVector< T >::init(), libMesh::EigenSparseVector< T >::init(), libMesh::LaspackVector< T >::init(), libMesh::EpetraVector< T >::init(), libMesh::PetscVector< T >::localize(), libMesh::PetscVector< T >::operator()(), libMesh::PetscVector< T >::operator=(), libMesh::System::project_vector(), libMesh::System::read_serialized_vector(), libMesh::PetscVector< T >::zero(), and libMesh::PetscVector< T >::zero_clone().
 { return _type; }
template<typename T> ParallelType& libMesh::NumericVector< T >::type () inline
Returns
the type (SERIAL, PARALLEL, GHOSTED) of the vector.
Definition at line 142 of file numeric_vector.h.
 { return _type; }
template<typename T> virtual void libMesh::NumericVector< T >::zero () pure virtual
Set all entries to zero. Equivalent to v = 0, but more obvious and faster.
Implemented in libMesh::PetscVector< T >, libMesh::EpetraVector< T >, libMesh::EigenSparseVector< T >, libMesh::LaspackVector< T >, and libMesh::DistributedVector< T >.
Referenced by libMesh::ImplicitSystem::assemble(), libMesh::ExplicitSystem::assemble_qoi_derivative(), libMesh::FEMSystem::assemble_qoi_derivative(), libMesh::FEMSystem::assembly(), libMesh::NumericVector< Number >::closed(), libMesh::ContinuationSystem::continuation_solve(), libMesh::NewmarkSystem::initial_conditions(), libMesh::NewtonSolver::solve(), libMesh::ContinuationSystem::solve_tangent(), libMesh::NewmarkSystem::update_rhs(), libMesh::SumShellMatrix< T >::vector_mult(), and libMesh::SparseMatrix< T >::vector_mult().
template<typename T> virtual UniquePtr<NumericVector<T> > libMesh::NumericVector< T >::zero_clone () const pure virtual
Creates a vector which has the same type, size and partitioning as this vector, but whose data is all zero. Returns it in an UniquePtr. This must be overloaded in the derived classes.
Implemented in libMesh::PetscVector< T >, libMesh::EpetraVector< T >, libMesh::EigenSparseVector< T >, libMesh::LaspackVector< T >, and libMesh::DistributedVector< T >.
Referenced by libMesh::NumericVector< Number >::closed(), libMesh::SumShellMatrix< T >::get_diagonal(), libMesh::NewtonSolver::solve(), and libMesh::ImplicitSystem::weighted_sensitivity_adjoint_solve().
Friends And Related Function Documentation
template<typename T> std::ostream& operator<< (std::ostream & os, const NumericVector< T > & v) friend
Same as above but allows you to use stream syntax.
Definition at line 665 of file numeric_vector.h.
   {
     v.print_global(os);
     return os;
   }
Member Data Documentation
const Parallel::Communicator& libMesh::ParallelObject::_communicator protected inherited
Definition at line 105 of file parallel_object.h.
Referenced by libMesh::EquationSystems::build_parallel_solution_vector(), libMesh::ParallelObject::comm(), libMesh::EquationSystems::get_solution(), libMesh::ParallelObject::n_processors(), libMesh::ParallelObject::operator=(), and libMesh::ParallelObject::processor_id().
ReferenceCounter::Counts libMesh::ReferenceCounter::_counts static protected inherited
Actually holds the data.
Definition at line 115 of file reference_counter.h.
Referenced by libMesh::ReferenceCounter::get_info(), libMesh::ReferenceCounter::increment_constructor_count(), and libMesh::ReferenceCounter::increment_destructor_count().
bool libMesh::ReferenceCounter::_enable_print_counter = true static protected inherited
Flag to control whether reference count information is printed when print_info is called.
Definition at line 134 of file reference_counter.h.
Referenced by libMesh::ReferenceCounter::disable_print_counter_info(), libMesh::ReferenceCounter::enable_print_counter_info(), and libMesh::ReferenceCounter::print_info().
template<typename T> bool libMesh::NumericVector< T >::_is_closed protected
Flag to see if the Numeric assemble routines have been called yet
Definition at line 707 of file numeric_vector.h.
Referenced by libMesh::EigenSparseVector< T >::add(), libMesh::LaspackVector< T >::add(), libMesh::DistributedVector< T >::clear(), libMesh::LaspackVector< T >::clear(), libMesh::EigenSparseVector< T >::clear(), libMesh::EpetraVector< T >::clear(), libMesh::PetscVector< T >::clear(), libMesh::NumericVector< T >::clear(), libMesh::DistributedVector< T >::close(), libMesh::LaspackVector< T >::close(), libMesh::EigenSparseVector< T >::close(), libMesh::EpetraVector< T >::close(), libMesh::PetscVector< T >::close(), libMesh::NumericVector< Number >::closed(), libMesh::EpetraVector< T >::EpetraVector(), libMesh::EigenSparseVector< T >::init(), libMesh::EpetraVector< T >::init(), libMesh::PetscVector< T >::init(), libMesh::DistributedVector< T >::localize(), libMesh::DistributedVector< T >::operator=(), libMesh::PetscVector< T >::PetscVector(), libMesh::LaspackVector< T >::set(), libMesh::EigenSparseVector< T >::set(), libMesh::EigenSparseVector< T >::swap(), libMesh::NumericVector< T >::swap(), and libMesh::LaspackVector< T >::~LaspackVector().
template<typename T> bool libMesh::NumericVector< T >::_is_initialized protected
Flag to tell if init has been called yet
Definition at line 713 of file numeric_vector.h.
Referenced by libMesh::DistributedVector< T >::clear(), libMesh::LaspackVector< T >::clear(), libMesh::EigenSparseVector< T >::clear(), libMesh::EpetraVector< T >::clear(), libMesh::PetscVector< T >::clear(), libMesh::NumericVector< T >::clear(), libMesh::PetscVector< T >::create_subvector(), libMesh::EpetraVector< T >::EpetraVector(), libMesh::DistributedVector< T >::init(), libMesh::EigenSparseVector< T >::init(), libMesh::EpetraVector< T >::init(), libMesh::PetscVector< T >::init(), libMesh::NumericVector< Number >::initialized(), libMesh::DistributedVector< T >::localize(), libMesh::DistributedVector< T >::operator=(), libMesh::PetscVector< T >::PetscVector(), libMesh::EigenSparseVector< T >::swap(), libMesh::NumericVector< T >::swap(), and libMesh::LaspackVector< T >::~LaspackVector().
Threads::spin_mutex libMesh::ReferenceCounter::_mutex static protected inherited
Mutual exclusion object to enable thread-safe reference counting.
Definition at line 128 of file reference_counter.h.
Threads::atomic< unsigned int > libMesh::ReferenceCounter::_n_objects static protected inherited
The number of objects. Print the reference count information when the number returns to 0.
Definition at line 123 of file reference_counter.h.
Referenced by libMesh::ReferenceCounter::n_objects(), libMesh::ReferenceCounter::ReferenceCounter(), and libMesh::ReferenceCounter::~ReferenceCounter().
template<typename T> ParallelType libMesh::NumericVector< T >::_type protected
Type of vector
Definition at line 718 of file numeric_vector.h.
Referenced by libMesh::DistributedVector< T >::DistributedVector(), libMesh::EigenSparseVector< T >::EigenSparseVector(), libMesh::EpetraVector< T >::EpetraVector(), libMesh::DistributedVector< T >::init(), libMesh::EigenSparseVector< T >::init(), libMesh::EpetraVector< T >::init(), libMesh::PetscVector< T >::init(), libMesh::LaspackVector< T >::LaspackVector(), libMesh::PetscVector< T >::operator=(), libMesh::PetscVector< T >::PetscVector(), libMesh::EigenSparseVector< T >::swap(), libMesh::NumericVector< T >::swap(), libMesh::NumericVector< Number >::type(), and libMesh::LaspackVector< T >::~LaspackVector().
The documentation for this class was generated from the following files:
diff_context.h
numeric_vector.h
numeric_vector.C