libMesh: libMesh::Parallel::Status Class Reference
SomeWebsiteLogo
libMesh::Parallel::Status Class Reference
#include <parallel.h>
Public Member Functions
Status ()
Status (const data_type &type)
Status (const status &status)
Status (const status &status, const data_type &type)
Status (const Status &status)
Status (const Status &status, const data_type &type)
status * get ()
status const * get () const
int source () const
int tag () const
data_type & datatype ()
const data_type & datatype () const
unsigned int size (const data_type &type) const
unsigned int size () const
Private Attributes
status _status
data_type _datatype
Detailed Description
Encapsulates the MPI_Status struct. Allows the source and size of the message to be determined.
Definition at line 415 of file parallel.h.
Constructor & Destructor Documentation
libMesh::Parallel::Status::Status () inline
Definition at line 701 of file parallel_implementation.h.
                        :
   _status(),
   _datatype()
 {}
libMesh::Parallel::Status::Status (const data_type & type) inline explicit
Definition at line 706 of file parallel_implementation.h.
                                              :
   _status(),
   _datatype(type)
 {}
libMesh::Parallel::Status::Status (const status & status) inline explicit
Definition at line 711 of file parallel_implementation.h.
                                           :
   _status(stat),
   _datatype()
 {}
libMesh::Parallel::Status::Status (const status & status, const data_type & type) inline
Definition at line 716 of file parallel_implementation.h.
                                                :
   _status(stat),
   _datatype(type)
 {}
libMesh::Parallel::Status::Status (const Status & status) inline
Definition at line 722 of file parallel_implementation.h.
                                           :
   _status(stat._status),
   _datatype(stat._datatype)
 {}
libMesh::Parallel::Status::Status (const Status & status, const data_type & type) inline
Definition at line 727 of file parallel_implementation.h.
                                                :
   _status(stat._status),
   _datatype(type)
 {}
Member Function Documentation
data_type& libMesh::Parallel::Status::datatype () inline
Definition at line 440 of file parallel.h.
Referenced by size().
 { return _datatype; }
const data_type& libMesh::Parallel::Status::datatype () const inline
Definition at line 442 of file parallel.h.
 { return _datatype; }
status* libMesh::Parallel::Status::get () inline
Definition at line 432 of file parallel.h.
Referenced by libMesh::Parallel::Communicator::packed_range_probe(), libMesh::Parallel::Communicator::receive(), and libMesh::Parallel::Request::wait().
 { return &_status; }
status const* libMesh::Parallel::Status::get () const inline
Definition at line 434 of file parallel.h.
 { return &_status; }
unsigned int libMesh::Parallel::Status::size (const data_type & type) const inline
Definition at line 753 of file parallel_implementation.h.
References _status, and size().
Referenced by libMesh::MeshCommunication::gather_neighboring_elements(), libMesh::Parallel::Communicator::nonblocking_receive_packed_range(), and libMesh::Parallel::Communicator::receive().
 {
   int msg_size;
   libmesh_call_mpi
     (MPI_Get_count (const_cast<MPI_Status*>(&_status), type,
                     &msg_size));
   libmesh_assert_greater_equal (msg_size, 0);
   return msg_size;
 }
unsigned int libMesh::Parallel::Status::size () const inline
Definition at line 771 of file parallel_implementation.h.
References datatype().
Referenced by size().
 { return this->size (this->datatype()); }
int libMesh::Parallel::Status::source () const inline
Definition at line 733 of file parallel_implementation.h.
References _status.
Referenced by libMesh::BoundaryInfo::build_node_list_from_side_list(), libMesh::Nemesis_IO::read(), libMesh::System::read_serialized_blocked_dof_objects(), libMesh::Parallel::Communicator::receive(), libMesh::Parallel::Communicator::receive_packed_range(), and libMesh::System::write_serialized_blocked_dof_objects().
 {
 #ifdef LIBMESH_HAVE_MPI
   return _status.MPI_SOURCE;
 #else
   return 0;
 #endif
 }
int libMesh::Parallel::Status::tag () const inline
Definition at line 742 of file parallel_implementation.h.
References _status.
Referenced by libMesh::Parallel::Communicator::receive(), and libMesh::Parallel::Communicator::receive_packed_range().
 {
 #ifdef LIBMESH_HAVE_MPI
   return _status.MPI_TAG;
 #else
   libmesh_not_implemented();
   return 0;
 #endif
 }
Member Data Documentation
data_type libMesh::Parallel::Status::_datatype private
Definition at line 451 of file parallel.h.
status libMesh::Parallel::Status::_status private
Definition at line 450 of file parallel.h.
Referenced by size(), source(), and tag().
The documentation for this class was generated from the following files:
parallel.h
parallel_implementation.h