libMesh: libMesh::EigenSparseVector< T > Class Template Reference
SomeWebsiteLogo
libMesh::EigenSparseVector< T > Class Template Reference
#include <eigen_sparse_matrix.h>
Public Types
typedef EigenSV DataType
Public Member Functions
EigenSparseVector (const Parallel::Communicator &comm_in, const ParallelType=AUTOMATIC)
EigenSparseVector (const Parallel::Communicator &comm_in, const numeric_index_type n, const ParallelType=AUTOMATIC)
EigenSparseVector (const Parallel::Communicator &comm_in, const numeric_index_type n, const numeric_index_type n_local, const ParallelType=AUTOMATIC)
EigenSparseVector (const Parallel::Communicator &comm_in, const numeric_index_type N, const numeric_index_type n_local, const std::vector< numeric_index_type > &ghost, const ParallelType=AUTOMATIC)
~EigenSparseVector ()
virtual void close () libmesh_override
virtual void clear () libmesh_override
virtual void zero () libmesh_override
virtual UniquePtr< NumericVector< T > > zero_clone () const libmesh_override
virtual UniquePtr< NumericVector< T > > clone () const libmesh_override
virtual void init (const numeric_index_type N, const numeric_index_type n_local, const bool fast=false, const ParallelType ptype=AUTOMATIC) libmesh_override
virtual void init (const numeric_index_type N, const bool fast=false, const ParallelType ptype=AUTOMATIC) libmesh_override
virtual void init (const numeric_index_type N, const numeric_index_type n_local, const std::vector< numeric_index_type > &ghost, const bool fast=false, const ParallelType=AUTOMATIC) libmesh_override
virtual void init (const NumericVector< T > &other, const bool fast=false) libmesh_override
virtual NumericVector< T > & operator= (const T s) libmesh_override
virtual NumericVector< T > & operator= (const NumericVector< T > &v) libmesh_override
EigenSparseVector< T > & operator= (const EigenSparseVector< T > &v)
virtual NumericVector< T > & operator= (const std::vector< T > &v) libmesh_override
virtual Real min () const libmesh_override
virtual Real max () const libmesh_override
virtual T sum () const libmesh_override
virtual Real l1_norm () const libmesh_override
virtual Real l2_norm () const libmesh_override
virtual Real linfty_norm () const libmesh_override
virtual numeric_index_type size () const libmesh_override
virtual numeric_index_type local_size () const libmesh_override
virtual numeric_index_type first_local_index () const libmesh_override
virtual numeric_index_type last_local_index () const libmesh_override
virtual T operator() (const numeric_index_type i) const libmesh_override
virtual NumericVector< T > & operator+= (const NumericVector< T > &v) libmesh_override
virtual NumericVector< T > & operator-= (const NumericVector< T > &v) libmesh_override
virtual NumericVector< T > & operator/= (NumericVector< T > &v_in) libmesh_override
virtual void reciprocal () libmesh_override
virtual void conjugate () libmesh_override
virtual void set (const numeric_index_type i, const T value) libmesh_override
virtual void add (const numeric_index_type i, const T value) libmesh_override
virtual void add (const T s) libmesh_override
virtual void add (const NumericVector< T > &v) libmesh_override
virtual void add (const T a, const NumericVector< T > &v) libmesh_override
virtual void add_vector (const NumericVector< T > &v, const SparseMatrix< T > &A) libmesh_override
virtual void add_vector_transpose (const NumericVector< T > &v, const SparseMatrix< T > &A) libmesh_override
virtual void scale (const T factor) libmesh_override
virtual void abs () libmesh_override
virtual T dot (const NumericVector< T > &v) const libmesh_override
virtual void localize (std::vector< T > &v_local) const libmesh_override
virtual void localize (NumericVector< T > &v_local) const libmesh_override
virtual void localize (NumericVector< T > &v_local, const std::vector< numeric_index_type > &send_list) const libmesh_override
virtual void localize (std::vector< T > &v_local, const std::vector< numeric_index_type > &indices) const libmesh_override
virtual void localize (const numeric_index_type first_local_idx, const numeric_index_type last_local_idx, const std::vector< numeric_index_type > &send_list) libmesh_override
virtual void localize_to_one (std::vector< T > &v_local, const processor_id_type proc_id=0) const libmesh_override
virtual void pointwise_mult (const NumericVector< T > &vec1, const NumericVector< T > &vec2) libmesh_override
virtual void swap (NumericVector< T > &v) libmesh_override
DataType & vec ()
const DataType & vec () const
virtual bool initialized () const
ParallelType type () const
ParallelType & type ()
virtual bool closed () const
virtual Real subset_l1_norm (const std::set< numeric_index_type > &indices) const
virtual Real subset_l2_norm (const std::set< numeric_index_type > &indices) const
virtual Real subset_linfty_norm (const std::set< numeric_index_type > &indices) const
virtual T el (const numeric_index_type i) const
virtual void get (const std::vector< numeric_index_type > &index, T *values) const
void get (const std::vector< numeric_index_type > &index, std::vector< T > &values) const
NumericVector< T > & operator*= (const T a)
NumericVector< T > & operator/= (const T a)
virtual void add_vector (const T *v, const std::vector< numeric_index_type > &dof_indices)
void add_vector (const std::vector< T > &v, const std::vector< numeric_index_type > &dof_indices)
virtual void add_vector (const NumericVector< T > &v, const std::vector< numeric_index_type > &dof_indices)
void add_vector (const DenseVector< T > &v, const std::vector< numeric_index_type > &dof_indices)
void add_vector (const NumericVector< T > &v, const ShellMatrix< T > &A)
virtual void insert (const T *v, const std::vector< numeric_index_type > &dof_indices)
void insert (const std::vector< T > &v, const std::vector< numeric_index_type > &dof_indices)
virtual void insert (const NumericVector< T > &v, const std::vector< numeric_index_type > &dof_indices)
void insert (const DenseVector< T > &v, const std::vector< numeric_index_type > &dof_indices)
void insert (const DenseSubVector< T > &v, const std::vector< numeric_index_type > &dof_indices)
virtual int compare (const NumericVector< T > &other_vector, const Real threshold=TOLERANCE) const
virtual int local_relative_compare (const NumericVector< T > &other_vector, const Real threshold=TOLERANCE) const
virtual int global_relative_compare (const NumericVector< T > &other_vector, const Real threshold=TOLERANCE) const
virtual void print (std::ostream &os=libMesh::out) const
template<>
void print (std::ostream &os) const
virtual void print_global (std::ostream &os=libMesh::out) const
template<>
void print_global (std::ostream &os) const
virtual void print_matlab (const std::string &="") const
virtual void create_subvector (NumericVector< T > &, const std::vector< numeric_index_type > &) const
const Parallel::Communicator & comm () const
processor_id_type n_processors () const
processor_id_type processor_id () const
Static Public Member Functions
static UniquePtr< NumericVector< T > > build (const Parallel::Communicator &comm, const SolverPackage solver_package=libMesh::default_solver_package())
static UniquePtr< NumericVector< T > > build (const SolverPackage solver_package=libMesh::default_solver_package())
static std::string get_info ()
static void print_info (std::ostream &out=libMesh::out)
static unsigned int n_objects ()
static void enable_print_counter_info ()
static void disable_print_counter_info ()
Protected Types
typedef std::map< std::string, std::pair< unsigned int, unsigned int > > Counts
Protected Member Functions
void increment_constructor_count (const std::string &name)
void increment_destructor_count (const std::string &name)
Protected Attributes
bool _is_closed
bool _is_initialized
ParallelType _type
const Parallel::Communicator & _communicator
Static Protected Attributes
static Counts _counts
static Threads::atomic< unsigned int > _n_objects
static Threads::spin_mutex _mutex
static bool _enable_print_counter = true
Private Attributes
DataType _vec
Friends
class EigenSparseMatrix< T >
class EigenSparseLinearSolver< T >
Detailed Description
template<typename T>
class libMesh::EigenSparseVector< T >
This class provides a nice interface to the Eigen C++-based data structures for serial vectors. All overridden virtual functions are documented in numeric_vector.h.
Author
Benjamin S. Kirk
Date
2002
Definition at line 42 of file eigen_sparse_matrix.h.
Member Typedef Documentation
typedef std::map<std::string, std::pair<unsigned int, unsigned int> > libMesh::ReferenceCounter::Counts protected inherited
Data structure to log the information. The log is identified by the class name.
Definition at line 119 of file reference_counter.h.
template<typename T> typedef EigenSV libMesh::EigenSparseVector< T >::DataType
Convenient typedefs
Definition at line 99 of file eigen_sparse_vector.h.
Constructor & Destructor Documentation
template<typename T > libMesh::EigenSparseVector< T >::EigenSparseVector (const Parallel::Communicator & comm_in, const ParallelType ptype = AUTOMATIC) inline explicit
Dummy-Constructor. Dimension=0
Definition at line 252 of file eigen_sparse_vector.h.
References libMesh::NumericVector< T >::_type.
   : NumericVector<T>(comm_in, ptype)
 {
   this->_type = ptype;
 }
template<typename T > libMesh::EigenSparseVector< T >::EigenSparseVector (const Parallel::Communicator & comm_in, const numeric_index_type n, const ParallelType ptype = AUTOMATIC) inline explicit
Constructor. Set dimension to n and initialize all elements with zero.
Definition at line 263 of file eigen_sparse_vector.h.
References libMesh::EigenSparseVector< T >::init().
   : NumericVector<T>(comm_in, ptype)
 {
   this->init(n, n, false, ptype);
 }
template<typename T > libMesh::EigenSparseVector< T >::EigenSparseVector (const Parallel::Communicator & comm_in, const numeric_index_type n, const numeric_index_type n_local, const ParallelType ptype = AUTOMATIC) inline
Constructor. Set local dimension to n_local, the global dimension to n, and initialize all elements with zero.
Definition at line 275 of file eigen_sparse_vector.h.
References libMesh::EigenSparseVector< T >::init().
   : NumericVector<T>(comm_in, ptype)
 {
   this->init(n, n_local, false, ptype);
 }
template<typename T > libMesh::EigenSparseVector< T >::EigenSparseVector (const Parallel::Communicator & comm_in, const numeric_index_type N, const numeric_index_type n_local, const std::vector< numeric_index_type > & ghost, const ParallelType ptype = AUTOMATIC) inline
Constructor. Set local dimension to n_local, the global dimension to n, but additionally reserve memory for the indices specified by the ghost argument.
Definition at line 288 of file eigen_sparse_vector.h.
References libMesh::EigenSparseVector< T >::init().
   : NumericVector<T>(comm_in, ptype)
 {
   this->init(N, n_local, ghost, false, ptype);
 }
template<typename T > libMesh::EigenSparseVector< T >::~EigenSparseVector () inline
Destructor, deallocates memory. Made virtual to allow for derived classes to behave properly.
Definition at line 302 of file eigen_sparse_vector.h.
References libMesh::EigenSparseVector< T >::clear().
 {
   this->clear ();
 }
Member Function Documentation
template<typename T > void libMesh::EigenSparseVector< T >::abs () virtual
Sets for each entry in the vector.
Implements libMesh::NumericVector< T >.
Definition at line 229 of file eigen_sparse_vector.C.
References std::abs(), libMesh::initialized(), and libMesh::libmesh_assert().
 {
   libmesh_assert (this->initialized());
   const numeric_index_type n = this->size();
   for (numeric_index_type i=0; i!=n; ++i)
     this->set(i,std::abs((*this)(i)));
 }
template<typename T > void libMesh::EigenSparseVector< T >::add (const numeric_index_type i, const T value) inline virtual
Adds value to each entry of the vector.
Implements libMesh::NumericVector< T >.
Definition at line 501 of file eigen_sparse_vector.h.
References libMesh::NumericVector< T >::_is_closed, libMesh::EigenSparseVector< T >::_vec, libMesh::NumericVector< T >::initialized(), libMesh::libmesh_assert(), and libMesh::EigenSparseVector< T >::size().
 {
   libmesh_assert (this->initialized());
   libmesh_assert_less (i, this->size());
   _vec[static_cast<eigen_idx_type>(i)] += value;
 #ifndef NDEBUG
   this->_is_closed = false;
 #endif
 }
template<typename T > void libMesh::EigenSparseVector< T >::add (const T s) virtual
Adds s to each entry of the vector,
Implements libMesh::NumericVector< T >.
Definition at line 150 of file eigen_sparse_vector.C.
 {
   _vec += EigenSV::Constant(this->size(), v);
 #ifndef NDEBUG
   this->_is_closed = false;
 #endif
 }
template<typename T > void libMesh::EigenSparseVector< T >::add (const NumericVector< T > & v) virtual
Adds v to this, . Equivalent to calling operator+=().
Implements libMesh::NumericVector< T >.
Definition at line 163 of file eigen_sparse_vector.C.
References libMesh::EigenSparseVector< T >::_vec, libMesh::initialized(), and libMesh::libmesh_assert().
 {
   libmesh_assert (this->initialized());
   const EigenSparseVector<T> & v = cast_ref<const EigenSparseVector<T> &>(v_in);
   _vec += v._vec;
 }
template<typename T > void libMesh::EigenSparseVector< T >::add (const T a, const NumericVector< T > & v) virtual
Vector addition with a scalar multiple, . Equivalent to calling operator+=().
Implements libMesh::NumericVector< T >.
Definition at line 175 of file eigen_sparse_vector.C.
References libMesh::EigenSparseVector< T >::_vec, libMesh::initialized(), and libMesh::libmesh_assert().
 {
   libmesh_assert (this->initialized());
   const EigenSparseVector<T> & v = cast_ref<const EigenSparseVector<T> &>(v_in);
   _vec += v._vec*a;
 }
template<typename T > void libMesh::EigenSparseVector< T >::add_vector (const NumericVector< T > & v, const SparseMatrix< T > & A) virtual
Computes , i.e. adds the product of a SparseMatrix A and a NumericVector v to this.
Implements libMesh::NumericVector< T >.
Definition at line 187 of file eigen_sparse_vector.C.
References libMesh::EigenSparseVector< T >::_vec, and libMesh::libmesh_assert().
 {
   // Make sure the data passed in are really in Eigen types
   const EigenSparseVector<T> * e_vec = cast_ptr<const EigenSparseVector<T> *>(&vec_in);
   const EigenSparseMatrix<T> * mat = cast_ptr<const EigenSparseMatrix<T> *>(&mat_in);
   libmesh_assert(e_vec);
   libmesh_assert(mat);
   _vec += mat->_mat*e_vec->_vec;
 }
template<typename T> void libMesh::NumericVector< T >::add_vector (const T * v, const std::vector< numeric_index_type > & dof_indices) virtual inherited
Computes , where v is a pointer and each dof_indices[i] specifies where to add value v[i]. This should be overridden in subclasses for efficiency.
Reimplemented in libMesh::PetscVector< T >, and libMesh::EpetraVector< T >.
Definition at line 383 of file numeric_vector.C.
Referenced by libMesh::NumericVector< T >::add_vector(), libMesh::LinearImplicitSystem::assembly(), libMesh::NumericVector< Number >::operator/=(), libMesh::NewmarkSystem::update_rhs(), and libMesh::SparseMatrix< T >::vector_mult_add().
 {
   int n = dof_indices.size();
   for (int i=0; i<n; i++)
     this->add (dof_indices[i], v[i]);
 }
template<typename T> void libMesh::NumericVector< T >::add_vector (const std::vector< T > & v, const std::vector< numeric_index_type > & dof_indices) inline inherited
Computes , where v is a std::vector and each dof_indices[i] specifies where to add value v[i].
Definition at line 837 of file numeric_vector.h.
References libMesh::NumericVector< T >::add_vector(), and libMesh::libmesh_assert().
 {
   libmesh_assert(v.size() == dof_indices.size());
   if (!v.empty())
     this->add_vector(&v[0], dof_indices);
 }
template<typename T> void libMesh::NumericVector< T >::add_vector (const NumericVector< T > & v, const std::vector< numeric_index_type > & dof_indices) virtual inherited
Computes , where v is a NumericVector and each dof_indices[i] specifies where to add value v(i).
Definition at line 394 of file numeric_vector.C.
References libMesh::NumericVector< T >::size().
 {
   int n = dof_indices.size();
   libmesh_assert_equal_to(v.size(), static_cast<unsigned>(n));
   for (int i=0; i<n; i++)
     this->add (dof_indices[i], v(i));
 }
template<typename T> void libMesh::NumericVector< T >::add_vector (const DenseVector< T > & v, const std::vector< numeric_index_type > & dof_indices) inline inherited
Computes , where v is a DenseVector and each dof_indices[i] specifies where to add value v(i).
Definition at line 849 of file numeric_vector.h.
References libMesh::NumericVector< T >::add_vector(), libMesh::DenseVector< T >::empty(), libMesh::libmesh_assert(), and libMesh::DenseVector< T >::size().
 {
   libmesh_assert(v.size() == dof_indices.size());
   if (!v.empty())
     this->add_vector(&v(0), dof_indices);
 }
template<typename T> void libMesh::NumericVector< T >::add_vector (const NumericVector< T > & v, const ShellMatrix< T > & A) inherited
Computes , i.e. adds the product of a ShellMatrix A and a NumericVector v to this.
Definition at line 406 of file numeric_vector.C.
References libMesh::ShellMatrix< T >::vector_mult_add().
 {
   a.vector_mult_add(*this,v);
 }
template<typename T > void libMesh::EigenSparseVector< T >::add_vector_transpose (const NumericVector< T > & v, const SparseMatrix< T > & A) virtual
Computes , i.e. adds the product of the transpose of a SparseMatrix A and a NumericVector v to this.
Implements libMesh::NumericVector< T >.
Definition at line 203 of file eigen_sparse_vector.C.
References libMesh::EigenSparseVector< T >::_vec, and libMesh::libmesh_assert().
 {
   // Make sure the data passed in are really in Eigen types
   const EigenSparseVector<T> * e_vec = cast_ptr<const EigenSparseVector<T> *>(&vec_in);
   const EigenSparseMatrix<T> * mat = cast_ptr<const EigenSparseMatrix<T> *>(&mat_in);
   libmesh_assert(e_vec);
   libmesh_assert(mat);
   _vec += mat->_mat.transpose()*e_vec->_vec;
 }
template<typename T > UniquePtr< NumericVector< T > > libMesh::NumericVector< T >::build (const Parallel::Communicator & comm, const SolverPackage solver_package = libMesh::default_solver_package()) static inherited
Builds a NumericVector on the processors in communicator comm using the linear solver package specified by solver_package
Definition at line 46 of file numeric_vector.C.
References libMesh::AUTOMATIC, libMesh::EIGEN_SOLVERS, libMesh::LASPACK_SOLVERS, libMesh::PETSC_SOLVERS, and libMesh::TRILINOS_SOLVERS.
Referenced by libMesh::ExactSolution::_compute_error(), libMesh::UniformRefinementEstimator::_estimate_error(), libMesh::System::add_vector(), libMesh::NumericVector< T >::build(), libMesh::EquationSystems::build_parallel_solution_vector(), libMesh::System::calculate_norm(), libMesh::AdjointRefinementEstimator::estimate_error(), libMesh::ExactErrorEstimator::estimate_error(), libMesh::CondensedEigenSystem::get_eigenpair(), libMesh::EquationSystems::get_solution(), and libMesh::System::project_vector().
 {
   // Build the appropriate vector
   switch (solver_package)
     {
 #ifdef LIBMESH_HAVE_LASPACK
     case LASPACK_SOLVERS:
       return UniquePtr<NumericVector<T> >(new LaspackVector<T>(comm, AUTOMATIC));
 #endif
 #ifdef LIBMESH_HAVE_PETSC
     case PETSC_SOLVERS:
       return UniquePtr<NumericVector<T> >(new PetscVector<T>(comm, AUTOMATIC));
 #endif
 #ifdef LIBMESH_TRILINOS_HAVE_EPETRA
     case TRILINOS_SOLVERS:
       return UniquePtr<NumericVector<T> >(new EpetraVector<T>(comm, AUTOMATIC));
 #endif
 #ifdef LIBMESH_HAVE_EIGEN
     case EIGEN_SOLVERS:
       return UniquePtr<NumericVector<T> >(new EigenSparseVector<T>(comm, AUTOMATIC));
 #endif
     default:
       return UniquePtr<NumericVector<T> >(new DistributedVector<T>(comm, AUTOMATIC));
     }
   libmesh_error_msg("We'll never get here!");
   return UniquePtr<NumericVector<T> >();
 }
template<typename T > UniquePtr< NumericVector< T > > libMesh::NumericVector< T >::build (const SolverPackage solver_package = libMesh::default_solver_package()) static inherited
Builds a NumericVector on the processors in communicator CommWorld using the linear solver package specified by solver_package.
Deprecated:
LIBMESH_DISABLE_COMMWORLD is now the default, use the build() method that takes a Parallel::Communicator instead.
Definition at line 84 of file numeric_vector.C.
References libMesh::NumericVector< T >::build(), and libMesh::CommWorld.
 {
   libmesh_deprecated();
   return NumericVector<T>::build(CommWorld, solver_package);
 }
template<typename T > void libMesh::EigenSparseVector< T >::clear () inline virtual
Restores the NumericVector<T> to a pristine state.
Reimplemented from libMesh::NumericVector< T >.
Definition at line 393 of file eigen_sparse_vector.h.
References libMesh::NumericVector< T >::_is_closed, libMesh::NumericVector< T >::_is_initialized, and libMesh::EigenSparseVector< T >::_vec.
Referenced by libMesh::EigenSparseVector< T >::init(), and libMesh::EigenSparseVector< T >::~EigenSparseVector().
 {
   _vec.resize(0);
   this->_is_initialized = false;
 #ifndef NDEBUG
   this->_is_closed = false;
 #endif
 }
template<typename T > UniquePtr< NumericVector< T > > libMesh::EigenSparseVector< T >::clone () const inline virtual
Returns
A copy of this vector wrapped in a smart pointer.
Note
This must be overridden in the derived classes.
Implements libMesh::NumericVector< T >.
Definition at line 429 of file eigen_sparse_vector.h.
References libMesh::ParallelObject::comm(), and libMesh::NumericVector< T >::init().
 {
   NumericVector<T> * cloned_vector = new EigenSparseVector<T>(this->comm());
   cloned_vector->init(*this, true);
   *cloned_vector = *this;
   return UniquePtr<NumericVector<T> >(cloned_vector);
 }
template<typename T > void libMesh::EigenSparseVector< T >::close () inline virtual
Calls the NumericVector's internal assembly routines, ensuring that the values are consistent across processors.
Implements libMesh::NumericVector< T >.
Definition at line 380 of file eigen_sparse_vector.h.
References libMesh::NumericVector< T >::_is_closed, libMesh::NumericVector< T >::initialized(), and libMesh::libmesh_assert().
 {
   libmesh_assert (this->initialized());
 #ifndef NDEBUG
   this->_is_closed = true;
 #endif
 }
template<typename T> virtual bool libMesh::NumericVector< T >::closed () const inline virtual inherited
Returns
true if the vector is closed and ready for computation, false otherwise.
Definition at line 151 of file numeric_vector.h.
Referenced by libMesh::DofMap::enforce_adjoint_constraints_exactly(), libMesh::DofMap::enforce_constraints_exactly(), libMesh::DofMap::max_constraint_error(), libMesh::EigenSparseVector< T >::operator=(), libMesh::LaspackVector< T >::operator=(), libMesh::PetscVector< T >::operator=(), libMesh::EigenSparseVector< T >::zero(), libMesh::LaspackVector< T >::zero(), libMesh::EpetraVector< T >::zero(), and libMesh::PetscVector< T >::zero().
 { return _is_closed; }
const Parallel::Communicator& libMesh::ParallelObject::comm () const inline inherited
Returns
A reference to the Parallel::Communicator object used by this mesh.
Definition at line 87 of file parallel_object.h.
References libMesh::ParallelObject::_communicator.
Referenced by libMesh::__libmesh_petsc_diff_solver_monitor(), libMesh::__libmesh_petsc_diff_solver_residual(), libMesh::__libmesh_petsc_snes_jacobian(), libMesh::__libmesh_petsc_snes_postcheck(), libMesh::__libmesh_petsc_snes_residual(), libMesh::__libmesh_tao_equality_constraints(), libMesh::__libmesh_tao_equality_constraints_jacobian(), libMesh::__libmesh_tao_gradient(), libMesh::__libmesh_tao_hessian(), libMesh::__libmesh_tao_inequality_constraints(), libMesh::__libmesh_tao_inequality_constraints_jacobian(), libMesh::__libmesh_tao_objective(), libMesh::MeshRefinement::_coarsen_elements(), libMesh::ExactSolution::_compute_error(), libMesh::ParmetisPartitioner::_do_repartition(), libMesh::UniformRefinementEstimator::_estimate_error(), libMesh::BoundaryInfo::_find_id_maps(), libMesh::PetscLinearSolver< T >::_petsc_shell_matrix_get_diagonal(), libMesh::SlepcEigenSolver< T >::_petsc_shell_matrix_get_diagonal(), libMesh::PetscLinearSolver< T >::_petsc_shell_matrix_mult(), libMesh::SlepcEigenSolver< T >::_petsc_shell_matrix_mult(), libMesh::PetscLinearSolver< T >::_petsc_shell_matrix_mult_add(), libMesh::EquationSystems::_read_impl(), libMesh::MeshRefinement::_refine_elements(), libMesh::MeshRefinement::_smooth_flags(), libMesh::ImplicitSystem::add_matrix(), libMesh::System::add_vector(), libMesh::EigenSparseLinearSolver< T >::adjoint_solve(), libMesh::UnstructuredMesh::all_second_order(), libMesh::MeshTools::Modification::all_tri(), libMesh::LaplaceMeshSmoother::allgather_graph(), libMesh::FEMSystem::assemble_qoi(), libMesh::MeshCommunication::assign_global_indices(), libMesh::ParmetisPartitioner::assign_partitioning(), libMesh::DofMap::attach_matrix(), libMesh::Parallel::BinSorter< KeyType, IdxType >::binsort(), libMesh::Parallel::Sort< KeyType, IdxType >::binsort(), libMesh::MeshCommunication::broadcast(), libMesh::SparseMatrix< T >::build(), libMesh::MeshTools::Generation::build_extrusion(), libMesh::Parallel::Histogram< KeyType, IdxType >::build_histogram(), libMesh::PetscNonlinearSolver< T >::build_mat_null_space(), libMesh::BoundaryInfo::build_node_list_from_side_list(), libMesh::EquationSystems::build_parallel_solution_vector(), libMesh::MeshBase::cache_elem_dims(), libMesh::System::calculate_norm(), libMesh::DofMap::check_dirichlet_bcid_consistency(), libMesh::DistributedVector< T >::clone(), libMesh::EigenSparseVector< T >::clone(), libMesh::LaspackVector< T >::clone(), libMesh::EpetraVector< T >::clone(), libMesh::PetscVector< T >::clone(), libMesh::EpetraVector< T >::close(), libMesh::Parallel::Sort< KeyType, IdxType >::communicate_bins(), libMesh::Nemesis_IO_Helper::compute_num_global_elem_blocks(), libMesh::Nemesis_IO_Helper::compute_num_global_nodesets(), libMesh::Nemesis_IO_Helper::compute_num_global_sidesets(), libMesh::Problem_Interface::computeF(), libMesh::Problem_Interface::computeJacobian(), libMesh::Problem_Interface::computePreconditioner(), libMesh::MeshTools::correct_node_proc_ids(), libMesh::MeshTools::create_bounding_box(), libMesh::MeshTools::create_nodal_bounding_box(), libMesh::MeshRefinement::create_parent_error_vector(), libMesh::MeshTools::create_processor_bounding_box(), libMesh::MeshTools::create_subdomain_bounding_box(), libMesh::MeshCommunication::delete_remote_elements(), libMesh::DofMap::distribute_dofs(), DMlibMeshFunction(), DMlibMeshJacobian(), DMlibMeshSetSystem_libMesh(), DMVariableBounds_libMesh(), libMesh::MeshRefinement::eliminate_unrefined_patches(), libMesh::EpetraVector< T >::EpetraVector(), libMesh::WeightedPatchRecoveryErrorEstimator::estimate_error(), libMesh::PatchRecoveryErrorEstimator::estimate_error(), libMesh::JumpErrorEstimator::estimate_error(), libMesh::AdjointRefinementEstimator::estimate_error(), libMesh::ExactErrorEstimator::estimate_error(), libMesh::MeshRefinement::flag_elements_by_elem_fraction(), libMesh::MeshRefinement::flag_elements_by_error_fraction(), libMesh::MeshRefinement::flag_elements_by_nelem_target(), libMesh::MeshCommunication::gather(), libMesh::MeshCommunication::gather_neighboring_elements(), libMesh::CondensedEigenSystem::get_eigenpair(), libMesh::DofMap::get_info(), libMesh::ImplicitSystem::get_linear_solver(), libMesh::EquationSystems::get_solution(), libMesh::LocationMap< T >::init(), libMesh::PetscDiffSolver::init(), libMesh::TimeSolver::init(), libMesh::TopologyMap::init(), libMesh::TaoOptimizationSolver< T >::init(), libMesh::PetscNonlinearSolver< T >::init(), libMesh::DistributedVector< T >::init(), libMesh::EpetraVector< T >::init(), libMesh::PetscVector< T >::init(), libMesh::SystemSubsetBySubdomain::init(), libMesh::EigenSystem::init_data(), libMesh::EigenSystem::init_matrices(), libMesh::ParmetisPartitioner::initialize(), libMesh::OptimizationSystem::initialize_equality_constraints_storage(), libMesh::OptimizationSystem::initialize_inequality_constraints_storage(), libMesh::MeshTools::libmesh_assert_parallel_consistent_procids< Elem >(), libMesh::MeshTools::libmesh_assert_parallel_consistent_procids< Node >(), libMesh::MeshTools::libmesh_assert_topology_consistent_procids< Node >(), libMesh::MeshTools::libmesh_assert_valid_boundary_ids(), libMesh::MeshTools::libmesh_assert_valid_dof_ids(), libMesh::MeshTools::libmesh_assert_valid_neighbors(), libMesh::DistributedMesh::libmesh_assert_valid_parallel_flags(), libMesh::DistributedMesh::libmesh_assert_valid_parallel_object_ids(), libMesh::DistributedMesh::libmesh_assert_valid_parallel_p_levels(), libMesh::MeshTools::libmesh_assert_valid_refinement_flags(), libMesh::MeshTools::libmesh_assert_valid_unique_ids(), libMesh::MeshRefinement::limit_level_mismatch_at_edge(), libMesh::MeshRefinement::limit_level_mismatch_at_node(), libMesh::MeshRefinement::limit_overrefined_boundary(), libMesh::MeshRefinement::limit_underrefined_boundary(), libMesh::MeshRefinement::make_coarsening_compatible(), libMesh::MeshCommunication::make_elems_parallel_consistent(), libMesh::MeshRefinement::make_flags_parallel_consistent(), libMesh::MeshCommunication::make_new_node_proc_ids_parallel_consistent(), libMesh::MeshCommunication::make_new_nodes_parallel_consistent(), libMesh::MeshCommunication::make_node_ids_parallel_consistent(), libMesh::MeshCommunication::make_node_proc_ids_parallel_consistent(), libMesh::MeshCommunication::make_node_unique_ids_parallel_consistent(), libMesh::MeshCommunication::make_nodes_parallel_consistent(), libMesh::MeshCommunication::make_p_levels_parallel_consistent(), libMesh::MeshRefinement::make_refinement_compatible(), libMesh::DistributedVector< T >::max(), libMesh::FEMSystem::mesh_position_set(), libMesh::MeshSerializer::MeshSerializer(), libMesh::DistributedVector< T >::min(), libMesh::DistributedMesh::n_active_elem(), libMesh::MeshTools::n_active_levels(), libMesh::BoundaryInfo::n_boundary_conds(), libMesh::BoundaryInfo::n_edge_conds(), libMesh::CondensedEigenSystem::n_global_non_condensed_dofs(), libMesh::MeshTools::n_levels(), libMesh::BoundaryInfo::n_nodeset_conds(), libMesh::MeshTools::n_p_levels(), libMesh::BoundaryInfo::n_shellface_conds(), libMesh::DistributedMesh::parallel_max_elem_id(), libMesh::DistributedMesh::parallel_max_node_id(), libMesh::ReplicatedMesh::parallel_max_unique_id(), libMesh::DistributedMesh::parallel_max_unique_id(), libMesh::DistributedMesh::parallel_n_elem(), libMesh::DistributedMesh::parallel_n_nodes(), libMesh::SparsityPattern::Build::parallel_sync(), libMesh::MeshTools::paranoid_n_levels(), libMesh::Partitioner::partition(), libMesh::MetisPartitioner::partition_range(), libMesh::Partitioner::partition_unpartitioned_elements(), libMesh::petsc_auto_fieldsplit(), libMesh::System::point_gradient(), libMesh::System::point_hessian(), libMesh::System::point_value(), libMesh::MeshBase::prepare_for_use(), libMesh::SparseMatrix< T >::print(), libMesh::Nemesis_IO::read(), libMesh::CheckpointIO::read(), libMesh::XdrIO::read(), libMesh::XdrIO::read_serialized_bc_names(), libMesh::XdrIO::read_serialized_bcs_helper(), libMesh::XdrIO::read_serialized_connectivity(), libMesh::XdrIO::read_serialized_nodes(), libMesh::XdrIO::read_serialized_nodesets(), libMesh::XdrIO::read_serialized_subdomain_names(), libMesh::MeshBase::recalculate_n_partitions(), libMesh::MeshCommunication::redistribute(), libMesh::DistributedMesh::renumber_dof_objects(), libMesh::MeshCommunication::send_coarse_ghosts(), libMesh::Partitioner::set_node_processor_ids(), libMesh::DofMap::set_nonlocal_dof_objects(), libMesh::Partitioner::set_parent_processor_ids(), libMesh::LaplaceMeshSmoother::smooth(), libMesh::Parallel::Sort< KeyType, IdxType >::sort(), libMesh::MeshBase::subdomain_ids(), libMesh::BoundaryInfo::sync(), libMesh::Parallel::sync_element_data_by_parent_id(), libMesh::Parallel::sync_node_data_by_element_id(), libMesh::MeshRefinement::test_level_one(), libMesh::MeshRefinement::test_unflagged(), libMesh::MeshTools::total_weight(), libMesh::MeshRefinement::uniformly_coarsen(), libMesh::NameBasedIO::write(), libMesh::XdrIO::write(), libMesh::XdrIO::write_serialized_bcs_helper(), libMesh::XdrIO::write_serialized_connectivity(), libMesh::XdrIO::write_serialized_nodes(), libMesh::XdrIO::write_serialized_nodesets(), libMesh::DistributedVector< T >::zero_clone(), libMesh::LaspackVector< T >::zero_clone(), libMesh::EigenSparseVector< T >::zero_clone(), libMesh::EpetraVector< T >::zero_clone(), and libMesh::PetscVector< T >::zero_clone().
   { return _communicator; }
template<typename T> int libMesh::NumericVector< T >::compare (const NumericVector< T > & other_vector, const Real threshold = TOLERANCE) const virtual inherited
Returns
-1 when this is equivalent to other_vector (up to the given threshold), or the first index where abs(a[i]-b[i]) exceeds the threshold.
Definition at line 116 of file numeric_vector.C.
References std::abs(), libMesh::NumericVector< T >::first_local_index(), libMesh::NumericVector< T >::initialized(), libMesh::initialized(), libMesh::NumericVector< T >::last_local_index(), libMesh::libmesh_assert(), and std::max().
Referenced by libMesh::NumericVector< Number >::operator/=().
 {
   libmesh_assert (this->initialized());
   libmesh_assert (other_vector.initialized());
   libmesh_assert_equal_to (this->first_local_index(), other_vector.first_local_index());
   libmesh_assert_equal_to (this->last_local_index(), other_vector.last_local_index());
   int first_different_i = std::numeric_limits<int>::max();
   numeric_index_type i = first_local_index();
   do
     {
       if (std::abs((*this)(i) - other_vector(i)) > threshold)
         first_different_i = i;
       else
         i++;
     }
   while (first_different_i==std::numeric_limits<int>::max()
          && i<last_local_index());
   // Find the correct first differing index in parallel
   this->comm().min(first_different_i);
   if (first_different_i == std::numeric_limits<int>::max())
     return -1;
   return first_different_i;
 }
template<typename T > void libMesh::EigenSparseVector< T >::conjugate () virtual
Negates the imaginary component of each entry in the vector.
Implements libMesh::NumericVector< T >.
Definition at line 142 of file eigen_sparse_vector.C.
 {
   _vec = _vec.conjugate();
 }
template<typename T> virtual void libMesh::NumericVector< T >::create_subvector (NumericVector< T > & , const std::vector< numeric_index_type > &) const inline virtual inherited
Fills in subvector from this vector using the indices in rows. Similar to the create_submatrix() routine for the SparseMatrix class, it is currently only implemented for PetscVectors.
Reimplemented in libMesh::PetscVector< T >, and libMesh::EpetraVector< T >.
Definition at line 685 of file numeric_vector.h.
   {
     libmesh_not_implemented();
   }
void libMesh::ReferenceCounter::disable_print_counter_info () static inherited
Definition at line 107 of file reference_counter.C.
References libMesh::ReferenceCounter::_enable_print_counter.
Referenced by libMesh::LibMeshInit::LibMeshInit(), and libMesh::ReferenceCounter::n_objects().
 {
   _enable_print_counter = false;
   return;
 }
template<typename T > T libMesh::EigenSparseVector< T >::dot (const NumericVector< T > & v) const virtual
Returns
, the dot product of (*this) with the vector v.
Uses the complex-conjugate of v in the complex-valued case.
Implements libMesh::NumericVector< T >.
Definition at line 242 of file eigen_sparse_vector.C.
References libMesh::EigenSparseVector< T >::_vec, libMesh::initialized(), and libMesh::libmesh_assert().
 {
   libmesh_assert (this->initialized());
   // Make sure the NumericVector passed in is really a EigenSparseVector
   const EigenSparseVector<T> * v = cast_ptr<const EigenSparseVector<T> *>(&v_in);
   libmesh_assert(v);
   return _vec.dot(v->_vec);
 }
template<typename T> virtual T libMesh::NumericVector< T >::el (const numeric_index_type i) const inline virtual inherited
Returns
(*this)(i).
Definition at line 339 of file numeric_vector.h.
 { return (*this)(i); }
void libMesh::ReferenceCounter::enable_print_counter_info () static inherited
Methods to enable/disable the reference counter output from print_info()
Definition at line 101 of file reference_counter.C.
References libMesh::ReferenceCounter::_enable_print_counter.
Referenced by libMesh::ReferenceCounter::n_objects().
 {
   _enable_print_counter = true;
   return;
 }
template<typename T > numeric_index_type libMesh::EigenSparseVector< T >::first_local_index () const inline virtual
Returns
The index of the first vector element actually stored on this processor.
Note
The minimum for this index is 0.
Implements libMesh::NumericVector< T >.
Definition at line 463 of file eigen_sparse_vector.h.
References libMesh::NumericVector< T >::initialized(), and libMesh::libmesh_assert().
Referenced by libMesh::EigenSparseVector< T >::operator()().
 {
   libmesh_assert (this->initialized());
   return 0;
 }
template<typename T> void libMesh::NumericVector< T >::get (const std::vector< numeric_index_type > & index, T * values) const inline virtual inherited
Access multiple components at once. values will not be reallocated; it should already have enough space. The default implementation calls operator() for each index, but some implementations may supply faster methods here.
Reimplemented in libMesh::PetscVector< T >.
Definition at line 808 of file numeric_vector.h.
Referenced by libMesh::DofMap::enforce_adjoint_constraints_exactly(), libMesh::DofMap::enforce_constraints_exactly(), libMesh::FEMContext::pre_fe_reinit(), and libMesh::System::project_vector().
 {
   const std::size_t num = index.size();
   for (std::size_t i=0; i<num; i++)
     {
       values[i] = (*this)(index[i]);
     }
 }
template<typename T> void libMesh::NumericVector< T >::get (const std::vector< numeric_index_type > & index, std::vector< T > & values) const inline inherited
Access multiple components at once. values will be resized, if necessary, and filled. The default implementation calls operator() for each index, but some implementations may supply faster methods here.
Definition at line 822 of file numeric_vector.h.
 {
   const std::size_t num = index.size();
   values.resize(num);
   if (!num)
     return;
   this->get(index, &values[0]);
 }
std::string libMesh::ReferenceCounter::get_info () static inherited
Gets a string containing the reference information.
Definition at line 47 of file reference_counter.C.
References libMesh::ReferenceCounter::_counts, and libMesh::Quality::name().
Referenced by libMesh::ReferenceCounter::print_info().
 {
 #if defined(LIBMESH_ENABLE_REFERENCE_COUNTING) && defined(DEBUG)
   std::ostringstream oss;
   oss << '\n'
       << " ---------------------------------------------------------------------------- \n"
       << "| Reference count information                                                |\n"
       << " ---------------------------------------------------------------------------- \n";
   for (Counts::iterator it = _counts.begin();
        it != _counts.end(); ++it)
     {
       const std::string name(it->first);
       const unsigned int creations    = it->second.first;
       const unsigned int destructions = it->second.second;
       oss << "| " << name << " reference count information:\n"
           << "|  Creations:    " << creations    << '\n'
           << "|  Destructions: " << destructions << '\n';
     }
   oss << " ---------------------------------------------------------------------------- \n";
   return oss.str();
 #else
   return "";
 #endif
 }
template<typename T> int libMesh::NumericVector< T >::global_relative_compare (const NumericVector< T > & other_vector, const Real threshold = TOLERANCE) const virtual inherited
Returns
-1 when this is equivalent to other_vector (up to the given global relative threshold), or the first index where abs(a[i]-b[i])/max_j(a[j],b[j]) exceeds the threshold.
Definition at line 181 of file numeric_vector.C.
References std::abs(), libMesh::NumericVector< T >::first_local_index(), libMesh::NumericVector< T >::initialized(), libMesh::initialized(), libMesh::NumericVector< T >::last_local_index(), libMesh::libmesh_assert(), libMesh::NumericVector< T >::linfty_norm(), std::max(), and libMesh::Real.
Referenced by libMesh::NumericVector< Number >::operator/=().
 {
   libmesh_assert (this->initialized());
   libmesh_assert (other_vector.initialized());
   libmesh_assert_equal_to (this->first_local_index(), other_vector.first_local_index());
   libmesh_assert_equal_to (this->last_local_index(), other_vector.last_local_index());
   int first_different_i = std::numeric_limits<int>::max();
   numeric_index_type i = first_local_index();
   const Real my_norm = this->linfty_norm();
   const Real other_norm = other_vector.linfty_norm();
   const Real abs_threshold = std::max(my_norm, other_norm) * threshold;
   do
     {
       if (std::abs((*this)(i) - other_vector(i) ) > abs_threshold)
         first_different_i = i;
       else
         i++;
     }
   while (first_different_i==std::numeric_limits<int>::max()
          && i<last_local_index());
   // Find the correct first differing index in parallel
   this->comm().min(first_different_i);
   if (first_different_i == std::numeric_limits<int>::max())
     return -1;
   return first_different_i;
 }
void libMesh::ReferenceCounter::increment_constructor_count (const std::string & name) inline protected inherited
Increments the construction counter. Should be called in the constructor of any derived class that will be reference counted.
Definition at line 185 of file reference_counter.h.
References libMesh::ReferenceCounter::_counts, libMesh::Quality::name(), and libMesh::Threads::spin_mtx.
Referenced by libMesh::ReferenceCounter::n_objects(), and libMesh::ReferenceCountedObject< RBParametrized >::ReferenceCountedObject().
 {
   Threads::spin_mutex::scoped_lock lock(Threads::spin_mtx);
   std::pair<unsigned int, unsigned int> & p = _counts[name];
   p.first++;
 }
void libMesh::ReferenceCounter::increment_destructor_count (const std::string & name) inline protected inherited
Increments the destruction counter. Should be called in the destructor of any derived class that will be reference counted.
Definition at line 198 of file reference_counter.h.
References libMesh::ReferenceCounter::_counts, libMesh::Quality::name(), and libMesh::Threads::spin_mtx.
Referenced by libMesh::ReferenceCounter::n_objects(), and libMesh::ReferenceCountedObject< RBParametrized >::~ReferenceCountedObject().
 {
   Threads::spin_mutex::scoped_lock lock(Threads::spin_mtx);
   std::pair<unsigned int, unsigned int> & p = _counts[name];
   p.second++;
 }
template<typename T > void libMesh::EigenSparseVector< T >::init (const numeric_index_type , const numeric_index_type , const bool = false, const ParallelType = AUTOMATIC) inline virtual
Change the dimension of the vector to N. The reserved memory for this vector remains unchanged if possible. If N==0, all memory is freed. Therefore, if you want to resize the vector and release the memory not needed, you have to first call init(0) and then init(N). This behaviour is analogous to that of the STL containers.
On fast==false, the vector is filled by zeros.
Implements libMesh::NumericVector< T >.
Definition at line 311 of file eigen_sparse_vector.h.
References libMesh::NumericVector< T >::_is_closed, libMesh::NumericVector< T >::_is_initialized, libMesh::NumericVector< T >::_type, libMesh::EigenSparseVector< T >::_vec, libMesh::EigenSparseVector< T >::clear(), libMesh::NumericVector< T >::initialized(), libMesh::SERIAL, and libMesh::EigenSparseVector< T >::zero().
Referenced by libMesh::EigenSparseVector< T >::EigenSparseVector(), and libMesh::EigenSparseVector< T >::init().
 {
   // Eigen vectors only for serial cases,
   // but can provide a "parallel" vector on one processor.
   if (n != n_local)
     libmesh_error_msg("Error: EigenSparseVectors can only be used in serial!");
   this->_type = SERIAL;
   // Clear initialized vectors
   if (this->initialized())
     this->clear();
   _vec.resize(n);
   this->_is_initialized = true;
 #ifndef NDEBUG
   this->_is_closed = true;
 #endif
   // Optionally zero out all components
   if (fast == false)
     this->zero ();
   return;
 }
template<typename T > void libMesh::EigenSparseVector< T >::init (const numeric_index_type , const bool = false, const ParallelType = AUTOMATIC) inline virtual
Call init() with n_local = N.
Implements libMesh::NumericVector< T >.
Definition at line 345 of file eigen_sparse_vector.h.
References libMesh::EigenSparseVector< T >::init(), libMesh::libmesh_assert(), and libMesh::libmesh_dbg_var().
 {
   this->init(n,n,fast,ptype);
 }
template<typename T> virtual void libMesh::EigenSparseVector< T >::init (const numeric_index_type , const numeric_index_type , const std::vector< numeric_index_type > & , const bool = false, const ParallelType = AUTOMATIC) virtual
Create a vector that holds tha local indices plus those specified in the ghost argument.
Implements libMesh::NumericVector< T >.
template<class T > void libMesh::EigenSparseVector< T >::init (const NumericVector< T > & other, const bool fast = false) virtual
Creates a vector that has the same dimension and storage type as other, including ghost dofs.
Implements libMesh::NumericVector< T >.
Definition at line 370 of file eigen_sparse_vector.h.
References libMesh::EigenSparseVector< T >::init(), libMesh::NumericVector< T >::local_size(), libMesh::NumericVector< T >::size(), and libMesh::NumericVector< T >::type().
 {
   this->init(other.size(),other.local_size(),fast,other.type());
 }
template<typename T> virtual bool libMesh::NumericVector< T >::initialized () const inline virtual inherited
Returns
true if the vector has been initialized, false otherwise.
Definition at line 135 of file numeric_vector.h.
Referenced by libMesh::DistributedVector< T >::add(), libMesh::EigenSparseVector< T >::add(), libMesh::LaspackVector< T >::add(), libMesh::ImplicitSystem::assemble(), libMesh::LaspackVector< T >::clear(), libMesh::EpetraVector< T >::clear(), libMesh::PetscVector< T >::clear(), libMesh::DistributedVector< T >::close(), libMesh::EigenSparseVector< T >::close(), libMesh::LaspackVector< T >::close(), libMesh::EpetraVector< T >::close(), libMesh::NumericVector< T >::compare(), libMesh::PetscVector< T >::create_subvector(), libMesh::DistributedVector< T >::first_local_index(), libMesh::LaspackVector< T >::first_local_index(), libMesh::EigenSparseVector< T >::first_local_index(), libMesh::EpetraVector< T >::first_local_index(), libMesh::PetscVector< T >::first_local_index(), libMesh::NumericVector< T >::global_relative_compare(), libMesh::DistributedVector< T >::init(), libMesh::EigenSparseVector< T >::init(), libMesh::PetscVector< T >::init(), libMesh::DistributedVector< T >::last_local_index(), libMesh::EigenSparseVector< T >::last_local_index(), libMesh::LaspackVector< T >::last_local_index(), libMesh::EpetraVector< T >::last_local_index(), libMesh::PetscVector< T >::last_local_index(), libMesh::NumericVector< T >::local_relative_compare(), libMesh::DistributedVector< T >::local_size(), libMesh::LaspackVector< T >::local_size(), libMesh::EigenSparseVector< T >::local_size(), libMesh::EpetraVector< T >::local_size(), libMesh::PetscVector< T >::local_size(), libMesh::PetscVector< T >::map_global_to_local_index(), libMesh::DistributedVector< T >::max(), libMesh::EpetraVector< T >::max(), libMesh::DistributedVector< T >::min(), libMesh::EpetraVector< T >::min(), libMesh::DistributedVector< T >::operator()(), libMesh::EigenSparseVector< T >::operator()(), libMesh::LaspackVector< T >::operator()(), libMesh::EpetraVector< T >::operator()(), libMesh::NumericVector< T >::print(), libMesh::NumericVector< T >::print_global(), libMesh::DistributedVector< T >::set(), libMesh::LaspackVector< T >::set(), libMesh::EigenSparseVector< T >::set(), libMesh::DistributedVector< T >::size(), libMesh::LaspackVector< T >::size(), libMesh::EigenSparseVector< T >::size(), libMesh::EpetraVector< T >::size(), libMesh::PetscVector< T >::size(), libMesh::DistributedVector< T >::zero(), libMesh::LaspackVector< T >::zero(), libMesh::EigenSparseVector< T >::zero(), libMesh::EpetraVector< T >::zero(), and libMesh::LaspackVector< T >::~LaspackVector().
 { return _is_initialized; }
template<typename T> void libMesh::NumericVector< T >::insert (const T * v, const std::vector< numeric_index_type > & dof_indices) virtual inherited
Inserts the entries of v in *this at the locations specified by v.
Reimplemented in libMesh::PetscVector< T >, and libMesh::EpetraVector< T >.
Definition at line 94 of file numeric_vector.C.
Referenced by libMesh::NumericVector< T >::insert(), and libMesh::NumericVector< Number >::operator/=().
 {
   for (numeric_index_type i=0; i<dof_indices.size(); i++)
     this->set (dof_indices[i], v[i]);
 }
template<typename T> void libMesh::NumericVector< T >::insert (const std::vector< T > & v, const std::vector< numeric_index_type > & dof_indices) inline inherited
Inserts the entries of v in *this at the locations specified by v.
Definition at line 861 of file numeric_vector.h.
References libMesh::NumericVector< T >::insert(), and libMesh::libmesh_assert().
 {
   libmesh_assert(v.size() == dof_indices.size());
   if (!v.empty())
     this->insert(&v[0], dof_indices);
 }
template<typename T> void libMesh::NumericVector< T >::insert (const NumericVector< T > & v, const std::vector< numeric_index_type > & dof_indices) virtual inherited
Inserts the entries of v in *this at the locations specified by v.
Definition at line 104 of file numeric_vector.C.
References libMesh::NumericVector< T >::size().
 {
   libmesh_assert_equal_to (V.size(), dof_indices.size());
   for (numeric_index_type i=0; i<dof_indices.size(); i++)
     this->set (dof_indices[i], V(i));
 }
template<typename T> void libMesh::NumericVector< T >::insert (const DenseVector< T > & v, const std::vector< numeric_index_type > & dof_indices) inline inherited
Inserts the entries of v in *this at the locations specified by v.
Definition at line 873 of file numeric_vector.h.
References libMesh::DenseVector< T >::empty(), libMesh::NumericVector< T >::insert(), libMesh::libmesh_assert(), and libMesh::DenseVector< T >::size().
 {
   libmesh_assert(v.size() == dof_indices.size());
   if (!v.empty())
     this->insert(&v(0), dof_indices);
 }
template<typename T> void libMesh::NumericVector< T >::insert (const DenseSubVector< T > & v, const std::vector< numeric_index_type > & dof_indices) inline inherited
Inserts the entries of v in *this at the locations specified by v.
Definition at line 885 of file numeric_vector.h.
References libMesh::DenseSubVector< T >::empty(), libMesh::NumericVector< T >::insert(), libMesh::libmesh_assert(), and libMesh::DenseSubVector< T >::size().
 {
   libmesh_assert(v.size() == dof_indices.size());
   if (!v.empty())
     this->insert(&v(0), dof_indices);
 }
template<typename T > Real libMesh::EigenSparseVector< T >::l1_norm () const virtual
Returns
The -norm of the vector, i.e. the sum of the absolute values of the entries.
Implements libMesh::NumericVector< T >.
Definition at line 48 of file eigen_sparse_vector.C.
References libMesh::closed(), libMesh::initialized(), and libMesh::libmesh_assert().
 {
   libmesh_assert (this->closed());
   libmesh_assert (this->initialized());
   return _vec.lpNorm<1>();
 }
template<typename T > Real libMesh::EigenSparseVector< T >::l2_norm () const virtual
Returns
The -norm of the vector, i.e. the square root of the sum of the squares of the entries.
Implements libMesh::NumericVector< T >.
Definition at line 59 of file eigen_sparse_vector.C.
References libMesh::closed(), libMesh::initialized(), and libMesh::libmesh_assert().
 {
   libmesh_assert (this->closed());
   libmesh_assert (this->initialized());
   return _vec.lpNorm<2>();
 }
template<typename T > numeric_index_type libMesh::EigenSparseVector< T >::last_local_index () const inline virtual
Returns
The index+1 of the last vector element actually stored on this processor.
Note
The maximum for this index is size().
Implements libMesh::NumericVector< T >.
Definition at line 474 of file eigen_sparse_vector.h.
References libMesh::NumericVector< T >::initialized(), libMesh::libmesh_assert(), and libMesh::EigenSparseVector< T >::size().
Referenced by libMesh::EigenSparseVector< T >::operator()().
 {
   libmesh_assert (this->initialized());
   return this->size();
 }
template<typename T > Real libMesh::EigenSparseVector< T >::linfty_norm () const virtual
Returns
The -norm of the vector, i.e. the maximum absolute value of the entries of the vector.
Implements libMesh::NumericVector< T >.
Definition at line 70 of file eigen_sparse_vector.C.
References libMesh::closed(), libMesh::initialized(), and libMesh::libmesh_assert().
 {
   libmesh_assert (this->closed());
   libmesh_assert (this->initialized());
   return _vec.lpNorm<Eigen::Infinity>();
 }
template<typename T> int libMesh::NumericVector< T >::local_relative_compare (const NumericVector< T > & other_vector, const Real threshold = TOLERANCE) const virtual inherited
Returns
-1 when this is equivalent to other_vector, (up to the given local relative threshold), or the first index where abs(a[i]-b[i])/max(a[i],b[i]) exceeds the threshold.
Definition at line 148 of file numeric_vector.C.
References std::abs(), libMesh::NumericVector< T >::first_local_index(), libMesh::NumericVector< T >::initialized(), libMesh::initialized(), libMesh::NumericVector< T >::last_local_index(), libMesh::libmesh_assert(), and std::max().
Referenced by libMesh::NumericVector< Number >::operator/=().
 {
   libmesh_assert (this->initialized());
   libmesh_assert (other_vector.initialized());
   libmesh_assert_equal_to (this->first_local_index(), other_vector.first_local_index());
   libmesh_assert_equal_to (this->last_local_index(), other_vector.last_local_index());
   int first_different_i = std::numeric_limits<int>::max();
   numeric_index_type i = first_local_index();
   do
     {
       if (std::abs((*this)(i) - other_vector(i)) > threshold *
           std::max(std::abs((*this)(i)), std::abs(other_vector(i))))
         first_different_i = i;
       else
         i++;
     }
   while (first_different_i==std::numeric_limits<int>::max()
          && i<last_local_index());
   // Find the correct first differing index in parallel
   this->comm().min(first_different_i);
   if (first_different_i == std::numeric_limits<int>::max())
     return -1;
   return first_different_i;
 }
template<typename T > numeric_index_type libMesh::EigenSparseVector< T >::local_size () const inline virtual
Returns
The local size of the vector, i.e. index_stop - index_start.
Implements libMesh::NumericVector< T >.
Definition at line 452 of file eigen_sparse_vector.h.
References libMesh::NumericVector< T >::initialized(), libMesh::libmesh_assert(), and libMesh::EigenSparseVector< T >::size().
 {
   libmesh_assert (this->initialized());
   return this->size();
 }
template<typename T > void libMesh::EigenSparseVector< T >::localize (std::vector< T > & v_local) const virtual
Creates a copy of the global vector in the local vector v_local.
Implements libMesh::NumericVector< T >.
Definition at line 385 of file eigen_sparse_vector.C.
Referenced by libMesh::EigenSparseVector< T >::localize().
 {
   v_local.resize(this->size());
   for (numeric_index_type i=0; i<v_local.size(); i++)
     v_local[i] = (*this)(i);
 }
template<typename T > void libMesh::EigenSparseVector< T >::localize (NumericVector< T > & v_local) const virtual
Same, but fills a NumericVector<T> instead of a std::vector.
Implements libMesh::NumericVector< T >.
Definition at line 325 of file eigen_sparse_vector.C.
References libMesh::libmesh_assert(), libMesh::libmesh_dbg_var(), libMesh::EigenSparseVector< T >::localize(), and libMesh::EigenSparseVector< T >::size().
 {
   // Make sure the NumericVector passed in is really a EigenSparseVector
   EigenSparseVector<T> * v_local =
     cast_ptr<EigenSparseVector<T> *>(&v_local_in);
   libmesh_assert(v_local);
   *v_local = *this;
 }
template<typename T> virtual void libMesh::EigenSparseVector< T >::localize (NumericVector< T > & v_local, const std::vector< numeric_index_type > & send_list) const virtual
Creates a local vector v_local containing only information relevant to this processor, as defined by the send_list.
Implements libMesh::NumericVector< T >.
template<typename T > void libMesh::EigenSparseVector< T >::localize (std::vector< T > & v_local, const std::vector< numeric_index_type > & indices) const virtual
Fill in the local std::vector "v_local" with the global indices given in "indices".
Note
The indices can be different on every processor, and the same index can be localized to more than one processor. The resulting v_local can be shorter than the original, and the entries will be in the order specified by indices.
Example:
*   On 4 procs *this = {a, b, c, d, e, f, g, h, i} is a parallel vector.
*   On each proc, the indices arrays are set up as:
*   proc0, indices = {1,2,4,5}
*   proc1, indices = {2,5,6,8}
*   proc2, indices = {2,3,6,7}
*   proc3, indices = {0,1,2,3}
*
*   After calling this version of localize, the v_local vectors are:
*   proc0, v_local = {b,c,e,f}
*   proc1, v_local = {c,f,g,i}
*   proc2, v_local = {c,d,g,h}
*   proc3, v_local = {a,b,c,d}
*
This function is useful in parallel I/O routines, when you have a parallel vector of solution values which you want to write a subset of.
Implements libMesh::NumericVector< T >.
Definition at line 355 of file eigen_sparse_vector.C.
References libMesh::libmesh_dbg_var(), and libMesh::EigenSparseVector< T >::localize().
 {
   // EigenSparseVectors are serial, so we can just copy values
   v_local.resize(indices.size());
   for (numeric_index_type i=0; i<v_local.size(); i++)
     v_local[i] = (*this)(indices[i]);
 }
template<typename T> virtual void libMesh::EigenSparseVector< T >::localize (const numeric_index_type first_local_idx, const numeric_index_type last_local_idx, const std::vector< numeric_index_type > & send_list) virtual
Updates a local vector with selected values from neighboring processors, as defined by send_list.
Implements libMesh::NumericVector< T >.
template<typename T> void libMesh::EigenSparseVector< T >::localize_to_one (std::vector< T > & v_local, const processor_id_type proc_id = 0) const virtual
Creates a local copy of the global vector in v_local only on processor proc_id. By default the data is sent to processor 0. This method is useful for outputting data from one processor.
Implements libMesh::NumericVector< T >.
Definition at line 397 of file eigen_sparse_vector.C.
 {
   libmesh_assert_equal_to (pid, 0);
   this->localize (v_local);
 }
template<typename T > Real libMesh::EigenSparseVector< T >::max () const virtual
Returns
The maximum entry in the vector, or the maximum real part in the case of complex numbers.
Implements libMesh::NumericVector< T >.
Definition at line 417 of file eigen_sparse_vector.C.
References libMesh::initialized(), libMesh::libmesh_assert(), libMesh::libmesh_real(), std::max(), and libMesh::Real.
 {
   libmesh_assert (this->initialized());
   if (!this->size())
     return -std::numeric_limits<Real>::max();
 #ifdef LIBMESH_USE_COMPLEX_NUMBERS
   Real the_max = libmesh_real((*this)(0));
   const numeric_index_type n = this->size();
   for (numeric_index_type i=1; i<n; i++)
     the_max = std::max (the_max, libmesh_real((*this)(i)));
   return the_max;
 #else
   return libmesh_real(_vec.maxCoeff());
 #endif
 }
template<typename T > Real libMesh::EigenSparseVector< T >::min () const virtual
Returns
The minimum entry in the vector, or the minimum real part in the case of complex numbers.
Implements libMesh::NumericVector< T >.
Definition at line 440 of file eigen_sparse_vector.C.
References libMesh::initialized(), libMesh::libmesh_assert(), libMesh::libmesh_real(), std::max(), std::min(), and libMesh::Real.
 {
   libmesh_assert (this->initialized());
   if (!this->size())
     return std::numeric_limits<Real>::max();
 #ifdef LIBMESH_USE_COMPLEX_NUMBERS
   Real the_min = libmesh_real((*this)(0));
   const numeric_index_type n = this->size();
   for (numeric_index_type i=1; i<n; i++)
     the_min = std::min (the_min, libmesh_real((*this)(i)));
   return the_min;
 #else
   return libmesh_real(_vec.minCoeff());
 #endif
 }
static unsigned int libMesh::ReferenceCounter::n_objects () inline static inherited
Prints the number of outstanding (created, but not yet destroyed) objects.
Definition at line 85 of file reference_counter.h.
References libMesh::ReferenceCounter::_n_objects, libMesh::ReferenceCounter::disable_print_counter_info(), libMesh::ReferenceCounter::enable_print_counter_info(), libMesh::ReferenceCounter::increment_constructor_count(), libMesh::ReferenceCounter::increment_destructor_count(), and libMesh::Quality::name().
Referenced by libMesh::System::hide_output(), and libMesh::LibMeshInit::LibMeshInit().
   { return _n_objects; }
processor_id_type libMesh::ParallelObject::n_processors () const inline inherited
Returns
The number of processors in the group.
Definition at line 93 of file parallel_object.h.
References libMesh::ParallelObject::_communicator, and libMesh::Parallel::Communicator::size().
Referenced by libMesh::ParmetisPartitioner::_do_repartition(), libMesh::BoundaryInfo::_find_id_maps(), libMesh::DistributedMesh::add_elem(), libMesh::DistributedMesh::add_node(), libMesh::LaplaceMeshSmoother::allgather_graph(), libMesh::FEMSystem::assembly(), libMesh::ParmetisPartitioner::assign_partitioning(), libMesh::AztecLinearSolver< T >::AztecLinearSolver(), libMesh::MeshCommunication::broadcast(), libMesh::BoundaryInfo::build_node_list_from_side_list(), libMesh::DistributedMesh::clear(), libMesh::Nemesis_IO_Helper::compute_border_node_ids(), libMesh::Nemesis_IO_Helper::construct_nemesis_filename(), libMesh::MeshTools::correct_node_proc_ids(), libMesh::UnstructuredMesh::create_pid_mesh(), libMesh::MeshTools::create_processor_bounding_box(), libMesh::DofMap::distribute_dofs(), libMesh::DofMap::distribute_local_dofs_node_major(), libMesh::DofMap::distribute_local_dofs_var_major(), libMesh::DistributedMesh::DistributedMesh(), libMesh::EnsightIO::EnsightIO(), libMesh::MeshCommunication::gather(), libMesh::MeshCommunication::gather_neighboring_elements(), libMesh::MeshBase::get_info(), libMesh::EquationSystems::get_solution(), libMesh::DistributedVector< T >::init(), libMesh::SystemSubsetBySubdomain::init(), libMesh::ParmetisPartitioner::initialize(), libMesh::Nemesis_IO_Helper::initialize(), libMesh::DistributedMesh::insert_elem(), libMesh::MeshTools::libmesh_assert_parallel_consistent_procids< Elem >(), libMesh::MeshTools::libmesh_assert_parallel_consistent_procids< Node >(), libMesh::MeshTools::libmesh_assert_topology_consistent_procids< Node >(), libMesh::MeshTools::libmesh_assert_valid_boundary_ids(), libMesh::MeshTools::libmesh_assert_valid_dof_ids(), libMesh::MeshTools::libmesh_assert_valid_neighbors(), libMesh::MeshTools::libmesh_assert_valid_refinement_flags(), libMesh::DofMap::local_variable_indices(), libMesh::MeshRefinement::make_coarsening_compatible(), libMesh::MeshBase::n_active_elem_on_proc(), libMesh::MeshBase::n_elem_on_proc(), libMesh::MeshBase::n_nodes_on_proc(), libMesh::SparsityPattern::Build::parallel_sync(), libMesh::Partitioner::partition(), libMesh::MeshBase::partition(), libMesh::Partitioner::partition_unpartitioned_elements(), libMesh::PetscLinearSolver< T >::PetscLinearSolver(), libMesh::System::point_gradient(), libMesh::System::point_hessian(), libMesh::System::point_value(), libMesh::SparseMatrix< T >::print(), libMesh::NameBasedIO::read(), libMesh::Nemesis_IO::read(), libMesh::CheckpointIO::read(), libMesh::XdrIO::read(), libMesh::CheckpointIO::read_connectivity(), libMesh::CheckpointIO::read_nodes(), libMesh::MeshCommunication::redistribute(), libMesh::DistributedMesh::renumber_dof_objects(), libMesh::Partitioner::repartition(), libMesh::MeshCommunication::send_coarse_ghosts(), libMesh::Partitioner::set_node_processor_ids(), libMesh::DofMap::set_nonlocal_dof_objects(), libMesh::Parallel::Sort< KeyType, IdxType >::sort(), libMesh::MeshRefinement::uniformly_coarsen(), libMesh::DistributedMesh::update_parallel_id_counts(), libMesh::GMVIO::write_binary(), libMesh::GMVIO::write_discontinuous_gmv(), libMesh::XdrIO::write_serialized_bcs_helper(), libMesh::XdrIO::write_serialized_connectivity(), libMesh::XdrIO::write_serialized_nodes(), and libMesh::XdrIO::write_serialized_nodesets().
   { return cast_int<processor_id_type>(_communicator.size()); }
template<typename T > T libMesh::EigenSparseVector< T >::operator() (const numeric_index_type i) const inline virtual
Returns
A copy of the ith entry of the vector.
Implements libMesh::NumericVector< T >.
Definition at line 517 of file eigen_sparse_vector.h.
References libMesh::EigenSparseVector< T >::_vec, libMesh::EigenSparseVector< T >::first_local_index(), libMesh::NumericVector< T >::initialized(), libMesh::EigenSparseVector< T >::last_local_index(), and libMesh::libmesh_assert().
 {
   libmesh_assert (this->initialized());
   libmesh_assert ( ((i >= this->first_local_index()) &&
                     (i <  this->last_local_index())) );
   return _vec[static_cast<eigen_idx_type>(i)];
 }
template<typename T> NumericVector<T>& libMesh::NumericVector< T >::operator*= (const T a) inline inherited
Scales the vector by a, . Equivalent to u.scale(a)
Returns
A reference to *this.
Definition at line 384 of file numeric_vector.h.
 { this->scale(a); return *this; }
template<typename T > NumericVector< T > & libMesh::EigenSparseVector< T >::operator+= (const NumericVector< T > & v) virtual
Adds v to *this, . Equivalent to u.add(1, v).
Returns
A reference to *this.
Implements libMesh::NumericVector< T >.
Definition at line 81 of file eigen_sparse_vector.C.
References libMesh::EigenSparseVector< T >::_vec, libMesh::closed(), and libMesh::libmesh_assert().
 {
   libmesh_assert (this->closed());
   const EigenSparseVector<T> & v = cast_ref<const EigenSparseVector<T> &>(v_in);
   _vec += v._vec;
   return *this;
 }
template<typename T > NumericVector< T > & libMesh::EigenSparseVector< T >::operator-= (const NumericVector< T > & v) virtual
Subtracts v from *this, . Equivalent to u.add(-1, v).
Returns
A reference to *this.
Implements libMesh::NumericVector< T >.
Definition at line 96 of file eigen_sparse_vector.C.
References libMesh::EigenSparseVector< T >::_vec, libMesh::closed(), and libMesh::libmesh_assert().
 {
   libmesh_assert (this->closed());
   const EigenSparseVector<T> & v = cast_ref<const EigenSparseVector<T> &>(v_in);
   _vec -= v._vec;
   return *this;
 }
template<typename T > NumericVector< T > & libMesh::EigenSparseVector< T >::operator/= (NumericVector< T > &) virtual
Computes the pointwise division of this vector's entries by another's,
Returns
A reference to *this.
Implements libMesh::NumericVector< T >.
Definition at line 110 of file eigen_sparse_vector.C.
References libMesh::closed(), libMesh::libmesh_assert(), and libMesh::NumericVector< T >::size().
 {
   libmesh_assert (this->closed());
   libmesh_assert_equal_to(size(), v_in.size());
   const EigenSparseVector<T> & v = cast_ref<const EigenSparseVector<T> &>(v_in);
   _vec = _vec.cwiseQuotient(v._vec);
   return *this;
 }
template<typename T> NumericVector<T>& libMesh::NumericVector< T >::operator/= (const T a) inline inherited
Scales the vector by 1/a, . Equivalent to u.scale(1./a)
Returns
A reference to *this.
Definition at line 393 of file numeric_vector.h.
Referenced by libMesh::NumericVector< Number >::operator/=().
 { this->scale(1./a); return *this; }
template<typename T > NumericVector< T > & libMesh::EigenSparseVector< T >::operator= (const T s) virtual
Sets all entries of the vector to the value s.
Returns
A reference to *this.
Implements libMesh::NumericVector< T >.
Definition at line 257 of file eigen_sparse_vector.C.
References libMesh::closed(), libMesh::initialized(), and libMesh::libmesh_assert().
 {
   libmesh_assert (this->initialized());
   libmesh_assert (this->closed());
   _vec.fill(s);
   return *this;
 }
template<typename T > NumericVector< T > & libMesh::EigenSparseVector< T >::operator= (const NumericVector< T > & v) virtual
Sets (*this)(i) = v(i) for each entry of the vector.
Returns
A reference to *this as the base type.
Implements libMesh::NumericVector< T >.
Definition at line 271 of file eigen_sparse_vector.C.
References libMesh::libmesh_assert().
 {
   // Make sure the NumericVector passed in is really a EigenSparseVector
   const EigenSparseVector<T> * v =
     cast_ptr<const EigenSparseVector<T> *>(&v_in);
   libmesh_assert(v);
   *this = *v;
   return *this;
 }
template<typename T > EigenSparseVector< T > & libMesh::EigenSparseVector< T >::operator= (const EigenSparseVector< T > & v)
Sets (*this)(i) = v(i) for each entry of the vector.
Returns
A reference to *this as the derived type.
Definition at line 288 of file eigen_sparse_vector.C.
References libMesh::EigenSparseVector< T >::_vec, libMesh::NumericVector< T >::closed(), libMesh::initialized(), libMesh::libmesh_assert(), and libMesh::EigenSparseVector< T >::size().
 {
   libmesh_assert (this->initialized());
   libmesh_assert (v.closed());
   libmesh_assert_equal_to (this->size(), v.size());
   _vec = v._vec;
 #ifndef NDEBUG
   this->_is_closed = true;
 #endif
   return *this;
 }
template<typename T > NumericVector< T > & libMesh::EigenSparseVector< T >::operator= (const std::vector< T > & v) virtual
Sets (*this)(i) = v(i) for each entry of the vector.
Returns
A reference to *this as the base type.
Case 1: The vector is the same size of The global vector. Only add the local components.
Implements libMesh::NumericVector< T >.
Definition at line 307 of file eigen_sparse_vector.C.
 {
   if (this->size() == v.size())
     for (numeric_index_type i=0; i<v.size(); i++)
       this->set (i, v[i]);
   else
     libmesh_error_msg("this->size() = " << this->size() << " must be equal to v.size() = " << v.size());
   return *this;
 }
template<typename T > void libMesh::EigenSparseVector< T >::pointwise_mult (const NumericVector< T > & vec1, const NumericVector< T > & vec2) virtual
Computes (summation not implied) i.e. the pointwise (component-wise) product of vec1 and vec2, and stores the result in *this.
Implements libMesh::NumericVector< T >.
Definition at line 408 of file eigen_sparse_vector.C.
 {
   libmesh_not_implemented();
 }
template<typename T > void libMesh::NumericVector< T >::print (std::ostream & os = libMesh::out) const inline virtual inherited
Prints the local contents of the vector, by default to libMesh::out
Definition at line 918 of file numeric_vector.h.
References libMesh::NumericVector< T >::first_local_index(), libMesh::NumericVector< T >::initialized(), libMesh::NumericVector< T >::last_local_index(), libMesh::libmesh_assert(), libMesh::NumericVector< T >::local_size(), and libMesh::NumericVector< T >::size().
Referenced by libMesh::NumericVector< Number >::operator/=().
 {
   libmesh_assert (this->initialized());
   os << "Size\tglobal =  " << this->size()
      << "\t\tlocal =  " << this->local_size() << std::endl;
   os << "#\tValue" << std::endl;
   for (numeric_index_type i=this->first_local_index(); i<this->last_local_index(); i++)
     os << i << "\t" << (*this)(i) << std::endl;
 }
template<> void libMesh::NumericVector< Complex >::print (std::ostream & os) const inline inherited
Definition at line 900 of file numeric_vector.h.
References libMesh::NumericVector< T >::first_local_index(), libMesh::NumericVector< T >::initialized(), libMesh::NumericVector< T >::last_local_index(), libMesh::libmesh_assert(), libMesh::NumericVector< T >::local_size(), and libMesh::NumericVector< T >::size().
 {
   libmesh_assert (this->initialized());
   os << "Size\tglobal =  " << this->size()
      << "\t\tlocal =  " << this->local_size() << std::endl;
   // std::complex<>::operator<<() is defined, but use this form
   os << "#\tReal part\t\tImaginary part" << std::endl;
   for (numeric_index_type i=this->first_local_index(); i<this->last_local_index(); i++)
     os << i << "\t"
        << (*this)(i).real() << "\t\t"
        << (*this)(i).imag() << std::endl;
 }
template<typename T > void libMesh::NumericVector< T >::print_global (std::ostream & os = libMesh::out) const inline virtual inherited
Prints the global contents of the vector, by default to libMesh::out
Definition at line 955 of file numeric_vector.h.
References libMesh::NumericVector< T >::initialized(), libMesh::libmesh_assert(), libMesh::NumericVector< T >::localize(), libMesh::ParallelObject::processor_id(), and libMesh::NumericVector< T >::size().
Referenced by libMesh::NumericVector< Number >::operator/=().
 {
   libmesh_assert (this->initialized());
   std::vector<T> v(this->size());
   this->localize(v);
   // Right now we only want one copy of the output
   if (this->processor_id())
     return;
   os << "Size\tglobal =  " << this->size() << std::endl;
   os << "#\tValue" << std::endl;
   for (numeric_index_type i=0; i!=v.size(); i++)
     os << i << "\t" << v[i] << std::endl;
 }
template<> void libMesh::NumericVector< Complex >::print_global (std::ostream & os) const inline inherited
Definition at line 933 of file numeric_vector.h.
References libMesh::NumericVector< T >::initialized(), libMesh::libmesh_assert(), libMesh::NumericVector< T >::localize(), libMesh::ParallelObject::processor_id(), and libMesh::NumericVector< T >::size().
 {
   libmesh_assert (this->initialized());
   std::vector<Complex> v(this->size());
   this->localize(v);
   // Right now we only want one copy of the output
   if (this->processor_id())
     return;
   os << "Size\tglobal =  " << this->size() << std::endl;
   os << "#\tReal part\t\tImaginary part" << std::endl;
   for (numeric_index_type i=0; i!=v.size(); i++)
     os << i << "\t"
        << v[i].real() << "\t\t"
        << v[i].imag() << std::endl;
 }
void libMesh::ReferenceCounter::print_info (std::ostream & out = libMesh::out) static inherited
Prints the reference information, by default to libMesh::out.
Definition at line 88 of file reference_counter.C.
References libMesh::ReferenceCounter::_enable_print_counter, and libMesh::ReferenceCounter::get_info().
Referenced by libMesh::LibMeshInit::LibMeshInit().
 {
   if (_enable_print_counter)
     out_stream << ReferenceCounter::get_info();
 }
template<typename T> virtual void libMesh::NumericVector< T >::print_matlab (const std::string & = "") const inline virtual inherited
Print the contents of the vector in Matlab's sparse matrix format. Optionally prints the vector to the file named name. If name is not specified it is dumped to the screen.
Reimplemented in libMesh::PetscVector< T >.
Definition at line 674 of file numeric_vector.h.
   {
     libmesh_not_implemented();
   }
processor_id_type libMesh::ParallelObject::processor_id () const inline inherited
Returns
The rank of this processor in the group.
Definition at line 99 of file parallel_object.h.
References libMesh::ParallelObject::_communicator, and libMesh::Parallel::Communicator::rank().
Referenced by libMesh::BoundaryInfo::_find_id_maps(), libMesh::EquationSystems::_read_impl(), libMesh::DistributedMesh::add_elem(), libMesh::BoundaryInfo::add_elements(), libMesh::DofMap::add_neighbors_to_send_list(), libMesh::DistributedMesh::add_node(), libMesh::MeshRefinement::add_node(), libMesh::MeshTools::Modification::all_tri(), libMesh::FEMSystem::assembly(), libMesh::ParmetisPartitioner::assign_partitioning(), libMesh::MeshCommunication::broadcast(), libMesh::EquationSystems::build_discontinuous_solution_vector(), libMesh::Nemesis_IO_Helper::build_element_and_node_maps(), libMesh::ParmetisPartitioner::build_graph(), libMesh::InfElemBuilder::build_inf_elem(), libMesh::BoundaryInfo::build_node_list_from_side_list(), libMesh::DofMap::build_sparsity(), libMesh::DistributedMesh::clear(), libMesh::ExodusII_IO_Helper::close(), libMesh::Nemesis_IO_Helper::compute_border_node_ids(), libMesh::Nemesis_IO_Helper::compute_communication_map_parameters(), libMesh::Nemesis_IO_Helper::compute_internal_and_border_elems_and_internal_nodes(), libMesh::Nemesis_IO_Helper::compute_node_communication_maps(), libMesh::Nemesis_IO_Helper::compute_num_global_elem_blocks(), libMesh::Nemesis_IO_Helper::compute_num_global_nodesets(), libMesh::Nemesis_IO_Helper::compute_num_global_sidesets(), libMesh::Nemesis_IO_Helper::construct_nemesis_filename(), libMesh::MeshTools::correct_node_proc_ids(), libMesh::ExodusII_IO_Helper::create(), libMesh::DistributedMesh::delete_elem(), libMesh::DistributedMesh::delete_node(), libMesh::MeshCommunication::delete_remote_elements(), libMesh::DofMap::distribute_dofs(), libMesh::DofMap::distribute_local_dofs_node_major(), libMesh::DofMap::distribute_local_dofs_var_major(), libMesh::DistributedMesh::DistributedMesh(), libMesh::EnsightIO::EnsightIO(), libMesh::MeshFunction::find_element(), libMesh::MeshFunction::find_elements(), libMesh::UnstructuredMesh::find_neighbors(), libMesh::MeshCommunication::gather(), libMesh::MeshCommunication::gather_neighboring_elements(), libMesh::Nemesis_IO_Helper::get_cmap_params(), libMesh::Nemesis_IO_Helper::get_eb_info_global(), libMesh::Nemesis_IO_Helper::get_elem_cmap(), libMesh::Nemesis_IO_Helper::get_elem_map(), libMesh::MeshBase::get_info(), libMesh::DofMap::get_info(), libMesh::Nemesis_IO_Helper::get_init_global(), libMesh::Nemesis_IO_Helper::get_init_info(), libMesh::Nemesis_IO_Helper::get_loadbal_param(), libMesh::Nemesis_IO_Helper::get_node_cmap(), libMesh::Nemesis_IO_Helper::get_node_map(), libMesh::Nemesis_IO_Helper::get_ns_param_global(), libMesh::EquationSystems::get_solution(), libMesh::Nemesis_IO_Helper::get_ss_param_global(), libMesh::SparsityPattern::Build::handle_vi_vj(), libMesh::DistributedVector< T >::init(), libMesh::SystemSubsetBySubdomain::init(), libMesh::ParmetisPartitioner::initialize(), libMesh::ExodusII_IO_Helper::initialize(), libMesh::ExodusII_IO_Helper::initialize_element_variables(), libMesh::ExodusII_IO_Helper::initialize_global_variables(), libMesh::ExodusII_IO_Helper::initialize_nodal_variables(), libMesh::DistributedMesh::insert_elem(), libMesh::DofMap::is_evaluable(), libMesh::SparsityPattern::Build::join(), libMesh::MeshTools::libmesh_assert_parallel_consistent_procids< Elem >(), libMesh::MeshTools::libmesh_assert_parallel_consistent_procids< Node >(), libMesh::MeshTools::libmesh_assert_valid_neighbors(), libMesh::DistributedMesh::libmesh_assert_valid_parallel_object_ids(), libMesh::DofMap::local_variable_indices(), libMesh::MeshRefinement::make_coarsening_compatible(), libMesh::MeshBase::n_active_local_elem(), libMesh::BoundaryInfo::n_boundary_conds(), libMesh::BoundaryInfo::n_edge_conds(), libMesh::System::n_local_dofs(), libMesh::MeshBase::n_local_elem(), libMesh::MeshBase::n_local_nodes(), libMesh::BoundaryInfo::n_nodeset_conds(), libMesh::BoundaryInfo::n_shellface_conds(), libMesh::WeightedPatchRecoveryErrorEstimator::EstimateError::operator()(), libMesh::SparsityPattern::Build::operator()(), libMesh::PatchRecoveryErrorEstimator::EstimateError::operator()(), libMesh::SparsityPattern::Build::parallel_sync(), libMesh::MetisPartitioner::partition_range(), libMesh::System::point_gradient(), libMesh::System::point_hessian(), libMesh::System::point_value(), libMesh::SparseMatrix< T >::print(), libMesh::NumericVector< T >::print_global(), libMesh::Nemesis_IO_Helper::put_cmap_params(), libMesh::Nemesis_IO_Helper::put_elem_cmap(), libMesh::Nemesis_IO_Helper::put_elem_map(), libMesh::Nemesis_IO_Helper::put_loadbal_param(), libMesh::Nemesis_IO_Helper::put_node_cmap(), libMesh::Nemesis_IO_Helper::put_node_map(), libMesh::NameBasedIO::read(), libMesh::Nemesis_IO::read(), libMesh::CheckpointIO::read(), libMesh::XdrIO::read(), libMesh::ExodusII_IO_Helper::read_elem_num_map(), libMesh::ExodusII_IO_Helper::read_node_num_map(), libMesh::XdrIO::read_serialized_bc_names(), libMesh::XdrIO::read_serialized_bcs_helper(), libMesh::XdrIO::read_serialized_connectivity(), libMesh::XdrIO::read_serialized_nodes(), libMesh::XdrIO::read_serialized_nodesets(), libMesh::XdrIO::read_serialized_subdomain_names(), libMesh::MeshCommunication::redistribute(), libMesh::DistributedMesh::renumber_dof_objects(), libMesh::MeshCommunication::send_coarse_ghosts(), libMesh::Partitioner::set_node_processor_ids(), libMesh::DofMap::set_nonlocal_dof_objects(), libMesh::LaplaceMeshSmoother::smooth(), libMesh::MeshTools::total_weight(), libMesh::MeshRefinement::uniformly_coarsen(), libMesh::Parallel::Packing< Node * >::unpack(), libMesh::Parallel::Packing< Elem * >::unpack(), libMesh::DistributedMesh::update_parallel_id_counts(), libMesh::MeshTools::weight(), libMesh::NameBasedIO::write(), libMesh::CheckpointIO::write(), libMesh::XdrIO::write(), libMesh::EquationSystems::write(), libMesh::GMVIO::write_discontinuous_gmv(), libMesh::ExodusII_IO::write_element_data(), libMesh::ExodusII_IO_Helper::write_element_values(), libMesh::ExodusII_IO_Helper::write_elements(), libMesh::ExodusII_IO::write_global_data(), libMesh::ExodusII_IO_Helper::write_global_values(), libMesh::ExodusII_IO::write_information_records(), libMesh::ExodusII_IO_Helper::write_information_records(), libMesh::ExodusII_IO_Helper::write_nodal_coordinates(), libMesh::UCDIO::write_nodal_data(), libMesh::ExodusII_IO::write_nodal_data(), libMesh::ExodusII_IO::write_nodal_data_discontinuous(), libMesh::ExodusII_IO_Helper::write_nodal_values(), libMesh::Nemesis_IO_Helper::write_nodesets(), libMesh::ExodusII_IO_Helper::write_nodesets(), libMesh::XdrIO::write_serialized_bc_names(), libMesh::XdrIO::write_serialized_bcs_helper(), libMesh::XdrIO::write_serialized_connectivity(), libMesh::XdrIO::write_serialized_nodes(), libMesh::XdrIO::write_serialized_nodesets(), libMesh::XdrIO::write_serialized_subdomain_names(), libMesh::Nemesis_IO_Helper::write_sidesets(), libMesh::ExodusII_IO_Helper::write_sidesets(), libMesh::ExodusII_IO::write_timestep(), and libMesh::ExodusII_IO_Helper::write_timestep().
   { return cast_int<processor_id_type>(_communicator.rank()); }
template<typename T > void libMesh::EigenSparseVector< T >::reciprocal () virtual
Computes the pointwise reciprocal,
Implements libMesh::NumericVector< T >.
Definition at line 126 of file eigen_sparse_vector.C.
 {
 #ifndef NDEBUG
   const numeric_index_type n = this->size();
   for (numeric_index_type i=0; i<n; i++)
     // Don't divide by zero!
     libmesh_assert_not_equal_to ((*this)(i), T(0));
 #endif
   _vec = _vec.cwiseInverse();
 }
template<typename T > void libMesh::EigenSparseVector< T >::scale (const T factor) virtual
Scale each element of the vector by the given factor.
Implements libMesh::NumericVector< T >.
Definition at line 219 of file eigen_sparse_vector.C.
References libMesh::initialized(), and libMesh::libmesh_assert().
 {
   libmesh_assert (this->initialized());
   _vec *= factor;
 }
template<typename T > void libMesh::EigenSparseVector< T >::set (const numeric_index_type i, const T value) inline virtual
Sets v(i) = value.
Implements libMesh::NumericVector< T >.
Definition at line 485 of file eigen_sparse_vector.h.
References libMesh::NumericVector< T >::_is_closed, libMesh::EigenSparseVector< T >::_vec, libMesh::NumericVector< T >::initialized(), libMesh::libmesh_assert(), and libMesh::EigenSparseVector< T >::size().
 {
   libmesh_assert (this->initialized());
   libmesh_assert_less (i, this->size());
   _vec[static_cast<eigen_idx_type>(i)] = value;
 #ifndef NDEBUG
   this->_is_closed = false;
 #endif
 }
template<typename T > numeric_index_type libMesh::EigenSparseVector< T >::size () const inline virtual
Returns
The size of the vector.
Implements libMesh::NumericVector< T >.
Definition at line 441 of file eigen_sparse_vector.h.
References libMesh::EigenSparseVector< T >::_vec, libMesh::NumericVector< T >::initialized(), and libMesh::libmesh_assert().
Referenced by libMesh::EigenSparseVector< T >::add(), libMesh::EigenSparseVector< T >::last_local_index(), libMesh::EigenSparseVector< T >::local_size(), libMesh::EigenSparseVector< T >::localize(), libMesh::EigenSparseVector< T >::operator=(), and libMesh::EigenSparseVector< T >::set().
 {
   libmesh_assert (this->initialized());
   return static_cast<numeric_index_type>(_vec.size());
 }
template<class T > Real libMesh::NumericVector< T >::subset_l1_norm (const std::set< numeric_index_type > & indices) const virtual inherited
Returns
The -norm of the vector, i.e. the sum of the absolute values for the specified entries in the vector.
Note
The indices must necessarily live on this processor.
Definition at line 323 of file numeric_vector.C.
References std::abs(), and libMesh::Real.
Referenced by libMesh::NumericVector< Number >::closed(), and libMesh::System::discrete_var_norm().
 {
   const NumericVector<T> & v = *this;
   std::set<numeric_index_type>::const_iterator it = indices.begin();
   const std::set<numeric_index_type>::const_iterator it_end = indices.end();
   Real norm = 0;
   for (; it!=it_end; ++it)
     norm += std::abs(v(*it));
   this->comm().sum(norm);
   return norm;
 }
template<class T > Real libMesh::NumericVector< T >::subset_l2_norm (const std::set< numeric_index_type > & indices) const virtual inherited
Returns
The -norm of the vector, i.e. the square root of the sum of the squares of the elements for the specified entries in the vector.
Note
The indices must necessarily live on this processor.
Definition at line 341 of file numeric_vector.C.
References libMesh::TensorTools::norm_sq(), and libMesh::Real.
Referenced by libMesh::NumericVector< Number >::closed(), and libMesh::System::discrete_var_norm().
 {
   const NumericVector<T> & v = *this;
   std::set<numeric_index_type>::const_iterator it = indices.begin();
   const std::set<numeric_index_type>::const_iterator it_end = indices.end();
   Real norm = 0;
   for (; it!=it_end; ++it)
     norm += TensorTools::norm_sq(v(*it));
   this->comm().sum(norm);
   return std::sqrt(norm);
 }
template<class T > Real libMesh::NumericVector< T >::subset_linfty_norm (const std::set< numeric_index_type > & indices) const virtual inherited
Returns
The maximum absolute value of the specified entries of this vector, which is the -norm of a vector.
Note
The indices must necessarily live on this processor.
Definition at line 359 of file numeric_vector.C.
References std::abs(), and libMesh::Real.
Referenced by libMesh::NumericVector< Number >::closed(), and libMesh::System::discrete_var_norm().
 {
   const NumericVector<T> & v = *this;
   std::set<numeric_index_type>::const_iterator it = indices.begin();
   const std::set<numeric_index_type>::const_iterator it_end = indices.end();
   Real norm = 0;
   for (; it!=it_end; ++it)
     {
       Real value = std::abs(v(*it));
       if (value > norm)
         norm = value;
     }
   this->comm().max(norm);
   return norm;
 }
template<typename T > T libMesh::EigenSparseVector< T >::sum () const virtual
Returns
The sum of all values in the vector.
Implements libMesh::NumericVector< T >.
Definition at line 37 of file eigen_sparse_vector.C.
References libMesh::closed(), libMesh::initialized(), and libMesh::libmesh_assert().
 {
   libmesh_assert (this->closed());
   libmesh_assert (this->initialized());
   return _vec.sum();
 }
template<typename T > void libMesh::EigenSparseVector< T >::swap (NumericVector< T > & v) inline virtual
Swaps the contents of this with v. There should be enough indirection in subclasses to make this an O(1) header-swap operation.
Reimplemented from libMesh::NumericVector< T >.
Definition at line 530 of file eigen_sparse_vector.h.
References libMesh::NumericVector< T >::_is_closed, libMesh::NumericVector< T >::_is_initialized, libMesh::NumericVector< T >::_type, libMesh::EigenSparseVector< T >::_vec, and swap().
 {
   EigenSparseVector<T> & v = cast_ref<EigenSparseVector<T> &>(other);
   _vec.swap(v._vec);
   std::swap (this->_is_closed,      v._is_closed);
   std::swap (this->_is_initialized, v._is_initialized);
   std::swap (this->_type,           v._type);
 }
template<typename T> ParallelType libMesh::NumericVector< T >::type () const inline inherited
Returns
The type (SERIAL, PARALLEL, GHOSTED) of the vector.
Definition at line 140 of file numeric_vector.h.
Referenced by libMesh::PetscVector< T >::clone(), libMesh::PetscVector< T >::close(), libMesh::DofMap::enforce_adjoint_constraints_exactly(), libMesh::DofMap::enforce_constraints_exactly(), libMesh::EpetraVector< T >::EpetraVector(), libMesh::MeshFunction::find_element(), libMesh::MeshFunction::find_elements(), libMesh::PetscVector< T >::get(), libMesh::DistributedVector< T >::init(), libMesh::EigenSparseVector< T >::init(), libMesh::LaspackVector< T >::init(), libMesh::EpetraVector< T >::init(), libMesh::PetscVector< T >::localize(), libMesh::PetscVector< T >::operator()(), libMesh::PetscVector< T >::operator=(), libMesh::System::project_vector(), libMesh::System::read_serialized_vector(), libMesh::PetscVector< T >::zero(), and libMesh::PetscVector< T >::zero_clone().
 { return _type; }
template<typename T> ParallelType& libMesh::NumericVector< T >::type () inline inherited
Returns
The type (SERIAL, PARALLEL, GHOSTED) of the vector.
Definition at line 145 of file numeric_vector.h.
 { return _type; }
template<typename T> DataType& libMesh::EigenSparseVector< T >::vec () inline
References to the underlying Eigen data types.
Note
This is generally not required in user-level code.
Definition at line 229 of file eigen_sparse_vector.h.
References libMesh::EigenSparseVector< T >::_vec.
 { return _vec; }
template<typename T> const DataType& libMesh::EigenSparseVector< T >::vec () const inline
Definition at line 230 of file eigen_sparse_vector.h.
References libMesh::EigenSparseVector< T >::_vec.
 { return _vec; }
template<typename T > void libMesh::EigenSparseVector< T >::zero () inline virtual
Set all entries to zero. Equivalent to v = 0, but more obvious and faster.
Implements libMesh::NumericVector< T >.
Definition at line 406 of file eigen_sparse_vector.h.
References libMesh::EigenSparseVector< T >::_vec, libMesh::NumericVector< T >::closed(), libMesh::NumericVector< T >::initialized(), and libMesh::libmesh_assert().
Referenced by libMesh::EigenSparseVector< T >::init().
 {
   libmesh_assert (this->initialized());
   libmesh_assert (this->closed());
   _vec.setZero();
 }
template<typename T > UniquePtr< NumericVector< T > > libMesh::EigenSparseVector< T >::zero_clone () const inline virtual
Returns
A smart pointer to a copy of this vector with the same type, size, and partitioning, but with all zero entries.
Note
This must be overridden in the derived classes.
Implements libMesh::NumericVector< T >.
Definition at line 418 of file eigen_sparse_vector.h.
References libMesh::ParallelObject::comm(), and libMesh::NumericVector< T >::init().
 {
   NumericVector<T> * cloned_vector = new EigenSparseVector<T>(this->comm());
   cloned_vector->init(*this);
   return UniquePtr<NumericVector<T> >(cloned_vector);
 }
Friends And Related Function Documentation
template<typename T> friend class EigenSparseLinearSolver< T > friend
Definition at line 243 of file eigen_sparse_vector.h.
template<typename T> friend class EigenSparseMatrix< T > friend
Make other Eigen datatypes friends
Definition at line 242 of file eigen_sparse_vector.h.
Member Data Documentation
const Parallel::Communicator& libMesh::ParallelObject::_communicator protected inherited
Definition at line 105 of file parallel_object.h.
Referenced by libMesh::EquationSystems::build_parallel_solution_vector(), libMesh::ParallelObject::comm(), libMesh::EquationSystems::get_solution(), libMesh::ParallelObject::n_processors(), libMesh::ParallelObject::operator=(), and libMesh::ParallelObject::processor_id().
ReferenceCounter::Counts libMesh::ReferenceCounter::_counts static protected inherited
Actually holds the data.
Definition at line 124 of file reference_counter.h.
Referenced by libMesh::ReferenceCounter::get_info(), libMesh::ReferenceCounter::increment_constructor_count(), and libMesh::ReferenceCounter::increment_destructor_count().
bool libMesh::ReferenceCounter::_enable_print_counter = true static protected inherited
Flag to control whether reference count information is printed when print_info is called.
Definition at line 143 of file reference_counter.h.
Referenced by libMesh::ReferenceCounter::disable_print_counter_info(), libMesh::ReferenceCounter::enable_print_counter_info(), and libMesh::ReferenceCounter::print_info().
template<typename T> bool libMesh::NumericVector< T >::_is_closed protected inherited
Flag which tracks whether the vector's values are consistent on all processors after insertion or addition of values has occurred on some or all processors.
Definition at line 705 of file numeric_vector.h.
Referenced by libMesh::EigenSparseVector< T >::add(), libMesh::LaspackVector< T >::add(), libMesh::DistributedVector< T >::clear(), libMesh::LaspackVector< T >::clear(), libMesh::EigenSparseVector< T >::clear(), libMesh::EpetraVector< T >::clear(), libMesh::PetscVector< T >::clear(), libMesh::NumericVector< T >::clear(), libMesh::DistributedVector< T >::close(), libMesh::LaspackVector< T >::close(), libMesh::EigenSparseVector< T >::close(), libMesh::EpetraVector< T >::close(), libMesh::PetscVector< T >::close(), libMesh::NumericVector< Number >::closed(), libMesh::EpetraVector< T >::EpetraVector(), libMesh::EigenSparseVector< T >::init(), libMesh::EpetraVector< T >::init(), libMesh::PetscVector< T >::init(), libMesh::DistributedVector< T >::localize(), libMesh::DistributedVector< T >::operator=(), libMesh::PetscVector< T >::PetscVector(), libMesh::EigenSparseVector< T >::set(), libMesh::LaspackVector< T >::set(), libMesh::EigenSparseVector< T >::swap(), libMesh::NumericVector< T >::swap(), and libMesh::LaspackVector< T >::~LaspackVector().
template<typename T> bool libMesh::NumericVector< T >::_is_initialized protected inherited
true once init() has been called.
Definition at line 710 of file numeric_vector.h.
Referenced by libMesh::DistributedVector< T >::clear(), libMesh::LaspackVector< T >::clear(), libMesh::EigenSparseVector< T >::clear(), libMesh::EpetraVector< T >::clear(), libMesh::PetscVector< T >::clear(), libMesh::NumericVector< T >::clear(), libMesh::PetscVector< T >::create_subvector(), libMesh::EpetraVector< T >::EpetraVector(), libMesh::DistributedVector< T >::init(), libMesh::EigenSparseVector< T >::init(), libMesh::EpetraVector< T >::init(), libMesh::PetscVector< T >::init(), libMesh::NumericVector< Number >::initialized(), libMesh::DistributedVector< T >::localize(), libMesh::DistributedVector< T >::operator=(), libMesh::PetscVector< T >::PetscVector(), libMesh::EigenSparseVector< T >::swap(), libMesh::NumericVector< T >::swap(), and libMesh::LaspackVector< T >::~LaspackVector().
Threads::spin_mutex libMesh::ReferenceCounter::_mutex static protected inherited
Mutual exclusion object to enable thread-safe reference counting.
Definition at line 137 of file reference_counter.h.
Threads::atomic< unsigned int > libMesh::ReferenceCounter::_n_objects static protected inherited
The number of objects. Print the reference count information when the number returns to 0.
Definition at line 132 of file reference_counter.h.
Referenced by libMesh::ReferenceCounter::n_objects(), libMesh::ReferenceCounter::ReferenceCounter(), and libMesh::ReferenceCounter::~ReferenceCounter().
template<typename T> ParallelType libMesh::NumericVector< T >::_type protected inherited
Type of vector.
Definition at line 715 of file numeric_vector.h.
Referenced by libMesh::DistributedVector< T >::DistributedVector(), libMesh::EigenSparseVector< T >::EigenSparseVector(), libMesh::EpetraVector< T >::EpetraVector(), libMesh::DistributedVector< T >::init(), libMesh::EigenSparseVector< T >::init(), libMesh::EpetraVector< T >::init(), libMesh::PetscVector< T >::init(), libMesh::LaspackVector< T >::LaspackVector(), libMesh::PetscVector< T >::operator=(), libMesh::PetscVector< T >::PetscVector(), libMesh::EigenSparseVector< T >::swap(), libMesh::NumericVector< T >::swap(), libMesh::NumericVector< Number >::type(), and libMesh::LaspackVector< T >::~LaspackVector().
template<typename T> DataType libMesh::EigenSparseVector< T >::_vec private
Actual Eigen::SparseVector<> we are wrapping.
Definition at line 237 of file eigen_sparse_vector.h.
Referenced by libMesh::EigenSparseVector< T >::add(), libMesh::EigenSparseVector< T >::add_vector(), libMesh::EigenSparseVector< T >::add_vector_transpose(), libMesh::EigenSparseVector< T >::clear(), libMesh::EigenSparseVector< T >::dot(), libMesh::EigenSparseMatrix< T >::get_diagonal(), libMesh::EigenSparseVector< T >::init(), libMesh::EigenSparseVector< T >::operator()(), libMesh::EigenSparseVector< T >::operator+=(), libMesh::EigenSparseVector< T >::operator-=(), libMesh::EigenSparseVector< T >::operator=(), libMesh::EigenSparseVector< T >::set(), libMesh::EigenSparseVector< T >::size(), libMesh::EigenSparseVector< T >::swap(), libMesh::EigenSparseVector< T >::vec(), and libMesh::EigenSparseVector< T >::zero().
The documentation for this class was generated from the following files:
eigen_sparse_matrix.h
eigen_sparse_vector.h
eigen_sparse_vector.C