libMesh: libMesh::GnuPlotIO Class Reference
SomeWebsiteLogo
libMesh::GnuPlotIO Class Reference
#include <gnuplot_io.h>
Public Types
enum PlottingProperties { GRID_ON = 1, PNG_OUTPUT = 2 }
Public Member Functions
GnuPlotIO (const MeshBase &, const std::string &=std::string("FE 1D Solution"), int properties=0)
virtual void write (const std::string &) override
virtual void write_nodal_data (const std::string &, const std::vector< Number > &, const std::vector< std::string > &) override
void set_title (const std::string &title)
void use_grid (bool grid)
void set_png_output (bool png_output)
virtual void write_equation_systems (const std::string &, const EquationSystems &, const std::set< std::string > *system_names=nullptr)
virtual void write_discontinuous_equation_systems (const std::string &, const EquationSystems &, const std::set< std::string > *system_names=nullptr)
virtual void write_nodal_data (const std::string &, const NumericVector< Number > &, const std::vector< std::string > &)
virtual void write_nodal_data_discontinuous (const std::string &, const std::vector< Number > &, const std::vector< std::string > &)
unsigned int & ascii_precision ()
Public Attributes
std::string axes_limits
Protected Member Functions
const MeshBase & mesh () const
Protected Attributes
const bool _is_parallel_format
const bool _serial_only_needed_on_proc_0
Private Member Functions
void write_solution (const std::string &, const std::vector< Number > *=nullptr, const std::vector< std::string > *=nullptr)
Private Attributes
std::string _title
bool _grid
bool _png_output
Detailed Description
This class implements writing meshes using GNUplot, designed for use only with 1D meshes.
Author
David Knezevic
Date
2005
Definition at line 43 of file gnuplot_io.h.
Member Enumeration Documentation
PlottingProperties
enum libMesh::GnuPlotIO::PlottingProperties
Define enumerations to set plotting properties on construction
Enumerator
GRID_ON
PNG_OUTPUT
Definition at line 50 of file gnuplot_io.h.
                           { GRID_ON    = 1,
                             PNG_OUTPUT = 2};
Constructor & Destructor Documentation
GnuPlotIO()
libMesh::GnuPlotIO::GnuPlotIO (const MeshBase & mesh_in, const std::string & title = std::string("FE 1D Solution"), int properties = 0) explicit
Constructor. Takes a reference to a constant mesh object. To set the properties, we input a bitwise OR of the GnuPlotIO::PlottingProperties enumerations, e.g. GnuPlotIO::GRID_ON | GnuPlotIO::PNG_OUTPUT
Definition at line 32 of file gnuplot_io.C.
References _grid, _png_output, GRID_ON, and PNG_OUTPUT.
   :
   MeshOutput<MeshBase> (mesh_in),
   _title(title)
 {
   _grid       = (mesh_properties & GRID_ON);
   _png_output = (mesh_properties & PNG_OUTPUT);
 }
Member Function Documentation
ascii_precision()
unsigned int & libMesh::MeshOutput< MeshBase >::ascii_precision () inline inherited
Return/set the precision to use when writing ASCII files.
By default we use numeric_limits<Real>::digits10 + 2, which should be enough to write out to ASCII and get the exact same Real back when reading in.
Definition at line 244 of file mesh_output.h.
Referenced by libMesh::TecplotIO::write_ascii(), libMesh::GMVIO::write_ascii_new_impl(), and libMesh::GMVIO::write_ascii_old_impl().
 {
   return _ascii_precision;
 }
mesh()
const MeshBase & libMesh::MeshOutput< MeshBase >::mesh () const inline protected inherited
Returns
The object as a read-only reference.
Definition at line 234 of file mesh_output.h.
Referenced by libMesh::FroIO::write(), libMesh::TecplotIO::write(), libMesh::MEDITIO::write(), libMesh::PostscriptIO::write(), libMesh::EnsightIO::write(), libMesh::TecplotIO::write_ascii(), libMesh::TecplotIO::write_binary(), libMesh::TecplotIO::write_nodal_data(), libMesh::MEDITIO::write_nodal_data(), and write_solution().
 {
   libmesh_assert(_obj);
   return *_obj;
 }
set_png_output()
void libMesh::GnuPlotIO::set_png_output (bool png_output) inline
Write output to a .png file using gnuplot
Definition at line 97 of file gnuplot_io.h.
References _png_output.
 { _png_output = png_output; }
set_title()
void libMesh::GnuPlotIO::set_title (const std::string & title) inline
Set title of plot
Definition at line 86 of file gnuplot_io.h.
References _title.
 { _title = title; }
use_grid()
void libMesh::GnuPlotIO::use_grid (bool grid) inline
Turn grid on or off.
Definition at line 91 of file gnuplot_io.h.
References _grid.
 { _grid = grid; }
write()
void libMesh::GnuPlotIO::write (const std::string & fname) override virtual
Write the mesh to the specified file.
Implements libMesh::MeshOutput< MeshBase >.
Definition at line 43 of file gnuplot_io.C.
References write_solution().
 {
   this->write_solution(fname);
 }
write_discontinuous_equation_systems()
void libMesh::MeshOutput< MeshBase >::write_discontinuous_equation_systems (const std::string & fname, const EquationSystems & es, const std::set< std::string > * system_names = nullptr) virtual inherited
This method implements writing a mesh with discontinuous data to a specified file where the data is taken from the EquationSystems object.
Definition at line 92 of file mesh_output.C.
References libMesh::EquationSystems::build_discontinuous_solution_vector(), libMesh::EquationSystems::build_variable_names(), libMesh::EquationSystems::get_mesh(), and libMesh::out.
Referenced by libMesh::ExodusII_IO::write_timestep_discontinuous().
 {
   LOG_SCOPE("write_discontinuous_equation_systems()", "MeshOutput");
   // We may need to gather and/or renumber a DistributedMesh to output
   // it, making that const qualifier in our constructor a dirty lie
   MT & my_mesh = const_cast<MT &>(*_obj);
   // If we're asked to write data that's associated with a different
   // mesh, output files full of garbage are the result.
   libmesh_assert_equal_to(&es.get_mesh(), _obj);
   // A non-renumbered mesh may not have a contiguous numbering, and
   // that needs to be fixed before we can build a solution vector.
   if (my_mesh.max_elem_id() != my_mesh.n_elem() ||
       my_mesh.max_node_id() != my_mesh.n_nodes())
     {
       // If we were allowed to renumber then we should have already
       // been properly renumbered...
       libmesh_assert(!my_mesh.allow_renumbering());
       libmesh_do_once(libMesh::out <<
                       "Warning:  This MeshOutput subclass only supports meshes which are contiguously renumbered!"
                       << std::endl;);
       my_mesh.allow_renumbering(true);
       my_mesh.renumber_nodes_and_elements();
       // Not sure what good going back to false will do here, the
       // renumbering horses have already left the barn...
       my_mesh.allow_renumbering(false);
     }
   MeshSerializer serialize(const_cast<MT &>(*_obj), !_is_parallel_format, _serial_only_needed_on_proc_0);
   // Build the list of variable names that will be written.
   std::vector<std::string> names;
   es.build_variable_names  (names, nullptr, system_names);
   if (!_is_parallel_format)
     {
       // Build the nodal solution values & get the variable
       // names from the EquationSystems object
       std::vector<Number> soln;
       es.build_discontinuous_solution_vector (soln, system_names);
       this->write_nodal_data_discontinuous (fname, soln, names);
     }
   else // _is_parallel_format
     {
       libmesh_not_implemented();
     }
 }
write_equation_systems()
void libMesh::MeshOutput< MeshBase >::write_equation_systems (const std::string & fname, const EquationSystems & es, const std::set< std::string > * system_names = nullptr) virtual inherited
This method implements writing a mesh with data to a specified file where the data is taken from the EquationSystems object.
Reimplemented in libMesh::NameBasedIO.
Definition at line 31 of file mesh_output.C.
References libMesh::EquationSystems::build_parallel_solution_vector(), libMesh::EquationSystems::build_solution_vector(), libMesh::EquationSystems::build_variable_names(), libMesh::EquationSystems::get_mesh(), and libMesh::out.
Referenced by libMesh::Nemesis_IO::write_timestep(), and libMesh::ExodusII_IO::write_timestep().
 {
   LOG_SCOPE("write_equation_systems()", "MeshOutput");
   // We may need to gather and/or renumber a DistributedMesh to output
   // it, making that const qualifier in our constructor a dirty lie
   MT & my_mesh = const_cast<MT &>(*_obj);
   // If we're asked to write data that's associated with a different
   // mesh, output files full of garbage are the result.
   libmesh_assert_equal_to(&es.get_mesh(), _obj);
   // A non-renumbered mesh may not have a contiguous numbering, and
   // that needs to be fixed before we can build a solution vector.
   if (my_mesh.max_elem_id() != my_mesh.n_elem() ||
       my_mesh.max_node_id() != my_mesh.n_nodes())
     {
       // If we were allowed to renumber then we should have already
       // been properly renumbered...
       libmesh_assert(!my_mesh.allow_renumbering());
       libmesh_do_once(libMesh::out <<
                       "Warning:  This MeshOutput subclass only supports meshes which are contiguously renumbered!"
                       << std::endl;);
       my_mesh.allow_renumbering(true);
       my_mesh.renumber_nodes_and_elements();
       // Not sure what good going back to false will do here, the
       // renumbering horses have already left the barn...
       my_mesh.allow_renumbering(false);
     }
   MeshSerializer serialize(const_cast<MT &>(*_obj), !_is_parallel_format, _serial_only_needed_on_proc_0);
   // Build the list of variable names that will be written.
   std::vector<std::string> names;
   es.build_variable_names  (names, nullptr, system_names);
   if (!_is_parallel_format)
     {
       // Build the nodal solution values & get the variable
       // names from the EquationSystems object
       std::vector<Number> soln;
       es.build_solution_vector (soln, system_names);
       this->write_nodal_data (fname, soln, names);
     }
   else // _is_parallel_format
     {
       std::unique_ptr<NumericVector<Number>> parallel_soln =
         es.build_parallel_solution_vector(system_names);
       this->write_nodal_data (fname, *parallel_soln, names);
     }
 }
write_nodal_data() [1/2]
void libMesh::GnuPlotIO::write_nodal_data (const std::string & fname, const std::vector< Number > & soln, const std::vector< std::string > & names) override virtual
This method implements writing a mesh with nodal data to a specified file where the nodal data and variable names are provided.
Reimplemented from libMesh::MeshOutput< MeshBase >.
Definition at line 48 of file gnuplot_io.C.
References write_solution().
 {
   LOG_SCOPE("write_nodal_data()", "GnuPlotIO");
   this->write_solution(fname, &soln, &names);
 }
write_nodal_data() [2/2]
void libMesh::MeshOutput< MeshBase >::write_nodal_data (const std::string & fname, const NumericVector< Number > & parallel_soln, const std::vector< std::string > & names) virtual inherited
This method should be overridden by "parallel" output formats for writing nodal data. Instead of getting a localized copy of the nodal solution vector, it is passed a NumericVector of type=PARALLEL which is in node-major order i.e. (u0,v0,w0, u1,v1,w1, u2,v2,w2, u3,v3,w3, ...) and contains n_nodes*n_vars total entries. Then, it is up to the individual I/O class to extract the required solution values from this vector and write them in parallel.
If not implemented, localizes the parallel vector into a std::vector and calls the other version of this function.
Reimplemented in libMesh::Nemesis_IO.
Definition at line 150 of file mesh_output.C.
References libMesh::NumericVector< T >::localize().
 {
   // This is the fallback implementation for parallel I/O formats that
   // do not yet implement proper writing in parallel, and instead rely
   // on the full solution vector being available on all processors.
   std::vector<Number> soln;
   parallel_soln.localize(soln);
   this->write_nodal_data(fname, soln, names);
 }
write_nodal_data_discontinuous()
virtual void libMesh::MeshOutput< MeshBase >::write_nodal_data_discontinuous (const std::string & , const std::vector< Number > & , const std::vector< std::string > &) inline virtual inherited
This method implements writing a mesh with discontinuous data to a specified file where the nodal data and variables names are provided.
Reimplemented in libMesh::ExodusII_IO.
Definition at line 114 of file mesh_output.h.
   { libmesh_not_implemented(); }
write_solution()
void libMesh::GnuPlotIO::write_solution (const std::string & fname, const std::vector< Number > * soln = nullptr, const std::vector< std::string > * names = nullptr) private
This method implements writing a mesh with nodal data to a specified file where the nodal data and variable names are optionally provided. This will write an ASCII file.
Definition at line 59 of file gnuplot_io.C.
References _grid, _png_output, _title, libMesh::MeshBase::active_element_ptr_range(), axes_limits, data, libMesh::MeshOutput< MeshBase >::mesh(), libMesh::MeshOutput< MT >::mesh(), libMesh::MeshBase::mesh_dimension(), libMesh::MeshBase::n_active_elem(), n_vars, libMesh::MeshBase::point(), and libMesh::Real.
Referenced by write(), and write_nodal_data().
 {
   // Even when writing on a serialized DistributedMesh, we expect
   // non-proc-0 help with calls like n_active_elem
   // libmesh_assert_equal_to (this->mesh().processor_id(), 0);
   const MeshBase & the_mesh = MeshOutput<MeshBase>::mesh();
   dof_id_type n_active_elem = the_mesh.n_active_elem();
   if (this->mesh().processor_id() == 0)
     {
       std::stringstream data_stream_name;
       data_stream_name << fname << "_data";
       const std::string data_file_name = data_stream_name.str();
       // This class is designed only for use with 1D meshes
       libmesh_assert_equal_to (the_mesh.mesh_dimension(), 1);
       // Make sure we have a solution to plot
       libmesh_assert ((names != nullptr) && (soln != nullptr));
       // Create an output stream for script file
       std::ofstream out_stream(fname.c_str());
       // Make sure it opened correctly
       if (!out_stream.good())
         libmesh_file_error(fname.c_str());
       // The number of variables in the equation system
       const unsigned int n_vars =
         cast_int<unsigned int>(names->size());
       // Write header to stream
       out_stream << "# This file was generated by gnuplot_io.C\n"
                  << "# Stores 1D solution data in GNUplot format\n"
                  << "# Execute this by loading gnuplot and typing "
                  << "\"call '" << fname << "'\"\n"
                  << "reset\n"
                  << "set title \"" << _title << "\"\n"
                  << "set xlabel \"x\"\n"
                  << "set xtics nomirror\n";
       // Loop over the elements to find the minimum and maximum x values,
       // and also to find the element boundaries to write out as xtics
       // if requested.
       Real x_min=0., x_max=0.;
       // construct string for xtic positions at element edges
       std::stringstream xtics_stream;
       unsigned int count = 0;
       for (const auto & el : the_mesh.active_element_ptr_range())
         {
           // if el is the left edge of the mesh, print its left node position
           if (el->neighbor_ptr(0) == nullptr)
             {
               x_min = (el->point(0))(0);
               xtics_stream << "\"\" " << x_min << ", \\\n";
             }
           if (el->neighbor_ptr(1) == nullptr)
             {
               x_max = (el->point(1))(0);
             }
           xtics_stream << "\"\" " << (el->point(1))(0);
           if (count+1 != n_active_elem)
             {
               xtics_stream << ", \\\n";
             }
           count++;
         }
       out_stream << "set xrange [" << x_min << ":" << x_max << "]\n";
       if (_grid)
         out_stream << "set x2tics (" << xtics_stream.str() << ")\nset grid noxtics noytics x2tics\n";
       if (_png_output)
         {
           out_stream << "set terminal png\n";
           out_stream << "set output \"" << fname << ".png\"\n";
         }
       out_stream << "plot "
                  << axes_limits
                  << " \"" << data_file_name << "\" using 1:2 title \"" << (*names)[0]
                  << "\" with lines";
       if (n_vars > 1)
         {
           for (unsigned int i=1; i<n_vars; i++)
             {
               out_stream << ", \\\n\"" << data_file_name << "\" using 1:" << i+2
                          << " title \"" << (*names)[i] << "\" with lines";
             }
         }
       out_stream.close();
       // Create an output stream for data file
       std::ofstream data(data_file_name.c_str());
       if (!data.good())
         libmesh_error_msg("ERROR: opening output data file " << data_file_name);
       // get ordered nodal data using a map
       std::map<Real, std::vector<Number>> node_map;
       for (const auto & elem : the_mesh.active_element_ptr_range())
         for (const auto & node : elem->node_ref_range())
           {
             dof_id_type global_id = node.id();
             std::vector<Number> values;
             for (unsigned int c=0; c<n_vars; c++)
               values.push_back((*soln)[global_id*n_vars + c]);
             node_map[the_mesh.point(global_id)(0)] = values;
           }
       for (const auto & pr : node_map)
         {
           const std::vector<Number> & values = pr.second;
           data << pr.first << "\t";
           for (const auto & val : values)
             data << val << "\t";
           data << "\n";
         }
       data.close();
     }
 }
Member Data Documentation
_grid
bool libMesh::GnuPlotIO::_grid private
Definition at line 121 of file gnuplot_io.h.
Referenced by GnuPlotIO(), use_grid(), and write_solution().
_is_parallel_format
const bool libMesh::MeshOutput< MeshBase >::_is_parallel_format protected inherited
Flag specifying whether this format is parallel-capable. If this is false (default) I/O is only permitted when the mesh has been serialized.
Definition at line 159 of file mesh_output.h.
Referenced by libMesh::FroIO::write(), libMesh::PostscriptIO::write(), and libMesh::EnsightIO::write().
_png_output
bool libMesh::GnuPlotIO::_png_output private
Definition at line 122 of file gnuplot_io.h.
Referenced by GnuPlotIO(), set_png_output(), and write_solution().
_serial_only_needed_on_proc_0
const bool libMesh::MeshOutput< MeshBase >::_serial_only_needed_on_proc_0 protected inherited
Flag specifying whether this format can be written by only serializing the mesh to processor zero
If this is false (default) the mesh will be serialized to all processors
Definition at line 168 of file mesh_output.h.
_title
std::string libMesh::GnuPlotIO::_title private
Definition at line 119 of file gnuplot_io.h.
Referenced by set_title(), and write_solution().
axes_limits
std::string libMesh::GnuPlotIO::axes_limits
GNUplot automatically adjusts the x and y-axes of 2D plots to "zoom in" on the data. You can set this string to force GNUplot to maintain a fixed set of axes. Example: axes_limits = "[0:1] [0:1]" would force x and y to be plotted on the range 0<=x<=1 and 0<=y<=1 regardless of where the data lie.
Definition at line 107 of file gnuplot_io.h.
Referenced by write_solution().
The documentation for this class was generated from the following files:
gnuplot_io.h
gnuplot_io.C