libMesh: libMesh::TrilinosPreconditioner< T > Class Template Reference
SomeWebsiteLogo
libMesh::TrilinosPreconditioner< T > Class Template Reference
#include <trilinos_preconditioner.h>
Public Member Functions
TrilinosPreconditioner (const libMesh::Parallel::Communicator &comm)
virtual ~TrilinosPreconditioner ()
virtual void apply (const NumericVector< T > &x, NumericVector< T > &y) override
virtual void clear () override
virtual void init () override
void set_params (Teuchos::ParameterList &list)
Epetra_FECrsMatrix * mat ()
void set_preconditioner_type (const PreconditionerType &preconditioner_type)
void compute ()
bool initialized () const
virtual void setup ()
void set_matrix (SparseMatrix< Number > &mat)
PreconditionerType type () const
void set_type (const PreconditionerType pct)
const Parallel::Communicator & comm () const
processor_id_type n_processors () const
processor_id_type processor_id () const
Static Public Member Functions
static std::unique_ptr< Preconditioner< T > > build_preconditioner (const libMesh::Parallel::Communicator &comm, const SolverPackage solver_package=libMesh::default_solver_package())
static Preconditioner< T > * build (const libMesh::Parallel::Communicator &comm, const SolverPackage solver_package=libMesh::default_solver_package())
static std::string get_info ()
static void print_info (std::ostream &out=libMesh::out)
static unsigned int n_objects ()
static void enable_print_counter_info ()
static void disable_print_counter_info ()
Protected Types
typedef std::map< std::string, std::pair< unsigned int, unsigned int > > Counts
Protected Member Functions
virtual int SetUseTranspose (bool UseTranspose) override
virtual int Apply (const Epetra_MultiVector &X, Epetra_MultiVector &Y) const override
virtual int ApplyInverse (const Epetra_MultiVector &r, Epetra_MultiVector &z) const override
virtual double NormInf () const override
virtual const char * Label () const override
virtual bool UseTranspose () const override
virtual bool HasNormInf () const override
virtual const Epetra_Comm & Comm () const override
virtual const Epetra_Map & OperatorDomainMap () const override
virtual const Epetra_Map & OperatorRangeMap () const override
void increment_constructor_count (const std::string &name)
void increment_destructor_count (const std::string &name)
Protected Attributes
Epetra_Operator * _prec
Epetra_FECrsMatrix * _mat
Teuchos::ParameterList _param_list
SparseMatrix< T > * _matrix
PreconditionerType _preconditioner_type
bool _is_initialized
const Parallel::Communicator & _communicator
Static Protected Attributes
static Counts _counts
static Threads::atomic< unsigned int > _n_objects
static Threads::spin_mutex _mutex
static bool _enable_print_counter = true
Detailed Description
template<typename T>
class libMesh::TrilinosPreconditioner< T >
This class provides an interface to the suite of preconditioners available from Trilinos. All overridden virtual functions are documented in preconditioner.h.
Author
David Andrs
Date
2011
Definition at line 71 of file trilinos_preconditioner.h.
Member Typedef Documentation
Counts
typedef std::map<std::string, std::pair<unsigned int, unsigned int> > libMesh::ReferenceCounter::Counts protected inherited
Data structure to log the information. The log is identified by the class name.
Definition at line 117 of file reference_counter.h.
Constructor & Destructor Documentation
TrilinosPreconditioner()
template<typename T > libMesh::TrilinosPreconditioner< T >::TrilinosPreconditioner (const libMesh::Parallel::Communicator & comm) inline
Constructor. Initializes PetscPreconditioner data structures
Definition at line 151 of file trilinos_preconditioner.h.
                                                                                            :
   Preconditioner<T>(comm),
   _prec(nullptr),
   _mat(nullptr)
 {
 }
~TrilinosPreconditioner()
template<typename T > libMesh::TrilinosPreconditioner< T >::~TrilinosPreconditioner () inline virtual
Destructor.
Definition at line 162 of file trilinos_preconditioner.h.
 {
   this->clear ();
 }
Member Function Documentation
apply()
template<typename T > void libMesh::TrilinosPreconditioner< T >::apply (const NumericVector< T > & x, NumericVector< T > & y) override virtual
Computes the preconditioned vector y based on input vector x. This is usually done by solving to get the action of .
Implements libMesh::Preconditioner< T >.
Definition at line 49 of file trilinos_preconditioner.C.
 {
 }
Apply()
template<typename T > int libMesh::TrilinosPreconditioner< T >::Apply (const Epetra_MultiVector & X, Epetra_MultiVector & Y) const override protected virtual
Definition at line 198 of file trilinos_preconditioner.C.
 {
   return _prec->Apply(X, Y);
 }
ApplyInverse()
template<typename T > int libMesh::TrilinosPreconditioner< T >::ApplyInverse (const Epetra_MultiVector & r, Epetra_MultiVector & z) const override protected virtual
Definition at line 205 of file trilinos_preconditioner.C.
 {
   return _prec->ApplyInverse(r, z);
 }
build()
template<typename T > Preconditioner< T > * libMesh::Preconditioner< T >::build (const libMesh::Parallel::Communicator & comm, const SolverPackage solver_package = libMesh::default_solver_package()) static inherited
Builds a Preconditioner using the linear solver package specified by solver_package
Deprecated:
Use build_preconditioner() instead.
Definition at line 84 of file preconditioner.C.
 {
   // You should be calling build_preconditioner() instead.
   libmesh_deprecated();
   // Call the non-deprecated method
   std::unique_ptr<Preconditioner<T>> ptr =
     Preconditioner<T>::build_preconditioner(comm, solver_package);
   // Vaya con dios
   return ptr.release();
 }
build_preconditioner()
template<typename T > std::unique_ptr< Preconditioner< T > > libMesh::Preconditioner< T >::build_preconditioner (const libMesh::Parallel::Communicator & comm, const SolverPackage solver_package = libMesh::default_solver_package()) static inherited
Builds a Preconditioner using the linear solver package specified by solver_package, returning the result wrapped in a std::unique_ptr for safety.
Definition at line 46 of file preconditioner.C.
 {
   // Avoid unused parameter warnings when no solver packages are enabled.
   libmesh_ignore(comm);
   // Build and return the appropriate Preconditioner object.
   switch (solver_package)
     {
 #ifdef LIBMESH_HAVE_PETSC
     case PETSC_SOLVERS:
       {
         return libmesh_make_unique<PetscPreconditioner<T>>(comm);
       }
 #endif
 #ifdef LIBMESH_TRILINOS_HAVE_EPETRA
     case TRILINOS_SOLVERS:
       return libmesh_make_unique<TrilinosPreconditioner<T>>(comm);
 #endif
 #ifdef LIBMESH_HAVE_EIGEN
     case EIGEN_SOLVERS:
       return libmesh_make_unique<EigenPreconditioner<T>>(comm);
 #endif
     default:
       libmesh_error_msg("ERROR:  Unrecognized solver package: " << solver_package);
     }
 }
clear()
template<typename T> virtual void libMesh::TrilinosPreconditioner< T >::clear () inline override virtual
Release all memory and clear data structures.
Reimplemented from libMesh::Preconditioner< T >.
Definition at line 89 of file trilinos_preconditioner.h.
 {}
comm()
const Parallel::Communicator& libMesh::ParallelObject::comm () const inline inherited
Returns
A reference to the Parallel::Communicator object used by this mesh.
Definition at line 89 of file parallel_object.h.
References libMesh::ParallelObject::_communicator.
Referenced by libMesh::__libmesh_petsc_diff_solver_jacobian(), libMesh::__libmesh_petsc_diff_solver_monitor(), libMesh::__libmesh_petsc_diff_solver_residual(), libMesh::__libmesh_tao_equality_constraints(), libMesh::__libmesh_tao_equality_constraints_jacobian(), libMesh::__libmesh_tao_gradient(), libMesh::__libmesh_tao_hessian(), libMesh::__libmesh_tao_inequality_constraints(), libMesh::__libmesh_tao_inequality_constraints_jacobian(), libMesh::__libmesh_tao_objective(), libMesh::MeshRefinement::_coarsen_elements(), libMesh::ExactSolution::_compute_error(), libMesh::UniformRefinementEstimator::_estimate_error(), libMesh::BoundaryInfo::_find_id_maps(), libMesh::SlepcEigenSolver< T >::_petsc_shell_matrix_get_diagonal(), libMesh::PetscLinearSolver< T >::_petsc_shell_matrix_get_diagonal(), libMesh::SlepcEigenSolver< T >::_petsc_shell_matrix_mult(), libMesh::PetscLinearSolver< T >::_petsc_shell_matrix_mult(), libMesh::PetscLinearSolver< T >::_petsc_shell_matrix_mult_add(), libMesh::EquationSystems::_read_impl(), libMesh::MeshRefinement::_refine_elements(), libMesh::MeshRefinement::_smooth_flags(), libMesh::PetscDMWrapper::add_dofs_helper(), libMesh::PetscDMWrapper::add_dofs_to_section(), libMesh::ImplicitSystem::add_matrix(), libMesh::System::add_vector(), libMesh::UnstructuredMesh::all_second_order(), libMesh::MeshTools::Modification::all_tri(), libMesh::LaplaceMeshSmoother::allgather_graph(), libMesh::FEMSystem::assemble_qoi(), libMesh::MeshCommunication::assign_global_indices(), libMesh::DofMap::attach_matrix(), libMesh::MeshTools::Generation::build_extrusion(), libMesh::BoundaryInfo::build_node_list_from_side_list(), libMesh::EquationSystems::build_parallel_elemental_solution_vector(), libMesh::EquationSystems::build_parallel_solution_vector(), libMesh::PetscDMWrapper::build_section(), libMesh::PetscDMWrapper::build_sf(), libMesh::MeshBase::cache_elem_dims(), libMesh::System::calculate_norm(), libMesh::DofMap::check_dirichlet_bcid_consistency(), libMesh::PetscDMWrapper::check_section_n_dofs(), libMesh::Nemesis_IO_Helper::compute_num_global_elem_blocks(), libMesh::Nemesis_IO_Helper::compute_num_global_nodesets(), libMesh::Nemesis_IO_Helper::compute_num_global_sidesets(), libMesh::Problem_Interface::computeF(), libMesh::Problem_Interface::computeJacobian(), libMesh::Problem_Interface::computePreconditioner(), libMesh::ExodusII_IO::copy_elemental_solution(), libMesh::MeshTools::correct_node_proc_ids(), libMesh::MeshTools::create_bounding_box(), libMesh::MeshTools::create_nodal_bounding_box(), libMesh::MeshRefinement::create_parent_error_vector(), libMesh::MeshTools::create_processor_bounding_box(), libMesh::MeshTools::create_subdomain_bounding_box(), libMesh::MeshCommunication::delete_remote_elements(), libMesh::DofMap::distribute_dofs(), DMlibMeshFunction(), DMlibMeshJacobian(), DMlibMeshSetSystem_libMesh(), DMVariableBounds_libMesh(), libMesh::MeshRefinement::eliminate_unrefined_patches(), libMesh::EpetraVector< T >::EpetraVector(), libMesh::WeightedPatchRecoveryErrorEstimator::estimate_error(), libMesh::PatchRecoveryErrorEstimator::estimate_error(), libMesh::JumpErrorEstimator::estimate_error(), libMesh::AdjointRefinementEstimator::estimate_error(), libMesh::ExactErrorEstimator::estimate_error(), libMesh::MeshRefinement::flag_elements_by_elem_fraction(), libMesh::MeshRefinement::flag_elements_by_error_fraction(), libMesh::MeshRefinement::flag_elements_by_nelem_target(), libMesh::CondensedEigenSystem::get_eigenpair(), libMesh::DofMap::get_info(), libMesh::ImplicitSystem::get_linear_solver(), libMesh::LocationMap< T >::init(), libMesh::TimeSolver::init(), libMesh::SystemSubsetBySubdomain::init(), libMesh::PetscDMWrapper::init_and_attach_petscdm(), libMesh::EigenSystem::init_data(), libMesh::EigenSystem::init_matrices(), libMesh::OptimizationSystem::initialize_equality_constraints_storage(), libMesh::OptimizationSystem::initialize_inequality_constraints_storage(), libMesh::MeshTools::libmesh_assert_consistent_distributed(), libMesh::MeshTools::libmesh_assert_consistent_distributed_nodes(), libMesh::MeshTools::libmesh_assert_contiguous_dof_ids(), libMesh::MeshTools::libmesh_assert_parallel_consistent_new_node_procids(), libMesh::MeshTools::libmesh_assert_parallel_consistent_procids< Elem >(), libMesh::MeshTools::libmesh_assert_parallel_consistent_procids< Node >(), libMesh::MeshTools::libmesh_assert_topology_consistent_procids< Node >(), libMesh::MeshTools::libmesh_assert_valid_boundary_ids(), libMesh::MeshTools::libmesh_assert_valid_dof_ids(), libMesh::MeshTools::libmesh_assert_valid_neighbors(), libMesh::DistributedMesh::libmesh_assert_valid_parallel_flags(), libMesh::DistributedMesh::libmesh_assert_valid_parallel_object_ids(), libMesh::DistributedMesh::libmesh_assert_valid_parallel_p_levels(), libMesh::MeshTools::libmesh_assert_valid_refinement_flags(), libMesh::MeshTools::libmesh_assert_valid_unique_ids(), libMesh::libmesh_petsc_snes_fd_residual(), libMesh::libmesh_petsc_snes_jacobian(), libMesh::libmesh_petsc_snes_mffd_residual(), libMesh::libmesh_petsc_snes_postcheck(), libMesh::libmesh_petsc_snes_residual(), libMesh::libmesh_petsc_snes_residual_helper(), libMesh::MeshRefinement::limit_level_mismatch_at_edge(), libMesh::MeshRefinement::limit_level_mismatch_at_node(), libMesh::MeshRefinement::limit_overrefined_boundary(), libMesh::MeshRefinement::limit_underrefined_boundary(), libMesh::MeshRefinement::make_coarsening_compatible(), libMesh::MeshCommunication::make_elems_parallel_consistent(), libMesh::MeshRefinement::make_flags_parallel_consistent(), libMesh::MeshCommunication::make_new_node_proc_ids_parallel_consistent(), libMesh::MeshCommunication::make_new_nodes_parallel_consistent(), libMesh::MeshCommunication::make_node_ids_parallel_consistent(), libMesh::MeshCommunication::make_node_proc_ids_parallel_consistent(), libMesh::MeshCommunication::make_node_unique_ids_parallel_consistent(), libMesh::MeshCommunication::make_nodes_parallel_consistent(), libMesh::MeshCommunication::make_p_levels_parallel_consistent(), libMesh::MeshRefinement::make_refinement_compatible(), libMesh::FEMSystem::mesh_position_set(), libMesh::DistributedMesh::n_active_elem(), libMesh::MeshTools::n_active_levels(), libMesh::BoundaryInfo::n_boundary_conds(), libMesh::BoundaryInfo::n_edge_conds(), libMesh::CondensedEigenSystem::n_global_non_condensed_dofs(), libMesh::MeshTools::n_levels(), libMesh::BoundaryInfo::n_nodeset_conds(), libMesh::MeshTools::n_p_levels(), libMesh::BoundaryInfo::n_shellface_conds(), libMesh::DistributedMesh::parallel_max_elem_id(), libMesh::DistributedMesh::parallel_max_node_id(), libMesh::ReplicatedMesh::parallel_max_unique_id(), libMesh::DistributedMesh::parallel_max_unique_id(), libMesh::DistributedMesh::parallel_n_elem(), libMesh::DistributedMesh::parallel_n_nodes(), libMesh::SparsityPattern::Build::parallel_sync(), libMesh::MeshTools::paranoid_n_levels(), libMesh::petsc_auto_fieldsplit(), libMesh::System::point_gradient(), libMesh::System::point_hessian(), libMesh::System::point_value(), libMesh::MeshBase::prepare_for_use(), libMesh::Nemesis_IO::read(), libMesh::XdrIO::read(), libMesh::CheckpointIO::read_header(), libMesh::XdrIO::read_header(), libMesh::System::read_header(), libMesh::System::read_legacy_data(), libMesh::System::read_SCALAR_dofs(), libMesh::XdrIO::read_serialized_bc_names(), libMesh::XdrIO::read_serialized_bcs_helper(), libMesh::System::read_serialized_blocked_dof_objects(), libMesh::XdrIO::read_serialized_connectivity(), libMesh::XdrIO::read_serialized_nodes(), libMesh::XdrIO::read_serialized_nodesets(), libMesh::XdrIO::read_serialized_subdomain_names(), libMesh::System::read_serialized_vector(), libMesh::MeshBase::recalculate_n_partitions(), libMesh::MeshRefinement::refine_and_coarsen_elements(), libMesh::DistributedMesh::renumber_dof_objects(), libMesh::CheckpointIO::select_split_config(), libMesh::DofMap::set_nonlocal_dof_objects(), libMesh::PetscDMWrapper::set_point_range_in_section(), libMesh::PetscDiffSolver::setup_petsc_data(), libMesh::LaplaceMeshSmoother::smooth(), libMesh::split_mesh(), libMesh::MeshBase::subdomain_ids(), libMesh::BoundaryInfo::sync(), libMesh::MeshRefinement::test_level_one(), libMesh::MeshRefinement::test_unflagged(), libMesh::MeshTools::total_weight(), libMesh::MeshRefinement::uniformly_coarsen(), libMesh::NameBasedIO::write(), libMesh::XdrIO::write(), libMesh::System::write_SCALAR_dofs(), libMesh::XdrIO::write_serialized_bcs_helper(), libMesh::System::write_serialized_blocked_dof_objects(), libMesh::XdrIO::write_serialized_connectivity(), libMesh::XdrIO::write_serialized_nodes(), and libMesh::XdrIO::write_serialized_nodesets().
   { return _communicator; }
Comm()
template<typename T > const Epetra_Comm & libMesh::TrilinosPreconditioner< T >::Comm () const override protected virtual
Definition at line 240 of file trilinos_preconditioner.C.
 {
   return _prec->Comm();
 }
compute()
template<typename T > void libMesh::TrilinosPreconditioner< T >::compute ()
Compute the preconditioner. In Trilinos, we need to call this explicitly.
Definition at line 86 of file trilinos_preconditioner.C.
References libMesh::AMG_PRECOND, libMesh::ILU_PRECOND, and libMesh::SOR_PRECOND.
Referenced by libMesh::Problem_Interface::computePreconditioner().
 {
 #ifdef LIBMESH_TRILINOS_HAVE_IFPACK
   Ifpack_Preconditioner * ifpack = nullptr;
 #endif
 #ifdef LIBMESH_TRILINOS_HAVE_ML
   ML_Epetra::MultiLevelPreconditioner * ml = nullptr;
 #endif
   switch (this->_preconditioner_type)
     {
 #ifdef LIBMESH_TRILINOS_HAVE_IFPACK
       // IFPACK preconditioners
     case ILU_PRECOND:
     case SOR_PRECOND:
       ifpack = dynamic_cast<Ifpack_Preconditioner *>(_prec);
       ifpack->Compute();
       break;
 #endif
 #ifdef LIBMESH_TRILINOS_HAVE_ML
       // ML preconditioners
     case AMG_PRECOND:
       ml = dynamic_cast<ML_Epetra::MultiLevelPreconditioner *>(_prec);
       ml->ComputePreconditioner();
       break;
 #endif
     default:
       // If we made it here, there were no TrilinosPreconditioners
       // active, so that's probably an error.
       libmesh_error_msg("ERROR: No valid TrilinosPreconditioners available!");
       break;
     }
 }
disable_print_counter_info()
void libMesh::ReferenceCounter::disable_print_counter_info () static inherited
Definition at line 106 of file reference_counter.C.
References libMesh::ReferenceCounter::_enable_print_counter.
Referenced by libMesh::LibMeshInit::LibMeshInit().
 {
   _enable_print_counter = false;
   return;
 }
enable_print_counter_info()
void libMesh::ReferenceCounter::enable_print_counter_info () static inherited
Methods to enable/disable the reference counter output from print_info()
Definition at line 100 of file reference_counter.C.
References libMesh::ReferenceCounter::_enable_print_counter.
 {
   _enable_print_counter = true;
   return;
 }
get_info()
std::string libMesh::ReferenceCounter::get_info () static inherited
Gets a string containing the reference information.
Definition at line 47 of file reference_counter.C.
References libMesh::ReferenceCounter::_counts, and libMesh::Quality::name().
Referenced by libMesh::ReferenceCounter::print_info().
 {
 #if defined(LIBMESH_ENABLE_REFERENCE_COUNTING) && defined(DEBUG)
   std::ostringstream oss;
   oss << '\n'
       << " ---------------------------------------------------------------------------- \n"
       << "| Reference count information                                                |\n"
       << " ---------------------------------------------------------------------------- \n";
   for (const auto & pr : _counts)
     {
       const std::string name(pr.first);
       const unsigned int creations    = pr.second.first;
       const unsigned int destructions = pr.second.second;
       oss << "| " << name << " reference count information:\n"
           << "|  Creations:    " << creations    << '\n'
           << "|  Destructions: " << destructions << '\n';
     }
   oss << " ---------------------------------------------------------------------------- \n";
   return oss.str();
 #else
   return "";
 #endif
 }
HasNormInf()
template<typename T > bool libMesh::TrilinosPreconditioner< T >::HasNormInf () const override protected virtual
Definition at line 233 of file trilinos_preconditioner.C.
 {
   return _prec->HasNormInf();
 }
increment_constructor_count()
void libMesh::ReferenceCounter::increment_constructor_count (const std::string & name) inline protected inherited
Increments the construction counter. Should be called in the constructor of any derived class that will be reference counted.
Definition at line 181 of file reference_counter.h.
References libMesh::ReferenceCounter::_counts, libMesh::Quality::name(), and libMesh::Threads::spin_mtx.
Referenced by libMesh::ReferenceCountedObject< RBParametrized >::ReferenceCountedObject().
 {
   Threads::spin_mutex::scoped_lock lock(Threads::spin_mtx);
   std::pair<unsigned int, unsigned int> & p = _counts[name];
   p.first++;
 }
increment_destructor_count()
void libMesh::ReferenceCounter::increment_destructor_count (const std::string & name) inline protected inherited
Increments the destruction counter. Should be called in the destructor of any derived class that will be reference counted.
Definition at line 194 of file reference_counter.h.
References libMesh::ReferenceCounter::_counts, libMesh::Quality::name(), and libMesh::Threads::spin_mtx.
Referenced by libMesh::ReferenceCountedObject< RBParametrized >::~ReferenceCountedObject().
 {
   Threads::spin_mutex::scoped_lock lock(Threads::spin_mtx);
   std::pair<unsigned int, unsigned int> & p = _counts[name];
   p.second++;
 }
init()
template<typename T > void libMesh::TrilinosPreconditioner< T >::init () override virtual
Initialize data structures if not done so already.
Note
This MUST be called before the preconditioning object is used.
Reimplemented from libMesh::Preconditioner< T >.
Definition at line 58 of file trilinos_preconditioner.C.
References libMesh::libMeshPrivateData::_is_initialized, and libMesh::EpetraMatrix< T >::mat().
 {
   if (!this->_matrix)
     libmesh_error_msg("ERROR: No matrix set for PetscPreconditioner, but init() called");
   // Clear the preconditioner in case it has been created in the past
   if (!this->_is_initialized)
     {
       EpetraMatrix<T> * matrix = cast_ptr<EpetraMatrix<T> *, SparseMatrix<T>>(this->_matrix);
       _mat = matrix->mat();
     }
   set_preconditioner_type(this->_preconditioner_type);
   this->_is_initialized = true;
 }
initialized()
template<typename T> bool libMesh::Preconditioner< T >::initialized () const inline inherited
Returns
true if the data structures are initialized, false otherwise.
Definition at line 106 of file preconditioner.h.
 { return _is_initialized; }
Label()
template<typename T > const char * libMesh::TrilinosPreconditioner< T >::Label () const override protected virtual
Definition at line 219 of file trilinos_preconditioner.C.
 {
   return _prec->Label();
 }
mat()
template<typename T> Epetra_FECrsMatrix* libMesh::TrilinosPreconditioner< T >::mat () inline
Returns
The actual Trilinos preconditioner object.
Definition at line 101 of file trilinos_preconditioner.h.
References libMesh::TrilinosPreconditioner< T >::_mat.
Referenced by libMesh::Problem_Interface::computePreconditioner().
 { return _mat; }
n_objects()
static unsigned int libMesh::ReferenceCounter::n_objects () inline static inherited
Prints the number of outstanding (created, but not yet destroyed) objects.
Definition at line 83 of file reference_counter.h.
References libMesh::ReferenceCounter::_n_objects.
   { return _n_objects; }
n_processors()
processor_id_type libMesh::ParallelObject::n_processors () const inline inherited
Returns
The number of processors in the group.
Definition at line 95 of file parallel_object.h.
References libMesh::ParallelObject::_communicator, and libMesh::Parallel::Communicator::size().
Referenced by libMesh::BoundaryInfo::_find_id_maps(), libMesh::PetscDMWrapper::add_dofs_to_section(), libMesh::DistributedMesh::add_elem(), libMesh::DistributedMesh::add_node(), libMesh::LaplaceMeshSmoother::allgather_graph(), libMesh::FEMSystem::assembly(), libMesh::AztecLinearSolver< T >::AztecLinearSolver(), libMesh::BoundaryInfo::build_node_list_from_side_list(), libMesh::EquationSystems::build_parallel_elemental_solution_vector(), libMesh::DistributedMesh::clear(), libMesh::Nemesis_IO_Helper::compute_border_node_ids(), libMesh::Nemesis_IO_Helper::construct_nemesis_filename(), libMesh::UnstructuredMesh::create_pid_mesh(), libMesh::MeshTools::create_processor_bounding_box(), libMesh::DofMap::distribute_dofs(), libMesh::DofMap::distribute_local_dofs_node_major(), libMesh::DofMap::distribute_local_dofs_var_major(), libMesh::EnsightIO::EnsightIO(), libMesh::MeshBase::get_info(), libMesh::SystemSubsetBySubdomain::init(), libMesh::PetscDMWrapper::init_and_attach_petscdm(), libMesh::Nemesis_IO_Helper::initialize(), libMesh::DistributedMesh::insert_elem(), libMesh::MeshTools::libmesh_assert_contiguous_dof_ids(), libMesh::MeshTools::libmesh_assert_parallel_consistent_new_node_procids(), libMesh::MeshTools::libmesh_assert_parallel_consistent_procids< Elem >(), libMesh::MeshTools::libmesh_assert_parallel_consistent_procids< Node >(), libMesh::MeshTools::libmesh_assert_topology_consistent_procids< Node >(), libMesh::MeshTools::libmesh_assert_valid_boundary_ids(), libMesh::MeshTools::libmesh_assert_valid_dof_ids(), libMesh::MeshTools::libmesh_assert_valid_neighbors(), libMesh::MeshTools::libmesh_assert_valid_refinement_flags(), libMesh::DofMap::local_variable_indices(), libMesh::MeshRefinement::make_coarsening_compatible(), libMesh::MeshBase::n_active_elem_on_proc(), libMesh::MeshBase::n_elem_on_proc(), libMesh::MeshBase::n_nodes_on_proc(), libMesh::MeshBase::partition(), libMesh::PetscLinearSolver< T >::PetscLinearSolver(), libMesh::System::point_gradient(), libMesh::System::point_hessian(), libMesh::System::point_value(), libMesh::NameBasedIO::read(), libMesh::Nemesis_IO::read(), libMesh::CheckpointIO::read(), libMesh::CheckpointIO::read_connectivity(), libMesh::XdrIO::read_header(), libMesh::CheckpointIO::read_nodes(), libMesh::System::read_parallel_data(), libMesh::System::read_SCALAR_dofs(), libMesh::System::read_serialized_blocked_dof_objects(), libMesh::System::read_serialized_vector(), libMesh::DistributedMesh::renumber_dof_objects(), libMesh::DofMap::set_nonlocal_dof_objects(), libMesh::PetscDMWrapper::set_point_range_in_section(), libMesh::MeshRefinement::uniformly_coarsen(), libMesh::DistributedMesh::update_parallel_id_counts(), libMesh::GMVIO::write_binary(), libMesh::GMVIO::write_discontinuous_gmv(), libMesh::System::write_parallel_data(), libMesh::System::write_SCALAR_dofs(), libMesh::XdrIO::write_serialized_bcs_helper(), libMesh::System::write_serialized_blocked_dof_objects(), libMesh::XdrIO::write_serialized_connectivity(), libMesh::XdrIO::write_serialized_nodes(), and libMesh::XdrIO::write_serialized_nodesets().
   { return cast_int<processor_id_type>(_communicator.size()); }
NormInf()
template<typename T > double libMesh::TrilinosPreconditioner< T >::NormInf () const override protected virtual
Definition at line 212 of file trilinos_preconditioner.C.
 {
   return _prec->NormInf();
 }
OperatorDomainMap()
template<typename T > const Epetra_Map & libMesh::TrilinosPreconditioner< T >::OperatorDomainMap () const override protected virtual
Definition at line 247 of file trilinos_preconditioner.C.
 {
   return _prec->OperatorDomainMap();
 }
OperatorRangeMap()
template<typename T > const Epetra_Map & libMesh::TrilinosPreconditioner< T >::OperatorRangeMap () const override protected virtual
Definition at line 254 of file trilinos_preconditioner.C.
 {
   return _prec->OperatorRangeMap();
 }
print_info()
void libMesh::ReferenceCounter::print_info (std::ostream & out = libMesh::out) static inherited
Prints the reference information, by default to libMesh::out.
Definition at line 87 of file reference_counter.C.
References libMesh::ReferenceCounter::_enable_print_counter, and libMesh::ReferenceCounter::get_info().
 {
   if (_enable_print_counter)
     out_stream << ReferenceCounter::get_info();
 }
processor_id()
processor_id_type libMesh::ParallelObject::processor_id () const inline inherited
Returns
The rank of this processor in the group.
Definition at line 101 of file parallel_object.h.
References libMesh::ParallelObject::_communicator, and libMesh::Parallel::Communicator::rank().
Referenced by libMesh::BoundaryInfo::_find_id_maps(), libMesh::EquationSystems::_read_impl(), libMesh::PetscDMWrapper::add_dofs_to_section(), libMesh::DistributedMesh::add_elem(), libMesh::BoundaryInfo::add_elements(), libMesh::DofMap::add_neighbors_to_send_list(), libMesh::DistributedMesh::add_node(), libMesh::UnstructuredMesh::all_second_order(), libMesh::MeshTools::Modification::all_tri(), libMesh::FEMSystem::assembly(), libMesh::EquationSystems::build_discontinuous_solution_vector(), libMesh::Nemesis_IO_Helper::build_element_and_node_maps(), libMesh::InfElemBuilder::build_inf_elem(), libMesh::BoundaryInfo::build_node_list_from_side_list(), libMesh::EquationSystems::build_parallel_elemental_solution_vector(), libMesh::DistributedMesh::clear(), libMesh::ExodusII_IO_Helper::close(), libMesh::Nemesis_IO_Helper::compute_border_node_ids(), libMesh::Nemesis_IO_Helper::compute_communication_map_parameters(), libMesh::Nemesis_IO_Helper::compute_internal_and_border_elems_and_internal_nodes(), libMesh::Nemesis_IO_Helper::compute_node_communication_maps(), libMesh::Nemesis_IO_Helper::compute_num_global_elem_blocks(), libMesh::Nemesis_IO_Helper::compute_num_global_nodesets(), libMesh::Nemesis_IO_Helper::compute_num_global_sidesets(), libMesh::Nemesis_IO_Helper::construct_nemesis_filename(), libMesh::MeshTools::correct_node_proc_ids(), libMesh::ExodusII_IO_Helper::create(), libMesh::DistributedMesh::delete_elem(), libMesh::DistributedMesh::delete_node(), libMesh::MeshCommunication::delete_remote_elements(), libMesh::DofMap::distribute_dofs(), libMesh::DofMap::distribute_local_dofs_node_major(), libMesh::DofMap::distribute_local_dofs_var_major(), libMesh::DistributedMesh::DistributedMesh(), libMesh::DofMap::end_dof(), libMesh::DofMap::end_old_dof(), libMesh::EnsightIO::EnsightIO(), libMesh::MeshFunction::find_element(), libMesh::MeshFunction::find_elements(), libMesh::UnstructuredMesh::find_neighbors(), libMesh::DofMap::first_dof(), libMesh::DofMap::first_old_dof(), libMesh::Nemesis_IO_Helper::get_cmap_params(), libMesh::Nemesis_IO_Helper::get_eb_info_global(), libMesh::Nemesis_IO_Helper::get_elem_cmap(), libMesh::Nemesis_IO_Helper::get_elem_map(), libMesh::MeshBase::get_info(), libMesh::DofMap::get_info(), libMesh::Nemesis_IO_Helper::get_init_global(), libMesh::Nemesis_IO_Helper::get_init_info(), libMesh::Nemesis_IO_Helper::get_loadbal_param(), libMesh::Nemesis_IO_Helper::get_node_cmap(), libMesh::Nemesis_IO_Helper::get_node_map(), libMesh::Nemesis_IO_Helper::get_ns_param_global(), libMesh::Nemesis_IO_Helper::get_ss_param_global(), libMesh::SparsityPattern::Build::handle_vi_vj(), libMesh::SystemSubsetBySubdomain::init(), libMesh::ExodusII_IO_Helper::initialize(), libMesh::ExodusII_IO_Helper::initialize_element_variables(), libMesh::ExodusII_IO_Helper::initialize_global_variables(), libMesh::ExodusII_IO_Helper::initialize_nodal_variables(), libMesh::DistributedMesh::insert_elem(), libMesh::DofMap::is_evaluable(), libMesh::SparsityPattern::Build::join(), libMesh::DofMap::last_dof(), libMesh::MeshTools::libmesh_assert_consistent_distributed(), libMesh::MeshTools::libmesh_assert_consistent_distributed_nodes(), libMesh::MeshTools::libmesh_assert_contiguous_dof_ids(), libMesh::MeshTools::libmesh_assert_parallel_consistent_procids< Elem >(), libMesh::MeshTools::libmesh_assert_valid_neighbors(), libMesh::DistributedMesh::libmesh_assert_valid_parallel_object_ids(), libMesh::DofMap::local_variable_indices(), libMesh::MeshRefinement::make_coarsening_compatible(), libMesh::MeshBase::n_active_local_elem(), libMesh::BoundaryInfo::n_boundary_conds(), libMesh::BoundaryInfo::n_edge_conds(), libMesh::DofMap::n_local_dofs(), libMesh::System::n_local_dofs(), libMesh::MeshBase::n_local_elem(), libMesh::MeshBase::n_local_nodes(), libMesh::BoundaryInfo::n_nodeset_conds(), libMesh::BoundaryInfo::n_shellface_conds(), libMesh::SparsityPattern::Build::operator()(), libMesh::DistributedMesh::own_node(), libMesh::System::point_gradient(), libMesh::System::point_hessian(), libMesh::System::point_value(), libMesh::Nemesis_IO_Helper::put_cmap_params(), libMesh::Nemesis_IO_Helper::put_elem_cmap(), libMesh::Nemesis_IO_Helper::put_elem_map(), libMesh::Nemesis_IO_Helper::put_loadbal_param(), libMesh::Nemesis_IO_Helper::put_node_cmap(), libMesh::Nemesis_IO_Helper::put_node_map(), libMesh::NameBasedIO::read(), libMesh::Nemesis_IO::read(), libMesh::XdrIO::read(), libMesh::CheckpointIO::read(), libMesh::ExodusII_IO_Helper::read_elem_num_map(), libMesh::ExodusII_IO_Helper::read_global_values(), libMesh::CheckpointIO::read_header(), libMesh::XdrIO::read_header(), libMesh::System::read_header(), libMesh::System::read_legacy_data(), libMesh::ExodusII_IO_Helper::read_node_num_map(), libMesh::System::read_parallel_data(), libMesh::System::read_SCALAR_dofs(), libMesh::XdrIO::read_serialized_bc_names(), libMesh::XdrIO::read_serialized_bcs_helper(), libMesh::System::read_serialized_blocked_dof_objects(), libMesh::XdrIO::read_serialized_connectivity(), libMesh::System::read_serialized_data(), libMesh::XdrIO::read_serialized_nodes(), libMesh::XdrIO::read_serialized_nodesets(), libMesh::XdrIO::read_serialized_subdomain_names(), libMesh::System::read_serialized_vector(), libMesh::System::read_serialized_vectors(), libMesh::DistributedMesh::renumber_dof_objects(), libMesh::CheckpointIO::select_split_config(), libMesh::DofMap::set_nonlocal_dof_objects(), libMesh::PetscDMWrapper::set_point_range_in_section(), libMesh::LaplaceMeshSmoother::smooth(), libMesh::MeshTools::total_weight(), libMesh::MeshRefinement::uniformly_coarsen(), libMesh::Parallel::Packing< T >::unpack(), libMesh::DistributedMesh::update_parallel_id_counts(), libMesh::NameBasedIO::write(), libMesh::XdrIO::write(), libMesh::CheckpointIO::write(), libMesh::EquationSystems::write(), libMesh::GMVIO::write_discontinuous_gmv(), libMesh::ExodusII_IO::write_element_data(), libMesh::ExodusII_IO_Helper::write_element_values(), libMesh::ExodusII_IO_Helper::write_elements(), libMesh::ExodusII_IO::write_global_data(), libMesh::ExodusII_IO_Helper::write_global_values(), libMesh::System::write_header(), libMesh::ExodusII_IO::write_information_records(), libMesh::ExodusII_IO_Helper::write_information_records(), libMesh::ExodusII_IO_Helper::write_nodal_coordinates(), libMesh::UCDIO::write_nodal_data(), libMesh::ExodusII_IO::write_nodal_data(), libMesh::ExodusII_IO::write_nodal_data_discontinuous(), libMesh::ExodusII_IO_Helper::write_nodal_values(), libMesh::Nemesis_IO_Helper::write_nodesets(), libMesh::ExodusII_IO_Helper::write_nodesets(), libMesh::System::write_parallel_data(), libMesh::System::write_SCALAR_dofs(), libMesh::XdrIO::write_serialized_bc_names(), libMesh::XdrIO::write_serialized_bcs_helper(), libMesh::System::write_serialized_blocked_dof_objects(), libMesh::XdrIO::write_serialized_connectivity(), libMesh::System::write_serialized_data(), libMesh::XdrIO::write_serialized_nodes(), libMesh::XdrIO::write_serialized_nodesets(), libMesh::XdrIO::write_serialized_subdomain_names(), libMesh::System::write_serialized_vector(), libMesh::System::write_serialized_vectors(), libMesh::Nemesis_IO_Helper::write_sidesets(), libMesh::ExodusII_IO_Helper::write_sidesets(), libMesh::ExodusII_IO::write_timestep(), libMesh::ExodusII_IO_Helper::write_timestep(), and libMesh::ExodusII_IO::write_timestep_discontinuous().
   { return cast_int<processor_id_type>(_communicator.rank()); }
set_matrix()
template<typename T > void libMesh::Preconditioner< T >::set_matrix (SparseMatrix< Number > & mat) inherited
Sets the matrix to be preconditioned.
Definition at line 181 of file preconditioner.h.
 {
   //If the matrix is changing then we (probably) need to reinitialize.
   _is_initialized = false;
   _matrix = &mat;
 }
set_params()
template<typename T > void libMesh::TrilinosPreconditioner< T >::set_params (Teuchos::ParameterList & list)
Stores a copy of the ParameterList list internally.
Definition at line 78 of file trilinos_preconditioner.C.
 {
   _param_list = list;
 }
set_preconditioner_type()
template<typename T > void libMesh::TrilinosPreconditioner< T >::set_preconditioner_type (const PreconditionerType & preconditioner_type)
Sets the Trilinos preconditioner to use based on the libMesh PreconditionerType.
Note
Not all libMesh PreconditionerTypes are supported.
Definition at line 126 of file trilinos_preconditioner.C.
References libMesh::AMG_PRECOND, libMesh::ASM_PRECOND, libMesh::BLOCK_JACOBI_PRECOND, libMesh::CHOLESKY_PRECOND, libMesh::EISENSTAT_PRECOND, libMesh::ICC_PRECOND, libMesh::IDENTITY_PRECOND, libMesh::ILU_PRECOND, libMesh::JACOBI_PRECOND, libMesh::LU_PRECOND, and libMesh::SOR_PRECOND.
 {
 #ifdef LIBMESH_TRILINOS_HAVE_IFPACK
   Ifpack_Preconditioner * pc = nullptr;
 #endif
 #ifdef LIBMESH_TRILINOS_HAVE_ML
   ML_Epetra::MultiLevelPreconditioner * ml = nullptr;
 #endif
   switch (preconditioner_type)
     {
     case IDENTITY_PRECOND:
       //    pc = new Ifpack_DiagPreconditioner();
       break;
     case CHOLESKY_PRECOND:
       break;
     case ICC_PRECOND:
       break;
 #ifdef LIBMESH_TRILINOS_HAVE_IFPACK
     case ILU_PRECOND:
       pc = new Ifpack_ILU(_mat);
       pc->SetParameters(_param_list);
       pc->Initialize();
       _prec = pc;
       break;
 #endif
     case LU_PRECOND:
       break;
     case ASM_PRECOND:
       break;
     case JACOBI_PRECOND:
       break;
     case BLOCK_JACOBI_PRECOND:
       break;
     case SOR_PRECOND:
       break;
     case EISENSTAT_PRECOND:
       break;
 #ifdef LIBMESH_TRILINOS_HAVE_ML
     case AMG_PRECOND:
       ml = new ML_Epetra::MultiLevelPreconditioner(*_mat, _param_list, false);;
       _prec = ml;
       break;
 #endif
     default:
       libmesh_error_msg("ERROR:  Unsupported Trilinos Preconditioner: " << preconditioner_type << "\nContinuing with Trilinos defaults");
     }
 }
set_type()
template<typename T > void libMesh::Preconditioner< T >::set_type (const PreconditionerType pct) inherited
Sets the type of preconditioner to use.
Definition at line 190 of file preconditioner.h.
 {
   //If the preconditioner type changes we (probably) need to reinitialize.
   _is_initialized = false;
   _preconditioner_type = pct;
 }
setup()
template<typename T> virtual void libMesh::Preconditioner< T >::setup () inline virtual inherited
This is called every time the "operator might have changed".
This is where you need to fill in your preconditioning matrix.
Definition at line 132 of file preconditioner.h.
 {}
SetUseTranspose()
template<typename T > int libMesh::TrilinosPreconditioner< T >::SetUseTranspose (bool UseTranspose) override protected virtual
Definition at line 191 of file trilinos_preconditioner.C.
 {
   return _prec->SetUseTranspose(UseTranspose);
 }
type()
template<typename T> PreconditionerType libMesh::Preconditioner< T >::type () const inline inherited
Returns
The type of preconditioner to use.
Definition at line 142 of file preconditioner.h.
 { return _preconditioner_type; }
UseTranspose()
template<typename T > bool libMesh::TrilinosPreconditioner< T >::UseTranspose () const override protected virtual
Definition at line 226 of file trilinos_preconditioner.C.
 {
   return _prec->UseTranspose();
 }
Member Data Documentation
_communicator
const Parallel::Communicator& libMesh::ParallelObject::_communicator protected inherited
Definition at line 107 of file parallel_object.h.
Referenced by libMesh::EquationSystems::build_parallel_elemental_solution_vector(), libMesh::EquationSystems::build_parallel_solution_vector(), libMesh::ParallelObject::comm(), libMesh::ParallelObject::n_processors(), libMesh::ParallelObject::operator=(), and libMesh::ParallelObject::processor_id().
_counts
ReferenceCounter::Counts libMesh::ReferenceCounter::_counts static protected inherited
Actually holds the data.
Definition at line 122 of file reference_counter.h.
Referenced by libMesh::ReferenceCounter::get_info(), libMesh::ReferenceCounter::increment_constructor_count(), and libMesh::ReferenceCounter::increment_destructor_count().
_enable_print_counter
bool libMesh::ReferenceCounter::_enable_print_counter = true static protected inherited
Flag to control whether reference count information is printed when print_info is called.
Definition at line 141 of file reference_counter.h.
Referenced by libMesh::ReferenceCounter::disable_print_counter_info(), libMesh::ReferenceCounter::enable_print_counter_info(), and libMesh::ReferenceCounter::print_info().
_is_initialized
template<typename T> bool libMesh::Preconditioner< T >::_is_initialized protected inherited
Flag indicating if the data structures have been initialized.
Definition at line 165 of file preconditioner.h.
Referenced by libMesh::Preconditioner< Number >::initialized().
_mat
template<typename T> Epetra_FECrsMatrix* libMesh::TrilinosPreconditioner< T >::_mat protected
Trilinos matrix that's been pulled out of the _matrix object.
Definition at line 125 of file trilinos_preconditioner.h.
Referenced by libMesh::TrilinosPreconditioner< T >::mat().
_matrix
template<typename T> SparseMatrix<T>* libMesh::Preconditioner< T >::_matrix protected inherited
The matrix P... ie the matrix to be preconditioned. This is often the actual system matrix of a linear system.
Definition at line 155 of file preconditioner.h.
_mutex
Threads::spin_mutex libMesh::ReferenceCounter::_mutex static protected inherited
Mutual exclusion object to enable thread-safe reference counting.
Definition at line 135 of file reference_counter.h.
_n_objects
Threads::atomic< unsigned int > libMesh::ReferenceCounter::_n_objects static protected inherited
The number of objects. Print the reference count information when the number returns to 0.
Definition at line 130 of file reference_counter.h.
Referenced by libMesh::ReferenceCounter::n_objects(), libMesh::ReferenceCounter::ReferenceCounter(), and libMesh::ReferenceCounter::~ReferenceCounter().
_param_list
template<typename T> Teuchos::ParameterList libMesh::TrilinosPreconditioner< T >::_param_list protected
Parameter list to be used for building the preconditioner.
Definition at line 130 of file trilinos_preconditioner.h.
_prec
template<typename T> Epetra_Operator* libMesh::TrilinosPreconditioner< T >::_prec protected
Trilinos preconditioner.
Definition at line 120 of file trilinos_preconditioner.h.
_preconditioner_type
template<typename T> PreconditionerType libMesh::Preconditioner< T >::_preconditioner_type protected inherited
Enum stating with type of preconditioner to use.
Definition at line 160 of file preconditioner.h.
Referenced by libMesh::Preconditioner< Number >::type().
The documentation for this class was generated from the following files:
trilinos_preconditioner.h
trilinos_preconditioner.C