libMesh: libMesh::EpetraVector< T > Class Template Reference
SomeWebsiteLogo
libMesh::EpetraVector< T > Class Template Reference
#include <trilinos_epetra_vector.h>
Public Member Functions
EpetraVector (const Parallel::Communicator &comm, const ParallelType type=AUTOMATIC)
EpetraVector (const Parallel::Communicator &comm, const numeric_index_type n, const ParallelType type=AUTOMATIC)
EpetraVector (const Parallel::Communicator &comm, const numeric_index_type n, const numeric_index_type n_local, const ParallelType type=AUTOMATIC)
EpetraVector (const Parallel::Communicator &comm, const numeric_index_type N, const numeric_index_type n_local, const std::vector< numeric_index_type > &ghost, const ParallelType type=AUTOMATIC)
EpetraVector (Epetra_Vector &v, const Parallel::Communicator &comm LIBMESH_CAN_DEFAULT_TO_COMMWORLD)
~EpetraVector ()
virtual void close () libmesh_override
virtual void clear () libmesh_override
virtual void zero () libmesh_override
virtual UniquePtr< NumericVector< T > > zero_clone () const libmesh_override
virtual UniquePtr< NumericVector< T > > clone () const libmesh_override
virtual void init (const numeric_index_type N, const numeric_index_type n_local, const bool fast=false, const ParallelType type=AUTOMATIC) libmesh_override
virtual void init (const numeric_index_type N, const bool fast=false, const ParallelType type=AUTOMATIC) libmesh_override
virtual void init (const numeric_index_type, const numeric_index_type, const std::vector< numeric_index_type > &, const bool=false, const ParallelType=AUTOMATIC) libmesh_override
virtual void init (const NumericVector< T > &other, const bool fast=false) libmesh_override
virtual NumericVector< T > & operator= (const T s) libmesh_override
virtual NumericVector< T > & operator= (const NumericVector< T > &v) libmesh_override
EpetraVector< T > & operator= (const EpetraVector< T > &v)
virtual NumericVector< T > & operator= (const std::vector< T > &v) libmesh_override
virtual Real min () const libmesh_override
virtual Real max () const libmesh_override
virtual T sum () const libmesh_override
virtual Real l1_norm () const libmesh_override
virtual Real l2_norm () const libmesh_override
virtual Real linfty_norm () const libmesh_override
virtual numeric_index_type size () const libmesh_override
virtual numeric_index_type local_size () const libmesh_override
virtual numeric_index_type first_local_index () const libmesh_override
virtual numeric_index_type last_local_index () const libmesh_override
virtual T operator() (const numeric_index_type i) const libmesh_override
virtual NumericVector< T > & operator+= (const NumericVector< T > &v) libmesh_override
virtual NumericVector< T > & operator-= (const NumericVector< T > &v) libmesh_override
virtual NumericVector< T > & operator/= (NumericVector< T > &v) libmesh_override
virtual void reciprocal () libmesh_override
virtual void conjugate () libmesh_override
virtual void set (const numeric_index_type i, const T value) libmesh_override
virtual void add (const numeric_index_type i, const T value) libmesh_override
virtual void add (const T s) libmesh_override
virtual void add (const NumericVector< T > &V) libmesh_override
virtual void add (const T a, const NumericVector< T > &v) libmesh_override
virtual void add_vector (const T *v, const std::vector< numeric_index_type > &dof_indices) libmesh_override
virtual void add_vector (const NumericVector< T > &v, const SparseMatrix< T > &A) libmesh_override
virtual void add_vector_transpose (const NumericVector< T > &v, const SparseMatrix< T > &A_trans) libmesh_override
virtual void insert (const T *v, const std::vector< numeric_index_type > &dof_indices) libmesh_override
virtual void scale (const T factor) libmesh_override
virtual void abs () libmesh_override
virtual T dot (const NumericVector< T > &V) const libmesh_override
virtual void localize (std::vector< T > &v_local) const libmesh_override
virtual void localize (NumericVector< T > &v_local) const libmesh_override
virtual void localize (NumericVector< T > &v_local, const std::vector< numeric_index_type > &send_list) const libmesh_override
virtual void localize (std::vector< T > &v_local, const std::vector< numeric_index_type > &indices) const libmesh_override
virtual void localize (const numeric_index_type first_local_idx, const numeric_index_type last_local_idx, const std::vector< numeric_index_type > &send_list) libmesh_override
virtual void localize_to_one (std::vector< T > &v_local, const processor_id_type proc_id=0) const libmesh_override
virtual void pointwise_mult (const NumericVector< T > &vec1, const NumericVector< T > &vec2) libmesh_override
virtual void create_subvector (NumericVector< T > &subvector, const std::vector< numeric_index_type > &rows) const libmesh_override
virtual void swap (NumericVector< T > &v) libmesh_override
Epetra_Vector * vec ()
virtual bool initialized () const
ParallelType type () const
ParallelType & type ()
virtual bool closed () const
virtual Real subset_l1_norm (const std::set< numeric_index_type > &indices) const
virtual Real subset_l2_norm (const std::set< numeric_index_type > &indices) const
virtual Real subset_linfty_norm (const std::set< numeric_index_type > &indices) const
virtual T el (const numeric_index_type i) const
virtual void get (const std::vector< numeric_index_type > &index, T *values) const
void get (const std::vector< numeric_index_type > &index, std::vector< T > &values) const
NumericVector< T > & operator*= (const T a)
NumericVector< T > & operator/= (const T a)
void add_vector (const std::vector< T > &v, const std::vector< numeric_index_type > &dof_indices)
virtual void add_vector (const NumericVector< T > &V, const std::vector< numeric_index_type > &dof_indices)
void add_vector (const DenseVector< T > &V, const std::vector< numeric_index_type > &dof_indices)
void add_vector (const NumericVector< T > &v, const ShellMatrix< T > &a)
void insert (const std::vector< T > &v, const std::vector< numeric_index_type > &dof_indices)
virtual void insert (const NumericVector< T > &V, const std::vector< numeric_index_type > &dof_indices)
void insert (const DenseVector< T > &V, const std::vector< numeric_index_type > &dof_indices)
void insert (const DenseSubVector< T > &V, const std::vector< numeric_index_type > &dof_indices)
virtual int compare (const NumericVector< T > &other_vector, const Real threshold=TOLERANCE) const
virtual int local_relative_compare (const NumericVector< T > &other_vector, const Real threshold=TOLERANCE) const
virtual int global_relative_compare (const NumericVector< T > &other_vector, const Real threshold=TOLERANCE) const
virtual void print (std::ostream &os=libMesh::out) const
template<>
void print (std::ostream &os) const
virtual void print_global (std::ostream &os=libMesh::out) const
template<>
void print_global (std::ostream &os) const
virtual void print_matlab (const std::string &="") const
const Parallel::Communicator & comm () const
processor_id_type n_processors () const
processor_id_type processor_id () const
Static Public Member Functions
static UniquePtr< NumericVector< T > > build (const Parallel::Communicator &comm, const SolverPackage solver_package=libMesh::default_solver_package())
static UniquePtr< NumericVector< T > > build (const SolverPackage solver_package=libMesh::default_solver_package())
static std::string get_info ()
static void print_info (std::ostream &out=libMesh::out)
static unsigned int n_objects ()
static void enable_print_counter_info ()
static void disable_print_counter_info ()
Protected Types
typedef std::map< std::string, std::pair< unsigned int, unsigned int > > Counts
Protected Member Functions
void increment_constructor_count (const std::string &name)
void increment_destructor_count (const std::string &name)
Protected Attributes
bool _is_closed
bool _is_initialized
ParallelType _type
const Parallel::Communicator & _communicator
Static Protected Attributes
static Counts _counts
static Threads::atomic< unsigned int > _n_objects
static Threads::spin_mutex _mutex
static bool _enable_print_counter = true
Private Member Functions
int SumIntoGlobalValues (int numIDs, const int *GIDs, const double *values)
int SumIntoGlobalValues (const Epetra_IntSerialDenseVector &GIDs, const Epetra_SerialDenseVector &values)
int ReplaceGlobalValues (int numIDs, const int *GIDs, const double *values)
int ReplaceGlobalValues (const Epetra_IntSerialDenseVector &GIDs, const Epetra_SerialDenseVector &values)
int SumIntoGlobalValues (int numIDs, const int *GIDs, const int *numValuesPerID, const double *values)
int ReplaceGlobalValues (int numIDs, const int *GIDs, const int *numValuesPerID, const double *values)
int GlobalAssemble (Epetra_CombineMode mode=Add)
void setIgnoreNonLocalEntries (bool flag)
void FEoperatorequals (const EpetraVector &source)
int inputValues (int numIDs, const int *GIDs, const double *values, bool accumulate)
int inputValues (int numIDs, const int *GIDs, const int *numValuesPerID, const double *values, bool accumulate)
int inputNonlocalValue (int GID, double value, bool accumulate)
int inputNonlocalValues (int GID, int numValues, const double *values, bool accumulate)
void destroyNonlocalData ()
Private Attributes
Epetra_Vector * _vec
UniquePtr< Epetra_Map > _map
bool _destroy_vec_on_exit
int myFirstID_
int myNumIDs_
double * myCoefs_
int * nonlocalIDs_
int * nonlocalElementSize_
int numNonlocalIDs_
int allocatedNonlocalLength_
double ** nonlocalCoefs_
unsigned char last_edit
bool ignoreNonLocalEntries_
Detailed Description
template<typename T>
class libMesh::EpetraVector< T >
Epetra vector. Provides a nice interface to the Trilinos Epetra data structures for parallel vectors.
Author
Derek R. Gaston
Date
2008
Definition at line 61 of file trilinos_epetra_vector.h.
Member Typedef Documentation
typedef std::map<std::string, std::pair<unsigned int, unsigned int> > libMesh::ReferenceCounter::Counts protected inherited
Data structure to log the information. The log is identified by the class name.
Definition at line 119 of file reference_counter.h.
Constructor & Destructor Documentation
template<typename T > libMesh::EpetraVector< T >::EpetraVector (const Parallel::Communicator & comm, const ParallelType type = AUTOMATIC) inline explicit
Dummy-Constructor. Dimension=0
Definition at line 612 of file trilinos_epetra_vector.h.
References libMesh::NumericVector< T >::_type, and libMesh::NumericVector< T >::type().
Referenced by libMesh::EpetraVector< T >::EpetraVector().
                                                         :
   NumericVector<T>(comm, type),
   _destroy_vec_on_exit(true),
   myFirstID_(0),
   myNumIDs_(0),
   myCoefs_(libmesh_nullptr),
   nonlocalIDs_(libmesh_nullptr),
   nonlocalElementSize_(libmesh_nullptr),
   numNonlocalIDs_(0),
   allocatedNonlocalLength_(0),
   nonlocalCoefs_(libmesh_nullptr),
   last_edit(0),
   ignoreNonLocalEntries_(false)
 {
   this->_type = type;
 }
template<typename T > libMesh::EpetraVector< T >::EpetraVector (const Parallel::Communicator & comm, const numeric_index_type n, const ParallelType type = AUTOMATIC) inline explicit
Constructor. Set dimension to n and initialize all elements with zero.
Definition at line 634 of file trilinos_epetra_vector.h.
References libMesh::EpetraVector< T >::init().
                                                         :
   NumericVector<T>(comm, type),
   _destroy_vec_on_exit(true),
   myFirstID_(0),
   myNumIDs_(0),
   myCoefs_(libmesh_nullptr),
   nonlocalIDs_(libmesh_nullptr),
   nonlocalElementSize_(libmesh_nullptr),
   numNonlocalIDs_(0),
   allocatedNonlocalLength_(0),
   nonlocalCoefs_(libmesh_nullptr),
   last_edit(0),
   ignoreNonLocalEntries_(false)
 {
   this->init(n, n, false, type);
 }
template<typename T > libMesh::EpetraVector< T >::EpetraVector (const Parallel::Communicator & comm, const numeric_index_type n, const numeric_index_type n_local, const ParallelType type = AUTOMATIC) inline
Constructor. Set local dimension to n_local, the global dimension to n, and initialize all elements with zero.
Definition at line 658 of file trilinos_epetra_vector.h.
References libMesh::EpetraVector< T >::_destroy_vec_on_exit, libMesh::NumericVector< T >::_is_closed, libMesh::NumericVector< T >::_is_initialized, libMesh::EpetraVector< T >::_map, libMesh::NumericVector< T >::_type, libMesh::EpetraVector< T >::_vec, libMesh::EpetraVector< T >::allocatedNonlocalLength_, libMesh::AUTOMATIC, libMesh::ParallelObject::comm(), libMesh::EpetraVector< T >::EpetraVector(), libMesh::EpetraVector< T >::ignoreNonLocalEntries_, libMesh::EpetraVector< T >::init(), libMesh::EpetraVector< T >::last_edit, libmesh_nullptr, libMesh::EpetraVector< T >::myCoefs_, libMesh::EpetraVector< T >::myFirstID_, libMesh::EpetraVector< T >::myNumIDs_, libMesh::EpetraVector< T >::nonlocalCoefs_, libMesh::EpetraVector< T >::nonlocalElementSize_, libMesh::EpetraVector< T >::nonlocalIDs_, libMesh::EpetraVector< T >::numNonlocalIDs_, and libMesh::PARALLEL.
                                                         :
   NumericVector<T>(comm, type),
   _destroy_vec_on_exit(true),
   myFirstID_(0),
   myNumIDs_(0),
   myCoefs_(libmesh_nullptr),
   nonlocalIDs_(libmesh_nullptr),
   nonlocalElementSize_(libmesh_nullptr),
   numNonlocalIDs_(0),
   allocatedNonlocalLength_(0),
   nonlocalCoefs_(libmesh_nullptr),
   last_edit(0),
   ignoreNonLocalEntries_(false)
 {
   this->init(n, n_local, false, type);
 }
template<typename T > libMesh::EpetraVector< T >::EpetraVector (const Parallel::Communicator & comm, const numeric_index_type N, const numeric_index_type n_local, const std::vector< numeric_index_type > & ghost, const ParallelType type = AUTOMATIC) inline
Constructor. Set local dimension to n_local, the global dimension to n, but additionally reserve memory for the indices specified by the ghost argument.
Definition at line 723 of file trilinos_epetra_vector.h.
References libMesh::EpetraVector< T >::init().
                                                         :
   NumericVector<T>(comm, AUTOMATIC),
   _destroy_vec_on_exit(true),
   myFirstID_(0),
   myNumIDs_(0),
   myCoefs_(libmesh_nullptr),
   nonlocalIDs_(libmesh_nullptr),
   nonlocalElementSize_(libmesh_nullptr),
   numNonlocalIDs_(0),
   allocatedNonlocalLength_(0),
   nonlocalCoefs_(libmesh_nullptr),
   last_edit(0),
   ignoreNonLocalEntries_(false)
 {
   this->init(n, n_local, ghost, false, type);
 }
template<typename T> libMesh::EpetraVector< T >::EpetraVector (Epetra_Vector & v, const Parallel::Communicator &comm LIBMESH_CAN_DEFAULT_TO_COMMWORLD)
Constructor. Creates a EpetraVector assuming you already have a valid Epetra Vec object. In this case, v is NOT destroyed by the EpetraVector constructor when this object goes out of scope. This allows ownership of v to remain with the original creator, and to simply provide additional functionality with the EpetraVector.
template<typename T > libMesh::EpetraVector< T >::~EpetraVector () inline
Destructor, deallocates memory. Made virtual to allow for derived classes to behave properly.
Definition at line 759 of file trilinos_epetra_vector.h.
References libMesh::EpetraVector< T >::clear().
 {
   this->clear ();
 }
Member Function Documentation
template<typename T > void libMesh::EpetraVector< T >::abs () virtual
v = abs(v)... that is, each entry in v is replaced by its absolute value.
Implements libMesh::NumericVector< T >.
Definition at line 305 of file trilinos_epetra_vector.C.
 {
   _vec->Abs(*_vec);
 }
template<typename T > void libMesh::EpetraVector< T >::add (const numeric_index_type i, const T value) virtual
v(i) += value
Implements libMesh::NumericVector< T >.
Definition at line 198 of file trilinos_epetra_vector.C.
 {
   int i = static_cast<int> (i_in);
   T value = value_in;
   libmesh_assert_less (i_in, this->size());
   SumIntoGlobalValues(1, &i, &value);
   this->_is_closed = false;
 }
template<typename T > void libMesh::EpetraVector< T >::add (const T s) virtual
. Addition of s to all components. Note that s is a scalar and not a vector.
Implements libMesh::NumericVector< T >.
Definition at line 253 of file trilinos_epetra_vector.C.
 {
   const unsigned int nl = _vec->MyLength();
   T * values = _vec->Values();
   for (unsigned int i=0; i<nl; i++)
     values[i]+=v_in;
   this->_is_closed = false;
 }
template<typename T > void libMesh::EpetraVector< T >::add (const NumericVector< T > & V) virtual
. Simple vector addition, equal to the operator +=.
Implements libMesh::NumericVector< T >.
Definition at line 267 of file trilinos_epetra_vector.C.
 {
   this->add (1., v);
 }
template<typename T > void libMesh::EpetraVector< T >::add (const T a, const NumericVector< T > & v) virtual
. Simple vector addition, equal to the operator +=.
Implements libMesh::NumericVector< T >.
Definition at line 274 of file trilinos_epetra_vector.C.
References libMesh::EpetraVector< T >::_vec, and libMesh::EpetraVector< T >::size().
 {
   const EpetraVector<T> * v = cast_ptr<const EpetraVector<T> *>(&v_in);
   libmesh_assert_equal_to (this->size(), v->size());
   _vec->Update(a_in,*v->_vec, 1.);
 }
template<typename T > void libMesh::EpetraVector< T >::add_vector (const T * v, const std::vector< numeric_index_type > & dof_indices) virtual
where v is a pointer and each dof_indices[i] specifies where to add value v[i]
Reimplemented from libMesh::NumericVector< T >.
Definition at line 213 of file trilinos_epetra_vector.C.
 {
   libmesh_assert_equal_to (sizeof(numeric_index_type), sizeof(int));
   SumIntoGlobalValues (dof_indices.size(),
                        (int *) &dof_indices[0],
                        const_cast<T *>(v));
 }
template<typename T > void libMesh::EpetraVector< T >::add_vector (const NumericVector< T > & v, const SparseMatrix< T > & A) virtual
, add the product of a SparseMatrix A and a NumericVector V to this, where this=U.
Implements libMesh::NumericVector< T >.
Definition at line 227 of file trilinos_epetra_vector.C.
References libMesh::EpetraVector< T >::_vec, A, and libMesh::EpetraVector< T >::zero_clone().
 {
   const EpetraVector<T> * V = cast_ptr<const EpetraVector<T> *>(&V_in);
   const EpetraMatrix<T> * A = cast_ptr<const EpetraMatrix<T> *>(&A_in);
   // FIXME - does Trilinos let us do this *without* memory allocation?
   UniquePtr<NumericVector<T> > temp = V->zero_clone();
   EpetraVector<T> * tempV = cast_ptr<EpetraVector<T> *>(temp.get());
   A->mat()->Multiply(false, *V->_vec, *tempV->_vec);
   *this += *temp;
 }
template<typename T> void libMesh::NumericVector< T >::add_vector (const std::vector< T > & v, const std::vector< numeric_index_type > & dof_indices) inline inherited
where v is a std::vector and each dof_indices[i] specifies where to add value v[i]
Definition at line 843 of file numeric_vector.h.
References libMesh::NumericVector< T >::add_vector(), and libMesh::libmesh_assert().
 {
   libmesh_assert(v.size() == dof_indices.size());
   if (!v.empty())
     this->add_vector(&v[0], dof_indices);
 }
template<typename T> void libMesh::NumericVector< T >::add_vector (const NumericVector< T > & V, const std::vector< numeric_index_type > & dof_indices) virtual inherited
where v is a NumericVector and each dof_indices[i] specifies where to add value v(i)
Definition at line 394 of file numeric_vector.C.
References libMesh::NumericVector< T >::size().
 {
   int n = dof_indices.size();
   libmesh_assert_equal_to(v.size(), static_cast<unsigned>(n));
   for (int i=0; i<n; i++)
     this->add (dof_indices[i], v(i));
 }
template<typename T> void libMesh::NumericVector< T >::add_vector (const DenseVector< T > & V, const std::vector< numeric_index_type > & dof_indices) inline inherited
where v is a DenseVector and each dof_indices[i] specifies where to add value v(i)
Definition at line 855 of file numeric_vector.h.
References libMesh::NumericVector< T >::add_vector(), libMesh::DenseVector< T >::empty(), libMesh::libmesh_assert(), and libMesh::DenseVector< T >::size().
 {
   libmesh_assert(v.size() == dof_indices.size());
   if (!v.empty())
     this->add_vector(&v(0), dof_indices);
 }
template<typename T> void libMesh::NumericVector< T >::add_vector (const NumericVector< T > & v, const ShellMatrix< T > & a) inherited
, add the product of a ShellMatrix A and a NumericVector V to this, where this=U.
Definition at line 406 of file numeric_vector.C.
References libMesh::ShellMatrix< T >::vector_mult_add().
 {
   a.vector_mult_add(*this,v);
 }
template<typename T > void libMesh::EpetraVector< T >::add_vector_transpose (const NumericVector< T > & v, const SparseMatrix< T > & A_trans) virtual
, add the product of the transpose of a SparseMatrix A_trans and a NumericVector V to this, where this=U.
Implements libMesh::NumericVector< T >.
Definition at line 244 of file trilinos_epetra_vector.C.
 {
   libmesh_not_implemented();
 }
template<typename T > UniquePtr< NumericVector< T > > libMesh::NumericVector< T >::build (const Parallel::Communicator & comm, const SolverPackage solver_package = libMesh::default_solver_package()) static inherited
Builds a NumericVector on the processors in communicator comm using the linear solver package specified by solver_package
Definition at line 46 of file numeric_vector.C.
References libMesh::AUTOMATIC, libMesh::EIGEN_SOLVERS, libMesh::LASPACK_SOLVERS, libMesh::PETSC_SOLVERS, and libMesh::TRILINOS_SOLVERS.
Referenced by libMesh::ExactSolution::_compute_error(), libMesh::UniformRefinementEstimator::_estimate_error(), libMesh::System::add_vector(), libMesh::NumericVector< T >::build(), libMesh::EquationSystems::build_parallel_solution_vector(), libMesh::System::calculate_norm(), libMesh::AdjointRefinementEstimator::estimate_error(), libMesh::ExactErrorEstimator::estimate_error(), libMesh::CondensedEigenSystem::get_eigenpair(), libMesh::EquationSystems::get_solution(), and libMesh::System::project_vector().
 {
   // Build the appropriate vector
   switch (solver_package)
     {
 #ifdef LIBMESH_HAVE_LASPACK
     case LASPACK_SOLVERS:
       return UniquePtr<NumericVector<T> >(new LaspackVector<T>(comm, AUTOMATIC));
 #endif
 #ifdef LIBMESH_HAVE_PETSC
     case PETSC_SOLVERS:
       return UniquePtr<NumericVector<T> >(new PetscVector<T>(comm, AUTOMATIC));
 #endif
 #ifdef LIBMESH_TRILINOS_HAVE_EPETRA
     case TRILINOS_SOLVERS:
       return UniquePtr<NumericVector<T> >(new EpetraVector<T>(comm, AUTOMATIC));
 #endif
 #ifdef LIBMESH_HAVE_EIGEN
     case EIGEN_SOLVERS:
       return UniquePtr<NumericVector<T> >(new EigenSparseVector<T>(comm, AUTOMATIC));
 #endif
     default:
       return UniquePtr<NumericVector<T> >(new DistributedVector<T>(comm, AUTOMATIC));
     }
   libmesh_error_msg("We'll never get here!");
   return UniquePtr<NumericVector<T> >();
 }
template<typename T > UniquePtr< NumericVector< T > > libMesh::NumericVector< T >::build (const SolverPackage solver_package = libMesh::default_solver_package()) static inherited
Builds a NumericVector on the processors in communicator CommWorld using the linear solver package specified by solver_package.
Deprecated:
LIBMESH_DISABLE_COMMWORLD is now the default, use the build() method that takes a Parallel::Communicator instead.
Definition at line 84 of file numeric_vector.C.
References libMesh::NumericVector< T >::build(), and libMesh::CommWorld.
 {
   libmesh_deprecated();
   return NumericVector<T>::build(CommWorld, solver_package);
 }
template<typename T > void libMesh::EpetraVector< T >::clear () inline virtual
Returns
the EpetraVector<T> to a pristine state.
Reimplemented from libMesh::NumericVector< T >.
Definition at line 872 of file trilinos_epetra_vector.h.
References libMesh::EpetraVector< T >::_destroy_vec_on_exit, libMesh::NumericVector< T >::_is_closed, libMesh::NumericVector< T >::_is_initialized, libMesh::EpetraVector< T >::_map, libMesh::EpetraVector< T >::_vec, libMesh::NumericVector< T >::initialized(), and libmesh_nullptr.
Referenced by libMesh::EpetraVector< T >::~EpetraVector().
 {
   if (this->initialized())
     {
       // We might just be an interface to a user-provided _vec
       if (this->_destroy_vec_on_exit)
         {
           delete _vec;
           _vec = libmesh_nullptr;
         }
       // But we currently always own our own _map
       _map.reset();
     }
   this->_is_closed = this->_is_initialized = false;
 }
template<typename T > UniquePtr< NumericVector< T > > libMesh::EpetraVector< T >::clone () const inline virtual
Creates a copy of this vector and returns it in an UniquePtr.
Implements libMesh::NumericVector< T >.
Definition at line 917 of file trilinos_epetra_vector.h.
References libMesh::AUTOMATIC, libMesh::ParallelObject::comm(), and libMesh::NumericVector< T >::init().
 {
   NumericVector<T> * cloned_vector = new EpetraVector<T>(this->comm(), AUTOMATIC);
   cloned_vector->init(*this, true);
   *cloned_vector = *this;
   return UniquePtr<NumericVector<T> >(cloned_vector);
 }
template<typename T > void libMesh::EpetraVector< T >::close () inline virtual
Call the assemble functions
Implements libMesh::NumericVector< T >.
Definition at line 848 of file trilinos_epetra_vector.h.
References libMesh::NumericVector< T >::_is_closed, libMesh::ParallelObject::comm(), libMesh::EpetraVector< T >::GlobalAssemble(), libMesh::NumericVector< T >::initialized(), libMesh::EpetraVector< T >::last_edit, libMesh::libmesh_assert(), and libMesh::Parallel::Communicator::max().
Referenced by libMesh::EpetraVector< T >::localize().
 {
   libmesh_assert (this->initialized());
   // Are we adding or inserting?
   unsigned char global_last_edit = last_edit;
   this->comm().max(global_last_edit);
   libmesh_assert(!last_edit || last_edit == global_last_edit);
   if (global_last_edit == 1)
     this->GlobalAssemble(Insert);
   else if (global_last_edit == 2)
     this->GlobalAssemble(Add);
   else
     libmesh_assert(!global_last_edit);
   this->_is_closed = true;
   this->last_edit = 0;
 }
template<typename T> virtual bool libMesh::NumericVector< T >::closed () const inline virtual inherited
Returns
true if the vector is closed and ready for computation, false otherwise.
Definition at line 151 of file numeric_vector.h.
Referenced by libMesh::DofMap::enforce_adjoint_constraints_exactly(), libMesh::DofMap::enforce_constraints_exactly(), libMesh::DofMap::max_constraint_error(), libMesh::EigenSparseVector< T >::operator=(), libMesh::LaspackVector< T >::operator=(), libMesh::PetscVector< T >::operator=(), libMesh::EigenSparseVector< T >::zero(), libMesh::LaspackVector< T >::zero(), libMesh::EpetraVector< T >::zero(), and libMesh::PetscVector< T >::zero().
 { return _is_closed; }
const Parallel::Communicator& libMesh::ParallelObject::comm () const inline inherited
Returns
a reference to the Parallel::Communicator object used by this mesh.
Definition at line 87 of file parallel_object.h.
References libMesh::ParallelObject::_communicator.
Referenced by libMesh::__libmesh_petsc_diff_solver_monitor(), libMesh::__libmesh_petsc_diff_solver_residual(), libMesh::__libmesh_petsc_snes_jacobian(), libMesh::__libmesh_petsc_snes_postcheck(), libMesh::__libmesh_petsc_snes_residual(), libMesh::__libmesh_tao_equality_constraints(), libMesh::__libmesh_tao_equality_constraints_jacobian(), libMesh::__libmesh_tao_gradient(), libMesh::__libmesh_tao_hessian(), libMesh::__libmesh_tao_inequality_constraints(), libMesh::__libmesh_tao_inequality_constraints_jacobian(), libMesh::__libmesh_tao_objective(), libMesh::MeshRefinement::_coarsen_elements(), libMesh::ExactSolution::_compute_error(), libMesh::ParmetisPartitioner::_do_repartition(), libMesh::UniformRefinementEstimator::_estimate_error(), libMesh::BoundaryInfo::_find_id_maps(), libMesh::PetscLinearSolver< T >::_petsc_shell_matrix_get_diagonal(), libMesh::SlepcEigenSolver< T >::_petsc_shell_matrix_get_diagonal(), libMesh::PetscLinearSolver< T >::_petsc_shell_matrix_mult(), libMesh::SlepcEigenSolver< T >::_petsc_shell_matrix_mult(), libMesh::PetscLinearSolver< T >::_petsc_shell_matrix_mult_add(), libMesh::EquationSystems::_read_impl(), libMesh::MeshRefinement::_refine_elements(), libMesh::MeshRefinement::_smooth_flags(), libMesh::ImplicitSystem::add_matrix(), libMesh::System::add_vector(), libMesh::EigenSparseLinearSolver< T >::adjoint_solve(), libMesh::UnstructuredMesh::all_second_order(), libMesh::MeshTools::Modification::all_tri(), libMesh::LaplaceMeshSmoother::allgather_graph(), libMesh::FEMSystem::assemble_qoi(), libMesh::MeshCommunication::assign_global_indices(), libMesh::ParmetisPartitioner::assign_partitioning(), libMesh::DofMap::attach_matrix(), libMesh::Parallel::BinSorter< KeyType, IdxType >::binsort(), libMesh::Parallel::Sort< KeyType, IdxType >::binsort(), libMesh::MeshCommunication::broadcast(), libMesh::SparseMatrix< T >::build(), libMesh::MeshTools::Generation::build_extrusion(), libMesh::Parallel::Histogram< KeyType, IdxType >::build_histogram(), libMesh::PetscNonlinearSolver< T >::build_mat_null_space(), libMesh::BoundaryInfo::build_node_list_from_side_list(), libMesh::EquationSystems::build_parallel_solution_vector(), libMesh::MeshBase::cache_elem_dims(), libMesh::System::calculate_norm(), libMesh::DofMap::check_dirichlet_bcid_consistency(), libMesh::DistributedVector< T >::clone(), libMesh::EigenSparseVector< T >::clone(), libMesh::LaspackVector< T >::clone(), libMesh::EpetraVector< T >::clone(), libMesh::PetscVector< T >::clone(), libMesh::EpetraVector< T >::close(), libMesh::Parallel::Sort< KeyType, IdxType >::communicate_bins(), libMesh::Nemesis_IO_Helper::compute_num_global_elem_blocks(), libMesh::Nemesis_IO_Helper::compute_num_global_nodesets(), libMesh::Nemesis_IO_Helper::compute_num_global_sidesets(), libMesh::Problem_Interface::computeF(), libMesh::Problem_Interface::computeJacobian(), libMesh::Problem_Interface::computePreconditioner(), libMesh::MeshTools::correct_node_proc_ids(), libMesh::MeshTools::create_bounding_box(), libMesh::MeshTools::create_nodal_bounding_box(), libMesh::MeshRefinement::create_parent_error_vector(), libMesh::MeshTools::create_processor_bounding_box(), libMesh::MeshTools::create_subdomain_bounding_box(), libMesh::MeshCommunication::delete_remote_elements(), libMesh::DofMap::distribute_dofs(), DMlibMeshFunction(), DMlibMeshJacobian(), DMlibMeshSetSystem_libMesh(), DMVariableBounds_libMesh(), libMesh::MeshRefinement::eliminate_unrefined_patches(), libMesh::EpetraVector< T >::EpetraVector(), libMesh::WeightedPatchRecoveryErrorEstimator::estimate_error(), libMesh::PatchRecoveryErrorEstimator::estimate_error(), libMesh::JumpErrorEstimator::estimate_error(), libMesh::AdjointRefinementEstimator::estimate_error(), libMesh::ExactErrorEstimator::estimate_error(), libMesh::MeshRefinement::flag_elements_by_elem_fraction(), libMesh::MeshRefinement::flag_elements_by_error_fraction(), libMesh::MeshRefinement::flag_elements_by_nelem_target(), libMesh::MeshCommunication::gather(), libMesh::MeshCommunication::gather_neighboring_elements(), libMesh::CondensedEigenSystem::get_eigenpair(), libMesh::DofMap::get_info(), libMesh::ImplicitSystem::get_linear_solver(), libMesh::EquationSystems::get_solution(), libMesh::LocationMap< T >::init(), libMesh::PetscDiffSolver::init(), libMesh::TimeSolver::init(), libMesh::TopologyMap::init(), libMesh::TaoOptimizationSolver< T >::init(), libMesh::PetscNonlinearSolver< T >::init(), libMesh::DistributedVector< T >::init(), libMesh::EpetraVector< T >::init(), libMesh::PetscVector< T >::init(), libMesh::SystemSubsetBySubdomain::init(), libMesh::EigenSystem::init_data(), libMesh::EigenSystem::init_matrices(), libMesh::ParmetisPartitioner::initialize(), libMesh::OptimizationSystem::initialize_equality_constraints_storage(), libMesh::OptimizationSystem::initialize_inequality_constraints_storage(), libMesh::MeshTools::libmesh_assert_parallel_consistent_procids< Elem >(), libMesh::MeshTools::libmesh_assert_parallel_consistent_procids< Node >(), libMesh::MeshTools::libmesh_assert_topology_consistent_procids< Node >(), libMesh::MeshTools::libmesh_assert_valid_boundary_ids(), libMesh::MeshTools::libmesh_assert_valid_dof_ids(), libMesh::MeshTools::libmesh_assert_valid_neighbors(), libMesh::DistributedMesh::libmesh_assert_valid_parallel_flags(), libMesh::DistributedMesh::libmesh_assert_valid_parallel_object_ids(), libMesh::DistributedMesh::libmesh_assert_valid_parallel_p_levels(), libMesh::MeshTools::libmesh_assert_valid_refinement_flags(), libMesh::MeshTools::libmesh_assert_valid_unique_ids(), libMesh::MeshRefinement::limit_level_mismatch_at_edge(), libMesh::MeshRefinement::limit_level_mismatch_at_node(), libMesh::MeshRefinement::limit_overrefined_boundary(), libMesh::MeshRefinement::limit_underrefined_boundary(), libMesh::MeshRefinement::make_coarsening_compatible(), libMesh::MeshCommunication::make_elems_parallel_consistent(), libMesh::MeshRefinement::make_flags_parallel_consistent(), libMesh::MeshCommunication::make_new_node_proc_ids_parallel_consistent(), libMesh::MeshCommunication::make_new_nodes_parallel_consistent(), libMesh::MeshCommunication::make_node_ids_parallel_consistent(), libMesh::MeshCommunication::make_node_proc_ids_parallel_consistent(), libMesh::MeshCommunication::make_node_unique_ids_parallel_consistent(), libMesh::MeshCommunication::make_nodes_parallel_consistent(), libMesh::MeshCommunication::make_p_levels_parallel_consistent(), libMesh::MeshRefinement::make_refinement_compatible(), libMesh::DistributedVector< T >::max(), libMesh::FEMSystem::mesh_position_set(), libMesh::MeshSerializer::MeshSerializer(), libMesh::DistributedVector< T >::min(), libMesh::DistributedMesh::n_active_elem(), libMesh::MeshTools::n_active_levels(), libMesh::BoundaryInfo::n_boundary_conds(), libMesh::BoundaryInfo::n_edge_conds(), libMesh::CondensedEigenSystem::n_global_non_condensed_dofs(), libMesh::MeshTools::n_levels(), libMesh::BoundaryInfo::n_nodeset_conds(), libMesh::MeshTools::n_p_levels(), libMesh::BoundaryInfo::n_shellface_conds(), libMesh::DistributedMesh::parallel_max_elem_id(), libMesh::DistributedMesh::parallel_max_node_id(), libMesh::ReplicatedMesh::parallel_max_unique_id(), libMesh::DistributedMesh::parallel_max_unique_id(), libMesh::DistributedMesh::parallel_n_elem(), libMesh::DistributedMesh::parallel_n_nodes(), libMesh::SparsityPattern::Build::parallel_sync(), libMesh::MeshTools::paranoid_n_levels(), libMesh::Partitioner::partition(), libMesh::MetisPartitioner::partition_range(), libMesh::Partitioner::partition_unpartitioned_elements(), libMesh::petsc_auto_fieldsplit(), libMesh::System::point_gradient(), libMesh::System::point_hessian(), libMesh::System::point_value(), libMesh::MeshBase::prepare_for_use(), libMesh::SparseMatrix< T >::print(), libMesh::Nemesis_IO::read(), libMesh::CheckpointIO::read(), libMesh::XdrIO::read(), libMesh::XdrIO::read_serialized_bc_names(), libMesh::XdrIO::read_serialized_bcs_helper(), libMesh::XdrIO::read_serialized_connectivity(), libMesh::XdrIO::read_serialized_nodes(), libMesh::XdrIO::read_serialized_nodesets(), libMesh::XdrIO::read_serialized_subdomain_names(), libMesh::MeshBase::recalculate_n_partitions(), libMesh::MeshCommunication::redistribute(), libMesh::DistributedMesh::renumber_dof_objects(), libMesh::MeshCommunication::send_coarse_ghosts(), libMesh::Partitioner::set_node_processor_ids(), libMesh::DofMap::set_nonlocal_dof_objects(), libMesh::Partitioner::set_parent_processor_ids(), libMesh::LaplaceMeshSmoother::smooth(), libMesh::Parallel::Sort< KeyType, IdxType >::sort(), libMesh::MeshBase::subdomain_ids(), libMesh::BoundaryInfo::sync(), libMesh::Parallel::sync_element_data_by_parent_id(), libMesh::Parallel::sync_node_data_by_element_id(), libMesh::MeshRefinement::test_level_one(), libMesh::MeshRefinement::test_unflagged(), libMesh::MeshTools::total_weight(), libMesh::NameBasedIO::write(), libMesh::XdrIO::write(), libMesh::XdrIO::write_serialized_bcs_helper(), libMesh::XdrIO::write_serialized_connectivity(), libMesh::XdrIO::write_serialized_nodes(), libMesh::XdrIO::write_serialized_nodesets(), libMesh::DistributedVector< T >::zero_clone(), libMesh::LaspackVector< T >::zero_clone(), libMesh::EigenSparseVector< T >::zero_clone(), libMesh::EpetraVector< T >::zero_clone(), and libMesh::PetscVector< T >::zero_clone().
   { return _communicator; }
template<typename T> int libMesh::NumericVector< T >::compare (const NumericVector< T > & other_vector, const Real threshold = TOLERANCE) const virtual inherited
Returns
-1 when this is equivalent to other_vector, up to the given threshold. When differences occur, the return value contains the first index i where the difference (a[i]-b[i]) exceeded the threshold. When no threshold is given, the libMesh TOLERANCE is used.
Definition at line 116 of file numeric_vector.C.
References std::abs(), libMesh::NumericVector< T >::first_local_index(), libMesh::NumericVector< T >::initialized(), libMesh::initialized(), libMesh::NumericVector< T >::last_local_index(), libMesh::libmesh_assert(), and std::max().
Referenced by libMesh::NumericVector< Number >::operator/=().
 {
   libmesh_assert (this->initialized());
   libmesh_assert (other_vector.initialized());
   libmesh_assert_equal_to (this->first_local_index(), other_vector.first_local_index());
   libmesh_assert_equal_to (this->last_local_index(), other_vector.last_local_index());
   int first_different_i = std::numeric_limits<int>::max();
   numeric_index_type i = first_local_index();
   do
     {
       if (std::abs((*this)(i) - other_vector(i)) > threshold)
         first_different_i = i;
       else
         i++;
     }
   while (first_different_i==std::numeric_limits<int>::max()
          && i<last_local_index());
   // Find the correct first differing index in parallel
   this->comm().min(first_different_i);
   if (first_different_i == std::numeric_limits<int>::max())
     return -1;
   return first_different_i;
 }
template<typename T > void libMesh::EpetraVector< T >::conjugate () virtual
Replace each entry v_i = real(v_i) + imag(v_i) of this vector by its complex conjugate, real(v_i) - imag(v_i). Epetra is real-valued only, rendering this a no-op.
Implements libMesh::NumericVector< T >.
Definition at line 190 of file trilinos_epetra_vector.C.
 {
   // EPetra is real, rendering this a no-op.
 }
template<typename T > void libMesh::EpetraVector< T >::create_subvector (NumericVector< T > & subvector, const std::vector< numeric_index_type > & rows) const virtual
Creates a "subvector" from this vector using the rows indices of the "rows" array.
Reimplemented from libMesh::NumericVector< T >.
Definition at line 572 of file trilinos_epetra_vector.C.
 {
   libmesh_not_implemented();
 }
template<typename T > void libMesh::EpetraVector< T >::destroyNonlocalData () private
Definition at line 904 of file trilinos_epetra_vector.C.
References libmesh_nullptr.
Referenced by libMesh::EpetraVector< T >::setIgnoreNonLocalEntries().
 {
   if (allocatedNonlocalLength_ > 0) {
     delete [] nonlocalIDs_;
     delete [] nonlocalElementSize_;
     nonlocalIDs_ = libmesh_nullptr;
     nonlocalElementSize_ = libmesh_nullptr;
     for (int i=0; i<numNonlocalIDs_; ++i) {
       delete [] nonlocalCoefs_[i];
     }
     delete [] nonlocalCoefs_;
     nonlocalCoefs_ = libmesh_nullptr;
     numNonlocalIDs_ = 0;
     allocatedNonlocalLength_ = 0;
   }
   return;
 }
void libMesh::ReferenceCounter::disable_print_counter_info () static inherited
Definition at line 107 of file reference_counter.C.
References libMesh::ReferenceCounter::_enable_print_counter.
Referenced by libMesh::LibMeshInit::LibMeshInit(), and libMesh::ReferenceCounter::n_objects().
 {
   _enable_print_counter = false;
   return;
 }
template<typename T > T libMesh::EpetraVector< T >::dot (const NumericVector< T > & V) const virtual
Computes the dot product, p = U.V
Implements libMesh::NumericVector< T >.
Definition at line 312 of file trilinos_epetra_vector.C.
References libMesh::EpetraVector< T >::_vec.
 {
   const EpetraVector<T> * V = cast_ptr<const EpetraVector<T> *>(&V_in);
   T result=0.0;
   _vec->Dot(*V->_vec, &result);
   return result;
 }
template<typename T> virtual T libMesh::NumericVector< T >::el (const numeric_index_type i) const inline virtual inherited
Returns
the element U(i)
Definition at line 348 of file numeric_vector.h.
 { return (*this)(i); }
void libMesh::ReferenceCounter::enable_print_counter_info () static inherited
Methods to enable/disable the reference counter output from print_info()
Definition at line 101 of file reference_counter.C.
References libMesh::ReferenceCounter::_enable_print_counter.
Referenced by libMesh::ReferenceCounter::n_objects().
 {
   _enable_print_counter = true;
   return;
 }
template<typename T > void libMesh::EpetraVector< T >::FEoperatorequals (const EpetraVector< T > & source) private
Definition at line 877 of file trilinos_epetra_vector.C.
References libMesh::EpetraVector< T >::_vec, libMesh::EpetraVector< T >::allocatedNonlocalLength_, libMesh::EpetraVector< T >::nonlocalCoefs_, libMesh::EpetraVector< T >::nonlocalElementSize_, libMesh::EpetraVector< T >::nonlocalIDs_, and libMesh::EpetraVector< T >::numNonlocalIDs_.
Referenced by libMesh::EpetraVector< T >::setIgnoreNonLocalEntries().
 {
   (*_vec) = *(source._vec);
   destroyNonlocalData();
   if (source.allocatedNonlocalLength_ > 0) {
     allocatedNonlocalLength_ = source.allocatedNonlocalLength_;
     numNonlocalIDs_ = source.numNonlocalIDs_;
     nonlocalIDs_ = new int[allocatedNonlocalLength_];
     nonlocalElementSize_ = new int[allocatedNonlocalLength_];
     nonlocalCoefs_ = new double *[allocatedNonlocalLength_];
     for (int i=0; i<numNonlocalIDs_; ++i) {
       int elemSize = source.nonlocalElementSize_[i];
       nonlocalCoefs_[i] = new double[elemSize];
       nonlocalIDs_[i] = source.nonlocalIDs_[i];
       nonlocalElementSize_[i] = elemSize;
       for (int j=0; j<elemSize; ++j) {
         nonlocalCoefs_[i][j] = source.nonlocalCoefs_[i][j];
       }
     }
   }
 }
template<typename T > numeric_index_type libMesh::EpetraVector< T >::first_local_index () const inline virtual
Returns
the index of the first vector element actually stored on this processor
Implements libMesh::NumericVector< T >.
Definition at line 949 of file trilinos_epetra_vector.h.
References libMesh::EpetraVector< T >::_vec, libMesh::NumericVector< T >::initialized(), and libMesh::libmesh_assert().
Referenced by libMesh::EpetraVector< T >::operator()().
 {
   libmesh_assert (this->initialized());
   return _vec->Map().MinMyGID();
 }
template<typename T> void libMesh::NumericVector< T >::get (const std::vector< numeric_index_type > & index, T * values) const inline virtual inherited
Access multiple components at once. values will not be reallocated; it should already have enough space. The default implementation calls operator() for each index, but some implementations may supply faster methods here.
Reimplemented in libMesh::PetscVector< T >.
Definition at line 814 of file numeric_vector.h.
Referenced by libMesh::DofMap::enforce_adjoint_constraints_exactly(), libMesh::DofMap::enforce_constraints_exactly(), libMesh::FEMContext::pre_fe_reinit(), and libMesh::System::project_vector().
 {
   const std::size_t num = index.size();
   for (std::size_t i=0; i<num; i++)
     {
       values[i] = (*this)(index[i]);
     }
 }
template<typename T> void libMesh::NumericVector< T >::get (const std::vector< numeric_index_type > & index, std::vector< T > & values) const inline inherited
Access multiple components at once. values will be resized, if necessary, and filled. The default implementation calls operator() for each index, but some implementations may supply faster methods here.
Definition at line 828 of file numeric_vector.h.
 {
   const std::size_t num = index.size();
   values.resize(num);
   if (!num)
     return;
   this->get(index, &values[0]);
 }
std::string libMesh::ReferenceCounter::get_info () static inherited
Gets a string containing the reference information.
Definition at line 47 of file reference_counter.C.
References libMesh::ReferenceCounter::_counts, and libMesh::Quality::name().
Referenced by libMesh::ReferenceCounter::print_info().
 {
 #if defined(LIBMESH_ENABLE_REFERENCE_COUNTING) && defined(DEBUG)
   std::ostringstream oss;
   oss << '\n'
       << " ---------------------------------------------------------------------------- \n"
       << "| Reference count information                                                |\n"
       << " ---------------------------------------------------------------------------- \n";
   for (Counts::iterator it = _counts.begin();
        it != _counts.end(); ++it)
     {
       const std::string name(it->first);
       const unsigned int creations    = it->second.first;
       const unsigned int destructions = it->second.second;
       oss << "| " << name << " reference count information:\n"
           << "|  Creations:    " << creations    << '\n'
           << "|  Destructions: " << destructions << '\n';
     }
   oss << " ---------------------------------------------------------------------------- \n";
   return oss.str();
 #else
   return "";
 #endif
 }
template<typename T> int libMesh::NumericVector< T >::global_relative_compare (const NumericVector< T > & other_vector, const Real threshold = TOLERANCE) const virtual inherited
Returns
-1 when this is equivalent to other_vector, up to the given local relative threshold. When differences occur, the return value contains the first index where the difference (a[i]-b[i])/max_j(a[j],b[j]) exceeded the threshold. When no threshold is given, the libMesh TOLERANCE is used.
Definition at line 181 of file numeric_vector.C.
References std::abs(), libMesh::NumericVector< T >::first_local_index(), libMesh::NumericVector< T >::initialized(), libMesh::initialized(), libMesh::NumericVector< T >::last_local_index(), libMesh::libmesh_assert(), libMesh::NumericVector< T >::linfty_norm(), std::max(), and libMesh::Real.
Referenced by libMesh::NumericVector< Number >::operator/=().
 {
   libmesh_assert (this->initialized());
   libmesh_assert (other_vector.initialized());
   libmesh_assert_equal_to (this->first_local_index(), other_vector.first_local_index());
   libmesh_assert_equal_to (this->last_local_index(), other_vector.last_local_index());
   int first_different_i = std::numeric_limits<int>::max();
   numeric_index_type i = first_local_index();
   const Real my_norm = this->linfty_norm();
   const Real other_norm = other_vector.linfty_norm();
   const Real abs_threshold = std::max(my_norm, other_norm) * threshold;
   do
     {
       if (std::abs((*this)(i) - other_vector(i) ) > abs_threshold)
         first_different_i = i;
       else
         i++;
     }
   while (first_different_i==std::numeric_limits<int>::max()
          && i<last_local_index());
   // Find the correct first differing index in parallel
   this->comm().min(first_different_i);
   if (first_different_i == std::numeric_limits<int>::max())
     return -1;
   return first_different_i;
 }
template<typename T > int libMesh::EpetraVector< T >::GlobalAssemble (Epetra_CombineMode mode = Add) private
Gather any overlapping/shared data into the non-overlapping partitioning defined by the Map that was passed to this vector at construction time. Data imported from other processors is stored on the owning processor with a "sumInto" or accumulate operation. This is a collective method – every processor must enter it before any will complete it.
Definition at line 832 of file trilinos_epetra_vector.C.
Referenced by libMesh::EpetraVector< T >::close().
 {
   //In this method we need to gather all the non-local (overlapping) data
   //that's been input on each processor, into the (probably) non-overlapping
   //distribution defined by the map that 'this' vector was constructed with.
   //We don't need to do anything if there's only one processor or if
   //ignoreNonLocalEntries_ is true.
   if (_vec->Map().Comm().NumProc() < 2 || ignoreNonLocalEntries_) {
     return(0);
   }
   //First build a map that describes the data in nonlocalIDs_/nonlocalCoefs_.
   //We'll use the arbitrary distribution constructor of Map.
   Epetra_BlockMap sourceMap(-1, numNonlocalIDs_,
                             nonlocalIDs_, nonlocalElementSize_,
                             _vec->Map().IndexBase(), _vec->Map().Comm());
   //Now build a vector to hold our nonlocalCoefs_, and to act as the source-
   //vector for our import operation.
   Epetra_MultiVector nonlocalVector(sourceMap, 1);
   int i,j;
   for (i=0; i<numNonlocalIDs_; ++i) {
     for (j=0; j<nonlocalElementSize_[i]; ++j) {
       nonlocalVector.ReplaceGlobalValue(nonlocalIDs_[i], j, 0,
                                         nonlocalCoefs_[i][j]);
     }
   }
   Epetra_Export exporter(sourceMap, _vec->Map());
   EPETRA_CHK_ERR( _vec->Export(nonlocalVector, exporter, mode) );
   destroyNonlocalData();
   return(0);
 }
void libMesh::ReferenceCounter::increment_constructor_count (const std::string & name) inline protected inherited
Increments the construction counter. Should be called in the constructor of any derived class that will be reference counted.
Definition at line 185 of file reference_counter.h.
References libMesh::ReferenceCounter::_counts, libMesh::Quality::name(), and libMesh::Threads::spin_mtx.
Referenced by libMesh::ReferenceCounter::n_objects(), and libMesh::ReferenceCountedObject< RBParametrized >::ReferenceCountedObject().
 {
   Threads::spin_mutex::scoped_lock lock(Threads::spin_mtx);
   std::pair<unsigned int, unsigned int> & p = _counts[name];
   p.first++;
 }
void libMesh::ReferenceCounter::increment_destructor_count (const std::string & name) inline protected inherited
Increments the destruction counter. Should be called in the destructor of any derived class that will be reference counted.
Definition at line 198 of file reference_counter.h.
References libMesh::ReferenceCounter::_counts, libMesh::Quality::name(), and libMesh::Threads::spin_mtx.
Referenced by libMesh::ReferenceCounter::n_objects(), and libMesh::ReferenceCountedObject< RBParametrized >::~ReferenceCountedObject().
 {
   Threads::spin_mutex::scoped_lock lock(Threads::spin_mtx);
   std::pair<unsigned int, unsigned int> & p = _counts[name];
   p.second++;
 }
template<typename T > void libMesh::EpetraVector< T >::init (const numeric_index_type N, const numeric_index_type n_local, const bool fast = false, const ParallelType type = AUTOMATIC) inline virtual
Change the dimension of the vector to N. The reserved memory for this vector remains unchanged if possible, to make things faster, but this may waste some memory, so take this in the back of your head. However, if N==0 all memory is freed, i.e. if you want to resize the vector and release the memory not needed, you have to first call init(0) and then init(N). This cited behaviour is analogous to that of the STL containers.
On fast==false, the vector is filled by zeros.
Implements libMesh::NumericVector< T >.
Definition at line 768 of file trilinos_epetra_vector.h.
References libMesh::NumericVector< T >::_is_closed, libMesh::NumericVector< T >::_is_initialized, libMesh::EpetraVector< T >::_map, libMesh::NumericVector< T >::_type, libMesh::EpetraVector< T >::_vec, libMesh::AUTOMATIC, libMesh::ParallelObject::comm(), libMesh::GHOSTED, libMesh::EpetraVector< T >::last_edit, libMesh::libmesh_assert(), libMesh::EpetraVector< T >::myCoefs_, libMesh::EpetraVector< T >::myFirstID_, libMesh::EpetraVector< T >::myNumIDs_, libMesh::PARALLEL, libMesh::SERIAL, libMesh::NumericVector< T >::type(), and libMesh::EpetraVector< T >::zero().
Referenced by libMesh::EpetraVector< T >::EpetraVector(), libMesh::EpetraVector< T >::init(), and libMesh::EpetraVector< T >::localize().
 {
   // We default to allocating n_local local storage
   numeric_index_type my_n_local = n_local;
   if (type == AUTOMATIC)
     {
       if (n == n_local)
         this->_type = SERIAL;
       else
         this->_type = PARALLEL;
     }
   else if (type == GHOSTED)
     {
       // We don't yet support GHOSTED Epetra vectors, so to get the
       // same functionality we need a SERIAL vector with local
       // storage allocated for every entry.
       this->_type = SERIAL;
       my_n_local = n;
     }
   else
     this->_type = type;
   libmesh_assert ((this->_type==SERIAL && n==my_n_local) ||
                   this->_type==PARALLEL);
   _map.reset(new Epetra_Map(static_cast<int>(n),
                             my_n_local,
                             0,
                             Epetra_MpiComm (this->comm().get())));
   _vec = new Epetra_Vector(*_map);
   myFirstID_ = _vec->Map().MinMyGID();
   myNumIDs_ = _vec->Map().NumMyElements();
   // Currently we impose the restriction that NumVectors==1, so we won't
   // need the LDA argument when calling ExtractView. Hence the "dummy" arg.
   int dummy;
   _vec->ExtractView(&myCoefs_, &dummy);
   this->_is_initialized = true;
   this->_is_closed = true;
   this->last_edit = 0;
   if (fast == false)
     this->zero ();
 }
template<typename T > void libMesh::EpetraVector< T >::init (const numeric_index_type N, const bool fast = false, const ParallelType type = AUTOMATIC) inline virtual
call init with n_local = N,
Implements libMesh::NumericVector< T >.
Definition at line 837 of file trilinos_epetra_vector.h.
References libMesh::EpetraVector< T >::init().
 {
   this->init(n,n,fast,type);
 }
template<typename T > void libMesh::EpetraVector< T >::init (const numeric_index_type n, const numeric_index_type n_local, const std::vector< numeric_index_type > & , const bool fast = false, const ParallelType type = AUTOMATIC) inline virtual
Create a vector that holds the local indices plus those specified in the ghost argument.
Implements libMesh::NumericVector< T >.
Definition at line 823 of file trilinos_epetra_vector.h.
References libMesh::EpetraVector< T >::init().
 {
   // TODO: we shouldn't ignore the ghost sparsity pattern
   this->init(n, n_local, fast, type);
 }
template<class T > void libMesh::EpetraVector< T >::init (const NumericVector< T > & other, const bool fast = false) virtual
Creates a vector that has the same dimension and storage type as other, including ghost dofs.
Implements libMesh::NumericVector< T >.
Definition at line 749 of file trilinos_epetra_vector.h.
References libMesh::EpetraVector< T >::init(), libMesh::NumericVector< T >::local_size(), libMesh::NumericVector< T >::size(), and libMesh::NumericVector< T >::type().
 {
   this->init(other.size(),other.local_size(),fast,other.type());
 }
template<typename T> virtual bool libMesh::NumericVector< T >::initialized () const inline virtual inherited
Returns
true if the vector has been initialized, false otherwise.
Definition at line 135 of file numeric_vector.h.
Referenced by libMesh::DistributedVector< T >::add(), libMesh::EigenSparseVector< T >::add(), libMesh::LaspackVector< T >::add(), libMesh::ImplicitSystem::assemble(), libMesh::LaspackVector< T >::clear(), libMesh::EpetraVector< T >::clear(), libMesh::PetscVector< T >::clear(), libMesh::DistributedVector< T >::close(), libMesh::EigenSparseVector< T >::close(), libMesh::LaspackVector< T >::close(), libMesh::EpetraVector< T >::close(), libMesh::NumericVector< T >::compare(), libMesh::PetscVector< T >::create_subvector(), libMesh::DistributedVector< T >::first_local_index(), libMesh::EigenSparseVector< T >::first_local_index(), libMesh::LaspackVector< T >::first_local_index(), libMesh::EpetraVector< T >::first_local_index(), libMesh::PetscVector< T >::first_local_index(), libMesh::NumericVector< T >::global_relative_compare(), libMesh::DistributedVector< T >::init(), libMesh::EigenSparseVector< T >::init(), libMesh::PetscVector< T >::init(), libMesh::DistributedVector< T >::last_local_index(), libMesh::EigenSparseVector< T >::last_local_index(), libMesh::LaspackVector< T >::last_local_index(), libMesh::EpetraVector< T >::last_local_index(), libMesh::PetscVector< T >::last_local_index(), libMesh::NumericVector< T >::local_relative_compare(), libMesh::DistributedVector< T >::local_size(), libMesh::EigenSparseVector< T >::local_size(), libMesh::LaspackVector< T >::local_size(), libMesh::EpetraVector< T >::local_size(), libMesh::PetscVector< T >::local_size(), libMesh::PetscVector< T >::map_global_to_local_index(), libMesh::DistributedVector< T >::max(), libMesh::EpetraVector< T >::max(), libMesh::DistributedVector< T >::min(), libMesh::EpetraVector< T >::min(), libMesh::DistributedVector< T >::operator()(), libMesh::LaspackVector< T >::operator()(), libMesh::EigenSparseVector< T >::operator()(), libMesh::EpetraVector< T >::operator()(), libMesh::NumericVector< T >::print(), libMesh::NumericVector< T >::print_global(), libMesh::DistributedVector< T >::set(), libMesh::EigenSparseVector< T >::set(), libMesh::LaspackVector< T >::set(), libMesh::DistributedVector< T >::size(), libMesh::LaspackVector< T >::size(), libMesh::EigenSparseVector< T >::size(), libMesh::EpetraVector< T >::size(), libMesh::PetscVector< T >::size(), libMesh::DistributedVector< T >::zero(), libMesh::LaspackVector< T >::zero(), libMesh::EigenSparseVector< T >::zero(), libMesh::EpetraVector< T >::zero(), and libMesh::LaspackVector< T >::~LaspackVector().
 { return _is_initialized; }
template<typename T > int libMesh::EpetraVector< T >::inputNonlocalValue (int GID, double value, bool accumulate) private
Definition at line 730 of file trilinos_epetra_vector.C.
Referenced by libMesh::EpetraVector< T >::setIgnoreNonLocalEntries().
 {
   int insertPoint = -1;
   //find offset of GID in nonlocalIDs_
   int offset = Epetra_Util_binary_search(GID, nonlocalIDs_, numNonlocalIDs_,
                                          insertPoint);
   if (offset >= 0) {
     //if offset >= 0
     //  put value in nonlocalCoefs_[offset][0]
     if (accumulate) {
       nonlocalCoefs_[offset][0] += value;
     }
     else {
       nonlocalCoefs_[offset][0] = value;
     }
   }
   else {
     //else
     //  insert GID in nonlocalIDs_
     //  insert 1   in nonlocalElementSize_
     //  insert value in nonlocalCoefs_
     int tmp1 = numNonlocalIDs_;
     int tmp2 = allocatedNonlocalLength_;
     int tmp3 = allocatedNonlocalLength_;
     EPETRA_CHK_ERR( Epetra_Util_insert(GID, insertPoint, nonlocalIDs_,
                                        tmp1, tmp2) );
     --tmp1;
     EPETRA_CHK_ERR( Epetra_Util_insert(1, insertPoint, nonlocalElementSize_,
                                        tmp1, tmp3) );
     double * values = new double[1];
     values[0] = value;
     EPETRA_CHK_ERR( Epetra_Util_insert(values, insertPoint, nonlocalCoefs_,
                                        numNonlocalIDs_, allocatedNonlocalLength_) );
   }
   return(0);
 }
template<typename T > int libMesh::EpetraVector< T >::inputNonlocalValues (int GID, int numValues, const double * values, bool accumulate) private
Definition at line 773 of file trilinos_epetra_vector.C.
References libMesh::err.
Referenced by libMesh::EpetraVector< T >::setIgnoreNonLocalEntries().
 {
   int insertPoint = -1;
   //find offset of GID in nonlocalIDs_
   int offset = Epetra_Util_binary_search(GID, nonlocalIDs_, numNonlocalIDs_,
                                          insertPoint);
   if (offset >= 0) {
     //if offset >= 0
     //  put value in nonlocalCoefs_[offset][0]
     if (numValues != nonlocalElementSize_[offset]) {
       libMesh::err << "Epetra_FEVector ERROR: block-size for GID " << GID << " is "
                    << numValues<<" which doesn't match previously set block-size of "
                    << nonlocalElementSize_[offset] << std::endl;
       return(-1);
     }
     if (accumulate) {
       for (int j=0; j<numValues; ++j) {
         nonlocalCoefs_[offset][j] += values[j];
       }
     }
     else {
       for (int j=0; j<numValues; ++j) {
         nonlocalCoefs_[offset][j] = values[j];
       }
     }
   }
   else {
     //else
     //  insert GID in nonlocalIDs_
     //  insert numValues   in nonlocalElementSize_
     //  insert values in nonlocalCoefs_
     int tmp1 = numNonlocalIDs_;
     int tmp2 = allocatedNonlocalLength_;
     int tmp3 = allocatedNonlocalLength_;
     EPETRA_CHK_ERR( Epetra_Util_insert(GID, insertPoint, nonlocalIDs_,
                                        tmp1, tmp2) );
     --tmp1;
     EPETRA_CHK_ERR( Epetra_Util_insert(numValues, insertPoint, nonlocalElementSize_,
                                        tmp1, tmp3) );
     double * newvalues = new double[numValues];
     for (int j=0; j<numValues; ++j) {
       newvalues[j] = values[j];
     }
     EPETRA_CHK_ERR( Epetra_Util_insert(newvalues, insertPoint, nonlocalCoefs_,
                                        numNonlocalIDs_, allocatedNonlocalLength_) );
   }
   return(0);
 }
template<typename T > int libMesh::EpetraVector< T >::inputValues (int numIDs, const int * GIDs, const double * values, bool accumulate) private
Definition at line 650 of file trilinos_epetra_vector.C.
References libMesh::libmesh_assert().
Referenced by libMesh::EpetraVector< T >::setIgnoreNonLocalEntries().
 {
   if (accumulate) {
     libmesh_assert(last_edit == 0 || last_edit == 2);
     last_edit = 2;
   } else {
     libmesh_assert(last_edit == 0 || last_edit == 1);
     last_edit = 1;
   }
   //Important note!! This method assumes that there is only 1 point
   //associated with each element.
   for (int i=0; i<numIDs; ++i) {
     if (_vec->Map().MyGID(GIDs[i])) {
       if (accumulate) {
         _vec->SumIntoGlobalValue(GIDs[i], 0, 0, values[i]);
       }
       else {
         _vec->ReplaceGlobalValue(GIDs[i], 0, 0, values[i]);
       }
     }
     else {
       if (!ignoreNonLocalEntries_) {
         EPETRA_CHK_ERR( inputNonlocalValue(GIDs[i], values[i], accumulate) );
       }
     }
   }
   return(0);
 }
template<typename T > int libMesh::EpetraVector< T >::inputValues (int numIDs, const int * GIDs, const int * numValuesPerID, const double * values, bool accumulate) private
Definition at line 687 of file trilinos_epetra_vector.C.
References libMesh::libmesh_assert().
 {
   if (accumulate) {
     libmesh_assert(last_edit == 0 || last_edit == 2);
     last_edit = 2;
   } else {
     libmesh_assert(last_edit == 0 || last_edit == 1);
     last_edit = 1;
   }
   int offset=0;
   for (int i=0; i<numIDs; ++i) {
     int numValues = numValuesPerID[i];
     if (_vec->Map().MyGID(GIDs[i])) {
       if (accumulate) {
         for (int j=0; j<numValues; ++j) {
           _vec->SumIntoGlobalValue(GIDs[i], j, 0, values[offset+j]);
         }
       }
       else {
         for (int j=0; j<numValues; ++j) {
           _vec->ReplaceGlobalValue(GIDs[i], j, 0, values[offset+j]);
         }
       }
     }
     else {
       if (!ignoreNonLocalEntries_) {
         EPETRA_CHK_ERR( inputNonlocalValues(GIDs[i], numValues,
                                             &(values[offset]), accumulate) );
       }
     }
     offset += numValues;
   }
   return(0);
 }
template<typename T > void libMesh::EpetraVector< T >::insert (const T * v, const std::vector< numeric_index_type > & dof_indices) virtual
where v is a T[] or T * and you want to specify WHERE to insert it
Reimplemented from libMesh::NumericVector< T >.
Definition at line 286 of file trilinos_epetra_vector.C.
 {
   libmesh_assert_equal_to (sizeof(numeric_index_type), sizeof(int));
   ReplaceGlobalValues (dof_indices.size(),
                        (int *) &dof_indices[0],
                        const_cast<T *>(v));
 }
template<typename T> void libMesh::NumericVector< T >::insert (const std::vector< T > & v, const std::vector< numeric_index_type > & dof_indices) inline inherited
where v is a std::vector<T> and you want to specify WHERE to insert it
Definition at line 867 of file numeric_vector.h.
References libMesh::NumericVector< T >::insert(), and libMesh::libmesh_assert().
 {
   libmesh_assert(v.size() == dof_indices.size());
   if (!v.empty())
     this->insert(&v[0], dof_indices);
 }
template<typename T> void libMesh::NumericVector< T >::insert (const NumericVector< T > & V, const std::vector< numeric_index_type > & dof_indices) virtual inherited
, where U and V are type NumericVector<T> and you want to specify WHERE to insert the NumericVector<T> V
Definition at line 104 of file numeric_vector.C.
References libMesh::NumericVector< T >::size().
 {
   libmesh_assert_equal_to (V.size(), dof_indices.size());
   for (numeric_index_type i=0; i<dof_indices.size(); i++)
     this->set (dof_indices[i], V(i));
 }
template<typename T> void libMesh::NumericVector< T >::insert (const DenseVector< T > & V, const std::vector< numeric_index_type > & dof_indices) inline inherited
where U and V are type DenseVector<T> and you want to specify WHERE to insert the DenseVector<T> V
Definition at line 879 of file numeric_vector.h.
References libMesh::DenseVector< T >::empty(), libMesh::NumericVector< T >::insert(), libMesh::libmesh_assert(), and libMesh::DenseVector< T >::size().
 {
   libmesh_assert(v.size() == dof_indices.size());
   if (!v.empty())
     this->insert(&v(0), dof_indices);
 }
template<typename T> void libMesh::NumericVector< T >::insert (const DenseSubVector< T > & V, const std::vector< numeric_index_type > & dof_indices) inline inherited
where V is a DenseSubVector<T> and you want to specify WHERE to insert it
Definition at line 891 of file numeric_vector.h.
References libMesh::DenseSubVector< T >::empty(), libMesh::NumericVector< T >::insert(), libMesh::libmesh_assert(), and libMesh::DenseSubVector< T >::size().
 {
   libmesh_assert(v.size() == dof_indices.size());
   if (!v.empty())
     this->insert(&v(0), dof_indices);
 }
template<typename T > Real libMesh::EpetraVector< T >::l1_norm () const virtual
Returns
the -norm of the vector, i.e. the sum of the absolute values.
Implements libMesh::NumericVector< T >.
Definition at line 69 of file trilinos_epetra_vector.C.
References libMesh::closed(), libMesh::libmesh_assert(), and libMesh::Real.
 {
   libmesh_assert(this->closed());
   Real value;
   _vec->Norm1(&value);
   return value;
 }
template<typename T > Real libMesh::EpetraVector< T >::l2_norm () const virtual
Returns
the -norm of the vector, i.e. the square root of the sum of the squares of the elements.
Implements libMesh::NumericVector< T >.
Definition at line 81 of file trilinos_epetra_vector.C.
References libMesh::closed(), libMesh::libmesh_assert(), and libMesh::Real.
 {
   libmesh_assert(this->closed());
   Real value;
   _vec->Norm2(&value);
   return value;
 }
template<typename T > numeric_index_type libMesh::EpetraVector< T >::last_local_index () const inline virtual
Returns
the index of the last vector element actually stored on this processor
Implements libMesh::NumericVector< T >.
Definition at line 960 of file trilinos_epetra_vector.h.
References libMesh::EpetraVector< T >::_vec, libMesh::NumericVector< T >::initialized(), and libMesh::libmesh_assert().
Referenced by libMesh::EpetraVector< T >::operator()().
 {
   libmesh_assert (this->initialized());
   return _vec->Map().MaxMyGID()+1;
 }
template<typename T > Real libMesh::EpetraVector< T >::linfty_norm () const virtual
Returns
the maximum absolute value of the elements of this vector, which is the -norm of a vector.
Implements libMesh::NumericVector< T >.
Definition at line 93 of file trilinos_epetra_vector.C.
References libMesh::closed(), libMesh::libmesh_assert(), and libMesh::Real.
 {
   libmesh_assert(this->closed());
   Real value;
   _vec->NormInf(&value);
   return value;
 }
template<typename T> int libMesh::NumericVector< T >::local_relative_compare (const NumericVector< T > & other_vector, const Real threshold = TOLERANCE) const virtual inherited
Returns
-1 when this is equivalent to other_vector, up to the given local relative threshold. When differences occur, the return value contains the first index where the difference (a[i]-b[i])/max(a[i],b[i]) exceeded the threshold. When no threshold is given, the libMesh TOLERANCE is used.
Definition at line 148 of file numeric_vector.C.
References std::abs(), libMesh::NumericVector< T >::first_local_index(), libMesh::NumericVector< T >::initialized(), libMesh::initialized(), libMesh::NumericVector< T >::last_local_index(), libMesh::libmesh_assert(), and std::max().
Referenced by libMesh::NumericVector< Number >::operator/=().
 {
   libmesh_assert (this->initialized());
   libmesh_assert (other_vector.initialized());
   libmesh_assert_equal_to (this->first_local_index(), other_vector.first_local_index());
   libmesh_assert_equal_to (this->last_local_index(), other_vector.last_local_index());
   int first_different_i = std::numeric_limits<int>::max();
   numeric_index_type i = first_local_index();
   do
     {
       if (std::abs((*this)(i) - other_vector(i)) > threshold *
           std::max(std::abs((*this)(i)), std::abs(other_vector(i))))
         first_different_i = i;
       else
         i++;
     }
   while (first_different_i==std::numeric_limits<int>::max()
          && i<last_local_index());
   // Find the correct first differing index in parallel
   this->comm().min(first_different_i);
   if (first_different_i == std::numeric_limits<int>::max())
     return -1;
   return first_different_i;
 }
template<typename T > numeric_index_type libMesh::EpetraVector< T >::local_size () const inline virtual
Returns
the local size of the vector (index_stop-index_start)
Implements libMesh::NumericVector< T >.
Definition at line 940 of file trilinos_epetra_vector.h.
References libMesh::EpetraVector< T >::_vec, libMesh::NumericVector< T >::initialized(), and libMesh::libmesh_assert().
 {
   libmesh_assert (this->initialized());
   return _vec->MyLength();
 }
template<typename T > void libMesh::EpetraVector< T >::localize (std::vector< T > & v_local) const virtual
Creates a copy of the global vector in the local vector v_local.
Implements libMesh::NumericVector< T >.
Definition at line 523 of file trilinos_epetra_vector.C.
References libMesh::libmesh_assert().
Referenced by libMesh::EpetraVector< T >::localize().
 {
   // This function must be run on all processors at once
   parallel_object_only();
   const unsigned int n  = this->size();
   const unsigned int nl = this->local_size();
   libmesh_assert(this->_vec);
   v_local.clear();
   v_local.reserve(n);
   // build up my local part
   for (unsigned int i=0; i<nl; i++)
     v_local.push_back((*this->_vec)[i]);
   this->comm().allgather (v_local);
 }
template<typename T > void libMesh::EpetraVector< T >::localize (NumericVector< T > & v_local) const virtual
Same, but fills a NumericVector<T> instead of a std::vector.
Implements libMesh::NumericVector< T >.
Definition at line 411 of file trilinos_epetra_vector.C.
References libMesh::EpetraVector< T >::_vec.
 {
   EpetraVector<T> * v_local = cast_ptr<EpetraVector<T> *>(&v_local_in);
   Epetra_Map rootMap = Epetra_Util::Create_Root_Map( *_map, -1);
   v_local->_vec->ReplaceMap(rootMap);
   Epetra_Import importer(v_local->_vec->Map(), *_map);
   v_local->_vec->Import(*_vec, importer, Insert);
 }
template<typename T > void libMesh::EpetraVector< T >::localize (NumericVector< T > & v_local, const std::vector< numeric_index_type > & send_list) const virtual
Creates a local vector v_local containing only information relevant to this processor, as defined by the send_list.
Implements libMesh::NumericVector< T >.
Definition at line 425 of file trilinos_epetra_vector.C.
 {
   // TODO: optimize to sync only the send list values
   this->localize(v_local_in);
   //   EpetraVector<T> * v_local =
   //   cast_ptr<EpetraVector<T> *>(&v_local_in);
   //   libmesh_assert(this->_map.get());
   //   libmesh_assert(v_local->_map.get());
   //   libmesh_assert_equal_to (v_local->local_size(), this->size());
   //   libmesh_assert_less_equal (send_list.size(), v_local->size());
   //   Epetra_Import importer (*v_local->_map, *this->_map);
   //   v_local->_vec->Import (*this->_vec, importer, Insert);
 }
template<typename T > void libMesh::EpetraVector< T >::localize (std::vector< T > & v_local, const std::vector< numeric_index_type > & indices) const virtual
Fill in the local std::vector "v_local" with the global indices given in "indices". See numeric_vector.h for more details.
Implements libMesh::NumericVector< T >.
Definition at line 447 of file trilinos_epetra_vector.C.
 {
   // Create a "replicated" map for importing values.  This is
   // equivalent to creating a general Epetra_Map with
   // NumGlobalElements == NumMyElements.
   Epetra_LocalMap import_map(static_cast<int>(indices.size()),
                              /*IndexBase=*/0,
                              _map->Comm());
   // Get a pointer to the list of global elements for the map, and set
   // all the values from indices.
   int * import_map_global_elements = import_map.MyGlobalElements();
   for (int i=0; i<import_map.NumMyElements(); ++i)
     import_map_global_elements[i] = indices[i];
   // Create a new EpetraVector to import values into.
   Epetra_Vector import_vector(import_map);
   // Set up an "Import" object which associates the two maps.
   Epetra_Import import_object(import_map, *_map);
   // Import the values
   import_vector.Import(*_vec, import_object, Insert);
   // Get a pointer to the imported values array and the length of the
   // array.
   T * values = import_vector.Values();
   int import_vector_length = import_vector.MyLength();
   // Copy the imported values into v_local
   v_local.resize(import_vector_length);
   for (int i=0; i<import_vector_length; ++i)
     v_local[i] = values[i];
 }
template<typename T > void libMesh::EpetraVector< T >::localize (const numeric_index_type first_local_idx, const numeric_index_type last_local_idx, const std::vector< numeric_index_type > & send_list) virtual
Updates a local vector with selected values from neighboring processors, as defined by send_list.
Implements libMesh::NumericVector< T >.
Definition at line 486 of file trilinos_epetra_vector.C.
References libMesh::EpetraVector< T >::close(), libMesh::EpetraVector< T >::init(), libMesh::EpetraVector< T >::localize(), libMesh::PARALLEL, and libMesh::EpetraVector< T >::set().
 {
   // Only good for serial vectors.
   libmesh_assert_equal_to (this->size(), this->local_size());
   libmesh_assert_greater (last_local_idx, first_local_idx);
   libmesh_assert_less_equal (send_list.size(), this->size());
   libmesh_assert_less (last_local_idx, this->size());
   const unsigned int my_size       = this->size();
   const unsigned int my_local_size = (last_local_idx - first_local_idx + 1);
   // Don't bother for serial cases
   if ((first_local_idx == 0) &&
       (my_local_size == my_size))
     return;
   // Build a parallel vector, initialize it with the local
   // parts of (*this)
   EpetraVector<T> parallel_vec(this->comm(), PARALLEL);
   parallel_vec.init (my_size, my_local_size, true, PARALLEL);
   // Copy part of *this into the parallel_vec
   for (numeric_index_type i=first_local_idx; i<=last_local_idx; i++)
     parallel_vec.set(i,this->el(i));
   // localize like normal
   parallel_vec.close();
   parallel_vec.localize (*this, send_list);
   this->close();
 }
template<typename T > void libMesh::EpetraVector< T >::localize_to_one (std::vector< T > & v_local, const processor_id_type proc_id = 0) const virtual
Creates a local copy of the global vector in v_local only on processor proc_id. By default the data is sent to processor 0. This method is useful for outputting data from one processor.
Implements libMesh::NumericVector< T >.
Definition at line 546 of file trilinos_epetra_vector.C.
References libMesh::libmesh_assert(), and libMesh::n_processors().
 {
   // This function must be run on all processors at once
   parallel_object_only();
   const unsigned int n  = this->size();
   const unsigned int nl = this->local_size();
   libmesh_assert_less (pid, this->n_processors());
   libmesh_assert(this->_vec);
   v_local.clear();
   v_local.reserve(n);
   // build up my local part
   for (unsigned int i=0; i<nl; i++)
     v_local.push_back((*this->_vec)[i]);
   this->comm().gather (pid, v_local);
 }
template<typename T > Real libMesh::EpetraVector< T >::max () const inline virtual
Returns
the maximum element in the vector. In case of complex numbers, this returns the maximum Real part.
Implements libMesh::NumericVector< T >.
Definition at line 998 of file trilinos_epetra_vector.h.
References libMesh::EpetraVector< T >::_vec, libMesh::NumericVector< T >::initialized(), and libMesh::libmesh_assert().
 {
   libmesh_assert (this->initialized());
   T value;
   _vec->MaxValue(&value);
   return value;
 }
template<typename T > Real libMesh::EpetraVector< T >::min () const inline virtual
Returns
the minimum element in the vector. In case of complex numbers, this returns the minimum Real part.
Implements libMesh::NumericVector< T >.
Definition at line 983 of file trilinos_epetra_vector.h.
References libMesh::EpetraVector< T >::_vec, libMesh::NumericVector< T >::initialized(), and libMesh::libmesh_assert().
 {
   libmesh_assert (this->initialized());
   T value;
   _vec->MinValue(&value);
   return value;
 }
static unsigned int libMesh::ReferenceCounter::n_objects () inline static inherited
Prints the number of outstanding (created, but not yet destroyed) objects.
Definition at line 85 of file reference_counter.h.
References libMesh::ReferenceCounter::_n_objects, libMesh::ReferenceCounter::disable_print_counter_info(), libMesh::ReferenceCounter::enable_print_counter_info(), libMesh::ReferenceCounter::increment_constructor_count(), libMesh::ReferenceCounter::increment_destructor_count(), and libMesh::Quality::name().
Referenced by libMesh::System::hide_output(), and libMesh::LibMeshInit::LibMeshInit().
   { return _n_objects; }
processor_id_type libMesh::ParallelObject::n_processors () const inline inherited
Returns
the number of processors in the group.
Definition at line 93 of file parallel_object.h.
References libMesh::ParallelObject::_communicator, and libMesh::Parallel::Communicator::size().
Referenced by libMesh::ParmetisPartitioner::_do_repartition(), libMesh::BoundaryInfo::_find_id_maps(), libMesh::DistributedMesh::add_elem(), libMesh::DistributedMesh::add_node(), libMesh::LaplaceMeshSmoother::allgather_graph(), libMesh::FEMSystem::assembly(), libMesh::ParmetisPartitioner::assign_partitioning(), libMesh::AztecLinearSolver< T >::AztecLinearSolver(), libMesh::MeshCommunication::broadcast(), libMesh::BoundaryInfo::build_node_list_from_side_list(), libMesh::DistributedMesh::clear(), libMesh::Nemesis_IO_Helper::compute_border_node_ids(), libMesh::Nemesis_IO_Helper::construct_nemesis_filename(), libMesh::MeshTools::correct_node_proc_ids(), libMesh::UnstructuredMesh::create_pid_mesh(), libMesh::MeshTools::create_processor_bounding_box(), libMesh::DofMap::distribute_dofs(), libMesh::DofMap::distribute_local_dofs_node_major(), libMesh::DofMap::distribute_local_dofs_var_major(), libMesh::DistributedMesh::DistributedMesh(), libMesh::EnsightIO::EnsightIO(), libMesh::MeshCommunication::gather(), libMesh::MeshCommunication::gather_neighboring_elements(), libMesh::MeshBase::get_info(), libMesh::EquationSystems::get_solution(), libMesh::DistributedVector< T >::init(), libMesh::SystemSubsetBySubdomain::init(), libMesh::ParmetisPartitioner::initialize(), libMesh::Nemesis_IO_Helper::initialize(), libMesh::DistributedMesh::insert_elem(), libMesh::MeshTools::libmesh_assert_parallel_consistent_procids< Elem >(), libMesh::MeshTools::libmesh_assert_parallel_consistent_procids< Node >(), libMesh::MeshTools::libmesh_assert_topology_consistent_procids< Node >(), libMesh::MeshTools::libmesh_assert_valid_boundary_ids(), libMesh::MeshTools::libmesh_assert_valid_dof_ids(), libMesh::MeshTools::libmesh_assert_valid_neighbors(), libMesh::MeshTools::libmesh_assert_valid_refinement_flags(), libMesh::DofMap::local_variable_indices(), libMesh::MeshBase::n_active_elem_on_proc(), libMesh::MeshBase::n_elem_on_proc(), libMesh::MeshBase::n_nodes_on_proc(), libMesh::SparsityPattern::Build::parallel_sync(), libMesh::Partitioner::partition(), libMesh::MeshBase::partition(), libMesh::Partitioner::partition_unpartitioned_elements(), libMesh::PetscLinearSolver< T >::PetscLinearSolver(), libMesh::System::point_gradient(), libMesh::System::point_hessian(), libMesh::System::point_value(), libMesh::SparseMatrix< T >::print(), libMesh::NameBasedIO::read(), libMesh::Nemesis_IO::read(), libMesh::CheckpointIO::read(), libMesh::XdrIO::read(), libMesh::CheckpointIO::read_connectivity(), libMesh::CheckpointIO::read_nodes(), libMesh::MeshCommunication::redistribute(), libMesh::DistributedMesh::renumber_dof_objects(), libMesh::Partitioner::repartition(), libMesh::MeshCommunication::send_coarse_ghosts(), libMesh::Partitioner::set_node_processor_ids(), libMesh::DofMap::set_nonlocal_dof_objects(), libMesh::Parallel::Sort< KeyType, IdxType >::sort(), libMesh::DistributedMesh::update_parallel_id_counts(), libMesh::GMVIO::write_binary(), libMesh::GMVIO::write_discontinuous_gmv(), libMesh::XdrIO::write_serialized_bcs_helper(), libMesh::XdrIO::write_serialized_connectivity(), libMesh::XdrIO::write_serialized_nodes(), and libMesh::XdrIO::write_serialized_nodesets().
   { return cast_int<processor_id_type>(_communicator.size()); }
template<typename T > T libMesh::EpetraVector< T >::operator() (const numeric_index_type i) const inline virtual
Access components, returns U(i).
Implements libMesh::NumericVector< T >.
Definition at line 970 of file trilinos_epetra_vector.h.
References libMesh::EpetraVector< T >::_vec, libMesh::EpetraVector< T >::first_local_index(), libMesh::NumericVector< T >::initialized(), libMesh::EpetraVector< T >::last_local_index(), and libMesh::libmesh_assert().
 {
   libmesh_assert (this->initialized());
   libmesh_assert ( ((i >= this->first_local_index()) &&
                     (i <  this->last_local_index())) );
   return (*_vec)[i-this->first_local_index()];
 }
template<typename T> NumericVector<T>& libMesh::NumericVector< T >::operator*= (const T a) inline inherited
Multiplication operator. Equivalent to U.scale(a)
Definition at line 384 of file numeric_vector.h.
 { this->scale(a); return *this; }
template<typename T > NumericVector< T > & libMesh::EpetraVector< T >::operator+= (const NumericVector< T > & v) virtual
Addition operator. Fast equivalent to U.add(1, V).
Implements libMesh::NumericVector< T >.
Definition at line 106 of file trilinos_epetra_vector.C.
References libMesh::closed(), and libMesh::libmesh_assert().
 {
   libmesh_assert(this->closed());
   this->add(1., v);
   return *this;
 }
template<typename T > NumericVector< T > & libMesh::EpetraVector< T >::operator-= (const NumericVector< T > & v) virtual
Subtraction operator. Fast equivalent to U.add(-1, V).
Implements libMesh::NumericVector< T >.
Definition at line 119 of file trilinos_epetra_vector.C.
References libMesh::closed(), and libMesh::libmesh_assert().
 {
   libmesh_assert(this->closed());
   this->add(-1., v);
   return *this;
 }
template<typename T > NumericVector< T > & libMesh::EpetraVector< T >::operator/= (NumericVector< T > & v) virtual
Pointwise Division operator. ie divide every entry in this vector by the entry in v
Implements libMesh::NumericVector< T >.
Definition at line 131 of file trilinos_epetra_vector.C.
References libMesh::closed(), libMesh::libmesh_assert(), and libMesh::NumericVector< T >::size().
 {
   libmesh_assert(this->closed());
   libmesh_assert_equal_to(size(), v.size());
   EpetraVector<T> & v_vec = cast_ref<EpetraVector<T> &>(v);
   _vec->ReciprocalMultiply(1.0, *v_vec._vec, *_vec, 0.0);
   return *this;
 }
template<typename T> NumericVector<T>& libMesh::NumericVector< T >::operator/= (const T a) inline inherited
Division operator. Equivalent to U.scale(1./a)
Definition at line 390 of file numeric_vector.h.
Referenced by libMesh::NumericVector< Number >::operator/=().
 { this->scale(1./a); return *this; }
template<typename T > NumericVector< T > & libMesh::EpetraVector< T >::operator= (const T s) virtual
: fill all components.
Implements libMesh::NumericVector< T >.
Definition at line 337 of file trilinos_epetra_vector.C.
 {
   _vec->PutScalar(s_in);
   return *this;
 }
template<typename T > NumericVector< T > & libMesh::EpetraVector< T >::operator= (const NumericVector< T > & v) virtual
: copy all components.
Implements libMesh::NumericVector< T >.
Definition at line 348 of file trilinos_epetra_vector.C.
 {
   const EpetraVector<T> * v = cast_ptr<const EpetraVector<T> *>(&v_in);
   *this = *v;
   return *this;
 }
template<typename T > EpetraVector< T > & libMesh::EpetraVector< T >::operator= (const EpetraVector< T > & v)
: copy all components.
Definition at line 361 of file trilinos_epetra_vector.C.
References libMesh::EpetraVector< T >::_vec.
 {
   (*_vec) = *v._vec;
   // FIXME - what about our communications data?
   return *this;
 }
template<typename T > NumericVector< T > & libMesh::EpetraVector< T >::operator= (const std::vector< T > & v) virtual
: copy all components.
Case 1: The vector is the same size of The global vector. Only add the local components.
Case 2: The vector is the same size as our local piece. Insert directly to the local piece.
Implements libMesh::NumericVector< T >.
Definition at line 374 of file trilinos_epetra_vector.C.
 {
   T * values = _vec->Values();
   if (this->size() == v.size())
     {
       const unsigned int nl=this->local_size();
       const unsigned int fli=this->first_local_index();
       for (unsigned int i=0;i<nl;i++)
         values[i]=v[fli+i];
     }
   else
     {
       libmesh_assert_equal_to (v.size(), this->local_size());
       const unsigned int nl=this->local_size();
       for (unsigned int i=0;i<nl;i++)
         values[i]=v[i];
     }
   return *this;
 }
template<typename T > void libMesh::EpetraVector< T >::pointwise_mult (const NumericVector< T > & vec1, const NumericVector< T > & vec2) virtual
Computes the pointwise (i.e. component-wise) product of vec1 and vec2 and stores the result in *this.
Implements libMesh::NumericVector< T >.
Definition at line 325 of file trilinos_epetra_vector.C.
References libMesh::EpetraVector< T >::_vec.
 {
   const EpetraVector<T> * V1 = cast_ptr<const EpetraVector<T> *>(&vec1);
   const EpetraVector<T> * V2 = cast_ptr<const EpetraVector<T> *>(&vec2);
   _vec->Multiply(1.0, *V1->_vec, *V2->_vec, 0.0);
 }
template<typename T > void libMesh::NumericVector< T >::print (std::ostream & os = libMesh::out) const inline virtual inherited
Prints the local contents of the vector, by default to libMesh::out
Definition at line 924 of file numeric_vector.h.
References libMesh::NumericVector< T >::first_local_index(), libMesh::NumericVector< T >::initialized(), libMesh::NumericVector< T >::last_local_index(), libMesh::libmesh_assert(), libMesh::NumericVector< T >::local_size(), and libMesh::NumericVector< T >::size().
Referenced by libMesh::NumericVector< Number >::operator/=().
 {
   libmesh_assert (this->initialized());
   os << "Size\tglobal =  " << this->size()
      << "\t\tlocal =  " << this->local_size() << std::endl;
   os << "#\tValue" << std::endl;
   for (numeric_index_type i=this->first_local_index(); i<this->last_local_index(); i++)
     os << i << "\t" << (*this)(i) << std::endl;
 }
template<> void libMesh::NumericVector< Complex >::print (std::ostream & os) const inline inherited
Definition at line 906 of file numeric_vector.h.
References libMesh::NumericVector< T >::first_local_index(), libMesh::NumericVector< T >::initialized(), libMesh::NumericVector< T >::last_local_index(), libMesh::libmesh_assert(), libMesh::NumericVector< T >::local_size(), and libMesh::NumericVector< T >::size().
 {
   libmesh_assert (this->initialized());
   os << "Size\tglobal =  " << this->size()
      << "\t\tlocal =  " << this->local_size() << std::endl;
   // std::complex<>::operator<<() is defined, but use this form
   os << "#\tReal part\t\tImaginary part" << std::endl;
   for (numeric_index_type i=this->first_local_index(); i<this->last_local_index(); i++)
     os << i << "\t"
        << (*this)(i).real() << "\t\t"
        << (*this)(i).imag() << std::endl;
 }
template<typename T > void libMesh::NumericVector< T >::print_global (std::ostream & os = libMesh::out) const inline virtual inherited
Prints the global contents of the vector, by default to libMesh::out
Definition at line 961 of file numeric_vector.h.
References libMesh::NumericVector< T >::initialized(), libMesh::libmesh_assert(), libMesh::NumericVector< T >::localize(), libMesh::ParallelObject::processor_id(), and libMesh::NumericVector< T >::size().
Referenced by libMesh::NumericVector< Number >::operator/=().
 {
   libmesh_assert (this->initialized());
   std::vector<T> v(this->size());
   this->localize(v);
   // Right now we only want one copy of the output
   if (this->processor_id())
     return;
   os << "Size\tglobal =  " << this->size() << std::endl;
   os << "#\tValue" << std::endl;
   for (numeric_index_type i=0; i!=v.size(); i++)
     os << i << "\t" << v[i] << std::endl;
 }
template<> void libMesh::NumericVector< Complex >::print_global (std::ostream & os) const inline inherited
Definition at line 939 of file numeric_vector.h.
References libMesh::NumericVector< T >::initialized(), libMesh::libmesh_assert(), libMesh::NumericVector< T >::localize(), libMesh::ParallelObject::processor_id(), and libMesh::NumericVector< T >::size().
 {
   libmesh_assert (this->initialized());
   std::vector<Complex> v(this->size());
   this->localize(v);
   // Right now we only want one copy of the output
   if (this->processor_id())
     return;
   os << "Size\tglobal =  " << this->size() << std::endl;
   os << "#\tReal part\t\tImaginary part" << std::endl;
   for (numeric_index_type i=0; i!=v.size(); i++)
     os << i << "\t"
        << v[i].real() << "\t\t"
        << v[i].imag() << std::endl;
 }
void libMesh::ReferenceCounter::print_info (std::ostream & out = libMesh::out) static inherited
Prints the reference information, by default to libMesh::out.
Definition at line 88 of file reference_counter.C.
References libMesh::ReferenceCounter::_enable_print_counter, and libMesh::ReferenceCounter::get_info().
Referenced by libMesh::LibMeshInit::LibMeshInit().
 {
   if (_enable_print_counter)
     out_stream << ReferenceCounter::get_info();
 }
template<typename T> virtual void libMesh::NumericVector< T >::print_matlab (const std::string & = "") const inline virtual inherited
Print the contents of the matrix in Matlab's sparse matrix format. Optionally prints the matrix to the file named name. If name is not specified it is dumped to the screen.
Reimplemented in libMesh::PetscVector< T >.
Definition at line 680 of file numeric_vector.h.
   {
     libmesh_not_implemented();
   }
processor_id_type libMesh::ParallelObject::processor_id () const inline inherited
Returns
the rank of this processor in the group.
Definition at line 99 of file parallel_object.h.
References libMesh::ParallelObject::_communicator, and libMesh::Parallel::Communicator::rank().
Referenced by libMesh::BoundaryInfo::_find_id_maps(), libMesh::EquationSystems::_read_impl(), libMesh::DistributedMesh::add_elem(), libMesh::BoundaryInfo::add_elements(), libMesh::DofMap::add_neighbors_to_send_list(), libMesh::DistributedMesh::add_node(), libMesh::MeshRefinement::add_node(), libMesh::MeshTools::Modification::all_tri(), libMesh::FEMSystem::assembly(), libMesh::ParmetisPartitioner::assign_partitioning(), libMesh::MeshCommunication::broadcast(), libMesh::EquationSystems::build_discontinuous_solution_vector(), libMesh::Nemesis_IO_Helper::build_element_and_node_maps(), libMesh::ParmetisPartitioner::build_graph(), libMesh::InfElemBuilder::build_inf_elem(), libMesh::BoundaryInfo::build_node_list_from_side_list(), libMesh::DofMap::build_sparsity(), libMesh::DistributedMesh::clear(), libMesh::ExodusII_IO_Helper::close(), libMesh::Nemesis_IO_Helper::compute_border_node_ids(), libMesh::Nemesis_IO_Helper::compute_communication_map_parameters(), libMesh::Nemesis_IO_Helper::compute_internal_and_border_elems_and_internal_nodes(), libMesh::Nemesis_IO_Helper::compute_node_communication_maps(), libMesh::Nemesis_IO_Helper::compute_num_global_elem_blocks(), libMesh::Nemesis_IO_Helper::compute_num_global_nodesets(), libMesh::Nemesis_IO_Helper::compute_num_global_sidesets(), libMesh::Nemesis_IO_Helper::construct_nemesis_filename(), libMesh::MeshTools::correct_node_proc_ids(), libMesh::ExodusII_IO_Helper::create(), libMesh::DistributedMesh::delete_elem(), libMesh::DistributedMesh::delete_node(), libMesh::MeshCommunication::delete_remote_elements(), libMesh::DofMap::distribute_dofs(), libMesh::DofMap::distribute_local_dofs_node_major(), libMesh::DofMap::distribute_local_dofs_var_major(), libMesh::DistributedMesh::DistributedMesh(), libMesh::EnsightIO::EnsightIO(), libMesh::MeshFunction::find_element(), libMesh::MeshFunction::find_elements(), libMesh::UnstructuredMesh::find_neighbors(), libMesh::MeshCommunication::gather(), libMesh::MeshCommunication::gather_neighboring_elements(), libMesh::Nemesis_IO_Helper::get_cmap_params(), libMesh::Nemesis_IO_Helper::get_eb_info_global(), libMesh::Nemesis_IO_Helper::get_elem_cmap(), libMesh::Nemesis_IO_Helper::get_elem_map(), libMesh::MeshBase::get_info(), libMesh::DofMap::get_info(), libMesh::Nemesis_IO_Helper::get_init_global(), libMesh::Nemesis_IO_Helper::get_init_info(), libMesh::Nemesis_IO_Helper::get_loadbal_param(), libMesh::Nemesis_IO_Helper::get_node_cmap(), libMesh::Nemesis_IO_Helper::get_node_map(), libMesh::Nemesis_IO_Helper::get_ns_param_global(), libMesh::EquationSystems::get_solution(), libMesh::Nemesis_IO_Helper::get_ss_param_global(), libMesh::SparsityPattern::Build::handle_vi_vj(), libMesh::DistributedVector< T >::init(), libMesh::SystemSubsetBySubdomain::init(), libMesh::ParmetisPartitioner::initialize(), libMesh::ExodusII_IO_Helper::initialize(), libMesh::ExodusII_IO_Helper::initialize_element_variables(), libMesh::ExodusII_IO_Helper::initialize_global_variables(), libMesh::ExodusII_IO_Helper::initialize_nodal_variables(), libMesh::DistributedMesh::insert_elem(), libMesh::DofMap::is_evaluable(), libMesh::SparsityPattern::Build::join(), libMesh::MeshTools::libmesh_assert_parallel_consistent_procids< Elem >(), libMesh::MeshTools::libmesh_assert_parallel_consistent_procids< Node >(), libMesh::MeshTools::libmesh_assert_valid_neighbors(), libMesh::DistributedMesh::libmesh_assert_valid_parallel_object_ids(), libMesh::DofMap::local_variable_indices(), libMesh::MeshRefinement::make_coarsening_compatible(), libMesh::MeshBase::n_active_local_elem(), libMesh::BoundaryInfo::n_boundary_conds(), libMesh::BoundaryInfo::n_edge_conds(), libMesh::System::n_local_dofs(), libMesh::MeshBase::n_local_elem(), libMesh::MeshBase::n_local_nodes(), libMesh::BoundaryInfo::n_nodeset_conds(), libMesh::BoundaryInfo::n_shellface_conds(), libMesh::WeightedPatchRecoveryErrorEstimator::EstimateError::operator()(), libMesh::SparsityPattern::Build::operator()(), libMesh::PatchRecoveryErrorEstimator::EstimateError::operator()(), libMesh::SparsityPattern::Build::parallel_sync(), libMesh::MetisPartitioner::partition_range(), libMesh::System::point_gradient(), libMesh::System::point_hessian(), libMesh::System::point_value(), libMesh::SparseMatrix< T >::print(), libMesh::NumericVector< T >::print_global(), libMesh::Nemesis_IO_Helper::put_cmap_params(), libMesh::Nemesis_IO_Helper::put_elem_cmap(), libMesh::Nemesis_IO_Helper::put_elem_map(), libMesh::Nemesis_IO_Helper::put_loadbal_param(), libMesh::Nemesis_IO_Helper::put_node_cmap(), libMesh::Nemesis_IO_Helper::put_node_map(), libMesh::NameBasedIO::read(), libMesh::Nemesis_IO::read(), libMesh::CheckpointIO::read(), libMesh::XdrIO::read(), libMesh::ExodusII_IO_Helper::read_elem_num_map(), libMesh::ExodusII_IO_Helper::read_node_num_map(), libMesh::XdrIO::read_serialized_bc_names(), libMesh::XdrIO::read_serialized_bcs_helper(), libMesh::XdrIO::read_serialized_connectivity(), libMesh::XdrIO::read_serialized_nodes(), libMesh::XdrIO::read_serialized_nodesets(), libMesh::XdrIO::read_serialized_subdomain_names(), libMesh::MeshCommunication::redistribute(), libMesh::DistributedMesh::renumber_dof_objects(), libMesh::MeshCommunication::send_coarse_ghosts(), libMesh::Partitioner::set_node_processor_ids(), libMesh::DofMap::set_nonlocal_dof_objects(), libMesh::LaplaceMeshSmoother::smooth(), libMesh::MeshTools::total_weight(), libMesh::Parallel::Packing< Node * >::unpack(), libMesh::Parallel::Packing< Elem * >::unpack(), libMesh::DistributedMesh::update_parallel_id_counts(), libMesh::MeshTools::weight(), libMesh::NameBasedIO::write(), libMesh::CheckpointIO::write(), libMesh::XdrIO::write(), libMesh::EquationSystems::write(), libMesh::GMVIO::write_discontinuous_gmv(), libMesh::ExodusII_IO::write_element_data(), libMesh::ExodusII_IO_Helper::write_element_values(), libMesh::ExodusII_IO_Helper::write_elements(), libMesh::ExodusII_IO::write_global_data(), libMesh::ExodusII_IO_Helper::write_global_values(), libMesh::ExodusII_IO::write_information_records(), libMesh::ExodusII_IO_Helper::write_information_records(), libMesh::ExodusII_IO_Helper::write_nodal_coordinates(), libMesh::UCDIO::write_nodal_data(), libMesh::ExodusII_IO::write_nodal_data(), libMesh::ExodusII_IO::write_nodal_data_discontinuous(), libMesh::ExodusII_IO_Helper::write_nodal_values(), libMesh::Nemesis_IO_Helper::write_nodesets(), libMesh::ExodusII_IO_Helper::write_nodesets(), libMesh::XdrIO::write_serialized_bc_names(), libMesh::XdrIO::write_serialized_bcs_helper(), libMesh::XdrIO::write_serialized_connectivity(), libMesh::XdrIO::write_serialized_nodes(), libMesh::XdrIO::write_serialized_nodesets(), libMesh::XdrIO::write_serialized_subdomain_names(), libMesh::Nemesis_IO_Helper::write_sidesets(), libMesh::ExodusII_IO_Helper::write_sidesets(), libMesh::ExodusII_IO::write_timestep(), and libMesh::ExodusII_IO_Helper::write_timestep().
   { return cast_int<processor_id_type>(_communicator.rank()); }
template<typename T > void libMesh::EpetraVector< T >::reciprocal () virtual
Replace each entry v_i of this vector by its reciprocal, 1/v_i.
Implements libMesh::NumericVector< T >.
Definition at line 162 of file trilinos_epetra_vector.C.
References std::abs(), and std::min().
 {
   // The Epetra::reciprocal() function takes a constant reference to *another* vector,
   // and fills _vec with its reciprocal.  Does that mean we can't pass *_vec as the
   // argument?
   // _vec->reciprocal( *_vec );
   // Alternatively, compute the reciprocal by hand... see also the add(T) member that does this...
   const unsigned int nl = _vec->MyLength();
   T * values = _vec->Values();
   for (unsigned int i=0; i<nl; i++)
     {
       // Don't divide by zero (maybe only check this in debug mode?)
       if (std::abs(values[i]) < std::numeric_limits<T>::min())
         libmesh_error_msg("Error, divide by zero in DistributedVector<T>::reciprocal()!");
       values[i] = 1. / values[i];
     }
   // Leave the vector in a closed state...
   this->close();
 }
template<typename T > int libMesh::EpetraVector< T >::ReplaceGlobalValues (int numIDs, const int * GIDs, const double * values) private
Copy values into the vector overwriting any values that already exist for the specified indices.
Definition at line 619 of file trilinos_epetra_vector.C.
 {
   return( inputValues( numIDs, GIDs, values, false) );
 }
template<typename T > int libMesh::EpetraVector< T >::ReplaceGlobalValues (const Epetra_IntSerialDenseVector & GIDs, const Epetra_SerialDenseVector & values) private
Copy values into the vector, replacing any values that already exist for the specified GIDs.
Parameters
GIDs List of global ids. Must be the same length as the accompanying list of values.
values List of coefficient values. Must be the same length as the accompanying list of GIDs.
Definition at line 628 of file trilinos_epetra_vector.C.
 {
   if (GIDs.Length() != values.Length()) {
     return(-1);
   }
   return( inputValues( GIDs.Length(), GIDs.Values(), values.Values(), false) );
 }
template<typename T > int libMesh::EpetraVector< T >::ReplaceGlobalValues (int numIDs, const int * GIDs, const int * numValuesPerID, const double * values) private
Definition at line 640 of file trilinos_epetra_vector.C.
 {
   return( inputValues( numIDs, GIDs, numValuesPerID, values, false) );
 }
template<typename T > void libMesh::EpetraVector< T >::scale (const T factor) virtual
Scale each element of the vector by the given factor.
Implements libMesh::NumericVector< T >.
Definition at line 299 of file trilinos_epetra_vector.C.
 {
   _vec->Scale(factor_in);
 }
template<typename T > void libMesh::EpetraVector< T >::set (const numeric_index_type i, const T value) virtual
v(i) = value
Implements libMesh::NumericVector< T >.
Definition at line 147 of file trilinos_epetra_vector.C.
Referenced by libMesh::EpetraVector< T >::localize().
 {
   int i = static_cast<int> (i_in);
   T value = value_in;
   libmesh_assert_less (i_in, this->size());
   ReplaceGlobalValues(1, &i, &value);
   this->_is_closed = false;
 }
template<typename T> void libMesh::EpetraVector< T >::setIgnoreNonLocalEntries (bool flag) inline private
Set whether or not non-local data values should be ignored.
Definition at line 557 of file trilinos_epetra_vector.h.
References libMesh::EpetraVector< T >::destroyNonlocalData(), libMesh::EpetraVector< T >::FEoperatorequals(), libMesh::EpetraVector< T >::ignoreNonLocalEntries_, libMesh::EpetraVector< T >::inputNonlocalValue(), libMesh::EpetraVector< T >::inputNonlocalValues(), and libMesh::EpetraVector< T >::inputValues().
{
     ignoreNonLocalEntries_ = flag;
   }
template<typename T > numeric_index_type libMesh::EpetraVector< T >::size () const inline virtual
Returns
dimension of the vector. This function was formerly called n(), but was renamed to get the EpetraVector<T> class closer to the C++ standard library's std::vector container.
Implements libMesh::NumericVector< T >.
Definition at line 929 of file trilinos_epetra_vector.h.
References libMesh::EpetraVector< T >::_vec, libMesh::NumericVector< T >::initialized(), and libMesh::libmesh_assert().
Referenced by libMesh::EpetraVector< T >::add().
 {
   libmesh_assert (this->initialized());
   return _vec->GlobalLength();
 }
template<class T > Real libMesh::NumericVector< T >::subset_l1_norm (const std::set< numeric_index_type > & indices) const virtual inherited
Returns
the -norm of the vector, i.e. the sum of the absolute values for the specified entries in the vector.
Note that the indices must necessary live on this processor.
Definition at line 323 of file numeric_vector.C.
References std::abs(), and libMesh::Real.
Referenced by libMesh::NumericVector< Number >::closed(), and libMesh::System::discrete_var_norm().
 {
   const NumericVector<T> & v = *this;
   std::set<numeric_index_type>::const_iterator it = indices.begin();
   const std::set<numeric_index_type>::const_iterator it_end = indices.end();
   Real norm = 0;
   for (; it!=it_end; ++it)
     norm += std::abs(v(*it));
   this->comm().sum(norm);
   return norm;
 }
template<class T > Real libMesh::NumericVector< T >::subset_l2_norm (const std::set< numeric_index_type > & indices) const virtual inherited
Returns
the -norm of the vector, i.e. the square root of the sum of the squares of the elements for the specified entries in the vector.
Note that the indices must necessary live on this processor.
Definition at line 341 of file numeric_vector.C.
References libMesh::TensorTools::norm_sq(), and libMesh::Real.
Referenced by libMesh::NumericVector< Number >::closed(), and libMesh::System::discrete_var_norm().
 {
   const NumericVector<T> & v = *this;
   std::set<numeric_index_type>::const_iterator it = indices.begin();
   const std::set<numeric_index_type>::const_iterator it_end = indices.end();
   Real norm = 0;
   for (; it!=it_end; ++it)
     norm += TensorTools::norm_sq(v(*it));
   this->comm().sum(norm);
   return std::sqrt(norm);
 }
template<class T > Real libMesh::NumericVector< T >::subset_linfty_norm (const std::set< numeric_index_type > & indices) const virtual inherited
Returns
the maximum absolute value of the specified entries of this vector, which is the -norm of a vector.
Note that the indices must necessary live on this processor.
Definition at line 359 of file numeric_vector.C.
References std::abs(), and libMesh::Real.
Referenced by libMesh::NumericVector< Number >::closed(), and libMesh::System::discrete_var_norm().
 {
   const NumericVector<T> & v = *this;
   std::set<numeric_index_type>::const_iterator it = indices.begin();
   const std::set<numeric_index_type>::const_iterator it_end = indices.end();
   Real norm = 0;
   for (; it!=it_end; ++it)
     {
       Real value = std::abs(v(*it));
       if (value > norm)
         norm = value;
     }
   this->comm().max(norm);
   return norm;
 }
template<typename T > T libMesh::EpetraVector< T >::sum () const virtual
Returns
the sum of values in a vector
Implements libMesh::NumericVector< T >.
Definition at line 50 of file trilinos_epetra_vector.C.
References libMesh::closed(), libMesh::libmesh_assert(), and libMesh::Parallel::sum().
 {
   libmesh_assert(this->closed());
   const unsigned int nl = _vec->MyLength();
   T sum=0.0;
   T * values = _vec->Values();
   for (unsigned int i=0; i<nl; i++)
     sum += values[i];
   this->comm().sum(sum);
   return sum;
 }
template<typename T > int libMesh::EpetraVector< T >::SumIntoGlobalValues (int numIDs, const int * GIDs, const double * values) private
Accumulate values into the vector, adding them to any values that already exist for the specified indices.
Definition at line 588 of file trilinos_epetra_vector.C.
 {
   return( inputValues( numIDs, GIDs, values, true) );
 }
template<typename T > int libMesh::EpetraVector< T >::SumIntoGlobalValues (const Epetra_IntSerialDenseVector & GIDs, const Epetra_SerialDenseVector & values) private
Accumulate values into the vector, adding them to any values that already exist for the specified GIDs.
Parameters
GIDs List of global ids. Must be the same length as the accompanying list of values.
values List of coefficient values. Must be the same length as the accompanying list of GIDs.
Definition at line 597 of file trilinos_epetra_vector.C.
 {
   if (GIDs.Length() != values.Length()) {
     return(-1);
   }
   return( inputValues( GIDs.Length(), GIDs.Values(), values.Values(), true) );
 }
template<typename T > int libMesh::EpetraVector< T >::SumIntoGlobalValues (int numIDs, const int * GIDs, const int * numValuesPerID, const double * values) private
Definition at line 609 of file trilinos_epetra_vector.C.
 {
   return( inputValues( numIDs, GIDs, numValuesPerID, values, true) );
 }
template<typename T > void libMesh::EpetraVector< T >::swap (NumericVector< T > & v) inline virtual
Swaps the raw Epetra vector context pointers.
Reimplemented from libMesh::NumericVector< T >.
Definition at line 1013 of file trilinos_epetra_vector.h.
References libMesh::EpetraVector< T >::_destroy_vec_on_exit, libMesh::EpetraVector< T >::_map, libMesh::EpetraVector< T >::_vec, libMesh::EpetraVector< T >::allocatedNonlocalLength_, libMesh::EpetraVector< T >::ignoreNonLocalEntries_, libMesh::EpetraVector< T >::last_edit, libMesh::EpetraVector< T >::myCoefs_, libMesh::EpetraVector< T >::myFirstID_, libMesh::EpetraVector< T >::myNumIDs_, libMesh::EpetraVector< T >::nonlocalCoefs_, libMesh::EpetraVector< T >::nonlocalElementSize_, libMesh::EpetraVector< T >::nonlocalIDs_, libMesh::EpetraVector< T >::numNonlocalIDs_, swap(), and libMesh::NumericVector< T >::swap().
Referenced by libMesh::Problem_Interface::computeF(), libMesh::Problem_Interface::computeJacobian(), and libMesh::Problem_Interface::computePreconditioner().
 {
   NumericVector<T>::swap(other);
   EpetraVector<T> & v = cast_ref<EpetraVector<T> &>(other);
   std::swap(_vec, v._vec);
   _map.swap(v._map);
   std::swap(_destroy_vec_on_exit, v._destroy_vec_on_exit);
   std::swap(myFirstID_, v.myFirstID_);
   std::swap(myNumIDs_, v.myNumIDs_);
   std::swap(myCoefs_, v.myCoefs_);
   std::swap(nonlocalIDs_, v.nonlocalIDs_);
   std::swap(nonlocalElementSize_, v.nonlocalElementSize_);
   std::swap(numNonlocalIDs_, v.numNonlocalIDs_);
   std::swap(allocatedNonlocalLength_, v.allocatedNonlocalLength_);
   std::swap(nonlocalCoefs_, v.nonlocalCoefs_);
   std::swap(last_edit, v.last_edit);
   std::swap(ignoreNonLocalEntries_, v.ignoreNonLocalEntries_);
 }
template<typename T> ParallelType libMesh::NumericVector< T >::type () const inline inherited
Returns
the type (SERIAL, PARALLEL, GHOSTED) of the vector.
Definition at line 140 of file numeric_vector.h.
Referenced by libMesh::PetscVector< T >::clone(), libMesh::PetscVector< T >::close(), libMesh::DofMap::enforce_adjoint_constraints_exactly(), libMesh::DofMap::enforce_constraints_exactly(), libMesh::EpetraVector< T >::EpetraVector(), libMesh::MeshFunction::find_element(), libMesh::MeshFunction::find_elements(), libMesh::PetscVector< T >::get(), libMesh::DistributedVector< T >::init(), libMesh::EigenSparseVector< T >::init(), libMesh::LaspackVector< T >::init(), libMesh::EpetraVector< T >::init(), libMesh::PetscVector< T >::localize(), libMesh::PetscVector< T >::operator()(), libMesh::PetscVector< T >::operator=(), libMesh::System::project_vector(), libMesh::System::read_serialized_vector(), libMesh::PetscVector< T >::zero(), and libMesh::PetscVector< T >::zero_clone().
 { return _type; }
template<typename T> ParallelType& libMesh::NumericVector< T >::type () inline inherited
Returns
the type (SERIAL, PARALLEL, GHOSTED) of the vector.
Definition at line 145 of file numeric_vector.h.
 { return _type; }
template<typename T> Epetra_Vector* libMesh::EpetraVector< T >::vec () inline
Returns the raw PETSc vector context pointer. Note this is generally not required in user-level code. Just don't do anything crazy like calling LibMeshVecDestroy()!
Definition at line 464 of file trilinos_epetra_vector.h.
References libMesh::EpetraVector< T >::_vec, and libMesh::libmesh_assert().
Referenced by libMesh::EpetraMatrix< T >::get_diagonal(), and libMesh::NoxNonlinearSolver< T >::solve().
 { libmesh_assert(_vec); return _vec; }
template<typename T > void libMesh::EpetraVector< T >::zero () inline virtual
Set all entries to zero. Equivalent to v = 0, but more obvious and faster.
Implements libMesh::NumericVector< T >.
Definition at line 894 of file trilinos_epetra_vector.h.
References libMesh::EpetraVector< T >::_vec, libMesh::NumericVector< T >::closed(), libMesh::NumericVector< T >::initialized(), and libMesh::libmesh_assert().
Referenced by libMesh::EpetraVector< T >::init().
 {
   libmesh_assert (this->initialized());
   libmesh_assert (this->closed());
   _vec->PutScalar(0.0);
 }
template<typename T > UniquePtr< NumericVector< T > > libMesh::EpetraVector< T >::zero_clone () const inline virtual
Creates a vector which has the same type, size and partitioning as this vector, but whose data is all zero. Returns it in an UniquePtr.
Implements libMesh::NumericVector< T >.
Definition at line 906 of file trilinos_epetra_vector.h.
References libMesh::AUTOMATIC, libMesh::ParallelObject::comm(), and libMesh::NumericVector< T >::init().
Referenced by libMesh::EpetraVector< T >::add_vector().
 {
   NumericVector<T> * cloned_vector = new EpetraVector<T>(this->comm(), AUTOMATIC);
   cloned_vector->init(*this);
   return UniquePtr<NumericVector<T> >(cloned_vector);
 }
Member Data Documentation
const Parallel::Communicator& libMesh::ParallelObject::_communicator protected inherited
Definition at line 105 of file parallel_object.h.
Referenced by libMesh::EquationSystems::build_parallel_solution_vector(), libMesh::ParallelObject::comm(), libMesh::EquationSystems::get_solution(), libMesh::ParallelObject::n_processors(), libMesh::ParallelObject::operator=(), and libMesh::ParallelObject::processor_id().
ReferenceCounter::Counts libMesh::ReferenceCounter::_counts static protected inherited
Actually holds the data.
Definition at line 124 of file reference_counter.h.
Referenced by libMesh::ReferenceCounter::get_info(), libMesh::ReferenceCounter::increment_constructor_count(), and libMesh::ReferenceCounter::increment_destructor_count().
template<typename T> bool libMesh::EpetraVector< T >::_destroy_vec_on_exit private
This boolean value should only be set to false for the constructor which takes a Epetra Vec object.
Definition at line 483 of file trilinos_epetra_vector.h.
Referenced by libMesh::EpetraVector< T >::clear(), libMesh::EpetraVector< T >::EpetraVector(), and libMesh::EpetraVector< T >::swap().
bool libMesh::ReferenceCounter::_enable_print_counter = true static protected inherited
Flag to control whether reference count information is printed when print_info is called.
Definition at line 143 of file reference_counter.h.
Referenced by libMesh::ReferenceCounter::disable_print_counter_info(), libMesh::ReferenceCounter::enable_print_counter_info(), and libMesh::ReferenceCounter::print_info().
template<typename T> bool libMesh::NumericVector< T >::_is_closed protected inherited
Flag to see if the Numeric assemble routines have been called yet
Definition at line 710 of file numeric_vector.h.
Referenced by libMesh::EigenSparseVector< T >::add(), libMesh::LaspackVector< T >::add(), libMesh::DistributedVector< T >::clear(), libMesh::LaspackVector< T >::clear(), libMesh::EigenSparseVector< T >::clear(), libMesh::EpetraVector< T >::clear(), libMesh::PetscVector< T >::clear(), libMesh::NumericVector< T >::clear(), libMesh::DistributedVector< T >::close(), libMesh::LaspackVector< T >::close(), libMesh::EigenSparseVector< T >::close(), libMesh::EpetraVector< T >::close(), libMesh::PetscVector< T >::close(), libMesh::NumericVector< Number >::closed(), libMesh::EpetraVector< T >::EpetraVector(), libMesh::EigenSparseVector< T >::init(), libMesh::EpetraVector< T >::init(), libMesh::PetscVector< T >::init(), libMesh::DistributedVector< T >::localize(), libMesh::DistributedVector< T >::operator=(), libMesh::PetscVector< T >::PetscVector(), libMesh::LaspackVector< T >::set(), libMesh::EigenSparseVector< T >::set(), libMesh::EigenSparseVector< T >::swap(), libMesh::NumericVector< T >::swap(), and libMesh::LaspackVector< T >::~LaspackVector().
template<typename T> bool libMesh::NumericVector< T >::_is_initialized protected inherited
Flag to tell if init has been called yet
Definition at line 716 of file numeric_vector.h.
Referenced by libMesh::DistributedVector< T >::clear(), libMesh::LaspackVector< T >::clear(), libMesh::EigenSparseVector< T >::clear(), libMesh::EpetraVector< T >::clear(), libMesh::PetscVector< T >::clear(), libMesh::NumericVector< T >::clear(), libMesh::PetscVector< T >::create_subvector(), libMesh::EpetraVector< T >::EpetraVector(), libMesh::DistributedVector< T >::init(), libMesh::EigenSparseVector< T >::init(), libMesh::EpetraVector< T >::init(), libMesh::PetscVector< T >::init(), libMesh::NumericVector< Number >::initialized(), libMesh::DistributedVector< T >::localize(), libMesh::DistributedVector< T >::operator=(), libMesh::PetscVector< T >::PetscVector(), libMesh::EigenSparseVector< T >::swap(), libMesh::NumericVector< T >::swap(), and libMesh::LaspackVector< T >::~LaspackVector().
template<typename T> UniquePtr<Epetra_Map> libMesh::EpetraVector< T >::_map private
Holds the distributed Map
Definition at line 477 of file trilinos_epetra_vector.h.
Referenced by libMesh::EpetraVector< T >::clear(), libMesh::EpetraVector< T >::EpetraVector(), libMesh::EpetraVector< T >::init(), and libMesh::EpetraVector< T >::swap().
Threads::spin_mutex libMesh::ReferenceCounter::_mutex static protected inherited
Mutual exclusion object to enable thread-safe reference counting.
Definition at line 137 of file reference_counter.h.
Threads::atomic< unsigned int > libMesh::ReferenceCounter::_n_objects static protected inherited
The number of objects. Print the reference count information when the number returns to 0.
Definition at line 132 of file reference_counter.h.
Referenced by libMesh::ReferenceCounter::n_objects(), libMesh::ReferenceCounter::ReferenceCounter(), and libMesh::ReferenceCounter::~ReferenceCounter().
template<typename T> ParallelType libMesh::NumericVector< T >::_type protected inherited
Type of vector
Definition at line 721 of file numeric_vector.h.
Referenced by libMesh::DistributedVector< T >::DistributedVector(), libMesh::EigenSparseVector< T >::EigenSparseVector(), libMesh::EpetraVector< T >::EpetraVector(), libMesh::DistributedVector< T >::init(), libMesh::EigenSparseVector< T >::init(), libMesh::EpetraVector< T >::init(), libMesh::PetscVector< T >::init(), libMesh::LaspackVector< T >::LaspackVector(), libMesh::PetscVector< T >::operator=(), libMesh::PetscVector< T >::PetscVector(), libMesh::EigenSparseVector< T >::swap(), libMesh::NumericVector< T >::swap(), libMesh::NumericVector< Number >::type(), and libMesh::LaspackVector< T >::~LaspackVector().
template<typename T> Epetra_Vector* libMesh::EpetraVector< T >::_vec private
Actual Epetra vector datatype to hold vector entries
Definition at line 472 of file trilinos_epetra_vector.h.
Referenced by libMesh::EpetraVector< T >::add(), libMesh::EpetraVector< T >::add_vector(), libMesh::EpetraVector< T >::clear(), libMesh::EpetraVector< T >::dot(), libMesh::EpetraVector< T >::EpetraVector(), libMesh::EpetraVector< T >::FEoperatorequals(), libMesh::EpetraVector< T >::first_local_index(), libMesh::EpetraVector< T >::init(), libMesh::EpetraVector< T >::last_local_index(), libMesh::EpetraVector< T >::local_size(), libMesh::EpetraVector< T >::localize(), libMesh::EpetraVector< T >::max(), libMesh::EpetraVector< T >::min(), libMesh::EpetraVector< T >::operator()(), libMesh::EpetraVector< T >::operator=(), libMesh::EpetraVector< T >::pointwise_mult(), libMesh::EpetraVector< T >::size(), libMesh::EpetraVector< T >::swap(), libMesh::EpetraVector< T >::vec(), and libMesh::EpetraVector< T >::zero().
template<typename T> int libMesh::EpetraVector< T >::allocatedNonlocalLength_ private
Definition at line 592 of file trilinos_epetra_vector.h.
Referenced by libMesh::EpetraVector< T >::EpetraVector(), libMesh::EpetraVector< T >::FEoperatorequals(), and libMesh::EpetraVector< T >::swap().
template<typename T> bool libMesh::EpetraVector< T >::ignoreNonLocalEntries_ private
Definition at line 602 of file trilinos_epetra_vector.h.
Referenced by libMesh::EpetraVector< T >::EpetraVector(), libMesh::EpetraVector< T >::setIgnoreNonLocalEntries(), and libMesh::EpetraVector< T >::swap().
template<typename T> unsigned char libMesh::EpetraVector< T >::last_edit private
Keep track of whether the last write operation on this vector was nothing (0) or a sum (1) or an add (2), so we can decide how to do the GlobalAssemble()
Definition at line 600 of file trilinos_epetra_vector.h.
Referenced by libMesh::EpetraVector< T >::close(), libMesh::EpetraVector< T >::EpetraVector(), libMesh::EpetraVector< T >::init(), and libMesh::EpetraVector< T >::swap().
template<typename T> double* libMesh::EpetraVector< T >::myCoefs_ private
Definition at line 587 of file trilinos_epetra_vector.h.
Referenced by libMesh::EpetraVector< T >::EpetraVector(), libMesh::EpetraVector< T >::init(), and libMesh::EpetraVector< T >::swap().
template<typename T> int libMesh::EpetraVector< T >::myFirstID_ private
Definition at line 585 of file trilinos_epetra_vector.h.
Referenced by libMesh::EpetraVector< T >::EpetraVector(), libMesh::EpetraVector< T >::init(), and libMesh::EpetraVector< T >::swap().
template<typename T> int libMesh::EpetraVector< T >::myNumIDs_ private
Definition at line 586 of file trilinos_epetra_vector.h.
Referenced by libMesh::EpetraVector< T >::EpetraVector(), libMesh::EpetraVector< T >::init(), and libMesh::EpetraVector< T >::swap().
template<typename T> double** libMesh::EpetraVector< T >::nonlocalCoefs_ private
Definition at line 593 of file trilinos_epetra_vector.h.
Referenced by libMesh::EpetraVector< T >::EpetraVector(), libMesh::EpetraVector< T >::FEoperatorequals(), and libMesh::EpetraVector< T >::swap().
template<typename T> int* libMesh::EpetraVector< T >::nonlocalElementSize_ private
Definition at line 590 of file trilinos_epetra_vector.h.
Referenced by libMesh::EpetraVector< T >::EpetraVector(), libMesh::EpetraVector< T >::FEoperatorequals(), and libMesh::EpetraVector< T >::swap().
template<typename T> int* libMesh::EpetraVector< T >::nonlocalIDs_ private
Definition at line 589 of file trilinos_epetra_vector.h.
Referenced by libMesh::EpetraVector< T >::EpetraVector(), libMesh::EpetraVector< T >::FEoperatorequals(), and libMesh::EpetraVector< T >::swap().
template<typename T> int libMesh::EpetraVector< T >::numNonlocalIDs_ private
Definition at line 591 of file trilinos_epetra_vector.h.
Referenced by libMesh::EpetraVector< T >::EpetraVector(), libMesh::EpetraVector< T >::FEoperatorequals(), and libMesh::EpetraVector< T >::swap().
The documentation for this class was generated from the following files:
trilinos_epetra_vector.h
trilinos_epetra_vector.C