libMesh: libMesh::MatrixFillAction< ValIn, ValOut > Class Template Reference
SomeWebsiteLogo
libMesh::MatrixFillAction< ValIn, ValOut > Class Template Reference
Public Member Functions
MatrixFillAction (SparseMatrix< ValOut > &target_mat)
void insert (const FEMContext &c, unsigned int var_num, const DenseVector< DynamicSparseNumberArray< ValIn, dof_id_type > > &Ue)
Private Attributes
SparseMatrix< ValOut > & target_matrix
Detailed Description
template<typename ValIn, typename ValOut>
class libMesh::MatrixFillAction< ValIn, ValOut >
The MatrixFillAction output functor class can be used with GenericProjector to write solution transfer coefficients into a sparse matrix.
Author
Roy H. Stogner
Date
2017
Definition at line 677 of file system_projection.C.
Constructor & Destructor Documentation
MatrixFillAction()
template<typename ValIn, typename ValOut> libMesh::MatrixFillAction< ValIn, ValOut >::MatrixFillAction (SparseMatrix< ValOut > & target_mat) inline
Definition at line 683 of file system_projection.C.
                                                       :
     target_matrix(target_mat) {}
Member Function Documentation
insert()
template<typename ValIn, typename ValOut> void libMesh::MatrixFillAction< ValIn, ValOut >::insert (const FEMContext & c, unsigned int var_num, const DenseVector< DynamicSparseNumberArray< ValIn, dof_id_type > > & Ue) inline
Definition at line 686 of file system_projection.C.
References libMesh::DiffContext::get_dof_indices(), libMesh::SparseMatrix< T >::row_start(), libMesh::SparseMatrix< T >::row_stop(), libMesh::SparseMatrix< T >::set(), and libMesh::Threads::spin_mtx.
   {
     const numeric_index_type
       begin_dof = target_matrix.row_start(),
       end_dof = target_matrix.row_stop();
     const std::vector<dof_id_type> & dof_indices =
       c.get_dof_indices(var_num);
     unsigned int size = Ue.size();
     libmesh_assert_equal_to(size, dof_indices.size());
     // Lock the target matrix since it is shared among threads.
     {
       Threads::spin_mutex::scoped_lock lock(Threads::spin_mtx);
       for (unsigned int i = 0; i != size; ++i)
         {
           const dof_id_type dof_i = dof_indices[i];
           if ((dof_i >= begin_dof) && (dof_i < end_dof))
             {
               const DynamicSparseNumberArray<ValIn,dof_id_type> & dnsa = Ue(i);
               const std::size_t dnsa_size = dnsa.size();
               for (unsigned int j = 0; j != dnsa_size; ++j)
                 {
                   const dof_id_type dof_j = dnsa.raw_index(j);
                   const ValIn dof_val = dnsa.raw_at(j);
                   target_matrix.set(dof_i, dof_j, dof_val);
                 }
             }
         }
     }
   }
Member Data Documentation
target_matrix
template<typename ValIn, typename ValOut> SparseMatrix<ValOut>& libMesh::MatrixFillAction< ValIn, ValOut >::target_matrix private
Definition at line 680 of file system_projection.C.
The documentation for this class was generated from the following file:
system_projection.C