libMesh: libMesh::DenseVector< T > Class Template Reference
SomeWebsiteLogo
libMesh::DenseVector< T > Class Template Reference
#include <analytic_function.h>
Public Member Functions
DenseVector (const unsigned int n=0)
DenseVector (const unsigned int n, const T &val)
template<typename T2 >
DenseVector (const DenseVector< T2 > &other_vector)
template<typename T2 >
DenseVector (const std::vector< T2 > &other_vector)
~DenseVector ()
virtual unsigned int size () const libmesh_override
virtual bool empty () const libmesh_override
virtual void zero () libmesh_override
const T & operator() (const unsigned int i) const
T & operator() (const unsigned int i)
virtual T el (const unsigned int i) const libmesh_override
virtual T & el (const unsigned int i) libmesh_override
template<typename T2 >
DenseVector< T > & operator= (const DenseVector< T2 > &other_vector)
void swap (DenseVector< T > &other_vector)
void resize (const unsigned int n)
template<typename T2 >
void append (const DenseVector< T2 > &other_vector)
void scale (const T factor)
DenseVector< T > & operator*= (const T factor)
template<typename T2 , typename T3 >
boostcopy::enable_if_c< ScalarTraits< T2 >::value, void >::type add (const T2 factor, const DenseVector< T3 > &vec)
template<typename T2 >
CompareTypes< T, T2 >::supertype dot (const DenseVector< T2 > &vec) const
template<typename T2 >
CompareTypes< T, T2 >::supertype indefinite_dot (const DenseVector< T2 > &vec) const
template<typename T2 >
bool operator== (const DenseVector< T2 > &vec) const
template<typename T2 >
bool operator!= (const DenseVector< T2 > &vec) const
template<typename T2 >
DenseVector< T > & operator+= (const DenseVector< T2 > &vec)
template<typename T2 >
DenseVector< T > & operator-= (const DenseVector< T2 > &vec)
Real min () const
Real max () const
Real l1_norm () const
Real l2_norm () const
Real linfty_norm () const
void get_principal_subvector (unsigned int sub_n, DenseVector< T > &dest) const
std::vector< T > & get_values ()
const std::vector< T > & get_values () const
void print (std::ostream &os) const
void print_scientific (std::ostream &os, unsigned precision=8) const
Private Attributes
std::vector< T > _val
Detailed Description
template<typename T>
class libMesh::DenseVector< T >
Defines a dense vector for use in Finite Element-type computations. This class is to basically compliment the DenseMatix class. It has additional capabilities over the std::vector that make it useful for finite elements, particulary for systems of equations. All overridden virtual functions are documented in dense_vector_base.h.
Author
Benjamin S. Kirk
Date
2003
Definition at line 34 of file analytic_function.h.
Constructor & Destructor Documentation
template<typename T > libMesh::DenseVector< T >::DenseVector (const unsigned int n = 0) inline explicit
Constructor. Creates a dense vector of dimension n.
Definition at line 272 of file dense_vector.h.
                                                 :
   _val (n, T(0.))
 {
 }
template<typename T> libMesh::DenseVector< T >::DenseVector (const unsigned int n, const T & val) inline explicit
Constructor. Creates a dense vector of dimension n where all entries have value val.
Definition at line 280 of file dense_vector.h.
                                            :
   _val (n, val)
 {
 }
template<typename T > template<typename T2 > libMesh::DenseVector< T >::DenseVector (const DenseVector< T2 > & other_vector) inline
Copy-constructor.
Definition at line 291 of file dense_vector.h.
References libMesh::DenseVector< T >::_val.
                                                                  :
   DenseVectorBase<T>()
 {
   const std::vector<T2> & other_vals = other_vector.get_values();
   _val.clear();
   const int N = cast_int<int>(other_vals.size());
   _val.reserve(N);
   for (int i=0; i<N; i++)
     _val.push_back(other_vals[i]);
 }
template<typename T > template<typename T2 > libMesh::DenseVector< T >::DenseVector (const std::vector< T2 > & other_vector) inline
Copy-constructor, from a std::vector.
Definition at line 310 of file dense_vector.h.
                                                                :
   _val(other_vector)
 {
 }
template<typename T> libMesh::DenseVector< T >::~DenseVector () inline
Destructor. Does nothing.
Definition at line 85 of file dense_vector.h.
 {}
Member Function Documentation
template<typename T > template<typename T2 , typename T3 > boostcopy::enable_if_c< ScalarTraits< T2 >::value, void >::type libMesh::DenseVector< T >::add (const T2 factor, const DenseVector< T3 > & vec) inline
Adds factor times vec to this vector. This should only work if T += T2 * T3 is valid C++ and if T2 is scalar. Return type is void
Returns
A reference to *this.
Definition at line 431 of file dense_vector.h.
References libMesh::DenseVector< T >::_val, and libMesh::DenseVector< T >::size().
Referenced by libMesh::EulerSolver::_general_residual(), libMesh::NewmarkSolver::_general_residual(), libMesh::DenseVector< Number >::el(), and libMesh::DenseMatrix< T >::vector_mult_add().
 {
   libmesh_assert_equal_to (this->size(), vec.size());
   const int N = cast_int<int>(_val.size());
   for (int i=0; i<N; i++)
     (*this)(i) += static_cast<T>(factor)*vec(i);
 }
template<typename T > template<typename T2 > void libMesh::DenseVector< T >::append (const DenseVector< T2 > & other_vector) inline
Append additional entries to (resizing, but unchanging) the vector.
Definition at line 362 of file dense_vector.h.
References libMesh::DenseVector< T >::_val, and libMesh::DenseVector< T >::size().
Referenced by libMesh::FEGenericBase< OutputType >::coarsened_dof_values(), and libMesh::DenseVector< Number >::el().
 {
   const std::vector<T2> & other_vals = other_vector.get_values();
   _val.reserve(this->size() + other_vals.size());
   _val.insert(_val.end(), other_vals.begin(), other_vals.end());
 }
template<typename T > template<typename T2 > CompareTypes< T, T2 >::supertype libMesh::DenseVector< T >::dot (const DenseVector< T2 > & vec) const inline
Returns
The dot product of *this with vec.
In the complex-valued case, uses the complex conjugate of vec.
Definition at line 446 of file dense_vector.h.
References libMesh::DenseVector< T >::_val, libMesh::libmesh_conj(), and libMesh::DenseVector< T >::size().
Referenced by libMesh::DenseVector< Number >::el().
 {
   if (!_val.size())
     return 0.;
   libmesh_assert_equal_to (this->size(), vec.size());
 #ifdef LIBMESH_HAVE_EIGEN
   // We reverse the order of the arguments to dot() here since
   // the convention in Eigen is to take the complex conjugate of the
   // *first* argument, while ours is to take the complex conjugate of
   // the second.
   return Eigen::Map<const typename Eigen::Matrix<T2, Eigen::Dynamic, 1> >(&(vec.get_values()[0]), vec.size())
     .dot(Eigen::Map<const typename Eigen::Matrix<T, Eigen::Dynamic, 1> >(&_val[0], _val.size()));
 #else
   typename CompareTypes<T, T2>::supertype val = 0.;
   const int N = cast_int<int>(_val.size());
   // The following pragma tells clang's vectorizer that it is safe to
   // reorder floating point operations for this loop.
 #ifdef __clang__
 #pragma clang loop vectorize(enable)
 #endif
   for (int i=0; i<N; i++)
     val += (*this)(i)*libmesh_conj(vec(i));
   return val;
 #endif
 }
template<typename T> virtual T libMesh::DenseVector< T >::el (const unsigned int i) const inline virtual
Returns
The (i) element of the vector.
Implements libMesh::DenseVectorBase< T >.
Definition at line 107 of file dense_vector.h.
   { return (*this)(i); }
template<typename T> virtual T& libMesh::DenseVector< T >::el (const unsigned int i) inline virtual
Returns
The (i) element of the vector as a writable reference.
Implements libMesh::DenseVectorBase< T >.
Definition at line 110 of file dense_vector.h.
   { return (*this)(i); }
template<typename T> virtual bool libMesh::DenseVector< T >::empty () const inline virtual
Returns
true iff size() is 0.
Reimplemented from libMesh::DenseVectorBase< T >.
Definition at line 92 of file dense_vector.h.
Referenced by libMesh::NumericVector< T >::add_vector(), and libMesh::NumericVector< T >::insert().
   { return _val.empty(); }
template<typename T> void libMesh::DenseVector< T >::get_principal_subvector (unsigned int sub_n, DenseVector< T > & dest) const inline
Puts the principal subvector of size sub_n (i.e. first sub_n entries) into dest.
Definition at line 667 of file dense_vector.h.
References libMesh::DenseVector< T >::_val, and libMesh::DenseVector< T >::size().
Referenced by libMesh::DenseVector< Number >::el().
 {
   libmesh_assert_less_equal ( sub_n, this->size() );
   dest.resize(sub_n);
   const int N = cast_int<int>(sub_n);
   for (int i=0; i<N; i++)
     dest(i) = _val[i];
 }
template<typename T> std::vector<T>& libMesh::DenseVector< T >::get_values () inline
Returns
A reference to the underlying data storage vector.
This should be used with caution (i.e. one should not change the size of the vector, etc.) but is useful for interoperating with low level BLAS routines which expect a simple array.
Definition at line 251 of file dense_vector.h.
Referenced by libMesh::DenseMatrix< T >::_evd_lapack(), libMesh::DenseMatrix< T >::_lu_back_substitute_lapack(), libMesh::DenseMatrix< T >::_matvec_blas(), libMesh::DenseMatrix< T >::_svd_solve_lapack(), libMesh::GenericProjector< FFunctor, GFunctor, FValue, ProjectionAction >::operator()(), and libMesh::FEMContext::pre_fe_reinit().
 { return _val; }
template<typename T> const std::vector<T>& libMesh::DenseVector< T >::get_values () const inline
Returns
A constant reference to the underlying data storage vector.
Definition at line 256 of file dense_vector.h.
 { return _val; }
template<typename T > template<typename T2 > CompareTypes< T, T2 >::supertype libMesh::DenseVector< T >::indefinite_dot (const DenseVector< T2 > & vec) const inline
Returns
The dot product of *this with vec.
In the complex-valued case, does not use the complex conjugate of vec.
Definition at line 479 of file dense_vector.h.
References libMesh::DenseVector< T >::_val, and libMesh::DenseVector< T >::size().
Referenced by libMesh::DenseVector< Number >::el().
 {
   libmesh_assert_equal_to (this->size(), vec.size());
   typename CompareTypes<T, T2>::supertype val = 0.;
   const int N = cast_int<int>(_val.size());
   for (int i=0; i<N; i++)
     val += (*this)(i)*(vec(i));
   return val;
 }
template<typename T > Real libMesh::DenseVector< T >::l1_norm () const inline
Returns
The -norm of the vector, i.e. the sum of the absolute values of the entries.
Definition at line 596 of file dense_vector.h.
References libMesh::DenseVector< T >::_val, std::abs(), and libMesh::Real.
Referenced by libMesh::DenseVector< Number >::el().
 {
   if (!_val.size())
     return 0.;
 #ifdef LIBMESH_HAVE_EIGEN
   return Eigen::Map<const typename Eigen::Matrix<T, Eigen::Dynamic, 1> >(&_val[0], _val.size()).template lpNorm<1>();
 #else
   Real my_norm = 0.;
   const int N = cast_int<int>(_val.size());
   for (int i=0; i!=N; i++)
     my_norm += std::abs((*this)(i));
   return my_norm;
 #endif
 }
template<typename T > Real libMesh::DenseVector< T >::l2_norm () const inline
Returns
The -norm of the vector, i.e. the square root of the sum of the squares of the entries.
Definition at line 617 of file dense_vector.h.
References libMesh::DenseVector< T >::_val, libMesh::TensorTools::norm_sq(), and libMesh::Real.
Referenced by libMesh::DenseVector< Number >::el().
 {
   if (!_val.size())
     return 0.;
 #ifdef LIBMESH_HAVE_EIGEN
   return Eigen::Map<const typename Eigen::Matrix<T, Eigen::Dynamic, 1> >(&_val[0], _val.size()).norm();
 #else
   Real my_norm = 0.;
   const int N = cast_int<int>(_val.size());
   // The following pragma tells clang's vectorizer that it is safe to
   // reorder floating point operations for this loop.
 #ifdef __clang__
 #pragma clang loop vectorize(enable)
 #endif
   for (int i=0; i!=N; i++)
     my_norm += TensorTools::norm_sq((*this)(i));
   return sqrt(my_norm);
 #endif
 }
template<typename T > Real libMesh::DenseVector< T >::linfty_norm () const inline
Returns
The -norm of the vector, i.e. the maximum absolute value of the entries.
Definition at line 643 of file dense_vector.h.
References libMesh::DenseVector< T >::_val, libMesh::TensorTools::norm_sq(), and libMesh::Real.
Referenced by libMesh::DenseVector< Number >::el().
 {
   if (!_val.size())
     return 0.;
 #ifdef LIBMESH_HAVE_EIGEN
   return Eigen::Map<const typename Eigen::Matrix<T, Eigen::Dynamic, 1> >(&_val[0], _val.size()).template lpNorm<Eigen::Infinity>();
 #else
   Real my_norm = TensorTools::norm_sq((*this)(0));
   const int N = cast_int<int>(_val.size());
   for (int i=1; i!=N; i++)
     {
       Real current = TensorTools::norm_sq((*this)(i));
       my_norm = (my_norm > current? my_norm : current);
     }
   return sqrt(my_norm);
 #endif
 }
template<typename T > Real libMesh::DenseVector< T >::max () const inline
Returns
The maximum entry of the vector, or the maximum real part in the case of complex numbers.
Definition at line 578 of file dense_vector.h.
References libMesh::DenseVector< T >::_val, libMesh::libmesh_assert(), libMesh::libmesh_real(), libMesh::Real, and libMesh::DenseVector< T >::size().
Referenced by libMesh::DenseVector< Number >::el().
 {
   libmesh_assert (this->size());
   Real my_max = libmesh_real((*this)(0));
   const int N = cast_int<int>(_val.size());
   for (int i=1; i!=N; i++)
     {
       Real current = libmesh_real((*this)(i));
       my_max = (my_max > current? my_max : current);
     }
   return my_max;
 }
template<typename T > Real libMesh::DenseVector< T >::min () const inline
Returns
The minimum entry of the vector, or the minimum real part in the case of complex numbers.
Definition at line 560 of file dense_vector.h.
References libMesh::DenseVector< T >::_val, libMesh::libmesh_assert(), libMesh::libmesh_real(), libMesh::Real, and libMesh::DenseVector< T >::size().
Referenced by libMesh::DenseVector< Number >::el().
 {
   libmesh_assert (this->size());
   Real my_min = libmesh_real((*this)(0));
   const int N = cast_int<int>(_val.size());
   for (int i=1; i!=N; i++)
     {
       Real current = libmesh_real((*this)(i));
       my_min = (my_min < current? my_min : current);
     }
   return my_min;
 }
template<typename T > template<typename T2 > bool libMesh::DenseVector< T >::operator!= (const DenseVector< T2 > & vec) const inline
Returns
true if vec is not exactly equal to this vector, false otherwise.
Definition at line 512 of file dense_vector.h.
References libMesh::DenseVector< T >::_val, and libMesh::DenseVector< T >::size().
Referenced by libMesh::DenseVector< Number >::el().
 {
   libmesh_assert_equal_to (this->size(), vec.size());
   const int N = cast_int<int>(_val.size());
   for (int i=0; i<N; i++)
     if ((*this)(i) != vec(i))
       return true;
   return false;
 }
template<typename T > const T & libMesh::DenseVector< T >::operator() (const unsigned int i) const inline
Returns
Entry i of the vector as a const reference.
Definition at line 385 of file dense_vector.h.
References libMesh::DenseVector< T >::_val.
Referenced by libMesh::DenseVector< Number >::empty().
 {
   libmesh_assert_less (i, _val.size());
   return _val[i];
 }
template<typename T > T & libMesh::DenseVector< T >::operator() (const unsigned int i) inline
Returns
Entry i of the vector as a writable reference.
Definition at line 396 of file dense_vector.h.
References libMesh::DenseVector< T >::_val.
 {
   libmesh_assert_less (i, _val.size());
   return _val[i];
 }
template<typename T> DenseVector< T > & libMesh::DenseVector< T >::operator*= (const T factor) inline
Multiplies every element in the vector by factor.
Returns
A reference to *this.
Definition at line 418 of file dense_vector.h.
References libMesh::DenseVector< T >::scale().
Referenced by libMesh::DenseVector< Number >::el().
 {
   this->scale(factor);
   return *this;
 }
template<typename T > template<typename T2 > DenseVector< T > & libMesh::DenseVector< T >::operator+= (const DenseVector< T2 > & vec) inline
Adds vec to this vector.
Returns
A reference to *this.
Definition at line 529 of file dense_vector.h.
References libMesh::DenseVector< T >::_val, and libMesh::DenseVector< T >::size().
Referenced by libMesh::DenseVector< Number >::el().
 {
   libmesh_assert_equal_to (this->size(), vec.size());
   const int N = cast_int<int>(_val.size());
   for (int i=0; i<N; i++)
     (*this)(i) += vec(i);
   return *this;
 }
template<typename T > template<typename T2 > DenseVector< T > & libMesh::DenseVector< T >::operator-= (const DenseVector< T2 > & vec) inline
Subtracts vec from this vector.
Returns
A reference to *this.
Definition at line 545 of file dense_vector.h.
References libMesh::DenseVector< T >::_val, and libMesh::DenseVector< T >::size().
Referenced by libMesh::DenseVector< Number >::el().
 {
   libmesh_assert_equal_to (this->size(), vec.size());
   const int N = cast_int<int>(_val.size());
   for (int i=0; i<N; i++)
     (*this)(i) -= vec(i);
   return *this;
 }
template<typename T > template<typename T2 > DenseVector< T > & libMesh::DenseVector< T >::operator= (const DenseVector< T2 > & other_vector) inline
Assignment operator.
Returns
A reference to *this.
Definition at line 322 of file dense_vector.h.
References libMesh::DenseVector< T >::_val.
Referenced by libMesh::DenseVector< Number >::el().
 {
   const std::vector<T2> & other_vals = other_vector.get_values();
   _val.clear();
   const int N = cast_int<int>(other_vals.size());
   _val.reserve(N);
   for (int i=0; i<N; i++)
     _val.push_back(other_vals[i]);
   return *this;
 }
template<typename T > template<typename T2 > bool libMesh::DenseVector< T >::operator== (const DenseVector< T2 > & vec) const inline
Returns
true if vec is exactly equal to this vector, false otherwise.
Definition at line 495 of file dense_vector.h.
References libMesh::DenseVector< T >::_val, and libMesh::DenseVector< T >::size().
Referenced by libMesh::DenseVector< Number >::el().
 {
   libmesh_assert_equal_to (this->size(), vec.size());
   const int N = cast_int<int>(_val.size());
   for (int i=0; i<N; i++)
     if ((*this)(i) != vec(i))
       return false;
   return true;
 }
template<typename T > void libMesh::DenseVectorBase< T >::print (std::ostream & os) const inherited
Pretty-print the vector to stdout.
Definition at line 62 of file dense_vector_base.C.
Referenced by libMesh::DenseVectorBase< T >::empty().
 {
   for (unsigned int i=0; i<this->size(); i++)
     os << std::setw(8)
        << this->el(i)
        << std::endl;
 }
template<typename T > void libMesh::DenseVectorBase< T >::print_scientific (std::ostream & os, unsigned precision = 8) const inherited
Prints the entries of the vector with additional decimal places in scientific notation.
Definition at line 30 of file dense_vector_base.C.
 {
 #ifndef LIBMESH_BROKEN_IOSTREAM
   // save the initial format flags
   std::ios_base::fmtflags os_flags = os.flags();
   // Print the vector entries.
   for (unsigned int i=0; i<this->size(); i++)
     os << std::setw(10)
        << std::scientific
        << std::setprecision(precision)
        << this->el(i)
        << std::endl;
   // reset the original format flags
   os.flags(os_flags);
 #else
   // Print the matrix entries.
   for (unsigned int i=0; i<this->size(); i++)
     os << std::setprecision(precision)
        << this->el(i)
        << std::endl;
 #endif
 }
template<typename T > void libMesh::DenseVector< T >::resize (const unsigned int n) inline
Resize the vector. Sets all elements to 0.
Definition at line 350 of file dense_vector.h.
References libMesh::DenseVector< T >::_val, and libMesh::DenseVector< T >::zero().
Referenced by libMesh::DenseMatrix< T >::_cholesky_back_substitute(), libMesh::DenseMatrix< T >::_evd_lapack(), libMesh::DenseMatrix< T >::_lu_back_substitute(), libMesh::DenseMatrix< T >::_svd_lapack(), libMesh::DenseMatrix< T >::_svd_solve_lapack(), libMesh::HPCoarsenTest::add_projection(), libMesh::DofMap::build_constraint_matrix_and_vector(), libMesh::FEGenericBase< OutputType >::coarsened_dof_values(), libMesh::FEGenericBase< OutputType >::compute_periodic_constraints(), libMesh::FEGenericBase< OutputType >::compute_proj_constraints(), libMesh::DenseVector< Number >::el(), libMesh::DGFEMContext::neighbor_side_fe_reinit(), libMesh::GenericProjector< FFunctor, GFunctor, FValue, ProjectionAction >::operator()(), libMesh::CompositeFEMFunction< Output >::operator()(), libMesh::WeightedPatchRecoveryErrorEstimator::EstimateError::operator()(), libMesh::CompositeFunction< Output >::operator()(), libMesh::PatchRecoveryErrorEstimator::EstimateError::operator()(), libMesh::MeshFunction::operator()(), libMesh::BoundaryProjectSolution::operator()(), libMesh::FEMContext::pre_fe_reinit(), libMesh::HPCoarsenTest::select_refinement(), libMesh::DenseMatrix< T >::vector_mult(), libMesh::DenseMatrix< T >::vector_mult_add(), and libMesh::DenseMatrix< T >::vector_mult_transpose().
 {
   _val.resize(n);
   zero();
 }
template<typename T> void libMesh::DenseVector< T >::scale (const T factor) inline
Multiplies every element in the vector by factor.
Definition at line 407 of file dense_vector.h.
References libMesh::DenseVector< T >::_val.
Referenced by libMesh::DenseVector< Number >::el(), and libMesh::DenseVector< T >::operator*=().
 {
   const int N = cast_int<int>(_val.size());
   for (int i=0; i<N; i++)
     _val[i] *= factor;
 }
template<typename T> virtual unsigned int libMesh::DenseVector< T >::size () const inline virtual
Returns
The size of the vector.
Implements libMesh::DenseVectorBase< T >.
Definition at line 87 of file dense_vector.h.
Referenced by libMesh::EulerSolver::_general_residual(), libMesh::Euler2Solver::_general_residual(), libMesh::NewmarkSolver::_general_residual(), libMesh::DenseMatrix< T >::_lu_back_substitute(), libMesh::DenseMatrix< T >::_matvec_blas(), libMesh::DenseMatrix< T >::_svd_lapack(), libMesh::DenseMatrix< T >::_svd_solve_lapack(), libMesh::DenseVector< T >::add(), libMesh::HPCoarsenTest::add_projection(), libMesh::NumericVector< T >::add_vector(), libMesh::DenseVector< T >::append(), libMesh::FEMSystem::assembly(), libMesh::DofMap::constrain_element_dyad_matrix(), libMesh::DofMap::constrain_element_matrix_and_vector(), libMesh::DofMap::constrain_element_vector(), libMesh::MeshFunction::discontinuous_gradient(), libMesh::MeshFunction::discontinuous_value(), libMesh::DenseVector< T >::dot(), libMesh::JumpErrorEstimator::estimate_error(), libMesh::ExactErrorEstimator::find_squared_element_error(), libMesh::DenseVector< T >::get_principal_subvector(), libMesh::MeshFunction::gradient(), libMesh::MeshFunction::hessian(), libMesh::DofMap::heterogenously_constrain_element_matrix_and_vector(), libMesh::DofMap::heterogenously_constrain_element_vector(), libMesh::DenseVector< T >::indefinite_dot(), libMesh::VectorSetAction< Val >::insert(), libMesh::NumericVector< T >::insert(), libMesh::LaplacianErrorEstimator::internal_side_integration(), libMesh::DenseVector< T >::max(), libMesh::DenseVector< T >::min(), libMesh::DenseVector< T >::operator!=(), libMesh::ConstFEMFunction< Output >::operator()(), libMesh::WrappedFunction< Output >::operator()(), libMesh::ParsedFEMFunction< Output >::operator()(), libMesh::CompositeFEMFunction< Output >::operator()(), libMesh::CompositeFunction< Output >::operator()(), libMesh::MeshFunction::operator()(), libMesh::DenseVector< T >::operator+=(), libMesh::DenseVector< T >::operator-=(), libMesh::DenseVector< T >::operator==(), libMesh::HPCoarsenTest::select_refinement(), libMesh::DenseMatrix< T >::vector_mult(), libMesh::DenseMatrix< T >::vector_mult_add(), and libMesh::DenseMatrix< T >::vector_mult_transpose().
   {
     return cast_int<unsigned int>(_val.size());
   }
template<typename T> void libMesh::DenseVector< T >::swap (DenseVector< T > & other_vector) inline
STL-like swap method
Definition at line 341 of file dense_vector.h.
References libMesh::DenseVector< T >::_val.
Referenced by libMesh::EulerSolver::_general_residual(), libMesh::Euler2Solver::_general_residual(), and libMesh::DenseVector< Number >::el().
 {
   _val.swap(other_vector._val);
 }
template<typename T > void libMesh::DenseVector< T >::zero () inline virtual
Set every element in the vector to 0. Needs to be pure virtual since the storage method may be different in derived classes.
Implements libMesh::DenseVectorBase< T >.
Definition at line 374 of file dense_vector.h.
References libMesh::DenseVector< T >::_val.
Referenced by libMesh::HPCoarsenTest::add_projection(), libMesh::FEGenericBase< OutputType >::coarsened_dof_values(), libMesh::DenseVector< Number >::empty(), libMesh::FEMSystem::numerical_jacobian(), libMesh::GenericProjector< FFunctor, GFunctor, FValue, ProjectionAction >::operator()(), libMesh::BoundaryProjectSolution::operator()(), libMesh::DenseVector< T >::resize(), and libMesh::HPCoarsenTest::select_refinement().
 {
   std::fill (_val.begin(),
              _val.end(),
              T(0.));
 }
Member Data Documentation
template<typename T> std::vector<T> libMesh::DenseVector< T >::_val private
The actual data values, stored as a 1D array.
Definition at line 263 of file dense_vector.h.
Referenced by libMesh::DenseVector< T >::add(), libMesh::DenseVector< T >::append(), libMesh::DenseVector< T >::DenseVector(), libMesh::DenseVector< T >::dot(), libMesh::DenseVector< Number >::empty(), libMesh::DenseVector< T >::get_principal_subvector(), libMesh::DenseVector< Number >::get_values(), libMesh::DenseVector< T >::indefinite_dot(), libMesh::DenseVector< T >::l1_norm(), libMesh::DenseVector< T >::l2_norm(), libMesh::DenseVector< T >::linfty_norm(), libMesh::DenseVector< T >::max(), libMesh::DenseVector< T >::min(), libMesh::DenseVector< T >::operator!=(), libMesh::DenseVector< T >::operator()(), libMesh::DenseVector< T >::operator+=(), libMesh::DenseVector< T >::operator-=(), libMesh::DenseVector< T >::operator=(), libMesh::DenseVector< T >::operator==(), libMesh::DenseVector< T >::resize(), libMesh::DenseVector< T >::scale(), libMesh::DenseVector< Number >::size(), libMesh::DenseVector< T >::swap(), and libMesh::DenseVector< T >::zero().
The documentation for this class was generated from the following files:
analytic_function.h
dense_vector.h