libMesh: libMesh::ConstCouplingRowConstIterator Class Reference
SomeWebsiteLogo
libMesh::ConstCouplingRowConstIterator Class Reference
#include <coupling_matrix.h>
Public Member Functions
ConstCouplingRowConstIterator (const ConstCouplingRow &row_in, std::size_t loc_in, CouplingMatrix::rc_type::const_iterator it_in)
unsigned int operator* ()
ConstCouplingRowConstIterator & operator++ ()
bool operator== (const ConstCouplingRowConstIterator &other) const
bool operator!= (const ConstCouplingRowConstIterator &other) const
Private Attributes
std::size_t _location
const ConstCouplingRow & _row
CouplingMatrix::rc_type::const_iterator _it
Detailed Description
Definition at line 443 of file coupling_matrix.h.
Constructor & Destructor Documentation
libMesh::ConstCouplingRowConstIterator::ConstCouplingRowConstIterator (const ConstCouplingRow & row_in, std::size_t loc_in, CouplingMatrix::rc_type::const_iterator it_in) inline
Definition at line 446 of file coupling_matrix.h.
References _it, _location, libMesh::ConstCouplingRow::_mat, libMesh::CouplingMatrix::_ranges, _row, and std::max().
                                                                             :
     _location(loc_in),
     _row(row_in),
     _it(it_in)
   {
 #ifndef NDEBUG
     if (_it != _row._mat._ranges.end())
       {
         libmesh_assert_less_equal(_it->first, _location);
         libmesh_assert_less_equal(_location, _it->second);
       }
     else
       {
         libmesh_assert_equal_to
           (_location, std::numeric_limits<size_t>::max());
       }
 #endif
   }
Member Function Documentation
bool libMesh::ConstCouplingRowConstIterator::operator!= (const ConstCouplingRowConstIterator & other) const inline
Definition at line 513 of file coupling_matrix.h.
   {
     return !(*this == other);
   }
unsigned int libMesh::ConstCouplingRowConstIterator::operator* () inline
Definition at line 467 of file coupling_matrix.h.
References _location, libMesh::ConstCouplingRow::_mat, _row, std::max(), and libMesh::CouplingMatrix::size().
   {
     libmesh_assert_not_equal_to
       (_location, std::numeric_limits<std::size_t>::max());
     return _location % _row._mat.size();
   }
ConstCouplingRowConstIterator& libMesh::ConstCouplingRowConstIterator::operator++ () inline
Definition at line 474 of file coupling_matrix.h.
References _it, _location, libMesh::ConstCouplingRow::_mat, libMesh::CouplingMatrix::_ranges, _row, libMesh::ConstCouplingRow::_row_i, std::max(), and libMesh::CouplingMatrix::size().
   {
     libmesh_assert_not_equal_to
       (_location, std::numeric_limits<std::size_t>::max());
     if (_location == _it->second)
       {
         ++_it;
         // Are we past the end of the matrix?
         if (_it == _row._mat._ranges.end())
           _location = std::numeric_limits<std::size_t>::max();
         else
           {
             _location = _it->first;
             // Are we past the end of the row?
             if (_location >= _row._mat.size()*(_row._row_i+1))
               {
                 _location = std::numeric_limits<std::size_t>::max();
                 _it = _row._mat._ranges.end();
               }
           }
       }
     else
       ++_location;
     return *this;
   }
bool libMesh::ConstCouplingRowConstIterator::operator== (const ConstCouplingRowConstIterator & other) const inline
Definition at line 503 of file coupling_matrix.h.
References _it, _location, _row, and libMesh::libmesh_assert().
   {
     // Thinking that iterators from different row objects are equal
     // is not even wrong
     libmesh_assert(_row == other._row);
     return ((_location == other._location) &&
             (_it == other._it));
   }
Member Data Documentation
CouplingMatrix::rc_type::const_iterator libMesh::ConstCouplingRowConstIterator::_it private
Definition at line 525 of file coupling_matrix.h.
Referenced by ConstCouplingRowConstIterator(), operator++(), and operator==().
std::size_t libMesh::ConstCouplingRowConstIterator::_location private
Definition at line 521 of file coupling_matrix.h.
Referenced by ConstCouplingRowConstIterator(), operator*(), operator++(), and operator==().
const ConstCouplingRow& libMesh::ConstCouplingRowConstIterator::_row private
Definition at line 522 of file coupling_matrix.h.
Referenced by ConstCouplingRowConstIterator(), operator*(), operator++(), and operator==().
The documentation for this class was generated from the following file:
coupling_matrix.h