libMesh: libMesh::InverseDistanceInterpolation< KDDim > Class Template Reference
SomeWebsiteLogo
libMesh::InverseDistanceInterpolation< KDDim > Class Template Reference
#include <meshfree_interpolation.h>
Public Types
enum ParallelizationStrategy { SYNC_SOURCES = 0, INVALID_STRATEGY }
Public Member Functions
InverseDistanceInterpolation (const libMesh::Parallel::Communicator &comm_in, const unsigned int n_interp_pts=8, const Real power=2)
virtual void clear () libmesh_override
virtual void interpolate_field_data (const std::vector< std::string > &field_names, const std::vector< Point > &tgt_pts, std::vector< Number > &tgt_vals) const libmesh_override
void print_info (std::ostream &os=libMesh::out) const
unsigned int n_field_variables () const
void set_field_variables (const std::vector< std::string > &names)
const std::vector< std::string > & field_variables () const
std::vector< Point > & get_source_points ()
std::vector< Number > & get_source_vals ()
virtual void add_field_data (const std::vector< std::string > &field_names, const std::vector< Point > &pts, const std::vector< Number > &vals)
virtual void prepare_for_use ()
const Parallel::Communicator & comm () const
processor_id_type n_processors () const
processor_id_type processor_id () const
Protected Member Functions
virtual void construct_kd_tree ()
virtual void interpolate (const Point &pt, const std::vector< size_t > &src_indices, const std::vector< Real > &src_dist_sqr, std::vector< Number >::iterator &out_it) const
virtual void gather_remote_data ()
Protected Attributes
const Real _half_power
const unsigned int _n_interp_pts
std::vector< Number > _vals
ParallelizationStrategy _parallelization_strategy
std::vector< std::string > _names
std::vector< Point > _src_pts
std::vector< Number > _src_vals
const Parallel::Communicator & _communicator
Detailed Description
template<unsigned int KDDim>
class libMesh::InverseDistanceInterpolation< KDDim >
Inverse distance interplation.
Definition at line 174 of file meshfree_interpolation.h.
Member Enumeration Documentation
enum libMesh::MeshfreeInterpolation::ParallelizationStrategy inherited
"ParallelizationStrategy" to employ.
SYNC_SOURCES assumes that the data added on each processor are independent and relatively small. Calling the prepare_for_use() method with this ParallelizationStrategy will copy remote data from other processors, so all interpolation can be performed locally.
Other ParallelizationStrategy techniques will be implemented as needed.
Enumerator
SYNC_SOURCES
INVALID_STRATEGY
Definition at line 67 of file meshfree_interpolation.h.
                                {SYNC_SOURCES     = 0,
                                 INVALID_STRATEGY};
Constructor & Destructor Documentation
template<unsigned int KDDim> libMesh::InverseDistanceInterpolation< KDDim >::InverseDistanceInterpolation (const libMesh::Parallel::Communicator & comm_in, const unsigned int n_interp_pts = 8, const Real power = 2) inline
Constructor. Takes the inverse distance power, which defaults to 2.
Definition at line 322 of file meshfree_interpolation.h.
                                                                      :
     MeshfreeInterpolation(comm_in),
 #if LIBMESH_HAVE_NANOFLANN
     _point_list_adaptor(_src_pts),
 #endif
     _half_power(power/2.0),
     _n_interp_pts(n_interp_pts)
   {}
Member Function Documentation
virtual void libMesh::MeshfreeInterpolation::add_field_data (const std::vector< std::string > & field_names, const std::vector< Point > & pts, const std::vector< Number > & vals) virtual inherited
Sets source data at specified points.
template<unsigned int KDDim> virtual void libMesh::InverseDistanceInterpolation< KDDim >::clear () virtual
Clears all internal data structures and restores to a pristine state.
Reimplemented from libMesh::MeshfreeInterpolation.
Reimplemented in libMesh::RadialBasisInterpolation< KDDim, RBF >.
const Parallel::Communicator& libMesh::ParallelObject::comm () const inline inherited
Returns
a reference to the Parallel::Communicator object used by this mesh.
Definition at line 87 of file parallel_object.h.
References libMesh::ParallelObject::_communicator.
Referenced by libMesh::ExactSolution::_compute_error(), libMesh::MetisPartitioner::_do_partition(), libMesh::ParmetisPartitioner::_do_repartition(), libMesh::BoundaryInfo::_find_id_maps(), libMesh::EquationSystems::_read_impl(), libMesh::ImplicitSystem::add_matrix(), libMesh::System::add_vector(), libMesh::UnstructuredMesh::all_second_order(), libMesh::MeshTools::Modification::all_tri(), libMesh::LaplaceMeshSmoother::allgather_graph(), libMesh::FEMSystem::assemble_qoi(), libMesh::DofMap::attach_matrix(), libMesh::MeshTools::bounding_box(), libMesh::EquationSystems::build_parallel_solution_vector(), libMesh::MeshBase::cache_elem_dims(), libMesh::System::calculate_norm(), libMesh::MeshTools::correct_node_proc_ids(), libMesh::MeshCommunication::delete_remote_elements(), libMesh::DofMap::distribute_dofs(), DMlibMeshFunction(), DMlibMeshJacobian(), DMlibMeshSetSystem_libMesh(), DMVariableBounds_libMesh(), libMesh::WeightedPatchRecoveryErrorEstimator::estimate_error(), libMesh::PatchRecoveryErrorEstimator::estimate_error(), libMesh::JumpErrorEstimator::estimate_error(), libMesh::ExactErrorEstimator::estimate_error(), libMesh::DofMap::get_info(), libMesh::ImplicitSystem::get_linear_solver(), libMesh::EquationSystems::get_solution(), libMesh::LocationMap< T >::init(), libMesh::TopologyMap::init(), libMesh::TimeSolver::init(), libMesh::SystemSubsetBySubdomain::init(), libMesh::OptimizationSystem::initialize_equality_constraints_storage(), libMesh::OptimizationSystem::initialize_inequality_constraints_storage(), libMesh::DistributedMesh::libmesh_assert_valid_parallel_flags(), libMesh::DistributedMesh::libmesh_assert_valid_parallel_object_ids(), libMesh::DistributedMesh::libmesh_assert_valid_parallel_p_levels(), libMesh::MeshCommunication::make_elems_parallel_consistent(), libMesh::MeshCommunication::make_new_node_proc_ids_parallel_consistent(), libMesh::MeshCommunication::make_new_nodes_parallel_consistent(), libMesh::MeshCommunication::make_node_ids_parallel_consistent(), libMesh::MeshCommunication::make_node_proc_ids_parallel_consistent(), libMesh::MeshCommunication::make_node_unique_ids_parallel_consistent(), libMesh::MeshCommunication::make_nodes_parallel_consistent(), libMesh::FEMSystem::mesh_position_set(), libMesh::MeshSerializer::MeshSerializer(), libMesh::DistributedMesh::n_active_elem(), libMesh::MeshTools::n_active_levels(), libMesh::BoundaryInfo::n_boundary_conds(), libMesh::BoundaryInfo::n_edge_conds(), libMesh::MeshTools::n_levels(), libMesh::BoundaryInfo::n_nodeset_conds(), libMesh::MeshTools::n_p_levels(), libMesh::BoundaryInfo::n_shellface_conds(), libMesh::DistributedMesh::parallel_max_elem_id(), libMesh::DistributedMesh::parallel_max_node_id(), libMesh::DistributedMesh::parallel_n_elem(), libMesh::DistributedMesh::parallel_n_nodes(), libMesh::SparsityPattern::Build::parallel_sync(), libMesh::Partitioner::partition(), libMesh::Partitioner::partition_unpartitioned_elements(), libMesh::System::point_gradient(), libMesh::System::point_value(), libMesh::MeshBase::prepare_for_use(), libMesh::MeshTools::processor_bounding_box(), libMesh::System::project_vector(), libMesh::XdrIO::read(), libMesh::System::read_header(), libMesh::System::read_legacy_data(), libMesh::System::read_SCALAR_dofs(), libMesh::XdrIO::read_serialized_bc_names(), libMesh::XdrIO::read_serialized_bcs_helper(), libMesh::System::read_serialized_blocked_dof_objects(), libMesh::XdrIO::read_serialized_connectivity(), libMesh::System::read_serialized_data(), libMesh::XdrIO::read_serialized_nodes(), libMesh::XdrIO::read_serialized_nodesets(), libMesh::XdrIO::read_serialized_subdomain_names(), libMesh::System::read_serialized_vector(), libMesh::MeshBase::recalculate_n_partitions(), libMesh::DistributedMesh::renumber_dof_objects(), libMesh::Partitioner::set_node_processor_ids(), libMesh::DofMap::set_nonlocal_dof_objects(), libMesh::Partitioner::set_parent_processor_ids(), libMesh::LaplaceMeshSmoother::smooth(), libMesh::MeshTools::subdomain_bounding_box(), libMesh::MeshBase::subdomain_ids(), libMesh::BoundaryInfo::sync(), libMesh::Parallel::sync_node_data_by_element_id(), libMesh::MeshTools::total_weight(), libMesh::NameBasedIO::write(), libMesh::XdrIO::write(), libMesh::System::write_SCALAR_dofs(), libMesh::XdrIO::write_serialized_bcs_helper(), libMesh::System::write_serialized_blocked_dof_objects(), libMesh::XdrIO::write_serialized_connectivity(), libMesh::XdrIO::write_serialized_nodes(), and libMesh::XdrIO::write_serialized_nodesets().
   { return _communicator; }
template<unsigned int KDDim> virtual void libMesh::InverseDistanceInterpolation< KDDim >::construct_kd_tree () protected virtual
Build & initialize the KD tree, if needed.
const std::vector<std::string>& libMesh::MeshfreeInterpolation::field_variables () const inline inherited
Returns
the field variables as a read-only reference.
Definition at line 112 of file meshfree_interpolation.h.
References libMesh::MeshfreeInterpolation::_names.
   { return _names; }
virtual void libMesh::MeshfreeInterpolation::gather_remote_data () protected virtual inherited
Gathers source points and values that have been added on other processors. Note the user is responsible for adding points only once per processor if this method is called. No attempt is made to identify duplicate points.
This method is virtual so that it can be overwritten or extended as required in derived classes.
std::vector<Point>& libMesh::MeshfreeInterpolation::get_source_points () inline inherited
Returns
a writeable reference to the point list.
Definition at line 118 of file meshfree_interpolation.h.
References libMesh::MeshfreeInterpolation::_src_pts.
   { return _src_pts; }
std::vector<Number>& libMesh::MeshfreeInterpolation::get_source_vals () inline inherited
Returns
a writeable reference to the point list.
Definition at line 124 of file meshfree_interpolation.h.
References libMesh::MeshfreeInterpolation::_src_vals.
   { return _src_vals; }
template<unsigned int KDDim> virtual void libMesh::InverseDistanceInterpolation< KDDim >::interpolate (const Point & pt, const std::vector< size_t > & src_indices, const std::vector< Real > & src_dist_sqr, std::vector< Number >::iterator & out_it) const protected virtual
Performs inverse distance interpolation at the input point from the specified points.
template<unsigned int KDDim> virtual void libMesh::InverseDistanceInterpolation< KDDim >::interpolate_field_data (const std::vector< std::string > & field_names, const std::vector< Point > & tgt_pts, std::vector< Number > & tgt_vals) const virtual
Interpolate source data at target points. Pure virtual, must be overriden in derived classes.
Implements libMesh::MeshfreeInterpolation.
Reimplemented in libMesh::RadialBasisInterpolation< KDDim, RBF >.
unsigned int libMesh::MeshfreeInterpolation::n_field_variables () const inline inherited
The number of field variables.
Definition at line 99 of file meshfree_interpolation.h.
References libMesh::MeshfreeInterpolation::_names.
   { return cast_int<unsigned int>(_names.size()); }
processor_id_type libMesh::ParallelObject::n_processors () const inline inherited
Returns
the number of processors in the group.
Definition at line 93 of file parallel_object.h.
References libMesh::ParallelObject::_communicator, and libMesh::Parallel::Communicator::size().
Referenced by libMesh::ParmetisPartitioner::_do_repartition(), libMesh::BoundaryInfo::_find_id_maps(), libMesh::DistributedMesh::add_elem(), libMesh::DistributedMesh::add_node(), libMesh::LaplaceMeshSmoother::allgather_graph(), libMesh::FEMSystem::assembly(), libMesh::DistributedMesh::clear(), libMesh::MeshTools::correct_node_proc_ids(), libMesh::UnstructuredMesh::create_pid_mesh(), libMesh::DofMap::distribute_dofs(), libMesh::DofMap::distribute_local_dofs_node_major(), libMesh::DofMap::distribute_local_dofs_var_major(), libMesh::EnsightIO::EnsightIO(), libMesh::MeshBase::get_info(), libMesh::EquationSystems::get_solution(), libMesh::EquationSystems::init(), libMesh::SystemSubsetBySubdomain::init(), libMesh::DistributedMesh::insert_elem(), libMesh::DofMap::local_variable_indices(), libMesh::MeshBase::n_active_elem_on_proc(), libMesh::MeshBase::n_elem_on_proc(), libMesh::MeshBase::n_nodes_on_proc(), libMesh::SparsityPattern::Build::parallel_sync(), libMesh::Partitioner::partition(), libMesh::MeshBase::partition(), libMesh::Partitioner::partition_unpartitioned_elements(), libMesh::System::point_gradient(), libMesh::System::point_value(), libMesh::MeshTools::processor_bounding_box(), libMesh::System::project_vector(), libMesh::NameBasedIO::read(), libMesh::XdrIO::read(), libMesh::System::read_parallel_data(), libMesh::System::read_SCALAR_dofs(), libMesh::System::read_serialized_blocked_dof_objects(), libMesh::System::read_serialized_vector(), libMesh::DistributedMesh::renumber_dof_objects(), libMesh::Partitioner::repartition(), libMesh::Partitioner::set_node_processor_ids(), libMesh::DofMap::set_nonlocal_dof_objects(), libMesh::DistributedMesh::update_parallel_id_counts(), libMesh::GMVIO::write_binary(), libMesh::GMVIO::write_discontinuous_gmv(), libMesh::System::write_parallel_data(), libMesh::System::write_SCALAR_dofs(), libMesh::XdrIO::write_serialized_bcs_helper(), libMesh::System::write_serialized_blocked_dof_objects(), libMesh::XdrIO::write_serialized_connectivity(), libMesh::XdrIO::write_serialized_nodes(), and libMesh::XdrIO::write_serialized_nodesets().
   { return cast_int<processor_id_type>(_communicator.size()); }
virtual void libMesh::MeshfreeInterpolation::prepare_for_use () virtual inherited
Prepares data structures for use.
This method is virtual so that it can be overwritten or extended as required in derived classes.
Reimplemented in libMesh::RadialBasisInterpolation< KDDim, RBF >.
void libMesh::MeshfreeInterpolation::print_info (std::ostream & os = libMesh::out) const inherited
Prints information about this object, by default to libMesh::out.
processor_id_type libMesh::ParallelObject::processor_id () const inline inherited
Returns
the rank of this processor in the group.
Definition at line 99 of file parallel_object.h.
References libMesh::ParallelObject::_communicator, and libMesh::Parallel::Communicator::rank().
Referenced by libMesh::MetisPartitioner::_do_partition(), libMesh::BoundaryInfo::_find_id_maps(), libMesh::EquationSystems::_read_impl(), libMesh::DistributedMesh::add_elem(), libMesh::BoundaryInfo::add_elements(), libMesh::DofMap::add_neighbors_to_send_list(), libMesh::DistributedMesh::add_node(), libMesh::UnstructuredMesh::all_second_order(), libMesh::MeshTools::Modification::all_tri(), libMesh::FEMSystem::assembly(), libMesh::EquationSystems::build_discontinuous_solution_vector(), libMesh::DofMap::build_sparsity(), libMesh::DistributedMesh::clear(), libMesh::MeshTools::correct_node_proc_ids(), libMesh::DistributedMesh::delete_elem(), libMesh::DistributedMesh::delete_node(), libMesh::MeshCommunication::delete_remote_elements(), libMesh::DofMap::distribute_dofs(), libMesh::DofMap::distribute_local_dofs_node_major(), libMesh::DofMap::distribute_local_dofs_var_major(), libMesh::DistributedMesh::DistributedMesh(), libMesh::DofMap::end_dof(), libMesh::EnsightIO::EnsightIO(), libMesh::MeshFunction::find_element(), libMesh::MeshFunction::find_elements(), libMesh::UnstructuredMesh::find_neighbors(), libMesh::DofMap::first_dof(), libMesh::MeshBase::get_info(), libMesh::DofMap::get_info(), libMesh::EquationSystems::get_solution(), libMesh::SparsityPattern::Build::handle_vi_vj(), libMesh::SystemSubsetBySubdomain::init(), libMesh::DistributedMesh::insert_elem(), libMesh::DofMap::is_evaluable(), libMesh::SparsityPattern::Build::join(), libMesh::DofMap::last_dof(), libMesh::DistributedMesh::libmesh_assert_valid_parallel_object_ids(), libMesh::DofMap::local_variable_indices(), libMesh::MeshBase::n_active_local_elem(), libMesh::BoundaryInfo::n_boundary_conds(), libMesh::BoundaryInfo::n_edge_conds(), libMesh::DofMap::n_local_dofs(), libMesh::System::n_local_dofs(), libMesh::MeshBase::n_local_elem(), libMesh::MeshBase::n_local_nodes(), libMesh::BoundaryInfo::n_nodeset_conds(), libMesh::BoundaryInfo::n_shellface_conds(), libMesh::WeightedPatchRecoveryErrorEstimator::EstimateError::operator()(), libMesh::SparsityPattern::Build::operator()(), libMesh::PatchRecoveryErrorEstimator::EstimateError::operator()(), libMesh::SparsityPattern::Build::parallel_sync(), libMesh::System::point_gradient(), libMesh::System::point_value(), libMesh::System::project_vector(), libMesh::NameBasedIO::read(), libMesh::XdrIO::read(), libMesh::System::read_header(), libMesh::System::read_legacy_data(), libMesh::System::read_parallel_data(), libMesh::System::read_SCALAR_dofs(), libMesh::XdrIO::read_serialized_bc_names(), libMesh::XdrIO::read_serialized_bcs_helper(), libMesh::System::read_serialized_blocked_dof_objects(), libMesh::XdrIO::read_serialized_connectivity(), libMesh::System::read_serialized_data(), libMesh::XdrIO::read_serialized_nodes(), libMesh::XdrIO::read_serialized_nodesets(), libMesh::XdrIO::read_serialized_subdomain_names(), libMesh::System::read_serialized_vector(), libMesh::System::read_serialized_vectors(), libMesh::MeshData::read_xdr(), libMesh::DistributedMesh::renumber_dof_objects(), libMesh::Partitioner::set_node_processor_ids(), libMesh::DofMap::set_nonlocal_dof_objects(), libMesh::LaplaceMeshSmoother::smooth(), libMesh::MeshTools::total_weight(), libMesh::Parallel::Packing< Node * >::unpack(), libMesh::Parallel::Packing< Elem * >::unpack(), libMesh::DistributedMesh::update_parallel_id_counts(), libMesh::MeshTools::weight(), libMesh::NameBasedIO::write(), libMesh::XdrIO::write(), libMesh::EquationSystems::write(), libMesh::GMVIO::write_discontinuous_gmv(), libMesh::System::write_header(), libMesh::UCDIO::write_nodal_data(), libMesh::System::write_parallel_data(), libMesh::System::write_SCALAR_dofs(), libMesh::XdrIO::write_serialized_bc_names(), libMesh::XdrIO::write_serialized_bcs_helper(), libMesh::System::write_serialized_blocked_dof_objects(), libMesh::XdrIO::write_serialized_connectivity(), libMesh::System::write_serialized_data(), libMesh::XdrIO::write_serialized_nodes(), libMesh::XdrIO::write_serialized_nodesets(), libMesh::XdrIO::write_serialized_subdomain_names(), libMesh::System::write_serialized_vector(), and libMesh::System::write_serialized_vectors().
   { return cast_int<processor_id_type>(_communicator.rank()); }
void libMesh::MeshfreeInterpolation::set_field_variables (const std::vector< std::string > & names) inline inherited
Defines the field variable(s) we are responsible for, and importantly their assumed ordering.
Definition at line 106 of file meshfree_interpolation.h.
References libMesh::MeshfreeInterpolation::_names.
   { _names = names; }
Member Data Documentation
const Parallel::Communicator& libMesh::ParallelObject::_communicator protected inherited
Definition at line 105 of file parallel_object.h.
Referenced by libMesh::EquationSystems::build_parallel_solution_vector(), libMesh::ParallelObject::comm(), libMesh::EquationSystems::get_solution(), libMesh::ParallelObject::n_processors(), libMesh::ParallelObject::operator=(), and libMesh::ParallelObject::processor_id().
template<unsigned int KDDim> const Real libMesh::InverseDistanceInterpolation< KDDim >::_half_power protected
Definition at line 308 of file meshfree_interpolation.h.
template<unsigned int KDDim> const unsigned int libMesh::InverseDistanceInterpolation< KDDim >::_n_interp_pts protected
Definition at line 309 of file meshfree_interpolation.h.
std::vector<std::string> libMesh::MeshfreeInterpolation::_names protected inherited
Definition at line 163 of file meshfree_interpolation.h.
Referenced by libMesh::MeshfreeInterpolation::field_variables(), libMesh::MeshfreeInterpolation::n_field_variables(), and libMesh::MeshfreeInterpolation::set_field_variables().
ParallelizationStrategy libMesh::MeshfreeInterpolation::_parallelization_strategy protected inherited
Definition at line 162 of file meshfree_interpolation.h.
std::vector<Point> libMesh::MeshfreeInterpolation::_src_pts protected inherited
Definition at line 164 of file meshfree_interpolation.h.
Referenced by libMesh::MeshfreeInterpolation::get_source_points().
std::vector<Number> libMesh::MeshfreeInterpolation::_src_vals protected inherited
Definition at line 165 of file meshfree_interpolation.h.
Referenced by libMesh::MeshfreeInterpolation::get_source_vals().
template<unsigned int KDDim> std::vector<Number> libMesh::InverseDistanceInterpolation< KDDim >::_vals mutable protected
Temporary work array. Object level scope to avoid cache thrashing.
Definition at line 314 of file meshfree_interpolation.h.
The documentation for this class was generated from the following file:
meshfree_interpolation.h