libMesh: libMesh::WrappedFunction< Output > Class Template Reference
SomeWebsiteLogo
libMesh::WrappedFunction< Output > Class Template Reference
Wrap a libMesh-style function pointer into a FunctionBase object.
#include <wrapped_function.h>
Public Member Functions
WrappedFunction (const System &sys, Output fptr(const Point &p, const Parameters &parameters, const std::string &sys_name, const std::string &unknown_name)=nullptr, const Parameters *parameters=nullptr, unsigned int varnum=0)
WrappedFunction (WrappedFunction &&)=default
WrappedFunction (const WrappedFunction &)=default
virtual ~WrappedFunction ()=default
WrappedFunction & operator= (const WrappedFunction &)=delete
WrappedFunction & operator= (WrappedFunction &&)=delete
virtual std::unique_ptr< FunctionBase< Output > > clone () const override
virtual Output operator() (const Point &p, const Real time=0.) override
virtual void operator() (const Point &p, const Real time, DenseVector< Output > &output) override
virtual Output component (unsigned int i, const Point &p, Real time=0.) override
virtual void init ()
virtual void clear ()
void operator() (const Point &p, DenseVector< Output > &output)
bool initialized () const
void set_is_time_dependent (bool is_time_dependent)
bool is_time_dependent () const
Protected Attributes
const System & _sys
Output(* _fptr)(const Point &p, const Parameters &parameters, const std::string &sys_name, const std::string &unknown_name)
const Parameters * _parameters
unsigned int _varnum
const FunctionBase * _master
bool _initialized
bool _is_time_dependent
Detailed Description
template<typename Output = Number>
class libMesh::WrappedFunction< Output >
Wrap a libMesh-style function pointer into a FunctionBase object.
This class provides a wrapper with which to evaluate a (libMesh-style) function pointer in a FunctionBase-compatible interface. All overridden virtual functions are documented in function_base.h.
Author
Roy Stogner
Date
2012
Note
To wrap an ordinary function pointer use the AnalyticFunction class.
Definition at line 50 of file wrapped_function.h.
Constructor & Destructor Documentation
WrappedFunction() [1/3]
template<typename Output = Number> libMesh::WrappedFunction< Output >::WrappedFunction (const System & sys, Output fptrconst Point &p, const Parameters &parameters, const std::string &sys_name, const std::string &unknown_name = nullptr, const Parameters * parameters = nullptr, unsigned int varnum = 0) inline
Constructor to wrap scalar-valued function pointers.
Definition at line 57 of file wrapped_function.h.
References libMesh::FunctionBase< Output >::_initialized, libMesh::WrappedFunction< Output >::_parameters, libMesh::System::get_equation_systems(), and libMesh::EquationSystems::parameters.
     : _sys(sys),
       _fptr(fptr),
       _parameters(parameters),
       _varnum(varnum)
   {
     this->_initialized = true;
     if (!parameters)
       _parameters = &sys.get_equation_systems().parameters;
   }
WrappedFunction() [2/3]
template<typename Output = Number> libMesh::WrappedFunction< Output >::WrappedFunction (WrappedFunction< Output > &&) default
The move/copy ctor and destructor are defaulted for this class.
WrappedFunction() [3/3]
template<typename Output = Number> libMesh::WrappedFunction< Output >::WrappedFunction (const WrappedFunction< Output > &) default
~WrappedFunction()
template<typename Output = Number> virtual libMesh::WrappedFunction< Output >::~WrappedFunction () virtual default
Member Function Documentation
clear()
template<typename Output = Number> virtual void libMesh::FunctionBase< Output >::clear () inline virtual inherited
Clears the function.
Reimplemented in libMesh::ParsedFunction< Output, OutputGradient >, libMesh::ParsedFunction< T >, libMesh::MeshFunction, and libMesh::AnalyticFunction< Output >.
Definition at line 92 of file function_base.h.
 {}
clone()
template<typename Output > std::unique_ptr< FunctionBase< Output > > libMesh::WrappedFunction< Output >::clone () const inline override virtual
Returns
A new copy of the function.
The new copy should be as "deep" as necessary to allow independent destruction and simultaneous evaluations of the copies in different threads.
Implements libMesh::FunctionBase< Output >.
Definition at line 136 of file wrapped_function.h.
 {
   return std::unique_ptr<FunctionBase<Output>>
     (new WrappedFunction<Output>
      (_sys, _fptr, _parameters, _varnum));
 }
component()
template<typename Output > Output libMesh::WrappedFunction< Output >::component (unsigned int i, const Point & p, Real time = 0.) inline override virtual
Returns
The vector component i at coordinate p and time time.
Note
Subclasses aren't required to override this, since the default implementation is based on the full vector evaluation, which is often correct.
Subclasses are recommended to override this, since the default implementation is based on a vector evaluation, which is usually unnecessarily inefficient.
Reimplemented from libMesh::FunctionBase< Output >.
Definition at line 187 of file wrapped_function.h.
References n_vars, and libMesh::SCALAR.
 {
   libmesh_assert(_fptr);
   libmesh_assert(_parameters);
   // Loop over variables, then over each component in
   // vector-valued variables.
   const unsigned int n_vars = _sys.n_vars();
   for (unsigned int v = 0; v != n_vars; ++v)
     {
       const unsigned int n_components =
         _sys.variable(v).n_components();
       if (n_components == 1 &&
           i == _sys.variable_scalar_number(v,0))
         return _fptr(p, *_parameters, _sys.name(), _sys.variable_name(v));
       else if (i >= _sys.variable_scalar_number(v,0) &&
                i <= _sys.variable_scalar_number(v,n_components-1))
         {
           // Right now our only non-scalar variable type is the
           // SCALAR variables.  The irony is priceless.
           libmesh_assert_equal_to (_sys.variable(i).type().family, SCALAR);
           // We pass the point (j,0,0) to an old-style fptr function
           // pointer to distinguish the different scalars within the
           // SCALAR variable.
           for (unsigned int j=0; j != n_components; ++j)
             if (i == _sys.variable_scalar_number(v,j))
               return _fptr(Point(j,0,0), *_parameters,
                            _sys.name(), _sys.variable_name(v));
         }
     }
   libmesh_error_msg("Component index " << i << " not found in system " << _sys.name());
   return Output();
 }
init()
template<typename Output = Number> virtual void libMesh::FunctionBase< Output >::init () inline virtual inherited
The actual initialization process.
Reimplemented in libMesh::ParsedFunction< Output, OutputGradient >, libMesh::ParsedFunction< T >, libMesh::MeshFunction, and libMesh::AnalyticFunction< Output >.
Definition at line 87 of file function_base.h.
Referenced by libMesh::MeshFunction::clone().
 {}
initialized()
template<typename Output > bool libMesh::FunctionBase< Output >::initialized () const inline inherited
Returns
true when this object is properly initialized and ready for use, false otherwise.
Definition at line 206 of file function_base.h.
 {
   return (this->_initialized);
 }
is_time_dependent()
template<typename Output > bool libMesh::FunctionBase< Output >::is_time_dependent () const inline inherited
Returns
true when the function this object represents is actually time-dependent, false otherwise.
Definition at line 220 of file function_base.h.
Referenced by libMesh::CompositeFunction< Output >::attach_subfunction().
 {
   return (this->_is_time_dependent);
 }
operator()() [1/3]
template<typename Output > Output libMesh::WrappedFunction< Output >::operator() (const Point & p, const Real time = 0.) inline override virtual
Returns
The scalar function value at coordinate p and time time, which defaults to zero.
Pure virtual, so you have to override it.
Implements libMesh::FunctionBase< Output >.
Definition at line 121 of file wrapped_function.h.
 {
   libmesh_assert(_fptr);
   libmesh_assert(_parameters);
   return _fptr(p,
                *_parameters,
                _sys.name(),
                _sys.variable_name(_varnum));
 }
operator()() [2/3]
template<typename Output > void libMesh::WrappedFunction< Output >::operator() (const Point & p, const Real time, DenseVector< Output > & output) inline override virtual
Evaluation function for time-dependent vector-valued functions. Sets output values in the passed-in output DenseVector.
Pure virtual, so you have to override it.
Implements libMesh::FunctionBase< Output >.
Definition at line 146 of file wrapped_function.h.
References n_vars, libMesh::SCALAR, and libMesh::DenseVector< T >::size().
 {
   libmesh_assert(_fptr);
   libmesh_assert(_parameters);
   // We fill each entry of output with a single scalar component of
   // the data in our System
   libmesh_assert_equal_to (output.size(), _sys.n_components());
   // Loop over variables, then over each component in
   // vector-valued variables, evaluating each.
   const unsigned int n_vars = _sys.n_vars();
   for (unsigned int v = 0; v != n_vars; ++v)
     {
       const unsigned int n_components =
         _sys.variable(v).n_components();
       if (n_components == 1)
         output(_sys.variable_scalar_number(v,0)) =
           _fptr(p, *_parameters, _sys.name(), _sys.variable_name(v));
       else
         {
           // Right now our only non-scalar variable type is the
           // SCALAR variables.  The irony is priceless.
           libmesh_assert_equal_to (_sys.variable(v).type().family, SCALAR);
           // We pass the point (j,0,0) to an old-style fptr function
           // pointer to distinguish the different scalars within the
           // SCALAR variable.
           for (unsigned int j=0; j != n_components; ++j)
             output(_sys.variable_scalar_number(v,j)) =
               _fptr(Point(j,0,0), *_parameters,
                     _sys.name(), _sys.variable_name(v));
         }
     }
 }
operator()() [3/3]
template<typename Output> void libMesh::FunctionBase< Output >::operator() (const Point & p, DenseVector< Output > & output) inline inherited
Evaluation function for time-independent vector-valued functions. Sets output values in the passed-in output DenseVector.
Definition at line 241 of file function_base.h.
 {
   // Call the time-dependent function with t=0.
   this->operator()(p, 0., output);
 }
operator=() [1/2]
template<typename Output = Number> WrappedFunction& libMesh::WrappedFunction< Output >::operator= (const WrappedFunction< Output > &) delete
This class contains a const reference so it can't be assigned.
operator=() [2/2]
template<typename Output = Number> WrappedFunction& libMesh::WrappedFunction< Output >::operator= (WrappedFunction< Output > &&) delete
set_is_time_dependent()
template<typename Output > void libMesh::FunctionBase< Output >::set_is_time_dependent (bool is_time_dependent) inline inherited
Function to set whether this is a time-dependent function or not. This is intended to be only used by subclasses who cannot natively determine time-dependence. In such a case, this function should be used immediately following construction.
Definition at line 213 of file function_base.h.
 {
   this->_is_time_dependent = is_time_dependent;
 }
Member Data Documentation
_fptr
template<typename Output = Number> Output(* libMesh::WrappedFunction< Output >::_fptr) (const Point &p, const Parameters &parameters, const std::string &sys_name, const std::string &unknown_name) protected
Definition at line 104 of file wrapped_function.h.
_initialized
template<typename Output = Number> bool libMesh::FunctionBase< Output >::_initialized protected inherited
When init() was called so that everything is ready for calls to operator() (...), then this bool is true.
Definition at line 180 of file function_base.h.
Referenced by libMesh::AnalyticFunction< Output >::AnalyticFunction(), libMesh::ConstFunction< Output >::ConstFunction(), and libMesh::WrappedFunction< Output >::WrappedFunction().
_is_time_dependent
template<typename Output = Number> bool libMesh::FunctionBase< Output >::_is_time_dependent protected inherited
Cache whether or not this function is actually time-dependent.
Definition at line 185 of file function_base.h.
Referenced by libMesh::CompositeFunction< Output >::attach_subfunction(), and libMesh::ConstFunction< Output >::ConstFunction().
_master
template<typename Output = Number> const FunctionBase* libMesh::FunctionBase< Output >::_master protected inherited
Const pointer to our master, initialized to nullptr. There may be cases where multiple functions are required, but to save memory, one master handles some centralized data.
Definition at line 174 of file function_base.h.
_parameters
template<typename Output = Number> const Parameters* libMesh::WrappedFunction< Output >::_parameters protected
Definition at line 109 of file wrapped_function.h.
Referenced by libMesh::WrappedFunction< Output >::WrappedFunction().
_sys
template<typename Output = Number> const System& libMesh::WrappedFunction< Output >::_sys protected
Definition at line 102 of file wrapped_function.h.
_varnum
template<typename Output = Number> unsigned int libMesh::WrappedFunction< Output >::_varnum protected
Definition at line 111 of file wrapped_function.h.
The documentation for this class was generated from the following file:
wrapped_function.h