libMesh: libMesh::OrderWrapper Class Reference
SomeWebsiteLogo
libMesh::OrderWrapper Class Reference
#include <fe_type.h>
Public Member Functions
OrderWrapper (Order order)
OrderWrapper (int order)
operator Order () const
int get_order () const
Private Attributes
int _order
Detailed Description
This provides a shim class that wraps the Order enum. The purpose of this is to store the order as an int instead of an enum (to enable higher orders) while retaining backwards compatibility.
Definition at line 46 of file fe_type.h.
Constructor & Destructor Documentation
OrderWrapper() [1/2]
libMesh::OrderWrapper::OrderWrapper (Order order) inline
Constructor. Enables implicit conversion from an Order enum to an OrderWrapper.
Definition at line 54 of file fe_type.h.
                             :
     _order(static_cast<int>(order))
   {}
OrderWrapper() [2/2]
libMesh::OrderWrapper::OrderWrapper (int order) inline
Constructor. Enables implicit conversion from an int to an OrderWrapper.
Definition at line 62 of file fe_type.h.
                           :
     _order(order)
   {}
Member Function Documentation
get_order()
int libMesh::OrderWrapper::get_order () const inline
Explicitly request the order as an int.
Definition at line 78 of file fe_type.h.
References _order.
Referenced by libMesh::PetscDMWrapper::add_dofs_to_section(), libMesh::FEGenericBase< FEOutputType< T >::type >::compute_proj_constraints(), libMesh::InfFE< Dim, T_radial, T_map >::compute_shape_indices(), libMesh::GMVIO::copy_nodal_solution(), libMesh::FEType::default_quadrature_order(), libMesh::DofMap::distribute_dofs(), libMesh::DofMap::distribute_local_dofs_node_major(), libMesh::DofMap::distribute_local_dofs_var_major(), libMesh::Variable::n_components(), libMesh::operator<(), libMesh::operator<<(), libMesh::operator==(), libMesh::OrderWrapperOperators(), libMesh::System::read_header(), libMesh::System::read_SCALAR_dofs(), libMesh::DofMap::reinit(), and libMesh::DofMap::SCALAR_dof_indices().
   {
     return _order;
   }
operator Order()
libMesh::OrderWrapper::operator Order () const inline
Operator that enables implicit conversion to an Order enum.
Definition at line 70 of file fe_type.h.
References _order.
   {
     return static_cast<Order>(_order);
   }
Member Data Documentation
_order
int libMesh::OrderWrapper::_order private
The approximation order of the element.
Definition at line 88 of file fe_type.h.
Referenced by get_order(), and operator Order().
The documentation for this class was generated from the following file:
fe_type.h