libMesh: libMesh::EigenSparseMatrix< T > Class Template Reference
SomeWebsiteLogo
libMesh::EigenSparseMatrix< T > Class Template Reference
#include <eigen_sparse_matrix.h>
Public Types
typedef EigenSM DataType
typedef Eigen::Triplet< T, eigen_idx_type > TripletType
Public Member Functions
EigenSparseMatrix (const Parallel::Communicator &comm LIBMESH_CAN_DEFAULT_TO_COMMWORLD)
~EigenSparseMatrix ()
virtual void init (const numeric_index_type m, const numeric_index_type n, const numeric_index_type m_l, const numeric_index_type n_l, const numeric_index_type nnz=30, const numeric_index_type noz=10, const numeric_index_type blocksize=1) libmesh_override
virtual void init () libmesh_override
virtual void clear () libmesh_override
virtual void zero () libmesh_override
virtual void close () const libmesh_override
virtual numeric_index_type m () const libmesh_override
virtual numeric_index_type n () const libmesh_override
virtual numeric_index_type row_start () const libmesh_override
virtual numeric_index_type row_stop () const libmesh_override
virtual void set (const numeric_index_type i, const numeric_index_type j, const T value) libmesh_override
virtual void add (const numeric_index_type i, const numeric_index_type j, const T value) libmesh_override
virtual void add_matrix (const DenseMatrix< T > &dm, const std::vector< numeric_index_type > &rows, const std::vector< numeric_index_type > &cols) libmesh_override
virtual void add_matrix (const DenseMatrix< T > &dm, const std::vector< numeric_index_type > &dof_indices) libmesh_override
virtual void add (const T a, SparseMatrix< T > &X) libmesh_override
virtual T operator() (const numeric_index_type i, const numeric_index_type j) const libmesh_override
virtual Real l1_norm () const libmesh_override
virtual Real linfty_norm () const libmesh_override
virtual bool closed () const libmesh_override
virtual void print_personal (std::ostream &os=libMesh::out) const libmesh_override
virtual void get_diagonal (NumericVector< T > &dest) const libmesh_override
virtual void get_transpose (SparseMatrix< T > &dest) const libmesh_override
virtual bool initialized () const
void attach_dof_map (const DofMap &dof_map)
virtual bool need_full_sparsity_pattern () const
virtual void update_sparsity_pattern (const SparsityPattern::Graph &)
virtual void zero_rows (std::vector< numeric_index_type > &rows, T diag_value=0.0)
virtual void add_block_matrix (const DenseMatrix< T > &dm, const std::vector< numeric_index_type > &brows, const std::vector< numeric_index_type > &bcols)
virtual void add_block_matrix (const DenseMatrix< T > &dm, const std::vector< numeric_index_type > &dof_indices)
void print (std::ostream &os=libMesh::out, const bool sparse=false) const
template<>
void print (std::ostream &os, const bool sparse) const
virtual void print_matlab (const std::string &="") const
virtual void create_submatrix (SparseMatrix< T > &submatrix, const std::vector< numeric_index_type > &rows, const std::vector< numeric_index_type > &cols) const
virtual void reinit_submatrix (SparseMatrix< T > &submatrix, const std::vector< numeric_index_type > &rows, const std::vector< numeric_index_type > &cols) const
void vector_mult (NumericVector< T > &dest, const NumericVector< T > &arg) const
void vector_mult_add (NumericVector< T > &dest, const NumericVector< T > &arg) const
const Parallel::Communicator & comm () const
processor_id_type n_processors () const
processor_id_type processor_id () const
Static Public Member Functions
static UniquePtr< SparseMatrix< T > > build (const Parallel::Communicator &comm, const SolverPackage solver_package=libMesh::default_solver_package())
static std::string get_info ()
static void print_info (std::ostream &out=libMesh::out)
static unsigned int n_objects ()
static void enable_print_counter_info ()
static void disable_print_counter_info ()
Protected Types
typedef std::map< std::string, std::pair< unsigned int, unsigned int > > Counts
Protected Member Functions
virtual void _get_submatrix (SparseMatrix< T > &, const std::vector< numeric_index_type > &, const std::vector< numeric_index_type > &, const bool) const
void increment_constructor_count (const std::string &name)
void increment_destructor_count (const std::string &name)
Protected Attributes
DofMap const * _dof_map
bool _is_initialized
const Parallel::Communicator & _communicator
Static Protected Attributes
static Counts _counts
static Threads::atomic< unsigned int > _n_objects
static Threads::spin_mutex _mutex
static bool _enable_print_counter = true
Private Attributes
DataType _mat
bool _closed
Friends
class EigenSparseVector< T >
class EigenSparseLinearSolver< T >
Detailed Description
template<typename T>
class libMesh::EigenSparseMatrix< T >
The EigenSparseMatrix class wraps a sparse matrix object from the Eigen library.
Author
Benjamin S. Kirk
Date
2013
Definition at line 53 of file eigen_sparse_matrix.h.
Member Typedef Documentation
typedef std::map<std::string, std::pair<unsigned int, unsigned int> > libMesh::ReferenceCounter::Counts protected inherited
Data structure to log the information. The log is identified by the class name.
Definition at line 110 of file reference_counter.h.
template<typename T> typedef EigenSM libMesh::EigenSparseMatrix< T >::DataType
Convenient typedefs
Definition at line 85 of file eigen_sparse_matrix.h.
template<typename T> typedef Eigen::Triplet<T,eigen_idx_type> libMesh::EigenSparseMatrix< T >::TripletType
Definition at line 86 of file eigen_sparse_matrix.h.
Constructor & Destructor Documentation
template<typename T> libMesh::EigenSparseMatrix< T >::EigenSparseMatrix (const Parallel::Communicator &comm LIBMESH_CAN_DEFAULT_TO_COMMWORLD)
Constructor; initializes the matrix to be empty, without any structure, i.e. the matrix is not usable at all. This constructor is therefore only useful for matrices which are members of a class. All other matrices should be created at a point in the data flow where all necessary information is available.
You have to initialize the matrix before usage with init(...).
Definition at line 161 of file eigen_sparse_matrix.C.
                                                                              :
   SparseMatrix<T>(comm_in),
   _closed (false)
 {
 }
template<typename T > libMesh::EigenSparseMatrix< T >::~EigenSparseMatrix ()
Destructor. Free all memory, but do not release the memory of the sparsity structure.
Definition at line 170 of file eigen_sparse_matrix.C.
References libMesh::EigenSparseMatrix< T >::clear().
 {
   this->clear ();
 }
Member Function Documentation
template<typename T> virtual void libMesh::SparseMatrix< T >::_get_submatrix (SparseMatrix< T > & , const std::vector< numeric_index_type > & , const std::vector< numeric_index_type > & , const bool) const inline protected virtual inherited
Protected implementation of the create_submatrix and reinit_submatrix routines. Note that this function must be redefined in derived classes for it to work properly!
Reimplemented in libMesh::PetscMatrix< T >.
Definition at line 425 of file sparse_matrix.h.
   {
     libmesh_not_implemented();
   }
template<typename T > void libMesh::EigenSparseMatrix< T >::add (const numeric_index_type i, const numeric_index_type j, const T value) virtual
Add value to the element (i,j). Throws an error if the entry does not exist. Still, it is allowed to store zero values in non-existent fields.
Implements libMesh::SparseMatrix< T >.
Definition at line 247 of file eigen_sparse_matrix.C.
References libMesh::EigenSparseMatrix< T >::_mat, libMesh::SparseMatrix< T >::initialized(), libMesh::libmesh_assert(), libMesh::EigenSparseMatrix< T >::m(), and libMesh::EigenSparseMatrix< T >::n().
Referenced by libMesh::EigenSparseMatrix< T >::close().
 {
   libmesh_assert (this->initialized());
   libmesh_assert_less (i, this->m());
   libmesh_assert_less (j, this->n());
   _mat.coeffRef(i,j) += value;
 }
template<typename T > void libMesh::EigenSparseMatrix< T >::add (const T a, SparseMatrix< T > & X) virtual
Add a Sparse matrix X, scaled with a, to this, stores the result in this: . LASPACK does not provide a true axpy for matrices, so a hand-coded version with hopefully acceptable performance is provided.
Implements libMesh::SparseMatrix< T >.
Definition at line 270 of file eigen_sparse_matrix.C.
References libMesh::EigenSparseMatrix< T >::_mat, libMesh::SparseMatrix< T >::initialized(), libMesh::libmesh_assert(), libMesh::EigenSparseMatrix< T >::m(), libMesh::SparseMatrix< T >::m(), libMesh::EigenSparseMatrix< T >::n(), and libMesh::SparseMatrix< T >::n().
 {
   libmesh_assert (this->initialized());
   libmesh_assert_equal_to (this->m(), X_in.m());
   libmesh_assert_equal_to (this->n(), X_in.n());
   EigenSparseMatrix<T> & X = cast_ref<EigenSparseMatrix<T> &> (X_in);
   _mat += X._mat*a_in;
 }
template<typename T> void libMesh::SparseMatrix< T >::add_block_matrix (const DenseMatrix< T > & dm, const std::vector< numeric_index_type > & brows, const std::vector< numeric_index_type > & bcols) virtual inherited
Add the full matrix dm to the Sparse matrix. This is useful for adding an element matrix at assembly time. The matrix is assumed blocked, and brow, bcol correspond to the block row, columm indices.
Reimplemented in libMesh::PetscMatrix< T >.
Definition at line 61 of file sparse_matrix.C.
References libMesh::SparseMatrix< T >::add_matrix(), libMesh::DenseMatrixBase< T >::m(), and libMesh::DenseMatrixBase< T >::n().
 {
   libmesh_assert_equal_to (dm.m() / brows.size(), dm.n() / bcols.size());
   const numeric_index_type blocksize = cast_int<numeric_index_type>
     (dm.m() / brows.size());
   libmesh_assert_equal_to (dm.m()%blocksize, 0);
   libmesh_assert_equal_to (dm.n()%blocksize, 0);
   std::vector<numeric_index_type> rows, cols;
   rows.reserve(blocksize*brows.size());
   cols.reserve(blocksize*bcols.size());
   for (std::size_t ib=0; ib<brows.size(); ib++)
     {
       numeric_index_type i=brows[ib]*blocksize;
       for (unsigned int v=0; v<blocksize; v++)
         rows.push_back(i++);
     }
   for (std::size_t jb=0; jb<bcols.size(); jb++)
     {
       numeric_index_type j=bcols[jb]*blocksize;
       for (unsigned int v=0; v<blocksize; v++)
         cols.push_back(j++);
     }
   this->add_matrix (dm, rows, cols);
 }
template<typename T> virtual void libMesh::SparseMatrix< T >::add_block_matrix (const DenseMatrix< T > & dm, const std::vector< numeric_index_type > & dof_indices) inline virtual inherited
Same as add_block_matrix , but assumes the row and column maps are the same. Thus the matrix dm must be square.
Reimplemented in libMesh::PetscMatrix< T >.
Definition at line 258 of file sparse_matrix.h.
   { this->add_block_matrix (dm, dof_indices, dof_indices); }
template<typename T > void libMesh::EigenSparseMatrix< T >::add_matrix (const DenseMatrix< T > & dm, const std::vector< numeric_index_type > & rows, const std::vector< numeric_index_type > & cols) virtual
Add the full matrix to the Eigen matrix. This is useful for adding an element matrix at assembly time
Implements libMesh::SparseMatrix< T >.
Definition at line 121 of file eigen_sparse_matrix.C.
References libMesh::initialized(), libMesh::libmesh_assert(), libMesh::DenseMatrixBase< T >::m(), and libMesh::DenseMatrixBase< T >::n().
Referenced by libMesh::EigenSparseMatrix< T >::add_matrix(), and libMesh::EigenSparseMatrix< T >::close().
 {
   libmesh_assert (this->initialized());
   unsigned int n_rows = cast_int<unsigned int>(rows.size());
   unsigned int n_cols = cast_int<unsigned int>(cols.size());
   libmesh_assert_equal_to (dm.m(), n_rows);
   libmesh_assert_equal_to (dm.n(), n_cols);
   for (unsigned int i=0; i<n_rows; i++)
     for (unsigned int j=0; j<n_cols; j++)
       this->add(rows[i],cols[j],dm(i,j));
 }
template<typename T > void libMesh::EigenSparseMatrix< T >::add_matrix (const DenseMatrix< T > & dm, const std::vector< numeric_index_type > & dof_indices) virtual
Same, but assumes the row and column maps are the same. Thus the matrix dm must be square.
Implements libMesh::SparseMatrix< T >.
Definition at line 261 of file eigen_sparse_matrix.C.
References libMesh::EigenSparseMatrix< T >::add_matrix().
 {
   this->add_matrix (dm, dof_indices, dof_indices);
 }
template<typename T> void libMesh::SparseMatrix< T >::attach_dof_map (const DofMap & dof_map) inline inherited
Get a pointer to the DofMap to use.
Definition at line 112 of file sparse_matrix.h.
Referenced by libMesh::__libmesh_tao_hessian(), and libMesh::DofMap::attach_matrix().
   { _dof_map = &dof_map; }
template<typename T > UniquePtr< SparseMatrix< T > > libMesh::SparseMatrix< T >::build (const Parallel::Communicator & comm, const SolverPackage solver_package = libMesh::default_solver_package()) static inherited
Builds a SparseMatrix<T> using the linear solver package specified by solver_package
Definition at line 135 of file sparse_matrix.C.
References libMesh::ParallelObject::comm(), libMesh::EIGEN_SOLVERS, libMesh::LASPACK_SOLVERS, libMesh::PETSC_SOLVERS, and libMesh::TRILINOS_SOLVERS.
Referenced by libMesh::ImplicitSystem::add_matrix().
 {
   // Build the appropriate vector
   switch (solver_package)
     {
 #ifdef LIBMESH_HAVE_LASPACK
     case LASPACK_SOLVERS:
       return UniquePtr<SparseMatrix<T> >(new LaspackMatrix<T>(comm));
 #endif
 #ifdef LIBMESH_HAVE_PETSC
     case PETSC_SOLVERS:
       return UniquePtr<SparseMatrix<T> >(new PetscMatrix<T>(comm));
 #endif
 #ifdef LIBMESH_TRILINOS_HAVE_EPETRA
     case TRILINOS_SOLVERS:
       return UniquePtr<SparseMatrix<T> >(new EpetraMatrix<T>(comm));
 #endif
 #ifdef LIBMESH_HAVE_EIGEN
     case EIGEN_SOLVERS:
       return UniquePtr<SparseMatrix<T> >(new EigenSparseMatrix<T>(comm));
 #endif
     default:
       libmesh_error_msg("ERROR:  Unrecognized solver package: " << solver_package);
     }
   libmesh_error_msg("We'll never get here!");
   return UniquePtr<SparseMatrix<T> >();
 }
template<typename T > void libMesh::EigenSparseMatrix< T >::clear () virtual
Release all memory and return to a state just like after having called the default constructor.
Implements libMesh::SparseMatrix< T >.
Definition at line 178 of file eigen_sparse_matrix.C.
References libMesh::EigenSparseMatrix< T >::_closed, libMesh::SparseMatrix< T >::_is_initialized, and libMesh::EigenSparseMatrix< T >::_mat.
Referenced by libMesh::EigenSparseMatrix< T >::~EigenSparseMatrix().
 {
   _mat.resize(0,0);
   _closed = false;
   this->_is_initialized = false;
 }
template<typename T> virtual void libMesh::EigenSparseMatrix< T >::close () const inline virtual
Close the matrix. Dummy routine. After calling this method closed() is true and the matrix can be used in computations.
Implements libMesh::SparseMatrix< T >.
Definition at line 129 of file eigen_sparse_matrix.h.
References libMesh::EigenSparseMatrix< T >::_closed, libMesh::EigenSparseMatrix< T >::add(), libMesh::EigenSparseMatrix< T >::add_matrix(), libMesh::EigenSparseMatrix< T >::l1_norm(), libMesh::EigenSparseMatrix< T >::linfty_norm(), libMesh::EigenSparseMatrix< T >::m(), libMesh::EigenSparseMatrix< T >::n(), libMesh::EigenSparseMatrix< T >::operator()(), libMesh::Real, libMesh::EigenSparseMatrix< T >::row_start(), and libMesh::EigenSparseMatrix< T >::row_stop().
Referenced by libMesh::EigenSparseLinearSolver< T >::solve().
 { const_cast<EigenSparseMatrix<T> *>(this)->_closed = true; }
template<typename T> virtual bool libMesh::EigenSparseMatrix< T >::closed () const inline virtual
see if Eigen matrix has been closed and fully assembled yet
Implements libMesh::SparseMatrix< T >.
Definition at line 242 of file eigen_sparse_matrix.h.
References libMesh::EigenSparseMatrix< T >::_closed.
 { return _closed; }
const Parallel::Communicator& libMesh::ParallelObject::comm () const inline inherited
Returns
a reference to the Parallel::Communicator object used by this mesh.
Definition at line 87 of file parallel_object.h.
References libMesh::ParallelObject::_communicator.
Referenced by libMesh::__libmesh_petsc_diff_solver_monitor(), libMesh::__libmesh_petsc_diff_solver_residual(), libMesh::__libmesh_petsc_snes_jacobian(), libMesh::__libmesh_petsc_snes_postcheck(), libMesh::__libmesh_petsc_snes_residual(), libMesh::__libmesh_tao_equality_constraints(), libMesh::__libmesh_tao_equality_constraints_jacobian(), libMesh::__libmesh_tao_gradient(), libMesh::__libmesh_tao_hessian(), libMesh::__libmesh_tao_inequality_constraints(), libMesh::__libmesh_tao_inequality_constraints_jacobian(), libMesh::__libmesh_tao_objective(), libMesh::MeshRefinement::_coarsen_elements(), libMesh::ExactSolution::_compute_error(), libMesh::ParmetisPartitioner::_do_repartition(), libMesh::UniformRefinementEstimator::_estimate_error(), libMesh::BoundaryInfo::_find_id_maps(), libMesh::PetscLinearSolver< T >::_petsc_shell_matrix_get_diagonal(), libMesh::SlepcEigenSolver< T >::_petsc_shell_matrix_get_diagonal(), libMesh::PetscLinearSolver< T >::_petsc_shell_matrix_mult(), libMesh::SlepcEigenSolver< T >::_petsc_shell_matrix_mult(), libMesh::PetscLinearSolver< T >::_petsc_shell_matrix_mult_add(), libMesh::EquationSystems::_read_impl(), libMesh::MeshRefinement::_refine_elements(), libMesh::MeshRefinement::_smooth_flags(), libMesh::ImplicitSystem::add_matrix(), libMesh::System::add_vector(), libMesh::EigenSparseLinearSolver< T >::adjoint_solve(), libMesh::UnstructuredMesh::all_second_order(), libMesh::MeshTools::Modification::all_tri(), libMesh::LaplaceMeshSmoother::allgather_graph(), libMesh::FEMSystem::assemble_qoi(), libMesh::MeshCommunication::assign_global_indices(), libMesh::ParmetisPartitioner::assign_partitioning(), libMesh::DofMap::attach_matrix(), libMesh::Parallel::BinSorter< KeyType, IdxType >::binsort(), libMesh::Parallel::Sort< KeyType, IdxType >::binsort(), libMesh::MeshTools::bounding_box(), libMesh::MeshCommunication::broadcast(), libMesh::SparseMatrix< T >::build(), libMesh::MeshTools::Generation::build_extrusion(), libMesh::Parallel::Histogram< KeyType, IdxType >::build_histogram(), libMesh::PetscNonlinearSolver< T >::build_mat_null_space(), libMesh::BoundaryInfo::build_node_list_from_side_list(), libMesh::EquationSystems::build_parallel_solution_vector(), libMesh::MeshBase::cache_elem_dims(), libMesh::System::calculate_norm(), libMesh::DofMap::check_dirichlet_bcid_consistency(), libMesh::DistributedVector< T >::clone(), libMesh::EigenSparseVector< T >::clone(), libMesh::LaspackVector< T >::clone(), libMesh::EpetraVector< T >::clone(), libMesh::PetscVector< T >::clone(), libMesh::EpetraVector< T >::close(), libMesh::Parallel::Sort< KeyType, IdxType >::communicate_bins(), libMesh::Nemesis_IO_Helper::compute_num_global_elem_blocks(), libMesh::Nemesis_IO_Helper::compute_num_global_nodesets(), libMesh::Nemesis_IO_Helper::compute_num_global_sidesets(), libMesh::Problem_Interface::computeF(), libMesh::Problem_Interface::computeJacobian(), libMesh::Problem_Interface::computePreconditioner(), libMesh::MeshTools::correct_node_proc_ids(), libMesh::MeshRefinement::create_parent_error_vector(), libMesh::MeshCommunication::delete_remote_elements(), libMesh::DofMap::distribute_dofs(), DMlibMeshFunction(), DMlibMeshJacobian(), DMlibMeshSetSystem_libMesh(), DMVariableBounds_libMesh(), libMesh::MeshRefinement::eliminate_unrefined_patches(), libMesh::EpetraVector< T >::EpetraVector(), libMesh::WeightedPatchRecoveryErrorEstimator::estimate_error(), libMesh::PatchRecoveryErrorEstimator::estimate_error(), libMesh::JumpErrorEstimator::estimate_error(), libMesh::AdjointRefinementEstimator::estimate_error(), libMesh::ExactErrorEstimator::estimate_error(), libMesh::MeshRefinement::flag_elements_by_elem_fraction(), libMesh::MeshRefinement::flag_elements_by_error_fraction(), libMesh::MeshRefinement::flag_elements_by_nelem_target(), libMesh::MeshCommunication::gather(), libMesh::MeshCommunication::gather_neighboring_elements(), libMesh::CondensedEigenSystem::get_eigenpair(), libMesh::DofMap::get_info(), libMesh::ImplicitSystem::get_linear_solver(), libMesh::EquationSystems::get_solution(), libMesh::LocationMap< T >::init(), libMesh::PetscDiffSolver::init(), libMesh::TimeSolver::init(), libMesh::TopologyMap::init(), libMesh::TaoOptimizationSolver< T >::init(), libMesh::PetscNonlinearSolver< T >::init(), libMesh::DistributedVector< T >::init(), libMesh::EpetraVector< T >::init(), libMesh::PetscVector< T >::init(), libMesh::SystemSubsetBySubdomain::init(), libMesh::EigenSystem::init_data(), libMesh::EigenSystem::init_matrices(), libMesh::ParmetisPartitioner::initialize(), libMesh::OptimizationSystem::initialize_equality_constraints_storage(), libMesh::OptimizationSystem::initialize_inequality_constraints_storage(), libMesh::MeshTools::libmesh_assert_parallel_consistent_procids< Elem >(), libMesh::MeshTools::libmesh_assert_parallel_consistent_procids< Node >(), libMesh::MeshTools::libmesh_assert_topology_consistent_procids< Node >(), libMesh::MeshTools::libmesh_assert_valid_boundary_ids(), libMesh::MeshTools::libmesh_assert_valid_dof_ids(), libMesh::MeshTools::libmesh_assert_valid_neighbors(), libMesh::DistributedMesh::libmesh_assert_valid_parallel_flags(), libMesh::DistributedMesh::libmesh_assert_valid_parallel_object_ids(), libMesh::DistributedMesh::libmesh_assert_valid_parallel_p_levels(), libMesh::MeshTools::libmesh_assert_valid_refinement_flags(), libMesh::MeshTools::libmesh_assert_valid_unique_ids(), libMesh::MeshRefinement::limit_level_mismatch_at_edge(), libMesh::MeshRefinement::limit_level_mismatch_at_node(), libMesh::MeshRefinement::limit_overrefined_boundary(), libMesh::MeshRefinement::limit_underrefined_boundary(), libMesh::MeshRefinement::make_coarsening_compatible(), libMesh::MeshCommunication::make_elems_parallel_consistent(), libMesh::MeshRefinement::make_flags_parallel_consistent(), libMesh::MeshCommunication::make_new_node_proc_ids_parallel_consistent(), libMesh::MeshCommunication::make_new_nodes_parallel_consistent(), libMesh::MeshCommunication::make_node_ids_parallel_consistent(), libMesh::MeshCommunication::make_node_proc_ids_parallel_consistent(), libMesh::MeshCommunication::make_node_unique_ids_parallel_consistent(), libMesh::MeshCommunication::make_nodes_parallel_consistent(), libMesh::MeshCommunication::make_p_levels_parallel_consistent(), libMesh::MeshRefinement::make_refinement_compatible(), libMesh::DistributedVector< T >::max(), libMesh::FEMSystem::mesh_position_set(), libMesh::MeshSerializer::MeshSerializer(), libMesh::DistributedVector< T >::min(), libMesh::DistributedMesh::n_active_elem(), libMesh::MeshTools::n_active_levels(), libMesh::BoundaryInfo::n_boundary_conds(), libMesh::BoundaryInfo::n_edge_conds(), libMesh::CondensedEigenSystem::n_global_non_condensed_dofs(), libMesh::MeshTools::n_levels(), libMesh::BoundaryInfo::n_nodeset_conds(), libMesh::MeshTools::n_p_levels(), libMesh::BoundaryInfo::n_shellface_conds(), libMesh::DistributedMesh::parallel_max_elem_id(), libMesh::DistributedMesh::parallel_max_node_id(), libMesh::ReplicatedMesh::parallel_max_unique_id(), libMesh::DistributedMesh::parallel_max_unique_id(), libMesh::DistributedMesh::parallel_n_elem(), libMesh::DistributedMesh::parallel_n_nodes(), libMesh::SparsityPattern::Build::parallel_sync(), libMesh::MeshTools::paranoid_n_levels(), libMesh::Partitioner::partition(), libMesh::MetisPartitioner::partition_range(), libMesh::Partitioner::partition_unpartitioned_elements(), libMesh::petsc_auto_fieldsplit(), libMesh::System::point_gradient(), libMesh::System::point_hessian(), libMesh::System::point_value(), libMesh::MeshBase::prepare_for_use(), libMesh::SparseMatrix< T >::print(), libMesh::MeshTools::processor_bounding_box(), libMesh::Nemesis_IO::read(), libMesh::XdrIO::read(), libMesh::XdrIO::read_serialized_bc_names(), libMesh::XdrIO::read_serialized_bcs_helper(), libMesh::XdrIO::read_serialized_connectivity(), libMesh::XdrIO::read_serialized_nodes(), libMesh::XdrIO::read_serialized_nodesets(), libMesh::XdrIO::read_serialized_subdomain_names(), libMesh::MeshBase::recalculate_n_partitions(), libMesh::MeshCommunication::redistribute(), libMesh::DistributedMesh::renumber_dof_objects(), libMesh::MeshCommunication::send_coarse_ghosts(), libMesh::Partitioner::set_node_processor_ids(), libMesh::DofMap::set_nonlocal_dof_objects(), libMesh::Partitioner::set_parent_processor_ids(), libMesh::LaplaceMeshSmoother::smooth(), libMesh::Parallel::Sort< KeyType, IdxType >::sort(), libMesh::MeshTools::subdomain_bounding_box(), libMesh::MeshBase::subdomain_ids(), libMesh::BoundaryInfo::sync(), libMesh::Parallel::sync_element_data_by_parent_id(), libMesh::Parallel::sync_node_data_by_element_id(), libMesh::MeshRefinement::test_level_one(), libMesh::MeshRefinement::test_unflagged(), libMesh::MeshTools::total_weight(), libMesh::NameBasedIO::write(), libMesh::XdrIO::write(), libMesh::XdrIO::write_serialized_bcs_helper(), libMesh::XdrIO::write_serialized_connectivity(), libMesh::XdrIO::write_serialized_nodes(), libMesh::XdrIO::write_serialized_nodesets(), libMesh::DistributedVector< T >::zero_clone(), libMesh::LaspackVector< T >::zero_clone(), libMesh::EigenSparseVector< T >::zero_clone(), libMesh::EpetraVector< T >::zero_clone(), and libMesh::PetscVector< T >::zero_clone().
   { return _communicator; }
template<typename T> virtual void libMesh::SparseMatrix< T >::create_submatrix (SparseMatrix< T > & submatrix, const std::vector< numeric_index_type > & rows, const std::vector< numeric_index_type > & cols) const inline virtual inherited
This function creates a matrix called "submatrix" which is defined by the row and column indices given in the "rows" and "cols" entries. Currently this operation is only defined for the PetscMatrix type.
Definition at line 368 of file sparse_matrix.h.
   {
     this->_get_submatrix(submatrix,
                          rows,
                          cols,
                          false); // false means DO NOT REUSE submatrix
   }
void libMesh::ReferenceCounter::disable_print_counter_info () static inherited
Definition at line 106 of file reference_counter.C.
References libMesh::ReferenceCounter::_enable_print_counter.
Referenced by libMesh::LibMeshInit::LibMeshInit(), and libMesh::ReferenceCounter::n_objects().
 {
   _enable_print_counter = false;
   return;
 }
void libMesh::ReferenceCounter::enable_print_counter_info () static inherited
Methods to enable/disable the reference counter output from print_info()
Definition at line 100 of file reference_counter.C.
References libMesh::ReferenceCounter::_enable_print_counter.
Referenced by libMesh::ReferenceCounter::n_objects().
 {
   _enable_print_counter = true;
   return;
 }
template<typename T > void libMesh::EigenSparseMatrix< T >::get_diagonal (NumericVector< T > & dest) const virtual
Copies the diagonal part of the matrix into dest.
Implements libMesh::SparseMatrix< T >.
Definition at line 141 of file eigen_sparse_matrix.C.
References libMesh::EigenSparseVector< T >::_vec.
Referenced by libMesh::EigenSparseMatrix< T >::print_personal().
 {
   EigenSparseVector<T> & dest = cast_ref<EigenSparseVector<T> &>(dest_in);
   dest._vec = _mat.diagonal();
 }
std::string libMesh::ReferenceCounter::get_info () static inherited
Gets a string containing the reference information.
Definition at line 47 of file reference_counter.C.
References libMesh::ReferenceCounter::_counts, and libMesh::Quality::name().
Referenced by libMesh::ReferenceCounter::print_info().
 {
 #if defined(LIBMESH_ENABLE_REFERENCE_COUNTING) && defined(DEBUG)
   std::ostringstream oss;
   oss << '\n'
       << " ---------------------------------------------------------------------------- \n"
       << "| Reference count information                                                |\n"
       << " ---------------------------------------------------------------------------- \n";
   for (Counts::iterator it = _counts.begin();
        it != _counts.end(); ++it)
     {
       const std::string name(it->first);
       const unsigned int creations    = it->second.first;
       const unsigned int destructions = it->second.second;
       oss << "| " << name << " reference count information:\n"
           << "|  Creations:    " << creations    << '\n'
           << "|  Destructions: " << destructions << '\n';
     }
   oss << " ---------------------------------------------------------------------------- \n";
   return oss.str();
 #else
   return "";
 #endif
 }
template<typename T > void libMesh::EigenSparseMatrix< T >::get_transpose (SparseMatrix< T > & dest) const virtual
Copies the transpose of the matrix into dest, which may be *this.
Implements libMesh::SparseMatrix< T >.
Definition at line 151 of file eigen_sparse_matrix.C.
References libMesh::EigenSparseMatrix< T >::_mat.
Referenced by libMesh::EigenSparseMatrix< T >::print_personal().
 {
   EigenSparseMatrix<T> & dest = cast_ref<EigenSparseMatrix<T> &>(dest_in);
   dest._mat = _mat.transpose();
 }
void libMesh::ReferenceCounter::increment_constructor_count (const std::string & name) inline protected inherited
Increments the construction counter. Should be called in the constructor of any derived class that will be reference counted.
Definition at line 160 of file reference_counter.h.
References libMesh::ReferenceCounter::_counts, libMesh::Quality::name(), and libMesh::Threads::spin_mtx.
Referenced by libMesh::ReferenceCounter::n_objects(), and libMesh::ReferenceCountedObject< RBParametrized >::ReferenceCountedObject().
 {
   Threads::spin_mutex::scoped_lock lock(Threads::spin_mtx);
   std::pair<unsigned int, unsigned int> & p = _counts[name];
   p.first++;
 }
void libMesh::ReferenceCounter::increment_destructor_count (const std::string & name) inline protected inherited
Increments the destruction counter. Should be called in the destructor of any derived class that will be reference counted.
Definition at line 173 of file reference_counter.h.
References libMesh::ReferenceCounter::_counts, libMesh::Quality::name(), and libMesh::Threads::spin_mtx.
Referenced by libMesh::ReferenceCounter::n_objects(), and libMesh::ReferenceCountedObject< RBParametrized >::~ReferenceCountedObject().
 {
   Threads::spin_mutex::scoped_lock lock(Threads::spin_mtx);
   std::pair<unsigned int, unsigned int> & p = _counts[name];
   p.second++;
 }
template<typename T> virtual void libMesh::EigenSparseMatrix< T >::init (const numeric_index_type m, const numeric_index_type n, const numeric_index_type m_l, const numeric_index_type n_l, const numeric_index_type nnz = 30, const numeric_index_type noz = 10, const numeric_index_type blocksize = 1) virtual
Initialize a Eigen matrix that is of global dimension with local dimensions . nnz is the number of on-processor nonzeros per row (defaults to 30). noz is the number of on-processor nonzeros per row (defaults to 30). Optionally supports a block size, which indicates dense coupled blocks for systems with multiple variables all of the same type.
Implements libMesh::SparseMatrix< T >.
template<typename T > void libMesh::EigenSparseMatrix< T >::init () virtual
Initialize using sparsity structure computed by dof_map.
Implements libMesh::SparseMatrix< T >.
Definition at line 63 of file eigen_sparse_matrix.C.
References libMesh::libMeshPrivateData::_is_initialized, libMesh::initialized(), and libMesh::libmesh_assert().
 {
   // Ignore calls on initialized objects
   if (this->initialized())
     return;
   // We need the DofMap for this!
   libmesh_assert(this->_dof_map);
   // Clear intialized matrices
   if (this->initialized())
     this->clear();
   const numeric_index_type n_rows   = this->_dof_map->n_dofs();
   const numeric_index_type n_cols   = n_rows;
 #ifndef NDEBUG
   // The following variables are only used for assertions,
   // so avoid declaring them when asserts are inactive.
   const numeric_index_type n_l = this->_dof_map->n_dofs_on_processor(0);
   const numeric_index_type m_l = n_l;
 #endif
   // Laspack Matrices only work for uniprocessor cases
   libmesh_assert_equal_to (n_rows, n_cols);
   libmesh_assert_equal_to (m_l, n_rows);
   libmesh_assert_equal_to (n_l, n_cols);
   const std::vector<numeric_index_type> & n_nz = this->_dof_map->get_n_nz();
 #ifndef NDEBUG
   // The following variables are only used for assertions,
   // so avoid declaring them when asserts are inactive.
   const std::vector<numeric_index_type> & n_oz = this->_dof_map->get_n_oz();
 #endif
   // Make sure the sparsity pattern isn't empty
   libmesh_assert_equal_to (n_nz.size(), n_l);
   libmesh_assert_equal_to (n_oz.size(), n_l);
   if (n_rows==0)
     {
       _mat.resize(0,0);
       return;
     }
   _mat.resize(n_rows,n_cols);
   _mat.reserve(n_nz);
   this->_is_initialized = true;
   libmesh_assert_equal_to (n_rows, this->m());
   libmesh_assert_equal_to (n_cols, this->n());
 }
template<typename T> virtual bool libMesh::SparseMatrix< T >::initialized () const inline virtual inherited
Returns
true if the matrix has been initialized, false otherwise.
Definition at line 107 of file sparse_matrix.h.
Referenced by libMesh::PetscMatrix< T >::_get_submatrix(), libMesh::EigenSparseMatrix< T >::add(), libMesh::LaspackMatrix< T >::add(), libMesh::ImplicitSystem::assemble(), libMesh::LaspackMatrix< T >::clear(), libMesh::ImplicitSystem::init_matrices(), libMesh::EigenSparseMatrix< T >::m(), libMesh::LaspackMatrix< T >::m(), libMesh::EigenSparseMatrix< T >::n(), libMesh::LaspackMatrix< T >::n(), libMesh::EigenSparseMatrix< T >::operator()(), libMesh::LaspackMatrix< T >::operator()(), libMesh::SparseMatrix< T >::print(), libMesh::EigenSparseMatrix< T >::set(), and libMesh::LaspackMatrix< T >::set().
 { return _is_initialized; }
template<typename T > Real libMesh::EigenSparseMatrix< T >::l1_norm () const virtual
Return the l1-norm of the matrix, that is , (max. sum of columns). This is the natural matrix norm that is compatible to the l1-norm for vectors, i.e. .
Implements libMesh::SparseMatrix< T >.
Definition at line 298 of file eigen_sparse_matrix.C.
References libMesh::EigenSparseMatrix< T >::_mat, std::abs(), libMesh::EigenSparseMatrix< T >::m(), and libMesh::EigenSparseMatrix< T >::n().
Referenced by libMesh::EigenSparseMatrix< T >::close().
 {
   // There does not seem to be a straightforward way to iterate over
   // the columns of an EigenSparseMatrix.  So we use some extra
   // storage and keep track of the column sums while going over the
   // row entries...
   std::vector<Real> abs_col_sums(this->n());
   // For a row-major Eigen SparseMatrix like we're using, the
   // InnerIterator iterates over the non-zero entries of rows.
   for (unsigned row=0; row<this->m(); ++row)
     {
       EigenSM::InnerIterator it(_mat, row);
       for (; it; ++it)
         abs_col_sums[it.col()] += std::abs(it.value());
     }
   return *(std::max_element(abs_col_sums.begin(), abs_col_sums.end()));
 }
template<typename T > Real libMesh::EigenSparseMatrix< T >::linfty_norm () const virtual
Return the linfty-norm of the matrix, that is , (max. sum of rows). This is the natural matrix norm that is compatible to the linfty-norm of vectors, i.e. .
Implements libMesh::SparseMatrix< T >.
Definition at line 321 of file eigen_sparse_matrix.C.
References libMesh::EigenSparseMatrix< T >::_mat, std::abs(), libMesh::EigenSparseMatrix< T >::m(), std::max(), and libMesh::Real.
Referenced by libMesh::EigenSparseMatrix< T >::close().
 {
   Real max_abs_row_sum = 0.;
   // For a row-major Eigen SparseMatrix like we're using, the
   // InnerIterator iterates over the non-zero entries of rows.
   for (unsigned row=0; row<this->m(); ++row)
     {
       Real current_abs_row_sum = 0.;
       EigenSM::InnerIterator it(_mat, row);
       for (; it; ++it)
         current_abs_row_sum += std::abs(it.value());
       max_abs_row_sum = std::max(max_abs_row_sum, current_abs_row_sum);
     }
   return max_abs_row_sum;
 }
template<typename T > numeric_index_type libMesh::EigenSparseMatrix< T >::m () const virtual
Returns
m, the row-dimension of the matrix where the marix is .
Implements libMesh::SparseMatrix< T >.
Definition at line 197 of file eigen_sparse_matrix.C.
References libMesh::EigenSparseMatrix< T >::_mat, libMesh::SparseMatrix< T >::initialized(), and libMesh::libmesh_assert().
Referenced by libMesh::EigenSparseMatrix< T >::add(), libMesh::EigenSparseMatrix< T >::close(), libMesh::EigenSparseMatrix< T >::l1_norm(), libMesh::EigenSparseMatrix< T >::linfty_norm(), libMesh::EigenSparseMatrix< T >::operator()(), libMesh::EigenSparseMatrix< T >::row_stop(), and libMesh::EigenSparseMatrix< T >::set().
 {
   libmesh_assert (this->initialized());
   return _mat.rows();
 }
template<typename T > numeric_index_type libMesh::EigenSparseMatrix< T >::n () const virtual
Returns
n, the column-dimension of the matrix where the marix is .
Implements libMesh::SparseMatrix< T >.
Definition at line 207 of file eigen_sparse_matrix.C.
References libMesh::EigenSparseMatrix< T >::_mat, libMesh::SparseMatrix< T >::initialized(), and libMesh::libmesh_assert().
Referenced by libMesh::EigenSparseMatrix< T >::add(), libMesh::EigenSparseMatrix< T >::close(), libMesh::EigenSparseMatrix< T >::l1_norm(), libMesh::EigenSparseMatrix< T >::operator()(), and libMesh::EigenSparseMatrix< T >::set().
 {
   libmesh_assert (this->initialized());
   return _mat.cols();
 }
static unsigned int libMesh::ReferenceCounter::n_objects () inline static inherited
Prints the number of outstanding (created, but not yet destroyed) objects.
Definition at line 76 of file reference_counter.h.
References libMesh::ReferenceCounter::_n_objects, libMesh::ReferenceCounter::disable_print_counter_info(), libMesh::ReferenceCounter::enable_print_counter_info(), libMesh::ReferenceCounter::increment_constructor_count(), libMesh::ReferenceCounter::increment_destructor_count(), and libMesh::Quality::name().
Referenced by libMesh::System::hide_output(), and libMesh::LibMeshInit::LibMeshInit().
   { return _n_objects; }
processor_id_type libMesh::ParallelObject::n_processors () const inline inherited
Returns
the number of processors in the group.
Definition at line 93 of file parallel_object.h.
References libMesh::ParallelObject::_communicator, and libMesh::Parallel::Communicator::size().
Referenced by libMesh::ParmetisPartitioner::_do_repartition(), libMesh::BoundaryInfo::_find_id_maps(), libMesh::DistributedMesh::add_elem(), libMesh::DistributedMesh::add_node(), libMesh::LaplaceMeshSmoother::allgather_graph(), libMesh::FEMSystem::assembly(), libMesh::ParmetisPartitioner::assign_partitioning(), libMesh::AztecLinearSolver< T >::AztecLinearSolver(), libMesh::MeshCommunication::broadcast(), libMesh::BoundaryInfo::build_node_list_from_side_list(), libMesh::DistributedMesh::clear(), libMesh::Nemesis_IO_Helper::compute_border_node_ids(), libMesh::Nemesis_IO_Helper::construct_nemesis_filename(), libMesh::MeshTools::correct_node_proc_ids(), libMesh::UnstructuredMesh::create_pid_mesh(), libMesh::DofMap::distribute_dofs(), libMesh::DofMap::distribute_local_dofs_node_major(), libMesh::DofMap::distribute_local_dofs_var_major(), libMesh::DistributedMesh::DistributedMesh(), libMesh::EnsightIO::EnsightIO(), libMesh::MeshCommunication::gather(), libMesh::MeshCommunication::gather_neighboring_elements(), libMesh::MeshBase::get_info(), libMesh::EquationSystems::get_solution(), libMesh::DistributedVector< T >::init(), libMesh::SystemSubsetBySubdomain::init(), libMesh::ParmetisPartitioner::initialize(), libMesh::Nemesis_IO_Helper::initialize(), libMesh::DistributedMesh::insert_elem(), libMesh::MeshTools::libmesh_assert_parallel_consistent_procids< Elem >(), libMesh::MeshTools::libmesh_assert_parallel_consistent_procids< Node >(), libMesh::MeshTools::libmesh_assert_topology_consistent_procids< Node >(), libMesh::MeshTools::libmesh_assert_valid_boundary_ids(), libMesh::MeshTools::libmesh_assert_valid_dof_ids(), libMesh::MeshTools::libmesh_assert_valid_neighbors(), libMesh::MeshTools::libmesh_assert_valid_refinement_flags(), libMesh::DofMap::local_variable_indices(), libMesh::MeshBase::n_active_elem_on_proc(), libMesh::MeshBase::n_elem_on_proc(), libMesh::MeshBase::n_nodes_on_proc(), libMesh::SparsityPattern::Build::parallel_sync(), libMesh::Partitioner::partition(), libMesh::MeshBase::partition(), libMesh::Partitioner::partition_unpartitioned_elements(), libMesh::PetscLinearSolver< T >::PetscLinearSolver(), libMesh::System::point_gradient(), libMesh::System::point_hessian(), libMesh::System::point_value(), libMesh::SparseMatrix< T >::print(), libMesh::MeshTools::processor_bounding_box(), libMesh::NameBasedIO::read(), libMesh::Nemesis_IO::read(), libMesh::XdrIO::read(), libMesh::MeshCommunication::redistribute(), libMesh::DistributedMesh::renumber_dof_objects(), libMesh::Partitioner::repartition(), libMesh::MeshCommunication::send_coarse_ghosts(), libMesh::Partitioner::set_node_processor_ids(), libMesh::DofMap::set_nonlocal_dof_objects(), libMesh::Parallel::Sort< KeyType, IdxType >::sort(), libMesh::DistributedMesh::update_parallel_id_counts(), libMesh::GMVIO::write_binary(), libMesh::GMVIO::write_discontinuous_gmv(), libMesh::XdrIO::write_serialized_bcs_helper(), libMesh::XdrIO::write_serialized_connectivity(), libMesh::XdrIO::write_serialized_nodes(), and libMesh::XdrIO::write_serialized_nodesets().
   { return cast_int<processor_id_type>(_communicator.size()); }
template<typename T> virtual bool libMesh::SparseMatrix< T >::need_full_sparsity_pattern () const inline virtual inherited
returns true if this sparse matrix format needs to be fed the graph of the sparse matrix. This is true in the case of the LaspackMatrix, but not for the PetscMatrix. In the case where the full graph is not required we can efficiently approximate it to provide a good estimate of the required size of the sparse matrix.
Reimplemented in libMesh::EpetraMatrix< T >, and libMesh::LaspackMatrix< T >.
Definition at line 122 of file sparse_matrix.h.
Referenced by libMesh::DofMap::attach_matrix().
   { return false; }
template<typename T > T libMesh::EigenSparseMatrix< T >::operator() (const numeric_index_type i, const numeric_index_type j) const virtual
Return the value of the entry (i,j). This may be an expensive operation, and you should always be careful where you call this function.
Implements libMesh::SparseMatrix< T >.
Definition at line 285 of file eigen_sparse_matrix.C.
References libMesh::EigenSparseMatrix< T >::_mat, libMesh::SparseMatrix< T >::initialized(), libMesh::libmesh_assert(), libMesh::EigenSparseMatrix< T >::m(), and libMesh::EigenSparseMatrix< T >::n().
Referenced by libMesh::EigenSparseMatrix< T >::close().
 {
   libmesh_assert (this->initialized());
   libmesh_assert_less (i, this->m());
   libmesh_assert_less (j, this->n());
   return _mat.coeff(i,j);
 }
template<> void libMesh::SparseMatrix< Complex >::print (std::ostream & os, const bool sparse) const inherited
Definition at line 101 of file sparse_matrix.C.
References libMesh::SparseMatrix< T >::m(), and libMesh::SparseMatrix< T >::n().
 {
   // std::complex<>::operator<<() is defined, but use this form
   if(sparse)
     {
       libmesh_not_implemented();
     }
   os << "Real part:" << std::endl;
   for (numeric_index_type i=0; i<this->m(); i++)
     {
       for (numeric_index_type j=0; j<this->n(); j++)
         os << std::setw(8) << (*this)(i,j).real() << " ";
       os << std::endl;
     }
   os << std::endl << "Imaginary part:" << std::endl;
   for (numeric_index_type i=0; i<this->m(); i++)
     {
       for (numeric_index_type j=0; j<this->n(); j++)
         os << std::setw(8) << (*this)(i,j).imag() << " ";
       os << std::endl;
     }
 }
template<typename T > void libMesh::SparseMatrix< T >::print (std::ostream & os = libMesh::out, const bool sparse = false) const inherited
Print the contents of the matrix to the screen in a uniform style, regardless of matrix/solver package being used.
Definition at line 205 of file sparse_matrix.C.
References libMesh::SparseMatrix< T >::_dof_map, libMesh::ParallelObject::comm(), libMesh::DofMap::end_dof(), libMesh::DofMap::first_dof(), libMesh::SparseMatrix< T >::initialized(), libMesh::libmesh_assert(), libMesh::SparseMatrix< T >::m(), libMesh::SparseMatrix< T >::n(), libMesh::ParallelObject::n_processors(), libMesh::ParallelObject::processor_id(), libMesh::Parallel::Communicator::receive(), and libMesh::Parallel::Communicator::send().
Referenced by libMesh::EigenSparseMatrix< T >::print_personal(), and libMesh::LaspackMatrix< T >::print_personal().
 {
   parallel_object_only();
   libmesh_assert (this->initialized());
   if(!this->_dof_map)
     libmesh_error_msg("Error!  Trying to print a matrix with no dof_map set!");
   // We'll print the matrix from processor 0 to make sure
   // it's serialized properly
   if (this->processor_id() == 0)
     {
       libmesh_assert_equal_to (this->_dof_map->first_dof(), 0);
       for (numeric_index_type i=this->_dof_map->first_dof();
            i!=this->_dof_map->end_dof(); ++i)
         {
           if(sparse)
             {
               for (numeric_index_type j=0; j<this->n(); j++)
                 {
                   T c = (*this)(i,j);
                   if (c != static_cast<T>(0.0))
                     {
                       os << i << " " << j << " " << c << std::endl;
                     }
                 }
             }
           else
             {
               for (numeric_index_type j=0; j<this->n(); j++)
                 os << (*this)(i,j) << " ";
               os << std::endl;
             }
         }
       std::vector<numeric_index_type> ibuf, jbuf;
       std::vector<T> cbuf;
       numeric_index_type currenti = this->_dof_map->end_dof();
       for (processor_id_type p=1; p < this->n_processors(); ++p)
         {
           this->comm().receive(p, ibuf);
           this->comm().receive(p, jbuf);
           this->comm().receive(p, cbuf);
           libmesh_assert_equal_to (ibuf.size(), jbuf.size());
           libmesh_assert_equal_to (ibuf.size(), cbuf.size());
           if (ibuf.empty())
             continue;
           libmesh_assert_greater_equal (ibuf.front(), currenti);
           libmesh_assert_greater_equal (ibuf.back(), ibuf.front());
           std::size_t currentb = 0;
           for (;currenti <= ibuf.back(); ++currenti)
             {
               if(sparse)
                 {
                   for (numeric_index_type j=0; j<this->n(); j++)
                     {
                       if (currentb < ibuf.size() &&
                           ibuf[currentb] == currenti &&
                           jbuf[currentb] == j)
{
                           os << currenti << " " << j << " " << cbuf[currentb] << std::endl;
                           currentb++;
                         }
                     }
                 }
               else
                 {
                   for (numeric_index_type j=0; j<this->n(); j++)
                     {
                       if (currentb < ibuf.size() &&
                           ibuf[currentb] == currenti &&
                           jbuf[currentb] == j)
{
                           os << cbuf[currentb] << " ";
                           currentb++;
                         }
                       else
                         os << static_cast<T>(0.0) << " ";
                     }
                   os << std::endl;
                 }
             }
         }
       if(!sparse)
         {
           for (; currenti != this->m(); ++currenti)
             {
               for (numeric_index_type j=0; j<this->n(); j++)
                 os << static_cast<T>(0.0) << " ";
               os << std::endl;
             }
         }
     }
   else
     {
       std::vector<numeric_index_type> ibuf, jbuf;
       std::vector<T> cbuf;
       // We'll assume each processor has access to entire
       // matrix rows, so (*this)(i,j) is valid if i is a local index.
       for (numeric_index_type i=this->_dof_map->first_dof();
            i!=this->_dof_map->end_dof(); ++i)
         {
           for (numeric_index_type j=0; j<this->n(); j++)
             {
               T c = (*this)(i,j);
               if (c != static_cast<T>(0.0))
                 {
                   ibuf.push_back(i);
                   jbuf.push_back(j);
                   cbuf.push_back(c);
                 }
             }
         }
       this->comm().send(0,ibuf);
       this->comm().send(0,jbuf);
       this->comm().send(0,cbuf);
     }
 }
void libMesh::ReferenceCounter::print_info (std::ostream & out = libMesh::out) static inherited
Prints the reference information, by default to libMesh::out.
Definition at line 88 of file reference_counter.C.
References libMesh::ReferenceCounter::_enable_print_counter, and libMesh::ReferenceCounter::get_info().
Referenced by libMesh::LibMeshInit::LibMeshInit().
 {
   if( _enable_print_counter ) out_stream << ReferenceCounter::get_info();
 }
template<typename T> virtual void libMesh::SparseMatrix< T >::print_matlab (const std::string & = "") const inline virtual inherited
Print the contents of the matrix in Matlab's sparse matrix format. Optionally prints the matrix to the file named name. If name is not specified it is dumped to the screen.
Reimplemented in libMesh::PetscMatrix< T >.
Definition at line 358 of file sparse_matrix.h.
   {
     libmesh_not_implemented();
   }
template<typename T> virtual void libMesh::EigenSparseMatrix< T >::print_personal (std::ostream & os = libMesh::out) const inline virtual
Print the contents of the matrix, by default to libMesh::out. Currently identical to print().
Implements libMesh::SparseMatrix< T >.
Definition at line 248 of file eigen_sparse_matrix.h.
References libMesh::EigenSparseMatrix< T >::get_diagonal(), libMesh::EigenSparseMatrix< T >::get_transpose(), and libMesh::SparseMatrix< T >::print().
 { this->print(os); }
processor_id_type libMesh::ParallelObject::processor_id () const inline inherited
Returns
the rank of this processor in the group.
Definition at line 99 of file parallel_object.h.
References libMesh::ParallelObject::_communicator, and libMesh::Parallel::Communicator::rank().
Referenced by libMesh::BoundaryInfo::_find_id_maps(), libMesh::EquationSystems::_read_impl(), libMesh::DistributedMesh::add_elem(), libMesh::BoundaryInfo::add_elements(), libMesh::DofMap::add_neighbors_to_send_list(), libMesh::DistributedMesh::add_node(), libMesh::MeshRefinement::add_node(), libMesh::MeshTools::Modification::all_tri(), libMesh::FEMSystem::assembly(), libMesh::ParmetisPartitioner::assign_partitioning(), libMesh::MeshCommunication::broadcast(), libMesh::EquationSystems::build_discontinuous_solution_vector(), libMesh::Nemesis_IO_Helper::build_element_and_node_maps(), libMesh::ParmetisPartitioner::build_graph(), libMesh::InfElemBuilder::build_inf_elem(), libMesh::BoundaryInfo::build_node_list_from_side_list(), libMesh::DofMap::build_sparsity(), libMesh::DistributedMesh::clear(), libMesh::ExodusII_IO_Helper::close(), libMesh::Nemesis_IO_Helper::compute_border_node_ids(), libMesh::Nemesis_IO_Helper::compute_communication_map_parameters(), libMesh::Nemesis_IO_Helper::compute_internal_and_border_elems_and_internal_nodes(), libMesh::Nemesis_IO_Helper::compute_node_communication_maps(), libMesh::Nemesis_IO_Helper::compute_num_global_elem_blocks(), libMesh::Nemesis_IO_Helper::compute_num_global_nodesets(), libMesh::Nemesis_IO_Helper::compute_num_global_sidesets(), libMesh::Nemesis_IO_Helper::construct_nemesis_filename(), libMesh::MeshTools::correct_node_proc_ids(), libMesh::ExodusII_IO_Helper::create(), libMesh::DistributedMesh::delete_elem(), libMesh::DistributedMesh::delete_node(), libMesh::MeshCommunication::delete_remote_elements(), libMesh::DofMap::distribute_dofs(), libMesh::DofMap::distribute_local_dofs_node_major(), libMesh::DofMap::distribute_local_dofs_var_major(), libMesh::DistributedMesh::DistributedMesh(), libMesh::EnsightIO::EnsightIO(), libMesh::MeshFunction::find_element(), libMesh::MeshFunction::find_elements(), libMesh::UnstructuredMesh::find_neighbors(), libMesh::MeshCommunication::gather(), libMesh::MeshCommunication::gather_neighboring_elements(), libMesh::Nemesis_IO_Helper::get_cmap_params(), libMesh::Nemesis_IO_Helper::get_eb_info_global(), libMesh::Nemesis_IO_Helper::get_elem_cmap(), libMesh::Nemesis_IO_Helper::get_elem_map(), libMesh::MeshBase::get_info(), libMesh::DofMap::get_info(), libMesh::Nemesis_IO_Helper::get_init_global(), libMesh::Nemesis_IO_Helper::get_init_info(), libMesh::Nemesis_IO_Helper::get_loadbal_param(), libMesh::Nemesis_IO_Helper::get_node_cmap(), libMesh::Nemesis_IO_Helper::get_node_map(), libMesh::Nemesis_IO_Helper::get_ns_param_global(), libMesh::EquationSystems::get_solution(), libMesh::Nemesis_IO_Helper::get_ss_param_global(), libMesh::SparsityPattern::Build::handle_vi_vj(), libMesh::DistributedVector< T >::init(), libMesh::SystemSubsetBySubdomain::init(), libMesh::ParmetisPartitioner::initialize(), libMesh::ExodusII_IO_Helper::initialize(), libMesh::ExodusII_IO_Helper::initialize_element_variables(), libMesh::ExodusII_IO_Helper::initialize_global_variables(), libMesh::ExodusII_IO_Helper::initialize_nodal_variables(), libMesh::DistributedMesh::insert_elem(), libMesh::DofMap::is_evaluable(), libMesh::SparsityPattern::Build::join(), libMesh::MeshTools::libmesh_assert_parallel_consistent_procids< Elem >(), libMesh::MeshTools::libmesh_assert_parallel_consistent_procids< Node >(), libMesh::MeshTools::libmesh_assert_valid_neighbors(), libMesh::DistributedMesh::libmesh_assert_valid_parallel_object_ids(), libMesh::DofMap::local_variable_indices(), libMesh::MeshRefinement::make_coarsening_compatible(), libMesh::MeshBase::n_active_local_elem(), libMesh::BoundaryInfo::n_boundary_conds(), libMesh::BoundaryInfo::n_edge_conds(), libMesh::System::n_local_dofs(), libMesh::MeshBase::n_local_elem(), libMesh::MeshBase::n_local_nodes(), libMesh::BoundaryInfo::n_nodeset_conds(), libMesh::BoundaryInfo::n_shellface_conds(), libMesh::WeightedPatchRecoveryErrorEstimator::EstimateError::operator()(), libMesh::SparsityPattern::Build::operator()(), libMesh::PatchRecoveryErrorEstimator::EstimateError::operator()(), libMesh::SparsityPattern::Build::parallel_sync(), libMesh::MetisPartitioner::partition_range(), libMesh::System::point_gradient(), libMesh::System::point_hessian(), libMesh::System::point_value(), libMesh::SparseMatrix< T >::print(), libMesh::NumericVector< T >::print_global(), libMesh::Nemesis_IO_Helper::put_cmap_params(), libMesh::Nemesis_IO_Helper::put_elem_cmap(), libMesh::Nemesis_IO_Helper::put_elem_map(), libMesh::Nemesis_IO_Helper::put_loadbal_param(), libMesh::Nemesis_IO_Helper::put_node_cmap(), libMesh::Nemesis_IO_Helper::put_node_map(), libMesh::NameBasedIO::read(), libMesh::Nemesis_IO::read(), libMesh::XdrIO::read(), libMesh::ExodusII_IO_Helper::read_elem_num_map(), libMesh::ExodusII_IO_Helper::read_node_num_map(), libMesh::XdrIO::read_serialized_bc_names(), libMesh::XdrIO::read_serialized_bcs_helper(), libMesh::XdrIO::read_serialized_connectivity(), libMesh::XdrIO::read_serialized_nodes(), libMesh::XdrIO::read_serialized_nodesets(), libMesh::XdrIO::read_serialized_subdomain_names(), libMesh::MeshCommunication::redistribute(), libMesh::DistributedMesh::renumber_dof_objects(), libMesh::MeshCommunication::send_coarse_ghosts(), libMesh::Partitioner::set_node_processor_ids(), libMesh::DofMap::set_nonlocal_dof_objects(), libMesh::LaplaceMeshSmoother::smooth(), libMesh::MeshTools::total_weight(), libMesh::Parallel::Packing< Node * >::unpack(), libMesh::Parallel::Packing< Elem * >::unpack(), libMesh::DistributedMesh::update_parallel_id_counts(), libMesh::MeshTools::weight(), libMesh::NameBasedIO::write(), libMesh::XdrIO::write(), libMesh::EquationSystems::write(), libMesh::GMVIO::write_discontinuous_gmv(), libMesh::ExodusII_IO::write_element_data(), libMesh::ExodusII_IO_Helper::write_element_values(), libMesh::ExodusII_IO_Helper::write_elements(), libMesh::ExodusII_IO::write_global_data(), libMesh::ExodusII_IO_Helper::write_global_values(), libMesh::ExodusII_IO::write_information_records(), libMesh::ExodusII_IO_Helper::write_information_records(), libMesh::ExodusII_IO_Helper::write_nodal_coordinates(), libMesh::UCDIO::write_nodal_data(), libMesh::ExodusII_IO::write_nodal_data(), libMesh::ExodusII_IO::write_nodal_data_discontinuous(), libMesh::ExodusII_IO_Helper::write_nodal_values(), libMesh::Nemesis_IO_Helper::write_nodesets(), libMesh::ExodusII_IO_Helper::write_nodesets(), libMesh::XdrIO::write_serialized_bc_names(), libMesh::XdrIO::write_serialized_bcs_helper(), libMesh::XdrIO::write_serialized_connectivity(), libMesh::XdrIO::write_serialized_nodes(), libMesh::XdrIO::write_serialized_nodesets(), libMesh::XdrIO::write_serialized_subdomain_names(), libMesh::Nemesis_IO_Helper::write_sidesets(), libMesh::ExodusII_IO_Helper::write_sidesets(), libMesh::ExodusII_IO::write_timestep(), and libMesh::ExodusII_IO_Helper::write_timestep().
   { return cast_int<processor_id_type>(_communicator.rank()); }
template<typename T> virtual void libMesh::SparseMatrix< T >::reinit_submatrix (SparseMatrix< T > & submatrix, const std::vector< numeric_index_type > & rows, const std::vector< numeric_index_type > & cols) const inline virtual inherited
This function is similar to the one above, but it allows you to reuse the existing sparsity pattern of "submatrix" instead of reallocating it again. This should hopefully be more efficient if you are frequently extracting submatrices of the same size.
Definition at line 384 of file sparse_matrix.h.
   {
     this->_get_submatrix(submatrix,
                          rows,
                          cols,
                          true); // true means REUSE submatrix
   }
template<typename T > numeric_index_type libMesh::EigenSparseMatrix< T >::row_start () const virtual
return row_start, the index of the first matrix row stored on this processor
Implements libMesh::SparseMatrix< T >.
Definition at line 217 of file eigen_sparse_matrix.C.
Referenced by libMesh::EigenSparseMatrix< T >::close().
 {
   return 0;
 }
template<typename T > numeric_index_type libMesh::EigenSparseMatrix< T >::row_stop () const virtual
return row_stop, the index of the last matrix row (+1) stored on this processor
Implements libMesh::SparseMatrix< T >.
Definition at line 225 of file eigen_sparse_matrix.C.
References libMesh::EigenSparseMatrix< T >::m().
Referenced by libMesh::EigenSparseMatrix< T >::close().
 {
   return this->m();
 }
template<typename T > void libMesh::EigenSparseMatrix< T >::set (const numeric_index_type i, const numeric_index_type j, const T value) virtual
Set the element (i,j) to value. Throws an error if the entry does not exist. Still, it is allowed to store zero values in non-existent fields.
Implements libMesh::SparseMatrix< T >.
Definition at line 233 of file eigen_sparse_matrix.C.
References libMesh::EigenSparseMatrix< T >::_mat, libMesh::SparseMatrix< T >::initialized(), libMesh::libmesh_assert(), libMesh::EigenSparseMatrix< T >::m(), and libMesh::EigenSparseMatrix< T >::n().
 {
   libmesh_assert (this->initialized());
   libmesh_assert_less (i, this->m());
   libmesh_assert_less (j, this->n());
   _mat.coeffRef(i,j) = value;
 }
template<typename T> virtual void libMesh::SparseMatrix< T >::update_sparsity_pattern (const SparsityPattern::Graph &) inline virtual inherited
Updates the matrix sparsity pattern. When your SparseMatrix<T> implementation does not need this data simply do not overload this method.
Reimplemented in libMesh::EpetraMatrix< T >, and libMesh::LaspackMatrix< T >.
Definition at line 130 of file sparse_matrix.h.
Referenced by libMesh::DofMap::attach_matrix().
 {}
template<typename T> void libMesh::SparseMatrix< T >::vector_mult (NumericVector< T > & dest, const NumericVector< T > & arg) const inherited
Multiplies the matrix with arg and stores the result in dest.
Definition at line 175 of file sparse_matrix.C.
References libMesh::SparseMatrix< T >::vector_mult_add(), and libMesh::NumericVector< T >::zero().
Referenced by libMesh::ImplicitSystem::qoi_parameter_hessian(), and libMesh::ImplicitSystem::qoi_parameter_hessian_vector_product().
 {
   dest.zero();
   this->vector_mult_add(dest,arg);
 }
template<typename T> void libMesh::SparseMatrix< T >::vector_mult_add (NumericVector< T > & dest, const NumericVector< T > & arg) const inherited
Multiplies the matrix with arg and adds the result to dest.
Definition at line 185 of file sparse_matrix.C.
References libMesh::NumericVector< T >::add_vector().
Referenced by libMesh::SparseMatrix< T >::vector_mult(), and libMesh::ImplicitSystem::weighted_sensitivity_adjoint_solve().
 {
   /* This functionality is actually implemented in the \p
      NumericVector class.  */
   dest.add_vector(arg,*this);
 }
template<typename T > void libMesh::EigenSparseMatrix< T >::zero () virtual
Set all entries to 0.
Implements libMesh::SparseMatrix< T >.
Definition at line 189 of file eigen_sparse_matrix.C.
References libMesh::EigenSparseMatrix< T >::_mat.
 {
   _mat.setZero();
 }
template<typename T> void libMesh::SparseMatrix< T >::zero_rows (std::vector< numeric_index_type > & rows, T diag_value = 0.0) virtual inherited
Set all row entries to 0 then puts diag_value in the diagonal entry
Reimplemented in libMesh::PetscMatrix< T >.
Definition at line 196 of file sparse_matrix.C.
 {
   /* This functionality isn't implemented or stubbed in every subclass yet */
   libmesh_not_implemented();
 }
Friends And Related Function Documentation
template<typename T> friend class EigenSparseLinearSolver< T > friend
Definition at line 277 of file eigen_sparse_matrix.h.
template<typename T> friend class EigenSparseVector< T > friend
Make other Eigen datatypes friends
Definition at line 276 of file eigen_sparse_matrix.h.
Member Data Documentation
template<typename T> bool libMesh::EigenSparseMatrix< T >::_closed private
Flag indicating if the matrix has been closed yet.
Definition at line 271 of file eigen_sparse_matrix.h.
Referenced by libMesh::EigenSparseMatrix< T >::clear(), libMesh::EigenSparseMatrix< T >::close(), and libMesh::EigenSparseMatrix< T >::closed().
const Parallel::Communicator& libMesh::ParallelObject::_communicator protected inherited
Definition at line 105 of file parallel_object.h.
Referenced by libMesh::EquationSystems::build_parallel_solution_vector(), libMesh::ParallelObject::comm(), libMesh::EquationSystems::get_solution(), libMesh::ParallelObject::n_processors(), libMesh::ParallelObject::operator=(), and libMesh::ParallelObject::processor_id().
ReferenceCounter::Counts libMesh::ReferenceCounter::_counts static protected inherited
Actually holds the data.
Definition at line 115 of file reference_counter.h.
Referenced by libMesh::ReferenceCounter::get_info(), libMesh::ReferenceCounter::increment_constructor_count(), and libMesh::ReferenceCounter::increment_destructor_count().
template<typename T> DofMap const* libMesh::SparseMatrix< T >::_dof_map protected inherited
The DofMap object associated with this object.
Definition at line 436 of file sparse_matrix.h.
Referenced by libMesh::SparseMatrix< T >::print().
bool libMesh::ReferenceCounter::_enable_print_counter = true static protected inherited
Flag to control whether reference count information is printed when print_info is called.
Definition at line 134 of file reference_counter.h.
Referenced by libMesh::ReferenceCounter::disable_print_counter_info(), libMesh::ReferenceCounter::enable_print_counter_info(), and libMesh::ReferenceCounter::print_info().
template<typename T> bool libMesh::SparseMatrix< T >::_is_initialized protected inherited
Flag indicating whether or not the matrix has been initialized.
Definition at line 442 of file sparse_matrix.h.
Referenced by libMesh::PetscMatrix< T >::_get_submatrix(), libMesh::EigenSparseMatrix< T >::clear(), libMesh::LaspackMatrix< T >::clear(), and libMesh::PetscMatrix< T >::get_transpose().
template<typename T> DataType libMesh::EigenSparseMatrix< T >::_mat private
Actual Eigen::SparseMatrix<> we are wrapping.
Definition at line 266 of file eigen_sparse_matrix.h.
Referenced by libMesh::EigenSparseMatrix< T >::add(), libMesh::EigenSparseMatrix< T >::clear(), libMesh::EigenSparseMatrix< T >::get_transpose(), libMesh::EigenSparseMatrix< T >::l1_norm(), libMesh::EigenSparseMatrix< T >::linfty_norm(), libMesh::EigenSparseMatrix< T >::m(), libMesh::EigenSparseMatrix< T >::n(), libMesh::EigenSparseMatrix< T >::operator()(), libMesh::EigenSparseMatrix< T >::set(), libMesh::EigenSparseLinearSolver< T >::solve(), and libMesh::EigenSparseMatrix< T >::zero().
Threads::spin_mutex libMesh::ReferenceCounter::_mutex static protected inherited
Mutual exclusion object to enable thread-safe reference counting.
Definition at line 128 of file reference_counter.h.
Threads::atomic< unsigned int > libMesh::ReferenceCounter::_n_objects static protected inherited
The number of objects. Print the reference count information when the number returns to 0.
Definition at line 123 of file reference_counter.h.
Referenced by libMesh::ReferenceCounter::n_objects(), libMesh::ReferenceCounter::ReferenceCounter(), and libMesh::ReferenceCounter::~ReferenceCounter().
The documentation for this class was generated from the following files:
eigen_sparse_matrix.h
eigen_sparse_matrix.C