libMesh: libMesh::RBEIMEvaluation Class Reference
SomeWebsiteLogo
libMesh::RBEIMEvaluation Class Reference
#include <rb_eim_evaluation.h>
Public Types
typedef RBEvaluation Parent
Public Member Functions
RBEIMEvaluation (const libMesh::Parallel::Communicator &comm_in LIBMESH_CAN_DEFAULT_TO_COMMWORLD)
virtual ~RBEIMEvaluation ()
virtual void clear () libmesh_override
virtual void resize_data_structures (const unsigned int Nmax, bool resize_error_bound_data=true) libmesh_override
void attach_parametrized_function (RBParametrizedFunction *pf)
unsigned int get_n_parametrized_functions () const
ReplicatedMesh & get_interpolation_points_mesh ()
Number evaluate_parametrized_function (unsigned int var_index, const Point &p, const Elem &elem)
virtual Real rb_solve (unsigned int N) libmesh_override
void rb_solve (DenseVector< Number > &EIM_rhs)
virtual Real get_error_bound_normalization () libmesh_override
void initialize_eim_theta_objects ()
std::vector< RBTheta * > get_eim_theta_objects ()
virtual UniquePtr< RBTheta > build_eim_theta (unsigned int index)
virtual void legacy_write_offline_data_to_files (const std::string &directory_name="offline_data", const bool write_binary_data=true) libmesh_override
virtual void legacy_read_offline_data_from_files (const std::string &directory_name="offline_data", bool read_error_bound_data=true, const bool read_binary_data=true) libmesh_override
void set_rb_theta_expansion (RBThetaExpansion &rb_theta_expansion_in)
RBThetaExpansion & get_rb_theta_expansion ()
bool is_rb_theta_expansion_initialized () const
NumericVector< Number > & get_basis_function (unsigned int i)
virtual Real compute_residual_dual_norm (const unsigned int N)
virtual Real residual_scaling_denom (Real alpha_LB)
Real eval_output_dual_norm (unsigned int n, const RBParameters &mu)
virtual Real get_stability_lower_bound ()
virtual unsigned int get_n_basis_functions () const
virtual void set_n_basis_functions (unsigned int n_bfs)
virtual void clear_riesz_representors ()
virtual void write_out_basis_functions (System &sys, const std::string &directory_name="offline_data", const bool write_binary_basis_functions=true)
virtual void write_out_vectors (System &sys, std::vector< NumericVector< Number > * > &vectors, const std::string &directory_name="offline_data", const std::string &data_name="bf", const bool write_binary_basis_functions=true)
virtual void read_in_basis_functions (System &sys, const std::string &directory_name="offline_data", const bool read_binary_basis_functions=true)
void read_in_vectors (System &sys, std::vector< NumericVector< Number > * > &vectors, const std::string &directory_name, const std::string &data_name, const bool read_binary_vectors)
void read_in_vectors_from_multiple_files (System &sys, std::vector< std::vector< NumericVector< Number > * > * > multiple_vectors, const std::vector< std::string > &multiple_directory_names, const std::vector< std::string > &multiple_data_names, const bool read_binary_vectors)
void initialize_parameters (const RBParameters &mu_min_in, const RBParameters &mu_max_in, const std::map< std::string, std::vector< Real > > &discrete_parameter_values)
void initialize_parameters (const RBParametrized &rb_parametrized)
unsigned int get_n_params () const
unsigned int get_n_continuous_params () const
unsigned int get_n_discrete_params () const
std::set< std::string > get_parameter_names () const
const RBParameters & get_parameters () const
void set_parameters (const RBParameters &params)
const RBParameters & get_parameters_min () const
const RBParameters & get_parameters_max () const
Real get_parameter_min (const std::string &param_name) const
Real get_parameter_max (const std::string &param_name) const
void print_parameters () const
void write_parameter_data_to_files (const std::string &continuous_param_file_name, const std::string &discrete_param_file_name, const bool write_binary_data)
void read_parameter_data_from_files (const std::string &continuous_param_file_name, const std::string &discrete_param_file_name, const bool read_binary_data)
bool is_discrete_parameter (const std::string &mu_name) const
const std::map< std::string, std::vector< Real > > & get_discrete_parameter_values () const
void print_discrete_parameter_values () const
const Parallel::Communicator & comm () const
processor_id_type n_processors () const
processor_id_type processor_id () const
Static Public Member Functions
static Real get_closest_value (Real value, const std::vector< Real > &list_of_values)
static std::string get_info ()
static void print_info (std::ostream &out=libMesh::out)
static unsigned int n_objects ()
static void enable_print_counter_info ()
static void disable_print_counter_info ()
Public Attributes
DenseMatrix< Number > interpolation_matrix
std::vector< Point > interpolation_points
std::vector< unsigned int > interpolation_points_var
std::vector< Elem * > interpolation_points_elem
std::vector< NumericVector< Number > * > basis_functions
std::vector< RBParameters > greedy_param_list
DenseMatrix< Number > RB_inner_product_matrix
std::vector< DenseMatrix< Number > > RB_Aq_vector
std::vector< DenseVector< Number > > RB_Fq_vector
DenseVector< Number > RB_solution
std::vector< std::vector< DenseVector< Number > > > RB_output_vectors
std::vector< Number > RB_outputs
std::vector< Real > RB_output_error_bounds
std::vector< Number > Fq_representor_innerprods
std::vector< std::vector< std::vector< Number > > > Fq_Aq_representor_innerprods
std::vector< std::vector< std::vector< Number > > > Aq_Aq_representor_innerprods
std::vector< std::vector< Number > > output_dual_innerprods
std::vector< std::vector< NumericVector< Number > * > > Aq_representor
bool evaluate_RB_error_bound
bool compute_RB_inner_product
bool verbose_mode
Protected Types
typedef std::map< std::string, std::pair< unsigned int, unsigned int > > Counts
Protected Member Functions
void assert_file_exists (const std::string &file_name)
void increment_constructor_count (const std::string &name)
void increment_destructor_count (const std::string &name)
Protected Attributes
const Parallel::Communicator & _communicator
Static Protected Attributes
static Counts _counts
static Threads::atomic< unsigned int > _n_objects
static Threads::spin_mutex _mutex
static bool _enable_print_counter = true
Private Member Functions
void legacy_write_out_interpolation_points_elem (const std::string &directory_name)
void legacy_read_in_interpolation_points_elem (const std::string &directory_name)
Private Attributes
std::vector< RBParametrizedFunction * > _parametrized_functions
std::vector< RBTheta * > _rb_eim_theta_objects
RBThetaExpansion _empty_rb_theta_expansion
RBParameters _previous_parameters
unsigned int _previous_N
Real _previous_error_bound
ReplicatedMesh _interpolation_points_mesh
Detailed Description
This class is part of the rbOOmit framework.
RBEIMEvaluation extends RBEvaluation to encapsulate the code and data required to perform "online" evaluations for EIM approximations.
Author
David J. Knezevic
Date
2011
Definition at line 51 of file rb_eim_evaluation.h.
Member Typedef Documentation
typedef std::map<std::string, std::pair<unsigned int, unsigned int> > libMesh::ReferenceCounter::Counts protected inherited
Data structure to log the information. The log is identified by the class name.
Definition at line 119 of file reference_counter.h.
typedef RBEvaluation libMesh::RBEIMEvaluation::Parent
The type of the parent.
Definition at line 69 of file rb_eim_evaluation.h.
Constructor & Destructor Documentation
libMesh::RBEIMEvaluation::RBEIMEvaluation (const libMesh::Parallel::Communicator &comm_in LIBMESH_CAN_DEFAULT_TO_COMMWORLD)
Constructor.
virtual libMesh::RBEIMEvaluation::~RBEIMEvaluation () virtual
Destructor.
Member Function Documentation
void libMesh::RBEvaluation::assert_file_exists (const std::string & file_name) protected inherited
Helper function that checks if file_name exists.
void libMesh::RBEIMEvaluation::attach_parametrized_function (RBParametrizedFunction * pf)
Attach the parametrized function that we will approximate using the Empirical Interpolation Method.
virtual UniquePtr<RBTheta> libMesh::RBEIMEvaluation::build_eim_theta (unsigned int index) virtual
Build a theta object corresponding to EIM index index. The default implementation builds an RBEIMTheta object, possibly override in subclasses if we need more specialized behavior.
virtual void libMesh::RBEIMEvaluation::clear () virtual
Clear this object.
Reimplemented from libMesh::RBEvaluation.
virtual void libMesh::RBEvaluation::clear_riesz_representors () virtual inherited
Clear all the Riesz representors that are used to compute the RB residual (and hence error bound). This is useful since once we complete the Greedy we may not need the representors any more.
Reimplemented in libMesh::TransientRBEvaluation.
Referenced by libMesh::RBEvaluation::set_n_basis_functions().
const Parallel::Communicator& libMesh::ParallelObject::comm () const inline inherited
Returns
A reference to the Parallel::Communicator object used by this mesh.
Definition at line 87 of file parallel_object.h.
References libMesh::ParallelObject::_communicator.
Referenced by libMesh::__libmesh_petsc_diff_solver_monitor(), libMesh::__libmesh_petsc_diff_solver_residual(), libMesh::__libmesh_petsc_snes_jacobian(), libMesh::__libmesh_petsc_snes_postcheck(), libMesh::__libmesh_petsc_snes_residual(), libMesh::__libmesh_tao_equality_constraints(), libMesh::__libmesh_tao_equality_constraints_jacobian(), libMesh::__libmesh_tao_gradient(), libMesh::__libmesh_tao_hessian(), libMesh::__libmesh_tao_inequality_constraints(), libMesh::__libmesh_tao_inequality_constraints_jacobian(), libMesh::__libmesh_tao_objective(), libMesh::MeshRefinement::_coarsen_elements(), libMesh::ExactSolution::_compute_error(), libMesh::ParmetisPartitioner::_do_repartition(), libMesh::UniformRefinementEstimator::_estimate_error(), libMesh::BoundaryInfo::_find_id_maps(), libMesh::PetscLinearSolver< T >::_petsc_shell_matrix_get_diagonal(), libMesh::SlepcEigenSolver< T >::_petsc_shell_matrix_get_diagonal(), libMesh::PetscLinearSolver< T >::_petsc_shell_matrix_mult(), libMesh::SlepcEigenSolver< T >::_petsc_shell_matrix_mult(), libMesh::PetscLinearSolver< T >::_petsc_shell_matrix_mult_add(), libMesh::EquationSystems::_read_impl(), libMesh::MeshRefinement::_refine_elements(), libMesh::MeshRefinement::_smooth_flags(), libMesh::ImplicitSystem::add_matrix(), libMesh::System::add_vector(), libMesh::EigenSparseLinearSolver< T >::adjoint_solve(), libMesh::UnstructuredMesh::all_second_order(), libMesh::MeshTools::Modification::all_tri(), libMesh::LaplaceMeshSmoother::allgather_graph(), libMesh::FEMSystem::assemble_qoi(), libMesh::MeshCommunication::assign_global_indices(), libMesh::ParmetisPartitioner::assign_partitioning(), libMesh::DofMap::attach_matrix(), libMesh::Parallel::BinSorter< KeyType, IdxType >::binsort(), libMesh::Parallel::Sort< KeyType, IdxType >::binsort(), libMesh::MeshCommunication::broadcast(), libMesh::SparseMatrix< T >::build(), libMesh::MeshTools::Generation::build_extrusion(), libMesh::Parallel::Histogram< KeyType, IdxType >::build_histogram(), libMesh::PetscNonlinearSolver< T >::build_mat_null_space(), libMesh::BoundaryInfo::build_node_list_from_side_list(), libMesh::EquationSystems::build_parallel_solution_vector(), libMesh::MeshBase::cache_elem_dims(), libMesh::System::calculate_norm(), libMesh::DofMap::check_dirichlet_bcid_consistency(), libMesh::DistributedVector< T >::clone(), libMesh::EigenSparseVector< T >::clone(), libMesh::LaspackVector< T >::clone(), libMesh::EpetraVector< T >::clone(), libMesh::PetscVector< T >::clone(), libMesh::EpetraVector< T >::close(), libMesh::Parallel::Sort< KeyType, IdxType >::communicate_bins(), libMesh::Nemesis_IO_Helper::compute_num_global_elem_blocks(), libMesh::Nemesis_IO_Helper::compute_num_global_nodesets(), libMesh::Nemesis_IO_Helper::compute_num_global_sidesets(), libMesh::Problem_Interface::computeF(), libMesh::Problem_Interface::computeJacobian(), libMesh::Problem_Interface::computePreconditioner(), libMesh::MeshTools::correct_node_proc_ids(), libMesh::MeshTools::create_bounding_box(), libMesh::MeshTools::create_nodal_bounding_box(), libMesh::MeshRefinement::create_parent_error_vector(), libMesh::MeshTools::create_processor_bounding_box(), libMesh::MeshTools::create_subdomain_bounding_box(), libMesh::MeshCommunication::delete_remote_elements(), libMesh::DofMap::distribute_dofs(), DMlibMeshFunction(), DMlibMeshJacobian(), DMlibMeshSetSystem_libMesh(), DMVariableBounds_libMesh(), libMesh::MeshRefinement::eliminate_unrefined_patches(), libMesh::EpetraVector< T >::EpetraVector(), libMesh::WeightedPatchRecoveryErrorEstimator::estimate_error(), libMesh::PatchRecoveryErrorEstimator::estimate_error(), libMesh::JumpErrorEstimator::estimate_error(), libMesh::AdjointRefinementEstimator::estimate_error(), libMesh::ExactErrorEstimator::estimate_error(), libMesh::MeshRefinement::flag_elements_by_elem_fraction(), libMesh::MeshRefinement::flag_elements_by_error_fraction(), libMesh::MeshRefinement::flag_elements_by_nelem_target(), libMesh::MeshCommunication::gather(), libMesh::MeshCommunication::gather_neighboring_elements(), libMesh::CondensedEigenSystem::get_eigenpair(), libMesh::DofMap::get_info(), libMesh::ImplicitSystem::get_linear_solver(), libMesh::EquationSystems::get_solution(), libMesh::LocationMap< T >::init(), libMesh::PetscDiffSolver::init(), libMesh::TimeSolver::init(), libMesh::TopologyMap::init(), libMesh::TaoOptimizationSolver< T >::init(), libMesh::PetscNonlinearSolver< T >::init(), libMesh::DistributedVector< T >::init(), libMesh::EpetraVector< T >::init(), libMesh::PetscVector< T >::init(), libMesh::SystemSubsetBySubdomain::init(), libMesh::EigenSystem::init_data(), libMesh::EigenSystem::init_matrices(), libMesh::ParmetisPartitioner::initialize(), libMesh::OptimizationSystem::initialize_equality_constraints_storage(), libMesh::OptimizationSystem::initialize_inequality_constraints_storage(), libMesh::MeshTools::libmesh_assert_parallel_consistent_procids< Elem >(), libMesh::MeshTools::libmesh_assert_parallel_consistent_procids< Node >(), libMesh::MeshTools::libmesh_assert_topology_consistent_procids< Node >(), libMesh::MeshTools::libmesh_assert_valid_boundary_ids(), libMesh::MeshTools::libmesh_assert_valid_dof_ids(), libMesh::MeshTools::libmesh_assert_valid_neighbors(), libMesh::DistributedMesh::libmesh_assert_valid_parallel_flags(), libMesh::DistributedMesh::libmesh_assert_valid_parallel_object_ids(), libMesh::DistributedMesh::libmesh_assert_valid_parallel_p_levels(), libMesh::MeshTools::libmesh_assert_valid_refinement_flags(), libMesh::MeshTools::libmesh_assert_valid_unique_ids(), libMesh::MeshRefinement::limit_level_mismatch_at_edge(), libMesh::MeshRefinement::limit_level_mismatch_at_node(), libMesh::MeshRefinement::limit_overrefined_boundary(), libMesh::MeshRefinement::limit_underrefined_boundary(), libMesh::MeshRefinement::make_coarsening_compatible(), libMesh::MeshCommunication::make_elems_parallel_consistent(), libMesh::MeshRefinement::make_flags_parallel_consistent(), libMesh::MeshCommunication::make_new_node_proc_ids_parallel_consistent(), libMesh::MeshCommunication::make_new_nodes_parallel_consistent(), libMesh::MeshCommunication::make_node_ids_parallel_consistent(), libMesh::MeshCommunication::make_node_proc_ids_parallel_consistent(), libMesh::MeshCommunication::make_node_unique_ids_parallel_consistent(), libMesh::MeshCommunication::make_nodes_parallel_consistent(), libMesh::MeshCommunication::make_p_levels_parallel_consistent(), libMesh::MeshRefinement::make_refinement_compatible(), libMesh::DistributedVector< T >::max(), libMesh::FEMSystem::mesh_position_set(), libMesh::MeshSerializer::MeshSerializer(), libMesh::DistributedVector< T >::min(), libMesh::DistributedMesh::n_active_elem(), libMesh::MeshTools::n_active_levels(), libMesh::BoundaryInfo::n_boundary_conds(), libMesh::BoundaryInfo::n_edge_conds(), libMesh::CondensedEigenSystem::n_global_non_condensed_dofs(), libMesh::MeshTools::n_levels(), libMesh::BoundaryInfo::n_nodeset_conds(), libMesh::MeshTools::n_p_levels(), libMesh::BoundaryInfo::n_shellface_conds(), libMesh::DistributedMesh::parallel_max_elem_id(), libMesh::DistributedMesh::parallel_max_node_id(), libMesh::ReplicatedMesh::parallel_max_unique_id(), libMesh::DistributedMesh::parallel_max_unique_id(), libMesh::DistributedMesh::parallel_n_elem(), libMesh::DistributedMesh::parallel_n_nodes(), libMesh::SparsityPattern::Build::parallel_sync(), libMesh::MeshTools::paranoid_n_levels(), libMesh::Partitioner::partition(), libMesh::MetisPartitioner::partition_range(), libMesh::Partitioner::partition_unpartitioned_elements(), libMesh::petsc_auto_fieldsplit(), libMesh::System::point_gradient(), libMesh::System::point_hessian(), libMesh::System::point_value(), libMesh::MeshBase::prepare_for_use(), libMesh::SparseMatrix< T >::print(), libMesh::Nemesis_IO::read(), libMesh::CheckpointIO::read(), libMesh::XdrIO::read(), libMesh::CheckpointIO::read_header(), libMesh::XdrIO::read_serialized_bc_names(), libMesh::XdrIO::read_serialized_bcs_helper(), libMesh::XdrIO::read_serialized_connectivity(), libMesh::XdrIO::read_serialized_nodes(), libMesh::XdrIO::read_serialized_nodesets(), libMesh::XdrIO::read_serialized_subdomain_names(), libMesh::MeshBase::recalculate_n_partitions(), libMesh::MeshCommunication::redistribute(), libMesh::DistributedMesh::renumber_dof_objects(), libMesh::MeshCommunication::send_coarse_ghosts(), libMesh::Partitioner::set_node_processor_ids(), libMesh::DofMap::set_nonlocal_dof_objects(), libMesh::Partitioner::set_parent_processor_ids(), libMesh::LaplaceMeshSmoother::smooth(), libMesh::Parallel::Sort< KeyType, IdxType >::sort(), libMesh::MeshBase::subdomain_ids(), libMesh::BoundaryInfo::sync(), libMesh::Parallel::sync_element_data_by_parent_id(), libMesh::Parallel::sync_node_data_by_element_id(), libMesh::MeshRefinement::test_level_one(), libMesh::MeshRefinement::test_unflagged(), libMesh::MeshTools::total_weight(), libMesh::MeshRefinement::uniformly_coarsen(), libMesh::NameBasedIO::write(), libMesh::XdrIO::write(), libMesh::XdrIO::write_serialized_bcs_helper(), libMesh::XdrIO::write_serialized_connectivity(), libMesh::XdrIO::write_serialized_nodes(), libMesh::XdrIO::write_serialized_nodesets(), libMesh::DistributedVector< T >::zero_clone(), libMesh::EigenSparseVector< T >::zero_clone(), libMesh::LaspackVector< T >::zero_clone(), libMesh::EpetraVector< T >::zero_clone(), and libMesh::PetscVector< T >::zero_clone().
   { return _communicator; }
virtual Real libMesh::RBEvaluation::compute_residual_dual_norm (const unsigned int N) virtual inherited
Compute the dual norm of the residual for the solution saved in RB_solution_vector.
Reimplemented in libMesh::TransientRBEvaluation.
void libMesh::ReferenceCounter::disable_print_counter_info () static inherited
Definition at line 107 of file reference_counter.C.
References libMesh::ReferenceCounter::_enable_print_counter.
Referenced by libMesh::LibMeshInit::LibMeshInit(), and libMesh::ReferenceCounter::n_objects().
 {
   _enable_print_counter = false;
   return;
 }
void libMesh::ReferenceCounter::enable_print_counter_info () static inherited
Methods to enable/disable the reference counter output from print_info()
Definition at line 101 of file reference_counter.C.
References libMesh::ReferenceCounter::_enable_print_counter.
Referenced by libMesh::ReferenceCounter::n_objects().
 {
   _enable_print_counter = true;
   return;
 }
Real libMesh::RBEvaluation::eval_output_dual_norm (unsigned int n, const RBParameters & mu) inherited
Evaluate the dual norm of output n for the current parameters.
Number libMesh::RBEIMEvaluation::evaluate_parametrized_function (unsigned int var_index, const Point & p, const Elem & elem)
Returns
The value of the parametrized function that is being approximated at the point p. var_index specifies the variable (i.e. the parametrized function index) to be evaluated. elem specifies the element of the mesh that contains p.
NumericVector<Number>& libMesh::RBEvaluation::get_basis_function (unsigned int i) inherited
Get a reference to the i^th basis function.
static Real libMesh::RBParametrized::get_closest_value (Real value, const std::vector< Real > & list_of_values) static inherited
Returns
The closest entry to value from list_of_values.
const std::map< std::string, std::vector<Real> >& libMesh::RBParametrized::get_discrete_parameter_values () const inherited
Get a const reference to the discrete parameter values.
std::vector<RBTheta *> libMesh::RBEIMEvaluation::get_eim_theta_objects ()
Returns
The vector of theta objects that point to this RBEIMEvaluation.
virtual Real libMesh::RBEIMEvaluation::get_error_bound_normalization () virtual
Returns
A scaling factor that we can use to provide a consistent scaling of the RB error bound across different parameter values.
Reimplemented from libMesh::RBEvaluation.
std::string libMesh::ReferenceCounter::get_info () static inherited
Gets a string containing the reference information.
Definition at line 47 of file reference_counter.C.
References libMesh::ReferenceCounter::_counts, and libMesh::Quality::name().
Referenced by libMesh::ReferenceCounter::print_info().
 {
 #if defined(LIBMESH_ENABLE_REFERENCE_COUNTING) && defined(DEBUG)
   std::ostringstream oss;
   oss << '\n'
       << " ---------------------------------------------------------------------------- \n"
       << "| Reference count information                                                |\n"
       << " ---------------------------------------------------------------------------- \n";
   for (Counts::iterator it = _counts.begin();
        it != _counts.end(); ++it)
     {
       const std::string name(it->first);
       const unsigned int creations    = it->second.first;
       const unsigned int destructions = it->second.second;
       oss << "| " << name << " reference count information:\n"
           << "|  Creations:    " << creations    << '\n'
           << "|  Destructions: " << destructions << '\n';
     }
   oss << " ---------------------------------------------------------------------------- \n";
   return oss.str();
 #else
   return "";
 #endif
 }
ReplicatedMesh& libMesh::RBEIMEvaluation::get_interpolation_points_mesh ()
Get a writable reference to the interpolation points mesh.
virtual unsigned int libMesh::RBEvaluation::get_n_basis_functions () const inline virtual inherited
Get the current number of basis functions.
Definition at line 146 of file rb_evaluation.h.
References libMesh::RBEvaluation::basis_functions.
   { return cast_int<unsigned int>(basis_functions.size()); }
unsigned int libMesh::RBParametrized::get_n_continuous_params () const inherited
Get the number of continuous parameters.
unsigned int libMesh::RBParametrized::get_n_discrete_params () const inherited
Get the number of discrete parameters.
unsigned int libMesh::RBEIMEvaluation::get_n_parametrized_functions () const
Get the number of parametrized functions that have been attached to this system.
unsigned int libMesh::RBParametrized::get_n_params () const inherited
Get the number of parameters.
Real libMesh::RBParametrized::get_parameter_max (const std::string & param_name) const inherited
Get maximum allowable value of parameter param_name.
Real libMesh::RBParametrized::get_parameter_min (const std::string & param_name) const inherited
Get minimum allowable value of parameter param_name.
std::set<std::string> libMesh::RBParametrized::get_parameter_names () const inherited
Get a set that stores the parameter names.
const RBParameters& libMesh::RBParametrized::get_parameters () const inherited
Get the current parameters.
const RBParameters& libMesh::RBParametrized::get_parameters_max () const inherited
Get an RBParameters object that specifies the maximum allowable value for each parameter.
const RBParameters& libMesh::RBParametrized::get_parameters_min () const inherited
Get an RBParameters object that specifies the minimum allowable value for each parameter.
RBThetaExpansion& libMesh::RBEvaluation::get_rb_theta_expansion () inherited
Get a reference to the rb_theta_expansion.
virtual Real libMesh::RBEvaluation::get_stability_lower_bound () virtual inherited
Get a lower bound for the stability constant (e.g. coercivity constant or inf-sup constant) at the current parameter value.
void libMesh::ReferenceCounter::increment_constructor_count (const std::string & name) inline protected inherited
Increments the construction counter. Should be called in the constructor of any derived class that will be reference counted.
Definition at line 185 of file reference_counter.h.
References libMesh::ReferenceCounter::_counts, libMesh::Quality::name(), and libMesh::Threads::spin_mtx.
Referenced by libMesh::ReferenceCounter::n_objects(), and libMesh::ReferenceCountedObject< RBParametrized >::ReferenceCountedObject().
 {
   Threads::spin_mutex::scoped_lock lock(Threads::spin_mtx);
   std::pair<unsigned int, unsigned int> & p = _counts[name];
   p.first++;
 }
void libMesh::ReferenceCounter::increment_destructor_count (const std::string & name) inline protected inherited
Increments the destruction counter. Should be called in the destructor of any derived class that will be reference counted.
Definition at line 198 of file reference_counter.h.
References libMesh::ReferenceCounter::_counts, libMesh::Quality::name(), and libMesh::Threads::spin_mtx.
Referenced by libMesh::ReferenceCounter::n_objects(), and libMesh::ReferenceCountedObject< RBParametrized >::~ReferenceCountedObject().
 {
   Threads::spin_mutex::scoped_lock lock(Threads::spin_mtx);
   std::pair<unsigned int, unsigned int> & p = _counts[name];
   p.second++;
 }
void libMesh::RBEIMEvaluation::initialize_eim_theta_objects ()
Build a vector of RBTheta objects that accesses the components of the RB_solution member variable of this RBEvaluation. Store these objects in the member vector rb_theta_objects.
void libMesh::RBParametrized::initialize_parameters (const RBParameters & mu_min_in, const RBParameters & mu_max_in, const std::map< std::string, std::vector< Real > > & discrete_parameter_values) inherited
Initialize the parameter ranges and set current_parameters.
void libMesh::RBParametrized::initialize_parameters (const RBParametrized & rb_parametrized) inherited
Initialize the parameter ranges and set current_parameters.
bool libMesh::RBParametrized::is_discrete_parameter (const std::string & mu_name) const inherited
Is parameter mu_name discrete?
bool libMesh::RBEvaluation::is_rb_theta_expansion_initialized () const inherited
Returns
true if the theta expansion has been initialized.
void libMesh::RBEIMEvaluation::legacy_read_in_interpolation_points_elem (const std::string & directory_name) private
Read int interpolation_points_elem from a mesh.
virtual void libMesh::RBEIMEvaluation::legacy_read_offline_data_from_files (const std::string & directory_name = "offline_data", bool read_error_bound_data = true, const bool read_binary_data = true) virtual
Read in the saved Offline reduced basis data to initialize the system for Online solves.
Note
This is a legacy method, use RBDataSerialization instead.
Reimplemented from libMesh::RBEvaluation.
virtual void libMesh::RBEIMEvaluation::legacy_write_offline_data_to_files (const std::string & directory_name = "offline_data", const bool write_binary_data = true) virtual
Write out all the data to text files in order to segregate the Offline stage from the Online stage.
Note
This is a legacy method, use RBDataSerialization instead.
Reimplemented from libMesh::RBEvaluation.
void libMesh::RBEIMEvaluation::legacy_write_out_interpolation_points_elem (const std::string & directory_name) private
Write out interpolation_points_elem by putting the elements into a mesh and writing out the mesh.
static unsigned int libMesh::ReferenceCounter::n_objects () inline static inherited
Prints the number of outstanding (created, but not yet destroyed) objects.
Definition at line 85 of file reference_counter.h.
References libMesh::ReferenceCounter::_n_objects, libMesh::ReferenceCounter::disable_print_counter_info(), libMesh::ReferenceCounter::enable_print_counter_info(), libMesh::ReferenceCounter::increment_constructor_count(), libMesh::ReferenceCounter::increment_destructor_count(), and libMesh::Quality::name().
Referenced by libMesh::System::hide_output(), and libMesh::LibMeshInit::LibMeshInit().
   { return _n_objects; }
processor_id_type libMesh::ParallelObject::n_processors () const inline inherited
Returns
The number of processors in the group.
Definition at line 93 of file parallel_object.h.
References libMesh::ParallelObject::_communicator, and libMesh::Parallel::Communicator::size().
Referenced by libMesh::ParmetisPartitioner::_do_repartition(), libMesh::BoundaryInfo::_find_id_maps(), libMesh::DistributedMesh::add_elem(), libMesh::DistributedMesh::add_node(), libMesh::LaplaceMeshSmoother::allgather_graph(), libMesh::FEMSystem::assembly(), libMesh::ParmetisPartitioner::assign_partitioning(), libMesh::AztecLinearSolver< T >::AztecLinearSolver(), libMesh::MeshCommunication::broadcast(), libMesh::BoundaryInfo::build_node_list_from_side_list(), libMesh::DistributedMesh::clear(), libMesh::Nemesis_IO_Helper::compute_border_node_ids(), libMesh::Nemesis_IO_Helper::construct_nemesis_filename(), libMesh::MeshTools::correct_node_proc_ids(), libMesh::UnstructuredMesh::create_pid_mesh(), libMesh::MeshTools::create_processor_bounding_box(), libMesh::DofMap::distribute_dofs(), libMesh::DofMap::distribute_local_dofs_node_major(), libMesh::DofMap::distribute_local_dofs_var_major(), libMesh::DistributedMesh::DistributedMesh(), libMesh::EnsightIO::EnsightIO(), libMesh::MeshCommunication::gather(), libMesh::MeshCommunication::gather_neighboring_elements(), libMesh::MeshBase::get_info(), libMesh::EquationSystems::get_solution(), libMesh::DistributedVector< T >::init(), libMesh::SystemSubsetBySubdomain::init(), libMesh::ParmetisPartitioner::initialize(), libMesh::Nemesis_IO_Helper::initialize(), libMesh::DistributedMesh::insert_elem(), libMesh::MeshTools::libmesh_assert_parallel_consistent_procids< Elem >(), libMesh::MeshTools::libmesh_assert_parallel_consistent_procids< Node >(), libMesh::MeshTools::libmesh_assert_topology_consistent_procids< Node >(), libMesh::MeshTools::libmesh_assert_valid_boundary_ids(), libMesh::MeshTools::libmesh_assert_valid_dof_ids(), libMesh::MeshTools::libmesh_assert_valid_neighbors(), libMesh::MeshTools::libmesh_assert_valid_refinement_flags(), libMesh::DofMap::local_variable_indices(), libMesh::MeshRefinement::make_coarsening_compatible(), libMesh::MeshBase::n_active_elem_on_proc(), libMesh::MeshBase::n_elem_on_proc(), libMesh::MeshBase::n_nodes_on_proc(), libMesh::SparsityPattern::Build::parallel_sync(), libMesh::Partitioner::partition(), libMesh::MeshBase::partition(), libMesh::Partitioner::partition_unpartitioned_elements(), libMesh::PetscLinearSolver< T >::PetscLinearSolver(), libMesh::System::point_gradient(), libMesh::System::point_hessian(), libMesh::System::point_value(), libMesh::SparseMatrix< T >::print(), libMesh::NameBasedIO::read(), libMesh::Nemesis_IO::read(), libMesh::CheckpointIO::read(), libMesh::XdrIO::read(), libMesh::CheckpointIO::read_connectivity(), libMesh::CheckpointIO::read_nodes(), libMesh::MeshCommunication::redistribute(), libMesh::DistributedMesh::renumber_dof_objects(), libMesh::Partitioner::repartition(), libMesh::MeshCommunication::send_coarse_ghosts(), libMesh::Partitioner::set_node_processor_ids(), libMesh::DofMap::set_nonlocal_dof_objects(), libMesh::Parallel::Sort< KeyType, IdxType >::sort(), libMesh::MeshRefinement::uniformly_coarsen(), libMesh::DistributedMesh::update_parallel_id_counts(), libMesh::GMVIO::write_binary(), libMesh::GMVIO::write_discontinuous_gmv(), libMesh::XdrIO::write_serialized_bcs_helper(), libMesh::XdrIO::write_serialized_connectivity(), libMesh::XdrIO::write_serialized_nodes(), and libMesh::XdrIO::write_serialized_nodesets().
   { return cast_int<processor_id_type>(_communicator.size()); }
void libMesh::RBParametrized::print_discrete_parameter_values () const inherited
Print out all the discrete parameter values.
void libMesh::ReferenceCounter::print_info (std::ostream & out = libMesh::out) static inherited
Prints the reference information, by default to libMesh::out.
Definition at line 88 of file reference_counter.C.
References libMesh::ReferenceCounter::_enable_print_counter, and libMesh::ReferenceCounter::get_info().
Referenced by libMesh::LibMeshInit::LibMeshInit().
 {
   if (_enable_print_counter)
     out_stream << ReferenceCounter::get_info();
 }
void libMesh::RBParametrized::print_parameters () const inherited
Print the current parameters.
processor_id_type libMesh::ParallelObject::processor_id () const inline inherited
Returns
The rank of this processor in the group.
Definition at line 99 of file parallel_object.h.
References libMesh::ParallelObject::_communicator, and libMesh::Parallel::Communicator::rank().
Referenced by libMesh::BoundaryInfo::_find_id_maps(), libMesh::EquationSystems::_read_impl(), libMesh::DistributedMesh::add_elem(), libMesh::BoundaryInfo::add_elements(), libMesh::DofMap::add_neighbors_to_send_list(), libMesh::DistributedMesh::add_node(), libMesh::MeshRefinement::add_node(), libMesh::MeshTools::Modification::all_tri(), libMesh::FEMSystem::assembly(), libMesh::ParmetisPartitioner::assign_partitioning(), libMesh::MeshCommunication::broadcast(), libMesh::EquationSystems::build_discontinuous_solution_vector(), libMesh::Nemesis_IO_Helper::build_element_and_node_maps(), libMesh::ParmetisPartitioner::build_graph(), libMesh::InfElemBuilder::build_inf_elem(), libMesh::BoundaryInfo::build_node_list_from_side_list(), libMesh::DofMap::build_sparsity(), libMesh::DistributedMesh::clear(), libMesh::ExodusII_IO_Helper::close(), libMesh::Nemesis_IO_Helper::compute_border_node_ids(), libMesh::Nemesis_IO_Helper::compute_communication_map_parameters(), libMesh::Nemesis_IO_Helper::compute_internal_and_border_elems_and_internal_nodes(), libMesh::Nemesis_IO_Helper::compute_node_communication_maps(), libMesh::Nemesis_IO_Helper::compute_num_global_elem_blocks(), libMesh::Nemesis_IO_Helper::compute_num_global_nodesets(), libMesh::Nemesis_IO_Helper::compute_num_global_sidesets(), libMesh::Nemesis_IO_Helper::construct_nemesis_filename(), libMesh::MeshTools::correct_node_proc_ids(), libMesh::ExodusII_IO_Helper::create(), libMesh::DistributedMesh::delete_elem(), libMesh::DistributedMesh::delete_node(), libMesh::MeshCommunication::delete_remote_elements(), libMesh::DofMap::distribute_dofs(), libMesh::DofMap::distribute_local_dofs_node_major(), libMesh::DofMap::distribute_local_dofs_var_major(), libMesh::DistributedMesh::DistributedMesh(), libMesh::EnsightIO::EnsightIO(), libMesh::MeshFunction::find_element(), libMesh::MeshFunction::find_elements(), libMesh::UnstructuredMesh::find_neighbors(), libMesh::MeshCommunication::gather(), libMesh::MeshCommunication::gather_neighboring_elements(), libMesh::Nemesis_IO_Helper::get_cmap_params(), libMesh::Nemesis_IO_Helper::get_eb_info_global(), libMesh::Nemesis_IO_Helper::get_elem_cmap(), libMesh::Nemesis_IO_Helper::get_elem_map(), libMesh::MeshBase::get_info(), libMesh::DofMap::get_info(), libMesh::Nemesis_IO_Helper::get_init_global(), libMesh::Nemesis_IO_Helper::get_init_info(), libMesh::Nemesis_IO_Helper::get_loadbal_param(), libMesh::Nemesis_IO_Helper::get_node_cmap(), libMesh::Nemesis_IO_Helper::get_node_map(), libMesh::Nemesis_IO_Helper::get_ns_param_global(), libMesh::EquationSystems::get_solution(), libMesh::Nemesis_IO_Helper::get_ss_param_global(), libMesh::SparsityPattern::Build::handle_vi_vj(), libMesh::DistributedVector< T >::init(), libMesh::SystemSubsetBySubdomain::init(), libMesh::ParmetisPartitioner::initialize(), libMesh::ExodusII_IO_Helper::initialize(), libMesh::ExodusII_IO_Helper::initialize_element_variables(), libMesh::ExodusII_IO_Helper::initialize_global_variables(), libMesh::ExodusII_IO_Helper::initialize_nodal_variables(), libMesh::DistributedMesh::insert_elem(), libMesh::DofMap::is_evaluable(), libMesh::SparsityPattern::Build::join(), libMesh::MeshTools::libmesh_assert_parallel_consistent_procids< Elem >(), libMesh::MeshTools::libmesh_assert_parallel_consistent_procids< Node >(), libMesh::MeshTools::libmesh_assert_valid_neighbors(), libMesh::DistributedMesh::libmesh_assert_valid_parallel_object_ids(), libMesh::DofMap::local_variable_indices(), libMesh::MeshRefinement::make_coarsening_compatible(), libMesh::MeshBase::n_active_local_elem(), libMesh::BoundaryInfo::n_boundary_conds(), libMesh::BoundaryInfo::n_edge_conds(), libMesh::System::n_local_dofs(), libMesh::MeshBase::n_local_elem(), libMesh::MeshBase::n_local_nodes(), libMesh::BoundaryInfo::n_nodeset_conds(), libMesh::BoundaryInfo::n_shellface_conds(), libMesh::WeightedPatchRecoveryErrorEstimator::EstimateError::operator()(), libMesh::SparsityPattern::Build::operator()(), libMesh::PatchRecoveryErrorEstimator::EstimateError::operator()(), libMesh::SparsityPattern::Build::parallel_sync(), libMesh::MetisPartitioner::partition_range(), libMesh::System::point_gradient(), libMesh::System::point_hessian(), libMesh::System::point_value(), libMesh::SparseMatrix< T >::print(), libMesh::NumericVector< T >::print_global(), libMesh::Nemesis_IO_Helper::put_cmap_params(), libMesh::Nemesis_IO_Helper::put_elem_cmap(), libMesh::Nemesis_IO_Helper::put_elem_map(), libMesh::Nemesis_IO_Helper::put_loadbal_param(), libMesh::Nemesis_IO_Helper::put_node_cmap(), libMesh::Nemesis_IO_Helper::put_node_map(), libMesh::NameBasedIO::read(), libMesh::Nemesis_IO::read(), libMesh::CheckpointIO::read(), libMesh::XdrIO::read(), libMesh::ExodusII_IO_Helper::read_elem_num_map(), libMesh::CheckpointIO::read_header(), libMesh::ExodusII_IO_Helper::read_node_num_map(), libMesh::XdrIO::read_serialized_bc_names(), libMesh::XdrIO::read_serialized_bcs_helper(), libMesh::XdrIO::read_serialized_connectivity(), libMesh::XdrIO::read_serialized_nodes(), libMesh::XdrIO::read_serialized_nodesets(), libMesh::XdrIO::read_serialized_subdomain_names(), libMesh::MeshCommunication::redistribute(), libMesh::DistributedMesh::renumber_dof_objects(), libMesh::MeshCommunication::send_coarse_ghosts(), libMesh::Partitioner::set_node_processor_ids(), libMesh::DofMap::set_nonlocal_dof_objects(), libMesh::LaplaceMeshSmoother::smooth(), libMesh::MeshTools::total_weight(), libMesh::MeshRefinement::uniformly_coarsen(), libMesh::Parallel::Packing< Node * >::unpack(), libMesh::Parallel::Packing< Elem * >::unpack(), libMesh::DistributedMesh::update_parallel_id_counts(), libMesh::MeshTools::weight(), libMesh::NameBasedIO::write(), libMesh::CheckpointIO::write(), libMesh::XdrIO::write(), libMesh::EquationSystems::write(), libMesh::GMVIO::write_discontinuous_gmv(), libMesh::ExodusII_IO::write_element_data(), libMesh::ExodusII_IO_Helper::write_element_values(), libMesh::ExodusII_IO_Helper::write_elements(), libMesh::ExodusII_IO::write_global_data(), libMesh::ExodusII_IO_Helper::write_global_values(), libMesh::ExodusII_IO::write_information_records(), libMesh::ExodusII_IO_Helper::write_information_records(), libMesh::ExodusII_IO_Helper::write_nodal_coordinates(), libMesh::UCDIO::write_nodal_data(), libMesh::ExodusII_IO::write_nodal_data(), libMesh::ExodusII_IO::write_nodal_data_discontinuous(), libMesh::ExodusII_IO_Helper::write_nodal_values(), libMesh::Nemesis_IO_Helper::write_nodesets(), libMesh::ExodusII_IO_Helper::write_nodesets(), libMesh::XdrIO::write_serialized_bc_names(), libMesh::XdrIO::write_serialized_bcs_helper(), libMesh::XdrIO::write_serialized_connectivity(), libMesh::XdrIO::write_serialized_nodes(), libMesh::XdrIO::write_serialized_nodesets(), libMesh::XdrIO::write_serialized_subdomain_names(), libMesh::Nemesis_IO_Helper::write_sidesets(), libMesh::ExodusII_IO_Helper::write_sidesets(), libMesh::ExodusII_IO::write_timestep(), and libMesh::ExodusII_IO_Helper::write_timestep().
   { return cast_int<processor_id_type>(_communicator.rank()); }
virtual Real libMesh::RBEIMEvaluation::rb_solve (unsigned int N) virtual
Calculate the EIM approximation to parametrized_function using the first N EIM basis functions. Store the solution coefficients in the member RB_solution.
Returns
The EIM a posteriori error bound.
Reimplemented from libMesh::RBEvaluation.
void libMesh::RBEIMEvaluation::rb_solve (DenseVector< Number > & EIM_rhs)
Calculate the EIM approximation for the given right-hand side vector EIM_rhs. Store the solution coefficients in the member RB_solution.
virtual void libMesh::RBEvaluation::read_in_basis_functions (System & sys, const std::string & directory_name = "offline_data", const bool read_binary_basis_functions = true) virtual inherited
Read in all the basis functions from file.
Parameters
sys Used for file IO.
directory_name Specifies which directory to write files to.
read_binary_basis_functions Indicates whether to expect binary or ASCII data.
Referenced by libMesh::RBEvaluation::set_n_basis_functions().
void libMesh::RBEvaluation::read_in_vectors (System & sys, std::vector< NumericVector< Number > * > & vectors, const std::string & directory_name, const std::string & data_name, const bool read_binary_vectors) inherited
Same as read_in_basis_functions, except in this case we pass in the vectors to be written. We assume that the size of vectors indicates the number of vectors that need to be read in.
Referenced by libMesh::RBEvaluation::set_n_basis_functions().
void libMesh::RBEvaluation::read_in_vectors_from_multiple_files (System & sys, std::vector< std::vector< NumericVector< Number > * > * > multiple_vectors, const std::vector< std::string > & multiple_directory_names, const std::vector< std::string > & multiple_data_names, const bool read_binary_vectors) inherited
Performs read_in_vectors for a list of directory names and data names. Reading in vectors requires us to renumber the dofs in a partition-independent way. This function only renumbers the dofs once at the start (and reverts it at the end), which can save a lot of work compared to renumbering on every read.
Referenced by libMesh::RBEvaluation::set_n_basis_functions().
void libMesh::RBParametrized::read_parameter_data_from_files (const std::string & continuous_param_file_name, const std::string & discrete_param_file_name, const bool read_binary_data) inherited
Read in the parameter ranges from files.
virtual Real libMesh::RBEvaluation::residual_scaling_denom (Real alpha_LB) virtual inherited
Specifies the residual scaling on the denominator to be used in the a posteriori error bound. Override in subclass in order to obtain the desired error bound.
virtual void libMesh::RBEIMEvaluation::resize_data_structures (const unsigned int Nmax, bool resize_error_bound_data = true) virtual
Resize the data structures for storing data associated with this object.
Reimplemented from libMesh::RBEvaluation.
virtual void libMesh::RBEvaluation::set_n_basis_functions (unsigned int n_bfs) inline virtual inherited
Set the number of basis functions. Useful when reading in stored data.
Definition at line 153 of file rb_evaluation.h.
References libMesh::RBEvaluation::basis_functions, libMesh::RBEvaluation::clear_riesz_representors(), libMesh::RBEvaluation::legacy_read_offline_data_from_files(), libMesh::RBEvaluation::legacy_write_offline_data_to_files(), libMesh::RBEvaluation::read_in_basis_functions(), libMesh::RBEvaluation::read_in_vectors(), libMesh::RBEvaluation::read_in_vectors_from_multiple_files(), libMesh::sys, libMesh::RBEvaluation::write_out_basis_functions(), and libMesh::RBEvaluation::write_out_vectors().
 { basis_functions.resize(n_bfs); }
void libMesh::RBParametrized::set_parameters (const RBParameters & params) inherited
Set the current parameters to params
void libMesh::RBEvaluation::set_rb_theta_expansion (RBThetaExpansion & rb_theta_expansion_in) inherited
Set the RBThetaExpansion object.
virtual void libMesh::RBEvaluation::write_out_basis_functions (System & sys, const std::string & directory_name = "offline_data", const bool write_binary_basis_functions = true) virtual inherited
Write out all the basis functions to file. sys is used for file IO directory_name specifies which directory to write files to read_binary_basis_functions indicates whether to expect binary or ASCII data
Referenced by libMesh::RBEvaluation::set_n_basis_functions().
virtual void libMesh::RBEvaluation::write_out_vectors (System & sys, std::vector< NumericVector< Number > * > & vectors, const std::string & directory_name = "offline_data", const std::string & data_name = "bf", const bool write_binary_basis_functions = true) virtual inherited
Same as write_out_basis_functions, except in this case we pass in the vectors to be written.
Referenced by libMesh::RBEvaluation::set_n_basis_functions().
void libMesh::RBParametrized::write_parameter_data_to_files (const std::string & continuous_param_file_name, const std::string & discrete_param_file_name, const bool write_binary_data) inherited
Write out the parameter ranges to files.
Member Data Documentation
const Parallel::Communicator& libMesh::ParallelObject::_communicator protected inherited
Definition at line 105 of file parallel_object.h.
Referenced by libMesh::EquationSystems::build_parallel_solution_vector(), libMesh::ParallelObject::comm(), libMesh::EquationSystems::get_solution(), libMesh::ParallelObject::n_processors(), libMesh::ParallelObject::operator=(), and libMesh::ParallelObject::processor_id().
ReferenceCounter::Counts libMesh::ReferenceCounter::_counts static protected inherited
Actually holds the data.
Definition at line 124 of file reference_counter.h.
Referenced by libMesh::ReferenceCounter::get_info(), libMesh::ReferenceCounter::increment_constructor_count(), and libMesh::ReferenceCounter::increment_destructor_count().
RBThetaExpansion libMesh::RBEIMEvaluation::_empty_rb_theta_expansion private
We initialize RBEIMEvaluation so that it has an "empty" RBThetaExpansion, because this isn't used at all in the EIM.
Definition at line 226 of file rb_eim_evaluation.h.
bool libMesh::ReferenceCounter::_enable_print_counter = true static protected inherited
Flag to control whether reference count information is printed when print_info is called.
Definition at line 143 of file reference_counter.h.
Referenced by libMesh::ReferenceCounter::disable_print_counter_info(), libMesh::ReferenceCounter::enable_print_counter_info(), and libMesh::ReferenceCounter::print_info().
ReplicatedMesh libMesh::RBEIMEvaluation::_interpolation_points_mesh private
Mesh object that we use to store copies of the elements associated with interpolation points.
Definition at line 250 of file rb_eim_evaluation.h.
Threads::spin_mutex libMesh::ReferenceCounter::_mutex static protected inherited
Mutual exclusion object to enable thread-safe reference counting.
Definition at line 137 of file reference_counter.h.
Threads::atomic< unsigned int > libMesh::ReferenceCounter::_n_objects static protected inherited
The number of objects. Print the reference count information when the number returns to 0.
Definition at line 132 of file reference_counter.h.
Referenced by libMesh::ReferenceCounter::n_objects(), libMesh::ReferenceCounter::ReferenceCounter(), and libMesh::ReferenceCounter::~ReferenceCounter().
std::vector<RBParametrizedFunction *> libMesh::RBEIMEvaluation::_parametrized_functions private
This vector stores the parametrized functions that will be approximated in this EIM system.
Definition at line 214 of file rb_eim_evaluation.h.
Real libMesh::RBEIMEvaluation::_previous_error_bound private
Store the previous error bound returned by rb_solve (so we can return it if we are avoiding an unnecessary repeat solve).
Definition at line 244 of file rb_eim_evaluation.h.
unsigned int libMesh::RBEIMEvaluation::_previous_N private
Store the number of basis functions used for the previous solve (so we can avoid an unnecessary repeat solve).
Definition at line 238 of file rb_eim_evaluation.h.
RBParameters libMesh::RBEIMEvaluation::_previous_parameters private
Store the parameters at which the previous solve was performed (so we can avoid an unnecessary repeat solve).
Definition at line 232 of file rb_eim_evaluation.h.
std::vector<RBTheta *> libMesh::RBEIMEvaluation::_rb_eim_theta_objects private
The vector of RBTheta objects that are created to point to this RBEIMEvaluation.
Definition at line 220 of file rb_eim_evaluation.h.
std::vector< std::vector< std::vector<Number> > > libMesh::RBEvaluation::Aq_Aq_representor_innerprods inherited
Definition at line 301 of file rb_evaluation.h.
std::vector< std::vector< NumericVector<Number> *> > libMesh::RBEvaluation::Aq_representor inherited
Vector storing the residual representors associated with the left-hand side. These are basis dependent and hence stored here, whereas the Fq_representors are stored in RBSystem.
Definition at line 317 of file rb_evaluation.h.
std::vector<NumericVector<Number> *> libMesh::RBEvaluation::basis_functions inherited
The libMesh vectors storing the finite element coefficients of the RB basis functions.
Definition at line 242 of file rb_evaluation.h.
Referenced by libMesh::RBEvaluation::get_n_basis_functions(), and libMesh::RBEvaluation::set_n_basis_functions().
bool libMesh::RBEvaluation::compute_RB_inner_product inherited
Boolean flag to indicate whether we compute the RB_inner_product_matrix.
Definition at line 328 of file rb_evaluation.h.
bool libMesh::RBEvaluation::evaluate_RB_error_bound inherited
Boolean to indicate whether we evaluate a posteriori error bounds when rb_solve is called.
Definition at line 323 of file rb_evaluation.h.
std::vector< std::vector< std::vector<Number> > > libMesh::RBEvaluation::Fq_Aq_representor_innerprods inherited
Vectors storing the residual representor inner products to be used in computing the residuals online. We store the Aq-dependent representor inner products because they depend on a reduced basis space. The basis independent representors are stored in RBSystem.
Definition at line 300 of file rb_evaluation.h.
std::vector<Number> libMesh::RBEvaluation::Fq_representor_innerprods inherited
Vectors storing the residual representor inner products to be used in computing the residuals online. These values are independent of a basis, hence they can be copied over directly from an RBSystem.
Definition at line 291 of file rb_evaluation.h.
std::vector<RBParameters> libMesh::RBEvaluation::greedy_param_list inherited
The list of parameters selected by the Greedy algorithm in generating the Reduced Basis associated with this RBEvaluation object.
Definition at line 248 of file rb_evaluation.h.
DenseMatrix<Number> libMesh::RBEIMEvaluation::interpolation_matrix
Dense matrix that stores the lower triangular interpolation matrix that can be used
Definition at line 177 of file rb_eim_evaluation.h.
std::vector<Point> libMesh::RBEIMEvaluation::interpolation_points
The list of interpolation points, i.e. locations at which the basis functions are maximized.
Definition at line 183 of file rb_eim_evaluation.h.
std::vector<Elem *> libMesh::RBEIMEvaluation::interpolation_points_elem
The corresponding list of elements at which the interpolation points were identified.
Definition at line 195 of file rb_eim_evaluation.h.
std::vector<unsigned int> libMesh::RBEIMEvaluation::interpolation_points_var
The corresponding list of variables indices at which the interpolation points were identified.
Definition at line 189 of file rb_eim_evaluation.h.
std::vector< std::vector< Number > > libMesh::RBEvaluation::output_dual_innerprods inherited
The vector storing the dual norm inner product terms for each output. These values are independent of a basis, hence they can be copied over directly from an RBSystem.
Definition at line 309 of file rb_evaluation.h.
std::vector<DenseMatrix<Number> > libMesh::RBEvaluation::RB_Aq_vector inherited
Dense matrices for the RB computations.
Definition at line 261 of file rb_evaluation.h.
std::vector<DenseVector<Number> > libMesh::RBEvaluation::RB_Fq_vector inherited
Dense vector for the RHS.
Definition at line 266 of file rb_evaluation.h.
DenseMatrix<Number> libMesh::RBEvaluation::RB_inner_product_matrix inherited
The inner product matrix. This should be close to the identity, we need to calculate this rather than assume diagonality in order to accurately perform projections since orthogonality degrades with increasing N.
Definition at line 256 of file rb_evaluation.h.
std::vector< Real > libMesh::RBEvaluation::RB_output_error_bounds inherited
Definition at line 283 of file rb_evaluation.h.
std::vector<std::vector<DenseVector<Number> > > libMesh::RBEvaluation::RB_output_vectors inherited
The vectors storing the RB output vectors.
Definition at line 276 of file rb_evaluation.h.
std::vector< Number > libMesh::RBEvaluation::RB_outputs inherited
The vectors storing the RB output values and corresponding error bounds.
Definition at line 282 of file rb_evaluation.h.
DenseVector<Number> libMesh::RBEvaluation::RB_solution inherited
The RB solution vector.
Definition at line 271 of file rb_evaluation.h.
bool libMesh::RBParametrized::verbose_mode inherited
Public boolean to toggle verbose mode.
Definition at line 170 of file rb_parametrized.h.
The documentation for this class was generated from the following file:
rb_eim_evaluation.h