libMesh: libMesh::ParameterMultiAccessor< T > Class Template Reference
SomeWebsiteLogo
libMesh::ParameterMultiAccessor< T > Class Template Reference
Stores a user-provided pointer to a parameter.
#include <parameter_multiaccessor.h>
Public Member Functions
ParameterMultiAccessor ()
ParameterMultiAccessor (const ParameterAccessor< T > &param_accessor)
~ParameterMultiAccessor ()
virtual ParameterAccessor< T > & operator= (T *) libmesh_override
virtual void set (const T &new_value) libmesh_override
virtual const T & get () const libmesh_override
virtual UniquePtr< ParameterAccessor< T > > clone () const libmesh_override
void push_back (const ParameterAccessor< T > &new_accessor)
std::size_t size () const
ParameterProxy< T > operator* ()
ConstParameterProxy< T > operator* () const
Private Attributes
std::vector< ParameterAccessor< T > * > _accessors
Detailed Description
template<typename T = Number>
class libMesh::ParameterMultiAccessor< T >
Stores a user-provided pointer to a parameter.
Accessor object allowing reading and modification of the independent variables in a parameter sensitivity calculation.
This is the "default" ParameterAccessor subclass: it simply stores a user-provided pointer to the parameter, and modifies the value at that location in memory.
Author
Roy Stogner
Date
2015
Definition at line 47 of file parameter_multiaccessor.h.
Constructor & Destructor Documentation
template<typename T = Number> libMesh::ParameterMultiAccessor< T >::ParameterMultiAccessor () inline
Constructor: no parameters attached yet
Definition at line 53 of file parameter_multiaccessor.h.
 {}
template<typename T = Number> libMesh::ParameterMultiAccessor< T >::ParameterMultiAccessor (const ParameterAccessor< T > & param_accessor) inline
Constructor: take the first sub-accessor for the parameter
Definition at line 58 of file parameter_multiaccessor.h.
                                                                       :
     _accessors(1, param_accessor.clone()) {}
template<typename T = Number> libMesh::ParameterMultiAccessor< T >::~ParameterMultiAccessor () inline
Definition at line 64 of file parameter_multiaccessor.h.
References libMesh::ParameterMultiAccessor< T >::_accessors.
{
     for (std::size_t i=0; i != _accessors.size(); ++i)
       delete _accessors[i];
   }
Member Function Documentation
template<typename T = Number> virtual UniquePtr<ParameterAccessor<T> > libMesh::ParameterMultiAccessor< T >::clone () const inline virtual
Returns
A new copy of the accessor.
Implements libMesh::ParameterAccessor< T >.
Definition at line 117 of file parameter_multiaccessor.h.
References libMesh::ParameterMultiAccessor< T >::_accessors.
   {
     ParameterMultiAccessor * pmp = new ParameterMultiAccessor<T>();
     for (std::size_t i=0; i != _accessors.size(); ++i)
       pmp->_accessors.push_back(_accessors[i]->clone().release());
     return UniquePtr<ParameterAccessor<T> >(pmp);
   }
template<typename T = Number> virtual const T& libMesh::ParameterMultiAccessor< T >::get () const inline virtual
Getter: get the value of the parameter we access.
Implements libMesh::ParameterAccessor< T >.
Definition at line 101 of file parameter_multiaccessor.h.
References libMesh::ParameterMultiAccessor< T >::_accessors, and libMesh::libmesh_assert().
   {
     libmesh_assert(!_accessors.empty());
     const T & val = _accessors[0]->get();
 #ifndef NDEBUG
     // If you're already using inconsistent parameters we can't help
     // you.
     for (std::size_t i=1; i < _accessors.size(); ++i)
       libmesh_assert_equal_to(_accessors[i]->get(), val);
 #endif
     return val;
   }
template<typename T = Number> ParameterProxy<T> libMesh::ParameterAccessor< T >::operator* () inline inherited
Proxy: for backward compatibility, we allow codes to treat a ParameterAccessor as if it were a simple pointer-to-value. We can't safely allow "Number * n = parameter_vector[p]" to compile, but we can allow "*parameter_vector[p] += deltap" to work.
Definition at line 86 of file parameter_accessor.h.
 { return ParameterProxy<T>(*this); }
template<typename T = Number> ConstParameterProxy<T> libMesh::ParameterAccessor< T >::operator* () const inline inherited
Definition at line 88 of file parameter_accessor.h.
References libMesh::ParameterAccessor< T >::clone().
 { return ConstParameterProxy<T>(*this); }
template<typename T = Number> virtual ParameterAccessor<T>& libMesh::ParameterMultiAccessor< T >::operator= (T *) inline virtual
A simple reseater won't work with a multi-accessor
Reimplemented from libMesh::ParameterAccessor< T >.
Definition at line 73 of file parameter_multiaccessor.h.
   {
     libmesh_error();
     return *this;
   }
template<typename T = Number> void libMesh::ParameterMultiAccessor< T >::push_back (const ParameterAccessor< T > & new_accessor) inline
Definition at line 127 of file parameter_multiaccessor.h.
References libMesh::ParameterMultiAccessor< T >::_accessors, and libMesh::ParameterAccessor< T >::clone().
{
     _accessors.push_back(new_accessor.clone().release());
   }
template<typename T = Number> virtual void libMesh::ParameterMultiAccessor< T >::set (const T & new_value) inline virtual
Setter: change the value of the parameter we access.
Implements libMesh::ParameterAccessor< T >.
Definition at line 82 of file parameter_multiaccessor.h.
References libMesh::ParameterMultiAccessor< T >::_accessors, and libMesh::libmesh_assert().
   {
     libmesh_assert(!_accessors.empty());
 #ifndef NDEBUG
     // Compare other values to the last one we'll change
     const T & val = _accessors.back()->get();
 #endif
     for (std::size_t i=0; i != _accessors.size(); ++i)
       {
         // If you're already using inconsistent parameters we can't
         // help you.
         libmesh_assert_equal_to(_accessors[i]->get(), val);
         _accessors[i]->set(new_value);
       }
   }
template<typename T = Number> std::size_t libMesh::ParameterMultiAccessor< T >::size () const inline
Returns
The number of sub-accessors associated with this parameter. Useful for testing if the multi-accessor is empty/invalid.
Definition at line 136 of file parameter_multiaccessor.h.
References libMesh::ParameterMultiAccessor< T >::_accessors.
 { return _accessors.size(); }
Member Data Documentation
template<typename T = Number> std::vector<ParameterAccessor<T> *> libMesh::ParameterMultiAccessor< T >::_accessors private
Definition at line 139 of file parameter_multiaccessor.h.
Referenced by libMesh::ParameterMultiAccessor< T >::clone(), libMesh::ParameterMultiAccessor< T >::get(), libMesh::ParameterMultiAccessor< T >::push_back(), libMesh::ParameterMultiAccessor< T >::set(), libMesh::ParameterMultiAccessor< T >::size(), and libMesh::ParameterMultiAccessor< T >::~ParameterMultiAccessor().
The documentation for this class was generated from the following file:
parameter_multiaccessor.h