libMesh: libMesh::SiblingCoupling Class Reference
SomeWebsiteLogo
libMesh::SiblingCoupling Class Reference
#include <sibling_coupling.h>
Public Types
typedef std::unordered_map< const Elem *, const CouplingMatrix * > map_type
Public Member Functions
SiblingCoupling ()
void set_dof_coupling (const CouplingMatrix *dof_coupling)
virtual void operator() (const MeshBase::const_element_iterator &range_begin, const MeshBase::const_element_iterator &range_end, processor_id_type p, map_type &coupled_elements)
virtual void mesh_reinit ()
virtual void dofmap_reinit ()
virtual void redistribute ()
virtual void delete_remote_elements ()
Static Public Member Functions
static std::string get_info ()
static void print_info (std::ostream &out=libMesh::out)
static unsigned int n_objects ()
static void enable_print_counter_info ()
static void disable_print_counter_info ()
Protected Types
typedef std::map< std::string, std::pair< unsigned int, unsigned int > > Counts
Protected Member Functions
void increment_constructor_count (const std::string &name)
void increment_destructor_count (const std::string &name)
Static Protected Attributes
static Counts _counts
static Threads::atomic< unsigned int > _n_objects
static Threads::spin_mutex _mutex
static bool _enable_print_counter = true
Private Attributes
const CouplingMatrix * _dof_coupling
Detailed Description
This class adds coupling (for use in send_list construction) between active elements and all descendants of their parent.
This may be useful when constructing projections onto the parent element for error indicator evaluation.
Author
Roy H. Stogner
Date
2016
Definition at line 39 of file sibling_coupling.h.
Member Typedef Documentation
Counts
typedef std::map<std::string, std::pair<unsigned int, unsigned int> > libMesh::ReferenceCounter::Counts protected inherited
Data structure to log the information. The log is identified by the class name.
Definition at line 117 of file reference_counter.h.
map_type
typedef std::unordered_map<const Elem*, const CouplingMatrix*> libMesh::GhostingFunctor::map_type inherited
What elements do we care about and what variables do we care about on each element?
Definition at line 154 of file ghosting_functor.h.
Constructor & Destructor Documentation
SiblingCoupling()
libMesh::SiblingCoupling::SiblingCoupling () inline
Constructor.
Definition at line 46 of file sibling_coupling.h.
                     :
     _dof_coupling(nullptr) {}
Member Function Documentation
delete_remote_elements()
virtual void libMesh::GhostingFunctor::delete_remote_elements () inline virtual inherited
GhostingFunctor subclasses with relatively long-lasting caches may want to delete the no-longer-relevant parts of those caches after a redistribution is complete.
Reimplemented in libMesh::PointNeighborCoupling, and libMesh::DefaultCoupling.
Definition at line 204 of file ghosting_functor.h.
 {};
disable_print_counter_info()
void libMesh::ReferenceCounter::disable_print_counter_info () static inherited
Definition at line 106 of file reference_counter.C.
References libMesh::ReferenceCounter::_enable_print_counter.
Referenced by libMesh::LibMeshInit::LibMeshInit().
 {
   _enable_print_counter = false;
   return;
 }
dofmap_reinit()
virtual void libMesh::GhostingFunctor::dofmap_reinit () inline virtual inherited
For algebraic ghosting or coupling functors we also call dofmap_reinit() later, after dofs have been distributed on the new mesh but before the functors have been queried for send_list or sparsity pattern calculations.
Definition at line 185 of file ghosting_functor.h.
 {};
enable_print_counter_info()
void libMesh::ReferenceCounter::enable_print_counter_info () static inherited
Methods to enable/disable the reference counter output from print_info()
Definition at line 100 of file reference_counter.C.
References libMesh::ReferenceCounter::_enable_print_counter.
 {
   _enable_print_counter = true;
   return;
 }
get_info()
std::string libMesh::ReferenceCounter::get_info () static inherited
Gets a string containing the reference information.
Definition at line 47 of file reference_counter.C.
References libMesh::ReferenceCounter::_counts, and libMesh::Quality::name().
Referenced by libMesh::ReferenceCounter::print_info().
 {
 #if defined(LIBMESH_ENABLE_REFERENCE_COUNTING) && defined(DEBUG)
   std::ostringstream oss;
   oss << '\n'
       << " ---------------------------------------------------------------------------- \n"
       << "| Reference count information                                                |\n"
       << " ---------------------------------------------------------------------------- \n";
   for (const auto & pr : _counts)
     {
       const std::string name(pr.first);
       const unsigned int creations    = pr.second.first;
       const unsigned int destructions = pr.second.second;
       oss << "| " << name << " reference count information:\n"
           << "|  Creations:    " << creations    << '\n'
           << "|  Destructions: " << destructions << '\n';
     }
   oss << " ---------------------------------------------------------------------------- \n";
   return oss.str();
 #else
   return "";
 #endif
 }
increment_constructor_count()
void libMesh::ReferenceCounter::increment_constructor_count (const std::string & name) inline protected inherited
Increments the construction counter. Should be called in the constructor of any derived class that will be reference counted.
Definition at line 181 of file reference_counter.h.
References libMesh::ReferenceCounter::_counts, libMesh::Quality::name(), and libMesh::Threads::spin_mtx.
Referenced by libMesh::ReferenceCountedObject< RBParametrized >::ReferenceCountedObject().
 {
   Threads::spin_mutex::scoped_lock lock(Threads::spin_mtx);
   std::pair<unsigned int, unsigned int> & p = _counts[name];
   p.first++;
 }
increment_destructor_count()
void libMesh::ReferenceCounter::increment_destructor_count (const std::string & name) inline protected inherited
Increments the destruction counter. Should be called in the destructor of any derived class that will be reference counted.
Definition at line 194 of file reference_counter.h.
References libMesh::ReferenceCounter::_counts, libMesh::Quality::name(), and libMesh::Threads::spin_mtx.
Referenced by libMesh::ReferenceCountedObject< RBParametrized >::~ReferenceCountedObject().
 {
   Threads::spin_mutex::scoped_lock lock(Threads::spin_mtx);
   std::pair<unsigned int, unsigned int> & p = _counts[name];
   p.second++;
 }
mesh_reinit()
virtual void libMesh::GhostingFunctor::mesh_reinit () inline virtual inherited
GhostingFunctor subclasses which cache data will need to initialize that cache. We call mesh_reinit() whenever the relevant Mesh has changed, but before remote elements on a distributed mesh are deleted.
Reimplemented in libMesh::PointNeighborCoupling, and libMesh::DefaultCoupling.
Definition at line 177 of file ghosting_functor.h.
 {};
n_objects()
static unsigned int libMesh::ReferenceCounter::n_objects () inline static inherited
Prints the number of outstanding (created, but not yet destroyed) objects.
Definition at line 83 of file reference_counter.h.
References libMesh::ReferenceCounter::_n_objects.
   { return _n_objects; }
operator()()
void libMesh::SiblingCoupling::operator() (const MeshBase::const_element_iterator & range_begin, const MeshBase::const_element_iterator & range_end, processor_id_type p, map_type & coupled_elements) virtual
For the specified range of active elements, find any sibling elements which should be evaluable too.
Implements libMesh::GhostingFunctor.
Definition at line 29 of file sibling_coupling.C.
References libMesh::Elem::active_family_tree(), libMesh::as_range(), and libMesh::Elem::parent().
 {
   LOG_SCOPE("operator()", "SiblingCoupling");
   for (const auto & elem : as_range(range_begin, range_end))
     {
       std::vector<const Elem *> active_siblings;
       const Elem * parent = elem->parent();
       if (!parent)
         continue;
 #ifdef LIBMESH_ENABLE_AMR
       parent->active_family_tree(active_siblings);
 #endif
       for (const Elem * sibling : active_siblings)
         if (sibling->processor_id() != p)
           coupled_elements.insert
             (std::make_pair(sibling, _dof_coupling));
     }
 }
print_info()
void libMesh::ReferenceCounter::print_info (std::ostream & out = libMesh::out) static inherited
Prints the reference information, by default to libMesh::out.
Definition at line 87 of file reference_counter.C.
References libMesh::ReferenceCounter::_enable_print_counter, and libMesh::ReferenceCounter::get_info().
 {
   if (_enable_print_counter)
     out_stream << ReferenceCounter::get_info();
 }
redistribute()
virtual void libMesh::GhostingFunctor::redistribute () inline virtual inherited
GhostingFunctor subclasses with relatively long-lasting caches may want to redistribute those caches whenever the relevant Mesh is redistributed; we will give them an opportunity when that happens. At the point in the code where this is called, element processor ids have been set to their new destinations, and those elements have been copied to their new destinations, but the elements have not yet been deleted by the processors which previously held them..
Reimplemented in libMesh::PointNeighborCoupling, and libMesh::DefaultCoupling.
Definition at line 197 of file ghosting_functor.h.
 {};
set_dof_coupling()
void libMesh::SiblingCoupling::set_dof_coupling (const CouplingMatrix * dof_coupling) inline
Definition at line 50 of file sibling_coupling.h.
References _dof_coupling.
   { _dof_coupling = dof_coupling; }
Member Data Documentation
_counts
ReferenceCounter::Counts libMesh::ReferenceCounter::_counts static protected inherited
Actually holds the data.
Definition at line 122 of file reference_counter.h.
Referenced by libMesh::ReferenceCounter::get_info(), libMesh::ReferenceCounter::increment_constructor_count(), and libMesh::ReferenceCounter::increment_destructor_count().
_dof_coupling
const CouplingMatrix* libMesh::SiblingCoupling::_dof_coupling private
Definition at line 64 of file sibling_coupling.h.
Referenced by set_dof_coupling().
_enable_print_counter
bool libMesh::ReferenceCounter::_enable_print_counter = true static protected inherited
Flag to control whether reference count information is printed when print_info is called.
Definition at line 141 of file reference_counter.h.
Referenced by libMesh::ReferenceCounter::disable_print_counter_info(), libMesh::ReferenceCounter::enable_print_counter_info(), and libMesh::ReferenceCounter::print_info().
_mutex
Threads::spin_mutex libMesh::ReferenceCounter::_mutex static protected inherited
Mutual exclusion object to enable thread-safe reference counting.
Definition at line 135 of file reference_counter.h.
_n_objects
Threads::atomic< unsigned int > libMesh::ReferenceCounter::_n_objects static protected inherited
The number of objects. Print the reference count information when the number returns to 0.
Definition at line 130 of file reference_counter.h.
Referenced by libMesh::ReferenceCounter::n_objects(), libMesh::ReferenceCounter::ReferenceCounter(), and libMesh::ReferenceCounter::~ReferenceCounter().
The documentation for this class was generated from the following files:
sibling_coupling.h
sibling_coupling.C