libMesh: libMesh::OldSolutionCoefs< Output, point_output > Class Template Reference
SomeWebsiteLogo
libMesh::OldSolutionCoefs< Output, point_output > Class Template Reference
Public Types
typedef DSNAOutput< Output >::type DSNA
Public Member Functions
OldSolutionCoefs (const libMesh::System &sys_in)
OldSolutionCoefs (const OldSolutionCoefs &in)
DSNA eval_at_node (const FEMContext &c, unsigned int i, unsigned int elem_dim, const Node &n, Real=0.)
DSNA eval_at_point (const FEMContext &c, unsigned int i, const Point &p, Real=0.)
void eval_old_dofs (const FEMContext &c, unsigned int var, std::vector< DSNA > &values)
template<>
DynamicSparseNumberArray< Real, dof_id_type > eval_at_point (const FEMContext &c, unsigned int i, const Point &p, Real)
template<>
VectorValue< DynamicSparseNumberArray< Real, dof_id_type > > eval_at_point (const FEMContext &c, unsigned int i, const Point &p, Real)
template<>
DynamicSparseNumberArray< Real, dof_id_type > eval_at_node (const FEMContext &c, unsigned int i, unsigned int, const Node &n, Real)
template<>
VectorValue< DynamicSparseNumberArray< Real, dof_id_type > > eval_at_node (const FEMContext &c, unsigned int i, unsigned int elem_dim, const Node &n, Real)
template<>
void get_shape_outputs (FEBase &fe)
template<>
void get_shape_outputs (FEBase &fe)
template<>
void get_shape_outputs (FEBase &fe)
template<>
void get_shape_outputs (FEBase &fe)
void init_context (FEMContext &c)
bool is_grid_projection ()
Static Public Member Functions
static void get_shape_outputs (FEBase &fe)
Protected Member Functions
template<>
const Real out_of_elem_tol
template<>
const Real out_of_elem_tol
template<>
const Real out_of_elem_tol
template<>
const Real out_of_elem_tol
void check_old_context (const FEMContext &c)
bool check_old_context (const FEMContext &c, const Point &p)
Protected Attributes
const Elem * last_elem
const System & sys
FEMContext old_context
Static Protected Attributes
static const Real out_of_elem_tol
Detailed Description
template<typename Output, void(FEMContext::*)(unsigned int, const Point &, Output &, const Real) const point_output>
class libMesh::OldSolutionCoefs< Output, point_output >
The OldSolutionCoefs input functor class can be used with GenericProjector to read solution transfer coefficients on a just-refined-and-coarsened mesh.
Author
Roy H. Stogner
Date
2017
Definition at line 443 of file system_projection.C.
Member Typedef Documentation
template<typename Output , void(FEMContext::*)(unsigned int, const Point &, Output &, const Real) const point_output> typedef DSNAOutput<Output>::type libMesh::OldSolutionCoefs< Output, point_output >::DSNA
Definition at line 446 of file system_projection.C.
Constructor & Destructor Documentation
template<typename Output , void(FEMContext::*)(unsigned int, const Point &, Output &, const Real) const point_output> libMesh::OldSolutionCoefs< Output, point_output >::OldSolutionCoefs (const libMesh::System & sys_in) inline
Definition at line 448 of file system_projection.C.
References libMesh::FEMContext::OLD_DOFS_ONLY.
                                                  :
     OldSolutionBase<Output, point_output>(sys_in)
   {
     this->old_context.set_algebraic_type(FEMContext::OLD_DOFS_ONLY);
   }
template<typename Output , void(FEMContext::*)(unsigned int, const Point &, Output &, const Real) const point_output> libMesh::OldSolutionCoefs< Output, point_output >::OldSolutionCoefs (const OldSolutionCoefs< Output, point_output > & in) inline
Definition at line 454 of file system_projection.C.
References libMesh::FEMContext::OLD_DOFS_ONLY, and libMesh::Real.
                                                 :
     OldSolutionBase<Output, point_output>(in.sys)
   {
     this->old_context.set_algebraic_type(FEMContext::OLD_DOFS_ONLY);
   }
Member Function Documentation
template<typename Output , void(FEMContext::*)(unsigned int, const Point &, Output &, const Real) const point_output> void libMesh::OldSolutionBase< Output, point_output >::check_old_context (const FEMContext & c) inline protected inherited
Definition at line 251 of file generic_projector.h.
References libMesh::FEMContext::get_elem(), libMesh::Elem::JUST_COARSENED, libMesh::Elem::JUST_REFINED, libMesh::DofObject::old_dof_object, libMesh::Elem::parent(), and libMesh::Elem::refinement_flag().
   {
     LOG_SCOPE ("check_old_context(c)", "OldSolutionBase");
     const Elem & elem = c.get_elem();
     if (last_elem != &elem)
       {
         if (elem.refinement_flag() == Elem::JUST_REFINED)
           {
             old_context.pre_fe_reinit(sys, elem.parent());
           }
         else if (elem.refinement_flag() == Elem::JUST_COARSENED)
           {
             libmesh_error();
           }
         else
           {
             if (!elem.old_dof_object)
               {
                 libmesh_error();
               }
             old_context.pre_fe_reinit(sys, &elem);
           }
         last_elem = &elem;
       }
     else
       {
         libmesh_assert(old_context.has_elem());
       }
   }
template<typename Output , void(FEMContext::*)(unsigned int, const Point &, Output &, const Real) const point_output> bool libMesh::OldSolutionBase< Output, point_output >::check_old_context (const FEMContext & c, const Point & p) inline protected inherited
Definition at line 284 of file generic_projector.h.
References libMesh::Elem::child_ref_range(), libMesh::FEMContext::get_elem(), libMesh::Elem::hmax(), libMesh::Elem::JUST_COARSENED, libMesh::Elem::JUST_REFINED, libMesh::DofObject::old_dof_object, libMesh::Elem::parent(), libMesh::Real, and libMesh::Elem::refinement_flag().
   {
     LOG_SCOPE ("check_old_context(c,p)", "OldSolutionBase");
     const Elem & elem = c.get_elem();
     if (last_elem != &elem)
       {
         if (elem.refinement_flag() == Elem::JUST_REFINED)
           {
             old_context.pre_fe_reinit(sys, elem.parent());
           }
         else if (elem.refinement_flag() == Elem::JUST_COARSENED)
           {
             // Find the child with this point.  Use out_of_elem_tol
             // (in physical space, which may correspond to a large
             // tolerance in master space!) to allow for out-of-element
             // finite differencing of mixed gradient terms.  Pray we
             // have no quadrature locations which are within 1e-5 of
             // the element subdivision boundary but are not exactly on
             // that boundary.
             const Real master_tol = out_of_elem_tol / elem.hmax() * 2;
             for (auto & child : elem.child_ref_range())
               if (child.close_to_point(p, master_tol))
                 {
                   old_context.pre_fe_reinit(sys, &child);
                   break;
                 }
             libmesh_assert
               (old_context.get_elem().close_to_point(p, master_tol));
           }
         else
           {
             if (!elem.old_dof_object)
               return false;
             old_context.pre_fe_reinit(sys, &elem);
           }
         last_elem = &elem;
       }
     else
       {
         libmesh_assert(old_context.has_elem());
         const Real master_tol = out_of_elem_tol / elem.hmax() * 2;
         if (!old_context.get_elem().close_to_point(p, master_tol))
           {
             libmesh_assert_equal_to
               (elem.refinement_flag(), Elem::JUST_COARSENED);
             for (auto & child : elem.child_ref_range())
               if (child.close_to_point(p, master_tol))
                 {
                   old_context.pre_fe_reinit(sys, &child);
                   break;
                 }
             libmesh_assert
               (old_context.get_elem().close_to_point(p, master_tol));
           }
       }
     return true;
   }
template<typename Output , void(FEMContext::*)(unsigned int, const Point &, Output &, const Real) const point_output> DSNA libMesh::OldSolutionCoefs< Output, point_output >::eval_at_node (const FEMContext & c, unsigned int i, unsigned int elem_dim, const Node & n, Real = 0.)
Referenced by libMesh::OldSolutionCoefs< Output, point_output >::eval_at_node(), and libMesh::OldSolutionCoefs< Output, point_output >::eval_at_point().
template<> DynamicSparseNumberArray< Real, dof_id_type > libMesh::OldSolutionCoefs< Real,&FEMContext::point_value >::eval_at_node (const FEMContext & c, unsigned int i, unsigned int, const Node & n, Real) inline
Definition at line 594 of file system_projection.C.
References libMesh::DofObject::dof_number(), libMesh::OldSolutionCoefs< Output, point_output >::eval_at_node(), libMesh::DofObject::n_comp(), libMesh::DofObject::n_vars(), and libMesh::DofObject::old_dof_object.
 {
   LOG_SCOPE ("Real eval_at_node()", "OldSolutionCoefs");
   // Optimize for the common case, where this node was part of the
   // old solution.
   //
   // Be sure to handle cases where the variable wasn't defined on
   // this node (due to changing subdomain support) or where the
   // variable has no components on this node (due to Elem order
   // exceeding FE order)
   if (n.old_dof_object &&
       n.old_dof_object->n_vars(sys.number()) &&
       n.old_dof_object->n_comp(sys.number(), i))
     {
       DynamicSparseNumberArray<Real, dof_id_type> returnval;
       const dof_id_type old_id =
         n.old_dof_object->dof_number(sys.number(), i, 0);
       returnval.resize(1);
       returnval.raw_at(0) = 1;
       returnval.raw_index(0) = old_id;
       return returnval;
     }
   return this->eval_at_point(c, i, n, 0);
 }
template<> VectorValue< DynamicSparseNumberArray< Real, dof_id_type > > libMesh::OldSolutionCoefs< RealGradient,&FEMContext::point_gradient >::eval_at_node (const FEMContext & c, unsigned int i, unsigned int elem_dim, const Node & n, Real) inline
Definition at line 631 of file system_projection.C.
References libMesh::DofObject::dof_number(), libMesh::DofObject::n_comp(), libMesh::DofObject::n_vars(), and libMesh::DofObject::old_dof_object.
 {
   LOG_SCOPE ("RealGradient eval_at_node()", "OldSolutionCoefs");
   // Optimize for the common case, where this node was part of the
   // old solution.
   //
   // Be sure to handle cases where the variable wasn't defined on
   // this node (due to changing subdomain support) or where the
   // variable has no components on this node (due to Elem order
   // exceeding FE order)
   if (n.old_dof_object &&
       n.old_dof_object->n_vars(sys.number()) &&
       n.old_dof_object->n_comp(sys.number(), i))
     {
       VectorValue<DynamicSparseNumberArray<Real, dof_id_type> > g;
       for (unsigned int d = 0; d != elem_dim; ++d)
         {
           const dof_id_type old_id =
             n.old_dof_object->dof_number(sys.number(), i, d+1);
           g(d).resize(1);
           g(d).raw_at(0) = 1;
           g(d).raw_index(0) = old_id;
         }
       return g;
     }
   return this->eval_at_point(c, i, n, 0);
 }
template<typename Output , void(FEMContext::*)(unsigned int, const Point &, Output &, const Real) const point_output> DSNA libMesh::OldSolutionCoefs< Output, point_output >::eval_at_point (const FEMContext & c, unsigned int i, const Point & p, Real = 0.)
Referenced by libMesh::OldSolutionCoefs< Output, point_output >::eval_at_point(), and libMesh::OldSolutionCoefs< Output, point_output >::eval_old_dofs().
template<> DynamicSparseNumberArray< Real, dof_id_type > libMesh::OldSolutionCoefs< Real,&FEMContext::point_value >::eval_at_point (const FEMContext & c, unsigned int i, const Point & p, Real) inline
Definition at line 500 of file system_projection.C.
References libMesh::OldSolutionCoefs< Output, point_output >::eval_at_point(), libMesh::FEGenericBase< OutputType >::get_phi(), libmesh_nullptr, and libMesh::Real.
 {
   LOG_SCOPE ("eval_at_point()", "OldSolutionCoefs");
   if (!this->check_old_context(c, p))
     return 0;
   // Get finite element object
   FEGenericBase<Real> * fe = libmesh_nullptr;
   this->old_context.get_element_fe<Real>
     (i, fe, this->old_context.get_elem_dim());
   // Build a FE for calculating phi(p)
   FEGenericBase<Real> * fe_new =
     this->old_context.build_new_fe(fe, p);
   // Get the values and global indices of the shape functions
   const std::vector<std::vector<Real> > & phi = fe_new->get_phi();
   const std::vector<dof_id_type> & dof_indices =
     this->old_context.get_dof_indices(i);
   const std::size_t n_dofs = phi.size();
   libmesh_assert_equal_to(n_dofs, dof_indices.size());
   DynamicSparseNumberArray<Real, dof_id_type> returnval;
   returnval.resize(n_dofs);
   for (std::size_t i = 0; i != n_dofs; ++i)
     {
       returnval.raw_at(i) = phi[i][0];
       returnval.raw_index(i) = dof_indices[i];
     }
   return returnval;
 }
template<> VectorValue< DynamicSparseNumberArray< Real, dof_id_type > > libMesh::OldSolutionCoefs< RealGradient,&FEMContext::point_gradient >::eval_at_point (const FEMContext & c, unsigned int i, const Point & p, Real) inline
Definition at line 545 of file system_projection.C.
References libMesh::OldSolutionCoefs< Output, point_output >::eval_at_node(), libMesh::FEGenericBase< OutputType >::get_dphi(), libmesh_nullptr, and libMesh::Real.
 {
   LOG_SCOPE ("eval_at_point()", "OldSolutionCoefs");
   if (!this->check_old_context(c, p))
     return 0;
   // Get finite element object
   FEGenericBase<Real> * fe = libmesh_nullptr;
   this->old_context.get_element_fe<Real>
     (i, fe, this->old_context.get_elem_dim());
   // Build a FE for calculating phi(p)
   FEGenericBase<Real> * fe_new =
     this->old_context.build_new_fe(fe, p);
   // Get the values and global indices of the shape functions
   const std::vector<std::vector<RealGradient> > & dphi = fe_new->get_dphi();
   const std::vector<dof_id_type> & dof_indices =
     this->old_context.get_dof_indices(i);
   const std::size_t n_dofs = dphi.size();
   libmesh_assert_equal_to(n_dofs, dof_indices.size());
   VectorValue<DynamicSparseNumberArray<Real, dof_id_type> > returnval;
   for (unsigned int d = 0; d != LIBMESH_DIM; ++d)
     returnval(d).resize(n_dofs);
   for (std::size_t i = 0; i != n_dofs; ++i)
     {
       for (unsigned int d = 0; d != LIBMESH_DIM; ++d)
         {
           returnval(d).raw_at(i) = dphi[i][0](d);
           returnval(d).raw_index(i) = dof_indices[i];
         }
     }
   return returnval;
 }
template<typename Output , void(FEMContext::*)(unsigned int, const Point &, Output &, const Real) const point_output> void libMesh::OldSolutionCoefs< Output, point_output >::eval_old_dofs (const FEMContext & c, unsigned int var, std::vector< DSNA > & values) inline
Definition at line 471 of file system_projection.C.
References libMesh::OldSolutionCoefs< Output, point_output >::eval_at_point().
   {
     LOG_SCOPE ("eval_old_dofs()", "OldSolutionValue");
     this->check_old_context(c);
     const std::vector<dof_id_type> & old_dof_indices =
       this->old_context.get_dof_indices(var);
     std::size_t size = values.size();
     libmesh_assert_equal_to (old_dof_indices.size(), size);
     for (unsigned int i=0; i != size; ++i)
       {
         values[i].resize(1);
         values[i].raw_at(0) = 1;
         values[i].raw_index(0) = old_dof_indices[i];
       }
   }
template<typename Output , void(FEMContext::*)(unsigned int, const Point &, Output &, const Real) const point_output> static void libMesh::OldSolutionBase< Output, point_output >::get_shape_outputs (FEBase & fe) static inherited
template<> void libMesh::OldSolutionBase< Number,&FEMContext::point_value >::get_shape_outputs (FEBase & fe) inline inherited
Definition at line 438 of file generic_projector.h.
References libMesh::FEGenericBase< OutputType >::get_phi().
 {
   fe.get_phi();
 }
template<> void libMesh::OldSolutionBase< Gradient,&FEMContext::point_gradient >::get_shape_outputs (FEBase & fe) inline inherited
Definition at line 446 of file generic_projector.h.
References libMesh::FEGenericBase< OutputType >::get_dphi().
 {
   fe.get_dphi();
 }
template<> void libMesh::OldSolutionBase< Real,&FEMContext::point_value >::get_shape_outputs (FEBase & fe) inline inherited
Definition at line 455 of file generic_projector.h.
References libMesh::FEGenericBase< OutputType >::get_phi().
 {
   fe.get_phi();
 }
template<> void libMesh::OldSolutionBase< RealGradient,&FEMContext::point_gradient >::get_shape_outputs (FEBase & fe) inline inherited
Definition at line 463 of file generic_projector.h.
References libMesh::OldSolutionValue< Output, point_output >::eval_at_node(), and libMesh::FEGenericBase< OutputType >::get_dphi().
 {
   fe.get_dphi();
 }
template<typename Output , void(FEMContext::*)(unsigned int, const Point &, Output &, const Real) const point_output> void libMesh::OldSolutionBase< Output, point_output >::init_context (FEMContext & c) inline inherited
Definition at line 227 of file generic_projector.h.
References libMesh::FEMContext::DOFS_ONLY, libmesh_nullptr, and libMesh::FEMContext::set_algebraic_type().
   {
     c.set_algebraic_type(FEMContext::DOFS_ONLY);
     // Loop over variables, to prerequest
     for (unsigned int var=0; var!=sys.n_vars(); ++var)
       {
         FEBase * fe = libmesh_nullptr;
         const std::set<unsigned char> & elem_dims =
           old_context.elem_dimensions();
         for (std::set<unsigned char>::const_iterator dim_it =
                elem_dims.begin(); dim_it != elem_dims.end(); ++dim_it)
           {
             const unsigned char dim = *dim_it;
             old_context.get_element_fe( var, fe, dim );
             get_shape_outputs(*fe);
           }
       }
   }
template<typename Output , void(FEMContext::*)(unsigned int, const Point &, Output &, const Real) const point_output> bool libMesh::OldSolutionBase< Output, point_output >::is_grid_projection () inline inherited
Definition at line 248 of file generic_projector.h.
 { return true; }
template<> const Real libMesh::OldSolutionBase< Number,&FEMContext::point_value >::out_of_elem_tol () protected inherited
Definition at line 544 of file generic_projector.h.
template<> const Real libMesh::OldSolutionBase< Gradient,&FEMContext::point_gradient >::out_of_elem_tol () protected inherited
Definition at line 547 of file generic_projector.h.
template<> const Real libMesh::OldSolutionBase< Real,&FEMContext::point_value >::out_of_elem_tol () protected inherited
Definition at line 551 of file generic_projector.h.
template<> const Real libMesh::OldSolutionBase< RealGradient,&FEMContext::point_gradient >::out_of_elem_tol () protected inherited
Definition at line 554 of file generic_projector.h.
Member Data Documentation
template<typename Output , void(FEMContext::*)(unsigned int, const Point &, Output &, const Real) const point_output> const Elem* libMesh::OldSolutionBase< Output, point_output >::last_elem protected inherited
Definition at line 352 of file generic_projector.h.
template<typename Output , void(FEMContext::*)(unsigned int, const Point &, Output &, const Real) const point_output> FEMContext libMesh::OldSolutionBase< Output, point_output >::old_context protected inherited
Definition at line 354 of file generic_projector.h.
template<typename Output , void(FEMContext::*)(unsigned int, const Point &, Output &, const Real) const point_output> const Real libMesh::OldSolutionBase< Output, point_output >::out_of_elem_tol static protected inherited
Definition at line 356 of file generic_projector.h.
template<typename Output , void(FEMContext::*)(unsigned int, const Point &, Output &, const Real) const point_output> const System& libMesh::OldSolutionBase< Output, point_output >::sys protected inherited
Definition at line 353 of file generic_projector.h.
The documentation for this class was generated from the following file:
system_projection.C