libMesh: libMesh::Sphere Class Reference
SomeWebsiteLogo
libMesh::Sphere Class Reference
A geometric object representing a sphere.
#include <sphere.h>
Public Member Functions
Sphere ()
Sphere (const Point &c, const Real r)
Sphere (const Point &, const Point &, const Point &, const Point &)
Sphere (const Sphere &other_sphere)
~Sphere ()
void create_from_center_radius (const Point &c, const Real r)
bool intersects (const Sphere &other_sphere) const
Real distance (const Sphere &other_sphere) const
virtual bool above_surface (const Point &p) const override
virtual bool below_surface (const Point &p) const override
virtual bool on_surface (const Point &p) const override
virtual Point closest_point (const Point &p) const override
virtual Point unit_normal (const Point &p) const override
Real radius () const
Real & radius ()
const Point & center () const
Point & center ()
virtual Point surface_coords (const Point &cart) const override
virtual Point world_coords (const Point &sph) const override
Private Attributes
Point _cent
Real _rad
Detailed Description
A geometric object representing a sphere.
This class defines a sphere. It also computes coordinate transformations between cartesian and spherical coordinates. The spherical coordinates are valid in the ranges:
The coordinates are related as follows: is the angle in the xy plane starting with 0. from the positive x axis, is measured against the positive z axis.
*
*        \      | Z
*         \theta|
*          \    |    .
*           \   |   .
*            \  |  .
*             \ | .
*              \|.
* --------------+---------.---------
*              /|\       .          Y
*             /phi\     .
*            /  |  \   .
*           /   |   \ .
*          /.........\
*         /     |
*      X /
*
Author
Benjamin S. Kirk, Daniel Dreyer
Date
2002-2007
Definition at line 72 of file sphere.h.
Constructor & Destructor Documentation
Sphere() [1/4]
libMesh::Sphere::Sphere ()
Dummy Constructor.
Definition at line 36 of file sphere.C.
                 :
   _rad(-1.)
 {
 }
Sphere() [2/4]
libMesh::Sphere::Sphere (const Point & c, const Real r)
Constructs a sphere of radius r centered at c.
Definition at line 43 of file sphere.C.
References create_from_center_radius().
 {
   libmesh_assert_greater (r, 0.);
   this->create_from_center_radius (c, r);
 }
Sphere() [3/4]
libMesh::Sphere::Sphere (const Point & pa, const Point & pb, const Point & pc, const Point & pd)
Constructs a sphere connecting four points.
Definition at line 62 of file sphere.C.
References std::abs(), create_from_center_radius(), libMesh::TypeTensor< T >::det(), libMesh::TypeVector< T >::norm_sq(), and libMesh::Real.
 {
   Point pad = pa - pd;
   Point pbd = pb - pd;
   Point pcd = pc - pd;
   TensorValue<Real> T(pad,pbd,pcd);
   Real D = T.det();
   // The points had better not be coplanar
   libmesh_assert_greater (std::abs(D), 1e-12);
   Real e = 0.5*(pa.norm_sq() - pd.norm_sq());
   Real f = 0.5*(pb.norm_sq() - pd.norm_sq());
   Real g = 0.5*(pc.norm_sq() - pd.norm_sq());
   TensorValue<Real> T1(e,pad(1),pad(2),
                        f,pbd(1),pbd(2),
                        g,pcd(1),pcd(2));
   Real sx = T1.det()/D;
   TensorValue<Real> T2(pad(0),e,pad(2),
                        pbd(0),f,pbd(2),
                        pcd(0),g,pcd(2));
   Real sy = T2.det()/D;
   TensorValue<Real> T3(pad(0),pad(1),e,
                        pbd(0),pbd(1),f,
                        pcd(0),pcd(1),g);
   Real sz = T3.det()/D;
   Point c(sx,sy,sz);
   Real r = (c-pa).norm();
   this->create_from_center_radius(c,r);
 }
Sphere() [4/4]
libMesh::Sphere::Sphere (const Sphere & other_sphere)
Copy-constructor.
Definition at line 53 of file sphere.C.
References center(), create_from_center_radius(), and radius().
                                            :
   Surface()
 {
   this->create_from_center_radius (other_sphere.center(),
                                    other_sphere.radius());
 }
~Sphere()
libMesh::Sphere::~Sphere ()
Destructor. Does nothing at the moment.
Definition at line 105 of file sphere.C.
 {
 }
Member Function Documentation
above_surface()
bool libMesh::Sphere::above_surface (const Point & p) const override virtual
Returns
true if the point p is above the surface, false otherwise.
Implements libMesh::Surface.
Definition at line 140 of file sphere.C.
References center(), libMesh::TypeVector< T >::norm(), and radius().
Referenced by below_surface().
 {
   libmesh_assert_greater (this->radius(), 0.);
   // create a vector from the center to the point.
   const Point w = p - this->center();
   if (w.norm() > this->radius())
     return true;
   return false;
 }
below_surface()
bool libMesh::Sphere::below_surface (const Point & p) const override virtual
Returns
true if the point p is below the surface, false otherwise.
Implements libMesh::Surface.
Definition at line 155 of file sphere.C.
References above_surface(), and radius().
 {
   libmesh_assert_greater (this->radius(), 0.);
   return ( !this->above_surface (p) );
 }
center() [1/2]
const Point& libMesh::Sphere::center () const inline
Returns
The center of the sphere.
Definition at line 163 of file sphere.h.
References _cent.
Referenced by above_surface(), closest_point(), create_from_center_radius(), distance(), on_surface(), Sphere(), surface_coords(), unit_normal(), and world_coords().
 { return _cent; }
center() [2/2]
Point& libMesh::Sphere::center () inline
Returns
The center of the sphere.
Definition at line 168 of file sphere.h.
References _cent.
 { return _cent; }
closest_point()
Point libMesh::Sphere::closest_point (const Point & p) const override virtual
Returns
The closest point on the surface to point p.
Implements libMesh::Surface.
Definition at line 181 of file sphere.C.
References center(), radius(), and unit_normal().
 {
   libmesh_assert_greater (this->radius(), 0.);
   // get the normal from the surface in the direction
   // of p
   Point normal = this->unit_normal (p);
   // The closest point on the sphere is in the direction
   // of the normal a distance r from the center.
   const Point cp = this->center() + normal*this->radius();
   return cp;
 }
create_from_center_radius()
void libMesh::Sphere::create_from_center_radius (const Point & c, const Real r)
Defines a sphere of radius r centered at c.
Definition at line 111 of file sphere.C.
References center(), and radius().
Referenced by Sphere().
 {
   this->center() = c;
   this->radius() = r;
   libmesh_assert_greater (this->radius(), 0.);
 }
distance()
Real libMesh::Sphere::distance (const Sphere & other_sphere) const
Returns
The distance between the surface of this sphere and another sphere.
Definition at line 128 of file sphere.C.
References center(), radius(), and libMesh::Real.
Referenced by intersects().
 {
   libmesh_assert_greater ( this->radius(), 0. );
   libmesh_assert_greater ( other_sphere.radius(), 0. );
   const Real the_distance = (this->center() - other_sphere.center()).norm();
   return the_distance - (this->radius() + other_sphere.radius());
 }
intersects()
bool libMesh::Sphere::intersects (const Sphere & other_sphere) const
Returns
true if other_sphere intersects this sphere, false otherwise.
Definition at line 121 of file sphere.C.
References distance().
 {
   return distance(other_sphere) < 0 ? true : false;
 }
on_surface()
bool libMesh::Sphere::on_surface (const Point & p) const override virtual
Returns
true if the point p is on the surface, false otherwise.
Note
The definition of "on the surface" really means "very close" to account for roundoff error.
Implements libMesh::Surface.
Definition at line 164 of file sphere.C.
References std::abs(), center(), libMesh::TypeVector< T >::norm(), and radius().
 {
   libmesh_assert_greater (this->radius(), 0.);
   // Create a vector from the center to the point.
   const Point w = p - this->center();
   // if the size of that vector is the same as the radius() then
   // the point is on the surface.
   if (std::abs(w.norm() - this->radius()) < 1.e-10)
     return true;
   return false;
 }
radius() [1/2]
Real libMesh::Sphere::radius () const inline
Returns
The radius of the sphere.
Definition at line 153 of file sphere.h.
References _rad.
Referenced by above_surface(), below_surface(), closest_point(), create_from_center_radius(), distance(), on_surface(), Sphere(), and unit_normal().
 { return _rad; }
radius() [2/2]
Real& libMesh::Sphere::radius () inline
Returns
The radius of the sphere as a writable reference.
Definition at line 158 of file sphere.h.
References _rad.
 { return _rad; }
surface_coords()
Point libMesh::Sphere::surface_coords (const Point & cart) const inline override virtual
Returns
The spherical coordinates for the cartesian coordinates cart.
Reimplemented from libMesh::Surface.
Definition at line 201 of file sphere.h.
References center(), libMesh::TypeVector< T >::norm(), libMesh::pi, and libMesh::Real.
 {
   // constant translation in the origin
   const Point c (cart-this->center());
   // phi: special care, so that it gives 0..2pi results
   const Real phi = std::atan2(c(1), c(0));
   return Point(/* radius */ c.norm(),
                /* theta  */ std::atan2( std::sqrt( c(0)*c(0) + c(1)*c(1) ), c(2) ),
                /* phi    */ ( (phi < 0)  ?  2.*libMesh::pi+phi  :  phi ) );
 }
unit_normal()
Point libMesh::Sphere::unit_normal (const Point & p) const override virtual
Returns
A unit vector normal to the surface at point p.
Implements libMesh::Surface.
Definition at line 198 of file sphere.C.
References center(), radius(), and libMesh::TypeVector< T >::unit().
Referenced by closest_point().
 {
   libmesh_assert_greater (this->radius(), 0.);
   libmesh_assert_not_equal_to (p, this->center());
   // Create a vector from the center to the point
   Point n = p - this->center();
   return n.unit();
 }
world_coords()
Point libMesh::Sphere::world_coords (const Point & sph) const inline override virtual
Returns
The cartesian coordinates for the spherical coordinates sph.
Reimplemented from libMesh::Surface.
Definition at line 217 of file sphere.h.
References center(), and libMesh::Real.
 {
   const Real r     = sph(0);
   const Real theta = sph(1);
   const Real phi   = sph(2);
   // constant translation out of the origin
   return Point (/* x */ r*std::sin(theta)*std::cos(phi) + this->center()(0),
                 /* y */ r*std::sin(theta)*std::sin(phi) + this->center()(1),
                 /* z */ r*std::cos(theta)               + this->center()(2));
 }
Member Data Documentation
_cent
Point libMesh::Sphere::_cent private
The center of the sphere.
Definition at line 188 of file sphere.h.
Referenced by center().
_rad
Real libMesh::Sphere::_rad private
The radius of the sphere.
Definition at line 193 of file sphere.h.
Referenced by radius().
The documentation for this class was generated from the following files:
sphere.h
sphere.C