libMesh: libMesh::ReferenceCounter Class Reference
SomeWebsiteLogo
libMesh::ReferenceCounter Class Reference
Common base for all objects whose creations/destructions are counted.
#include <reference_counter.h>
Public Member Functions
~ReferenceCounter ()
Static Public Member Functions
static std::string get_info ()
static void print_info (std::ostream &out=libMesh::out)
static unsigned int n_objects ()
static void enable_print_counter_info ()
static void disable_print_counter_info ()
Protected Types
typedef std::map< std::string, std::pair< unsigned int, unsigned int > > Counts
Protected Member Functions
ReferenceCounter ()
ReferenceCounter (const ReferenceCounter &)
ReferenceCounter (ReferenceCounter &&other) noexcept
void increment_constructor_count (const std::string &name)
void increment_destructor_count (const std::string &name)
Static Protected Attributes
static Counts _counts
static Threads::atomic< unsigned int > _n_objects
static Threads::spin_mutex _mutex
static bool _enable_print_counter = true
Detailed Description
Common base for all objects whose creations/destructions are counted.
This is the base class for enabling reference counting. It should not be used by the user, thus it has a private constructor.
Author
Benjamin S. Kirk
Date
2002-2007
Definition at line 44 of file reference_counter.h.
Member Typedef Documentation
Counts
typedef std::map<std::string, std::pair<unsigned int, unsigned int> > libMesh::ReferenceCounter::Counts protected
Data structure to log the information. The log is identified by the class name.
Definition at line 117 of file reference_counter.h.
Constructor & Destructor Documentation
ReferenceCounter() [1/3]
libMesh::ReferenceCounter::ReferenceCounter () inline protected
Constructors. Protected so that you cannot instantiate a ReferenceCounter, only derive from it.
Definition at line 148 of file reference_counter.h.
References _n_objects.
 {
   ++_n_objects;
 }
ReferenceCounter() [2/3]
libMesh::ReferenceCounter::ReferenceCounter (const ReferenceCounter &) inline protected
Definition at line 155 of file reference_counter.h.
References _n_objects.
 {
   ++_n_objects;
 }
ReferenceCounter() [3/3]
libMesh::ReferenceCounter::ReferenceCounter (ReferenceCounter && other) inline protected noexcept
Move constructor, must be declared noexcept.
Definition at line 162 of file reference_counter.h.
References _n_objects.
 {
   ++_n_objects;
 }
~ReferenceCounter()
libMesh::ReferenceCounter::~ReferenceCounter () inline
Destructor.
Definition at line 169 of file reference_counter.h.
References _n_objects.
 {
   --_n_objects;
 }
Member Function Documentation
disable_print_counter_info()
void libMesh::ReferenceCounter::disable_print_counter_info () static
Definition at line 106 of file reference_counter.C.
References _enable_print_counter.
Referenced by libMesh::LibMeshInit::LibMeshInit().
 {
   _enable_print_counter = false;
   return;
 }
enable_print_counter_info()
void libMesh::ReferenceCounter::enable_print_counter_info () static
Methods to enable/disable the reference counter output from print_info()
Definition at line 100 of file reference_counter.C.
References _enable_print_counter.
 {
   _enable_print_counter = true;
   return;
 }
get_info()
std::string libMesh::ReferenceCounter::get_info () static
Gets a string containing the reference information.
Definition at line 47 of file reference_counter.C.
References _counts, and libMesh::Quality::name().
Referenced by print_info().
 {
 #if defined(LIBMESH_ENABLE_REFERENCE_COUNTING) && defined(DEBUG)
   std::ostringstream oss;
   oss << '\n'
       << " ---------------------------------------------------------------------------- \n"
       << "| Reference count information                                                |\n"
       << " ---------------------------------------------------------------------------- \n";
   for (const auto & pr : _counts)
     {
       const std::string name(pr.first);
       const unsigned int creations    = pr.second.first;
       const unsigned int destructions = pr.second.second;
       oss << "| " << name << " reference count information:\n"
           << "|  Creations:    " << creations    << '\n'
           << "|  Destructions: " << destructions << '\n';
     }
   oss << " ---------------------------------------------------------------------------- \n";
   return oss.str();
 #else
   return "";
 #endif
 }
increment_constructor_count()
void libMesh::ReferenceCounter::increment_constructor_count (const std::string & name) inline protected
Increments the construction counter. Should be called in the constructor of any derived class that will be reference counted.
Definition at line 181 of file reference_counter.h.
References _counts, libMesh::Quality::name(), and libMesh::Threads::spin_mtx.
Referenced by libMesh::ReferenceCountedObject< RBParametrized >::ReferenceCountedObject().
 {
   Threads::spin_mutex::scoped_lock lock(Threads::spin_mtx);
   std::pair<unsigned int, unsigned int> & p = _counts[name];
   p.first++;
 }
increment_destructor_count()
void libMesh::ReferenceCounter::increment_destructor_count (const std::string & name) inline protected
Increments the destruction counter. Should be called in the destructor of any derived class that will be reference counted.
Definition at line 194 of file reference_counter.h.
References _counts, libMesh::Quality::name(), and libMesh::Threads::spin_mtx.
Referenced by libMesh::ReferenceCountedObject< RBParametrized >::~ReferenceCountedObject().
 {
   Threads::spin_mutex::scoped_lock lock(Threads::spin_mtx);
   std::pair<unsigned int, unsigned int> & p = _counts[name];
   p.second++;
 }
n_objects()
static unsigned int libMesh::ReferenceCounter::n_objects () inline static
Prints the number of outstanding (created, but not yet destroyed) objects.
Definition at line 83 of file reference_counter.h.
References _n_objects.
   { return _n_objects; }
print_info()
void libMesh::ReferenceCounter::print_info (std::ostream & out = libMesh::out) static
Prints the reference information, by default to libMesh::out.
Definition at line 87 of file reference_counter.C.
References _enable_print_counter, and get_info().
 {
   if (_enable_print_counter)
     out_stream << ReferenceCounter::get_info();
 }
Member Data Documentation
_counts
ReferenceCounter::Counts libMesh::ReferenceCounter::_counts static protected
Actually holds the data.
Definition at line 122 of file reference_counter.h.
Referenced by get_info(), increment_constructor_count(), and increment_destructor_count().
_enable_print_counter
bool libMesh::ReferenceCounter::_enable_print_counter = true static protected
Flag to control whether reference count information is printed when print_info is called.
Definition at line 141 of file reference_counter.h.
Referenced by disable_print_counter_info(), enable_print_counter_info(), and print_info().
_mutex
Threads::spin_mutex libMesh::ReferenceCounter::_mutex static protected
Mutual exclusion object to enable thread-safe reference counting.
Definition at line 135 of file reference_counter.h.
_n_objects
Threads::atomic< unsigned int > libMesh::ReferenceCounter::_n_objects static protected
The number of objects. Print the reference count information when the number returns to 0.
Definition at line 130 of file reference_counter.h.
Referenced by n_objects(), ReferenceCounter(), and ~ReferenceCounter().
The documentation for this class was generated from the following files:
reference_counter.h
reference_counter.C