libMesh: libMesh::CompositeFEMFunction< Output > Class Template Reference
SomeWebsiteLogo
libMesh::CompositeFEMFunction< Output > Class Template Reference
FEMFunction which is a function of another function.
#include <composite_fem_function.h>
Public Member Functions
CompositeFEMFunction ()=default
CompositeFEMFunction (CompositeFEMFunction &&)=default
CompositeFEMFunction & operator= (CompositeFEMFunction &&)=default
CompositeFEMFunction (const CompositeFEMFunction &)=delete
CompositeFEMFunction & operator= (const CompositeFEMFunction &)=delete
virtual ~CompositeFEMFunction ()=default
void attach_subfunction (const FEMFunctionBase< Output > &f, const std::vector< unsigned int > &index_map)
virtual Output operator() (const FEMContext &c, const Point &p, const Real time=0) override
virtual void operator() (const FEMContext &c, const Point &p, const Real time, DenseVector< Output > &output) override
virtual Output component (const FEMContext &c, unsigned int i, const Point &p, Real time) override
virtual std::unique_ptr< FEMFunctionBase< Output > > clone () const override
unsigned int n_subfunctions () const
unsigned int n_components () const
virtual void init_context (const FEMContext &)
void operator() (const FEMContext &, const Point &p, DenseVector< Output > &output)
Private Attributes
std::vector< std::unique_ptr< FEMFunctionBase< Output > > > subfunctions
std::vector< std::vector< unsigned int > > index_maps
std::vector< std::pair< unsigned int, unsigned int > > reverse_index_map
Detailed Description
template<typename Output = Number>
class libMesh::CompositeFEMFunction< Output >
FEMFunction which is a function of another function.
FEMFunction which is a function of another function.
Author
Roy Stogner
Date
2012
Definition at line 43 of file composite_fem_function.h.
Constructor & Destructor Documentation
CompositeFEMFunction() [1/3]
template<typename Output = Number> libMesh::CompositeFEMFunction< Output >::CompositeFEMFunction () explicit default
Referenced by libMesh::CompositeFEMFunction< Output >::clone().
CompositeFEMFunction() [2/3]
template<typename Output = Number> libMesh::CompositeFEMFunction< Output >::CompositeFEMFunction (CompositeFEMFunction< Output > &&) default
This class can be default move constructed and assigned.
CompositeFEMFunction() [3/3]
template<typename Output = Number> libMesh::CompositeFEMFunction< Output >::CompositeFEMFunction (const CompositeFEMFunction< Output > &) delete
This class contains unique_ptr members so it can't be default copied or assigned.
~CompositeFEMFunction()
template<typename Output = Number> virtual libMesh::CompositeFEMFunction< Output >::~CompositeFEMFunction () virtual default
The subfunctions vector is automatically cleaned up.
Member Function Documentation
attach_subfunction()
template<typename Output = Number> void libMesh::CompositeFEMFunction< Output >::attach_subfunction (const FEMFunctionBase< Output > & f, const std::vector< unsigned int > & index_map) inline
Attach a new subfunction, along with a map from the indices of that subfunction to the indices of the global function. (*this)(index_map[i]) will return f(i).
Definition at line 72 of file composite_fem_function.h.
References libMesh::FEMFunctionBase< Output >::clone(), libMesh::CompositeFEMFunction< Output >::index_maps, libMesh::invalid_uint, libMesh::CompositeFEMFunction< Output >::reverse_index_map, and libMesh::CompositeFEMFunction< Output >::subfunctions.
Referenced by libMesh::CompositeFEMFunction< Output >::clone().
   {
     const unsigned int subfunction_index =
       cast_int<unsigned int>(subfunctions.size());
     libmesh_assert_equal_to(subfunctions.size(), index_maps.size());
     subfunctions.push_back(f.clone());
     index_maps.push_back(index_map);
     unsigned int max_index =
       *std::max_element(index_map.begin(), index_map.end());
     if (max_index >= reverse_index_map.size())
       reverse_index_map.resize
         (max_index+1, std::make_pair(libMesh::invalid_uint,
                                      libMesh::invalid_uint));
     for (std::size_t j=0; j != index_map.size(); ++j)
       {
         libmesh_assert_less(index_map[j], reverse_index_map.size());
         libmesh_assert_equal_to(reverse_index_map[index_map[j]].first,
                                 libMesh::invalid_uint);
         libmesh_assert_equal_to(reverse_index_map[index_map[j]].second,
                                 libMesh::invalid_uint);
         reverse_index_map[index_map[j]] =
           std::make_pair(subfunction_index, j);
       }
   }
clone()
template<typename Output = Number> virtual std::unique_ptr<FEMFunctionBase<Output> > libMesh::CompositeFEMFunction< Output >::clone () const inline override virtual
Returns
A new copy of the function.
The new copy should be as "deep" as necessary to allow independent destruction and simultaneous evaluations of the copies in different threads.
Implements libMesh::FEMFunctionBase< Output >.
Definition at line 148 of file composite_fem_function.h.
References libMesh::CompositeFEMFunction< Output >::attach_subfunction(), libMesh::CompositeFEMFunction< Output >::CompositeFEMFunction(), libMesh::CompositeFEMFunction< Output >::index_maps, and libMesh::CompositeFEMFunction< Output >::subfunctions.
   {
     CompositeFEMFunction * returnval = new CompositeFEMFunction();
     for (std::size_t i=0; i != subfunctions.size(); ++i)
       returnval->attach_subfunction(*subfunctions[i], index_maps[i]);
     return std::unique_ptr<FEMFunctionBase<Output>> (returnval);
   }
component()
template<typename Output = Number> virtual Output libMesh::CompositeFEMFunction< Output >::component (const FEMContext & context, unsigned int i, const Point & p, Real time) inline override virtual
Returns
The vector component i at coordinate p and time time.
Note
Subclasses aren't required to override this, since the default implementation is based on the full vector evaluation, which is often correct.
Subclasses are recommended to override this, since the default implementation is based on a vector evaluation, which is usually unnecessarily inefficient.
Reimplemented from libMesh::FEMFunctionBase< Output >.
Definition at line 131 of file composite_fem_function.h.
References libMesh::invalid_uint, libMesh::CompositeFEMFunction< Output >::reverse_index_map, and libMesh::CompositeFEMFunction< Output >::subfunctions.
Referenced by libMesh::CompositeFEMFunction< Output >::operator()().
   {
     if (i >= reverse_index_map.size() ||
         reverse_index_map[i].first == libMesh::invalid_uint)
       return 0;
     libmesh_assert_less(reverse_index_map[i].first,
                         subfunctions.size());
     libmesh_assert_not_equal_to(reverse_index_map[i].second,
                                 libMesh::invalid_uint);
     return subfunctions[reverse_index_map[i].first]->
       component(c, reverse_index_map[i].second, p, time);
   }
init_context()
template<typename Output = Number> virtual void libMesh::FEMFunctionBase< Output >::init_context (const FEMContext &) inline virtual inherited
Prepares a context object for use.
Most problems will want to reimplement this for efficiency, in order to call FE::get_*() as their particular function requires.
Reimplemented in libMesh::ParsedFEMFunction< Output >, and libMesh::ParsedFEMFunction< T >.
Definition at line 73 of file fem_function_base.h.
 {}
n_components()
template<typename Output = Number> unsigned int libMesh::CompositeFEMFunction< Output >::n_components () const inline
Definition at line 161 of file composite_fem_function.h.
References libMesh::CompositeFEMFunction< Output >::reverse_index_map.
   {
     return reverse_index_map.size();
   }
n_subfunctions()
template<typename Output = Number> unsigned int libMesh::CompositeFEMFunction< Output >::n_subfunctions () const inline
Definition at line 156 of file composite_fem_function.h.
References libMesh::CompositeFEMFunction< Output >::subfunctions.
   {
     return subfunctions.size();
   }
operator()() [1/3]
template<typename Output > void libMesh::FEMFunctionBase< Output >::operator() (const FEMContext & context, const Point & p, DenseVector< Output > & output) inline inherited
Evaluation function for time-independent vector-valued functions. Sets output values in the passed-in output DenseVector.
Definition at line 145 of file fem_function_base.h.
 {
   // Call the time-dependent function with t=0.
   this->operator()(context, p, 0., output);
 }
operator()() [2/3]
template<typename Output = Number> virtual Output libMesh::CompositeFEMFunction< Output >::operator() (const FEMContext & , const Point & p, const Real time = 0) inline override virtual
Returns
The scalar function value at coordinate p and time time, which defaults to zero.
Pure virtual, so you have to override it.
Implements libMesh::FEMFunctionBase< Output >.
Definition at line 102 of file composite_fem_function.h.
References libMesh::CompositeFEMFunction< Output >::component().
   {
     return this->component(c,0,p,time);
   }
operator()() [3/3]
template<typename Output = Number> virtual void libMesh::CompositeFEMFunction< Output >::operator() (const FEMContext & , const Point & p, const Real time, DenseVector< Output > & output) inline override virtual
Evaluation function for time-dependent vector-valued functions. Sets output values in the passed-in output DenseVector.
Pure virtual, so you have to override it.
Implements libMesh::FEMFunctionBase< Output >.
Definition at line 109 of file composite_fem_function.h.
References libMesh::CompositeFEMFunction< Output >::index_maps, libMesh::DenseVector< T >::resize(), libMesh::CompositeFEMFunction< Output >::reverse_index_map, libMesh::DenseVector< T >::size(), libMesh::CompositeFEMFunction< Output >::subfunctions, and libMesh::DenseVector< T >::zero().
   {
     libmesh_assert_greater_equal (output.size(),
                                   reverse_index_map.size());
     // Necessary in case we have output components not covered by
     // any subfunctions
     output.zero();
     DenseVector<Output> temp;
     for (std::size_t i=0; i != subfunctions.size(); ++i)
       {
         temp.resize(cast_int<unsigned int>(index_maps[i].size()));
         (*subfunctions[i])(c, p, time, temp);
         for (unsigned int j=0; j != temp.size(); ++j)
           output(index_maps[i][j]) = temp(j);
       }
   }
operator=() [1/2]
template<typename Output = Number> CompositeFEMFunction& libMesh::CompositeFEMFunction< Output >::operator= (CompositeFEMFunction< Output > &&) default
operator=() [2/2]
template<typename Output = Number> CompositeFEMFunction& libMesh::CompositeFEMFunction< Output >::operator= (const CompositeFEMFunction< Output > &) delete
Member Data Documentation
index_maps
template<typename Output = Number> std::vector<std::vector<unsigned int> > libMesh::CompositeFEMFunction< Output >::index_maps private
Definition at line 171 of file composite_fem_function.h.
Referenced by libMesh::CompositeFEMFunction< Output >::attach_subfunction(), libMesh::CompositeFEMFunction< Output >::clone(), and libMesh::CompositeFEMFunction< Output >::operator()().
reverse_index_map
template<typename Output = Number> std::vector<std::pair<unsigned int, unsigned int> > libMesh::CompositeFEMFunction< Output >::reverse_index_map private
Definition at line 174 of file composite_fem_function.h.
Referenced by libMesh::CompositeFEMFunction< Output >::attach_subfunction(), libMesh::CompositeFEMFunction< Output >::component(), libMesh::CompositeFEMFunction< Output >::n_components(), and libMesh::CompositeFEMFunction< Output >::operator()().
subfunctions
template<typename Output = Number> std::vector<std::unique_ptr<FEMFunctionBase<Output> > > libMesh::CompositeFEMFunction< Output >::subfunctions private
Definition at line 168 of file composite_fem_function.h.
Referenced by libMesh::CompositeFEMFunction< Output >::attach_subfunction(), libMesh::CompositeFEMFunction< Output >::clone(), libMesh::CompositeFEMFunction< Output >::component(), libMesh::CompositeFEMFunction< Output >::n_subfunctions(), and libMesh::CompositeFEMFunction< Output >::operator()().
The documentation for this class was generated from the following file:
composite_fem_function.h