libMesh: libMesh::Parallel::StandardType< VectorValue< T > > Class Template Reference
SomeWebsiteLogo
libMesh::Parallel::StandardType< VectorValue< T > > Class Template Reference
#include <parallel_algebra.h>
Public Member Functions
StandardType (const VectorValue< T > *example=nullptr)
StandardType (const StandardType< VectorValue< T >> &t)
~StandardType ()
operator const data_type & () const
operator data_type & ()
void commit ()
void free ()
Protected Attributes
data_type _datatype
Detailed Description
template<typename T>
class libMesh::Parallel::StandardType< VectorValue< T > >
Definition at line 111 of file parallel_algebra.h.
Constructor & Destructor Documentation
StandardType() [1/2]
template<typename T > libMesh::Parallel::StandardType< VectorValue< T > >::StandardType (const VectorValue< T > * example = nullptr) inline explicit
Definition at line 115 of file parallel_algebra.h.
References libMesh::Parallel::DataType::_datatype.
{
     // We need an example for MPI_Address to use
     VectorValue<T> * ex;
     std::unique_ptr<VectorValue<T>> temp;
     if (example)
       ex = const_cast<VectorValue<T> *>(example);
     else
       {
         temp.reset(new VectorValue<T>());
         ex = temp.get();
       }
 #ifdef LIBMESH_HAVE_MPI
     StandardType<T> T_type(&((*ex)(0)));
     int blocklength = LIBMESH_DIM;
     MPI_Aint displs, start;
     MPI_Datatype tmptype, type = T_type;
     libmesh_call_mpi
       (MPI_Get_address (ex, &start));
     libmesh_call_mpi
       (MPI_Get_address (&((*ex)(0)), &displs));
     // subtract off offset to first value from the beginning of the structure
     displs -= start;
     // create a prototype structure
     libmesh_call_mpi
       (MPI_Type_create_struct (1, &blocklength, &displs, &type,
                                &tmptype));
     libmesh_call_mpi
       (MPI_Type_commit (&tmptype));
     // resize the structure type to account for padding, if any
     libmesh_call_mpi
       (MPI_Type_create_resized (tmptype, 0,
                                 sizeof(VectorValue<T>),
                                 &_datatype));
     libmesh_call_mpi
       (MPI_Type_commit (&_datatype));
     libmesh_call_mpi
       (MPI_Type_free (&tmptype));
 #endif // #ifdef LIBMESH_HAVE_MPI
   }
StandardType() [2/2]
template<typename T > libMesh::Parallel::StandardType< VectorValue< T > >::StandardType (const StandardType< VectorValue< T >> & t) inline
Definition at line 163 of file parallel_algebra.h.
References libMesh::Parallel::DataType::_datatype.
     : DataType()
   {
 #ifdef LIBMESH_HAVE_MPI
     libmesh_call_mpi (MPI_Type_dup (t._datatype, &_datatype));
 #endif
   }
~StandardType()
template<typename T > libMesh::Parallel::StandardType< VectorValue< T > >::~StandardType () inline
Definition at line 171 of file parallel_algebra.h.
References libMesh::Parallel::DataType::free().
 { this->free(); }
Member Function Documentation
commit()
void libMesh::Parallel::DataType::commit () inline inherited
Definition at line 103 of file data_type.h.
References libMesh::Parallel::DataType::_datatype.
Referenced by libMesh::Parallel::DataType::DataType(), libMesh::Parallel::StandardType< std::pair< T1, T2 > >::StandardType(), and libMesh::Parallel::StandardType< std::tuple< Types... > >::StandardType().
   {
     libmesh_call_mpi
       (MPI_Type_commit (&_datatype));
   }
free()
void libMesh::Parallel::DataType::free () inline inherited
Definition at line 109 of file data_type.h.
References libMesh::Parallel::DataType::_datatype.
Referenced by libMesh::Parallel::StandardType< Hilbert::HilbertIndices >::~StandardType(), libMesh::Parallel::StandardType< TypeVector< T > >::~StandardType(), ~StandardType(), libMesh::Parallel::StandardType< std::pair< T1, T2 > >::~StandardType(), libMesh::Parallel::StandardType< Point >::~StandardType(), libMesh::Parallel::StandardType< std::tuple< Types... > >::~StandardType(), libMesh::Parallel::StandardType< std::complex< T > >::~StandardType(), libMesh::Parallel::StandardType< TypeTensor< T > >::~StandardType(), and libMesh::Parallel::StandardType< TensorValue< T > >::~StandardType().
   {
     libmesh_call_mpi
       (MPI_Type_free (&_datatype));
   }
operator const data_type &()
libMesh::Parallel::DataType::operator const data_type & () const inline inherited
Definition at line 91 of file data_type.h.
References libMesh::Parallel::DataType::_datatype.
   { return _datatype; }
operator data_type &()
libMesh::Parallel::DataType::operator data_type & () inline inherited
Definition at line 94 of file data_type.h.
References libMesh::Parallel::DataType::_datatype.
   { return _datatype; }
Member Data Documentation
_datatype
data_type libMesh::Parallel::DataType::_datatype protected inherited
Definition at line 117 of file data_type.h.
Referenced by libMesh::Parallel::DataType::commit(), libMesh::Parallel::DataType::DataType(), libMesh::Parallel::DataType::free(), libMesh::Parallel::DataType::operator const data_type &(), libMesh::Parallel::DataType::operator data_type &(), libMesh::Parallel::DataType::operator=(), libMesh::Parallel::StandardType< TypeVector< T > >::StandardType(), libMesh::Parallel::StandardType< Hilbert::HilbertIndices >::StandardType(), StandardType(), libMesh::Parallel::StandardType< std::pair< T1, T2 > >::StandardType(), libMesh::Parallel::StandardType< Point >::StandardType(), and libMesh::Parallel::StandardType< std::tuple< Types... > >::StandardType().
The documentation for this class was generated from the following file:
parallel_algebra.h