libMesh: libMesh::FEMContext Class Reference
SomeWebsiteLogo
libMesh::FEMContext Class Reference
#include <fem_context.h>
Classes
struct FENeeded
Public Types
enum AlgebraicType {
NONE = 0, DOFS_ONLY, CURRENT, OLD,
OLD_DOFS_ONLY
}
typedef const DenseSubVector< Number > &(DiffContext::* diff_subsolution_getter) (unsigned int) const
typedef std::map< const NumericVector< Number > *, std::pair< DenseVector< Number >, std::vector< std::unique_ptr< DenseSubVector< Number > > > > >::iterator localized_vectors_iterator
Public Member Functions
FEMContext (const System &sys)
FEMContext (const System &sys, int extra_quadrature_order)
virtual ~FEMContext ()
bool has_side_boundary_id (boundary_id_type id) const
std::vector< boundary_id_type > side_boundary_ids () const
void side_boundary_ids (std::vector< boundary_id_type > &vec_to_fill) const
Number interior_value (unsigned int var, unsigned int qp) const
Number side_value (unsigned int var, unsigned int qp) const
Number point_value (unsigned int var, const Point &p) const
Gradient interior_gradient (unsigned int var, unsigned int qp) const
Gradient side_gradient (unsigned int var, unsigned int qp) const
Gradient point_gradient (unsigned int var, const Point &p) const
Tensor interior_hessian (unsigned int var, unsigned int qp) const
Tensor side_hessian (unsigned int var, unsigned int qp) const
Tensor point_hessian (unsigned int var, const Point &p) const
Number fixed_interior_value (unsigned int var, unsigned int qp) const
Number fixed_side_value (unsigned int var, unsigned int qp) const
Number fixed_point_value (unsigned int var, const Point &p) const
Gradient fixed_interior_gradient (unsigned int var, unsigned int qp) const
Gradient fixed_side_gradient (unsigned int var, unsigned int qp) const
Gradient fixed_point_gradient (unsigned int var, const Point &p) const
Tensor fixed_interior_hessian (unsigned int var, unsigned int qp) const
Tensor fixed_side_hessian (unsigned int var, unsigned int qp) const
Tensor fixed_point_hessian (unsigned int var, const Point &p) const
template<typename OutputShape >
void get_element_fe (unsigned int var, FEGenericBase< OutputShape > *&fe) const
FEBase * get_element_fe (unsigned int var) const
template<typename OutputShape >
void get_element_fe (unsigned int var, FEGenericBase< OutputShape > *&fe, unsigned short dim) const
FEBase * get_element_fe (unsigned int var, unsigned short dim) const
template<typename OutputShape >
void get_side_fe (unsigned int var, FEGenericBase< OutputShape > *&fe) const
FEBase * get_side_fe (unsigned int var) const
template<typename OutputShape >
void get_side_fe (unsigned int var, FEGenericBase< OutputShape > *&fe, unsigned short dim) const
FEBase * get_side_fe (unsigned int var, unsigned short dim) const
template<typename OutputShape >
void get_edge_fe (unsigned int var, FEGenericBase< OutputShape > *&fe) const
FEBase * get_edge_fe (unsigned int var) const
template<typename OutputType >
void interior_value (unsigned int var, unsigned int qp, OutputType &u) const
template<typename OutputType >
void interior_values (unsigned int var, const NumericVector< Number > &_system_vector, std::vector< OutputType > &interior_values_vector) const
template<typename OutputType >
void side_value (unsigned int var, unsigned int qp, OutputType &u) const
template<typename OutputType >
void side_values (unsigned int var, const NumericVector< Number > &_system_vector, std::vector< OutputType > &side_values_vector) const
template<typename OutputType >
void point_value (unsigned int var, const Point &p, OutputType &u, const Real tolerance=TOLERANCE) const
template<typename OutputType >
void interior_gradient (unsigned int var, unsigned int qp, OutputType &du) const
template<typename OutputType >
void interior_gradients (unsigned int var, const NumericVector< Number > &_system_vector, std::vector< OutputType > &interior_gradients_vector) const
template<typename OutputType >
void side_gradient (unsigned int var, unsigned int qp, OutputType &du) const
template<typename OutputType >
void side_gradients (unsigned int var, const NumericVector< Number > &_system_vector, std::vector< OutputType > &side_gradients_vector) const
template<typename OutputType >
void point_gradient (unsigned int var, const Point &p, OutputType &grad_u, const Real tolerance=TOLERANCE) const
template<typename OutputType >
void interior_hessian (unsigned int var, unsigned int qp, OutputType &d2u) const
template<typename OutputType >
void interior_hessians (unsigned int var, const NumericVector< Number > &_system_vector, std::vector< OutputType > &d2u_vals) const
template<typename OutputType >
void side_hessian (unsigned int var, unsigned int qp, OutputType &d2u) const
template<typename OutputType >
void side_hessians (unsigned int var, const NumericVector< Number > &_system_vector, std::vector< OutputType > &d2u_vals) const
template<typename OutputType >
void point_hessian (unsigned int var, const Point &p, OutputType &hess_u, const Real tolerance=TOLERANCE) const
template<typename OutputType >
void interior_rate (unsigned int var, unsigned int qp, OutputType &u) const
template<typename OutputType >
void side_rate (unsigned int var, unsigned int qp, OutputType &u) const
template<typename OutputType >
void point_rate (unsigned int var, const Point &p, OutputType &u) const
template<typename OutputType >
void interior_accel (unsigned int var, unsigned int qp, OutputType &u) const
template<typename OutputType >
void side_accel (unsigned int var, unsigned int qp, OutputType &u) const
template<typename OutputType >
void point_accel (unsigned int var, const Point &p, OutputType &u) const
template<typename OutputType >
void fixed_interior_value (unsigned int var, unsigned int qp, OutputType &u) const
template<typename OutputType >
void fixed_side_value (unsigned int var, unsigned int qp, OutputType &u) const
template<typename OutputType >
void fixed_point_value (unsigned int var, const Point &p, OutputType &u, const Real tolerance=TOLERANCE) const
template<typename OutputType >
void fixed_interior_gradient (unsigned int var, unsigned int qp, OutputType &grad_u) const
template<typename OutputType >
void fixed_side_gradient (unsigned int var, unsigned int qp, OutputType &grad_u) const
template<typename OutputType >
void fixed_point_gradient (unsigned int var, const Point &p, OutputType &grad_u, const Real tolerance=TOLERANCE) const
template<typename OutputType >
void fixed_interior_hessian (unsigned int var, unsigned int qp, OutputType &hess_u) const
template<typename OutputType >
void fixed_side_hessian (unsigned int var, unsigned int qp, OutputType &hess_u) const
template<typename OutputType >
void fixed_point_hessian (unsigned int var, const Point &p, OutputType &hess_u, const Real tolerance=TOLERANCE) const
template<typename OutputType >
void interior_curl (unsigned int var, unsigned int qp, OutputType &curl_u) const
template<typename OutputType >
void point_curl (unsigned int var, const Point &p, OutputType &curl_u, const Real tolerance=TOLERANCE) const
template<typename OutputType >
void interior_div (unsigned int var, unsigned int qp, OutputType &div_u) const
virtual void elem_reinit (Real theta) override
virtual void elem_side_reinit (Real theta) override
virtual void elem_edge_reinit (Real theta) override
virtual void nonlocal_reinit (Real theta) override
virtual void pre_fe_reinit (const System &, const Elem *e)
virtual void elem_fe_reinit (const std::vector< Point > *const pts=nullptr)
virtual void side_fe_reinit ()
virtual void edge_fe_reinit ()
const QBase & get_element_qrule () const
const QBase & get_side_qrule () const
const QBase & get_element_qrule (unsigned short dim) const
const QBase & get_side_qrule (unsigned short dim) const
const QBase & get_edge_qrule () const
virtual void set_mesh_system (System *sys)
const System * get_mesh_system () const
System * get_mesh_system ()
unsigned int get_mesh_x_var () const
void set_mesh_x_var (unsigned int x_var)
unsigned int get_mesh_y_var () const
void set_mesh_y_var (unsigned int y_var)
unsigned int get_mesh_z_var () const
void set_mesh_z_var (unsigned int z_var)
bool has_elem () const
const Elem & get_elem () const
Elem & get_elem ()
unsigned char get_side () const
unsigned char get_edge () const
unsigned char get_dim () const
unsigned char get_elem_dim () const
const std::set< unsigned char > & elem_dimensions () const
void elem_position_set (Real theta)
void elem_position_get ()
void set_algebraic_type (const AlgebraicType atype)
AlgebraicType algebraic_type () const
void set_custom_solution (const NumericVector< Number > *custom_sol)
template<typename OutputShape >
FEGenericBase< OutputShape > * build_new_fe (const FEGenericBase< OutputShape > *fe, const Point &p, const Real tolerance=TOLERANCE) const
template<>
FEGenericBase< Real > * cached_fe (const unsigned int elem_dim, const FEType fe_type) const
template<>
FEGenericBase< RealGradient > * cached_fe (const unsigned int elem_dim, const FEType fe_type) const
unsigned int n_vars () const
const System & get_system () const
const DenseVector< Number > & get_elem_solution () const
DenseVector< Number > & get_elem_solution ()
const DenseSubVector< Number > & get_elem_solution (unsigned int var) const
DenseSubVector< Number > & get_elem_solution (unsigned int var)
const DenseVector< Number > & get_elem_solution_rate () const
DenseVector< Number > & get_elem_solution_rate ()
const DenseSubVector< Number > & get_elem_solution_rate (unsigned int var) const
DenseSubVector< Number > & get_elem_solution_rate (unsigned int var)
const DenseVector< Number > & get_elem_solution_accel () const
DenseVector< Number > & get_elem_solution_accel ()
const DenseSubVector< Number > & get_elem_solution_accel (unsigned int var) const
DenseSubVector< Number > & get_elem_solution_accel (unsigned int var)
const DenseVector< Number > & get_elem_fixed_solution () const
DenseVector< Number > & get_elem_fixed_solution ()
const DenseSubVector< Number > & get_elem_fixed_solution (unsigned int var) const
DenseSubVector< Number > & get_elem_fixed_solution (unsigned int var)
const DenseVector< Number > & get_elem_residual () const
DenseVector< Number > & get_elem_residual ()
const DenseSubVector< Number > & get_elem_residual (unsigned int var) const
DenseSubVector< Number > & get_elem_residual (unsigned int var)
const DenseMatrix< Number > & get_elem_jacobian () const
DenseMatrix< Number > & get_elem_jacobian ()
const DenseSubMatrix< Number > & get_elem_jacobian (unsigned int var1, unsigned int var2) const
DenseSubMatrix< Number > & get_elem_jacobian (unsigned int var1, unsigned int var2)
const std::vector< Number > & get_qois () const
std::vector< Number > & get_qois ()
const std::vector< DenseVector< Number > > & get_qoi_derivatives () const
std::vector< DenseVector< Number > > & get_qoi_derivatives ()
const DenseSubVector< Number > & get_qoi_derivatives (std::size_t qoi, unsigned int var) const
DenseSubVector< Number > & get_qoi_derivatives (std::size_t qoi, unsigned int var)
const std::vector< dof_id_type > & get_dof_indices () const
std::vector< dof_id_type > & get_dof_indices ()
const std::vector< dof_id_type > & get_dof_indices (unsigned int var) const
std::vector< dof_id_type > & get_dof_indices (unsigned int var)
unsigned int n_dof_indices () const
unsigned int n_dof_indices (unsigned int var) const
Real get_system_time () const
Real get_time () const
void set_time (Real time_in)
Real get_elem_solution_derivative () const
Real get_elem_solution_rate_derivative () const
Real get_elem_solution_accel_derivative () const
Real get_fixed_solution_derivative () const
bool is_adjoint () const
bool & is_adjoint ()
void set_deltat_pointer (Real *dt)
Real get_deltat_value ()
void add_localized_vector (NumericVector< Number > &localized_vector, const System &sys)
DenseVector< Number > & get_localized_vector (const NumericVector< Number > &localized_vector)
const DenseVector< Number > & get_localized_vector (const NumericVector< Number > &localized_vector) const
DenseSubVector< Number > & get_localized_subvector (const NumericVector< Number > &localized_vector, unsigned int var)
const DenseSubVector< Number > & get_localized_subvector (const NumericVector< Number > &localized_vector, unsigned int var) const
Public Attributes
System * _mesh_sys
unsigned int _mesh_x_var
unsigned int _mesh_y_var
unsigned int _mesh_z_var
unsigned char side
unsigned char edge
Real time
const Real system_time
Real elem_solution_derivative
Real elem_solution_rate_derivative
Real elem_solution_accel_derivative
Real fixed_solution_derivative
Protected Member Functions
template<typename OutputShape >
FEGenericBase< OutputShape > * cached_fe (const unsigned int elem_dim, const FEType fe_type) const
void set_elem (const Elem *e)
template<typename OutputType , typename FENeeded< OutputType >::value_getter fe_getter, diff_subsolution_getter subsolution_getter>
void some_value (unsigned int var, unsigned int qp, OutputType &u) const
template<typename OutputType , typename FENeeded< OutputType >::grad_getter fe_getter, diff_subsolution_getter subsolution_getter>
void some_gradient (unsigned int var, unsigned int qp, OutputType &u) const
template<typename OutputType , typename FENeeded< OutputType >::hess_getter fe_getter, diff_subsolution_getter subsolution_getter>
void some_hessian (unsigned int var, unsigned int qp, OutputType &u) const
Protected Attributes
AlgebraicType _atype
const NumericVector< Number > * _custom_solution
std::unique_ptr< FEGenericBase< Real > > _real_fe
std::unique_ptr< FEGenericBase< RealGradient > > _real_grad_fe
bool _real_fe_is_inf
bool _real_grad_fe_is_inf
std::vector< std::map< FEType, std::unique_ptr< FEAbstract > > > _element_fe
std::vector< std::map< FEType, std::unique_ptr< FEAbstract > > > _side_fe
std::map< FEType, std::unique_ptr< FEAbstract > > _edge_fe
std::vector< std::vector< FEAbstract * > > _element_fe_var
std::vector< std::vector< FEAbstract * > > _side_fe_var
std::vector< FEAbstract * > _edge_fe_var
const BoundaryInfo & _boundary_info
const Elem * _elem
unsigned char _dim
unsigned char _elem_dim
std::set< unsigned char > _elem_dims
std::vector< std::unique_ptr< QBase > > _element_qrule
std::vector< std::unique_ptr< QBase > > _side_qrule
std::unique_ptr< QBase > _edge_qrule
int _extra_quadrature_order
std::map< const NumericVector< Number > *, std::pair< DenseVector< Number >, std::vector< std::unique_ptr< DenseSubVector< Number > > > > > _localized_vectors
DenseVector< Number > _elem_solution
std::vector< std::unique_ptr< DenseSubVector< Number > > > _elem_subsolutions
DenseVector< Number > _elem_solution_rate
std::vector< std::unique_ptr< DenseSubVector< Number > > > _elem_subsolution_rates
DenseVector< Number > _elem_solution_accel
std::vector< std::unique_ptr< DenseSubVector< Number > > > _elem_subsolution_accels
DenseVector< Number > _elem_fixed_solution
std::vector< std::unique_ptr< DenseSubVector< Number > > > _elem_fixed_subsolutions
DenseVector< Number > _elem_residual
DenseMatrix< Number > _elem_jacobian
std::vector< Number > _elem_qoi
std::vector< DenseVector< Number > > _elem_qoi_derivative
std::vector< std::vector< std::unique_ptr< DenseSubVector< Number > > > > _elem_qoi_subderivatives
std::vector< std::unique_ptr< DenseSubVector< Number > > > _elem_subresiduals
std::vector< std::vector< std::unique_ptr< DenseSubMatrix< Number > > > > _elem_subjacobians
std::vector< dof_id_type > _dof_indices
std::vector< std::vector< dof_id_type > > _dof_indices_var
Private Member Functions
void init_internal_data (const System &sys)
void _do_elem_position_set (Real theta)
void _update_time_from_system (Real theta)
Detailed Description
This class provides all data required for a physics package (e.g. an FEMSystem subclass) to perform local element residual and jacobian integrations.
This class is part of the new DifferentiableSystem framework, which is still experimental. Users of this framework should beware of bugs and future API changes.
Author
Roy H. Stogner
Date
2009
Definition at line 61 of file fem_context.h.
Member Typedef Documentation
diff_subsolution_getter
typedef const DenseSubVector<Number>&(DiffContext::* libMesh::FEMContext::diff_subsolution_getter) (unsigned int) const
Helper typedef to simplify refactoring
Definition at line 1030 of file fem_context.h.
localized_vectors_iterator
typedef std::map<const NumericVector<Number> *, std::pair<DenseVector<Number>, std::vector<std::unique_ptr<DenseSubVector<Number> > > > >::iterator libMesh::DiffContext::localized_vectors_iterator inherited
Typedef for the localized_vectors iterator
Definition at line 544 of file diff_context.h.
Member Enumeration Documentation
AlgebraicType
enum libMesh::FEMContext::AlgebraicType
Enum describing what data to use when initializing algebraic structures on each element.
Enumerator
NONE
DOFS_ONLY
CURRENT
OLD
OLD_DOFS_ONLY
Definition at line 933 of file fem_context.h.
                      { NONE = 0,  // Do not reinitialize dof_indices
                        DOFS_ONLY, // Reinitialize dof_indices, not
                                   // algebraic structures
                        CURRENT,   // Use dof_indices, current solution
                        OLD,       // Use old_dof_indices, custom solution
                        OLD_DOFS_ONLY}; // Reinitialize old_dof_indices, not
Constructor & Destructor Documentation
FEMContext() [1/2]
libMesh::FEMContext::FEMContext (const System & sys) explicit
Constructor. Allocates some but fills no data structures.
Definition at line 37 of file fem_context.C.
References init_internal_data().
   : DiffContext(sys),
     _mesh_sys(nullptr),
     _mesh_x_var(0),
     _mesh_y_var(0),
     _mesh_z_var(0),
     side(0), edge(0),
     _atype(CURRENT),
     _custom_solution(nullptr),
     _boundary_info(sys.get_mesh().get_boundary_info()),
     _elem(nullptr),
     _dim(cast_int<unsigned char>(sys.get_mesh().mesh_dimension())),
     _elem_dim(0), /* This will be reset in set_elem(). */
     _elem_dims(sys.get_mesh().elem_dimensions()),
     _element_qrule(4),
     _side_qrule(4),
     _extra_quadrature_order(sys.extra_quadrature_order)
 {
   init_internal_data(sys);
 }
FEMContext() [2/2]
libMesh::FEMContext::FEMContext (const System & sys, int extra_quadrature_order) explicit
Constructor. Specify the extra quadrature order instead of getting it from sys.
Definition at line 58 of file fem_context.C.
References init_internal_data().
   : DiffContext(sys),
     _mesh_sys(nullptr),
     _mesh_x_var(0),
     _mesh_y_var(0),
     _mesh_z_var(0),
     side(0), edge(0),
     _atype(CURRENT),
     _custom_solution(nullptr),
     _boundary_info(sys.get_mesh().get_boundary_info()),
     _elem(nullptr),
     _dim(cast_int<unsigned char>(sys.get_mesh().mesh_dimension())),
     _elem_dim(0), /* This will be reset in set_elem(). */
     _elem_dims(sys.get_mesh().elem_dimensions()),
     _element_qrule(4),
     _side_qrule(4),
     _extra_quadrature_order(extra_quadrature_order)
 {
   init_internal_data(sys);
 }
~FEMContext()
libMesh::FEMContext::~FEMContext () virtual
Destructor.
Definition at line 183 of file fem_context.C.
 {
 }
Member Function Documentation
_do_elem_position_set()
void libMesh::FEMContext::_do_elem_position_set (Real theta) private
Uses the coordinate data specified by mesh_*_position configuration to set the geometry of elem to the value it would take after a fraction theta of a timestep.
This does the work of elem_position_set, but isn't safe to call without _mesh_sys/etc. defined first.
Definition at line 1476 of file fem_context.C.
References _mesh_sys, get_elem(), get_elem_dim(), libMesh::DiffContext::get_elem_solution(), get_element_fe(), get_mesh_x_var(), get_mesh_y_var(), get_mesh_z_var(), libMesh::invalid_uint, libMesh::LAGRANGE, libMesh::libmesh_real(), n_nodes, libMesh::Elem::n_nodes(), and libMesh::n_threads().
Referenced by elem_position_set().
 {
   // This is too expensive to call unless we've been asked to move the mesh
   libmesh_assert (_mesh_sys);
   // This will probably break with threading when two contexts are
   // operating on elements which share a node
   libmesh_assert_equal_to (libMesh::n_threads(), 1);
   // If the coordinate data is in our own system, it's already
   // been set up for us, and we can ignore our input parameter theta
   //  if (_mesh_sys == this->number())
   //    {
   unsigned int n_nodes = this->get_elem().n_nodes();
 #ifndef NDEBUG
   const unsigned char dim = this->get_elem_dim();
   // For simplicity we demand that mesh coordinates be stored
   // in a format that allows a direct copy
   libmesh_assert(this->get_mesh_x_var() == libMesh::invalid_uint ||
                  (this->get_element_fe(this->get_mesh_x_var(), dim)->get_fe_type().family
                   == LAGRANGE &&
                   this->get_elem_solution(this->get_mesh_x_var()).size() == n_nodes));
   libmesh_assert(this->get_mesh_y_var() == libMesh::invalid_uint ||
                  (this->get_element_fe(this->get_mesh_y_var(), dim)->get_fe_type().family
                   == LAGRANGE &&
                   this->get_elem_solution(this->get_mesh_y_var()).size() == n_nodes));
   libmesh_assert(this->get_mesh_z_var() == libMesh::invalid_uint ||
                  (this->get_element_fe(this->get_mesh_z_var(), dim)->get_fe_type().family
                   == LAGRANGE &&
                   this->get_elem_solution(this->get_mesh_z_var()).size() == n_nodes));
 #endif
   // Set the new point coordinates
   if (this->get_mesh_x_var() != libMesh::invalid_uint)
     for (unsigned int i=0; i != n_nodes; ++i)
       const_cast<Elem &>(this->get_elem()).point(i)(0) =
         libmesh_real(this->get_elem_solution(this->get_mesh_x_var())(i));
   if (this->get_mesh_y_var() != libMesh::invalid_uint)
     for (unsigned int i=0; i != n_nodes; ++i)
       const_cast<Elem &>(this->get_elem()).point(i)(1) =
         libmesh_real(this->get_elem_solution(this->get_mesh_y_var())(i));
   if (this->get_mesh_z_var() != libMesh::invalid_uint)
     for (unsigned int i=0; i != n_nodes; ++i)
       const_cast<Elem &>(this->get_elem()).point(i)(2) =
         libmesh_real(this->get_elem_solution(this->get_mesh_z_var())(i));
   //    }
   // FIXME - If the coordinate data is not in our own system, someone
   // had better get around to implementing that... - RHS
   //  else
   //    {
   //      libmesh_not_implemented();
   //    }
 }
_update_time_from_system()
void libMesh::FEMContext::_update_time_from_system (Real theta) private
Update the time in the context object for the given value of theta, based on the values of "time" and "deltat" stored in the system which created this context.
Definition at line 1774 of file fem_context.C.
References libMesh::DiffContext::get_deltat_value(), libMesh::DiffContext::get_system_time(), libMesh::Real, and libMesh::DiffContext::set_time().
Referenced by elem_edge_reinit(), elem_reinit(), elem_side_reinit(), and nonlocal_reinit().
 {
   // Update the "time" variable based on the value of theta.  For this
   // to work, we need to know the value of deltat, a pointer to which is now
   // stored by our parent DiffContext class.  Note: get_deltat_value() will
   // assert in debug mode if the requested pointer is nullptr.
   const Real deltat = this->get_deltat_value();
   this->set_time(theta*(this->get_system_time() + deltat) + (1.-theta)*this->get_system_time());
 }
add_localized_vector()
void libMesh::DiffContext::add_localized_vector (NumericVector< Number > & localized_vector, const System & sys) inherited
Adds a vector to the map of localized vectors. We can later evaluate interior_values, interior_gradients and side_values for these fields these vectors represent.
Definition at line 119 of file diff_context.C.
References libMesh::DiffContext::_localized_vectors, and libMesh::System::n_vars().
 {
   // Make an empty pair keyed with a reference to this _localized_vector
   _localized_vectors[&localized_vector] = std::make_pair(DenseVector<Number>(), std::vector<std::unique_ptr<DenseSubVector<Number>>>());
   unsigned int nv = sys.n_vars();
   _localized_vectors[&localized_vector].second.reserve(nv);
   // Fill the DenseSubVector with nv copies of DenseVector
   for (unsigned int i=0; i != nv; ++i)
     _localized_vectors[&localized_vector].second.emplace_back(libmesh_make_unique<DenseSubVector<Number>>(_localized_vectors[&localized_vector].first));
 }
algebraic_type()
AlgebraicType libMesh::FEMContext::algebraic_type () const inline
Definition at line 954 of file fem_context.h.
References _atype.
Referenced by build_new_fe(), and pre_fe_reinit().
 { return _atype; }
build_new_fe()
template<typename OutputShape > template FEGenericBase< RealGradient > * libMesh::FEMContext::build_new_fe (const FEGenericBase< OutputShape > * fe, const Point & p, const Real tolerance = TOLERANCE) const
Helper function to reduce some code duplication in the *_point_* methods.
Definition at line 1862 of file fem_context.C.
References algebraic_type(), libMesh::Elem::dim(), libMesh::FEType::family, get_elem(), libMesh::FEAbstract::get_fe_type(), has_elem(), libMesh::FEInterface::inverse_map(), libMesh::Elem::JUST_COARSENED, libMesh::Elem::JUST_REFINED, OLD, libMesh::FEType::order, libMesh::Elem::p_refinement_flag(), libMesh::FEAbstract::reinit(), and libMesh::SCALAR.
Referenced by fixed_point_gradient(), fixed_point_hessian(), fixed_point_value(), point_curl(), point_gradient(), point_hessian(), and point_value().
 {
   FEType fe_type = fe->get_fe_type();
   // If we don't have an Elem to evaluate on, then the only functions
   // we can sensibly evaluate are the scalar dofs which are the same
   // everywhere.
   libmesh_assert(this->has_elem() || fe_type.family == SCALAR);
 #ifdef LIBMESH_ENABLE_AMR
   if ((algebraic_type() == OLD) &&
       this->has_elem())
     {
       if (this->get_elem().p_refinement_flag() == Elem::JUST_REFINED)
         fe_type.order = static_cast<Order>(fe_type.order - 1);
       else if (this->get_elem().p_refinement_flag() == Elem::JUST_COARSENED)
         fe_type.order = static_cast<Order>(fe_type.order + 1);
     }
 #endif // LIBMESH_ENABLE_AMR
   const unsigned int elem_dim = this->has_elem() ? this->get_elem().dim() : 0;
   FEGenericBase<OutputShape>* fe_new = cached_fe<OutputShape>(elem_dim, fe_type);
   // Map the physical co-ordinates to the master co-ordinates using the inverse_map from fe_interface.h
   // Build a vector of point co-ordinates to send to reinit
   Point master_point = this->has_elem() ?
     FEInterface::inverse_map (elem_dim,
                               fe_type,
                               &this->get_elem(),
                               p,
                               tolerance) : Point(0);
   std::vector<Point> coor(1, master_point);
   // Reinitialize the element and compute the shape function values at coor
   if (this->has_elem())
     fe_new->reinit (&this->get_elem(), &coor);
   else
     // If !this->has_elem(), then we assume we are dealing with a SCALAR variable
     fe_new->reinit (nullptr, &coor);
   return fe_new;
 }
cached_fe() [1/3]
template<typename OutputShape > FEGenericBase<OutputShape>* libMesh::FEMContext::cached_fe (const unsigned int elem_dim, const FEType fe_type) const protected
cached_fe() [2/3]
template<> FEGenericBase<Real>* libMesh::FEMContext::cached_fe (const unsigned int elem_dim, const FEType fe_type) const
Definition at line 1789 of file fem_context.C.
References _real_fe, _real_fe_is_inf, libMesh::FEGenericBase< OutputType >::build(), libMesh::FEGenericBase< OutputType >::build_InfFE(), get_elem(), has_elem(), and libMesh::Elem::infinite().
 {
 #ifdef LIBMESH_ENABLE_INFINITE_ELEMENTS
   const bool fe_needs_inf =
     this->has_elem() && this->get_elem().infinite();
 #endif
   if (!_real_fe ||
       elem_dim != _real_fe->get_dim() ||
       fe_type != _real_fe->get_fe_type())
     _real_fe =
 #ifdef LIBMESH_ENABLE_INFINITE_ELEMENTS
       fe_needs_inf ?
       FEGenericBase<Real>::build_InfFE(elem_dim, fe_type) :
 #endif
       FEGenericBase<Real>::build(elem_dim, fe_type);
 #ifdef LIBMESH_ENABLE_INFINITE_ELEMENTS
   else if (fe_needs_inf && !_real_fe_is_inf)
     _real_fe =
       FEGenericBase<Real>::build_InfFE(elem_dim, fe_type);
   else if (!fe_needs_inf && _real_fe_is_inf)
     _real_fe =
       FEGenericBase<Real>::build(elem_dim, fe_type);
   _real_fe_is_inf =
     (this->has_elem() && this->get_elem().infinite());
 #endif
   return _real_fe.get();
 }
cached_fe() [3/3]
template<> FEGenericBase<RealGradient>* libMesh::FEMContext::cached_fe (const unsigned int elem_dim, const FEType fe_type) const
Definition at line 1825 of file fem_context.C.
References _real_grad_fe, _real_grad_fe_is_inf, libMesh::FEGenericBase< OutputType >::build(), libMesh::FEGenericBase< OutputType >::build_InfFE(), get_elem(), has_elem(), and libMesh::Elem::infinite().
 {
 #ifdef LIBMESH_ENABLE_INFINITE_ELEMENTS
   const bool fe_needs_inf =
     this->has_elem() && this->get_elem().infinite();
 #endif
   if (!_real_grad_fe ||
       elem_dim != _real_grad_fe->get_dim() ||
       fe_type != _real_grad_fe->get_fe_type())
     _real_grad_fe =
 #ifdef LIBMESH_ENABLE_INFINITE_ELEMENTS
       fe_needs_inf ?
       FEGenericBase<RealGradient>::build_InfFE(elem_dim, fe_type) :
 #endif
       FEGenericBase<RealGradient>::build(elem_dim, fe_type);
 #ifdef LIBMESH_ENABLE_INFINITE_ELEMENTS
   else if (fe_needs_inf && !_real_grad_fe_is_inf)
     _real_grad_fe =
       FEGenericBase<RealGradient>::build_InfFE(elem_dim, fe_type);
   else if (!fe_needs_inf && _real_grad_fe_is_inf)
     _real_grad_fe =
       FEGenericBase<RealGradient>::build(elem_dim, fe_type);
   _real_grad_fe_is_inf =
     (this->has_elem() && this->get_elem().infinite());
 #endif
   return _real_grad_fe.get();
 }
edge_fe_reinit()
void libMesh::FEMContext::edge_fe_reinit () virtual
Reinitializes edge FE objects on the current geometric element
Definition at line 1399 of file fem_context.C.
References _edge_fe, get_edge(), get_elem(), and get_elem_dim().
Referenced by elem_edge_reinit(), and libMesh::GenericProjector< FFunctor, GFunctor, FValue, ProjectionAction >::operator()().
 {
   libmesh_assert_equal_to (this->get_elem_dim(), 3);
   // Initialize all the interior FE objects on elem/edge.
   // Logging of FE::reinit is done in the FE functions
   for (auto & pr : _edge_fe)
     pr.second->edge_reinit(&(this->get_elem()), this->get_edge());
 }
elem_dimensions()
const std::set<unsigned char>& libMesh::FEMContext::elem_dimensions () const inline
Returns
Set of dimensions of elements present in the mesh at context initialization.
Definition at line 913 of file fem_context.h.
References _elem_dims.
Referenced by libMesh::LaplacianErrorEstimator::init_context(), libMesh::DiscontinuityMeasure::init_context(), libMesh::KellyErrorEstimator::init_context(), and libMesh::GenericProjector< FFunctor, GFunctor, FValue, ProjectionAction >::operator()().
   { return _elem_dims; }
elem_edge_reinit()
void libMesh::FEMContext::elem_edge_reinit (Real theta) override virtual
Resets the current time in the context. Additionally, reinitialize Elem and FE objects if there's a moving mesh present in the system such that the mesh is deformed to its position at .
Reimplemented from libMesh::DiffContext.
Definition at line 1337 of file fem_context.C.
References _mesh_sys, _update_time_from_system(), edge_fe_reinit(), and elem_position_set().
 {
   // Update the "time" variable of this context object
   this->_update_time_from_system(theta);
   // Handle a moving element if necessary
   if (_mesh_sys)
     {
       // FIXME - not threadsafe yet!
       elem_position_set(theta);
       edge_fe_reinit();
     }
 }
elem_fe_reinit()
void libMesh::FEMContext::elem_fe_reinit (const std::vector< Point > *const pts = nullptr) virtual
Reinitializes interior FE objects on the current geometric element
Definition at line 1362 of file fem_context.C.
References _element_fe, get_elem(), get_elem_dim(), and has_elem().
Referenced by elem_reinit(), libMesh::FEMSystem::mesh_position_set(), nonlocal_reinit(), and libMesh::GenericProjector< FFunctor, GFunctor, FValue, ProjectionAction >::operator()().
 {
   // Initialize all the interior FE objects on elem.
   // Logging of FE::reinit is done in the FE functions
   // We only reinit the FE objects for the current element
   // dimension
   const unsigned char dim = this->get_elem_dim();
   libmesh_assert( !_element_fe[dim].empty() );
   for (const auto & pr : _element_fe[dim])
     {
       if (this->has_elem())
         pr.second->reinit(&(this->get_elem()), pts);
       else
         // If !this->has_elem(), then we assume we are dealing with a SCALAR variable
         pr.second->reinit(nullptr);
     }
 }
elem_position_get()
void libMesh::FEMContext::elem_position_get ()
Uses the geometry of elem to set the coordinate data specified by mesh_*_position configuration.
Definition at line 1411 of file fem_context.C.
References _mesh_sys, libMesh::Elem::default_order(), get_elem(), get_elem_dim(), libMesh::DiffContext::get_elem_solution(), get_element_fe(), get_mesh_x_var(), get_mesh_y_var(), get_mesh_z_var(), libMesh::invalid_uint, libMesh::LAGRANGE, n_nodes, libMesh::Elem::n_nodes(), libMesh::n_threads(), and libMesh::Elem::point().
Referenced by libMesh::FEMSystem::mesh_position_get().
 {
   // This is too expensive to call unless we've been asked to move the mesh
   libmesh_assert (_mesh_sys);
   // This will probably break with threading when two contexts are
   // operating on elements which share a node
   libmesh_assert_equal_to (libMesh::n_threads(), 1);
   // If the coordinate data is in our own system, it's already
   // been set up for us
   //  if (_mesh_sys == this->number())
   //    {
   unsigned int n_nodes = this->get_elem().n_nodes();
 #ifndef NDEBUG
   const unsigned char dim = this->get_elem_dim();
   // For simplicity we demand that mesh coordinates be stored
   // in a format that allows a direct copy
   libmesh_assert(this->get_mesh_x_var() == libMesh::invalid_uint ||
                  (this->get_element_fe(this->get_mesh_x_var(), dim)->get_fe_type().family
                   == LAGRANGE &&
                   this->get_element_fe(this->get_mesh_x_var(), dim)->get_fe_type().order.get_order()
                   == this->get_elem().default_order()));
   libmesh_assert(this->get_mesh_y_var() == libMesh::invalid_uint ||
                  (this->get_element_fe(this->get_mesh_y_var(), dim)->get_fe_type().family
                   == LAGRANGE &&
                   this->get_element_fe(this->get_mesh_y_var(), dim)->get_fe_type().order.get_order()
                   == this->get_elem().default_order()));
   libmesh_assert(this->get_mesh_z_var() == libMesh::invalid_uint ||
                  (this->get_element_fe(this->get_mesh_z_var(), dim)->get_fe_type().family
                   == LAGRANGE &&
                   this->get_element_fe(this->get_mesh_z_var(), dim)->get_fe_type().order.get_order()
                   == this->get_elem().default_order()));
 #endif
   // Get degree of freedom coefficients from point coordinates
   if (this->get_mesh_x_var() != libMesh::invalid_uint)
     for (unsigned int i=0; i != n_nodes; ++i)
       (this->get_elem_solution(this->get_mesh_x_var()))(i) = this->get_elem().point(i)(0);
   if (this->get_mesh_y_var() != libMesh::invalid_uint)
     for (unsigned int i=0; i != n_nodes; ++i)
       (this->get_elem_solution(this->get_mesh_y_var()))(i) = this->get_elem().point(i)(1);
   if (this->get_mesh_z_var() != libMesh::invalid_uint)
     for (unsigned int i=0; i != n_nodes; ++i)
       (this->get_elem_solution(this->get_mesh_z_var()))(i) = this->get_elem().point(i)(2);
   //    }
   // FIXME - If the coordinate data is not in our own system, someone
   // had better get around to implementing that... - RHS
   //  else
   //    {
   //      libmesh_not_implemented();
   //    }
 }
elem_position_set()
void libMesh::FEMContext::elem_position_set (Real theta) inline
Uses the coordinate data specified by mesh_*_position configuration to set the geometry of elem to the value it would take after a fraction theta of a timestep.
Definition at line 1197 of file fem_context.h.
References _do_elem_position_set(), and _mesh_sys.
Referenced by elem_edge_reinit(), elem_reinit(), elem_side_reinit(), and libMesh::FEMSystem::mesh_position_set().
 {
   if (_mesh_sys)
     this->_do_elem_position_set(theta);
 }
elem_reinit()
void libMesh::FEMContext::elem_reinit (Real theta) override virtual
Resets the current time in the context. Additionally, reinitialize Elem and FE objects if there's a moving mesh present in the system such that the mesh is deformed to its position at .
Reimplemented from libMesh::DiffContext.
Definition at line 1298 of file fem_context.C.
References _mesh_sys, _update_time_from_system(), elem_fe_reinit(), elem_position_set(), and libMesh::n_threads().
 {
   // Update the "time" variable of this context object
   this->_update_time_from_system(theta);
   // Handle a moving element if necessary.
   if (_mesh_sys)
     {
       // We assume that the ``default'' state
       // of the mesh is its final, theta=1.0
       // position, so we don't bother with
       // mesh motion in that case.
       if (theta != 1.0)
         {
           // FIXME - ALE is not threadsafe yet!
           libmesh_assert_equal_to (libMesh::n_threads(), 1);
           elem_position_set(theta);
         }
       elem_fe_reinit();
     }
 }
elem_side_reinit()
void libMesh::FEMContext::elem_side_reinit (Real theta) override virtual
Resets the current time in the context. Additionally, reinitialize Elem and FE objects if there's a moving mesh present in the system such that the mesh is deformed to its position at .
Reimplemented from libMesh::DiffContext.
Definition at line 1322 of file fem_context.C.
References _mesh_sys, _update_time_from_system(), elem_position_set(), and side_fe_reinit().
 {
   // Update the "time" variable of this context object
   this->_update_time_from_system(theta);
   // Handle a moving element if necessary
   if (_mesh_sys)
     {
       // FIXME - not threadsafe yet!
       elem_position_set(theta);
       side_fe_reinit();
     }
 }
fixed_interior_gradient() [1/2]
Gradient libMesh::FEMContext::fixed_interior_gradient (unsigned int var, unsigned int qp) const
Returns
The gradient of the fixed_solution variable var at the quadrature point qp on the current element interior.
Note
This API is currently present for backward compatibility.
Definition at line 976 of file fem_context.C.
 {
   Gradient du;
   this->fixed_interior_gradient( var, qp, du );
   return du;
 }
fixed_interior_gradient() [2/2]
template<typename OutputType > void libMesh::FEMContext::fixed_interior_gradient (unsigned int var, unsigned int qp, OutputType & grad_u) const
Returns
The gradient of the fixed_solution variable var at the quadrature point qp on the current element interior.
Note
This is the preferred API.
Definition at line 987 of file fem_context.C.
References libMesh::DiffContext::get_elem_fixed_solution(), get_element_fe(), and some_gradient().
 {
   this->some_gradient
     <OutputType,
      &FEMContext::get_element_fe
      <typename TensorTools::MakeReal
       <typename TensorTools::DecrementRank
        <OutputType>::type>::type>,
      &DiffContext::get_elem_fixed_solution>
     (var, qp, du);
 }
fixed_interior_hessian() [1/2]
Tensor libMesh::FEMContext::fixed_interior_hessian (unsigned int var, unsigned int qp) const
Returns
The hessian of the fixed_solution variable var at the quadrature point qp on the current element interior.
Note
This API is currently present for backward compatibility.
Definition at line 1003 of file fem_context.C.
 {
   Tensor d2u;
   this->fixed_interior_hessian( var, qp, d2u );
   return d2u;
 }
fixed_interior_hessian() [2/2]
template<typename OutputType > void libMesh::FEMContext::fixed_interior_hessian (unsigned int var, unsigned int qp, OutputType & hess_u) const
Returns
The hessian of the fixed_solution variable var at the quadrature point qp on the current element interior.
Note
This is the preferred API.
Definition at line 1014 of file fem_context.C.
References libMesh::DiffContext::get_elem_fixed_solution(), get_element_fe(), and some_hessian().
 {
   this->some_hessian<OutputType,
                      &FEMContext::get_element_fe
                      <typename TensorTools::MakeReal
                       <typename TensorTools::DecrementRank
                        <typename TensorTools::DecrementRank
                         <OutputType>::type>::type>::type>,
                      &DiffContext::get_elem_fixed_solution>(var, qp, d2u);
 }
fixed_interior_value() [1/2]
Number libMesh::FEMContext::fixed_interior_value (unsigned int var, unsigned int qp) const
Returns
The value of the fixed_solution variable var at the quadrature point qp on the current element interior.
Note
This API is currently present for backward compatibility.
Definition at line 953 of file fem_context.C.
 {
   Number u = 0.;
   this->fixed_interior_value( var, qp, u );
   return u;
 }
fixed_interior_value() [2/2]
template<typename OutputType > void libMesh::FEMContext::fixed_interior_value (unsigned int var, unsigned int qp, OutputType & u) const
Returns
The value of the fixed_solution variable var at the quadrature point qp on the current element interior.
Note
This is the preferred API.
Definition at line 965 of file fem_context.C.
References libMesh::DiffContext::get_elem_fixed_solution(), get_element_fe(), and some_value().
 {
   this->some_value<OutputType,
                    &FEMContext::get_element_fe
                    <typename TensorTools::MakeReal<OutputType>::type>,
                    &DiffContext::get_elem_fixed_solution>(var, qp, u);
 }
fixed_point_gradient() [1/2]
Gradient libMesh::FEMContext::fixed_point_gradient (unsigned int var, const Point & p) const
Returns
The gradient of the fixed_solution variable var at the physical point p on the current element.
Note
This API is currently present for backward compatibility.
Definition at line 1149 of file fem_context.C.
 {
   Gradient grad_u;
   this->fixed_point_gradient( var, p, grad_u );
   return grad_u;
 }
fixed_point_gradient() [2/2]
template<typename OutputType > void libMesh::FEMContext::fixed_point_gradient (unsigned int var, const Point & p, OutputType & grad_u, const Real tolerance = TOLERANCE) const
Returns
The gradient of the fixed_solution variable var at the physical point p on the current element.
Note
This is the preferred API.
Allows evaluation of points within a relative tolerance outside the element.
Definition at line 1161 of file fem_context.C.
References libMesh::DiffContext::_elem_fixed_subsolutions, build_new_fe(), libMesh::DiffContext::get_dof_indices(), get_elem_dim(), and libMesh::DiffContext::get_elem_fixed_solution().
 {
   typedef typename TensorTools::MakeReal
     <typename TensorTools::DecrementRank<OutputType>::type>::type
     OutputShape;
   // Get local-to-global dof index lookup
   const unsigned int n_dofs = cast_int<unsigned int>
     (this->get_dof_indices(var).size());
   // Get current local coefficients
   libmesh_assert_greater (_elem_fixed_subsolutions.size(), var);
   const DenseSubVector<Number> & coef = this->get_elem_fixed_solution(var);
   // Get finite element object
   FEGenericBase<OutputShape> * fe = nullptr;
   this->get_element_fe<OutputShape>( var, fe, this->get_elem_dim() );
   // Build a FE for calculating u(p)
   FEGenericBase<OutputShape> * fe_new =
     this->build_new_fe( fe, p, tolerance );
   // Get the values of the shape function derivatives
   const std::vector<std::vector<typename FEGenericBase<OutputShape>::OutputGradient>> &  dphi = fe_new->get_dphi();
   grad_u = 0.0;
   for (unsigned int l=0; l != n_dofs; l++)
     grad_u.add_scaled(dphi[l][0], coef(l));
   return;
 }
fixed_point_hessian() [1/2]
Tensor libMesh::FEMContext::fixed_point_hessian (unsigned int var, const Point & p) const
Returns
The hessian of the fixed_solution variable var at the physical point p on the current element.
Note
This API is currently present for backward compatibility.
Definition at line 1200 of file fem_context.C.
 {
   Tensor hess_u;
   this->fixed_point_hessian( var, p, hess_u );
   return hess_u;
 }
fixed_point_hessian() [2/2]
template<typename OutputType > void libMesh::FEMContext::fixed_point_hessian (unsigned int var, const Point & p, OutputType & hess_u, const Real tolerance = TOLERANCE) const
Returns
The hessian of the fixed_solution variable var at the physical point p on the current element.
Note
This is the preferred API.
Allows evaluation of points within a relative tolerance outside the element.
Definition at line 1212 of file fem_context.C.
References libMesh::DiffContext::_elem_fixed_subsolutions, build_new_fe(), libMesh::DiffContext::get_dof_indices(), get_elem_dim(), and libMesh::DiffContext::get_elem_fixed_solution().
 {
   typedef typename TensorTools::DecrementRank<OutputType>::type Rank1Decrement;
   typedef typename TensorTools::DecrementRank<Rank1Decrement>::type Rank2Decrement;
   typedef typename TensorTools::MakeReal<Rank2Decrement>::type OutputShape;
   // Get local-to-global dof index lookup
   const unsigned int n_dofs = cast_int<unsigned int>
     (this->get_dof_indices(var).size());
   // Get current local coefficients
   libmesh_assert_greater (_elem_fixed_subsolutions.size(), var);
   const DenseSubVector<Number> & coef = this->get_elem_fixed_solution(var);
   // Get finite element object
   FEGenericBase<OutputShape> * fe = nullptr;
   this->get_element_fe<OutputShape>( var, fe, this->get_elem_dim() );
   // Build a FE for calculating u(p)
   FEGenericBase<OutputShape> * fe_new =
     this->build_new_fe( fe, p, tolerance );
   // Get the values of the shape function derivatives
   const std::vector<std::vector<typename FEGenericBase<OutputShape>::OutputTensor>> &  d2phi = fe_new->get_d2phi();
   hess_u = 0.0;
   for (unsigned int l=0; l != n_dofs; l++)
     hess_u.add_scaled(d2phi[l][0], coef(l));
   return;
 }
fixed_point_value() [1/2]
Number libMesh::FEMContext::fixed_point_value (unsigned int var, const Point & p) const
Returns
The value of the fixed_solution variable var at the physical point p on the current element.
Note
This API is currently present for backward compatibility.
Definition at line 1103 of file fem_context.C.
 {
   Number u = 0.;
   this->fixed_point_value( var, p, u );
   return u;
 }
fixed_point_value() [2/2]
template<typename OutputType > void libMesh::FEMContext::fixed_point_value (unsigned int var, const Point & p, OutputType & u, const Real tolerance = TOLERANCE) const
Returns
The value of the fixed_solution variable var at the physical point p on the current element.
Note
This is the preferred API.
Allows evaluation of points within a relative tolerance outside the element.
Definition at line 1113 of file fem_context.C.
References libMesh::DiffContext::_elem_fixed_subsolutions, build_new_fe(), libMesh::DiffContext::get_dof_indices(), get_elem_dim(), and libMesh::DiffContext::get_elem_fixed_solution().
 {
   typedef typename TensorTools::MakeReal<OutputType>::type OutputShape;
   // Get local-to-global dof index lookup
   const unsigned int n_dofs = cast_int<unsigned int>
     (this->get_dof_indices(var).size());
   // Get current local coefficients
   libmesh_assert_greater (_elem_fixed_subsolutions.size(), var);
   const DenseSubVector<Number> & coef = this->get_elem_fixed_solution(var);
   // Get finite element object
   FEGenericBase<OutputShape> * fe = nullptr;
   this->get_element_fe<OutputShape>( var, fe, this->get_elem_dim() );
   // Build a FE for calculating u(p)
   FEGenericBase<OutputShape> * fe_new =
     this->build_new_fe( fe, p, tolerance );
   // Get the values of the shape function derivatives
   const std::vector<std::vector<OutputShape>> &  phi = fe_new->get_phi();
   u = 0.;
   for (unsigned int l=0; l != n_dofs; l++)
     u += phi[l][0] * coef(l);
   return;
 }
fixed_side_gradient() [1/2]
Gradient libMesh::FEMContext::fixed_side_gradient (unsigned int var, unsigned int qp) const
Returns
The gradient of the fixed_solution variable var at the quadrature point qp on the current element side.
Note
This API is currently present for backward compatibility.
Definition at line 1053 of file fem_context.C.
 {
   Gradient du;
   this->fixed_side_gradient( var, qp, du );
   return du;
 }
fixed_side_gradient() [2/2]
template<typename OutputType > void libMesh::FEMContext::fixed_side_gradient (unsigned int var, unsigned int qp, OutputType & grad_u) const
Returns
The gradient of the fixed_solution variable var at the quadrature point qp on the current element side.
Note
This is the preferred API.
Definition at line 1064 of file fem_context.C.
References libMesh::DiffContext::get_elem_fixed_solution(), get_side_fe(), and some_gradient().
 {
   this->some_gradient<OutputType,
                       &FEMContext::get_side_fe
                       <typename TensorTools::MakeReal
                        <typename TensorTools::DecrementRank
                         <OutputType>::type>::type>,
                       &DiffContext::get_elem_fixed_solution>(var, qp, du);
 }
fixed_side_hessian() [1/2]
Tensor libMesh::FEMContext::fixed_side_hessian (unsigned int var, unsigned int qp) const
Returns
The hessian of the fixed_solution variable var at the quadrature point qp on the current element side.
Note
This API is currently present for backward compatibility.
Definition at line 1078 of file fem_context.C.
 {
   Tensor d2u;
   this->fixed_side_hessian( var, qp, d2u );
   return d2u;
 }
fixed_side_hessian() [2/2]
template<typename OutputType > void libMesh::FEMContext::fixed_side_hessian (unsigned int var, unsigned int qp, OutputType & hess_u) const
Returns
The hessian of the fixed_solution variable var at the quadrature point qp on the current element side.
Note
This is the preferred API.
Definition at line 1088 of file fem_context.C.
References libMesh::DiffContext::get_elem_fixed_solution(), get_side_fe(), and some_hessian().
 {
   this->some_hessian<OutputType,
                      &FEMContext::get_side_fe
                      <typename TensorTools::MakeReal
                       <typename TensorTools::DecrementRank
                        <typename TensorTools::DecrementRank
                         <OutputType>::type>::type>::type>,
                      &DiffContext::get_elem_fixed_solution>(var, qp, d2u);
 }
fixed_side_value() [1/2]
Number libMesh::FEMContext::fixed_side_value (unsigned int var, unsigned int qp) const
Returns
The value of the fixed_solution variable var at the quadrature point qp on the current element side.
Note
This API is currently present for backward compatibility.
Definition at line 1029 of file fem_context.C.
 {
   Number u = 0.;
   this->fixed_side_value( var, qp, u );
   return u;
 }
fixed_side_value() [2/2]
template<typename OutputType > void libMesh::FEMContext::fixed_side_value (unsigned int var, unsigned int qp, OutputType & u) const
Returns
The value of the fixed_solution variable var at the quadrature point qp on the current element side.
Note
This is the preferred API.
Definition at line 1040 of file fem_context.C.
References libMesh::DiffContext::get_elem_fixed_solution(), get_side_fe(), and some_value().
 {
   this->some_value
     <OutputType,
      &FEMContext::get_side_fe
      <typename TensorTools::MakeReal<OutputType>::type>,
      &DiffContext::get_elem_fixed_solution>
     (var, qp, u);
 }
get_deltat_value()
Real libMesh::DiffContext::get_deltat_value () inherited
Returns
The value currently pointed to by this class's _deltat member
Definition at line 111 of file diff_context.C.
References libMesh::DiffContext::_deltat.
Referenced by _update_time_from_system().
 {
   libmesh_assert(_deltat);
   return *_deltat;
 }
get_dim()
unsigned char libMesh::FEMContext::get_dim () const inline
Accessor for cached mesh dimension. This is the largest dimension of the elements in the mesh. For the dimension of this->_elem, use get_elem_dim();
Definition at line 899 of file fem_context.h.
References _dim.
Referenced by get_element_fe(), get_side_fe(), and libMesh::DGFEMContext::neighbor_side_fe_reinit().
   { return this->_dim; }
get_dof_indices() [1/4]
const std::vector<dof_id_type>& libMesh::DiffContext::get_dof_indices () const inline inherited
Accessor for element dof indices
Definition at line 367 of file diff_context.h.
References libMesh::DiffContext::_dof_indices.
Referenced by libMesh::EulerSolver::_general_residual(), libMesh::Euler2Solver::_general_residual(), libMesh::NewmarkSolver::_general_residual(), libMesh::FirstOrderUnsteadySolver::compute_second_order_eqns(), fixed_point_gradient(), fixed_point_hessian(), fixed_point_value(), libMesh::VectorSetAction< Val >::insert(), libMesh::MatrixFillAction< ValIn, ValOut >::insert(), interior_curl(), interior_div(), interior_gradients(), interior_hessians(), interior_values(), libMesh::FEMSystem::mesh_position_get(), libMesh::DGFEMContext::neighbor_side_fe_reinit(), libMesh::FEMSystem::numerical_jacobian(), libMesh::GenericProjector< FFunctor, GFunctor, FValue, ProjectionAction >::operator()(), point_curl(), point_gradient(), point_hessian(), point_value(), pre_fe_reinit(), side_gradient(), side_gradients(), side_hessians(), side_values(), some_gradient(), some_hessian(), and some_value().
   { return _dof_indices; }
get_dof_indices() [2/4]
std::vector<dof_id_type>& libMesh::DiffContext::get_dof_indices () inline inherited
Non-const accessor for element dof indices
Definition at line 373 of file diff_context.h.
References libMesh::DiffContext::_dof_indices.
   { return _dof_indices; }
get_dof_indices() [3/4]
const std::vector<dof_id_type>& libMesh::DiffContext::get_dof_indices (unsigned int var) const inline inherited
Accessor for element dof indices of a particular variable corresponding to the index argument.
Definition at line 380 of file diff_context.h.
References libMesh::DiffContext::_dof_indices_var.
   {
     libmesh_assert_greater(_dof_indices_var.size(), var);
     return _dof_indices_var[var];
   }
get_dof_indices() [4/4]
std::vector<dof_id_type>& libMesh::DiffContext::get_dof_indices (unsigned int var) inline inherited
Accessor for element dof indices of a particular variable corresponding to the index argument.
Definition at line 390 of file diff_context.h.
References libMesh::DiffContext::_dof_indices_var.
   {
     libmesh_assert_greater(_dof_indices_var.size(), var);
     return _dof_indices_var[var];
   }
get_edge()
unsigned char libMesh::FEMContext::get_edge () const inline
Accessor for current edge of Elem object
Definition at line 891 of file fem_context.h.
References edge.
Referenced by edge_fe_reinit().
   { return edge; }
get_edge_fe() [1/2]
template<typename OutputShape > void libMesh::FEMContext::get_edge_fe (unsigned int var, FEGenericBase< OutputShape > *& fe) const inline
Accessor for edge (3D only!) finite element object for variable var.
Definition at line 1241 of file fem_context.h.
References _edge_fe_var.
Referenced by libMesh::GenericProjector< FFunctor, GFunctor, FValue, ProjectionAction >::operator()().
 {
   libmesh_assert_less ( var, _edge_fe_var.size() );
   fe = cast_ptr<FEGenericBase<OutputShape> *>( _edge_fe_var[var] );
 }
get_edge_fe() [2/2]
FEBase * libMesh::FEMContext::get_edge_fe (unsigned int var) const inline
Accessor for edge (3D only!) finite element object for scalar-valued variable var.
Definition at line 1248 of file fem_context.h.
References _edge_fe_var.
 {
   libmesh_assert_less ( var, _edge_fe_var.size() );
   return cast_ptr<FEBase *>( _edge_fe_var[var] );
 }
get_edge_qrule()
const QBase& libMesh::FEMContext::get_edge_qrule () const inline
Accessor for element edge quadrature rule.
Definition at line 794 of file fem_context.h.
References _edge_qrule.
   { return *(this->_edge_qrule); }
get_elem() [1/2]
const Elem& libMesh::FEMContext::get_elem () const inline
Accessor for current Elem object
Definition at line 871 of file fem_context.h.
References _elem.
Referenced by _do_elem_position_set(), build_new_fe(), cached_fe(), libMesh::OldSolutionBase< Output, point_output >::check_old_context(), edge_fe_reinit(), elem_fe_reinit(), elem_position_get(), has_side_boundary_id(), libMesh::FEMSystem::mesh_position_set(), libMesh::FEMSystem::numerical_jacobian(), pre_fe_reinit(), side_boundary_ids(), and side_fe_reinit().
   { libmesh_assert(this->_elem);
     return *(this->_elem); }
get_elem() [2/2]
Elem& libMesh::FEMContext::get_elem () inline
Accessor for current Elem object
Definition at line 878 of file fem_context.h.
References _elem.
   { libmesh_assert(this->_elem);
     return *(const_cast<Elem *>(this->_elem)); }
get_elem_dim()
unsigned char libMesh::FEMContext::get_elem_dim () const inline
Returns
The dimension of this->_elem. For mixed dimension meshes, this may be different from get_dim().
Definition at line 906 of file fem_context.h.
References _elem_dim.
Referenced by _do_elem_position_set(), edge_fe_reinit(), elem_fe_reinit(), elem_position_get(), fixed_point_gradient(), fixed_point_hessian(), fixed_point_value(), get_element_qrule(), get_side_qrule(), interior_curl(), interior_div(), interior_gradients(), interior_hessians(), interior_values(), point_curl(), point_gradient(), point_hessian(), point_value(), side_fe_reinit(), side_gradient(), side_gradients(), side_hessians(), side_values(), some_gradient(), some_hessian(), and some_value().
   { return _elem_dim; }
get_elem_fixed_solution() [1/4]
const DenseVector<Number>& libMesh::DiffContext::get_elem_fixed_solution () const inline inherited
Accessor for element fixed solution.
Definition at line 215 of file diff_context.h.
References libMesh::DiffContext::_elem_fixed_solution.
Referenced by libMesh::EulerSolver::_general_residual(), libMesh::Euler2Solver::_general_residual(), libMesh::SteadySolver::_general_residual(), libMesh::NewmarkSolver::_general_residual(), fixed_interior_gradient(), fixed_interior_hessian(), fixed_interior_value(), fixed_point_gradient(), fixed_point_hessian(), fixed_point_value(), fixed_side_gradient(), fixed_side_hessian(), fixed_side_value(), and pre_fe_reinit().
   { return _elem_fixed_solution; }
get_elem_fixed_solution() [2/4]
DenseVector<Number>& libMesh::DiffContext::get_elem_fixed_solution () inline inherited
Non-const accessor for element fixed solution.
Definition at line 221 of file diff_context.h.
References libMesh::DiffContext::_elem_fixed_solution.
   { return _elem_fixed_solution; }
get_elem_fixed_solution() [3/4]
const DenseSubVector<Number>& libMesh::DiffContext::get_elem_fixed_solution (unsigned int var) const inline inherited
Accessor for element fixed solution of a particular variable corresponding to the variable index argument.
Definition at line 228 of file diff_context.h.
References libMesh::DiffContext::_elem_fixed_subsolutions.
   {
     libmesh_assert_greater(_elem_fixed_subsolutions.size(), var);
     libmesh_assert(_elem_fixed_subsolutions[var]);
     return *(_elem_fixed_subsolutions[var]);
   }
get_elem_fixed_solution() [4/4]
DenseSubVector<Number>& libMesh::DiffContext::get_elem_fixed_solution (unsigned int var) inline inherited
Accessor for element fixed solution of a particular variable corresponding to the variable index argument.
Definition at line 239 of file diff_context.h.
References libMesh::DiffContext::_elem_fixed_subsolutions.
   {
     libmesh_assert_greater(_elem_fixed_subsolutions.size(), var);
     libmesh_assert(_elem_fixed_subsolutions[var]);
     return *(_elem_fixed_subsolutions[var]);
   }
get_elem_jacobian() [1/4]
const DenseMatrix<Number>& libMesh::DiffContext::get_elem_jacobian () const inline inherited
Const accessor for element Jacobian.
Definition at line 283 of file diff_context.h.
References libMesh::DiffContext::_elem_jacobian.
Referenced by libMesh::EulerSolver::_general_residual(), libMesh::Euler2Solver::_general_residual(), libMesh::NewmarkSolver::_general_residual(), libMesh::FEMSystem::assembly(), libMesh::FirstOrderUnsteadySolver::compute_second_order_eqns(), libMesh::EigenTimeSolver::element_residual(), libMesh::EigenTimeSolver::nonlocal_residual(), libMesh::FEMSystem::numerical_jacobian(), pre_fe_reinit(), and libMesh::EigenTimeSolver::side_residual().
   { return _elem_jacobian; }
get_elem_jacobian() [2/4]
DenseMatrix<Number>& libMesh::DiffContext::get_elem_jacobian () inline inherited
Non-const accessor for element Jacobian.
Definition at line 289 of file diff_context.h.
References libMesh::DiffContext::_elem_jacobian.
   { return _elem_jacobian; }
get_elem_jacobian() [3/4]
const DenseSubMatrix<Number>& libMesh::DiffContext::get_elem_jacobian (unsigned int var1, unsigned int var2) const inline inherited
Const accessor for element Jacobian of particular variables corresponding to the variable index arguments.
Definition at line 296 of file diff_context.h.
References libMesh::DiffContext::_elem_subjacobians.
   {
     libmesh_assert_greater(_elem_subjacobians.size(), var1);
     libmesh_assert_greater(_elem_subjacobians[var1].size(), var2);
     libmesh_assert(_elem_subjacobians[var1][var2]);
     return *(_elem_subjacobians[var1][var2]);
   }
get_elem_jacobian() [4/4]
DenseSubMatrix<Number>& libMesh::DiffContext::get_elem_jacobian (unsigned int var1, unsigned int var2) inline inherited
Non-const accessor for element Jacobian of particular variables corresponding to the variable index arguments.
Definition at line 308 of file diff_context.h.
References libMesh::DiffContext::_elem_subjacobians.
   {
     libmesh_assert_greater(_elem_subjacobians.size(), var1);
     libmesh_assert_greater(_elem_subjacobians[var1].size(), var2);
     libmesh_assert(_elem_subjacobians[var1][var2]);
     return *(_elem_subjacobians[var1][var2]);
   }
get_elem_residual() [1/4]
const DenseVector<Number>& libMesh::DiffContext::get_elem_residual () const inline inherited
Const accessor for element residual.
Definition at line 249 of file diff_context.h.
References libMesh::DiffContext::_elem_residual.
Referenced by libMesh::Euler2Solver::_general_residual(), libMesh::FEMSystem::assembly(), libMesh::FirstOrderUnsteadySolver::compute_second_order_eqns(), libMesh::FEMSystem::numerical_jacobian(), and pre_fe_reinit().
   { return _elem_residual; }
get_elem_residual() [2/4]
DenseVector<Number>& libMesh::DiffContext::get_elem_residual () inline inherited
Non-const accessor for element residual.
Definition at line 255 of file diff_context.h.
References libMesh::DiffContext::_elem_residual.
   { return _elem_residual; }
get_elem_residual() [3/4]
const DenseSubVector<Number>& libMesh::DiffContext::get_elem_residual (unsigned int var) const inline inherited
Const accessor for element residual of a particular variable corresponding to the variable index argument.
Definition at line 262 of file diff_context.h.
References libMesh::DiffContext::_elem_subresiduals.
   {
     libmesh_assert_greater(_elem_subresiduals.size(), var);
     libmesh_assert(_elem_subresiduals[var]);
     return *(_elem_subresiduals[var]);
   }
get_elem_residual() [4/4]
DenseSubVector<Number>& libMesh::DiffContext::get_elem_residual (unsigned int var) inline inherited
Non-const accessor for element residual of a particular variable corresponding to the variable index argument.
Definition at line 273 of file diff_context.h.
References libMesh::DiffContext::_elem_subresiduals.
   {
     libmesh_assert_greater(_elem_subresiduals.size(), var);
     libmesh_assert(_elem_subresiduals[var]);
     return *(_elem_subresiduals[var]);
   }
get_elem_solution() [1/4]
const DenseVector<Number>& libMesh::DiffContext::get_elem_solution () const inline inherited
Accessor for element solution.
Definition at line 111 of file diff_context.h.
References libMesh::DiffContext::_elem_solution.
Referenced by _do_elem_position_set(), libMesh::EulerSolver::_general_residual(), libMesh::Euler2Solver::_general_residual(), libMesh::SteadySolver::_general_residual(), libMesh::NewmarkSolver::_general_residual(), elem_position_get(), interior_curl(), interior_div(), interior_gradient(), interior_hessian(), interior_value(), libMesh::FEMSystem::mesh_position_get(), libMesh::FEMSystem::numerical_jacobian(), point_curl(), point_gradient(), point_hessian(), point_value(), pre_fe_reinit(), side_gradient(), side_hessian(), and side_value().
   { return _elem_solution; }
get_elem_solution() [2/4]
DenseVector<Number>& libMesh::DiffContext::get_elem_solution () inline inherited
Non-const accessor for element solution.
Definition at line 117 of file diff_context.h.
References libMesh::DiffContext::_elem_solution.
   { return _elem_solution; }
get_elem_solution() [3/4]
const DenseSubVector<Number>& libMesh::DiffContext::get_elem_solution (unsigned int var) const inline inherited
Accessor for element solution of a particular variable corresponding to the variable index argument.
Definition at line 124 of file diff_context.h.
References libMesh::DiffContext::_elem_subsolutions.
   {
     libmesh_assert_greater(_elem_subsolutions.size(), var);
     libmesh_assert(_elem_subsolutions[var]);
     return *(_elem_subsolutions[var]);
   }
get_elem_solution() [4/4]
DenseSubVector<Number>& libMesh::DiffContext::get_elem_solution (unsigned int var) inline inherited
Accessor for element solution of a particular variable corresponding to the variable index argument.
Definition at line 135 of file diff_context.h.
References libMesh::DiffContext::_elem_subsolutions.
   {
     libmesh_assert_greater(_elem_subsolutions.size(), var);
     libmesh_assert(_elem_subsolutions[var]);
     return *(_elem_subsolutions[var]);
   }
get_elem_solution_accel() [1/4]
const DenseVector<Number>& libMesh::DiffContext::get_elem_solution_accel () const inline inherited
Accessor for element solution accel of change w.r.t. time.
Definition at line 180 of file diff_context.h.
References libMesh::DiffContext::_elem_solution_accel.
Referenced by libMesh::NewmarkSolver::_general_residual(), interior_accel(), pre_fe_reinit(), libMesh::FirstOrderUnsteadySolver::prepare_accel(), and side_accel().
   { return _elem_solution_accel; }
get_elem_solution_accel() [2/4]
DenseVector<Number>& libMesh::DiffContext::get_elem_solution_accel () inline inherited
Non-const accessor for element solution accel of change w.r.t. time.
Definition at line 187 of file diff_context.h.
References libMesh::DiffContext::_elem_solution_accel.
   { return _elem_solution_accel; }
get_elem_solution_accel() [3/4]
const DenseSubVector<Number>& libMesh::DiffContext::get_elem_solution_accel (unsigned int var) const inline inherited
Accessor for element solution accel for a particular variable corresponding to the variable index argument.
Definition at line 194 of file diff_context.h.
References libMesh::DiffContext::_elem_subsolution_accels.
   {
     libmesh_assert_greater(_elem_subsolution_accels.size(), var);
     libmesh_assert(_elem_subsolution_accels[var]);
     return *(_elem_subsolution_accels[var]);
   }
get_elem_solution_accel() [4/4]
DenseSubVector<Number>& libMesh::DiffContext::get_elem_solution_accel (unsigned int var) inline inherited
Accessor for element solution accel for a particular variable corresponding to the variable index argument.
Definition at line 205 of file diff_context.h.
References libMesh::DiffContext::_elem_subsolution_accels.
   {
     libmesh_assert_greater(_elem_subsolution_accels.size(), var);
     libmesh_assert(_elem_subsolution_accels[var]);
     return *(_elem_subsolution_accels[var]);
   }
get_elem_solution_accel_derivative()
Real libMesh::DiffContext::get_elem_solution_accel_derivative () const inline inherited
The derivative of the current elem_solution_accel w.r.t. the unknown solution. Corresponding Jacobian contributions should be multiplied by this amount, or may be skipped if get_elem_solution_accel_derivative() is 0.
Definition at line 454 of file diff_context.h.
References libMesh::DiffContext::elem_solution_accel_derivative.
   { return elem_solution_accel_derivative; }
get_elem_solution_derivative()
Real libMesh::DiffContext::get_elem_solution_derivative () const inline inherited
The derivative of the current elem_solution w.r.t. the unknown solution. Corresponding Jacobian contributions should be multiplied by this amount, or may be skipped if get_elem_solution_derivative() is 0.
Definition at line 436 of file diff_context.h.
References libMesh::DiffContext::elem_solution_derivative.
Referenced by libMesh::FirstOrderUnsteadySolver::compute_second_order_eqns().
   { return elem_solution_derivative; }
get_elem_solution_rate() [1/4]
const DenseVector<Number>& libMesh::DiffContext::get_elem_solution_rate () const inline inherited
Accessor for element solution rate of change w.r.t. time.
Definition at line 145 of file diff_context.h.
References libMesh::DiffContext::_elem_solution_rate.
Referenced by libMesh::EulerSolver::_general_residual(), libMesh::Euler2Solver::_general_residual(), libMesh::NewmarkSolver::_general_residual(), interior_rate(), pre_fe_reinit(), libMesh::FirstOrderUnsteadySolver::prepare_accel(), and side_rate().
   { return _elem_solution_rate; }
get_elem_solution_rate() [2/4]
DenseVector<Number>& libMesh::DiffContext::get_elem_solution_rate () inline inherited
Non-const accessor for element solution rate of change w.r.t. time.
Definition at line 152 of file diff_context.h.
References libMesh::DiffContext::_elem_solution_rate.
   { return _elem_solution_rate; }
get_elem_solution_rate() [3/4]
const DenseSubVector<Number>& libMesh::DiffContext::get_elem_solution_rate (unsigned int var) const inline inherited
Accessor for element solution rate for a particular variable corresponding to the variable index argument.
Definition at line 159 of file diff_context.h.
References libMesh::DiffContext::_elem_subsolution_rates.
   {
     libmesh_assert_greater(_elem_subsolution_rates.size(), var);
     libmesh_assert(_elem_subsolution_rates[var]);
     return *(_elem_subsolution_rates[var]);
   }
get_elem_solution_rate() [4/4]
DenseSubVector<Number>& libMesh::DiffContext::get_elem_solution_rate (unsigned int var) inline inherited
Accessor for element solution rate for a particular variable corresponding to the variable index argument.
Definition at line 170 of file diff_context.h.
References libMesh::DiffContext::_elem_subsolution_rates.
   {
     libmesh_assert_greater(_elem_subsolution_rates.size(), var);
     libmesh_assert(_elem_subsolution_rates[var]);
     return *(_elem_subsolution_rates[var]);
   }
get_elem_solution_rate_derivative()
Real libMesh::DiffContext::get_elem_solution_rate_derivative () const inline inherited
The derivative of the current elem_solution_rate w.r.t. the unknown solution. Corresponding Jacobian contributions should be multiplied by this amount, or may be skipped if get_elem_solution_rate_derivative() is 0.
Definition at line 445 of file diff_context.h.
References libMesh::DiffContext::elem_solution_rate_derivative.
Referenced by libMesh::FirstOrderUnsteadySolver::compute_second_order_eqns(), and libMesh::FirstOrderUnsteadySolver::prepare_accel().
   { return elem_solution_rate_derivative; }
get_element_fe() [1/4]
template<typename OutputShape > void libMesh::FEMContext::get_element_fe (unsigned int var, FEGenericBase< OutputShape > *& fe) const inline
Accessor for interior finite element object for variable var for the largest dimension in the mesh. We default to the largest mesh dim because this method may be called before the Elem * is set in the FEMContext, e.g. in FEMSystem::init_context (or a subclass). If you have lower dimensional elements in the mesh and need to query for those FE objects, use the alternative get_element_fe method.
Definition at line 262 of file fem_context.h.
References get_dim().
Referenced by _do_elem_position_set(), libMesh::FirstOrderUnsteadySolver::compute_second_order_eqns(), elem_position_get(), fixed_interior_gradient(), fixed_interior_hessian(), fixed_interior_value(), get_element_fe(), libMesh::ParsedFEMFunction< T >::init_context(), libMesh::FEMSystem::init_context(), interior_accel(), interior_gradient(), interior_hessian(), interior_rate(), and libMesh::GenericProjector< FFunctor, GFunctor, FValue, ProjectionAction >::operator()().
   { this->get_element_fe<OutputShape>(var,fe,this->get_dim()); }
get_element_fe() [2/4]
FEBase* libMesh::FEMContext::get_element_fe (unsigned int var) const inline
Accessor for interior finite element object for scalar-valued variable var for the largest dimension in the mesh. We default to the largest mesh dim because this method may be called before the Elem * is set in the FEMContext, e.g. in FEMSystem::init_context (or a subclass). If you have lower dimensional elements in the mesh and need to query for those FE objects, use the alternative get_element_fe method.
Definition at line 273 of file fem_context.h.
References get_dim(), and get_element_fe().
   { return this->get_element_fe(var,this->get_dim()); }
get_element_fe() [3/4]
template<typename OutputShape > void libMesh::FEMContext::get_element_fe (unsigned int var, FEGenericBase< OutputShape > *& fe, unsigned short dim) const inline
Accessor for interior finite element object for variable var for dimension dim.
Definition at line 1205 of file fem_context.h.
References _element_fe_var.
 {
   libmesh_assert( !_element_fe_var[dim].empty() );
   libmesh_assert_less ( var, (_element_fe_var[dim].size() ) );
   fe = cast_ptr<FEGenericBase<OutputShape> *>( (_element_fe_var[dim][var] ) );
 }
get_element_fe() [4/4]
FEBase * libMesh::FEMContext::get_element_fe (unsigned int var, unsigned short dim) const inline
Accessor for interior finite element object for scalar-valued variable var for dimension dim.
Definition at line 1214 of file fem_context.h.
References _element_fe_var.
 {
   libmesh_assert( !_element_fe_var[dim].empty() );
   libmesh_assert_less ( var, (_element_fe_var[dim].size() ) );
   return cast_ptr<FEBase *>( (_element_fe_var[dim][var] ) );
 }
get_element_qrule() [1/2]
const QBase& libMesh::FEMContext::get_element_qrule () const inline
Accessor for element interior quadrature rule for the dimension of the current _elem.
Definition at line 765 of file fem_context.h.
References get_elem_dim().
Referenced by libMesh::FirstOrderUnsteadySolver::compute_second_order_eqns().
   { return this->get_element_qrule(this->get_elem_dim()); }
get_element_qrule() [2/2]
const QBase& libMesh::FEMContext::get_element_qrule (unsigned short dim) const inline
Accessor for element interior quadrature rule.
Definition at line 778 of file fem_context.h.
References _element_qrule.
   { libmesh_assert(_element_qrule[dim]);
     return *(this->_element_qrule[dim]); }
get_fixed_solution_derivative()
Real libMesh::DiffContext::get_fixed_solution_derivative () const inline inherited
The derivative of the current fixed_elem_solution w.r.t. the unknown solution. Corresponding Jacobian contributions should be multiplied by this amount, or may be skipped if get_fixed_elem_solution_derivative() is 0.
Definition at line 463 of file diff_context.h.
References libMesh::DiffContext::fixed_solution_derivative.
   { return fixed_solution_derivative; }
get_localized_subvector() [1/2]
DenseSubVector< Number > & libMesh::DiffContext::get_localized_subvector (const NumericVector< Number > & localized_vector, unsigned int var) inherited
Return a reference to DenseSubVector localization of localized_vector at variable var contained in the _localized_vectors map
Definition at line 148 of file diff_context.C.
References libMesh::DiffContext::_localized_vectors.
Referenced by interior_gradients(), interior_hessians(), interior_values(), side_gradients(), side_hessians(), and side_values().
 {
   return *_localized_vectors[&localized_vector].second[var];
 }
get_localized_subvector() [2/2]
const DenseSubVector< Number > & libMesh::DiffContext::get_localized_subvector (const NumericVector< Number > & localized_vector, unsigned int var) const inherited
const accessible version of get_localized_subvector function
Definition at line 154 of file diff_context.C.
References libMesh::DiffContext::_localized_vectors.
 {
   auto localized_vectors_it = _localized_vectors.find(&localized_vector);
   libmesh_assert(localized_vectors_it != _localized_vectors.end());
   return *localized_vectors_it->second.second[var];
 }
get_localized_vector() [1/2]
DenseVector< Number > & libMesh::DiffContext::get_localized_vector (const NumericVector< Number > & localized_vector) inherited
Return a reference to DenseVector localization of localized_vector contained in the _localized_vectors map
Definition at line 134 of file diff_context.C.
References libMesh::DiffContext::_localized_vectors.
 {
   return _localized_vectors[&localized_vector].first;
 }
get_localized_vector() [2/2]
const DenseVector< Number > & libMesh::DiffContext::get_localized_vector (const NumericVector< Number > & localized_vector) const inherited
const accessible version of get_localized_vector function
Definition at line 140 of file diff_context.C.
References libMesh::DiffContext::_localized_vectors.
 {
   auto localized_vectors_it = _localized_vectors.find(&localized_vector);
   libmesh_assert(localized_vectors_it != _localized_vectors.end());
   return localized_vectors_it->second.first;
 }
get_mesh_system() [1/2]
const System* libMesh::FEMContext::get_mesh_system () const inline
Accessor for moving mesh System
Definition at line 811 of file fem_context.h.
References _mesh_sys.
   { return this->_mesh_sys; }
get_mesh_system() [2/2]
System* libMesh::FEMContext::get_mesh_system () inline
Accessor for moving mesh System
Definition at line 817 of file fem_context.h.
References _mesh_sys.
   { return this->_mesh_sys; }
get_mesh_x_var()
unsigned int libMesh::FEMContext::get_mesh_x_var () const inline
Accessor for x-variable of moving mesh System
Definition at line 823 of file fem_context.h.
References _mesh_x_var.
Referenced by _do_elem_position_set(), and elem_position_get().
   { return _mesh_x_var; }
get_mesh_y_var()
unsigned int libMesh::FEMContext::get_mesh_y_var () const inline
Accessor for y-variable of moving mesh System
Definition at line 837 of file fem_context.h.
References _mesh_y_var.
Referenced by _do_elem_position_set(), and elem_position_get().
   { return _mesh_y_var; }
get_mesh_z_var()
unsigned int libMesh::FEMContext::get_mesh_z_var () const inline
Accessor for z-variable of moving mesh System
Definition at line 851 of file fem_context.h.
References _mesh_z_var.
Referenced by _do_elem_position_set(), and elem_position_get().
   { return _mesh_z_var; }
get_qoi_derivatives() [1/4]
const std::vector<DenseVector<Number> >& libMesh::DiffContext::get_qoi_derivatives () const inline inherited
Const accessor for QoI derivatives.
Definition at line 331 of file diff_context.h.
References libMesh::DiffContext::_elem_qoi_derivative.
Referenced by pre_fe_reinit().
   { return _elem_qoi_derivative; }
get_qoi_derivatives() [2/4]
std::vector<DenseVector<Number> >& libMesh::DiffContext::get_qoi_derivatives () inline inherited
Non-const accessor for QoI derivatives.
Definition at line 337 of file diff_context.h.
References libMesh::DiffContext::_elem_qoi_derivative.
   { return _elem_qoi_derivative; }
get_qoi_derivatives() [3/4]
const DenseSubVector<Number>& libMesh::DiffContext::get_qoi_derivatives (std::size_t qoi, unsigned int var) const inline inherited
Const accessor for QoI derivative of a particular qoi and variable corresponding to the index arguments.
Definition at line 344 of file diff_context.h.
References libMesh::DiffContext::_elem_qoi_subderivatives.
   {
     libmesh_assert_greater(_elem_qoi_subderivatives.size(), qoi);
     libmesh_assert_greater(_elem_qoi_subderivatives[qoi].size(), var);
     libmesh_assert(_elem_qoi_subderivatives[qoi][var]);
     return *(_elem_qoi_subderivatives[qoi][var]);
   }
get_qoi_derivatives() [4/4]
DenseSubVector<Number>& libMesh::DiffContext::get_qoi_derivatives (std::size_t qoi, unsigned int var) inline inherited
Non-const accessor for QoI derivative of a particular qoi and variable corresponding to the index arguments.
Definition at line 356 of file diff_context.h.
References libMesh::DiffContext::_elem_qoi_subderivatives.
   {
     libmesh_assert_greater(_elem_qoi_subderivatives.size(), qoi);
     libmesh_assert_greater(_elem_qoi_subderivatives[qoi].size(), var);
     libmesh_assert(_elem_qoi_subderivatives[qoi][var]);
     return *(_elem_qoi_subderivatives[qoi][var]);
   }
get_qois() [1/2]
const std::vector<Number>& libMesh::DiffContext::get_qois () const inline inherited
Const accessor for QoI vector.
Definition at line 319 of file diff_context.h.
References libMesh::DiffContext::_elem_qoi.
   { return _elem_qoi; }
get_qois() [2/2]
std::vector<Number>& libMesh::DiffContext::get_qois () inline inherited
Non-const accessor for QoI vector.
Definition at line 325 of file diff_context.h.
References libMesh::DiffContext::_elem_qoi.
   { return _elem_qoi; }
get_side()
unsigned char libMesh::FEMContext::get_side () const inline
Accessor for current side of Elem object
Definition at line 885 of file fem_context.h.
References side.
Referenced by side_fe_reinit().
   { return side; }
get_side_fe() [1/4]
template<typename OutputShape > void libMesh::FEMContext::get_side_fe (unsigned int var, FEGenericBase< OutputShape > *& fe) const inline
Accessor for edge/face (2D/3D) finite element object for variable var for the largest dimension in the mesh. We default to the largest mesh dim because this method may be called before the Elem * is set in the FEMContext, e.g. in FEMSystem::init_context (or a subclass). If you have lower dimensional elements in the mesh and need to query for those FE objects, use the alternative get_side_fe method.
Definition at line 299 of file fem_context.h.
References get_dim().
Referenced by libMesh::ParsedFEMFunction< T >::eval_args(), fixed_side_gradient(), fixed_side_hessian(), fixed_side_value(), get_side_fe(), libMesh::ParsedFEMFunction< T >::init_context(), libMesh::GenericProjector< FFunctor, GFunctor, FValue, ProjectionAction >::operator()(), side_accel(), side_hessian(), and side_rate().
   { this->get_side_fe<OutputShape>(var,fe,this->get_dim()); }
get_side_fe() [2/4]
FEBase* libMesh::FEMContext::get_side_fe (unsigned int var) const inline
Accessor for side finite element object for scalar-valued variable var for the largest dimension in the mesh. We default to the largest mesh dim because this method may be called before the Elem * is set in the FEMContext, e.g. in FEMSystem::init_context (or a subclass). If you have lower dimensional elements in the mesh and need to query for those FE objects, use the alternative get_side_fe method.
Definition at line 310 of file fem_context.h.
References get_dim(), and get_side_fe().
   { return this->get_side_fe(var,this->get_dim()); }
get_side_fe() [3/4]
template<typename OutputShape > void libMesh::FEMContext::get_side_fe (unsigned int var, FEGenericBase< OutputShape > *& fe, unsigned short dim) const inline
Accessor for edge/face (2D/3D) finite element object for variable var for dimension dim.
Definition at line 1223 of file fem_context.h.
References _side_fe_var.
 {
   libmesh_assert( !_side_fe_var[dim].empty() );
   libmesh_assert_less ( var, (_side_fe_var[dim].size() ) );
   fe = cast_ptr<FEGenericBase<OutputShape> *>( (_side_fe_var[dim][var] ) );
 }
get_side_fe() [4/4]
FEBase * libMesh::FEMContext::get_side_fe (unsigned int var, unsigned short dim) const inline
Accessor for side finite element object for scalar-valued variable var for dimension dim.
Definition at line 1232 of file fem_context.h.
References _side_fe_var.
 {
   libmesh_assert( !_side_fe_var[dim].empty() );
   libmesh_assert_less ( var, (_side_fe_var[dim].size() ) );
   return cast_ptr<FEBase *>( (_side_fe_var[dim][var] ) );
 }
get_side_qrule() [1/2]
const QBase& libMesh::FEMContext::get_side_qrule () const inline
Accessor for element side quadrature rule for the dimension of the current _elem.
Definition at line 772 of file fem_context.h.
References get_elem_dim().
   { return this->get_side_qrule(this->get_elem_dim()); }
get_side_qrule() [2/2]
const QBase& libMesh::FEMContext::get_side_qrule (unsigned short dim) const inline
Accessor for element side quadrature rule.
Definition at line 785 of file fem_context.h.
References _side_qrule.
   {
     libmesh_assert(_side_qrule[dim]);
     return *(this->_side_qrule[dim]);
   }
get_system()
const System& libMesh::DiffContext::get_system () const inline inherited
Accessor for associated system.
Definition at line 105 of file diff_context.h.
References libMesh::DiffContext::_system.
Referenced by libMesh::FirstOrderUnsteadySolver::compute_second_order_eqns(), and libMesh::DGFEMContext::neighbor_side_fe_reinit().
   { return _system; }
get_system_time()
Real libMesh::DiffContext::get_system_time () const inline inherited
Accessor for the time variable stored in the system class.
Definition at line 415 of file diff_context.h.
References libMesh::DiffContext::system_time.
Referenced by _update_time_from_system().
   { return system_time; }
get_time()
Real libMesh::DiffContext::get_time () const inline inherited
Accessor for the time for which the current nonlinear_solution is defined.
Definition at line 421 of file diff_context.h.
References libMesh::DiffContext::time.
   { return time; }
has_elem()
bool libMesh::FEMContext::has_elem () const inline
Test for current Elem object
Definition at line 865 of file fem_context.h.
References _elem.
Referenced by build_new_fe(), cached_fe(), elem_fe_reinit(), and pre_fe_reinit().
   { return (this->_elem != nullptr); }
has_side_boundary_id()
bool libMesh::FEMContext::has_side_boundary_id (boundary_id_type id) const
Reports if the boundary id is found on the current side
Definition at line 189 of file fem_context.C.
References _boundary_info, get_elem(), libMesh::BoundaryInfo::has_boundary_id(), and side.
 {
   return _boundary_info.has_boundary_id(&(this->get_elem()), side, id);
 }
init_internal_data()
void libMesh::FEMContext::init_internal_data (const System & sys) private
Helper function used in constructors to set up internal data.
Definition at line 79 of file fem_context.C.
References _edge_fe, _edge_fe_var, _edge_qrule, _elem_dims, _element_fe, _element_fe_var, _element_qrule, _extra_quadrature_order, _side_fe, _side_fe_var, _side_qrule, libMesh::FEAbstract::build(), libMesh::FEType::default_quadrature_rule(), libMesh::FEType::family, libMesh::System::n_vars(), libMesh::FEType::order, libMesh::SCALAR, and libMesh::System::variable_type().
Referenced by FEMContext().
 {
   // Reserve space for the FEAbstract and QBase objects for each
   // element dimension possibility (0,1,2,3)
   // Below is a workaround for the ICC 19. The original code was:
   //
   // _element_fe.resize(4);
   // _side_fe.resize(4);
   _element_fe.clear();
   for (int i=0; i<4; ++i)
     _element_fe.push_back(std::map<FEType, std::unique_ptr<FEAbstract>>());
   _side_fe.clear();
   for (int i=0; i<4; ++i)
     _side_fe.push_back(std::map<FEType, std::unique_ptr<FEAbstract>>());
   _element_fe_var.resize(4);
   _side_fe_var.resize(4);
   // We need to know which of our variables has the hardest
   // shape functions to numerically integrate.
   unsigned int nv = sys.n_vars();
   libmesh_assert (nv);
   FEType hardest_fe_type = sys.variable_type(0);
   bool have_scalar = false;
   for (unsigned int i=0; i != nv; ++i)
     {
       FEType fe_type = sys.variable_type(i);
       // Make sure we find a non-SCALAR FE family, even in the case
       // where the first variable(s) weren't
       if (hardest_fe_type.family == SCALAR)
         {
           hardest_fe_type.family = fe_type.family;
           hardest_fe_type.order = fe_type.order;
         }
       // FIXME - we don't yet handle mixed finite elements from
       // different families which require different quadrature rules
       // libmesh_assert_equal_to (fe_type.family, hardest_fe_type.family);
       // We need to detect SCALAR's so we can prepare FE objects for
       // them, and so we don't mistake high order scalars as a reason
       // to crank up the quadrature order on other types.
       if (fe_type.family == SCALAR)
         have_scalar = true;
       else if (fe_type.order > hardest_fe_type.order)
         hardest_fe_type = fe_type;
     }
   if (have_scalar)
     // SCALAR FEs have dimension 0 by assumption
     _elem_dims.insert(0);
   for (const auto & dim : _elem_dims)
     {
       // Create an adequate quadrature rule
       _element_qrule[dim] =
         hardest_fe_type.default_quadrature_rule(dim, _extra_quadrature_order);
       _side_qrule[dim] =
         hardest_fe_type.default_quadrature_rule(dim-1, _extra_quadrature_order);
       if (dim == 3)
         _edge_qrule = hardest_fe_type.default_quadrature_rule(1, _extra_quadrature_order);
       // Next, create finite element objects
       _element_fe_var[dim].resize(nv);
       _side_fe_var[dim].resize(nv);
       if (dim == 3)
         _edge_fe_var.resize(nv);
       for (unsigned int i=0; i != nv; ++i)
         {
           FEType fe_type = sys.variable_type(i);
           if (_element_fe[dim][fe_type] == nullptr)
             {
               _element_fe[dim][fe_type] = FEAbstract::build(dim, fe_type);
               _element_fe[dim][fe_type]->attach_quadrature_rule(_element_qrule[dim].get());
               _side_fe[dim][fe_type] = FEAbstract::build(dim, fe_type);
               _side_fe[dim][fe_type]->attach_quadrature_rule(_side_qrule[dim].get());
               if (dim == 3)
                 {
                   _edge_fe[fe_type] = FEAbstract::build(dim, fe_type);
                   _edge_fe[fe_type]->attach_quadrature_rule(_edge_qrule.get());
                 }
             }
           _element_fe_var[dim][i] = _element_fe[dim][fe_type].get();
           _side_fe_var[dim][i] = _side_fe[dim][fe_type].get();
           if ((dim) == 3)
             _edge_fe_var[i] = _edge_fe[fe_type].get();
         }
     }
 }
interior_accel()
template<typename OutputType > template void libMesh::FEMContext::interior_accel< Gradient > (unsigned int var, unsigned int qp, OutputType & u) const
Returns
The second time derivative (acceleration) of the solution variable var at the quadrature point qp on the current element interior.
Definition at line 1275 of file fem_context.C.
References libMesh::DiffContext::get_elem_solution_accel(), get_element_fe(), and some_value().
 {
   this->some_value<OutputType,
                    &FEMContext::get_element_fe
                    <typename TensorTools::MakeReal<OutputType>::type>,
                    &DiffContext::get_elem_solution_accel>(var, qp, u);
 }
interior_curl()
template<typename OutputType > template void libMesh::FEMContext::interior_curl< Gradient > (unsigned int var, unsigned int qp, OutputType & curl_u) const
Returns
The curl of the solution variable var at the physical point p on the current element.
Definition at line 492 of file fem_context.C.
References libMesh::DiffContext::_elem_subsolutions, libMesh::FEGenericBase< OutputType >::get_curl_phi(), libMesh::DiffContext::get_dof_indices(), get_elem_dim(), and libMesh::DiffContext::get_elem_solution().
 {
   typedef typename TensorTools::MakeReal<OutputType>::type OutputShape;
   // Get local-to-global dof index lookup
   const unsigned int n_dofs = cast_int<unsigned int>
     (this->get_dof_indices(var).size());
   // Get current local coefficients
   libmesh_assert_greater (this->_elem_subsolutions.size(), var);
   const DenseSubVector<Number> & coef = this->get_elem_solution(var);
   // Get finite element object
   FEGenericBase<OutputShape> * fe = nullptr;
   this->get_element_fe<OutputShape>( var, fe, this->get_elem_dim() );
   // Get shape function values at quadrature point
   const std::vector<std::vector<typename FEGenericBase<OutputShape>::OutputShape>> & curl_phi = fe->get_curl_phi();
   // Accumulate solution curl
   curl_u = 0.;
   for (unsigned int l=0; l != n_dofs; l++)
     curl_u.add_scaled(curl_phi[l][qp], coef(l));
   return;
 }
interior_div()
template<typename OutputType > template void libMesh::FEMContext::interior_div< Number > (unsigned int var, unsigned int qp, OutputType & div_u) const
Returns
The divergence of the solution variable var at the physical point p on the current element.
Definition at line 523 of file fem_context.C.
References libMesh::DiffContext::_elem_subsolutions, libMesh::FEGenericBase< OutputType >::get_div_phi(), libMesh::DiffContext::get_dof_indices(), get_elem_dim(), and libMesh::DiffContext::get_elem_solution().
 {
   typedef typename
     TensorTools::IncrementRank
     <typename TensorTools::MakeReal<OutputType>::type>::type OutputShape;
   // Get local-to-global dof index lookup
   const unsigned int n_dofs = cast_int<unsigned int>
     (this->get_dof_indices(var).size());
   // Get current local coefficients
   libmesh_assert_greater (this->_elem_subsolutions.size(), var);
   const DenseSubVector<Number> & coef = this->get_elem_solution(var);
   // Get finite element object
   FEGenericBase<OutputShape> * fe = nullptr;
   this->get_element_fe<OutputShape>( var, fe, this->get_elem_dim() );
   // Get shape function values at quadrature point
   const std::vector<std::vector<typename FEGenericBase<OutputShape>::OutputDivergence>> & div_phi = fe->get_div_phi();
   // Accumulate solution curl
   div_u = 0.;
   for (unsigned int l=0; l != n_dofs; l++)
     div_u += div_phi[l][qp] * coef(l);
   return;
 }
interior_gradient() [1/2]
Gradient libMesh::FEMContext::interior_gradient (unsigned int var, unsigned int qp) const
Returns
The gradient of the solution variable var at the quadrature point qp on the current element interior.
Note
This API is currently present for backward compatibility.
Definition at line 361 of file fem_context.C.
 {
   Gradient du;
   this->interior_gradient( var, qp, du );
   return du;
 }
interior_gradient() [2/2]
template<typename OutputType > void libMesh::FEMContext::interior_gradient (unsigned int var, unsigned int qp, OutputType & du) const
Returns
The gradient of the solution variable var at the quadrature point qp on the current element interior.
Note
This is the preferred API.
Definition at line 374 of file fem_context.C.
References libMesh::DiffContext::get_elem_solution(), get_element_fe(), and some_gradient().
 {
   this->some_gradient<OutputType,
                       &FEMContext::get_element_fe<typename TensorTools::MakeReal
                                                   <typename TensorTools::DecrementRank
                                                    <OutputType>::type>::type>,
                       &DiffContext::get_elem_solution>(var, qp, du);
 }
interior_gradients()
template<typename OutputType > template void libMesh::FEMContext::interior_gradients< Tensor > (unsigned int var, const NumericVector< Number > & _system_vector, std::vector< OutputType > & interior_gradients_vector) const
Fills a vector with the gradient of the solution variable var at all the quadrature points in the current element interior.
Note
This is the preferred API.
Definition at line 388 of file fem_context.C.
References libMesh::DiffContext::get_dof_indices(), libMesh::FEGenericBase< OutputType >::get_dphi(), get_elem_dim(), and libMesh::DiffContext::get_localized_subvector().
 {
   typedef typename TensorTools::MakeReal
     <typename TensorTools::DecrementRank<OutputType>::type>::type
     OutputShape;
   // Get local-to-global dof index lookup
   const unsigned int n_dofs = cast_int<unsigned int>
     (this->get_dof_indices(var).size());
   // Get current local coefficients
   const DenseSubVector<Number> & coef = get_localized_subvector(_system_vector, var);
   // Get finite element object
   FEGenericBase<OutputShape> * fe = nullptr;
   this->get_element_fe<OutputShape>( var, fe, this->get_elem_dim() );
   // Get shape function values at quadrature point
   const std::vector<std::vector<typename FEGenericBase<OutputShape>::OutputGradient>> & dphi = fe->get_dphi();
   // Loop over all the q_points in this finite element
   for (std::size_t qp=0; qp != du_vals.size(); qp++)
     {
       OutputType & du = du_vals[qp];
       // Compute the gradient at this q_point
       du = 0;
       for (unsigned int l=0; l != n_dofs; l++)
         du.add_scaled(dphi[l][qp], coef(l));
     }
   return;
 }
interior_hessian() [1/2]
Tensor libMesh::FEMContext::interior_hessian (unsigned int var, unsigned int qp) const
Returns
The hessian of the solution variable var at the quadrature point qp on the current element interior.
Note
This API is currently present for backward compatibility.
Definition at line 426 of file fem_context.C.
 {
   Tensor d2u;
   this->interior_hessian( var, qp, d2u );
   return d2u;
 }
interior_hessian() [2/2]
template<typename OutputType > void libMesh::FEMContext::interior_hessian (unsigned int var, unsigned int qp, OutputType & d2u) const
Returns
The hessian of the solution variable var at the quadrature point qp on the current element interior.
Note
This is the preferred API.
Definition at line 436 of file fem_context.C.
References libMesh::DiffContext::get_elem_solution(), get_element_fe(), and some_hessian().
 {
   this->some_hessian<OutputType,
                      &FEMContext::get_element_fe
                      <typename TensorTools::MakeReal
                       <typename TensorTools::DecrementRank
                        <typename TensorTools::DecrementRank
                         <OutputType>::type>::type>::type>,
                      &DiffContext::get_elem_solution>(var, qp, d2u);
 }
interior_hessians()
template<typename OutputType > template void libMesh::FEMContext::interior_hessians< Tensor > (unsigned int var, const NumericVector< Number > & _system_vector, std::vector< OutputType > & d2u_vals) const
Fills a vector of hessians of the _system_vector at the all the quadrature points in the current element interior. This is the preferred API.
Definition at line 450 of file fem_context.C.
References libMesh::FEGenericBase< OutputType >::get_d2phi(), libMesh::DiffContext::get_dof_indices(), get_elem_dim(), and libMesh::DiffContext::get_localized_subvector().
 {
   typedef typename TensorTools::DecrementRank<OutputType>::type Rank1Decrement;
   typedef typename TensorTools::DecrementRank<Rank1Decrement>::type Rank2Decrement;
   typedef typename TensorTools::MakeReal<Rank2Decrement>::type OutputShape;
   // Get local-to-global dof index lookup
   const unsigned int n_dofs = cast_int<unsigned int>
     (this->get_dof_indices(var).size());
   // Get current local coefficients
   const DenseSubVector<Number> & coef = get_localized_subvector(_system_vector, var);
   // Get finite element object
   FEGenericBase<OutputShape> * fe = nullptr;
   this->get_element_fe<OutputShape>( var, fe, this->get_elem_dim() );
   // Get shape function values at quadrature point
   const std::vector<std::vector<typename FEGenericBase<OutputShape>::OutputTensor>> & d2phi = fe->get_d2phi();
   // Loop over all the q_points in this finite element
   for (std::size_t qp=0; qp != d2u_vals.size(); qp++)
     {
       OutputType & d2u = d2u_vals[qp];
       // Compute the gradient at this q_point
       d2u = 0;
       for (unsigned int l=0; l != n_dofs; l++)
         d2u.add_scaled(d2phi[l][qp], coef(l));
     }
   return;
 }
interior_rate()
template<typename OutputType > template void libMesh::FEMContext::interior_rate< Gradient > (unsigned int var, unsigned int qp, OutputType & u) const
Returns
The time derivative (rate) of the solution variable var at the quadrature point qp on the current element interior.
Definition at line 1253 of file fem_context.C.
References libMesh::DiffContext::get_elem_solution_rate(), get_element_fe(), and some_value().
Referenced by libMesh::FirstOrderUnsteadySolver::compute_second_order_eqns().
 {
   this->some_value<OutputType,
                    &FEMContext::get_element_fe
                    <typename TensorTools::MakeReal<OutputType>::type>,
                    &DiffContext::get_elem_solution_rate>(var, qp, u);
 }
interior_value() [1/2]
Number libMesh::FEMContext::interior_value (unsigned int var, unsigned int qp) const
Returns
The value of the solution variable var at the quadrature point qp on the current element interior.
Note
This API is currently present for backward compatibility.
Definition at line 306 of file fem_context.C.
Referenced by libMesh::FirstOrderUnsteadySolver::compute_second_order_eqns().
 {
   Number u;
   this->interior_value( var, qp, u );
   return u;
 }
interior_value() [2/2]
template<typename OutputType > void libMesh::FEMContext::interior_value (unsigned int var, unsigned int qp, OutputType & u) const
Returns
The value of the solution variable var at the quadrature point qp on the current element interior.
Note
This is the preferred API.
Definition at line 316 of file fem_context.C.
References libMesh::DiffContext::get_elem_solution(), and some_value().
 {
   this->some_value<OutputType,
                    &FEMContext::get_element_fe<typename TensorTools::MakeReal<OutputType>::type>,
                    &DiffContext::get_elem_solution>(var, qp, u);
 }
interior_values()
template<typename OutputType > template void libMesh::FEMContext::interior_values< Gradient > (unsigned int var, const NumericVector< Number > & _system_vector, std::vector< OutputType > & interior_values_vector) const
Fills a vector of values of the _system_vector at the all the quadrature points in the current element interior.
Definition at line 326 of file fem_context.C.
References libMesh::DiffContext::get_dof_indices(), get_elem_dim(), libMesh::DiffContext::get_localized_subvector(), and libMesh::FEGenericBase< OutputType >::get_phi().
 {
   typedef typename TensorTools::MakeReal<OutputType>::type OutputShape;
   // Get local-to-global dof index lookup
   const unsigned int n_dofs = cast_int<unsigned int>
     (this->get_dof_indices(var).size());
   // Get current local coefficients
   const DenseSubVector<Number> & coef = get_localized_subvector(_system_vector, var);
   // Get the finite element object
   FEGenericBase<OutputShape> * fe = nullptr;
   this->get_element_fe<OutputShape>( var, fe, this->get_elem_dim() );
   // Get shape function values at quadrature point
   const std::vector<std::vector<OutputShape>> & phi = fe->get_phi();
   // Loop over all the q_points on this element
   for (std::size_t qp=0; qp != u_vals.size(); qp++)
     {
       OutputType & u = u_vals[qp];
       // Compute the value at this q_point
       u = 0.;
       for (unsigned int l=0; l != n_dofs; l++)
         u += phi[l][qp] * coef(l);
     }
   return;
 }
is_adjoint() [1/2]
bool libMesh::DiffContext::is_adjoint () const inline inherited
Accessor for querying whether we need to do a primal or adjoint solve
Definition at line 470 of file diff_context.h.
References libMesh::DiffContext::_is_adjoint.
Referenced by libMesh::FEMSystem::build_context().
   { return _is_adjoint; }
is_adjoint() [2/2]
bool& libMesh::DiffContext::is_adjoint () inline inherited
Accessor for setting whether we need to do a primal or adjoint solve
Definition at line 477 of file diff_context.h.
References libMesh::DiffContext::_is_adjoint.
   { return _is_adjoint; }
n_dof_indices() [1/2]
unsigned int libMesh::DiffContext::n_dof_indices () const inline inherited
Total number of dof indices on the element
Definition at line 399 of file diff_context.h.
References libMesh::DiffContext::_dof_indices.
   { return cast_int<unsigned int>(_dof_indices.size()); }
n_dof_indices() [2/2]
unsigned int libMesh::DiffContext::n_dof_indices (unsigned int var) const inline inherited
Total number of dof indices of the particular variable corresponding to the index argument
Definition at line 406 of file diff_context.h.
References libMesh::DiffContext::_dof_indices_var.
   {
     libmesh_assert_greater(_dof_indices_var.size(), var);
     return cast_int<unsigned int>(_dof_indices_var[var].size());
   }
n_vars()
unsigned int libMesh::DiffContext::n_vars () const inline inherited
Number of variables in solution.
Definition at line 99 of file diff_context.h.
References libMesh::DiffContext::_dof_indices_var.
Referenced by libMesh::FirstOrderUnsteadySolver::compute_second_order_eqns(), libMesh::LaplacianErrorEstimator::init_context(), libMesh::DiscontinuityMeasure::init_context(), libMesh::KellyErrorEstimator::init_context(), and libMesh::FEMSystem::numerical_jacobian().
   { return cast_int<unsigned int>(_dof_indices_var.size()); }
nonlocal_reinit()
void libMesh::FEMContext::nonlocal_reinit (Real theta) override virtual
Gives derived classes the opportunity to reinitialize data needed for nonlocal calculations at a new point within a timestep
Reimplemented from libMesh::DiffContext.
Definition at line 1352 of file fem_context.C.
References _update_time_from_system(), and elem_fe_reinit().
 {
   // Update the "time" variable of this context object
   this->_update_time_from_system(theta);
   // We can reuse the Elem FE safely here.
   elem_fe_reinit();
 }
point_accel()
template<typename OutputType > void libMesh::FEMContext::point_accel (unsigned int var, const Point & p, OutputType & u) const
Returns
The second time derivative (acceleration) of the solution variable var at the physical point p on the current element.
point_curl()
template<typename OutputType > template void libMesh::FEMContext::point_curl< Gradient > (unsigned int var, const Point & p, OutputType & curl_u, const Real tolerance = TOLERANCE) const
Returns
The curl of the solution variable var at the physical point p on the current element.
Allows evaluation of points within a relative tolerance outside the element.
Definition at line 917 of file fem_context.C.
References libMesh::DiffContext::_elem_subsolutions, build_new_fe(), libMesh::DiffContext::get_dof_indices(), get_elem_dim(), and libMesh::DiffContext::get_elem_solution().
 {
   typedef typename TensorTools::MakeReal<OutputType>::type OutputShape;
   // Get local-to-global dof index lookup
   const unsigned int n_dofs = cast_int<unsigned int>
     (this->get_dof_indices(var).size());
   // Get current local coefficients
   libmesh_assert_greater (this->_elem_subsolutions.size(), var);
   const DenseSubVector<Number> & coef = this->get_elem_solution(var);
   // Get finite element object
   FEGenericBase<OutputShape> * fe = nullptr;
   this->get_element_fe<OutputShape>( var, fe, this->get_elem_dim() );
   // Build a FE for calculating u(p)
   FEGenericBase<OutputShape> * fe_new =
     this->build_new_fe( fe, p, tolerance );
   // Get the values of the shape function derivatives
   const std::vector<std::vector<typename FEGenericBase<OutputShape>::OutputShape>> &  curl_phi = fe_new->get_curl_phi();
   curl_u = 0.0;
   for (unsigned int l=0; l != n_dofs; l++)
     curl_u.add_scaled(curl_phi[l][0], coef(l));
   return;
 }
point_gradient() [1/2]
Gradient libMesh::FEMContext::point_gradient (unsigned int var, const Point & p) const
Returns
The gradient of the solution variable var at the physical point p on the current element.
Note
This API is currently present for backward compatibility.
Definition at line 814 of file fem_context.C.
Referenced by libMesh::ParsedFEMFunction< T >::eval_args().
 {
   Gradient grad_u;
   this->point_gradient( var, p, grad_u );
   return grad_u;
 }
point_gradient() [2/2]
template<typename OutputType > void libMesh::FEMContext::point_gradient (unsigned int var, const Point & p, OutputType & grad_u, const Real tolerance = TOLERANCE) const
Returns
The gradient of the solution variable var at the physical point p on the current element.
Note
This is the preferred API.
Allows evaluation of points within a relative tolerance outside the element.
Definition at line 826 of file fem_context.C.
References libMesh::DiffContext::_elem_subsolutions, build_new_fe(), libMesh::DiffContext::get_dof_indices(), get_elem_dim(), and libMesh::DiffContext::get_elem_solution().
 {
   typedef typename TensorTools::MakeReal
     <typename TensorTools::DecrementRank<OutputType>::type>::type
     OutputShape;
   // Get local-to-global dof index lookup
   const unsigned int n_dofs = cast_int<unsigned int>
     (this->get_dof_indices(var).size());
   // Get current local coefficients
   libmesh_assert_greater (this->_elem_subsolutions.size(), var);
   const DenseSubVector<Number> & coef = this->get_elem_solution(var);
   // Get finite element object
   FEGenericBase<OutputShape> * fe = nullptr;
   this->get_element_fe<OutputShape>( var, fe, this->get_elem_dim() );
   // Build a FE for calculating u(p)
   FEGenericBase<OutputShape> * fe_new =
     this->build_new_fe( fe, p, tolerance );
   // Get the values of the shape function derivatives
   const std::vector<std::vector<typename FEGenericBase<OutputShape>::OutputGradient>> &  dphi = fe_new->get_dphi();
   grad_u = 0.0;
   for (unsigned int l=0; l != n_dofs; l++)
     grad_u.add_scaled(dphi[l][0], coef(l));
   return;
 }
point_hessian() [1/2]
Tensor libMesh::FEMContext::point_hessian (unsigned int var, const Point & p) const
Returns
The hessian of the solution variable var at the physical point p on the current element.
Note
This API currently present for backward compatibility.
Definition at line 866 of file fem_context.C.
Referenced by libMesh::ParsedFEMFunction< T >::eval_args().
 {
   Tensor hess_u;
   this->point_hessian( var, p, hess_u );
   return hess_u;
 }
point_hessian() [2/2]
template<typename OutputType > void libMesh::FEMContext::point_hessian (unsigned int var, const Point & p, OutputType & hess_u, const Real tolerance = TOLERANCE) const
Returns
The hessian of the solution variable var at the physical point p on the current element.
Note
This is the preferred API.
Allows evaluation of points within a relative tolerance outside the element.
Definition at line 877 of file fem_context.C.
References libMesh::DiffContext::_elem_subsolutions, build_new_fe(), libMesh::DiffContext::get_dof_indices(), get_elem_dim(), and libMesh::DiffContext::get_elem_solution().
 {
   typedef typename TensorTools::DecrementRank<OutputType>::type Rank1Decrement;
   typedef typename TensorTools::DecrementRank<Rank1Decrement>::type Rank2Decrement;
   typedef typename TensorTools::MakeReal<Rank2Decrement>::type OutputShape;
   // Get local-to-global dof index lookup
   const unsigned int n_dofs = cast_int<unsigned int>
     (this->get_dof_indices(var).size());
   // Get current local coefficients
   libmesh_assert_greater (this->_elem_subsolutions.size(), var);
   const DenseSubVector<Number> & coef = this->get_elem_solution(var);
   // Get finite element object
   FEGenericBase<OutputShape> * fe = nullptr;
   this->get_element_fe<OutputShape>( var, fe, this->get_elem_dim() );
   // Build a FE for calculating u(p)
   FEGenericBase<OutputShape> * fe_new =
     this->build_new_fe( fe, p, tolerance );
   // Get the values of the shape function derivatives
   const std::vector<std::vector<typename FEGenericBase<OutputShape>::OutputTensor>> &  d2phi = fe_new->get_d2phi();
   hess_u = 0.0;
   for (unsigned int l=0; l != n_dofs; l++)
     hess_u.add_scaled(d2phi[l][0], coef(l));
   return;
 }
point_rate()
template<typename OutputType > void libMesh::FEMContext::point_rate (unsigned int var, const Point & p, OutputType & u) const
Returns
The time derivative (rate) of the solution variable var at the physical point p on the current element.
point_value() [1/2]
Number libMesh::FEMContext::point_value (unsigned int var, const Point & p) const
Returns
The value of the solution variable var at the physical point p on the current element.
Note
This API is currently present for backward compatibility.
Definition at line 768 of file fem_context.C.
Referenced by libMesh::ParsedFEMFunction< T >::eval_args().
 {
   Number u = 0.;
   this->point_value( var, p, u );
   return u;
 }
point_value() [2/2]
template<typename OutputType > void libMesh::FEMContext::point_value (unsigned int var, const Point & p, OutputType & u, const Real tolerance = TOLERANCE) const
Returns
The value of the solution variable var at the physical point p on the current element.
Note
This is the preferred API.
Allows evaluation of points within a relative tolerance outside the element.
Definition at line 778 of file fem_context.C.
References libMesh::DiffContext::_elem_subsolutions, build_new_fe(), libMesh::DiffContext::get_dof_indices(), get_elem_dim(), and libMesh::DiffContext::get_elem_solution().
 {
   typedef typename TensorTools::MakeReal<OutputType>::type OutputShape;
   // Get local-to-global dof index lookup
   const unsigned int n_dofs = cast_int<unsigned int>
     (this->get_dof_indices(var).size());
   // Get current local coefficients
   libmesh_assert_greater (this->_elem_subsolutions.size(), var);
   const DenseSubVector<Number> & coef = this->get_elem_solution(var);
   // Get finite element object
   FEGenericBase<OutputShape> * fe = nullptr;
   this->get_element_fe<OutputShape>( var, fe, this->get_elem_dim() );
   // Build a FE for calculating u(p)
   FEGenericBase<OutputShape> * fe_new =
     this->build_new_fe( fe, p, tolerance );
   // Get the values of the shape function derivatives
   const std::vector<std::vector<OutputShape>> &  phi = fe_new->get_phi();
   u = 0.;
   for (unsigned int l=0; l != n_dofs; l++)
     u += phi[l][0] * coef(l);
   return;
 }
pre_fe_reinit()
void libMesh::FEMContext::pre_fe_reinit (const System & sys, const Elem * e) virtual
Reinitializes local data vectors/matrices on the current geometric element
Definition at line 1552 of file fem_context.C.
References _custom_solution, libMesh::DiffContext::_elem_qoi_subderivatives, libMesh::DiffContext::_localized_vectors, algebraic_type(), CURRENT, libMesh::System::current_local_solution, libMesh::DofMap::dof_indices(), DOFS_ONLY, libMesh::NumericVector< T >::get(), libMesh::DiffContext::get_dof_indices(), libMesh::System::get_dof_map(), get_elem(), libMesh::DiffContext::get_elem_fixed_solution(), libMesh::DiffContext::get_elem_jacobian(), libMesh::DiffContext::get_elem_residual(), libMesh::DiffContext::get_elem_solution(), libMesh::DiffContext::get_elem_solution_accel(), libMesh::DiffContext::get_elem_solution_rate(), libMesh::DiffContext::get_qoi_derivatives(), libMesh::DifferentiablePhysics::get_second_order_vars(), libMesh::DifferentiableSystem::get_time_solver(), libMesh::DenseVector< T >::get_values(), has_elem(), libMesh::TimeSolver::is_steady(), libMesh::System::n_qois(), libMesh::System::n_vars(), NONE, OLD, libMesh::DofMap::old_dof_indices(), OLD_DOFS_ONLY, libMesh::DenseVector< T >::resize(), libMesh::DenseMatrix< T >::resize(), set_elem(), libMesh::UnsteadySolver::time_order(), and libMesh::System::use_fixed_solution.
Referenced by libMesh::FEMSystem::assembly(), libMesh::FEMSystem::mesh_position_get(), libMesh::FEMSystem::mesh_position_set(), libMesh::GenericProjector< FFunctor, GFunctor, FValue, ProjectionAction >::operator()(), libMesh::WeightedPatchRecoveryErrorEstimator::EstimateError::operator()(), and libMesh::System::project_vector().
 {
   this->set_elem(e);
   if (algebraic_type() == CURRENT ||
       algebraic_type() == DOFS_ONLY)
     {
       // Initialize the per-element data for elem.
       if (this->has_elem())
         sys.get_dof_map().dof_indices (&(this->get_elem()), this->get_dof_indices());
       else
         // If !this->has_elem(), then we assume we are dealing with a SCALAR variable
         sys.get_dof_map().dof_indices
           (static_cast<Elem*>(nullptr), this->get_dof_indices());
     }
 #ifdef LIBMESH_ENABLE_AMR
   else if (algebraic_type() == OLD ||
            algebraic_type() == OLD_DOFS_ONLY)
     {
       // Initialize the per-element data for elem.
       if (this->has_elem())
         sys.get_dof_map().old_dof_indices (&(this->get_elem()), this->get_dof_indices());
       else
         // If !this->has_elem(), then we assume we are dealing with a SCALAR variable
         sys.get_dof_map().old_dof_indices
           (static_cast<Elem*>(nullptr), this->get_dof_indices());
     }
 #endif // LIBMESH_ENABLE_AMR
   const unsigned int n_dofs = cast_int<unsigned int>
     (this->get_dof_indices().size());
   const unsigned int n_qoi = sys.n_qois();
   if (this->algebraic_type() != NONE &&
       this->algebraic_type() != DOFS_ONLY &&
       this->algebraic_type() != OLD_DOFS_ONLY)
     {
       // This also resizes elem_solution
       if (_custom_solution == nullptr)
         sys.current_local_solution->get(this->get_dof_indices(), this->get_elem_solution().get_values());
       else
         _custom_solution->get(this->get_dof_indices(), this->get_elem_solution().get_values());
       if (sys.use_fixed_solution)
         this->get_elem_fixed_solution().resize(n_dofs);
       // Only make space for these if we're using DiffSystem
       // This is assuming *only* DiffSystem is using elem_solution_rate/accel
       const DifferentiableSystem * diff_system = dynamic_cast<const DifferentiableSystem *>(&sys);
       if (diff_system)
         {
           // Now, we only need these if the solver is unsteady
           if (!diff_system->get_time_solver().is_steady())
             {
               this->get_elem_solution_rate().resize(n_dofs);
               // We only need accel space if the TimeSolver is second order
               const UnsteadySolver & time_solver = cast_ref<const UnsteadySolver &>(diff_system->get_time_solver());
               if (time_solver.time_order() >= 2 || !diff_system->get_second_order_vars().empty())
                 this->get_elem_solution_accel().resize(n_dofs);
             }
         }
       if (algebraic_type() != OLD)
         {
           // These resize calls also zero out the residual and jacobian
           this->get_elem_residual().resize(n_dofs);
           this->get_elem_jacobian().resize(n_dofs, n_dofs);
           this->get_qoi_derivatives().resize(n_qoi);
           this->_elem_qoi_subderivatives.resize(n_qoi);
           for (std::size_t q=0; q != n_qoi; ++q)
             (this->get_qoi_derivatives())[q].resize(n_dofs);
         }
     }
   // Initialize the per-variable data for elem.
   {
     unsigned int sub_dofs = 0;
     for (unsigned int i=0; i != sys.n_vars(); ++i)
       {
         if (algebraic_type() == CURRENT ||
             algebraic_type() == DOFS_ONLY)
           {
             if (this->has_elem())
               sys.get_dof_map().dof_indices (&(this->get_elem()), this->get_dof_indices(i), i);
             else
               // If !this->has_elem(), then we assume we are dealing with a SCALAR variable
               sys.get_dof_map().dof_indices
                 (static_cast<Elem*>(nullptr), this->get_dof_indices(i), i);
           }
 #ifdef LIBMESH_ENABLE_AMR
         else if (algebraic_type() == OLD ||
                  algebraic_type() == OLD_DOFS_ONLY)
           {
             if (this->has_elem())
               sys.get_dof_map().old_dof_indices (&(this->get_elem()), this->get_dof_indices(i), i);
             else
               // If !this->has_elem(), then we assume we are dealing with a SCALAR variable
               sys.get_dof_map().old_dof_indices
                 (static_cast<Elem*>(nullptr), this->get_dof_indices(i), i);
           }
 #endif // LIBMESH_ENABLE_AMR
         if (this->algebraic_type() != NONE &&
             this->algebraic_type() != DOFS_ONLY &&
             this->algebraic_type() != OLD_DOFS_ONLY)
           {
             const unsigned int n_dofs_var = cast_int<unsigned int>
               (this->get_dof_indices(i).size());
             this->get_elem_solution(i).reposition
               (sub_dofs, n_dofs_var);
             // Only make space for these if we're using DiffSystem
             // This is assuming *only* DiffSystem is using elem_solution_rate/accel
             const DifferentiableSystem * diff_system = dynamic_cast<const DifferentiableSystem *>(&sys);
             if (diff_system)
               {
                 // Now, we only need these if the solver is unsteady
                 if (!diff_system->get_time_solver().is_steady())
                   {
                     this->get_elem_solution_rate(i).reposition
                       (sub_dofs, n_dofs_var);
                     // We only need accel space if the TimeSolver is second order
                     const UnsteadySolver & time_solver = cast_ref<const UnsteadySolver &>(diff_system->get_time_solver());
                     if (time_solver.time_order() >= 2 || !diff_system->get_second_order_vars().empty())
                       this->get_elem_solution_accel(i).reposition
                         (sub_dofs, n_dofs_var);
                   }
               }
             if (sys.use_fixed_solution)
               this->get_elem_fixed_solution(i).reposition
                 (sub_dofs, n_dofs_var);
             if (algebraic_type() != OLD)
               {
                 this->get_elem_residual(i).reposition
                   (sub_dofs, n_dofs_var);
                 for (std::size_t q=0; q != n_qoi; ++q)
                   this->get_qoi_derivatives(q,i).reposition
                     (sub_dofs, n_dofs_var);
                 for (unsigned int j=0; j != i; ++j)
                   {
                     const unsigned int n_dofs_var_j =
                       cast_int<unsigned int>
                       (this->get_dof_indices(j).size());
                     this->get_elem_jacobian(i,j).reposition
                       (sub_dofs, this->get_elem_residual(j).i_off(),
                        n_dofs_var, n_dofs_var_j);
                     this->get_elem_jacobian(j,i).reposition
                       (this->get_elem_residual(j).i_off(), sub_dofs,
                        n_dofs_var_j, n_dofs_var);
                   }
                 this->get_elem_jacobian(i,i).reposition
                   (sub_dofs, sub_dofs,
                    n_dofs_var,
                    n_dofs_var);
               }
             sub_dofs += n_dofs_var;
           }
       }
     if (this->algebraic_type() != NONE &&
         this->algebraic_type() != DOFS_ONLY &&
         this->algebraic_type() != OLD &&
         this->algebraic_type() != OLD_DOFS_ONLY)
       libmesh_assert_equal_to (sub_dofs, n_dofs);
   }
   // Now do the localization for the user requested vectors
   if (this->algebraic_type() != NONE &&
       this->algebraic_type() != DOFS_ONLY &&
       this->algebraic_type() != OLD_DOFS_ONLY)
     {
       DiffContext::localized_vectors_iterator localized_vec_it = this->_localized_vectors.begin();
       const DiffContext::localized_vectors_iterator localized_vec_end = this->_localized_vectors.end();
       for (; localized_vec_it != localized_vec_end; ++localized_vec_it)
         {
           const NumericVector<Number> & current_localized_vector = *localized_vec_it->first;
           DenseVector<Number> & target_vector = localized_vec_it->second.first;
           current_localized_vector.get(this->get_dof_indices(), target_vector.get_values());
           // Initialize the per-variable data for elem.
           unsigned int sub_dofs = 0;
           for (unsigned int i=0; i != sys.n_vars(); ++i)
             {
               const unsigned int n_dofs_var = cast_int<unsigned int>
                 (this->get_dof_indices(i).size());
               // This is redundant with earlier initialization, isn't it? - RHS
               // sys.get_dof_map().dof_indices (&(this->get_elem()), this->get_dof_indices(i), i);
               localized_vec_it->second.second[i]->reposition
                 (sub_dofs, n_dofs_var);
               sub_dofs += n_dofs_var;
             }
           libmesh_assert_equal_to (sub_dofs, n_dofs);
         }
     }
 }
set_algebraic_type()
void libMesh::FEMContext::set_algebraic_type (const AlgebraicType atype) inline
Setting which determines whether to initialize algebraic structures (elem_*) on each element and set their values from current_local_solution. Algebraic initialization may be disabled for efficiency in cases where FEMContext is only used as a convenient container of FE objects.
Definition at line 948 of file fem_context.h.
References _atype.
Referenced by libMesh::OldSolutionBase< Output, point_output >::init_context().
   { _atype = atype; }
set_custom_solution()
void libMesh::FEMContext::set_custom_solution (const NumericVector< Number > * custom_sol) inline
Set a NumericVector to be used in place of current_local_solution for calculating elem_solution. Set to nullptr to restore the current_local_solution behavior. Advanced DifferentiableSystem specific capabilities will only be enabled in the current_local_solution case.
Definition at line 963 of file fem_context.h.
References _custom_solution.
   { _custom_solution = custom_sol; }
set_deltat_pointer()
void libMesh::DiffContext::set_deltat_pointer (Real * dt) inherited
Points the _deltat member of this class at a timestep value stored in the creating System, for example DiffSystem::deltat
Definition at line 103 of file diff_context.C.
References libMesh::DiffContext::_deltat.
Referenced by libMesh::FEMSystem::build_context(), libMesh::DifferentiableSystem::build_context(), and libMesh::FEMSystem::init_context().
 {
   // We may actually want to be able to set this pointer to nullptr, so
   // don't report an error for that.
   _deltat = dt;
 }
set_elem()
void libMesh::FEMContext::set_elem (const Elem * e) protected
Helper function to promote accessor usage
Definition at line 1765 of file fem_context.C.
References _elem, _elem_dim, and libMesh::Elem::dim().
Referenced by pre_fe_reinit().
 {
   this->_elem = e;
   // If e is nullptr, we assume it's SCALAR and set _elem_dim to 0.
   this->_elem_dim =
     cast_int<unsigned char>(this->_elem ? this->_elem->dim() : 0);
 }
set_mesh_system()
virtual void libMesh::FEMContext::set_mesh_system (System * sys) inline virtual
Tells the FEMContext that system sys contains the isoparametric Lagrangian variables which correspond to the coordinates of mesh nodes, in problems where the mesh itself is expected to move in time.
This should be set automatically if the FEMPhysics requires it.
Definition at line 805 of file fem_context.h.
References _mesh_sys.
Referenced by libMesh::FEMSystem::build_context().
   { this->_mesh_sys = sys; }
set_mesh_x_var()
void libMesh::FEMContext::set_mesh_x_var (unsigned int x_var) inline
Accessor for x-variable of moving mesh System
This should be set automatically if the FEMPhysics requires it.
Definition at line 831 of file fem_context.h.
References _mesh_x_var.
Referenced by libMesh::FEMSystem::build_context().
   { _mesh_x_var = x_var; }
set_mesh_y_var()
void libMesh::FEMContext::set_mesh_y_var (unsigned int y_var) inline
Accessor for y-variable of moving mesh System
This should be set automatically if the FEMPhysics requires it.
Definition at line 845 of file fem_context.h.
References _mesh_y_var.
Referenced by libMesh::FEMSystem::build_context().
   { _mesh_y_var = y_var; }
set_mesh_z_var()
void libMesh::FEMContext::set_mesh_z_var (unsigned int z_var) inline
Accessor for z-variable of moving mesh System
This should be set automatically if the FEMPhysics requires it.
Definition at line 859 of file fem_context.h.
References _mesh_z_var.
Referenced by libMesh::FEMSystem::build_context().
   { _mesh_z_var = z_var; }
set_time()
void libMesh::DiffContext::set_time (Real time_in) inline inherited
Set the time for which the current nonlinear_solution is defined.
Definition at line 427 of file diff_context.h.
References libMesh::DiffContext::time.
Referenced by _update_time_from_system().
   { time = time_in; }
side_accel()
template<typename OutputType > template void libMesh::FEMContext::side_accel< Gradient > (unsigned int var, unsigned int qp, OutputType & u) const
Returns
The second time derivative (acceleration) of the solution variable var at the quadrature point qp on the current element side.
Definition at line 1287 of file fem_context.C.
References libMesh::DiffContext::get_elem_solution_accel(), get_side_fe(), and some_value().
 {
   this->some_value<OutputType,
                    &FEMContext::get_side_fe
                    <typename TensorTools::MakeReal<OutputType>::type>,
                    &DiffContext::get_elem_solution_accel>(var, qp, u);
 }
side_boundary_ids() [1/2]
std::vector< boundary_id_type > libMesh::FEMContext::side_boundary_ids () const
Lists the boundary ids found on the current side
Deprecated:
Instead, use the version that takes a reference to a std::set.
Definition at line 196 of file fem_context.C.
References _boundary_info, libMesh::BoundaryInfo::boundary_ids(), get_elem(), and side.
 {
   libmesh_deprecated();
   return _boundary_info.boundary_ids(&(this->get_elem()), side);
 }
side_boundary_ids() [2/2]
void libMesh::FEMContext::side_boundary_ids (std::vector< boundary_id_type > & vec_to_fill) const
As above, but fills in the std::set provided by the user.
Definition at line 204 of file fem_context.C.
References _boundary_info, libMesh::BoundaryInfo::boundary_ids(), get_elem(), and side.
 {
   _boundary_info.boundary_ids(&(this->get_elem()), side, vec_to_fill);
 }
side_fe_reinit()
void libMesh::FEMContext::side_fe_reinit () virtual
Reinitializes side FE objects on the current geometric element
Reimplemented in libMesh::DGFEMContext.
Definition at line 1383 of file fem_context.C.
References _side_fe, get_elem(), get_elem_dim(), and get_side().
Referenced by elem_side_reinit(), libMesh::GenericProjector< FFunctor, GFunctor, FValue, ProjectionAction >::operator()(), and libMesh::DGFEMContext::side_fe_reinit().
 {
   // Initialize all the side FE objects on elem/side.
   // Logging of FE::reinit is done in the FE functions
   // We only reinit the FE objects for the current element
   // dimension
   const unsigned char dim = this->get_elem_dim();
   libmesh_assert( !_side_fe[dim].empty() );
   for (auto & pr : _side_fe[dim])
     pr.second->reinit(&(this->get_elem()), this->get_side());
 }
side_gradient() [1/2]
Gradient libMesh::FEMContext::side_gradient (unsigned int var, unsigned int qp) const
Returns
The gradient of the solution variable var at the quadrature point qp on the current element side.
Note
This API is currently present for backward compatibility.
Definition at line 613 of file fem_context.C.
 {
   Gradient du;
   this->side_gradient( var, qp, du );
   return du;
 }
side_gradient() [2/2]
template<typename OutputType > void libMesh::FEMContext::side_gradient (unsigned int var, unsigned int qp, OutputType & du) const
Returns
The gradient of the solution variable var at the quadrature point qp on the current element side.
Note
This is the preferred API.
Definition at line 624 of file fem_context.C.
References libMesh::DiffContext::_elem_subsolutions, libMesh::DiffContext::get_dof_indices(), libMesh::FEGenericBase< OutputType >::get_dphi(), get_elem_dim(), and libMesh::DiffContext::get_elem_solution().
 {
   typedef typename TensorTools::MakeReal
     <typename TensorTools::DecrementRank<OutputType>::type>::type
     OutputShape;
   // Get local-to-global dof index lookup
   const unsigned int n_dofs = cast_int<unsigned int>
     (this->get_dof_indices(var).size());
   // Get current local coefficients
   libmesh_assert_greater (this->_elem_subsolutions.size(), var);
   const DenseSubVector<Number> & coef = this->get_elem_solution(var);
   // Get finite element object
   FEGenericBase<OutputShape> * the_side_fe = nullptr;
   this->get_side_fe<OutputShape>( var, the_side_fe, this->get_elem_dim() );
   // Get shape function values at quadrature point
   const std::vector<std::vector<typename FEGenericBase<OutputShape>::OutputGradient>> & dphi = the_side_fe->get_dphi();
   // Accumulate solution derivatives
   du = 0.;
   for (unsigned int l=0; l != n_dofs; l++)
     du.add_scaled(dphi[l][qp], coef(l));
   return;
 }
side_gradients()
template<typename OutputType > template void libMesh::FEMContext::side_gradients< Tensor > (unsigned int var, const NumericVector< Number > & _system_vector, std::vector< OutputType > & side_gradients_vector) const
Fills a vector with the gradient of the solution variable var at all the quadrature points on the current element side.
Note
This is the preferred API.
Definition at line 658 of file fem_context.C.
References libMesh::DiffContext::get_dof_indices(), libMesh::FEGenericBase< OutputType >::get_dphi(), get_elem_dim(), and libMesh::DiffContext::get_localized_subvector().
 {
   typedef typename TensorTools::MakeReal
     <typename TensorTools::DecrementRank<OutputType>::type>::type
     OutputShape;
   // Get local-to-global dof index lookup
   const unsigned int n_dofs = cast_int<unsigned int>
     (this->get_dof_indices(var).size());
   // Get current local coefficients
   const DenseSubVector<Number> & coef = get_localized_subvector(_system_vector, var);
   // Get finite element object
   FEGenericBase<OutputShape> * the_side_fe = nullptr;
   this->get_side_fe<OutputShape>( var, the_side_fe, this->get_elem_dim() );
   // Get shape function values at quadrature point
   const std::vector<std::vector<typename FEGenericBase<OutputShape>::OutputGradient>> & dphi = the_side_fe->get_dphi();
   // Loop over all the q_points in this finite element
   for (std::size_t qp=0; qp != du_vals.size(); qp++)
     {
       OutputType & du = du_vals[qp];
       du = 0;
       // Compute the gradient at this q_point
       for (unsigned int l=0; l != n_dofs; l++)
         du.add_scaled(dphi[l][qp], coef(l));
     }
   return;
 }
side_hessian() [1/2]
Tensor libMesh::FEMContext::side_hessian (unsigned int var, unsigned int qp) const
Returns
The hessian of the solution variable var at the quadrature point qp on the current element side.
Note
This API is currently present for backward compatibility.
Definition at line 696 of file fem_context.C.
 {
   Tensor d2u;
   this->side_hessian( var, qp, d2u );
   return d2u;
 }
side_hessian() [2/2]
template<typename OutputType > void libMesh::FEMContext::side_hessian (unsigned int var, unsigned int qp, OutputType & d2u) const
Returns
The hessian of the solution variable var at the quadrature point qp on the current element side.
Note
This is the preferred API.
Definition at line 709 of file fem_context.C.
References libMesh::DiffContext::get_elem_solution(), get_side_fe(), and some_hessian().
 {
   this->some_hessian<OutputType,
                      &FEMContext::get_side_fe
                      <typename TensorTools::MakeReal
                       <typename TensorTools::DecrementRank
                        <typename TensorTools::DecrementRank
                         <OutputType>::type>::type>::type>,
                      &DiffContext::get_elem_solution>(var, qp, d2u);
 }
side_hessians()
template<typename OutputType > template void libMesh::FEMContext::side_hessians< Tensor > (unsigned int var, const NumericVector< Number > & _system_vector, std::vector< OutputType > & d2u_vals) const
Fills a vector of hessians of the _system_vector at the all the quadrature points on the current element side. This is the preferred API.
Definition at line 725 of file fem_context.C.
References libMesh::FEGenericBase< OutputType >::get_d2phi(), libMesh::DiffContext::get_dof_indices(), get_elem_dim(), and libMesh::DiffContext::get_localized_subvector().
 {
   typedef typename TensorTools::DecrementRank<OutputType>::type Rank1Decrement;
   typedef typename TensorTools::DecrementRank<Rank1Decrement>::type Rank2Decrement;
   typedef typename TensorTools::MakeReal<Rank2Decrement>::type OutputShape;
   // Get local-to-global dof index lookup
   const unsigned int n_dofs = cast_int<unsigned int>
     (this->get_dof_indices(var).size());
   // Get current local coefficients
   const DenseSubVector<Number> & coef = get_localized_subvector(_system_vector, var);
   // Get finite element object
   FEGenericBase<OutputShape> * the_side_fe = nullptr;
   this->get_side_fe<OutputShape>( var, the_side_fe, this->get_elem_dim() );
   // Get shape function values at quadrature point
   const std::vector<std::vector<typename FEGenericBase<OutputShape>::OutputTensor>> & d2phi = the_side_fe->get_d2phi();
   // Loop over all the q_points in this finite element
   for (std::size_t qp=0; qp != d2u_vals.size(); qp++)
     {
       OutputType & d2u = d2u_vals[qp];
       // Compute the gradient at this q_point
       d2u = 0;
       for (unsigned int l=0; l != n_dofs; l++)
         d2u.add_scaled(d2phi[l][qp], coef(l));
     }
   return;
 }
side_rate()
template<typename OutputType > template void libMesh::FEMContext::side_rate< Gradient > (unsigned int var, unsigned int qp, OutputType & u) const
Returns
The time derivative (rate) of the solution variable var at the quadrature point qp on the current element side.
Definition at line 1265 of file fem_context.C.
References libMesh::DiffContext::get_elem_solution_rate(), get_side_fe(), and some_value().
 {
   this->some_value<OutputType,
                    &FEMContext::get_side_fe
                    <typename TensorTools::MakeReal<OutputType>::type>,
                    &DiffContext::get_elem_solution_rate>(var, qp, u);
 }
side_value() [1/2]
Number libMesh::FEMContext::side_value (unsigned int var, unsigned int qp) const
Returns
The value of the solution variable var at the quadrature point qp on the current element side.
Note
This API currently is present for backward compatibility.
Definition at line 555 of file fem_context.C.
 {
   Number u = 0.;
   this->side_value( var, qp, u );
   return u;
 }
side_value() [2/2]
template<typename OutputType > void libMesh::FEMContext::side_value (unsigned int var, unsigned int qp, OutputType & u) const
Returns
The value of the solution variable var at the quadrature point qp on the current element side.
Note
This is the preferred API.
Definition at line 567 of file fem_context.C.
References libMesh::DiffContext::get_elem_solution(), and some_value().
 {
   this->some_value<OutputType,
                    &FEMContext::get_side_fe<typename TensorTools::MakeReal<OutputType>::type>,
                    &DiffContext::get_elem_solution>(var, qp, u);
 }
side_values()
template<typename OutputType > template void libMesh::FEMContext::side_values< Gradient > (unsigned int var, const NumericVector< Number > & _system_vector, std::vector< OutputType > & side_values_vector) const
Fills a vector of values of the _system_vector at the all the quadrature points on the current element side.
Definition at line 578 of file fem_context.C.
References libMesh::DiffContext::get_dof_indices(), get_elem_dim(), libMesh::DiffContext::get_localized_subvector(), and libMesh::FEGenericBase< OutputType >::get_phi().
 {
   typedef typename TensorTools::MakeReal<OutputType>::type OutputShape;
   // Get local-to-global dof index lookup
   const unsigned int n_dofs = cast_int<unsigned int>
     (this->get_dof_indices(var).size());
   // Get current local coefficients
   const DenseSubVector<Number> & coef = get_localized_subvector(_system_vector, var);
   // Get the finite element object
   FEGenericBase<OutputShape> * the_side_fe = nullptr;
   this->get_side_fe<OutputShape>( var, the_side_fe, this->get_elem_dim() );
   // Get shape function values at quadrature point
   const std::vector<std::vector<OutputShape>> & phi = the_side_fe->get_phi();
   // Loop over all the q_points on this element
   for (std::size_t qp=0; qp != u_vals.size(); qp++)
     {
       OutputType & u = u_vals[qp];
       // Compute the value at this q_point
       u = 0.;
       for (unsigned int l=0; l != n_dofs; l++)
         u += phi[l][qp] * coef(l);
     }
   return;
 }
some_gradient()
template<typename OutputType , typename FEMContext::FENeeded< OutputType >::grad_getter fe_getter, FEMContext::diff_subsolution_getter subsolution_getter> void libMesh::FEMContext::some_gradient (unsigned int var, unsigned int qp, OutputType & u) const protected
Helper function to reduce some code duplication in the *interior_gradient methods.
Definition at line 243 of file fem_context.C.
References libMesh::DiffContext::get_dof_indices(), libMesh::FEGenericBase< OutputType >::get_dphi(), and get_elem_dim().
Referenced by fixed_interior_gradient(), fixed_side_gradient(), and interior_gradient().
 {
   // Get local-to-global dof index lookup
   const unsigned int n_dofs = cast_int<unsigned int>
     (this->get_dof_indices(var).size());
   // Get current local coefficients
   const DenseSubVector<Number> & coef = (this->*subsolution_getter)(var);
   // Get finite element object
   typename FENeeded<OutputType>::grad_base * fe = nullptr;
   (this->*fe_getter)( var, fe, this->get_elem_dim() );
   // Get shape function values at quadrature point
   const std::vector<std::vector
                     <typename FENeeded<OutputType>::grad_base::OutputGradient>>
     & dphi = fe->get_dphi();
   // Accumulate solution derivatives
   du = 0;
   for (unsigned int l=0; l != n_dofs; l++)
     du.add_scaled(dphi[l][qp], coef(l));
   return;
 }
some_hessian()
template<typename OutputType , typename FEMContext::FENeeded< OutputType >::hess_getter fe_getter, FEMContext::diff_subsolution_getter subsolution_getter> void libMesh::FEMContext::some_hessian (unsigned int var, unsigned int qp, OutputType & u) const protected
Helper function to reduce some code duplication in the *interior_hessian methods.
Definition at line 276 of file fem_context.C.
References libMesh::FEGenericBase< OutputType >::get_d2phi(), libMesh::DiffContext::get_dof_indices(), and get_elem_dim().
Referenced by fixed_interior_hessian(), fixed_side_hessian(), interior_hessian(), and side_hessian().
 {
   // Get local-to-global dof index lookup
   const unsigned int n_dofs = cast_int<unsigned int>
     (this->get_dof_indices(var).size());
   // Get current local coefficients
   const DenseSubVector<Number> & coef = (this->*subsolution_getter)(var);
   // Get finite element object
   typename FENeeded<OutputType>::hess_base * fe = nullptr;
   (this->*fe_getter)( var, fe, this->get_elem_dim() );
   // Get shape function values at quadrature point
   const std::vector<std::vector
                     <typename FENeeded<OutputType>::hess_base::OutputTensor>>
     & d2phi = fe->get_d2phi();
   // Accumulate solution second derivatives
   d2u = 0.0;
   for (unsigned int l=0; l != n_dofs; l++)
     d2u.add_scaled(d2phi[l][qp], coef(l));
   return;
 }
some_value()
template<typename OutputType , typename FEMContext::FENeeded< OutputType >::value_getter fe_getter, FEMContext::diff_subsolution_getter subsolution_getter> void libMesh::FEMContext::some_value (unsigned int var, unsigned int qp, OutputType & u) const protected
Helper function to reduce some code duplication in the *interior_value methods.
Definition at line 214 of file fem_context.C.
References libMesh::DiffContext::get_dof_indices(), get_elem_dim(), and libMesh::FEGenericBase< OutputType >::get_phi().
Referenced by fixed_interior_value(), fixed_side_value(), interior_accel(), interior_rate(), interior_value(), side_accel(), side_rate(), and side_value().
 {
   // Get local-to-global dof index lookup
   const unsigned int n_dofs = cast_int<unsigned int>
     (this->get_dof_indices(var).size());
   // Get current local coefficients
   const DenseSubVector<Number> & coef = (this->*subsolution_getter)(var);
   // Get finite element object
   typename FENeeded<OutputType>::value_base * fe = nullptr;
   (this->*fe_getter)( var, fe, this->get_elem_dim() );
   // Get shape function values at quadrature point
   const std::vector<std::vector
                     <typename FENeeded<OutputType>::value_shape>> & phi = fe->get_phi();
   // Accumulate solution value
   u = 0.;
   for (unsigned int l=0; l != n_dofs; l++)
     u += phi[l][qp] * coef(l);
 }
Member Data Documentation
_atype
AlgebraicType libMesh::FEMContext::_atype protected
Keep track of what type of algebra reinitialization is to be done
Definition at line 999 of file fem_context.h.
Referenced by algebraic_type(), and set_algebraic_type().
_boundary_info
const BoundaryInfo& libMesh::FEMContext::_boundary_info protected
Saved reference to BoundaryInfo on the mesh for this System. Used to answer boundary id requests.
Definition at line 1114 of file fem_context.h.
Referenced by has_side_boundary_id(), and side_boundary_ids().
_custom_solution
const NumericVector<Number>* libMesh::FEMContext::_custom_solution protected
Data with which to do algebra reinitialization
Definition at line 1004 of file fem_context.h.
Referenced by pre_fe_reinit(), and set_custom_solution().
_dim
unsigned char libMesh::FEMContext::_dim protected
Cached dimension of largest dimension element in this mesh
Definition at line 1124 of file fem_context.h.
Referenced by libMesh::DGFEMContext::DGFEMContext(), and get_dim().
_dof_indices
std::vector<dof_id_type> libMesh::DiffContext::_dof_indices protected inherited
Global Degree of freedom index lists
Definition at line 637 of file diff_context.h.
Referenced by libMesh::DiffContext::get_dof_indices(), and libMesh::DiffContext::n_dof_indices().
_dof_indices_var
std::vector<std::vector<dof_id_type> > libMesh::DiffContext::_dof_indices_var protected inherited
Definition at line 638 of file diff_context.h.
Referenced by libMesh::DiffContext::get_dof_indices(), libMesh::DiffContext::n_dof_indices(), and libMesh::DiffContext::n_vars().
_edge_fe
std::map<FEType, std::unique_ptr<FEAbstract> > libMesh::FEMContext::_edge_fe protected
Definition at line 1097 of file fem_context.h.
Referenced by edge_fe_reinit(), and init_internal_data().
_edge_fe_var
std::vector<FEAbstract *> libMesh::FEMContext::_edge_fe_var protected
Definition at line 1108 of file fem_context.h.
Referenced by get_edge_fe(), and init_internal_data().
_edge_qrule
std::unique_ptr<QBase> libMesh::FEMContext::_edge_qrule protected
Quadrature rules for element edges. If the FEM context is told to prepare for edge integration on 3D elements, it will try to find a quadrature rule that correctly integrates all variables. Because edge rules only apply to 3D elements, we don't need to worry about multiple dimensions
Definition at line 1160 of file fem_context.h.
Referenced by get_edge_qrule(), and init_internal_data().
_elem
const Elem* libMesh::FEMContext::_elem protected
Current element for element_* to examine
Definition at line 1119 of file fem_context.h.
Referenced by get_elem(), has_elem(), and set_elem().
_elem_dim
unsigned char libMesh::FEMContext::_elem_dim protected
Cached dimension of this->_elem.
Definition at line 1129 of file fem_context.h.
Referenced by get_elem_dim(), and set_elem().
_elem_dims
std::set<unsigned char> libMesh::FEMContext::_elem_dims protected
Cached dimensions of elements in the mesh, plus dimension 0 if SCALAR variables are in use.
Definition at line 1135 of file fem_context.h.
Referenced by elem_dimensions(), and init_internal_data().
_elem_fixed_solution
DenseVector<Number> libMesh::DiffContext::_elem_fixed_solution protected inherited
Element by element components of nonlinear_solution at a fixed point in a timestep, for optional use by e.g. stabilized methods
Definition at line 603 of file diff_context.h.
Referenced by libMesh::DiffContext::DiffContext(), and libMesh::DiffContext::get_elem_fixed_solution().
_elem_fixed_subsolutions
std::vector<std::unique_ptr<DenseSubVector<Number> > > libMesh::DiffContext::_elem_fixed_subsolutions protected inherited
Definition at line 604 of file diff_context.h.
Referenced by libMesh::DiffContext::DiffContext(), fixed_point_gradient(), fixed_point_hessian(), fixed_point_value(), and libMesh::DiffContext::get_elem_fixed_solution().
_elem_jacobian
DenseMatrix<Number> libMesh::DiffContext::_elem_jacobian protected inherited
Element jacobian: derivatives of elem_residual with respect to elem_solution
Definition at line 615 of file diff_context.h.
Referenced by libMesh::DiffContext::DiffContext(), and libMesh::DiffContext::get_elem_jacobian().
_elem_qoi
std::vector<Number> libMesh::DiffContext::_elem_qoi protected inherited
Element quantity of interest contributions
Definition at line 620 of file diff_context.h.
Referenced by libMesh::DiffContext::DiffContext(), and libMesh::DiffContext::get_qois().
_elem_qoi_derivative
std::vector<DenseVector<Number> > libMesh::DiffContext::_elem_qoi_derivative protected inherited
Element quantity of interest derivative contributions
Definition at line 625 of file diff_context.h.
Referenced by libMesh::DiffContext::DiffContext(), and libMesh::DiffContext::get_qoi_derivatives().
_elem_qoi_subderivatives
std::vector<std::vector<std::unique_ptr<DenseSubVector<Number> > > > libMesh::DiffContext::_elem_qoi_subderivatives protected inherited
Definition at line 626 of file diff_context.h.
Referenced by libMesh::DiffContext::DiffContext(), libMesh::DiffContext::get_qoi_derivatives(), and pre_fe_reinit().
_elem_residual
DenseVector<Number> libMesh::DiffContext::_elem_residual protected inherited
Element residual vector
Definition at line 609 of file diff_context.h.
Referenced by libMesh::DiffContext::DiffContext(), and libMesh::DiffContext::get_elem_residual().
_elem_solution
DenseVector<Number> libMesh::DiffContext::_elem_solution protected inherited
Element by element components of nonlinear_solution as adjusted by a time_solver
Definition at line 581 of file diff_context.h.
Referenced by libMesh::DiffContext::DiffContext(), and libMesh::DiffContext::get_elem_solution().
_elem_solution_accel
DenseVector<Number> libMesh::DiffContext::_elem_solution_accel protected inherited
Element by element components of du/dt as adjusted by a time_solver
Definition at line 595 of file diff_context.h.
Referenced by libMesh::DiffContext::DiffContext(), and libMesh::DiffContext::get_elem_solution_accel().
_elem_solution_rate
DenseVector<Number> libMesh::DiffContext::_elem_solution_rate protected inherited
Element by element components of du/dt as adjusted by a time_solver
Definition at line 588 of file diff_context.h.
Referenced by libMesh::DiffContext::DiffContext(), and libMesh::DiffContext::get_elem_solution_rate().
_elem_subjacobians
std::vector<std::vector<std::unique_ptr<DenseSubMatrix<Number> > > > libMesh::DiffContext::_elem_subjacobians protected inherited
Definition at line 632 of file diff_context.h.
Referenced by libMesh::DiffContext::DiffContext(), and libMesh::DiffContext::get_elem_jacobian().
_elem_subresiduals
std::vector<std::unique_ptr<DenseSubVector<Number> > > libMesh::DiffContext::_elem_subresiduals protected inherited
Element residual subvectors and Jacobian submatrices
Definition at line 631 of file diff_context.h.
Referenced by libMesh::DiffContext::DiffContext(), and libMesh::DiffContext::get_elem_residual().
_elem_subsolution_accels
std::vector<std::unique_ptr<DenseSubVector<Number> > > libMesh::DiffContext::_elem_subsolution_accels protected inherited
Definition at line 596 of file diff_context.h.
Referenced by libMesh::DiffContext::DiffContext(), and libMesh::DiffContext::get_elem_solution_accel().
_elem_subsolution_rates
std::vector<std::unique_ptr<DenseSubVector<Number> > > libMesh::DiffContext::_elem_subsolution_rates protected inherited
Definition at line 589 of file diff_context.h.
Referenced by libMesh::DiffContext::DiffContext(), and libMesh::DiffContext::get_elem_solution_rate().
_elem_subsolutions
std::vector<std::unique_ptr<DenseSubVector<Number> > > libMesh::DiffContext::_elem_subsolutions protected inherited
Definition at line 582 of file diff_context.h.
Referenced by libMesh::DiffContext::DiffContext(), libMesh::DiffContext::get_elem_solution(), interior_curl(), interior_div(), point_curl(), point_gradient(), point_hessian(), point_value(), and side_gradient().
_element_fe
std::vector<std::map<FEType, std::unique_ptr<FEAbstract> > > libMesh::FEMContext::_element_fe protected
Finite element objects for each variable's interior, sides and edges. We store FE objects for each element dimension present in the mesh, except for edge_fe which only applies to 3D elements.
Definition at line 1095 of file fem_context.h.
Referenced by elem_fe_reinit(), and init_internal_data().
_element_fe_var
std::vector<std::vector<FEAbstract *> > libMesh::FEMContext::_element_fe_var protected
Pointers to the same finite element objects, but indexed by variable number. We store FE objects for each element dimension present in the mesh, except for edge_fe_var which only applies for 3D elements.
Definition at line 1106 of file fem_context.h.
Referenced by get_element_fe(), and init_internal_data().
_element_qrule
std::vector<std::unique_ptr<QBase> > libMesh::FEMContext::_element_qrule protected
Quadrature rule for element interior. The FEM context will try to find a quadrature rule that correctly integrates all variables. We prepare quadrature rules for each element dimension in the mesh.
Definition at line 1143 of file fem_context.h.
Referenced by get_element_qrule(), and init_internal_data().
_extra_quadrature_order
int libMesh::FEMContext::_extra_quadrature_order protected
The extra quadrature order for this context.
Definition at line 1165 of file fem_context.h.
Referenced by init_internal_data().
_localized_vectors
std::map<const NumericVector<Number> *, std::pair<DenseVector<Number>, std::vector<std::unique_ptr<DenseSubVector<Number> > > > > libMesh::DiffContext::_localized_vectors protected inherited
Contains pointers to vectors the user has asked to be localized, keyed with pairs of element localized versions of that vector and per variable views
Definition at line 575 of file diff_context.h.
Referenced by libMesh::DiffContext::add_localized_vector(), libMesh::DiffContext::get_localized_subvector(), libMesh::DiffContext::get_localized_vector(), and pre_fe_reinit().
_mesh_sys
System* libMesh::FEMContext::_mesh_sys
System from which to acquire moving mesh information
Definition at line 969 of file fem_context.h.
Referenced by _do_elem_position_set(), elem_edge_reinit(), elem_position_get(), elem_position_set(), elem_reinit(), elem_side_reinit(), get_mesh_system(), and set_mesh_system().
_mesh_x_var
unsigned int libMesh::FEMContext::_mesh_x_var
Variables from which to acquire moving mesh information
Definition at line 974 of file fem_context.h.
Referenced by get_mesh_x_var(), and set_mesh_x_var().
_mesh_y_var
unsigned int libMesh::FEMContext::_mesh_y_var
Definition at line 974 of file fem_context.h.
Referenced by get_mesh_y_var(), and set_mesh_y_var().
_mesh_z_var
unsigned int libMesh::FEMContext::_mesh_z_var
Definition at line 974 of file fem_context.h.
Referenced by get_mesh_z_var(), and set_mesh_z_var().
_real_fe
std::unique_ptr<FEGenericBase<Real> > libMesh::FEMContext::_real_fe mutable protected
Definition at line 1006 of file fem_context.h.
Referenced by cached_fe().
_real_fe_is_inf
bool libMesh::FEMContext::_real_fe_is_inf mutable protected
Definition at line 1010 of file fem_context.h.
Referenced by cached_fe().
_real_grad_fe
std::unique_ptr<FEGenericBase<RealGradient> > libMesh::FEMContext::_real_grad_fe mutable protected
Definition at line 1007 of file fem_context.h.
Referenced by cached_fe().
_real_grad_fe_is_inf
bool libMesh::FEMContext::_real_grad_fe_is_inf mutable protected
Definition at line 1011 of file fem_context.h.
Referenced by cached_fe().
_side_fe
std::vector<std::map<FEType, std::unique_ptr<FEAbstract> > > libMesh::FEMContext::_side_fe protected
Definition at line 1096 of file fem_context.h.
Referenced by init_internal_data(), libMesh::DGFEMContext::neighbor_side_fe_reinit(), and side_fe_reinit().
_side_fe_var
std::vector<std::vector<FEAbstract *> > libMesh::FEMContext::_side_fe_var protected
Definition at line 1107 of file fem_context.h.
Referenced by get_side_fe(), and init_internal_data().
_side_qrule
std::vector<std::unique_ptr<QBase> > libMesh::FEMContext::_side_qrule protected
Quadrature rules for element sides The FEM context will try to find a quadrature rule that correctly integrates all variables. We prepare quadrature rules for each element dimension in the mesh.
Definition at line 1151 of file fem_context.h.
Referenced by get_side_qrule(), and init_internal_data().
edge
unsigned char libMesh::FEMContext::edge
Current edge for edge_* to examine
Definition at line 984 of file fem_context.h.
Referenced by get_edge(), and libMesh::GenericProjector< FFunctor, GFunctor, FValue, ProjectionAction >::operator()().
elem_solution_accel_derivative
Real libMesh::DiffContext::elem_solution_accel_derivative inherited
The derivative of elem_solution_accel with respect to the current nonlinear solution, for use by systems with non default mass_residual terms.
Definition at line 514 of file diff_context.h.
Referenced by libMesh::NewmarkSolver::_general_residual(), libMesh::DiffContext::get_elem_solution_accel_derivative(), and libMesh::FirstOrderUnsteadySolver::prepare_accel().
elem_solution_derivative
Real libMesh::DiffContext::elem_solution_derivative inherited
The derivative of elem_solution with respect to the current nonlinear solution.
Definition at line 500 of file diff_context.h.
Referenced by libMesh::EulerSolver::_general_residual(), libMesh::Euler2Solver::_general_residual(), libMesh::NewmarkSolver::_general_residual(), libMesh::EigenTimeSolver::element_residual(), libMesh::DiffContext::get_elem_solution_derivative(), and libMesh::EigenTimeSolver::side_residual().
elem_solution_rate_derivative
Real libMesh::DiffContext::elem_solution_rate_derivative inherited
The derivative of elem_solution_rate with respect to the current nonlinear solution, for use by systems with non default mass_residual terms.
Definition at line 507 of file diff_context.h.
Referenced by libMesh::EulerSolver::_general_residual(), libMesh::Euler2Solver::_general_residual(), libMesh::NewmarkSolver::_general_residual(), libMesh::EigenTimeSolver::element_residual(), libMesh::DiffContext::get_elem_solution_rate_derivative(), and libMesh::EigenTimeSolver::side_residual().
fixed_solution_derivative
Real libMesh::DiffContext::fixed_solution_derivative inherited
The derivative of elem_fixed_solution with respect to the nonlinear solution, for use by systems constructing jacobians with elem_fixed_solution based methods
Definition at line 521 of file diff_context.h.
Referenced by libMesh::EulerSolver::_general_residual(), libMesh::Euler2Solver::_general_residual(), libMesh::SteadySolver::_general_residual(), and libMesh::DiffContext::get_fixed_solution_derivative().
side
unsigned char libMesh::FEMContext::side
Current side for side_* to examine
Definition at line 979 of file fem_context.h.
Referenced by get_side(), has_side_boundary_id(), libMesh::GenericProjector< FFunctor, GFunctor, FValue, ProjectionAction >::operator()(), and side_boundary_ids().
system_time
const Real libMesh::DiffContext::system_time inherited
This is the time stored in the System class at the time this context was created, i.e. the time at the beginning of the current timestep. This value gets set in the constructor and unlike DiffContext::time, is not tweaked mid-timestep by transient solvers: it remains equal to the value it was assigned at construction.
Definition at line 494 of file diff_context.h.
Referenced by libMesh::DiffContext::get_system_time().
time
Real libMesh::DiffContext::time inherited
For time-dependent problems, this is the time t for which the current nonlinear_solution is defined. FIXME - this needs to be tweaked mid-timestep by all transient solvers!
Definition at line 485 of file diff_context.h.
Referenced by libMesh::DiffContext::get_time(), libMesh::GenericProjector< FFunctor, GFunctor, FValue, ProjectionAction >::operator()(), and libMesh::DiffContext::set_time().
The documentation for this class was generated from the following files:
fem_context.h
fem_context.C