libMesh: libMesh::Partitioner Class Reference
SomeWebsiteLogo
libMesh::Partitioner Class Reference abstract
Base class for all concrete Partitioner instantiations.
#include <partitioner.h>
Public Member Functions
Partitioner ()
virtual ~Partitioner ()
virtual UniquePtr< Partitioner > clone () const =0
virtual void partition (MeshBase &mesh, const unsigned int n)
virtual void partition (MeshBase &mesh)
virtual void partition_range (MeshBase &, MeshBase::element_iterator, MeshBase::element_iterator, const unsigned int)
void repartition (MeshBase &mesh, const unsigned int n)
void repartition (MeshBase &mesh)
virtual void attach_weights (ErrorVector *)
Static Public Member Functions
static void partition_unpartitioned_elements (MeshBase &mesh)
static void partition_unpartitioned_elements (MeshBase &mesh, const unsigned int n)
static void set_parent_processor_ids (MeshBase &mesh)
static void set_node_processor_ids (MeshBase &mesh)
Protected Member Functions
void single_partition (MeshBase &mesh)
void single_partition_range (MeshBase::element_iterator it, MeshBase::element_iterator end)
virtual void _do_partition (MeshBase &mesh, const unsigned int n)=0
virtual void _do_repartition (MeshBase &mesh, const unsigned int n)
Protected Attributes
ErrorVector * _weights
Static Protected Attributes
static const dof_id_type communication_blocksize = 1000000
Detailed Description
Base class for all concrete Partitioner instantiations.
The Partitioner class provides a uniform interface for partitioning algorithms. It takes a reference to a MeshBase object as input, which it will partition into a number of subdomains.
Author
Benjamin S. Kirk
Date
2003
Definition at line 48 of file partitioner.h.
Constructor & Destructor Documentation
libMesh::Partitioner::Partitioner () inline
Constructor.
Definition at line 55 of file partitioner.h.
 : _weights(libmesh_nullptr) {}
virtual libMesh::Partitioner::~Partitioner () inline virtual
Destructor. Virtual so that we can derive from this class.
Definition at line 60 of file partitioner.h.
References clone(), mesh, and partition().
 {}
Member Function Documentation
virtual void libMesh::Partitioner::_do_partition (MeshBase & mesh, const unsigned int n) protected pure virtual
This is the actual partitioning method which must be overridden in derived classes. It is called via the public partition() method above by the user.
Implemented in libMesh::SubdomainPartitioner, libMesh::CentroidPartitioner, libMesh::MappedSubdomainPartitioner, libMesh::SFCPartitioner, libMesh::ParmetisPartitioner, libMesh::MetisPartitioner, libMesh::LinearPartitioner, libMesh::HilbertSFCPartitioner, and libMesh::MortonSFCPartitioner.
Referenced by _do_repartition(), attach_weights(), and partition().
virtual void libMesh::Partitioner::_do_repartition (MeshBase & mesh, const unsigned int n) inline protected virtual
This is the actual re-partitioning method which can be overridden in derived classes.
Note
The default behavior is to simply call the partition function.
Reimplemented in libMesh::ParmetisPartitioner.
Definition at line 204 of file partitioner.h.
References _do_partition().
Referenced by repartition().
                                                       { this->_do_partition (mesh, n); }
virtual void libMesh::Partitioner::attach_weights (ErrorVector *) inline virtual
Attach weights that can be used for partitioning. This ErrorVector should be exactly the same on every processor and should have mesh->max_elem_id() entries.
Reimplemented in libMesh::MetisPartitioner.
Definition at line 170 of file partitioner.h.
References _do_partition(), end, single_partition(), and single_partition_range().
 { libmesh_not_implemented(); }
virtual UniquePtr<Partitioner> libMesh::Partitioner::clone () const pure virtual
Returns
A copy of this partitioner wrapped in a smart pointer.
This is used when copying meshes, and must be overridden in the derived classes.
Implemented in libMesh::CentroidPartitioner, libMesh::SubdomainPartitioner, libMesh::ParmetisPartitioner, libMesh::SFCPartitioner, libMesh::MappedSubdomainPartitioner, libMesh::HilbertSFCPartitioner, libMesh::MortonSFCPartitioner, libMesh::LinearPartitioner, and libMesh::MetisPartitioner.
Referenced by ~Partitioner().
void libMesh::Partitioner::partition (MeshBase & mesh, const unsigned int n) virtual
Partitions the MeshBase into n parts by setting processor_id() on Nodes and Elems.
Note
If you are implementing a new type of Partitioner, you most likely do not want to override the partition() function, see instead the protected virtual _do_partition() method below. The partition() function is responsible for doing a lot of libmesh-internals-specific setup and finalization before and after the _do_partition() function is called. The only responsibility of the _do_partition() function, on the other hand, is to set the processor IDs of the elements according to a specific partitioning algorithm. See, e.g. MetisPartitioner for an example.
Definition at line 49 of file partitioner.C.
References _do_partition(), libMesh::ParallelObject::comm(), libMesh::MeshTools::libmesh_assert_valid_remote_elems(), mesh, std::min(), libMesh::MeshBase::n_active_elem(), partition_unpartitioned_elements(), libMesh::MeshBase::redistribute(), libMesh::MeshBase::set_n_partitions(), set_node_processor_ids(), set_parent_processor_ids(), single_partition(), and libMesh::MeshBase::update_post_partitioning().
Referenced by libMesh::ParmetisPartitioner::_do_repartition(), partition(), and ~Partitioner().
 {
   libmesh_parallel_only(mesh.comm());
   // BSK - temporary fix while redistribution is integrated 6/26/2008
   // Uncomment this to not repartition in parallel
   //   if (!mesh.is_serial())
   //     return;
   // we cannot partition into more pieces than we have
   // active elements!
   const unsigned int n_parts =
     static_cast<unsigned int>
     (std::min(mesh.n_active_elem(), static_cast<dof_id_type>(n)));
   // Set the number of partitions in the mesh
   mesh.set_n_partitions()=n_parts;
   if (n_parts == 1)
     {
       this->single_partition (mesh);
       return;
     }
   // First assign a temporary partitioning to any unpartitioned elements
   Partitioner::partition_unpartitioned_elements(mesh, n_parts);
   // Call the partitioning function
   this->_do_partition(mesh,n_parts);
   // Set the parent's processor ids
   Partitioner::set_parent_processor_ids(mesh);
   // Redistribute elements if necessary, before setting node processor
   // ids, to make sure those will be set consistently
   mesh.redistribute();
 #ifdef DEBUG
   MeshTools::libmesh_assert_valid_remote_elems(mesh);
   // Messed up elem processor_id()s can leave us without the child
   // elements we need to restrict vectors on a distributed mesh
   MeshTools::libmesh_assert_valid_procids<Elem>(mesh);
 #endif
   // Set the node's processor ids
   Partitioner::set_node_processor_ids(mesh);
 #ifdef DEBUG
   MeshTools::libmesh_assert_valid_procids<Elem>(mesh);
 #endif
   // Give derived Mesh classes a chance to update any cached data to
   // reflect the new partitioning
   mesh.update_post_partitioning();
 }
void libMesh::Partitioner::partition (MeshBase & mesh) virtual
Partitions the MeshBase into mesh.n_processors() by setting processor_id() on Nodes and Elems.
Note
If you are implementing a new type of Partitioner, you most likely do not want to override the partition() function, see instead the protected virtual _do_partition() method below. The partition() function is responsible for doing a lot of libmesh-internals-specific setup and finalization before and after the _do_partition() function is called. The only responsibility of the _do_partition() function, on the other hand, is to set the processor IDs of the elements according to a specific partitioning algorithm. See, e.g. MetisPartitioner for an example.
Definition at line 42 of file partitioner.C.
References libMesh::ParallelObject::n_processors(), and partition().
 {
   this->partition(mesh,mesh.n_processors());
 }
virtual void libMesh::Partitioner::partition_range (MeshBase & , MeshBase::element_iterator , MeshBase::element_iterator , const unsigned int) inline virtual
Partitions elements in the range (it, end) into n parts. The mesh from which the iterators are created must also be passed in, since it is a parallel object and has other useful information in it.
Although partition_range() is part of the public Partitioner interface, it should not generally be called by applications. Its main purpose is to support the SubdomainPartitioner, which uses it internally to individually partition ranges of elements before combining them into the final partitioning. Most of the time, the protected _do_partition() function is implemented in terms of partition_range() by passing a range which includes all the elements of the Mesh.
Reimplemented in libMesh::CentroidPartitioner, libMesh::MappedSubdomainPartitioner, libMesh::SFCPartitioner, libMesh::LinearPartitioner, and libMesh::MetisPartitioner.
Definition at line 120 of file partitioner.h.
References partition_unpartitioned_elements(), repartition(), set_node_processor_ids(), and set_parent_processor_ids().
   { libmesh_not_implemented(); }
void libMesh::Partitioner::partition_unpartitioned_elements (MeshBase & mesh) static
These functions assign processor IDs to newly-created elements (in parallel) which are currently assigned to processor 0.
Definition at line 175 of file partitioner.C.
References libMesh::ParallelObject::n_processors().
Referenced by partition(), partition_range(), and repartition().
 {
   Partitioner::partition_unpartitioned_elements(mesh, mesh.n_processors());
 }
void libMesh::Partitioner::partition_unpartitioned_elements (MeshBase & mesh, const unsigned int n) static
Definition at line 182 of file partitioner.C.
References libMesh::ParallelObject::comm(), libMesh::MeshTools::create_bounding_box(), end, libMesh::MeshCommunication::find_global_indices(), libMesh::MeshTools::n_elem(), libMesh::ParallelObject::n_processors(), libMesh::DofObject::processor_id(), libMesh::MeshBase::unpartitioned_elements_begin(), and libMesh::MeshBase::unpartitioned_elements_end().
 {
   MeshBase::element_iterator       it  = mesh.unpartitioned_elements_begin();
   const MeshBase::element_iterator end = mesh.unpartitioned_elements_end();
   const dof_id_type n_unpartitioned_elements = MeshTools::n_elem (it, end);
   // the unpartitioned elements must exist on all processors. If the range is empty on one
   // it is empty on all, and we can quit right here.
   if (!n_unpartitioned_elements) return;
   // find the target subdomain sizes
   std::vector<dof_id_type> subdomain_bounds(mesh.n_processors());
   for (processor_id_type pid=0; pid<mesh.n_processors(); pid++)
     {
       dof_id_type tgt_subdomain_size = 0;
       // watch out for the case that n_subdomains < n_processors
       if (pid < n_subdomains)
         {
           tgt_subdomain_size = n_unpartitioned_elements/n_subdomains;
           if (pid < n_unpartitioned_elements%n_subdomains)
             tgt_subdomain_size++;
         }
       //libMesh::out << "pid, #= " << pid << ", " << tgt_subdomain_size << std::endl;
       if (pid == 0)
         subdomain_bounds[0] = tgt_subdomain_size;
       else
         subdomain_bounds[pid] = subdomain_bounds[pid-1] + tgt_subdomain_size;
     }
   libmesh_assert_equal_to (subdomain_bounds.back(), n_unpartitioned_elements);
   // create the unique mapping for all unpartitioned elements independent of partitioning
   // determine the global indexing for all the unpartitioned elements
   std::vector<dof_id_type> global_indices;
   // Calling this on all processors a unique range in [0,n_unpartitioned_elements) is constructed.
   // Only the indices for the elements we pass in are returned in the array.
   MeshCommunication().find_global_indices (mesh.comm(),
                                            MeshTools::create_bounding_box(mesh), it, end,
                                            global_indices);
   for (dof_id_type cnt=0; it != end; ++it)
     {
       Elem * elem = *it;
       libmesh_assert_less (cnt, global_indices.size());
       const dof_id_type global_index =
         global_indices[cnt++];
       libmesh_assert_less (global_index, subdomain_bounds.back());
       libmesh_assert_less (global_index, n_unpartitioned_elements);
       const processor_id_type subdomain_id =
         cast_int<processor_id_type>
         (std::distance(subdomain_bounds.begin(),
                        std::upper_bound(subdomain_bounds.begin(),
                                         subdomain_bounds.end(),
                                         global_index)));
       libmesh_assert_less (subdomain_id, n_subdomains);
       elem->processor_id() = subdomain_id;
       //libMesh::out << "assigning " << global_index << " to " << subdomain_id << std::endl;
     }
 }
void libMesh::Partitioner::repartition (MeshBase & mesh, const unsigned int n)
Repartitions the MeshBase into n parts. (Some partitioning algorithms can repartition more efficiently than computing a new partitioning from scratch.) The default behavior is to simply call this->partition(mesh,n).
Definition at line 116 of file partitioner.C.
References _do_repartition(), std::min(), libMesh::MeshBase::n_active_elem(), partition_unpartitioned_elements(), libMesh::MeshBase::set_n_partitions(), set_node_processor_ids(), set_parent_processor_ids(), and single_partition().
Referenced by partition_range(), and repartition().
 {
   // we cannot partition into more pieces than we have
   // active elements!
   const unsigned int n_parts =
     static_cast<unsigned int>
     (std::min(mesh.n_active_elem(), static_cast<dof_id_type>(n)));
   // Set the number of partitions in the mesh
   mesh.set_n_partitions()=n_parts;
   if (n_parts == 1)
     {
       this->single_partition (mesh);
       return;
     }
   // First assign a temporary partitioning to any unpartitioned elements
   Partitioner::partition_unpartitioned_elements(mesh, n_parts);
   // Call the partitioning function
   this->_do_repartition(mesh,n_parts);
   // Set the parent's processor ids
   Partitioner::set_parent_processor_ids(mesh);
   // Set the node's processor ids
   Partitioner::set_node_processor_ids(mesh);
 }
void libMesh::Partitioner::repartition (MeshBase & mesh)
Repartitions the MeshBase into mesh.n_processors() parts. This is required since some partitioning algorithms can repartition more efficiently than computing a new partitioning from scratch.
Definition at line 109 of file partitioner.C.
References libMesh::ParallelObject::n_processors(), and repartition().
 {
   this->repartition(mesh,mesh.n_processors());
 }
void libMesh::Partitioner::set_node_processor_ids (MeshBase & mesh) static
This function is called after partitioning to set the processor IDs for the nodes. By definition, a Node's processor ID is the minimum processor ID for all of the elements which share the node.
Definition at line 431 of file partitioner.C.
References libMesh::MeshBase::active_elements_begin(), libMesh::MeshBase::active_elements_end(), libMesh::ParallelObject::comm(), libMesh::DofObject::id(), libMesh::DofObject::invalid_processor_id, libMesh::DofObject::invalidate_processor_id(), libMesh::libmesh_assert(), mesh, std::min(), libMesh::MeshTools::n_elem(), libMesh::Elem::n_nodes(), libMesh::ParallelObject::n_processors(), libMesh::Elem::node_ptr(), libMesh::MeshBase::node_ref(), libMesh::MeshBase::nodes_begin(), libMesh::MeshBase::nodes_end(), libMesh::MeshBase::not_active_elements_begin(), libMesh::MeshBase::not_active_elements_end(), libMesh::ParallelObject::processor_id(), libMesh::DofObject::processor_id(), libMesh::Parallel::Communicator::send_receive(), libMesh::MeshBase::subactive_elements_begin(), libMesh::MeshBase::subactive_elements_end(), libMesh::MeshBase::unpartitioned_elements_begin(), and libMesh::MeshBase::unpartitioned_elements_end().
Referenced by libMesh::UnstructuredMesh::all_first_order(), partition(), libMesh::MeshBase::partition(), partition_range(), libMesh::XdrIO::read(), repartition(), and libMesh::BoundaryInfo::sync().
 {
   LOG_SCOPE("set_node_processor_ids()","Partitioner");
   // This function must be run on all processors at once
   libmesh_parallel_only(mesh.comm());
   // If we have any unpartitioned elements at this
   // stage there is a problem
   libmesh_assert (MeshTools::n_elem(mesh.unpartitioned_elements_begin(),
                                     mesh.unpartitioned_elements_end()) == 0);
   //   const dof_id_type orig_n_local_nodes = mesh.n_local_nodes();
   //   libMesh::err << "[" << mesh.processor_id() << "]: orig_n_local_nodes="
   //     << orig_n_local_nodes << std::endl;
   // Build up request sets.  Each node is currently owned by a processor because
   // it is connected to an element owned by that processor.  However, during the
   // repartitioning phase that element may have been assigned a new processor id, but
   // it is still resident on the original processor.  We need to know where to look
   // for new ids before assigning new ids, otherwise we may be asking the wrong processors
   // for the wrong information.
   //
   // The only remaining issue is what to do with unpartitioned nodes.  Since they are required
   // to live on all processors we can simply rely on ourselves to number them properly.
   std::vector<std::vector<dof_id_type> >
     requested_node_ids(mesh.n_processors());
   // Loop over all the nodes, count the ones on each processor.  We can skip ourself
   std::vector<dof_id_type> ghost_nodes_from_proc(mesh.n_processors(), 0);
   MeshBase::node_iterator       node_it  = mesh.nodes_begin();
   const MeshBase::node_iterator node_end = mesh.nodes_end();
   for (; node_it != node_end; ++node_it)
     {
       Node * node = *node_it;
       libmesh_assert(node);
       const processor_id_type current_pid = node->processor_id();
       if (current_pid != mesh.processor_id() &&
           current_pid != DofObject::invalid_processor_id)
         {
           libmesh_assert_less (current_pid, ghost_nodes_from_proc.size());
           ghost_nodes_from_proc[current_pid]++;
         }
     }
   // We know how many objects live on each processor, so reserve()
   // space for each.
   for (processor_id_type pid=0; pid != mesh.n_processors(); ++pid)
     requested_node_ids[pid].reserve(ghost_nodes_from_proc[pid]);
   // We need to get the new pid for each node from the processor
   // which *currently* owns the node.  We can safely skip ourself
   for (node_it = mesh.nodes_begin(); node_it != node_end; ++node_it)
     {
       Node * node = *node_it;
       libmesh_assert(node);
       const processor_id_type current_pid = node->processor_id();
       if (current_pid != mesh.processor_id() &&
           current_pid != DofObject::invalid_processor_id)
         {
           libmesh_assert_less (current_pid, requested_node_ids.size());
           libmesh_assert_less (requested_node_ids[current_pid].size(),
                                ghost_nodes_from_proc[current_pid]);
           requested_node_ids[current_pid].push_back(node->id());
         }
       // Unset any previously-set node processor ids
       node->invalidate_processor_id();
     }
   // Loop over all the active elements
   MeshBase::element_iterator       elem_it  = mesh.active_elements_begin();
   const MeshBase::element_iterator elem_end = mesh.active_elements_end();
   for ( ; elem_it != elem_end; ++elem_it)
     {
       Elem * elem = *elem_it;
       libmesh_assert(elem);
       libmesh_assert_not_equal_to (elem->processor_id(), DofObject::invalid_processor_id);
       // For each node, set the processor ID to the min of
       // its current value and this Element's processor id.
       //
       // TODO: we would probably get better parallel partitioning if
       // we did something like "min for even numbered nodes, max for
       // odd numbered".  We'd need to be careful about how that would
       // affect solution ordering for I/O, though.
       for (unsigned int n=0; n<elem->n_nodes(); ++n)
         elem->node_ptr(n)->processor_id() = std::min(elem->node_ptr(n)->processor_id(),
                                                      elem->processor_id());
     }
   // And loop over the subactive elements, but don't reassign
   // nodes that are already active on another processor.
   MeshBase::element_iterator       sub_it  = mesh.subactive_elements_begin();
   const MeshBase::element_iterator sub_end = mesh.subactive_elements_end();
   for ( ; sub_it != sub_end; ++sub_it)
     {
       Elem * elem = *sub_it;
       libmesh_assert(elem);
       libmesh_assert_not_equal_to (elem->processor_id(), DofObject::invalid_processor_id);
       for (unsigned int n=0; n<elem->n_nodes(); ++n)
         if (elem->node_ptr(n)->processor_id() == DofObject::invalid_processor_id)
           elem->node_ptr(n)->processor_id() = elem->processor_id();
     }
   // Same for the inactive elements -- we will have already gotten most of these
   // nodes, *except* for the case of a parent with a subset of children which are
   // ghost elements.  In that case some of the parent nodes will not have been
   // properly handled yet
   MeshBase::element_iterator       not_it  = mesh.not_active_elements_begin();
   const MeshBase::element_iterator not_end = mesh.not_active_elements_end();
   for ( ; not_it != not_end; ++not_it)
     {
       Elem * elem = *not_it;
       libmesh_assert(elem);
       libmesh_assert_not_equal_to (elem->processor_id(), DofObject::invalid_processor_id);
       for (unsigned int n=0; n<elem->n_nodes(); ++n)
         if (elem->node_ptr(n)->processor_id() == DofObject::invalid_processor_id)
           elem->node_ptr(n)->processor_id() = elem->processor_id();
     }
   // We can't assert that all nodes are connected to elements, because
   // a DistributedMesh with NodeConstraints might have pulled in some
   // remote nodes solely for evaluating those constraints.
   // MeshTools::libmesh_assert_connected_nodes(mesh);
   // For such nodes, we'll do a sanity check later when making sure
   // that we successfully reset their processor ids to something
   // valid.
   // Next set node ids from other processors, excluding self
   for (processor_id_type p=1; p != mesh.n_processors(); ++p)
     {
       // Trade my requests with processor procup and procdown
       processor_id_type procup = cast_int<processor_id_type>
         ((mesh.processor_id() + p) % mesh.n_processors());
       processor_id_type procdown = cast_int<processor_id_type>
         ((mesh.n_processors() + mesh.processor_id() - p) %
          mesh.n_processors());
       std::vector<dof_id_type> request_to_fill;
       mesh.comm().send_receive(procup, requested_node_ids[procup],
                                procdown, request_to_fill);
       // Fill those requests in-place
       for (std::size_t i=0; i != request_to_fill.size(); ++i)
         {
           Node & node = mesh.node_ref(request_to_fill[i]);
           const processor_id_type new_pid = node.processor_id();
           // We may have an invalid processor_id() on nodes that have been
           // "detached" from coarsened-away elements but that have not yet
           // themselves been removed.
           // libmesh_assert_not_equal_to (new_pid, DofObject::invalid_processor_id);
           // libmesh_assert_less (new_pid, mesh.n_partitions()); // this is the correct test --
           request_to_fill[i] = new_pid;           //  the number of partitions may
         }                                         //  not equal the number of processors
       // Trade back the results
       std::vector<dof_id_type> filled_request;
       mesh.comm().send_receive(procdown, request_to_fill,
                                procup,   filled_request);
       libmesh_assert_equal_to (filled_request.size(), requested_node_ids[procup].size());
       // And copy the id changes we've now been informed of
       for (std::size_t i=0; i != filled_request.size(); ++i)
         {
           Node & node = mesh.node_ref(requested_node_ids[procup][i]);
           // this is the correct test -- the number of partitions may
           // not equal the number of processors
           // But: we may have an invalid processor_id() on nodes that
           // have been "detached" from coarsened-away elements but
           // that have not yet themselves been removed.
           // libmesh_assert_less (filled_request[i], mesh.n_partitions());
           node.processor_id(cast_int<processor_id_type>(filled_request[i]));
         }
     }
 #ifdef DEBUG
   MeshTools::libmesh_assert_valid_procids<Node>(mesh);
 #endif
 }
void libMesh::Partitioner::set_parent_processor_ids (MeshBase & mesh) static
This function is called after partitioning to set the processor IDs for the inactive parent elements. A parent's processor ID is the same as its first child.
Definition at line 256 of file partitioner.C.
References libMesh::MeshBase::active_elements_begin(), libMesh::MeshBase::active_elements_end(), libMesh::Elem::active_family_tree(), libMesh::MeshBase::ancestor_elements_begin(), libMesh::MeshBase::ancestor_elements_end(), libMesh::Elem::child_ptr(), libMesh::ParallelObject::comm(), communication_blocksize, end, libMesh::DofObject::id(), libMesh::DofObject::invalid_processor_id, libMesh::DofObject::invalidate_processor_id(), libMesh::Elem::is_remote(), libMesh::MeshBase::is_serial(), libMesh::libmesh_assert(), libMesh::libmesh_ignore(), libMesh::MeshBase::max_elem_id(), std::min(), libMesh::Parallel::Communicator::min(), libMesh::Elem::n_children(), libMesh::MeshTools::n_elem(), libMesh::Elem::parent(), libMesh::processor_id(), libMesh::DofObject::processor_id(), libMesh::Elem::total_family_tree(), libMesh::MeshBase::unpartitioned_elements_begin(), and libMesh::MeshBase::unpartitioned_elements_end().
Referenced by partition(), partition_range(), and repartition().
 {
   // Ignore the parameter when !LIBMESH_ENABLE_AMR
   libmesh_ignore(mesh);
   LOG_SCOPE("set_parent_processor_ids()", "Partitioner");
 #ifdef LIBMESH_ENABLE_AMR
   // If the mesh is serial we have access to all the elements,
   // in particular all the active ones.  We can therefore set
   // the parent processor ids indirectly through their children, and
   // set the subactive processor ids while examining their active
   // ancestors.
   // By convention a parent is assigned to the minimum processor
   // of all its children, and a subactive is assigned to the processor
   // of its active ancestor.
   if (mesh.is_serial())
     {
       // Loop over all the active elements in the mesh
       MeshBase::element_iterator       it  = mesh.active_elements_begin();
       const MeshBase::element_iterator end = mesh.active_elements_end();
       for ( ; it!=end; ++it)
         {
           Elem * child  = *it;
           // First set descendents
           std::vector<const Elem *> subactive_family;
           child->total_family_tree(subactive_family);
           for (std::size_t i = 0; i != subactive_family.size(); ++i)
             const_cast<Elem *>(subactive_family[i])->processor_id() = child->processor_id();
           // Then set ancestors
           Elem * parent = child->parent();
           while (parent)
             {
               // invalidate the parent id, otherwise the min below
               // will not work if the current parent id is less
               // than all the children!
               parent->invalidate_processor_id();
               for (unsigned int c=0; c<parent->n_children(); c++)
                 {
                   child = parent->child_ptr(c);
                   libmesh_assert(child);
                   libmesh_assert(!child->is_remote());
                   libmesh_assert_not_equal_to (child->processor_id(), DofObject::invalid_processor_id);
                   parent->processor_id() = std::min(parent->processor_id(),
                                                     child->processor_id());
                 }
               parent = parent->parent();
             }
         }
     }
   // When the mesh is parallel we cannot guarantee that parents have access to
   // all their children.
   else
     {
       // Setting subactive processor ids is easy: we can guarantee
       // that children have access to all their parents.
       // Loop over all the active elements in the mesh
       MeshBase::element_iterator       it  = mesh.active_elements_begin();
       const MeshBase::element_iterator end = mesh.active_elements_end();
       for ( ; it!=end; ++it)
         {
           Elem * child  = *it;
           std::vector<const Elem *> subactive_family;
           child->total_family_tree(subactive_family);
           for (std::size_t i = 0; i != subactive_family.size(); ++i)
             const_cast<Elem *>(subactive_family[i])->processor_id() = child->processor_id();
         }
       // When the mesh is parallel we cannot guarantee that parents have access to
       // all their children.
       // We will use a brute-force approach here.  Each processor finds its parent
       // elements and sets the parent pid to the minimum of its
       // semilocal descendants.
       // A global reduction is then performed to make sure the true minimum is found.
       // As noted, this is required because we cannot guarantee that a parent has
       // access to all its children on any single processor.
       libmesh_parallel_only(mesh.comm());
       libmesh_assert(MeshTools::n_elem(mesh.unpartitioned_elements_begin(),
                                        mesh.unpartitioned_elements_end()) == 0);
       const dof_id_type max_elem_id = mesh.max_elem_id();
       std::vector<processor_id_type>
         parent_processor_ids (std::min(communication_blocksize,
                                        max_elem_id));
       for (dof_id_type blk=0, last_elem_id=0; last_elem_id<max_elem_id; blk++)
         {
           last_elem_id =
             std::min(static_cast<dof_id_type>((blk+1)*communication_blocksize),
                      max_elem_id);
           const dof_id_type first_elem_id = blk*communication_blocksize;
           std::fill (parent_processor_ids.begin(),
                      parent_processor_ids.end(),
                      DofObject::invalid_processor_id);
           // first build up local contributions to parent_processor_ids
           MeshBase::element_iterator       not_it  = mesh.ancestor_elements_begin();
           const MeshBase::element_iterator not_end = mesh.ancestor_elements_end();
           bool have_parent_in_block = false;
           for ( ; not_it != not_end; ++not_it)
             {
               Elem * parent = *not_it;
               const dof_id_type parent_idx = parent->id();
               libmesh_assert_less (parent_idx, max_elem_id);
               if ((parent_idx >= first_elem_id) &&
                   (parent_idx <  last_elem_id))
                 {
                   have_parent_in_block = true;
                   processor_id_type parent_pid = DofObject::invalid_processor_id;
                   std::vector<const Elem *> active_family;
                   parent->active_family_tree(active_family);
                   for (std::size_t i = 0; i != active_family.size(); ++i)
                     parent_pid = std::min (parent_pid, active_family[i]->processor_id());
                   const dof_id_type packed_idx = parent_idx - first_elem_id;
                   libmesh_assert_less (packed_idx, parent_processor_ids.size());
                   parent_processor_ids[packed_idx] = parent_pid;
                 }
             }
           // then find the global minimum
           mesh.comm().min (parent_processor_ids);
           // and assign the ids, if we have a parent in this block.
           if (have_parent_in_block)
             for (not_it = mesh.ancestor_elements_begin();
                  not_it != not_end; ++not_it)
               {
                 Elem * parent = *not_it;
                 const dof_id_type parent_idx = parent->id();
                 if ((parent_idx >= first_elem_id) &&
                     (parent_idx <  last_elem_id))
                   {
                     const dof_id_type packed_idx = parent_idx - first_elem_id;
                     libmesh_assert_less (packed_idx, parent_processor_ids.size());
                     const processor_id_type parent_pid =
                       parent_processor_ids[packed_idx];
                     libmesh_assert_not_equal_to (parent_pid, DofObject::invalid_processor_id);
                     parent->processor_id() = parent_pid;
                   }
               }
         }
     }
 #endif // LIBMESH_ENABLE_AMR
 }
void libMesh::Partitioner::single_partition (MeshBase & mesh) protected
Trivially "partitions" the mesh for one processor. Simply loops through the elements and assigns all of them to processor 0. Is is provided as a separate function so that derived classes may use it without reimplementing it.
Definition at line 151 of file partitioner.C.
References libMesh::MeshBase::elements_begin(), libMesh::MeshBase::elements_end(), and single_partition_range().
Referenced by libMesh::SubdomainPartitioner::_do_partition(), attach_weights(), partition(), and repartition().
 {
   this->single_partition_range(mesh.elements_begin(),
                                mesh.elements_end());
 }
void libMesh::Partitioner::single_partition_range (MeshBase::element_iterator it, MeshBase::element_iterator end) protected
Slightly generalized version of single_partition which acts on a range of elements defined by the pair of iterators (it, end).
Definition at line 159 of file partitioner.C.
References end, libMesh::Elem::n_nodes(), libMesh::Elem::node_ptr(), and libMesh::DofObject::processor_id().
Referenced by attach_weights(), libMesh::LinearPartitioner::partition_range(), libMesh::MappedSubdomainPartitioner::partition_range(), libMesh::CentroidPartitioner::partition_range(), and single_partition().
 {
   LOG_SCOPE("single_partition_range()", "Partitioner");
   for ( ; it != end; ++it)
     {
       Elem * elem = *it;
       elem->processor_id() = 0;
       // Assign all this element's nodes to processor 0 as well.
       for (unsigned int n=0; n<elem->n_nodes(); ++n)
         elem->node_ptr(n)->processor_id() = 0;
     }
 }
Member Data Documentation
ErrorVector* libMesh::Partitioner::_weights protected
The weights that might be used for partitioning.
Definition at line 216 of file partitioner.h.
Referenced by libMesh::MetisPartitioner::attach_weights().
const dof_id_type libMesh::Partitioner::communication_blocksize = 1000000 static protected
The blocksize to use when doing blocked parallel communication. This limits the maximum vector size which can be used in a single communication step.
Definition at line 211 of file partitioner.h.
Referenced by set_parent_processor_ids().
The documentation for this class was generated from the following files:
partitioner.h
partitioner.C