libMesh: libMesh::Parallel::Packing< Node * > Class Template Reference
SomeWebsiteLogo
libMesh::Parallel::Packing< Node * > Class Template Reference
#include <parallel_node.h>
Public Types
typedef largest_id_type buffer_type
Public Member Functions
template<>
Node * unpack (std::vector< largest_id_type >::const_iterator in, MeshBase *mesh)
template<>
Node * unpack (std::vector< largest_id_type >::const_iterator in, DistributedMesh *mesh)
template<>
Node * unpack (std::vector< largest_id_type >::const_iterator in, ParallelMesh *mesh)
Static Public Member Functions
template<typename OutputIter , typename Context >
static void pack (Node *const &object, OutputIter data_out, const Context *context)
template<typename Context >
static unsigned int packable_size (Node *const &object, const Context *context)
template<typename BufferIter >
static unsigned int packed_size (BufferIter iter)
template<typename BufferIter , typename Context >
static Node * unpack (BufferIter in, Context *ctx)
Detailed Description
template<>
class libMesh::Parallel::Packing< Node * >
Definition at line 58 of file parallel_node.h.
Member Typedef Documentation
typedef largest_id_type libMesh::Parallel::Packing< Node * >::buffer_type
Definition at line 61 of file parallel_node.h.
Member Function Documentation
template<typename OutputIter , typename Context > static void libMesh::Parallel::Packing< Node * >::pack (Node *const & object, OutputIter data_out, const Context * context) inline static
Definition at line 64 of file parallel_node.h.
References libMesh::Parallel::Packing< T >::pack().
   { return Packing<const Node *>::pack(object, data_out, context); }
template<typename Context > static unsigned int libMesh::Parallel::Packing< Node * >::packable_size (Node *const & object, const Context * context) inline static
Definition at line 70 of file parallel_node.h.
References libMesh::Parallel::Packing< T >::packable_size().
   { return Packing<const Node*>::packable_size(object, context); }
template<typename BufferIter > static unsigned int libMesh::Parallel::Packing< Node * >::packed_size (BufferIter iter) inline static
Definition at line 75 of file parallel_node.h.
References libMesh::Parallel::Packing< T >::packed_size().
   { return Packing<const Node *>::packed_size(iter); }
template<typename BufferIter , typename Context > static Node* libMesh::Parallel::Packing< Node * >::unpack (BufferIter in, Context * ctx) static
template<> Node* libMesh::Parallel::Packing< Node * >::unpack (std::vector< largest_id_type >::const_iterator in, MeshBase * mesh)
Definition at line 211 of file parallel_node.C.
References libMesh::BoundaryInfo::add_node(), libMesh::MeshBase::get_boundary_info(), libMesh::DofObject::invalid_processor_id, libMesh::libmesh_assert(), std::max(), libMesh::n_processors(), libMesh::processor_id(), libMesh::ParallelObject::processor_id(), libMesh::MeshBase::query_node_ptr(), libMesh::Real, libMesh::TOLERANCE, and libMesh::DofObject::unpackable_indexing_size().
 {
 #ifndef NDEBUG
   const std::vector<largest_id_type>::const_iterator original_in = in;
   const largest_id_type incoming_header = *in++;
   libmesh_assert_equal_to (incoming_header, node_magic_header);
 #endif
   const processor_id_type processor_id = cast_int<processor_id_type>(*in++);
   libmesh_assert(processor_id == DofObject::invalid_processor_id ||
                  processor_id < mesh->n_processors());
   const dof_id_type id = cast_int<dof_id_type>(*in++);
 #ifdef LIBMESH_ENABLE_UNIQUE_ID
   const unique_id_type unique_id = cast_int<unique_id_type>(*in++);
 #endif
   Node * node = mesh->query_node_ptr(id);
   if (node)
     {
       libmesh_assert_equal_to (node->processor_id(), processor_id);
       // We currently don't communicate mesh motion via packed Nodes,
       // so it should usually be safe to assume (and assert) that Node
       // locations are consistent between processors.
       //
       // There may be exceptions due to rounding in file I/O, so we'll
       // only assert equality to within a tight tolerance, and we'll
       // believe the sender's node locations over our own if we don't
       // own the node.
       for (unsigned int i=0; i != LIBMESH_DIM; ++i)
         {
           const Real & idtypes_as_Real = *(reinterpret_cast<const Real *>(&(*in)));
           libmesh_assert_less_equal ((*node)(i), idtypes_as_Real + (std::max(Real(1),idtypes_as_Real)*TOLERANCE*TOLERANCE));
           libmesh_assert_greater_equal ((*node)(i), idtypes_as_Real - (std::max(Real(1),idtypes_as_Real)*TOLERANCE*TOLERANCE));
           if (processor_id != mesh->processor_id())
             (*node)(i) = idtypes_as_Real;
           in += idtypes_per_Real;
         }
       if (!node->has_dofs())
         {
           node->unpack_indexing(in);
           libmesh_assert_equal_to (DofObject::unpackable_indexing_size(in),
                                    node->packed_indexing_size());
           in += node->packed_indexing_size();
         }
       else
         {
           // FIXME: We should add some debug mode tests to ensure that
           // the encoded indexing is consistent
           in += DofObject::unpackable_indexing_size(in);
         }
     }
   else
     {
       // If we don't already have it, we need to allocate it
       node = new Node();
       for (unsigned int i=0; i != LIBMESH_DIM; ++i)
         {
           const Real * idtypes_as_Real = reinterpret_cast<const Real *>(&(*in));
           (*node)(i) = *idtypes_as_Real;
           in += idtypes_per_Real;
         }
       node->set_id() = id;
 #ifdef LIBMESH_ENABLE_UNIQUE_ID
       node->set_unique_id() = unique_id;
 #endif
       node->processor_id() = processor_id;
       node->unpack_indexing(in);
       libmesh_assert_equal_to (DofObject::unpackable_indexing_size(in),
                                node->packed_indexing_size());
       in += node->packed_indexing_size();
     }
   // FIXME: We should add some debug mode tests to ensure that the
   // encoded boundary conditions are consistent
   // Add any nodal boundary condition ids
   const largest_id_type num_bcs = *in++;
   // libmesh_assert_greater_equal (num_bcs, 0);
   for(largest_id_type bc_it=0; bc_it < num_bcs; bc_it++)
     mesh->get_boundary_info().add_node
       (node, cast_int<boundary_id_type>(*in++));
 #ifndef NDEBUG
   libmesh_assert (in - original_in ==
                   cast_int<int>
                   (Parallel::Packing<const Node*>::packed_size(original_in)));
 #endif
   return node;
 }
template<> Node* libMesh::Parallel::Packing< Node * >::unpack (std::vector< largest_id_type >::const_iterator in, DistributedMesh * mesh)
Definition at line 318 of file parallel_node.C.
References libMesh::Parallel::Packing< T >::unpack().
 {
   return unpack(in, static_cast<MeshBase*>(mesh));
 }
template<> Node* libMesh::Parallel::Packing< Node * >::unpack (std::vector< largest_id_type >::const_iterator in, ParallelMesh * mesh)
Definition at line 329 of file parallel_node.C.
References libMesh::Parallel::Packing< T >::unpack().
 {
   return unpack(in, static_cast<MeshBase*>(mesh));
 }
The documentation for this class was generated from the following files:
parallel_node.h
parallel_node.C