libMesh: libMesh::InfFE< Dim, T_radial, T_map >::Base Class Reference
SomeWebsiteLogo
libMesh::InfFE< Dim, T_radial, T_map >::Base Class Reference
#include <inf_fe.h>
Static Public Member Functions
static Elem * build_elem (const Elem *inf_elem)
static ElemType get_elem_type (const ElemType type)
static unsigned int n_base_mapping_sf (const ElemType base_elem_type, const Order base_mapping_order)
Private Member Functions
Base ()
Detailed Description
template<unsigned int Dim, FEFamily T_radial, InfMapType T_map>
class libMesh::InfFE< Dim, T_radial, T_map >::Base
This nested class contains most of the static methods related to the base part of an infinite element. Only static members are provided, and these should only be accessible from within InfFE.
Author
Daniel Dreyer
Date
2003
Definition at line 185 of file inf_fe.h.
Constructor & Destructor Documentation
template<unsigned int Dim, FEFamily T_radial, InfMapType T_map> libMesh::InfFE< Dim, T_radial, T_map >::Base::Base () inline private
Never use an object of this type.
Definition at line 192 of file inf_fe.h.
References libMesh::InfFE< Dim, T_radial, T_map >::InfFE.
 {}
Member Function Documentation
template<unsigned int Dim, FEFamily T_radial, InfMapType T_base> Elem * libMesh::InfFE< Dim, T_radial, T_base >::Base::build_elem (const Elem * inf_elem) static
Build the base element of an infinite element. Be careful, this method allocates memory! So be sure to delete the new element afterward.
Definition at line 36 of file inf_fe_base_radial.C.
References libMesh::Elem::build_side_ptr().
Referenced by libMesh::InfFE< Dim, T_radial, T_map >::Radial::n_dofs_at_node(), and libMesh::InfFE< Dim, T_radial, T_map >::update_base_elem().
 {
   std::unique_ptr<const Elem> ape(inf_elem->build_side_ptr(0));
   // The incoming inf_elem is const, but this function is required to
   // return a non-const Elem * so that it can be used by
   // update_base_elem().  Therefore a const_cast seems to be
   // unavoidable here.
   return const_cast<Elem *>(ape.release());
 }
template<unsigned int Dim, FEFamily T_radial, InfMapType T_base> ElemType libMesh::InfFE< Dim, T_radial, T_base >::Base::get_elem_type (const ElemType type) static
Returns
The base element associated to type. This is, for example, TRI3 for INFPRISM6.
Definition at line 51 of file inf_fe_base_radial.C.
References libMesh::EDGE2, libMesh::EDGE3, libMesh::INFEDGE2, libMesh::INFHEX16, libMesh::INFHEX18, libMesh::INFHEX8, libMesh::INFPRISM12, libMesh::INFPRISM6, libMesh::INFQUAD4, libMesh::INFQUAD6, libMesh::INVALID_ELEM, libMesh::QUAD4, libMesh::QUAD8, libMesh::QUAD9, libMesh::TRI3, and libMesh::TRI6.
Referenced by libMesh::InfFE< Dim, T_radial, T_map >::combine_base_radial(), and libMesh::InfFE< Dim, T_radial, T_map >::Radial::n_dofs_at_node().
 {
   switch (type)
     {
       // 3D infinite elements:
       // with Dim=3 -> infinite elements on their own
     case INFHEX8:
       return QUAD4;
     case INFHEX16:
       return QUAD8;
     case INFHEX18:
       return QUAD9;
     case INFPRISM6:
       return TRI3;
     case INFPRISM12:
       return TRI6;
       // 2D infinite elements:
       // with Dim=3 -> used as boundary condition,
       // with Dim=2 -> infinite elements on their own
     case INFQUAD4:
       return EDGE2;
     case INFQUAD6:
       return EDGE3;
       // 1D infinite elements:
       // with Dim=2 -> used as boundary condition,
       // with Dim=1 -> infinite elements on their own,
       //               but no base element!
     case INFEDGE2:
       return INVALID_ELEM;
     default:
       libmesh_error_msg("ERROR: Unsupported element type!: " << type);
     }
 }
template<unsigned int Dim, FEFamily T_radial, InfMapType T_base> unsigned int libMesh::InfFE< Dim, T_radial, T_base >::Base::n_base_mapping_sf (const ElemType base_elem_type, const Order base_mapping_order) static
Returns
The number of shape functions used in the mapping in the base element of type base_elem_type mapped with order base_mapping_order
Definition at line 98 of file inf_fe_base_radial.C.
References libMesh::FE< Dim, T >::n_shape_functions().
Referenced by libMesh::InfFE< Dim, T_radial, T_map >::init_shape_functions(), and libMesh::InfFE< Dim, T_radial, T_map >::Radial::n_dofs_at_node().
 {
   if (Dim == 1)
     return 1;
   else if (Dim == 2)
     return FE<1,LAGRANGE>::n_shape_functions (base_elem_type,
                                               base_mapping_order);
   else if (Dim == 3)
     return FE<2,LAGRANGE>::n_shape_functions (base_elem_type,
                                               base_mapping_order);
   else
     {
       libmesh_error_msg("Unsupported Dim = " << Dim);
       return 0;
     }
 }
The documentation for this class was generated from the following files:
inf_fe.h
inf_fe_base_radial.C