libMesh: libMesh::GenericProjector< FFunctor, GFunctor, FValue, ProjectionAction > Class Template Reference
SomeWebsiteLogo
libMesh::GenericProjector< FFunctor, GFunctor, FValue, ProjectionAction > Class Template Reference
#include <generic_projector.h>
Public Member Functions
GenericProjector (const System &system_in, const FFunctor &f_in, const GFunctor *g_in, const ProjectionAction &act_in, const std::vector< unsigned int > &variables_in)
GenericProjector (const GenericProjector &in)
~GenericProjector ()
void operator() (const ConstElemRange &range) const
Private Attributes
const System & system
const FFunctor & master_f
const GFunctor * master_g
bool g_was_copied
const ProjectionAction & master_action
const std::vector< unsigned int > & variables
Detailed Description
template<typename FFunctor, typename GFunctor, typename FValue, typename ProjectionAction>
class libMesh::GenericProjector< FFunctor, GFunctor, FValue, ProjectionAction >
The GenericProjector class implements the core of other projection operations, using two input functors to read values to be projected and an output functor to set degrees of freedom in the result.
This may be executed in parallel on multiple threads.
Author
Roy H. Stogner
Date
2016
Definition at line 54 of file generic_projector.h.
Constructor & Destructor Documentation
template<typename FFunctor , typename GFunctor , typename FValue , typename ProjectionAction > libMesh::GenericProjector< FFunctor, GFunctor, FValue, ProjectionAction >::GenericProjector (const System & system_in, const FFunctor & f_in, const GFunctor * g_in, const ProjectionAction & act_in, const std::vector< unsigned int > & variables_in) inline
Definition at line 68 of file generic_projector.h.
                                                                   :
     system(system_in),
     master_f(f_in),
     master_g(g_in),
     g_was_copied(false),
     master_action(act_in),
     variables(variables_in)
   {}
template<typename FFunctor , typename GFunctor , typename FValue , typename ProjectionAction > libMesh::GenericProjector< FFunctor, GFunctor, FValue, ProjectionAction >::GenericProjector (const GenericProjector< FFunctor, GFunctor, FValue, ProjectionAction > & in) inline
Definition at line 81 of file generic_projector.h.
                                                  :
     system(in.system),
     master_f(in.master_f),
     master_g(in.master_g ? new GFunctor(*in.master_g) : libmesh_nullptr),
     g_was_copied(in.master_g),
     master_action(in.master_action),
     variables(in.variables)
   {}
template<typename FFunctor , typename GFunctor , typename FValue , typename ProjectionAction > libMesh::GenericProjector< FFunctor, GFunctor, FValue, ProjectionAction >::~GenericProjector () inline
Definition at line 90 of file generic_projector.h.
References libMesh::GenericProjector< FFunctor, GFunctor, FValue, ProjectionAction >::master_g, and libMesh::GenericProjector< FFunctor, GFunctor, FValue, ProjectionAction >::operator()().
   {
     if (g_was_copied)
       delete master_g;
   }
Member Function Documentation
template<typename FFunctor , typename GFunctor , typename FValue , typename ProjectionAction > void libMesh::GenericProjector< FFunctor, GFunctor, FValue, ProjectionAction >::operator() (const ConstElemRange & range) const
Function definitions
Definition at line 567 of file generic_projector.h.
References std::abs(), libMesh::Variable::active_on_subdomain(), libMesh::FEGenericBase< OutputType >::build(), libMesh::C_ONE, libMesh::C_ZERO, libMesh::Elem::child_ptr(), libMesh::Elem::child_ref_range(), libMesh::DenseMatrix< T >::cholesky_solve(), libMesh::CONSTANT, libMesh::FEType::default_quadrature_rule(), libMesh::Elem::dim(), libMesh::DISCONTINUOUS, libMesh::FEInterface::dofs_on_edge(), libMesh::FEInterface::dofs_on_side(), libMesh::FEMContext::edge, libMesh::FEMContext::edge_fe_reinit(), libMesh::Elem::edge_index_range(), libMesh::FEMContext::elem_dimensions(), libMesh::FEMContext::elem_fe_reinit(), libMesh::FEType::family, libMesh::FEAbstract::get_continuity(), libMesh::DiffContext::get_dof_indices(), libMesh::System::get_dof_map(), libMesh::FEGenericBase< OutputType >::get_dphi(), libMesh::FEMContext::get_edge_fe(), libMesh::FEMContext::get_element_fe(), libMesh::FEAbstract::get_fe_type(), libMesh::FEAbstract::get_JxW(), libMesh::FEGenericBase< OutputType >::get_phi(), libMesh::FEMContext::get_side_fe(), libMesh::DenseVector< T >::get_values(), libMesh::FEAbstract::get_xyz(), libMesh::HERMITE, libMesh::Elem::hmin(), libMesh::Elem::infinite(), libMesh::FEInterface::inverse_map(), libMesh::Elem::is_child_on_edge(), libMesh::Elem::is_child_on_side(), libMesh::Elem::is_vertex(), libMesh::Elem::is_vertex_on_parent(), libMesh::Elem::JUST_COARSENED, libMesh::Elem::JUST_REFINED, libMesh::LAGRANGE, libmesh_nullptr, libMesh::GenericProjector< FFunctor, GFunctor, FValue, ProjectionAction >::master_action, libMesh::GenericProjector< FFunctor, GFunctor, FValue, ProjectionAction >::master_f, libMesh::GenericProjector< FFunctor, GFunctor, FValue, ProjectionAction >::master_g, libMesh::MONOMIAL, libMesh::Elem::n_children(), libMesh::FEInterface::n_dofs_at_node(), n_nodes, libMesh::Elem::n_nodes(), libMesh::Elem::node_ref(), libMesh::DofObject::old_dof_object, libMesh::FEType::order, libMesh::Elem::p_level(), libMesh::Elem::p_refinement_flag(), libMesh::Elem::parent(), libMesh::Elem::point(), libMesh::FEMContext::pre_fe_reinit(), libMesh::Real, libMesh::Elem::refinement_flag(), libMesh::DenseVector< T >::resize(), libMesh::DenseMatrix< T >::resize(), libMesh::SCALAR, libMesh::FEMContext::side, libMesh::FEMContext::side_fe_reinit(), libMesh::Elem::side_index_range(), libMesh::Elem::subdomain_id(), libMesh::GenericProjector< FFunctor, GFunctor, FValue, ProjectionAction >::system, libMesh::System::time, libMesh::TOLERANCE, libMesh::Variable::type(), libMesh::Elem::type(), libMesh::DofMap::variable(), libMesh::System::variable_scalar_number(), libMesh::GenericProjector< FFunctor, GFunctor, FValue, ProjectionAction >::variables, libMesh::Elem::which_child_am_i(), libMesh::DenseMatrix< T >::zero(), and libMesh::DenseVector< T >::zero().
Referenced by libMesh::GenericProjector< FFunctor, GFunctor, FValue, ProjectionAction >::~GenericProjector().
 {
   LOG_SCOPE ("operator()", "GenericProjector");
   ProjectionAction action(master_action);
   FFunctor f(master_f);
   std::unique_ptr<GFunctor> g;
   if (master_g)
     g.reset(new GFunctor(*master_g));
   // The DofMap for this system
   const DofMap & dof_map = system.get_dof_map();
   // The element matrix and RHS for projections.
   // Note that Ke is always real-valued, whereas
   // Fe may be complex valued if complex number
   // support is enabled
   DenseMatrix<Real> Ke;
   DenseVector<FValue> Fe;
   // The new element degree of freedom coefficients
   DenseVector<FValue> Ue;
   // Context objects to contain all our required FE objects
   FEMContext context( system );
   // Loop over all the variables we've been requested to project, to
   // pre-request
   for (std::size_t v=0; v!=variables.size(); v++)
     {
       const unsigned int var = variables[v];
       // FIXME: Need to generalize this to vector-valued elements. [PB]
       FEBase * fe = libmesh_nullptr;
       FEBase * side_fe = libmesh_nullptr;
       FEBase * edge_fe = libmesh_nullptr;
       const std::set<unsigned char> & elem_dims =
         context.elem_dimensions();
       for (std::set<unsigned char>::const_iterator dim_it =
              elem_dims.begin(); dim_it != elem_dims.end(); ++dim_it)
         {
           const unsigned char dim = *dim_it;
           context.get_element_fe( var, fe, dim );
           if (fe->get_fe_type().family == SCALAR)
             continue;
           if (dim > 1)
             context.get_side_fe( var, side_fe, dim );
           if (dim > 2)
             context.get_edge_fe( var, edge_fe );
           fe->get_xyz();
           fe->get_phi();
           if (dim > 1)
             side_fe->get_phi();
           if (dim > 2)
             edge_fe->get_phi();
           const FEContinuity cont = fe->get_continuity();
           if (cont == C_ONE)
             {
               // Our C1 elements need gradient information
               libmesh_assert(g);
               fe->get_dphi();
               if (dim > 1)
                 side_fe->get_dphi();
               if (dim > 2)
                 edge_fe->get_dphi();
             }
         }
     }
   // Now initialize any user requested shape functions, xyz vals, etc
   f.init_context(context);
   if (g.get())
     g->init_context(context);
   // this->init_context(context);
   // Iterate over all the elements in the range
   for (ConstElemRange::const_iterator elem_it=range.begin(); elem_it != range.end();
        ++elem_it)
     {
       const Elem * elem = *elem_it;
       unsigned int dim = elem->dim();
       context.pre_fe_reinit(system, elem);
       // If we're doing AMR, this might be a grid projection with a cheap
       // early exit.
 #ifdef LIBMESH_ENABLE_AMR
       // If this element doesn't have an old_dof_object, but it
       // wasn't just refined or just coarsened into activity, then
       // it must be newly added, so the user is responsible for
       // setting the new dofs on it during a grid projection.
       if (!elem->old_dof_object &&
           elem->refinement_flag() != Elem::JUST_REFINED &&
           elem->refinement_flag() != Elem::JUST_COARSENED &&
           f.is_grid_projection())
         continue;
 #endif // LIBMESH_ENABLE_AMR
       // Loop over all the variables we've been requested to project, to
       // do the projection
       for (std::size_t v=0; v!=variables.size(); v++)
         {
           const unsigned int var = variables[v];
           const Variable & variable = dof_map.variable(var);
           const FEType & base_fe_type = variable.type();
           FEType fe_type = base_fe_type;
           // This may be a p refined element
           fe_type.order =
             libMesh::Order (fe_type.order + elem->p_level());
           if (fe_type.family == SCALAR)
             continue;
           // Per-subdomain variables don't need to be projected on
           // elements where they're not active
           if (!variable.active_on_subdomain(elem->subdomain_id()))
             continue;
           const std::vector<dof_id_type> & dof_indices =
             context.get_dof_indices(var);
           // The number of DOFs on the element
           const unsigned int n_dofs =
             cast_int<unsigned int>(dof_indices.size());
           const unsigned int var_component =
             system.variable_scalar_number(var, 0);
           // Zero the interpolated values
           Ue.resize (n_dofs); Ue.zero();
           // If we're projecting from an old grid
 #ifdef LIBMESH_ENABLE_AMR
           if (f.is_grid_projection() &&
               // And either this is an unchanged element
               ((elem->refinement_flag() != Elem::JUST_REFINED &&
                 elem->refinement_flag() != Elem::JUST_COARSENED &&
                 elem->p_refinement_flag() != Elem::JUST_REFINED &&
                 elem->p_refinement_flag() != Elem::JUST_COARSENED) ||
                // Or this is a low order monomial element which has merely
                // been h refined
                (fe_type.family == MONOMIAL &&
                 fe_type.order == CONSTANT &&
                 elem->p_level() == 0 &&
                 elem->refinement_flag() != Elem::JUST_COARSENED &&
                 elem->p_refinement_flag() != Elem::JUST_COARSENED))
               )
             // then we can simply copy its old dof
             // values to new indices.
             {
               LOG_SCOPE ("copy_dofs", "GenericProjector");
               f.eval_old_dofs(context, var_component, Ue.get_values());
               action.insert(context, var, Ue);
               continue;
             }
 #endif // LIBMESH_ENABLE_AMR
           FEBase * fe = libmesh_nullptr;
           FEBase * side_fe = libmesh_nullptr;
           FEBase * edge_fe = libmesh_nullptr;
           context.get_element_fe( var, fe, dim );
           if (fe->get_fe_type().family == SCALAR)
             continue;
           if (dim > 1)
             context.get_side_fe( var, side_fe, dim );
           if (dim > 2)
             context.get_edge_fe( var, edge_fe );
           const FEContinuity cont = fe->get_continuity();
           std::vector<unsigned int> side_dofs;
           // Fixed vs. free DoFs on edge/face projections
           std::vector<char> dof_is_fixed(n_dofs, false); // bools
           std::vector<int> free_dof(n_dofs, 0);
           // The element type
           const ElemType elem_type = elem->type();
           // The number of nodes on the new element
           const unsigned int n_nodes = elem->n_nodes();
           START_LOG ("project_nodes","GenericProjector");
           // When interpolating C1 elements we need to know which
           // vertices were also parent vertices; we'll cache an
           // intermediate fact outside the nodes loop.
           int i_am_child = -1;
 #ifdef LIBMESH_ENABLE_AMR
           if (elem->parent())
             i_am_child = elem->parent()->which_child_am_i(elem);
 #endif
           // In general, we need a series of
           // projections to ensure a unique and continuous
           // solution.  We start by interpolating nodes, then
           // hold those fixed and project edges, then
           // hold those fixed and project faces, then
           // hold those fixed and project interiors
           //
           // In the LAGRANGE case, we will save a lot of solution
           // evaluations (at a slight cost in accuracy) by simply
           // interpolating all nodes rather than projecting.
           // Interpolate vertex (or for LAGRANGE, all node) values first.
           unsigned int current_dof = 0;
           for (unsigned int n=0; n!= n_nodes; ++n)
             {
               // FIXME: this should go through the DofMap,
               // not duplicate dof_indices code badly!
               const unsigned int nc =
                 FEInterface::n_dofs_at_node (dim, fe_type, elem_type, n);
               if (!elem->is_vertex(n) &&
                   fe_type.family != LAGRANGE)
                 {
                   current_dof += nc;
                   continue;
                 }
               if (cont == DISCONTINUOUS)
                 {
                   libmesh_assert_equal_to (nc, 0);
                 }
               else if (!nc)
                 {
                   // This should only occur for first-order LAGRANGE
                   // FE on non-vertices of higher-order elements
                   libmesh_assert (!elem->is_vertex(n));
                   libmesh_assert_equal_to(fe_type.family, LAGRANGE);
                 }
               // Assume that C_ZERO elements have a single nodal
               // value shape function at vertices
               else if (cont == C_ZERO)
                 {
                   Ue(current_dof) = f.eval_at_node(context,
                                                    var_component,
                                                    dim,
                                                    elem->node_ref(n),
                                                    system.time);
                   dof_is_fixed[current_dof] = true;
                   current_dof++;
                 }
               else if (cont == C_ONE)
                 {
                   const bool is_parent_vertex = (i_am_child == -1) ||
                     elem->parent()->is_vertex_on_parent(i_am_child, n);
                   // The hermite element vertex shape functions are weird
                   if (fe_type.family == HERMITE)
                     {
                       Ue(current_dof) =
                         f.eval_at_node(context,
                                        var_component,
                                        dim,
                                        elem->node_ref(n),
                                        system.time);
                       dof_is_fixed[current_dof] = true;
                       current_dof++;
                       VectorValue<FValue> grad =
                         is_parent_vertex ?
                         g->eval_at_node(context,
                                         var_component,
                                         dim,
                                         elem->node_ref(n),
                                         system.time) :
                         g->eval_at_point(context,
                                          var_component,
                                          elem->node_ref(n),
                                          system.time);
                       // x derivative
                       Ue(current_dof) = grad(0);
                       dof_is_fixed[current_dof] = true;
                       current_dof++;
                       if (dim > 1)
{
                           // We'll finite difference mixed derivatives
                           Real delta_x = TOLERANCE * elem->hmin();
                           Point nxminus = elem->point(n),
                             nxplus = elem->point(n);
                           nxminus(0) -= delta_x;
                           nxplus(0) += delta_x;
                           VectorValue<FValue> gxminus =
                             g->eval_at_point(context,
                                              var_component,
                                              nxminus,
                                              system.time);
                           VectorValue<FValue> gxplus =
                             g->eval_at_point(context,
                                              var_component,
                                              nxplus,
                                              system.time);
                           // y derivative
                           Ue(current_dof) = grad(1);
                           dof_is_fixed[current_dof] = true;
                           current_dof++;
                           // xy derivative
                           Ue(current_dof) = (gxplus(1) - gxminus(1))
                             / 2. / delta_x;
                           dof_is_fixed[current_dof] = true;
                           current_dof++;
                           if (dim > 2)
{
                               // z derivative
                               Ue(current_dof) = grad(2);
                               dof_is_fixed[current_dof] = true;
                               current_dof++;
                               // xz derivative
                               Ue(current_dof) = (gxplus(2) - gxminus(2))
                                 / 2. / delta_x;
                               dof_is_fixed[current_dof] = true;
                               current_dof++;
                               // We need new points for yz
                               Point nyminus = elem->point(n),
                                 nyplus = elem->point(n);
                               nyminus(1) -= delta_x;
                               nyplus(1) += delta_x;
                               VectorValue<FValue> gyminus =
                                 g->eval_at_point(context,
                                                  var_component,
                                                  nyminus,
                                                  system.time);
                               VectorValue<FValue> gyplus =
                                 g->eval_at_point(context,
                                                  var_component,
                                                  nyplus,
                                                  system.time);
                               // xz derivative
                               Ue(current_dof) = (gyplus(2) - gyminus(2))
                                 / 2. / delta_x;
                               dof_is_fixed[current_dof] = true;
                               current_dof++;
                               // Getting a 2nd order xyz is more tedious
                               Point nxmym = elem->point(n),
                                 nxmyp = elem->point(n),
                                 nxpym = elem->point(n),
                                 nxpyp = elem->point(n);
                               nxmym(0) -= delta_x;
                               nxmym(1) -= delta_x;
                               nxmyp(0) -= delta_x;
                               nxmyp(1) += delta_x;
                               nxpym(0) += delta_x;
                               nxpym(1) -= delta_x;
                               nxpyp(0) += delta_x;
                               nxpyp(1) += delta_x;
                               VectorValue<FValue> gxmym =
                                 g->eval_at_point(context,
                                                  var_component,
                                                  nxmym,
                                                  system.time);
                               VectorValue<FValue> gxmyp =
                                 g->eval_at_point(context,
                                                  var_component,
                                                  nxmyp,
                                                  system.time);
                               VectorValue<FValue> gxpym =
                                 g->eval_at_point(context,
                                                  var_component,
                                                  nxpym,
                                                  system.time);
                               VectorValue<FValue> gxpyp =
                                 g->eval_at_point(context,
                                                  var_component,
                                                  nxpyp,
                                                  system.time);
                               FValue gxzplus = (gxpyp(2) - gxmyp(2))
                                 / 2. / delta_x;
                               FValue gxzminus = (gxpym(2) - gxmym(2))
                                 / 2. / delta_x;
                               // xyz derivative
                               Ue(current_dof) = (gxzplus - gxzminus)
                                 / 2. / delta_x;
                               dof_is_fixed[current_dof] = true;
                               current_dof++;
                             }
                         }
                     }
                   else
                     {
                       // Assume that other C_ONE elements have a single nodal
                       // value shape function and nodal gradient component
                       // shape functions
                       libmesh_assert_equal_to (nc, 1 + dim);
                       Ue(current_dof) = f.eval_at_node(context,
                                                        var_component,
                                                        dim,
                                                        elem->node_ref(n),
                                                        system.time);
                       dof_is_fixed[current_dof] = true;
                       current_dof++;
                       VectorValue<FValue> grad =
                         is_parent_vertex ?
                         g->eval_at_node(context,
                                         var_component,
                                         dim,
                                         elem->node_ref(n),
                                         system.time) :
                         g->eval_at_point(context,
                                          var_component,
                                          elem->node_ref(n),
                                          system.time);
                       for (unsigned int i=0; i!= dim; ++i)
{
                           Ue(current_dof) = grad(i);
                           dof_is_fixed[current_dof] = true;
                           current_dof++;
                         }
                     }
                 }
               else
                 libmesh_error_msg("Unknown continuity " << cont);
             }
           STOP_LOG ("project_nodes","GenericProjector");
           START_LOG ("project_edges","GenericProjector");
           // In 3D with non-LAGRANGE, project any edge values next
           if (dim > 2 &&
               cont != DISCONTINUOUS &&
               (fe_type.family != LAGRANGE
 #ifdef LIBMESH_ENABLE_INFINITE_ELEMENTS
                || elem->infinite()
 #endif
                ))
             {
               // If we're JUST_COARSENED we'll need a custom
               // evaluation, not just the standard edge FE
               const std::vector<Point> & xyz_values =
 #ifdef LIBMESH_ENABLE_AMR
                 (elem->refinement_flag() == Elem::JUST_COARSENED) ?
                 fe->get_xyz() :
 #endif
                 edge_fe->get_xyz();
               const std::vector<Real> & JxW =
 #ifdef LIBMESH_ENABLE_AMR
                 (elem->refinement_flag() == Elem::JUST_COARSENED) ?
                 fe->get_JxW() :
 #endif
                 edge_fe->get_JxW();
               const std::vector<std::vector<Real>> & phi =
 #ifdef LIBMESH_ENABLE_AMR
                 (elem->refinement_flag() == Elem::JUST_COARSENED) ?
                 fe->get_phi() :
 #endif
                 edge_fe->get_phi();
               const std::vector<std::vector<RealGradient>> * dphi = libmesh_nullptr;
               if (cont == C_ONE)
                 dphi =
 #ifdef LIBMESH_ENABLE_AMR
                   (elem->refinement_flag() == Elem::JUST_COARSENED) ?
                   &(fe->get_dphi()) :
 #endif
                   &(edge_fe->get_dphi());
               for (auto e : elem->edge_index_range())
                 {
                   context.edge = e;
 #ifdef LIBMESH_ENABLE_AMR
                   if (elem->refinement_flag() == Elem::JUST_COARSENED)
                     {
                       std::vector<Point> fine_points;
                       std::unique_ptr<FEBase> fine_fe
                         (FEBase::build (dim, base_fe_type));
                       std::unique_ptr<QBase> qrule
                         (base_fe_type.default_quadrature_rule(1));
                       fine_fe->attach_quadrature_rule(qrule.get());
                       const std::vector<Point> & child_xyz =
                         fine_fe->get_xyz();
                       for (unsigned int c = 0, nc = elem->n_children();
                            c != nc; ++c)
{
                           if (!elem->is_child_on_edge(c, e))
                             continue;
                           fine_fe->edge_reinit(elem->child_ptr(c), e);
                           fine_points.insert(fine_points.end(),
                                              child_xyz.begin(),
                                              child_xyz.end());
                         }
                       std::vector<Point> fine_qp;
                       FEInterface::inverse_map (dim, base_fe_type, elem,
                                                 fine_points, fine_qp);
                       context.elem_fe_reinit(&fine_qp);
                     }
                   else
 #endif // LIBMESH_ENABLE_AMR
                     context.edge_fe_reinit();
                   const unsigned int n_qp = xyz_values.size();
                   FEInterface::dofs_on_edge(elem, dim, base_fe_type,
                                             e, side_dofs);
                   // Some edge dofs are on nodes and already
                   // fixed, others are free to calculate
                   unsigned int free_dofs = 0;
                   for (std::size_t i=0; i != side_dofs.size(); ++i)
                     if (!dof_is_fixed[side_dofs[i]])
                       free_dof[free_dofs++] = i;
                   // There may be nothing to project
                   if (!free_dofs)
                     continue;
                   Ke.resize (free_dofs, free_dofs); Ke.zero();
                   Fe.resize (free_dofs); Fe.zero();
                   // The new edge coefficients
                   DenseVector<FValue> Uedge(free_dofs);
                   // Loop over the quadrature points
                   for (unsigned int qp=0; qp<n_qp; qp++)
                     {
                       // solution at the quadrature point
                       FValue fineval = f.eval_at_point(context,
                                                        var_component,
                                                        xyz_values[qp],
                                                        system.time);
                       // solution grad at the quadrature point
                       VectorValue<FValue> finegrad;
                       if (cont == C_ONE)
                         finegrad = g->eval_at_point(context,
                                                     var_component,
                                                     xyz_values[qp],
                                                     system.time);
                       // Form edge projection matrix
                       for (std::size_t sidei=0, freei=0;
                            sidei != side_dofs.size(); ++sidei)
{
                           unsigned int i = side_dofs[sidei];
                           // fixed DoFs aren't test functions
                           if (dof_is_fixed[i])
                             continue;
                           for (std::size_t sidej=0, freej=0;
                                sidej != side_dofs.size(); ++sidej)
{
                               unsigned int j = side_dofs[sidej];
                               if (dof_is_fixed[j])
                                 Fe(freei) -= phi[i][qp] * phi[j][qp] *
                                   JxW[qp] * Ue(j);
                               else
                                 Ke(freei,freej) += phi[i][qp] *
                                   phi[j][qp] * JxW[qp];
                               if (cont == C_ONE)
{
                                   if (dof_is_fixed[j])
                                     Fe(freei) -= ( (*dphi)[i][qp] *
                                                    (*dphi)[j][qp] ) *
                                       JxW[qp] * Ue(j);
                                   else
                                     Ke(freei,freej) += ( (*dphi)[i][qp] *
                                                          (*dphi)[j][qp] )
                                       * JxW[qp];
                                 }
                               if (!dof_is_fixed[j])
                                 freej++;
                             }
                           Fe(freei) += phi[i][qp] * fineval * JxW[qp];
                           if (cont == C_ONE)
                             Fe(freei) += (finegrad * (*dphi)[i][qp] ) *
                               JxW[qp];
                           freei++;
                         }
                     }
                   Ke.cholesky_solve(Fe, Uedge);
                   // Transfer new edge solutions to element
                   for (unsigned int i=0; i != free_dofs; ++i)
                     {
                       FValue & ui = Ue(side_dofs[free_dof[i]]);
                       libmesh_assert(bool(std::abs(ui) < TOLERANCE) ||
                                      bool(std::abs(ui - Uedge(i)) < TOLERANCE));
                       ui = Uedge(i);
                       dof_is_fixed[side_dofs[free_dof[i]]] = true;
                     }
                 }
             } // end if (dim > 2, !DISCONTINUOUS, !LAGRANGE)
           STOP_LOG ("project_edges","GenericProjector");
           START_LOG ("project_sides","GenericProjector");
           // With non-LAGRANGE, project any side values (edges in 2D,
           // faces in 3D) next.
           if (dim > 1 &&
               cont != DISCONTINUOUS &&
               (fe_type.family != LAGRANGE
 #ifdef LIBMESH_ENABLE_INFINITE_ELEMENTS
                || elem->infinite()
 #endif
                ))
             {
               // If we're JUST_COARSENED we'll need a custom
               // evaluation, not just the standard side FE
               const std::vector<Point> & xyz_values =
 #ifdef LIBMESH_ENABLE_AMR
                 (elem->refinement_flag() == Elem::JUST_COARSENED) ?
                 fe->get_xyz() :
 #endif // LIBMESH_ENABLE_AMR
                 side_fe->get_xyz();
               const std::vector<Real> & JxW =
 #ifdef LIBMESH_ENABLE_AMR
                 (elem->refinement_flag() == Elem::JUST_COARSENED) ?
                 fe->get_JxW() :
 #endif // LIBMESH_ENABLE_AMR
                 side_fe->get_JxW();
               const std::vector<std::vector<Real>> & phi =
 #ifdef LIBMESH_ENABLE_AMR
                 (elem->refinement_flag() == Elem::JUST_COARSENED) ?
                 fe->get_phi() :
 #endif // LIBMESH_ENABLE_AMR
                 side_fe->get_phi();
               const std::vector<std::vector<RealGradient>> * dphi = libmesh_nullptr;
               if (cont == C_ONE)
                 dphi =
 #ifdef LIBMESH_ENABLE_AMR
                   (elem->refinement_flag() == Elem::JUST_COARSENED) ? &(fe->get_dphi()) :
 #endif // LIBMESH_ENABLE_AMR
                   &(side_fe->get_dphi());
               for (auto s : elem->side_index_range())
                 {
                   FEInterface::dofs_on_side(elem, dim, base_fe_type,
                                             s, side_dofs);
                   // Some side dofs are on nodes/edges and already
                   // fixed, others are free to calculate
                   unsigned int free_dofs = 0;
                   for (std::size_t i=0; i != side_dofs.size(); ++i)
                     if (!dof_is_fixed[side_dofs[i]])
                       free_dof[free_dofs++] = i;
                   // There may be nothing to project
                   if (!free_dofs)
                     continue;
                   Ke.resize (free_dofs, free_dofs); Ke.zero();
                   Fe.resize (free_dofs); Fe.zero();
                   // The new side coefficients
                   DenseVector<FValue> Uside(free_dofs);
                   context.side = s;
 #ifdef LIBMESH_ENABLE_AMR
                   if (elem->refinement_flag() == Elem::JUST_COARSENED)
                     {
                       std::vector<Point> fine_points;
                       std::unique_ptr<FEBase> fine_fe
                         (FEBase::build (dim, base_fe_type));
                       std::unique_ptr<QBase> qrule
                         (base_fe_type.default_quadrature_rule(dim-1));
                       fine_fe->attach_quadrature_rule(qrule.get());
                       const std::vector<Point> & child_xyz =
                         fine_fe->get_xyz();
                       for (unsigned int c = 0, nc = elem->n_children();
                            c != nc; ++c)
{
                           if (!elem->is_child_on_side(c, s))
                             continue;
                           fine_fe->reinit(elem->child_ptr(c), s);
                           fine_points.insert(fine_points.end(),
                                              child_xyz.begin(),
                                              child_xyz.end());
                         }
                       std::vector<Point> fine_qp;
                       FEInterface::inverse_map (dim, base_fe_type, elem,
                                                 fine_points, fine_qp);
                       context.elem_fe_reinit(&fine_qp);
                     }
                   else
 #endif // LIBMESH_ENABLE_AMR
                     context.side_fe_reinit();
                   const unsigned int n_qp = xyz_values.size();
                   // Loop over the quadrature points
                   for (unsigned int qp=0; qp<n_qp; qp++)
                     {
                       // solution at the quadrature point
                       FValue fineval = f.eval_at_point(context,
                                                        var_component,
                                                        xyz_values[qp],
                                                        system.time);
                       // solution grad at the quadrature point
                       VectorValue<FValue> finegrad;
                       if (cont == C_ONE)
                         finegrad = g->eval_at_point(context,
                                                     var_component,
                                                     xyz_values[qp],
                                                     system.time);
                       // Form side projection matrix
                       for (std::size_t sidei=0, freei=0;
                            sidei != side_dofs.size(); ++sidei)
{
                           unsigned int i = side_dofs[sidei];
                           // fixed DoFs aren't test functions
                           if (dof_is_fixed[i])
                             continue;
                           for (std::size_t sidej=0, freej=0;
                                sidej != side_dofs.size(); ++sidej)
{
                               unsigned int j = side_dofs[sidej];
                               if (dof_is_fixed[j])
                                 Fe(freei) -= phi[i][qp] * phi[j][qp] *
                                   JxW[qp] * Ue(j);
                               else
                                 Ke(freei,freej) += phi[i][qp] *
                                   phi[j][qp] * JxW[qp];
                               if (cont == C_ONE)
{
                                   if (dof_is_fixed[j])
                                     Fe(freei) -= ( (*dphi)[i][qp] *
                                                    (*dphi)[j][qp] ) *
                                       JxW[qp] * Ue(j);
                                   else
                                     Ke(freei,freej) += ( (*dphi)[i][qp] *
                                                          (*dphi)[j][qp] )
                                       * JxW[qp];
                                 }
                               if (!dof_is_fixed[j])
                                 freej++;
                             }
                           Fe(freei) += (fineval * phi[i][qp]) * JxW[qp];
                           if (cont == C_ONE)
                             Fe(freei) += (finegrad * (*dphi)[i][qp] ) *
                               JxW[qp];
                           freei++;
                         }
                     }
                   Ke.cholesky_solve(Fe, Uside);
                   // Transfer new side solutions to element
                   for (unsigned int i=0; i != free_dofs; ++i)
                     {
                       FValue & ui = Ue(side_dofs[free_dof[i]]);
                       libmesh_assert(bool(std::abs(ui) < TOLERANCE) ||
                                      bool(std::abs(ui - Uside(i)) < TOLERANCE));
                       ui = Uside(i);
                       dof_is_fixed[side_dofs[free_dof[i]]] = true;
                     }
                 }
             } // end if (dim > 1, !DISCONTINUOUS, !LAGRANGE)
           STOP_LOG ("project_sides","GenericProjector");
           START_LOG ("project_interior","GenericProjector");
           // Project the interior values, finally
           // Some interior dofs are on nodes/edges/sides and
           // already fixed, others are free to calculate
           unsigned int free_dofs = 0;
           for (unsigned int i=0; i != n_dofs; ++i)
             if (!dof_is_fixed[i])
               free_dof[free_dofs++] = i;
           // Project any remaining (interior) dofs in the non-LAGRANGE
           // case.
           if (free_dofs &&
               (fe_type.family != LAGRANGE
 #ifdef LIBMESH_ENABLE_INFINITE_ELEMENTS
                || elem->infinite()
 #endif
                ))
             {
               const std::vector<Point> & xyz_values = fe->get_xyz();
               const std::vector<Real> & JxW = fe->get_JxW();
               const std::vector<std::vector<Real>> & phi = fe->get_phi();
               const std::vector<std::vector<RealGradient>> * dphi = libmesh_nullptr;
               if (cont == C_ONE)
                 dphi = &(fe->get_dphi());
 #ifdef LIBMESH_ENABLE_AMR
               if (elem->refinement_flag() == Elem::JUST_COARSENED)
                 {
                   std::vector<Point> fine_points;
                   std::unique_ptr<FEBase> fine_fe
                     (FEBase::build (dim, base_fe_type));
                   std::unique_ptr<QBase> qrule
                     (base_fe_type.default_quadrature_rule(dim));
                   fine_fe->attach_quadrature_rule(qrule.get());
                   const std::vector<Point> & child_xyz =
                     fine_fe->get_xyz();
                   for (auto & child : elem->child_ref_range())
                     {
                       fine_fe->reinit(&child);
                       fine_points.insert(fine_points.end(),
                                          child_xyz.begin(),
                                          child_xyz.end());
                     }
                   std::vector<Point> fine_qp;
                   FEInterface::inverse_map (dim, base_fe_type, elem,
                                             fine_points, fine_qp);
                   context.elem_fe_reinit(&fine_qp);
                 }
               else
 #endif // LIBMESH_ENABLE_AMR
                 context.elem_fe_reinit();
               const unsigned int n_qp = xyz_values.size();
               Ke.resize (free_dofs, free_dofs); Ke.zero();
               Fe.resize (free_dofs); Fe.zero();
               // The new interior coefficients
               DenseVector<FValue> Uint(free_dofs);
               // Loop over the quadrature points
               for (unsigned int qp=0; qp<n_qp; qp++)
                 {
                   // solution at the quadrature point
                   FValue fineval = f.eval_at_point(context,
                                                    var_component,
                                                    xyz_values[qp],
                                                    system.time);
                   // solution grad at the quadrature point
                   VectorValue<FValue> finegrad;
                   if (cont == C_ONE)
                     finegrad = g->eval_at_point(context,
                                                 var_component,
                                                 xyz_values[qp],
                                                 system.time);
                   // Form interior projection matrix
                   for (unsigned int i=0, freei=0; i != n_dofs; ++i)
                     {
                       // fixed DoFs aren't test functions
                       if (dof_is_fixed[i])
                         continue;
                       for (unsigned int j=0, freej=0; j != n_dofs; ++j)
{
                           if (dof_is_fixed[j])
                             Fe(freei) -= phi[i][qp] * phi[j][qp] * JxW[qp]
                               * Ue(j);
                           else
                             Ke(freei,freej) += phi[i][qp] * phi[j][qp] *
                               JxW[qp];
                           if (cont == C_ONE)
{
                               if (dof_is_fixed[j])
                                 Fe(freei) -= ( (*dphi)[i][qp] *
                                                (*dphi)[j][qp] ) * JxW[qp] *
                                   Ue(j);
                               else
                                 Ke(freei,freej) += ( (*dphi)[i][qp] *
                                                      (*dphi)[j][qp] ) *
                                   JxW[qp];
                             }
                           if (!dof_is_fixed[j])
                             freej++;
                         }
                       Fe(freei) += phi[i][qp] * fineval * JxW[qp];
                       if (cont == C_ONE)
                         Fe(freei) += (finegrad * (*dphi)[i][qp] ) * JxW[qp];
                       freei++;
                     }
                 }
               Ke.cholesky_solve(Fe, Uint);
               // Transfer new interior solutions to element
               for (unsigned int i=0; i != free_dofs; ++i)
                 {
                   FValue & ui = Ue(free_dof[i]);
                   libmesh_assert(bool(std::abs(ui) < TOLERANCE) ||
                                  bool(std::abs(ui - Uint(i)) < TOLERANCE));
                   ui = Uint(i);
                   dof_is_fixed[free_dof[i]] = true;
                 }
             } // if there are free interior dofs
           STOP_LOG ("project_interior","GenericProjector");
           // Make sure every DoF got reached!
           for (unsigned int i=0; i != n_dofs; ++i)
             libmesh_assert(dof_is_fixed[i]);
           action.insert(context, var, Ue);
         } // end variables loop
     } // end elements loop
 }
Member Data Documentation
template<typename FFunctor , typename GFunctor , typename FValue , typename ProjectionAction > bool libMesh::GenericProjector< FFunctor, GFunctor, FValue, ProjectionAction >::g_was_copied private
Definition at line 63 of file generic_projector.h.
template<typename FFunctor , typename GFunctor , typename FValue , typename ProjectionAction > const ProjectionAction& libMesh::GenericProjector< FFunctor, GFunctor, FValue, ProjectionAction >::master_action private
Definition at line 64 of file generic_projector.h.
Referenced by libMesh::GenericProjector< FFunctor, GFunctor, FValue, ProjectionAction >::operator()().
template<typename FFunctor , typename GFunctor , typename FValue , typename ProjectionAction > const FFunctor& libMesh::GenericProjector< FFunctor, GFunctor, FValue, ProjectionAction >::master_f private
Definition at line 61 of file generic_projector.h.
Referenced by libMesh::GenericProjector< FFunctor, GFunctor, FValue, ProjectionAction >::operator()().
template<typename FFunctor , typename GFunctor , typename FValue , typename ProjectionAction > const GFunctor* libMesh::GenericProjector< FFunctor, GFunctor, FValue, ProjectionAction >::master_g private
Definition at line 62 of file generic_projector.h.
Referenced by libMesh::GenericProjector< FFunctor, GFunctor, FValue, ProjectionAction >::operator()(), and libMesh::GenericProjector< FFunctor, GFunctor, FValue, ProjectionAction >::~GenericProjector().
template<typename FFunctor , typename GFunctor , typename FValue , typename ProjectionAction > const System& libMesh::GenericProjector< FFunctor, GFunctor, FValue, ProjectionAction >::system private
Definition at line 57 of file generic_projector.h.
Referenced by libMesh::GenericProjector< FFunctor, GFunctor, FValue, ProjectionAction >::operator()().
template<typename FFunctor , typename GFunctor , typename FValue , typename ProjectionAction > const std::vector<unsigned int>& libMesh::GenericProjector< FFunctor, GFunctor, FValue, ProjectionAction >::variables private
Definition at line 65 of file generic_projector.h.
Referenced by libMesh::GenericProjector< FFunctor, GFunctor, FValue, ProjectionAction >::operator()().
The documentation for this class was generated from the following file:
generic_projector.h