libMesh: libMesh::Tet4 Class Reference
SomeWebsiteLogo
libMesh::Tet4 Class Reference
A 3D tetrahedral element with 4 nodes.
#include <cell_tet4.h>
Public Types
enum Diagonal { DIAG_02_13 =0, DIAG_03_12 =1, DIAG_01_23 =2, INVALID_DIAG =99 }
enum RefinementState {
COARSEN = 0, DO_NOTHING, REFINE, JUST_REFINED,
JUST_COARSENED, INACTIVE, COARSEN_INACTIVE, INVALID_REFINEMENTSTATE
}
typedef Predicates::multi_predicate Predicate
Public Member Functions
Tet4 (Elem *p=libmesh_nullptr)
virtual ElemType type () const libmesh_override
virtual unsigned int n_nodes () const libmesh_override
virtual unsigned int n_sub_elem () const libmesh_override
virtual bool is_vertex (const unsigned int i) const libmesh_override
virtual bool is_edge (const unsigned int i) const libmesh_override
virtual bool is_face (const unsigned int i) const libmesh_override
virtual bool is_node_on_side (const unsigned int n, const unsigned int s) const libmesh_override
virtual bool is_node_on_edge (const unsigned int n, const unsigned int e) const libmesh_override
virtual bool is_child_on_side (const unsigned int c, const unsigned int s) const libmesh_override
virtual bool has_affine_map () const libmesh_override
virtual bool is_linear () const libmesh_override
virtual Order default_order () const libmesh_override
virtual UniquePtr< Elem > build_side_ptr (const unsigned int i, bool proxy) libmesh_override
virtual UniquePtr< Elem > build_edge_ptr (const unsigned int i) libmesh_override
virtual void connectivity (const unsigned int sc, const IOPackage iop, std::vector< dof_id_type > &conn) const libmesh_override
virtual Real volume () const libmesh_override
std::pair< Real, Real > min_and_max_angle () const
virtual dof_id_type key () const libmesh_override
virtual bool contains_point (const Point &p, Real tol) const libmesh_override
virtual Point master_point (const unsigned int i) const libmesh_override
virtual unsigned int n_sides () const libmesh_override
virtual unsigned int n_vertices () const libmesh_override
virtual unsigned int n_edges () const libmesh_override
virtual unsigned int n_faces () const libmesh_override
virtual unsigned int n_children () const libmesh_override
virtual bool is_edge_on_side (const unsigned int e, const unsigned int s) const libmesh_override
virtual dof_id_type key (const unsigned int s) const libmesh_override
virtual unsigned int which_node_am_i (unsigned int side, unsigned int side_node) const libmesh_override
virtual UniquePtr< Elem > side_ptr (const unsigned int i) libmesh_override
UniquePtr< const Elem > side_ptr (unsigned int i) const
virtual Real quality (const ElemQuality q) const libmesh_override
virtual std::pair< Real, Real > qual_bounds (const ElemQuality q) const libmesh_override
Diagonal diagonal_selection () const
void select_diagonal (const Diagonal diag) const
virtual unsigned int embedding_matrix_version () const libmesh_override
virtual unsigned int dim () const libmesh_override
virtual BoundingBox loose_bounding_box () const libmesh_override
virtual bool infinite () const libmesh_override
const Point & point (const unsigned int i) const
Point & point (const unsigned int i)
dof_id_type node_id (const unsigned int i) const
dof_id_type node (const unsigned int i) const
unsigned int local_node (const dof_id_type i) const
unsigned int get_node_index (const Node *node_ptr) const
const Node *const * get_nodes () const
const Node * node_ptr (const unsigned int i) const
Node * node_ptr (const unsigned int i)
const Node & node_ref (const unsigned int i) const
Node & node_ref (const unsigned int i)
Node * get_node (const unsigned int i) const
virtual Node *& set_node (const unsigned int i)
subdomain_id_type subdomain_id () const
subdomain_id_type & subdomain_id ()
const Elem * reference_elem () const
bool operator== (const Elem &rhs) const
const Elem * neighbor_ptr (unsigned int i) const
Elem * neighbor_ptr (unsigned int i)
Elem * neighbor (const unsigned int i) const
const Elem * topological_neighbor (const unsigned int i, const MeshBase &mesh, const PointLocatorBase &point_locator, const PeriodicBoundaries *pb) const
Elem * topological_neighbor (const unsigned int i, MeshBase &mesh, const PointLocatorBase &point_locator, const PeriodicBoundaries *pb)
bool has_topological_neighbor (const Elem *elem, const MeshBase &mesh, const PointLocatorBase &point_locator, const PeriodicBoundaries *pb) const
void set_neighbor (const unsigned int i, Elem *n)
bool has_neighbor (const Elem *elem) const
Elem * child_neighbor (Elem *elem)
const Elem * child_neighbor (const Elem *elem) const
bool on_boundary () const
bool is_semilocal (const processor_id_type my_pid) const
unsigned int which_neighbor_am_i (const Elem *e) const
unsigned int which_side_am_i (const Elem *e) const
bool contains_vertex_of (const Elem *e) const
bool contains_edge_of (const Elem *e) const
void find_point_neighbors (const Point &p, std::set< const Elem * > &neighbor_set) const
void find_point_neighbors (std::set< const Elem * > &neighbor_set) const
void find_point_neighbors (std::set< const Elem * > &neighbor_set, const Elem *start_elem) const
void find_edge_neighbors (const Point &p1, const Point &p2, std::set< const Elem * > &neighbor_set) const
void find_edge_neighbors (std::set< const Elem * > &neighbor_set) const
void find_interior_neighbors (std::set< const Elem * > &neighbor_set) const
void remove_links_to_me ()
void make_links_to_me_remote ()
void make_links_to_me_local (unsigned int n)
virtual bool is_remote () const
void write_connectivity (std::ostream &out, const IOPackage iop) const
virtual unsigned int n_nodes_in_child (unsigned int) const
virtual unsigned int n_neighbors () const
virtual unsigned int is_vertex_on_child (unsigned int, unsigned int n) const
virtual bool is_vertex_on_parent (unsigned int c, unsigned int n) const
virtual unsigned int opposite_side (const unsigned int s) const
virtual unsigned int opposite_node (const unsigned int n, const unsigned int s) const
UniquePtr< Elem > side (const unsigned int i) const
UniquePtr< const Elem > build_side_ptr (const unsigned int i, bool proxy=true) const
UniquePtr< Elem > build_side (const unsigned int i, bool proxy=true) const
UniquePtr< const Elem > build_edge_ptr (const unsigned int i) const
UniquePtr< Elem > build_edge (const unsigned int i) const
virtual Point centroid () const
virtual Real hmin () const
virtual Real hmax () const
virtual bool close_to_point (const Point &p, Real tol) const
void print_info (std::ostream &os=libMesh::out) const
std::string get_info () const
bool active () const
bool ancestor () const
bool subactive () const
bool has_children () const
bool has_ancestor_children () const
bool is_ancestor_of (const Elem *descendant) const
const Elem * parent () const
Elem * parent ()
void set_parent (Elem *p)
const Elem * top_parent () const
const Elem * interior_parent () const
Elem * interior_parent ()
void set_interior_parent (Elem *p)
Real length (const unsigned int n1, const unsigned int n2) const
virtual unsigned int n_second_order_adjacent_vertices (const unsigned int n) const
virtual unsigned short int second_order_adjacent_vertex (const unsigned int n, const unsigned int v) const
virtual std::pair< unsigned short int, unsigned short int > second_order_child_vertex (const unsigned int n) const
unsigned int level () const
unsigned int p_level () const
const Elem * child_ptr (unsigned int i) const
Elem * child_ptr (unsigned int i)
Elem * child (const unsigned int i) const
unsigned int which_child_am_i (const Elem *e) const
virtual bool is_child_on_edge (const unsigned int c, const unsigned int e) const
void add_child (Elem *elem)
void add_child (Elem *elem, unsigned int c)
void replace_child (Elem *elem, unsigned int c)
void family_tree (std::vector< const Elem * > &family, const bool reset=true) const
void total_family_tree (std::vector< const Elem * > &active_family, const bool reset=true) const
void active_family_tree (std::vector< const Elem * > &active_family, const bool reset=true) const
void family_tree_by_side (std::vector< const Elem * > &family, const unsigned int side, const bool reset=true) const
void active_family_tree_by_side (std::vector< const Elem * > &family, const unsigned int side, const bool reset=true) const
void family_tree_by_neighbor (std::vector< const Elem * > &family, const Elem *neighbor, const bool reset=true) const
void total_family_tree_by_neighbor (std::vector< const Elem * > &family, const Elem *neighbor, const bool reset=true) const
void family_tree_by_subneighbor (std::vector< const Elem * > &family, const Elem *neighbor, const Elem *subneighbor, const bool reset=true) const
void total_family_tree_by_subneighbor (std::vector< const Elem * > &family, const Elem *neighbor, const Elem *subneighbor, const bool reset=true) const
void active_family_tree_by_neighbor (std::vector< const Elem * > &family, const Elem *neighbor, const bool reset=true) const
void active_family_tree_by_topological_neighbor (std::vector< const Elem * > &family, const Elem *neighbor, const MeshBase &mesh, const PointLocatorBase &point_locator, const PeriodicBoundaries *pb, const bool reset=true) const
RefinementState refinement_flag () const
void set_refinement_flag (const RefinementState rflag)
RefinementState p_refinement_flag () const
void set_p_refinement_flag (const RefinementState pflag)
unsigned int max_descendant_p_level () const
unsigned int min_p_level_by_neighbor (const Elem *neighbor, unsigned int current_min) const
unsigned int min_new_p_level_by_neighbor (const Elem *neighbor, unsigned int current_min) const
void set_p_level (const unsigned int p)
void hack_p_level (const unsigned int p)
virtual void refine (MeshRefinement &mesh_refinement)
void coarsen ()
void contract ()
void libmesh_assert_valid_neighbors () const
void libmesh_assert_valid_node_pointers () const
side_iterator boundary_sides_begin ()
side_iterator boundary_sides_end ()
virtual bool is_mid_infinite_edge_node (const unsigned int) const
virtual Point origin () const
virtual unsigned int as_parent_node (unsigned int c, unsigned int n) const
virtual const std::vector< std::pair< unsigned char, unsigned char > > & parent_bracketing_nodes (unsigned int c, unsigned int n) const
virtual const std::vector< std::pair< dof_id_type, dof_id_type > > bracketing_nodes (unsigned int c, unsigned int n) const
void nullify_neighbors ()
void clear_old_dof_object ()
void set_old_dof_object ()
void clear_dofs ()
void invalidate_dofs (const unsigned int sys_num=libMesh::invalid_uint)
void invalidate_id ()
void invalidate_processor_id ()
void invalidate ()
unsigned int n_dofs (const unsigned int s, const unsigned int var=libMesh::invalid_uint) const
dof_id_type id () const
dof_id_type & set_id ()
void set_id (const dof_id_type dofid)
unique_id_type unique_id () const
unique_id_type & set_unique_id ()
bool valid_id () const
bool valid_unique_id () const
processor_id_type processor_id () const
processor_id_type & processor_id ()
void processor_id (const processor_id_type pid)
bool valid_processor_id () const
unsigned int n_systems () const
void set_n_systems (const unsigned int s)
void add_system ()
unsigned int n_var_groups (const unsigned int s) const
unsigned int n_vars (const unsigned int s, const unsigned int vg) const
unsigned int n_vars (const unsigned int s) const
void set_n_vars_per_group (const unsigned int s, const std::vector< unsigned int > &nvpg)
unsigned int n_comp (const unsigned int s, const unsigned int var) const
unsigned int n_comp_group (const unsigned int s, const unsigned int vg) const
void set_n_comp (const unsigned int s, const unsigned int var, const unsigned int ncomp)
void set_n_comp_group (const unsigned int s, const unsigned int vg, const unsigned int ncomp)
dof_id_type dof_number (const unsigned int s, const unsigned int var, const unsigned int comp) const
void set_dof_number (const unsigned int s, const unsigned int var, const unsigned int comp, const dof_id_type dn)
bool has_dofs (const unsigned int s=libMesh::invalid_uint) const
void set_vg_dof_base (const unsigned int s, const unsigned int vg, const dof_id_type db)
dof_id_type vg_dof_base (const unsigned int s, const unsigned int vg) const
unsigned int packed_indexing_size () const
void unpack_indexing (std::vector< largest_id_type >::const_iterator begin)
void pack_indexing (std::back_insert_iterator< std::vector< largest_id_type > > target) const
void debug_buffer () const
void print_dof_info () const
void set_buffer (const std::vector< dof_id_type > &buf)
Static Public Member Functions
static void print_info (std::ostream &out=libMesh::out)
static void print_info (std::ostream &out=libMesh::out)
static std::string get_info ()
static std::string get_info ()
static ElemType second_order_equivalent_type (const ElemType et, const bool full_ordered=true)
static ElemType first_order_equivalent_type (const ElemType et)
static UniquePtr< Elem > build (const ElemType type, Elem *p=libmesh_nullptr)
static unsigned int n_objects ()
static unsigned int n_objects ()
static void enable_print_counter_info ()
static void enable_print_counter_info ()
static void disable_print_counter_info ()
static void disable_print_counter_info ()
static unsigned int unpackable_indexing_size (std::vector< largest_id_type >::const_iterator begin)
Public Attributes
DofObject * old_dof_object
Static Public Attributes
static const unsigned int side_nodes_map [4][3]
static const unsigned int edge_nodes_map [6][2]
static const subdomain_id_type invalid_subdomain_id = std::numeric_limits<subdomain_id_type>::max()
static const unsigned int type_to_n_nodes_map [INVALID_ELEM]
static const unsigned int type_to_n_sides_map [INVALID_ELEM]
static const unsigned int type_to_n_edges_map [INVALID_ELEM]
static const dof_id_type invalid_id = static_cast<dof_id_type>(-1)
static const unique_id_type invalid_unique_id = static_cast<unique_id_type>(-1)
static const processor_id_type invalid_processor_id = static_cast<processor_id_type>(-1)
Protected Types
typedef std::map< std::string, std::pair< unsigned int, unsigned int > > Counts
typedef std::map< std::string, std::pair< unsigned int, unsigned int > > Counts
Protected Member Functions
virtual float embedding_matrix (const unsigned int i, const unsigned int j, const unsigned int k) const libmesh_override
bool is_child_on_side_helper (const unsigned int c, const unsigned int s, const unsigned int checked_nodes[][3]) const
void choose_diagonal () const
virtual std::vector< std::vector< std::vector< std::vector< std::pair< unsigned char, unsigned char > > > > > & _get_bracketing_node_cache () const
virtual std::vector< std::vector< std::vector< signed char > > > & _get_parent_indices_cache () const
void increment_constructor_count (const std::string &name)
void increment_constructor_count (const std::string &name)
void increment_destructor_count (const std::string &name)
void increment_destructor_count (const std::string &name)
Static Protected Member Functions
static dof_id_type compute_key (dof_id_type n0)
static dof_id_type compute_key (dof_id_type n0, dof_id_type n1)
static dof_id_type compute_key (dof_id_type n0, dof_id_type n1, dof_id_type n2)
static dof_id_type compute_key (dof_id_type n0, dof_id_type n1, dof_id_type n2, dof_id_type n3)
Protected Attributes
Node * _nodelinks_data [4]
LIBMESH_ENABLE_TOPOLOGY_CACHES
Elem * _elemlinks_data [5+(LIBMESH_DIM >3)]
Diagonal _diagonal_selection
Node ** _nodes
Elem ** _elemlinks
Elem ** _children
subdomain_id_type _sbd_id
unsigned char _rflag
unsigned char _pflag
unsigned char _p_level
Static Protected Attributes
static const float _embedding_matrix [8][4][4]
static const Real _master_points [10][3]
static Counts _counts
static Counts _counts
static Threads::atomic< unsigned int > _n_objects
static Threads::atomic< unsigned int > _n_objects
static Threads::spin_mutex _mutex
static Threads::spin_mutex _mutex
static bool _enable_print_counter = true
static bool _enable_print_counter = true
Detailed Description
A 3D tetrahedral element with 4 nodes.
The Tet4 is an element in 3D composed of 4 nodes. It is numbered like this:
*   TET4:
*         3
*         o
*        /|\
*       / | \
*      /  |  \
*   0 o...|...o 2
*      \  |  /
*       \ | /
*        \|/
*         o
*         1
*
Author
Benjamin S. Kirk
Date
2002
Definition at line 51 of file cell_tet4.h.
Member Typedef Documentation
typedef std::map<std::string, std::pair<unsigned int, unsigned int> > libMesh::ReferenceCounter::Counts protected inherited
Data structure to log the information. The log is identified by the class name.
Definition at line 119 of file reference_counter.h.
typedef std::map<std::string, std::pair<unsigned int, unsigned int> > libMesh::ReferenceCounter::Counts protected inherited
Data structure to log the information. The log is identified by the class name.
Definition at line 119 of file reference_counter.h.
typedef Predicates::multi_predicate libMesh::Elem::Predicate inherited
Useful iterator typedefs
Definition at line 1333 of file elem.h.
Member Enumeration Documentation
enum libMesh::Tet::Diagonal inherited
This enumeration keeps track of which diagonal is selected during refinement. In general there are three possible diagonals to choose when splitting the octahedron, and by choosing the shortest one we obtain the best element shape.
Enumerator
DIAG_02_13
DIAG_03_12
DIAG_01_23
INVALID_DIAG
Definition at line 138 of file cell_tet.h.
     {
       DIAG_02_13=0,    // diagonal between edges (0,2) and (1,3)
       DIAG_03_12=1,    // diagonal between edges (0,3) and (1,2)
       DIAG_01_23=2,    // diagonal between edges (0,1) and (2,3)
       INVALID_DIAG=99  // diagonal not yet selected
     };
enum libMesh::Elem::RefinementState inherited
Enumeration of possible element refinement states.
Enumerator
COARSEN
DO_NOTHING
REFINE
JUST_REFINED
JUST_COARSENED
INACTIVE
COARSEN_INACTIVE
INVALID_REFINEMENTSTATE
Definition at line 1057 of file elem.h.
                        { COARSEN = 0,
                          DO_NOTHING,
                          REFINE,
                          JUST_REFINED,
                          JUST_COARSENED,
                          INACTIVE,
                          COARSEN_INACTIVE,
                          INVALID_REFINEMENTSTATE };
Constructor & Destructor Documentation
libMesh::Tet4::Tet4 (Elem * p = libmesh_nullptr) inline explicit
Constructor. By default this element has no parent.
Definition at line 59 of file cell_tet4.h.
                                   :
     Tet(Tet4::n_nodes(), p, _nodelinks_data)
   {}
Member Function Documentation
virtual std::vector<std::vector<std::vector<std::vector<std::pair<unsigned char, unsigned char> > > > >& libMesh::Elem::_get_bracketing_node_cache () const inline protected virtual inherited
Elem subclasses which don't do their own bracketing node calculations will need to supply a static cache, since the default calculation is slow.
Definition at line 1486 of file elem.h.
Referenced by libMesh::Elem::parent_bracketing_nodes().
   {
     static std::vector<std::vector<std::vector<std::vector<std::pair<unsigned char, unsigned char> > > > > c;
     libmesh_error();
     return c;
   }
virtual std::vector<std::vector<std::vector<signed char> > >& libMesh::Elem::_get_parent_indices_cache () const inline protected virtual inherited
Elem subclasses which don't do their own child-to-parent node calculations will need to supply a static cache, since the default calculation is slow.
Definition at line 1500 of file elem.h.
References libMesh::Elem::nullify_neighbors().
Referenced by libMesh::Elem::as_parent_node().
   {
     static std::vector<std::vector<std::vector<signed char> > > c;
     libmesh_error();
     return c;
   }
bool libMesh::Elem::active () const inline inherited
Returns
true if the element is active (i.e. has no active descendants) or AMR is disabled, false otherwise.
Note
It suffices to check the first child only.
Definition at line 2053 of file elem.h.
References libMesh::Elem::COARSEN_INACTIVE, libMesh::Elem::INACTIVE, and libMesh::Elem::refinement_flag().
Referenced by libMesh::MeshRefinement::_coarsen_elements(), libMesh::DofMap::_dof_indices(), libMesh::MeshRefinement::_refine_elements(), libMesh::Elem::active_family_tree(), libMesh::Elem::active_family_tree_by_neighbor(), libMesh::Elem::active_family_tree_by_side(), libMesh::Elem::active_family_tree_by_topological_neighbor(), libMesh::HPCoarsenTest::add_projection(), libMesh::Elem::ancestor(), libMesh::Patch::build_around_element(), libMesh::ParmetisPartitioner::build_graph(), libMesh::Elem::coarsen(), libMesh::MeshRefinement::coarsen_elements(), libMesh::FEGenericBase< OutputType >::compute_periodic_constraints(), libMesh::FEAbstract::compute_periodic_node_constraints(), libMesh::FEGenericBase< OutputType >::compute_proj_constraints(), libMesh::connect_families(), libMesh::UnstructuredMesh::contract(), libMesh::Elem::contract(), libMesh::DofMap::dof_indices(), libMesh::MeshRefinement::eliminate_unrefined_patches(), libMesh::JumpErrorEstimator::estimate_error(), libMesh::ExactErrorEstimator::estimate_error(), libMesh::Elem::family_tree(), libMesh::Elem::family_tree_by_neighbor(), libMesh::Elem::family_tree_by_side(), libMesh::Elem::family_tree_by_subneighbor(), libMesh::Elem::find_edge_neighbors(), libMesh::Patch::find_face_neighbors(), libMesh::Elem::find_interior_neighbors(), libMesh::UnstructuredMesh::find_neighbors(), libMesh::MeshTools::find_nodal_neighbors(), libMesh::Elem::find_point_neighbors(), libMesh::MeshRefinement::flag_elements_by_nelem_target(), libMesh::Elem::get_info(), libMesh::ErrorVector::is_active_elem(), libMesh::Elem::is_linear(), libMesh::MeshTools::libmesh_assert_topology_consistent_procids< Elem >(), libMesh::DistributedMesh::libmesh_assert_valid_parallel_flags(), libMesh::DistributedMesh::libmesh_assert_valid_parallel_p_levels(), libMesh::MeshTools::libmesh_assert_valid_refinement_tree(), libMesh::MeshTools::libmesh_assert_valid_remote_elems(), libMesh::MeshRefinement::make_coarsening_compatible(), libMesh::Elem::make_links_to_me_local(), libMesh::MeshRefinement::make_refinement_compatible(), libMesh::Elem::max_descendant_p_level(), libMesh::Elem::min_new_p_level_by_neighbor(), libMesh::Elem::min_p_level_by_neighbor(), libMesh::DofMap::old_dof_indices(), libMesh::GhostPointNeighbors::operator()(), libMesh::PointLocatorTree::operator()(), libMesh::MetisPartitioner::partition_range(), libMesh::Elem::refine(), libMesh::MeshRefinement::refine_and_coarsen_elements(), libMesh::MeshRefinement::refine_elements(), libMesh::Elem::subactive(), libMesh::Parallel::sync_element_data_by_parent_id(), libMesh::MeshRefinement::test_level_one(), and libMesh::Parallel::Packing< Elem * >::unpack().
 {
 #ifdef LIBMESH_ENABLE_AMR
   if ((this->refinement_flag() == INACTIVE) ||
       (this->refinement_flag() == COARSEN_INACTIVE))
     return false;
   else
     return true;
 #else
   return true;
 #endif
 }
void libMesh::Elem::active_family_tree (std::vector< const Elem * > & active_family, const bool reset = true) const inherited
Same as the family_tree() member, but only adds the active children. Can be thought of as removing all the inactive elements from the vector created by family_tree, but is implemented more efficiently.
Definition at line 1717 of file elem.C.
References libMesh::Elem::active(), libMesh::Elem::active_family_tree(), libMesh::Elem::child_ptr(), libMesh::Elem::is_remote(), libMesh::libmesh_assert(), libMesh::Elem::n_children(), and libMesh::Elem::subactive().
Referenced by libMesh::Elem::active_family_tree(), libMesh::ParmetisPartitioner::build_graph(), libMesh::MeshCommunication::delete_remote_elements(), libMesh::SiblingCoupling::operator()(), libMesh::MetisPartitioner::partition_range(), and libMesh::Partitioner::set_parent_processor_ids().
 {
   // The "family tree" doesn't include subactive elements
   libmesh_assert(!this->subactive());
   // Clear the vector if the flag reset tells us to.
   if (reset)
     active_family.clear();
   // Add this element to the family tree if it is active
   if (this->active())
     active_family.push_back(this);
   // Otherwise recurse into the element's children.
   // Do not clear the vector any more.
   else
     for (unsigned int c=0; c<this->n_children(); c++)
       if (!this->child_ptr(c)->is_remote())
         this->child_ptr(c)->active_family_tree (active_family, false);
 }
void libMesh::Elem::active_family_tree_by_neighbor (std::vector< const Elem * > & family, const Elem * neighbor, const bool reset = true) const inherited
Same as the active_family_tree() member, but only adds elements which are next to neighbor.
Definition at line 1994 of file elem.C.
References libMesh::Elem::active(), libMesh::Elem::active_family_tree_by_neighbor(), libMesh::Elem::child_ptr(), libMesh::Elem::has_neighbor(), libMesh::Elem::level(), libMesh::libmesh_assert(), libMesh::Elem::n_children(), libMesh::remote_elem, and libMesh::Elem::subactive().
Referenced by libMesh::Elem::active_family_tree_by_neighbor(), libMesh::Elem::find_edge_neighbors(), libMesh::Patch::find_face_neighbors(), libMesh::Elem::find_point_neighbors(), libMesh::GhostPointNeighbors::operator()(), and libMesh::DefaultCoupling::operator()().
 {
   // The "family tree" doesn't include subactive elements or
   // remote_elements
   libmesh_assert(!this->subactive());
   libmesh_assert(this != remote_elem);
   // Clear the vector if the flag reset tells us to.
   if (reset)
     family.clear();
   // This only makes sense if we're already a neighbor
 #ifndef NDEBUG
   if (this->level() >= neighbor_in->level())
     libmesh_assert (this->has_neighbor(neighbor_in));
 #endif
   // Add an active element to the family tree.
   if (this->active())
     family.push_back(this);
   // Or recurse into an ancestor element's children.
   // Do not clear the vector any more.
   else if (!this->active())
     for (unsigned int c=0; c<this->n_children(); c++)
       {
         const Elem * current_child = this->child_ptr(c);
         if (current_child != remote_elem && current_child->has_neighbor(neighbor_in))
           current_child->active_family_tree_by_neighbor (family, neighbor_in, false);
       }
 }
void libMesh::Elem::active_family_tree_by_side (std::vector< const Elem * > & family, const unsigned int side, const bool reset = true) const inherited
Same as the active_family_tree() member, but only adds elements which are next to side.
Definition at line 1767 of file elem.C.
References libMesh::Elem::active(), libMesh::Elem::active_family_tree_by_side(), libMesh::Elem::child_ptr(), libMesh::Elem::is_child_on_side(), libMesh::Elem::is_remote(), libMesh::libmesh_assert(), libMesh::Elem::n_children(), libMesh::Elem::n_sides(), libMesh::remote_elem, and libMesh::Elem::subactive().
Referenced by libMesh::Elem::active_family_tree_by_side(), libMesh::Nemesis_IO_Helper::write_sidesets(), and libMesh::ExodusII_IO_Helper::write_sidesets().
 {
   // The "family tree" doesn't include subactive or remote elements
   libmesh_assert(!this->subactive());
   libmesh_assert(this != remote_elem);
   // Clear the vector if the flag reset tells us to.
   if (reset)
     family.clear();
   libmesh_assert_less (s, this->n_sides());
   // Add an active element to the family tree.
   if (this->active())
     family.push_back(this);
   // Or recurse into an ancestor element's children.
   // Do not clear the vector any more.
   else
     for (unsigned int c=0; c<this->n_children(); c++)
       if (!this->child_ptr(c)->is_remote() && this->is_child_on_side(c, s))
         this->child_ptr(c)->active_family_tree_by_side (family, s, false);
 }
void libMesh::Elem::active_family_tree_by_topological_neighbor (std::vector< const Elem * > & family, const Elem * neighbor, const MeshBase & mesh, const PointLocatorBase & point_locator, const PeriodicBoundaries * pb, const bool reset = true) const inherited
Same as the active_family_tree_by_neighbor() member, but the neighbor here may be a topological (e.g. periodic boundary condition) neighbor, not just a local neighbor.
Definition at line 1947 of file elem.C.
References libMesh::Elem::active(), libMesh::Elem::active_family_tree_by_topological_neighbor(), libMesh::Elem::child_ptr(), libMesh::Elem::has_topological_neighbor(), libMesh::Elem::level(), libMesh::libmesh_assert(), libMesh::Elem::n_children(), libMesh::remote_elem, and libMesh::Elem::subactive().
Referenced by libMesh::Elem::active_family_tree_by_topological_neighbor(), libMesh::DefaultCoupling::operator()(), and libMesh::Elem::total_family_tree_by_subneighbor().
 {
   // The "family tree" doesn't include subactive elements or
   // remote_elements
   libmesh_assert(!this->subactive());
   libmesh_assert(this != remote_elem);
   // Clear the vector if the flag reset tells us to.
   if (reset)
     family.clear();
   // This only makes sense if we're already a topological neighbor
 #ifndef NDEBUG
   if (this->level() >= neighbor_in->level())
     libmesh_assert (this->has_topological_neighbor(neighbor_in,
                                                    mesh,
                                                    point_locator,
                                                    pb));
 #endif
   // Add an active element to the family tree.
   if (this->active())
     family.push_back(this);
   // Or recurse into an ancestor element's children.
   // Do not clear the vector any more.
   else if (!this->active())
     for (unsigned int c=0; c<this->n_children(); c++)
       {
         const Elem * current_child = this->child_ptr(c);
         if (current_child != remote_elem &&
             current_child->has_topological_neighbor(neighbor_in,
                                                     mesh,
                                                     point_locator,
                                                     pb))
           current_child->active_family_tree_by_topological_neighbor
             (family, neighbor_in, mesh, point_locator, pb, false);
       }
 }
void libMesh::Elem::add_child (Elem * elem) inherited
Adds a child pointer to the array of children of this element. If this is the first child to be added, this method allocates memory in the parent's _children array, otherwise, it just sets the pointer.
Definition at line 1604 of file elem.C.
References libMesh::Elem::_children, libmesh_nullptr, libMesh::Elem::n_children(), libMesh::Elem::parent(), libMesh::remote_elem, and libMesh::Elem::set_child().
Referenced by libMesh::UnstructuredMesh::all_first_order(), libMesh::UnstructuredMesh::copy_nodes_and_elements(), libMesh::XdrIO::read_serialized_connectivity(), and libMesh::Parallel::Packing< Elem * >::unpack().
 {
   if (_children == libmesh_nullptr)
     {
       _children = new Elem *[this->n_children()];
       for (unsigned int c=0; c<this->n_children(); c++)
         this->set_child(c, libmesh_nullptr);
     }
   for (unsigned int c=0; c<this->n_children(); c++)
     {
       if (this->_children[c] == libmesh_nullptr || this->_children[c] == remote_elem)
         {
           libmesh_assert_equal_to (this, elem->parent());
           this->set_child(c, elem);
           return;
         }
     }
   libmesh_error_msg("Error: Tried to add a child to an element with full children array");
 }
void libMesh::Elem::add_child (Elem * elem, unsigned int c) inherited
Adds a new child pointer to the specified index in the array of children of this element. If this is the first child to be added, this method allocates memory in the parent's _children array, otherwise, it just sets the pointer.
Definition at line 1629 of file elem.C.
References libMesh::Elem::_children, libMesh::Elem::child_ptr(), libMesh::Elem::has_children(), libMesh::libmesh_assert(), libmesh_nullptr, libMesh::Elem::n_children(), libMesh::Elem::parent(), libMesh::remote_elem, and libMesh::Elem::set_child().
 {
   if (!this->has_children())
     {
       _children = new Elem *[this->n_children()];
       for (unsigned int i=0; i<this->n_children(); i++)
         this->set_child(i, libmesh_nullptr);
     }
   libmesh_assert (this->_children[c] == libmesh_nullptr || this->child_ptr(c) == remote_elem);
   libmesh_assert (elem == remote_elem || this == elem->parent());
   this->set_child(c, elem);
 }
void libMesh::DofObject::add_system () inherited
Adds an additional system to the DofObject
Definition at line 187 of file dof_object.C.
References libMesh::DofObject::_idx_buf, libMesh::DofObject::n_systems(), libMesh::DofObject::n_var_groups(), libMesh::DofObject::n_vars(), and libMesh::DofObject::set_n_systems().
Referenced by libMesh::DofObject::set_id().
 {
   // quick return?
   if (this->n_systems() == 0)
     {
       this->set_n_systems(1);
       return;
     }
   DofObject::index_buffer_t::iterator it = _idx_buf.begin();
   std::advance(it, this->n_systems());
   // this inserts the current vector size at the position for the new system - creating the
   // entry we need for the new system indicating there are 0 variables.
   _idx_buf.insert(it, cast_int<dof_id_type>(_idx_buf.size()));
   // cache this value before we screw it up!
   const unsigned int ns_orig = this->n_systems();
   // incriment the number of systems and the offsets for each of
   // the systems including the new one we just added.
   for (unsigned int i=0; i<ns_orig+1; i++)
     _idx_buf[i]++;
   libmesh_assert_equal_to (this->n_systems(), (ns_orig+1));
   libmesh_assert_equal_to (this->n_vars(ns_orig), 0);
   libmesh_assert_equal_to (this->n_var_groups(ns_orig), 0);
 }
bool libMesh::Elem::ancestor () const inherited
Returns
true if the element is an ancestor (i.e. has an active child or ancestor child), false otherwise or when AMR is disabled.
Definition at line 1569 of file elem.C.
References libMesh::Elem::active(), libMesh::Elem::ancestor(), libMesh::Elem::child_ptr(), libMesh::Elem::has_children(), libMesh::libmesh_assert(), libMesh::Elem::n_children(), libMesh::remote_elem, and libMesh::Elem::subactive().
Referenced by libMesh::Elem::ancestor(), libMesh::UnstructuredMesh::contract(), libMesh::MeshRefinement::eliminate_unrefined_patches(), libMesh::UnstructuredMesh::find_neighbors(), libMesh::Elem::get_info(), libMesh::Elem::is_linear(), libMesh::MeshTools::libmesh_assert_valid_refinement_tree(), libMesh::MeshRefinement::make_coarsening_compatible(), and libMesh::Elem::refine().
 {
 #ifdef LIBMESH_ENABLE_AMR
   // Use a fast, DistributedMesh-safe definition
   const bool is_ancestor =
     !this->active() && !this->subactive();
   // But check for inconsistencies if we have time
 #ifdef DEBUG
   if (!is_ancestor && this->has_children())
     {
       for (unsigned int c=0; c != this->n_children(); ++c)
         {
           const Elem * kid = this->child_ptr(c);
           if (kid != remote_elem)
             {
               libmesh_assert(!kid->active());
               libmesh_assert(!kid->ancestor());
             }
         }
     }
 #endif // DEBUG
   return is_ancestor;
 #else
   return false;
 #endif
 }
unsigned int libMesh::Elem::as_parent_node (unsigned int c, unsigned int n) const virtual inherited
Returns
The local node id on the parent which corresponds to node n of child c, or invalid_uint if no such parent node exists.
Definition at line 2102 of file elem.C.
References libMesh::Elem::_get_parent_indices_cache(), libMesh::Elem::child(), libMesh::Elem::embedding_matrix(), libMesh::Elem::embedding_matrix_version(), libMesh::invalid_uint, libMesh::Elem::n_children(), libMesh::Elem::n_nodes(), and libMesh::Elem::n_nodes_in_child().
Referenced by libMesh::MeshRefinement::add_node(), libMesh::MeshCommunication::make_p_levels_parallel_consistent(), libMesh::Elem::origin(), and libMesh::Elem::parent_bracketing_nodes().
 {
   libmesh_assert_less(child, this->n_children());
   // Cached return values, indexed first by embedding_matrix version,
   // then by child number, then by child node number.
   std::vector<std::vector<std::vector<signed char> > > &
     cached_parent_indices = this->_get_parent_indices_cache();
   unsigned int em_vers = this->embedding_matrix_version();
   // We may be updating the cache on one thread, and while that
   // happens we can't safely access the cache from other threads.
   Threads::spin_mutex::scoped_lock lock(parent_indices_mutex);
   if (em_vers >= cached_parent_indices.size())
     cached_parent_indices.resize(em_vers+1);
   if (child >= cached_parent_indices[em_vers].size())
     {
       const unsigned int nn = this->n_nodes();
       cached_parent_indices[em_vers].resize(this->n_children());
       for (unsigned int c = 0; c != this->n_children(); ++c)
         {
           const unsigned int ncn = this->n_nodes_in_child(c);
           cached_parent_indices[em_vers][c].resize(ncn);
           for (unsigned int cn = 0; cn != ncn; ++cn)
             {
               for (unsigned int n = 0; n != nn; ++n)
                 {
                   const float em_val = this->embedding_matrix
                     (c, cn, n);
                   if (em_val == 1)
                     {
                       cached_parent_indices[em_vers][c][cn] = n;
                       break;
                     }
                   if (em_val != 0)
                     {
                       cached_parent_indices[em_vers][c][cn] =
                         -1;
                       break;
                     }
                   // We should never see an all-zero embedding matrix
                   // row
                   libmesh_assert_not_equal_to (n+1, nn);
                 }
             }
         }
     }
   const signed char cache_val =
     cached_parent_indices[em_vers][child][child_node];
   if (cache_val == -1)
     return libMesh::invalid_uint;
   return cached_parent_indices[em_vers][child][child_node];
 }
Elem::side_iterator libMesh::Elem::boundary_sides_begin () inherited
Iterator accessor functions
Definition at line 2960 of file elem.C.
References libMesh::Elem::_first_side(), and libMesh::Elem::_last_side().
 {
   Predicates::BoundarySide<SideIter> bsp;
   return side_iterator(this->_first_side(), this->_last_side(), bsp);
 }
Elem::side_iterator libMesh::Elem::boundary_sides_end () inherited
Definition at line 2969 of file elem.C.
References libMesh::Elem::_last_side().
 {
   Predicates::BoundarySide<SideIter> bsp;
   return side_iterator(this->_last_side(), this->_last_side(), bsp);
 }
const std::vector< std::pair< dof_id_type, dof_id_type > > libMesh::Elem::bracketing_nodes (unsigned int c, unsigned int n) const virtual inherited
Returns
All the pairs of nodes (indexed by global node id) which should bracket node n of child c.
Definition at line 2374 of file elem.C.
References libMesh::Elem::build(), libMesh::Elem::child(), libMesh::Elem::child_ptr(), libMesh::Elem::default_order(), libMesh::FIRST, libMesh::HEX20, libMesh::DofObject::invalid_id, libMesh::Elem::n_nodes(), libMesh::Elem::n_nodes_in_child(), libMesh::Elem::node_id(), libMesh::Elem::parent_bracketing_nodes(), libMesh::Elem::second_order_equivalent_type(), and libMesh::Elem::type().
Referenced by libMesh::MeshRefinement::add_node(), libMesh::TopologyMap::fill(), and libMesh::Elem::origin().
 {
   std::vector<std::pair<dof_id_type, dof_id_type> > returnval;
   const std::vector<std::pair<unsigned char, unsigned char> > & pbc =
     this->parent_bracketing_nodes(child,child_node);
   for (std::size_t i = 0; i != pbc.size(); ++i)
     {
       if (pbc[i].first < this->n_nodes() &&
           pbc[i].second < this->n_nodes())
         returnval.push_back(std::make_pair(this->node_id(pbc[i].first),
                                            this->node_id(pbc[i].second)));
       else
         {
           // We must be on a non-full-order higher order element...
           libmesh_assert_not_equal_to(this->default_order(), FIRST);
           libmesh_assert_not_equal_to
             (second_order_equivalent_type (this->type(), true),
              this->type());
           libmesh_assert_equal_to
             (second_order_equivalent_type (this->type(), false),
              this->type());
           // And that's a shame, because this is a nasty search:
           // Build the full-order type
           ElemType full_type =
             second_order_equivalent_type(this->type(), /*full_ordered=*/ true);
           UniquePtr<Elem> full_elem = Elem::build(full_type);
           dof_id_type pt1 = DofObject::invalid_id;
           dof_id_type pt2 = DofObject::invalid_id;
           // Find the bracketing nodes by figuring out what
           // already-created children will have them.
           // This only doesn't break horribly because we add children
           // and nodes in straightforward + hierarchical orders...
           for (unsigned int c=0; c <= child; ++c)
             for (unsigned int n=0; n != this->n_nodes_in_child(c); ++n)
               {
                 if (c == child && n == child_node)
                   break;
                 if (pbc[i].first == full_elem->as_parent_node(c,n))
                   {
                     // We should be consistent
                     if (pt1 != DofObject::invalid_id)
                       libmesh_assert_equal_to(pt1, this->child_ptr(c)->node_id(n));
                     pt1 = this->child_ptr(c)->node_id(n);
                   }
                 if (pbc[i].second == full_elem->as_parent_node(c,n))
                   {
                     // We should be consistent
                     if (pt2 != DofObject::invalid_id)
                       libmesh_assert_equal_to(pt2, this->child_ptr(c)->node_id(n));
                     pt2 = this->child_ptr(c)->node_id(n);
                   }
               }
           // We should *usually* find all bracketing nodes by the time
           // we query them (again, because of the child & node add
           // order)
           //
           // The exception is if we're a HEX20, in which case we will
           // find pairs of vertex nodes and edge nodes bracketing the
           // new central node but we *won't* find the pairs of face
           // nodes which we would have had on a HEX27.  In that case
           // we'll still have enough bracketing nodes for a
           // topological lookup, but we won't be able to make the
           // following assertions.
           if (this->type() != HEX20)
             {
               libmesh_assert_not_equal_to (pt1, DofObject::invalid_id);
               libmesh_assert_not_equal_to (pt2, DofObject::invalid_id);
             }
           if (pt1 != DofObject::invalid_id &&
               pt2 != DofObject::invalid_id)
             returnval.push_back(std::make_pair(pt1, pt2));
         }
     }
   return returnval;
 }
UniquePtr< Elem > libMesh::Elem::build (const ElemType type, Elem * p = libmesh_nullptr) static inherited
Returns
An Elem of type type wrapped in a smart pointer.
Definition at line 234 of file elem.C.
References libMesh::EDGE2, libMesh::EDGE3, libMesh::EDGE4, libMesh::HEX20, libMesh::HEX27, libMesh::HEX8, libMesh::INFEDGE2, libMesh::INFHEX16, libMesh::INFHEX18, libMesh::INFHEX8, libMesh::INFPRISM12, libMesh::INFPRISM6, libMesh::INFQUAD4, libMesh::INFQUAD6, libmesh_nullptr, libMesh::NODEELEM, libMesh::PRISM15, libMesh::PRISM18, libMesh::PRISM6, libMesh::PYRAMID13, libMesh::PYRAMID14, libMesh::PYRAMID5, libMesh::QUAD4, libMesh::QUAD8, libMesh::QUAD9, libMesh::QUADSHELL4, libMesh::TET10, libMesh::TET4, libMesh::TRI3, libMesh::TRI3SUBDIVISION, libMesh::TRI6, and libMesh::TRISHELL3.
Referenced by libMesh::GMVIO::_read_one_cell(), libMesh::UnstructuredMesh::all_first_order(), libMesh::UnstructuredMesh::all_second_order(), libMesh::Elem::bracketing_nodes(), libMesh::Nemesis_IO_Helper::build_element_and_node_maps(), libMesh::MeshTools::Generation::build_sphere(), libMesh::UnstructuredMesh::copy_nodes_and_elements(), libMesh::UnstructuredMesh::create_submesh(), libMesh::MeshTools::Modification::flatten(), libMesh::Elem::origin(), libMesh::Elem::parent_bracketing_nodes(), libMesh::Nemesis_IO::read(), libMesh::ExodusII_IO::read(), libMesh::VTKIO::read(), libMesh::CheckpointIO::read_connectivity(), libMesh::AbaqusIO::read_elements(), libMesh::UCDIO::read_implementation(), libMesh::GmshIO::read_mesh(), libMesh::XdrIO::read_serialized_connectivity(), libMesh::Elem::refine(), libMesh::Parallel::Packing< Elem * >::unpack(), and libMesh::GMVIO::write_ascii_old_impl().
 {
   Elem * elem = libmesh_nullptr;
   switch (type)
     {
       // 0D elements
     case NODEELEM:
       {
         elem = new NodeElem(p);
         break;
       }
       // 1D elements
     case EDGE2:
       {
         elem = new Edge2(p);
         break;
       }
     case EDGE3:
       {
         elem = new Edge3(p);
         break;
       }
     case EDGE4:
       {
         elem = new Edge4(p);
         break;
       }
       // 2D elements
     case TRI3:
       {
         elem = new Tri3(p);
         break;
       }
     case TRISHELL3:
       {
         elem = new TriShell3(p);
         break;
       }
     case TRI3SUBDIVISION:
       {
         elem = new Tri3Subdivision(p);
         break;
       }
     case TRI6:
       {
         elem = new Tri6(p);
         break;
       }
     case QUAD4:
       {
         elem = new Quad4(p);
         break;
       }
     case QUADSHELL4:
       {
         elem = new QuadShell4(p);
         break;
       }
     case QUAD8:
       {
         elem = new Quad8(p);
         break;
       }
     case QUAD9:
       {
         elem = new Quad9(p);
         break;
       }
       // 3D elements
     case TET4:
       {
         elem = new Tet4(p);
         break;
       }
     case TET10:
       {
         elem = new Tet10(p);
         break;
       }
     case HEX8:
       {
         elem = new Hex8(p);
         break;
       }
     case HEX20:
       {
         elem = new Hex20(p);
         break;
       }
     case HEX27:
       {
         elem = new Hex27(p);
         break;
       }
     case PRISM6:
       {
         elem = new Prism6(p);
         break;
       }
     case PRISM15:
       {
         elem = new Prism15(p);
         break;
       }
     case PRISM18:
       {
         elem = new Prism18(p);
         break;
       }
     case PYRAMID5:
       {
         elem = new Pyramid5(p);
         break;
       }
     case PYRAMID13:
       {
         elem = new Pyramid13(p);
         break;
       }
     case PYRAMID14:
       {
         elem = new Pyramid14(p);
         break;
       }
 #ifdef LIBMESH_ENABLE_INFINITE_ELEMENTS
       // 1D infinite elements
     case INFEDGE2:
       {
         elem = new InfEdge2(p);
         break;
       }
       // 2D infinite elements
     case INFQUAD4:
       {
         elem = new InfQuad4(p);
         break;
       }
     case INFQUAD6:
       {
         elem = new InfQuad6(p);
         break;
       }
       // 3D infinite elements
     case INFHEX8:
       {
         elem = new InfHex8(p);
         break;
       }
     case INFHEX16:
       {
         elem = new InfHex16(p);
         break;
       }
     case INFHEX18:
       {
         elem = new InfHex18(p);
         break;
       }
     case INFPRISM6:
       {
         elem = new InfPrism6(p);
         break;
       }
     case INFPRISM12:
       {
         elem = new InfPrism12(p);
         break;
       }
 #endif
     default:
       libmesh_error_msg("ERROR: Undefined element type!");
     }
   return UniquePtr<Elem>(elem);
 }
UniquePtr< Elem > libMesh::Elem::build_edge (const unsigned int i) const inline inherited
Creates an element coincident with edge i.
Deprecated:
This method will eventually be removed since it hands back a non-const pointer to an edge that could be used to indirectly modify this Elem. Please use the the const-correct build_edge_ptr() function instead.
Definition at line 1956 of file elem.h.
References libMesh::Elem::build_edge_ptr().
Referenced by libMesh::Elem::is_vertex_on_child().
 {
   // Call the const version of build_edge_ptr(), and const_cast the result.
   libmesh_deprecated();
   Elem * e = const_cast<Elem *>(this->build_edge_ptr(i).release());
   return UniquePtr<Elem>(e);
 }
UniquePtr< Elem > libMesh::Tet4::build_edge_ptr (const unsigned int i) virtual
Builds a EDGE2 built coincident with face i. The UniquePtr<Elem> handles the memory aspect.
Implements libMesh::Elem.
Definition at line 154 of file cell_tet4.C.
References libMesh::Tet::n_edges().
Referenced by default_order().
 {
   libmesh_assert_less (i, this->n_edges());
   return UniquePtr<Elem>(new SideEdge<Edge2,Tet4>(this,i));
 }
UniquePtr< const Elem > libMesh::Elem::build_edge_ptr (const unsigned int i) const inline inherited
Definition at line 1943 of file elem.h.
References libMesh::Elem::build_edge_ptr().
 {
   // Call the non-const version of this function, return the result as
   // a UniquePtr<const Elem>.
   Elem * me = const_cast<Elem *>(this);
   const Elem * e = const_cast<const Elem *>(me->build_edge_ptr(i).release());
   return UniquePtr<const Elem>(e);
 }
UniquePtr< Elem > libMesh::Elem::build_side (const unsigned int i, bool proxy = true) const inline inherited
Returns
A proxy element coincident with side i.
Deprecated:
This method will eventually be removed since it hands back a non-const pointer to a side that could be used to indirectly modify this. Please use the the const-correct build_side_ptr() function instead.
Definition at line 1931 of file elem.h.
References libMesh::Elem::build_side_ptr().
Referenced by libMesh::Elem::is_vertex_on_child().
 {
   // Call the const version of build_side_ptr(), and const_cast the result.
   libmesh_deprecated();
   Elem * s = const_cast<Elem *>(this->build_side_ptr(i, proxy).release());
   return UniquePtr<Elem>(s);
 }
UniquePtr< Elem > libMesh::Tet4::build_side_ptr (const unsigned int i, bool proxy) virtual
Builds a TRI3 built coincident with face i. The UniquePtr<Elem> handles the memory aspect.
Implements libMesh::Elem.
Definition at line 130 of file cell_tet4.C.
References libMesh::Elem::n_nodes(), libMesh::Tet::n_sides(), libMesh::Elem::node_ptr(), libMesh::Elem::set_node(), and libMesh::Elem::subdomain_id().
Referenced by default_order().
 {
   libmesh_assert_less (i, this->n_sides());
   if (proxy)
     return UniquePtr<Elem>(new Side<Tri3,Tet4>(this,i));
   else
     {
       Elem * face = new Tri3;
       face->subdomain_id() = this->subdomain_id();
       for (unsigned n=0; n<face->n_nodes(); ++n)
         face->set_node(n) = this->node_ptr(Tet4::side_nodes_map[i][n]);
       return UniquePtr<Elem>(face);
     }
   libmesh_error_msg("We'll never get here!");
   return UniquePtr<Elem>();
 }
UniquePtr< const Elem > libMesh::Elem::build_side_ptr (const unsigned int i, bool proxy = true) const inline inherited
Definition at line 1918 of file elem.h.
References libMesh::Elem::build_side_ptr().
 {
   // Call the non-const version of this function, return the result as
   // a UniquePtr<const Elem>.
   Elem * me = const_cast<Elem *>(this);
   const Elem * s = const_cast<const Elem *>(me->build_side_ptr(i, proxy).release());
   return UniquePtr<const Elem>(s);
 }
Point libMesh::Elem::centroid () const virtual inherited
Returns
The centriod of the element. The centroid is computed as the average of all the element vertices.
This method is virtual since some derived elements might want to use shortcuts to compute their centroid.
Definition at line 437 of file elem.C.
References libMesh::TypeVector< T >::add(), and libMesh::Elem::n_vertices().
Referenced by libMesh::CentroidPartitioner::compute_centroids(), libMesh::UnstructuredMesh::find_neighbors(), libMesh::BoundaryInfo::get_side_and_node_maps(), libMesh::Elem::is_vertex_on_child(), libMesh::SFCPartitioner::partition_range(), libMesh::LocationMap< T >::point_of(), libMesh::FE< Dim, T >::shape(), libMesh::FE< Dim, T >::shape_deriv(), and libMesh::FE< Dim, T >::shape_second_deriv().
 {
   Point cp;
   for (unsigned int n=0; n<this->n_vertices(); n++)
     cp.add (this->point(n));
   return (cp /= static_cast<Real>(this->n_vertices()));
 }
Elem * libMesh::Elem::child (const unsigned int i) const inline inherited
Returns
A non-constant pointer to the child for this element.
Deprecated:
Use the more accurately-named and const correct child_ptr() function instead.
Definition at line 2251 of file elem.h.
References libMesh::Elem::child_ptr().
Referenced by libMesh::Elem::as_parent_node(), libMesh::Elem::bracketing_nodes(), libMesh::Elem::find_interior_neighbors(), and libMesh::Elem::parent_bracketing_nodes().
 {
   // Support the deprecated interface by calling the new,
   // const-correct interface and casting the result to an Elem *.
   libmesh_deprecated();
   return const_cast<Elem *>(this->child_ptr(i));
 }
Elem * libMesh::Elem::child_neighbor (Elem * elem) inline inherited
Returns
If elem is a neighbor of a child of this element, a pointer to that child, otherwise NULL.
Definition at line 1868 of file elem.h.
References libmesh_nullptr, libMesh::Elem::n_neighbors(), libMesh::Elem::neighbor_ptr(), and libMesh::Elem::parent().
 {
   for (unsigned int n=0; n<elem->n_neighbors(); n++)
     if (elem->neighbor_ptr(n) &&
         elem->neighbor_ptr(n)->parent() == this)
       return elem->neighbor_ptr(n);
   return libmesh_nullptr;
 }
const Elem * libMesh::Elem::child_neighbor (const Elem * elem) const inline inherited
Returns
If elem is a neighbor of a child of this element, a pointer to that child, otherwise NULL.
Definition at line 1881 of file elem.h.
References libmesh_nullptr, libMesh::Elem::n_neighbors(), libMesh::Elem::neighbor_ptr(), and libMesh::Elem::parent().
 {
   for (unsigned int n=0; n<elem->n_neighbors(); n++)
     if (elem->neighbor_ptr(n) &&
         elem->neighbor_ptr(n)->parent() == this)
       return elem->neighbor_ptr(n);
   return libmesh_nullptr;
 }
const Elem * libMesh::Elem::child_ptr (unsigned int i) const inline inherited
Returns
A constant pointer to the child for this element. Do not call if this element has no children, i.e. is active.
Definition at line 2232 of file elem.h.
References libMesh::Elem::_children, and libMesh::libmesh_assert().
Referenced by libMesh::Elem::active_family_tree(), libMesh::Elem::active_family_tree_by_neighbor(), libMesh::Elem::active_family_tree_by_side(), libMesh::Elem::active_family_tree_by_topological_neighbor(), libMesh::Elem::add_child(), libMesh::HPCoarsenTest::add_projection(), libMesh::UnstructuredMesh::all_first_order(), libMesh::Elem::ancestor(), libMesh::Elem::bracketing_nodes(), libMesh::OldSolutionValue< Output, point_output >::check_old_context(), libMesh::Elem::child(), libMesh::Elem::coarsen(), libMesh::FEGenericBase< OutputType >::coarsened_dof_values(), libMesh::connect_children(), libMesh::UnstructuredMesh::copy_nodes_and_elements(), libMesh::MeshRefinement::eliminate_unrefined_patches(), libMesh::JumpErrorEstimator::estimate_error(), libMesh::ExactErrorEstimator::estimate_error(), libMesh::Elem::family_tree(), libMesh::Elem::family_tree_by_neighbor(), libMesh::Elem::family_tree_by_side(), libMesh::Elem::family_tree_by_subneighbor(), libMesh::TopologyMap::fill(), libMesh::Elem::find_interior_neighbors(), libMesh::UnstructuredMesh::find_neighbors(), libMesh::MeshRefinement::flag_elements_by_nelem_target(), libMesh::Elem::has_ancestor_children(), libMesh::Elem::is_vertex_on_parent(), libMesh::MeshTools::libmesh_assert_no_links_to_elem(), libMesh::MeshTools::libmesh_assert_topology_consistent_procids< Elem >(), libMesh::MeshTools::libmesh_assert_valid_refinement_tree(), libMesh::MeshTools::libmesh_assert_valid_remote_elems(), libMesh::MeshRefinement::make_coarsening_compatible(), libMesh::Elem::make_links_to_me_remote(), libMesh::MeshRefinement::make_refinement_compatible(), libMesh::Elem::max_descendant_p_level(), libMesh::Elem::min_new_p_level_by_neighbor(), libMesh::Elem::min_p_level_by_neighbor(), libMesh::GenericProjector< FFunctor, GFunctor, FValue, ProjectionAction >::operator()(), libMesh::BuildProjectionList::operator()(), libMesh::Elem::refine(), libMesh::Elem::replace_child(), libMesh::Elem::set_p_level(), libMesh::Partitioner::set_parent_processor_ids(), libMesh::MeshTools::Modification::smooth(), libMesh::Parallel::sync_element_data_by_parent_id(), libMesh::Elem::total_family_tree(), libMesh::Elem::total_family_tree_by_neighbor(), libMesh::Elem::total_family_tree_by_subneighbor(), libMesh::Parallel::Packing< Elem * >::unpack(), libMesh::Elem::which_child_am_i(), and libMesh::XdrIO::write_serialized_connectivity().
 {
   libmesh_assert(_children);
   libmesh_assert(_children[i]);
   return _children[i];
 }
Elem * libMesh::Elem::child_ptr (unsigned int i) inline inherited
Returns
A non-constant pointer to the child for this element. Do not call if this element has no children, i.e. is active.
Definition at line 2241 of file elem.h.
References libMesh::Elem::_children, and libMesh::libmesh_assert().
 {
   libmesh_assert(_children);
   libmesh_assert(_children[i]);
   return _children[i];
 }
void libMesh::Tet::choose_diagonal () const protected inherited
Derived classes use this function to select an initial diagonal during refinement. The optimal choice is the shortest of the three.
Definition at line 155 of file cell_tet.C.
References libMesh::Tet::_diagonal_selection, libMesh::Tet::DIAG_01_23, libMesh::Tet::DIAG_02_13, libMesh::Tet::DIAG_03_12, libMesh::Tet::INVALID_DIAG, libMesh::TensorTools::norm_sq(), libMesh::Elem::point(), and libMesh::Real.
Referenced by libMesh::Tet10::embedding_matrix(), embedding_matrix(), and libMesh::Tet::embedding_matrix_version().
 {
   // Check for uninitialized diagonal selection
   if (this->_diagonal_selection==INVALID_DIAG)
     {
       Real diag_01_23 = (this->point(0) + this->point(1) - this->point(2) - this->point(3)).norm_sq();
       Real diag_02_13 = (this->point(0) - this->point(1) + this->point(2) - this->point(3)).norm_sq();
       Real diag_03_12 = (this->point(0) - this->point(1) - this->point(2) + this->point(3)).norm_sq();
       this->_diagonal_selection=DIAG_02_13;
       if (diag_01_23 < diag_02_13 || diag_03_12 < diag_02_13)
         {
           if (diag_01_23 < diag_03_12)
             this->_diagonal_selection=DIAG_01_23;
           else
             this->_diagonal_selection=DIAG_03_12;
         }
     }
 }
void libMesh::DofObject::clear_dofs () inline inherited
Clear the DofMap data structures and return to a pristine state.
Definition at line 590 of file dof_object.h.
References libMesh::DofObject::_idx_buf, libMesh::libmesh_assert(), and libMesh::DofObject::n_systems().
Referenced by libMesh::DofObject::set_n_systems(), and libMesh::DofObject::~DofObject().
 {
   // vector swap trick to force deallocation
   index_buffer_t().swap(_idx_buf);
   libmesh_assert_equal_to (this->n_systems(), 0);
   libmesh_assert (_idx_buf.empty());
 }
void libMesh::DofObject::clear_old_dof_object () inherited
Sets the old_dof_object to libmesh_nullptr
Definition at line 134 of file dof_object.C.
References libmesh_nullptr, and libMesh::DofObject::old_dof_object.
Referenced by libMesh::DofObject::operator=(), libMesh::DofObject::set_old_dof_object(), libMesh::DofObject::unpack_indexing(), and libMesh::DofObject::~DofObject().
 {
   delete this->old_dof_object;
   this->old_dof_object = libmesh_nullptr;
 }
bool libMesh::Elem::close_to_point (const Point & p, Real tol) const virtual inherited
Returns
true if this element is "close" to the point p, where "close" is determined by the tolerance tol.
Definition at line 2494 of file elem.C.
References libMesh::Elem::point_test().
Referenced by libMesh::OldSolutionValue< Output, point_output >::check_old_context(), and libMesh::Elem::qual_bounds().
 {
   // This test uses the user's passed-in tolerance for the
   // bounding box test as well, thereby allowing the routine to
   // find points which are not only "in" the element, but also
   // "nearby" to within some tolerance.
   return this->point_test(p, tol, tol);
 }
void libMesh::Elem::coarsen () inherited
Coarsen the element. This function is non-virtual since it is the same for all element types.
Definition at line 104 of file elem_refinement.C.
References libMesh::Elem::active(), libMesh::TypeVector< T >::add_scaled(), libMesh::Elem::child_ptr(), libMesh::Elem::COARSEN, libMesh::Elem::COARSEN_INACTIVE, libMesh::Elem::embedding_matrix(), libMesh::Elem::INACTIVE, libMesh::Elem::JUST_COARSENED, libMesh::libmesh_assert(), libMesh::Elem::n_children(), libMesh::Elem::n_nodes(), libMesh::Elem::p_level(), libMesh::Elem::point(), libMesh::Elem::refinement_flag(), libMesh::remote_elem, libMesh::Elem::set_p_level(), and libMesh::Elem::set_refinement_flag().
Referenced by libMesh::MeshRefinement::_coarsen_elements().
 {
   libmesh_assert_equal_to (this->refinement_flag(), Elem::COARSEN_INACTIVE);
   libmesh_assert (!this->active());
   // We no longer delete children until MeshRefinement::contract()
   // delete [] _children;
   // _children = libmesh_nullptr;
   unsigned int parent_p_level = 0;
   // re-compute hanging node nodal locations
   for (unsigned int c=0; c<this->n_children(); c++)
     {
       Elem * mychild = this->child_ptr(c);
       if (mychild == remote_elem)
         continue;
       for (unsigned int nc=0; nc<mychild->n_nodes(); nc++)
         {
           Point new_pos;
           bool calculated_new_pos = false;
           for (unsigned int n=0; n<this->n_nodes(); n++)
             {
               // The value from the embedding matrix
               const float em_val = this->embedding_matrix(c,nc,n);
               // The node location is somewhere between existing vertices
               if ((em_val != 0.) && (em_val != 1.))
                 {
                   new_pos.add_scaled (this->point(n), em_val);
                   calculated_new_pos = true;
                 }
             }
           if (calculated_new_pos)
             {
               //Move the existing node back into it's original location
               for (unsigned int i=0; i<LIBMESH_DIM; i++)
                 {
                   Point & child_node = mychild->point(nc);
                   child_node(i)=new_pos(i);
                 }
             }
         }
     }
   for (unsigned int c=0; c<this->n_children(); c++)
     {
       Elem * mychild = this->child_ptr(c);
       if (mychild == remote_elem)
         continue;
       libmesh_assert_equal_to (mychild->refinement_flag(), Elem::COARSEN);
       mychild->set_refinement_flag(Elem::INACTIVE);
       if (mychild->p_level() > parent_p_level)
         parent_p_level = mychild->p_level();
     }
   this->set_refinement_flag(Elem::JUST_COARSENED);
   this->set_p_level(parent_p_level);
   libmesh_assert (this->active());
 }
dof_id_type libMesh::Elem::compute_key (dof_id_type n0) inline static protected inherited
Returns
A hash key computed from a single node id.
Definition at line 2405 of file elem.h.
Referenced by libMesh::Elem::embedding_matrix_version(), libMesh::Tet::key(), libMesh::Prism::key(), libMesh::Tri::key(), libMesh::Pyramid::key(), libMesh::Hex::key(), libMesh::InfQuad6::key(), libMesh::Edge::key(), libMesh::InfPrism::key(), libMesh::Tri6::key(), libMesh::Quad9::key(), libMesh::Quad8::key(), libMesh::Quad::key(), libMesh::InfHex::key(), libMesh::InfQuad::key(), libMesh::Hex27::key(), libMesh::Edge2::key(), libMesh::Prism18::key(), libMesh::Pyramid14::key(), libMesh::InfHex18::key(), libMesh::Edge4::key(), libMesh::Edge3::key(), and key().
 {
   return n0;
 }
dof_id_type libMesh::Elem::compute_key (dof_id_type n0, dof_id_type n1) inline static protected inherited
Returns
A hash key computed from two node ids.
Definition at line 2413 of file elem.h.
References libMesh::Utility::hashword2(), and swap().
 {
   // Order the two so that n0 < n1
   if (n0 > n1) std::swap (n0, n1);
   return Utility::hashword2(n0, n1);
 }
dof_id_type libMesh::Elem::compute_key (dof_id_type n0, dof_id_type n1, dof_id_type n2) inline static protected inherited
Returns
A hash key computed from three node ids.
Definition at line 2425 of file elem.h.
References libMesh::Utility::hashword(), libMesh::libmesh_assert(), and swap().
 {
   // Order the numbers such that n0 < n1 < n2.
   // We'll do it in 3 steps like this:
   //
   //     n0         n1                n2
   //     min(n0,n1) max(n0,n1)        n2
   //     min(n0,n1) min(n2,max(n0,n1) max(n2,max(n0,n1)
   //           |\   /|                  |
   //           | \ / |                  |
   //           |  /  |                  |
   //           | /  \|                  |
   //  gb min= min   max              gb max
   // Step 1
   if (n0 > n1) std::swap (n0, n1);
   // Step 2
   if (n1 > n2) std::swap (n1, n2);
   // Step 3
   if (n0 > n1) std::swap (n0, n1);
   libmesh_assert ((n0 < n1) && (n1 < n2));
   dof_id_type array[3] = {n0, n1, n2};
   return Utility::hashword(array, 3);
 }
dof_id_type libMesh::Elem::compute_key (dof_id_type n0, dof_id_type n1, dof_id_type n2, dof_id_type n3) inline static protected inherited
Returns
A hash key computed from four node ids.
Definition at line 2459 of file elem.h.
References libMesh::Utility::hashword(), libMesh::libmesh_assert(), and swap().
 {
   // Sort first
   // Step 1
   if (n0 > n1) std::swap (n0, n1);
   // Step 2
   if (n2 > n3) std::swap (n2, n3);
   // Step 3
   if (n0 > n2) std::swap (n0, n2);
   // Step 4
   if (n1 > n3) std::swap (n1, n3);
   // Finally sort step 5
   if (n1 > n2) std::swap (n1, n2);
   libmesh_assert ((n0 < n1) && (n1 < n2) && (n2 < n3));
   dof_id_type array[4] = {n0, n1, n2, n3};
   return Utility::hashword(array, 4);
 }
void libMesh::Tet4::connectivity (const unsigned int sc, const IOPackage iop, std::vector< dof_id_type > & conn) const virtual
Returns
The connectivity for this element in a specific format, which is specified by the IOPackage tag.
Implements libMesh::Elem.
Definition at line 162 of file cell_tet4.C.
References _embedding_matrix, libMesh::Elem::_nodes, libMesh::INVALID_IO_PACKAGE, libMesh::libmesh_assert(), n_sub_elem(), libMesh::Elem::node_id(), libMesh::TECPLOT, and libMesh::VTK.
Referenced by default_order().
 {
   libmesh_assert(_nodes);
   libmesh_assert_less (sc, this->n_sub_elem());
   libmesh_assert_not_equal_to (iop, INVALID_IO_PACKAGE);
   switch (iop)
     {
     case TECPLOT:
       {
         conn.resize(8);
         conn[0] = this->node_id(0)+1;
         conn[1] = this->node_id(1)+1;
         conn[2] = this->node_id(2)+1;
         conn[3] = this->node_id(2)+1;
         conn[4] = this->node_id(3)+1;
         conn[5] = this->node_id(3)+1;
         conn[6] = this->node_id(3)+1;
         conn[7] = this->node_id(3)+1;
         return;
       }
     case VTK:
       {
         conn.resize(4);
         conn[0] = this->node_id(0);
         conn[1] = this->node_id(1);
         conn[2] = this->node_id(2);
         conn[3] = this->node_id(3);
         return;
       }
     default:
       libmesh_error_msg("Unsupported IO package " << iop);
     }
 }
bool libMesh::Elem::contains_edge_of (const Elem * e) const inherited
Returns
true if an edge of e is contained in this element. (Internally, this is done by checking whether at least two vertices of e are contained in this element).
Definition at line 570 of file elem.C.
References libMesh::Elem::contains_point(), libMesh::Elem::n_vertices(), and libMesh::Elem::point().
Referenced by libMesh::Elem::find_edge_neighbors().
 {
   unsigned int num_contained_edges = 0;
   // Our vertices are the first numbered nodes
   for (unsigned int n = 0; n != e->n_vertices(); ++n)
     {
       if (this->contains_point(e->point(n)))
         {
           num_contained_edges++;
           if (num_contained_edges>=2)
             {
               return true;
             }
         }
     }
   return false;
 }
bool libMesh::Tet4::contains_point (const Point & p, Real tol) const virtual
Uses simple geometric tests to determine if the point p is inside the tetrahedron.
Reimplemented from libMesh::Elem.
Definition at line 340 of file cell_tet4.C.
References libMesh::Elem::point().
 {
   // See the response by Tony Noe on this thread.
   // http://bbs.dartmouth.edu/~fangq/MATH/download/source/Point_in_Tetrahedron.htm
   Point
     col1 = point(1) - point(0),
     col2 = point(2) - point(0),
     col3 = point(3) - point(0);
   Point r;
   libmesh_try
     {
       RealTensorValue(col1(0), col2(0), col3(0),
                       col1(1), col2(1), col3(1),
                       col1(2), col2(2), col3(2)).solve(p - point(0), r);
     }
   libmesh_catch (ConvergenceFailure &)
     {
       // The Jacobian was singular, therefore the Tet had
       // zero volume.  In this degenerate case, it is not
       // possible for the Tet to contain any points.
       return false;
     }
   // The point p is inside the tetrahedron if r1 + r2 + r3 < 1 and
   // 0 <= ri <= 1 for i = 1,2,3.
   return
     r(0) > -tol &&
     r(1) > -tol &&
     r(2) > -tol &&
     r(0) + r(1) + r(2) < 1.0 + tol;
 }
bool libMesh::Elem::contains_vertex_of (const Elem * e) const inherited
Returns
true if a vertex of e is contained in this element.
Definition at line 559 of file elem.C.
References libMesh::Elem::contains_point(), libMesh::Elem::n_vertices(), and libMesh::Elem::point().
Referenced by libMesh::Elem::find_interior_neighbors(), and libMesh::Elem::find_point_neighbors().
 {
   // Our vertices are the first numbered nodes
   for (unsigned int n = 0; n != e->n_vertices(); ++n)
     if (this->contains_point(e->point(n)))
       return true;
   return false;
 }
void libMesh::Elem::contract () inherited
Contract an active element, i.e. remove pointers to any subactive children. This should only be called via MeshRefinement::contract, which will also remove subactive children from the mesh.
Definition at line 170 of file elem_refinement.C.
References libMesh::Elem::_children, libMesh::Elem::active(), libMesh::Elem::DO_NOTHING, libMesh::Elem::JUST_COARSENED, libMesh::libmesh_assert(), libmesh_nullptr, libMesh::Elem::refinement_flag(), and libMesh::Elem::set_refinement_flag().
Referenced by libMesh::UnstructuredMesh::contract().
 {
   // Subactive elements get deleted entirely, not contracted
   libmesh_assert (this->active());
   // Active contracted elements no longer can have children
   delete [] _children;
   _children = libmesh_nullptr;
   if (this->refinement_flag() == Elem::JUST_COARSENED)
     this->set_refinement_flag(Elem::DO_NOTHING);
 }
void libMesh::DofObject::debug_buffer () const inherited
Print our buffer for debugging.
Definition at line 542 of file dof_object.C.
References libMesh::DofObject::_idx_buf, and libMesh::out.
 {
   libMesh::out << " [ ";
   for (std::size_t i=0; i<_idx_buf.size(); i++)
     libMesh::out << _idx_buf[i] << " ";
   libMesh::out << "]\n";
 }
virtual Order libMesh::Tet4::default_order () const inline virtual
Returns
FIRST.
Implements libMesh::Elem.
Definition at line 129 of file cell_tet4.h.
References build_edge_ptr(), build_side_ptr(), connectivity(), and libMesh::FIRST.
 { return FIRST; }
Diagonal libMesh::Tet::diagonal_selection () const inline inherited
Returns
The diagonal that has been selected during refinement.
Definition at line 149 of file cell_tet.h.
References libMesh::Tet::_diagonal_selection, and libMesh::Tet::select_diagonal().
Referenced by libMesh::Tet::embedding_matrix_version().
 { return _diagonal_selection; }
virtual unsigned int libMesh::Cell::dim () const inline virtual inherited
Returns
3, the dimensionality of the object.
Implements libMesh::Elem.
Definition at line 55 of file cell.h.
References libMesh::Cell::loose_bounding_box().
 { return 3; }
void libMesh::ReferenceCounter::disable_print_counter_info () static inherited
Definition at line 107 of file reference_counter.C.
References libMesh::ReferenceCounter::_enable_print_counter.
Referenced by libMesh::LibMeshInit::LibMeshInit(), and libMesh::ReferenceCounter::n_objects().
 {
   _enable_print_counter = false;
   return;
 }
void libMesh::ReferenceCounter::disable_print_counter_info () static inherited
Definition at line 107 of file reference_counter.C.
References libMesh::ReferenceCounter::_enable_print_counter.
Referenced by libMesh::LibMeshInit::LibMeshInit(), and libMesh::ReferenceCounter::n_objects().
 {
   _enable_print_counter = false;
   return;
 }
dof_id_type libMesh::DofObject::dof_number (const unsigned int s, const unsigned int var, const unsigned int comp) const inline inherited
Returns
The global degree of freedom number for variable var, component comp for system s associated with this DofObject
When partitioning and DoF numbering have been performed by libMesh, every current DoF on this DofObject will belong to its processor.
Definition at line 802 of file dof_object.h.
References libMesh::DofObject::_idx_buf, libMesh::DofObject::invalid_id, libMesh::DofObject::n_comp(), libMesh::DofObject::n_comp_group(), libMesh::DofObject::n_systems(), libMesh::DofObject::n_vars(), libMesh::DofObject::start_idx(), libMesh::DofObject::system_var_to_vg_var(), and libMesh::DofObject::var_to_vg().
Referenced by libMesh::DofMap::_dof_indices(), libMesh::DofMap::allgather_recursive_constraints(), libMesh::FEGenericBase< OutputType >::compute_periodic_constraints(), libMesh::DofMap::constrain_p_dofs(), libMesh::ExodusII_IO::copy_elemental_solution(), libMesh::ExodusII_IO::copy_nodal_solution(), libMesh::DofMap::distribute_dofs(), libMesh::DofMap::dof_indices(), libMesh::DofObject::DofObject(), libMesh::OldSolutionValue< Output, point_output >::eval_at_node(), libMesh::Node::get_info(), libMesh::Elem::get_info(), libMesh::DofMap::local_variable_indices(), libMesh::DofMap::old_dof_indices(), libMesh::BuildProjectionList::operator()(), libMesh::DofObject::operator=(), libMesh::DofObject::print_dof_info(), libMesh::HPCoarsenTest::select_refinement(), libMesh::DofObject::set_dof_number(), libMesh::DofObject::set_id(), libMesh::DofMap::set_nonlocal_dof_objects(), and libMesh::System::zero_variable().
 {
   libmesh_assert_less (s,    this->n_systems());
   libmesh_assert_less (var,  this->n_vars(s));
   libmesh_assert_less (comp, this->n_comp(s,var));
   const unsigned int
     vg            = this->var_to_vg(s,var),
     start_idx_sys = this->start_idx(s);
   libmesh_assert_less ((start_idx_sys + 2*vg + 1), _idx_buf.size());
   const dof_id_type
     base_idx = _idx_buf[start_idx_sys + 2*vg + 1];
   // if the first component is invalid, they
   // are all invalid
   if (base_idx == invalid_id)
     return invalid_id;
   // otherwise the index is the first component
   // index augemented by the component number
   else
     {
       const unsigned int
         ncg = this->n_comp_group(s,vg),
         vig = this->system_var_to_vg_var(s,vg,var);
       // std::cout << "base_idx, var, vg, vig, ncg, comp="
       // << base_idx << " "
       // << var << " "
       // << vg << " "
       // << vig << " "
       // << ncg << " "
       // << comp << '\n';
       return cast_int<dof_id_type>(base_idx + vig*ncg + comp);
     }
 }
float libMesh::Tet4::embedding_matrix (const unsigned int i, const unsigned int j, const unsigned int k) const protected virtual
Matrix used to create the elements children.
Implements libMesh::Elem.
Definition at line 377 of file cell_tet4.C.
References libMesh::Tet::_diagonal_selection, _embedding_matrix, libMesh::Tet::choose_diagonal(), and libMesh::Tet::DIAG_02_13.
 {
   // Choose an optimal diagonal, if one has not already been selected
   this->choose_diagonal();
   // Permuted j and k indices
   unsigned int
     jp=j,
     kp=k;
   if ((i>3) && (this->_diagonal_selection!=DIAG_02_13))
     {
       // Just the enum value cast to an unsigned int...
       const unsigned ds = static_cast<unsigned int>(this->_diagonal_selection);
       // Permute j, k:
       // ds==1      ds==2
       // 0 -> 1     0 -> 2
       // 1 -> 2     1 -> 0
       // 2 -> 0     2 -> 1
       if (jp != 3)
         jp = (jp+ds)%3;
       if (kp != 3)
         kp = (kp+ds)%3;
     }
   // Debugging
   // libMesh::err << "Selected diagonal " << _diagonal_selection << std::endl;
   // libMesh::err << "j=" << j << std::endl;
   // libMesh::err << "k=" << k << std::endl;
   // libMesh::err << "jp=" << jp << std::endl;
   // libMesh::err << "kp=" << kp << std::endl;
   // Call embedding matrx with permuted indices
   return this->_embedding_matrix[i][jp][kp];
 }
virtual unsigned int libMesh::Tet::embedding_matrix_version () const inline virtual inherited
Tetrahedral elements permute the embedding matrix depending on which interior diagonal is used to subdivide into child elements. But we want to cache topology data based on that matrix. So we return a "version number" based on the diagonal selection.
Reimplemented from libMesh::Elem.
Definition at line 168 of file cell_tet.h.
References libMesh::Tet::choose_diagonal(), and libMesh::Tet::diagonal_selection().
   {
     this->choose_diagonal();
     return this->diagonal_selection();
   }
void libMesh::ReferenceCounter::enable_print_counter_info () static inherited
Methods to enable/disable the reference counter output from print_info()
Definition at line 101 of file reference_counter.C.
References libMesh::ReferenceCounter::_enable_print_counter.
Referenced by libMesh::ReferenceCounter::n_objects().
 {
   _enable_print_counter = true;
   return;
 }
void libMesh::ReferenceCounter::enable_print_counter_info () static inherited
Methods to enable/disable the reference counter output from print_info()
Definition at line 101 of file reference_counter.C.
References libMesh::ReferenceCounter::_enable_print_counter.
Referenced by libMesh::ReferenceCounter::n_objects().
 {
   _enable_print_counter = true;
   return;
 }
void libMesh::Elem::family_tree (std::vector< const Elem * > & family, const bool reset = true) const inherited
Fills the vector family with the children of this element, recursively. Calling this method on a twice-refined element will give you the element itself, its direct children, and their children, etc... When the optional parameter reset is true, the vector will be cleared before the element and its descendants are added.
The family tree only includes ancestor and active elements. To include subactive elements as well, use total_family_tree().
Definition at line 1674 of file elem.C.
References libMesh::Elem::active(), libMesh::Elem::child_ptr(), libMesh::Elem::family_tree(), libMesh::Elem::is_remote(), libMesh::libmesh_assert(), libMesh::Elem::n_children(), and libMesh::Elem::subactive().
Referenced by libMesh::Elem::family_tree(), and libMesh::MeshCommunication::gather_neighboring_elements().
 {
   // The "family tree" doesn't include subactive elements
   libmesh_assert(!this->subactive());
   // Clear the vector if the flag reset tells us to.
   if (reset)
     family.clear();
   // Add this element to the family tree.
   family.push_back(this);
   // Recurse into the elements children, if it has them.
   // Do not clear the vector any more.
   if (!this->active())
     for (unsigned int c=0; c<this->n_children(); c++)
       if (!this->child_ptr(c)->is_remote())
         this->child_ptr(c)->family_tree (family, false);
 }
void libMesh::Elem::family_tree_by_neighbor (std::vector< const Elem * > & family, const Elem * neighbor, const bool reset = true) const inherited
Same as the family_tree() member, but only adds elements which are next to neighbor.
Definition at line 1795 of file elem.C.
References libMesh::Elem::active(), libMesh::Elem::child_ptr(), libMesh::Elem::family_tree_by_neighbor(), libMesh::Elem::has_neighbor(), libMesh::libmesh_assert(), libMesh::Elem::n_children(), libMesh::remote_elem, and libMesh::Elem::subactive().
Referenced by libMesh::Elem::family_tree_by_neighbor().
 {
   // The "family tree" doesn't include subactive elements
   libmesh_assert(!this->subactive());
   // Clear the vector if the flag reset tells us to.
   if (reset)
     family.clear();
   // This only makes sense if we're already a neighbor
   libmesh_assert (this->has_neighbor(neighbor_in));
   // Add this element to the family tree.
   family.push_back(this);
   // Recurse into the elements children, if it's not active.
   // Do not clear the vector any more.
   if (!this->active())
     for (unsigned int c=0; c<this->n_children(); c++)
       {
         const Elem * current_child = this->child_ptr(c);
         if (current_child != remote_elem && current_child->has_neighbor(neighbor_in))
           current_child->family_tree_by_neighbor (family, neighbor_in, false);
       }
 }
void libMesh::Elem::family_tree_by_side (std::vector< const Elem * > & family, const unsigned int side, const bool reset = true) const inherited
Same as the family_tree() member, but only adds elements which are next to side.
Definition at line 1741 of file elem.C.
References libMesh::Elem::active(), libMesh::Elem::child_ptr(), libMesh::Elem::family_tree_by_side(), libMesh::Elem::is_child_on_side(), libMesh::Elem::is_remote(), libMesh::libmesh_assert(), libMesh::Elem::n_children(), libMesh::Elem::n_sides(), and libMesh::Elem::subactive().
Referenced by libMesh::Elem::family_tree_by_side(), and libMesh::Elem::make_links_to_me_local().
 {
   // The "family tree" doesn't include subactive elements
   libmesh_assert(!this->subactive());
   // Clear the vector if the flag reset tells us to.
   if (reset)
     family.clear();
   libmesh_assert_less (s, this->n_sides());
   // Add this element to the family tree.
   family.push_back(this);
   // Recurse into the elements children, if it has them.
   // Do not clear the vector any more.
   if (!this->active())
     for (unsigned int c=0; c<this->n_children(); c++)
       if (!this->child_ptr(c)->is_remote() && this->is_child_on_side(c, s))
         this->child_ptr(c)->family_tree_by_side (family, s, false);
 }
void libMesh::Elem::family_tree_by_subneighbor (std::vector< const Elem * > & family, const Elem * neighbor, const Elem * subneighbor, const bool reset = true) const inherited
Same as the family_tree() member, but only adds elements which are next to subneighbor. Only applicable when this->has_neighbor(neighbor) and neighbor->is_ancestor(subneighbor)
Definition at line 1852 of file elem.C.
References libMesh::Elem::active(), libMesh::Elem::child_ptr(), libMesh::Elem::family_tree_by_subneighbor(), libMesh::Elem::has_neighbor(), libMesh::Elem::is_ancestor_of(), libMesh::libmesh_assert(), libMesh::Elem::n_children(), libMesh::Elem::n_sides(), libMesh::Elem::neighbor_ptr(), libMesh::Elem::parent(), libMesh::remote_elem, and libMesh::Elem::subactive().
Referenced by libMesh::Elem::family_tree_by_subneighbor().
 {
   // The "family tree" doesn't include subactive elements
   libmesh_assert(!this->subactive());
   // Clear the vector if the flag reset tells us to.
   if (reset)
     family.clear();
   // To simplifly this function we need an existing neighbor
   libmesh_assert (neighbor_in);
   libmesh_assert_not_equal_to (neighbor_in, remote_elem);
   libmesh_assert (this->has_neighbor(neighbor_in));
   // This only makes sense if subneighbor descends from neighbor
   libmesh_assert (subneighbor);
   libmesh_assert_not_equal_to (subneighbor, remote_elem);
   libmesh_assert (neighbor_in->is_ancestor_of(subneighbor));
   // Add this element to the family tree if applicable.
   if (neighbor_in == subneighbor)
     family.push_back(this);
   // Recurse into the elements children, if it's not active.
   // Do not clear the vector any more.
   if (!this->active())
     for (unsigned int c=0; c != this->n_children(); ++c)
       {
         const Elem * current_child = this->child_ptr(c);
         if (current_child != remote_elem)
           for (unsigned int s=0; s != current_child->n_sides(); ++s)
             {
               const Elem * child_neigh = current_child->neighbor_ptr(s);
               if (child_neigh &&
                   (child_neigh == neighbor_in ||
                    (child_neigh->parent() == neighbor_in &&
                     child_neigh->is_ancestor_of(subneighbor))))
                 current_child->family_tree_by_subneighbor (family, child_neigh,
                                                            subneighbor, false);
             }
       }
 }
void libMesh::Elem::find_edge_neighbors (const Point & p1, const Point & p2, std::set< const Elem * > & neighbor_set) const inherited
This function finds all active elements in the same manifold as this element which touch the current active element along the whole edge defined by the two points p1 and p2.
Definition at line 758 of file elem.C.
References libMesh::Elem::contains_point(), end, libMesh::Elem::find_point_neighbors(), and libMesh::libmesh_assert().
Referenced by libMesh::MeshRefinement::enforce_mismatch_limit_prior_to_refinement().
 {
   // Simple but perhaps suboptimal code: find elements containing the
   // first point, then winnow this set down by removing elements which
   // don't also contain the second point
   libmesh_assert(this->contains_point(p2));
   this->find_point_neighbors(p1, neighbor_set);
   std::set<const Elem *>::iterator        it = neighbor_set.begin();
   const std::set<const Elem *>::iterator end = neighbor_set.end();
   while (it != end)
     {
       std::set<const Elem *>::iterator current = it++;
       const Elem * elem = *current;
       // This won't invalidate iterator it, because it is already
       // pointing to the next element
       if (!elem->contains_point(p2))
         neighbor_set.erase(current);
     }
 }
void libMesh::Elem::find_edge_neighbors (std::set< const Elem * > & neighbor_set) const inherited
This function finds all active elements in the same manifold as this element which touch the current active element along any edge (more precisely, at at least two points).
In this case, elements are included even if they do not touch a whole edge of this element.
Definition at line 786 of file elem.C.
References libMesh::Elem::active(), libMesh::Elem::active_family_tree_by_neighbor(), libMesh::Elem::contains_edge_of(), end, libMesh::Elem::n_sides(), libMesh::Elem::neighbor_ptr(), and libMesh::remote_elem.
 {
   neighbor_set.clear();
   neighbor_set.insert(this);
   std::set<const Elem *> untested_set, next_untested_set;
   untested_set.insert(this);
   while (!untested_set.empty())
     {
       // Loop over all the elements in the patch that haven't already
       // been tested
       std::set<const Elem *>::const_iterator       it  = untested_set.begin();
       const std::set<const Elem *>::const_iterator end = untested_set.end();
       for (; it != end; ++it)
         {
           const Elem * elem = *it;
           for (unsigned int s=0; s<elem->n_sides(); s++)
             {
               const Elem * current_neighbor = elem->neighbor_ptr(s);
               if (current_neighbor &&
                   current_neighbor != remote_elem)    // we have a real neighbor on this side
                 {
                   if (current_neighbor->active())                // ... if it is active
                     {
                       if (this->contains_edge_of(current_neighbor) // ... and touches us
                           || current_neighbor->contains_edge_of(this))
{
                           // Make sure we'll test it
                           if (!neighbor_set.count(current_neighbor))
                             next_untested_set.insert (current_neighbor);
                           // And add it
                           neighbor_set.insert (current_neighbor);
                         }
                     }
 #ifdef LIBMESH_ENABLE_AMR
                   else                                 // ... the neighbor is *not* active,
                     {                                  // ... so add *all* neighboring
                                                        // active children
                       std::vector<const Elem *> active_neighbor_children;
                       current_neighbor->active_family_tree_by_neighbor
                         (active_neighbor_children, elem);
                       std::vector<const Elem *>::const_iterator
                         child_it = active_neighbor_children.begin();
                       const std::vector<const Elem *>::const_iterator
                         child_end = active_neighbor_children.end();
                       for (; child_it != child_end; ++child_it)
{
                           const Elem * current_child = *child_it;
                           if (this->contains_edge_of(*child_it) ||
                               (*child_it)->contains_edge_of(this))
{
                               // Make sure we'll test it
                               if (!neighbor_set.count(current_child))
                                 next_untested_set.insert (current_child);
                               neighbor_set.insert (current_child);
                             }
                         }
                     }
 #endif // #ifdef LIBMESH_ENABLE_AMR
                 }
             }
         }
       untested_set.swap(next_untested_set);
       next_untested_set.clear();
     }
 }
void libMesh::Elem::find_interior_neighbors (std::set< const Elem * > & neighbor_set) const inherited
This function finds all active elements (not including this one) in the parent manifold of this element whose intersection with this element has non-zero measure.
Definition at line 861 of file elem.C.
References libMesh::Elem::active(), libMesh::Elem::child(), libMesh::Elem::child_ptr(), libMesh::Elem::contains_point(), libMesh::Elem::contains_vertex_of(), libMesh::Elem::dim(), end, libMesh::Elem::find_point_neighbors(), libMesh::Elem::interior_parent(), libMesh::Elem::level(), libMesh::libmesh_assert(), libMesh::Elem::n_children(), libMesh::Elem::n_nodes(), libMesh::Elem::point(), and libMesh::Elem::subactive().
Referenced by libMesh::ParmetisPartitioner::build_graph(), libMesh::MeshRefinement::limit_overrefined_boundary(), libMesh::MeshRefinement::limit_underrefined_boundary(), and libMesh::MetisPartitioner::partition_range().
 {
   neighbor_set.clear();
   if ((this->dim() >= LIBMESH_DIM) ||
       !this->interior_parent())
     return;
   const Elem * ip = this->interior_parent();
   libmesh_assert (ip->contains_vertex_of(this) ||
                   this->contains_vertex_of(ip));
   libmesh_assert (!ip->subactive());
 #ifdef LIBMESH_ENABLE_AMR
   while (!ip->active()) // only possible with AMR, be careful because
     {                   // ip->child_ptr(c) is only good with AMR.
       for (unsigned int c = 0; c != ip->n_children(); ++c)
         {
           const Elem * child = ip->child_ptr(c);
           if (child->contains_vertex_of(this) ||
               this->contains_vertex_of(child))
             {
               ip = child;
               break;
             }
         }
     }
 #endif
   this->find_point_neighbors(neighbor_set, ip);
   // Now we have all point neighbors from the interior manifold, but
   // we need to weed out any neighbors that *only* intersect us at one
   // point (or at one edge, if we're a 1-D element in 3D).
   //
   // The refinement hierarchy helps us here: if the interior element
   // has a lower or equal refinement level then we can discard it iff
   // it doesn't contain all our vertices.  If it has a higher
   // refinement level then we can discard it iff we don't contain at
   // least dim()+1 of its vertices
   std::set<const Elem *>::iterator        it = neighbor_set.begin();
   const std::set<const Elem *>::iterator end = neighbor_set.end();
   while (it != end)
     {
       std::set<const Elem *>::iterator current = it++;
       const Elem * elem = *current;
       // This won't invalidate iterator it, because it is already
       // pointing to the next element
       if (elem->level() > this->level())
         {
           unsigned int vertices_contained = 0;
           for (unsigned int p=0; p < elem->n_nodes(); ++p)
             if (this->contains_point(elem->point(p)))
               vertices_contained++;
           if (vertices_contained <= this->dim())
             {
               neighbor_set.erase(current);
               continue;
             }
         }
       else
         {
           for (unsigned int p=0; p < this->n_nodes(); ++p)
             {
               if (!elem->contains_point(this->point(p)))
                 {
                   neighbor_set.erase(current);
                   break;
                 }
             }
         }
     }
 }
void libMesh::Elem::find_point_neighbors (const Point & p, std::set< const Elem * > & neighbor_set) const inherited
This function finds all active elements (including this one) which are in the same manifold as this element and which touch the current active element at the specified point, which should be a point in the current element.
Elements which are not "in the same manifold" (e.g. the interior_parent of a boundary element) will not be found with this method.
Elements which overlap the specified point but which are only connected to the current element via elements which do not overlap that point (e.g. in a folded or tangled mesh) are not considered to "touch" the current element and will not be found with this method.
Definition at line 591 of file elem.C.
References libMesh::Elem::active(), libMesh::Elem::active_family_tree_by_neighbor(), libMesh::Elem::contains_point(), end, libMesh::libmesh_assert(), libMesh::Elem::n_sides(), libMesh::Elem::neighbor_ptr(), and libMesh::remote_elem.
Referenced by libMesh::MeshRefinement::enforce_mismatch_limit_prior_to_refinement(), libMesh::AdjointRefinementEstimator::estimate_error(), libMesh::Elem::find_edge_neighbors(), libMesh::MeshFunction::find_element(), libMesh::MeshFunction::find_elements(), libMesh::Elem::find_interior_neighbors(), libMesh::Patch::find_point_neighbors(), libMesh::Elem::find_point_neighbors(), libMesh::Elem::is_semilocal(), and libMesh::PointNeighborCoupling::operator()().
 {
   libmesh_assert(this->contains_point(p));
   libmesh_assert(this->active());
   neighbor_set.clear();
   neighbor_set.insert(this);
   std::set<const Elem *> untested_set, next_untested_set;
   untested_set.insert(this);
   while (!untested_set.empty())
     {
       // Loop over all the elements in the patch that haven't already
       // been tested
       std::set<const Elem *>::const_iterator       it  = untested_set.begin();
       const std::set<const Elem *>::const_iterator end = untested_set.end();
       for (; it != end; ++it)
         {
           const Elem * elem = *it;
           for (unsigned int s=0; s<elem->n_sides(); s++)
             {
               const Elem * current_neighbor = elem->neighbor_ptr(s);
               if (current_neighbor &&
                   current_neighbor != remote_elem)    // we have a real neighbor on this side
                 {
                   if (current_neighbor->active())                // ... if it is active
                     {
                       if (current_neighbor->contains_point(p))   // ... and touches p
{
                           // Make sure we'll test it
                           if (!neighbor_set.count(current_neighbor))
                             next_untested_set.insert (current_neighbor);
                           // And add it
                           neighbor_set.insert (current_neighbor);
                         }
                     }
 #ifdef LIBMESH_ENABLE_AMR
                   else                                 // ... the neighbor is *not* active,
                     {                                  // ... so add *all* neighboring
                                                        // active children that touch p
                       std::vector<const Elem *> active_neighbor_children;
                       current_neighbor->active_family_tree_by_neighbor
                         (active_neighbor_children, elem);
                       std::vector<const Elem *>::const_iterator
                         child_it = active_neighbor_children.begin();
                       const std::vector<const Elem *>::const_iterator
                         child_end = active_neighbor_children.end();
                       for (; child_it != child_end; ++child_it)
{
                           const Elem * current_child = *child_it;
                           if (current_child->contains_point(p))
{
                               // Make sure we'll test it
                               if (!neighbor_set.count(current_child))
                                 next_untested_set.insert (current_child);
                               neighbor_set.insert (current_child);
                             }
                         }
                     }
 #endif // #ifdef LIBMESH_ENABLE_AMR
                 }
             }
         }
       untested_set.swap(next_untested_set);
       next_untested_set.clear();
     }
 }
void libMesh::Elem::find_point_neighbors (std::set< const Elem * > & neighbor_set) const inherited
This function finds all active elements (including this one) in the same manifold as this element which touch this active element at any point.
Definition at line 669 of file elem.C.
References libMesh::Elem::find_point_neighbors().
 {
   this->find_point_neighbors(neighbor_set, this);
 }
void libMesh::Elem::find_point_neighbors (std::set< const Elem * > & neighbor_set, const Elem * start_elem) const inherited
This function finds all active elements (including this one) in the same manifold as start_elem (which must be active and must touch this element) which touch this element at any point.
Definition at line 676 of file elem.C.
References libMesh::Elem::active(), libMesh::Elem::active_family_tree_by_neighbor(), libMesh::Elem::contains_vertex_of(), end, libMesh::libmesh_assert(), libMesh::Elem::n_sides(), libMesh::Elem::neighbor_ptr(), and libMesh::remote_elem.
 {
   libmesh_assert(start_elem);
   libmesh_assert(start_elem->active());
   libmesh_assert(start_elem->contains_vertex_of(this) ||
                  this->contains_vertex_of(start_elem));
   neighbor_set.clear();
   neighbor_set.insert(start_elem);
   std::set<const Elem *> untested_set, next_untested_set;
   untested_set.insert(start_elem);
   while (!untested_set.empty())
     {
       // Loop over all the elements in the patch that haven't already
       // been tested
       std::set<const Elem *>::const_iterator       it  = untested_set.begin();
       const std::set<const Elem *>::const_iterator end = untested_set.end();
       for (; it != end; ++it)
         {
           const Elem * elem = *it;
           for (unsigned int s=0; s<elem->n_sides(); s++)
             {
               const Elem * current_neighbor = elem->neighbor_ptr(s);
               if (current_neighbor &&
                   current_neighbor != remote_elem)    // we have a real neighbor on this side
                 {
                   if (current_neighbor->active())                // ... if it is active
                     {
                       if (this->contains_vertex_of(current_neighbor) // ... and touches us
                           || current_neighbor->contains_vertex_of(this))
{
                           // Make sure we'll test it
                           if (!neighbor_set.count(current_neighbor))
                             next_untested_set.insert (current_neighbor);
                           // And add it
                           neighbor_set.insert (current_neighbor);
                         }
                     }
 #ifdef LIBMESH_ENABLE_AMR
                   else                                 // ... the neighbor is *not* active,
                     {                                  // ... so add *all* neighboring
                                                        // active children
                       std::vector<const Elem *> active_neighbor_children;
                       current_neighbor->active_family_tree_by_neighbor
                         (active_neighbor_children, elem);
                       std::vector<const Elem *>::const_iterator
                         child_it = active_neighbor_children.begin();
                       const std::vector<const Elem *>::const_iterator
                         child_end = active_neighbor_children.end();
                       for (; child_it != child_end; ++child_it)
{
                           const Elem * current_child = *child_it;
                           if (this->contains_vertex_of(current_child) ||
                               (current_child)->contains_vertex_of(this))
{
                               // Make sure we'll test it
                               if (!neighbor_set.count(current_child))
                                 next_untested_set.insert (current_child);
                               neighbor_set.insert (current_child);
                             }
                         }
                     }
 #endif // #ifdef LIBMESH_ENABLE_AMR
                 }
             }
         }
       untested_set.swap(next_untested_set);
       next_untested_set.clear();
     }
 }
ElemType libMesh::Elem::first_order_equivalent_type (const ElemType et) static inherited
Returns
The element type of the associated first-order element, or INVALID_ELEM for first-order or other elements that cannot be converted into lower order equivalents.
For example, when this is a TET10, then TET4 is returned.
Definition at line 2746 of file elem.C.
References libMesh::EDGE2, libMesh::EDGE3, libMesh::EDGE4, libMesh::HEX20, libMesh::HEX27, libMesh::HEX8, libMesh::INFHEX16, libMesh::INFHEX18, libMesh::INFHEX8, libMesh::INFPRISM12, libMesh::INFPRISM6, libMesh::INFQUAD4, libMesh::INFQUAD6, libMesh::INVALID_ELEM, libMesh::PRISM15, libMesh::PRISM18, libMesh::PRISM6, libMesh::PYRAMID13, libMesh::PYRAMID14, libMesh::PYRAMID5, libMesh::QUAD4, libMesh::QUAD8, libMesh::QUAD9, libMesh::QUADSHELL4, libMesh::TET10, libMesh::TET4, libMesh::TRI3, libMesh::TRI6, and libMesh::TRISHELL3.
Referenced by libMesh::UnstructuredMesh::all_first_order(), libMesh::Elem::is_linear(), and libMesh::GMVIO::write_ascii_old_impl().
 {
   switch (et)
     {
     case EDGE2:
     case EDGE3:
     case EDGE4:
       return EDGE2;
     case TRI3:
     case TRI6:
       return TRI3;
     case TRISHELL3:
       return TRISHELL3;
     case QUAD4:
     case QUAD8:
     case QUAD9:
       return QUAD4;
     case QUADSHELL4:
       return QUADSHELL4;
     case TET4:
     case TET10:
       return TET4;
     case HEX8:
     case HEX27:
     case HEX20:
       return HEX8;
     case PRISM6:
     case PRISM15:
     case PRISM18:
       return PRISM6;
     case PYRAMID5:
     case PYRAMID13:
     case PYRAMID14:
       return PYRAMID5;
 #ifdef LIBMESH_ENABLE_INFINITE_ELEMENTS
     case INFQUAD4:
     case INFQUAD6:
       return INFQUAD4;
     case INFHEX8:
     case INFHEX16:
     case INFHEX18:
       return INFHEX8;
     case INFPRISM6:
     case INFPRISM12:
       return INFPRISM6;
 #endif
     default:
       // unknown element
       return INVALID_ELEM;
     }
 }
std::string libMesh::ReferenceCounter::get_info () static inherited
Gets a string containing the reference information.
Definition at line 47 of file reference_counter.C.
References libMesh::ReferenceCounter::_counts, and libMesh::Quality::name().
Referenced by libMesh::ReferenceCounter::print_info().
 {
 #if defined(LIBMESH_ENABLE_REFERENCE_COUNTING) && defined(DEBUG)
   std::ostringstream oss;
   oss << '\n'
       << " ---------------------------------------------------------------------------- \n"
       << "| Reference count information                                                |\n"
       << " ---------------------------------------------------------------------------- \n";
   for (Counts::iterator it = _counts.begin();
        it != _counts.end(); ++it)
     {
       const std::string name(it->first);
       const unsigned int creations    = it->second.first;
       const unsigned int destructions = it->second.second;
       oss << "| " << name << " reference count information:\n"
           << "|  Creations:    " << creations    << '\n'
           << "|  Destructions: " << destructions << '\n';
     }
   oss << " ---------------------------------------------------------------------------- \n";
   return oss.str();
 #else
   return "";
 #endif
 }
std::string libMesh::ReferenceCounter::get_info () static inherited
Gets a string containing the reference information.
Definition at line 47 of file reference_counter.C.
References libMesh::ReferenceCounter::_counts, and libMesh::Quality::name().
Referenced by libMesh::ReferenceCounter::print_info().
 {
 #if defined(LIBMESH_ENABLE_REFERENCE_COUNTING) && defined(DEBUG)
   std::ostringstream oss;
   oss << '\n'
       << " ---------------------------------------------------------------------------- \n"
       << "| Reference count information                                                |\n"
       << " ---------------------------------------------------------------------------- \n";
   for (Counts::iterator it = _counts.begin();
        it != _counts.end(); ++it)
     {
       const std::string name(it->first);
       const unsigned int creations    = it->second.first;
       const unsigned int destructions = it->second.second;
       oss << "| " << name << " reference count information:\n"
           << "|  Creations:    " << creations    << '\n'
           << "|  Destructions: " << destructions << '\n';
     }
   oss << " ---------------------------------------------------------------------------- \n";
   return oss.str();
 #else
   return "";
 #endif
 }
std::string libMesh::Elem::get_info () const inherited
Prints relevant information about the element to a string.
Definition at line 2617 of file elem.C.
References libMesh::Elem::active(), libMesh::Elem::ancestor(), libMesh::Elem::dim(), libMesh::DofObject::dof_number(), libMesh::Utility::enum_to_string(), libMesh::Elem::has_children(), libMesh::Elem::hmax(), libMesh::Elem::hmin(), libMesh::DofObject::id(), libMesh::Elem::infinite(), libMesh::Elem::level(), libMesh::DofObject::n_comp(), libMesh::Elem::n_nodes(), libMesh::Elem::n_sides(), libMesh::DofObject::n_systems(), libMesh::DofObject::n_vars(), libMesh::Elem::neighbor_ptr(), libMesh::Elem::node_ref(), libMesh::Elem::origin(), libMesh::Elem::p_level(), libMesh::Elem::p_refinement_flag(), libMesh::Elem::parent(), libMesh::DofObject::processor_id(), libMesh::Elem::refinement_flag(), libMesh::Elem::subactive(), libMesh::Elem::type(), libMesh::DofObject::unique_id(), libMesh::DofObject::valid_id(), libMesh::DofObject::valid_unique_id(), and libMesh::Elem::volume().
Referenced by libMesh::Elem::is_linear(), and libMesh::Elem::print_info().
 {
   std::ostringstream oss;
   oss << "  Elem Information"                                      << '\n'
       << "   id()=";
   if (this->valid_id())
     oss << this->id();
   else
     oss << "invalid";
 #ifdef LIBMESH_ENABLE_UNIQUE_ID
   oss << ", unique_id()=";
   if (this->valid_unique_id())
     oss << this->unique_id();
   else
     oss << "invalid";
 #endif
   oss << ", processor_id()=" << this->processor_id()               << '\n';
   oss << "   type()="    << Utility::enum_to_string(this->type())  << '\n'
       << "   dim()="     << this->dim()                            << '\n'
       << "   n_nodes()=" << this->n_nodes()                        << '\n';
   for (unsigned int n=0; n != this->n_nodes(); ++n)
     oss << "    " << n << this->node_ref(n);
   oss << "   n_sides()=" << this->n_sides()                        << '\n';
   for (unsigned int s=0; s != this->n_sides(); ++s)
     {
       oss << "    neighbor(" << s << ")=";
       if (this->neighbor_ptr(s))
         oss << this->neighbor_ptr(s)->id() << '\n';
       else
         oss << "NULL\n";
     }
   oss << "   hmin()=" << this->hmin()
       << ", hmax()=" << this->hmax()                               << '\n'
       << "   volume()=" << this->volume()                          << '\n'
       << "   active()=" << this->active()
       << ", ancestor()=" << this->ancestor()
       << ", subactive()=" << this->subactive()
       << ", has_children()=" << this->has_children()               << '\n'
       << "   parent()=";
   if (this->parent())
     oss << this->parent()->id() << '\n';
   else
     oss << "NULL\n";
   oss << "   level()=" << this->level()
       << ", p_level()=" << this->p_level()                         << '\n'
 #ifdef LIBMESH_ENABLE_AMR
       << "   refinement_flag()=" << Utility::enum_to_string(this->refinement_flag())        << '\n'
       << "   p_refinement_flag()=" << Utility::enum_to_string(this->p_refinement_flag())    << '\n'
 #endif
 #ifdef LIBMESH_ENABLE_INFINITE_ELEMENTS
       << "   infinite()=" << this->infinite()    << '\n';
   if (this->infinite())
     oss << "   origin()=" << this->origin()    << '\n'
 #endif
       ;
   oss << "   DoFs=";
   for (unsigned int s=0; s != this->n_systems(); ++s)
     for (unsigned int v=0; v != this->n_vars(s); ++v)
       for (unsigned int c=0; c != this->n_comp(s,v); ++c)
         oss << '(' << s << '/' << v << '/' << this->dof_number(s,v,c) << ") ";
   return oss.str();
 }
Node * libMesh::Elem::get_node (const unsigned int i) const inline inherited
Returns
The pointer to local Node i.
Deprecated:
Use the less ambiguously named node_ptr() instead.
Definition at line 1762 of file elem.h.
References libMesh::Elem::node_ptr().
 {
   // This const function has incorrectly returned a non-const pointer
   // for years.  Now that it is reimplemented in terms of the new
   // interface which does return a const pointer, we need to use a
   // const_cast to mimic the old (incorrect) behavior.  This function
   // is now deprecated and eventually will be removed entirely,
   // obviating the need for this ugly cast.
   libmesh_deprecated();
   return const_cast<Node *>(this->node_ptr(i));
 }
unsigned int libMesh::Elem::get_node_index (const Node * node_ptr) const inline inherited
Returns
The local index for the Node pointer node_ptr, or invalid_id if node_ptr is not a local node.
Definition at line 1777 of file elem.h.
References libMesh::Elem::_nodes, libMesh::invalid_uint, and libMesh::Elem::n_nodes().
Referenced by libMesh::ElemCutter::find_intersection_points().
 {
   for (unsigned int n=0; n != this->n_nodes(); ++n)
     if (this->_nodes[n] == node_ptr)
       return n;
   return libMesh::invalid_uint;
 }
const Node *const * libMesh::Elem::get_nodes () const inline inherited
Returns
A pointer to an array of local node pointers.
Definition at line 1716 of file elem.h.
References libMesh::Elem::_nodes.
Referenced by libMesh::DofMap::dof_indices().
 {
   return _nodes;
 }
void libMesh::Elem::hack_p_level (const unsigned int p) inline inherited
Sets the value of the p-refinement level for the element without altering the p-level of its ancestors
Definition at line 2390 of file elem.h.
References libMesh::Elem::_p_level, libMesh::Elem::JUST_REFINED, and libMesh::Elem::p_refinement_flag().
Referenced by libMesh::CheckpointIO::read_connectivity(), libMesh::XdrIO::read_serialized_connectivity(), and libMesh::Parallel::Packing< Elem * >::unpack().
 {
   if (p == 0)
     libmesh_assert_not_equal_to
       (this->p_refinement_flag(), Elem::JUST_REFINED);
   _p_level = cast_int<unsigned char>(p);
 }
virtual bool libMesh::Tet4::has_affine_map () const inline virtual
Returns
true if the element map is definitely affine within numerical tolerances.
Reimplemented from libMesh::Elem.
Definition at line 118 of file cell_tet4.h.
 { return true; }
bool libMesh::Elem::has_ancestor_children () const inline inherited
Returns
true if the element has any descendants other than its immediate children, false otherwise, or if AMR is disabled.
Definition at line 2105 of file elem.h.
References libMesh::Elem::_children, libMesh::Elem::child_ptr(), libMesh::Elem::has_children(), libmesh_nullptr, and libMesh::Elem::n_children().
Referenced by libMesh::Elem::is_linear().
 {
 #ifdef LIBMESH_ENABLE_AMR
   if (_children == libmesh_nullptr)
     return false;
   else
     for (unsigned int c=0; c != this->n_children(); c++)
       if (this->child_ptr(c)->has_children())
         return true;
 #endif
   return false;
 }
bool libMesh::Elem::has_children () const inline inherited
Returns
true if the element has any children (active or not), false otherwise, or if AMR is disabled.
Definition at line 2091 of file elem.h.
References libMesh::Elem::_children, and libmesh_nullptr.
Referenced by libMesh::Elem::add_child(), libMesh::UnstructuredMesh::all_first_order(), libMesh::Elem::ancestor(), libMesh::connect_children(), libMesh::connect_families(), libMesh::UnstructuredMesh::copy_nodes_and_elements(), libMesh::TopologyMap::fill(), libMesh::UnstructuredMesh::find_neighbors(), libMesh::MeshRefinement::flag_elements_by_nelem_target(), libMesh::Elem::get_info(), libMesh::Elem::has_ancestor_children(), libMesh::Elem::is_linear(), libMesh::MeshTools::libmesh_assert_no_links_to_elem(), libMesh::MeshTools::libmesh_assert_topology_consistent_procids< Elem >(), libMesh::MeshTools::libmesh_assert_valid_refinement_tree(), libMesh::MeshTools::libmesh_assert_valid_remote_elems(), libMesh::MeshRefinement::make_coarsening_compatible(), libMesh::Elem::make_links_to_me_local(), libMesh::Elem::make_links_to_me_remote(), libMesh::MeshRefinement::make_refinement_compatible(), libMesh::FEMSystem::mesh_position_set(), libMesh::Parallel::Packing< const Elem * >::pack(), libMesh::Elem::remove_links_to_me(), libMesh::Elem::replace_child(), libMesh::Elem::set_child(), libMesh::Elem::subactive(), libMesh::Parallel::sync_element_data_by_parent_id(), libMesh::Elem::total_family_tree(), libMesh::Elem::total_family_tree_by_neighbor(), libMesh::Elem::total_family_tree_by_subneighbor(), libMesh::Parallel::Packing< Elem * >::unpack(), and libMesh::Elem::which_child_am_i().
 {
 #ifdef LIBMESH_ENABLE_AMR
   if (_children == libmesh_nullptr)
     return false;
   else
     return true;
 #else
   return false;
 #endif
 }
bool libMesh::DofObject::has_dofs (const unsigned int s = libMesh::invalid_uint) const inline inherited
Returns
true if any system has variables which have been assigned, false otherwise.
Definition at line 847 of file dof_object.h.
References libMesh::invalid_uint, libMesh::DofObject::n_systems(), and libMesh::DofObject::n_vars().
Referenced by libMesh::MeshTools::libmesh_assert_old_dof_objects(), libMesh::DofMap::old_dof_indices(), libMesh::DofMap::reinit(), and libMesh::DofObject::set_id().
 {
   if (sys == libMesh::invalid_uint)
     {
       for (unsigned int s=0; s<this->n_systems(); s++)
         if (this->n_vars(s))
           return true;
     }
   else
     {
       libmesh_assert_less (sys, this->n_systems());
       if (this->n_vars(sys))
         return true;
     }
   return false;
 }
bool libMesh::Elem::has_neighbor (const Elem * elem) const inline inherited
Returns
true if the element elem in question is a neighbor of this element, false otherwise.
Definition at line 1856 of file elem.h.
References libMesh::Elem::n_neighbors(), and libMesh::Elem::neighbor_ptr().
Referenced by libMesh::Elem::active_family_tree_by_neighbor(), libMesh::Elem::family_tree_by_neighbor(), libMesh::Elem::family_tree_by_subneighbor(), libMesh::Elem::has_topological_neighbor(), libMesh::MeshRefinement::has_topological_neighbor(), libMesh::Elem::make_links_to_me_remote(), libMesh::Elem::min_new_p_level_by_neighbor(), libMesh::Elem::min_p_level_by_neighbor(), libMesh::Elem::on_boundary(), libMesh::Elem::remove_links_to_me(), libMesh::Elem::total_family_tree_by_neighbor(), and libMesh::Elem::total_family_tree_by_subneighbor().
 {
   for (unsigned int n=0; n<this->n_neighbors(); n++)
     if (this->neighbor_ptr(n) == elem)
       return true;
   return false;
 }
bool libMesh::Elem::has_topological_neighbor (const Elem * elem, const MeshBase & mesh, const PointLocatorBase & point_locator, const PeriodicBoundaries * pb) const inherited
Returns
true if the element elem in question is a neighbor or topological neighbor of this element, false otherwise.
Definition at line 1094 of file elem.C.
References libMesh::Elem::has_neighbor(), libMesh::Elem::n_neighbors(), and libMesh::Elem::topological_neighbor().
Referenced by libMesh::Elem::active_family_tree_by_topological_neighbor(), and libMesh::MeshRefinement::has_topological_neighbor().
 {
   // First see if this is a normal "interior" neighbor
   if (has_neighbor(elem))
     return true;
   for (unsigned int n=0; n<this->n_neighbors(); n++)
     if (this->topological_neighbor(n, mesh, point_locator, pb))
       return true;
   return false;
 }
Real libMesh::Elem::hmax () const virtual inherited
Returns
The maximum vertex separation for the element.
Definition at line 466 of file elem.C.
References std::max(), libMesh::Elem::n_vertices(), libMesh::TypeVector< T >::norm_sq(), libMesh::Elem::point(), and libMesh::Real.
Referenced by libMesh::DiscontinuityMeasure::boundary_side_integration(), libMesh::KellyErrorEstimator::boundary_side_integration(), libMesh::OldSolutionValue< Output, point_output >::check_old_context(), libMesh::Elem::get_info(), libMesh::LaplacianErrorEstimator::internal_side_integration(), libMesh::DiscontinuityMeasure::internal_side_integration(), libMesh::KellyErrorEstimator::internal_side_integration(), libMesh::Elem::is_vertex_on_child(), libMesh::PointLocatorBase::locate_node(), and libMesh::Elem::point_test().
 {
   Real h_max=0;
   for (unsigned int n_outer=0; n_outer<this->n_vertices(); n_outer++)
     for (unsigned int n_inner=n_outer+1; n_inner<this->n_vertices(); n_inner++)
       {
         const Point diff = (this->point(n_outer) - this->point(n_inner));
         h_max = std::max(h_max, diff.norm_sq());
       }
   return std::sqrt(h_max);
 }
Real libMesh::Elem::hmin () const virtual inherited
Returns
The minimum vertex separation for the element.
Definition at line 449 of file elem.C.
References std::max(), std::min(), libMesh::Elem::n_vertices(), libMesh::TypeVector< T >::norm_sq(), libMesh::Elem::point(), and libMesh::Real.
Referenced by libMesh::FEGenericBase< OutputType >::compute_periodic_constraints(), libMesh::UnstructuredMesh::find_neighbors(), libMesh::Elem::get_info(), libMesh::BoundaryInfo::get_side_and_node_maps(), libMesh::Elem::is_vertex_on_child(), libMesh::FEMSystem::numerical_jacobian(), libMesh::GenericProjector< FFunctor, GFunctor, FValue, ProjectionAction >::operator()(), and libMesh::ReplicatedMesh::stitching_helper().
 {
   Real h_min=std::numeric_limits<Real>::max();
   for (unsigned int n_outer=0; n_outer<this->n_vertices(); n_outer++)
     for (unsigned int n_inner=n_outer+1; n_inner<this->n_vertices(); n_inner++)
       {
         const Point diff = (this->point(n_outer) - this->point(n_inner));
         h_min = std::min(h_min, diff.norm_sq());
       }
   return std::sqrt(h_min);
 }
dof_id_type libMesh::DofObject::id () const inline inherited
Returns
The id for this DofObject
Definition at line 624 of file dof_object.h.
References libMesh::DofObject::_id, libMesh::libmesh_assert(), and libMesh::DofObject::valid_id().
Referenced by libMesh::UniformRefinementEstimator::_estimate_error(), libMesh::BoundaryInfo::_find_id_maps(), libMesh::MeshTools::Subdivision::add_boundary_ghosts(), libMesh::ReplicatedMesh::add_elem(), libMesh::DistributedMesh::add_elem(), libMesh::BoundaryInfo::add_elements(), libMesh::TopologyMap::add_node(), libMesh::ReplicatedMesh::add_node(), libMesh::DistributedMesh::add_node(), libMesh::DistributedMesh::add_point(), libMesh::UnstructuredMesh::all_first_order(), libMesh::UnstructuredMesh::all_second_order(), libMesh::MeshTools::Subdivision::all_subdivision(), libMesh::MeshTools::Modification::all_tri(), libMesh::DofMap::allgather_recursive_constraints(), libMesh::ParmetisPartitioner::assign_partitioning(), libMesh::MeshTools::Generation::build_delaunay_square(), libMesh::Nemesis_IO_Helper::build_element_and_node_maps(), libMesh::MeshTools::Generation::build_extrusion(), libMesh::ParmetisPartitioner::build_graph(), libMesh::InfElemBuilder::build_inf_elem(), libMesh::BoundaryInfo::build_node_list_from_side_list(), libMesh::VTKIO::cells_to_vtk(), libMesh::Nemesis_IO_Helper::compute_internal_and_border_elems_and_internal_nodes(), libMesh::FEGenericBase< OutputType >::compute_periodic_constraints(), libMesh::FEMap::compute_single_point_map(), libMesh::UnstructuredMesh::copy_nodes_and_elements(), libMesh::MeshTools::correct_node_proc_ids(), libMesh::MeshRefinement::create_parent_error_vector(), libMesh::UnstructuredMesh::create_submesh(), libMesh::ReplicatedMesh::delete_elem(), libMesh::DistributedMesh::delete_elem(), libMesh::ReplicatedMesh::delete_node(), libMesh::DistributedMesh::delete_node(), libMesh::MeshBase::detect_interior_parents(), libMesh::UNVIO::elements_out(), libMesh::JumpErrorEstimator::estimate_error(), libMesh::AdjointRefinementEstimator::estimate_error(), libMesh::ExactErrorEstimator::estimate_error(), libMesh::UnstructuredMesh::find_neighbors(), libMesh::MeshTools::find_nodal_neighbors(), libMesh::MeshRefinement::flag_elements_by_elem_fraction(), libMesh::MeshRefinement::flag_elements_by_error_fraction(), libMesh::MeshRefinement::flag_elements_by_error_tolerance(), libMesh::MeshRefinement::flag_elements_by_mean_stddev(), libMesh::MeshTools::Modification::flatten(), libMesh::Node::get_info(), libMesh::Elem::get_info(), libMesh::DofMap::get_local_constraints(), libMesh::BoundaryInfo::get_side_and_node_maps(), libMesh::EquationSystems::get_solution(), libMesh::LaplaceMeshSmoother::init(), libMesh::ParmetisPartitioner::initialize(), libMesh::ExodusII_IO_Helper::initialize(), libMesh::TreeNode< N >::insert(), libMesh::ReplicatedMesh::insert_elem(), libMesh::DistributedMesh::insert_elem(), libMesh::ReplicatedMesh::insert_node(), libMesh::FE< Dim, T >::inverse_map(), libMesh::MeshTools::libmesh_assert_parallel_consistent_procids< Node >(), libMesh::MeshTools::libmesh_assert_topology_consistent_procids< Node >(), libMesh::MeshTools::libmesh_assert_valid_amr_elem_ids(), libMesh::MeshTools::libmesh_assert_valid_elem_ids(), libMesh::MeshTools::libmesh_assert_valid_neighbors(), libMesh::MeshTools::libmesh_assert_valid_refinement_flags(), libMesh::Tri3Subdivision::local_node_number(), libMesh::MeshRefinement::make_coarsening_compatible(), libMesh::Elem::node_id(), libMesh::UNVIO::nodes_out(), libMesh::VTKIO::nodes_to_vtk(), libMesh::CompareElemIdsByLevel::operator()(), libMesh::WeightedPatchRecoveryErrorEstimator::EstimateError::operator()(), libMesh::PatchRecoveryErrorEstimator::EstimateError::operator()(), libMesh::BoundaryInfo::operator=(), libMesh::Parallel::Packing< const Node * >::pack(), libMesh::Parallel::Packing< const Elem * >::pack(), libMesh::MetisPartitioner::partition_range(), libMesh::SFCPartitioner::partition_range(), libMesh::ErrorVector::plot_error(), libMesh::DofObject::print_dof_info(), libMesh::DistributedMesh::query_elem_ptr(), libMesh::DistributedMesh::query_node_ptr(), libMesh::Nemesis_IO::read(), libMesh::ExodusII_IO::read(), libMesh::AbaqusIO::read_elements(), libMesh::DistributedMesh::renumber_elem(), libMesh::DistributedMesh::renumber_node(), libMesh::DistributedMesh::renumber_nodes_and_elements(), libMesh::DofMap::scatter_constraints(), libMesh::HPCoarsenTest::select_refinement(), libMesh::Partitioner::set_node_processor_ids(), libMesh::DofMap::set_nonlocal_dof_objects(), libMesh::Partitioner::set_parent_processor_ids(), libMesh::LaplaceMeshSmoother::smooth(), libMesh::MeshTools::Modification::smooth(), libMesh::ReplicatedMesh::stitching_helper(), libMesh::BoundaryInfo::sync(), libMesh::Parallel::sync_dofobject_data_by_id(), libMesh::Parallel::sync_element_data_by_parent_id(), libMesh::Parallel::sync_node_data_by_element_id(), libMesh::TetGenMeshInterface::triangulate_conformingDelaunayMesh_carvehole(), libMesh::MeshRefinement::uniformly_coarsen(), libMesh::Parallel::Packing< Elem * >::unpack(), libMesh::GMVIO::write_ascii_new_impl(), libMesh::GMVIO::write_ascii_old_impl(), libMesh::CheckpointIO::write_connectivity(), libMesh::ExodusII_IO_Helper::write_element_values(), libMesh::ExodusII_IO_Helper::write_elements(), libMesh::GmshIO::write_mesh(), libMesh::ExodusII_IO_Helper::write_nodal_coordinates(), libMesh::CheckpointIO::write_nodes(), libMesh::CheckpointIO::write_remote_elem(), and libMesh::XdrIO::write_serialized_connectivity().
 {
   libmesh_assert (this->valid_id());
   return _id;
 }
void libMesh::ReferenceCounter::increment_constructor_count (const std::string & name) inline protected inherited
Increments the construction counter. Should be called in the constructor of any derived class that will be reference counted.
Definition at line 185 of file reference_counter.h.
References libMesh::ReferenceCounter::_counts, libMesh::Quality::name(), and libMesh::Threads::spin_mtx.
Referenced by libMesh::ReferenceCounter::n_objects(), and libMesh::ReferenceCountedObject< RBParametrized >::ReferenceCountedObject().
 {
   Threads::spin_mutex::scoped_lock lock(Threads::spin_mtx);
   std::pair<unsigned int, unsigned int> & p = _counts[name];
   p.first++;
 }
void libMesh::ReferenceCounter::increment_constructor_count (const std::string & name) inline protected inherited
Increments the construction counter. Should be called in the constructor of any derived class that will be reference counted.
Definition at line 185 of file reference_counter.h.
References libMesh::ReferenceCounter::_counts, libMesh::Quality::name(), and libMesh::Threads::spin_mtx.
Referenced by libMesh::ReferenceCounter::n_objects(), and libMesh::ReferenceCountedObject< RBParametrized >::ReferenceCountedObject().
 {
   Threads::spin_mutex::scoped_lock lock(Threads::spin_mtx);
   std::pair<unsigned int, unsigned int> & p = _counts[name];
   p.first++;
 }
void libMesh::ReferenceCounter::increment_destructor_count (const std::string & name) inline protected inherited
Increments the destruction counter. Should be called in the destructor of any derived class that will be reference counted.
Definition at line 198 of file reference_counter.h.
References libMesh::ReferenceCounter::_counts, libMesh::Quality::name(), and libMesh::Threads::spin_mtx.
Referenced by libMesh::ReferenceCounter::n_objects(), and libMesh::ReferenceCountedObject< RBParametrized >::~ReferenceCountedObject().
 {
   Threads::spin_mutex::scoped_lock lock(Threads::spin_mtx);
   std::pair<unsigned int, unsigned int> & p = _counts[name];
   p.second++;
 }
void libMesh::ReferenceCounter::increment_destructor_count (const std::string & name) inline protected inherited
Increments the destruction counter. Should be called in the destructor of any derived class that will be reference counted.
Definition at line 198 of file reference_counter.h.
References libMesh::ReferenceCounter::_counts, libMesh::Quality::name(), and libMesh::Threads::spin_mtx.
Referenced by libMesh::ReferenceCounter::n_objects(), and libMesh::ReferenceCountedObject< RBParametrized >::~ReferenceCountedObject().
 {
   Threads::spin_mutex::scoped_lock lock(Threads::spin_mtx);
   std::pair<unsigned int, unsigned int> & p = _counts[name];
   p.second++;
 }
virtual bool libMesh::Cell::infinite () const inline virtual inherited
Returns
false. All classes derived from Cell are finite elements.
Implements libMesh::Elem.
Definition at line 69 of file cell.h.
 { return false; }
const Elem * libMesh::Elem::interior_parent () const inherited
Returns
The higher-dimensional Elem for which this Elem is a face.
In some cases it is desireable to extract the boundary (or a subset thereof) of a D-dimensional mesh as a (D-1)-dimensional manifold. In this case we may want to know the 'parent' element from which the manifold elements were extracted. We can easily do that for the level-0 manifold elements by storing the D-dimensional parent. This method provides access to that element.
This method is not safe to call if this->dim() == LIBMESH_DIM; in such cases no data storage for an interior parent pointer has been allocated.
Definition at line 941 of file elem.C.
References libMesh::Elem::_elemlinks, libMesh::Elem::dim(), libMesh::Elem::level(), libMesh::libmesh_assert(), libMesh::Elem::n_sides(), and libMesh::remote_elem.
Referenced by libMesh::ParmetisPartitioner::build_graph(), libMesh::MeshBase::detect_interior_parents(), libMesh::Elem::find_interior_neighbors(), libMesh::UnstructuredMesh::find_neighbors(), libMesh::BoundaryInfo::get_side_and_node_maps(), libMesh::Elem::is_linear(), libMesh::MeshTools::libmesh_assert_valid_amr_interior_parents(), libMesh::MeshRefinement::limit_overrefined_boundary(), libMesh::MeshRefinement::limit_underrefined_boundary(), libMesh::GhostPointNeighbors::operator()(), libMesh::Parallel::Packing< const Elem * >::pack(), libMesh::MetisPartitioner::partition_range(), and libMesh::Parallel::Packing< Elem * >::unpack().
 {
   // interior parents make no sense for full-dimensional elements.
   libmesh_assert_less (this->dim(), LIBMESH_DIM);
   // they USED TO BE only good for level-0 elements, but we now
   // support keeping interior_parent() valid on refined boundary
   // elements.
   // if (this->level() != 0)
   // return this->parent()->interior_parent();
   // We store the interior_parent pointer after both the parent
   // neighbor and neighbor pointers
   Elem * interior_p = _elemlinks[1+this->n_sides()];
   // If we have an interior_parent, we USED TO assume it was a
   // one-higher-dimensional interior element, but we now allow e.g.
   // edge elements to have a 3D interior_parent with no
   // intermediate 2D element.
   // libmesh_assert (!interior_p ||
   //                interior_p->dim() == (this->dim()+1));
   libmesh_assert (!interior_p ||
                   (interior_p == remote_elem) ||
                   (interior_p->dim() > this->dim()));
   // We require consistency between AMR of interior and of boundary
   // elements
   if (interior_p && (interior_p != remote_elem))
     libmesh_assert_less_equal (interior_p->level(), this->level());
   return interior_p;
 }
Elem * libMesh::Elem::interior_parent () inherited
Definition at line 976 of file elem.C.
References libMesh::Elem::_elemlinks, libMesh::Elem::dim(), libMesh::Elem::level(), libMesh::libmesh_assert(), libMesh::Elem::n_sides(), and libMesh::remote_elem.
 {
   // See the const version for comments
   libmesh_assert_less (this->dim(), LIBMESH_DIM);
   Elem * interior_p = _elemlinks[1+this->n_sides()];
   libmesh_assert (!interior_p ||
                   (interior_p == remote_elem) ||
                   (interior_p->dim() > this->dim()));
   if (interior_p && (interior_p != remote_elem))
     libmesh_assert_less_equal (interior_p->level(), this->level());
   return interior_p;
 }
void libMesh::DofObject::invalidate () inline inherited
Invalidates all the indices for this DofObject
Definition at line 580 of file dof_object.h.
References libMesh::DofObject::invalidate_dofs(), libMesh::DofObject::invalidate_id(), and libMesh::DofObject::invalidate_processor_id().
Referenced by libMesh::DofObject::DofObject().
 {
   this->invalidate_dofs ();
   this->invalidate_id ();
   this->invalidate_processor_id ();
 }
void libMesh::DofObject::invalidate_dofs (const unsigned int sys_num = libMesh::invalid_uint) inline inherited
Sets all degree of freedom numbers to invalid_id
Definition at line 544 of file dof_object.h.
References libMesh::DofObject::invalid_id, libMesh::DofObject::n_comp_group(), libMesh::DofObject::n_systems(), libMesh::DofObject::n_var_groups(), and libMesh::DofObject::set_vg_dof_base().
Referenced by libMesh::DofObject::invalidate().
 {
   // If the user does not specify the system number...
   if (sys_num >= this->n_systems())
     {
       for (unsigned int s=0; s<this->n_systems(); s++)
         for (unsigned int vg=0; vg<this->n_var_groups(s); vg++)
           if (this->n_comp_group(s,vg))
             this->set_vg_dof_base(s,vg,invalid_id);
     }
   // ...otherwise invalidate the dofs for all systems
   else
     for (unsigned int vg=0; vg<this->n_var_groups(sys_num); vg++)
       if (this->n_comp_group(sys_num,vg))
         this->set_vg_dof_base(sys_num,vg,invalid_id);
 }
void libMesh::DofObject::invalidate_id () inline inherited
Sets the id to invalid_id
Definition at line 564 of file dof_object.h.
References libMesh::DofObject::invalid_id, and libMesh::DofObject::set_id().
Referenced by libMesh::DofObject::invalidate().
 {
   this->set_id (invalid_id);
 }
void libMesh::DofObject::invalidate_processor_id () inline inherited
Sets the processor id to invalid_processor_id
Definition at line 572 of file dof_object.h.
References libMesh::DofObject::invalid_processor_id, and libMesh::DofObject::processor_id().
Referenced by libMesh::DofObject::invalidate(), libMesh::Partitioner::set_node_processor_ids(), and libMesh::Partitioner::set_parent_processor_ids().
 {
   this->processor_id (invalid_processor_id);
 }
bool libMesh::Elem::is_ancestor_of (const Elem * descendant) const inline inherited
Returns
true if descendant is a child of this, or a child of a child of this, etc., false otherwise or if AMR is disabled.
Definition at line 2121 of file elem.h.
References libMesh::Elem::parent().
Referenced by libMesh::Elem::family_tree_by_subneighbor(), libMesh::UnstructuredMesh::find_neighbors(), libMesh::Elem::is_linear(), libMesh::Elem::make_links_to_me_local(), and libMesh::Elem::total_family_tree_by_subneighbor().
 {
 #ifdef LIBMESH_ENABLE_AMR
   const Elem * e = descendant;
   while (e)
     {
       if (this == e)
         return true;
       e = e->parent();
     }
 #endif
   return false;
 }
bool libMesh::Elem::is_child_on_edge (const unsigned int c, const unsigned int e) const virtual inherited
Returns
true if the specified child is on the specified edge.
Definition at line 1658 of file elem.C.
References libMesh::Elem::build_edge_ptr(), libMesh::Elem::n_children(), and libMesh::Elem::n_edges().
Referenced by libMesh::FEGenericBase< OutputType >::coarsened_dof_values(), libMesh::BoundaryInfo::edge_boundary_ids(), and libMesh::GenericProjector< FFunctor, GFunctor, FValue, ProjectionAction >::operator()().
 {
   libmesh_assert_less (c, this->n_children());
   libmesh_assert_less (e, this->n_edges());
   UniquePtr<const Elem> my_edge = this->build_edge_ptr(e);
   UniquePtr<const Elem> child_edge = this->build_edge_ptr(e);
   // We're assuming that an overlapping child edge has the same
   // number and orientation as its parent
   return (child_edge->node_id(0) == my_edge->node_id(0) ||
           child_edge->node_id(1) == my_edge->node_id(1));
 }
bool libMesh::Tet4::is_child_on_side (const unsigned int c, const unsigned int s) const virtual
Returns
true if the specified child is on the specified side.
Implements libMesh::Elem.
Definition at line 88 of file cell_tet4.C.
References libMesh::Tet::is_child_on_side_helper().
Referenced by n_sub_elem().
 {
   // OK, for the Tet4, this is pretty obvious... it is sets of nodes
   // not equal to the current node.  But if we want this algorithm to
   // be generic and work for Tet10 also it helps to do it this way.
   const unsigned int nodes_opposite[4][3] =
     {
       {1,2,3}, // nodes opposite node 0
       {0,2,3}, // nodes opposite node 1
       {0,1,3}, // nodes opposite node 2
       {0,1,2}  // nodes opposite node 3
     };
   // Call the base class helper function
   return Tet::is_child_on_side_helper(c, s, nodes_opposite);
 }
bool libMesh::Tet::is_child_on_side_helper (const unsigned int c, const unsigned int s, const unsigned int checked_nodes[][3]) const protected inherited
Called by descendant classes with appropriate data to determine if child c is on side s. Only works if LIBMESH_ENABLE_AMR.
Definition at line 103 of file cell_tet.C.
References std::abs(), libMesh::Elem::embedding_matrix(), libMesh::Tet::n_children(), libMesh::Tet::n_sides(), libMesh::Real, and side_nodes_map.
Referenced by is_child_on_side(), and libMesh::Tet10::is_child_on_side().
 {
   libmesh_assert_less (c, this->n_children());
   libmesh_assert_less (s, this->n_sides());
   // For the 4 vertices, child c touches vertex c, so we can return
   // true if that vertex is on side s
   for (unsigned int i = 0; i != 3; ++i)
     if (Tet4::side_nodes_map[s][i] == c)
       return true;
   // If we are a "vertex child" and we didn't already return true,
   // we must not be on the side in question
   if (c < 4)
     return false;
   // For the 4 non-vertex children, the child ordering depends on the
   // diagonal selection.  We'll let the embedding matrix figure that
   // out: if this child has three nodes that don't depend on the
   // position of the node_facing_side[s], then we're on side s.  Which
   // three nodes those are depends on the subclass, so their responsibility
   // is to call this function with the proper check_nodes array
   const unsigned int node_facing_side[4] = {3, 2, 0, 1};
   const unsigned int n = node_facing_side[s];
   // Add up the absolute values of the entries of the embedding matrix for the
   // nodes opposite node n.  If it is equal to zero, then the child in question is
   // on side s, so return true.
   Real embedding_sum = 0.;
   for (unsigned i=0; i<3; ++i)
     embedding_sum += std::abs(this->embedding_matrix(c, checked_nodes[n][i], n));
   return ( std::abs(embedding_sum) < 1.e-3 );
 }
bool libMesh::Tet4::is_edge (const unsigned int i) const virtual
Returns
true if the specified (local) node number is an edge.
Implements libMesh::Elem.
Definition at line 62 of file cell_tet4.C.
Referenced by n_sub_elem().
 {
   return false;
 }
bool libMesh::Tet::is_edge_on_side (const unsigned int e, const unsigned int s) const virtual inherited
Returns
true if the specified edge is on the specified side.
Implements libMesh::Elem.
Definition at line 179 of file cell_tet.C.
References edge_nodes_map, libMesh::Elem::is_node_on_side(), libMesh::Tet::n_edges(), and libMesh::Tet::n_sides().
Referenced by libMesh::Tet::n_children().
 {
   libmesh_assert_less (e, this->n_edges());
   libmesh_assert_less (s, this->n_sides());
   return (is_node_on_side(Tet4::edge_nodes_map[e][0],s) &&
           is_node_on_side(Tet4::edge_nodes_map[e][1],s));
 }
bool libMesh::Tet4::is_face (const unsigned int i) const virtual
Returns
true if the specified (local) node number is a face.
Implements libMesh::Elem.
Definition at line 67 of file cell_tet4.C.
Referenced by n_sub_elem().
 {
   return false;
 }
virtual bool libMesh::Tet4::is_linear () const inline virtual
Returns
true if the Lagrange shape functions on this element are linear.
Reimplemented from libMesh::Elem.
Definition at line 124 of file cell_tet4.h.
 { return true; }
virtual bool libMesh::Elem::is_mid_infinite_edge_node (const unsigned int) const inline virtual inherited
Returns
true if the specified (local) node number is a "mid-edge" node on an infinite element edge.
This is false for all nodes on non-infinite elements, so we won't make it pure virtual, to simplify their code.
Reimplemented in libMesh::InfEdge2, libMesh::InfQuad, libMesh::InfPrism, and libMesh::InfHex.
Definition at line 1378 of file elem.h.
References libMesh::Elem::infinite(), and libMesh::libmesh_assert().
Referenced by libMesh::Elem::parent_bracketing_nodes().
   { libmesh_assert (!this->infinite()); return false; }
bool libMesh::Tet4::is_node_on_edge (const unsigned int n, const unsigned int e) const virtual
Returns
true if the specified (local) node number is on the specified edge.
Implements libMesh::Elem.
Definition at line 72 of file cell_tet4.C.
References edge_nodes_map, and libMesh::Tet::n_edges().
Referenced by n_sub_elem().
 {
   libmesh_assert_less (e, n_edges());
   for (unsigned int i = 0; i != 2; ++i)
     if (edge_nodes_map[e][i] == n)
       return true;
   return false;
 }
bool libMesh::Tet4::is_node_on_side (const unsigned int n, const unsigned int s) const virtual
Returns
true if the specified (local) node number is on the specified side.
Implements libMesh::Elem.
Definition at line 120 of file cell_tet4.C.
References libMesh::Tet::n_sides(), and side_nodes_map.
Referenced by n_sub_elem().
 {
   libmesh_assert_less (s, n_sides());
   for (unsigned int i = 0; i != 3; ++i)
     if (side_nodes_map[s][i] == n)
       return true;
   return false;
 }
virtual bool libMesh::Elem::is_remote () const inline virtual inherited
Returns
true if this element is remote, false otherwise.
A remote element (see RemoteElem) is a syntactic convenience – it is a placeholder for an element which exists on some other processor. Local elements are required to have valid neighbors, and these ghost elements may have remote neighbors for data structure consistency. The use of remote elements helps ensure that any element we may access has a NULL neighbor only if it lies on the physical boundary of the domain.
Reimplemented in libMesh::RemoteElem.
Definition at line 487 of file elem.h.
References libMesh::Elem::connectivity(), libMesh::Elem::dim(), libMesh::out, libMesh::Elem::type(), and libMesh::Elem::write_connectivity().
Referenced by libMesh::Elem::active_family_tree(), libMesh::Elem::active_family_tree_by_side(), libMesh::Elem::family_tree(), libMesh::Elem::family_tree_by_side(), libMesh::TopologyMap::fill(), libMesh::Elem::make_links_to_me_local(), libMesh::Partitioner::set_parent_processor_ids(), and libMesh::Elem::total_family_tree().
   { return false; }
bool libMesh::Elem::is_semilocal (const processor_id_type my_pid) const inherited
Returns
true if this element is semilocal to the calling processor, which must specify its rank.
Definition at line 538 of file elem.C.
References end, libMesh::Elem::find_point_neighbors(), and libMesh::DofObject::processor_id().
Referenced by libMesh::Patch::add_semilocal_face_neighbors(), and libMesh::Patch::add_semilocal_point_neighbors().
 {
   std::set<const Elem *> point_neighbors;
   this->find_point_neighbors(point_neighbors);
   std::set<const Elem *>::const_iterator       it  = point_neighbors.begin();
   const std::set<const Elem *>::const_iterator end = point_neighbors.end();
   for (; it != end; ++it)
     {
       const Elem * elem = *it;
       if (elem->processor_id() == my_pid)
         return true;
     }
   return false;
 }
bool libMesh::Tet4::is_vertex (const unsigned int i) const virtual
Returns
true if the specified (local) node number is a vertex.
Implements libMesh::Elem.
Definition at line 57 of file cell_tet4.C.
Referenced by n_sub_elem().
 {
   return true;
 }
virtual unsigned int libMesh::Elem::is_vertex_on_child (unsigned int, unsigned int n) const inline virtual inherited
Returns
true if the specified child has a vertex at the specified (child-local) node number. Except in odd cases like pyramid refinement the child will have the same local structure as the parent element.
Definition at line 601 of file elem.h.
References libMesh::Elem::build_edge(), libMesh::Elem::build_edge_ptr(), libMesh::Elem::build_side(), libMesh::Elem::build_side_ptr(), libMesh::Elem::centroid(), libMesh::Elem::default_order(), libMesh::Elem::hmax(), libMesh::Elem::hmin(), libMesh::Elem::is_edge(), libMesh::Elem::is_edge_on_side(), libMesh::Elem::is_face(), libMesh::Elem::is_node_on_edge(), libMesh::Elem::is_node_on_side(), libMesh::Elem::is_vertex(), libMesh::Elem::is_vertex_on_parent(), libMesh::Elem::loose_bounding_box(), libMesh::Elem::n_sub_elem(), libMesh::Elem::opposite_node(), libMesh::Elem::opposite_side(), libMesh::Elem::quality(), libMesh::Real, libMesh::Elem::side(), libMesh::Elem::side_ptr(), and libMesh::Elem::volume().
Referenced by libMesh::Elem::parent_bracketing_nodes().
   { return this->is_vertex(n); }
bool libMesh::Elem::is_vertex_on_parent (unsigned int c, unsigned int n) const virtual inherited
Returns
true if this element has a vertex at the specified (child-local) node number n of the specified child c.
Definition at line 3031 of file elem.C.
References libMesh::Elem::child_ptr(), libMesh::libmesh_ignore(), libMesh::Elem::n_vertices(), and libMesh::Elem::node_ptr().
Referenced by libMesh::Elem::is_vertex_on_child(), and libMesh::GenericProjector< FFunctor, GFunctor, FValue, ProjectionAction >::operator()().
 {
 #ifdef LIBMESH_ENABLE_AMR
   unsigned int my_n_vertices = this->n_vertices();
   for (unsigned int n_parent = 0; n_parent != my_n_vertices;
        ++n_parent)
     if (this->node_ptr(n_parent) == this->child_ptr(c)->node_ptr(n))
       return true;
   return false;
 #else
   // No AMR?
   libmesh_ignore(c);
   libmesh_ignore(n);
   libmesh_error_msg("ERROR: AMR disabled, how did we get here?");
   return true;
 #endif
 }
dof_id_type libMesh::Tet::key (const unsigned int s) const virtual inherited
Returns
An id associated with the s side of this element. The id is not necessarily unique, but should be close. This is particularly useful in the MeshBase::find_neighbors() routine.
Implements libMesh::Elem.
Definition at line 55 of file cell_tet.C.
References libMesh::Elem::compute_key(), libMesh::Tet::n_sides(), libMesh::Elem::node_id(), and side_nodes_map.
 {
   libmesh_assert_less (s, this->n_sides());
   return this->compute_key(this->node_id(Tet4::side_nodes_map[s][0]),
                            this->node_id(Tet4::side_nodes_map[s][1]),
                            this->node_id(Tet4::side_nodes_map[s][2]));
 }
dof_id_type libMesh::Tet4::key () const virtual
Returns
An id associated with the global node ids of this element. The id is not necessarily unique, but should be close.
Reimplemented from libMesh::Elem.
Definition at line 330 of file cell_tet4.C.
References libMesh::Elem::compute_key(), and libMesh::Elem::node_id().
 {
   return this->compute_key(this->node_id(0),
                            this->node_id(1),
                            this->node_id(2),
                            this->node_id(3));
 }
Real libMesh::Elem::length (const unsigned int n1, const unsigned int n2) const inherited
Returns
The distance between nodes n1 and n2.
Useful for computing the lengths of the sides of elements.
Definition at line 483 of file elem.C.
References libMesh::Elem::n_vertices(), and libMesh::Elem::point().
Referenced by libMesh::Elem::is_linear(), libMesh::Hex::quality(), libMesh::InfHex::quality(), and libMesh::Quad::quality().
 {
   libmesh_assert_less ( n1, this->n_vertices() );
   libmesh_assert_less ( n2, this->n_vertices() );
   return (this->point(n1) - this->point(n2)).norm();
 }
unsigned int libMesh::Elem::level () const inline inherited
Returns
The refinement level of the current element.
If the element's parent is NULL then by convention it is at level 0, otherwise it is simply at one level greater than its parent.
Definition at line 2184 of file elem.h.
References libMesh::Elem::dim(), libMesh::Elem::level(), libmesh_nullptr, and libMesh::Elem::parent().
Referenced by libMesh::MeshRefinement::_coarsen_elements(), libMesh::Elem::active_family_tree_by_neighbor(), libMesh::Elem::active_family_tree_by_topological_neighbor(), libMesh::BoundaryInfo::add_edge(), libMesh::BoundaryInfo::add_shellface(), libMesh::BoundaryInfo::add_side(), libMesh::UnstructuredMesh::all_second_order(), libMesh::BoundaryInfo::boundary_ids(), libMesh::FEAbstract::compute_node_constraints(), libMesh::FEGenericBase< OutputType >::compute_periodic_constraints(), libMesh::FEAbstract::compute_periodic_node_constraints(), libMesh::FEGenericBase< OutputType >::compute_proj_constraints(), libMesh::BoundaryInfo::edge_boundary_ids(), libMesh::MeshRefinement::eliminate_unrefined_patches(), libMesh::MeshRefinement::enforce_mismatch_limit_prior_to_refinement(), libMesh::JumpErrorEstimator::estimate_error(), libMesh::MeshTools::find_hanging_nodes_and_parents(), libMesh::Elem::find_interior_neighbors(), libMesh::UnstructuredMesh::find_neighbors(), libMesh::MeshRefinement::flag_elements_by_elem_fraction(), libMesh::MeshRefinement::flag_elements_by_error_fraction(), libMesh::MeshRefinement::flag_elements_by_error_tolerance(), libMesh::MeshRefinement::flag_elements_by_mean_stddev(), libMesh::MeshRefinement::flag_elements_by_nelem_target(), libMesh::Elem::get_info(), libMesh::Elem::interior_parent(), libMesh::Elem::is_linear(), libMesh::Elem::level(), libMesh::MeshTools::libmesh_assert_valid_amr_interior_parents(), libMesh::MeshRefinement::limit_level_mismatch_at_edge(), libMesh::MeshRefinement::limit_level_mismatch_at_node(), libMesh::MeshRefinement::limit_overrefined_boundary(), libMesh::MeshRefinement::limit_underrefined_boundary(), libMesh::MeshRefinement::make_coarsening_compatible(), libMesh::Elem::make_links_to_me_local(), libMesh::Elem::make_links_to_me_remote(), libMesh::MeshRefinement::make_refinement_compatible(), libMesh::Elem::nullify_neighbors(), libMesh::CompareElemIdsByLevel::operator()(), libMesh::Parallel::Packing< const Elem * >::pack(), libMesh::Parallel::Packing< const Elem * >::packable_size(), libMesh::BoundaryInfo::remove_edge(), libMesh::Elem::remove_links_to_me(), libMesh::BoundaryInfo::remove_shellface(), libMesh::BoundaryInfo::remove_side(), libMesh::BoundaryInfo::shellface_boundary_ids(), libMesh::BoundaryInfo::side_with_boundary_id(), libMesh::ReplicatedMesh::stitching_helper(), libMesh::MeshRefinement::test_level_one(), libMesh::Elem::top_parent(), libMesh::Elem::topological_neighbor(), libMesh::Parallel::Packing< Elem * >::unpack(), and libMesh::Elem::which_neighbor_am_i().
 {
 #ifdef LIBMESH_ENABLE_AMR
   // if I don't have a parent I was
   // created directly from file
   // or by the user, so I am a
   // level-0 element
   if (this->parent() == libmesh_nullptr)
     return 0;
   // if the parent and this element are of different
   // dimensionality we are at the same level as
   // the parent (e.g. we are the 2D side of a
   // 3D element)
   if (this->dim() != this->parent()->dim())
     return this->parent()->level();
   // otherwise we are at a level one
   // higher than our parent
   return (this->parent()->level() + 1);
 #else
   // Without AMR all elements are
   // at level 0.
   return 0;
 #endif
 }
void libMesh::Elem::libmesh_assert_valid_neighbors () const inherited
Checks for consistent neighbor links on this element.
Definition at line 1127 of file elem.C.
References libMesh::Elem::dim(), libMesh::libmesh_assert(), libMesh::Elem::n_neighbors(), libMesh::Elem::neighbor_ptr(), libMesh::Elem::parent(), libMesh::remote_elem, libMesh::Elem::subactive(), and libMesh::Elem::which_neighbor_am_i().
Referenced by libMesh::MeshTools::libmesh_assert_valid_neighbors().
 {
   for (unsigned int s=0; s<this->n_neighbors(); s++)
     {
       const Elem * neigh = this->neighbor_ptr(s);
       // Any element might have a remote neighbor; checking
       // to make sure that's not inaccurate is tough.
       if (neigh == remote_elem)
         continue;
       if (neigh)
         {
           // Only subactive elements have subactive neighbors
           libmesh_assert (this->subactive() || !neigh->subactive());
           const Elem * elem = this;
           // If we're subactive but our neighbor isn't, its
           // return neighbor link will be to our first active
           // ancestor OR to our inactive ancestor of the same
           // level as neigh,
           if (this->subactive() && !neigh->subactive())
             {
               for (elem = this; !elem->active();
                    elem = elem->parent())
                 libmesh_assert(elem);
             }
           else
             {
               unsigned int rev = neigh->which_neighbor_am_i(elem);
               libmesh_assert_less (rev, neigh->n_neighbors());
               if (this->subactive() && !neigh->subactive())
                 {
                   while (neigh->neighbor_ptr(rev) != elem)
                     {
                       libmesh_assert(elem->parent());
                       elem = elem->parent();
                     }
                 }
               else
                 {
                   const Elem * nn = neigh->neighbor_ptr(rev);
                   libmesh_assert(nn);
                   for (; elem != nn; elem = elem->parent())
                     libmesh_assert(elem);
                 }
             }
         }
       // If we don't have a neighbor and we're not subactive, our
       // ancestors shouldn't have any neighbors in this same
       // direction.
       else if (!this->subactive())
         {
           const Elem * my_parent = this->parent();
           if (my_parent &&
               // A parent with a different dimension isn't really one of
               // our ancestors, it means we're on a boundary mesh and this
               // is an interior mesh element for which we're on a side.
               // Nothing to test for in that case.
               (my_parent->dim() == this->dim()))
             libmesh_assert (!my_parent->neighbor_ptr(s));
         }
     }
 }
void libMesh::Elem::libmesh_assert_valid_node_pointers () const inherited
Checks for a valid id and pointers to nodes with valid ids on this element.
Definition at line 1115 of file elem.C.
References libMesh::libmesh_assert(), libMesh::Elem::n_nodes(), libMesh::Elem::node_ptr(), and libMesh::DofObject::valid_id().
Referenced by libMesh::MeshTools::libmesh_assert_valid_node_pointers().
 {
   libmesh_assert(this->valid_id());
   for (unsigned int n=0; n != this->n_nodes(); ++n)
     {
       libmesh_assert(this->node_ptr(n));
       libmesh_assert(this->node_ptr(n)->valid_id());
     }
 }
unsigned int libMesh::Elem::local_node (const dof_id_type i) const inline inherited
Returns
The local id number of global Node id i, or invalid_uint if Node id i is not local.
Definition at line 1704 of file elem.h.
References libMesh::invalid_uint, libMesh::Elem::n_nodes(), and libMesh::Elem::node_id().
Referenced by libMesh::MeshTools::find_nodal_neighbors(), and libMesh::ReplicatedMesh::stitching_helper().
 {
   for (unsigned int n=0; n != this->n_nodes(); ++n)
     if (this->node_id(n) == i)
       return n;
   return libMesh::invalid_uint;
 }
BoundingBox libMesh::Cell::loose_bounding_box () const virtual inherited
Returns
A bounding box (not necessarily the minimal bounding box) containing the geometric element.
Reimplemented from libMesh::Elem.
Definition at line 26 of file cell.C.
References libMesh::Elem::build_side_ptr(), libMesh::Elem::n_sides(), and libMesh::BoundingBox::union_with().
Referenced by libMesh::Cell::dim().
 {
   // This might have curved sides, but it's definitely *not* curving
   // through 4-D space, so the full bounding box is just the merger of
   // the sides' bounding boxes.
   BoundingBox bbox = this->build_side_ptr(0)->loose_bounding_box();
   unsigned int my_n_sides = this->n_sides();
   for (unsigned s=1; s < my_n_sides; ++s)
     bbox.union_with(this->build_side_ptr(s)->loose_bounding_box());
   return bbox;
 }
void libMesh::Elem::make_links_to_me_local (unsigned int n) inherited
Resets the appropriate neighbor pointers of our nth neighbor (and its descendants, if appropriate) to point to this Elem instead of to the global remote_elem. Used by the library when a formerly remote element is being added to the local processor.
Definition at line 1199 of file elem.C.
References libMesh::Elem::active(), libMesh::Elem::family_tree_by_side(), libMesh::Elem::has_children(), libMesh::Elem::is_ancestor_of(), libMesh::Elem::is_remote(), libMesh::Elem::JUST_REFINED, libMesh::Elem::level(), libMesh::libmesh_assert(), libmesh_nullptr, libMesh::Elem::n_sides(), libMesh::Elem::neighbor_ptr(), libMesh::Elem::parent(), libMesh::Elem::refinement_flag(), libMesh::remote_elem, libMesh::Elem::set_neighbor(), libMesh::Elem::side_ptr(), and libMesh::Elem::subactive().
Referenced by libMesh::Parallel::Packing< Elem * >::unpack().
 {
   Elem * neigh = this->neighbor_ptr(n);
   // Don't bother calling this function unless it's necessary
   libmesh_assert(neigh);
   libmesh_assert(!neigh->is_remote());
   // We never have neighbors more refined than us
   libmesh_assert_less_equal (neigh->level(), this->level());
   // We never have subactive neighbors of non subactive elements
   libmesh_assert(!neigh->subactive() || this->subactive());
   // If we have a neighbor less refined than us then it must not
   // have any more refined descendants we could have pointed to
   // instead.
   libmesh_assert((neigh->level() == this->level()) ||
                  (neigh->active() && !this->subactive()) ||
                  (!neigh->has_children() && this->subactive()));
   // If neigh is at our level, then its family might have
   // remote_elem neighbor links which need to point to us
   // instead, but if not, then we're done.
   if (neigh->level() != this->level())
     return;
   // What side of neigh are we on?  We can't use the usual Elem
   // method because we're in the middle of restoring topology
   const UniquePtr<Elem> my_side = this->side_ptr(n);
   unsigned int nn = 0;
   for (; nn != neigh->n_sides(); ++nn)
     {
       const UniquePtr<Elem> neigh_side = neigh->side_ptr(nn);
       if (*my_side == *neigh_side)
         break;
     }
   // we had better be on *some* side of neigh
   libmesh_assert_less (nn, neigh->n_sides());
   // Find any elements that ought to point to elem
   std::vector<const Elem *> neigh_family;
 #ifdef LIBMESH_ENABLE_AMR
   if (this->active())
     neigh->family_tree_by_side(neigh_family, nn);
   else if (neigh->subactive())
 #endif
     neigh_family.push_back(neigh);
   // And point them to elem
   for (std::size_t i = 0; i != neigh_family.size(); ++i)
     {
       Elem * neigh_family_member = const_cast<Elem *>(neigh_family[i]);
       // Only subactive elements point to other subactive elements
       if (this->subactive() && !neigh_family_member->subactive())
         continue;
       // Ideally, the neighbor link ought to either be correct
       // already or ought to be to remote_elem.
       //
       // However, if we're redistributing a newly created elem,
       // after an AMR step but before find_neighbors has fixed up
       // neighbor links, we might have an out of date neighbor
       // link to elem's parent instead.
 #ifdef LIBMESH_ENABLE_AMR
       libmesh_assert((neigh_family_member->neighbor_ptr(nn) &&
                       (neigh_family_member->neighbor_ptr(nn)->active() ||
                        neigh_family_member->neighbor_ptr(nn)->is_ancestor_of(this))) ||
                      (neigh_family_member->neighbor_ptr(nn) == remote_elem) ||
                      ((this->refinement_flag() == JUST_REFINED) &&
                       (this->parent() != libmesh_nullptr) &&
                       (neigh_family_member->neighbor_ptr(nn) == this->parent())));
 #else
       libmesh_assert((neigh_family_member->neighbor_ptr(nn) == this) ||
                      (neigh_family_member->neighbor_ptr(nn) == remote_elem));
 #endif
       neigh_family_member->set_neighbor(nn, this);
     }
 }
void libMesh::Elem::make_links_to_me_remote () inherited
Resets this element's neighbors' appropriate neighbor pointers and its parent's and children's appropriate pointers to point to the global remote_elem instead of this. Used by the library before an element becomes remote on the local processor.
Definition at line 1283 of file elem.C.
References libMesh::Elem::child_ptr(), libMesh::Elem::dim(), libMesh::Elem::has_children(), libMesh::Elem::has_neighbor(), libMesh::Elem::level(), libMesh::libmesh_assert(), libMesh::Elem::n_children(), libMesh::Elem::n_neighbors(), libMesh::Elem::n_sides(), libMesh::Elem::neighbor_ptr(), libMesh::Elem::parent(), libMesh::remote_elem, libMesh::Elem::set_child(), libMesh::Elem::set_neighbor(), libMesh::Elem::subactive(), libMesh::Elem::total_family_tree_by_neighbor(), libMesh::Elem::total_family_tree_by_subneighbor(), libMesh::Elem::which_child_am_i(), and libMesh::Elem::which_neighbor_am_i().
Referenced by libMesh::MeshCommunication::delete_remote_elements().
 {
   libmesh_assert_not_equal_to (this, remote_elem);
   // We need to have handled any children first
 #if defined(LIBMESH_ENABLE_AMR) && defined(DEBUG)
   if (this->has_children())
     for (unsigned int c = 0; c != this->n_children(); ++c)
       {
         Elem * current_child = this->child_ptr(c);
         libmesh_assert_equal_to (current_child, remote_elem);
       }
 #endif
   // Remotify any neighbor links
   for (unsigned int s = 0; s != this->n_sides(); ++s)
     {
       Elem * neigh = this->neighbor_ptr(s);
       if (neigh && neigh != remote_elem)
         {
           // My neighbor should never be more refined than me; my real
           // neighbor would have been its parent in that case.
           libmesh_assert_greater_equal (this->level(), neigh->level());
           if (this->level() == neigh->level() &&
               neigh->has_neighbor(this))
             {
 #ifdef LIBMESH_ENABLE_AMR
               // My neighbor may have descendants which also consider me a
               // neighbor
               std::vector<const Elem *> family;
               neigh->total_family_tree_by_neighbor (family, this);
               // FIXME - There's a lot of ugly const_casts here; we
               // may want to make remote_elem non-const and create
               // non-const versions of the family_tree methods
               for (std::size_t i=0; i != family.size(); ++i)
                 {
                   Elem * n = const_cast<Elem *>(family[i]);
                   libmesh_assert (n);
                   if (n == remote_elem)
                     continue;
                   unsigned int my_s = n->which_neighbor_am_i(this);
                   libmesh_assert_less (my_s, n->n_neighbors());
                   libmesh_assert_equal_to (n->neighbor_ptr(my_s), this);
                   n->set_neighbor(my_s, const_cast<RemoteElem *>(remote_elem));
                 }
 #else
               unsigned int my_s = neigh->which_neighbor_am_i(this);
               libmesh_assert_less (my_s, neigh->n_neighbors());
               libmesh_assert_equal_to (neigh->neighbor_ptr(my_s), this);
               neigh->set_neighbor(my_s, const_cast<RemoteElem *>(remote_elem));
 #endif
             }
 #ifdef LIBMESH_ENABLE_AMR
           // Even if my neighbor doesn't link back to me, it might
           // have subactive descendants which do
           else if (neigh->has_children())
             {
               // If my neighbor at the same level doesn't have me as a
               // neighbor, I must be subactive
               libmesh_assert(this->level() > neigh->level() ||
                              this->subactive());
               // My neighbor must have some ancestor of mine as a
               // neighbor
               Elem * my_ancestor = this->parent();
               libmesh_assert(my_ancestor);
               while (!neigh->has_neighbor(my_ancestor))
                 {
                   my_ancestor = my_ancestor->parent();
                   libmesh_assert(my_ancestor);
                 }
               // My neighbor may have descendants which consider me a
               // neighbor
               std::vector<const Elem *> family;
               neigh->total_family_tree_by_subneighbor (family, my_ancestor, this);
               // FIXME - There's a lot of ugly const_casts here; we
               // may want to make remote_elem non-const and create
               // non-const versions of the family_tree methods
               for (std::size_t i=0; i != family.size(); ++i)
                 {
                   Elem * n = const_cast<Elem *>(family[i]);
                   libmesh_assert (n);
                   if (n == remote_elem)
                     continue;
                   unsigned int my_s = n->which_neighbor_am_i(this);
                   libmesh_assert_less (my_s, n->n_neighbors());
                   libmesh_assert_equal_to (n->neighbor_ptr(my_s), this);
                   n->set_neighbor(my_s, const_cast<RemoteElem *>(remote_elem));
                 }
             }
 #endif
         }
     }
 #ifdef LIBMESH_ENABLE_AMR
   // Remotify parent's child link
   Elem * my_parent = this->parent();
   if (my_parent &&
       // As long as it's not already remote
       my_parent != remote_elem &&
       // And it's a real parent, not an interior parent
       this->dim() == my_parent->dim())
     {
       unsigned int me = my_parent->which_child_am_i(this);
       libmesh_assert_equal_to (my_parent->child_ptr(me), this);
       my_parent->set_child(me, const_cast<RemoteElem *>(remote_elem));
     }
 #endif
 }
virtual Point libMesh::Tet::master_point (const unsigned int i) const inline virtual inherited
Returns
The Point associated with local Node i, in master element rather than physical coordinates.
Implements libMesh::Elem.
Definition at line 57 of file cell_tet.h.
References libMesh::Tet::_master_points, and libMesh::Elem::n_nodes().
   {
     libmesh_assert_less(i, this->n_nodes());
     return Point(_master_points[i][0],
                  _master_points[i][1],
                  _master_points[i][2]);
   }
unsigned int libMesh::Elem::max_descendant_p_level () const inline inherited
Returns
The maximum value of the p-refinement levels of an ancestor element's descendants.
Definition at line 2325 of file elem.h.
References libMesh::Elem::_p_level, libMesh::Elem::active(), libMesh::Elem::child_ptr(), libMesh::libmesh_assert(), std::max(), libMesh::Elem::max_descendant_p_level(), libMesh::Elem::n_children(), libMesh::Elem::p_level(), and libMesh::Elem::subactive().
Referenced by libMesh::FEGenericBase< OutputType >::coarsened_dof_values(), and libMesh::Elem::max_descendant_p_level().
 {
   // This is undefined for subactive elements,
   // which have no active descendants
   libmesh_assert (!this->subactive());
   if (this->active())
     return this->p_level();
   unsigned int max_p_level = _p_level;
   for (unsigned int c=0; c != this->n_children(); c++)
     max_p_level = std::max(max_p_level,
                            this->child_ptr(c)->max_descendant_p_level());
   return max_p_level;
 }
std::pair< Real, Real > libMesh::Tet4::min_and_max_angle () const
Returns
The min and max dihedral angles for the tetrahedron.
Note
There are 6 dihedral angles (angles between the planar faces) for the Tet4. Dihedral angles near 180 deg. are generally bad for interpolation. Small dihedral angles are not necessarily bad for interpolation, but they can affect the stiffness matrix condition number.
Definition at line 305 of file cell_tet4.C.
References libMesh::TypeVector< T >::norm(), libMesh::Elem::point(), and libMesh::Real.
 {
   Point n[4];
   // Compute the outward normal vectors on each face
   n[0] = (this->point(2) - this->point(0)).cross(this->point(1) - this->point(0));
   n[1] = (this->point(1) - this->point(0)).cross(this->point(3) - this->point(0));
   n[2] = (this->point(2) - this->point(1)).cross(this->point(3) - this->point(1));
   n[3] = (this->point(0) - this->point(2)).cross(this->point(3) - this->point(2));
   Real dihedral_angles[6]; // 01, 02, 03, 12, 13, 23
   // Compute dihedral angles
   for (unsigned int k=0,i=0; i<4; ++i)
     for (unsigned int j=i+1; j<4; ++j,k+=1)
       dihedral_angles[k] = std::acos(n[i]*n[j] / n[i].norm() / n[j].norm()); // return value is between 0 and PI
   // Return max/min dihedral angles
   return std::make_pair(*std::min_element(dihedral_angles, dihedral_angles+6),
                         *std::max_element(dihedral_angles, dihedral_angles+6));
 }
unsigned int libMesh::Elem::min_new_p_level_by_neighbor (const Elem * neighbor, unsigned int current_min) const inherited
Returns
The minimum new p-refinement level (i.e. after refinement and coarsening is done) of elements which are descended from this element and which share a side with the active neighbor.
Definition at line 2063 of file elem.C.
References libMesh::Elem::active(), libMesh::Elem::child_ptr(), libMesh::Elem::COARSEN, libMesh::Elem::has_neighbor(), libMesh::libmesh_assert(), std::min(), libMesh::Elem::min_new_p_level_by_neighbor(), libMesh::Elem::n_children(), libMesh::Elem::p_level(), libMesh::Elem::p_refinement_flag(), libMesh::Elem::REFINE, libMesh::remote_elem, and libMesh::Elem::subactive().
Referenced by libMesh::MeshRefinement::eliminate_unrefined_patches(), and libMesh::Elem::min_new_p_level_by_neighbor().
 {
   libmesh_assert(!this->subactive());
   libmesh_assert(neighbor_in->active());
   // If we're an active element this is simple
   if (this->active())
     {
       unsigned int new_p_level = this->p_level();
       if (this->p_refinement_flag() == Elem::REFINE)
         new_p_level += 1;
       if (this->p_refinement_flag() == Elem::COARSEN)
         {
           libmesh_assert_greater (new_p_level, 0);
           new_p_level -= 1;
         }
       return std::min(current_min, new_p_level);
     }
   libmesh_assert(has_neighbor(neighbor_in));
   unsigned int min_p_level = current_min;
   for (unsigned int c=0; c<this->n_children(); c++)
     {
       const Elem * const current_child = this->child_ptr(c);
       if (current_child && current_child != remote_elem)
         if (current_child->has_neighbor(neighbor_in))
           min_p_level =
             current_child->min_new_p_level_by_neighbor(neighbor_in,
                                                        min_p_level);
     }
   return min_p_level;
 }
unsigned int libMesh::Elem::min_p_level_by_neighbor (const Elem * neighbor, unsigned int current_min) const inherited
Returns
The minimum p-refinement level of elements which are descended from this element, and which share a side with the active neighbor.
Definition at line 2030 of file elem.C.
References libMesh::Elem::active(), libMesh::Elem::child_ptr(), libMesh::Elem::has_neighbor(), libMesh::libmesh_assert(), std::min(), libMesh::Elem::min_p_level_by_neighbor(), libMesh::Elem::n_children(), libMesh::Elem::p_level(), libMesh::remote_elem, and libMesh::Elem::subactive().
Referenced by libMesh::FEGenericBase< OutputType >::compute_periodic_constraints(), libMesh::FEGenericBase< OutputType >::compute_proj_constraints(), and libMesh::Elem::min_p_level_by_neighbor().
 {
   libmesh_assert(!this->subactive());
   libmesh_assert(neighbor_in->active());
   // If we're an active element this is simple
   if (this->active())
     return std::min(current_min, this->p_level());
   libmesh_assert(has_neighbor(neighbor_in));
   // The p_level() of an ancestor element is already the minimum
   // p_level() of its children - so if that's high enough, we don't
   // need to examine any children.
   if (current_min <= this->p_level())
     return current_min;
   unsigned int min_p_level = current_min;
   for (unsigned int c=0; c<this->n_children(); c++)
     {
       const Elem * const current_child = this->child_ptr(c);
       if (current_child != remote_elem && current_child->has_neighbor(neighbor_in))
         min_p_level =
           current_child->min_p_level_by_neighbor(neighbor_in,
                                                  min_p_level);
     }
   return min_p_level;
 }
virtual unsigned int libMesh::Tet::n_children () const inline virtual inherited
Returns
8.
Implements libMesh::Elem.
Definition at line 88 of file cell_tet.h.
References libMesh::Tet::is_edge_on_side(), libMesh::Elem::key(), libMesh::Tet::qual_bounds(), libMesh::Tet::quality(), libMesh::Real, libMesh::Elem::side(), libMesh::Tet::side_ptr(), and libMesh::Tet::which_node_am_i().
Referenced by libMesh::Tet::is_child_on_side_helper().
 { return 8; }
unsigned int libMesh::DofObject::n_comp (const unsigned int s, const unsigned int var) const inline inherited
Returns
The number of components for variable var of system s associated with this DofObject. For example, the HIERARCHIC shape functions may have multiple DoFs associated with one node. Another example is the MONOMIALs, where only the elements hold the DoFs. For the different spatial directions, and orders, see FE.
Definition at line 772 of file dof_object.h.
References libMesh::DofObject::n_comp_group(), libMesh::DofObject::n_systems(), libMesh::DofObject::n_vars(), and libMesh::DofObject::var_to_vg().
Referenced by libMesh::DofMap::_dof_indices(), libMesh::DofMap::allgather_recursive_constraints(), libMesh::FEGenericBase< OutputType >::compute_periodic_constraints(), libMesh::DofMap::constrain_p_dofs(), libMesh::ExodusII_IO::copy_elemental_solution(), libMesh::ExodusII_IO::copy_nodal_solution(), libMesh::DofMap::distribute_dofs(), libMesh::DofMap::distribute_local_dofs_node_major(), libMesh::DofMap::dof_indices(), libMesh::DofObject::dof_number(), libMesh::DofObject::DofObject(), libMesh::OldSolutionValue< Output, point_output >::eval_at_node(), libMesh::Node::get_info(), libMesh::Elem::get_info(), libMesh::DofMap::local_variable_indices(), libMesh::DofObject::n_dofs(), libMesh::DofMap::old_dof_indices(), libMesh::BuildProjectionList::operator()(), libMesh::DofObject::operator=(), libMesh::DofObject::print_dof_info(), libMesh::DofObject::set_dof_number(), libMesh::DofObject::set_id(), libMesh::DofObject::set_n_vars_per_group(), libMesh::DofMap::set_nonlocal_dof_objects(), and libMesh::System::zero_variable().
 {
   libmesh_assert_less (s,   this->n_systems());
   libmesh_assert_less (var, this->n_vars(s));
   return this->n_comp_group(s,this->var_to_vg(s,var));
 }
unsigned int libMesh::DofObject::n_comp_group (const unsigned int s, const unsigned int vg) const inline inherited
Returns
The number of components for VariableGroup vg of system s associated with this DofObject. For example, the HIERARCHIC shape functions may have multiple DoFs associated with one node. Another example is the MONOMIALs, where only the elements hold the DoFs. For the different spatial directions, and orders, see FE.
Definition at line 785 of file dof_object.h.
References libMesh::DofObject::_idx_buf, libMesh::DofObject::n_systems(), libMesh::DofObject::n_var_groups(), libMesh::DofObject::ncv_magic, and libMesh::DofObject::start_idx().
Referenced by libMesh::DofMap::distribute_local_dofs_node_major(), libMesh::DofMap::distribute_local_dofs_var_major(), libMesh::DofObject::dof_number(), libMesh::DofObject::invalidate_dofs(), libMesh::DofObject::n_comp(), libMesh::DofMap::reinit(), libMesh::DofObject::set_dof_number(), libMesh::DofObject::set_id(), libMesh::DofObject::set_n_comp_group(), libMesh::DofObject::set_n_vars_per_group(), and libMesh::DofMap::set_nonlocal_dof_objects().
 {
   libmesh_assert_less (s,  this->n_systems());
   libmesh_assert_less (vg, this->n_var_groups(s));
   const unsigned int
     start_idx_sys = this->start_idx(s);
   libmesh_assert_less ((start_idx_sys + 2*vg), _idx_buf.size());
   return (_idx_buf[start_idx_sys + 2*vg] % ncv_magic);
 }
unsigned int libMesh::DofObject::n_dofs (const unsigned int s, const unsigned int var = libMesh::invalid_uint) const inline inherited
Returns
The number of degrees of freedom associated with system s for this object. Optionally only counts degrees of freedom for variable number var
Definition at line 602 of file dof_object.h.
References libMesh::invalid_uint, libMesh::DofObject::n_comp(), libMesh::DofObject::n_systems(), and libMesh::DofObject::n_vars().
Referenced by libMesh::EquationSystems::build_parallel_solution_vector().
 {
   libmesh_assert_less (s, this->n_systems());
   unsigned int num = 0;
   // Count all variables
   if (var == libMesh::invalid_uint)
     for (unsigned int v=0; v<this->n_vars(s); v++)
       num += this->n_comp(s,v);
   // Only count specified variable
   else
     num = this->n_comp(s,var);
   return num;
 }
virtual unsigned int libMesh::Tet::n_edges () const inline virtual inherited
Returns
6. All tetrahedrals have 6 edges.
Implements libMesh::Elem.
Definition at line 78 of file cell_tet.h.
Referenced by build_edge_ptr(), libMesh::Tet10::build_edge_ptr(), libMesh::Tet::is_edge_on_side(), is_node_on_edge(), and libMesh::Tet10::is_node_on_edge().
 { return 6; }
virtual unsigned int libMesh::Tet::n_faces () const inline virtual inherited
Returns
4. All tetrahedrals have 4 faces.
Implements libMesh::Elem.
Definition at line 83 of file cell_tet.h.
 { return 4; }
virtual unsigned int libMesh::Elem::n_neighbors () const inline virtual inherited
Returns
The number of neighbors the element that has been derived from this class has.
By default, only face (or edge in 2D) neighbors are stored, so this method returns n_sides(), however it may be overridden in a derived class.
Definition at line 557 of file elem.h.
References libMesh::Elem::n_edges(), libMesh::Elem::n_sides(), and libMesh::Elem::n_vertices().
Referenced by libMesh::Elem::_last_side(), libMesh::ParmetisPartitioner::build_graph(), libMesh::InfElemBuilder::build_inf_elem(), libMesh::TetGenMeshInterface::check_hull_integrity(), libMesh::Elem::child_neighbor(), libMesh::Nemesis_IO_Helper::compute_internal_and_border_elems_and_internal_nodes(), libMesh::FEGenericBase< OutputType >::compute_proj_constraints(), libMesh::UnstructuredMesh::copy_nodes_and_elements(), libMesh::MeshRefinement::eliminate_unrefined_patches(), libMesh::JumpErrorEstimator::estimate_error(), libMesh::MeshTools::find_boundary_nodes(), libMesh::MeshTools::find_hanging_nodes_and_parents(), libMesh::UnstructuredMesh::find_neighbors(), libMesh::Tri3Subdivision::get_ordered_valence(), libMesh::Elem::has_neighbor(), libMesh::Elem::has_topological_neighbor(), libMesh::LaplaceMeshSmoother::init(), libMesh::MeshTools::libmesh_assert_no_links_to_elem(), libMesh::MeshTools::libmesh_assert_valid_neighbors(), libMesh::Elem::libmesh_assert_valid_neighbors(), libMesh::MeshTools::libmesh_assert_valid_node_pointers(), libMesh::MeshTools::libmesh_assert_valid_remote_elems(), libMesh::MeshRefinement::make_coarsening_compatible(), libMesh::Elem::make_links_to_me_remote(), libMesh::MeshCommunication::make_p_levels_parallel_consistent(), libMesh::Elem::neighbor_ptr(), libMesh::Elem::nullify_neighbors(), libMesh::Parallel::Packing< const Elem * >::pack(), libMesh::Parallel::Packing< const Elem * >::packable_size(), libMesh::MetisPartitioner::partition_range(), libMesh::Elem::remove_links_to_me(), libMesh::Elem::set_neighbor(), libMesh::MeshTools::Modification::smooth(), libMesh::ReplicatedMesh::stitching_helper(), libMesh::MeshRefinement::test_level_one(), libMesh::Elem::topological_neighbor(), libMesh::Parallel::Packing< Elem * >::unpack(), libMesh::Elem::which_neighbor_am_i(), and libMesh::CheckpointIO::write_remote_elem().
   { return this->n_sides(); }
virtual unsigned int libMesh::Tet4::n_nodes () const inline virtual
Returns
4.
Implements libMesh::Elem.
Definition at line 71 of file cell_tet4.h.
 { return 4; }
virtual unsigned int libMesh::Elem::n_nodes_in_child (unsigned int) const inline virtual inherited
Returns
The number of nodes the given child of this element contains. Except in odd cases like pyramid refinement this will be the same as the number of nodes in the parent element.
Definition at line 533 of file elem.h.
References libMesh::Elem::n_nodes().
Referenced by libMesh::Elem::as_parent_node(), libMesh::Elem::bracketing_nodes(), libMesh::TopologyMap::fill(), and libMesh::Elem::parent_bracketing_nodes().
   { return this->n_nodes(); }
static unsigned int libMesh::ReferenceCounter::n_objects () inline static inherited
Prints the number of outstanding (created, but not yet destroyed) objects.
Definition at line 85 of file reference_counter.h.
References libMesh::ReferenceCounter::_n_objects, libMesh::ReferenceCounter::disable_print_counter_info(), libMesh::ReferenceCounter::enable_print_counter_info(), libMesh::ReferenceCounter::increment_constructor_count(), libMesh::ReferenceCounter::increment_destructor_count(), and libMesh::Quality::name().
Referenced by libMesh::System::hide_output(), and libMesh::LibMeshInit::LibMeshInit().
   { return _n_objects; }
static unsigned int libMesh::ReferenceCounter::n_objects () inline static inherited
Prints the number of outstanding (created, but not yet destroyed) objects.
Definition at line 85 of file reference_counter.h.
References libMesh::ReferenceCounter::_n_objects, libMesh::ReferenceCounter::disable_print_counter_info(), libMesh::ReferenceCounter::enable_print_counter_info(), libMesh::ReferenceCounter::increment_constructor_count(), libMesh::ReferenceCounter::increment_destructor_count(), and libMesh::Quality::name().
Referenced by libMesh::System::hide_output(), and libMesh::LibMeshInit::LibMeshInit().
   { return _n_objects; }
unsigned int libMesh::Elem::n_second_order_adjacent_vertices (const unsigned int n) const virtual inherited
Returns
The number of adjacent vertices that uniquely define the location of the second-order node, or 0 for linear elements.
This method is useful when converting linear elements to quadratic elements.
Note
n has to be greater than or equal to this->n_vertices().
Reimplemented in libMesh::InfHex18, libMesh::Pyramid14, libMesh::Hex27, libMesh::Prism18, libMesh::InfHex16, libMesh::Pyramid13, libMesh::Hex20, libMesh::Prism15, libMesh::Tet10, libMesh::Quad9, libMesh::InfPrism12, libMesh::InfQuad6, libMesh::Quad8, libMesh::Tri6, libMesh::Edge4, and libMesh::Edge3.
Definition at line 2720 of file elem.C.
Referenced by libMesh::Elem::is_linear(), libMesh::LaplaceMeshSmoother::smooth(), and libMesh::MeshTools::Modification::smooth().
 {
   // for linear elements, always return 0
   return 0;
 }
virtual unsigned int libMesh::Tet::n_sides () const inline virtual inherited
Returns
4.
Implements libMesh::Elem.
Definition at line 68 of file cell_tet.h.
Referenced by build_side_ptr(), libMesh::Tet10::build_side_ptr(), libMesh::Tet::is_child_on_side_helper(), libMesh::Tet::is_edge_on_side(), is_node_on_side(), libMesh::Tet10::is_node_on_side(), libMesh::Tet::key(), libMesh::Tet::side_ptr(), libMesh::Tet::which_node_am_i(), and libMesh::Tet10::which_node_am_i().
 { return 4; }
virtual unsigned int libMesh::Tet4::n_sub_elem () const inline virtual
Returns
1.
Implements libMesh::Elem.
Definition at line 76 of file cell_tet4.h.
References is_child_on_side(), is_edge(), is_face(), is_node_on_edge(), is_node_on_side(), and is_vertex().
Referenced by connectivity().
 { return 1; }
unsigned int libMesh::DofObject::n_systems () const inline inherited
Returns
The number of systems associated with this DofObject
Definition at line 718 of file dof_object.h.
References libMesh::DofObject::_idx_buf.
Referenced by libMesh::DofMap::_dof_indices(), libMesh::DofObject::add_system(), libMesh::DofObject::clear_dofs(), libMesh::DofObject::dof_number(), libMesh::DofObject::DofObject(), libMesh::DofObject::end_idx(), libMesh::Node::get_info(), libMesh::Elem::get_info(), libMesh::DofObject::has_dofs(), libMesh::DofObject::invalidate_dofs(), libMesh::MeshTools::libmesh_assert_equal_n_systems(), libMesh::DofObject::n_comp(), libMesh::DofObject::n_comp_group(), libMesh::DofObject::n_dofs(), libMesh::DofObject::n_var_groups(), libMesh::DofObject::n_vars(), libMesh::DofMap::old_dof_indices(), libMesh::DofObject::operator=(), libMesh::DofObject::print_dof_info(), libMesh::Elem::refine(), libMesh::DofObject::set_dof_number(), libMesh::DofObject::set_id(), libMesh::DofObject::set_n_comp(), libMesh::DofObject::set_n_comp_group(), libMesh::DofObject::set_n_systems(), libMesh::DofObject::set_n_vars_per_group(), libMesh::DofObject::set_vg_dof_base(), libMesh::DofObject::start_idx(), and libMesh::DofObject::vg_dof_base().
 {
   return _idx_buf.empty() ?
     0 : cast_int<unsigned int>(_idx_buf[0]);
 }
unsigned int libMesh::DofObject::n_var_groups (const unsigned int s) const inline inherited
Returns
The number of VariableGroup variable groups associated with system s for this DofObject
Definition at line 727 of file dof_object.h.
References libMesh::DofObject::end_idx(), libMesh::DofObject::n_systems(), and libMesh::DofObject::start_idx().
Referenced by libMesh::DofObject::add_system(), libMesh::DofMap::distribute_local_dofs_node_major(), libMesh::DofMap::distribute_local_dofs_var_major(), libMesh::DofObject::DofObject(), libMesh::DofObject::invalidate_dofs(), libMesh::DofObject::n_comp_group(), libMesh::DofObject::n_vars(), libMesh::DofObject::operator=(), libMesh::DofObject::set_id(), libMesh::DofObject::set_n_comp_group(), libMesh::DofObject::set_n_systems(), libMesh::DofObject::set_n_vars_per_group(), libMesh::DofMap::set_nonlocal_dof_objects(), libMesh::DofObject::set_vg_dof_base(), libMesh::DofObject::var_to_vg(), and libMesh::DofObject::vg_dof_base().
 {
   libmesh_assert_less (s, this->n_systems());
   return (this->end_idx(s) - this->start_idx(s)) / 2;
 }
unsigned int libMesh::DofObject::n_vars (const unsigned int s, const unsigned int vg) const inline inherited
Returns
The number of Variable variables associated with VariableGroup vg in system s for this DofObject
Definition at line 737 of file dof_object.h.
References libMesh::DofObject::_idx_buf, libMesh::DofObject::n_systems(), libMesh::DofObject::n_var_groups(), libMesh::DofObject::ncv_magic_exp, and libMesh::DofObject::start_idx().
Referenced by libMesh::DofObject::add_system(), libMesh::DofMap::allgather_recursive_constraints(), libMesh::DofMap::distribute_dofs(), libMesh::DofObject::dof_number(), libMesh::DofObject::DofObject(), libMesh::OldSolutionValue< Output, point_output >::eval_at_node(), libMesh::Node::get_info(), libMesh::Elem::get_info(), libMesh::DofObject::has_dofs(), libMesh::DofObject::n_comp(), libMesh::DofObject::n_dofs(), libMesh::DofObject::n_vars(), libMesh::BuildProjectionList::operator()(), libMesh::DofObject::operator=(), libMesh::DofObject::print_dof_info(), libMesh::DofObject::set_dof_number(), libMesh::DofObject::set_id(), libMesh::DofObject::set_n_comp(), libMesh::DofObject::set_n_comp_group(), libMesh::DofObject::set_n_systems(), libMesh::DofObject::set_n_vars_per_group(), libMesh::DofMap::set_nonlocal_dof_objects(), libMesh::DofObject::system_var_to_vg_var(), and libMesh::DofObject::var_to_vg().
 {
   libmesh_assert_less (s,  this->n_systems());
   libmesh_assert_less (vg, this->n_var_groups(s));
   const unsigned int start_idx_sys = this->start_idx(s);
   libmesh_assert_less ((start_idx_sys + 2*vg), _idx_buf.size());
   return (cast_int<unsigned int>
           (_idx_buf[start_idx_sys + 2*vg]) >> ncv_magic_exp);
 }
unsigned int libMesh::DofObject::n_vars (const unsigned int s) const inline inherited
Returns
The number of Variable variables associated with system s for this DofObject
Definition at line 754 of file dof_object.h.
References libMesh::DofObject::n_systems(), libMesh::DofObject::n_var_groups(), and libMesh::DofObject::n_vars().
 {
   libmesh_assert_less (s, this->n_systems());
   const unsigned int nvg = this->n_var_groups(s);
   unsigned int val=0;
   for (unsigned int vg=0; vg<nvg; vg++)
     val += this->n_vars(s,vg);
   return val;
 }
virtual unsigned int libMesh::Tet::n_vertices () const inline virtual inherited
Returns
4. All tetrahedrals have 4 vertices.
Implements libMesh::Elem.
Definition at line 73 of file cell_tet.h.
Referenced by libMesh::Tet10::second_order_adjacent_vertex(), and libMesh::Tet10::second_order_child_vertex().
 { return 4; }
Elem * libMesh::Elem::neighbor (const unsigned int i) const inline inherited
Deprecated:
Use the const-correct neighbor_ptr() function instead.
Definition at line 1835 of file elem.h.
References libMesh::Elem::neighbor_ptr().
Referenced by libMesh::UnstructuredMesh::all_first_order(), libMesh::InfElemBuilder::build_inf_elem(), libMesh::TetGenMeshInterface::check_hull_integrity(), libMesh::UnstructuredMesh::find_neighbors(), libMesh::MeshCommunication::make_p_levels_parallel_consistent(), and libMesh::Elem::remove_links_to_me().
 {
   // Support the deprecated interface by calling the new,
   // const-correct interface and casting the result to an Elem *.
   libmesh_deprecated();
   return const_cast<Elem *>(this->neighbor_ptr(i));
 }
const Elem * libMesh::Elem::neighbor_ptr (unsigned int i) const inline inherited
Returns
A const pointer to the neighbor of this element, or NULL if MeshBase::find_neighbors() has not been called.
Note
If MeshBase::find_neighbors() has been called and this function still returns NULL, then the side is on a boundary of the domain.
Definition at line 1815 of file elem.h.
References libMesh::Elem::_elemlinks, and libMesh::Elem::n_neighbors().
Referenced by libMesh::BoundaryInfo::_find_id_maps(), libMesh::MeshTools::Subdivision::add_boundary_ghosts(), libMesh::BoundaryInfo::add_elements(), libMesh::UnstructuredMesh::all_first_order(), libMesh::UnstructuredMesh::all_second_order(), libMesh::MeshTools::Modification::all_tri(), libMesh::BoundaryInfo::boundary_ids(), libMesh::MeshTools::Generation::build_delaunay_square(), libMesh::MeshTools::Generation::build_extrusion(), libMesh::ParmetisPartitioner::build_graph(), libMesh::MeshTools::Generation::build_sphere(), libMesh::Elem::child_neighbor(), libMesh::Nemesis_IO_Helper::compute_internal_and_border_elems_and_internal_nodes(), libMesh::FEAbstract::compute_node_constraints(), libMesh::FEGenericBase< OutputType >::compute_periodic_constraints(), libMesh::FEAbstract::compute_periodic_node_constraints(), libMesh::FEGenericBase< OutputType >::compute_proj_constraints(), libMesh::UnstructuredMesh::copy_nodes_and_elements(), libMesh::BoundaryInfo::edge_boundary_ids(), libMesh::MeshRefinement::eliminate_unrefined_patches(), libMesh::JumpErrorEstimator::estimate_error(), libMesh::Elem::family_tree_by_subneighbor(), libMesh::MeshTools::find_boundary_nodes(), libMesh::Elem::find_edge_neighbors(), libMesh::Patch::find_face_neighbors(), libMesh::MeshTools::find_hanging_nodes_and_parents(), libMesh::UnstructuredMesh::find_neighbors(), libMesh::MeshTools::Subdivision::find_one_ring(), libMesh::Elem::find_point_neighbors(), libMesh::MeshTools::Modification::flatten(), libMesh::MeshCommunication::gather_neighboring_elements(), libMesh::Elem::get_info(), libMesh::Elem::has_neighbor(), libMesh::LaplaceMeshSmoother::init(), libMesh::MeshTools::libmesh_assert_no_links_to_elem(), libMesh::MeshTools::libmesh_assert_valid_neighbors(), libMesh::Elem::libmesh_assert_valid_neighbors(), libMesh::MeshTools::libmesh_assert_valid_node_pointers(), libMesh::MeshTools::libmesh_assert_valid_remote_elems(), libMesh::Elem::make_links_to_me_local(), libMesh::Elem::make_links_to_me_remote(), libMesh::Elem::neighbor(), libMesh::Elem::nullify_neighbors(), libMesh::GhostPointNeighbors::operator()(), libMesh::DefaultCoupling::operator()(), libMesh::Parallel::Packing< const Elem * >::pack(), libMesh::MetisPartitioner::partition_range(), libMesh::FE< Dim, T >::reinit(), libMesh::Elem::remove_links_to_me(), libMesh::FE< Dim, T >::side_map(), libMesh::BoundaryInfo::side_with_boundary_id(), libMesh::MeshTools::Modification::smooth(), libMesh::ReplicatedMesh::stitching_helper(), libMesh::MeshTools::Subdivision::tag_boundary_ghosts(), libMesh::Elem::topological_neighbor(), libMesh::MeshRefinement::topological_neighbor(), libMesh::Elem::total_family_tree_by_subneighbor(), libMesh::Parallel::Packing< Elem * >::unpack(), libMesh::Elem::which_neighbor_am_i(), libMesh::CheckpointIO::write_remote_elem(), and libMesh::GnuPlotIO::write_solution().
 {
   libmesh_assert_less (i, this->n_neighbors());
   return _elemlinks[i+1];
 }
Elem * libMesh::Elem::neighbor_ptr (unsigned int i) inline inherited
Returns
A non-const pointer to the neighbor of this element.
Definition at line 1825 of file elem.h.
References libMesh::Elem::_elemlinks, and libMesh::Elem::n_neighbors().
 {
   libmesh_assert_less (i, this->n_neighbors());
   return _elemlinks[i+1];
 }
dof_id_type libMesh::Elem::node (const unsigned int i) const inline inherited
Returns
The global id number of local Node i.
Deprecated:
Use the less ambiguously named node_id() instead.
Definition at line 1695 of file elem.h.
References libMesh::Elem::node_id().
Referenced by libMesh::Elem::refine().
 {
   libmesh_deprecated();
   return this->node_id(i);
 }
dof_id_type libMesh::Elem::node_id (const unsigned int i) const inline inherited
Returns
The global id number of local Node i.
Definition at line 1683 of file elem.h.
References libMesh::Elem::_nodes, libMesh::DofObject::id(), libMesh::DofObject::invalid_id, libMesh::libmesh_assert(), and libMesh::Elem::n_nodes().
Referenced by libMesh::MeshTools::Subdivision::add_boundary_ghosts(), libMesh::UnstructuredMesh::all_first_order(), libMesh::MeshTools::Modification::all_tri(), libMesh::DofMap::allgather_recursive_constraints(), libMesh::Elem::bracketing_nodes(), libMesh::Nemesis_IO_Helper::build_element_and_node_maps(), libMesh::EquationSystems::build_parallel_solution_vector(), libMesh::VTKIO::cells_to_vtk(), libMesh::Nemesis_IO_Helper::compute_border_node_ids(), libMesh::FEMap::compute_face_map(), libMesh::Nemesis_IO_Helper::compute_internal_and_border_elems_and_internal_nodes(), libMesh::Quad4::connectivity(), libMesh::InfEdge2::connectivity(), libMesh::Edge2::connectivity(), libMesh::InfQuad4::connectivity(), libMesh::Edge3::connectivity(), libMesh::Edge4::connectivity(), libMesh::Pyramid5::connectivity(), libMesh::Prism6::connectivity(), libMesh::Tri3::connectivity(), libMesh::Hex8::connectivity(), libMesh::InfHex8::connectivity(), libMesh::InfPrism6::connectivity(), libMesh::Tri6::connectivity(), libMesh::Quad8::connectivity(), libMesh::InfQuad6::connectivity(), connectivity(), libMesh::InfPrism12::connectivity(), libMesh::Quad9::connectivity(), libMesh::Tet10::connectivity(), libMesh::Hex20::connectivity(), libMesh::Prism15::connectivity(), libMesh::InfHex16::connectivity(), libMesh::Hex27::connectivity(), libMesh::Prism18::connectivity(), libMesh::InfHex18::connectivity(), libMesh::UnstructuredMesh::copy_nodes_and_elements(), libMesh::UnstructuredMesh::create_submesh(), libMesh::MeshBase::detect_interior_parents(), libMesh::MeshTools::find_hanging_nodes_and_parents(), libMesh::MeshTools::find_nodal_neighbors(), libMesh::MeshCommunication::gather_neighboring_elements(), libMesh::MeshTools::get_not_subactive_node_ids(), libMesh::Tri3Subdivision::get_ordered_node(), libMesh::BoundaryInfo::get_side_and_node_maps(), libMesh::Tri3Subdivision::is_subdivision_updated(), libMesh::Tet::key(), libMesh::Prism::key(), libMesh::Tri::key(), libMesh::Pyramid::key(), libMesh::Hex::key(), libMesh::Edge::key(), libMesh::InfQuad6::key(), libMesh::InfPrism::key(), libMesh::Quad8::key(), libMesh::Quad9::key(), libMesh::Tri6::key(), libMesh::InfHex::key(), libMesh::Quad::key(), libMesh::InfQuad::key(), libMesh::Hex27::key(), libMesh::Edge2::key(), libMesh::Prism18::key(), libMesh::Pyramid14::key(), libMesh::InfHex18::key(), libMesh::Edge4::key(), libMesh::Edge3::key(), key(), libMesh::Elem::key(), libMesh::MeshRefinement::limit_level_mismatch_at_node(), libMesh::Elem::local_node(), libMesh::Tri3Subdivision::local_node_number(), libMesh::Elem::node(), libMesh::Elem::operator==(), libMesh::Parallel::Packing< const Elem * >::pack(), libMesh::XdrIO::pack_element(), libMesh::CheckpointIO::read_connectivity(), libMesh::GmshIO::read_mesh(), libMesh::VariationalMeshSmoother::readgr(), libMesh::ReplicatedMesh::renumber_nodes_and_elements(), libMesh::DistributedMesh::renumber_nodes_and_elements(), libMesh::FE< Dim, T >::side_map(), libMesh::LaplaceMeshSmoother::smooth(), libMesh::ReplicatedMesh::stitching_helper(), libMesh::BoundaryInfo::sync(), libMesh::TetGenMeshInterface::triangulate_conformingDelaunayMesh_carvehole(), libMesh::Parallel::Packing< Elem * >::unpack(), libMesh::GMVIO::write_ascii_new_impl(), libMesh::GMVIO::write_binary(), libMesh::CheckpointIO::write_connectivity(), libMesh::Elem::write_connectivity(), libMesh::ExodusII_IO_Helper::write_elements(), libMesh::EnsightIO::write_geometry_ascii(), libMesh::GmshIO::write_mesh(), libMesh::GmshIO::write_post(), libMesh::EnsightIO::write_scalar_ascii(), libMesh::GnuPlotIO::write_solution(), and libMesh::EnsightIO::write_vector_ascii().
 {
   libmesh_assert_less (i, this->n_nodes());
   libmesh_assert(_nodes[i]);
   libmesh_assert_not_equal_to (_nodes[i]->id(), Node::invalid_id);
   return _nodes[i]->id();
 }
const Node * libMesh::Elem::node_ptr (const unsigned int i) const inline inherited
Returns
A const pointer to local Node i.
Definition at line 1724 of file elem.h.
References libMesh::Elem::_nodes, libMesh::libmesh_assert(), and libMesh::Elem::n_nodes().
Referenced by libMesh::MeshTools::Subdivision::add_boundary_ghosts(), libMesh::BoundaryInfo::add_elements(), libMesh::MeshRefinement::add_node(), libMesh::UnstructuredMesh::all_first_order(), libMesh::UnstructuredMesh::all_second_order(), libMesh::MeshTools::Modification::all_tri(), libMesh::DofMap::allgather_recursive_constraints(), libMesh::MeshTools::Generation::build_cube(), libMesh::MeshTools::Generation::build_extrusion(), libMesh::EquationSystems::build_parallel_solution_vector(), libMesh::Quad4::build_side_ptr(), libMesh::Prism6::build_side_ptr(), libMesh::Pyramid5::build_side_ptr(), libMesh::InfQuad4::build_side_ptr(), libMesh::Hex8::build_side_ptr(), libMesh::Tri3::build_side_ptr(), libMesh::InfHex8::build_side_ptr(), libMesh::InfPrism6::build_side_ptr(), libMesh::InfPrism12::build_side_ptr(), build_side_ptr(), libMesh::InfHex18::build_side_ptr(), libMesh::Quad8::build_side_ptr(), libMesh::Tri6::build_side_ptr(), libMesh::InfQuad6::build_side_ptr(), libMesh::Tet10::build_side_ptr(), libMesh::Hex20::build_side_ptr(), libMesh::InfHex16::build_side_ptr(), libMesh::Pyramid13::build_side_ptr(), libMesh::Edge::build_side_ptr(), libMesh::Prism15::build_side_ptr(), libMesh::Quad9::build_side_ptr(), libMesh::Hex27::build_side_ptr(), libMesh::Prism18::build_side_ptr(), libMesh::Pyramid14::build_side_ptr(), libMesh::FEMap::compute_affine_map(), libMesh::FEMap::compute_map(), libMesh::FEGenericBase< OutputType >::compute_periodic_constraints(), libMesh::UnstructuredMesh::create_submesh(), libMesh::UNVIO::elements_out(), libMesh::MeshTools::find_nodal_neighbors(), libMesh::MeshTools::Subdivision::find_one_ring(), libMesh::MeshTools::Modification::flatten(), libMesh::MeshCommunication::gather_neighboring_elements(), libMesh::Elem::get_node(), libMesh::Elem::is_vertex_on_parent(), libMesh::MeshTools::libmesh_assert_connected_nodes(), libMesh::MeshTools::libmesh_assert_valid_boundary_ids(), libMesh::Elem::libmesh_assert_valid_node_pointers(), libMesh::PointLocatorBase::locate_node(), libMesh::Elem::node_ref(), libMesh::DofMap::old_dof_indices(), libMesh::GhostPointNeighbors::operator()(), libMesh::BuildProjectionList::operator()(), libMesh::Tri3Subdivision::prepare_subdivision_properties(), libMesh::reconnect_nodes(), libMesh::ReplicatedMesh::renumber_nodes_and_elements(), libMesh::MeshCommunication::send_coarse_ghosts(), libMesh::Partitioner::set_node_processor_ids(), libMesh::Tet::side_ptr(), libMesh::Prism::side_ptr(), libMesh::Pyramid::side_ptr(), libMesh::Hex::side_ptr(), libMesh::Tri::side_ptr(), libMesh::Edge::side_ptr(), libMesh::InfPrism::side_ptr(), libMesh::InfHex::side_ptr(), libMesh::Quad::side_ptr(), libMesh::InfQuad::side_ptr(), libMesh::Partitioner::single_partition_range(), libMesh::MeshTools::Modification::smooth(), and libMesh::ReplicatedMesh::stitching_helper().
 {
   libmesh_assert_less (i, this->n_nodes());
   libmesh_assert(_nodes[i]);
   return _nodes[i];
 }
Node * libMesh::Elem::node_ptr (const unsigned int i) inline inherited
Returns
A non-const pointer to local Node i.
Definition at line 1735 of file elem.h.
References libMesh::Elem::_nodes, libMesh::libmesh_assert(), and libMesh::Elem::n_nodes().
 {
   libmesh_assert_less (i, this->n_nodes());
   libmesh_assert(_nodes[i]);
   return _nodes[i];
 }
const Node & libMesh::Elem::node_ref (const unsigned int i) const inline inherited
Returns
A const reference to local Node i.
Definition at line 1746 of file elem.h.
References libMesh::Elem::node_ptr().
Referenced by libMesh::DofMap::allgather_recursive_constraints(), libMesh::FEGenericBase< OutputType >::compute_periodic_constraints(), libMesh::DofMap::constrain_p_dofs(), libMesh::MeshTools::correct_node_proc_ids(), libMesh::DofMap::distribute_local_dofs_node_major(), libMesh::DofMap::distribute_local_dofs_var_major(), libMesh::AdjointRefinementEstimator::estimate_error(), libMesh::TopologyMap::fill(), libMesh::Elem::get_info(), libMesh::MeshTools::libmesh_assert_old_dof_objects(), libMesh::MeshTools::libmesh_assert_parallel_consistent_procids< Node >(), libMesh::MeshTools::libmesh_assert_topology_consistent_procids< Node >(), libMesh::DofMap::local_variable_indices(), libMesh::GenericProjector< FFunctor, GFunctor, FValue, ProjectionAction >::operator()(), libMesh::DofMap::reinit(), libMesh::HPCoarsenTest::select_refinement(), and libMesh::Parallel::sync_node_data_by_element_id().
 {
   return *this->node_ptr(i);
 }
Node & libMesh::Elem::node_ref (const unsigned int i) inline inherited
Returns
A writable reference to local Node i.
Definition at line 1754 of file elem.h.
References libMesh::Elem::node_ptr().
 {
   return *this->node_ptr(i);
 }
void libMesh::Elem::nullify_neighbors () inherited
Replaces this element with NULL for all of its neighbors. This is useful when deleting an element.
Definition at line 2694 of file elem.C.
References libMesh::Elem::level(), libmesh_nullptr, libMesh::Elem::n_neighbors(), libMesh::Elem::neighbor_ptr(), libMesh::remote_elem, libMesh::Elem::set_neighbor(), and libMesh::Elem::which_neighbor_am_i().
Referenced by libMesh::MeshRefinement::_coarsen_elements(), and libMesh::Elem::_get_parent_indices_cache().
 {
   // Tell any of my neighbors about my death...
   // Looks strange, huh?
   for (unsigned int n=0; n<this->n_neighbors(); n++)
     {
       Elem * current_neighbor = this->neighbor_ptr(n);
       if (current_neighbor && current_neighbor != remote_elem)
         {
           // Note:  it is possible that I see the neighbor
           // (which is coarser than me)
           // but they don't see me, so avoid that case.
           if (current_neighbor->level() == this->level())
             {
               const unsigned int w_n_a_i = current_neighbor->which_neighbor_am_i(this);
               libmesh_assert_less (w_n_a_i, current_neighbor->n_neighbors());
               current_neighbor->set_neighbor(w_n_a_i, libmesh_nullptr);
               this->set_neighbor(n, libmesh_nullptr);
             }
         }
     }
 }
bool libMesh::Elem::on_boundary () const inline inherited
Returns
true if this element has a side coincident with a boundary (indicated by a NULL neighbor), false otherwise.
Definition at line 1967 of file elem.h.
References libMesh::Elem::has_neighbor(), and libmesh_nullptr.
Referenced by libMesh::MeshCommunication::gather_neighboring_elements().
 {
   // By convention, the element is on the boundary
   // if it has a NULL neighbor.
   return this->has_neighbor(libmesh_nullptr);
 }
bool libMesh::Elem::operator== (const Elem & rhs) const inherited
Returns
true if two elements are identical, false otherwise. This is true if the elements are connected to identical global nodes, regardless of how those nodes might be numbered local to the elements.
Definition at line 510 of file elem.C.
References libMesh::Elem::n_nodes(), libMesh::Elem::node_id(), and libMesh::Elem::type().
 {
   // If the elements aren't the same type, they aren't equal
   if (this->type() != rhs.type())
     return false;
   // Make two sorted vectors of global node ids and compare them for
   // equality.
   std::vector<dof_id_type>
     this_ids(this->n_nodes()),
     rhs_ids(rhs.n_nodes());
   for (unsigned n=0; n<this->n_nodes(); n++)
     {
       this_ids[n] = this->node_id(n);
       rhs_ids[n] = rhs.node_id(n);
     }
   // Sort the vectors to rule out different local node numberings.
   std::sort(this_ids.begin(), this_ids.end());
   std::sort(rhs_ids.begin(), rhs_ids.end());
   // If the node ids match, the elements are equal!
   return this_ids == rhs_ids;
 }
unsigned int libMesh::Elem::opposite_node (const unsigned int n, const unsigned int s) const virtual inherited
Returns
The local node number for the node opposite to node n on side opposite_side(s) (for a tensor product element), or throws an error otherwise.
Reimplemented in libMesh::Quad, libMesh::Edge, and libMesh::Hex.
Definition at line 3064 of file elem.C.
Referenced by libMesh::Elem::is_vertex_on_child().
 {
   // If the subclass didn't rederive this, using it is an error
   libmesh_not_implemented();
 }
unsigned int libMesh::Elem::opposite_side (const unsigned int s) const virtual inherited
Returns
The side number opposite to s (for a tensor product element), or throws an error otherwise.
Reimplemented in libMesh::Quad, libMesh::Edge, and libMesh::Hex.
Definition at line 3056 of file elem.C.
Referenced by libMesh::Elem::is_vertex_on_child().
 {
   // If the subclass didn't rederive this, using it is an error
   libmesh_not_implemented();
 }
virtual Point libMesh::Elem::origin () const inline virtual inherited
Returns
The origin for an infinite element.
Currently, all infinite elements used in a mesh share the same origin. Override this in infinite element classes.
Reimplemented in libMesh::InfQuad, libMesh::InfEdge2, and libMesh::InfCell.
Definition at line 1387 of file elem.h.
References libMesh::Elem::as_parent_node(), libMesh::Elem::bracketing_nodes(), libMesh::Elem::build(), libMesh::Elem::embedding_matrix(), libmesh_nullptr, libMesh::Elem::parent_bracketing_nodes(), and libMesh::Elem::type().
Referenced by libMesh::InfFE< Dim, T_radial, T_map >::combine_base_radial(), libMesh::InfFE< Dim, T_radial, T_map >::compute_data(), libMesh::Elem::get_info(), libMesh::InfFE< Dim, T_radial, T_map >::inverse_map(), and libMesh::InfFE< Dim, T_radial, T_map >::map().
 { libmesh_not_implemented(); return Point(); }
unsigned int libMesh::Elem::p_level () const inline inherited
Returns
The value of the p refinement level of an active element, or the minimum value of the p refinement levels of an ancestor element's descendants.
Definition at line 2218 of file elem.h.
References libMesh::Elem::_p_level.
Referenced by libMesh::MeshRefinement::_coarsen_elements(), libMesh::MeshRefinement::_refine_elements(), libMesh::UnstructuredMesh::all_first_order(), libMesh::Elem::coarsen(), libMesh::FEGenericBase< OutputType >::coarsened_dof_values(), libMesh::FEInterface::compute_data(), libMesh::FEGenericBase< OutputType >::compute_periodic_constraints(), libMesh::FEGenericBase< OutputType >::compute_proj_constraints(), libMesh::DofMap::constrain_p_dofs(), libMesh::UnstructuredMesh::copy_nodes_and_elements(), libMesh::DofMap::dof_indices(), libMesh::FE< Dim, T >::dofs_on_edge(), libMesh::FE< Dim, T >::dofs_on_side(), libMesh::FE< Dim, T >::edge_reinit(), libMesh::Elem::Elem(), libMesh::MeshRefinement::eliminate_unrefined_patches(), libMesh::MeshRefinement::enforce_mismatch_limit_prior_to_refinement(), libMesh::Elem::get_info(), libMesh::InfFE< Dim, T_radial, T_map >::init_face_shape_functions(), libMesh::Elem::is_linear(), libMesh::DistributedMesh::libmesh_assert_valid_parallel_p_levels(), libMesh::MeshTools::libmesh_assert_valid_refinement_tree(), libMesh::MeshRefinement::limit_level_mismatch_at_edge(), libMesh::MeshRefinement::limit_level_mismatch_at_node(), libMesh::MeshRefinement::limit_overrefined_boundary(), libMesh::MeshRefinement::limit_underrefined_boundary(), libMesh::MeshRefinement::make_coarsening_compatible(), libMesh::MeshRefinement::make_refinement_compatible(), libMesh::Elem::max_descendant_p_level(), libMesh::Elem::min_new_p_level_by_neighbor(), libMesh::Elem::min_p_level_by_neighbor(), libMesh::DofMap::old_dof_indices(), libMesh::GenericProjector< FFunctor, GFunctor, FValue, ProjectionAction >::operator()(), libMesh::WeightedPatchRecoveryErrorEstimator::EstimateError::operator()(), libMesh::PatchRecoveryErrorEstimator::EstimateError::operator()(), libMesh::Parallel::Packing< const Elem * >::pack(), libMesh::XdrIO::pack_element(), libMesh::Elem::refine(), libMesh::FE< Dim, T >::reinit(), libMesh::InfFE< Dim, T_radial, T_map >::reinit(), libMesh::FEXYZ< Dim >::reinit(), libMesh::DofMap::reinit(), libMesh::HPCoarsenTest::select_refinement(), libMesh::Elem::set_p_level(), libMesh::Elem::set_p_refinement_flag(), libMesh::FE< Dim, T >::shape(), libMesh::FE< Dim, T >::shape_deriv(), libMesh::FE< Dim, T >::shape_second_deriv(), libMesh::FE< Dim, T >::side_map(), libMesh::MeshRefinement::test_level_one(), libMesh::Parallel::Packing< Elem * >::unpack(), libMesh::GMVIO::write_ascii_new_impl(), libMesh::GMVIO::write_ascii_old_impl(), libMesh::GMVIO::write_binary(), and libMesh::CheckpointIO::write_connectivity().
 {
 #ifdef LIBMESH_ENABLE_AMR
   return _p_level;
 #else
   return 0;
 #endif
 }
Elem::RefinementState libMesh::Elem::p_refinement_flag () const inline inherited
Returns
The value of the p-refinement flag for the element.
Definition at line 2305 of file elem.h.
References libMesh::Elem::_pflag.
Referenced by libMesh::MeshRefinement::_coarsen_elements(), libMesh::MeshRefinement::_refine_elements(), libMesh::UnstructuredMesh::all_first_order(), libMesh::FEMContext::build_new_fe(), libMesh::UnstructuredMesh::copy_nodes_and_elements(), libMesh::MeshRefinement::eliminate_unrefined_patches(), libMesh::Elem::get_info(), libMesh::Elem::hack_p_level(), libMesh::DistributedMesh::libmesh_assert_valid_parallel_flags(), libMesh::MeshTools::libmesh_assert_valid_refinement_flags(), libMesh::MeshTools::libmesh_assert_valid_refinement_tree(), libMesh::MeshRefinement::limit_level_mismatch_at_edge(), libMesh::MeshRefinement::limit_level_mismatch_at_node(), libMesh::MeshRefinement::limit_overrefined_boundary(), libMesh::MeshRefinement::limit_underrefined_boundary(), libMesh::MeshRefinement::make_coarsening_compatible(), libMesh::MeshRefinement::make_flags_parallel_consistent(), libMesh::MeshRefinement::make_refinement_compatible(), libMesh::Elem::min_new_p_level_by_neighbor(), libMesh::DofMap::old_dof_indices(), libMesh::GenericProjector< FFunctor, GFunctor, FValue, ProjectionAction >::operator()(), libMesh::Parallel::Packing< const Elem * >::pack(), libMesh::Elem::refine(), libMesh::MeshRefinement::test_unflagged(), and libMesh::Parallel::Packing< Elem * >::unpack().
 {
   return static_cast<RefinementState>(_pflag);
 }
void libMesh::DofObject::pack_indexing (std::back_insert_iterator< std::vector< largest_id_type > > target) const inherited
A method for creating packed data from our index buffer - basically a copy with prepended size with our current implementation.
Definition at line 524 of file dof_object.C.
References libMesh::DofObject::_idx_buf, libmesh_nullptr, libMesh::DofObject::old_dof_object, and libMesh::DofObject::pack_indexing().
Referenced by libMesh::Parallel::Packing< const Node * >::pack(), libMesh::Parallel::Packing< const Elem * >::pack(), and libMesh::DofObject::pack_indexing().
 {
 #ifdef LIBMESH_ENABLE_AMR
   // We might need to pack old_dof_object too
   *target++ = (old_dof_object == libmesh_nullptr) ? 0 : 1;
 #endif
   *target++ = _idx_buf.size();
   std::copy(_idx_buf.begin(), _idx_buf.end(), target);
 #ifdef LIBMESH_ENABLE_AMR
   if (old_dof_object)
     old_dof_object->pack_indexing(target);
 #endif
 }
unsigned int libMesh::DofObject::packed_indexing_size () const inherited
If we pack our indices into an buffer for communications, how many ints do we need?
Definition at line 449 of file dof_object.C.
References libMesh::DofObject::_idx_buf, libmesh_nullptr, and libMesh::DofObject::old_dof_object.
Referenced by libMesh::Parallel::Packing< const Node * >::packable_size(), libMesh::Parallel::Packing< const Elem * >::packable_size(), libMesh::Node::packed_size(), and libMesh::Parallel::Packing< Elem * >::unpack().
 {
   return
     cast_int<unsigned int> (
 #ifdef LIBMESH_ENABLE_AMR
                             ((old_dof_object == libmesh_nullptr) ? 0 : old_dof_object->packed_indexing_size()) + 2 +
 #else
                             1 +
 #endif
                             _idx_buf.size());
 }
const Elem * libMesh::Elem::parent () const inline inherited
Returns
A const pointer to the element's parent, or NULL if the element was not created via refinement.
Definition at line 2142 of file elem.h.
References libMesh::Elem::_elemlinks.
Referenced by libMesh::UniformRefinementEstimator::_estimate_error(), libMesh::Elem::add_child(), libMesh::BoundaryInfo::add_elements(), libMesh::UnstructuredMesh::all_first_order(), libMesh::MeshTools::Modification::all_tri(), libMesh::BoundaryInfo::boundary_ids(), libMesh::MeshTools::Generation::build_extrusion(), libMesh::OldSolutionValue< Output, point_output >::check_old_context(), libMesh::Elem::child_neighbor(), libMesh::FEMap::compute_face_map(), libMesh::FEAbstract::compute_node_constraints(), libMesh::connect_families(), libMesh::UnstructuredMesh::contract(), libMesh::UnstructuredMesh::copy_nodes_and_elements(), libMesh::MeshRefinement::create_parent_error_vector(), libMesh::BoundaryInfo::edge_boundary_ids(), libMesh::Elem::Elem(), libMesh::MeshRefinement::eliminate_unrefined_patches(), libMesh::JumpErrorEstimator::estimate_error(), libMesh::AdjointRefinementEstimator::estimate_error(), libMesh::ExactErrorEstimator::estimate_error(), libMesh::Elem::family_tree_by_subneighbor(), libMesh::MeshTools::find_hanging_nodes_and_parents(), libMesh::UnstructuredMesh::find_neighbors(), libMesh::MeshRefinement::flag_elements_by_elem_fraction(), libMesh::MeshRefinement::flag_elements_by_error_fraction(), libMesh::MeshRefinement::flag_elements_by_error_tolerance(), libMesh::Elem::get_info(), libMesh::Elem::is_ancestor_of(), libMesh::Elem::is_linear(), libMesh::Elem::level(), libMesh::MeshTools::libmesh_assert_no_links_to_elem(), libMesh::MeshTools::libmesh_assert_topology_consistent_procids< Elem >(), libMesh::MeshTools::libmesh_assert_valid_amr_elem_ids(), libMesh::MeshTools::libmesh_assert_valid_amr_interior_parents(), libMesh::Elem::libmesh_assert_valid_neighbors(), libMesh::MeshTools::libmesh_assert_valid_node_pointers(), libMesh::MeshTools::libmesh_assert_valid_refinement_tree(), libMesh::MeshTools::libmesh_assert_valid_remote_elems(), libMesh::Elem::make_links_to_me_local(), libMesh::Elem::make_links_to_me_remote(), libMesh::MeshCommunication::make_p_levels_parallel_consistent(), libMesh::MeshRefinement::make_refinement_compatible(), libMesh::SiblingCoupling::operator()(), libMesh::GenericProjector< FFunctor, GFunctor, FValue, ProjectionAction >::operator()(), libMesh::BuildProjectionList::operator()(), libMesh::Parallel::Packing< const Elem * >::pack(), libMesh::BoundaryInfo::raw_boundary_ids(), libMesh::BoundaryInfo::raw_edge_boundary_ids(), libMesh::BoundaryInfo::raw_shellface_boundary_ids(), libMesh::CheckpointIO::read_connectivity(), libMesh::Elem::refine(), libMesh::Elem::remove_links_to_me(), libMesh::HPCoarsenTest::select_refinement(), libMesh::MeshCommunication::send_coarse_ghosts(), libMesh::Elem::set_p_level(), libMesh::Partitioner::set_parent_processor_ids(), libMesh::BoundaryInfo::shellface_boundary_ids(), libMesh::BoundaryInfo::side_with_boundary_id(), libMesh::MeshTools::Modification::smooth(), libMesh::Elem::subactive(), libMesh::Parallel::sync_element_data_by_parent_id(), libMesh::Elem::top_parent(), libMesh::Elem::topological_neighbor(), libMesh::Elem::total_family_tree_by_subneighbor(), libMesh::Parallel::Packing< Elem * >::unpack(), libMesh::Elem::which_neighbor_am_i(), and libMesh::CheckpointIO::write_connectivity().
 {
   return _elemlinks[0];
 }
Elem * libMesh::Elem::parent () inline inherited
Returns
A pointer to the element's parent, or NULL if the element was not created via refinement.
Definition at line 2150 of file elem.h.
References libMesh::Elem::_elemlinks.
 {
   return _elemlinks[0];
 }
const std::vector< std::pair< unsigned char, unsigned char > > & libMesh::Elem::parent_bracketing_nodes (unsigned int c, unsigned int n) const virtual inherited
Returns
All the pairs of nodes (indexed by local node id) which should bracket node n of child c.
Definition at line 2169 of file elem.C.
References libMesh::Elem::_get_bracketing_node_cache(), libMesh::TypeVector< T >::absolute_fuzzy_equals(), libMesh::TypeVector< T >::add_scaled(), libMesh::Elem::as_parent_node(), libMesh::Elem::build(), libMesh::Elem::child(), libMesh::Elem::default_order(), libMesh::Elem::embedding_matrix(), libMesh::Elem::embedding_matrix_version(), libMesh::FIRST, libMesh::invalid_uint, libMesh::Elem::is_mid_infinite_edge_node(), libMesh::Elem::is_vertex_on_child(), libMesh::libmesh_assert(), libMesh::Elem::master_point(), libMesh::Elem::n_children(), libMesh::Elem::n_nodes(), libMesh::Elem::n_nodes_in_child(), libMesh::Elem::second_order_equivalent_type(), and libMesh::Elem::type().
Referenced by libMesh::Elem::bracketing_nodes(), and libMesh::Elem::origin().
 {
   // Indexed first by embedding matrix type, then by child id, then by
   // child node, then by bracketing pair
   std::vector<std::vector<std::vector<std::vector<std::pair<unsigned char, unsigned char> > > > > &
     cached_bracketing_nodes = this->_get_bracketing_node_cache();
   const unsigned int em_vers = this->embedding_matrix_version();
   // We may be updating the cache on one thread, and while that
   // happens we can't safely access the cache from other threads.
   Threads::spin_mutex::scoped_lock lock(parent_bracketing_nodes_mutex);
   if (cached_bracketing_nodes.size() <= em_vers)
     cached_bracketing_nodes.resize(em_vers+1);
   const unsigned int nc = this->n_children();
   // If we haven't cached the bracketing nodes corresponding to this
   // embedding matrix yet, let's do so now.
   if (cached_bracketing_nodes[em_vers].size() < nc)
     {
       // If we're a second-order element but we're not a full-order
       // element, then some of our bracketing nodes may not exist
       // except on the equivalent full-order element.  Let's build an
       // equivalent full-order element and make a copy of its cache to
       // use.
       if (this->default_order() != FIRST &&
           second_order_equivalent_type(this->type(), /*full_ordered=*/ true) != this->type())
         {
           // Check that we really are the non-full-order type
           libmesh_assert_equal_to
             (second_order_equivalent_type (this->type(), false),
              this->type());
           // Build the full-order type
           ElemType full_type =
             second_order_equivalent_type(this->type(), /*full_ordered=*/ true);
           UniquePtr<Elem> full_elem = Elem::build(full_type);
           // This won't work for elements with multiple
           // embedding_matrix versions, but every such element is full
           // order anyways.
           libmesh_assert_equal_to(em_vers, 0);
           // Make sure its cache has been built.  We temporarily
           // release our mutex lock so that the inner call can
           // re-acquire it.
           lock.release();
           full_elem->parent_bracketing_nodes(0,0);
           // And then we need to lock again, so that if someone *else*
           // grabbed our lock before we did we don't risk accessing
           // cached_bracketing_nodes while they're working on it.
           // Threading is hard.
           lock.acquire(parent_bracketing_nodes_mutex);
           // Copy its cache
           cached_bracketing_nodes =
             full_elem->_get_bracketing_node_cache();
           // Now we don't need to build the cache ourselves.
           return cached_bracketing_nodes[em_vers][child][child_node];
         }
       cached_bracketing_nodes[em_vers].resize(nc);
       const unsigned int nn = this->n_nodes();
       // We have to examine each child
       for (unsigned int c = 0; c != nc; ++c)
         {
           const unsigned int ncn = this->n_nodes_in_child(c);
           cached_bracketing_nodes[em_vers][c].resize(ncn);
           // We have to examine each node in that child
           for (unsigned int n = 0; n != ncn; ++n)
             {
               // If this child node isn't a vertex or an infinite
               // child element's mid-infinite-edge node, then we need
               // to find bracketing nodes on the child.
               if (!this->is_vertex_on_child(c, n)
 #ifdef LIBMESH_ENABLE_INFINITE_ELEMENTS
                   && !this->is_mid_infinite_edge_node(n)
 #endif
                   )
                 {
                   // Use the embedding matrix to find the child node
                   // location in parent master element space
                   Point bracketed_pt;
                   for (unsigned int pn = 0; pn != nn; ++pn)
                     {
                       const float em_val =
                         this->embedding_matrix(c,n,pn);
                       libmesh_assert_not_equal_to (em_val, 1);
                       if (em_val != 0.)
                         bracketed_pt.add_scaled(this->master_point(pn), em_val);
                     }
                   // Check each pair of nodes on the child which are
                   // also both parent nodes
                   for (unsigned int n1 = 0; n1 != ncn; ++n1)
                     {
                       if (n1 == n)
                         continue;
                       unsigned int parent_n1 =
                         this->as_parent_node(c,n1);
                       if (parent_n1 == libMesh::invalid_uint)
                         continue;
                       Point p1 = this->master_point(parent_n1);
                       for (unsigned int n2 = n1+1; n2 < nn; ++n2)
{
                           if (n2 == n)
                             continue;
                           unsigned int parent_n2 =
                             this->as_parent_node(c,n2);
                           if (parent_n2 == libMesh::invalid_uint)
                             continue;
                           Point p2 = this->master_point(parent_n2);
                           Point pmid = (p1 + p2)/2;
                           if (pmid == bracketed_pt)
{
                               cached_bracketing_nodes[em_vers][c][n].push_back
                                 (std::make_pair(parent_n1,parent_n2));
                               break;
                             }
                           else
                             libmesh_assert(!pmid.absolute_fuzzy_equals(bracketed_pt));
                         }
                     }
                 }
               // If this child node is a parent node, we need to
               // find bracketing nodes on the parent.
               else
                 {
                   unsigned int parent_node = this->as_parent_node(c,n);
                   Point bracketed_pt;
                   // If we're not a parent node, use the embedding
                   // matrix to find the child node location in parent
                   // master element space
                   if (parent_node == libMesh::invalid_uint)
                     {
                       for (unsigned int pn = 0; pn != nn; ++pn)
{
                           const float em_val =
                             this->embedding_matrix(c,n,pn);
                           libmesh_assert_not_equal_to (em_val, 1);
                           if (em_val != 0.)
                             bracketed_pt.add_scaled(this->master_point(pn), em_val);
                         }
                     }
                   // If we're a parent node then we need no arithmetic
                   else
                     bracketed_pt = this->master_point(parent_node);
                   for (unsigned int n1 = 0; n1 != nn; ++n1)
                     {
                       if (n1 == parent_node)
                         continue;
                       Point p1 = this->master_point(n1);
                       for (unsigned int n2 = n1+1; n2 < nn; ++n2)
{
                           if (n2 == parent_node)
                             continue;
                           Point pmid = (p1 + this->master_point(n2))/2;
                           if (pmid == bracketed_pt)
{
                               cached_bracketing_nodes[em_vers][c][n].push_back
                                 (std::make_pair(n1,n2));
                               break;
                             }
                           else
                             libmesh_assert(!pmid.absolute_fuzzy_equals(bracketed_pt));
                         }
                     }
                 }
             }
         }
     }
   return cached_bracketing_nodes[em_vers][child][child_node];
 }
const Point & libMesh::Elem::point (const unsigned int i) const inline inherited
Returns
The Point associated with local Node i.
Definition at line 1661 of file elem.h.
References libMesh::Elem::_nodes, libMesh::DofObject::invalid_id, libMesh::libmesh_assert(), and libMesh::Elem::n_nodes().
Referenced by libMesh::PostscriptIO::_compute_edge_bezier_coeffs(), libMesh::MeshTools::Subdivision::add_boundary_ghosts(), libMesh::BoundaryInfo::add_elements(), libMesh::MeshRefinement::add_node(), libMesh::MeshTools::Modification::all_tri(), libMesh::Tet::choose_diagonal(), libMesh::Elem::coarsen(), libMesh::InfFE< Dim, T_radial, T_map >::compute_data(), libMesh::FEMap::compute_edge_map(), libMesh::FEXYZMap::compute_face_map(), libMesh::FEMap::compute_face_map(), libMesh::Elem::contains_edge_of(), libMesh::InfQuad4::contains_point(), libMesh::InfPrism6::contains_point(), libMesh::InfHex8::contains_point(), libMesh::Tri3::contains_point(), contains_point(), libMesh::Elem::contains_vertex_of(), libMesh::UnstructuredMesh::create_submesh(), libMesh::ElemCutter::cut_2D(), libMesh::ElemCutter::cut_3D(), libMesh::FEMContext::elem_position_get(), libMesh::Elem::find_interior_neighbors(), libMesh::UnstructuredMesh::find_neighbors(), libMesh::Quad4::has_affine_map(), libMesh::Prism6::has_affine_map(), libMesh::Edge3::has_affine_map(), libMesh::Quad8::has_affine_map(), libMesh::Quad9::has_affine_map(), libMesh::Tri6::has_affine_map(), libMesh::Edge4::has_affine_map(), libMesh::Hex8::has_affine_map(), libMesh::Tet10::has_affine_map(), libMesh::Hex27::has_affine_map(), libMesh::Hex20::has_affine_map(), libMesh::Prism15::has_affine_map(), libMesh::Prism18::has_affine_map(), libMesh::Elem::hmax(), libMesh::Elem::hmin(), libMesh::Elem::length(), libMesh::PointLocatorBase::locate_node(), libMesh::Edge4::loose_bounding_box(), libMesh::Edge3::loose_bounding_box(), libMesh::Quad8::loose_bounding_box(), libMesh::Tri6::loose_bounding_box(), libMesh::Quad9::loose_bounding_box(), libMesh::Elem::loose_bounding_box(), libMesh::InfFE< Dim, T_radial, T_map >::map(), libMesh::FE< Dim, T >::map(), libMesh::FE< Dim, T >::map_eta(), libMesh::FE< Dim, T >::map_xi(), libMesh::FE< Dim, T >::map_zeta(), libMesh::Tri3::min_and_max_angle(), min_and_max_angle(), libMesh::FEMSystem::numerical_jacobian(), libMesh::GenericProjector< FFunctor, GFunctor, FValue, ProjectionAction >::operator()(), libMesh::BoundaryProjectSolution::operator()(), libMesh::InfCell::origin(), libMesh::InfEdge2::origin(), libMesh::InfQuad::origin(), libMesh::PostscriptIO::plot_linear_elem(), libMesh::Elem::point_test(), libMesh::Tri::quality(), libMesh::FE< Dim, T >::reinit(), libMesh::FE< Dim, T >::shape(), libMesh::FE< Dim, T >::shape_deriv(), libMesh::FE< Dim, T >::shape_second_deriv(), libMesh::MeshTools::Modification::smooth(), libMesh::Edge2::volume(), libMesh::Quad4::volume(), libMesh::Tri3::volume(), libMesh::Pyramid5::volume(), libMesh::Prism6::volume(), libMesh::Edge3::volume(), libMesh::Hex8::volume(), volume(), libMesh::Edge4::volume(), libMesh::Quad8::volume(), libMesh::Tri6::volume(), libMesh::Pyramid13::volume(), libMesh::Quad9::volume(), libMesh::Tet10::volume(), libMesh::Hex20::volume(), libMesh::Prism15::volume(), libMesh::Pyramid14::volume(), libMesh::Hex27::volume(), libMesh::Prism18::volume(), libMesh::Elem::which_side_am_i(), libMesh::EnsightIO::write_geometry_ascii(), libMesh::ExodusII_IO_Helper::write_nodal_coordinates(), libMesh::GmshIO::write_post(), and libMesh::GnuPlotIO::write_solution().
 {
   libmesh_assert_less (i, this->n_nodes());
   libmesh_assert(_nodes[i]);
   libmesh_assert_not_equal_to (_nodes[i]->id(), Node::invalid_id);
   return *_nodes[i];
 }
Point & libMesh::Elem::point (const unsigned int i) inline inherited
Returns
The Point associated with local Node i as a writable reference.
Definition at line 1673 of file elem.h.
References libMesh::Elem::_nodes, and libMesh::Elem::n_nodes().
 {
   libmesh_assert_less (i, this->n_nodes());
   return *_nodes[i];
 }
void libMesh::DofObject::print_dof_info () const inherited
Print out info for debugging.
Definition at line 552 of file dof_object.C.
References libMesh::DofObject::dof_number(), libMesh::DofObject::id(), libMesh::DofObject::n_comp(), libMesh::DofObject::n_systems(), libMesh::DofObject::n_vars(), and libMesh::out.
 {
   libMesh::out << this->id() << " [ ";
   for (unsigned int s=0; s<this->n_systems(); s++)
     {
       libMesh::out << "s:" << s << " ";
       for (unsigned int var=0; var<this->n_vars(s); var++)
         {
           libMesh::out << "v:" << var << " ";
           for (unsigned int comp=0; comp<this->n_comp(s,var); comp++)
             {
               libMesh::out << "c:" << comp << " dof:" << this->dof_number(s,var,comp) << " ";
             }
         }
     }
   libMesh::out << "]\n";
 }
void libMesh::ReferenceCounter::print_info (std::ostream & out = libMesh::out) static inherited
Prints the reference information, by default to libMesh::out.
Definition at line 88 of file reference_counter.C.
References libMesh::ReferenceCounter::_enable_print_counter, and libMesh::ReferenceCounter::get_info().
Referenced by libMesh::LibMeshInit::LibMeshInit().
 {
   if (_enable_print_counter)
     out_stream << ReferenceCounter::get_info();
 }
void libMesh::ReferenceCounter::print_info (std::ostream & out = libMesh::out) static inherited
Prints the reference information, by default to libMesh::out.
Definition at line 88 of file reference_counter.C.
References libMesh::ReferenceCounter::_enable_print_counter, and libMesh::ReferenceCounter::get_info().
Referenced by libMesh::LibMeshInit::LibMeshInit().
 {
   if (_enable_print_counter)
     out_stream << ReferenceCounter::get_info();
 }
void libMesh::Elem::print_info (std::ostream & os = libMesh::out) const inherited
Prints relevant information about the element.
Definition at line 2609 of file elem.C.
References libMesh::Elem::get_info().
Referenced by libMesh::FEMap::compute_single_point_map(), libMesh::FE< Dim, T >::inverse_map(), libMesh::Elem::is_linear(), and libMesh::operator<<().
 {
   os << this->get_info()
      << std::endl;
 }
processor_id_type libMesh::DofObject::processor_id () const inline inherited
Returns
The processor that this DofObject belongs to.
When partitioning and DoF numbering have been performed by libMesh, every current DoF on this DofObject will belong to its processor.
Definition at line 686 of file dof_object.h.
References libMesh::DofObject::_processor_id.
Referenced by libMesh::BoundaryInfo::_find_id_maps(), libMesh::DistributedMesh::add_elem(), libMesh::BoundaryInfo::add_elements(), libMesh::Patch::add_local_face_neighbors(), libMesh::Patch::add_local_point_neighbors(), libMesh::DofMap::add_neighbors_to_send_list(), libMesh::DistributedMesh::add_node(), libMesh::MeshRefinement::add_node(), libMesh::ReplicatedMesh::add_point(), libMesh::DistributedMesh::add_point(), libMesh::UnstructuredMesh::all_first_order(), libMesh::UnstructuredMesh::all_second_order(), libMesh::MeshTools::Modification::all_tri(), libMesh::DofMap::allgather_recursive_constraints(), libMesh::ParmetisPartitioner::assign_partitioning(), libMesh::Patch::build_around_element(), libMesh::MeshTools::Generation::build_extrusion(), libMesh::InfElemBuilder::build_inf_elem(), libMesh::BoundaryInfo::build_node_list_from_side_list(), libMesh::VTKIO::cells_to_vtk(), libMesh::Nemesis_IO_Helper::compute_border_node_ids(), libMesh::Nemesis_IO_Helper::compute_internal_and_border_elems_and_internal_nodes(), libMesh::Nemesis_IO_Helper::compute_num_global_nodesets(), libMesh::Nemesis_IO_Helper::compute_num_global_sidesets(), libMesh::UnstructuredMesh::copy_nodes_and_elements(), libMesh::MeshTools::correct_node_proc_ids(), libMesh::UnstructuredMesh::create_submesh(), libMesh::DistributedMesh::delete_elem(), libMesh::DistributedMesh::delete_node(), libMesh::DofMap::distribute_dofs(), libMesh::DofMap::distribute_local_dofs_node_major(), libMesh::DofMap::distribute_local_dofs_var_major(), libMesh::Elem::Elem(), libMesh::MeshFunction::find_element(), libMesh::MeshFunction::find_elements(), libMesh::UnstructuredMesh::find_neighbors(), libMesh::MeshTools::Modification::flatten(), libMesh::Node::get_info(), libMesh::Elem::get_info(), libMesh::DofMap::get_info(), libMesh::DofMap::get_local_constraints(), libMesh::DistributedMesh::insert_elem(), libMesh::DofObject::invalidate_processor_id(), libMesh::Elem::is_semilocal(), libMesh::MeshTools::libmesh_assert_parallel_consistent_procids< Elem >(), libMesh::MeshTools::libmesh_assert_parallel_consistent_procids< Node >(), libMesh::MeshTools::libmesh_assert_topology_consistent_procids< Elem >(), libMesh::MeshTools::libmesh_assert_valid_amr_elem_ids(), libMesh::MeshTools::libmesh_assert_valid_elem_ids(), libMesh::MeshTools::libmesh_assert_valid_neighbors(), libMesh::DofMap::local_variable_indices(), libMesh::MeshRefinement::make_coarsening_compatible(), libMesh::MeshCommunication::make_p_levels_parallel_consistent(), libMesh::GhostPointNeighbors::operator()(), libMesh::SiblingCoupling::operator()(), libMesh::DefaultCoupling::operator()(), libMesh::PointNeighborCoupling::operator()(), libMesh::Parallel::Packing< const Node * >::pack(), libMesh::Parallel::Packing< const Elem * >::pack(), libMesh::XdrIO::pack_element(), libMesh::LinearPartitioner::partition_range(), libMesh::MetisPartitioner::partition_range(), libMesh::SFCPartitioner::partition_range(), libMesh::MappedSubdomainPartitioner::partition_range(), libMesh::CentroidPartitioner::partition_range(), libMesh::Partitioner::partition_unpartitioned_elements(), libMesh::System::point_gradient(), libMesh::System::point_hessian(), libMesh::System::point_value(), libMesh::DofObject::processor_id(), libMesh::Nemesis_IO::read(), libMesh::CheckpointIO::read_connectivity(), libMesh::XdrIO::read_serialized_connectivity(), libMesh::Elem::refine(), libMesh::DofMap::scatter_constraints(), libMesh::MeshCommunication::send_coarse_ghosts(), libMesh::DofObject::set_id(), libMesh::Partitioner::set_node_processor_ids(), libMesh::DofMap::set_nonlocal_dof_objects(), libMesh::Partitioner::set_parent_processor_ids(), libMesh::Partitioner::single_partition_range(), libMesh::BoundaryInfo::sync(), libMesh::Parallel::sync_dofobject_data_by_id(), libMesh::Parallel::sync_element_data_by_parent_id(), libMesh::Parallel::sync_node_data_by_element_id(), libMesh::MeshRefinement::uniformly_coarsen(), libMesh::Parallel::Packing< Elem * >::unpack(), libMesh::GMVIO::write_binary(), libMesh::CheckpointIO::write_connectivity(), libMesh::GmshIO::write_mesh(), libMesh::CheckpointIO::write_nodes(), libMesh::XdrIO::write_serialized_connectivity(), and libMesh::Nemesis_IO_Helper::write_sidesets().
 {
   return _processor_id;
 }
processor_id_type & libMesh::DofObject::processor_id () inline inherited
Returns
The processor that this DofObject belongs to as a writable reference.
Definition at line 694 of file dof_object.h.
References libMesh::DofObject::_processor_id.
 {
   return _processor_id;
 }
void libMesh::DofObject::processor_id (const processor_id_type pid) inline inherited
Sets the processor_id for this DofObject.
Definition at line 702 of file dof_object.h.
References libMesh::DofObject::processor_id().
 {
   this->processor_id() = pid;
 }
std::pair< Real, Real > libMesh::Tet::qual_bounds (const ElemQuality q) const virtual inherited
Returns
The suggested quality bounds for the hex based on quality measure q. These are the values suggested by the CUBIT User's Manual.
Reimplemented from libMesh::Elem.
Definition at line 199 of file cell_tet.C.
References libMesh::ASPECT_RATIO_BETA, libMesh::ASPECT_RATIO_GAMMA, libMesh::CONDITION, libMesh::DISTORTION, libMesh::JACOBIAN, libMesh::out, libMesh::SHAPE, and libMesh::SIZE.
Referenced by libMesh::Tet::n_children().
 {
   std::pair<Real, Real> bounds;
   switch (q)
     {
     case ASPECT_RATIO_BETA:
     case ASPECT_RATIO_GAMMA:
       bounds.first  = 1.;
       bounds.second = 3.;
       break;
     case SIZE:
     case SHAPE:
       bounds.first  = 0.2;
       bounds.second = 1.;
       break;
     case CONDITION:
       bounds.first  = 1.;
       bounds.second = 3.;
       break;
     case DISTORTION:
       bounds.first  = 0.6;
       bounds.second = 1.;
       break;
     case JACOBIAN:
       bounds.first  = 0.5;
       bounds.second = 1.414;
       break;
     default:
       libMesh::out << "Warning: Invalid quality measure chosen." << std::endl;
       bounds.first  = -1;
       bounds.second = -1;
     }
   return bounds;
 }
Real libMesh::Tet::quality (const ElemQuality q) const virtual inherited
Returns
A quantitative assessment of element quality based on the quality metric q specified by the user.
Reimplemented from libMesh::Elem.
Definition at line 191 of file cell_tet.C.
References libMesh::Elem::quality().
Referenced by libMesh::Tet::n_children().
 {
   return Elem::quality(q); // Not implemented
 }
const Elem * libMesh::Elem::reference_elem () const inherited
Returns
A pointer to the "reference element" associated with this element. The reference element is the image of this element in reference parametric space. Importantly, it is not an actual element in the mesh, but rather a Singleton-type object, so for example all Quad4 elements share the same reference_elem().
Definition at line 430 of file elem.C.
References libMesh::ReferenceElem::get(), and libMesh::Elem::type().
Referenced by libMesh::QComposite< QSubCell >::init().
 {
   return &(ReferenceElem::get(this->type()));
 }
void libMesh::Elem::refine (MeshRefinement & mesh_refinement) virtual inherited
Refine the element.
The following functions only apply when AMR is enabled and thus are not present otherwise.
Definition at line 41 of file elem_refinement.C.
References libMesh::Elem::_children, libMesh::Elem::active(), libMesh::MeshRefinement::add_elem(), libMesh::MeshRefinement::add_node(), libMesh::Elem::ancestor(), libMesh::Elem::build(), libMesh::Elem::child_ptr(), libMesh::Elem::INACTIVE, libMesh::Elem::JUST_REFINED, libMesh::libmesh_assert(), libMesh::Elem::n_children(), libMesh::Elem::n_nodes(), libMesh::DofObject::n_systems(), libMesh::Elem::node(), libMesh::Elem::p_level(), libMesh::Elem::p_refinement_flag(), libMesh::Elem::parent(), libMesh::DofObject::processor_id(), libMesh::Elem::REFINE, libMesh::Elem::refinement_flag(), libMesh::DofObject::set_n_systems(), libMesh::Elem::set_node(), libMesh::Elem::set_p_level(), libMesh::Elem::set_p_refinement_flag(), libMesh::Elem::set_refinement_flag(), libMesh::Elem::subactive(), and libMesh::Elem::type().
 {
   libmesh_assert_equal_to (this->refinement_flag(), Elem::REFINE);
   libmesh_assert (this->active());
   // Create my children if necessary
   if (!_children)
     {
       _children = new Elem *[this->n_children()];
       unsigned int parent_p_level = this->p_level();
       for (unsigned int c=0; c<this->n_children(); c++)
         {
           _children[c] = Elem::build(this->type(), this).release();
           Elem * current_child = this->child_ptr(c);
           current_child->set_refinement_flag(Elem::JUST_REFINED);
           current_child->set_p_level(parent_p_level);
           current_child->set_p_refinement_flag(this->p_refinement_flag());
           for (unsigned int nc=0; nc<current_child->n_nodes(); nc++)
             {
               Node * node =
                 mesh_refinement.add_node(*this, c, nc,
                                          current_child->processor_id());
               node->set_n_systems (this->n_systems());
               current_child->set_node(nc) = node;
             }
           mesh_refinement.add_elem (current_child);
           current_child->set_n_systems(this->n_systems());
         }
     }
   else
     {
       unsigned int parent_p_level = this->p_level();
       for (unsigned int c=0; c<this->n_children(); c++)
         {
           Elem * current_child = this->child_ptr(c);
           libmesh_assert(current_child->subactive());
           current_child->set_refinement_flag(Elem::JUST_REFINED);
           current_child->set_p_level(parent_p_level);
           current_child->set_p_refinement_flag(this->p_refinement_flag());
         }
     }
   // Un-set my refinement flag now
   this->set_refinement_flag(Elem::INACTIVE);
   // Leave the p refinement flag set - we will need that later to get
   // projection operations correct
   // this->set_p_refinement_flag(Elem::INACTIVE);
   for (unsigned int c=0; c<this->n_children(); c++)
     {
       libmesh_assert_equal_to (this->child_ptr(c)->parent(), this);
       libmesh_assert(this->child_ptr(c)->active());
     }
   libmesh_assert (this->ancestor());
 }
Elem::RefinementState libMesh::Elem::refinement_flag () const inline inherited
Returns
The value of the refinement flag for the element.
Definition at line 2289 of file elem.h.
References libMesh::Elem::_rflag.
Referenced by libMesh::MeshRefinement::_coarsen_elements(), libMesh::MeshRefinement::_refine_elements(), libMesh::Elem::active(), libMesh::UnstructuredMesh::all_first_order(), libMesh::OldSolutionValue< Output, point_output >::check_old_context(), libMesh::Elem::coarsen(), libMesh::MeshRefinement::coarsen_elements(), libMesh::Elem::contract(), libMesh::UnstructuredMesh::copy_nodes_and_elements(), libMesh::MeshRefinement::eliminate_unrefined_patches(), libMesh::MeshRefinement::enforce_mismatch_limit_prior_to_refinement(), libMesh::Elem::get_info(), libMesh::MeshTools::libmesh_assert_old_dof_objects(), libMesh::DistributedMesh::libmesh_assert_valid_parallel_flags(), libMesh::MeshTools::libmesh_assert_valid_refinement_flags(), libMesh::MeshRefinement::limit_level_mismatch_at_edge(), libMesh::MeshRefinement::limit_level_mismatch_at_node(), libMesh::MeshRefinement::limit_overrefined_boundary(), libMesh::MeshRefinement::limit_underrefined_boundary(), libMesh::MeshRefinement::make_coarsening_compatible(), libMesh::MeshRefinement::make_flags_parallel_consistent(), libMesh::Elem::make_links_to_me_local(), libMesh::MeshCommunication::make_p_levels_parallel_consistent(), libMesh::MeshRefinement::make_refinement_compatible(), libMesh::DofMap::old_dof_indices(), libMesh::GenericProjector< FFunctor, GFunctor, FValue, ProjectionAction >::operator()(), libMesh::BuildProjectionList::operator()(), libMesh::Parallel::Packing< const Elem * >::pack(), libMesh::Elem::refine(), libMesh::MeshRefinement::refine_and_coarsen_elements(), libMesh::MeshRefinement::refine_elements(), libMesh::DofMap::reinit(), libMesh::HPSingularity::select_refinement(), libMesh::HPCoarsenTest::select_refinement(), libMesh::MeshRefinement::test_unflagged(), libMesh::MeshRefinement::uniformly_coarsen(), and libMesh::Parallel::Packing< Elem * >::unpack().
 {
   return static_cast<RefinementState>(_rflag);
 }
void libMesh::Elem::remove_links_to_me () inherited
Resets this element's neighbors' appropriate neighbor pointers and its parent's and children's appropriate pointers to point to null instead of to this.
Used by the library before an element is deleted from a mesh.
Definition at line 1398 of file elem.C.
References libMesh::Elem::has_children(), libMesh::Elem::has_neighbor(), libMesh::Elem::level(), libMesh::libmesh_assert(), libmesh_nullptr, libMesh::Elem::n_neighbors(), libMesh::Elem::n_sides(), libMesh::Elem::neighbor(), libMesh::Elem::neighbor_ptr(), libMesh::Elem::parent(), libMesh::remote_elem, libMesh::Elem::set_neighbor(), libMesh::Elem::subactive(), libMesh::Elem::total_family_tree_by_neighbor(), libMesh::Elem::total_family_tree_by_subneighbor(), and libMesh::Elem::which_neighbor_am_i().
 {
   libmesh_assert_not_equal_to (this, remote_elem);
   // We need to have handled any children first
 #ifdef LIBMESH_ENABLE_AMR
   libmesh_assert (!this->has_children());
 #endif
   // Nullify any neighbor links
   for (unsigned int s = 0; s != this->n_sides(); ++s)
     {
       Elem * neigh = this->neighbor_ptr(s);
       if (neigh && neigh != remote_elem)
         {
           // My neighbor should never be more refined than me; my real
           // neighbor would have been its parent in that case.
           libmesh_assert_greater_equal (this->level(), neigh->level());
           if (this->level() == neigh->level() &&
               neigh->has_neighbor(this))
             {
 #ifdef LIBMESH_ENABLE_AMR
               // My neighbor may have descendants which also consider me a
               // neighbor
               std::vector<const Elem *> family;
               neigh->total_family_tree_by_neighbor (family, this);
               // FIXME - There's a lot of ugly const_casts here; we
               // may want to make remote_elem non-const and create
               // non-const versions of the family_tree methods
               for (std::size_t i=0; i != family.size(); ++i)
                 {
                   Elem * n = const_cast<Elem *>(family[i]);
                   libmesh_assert (n);
                   if (n == remote_elem)
                     continue;
                   unsigned int my_s = n->which_neighbor_am_i(this);
                   libmesh_assert_less (my_s, n->n_neighbors());
                   libmesh_assert_equal_to (n->neighbor_ptr(my_s), this);
                   n->set_neighbor(my_s, libmesh_nullptr);
                 }
 #else
               unsigned int my_s = neigh->which_neighbor_am_i(this);
               libmesh_assert_less (my_s, neigh->n_neighbors());
               libmesh_assert_equal_to (neigh->neighbor(my_s), this);
               neigh->set_neighbor(my_s, libmesh_nullptr);
 #endif
             }
 #ifdef LIBMESH_ENABLE_AMR
           // Even if my neighbor doesn't link back to me, it might
           // have subactive descendants which do
           else if (neigh->has_children())
             {
               // If my neighbor at the same level doesn't have me as a
               // neighbor, I must be subactive
               libmesh_assert(this->level() > neigh->level() ||
                              this->subactive());
               // My neighbor must have some ancestor of mine as a
               // neighbor
               Elem * my_ancestor = this->parent();
               libmesh_assert(my_ancestor);
               while (!neigh->has_neighbor(my_ancestor))
                 {
                   my_ancestor = my_ancestor->parent();
                   libmesh_assert(my_ancestor);
                 }
               // My neighbor may have descendants which consider me a
               // neighbor
               std::vector<const Elem *> family;
               neigh->total_family_tree_by_subneighbor (family, my_ancestor, this);
               // FIXME - There's a lot of ugly const_casts here; we
               // may want to make remote_elem non-const and create
               // non-const versions of the family_tree methods
               for (std::size_t i=0; i != family.size(); ++i)
                 {
                   Elem * n = const_cast<Elem *>(family[i]);
                   libmesh_assert (n);
                   if (n == remote_elem)
                     continue;
                   unsigned int my_s = n->which_neighbor_am_i(this);
                   libmesh_assert_less (my_s, n->n_neighbors());
                   libmesh_assert_equal_to (n->neighbor_ptr(my_s), this);
                   n->set_neighbor(my_s, libmesh_nullptr);
                 }
             }
 #endif
         }
     }
 #ifdef LIBMESH_ENABLE_AMR
   // We can't currently delete a child with a parent!
   libmesh_assert (!this->parent());
 #endif
 }
void libMesh::Elem::replace_child (Elem * elem, unsigned int c) inherited
Replaces the child pointer at the specified index in the child array.
Definition at line 1647 of file elem.C.
References libMesh::Elem::child_ptr(), libMesh::Elem::has_children(), libMesh::libmesh_assert(), and libMesh::Elem::set_child().
Referenced by libMesh::UnstructuredMesh::all_first_order().
 {
   libmesh_assert(this->has_children());
   libmesh_assert(this->child_ptr(c));
   this->set_child(c, elem);
 }
unsigned short int libMesh::Elem::second_order_adjacent_vertex (const unsigned int n, const unsigned int v) const virtual inherited
Returns
The element-local number of the vertex that defines the second-order node, or 0 for linear elements.
Note
The value is always less than this->n_vertices(), while n has to be greater than or equal to this->n_vertices().
Reimplemented in libMesh::InfHex18, libMesh::Pyramid14, libMesh::Hex27, libMesh::Prism18, libMesh::InfHex16, libMesh::Hex20, libMesh::Prism15, libMesh::Tet10, libMesh::Pyramid13, libMesh::Quad9, libMesh::InfPrism12, libMesh::InfQuad6, libMesh::Quad8, libMesh::Tri6, libMesh::Edge3, and libMesh::Edge4.
Definition at line 2728 of file elem.C.
Referenced by libMesh::Elem::is_linear(), libMesh::LaplaceMeshSmoother::smooth(), and libMesh::MeshTools::Modification::smooth().
 {
   // for linear elements, always return 0
   return 0;
 }
std::pair< unsigned short int, unsigned short int > libMesh::Elem::second_order_child_vertex (const unsigned int n) const virtual inherited
Returns
A pair (c,v), where c == child index, and v == element-local index of the second-order node on the parent element. For linear elements, (0,0) is returned.
Note
The return values are always less than this->n_children() and this->child_ptr(c)->n_vertices().
n has to be greater than or equal to this->n_vertices().
On refined second-order elements, the return value will satisfy this->node_ptr(n) == this->child_ptr(c)->node_ptr(v).
Reimplemented in libMesh::InfHex18, libMesh::Hex27, libMesh::Prism18, libMesh::InfHex16, libMesh::Hex20, libMesh::Prism15, libMesh::Tet10, libMesh::Quad9, libMesh::InfPrism12, libMesh::InfQuad6, libMesh::Quad8, libMesh::Tri6, and libMesh::Edge3.
Definition at line 2738 of file elem.C.
Referenced by libMesh::Elem::is_linear().
 {
   // for linear elements, always return 0
   return std::pair<unsigned short int, unsigned short int>(0,0);
 }
ElemType libMesh::Elem::second_order_equivalent_type (const ElemType et, const bool full_ordered = true) static inherited
Returns
The element type of the associated second-order element, or INVALID_ELEM for second-order or other elements that cannot be converted into higher order equivalents.
For example, when this is a TET4, then TET10 is returned.
For some elements, there exist two second-order equivalents, e.g. for Quad4 there is Quad8 and Quad9. When the optional full_ordered is true, then QUAD9 is returned. When full_ordered is false, then QUAD8 is returned.
Definition at line 2804 of file elem.C.
References libMesh::EDGE2, libMesh::EDGE3, libMesh::EDGE4, libMesh::HEX20, libMesh::HEX27, libMesh::HEX8, libMesh::INFEDGE2, libMesh::INFHEX16, libMesh::INFHEX18, libMesh::INFHEX8, libMesh::INFPRISM12, libMesh::INFPRISM6, libMesh::INFQUAD4, libMesh::INFQUAD6, libMesh::INVALID_ELEM, libMesh::PRISM15, libMesh::PRISM18, libMesh::PRISM6, libMesh::PYRAMID13, libMesh::PYRAMID14, libMesh::PYRAMID5, libMesh::QUAD4, libMesh::QUAD8, libMesh::QUAD9, libMesh::TET10, libMesh::TET4, libMesh::TRI3, and libMesh::TRI6.
Referenced by libMesh::UnstructuredMesh::all_second_order(), libMesh::Elem::bracketing_nodes(), libMesh::Elem::is_linear(), and libMesh::Elem::parent_bracketing_nodes().
 {
   /* for second-order elements, always return \p INVALID_ELEM
    * since second-order elements should not be converted
    * into something else.  Only linear elements should
    * return something sensible here
    */
   switch (et)
     {
     case EDGE2:
     case EDGE3:
       {
         // full_ordered not relevant
         return EDGE3;
       }
     case EDGE4:
       {
         // full_ordered not relevant
         return EDGE4;
       }
     case TRI3:
     case TRI6:
       {
         // full_ordered not relevant
         return TRI6;
       }
     case QUAD4:
     case QUAD8:
       {
         if (full_ordered)
           return QUAD9;
         else
           return QUAD8;
       }
     case QUAD9:
       {
         // full_ordered not relevant
         return QUAD9;
       }
     case TET4:
     case TET10:
       {
         // full_ordered not relevant
         return TET10;
       }
     case HEX8:
     case HEX20:
       {
         // see below how this correlates with INFHEX8
         if (full_ordered)
           return HEX27;
         else
           return HEX20;
       }
     case HEX27:
       {
         // full_ordered not relevant
         return HEX27;
       }
     case PRISM6:
     case PRISM15:
       {
         if (full_ordered)
           return PRISM18;
         else
           return PRISM15;
       }
     case PRISM18:
       {
         // full_ordered not relevant
         return PRISM18;
       }
     case PYRAMID5:
     case PYRAMID13:
       {
         if (full_ordered)
           return PYRAMID14;
         else
           return PYRAMID13;
       }
     case PYRAMID14:
       {
         // full_ordered not relevant
         return PYRAMID14;
       }
 #ifdef LIBMESH_ENABLE_INFINITE_ELEMENTS
       // infinite elements
     case INFEDGE2:
       {
         return INVALID_ELEM;
       }
     case INFQUAD4:
     case INFQUAD6:
       {
         // full_ordered not relevant
         return INFQUAD6;
       }
     case INFHEX8:
     case INFHEX16:
       {
         /*
          * Note that this matches with \p Hex8:
          * For full-ordered, \p InfHex18 and \p Hex27
          * belong together, and for not full-ordered,
          * \p InfHex16 and \p Hex20 belong together.
          */
         if (full_ordered)
           return INFHEX18;
         else
           return INFHEX16;
       }
     case INFHEX18:
       {
         // full_ordered not relevant
         return INFHEX18;
       }
     case INFPRISM6:
     case INFPRISM12:
       {
         // full_ordered not relevant
         return INFPRISM12;
       }
 #endif
     default:
       {
         // what did we miss?
         libmesh_error();
       }
     }
 }
void libMesh::Tet::select_diagonal (const Diagonal diag) const inherited
Allows the user to select the diagonal for the refinement. This function may only be called before the element is ever refined.
Definition at line 90 of file cell_tet.C.
References libMesh::Tet::_diagonal_selection, and libMesh::Tet::INVALID_DIAG.
Referenced by libMesh::Tet::diagonal_selection().
 {
   libmesh_assert_equal_to (_diagonal_selection, INVALID_DIAG);
   _diagonal_selection = diag;
 }
void libMesh::DofObject::set_buffer (const std::vector< dof_id_type > & buf) inline inherited
Definition at line 504 of file dof_object.h.
   { _idx_buf = buf; }
void libMesh::DofObject::set_dof_number (const unsigned int s, const unsigned int var, const unsigned int comp, const dof_id_type dn) inherited
Sets the global degree of freedom number for variable var, component comp for system s associated with this DofObject
Definition at line 406 of file dof_object.C.
References libMesh::DofObject::_idx_buf, libMesh::DofObject::dof_number(), libMesh::DofObject::invalid_id, libMesh::libmesh_assert(), libMesh::DofObject::n_comp(), libMesh::DofObject::n_comp_group(), libMesh::DofObject::n_systems(), libMesh::DofObject::n_vars(), libMesh::DofObject::start_idx(), libMesh::DofObject::system_var_to_vg_var(), and libMesh::DofObject::var_to_vg().
Referenced by libMesh::DofObject::set_id().
 {
   libmesh_assert_less (s,    this->n_systems());
   libmesh_assert_less (var,  this->n_vars(s));
   libmesh_assert_less (comp, this->n_comp(s,var));
   const unsigned int
     vg            = this->var_to_vg(s,var),
 #ifndef NDEBUG
     ncg           = this->n_comp_group(s,vg),
 #endif
     vig           = this->system_var_to_vg_var(s,vg,var),
     start_idx_sys = this->start_idx(s);
   libmesh_assert_less ((start_idx_sys + 2*vg + 1), _idx_buf.size());
   dof_id_type & base_idx = _idx_buf[start_idx_sys + 2*vg + 1];
   // We intend to change all dof numbers together or not at all
   if (comp || vig)
     libmesh_assert ((dn == invalid_id && base_idx == invalid_id) ||
                     (dn == base_idx + vig*ncg + comp));
   // only explicitly store the base index for vig==0, comp==0
   else
     base_idx = dn;
   // #ifdef DEBUG
   //   libMesh::out << " [ ";
   //   for (std::size_t i=0; i<_idx_buf.size(); i++)
   //     libMesh::out << _idx_buf[i] << " ";
   //   libMesh::out << "]\n";
   // #endif
   libmesh_assert_equal_to (this->dof_number(s, var, comp), dn);
 }
dof_id_type & libMesh::DofObject::set_id () inline inherited
Returns
The id for this DofObject as a writable reference.
Definition at line 633 of file dof_object.h.
References libMesh::DofObject::_id.
Referenced by libMesh::GMVIO::_read_one_cell(), libMesh::ReplicatedMesh::add_elem(), libMesh::DistributedMesh::add_elem(), libMesh::ReplicatedMesh::add_node(), libMesh::DistributedMesh::add_node(), libMesh::UnstructuredMesh::all_first_order(), libMesh::MeshTools::Subdivision::all_subdivision(), libMesh::MeshCommunication::assign_global_indices(), libMesh::MeshTools::Generation::build_cube(), libMesh::MeshTools::Generation::build_extrusion(), libMesh::InfElemBuilder::build_inf_elem(), libMesh::UnstructuredMesh::create_submesh(), libMesh::UNVIO::elements_in(), libMesh::MeshTools::Modification::flatten(), libMesh::DofObject::invalidate_id(), libMesh::Node::Node(), libMesh::Nemesis_IO::read(), libMesh::ExodusII_IO::read(), libMesh::VTKIO::read(), libMesh::CheckpointIO::read_connectivity(), libMesh::UCDIO::read_implementation(), libMesh::GmshIO::read_mesh(), libMesh::XdrIO::read_serialized_connectivity(), libMesh::OFFIO::read_stream(), libMesh::MatlabIO::read_stream(), libMesh::RemoteElem::RemoteElem(), libMesh::ReplicatedMesh::renumber_elem(), libMesh::DistributedMesh::renumber_elem(), libMesh::ReplicatedMesh::renumber_node(), libMesh::DistributedMesh::renumber_node(), libMesh::ReplicatedMesh::renumber_nodes_and_elements(), libMesh::DofObject::set_id(), libMesh::ReplicatedMesh::stitching_helper(), and libMesh::Parallel::Packing< Elem * >::unpack().
 {
   return _id;
 }
void libMesh::DofObject::set_id (const dof_id_type dofid) inline inherited
Sets the id for this DofObject
Definition at line 161 of file dof_object.h.
References libMesh::DofObject::add_system(), libMesh::DofObject::dof_number(), libMesh::DofObject::has_dofs(), libMesh::invalid_uint, libMesh::DofObject::n_comp(), libMesh::DofObject::n_comp_group(), libMesh::DofObject::n_systems(), libMesh::DofObject::n_var_groups(), libMesh::DofObject::n_vars(), libMesh::DofObject::processor_id(), libMesh::DofObject::set_dof_number(), libMesh::DofObject::set_id(), libMesh::DofObject::set_n_comp(), libMesh::DofObject::set_n_comp_group(), libMesh::DofObject::set_n_systems(), libMesh::DofObject::set_n_vars_per_group(), libMesh::DofObject::set_vg_dof_base(), libMesh::DofObject::valid_id(), libMesh::DofObject::valid_processor_id(), libMesh::DofObject::valid_unique_id(), and libMesh::DofObject::vg_dof_base().
   { this->set_id() = dofid; }
void libMesh::Elem::set_interior_parent (Elem * p) inherited
Sets the pointer to the element's interior_parent. Dangerous! Only use this if you know what you are doing!
Definition at line 993 of file elem.C.
References libMesh::Elem::_elemlinks, libMesh::Elem::dim(), libMesh::libmesh_assert(), libMesh::Elem::n_sides(), and libMesh::remote_elem.
Referenced by libMesh::BoundaryInfo::add_elements(), libMesh::MeshBase::detect_interior_parents(), libMesh::Edge::Edge(), libMesh::UnstructuredMesh::find_neighbors(), libMesh::Hex::Hex(), libMesh::InfHex::InfHex(), libMesh::InfQuad::InfQuad(), libMesh::Elem::is_linear(), libMesh::NodeElem::NodeElem(), libMesh::Prism::Prism(), libMesh::Pyramid::Pyramid(), libMesh::Quad::Quad(), libMesh::Tet::Tet(), libMesh::Tri::Tri(), and libMesh::Parallel::Packing< Elem * >::unpack().
 {
   // interior parents make no sense for full-dimensional elements.
   libmesh_assert_less (this->dim(), LIBMESH_DIM);
   // If we have an interior_parent, we USED TO assume it was a
   // one-higher-dimensional interior element, but we now allow e.g.
   // edge elements to have a 3D interior_parent with no
   // intermediate 2D element.
   // libmesh_assert (!p ||
   //                 p->dim() == (this->dim()+1));
   libmesh_assert (!p ||
                   (p == remote_elem) ||
                   (p->dim() > this->dim()));
   _elemlinks[1+this->n_sides()] = p;
 }
void libMesh::DofObject::set_n_comp (const unsigned int s, const unsigned int var, const unsigned int ncomp) inherited
Sets the number of components for Variable var of system s associated with this DofObject
Definition at line 337 of file dof_object.C.
References libMesh::DofObject::n_systems(), libMesh::DofObject::n_vars(), libMesh::DofObject::set_n_comp_group(), and libMesh::DofObject::var_to_vg().
Referenced by libMesh::DofObject::set_id().
 {
   libmesh_assert_less (s,   this->n_systems());
   libmesh_assert_less (var, this->n_vars(s));
   this->set_n_comp_group(s, this->var_to_vg(s,var), ncomp);
 }
void libMesh::DofObject::set_n_comp_group (const unsigned int s, const unsigned int vg, const unsigned int ncomp) inherited
Sets the number of components for VariableGroup vg of system s associated with this DofObject
Definition at line 349 of file dof_object.C.
References libMesh::DofObject::_idx_buf, libMesh::DofObject::invalid_id, libMesh::DofObject::n_comp_group(), libMesh::DofObject::n_systems(), libMesh::DofObject::n_var_groups(), libMesh::DofObject::n_vars(), libMesh::DofObject::ncv_magic, and libMesh::DofObject::start_idx().
Referenced by libMesh::DofMap::reinit(), libMesh::DofObject::set_id(), libMesh::DofObject::set_n_comp(), libMesh::DofObject::set_n_vars_per_group(), and libMesh::DofMap::set_nonlocal_dof_objects().
 {
   libmesh_assert_less (s,  this->n_systems());
   libmesh_assert_less (vg, this->n_var_groups(s));
   // Check for trivial return
   if (ncomp == this->n_comp_group(s,vg)) return;
 #ifndef NDEBUG
   if (ncomp >= ncv_magic)
     {
       const index_t ncvm = ncv_magic;
       libmesh_error_msg("ERROR: ncomp must be less than DofObject::ncv_magic!\n" \
                         << "ncomp = "                                   \
                         << ncomp                                \
                         << ", ncv_magic = "                     \
                         << ncvm                                 \
                         << "\nrecompile and try again!");
     }
 #endif
   const unsigned int
     start_idx_sys = this->start_idx(s),
     n_vars_group  = this->n_vars(s,vg),
     base_offset   = start_idx_sys + 2*vg;
   libmesh_assert_less ((base_offset + 1), _idx_buf.size());
   // if (ncomp)
   //   libMesh::out << "s,vg,ncomp="
   //       << s  << ","
   //       << vg << ","
   //       << ncomp << '\n';
   // set the number of components, maintaining the number
   // of variables in the group
   _idx_buf[base_offset] = ncv_magic*n_vars_group + ncomp;
   // We use (invalid_id - 1) to signify no
   // components for this object
   _idx_buf[base_offset + 1] = (ncomp == 0) ? invalid_id - 1 : invalid_id;
   // this->debug_buffer();
   // libMesh::out << "s,vg = " << s << "," << vg << '\n'
   //     << "base_offset=" << base_offset << '\n'
   //     << "this->n_comp(s,vg)=" << this->n_comp(s,vg) << '\n'
   //     << "this->n_comp_group(s,vg)=" << this->n_comp_group(s,vg) << '\n'
   //     << "this->n_vars(s,vg)=" << this->n_vars(s,vg) << '\n'
   //     << "this->n_var_groups(s)=" << this->n_var_groups(s) << '\n';
   libmesh_assert_equal_to (ncomp, this->n_comp_group(s,vg));
 }
void libMesh::DofObject::set_n_systems (const unsigned int s) inherited
Sets the number of systems for this DofObject
Definition at line 157 of file dof_object.C.
References libMesh::DofObject::_idx_buf, libMesh::DofObject::clear_dofs(), libMesh::DofObject::n_systems(), libMesh::DofObject::n_var_groups(), and libMesh::DofObject::n_vars().
Referenced by libMesh::DofObject::add_system(), libMesh::Elem::refine(), libMesh::EquationSystems::reinit(), and libMesh::DofObject::set_id().
 {
   // Check for trivial return
   if (ns == this->n_systems())
     return;
   // Clear any existing data.  This is safe to call
   // even if we don't have any data.
   this->clear_dofs();
   // Set the new number of systems
   _idx_buf.resize(ns, ns);
   _idx_buf[0] = ns;
 #ifdef DEBUG
   // check that all systems now exist and that they have 0 size
   libmesh_assert_equal_to (ns, this->n_systems());
   for (unsigned int s=0; s<this->n_systems(); s++)
     {
       libmesh_assert_equal_to (this->n_vars(s),       0);
       libmesh_assert_equal_to (this->n_var_groups(s), 0);
     }
 #endif
 }
void libMesh::DofObject::set_n_vars_per_group (const unsigned int s, const std::vector< unsigned int > & nvpg) inherited
Sets number of variables in each group associated with system s for this DofObject. Implicit in this is salso setting the number of VariableGroup variable groups for the system. Has the effect of setting the number of components to 0 even when called even with (nvg == this->n_var_groups(s)).
Definition at line 219 of file dof_object.C.
References libMesh::DofObject::_idx_buf, end, libMesh::DofObject::end_idx(), libMesh::DofObject::invalid_id, libMesh::DofObject::n_comp(), libMesh::DofObject::n_comp_group(), libMesh::DofObject::n_systems(), libMesh::DofObject::n_var_groups(), libMesh::DofObject::n_vars(), libMesh::DofObject::ncv_magic, libMesh::DofObject::set_n_comp_group(), and libMesh::DofObject::start_idx().
Referenced by libMesh::DofObject::set_id().
 {
   libmesh_assert_less (s, this->n_systems());
   // number of varaible groups for this system - inferred
   const unsigned int nvg = cast_int<unsigned int>(nvpg.size());
   // BSK - note that for compatibility with the previous implementation
   // calling this method when (nvars == this->n_vars()) requires that
   // we invalidate the DOF indices and set the number of components to 0.
   // Note this was a bit of a suprise to me - there was no quick return in
   // the old method, which caused removal and readdition of the DOF indices
   // even in the case of (nvars == this->n_vars()), resulting in n_comp(s,v)
   // implicitly becoming 0 regardless of any previous value.
   // quick return?
   if (nvg == this->n_var_groups(s))
     {
       for (unsigned int vg=0; vg<nvg; vg++)
         {
           this->set_n_comp_group(s,vg,0);
           libmesh_assert_equal_to (this->n_vars(s,vg), nvpg[vg]);
         }
       return;
     }
   // since there is ample opportunity to screw up other systems, let us
   // cache their current sizes and later assert that they are unchanged.
 #ifdef DEBUG
   DofObject::index_buffer_t old_system_sizes;
   old_system_sizes.reserve(this->n_systems());
   for (unsigned int s_ctr=0; s_ctr<this->n_systems(); s_ctr++)
     old_system_sizes.push_back(this->n_var_groups(s_ctr));
 #endif
   // remove current indices if we have some
   if (this->n_var_groups(s) != 0)
     {
       const unsigned int old_nvg_s = this->n_var_groups(s);
       DofObject::index_buffer_t::iterator
         it  = _idx_buf.begin(),
         end = _idx_buf.begin();
       std::advance(it,  this->start_idx(s));
       std::advance(end, this->end_idx(s));
       _idx_buf.erase(it,end);
       for (unsigned int ctr=(s+1); ctr<this->n_systems(); ctr++)
         _idx_buf[ctr] -= 2*old_nvg_s;
     }
   // better not have any now!
   libmesh_assert_equal_to (this->n_var_groups(s), 0);
   // Make sure we didn't screw up any of our sizes!
 #ifdef DEBUG
   for (unsigned int s_ctr=0; s_ctr<this->n_systems(); s_ctr++)
     if (s_ctr != s)
       libmesh_assert_equal_to (this->n_var_groups(s_ctr), old_system_sizes[s_ctr]);
 #endif
   // OK, if the user requested 0 that is what we have
   if (nvg == 0)
     return;
   {
     // array to hold new indices
     DofObject::index_buffer_t var_idxs(2*nvg);
     for (unsigned int vg=0; vg<nvg; vg++)
       {
         var_idxs[2*vg    ] = ncv_magic*nvpg[vg] + 0;
         var_idxs[2*vg + 1] = invalid_id - 1;
       }
     DofObject::index_buffer_t::iterator it = _idx_buf.begin();
     std::advance(it, this->end_idx(s));
     _idx_buf.insert(it, var_idxs.begin(), var_idxs.end());
     for (unsigned int ctr=(s+1); ctr<this->n_systems(); ctr++)
       _idx_buf[ctr] += 2*nvg;
     // resize _idx_buf to fit so no memory is wasted.
     DofObject::index_buffer_t(_idx_buf).swap(_idx_buf);
   }
   libmesh_assert_equal_to (nvg, this->n_var_groups(s));
 #ifdef DEBUG
   // libMesh::out << " [ ";
   // for (std::size_t i=0; i<_idx_buf.size(); i++)
   //   libMesh::out << _idx_buf[i] << " ";
   // libMesh::out << "]\n";
   libmesh_assert_equal_to (this->n_var_groups(s), nvpg.size());
   for (unsigned int vg=0; vg<this->n_var_groups(s); vg++)
     {
       libmesh_assert_equal_to (this->n_vars(s,vg), nvpg[vg]);
       libmesh_assert_equal_to (this->n_comp_group(s,vg), 0);
     }
   for (unsigned int v=0; v<this->n_vars(s); v++)
     libmesh_assert_equal_to (this->n_comp(s,v), 0);
   // again, all other system sizes shoudl be unchanged!
   for (unsigned int s_ctr=0; s_ctr<this->n_systems(); s_ctr++)
     if (s_ctr != s)
       libmesh_assert_equal_to (this->n_var_groups(s_ctr), old_system_sizes[s_ctr]);
 #endif
 }
void libMesh::Elem::set_neighbor (const unsigned int i, Elem * n) inline inherited
Assigns n as the neighbor.
Definition at line 1846 of file elem.h.
References libMesh::Elem::_elemlinks, and libMesh::Elem::n_neighbors().
Referenced by libMesh::MeshTools::Subdivision::add_boundary_ghosts(), libMesh::BoundaryInfo::add_elements(), libMesh::UnstructuredMesh::all_first_order(), libMesh::MeshTools::Generation::build_extrusion(), libMesh::UnstructuredMesh::copy_nodes_and_elements(), libMesh::UnstructuredMesh::find_neighbors(), libMesh::MeshTools::Modification::flatten(), libMesh::Elem::make_links_to_me_local(), libMesh::Elem::make_links_to_me_remote(), libMesh::Elem::nullify_neighbors(), libMesh::CheckpointIO::read_remote_elem(), libMesh::Elem::remove_links_to_me(), libMesh::ReplicatedMesh::stitching_helper(), and libMesh::Parallel::Packing< Elem * >::unpack().
 {
   libmesh_assert_less (i, this->n_neighbors());
   _elemlinks[i+1] = n;
 }
Node *& libMesh::Elem::set_node (const unsigned int i) inline virtual inherited
Returns
The pointer to local Node i as a writable reference.
Reimplemented in libMesh::RemoteElem.
Definition at line 1789 of file elem.h.
References libMesh::Elem::_nodes, and libMesh::Elem::n_nodes().
Referenced by libMesh::GMVIO::_read_one_cell(), libMesh::MeshTools::Subdivision::add_boundary_ghosts(), libMesh::UnstructuredMesh::all_first_order(), libMesh::MeshTools::Modification::all_tri(), libMesh::TetGenMeshInterface::assign_nodes_to_elem(), libMesh::MeshTools::Generation::build_cube(), libMesh::MeshTools::Generation::build_extrusion(), libMesh::InfElemBuilder::build_inf_elem(), libMesh::Quad4::build_side_ptr(), libMesh::Pyramid5::build_side_ptr(), libMesh::Prism6::build_side_ptr(), libMesh::InfQuad4::build_side_ptr(), libMesh::InfHex8::build_side_ptr(), libMesh::Tri3::build_side_ptr(), libMesh::Hex8::build_side_ptr(), libMesh::InfPrism6::build_side_ptr(), libMesh::InfPrism12::build_side_ptr(), build_side_ptr(), libMesh::InfHex18::build_side_ptr(), libMesh::Quad8::build_side_ptr(), libMesh::Tri6::build_side_ptr(), libMesh::InfQuad6::build_side_ptr(), libMesh::Tet10::build_side_ptr(), libMesh::InfHex16::build_side_ptr(), libMesh::Hex20::build_side_ptr(), libMesh::Pyramid13::build_side_ptr(), libMesh::Edge::build_side_ptr(), libMesh::Prism15::build_side_ptr(), libMesh::Quad9::build_side_ptr(), libMesh::Hex27::build_side_ptr(), libMesh::Prism18::build_side_ptr(), libMesh::Pyramid14::build_side_ptr(), libMesh::MeshTools::Generation::build_sphere(), libMesh::TriangleWrapper::copy_tri_to_mesh(), libMesh::UnstructuredMesh::create_submesh(), libMesh::UNVIO::elements_in(), libMesh::MeshTools::Modification::flatten(), libMesh::Nemesis_IO::read(), libMesh::ExodusII_IO::read(), libMesh::VTKIO::read(), libMesh::CheckpointIO::read_connectivity(), libMesh::AbaqusIO::read_elements(), libMesh::UCDIO::read_implementation(), libMesh::GmshIO::read_mesh(), libMesh::XdrIO::read_serialized_connectivity(), libMesh::OFFIO::read_stream(), libMesh::MatlabIO::read_stream(), libMesh::Elem::refine(), libMesh::RemoteElem::set_node(), libMesh::Tet::side_ptr(), libMesh::Prism::side_ptr(), libMesh::Pyramid::side_ptr(), libMesh::Hex::side_ptr(), libMesh::Tri::side_ptr(), libMesh::Edge::side_ptr(), libMesh::InfPrism::side_ptr(), libMesh::InfHex::side_ptr(), libMesh::Quad::side_ptr(), libMesh::InfQuad::side_ptr(), libMesh::ReplicatedMesh::stitching_helper(), libMesh::BoundaryInfo::sync(), and libMesh::Parallel::Packing< Elem * >::unpack().
 {
   libmesh_assert_less (i, this->n_nodes());
   return _nodes[i];
 }
void libMesh::DofObject::set_old_dof_object () inherited
Sets the old_dof_object to a copy of this
Definition at line 142 of file dof_object.C.
References libMesh::DofObject::clear_old_dof_object(), libMesh::DofObject::DofObject(), libMesh::libmesh_assert(), and libMesh::DofObject::old_dof_object.
Referenced by libMesh::DofMap::reinit().
 {
   this->clear_old_dof_object();
   libmesh_assert (!this->old_dof_object);
   // Make a new DofObject, assign a copy of \p this.
   // Make sure the copy ctor for DofObject works!!
   this->old_dof_object = new DofObject(*this);
 }
void libMesh::Elem::set_p_level (const unsigned int p) inline inherited
Sets the value of the p-refinement level for the element.
Note
The maximum p-refinement level is currently 255.
Definition at line 2343 of file elem.h.
References libMesh::Elem::_p_level, libMesh::Elem::child_ptr(), libMesh::Elem::JUST_COARSENED, libMesh::Elem::JUST_REFINED, libmesh_nullptr, std::min(), libMesh::Elem::n_children(), libMesh::Elem::p_level(), libMesh::Elem::parent(), libMesh::Elem::set_p_level(), and libMesh::Elem::set_p_refinement_flag().
Referenced by libMesh::MeshRefinement::_coarsen_elements(), libMesh::MeshRefinement::_refine_elements(), libMesh::UnstructuredMesh::all_first_order(), libMesh::Elem::coarsen(), libMesh::Elem::Elem(), libMesh::ErrorVector::plot_error(), libMesh::Elem::refine(), libMesh::DofMap::reinit(), libMesh::Elem::set_p_level(), and libMesh::Parallel::Packing< Elem * >::unpack().
 {
   // Maintain the parent's p level as the minimum of it's children
   if (this->parent() != libmesh_nullptr)
     {
       unsigned int parent_p_level = this->parent()->p_level();
       // If our new p level is less than our parents, our parents drops
       if (parent_p_level > p)
         {
           this->parent()->set_p_level(p);
           // And we should keep track of the drop, in case we need to
           // do a projection later.
           this->parent()->set_p_refinement_flag(Elem::JUST_COARSENED);
         }
       // If we are the lowest p level and it increases, so might
       // our parent's, but we have to check every other child to see
       else if (parent_p_level == _p_level && _p_level < p)
         {
           _p_level = cast_int<unsigned char>(p);
           parent_p_level = cast_int<unsigned char>(p);
           for (unsigned int c=0; c != this->parent()->n_children(); c++)
             parent_p_level = std::min(parent_p_level,
                                       this->parent()->child_ptr(c)->p_level());
           // When its children all have a higher p level, the parent's
           // should rise
           if (parent_p_level > this->parent()->p_level())
             {
               this->parent()->set_p_level(parent_p_level);
               // And we should keep track of the rise, in case we need to
               // do a projection later.
               this->parent()->set_p_refinement_flag(Elem::JUST_REFINED);
             }
           return;
         }
     }
   _p_level = cast_int<unsigned char>(p);
 }
void libMesh::Elem::set_p_refinement_flag (const RefinementState pflag) inline inherited
Sets the value of the p-refinement flag for the element.
Definition at line 2313 of file elem.h.
References libMesh::Elem::_pflag, libMesh::Elem::JUST_REFINED, and libMesh::Elem::p_level().
Referenced by libMesh::MeshRefinement::_coarsen_elements(), libMesh::MeshRefinement::_refine_elements(), libMesh::UnstructuredMesh::all_first_order(), libMesh::MeshRefinement::coarsen_elements(), libMesh::MeshRefinement::eliminate_unrefined_patches(), libMesh::MeshRefinement::enforce_mismatch_limit_prior_to_refinement(), libMesh::MeshRefinement::limit_level_mismatch_at_edge(), libMesh::MeshRefinement::limit_level_mismatch_at_node(), libMesh::MeshRefinement::limit_overrefined_boundary(), libMesh::MeshRefinement::limit_underrefined_boundary(), libMesh::MeshRefinement::make_coarsening_compatible(), libMesh::MeshRefinement::make_flags_parallel_consistent(), libMesh::MeshRefinement::make_refinement_compatible(), libMesh::ErrorVector::plot_error(), libMesh::Elem::refine(), libMesh::MeshRefinement::refine_and_coarsen_elements(), libMesh::MeshRefinement::refine_elements(), libMesh::HPSingularity::select_refinement(), libMesh::HPCoarsenTest::select_refinement(), libMesh::Elem::set_p_level(), and libMesh::Parallel::Packing< Elem * >::unpack().
 {
   if (this->p_level() == 0)
     libmesh_assert_not_equal_to
       (pflag, Elem::JUST_REFINED);
   _pflag = cast_int<unsigned char>(pflag);
 }
void libMesh::Elem::set_parent (Elem * p) inline inherited
Sets the pointer to the element's parent. Dangerous! Only use this if you know what you are doing!
Definition at line 2158 of file elem.h.
References libMesh::Elem::_elemlinks.
Referenced by libMesh::BoundaryInfo::add_elements(), libMesh::UnstructuredMesh::all_first_order(), and libMesh::Elem::is_linear().
 {
   _elemlinks[0] = p;
 }
void libMesh::Elem::set_refinement_flag (const RefinementState rflag) inline inherited
Sets the value of the refinement flag for the element.
Definition at line 2297 of file elem.h.
References libMesh::Elem::_rflag.
Referenced by libMesh::UnstructuredMesh::all_first_order(), libMesh::Elem::coarsen(), libMesh::MeshRefinement::coarsen_elements(), libMesh::Elem::contract(), libMesh::MeshRefinement::eliminate_unrefined_patches(), libMesh::MeshRefinement::enforce_mismatch_limit_prior_to_refinement(), libMesh::MeshRefinement::flag_elements_by_elem_fraction(), libMesh::MeshRefinement::flag_elements_by_error_fraction(), libMesh::MeshRefinement::flag_elements_by_error_tolerance(), libMesh::MeshRefinement::flag_elements_by_mean_stddev(), libMesh::MeshRefinement::flag_elements_by_nelem_target(), libMesh::MeshRefinement::limit_level_mismatch_at_edge(), libMesh::MeshRefinement::limit_level_mismatch_at_node(), libMesh::MeshRefinement::limit_overrefined_boundary(), libMesh::MeshRefinement::limit_underrefined_boundary(), libMesh::MeshRefinement::make_coarsening_compatible(), libMesh::MeshRefinement::make_flags_parallel_consistent(), libMesh::MeshRefinement::make_refinement_compatible(), libMesh::CheckpointIO::read_connectivity(), libMesh::XdrIO::read_serialized_connectivity(), libMesh::Elem::refine(), libMesh::MeshRefinement::refine_and_coarsen_elements(), libMesh::MeshRefinement::refine_elements(), libMesh::HPSingularity::select_refinement(), libMesh::HPCoarsenTest::select_refinement(), libMesh::MeshRefinement::uniformly_coarsen(), and libMesh::Parallel::Packing< Elem * >::unpack().
 {
   _rflag = cast_int<RefinementState>(rflag);
 }
unique_id_type & libMesh::DofObject::set_unique_id () inline inherited
Returns
The globally unique_id for this DofObject as a writable reference.
Definition at line 654 of file dof_object.h.
References libMesh::DofObject::_unique_id.
Referenced by libMesh::ReplicatedMesh::add_elem(), libMesh::DistributedMesh::add_elem(), libMesh::ReplicatedMesh::add_node(), libMesh::DistributedMesh::add_node(), libMesh::ReplicatedMesh::add_point(), libMesh::UnstructuredMesh::all_first_order(), libMesh::MeshTools::Generation::build_extrusion(), libMesh::UnstructuredMesh::copy_nodes_and_elements(), libMesh::UnstructuredMesh::create_submesh(), libMesh::MeshTools::Modification::flatten(), libMesh::ReplicatedMesh::insert_elem(), libMesh::DistributedMesh::insert_elem(), libMesh::ReplicatedMesh::insert_node(), libMesh::Nemesis_IO::read(), libMesh::CheckpointIO::read_connectivity(), libMesh::CheckpointIO::read_nodes(), libMesh::XdrIO::read_serialized_connectivity(), and libMesh::Parallel::Packing< Elem * >::unpack().
 {
 #ifdef LIBMESH_ENABLE_UNIQUE_ID
   return _unique_id;
 #else
   libmesh_not_implemented();
 #endif
 }
void libMesh::DofObject::set_vg_dof_base (const unsigned int s, const unsigned int vg, const dof_id_type db) inline inherited
VariableGroup DoF indices are indexed as id = base + var_in_vg*ncomp + comp This method allows for direct access to the base.
Definition at line 894 of file dof_object.h.
References libMesh::DofObject::_idx_buf, libMesh::DofObject::n_systems(), libMesh::DofObject::n_var_groups(), libMesh::DofObject::start_idx(), and libMesh::DofObject::vg_dof_base().
Referenced by libMesh::DofMap::distribute_local_dofs_node_major(), libMesh::DofMap::distribute_local_dofs_var_major(), libMesh::DofObject::invalidate_dofs(), libMesh::DofMap::reinit(), libMesh::DofObject::set_id(), and libMesh::DofMap::set_nonlocal_dof_objects().
 {
   libmesh_assert_less (s,  this->n_systems());
   libmesh_assert_less (vg, this->n_var_groups(s));
   const unsigned int
     start_idx_sys = this->start_idx(s);
   libmesh_assert_less ((start_idx_sys + 2*vg + 1), _idx_buf.size());
   _idx_buf[start_idx_sys + 2*vg + 1] = db;
   libmesh_assert_equal_to (this->vg_dof_base(s,vg), db);
 }
UniquePtr< Elem > libMesh::Elem::side (const unsigned int i) const inline inherited
Returns
A proxy element coincident with side i.
Deprecated:
This method will eventually be removed since it hands back a non-const pointer to a side that could be used to indirectly modify this. Please use the the const-correct side_ptr() function instead.
Definition at line 1906 of file elem.h.
References libMesh::Elem::side_ptr().
Referenced by libMesh::InfHex18::default_order(), libMesh::InfQuad6::default_order(), libMesh::Quad9::default_order(), libMesh::Tri6::default_order(), libMesh::Quad8::default_order(), libMesh::InfPrism12::default_order(), libMesh::InfHex16::default_order(), libMesh::Tet10::default_order(), libMesh::Hex20::default_order(), libMesh::Hex27::default_order(), libMesh::Prism15::default_order(), libMesh::Prism18::default_order(), libMesh::Pyramid13::default_order(), libMesh::Pyramid14::default_order(), libMesh::InfPrism::is_mid_infinite_edge_node(), libMesh::InfQuad::is_mid_infinite_edge_node(), libMesh::Elem::is_vertex_on_child(), libMesh::Edge::key(), libMesh::Hex::n_children(), libMesh::Tet::n_children(), libMesh::Prism::n_children(), libMesh::Pyramid::n_children(), libMesh::Quad::n_children(), libMesh::Tri::n_children(), libMesh::InfHex::n_children(), libMesh::Tet::which_node_am_i(), libMesh::Prism::which_node_am_i(), libMesh::InfPrism12::which_node_am_i(), libMesh::Pyramid::which_node_am_i(), libMesh::Hex::which_node_am_i(), libMesh::InfQuad6::which_node_am_i(), libMesh::Tri::which_node_am_i(), libMesh::Edge::which_node_am_i(), libMesh::InfPrism::which_node_am_i(), libMesh::InfHex16::which_node_am_i(), libMesh::Quad8::which_node_am_i(), libMesh::Tri6::which_node_am_i(), libMesh::Tet10::which_node_am_i(), libMesh::Hex20::which_node_am_i(), libMesh::Prism15::which_node_am_i(), libMesh::Pyramid13::which_node_am_i(), libMesh::InfHex::which_node_am_i(), libMesh::Quad9::which_node_am_i(), libMesh::Quad::which_node_am_i(), libMesh::InfQuad::which_node_am_i(), libMesh::Hex27::which_node_am_i(), libMesh::Prism18::which_node_am_i(), libMesh::Pyramid14::which_node_am_i(), and libMesh::InfHex18::which_node_am_i().
 {
   // Call the const version of side_ptr(), and const_cast the result.
   libmesh_deprecated();
   Elem * s = const_cast<Elem *>(this->side_ptr(i).release());
   return UniquePtr<Elem>(s);
 }
UniquePtr< Elem > libMesh::Tet::side_ptr (const unsigned int i) virtual inherited
Returns
A primitive (3-noded) triangle for face i.
Implements libMesh::Elem.
Definition at line 77 of file cell_tet.C.
References libMesh::Elem::n_nodes(), libMesh::Tet::n_sides(), libMesh::Elem::node_ptr(), libMesh::Elem::set_node(), and side_nodes_map.
Referenced by libMesh::Tet::n_children().
 {
   libmesh_assert_less (i, this->n_sides());
   Elem * face = new Tri3;
   for (unsigned n=0; n<face->n_nodes(); ++n)
     face->set_node(n) = this->node_ptr(Tet4::side_nodes_map[i][n]);
   return UniquePtr<Elem>(face);
 }
UniquePtr< const Elem > libMesh::Elem::side_ptr (unsigned int i) const inline inherited
Definition at line 1894 of file elem.h.
References libMesh::Elem::side_ptr().
 {
   // Call the non-const version of this function, return the result as
   // a UniquePtr<const Elem>.
   Elem * me = const_cast<Elem *>(this);
   const Elem * s = const_cast<const Elem *>(me->side_ptr(i).release());
   return UniquePtr<const Elem>(s);
 }
bool libMesh::Elem::subactive () const inline inherited
Returns
true if the element is subactive (i.e. has no active descendants), false otherwise or if AMR is disabled.
Definition at line 2071 of file elem.h.
References libMesh::Elem::active(), libMesh::Elem::has_children(), libmesh_nullptr, and libMesh::Elem::parent().
Referenced by libMesh::Elem::active_family_tree(), libMesh::Elem::active_family_tree_by_neighbor(), libMesh::Elem::active_family_tree_by_side(), libMesh::Elem::active_family_tree_by_topological_neighbor(), libMesh::HPCoarsenTest::add_projection(), libMesh::Elem::ancestor(), libMesh::FEAbstract::compute_node_constraints(), libMesh::UnstructuredMesh::contract(), libMesh::Elem::family_tree(), libMesh::Elem::family_tree_by_neighbor(), libMesh::Elem::family_tree_by_side(), libMesh::Elem::family_tree_by_subneighbor(), libMesh::Elem::find_interior_neighbors(), libMesh::UnstructuredMesh::find_neighbors(), libMesh::Elem::get_info(), libMesh::MeshTools::get_not_subactive_node_ids(), libMesh::Elem::is_linear(), libMesh::MeshTools::libmesh_assert_topology_consistent_procids< Elem >(), libMesh::Elem::libmesh_assert_valid_neighbors(), libMesh::MeshTools::libmesh_assert_valid_refinement_tree(), libMesh::Elem::make_links_to_me_local(), libMesh::Elem::make_links_to_me_remote(), libMesh::Elem::max_descendant_p_level(), libMesh::Elem::min_new_p_level_by_neighbor(), libMesh::Elem::min_p_level_by_neighbor(), libMesh::Elem::refine(), libMesh::Elem::remove_links_to_me(), libMesh::ReplicatedMesh::stitching_helper(), and libMesh::Parallel::Packing< Elem * >::unpack().
 {
 #ifdef LIBMESH_ENABLE_AMR
   if (this->active())
     return false;
   if (!this->has_children())
     return true;
   for (const Elem * my_ancestor = this->parent();
        my_ancestor != libmesh_nullptr;
        my_ancestor = my_ancestor->parent())
     if (my_ancestor->active())
       return true;
 #endif
   return false;
 }
subdomain_id_type libMesh::Elem::subdomain_id () const inline inherited
Returns
The subdomain that this element belongs to.
Definition at line 1799 of file elem.h.
References libMesh::Elem::_sbd_id.
Referenced by libMesh::ExactSolution::_compute_error(), libMesh::DofMap::_dof_indices(), libMesh::BoundaryInfo::_find_id_maps(), libMesh::BoundaryInfo::add_elements(), libMesh::UnstructuredMesh::all_first_order(), libMesh::UnstructuredMesh::all_second_order(), libMesh::MeshTools::Subdivision::all_subdivision(), libMesh::MeshTools::Modification::all_tri(), libMesh::AbaqusIO::assign_subdomain_ids(), libMesh::Nemesis_IO_Helper::build_element_and_node_maps(), libMesh::MeshTools::Generation::build_extrusion(), libMesh::Quad4::build_side_ptr(), libMesh::Pyramid5::build_side_ptr(), libMesh::Prism6::build_side_ptr(), libMesh::InfQuad4::build_side_ptr(), libMesh::InfHex8::build_side_ptr(), libMesh::Tri3::build_side_ptr(), libMesh::Hex8::build_side_ptr(), libMesh::InfPrism6::build_side_ptr(), libMesh::InfPrism12::build_side_ptr(), build_side_ptr(), libMesh::InfHex18::build_side_ptr(), libMesh::Quad8::build_side_ptr(), libMesh::Tri6::build_side_ptr(), libMesh::InfQuad6::build_side_ptr(), libMesh::Tet10::build_side_ptr(), libMesh::Hex20::build_side_ptr(), libMesh::InfHex16::build_side_ptr(), libMesh::Prism15::build_side_ptr(), libMesh::Pyramid13::build_side_ptr(), libMesh::Quad9::build_side_ptr(), libMesh::Hex27::build_side_ptr(), libMesh::Prism18::build_side_ptr(), libMesh::Pyramid14::build_side_ptr(), libMesh::VTKIO::cells_to_vtk(), libMesh::MeshTools::Modification::change_subdomain_id(), libMesh::Nemesis_IO_Helper::compute_num_global_elem_blocks(), libMesh::UnstructuredMesh::copy_nodes_and_elements(), libMesh::UnstructuredMesh::create_submesh(), libMesh::DofMap::distribute_local_dofs_node_major(), libMesh::DofMap::distribute_local_dofs_var_major(), libMesh::DofMap::dof_indices(), libMesh::Elem::Elem(), libMesh::MeshTools::Modification::flatten(), libMesh::EquationSystems::get_solution(), libMesh::UNVIO::groups_in(), libMesh::SystemSubsetBySubdomain::init(), libMesh::ExodusII_IO_Helper::initialize(), libMesh::DofMap::old_dof_indices(), libMesh::GenericProjector< FFunctor, GFunctor, FValue, ProjectionAction >::operator()(), libMesh::BoundaryProjectSolution::operator()(), libMesh::Parallel::Packing< const Elem * >::pack(), libMesh::XdrIO::pack_element(), libMesh::MappedSubdomainPartitioner::partition_range(), libMesh::Nemesis_IO::read(), libMesh::ExodusII_IO::read(), libMesh::CheckpointIO::read_connectivity(), libMesh::UCDIO::read_implementation(), libMesh::GmshIO::read_mesh(), libMesh::XdrIO::read_serialized_connectivity(), libMesh::DofMap::reinit(), libMesh::Parallel::Packing< Elem * >::unpack(), libMesh::CheckpointIO::write_connectivity(), libMesh::ExodusII_IO_Helper::write_element_values(), libMesh::ExodusII_IO_Helper::write_elements(), and libMesh::GmshIO::write_mesh().
 {
   return _sbd_id;
 }
subdomain_id_type & libMesh::Elem::subdomain_id () inline inherited
Returns
The subdomain that this element belongs to as a writable reference.
Definition at line 1807 of file elem.h.
References libMesh::Elem::_sbd_id.
 {
   return _sbd_id;
 }
const Elem * libMesh::Elem::top_parent () const inline inherited
Returns
A pointer to the element's top-most (i.e. level-0) parent.
That is, this if this is a level-0 element, this element's parent if this is a level-1 element, this element's grandparent if this is a level-2 element, etc...
Definition at line 2166 of file elem.h.
References libMesh::Elem::level(), libMesh::libmesh_assert(), libmesh_nullptr, and libMesh::Elem::parent().
Referenced by libMesh::BoundaryInfo::_find_id_maps(), libMesh::BoundaryInfo::add_elements(), libMesh::BoundaryInfo::boundary_ids(), libMesh::BoundaryInfo::edge_boundary_ids(), libMesh::MeshCommunication::gather_neighboring_elements(), libMesh::Elem::is_linear(), libMesh::MeshTools::libmesh_assert_valid_amr_interior_parents(), and libMesh::BoundaryInfo::side_with_boundary_id().
 {
   const Elem * tp = this;
   // Keep getting the element's parent
   // until that parent is at level-0
   while (tp->parent() != libmesh_nullptr)
     tp = tp->parent();
   libmesh_assert(tp);
   libmesh_assert_equal_to (tp->level(), 0);
   return tp;
 }
const Elem * libMesh::Elem::topological_neighbor (const unsigned int i, const MeshBase & mesh, const PointLocatorBase & point_locator, const PeriodicBoundaries * pb) const inherited
Returns
A pointer to the neighbor of this element for interior elements. If an element is on a periodic boundary, it will return a corresponding element on the opposite side.
Definition at line 1057 of file elem.C.
References libMesh::PeriodicBoundaries::boundary(), libMesh::BoundaryInfo::boundary_ids(), libMesh::MeshBase::get_boundary_info(), libMesh::Elem::level(), libmesh_nullptr, libMesh::Elem::n_neighbors(), libMesh::PeriodicBoundaries::neighbor(), libMesh::Elem::neighbor_ptr(), and libMesh::Elem::parent().
Referenced by libMesh::Elem::has_topological_neighbor(), libMesh::DefaultCoupling::operator()(), and libMesh::MeshRefinement::topological_neighbor().
 {
   libmesh_assert_less (i, this->n_neighbors());
   const Elem * neighbor_i = this->neighbor_ptr(i);
   if (neighbor_i != libmesh_nullptr)
     return neighbor_i;
   if (pb)
     {
       // Since the neighbor is NULL it must be on a boundary. We need
       // see if this is a periodic boundary in which case it will have a
       // topological neighbor
       std::vector<boundary_id_type> bc_ids;
       mesh.get_boundary_info().boundary_ids(this, cast_int<unsigned short>(i), bc_ids);
       for (std::vector<boundary_id_type>::iterator j = bc_ids.begin(); j != bc_ids.end(); ++j)
         if (pb->boundary(*j))
           {
             neighbor_i = pb->neighbor(*j, point_locator, this, i);
             // Since coarse elements do not have more refined
             // neighbors we need to make sure that we don't return one
             // of these types of neighbors.
             if (neighbor_i)
               while (level() < neighbor_i->level())
                 neighbor_i = neighbor_i->parent();
             return neighbor_i;
           }
     }
   return libmesh_nullptr;
 }
Elem * libMesh::Elem::topological_neighbor (const unsigned int i, MeshBase & mesh, const PointLocatorBase & point_locator, const PeriodicBoundaries * pb) inherited
Returns
A writable pointer to the neighbor of this element for interior elements. If an element is on a periodic boundary, it will return a corresponding element on the opposite side.
Definition at line 1015 of file elem.C.
References libMesh::PeriodicBoundaries::boundary(), libMesh::BoundaryInfo::boundary_ids(), libMesh::MeshBase::get_boundary_info(), libMesh::Elem::level(), libmesh_nullptr, libMesh::Elem::n_neighbors(), libMesh::PeriodicBoundaries::neighbor(), libMesh::Elem::neighbor_ptr(), and libMesh::Elem::parent().
 {
   libmesh_assert_less (i, this->n_neighbors());
   Elem * neighbor_i = this->neighbor_ptr(i);
   if (neighbor_i != libmesh_nullptr)
     return neighbor_i;
   if (pb)
     {
       // Since the neighbor is NULL it must be on a boundary. We need
       // see if this is a periodic boundary in which case it will have a
       // topological neighbor
       std::vector<boundary_id_type> bc_ids;
       mesh.get_boundary_info().boundary_ids(this, cast_int<unsigned short>(i), bc_ids);
       for (std::vector<boundary_id_type>::iterator j = bc_ids.begin(); j != bc_ids.end(); ++j)
         if (pb->boundary(*j))
           {
             // Since the point locator inside of periodic boundaries
             // returns a const pointer we will retrieve the proper
             // pointer directly from the mesh object.
             const Elem * const cn = pb->neighbor(*j, point_locator, this, i);
             neighbor_i = const_cast<Elem *>(cn);
             // Since coarse elements do not have more refined
             // neighbors we need to make sure that we don't return one
             // of these types of neighbors.
             if (neighbor_i)
               while (level() < neighbor_i->level())
                 neighbor_i = neighbor_i->parent();
             return neighbor_i;
           }
     }
   return libmesh_nullptr;
 }
void libMesh::Elem::total_family_tree (std::vector< const Elem * > & active_family, const bool reset = true) const inherited
Same as the family_tree() member, but also adds any subactive descendants.
Definition at line 1697 of file elem.C.
References libMesh::Elem::child_ptr(), libMesh::Elem::has_children(), libMesh::Elem::is_remote(), libMesh::Elem::n_children(), and libMesh::Elem::total_family_tree().
Referenced by libMesh::connect_families(), libMesh::Partitioner::set_parent_processor_ids(), and libMesh::Elem::total_family_tree().
 {
   // Clear the vector if the flag reset tells us to.
   if (reset)
     family.clear();
   // Add this element to the family tree.
   family.push_back(this);
   // Recurse into the elements children, if it has them.
   // Do not clear the vector any more.
   if (this->has_children())
     for (unsigned int c=0; c<this->n_children(); c++)
       if (!this->child_ptr(c)->is_remote())
         this->child_ptr(c)->total_family_tree (family, false);
 }
void libMesh::Elem::total_family_tree_by_neighbor (std::vector< const Elem * > & family, const Elem * neighbor, const bool reset = true) const inherited
Same as the family_tree_by_neighbor() member, but also adds any subactive descendants.
Definition at line 1825 of file elem.C.
References libMesh::Elem::child_ptr(), libMesh::Elem::has_children(), libMesh::Elem::has_neighbor(), libMesh::libmesh_assert(), libMesh::Elem::n_children(), libMesh::remote_elem, and libMesh::Elem::total_family_tree_by_neighbor().
Referenced by libMesh::Elem::make_links_to_me_remote(), libMesh::Elem::remove_links_to_me(), and libMesh::Elem::total_family_tree_by_neighbor().
 {
   // Clear the vector if the flag reset tells us to.
   if (reset)
     family.clear();
   // This only makes sense if we're already a neighbor
   libmesh_assert (this->has_neighbor(neighbor_in));
   // Add this element to the family tree.
   family.push_back(this);
   // Recurse into the elements children, if it has any.
   // Do not clear the vector any more.
   if (this->has_children())
     for (unsigned int c=0; c<this->n_children(); c++)
       {
         const Elem * current_child = this->child_ptr(c);
         if (current_child != remote_elem && current_child->has_neighbor(neighbor_in))
           current_child->total_family_tree_by_neighbor (family, neighbor_in, false);
       }
 }
void libMesh::Elem::total_family_tree_by_subneighbor (std::vector< const Elem * > & family, const Elem * neighbor, const Elem * subneighbor, const bool reset = true) const inherited
Same as the family_tree_by_subneighbor() member, but also adds any subactive descendants.
Definition at line 1900 of file elem.C.
References libMesh::Elem::active_family_tree_by_topological_neighbor(), libMesh::Elem::child_ptr(), libMesh::Elem::has_children(), libMesh::Elem::has_neighbor(), libMesh::Elem::is_ancestor_of(), libMesh::libmesh_assert(), libMesh::Elem::n_children(), libMesh::Elem::n_sides(), libMesh::Elem::neighbor_ptr(), libMesh::Elem::parent(), libMesh::remote_elem, and libMesh::Elem::total_family_tree_by_subneighbor().
Referenced by libMesh::Elem::make_links_to_me_remote(), libMesh::Elem::remove_links_to_me(), and libMesh::Elem::total_family_tree_by_subneighbor().
 {
   // Clear the vector if the flag reset tells us to.
   if (reset)
     family.clear();
   // To simplifly this function we need an existing neighbor
   libmesh_assert (neighbor_in);
   libmesh_assert_not_equal_to (neighbor_in, remote_elem);
   libmesh_assert (this->has_neighbor(neighbor_in));
   // This only makes sense if subneighbor descends from neighbor
   libmesh_assert (subneighbor);
   libmesh_assert_not_equal_to (subneighbor, remote_elem);
   libmesh_assert (neighbor_in->is_ancestor_of(subneighbor));
   // Add this element to the family tree if applicable.
   if (neighbor_in == subneighbor)
     family.push_back(this);
   // Recurse into the elements children, if it has any.
   // Do not clear the vector any more.
   if (this->has_children())
     for (unsigned int c=0; c != this->n_children(); ++c)
       {
         const Elem * current_child = this->child_ptr(c);
         if (current_child != remote_elem)
           for (unsigned int s=0; s != current_child->n_sides(); ++s)
             {
               const Elem * child_neigh = current_child->neighbor_ptr(s);
               if (child_neigh &&
                   (child_neigh == neighbor_in ||
                    (child_neigh->parent() == neighbor_in &&
                     child_neigh->is_ancestor_of(subneighbor))))
                 current_child->total_family_tree_by_subneighbor
                   (family, child_neigh, subneighbor, false);
             }
       }
 }
virtual ElemType libMesh::Tet4::type () const inline virtual
Returns
TET4.
Implements libMesh::Elem.
Definition at line 66 of file cell_tet4.h.
References libMesh::TET4.
 { return TET4; }
unique_id_type libMesh::DofObject::unique_id () const inline inherited
Returns
The globally unique_id for this DofObject
Definition at line 641 of file dof_object.h.
References libMesh::DofObject::_unique_id, libMesh::DofObject::invalid_unique_id, libMesh::libmesh_assert(), and libMesh::DofObject::valid_unique_id().
Referenced by libMesh::UnstructuredMesh::all_first_order(), libMesh::UnstructuredMesh::all_second_order(), libMesh::MeshTools::Modification::all_tri(), libMesh::MeshTools::Generation::build_extrusion(), libMesh::UnstructuredMesh::copy_nodes_and_elements(), libMesh::UnstructuredMesh::create_submesh(), libMesh::MeshTools::Modification::flatten(), libMesh::Elem::get_info(), libMesh::MeshTools::libmesh_assert_valid_unique_ids(), libMesh::Parallel::Packing< const Node * >::pack(), libMesh::Parallel::Packing< const Elem * >::pack(), libMesh::XdrIO::pack_element(), libMesh::CheckpointIO::write_connectivity(), and libMesh::CheckpointIO::write_nodes().
 {
 #ifdef LIBMESH_ENABLE_UNIQUE_ID
   libmesh_assert (this->valid_unique_id());
   return _unique_id;
 #else
   return invalid_unique_id;
 #endif
 }
void libMesh::DofObject::unpack_indexing (std::vector< largest_id_type >::const_iterator begin) inherited
A method for creating our index buffer from packed data - basically with our current implementation we investigate the size term and then copy.
Definition at line 486 of file dof_object.C.
References libMesh::DofObject::_idx_buf, libMesh::DofObject::clear_old_dof_object(), libMesh::DofObject::DofObject(), libMesh::libmesh_assert(), libMesh::DofObject::old_dof_object, and libMesh::DofObject::unpack_indexing().
Referenced by libMesh::Parallel::Packing< Elem * >::unpack(), and libMesh::DofObject::unpack_indexing().
 {
   _idx_buf.clear();
 #ifdef LIBMESH_ENABLE_AMR
   this->clear_old_dof_object();
   const bool has_old_dof_object = cast_int<bool>(*begin++);
 #endif
   const largest_id_type size = *begin++;
   _idx_buf.reserve(size);
   std::copy(begin, begin+size, back_inserter(_idx_buf));
   // Check as best we can for internal consistency now
   libmesh_assert(_idx_buf.empty() ||
                  (_idx_buf[0] <= _idx_buf.size()));
 #ifdef DEBUG
   if (!_idx_buf.empty())
     for (unsigned int i=1; i < _idx_buf[0]; ++i)
       {
         libmesh_assert_greater_equal (_idx_buf[i], _idx_buf[i-1]);
         libmesh_assert_equal_to ((_idx_buf[i] - _idx_buf[i-1])%2, 0);
         libmesh_assert_less_equal (_idx_buf[i], _idx_buf.size());
       }
 #endif
 #ifdef LIBMESH_ENABLE_AMR
   if (has_old_dof_object)
     {
       this->old_dof_object = new DofObject();
       this->old_dof_object->unpack_indexing(begin+size);
     }
 #endif
 }
unsigned int libMesh::DofObject::unpackable_indexing_size (std::vector< largest_id_type >::const_iterator begin) static inherited
If we have indices packed into an buffer for communications, how much of that buffer applies to this dof object?
Definition at line 465 of file dof_object.C.
Referenced by libMesh::Parallel::Packing< const Elem * >::packed_size(), libMesh::Parallel::Packing< const Node * >::packed_size(), and libMesh::Parallel::Packing< Node * >::unpack().
 {
 #ifdef LIBMESH_ENABLE_AMR
   const bool has_old_dof_object = cast_int<bool>(*begin++);
   static const int dof_header_size = 2;
 #else
   static const bool has_old_dof_object = false;
   static const int dof_header_size = 1;
 #endif
   const largest_id_type this_indexing_size = *begin++;
   return cast_int<unsigned int>
     (dof_header_size + this_indexing_size +
      (has_old_dof_object ?
       unpackable_indexing_size(begin+this_indexing_size) : 0));
 }
bool libMesh::DofObject::valid_id () const inline inherited
Returns
true if this DofObject has a valid id set, false otherwise.
Definition at line 666 of file dof_object.h.
References libMesh::DofObject::_id, and libMesh::DofObject::invalid_id.
Referenced by libMesh::ReplicatedMesh::add_elem(), libMesh::DistributedMesh::add_elem(), libMesh::ReplicatedMesh::add_node(), libMesh::DistributedMesh::add_node(), libMesh::Node::get_info(), libMesh::Elem::get_info(), libMesh::DofObject::id(), libMesh::Elem::libmesh_assert_valid_node_pointers(), and libMesh::DofObject::set_id().
 {
   return (DofObject::invalid_id != _id);
 }
bool libMesh::DofObject::valid_processor_id () const inline inherited
Returns
true if this DofObject has a valid id set, false otherwise.
Definition at line 710 of file dof_object.h.
References libMesh::DofObject::_processor_id, and libMesh::DofObject::invalid_processor_id.
Referenced by libMesh::DofObject::set_id().
 {
   return (DofObject::invalid_processor_id != _processor_id);
 }
bool libMesh::DofObject::valid_unique_id () const inline inherited
Returns
true if this DofObject has a valid unique_id set, false otherwise.
Definition at line 674 of file dof_object.h.
References libMesh::DofObject::_unique_id, and libMesh::DofObject::invalid_unique_id.
Referenced by libMesh::ReplicatedMesh::add_elem(), libMesh::DistributedMesh::add_elem(), libMesh::ReplicatedMesh::add_node(), libMesh::DistributedMesh::add_node(), libMesh::ReplicatedMesh::add_point(), libMesh::Elem::get_info(), libMesh::ReplicatedMesh::insert_elem(), libMesh::DistributedMesh::insert_elem(), libMesh::ReplicatedMesh::insert_node(), libMesh::Parallel::Packing< const Node * >::pack(), libMesh::Parallel::Packing< const Elem * >::pack(), libMesh::DofObject::set_id(), and libMesh::DofObject::unique_id().
 {
 #ifdef LIBMESH_ENABLE_UNIQUE_ID
   return (DofObject::invalid_unique_id != _unique_id);
 #else
   return false;
 #endif
 }
dof_id_type libMesh::DofObject::vg_dof_base (const unsigned int s, const unsigned int vg) const inline inherited
VariableGroup DoF indices are indexed as id = base + var_in_vg*ncomp + comp This method allows for direct access to the base.
Definition at line 914 of file dof_object.h.
References libMesh::DofObject::_idx_buf, libMesh::DofObject::n_systems(), libMesh::DofObject::n_var_groups(), and libMesh::DofObject::start_idx().
Referenced by libMesh::DofMap::distribute_local_dofs_node_major(), libMesh::DofMap::distribute_local_dofs_var_major(), libMesh::DofMap::reinit(), libMesh::DofObject::set_id(), libMesh::DofMap::set_nonlocal_dof_objects(), and libMesh::DofObject::set_vg_dof_base().
 {
   libmesh_assert_less (s,  this->n_systems());
   libmesh_assert_less (vg, this->n_var_groups(s));
   const unsigned int
     start_idx_sys = this->start_idx(s);
   libmesh_assert_less ((start_idx_sys + 2*vg + 1), _idx_buf.size());
   // #ifdef DEBUG
   //   std::cout << " [ ";
   //   for (std:size_t i=0; i<_idx_buf.size(); i++)
   //     std::cout << _idx_buf[i] << " ";
   //   std::cout << "]\n";
   // #endif
   return _idx_buf[start_idx_sys + 2*vg + 1];
 }
Real libMesh::Tet4::volume () const virtual
An optimized method for computing the area of a 4-node tetrahedron.
Reimplemented from libMesh::Elem.
Definition at line 287 of file cell_tet4.C.
References libMesh::Elem::point(), and libMesh::triple_product().
 {
   // The volume of a tetrahedron is 1/6 the box product formed
   // by its base and apex vectors
   Point a = point(3) - point(0);
   // b is the vector pointing from 0 to 1
   Point b = point(1) - point(0);
   // c is the vector pointing from 0 to 2
   Point c = point(2) - point(0);
   return triple_product(a, b, c) / 6.;
 }
unsigned int libMesh::Elem::which_child_am_i (const Elem * e) const inline inherited
Returns
The child index which e corresponds to.
I.e. if c = a->which_child_am_i(e); then a->child_ptr(c) will be e.
Definition at line 2272 of file elem.h.
References libMesh::Elem::child_ptr(), libMesh::Elem::has_children(), libMesh::invalid_uint, libMesh::libmesh_assert(), and libMesh::Elem::n_children().
Referenced by libMesh::UnstructuredMesh::all_first_order(), libMesh::BoundaryInfo::boundary_ids(), libMesh::UnstructuredMesh::copy_nodes_and_elements(), libMesh::BoundaryInfo::edge_boundary_ids(), libMesh::UnstructuredMesh::find_neighbors(), libMesh::Elem::make_links_to_me_remote(), libMesh::MeshCommunication::make_p_levels_parallel_consistent(), libMesh::GenericProjector< FFunctor, GFunctor, FValue, ProjectionAction >::operator()(), libMesh::Parallel::Packing< const Elem * >::pack(), libMesh::BoundaryInfo::side_with_boundary_id(), and libMesh::Parallel::sync_element_data_by_parent_id().
 {
   libmesh_assert(e);
   libmesh_assert (this->has_children());
   for (unsigned int c=0; c<this->n_children(); c++)
     if (this->child_ptr(c) == e)
       return c;
   libmesh_error_msg("ERROR:  which_child_am_i() was called with a non-child!");
   return libMesh::invalid_uint;
 }
unsigned int libMesh::Elem::which_neighbor_am_i (const Elem * e) const inline inherited
This function tells you which neighbor e is. I.e. if s = a->which_neighbor_am_i(e); then a->neighbor(s) will be an ancestor of e.
Definition at line 1977 of file elem.h.
References libMesh::invalid_uint, libMesh::Elem::level(), libMesh::libmesh_assert(), libMesh::Elem::n_neighbors(), libMesh::Elem::neighbor_ptr(), and libMesh::Elem::parent().
Referenced by libMesh::ParmetisPartitioner::build_graph(), libMesh::FEGenericBase< OutputType >::compute_proj_constraints(), libMesh::MeshTools::find_hanging_nodes_and_parents(), libMesh::Elem::libmesh_assert_valid_neighbors(), libMesh::Elem::make_links_to_me_remote(), libMesh::Elem::nullify_neighbors(), libMesh::MetisPartitioner::partition_range(), and libMesh::Elem::remove_links_to_me().
 {
   libmesh_assert(e);
   const Elem * eparent = e;
   while (eparent->level() > this->level())
     {
       eparent = eparent->parent();
       libmesh_assert(eparent);
     }
   for (unsigned int s=0; s<this->n_neighbors(); s++)
     if (this->neighbor_ptr(s) == eparent)
       return s;
   return libMesh::invalid_uint;
 }
unsigned int libMesh::Tet::which_node_am_i (unsigned int side, unsigned int side_node) const virtual inherited
Returns
Tet4::side_nodes_map[side][side_node] after doing some range checking.
Implements libMesh::Elem.
Reimplemented in libMesh::Tet10.
Definition at line 66 of file cell_tet.C.
References libMesh::Tet::n_sides(), libMesh::Elem::side(), and side_nodes_map.
Referenced by libMesh::Tet::n_children().
 {
   libmesh_assert_less (side, this->n_sides());
   libmesh_assert_less (side_node, 3);
   return Tet4::side_nodes_map[side][side_node];
 }
unsigned int libMesh::Elem::which_side_am_i (const Elem * e) const inline inherited
This function tells you which side the boundary element e is. I.e. if e = a->build_side_ptr(s) or e = a->side_ptr(s); then a->which_side_am_i(e) will be s.
Note
An exact floating point comparison of the nodal positions of e is made with the nodal positions of this in order to perform this test. The idea is that the test will return a valid side id if e either directly shares Node pointers with this, or was created by exactly copying some of the nodes of this (e.g. through BoundaryMesh::sync()). In these circumstances, non-fuzzy floating point equality is expected.
Returns
The side of this the element which e is, otherwise invalid_uint.
Definition at line 1999 of file elem.h.
References libMesh::invalid_uint, libMesh::Elem::is_node_on_side(), libMesh::libmesh_assert(), libMesh::Elem::n_nodes(), libMesh::Elem::n_sides(), and libMesh::Elem::point().
 {
   libmesh_assert(e);
   const unsigned int ns = this->n_sides();
   const unsigned int nn = this->n_nodes();
   const unsigned int en = e->n_nodes();
   // e might be on any side until proven otherwise
   std::vector<bool> might_be_side(ns, true);
   for (unsigned int i=0; i != en; ++i)
     {
       Point side_point = e->point(i);
       unsigned int local_node_id = libMesh::invalid_uint;
       // Look for a node of this that's contiguous with node i of
       // e. Note that the exact floating point comparison of Point
       // positions is intentional, see the class documentation for
       // this function.
       for (unsigned int j=0; j != nn; ++j)
         if (this->point(j) == side_point)
           local_node_id = j;
       // If a node of e isn't contiguous with some node of this, then
       // e isn't a side of this.
       if (local_node_id == libMesh::invalid_uint)
         return libMesh::invalid_uint;
       // If a node of e isn't contiguous with some node on side s of
       // this, then e isn't on side s.
       for (unsigned int s=0; s != ns; ++s)
         if (!this->is_node_on_side(local_node_id, s))
           might_be_side[s] = false;
     }
   for (unsigned int s=0; s != ns; ++s)
     if (might_be_side[s])
       {
 #ifdef DEBUG
         for (unsigned int s2=s+1; s2 < ns; ++s2)
           libmesh_assert (!might_be_side[s2]);
 #endif
         return s;
       }
   // Didn't find any matching side
   return libMesh::invalid_uint;
 }
void libMesh::Elem::write_connectivity (std::ostream & out, const IOPackage iop) const inherited
Writes the element connectivity for various IO packages to the passed ostream "out". Not virtual, since it is implemented in the base class.
Definition at line 1499 of file elem.C.
References libMesh::Elem::_nodes, libMesh::Elem::connectivity(), libMesh::INVALID_IO_PACKAGE, libMesh::libmesh_assert(), libMesh::Elem::n_nodes(), libMesh::Elem::n_sub_elem(), libMesh::Elem::node_id(), libMesh::TECPLOT, and libMesh::UCD.
Referenced by libMesh::Elem::is_remote().
 {
   libmesh_assert (out_stream.good());
   libmesh_assert(_nodes);
   libmesh_assert_not_equal_to (iop, INVALID_IO_PACKAGE);
   switch (iop)
     {
     case TECPLOT:
       {
         // This connectivity vector will be used repeatedly instead
         // of being reconstructed inside the loop.
         std::vector<dof_id_type> conn;
         for (unsigned int sc=0; sc <this->n_sub_elem(); sc++)
           {
             this->connectivity(sc, TECPLOT, conn);
             std::copy(conn.begin(),
                       conn.end(),
                       std::ostream_iterator<dof_id_type>(out_stream, " "));
             out_stream << '\n';
           }
         return;
       }
     case UCD:
       {
         for (unsigned int i=0; i<this->n_nodes(); i++)
           out_stream << this->node_id(i)+1 << "\t";
         out_stream << '\n';
         return;
       }
     default:
       libmesh_error_msg("Unsupported IO package " << iop);
     }
 }
Member Data Documentation
Elem** libMesh::Elem::_children protected inherited
Pointers to this element's children.
Definition at line 1534 of file elem.h.
Referenced by libMesh::Elem::add_child(), libMesh::Elem::child_ptr(), libMesh::Elem::contract(), libMesh::Elem::Elem(), libMesh::Elem::has_ancestor_children(), libMesh::Elem::has_children(), libMesh::Elem::refine(), and libMesh::Elem::set_child().
ReferenceCounter::Counts libMesh::ReferenceCounter::_counts static protected inherited
Actually holds the data.
Definition at line 124 of file reference_counter.h.
Referenced by libMesh::ReferenceCounter::get_info(), libMesh::ReferenceCounter::increment_constructor_count(), and libMesh::ReferenceCounter::increment_destructor_count().
ReferenceCounter::Counts libMesh::ReferenceCounter::_counts static protected inherited
Actually holds the data.
Definition at line 124 of file reference_counter.h.
Referenced by libMesh::ReferenceCounter::get_info(), libMesh::ReferenceCounter::increment_constructor_count(), and libMesh::ReferenceCounter::increment_destructor_count().
Diagonal libMesh::Tet::_diagonal_selection mutable protected inherited
The currently-selected diagonal used during refinement. Initialized to INVALID_DIAG.
Definition at line 202 of file cell_tet.h.
Referenced by libMesh::Tet::choose_diagonal(), libMesh::Tet::diagonal_selection(), libMesh::Tet10::embedding_matrix(), embedding_matrix(), and libMesh::Tet::select_diagonal().
Elem** libMesh::Elem::_elemlinks protected inherited
Pointers to this element's parent and neighbors, and for lower-dimensional elements' interior_parent.
Definition at line 1528 of file elem.h.
Referenced by libMesh::Elem::Elem(), libMesh::Elem::interior_parent(), libMesh::Elem::neighbor_ptr(), libMesh::Elem::parent(), libMesh::Elem::set_interior_parent(), libMesh::Elem::set_neighbor(), and libMesh::Elem::set_parent().
Elem* libMesh::Tet::_elemlinks_data[5+(LIBMESH_DIM >3)] protected inherited
Data for links to parent/neighbor/interior_parent elements.
Definition at line 183 of file cell_tet.h.
const float libMesh::Tet4::_embedding_matrix static protected
Matrix that computes new nodal locations/solution values from current nodes/solution.
Definition at line 217 of file cell_tet4.h.
Referenced by connectivity(), and embedding_matrix().
bool libMesh::ReferenceCounter::_enable_print_counter = true static protected inherited
Flag to control whether reference count information is printed when print_info is called.
Definition at line 143 of file reference_counter.h.
Referenced by libMesh::ReferenceCounter::disable_print_counter_info(), libMesh::ReferenceCounter::enable_print_counter_info(), and libMesh::ReferenceCounter::print_info().
bool libMesh::ReferenceCounter::_enable_print_counter = true static protected inherited
Flag to control whether reference count information is printed when print_info is called.
Definition at line 143 of file reference_counter.h.
Referenced by libMesh::ReferenceCounter::disable_print_counter_info(), libMesh::ReferenceCounter::enable_print_counter_info(), and libMesh::ReferenceCounter::print_info().
const Real libMesh::Tet::_master_points static protected inherited
Initial value:
=
  {
    {0, 0, 0},
    {1, 0, 0},
    {0, 1, 0},
    {0, 0, 1},
    {0.5, 0, 0},
    {0.5, 0.5, 0},
    {0, 0.5, 0},
    {0, 0, 0.5},
    {0.5, 0, 0.5},
    {0, 0.5, 0.5}
  }
Master element node locations
Definition at line 188 of file cell_tet.h.
Referenced by libMesh::Tet::master_point().
Threads::spin_mutex libMesh::ReferenceCounter::_mutex static protected inherited
Mutual exclusion object to enable thread-safe reference counting.
Definition at line 137 of file reference_counter.h.
Threads::spin_mutex libMesh::ReferenceCounter::_mutex static protected inherited
Mutual exclusion object to enable thread-safe reference counting.
Definition at line 137 of file reference_counter.h.
Threads::atomic< unsigned int > libMesh::ReferenceCounter::_n_objects static protected inherited
The number of objects. Print the reference count information when the number returns to 0.
Definition at line 132 of file reference_counter.h.
Referenced by libMesh::ReferenceCounter::n_objects(), libMesh::ReferenceCounter::ReferenceCounter(), and libMesh::ReferenceCounter::~ReferenceCounter().
Threads::atomic< unsigned int > libMesh::ReferenceCounter::_n_objects static protected inherited
The number of objects. Print the reference count information when the number returns to 0.
Definition at line 132 of file reference_counter.h.
Referenced by libMesh::ReferenceCounter::n_objects(), libMesh::ReferenceCounter::ReferenceCounter(), and libMesh::ReferenceCounter::~ReferenceCounter().
Node* libMesh::Tet4::_nodelinks_data[4] protected
Data for links to nodes.
Definition at line 200 of file cell_tet4.h.
Node** libMesh::Elem::_nodes protected inherited
Pointers to the nodes we are connected to.
Definition at line 1522 of file elem.h.
Referenced by libMesh::Prism6::connectivity(), libMesh::Pyramid5::connectivity(), libMesh::Hex8::connectivity(), libMesh::InfHex8::connectivity(), libMesh::InfPrism6::connectivity(), connectivity(), libMesh::InfPrism12::connectivity(), libMesh::Tet10::connectivity(), libMesh::Hex20::connectivity(), libMesh::Prism15::connectivity(), libMesh::Pyramid13::connectivity(), libMesh::InfHex16::connectivity(), libMesh::Hex27::connectivity(), libMesh::Prism18::connectivity(), libMesh::InfHex18::connectivity(), libMesh::Pyramid14::connectivity(), libMesh::Elem::Elem(), libMesh::Elem::get_node_index(), libMesh::Elem::get_nodes(), libMesh::Tri3Subdivision::local_node_number(), libMesh::Elem::node_id(), libMesh::Elem::node_ptr(), libMesh::Elem::point(), libMesh::Elem::set_node(), and libMesh::Elem::write_connectivity().
unsigned char libMesh::Elem::_p_level protected inherited
p refinement level - the difference between the polynomial degree on this element and the minimum polynomial degree on the mesh. This is stored as an unsigned char to save space. In theory, these last four bytes might have been padding anyway.
Definition at line 1563 of file elem.h.
Referenced by libMesh::Elem::hack_p_level(), libMesh::Elem::max_descendant_p_level(), libMesh::Elem::p_level(), and libMesh::Elem::set_p_level().
unsigned char libMesh::Elem::_pflag protected inherited
p refinement flag. This is stored as an unsigned char to save space.
Definition at line 1553 of file elem.h.
Referenced by libMesh::Elem::p_refinement_flag(), and libMesh::Elem::set_p_refinement_flag().
unsigned char libMesh::Elem::_rflag protected inherited
h refinement flag. This is stored as an unsigned char to save space.
Definition at line 1547 of file elem.h.
Referenced by libMesh::Elem::refinement_flag(), and libMesh::Elem::set_refinement_flag().
subdomain_id_type libMesh::Elem::_sbd_id protected inherited
The subdomain to which this element belongs.
Definition at line 1540 of file elem.h.
Referenced by libMesh::Elem::subdomain_id().
const unsigned int libMesh::Tet4::edge_nodes_map static
Initial value:
=
  {
    {0, 1},
    {1, 2},
    {0, 2},
    {0, 3},
    {1, 3},
    {2, 3}
  }
This maps the node of the edge to element node numbers.
Definition at line 158 of file cell_tet4.h.
Referenced by libMesh::Tet::is_edge_on_side(), and is_node_on_edge().
const dof_id_type libMesh::DofObject::invalid_id = static_cast<dof_id_type>(-1) static inherited
An invaild id to distinguish an uninitialized DofObject
Definition at line 334 of file dof_object.h.
Referenced by libMesh::DofMap::_dof_indices(), libMesh::Node::active(), libMesh::TopologyMap::add_node(), libMesh::MeshRefinement::add_node(), libMesh::ReplicatedMesh::add_point(), libMesh::UnstructuredMesh::all_second_order(), libMesh::MeshTools::Modification::all_tri(), libMesh::Elem::bracketing_nodes(), libMesh::FEGenericBase< OutputType >::compute_periodic_constraints(), libMesh::FEGenericBase< OutputType >::compute_proj_constraints(), libMesh::DofMap::distribute_dofs(), libMesh::DofMap::distribute_local_dofs_node_major(), libMesh::DofMap::distribute_local_dofs_var_major(), libMesh::DofMap::dof_indices(), libMesh::DofObject::dof_number(), libMesh::TopologyMap::find(), libMesh::ReplicatedMesh::insert_node(), libMesh::DofObject::invalidate_dofs(), libMesh::DofObject::invalidate_id(), libMesh::MeshTools::libmesh_assert_valid_neighbors(), libMesh::DistributedMesh::libmesh_assert_valid_parallel_object_ids(), libMesh::Node::Node(), libMesh::Elem::node_id(), libMesh::DofMap::old_dof_indices(), libMesh::Parallel::Packing< const Elem * >::pack(), libMesh::XdrIO::pack_element(), libMesh::Elem::point(), libMesh::XdrIO::polynomial_level_file_name(), libMesh::MeshBase::query_elem(), libMesh::XdrIO::read_serialized_connectivity(), libMesh::ReplicatedMesh::reserve_elem(), libMesh::DistributedMesh::reserve_elem(), libMesh::DofMap::SCALAR_dof_indices(), libMesh::DofObject::set_dof_number(), libMesh::DofObject::set_n_comp_group(), libMesh::DofObject::set_n_vars_per_group(), libMesh::DofMap::set_nonlocal_dof_objects(), libMesh::Parallel::Packing< Elem * >::unpack(), and libMesh::DofObject::valid_id().
const processor_id_type libMesh::DofObject::invalid_processor_id = static_cast<processor_id_type>(-1) static inherited
An invalid processor_id to distinguish DoFs that have not been assigned to a processor.
Definition at line 345 of file dof_object.h.
Referenced by libMesh::BoundaryInfo::_find_id_maps(), libMesh::DistributedMesh::add_elem(), libMesh::DistributedMesh::add_node(), libMesh::MeshCommunication::allgather(), libMesh::MeshTools::create_bounding_box(), libMesh::MeshTools::create_nodal_bounding_box(), libMesh::DistributedMesh::delete_elem(), libMesh::DistributedMesh::delete_node(), libMesh::Elem::Elem(), libMesh::MeshCommunication::find_global_indices(), libMesh::DistributedMesh::insert_elem(), libMesh::DofObject::invalidate_processor_id(), libMesh::DistributedMesh::libmesh_assert_valid_parallel_object_ids(), libMesh::DistributedMesh::n_active_elem(), libMesh::MeshBase::n_elem_on_proc(), libMesh::MeshBase::n_nodes_on_proc(), libMesh::MeshBase::n_unpartitioned_elem(), libMesh::MeshBase::n_unpartitioned_nodes(), libMesh::SparsityPattern::Build::operator()(), libMesh::MeshBase::query_elem(), libMesh::CheckpointIO::read_connectivity(), libMesh::DistributedMesh::renumber_dof_objects(), libMesh::ReplicatedMesh::reserve_elem(), libMesh::DistributedMesh::reserve_elem(), libMesh::Partitioner::set_node_processor_ids(), libMesh::DofMap::set_nonlocal_dof_objects(), libMesh::Partitioner::set_parent_processor_ids(), libMesh::Parallel::sync_dofobject_data_by_id(), libMesh::Parallel::sync_dofobject_data_by_xyz(), libMesh::Parallel::sync_element_data_by_parent_id(), libMesh::Parallel::sync_node_data_by_element_id(), libMesh::MeshTools::total_weight(), libMesh::Parallel::Packing< Node * >::unpack(), libMesh::Parallel::Packing< Elem * >::unpack(), libMesh::DofObject::valid_processor_id(), and libMesh::CheckpointIO::write_connectivity().
const subdomain_id_type libMesh::Elem::invalid_subdomain_id = std::numeric_limits<subdomain_id_type>::max() static inherited
A static integral constant representing an invalid subdomain id. See also DofObject::{invalid_id, invalid_unique_id, invalid_processor_id}.
Note
We don't use the static_cast(-1) trick here since subdomain_id_type is sometimes a signed integer for compatibility reasons (see libmesh/id_types.h).
Normally you can declare static const integral types directly in the header file (C++ standard, 9.4.2/4) but std::numeric_limits<T>::max() is not considered a "constant expression". This one is therefore defined in elem.C. http://stackoverflow.com/questions/2738435/using-numeric-limitsmax-in-constant-expressions
Definition at line 213 of file elem.h.
Referenced by libMesh::BoundaryInfo::_find_id_maps(), libMesh::BoundaryInfo::add_elements(), libMesh::MeshBase::get_id_by_name(), and libMesh::BoundaryInfo::sync().
const unique_id_type libMesh::DofObject::invalid_unique_id = static_cast<unique_id_type>(-1) static inherited
An invaild unique_id to distinguish an uninitialized DofObject
Definition at line 339 of file dof_object.h.
Referenced by libMesh::Parallel::Packing< const Node * >::pack(), libMesh::Parallel::Packing< const Elem * >::pack(), libMesh::DistributedMesh::renumber_dof_objects(), libMesh::DofObject::unique_id(), and libMesh::DofObject::valid_unique_id().
libMesh::Tet4::LIBMESH_ENABLE_TOPOLOGY_CACHES protected
Definition at line 219 of file cell_tet4.h.
DofObject* libMesh::DofObject::old_dof_object inherited
This object on the last mesh. Useful for projecting solutions from one mesh to another.
Definition at line 89 of file dof_object.h.
Referenced by libMesh::OldSolutionValue< Output, point_output >::check_old_context(), libMesh::DofObject::clear_old_dof_object(), libMesh::OldSolutionValue< Output, point_output >::eval_at_node(), libMesh::MeshTools::libmesh_assert_old_dof_objects(), libMesh::DofMap::old_dof_indices(), libMesh::GenericProjector< FFunctor, GFunctor, FValue, ProjectionAction >::operator()(), libMesh::BuildProjectionList::operator()(), libMesh::DofObject::operator=(), libMesh::DofObject::pack_indexing(), libMesh::DofObject::packed_indexing_size(), libMesh::DofMap::reinit(), libMesh::DofObject::set_old_dof_object(), and libMesh::DofObject::unpack_indexing().
const unsigned int libMesh::Tet4::side_nodes_map static
Initial value:
=
  {
    {0, 2, 1},
    {0, 1, 3},
    {1, 2, 3},
    {2, 0, 3}
  }
This maps the node of the side to element node numbers.
Definition at line 152 of file cell_tet4.h.
Referenced by libMesh::Tet::is_child_on_side_helper(), is_node_on_side(), libMesh::Tet::key(), libMesh::Tet::side_ptr(), and libMesh::Tet::which_node_am_i().
const unsigned int libMesh::Elem::type_to_n_edges_map static inherited
This array maps the integer representation of the ElemType enum to the number of edges on the element.
Definition at line 576 of file elem.h.
Referenced by libMesh::Parallel::Packing< const Elem * >::packed_size().
const unsigned int libMesh::Elem::type_to_n_nodes_map static inherited
This array maps the integer representation of the ElemType enum to the number of nodes in the element.
Definition at line 521 of file elem.h.
Referenced by libMesh::XdrIO::pack_element(), libMesh::Parallel::Packing< const Elem * >::packed_size(), libMesh::CheckpointIO::read_connectivity(), libMesh::XdrIO::read_serialized_connectivity(), and libMesh::Parallel::Packing< Elem * >::unpack().
const unsigned int libMesh::Elem::type_to_n_sides_map static inherited
This array maps the integer representation of the ElemType enum to the number of sides on the element.
Definition at line 540 of file elem.h.
Referenced by libMesh::Parallel::Packing< const Elem * >::packed_size().
The documentation for this class was generated from the following files:
cell_tet4.h
cell_tet4.C