libMesh: libMesh::CheckpointIO Class Reference
SomeWebsiteLogo
libMesh::CheckpointIO Class Reference
#include <checkpoint_io.h>
Public Types
typedef largest_id_type xdr_id_type
typedef uint64_t header_id_type
Public Member Functions
CheckpointIO (MeshBase &, const bool=false)
CheckpointIO (const MeshBase &, const bool=false)
virtual ~CheckpointIO ()
virtual void read (const std::string &input_name) override
virtual void write (const std::string &name) override
bool binary () const
bool & binary ()
bool parallel () const
bool & parallel ()
const std::string & version () const
std::string & version ()
const std::vector< processor_id_type > & current_processor_ids () const
std::vector< processor_id_type > & current_processor_ids ()
const processor_id_type & current_n_processors () const
processor_id_type & current_n_processors ()
template<typename file_id_type >
void read_remote_elem (Xdr &io, bool libmesh_dbg_var(expect_all_remote))
virtual void write_equation_systems (const std::string &, const EquationSystems &, const std::set< std::string > *system_names=nullptr)
virtual void write_discontinuous_equation_systems (const std::string &, const EquationSystems &, const std::set< std::string > *system_names=nullptr)
virtual void write_nodal_data (const std::string &, const std::vector< Number > &, const std::vector< std::string > &)
virtual void write_nodal_data (const std::string &, const NumericVector< Number > &, const std::vector< std::string > &)
virtual void write_nodal_data_discontinuous (const std::string &, const std::vector< Number > &, const std::vector< std::string > &)
unsigned int & ascii_precision ()
const Parallel::Communicator & comm () const
processor_id_type n_processors () const
processor_id_type processor_id () const
Static Public Member Functions
static void cleanup (const std::string &input_name, processor_id_type n_procs)
Protected Member Functions
MeshBase & mesh ()
void set_n_partitions (unsigned int n_parts)
void skip_comment_lines (std::istream &in, const char comment_start)
const MeshBase & mesh () const
Protected Attributes
std::vector< bool > elems_of_dimension
const bool _is_parallel_format
const bool _serial_only_needed_on_proc_0
const Parallel::Communicator & _communicator
Private Member Functions
void write_subdomain_names (Xdr &io) const
void write_connectivity (Xdr &io, const std::set< const Elem *, CompareElemIdsByLevel > &elements) const
void write_remote_elem (Xdr &io, const std::set< const Elem *, CompareElemIdsByLevel > &elements) const
void write_nodes (Xdr &io, const std::set< const Node *> &nodeset) const
void write_bcs (Xdr &io, const std::set< const Elem *, CompareElemIdsByLevel > &elements, const std::vector< std::tuple< dof_id_type, unsigned short int, boundary_id_type >> &bc_triples) const
void write_nodesets (Xdr &io, const std::set< const Node *> &nodeset, const std::vector< std::tuple< dof_id_type, boundary_id_type >> &bc_tuples) const
void write_bc_names (Xdr &io, const BoundaryInfo &info, bool is_sideset) const
template<typename file_id_type >
file_id_type read_header (const std::string &name)
template<typename file_id_type >
void read_subfile (Xdr &io, bool expect_all_remote)
template<typename file_id_type >
void read_subdomain_names (Xdr &io)
template<typename file_id_type >
void read_connectivity (Xdr &io)
template<typename file_id_type >
void read_remote_elem (Xdr &io, bool expect_all_remote)
template<typename file_id_type >
void read_nodes (Xdr &io)
template<typename file_id_type >
void read_bcs (Xdr &io)
template<typename file_id_type >
void read_nodesets (Xdr &io)
template<typename file_id_type >
void read_bc_names (Xdr &io, BoundaryInfo &info, bool is_sideset)
unsigned int n_active_levels_in (MeshBase::const_element_iterator begin, MeshBase::const_element_iterator end) const
processor_id_type select_split_config (const std::string &input_name, header_id_type &data_size)
Private Attributes
bool _binary
bool _parallel
std::string _version
std::vector< processor_id_type > _my_processor_ids
processor_id_type _my_n_processors
Detailed Description
The CheckpointIO class can be used to write simplified restart files that can be used to restart simulations that have crashed.
Author
Benjamin Kirk
John Peterson
Derek Gaston
Roy Stogner
Date
2017
Definition at line 60 of file checkpoint_io.h.
Member Typedef Documentation
header_id_type
typedef uint64_t libMesh::CheckpointIO::header_id_type
Definition at line 69 of file checkpoint_io.h.
xdr_id_type
typedef largest_id_type libMesh::CheckpointIO::xdr_id_type
Definition at line 66 of file checkpoint_io.h.
Constructor & Destructor Documentation
CheckpointIO() [1/2]
libMesh::CheckpointIO::CheckpointIO (MeshBase & mesh, const bool binary_in = false) explicit
Constructor. Takes a writable reference to a mesh object. This is the constructor required to read a mesh. The optional parameter binary can be used to switch between ASCII (false, the default) or binary (true) files.
Definition at line 160 of file checkpoint_io.C.
                                                                  :
   MeshInput<MeshBase> (mesh,/* is_parallel_format = */ true),
   MeshOutput<MeshBase>(mesh,/* is_parallel_format = */ true),
   ParallelObject      (mesh),
   _binary             (binary_in),
   _parallel           (false),
   _version            ("checkpoint-1.2"),
   _my_processor_ids   (1, processor_id()),
   _my_n_processors    (mesh.is_replicated() ? 1 : n_processors())
 {
 }
CheckpointIO() [2/2]
libMesh::CheckpointIO::CheckpointIO (const MeshBase & mesh, const bool binary_in = false) explicit
Constructor. Takes a reference to a constant mesh object. This constructor will only allow us to write the mesh. The optional parameter binary can be used to switch between ASCII (false, the default) or binary (true) files.
Definition at line 172 of file checkpoint_io.C.
                                                                        :
   MeshOutput<MeshBase>(mesh,/* is_parallel_format = */ true),
   ParallelObject      (mesh),
   _binary             (binary_in),
   _parallel           (false),
   _my_processor_ids   (1, processor_id()),
   _my_n_processors    (mesh.is_replicated() ? 1 : n_processors())
 {
 }
~CheckpointIO()
libMesh::CheckpointIO::~CheckpointIO () virtual
Destructor.
Definition at line 182 of file checkpoint_io.C.
 {
 }
Member Function Documentation
ascii_precision()
unsigned int & libMesh::MeshOutput< MeshBase >::ascii_precision () inline inherited
Return/set the precision to use when writing ASCII files.
By default we use numeric_limits<Real>::digits10 + 2, which should be enough to write out to ASCII and get the exact same Real back when reading in.
Definition at line 244 of file mesh_output.h.
Referenced by libMesh::TecplotIO::write_ascii(), libMesh::GMVIO::write_ascii_new_impl(), and libMesh::GMVIO::write_ascii_old_impl().
 {
   return _ascii_precision;
 }
binary() [1/2]
bool libMesh::CheckpointIO::binary () const inline
Get/Set the flag indicating if we should read/write binary.
Definition at line 145 of file checkpoint_io.h.
References _binary.
Referenced by read(), read_header(), select_split_config(), and write().
 { return _binary; }
binary() [2/2]
bool& libMesh::CheckpointIO::binary () inline
Definition at line 146 of file checkpoint_io.h.
References _binary.
 { return _binary; }
cleanup()
void libMesh::CheckpointIO::cleanup (const std::string & input_name, processor_id_type n_procs) static
Used to remove a checkpoint directory and its corresponding files. This effectively undoes all the work done be calls to write(...). For example, if a checkpoint configuration was written via:
unsigned int n_splits = 42;
std::unique_ptr<CheckpointIO> cp = split_mesh(my_mesh, n_splits);
// ...
cp->write("foo.cpr");
then you could remove all the corresponding created files/dirs by:
CheckpointIO::cleanup(my_mesh, n_splits);
Or for cases where the split configuration was determined automatically (e.g. via number of running procs with distributed/parallel mesh), then you could:
CheckpointIO::cleanup(your_mesh, your_mesh.comm().size());
Other remaining checkpoint split configurations for the mesh are left unmodified.
Definition at line 245 of file checkpoint_io.C.
 {
   auto header = header_file(input_name, n_procs);
   auto ret = std::remove(header.c_str());
   if (ret != 0)
     libmesh_warning("Failed to clean up checkpoint header '" << header << "': " << std::strerror(ret));
   for (processor_id_type i = 0; i < n_procs; i++)
     {
       auto split = split_file(input_name, n_procs, i);
       ret = std::remove(split.c_str());
       if (ret != 0)
         libmesh_warning("Failed to clean up checkpoint split file '" << split << "': " << std::strerror(ret));
     }
   auto dir = split_dir(input_name, n_procs);
   ret = rmdir(dir.c_str());
   if (ret != 0)
     libmesh_warning("Failed to clean up checkpoint split dir '" << dir << "': " << std::strerror(ret));
   // We expect that this may fail if there are other split configurations still present in this
   // directory - so don't bother to check/warn for failure.
   rmdir(input_name.c_str());
 }
comm()
const Parallel::Communicator& libMesh::ParallelObject::comm () const inline inherited
Returns
A reference to the Parallel::Communicator object used by this mesh.
Definition at line 89 of file parallel_object.h.
References libMesh::ParallelObject::_communicator.
Referenced by libMesh::__libmesh_petsc_diff_solver_jacobian(), libMesh::__libmesh_petsc_diff_solver_monitor(), libMesh::__libmesh_petsc_diff_solver_residual(), libMesh::__libmesh_tao_equality_constraints(), libMesh::__libmesh_tao_equality_constraints_jacobian(), libMesh::__libmesh_tao_gradient(), libMesh::__libmesh_tao_hessian(), libMesh::__libmesh_tao_inequality_constraints(), libMesh::__libmesh_tao_inequality_constraints_jacobian(), libMesh::__libmesh_tao_objective(), libMesh::MeshRefinement::_coarsen_elements(), libMesh::ExactSolution::_compute_error(), libMesh::UniformRefinementEstimator::_estimate_error(), libMesh::BoundaryInfo::_find_id_maps(), libMesh::SlepcEigenSolver< T >::_petsc_shell_matrix_get_diagonal(), libMesh::PetscLinearSolver< T >::_petsc_shell_matrix_get_diagonal(), libMesh::SlepcEigenSolver< T >::_petsc_shell_matrix_mult(), libMesh::PetscLinearSolver< T >::_petsc_shell_matrix_mult(), libMesh::PetscLinearSolver< T >::_petsc_shell_matrix_mult_add(), libMesh::EquationSystems::_read_impl(), libMesh::MeshRefinement::_refine_elements(), libMesh::MeshRefinement::_smooth_flags(), libMesh::PetscDMWrapper::add_dofs_helper(), libMesh::PetscDMWrapper::add_dofs_to_section(), libMesh::ImplicitSystem::add_matrix(), libMesh::System::add_vector(), libMesh::UnstructuredMesh::all_second_order(), libMesh::MeshTools::Modification::all_tri(), libMesh::LaplaceMeshSmoother::allgather_graph(), libMesh::FEMSystem::assemble_qoi(), libMesh::MeshCommunication::assign_global_indices(), libMesh::DofMap::attach_matrix(), libMesh::MeshTools::Generation::build_extrusion(), libMesh::BoundaryInfo::build_node_list_from_side_list(), libMesh::EquationSystems::build_parallel_elemental_solution_vector(), libMesh::EquationSystems::build_parallel_solution_vector(), libMesh::PetscDMWrapper::build_section(), libMesh::PetscDMWrapper::build_sf(), libMesh::MeshBase::cache_elem_dims(), libMesh::System::calculate_norm(), libMesh::DofMap::check_dirichlet_bcid_consistency(), libMesh::PetscDMWrapper::check_section_n_dofs(), libMesh::Nemesis_IO_Helper::compute_num_global_elem_blocks(), libMesh::Nemesis_IO_Helper::compute_num_global_nodesets(), libMesh::Nemesis_IO_Helper::compute_num_global_sidesets(), libMesh::Problem_Interface::computeF(), libMesh::Problem_Interface::computeJacobian(), libMesh::Problem_Interface::computePreconditioner(), libMesh::ExodusII_IO::copy_elemental_solution(), libMesh::MeshTools::correct_node_proc_ids(), libMesh::MeshTools::create_bounding_box(), libMesh::MeshTools::create_nodal_bounding_box(), libMesh::MeshRefinement::create_parent_error_vector(), libMesh::MeshTools::create_processor_bounding_box(), libMesh::MeshTools::create_subdomain_bounding_box(), libMesh::MeshCommunication::delete_remote_elements(), libMesh::DofMap::distribute_dofs(), DMlibMeshFunction(), DMlibMeshJacobian(), DMlibMeshSetSystem_libMesh(), DMVariableBounds_libMesh(), libMesh::MeshRefinement::eliminate_unrefined_patches(), libMesh::EpetraVector< T >::EpetraVector(), libMesh::WeightedPatchRecoveryErrorEstimator::estimate_error(), libMesh::PatchRecoveryErrorEstimator::estimate_error(), libMesh::JumpErrorEstimator::estimate_error(), libMesh::AdjointRefinementEstimator::estimate_error(), libMesh::ExactErrorEstimator::estimate_error(), libMesh::MeshRefinement::flag_elements_by_elem_fraction(), libMesh::MeshRefinement::flag_elements_by_error_fraction(), libMesh::MeshRefinement::flag_elements_by_nelem_target(), libMesh::CondensedEigenSystem::get_eigenpair(), libMesh::DofMap::get_info(), libMesh::ImplicitSystem::get_linear_solver(), libMesh::LocationMap< T >::init(), libMesh::TimeSolver::init(), libMesh::SystemSubsetBySubdomain::init(), libMesh::PetscDMWrapper::init_and_attach_petscdm(), libMesh::EigenSystem::init_data(), libMesh::EigenSystem::init_matrices(), libMesh::OptimizationSystem::initialize_equality_constraints_storage(), libMesh::OptimizationSystem::initialize_inequality_constraints_storage(), libMesh::MeshTools::libmesh_assert_consistent_distributed(), libMesh::MeshTools::libmesh_assert_consistent_distributed_nodes(), libMesh::MeshTools::libmesh_assert_contiguous_dof_ids(), libMesh::MeshTools::libmesh_assert_parallel_consistent_new_node_procids(), libMesh::MeshTools::libmesh_assert_parallel_consistent_procids< Elem >(), libMesh::MeshTools::libmesh_assert_parallel_consistent_procids< Node >(), libMesh::MeshTools::libmesh_assert_topology_consistent_procids< Node >(), libMesh::MeshTools::libmesh_assert_valid_boundary_ids(), libMesh::MeshTools::libmesh_assert_valid_dof_ids(), libMesh::MeshTools::libmesh_assert_valid_neighbors(), libMesh::DistributedMesh::libmesh_assert_valid_parallel_flags(), libMesh::DistributedMesh::libmesh_assert_valid_parallel_object_ids(), libMesh::DistributedMesh::libmesh_assert_valid_parallel_p_levels(), libMesh::MeshTools::libmesh_assert_valid_refinement_flags(), libMesh::MeshTools::libmesh_assert_valid_unique_ids(), libMesh::libmesh_petsc_snes_fd_residual(), libMesh::libmesh_petsc_snes_jacobian(), libMesh::libmesh_petsc_snes_mffd_residual(), libMesh::libmesh_petsc_snes_postcheck(), libMesh::libmesh_petsc_snes_residual(), libMesh::libmesh_petsc_snes_residual_helper(), libMesh::MeshRefinement::limit_level_mismatch_at_edge(), libMesh::MeshRefinement::limit_level_mismatch_at_node(), libMesh::MeshRefinement::limit_overrefined_boundary(), libMesh::MeshRefinement::limit_underrefined_boundary(), libMesh::MeshRefinement::make_coarsening_compatible(), libMesh::MeshCommunication::make_elems_parallel_consistent(), libMesh::MeshRefinement::make_flags_parallel_consistent(), libMesh::MeshCommunication::make_new_node_proc_ids_parallel_consistent(), libMesh::MeshCommunication::make_new_nodes_parallel_consistent(), libMesh::MeshCommunication::make_node_ids_parallel_consistent(), libMesh::MeshCommunication::make_node_proc_ids_parallel_consistent(), libMesh::MeshCommunication::make_node_unique_ids_parallel_consistent(), libMesh::MeshCommunication::make_nodes_parallel_consistent(), libMesh::MeshCommunication::make_p_levels_parallel_consistent(), libMesh::MeshRefinement::make_refinement_compatible(), libMesh::FEMSystem::mesh_position_set(), libMesh::DistributedMesh::n_active_elem(), libMesh::MeshTools::n_active_levels(), libMesh::BoundaryInfo::n_boundary_conds(), libMesh::BoundaryInfo::n_edge_conds(), libMesh::CondensedEigenSystem::n_global_non_condensed_dofs(), libMesh::MeshTools::n_levels(), libMesh::BoundaryInfo::n_nodeset_conds(), libMesh::MeshTools::n_p_levels(), libMesh::BoundaryInfo::n_shellface_conds(), libMesh::DistributedMesh::parallel_max_elem_id(), libMesh::DistributedMesh::parallel_max_node_id(), libMesh::ReplicatedMesh::parallel_max_unique_id(), libMesh::DistributedMesh::parallel_max_unique_id(), libMesh::DistributedMesh::parallel_n_elem(), libMesh::DistributedMesh::parallel_n_nodes(), libMesh::SparsityPattern::Build::parallel_sync(), libMesh::MeshTools::paranoid_n_levels(), libMesh::petsc_auto_fieldsplit(), libMesh::System::point_gradient(), libMesh::System::point_hessian(), libMesh::System::point_value(), libMesh::MeshBase::prepare_for_use(), libMesh::Nemesis_IO::read(), libMesh::XdrIO::read(), read_header(), libMesh::XdrIO::read_header(), libMesh::System::read_header(), libMesh::System::read_legacy_data(), libMesh::System::read_SCALAR_dofs(), libMesh::XdrIO::read_serialized_bc_names(), libMesh::XdrIO::read_serialized_bcs_helper(), libMesh::System::read_serialized_blocked_dof_objects(), libMesh::XdrIO::read_serialized_connectivity(), libMesh::XdrIO::read_serialized_nodes(), libMesh::XdrIO::read_serialized_nodesets(), libMesh::XdrIO::read_serialized_subdomain_names(), libMesh::System::read_serialized_vector(), libMesh::MeshBase::recalculate_n_partitions(), libMesh::MeshRefinement::refine_and_coarsen_elements(), libMesh::DistributedMesh::renumber_dof_objects(), select_split_config(), libMesh::DofMap::set_nonlocal_dof_objects(), libMesh::PetscDMWrapper::set_point_range_in_section(), libMesh::PetscDiffSolver::setup_petsc_data(), libMesh::LaplaceMeshSmoother::smooth(), libMesh::split_mesh(), libMesh::MeshBase::subdomain_ids(), libMesh::BoundaryInfo::sync(), libMesh::MeshRefinement::test_level_one(), libMesh::MeshRefinement::test_unflagged(), libMesh::MeshTools::total_weight(), libMesh::MeshRefinement::uniformly_coarsen(), libMesh::NameBasedIO::write(), libMesh::XdrIO::write(), libMesh::System::write_SCALAR_dofs(), libMesh::XdrIO::write_serialized_bcs_helper(), libMesh::System::write_serialized_blocked_dof_objects(), libMesh::XdrIO::write_serialized_connectivity(), libMesh::XdrIO::write_serialized_nodes(), and libMesh::XdrIO::write_serialized_nodesets().
   { return _communicator; }
current_n_processors() [1/2]
const processor_id_type& libMesh::CheckpointIO::current_n_processors () const inline
Get/Set the n_processors to use
The default n_processors to use is the n_processors() of the mesh.
This is used for m->n parallel checkpoint file writing: You can force CheckpointIO to view the world as if it contains this number of processors by setting it here
Definition at line 183 of file checkpoint_io.h.
References _my_n_processors.
 { return _my_n_processors; }
current_n_processors() [2/2]
processor_id_type& libMesh::CheckpointIO::current_n_processors () inline
Definition at line 184 of file checkpoint_io.h.
References _my_n_processors.
 { return _my_n_processors; }
current_processor_ids() [1/2]
const std::vector<processor_id_type>& libMesh::CheckpointIO::current_processor_ids () const inline
Get/Set the processor id or processor ids to use.
The default processor_id to use is the processor_id() of the mesh.
This is used for m->n parallel checkpoint file writing: You can force CheckpointIO to write out different partitions of a mesh by setting which partitions to write from each processor here.
Definition at line 170 of file checkpoint_io.h.
References _my_processor_ids.
 { return _my_processor_ids; }
current_processor_ids() [2/2]
std::vector<processor_id_type>& libMesh::CheckpointIO::current_processor_ids () inline
Definition at line 171 of file checkpoint_io.h.
References _my_processor_ids.
 { return _my_processor_ids; }
mesh() [1/2]
MeshBase & libMesh::MeshInput< MeshBase >::mesh () inline protected inherited
Returns
The object as a writable reference.
Definition at line 169 of file mesh_input.h.
Referenced by libMesh::GMVIO::_read_one_cell(), libMesh::VTKIO::cells_to_vtk(), libMesh::TetGenIO::element_in(), libMesh::UNVIO::elements_in(), libMesh::UNVIO::elements_out(), libMesh::UNVIO::groups_in(), libMesh::TetGenIO::node_in(), libMesh::UNVIO::nodes_in(), libMesh::UNVIO::nodes_out(), libMesh::VTKIO::nodes_to_vtk(), libMesh::Nemesis_IO::prepare_to_write_nodal_data(), libMesh::Nemesis_IO::read(), libMesh::ExodusII_IO::read(), libMesh::GMVIO::read(), libMesh::XdrIO::read(), read(), libMesh::VTKIO::read(), read_bcs(), read_connectivity(), read_header(), libMesh::XdrIO::read_header(), libMesh::UCDIO::read_implementation(), libMesh::UNVIO::read_implementation(), libMesh::GmshIO::read_mesh(), read_nodes(), read_nodesets(), read_remote_elem(), libMesh::XdrIO::read_serialized_bcs_helper(), libMesh::XdrIO::read_serialized_connectivity(), libMesh::XdrIO::read_serialized_nodes(), libMesh::XdrIO::read_serialized_nodesets(), libMesh::XdrIO::read_serialized_subdomain_names(), libMesh::OFFIO::read_stream(), libMesh::MatlabIO::read_stream(), read_subdomain_names(), libMesh::TetGenIO::write(), libMesh::Nemesis_IO::write(), libMesh::ExodusII_IO::write(), libMesh::XdrIO::write(), write(), libMesh::GMVIO::write_ascii_new_impl(), libMesh::GMVIO::write_ascii_old_impl(), libMesh::GMVIO::write_binary(), libMesh::GMVIO::write_discontinuous_gmv(), libMesh::Nemesis_IO::write_element_data(), libMesh::ExodusII_IO::write_element_data(), libMesh::UCDIO::write_header(), libMesh::UCDIO::write_implementation(), libMesh::UCDIO::write_interior_elems(), libMesh::GmshIO::write_mesh(), libMesh::VTKIO::write_nodal_data(), libMesh::UCDIO::write_nodal_data(), libMesh::ExodusII_IO::write_nodal_data(), libMesh::ExodusII_IO::write_nodal_data_common(), libMesh::ExodusII_IO::write_nodal_data_discontinuous(), libMesh::UCDIO::write_nodes(), write_nodesets(), libMesh::XdrIO::write_parallel(), libMesh::GmshIO::write_post(), libMesh::XdrIO::write_serialized_bcs_helper(), libMesh::XdrIO::write_serialized_connectivity(), libMesh::XdrIO::write_serialized_nodes(), libMesh::XdrIO::write_serialized_nodesets(), libMesh::XdrIO::write_serialized_subdomain_names(), libMesh::UCDIO::write_soln(), and write_subdomain_names().
 {
   if (_obj == nullptr)
     libmesh_error_msg("ERROR: _obj should not be nullptr!");
   return *_obj;
 }
mesh() [2/2]
const MeshBase & libMesh::MeshOutput< MeshBase >::mesh () const inline protected inherited
Returns
The object as a read-only reference.
Definition at line 234 of file mesh_output.h.
Referenced by libMesh::FroIO::write(), libMesh::TecplotIO::write(), libMesh::MEDITIO::write(), libMesh::PostscriptIO::write(), libMesh::EnsightIO::write(), libMesh::TecplotIO::write_ascii(), libMesh::TecplotIO::write_binary(), libMesh::TecplotIO::write_nodal_data(), libMesh::MEDITIO::write_nodal_data(), and libMesh::GnuPlotIO::write_solution().
 {
   libmesh_assert(_obj);
   return *_obj;
 }
n_active_levels_in()
unsigned int libMesh::CheckpointIO::n_active_levels_in (MeshBase::const_element_iterator begin, MeshBase::const_element_iterator end) const private
Returns
The number of levels of refinement in the active mesh on this processor.
Note
This includes all elements on this processor even those not owned by this processor! Implemented by looping over all the active elements and finding the maximum level.
Definition at line 1307 of file checkpoint_io.C.
References libMesh::as_range(), end, std::max(), and libMesh::MeshTools::max_level().
 {
   unsigned int max_level = 0;
   for (const auto & elem : as_range(begin, end))
     max_level = std::max(elem->level(), max_level);
   return max_level + 1;
 }
n_processors()
processor_id_type libMesh::ParallelObject::n_processors () const inline inherited
Returns
The number of processors in the group.
Definition at line 95 of file parallel_object.h.
References libMesh::ParallelObject::_communicator, and libMesh::Parallel::Communicator::size().
Referenced by libMesh::BoundaryInfo::_find_id_maps(), libMesh::PetscDMWrapper::add_dofs_to_section(), libMesh::DistributedMesh::add_elem(), libMesh::DistributedMesh::add_node(), libMesh::LaplaceMeshSmoother::allgather_graph(), libMesh::FEMSystem::assembly(), libMesh::AztecLinearSolver< T >::AztecLinearSolver(), libMesh::BoundaryInfo::build_node_list_from_side_list(), libMesh::EquationSystems::build_parallel_elemental_solution_vector(), libMesh::DistributedMesh::clear(), libMesh::Nemesis_IO_Helper::compute_border_node_ids(), libMesh::Nemesis_IO_Helper::construct_nemesis_filename(), libMesh::UnstructuredMesh::create_pid_mesh(), libMesh::MeshTools::create_processor_bounding_box(), libMesh::DofMap::distribute_dofs(), libMesh::DofMap::distribute_local_dofs_node_major(), libMesh::DofMap::distribute_local_dofs_var_major(), libMesh::EnsightIO::EnsightIO(), libMesh::MeshBase::get_info(), libMesh::SystemSubsetBySubdomain::init(), libMesh::PetscDMWrapper::init_and_attach_petscdm(), libMesh::Nemesis_IO_Helper::initialize(), libMesh::DistributedMesh::insert_elem(), libMesh::MeshTools::libmesh_assert_contiguous_dof_ids(), libMesh::MeshTools::libmesh_assert_parallel_consistent_new_node_procids(), libMesh::MeshTools::libmesh_assert_parallel_consistent_procids< Elem >(), libMesh::MeshTools::libmesh_assert_parallel_consistent_procids< Node >(), libMesh::MeshTools::libmesh_assert_topology_consistent_procids< Node >(), libMesh::MeshTools::libmesh_assert_valid_boundary_ids(), libMesh::MeshTools::libmesh_assert_valid_dof_ids(), libMesh::MeshTools::libmesh_assert_valid_neighbors(), libMesh::MeshTools::libmesh_assert_valid_refinement_flags(), libMesh::DofMap::local_variable_indices(), libMesh::MeshRefinement::make_coarsening_compatible(), libMesh::MeshBase::n_active_elem_on_proc(), libMesh::MeshBase::n_elem_on_proc(), libMesh::MeshBase::n_nodes_on_proc(), libMesh::MeshBase::partition(), libMesh::PetscLinearSolver< T >::PetscLinearSolver(), libMesh::System::point_gradient(), libMesh::System::point_hessian(), libMesh::System::point_value(), libMesh::NameBasedIO::read(), libMesh::Nemesis_IO::read(), read(), read_connectivity(), libMesh::XdrIO::read_header(), read_nodes(), libMesh::System::read_parallel_data(), libMesh::System::read_SCALAR_dofs(), libMesh::System::read_serialized_blocked_dof_objects(), libMesh::System::read_serialized_vector(), libMesh::DistributedMesh::renumber_dof_objects(), libMesh::DofMap::set_nonlocal_dof_objects(), libMesh::PetscDMWrapper::set_point_range_in_section(), libMesh::MeshRefinement::uniformly_coarsen(), libMesh::DistributedMesh::update_parallel_id_counts(), libMesh::GMVIO::write_binary(), libMesh::GMVIO::write_discontinuous_gmv(), libMesh::System::write_parallel_data(), libMesh::System::write_SCALAR_dofs(), libMesh::XdrIO::write_serialized_bcs_helper(), libMesh::System::write_serialized_blocked_dof_objects(), libMesh::XdrIO::write_serialized_connectivity(), libMesh::XdrIO::write_serialized_nodes(), and libMesh::XdrIO::write_serialized_nodesets().
   { return cast_int<processor_id_type>(_communicator.size()); }
parallel() [1/2]
bool libMesh::CheckpointIO::parallel () const inline
Get/Set the flag indicating if we should read/write binary.
Definition at line 151 of file checkpoint_io.h.
References _parallel.
Referenced by write().
 { return _parallel; }
parallel() [2/2]
bool& libMesh::CheckpointIO::parallel () inline
Definition at line 152 of file checkpoint_io.h.
References _parallel.
 { return _parallel; }
processor_id()
processor_id_type libMesh::ParallelObject::processor_id () const inline inherited
Returns
The rank of this processor in the group.
Definition at line 101 of file parallel_object.h.
References libMesh::ParallelObject::_communicator, and libMesh::Parallel::Communicator::rank().
Referenced by libMesh::BoundaryInfo::_find_id_maps(), libMesh::EquationSystems::_read_impl(), libMesh::PetscDMWrapper::add_dofs_to_section(), libMesh::DistributedMesh::add_elem(), libMesh::BoundaryInfo::add_elements(), libMesh::DofMap::add_neighbors_to_send_list(), libMesh::DistributedMesh::add_node(), libMesh::UnstructuredMesh::all_second_order(), libMesh::MeshTools::Modification::all_tri(), libMesh::FEMSystem::assembly(), libMesh::EquationSystems::build_discontinuous_solution_vector(), libMesh::Nemesis_IO_Helper::build_element_and_node_maps(), libMesh::InfElemBuilder::build_inf_elem(), libMesh::BoundaryInfo::build_node_list_from_side_list(), libMesh::EquationSystems::build_parallel_elemental_solution_vector(), libMesh::DistributedMesh::clear(), libMesh::ExodusII_IO_Helper::close(), libMesh::Nemesis_IO_Helper::compute_border_node_ids(), libMesh::Nemesis_IO_Helper::compute_communication_map_parameters(), libMesh::Nemesis_IO_Helper::compute_internal_and_border_elems_and_internal_nodes(), libMesh::Nemesis_IO_Helper::compute_node_communication_maps(), libMesh::Nemesis_IO_Helper::compute_num_global_elem_blocks(), libMesh::Nemesis_IO_Helper::compute_num_global_nodesets(), libMesh::Nemesis_IO_Helper::compute_num_global_sidesets(), libMesh::Nemesis_IO_Helper::construct_nemesis_filename(), libMesh::MeshTools::correct_node_proc_ids(), libMesh::ExodusII_IO_Helper::create(), libMesh::DistributedMesh::delete_elem(), libMesh::DistributedMesh::delete_node(), libMesh::MeshCommunication::delete_remote_elements(), libMesh::DofMap::distribute_dofs(), libMesh::DofMap::distribute_local_dofs_node_major(), libMesh::DofMap::distribute_local_dofs_var_major(), libMesh::DistributedMesh::DistributedMesh(), libMesh::DofMap::end_dof(), libMesh::DofMap::end_old_dof(), libMesh::EnsightIO::EnsightIO(), libMesh::MeshFunction::find_element(), libMesh::MeshFunction::find_elements(), libMesh::UnstructuredMesh::find_neighbors(), libMesh::DofMap::first_dof(), libMesh::DofMap::first_old_dof(), libMesh::Nemesis_IO_Helper::get_cmap_params(), libMesh::Nemesis_IO_Helper::get_eb_info_global(), libMesh::Nemesis_IO_Helper::get_elem_cmap(), libMesh::Nemesis_IO_Helper::get_elem_map(), libMesh::MeshBase::get_info(), libMesh::DofMap::get_info(), libMesh::Nemesis_IO_Helper::get_init_global(), libMesh::Nemesis_IO_Helper::get_init_info(), libMesh::Nemesis_IO_Helper::get_loadbal_param(), libMesh::Nemesis_IO_Helper::get_node_cmap(), libMesh::Nemesis_IO_Helper::get_node_map(), libMesh::Nemesis_IO_Helper::get_ns_param_global(), libMesh::Nemesis_IO_Helper::get_ss_param_global(), libMesh::SparsityPattern::Build::handle_vi_vj(), libMesh::SystemSubsetBySubdomain::init(), libMesh::ExodusII_IO_Helper::initialize(), libMesh::ExodusII_IO_Helper::initialize_element_variables(), libMesh::ExodusII_IO_Helper::initialize_global_variables(), libMesh::ExodusII_IO_Helper::initialize_nodal_variables(), libMesh::DistributedMesh::insert_elem(), libMesh::DofMap::is_evaluable(), libMesh::SparsityPattern::Build::join(), libMesh::DofMap::last_dof(), libMesh::MeshTools::libmesh_assert_consistent_distributed(), libMesh::MeshTools::libmesh_assert_consistent_distributed_nodes(), libMesh::MeshTools::libmesh_assert_contiguous_dof_ids(), libMesh::MeshTools::libmesh_assert_parallel_consistent_procids< Elem >(), libMesh::MeshTools::libmesh_assert_valid_neighbors(), libMesh::DistributedMesh::libmesh_assert_valid_parallel_object_ids(), libMesh::DofMap::local_variable_indices(), libMesh::MeshRefinement::make_coarsening_compatible(), libMesh::MeshBase::n_active_local_elem(), libMesh::BoundaryInfo::n_boundary_conds(), libMesh::BoundaryInfo::n_edge_conds(), libMesh::DofMap::n_local_dofs(), libMesh::System::n_local_dofs(), libMesh::MeshBase::n_local_elem(), libMesh::MeshBase::n_local_nodes(), libMesh::BoundaryInfo::n_nodeset_conds(), libMesh::BoundaryInfo::n_shellface_conds(), libMesh::SparsityPattern::Build::operator()(), libMesh::DistributedMesh::own_node(), libMesh::System::point_gradient(), libMesh::System::point_hessian(), libMesh::System::point_value(), libMesh::Nemesis_IO_Helper::put_cmap_params(), libMesh::Nemesis_IO_Helper::put_elem_cmap(), libMesh::Nemesis_IO_Helper::put_elem_map(), libMesh::Nemesis_IO_Helper::put_loadbal_param(), libMesh::Nemesis_IO_Helper::put_node_cmap(), libMesh::Nemesis_IO_Helper::put_node_map(), libMesh::NameBasedIO::read(), libMesh::Nemesis_IO::read(), libMesh::XdrIO::read(), read(), libMesh::ExodusII_IO_Helper::read_elem_num_map(), libMesh::ExodusII_IO_Helper::read_global_values(), read_header(), libMesh::XdrIO::read_header(), libMesh::System::read_header(), libMesh::System::read_legacy_data(), libMesh::ExodusII_IO_Helper::read_node_num_map(), libMesh::System::read_parallel_data(), libMesh::System::read_SCALAR_dofs(), libMesh::XdrIO::read_serialized_bc_names(), libMesh::XdrIO::read_serialized_bcs_helper(), libMesh::System::read_serialized_blocked_dof_objects(), libMesh::XdrIO::read_serialized_connectivity(), libMesh::System::read_serialized_data(), libMesh::XdrIO::read_serialized_nodes(), libMesh::XdrIO::read_serialized_nodesets(), libMesh::XdrIO::read_serialized_subdomain_names(), libMesh::System::read_serialized_vector(), libMesh::System::read_serialized_vectors(), libMesh::DistributedMesh::renumber_dof_objects(), select_split_config(), libMesh::DofMap::set_nonlocal_dof_objects(), libMesh::PetscDMWrapper::set_point_range_in_section(), libMesh::LaplaceMeshSmoother::smooth(), libMesh::MeshTools::total_weight(), libMesh::MeshRefinement::uniformly_coarsen(), libMesh::Parallel::Packing< T >::unpack(), libMesh::DistributedMesh::update_parallel_id_counts(), libMesh::NameBasedIO::write(), libMesh::XdrIO::write(), write(), libMesh::EquationSystems::write(), libMesh::GMVIO::write_discontinuous_gmv(), libMesh::ExodusII_IO::write_element_data(), libMesh::ExodusII_IO_Helper::write_element_values(), libMesh::ExodusII_IO_Helper::write_elements(), libMesh::ExodusII_IO::write_global_data(), libMesh::ExodusII_IO_Helper::write_global_values(), libMesh::System::write_header(), libMesh::ExodusII_IO::write_information_records(), libMesh::ExodusII_IO_Helper::write_information_records(), libMesh::ExodusII_IO_Helper::write_nodal_coordinates(), libMesh::UCDIO::write_nodal_data(), libMesh::ExodusII_IO::write_nodal_data(), libMesh::ExodusII_IO::write_nodal_data_discontinuous(), libMesh::ExodusII_IO_Helper::write_nodal_values(), libMesh::Nemesis_IO_Helper::write_nodesets(), libMesh::ExodusII_IO_Helper::write_nodesets(), libMesh::System::write_parallel_data(), libMesh::System::write_SCALAR_dofs(), libMesh::XdrIO::write_serialized_bc_names(), libMesh::XdrIO::write_serialized_bcs_helper(), libMesh::System::write_serialized_blocked_dof_objects(), libMesh::XdrIO::write_serialized_connectivity(), libMesh::System::write_serialized_data(), libMesh::XdrIO::write_serialized_nodes(), libMesh::XdrIO::write_serialized_nodesets(), libMesh::XdrIO::write_serialized_subdomain_names(), libMesh::System::write_serialized_vector(), libMesh::System::write_serialized_vectors(), libMesh::Nemesis_IO_Helper::write_sidesets(), libMesh::ExodusII_IO_Helper::write_sidesets(), libMesh::ExodusII_IO::write_timestep(), libMesh::ExodusII_IO_Helper::write_timestep(), and libMesh::ExodusII_IO::write_timestep_discontinuous().
   { return cast_int<processor_id_type>(_communicator.rank()); }
read()
void libMesh::CheckpointIO::read (const std::string & input_name) override virtual
This method implements reading a mesh from a specified file. If the mesh has been split for running on several processors, input_name should simply be the name of the mesh split directory without the "-split[n]" suffix. The number of splits will be determined automatically by the number of processes being used for the mesh at the time of reading.
Implements libMesh::MeshInput< MeshBase >.
Definition at line 750 of file checkpoint_io.C.
References binary(), libMesh::MeshCommunication::broadcast(), libMesh::Xdr::close(), libMesh::DECODE, libMesh::MeshBase::is_replicated(), libMesh::MeshInput< MeshBase >::mesh(), libMesh::MeshInput< MT >::mesh(), libMesh::MeshBase::n_elem(), libMesh::ParallelObject::n_processors(), libMesh::ParallelObject::processor_id(), libMesh::READ, select_split_config(), and libMesh::MeshBase::set_distributed().
Referenced by libMesh::NameBasedIO::read().
 {
   LOG_SCOPE("read()","CheckpointIO");
   MeshBase & mesh = MeshInput<MeshBase>::mesh();
   libmesh_assert(!mesh.n_elem());
   header_id_type data_size;
   processor_id_type input_n_procs = select_split_config(input_name, data_size);
   auto header_name = header_file(input_name, input_n_procs);
   bool input_parallel = input_n_procs > 0;
   // If this is a serial read then we're going to only read the mesh
   // on processor 0, then broadcast it
   if ((input_parallel && !mesh.is_replicated()) || mesh.processor_id() == 0)
     {
       // If we're trying to read a parallel checkpoint file on a
       // replicated mesh, we'll read every file on processor 0 so we
       // can broadcast it later.  If we're on a distributed mesh then
       // we'll read every id to it's own processor and we'll "wrap
       // around" with any ids that exceed our processor count.
       const processor_id_type begin_proc_id =
         (input_parallel && !mesh.is_replicated()) ?
         mesh.processor_id() : 0;
       const processor_id_type stride =
         (input_parallel && !mesh.is_replicated()) ?
         mesh.n_processors() : 1;
       for (processor_id_type proc_id = begin_proc_id; proc_id < input_n_procs;
            proc_id = cast_int<processor_id_type>(proc_id + stride))
         {
           auto file_name = split_file(input_name, input_n_procs, proc_id);
           {
             std::ifstream in (file_name.c_str());
             if (!in.good())
               libmesh_error_msg("ERROR: cannot locate specified file:\n\t" << file_name);
           }
           // Do we expect all our files' remote_elem entries to really
           // be remote?  Only if we're not reading multiple input
           // files on the same processor.
           const bool expect_all_remote =
             (input_n_procs <= mesh.n_processors() &&
              !mesh.is_replicated());
           Xdr io (file_name, this->binary() ? DECODE : READ);
           switch (data_size) {
           case 2:
             this->read_subfile<uint16_t>(io, expect_all_remote);
             break;
           case 4:
             this->read_subfile<uint32_t>(io, expect_all_remote);
             break;
           case 8:
             this->read_subfile<uint64_t>(io, expect_all_remote);
             break;
           default:
             libmesh_error();
           }
           io.close();
         }
     }
   // If the mesh was only read on processor 0 then we need to broadcast it
   if (mesh.is_replicated())
     MeshCommunication().broadcast(mesh);
   // If the mesh is really distributed then we need to make sure it
   // knows that
   else if (mesh.n_processors() > 1)
     mesh.set_distributed();
 }
read_bc_names()
template<typename file_id_type > void libMesh::CheckpointIO::read_bc_names (Xdr & io, BoundaryInfo & info, bool is_sideset) private
Read boundary names information (sideset and nodeset)
Definition at line 1279 of file checkpoint_io.C.
References libMesh::Xdr::data(), libMesh::index_range(), libMesh::BoundaryInfo::set_nodeset_name_map(), and libMesh::BoundaryInfo::set_sideset_name_map().
 {
   std::map<boundary_id_type, std::string> & boundary_map = is_sideset ?
     info.set_sideset_name_map() : info.set_nodeset_name_map();
   std::vector<file_id_type> boundary_ids;
   std::vector<std::string>  boundary_names;
   file_id_type n_boundary_names = 0;
   if (is_sideset)
     io.data(n_boundary_names, "# sideset id to name map");
   else
     io.data(n_boundary_names, "# nodeset id to name map");
   if (n_boundary_names)
     {
       io.data(boundary_ids);
       io.data(boundary_names);
     }
   // Add them back into the map
   for (auto i : index_range(boundary_ids))
     boundary_map[cast_int<boundary_id_type>(boundary_ids[i])] =
       boundary_names[i];
 }
read_bcs()
template<typename file_id_type > void libMesh::CheckpointIO::read_bcs (Xdr & io) private
Read the boundary conditions for a parallel, distributed mesh
Definition at line 1231 of file checkpoint_io.C.
References libMesh::BoundaryInfo::add_side(), libMesh::Xdr::data(), libMesh::MeshBase::get_boundary_info(), libMesh::index_range(), libMesh::MeshInput< MeshBase >::mesh(), and libMesh::MeshInput< MT >::mesh().
 {
   // convenient reference to our mesh
   MeshBase & mesh = MeshInput<MeshBase>::mesh();
   // and our boundary info object
   BoundaryInfo & boundary_info = mesh.get_boundary_info();
   std::vector<file_id_type> element_id_list;
   std::vector<uint16_t> side_list;
   std::vector<file_id_type> bc_id_list;
   io.data(element_id_list, "# element ids for bcs");
   io.data(side_list, "# sides of elements for bcs");
   io.data(bc_id_list, "# bc ids");
   for (auto i : index_range(element_id_list))
     boundary_info.add_side
       (cast_int<dof_id_type>(element_id_list[i]), side_list[i],
        cast_int<boundary_id_type>(bc_id_list[i]));
 }
read_connectivity()
template<typename file_id_type > void libMesh::CheckpointIO::read_connectivity (Xdr & io) private
Read the connectivity for a parallel, distributed mesh
Definition at line 1023 of file checkpoint_io.C.
References libMesh::Elem::add_child(), libMesh::MeshBase::add_elem(), libMesh::Elem::build(), libMesh::Xdr::data(), libMesh::Xdr::data_stream(), libMesh::Elem::dim(), libMesh::MeshBase::elem_ptr(), libMesh::Elem::hack_p_level(), libMesh::MeshInput< MT >::mesh(), libMesh::MeshInput< MeshBase >::mesh(), n_nodes, libMesh::Elem::n_nodes(), libMesh::ParallelObject::n_processors(), libMesh::Elem::node_id(), libMesh::MeshBase::node_ptr(), libMesh::Elem::parent(), libMesh::DofObject::processor_id(), libMesh::MeshBase::query_elem_ptr(), libMesh::DofObject::set_id(), libMesh::MeshBase::set_mesh_dimension(), libMesh::Elem::set_node(), libMesh::Elem::set_p_refinement_flag(), libMesh::Elem::set_refinement_flag(), libMesh::DofObject::set_unique_id(), libMesh::Elem::subdomain_id(), libMesh::Elem::type(), and libMesh::Elem::type_to_n_nodes_map.
 {
   // convenient reference to our mesh
   MeshBase & mesh = MeshInput<MeshBase>::mesh();
   file_id_type n_elems_here;
   io.data(n_elems_here);
   // Keep track of the highest dimensional element we've added to the mesh
   unsigned int highest_elem_dim = 1;
   // RHS: Originally we used invalid_processor_id as a "no parent" tag
   // number, because I'm an idiot.  Let's try to support broken files
   // as much as possible.
   bool file_is_broken = false;
   for (unsigned int i=0; i<n_elems_here; i++)
     {
       // id type pid subdomain_id parent_id
       std::vector<file_id_type> elem_data(6);
       io.data_stream
         (elem_data.data(), cast_int<unsigned int>(elem_data.size()),
          cast_int<unsigned int>(elem_data.size()));
 #ifdef LIBMESH_ENABLE_UNIQUE_ID
       file_id_type unique_id = 0;
       io.data(unique_id, "# unique id");
 #endif
 #ifdef LIBMESH_ENABLE_AMR
       uint16_t p_level = 0;
       io.data(p_level, "# p_level");
       uint16_t rflag, pflag;
       io.data(rflag, "# rflag");
       io.data(pflag, "# pflag");
 #endif
       unsigned int n_nodes = Elem::type_to_n_nodes_map[elem_data[1]];
       // Snag the node ids this element was connected to
       std::vector<file_id_type> conn_data(n_nodes);
       io.data_stream
         (conn_data.data(), cast_int<unsigned int>(conn_data.size()),
          cast_int<unsigned int>(conn_data.size()));
       const dof_id_type id                 =
         cast_int<dof_id_type>      (elem_data[0]);
       const ElemType elem_type             =
         static_cast<ElemType>      (elem_data[1]);
       const processor_id_type proc_id      =
         cast_int<processor_id_type>
         (elem_data[2] % mesh.n_processors());
       const subdomain_id_type subdomain_id =
         cast_int<subdomain_id_type>(elem_data[3]);
       // Old broken files used processsor_id_type(-1)...
       // But we *know* our first element will be level 0
       if (i == 0 && elem_data[4] == 65535)
         file_is_broken = true;
       // On a broken file we can't tell whether a parent of 65535 is a
       // null parent or an actual parent of 65535.  Assuming the
       // former will cause less breakage.
       Elem * parent =
         (elem_data[4] == static_cast<largest_id_type>(-1) ||
          (file_is_broken && elem_data[4] == 65535)) ?
         nullptr : mesh.elem_ptr(cast_int<dof_id_type>(elem_data[4]));
       const unsigned short int child_num   =
         (elem_data[5] == static_cast<largest_id_type>(-1) ||
          (file_is_broken && elem_data[5] == 65535)) ?
         static_cast<unsigned short>(-1) :
         cast_int<unsigned short>(elem_data[5]);
       if (!parent)
         libmesh_assert_equal_to
           (child_num, static_cast<unsigned short>(-1));
       Elem * old_elem = mesh.query_elem_ptr(id);
       // If we already have this element (e.g. from another file,
       // when reading multiple distributed CheckpointIO files into
       // a ReplicatedMesh) then we don't want to add it again
       // (because ReplicatedMesh can't handle that) but we do want
       // to assert consistency between what we're reading and what
       // we have.
       if (old_elem)
         {
           libmesh_assert_equal_to(elem_type, old_elem->type());
           libmesh_assert_equal_to(proc_id, old_elem->processor_id());
           libmesh_assert_equal_to(subdomain_id, old_elem->subdomain_id());
           if (parent)
             libmesh_assert_equal_to(parent, old_elem->parent());
           else
             libmesh_assert(!old_elem->parent());
           libmesh_assert_equal_to(old_elem->n_nodes(), conn_data.size());
           for (unsigned int n=0,
                n_conn = cast_int<unsigned int>(conn_data.size());
                n != n_conn; n++)
             libmesh_assert_equal_to
               (old_elem->node_id(n),
                cast_int<dof_id_type>(conn_data[n]));
         }
       else
         {
           // Create the element
           Elem * elem = Elem::build(elem_type, parent).release();
 #ifdef LIBMESH_ENABLE_UNIQUE_ID
           elem->set_unique_id() = unique_id;
 #endif
           if (elem->dim() > highest_elem_dim)
             highest_elem_dim = elem->dim();
           elem->set_id()       = id;
           elem->processor_id() = proc_id;
           elem->subdomain_id() = subdomain_id;
 #ifdef LIBMESH_ENABLE_AMR
           elem->hack_p_level(p_level);
           elem->set_refinement_flag  (cast_int<Elem::RefinementState>(rflag));
           elem->set_p_refinement_flag(cast_int<Elem::RefinementState>(pflag));
           // Set parent connections
           if (parent)
             {
               // We must specify a child_num, because we will have
               // skipped adding any preceding remote_elem children
               parent->add_child(elem, child_num);
             }
 #endif
           libmesh_assert(elem->n_nodes() == conn_data.size());
           // Connect all the nodes to this element
           for (unsigned int n=0,
                n_conn = cast_int<unsigned int>(conn_data.size());
                n != n_conn; n++)
             elem->set_node(n) =
               mesh.node_ptr(cast_int<dof_id_type>(conn_data[n]));
           mesh.add_elem(elem);
         }
     }
   mesh.set_mesh_dimension(cast_int<unsigned char>(highest_elem_dim));
 }
read_header()
template<typename file_id_type > file_id_type libMesh::CheckpointIO::read_header (const std::string & name) private
Read header data on processor 0, then broadcast. Returns the number of processors for which parallel non-header files have been written, or 0 if files were written in serial.
Definition at line 830 of file checkpoint_io.C.
References binary(), libMesh::Parallel::Communicator::broadcast(), libMesh::ParallelObject::comm(), libMesh::Xdr::data(), libMesh::DECODE, libMesh::MeshBase::get_boundary_info(), libMesh::MeshInput< MeshBase >::mesh(), libMesh::MeshInput< MT >::mesh(), libMesh::Quality::name(), libMesh::ParallelObject::processor_id(), libMesh::READ, libMesh::MeshBase::set_mesh_dimension(), libMesh::BoundaryInfo::set_nodeset_name_map(), libMesh::BoundaryInfo::set_sideset_name_map(), and libMesh::MeshBase::set_subdomain_name_map().
 {
   MeshBase & mesh = MeshInput<MeshBase>::mesh();
   // Hack for codes which don't look at all elem dimensions
   uint16_t mesh_dimension;
   // Will this be a parallel input file?  With how many processors?  Stay tuned!
   uint16_t input_parallel;
   file_id_type input_n_procs;
   // We'll write a header file from processor 0 and broadcast.
   if (this->processor_id() == 0)
     {
       Xdr io (name, this->binary() ? DECODE : READ);
       // read the version, but don't care about it
       std::string input_version;
       io.data(input_version);
       // read the data type, don't care about it this time
       header_id_type data_size;
       io.data (data_size);
       // read the dimension
       io.data (mesh_dimension);
       // Read whether or not this is a parallel file
       io.data(input_parallel);
       // With how many processors?
       if (input_parallel)
         io.data(input_n_procs);
       // read subdomain names
       this->read_subdomain_names<file_id_type>(io);
       // read boundary names
       BoundaryInfo & boundary_info = mesh.get_boundary_info();
       this->read_bc_names<file_id_type>(io, boundary_info, true);  // sideset names
       this->read_bc_names<file_id_type>(io, boundary_info, false); // nodeset names
     }
   // broadcast data from processor 0, set values everywhere
   this->comm().broadcast(mesh_dimension);
   mesh.set_mesh_dimension(cast_int<unsigned char>(mesh_dimension));
   this->comm().broadcast(input_parallel);
   if (input_parallel)
     this->comm().broadcast(input_n_procs);
   else
     input_n_procs = 1;
   std::map<subdomain_id_type, std::string> & subdomain_map =
     mesh.set_subdomain_name_map();
   this->comm().broadcast(subdomain_map);
   BoundaryInfo & boundary_info = mesh.get_boundary_info();
   this->comm().broadcast(boundary_info.set_sideset_name_map());
   this->comm().broadcast(boundary_info.set_nodeset_name_map());
   return input_parallel ? input_n_procs : 0;
 }
read_nodes()
template<typename file_id_type > void libMesh::CheckpointIO::read_nodes (Xdr & io) private
Read the nodal locations for a parallel, distributed mesh
Definition at line 950 of file checkpoint_io.C.
References libMesh::MeshBase::add_point(), libMesh::Xdr::data(), libMesh::Xdr::data_stream(), libMesh::MeshInput< MT >::mesh(), libMesh::MeshInput< MeshBase >::mesh(), libMesh::ParallelObject::n_processors(), libMesh::MeshBase::query_node_ptr(), and libMesh::DofObject::set_unique_id().
 {
   // convenient reference to our mesh
   MeshBase & mesh = MeshInput<MeshBase>::mesh();
   file_id_type n_nodes_here;
   io.data(n_nodes_here, "# n_nodes on proc");
   // Will hold the node id and pid
   std::vector<file_id_type> id_pid(2);
   // For the coordinates
   std::vector<Real> coords(LIBMESH_DIM);
   for (unsigned int i=0; i<n_nodes_here; i++)
     {
       io.data_stream(id_pid.data(), 2, 2);
 #ifdef LIBMESH_ENABLE_UNIQUE_ID
       file_id_type unique_id = 0;
       io.data(unique_id, "# unique id");
 #endif
       io.data_stream(coords.data(), LIBMESH_DIM, LIBMESH_DIM);
       Point p;
       p(0) = coords[0];
 #if LIBMESH_DIM > 1
       p(1) = coords[1];
 #endif
 #if LIBMESH_DIM > 2
       p(2) = coords[2];
 #endif
       const dof_id_type id = cast_int<dof_id_type>(id_pid[0]);
       // "Wrap around" if we see more processors than we're using.
       processor_id_type pid =
         cast_int<processor_id_type>(id_pid[1] % mesh.n_processors());
       // If we already have this node (e.g. from another file, when
       // reading multiple distributed CheckpointIO files into a
       // ReplicatedMesh) then we don't want to add it again (because
       // ReplicatedMesh can't handle that) but we do want to assert
       // consistency between what we're reading and what we have.
       const Node * old_node = mesh.query_node_ptr(id);
       if (old_node)
         {
           libmesh_assert_equal_to(pid, old_node->processor_id());
 #ifdef LIBMESH_ENABLE_UNIQUE_ID
           libmesh_assert_equal_to(unique_id, old_node->unique_id());
 #endif
         }
       else
         {
 #ifdef LIBMESH_ENABLE_UNIQUE_ID
           Node * node =
 #endif
             mesh.add_point(p, id, pid);
 #ifdef LIBMESH_ENABLE_UNIQUE_ID
           node->set_unique_id() = unique_id;
 #endif
         }
     }
 }
read_nodesets()
template<typename file_id_type > void libMesh::CheckpointIO::read_nodesets (Xdr & io) private
Read the nodeset conditions for a parallel, distributed mesh
Definition at line 1256 of file checkpoint_io.C.
References libMesh::BoundaryInfo::add_node(), libMesh::Xdr::data(), libMesh::MeshBase::get_boundary_info(), libMesh::index_range(), libMesh::MeshInput< MeshBase >::mesh(), and libMesh::MeshInput< MT >::mesh().
 {
   // convenient reference to our mesh
   MeshBase & mesh = MeshInput<MeshBase>::mesh();
   // and our boundary info object
   BoundaryInfo & boundary_info = mesh.get_boundary_info();
   std::vector<file_id_type> node_id_list;
   std::vector<file_id_type> bc_id_list;
   io.data(node_id_list, "# node id list");
   io.data(bc_id_list, "# nodeset bc id list");
   for (auto i : index_range(node_id_list))
     boundary_info.add_node
       (cast_int<dof_id_type>(node_id_list[i]),
        cast_int<boundary_id_type>(bc_id_list[i]));
 }
read_remote_elem() [1/2]
template<typename file_id_type > void libMesh::CheckpointIO::read_remote_elem (Xdr & io, bool expect_all_remote) private
Read the remote_elem neighbor and child links for a parallel, distributed mesh
If we expect all these remote_elem links to truly be remote, because we aren't doing an N -> M restart with M < N, then we set expect_all_remote to true and test more assertions.
read_remote_elem() [2/2]
template<typename file_id_type > void libMesh::CheckpointIO::read_remote_elem (Xdr & io, bool libmesh_dbg_varexpect_all_remote)
Definition at line 1177 of file checkpoint_io.C.
References libMesh::Elem::add_child(), libMesh::Xdr::data(), libMesh::MeshBase::elem_ref(), libMesh::index_range(), libMesh::MeshInput< MT >::mesh(), libMesh::MeshInput< MeshBase >::mesh(), libMesh::Elem::neighbor_ptr(), libMesh::Elem::raw_child_ptr(), libMesh::remote_elem, and libMesh::Elem::set_neighbor().
 {
   // convenient reference to our mesh
   MeshBase & mesh = MeshInput<MeshBase>::mesh();
   // Find the remote_elem neighbor links
   std::vector<file_id_type> elem_ids;
   std::vector<uint16_t> elem_sides;
   io.data(elem_ids, "# remote neighbor elem_ids");
   io.data(elem_sides, "# remote neighbor elem_sides");
   libmesh_assert_equal_to(elem_ids.size(), elem_sides.size());
   for (auto i : index_range(elem_ids))
     {
       Elem & elem = mesh.elem_ref(cast_int<dof_id_type>(elem_ids[i]));
       if (!elem.neighbor_ptr(elem_sides[i]))
         elem.set_neighbor(elem_sides[i],
                           const_cast<RemoteElem *>(remote_elem));
       else
         libmesh_assert(!expect_all_remote);
     }
   // Find the remote_elem children links
   std::vector<file_id_type> parent_ids;
   std::vector<uint16_t> child_numbers;
   io.data(parent_ids, "# remote child parent_ids");
   io.data(child_numbers, "# remote child_numbers");
 #ifdef LIBMESH_ENABLE_AMR
   for (auto i : index_range(parent_ids))
     {
       Elem & elem = mesh.elem_ref(cast_int<dof_id_type>(parent_ids[i]));
       // We'd like to assert that no child pointer already exists to
       // be overwritten by remote_elem, but Elem doesn't actually have
       // an API that will return a child pointer without asserting
       // that it isn't nullptr.
       const Elem * child = elem.raw_child_ptr(child_numbers[i]);
       if (!child)
         elem.add_child(const_cast<RemoteElem *>(remote_elem),
                        child_numbers[i]);
       else
         libmesh_assert(!expect_all_remote);
     }
 #endif
 }
read_subdomain_names()
template<typename file_id_type > void libMesh::CheckpointIO::read_subdomain_names (Xdr & io) private
Read subdomain name information
Definition at line 920 of file checkpoint_io.C.
References libMesh::Xdr::data(), libMesh::index_range(), libMesh::MeshInput< MT >::mesh(), libMesh::MeshInput< MeshBase >::mesh(), and libMesh::MeshBase::set_subdomain_name_map().
 {
   MeshBase & mesh = MeshInput<MeshBase>::mesh();
   std::map<subdomain_id_type, std::string> & subdomain_map =
     mesh.set_subdomain_name_map();
   std::vector<file_id_type> subdomain_ids;
   subdomain_ids.reserve(subdomain_map.size());
   std::vector<std::string>  subdomain_names;
   subdomain_names.reserve(subdomain_map.size());
   file_id_type n_subdomain_names = 0;
   io.data(n_subdomain_names, "# subdomain id to name map");
   if (n_subdomain_names)
     {
       io.data(subdomain_ids);
       io.data(subdomain_names);
       for (auto i : index_range(subdomain_ids))
         subdomain_map[cast_int<subdomain_id_type>(subdomain_ids[i])] =
           subdomain_names[i];
     }
 }
read_subfile()
template<typename file_id_type > void libMesh::CheckpointIO::read_subfile (Xdr & io, bool expect_all_remote) private
Read a non-header file
Definition at line 899 of file checkpoint_io.C.
 {
   // read the nodal locations
   this->read_nodes<file_id_type> (io);
   // read connectivity
   this->read_connectivity<file_id_type> (io);
   // read remote_elem connectivity
   this->read_remote_elem<file_id_type> (io, expect_all_remote);
   // read the boundary conditions
   this->read_bcs<file_id_type> (io);
   // read the nodesets
   this->read_nodesets<file_id_type> (io);
 }
select_split_config()
processor_id_type libMesh::CheckpointIO::select_split_config (const std::string & input_name, header_id_type & data_size) private
Definition at line 186 of file checkpoint_io.C.
References _my_n_processors, binary(), libMesh::Parallel::Communicator::broadcast(), libMesh::ParallelObject::comm(), libMesh::Xdr::data(), libMesh::DECODE, libMesh::ParallelObject::processor_id(), and libMesh::READ.
Referenced by read().
 {
   std::string header_name;
   // We'll read a header file from processor 0 and broadcast.
   if (this->processor_id() == 0)
     {
       header_name = header_file(input_name, _my_n_processors);
       {
         // look for header+splits with nprocs equal to _my_n_processors
         std::ifstream in (header_name.c_str());
         if (!in.good())
           {
             // otherwise fall back to a serial/single-split mesh
             header_name = header_file(input_name, 1);
             std::ifstream in2 (header_name.c_str());
             if (!in2.good())
               {
                 libmesh_error_msg("ERROR: cannot locate header file for input '" << input_name << "'");
               }
           }
       }
       Xdr io (header_name, this->binary() ? DECODE : READ);
       // read the version, but don't care about it
       std::string input_version;
       io.data(input_version);
       // read the data type
       io.data (data_size);
     }
   this->comm().broadcast(data_size);
   this->comm().broadcast(header_name);
   // How many per-processor files are here?
   largest_id_type input_n_procs;
   switch (data_size) {
   case 2:
     input_n_procs = this->read_header<uint16_t>(header_name);
     break;
   case 4:
     input_n_procs = this->read_header<uint32_t>(header_name);
     break;
   case 8:
     input_n_procs = this->read_header<uint64_t>(header_name);
     break;
   default:
     libmesh_error();
   }
   if (!input_n_procs)
     input_n_procs = 1;
   return cast_int<processor_id_type>(input_n_procs);
 }
set_n_partitions()
void libMesh::MeshInput< MeshBase >::set_n_partitions (unsigned int n_parts) inline protected inherited
Sets the number of partitions in the mesh. Typically this gets done by the partitioner, but some parallel file formats begin "pre-partitioned".
Definition at line 91 of file mesh_input.h.
References libMesh::MeshInput< MT >::mesh().
Referenced by libMesh::Nemesis_IO::read(), and libMesh::XdrIO::read_header().
 { this->mesh().set_n_partitions() = n_parts; }
skip_comment_lines()
void libMesh::MeshInput< MeshBase >::skip_comment_lines (std::istream & in, const char comment_start) protected inherited
Reads input from in, skipping all the lines that start with the character comment_start.
Definition at line 179 of file mesh_input.h.
Referenced by libMesh::TetGenIO::read(), and libMesh::UCDIO::read_implementation().
 {
   char c, line[256];
   while (in.get(c), c==comment_start)
     in.getline (line, 255);
   // put back first character of
   // first non-comment line
   in.putback (c);
 }
version() [1/2]
const std::string& libMesh::CheckpointIO::version () const inline
Get/Set the version string.
Definition at line 157 of file checkpoint_io.h.
References _version.
 { return _version; }
version() [2/2]
std::string& libMesh::CheckpointIO::version () inline
Definition at line 158 of file checkpoint_io.h.
References _version.
 { return _version; }
write()
void libMesh::CheckpointIO::write (const std::string & name) override virtual
This method implements writing a mesh to a specified file. If the mesh has been split for running on several processors, this will create a subdirectory named "[name]-split[n]" where name is the given name argument and n is the number of processors the mesh is split for running on. For example:
unsigned int n_splits = 42;
std::unique_ptr<CheckpointIO> cp = split_mesh(my_mesh, n_splits);
// ...
cp->write("foo.cpr");
would create a directory named "foo.cpr-split42".
Implements libMesh::MeshOutput< MeshBase >.
Definition at line 270 of file checkpoint_io.C.
References _my_n_processors, _my_processor_ids, _parallel, _version, binary(), libMesh::BoundaryInfo::build_node_list(), libMesh::BoundaryInfo::build_side_list(), libMesh::Xdr::close(), libMesh::connect_children(), libMesh::connect_families(), libMesh::Xdr::data(), libMesh::MeshBase::element_ptr_range(), libMesh::MeshBase::elements_begin(), libMesh::MeshBase::elements_end(), libMesh::ENCODE, libMesh::MeshBase::get_boundary_info(), libMesh::DofObject::invalid_processor_id, libMesh::MeshBase::is_serial(), libMesh::MeshInput< MeshBase >::mesh(), libMesh::MeshOutput< MT >::mesh(), libMesh::MeshBase::mesh_dimension(), libMesh::Quality::name(), parallel(), libMesh::ParallelObject::processor_id(), libMesh::query_ghosting_functors(), libMesh::reconnect_nodes(), libMesh::WRITE, write_bc_names(), write_bcs(), write_connectivity(), write_nodes(), write_nodesets(), write_remote_elem(), and write_subdomain_names().
 {
   LOG_SCOPE("write()", "CheckpointIO");
   // convenient reference to our mesh
   const MeshBase & mesh = MeshOutput<MeshBase>::mesh();
   // FIXME: For backwards compatibility, we'll assume for now that we
   // only want to write distributed meshes in parallel.  Later we can
   // do a gather_to_zero() and support that case too.
   _parallel = _parallel || !mesh.is_serial();
   processor_id_type use_n_procs = 1;
   if (_parallel)
     use_n_procs = _my_n_processors;
   std::string header_file_name = header_file(name, use_n_procs);
   make_dir(name, use_n_procs);
   // We'll write a header file from processor 0 to make it easier to do unambiguous
   // restarts later:
   if (this->processor_id() == 0)
     {
       Xdr io (header_file_name, this->binary() ? ENCODE : WRITE);
       // write the version
       io.data(_version, "# version");
       // write what kind of data type we're using
       header_id_type data_size = sizeof(largest_id_type);
       io.data(data_size, "# integer size");
       // Write out the max mesh dimension for backwards compatibility
       // with code that sets it independently of element dimensions
       {
         uint16_t mesh_dimension = cast_int<uint16_t>(mesh.mesh_dimension());
         io.data(mesh_dimension, "# dimensions");
       }
       // Write out whether or not this is serial output
       {
         uint16_t parallel = _parallel;
         io.data(parallel, "# parallel");
       }
       // If we're writing out a parallel mesh then we need to write the number of processors
       // so we can check it upon reading the file
       if (_parallel)
         {
           largest_id_type n_procs = _my_n_processors;
           io.data(n_procs, "# n_procs");
         }
       // write subdomain names
       this->write_subdomain_names(io);
       // write boundary id names
       const BoundaryInfo & boundary_info = mesh.get_boundary_info();
       write_bc_names(io, boundary_info, true);  // sideset names
       write_bc_names(io, boundary_info, false); // nodeset names
     }
   // If this is a serial mesh written to a serial file then we're only
   // going to write local data from processor 0.  If this is a mesh being
   // written in parallel then we're going to write from every
   // processor.
   std::vector<processor_id_type> ids_to_write;
   // We're going to sort elements by pid in one pass, to avoid sending
   // predicated iterators through the whole mesh N_p times
   std::unordered_map<processor_id_type, std::vector<Elem *>> elements_on_pid;
   if (_parallel)
     {
       ids_to_write = _my_processor_ids;
       for (processor_id_type p : ids_to_write)
         elements_on_pid[p].clear();
       auto eop_end = elements_on_pid.end();
       for (auto & elem : mesh.element_ptr_range())
         {
           const processor_id_type p = elem->processor_id();
           auto eop_it = elements_on_pid.find(p);
           if (eop_it != eop_end)
             eop_it->second.push_back(elem);
         }
     }
   else if (mesh.is_serial())
     {
       if (mesh.processor_id() == 0)
         {
           // placeholder
           ids_to_write.push_back(0);
         }
     }
   else
     {
       libmesh_error_msg("Cannot write serial checkpoint from distributed mesh");
     }
   // Call build_side_list() and build_node_list() just *once* to avoid
   // redundant expensive sorts during mesh splitting.
   const BoundaryInfo & boundary_info = mesh.get_boundary_info();
   std::vector<std::tuple<dof_id_type, unsigned short int, boundary_id_type>>
     bc_triples = boundary_info.build_side_list();
   std::vector<std::tuple<dof_id_type, boundary_id_type>>
     bc_tuples = boundary_info.build_node_list();
   for (const auto & my_pid : ids_to_write)
     {
       auto file_name = split_file(name, use_n_procs, my_pid);
       Xdr io (file_name, this->binary() ? ENCODE : WRITE);
       std::set<const Elem *, CompareElemIdsByLevel> elements;
       // For serial files or for already-distributed meshs, we write
       // everything we can see.
       if (!_parallel || !mesh.is_serial())
         elements.insert(mesh.elements_begin(), mesh.elements_end());
       // For parallel files written from serial meshes we write what
       // we'd be required to keep if we were to be deleting remote
       // elements.  This allows us to write proper parallel files even
       // from a ReplicateMesh.
       //
       // WARNING: If we have a DistributedMesh which used
       // "add_extra_ghost_elem" rather than ghosting functors to
       // preserve elements and which is *also* currently serialized
       // then we're not preserving those elements here.  As a quick
       // workaround user code should delete_remote_elements() before
       // writing the checkpoint; as a long term workaround user code
       // should use ghosting functors instead of extra_ghost_elem
       // lists.
       else
         {
           for (processor_id_type p : {my_pid, DofObject::invalid_processor_id})
             {
               const auto elements_vec_it = elements_on_pid.find(p);
               if (elements_vec_it != elements_on_pid.end())
                 {
                   const auto & p_elements = elements_vec_it->second;
                   Elem * const * elempp = p_elements.data();
                   Elem * const * elemend = elempp + p_elements.size();
                   const MeshBase::const_element_iterator
                     pid_elements_begin = MeshBase::const_element_iterator
                       (elempp, elemend, Predicates::NotNull<Elem * const *>()),
                     pid_elements_end = MeshBase::const_element_iterator
                       (elemend, elemend, Predicates::NotNull<Elem * const *>()),
                     active_pid_elements_begin = MeshBase::const_element_iterator
                       (elempp, elemend, Predicates::Active<Elem * const *>()),
                     active_pid_elements_end = MeshBase::const_element_iterator
                       (elemend, elemend, Predicates::Active<Elem * const *>());
                   query_ghosting_functors
                     (mesh, p, active_pid_elements_begin,
                      active_pid_elements_end, elements);
                   connect_children(mesh, pid_elements_begin,
                                    pid_elements_end, elements);
                 }
               connect_families(elements);
             }
         }
       std::set<const Node *> connected_nodes;
       reconnect_nodes(elements, connected_nodes);
       // write the nodal locations
       this->write_nodes (io, connected_nodes);
       // write connectivity
       this->write_connectivity (io, elements);
       // write remote_elem connectivity
       this->write_remote_elem (io, elements);
       // write the boundary condition information
       this->write_bcs (io, elements, bc_triples);
       // write the nodeset information
       this->write_nodesets (io, connected_nodes, bc_tuples);
       // close it up
       io.close();
     }
   // this->comm().barrier();
 }
write_bc_names()
void libMesh::CheckpointIO::write_bc_names (Xdr & io, const BoundaryInfo & info, bool is_sideset) const private
Write boundary names information (sideset and nodeset)
Definition at line 718 of file checkpoint_io.C.
References libMesh::Xdr::data(), libMesh::BoundaryInfo::get_nodeset_name_map(), and libMesh::BoundaryInfo::get_sideset_name_map().
Referenced by write().
 {
   const std::map<boundary_id_type, std::string> & boundary_map = is_sideset ?
     info.get_sideset_name_map() : info.get_nodeset_name_map();
   std::vector<largest_id_type> boundary_ids;   boundary_ids.reserve(boundary_map.size());
   std::vector<std::string>  boundary_names; boundary_names.reserve(boundary_map.size());
   // We need to loop over the map and make sure that there aren't any invalid entries.  Since we
   // return writable references in boundary_info, it's possible for the user to leave some entity names
   // blank.  We can't write those to the XDA file.
   largest_id_type n_boundary_names = 0;
   for (const auto & pr : boundary_map)
     if (!pr.second.empty())
       {
         n_boundary_names++;
         boundary_ids.push_back(pr.first);
         boundary_names.push_back(pr.second);
       }
   if (is_sideset)
     io.data(n_boundary_names, "# sideset id to name map");
   else
     io.data(n_boundary_names, "# nodeset id to name map");
   // Write out the ids and names in two vectors
   if (n_boundary_names)
     {
       io.data(boundary_ids);
       io.data(boundary_names);
     }
 }
write_bcs()
void libMesh::CheckpointIO::write_bcs (Xdr & io, const std::set< const Elem *, CompareElemIdsByLevel > & elements, const std::vector< std::tuple< dof_id_type, unsigned short int, boundary_id_type >> & bc_triples) const private
Write the side boundary conditions for part of a mesh
Definition at line 650 of file checkpoint_io.C.
References libMesh::Xdr::data(), and libMesh::Xdr::writing().
Referenced by write().
 {
   libmesh_assert (io.writing());
   // Build a list of (elem, side, bc) tuples.
   std::size_t bc_size = bc_triples.size();
   std::vector<largest_id_type> element_id_list;
   std::vector<uint16_t> side_list;
   std::vector<largest_id_type> bc_id_list;
   element_id_list.reserve(bc_size);
   side_list.reserve(bc_size);
   bc_id_list.reserve(bc_size);
   std::unordered_set<dof_id_type> elems;
   for (auto & e : elements)
     elems.insert(e->id());
   for (const auto & t : bc_triples)
     if (elems.count(std::get<0>(t)))
       {
         element_id_list.push_back(std::get<0>(t));
         side_list.push_back(std::get<1>(t));
         bc_id_list.push_back(std::get<2>(t));
       }
   io.data(element_id_list, "# element ids for bcs");
   io.data(side_list, "# sides of elements for bcs");
   io.data(bc_id_list, "# bc ids");
 }
write_connectivity()
void libMesh::CheckpointIO::write_connectivity (Xdr & io, const std::set< const Elem *, CompareElemIdsByLevel > & elements) const private
Write the connectivity for part of a mesh
Definition at line 533 of file checkpoint_io.C.
References libMesh::Xdr::data(), libMesh::Xdr::data_stream(), n_nodes, and libMesh::Xdr::writing().
Referenced by write().
 {
   libmesh_assert (io.writing());
   // Put these out here to reduce memory churn
   // id type pid subdomain_id parent_id
   std::vector<largest_id_type> elem_data(6);
   std::vector<largest_id_type> conn_data;
   largest_id_type n_elems_here = elements.size();
   io.data(n_elems_here, "# number of elements");
   for (const auto & elem : elements)
     {
       unsigned int n_nodes = elem->n_nodes();
       elem_data[0] = elem->id();
       elem_data[1] = elem->type();
       elem_data[2] = elem->processor_id();
       elem_data[3] = elem->subdomain_id();
 #ifdef LIBMESH_ENABLE_AMR
       if (elem->parent() != nullptr)
         {
           elem_data[4] = elem->parent()->id();
           elem_data[5] = elem->parent()->which_child_am_i(elem);
         }
       else
 #endif
         {
           elem_data[4] = static_cast<largest_id_type>(-1);
           elem_data[5] = static_cast<largest_id_type>(-1);
         }
       conn_data.resize(n_nodes);
       for (unsigned int i=0; i<n_nodes; i++)
         conn_data[i] = elem->node_id(i);
       io.data_stream(elem_data.data(),
                      cast_int<unsigned int>(elem_data.size()),
                      cast_int<unsigned int>(elem_data.size()));
 #ifdef LIBMESH_ENABLE_UNIQUE_ID
       largest_id_type unique_id = elem->unique_id();
       io.data(unique_id, "# unique id");
 #endif
 #ifdef LIBMESH_ENABLE_AMR
       uint16_t p_level = cast_int<uint16_t>(elem->p_level());
       io.data(p_level, "# p_level");
       uint16_t rflag = elem->refinement_flag();
       io.data(rflag, "# rflag");
       uint16_t pflag = elem->p_refinement_flag();
       io.data(pflag, "# pflag");
 #endif
       io.data_stream(conn_data.data(),
                      cast_int<unsigned int>(conn_data.size()),
                      cast_int<unsigned int>(conn_data.size()));
     }
 }
write_discontinuous_equation_systems()
void libMesh::MeshOutput< MeshBase >::write_discontinuous_equation_systems (const std::string & fname, const EquationSystems & es, const std::set< std::string > * system_names = nullptr) virtual inherited
This method implements writing a mesh with discontinuous data to a specified file where the data is taken from the EquationSystems object.
Definition at line 92 of file mesh_output.C.
References libMesh::EquationSystems::build_discontinuous_solution_vector(), libMesh::EquationSystems::build_variable_names(), libMesh::EquationSystems::get_mesh(), and libMesh::out.
Referenced by libMesh::ExodusII_IO::write_timestep_discontinuous().
 {
   LOG_SCOPE("write_discontinuous_equation_systems()", "MeshOutput");
   // We may need to gather and/or renumber a DistributedMesh to output
   // it, making that const qualifier in our constructor a dirty lie
   MT & my_mesh = const_cast<MT &>(*_obj);
   // If we're asked to write data that's associated with a different
   // mesh, output files full of garbage are the result.
   libmesh_assert_equal_to(&es.get_mesh(), _obj);
   // A non-renumbered mesh may not have a contiguous numbering, and
   // that needs to be fixed before we can build a solution vector.
   if (my_mesh.max_elem_id() != my_mesh.n_elem() ||
       my_mesh.max_node_id() != my_mesh.n_nodes())
     {
       // If we were allowed to renumber then we should have already
       // been properly renumbered...
       libmesh_assert(!my_mesh.allow_renumbering());
       libmesh_do_once(libMesh::out <<
                       "Warning:  This MeshOutput subclass only supports meshes which are contiguously renumbered!"
                       << std::endl;);
       my_mesh.allow_renumbering(true);
       my_mesh.renumber_nodes_and_elements();
       // Not sure what good going back to false will do here, the
       // renumbering horses have already left the barn...
       my_mesh.allow_renumbering(false);
     }
   MeshSerializer serialize(const_cast<MT &>(*_obj), !_is_parallel_format, _serial_only_needed_on_proc_0);
   // Build the list of variable names that will be written.
   std::vector<std::string> names;
   es.build_variable_names  (names, nullptr, system_names);
   if (!_is_parallel_format)
     {
       // Build the nodal solution values & get the variable
       // names from the EquationSystems object
       std::vector<Number> soln;
       es.build_discontinuous_solution_vector (soln, system_names);
       this->write_nodal_data_discontinuous (fname, soln, names);
     }
   else // _is_parallel_format
     {
       libmesh_not_implemented();
     }
 }
write_equation_systems()
void libMesh::MeshOutput< MeshBase >::write_equation_systems (const std::string & fname, const EquationSystems & es, const std::set< std::string > * system_names = nullptr) virtual inherited
This method implements writing a mesh with data to a specified file where the data is taken from the EquationSystems object.
Reimplemented in libMesh::NameBasedIO.
Definition at line 31 of file mesh_output.C.
References libMesh::EquationSystems::build_parallel_solution_vector(), libMesh::EquationSystems::build_solution_vector(), libMesh::EquationSystems::build_variable_names(), libMesh::EquationSystems::get_mesh(), and libMesh::out.
Referenced by libMesh::Nemesis_IO::write_timestep(), and libMesh::ExodusII_IO::write_timestep().
 {
   LOG_SCOPE("write_equation_systems()", "MeshOutput");
   // We may need to gather and/or renumber a DistributedMesh to output
   // it, making that const qualifier in our constructor a dirty lie
   MT & my_mesh = const_cast<MT &>(*_obj);
   // If we're asked to write data that's associated with a different
   // mesh, output files full of garbage are the result.
   libmesh_assert_equal_to(&es.get_mesh(), _obj);
   // A non-renumbered mesh may not have a contiguous numbering, and
   // that needs to be fixed before we can build a solution vector.
   if (my_mesh.max_elem_id() != my_mesh.n_elem() ||
       my_mesh.max_node_id() != my_mesh.n_nodes())
     {
       // If we were allowed to renumber then we should have already
       // been properly renumbered...
       libmesh_assert(!my_mesh.allow_renumbering());
       libmesh_do_once(libMesh::out <<
                       "Warning:  This MeshOutput subclass only supports meshes which are contiguously renumbered!"
                       << std::endl;);
       my_mesh.allow_renumbering(true);
       my_mesh.renumber_nodes_and_elements();
       // Not sure what good going back to false will do here, the
       // renumbering horses have already left the barn...
       my_mesh.allow_renumbering(false);
     }
   MeshSerializer serialize(const_cast<MT &>(*_obj), !_is_parallel_format, _serial_only_needed_on_proc_0);
   // Build the list of variable names that will be written.
   std::vector<std::string> names;
   es.build_variable_names  (names, nullptr, system_names);
   if (!_is_parallel_format)
     {
       // Build the nodal solution values & get the variable
       // names from the EquationSystems object
       std::vector<Number> soln;
       es.build_solution_vector (soln, system_names);
       this->write_nodal_data (fname, soln, names);
     }
   else // _is_parallel_format
     {
       std::unique_ptr<NumericVector<Number>> parallel_soln =
         es.build_parallel_solution_vector(system_names);
       this->write_nodal_data (fname, *parallel_soln, names);
     }
 }
write_nodal_data() [1/2]
virtual void libMesh::MeshOutput< MeshBase >::write_nodal_data (const std::string & , const std::vector< Number > & , const std::vector< std::string > &) inline virtual inherited
This method implements writing a mesh with nodal data to a specified file where the nodal data and variable names are provided.
Reimplemented in libMesh::ExodusII_IO, libMesh::Nemesis_IO, libMesh::UCDIO, libMesh::NameBasedIO, libMesh::GmshIO, libMesh::GMVIO, libMesh::VTKIO, libMesh::MEDITIO, libMesh::GnuPlotIO, and libMesh::TecplotIO.
Definition at line 105 of file mesh_output.h.
   { libmesh_not_implemented(); }
write_nodal_data() [2/2]
void libMesh::MeshOutput< MeshBase >::write_nodal_data (const std::string & fname, const NumericVector< Number > & parallel_soln, const std::vector< std::string > & names) virtual inherited
This method should be overridden by "parallel" output formats for writing nodal data. Instead of getting a localized copy of the nodal solution vector, it is passed a NumericVector of type=PARALLEL which is in node-major order i.e. (u0,v0,w0, u1,v1,w1, u2,v2,w2, u3,v3,w3, ...) and contains n_nodes*n_vars total entries. Then, it is up to the individual I/O class to extract the required solution values from this vector and write them in parallel.
If not implemented, localizes the parallel vector into a std::vector and calls the other version of this function.
Reimplemented in libMesh::Nemesis_IO.
Definition at line 150 of file mesh_output.C.
References libMesh::NumericVector< T >::localize().
 {
   // This is the fallback implementation for parallel I/O formats that
   // do not yet implement proper writing in parallel, and instead rely
   // on the full solution vector being available on all processors.
   std::vector<Number> soln;
   parallel_soln.localize(soln);
   this->write_nodal_data(fname, soln, names);
 }
write_nodal_data_discontinuous()
virtual void libMesh::MeshOutput< MeshBase >::write_nodal_data_discontinuous (const std::string & , const std::vector< Number > & , const std::vector< std::string > &) inline virtual inherited
This method implements writing a mesh with discontinuous data to a specified file where the nodal data and variables names are provided.
Reimplemented in libMesh::ExodusII_IO.
Definition at line 114 of file mesh_output.h.
   { libmesh_not_implemented(); }
write_nodes()
void libMesh::CheckpointIO::write_nodes (Xdr & io, const std::set< const Node *> & nodeset) const private
Write the nodal locations for part of a mesh
Definition at line 491 of file checkpoint_io.C.
References libMesh::Xdr::data(), and libMesh::Xdr::data_stream().
Referenced by write().
 {
   largest_id_type n_nodes_here = nodeset.size();
   io.data(n_nodes_here, "# n_nodes on proc");
   // Will hold the node id and pid
   std::vector<largest_id_type> id_pid(2);
   // For the coordinates
   std::vector<Real> coords(LIBMESH_DIM);
   for (const auto & node : nodeset)
     {
       id_pid[0] = node->id();
       id_pid[1] = node->processor_id();
       io.data_stream(id_pid.data(), 2, 2);
 #ifdef LIBMESH_ENABLE_UNIQUE_ID
       largest_id_type unique_id = node->unique_id();
       io.data(unique_id, "# unique id");
 #endif
       coords[0] = (*node)(0);
 #if LIBMESH_DIM > 1
       coords[1] = (*node)(1);
 #endif
 #if LIBMESH_DIM > 2
       coords[2] = (*node)(2);
 #endif
       io.data_stream(coords.data(), LIBMESH_DIM, 3);
     }
 }
write_nodesets()
void libMesh::CheckpointIO::write_nodesets (Xdr & io, const std::set< const Node *> & nodeset, const std::vector< std::tuple< dof_id_type, boundary_id_type >> & bc_tuples) const private
Write the nodal boundary conditions for part of a mesh
Definition at line 687 of file checkpoint_io.C.
References libMesh::Xdr::data(), libMesh::MeshInput< MeshBase >::mesh(), libMesh::MeshOutput< MT >::mesh(), libMesh::MeshBase::node_ptr(), and libMesh::Xdr::writing().
Referenced by write().
 {
   libmesh_assert (io.writing());
   // convenient reference to our mesh
   const MeshBase & mesh = MeshOutput<MeshBase>::mesh();
   // Build a list of (node, bc) tuples
   std::size_t nodeset_size = bc_tuples.size();
   std::vector<largest_id_type> node_id_list;
   std::vector<largest_id_type> bc_id_list;
   node_id_list.reserve(nodeset_size);
   bc_id_list.reserve(nodeset_size);
   for (const auto & t : bc_tuples)
     if (nodeset.count(mesh.node_ptr(std::get<0>(t))))
       {
         node_id_list.push_back(std::get<0>(t));
         bc_id_list.push_back(std::get<1>(t));
       }
   io.data(node_id_list, "# node id list");
   io.data(bc_id_list, "# nodeset bc id list");
 }
write_remote_elem()
void libMesh::CheckpointIO::write_remote_elem (Xdr & io, const std::set< const Elem *, CompareElemIdsByLevel > & elements) const private
Write the remote_elem neighbor and child links for part of a mesh
Definition at line 601 of file checkpoint_io.C.
References libMesh::Elem::child_ptr(), libMesh::Xdr::data(), libMesh::Elem::neighbor_ptr(), libMesh::remote_elem, and libMesh::Xdr::writing().
Referenced by write().
 {
   libmesh_assert (io.writing());
   // Find the remote_elem neighbor and child links
   std::vector<largest_id_type> elem_ids, parent_ids;
   std::vector<uint16_t> elem_sides, child_numbers;
   for (const auto & elem : elements)
     {
       for (auto n : elem->side_index_range())
         {
           const Elem * neigh = elem->neighbor_ptr(n);
           if (neigh == remote_elem ||
               (neigh && !elements.count(neigh)))
             {
               elem_ids.push_back(elem->id());
               elem_sides.push_back(n);
             }
         }
 #ifdef LIBMESH_ENABLE_AMR
       if (elem->has_children())
         {
           for (unsigned short c = 0,
                nc = cast_int<unsigned short>(elem->n_children());
                c != nc; ++c)
             {
               const Elem * child = elem->child_ptr(c);
               if (child == remote_elem ||
                   (child && !elements.count(child)))
                 {
                   parent_ids.push_back(elem->id());
                   child_numbers.push_back(c);
                 }
             }
         }
 #endif
     }
   io.data(elem_ids, "# remote neighbor elem_ids");
   io.data(elem_sides, "# remote neighbor elem_sides");
   io.data(parent_ids, "# remote child parent_ids");
   io.data(child_numbers, "# remote child_numbers");
 }
write_subdomain_names()
void libMesh::CheckpointIO::write_subdomain_names (Xdr & io) const private
Write subdomain name information
Definition at line 457 of file checkpoint_io.C.
References libMesh::Xdr::data(), libMesh::MeshBase::get_subdomain_name_map(), libMesh::MeshInput< MeshBase >::mesh(), and libMesh::MeshOutput< MT >::mesh().
Referenced by write().
 {
   {
     const MeshBase & mesh = MeshOutput<MeshBase>::mesh();
     const std::map<subdomain_id_type, std::string> & subdomain_map = mesh.get_subdomain_name_map();
     std::vector<largest_id_type> subdomain_ids;   subdomain_ids.reserve(subdomain_map.size());
     std::vector<std::string>  subdomain_names; subdomain_names.reserve(subdomain_map.size());
     // We need to loop over the map and make sure that there aren't any invalid entries.  Since we
     // return writable references in mesh_base, it's possible for the user to leave some entity names
     // blank.  We can't write those to the XDA file.
     largest_id_type n_subdomain_names = 0;
     for (const auto & pr : subdomain_map)
       if (!pr.second.empty())
         {
           n_subdomain_names++;
           subdomain_ids.push_back(pr.first);
           subdomain_names.push_back(pr.second);
         }
     io.data(n_subdomain_names, "# subdomain id to name map");
     // Write out the ids and names in two vectors
     if (n_subdomain_names)
       {
         io.data(subdomain_ids);
         io.data(subdomain_names);
       }
   }
 }
Member Data Documentation
_binary
bool libMesh::CheckpointIO::_binary private
Definition at line 309 of file checkpoint_io.h.
Referenced by binary().
_communicator
const Parallel::Communicator& libMesh::ParallelObject::_communicator protected inherited
Definition at line 107 of file parallel_object.h.
Referenced by libMesh::EquationSystems::build_parallel_elemental_solution_vector(), libMesh::EquationSystems::build_parallel_solution_vector(), libMesh::ParallelObject::comm(), libMesh::ParallelObject::n_processors(), libMesh::ParallelObject::operator=(), and libMesh::ParallelObject::processor_id().
_is_parallel_format
const bool libMesh::MeshOutput< MeshBase >::_is_parallel_format protected inherited
Flag specifying whether this format is parallel-capable. If this is false (default) I/O is only permitted when the mesh has been serialized.
Definition at line 159 of file mesh_output.h.
Referenced by libMesh::FroIO::write(), libMesh::PostscriptIO::write(), and libMesh::EnsightIO::write().
_my_n_processors
processor_id_type libMesh::CheckpointIO::_my_n_processors private
Definition at line 317 of file checkpoint_io.h.
Referenced by current_n_processors(), select_split_config(), and write().
_my_processor_ids
std::vector<processor_id_type> libMesh::CheckpointIO::_my_processor_ids private
Definition at line 314 of file checkpoint_io.h.
Referenced by current_processor_ids(), and write().
_parallel
bool libMesh::CheckpointIO::_parallel private
Definition at line 310 of file checkpoint_io.h.
Referenced by parallel(), and write().
_serial_only_needed_on_proc_0
const bool libMesh::MeshOutput< MeshBase >::_serial_only_needed_on_proc_0 protected inherited
Flag specifying whether this format can be written by only serializing the mesh to processor zero
If this is false (default) the mesh will be serialized to all processors
Definition at line 168 of file mesh_output.h.
_version
std::string libMesh::CheckpointIO::_version private
Definition at line 311 of file checkpoint_io.h.
Referenced by version(), and write().
elems_of_dimension
std::vector<bool> libMesh::MeshInput< MeshBase >::elems_of_dimension protected inherited
A vector of bools describing what dimension elements have been encountered when reading a mesh.
Definition at line 97 of file mesh_input.h.
Referenced by libMesh::GMVIO::_read_one_cell(), libMesh::UNVIO::elements_in(), libMesh::UNVIO::max_elem_dimension_seen(), libMesh::AbaqusIO::max_elem_dimension_seen(), libMesh::AbaqusIO::read(), libMesh::Nemesis_IO::read(), libMesh::ExodusII_IO::read(), libMesh::GMVIO::read(), libMesh::VTKIO::read(), libMesh::AbaqusIO::read_elements(), libMesh::UCDIO::read_implementation(), libMesh::UNVIO::read_implementation(), and libMesh::XdrIO::read_serialized_connectivity().
The documentation for this class was generated from the following files:
checkpoint_io.h
checkpoint_io.C