libMesh: libMesh::SteadySolver Class Reference
SomeWebsiteLogo
libMesh::SteadySolver Class Reference
#include <steady_solver.h>
Public Types
typedef DifferentiableSystem sys_type
typedef TimeSolver Parent
Public Member Functions
SteadySolver (sys_type &s)
virtual ~SteadySolver ()
virtual Real error_order () const
virtual bool element_residual (bool request_jacobian, DiffContext &) libmesh_override
virtual bool side_residual (bool request_jacobian, DiffContext &) libmesh_override
virtual bool nonlocal_residual (bool request_jacobian, DiffContext &) libmesh_override
virtual Real du (const SystemNorm &) const libmesh_override
virtual bool is_steady () const libmesh_override
virtual void init ()
virtual void init_data ()
virtual void reinit ()
virtual void solve ()
virtual void advance_timestep ()
virtual void adjoint_advance_timestep ()
virtual void retrieve_timestep ()
virtual void before_timestep ()
const sys_type & system () const
sys_type & system ()
virtual std::unique_ptr< DiffSolver > & diff_solver ()
virtual std::unique_ptr< LinearSolver< Number > > & linear_solver ()
void set_solution_history (const SolutionHistory &_solution_history)
bool is_adjoint () const
void set_is_adjoint (bool _is_adjoint_value)
Static Public Member Functions
static std::string get_info ()
static void print_info (std::ostream &out=libMesh::out)
static unsigned int n_objects ()
static void enable_print_counter_info ()
static void disable_print_counter_info ()
Public Attributes
bool quiet
unsigned int reduce_deltat_on_diffsolver_failure
Protected Types
typedef bool(DifferentiablePhysics::* ResFuncType) (bool, DiffContext &)
typedef void(DiffContext::* ReinitFuncType) (Real)
typedef std::map< std::string, std::pair< unsigned int, unsigned int > > Counts
Protected Member Functions
virtual bool _general_residual (bool request_jacobian, DiffContext &, ResFuncType time_deriv, ResFuncType constraint)
void increment_constructor_count (const std::string &name)
void increment_destructor_count (const std::string &name)
Protected Attributes
std::unique_ptr< DiffSolver > _diff_solver
std::unique_ptr< LinearSolver< Number > > _linear_solver
sys_type & _system
std::unique_ptr< SolutionHistory > solution_history
Static Protected Attributes
static Counts _counts
static Threads::atomic< unsigned int > _n_objects
static Threads::spin_mutex _mutex
static bool _enable_print_counter = true
Detailed Description
This class implements a TimeSolver which does a single solve of the steady state problem.
This class is part of the new DifferentiableSystem framework, which is still experimental. Users of this framework should beware of bugs and future API changes.
Author
Roy H. Stogner
Date
2006
Definition at line 47 of file steady_solver.h.
Member Typedef Documentation
typedef std::map<std::string, std::pair<unsigned int, unsigned int> > libMesh::ReferenceCounter::Counts protected inherited
Data structure to log the information. The log is identified by the class name.
Definition at line 119 of file reference_counter.h.
typedef TimeSolver libMesh::SteadySolver::Parent
The parent class
Definition at line 58 of file steady_solver.h.
typedef void(DiffContext::* libMesh::TimeSolver::ReinitFuncType) (Real) protected inherited
Definition at line 273 of file time_solver.h.
typedef bool(DifferentiablePhysics::* libMesh::TimeSolver::ResFuncType) (bool, DiffContext &) protected inherited
Definitions of argument types for use in refactoring subclasses.
Definition at line 271 of file time_solver.h.
typedef DifferentiableSystem libMesh::SteadySolver::sys_type
The type of system
Definition at line 53 of file steady_solver.h.
Constructor & Destructor Documentation
libMesh::SteadySolver::SteadySolver (sys_type & s) inline explicit
Constructor. Requires a reference to the system to be solved.
Definition at line 65 of file steady_solver.h.
References ~SteadySolver().
 : Parent(s) {}
libMesh::SteadySolver::~SteadySolver () virtual
Destructor.
Definition at line 28 of file steady_solver.C.
Referenced by SteadySolver().
 {
 }
Member Function Documentation
bool libMesh::SteadySolver::_general_residual (bool request_jacobian, DiffContext & context, ResFuncType time_deriv, ResFuncType constraint) protected virtual
This method is the underlying implementation of the public residual methods.
Definition at line 67 of file steady_solver.C.
References libMesh::TimeSolver::_system, libMesh::DiffContext::fixed_solution_derivative, libMesh::DiffContext::get_elem_fixed_solution(), libMesh::DiffContext::get_elem_solution(), libMesh::DifferentiableSystem::get_physics(), and libMesh::System::use_fixed_solution.
Referenced by element_residual(), is_steady(), nonlocal_residual(), and side_residual().
 {
   // If a fixed solution is requested, it will just be the current
   // solution
   if (_system.use_fixed_solution)
     {
       context.get_elem_fixed_solution() = context.get_elem_solution();
       context.fixed_solution_derivative = 1.0;
     }
   bool jacobian_computed =
     (_system.get_physics()->*time_deriv)(request_jacobian, context);
   // The user shouldn't compute a jacobian unless requested
   libmesh_assert (request_jacobian || !jacobian_computed);
   bool jacobian_computed2 =
     (_system.get_physics()->*constraint)(jacobian_computed, context);
   // The user shouldn't compute a jacobian unless requested
   libmesh_assert (jacobian_computed || !jacobian_computed2);
   return jacobian_computed2;
 }
void libMesh::TimeSolver::adjoint_advance_timestep () virtual inherited
This method advances the adjoint solution to the previous timestep, after an adjoint_solve() has been performed. This will be done before every UnsteadySolver::adjoint_solve().
Reimplemented in libMesh::UnsteadySolver, and libMesh::NewmarkSolver.
Definition at line 106 of file time_solver.C.
 {
 }
void libMesh::TimeSolver::advance_timestep () virtual inherited
This method advances the solution to the next timestep, after a solve() has been performed. Often this will be done after every UnsteadySolver::solve(), but adaptive mesh refinement and/or adaptive time step selection may require some solve() steps to be repeated.
Reimplemented in libMesh::EigenTimeSolver, libMesh::UnsteadySolver, libMesh::AdaptiveTimeSolver, and libMesh::NewmarkSolver.
Definition at line 102 of file time_solver.C.
 {
 }
virtual void libMesh::TimeSolver::before_timestep () inline virtual inherited
This method is for subclasses or users to override to do arbitrary processing between timesteps
Definition at line 167 of file time_solver.h.
 {}
virtual std::unique_ptr<DiffSolver>& libMesh::TimeSolver::diff_solver () inline virtual inherited
An implicit linear or nonlinear solver to use at each timestep.
Reimplemented in libMesh::AdaptiveTimeSolver.
Definition at line 182 of file time_solver.h.
References libMesh::TimeSolver::_diff_solver.
Referenced by libMesh::TimeSolver::init(), libMesh::TimeSolver::init_data(), libMesh::TimeSolver::reinit(), and libMesh::TimeSolver::solve().
 { return _diff_solver; }
void libMesh::ReferenceCounter::disable_print_counter_info () static inherited
Definition at line 107 of file reference_counter.C.
References libMesh::ReferenceCounter::_enable_print_counter.
Referenced by libMesh::LibMeshInit::LibMeshInit(), and libMesh::ReferenceCounter::n_objects().
 {
   _enable_print_counter = false;
   return;
 }
virtual Real libMesh::SteadySolver::du (const SystemNorm &) const inline virtual
Returns
0, but derived classes should override this function to compute the size of the difference between successive solution iterates ||u^{n+1} - u^{n}|| in some norm.
Implements libMesh::TimeSolver.
Definition at line 107 of file steady_solver.h.
 { return 0; }
bool libMesh::SteadySolver::element_residual (bool request_jacobian, DiffContext & context) virtual
This method uses the DifferentiablePhysics' element_time_derivative() and element_constraint() to build a full residual/jacobian on an element.
Implements libMesh::TimeSolver.
Definition at line 34 of file steady_solver.C.
References _general_residual(), libMesh::DifferentiablePhysics::element_constraint(), and libMesh::DifferentiablePhysics::element_time_derivative().
Referenced by error_order().
 {
   return this->_general_residual(request_jacobian,
                                  context,
                                  &DifferentiablePhysics::element_time_derivative,
                                  &DifferentiablePhysics::element_constraint);
 }
void libMesh::ReferenceCounter::enable_print_counter_info () static inherited
Methods to enable/disable the reference counter output from print_info()
Definition at line 101 of file reference_counter.C.
References libMesh::ReferenceCounter::_enable_print_counter.
Referenced by libMesh::ReferenceCounter::n_objects().
 {
   _enable_print_counter = true;
   return;
 }
virtual Real libMesh::SteadySolver::error_order () const inline virtual
error convergence order against deltat is not applicable to a steady problem.
Definition at line 76 of file steady_solver.h.
References element_residual(), nonlocal_residual(), and side_residual().
 { return 0.; }
std::string libMesh::ReferenceCounter::get_info () static inherited
Gets a string containing the reference information.
Definition at line 47 of file reference_counter.C.
References libMesh::ReferenceCounter::_counts, and libMesh::Quality::name().
Referenced by libMesh::ReferenceCounter::print_info().
 {
 #if defined(LIBMESH_ENABLE_REFERENCE_COUNTING) && defined(DEBUG)
   std::ostringstream oss;
   oss << '\n'
       << " ---------------------------------------------------------------------------- \n"
       << "| Reference count information                                                |\n"
       << " ---------------------------------------------------------------------------- \n";
   for (Counts::iterator it = _counts.begin();
        it != _counts.end(); ++it)
     {
       const std::string name(it->first);
       const unsigned int creations    = it->second.first;
       const unsigned int destructions = it->second.second;
       oss << "| " << name << " reference count information:\n"
           << "|  Creations:    " << creations    << '\n'
           << "|  Destructions: " << destructions << '\n';
     }
   oss << " ---------------------------------------------------------------------------- \n";
   return oss.str();
 #else
   return "";
 #endif
 }
void libMesh::ReferenceCounter::increment_constructor_count (const std::string & name) inline protected inherited
Increments the construction counter. Should be called in the constructor of any derived class that will be reference counted.
Definition at line 185 of file reference_counter.h.
References libMesh::ReferenceCounter::_counts, libMesh::Quality::name(), and libMesh::Threads::spin_mtx.
Referenced by libMesh::ReferenceCounter::n_objects(), and libMesh::ReferenceCountedObject< RBParametrized >::ReferenceCountedObject().
 {
   Threads::spin_mutex::scoped_lock lock(Threads::spin_mtx);
   std::pair<unsigned int, unsigned int> & p = _counts[name];
   p.first++;
 }
void libMesh::ReferenceCounter::increment_destructor_count (const std::string & name) inline protected inherited
Increments the destruction counter. Should be called in the destructor of any derived class that will be reference counted.
Definition at line 198 of file reference_counter.h.
References libMesh::ReferenceCounter::_counts, libMesh::Quality::name(), and libMesh::Threads::spin_mtx.
Referenced by libMesh::ReferenceCounter::n_objects(), and libMesh::ReferenceCountedObject< RBParametrized >::~ReferenceCountedObject().
 {
   Threads::spin_mutex::scoped_lock lock(Threads::spin_mtx);
   std::pair<unsigned int, unsigned int> & p = _counts[name];
   p.second++;
 }
void libMesh::TimeSolver::init () virtual inherited
The initialization function. This method is used to initialize internal data structures before a simulation begins.
Reimplemented in libMesh::EigenTimeSolver, libMesh::AdaptiveTimeSolver, libMesh::UnsteadySolver, and libMesh::SecondOrderUnsteadySolver.
Definition at line 64 of file time_solver.C.
References libMesh::TimeSolver::_system, libMesh::LinearSolver< T >::build(), libMesh::DiffSolver::build(), libMesh::ParallelObject::comm(), libMesh::TimeSolver::diff_solver(), libmesh_nullptr, and libMesh::TimeSolver::linear_solver().
Referenced by libMesh::UnsteadySolver::init().
 {
   // If the user hasn't given us a solver to use,
   // just build a default solver
   if (this->diff_solver().get() == libmesh_nullptr)
     this->diff_solver() = DiffSolver::build(_system);
   if (this->linear_solver().get() == libmesh_nullptr)
     this->linear_solver() = LinearSolver<Number>::build(_system.comm());
 }
void libMesh::TimeSolver::init_data () virtual inherited
The data initialization function. This method is used to initialize internal data structures after the underlying System has been initialized
Reimplemented in libMesh::UnsteadySolver, and libMesh::SecondOrderUnsteadySolver.
Definition at line 77 of file time_solver.C.
References libMesh::TimeSolver::_system, libMesh::TimeSolver::diff_solver(), libMesh::TimeSolver::linear_solver(), libMesh::System::name(), and libMesh::on_command_line().
Referenced by libMesh::UnsteadySolver::init_data().
 {
   this->diff_solver()->init();
   if (libMesh::on_command_line("--solver_system_names"))
     this->linear_solver()->init((_system.name()+"_").c_str());
   else
     this->linear_solver()->init();
 }
bool libMesh::TimeSolver::is_adjoint () const inline inherited
Accessor for querying whether we need to do a primal or adjoint solve
Definition at line 233 of file time_solver.h.
References libMesh::TimeSolver::_is_adjoint.
Referenced by libMesh::FEMSystem::build_context().
   { return _is_adjoint; }
virtual bool libMesh::SteadySolver::is_steady () const inline virtual
This is a steady-state solver.
Implements libMesh::TimeSolver.
Definition at line 112 of file steady_solver.h.
References _general_residual().
 { return true; }
virtual std::unique_ptr<LinearSolver<Number> >& libMesh::TimeSolver::linear_solver () inline virtual inherited
An implicit linear solver to use for adjoint and sensitivity problems.
Reimplemented in libMesh::AdaptiveTimeSolver.
Definition at line 187 of file time_solver.h.
References libMesh::TimeSolver::_linear_solver.
Referenced by libMesh::TimeSolver::init(), libMesh::TimeSolver::init_data(), and libMesh::TimeSolver::reinit().
 { return _linear_solver; }
static unsigned int libMesh::ReferenceCounter::n_objects () inline static inherited
Prints the number of outstanding (created, but not yet destroyed) objects.
Definition at line 85 of file reference_counter.h.
References libMesh::ReferenceCounter::_n_objects, libMesh::ReferenceCounter::disable_print_counter_info(), libMesh::ReferenceCounter::enable_print_counter_info(), libMesh::ReferenceCounter::increment_constructor_count(), libMesh::ReferenceCounter::increment_destructor_count(), and libMesh::Quality::name().
Referenced by libMesh::System::hide_output(), and libMesh::LibMeshInit::LibMeshInit().
   { return _n_objects; }
bool libMesh::SteadySolver::nonlocal_residual (bool request_jacobian, DiffContext & context) virtual
This method uses the DifferentiablePhysics' nonlocal_time_derivative() and nonlocal_constraint() to build a full residual/jacobian for non-local terms.
Implements libMesh::TimeSolver.
Definition at line 56 of file steady_solver.C.
References _general_residual(), libMesh::DifferentiablePhysics::nonlocal_constraint(), and libMesh::DifferentiablePhysics::nonlocal_time_derivative().
Referenced by error_order().
 {
   return this->_general_residual(request_jacobian,
                                  context,
                                  &DifferentiablePhysics::nonlocal_time_derivative,
                                  &DifferentiablePhysics::nonlocal_constraint);
 }
void libMesh::ReferenceCounter::print_info (std::ostream & out = libMesh::out) static inherited
Prints the reference information, by default to libMesh::out.
Definition at line 88 of file reference_counter.C.
References libMesh::ReferenceCounter::_enable_print_counter, and libMesh::ReferenceCounter::get_info().
Referenced by libMesh::LibMeshInit::LibMeshInit().
 {
   if (_enable_print_counter)
     out_stream << ReferenceCounter::get_info();
 }
void libMesh::TimeSolver::reinit () virtual inherited
The reinitialization function. This method is used after changes in the mesh
Reimplemented in libMesh::EigenTimeSolver, libMesh::UnsteadySolver, libMesh::SecondOrderUnsteadySolver, and libMesh::AdaptiveTimeSolver.
Definition at line 48 of file time_solver.C.
References libMesh::TimeSolver::_system, libMesh::TimeSolver::diff_solver(), libMesh::TimeSolver::linear_solver(), libMesh::System::name(), libMesh::on_command_line(), and libMesh::TimeSolver::system().
Referenced by libMesh::UnsteadySolver::reinit().
 {
   libmesh_assert(this->diff_solver().get());
   libmesh_assert_equal_to (&(this->diff_solver()->system()), &(this->system()));
   this->diff_solver()->reinit();
   libmesh_assert(this->linear_solver().get());
   this->linear_solver()->clear();
   if (libMesh::on_command_line("--solver_system_names"))
     this->linear_solver()->init((_system.name()+"_").c_str());
   else
     this->linear_solver()->init();
 }
void libMesh::TimeSolver::retrieve_timestep () virtual inherited
This method retrieves all the stored solutions at the current system.time
Reimplemented in libMesh::UnsteadySolver, and libMesh::SecondOrderUnsteadySolver.
Definition at line 110 of file time_solver.C.
 {
 }
void libMesh::TimeSolver::set_is_adjoint (bool _is_adjoint_value) inline inherited
Accessor for setting whether we need to do a primal or adjoint solve
Definition at line 240 of file time_solver.h.
References libMesh::TimeSolver::_is_adjoint.
Referenced by libMesh::DifferentiableSystem::adjoint_solve(), libMesh::FEMSystem::postprocess(), and libMesh::DifferentiableSystem::solve().
   { _is_adjoint = _is_adjoint_value; }
void libMesh::TimeSolver::set_solution_history (const SolutionHistory & _solution_history) inherited
A setter function users will employ if they need to do something other than save no solution history
Definition at line 97 of file time_solver.C.
References libMesh::SolutionHistory::clone(), and libMesh::TimeSolver::solution_history.
 {
   solution_history = _solution_history.clone();
 }
bool libMesh::SteadySolver::side_residual (bool request_jacobian, DiffContext & context) virtual
This method uses the DifferentiablePhysics' side_time_derivative() and side_constraint() to build a full residual/jacobian on an element's side.
Implements libMesh::TimeSolver.
Definition at line 45 of file steady_solver.C.
References _general_residual(), libMesh::DifferentiablePhysics::side_constraint(), and libMesh::DifferentiablePhysics::side_time_derivative().
Referenced by error_order().
 {
   return this->_general_residual(request_jacobian,
                                  context,
                                  &DifferentiablePhysics::side_time_derivative,
                                  &DifferentiablePhysics::side_constraint);
 }
void libMesh::TimeSolver::solve () virtual inherited
This method solves for the solution at the next timestep (or solves for a steady-state solution). Usually we will only need to solve one (non)linear system per timestep, but more complex subclasses may override this.
Reimplemented in libMesh::NewmarkSolver, libMesh::EigenTimeSolver, libMesh::UnsteadySolver, libMesh::AdaptiveTimeSolver, and libMesh::TwostepTimeSolver.
Definition at line 89 of file time_solver.C.
References libMesh::TimeSolver::diff_solver(), and libMesh::TimeSolver::system().
 {
   libmesh_assert(this->diff_solver().get());
   libmesh_assert_equal_to (&(this->diff_solver()->system()), &(this->system()));
   this->diff_solver()->solve();
 }
const sys_type& libMesh::TimeSolver::system () const inline inherited
Returns
A constant reference to the system we are solving.
Definition at line 172 of file time_solver.h.
References libMesh::TimeSolver::_system.
Referenced by libMesh::TimeSolver::reinit(), and libMesh::TimeSolver::solve().
 { return _system; }
sys_type& libMesh::TimeSolver::system () inline inherited
Returns
A writable reference to the system we are solving.
Definition at line 177 of file time_solver.h.
References libMesh::TimeSolver::_system.
 { return _system; }
Member Data Documentation
ReferenceCounter::Counts libMesh::ReferenceCounter::_counts static protected inherited
Actually holds the data.
Definition at line 124 of file reference_counter.h.
Referenced by libMesh::ReferenceCounter::get_info(), libMesh::ReferenceCounter::increment_constructor_count(), and libMesh::ReferenceCounter::increment_destructor_count().
std::unique_ptr<DiffSolver> libMesh::TimeSolver::_diff_solver protected inherited
An implicit linear or nonlinear solver to use at each timestep.
Definition at line 248 of file time_solver.h.
Referenced by libMesh::NewmarkSolver::compute_initial_accel(), libMesh::TimeSolver::diff_solver(), and libMesh::UnsteadySolver::solve().
bool libMesh::ReferenceCounter::_enable_print_counter = true static protected inherited
Flag to control whether reference count information is printed when print_info is called.
Definition at line 143 of file reference_counter.h.
Referenced by libMesh::ReferenceCounter::disable_print_counter_info(), libMesh::ReferenceCounter::enable_print_counter_info(), and libMesh::ReferenceCounter::print_info().
std::unique_ptr<LinearSolver<Number> > libMesh::TimeSolver::_linear_solver protected inherited
An implicit linear solver to use for adjoint problems.
Definition at line 253 of file time_solver.h.
Referenced by libMesh::TimeSolver::linear_solver().
Threads::spin_mutex libMesh::ReferenceCounter::_mutex static protected inherited
Mutual exclusion object to enable thread-safe reference counting.
Definition at line 137 of file reference_counter.h.
Threads::atomic< unsigned int > libMesh::ReferenceCounter::_n_objects static protected inherited
The number of objects. Print the reference count information when the number returns to 0.
Definition at line 132 of file reference_counter.h.
Referenced by libMesh::ReferenceCounter::n_objects(), libMesh::ReferenceCounter::ReferenceCounter(), and libMesh::ReferenceCounter::~ReferenceCounter().
sys_type& libMesh::TimeSolver::_system protected inherited
A reference to the system we are solving.
Definition at line 258 of file time_solver.h.
Referenced by libMesh::EulerSolver::_general_residual(), libMesh::Euler2Solver::_general_residual(), _general_residual(), libMesh::NewmarkSolver::_general_residual(), libMesh::UnsteadySolver::adjoint_advance_timestep(), libMesh::NewmarkSolver::advance_timestep(), libMesh::AdaptiveTimeSolver::advance_timestep(), libMesh::UnsteadySolver::advance_timestep(), libMesh::NewmarkSolver::compute_initial_accel(), libMesh::FirstOrderUnsteadySolver::compute_second_order_eqns(), libMesh::UnsteadySolver::du(), libMesh::EulerSolver::element_residual(), libMesh::Euler2Solver::element_residual(), libMesh::EigenTimeSolver::element_residual(), libMesh::SecondOrderUnsteadySolver::init(), libMesh::UnsteadySolver::init(), libMesh::TimeSolver::init(), libMesh::EigenTimeSolver::init(), libMesh::SecondOrderUnsteadySolver::init_data(), libMesh::UnsteadySolver::init_data(), libMesh::TimeSolver::init_data(), libMesh::EulerSolver::nonlocal_residual(), libMesh::Euler2Solver::nonlocal_residual(), libMesh::EigenTimeSolver::nonlocal_residual(), libMesh::UnsteadySolver::old_nonlinear_solution(), libMesh::SecondOrderUnsteadySolver::old_solution_accel(), libMesh::SecondOrderUnsteadySolver::old_solution_rate(), libMesh::NewmarkSolver::project_initial_accel(), libMesh::SecondOrderUnsteadySolver::project_initial_rate(), libMesh::SecondOrderUnsteadySolver::reinit(), libMesh::UnsteadySolver::reinit(), libMesh::TimeSolver::reinit(), libMesh::UnsteadySolver::retrieve_timestep(), libMesh::EigenTimeSolver::side_residual(), libMesh::TwostepTimeSolver::solve(), libMesh::UnsteadySolver::solve(), libMesh::EigenTimeSolver::solve(), and libMesh::TimeSolver::system().
bool libMesh::TimeSolver::quiet inherited
Print extra debugging information if quiet == false.
Definition at line 192 of file time_solver.h.
Referenced by libMesh::TwostepTimeSolver::solve(), libMesh::UnsteadySolver::solve(), and libMesh::EigenTimeSolver::solve().
unsigned int libMesh::TimeSolver::reduce_deltat_on_diffsolver_failure inherited
This value (which defaults to zero) is the number of times the TimeSolver is allowed to halve deltat and let the DiffSolver repeat the latest failed solve with a reduced timestep.
Note
This has no effect for SteadySolvers.
You must set at least one of the DiffSolver flags "continue_after_max_iterations" or "continue_after_backtrack_failure" to allow the TimeSolver to retry the solve.
Definition at line 221 of file time_solver.h.
Referenced by libMesh::TwostepTimeSolver::solve(), and libMesh::UnsteadySolver::solve().
std::unique_ptr<SolutionHistory> libMesh::TimeSolver::solution_history protected inherited
A std::unique_ptr to a SolutionHistory object. Default is NoSolutionHistory, which the user can override by declaring a different kind of SolutionHistory in the application
Definition at line 265 of file time_solver.h.
Referenced by libMesh::UnsteadySolver::adjoint_advance_timestep(), libMesh::UnsteadySolver::advance_timestep(), libMesh::UnsteadySolver::retrieve_timestep(), and libMesh::TimeSolver::set_solution_history().
The documentation for this class was generated from the following files:
steady_solver.h
steady_solver.C