libMesh: libMesh::PostscriptIO Class Reference
SomeWebsiteLogo
libMesh::PostscriptIO Class Reference
#include <postscript_io.h>
Public Member Functions
PostscriptIO (const MeshBase &mesh)
virtual ~PostscriptIO ()
virtual void write (const std::string &) override
void plot_quadratic_elem (const Elem *elem)
void plot_linear_elem (const Elem *elem)
virtual void write_equation_systems (const std::string &, const EquationSystems &, const std::set< std::string > *system_names=nullptr)
virtual void write_discontinuous_equation_systems (const std::string &, const EquationSystems &, const std::set< std::string > *system_names=nullptr)
virtual void write_nodal_data (const std::string &, const std::vector< Number > &, const std::vector< std::string > &)
virtual void write_nodal_data (const std::string &, const NumericVector< Number > &, const std::vector< std::string > &)
virtual void write_nodal_data_discontinuous (const std::string &, const std::vector< Number > &, const std::vector< std::string > &)
unsigned int & ascii_precision ()
Public Attributes
Real shade_value
Real line_width
Protected Member Functions
const MeshBase & mesh () const
Protected Attributes
const bool _is_parallel_format
const bool _serial_only_needed_on_proc_0
Private Member Functions
void _compute_edge_bezier_coeffs (const Elem *elem)
Private Attributes
std::vector< Point > _bezier_coeffs
Point _offset
Real _scale
Point _current_point
std::ostringstream _cell_string
std::ofstream _out
Static Private Attributes
static const float _bezier_transform [3][3]
Detailed Description
This class implements writing 2D meshes in Postscript. It borrows several ideas from, and is a more simple-minded version of, the DataOutBase::write_eps() function from Deal II. Only output is supported here, and only the Mesh (none of the data) is written. The main use I imagined for this class is creating nice Mesh images for publications, since I didn't find/don't know of a free visualization program which would do this.
Author
John W. Peterson
Date
2008
Definition at line 53 of file postscript_io.h.
Constructor & Destructor Documentation
PostscriptIO()
libMesh::PostscriptIO::PostscriptIO (const MeshBase & mesh) explicit
Constructor.
Definition at line 42 of file postscript_io.C.
References _bezier_coeffs.
                                                     :
   MeshOutput<MeshBase> (mesh_in),
   shade_value(0.0),
   line_width(0.5),
   //_M(3,3),
   _offset(0., 0.),
   _scale(1.0),
   _current_point(0., 0.)
 {
   // This code is still undergoing some development.
   libmesh_experimental();
   // Entries of transformation matrix from physical to Bezier coords.
   // _M(0,0) = -1./6.;    _M(0,1) = 1./6.;    _M(0,2) = 1.;
   // _M(1,0) = -1./6.;    _M(1,1) = 0.5  ;    _M(1,2) = 1./6.;
   // _M(2,0) = 0.    ;    _M(2,1) = 1.   ;    _M(2,2) = 0.;
   // Make sure there is enough room to store Bezier coefficients.
   _bezier_coeffs.resize(3);
 }
~PostscriptIO()
libMesh::PostscriptIO::~PostscriptIO () virtual
Destructor.
Definition at line 65 of file postscript_io.C.
 {
 }
Member Function Documentation
_compute_edge_bezier_coeffs()
void libMesh::PostscriptIO::_compute_edge_bezier_coeffs (const Elem * elem) private
Given a quadratic edge Elem which lies in the x-y plane, computes the Bezier coefficients. These may be passed to the Postscript routine "curveto".
Definition at line 264 of file postscript_io.C.
References _bezier_coeffs, _bezier_transform, _offset, _scale, libMesh::EDGE3, libMesh::Elem::point(), and libMesh::Elem::type().
Referenced by plot_quadratic_elem().
 {
   // I only know how to do this for an Edge3!
   libmesh_assert_equal_to (elem->type(), EDGE3);
   // Get x-coordinates into an array, transform them,
   // and repeat for y.
   float phys_coords[3] = {0., 0., 0.};
   float bez_coords[3]  = {0., 0., 0.};
   for (unsigned int i=0; i<2; ++i)
     {
       // Initialize vectors.  Physical coordinates are initialized
       // by their postscript-scaled values.
       for (unsigned int j=0; j<3; ++j)
         {
           phys_coords[j] = static_cast<float>
             ((elem->point(j)(i) - _offset(i)) * _scale);
           bez_coords[j] = 0.; // zero out result vector
         }
       // Multiply matrix times vector
       for (unsigned int j=0; j<3; ++j)
         for (unsigned int k=0; k<3; ++k)
           bez_coords[j] += _bezier_transform[j][k]*phys_coords[k];
       // Store result in _bezier_coeffs
       for (unsigned int j=0; j<3; ++j)
         _bezier_coeffs[j](i) = phys_coords[j];
     }
 }
ascii_precision()
unsigned int & libMesh::MeshOutput< MeshBase >::ascii_precision () inline inherited
Return/set the precision to use when writing ASCII files.
By default we use numeric_limits<Real>::digits10 + 2, which should be enough to write out to ASCII and get the exact same Real back when reading in.
Definition at line 244 of file mesh_output.h.
Referenced by libMesh::TecplotIO::write_ascii(), libMesh::GMVIO::write_ascii_new_impl(), and libMesh::GMVIO::write_ascii_old_impl().
 {
   return _ascii_precision;
 }
mesh()
const MeshBase & libMesh::MeshOutput< MeshBase >::mesh () const inline protected inherited
Returns
The object as a read-only reference.
Definition at line 234 of file mesh_output.h.
Referenced by libMesh::FroIO::write(), libMesh::TecplotIO::write(), libMesh::MEDITIO::write(), write(), libMesh::EnsightIO::write(), libMesh::TecplotIO::write_ascii(), libMesh::TecplotIO::write_binary(), libMesh::TecplotIO::write_nodal_data(), libMesh::MEDITIO::write_nodal_data(), and libMesh::GnuPlotIO::write_solution().
 {
   libmesh_assert(_obj);
   return *_obj;
 }
plot_linear_elem()
void libMesh::PostscriptIO::plot_linear_elem (const Elem * elem)
Draws an element with straight lines
Definition at line 190 of file postscript_io.C.
References _cell_string, _current_point, _offset, _out, _scale, libMesh::Elem::n_vertices(), libMesh::Elem::point(), and shade_value.
Referenced by write().
 {
   // Clear the string contents.  Yes, this really is how you do that...
   _cell_string.str("");
   // The general strategy is:
   // 1.) Use m  := {moveto} to go to vertex 0.
   // 2.) Use l  := {lineto} commands to draw lines to vertex 1, 2, ... N-1.
   // 3a.) Use lx := {lineto closepath stroke} command at  vertex N to draw the last line.
   // 3b.)     lf := {lineto closepath fill} command to shade the cell just drawn
   // All of our 2D elements' vertices are numbered in counterclockwise order,
   // so we can just draw them in the same order.
   // 1.)
   _current_point = (elem->point(0) - _offset) * _scale;
   _cell_string << _current_point(0) << " " << _current_point(1) << " "; // write x y
   _cell_string << "m ";
   // 2.)
   const unsigned int nv=elem->n_vertices();
   for (unsigned int v=1; v<nv-1; ++v)
     {
       _current_point = (elem->point(v) - _offset) * _scale;
       _cell_string << _current_point(0) << " " << _current_point(1) << " "; // write x y
       _cell_string << "l ";
     }
   // 3.)
   _current_point = (elem->point(nv-1) - _offset) * _scale;
   _cell_string << _current_point(0) << " " << _current_point(1) << " "; // write x y
   // We draw the shaded (interior) parts first, if applicable.
   if (shade_value > 0.0)
     _out << shade_value << " sg " << _cell_string.str() << "lf\n";
   // Draw the black lines (I guess we will always do this)
   _out << "0 sg " << _cell_string.str() << "lx\n";
 }
plot_quadratic_elem()
void libMesh::PostscriptIO::plot_quadratic_elem (const Elem * elem)
Draws an element with Bezier curves
Definition at line 232 of file postscript_io.C.
References _bezier_coeffs, _compute_edge_bezier_coeffs(), _current_point, _offset, _out, _scale, libMesh::Elem::build_side_ptr(), libMesh::EDGE3, side, and libMesh::Elem::side_index_range().
 {
   for (auto ns : elem->side_index_range())
     {
       // Build the quadratic side
       std::unique_ptr<const Elem> side = elem->build_side_ptr(ns);
       // Be sure it's quadratic (Edge2).  Eventually we could
       // handle cubic elements as well...
       libmesh_assert_equal_to ( side->type(), EDGE3 );
       _out << "0 sg ";
       // Move to the first point on this side.
       _current_point = (side->point(0) - _offset) * _scale;
       _out << _current_point(0) << " " << _current_point(1) << " "; // write x y
       _out << "m ";
       // Compute _bezier_coeffs for this edge.  This fills up
       // the _bezier_coeffs vector.
       this->_compute_edge_bezier_coeffs(side.get());
       // Print curveto path to file
       for (std::size_t i=0; i<_bezier_coeffs.size(); ++i)
         _out << _bezier_coeffs[i](0) << " " << _bezier_coeffs[i](1) << " ";
       _out << " cs\n";
     }
 }
write()
void libMesh::PostscriptIO::write (const std::string & fname) override virtual
This method implements writing a mesh to a specified file.
Implements libMesh::MeshOutput< MeshBase >.
Definition at line 71 of file postscript_io.C.
References libMesh::MeshOutput< MeshBase >::_is_parallel_format, _offset, _out, _scale, libMesh::MeshBase::active_element_ptr_range(), libMesh::MeshTools::create_bounding_box(), line_width, libMesh::MeshOutput< MeshBase >::mesh(), libMesh::MeshOutput< MT >::mesh(), libMesh::MeshBase::mesh_dimension(), plot_linear_elem(), and libMesh::Real.
 {
   // We may need to gather a DistributedMesh to output it, making that
   // const qualifier in our constructor a dirty lie
   MeshSerializer serialize(const_cast<MeshBase &>(this->mesh()), !_is_parallel_format);
   if (this->mesh().processor_id() == 0)
     {
       // Get a constant reference to the mesh.
       const MeshBase & the_mesh = MeshOutput<MeshBase>::mesh();
       // Only works in 2D
       libmesh_assert_equal_to (the_mesh.mesh_dimension(), 2);
       // Create output file stream.
       // _out is now a private member of the class.
       _out.open(fname.c_str());
       // Make sure it opened correctly
       if (!_out.good())
         libmesh_file_error(fname.c_str());
       // The mesh bounding box gives us info about what the
       // Postscript bounding box should be.
       BoundingBox bbox = MeshTools::create_bounding_box(the_mesh);
       // Add a little extra padding to the "true" bounding box so
       // that we can still see the boundary
       const Real percent_padding = 0.01;
       const Real dx=bbox.second(0)-bbox.first(0); libmesh_assert_greater (dx, 0.0);
       const Real dy=bbox.second(1)-bbox.first(1); libmesh_assert_greater (dy, 0.0);
       const Real x_min = bbox.first(0)  - percent_padding*dx;
       const Real y_min = bbox.first(1)  - percent_padding*dy;
       const Real x_max = bbox.second(0) + percent_padding*dx;
       const Real y_max = bbox.second(1) + percent_padding*dy;
       // Width of the output as given in postscript units.
       // This usually is given by the strange unit 1/72 inch.
       // A width of 300 represents a size of roughly 10 cm.
       const Real width = 300;
       _scale = width / (x_max-x_min);
       _offset(0) = x_min;
       _offset(1) = y_min;
       // Header writing stuff stolen from Deal.II
       std::time_t  time1= std::time (0);
       std::tm     * time = std::localtime(&time1);
       _out << "%!PS-Adobe-2.0 EPSF-1.2" << '\n'
         //<< "%!PS-Adobe-1.0" << '\n' // Lars' PS version
            << "%%Filename: " << fname << '\n'
            << "%%Title: LibMesh Output" << '\n'
            << "%%Creator: LibMesh: A C++ finite element library" << '\n'
            << "%%Creation Date: "
            << time->tm_year+1900 << "/"
            << time->tm_mon+1 << "/"
            << time->tm_mday << " - "
            << time->tm_hour << ":"
            << std::setw(2) << time->tm_min << ":"
            << std::setw(2) << time->tm_sec << '\n'
            << "%%BoundingBox: "
         // lower left corner
            << "0 0 "
         // upper right corner
            << static_cast<unsigned int>( rint((x_max-x_min) * _scale ))
            << ' '
            << static_cast<unsigned int>( rint((y_max-y_min) * _scale ))
            << '\n';
       // define some abbreviations to keep
       // the output small:
       // m=move turtle to
       // l=define a line
       // s=set rgb color
       // sg=set gray value
       // lx=close the line and plot the line
       // lf=close the line and fill the interior
       _out << "/m {moveto} bind def"      << '\n'
            << "/l {lineto} bind def"      << '\n'
            << "/s {setrgbcolor} bind def" << '\n'
            << "/sg {setgray} bind def"    << '\n'
            << "/cs {curveto stroke} bind def" << '\n'
            << "/lx {lineto closepath stroke} bind def" << '\n'
            << "/lf {lineto closepath fill} bind def"   << '\n';
       _out << "%%EndProlog" << '\n';
       //  << '\n';
       // Set line width in the postscript file.
       _out << line_width << " setlinewidth" << '\n';
       // Set line cap and join options
       _out << "1 setlinecap" << '\n';
       _out << "1 setlinejoin" << '\n';
       // allow only five digits for output (instead of the default
       // six); this should suffice even for fine grids, but reduces
       // the file size significantly
       _out << std::setprecision (5);
       // Loop over the active elements, draw lines for the edges.  We
       // draw even quadratic elements with straight sides, i.e. a straight
       // line sits between each pair of vertices.  Also we draw every edge
       // for an element regardless of the fact that it may overlap with
       // another.  This would probably be a useful optimization...
       for (const auto & elem : the_mesh.active_element_ptr_range())
         this->plot_linear_elem(elem);
       // Issue the showpage command, and we're done.
       _out << "showpage" << std::endl;
     } // end if (this->mesh().processor_id() == 0)
 }
write_discontinuous_equation_systems()
void libMesh::MeshOutput< MeshBase >::write_discontinuous_equation_systems (const std::string & fname, const EquationSystems & es, const std::set< std::string > * system_names = nullptr) virtual inherited
This method implements writing a mesh with discontinuous data to a specified file where the data is taken from the EquationSystems object.
Definition at line 92 of file mesh_output.C.
References libMesh::EquationSystems::build_discontinuous_solution_vector(), libMesh::EquationSystems::build_variable_names(), libMesh::EquationSystems::get_mesh(), and libMesh::out.
Referenced by libMesh::ExodusII_IO::write_timestep_discontinuous().
 {
   LOG_SCOPE("write_discontinuous_equation_systems()", "MeshOutput");
   // We may need to gather and/or renumber a DistributedMesh to output
   // it, making that const qualifier in our constructor a dirty lie
   MT & my_mesh = const_cast<MT &>(*_obj);
   // If we're asked to write data that's associated with a different
   // mesh, output files full of garbage are the result.
   libmesh_assert_equal_to(&es.get_mesh(), _obj);
   // A non-renumbered mesh may not have a contiguous numbering, and
   // that needs to be fixed before we can build a solution vector.
   if (my_mesh.max_elem_id() != my_mesh.n_elem() ||
       my_mesh.max_node_id() != my_mesh.n_nodes())
     {
       // If we were allowed to renumber then we should have already
       // been properly renumbered...
       libmesh_assert(!my_mesh.allow_renumbering());
       libmesh_do_once(libMesh::out <<
                       "Warning:  This MeshOutput subclass only supports meshes which are contiguously renumbered!"
                       << std::endl;);
       my_mesh.allow_renumbering(true);
       my_mesh.renumber_nodes_and_elements();
       // Not sure what good going back to false will do here, the
       // renumbering horses have already left the barn...
       my_mesh.allow_renumbering(false);
     }
   MeshSerializer serialize(const_cast<MT &>(*_obj), !_is_parallel_format, _serial_only_needed_on_proc_0);
   // Build the list of variable names that will be written.
   std::vector<std::string> names;
   es.build_variable_names  (names, nullptr, system_names);
   if (!_is_parallel_format)
     {
       // Build the nodal solution values & get the variable
       // names from the EquationSystems object
       std::vector<Number> soln;
       es.build_discontinuous_solution_vector (soln, system_names);
       this->write_nodal_data_discontinuous (fname, soln, names);
     }
   else // _is_parallel_format
     {
       libmesh_not_implemented();
     }
 }
write_equation_systems()
void libMesh::MeshOutput< MeshBase >::write_equation_systems (const std::string & fname, const EquationSystems & es, const std::set< std::string > * system_names = nullptr) virtual inherited
This method implements writing a mesh with data to a specified file where the data is taken from the EquationSystems object.
Reimplemented in libMesh::NameBasedIO.
Definition at line 31 of file mesh_output.C.
References libMesh::EquationSystems::build_parallel_solution_vector(), libMesh::EquationSystems::build_solution_vector(), libMesh::EquationSystems::build_variable_names(), libMesh::EquationSystems::get_mesh(), and libMesh::out.
Referenced by libMesh::Nemesis_IO::write_timestep(), and libMesh::ExodusII_IO::write_timestep().
 {
   LOG_SCOPE("write_equation_systems()", "MeshOutput");
   // We may need to gather and/or renumber a DistributedMesh to output
   // it, making that const qualifier in our constructor a dirty lie
   MT & my_mesh = const_cast<MT &>(*_obj);
   // If we're asked to write data that's associated with a different
   // mesh, output files full of garbage are the result.
   libmesh_assert_equal_to(&es.get_mesh(), _obj);
   // A non-renumbered mesh may not have a contiguous numbering, and
   // that needs to be fixed before we can build a solution vector.
   if (my_mesh.max_elem_id() != my_mesh.n_elem() ||
       my_mesh.max_node_id() != my_mesh.n_nodes())
     {
       // If we were allowed to renumber then we should have already
       // been properly renumbered...
       libmesh_assert(!my_mesh.allow_renumbering());
       libmesh_do_once(libMesh::out <<
                       "Warning:  This MeshOutput subclass only supports meshes which are contiguously renumbered!"
                       << std::endl;);
       my_mesh.allow_renumbering(true);
       my_mesh.renumber_nodes_and_elements();
       // Not sure what good going back to false will do here, the
       // renumbering horses have already left the barn...
       my_mesh.allow_renumbering(false);
     }
   MeshSerializer serialize(const_cast<MT &>(*_obj), !_is_parallel_format, _serial_only_needed_on_proc_0);
   // Build the list of variable names that will be written.
   std::vector<std::string> names;
   es.build_variable_names  (names, nullptr, system_names);
   if (!_is_parallel_format)
     {
       // Build the nodal solution values & get the variable
       // names from the EquationSystems object
       std::vector<Number> soln;
       es.build_solution_vector (soln, system_names);
       this->write_nodal_data (fname, soln, names);
     }
   else // _is_parallel_format
     {
       std::unique_ptr<NumericVector<Number>> parallel_soln =
         es.build_parallel_solution_vector(system_names);
       this->write_nodal_data (fname, *parallel_soln, names);
     }
 }
write_nodal_data() [1/2]
virtual void libMesh::MeshOutput< MeshBase >::write_nodal_data (const std::string & , const std::vector< Number > & , const std::vector< std::string > &) inline virtual inherited
This method implements writing a mesh with nodal data to a specified file where the nodal data and variable names are provided.
Reimplemented in libMesh::ExodusII_IO, libMesh::Nemesis_IO, libMesh::UCDIO, libMesh::NameBasedIO, libMesh::GmshIO, libMesh::GMVIO, libMesh::VTKIO, libMesh::MEDITIO, libMesh::GnuPlotIO, and libMesh::TecplotIO.
Definition at line 105 of file mesh_output.h.
   { libmesh_not_implemented(); }
write_nodal_data() [2/2]
void libMesh::MeshOutput< MeshBase >::write_nodal_data (const std::string & fname, const NumericVector< Number > & parallel_soln, const std::vector< std::string > & names) virtual inherited
This method should be overridden by "parallel" output formats for writing nodal data. Instead of getting a localized copy of the nodal solution vector, it is passed a NumericVector of type=PARALLEL which is in node-major order i.e. (u0,v0,w0, u1,v1,w1, u2,v2,w2, u3,v3,w3, ...) and contains n_nodes*n_vars total entries. Then, it is up to the individual I/O class to extract the required solution values from this vector and write them in parallel.
If not implemented, localizes the parallel vector into a std::vector and calls the other version of this function.
Reimplemented in libMesh::Nemesis_IO.
Definition at line 150 of file mesh_output.C.
References libMesh::NumericVector< T >::localize().
 {
   // This is the fallback implementation for parallel I/O formats that
   // do not yet implement proper writing in parallel, and instead rely
   // on the full solution vector being available on all processors.
   std::vector<Number> soln;
   parallel_soln.localize(soln);
   this->write_nodal_data(fname, soln, names);
 }
write_nodal_data_discontinuous()
virtual void libMesh::MeshOutput< MeshBase >::write_nodal_data_discontinuous (const std::string & , const std::vector< Number > & , const std::vector< std::string > &) inline virtual inherited
This method implements writing a mesh with discontinuous data to a specified file where the nodal data and variables names are provided.
Reimplemented in libMesh::ExodusII_IO.
Definition at line 114 of file mesh_output.h.
   { libmesh_not_implemented(); }
Member Data Documentation
_bezier_coeffs
std::vector<Point> libMesh::PostscriptIO::_bezier_coeffs private
Vector containing 3 points corresponding to Bezier coefficients, as computed by _compute_edge_bezier_coeffs.
Definition at line 120 of file postscript_io.h.
Referenced by _compute_edge_bezier_coeffs(), plot_quadratic_elem(), and PostscriptIO().
_bezier_transform
const float libMesh::PostscriptIO::_bezier_transform static private
Initial value:
=
  {
    {-1.f/6.f, 1.f/6.f, 1.},
    {-1.f/6.f, 0.5,     1.f/6.f},
    {0.,       1.,      0.}
  }
Coefficients of the transformation from physical-space edge coordinates to Bezier basis coefficients. Transforms x and y separately.
Definition at line 114 of file postscript_io.h.
Referenced by _compute_edge_bezier_coeffs().
_cell_string
std::ostringstream libMesh::PostscriptIO::_cell_string private
Drawing style-independent data for a single cell. This can be used as a temporary buffer for storing data which may be sent to the output stream multiple times.
Definition at line 142 of file postscript_io.h.
Referenced by plot_linear_elem().
_current_point
Point libMesh::PostscriptIO::_current_point private
A point object used for temporary calculations
Definition at line 135 of file postscript_io.h.
Referenced by plot_linear_elem(), and plot_quadratic_elem().
_is_parallel_format
const bool libMesh::MeshOutput< MeshBase >::_is_parallel_format protected inherited
Flag specifying whether this format is parallel-capable. If this is false (default) I/O is only permitted when the mesh has been serialized.
Definition at line 159 of file mesh_output.h.
Referenced by libMesh::FroIO::write(), write(), and libMesh::EnsightIO::write().
_offset
Point libMesh::PostscriptIO::_offset private
Amount to add to every (x,y) point to place it in Postscript coordinates.
Definition at line 125 of file postscript_io.h.
Referenced by _compute_edge_bezier_coeffs(), plot_linear_elem(), plot_quadratic_elem(), and write().
_out
std::ofstream libMesh::PostscriptIO::_out private
Output file stream which will be opened when the file name is known
Definition at line 147 of file postscript_io.h.
Referenced by plot_linear_elem(), plot_quadratic_elem(), and write().
_scale
Real libMesh::PostscriptIO::_scale private
Amount by which to stretch each point to place it in Postscript coordinates.
Definition at line 130 of file postscript_io.h.
Referenced by _compute_edge_bezier_coeffs(), plot_linear_elem(), plot_quadratic_elem(), and write().
_serial_only_needed_on_proc_0
const bool libMesh::MeshOutput< MeshBase >::_serial_only_needed_on_proc_0 protected inherited
Flag specifying whether this format can be written by only serializing the mesh to processor zero
If this is false (default) the mesh will be serialized to all processors
Definition at line 168 of file mesh_output.h.
line_width
Real libMesh::PostscriptIO::line_width
Control the thickness of the lines used. 0.5 is a reasonable default for printed images, but you may need to decrease this value (or choose it adaptively) when there are very slim cells present in the mesh.
Definition at line 88 of file postscript_io.h.
Referenced by write().
shade_value
Real libMesh::PostscriptIO::shade_value
Controls greyscale shading of cells. By default this value is 0.0 (which actually corresponds to black) and this indicates "no shading" i.e. only mesh lines will be drawn. Any other value in (0,1] will cause the cells to be grey-shaded to some degree, with higher values being lighter. A value of 0.75 gives decent results.
Definition at line 80 of file postscript_io.h.
Referenced by plot_linear_elem().
The documentation for this class was generated from the following files:
postscript_io.h
postscript_io.C