libMesh: libMesh::FroIO Class Reference
SomeWebsiteLogo
libMesh::FroIO Class Reference
#include <fro_io.h>
Public Member Functions
FroIO (const MeshBase &)
virtual void write (const std::string &) override
virtual void write_equation_systems (const std::string &, const EquationSystems &, const std::set< std::string > *system_names=nullptr)
virtual void write_discontinuous_equation_systems (const std::string &, const EquationSystems &, const std::set< std::string > *system_names=nullptr)
virtual void write_nodal_data (const std::string &, const std::vector< Number > &, const std::vector< std::string > &)
virtual void write_nodal_data (const std::string &, const NumericVector< Number > &, const std::vector< std::string > &)
virtual void write_nodal_data_discontinuous (const std::string &, const std::vector< Number > &, const std::vector< std::string > &)
unsigned int & ascii_precision ()
Protected Member Functions
const MeshBase & mesh () const
Protected Attributes
const bool _is_parallel_format
const bool _serial_only_needed_on_proc_0
Detailed Description
This class implements writing meshes in the .fro format used by the MIT ACDL. Valid only for triangular meshes.
Author
Benjamin S. Kirk
Date
2007
Definition at line 42 of file fro_io.h.
Constructor & Destructor Documentation
FroIO()
libMesh::FroIO::FroIO (const MeshBase & mesh_in) inline explicit
Constructor. Takes a reference to a constant mesh object. This constructor will only allow us to write the mesh.
Definition at line 64 of file fro_io.h.
                                       :
   MeshOutput<MeshBase> (mesh_in)
 {
 }
Member Function Documentation
ascii_precision()
unsigned int & libMesh::MeshOutput< MeshBase >::ascii_precision () inline inherited
Return/set the precision to use when writing ASCII files.
By default we use numeric_limits<Real>::digits10 + 2, which should be enough to write out to ASCII and get the exact same Real back when reading in.
Definition at line 244 of file mesh_output.h.
Referenced by libMesh::TecplotIO::write_ascii(), libMesh::GMVIO::write_ascii_new_impl(), and libMesh::GMVIO::write_ascii_old_impl().
 {
   return _ascii_precision;
 }
mesh()
const MeshBase & libMesh::MeshOutput< MeshBase >::mesh () const inline protected inherited
Returns
The object as a read-only reference.
Definition at line 234 of file mesh_output.h.
Referenced by write(), libMesh::TecplotIO::write(), libMesh::MEDITIO::write(), libMesh::PostscriptIO::write(), libMesh::EnsightIO::write(), libMesh::TecplotIO::write_ascii(), libMesh::TecplotIO::write_binary(), libMesh::TecplotIO::write_nodal_data(), libMesh::MEDITIO::write_nodal_data(), and libMesh::GnuPlotIO::write_solution().
 {
   libmesh_assert(_obj);
   return *_obj;
 }
write()
void libMesh::FroIO::write (const std::string & fname) override virtual
This method implements writing a mesh to a specified file.
Implements libMesh::MeshOutput< MeshBase >.
Definition at line 41 of file fro_io.C.
References libMesh::MeshOutput< MeshBase >::_is_parallel_format, libMesh::MeshBase::active_element_ptr_range(), bc_id, libMesh::BoundaryInfo::build_side_list(), libMesh::Elem::build_side_ptr(), libMesh::MeshBase::elem_ref(), libMesh::BoundaryInfo::get_boundary_ids(), libMesh::MeshBase::get_boundary_info(), libMesh::MeshOutput< MeshBase >::mesh(), libMesh::MeshOutput< MT >::mesh(), libMesh::BoundaryInfo::n_boundary_ids(), libMesh::MeshBase::n_elem(), libMesh::MeshBase::n_nodes(), libMesh::MeshBase::point(), side, and libMesh::TRI3.
Referenced by libMesh::NameBasedIO::write().
 {
   // We may need to gather a DistributedMesh to output it, making that
   // const qualifier in our constructor a dirty lie
   MeshSerializer serialize(const_cast<MeshBase &>(this->mesh()), !_is_parallel_format);
   if (this->mesh().processor_id() == 0)
     {
       // Open the output file stream
       std::ofstream out_stream (fname.c_str());
       libmesh_assert (out_stream.good());
       // Make sure it opened correctly
       if (!out_stream.good())
         libmesh_file_error(fname.c_str());
       // Get a reference to the mesh
       const MeshBase & the_mesh = MeshOutput<MeshBase>::mesh();
       // Write the header
       out_stream << the_mesh.n_elem()  << " "
                  << the_mesh.n_nodes() << " "
                  << "0 0 "
                  << the_mesh.get_boundary_info().n_boundary_ids()  << " 1\n";
       // Write the nodes -- 1-based!
       for (unsigned int n=0; n<the_mesh.n_nodes(); n++)
         out_stream << n+1 << " \t"
                    << std::scientific
                    << std::setprecision(12)
                    << the_mesh.point(n)(0) << " \t"
                    << the_mesh.point(n)(1) << " \t"
                    << 0. << '\n';
       // Write the elements -- 1-based!
       unsigned int e = 0;
       for (const auto & elem : the_mesh.active_element_ptr_range())
         {
           // .fro likes TRI3's
           if (elem->type() != TRI3)
             libmesh_error_msg("ERROR:  .fro format only valid for triangles!\n" \
                               << "  writing of " << fname << " aborted.");
           out_stream << ++e << " \t";
           for (unsigned int n=0; n<elem->n_nodes(); n++)
             out_stream << elem->node_id(n)+1 << " \t";
           //   // LHS -> RHS Mapping, for inverted triangles
           //   out_stream << elem->node_id(0)+1 << " \t";
           //   out_stream << elem->node_id(2)+1 << " \t";
           //   out_stream << elem->node_id(1)+1 << " \t";
           out_stream << "1\n";
         }
       // Write BCs.
       {
         const std::set<boundary_id_type> & bc_ids =
           the_mesh.get_boundary_info().get_boundary_ids();
         // Build a list of (elem, side, bc) tuples.
         auto bc_triples = the_mesh.get_boundary_info().build_side_list();
         // Map the boundary ids into [1,n_bc_ids],
         // treat them one at a time.
         boundary_id_type bc_id=0;
         for (const auto & id : bc_ids)
           {
             std::deque<dof_id_type> node_list;
             std::map<dof_id_type, dof_id_type>
               forward_edges, backward_edges;
             // Get all sides on this element with the relevant BC id.
             for (const auto & t : bc_triples)
               if (std::get<2>(t) == id)
                 {
                   // need to build up node_list as a sorted array of edge nodes...
                   // for the following:
                   // a---b---c---d---e
                   // node_list [ a b c d e];
                   //
                   // the issue is just how to get this out of the elem/side based data structure.
                   // the approach is to build up 'chain links' like this:
                   // a---b b---c c---d d---e
                   // and piece them together.
                   //
                   // so, for an arbitrary edge n0---n1, we build the
                   // "forward_edges"  map n0-->n1
                   // "backward_edges" map n1-->n0
                   // and then start with one chain link, and add on...
                   //
                   std::unique_ptr<const Elem> side =
                     the_mesh.elem_ref(std::get<0>(t)).build_side_ptr(std::get<1>(t));
                   const dof_id_type
                     n0 = side->node_id(0),
                     n1 = side->node_id(1);
                   // insert into forward-edge set
                   forward_edges.insert (std::make_pair(n0, n1));
                   // insert into backward-edge set
                   backward_edges.insert (std::make_pair(n1, n0));
                   // go ahead and add one edge to the list -- this will give us the beginning of a
                   // chain to work from!
                   if (node_list.empty())
                     {
                       node_list.push_front(n0);
                       node_list.push_back (n1);
                     }
                 }
             // we now have the node_list with one edge, the forward_edges, and the backward_edges
             // the node_list will be filled when (node_list.size() == (n_edges+1))
             // until that is the case simply add on to the beginning and end of the node_list,
             // building up a chain of ordered nodes...
             const std::size_t n_edges = forward_edges.size();
             while (node_list.size() != (n_edges+1))
               {
                 const dof_id_type
                   front_node = node_list.front(),
                   back_node  = node_list.back();
                 // look for front_pair in the backward_edges list
                 {
                   auto pos = backward_edges.find(front_node);
                   if (pos != backward_edges.end())
                     {
                       node_list.push_front(pos->second);
                       backward_edges.erase(pos);
                     }
                 }
                 // look for back_pair in the forward_edges list
                 {
                   auto pos = forward_edges.find(back_node);
                   if (pos != forward_edges.end())
                     {
                       node_list.push_back(pos->second);
                       forward_edges.erase(pos);
                     }
                 }
               }
             out_stream << ++bc_id << " " << node_list.size() << '\n';
             for (const auto & node_id : node_list)
               out_stream << node_id + 1 << " \t0\n";
           }
       }
     }
 }
write_discontinuous_equation_systems()
void libMesh::MeshOutput< MeshBase >::write_discontinuous_equation_systems (const std::string & fname, const EquationSystems & es, const std::set< std::string > * system_names = nullptr) virtual inherited
This method implements writing a mesh with discontinuous data to a specified file where the data is taken from the EquationSystems object.
Definition at line 92 of file mesh_output.C.
References libMesh::EquationSystems::build_discontinuous_solution_vector(), libMesh::EquationSystems::build_variable_names(), libMesh::EquationSystems::get_mesh(), and libMesh::out.
Referenced by libMesh::ExodusII_IO::write_timestep_discontinuous().
 {
   LOG_SCOPE("write_discontinuous_equation_systems()", "MeshOutput");
   // We may need to gather and/or renumber a DistributedMesh to output
   // it, making that const qualifier in our constructor a dirty lie
   MT & my_mesh = const_cast<MT &>(*_obj);
   // If we're asked to write data that's associated with a different
   // mesh, output files full of garbage are the result.
   libmesh_assert_equal_to(&es.get_mesh(), _obj);
   // A non-renumbered mesh may not have a contiguous numbering, and
   // that needs to be fixed before we can build a solution vector.
   if (my_mesh.max_elem_id() != my_mesh.n_elem() ||
       my_mesh.max_node_id() != my_mesh.n_nodes())
     {
       // If we were allowed to renumber then we should have already
       // been properly renumbered...
       libmesh_assert(!my_mesh.allow_renumbering());
       libmesh_do_once(libMesh::out <<
                       "Warning:  This MeshOutput subclass only supports meshes which are contiguously renumbered!"
                       << std::endl;);
       my_mesh.allow_renumbering(true);
       my_mesh.renumber_nodes_and_elements();
       // Not sure what good going back to false will do here, the
       // renumbering horses have already left the barn...
       my_mesh.allow_renumbering(false);
     }
   MeshSerializer serialize(const_cast<MT &>(*_obj), !_is_parallel_format, _serial_only_needed_on_proc_0);
   // Build the list of variable names that will be written.
   std::vector<std::string> names;
   es.build_variable_names  (names, nullptr, system_names);
   if (!_is_parallel_format)
     {
       // Build the nodal solution values & get the variable
       // names from the EquationSystems object
       std::vector<Number> soln;
       es.build_discontinuous_solution_vector (soln, system_names);
       this->write_nodal_data_discontinuous (fname, soln, names);
     }
   else // _is_parallel_format
     {
       libmesh_not_implemented();
     }
 }
write_equation_systems()
void libMesh::MeshOutput< MeshBase >::write_equation_systems (const std::string & fname, const EquationSystems & es, const std::set< std::string > * system_names = nullptr) virtual inherited
This method implements writing a mesh with data to a specified file where the data is taken from the EquationSystems object.
Reimplemented in libMesh::NameBasedIO.
Definition at line 31 of file mesh_output.C.
References libMesh::EquationSystems::build_parallel_solution_vector(), libMesh::EquationSystems::build_solution_vector(), libMesh::EquationSystems::build_variable_names(), libMesh::EquationSystems::get_mesh(), and libMesh::out.
Referenced by libMesh::Nemesis_IO::write_timestep(), and libMesh::ExodusII_IO::write_timestep().
 {
   LOG_SCOPE("write_equation_systems()", "MeshOutput");
   // We may need to gather and/or renumber a DistributedMesh to output
   // it, making that const qualifier in our constructor a dirty lie
   MT & my_mesh = const_cast<MT &>(*_obj);
   // If we're asked to write data that's associated with a different
   // mesh, output files full of garbage are the result.
   libmesh_assert_equal_to(&es.get_mesh(), _obj);
   // A non-renumbered mesh may not have a contiguous numbering, and
   // that needs to be fixed before we can build a solution vector.
   if (my_mesh.max_elem_id() != my_mesh.n_elem() ||
       my_mesh.max_node_id() != my_mesh.n_nodes())
     {
       // If we were allowed to renumber then we should have already
       // been properly renumbered...
       libmesh_assert(!my_mesh.allow_renumbering());
       libmesh_do_once(libMesh::out <<
                       "Warning:  This MeshOutput subclass only supports meshes which are contiguously renumbered!"
                       << std::endl;);
       my_mesh.allow_renumbering(true);
       my_mesh.renumber_nodes_and_elements();
       // Not sure what good going back to false will do here, the
       // renumbering horses have already left the barn...
       my_mesh.allow_renumbering(false);
     }
   MeshSerializer serialize(const_cast<MT &>(*_obj), !_is_parallel_format, _serial_only_needed_on_proc_0);
   // Build the list of variable names that will be written.
   std::vector<std::string> names;
   es.build_variable_names  (names, nullptr, system_names);
   if (!_is_parallel_format)
     {
       // Build the nodal solution values & get the variable
       // names from the EquationSystems object
       std::vector<Number> soln;
       es.build_solution_vector (soln, system_names);
       this->write_nodal_data (fname, soln, names);
     }
   else // _is_parallel_format
     {
       std::unique_ptr<NumericVector<Number>> parallel_soln =
         es.build_parallel_solution_vector(system_names);
       this->write_nodal_data (fname, *parallel_soln, names);
     }
 }
write_nodal_data() [1/2]
virtual void libMesh::MeshOutput< MeshBase >::write_nodal_data (const std::string & , const std::vector< Number > & , const std::vector< std::string > &) inline virtual inherited
This method implements writing a mesh with nodal data to a specified file where the nodal data and variable names are provided.
Reimplemented in libMesh::ExodusII_IO, libMesh::Nemesis_IO, libMesh::UCDIO, libMesh::NameBasedIO, libMesh::GmshIO, libMesh::GMVIO, libMesh::VTKIO, libMesh::MEDITIO, libMesh::GnuPlotIO, and libMesh::TecplotIO.
Definition at line 105 of file mesh_output.h.
   { libmesh_not_implemented(); }
write_nodal_data() [2/2]
void libMesh::MeshOutput< MeshBase >::write_nodal_data (const std::string & fname, const NumericVector< Number > & parallel_soln, const std::vector< std::string > & names) virtual inherited
This method should be overridden by "parallel" output formats for writing nodal data. Instead of getting a localized copy of the nodal solution vector, it is passed a NumericVector of type=PARALLEL which is in node-major order i.e. (u0,v0,w0, u1,v1,w1, u2,v2,w2, u3,v3,w3, ...) and contains n_nodes*n_vars total entries. Then, it is up to the individual I/O class to extract the required solution values from this vector and write them in parallel.
If not implemented, localizes the parallel vector into a std::vector and calls the other version of this function.
Reimplemented in libMesh::Nemesis_IO.
Definition at line 150 of file mesh_output.C.
References libMesh::NumericVector< T >::localize().
 {
   // This is the fallback implementation for parallel I/O formats that
   // do not yet implement proper writing in parallel, and instead rely
   // on the full solution vector being available on all processors.
   std::vector<Number> soln;
   parallel_soln.localize(soln);
   this->write_nodal_data(fname, soln, names);
 }
write_nodal_data_discontinuous()
virtual void libMesh::MeshOutput< MeshBase >::write_nodal_data_discontinuous (const std::string & , const std::vector< Number > & , const std::vector< std::string > &) inline virtual inherited
This method implements writing a mesh with discontinuous data to a specified file where the nodal data and variables names are provided.
Reimplemented in libMesh::ExodusII_IO.
Definition at line 114 of file mesh_output.h.
   { libmesh_not_implemented(); }
Member Data Documentation
_is_parallel_format
const bool libMesh::MeshOutput< MeshBase >::_is_parallel_format protected inherited
Flag specifying whether this format is parallel-capable. If this is false (default) I/O is only permitted when the mesh has been serialized.
Definition at line 159 of file mesh_output.h.
Referenced by write(), libMesh::PostscriptIO::write(), and libMesh::EnsightIO::write().
_serial_only_needed_on_proc_0
const bool libMesh::MeshOutput< MeshBase >::_serial_only_needed_on_proc_0 protected inherited
Flag specifying whether this format can be written by only serializing the mesh to processor zero
If this is false (default) the mesh will be serialized to all processors
Definition at line 168 of file mesh_output.h.
The documentation for this class was generated from the following files:
fro_io.h
fro_io.C