libMesh: libMesh::Parallel::MessageTag Class Reference
SomeWebsiteLogo
libMesh::Parallel::MessageTag Class Reference
#include <message_tag.h>
Public Member Functions
MessageTag (int tagvalue=invalid_tag)
MessageTag (const MessageTag &other)
MessageTag (MessageTag &&other)
MessageTag & operator= (const MessageTag &other)
MessageTag & operator= (MessageTag &&other)
~MessageTag ()
int value () const
Static Public Attributes
static const int invalid_tag = INT_MIN
Private Member Functions
MessageTag (int tagvalue, const Communicator *comm)
Private Attributes
int _tagvalue
const Communicator * _comm
Friends
class Communicator
Detailed Description
Encapsulates the MPI tag integers.
Definition at line 47 of file message_tag.h.
Constructor & Destructor Documentation
MessageTag() [1/4]
libMesh::Parallel::MessageTag::MessageTag (int tagvalue = invalid_tag) inline explicit
Explicit constructor, to discourage using "magic numbers" as tags. Communicator::get_unique_tag is recommended instead.
Definition at line 60 of file message_tag.h.
     : _tagvalue(tagvalue), _comm(nullptr) {}
MessageTag() [2/4]
libMesh::Parallel::MessageTag::MessageTag (const MessageTag & other)
Copy constructor. Helps Communicator do reference counting on unique tags
Definition at line 41 of file message_tag.C.
References _comm, _tagvalue, and libMesh::Parallel::Communicator::reference_unique_tag().
   : _tagvalue(other._tagvalue), _comm(other._comm)
 {
   if (_comm)
     _comm->reference_unique_tag(_tagvalue);
 }
MessageTag() [3/4]
libMesh::Parallel::MessageTag::MessageTag (MessageTag && other)
Move constructor. Helps Communicator do reference counting on unique tags
Definition at line 49 of file message_tag.C.
   : _tagvalue(other._tagvalue), _comm(other._comm)
 {
   // I stole your tag reference!
   other._comm = nullptr;
 }
~MessageTag()
libMesh::Parallel::MessageTag::~MessageTag ()
Destructor. Helps Communicator do reference counting on unique tags
Definition at line 34 of file message_tag.C.
References _comm, _tagvalue, and libMesh::Parallel::Communicator::dereference_unique_tag().
 {
   if (_comm)
     _comm->dereference_unique_tag(_tagvalue);
 }
MessageTag() [4/4]
libMesh::Parallel::MessageTag::MessageTag (int tagvalue, const Communicator * comm) inline private
Definition at line 102 of file message_tag.h.
     : _tagvalue(tagvalue), _comm(comm) {}
Member Function Documentation
operator=() [1/2]
MessageTag & libMesh::Parallel::MessageTag::operator= (const MessageTag & other)
Copy assignment operator. Helps Communicator do reference counting on unique tags
Definition at line 57 of file message_tag.C.
References _comm, _tagvalue, libMesh::Parallel::Communicator::dereference_unique_tag(), and libMesh::Parallel::Communicator::reference_unique_tag().
 {
   if (_comm)
     _comm->dereference_unique_tag(_tagvalue);
   _tagvalue = other._tagvalue;
   _comm = other._comm;
   if (_comm)
     _comm->reference_unique_tag(_tagvalue);
   return *this;
 }
operator=() [2/2]
MessageTag & libMesh::Parallel::MessageTag::operator= (MessageTag && other)
Move assignment operator. Helps Communicator do reference counting on unique tags
Definition at line 72 of file message_tag.C.
References _comm, _tagvalue, and libMesh::Parallel::Communicator::dereference_unique_tag().
 {
   if (_comm)
     _comm->dereference_unique_tag(_tagvalue);
   _tagvalue = other._tagvalue;
   _comm = other._comm;
   // I stole your tag reference!
   other._comm = nullptr;
   return *this;
 }
value()
int libMesh::Parallel::MessageTag::value () const inline
Definition at line 93 of file message_tag.h.
References _tagvalue.
Referenced by libMesh::Parallel::Communicator::packed_range_probe(), libMesh::Parallel::Communicator::probe(), libMesh::Parallel::Communicator::receive(), libMesh::Parallel::Communicator::send(), and libMesh::Parallel::Communicator::send_receive().
                     {
     return _tagvalue;
   }
Friends And Related Function Documentation
Communicator
friend class Communicator friend
Definition at line 106 of file message_tag.h.
Member Data Documentation
_comm
const Communicator* libMesh::Parallel::MessageTag::_comm private
Definition at line 99 of file message_tag.h.
Referenced by MessageTag(), operator=(), and ~MessageTag().
_tagvalue
int libMesh::Parallel::MessageTag::_tagvalue private
Definition at line 98 of file message_tag.h.
Referenced by MessageTag(), operator=(), value(), and ~MessageTag().
invalid_tag
const int libMesh::Parallel::MessageTag::invalid_tag = INT_MIN static
Invalid tag, to allow for default construction.
Definition at line 54 of file message_tag.h.
The documentation for this class was generated from the following files:
message_tag.h
message_tag.C