libMesh: libMesh::TransientRBThetaExpansion Class Reference
SomeWebsiteLogo
libMesh::TransientRBThetaExpansion Class Reference
#include <transient_rb_theta_expansion.h>
Public Types
typedef RBThetaExpansion Parent
Public Member Functions
TransientRBThetaExpansion ()
virtual Number eval_M_theta (unsigned int q, const RBParameters &mu)
virtual unsigned int get_n_M_terms ()
virtual void attach_M_theta (RBTheta *theta_q_m)
Number eval_A_theta (unsigned int q, const RBParameters &mu)
Number eval_F_theta (unsigned int q, const RBParameters &mu)
Number eval_output_theta (unsigned int output_index, unsigned int q_l, const RBParameters &mu)
unsigned int get_n_A_terms () const
unsigned int get_n_F_terms () const
unsigned int get_n_outputs () const
unsigned int get_n_output_terms (unsigned int output_index) const
virtual void attach_A_theta (RBTheta *theta_q_a)
virtual void attach_multiple_A_theta (std::vector< RBTheta * > theta_q_a)
virtual void attach_F_theta (RBTheta *theta_q_f)
virtual void attach_multiple_F_theta (std::vector< RBTheta * > theta_q_f)
virtual void attach_output_theta (std::vector< RBTheta * > theta_q_l)
virtual void attach_output_theta (RBTheta *theta_q_l)
Static Public Member Functions
static std::string get_info ()
static void print_info (std::ostream &out=libMesh::out)
static unsigned int n_objects ()
static void enable_print_counter_info ()
static void disable_print_counter_info ()
Protected Types
typedef std::map< std::string,
std::pair< unsigned int,
unsigned int > > Counts
Protected Member Functions
void increment_constructor_count (const std::string &name)
void increment_destructor_count (const std::string &name)
Static Protected Attributes
static Counts _counts
static Threads::atomic
< unsigned int > _n_objects
static Threads::spin_mutex _mutex
static bool _enable_print_counter = true
Private Attributes
std::vector< RBTheta * > _M_theta_vector
Detailed Description
This class stores the set of RBTheta functor objects that define the "parameter-dependent expansion" of a PDE.
Author
David J. Knezevic, 2011
Definition at line 43 of file transient_rb_theta_expansion.h.
Member Typedef Documentation
typedef std::map<std::string, std::pair<unsigned int, unsigned int> > libMesh::ReferenceCounter::Counts protected inherited
Data structure to log the information. The log is identified by the class name.
Definition at line 113 of file reference_counter.h.
typedef RBThetaExpansion libMesh::TransientRBThetaExpansion::Parent
The type of the parent.
Definition at line 55 of file transient_rb_theta_expansion.h.
Constructor & Destructor Documentation
libMesh::TransientRBThetaExpansion::TransientRBThetaExpansion ()
Constructor.
Member Function Documentation
virtual void libMesh::RBThetaExpansion::attach_A_theta (RBTheta * theta_q_a) virtual inherited
Attach a pointer to a functor object that defines one of the theta_q_a terms.
virtual void libMesh::RBThetaExpansion::attach_F_theta (RBTheta * theta_q_f) virtual inherited
Attach a pointer to a functor object that defines one of the theta_q_a terms.
virtual void libMesh::TransientRBThetaExpansion::attach_M_theta (RBTheta * theta_q_m) virtual
Attach a pointer to a functor object that defines one of the theta_q_m terms.
virtual void libMesh::RBThetaExpansion::attach_multiple_A_theta (std::vector< RBTheta * > theta_q_a) virtual inherited
Attach a vector of pointers to functor objects that each define one of the theta_q_a terms.
virtual void libMesh::RBThetaExpansion::attach_multiple_F_theta (std::vector< RBTheta * > theta_q_f) virtual inherited
Attach a vector of pointers to functor objects that each define one of the theta_q_f terms.
virtual void libMesh::RBThetaExpansion::attach_output_theta (std::vector< RBTheta * > theta_q_l) virtual inherited
Attach a vector of pointers to functor objects that define one of the outputs.
virtual void libMesh::RBThetaExpansion::attach_output_theta (RBTheta * theta_q_l) virtual inherited
Attach a pointer to a functor object that defines one of the outputs.
void libMesh::ReferenceCounter::disable_print_counter_info () static inherited
Definition at line 106 of file reference_counter.C.
References libMesh::ReferenceCounter::_enable_print_counter.
 {
   _enable_print_counter = false;
   return;
 }
void libMesh::ReferenceCounter::enable_print_counter_info () static inherited
Methods to enable/disable the reference counter output from print_info()
Definition at line 100 of file reference_counter.C.
References libMesh::ReferenceCounter::_enable_print_counter.
 {
   _enable_print_counter = true;
   return;
 }
Number libMesh::RBThetaExpansion::eval_A_theta (unsigned int q, const RBParameters & mu) inherited
Evaluate theta_q_a at the current parameter. Overload if the theta functions need to be treated differently in subclasses.
Number libMesh::RBThetaExpansion::eval_F_theta (unsigned int q, const RBParameters & mu) inherited
Evaluate theta_q_f at the current parameter.
virtual Number libMesh::TransientRBThetaExpansion::eval_M_theta (unsigned int q, const RBParameters & mu) virtual
Evaluate theta at the current parameter. Overload if the theta functions need to be treated differently in subclasses.
Number libMesh::RBThetaExpansion::eval_output_theta (unsigned int output_index, unsigned int q_l, const RBParameters & mu) inherited
Evaluate theta_q_l at the current parameter.
std::string libMesh::ReferenceCounter::get_info () static inherited
Gets a string containing the reference information.
Definition at line 47 of file reference_counter.C.
References libMesh::ReferenceCounter::_counts, and libMesh::Quality::name().
Referenced by libMesh::ReferenceCounter::print_info().
 {
 #if defined(LIBMESH_ENABLE_REFERENCE_COUNTING) && defined(DEBUG)
   std::ostringstream oss;
   oss << '\n'
       << " ---------------------------------------------------------------------------- \n"
       << "| Reference count information                                                |\n"
       << " ---------------------------------------------------------------------------- \n";
   for (Counts::iterator it = _counts.begin();
        it != _counts.end(); ++it)
     {
       const std::string name(it->first);
       const unsigned int creations    = it->second.first;
       const unsigned int destructions = it->second.second;
       oss << "| " << name << " reference count information:\n"
           << "|  Creations:    " << creations    << '\n'
           << "|  Destructions: " << destructions << '\n';
     }
   oss << " ---------------------------------------------------------------------------- \n";
   return oss.str();
 #else
   return "";
 #endif
 }
unsigned int libMesh::RBThetaExpansion::get_n_A_terms () const inherited
Get Q_a, the number of terms in the affine expansion for the bilinear form.
unsigned int libMesh::RBThetaExpansion::get_n_F_terms () const inherited
Get Q_f, the number of terms in the affine expansion for the right-hand side.
virtual unsigned int libMesh::TransientRBThetaExpansion::get_n_M_terms () inline virtual
Get Q_m, the number of terms in the affine expansion for the mass operator.
Definition at line 69 of file transient_rb_theta_expansion.h.
References _M_theta_vector.
   { return cast_int<unsigned int>(_M_theta_vector.size()); }
unsigned int libMesh::RBThetaExpansion::get_n_output_terms (unsigned int output_index) const inherited
Get the number of affine terms associated with the specified output.
unsigned int libMesh::RBThetaExpansion::get_n_outputs () const inherited
Get n_outputs, the number output functionals.
void libMesh::ReferenceCounter::increment_constructor_count (const std::string & name) inline protected inherited
Increments the construction counter. Should be called in the constructor of any derived class that will be reference counted.
Definition at line 163 of file reference_counter.h.
References libMesh::ReferenceCounter::_counts, libMesh::Quality::name(), and libMesh::Threads::spin_mtx.
Referenced by libMesh::ReferenceCountedObject< RBParametrized >::ReferenceCountedObject().
 {
   Threads::spin_mutex::scoped_lock lock(Threads::spin_mtx);
   std::pair<unsigned int, unsigned int>& p = _counts[name];
   p.first++;
 }
void libMesh::ReferenceCounter::increment_destructor_count (const std::string & name) inline protected inherited
Increments the destruction counter. Should be called in the destructor of any derived class that will be reference counted.
Definition at line 176 of file reference_counter.h.
References libMesh::ReferenceCounter::_counts, libMesh::Quality::name(), and libMesh::Threads::spin_mtx.
Referenced by libMesh::ReferenceCountedObject< RBParametrized >::~ReferenceCountedObject().
 {
   Threads::spin_mutex::scoped_lock lock(Threads::spin_mtx);
   std::pair<unsigned int, unsigned int>& p = _counts[name];
   p.second++;
 }
static unsigned int libMesh::ReferenceCounter::n_objects () inline static inherited
Prints the number of outstanding (created, but not yet destroyed) objects.
Definition at line 79 of file reference_counter.h.
References libMesh::ReferenceCounter::_n_objects.
   { return _n_objects; }
void libMesh::ReferenceCounter::print_info (std::ostream & out = libMesh::out) static inherited
Prints the reference information, by default to libMesh::out.
Definition at line 88 of file reference_counter.C.
References libMesh::ReferenceCounter::_enable_print_counter, and libMesh::ReferenceCounter::get_info().
 {
   if( _enable_print_counter ) out_stream << ReferenceCounter::get_info();
 }
Member Data Documentation
ReferenceCounter::Counts libMesh::ReferenceCounter::_counts static protected inherited
Actually holds the data.
Definition at line 118 of file reference_counter.h.
Referenced by libMesh::ReferenceCounter::get_info(), libMesh::ReferenceCounter::increment_constructor_count(), and libMesh::ReferenceCounter::increment_destructor_count().
bool libMesh::ReferenceCounter::_enable_print_counter = true static protected inherited
Flag to control whether reference count information is printed when print_info is called.
Definition at line 137 of file reference_counter.h.
Referenced by libMesh::ReferenceCounter::disable_print_counter_info(), libMesh::ReferenceCounter::enable_print_counter_info(), and libMesh::ReferenceCounter::print_info().
std::vector<RBTheta*> libMesh::TransientRBThetaExpansion::_M_theta_vector private
Vector storing the pointers to the RBTheta functors.
Definition at line 83 of file transient_rb_theta_expansion.h.
Referenced by get_n_M_terms().
Threads::spin_mutex libMesh::ReferenceCounter::_mutex static protected inherited
Mutual exclusion object to enable thread-safe reference counting.
Definition at line 131 of file reference_counter.h.
Threads::atomic< unsigned int > libMesh::ReferenceCounter::_n_objects static protected inherited
The number of objects. Print the reference count information when the number returns to 0.
Definition at line 126 of file reference_counter.h.
Referenced by libMesh::ReferenceCounter::n_objects(), libMesh::ReferenceCounter::ReferenceCounter(), and libMesh::ReferenceCounter::~ReferenceCounter().
The documentation for this class was generated from the following file:
transient_rb_theta_expansion.h