libMesh: libMesh::EigenSystem Class Reference
SomeWebsiteLogo
libMesh::EigenSystem Class Reference
Manages consistently variables, degrees of freedom, and coefficient vectors for eigenvalue problems.
#include <eigen_system.h>
Public Types
typedef EigenSystem sys_type
typedef System Parent
typedef Number(* ValueFunctionPointer) (const Point &p, const Parameters &Parameters, const std::string &sys_name, const std::string &unknown_name)
typedef Gradient(* GradientFunctionPointer) (const Point &p, const Parameters &parameters, const std::string &sys_name, const std::string &unknown_name)
typedef std::map< std::string, NumericVector< Number > * >::iterator vectors_iterator
typedef std::map< std::string, NumericVector< Number > * >::const_iterator const_vectors_iterator
Public Member Functions
EigenSystem (EquationSystems &es, const std::string &name_in, const unsigned int number_in)
virtual ~EigenSystem ()
sys_type & system ()
virtual void clear () override
virtual void reinit () override
virtual void solve () override
virtual void assemble () override
virtual std::pair< Real, Real > get_eigenpair (dof_id_type i)
virtual std::string system_type () const override
virtual unsigned int n_matrices () const override
unsigned int get_n_converged () const
unsigned int get_n_iterations () const
void set_eigenproblem_type (EigenProblemType ept)
EigenProblemType get_eigenproblem_type () const
bool generalized () const
void init ()
virtual void reinit_constraints ()
bool is_initialized ()
virtual void update ()
virtual void assemble_qoi (const QoISet &qoi_indices=QoISet())
virtual void assemble_qoi_derivative (const QoISet &qoi_indices=QoISet(), bool include_liftfunc=true, bool apply_constraints=true)
virtual void assemble_residual_derivatives (const ParameterVector &parameters)
virtual void restrict_solve_to (const SystemSubset *subset, const SubsetSolveMode subset_solve_mode=SUBSET_ZERO)
virtual std::pair< unsigned int, Real > sensitivity_solve (const ParameterVector &parameters)
virtual std::pair< unsigned int, Real > weighted_sensitivity_solve (const ParameterVector &parameters, const ParameterVector &weights)
virtual std::pair< unsigned int, Real > adjoint_solve (const QoISet &qoi_indices=QoISet())
virtual std::pair< unsigned int, Real > weighted_sensitivity_adjoint_solve (const ParameterVector &parameters, const ParameterVector &weights, const QoISet &qoi_indices=QoISet())
bool is_adjoint_already_solved () const
void set_adjoint_already_solved (bool setting)
virtual void qoi_parameter_sensitivity (const QoISet &qoi_indices, const ParameterVector &parameters, SensitivityData &sensitivities)
virtual void adjoint_qoi_parameter_sensitivity (const QoISet &qoi_indices, const ParameterVector &parameters, SensitivityData &sensitivities)
virtual void forward_qoi_parameter_sensitivity (const QoISet &qoi_indices, const ParameterVector &parameters, SensitivityData &sensitivities)
virtual void qoi_parameter_hessian (const QoISet &qoi_indices, const ParameterVector &parameters, SensitivityData &hessian)
virtual void qoi_parameter_hessian_vector_product (const QoISet &qoi_indices, const ParameterVector &parameters, const ParameterVector &vector, SensitivityData &product)
virtual bool compare (const System &other_system, const Real threshold, const bool verbose) const
const std::string & name () const
void project_solution (FunctionBase< Number > *f, FunctionBase< Gradient > *g=nullptr) const
void project_solution (FEMFunctionBase< Number > *f, FEMFunctionBase< Gradient > *g=nullptr) const
void project_solution (ValueFunctionPointer fptr, GradientFunctionPointer gptr, const Parameters &parameters) const
void project_vector (NumericVector< Number > &new_vector, FunctionBase< Number > *f, FunctionBase< Gradient > *g=nullptr, int is_adjoint=-1) const
void project_vector (NumericVector< Number > &new_vector, FEMFunctionBase< Number > *f, FEMFunctionBase< Gradient > *g=nullptr, int is_adjoint=-1) const
void project_vector (ValueFunctionPointer fptr, GradientFunctionPointer gptr, const Parameters &parameters, NumericVector< Number > &new_vector, int is_adjoint=-1) const
void boundary_project_solution (const std::set< boundary_id_type > &b, const std::vector< unsigned int > &variables, FunctionBase< Number > *f, FunctionBase< Gradient > *g=nullptr)
void boundary_project_solution (const std::set< boundary_id_type > &b, const std::vector< unsigned int > &variables, ValueFunctionPointer fptr, GradientFunctionPointer gptr, const Parameters &parameters)
void boundary_project_vector (const std::set< boundary_id_type > &b, const std::vector< unsigned int > &variables, NumericVector< Number > &new_vector, FunctionBase< Number > *f, FunctionBase< Gradient > *g=nullptr, int is_adjoint=-1) const
void boundary_project_vector (const std::set< boundary_id_type > &b, const std::vector< unsigned int > &variables, ValueFunctionPointer fptr, GradientFunctionPointer gptr, const Parameters &parameters, NumericVector< Number > &new_vector, int is_adjoint=-1) const
unsigned int number () const
void update_global_solution (std::vector< Number > &global_soln) const
void update_global_solution (std::vector< Number > &global_soln, const processor_id_type dest_proc) const
const MeshBase & get_mesh () const
MeshBase & get_mesh ()
const DofMap & get_dof_map () const
DofMap & get_dof_map ()
const EquationSystems & get_equation_systems () const
EquationSystems & get_equation_systems ()
bool active () const
void activate ()
void deactivate ()
void set_basic_system_only ()
vectors_iterator vectors_begin ()
const_vectors_iterator vectors_begin () const
vectors_iterator vectors_end ()
const_vectors_iterator vectors_end () const
NumericVector< Number > & add_vector (const std::string &vec_name, const bool projections=true, const ParallelType type=PARALLEL)
void remove_vector (const std::string &vec_name)
bool & project_solution_on_reinit (void)
bool have_vector (const std::string &vec_name) const
const NumericVector< Number > * request_vector (const std::string &vec_name) const
NumericVector< Number > * request_vector (const std::string &vec_name)
const NumericVector< Number > * request_vector (const unsigned int vec_num) const
NumericVector< Number > * request_vector (const unsigned int vec_num)
const NumericVector< Number > & get_vector (const std::string &vec_name) const
NumericVector< Number > & get_vector (const std::string &vec_name)
const NumericVector< Number > & get_vector (const unsigned int vec_num) const
NumericVector< Number > & get_vector (const unsigned int vec_num)
const std::string & vector_name (const unsigned int vec_num) const
const std::string & vector_name (const NumericVector< Number > &vec_reference) const
void set_vector_as_adjoint (const std::string &vec_name, int qoi_num)
int vector_is_adjoint (const std::string &vec_name) const
void set_vector_preservation (const std::string &vec_name, bool preserve)
bool vector_preservation (const std::string &vec_name) const
NumericVector< Number > & add_adjoint_solution (unsigned int i=0)
NumericVector< Number > & get_adjoint_solution (unsigned int i=0)
const NumericVector< Number > & get_adjoint_solution (unsigned int i=0) const
NumericVector< Number > & add_sensitivity_solution (unsigned int i=0)
NumericVector< Number > & get_sensitivity_solution (unsigned int i=0)
const NumericVector< Number > & get_sensitivity_solution (unsigned int i=0) const
NumericVector< Number > & add_weighted_sensitivity_adjoint_solution (unsigned int i=0)
NumericVector< Number > & get_weighted_sensitivity_adjoint_solution (unsigned int i=0)
const NumericVector< Number > & get_weighted_sensitivity_adjoint_solution (unsigned int i=0) const
NumericVector< Number > & add_weighted_sensitivity_solution ()
NumericVector< Number > & get_weighted_sensitivity_solution ()
const NumericVector< Number > & get_weighted_sensitivity_solution () const
NumericVector< Number > & add_adjoint_rhs (unsigned int i=0)
NumericVector< Number > & get_adjoint_rhs (unsigned int i=0)
const NumericVector< Number > & get_adjoint_rhs (unsigned int i=0) const
NumericVector< Number > & add_sensitivity_rhs (unsigned int i=0)
NumericVector< Number > & get_sensitivity_rhs (unsigned int i=0)
const NumericVector< Number > & get_sensitivity_rhs (unsigned int i=0) const
unsigned int n_vectors () const
unsigned int n_vars () const
unsigned int n_variable_groups () const
unsigned int n_components () const
dof_id_type n_dofs () const
dof_id_type n_active_dofs () const
dof_id_type n_constrained_dofs () const
dof_id_type n_local_constrained_dofs () const
dof_id_type n_local_dofs () const
unsigned int add_variable (const std::string &var, const FEType &type, const std::set< subdomain_id_type > *const active_subdomains=nullptr)
unsigned int add_variable (const std::string &var, const Order order=FIRST, const FEFamily=LAGRANGE, const std::set< subdomain_id_type > *const active_subdomains=nullptr)
unsigned int add_variables (const std::vector< std::string > &vars, const FEType &type, const std::set< subdomain_id_type > *const active_subdomains=nullptr)
unsigned int add_variables (const std::vector< std::string > &vars, const Order order=FIRST, const FEFamily=LAGRANGE, const std::set< subdomain_id_type > *const active_subdomains=nullptr)
const Variable & variable (unsigned int var) const
const VariableGroup & variable_group (unsigned int vg) const
bool has_variable (const std::string &var) const
const std::string & variable_name (const unsigned int i) const
unsigned short int variable_number (const std::string &var) const
void get_all_variable_numbers (std::vector< unsigned int > &all_variable_numbers) const
unsigned int variable_scalar_number (const std::string &var, unsigned int component) const
unsigned int variable_scalar_number (unsigned int var_num, unsigned int component) const
const FEType & variable_type (const unsigned int i) const
const FEType & variable_type (const std::string &var) const
bool identify_variable_groups () const
void identify_variable_groups (const bool)
Real calculate_norm (const NumericVector< Number > &v, unsigned int var, FEMNormType norm_type, std::set< unsigned int > *skip_dimensions=nullptr) const
Real calculate_norm (const NumericVector< Number > &v, const SystemNorm &norm, std::set< unsigned int > *skip_dimensions=nullptr) const
void read_header (Xdr &io, const std::string &version, const bool read_header=true, const bool read_additional_data=true, const bool read_legacy_format=false)
void read_legacy_data (Xdr &io, const bool read_additional_data=true)
template<typename ValType >
void read_serialized_data (Xdr &io, const bool read_additional_data=true)
void read_serialized_data (Xdr &io, const bool read_additional_data=true)
template<typename InValType >
std::size_t read_serialized_vectors (Xdr &io, const std::vector< NumericVector< Number > *> &vectors) const
std::size_t read_serialized_vectors (Xdr &io, const std::vector< NumericVector< Number > *> &vectors) const
template<typename InValType >
void read_parallel_data (Xdr &io, const bool read_additional_data)
void read_parallel_data (Xdr &io, const bool read_additional_data)
void write_header (Xdr &io, const std::string &version, const bool write_additional_data) const
void write_serialized_data (Xdr &io, const bool write_additional_data=true) const
std::size_t write_serialized_vectors (Xdr &io, const std::vector< const NumericVector< Number > *> &vectors) const
void write_parallel_data (Xdr &io, const bool write_additional_data) const
std::string get_info () const
void attach_init_function (void fptr(EquationSystems &es, const std::string &name))
void attach_init_object (Initialization &init)
void attach_assemble_function (void fptr(EquationSystems &es, const std::string &name))
void attach_assemble_object (Assembly &assemble)
void attach_constraint_function (void fptr(EquationSystems &es, const std::string &name))
void attach_constraint_object (Constraint &constrain)
void attach_QOI_function (void fptr(EquationSystems &es, const std::string &name, const QoISet &qoi_indices))
void attach_QOI_object (QOI &qoi)
void attach_QOI_derivative (void fptr(EquationSystems &es, const std::string &name, const QoISet &qoi_indices, bool include_liftfunc, bool apply_constraints))
void attach_QOI_derivative_object (QOIDerivative &qoi_derivative)
virtual void user_initialization ()
virtual void user_assembly ()
virtual void user_constrain ()
virtual void user_QOI (const QoISet &qoi_indices)
virtual void user_QOI_derivative (const QoISet &qoi_indices=QoISet(), bool include_liftfunc=true, bool apply_constraints=true)
virtual void re_update ()
virtual void restrict_vectors ()
virtual void prolong_vectors ()
virtual void disable_cache ()
Number current_solution (const dof_id_type global_dof_number) const
unsigned int n_qois () const
Number point_value (unsigned int var, const Point &p, const bool insist_on_success=true) const
Number point_value (unsigned int var, const Point &p, const Elem &e) const
Number point_value (unsigned int var, const Point &p, const Elem *e) const
Gradient point_gradient (unsigned int var, const Point &p, const bool insist_on_success=true) const
Gradient point_gradient (unsigned int var, const Point &p, const Elem &e) const
Gradient point_gradient (unsigned int var, const Point &p, const Elem *e) const
Tensor point_hessian (unsigned int var, const Point &p, const bool insist_on_success=true) const
Tensor point_hessian (unsigned int var, const Point &p, const Elem &e) const
Tensor point_hessian (unsigned int var, const Point &p, const Elem *e) const
void local_dof_indices (const unsigned int var, std::set< dof_id_type > &var_indices) const
void zero_variable (NumericVector< Number > &v, unsigned int var_num) const
bool & hide_output ()
void projection_matrix (SparseMatrix< Number > &proj_mat) const
const Parallel::Communicator & comm () const
processor_id_type n_processors () const
processor_id_type processor_id () const
Static Public Member Functions
static std::string get_info ()
static void print_info (std::ostream &out=libMesh::out)
static unsigned int n_objects ()
static void enable_print_counter_info ()
static void disable_print_counter_info ()
Public Attributes
std::unique_ptr< SparseMatrix< Number > > matrix_A
std::unique_ptr< SparseMatrix< Number > > matrix_B
std::unique_ptr< EigenSolver< Number > > eigen_solver
bool assemble_before_solve
bool use_fixed_solution
int extra_quadrature_order
std::unique_ptr< NumericVector< Number > > solution
std::unique_ptr< NumericVector< Number > > current_local_solution
Real time
std::vector< Number > qoi
Protected Types
typedef std::map< std::string, std::pair< unsigned int, unsigned int > > Counts
Protected Member Functions
virtual void init_data () override
virtual void init_matrices ()
void set_n_converged (unsigned int nconv)
void set_n_iterations (unsigned int its)
void project_vector (NumericVector< Number > &, int is_adjoint=-1) const
void project_vector (const NumericVector< Number > &, NumericVector< Number > &, int is_adjoint=-1) const
void increment_constructor_count (const std::string &name)
void increment_destructor_count (const std::string &name)
Protected Attributes
const Parallel::Communicator & _communicator
Static Protected Attributes
static Counts _counts
static Threads::atomic< unsigned int > _n_objects
static Threads::spin_mutex _mutex
static bool _enable_print_counter = true
Private Attributes
unsigned int _n_converged_eigenpairs
unsigned int _n_iterations
bool _is_generalized_eigenproblem
EigenProblemType _eigen_problem_type
Detailed Description
Manages consistently variables, degrees of freedom, and coefficient vectors for eigenvalue problems.
Currently, this class is able to handle standard eigenvalue problems A*x=lambda*x and generalized eigenvalue problems A*x=lambda*B*x.
The matrices EigenSystem::matrix_A and EigenSystem::matrix_B should be filled during assembly.
Author
Steffen Peterson
Date
2005 Base class for defining systems of equations for eigenproblems.
Definition at line 54 of file eigen_system.h.
Member Typedef Documentation
const_vectors_iterator
typedef std::map<std::string, NumericVector<Number> *>::const_iterator libMesh::System::const_vectors_iterator inherited
Definition at line 749 of file system.h.
Counts
typedef std::map<std::string, std::pair<unsigned int, unsigned int> > libMesh::ReferenceCounter::Counts protected inherited
Data structure to log the information. The log is identified by the class name.
Definition at line 117 of file reference_counter.h.
GradientFunctionPointer
typedef Gradient(* libMesh::System::GradientFunctionPointer) (const Point &p, const Parameters &parameters, const std::string &sys_name, const std::string &unknown_name) inherited
Definition at line 524 of file system.h.
Parent
typedef System libMesh::EigenSystem::Parent
The type of the parent
Definition at line 79 of file eigen_system.h.
sys_type
typedef EigenSystem libMesh::EigenSystem::sys_type
The type of system.
Definition at line 74 of file eigen_system.h.
ValueFunctionPointer
typedef Number(* libMesh::System::ValueFunctionPointer) (const Point &p, const Parameters &Parameters, const std::string &sys_name, const std::string &unknown_name) inherited
Projects arbitrary functions onto the current solution. The function value fptr and its gradient gptr are represented by function pointers. A gradient gptr is only required/used for projecting onto finite element spaces with continuous derivatives.
Definition at line 520 of file system.h.
vectors_iterator
typedef std::map<std::string, NumericVector<Number> *>::iterator libMesh::System::vectors_iterator inherited
Vector iterator typedefs.
Definition at line 748 of file system.h.
Constructor & Destructor Documentation
EigenSystem()
libMesh::EigenSystem::EigenSystem (EquationSystems & es, const std::string & name_in, const unsigned int number_in)
Constructor. Optionally initializes required data structures.
Definition at line 40 of file eigen_system.C.
                             :
   Parent           (es, name_in, number_in),
   eigen_solver     (EigenSolver<Number>::build(es.comm())),
   _n_converged_eigenpairs (0),
   _n_iterations           (0),
   _is_generalized_eigenproblem (false),
   _eigen_problem_type (NHEP)
 {
 }
~EigenSystem()
libMesh::EigenSystem::~EigenSystem () virtual
Destructor.
Definition at line 55 of file eigen_system.C.
References clear().
 {
   // clear data
   this->clear();
 }
Member Function Documentation
activate()
void libMesh::System::activate () inline inherited
Activates the system. Only active systems are solved.
Definition at line 2073 of file system.h.
References libMesh::System::_active.
 {
   _active = true;
 }
active()
bool libMesh::System::active () const inline inherited
Returns
true if the system is active, false otherwise. An active system will be solved.
Definition at line 2065 of file system.h.
References libMesh::System::_active.
 {
   return _active;
 }
add_adjoint_rhs()
NumericVector< Number > & libMesh::System::add_adjoint_rhs (unsigned int i = 0) inherited
Returns
A reference to one of the system's adjoint rhs vectors, by default the one corresponding to the first qoi. Creates the vector if it doesn't already exist.
Definition at line 1021 of file system.C.
References libMesh::System::add_vector().
Referenced by libMesh::ExplicitSystem::assemble_qoi_derivative(), and libMesh::FEMSystem::assemble_qoi_derivative().
 {
   std::ostringstream adjoint_rhs_name;
   adjoint_rhs_name << "adjoint_rhs" << i;
   return this->add_vector(adjoint_rhs_name.str(), false);
 }
add_adjoint_solution()
NumericVector< Number > & libMesh::System::add_adjoint_solution (unsigned int i = 0) inherited
Returns
A reference to one of the system's adjoint solution vectors, by default the one corresponding to the first qoi. Creates the vector if it doesn't already exist.
Definition at line 957 of file system.C.
References libMesh::System::add_vector(), and libMesh::System::set_vector_as_adjoint().
Referenced by libMesh::ImplicitSystem::adjoint_solve().
 {
   std::ostringstream adjoint_name;
   adjoint_name << "adjoint_solution" << i;
   NumericVector<Number> & returnval = this->add_vector(adjoint_name.str());
   this->set_vector_as_adjoint(adjoint_name.str(), i);
   return returnval;
 }
add_sensitivity_rhs()
NumericVector< Number > & libMesh::System::add_sensitivity_rhs (unsigned int i = 0) inherited
Returns
A reference to one of the system's sensitivity rhs vectors, by default the one corresponding to the first parameter. Creates the vector if it doesn't already exist.
Definition at line 1051 of file system.C.
References libMesh::System::add_vector().
Referenced by libMesh::ImplicitSystem::assemble_residual_derivatives().
 {
   std::ostringstream sensitivity_rhs_name;
   sensitivity_rhs_name << "sensitivity_rhs" << i;
   return this->add_vector(sensitivity_rhs_name.str(), false);
 }
add_sensitivity_solution()
NumericVector< Number > & libMesh::System::add_sensitivity_solution (unsigned int i = 0) inherited
Returns
A reference to one of the system's solution sensitivity vectors, by default the one corresponding to the first parameter. Creates the vector if it doesn't already exist.
Definition at line 906 of file system.C.
References libMesh::System::add_vector().
Referenced by libMesh::ImplicitSystem::sensitivity_solve().
 {
   std::ostringstream sensitivity_name;
   sensitivity_name << "sensitivity_solution" << i;
   return this->add_vector(sensitivity_name.str());
 }
add_variable() [1/2]
unsigned int libMesh::System::add_variable (const std::string & var, const FEType & type, const std::set< subdomain_id_type > *const active_subdomains = nullptr) inherited
Adds the variable var to the list of variables for this system.
Returns
The index number for the new variable.
Definition at line 1081 of file system.C.
References libMesh::System::_variable_groups, libMesh::System::_variable_numbers, libMesh::System::_variables, libMesh::System::add_variables(), libMesh::VariableGroup::append(), libMesh::System::identify_variable_groups(), libMesh::System::is_initialized(), libMesh::System::n_variable_groups(), libMesh::System::n_vars(), libMesh::System::number(), libMesh::System::variable_name(), and libMesh::System::variable_type().
Referenced by libMesh::DifferentiableSystem::add_second_order_dot_vars(), libMesh::System::add_variable(), libMesh::ErrorVector::plot_error(), and libMesh::System::read_header().
 {
   libmesh_assert(!this->is_initialized());
   // Make sure the variable isn't there already
   // or if it is, that it's the type we want
   for (unsigned int v=0; v<this->n_vars(); v++)
     if (this->variable_name(v) == var)
       {
         if (this->variable_type(v) == type)
           return _variables[v].number();
         libmesh_error_msg("ERROR: incompatible variable " << var << " has already been added for this system!");
       }
   // Optimize for VariableGroups here - if the user is adding multiple
   // variables of the same FEType and subdomain restriction, catch
   // that here and add them as members of the same VariableGroup.
   //
   // start by setting this flag to whatever the user has requested
   // and then consider the conditions which should negate it.
   bool should_be_in_vg = this->identify_variable_groups();
   // No variable groups, nothing to add to
   if (!this->n_variable_groups())
     should_be_in_vg = false;
   else
     {
       VariableGroup & vg(_variable_groups.back());
       // get a pointer to their subdomain restriction, if any.
       const std::set<subdomain_id_type> * const
         their_active_subdomains (vg.implicitly_active() ?
                                  nullptr : &vg.active_subdomains());
       // Different types?
       if (vg.type() != type)
         should_be_in_vg = false;
       // they are restricted, we aren't?
       if (their_active_subdomains && !active_subdomains)
         should_be_in_vg = false;
       // they aren't restricted, we are?
       if (!their_active_subdomains && active_subdomains)
         should_be_in_vg = false;
       if (their_active_subdomains && active_subdomains)
         // restricted to different sets?
         if (*their_active_subdomains != *active_subdomains)
           should_be_in_vg = false;
       // OK, after all that, append the variable to the vg if none of the conditions
       // were violated
       if (should_be_in_vg)
         {
           const unsigned short curr_n_vars = cast_int<unsigned short>
             (this->n_vars());
           vg.append (var);
           _variables.push_back(vg(vg.n_variables()-1));
           _variable_numbers[var] = curr_n_vars;
           return curr_n_vars;
         }
     }
   // otherwise, fall back to adding a single variable group
   return this->add_variables (std::vector<std::string>(1, var),
                               type,
                               active_subdomains);
 }
add_variable() [2/2]
unsigned int libMesh::System::add_variable (const std::string & var, const Order order = FIRST, const FEFamily family = LAGRANGE, const std::set< subdomain_id_type > *const active_subdomains = nullptr) inherited
Adds the variable var to the list of variables for this system. Same as before, but assumes LAGRANGE as default value for FEType.family.
Definition at line 1159 of file system.C.
References libMesh::System::add_variable().
 {
   return this->add_variable(var,
                             FEType(order, family),
                             active_subdomains);
 }
add_variables() [1/2]
unsigned int libMesh::System::add_variables (const std::vector< std::string > & vars, const FEType & type, const std::set< subdomain_id_type > *const active_subdomains = nullptr) inherited
Adds the variable var to the list of variables for this system.
Returns
The index number for the new variable.
Definition at line 1171 of file system.C.
References libMesh::System::_variable_groups, libMesh::System::_variable_numbers, libMesh::System::_variables, libMesh::System::is_initialized(), libMesh::System::n_components(), libMesh::System::n_vars(), libMesh::System::number(), libMesh::System::variable_name(), and libMesh::System::variable_type().
Referenced by libMesh::System::add_variable(), and libMesh::System::add_variables().
 {
   libmesh_assert(!this->is_initialized());
   // Make sure the variable isn't there already
   // or if it is, that it's the type we want
   for (std::size_t ov=0; ov<vars.size(); ov++)
     for (unsigned int v=0; v<this->n_vars(); v++)
       if (this->variable_name(v) == vars[ov])
         {
           if (this->variable_type(v) == type)
             return _variables[v].number();
           libmesh_error_msg("ERROR: incompatible variable " << vars[ov] << " has already been added for this system!");
         }
   const unsigned short curr_n_vars = cast_int<unsigned short>
     (this->n_vars());
   const unsigned int next_first_component = this->n_components();
   // Add the variable group to the list
   _variable_groups.push_back((active_subdomains == nullptr) ?
                              VariableGroup(this, vars, curr_n_vars,
                                            next_first_component, type) :
                              VariableGroup(this, vars, curr_n_vars,
                                            next_first_component, type, *active_subdomains));
   const VariableGroup & vg (_variable_groups.back());
   // Add each component of the group individually
   for (auto v : IntRange<unsigned int>(0, vars.size()))
     {
       _variables.push_back (vg(v));
       _variable_numbers[vars[v]] = cast_int<unsigned short>
         (curr_n_vars+v);
     }
   libmesh_assert_equal_to ((curr_n_vars+vars.size()), this->n_vars());
   // BSK - Defer this now to System::init_data() so we can detect
   // VariableGroups 12/28/2012
   // // Add the variable group to the _dof_map
   // _dof_map->add_variable_group (vg);
   // Return the number of the new variable
   return cast_int<unsigned int>(curr_n_vars+vars.size()-1);
 }
add_variables() [2/2]
unsigned int libMesh::System::add_variables (const std::vector< std::string > & vars, const Order order = FIRST, const FEFamily family = LAGRANGE, const std::set< subdomain_id_type > *const active_subdomains = nullptr) inherited
Adds the variable var to the list of variables for this system. Same as before, but assumes LAGRANGE as default value for FEType.family.
Definition at line 1224 of file system.C.
References libMesh::System::add_variables().
 {
   return this->add_variables(vars,
                              FEType(order, family),
                              active_subdomains);
 }
add_vector()
NumericVector< Number > & libMesh::System::add_vector (const std::string & vec_name, const bool projections = true, const ParallelType type = PARALLEL) inherited
Adds the additional vector vec_name to this system. All the additional vectors are similarly distributed, like the solution, and initialized to zero.
By default vectors added by add_vector are projected to changed grids by reinit(). To zero them instead (more efficient), pass "false" as the second argument
Definition at line 661 of file system.C.
References libMesh::System::_dof_map, libMesh::System::_is_initialized, libMesh::System::_vector_is_adjoint, libMesh::System::_vector_projections, libMesh::System::_vector_types, libMesh::System::_vectors, libMesh::NumericVector< T >::build(), libMesh::ParallelObject::comm(), libMesh::GHOSTED, libMesh::System::have_vector(), libMesh::NumericVector< T >::init(), libMesh::System::n_dofs(), and libMesh::System::n_local_dofs().
Referenced by libMesh::System::add_adjoint_rhs(), libMesh::System::add_adjoint_solution(), libMesh::System::add_sensitivity_rhs(), libMesh::System::add_sensitivity_solution(), libMesh::ExplicitSystem::add_system_rhs(), libMesh::System::add_weighted_sensitivity_adjoint_solution(), libMesh::System::add_weighted_sensitivity_solution(), libMesh::AdjointRefinementEstimator::estimate_error(), libMesh::SecondOrderUnsteadySolver::init(), libMesh::UnsteadySolver::init(), libMesh::OptimizationSystem::init_data(), libMesh::ContinuationSystem::init_data(), libMesh::NewmarkSystem::NewmarkSystem(), libMesh::System::read_header(), libMesh::FrequencySystem::set_frequencies(), libMesh::FrequencySystem::set_frequencies_by_range(), and libMesh::FrequencySystem::set_frequencies_by_steps().
 {
   // Return the vector if it is already there.
   if (this->have_vector(vec_name))
     return *(_vectors[vec_name]);
   // Otherwise build the vector
   NumericVector<Number> * buf = NumericVector<Number>::build(this->comm()).release();
   _vectors.insert (std::make_pair (vec_name, buf));
   _vector_projections.insert (std::make_pair (vec_name, projections));
   _vector_types.insert (std::make_pair (vec_name, type));
   // Vectors are primal by default
   _vector_is_adjoint.insert (std::make_pair (vec_name, -1));
   // Initialize it if necessary
   if (_is_initialized)
     {
       if (type == GHOSTED)
         {
 #ifdef LIBMESH_ENABLE_GHOSTED
           buf->init (this->n_dofs(), this->n_local_dofs(),
                      _dof_map->get_send_list(), false,
                      GHOSTED);
 #else
           libmesh_error_msg("Cannot initialize ghosted vectors when they are not enabled.");
 #endif
         }
       else
         buf->init (this->n_dofs(), this->n_local_dofs(), false, type);
     }
   return *buf;
 }
add_weighted_sensitivity_adjoint_solution()
NumericVector< Number > & libMesh::System::add_weighted_sensitivity_adjoint_solution (unsigned int i = 0) inherited
Returns
A reference to one of the system's weighted sensitivity adjoint solution vectors, by default the one corresponding to the first qoi. Creates the vector if it doesn't already exist.
Definition at line 989 of file system.C.
References libMesh::System::add_vector(), and libMesh::System::set_vector_as_adjoint().
Referenced by libMesh::ImplicitSystem::weighted_sensitivity_adjoint_solve().
 {
   std::ostringstream adjoint_name;
   adjoint_name << "weighted_sensitivity_adjoint_solution" << i;
   NumericVector<Number> & returnval = this->add_vector(adjoint_name.str());
   this->set_vector_as_adjoint(adjoint_name.str(), i);
   return returnval;
 }
add_weighted_sensitivity_solution()
NumericVector< Number > & libMesh::System::add_weighted_sensitivity_solution () inherited
Returns
A reference to the solution of the last weighted sensitivity solve Creates the vector if it doesn't already exist.
Definition at line 936 of file system.C.
References libMesh::System::add_vector().
Referenced by libMesh::ImplicitSystem::weighted_sensitivity_solve().
 {
   return this->add_vector("weighted_sensitivity_solution");
 }
adjoint_qoi_parameter_sensitivity()
void libMesh::System::adjoint_qoi_parameter_sensitivity (const QoISet & qoi_indices, const ParameterVector & parameters, SensitivityData & sensitivities) inline virtual inherited
Solves for parameter sensitivities using the adjoint method.
This method is only implemented in some derived classes.
Reimplemented in libMesh::ImplicitSystem.
Definition at line 2316 of file system.h.
Referenced by libMesh::System::qoi_parameter_sensitivity().
 {
   libmesh_not_implemented();
 }
adjoint_solve()
std::pair< unsigned int, Real > libMesh::System::adjoint_solve (const QoISet & qoi_indices = QoISet()) inline virtual inherited
Solves the adjoint system, for the specified qoi indices, or for every qoi if qoi_indices is nullptr. Must be overridden in derived systems.
Returns
A pair with the total number of linear iterations performed and the (sum of the) final residual norms
This method is only implemented in some derived classes.
Reimplemented in libMesh::ImplicitSystem, and libMesh::DifferentiableSystem.
Definition at line 2300 of file system.h.
Referenced by libMesh::UniformRefinementEstimator::_estimate_error(), libMesh::AdjointRefinementEstimator::estimate_error(), and libMesh::AdjointResidualErrorEstimator::estimate_error().
 {
   libmesh_not_implemented();
 }
assemble()
void libMesh::EigenSystem::assemble () override virtual
Assembles the system matrix.
Reimplemented from libMesh::System.
Definition at line 247 of file eigen_system.C.
References libMesh::System::assemble().
Referenced by libMesh::CondensedEigenSystem::solve(), and solve().
 {
   // Assemble the linear system
   Parent::assemble ();
 }
assemble_qoi()
void libMesh::System::assemble_qoi (const QoISet & qoi_indices = QoISet()) virtual inherited
Calls user qoi function. Can be overridden in derived classes.
Reimplemented in libMesh::FEMSystem, and libMesh::ExplicitSystem.
Definition at line 473 of file system.C.
References libMesh::System::user_QOI().
Referenced by libMesh::ExplicitSystem::assemble_qoi().
 {
   // Log how long the user's assembly code takes
   LOG_SCOPE("assemble_qoi()", "System");
   // Call the user-specified quantity of interest function
   this->user_QOI(qoi_indices);
 }
assemble_qoi_derivative()
void libMesh::System::assemble_qoi_derivative (const QoISet & qoi_indices = QoISet(), bool include_liftfunc = true, bool apply_constraints = true) virtual inherited
Calls user qoi derivative function. Can be overridden in derived classes.
Reimplemented in libMesh::FEMSystem, and libMesh::ExplicitSystem.
Definition at line 484 of file system.C.
References libMesh::System::user_QOI_derivative().
Referenced by libMesh::ExplicitSystem::assemble_qoi_derivative().
 {
   // Log how long the user's assembly code takes
   LOG_SCOPE("assemble_qoi_derivative()", "System");
   // Call the user-specified quantity of interest function
   this->user_QOI_derivative(qoi_indices, include_liftfunc,
                             apply_constraints);
 }
assemble_residual_derivatives()
void libMesh::System::assemble_residual_derivatives (const ParameterVector & parameters) inline virtual inherited
Calls residual parameter derivative function.
Library subclasses use finite differences by default.
This should assemble the sensitivity rhs vectors to hold -(partial R / partial p_i), making them ready to solve the forward sensitivity equation.
This method is only implemented in some derived classes.
Reimplemented in libMesh::ImplicitSystem.
Definition at line 2269 of file system.h.
 {
   libmesh_not_implemented();
 }
attach_assemble_function()
void libMesh::System::attach_assemble_function (void fptrEquationSystems &es, const std::string &name) inherited
Register a user function to use in assembling the system matrix and RHS.
Definition at line 1777 of file system.C.
References libMesh::System::_assemble_system_function, libMesh::System::_assemble_system_object, and libMesh::out.
 {
   libmesh_assert(fptr);
   if (_assemble_system_object != nullptr)
     {
       libmesh_here();
       libMesh::out << "WARNING:  Cannot specify both assembly function and object!"
                    << std::endl;
       _assemble_system_object = nullptr;
     }
   _assemble_system_function = fptr;
 }
attach_assemble_object()
void libMesh::System::attach_assemble_object (System::Assembly & assemble_in) inherited
Register a user object to use in assembling the system matrix and RHS.
Definition at line 1796 of file system.C.
References libMesh::System::_assemble_system_function, libMesh::System::_assemble_system_object, and libMesh::out.
 {
   if (_assemble_system_function != nullptr)
     {
       libmesh_here();
       libMesh::out << "WARNING:  Cannot specify both assembly object and function!"
                    << std::endl;
       _assemble_system_function = nullptr;
     }
   _assemble_system_object = &assemble_in;
 }
attach_constraint_function()
void libMesh::System::attach_constraint_function (void fptrEquationSystems &es, const std::string &name) inherited
Register a user function for imposing constraints.
Definition at line 1812 of file system.C.
References libMesh::System::_constrain_system_function, libMesh::System::_constrain_system_object, and libMesh::out.
 {
   libmesh_assert(fptr);
   if (_constrain_system_object != nullptr)
     {
       libmesh_here();
       libMesh::out << "WARNING:  Cannot specify both constraint function and object!"
                    << std::endl;
       _constrain_system_object = nullptr;
     }
   _constrain_system_function = fptr;
 }
attach_constraint_object()
void libMesh::System::attach_constraint_object (System::Constraint & constrain) inherited
Register a user object for imposing constraints.
Definition at line 1831 of file system.C.
References libMesh::System::_constrain_system_function, libMesh::System::_constrain_system_object, and libMesh::out.
 {
   if (_constrain_system_function != nullptr)
     {
       libmesh_here();
       libMesh::out << "WARNING:  Cannot specify both constraint object and function!"
                    << std::endl;
       _constrain_system_function = nullptr;
     }
   _constrain_system_object = &constrain;
 }
attach_init_function()
void libMesh::System::attach_init_function (void fptrEquationSystems &es, const std::string &name) inherited
Register a user function to use in initializing the system.
Definition at line 1742 of file system.C.
References libMesh::System::_init_system_function, libMesh::System::_init_system_object, and libMesh::out.
 {
   libmesh_assert(fptr);
   if (_init_system_object != nullptr)
     {
       libmesh_here();
       libMesh::out << "WARNING:  Cannot specify both initialization function and object!"
                    << std::endl;
       _init_system_object = nullptr;
     }
   _init_system_function = fptr;
 }
attach_init_object()
void libMesh::System::attach_init_object (System::Initialization & init_in) inherited
Register a user class to use to initialize the system.
Note
This is exclusive with the attach_init_function.
Definition at line 1761 of file system.C.
References libMesh::System::_init_system_function, libMesh::System::_init_system_object, and libMesh::out.
 {
   if (_init_system_function != nullptr)
     {
       libmesh_here();
       libMesh::out << "WARNING:  Cannot specify both initialization object and function!"
                    << std::endl;
       _init_system_function = nullptr;
     }
   _init_system_object = &init_in;
 }
attach_QOI_derivative()
void libMesh::System::attach_QOI_derivative (void fptrEquationSystems &es, const std::string &name, const QoISet &qoi_indices, bool include_liftfunc, bool apply_constraints) inherited
Register a user function for evaluating derivatives of a quantity of interest with respect to test functions, whose values should be placed in System::rhs
Definition at line 1883 of file system.C.
References libMesh::System::_qoi_evaluate_derivative_function, libMesh::System::_qoi_evaluate_derivative_object, and libMesh::out.
 {
   libmesh_assert(fptr);
   if (_qoi_evaluate_derivative_object != nullptr)
     {
       libmesh_here();
       libMesh::out << "WARNING:  Cannot specify both QOI derivative function and object!"
                    << std::endl;
       _qoi_evaluate_derivative_object = nullptr;
     }
   _qoi_evaluate_derivative_function = fptr;
 }
attach_QOI_derivative_object()
void libMesh::System::attach_QOI_derivative_object (QOIDerivative & qoi_derivative) inherited
Register a user object for evaluating derivatives of a quantity of interest with respect to test functions, whose values should be placed in System::rhs
Definition at line 1902 of file system.C.
References libMesh::System::_qoi_evaluate_derivative_function, libMesh::System::_qoi_evaluate_derivative_object, and libMesh::out.
 {
   if (_qoi_evaluate_derivative_function != nullptr)
     {
       libmesh_here();
       libMesh::out << "WARNING:  Cannot specify both QOI derivative object and function!"
                    << std::endl;
       _qoi_evaluate_derivative_function = nullptr;
     }
   _qoi_evaluate_derivative_object = &qoi_derivative;
 }
attach_QOI_function()
void libMesh::System::attach_QOI_function (void fptrEquationSystems &es, const std::string &name, const QoISet &qoi_indices) inherited
Register a user function for evaluating the quantities of interest, whose values should be placed in System::qoi
Definition at line 1847 of file system.C.
References libMesh::System::_qoi_evaluate_function, libMesh::System::_qoi_evaluate_object, and libMesh::out.
 {
   libmesh_assert(fptr);
   if (_qoi_evaluate_object != nullptr)
     {
       libmesh_here();
       libMesh::out << "WARNING:  Cannot specify both QOI function and object!"
                    << std::endl;
       _qoi_evaluate_object = nullptr;
     }
   _qoi_evaluate_function = fptr;
 }
attach_QOI_object()
void libMesh::System::attach_QOI_object (QOI & qoi) inherited
Register a user object for evaluating the quantities of interest, whose values should be placed in System::qoi
Definition at line 1867 of file system.C.
References libMesh::System::_qoi_evaluate_function, libMesh::System::_qoi_evaluate_object, and libMesh::out.
 {
   if (_qoi_evaluate_function != nullptr)
     {
       libmesh_here();
       libMesh::out << "WARNING:  Cannot specify both QOI object and function!"
                    << std::endl;
       _qoi_evaluate_function = nullptr;
     }
   _qoi_evaluate_object = &qoi_in;
 }
boundary_project_solution() [1/2]
void libMesh::System::boundary_project_solution (const std::set< boundary_id_type > & b, const std::vector< unsigned int > & variables, FunctionBase< Number > * f, FunctionBase< Gradient > * g = nullptr) inherited
Projects arbitrary boundary functions onto a vector of degree of freedom values for the current system. Only degrees of freedom which affect the function's trace on a boundary in the set b are affected. Only degrees of freedom associated with the variables listed in the vector variables are projected. The function value f and its gradient g are user-provided cloneable functors. A gradient g is only required/used for projecting onto finite element spaces with continuous derivatives. If non-default Parameters are to be used, they can be provided in the parameters argument.
This method projects an arbitrary boundary function onto the solution via L2 projections and nodal interpolations on each element.
Definition at line 985 of file system_projection.C.
 {
   this->boundary_project_vector(b, variables, *solution, f, g);
   solution->localize(*current_local_solution);
 }
boundary_project_solution() [2/2]
void libMesh::System::boundary_project_solution (const std::set< boundary_id_type > & b, const std::vector< unsigned int > & variables, ValueFunctionPointer fptr, GradientFunctionPointer gptr, const Parameters & parameters) inherited
Projects arbitrary boundary functions onto a vector of degree of freedom values for the current system. Only degrees of freedom which affect the function's trace on a boundary in the set b are affected. Only degrees of freedom associated with the variables listed in the vector variables are projected. The function value fptr and its gradient gptr are represented by function pointers. A gradient gptr is only required/used for projecting onto finite element spaces with continuous derivatives.
This method projects components of an arbitrary boundary function onto the solution via L2 projections and nodal interpolations on each element.
Definition at line 968 of file system_projection.C.
 {
   WrappedFunction<Number> f(*this, fptr, &parameters);
   WrappedFunction<Gradient> g(*this, gptr, &parameters);
   this->boundary_project_solution(b, variables, &f, &g);
 }
boundary_project_vector() [1/2]
void libMesh::System::boundary_project_vector (const std::set< boundary_id_type > & b, const std::vector< unsigned int > & variables, NumericVector< Number > & new_vector, FunctionBase< Number > * f, FunctionBase< Gradient > * g = nullptr, int is_adjoint = -1) const inherited
Projects arbitrary boundary functions onto a vector of degree of freedom values for the current system. Only degrees of freedom which affect the function's trace on a boundary in the set b are affected. Only degrees of freedom associated with the variables listed in the vector variables are projected. The function value f and its gradient g are user-provided cloneable functors. A gradient g is only required/used for projecting onto finite element spaces with continuous derivatives. If non-default Parameters are to be used, they can be provided in the parameters argument.
Constrain the new vector using the requested adjoint rather than primal constraints if is_adjoint is non-negative.
This method projects an arbitrary function via L2 projections and nodal interpolations on each element.
Definition at line 1021 of file system_projection.C.
References libMesh::NumericVector< T >::close(), and libMesh::Threads::parallel_for().
 {
   LOG_SCOPE ("boundary_project_vector()", "System");
   Threads::parallel_for
     (ConstElemRange (this->get_mesh().active_local_elements_begin(),
                      this->get_mesh().active_local_elements_end() ),
      BoundaryProjectSolution(b, variables, *this, f, g,
                              this->get_equation_systems().parameters,
                              new_vector)
      );
   // We don't do SCALAR dofs when just projecting the boundary, so
   // we're done here.
   new_vector.close();
 #ifdef LIBMESH_ENABLE_CONSTRAINTS
   if (is_adjoint == -1)
     this->get_dof_map().enforce_constraints_exactly(*this, &new_vector);
   else if (is_adjoint >= 0)
     this->get_dof_map().enforce_adjoint_constraints_exactly(new_vector,
                                                             is_adjoint);
 #endif
 }
boundary_project_vector() [2/2]
void libMesh::System::boundary_project_vector (const std::set< boundary_id_type > & b, const std::vector< unsigned int > & variables, ValueFunctionPointer fptr, GradientFunctionPointer gptr, const Parameters & parameters, NumericVector< Number > & new_vector, int is_adjoint = -1) const inherited
Projects arbitrary boundary functions onto a vector of degree of freedom values for the current system. Only degrees of freedom which affect the function's trace on a boundary in the set b are affected. Only degrees of freedom associated with the variables listed in the vector variables are projected. The function value fptr and its gradient gptr are represented by function pointers. A gradient gptr is only required/used for projecting onto finite element spaces with continuous derivatives.
Constrain the new vector using the requested adjoint rather than primal constraints if is_adjoint is non-negative.
This method projects an arbitrary boundary function via L2 projections and nodal interpolations on each element.
Definition at line 1003 of file system_projection.C.
 {
   WrappedFunction<Number> f(*this, fptr, &parameters);
   WrappedFunction<Gradient> g(*this, gptr, &parameters);
   this->boundary_project_vector(b, variables, new_vector, &f, &g,
                                 is_adjoint);
 }
calculate_norm() [1/2]
Real libMesh::System::calculate_norm (const NumericVector< Number > & v, unsigned int var, FEMNormType norm_type, std::set< unsigned int > * skip_dimensions = nullptr) const inherited
Returns
A norm of variable var in the vector v, in the specified norm (e.g. L2, L_INF, H1)
Definition at line 1378 of file system.C.
References libMesh::DISCRETE_L1, libMesh::DISCRETE_L2, libMesh::DISCRETE_L_INF, libMesh::System::discrete_var_norm(), libMesh::L2, libMesh::System::n_vars(), and libMesh::Real.
Referenced by libMesh::AdaptiveTimeSolver::calculate_norm(), and libMesh::UnsteadySolver::du().
 {
   //short circuit to save time
   if (norm_type == DISCRETE_L1 ||
       norm_type == DISCRETE_L2 ||
       norm_type == DISCRETE_L_INF)
     return discrete_var_norm(v,var,norm_type);
   // Not a discrete norm
   std::vector<FEMNormType> norms(this->n_vars(), L2);
   std::vector<Real> weights(this->n_vars(), 0.0);
   norms[var] = norm_type;
   weights[var] = 1.0;
   Real val = this->calculate_norm(v, SystemNorm(norms, weights), skip_dimensions);
   return val;
 }
calculate_norm() [2/2]
Real libMesh::System::calculate_norm (const NumericVector< Number > & v, const SystemNorm & norm, std::set< unsigned int > * skip_dimensions = nullptr) const inherited
Returns
A norm of the vector v, using component_norm and component_scale to choose and weight the norms of each variable.
Definition at line 1400 of file system.C.
References libMesh::System::_dof_map, libMesh::System::_mesh, std::abs(), libMesh::TypeVector< T >::add_scaled(), libMesh::TypeTensor< T >::add_scaled(), libMesh::FEGenericBase< OutputType >::build(), libMesh::NumericVector< T >::build(), libMesh::ParallelObject::comm(), libMesh::FEType::default_quadrature_rule(), libMesh::DISCRETE_L1, libMesh::DISCRETE_L2, libMesh::DISCRETE_L_INF, libMesh::System::discrete_var_norm(), libMesh::DofMap::dof_indices(), libMesh::MeshBase::elem_dimensions(), libMesh::FEGenericBase< OutputType >::get_d2phi(), libMesh::System::get_dof_map(), libMesh::FEGenericBase< OutputType >::get_dphi(), libMesh::FEAbstract::get_JxW(), libMesh::System::get_mesh(), libMesh::FEGenericBase< OutputType >::get_phi(), libMesh::H1, libMesh::H1_SEMINORM, libMesh::H2, libMesh::H2_SEMINORM, libMesh::SystemNorm::is_discrete(), libMesh::L1, libMesh::NumericVector< T >::l1_norm(), libMesh::L2, libMesh::NumericVector< T >::l2_norm(), libMesh::L_INF, libMesh::NumericVector< T >::linfty_norm(), libMesh::NumericVector< T >::localize(), std::max(), libMesh::Parallel::Communicator::max(), libMesh::QBase::n_points(), libMesh::System::n_vars(), libMesh::TypeVector< T >::norm(), libMesh::TypeTensor< T >::norm(), libMesh::TensorTools::norm_sq(), libMesh::TypeVector< T >::norm_sq(), libMesh::TypeTensor< T >::norm_sq(), libMesh::Real, libMesh::FEAbstract::reinit(), libMesh::SERIAL, libMesh::NumericVector< T >::size(), libMesh::Parallel::Communicator::sum(), libMesh::SystemNorm::type(), libMesh::DofMap::variable_type(), libMesh::W1_INF_SEMINORM, libMesh::W2_INF_SEMINORM, libMesh::SystemNorm::weight(), and libMesh::SystemNorm::weight_sq().
 {
   // This function must be run on all processors at once
   parallel_object_only();
   LOG_SCOPE ("calculate_norm()", "System");
   // Zero the norm before summation
   Real v_norm = 0.;
   if (norm.is_discrete())
     {
       //Check to see if all weights are 1.0 and all types are equal
       FEMNormType norm_type0 = norm.type(0);
       unsigned int check_var = 0;
       for (; check_var != this->n_vars(); ++check_var)
         if ((norm.weight(check_var) != 1.0) || (norm.type(check_var) != norm_type0))
           break;
       //All weights were 1.0 so just do the full vector discrete norm
       if (check_var == this->n_vars())
         {
           if (norm_type0 == DISCRETE_L1)
             return v.l1_norm();
           if (norm_type0 == DISCRETE_L2)
             return v.l2_norm();
           if (norm_type0 == DISCRETE_L_INF)
             return v.linfty_norm();
           else
             libmesh_error_msg("Invalid norm_type0 = " << norm_type0);
         }
       for (unsigned int var=0; var != this->n_vars(); ++var)
         {
           // Skip any variables we don't need to integrate
           if (norm.weight(var) == 0.0)
             continue;
           v_norm += norm.weight(var) * discrete_var_norm(v, var, norm.type(var));
         }
       return v_norm;
     }
   // Localize the potentially parallel vector
   std::unique_ptr<NumericVector<Number>> local_v = NumericVector<Number>::build(this->comm());
   local_v->init(v.size(), true, SERIAL);
   v.localize (*local_v, _dof_map->get_send_list());
   // I'm not sure how best to mix Hilbert norms on some variables (for
   // which we'll want to square then sum then square root) with norms
   // like L_inf (for which we'll just want to take an absolute value
   // and then sum).
   bool using_hilbert_norm = true,
     using_nonhilbert_norm = true;
   // Loop over all variables
   for (unsigned int var=0; var != this->n_vars(); ++var)
     {
       // Skip any variables we don't need to integrate
       Real norm_weight_sq = norm.weight_sq(var);
       if (norm_weight_sq == 0.0)
         continue;
       Real norm_weight = norm.weight(var);
       // Check for unimplemented norms (rather than just returning 0).
       FEMNormType norm_type = norm.type(var);
       if ((norm_type==H1) ||
           (norm_type==H2) ||
           (norm_type==L2) ||
           (norm_type==H1_SEMINORM) ||
           (norm_type==H2_SEMINORM))
         {
           if (!using_hilbert_norm)
             libmesh_not_implemented();
           using_nonhilbert_norm = false;
         }
       else if ((norm_type==L1) ||
                (norm_type==L_INF) ||
                (norm_type==W1_INF_SEMINORM) ||
                (norm_type==W2_INF_SEMINORM))
         {
           if (!using_nonhilbert_norm)
             libmesh_not_implemented();
           using_hilbert_norm = false;
         }
       else
         libmesh_not_implemented();
       const FEType & fe_type = this->get_dof_map().variable_type(var);
       // Allow space for dims 0-3, even if we don't use them all
       std::vector<std::unique_ptr<FEBase>> fe_ptrs(4);
       std::vector<std::unique_ptr<QBase>> q_rules(4);
       const std::set<unsigned char> & elem_dims = _mesh.elem_dimensions();
       // Prepare finite elements for each dimension present in the mesh
       for (const auto & dim : elem_dims)
         {
           if (skip_dimensions && skip_dimensions->find(dim) != skip_dimensions->end())
             continue;
           // Construct quadrature and finite element objects
           q_rules[dim] = fe_type.default_quadrature_rule (dim);
           fe_ptrs[dim] = FEBase::build(dim, fe_type);
           // Attach quadrature rule to FE object
           fe_ptrs[dim]->attach_quadrature_rule (q_rules[dim].get());
         }
       std::vector<dof_id_type> dof_indices;
       // Begin the loop over the elements
       for (const auto & elem : this->get_mesh().active_local_element_ptr_range())
         {
           const unsigned int dim = elem->dim();
 #ifdef LIBMESH_ENABLE_INFINITE_ELEMENTS
           // One way for implementing this would be to exchange the fe with the FEInterface- class.
           // However, it needs to be discussed whether integral-norms make sense for infinite elements.
           // or in which sense they could make sense.
           if (elem->infinite() )
             libmesh_not_implemented();
 #endif
           if (skip_dimensions && skip_dimensions->find(dim) != skip_dimensions->end())
             continue;
           FEBase * fe = fe_ptrs[dim].get();
           QBase * qrule = q_rules[dim].get();
           libmesh_assert(fe);
           libmesh_assert(qrule);
           const std::vector<Real> &               JxW = fe->get_JxW();
           const std::vector<std::vector<Real>> * phi = nullptr;
           if (norm_type == H1 ||
               norm_type == H2 ||
               norm_type == L2 ||
               norm_type == L1 ||
               norm_type == L_INF)
             phi = &(fe->get_phi());
           const std::vector<std::vector<RealGradient>> * dphi = nullptr;
           if (norm_type == H1 ||
               norm_type == H2 ||
               norm_type == H1_SEMINORM ||
               norm_type == W1_INF_SEMINORM)
             dphi = &(fe->get_dphi());
 #ifdef LIBMESH_ENABLE_SECOND_DERIVATIVES
           const std::vector<std::vector<RealTensor>> *   d2phi = nullptr;
           if (norm_type == H2 ||
               norm_type == H2_SEMINORM ||
               norm_type == W2_INF_SEMINORM)
             d2phi = &(fe->get_d2phi());
 #endif
           fe->reinit (elem);
           this->get_dof_map().dof_indices (elem, dof_indices, var);
           const unsigned int n_qp = qrule->n_points();
           const unsigned int n_sf = cast_int<unsigned int>
             (dof_indices.size());
           // Begin the loop over the Quadrature points.
           for (unsigned int qp=0; qp<n_qp; qp++)
             {
               if (norm_type == L1)
                 {
                   Number u_h = 0.;
                   for (unsigned int i=0; i != n_sf; ++i)
                     u_h += (*phi)[i][qp] * (*local_v)(dof_indices[i]);
                   v_norm += norm_weight *
                     JxW[qp] * std::abs(u_h);
                 }
               if (norm_type == L_INF)
                 {
                   Number u_h = 0.;
                   for (unsigned int i=0; i != n_sf; ++i)
                     u_h += (*phi)[i][qp] * (*local_v)(dof_indices[i]);
                   v_norm = std::max(v_norm, norm_weight * std::abs(u_h));
                 }
               if (norm_type == H1 ||
                   norm_type == H2 ||
                   norm_type == L2)
                 {
                   Number u_h = 0.;
                   for (unsigned int i=0; i != n_sf; ++i)
                     u_h += (*phi)[i][qp] * (*local_v)(dof_indices[i]);
                   v_norm += norm_weight_sq *
                     JxW[qp] * TensorTools::norm_sq(u_h);
                 }
               if (norm_type == H1 ||
                   norm_type == H2 ||
                   norm_type == H1_SEMINORM)
                 {
                   Gradient grad_u_h;
                   for (unsigned int i=0; i != n_sf; ++i)
                     grad_u_h.add_scaled((*dphi)[i][qp], (*local_v)(dof_indices[i]));
                   v_norm += norm_weight_sq *
                     JxW[qp] * grad_u_h.norm_sq();
                 }
               if (norm_type == W1_INF_SEMINORM)
                 {
                   Gradient grad_u_h;
                   for (unsigned int i=0; i != n_sf; ++i)
                     grad_u_h.add_scaled((*dphi)[i][qp], (*local_v)(dof_indices[i]));
                   v_norm = std::max(v_norm, norm_weight * grad_u_h.norm());
                 }
 #ifdef LIBMESH_ENABLE_SECOND_DERIVATIVES
               if (norm_type == H2 ||
                   norm_type == H2_SEMINORM)
                 {
                   Tensor hess_u_h;
                   for (unsigned int i=0; i != n_sf; ++i)
                     hess_u_h.add_scaled((*d2phi)[i][qp], (*local_v)(dof_indices[i]));
                   v_norm += norm_weight_sq *
                     JxW[qp] * hess_u_h.norm_sq();
                 }
               if (norm_type == W2_INF_SEMINORM)
                 {
                   Tensor hess_u_h;
                   for (unsigned int i=0; i != n_sf; ++i)
                     hess_u_h.add_scaled((*d2phi)[i][qp], (*local_v)(dof_indices[i]));
                   v_norm = std::max(v_norm, norm_weight * hess_u_h.norm());
                 }
 #endif
             }
         }
     }
   if (using_hilbert_norm)
     {
       this->comm().sum(v_norm);
       v_norm = std::sqrt(v_norm);
     }
   else
     {
       this->comm().max(v_norm);
     }
   return v_norm;
 }
clear()
void libMesh::EigenSystem::clear () override virtual
Clear all the data structures associated with the system.
Reimplemented from libMesh::System.
Reimplemented in libMesh::RBConstructionBase< CondensedEigenSystem >, and libMesh::RBSCMConstruction.
Definition at line 63 of file eigen_system.C.
References libMesh::System::clear(), eigen_solver, matrix_A, and matrix_B.
Referenced by ~EigenSystem().
 {
   // Clear the parent data
   Parent::clear();
   // Clean up the matrices
   matrix_A.reset();
   matrix_B.reset();
   // clear the solver
   eigen_solver->clear();
 }
comm()
const Parallel::Communicator& libMesh::ParallelObject::comm () const inline inherited
Returns
A reference to the Parallel::Communicator object used by this mesh.
Definition at line 89 of file parallel_object.h.
References libMesh::ParallelObject::_communicator.
Referenced by libMesh::__libmesh_petsc_diff_solver_jacobian(), libMesh::__libmesh_petsc_diff_solver_monitor(), libMesh::__libmesh_petsc_diff_solver_residual(), libMesh::__libmesh_tao_equality_constraints(), libMesh::__libmesh_tao_equality_constraints_jacobian(), libMesh::__libmesh_tao_gradient(), libMesh::__libmesh_tao_hessian(), libMesh::__libmesh_tao_inequality_constraints(), libMesh::__libmesh_tao_inequality_constraints_jacobian(), libMesh::__libmesh_tao_objective(), libMesh::MeshRefinement::_coarsen_elements(), libMesh::ExactSolution::_compute_error(), libMesh::UniformRefinementEstimator::_estimate_error(), libMesh::BoundaryInfo::_find_id_maps(), libMesh::SlepcEigenSolver< T >::_petsc_shell_matrix_get_diagonal(), libMesh::PetscLinearSolver< T >::_petsc_shell_matrix_get_diagonal(), libMesh::SlepcEigenSolver< T >::_petsc_shell_matrix_mult(), libMesh::PetscLinearSolver< T >::_petsc_shell_matrix_mult(), libMesh::PetscLinearSolver< T >::_petsc_shell_matrix_mult_add(), libMesh::EquationSystems::_read_impl(), libMesh::MeshRefinement::_refine_elements(), libMesh::MeshRefinement::_smooth_flags(), libMesh::PetscDMWrapper::add_dofs_helper(), libMesh::PetscDMWrapper::add_dofs_to_section(), libMesh::ImplicitSystem::add_matrix(), libMesh::System::add_vector(), libMesh::UnstructuredMesh::all_second_order(), libMesh::MeshTools::Modification::all_tri(), libMesh::LaplaceMeshSmoother::allgather_graph(), libMesh::FEMSystem::assemble_qoi(), libMesh::MeshCommunication::assign_global_indices(), libMesh::DofMap::attach_matrix(), libMesh::MeshTools::Generation::build_extrusion(), libMesh::BoundaryInfo::build_node_list_from_side_list(), libMesh::EquationSystems::build_parallel_elemental_solution_vector(), libMesh::EquationSystems::build_parallel_solution_vector(), libMesh::PetscDMWrapper::build_section(), libMesh::PetscDMWrapper::build_sf(), libMesh::MeshBase::cache_elem_dims(), libMesh::System::calculate_norm(), libMesh::DofMap::check_dirichlet_bcid_consistency(), libMesh::PetscDMWrapper::check_section_n_dofs(), libMesh::Nemesis_IO_Helper::compute_num_global_elem_blocks(), libMesh::Nemesis_IO_Helper::compute_num_global_nodesets(), libMesh::Nemesis_IO_Helper::compute_num_global_sidesets(), libMesh::Problem_Interface::computeF(), libMesh::Problem_Interface::computeJacobian(), libMesh::Problem_Interface::computePreconditioner(), libMesh::ExodusII_IO::copy_elemental_solution(), libMesh::MeshTools::correct_node_proc_ids(), libMesh::MeshTools::create_bounding_box(), libMesh::MeshTools::create_nodal_bounding_box(), libMesh::MeshRefinement::create_parent_error_vector(), libMesh::MeshTools::create_processor_bounding_box(), libMesh::MeshTools::create_subdomain_bounding_box(), libMesh::MeshCommunication::delete_remote_elements(), libMesh::DofMap::distribute_dofs(), DMlibMeshFunction(), DMlibMeshJacobian(), DMlibMeshSetSystem_libMesh(), DMVariableBounds_libMesh(), libMesh::MeshRefinement::eliminate_unrefined_patches(), libMesh::EpetraVector< T >::EpetraVector(), libMesh::WeightedPatchRecoveryErrorEstimator::estimate_error(), libMesh::PatchRecoveryErrorEstimator::estimate_error(), libMesh::JumpErrorEstimator::estimate_error(), libMesh::AdjointRefinementEstimator::estimate_error(), libMesh::ExactErrorEstimator::estimate_error(), libMesh::MeshRefinement::flag_elements_by_elem_fraction(), libMesh::MeshRefinement::flag_elements_by_error_fraction(), libMesh::MeshRefinement::flag_elements_by_nelem_target(), libMesh::CondensedEigenSystem::get_eigenpair(), libMesh::DofMap::get_info(), libMesh::ImplicitSystem::get_linear_solver(), libMesh::LocationMap< T >::init(), libMesh::TimeSolver::init(), libMesh::SystemSubsetBySubdomain::init(), libMesh::PetscDMWrapper::init_and_attach_petscdm(), init_data(), init_matrices(), libMesh::OptimizationSystem::initialize_equality_constraints_storage(), libMesh::OptimizationSystem::initialize_inequality_constraints_storage(), libMesh::MeshTools::libmesh_assert_consistent_distributed(), libMesh::MeshTools::libmesh_assert_consistent_distributed_nodes(), libMesh::MeshTools::libmesh_assert_contiguous_dof_ids(), libMesh::MeshTools::libmesh_assert_parallel_consistent_new_node_procids(), libMesh::MeshTools::libmesh_assert_parallel_consistent_procids< Elem >(), libMesh::MeshTools::libmesh_assert_parallel_consistent_procids< Node >(), libMesh::MeshTools::libmesh_assert_topology_consistent_procids< Node >(), libMesh::MeshTools::libmesh_assert_valid_boundary_ids(), libMesh::MeshTools::libmesh_assert_valid_dof_ids(), libMesh::MeshTools::libmesh_assert_valid_neighbors(), libMesh::DistributedMesh::libmesh_assert_valid_parallel_flags(), libMesh::DistributedMesh::libmesh_assert_valid_parallel_object_ids(), libMesh::DistributedMesh::libmesh_assert_valid_parallel_p_levels(), libMesh::MeshTools::libmesh_assert_valid_refinement_flags(), libMesh::MeshTools::libmesh_assert_valid_unique_ids(), libMesh::libmesh_petsc_snes_fd_residual(), libMesh::libmesh_petsc_snes_jacobian(), libMesh::libmesh_petsc_snes_mffd_residual(), libMesh::libmesh_petsc_snes_postcheck(), libMesh::libmesh_petsc_snes_residual(), libMesh::libmesh_petsc_snes_residual_helper(), libMesh::MeshRefinement::limit_level_mismatch_at_edge(), libMesh::MeshRefinement::limit_level_mismatch_at_node(), libMesh::MeshRefinement::limit_overrefined_boundary(), libMesh::MeshRefinement::limit_underrefined_boundary(), libMesh::MeshRefinement::make_coarsening_compatible(), libMesh::MeshCommunication::make_elems_parallel_consistent(), libMesh::MeshRefinement::make_flags_parallel_consistent(), libMesh::MeshCommunication::make_new_node_proc_ids_parallel_consistent(), libMesh::MeshCommunication::make_new_nodes_parallel_consistent(), libMesh::MeshCommunication::make_node_ids_parallel_consistent(), libMesh::MeshCommunication::make_node_proc_ids_parallel_consistent(), libMesh::MeshCommunication::make_node_unique_ids_parallel_consistent(), libMesh::MeshCommunication::make_nodes_parallel_consistent(), libMesh::MeshCommunication::make_p_levels_parallel_consistent(), libMesh::MeshRefinement::make_refinement_compatible(), libMesh::FEMSystem::mesh_position_set(), libMesh::DistributedMesh::n_active_elem(), libMesh::MeshTools::n_active_levels(), libMesh::BoundaryInfo::n_boundary_conds(), libMesh::BoundaryInfo::n_edge_conds(), libMesh::CondensedEigenSystem::n_global_non_condensed_dofs(), libMesh::MeshTools::n_levels(), libMesh::BoundaryInfo::n_nodeset_conds(), libMesh::MeshTools::n_p_levels(), libMesh::BoundaryInfo::n_shellface_conds(), libMesh::DistributedMesh::parallel_max_elem_id(), libMesh::DistributedMesh::parallel_max_node_id(), libMesh::ReplicatedMesh::parallel_max_unique_id(), libMesh::DistributedMesh::parallel_max_unique_id(), libMesh::DistributedMesh::parallel_n_elem(), libMesh::DistributedMesh::parallel_n_nodes(), libMesh::SparsityPattern::Build::parallel_sync(), libMesh::MeshTools::paranoid_n_levels(), libMesh::petsc_auto_fieldsplit(), libMesh::System::point_gradient(), libMesh::System::point_hessian(), libMesh::System::point_value(), libMesh::MeshBase::prepare_for_use(), libMesh::Nemesis_IO::read(), libMesh::XdrIO::read(), libMesh::CheckpointIO::read_header(), libMesh::XdrIO::read_header(), libMesh::System::read_header(), libMesh::System::read_legacy_data(), libMesh::System::read_SCALAR_dofs(), libMesh::XdrIO::read_serialized_bc_names(), libMesh::XdrIO::read_serialized_bcs_helper(), libMesh::System::read_serialized_blocked_dof_objects(), libMesh::XdrIO::read_serialized_connectivity(), libMesh::XdrIO::read_serialized_nodes(), libMesh::XdrIO::read_serialized_nodesets(), libMesh::XdrIO::read_serialized_subdomain_names(), libMesh::System::read_serialized_vector(), libMesh::MeshBase::recalculate_n_partitions(), libMesh::MeshRefinement::refine_and_coarsen_elements(), libMesh::DistributedMesh::renumber_dof_objects(), libMesh::CheckpointIO::select_split_config(), libMesh::DofMap::set_nonlocal_dof_objects(), libMesh::PetscDMWrapper::set_point_range_in_section(), libMesh::PetscDiffSolver::setup_petsc_data(), libMesh::LaplaceMeshSmoother::smooth(), libMesh::split_mesh(), libMesh::MeshBase::subdomain_ids(), libMesh::BoundaryInfo::sync(), libMesh::MeshRefinement::test_level_one(), libMesh::MeshRefinement::test_unflagged(), libMesh::MeshTools::total_weight(), libMesh::MeshRefinement::uniformly_coarsen(), libMesh::NameBasedIO::write(), libMesh::XdrIO::write(), libMesh::System::write_SCALAR_dofs(), libMesh::XdrIO::write_serialized_bcs_helper(), libMesh::System::write_serialized_blocked_dof_objects(), libMesh::XdrIO::write_serialized_connectivity(), libMesh::XdrIO::write_serialized_nodes(), and libMesh::XdrIO::write_serialized_nodesets().
   { return _communicator; }
compare()
bool libMesh::System::compare (const System & other_system, const Real threshold, const bool verbose) const virtual inherited
Returns
true when the other system contains identical data, up to the given threshold. Outputs some diagnostic info when verbose is set.
Definition at line 514 of file system.C.
References libMesh::System::_is_initialized, libMesh::System::_sys_name, libMesh::System::_vectors, libMesh::System::get_vector(), libMesh::System::n_vectors(), libMesh::System::name(), libMesh::out, and libMesh::System::solution.
Referenced by libMesh::EquationSystems::compare().
 {
   // we do not care for matrices, but for vectors
   libmesh_assert (_is_initialized);
   libmesh_assert (other_system._is_initialized);
   if (verbose)
     {
       libMesh::out << "  Systems \"" << _sys_name << "\"" << std::endl;
       libMesh::out << "   comparing matrices not supported." << std::endl;
       libMesh::out << "   comparing names...";
     }
   // compare the name: 0 means identical
   const int name_result = _sys_name.compare(other_system.name());
   if (verbose)
     {
       if (name_result == 0)
         libMesh::out << " identical." << std::endl;
       else
         libMesh::out << "  names not identical." << std::endl;
       libMesh::out << "   comparing solution vector...";
     }
   // compare the solution: -1 means identical
   const int solu_result = solution->compare (*other_system.solution.get(),
                                              threshold);
   if (verbose)
     {
       if (solu_result == -1)
         libMesh::out << " identical up to threshold." << std::endl;
       else
         libMesh::out << "  first difference occurred at index = "
                      << solu_result << "." << std::endl;
     }
   // safety check, whether we handle at least the same number
   // of vectors
   std::vector<int> ov_result;
   if (this->n_vectors() != other_system.n_vectors())
     {
       if (verbose)
         {
           libMesh::out << "   Fatal difference. This system handles "
                        << this->n_vectors() << " add'l vectors," << std::endl
                        << "   while the other system handles "
                        << other_system.n_vectors()
                        << " add'l vectors." << std::endl
                        << "   Aborting comparison." << std::endl;
         }
       return false;
     }
   else if (this->n_vectors() == 0)
     {
       // there are no additional vectors...
       ov_result.clear ();
     }
   else
     {
       // compare other vectors
       for (auto & pr : _vectors)
         {
           if (verbose)
             libMesh::out << "   comparing vector \""
                          << pr.first << "\" ...";
           // assume they have the same name
           const NumericVector<Number> & other_system_vector =
             other_system.get_vector(pr.first);
           ov_result.push_back(pr.second->compare (other_system_vector,
                                                   threshold));
           if (verbose)
             {
               if (ov_result[ov_result.size()-1] == -1)
                 libMesh::out << " identical up to threshold." << std::endl;
               else
                 libMesh::out << " first difference occurred at" << std::endl
                              << "   index = " << ov_result[ov_result.size()-1] << "." << std::endl;
             }
         }
     } // finished comparing additional vectors
   bool overall_result;
   // sum up the results
   if ((name_result==0) && (solu_result==-1))
     {
       if (ov_result.size()==0)
         overall_result = true;
       else
         {
           bool ov_identical;
           unsigned int n    = 0;
           do
             {
               ov_identical = (ov_result[n]==-1);
               n++;
             }
           while (ov_identical && n<ov_result.size());
           overall_result = ov_identical;
         }
     }
   else
     overall_result = false;
   if (verbose)
     {
       libMesh::out << "   finished comparisons, ";
       if (overall_result)
         libMesh::out << "found no differences." << std::endl << std::endl;
       else
         libMesh::out << "found differences." << std::endl << std::endl;
     }
   return overall_result;
 }
current_solution()
Number libMesh::System::current_solution (const dof_id_type global_dof_number) const inherited
Returns
The current solution for the specified global DOF.
Definition at line 194 of file system.C.
References libMesh::System::_dof_map, and libMesh::System::current_local_solution.
Referenced by libMesh::ExactSolution::_compute_error(), libMesh::UniformRefinementEstimator::_estimate_error(), libMesh::HPCoarsenTest::add_projection(), libMesh::ExactErrorEstimator::estimate_error(), libMesh::WeightedPatchRecoveryErrorEstimator::EstimateError::operator()(), libMesh::PatchRecoveryErrorEstimator::EstimateError::operator()(), libMesh::System::point_gradient(), libMesh::System::point_hessian(), libMesh::System::point_value(), libMesh::HPCoarsenTest::select_refinement(), libMesh::EnsightIO::write_scalar_ascii(), and libMesh::EnsightIO::write_vector_ascii().
 {
   // Check the sizes
   libmesh_assert_less (global_dof_number, _dof_map->n_dofs());
   libmesh_assert_less (global_dof_number, current_local_solution->size());
   return (*current_local_solution)(global_dof_number);
 }
deactivate()
void libMesh::System::deactivate () inline inherited
Deactivates the system. Only active systems are solved.
Definition at line 2081 of file system.h.
References libMesh::System::_active.
 {
   _active = false;
 }
disable_cache()
void libMesh::System::disable_cache () inline virtual inherited
Avoids use of any cached data that might affect any solve result. Should be overridden in derived systems.
Reimplemented in libMesh::ImplicitSystem.
Definition at line 2275 of file system.h.
References libMesh::System::assemble_before_solve.
Referenced by libMesh::UniformRefinementEstimator::_estimate_error().
 { assemble_before_solve = true; }
disable_print_counter_info()
void libMesh::ReferenceCounter::disable_print_counter_info () static inherited
Definition at line 106 of file reference_counter.C.
References libMesh::ReferenceCounter::_enable_print_counter.
Referenced by libMesh::LibMeshInit::LibMeshInit().
 {
   _enable_print_counter = false;
   return;
 }
enable_print_counter_info()
void libMesh::ReferenceCounter::enable_print_counter_info () static inherited
Methods to enable/disable the reference counter output from print_info()
Definition at line 100 of file reference_counter.C.
References libMesh::ReferenceCounter::_enable_print_counter.
 {
   _enable_print_counter = true;
   return;
 }
forward_qoi_parameter_sensitivity()
void libMesh::System::forward_qoi_parameter_sensitivity (const QoISet & qoi_indices, const ParameterVector & parameters, SensitivityData & sensitivities) inline virtual inherited
Solves for parameter sensitivities using the forward method.
This method is only implemented in some derived classes.
Reimplemented in libMesh::ImplicitSystem.
Definition at line 2325 of file system.h.
Referenced by libMesh::System::qoi_parameter_sensitivity().
 {
   libmesh_not_implemented();
 }
generalized()
bool libMesh::EigenSystem::generalized () const inline
Returns
true if the underlying problem is generalized , false otherwise.
Definition at line 149 of file eigen_system.h.
References _is_generalized_eigenproblem.
Referenced by libMesh::CondensedEigenSystem::solve().
 { return _is_generalized_eigenproblem; }
get_adjoint_rhs() [1/2]
NumericVector< Number > & libMesh::System::get_adjoint_rhs (unsigned int i = 0) inherited
Returns
A reference to one of the system's adjoint rhs vectors, by default the one corresponding to the first qoi. This what the user's QoI derivative code should assemble when setting up an adjoint problem
Definition at line 1031 of file system.C.
References libMesh::System::get_vector().
Referenced by libMesh::ImplicitSystem::adjoint_solve(), libMesh::ImplicitSystem::forward_qoi_parameter_sensitivity(), libMesh::ImplicitSystem::qoi_parameter_hessian(), libMesh::ImplicitSystem::qoi_parameter_hessian_vector_product(), and libMesh::ImplicitSystem::weighted_sensitivity_adjoint_solve().
 {
   std::ostringstream adjoint_rhs_name;
   adjoint_rhs_name << "adjoint_rhs" << i;
   return this->get_vector(adjoint_rhs_name.str());
 }
get_adjoint_rhs() [2/2]
const NumericVector< Number > & libMesh::System::get_adjoint_rhs (unsigned int i = 0) const inherited
Returns
A reference to one of the system's adjoint rhs vectors, by default the one corresponding to the first qoi.
Definition at line 1041 of file system.C.
References libMesh::System::get_vector().
 {
   std::ostringstream adjoint_rhs_name;
   adjoint_rhs_name << "adjoint_rhs" << i;
   return this->get_vector(adjoint_rhs_name.str());
 }
get_adjoint_solution() [1/2]
NumericVector< Number > & libMesh::System::get_adjoint_solution (unsigned int i = 0) inherited
Returns
A reference to one of the system's adjoint solution vectors, by default the one corresponding to the first qoi.
Definition at line 969 of file system.C.
References libMesh::System::get_vector().
Referenced by libMesh::UniformRefinementEstimator::_estimate_error(), libMesh::ImplicitSystem::adjoint_solve(), libMesh::AdjointRefinementEstimator::estimate_error(), libMesh::AdjointResidualErrorEstimator::estimate_error(), libMesh::ImplicitSystem::qoi_parameter_hessian(), libMesh::ImplicitSystem::qoi_parameter_hessian_vector_product(), and libMesh::ImplicitSystem::weighted_sensitivity_adjoint_solve().
 {
   std::ostringstream adjoint_name;
   adjoint_name << "adjoint_solution" << i;
   return this->get_vector(adjoint_name.str());
 }
get_adjoint_solution() [2/2]
const NumericVector< Number > & libMesh::System::get_adjoint_solution (unsigned int i = 0) const inherited
Returns
A reference to one of the system's adjoint solution vectors, by default the one corresponding to the first qoi.
Definition at line 979 of file system.C.
References libMesh::System::get_vector().
 {
   std::ostringstream adjoint_name;
   adjoint_name << "adjoint_solution" << i;
   return this->get_vector(adjoint_name.str());
 }
get_all_variable_numbers()
void libMesh::System::get_all_variable_numbers (std::vector< unsigned int > & all_variable_numbers) const inherited
Fills all_variable_numbers with all the variable numbers for the variables that have been added to this system.
Definition at line 1258 of file system.C.
References libMesh::System::_variable_numbers, and libMesh::System::n_vars().
 {
   all_variable_numbers.resize(n_vars());
   // Make sure the variable exists
   std::map<std::string, unsigned short int>::const_iterator
     it = _variable_numbers.begin();
   std::map<std::string, unsigned short int>::const_iterator
     it_end = _variable_numbers.end();
   unsigned int count = 0;
   for ( ; it != it_end; ++it)
     {
       all_variable_numbers[count] = it->second;
       count++;
     }
 }
get_dof_map() [1/2]
const DofMap & libMesh::System::get_dof_map () const inline inherited
Returns
A constant reference to this system's _dof_map.
Definition at line 2049 of file system.h.
References libMesh::System::_dof_map.
Referenced by libMesh::__libmesh_petsc_diff_solver_jacobian(), libMesh::__libmesh_petsc_diff_solver_residual(), libMesh::ExactSolution::_compute_error(), libMesh::UniformRefinementEstimator::_estimate_error(), libMesh::DifferentiableSystem::add_dot_var_dirichlet_bcs(), libMesh::HPCoarsenTest::add_projection(), libMesh::UnsteadySolver::adjoint_advance_timestep(), libMesh::ImplicitSystem::adjoint_solve(), libMesh::NewmarkSolver::advance_timestep(), libMesh::UnsteadySolver::advance_timestep(), libMesh::EquationSystems::allgather(), libMesh::EquationSystems::build_discontinuous_solution_vector(), libMesh::EquationSystems::build_parallel_elemental_solution_vector(), libMesh::EquationSystems::build_parallel_solution_vector(), libMesh::PetscDMWrapper::build_sf(), libMesh::System::calculate_norm(), libMesh::Problem_Interface::computeF(), libMesh::Problem_Interface::computeJacobian(), libMesh::Problem_Interface::computePreconditioner(), DMCreateDomainDecomposition_libMesh(), DMCreateFieldDecomposition_libMesh(), DMlibMeshFunction(), DMlibMeshJacobian(), DMlibMeshSetSystem_libMesh(), libMesh::DofMap::enforce_constraints_exactly(), libMesh::JumpErrorEstimator::estimate_error(), libMesh::AdjointRefinementEstimator::estimate_error(), libMesh::ExactErrorEstimator::estimate_error(), libMesh::System::get_info(), libMesh::SystemSubsetBySubdomain::init(), libMesh::SecondOrderUnsteadySolver::init_data(), libMesh::UnsteadySolver::init_data(), init_matrices(), libMesh::ImplicitSystem::init_matrices(), libMesh::CondensedEigenSystem::initialize_condensed_dofs(), libMesh::OptimizationSystem::initialize_equality_constraints_storage(), libMesh::OptimizationSystem::initialize_inequality_constraints_storage(), libMesh::libmesh_petsc_snes_jacobian(), libMesh::libmesh_petsc_snes_postcheck(), libMesh::libmesh_petsc_snes_residual_helper(), libMesh::System::local_dof_indices(), libMesh::DofMap::max_constraint_error(), libMesh::DGFEMContext::neighbor_side_fe_reinit(), libMesh::UnsteadySolver::old_nonlinear_solution(), libMesh::SecondOrderUnsteadySolver::old_solution_accel(), libMesh::SecondOrderUnsteadySolver::old_solution_rate(), libMesh::WeightedPatchRecoveryErrorEstimator::EstimateError::operator()(), libMesh::PatchRecoveryErrorEstimator::EstimateError::operator()(), libMesh::petsc_auto_fieldsplit(), libMesh::ErrorVector::plot_error(), libMesh::System::point_gradient(), libMesh::System::point_hessian(), libMesh::System::point_value(), libMesh::FEMContext::pre_fe_reinit(), libMesh::System::re_update(), libMesh::System::read_parallel_data(), libMesh::System::read_SCALAR_dofs(), libMesh::SecondOrderUnsteadySolver::reinit(), libMesh::UnsteadySolver::reinit(), reinit(), libMesh::ImplicitSystem::reinit(), libMesh::System::reinit_constraints(), libMesh::EquationSystems::reinit_solutions(), libMesh::UnsteadySolver::retrieve_timestep(), libMesh::HPCoarsenTest::select_refinement(), libMesh::ImplicitSystem::sensitivity_solve(), libMesh::PetscDMWrapper::set_point_range_in_section(), libMesh::NewtonSolver::solve(), libMesh::PetscDiffSolver::solve(), libMesh::ImplicitSystem::weighted_sensitivity_adjoint_solve(), libMesh::ImplicitSystem::weighted_sensitivity_solve(), libMesh::System::write_parallel_data(), libMesh::EnsightIO::write_scalar_ascii(), libMesh::System::write_SCALAR_dofs(), and libMesh::EnsightIO::write_vector_ascii().
 {
   return *_dof_map;
 }
get_dof_map() [2/2]
DofMap & libMesh::System::get_dof_map () inline inherited
Returns
A writable reference to this system's _dof_map.
Definition at line 2057 of file system.h.
References libMesh::System::_dof_map.
 {
   return *_dof_map;
 }
get_eigenpair()
std::pair< Real, Real > libMesh::EigenSystem::get_eigenpair (dof_id_type i) virtual
Returns
Real and imaginary part of the ith eigenvalue and copies the respective eigen vector to the solution vector.
Reimplemented in libMesh::CondensedEigenSystem.
Definition at line 256 of file eigen_system.C.
References eigen_solver, and libMesh::System::solution.
Referenced by libMesh::CondensedEigenSystem::get_eigenpair().
 {
   // call the eigen_solver get_eigenpair method
   return eigen_solver->get_eigenpair (i, *solution);
 }
get_eigenproblem_type()
EigenProblemType libMesh::EigenSystem::get_eigenproblem_type () const inline
Returns
The eigen problem type.
Definition at line 143 of file eigen_system.h.
References _eigen_problem_type.
 {return _eigen_problem_type;}
get_equation_systems() [1/2]
const EquationSystems& libMesh::System::get_equation_systems () const inline inherited
Returns
A constant reference to this system's parent EquationSystems object.
Definition at line 712 of file system.h.
References libMesh::System::_equation_systems.
Referenced by libMesh::UniformRefinementEstimator::_estimate_error(), libMesh::NewmarkSystem::clear(), libMesh::FrequencySystem::clear_all(), libMesh::AdjointRefinementEstimator::estimate_error(), libMesh::AdjointResidualErrorEstimator::estimate_error(), libMesh::ExactErrorEstimator::find_squared_element_error(), libMesh::ImplicitSystem::get_linear_solve_parameters(), libMesh::FrequencySystem::init_data(), libMesh::FrequencySystem::n_frequencies(), libMesh::System::point_value(), libMesh::FrequencySystem::set_current_frequency(), libMesh::FrequencySystem::set_frequencies(), libMesh::FrequencySystem::set_frequencies_by_range(), libMesh::FrequencySystem::set_frequencies_by_steps(), libMesh::NewmarkSystem::set_newmark_parameters(), libMesh::NonlinearImplicitSystem::set_solver_parameters(), libMesh::CondensedEigenSystem::solve(), solve(), libMesh::FrequencySystem::solve(), libMesh::LinearImplicitSystem::solve(), and libMesh::WrappedFunction< Output >::WrappedFunction().
 { return _equation_systems; }
get_equation_systems() [2/2]
EquationSystems& libMesh::System::get_equation_systems () inline inherited
Returns
A reference to this system's parent EquationSystems object.
Definition at line 717 of file system.h.
References libMesh::System::_equation_systems.
 { return _equation_systems; }
get_info() [1/2]
std::string libMesh::ReferenceCounter::get_info () static inherited
Gets a string containing the reference information.
Definition at line 47 of file reference_counter.C.
References libMesh::ReferenceCounter::_counts, and libMesh::Quality::name().
Referenced by libMesh::ReferenceCounter::print_info().
 {
 #if defined(LIBMESH_ENABLE_REFERENCE_COUNTING) && defined(DEBUG)
   std::ostringstream oss;
   oss << '\n'
       << " ---------------------------------------------------------------------------- \n"
       << "| Reference count information                                                |\n"
       << " ---------------------------------------------------------------------------- \n";
   for (const auto & pr : _counts)
     {
       const std::string name(pr.first);
       const unsigned int creations    = pr.second.first;
       const unsigned int destructions = pr.second.second;
       oss << "| " << name << " reference count information:\n"
           << "|  Creations:    " << creations    << '\n'
           << "|  Destructions: " << destructions << '\n';
     }
   oss << " ---------------------------------------------------------------------------- \n";
   return oss.str();
 #else
   return "";
 #endif
 }
get_info() [2/2]
std::string libMesh::System::get_info () const inherited
Returns
A string containing information about the system.
Definition at line 1658 of file system.C.
References libMesh::FEType::family, libMesh::System::get_dof_map(), libMesh::DofMap::get_info(), libMesh::FEType::inf_map, libMesh::System::n_constrained_dofs(), libMesh::System::n_dofs(), libMesh::System::n_local_constrained_dofs(), libMesh::System::n_local_dofs(), libMesh::System::n_matrices(), libMesh::System::n_variable_groups(), libMesh::VariableGroup::n_variables(), libMesh::System::n_vectors(), libMesh::VariableGroup::name(), libMesh::System::name(), libMesh::System::number(), libMesh::FEType::order, libMesh::FEType::radial_family, libMesh::FEType::radial_order, libMesh::System::system_type(), libMesh::Variable::type(), libMesh::DofMap::variable_group(), and libMesh::System::variable_group().
 {
   std::ostringstream oss;
   const std::string & sys_name = this->name();
   oss << "   System #"  << this->number() << ", \"" << sys_name << "\"\n"
       << "    Type \""  << this->system_type() << "\"\n"
       << "    Variables=";
   for (unsigned int vg=0; vg<this->n_variable_groups(); vg++)
     {
       const VariableGroup & vg_description (this->variable_group(vg));
       if (vg_description.n_variables() > 1) oss << "{ ";
       for (unsigned int vn=0; vn<vg_description.n_variables(); vn++)
         oss << "\"" << vg_description.name(vn) << "\" ";
       if (vg_description.n_variables() > 1) oss << "} ";
     }
   oss << '\n';
   oss << "    Finite Element Types=";
 #ifndef LIBMESH_ENABLE_INFINITE_ELEMENTS
   for (unsigned int vg=0; vg<this->n_variable_groups(); vg++)
     oss << "\""
         << Utility::enum_to_string<FEFamily>(this->get_dof_map().variable_group(vg).type().family)
         << "\" ";
 #else
   for (unsigned int vg=0; vg<this->n_variable_groups(); vg++)
     {
       oss << "\""
           << Utility::enum_to_string<FEFamily>(this->get_dof_map().variable_group(vg).type().family)
           << "\", \""
           << Utility::enum_to_string<FEFamily>(this->get_dof_map().variable_group(vg).type().radial_family)
           << "\" ";
     }
   oss << '\n' << "    Infinite Element Mapping=";
   for (unsigned int vg=0; vg<this->n_variable_groups(); vg++)
     oss << "\""
         << Utility::enum_to_string<InfMapType>(this->get_dof_map().variable_group(vg).type().inf_map)
         << "\" ";
 #endif
   oss << '\n';
   oss << "    Approximation Orders=";
   for (unsigned int vg=0; vg<this->n_variable_groups(); vg++)
     {
 #ifndef LIBMESH_ENABLE_INFINITE_ELEMENTS
       oss << "\""
           << Utility::enum_to_string<Order>(this->get_dof_map().variable_group(vg).type().order)
           << "\" ";
 #else
       oss << "\""
           << Utility::enum_to_string<Order>(this->get_dof_map().variable_group(vg).type().order)
           << "\", \""
           << Utility::enum_to_string<Order>(this->get_dof_map().variable_group(vg).type().radial_order)
           << "\" ";
 #endif
     }
   oss << '\n';
   oss << "    n_dofs()="             << this->n_dofs()             << '\n';
   oss << "    n_local_dofs()="       << this->n_local_dofs()       << '\n';
 #ifdef LIBMESH_ENABLE_CONSTRAINTS
   oss << "    n_constrained_dofs()=" << this->n_constrained_dofs() << '\n';
   oss << "    n_local_constrained_dofs()=" << this->n_local_constrained_dofs() << '\n';
 #endif
   oss << "    " << "n_vectors()="  << this->n_vectors()  << '\n';
   oss << "    " << "n_matrices()="  << this->n_matrices()  << '\n';
   //   oss << "    " << "n_additional_matrices()=" << this->n_additional_matrices() << '\n';
   oss << this->get_dof_map().get_info();
   return oss.str();
 }
get_mesh() [1/2]
const MeshBase & libMesh::System::get_mesh () const inline inherited
Returns
A constant reference to this systems's _mesh.
Definition at line 2033 of file system.h.
References libMesh::System::_mesh.
Referenced by libMesh::ExactSolution::_compute_error(), libMesh::PetscDMWrapper::add_dofs_to_section(), libMesh::HPCoarsenTest::add_projection(), libMesh::FEMSystem::assemble_qoi(), libMesh::FEMSystem::assemble_qoi_derivative(), libMesh::FEMSystem::assembly(), libMesh::System::calculate_norm(), DMCreateDomainDecomposition_libMesh(), DMCreateFieldDecomposition_libMesh(), DMlibMeshSetSystem_libMesh(), libMesh::WeightedPatchRecoveryErrorEstimator::estimate_error(), libMesh::PatchRecoveryErrorEstimator::estimate_error(), libMesh::JumpErrorEstimator::estimate_error(), libMesh::AdjointResidualErrorEstimator::estimate_error(), libMesh::ExactErrorEstimator::estimate_error(), libMesh::SystemSubsetBySubdomain::init(), libMesh::System::init_data(), init_matrices(), libMesh::ImplicitSystem::init_matrices(), libMesh::System::local_dof_indices(), libMesh::DofMap::max_constraint_error(), libMesh::FEMSystem::mesh_position_get(), libMesh::FEMSystem::mesh_position_set(), libMesh::WeightedPatchRecoveryErrorEstimator::EstimateError::operator()(), libMesh::PatchRecoveryErrorEstimator::EstimateError::operator()(), libMesh::petsc_auto_fieldsplit(), libMesh::System::point_gradient(), libMesh::System::point_hessian(), libMesh::System::point_value(), libMesh::FEMSystem::postprocess(), libMesh::System::read_header(), libMesh::System::read_legacy_data(), libMesh::System::read_parallel_data(), libMesh::System::read_serialized_vector(), libMesh::System::read_serialized_vectors(), reinit(), libMesh::ImplicitSystem::reinit(), libMesh::HPSingularity::select_refinement(), libMesh::HPCoarsenTest::select_refinement(), libMesh::PetscDMWrapper::set_point_range_in_section(), libMesh::System::write_header(), libMesh::System::write_parallel_data(), libMesh::System::write_serialized_vector(), libMesh::System::write_serialized_vectors(), and libMesh::System::zero_variable().
 {
   return _mesh;
 }
get_mesh() [2/2]
MeshBase & libMesh::System::get_mesh () inline inherited
Returns
A reference to this systems's _mesh.
Definition at line 2041 of file system.h.
References libMesh::System::_mesh.
 {
   return _mesh;
 }
get_n_converged()
unsigned int libMesh::EigenSystem::get_n_converged () const inline
Returns
The number of converged eigenpairs.
Definition at line 128 of file eigen_system.h.
References _n_converged_eigenpairs.
 {return _n_converged_eigenpairs;}
get_n_iterations()
unsigned int libMesh::EigenSystem::get_n_iterations () const inline
Returns
The number of eigen solver iterations.
Definition at line 133 of file eigen_system.h.
References _n_iterations.
 {return _n_iterations;}
get_sensitivity_rhs() [1/2]
NumericVector< Number > & libMesh::System::get_sensitivity_rhs (unsigned int i = 0) inherited
Returns
A reference to one of the system's sensitivity rhs vectors, by default the one corresponding to the first parameter. By default these vectors are built by the library, using finite differences, when assemble_residual_derivatives() is called.
When assembled, this vector should hold -(partial R / partial p_i)
Definition at line 1061 of file system.C.
References libMesh::System::get_vector().
Referenced by libMesh::ImplicitSystem::adjoint_qoi_parameter_sensitivity(), and libMesh::ImplicitSystem::sensitivity_solve().
 {
   std::ostringstream sensitivity_rhs_name;
   sensitivity_rhs_name << "sensitivity_rhs" << i;
   return this->get_vector(sensitivity_rhs_name.str());
 }
get_sensitivity_rhs() [2/2]
const NumericVector< Number > & libMesh::System::get_sensitivity_rhs (unsigned int i = 0) const inherited
Returns
A reference to one of the system's sensitivity rhs vectors, by default the one corresponding to the first parameter.
Definition at line 1071 of file system.C.
References libMesh::System::get_vector().
 {
   std::ostringstream sensitivity_rhs_name;
   sensitivity_rhs_name << "sensitivity_rhs" << i;
   return this->get_vector(sensitivity_rhs_name.str());
 }
get_sensitivity_solution() [1/2]
NumericVector< Number > & libMesh::System::get_sensitivity_solution (unsigned int i = 0) inherited
Returns
A reference to one of the system's solution sensitivity vectors, by default the one corresponding to the first parameter.
Definition at line 916 of file system.C.
References libMesh::System::get_vector().
Referenced by libMesh::ImplicitSystem::forward_qoi_parameter_sensitivity(), libMesh::ImplicitSystem::qoi_parameter_hessian(), and libMesh::ImplicitSystem::sensitivity_solve().
 {
   std::ostringstream sensitivity_name;
   sensitivity_name << "sensitivity_solution" << i;
   return this->get_vector(sensitivity_name.str());
 }
get_sensitivity_solution() [2/2]
const NumericVector< Number > & libMesh::System::get_sensitivity_solution (unsigned int i = 0) const inherited
Returns
A reference to one of the system's solution sensitivity vectors, by default the one corresponding to the first parameter.
Definition at line 926 of file system.C.
References libMesh::System::get_vector().
 {
   std::ostringstream sensitivity_name;
   sensitivity_name << "sensitivity_solution" << i;
   return this->get_vector(sensitivity_name.str());
 }
get_vector() [1/4]
const NumericVector< Number > & libMesh::System::get_vector (const std::string & vec_name) const inherited
Returns
A const reference to this system's additional vector named vec_name. Access is only granted when the vector is already properly initialized.
Definition at line 774 of file system.C.
References libMesh::System::_vectors.
Referenced by libMesh::UniformRefinementEstimator::_estimate_error(), libMesh::UnsteadySolver::adjoint_advance_timestep(), libMesh::NewmarkSolver::advance_timestep(), libMesh::AdaptiveTimeSolver::advance_timestep(), libMesh::UnsteadySolver::advance_timestep(), libMesh::System::compare(), libMesh::NewmarkSolver::compute_initial_accel(), libMesh::UnsteadySolver::du(), libMesh::AdjointRefinementEstimator::estimate_error(), libMesh::System::get_adjoint_rhs(), libMesh::System::get_adjoint_solution(), libMesh::System::get_sensitivity_rhs(), libMesh::System::get_sensitivity_solution(), libMesh::System::get_weighted_sensitivity_adjoint_solution(), libMesh::System::get_weighted_sensitivity_solution(), libMesh::NewmarkSystem::initial_conditions(), libMesh::NewmarkSolver::project_initial_accel(), libMesh::SecondOrderUnsteadySolver::project_initial_rate(), libMesh::SecondOrderUnsteadySolver::reinit(), libMesh::UnsteadySolver::reinit(), libMesh::MemorySolutionHistory::retrieve(), libMesh::UnsteadySolver::retrieve_timestep(), libMesh::TwostepTimeSolver::solve(), libMesh::FrequencySystem::solve(), libMesh::NewmarkSystem::update_rhs(), and libMesh::NewmarkSystem::update_u_v_a().
 {
   // Make sure the vector exists
   const_vectors_iterator pos = _vectors.find(vec_name);
   if (pos == _vectors.end())
     libmesh_error_msg("ERROR: vector " << vec_name << " does not exist in this system!");
   return *(pos->second);
 }
get_vector() [2/4]
NumericVector< Number > & libMesh::System::get_vector (const std::string & vec_name) inherited
Returns
A writable reference to this system's additional vector named vec_name. Access is only granted when the vector is already properly initialized.
Definition at line 787 of file system.C.
References libMesh::System::_vectors.
 {
   // Make sure the vector exists
   vectors_iterator pos = _vectors.find(vec_name);
   if (pos == _vectors.end())
     libmesh_error_msg("ERROR: vector " << vec_name << " does not exist in this system!");
   return *(pos->second);
 }
get_vector() [3/4]
const NumericVector< Number > & libMesh::System::get_vector (const unsigned int vec_num) const inherited
Returns
A const reference to this system's additional vector number vec_num (where the vectors are counted starting with 0).
Definition at line 800 of file system.C.
References libMesh::System::vectors_begin(), and libMesh::System::vectors_end().
 {
   const_vectors_iterator v = vectors_begin();
   const_vectors_iterator v_end = vectors_end();
   unsigned int num = 0;
   while ((num<vec_num) && (v!=v_end))
     {
       num++;
       ++v;
     }
   libmesh_assert (v != v_end);
   return *(v->second);
 }
get_vector() [4/4]
NumericVector< Number > & libMesh::System::get_vector (const unsigned int vec_num) inherited
Returns
A writable reference to this system's additional vector number vec_num (where the vectors are counted starting with 0).
Definition at line 816 of file system.C.
References libMesh::System::vectors_begin(), and libMesh::System::vectors_end().
 {
   vectors_iterator v = vectors_begin();
   vectors_iterator v_end = vectors_end();
   unsigned int num = 0;
   while ((num<vec_num) && (v!=v_end))
     {
       num++;
       ++v;
     }
   libmesh_assert (v != v_end);
   return *(v->second);
 }
get_weighted_sensitivity_adjoint_solution() [1/2]
NumericVector< Number > & libMesh::System::get_weighted_sensitivity_adjoint_solution (unsigned int i = 0) inherited
Returns
A reference to one of the system's weighted sensitivity adjoint solution vectors, by default the one corresponding to the first qoi.
Definition at line 1001 of file system.C.
References libMesh::System::get_vector().
Referenced by libMesh::ImplicitSystem::qoi_parameter_hessian_vector_product(), and libMesh::ImplicitSystem::weighted_sensitivity_adjoint_solve().
 {
   std::ostringstream adjoint_name;
   adjoint_name << "weighted_sensitivity_adjoint_solution" << i;
   return this->get_vector(adjoint_name.str());
 }
get_weighted_sensitivity_adjoint_solution() [2/2]
const NumericVector< Number > & libMesh::System::get_weighted_sensitivity_adjoint_solution (unsigned int i = 0) const inherited
Returns
A reference to one of the system's weighted sensitivity adjoint solution vectors, by default the one corresponding to the first qoi.
Definition at line 1011 of file system.C.
References libMesh::System::get_vector().
 {
   std::ostringstream adjoint_name;
   adjoint_name << "weighted_sensitivity_adjoint_solution" << i;
   return this->get_vector(adjoint_name.str());
 }
get_weighted_sensitivity_solution() [1/2]
NumericVector< Number > & libMesh::System::get_weighted_sensitivity_solution () inherited
Returns
A reference to the solution of the last weighted sensitivity solve
Definition at line 943 of file system.C.
References libMesh::System::get_vector().
Referenced by libMesh::ImplicitSystem::qoi_parameter_hessian_vector_product(), and libMesh::ImplicitSystem::weighted_sensitivity_solve().
 {
   return this->get_vector("weighted_sensitivity_solution");
 }
get_weighted_sensitivity_solution() [2/2]
const NumericVector< Number > & libMesh::System::get_weighted_sensitivity_solution () const inherited
Returns
A reference to the solution of the last weighted sensitivity solve
Definition at line 950 of file system.C.
References libMesh::System::get_vector().
 {
   return this->get_vector("weighted_sensitivity_solution");
 }
has_variable()
bool libMesh::System::has_variable (const std::string & var) const inherited
Returns
true if a variable named var exists in this System
Definition at line 1236 of file system.C.
References libMesh::System::_variable_numbers.
Referenced by libMesh::GMVIO::copy_nodal_solution().
 {
   return _variable_numbers.count(var);
 }
have_vector()
bool libMesh::System::have_vector (const std::string & vec_name) const inline inherited
Returns
true if this System has a vector associated with the given name, false otherwise.
Definition at line 2225 of file system.h.
References libMesh::System::_vectors.
Referenced by libMesh::System::add_vector().
 {
   return (_vectors.count(vec_name));
 }
hide_output()
bool& libMesh::System::hide_output () inline inherited
Returns
A writable reference to a boolean that determines if this system can be written to file or not. If set to true, then EquationSystems::write will ignore this system.
Definition at line 1662 of file system.h.
References libMesh::System::_hide_output.
 { return _hide_output; }
identify_variable_groups() [1/2]
bool libMesh::System::identify_variable_groups () const inline inherited
Returns
true when VariableGroup structures should be automatically identified, false otherwise.
Definition at line 2201 of file system.h.
References libMesh::System::_identify_variable_groups.
Referenced by libMesh::System::add_variable().
 {
   return _identify_variable_groups;
 }
identify_variable_groups() [2/2]
void libMesh::System::identify_variable_groups (const bool ivg) inline inherited
Toggle automatic VariableGroup identification.
Definition at line 2209 of file system.h.
References libMesh::System::_identify_variable_groups.
 {
   _identify_variable_groups = ivg;
 }
increment_constructor_count()
void libMesh::ReferenceCounter::increment_constructor_count (const std::string & name) inline protected inherited
Increments the construction counter. Should be called in the constructor of any derived class that will be reference counted.
Definition at line 181 of file reference_counter.h.
References libMesh::ReferenceCounter::_counts, libMesh::Quality::name(), and libMesh::Threads::spin_mtx.
Referenced by libMesh::ReferenceCountedObject< RBParametrized >::ReferenceCountedObject().
 {
   Threads::spin_mutex::scoped_lock lock(Threads::spin_mtx);
   std::pair<unsigned int, unsigned int> & p = _counts[name];
   p.first++;
 }
increment_destructor_count()
void libMesh::ReferenceCounter::increment_destructor_count (const std::string & name) inline protected inherited
Increments the destruction counter. Should be called in the destructor of any derived class that will be reference counted.
Definition at line 194 of file reference_counter.h.
References libMesh::ReferenceCounter::_counts, libMesh::Quality::name(), and libMesh::Threads::spin_mtx.
Referenced by libMesh::ReferenceCountedObject< RBParametrized >::~ReferenceCountedObject().
 {
   Threads::spin_mutex::scoped_lock lock(Threads::spin_mtx);
   std::pair<unsigned int, unsigned int> & p = _counts[name];
   p.second++;
 }
init()
void libMesh::System::init () inherited
Initializes degrees of freedom on the current mesh. Sets the
Definition at line 237 of file system.C.
References libMesh::System::_basic_system_only, libMesh::System::init_data(), libMesh::System::is_initialized(), libMesh::System::n_vars(), and libMesh::System::user_initialization().
 {
   // Calling init() twice on the same system currently works evil
   // magic, whether done directly or via EquationSystems::read()
   libmesh_assert(!this->is_initialized());
   // First initialize any required data:
   // either only the basic System data
   if (_basic_system_only)
     System::init_data();
   // or all the derived class' data too
   else
     this->init_data();
   // If no variables have been added to this system
   // don't do anything
   if (!this->n_vars())
     return;
   // Then call the user-provided initialization function
   this->user_initialization();
 }
init_data()
void libMesh::EigenSystem::init_data () override protected virtual
Initializes the member data fields associated with the system, so that, e.g., assemble() may be used.
Reimplemented from libMesh::System.
Reimplemented in libMesh::RBConstructionBase< CondensedEigenSystem >.
Definition at line 116 of file eigen_system.C.
References _eigen_problem_type, _is_generalized_eigenproblem, libMesh::SparseMatrix< T >::build(), libMesh::ParallelObject::comm(), libMesh::GHEP, libMesh::GHIEP, libMesh::GNHEP, libMesh::System::init_data(), init_matrices(), and matrix_A.
 {
   // initialize parent data
   Parent::init_data();
   // define the type of eigenproblem
   if (_eigen_problem_type == GNHEP ||
       _eigen_problem_type == GHEP  ||
       _eigen_problem_type == GHIEP)
     _is_generalized_eigenproblem = true;
   // build the system matrix
   matrix_A = SparseMatrix<Number>::build(this->comm());
   this->init_matrices();
 }
init_matrices()
void libMesh::EigenSystem::init_matrices () protected virtual
Initializes the matrices associated with the system
Definition at line 135 of file eigen_system.C.
References _is_generalized_eigenproblem, libMesh::DofMap::attach_matrix(), libMesh::SparseMatrix< T >::build(), libMesh::ParallelObject::comm(), libMesh::DofMap::compute_sparsity(), libMesh::System::get_dof_map(), libMesh::System::get_mesh(), matrix_A, and matrix_B.
Referenced by init_data().
 {
   DofMap & dof_map = this->get_dof_map();
   dof_map.attach_matrix(*matrix_A);
   // build matrix_B only in case of a
   // generalized problem
   if (_is_generalized_eigenproblem)
     {
       matrix_B = SparseMatrix<Number>::build(this->comm());
       dof_map.attach_matrix(*matrix_B);
     }
   dof_map.compute_sparsity(this->get_mesh());
   // initialize and zero system matrix
   matrix_A->init();
   matrix_A->zero();
   // eventually initialize and zero system matrix_B
   if (_is_generalized_eigenproblem)
     {
       matrix_B->init();
       matrix_B->zero();
     }
 }
is_adjoint_already_solved()
bool libMesh::System::is_adjoint_already_solved () const inline inherited
Accessor for the adjoint_already_solved boolean
Definition at line 388 of file system.h.
References libMesh::System::adjoint_already_solved.
Referenced by libMesh::ImplicitSystem::adjoint_qoi_parameter_sensitivity(), libMesh::AdjointRefinementEstimator::estimate_error(), libMesh::AdjointResidualErrorEstimator::estimate_error(), libMesh::ImplicitSystem::qoi_parameter_hessian(), and libMesh::ImplicitSystem::qoi_parameter_hessian_vector_product().
   { return adjoint_already_solved;}
is_initialized()
bool libMesh::System::is_initialized () inline inherited
Returns
true iff this system has been initialized.
Definition at line 2089 of file system.h.
References libMesh::System::_is_initialized.
Referenced by libMesh::System::add_variable(), libMesh::System::add_variables(), and libMesh::System::init().
 {
   return _is_initialized;
 }
local_dof_indices()
void libMesh::System::local_dof_indices (const unsigned int var, std::set< dof_id_type > & var_indices) const inherited
Fills the std::set with the degrees of freedom on the local processor corresponding the the variable number passed in.
Definition at line 1277 of file system.C.
References libMesh::DofMap::dof_indices(), libMesh::DofMap::end_dof(), libMesh::DofMap::first_dof(), libMesh::System::get_dof_map(), and libMesh::System::get_mesh().
Referenced by libMesh::System::discrete_var_norm().
 {
   // Make sure the set is clear
   var_indices.clear();
   std::vector<dof_id_type> dof_indices;
   const dof_id_type
     first_local = this->get_dof_map().first_dof(),
     end_local   = this->get_dof_map().end_dof();
   // Begin the loop over the elements
   for (const auto & elem : this->get_mesh().active_local_element_ptr_range())
     {
       this->get_dof_map().dof_indices (elem, dof_indices, var);
       for (std::size_t i=0; i<dof_indices.size(); i++)
         {
           dof_id_type dof = dof_indices[i];
           //If the dof is owned by the local processor
           if (first_local <= dof && dof < end_local)
             var_indices.insert(dof_indices[i]);
         }
     }
   // we may have missed assigning DOFs to nodes that we own
   // but to which we have no connected elements matching our
   // variable restriction criterion.  this will happen, for example,
   // if variable V is restricted to subdomain S.  We may not own
   // any elements which live in S, but we may own nodes which are
   // *connected* to elements which do.
   for (const auto & node : this->get_mesh().local_node_ptr_range())
     {
       libmesh_assert(node);
       this->get_dof_map().dof_indices (node, dof_indices, var);
       for (auto dof : dof_indices)
         if (first_local <= dof && dof < end_local)
           var_indices.insert(dof);
     }
 }
n_active_dofs()
dof_id_type libMesh::System::n_active_dofs () const inline inherited
Returns
The number of active degrees of freedom for this System.
Definition at line 2217 of file system.h.
References libMesh::System::n_constrained_dofs(), and libMesh::System::n_dofs().
 {
   return this->n_dofs() - this->n_constrained_dofs();
 }
n_components()
unsigned int libMesh::System::n_components () const inline inherited
Returns
The total number of scalar components in the system's variables. This will equal n_vars() in the case of all scalar-valued variables.
Definition at line 2121 of file system.h.
References libMesh::System::_variables, libMesh::Variable::first_scalar_number(), and libMesh::Variable::n_components().
Referenced by libMesh::System::add_variables().
 {
   if (_variables.empty())
     return 0;
   const Variable & last = _variables.back();
   return last.first_scalar_number() + last.n_components();
 }
n_constrained_dofs()
dof_id_type libMesh::System::n_constrained_dofs () const inherited
Returns
The total number of constrained degrees of freedom in the system.
Definition at line 157 of file system.C.
References libMesh::System::_dof_map.
Referenced by libMesh::System::get_info(), and libMesh::System::n_active_dofs().
 {
 #ifdef LIBMESH_ENABLE_CONSTRAINTS
   return _dof_map->n_constrained_dofs();
 #else
   return 0;
 #endif
 }
n_dofs()
dof_id_type libMesh::System::n_dofs () const inherited
Returns
The number of degrees of freedom in the system
Definition at line 150 of file system.C.
References libMesh::System::_dof_map.
Referenced by libMesh::System::add_vector(), libMesh::AdjointRefinementEstimator::estimate_error(), libMesh::System::get_info(), libMesh::SecondOrderUnsteadySolver::init_data(), libMesh::UnsteadySolver::init_data(), libMesh::System::init_data(), libMesh::OptimizationSystem::initialize_equality_constraints_storage(), libMesh::OptimizationSystem::initialize_inequality_constraints_storage(), libMesh::System::n_active_dofs(), libMesh::CondensedEigenSystem::n_global_non_condensed_dofs(), libMesh::FEMSystem::numerical_jacobian(), libMesh::System::read_legacy_data(), libMesh::SecondOrderUnsteadySolver::reinit(), libMesh::UnsteadySolver::reinit(), and libMesh::System::restrict_vectors().
 {
   return _dof_map->n_dofs();
 }
n_local_constrained_dofs()
dof_id_type libMesh::System::n_local_constrained_dofs () const inherited
Returns
The number of constrained degrees of freedom on this processor.
Definition at line 172 of file system.C.
References libMesh::System::_dof_map.
Referenced by libMesh::System::get_info().
 {
 #ifdef LIBMESH_ENABLE_CONSTRAINTS
   return _dof_map->n_local_constrained_dofs();
 #else
   return 0;
 #endif
 }
n_local_dofs()
dof_id_type libMesh::System::n_local_dofs () const inherited
Returns
The number of degrees of freedom local to this processor
Definition at line 187 of file system.C.
References libMesh::System::_dof_map, and libMesh::ParallelObject::processor_id().
Referenced by libMesh::System::add_vector(), libMesh::PetscDMWrapper::build_section(), libMesh::AdjointRefinementEstimator::estimate_error(), libMesh::System::get_info(), libMesh::SecondOrderUnsteadySolver::init_data(), libMesh::UnsteadySolver::init_data(), libMesh::System::init_data(), libMesh::OptimizationSystem::initialize_equality_constraints_storage(), libMesh::OptimizationSystem::initialize_inequality_constraints_storage(), libMesh::SecondOrderUnsteadySolver::reinit(), libMesh::UnsteadySolver::reinit(), and libMesh::System::restrict_vectors().
 {
   return _dof_map->n_dofs_on_processor (this->processor_id());
 }
n_matrices()
unsigned int libMesh::EigenSystem::n_matrices () const inline override virtual
Returns
The number of matrices handled by this system
Reimplemented from libMesh::System.
Definition at line 226 of file eigen_system.h.
References _is_generalized_eigenproblem.
 {
   if (_is_generalized_eigenproblem)
     return 2;
   return 1;
 }
n_objects()
static unsigned int libMesh::ReferenceCounter::n_objects () inline static inherited
Prints the number of outstanding (created, but not yet destroyed) objects.
Definition at line 83 of file reference_counter.h.
References libMesh::ReferenceCounter::_n_objects.
   { return _n_objects; }
n_processors()
processor_id_type libMesh::ParallelObject::n_processors () const inline inherited
Returns
The number of processors in the group.
Definition at line 95 of file parallel_object.h.
References libMesh::ParallelObject::_communicator, and libMesh::Parallel::Communicator::size().
Referenced by libMesh::BoundaryInfo::_find_id_maps(), libMesh::PetscDMWrapper::add_dofs_to_section(), libMesh::DistributedMesh::add_elem(), libMesh::DistributedMesh::add_node(), libMesh::LaplaceMeshSmoother::allgather_graph(), libMesh::FEMSystem::assembly(), libMesh::AztecLinearSolver< T >::AztecLinearSolver(), libMesh::BoundaryInfo::build_node_list_from_side_list(), libMesh::EquationSystems::build_parallel_elemental_solution_vector(), libMesh::DistributedMesh::clear(), libMesh::Nemesis_IO_Helper::compute_border_node_ids(), libMesh::Nemesis_IO_Helper::construct_nemesis_filename(), libMesh::UnstructuredMesh::create_pid_mesh(), libMesh::MeshTools::create_processor_bounding_box(), libMesh::DofMap::distribute_dofs(), libMesh::DofMap::distribute_local_dofs_node_major(), libMesh::DofMap::distribute_local_dofs_var_major(), libMesh::EnsightIO::EnsightIO(), libMesh::MeshBase::get_info(), libMesh::SystemSubsetBySubdomain::init(), libMesh::PetscDMWrapper::init_and_attach_petscdm(), libMesh::Nemesis_IO_Helper::initialize(), libMesh::DistributedMesh::insert_elem(), libMesh::MeshTools::libmesh_assert_contiguous_dof_ids(), libMesh::MeshTools::libmesh_assert_parallel_consistent_new_node_procids(), libMesh::MeshTools::libmesh_assert_parallel_consistent_procids< Elem >(), libMesh::MeshTools::libmesh_assert_parallel_consistent_procids< Node >(), libMesh::MeshTools::libmesh_assert_topology_consistent_procids< Node >(), libMesh::MeshTools::libmesh_assert_valid_boundary_ids(), libMesh::MeshTools::libmesh_assert_valid_dof_ids(), libMesh::MeshTools::libmesh_assert_valid_neighbors(), libMesh::MeshTools::libmesh_assert_valid_refinement_flags(), libMesh::DofMap::local_variable_indices(), libMesh::MeshRefinement::make_coarsening_compatible(), libMesh::MeshBase::n_active_elem_on_proc(), libMesh::MeshBase::n_elem_on_proc(), libMesh::MeshBase::n_nodes_on_proc(), libMesh::MeshBase::partition(), libMesh::PetscLinearSolver< T >::PetscLinearSolver(), libMesh::System::point_gradient(), libMesh::System::point_hessian(), libMesh::System::point_value(), libMesh::NameBasedIO::read(), libMesh::Nemesis_IO::read(), libMesh::CheckpointIO::read(), libMesh::CheckpointIO::read_connectivity(), libMesh::XdrIO::read_header(), libMesh::CheckpointIO::read_nodes(), libMesh::System::read_parallel_data(), libMesh::System::read_SCALAR_dofs(), libMesh::System::read_serialized_blocked_dof_objects(), libMesh::System::read_serialized_vector(), libMesh::DistributedMesh::renumber_dof_objects(), libMesh::DofMap::set_nonlocal_dof_objects(), libMesh::PetscDMWrapper::set_point_range_in_section(), libMesh::MeshRefinement::uniformly_coarsen(), libMesh::DistributedMesh::update_parallel_id_counts(), libMesh::GMVIO::write_binary(), libMesh::GMVIO::write_discontinuous_gmv(), libMesh::System::write_parallel_data(), libMesh::System::write_SCALAR_dofs(), libMesh::XdrIO::write_serialized_bcs_helper(), libMesh::System::write_serialized_blocked_dof_objects(), libMesh::XdrIO::write_serialized_connectivity(), libMesh::XdrIO::write_serialized_nodes(), and libMesh::XdrIO::write_serialized_nodesets().
   { return cast_int<processor_id_type>(_communicator.size()); }
n_qois()
unsigned int libMesh::System::n_qois () const inline inherited
Number of currently active quantities of interest.
Definition at line 2278 of file system.h.
References libMesh::System::qoi.
Referenced by libMesh::UniformRefinementEstimator::_estimate_error(), libMesh::ImplicitSystem::adjoint_qoi_parameter_sensitivity(), libMesh::ImplicitSystem::adjoint_solve(), libMesh::SensitivityData::allocate_data(), libMesh::SensitivityData::allocate_hessian_data(), libMesh::ExplicitSystem::assemble_qoi(), libMesh::FEMSystem::assemble_qoi(), libMesh::ExplicitSystem::assemble_qoi_derivative(), libMesh::FEMSystem::assemble_qoi_derivative(), libMesh::AdjointRefinementEstimator::estimate_error(), libMesh::AdjointResidualErrorEstimator::estimate_error(), libMesh::ImplicitSystem::forward_qoi_parameter_sensitivity(), libMesh::FEMContext::pre_fe_reinit(), libMesh::ImplicitSystem::qoi_parameter_hessian(), libMesh::ImplicitSystem::qoi_parameter_hessian_vector_product(), libMesh::QoISet::size(), and libMesh::ImplicitSystem::weighted_sensitivity_adjoint_solve().
 {
   return cast_int<unsigned int>(this->qoi.size());
 }
n_variable_groups()
unsigned int libMesh::System::n_variable_groups () const inline inherited
Returns
The number of VariableGroup variable groups in the system
Definition at line 2113 of file system.h.
References libMesh::System::_variable_groups.
Referenced by libMesh::System::add_variable(), libMesh::FEMSystem::assembly(), libMesh::System::get_info(), and libMesh::System::init_data().
 {
   return cast_int<unsigned int>(_variable_groups.size());
 }
n_vars()
unsigned int libMesh::System::n_vars () const inline inherited
Returns
The number of variables in the system
Definition at line 2105 of file system.h.
References libMesh::System::_variables.
Referenced by libMesh::UniformRefinementEstimator::_estimate_error(), libMesh::PetscDMWrapper::add_dofs_helper(), libMesh::DiffContext::add_localized_vector(), libMesh::System::add_variable(), libMesh::System::add_variables(), libMesh::EquationSystems::build_discontinuous_solution_vector(), libMesh::EquationSystems::build_parallel_elemental_solution_vector(), libMesh::EquationSystems::build_parallel_solution_vector(), libMesh::PetscDMWrapper::build_section(), libMesh::System::calculate_norm(), libMesh::DGFEMContext::DGFEMContext(), libMesh::DiffContext::DiffContext(), libMesh::JumpErrorEstimator::estimate_error(), libMesh::AdjointResidualErrorEstimator::estimate_error(), libMesh::ExactErrorEstimator::estimate_error(), libMesh::ErrorEstimator::estimate_errors(), libMesh::ExactSolution::ExactSolution(), libMesh::System::get_all_variable_numbers(), libMesh::System::init(), libMesh::FEMSystem::init_context(), libMesh::FEMContext::init_internal_data(), libMesh::DGFEMContext::neighbor_side_fe_reinit(), libMesh::WeightedPatchRecoveryErrorEstimator::EstimateError::operator()(), libMesh::PatchRecoveryErrorEstimator::EstimateError::operator()(), libMesh::petsc_auto_fieldsplit(), libMesh::FEMContext::pre_fe_reinit(), libMesh::System::re_update(), libMesh::System::read_legacy_data(), libMesh::System::read_parallel_data(), libMesh::System::read_serialized_blocked_dof_objects(), libMesh::System::read_serialized_vector(), libMesh::System::read_serialized_vectors(), libMesh::HPCoarsenTest::select_refinement(), libMesh::PetscDMWrapper::set_point_range_in_section(), libMesh::SystemSubsetBySubdomain::set_var_nums(), libMesh::System::write_header(), libMesh::System::write_parallel_data(), libMesh::System::write_serialized_blocked_dof_objects(), libMesh::System::write_serialized_vector(), libMesh::System::write_serialized_vectors(), and libMesh::System::zero_variable().
 {
   return cast_int<unsigned int>(_variables.size());
 }
n_vectors()
unsigned int libMesh::System::n_vectors () const inline inherited
Returns
The number of vectors (in addition to the solution) handled by this system This is the size of the _vectors map
Definition at line 2233 of file system.h.
References libMesh::System::_vectors.
Referenced by libMesh::ExplicitSystem::add_system_rhs(), libMesh::System::compare(), libMesh::System::get_info(), and libMesh::System::write_header().
 {
   return cast_int<unsigned int>(_vectors.size());
 }
name()
const std::string & libMesh::System::name () const inline inherited
Returns
The system name.
Definition at line 2017 of file system.h.
References libMesh::System::_sys_name.
Referenced by libMesh::System::compare(), libMesh::ContinuationSystem::ContinuationSystem(), DMlibMeshSetUpName_Private(), libMesh::ExactErrorEstimator::estimate_error(), libMesh::ExactSolution::ExactSolution(), libMesh::ExactErrorEstimator::find_squared_element_error(), libMesh::System::get_info(), libMesh::ImplicitSystem::get_linear_solver(), libMesh::NewtonSolver::init(), libMesh::TimeSolver::init_data(), libMesh::petsc_auto_fieldsplit(), libMesh::TimeSolver::reinit(), libMesh::PetscDiffSolver::setup_petsc_data(), libMesh::FrequencySystem::solve(), libMesh::LinearImplicitSystem::solve(), libMesh::NonlinearImplicitSystem::solve(), libMesh::System::user_assembly(), libMesh::System::user_constrain(), libMesh::System::user_initialization(), libMesh::System::user_QOI(), libMesh::System::user_QOI_derivative(), libMesh::System::write_header(), libMesh::System::write_parallel_data(), and libMesh::System::write_serialized_data().
 {
   return _sys_name;
 }
number()
unsigned int libMesh::System::number () const inline inherited
Returns
The system number.
Definition at line 2025 of file system.h.
References libMesh::System::_sys_number.
Referenced by libMesh::ExactSolution::_compute_error(), libMesh::PetscDMWrapper::add_dofs_helper(), libMesh::System::add_variable(), libMesh::System::add_variables(), libMesh::EquationSystems::build_parallel_solution_vector(), libMesh::ExodusII_IO::copy_elemental_solution(), libMesh::ExodusII_IO::copy_nodal_solution(), libMesh::AdjointRefinementEstimator::estimate_error(), libMesh::ExactErrorEstimator::find_squared_element_error(), libMesh::System::get_info(), libMesh::System::read_legacy_data(), libMesh::System::read_parallel_data(), libMesh::System::read_serialized_blocked_dof_objects(), libMesh::HPCoarsenTest::select_refinement(), libMesh::PetscDMWrapper::set_point_range_in_section(), libMesh::System::write_parallel_data(), libMesh::System::write_serialized_blocked_dof_objects(), and libMesh::System::zero_variable().
 {
   return _sys_number;
 }
point_gradient() [1/3]
Gradient libMesh::System::point_gradient (unsigned int var, const Point & p, const bool insist_on_success = true) const inherited
Returns
The gradient of the solution variable var at the physical point p in the mesh, similarly to point_value.
Definition at line 2100 of file system.C.
References libMesh::Parallel::Communicator::broadcast(), libMesh::ParallelObject::comm(), libMesh::PointLocatorBase::enable_out_of_mesh_mode(), libMesh::System::get_dof_map(), libMesh::System::get_mesh(), mesh, libMesh::Parallel::Communicator::min(), libMesh::ParallelObject::n_processors(), libMesh::ParallelObject::processor_id(), and libMesh::DofObject::processor_id().
Referenced by libMesh::System::point_gradient().
 {
   // This function must be called on every processor; there's no
   // telling where in the partition p falls.
   parallel_object_only();
   // And every processor had better agree about which point we're
   // looking for
 #ifndef NDEBUG
   libmesh_assert(this->comm().verify(p(0)));
 #if LIBMESH_DIM > 1
   libmesh_assert(this->comm().verify(p(1)));
 #endif
 #if LIBMESH_DIM > 2
   libmesh_assert(this->comm().verify(p(2)));
 #endif
 #endif // NDEBUG
   // Get a reference to the mesh object associated with the system object that calls this function
   const MeshBase & mesh = this->get_mesh();
   // Use an existing PointLocator or create a new one
   std::unique_ptr<PointLocatorBase> locator_ptr = mesh.sub_point_locator();
   PointLocatorBase & locator = *locator_ptr;
   if (!insist_on_success || !mesh.is_serial())
     locator.enable_out_of_mesh_mode();
   // Get a pointer to the element that contains P
   const Elem * e = locator(p);
   Gradient grad_u;
   if (e && this->get_dof_map().is_evaluable(*e, var))
     grad_u = point_gradient(var, p, *e);
   // If I have an element containing p, then let's let everyone know
   processor_id_type lowest_owner =
     (e && (e->processor_id() == this->processor_id())) ?
     this->processor_id() : this->n_processors();
   this->comm().min(lowest_owner);
   // Everybody should get their value from a processor that was able
   // to compute it.
   // If nobody admits owning the point, we may have a problem.
   if (lowest_owner != this->n_processors())
     this->comm().broadcast(grad_u, lowest_owner);
   else
     libmesh_assert(!insist_on_success);
   return grad_u;
 }
point_gradient() [2/3]
Gradient libMesh::System::point_gradient (unsigned int var, const Point & p, const Elem & e) const inherited
Returns
The gradient of the solution variable var at the physical point p in local Elem e in the mesh, similarly to point_value.
Definition at line 2154 of file system.C.
References libMesh::TypeVector< T >::add_scaled(), libMesh::FEGenericBase< OutputType >::build(), libMesh::Elem::contains_point(), libMesh::System::current_solution(), libMesh::Elem::dim(), libMesh::DofMap::dof_indices(), libMesh::System::get_dof_map(), libMesh::Elem::infinite(), libMesh::FEInterface::inverse_map(), libMesh::DofMap::is_evaluable(), and libMesh::DofMap::variable_type().
 {
   // Ensuring that the given point is really in the element is an
   // expensive assert, but as long as debugging is turned on we might
   // as well try to catch a particularly nasty potential error
   libmesh_assert (e.contains_point(p));
 #ifdef LIBMESH_ENABLE_INFINITE_ELEMENTS
   if (e.infinite())
     libmesh_not_implemented();
 #endif
   // Get the dof map to get the proper indices for our computation
   const DofMap & dof_map = this->get_dof_map();
   // Make sure we can evaluate on this element.
   libmesh_assert (dof_map.is_evaluable(e, var));
   // Need dof_indices for phi[i][j]
   std::vector<dof_id_type> dof_indices;
   // Fill in the dof_indices for our element
   dof_map.dof_indices (&e, dof_indices, var);
   // Get the no of dofs associated with this point
   const unsigned int num_dofs = cast_int<unsigned int>
     (dof_indices.size());
   FEType fe_type = dof_map.variable_type(var);
   // Build a FE again so we can calculate u(p)
   std::unique_ptr<FEBase> fe (FEBase::build(e.dim(), fe_type));
   // Map the physical co-ordinates to the master co-ordinates using the inverse_map from fe_interface.h
   // Build a vector of point co-ordinates to send to reinit
   std::vector<Point> coor(1, FEInterface::inverse_map(e.dim(), fe_type, &e, p));
   // Get the values of the shape function derivatives
   const std::vector<std::vector<RealGradient>> &  dphi = fe->get_dphi();
   // Reinitialize the element and compute the shape function values at coor
   fe->reinit (&e, &coor);
   // Get ready to accumulate a gradient
   Gradient grad_u;
   for (unsigned int l=0; l<num_dofs; l++)
     {
       grad_u.add_scaled (dphi[l][0], this->current_solution (dof_indices[l]));
     }
   return grad_u;
 }
point_gradient() [3/3]
Gradient libMesh::System::point_gradient (unsigned int var, const Point & p, const Elem * e) const inherited
Calls the version of point_gradient() which takes a reference. This function exists only to prevent people from calling the version of point_gradient() that has a boolean third argument, which would result in unnecessary PointLocator calls.
Definition at line 2210 of file system.C.
References libMesh::System::point_gradient().
 {
   libmesh_assert(e);
   return this->point_gradient(var, p, *e);
 }
point_hessian() [1/3]
Tensor libMesh::System::point_hessian (unsigned int var, const Point & p, const bool insist_on_success = true) const inherited
Returns
The second derivative tensor of the solution variable var at the physical point p in the mesh, similarly to point_value.
Definition at line 2220 of file system.C.
References libMesh::Parallel::Communicator::broadcast(), libMesh::ParallelObject::comm(), libMesh::PointLocatorBase::enable_out_of_mesh_mode(), libMesh::System::get_dof_map(), libMesh::System::get_mesh(), mesh, libMesh::Parallel::Communicator::min(), libMesh::ParallelObject::n_processors(), libMesh::ParallelObject::processor_id(), and libMesh::DofObject::processor_id().
Referenced by libMesh::System::point_hessian().
 {
   // This function must be called on every processor; there's no
   // telling where in the partition p falls.
   parallel_object_only();
   // And every processor had better agree about which point we're
   // looking for
 #ifndef NDEBUG
   libmesh_assert(this->comm().verify(p(0)));
 #if LIBMESH_DIM > 1
   libmesh_assert(this->comm().verify(p(1)));
 #endif
 #if LIBMESH_DIM > 2
   libmesh_assert(this->comm().verify(p(2)));
 #endif
 #endif // NDEBUG
   // Get a reference to the mesh object associated with the system object that calls this function
   const MeshBase & mesh = this->get_mesh();
   // Use an existing PointLocator or create a new one
   std::unique_ptr<PointLocatorBase> locator_ptr = mesh.sub_point_locator();
   PointLocatorBase & locator = *locator_ptr;
   if (!insist_on_success || !mesh.is_serial())
     locator.enable_out_of_mesh_mode();
   // Get a pointer to the element that contains P
   const Elem * e = locator(p);
   Tensor hess_u;
   if (e && this->get_dof_map().is_evaluable(*e, var))
     hess_u = point_hessian(var, p, *e);
   // If I have an element containing p, then let's let everyone know
   processor_id_type lowest_owner =
     (e && (e->processor_id() == this->processor_id())) ?
     this->processor_id() : this->n_processors();
   this->comm().min(lowest_owner);
   // Everybody should get their value from a processor that was able
   // to compute it.
   // If nobody admits owning the point, we may have a problem.
   if (lowest_owner != this->n_processors())
     this->comm().broadcast(hess_u, lowest_owner);
   else
     libmesh_assert(!insist_on_success);
   return hess_u;
 }
point_hessian() [2/3]
Tensor libMesh::System::point_hessian (unsigned int var, const Point & p, const Elem & e) const inherited
Returns
The second derivative tensor of the solution variable var at the physical point p in local Elem e in the mesh, similarly to point_value.
Definition at line 2273 of file system.C.
References libMesh::TypeTensor< T >::add_scaled(), libMesh::FEGenericBase< OutputType >::build(), libMesh::Elem::contains_point(), libMesh::System::current_solution(), libMesh::Elem::dim(), libMesh::DofMap::dof_indices(), libMesh::System::get_dof_map(), libMesh::Elem::infinite(), libMesh::FEInterface::inverse_map(), libMesh::DofMap::is_evaluable(), and libMesh::DofMap::variable_type().
 {
   // Ensuring that the given point is really in the element is an
   // expensive assert, but as long as debugging is turned on we might
   // as well try to catch a particularly nasty potential error
   libmesh_assert (e.contains_point(p));
 #ifdef LIBMESH_ENABLE_INFINITE_ELEMENTS
   if (e.infinite())
     libmesh_not_implemented();
 #endif
   // Get the dof map to get the proper indices for our computation
   const DofMap & dof_map = this->get_dof_map();
   // Make sure we can evaluate on this element.
   libmesh_assert (dof_map.is_evaluable(e, var));
   // Need dof_indices for phi[i][j]
   std::vector<dof_id_type> dof_indices;
   // Fill in the dof_indices for our element
   dof_map.dof_indices (&e, dof_indices, var);
   // Get the no of dofs associated with this point
   const unsigned int num_dofs = cast_int<unsigned int>
     (dof_indices.size());
   FEType fe_type = dof_map.variable_type(var);
   // Build a FE again so we can calculate u(p)
   std::unique_ptr<FEBase> fe (FEBase::build(e.dim(), fe_type));
   // Map the physical co-ordinates to the master co-ordinates using the inverse_map from fe_interface.h
   // Build a vector of point co-ordinates to send to reinit
   std::vector<Point> coor(1, FEInterface::inverse_map(e.dim(), fe_type, &e, p));
   // Get the values of the shape function derivatives
   const std::vector<std::vector<RealTensor>> &  d2phi = fe->get_d2phi();
   // Reinitialize the element and compute the shape function values at coor
   fe->reinit (&e, &coor);
   // Get ready to accumulate a hessian
   Tensor hess_u;
   for (unsigned int l=0; l<num_dofs; l++)
     {
       hess_u.add_scaled (d2phi[l][0], this->current_solution (dof_indices[l]));
     }
   return hess_u;
 }
point_hessian() [3/3]
Tensor libMesh::System::point_hessian (unsigned int var, const Point & p, const Elem * e) const inherited
Calls the version of point_hessian() which takes a reference. This function exists only to prevent people from calling the version of point_hessian() that has a boolean third argument, which would result in unnecessary PointLocator calls.
Definition at line 2329 of file system.C.
References libMesh::System::point_hessian().
 {
   libmesh_assert(e);
   return this->point_hessian(var, p, *e);
 }
point_value() [1/3]
Number libMesh::System::point_value (unsigned int var, const Point & p, const bool insist_on_success = true) const inherited
Returns
The value of the solution variable var at the physical point p in the mesh, without knowing a priori which element contains p.
Note
This function uses MeshBase::sub_point_locator(); users may or may not want to call MeshBase::clear_point_locator() afterward. Also, point_locator() is expensive (N log N for initial construction, log N for evaluations). Avoid using this function in any context where you are already looping over elements.
Because the element containing p may lie on any processor, this function is parallel-only.
By default this method expects the point to reside inside the domain and will abort if no element can be found which contains p. The optional parameter insist_on_success can be set to false to allow the method to return 0 when the point is not located.
Definition at line 1993 of file system.C.
References libMesh::Parallel::Communicator::broadcast(), libMesh::ParallelObject::comm(), libMesh::PointLocatorBase::enable_out_of_mesh_mode(), libMesh::System::get_dof_map(), libMesh::System::get_mesh(), mesh, libMesh::Parallel::Communicator::min(), libMesh::ParallelObject::n_processors(), libMesh::ParallelObject::processor_id(), and libMesh::DofObject::processor_id().
Referenced by libMesh::System::point_value().
 {
   // This function must be called on every processor; there's no
   // telling where in the partition p falls.
   parallel_object_only();
   // And every processor had better agree about which point we're
   // looking for
 #ifndef NDEBUG
   libmesh_assert(this->comm().verify(p(0)));
 #if LIBMESH_DIM > 1
   libmesh_assert(this->comm().verify(p(1)));
 #endif
 #if LIBMESH_DIM > 2
   libmesh_assert(this->comm().verify(p(2)));
 #endif
 #endif // NDEBUG
   // Get a reference to the mesh object associated with the system object that calls this function
   const MeshBase & mesh = this->get_mesh();
   // Use an existing PointLocator or create a new one
   std::unique_ptr<PointLocatorBase> locator_ptr = mesh.sub_point_locator();
   PointLocatorBase & locator = *locator_ptr;
   if (!insist_on_success || !mesh.is_serial())
     locator.enable_out_of_mesh_mode();
   // Get a pointer to the element that contains P
   const Elem * e = locator(p);
   Number u = 0;
   if (e && this->get_dof_map().is_evaluable(*e, var))
     u = point_value(var, p, *e);
   // If I have an element containing p, then let's let everyone know
   processor_id_type lowest_owner =
     (e && (e->processor_id() == this->processor_id())) ?
     this->processor_id() : this->n_processors();
   this->comm().min(lowest_owner);
   // Everybody should get their value from a processor that was able
   // to compute it.
   // If nobody admits owning the point, we have a problem.
   if (lowest_owner != this->n_processors())
     this->comm().broadcast(u, lowest_owner);
   else
     libmesh_assert(!insist_on_success);
   return u;
 }
point_value() [2/3]
Number libMesh::System::point_value (unsigned int var, const Point & p, const Elem & e) const inherited
Returns
The value of the solution variable var at the physical point p contained in local Elem e
This version of point_value can be run in serial, but assumes e is in the local mesh partition or is algebraically ghosted.
Definition at line 2046 of file system.C.
References libMesh::FEInterface::compute_data(), libMesh::Elem::contains_point(), libMesh::System::current_solution(), libMesh::Elem::dim(), libMesh::System::get_dof_map(), libMesh::System::get_equation_systems(), and libMesh::FEInterface::inverse_map().
 {
   // Ensuring that the given point is really in the element is an
   // expensive assert, but as long as debugging is turned on we might
   // as well try to catch a particularly nasty potential error
   libmesh_assert (e.contains_point(p));
   // Get the dof map to get the proper indices for our computation
   const DofMap & dof_map = this->get_dof_map();
   // Make sure we can evaluate on this element.
   libmesh_assert (dof_map.is_evaluable(e, var));
   // Need dof_indices for phi[i][j]
   std::vector<dof_id_type> dof_indices;
   // Fill in the dof_indices for our element
   dof_map.dof_indices (&e, dof_indices, var);
   // Get the no of dofs associated with this point
   const unsigned int num_dofs = cast_int<unsigned int>
     (dof_indices.size());
   FEType fe_type = dof_map.variable_type(var);
   // Map the physical co-ordinates to the master co-ordinates using the inverse_map from fe_interface.h.
   Point coor = FEInterface::inverse_map(e.dim(), fe_type, &e, p);
   // get the shape function value via the FEInterface to also handle the case
   // of infinite elements correcly, the shape function is not fe->phi().
   FEComputeData fe_data(this->get_equation_systems(), coor);
   FEInterface::compute_data(e.dim(), fe_type, &e, fe_data);
   // Get ready to accumulate a value
   Number u = 0;
   for (unsigned int l=0; l<num_dofs; l++)
     {
       u += fe_data.shape[l]*this->current_solution (dof_indices[l]);
     }
   return u;
 }
point_value() [3/3]
Number libMesh::System::point_value (unsigned int var, const Point & p, const Elem * e) const inherited
Calls the version of point_value() which takes a reference. This function exists only to prevent people from calling the version of point_value() that has a boolean third argument, which would result in unnecessary PointLocator calls.
Definition at line 2092 of file system.C.
References libMesh::System::point_value().
 {
   libmesh_assert(e);
   return this->point_value(var, p, *e);
 }
print_info()
void libMesh::ReferenceCounter::print_info (std::ostream & out = libMesh::out) static inherited
Prints the reference information, by default to libMesh::out.
Definition at line 87 of file reference_counter.C.
References libMesh::ReferenceCounter::_enable_print_counter, and libMesh::ReferenceCounter::get_info().
 {
   if (_enable_print_counter)
     out_stream << ReferenceCounter::get_info();
 }
processor_id()
processor_id_type libMesh::ParallelObject::processor_id () const inline inherited
Returns
The rank of this processor in the group.
Definition at line 101 of file parallel_object.h.
References libMesh::ParallelObject::_communicator, and libMesh::Parallel::Communicator::rank().
Referenced by libMesh::BoundaryInfo::_find_id_maps(), libMesh::EquationSystems::_read_impl(), libMesh::PetscDMWrapper::add_dofs_to_section(), libMesh::DistributedMesh::add_elem(), libMesh::BoundaryInfo::add_elements(), libMesh::DofMap::add_neighbors_to_send_list(), libMesh::DistributedMesh::add_node(), libMesh::UnstructuredMesh::all_second_order(), libMesh::MeshTools::Modification::all_tri(), libMesh::FEMSystem::assembly(), libMesh::EquationSystems::build_discontinuous_solution_vector(), libMesh::Nemesis_IO_Helper::build_element_and_node_maps(), libMesh::InfElemBuilder::build_inf_elem(), libMesh::BoundaryInfo::build_node_list_from_side_list(), libMesh::EquationSystems::build_parallel_elemental_solution_vector(), libMesh::DistributedMesh::clear(), libMesh::ExodusII_IO_Helper::close(), libMesh::Nemesis_IO_Helper::compute_border_node_ids(), libMesh::Nemesis_IO_Helper::compute_communication_map_parameters(), libMesh::Nemesis_IO_Helper::compute_internal_and_border_elems_and_internal_nodes(), libMesh::Nemesis_IO_Helper::compute_node_communication_maps(), libMesh::Nemesis_IO_Helper::compute_num_global_elem_blocks(), libMesh::Nemesis_IO_Helper::compute_num_global_nodesets(), libMesh::Nemesis_IO_Helper::compute_num_global_sidesets(), libMesh::Nemesis_IO_Helper::construct_nemesis_filename(), libMesh::MeshTools::correct_node_proc_ids(), libMesh::ExodusII_IO_Helper::create(), libMesh::DistributedMesh::delete_elem(), libMesh::DistributedMesh::delete_node(), libMesh::MeshCommunication::delete_remote_elements(), libMesh::DofMap::distribute_dofs(), libMesh::DofMap::distribute_local_dofs_node_major(), libMesh::DofMap::distribute_local_dofs_var_major(), libMesh::DistributedMesh::DistributedMesh(), libMesh::DofMap::end_dof(), libMesh::DofMap::end_old_dof(), libMesh::EnsightIO::EnsightIO(), libMesh::MeshFunction::find_element(), libMesh::MeshFunction::find_elements(), libMesh::UnstructuredMesh::find_neighbors(), libMesh::DofMap::first_dof(), libMesh::DofMap::first_old_dof(), libMesh::Nemesis_IO_Helper::get_cmap_params(), libMesh::Nemesis_IO_Helper::get_eb_info_global(), libMesh::Nemesis_IO_Helper::get_elem_cmap(), libMesh::Nemesis_IO_Helper::get_elem_map(), libMesh::MeshBase::get_info(), libMesh::DofMap::get_info(), libMesh::Nemesis_IO_Helper::get_init_global(), libMesh::Nemesis_IO_Helper::get_init_info(), libMesh::Nemesis_IO_Helper::get_loadbal_param(), libMesh::Nemesis_IO_Helper::get_node_cmap(), libMesh::Nemesis_IO_Helper::get_node_map(), libMesh::Nemesis_IO_Helper::get_ns_param_global(), libMesh::Nemesis_IO_Helper::get_ss_param_global(), libMesh::SparsityPattern::Build::handle_vi_vj(), libMesh::SystemSubsetBySubdomain::init(), libMesh::ExodusII_IO_Helper::initialize(), libMesh::ExodusII_IO_Helper::initialize_element_variables(), libMesh::ExodusII_IO_Helper::initialize_global_variables(), libMesh::ExodusII_IO_Helper::initialize_nodal_variables(), libMesh::DistributedMesh::insert_elem(), libMesh::DofMap::is_evaluable(), libMesh::SparsityPattern::Build::join(), libMesh::DofMap::last_dof(), libMesh::MeshTools::libmesh_assert_consistent_distributed(), libMesh::MeshTools::libmesh_assert_consistent_distributed_nodes(), libMesh::MeshTools::libmesh_assert_contiguous_dof_ids(), libMesh::MeshTools::libmesh_assert_parallel_consistent_procids< Elem >(), libMesh::MeshTools::libmesh_assert_valid_neighbors(), libMesh::DistributedMesh::libmesh_assert_valid_parallel_object_ids(), libMesh::DofMap::local_variable_indices(), libMesh::MeshRefinement::make_coarsening_compatible(), libMesh::MeshBase::n_active_local_elem(), libMesh::BoundaryInfo::n_boundary_conds(), libMesh::BoundaryInfo::n_edge_conds(), libMesh::DofMap::n_local_dofs(), libMesh::System::n_local_dofs(), libMesh::MeshBase::n_local_elem(), libMesh::MeshBase::n_local_nodes(), libMesh::BoundaryInfo::n_nodeset_conds(), libMesh::BoundaryInfo::n_shellface_conds(), libMesh::SparsityPattern::Build::operator()(), libMesh::DistributedMesh::own_node(), libMesh::System::point_gradient(), libMesh::System::point_hessian(), libMesh::System::point_value(), libMesh::Nemesis_IO_Helper::put_cmap_params(), libMesh::Nemesis_IO_Helper::put_elem_cmap(), libMesh::Nemesis_IO_Helper::put_elem_map(), libMesh::Nemesis_IO_Helper::put_loadbal_param(), libMesh::Nemesis_IO_Helper::put_node_cmap(), libMesh::Nemesis_IO_Helper::put_node_map(), libMesh::NameBasedIO::read(), libMesh::Nemesis_IO::read(), libMesh::XdrIO::read(), libMesh::CheckpointIO::read(), libMesh::ExodusII_IO_Helper::read_elem_num_map(), libMesh::ExodusII_IO_Helper::read_global_values(), libMesh::CheckpointIO::read_header(), libMesh::XdrIO::read_header(), libMesh::System::read_header(), libMesh::System::read_legacy_data(), libMesh::ExodusII_IO_Helper::read_node_num_map(), libMesh::System::read_parallel_data(), libMesh::System::read_SCALAR_dofs(), libMesh::XdrIO::read_serialized_bc_names(), libMesh::XdrIO::read_serialized_bcs_helper(), libMesh::System::read_serialized_blocked_dof_objects(), libMesh::XdrIO::read_serialized_connectivity(), libMesh::System::read_serialized_data(), libMesh::XdrIO::read_serialized_nodes(), libMesh::XdrIO::read_serialized_nodesets(), libMesh::XdrIO::read_serialized_subdomain_names(), libMesh::System::read_serialized_vector(), libMesh::System::read_serialized_vectors(), libMesh::DistributedMesh::renumber_dof_objects(), libMesh::CheckpointIO::select_split_config(), libMesh::DofMap::set_nonlocal_dof_objects(), libMesh::PetscDMWrapper::set_point_range_in_section(), libMesh::LaplaceMeshSmoother::smooth(), libMesh::MeshTools::total_weight(), libMesh::MeshRefinement::uniformly_coarsen(), libMesh::Parallel::Packing< T >::unpack(), libMesh::DistributedMesh::update_parallel_id_counts(), libMesh::NameBasedIO::write(), libMesh::XdrIO::write(), libMesh::CheckpointIO::write(), libMesh::EquationSystems::write(), libMesh::GMVIO::write_discontinuous_gmv(), libMesh::ExodusII_IO::write_element_data(), libMesh::ExodusII_IO_Helper::write_element_values(), libMesh::ExodusII_IO_Helper::write_elements(), libMesh::ExodusII_IO::write_global_data(), libMesh::ExodusII_IO_Helper::write_global_values(), libMesh::System::write_header(), libMesh::ExodusII_IO::write_information_records(), libMesh::ExodusII_IO_Helper::write_information_records(), libMesh::ExodusII_IO_Helper::write_nodal_coordinates(), libMesh::UCDIO::write_nodal_data(), libMesh::ExodusII_IO::write_nodal_data(), libMesh::ExodusII_IO::write_nodal_data_discontinuous(), libMesh::ExodusII_IO_Helper::write_nodal_values(), libMesh::Nemesis_IO_Helper::write_nodesets(), libMesh::ExodusII_IO_Helper::write_nodesets(), libMesh::System::write_parallel_data(), libMesh::System::write_SCALAR_dofs(), libMesh::XdrIO::write_serialized_bc_names(), libMesh::XdrIO::write_serialized_bcs_helper(), libMesh::System::write_serialized_blocked_dof_objects(), libMesh::XdrIO::write_serialized_connectivity(), libMesh::System::write_serialized_data(), libMesh::XdrIO::write_serialized_nodes(), libMesh::XdrIO::write_serialized_nodesets(), libMesh::XdrIO::write_serialized_subdomain_names(), libMesh::System::write_serialized_vector(), libMesh::System::write_serialized_vectors(), libMesh::Nemesis_IO_Helper::write_sidesets(), libMesh::ExodusII_IO_Helper::write_sidesets(), libMesh::ExodusII_IO::write_timestep(), libMesh::ExodusII_IO_Helper::write_timestep(), and libMesh::ExodusII_IO::write_timestep_discontinuous().
   { return cast_int<processor_id_type>(_communicator.rank()); }
project_solution() [1/3]
void libMesh::System::project_solution (FunctionBase< Number > * f, FunctionBase< Gradient > * g = nullptr) const inherited
Projects arbitrary functions onto the current solution. The function value f and its gradient g are user-provided cloneable functors. A gradient g is only required/used for projecting onto finite element spaces with continuous derivatives. If non-default Parameters are to be used, they can be provided in the parameters argument.
This method projects an arbitrary function onto the solution via L2 projections and nodal interpolations on each element.
Definition at line 810 of file system_projection.C.
 {
   this->project_vector(*solution, f, g);
   solution->localize(*current_local_solution, _dof_map->get_send_list());
 }
project_solution() [2/3]
void libMesh::System::project_solution (FEMFunctionBase< Number > * f, FEMFunctionBase< Gradient > * g = nullptr) const inherited
Projects arbitrary functions onto the current solution. The function value f and its gradient g are user-provided cloneable functors. A gradient g is only required/used for projecting onto finite element spaces with continuous derivatives. If non-default Parameters are to be used, they can be provided in the parameters argument.
This method projects an arbitrary function onto the solution via L2 projections and nodal interpolations on each element.
Definition at line 823 of file system_projection.C.
 {
   this->project_vector(*solution, f, g);
   solution->localize(*current_local_solution, _dof_map->get_send_list());
 }
project_solution() [3/3]
void libMesh::System::project_solution (ValueFunctionPointer fptr, GradientFunctionPointer gptr, const Parameters & parameters) const inherited
This method projects an arbitrary function onto the solution via L2 projections and nodal interpolations on each element.
Definition at line 796 of file system_projection.C.
 {
   WrappedFunction<Number> f(*this, fptr, &parameters);
   WrappedFunction<Gradient> g(*this, gptr, &parameters);
   this->project_solution(&f, &g);
 }
project_solution_on_reinit()
bool& libMesh::System::project_solution_on_reinit (void) inline inherited
Tells the System whether or not to project the solution vector onto new grids when the system is reinitialized. The solution will be projected unless project_solution_on_reinit() = false is called.
Definition at line 794 of file system.h.
References libMesh::System::_solution_projection.
Referenced by libMesh::UniformRefinementEstimator::_estimate_error(), libMesh::AdjointRefinementEstimator::estimate_error(), and libMesh::MemorySolutionHistory::store().
   { return _solution_projection; }
project_vector() [1/5]
void libMesh::System::project_vector (NumericVector< Number > & new_vector, FunctionBase< Number > * f, FunctionBase< Gradient > * g = nullptr, int is_adjoint = -1) const inherited
Projects arbitrary functions onto a vector of degree of freedom values for the current system. The function value f and its gradient g are user-provided cloneable functors. A gradient g is only required/used for projecting onto finite element spaces with continuous derivatives. If non-default Parameters are to be used, they can be provided in the parameters argument.
Constrain the new vector using the requested adjoint rather than primal constraints if is_adjoint is non-negative.
This method projects an arbitrary function via L2 projections and nodal interpolations on each element.
Definition at line 851 of file system_projection.C.
Referenced by libMesh::NewmarkSolver::project_initial_accel(), libMesh::SecondOrderUnsteadySolver::project_initial_rate(), and libMesh::System::restrict_vectors().
 {
   LOG_SCOPE ("project_vector(FunctionBase)", "System");
   libmesh_assert(f);
   WrappedFunctor<Number> f_fem(*f);
   if (g)
     {
       WrappedFunctor<Gradient> g_fem(*g);
       this->project_vector(new_vector, &f_fem, &g_fem, is_adjoint);
     }
   else
     this->project_vector(new_vector, &f_fem, nullptr, is_adjoint);
 }
project_vector() [2/5]
void libMesh::System::project_vector (NumericVector< Number > & new_vector, FEMFunctionBase< Number > * f, FEMFunctionBase< Gradient > * g = nullptr, int is_adjoint = -1) const inherited
Projects arbitrary functions onto a vector of degree of freedom values for the current system. The function value f and its gradient g are user-provided cloneable functors. A gradient g is only required/used for projecting onto finite element spaces with continuous derivatives. If non-default Parameters are to be used, they can be provided in the parameters argument.
Constrain the new vector using the requested adjoint rather than primal constraints if is_adjoint is non-negative.
This method projects an arbitrary function via L2 projections and nodal interpolations on each element.
Definition at line 877 of file system_projection.C.
References libMesh::NumericVector< T >::close(), libMesh::FEMFunctionBase< Output >::component(), libMesh::Utility::iota(), n_vars, libMesh::Threads::parallel_for(), libMesh::FEMContext::pre_fe_reinit(), libMesh::SCALAR, libMesh::DofMap::SCALAR_dof_indices(), and libMesh::NumericVector< T >::set().
 {
   LOG_SCOPE ("project_fem_vector()", "System");
   libmesh_assert (f);
   ConstElemRange active_local_range
     (this->get_mesh().active_local_elements_begin(),
      this->get_mesh().active_local_elements_end() );
   VectorSetAction<Number> setter(new_vector);
   const unsigned int n_variables = this->n_vars();
   std::vector<unsigned int> vars(n_variables);
   std::iota(vars.begin(), vars.end(), 0);
   // Use a typedef to make the calling sequence for parallel_for() a bit more readable
   typedef
     GenericProjector<FEMFunctionWrapper<Number>, FEMFunctionWrapper<Gradient>,
                      Number, VectorSetAction<Number>> FEMProjector;
   FEMFunctionWrapper<Number> fw(*f);
   if (g)
     {
       FEMFunctionWrapper<Gradient> gw(*g);
       Threads::parallel_for
         (active_local_range,
          FEMProjector(*this, fw, &gw, setter, vars));
     }
   else
     Threads::parallel_for
       (active_local_range,
        FEMProjector(*this, fw, nullptr, setter, vars));
   // Also, load values into the SCALAR dofs
   // Note: We assume that all SCALAR dofs are on the
   // processor with highest ID
   if (this->processor_id() == (this->n_processors()-1))
     {
       // FIXME: Do we want to first check for SCALAR vars before building this? [PB]
       FEMContext context( *this );
       const DofMap & dof_map = this->get_dof_map();
       for (unsigned int var=0; var<this->n_vars(); var++)
         if (this->variable(var).type().family == SCALAR)
           {
             // FIXME: We reinit with an arbitrary element in case the user
             //        doesn't override FEMFunctionBase::component. Is there
             //        any use case we're missing? [PB]
             Elem * el = const_cast<Elem *>(*(this->get_mesh().active_local_elements_begin()));
             context.pre_fe_reinit(*this, el);
             std::vector<dof_id_type> SCALAR_indices;
             dof_map.SCALAR_dof_indices (SCALAR_indices, var);
             const unsigned int n_SCALAR_dofs =
               cast_int<unsigned int>(SCALAR_indices.size());
             for (unsigned int i=0; i<n_SCALAR_dofs; i++)
               {
                 const dof_id_type global_index = SCALAR_indices[i];
                 const unsigned int component_index =
                   this->variable_scalar_number(var,i);
                 new_vector.set(global_index, f->component(context, component_index, Point(), this->time));
               }
           }
     }
   new_vector.close();
 #ifdef LIBMESH_ENABLE_CONSTRAINTS
   if (is_adjoint == -1)
     this->get_dof_map().enforce_constraints_exactly(*this, &new_vector);
   else if (is_adjoint >= 0)
     this->get_dof_map().enforce_adjoint_constraints_exactly(new_vector,
                                                             is_adjoint);
 #endif
 }
project_vector() [3/5]
void libMesh::System::project_vector (ValueFunctionPointer fptr, GradientFunctionPointer gptr, const Parameters & parameters, NumericVector< Number > & new_vector, int is_adjoint = -1) const inherited
Projects arbitrary functions onto a vector of degree of freedom values for the current system. The function value fptr and its gradient gptr are represented by function pointers. A gradient gptr is only required/used for projecting onto finite element spaces with continuous derivatives.
Constrain the new vector using the requested adjoint rather than primal constraints if is_adjoint is non-negative.
This method projects an arbitrary function via L2 projections and nodal interpolations on each element.
Definition at line 836 of file system_projection.C.
 {
   WrappedFunction<Number> f(*this, fptr, &parameters);
   WrappedFunction<Gradient> g(*this, gptr, &parameters);
   this->project_vector(new_vector, &f, &g, is_adjoint);
 }
project_vector() [4/5]
void libMesh::System::project_vector (NumericVector< Number > & vector, int is_adjoint = -1) const protected inherited
Projects the vector defined on the old mesh onto the new mesh.
Constrain the new vector using the requested adjoint rather than primal constraints if is_adjoint is non-negative.
Definition at line 212 of file system_projection.C.
References libMesh::NumericVector< T >::clone().
 {
   // Create a copy of the vector, which currently
   // contains the old data.
   std::unique_ptr<NumericVector<Number>>
     old_vector (vector.clone());
   // Project the old vector to the new vector
   this->project_vector (*old_vector, vector, is_adjoint);
 }
project_vector() [5/5]
void libMesh::System::project_vector (const NumericVector< Number > & , NumericVector< Number > & , int is_adjoint = -1) const protected inherited
Projects the vector defined on the old mesh onto the new mesh. The original vector is unchanged and the new vector is passed through the second argument.
Constrain the new vector using the requested adjoint rather than primal constraints if is_adjoint is non-negative.
projection_matrix()
void libMesh::System::projection_matrix (SparseMatrix< Number > & proj_mat) const inherited
This method creates a projection matrix which corresponds to the operation of project_vector between old and new solution spaces.
Heterogeneous Dirichlet boundary conditions are not taken into account here; if this matrix is used for prolongation (mesh refinement) on a side with a heterogeneous BC, the newly created degrees of freedom on that side will still match the coarse grid approximation of the BC, not the fine grid approximation.
This method creates a projection matrix which corresponds to the operation of project_vector between old and new solution spaces.
Definition at line 730 of file system_projection.C.
References libMesh::Utility::iota(), n_vars, libMesh::Threads::parallel_for(), libMesh::SCALAR, libMesh::DofMap::SCALAR_dof_indices(), and libMesh::SparseMatrix< T >::set().
 {
   LOG_SCOPE ("projection_matrix()", "System");
   const unsigned int n_variables = this->n_vars();
   if (n_variables)
     {
       ConstElemRange active_local_elem_range
         (this->get_mesh().active_local_elements_begin(),
          this->get_mesh().active_local_elements_end());
       std::vector<unsigned int> vars(n_variables);
       std::iota(vars.begin(), vars.end(), 0);
       // Use a typedef to make the calling sequence for parallel_for() a bit more readable
       typedef OldSolutionCoefs<Real, &FEMContext::point_value> OldSolutionValueCoefs;
       typedef OldSolutionCoefs<RealGradient, &FEMContext::point_gradient> OldSolutionGradientCoefs;
       typedef
         GenericProjector<OldSolutionValueCoefs,
                          OldSolutionGradientCoefs,
                          DynamicSparseNumberArray<Real,dof_id_type>,
                          MatrixFillAction<Real, Number> > ProjMatFiller;
       OldSolutionValueCoefs    f(*this);
       OldSolutionGradientCoefs g(*this);
       MatrixFillAction<Real, Number> setter(proj_mat);
       Threads::parallel_for (active_local_elem_range,
                              ProjMatFiller(*this, f, &g, setter, vars));
       // Set the SCALAR dof transfer entries too.
       // Note: We assume that all SCALAR dofs are on the
       // processor with highest ID
       if (this->processor_id() == (this->n_processors()-1))
         {
           const DofMap & dof_map = this->get_dof_map();
           for (unsigned int var=0; var<this->n_vars(); var++)
             if (this->variable(var).type().family == SCALAR)
               {
                 // We can just map SCALAR dofs directly across
                 std::vector<dof_id_type> new_SCALAR_indices, old_SCALAR_indices;
                 dof_map.SCALAR_dof_indices (new_SCALAR_indices, var, false);
                 dof_map.SCALAR_dof_indices (old_SCALAR_indices, var, true);
                 const unsigned int new_n_dofs =
                   cast_int<unsigned int>(new_SCALAR_indices.size());
                 for (unsigned int i=0; i<new_n_dofs; i++)
                   {
                     proj_mat.set( new_SCALAR_indices[i],
                                   old_SCALAR_indices[i], 1);
                   }
               }
         }
     }
 }
prolong_vectors()
void libMesh::System::prolong_vectors () virtual inherited
Prolong vectors after the mesh has refined
Definition at line 380 of file system.C.
References libMesh::System::restrict_vectors().
Referenced by libMesh::EquationSystems::reinit_solutions().
 {
 #ifdef LIBMESH_ENABLE_AMR
   // Currently project_vector handles both restriction and prolongation
   this->restrict_vectors();
 #endif
 }
qoi_parameter_hessian()
void libMesh::System::qoi_parameter_hessian (const QoISet & qoi_indices, const ParameterVector & parameters, SensitivityData & hessian) inline virtual inherited
For each of the system's quantities of interest q in qoi[qoi_indices], and for a vector of parameters p, the parameter sensitivity Hessian H_ij is defined as H_ij = (d^2 q)/(d p_i d p_j) This Hessian is the output of this method, where for each q_i, H_jk is stored in hessian.second_derivative(i,j,k).
This method is only implemented in some derived classes.
Reimplemented in libMesh::ImplicitSystem.
Definition at line 2334 of file system.h.
 {
   libmesh_not_implemented();
 }
qoi_parameter_hessian_vector_product()
void libMesh::System::qoi_parameter_hessian_vector_product (const QoISet & qoi_indices, const ParameterVector & parameters, const ParameterVector & vector, SensitivityData & product) inline virtual inherited
For each of the system's quantities of interest q in qoi[qoi_indices], and for a vector of parameters p, the parameter sensitivity Hessian H_ij is defined as H_ij = (d^2 q)/(d p_i d p_j) The Hessian-vector product, for a vector v_k in parameter space, is S_j = H_jk v_k This product is the output of this method, where for each q_i, S_j is stored in sensitivities[i][j].
This method is only implemented in some derived classes.
Reimplemented in libMesh::ImplicitSystem.
Definition at line 2343 of file system.h.
 {
   libmesh_not_implemented();
 }
qoi_parameter_sensitivity()
void libMesh::System::qoi_parameter_sensitivity (const QoISet & qoi_indices, const ParameterVector & parameters, SensitivityData & sensitivities) virtual inherited
Solves for the derivative of each of the system's quantities of interest q in qoi[qoi_indices] with respect to each parameter in parameters, placing the result for qoi i and parameter j into sensitivities[i][j].
Note
parameters is a const vector, not a vector-of-const; parameter values in this vector need to be mutable for finite differencing to work.
Automatically chooses the forward method for problems with more quantities of interest than parameters, or the adjoint method otherwise.
This method is only usable in derived classes which override an implementation.
Definition at line 498 of file system.C.
References libMesh::System::adjoint_qoi_parameter_sensitivity(), libMesh::System::forward_qoi_parameter_sensitivity(), libMesh::ParameterVector::size(), and libMesh::QoISet::size().
 {
   // Forward sensitivities are more efficient for Nq > Np
   if (qoi_indices.size(*this) > parameters.size())
     forward_qoi_parameter_sensitivity(qoi_indices, parameters, sensitivities);
   // Adjoint sensitivities are more efficient for Np > Nq,
   // and an adjoint may be more reusable than a forward
   // solution sensitivity in the Np == Nq case.
   else
     adjoint_qoi_parameter_sensitivity(qoi_indices, parameters, sensitivities);
 }
re_update()
void libMesh::System::re_update () virtual inherited
Re-update the local values when the mesh has changed. This method takes the data updated by update() and makes it up-to-date on the current mesh.
Reimplemented in libMesh::TransientSystem< RBConstruction >.
Definition at line 429 of file system.C.
References libMesh::System::current_local_solution, libMesh::System::get_dof_map(), libMesh::DofMap::get_send_list(), libMesh::System::n_vars(), and libMesh::System::solution.
 {
   parallel_object_only();
   // If this system is empty... don't do anything!
   if (!this->n_vars())
     return;
   const std::vector<dof_id_type> & send_list = this->get_dof_map().get_send_list ();
   // Check sizes
   libmesh_assert_equal_to (current_local_solution->size(), solution->size());
   // Not true with ghosted vectors
   // libmesh_assert_equal_to (current_local_solution->local_size(), solution->size());
   // libmesh_assert (!send_list.empty());
   libmesh_assert_less_equal (send_list.size(), solution->size());
   // Create current_local_solution from solution.  This will
   // put a local copy of solution into current_local_solution.
   solution->localize (*current_local_solution, send_list);
 }
read_header()
void libMesh::System::read_header (Xdr & io, const std::string & version, const bool read_header = true, const bool read_additional_data = true, const bool read_legacy_format = false) inherited
Reads the basic data header for this System.
Definition at line 115 of file system_io.C.
References libMesh::System::_additional_data_written, libMesh::System::_written_var_indices, libMesh::System::add_variable(), libMesh::System::add_vector(), libMesh::Parallel::Communicator::broadcast(), libMesh::System::clear(), libMesh::ParallelObject::comm(), libMesh::Xdr::data(), libMesh::FEType::family, libMesh::System::get_mesh(), libMesh::OrderWrapper::get_order(), libMesh::FEType::inf_map, libMesh::MeshBase::mesh_dimension(), libMesh::MONOMIAL, libMesh::on_command_line(), libMesh::FEType::order, libMesh::out, libMesh::ParallelObject::processor_id(), libMesh::FEType::radial_family, libMesh::FEType::radial_order, libMesh::Xdr::reading(), libMesh::System::variable_number(), libMesh::Xdr::version(), and libMesh::XYZ.
Referenced by libMesh::EquationSystems::_read_impl().
 {
   // This method implements the input of a
   // System object, embedded in the output of
   // an EquationSystems<T_sys>.  This warrants some
   // documentation.  The output file essentially
   // consists of 5 sections:
   //
   // for this system
   //
   //   5.) The number of variables in the system (unsigned int)
   //
   //   for each variable in the system
   //
   //     6.) The name of the variable (string)
   //
   //     6.1.) Variable subdomains
   //
   //     7.) Combined in an FEType:
   //         - The approximation order(s) of the variable
   //           (Order Enum, cast to int/s)
   //         - The finite element family/ies of the variable
   //           (FEFamily Enum, cast to int/s)
   //
   //   end variable loop
   //
   //   8.) The number of additional vectors (unsigned int),
   //
   //     for each additional vector in the system object
   //
   //     9.) the name of the additional vector  (string)
   //
   // end system
   libmesh_assert (io.reading());
   // Possibly clear data structures and start from scratch.
   if (read_header_in)
     this->clear ();
   // Figure out if we need to read infinite element information.
   // This will be true if the version string contains " with infinite elements"
   const bool read_ifem_info =
     (version.rfind(" with infinite elements") < version.size()) ||
     libMesh::on_command_line ("--read-ifem-systems");
   {
     // 5.)
     // Read the number of variables in the system
     unsigned int nv=0;
     if (this->processor_id() == 0)
       io.data (nv);
     this->comm().broadcast(nv);
     _written_var_indices.clear();
     _written_var_indices.resize(nv, 0);
     for (unsigned int var=0; var<nv; var++)
       {
         // 6.)
         // Read the name of the var-th variable
         std::string var_name;
         if (this->processor_id() == 0)
           io.data (var_name);
         this->comm().broadcast(var_name);
         // 6.1.)
         std::set<subdomain_id_type> domains;
         if (io.version() >= LIBMESH_VERSION_ID(0,7,2))
           {
             std::vector<subdomain_id_type> domain_array;
             if (this->processor_id() == 0)
               io.data (domain_array);
             for (const auto & id : domain_array)
               domains.insert(id);
           }
         this->comm().broadcast(domains);
         // 7.)
         // Read the approximation order(s) of the var-th variable
         int order=0;
         if (this->processor_id() == 0)
           io.data (order);
         this->comm().broadcast(order);
         // do the same for infinite element radial_order
         int rad_order=0;
         if (read_ifem_info)
           {
             if (this->processor_id() == 0)
               io.data(rad_order);
             this->comm().broadcast(rad_order);
           }
         // Read the finite element type of the var-th variable
         int fam=0;
         if (this->processor_id() == 0)
           io.data (fam);
         this->comm().broadcast(fam);
         FEType type;
         type.order  = static_cast<Order>(order);
         type.family = static_cast<FEFamily>(fam);
         // Check for incompatibilities.  The shape function indexing was
         // changed for the monomial and xyz finite element families to
         // simplify extension to arbitrary p.  The consequence is that
         // old restart files will not be read correctly.  This is expected
         // to be an unlikely occurence, but catch it anyway.
         if (read_legacy_format)
           if ((type.family == MONOMIAL || type.family == XYZ) &&
               ((type.order.get_order() > 2 && this->get_mesh().mesh_dimension() == 2) ||
                (type.order.get_order() > 1 && this->get_mesh().mesh_dimension() == 3)))
             {
               libmesh_here();
               libMesh::out << "*****************************************************************\n"
                            << "* WARNING: reading a potentially incompatible restart file!!!   *\n"
                            << "*  contact libmesh-users@lists.sourceforge.net for more details *\n"
                            << "*****************************************************************"
                            << std::endl;
             }
         // Read additional information for infinite elements
         int radial_fam=0;
         int i_map=0;
         if (read_ifem_info)
           {
             if (this->processor_id() == 0)
               io.data (radial_fam);
             this->comm().broadcast(radial_fam);
             if (this->processor_id() == 0)
               io.data (i_map);
             this->comm().broadcast(i_map);
           }
 #ifdef LIBMESH_ENABLE_INFINITE_ELEMENTS
         type.radial_order  = static_cast<Order>(rad_order);
         type.radial_family = static_cast<FEFamily>(radial_fam);
         type.inf_map       = static_cast<InfMapType>(i_map);
 #endif
         if (read_header_in)
           {
             if (domains.empty())
               _written_var_indices[var] = this->add_variable (var_name, type);
             else
               _written_var_indices[var] = this->add_variable (var_name, type, &domains);
           }
         else
           _written_var_indices[var] = this->variable_number(var_name);
       }
   }
   // 8.)
   // Read the number of additional vectors.
   unsigned int nvecs=0;
   if (this->processor_id() == 0)
     io.data (nvecs);
   this->comm().broadcast(nvecs);
   // If nvecs > 0, this means that write_additional_data
   // was true when this file was written.  We will need to
   // make use of this fact later.
   this->_additional_data_written = nvecs;
   for (unsigned int vec=0; vec<nvecs; vec++)
     {
       // 9.)
       // Read the name of the vec-th additional vector
       std::string vec_name;
       if (this->processor_id() == 0)
         io.data (vec_name);
       this->comm().broadcast(vec_name);
       if (read_additional_data)
         {
           // Systems now can handle adding post-initialization vectors
           //  libmesh_assert(this->_can_add_vectors);
           // Some systems may have added their own vectors already
           //  libmesh_assert_equal_to (this->_vectors.count(vec_name), 0);
           this->add_vector(vec_name);
         }
     }
 }
read_legacy_data()
void libMesh::System::read_legacy_data (Xdr & io, const bool read_additional_data = true) inherited
Reads additional data, namely vectors, for this System.
Deprecated:
The ability to read XDR data files in the old (aka "legacy") XDR format has been deprecated for many years, this capability may soon disappear altogether.
Definition at line 310 of file system_io.C.
References libMesh::System::_additional_data_written, libMesh::System::_vectors, libMesh::System::_written_var_indices, libMesh::Parallel::Communicator::broadcast(), libMesh::ParallelObject::comm(), libMesh::Xdr::data(), libMesh::System::get_mesh(), libMesh::DofObject::invalid_id, libMesh::System::n_dofs(), libMesh::System::n_vars(), libMesh::System::number(), libMesh::ParallelObject::processor_id(), libMesh::Xdr::reading(), libMesh::System::solution, and libMesh::zero.
 {
   libmesh_deprecated();
   // This method implements the output of the vectors
   // contained in this System object, embedded in the
   // output of an EquationSystems<T_sys>.
   //
   //   10.) The global solution vector, re-ordered to be node-major
   //       (More on this later.)
   //
   //      for each additional vector in the object
   //
   //      11.) The global additional vector, re-ordered to be
   //           node-major (More on this later.)
   libmesh_assert (io.reading());
   // read and reordering buffers
   std::vector<Number> global_vector;
   std::vector<Number> reordered_vector;
   // 10.)
   // Read and set the solution vector
   {
     if (this->processor_id() == 0)
       io.data (global_vector);
     this->comm().broadcast(global_vector);
     // Remember that the stored vector is node-major.
     // We need to put it into whatever application-specific
     // ordering we may have using the dof_map.
     reordered_vector.resize(global_vector.size());
     //libMesh::out << "global_vector.size()=" << global_vector.size() << std::endl;
     //libMesh::out << "this->n_dofs()=" << this->n_dofs() << std::endl;
     libmesh_assert_equal_to (global_vector.size(), this->n_dofs());
     dof_id_type cnt=0;
     const unsigned int sys = this->number();
     const unsigned int nv  = cast_int<unsigned int>
       (this->_written_var_indices.size());
     libmesh_assert_less_equal (nv, this->n_vars());
     for (unsigned int data_var=0; data_var<nv; data_var++)
       {
         const unsigned int var = _written_var_indices[data_var];
         // First reorder the nodal DOF values
         for (auto & node : this->get_mesh().node_ptr_range())
           for (unsigned int index=0; index<node->n_comp(sys,var); index++)
             {
               libmesh_assert_not_equal_to (node->dof_number(sys, var, index),
                                            DofObject::invalid_id);
               libmesh_assert_less (cnt, global_vector.size());
               reordered_vector[node->dof_number(sys, var, index)] =
                 global_vector[cnt++];
             }
         // Then reorder the element DOF values
         for (auto & elem : this->get_mesh().active_element_ptr_range())
           for (unsigned int index=0; index<elem->n_comp(sys,var); index++)
             {
               libmesh_assert_not_equal_to (elem->dof_number(sys, var, index),
                                            DofObject::invalid_id);
               libmesh_assert_less (cnt, global_vector.size());
               reordered_vector[elem->dof_number(sys, var, index)] =
                 global_vector[cnt++];
             }
       }
     *(this->solution) = reordered_vector;
   }
   // For each additional vector, simply go through the list.
   // ONLY attempt to do this IF additional data was actually
   // written to the file for this system (controlled by the
   // _additional_data_written flag).
   if (this->_additional_data_written)
     {
       const std::size_t nvecs = this->_vectors.size();
       // If the number of additional vectors written is non-zero, and
       // the number of additional vectors we have is non-zero, and
       // they don't match, then something is wrong and we can't be
       // sure we're reading data into the correct places.
       if (read_additional_data && nvecs &&
           nvecs != this->_additional_data_written)
         libmesh_error_msg
           ("Additional vectors in file do not match system");
       std::map<std::string, NumericVector<Number> *>::iterator
         pos = this->_vectors.begin();
       for (std::size_t i = 0; i != this->_additional_data_written; ++i)
         {
           // 11.)
           // Read the values of the vec-th additional vector.
           // Prior do _not_ clear, but fill with zero, since the
           // additional vectors _have_ to have the same size
           // as the solution vector
           std::fill (global_vector.begin(), global_vector.end(), libMesh::zero);
           if (this->processor_id() == 0)
             io.data (global_vector);
           // If read_additional_data==true and we have additional vectors,
           // then we will keep this vector data; otherwise we are going to
           // throw it away.
           if (read_additional_data && nvecs)
             {
               this->comm().broadcast(global_vector);
               // Remember that the stored vector is node-major.
               // We need to put it into whatever application-specific
               // ordering we may have using the dof_map.
               std::fill (reordered_vector.begin(),
                          reordered_vector.end(),
                          libMesh::zero);
               reordered_vector.resize(global_vector.size());
               libmesh_assert_equal_to (global_vector.size(), this->n_dofs());
               dof_id_type cnt=0;
               const unsigned int sys = this->number();
               const unsigned int nv  = cast_int<unsigned int>
                 (this->_written_var_indices.size());
               libmesh_assert_less_equal (nv, this->n_vars());
               for (unsigned int data_var=0; data_var<nv; data_var++)
                 {
                   const unsigned int var = _written_var_indices[data_var];
                   // First reorder the nodal DOF values
                   for (auto & node : this->get_mesh().node_ptr_range())
                     for (unsigned int index=0; index<node->n_comp(sys,var); index++)
                       {
                         libmesh_assert_not_equal_to (node->dof_number(sys, var, index),
                                                      DofObject::invalid_id);
                         libmesh_assert_less (cnt, global_vector.size());
                         reordered_vector[node->dof_number(sys, var, index)] =
                           global_vector[cnt++];
                       }
                   // Then reorder the element DOF values
                   for (auto & elem : this->get_mesh().active_element_ptr_range())
                     for (unsigned int index=0; index<elem->n_comp(sys,var); index++)
                       {
                         libmesh_assert_not_equal_to (elem->dof_number(sys, var, index),
                                                      DofObject::invalid_id);
                         libmesh_assert_less (cnt, global_vector.size());
                         reordered_vector[elem->dof_number(sys, var, index)] =
                           global_vector[cnt++];
                       }
                 }
               // use the overloaded operator=(std::vector) to assign the values
               *(pos->second) = reordered_vector;
             }
           // If we've got vectors then we need to be iterating through
           // those too
           if (pos != this->_vectors.end())
             ++pos;
         }
     } // end if (_additional_data_written)
 }
read_parallel_data() [1/2]
template<typename InValType > void libMesh::System::read_parallel_data (Xdr & io, const bool read_additional_data) inherited
Reads additional data, namely vectors, for this System. This method may safely be called on a distributed-memory mesh. This method will read an individual file for each processor in the simulation where the local solution components for that processor are stored.
This method implements the output of the vectors contained in this System object, embedded in the output of an EquationSystems<T_sys>.
9.) The global solution vector, re-ordered to be node-major (More on this later.)
for each additional vector in the object
10.) The global additional vector, re-ordered to be node-major (More on this later.)
Note that the actual IO is handled through the Xdr class (to be renamed later?) which provides a uniform interface to both the XDR (eXternal Data Representation) interface and standard ASCII output. Thus this one section of code will read XDR or ASCII files with no changes.
Definition at line 493 of file system_io.C.
References libMesh::System::_additional_data_written, libMesh::System::_vectors, libMesh::System::_written_var_indices, libMesh::Xdr::data(), libMesh::FEType::family, libMesh::System::get_dof_map(), libMesh::System::get_mesh(), libMesh::DofObject::invalid_id, libMesh::Xdr::is_open(), libMesh::ParallelObject::n_processors(), libMesh::System::n_vars(), libMesh::System::number(), libMesh::ParallelObject::processor_id(), libMesh::Xdr::reading(), libMesh::SCALAR, libMesh::DofMap::SCALAR_dof_indices(), libMesh::System::solution, libMesh::Variable::type(), and libMesh::System::variable().
 {
   // PerfLog pl("IO Performance",false);
   // pl.push("read_parallel_data");
   dof_id_type total_read_size = 0;
   libmesh_assert (io.reading());
   libmesh_assert (io.is_open());
   // build the ordered nodes and element maps.
   // when writing/reading parallel files we need to iterate
   // over our nodes/elements in order of increasing global id().
   // however, this is not guaranteed to be ordering we obtain
   // by using the node_iterators/element_iterators directly.
   // so build a set, sorted by id(), that provides the ordering.
   // further, for memory economy build the set but then transfer
   // its contents to vectors, which will be sorted.
   std::vector<const DofObject *> ordered_nodes, ordered_elements;
   {
     std::set<const DofObject *, CompareDofObjectsByID>
       ordered_nodes_set (this->get_mesh().local_nodes_begin(),
                          this->get_mesh().local_nodes_end());
     ordered_nodes.insert(ordered_nodes.end(),
                          ordered_nodes_set.begin(),
                          ordered_nodes_set.end());
   }
   {
     std::set<const DofObject *, CompareDofObjectsByID>
       ordered_elements_set (this->get_mesh().local_elements_begin(),
                             this->get_mesh().local_elements_end());
     ordered_elements.insert(ordered_elements.end(),
                             ordered_elements_set.begin(),
                             ordered_elements_set.end());
   }
   //  std::vector<Number> io_buffer;
   std::vector<InValType> io_buffer;
   // 9.)
   //
   // Actually read the solution components
   // for the ith system to disk
   io.data(io_buffer);
   total_read_size += cast_int<dof_id_type>(io_buffer.size());
   const unsigned int sys_num = this->number();
   const unsigned int nv      = cast_int<unsigned int>
     (this->_written_var_indices.size());
   libmesh_assert_less_equal (nv, this->n_vars());
   dof_id_type cnt=0;
   // Loop over each non-SCALAR variable and each node, and read out the value.
   for (unsigned int data_var=0; data_var<nv; data_var++)
     {
       const unsigned int var = _written_var_indices[data_var];
       if (this->variable(var).type().family != SCALAR)
         {
           // First read the node DOF values
           for (const auto & node : ordered_nodes)
             for (unsigned int comp=0; comp<node->n_comp(sys_num, var); comp++)
               {
                 libmesh_assert_not_equal_to (node->dof_number(sys_num, var, comp),
                                              DofObject::invalid_id);
                 libmesh_assert_less (cnt, io_buffer.size());
                 this->solution->set(node->dof_number(sys_num, var, comp), io_buffer[cnt++]);
               }
           // Then read the element DOF values
           for (const auto & elem : ordered_elements)
             for (unsigned int comp=0; comp<elem->n_comp(sys_num, var); comp++)
               {
                 libmesh_assert_not_equal_to (elem->dof_number(sys_num, var, comp),
                                              DofObject::invalid_id);
                 libmesh_assert_less (cnt, io_buffer.size());
                 this->solution->set(elem->dof_number(sys_num, var, comp), io_buffer[cnt++]);
               }
         }
     }
   // Finally, read the SCALAR variables on the last processor
   for (unsigned int data_var=0; data_var<nv; data_var++)
     {
       const unsigned int var = _written_var_indices[data_var];
       if (this->variable(var).type().family == SCALAR)
         {
           if (this->processor_id() == (this->n_processors()-1))
             {
               const DofMap & dof_map = this->get_dof_map();
               std::vector<dof_id_type> SCALAR_dofs;
               dof_map.SCALAR_dof_indices(SCALAR_dofs, var);
               for (std::size_t i=0; i<SCALAR_dofs.size(); i++)
                 this->solution->set(SCALAR_dofs[i], io_buffer[cnt++]);
             }
         }
     }
   // And we're done setting solution entries
   this->solution->close();
   // For each additional vector, simply go through the list.
   // ONLY attempt to do this IF additional data was actually
   // written to the file for this system (controlled by the
   // _additional_data_written flag).
   if (this->_additional_data_written)
     {
       const std::size_t nvecs = this->_vectors.size();
       // If the number of additional vectors written is non-zero, and
       // the number of additional vectors we have is non-zero, and
       // they don't match, then something is wrong and we can't be
       // sure we're reading data into the correct places.
       if (read_additional_data && nvecs &&
           nvecs != this->_additional_data_written)
         libmesh_error_msg
           ("Additional vectors in file do not match system");
       std::map<std::string, NumericVector<Number> *>::const_iterator
         pos = _vectors.begin();
       for (std::size_t i = 0; i != this->_additional_data_written; ++i)
         {
           cnt=0;
           io_buffer.clear();
           // 10.)
           //
           // Actually read the additional vector components
           // for the ith system from disk
           io.data(io_buffer);
           total_read_size += cast_int<dof_id_type>(io_buffer.size());
           // If read_additional_data==true and we have additional vectors,
           // then we will keep this vector data; otherwise we are going to
           // throw it away.
           if (read_additional_data && nvecs)
             {
               // Loop over each non-SCALAR variable and each node, and read out the value.
               for (unsigned int data_var=0; data_var<nv; data_var++)
                 {
                   const unsigned int var = _written_var_indices[data_var];
                   if (this->variable(var).type().family != SCALAR)
                     {
                       // First read the node DOF values
                       for (const auto & node : ordered_nodes)
                         for (unsigned int comp=0; comp<node->n_comp(sys_num, var); comp++)
{
                             libmesh_assert_not_equal_to (node->dof_number(sys_num, var, comp),
                                                          DofObject::invalid_id);
                             libmesh_assert_less (cnt, io_buffer.size());
                             pos->second->set(node->dof_number(sys_num, var, comp), io_buffer[cnt++]);
                           }
                       // Then read the element DOF values
                       for (const auto & elem : ordered_elements)
                         for (unsigned int comp=0; comp<elem->n_comp(sys_num, var); comp++)
{
                             libmesh_assert_not_equal_to (elem->dof_number(sys_num, var, comp),
                                                          DofObject::invalid_id);
                             libmesh_assert_less (cnt, io_buffer.size());
                             pos->second->set(elem->dof_number(sys_num, var, comp), io_buffer[cnt++]);
                           }
                     }
                 }
               // Finally, read the SCALAR variables on the last processor
               for (unsigned int data_var=0; data_var<nv; data_var++)
                 {
                   const unsigned int var = _written_var_indices[data_var];
                   if (this->variable(var).type().family == SCALAR)
                     {
                       if (this->processor_id() == (this->n_processors()-1))
{
                           const DofMap & dof_map = this->get_dof_map();
                           std::vector<dof_id_type> SCALAR_dofs;
                           dof_map.SCALAR_dof_indices(SCALAR_dofs, var);
                           for (std::size_t sd=0; sd<SCALAR_dofs.size(); sd++)
                             pos->second->set(SCALAR_dofs[sd], io_buffer[cnt++]);
                         }
                     }
                 }
               // And we're done setting entries for this variable
               pos->second->close();
             }
           // If we've got vectors then we need to be iterating through
           // those too
           if (pos != this->_vectors.end())
             ++pos;
         }
     }
   // const Real
   //   dt   = pl.get_elapsed_time(),
   //   rate = total_read_size*sizeof(Number)/dt;
   // libMesh::err << "Read " << total_read_size << " \"Number\" values\n"
   //     << " Elapsed time = " << dt << '\n'
   //     << " Rate = " << rate/1.e6 << "(MB/sec)\n\n";
   // pl.pop("read_parallel_data");
 }
read_parallel_data() [2/2]
template void libMesh::System::read_parallel_data< Real > (Xdr & io, const bool read_additional_data) inline inherited
Non-templated version for backward compatibility.
Reads additional data, namely vectors, for this System. This method may safely be called on a distributed-memory mesh. This method will read an individual file for each processor in the simulation where the local solution components for that processor are stored.
Definition at line 1299 of file system.h.
   { read_parallel_data<Number>(io, read_additional_data); }
read_serialized_data() [1/2]
template<typename InValType > void libMesh::System::read_serialized_data (Xdr & io, const bool read_additional_data = true) inherited
Reads additional data, namely vectors, for this System. This method may safely be called on a distributed-memory mesh.
Definition at line 725 of file system_io.C.
References libMesh::System::_additional_data_written, libMesh::System::_vectors, libMesh::ParallelObject::processor_id(), and libMesh::System::solution.
 {
   // This method implements the input of the vectors
   // contained in this System object, embedded in the
   // output of an EquationSystems<T_sys>.
   //
   //   10.) The global solution vector, re-ordered to be node-major
   //       (More on this later.)
   //
   //      for each additional vector in the object
   //
   //      11.) The global additional vector, re-ordered to be
   //          node-major (More on this later.)
   parallel_object_only();
   std::string comment;
   // PerfLog pl("IO Performance",false);
   // pl.push("read_serialized_data");
   // std::size_t total_read_size = 0;
   // 10.)
   // Read the global solution vector
   {
     // total_read_size +=
     this->read_serialized_vector<InValType>(io, this->solution.get());
     // get the comment
     if (this->processor_id() == 0)
       io.comment (comment);
   }
   // 11.)
   // Only read additional vectors if data is available, and only use
   // that data to fill our vectors if the user requested it.
   if (this->_additional_data_written)
     {
       const std::size_t nvecs = this->_vectors.size();
       // If the number of additional vectors written is non-zero, and
       // the number of additional vectors we have is non-zero, and
       // they don't match, then we can't read additional vectors
       // and be sure we're reading data into the correct places.
       if (read_additional_data && nvecs &&
           nvecs != this->_additional_data_written)
         libmesh_error_msg
           ("Additional vectors in file do not match system");
       std::map<std::string, NumericVector<Number> *>::const_iterator
         pos = _vectors.begin();
       for (std::size_t i = 0; i != this->_additional_data_written; ++i)
         {
           // Read data, but only put it into a vector if we've been
           // asked to and if we have a corresponding vector to read.
           // total_read_size +=
           this->read_serialized_vector<InValType>
             (io, (read_additional_data && nvecs) ? pos->second : nullptr);
           // get the comment
           if (this->processor_id() == 0)
             io.comment (comment);
           // If we've got vectors then we need to be iterating through
           // those too
           if (pos != this->_vectors.end())
             ++pos;
         }
     }
   // const Real
   //   dt   = pl.get_elapsed_time(),
   //   rate = total_read_size*sizeof(Number)/dt;
   // libMesh::out << "Read " << total_read_size << " \"Number\" values\n"
   //     << " Elapsed time = " << dt << '\n'
   //     << " Rate = " << rate/1.e6 << "(MB/sec)\n\n";
   // pl.pop("read_serialized_data");
 }
read_serialized_data() [2/2]
template void libMesh::System::read_serialized_data< Real > (Xdr & io, const bool read_additional_data = true) inline inherited
Non-templated version for backward compatibility.
Reads additional data, namely vectors, for this System. This method may safely be called on a distributed-memory mesh.
Definition at line 1257 of file system.h.
   { read_serialized_data<Number>(io, read_additional_data); }
read_serialized_vectors() [1/2]
template<typename InValType > std::size_t libMesh::System::read_serialized_vectors (Xdr & io, const std::vector< NumericVector< Number > *> & vectors) const inherited
Read a number of identically distributed vectors. This method allows for optimization for the multiple vector case by only communicating the metadata once.
Definition at line 2203 of file system_io.C.
References libMesh::Xdr::data(), libMesh::FEType::family, libMesh::System::get_mesh(), libMesh::MeshBase::n_elem(), libMesh::MeshTools::n_elem(), n_nodes, libMesh::MeshBase::n_nodes(), libMesh::System::n_vars(), libMesh::ParallelObject::processor_id(), libMesh::System::read_SCALAR_dofs(), libMesh::System::read_serialized_blocked_dof_objects(), libMesh::Xdr::reading(), libMesh::SCALAR, libMesh::Variable::type(), and libMesh::System::variable().
 {
   parallel_object_only();
   // Error checking
   // #ifndef NDEBUG
   //   // In parallel we better be reading a parallel vector -- if not
   //   // we will not set all of its components below!!
   //   if (this->n_processors() > 1)
   //     {
   //       libmesh_assert (vec.type() == PARALLEL ||
   //       vec.type() == GHOSTED);
   //     }
   // #endif
   libmesh_assert (io.reading());
   if (this->processor_id() == 0)
     {
       // sizes
       unsigned int num_vecs=0;
       dof_id_type vector_length=0;
       // Get the number of vectors
       io.data(num_vecs);
       // Get the buffer size
       io.data(vector_length);
       libmesh_assert_equal_to (num_vecs, vectors.size());
       if (num_vecs != 0)
         {
           libmesh_assert_not_equal_to (vectors[0], 0);
           libmesh_assert_equal_to     (vectors[0]->size(), vector_length);
         }
     }
   // no need to actually communicate these.
   // this->comm().broadcast(num_vecs);
   // this->comm().broadcast(vector_length);
   // Cache these - they are not free!
   const dof_id_type
     n_nodes = this->get_mesh().n_nodes(),
     n_elem  = this->get_mesh().n_elem();
   std::size_t read_length = 0;
   //---------------------------------
   // Collect the values for all nodes
   read_length +=
     this->read_serialized_blocked_dof_objects (n_nodes,
                                                this->get_mesh().local_nodes_begin(),
                                                this->get_mesh().local_nodes_end(),
                                                InValType(),
                                                io,
                                                vectors);
   //------------------------------------
   // Collect the values for all elements
   read_length +=
     this->read_serialized_blocked_dof_objects (n_elem,
                                                this->get_mesh().local_elements_begin(),
                                                this->get_mesh().local_elements_end(),
                                                InValType(),
                                                io,
                                                vectors);
   //-------------------------------------------
   // Finally loop over all the SCALAR variables
   for (std::size_t vec=0; vec<vectors.size(); vec++)
     for (unsigned int var=0; var<this->n_vars(); var++)
       if (this->variable(var).type().family == SCALAR)
         {
           libmesh_assert_not_equal_to (vectors[vec], 0);
           read_length +=
             this->read_SCALAR_dofs (var, io, vectors[vec]);
         }
   //---------------------------------------
   // last step - must close all the vectors
   for (std::size_t vec=0; vec<vectors.size(); vec++)
     {
       libmesh_assert_not_equal_to (vectors[vec], 0);
       vectors[vec]->close();
     }
   return read_length;
 }
read_serialized_vectors() [2/2]
template std::size_t libMesh::System::read_serialized_vectors< Real > (Xdr & io, const std::vector< NumericVector< Number > *> & vectors) const inline inherited
Non-templated version for backward compatibility.
Read a number of identically distributed vectors. This method allows for optimization for the multiple vector case by only communicating the metadata once.
Definition at line 1277 of file system.h.
   { return read_serialized_vectors<Number>(io, vectors); }
reinit()
void libMesh::EigenSystem::reinit () override virtual
Reinitializes the member data fields associated with the system, so that, e.g., assemble() may be used.
Reimplemented from libMesh::System.
Definition at line 165 of file eigen_system.C.
References _is_generalized_eigenproblem, libMesh::DofMap::clear_sparsity(), libMesh::DofMap::compute_sparsity(), libMesh::System::get_dof_map(), libMesh::System::get_mesh(), matrix_A, matrix_B, and libMesh::System::reinit().
 {
   // initialize parent data
   Parent::reinit();
   // Clear the matrices
   matrix_A->clear();
   if (_is_generalized_eigenproblem)
     matrix_B->clear();
   DofMap & dof_map = this->get_dof_map();
   // Clear the sparsity pattern
   dof_map.clear_sparsity();
   // Compute the sparsity pattern for the current
   // mesh and DOF distribution.  This also updates
   // both matrices, \p DofMap now knows them
   dof_map.compute_sparsity(this->get_mesh());
   matrix_A->init();
   matrix_A->zero();
   if (_is_generalized_eigenproblem)
     {
       matrix_B->init();
       matrix_B->zero();
     }
 }
reinit_constraints()
void libMesh::System::reinit_constraints () virtual inherited
Reinitializes the constraints for this system.
Definition at line 397 of file system.C.
References libMesh::System::_mesh, libMesh::DofMap::create_dof_constraints(), libMesh::System::get_dof_map(), libMesh::DofMap::prepare_send_list(), libMesh::DofMap::process_constraints(), libMesh::System::time, and libMesh::System::user_constrain().
Referenced by libMesh::EquationSystems::allgather(), libMesh::System::init_data(), and libMesh::EquationSystems::reinit_solutions().
 {
 #ifdef LIBMESH_ENABLE_CONSTRAINTS
   get_dof_map().create_dof_constraints(_mesh, this->time);
   user_constrain();
   get_dof_map().process_constraints(_mesh);
 #endif
   get_dof_map().prepare_send_list();
 }
remove_vector()
void libMesh::System::remove_vector (const std::string & vec_name) inherited
Removes the additional vector vec_name from this system
Definition at line 699 of file system.C.
References libMesh::System::_vector_is_adjoint, libMesh::System::_vector_projections, libMesh::System::_vector_types, and libMesh::System::_vectors.
 {
   vectors_iterator pos = _vectors.find(vec_name);
   //Return if the vector does not exist
   if (pos == _vectors.end())
     return;
   delete pos->second;
   _vectors.erase(pos);
   _vector_projections.erase(vec_name);
   _vector_is_adjoint.erase(vec_name);
   _vector_types.erase(vec_name);
 }
request_vector() [1/4]
const NumericVector< Number > * libMesh::System::request_vector (const std::string & vec_name) const inherited
Returns
A const pointer to the vector if this System has a vector associated with the given name, nullptr otherwise.
Definition at line 716 of file system.C.
References libMesh::System::_vectors.
Referenced by libMesh::UniformRefinementEstimator::_estimate_error().
 {
   const_vectors_iterator pos = _vectors.find(vec_name);
   if (pos == _vectors.end())
     return nullptr;
   return pos->second;
 }
request_vector() [2/4]
NumericVector< Number > * libMesh::System::request_vector (const std::string & vec_name) inherited
Returns
A pointer to the vector if this System has a vector associated with the given name, nullptr otherwise.
Definition at line 728 of file system.C.
References libMesh::System::_vectors.
 {
   vectors_iterator pos = _vectors.find(vec_name);
   if (pos == _vectors.end())
     return nullptr;
   return pos->second;
 }
request_vector() [3/4]
const NumericVector< Number > * libMesh::System::request_vector (const unsigned int vec_num) const inherited
Returns
A const pointer to this system's additional vector number vec_num (where the vectors are counted starting with 0), or nullptr if the system has no such vector.
Definition at line 740 of file system.C.
References libMesh::System::vectors_begin(), and libMesh::System::vectors_end().
 {
   const_vectors_iterator v = vectors_begin();
   const_vectors_iterator v_end = vectors_end();
   unsigned int num = 0;
   while ((num<vec_num) && (v!=v_end))
     {
       num++;
       ++v;
     }
   if (v==v_end)
     return nullptr;
   return v->second;
 }
request_vector() [4/4]
NumericVector< Number > * libMesh::System::request_vector (const unsigned int vec_num) inherited
Returns
A writable pointer to this system's additional vector number vec_num (where the vectors are counted starting with 0), or nullptr if the system has no such vector.
Definition at line 757 of file system.C.
References libMesh::System::vectors_begin(), and libMesh::System::vectors_end().
 {
   vectors_iterator v = vectors_begin();
   vectors_iterator v_end = vectors_end();
   unsigned int num = 0;
   while ((num<vec_num) && (v!=v_end))
     {
       num++;
       ++v;
     }
   if (v==v_end)
     return nullptr;
   return v->second;
 }
restrict_solve_to()
void libMesh::System::restrict_solve_to (const SystemSubset * subset, const SubsetSolveMode subset_solve_mode = SUBSET_ZERO) virtual inherited
After calling this method, any solve will be restricted to the given subdomain. To disable this mode, call this method with subset being a nullptr.
Reimplemented in libMesh::LinearImplicitSystem.
Definition at line 453 of file system.C.
 {
   if (subset != nullptr)
     libmesh_not_implemented();
 }
restrict_vectors()
void libMesh::System::restrict_vectors () virtual inherited
Restrict vectors after the mesh has coarsened
Definition at line 324 of file system.C.
References libMesh::System::_dof_map, libMesh::System::_solution_projection, libMesh::System::_vector_projections, libMesh::System::_vector_types, libMesh::System::_vectors, libMesh::System::current_local_solution, libMesh::GHOSTED, libMesh::System::n_dofs(), libMesh::System::n_local_dofs(), libMesh::PARALLEL, libMesh::System::project_vector(), libMesh::System::solution, and libMesh::System::vector_is_adjoint().
Referenced by libMesh::System::prolong_vectors(), and libMesh::EquationSystems::reinit_solutions().
 {
 #ifdef LIBMESH_ENABLE_AMR
   // Restrict the _vectors on the coarsened cells
   for (auto & pr : _vectors)
     {
       NumericVector<Number> * v = pr.second;
       if (_vector_projections[pr.first])
         {
           this->project_vector (*v, this->vector_is_adjoint(pr.first));
         }
       else
         {
           ParallelType type = _vector_types[pr.first];
           if (type == GHOSTED)
             {
 #ifdef LIBMESH_ENABLE_GHOSTED
               pr.second->init (this->n_dofs(), this->n_local_dofs(),
                                _dof_map->get_send_list(), false,
                                GHOSTED);
 #else
               libmesh_error_msg("Cannot initialize ghosted vectors when they are not enabled.");
 #endif
             }
           else
             pr.second->init (this->n_dofs(), this->n_local_dofs(), false, type);
         }
     }
   const std::vector<dof_id_type> & send_list = _dof_map->get_send_list ();
   // Restrict the solution on the coarsened cells
   if (_solution_projection)
     this->project_vector (*solution);
   // Or at least make sure the solution vector is the correct size
   else
     solution->init (this->n_dofs(), this->n_local_dofs(), true, PARALLEL);
 #ifdef LIBMESH_ENABLE_GHOSTED
   current_local_solution->init(this->n_dofs(),
                                this->n_local_dofs(), send_list,
                                false, GHOSTED);
 #else
   current_local_solution->init(this->n_dofs());
 #endif
   if (_solution_projection)
     solution->localize (*current_local_solution, send_list);
 #endif // LIBMESH_ENABLE_AMR
 }
sensitivity_solve()
std::pair< unsigned int, Real > libMesh::System::sensitivity_solve (const ParameterVector & parameters) inline virtual inherited
Solves the sensitivity system, for the provided parameters. Must be overridden in derived systems.
Returns
A pair with the total number of linear iterations performed and the (sum of the) final residual norms
This method is only implemented in some derived classes.
Reimplemented in libMesh::ImplicitSystem.
Definition at line 2285 of file system.h.
 {
   libmesh_not_implemented();
 }
set_adjoint_already_solved()
void libMesh::System::set_adjoint_already_solved (bool setting) inline inherited
Setter for the adjoint_already_solved boolean
Definition at line 394 of file system.h.
References libMesh::System::adjoint_already_solved.
   { adjoint_already_solved = setting;}
set_basic_system_only()
void libMesh::System::set_basic_system_only () inline inherited
Sets the system to be "basic only": i.e. advanced system components such as ImplicitSystem matrices may not be initialized. This is useful for efficiency in certain utility programs that never use System::solve(). This method must be called after the System or derived class is created but before it is initialized; e.g. from within EquationSystems::read()
Definition at line 2097 of file system.h.
References libMesh::System::_basic_system_only.
Referenced by libMesh::EquationSystems::_read_impl().
 {
   _basic_system_only = true;
 }
set_eigenproblem_type()
void libMesh::EigenSystem::set_eigenproblem_type (EigenProblemType ept)
Sets the type of the current eigen problem.
Definition at line 77 of file eigen_system.C.
References _eigen_problem_type, eigen_solver, libMesh::GHEP, libMesh::GHIEP, libMesh::GNHEP, libMesh::HEP, and libMesh::NHEP.
 {
   _eigen_problem_type = ept;
   eigen_solver->set_eigenproblem_type(ept);
   // libMesh::out << "The Problem type is set to be: " << std::endl;
   switch (_eigen_problem_type)
     {
     case HEP:
       // libMesh::out << "Hermitian" << std::endl;
       break;
     case NHEP:
       // libMesh::out << "Non-Hermitian" << std::endl;
       break;
     case GHEP:
       // libMesh::out << "Generalized Hermitian" << std::endl;
       break;
     case GNHEP:
       // libMesh::out << "Generalized Non-Hermitian" << std::endl;
       break;
     case GHIEP:
       // libMesh::out << "Generalized indefinite Hermitian" << std::endl;
       break;
     default:
       // libMesh::out << "not properly specified" << std::endl;
       libmesh_error_msg("Unrecognized _eigen_problem_type = " << _eigen_problem_type);
     }
 }
set_n_converged()
void libMesh::EigenSystem::set_n_converged (unsigned int nconv) inline protected
Set the _n_converged_eigenpairs member, useful for subclasses of EigenSystem.
Definition at line 186 of file eigen_system.h.
References _n_converged_eigenpairs.
Referenced by libMesh::CondensedEigenSystem::solve().
   { _n_converged_eigenpairs = nconv; }
set_n_iterations()
void libMesh::EigenSystem::set_n_iterations (unsigned int its) inline protected
Set the _n_iterations member, useful for subclasses of EigenSystem.
Definition at line 193 of file eigen_system.h.
References _n_iterations.
Referenced by libMesh::CondensedEigenSystem::solve().
   { _n_iterations = its;}
set_vector_as_adjoint()
void libMesh::System::set_vector_as_adjoint (const std::string & vec_name, int qoi_num) inherited
Allows one to set the QoI index controlling whether the vector identified by vec_name represents a solution from the adjoint (qoi_num >= 0) or primal (qoi_num == -1) space. This becomes significant if those spaces have differing heterogeneous Dirichlet constraints.
qoi_num == -2 can be used to indicate a vector which should not be affected by constraints during projection operations.
Definition at line 885 of file system.C.
References libMesh::System::_vector_is_adjoint.
Referenced by libMesh::System::add_adjoint_solution(), and libMesh::System::add_weighted_sensitivity_adjoint_solution().
 {
   // We reserve -1 for vectors which get primal constraints, -2 for
   // vectors which get no constraints
   libmesh_assert_greater_equal(qoi_num, -2);
   _vector_is_adjoint[vec_name] = qoi_num;
 }
set_vector_preservation()
void libMesh::System::set_vector_preservation (const std::string & vec_name, bool preserve) inherited
Allows one to set the boolean controlling whether the vector identified by vec_name should be "preserved": projected to new meshes, saved, etc.
Definition at line 867 of file system.C.
References libMesh::System::_vector_projections.
 {
   _vector_projections[vec_name] = preserve;
 }
solve()
void libMesh::EigenSystem::solve () override virtual
Assembles & solves the eigen system.
Reimplemented from libMesh::System.
Reimplemented in libMesh::CondensedEigenSystem.
Definition at line 198 of file eigen_system.C.
References _is_generalized_eigenproblem, _n_converged_eigenpairs, _n_iterations, assemble(), libMesh::System::assemble_before_solve, eigen_solver, libMesh::Parameters::get(), libMesh::System::get_equation_systems(), libMesh::Parameters::have_parameter(), matrix_A, matrix_B, libMesh::EquationSystems::parameters, and libMesh::Real.
Referenced by libMesh::CondensedEigenSystem::solve().
 {
   // A reference to the EquationSystems
   EquationSystems & es = this->get_equation_systems();
   // check that necessary parameters have been set
   libmesh_assert (es.parameters.have_parameter<unsigned int>("eigenpairs"));
   libmesh_assert (es.parameters.have_parameter<unsigned int>("basis vectors"));
   if (this->assemble_before_solve)
     // Assemble the linear system
     this->assemble ();
   // Get the tolerance for the solver and the maximum
   // number of iterations. Here, we simply adopt the linear solver
   // specific parameters.
   const Real tol            =
     es.parameters.get<Real>("linear solver tolerance");
   const unsigned int maxits =
     es.parameters.get<unsigned int>("linear solver maximum iterations");
   const unsigned int nev    =
     es.parameters.get<unsigned int>("eigenpairs");
   const unsigned int ncv    =
     es.parameters.get<unsigned int>("basis vectors");
   std::pair<unsigned int, unsigned int> solve_data;
   // call the solver depending on the type of eigenproblem
   // Generalized eigenproblem
   if (_is_generalized_eigenproblem)
     solve_data = eigen_solver->solve_generalized (*matrix_A, *matrix_B, nev, ncv, tol, maxits);
   // Standard eigenproblem
   else
     {
       libmesh_assert (!matrix_B);
       solve_data = eigen_solver->solve_standard (*matrix_A, nev, ncv, tol, maxits);
     }
   this->_n_converged_eigenpairs = solve_data.first;
   this->_n_iterations           = solve_data.second;
 }
system()
sys_type& libMesh::EigenSystem::system () inline
Returns
A reference to *this.
Definition at line 84 of file eigen_system.h.
 { return *this; }
system_type()
virtual std::string libMesh::EigenSystem::system_type () const inline override virtual
Returns
"Eigen". Helps in identifying the system type in an equation system file.
Reimplemented from libMesh::System.
Definition at line 118 of file eigen_system.h.
 { return "Eigen"; }
update()
void libMesh::System::update () virtual inherited
Update the local values to reflect the solution on neighboring processors.
Definition at line 408 of file system.C.
References libMesh::System::_dof_map, libMesh::System::current_local_solution, and libMesh::System::solution.
Referenced by libMesh::__libmesh_petsc_diff_solver_jacobian(), libMesh::__libmesh_petsc_diff_solver_residual(), libMesh::UniformRefinementEstimator::_estimate_error(), libMesh::FEMSystem::assemble_qoi(), libMesh::FEMSystem::assemble_qoi_derivative(), libMesh::NonlinearImplicitSystem::assembly(), libMesh::EquationSystems::build_parallel_elemental_solution_vector(), libMesh::EquationSystems::build_parallel_solution_vector(), libMesh::NewmarkSolver::compute_initial_accel(), libMesh::Problem_Interface::computeF(), libMesh::Problem_Interface::computeJacobian(), libMesh::Problem_Interface::computePreconditioner(), libMesh::ExodusII_IO::copy_elemental_solution(), libMesh::ExodusII_IO::copy_nodal_solution(), libMesh::GMVIO::copy_nodal_solution(), DMlibMeshFunction(), DMlibMeshJacobian(), libMesh::AdjointRefinementEstimator::estimate_error(), libMesh::CondensedEigenSystem::get_eigenpair(), libMesh::libmesh_petsc_snes_jacobian(), libMesh::libmesh_petsc_snes_residual_helper(), libMesh::NewtonSolver::line_search(), libMesh::FEMSystem::mesh_position_get(), libMesh::FEMSystem::postprocess(), libMesh::ImplicitSystem::qoi_parameter_hessian(), libMesh::NewtonSolver::solve(), libMesh::ExplicitSystem::solve(), libMesh::LinearImplicitSystem::solve(), libMesh::NonlinearImplicitSystem::solve(), and libMesh::OptimizationSystem::solve().
 {
   libmesh_assert(solution->closed());
   const std::vector<dof_id_type> & send_list = _dof_map->get_send_list ();
   // Check sizes
   libmesh_assert_equal_to (current_local_solution->size(), solution->size());
   // More processors than elements => empty send_list
   //  libmesh_assert (!send_list.empty());
   libmesh_assert_less_equal (send_list.size(), solution->size());
   // Create current_local_solution from solution.  This will
   // put a local copy of solution into current_local_solution.
   // Only the necessary values (specified by the send_list)
   // are copied to minimize communication
   solution->localize (*current_local_solution, send_list);
 }
update_global_solution() [1/2]
void libMesh::System::update_global_solution (std::vector< Number > & global_soln) const inherited
Fill the input vector global_soln so that it contains the global solution on all processors. Requires communication with all other processors.
Definition at line 642 of file system.C.
References libMesh::System::solution.
Referenced by libMesh::ExactSolution::_compute_error(), libMesh::EquationSystems::build_discontinuous_solution_vector(), and libMesh::ExactErrorEstimator::estimate_error().
 {
   global_soln.resize (solution->size());
   solution->localize (global_soln);
 }
update_global_solution() [2/2]
void libMesh::System::update_global_solution (std::vector< Number > & global_soln, const processor_id_type dest_proc) const inherited
Fill the input vector global_soln so that it contains the global solution on processor dest_proc. Requires communication with all other processors.
Definition at line 651 of file system.C.
References libMesh::System::solution.
 {
   global_soln.resize        (solution->size());
   solution->localize_to_one (global_soln, dest_proc);
 }
user_assembly()
void libMesh::System::user_assembly () virtual inherited
Calls user's attached assembly function, or is overridden by the user in derived classes.
Definition at line 1932 of file system.C.
References libMesh::System::_assemble_system_function, libMesh::System::_assemble_system_object, libMesh::System::_equation_systems, libMesh::System::Assembly::assemble(), and libMesh::System::name().
Referenced by libMesh::System::assemble().
 {
   // Call the user-provided assembly function,
   // if it was provided
   if (_assemble_system_function != nullptr)
     this->_assemble_system_function (_equation_systems, this->name());
   // ...or the user-provided assembly object.
   else if (_assemble_system_object != nullptr)
     this->_assemble_system_object->assemble();
 }
user_constrain()
void libMesh::System::user_constrain () virtual inherited
Calls user's attached constraint function, or is overridden by the user in derived classes.
Definition at line 1946 of file system.C.
References libMesh::System::_constrain_system_function, libMesh::System::_constrain_system_object, libMesh::System::_equation_systems, libMesh::System::Constraint::constrain(), and libMesh::System::name().
Referenced by libMesh::System::reinit_constraints().
 {
   // Call the user-provided constraint function,
   // if it was provided
   if (_constrain_system_function!= nullptr)
     this->_constrain_system_function(_equation_systems, this->name());
   // ...or the user-provided constraint object.
   else if (_constrain_system_object != nullptr)
     this->_constrain_system_object->constrain();
 }
user_initialization()
void libMesh::System::user_initialization () virtual inherited
Calls user's attached initialization function, or is overridden by the user in derived classes.
Definition at line 1918 of file system.C.
References libMesh::System::_equation_systems, libMesh::System::_init_system_function, libMesh::System::_init_system_object, libMesh::System::Initialization::initialize(), and libMesh::System::name().
Referenced by libMesh::System::init(), and libMesh::NewmarkSystem::initial_conditions().
 {
   // Call the user-provided initialization function,
   // if it was provided
   if (_init_system_function != nullptr)
     this->_init_system_function (_equation_systems, this->name());
   // ...or the user-provided initialization object.
   else if (_init_system_object != nullptr)
     this->_init_system_object->initialize();
 }
user_QOI()
void libMesh::System::user_QOI (const QoISet & qoi_indices) virtual inherited
Calls user's attached quantity of interest function, or is overridden by the user in derived classes.
Definition at line 1960 of file system.C.
References libMesh::System::_equation_systems, libMesh::System::_qoi_evaluate_function, libMesh::System::_qoi_evaluate_object, libMesh::System::name(), and libMesh::System::QOI::qoi().
Referenced by libMesh::System::assemble_qoi().
 {
   // Call the user-provided quantity of interest function,
   // if it was provided
   if (_qoi_evaluate_function != nullptr)
     this->_qoi_evaluate_function(_equation_systems, this->name(), qoi_indices);
   // ...or the user-provided QOI function object.
   else if (_qoi_evaluate_object != nullptr)
     this->_qoi_evaluate_object->qoi(qoi_indices);
 }
user_QOI_derivative()
void libMesh::System::user_QOI_derivative (const QoISet & qoi_indices = QoISet(), bool include_liftfunc = true, bool apply_constraints = true) virtual inherited
Calls user's attached quantity of interest derivative function, or is overridden by the user in derived classes.
Definition at line 1974 of file system.C.
References libMesh::System::_equation_systems, libMesh::System::_qoi_evaluate_derivative_function, libMesh::System::_qoi_evaluate_derivative_object, libMesh::System::name(), and libMesh::System::QOIDerivative::qoi_derivative().
Referenced by libMesh::System::assemble_qoi_derivative().
 {
   // Call the user-provided quantity of interest derivative,
   // if it was provided
   if (_qoi_evaluate_derivative_function != nullptr)
     this->_qoi_evaluate_derivative_function
       (_equation_systems, this->name(), qoi_indices, include_liftfunc,
        apply_constraints);
   // ...or the user-provided QOI derivative function object.
   else if (_qoi_evaluate_derivative_object != nullptr)
     this->_qoi_evaluate_derivative_object->qoi_derivative
       (qoi_indices, include_liftfunc, apply_constraints);
 }
variable()
const Variable & libMesh::System::variable (unsigned int var) const inline inherited
Return a constant reference to Variable var.
Definition at line 2133 of file system.h.
References libMesh::System::_variables.
Referenced by libMesh::ExactSolution::_compute_error(), libMesh::PetscDMWrapper::add_dofs_to_section(), libMesh::DifferentiableSystem::add_second_order_dot_vars(), libMesh::EquationSystems::build_discontinuous_solution_vector(), libMesh::EquationSystems::build_parallel_elemental_solution_vector(), libMesh::EquationSystems::build_parallel_solution_vector(), libMesh::FirstOrderUnsteadySolver::compute_second_order_eqns(), libMesh::DifferentiableSystem::have_first_order_scalar_vars(), libMesh::DifferentiableSystem::have_second_order_scalar_vars(), libMesh::System::read_parallel_data(), libMesh::System::read_SCALAR_dofs(), libMesh::System::read_serialized_vector(), libMesh::System::read_serialized_vectors(), libMesh::PetscDMWrapper::set_point_range_in_section(), libMesh::System::write_header(), libMesh::System::write_parallel_data(), libMesh::System::write_serialized_vector(), and libMesh::System::write_serialized_vectors().
 {
   libmesh_assert_less (i, _variables.size());
   return _variables[i];
 }
variable_group()
const VariableGroup & libMesh::System::variable_group (unsigned int vg) const inline inherited
Return a constant reference to VariableGroup vg.
Definition at line 2143 of file system.h.
References libMesh::System::_variable_groups.
Referenced by libMesh::FEMSystem::assembly(), and libMesh::System::get_info().
 {
   libmesh_assert_less (vg, _variable_groups.size());
   return _variable_groups[vg];
 }
variable_name()
const std::string & libMesh::System::variable_name (const unsigned int i) const inline inherited
Returns
The name of variable i.
Definition at line 2153 of file system.h.
References libMesh::System::_variables.
Referenced by libMesh::System::add_variable(), libMesh::System::add_variables(), libMesh::EquationSystems::build_parallel_elemental_solution_vector(), libMesh::PetscDMWrapper::build_section(), libMesh::ExactErrorEstimator::estimate_error(), libMesh::ExactSolution::ExactSolution(), libMesh::petsc_auto_fieldsplit(), and libMesh::System::write_header().
 {
   libmesh_assert_less (i, _variables.size());
   return _variables[i].name();
 }
variable_number()
unsigned short int libMesh::System::variable_number (const std::string & var) const inherited
Returns
The variable number associated with the user-specified variable named var.
Definition at line 1243 of file system.C.
References libMesh::System::_variable_numbers, and libMesh::System::_variables.
Referenced by libMesh::ExactSolution::_compute_error(), libMesh::ExodusII_IO::copy_elemental_solution(), libMesh::ExodusII_IO::copy_nodal_solution(), libMesh::GMVIO::copy_nodal_solution(), libMesh::ExactErrorEstimator::estimate_error(), libMesh::ExactErrorEstimator::find_squared_element_error(), libMesh::System::read_header(), libMesh::System::variable_scalar_number(), libMesh::System::variable_type(), libMesh::EnsightIO::write_scalar_ascii(), and libMesh::EnsightIO::write_vector_ascii().
 {
   // Make sure the variable exists
   std::map<std::string, unsigned short int>::const_iterator
     pos = _variable_numbers.find(var);
   if (pos == _variable_numbers.end())
     libmesh_error_msg("ERROR: variable " << var << " does not exist in this system!");
   libmesh_assert_equal_to (_variables[pos->second].name(), var);
   return pos->second;
 }
variable_scalar_number() [1/2]
unsigned int libMesh::System::variable_scalar_number (const std::string & var, unsigned int component) const inline inherited
Returns
An index, starting from 0 for the first component of the first variable, and incrementing for each component of each (potentially vector-valued) variable in the system in order. For systems with only scalar-valued variables, this will be the same as variable_number(var)
Irony: currently our only non-scalar-valued variable type is SCALAR.
Definition at line 2164 of file system.h.
References libMesh::System::variable_number().
Referenced by libMesh::ExactSolution::_compute_error(), and libMesh::ExactErrorEstimator::find_squared_element_error().
 {
   return variable_scalar_number(this->variable_number(var), component);
 }
variable_scalar_number() [2/2]
unsigned int libMesh::System::variable_scalar_number (unsigned int var_num, unsigned int component) const inline inherited
Returns
An index, starting from 0 for the first component of the first variable, and incrementing for each component of each (potentially vector-valued) variable in the system in order. For systems with only scalar-valued variables, this will be the same as var_num
Irony: currently our only non-scalar-valued variable type is SCALAR.
Definition at line 2174 of file system.h.
References libMesh::System::_variables.
 {
   return _variables[var_num].first_scalar_number() + component;
 }
variable_type() [1/2]
const FEType & libMesh::System::variable_type (const unsigned int i) const inline inherited
Returns
The finite element type variable number i.
Definition at line 2183 of file system.h.
References libMesh::System::_variables.
Referenced by libMesh::System::add_variable(), libMesh::System::add_variables(), libMesh::EquationSystems::build_discontinuous_solution_vector(), libMesh::EquationSystems::build_parallel_elemental_solution_vector(), libMesh::EquationSystems::build_parallel_solution_vector(), libMesh::ExodusII_IO::copy_elemental_solution(), libMesh::GMVIO::copy_nodal_solution(), libMesh::DGFEMContext::DGFEMContext(), libMesh::JumpErrorEstimator::estimate_error(), libMesh::FEMSystem::init_context(), libMesh::FEMContext::init_internal_data(), libMesh::System::write_header(), libMesh::EnsightIO::write_scalar_ascii(), and libMesh::EnsightIO::write_vector_ascii().
 {
   libmesh_assert_less (i, _variables.size());
   return _variables[i].type();
 }
variable_type() [2/2]
const FEType & libMesh::System::variable_type (const std::string & var) const inline inherited
Returns
The finite element type for variable var.
Definition at line 2193 of file system.h.
References libMesh::System::_variables, and libMesh::System::variable_number().
 {
   return _variables[this->variable_number(var)].type();
 }
vector_is_adjoint()
int libMesh::System::vector_is_adjoint (const std::string & vec_name) const inherited
Returns
The integer describing whether the vector identified by vec_name represents a solution from an adjoint (non-negative) or the primal (-1) space.
Definition at line 896 of file system.C.
References libMesh::System::_vector_is_adjoint.
Referenced by libMesh::System::restrict_vectors().
 {
   libmesh_assert(_vector_is_adjoint.find(vec_name) !=
                  _vector_is_adjoint.end());
   return _vector_is_adjoint.find(vec_name)->second;
 }
vector_name() [1/2]
const std::string & libMesh::System::vector_name (const unsigned int vec_num) const inherited
Returns
The name of this system's additional vector number vec_num (where the vectors are counted starting with 0).
Definition at line 832 of file system.C.
References libMesh::System::vectors_begin(), and libMesh::System::vectors_end().
 {
   const_vectors_iterator v = vectors_begin();
   const_vectors_iterator v_end = vectors_end();
   unsigned int num = 0;
   while ((num<vec_num) && (v!=v_end))
     {
       num++;
       ++v;
     }
   libmesh_assert (v != v_end);
   return v->first;
 }
vector_name() [2/2]
const std::string & libMesh::System::vector_name (const NumericVector< Number > & vec_reference) const inherited
Returns
The name of a system vector, given a reference to that vector
Definition at line 846 of file system.C.
References libMesh::System::vectors_begin(), and libMesh::System::vectors_end().
 {
   const_vectors_iterator v = vectors_begin();
   const_vectors_iterator v_end = vectors_end();
   for (; v != v_end; ++v)
     {
       // Check if the current vector is the one whose name we want
       if (&vec_reference == v->second)
         break; // exit loop if it is
     }
   // Before returning, make sure we didnt loop till the end and not find any match
   libmesh_assert (v != v_end);
   // Return the string associated with the current vector
   return v->first;
 }
vector_preservation()
bool libMesh::System::vector_preservation (const std::string & vec_name) const inherited
Returns
The boolean describing whether the vector identified by vec_name should be "preserved": projected to new meshes, saved, etc.
Definition at line 875 of file system.C.
References libMesh::System::_vector_projections.
Referenced by libMesh::MemorySolutionHistory::store().
 {
   if (_vector_projections.find(vec_name) == _vector_projections.end())
     return false;
   return _vector_projections.find(vec_name)->second;
 }
vectors_begin() [1/2]
System::vectors_iterator libMesh::System::vectors_begin () inline inherited
Beginning of vectors container
Definition at line 2245 of file system.h.
References libMesh::System::_vectors.
Referenced by libMesh::UniformRefinementEstimator::_estimate_error(), libMesh::AdjointRefinementEstimator::estimate_error(), libMesh::System::get_vector(), libMesh::System::request_vector(), libMesh::MemorySolutionHistory::store(), and libMesh::System::vector_name().
 {
   return _vectors.begin();
 }
vectors_begin() [2/2]
System::const_vectors_iterator libMesh::System::vectors_begin () const inline inherited
Beginning of vectors container
Definition at line 2251 of file system.h.
References libMesh::System::_vectors.
 {
   return _vectors.begin();
 }
vectors_end() [1/2]
System::vectors_iterator libMesh::System::vectors_end () inline inherited
End of vectors container
Definition at line 2257 of file system.h.
References libMesh::System::_vectors.
Referenced by libMesh::UniformRefinementEstimator::_estimate_error(), libMesh::AdjointRefinementEstimator::estimate_error(), libMesh::System::get_vector(), libMesh::System::request_vector(), libMesh::MemorySolutionHistory::store(), and libMesh::System::vector_name().
 {
   return _vectors.end();
 }
vectors_end() [2/2]
System::const_vectors_iterator libMesh::System::vectors_end () const inline inherited
End of vectors container
Definition at line 2263 of file system.h.
References libMesh::System::_vectors.
 {
   return _vectors.end();
 }
weighted_sensitivity_adjoint_solve()
std::pair< unsigned int, Real > libMesh::System::weighted_sensitivity_adjoint_solve (const ParameterVector & parameters, const ParameterVector & weights, const QoISet & qoi_indices = QoISet()) inline virtual inherited
Assembles & solves the linear system(s) (dR/du)^T*z_w = sum(w_p*(d^2q/dudp - d^2R/dudp*z)), for those parameters p contained within parameters, weighted by the values w_p found within weights.
Assumes that adjoint_solve has already calculated z for each qoi in qoi_indices.
Returns
A pair with the total number of linear iterations performed and the (sum of the) final residual norms
This method is only implemented in some derived classes.
Reimplemented in libMesh::ImplicitSystem.
Definition at line 2307 of file system.h.
 {
   libmesh_not_implemented();
 }
weighted_sensitivity_solve()
std::pair< unsigned int, Real > libMesh::System::weighted_sensitivity_solve (const ParameterVector & parameters, const ParameterVector & weights) inline virtual inherited
Assembles & solves the linear system(s) (dR/du)*u_w = sum(w_p*-dR/dp), for those parameters p contained within parameters weighted by the values w_p found within weights.
Returns
A pair with the total number of linear iterations performed and the (sum of the) final residual norms
This method is only implemented in some derived classes.
Reimplemented in libMesh::ImplicitSystem.
Definition at line 2292 of file system.h.
 {
   libmesh_not_implemented();
 }
write_header()
void libMesh::System::write_header (Xdr & io, const std::string & version, const bool write_additional_data) const inherited
Writes the basic data header for this System.
This method implements the output of a System object, embedded in the output of an EquationSystems<T_sys>. This warrants some documentation. The output of this part consists of 5 sections:
for this system
5.) The number of variables in the system (unsigned int)
for each variable in the system
6.) The name of the variable (string)
6.1.) subdomain where the variable lives
7.) Combined in an FEType:
The approximation order(s) of the variable (Order Enum, cast to int/s)
The finite element family/ies of the variable (FEFamily Enum, cast to int/s)
end variable loop
8.) The number of additional vectors (unsigned int),
for each additional vector in the system object
9.) the name of the additional vector (string)
end system
Definition at line 1299 of file system_io.C.
References libMesh::System::_vectors, libMesh::Variable::active_subdomains(), libMesh::Xdr::data(), libMesh::FEType::family, libMesh::System::get_mesh(), libMesh::FEType::inf_map, libMesh::System::n_vars(), libMesh::System::n_vectors(), libMesh::System::name(), libMesh::FEType::order, libMesh::ParallelObject::processor_id(), libMesh::FEType::radial_family, libMesh::FEType::radial_order, libMesh::System::variable(), libMesh::System::variable_name(), libMesh::System::variable_type(), and libMesh::Xdr::writing().
 {
   libmesh_assert (io.writing());
   // Only write the header information
   // if we are processor 0.
   if (this->get_mesh().processor_id() != 0)
     return;
   std::string comment;
   char buf[80];
   // 5.)
   // Write the number of variables in the system
   {
     // set up the comment
     comment = "# No. of Variables in System \"";
     comment += this->name();
     comment += "\"";
     unsigned int nv = this->n_vars();
     io.data (nv, comment.c_str());
   }
   for (unsigned int var=0; var<this->n_vars(); var++)
     {
       // 6.)
       // Write the name of the var-th variable
       {
         // set up the comment
         comment  = "#   Name, Variable No. ";
         std::sprintf(buf, "%u", var);
         comment += buf;
         comment += ", System \"";
         comment += this->name();
         comment += "\"";
         std::string var_name = this->variable_name(var);
         io.data (var_name, comment.c_str());
       }
       // 6.1.) Variable subdomains
       {
         // set up the comment
         comment  = "#     Subdomains, Variable \"";
         std::sprintf(buf, "%s", this->variable_name(var).c_str());
         comment += buf;
         comment += "\", System \"";
         comment += this->name();
         comment += "\"";
         const std::set<subdomain_id_type> & domains = this->variable(var).active_subdomains();
         std::vector<subdomain_id_type> domain_array;
         domain_array.assign(domains.begin(), domains.end());
         io.data (domain_array, comment.c_str());
       }
       // 7.)
       // Write the approximation order of the var-th variable
       // in this system
       {
         // set up the comment
         comment = "#     Approximation Order, Variable \"";
         std::sprintf(buf, "%s", this->variable_name(var).c_str());
         comment += buf;
         comment += "\", System \"";
         comment += this->name();
         comment += "\"";
         int order = static_cast<int>(this->variable_type(var).order);
         io.data (order, comment.c_str());
       }
 #ifdef LIBMESH_ENABLE_INFINITE_ELEMENTS
       // do the same for radial_order
       {
         comment = "#     Radial Approximation Order, Variable \"";
         std::sprintf(buf, "%s", this->variable_name(var).c_str());
         comment += buf;
         comment += "\", System \"";
         comment += this->name();
         comment += "\"";
         int rad_order = static_cast<int>(this->variable_type(var).radial_order);
         io.data (rad_order, comment.c_str());
       }
 #endif
       // Write the Finite Element type of the var-th variable
       // in this System
       {
         // set up the comment
         comment = "#     FE Family, Variable \"";
         std::sprintf(buf, "%s", this->variable_name(var).c_str());
         comment += buf;
         comment += "\", System \"";
         comment += this->name();
         comment += "\"";
         const FEType & type = this->variable_type(var);
         int fam = static_cast<int>(type.family);
         io.data (fam, comment.c_str());
 #ifdef LIBMESH_ENABLE_INFINITE_ELEMENTS
         comment = "#     Radial FE Family, Variable \"";
         std::sprintf(buf, "%s", this->variable_name(var).c_str());
         comment += buf;
         comment += "\", System \"";
         comment += this->name();
         comment += "\"";
         int radial_fam = static_cast<int>(type.radial_family);
         io.data (radial_fam, comment.c_str());
         comment = "#     Infinite Mapping Type, Variable \"";
         std::sprintf(buf, "%s", this->variable_name(var).c_str());
         comment += buf;
         comment += "\", System \"";
         comment += this->name();
         comment += "\"";
         int i_map = static_cast<int>(type.inf_map);
         io.data (i_map, comment.c_str());
 #endif
       }
     } // end of the variable loop
   // 8.)
   // Write the number of additional vectors in the System.
   // If write_additional_data==false, then write zero for
   // the number of additional vectors.
   {
     {
       // set up the comment
       comment = "# No. of Additional Vectors, System \"";
       comment += this->name();
       comment += "\"";
       unsigned int nvecs = write_additional_data ? this->n_vectors () : 0;
       io.data (nvecs, comment.c_str());
     }
     if (write_additional_data)
       {
         unsigned int cnt=0;
         for (const auto & pr : _vectors)
           {
             // 9.)
             // write the name of the cnt-th additional vector
             comment =  "# Name of ";
             std::sprintf(buf, "%d", cnt++);
             comment += buf;
             comment += "th vector";
             std::string vec_name = pr.first;
             io.data (vec_name, comment.c_str());
           }
       }
   }
 }
write_parallel_data()
void libMesh::System::write_parallel_data (Xdr & io, const bool write_additional_data) const inherited
Writes additional data, namely vectors, for this System. This method may safely be called on a distributed-memory mesh. This method will create an individual file for each processor in the simulation where the local solution components for that processor will be stored.
This method implements the output of the vectors contained in this System object, embedded in the output of an EquationSystems<T_sys>.
9.) The global solution vector, re-ordered to be node-major (More on this later.)
for each additional vector in the object
10.) The global additional vector, re-ordered to be node-major (More on this later.)
Note that the actual IO is handled through the Xdr class (to be renamed later?) which provides a uniform interface to both the XDR (eXternal Data Representation) interface and standard ASCII output. Thus this one section of code will read XDR or ASCII files with no changes.
Definition at line 1504 of file system_io.C.
References libMesh::System::_vectors, libMesh::Xdr::data(), libMesh::FEType::family, libMesh::System::get_dof_map(), libMesh::System::get_mesh(), libMesh::DofObject::invalid_id, libMesh::ParallelObject::n_processors(), libMesh::System::n_vars(), libMesh::System::name(), libMesh::System::number(), libMesh::ParallelObject::processor_id(), libMesh::SCALAR, libMesh::DofMap::SCALAR_dof_indices(), libMesh::System::solution, libMesh::Variable::type(), libMesh::System::variable(), and libMesh::Xdr::writing().
 {
   // PerfLog pl("IO Performance",false);
   // pl.push("write_parallel_data");
   // std::size_t total_written_size = 0;
   std::string comment;
   libmesh_assert (io.writing());
   std::vector<Number> io_buffer; io_buffer.reserve(this->solution->local_size());
   // build the ordered nodes and element maps.
   // when writing/reading parallel files we need to iterate
   // over our nodes/elements in order of increasing global id().
   // however, this is not guaranteed to be ordering we obtain
   // by using the node_iterators/element_iterators directly.
   // so build a set, sorted by id(), that provides the ordering.
   // further, for memory economy build the set but then transfer
   // its contents to vectors, which will be sorted.
   std::vector<const DofObject *> ordered_nodes, ordered_elements;
   {
     std::set<const DofObject *, CompareDofObjectsByID>
       ordered_nodes_set (this->get_mesh().local_nodes_begin(),
                          this->get_mesh().local_nodes_end());
     ordered_nodes.insert(ordered_nodes.end(),
                          ordered_nodes_set.begin(),
                          ordered_nodes_set.end());
   }
   {
     std::set<const DofObject *, CompareDofObjectsByID>
       ordered_elements_set (this->get_mesh().local_elements_begin(),
                             this->get_mesh().local_elements_end());
     ordered_elements.insert(ordered_elements.end(),
                             ordered_elements_set.begin(),
                             ordered_elements_set.end());
   }
   const unsigned int sys_num = this->number();
   const unsigned int nv      = this->n_vars();
   // Loop over each non-SCALAR variable and each node, and write out the value.
   for (unsigned int var=0; var<nv; var++)
     if (this->variable(var).type().family != SCALAR)
       {
         // First write the node DOF values
         for (const auto & node : ordered_nodes)
           for (unsigned int comp=0; comp<node->n_comp(sys_num, var); comp++)
             {
               libmesh_assert_not_equal_to (node->dof_number(sys_num, var, comp),
                                            DofObject::invalid_id);
               io_buffer.push_back((*this->solution)(node->dof_number(sys_num, var, comp)));
             }
         // Then write the element DOF values
         for (const auto & elem : ordered_elements)
           for (unsigned int comp=0; comp<elem->n_comp(sys_num, var); comp++)
             {
               libmesh_assert_not_equal_to (elem->dof_number(sys_num, var, comp),
                                            DofObject::invalid_id);
               io_buffer.push_back((*this->solution)(elem->dof_number(sys_num, var, comp)));
             }
       }
   // Finally, write the SCALAR data on the last processor
   for (unsigned int var=0; var<this->n_vars(); var++)
     if (this->variable(var).type().family == SCALAR)
       {
         if (this->processor_id() == (this->n_processors()-1))
           {
             const DofMap & dof_map = this->get_dof_map();
             std::vector<dof_id_type> SCALAR_dofs;
             dof_map.SCALAR_dof_indices(SCALAR_dofs, var);
             for (std::size_t i=0; i<SCALAR_dofs.size(); i++)
               io_buffer.push_back((*this->solution)(SCALAR_dofs[i]));
           }
       }
   // 9.)
   //
   // Actually write the reordered solution vector
   // for the ith system to disk
   // set up the comment
   {
     comment = "# System \"";
     comment += this->name();
     comment += "\" Solution Vector";
   }
   io.data (io_buffer, comment.c_str());
   // total_written_size += io_buffer.size();
   // Only write additional vectors if wanted
   if (write_additional_data)
     {
       for (auto & pr : _vectors)
         {
           io_buffer.clear();
           io_buffer.reserve(pr.second->local_size());
           // Loop over each non-SCALAR variable and each node, and write out the value.
           for (unsigned int var=0; var<nv; var++)
             if (this->variable(var).type().family != SCALAR)
               {
                 // First write the node DOF values
                 for (const auto & node : ordered_nodes)
                   for (unsigned int comp=0; comp<node->n_comp(sys_num, var); comp++)
                     {
                       libmesh_assert_not_equal_to (node->dof_number(sys_num, var, comp),
                                                    DofObject::invalid_id);
                       io_buffer.push_back((*pr.second)(node->dof_number(sys_num, var, comp)));
                     }
                 // Then write the element DOF values
                 for (const auto & elem : ordered_elements)
                   for (unsigned int comp=0; comp<elem->n_comp(sys_num, var); comp++)
                     {
                       libmesh_assert_not_equal_to (elem->dof_number(sys_num, var, comp),
                                                    DofObject::invalid_id);
                       io_buffer.push_back((*pr.second)(elem->dof_number(sys_num, var, comp)));
                     }
               }
           // Finally, write the SCALAR data on the last processor
           for (unsigned int var=0; var<this->n_vars(); var++)
             if (this->variable(var).type().family == SCALAR)
               {
                 if (this->processor_id() == (this->n_processors()-1))
                   {
                     const DofMap & dof_map = this->get_dof_map();
                     std::vector<dof_id_type> SCALAR_dofs;
                     dof_map.SCALAR_dof_indices(SCALAR_dofs, var);
                     for (std::size_t i=0; i<SCALAR_dofs.size(); i++)
                       io_buffer.push_back((*pr.second)(SCALAR_dofs[i]));
                   }
               }
           // 10.)
           //
           // Actually write the reordered additional vector
           // for this system to disk
           // set up the comment
           {
             comment = "# System \"";
             comment += this->name();
             comment += "\" Additional Vector \"";
             comment += pr.first;
             comment += "\"";
           }
           io.data (io_buffer, comment.c_str());
           // total_written_size += io_buffer.size();
         }
     }
   // const Real
   //   dt   = pl.get_elapsed_time(),
   //   rate = total_written_size*sizeof(Number)/dt;
   // libMesh::err << "Write " << total_written_size << " \"Number\" values\n"
   //     << " Elapsed time = " << dt << '\n'
   //     << " Rate = " << rate/1.e6 << "(MB/sec)\n\n";
   // pl.pop("write_parallel_data");
 }
write_serialized_data()
void libMesh::System::write_serialized_data (Xdr & io, const bool write_additional_data = true) const inherited
Writes additional data, namely vectors, for this System. This method may safely be called on a distributed-memory mesh.
This method implements the output of the vectors contained in this System object, embedded in the output of an EquationSystems<T_sys>.
9.) The global solution vector, re-ordered to be node-major (More on this later.)
for each additional vector in the object
10.) The global additional vector, re-ordered to be node-major (More on this later.)
Definition at line 1704 of file system_io.C.
References libMesh::System::_vectors, libMesh::Xdr::comment(), libMesh::System::name(), libMesh::ParallelObject::processor_id(), libMesh::System::solution, and libMesh::System::write_serialized_vector().
 {
   parallel_object_only();
   std::string comment;
   // PerfLog pl("IO Performance",false);
   // pl.push("write_serialized_data");
   // std::size_t total_written_size = 0;
   // total_written_size +=
   this->write_serialized_vector(io, *this->solution);
   // set up the comment
   if (this->processor_id() == 0)
     {
       comment = "# System \"";
       comment += this->name();
       comment += "\" Solution Vector";
       io.comment (comment);
     }
   // Only write additional vectors if wanted
   if (write_additional_data)
     {
       std::map<std::string, NumericVector<Number> *>::const_iterator
         pos = _vectors.begin();
       for (; pos != this->_vectors.end(); ++pos)
         {
           // total_written_size +=
           this->write_serialized_vector(io, *pos->second);
           // set up the comment
           if (this->processor_id() == 0)
             {
               comment = "# System \"";
               comment += this->name();
               comment += "\" Additional Vector \"";
               comment += pos->first;
               comment += "\"";
               io.comment (comment);
             }
         }
     }
   // const Real
   //   dt   = pl.get_elapsed_time(),
   //   rate = total_written_size*sizeof(Number)/dt;
   // libMesh::out << "Write " << total_written_size << " \"Number\" values\n"
   //     << " Elapsed time = " << dt << '\n'
   //     << " Rate = " << rate/1.e6 << "(MB/sec)\n\n";
   // pl.pop("write_serialized_data");
   // // test the new method
   // {
   //   std::vector<std::string> names;
   //   std::vector<NumericVector<Number> *> vectors_to_write;
   //   names.push_back("Solution Vector");
   //   vectors_to_write.push_back(this->solution.get());
   //   // Only write additional vectors if wanted
   //   if (write_additional_data)
   //     {
   // std::map<std::string, NumericVector<Number> *>::const_iterator
   //   pos = _vectors.begin();
   // for (; pos != this->_vectors.end(); ++pos)
   //   {
   //     names.push_back("Additional Vector " + pos->first);
   //     vectors_to_write.push_back(pos->second);
   //   }
   //     }
   //   total_written_size =
   //     this->write_serialized_vectors (io, names, vectors_to_write);
   //   const Real
   //     dt2   = pl.get_elapsed_time(),
   //     rate2 = total_written_size*sizeof(Number)/(dt2-dt);
   //   libMesh::out << "Write (new) " << total_written_size << " \"Number\" values\n"
   //       << " Elapsed time = " << (dt2-dt) << '\n'
   //       << " Rate = " << rate2/1.e6 << "(MB/sec)\n\n";
   // }
 }
write_serialized_vectors()
std::size_t libMesh::System::write_serialized_vectors (Xdr & io, const std::vector< const NumericVector< Number > *> & vectors) const inherited
Serialize & write a number of identically distributed vectors. This method allows for optimization for the multiple vector case by only communicating the metadata once.
Definition at line 2297 of file system_io.C.
References libMesh::Xdr::data(), libMesh::FEType::family, libMesh::System::get_mesh(), libMesh::MeshBase::n_elem(), libMesh::MeshTools::n_elem(), n_nodes, libMesh::MeshBase::n_nodes(), libMesh::System::n_vars(), libMesh::ParallelObject::processor_id(), libMesh::SCALAR, libMesh::Variable::type(), libMesh::System::variable(), libMesh::System::write_SCALAR_dofs(), libMesh::System::write_serialized_blocked_dof_objects(), and libMesh::Xdr::writing().
 {
   parallel_object_only();
   libmesh_assert (io.writing());
   // Cache these - they are not free!
   const dof_id_type
     n_nodes       = this->get_mesh().n_nodes(),
     n_elem        = this->get_mesh().n_elem();
   std::size_t written_length = 0;
   if (this->processor_id() == 0)
     {
       unsigned int
         n_vec    = cast_int<unsigned int>(vectors.size());
       dof_id_type
         vec_size = vectors.empty() ? 0 : vectors[0]->size();
       // Set the number of vectors
       io.data(n_vec, "# number of vectors");
       // Set the buffer size
       io.data(vec_size, "# vector length");
     }
   //---------------------------------
   // Collect the values for all nodes
   written_length +=
     this->write_serialized_blocked_dof_objects (vectors,
                                                 n_nodes,
                                                 this->get_mesh().local_nodes_begin(),
                                                 this->get_mesh().local_nodes_end(),
                                                 io);
   //------------------------------------
   // Collect the values for all elements
   written_length +=
     this->write_serialized_blocked_dof_objects (vectors,
                                                 n_elem,
                                                 this->get_mesh().local_elements_begin(),
                                                 this->get_mesh().local_elements_end(),
                                                 io);
   //-------------------------------------------
   // Finally loop over all the SCALAR variables
   for (std::size_t vec=0; vec<vectors.size(); vec++)
     for (unsigned int var=0; var<this->n_vars(); var++)
       if (this->variable(var).type().family == SCALAR)
         {
           libmesh_assert_not_equal_to (vectors[vec], 0);
           written_length +=
             this->write_SCALAR_dofs (*vectors[vec], var, io);
         }
   return written_length;
 }
zero_variable()
void libMesh::System::zero_variable (NumericVector< Number > & v, unsigned int var_num) const inherited
Zeroes all dofs in v that correspond to variable number var_num.
Definition at line 1322 of file system.C.
References libMesh::System::get_mesh(), mesh, libMesh::System::n_vars(), libMesh::System::number(), and libMesh::NumericVector< T >::set().
 {
   /* Make sure the call makes sense.  */
   libmesh_assert_less (var_num, this->n_vars());
   /* Get a reference to the mesh.  */
   const MeshBase & mesh = this->get_mesh();
   /* Check which system we are.  */
   const unsigned int sys_num = this->number();
   // Loop over nodes.
   for (const auto & node : mesh.local_node_ptr_range())
     {
       unsigned int n_comp = node->n_comp(sys_num,var_num);
       for (unsigned int i=0; i<n_comp; i++)
         {
           const dof_id_type index = node->dof_number(sys_num,var_num,i);
           v.set(index,0.0);
         }
     }
   // Loop over elements.
   for (const auto & elem : mesh.active_local_element_ptr_range())
     {
       unsigned int n_comp = elem->n_comp(sys_num,var_num);
       for (unsigned int i=0; i<n_comp; i++)
         {
           const dof_id_type index = elem->dof_number(sys_num,var_num,i);
           v.set(index,0.0);
         }
     }
 }
Member Data Documentation
_communicator
const Parallel::Communicator& libMesh::ParallelObject::_communicator protected inherited
Definition at line 107 of file parallel_object.h.
Referenced by libMesh::EquationSystems::build_parallel_elemental_solution_vector(), libMesh::EquationSystems::build_parallel_solution_vector(), libMesh::ParallelObject::comm(), libMesh::ParallelObject::n_processors(), libMesh::ParallelObject::operator=(), and libMesh::ParallelObject::processor_id().
_counts
ReferenceCounter::Counts libMesh::ReferenceCounter::_counts static protected inherited
Actually holds the data.
Definition at line 122 of file reference_counter.h.
Referenced by libMesh::ReferenceCounter::get_info(), libMesh::ReferenceCounter::increment_constructor_count(), and libMesh::ReferenceCounter::increment_destructor_count().
_eigen_problem_type
EigenProblemType libMesh::EigenSystem::_eigen_problem_type private
The type of the eigenvalue problem.
Definition at line 218 of file eigen_system.h.
Referenced by get_eigenproblem_type(), init_data(), and set_eigenproblem_type().
_enable_print_counter
bool libMesh::ReferenceCounter::_enable_print_counter = true static protected inherited
Flag to control whether reference count information is printed when print_info is called.
Definition at line 141 of file reference_counter.h.
Referenced by libMesh::ReferenceCounter::disable_print_counter_info(), libMesh::ReferenceCounter::enable_print_counter_info(), and libMesh::ReferenceCounter::print_info().
_is_generalized_eigenproblem
bool libMesh::EigenSystem::_is_generalized_eigenproblem private
A boolean flag to indicate whether we are dealing with a generalized eigenvalue problem.
Definition at line 213 of file eigen_system.h.
Referenced by generalized(), init_data(), init_matrices(), n_matrices(), reinit(), and solve().
_mutex
Threads::spin_mutex libMesh::ReferenceCounter::_mutex static protected inherited
Mutual exclusion object to enable thread-safe reference counting.
Definition at line 135 of file reference_counter.h.
_n_converged_eigenpairs
unsigned int libMesh::EigenSystem::_n_converged_eigenpairs private
The number of converged eigenpairs.
Definition at line 202 of file eigen_system.h.
Referenced by get_n_converged(), set_n_converged(), and solve().
_n_iterations
unsigned int libMesh::EigenSystem::_n_iterations private
The number of iterations of the eigen solver algorithm.
Definition at line 207 of file eigen_system.h.
Referenced by get_n_iterations(), set_n_iterations(), and solve().
_n_objects
Threads::atomic< unsigned int > libMesh::ReferenceCounter::_n_objects static protected inherited
The number of objects. Print the reference count information when the number returns to 0.
Definition at line 130 of file reference_counter.h.
Referenced by libMesh::ReferenceCounter::n_objects(), libMesh::ReferenceCounter::ReferenceCounter(), and libMesh::ReferenceCounter::~ReferenceCounter().
assemble_before_solve
bool libMesh::System::assemble_before_solve inherited
Flag which tells the system to whether or not to call the user assembly function during each call to solve(). By default, every call to solve() begins with a call to the user assemble, so this flag is true. (For explicit systems, "solving" the system occurs during the assembly step, so this flag is always true for explicit systems.)
You will only want to set this to false if you need direct control over when the system is assembled, and are willing to track the state of its assembly yourself. An example of such a case is an implicit system with multiple right hand sides. In this instance, a single assembly would likely be followed with multiple calls to solve.
The frequency system and Newmark system have their own versions of this flag, called _finished_assemble, which might be able to be replaced with this more general concept.
Definition at line 1477 of file system.h.
Referenced by libMesh::ImplicitSystem::adjoint_solve(), libMesh::ImplicitSystem::disable_cache(), libMesh::System::disable_cache(), libMesh::ImplicitSystem::sensitivity_solve(), libMesh::CondensedEigenSystem::solve(), solve(), and libMesh::LinearImplicitSystem::solve().
current_local_solution
std::unique_ptr<NumericVector<Number> > libMesh::System::current_local_solution inherited
All the values I need to compute my contribution to the simulation at hand. Think of this as the current solution with any ghost values needed from other processors. This vector is necessarily larger than the solution vector in the case of a parallel simulation. The update() member is used to synchronize the contents of the solution and current_local_solution vectors.
Definition at line 1535 of file system.h.
Referenced by libMesh::__libmesh_petsc_diff_solver_jacobian(), libMesh::__libmesh_petsc_diff_solver_residual(), libMesh::UniformRefinementEstimator::_estimate_error(), libMesh::NonlinearImplicitSystem::assembly(), libMesh::EquationSystems::build_parallel_elemental_solution_vector(), libMesh::EquationSystems::build_parallel_solution_vector(), libMesh::System::clear(), libMesh::Problem_Interface::computeF(), libMesh::Problem_Interface::computeJacobian(), libMesh::Problem_Interface::computePreconditioner(), libMesh::System::current_solution(), DMlibMeshFunction(), DMlibMeshJacobian(), libMesh::AdjointRefinementEstimator::estimate_error(), libMesh::ExactErrorEstimator::estimate_error(), libMesh::System::init_data(), libMesh::libmesh_petsc_snes_fd_residual(), libMesh::libmesh_petsc_snes_jacobian(), libMesh::libmesh_petsc_snes_mffd_residual(), libMesh::libmesh_petsc_snes_residual(), libMesh::libmesh_petsc_snes_residual_helper(), libMesh::FEMContext::pre_fe_reinit(), libMesh::System::re_update(), libMesh::System::reinit(), libMesh::System::restrict_vectors(), and libMesh::System::update().
eigen_solver
std::unique_ptr<EigenSolver<Number> > libMesh::EigenSystem::eigen_solver
The EigenSolver, defining which interface, i.e solver package to use.
Definition at line 165 of file eigen_system.h.
Referenced by clear(), libMesh::CondensedEigenSystem::get_eigenpair(), get_eigenpair(), set_eigenproblem_type(), libMesh::CondensedEigenSystem::solve(), and solve().
extra_quadrature_order
int libMesh::System::extra_quadrature_order inherited
A member int that can be employed to indicate increased or reduced quadrature order.
Note
For FEMSystem users, by default, when calling the user-defined residual functions, the FEMSystem will first set up an appropriate FEType::default_quadrature_rule() object for performing the integration. This rule will integrate elements of order up to 2*p+1 exactly (where p is the sum of the base FEType and local p refinement levels), but if additional (or reduced) quadrature accuracy is desired then this extra_quadrature_order (default 0) will be added.
Definition at line 1508 of file system.h.
matrix_A
std::unique_ptr<SparseMatrix<Number> > libMesh::EigenSystem::matrix_A
The system matrix for standard eigenvalue problems.
Definition at line 154 of file eigen_system.h.
Referenced by clear(), init_data(), init_matrices(), reinit(), libMesh::CondensedEigenSystem::solve(), and solve().
matrix_B
std::unique_ptr<SparseMatrix<Number> > libMesh::EigenSystem::matrix_B
A second system matrix for generalized eigenvalue problems.
Definition at line 159 of file eigen_system.h.
Referenced by clear(), init_matrices(), reinit(), libMesh::CondensedEigenSystem::solve(), and solve().
qoi
std::vector<Number> libMesh::System::qoi inherited
Values of the quantities of interest. This vector needs to be both resized and filled by the user before any quantity of interest assembly is done and before any sensitivities are calculated.
Definition at line 1558 of file system.h.
Referenced by libMesh::ImplicitSystem::adjoint_qoi_parameter_sensitivity(), libMesh::ExplicitSystem::assemble_qoi(), libMesh::FEMSystem::assemble_qoi(), libMesh::DifferentiableSystem::attach_qoi(), libMesh::DiffContext::DiffContext(), libMesh::ImplicitSystem::forward_qoi_parameter_sensitivity(), libMesh::System::n_qois(), libMesh::ImplicitSystem::qoi_parameter_hessian(), and libMesh::ImplicitSystem::qoi_parameter_hessian_vector_product().
solution
std::unique_ptr<NumericVector<Number> > libMesh::System::solution inherited
Data structure to hold solution values.
Definition at line 1523 of file system.h.
Referenced by libMesh::__libmesh_petsc_diff_solver_jacobian(), libMesh::__libmesh_petsc_diff_solver_residual(), libMesh::ExactSolution::_compute_error(), libMesh::UniformRefinementEstimator::_estimate_error(), libMesh::NewmarkSolver::advance_timestep(), libMesh::AdaptiveTimeSolver::advance_timestep(), libMesh::UnsteadySolver::advance_timestep(), libMesh::ContinuationSystem::apply_predictor(), libMesh::FEMSystem::assembly(), libMesh::LinearImplicitSystem::assembly(), libMesh::EquationSystems::build_parallel_elemental_solution_vector(), libMesh::EquationSystems::build_parallel_solution_vector(), libMesh::System::clear(), libMesh::System::compare(), libMesh::NewmarkSolver::compute_initial_accel(), libMesh::Problem_Interface::computeF(), libMesh::Problem_Interface::computeJacobian(), libMesh::Problem_Interface::computePreconditioner(), libMesh::ContinuationSystem::continuation_solve(), libMesh::ExodusII_IO::copy_elemental_solution(), libMesh::ExodusII_IO::copy_nodal_solution(), libMesh::GMVIO::copy_nodal_solution(), DMCreateGlobalVector_libMesh(), DMlibMeshFunction(), DMlibMeshJacobian(), libMesh::UnsteadySolver::du(), libMesh::DofMap::enforce_constraints_exactly(), libMesh::WeightedPatchRecoveryErrorEstimator::estimate_error(), libMesh::PatchRecoveryErrorEstimator::estimate_error(), libMesh::JumpErrorEstimator::estimate_error(), libMesh::AdjointRefinementEstimator::estimate_error(), libMesh::AdjointResidualErrorEstimator::estimate_error(), libMesh::ExactErrorEstimator::estimate_error(), libMesh::CondensedEigenSystem::get_eigenpair(), get_eigenpair(), libMesh::System::init_data(), libMesh::ContinuationSystem::initialize_tangent(), libMesh::libmesh_petsc_snes_jacobian(), libMesh::libmesh_petsc_snes_postcheck(), libMesh::libmesh_petsc_snes_residual_helper(), libMesh::DofMap::max_constraint_error(), libMesh::FEMSystem::mesh_position_get(), libMesh::ErrorVector::plot_error(), libMesh::ImplicitSystem::qoi_parameter_hessian(), libMesh::ImplicitSystem::qoi_parameter_hessian_vector_product(), libMesh::System::re_update(), libMesh::System::read_legacy_data(), libMesh::System::read_parallel_data(), libMesh::System::read_serialized_data(), libMesh::System::reinit(), libMesh::System::restrict_vectors(), libMesh::MemorySolutionHistory::retrieve(), libMesh::ContinuationSystem::save_current_solution(), libMesh::TwostepTimeSolver::solve(), libMesh::NewtonSolver::solve(), libMesh::PetscDiffSolver::solve(), libMesh::FrequencySystem::solve(), libMesh::LinearImplicitSystem::solve(), libMesh::NonlinearImplicitSystem::solve(), libMesh::ContinuationSystem::solve_tangent(), libMesh::MemorySolutionHistory::store(), libMesh::System::update(), libMesh::System::update_global_solution(), libMesh::ContinuationSystem::update_solution(), libMesh::NewmarkSystem::update_u_v_a(), libMesh::System::write_parallel_data(), and libMesh::System::write_serialized_data().
time
Real libMesh::System::time inherited
For time-dependent problems, this is the time t at the beginning of the current timestep.
Note
For DifferentiableSystem users: do not access this time during an assembly! Use the DiffContext::time value instead to get correct results.
Definition at line 1545 of file system.h.
Referenced by libMesh::UnsteadySolver::adjoint_advance_timestep(), libMesh::AdaptiveTimeSolver::advance_timestep(), libMesh::UnsteadySolver::advance_timestep(), libMesh::ExactErrorEstimator::find_squared_element_error(), libMesh::MemorySolutionHistory::find_stored_entry(), libMesh::WeightedPatchRecoveryErrorEstimator::EstimateError::operator()(), libMesh::System::reinit_constraints(), libMesh::MemorySolutionHistory::retrieve(), libMesh::TwostepTimeSolver::solve(), and libMesh::MemorySolutionHistory::store().
use_fixed_solution
bool libMesh::System::use_fixed_solution inherited
A boolean to be set to true by systems using elem_fixed_solution, for optional use by e.g. stabilized methods. False by default.
Note
For FEMSystem users, if this variable is set to true, it must be before init_data() is called.
Definition at line 1493 of file system.h.
Referenced by libMesh::EulerSolver::_general_residual(), libMesh::Euler2Solver::_general_residual(), libMesh::SteadySolver::_general_residual(), libMesh::NewmarkSolver::_general_residual(), libMesh::DifferentiableSystem::clear(), libMesh::DiffContext::DiffContext(), and libMesh::FEMContext::pre_fe_reinit().
The documentation for this class was generated from the following files:
eigen_system.h
eigen_system.C