libMesh: libMesh::SerialMesh Class Reference
SomeWebsiteLogo
libMesh::SerialMesh Class Reference
#include <serial_mesh.h>
Public Types
typedef Predicates::multi_predicate Predicate
Public Member Functions
SerialMesh (const Parallel::Communicator &comm_in, unsigned char dim=1)
SerialMesh (unsigned char dim=1)
SerialMesh (const UnstructuredMesh &other_mesh)
virtual std::unique_ptr< MeshBase > clone () const libmesh_override
~SerialMesh ()
virtual void clear () libmesh_override
virtual void renumber_nodes_and_elements () libmesh_override
virtual dof_id_type n_nodes () const libmesh_override
virtual dof_id_type parallel_n_nodes () const libmesh_override
virtual dof_id_type max_node_id () const libmesh_override
virtual void reserve_nodes (const dof_id_type nn) libmesh_override
virtual dof_id_type n_elem () const libmesh_override
virtual dof_id_type parallel_n_elem () const libmesh_override
virtual dof_id_type n_active_elem () const libmesh_override
virtual dof_id_type max_elem_id () const libmesh_override
virtual unique_id_type parallel_max_unique_id () const libmesh_override
virtual void reserve_elem (const dof_id_type ne) libmesh_override
virtual void update_parallel_id_counts () libmesh_override
virtual const Point & point (const dof_id_type i) const libmesh_override
virtual const Node * node_ptr (const dof_id_type i) const libmesh_override
virtual Node * node_ptr (const dof_id_type i) libmesh_override
virtual const Node * query_node_ptr (const dof_id_type i) const libmesh_override
virtual Node * query_node_ptr (const dof_id_type i) libmesh_override
virtual const Elem * elem_ptr (const dof_id_type i) const libmesh_override
virtual Elem * elem_ptr (const dof_id_type i) libmesh_override
virtual const Elem * query_elem_ptr (const dof_id_type i) const libmesh_override
virtual Elem * query_elem_ptr (const dof_id_type i) libmesh_override
virtual Node * add_point (const Point &p, const dof_id_type id=DofObject::invalid_id, const processor_id_type proc_id=DofObject::invalid_processor_id) libmesh_override
virtual Node * add_node (Node *n) libmesh_override
virtual Node * insert_node (Node *n) libmesh_override
virtual void delete_node (Node *n) libmesh_override
virtual void renumber_node (dof_id_type old_id, dof_id_type new_id) libmesh_override
virtual Elem * add_elem (Elem *e) libmesh_override
virtual Elem * insert_elem (Elem *e) libmesh_override
virtual void delete_elem (Elem *e) libmesh_override
virtual void renumber_elem (dof_id_type old_id, dof_id_type new_id) libmesh_override
virtual void fix_broken_node_and_element_numbering () libmesh_override
void stitch_meshes (ReplicatedMesh &other_mesh, boundary_id_type this_mesh_boundary, boundary_id_type other_mesh_boundary, Real tol=TOLERANCE, bool clear_stitched_boundary_ids=false, bool verbose=true, bool use_binary_search=true, bool enforce_all_nodes_match_on_boundaries=false)
void stitch_surfaces (boundary_id_type boundary_id_1, boundary_id_type boundary_id_2, Real tol=TOLERANCE, bool clear_stitched_boundary_ids=false, bool verbose=true, bool use_binary_search=true, bool enforce_all_nodes_match_on_boundaries=false)
virtual element_iterator elements_begin () libmesh_override
virtual const_element_iterator elements_begin () const libmesh_override
virtual element_iterator elements_end () libmesh_override
virtual const_element_iterator elements_end () const libmesh_override
virtual SimpleRange< element_iterator > element_ptr_range () libmesh_override
virtual SimpleRange< const_element_iterator > element_ptr_range () const libmesh_override
virtual element_iterator active_elements_begin () libmesh_override
virtual const_element_iterator active_elements_begin () const libmesh_override
virtual element_iterator active_elements_end () libmesh_override
virtual const_element_iterator active_elements_end () const libmesh_override
virtual SimpleRange< element_iterator > active_element_ptr_range () libmesh_override
virtual SimpleRange< const_element_iterator > active_element_ptr_range () const libmesh_override
virtual element_iterator ancestor_elements_begin () libmesh_override
virtual const_element_iterator ancestor_elements_begin () const libmesh_override
virtual element_iterator ancestor_elements_end () libmesh_override
virtual const_element_iterator ancestor_elements_end () const libmesh_override
virtual element_iterator subactive_elements_begin () libmesh_override
virtual const_element_iterator subactive_elements_begin () const libmesh_override
virtual element_iterator subactive_elements_end () libmesh_override
virtual const_element_iterator subactive_elements_end () const libmesh_override
virtual element_iterator not_active_elements_begin () libmesh_override
virtual const_element_iterator not_active_elements_begin () const libmesh_override
virtual element_iterator not_active_elements_end () libmesh_override
virtual const_element_iterator not_active_elements_end () const libmesh_override
virtual element_iterator not_ancestor_elements_begin () libmesh_override
virtual const_element_iterator not_ancestor_elements_begin () const libmesh_override
virtual element_iterator not_ancestor_elements_end () libmesh_override
virtual const_element_iterator not_ancestor_elements_end () const libmesh_override
virtual element_iterator not_subactive_elements_begin () libmesh_override
virtual const_element_iterator not_subactive_elements_begin () const libmesh_override
virtual element_iterator not_subactive_elements_end () libmesh_override
virtual const_element_iterator not_subactive_elements_end () const libmesh_override
virtual element_iterator local_elements_begin () libmesh_override
virtual const_element_iterator local_elements_begin () const libmesh_override
virtual element_iterator local_elements_end () libmesh_override
virtual const_element_iterator local_elements_end () const libmesh_override
virtual element_iterator semilocal_elements_begin () libmesh_override
virtual const_element_iterator semilocal_elements_begin () const libmesh_override
virtual element_iterator semilocal_elements_end () libmesh_override
virtual const_element_iterator semilocal_elements_end () const libmesh_override
virtual element_iterator active_semilocal_elements_begin () libmesh_override
virtual const_element_iterator active_semilocal_elements_begin () const libmesh_override
virtual element_iterator active_semilocal_elements_end () libmesh_override
virtual const_element_iterator active_semilocal_elements_end () const libmesh_override
virtual element_iterator facelocal_elements_begin () libmesh_override
virtual const_element_iterator facelocal_elements_begin () const libmesh_override
virtual element_iterator facelocal_elements_end () libmesh_override
virtual const_element_iterator facelocal_elements_end () const libmesh_override
virtual element_iterator not_local_elements_begin () libmesh_override
virtual const_element_iterator not_local_elements_begin () const libmesh_override
virtual element_iterator not_local_elements_end () libmesh_override
virtual const_element_iterator not_local_elements_end () const libmesh_override
virtual element_iterator active_local_elements_begin () libmesh_override
virtual const_element_iterator active_local_elements_begin () const libmesh_override
virtual element_iterator active_local_elements_end () libmesh_override
virtual const_element_iterator active_local_elements_end () const libmesh_override
virtual SimpleRange< element_iterator > active_local_element_ptr_range () libmesh_override
virtual SimpleRange< const_element_iterator > active_local_element_ptr_range () const libmesh_override
virtual element_iterator active_not_local_elements_begin () libmesh_override
virtual const_element_iterator active_not_local_elements_begin () const libmesh_override
virtual element_iterator active_not_local_elements_end () libmesh_override
virtual const_element_iterator active_not_local_elements_end () const libmesh_override
virtual element_iterator level_elements_begin (unsigned int level) libmesh_override
virtual const_element_iterator level_elements_begin (unsigned int level) const libmesh_override
virtual element_iterator level_elements_end (unsigned int level) libmesh_override
virtual const_element_iterator level_elements_end (unsigned int level) const libmesh_override
virtual element_iterator not_level_elements_begin (unsigned int level) libmesh_override
virtual const_element_iterator not_level_elements_begin (unsigned int level) const libmesh_override
virtual element_iterator not_level_elements_end (unsigned int level) libmesh_override
virtual const_element_iterator not_level_elements_end (unsigned int level) const libmesh_override
virtual element_iterator local_level_elements_begin (unsigned int level) libmesh_override
virtual const_element_iterator local_level_elements_begin (unsigned int level) const libmesh_override
virtual element_iterator local_level_elements_end (unsigned int level) libmesh_override
virtual const_element_iterator local_level_elements_end (unsigned int level) const libmesh_override
virtual element_iterator local_not_level_elements_begin (unsigned int level) libmesh_override
virtual const_element_iterator local_not_level_elements_begin (unsigned int level) const libmesh_override
virtual element_iterator local_not_level_elements_end (unsigned int level) libmesh_override
virtual const_element_iterator local_not_level_elements_end (unsigned int level) const libmesh_override
virtual element_iterator pid_elements_begin (processor_id_type proc_id) libmesh_override
virtual const_element_iterator pid_elements_begin (processor_id_type proc_id) const libmesh_override
virtual element_iterator pid_elements_end (processor_id_type proc_id) libmesh_override
virtual const_element_iterator pid_elements_end (processor_id_type proc_id) const libmesh_override
virtual element_iterator type_elements_begin (ElemType type) libmesh_override
virtual const_element_iterator type_elements_begin (ElemType type) const libmesh_override
virtual element_iterator type_elements_end (ElemType type) libmesh_override
virtual const_element_iterator type_elements_end (ElemType type) const libmesh_override
virtual element_iterator active_type_elements_begin (ElemType type) libmesh_override
virtual const_element_iterator active_type_elements_begin (ElemType type) const libmesh_override
virtual element_iterator active_type_elements_end (ElemType type) libmesh_override
virtual const_element_iterator active_type_elements_end (ElemType type) const libmesh_override
virtual element_iterator active_pid_elements_begin (processor_id_type proc_id) libmesh_override
virtual const_element_iterator active_pid_elements_begin (processor_id_type proc_id) const libmesh_override
virtual element_iterator active_pid_elements_end (processor_id_type proc_id) libmesh_override
virtual const_element_iterator active_pid_elements_end (processor_id_type proc_id) const libmesh_override
virtual element_iterator unpartitioned_elements_begin () libmesh_override
virtual const_element_iterator unpartitioned_elements_begin () const libmesh_override
virtual element_iterator unpartitioned_elements_end () libmesh_override
virtual const_element_iterator unpartitioned_elements_end () const libmesh_override
virtual element_iterator active_unpartitioned_elements_begin () libmesh_override
virtual const_element_iterator active_unpartitioned_elements_begin () const libmesh_override
virtual element_iterator active_unpartitioned_elements_end () libmesh_override
virtual const_element_iterator active_unpartitioned_elements_end () const libmesh_override
virtual element_iterator active_local_subdomain_elements_begin (subdomain_id_type subdomain_id) libmesh_override
virtual const_element_iterator active_local_subdomain_elements_begin (subdomain_id_type subdomain_id) const libmesh_override
virtual element_iterator active_local_subdomain_elements_end (subdomain_id_type subdomain_id) libmesh_override
virtual const_element_iterator active_local_subdomain_elements_end (subdomain_id_type subdomain_id) const libmesh_override
virtual element_iterator active_subdomain_elements_begin (subdomain_id_type subdomain_id) libmesh_override
virtual const_element_iterator active_subdomain_elements_begin (subdomain_id_type subdomain_id) const libmesh_override
virtual element_iterator active_subdomain_elements_end (subdomain_id_type subdomain_id) libmesh_override
virtual const_element_iterator active_subdomain_elements_end (subdomain_id_type subdomain_id) const libmesh_override
virtual element_iterator active_subdomain_set_elements_begin (std::set< subdomain_id_type > ss) libmesh_override
virtual const_element_iterator active_subdomain_set_elements_begin (std::set< subdomain_id_type > ss) const libmesh_override
virtual element_iterator active_subdomain_set_elements_end (std::set< subdomain_id_type > ss) libmesh_override
virtual const_element_iterator active_subdomain_set_elements_end (std::set< subdomain_id_type > ss) const libmesh_override
virtual element_iterator ghost_elements_begin () libmesh_override
virtual const_element_iterator ghost_elements_begin () const libmesh_override
virtual element_iterator ghost_elements_end () libmesh_override
virtual const_element_iterator ghost_elements_end () const libmesh_override
virtual element_iterator evaluable_elements_begin (const DofMap &dof_map, unsigned int var_num=libMesh::invalid_uint) libmesh_override
virtual const_element_iterator evaluable_elements_begin (const DofMap &dof_map, unsigned int var_num=libMesh::invalid_uint) const libmesh_override
virtual element_iterator evaluable_elements_end (const DofMap &dof_map, unsigned int var_num=libMesh::invalid_uint) libmesh_override
virtual const_element_iterator evaluable_elements_end (const DofMap &dof_map, unsigned int var_num=libMesh::invalid_uint) const libmesh_override
virtual element_iterator flagged_elements_begin (unsigned char rflag) libmesh_override
virtual const_element_iterator flagged_elements_begin (unsigned char rflag) const libmesh_override
virtual element_iterator flagged_elements_end (unsigned char rflag) libmesh_override
virtual const_element_iterator flagged_elements_end (unsigned char rflag) const libmesh_override
virtual element_iterator flagged_pid_elements_begin (unsigned char rflag, processor_id_type pid) libmesh_override
virtual const_element_iterator flagged_pid_elements_begin (unsigned char rflag, processor_id_type pid) const libmesh_override
virtual element_iterator flagged_pid_elements_end (unsigned char rflag, processor_id_type pid) libmesh_override
virtual const_element_iterator flagged_pid_elements_end (unsigned char rflag, processor_id_type pid) const libmesh_override
virtual node_iterator nodes_begin () libmesh_override
virtual const_node_iterator nodes_begin () const libmesh_override
virtual node_iterator nodes_end () libmesh_override
virtual const_node_iterator nodes_end () const libmesh_override
virtual SimpleRange< node_iterator > node_ptr_range () libmesh_override
virtual SimpleRange< const_node_iterator > node_ptr_range () const libmesh_override
virtual node_iterator active_nodes_begin () libmesh_override
virtual const_node_iterator active_nodes_begin () const libmesh_override
virtual node_iterator active_nodes_end () libmesh_override
virtual const_node_iterator active_nodes_end () const libmesh_override
virtual node_iterator local_nodes_begin () libmesh_override
virtual const_node_iterator local_nodes_begin () const libmesh_override
virtual node_iterator local_nodes_end () libmesh_override
virtual const_node_iterator local_nodes_end () const libmesh_override
virtual SimpleRange< node_iterator > local_node_ptr_range () libmesh_override
virtual SimpleRange< const_node_iterator > local_node_ptr_range () const libmesh_override
virtual node_iterator pid_nodes_begin (processor_id_type proc_id) libmesh_override
virtual const_node_iterator pid_nodes_begin (processor_id_type proc_id) const libmesh_override
virtual node_iterator pid_nodes_end (processor_id_type proc_id) libmesh_override
virtual const_node_iterator pid_nodes_end (processor_id_type proc_id) const libmesh_override
virtual node_iterator bid_nodes_begin (boundary_id_type bndry_id) libmesh_override
virtual const_node_iterator bid_nodes_begin (boundary_id_type bndry_id) const libmesh_override
virtual node_iterator bid_nodes_end (boundary_id_type bndry_id) libmesh_override
virtual const_node_iterator bid_nodes_end (boundary_id_type bndry_id) const libmesh_override
virtual node_iterator bnd_nodes_begin () libmesh_override
virtual const_node_iterator bnd_nodes_begin () const libmesh_override
virtual node_iterator bnd_nodes_end () libmesh_override
virtual const_node_iterator bnd_nodes_end () const libmesh_override
virtual node_iterator evaluable_nodes_begin (const DofMap &dof_map, unsigned int var_num=libMesh::invalid_uint) libmesh_override
virtual const_node_iterator evaluable_nodes_begin (const DofMap &dof_map, unsigned int var_num=libMesh::invalid_uint) const libmesh_override
virtual node_iterator evaluable_nodes_end (const DofMap &dof_map, unsigned int var_num=libMesh::invalid_uint) libmesh_override
virtual const_node_iterator evaluable_nodes_end (const DofMap &dof_map, unsigned int var_num=libMesh::invalid_uint) const libmesh_override
virtual void read (const std::string &name, void *mesh_data=libmesh_nullptr, bool skip_renumber_nodes_and_elements=false, bool skip_find_neighbors=false) libmesh_override
virtual void write (const std::string &name) libmesh_override
void write (const std::string &name, const std::vector< Number > &values, const std::vector< std::string > &variable_names)
virtual void all_first_order () libmesh_override
virtual void all_second_order (const bool full_ordered=true) libmesh_override
void create_pid_mesh (UnstructuredMesh &pid_mesh, const processor_id_type pid) const
void create_submesh (UnstructuredMesh &new_mesh, const_element_iterator &it, const const_element_iterator &it_end) const
virtual void copy_nodes_and_elements (const UnstructuredMesh &other_mesh, const bool skip_find_neighbors=false)
virtual void find_neighbors (const bool reset_remote_elements=false, const bool reset_current_list=true) libmesh_override
virtual bool contract () libmesh_override
virtual std::unique_ptr< Partitioner > & partitioner ()
const BoundaryInfo & get_boundary_info () const
BoundaryInfo & get_boundary_info ()
bool is_prepared () const
virtual bool is_serial () const
virtual bool is_serial_on_zero () const
virtual void set_distributed ()
virtual bool is_replicated () const
virtual void allgather ()
virtual void gather_to_zero ()
virtual void delete_remote_elements ()
unsigned int mesh_dimension () const
void set_mesh_dimension (unsigned char d)
const std::set< unsigned char > & elem_dimensions () const
unsigned int spatial_dimension () const
void set_spatial_dimension (unsigned char d)
dof_id_type n_nodes_on_proc (const processor_id_type proc) const
dof_id_type n_local_nodes () const
dof_id_type n_unpartitioned_nodes () const
unique_id_type next_unique_id ()
void set_next_unique_id (unique_id_type id)
dof_id_type n_elem_on_proc (const processor_id_type proc) const
dof_id_type n_local_elem () const
dof_id_type n_unpartitioned_elem () const
dof_id_type n_active_elem_on_proc (const processor_id_type proc) const
dof_id_type n_active_local_elem () const
dof_id_type n_sub_elem () const
dof_id_type n_active_sub_elem () const
virtual const Node & node_ref (const dof_id_type i) const
virtual Node & node_ref (const dof_id_type i)
virtual const Node & node (const dof_id_type i) const
virtual Node & node (const dof_id_type i)
virtual const Elem & elem_ref (const dof_id_type i) const
virtual Elem & elem_ref (const dof_id_type i)
virtual const Elem * elem (const dof_id_type i) const
virtual Elem * elem (const dof_id_type i)
virtual const Elem * query_elem (const dof_id_type i) const
virtual Elem * query_elem (const dof_id_type i)
void prepare_for_use (const bool skip_renumber_nodes_and_elements=false, const bool skip_find_neighbors=false)
virtual void partition (const unsigned int n_parts)
void partition ()
virtual void redistribute ()
virtual void update_post_partitioning ()
void allow_renumbering (bool allow)
bool allow_renumbering () const
void allow_remote_element_removal (bool allow)
bool allow_remote_element_removal () const
void skip_partitioning (bool skip)
bool skip_partitioning () const
void add_ghosting_functor (GhostingFunctor &ghosting_functor)
void remove_ghosting_functor (GhostingFunctor &ghosting_functor)
std::set< GhostingFunctor * >::const_iterator ghosting_functors_begin () const
std::set< GhostingFunctor * >::const_iterator ghosting_functors_end () const
void subdomain_ids (std::set< subdomain_id_type > &ids) const
subdomain_id_type n_subdomains () const
unsigned int n_partitions () const
std::string get_info () const
void print_info (std::ostream &os=libMesh::out) const
unsigned int recalculate_n_partitions ()
const PointLocatorBase & point_locator () const
std::unique_ptr< PointLocatorBase > sub_point_locator () const
void clear_point_locator ()
void set_count_lower_dim_elems_in_point_locator (bool count_lower_dim_elems)
bool get_count_lower_dim_elems_in_point_locator () const
virtual void libmesh_assert_valid_parallel_ids () const
std::string & subdomain_name (subdomain_id_type id)
const std::string & subdomain_name (subdomain_id_type id) const
subdomain_id_type get_id_by_name (const std::string &name) const
std::map< subdomain_id_type, std::string > & set_subdomain_name_map ()
const std::map< subdomain_id_type, std::string > & get_subdomain_name_map () const
void cache_elem_dims ()
void detect_interior_parents ()
const Parallel::Communicator & comm () const
processor_id_type n_processors () const
processor_id_type processor_id () const
Public Attributes
std::unique_ptr< BoundaryInfo > boundary_info
Protected Member Functions
unsigned int & set_n_partitions ()
Protected Attributes
std::vector< Node * > _nodes
std::vector< Elem * > _elements
unsigned int _n_parts
bool _is_prepared
std::unique_ptr< PointLocatorBase > _point_locator
bool _count_lower_dim_elems_in_point_locator
std::unique_ptr< Partitioner > _partitioner
unique_id_type _next_unique_id
bool _skip_partitioning
bool _skip_renumber_nodes_and_elements
bool _allow_remote_element_removal
std::map< subdomain_id_type, std::string > _block_id_to_name
std::set< unsigned char > _elem_dims
unsigned char _spatial_dimension
std::unique_ptr< GhostingFunctor > _default_ghosting
std::set< GhostingFunctor * > _ghosting_functors
const Parallel::Communicator & _communicator
Detailed Description
Definition at line 34 of file serial_mesh.h.
Member Typedef Documentation
typedef Predicates::multi_predicate libMesh::MeshBase::Predicate inherited
We need an empty, generic class to act as a predicate for this and derived mesh classes.
Definition at line 890 of file mesh_base.h.
Constructor & Destructor Documentation
libMesh::SerialMesh::SerialMesh (const Parallel::Communicator & comm_in, unsigned char dim = 1) inline explicit
Definition at line 38 of file serial_mesh.h.
     : ReplicatedMesh(comm_in,dim) {}
libMesh::SerialMesh::SerialMesh (unsigned char dim = 1) inline explicit
Constructor which takes dim, the dimension of the mesh. The mesh dimension can be changed (and may automatically be changed by mesh generation/loading) later.
Deprecated:
LIBMESH_DISABLE_COMMWORLD is now the default, use the constructor that takes a Parallel::Communicator instead.
Definition at line 53 of file serial_mesh.h.
     : ReplicatedMesh(dim)
   {
     libmesh_deprecated();
   }
libMesh::SerialMesh::SerialMesh (const UnstructuredMesh & other_mesh) inline
Definition at line 61 of file serial_mesh.h.
 : ReplicatedMesh(other_mesh) {}
libMesh::SerialMesh::~SerialMesh () inline
Definition at line 66 of file serial_mesh.h.
 {}
Member Function Documentation
virtual SimpleRange<element_iterator> libMesh::ReplicatedMesh::active_element_ptr_range () inline virtual inherited
Implements libMesh::MeshBase.
Definition at line 251 of file replicated_mesh.h.
References libMesh::ReplicatedMesh::active_elements_begin(), and libMesh::ReplicatedMesh::active_elements_end().
 { return {active_elements_begin(), active_elements_end()}; }
virtual SimpleRange<const_element_iterator> libMesh::ReplicatedMesh::active_element_ptr_range () const inline virtual inherited
Implements libMesh::MeshBase.
Definition at line 252 of file replicated_mesh.h.
References libMesh::ReplicatedMesh::active_elements_begin(), libMesh::ReplicatedMesh::active_elements_end(), libMesh::ReplicatedMesh::active_local_elements_begin(), libMesh::ReplicatedMesh::active_local_elements_end(), libMesh::ReplicatedMesh::active_semilocal_elements_begin(), libMesh::ReplicatedMesh::active_semilocal_elements_end(), libMesh::ReplicatedMesh::ancestor_elements_begin(), libMesh::ReplicatedMesh::ancestor_elements_end(), libMesh::ReplicatedMesh::facelocal_elements_begin(), libMesh::ReplicatedMesh::facelocal_elements_end(), libMesh::ReplicatedMesh::local_elements_begin(), libMesh::ReplicatedMesh::local_elements_end(), libMesh::ReplicatedMesh::not_active_elements_begin(), libMesh::ReplicatedMesh::not_active_elements_end(), libMesh::ReplicatedMesh::not_ancestor_elements_begin(), libMesh::ReplicatedMesh::not_ancestor_elements_end(), libMesh::ReplicatedMesh::not_local_elements_begin(), libMesh::ReplicatedMesh::not_local_elements_end(), libMesh::ReplicatedMesh::not_subactive_elements_begin(), libMesh::ReplicatedMesh::not_subactive_elements_end(), libMesh::ReplicatedMesh::semilocal_elements_begin(), libMesh::ReplicatedMesh::semilocal_elements_end(), libMesh::ReplicatedMesh::subactive_elements_begin(), and libMesh::ReplicatedMesh::subactive_elements_end().
 { return {active_elements_begin(), active_elements_end()}; }
virtual element_iterator libMesh::ReplicatedMesh::active_elements_begin () virtual inherited
Active, local, and negation forms of the element iterators described above. An "active" element is an element without children (i.e. has not been refined). A "local" element is one whose processor_id() matches the current processor.
Implements libMesh::MeshBase.
Referenced by libMesh::ReplicatedMesh::active_element_ptr_range(), libMesh::ReplicatedMesh::element_ptr_range(), libMesh::ReplicatedMesh::n_active_elem(), and libMesh::ReplicatedMesh::stitching_helper().
virtual const_element_iterator libMesh::ReplicatedMesh::active_elements_begin () const virtual inherited
Implements libMesh::MeshBase.
virtual element_iterator libMesh::ReplicatedMesh::active_elements_end () virtual inherited
Implements libMesh::MeshBase.
Referenced by libMesh::ReplicatedMesh::active_element_ptr_range(), libMesh::ReplicatedMesh::element_ptr_range(), and libMesh::ReplicatedMesh::n_active_elem().
virtual const_element_iterator libMesh::ReplicatedMesh::active_elements_end () const virtual inherited
Implements libMesh::MeshBase.
virtual SimpleRange<element_iterator> libMesh::ReplicatedMesh::active_local_element_ptr_range () inline virtual inherited
Implements libMesh::MeshBase.
Definition at line 308 of file replicated_mesh.h.
References libMesh::ReplicatedMesh::active_local_elements_begin(), and libMesh::ReplicatedMesh::active_local_elements_end().
 { return {active_local_elements_begin(), active_local_elements_end()}; }
virtual SimpleRange<const_element_iterator> libMesh::ReplicatedMesh::active_local_element_ptr_range () const inline virtual inherited
Implements libMesh::MeshBase.
Definition at line 309 of file replicated_mesh.h.
References libMesh::ReplicatedMesh::active_local_elements_begin(), libMesh::ReplicatedMesh::active_local_elements_end(), libMesh::ReplicatedMesh::active_local_subdomain_elements_begin(), libMesh::ReplicatedMesh::active_local_subdomain_elements_end(), libMesh::ReplicatedMesh::active_not_local_elements_begin(), libMesh::ReplicatedMesh::active_not_local_elements_end(), libMesh::ReplicatedMesh::active_pid_elements_begin(), libMesh::ReplicatedMesh::active_pid_elements_end(), libMesh::ReplicatedMesh::active_subdomain_elements_begin(), libMesh::ReplicatedMesh::active_subdomain_elements_end(), libMesh::ReplicatedMesh::active_subdomain_set_elements_begin(), libMesh::ReplicatedMesh::active_subdomain_set_elements_end(), libMesh::ReplicatedMesh::active_type_elements_begin(), libMesh::ReplicatedMesh::active_type_elements_end(), libMesh::ReplicatedMesh::active_unpartitioned_elements_begin(), libMesh::ReplicatedMesh::active_unpartitioned_elements_end(), libMesh::ReplicatedMesh::evaluable_elements_begin(), libMesh::ReplicatedMesh::evaluable_elements_end(), libMesh::ReplicatedMesh::flagged_elements_begin(), libMesh::ReplicatedMesh::flagged_elements_end(), libMesh::ReplicatedMesh::flagged_pid_elements_begin(), libMesh::ReplicatedMesh::flagged_pid_elements_end(), libMesh::ReplicatedMesh::ghost_elements_begin(), libMesh::ReplicatedMesh::ghost_elements_end(), libMesh::invalid_uint, libMesh::ReplicatedMesh::level_elements_begin(), libMesh::ReplicatedMesh::level_elements_end(), libMesh::ReplicatedMesh::local_level_elements_begin(), libMesh::ReplicatedMesh::local_level_elements_end(), libMesh::ReplicatedMesh::local_not_level_elements_begin(), libMesh::ReplicatedMesh::local_not_level_elements_end(), libMesh::ReplicatedMesh::nodes_begin(), libMesh::ReplicatedMesh::nodes_end(), libMesh::ReplicatedMesh::not_level_elements_begin(), libMesh::ReplicatedMesh::not_level_elements_end(), libMesh::ReplicatedMesh::pid_elements_begin(), libMesh::ReplicatedMesh::pid_elements_end(), libMesh::ReplicatedMesh::type_elements_begin(), libMesh::ReplicatedMesh::type_elements_end(), libMesh::ReplicatedMesh::unpartitioned_elements_begin(), and libMesh::ReplicatedMesh::unpartitioned_elements_end().
 { return {active_local_elements_begin(), active_local_elements_end()}; }
virtual element_iterator libMesh::ReplicatedMesh::active_local_elements_begin () virtual inherited
Implements libMesh::MeshBase.
Referenced by libMesh::ReplicatedMesh::active_element_ptr_range(), and libMesh::ReplicatedMesh::active_local_element_ptr_range().
virtual const_element_iterator libMesh::ReplicatedMesh::active_local_elements_begin () const virtual inherited
Implements libMesh::MeshBase.
virtual element_iterator libMesh::ReplicatedMesh::active_local_elements_end () virtual inherited
Implements libMesh::MeshBase.
Referenced by libMesh::ReplicatedMesh::active_element_ptr_range(), and libMesh::ReplicatedMesh::active_local_element_ptr_range().
virtual const_element_iterator libMesh::ReplicatedMesh::active_local_elements_end () const virtual inherited
Implements libMesh::MeshBase.
virtual element_iterator libMesh::ReplicatedMesh::active_local_subdomain_elements_begin (subdomain_id_type subdomain_id) virtual inherited
Implements libMesh::MeshBase.
Referenced by libMesh::ReplicatedMesh::active_local_element_ptr_range().
virtual const_element_iterator libMesh::ReplicatedMesh::active_local_subdomain_elements_begin (subdomain_id_type subdomain_id) const virtual inherited
Implements libMesh::MeshBase.
virtual element_iterator libMesh::ReplicatedMesh::active_local_subdomain_elements_end (subdomain_id_type subdomain_id) virtual inherited
Implements libMesh::MeshBase.
Referenced by libMesh::ReplicatedMesh::active_local_element_ptr_range().
virtual const_element_iterator libMesh::ReplicatedMesh::active_local_subdomain_elements_end (subdomain_id_type subdomain_id) const virtual inherited
Implements libMesh::MeshBase.
virtual node_iterator libMesh::ReplicatedMesh::active_nodes_begin () virtual inherited
Iterate over only the active nodes in the Mesh.
Implements libMesh::MeshBase.
Referenced by libMesh::ReplicatedMesh::node_ptr_range().
virtual const_node_iterator libMesh::ReplicatedMesh::active_nodes_begin () const virtual inherited
Implements libMesh::MeshBase.
virtual node_iterator libMesh::ReplicatedMesh::active_nodes_end () virtual inherited
Implements libMesh::MeshBase.
Referenced by libMesh::ReplicatedMesh::node_ptr_range().
virtual const_node_iterator libMesh::ReplicatedMesh::active_nodes_end () const virtual inherited
Implements libMesh::MeshBase.
virtual element_iterator libMesh::ReplicatedMesh::active_not_local_elements_begin () virtual inherited
Implements libMesh::MeshBase.
Referenced by libMesh::ReplicatedMesh::active_local_element_ptr_range().
virtual const_element_iterator libMesh::ReplicatedMesh::active_not_local_elements_begin () const virtual inherited
Implements libMesh::MeshBase.
virtual element_iterator libMesh::ReplicatedMesh::active_not_local_elements_end () virtual inherited
Implements libMesh::MeshBase.
Referenced by libMesh::ReplicatedMesh::active_local_element_ptr_range().
virtual const_element_iterator libMesh::ReplicatedMesh::active_not_local_elements_end () const virtual inherited
Implements libMesh::MeshBase.
virtual element_iterator libMesh::ReplicatedMesh::active_pid_elements_begin (processor_id_type proc_id) virtual inherited
Implements libMesh::MeshBase.
Referenced by libMesh::ReplicatedMesh::active_local_element_ptr_range().
virtual const_element_iterator libMesh::ReplicatedMesh::active_pid_elements_begin (processor_id_type proc_id) const virtual inherited
Implements libMesh::MeshBase.
virtual element_iterator libMesh::ReplicatedMesh::active_pid_elements_end (processor_id_type proc_id) virtual inherited
Implements libMesh::MeshBase.
Referenced by libMesh::ReplicatedMesh::active_local_element_ptr_range().
virtual const_element_iterator libMesh::ReplicatedMesh::active_pid_elements_end (processor_id_type proc_id) const virtual inherited
Implements libMesh::MeshBase.
virtual element_iterator libMesh::ReplicatedMesh::active_semilocal_elements_begin () virtual inherited
Implements libMesh::MeshBase.
Referenced by libMesh::ReplicatedMesh::active_element_ptr_range().
virtual const_element_iterator libMesh::ReplicatedMesh::active_semilocal_elements_begin () const virtual inherited
Implements libMesh::MeshBase.
virtual element_iterator libMesh::ReplicatedMesh::active_semilocal_elements_end () virtual inherited
Implements libMesh::MeshBase.
Referenced by libMesh::ReplicatedMesh::active_element_ptr_range().
virtual const_element_iterator libMesh::ReplicatedMesh::active_semilocal_elements_end () const virtual inherited
Implements libMesh::MeshBase.
virtual element_iterator libMesh::ReplicatedMesh::active_subdomain_elements_begin (subdomain_id_type subdomain_id) virtual inherited
Implements libMesh::MeshBase.
Referenced by libMesh::ReplicatedMesh::active_local_element_ptr_range().
virtual const_element_iterator libMesh::ReplicatedMesh::active_subdomain_elements_begin (subdomain_id_type subdomain_id) const virtual inherited
Implements libMesh::MeshBase.
virtual element_iterator libMesh::ReplicatedMesh::active_subdomain_elements_end (subdomain_id_type subdomain_id) virtual inherited
Implements libMesh::MeshBase.
Referenced by libMesh::ReplicatedMesh::active_local_element_ptr_range().
virtual const_element_iterator libMesh::ReplicatedMesh::active_subdomain_elements_end (subdomain_id_type subdomain_id) const virtual inherited
Implements libMesh::MeshBase.
virtual element_iterator libMesh::ReplicatedMesh::active_subdomain_set_elements_begin (std::set< subdomain_id_type > ss) virtual inherited
Implements libMesh::MeshBase.
Referenced by libMesh::ReplicatedMesh::active_local_element_ptr_range().
virtual const_element_iterator libMesh::ReplicatedMesh::active_subdomain_set_elements_begin (std::set< subdomain_id_type > ss) const virtual inherited
Implements libMesh::MeshBase.
virtual element_iterator libMesh::ReplicatedMesh::active_subdomain_set_elements_end (std::set< subdomain_id_type > ss) virtual inherited
Implements libMesh::MeshBase.
Referenced by libMesh::ReplicatedMesh::active_local_element_ptr_range().
virtual const_element_iterator libMesh::ReplicatedMesh::active_subdomain_set_elements_end (std::set< subdomain_id_type > ss) const virtual inherited
Implements libMesh::MeshBase.
virtual element_iterator libMesh::ReplicatedMesh::active_type_elements_begin (ElemType type) virtual inherited
Implements libMesh::MeshBase.
Referenced by libMesh::ReplicatedMesh::active_local_element_ptr_range().
virtual const_element_iterator libMesh::ReplicatedMesh::active_type_elements_begin (ElemType type) const virtual inherited
Implements libMesh::MeshBase.
virtual element_iterator libMesh::ReplicatedMesh::active_type_elements_end (ElemType type) virtual inherited
Implements libMesh::MeshBase.
Referenced by libMesh::ReplicatedMesh::active_local_element_ptr_range().
virtual const_element_iterator libMesh::ReplicatedMesh::active_type_elements_end (ElemType type) const virtual inherited
Implements libMesh::MeshBase.
virtual element_iterator libMesh::ReplicatedMesh::active_unpartitioned_elements_begin () virtual inherited
Iterate over active unpartitioned elements in the Mesh.
Implements libMesh::MeshBase.
Referenced by libMesh::ReplicatedMesh::active_local_element_ptr_range().
virtual const_element_iterator libMesh::ReplicatedMesh::active_unpartitioned_elements_begin () const virtual inherited
Implements libMesh::MeshBase.
virtual element_iterator libMesh::ReplicatedMesh::active_unpartitioned_elements_end () virtual inherited
Implements libMesh::MeshBase.
Referenced by libMesh::ReplicatedMesh::active_local_element_ptr_range().
virtual const_element_iterator libMesh::ReplicatedMesh::active_unpartitioned_elements_end () const virtual inherited
Implements libMesh::MeshBase.
Elem * libMesh::ReplicatedMesh::add_elem (Elem * e) virtual inherited
Add elem e to the end of the element array. To add an element locally, set e->processor_id() before adding it. To ensure a specific element id, call e->set_id() before adding it; only do this in parallel if you are manually keeping ids consistent.
Users should call MeshBase::prepare_for_use() after elements are added to and/or deleted from the mesh.
Implements libMesh::MeshBase.
Definition at line 286 of file replicated_mesh.C.
References libMesh::ReplicatedMesh::_elements, libMesh::MeshBase::_next_unique_id, libMesh::DofObject::id(), libmesh_nullptr, libMesh::DofObject::set_id(), libMesh::DofObject::set_unique_id(), libMesh::DofObject::valid_id(), and libMesh::DofObject::valid_unique_id().
Referenced by libMesh::ReplicatedMesh::reserve_elem().
 {
   libmesh_assert(e);
   // We no longer merely append elements with ReplicatedMesh
   // If the user requests a valid id that doesn't correspond to an
   // existing element, let's give them that id, resizing the elements
   // container if necessary.
   if (!e->valid_id())
     e->set_id (cast_int<dof_id_type>(_elements.size()));
 #ifdef LIBMESH_ENABLE_UNIQUE_ID
   if (!e->valid_unique_id())
     e->set_unique_id() = _next_unique_id++;
 #endif
   const dof_id_type id = e->id();
   if (id < _elements.size())
     {
       // Overwriting existing elements is still probably a mistake.
       libmesh_assert(!_elements[id]);
     }
   else
     {
       _elements.resize(id+1, libmesh_nullptr);
     }
   _elements[id] = e;
   return e;
 }
void libMesh::MeshBase::add_ghosting_functor (GhostingFunctor & ghosting_functor) inline inherited
Adds a functor which can specify ghosting requirements for use on distributed meshes. Multiple ghosting functors can be added; any element which is required by any functor will be ghosted.
GhostingFunctor memory must be managed by the code which calls this function; the GhostingFunctor lifetime is expected to extend until either the functor is removed or the Mesh is destructed.
Definition at line 787 of file mesh_base.h.
References libMesh::MeshBase::_ghosting_functors, and libMesh::MeshBase::remove_ghosting_functor().
Referenced by libMesh::DofMap::add_algebraic_ghosting_functor(), and libMesh::DofMap::add_coupling_functor().
   { _ghosting_functors.insert(&ghosting_functor); }
Node * libMesh::ReplicatedMesh::add_node (Node * n) virtual inherited
Add Node n to the end of the vertex array.
Implements libMesh::MeshBase.
Definition at line 456 of file replicated_mesh.C.
References libMesh::MeshBase::_next_unique_id, libMesh::ReplicatedMesh::_nodes, libMesh::DofObject::id(), libMesh::DofObject::set_id(), libMesh::DofObject::set_unique_id(), libMesh::DofObject::valid_id(), and libMesh::DofObject::valid_unique_id().
Referenced by libMesh::ReplicatedMesh::reserve_elem().
 {
   libmesh_assert(n);
   // We only append points with ReplicatedMesh
   libmesh_assert(!n->valid_id() || n->id() == _nodes.size());
   n->set_id (cast_int<dof_id_type>(_nodes.size()));
 #ifdef LIBMESH_ENABLE_UNIQUE_ID
   if (!n->valid_unique_id())
     n->set_unique_id() = _next_unique_id++;
 #endif
   _nodes.push_back(n);
   return n;
 }
Node * libMesh::ReplicatedMesh::add_point (const Point & p, const dof_id_type id = DofObject::invalid_id, const processor_id_type proc_id = DofObject::invalid_processor_id) virtual inherited
functions for adding /deleting nodes elements.
Implements libMesh::MeshBase.
Definition at line 403 of file replicated_mesh.C.
References libMesh::MeshBase::_next_unique_id, libMesh::ReplicatedMesh::_nodes, libMesh::Node::build(), libMesh::DofObject::invalid_id, libmesh_nullptr, libMesh::DofObject::processor_id(), libMesh::DofObject::set_unique_id(), and libMesh::DofObject::valid_unique_id().
Referenced by libMesh::ReplicatedMesh::reserve_elem().
 {
   //   // We only append points with ReplicatedMesh
   //   libmesh_assert(id == DofObject::invalid_id || id == _nodes.size());
   //   Node *n = Node::build(p, _nodes.size()).release();
   //   n->processor_id() = proc_id;
   //   _nodes.push_back (n);
   Node * n = libmesh_nullptr;
   // If the user requests a valid id, either
   // provide the existing node or resize the container
   // to fit the new node.
   if (id != DofObject::invalid_id)
     if (id < _nodes.size())
       n = _nodes[id];
     else
       _nodes.resize(id+1);
   else
     _nodes.push_back (static_cast<Node *>(libmesh_nullptr));
   // if the node already exists, then assign new (x,y,z) values
   if (n)
     *n = p;
   // otherwise build a new node, put it in the right spot, and return
   // a valid pointer.
   else
     {
       n = Node::build(p, (id == DofObject::invalid_id) ?
                       cast_int<dof_id_type>(_nodes.size()-1) : id).release();
       n->processor_id() = proc_id;
 #ifdef LIBMESH_ENABLE_UNIQUE_ID
       if (!n->valid_unique_id())
         n->set_unique_id() = _next_unique_id++;
 #endif
       if (id == DofObject::invalid_id)
         _nodes.back() = n;
       else
         _nodes[id] = n;
     }
   // better not pass back a NULL pointer.
   libmesh_assert (n);
   return n;
 }
void libMesh::UnstructuredMesh::all_first_order () virtual inherited
Converts a mesh with higher-order elements into a mesh with linear elements. For example, a mesh consisting of Tet10 will be converted to a mesh with Tet4 etc.
Prepare to identify (and then delete) a bunch of no-longer-used nodes.
Loop over the high-ordered elements. First make sure they are indeed high-order, and then replace them with an equivalent first-order element.
If the second order element had any boundary conditions they should be transferred to the first-order element. The old boundary conditions will be removed from the BoundaryInfo data structure by insert_elem.
Implements libMesh::MeshBase.
Definition at line 283 of file mesh_modification.C.
References libMesh::MeshBase::_is_prepared, libMesh::Elem::add_child(), libMesh::Elem::build(), libMesh::Elem::child_ptr(), libMesh::BoundaryInfo::copy_boundary_ids(), libMesh::MeshBase::delete_node(), libMesh::MeshBase::elements_begin(), libMesh::MeshBase::elements_end(), libMesh::Elem::first_order_equivalent_type(), libMesh::MeshBase::get_boundary_info(), libMesh::Elem::has_children(), libMesh::DofObject::id(), libMesh::MeshBase::insert_elem(), libMesh::MeshBase::max_node_id(), libMesh::Elem::n_children(), libMesh::Elem::n_sides(), libMesh::Elem::n_vertices(), libMesh::Elem::neighbor_ptr(), libMesh::Elem::node_id(), libMesh::Elem::node_ptr(), libMesh::MeshBase::nodes_begin(), libMesh::MeshBase::nodes_end(), libMesh::Elem::p_level(), libMesh::Elem::p_refinement_flag(), libMesh::Elem::parent(), libMesh::MeshBase::prepare_for_use(), libMesh::DofObject::processor_id(), libMesh::Elem::refinement_flag(), libMesh::BoundaryInfo::regenerate_id_sets(), libMesh::remote_elem, libMesh::MeshBase::renumber_nodes_and_elements(), libMesh::Elem::replace_child(), libMesh::DofObject::set_id(), libMesh::Elem::set_neighbor(), libMesh::Elem::set_node(), libMesh::Partitioner::set_node_processor_ids(), libMesh::Elem::set_p_level(), libMesh::Elem::set_p_refinement_flag(), libMesh::Elem::set_parent(), libMesh::Elem::set_refinement_flag(), libMesh::DofObject::set_unique_id(), libMesh::Elem::subdomain_id(), libMesh::Elem::type(), libMesh::DofObject::unique_id(), and libMesh::Elem::which_child_am_i().
 {
   /*
    * when the mesh is not prepared,
    * at least renumber the nodes and
    * elements, so that the node ids
    * are correct
    */
   if (!this->_is_prepared)
     this->renumber_nodes_and_elements ();
   START_LOG("all_first_order()", "Mesh");
   std::vector<bool> node_touched_by_me(this->max_node_id(), false);
   element_iterator endit = elements_end();
   for (element_iterator it = elements_begin();
        it != endit; ++it)
     {
       Elem * so_elem = *it;
       libmesh_assert(so_elem);
       /*
        * build the first-order equivalent, add to
        * the new_elements list.
        */
       Elem * lo_elem = Elem::build
         (Elem::first_order_equivalent_type
          (so_elem->type()), so_elem->parent()).release();
       const unsigned short n_sides = so_elem->n_sides();
       for (unsigned short s=0; s != n_sides; ++s)
         if (so_elem->neighbor_ptr(s) == remote_elem)
           lo_elem->set_neighbor(s, const_cast<RemoteElem *>(remote_elem));
 #ifdef LIBMESH_ENABLE_AMR
       /*
        * Reset the parent links of any child elements
        */
       if (so_elem->has_children())
         for (unsigned int c = 0, nc = so_elem->n_children(); c != nc; ++c)
           {
             Elem * child = so_elem->child_ptr(c);
             child->set_parent(lo_elem);
             lo_elem->add_child(child, c);
           }
       /*
        * Reset the child link of any parent element
        */
       if (so_elem->parent())
         {
           unsigned int c =
             so_elem->parent()->which_child_am_i(so_elem);
           lo_elem->parent()->replace_child(lo_elem, c);
         }
       /*
        * Copy as much data to the new element as makes sense
        */
       lo_elem->set_p_level(so_elem->p_level());
       lo_elem->set_refinement_flag(so_elem->refinement_flag());
       lo_elem->set_p_refinement_flag(so_elem->p_refinement_flag());
 #endif
       libmesh_assert_equal_to (lo_elem->n_vertices(), so_elem->n_vertices());
       /*
        * By definition the vertices of the linear and
        * second order element are identically numbered.
        * transfer these.
        */
       for (unsigned int v=0; v < so_elem->n_vertices(); v++)
         {
           lo_elem->set_node(v) = so_elem->node_ptr(v);
           node_touched_by_me[lo_elem->node_id(v)] = true;
         }
       /*
        * find_neighbors relies on remote_elem neighbor links being
        * properly maintained.
        */
       for (unsigned short s=0; s != n_sides; s++)
         {
           if (so_elem->neighbor_ptr(s) == remote_elem)
             lo_elem->set_neighbor(s, const_cast<RemoteElem*>(remote_elem));
         }
       this->get_boundary_info().copy_boundary_ids
         (this->get_boundary_info(), so_elem, lo_elem);
       /*
        * The new first-order element is ready.
        * Inserting it into the mesh will replace and delete
        * the second-order element.
        */
       lo_elem->set_id(so_elem->id());
 #ifdef LIBMESH_ENABLE_UNIQUE_ID
       lo_elem->set_unique_id() = so_elem->unique_id();
 #endif
       lo_elem->processor_id() = so_elem->processor_id();
       lo_elem->subdomain_id() = so_elem->subdomain_id();
       this->insert_elem(lo_elem);
     }
   const MeshBase::node_iterator nd_end = this->nodes_end();
   MeshBase::node_iterator nd = this->nodes_begin();
   while (nd != nd_end)
     {
       Node * the_node = *nd;
       ++nd;
       if (!node_touched_by_me[the_node->id()])
         this->delete_node(the_node);
     }
   // If crazy people applied boundary info to non-vertices and then
   // deleted those non-vertices, we should make sure their boundary id
   // caches are correct.
   this->get_boundary_info().regenerate_id_sets();
   STOP_LOG("all_first_order()", "Mesh");
   // On hanging nodes that used to also be second order nodes, we
   // might now have an invalid nodal processor_id()
   Partitioner::set_node_processor_ids(*this);
   // delete or renumber nodes if desired
   this->prepare_for_use();
 }
void libMesh::UnstructuredMesh::all_second_order (const bool full_ordered = true) virtual inherited
Converts a (conforming, non-refined) mesh with linear elements into a mesh with second-order elements. For example, a mesh consisting of Tet4 will be converted to a mesh with Tet10 etc.
Note
For some elements like Hex8 there exist two higher order equivalents, Hex20 and Hex27. When full_ordered is true (default), then Hex27 is built. Otherwise, Hex20 is built. The same holds obviously for Quad4, Prism6, etc.
Loop over the low-ordered elements in the elements vector. First make sure they _are indeed low-order, and then replace them with an equivalent second-order element. Don't forget to delete the low-order element, or else it will leak!
If the linear element had any boundary conditions they should be transferred to the second-order element. The old boundary conditions will be removed from the BoundaryInfo data structure by insert_elem.
Also, prepare_for_use() will reconstruct most of our neighbor links, but if we have any remote_elem links in a distributed mesh, they need to be preserved. We do that in the same loop here.
Implements libMesh::MeshBase.
Definition at line 431 of file mesh_modification.C.
References libMesh::MeshBase::_is_prepared, libMesh::MeshBase::add_point(), libMesh::Elem::build(), libMesh::ParallelObject::comm(), libMesh::BoundaryInfo::copy_boundary_ids(), libMesh::Elem::default_order(), libMesh::MeshBase::elements_begin(), libMesh::MeshBase::elements_end(), libMesh::FIRST, libMesh::MeshBase::get_boundary_info(), libMesh::DofObject::id(), libMesh::MeshBase::insert_elem(), libMesh::DofObject::invalid_id, libMesh::MeshBase::is_serial(), libMesh::Elem::level(), libMesh::MeshCommunication::make_nodes_parallel_consistent(), libMesh::Parallel::Communicator::max(), libMesh::MeshBase::mesh_dimension(), libMesh::MeshBase::n_elem(), libMesh::MeshBase::n_nodes(), libMesh::Elem::n_vertices(), libMesh::Elem::neighbor_ptr(), libMesh::Elem::node_ptr(), libMesh::MeshBase::point(), libMesh::MeshBase::prepare_for_use(), libMesh::DofObject::processor_id(), libMesh::Real, libMesh::remote_elem, libMesh::MeshBase::renumber_nodes_and_elements(), libMesh::MeshBase::reserve_nodes(), libMesh::Elem::second_order_equivalent_type(), libMesh::Elem::side_index_range(), libMesh::Elem::subdomain_id(), libMesh::Elem::type(), and libMesh::DofObject::unique_id().
Referenced by libMesh::MeshTools::Generation::build_cube(), and libMesh::MeshTools::Generation::build_sphere().
 {
   // This function must be run on all processors at once
   parallel_object_only();
   /*
    * when the mesh is not prepared,
    * at least renumber the nodes and
    * elements, so that the node ids
    * are correct
    */
   if (!this->_is_prepared)
     this->renumber_nodes_and_elements ();
   /*
    * If the mesh is empty
    * then we have nothing to do
    */
   if (!this->n_elem())
     return;
   /*
    * If the mesh is already second order
    * then we have nothing to do.
    * We have to test for this in a round-about way to avoid
    * a bug on distributed parallel meshes with more processors
    * than elements.
    */
   bool already_second_order = false;
   if (this->elements_begin() != this->elements_end() &&
       (*(this->elements_begin()))->default_order() != FIRST)
     already_second_order = true;
   this->comm().max(already_second_order);
   if (already_second_order)
     return;
   START_LOG("all_second_order()", "Mesh");
   /*
    * this map helps in identifying second order
    * nodes.  Namely, a second-order node:
    * - edge node
    * - face node
    * - bubble node
    * is uniquely defined through a set of adjacent
    * vertices.  This set of adjacent vertices is
    * used to identify already added higher-order
    * nodes.  We are safe to use node id's since we
    * make sure that these are correctly numbered.
    */
   std::map<std::vector<dof_id_type>, Node *> adj_vertices_to_so_nodes;
   /*
    * for speed-up of the \p add_point() method, we
    * can reserve memory.  Guess the number of additional
    * nodes for different dimensions
    */
   switch (this->mesh_dimension())
     {
     case 1:
       /*
        * in 1D, there can only be order-increase from Edge2
        * to Edge3.  Something like 1/2 of n_nodes() have
        * to be added
        */
       this->reserve_nodes(static_cast<unsigned int>
                           (1.5*static_cast<double>(this->n_nodes())));
       break;
     case 2:
       /*
        * in 2D, either refine from Tri3 to Tri6 (double the nodes)
        * or from Quad4 to Quad8 (again, double) or Quad9 (2.25 that much)
        */
       this->reserve_nodes(static_cast<unsigned int>
                           (2*static_cast<double>(this->n_nodes())));
       break;
     case 3:
       /*
        * in 3D, either refine from Tet4 to Tet10 (factor = 2.5) up to
        * Hex8 to Hex27 (something  > 3).  Since in 3D there _are_ already
        * quite some nodes, and since we do not want to overburden the memory by
        * a too conservative guess, use the lower bound
        */
       this->reserve_nodes(static_cast<unsigned int>
                           (2.5*static_cast<double>(this->n_nodes())));
       break;
     default:
       // Hm?
       libmesh_error_msg("Unknown mesh dimension " << this->mesh_dimension());
     }
   /*
    * form a vector that will hold the node id's of
    * the vertices that are adjacent to the son-th
    * second-order node.  Pull this outside of the
    * loop so that silly compilers don't repeatedly
    * create and destroy the vector.
    */
   std::vector<dof_id_type> adjacent_vertices_ids;
   element_iterator
     it = elements_begin(),
     endit = elements_end();
   for (; it != endit; ++it)
     {
       // the linear-order element
       Elem * lo_elem = *it;
       libmesh_assert(lo_elem);
       // make sure it is linear order
       if (lo_elem->default_order() != FIRST)
         libmesh_error_msg("ERROR: This is not a linear element: type=" << lo_elem->type());
       // this does _not_ work for refined elements
       libmesh_assert_equal_to (lo_elem->level (), 0);
       /*
        * build the second-order equivalent, add to
        * the new_elements list.  Note that this here
        * is the only point where \p full_ordered
        * is necessary.  The remaining code works well
        * for either type of second-order equivalent, e.g.
        * Hex20 or Hex27, as equivalents for Hex8
        */
       Elem * so_elem =
         Elem::build (Elem::second_order_equivalent_type(lo_elem->type(),
                                                         full_ordered) ).release();
       libmesh_assert_equal_to (lo_elem->n_vertices(), so_elem->n_vertices());
       /*
        * By definition the vertices of the linear and
        * second order element are identically numbered.
        * transfer these.
        */
       for (unsigned int v=0; v < lo_elem->n_vertices(); v++)
         so_elem->set_node(v) = lo_elem->node_ptr(v);
       /*
        * Now handle the additional mid-side nodes.  This
        * is simply handled through a map that remembers
        * the already-added nodes.  This map maps the global
        * ids of the vertices (that uniquely define this
        * higher-order node) to the new node.
        * Notation: son = second-order node
        */
       const unsigned int son_begin = so_elem->n_vertices();
       const unsigned int son_end   = so_elem->n_nodes();
       for (unsigned int son=son_begin; son<son_end; son++)
         {
           const unsigned int n_adjacent_vertices =
             so_elem->n_second_order_adjacent_vertices(son);
           adjacent_vertices_ids.resize(n_adjacent_vertices);
           for (unsigned int v=0; v<n_adjacent_vertices; v++)
             adjacent_vertices_ids[v] =
               so_elem->node_id( so_elem->second_order_adjacent_vertex(son,v) );
           /*
            * \p adjacent_vertices_ids is now in order of the current
            * side.  sort it, so that comparisons  with the
            * \p adjacent_vertices_ids created through other elements'
            * sides can match
            */
           std::sort(adjacent_vertices_ids.begin(),
                     adjacent_vertices_ids.end());
           // does this set of vertices already has a mid-node added?
           std::pair<std::map<std::vector<dof_id_type>, Node *>::iterator,
                     std::map<std::vector<dof_id_type>, Node *>::iterator>
             pos = adj_vertices_to_so_nodes.equal_range (adjacent_vertices_ids);
           // no, not added yet
           if (pos.first == pos.second)
             {
               /*
                * for this set of vertices, there is no
                * second_order node yet.  Add it.
                *
                * compute the location of the new node as
                * the average over the adjacent vertices.
                */
               Point new_location = this->point(adjacent_vertices_ids[0]);
               for (unsigned int v=1; v<n_adjacent_vertices; v++)
                 new_location += this->point(adjacent_vertices_ids[v]);
               new_location /= static_cast<Real>(n_adjacent_vertices);
               /* Add the new point to the mesh.
                * If we are on a serialized mesh, then we're doing this
                * all in sync, and the node processor_id will be
                * consistent between processors.
                * If we are on a distributed mesh, we can fix
                * inconsistent processor ids later, but only if every
                * processor gives new nodes a *locally* consistent
                * processor id, so we'll give the new node the
                * processor id of an adjacent element for now and then
                * we'll update that later if appropriate.
                */
               Node * so_node = this->add_point
                 (new_location, DofObject::invalid_id,
                  lo_elem->processor_id());
               /*
                * insert the new node with its defining vertex
                * set into the map, and relocate pos to this
                * new entry, so that the so_elem can use
                * \p pos for inserting the node
                */
               adj_vertices_to_so_nodes.insert(pos.first,
                                               std::make_pair(adjacent_vertices_ids,
                                                              so_node));
               so_elem->set_node(son) = so_node;
             }
           // yes, already added.
           else
             {
               Node * so_node = pos.first->second;
               libmesh_assert(so_node);
               so_elem->set_node(son) = so_node;
               // We need to ensure that the processor who should own a
               // node *knows* they own the node.
               if (so_node->processor_id() > lo_elem->processor_id())
                 so_node->processor_id() = lo_elem->processor_id();
             }
         }
       /*
        * find_neighbors relies on remote_elem neighbor links being
        * properly maintained.
        */
       for (auto s : lo_elem->side_index_range())
         {
           if (lo_elem->neighbor_ptr(s) == remote_elem)
             so_elem->set_neighbor(s, const_cast<RemoteElem*>(remote_elem));
         }
       this->get_boundary_info().copy_boundary_ids
         (this->get_boundary_info(), lo_elem, so_elem);
       /*
        * The new second-order element is ready.
        * Inserting it into the mesh will replace and delete
        * the first-order element.
        */
       so_elem->set_id(lo_elem->id());
 #ifdef LIBMESH_ENABLE_UNIQUE_ID
       so_elem->set_unique_id() = lo_elem->unique_id();
 #endif
       so_elem->processor_id() = lo_elem->processor_id();
       so_elem->subdomain_id() = lo_elem->subdomain_id();
       this->insert_elem(so_elem);
     }
   // we can clear the map
   adj_vertices_to_so_nodes.clear();
   STOP_LOG("all_second_order()", "Mesh");
   // In a DistributedMesh our ghost node processor ids may be bad,
   // the ids of nodes touching remote elements may be inconsistent,
   // and unique_ids of newly added non-local nodes remain unset.
   // make_nodes_parallel_consistent() will fix all this.
   if (!this->is_serial())
     MeshCommunication().make_nodes_parallel_consistent (*this);
   // renumber nodes, elements etc
   this->prepare_for_use(/*skip_renumber =*/ false);
 }
virtual void libMesh::MeshBase::allgather () inline virtual inherited
Gathers all elements and nodes of the mesh onto every processor
Reimplemented in libMesh::DistributedMesh.
Definition at line 170 of file mesh_base.h.
Referenced by libMesh::ParmetisPartitioner::_do_repartition(), libMesh::EquationSystems::allgather(), and libMesh::MeshSerializer::MeshSerializer().
 {}
void libMesh::MeshBase::allow_remote_element_removal (bool allow) inline inherited
If false is passed in then this mesh will no longer have remote elements deleted when being prepared for use; i.e. even a DistributedMesh will remain (if it is already) serialized. This may adversely affect performance and memory use.
Definition at line 759 of file mesh_base.h.
References libMesh::MeshBase::_allow_remote_element_removal.
Referenced by libMesh::UnstructuredMesh::copy_nodes_and_elements().
 { _allow_remote_element_removal = allow; }
bool libMesh::MeshBase::allow_remote_element_removal () const inline inherited
Definition at line 760 of file mesh_base.h.
References libMesh::MeshBase::_allow_remote_element_removal.
Referenced by libMesh::UnstructuredMesh::copy_nodes_and_elements().
 { return _allow_remote_element_removal; }
void libMesh::MeshBase::allow_renumbering (bool allow) inline inherited
If false is passed in then this mesh will no longer be renumbered when being prepared for use. This may slightly adversely affect performance during subsequent element access, particularly when using a distributed mesh.
Definition at line 750 of file mesh_base.h.
References libMesh::MeshBase::_skip_renumber_nodes_and_elements.
Referenced by libMesh::UnstructuredMesh::copy_nodes_and_elements(), libMesh::AdjointRefinementEstimator::estimate_error(), libMesh::ErrorVector::plot_error(), libMesh::NameBasedIO::read(), and libMesh::GMVIO::read().
 { _skip_renumber_nodes_and_elements = !allow; }
bool libMesh::MeshBase::allow_renumbering () const inline inherited
Definition at line 751 of file mesh_base.h.
References libMesh::MeshBase::_skip_renumber_nodes_and_elements.
Referenced by libMesh::UnstructuredMesh::copy_nodes_and_elements(), libMesh::MeshBase::prepare_for_use(), and libMesh::UnstructuredMesh::read().
 { return !_skip_renumber_nodes_and_elements; }
virtual element_iterator libMesh::ReplicatedMesh::ancestor_elements_begin () virtual inherited
Iterate over elements for which elem->ancestor() is true.
Implements libMesh::MeshBase.
Referenced by libMesh::ReplicatedMesh::active_element_ptr_range().
virtual const_element_iterator libMesh::ReplicatedMesh::ancestor_elements_begin () const virtual inherited
Implements libMesh::MeshBase.
virtual element_iterator libMesh::ReplicatedMesh::ancestor_elements_end () virtual inherited
Implements libMesh::MeshBase.
Referenced by libMesh::ReplicatedMesh::active_element_ptr_range().
virtual const_element_iterator libMesh::ReplicatedMesh::ancestor_elements_end () const virtual inherited
Implements libMesh::MeshBase.
virtual node_iterator libMesh::ReplicatedMesh::bid_nodes_begin (boundary_id_type bndry_id) virtual inherited
Iterate over nodes for which BoundaryInfo::has_boundary_id(node, bndry_id) is true.
Implements libMesh::MeshBase.
Referenced by libMesh::ReplicatedMesh::local_node_ptr_range().
virtual const_node_iterator libMesh::ReplicatedMesh::bid_nodes_begin (boundary_id_type bndry_id) const virtual inherited
Implements libMesh::MeshBase.
virtual node_iterator libMesh::ReplicatedMesh::bid_nodes_end (boundary_id_type bndry_id) virtual inherited
Implements libMesh::MeshBase.
Referenced by libMesh::ReplicatedMesh::local_node_ptr_range().
virtual const_node_iterator libMesh::ReplicatedMesh::bid_nodes_end (boundary_id_type bndry_id) const virtual inherited
Implements libMesh::MeshBase.
virtual node_iterator libMesh::ReplicatedMesh::bnd_nodes_begin () virtual inherited
Iterate over nodes for which BoundaryInfo::n_boundary_ids(node) > 0.
Implements libMesh::MeshBase.
Referenced by libMesh::ReplicatedMesh::local_node_ptr_range().
virtual const_node_iterator libMesh::ReplicatedMesh::bnd_nodes_begin () const virtual inherited
Implements libMesh::MeshBase.
virtual node_iterator libMesh::ReplicatedMesh::bnd_nodes_end () virtual inherited
Implements libMesh::MeshBase.
Referenced by libMesh::ReplicatedMesh::local_node_ptr_range().
virtual const_node_iterator libMesh::ReplicatedMesh::bnd_nodes_end () const virtual inherited
Implements libMesh::MeshBase.
void libMesh::MeshBase::cache_elem_dims () inherited
Search the mesh and cache the different dimensions of the elements present in the mesh. This is done in prepare_for_use(), but can be done manually by other classes after major mesh modifications.
Definition at line 614 of file mesh_base.C.
References libMesh::MeshBase::_elem_dims, libMesh::MeshBase::_spatial_dimension, libMesh::MeshBase::active_elements_begin(), libMesh::MeshBase::active_elements_end(), libMesh::ParallelObject::comm(), end, libMesh::MeshBase::mesh_dimension(), libMesh::MeshBase::node(), libMesh::MeshBase::nodes_begin(), libMesh::MeshBase::nodes_end(), and libMesh::Parallel::Communicator::set_union().
Referenced by libMesh::MeshCommunication::broadcast(), libMesh::MeshBase::get_subdomain_name_map(), and libMesh::MeshBase::prepare_for_use().
 {
   // This requires an inspection on every processor
   parallel_object_only();
   // Need to clear _elem_dims first in case all elements of a
   // particular dimension have been deleted.
   _elem_dims.clear();
   const_element_iterator el  = this->active_elements_begin();
   const_element_iterator end = this->active_elements_end();
   for (; el!=end; ++el)
     _elem_dims.insert((*el)->dim());
   // Some different dimension elements may only live on other processors
   this->comm().set_union(_elem_dims);
   // If the largest element dimension found is larger than the current
   // _spatial_dimension, increase _spatial_dimension.
   unsigned int max_dim = this->mesh_dimension();
   if (max_dim > _spatial_dimension)
     _spatial_dimension = cast_int<unsigned char>(max_dim);
   // _spatial_dimension may need to increase from 1->2 or 2->3 if the
   // mesh is full of 1D elements but they are not x-aligned, or the
   // mesh is full of 2D elements but they are not in the x-y plane.
   // If the mesh is x-aligned or x-y planar, we will end up checking
   // every node's coordinates and not breaking out of the loop
   // early...
   if (_spatial_dimension < 3)
     {
       const_node_iterator node_it  = this->nodes_begin();
       const_node_iterator node_end = this->nodes_end();
       for (; node_it != node_end; ++node_it)
         {
           Node & node = **node_it;
 #if LIBMESH_DIM > 1
           // Note: the exact floating point comparison is intentional,
           // we don't want to get tripped up by tolerances.
           if (node(1) != 0.)
             {
               _spatial_dimension = 2;
 #if LIBMESH_DIM == 2
               // If libmesh is compiled in 2D mode, this is the
               // largest spatial dimension possible so we can break
               // out.
               break;
 #endif
             }
 #endif
 #if LIBMESH_DIM > 2
           if (node(2) != 0.)
             {
               // Spatial dimension can't get any higher than this, so
               // we can break out.
               _spatial_dimension = 3;
               break;
             }
 #endif
         }
     }
 }
void libMesh::ReplicatedMesh::clear () virtual inherited
Clear all internal data.
Reimplemented from libMesh::MeshBase.
Definition at line 573 of file replicated_mesh.C.
References libMesh::ReplicatedMesh::_elements, libMesh::ReplicatedMesh::_nodes, libMesh::MeshBase::clear(), and end.
Referenced by libMesh::ReplicatedMesh::clone(), and libMesh::ReplicatedMesh::~ReplicatedMesh().
 {
   // Call parent clear function
   MeshBase::clear();
   // Clear our elements and nodes
   {
     std::vector<Elem *>::iterator       it  = _elements.begin();
     const std::vector<Elem *>::iterator end = _elements.end();
     // There is no need to remove the elements from
     // the BoundaryInfo data structure since we
     // already cleared it.
     for (; it != end; ++it)
       delete *it;
     _elements.clear();
   }
   // clear the nodes data structure
   {
     std::vector<Node *>::iterator       it  = _nodes.begin();
     const std::vector<Node *>::iterator end = _nodes.end();
     // There is no need to remove the nodes from
     // the BoundaryInfo data structure since we
     // already cleared it.
     for (; it != end; ++it)
       delete *it;
     _nodes.clear();
   }
 }
void libMesh::MeshBase::clear_point_locator () inherited
Releases the current PointLocator object.
Definition at line 557 of file mesh_base.C.
References libMesh::MeshBase::_point_locator, and libmesh_nullptr.
Referenced by libMesh::MeshCommunication::broadcast(), libMesh::MeshBase::clear(), libMesh::UnstructuredMesh::contract(), libMesh::MeshCommunication::delete_remote_elements(), libMesh::MeshCommunication::gather(), libMesh::MeshCommunication::gather_neighboring_elements(), libMesh::MeshBase::prepare_for_use(), and libMesh::MeshCommunication::redistribute().
 {
   _point_locator.reset(libmesh_nullptr);
 }
virtual std::unique_ptr<MeshBase> libMesh::SerialMesh::clone () const inline virtual
Virtual copy-constructor, creates a copy of this mesh
Reimplemented from libMesh::ReplicatedMesh.
Definition at line 63 of file serial_mesh.h.
   { return libmesh_make_unique<SerialMesh>(*this); }
const Parallel::Communicator& libMesh::ParallelObject::comm () const inline inherited
Returns
A reference to the Parallel::Communicator object used by this mesh.
Definition at line 87 of file parallel_object.h.
References libMesh::ParallelObject::_communicator.
Referenced by libMesh::__libmesh_petsc_diff_solver_jacobian(), libMesh::__libmesh_petsc_diff_solver_monitor(), libMesh::__libmesh_petsc_diff_solver_residual(), libMesh::__libmesh_petsc_snes_fd_residual(), libMesh::__libmesh_petsc_snes_jacobian(), libMesh::__libmesh_petsc_snes_mffd_residual(), libMesh::__libmesh_petsc_snes_postcheck(), libMesh::__libmesh_petsc_snes_residual(), libMesh::__libmesh_tao_equality_constraints(), libMesh::__libmesh_tao_equality_constraints_jacobian(), libMesh::__libmesh_tao_gradient(), libMesh::__libmesh_tao_hessian(), libMesh::__libmesh_tao_inequality_constraints(), libMesh::__libmesh_tao_inequality_constraints_jacobian(), libMesh::__libmesh_tao_objective(), libMesh::MeshRefinement::_coarsen_elements(), libMesh::ExactSolution::_compute_error(), libMesh::ParmetisPartitioner::_do_repartition(), libMesh::UniformRefinementEstimator::_estimate_error(), libMesh::BoundaryInfo::_find_id_maps(), libMesh::PetscLinearSolver< T >::_petsc_shell_matrix_get_diagonal(), libMesh::SlepcEigenSolver< T >::_petsc_shell_matrix_get_diagonal(), libMesh::PetscLinearSolver< T >::_petsc_shell_matrix_mult(), libMesh::SlepcEigenSolver< T >::_petsc_shell_matrix_mult(), libMesh::PetscLinearSolver< T >::_petsc_shell_matrix_mult_add(), libMesh::EquationSystems::_read_impl(), libMesh::MeshRefinement::_refine_elements(), libMesh::MeshRefinement::_smooth_flags(), libMesh::ImplicitSystem::add_matrix(), libMesh::System::add_vector(), libMesh::EigenSparseLinearSolver< T >::adjoint_solve(), libMesh::UnstructuredMesh::all_second_order(), libMesh::MeshTools::Modification::all_tri(), libMesh::LaplaceMeshSmoother::allgather_graph(), libMesh::FEMSystem::assemble_qoi(), libMesh::MeshCommunication::assign_global_indices(), libMesh::ParmetisPartitioner::assign_partitioning(), libMesh::DofMap::attach_matrix(), libMesh::Parallel::BinSorter< KeyType, IdxType >::binsort(), libMesh::Parallel::Sort< KeyType, IdxType >::binsort(), libMesh::MeshCommunication::broadcast(), libMesh::SparseMatrix< T >::build(), libMesh::MeshTools::Generation::build_extrusion(), libMesh::Parallel::Histogram< KeyType, IdxType >::build_histogram(), libMesh::PetscNonlinearSolver< T >::build_mat_null_space(), libMesh::BoundaryInfo::build_node_list_from_side_list(), libMesh::EquationSystems::build_parallel_solution_vector(), libMesh::MeshBase::cache_elem_dims(), libMesh::System::calculate_norm(), libMesh::DofMap::check_dirichlet_bcid_consistency(), libMesh::DistributedVector< T >::clone(), libMesh::EigenSparseVector< T >::clone(), libMesh::LaspackVector< T >::clone(), libMesh::EpetraVector< T >::clone(), libMesh::PetscVector< T >::clone(), libMesh::EpetraVector< T >::close(), libMesh::Parallel::Sort< KeyType, IdxType >::communicate_bins(), libMesh::Nemesis_IO_Helper::compute_num_global_elem_blocks(), libMesh::Nemesis_IO_Helper::compute_num_global_nodesets(), libMesh::Nemesis_IO_Helper::compute_num_global_sidesets(), libMesh::Problem_Interface::computeF(), libMesh::Problem_Interface::computeJacobian(), libMesh::Problem_Interface::computePreconditioner(), libMesh::ExodusII_IO::copy_elemental_solution(), libMesh::MeshTools::correct_node_proc_ids(), libMesh::MeshTools::create_bounding_box(), libMesh::MeshTools::create_nodal_bounding_box(), libMesh::MeshRefinement::create_parent_error_vector(), libMesh::MeshTools::create_processor_bounding_box(), libMesh::MeshTools::create_subdomain_bounding_box(), libMesh::MeshCommunication::delete_remote_elements(), libMesh::DofMap::distribute_dofs(), DMlibMeshFunction(), DMlibMeshJacobian(), DMlibMeshSetSystem_libMesh(), DMVariableBounds_libMesh(), libMesh::MeshRefinement::eliminate_unrefined_patches(), libMesh::EpetraVector< T >::EpetraVector(), libMesh::WeightedPatchRecoveryErrorEstimator::estimate_error(), libMesh::PatchRecoveryErrorEstimator::estimate_error(), libMesh::JumpErrorEstimator::estimate_error(), libMesh::AdjointRefinementEstimator::estimate_error(), libMesh::ExactErrorEstimator::estimate_error(), libMesh::MeshRefinement::flag_elements_by_elem_fraction(), libMesh::MeshRefinement::flag_elements_by_error_fraction(), libMesh::MeshRefinement::flag_elements_by_nelem_target(), libMesh::MeshCommunication::gather(), libMesh::MeshCommunication::gather_neighboring_elements(), libMesh::CondensedEigenSystem::get_eigenpair(), libMesh::DofMap::get_info(), libMesh::ImplicitSystem::get_linear_solver(), libMesh::EquationSystems::get_solution(), libMesh::LocationMap< T >::init(), libMesh::TopologyMap::init(), libMesh::TimeSolver::init(), libMesh::TaoOptimizationSolver< T >::init(), libMesh::PetscNonlinearSolver< T >::init(), libMesh::DistributedVector< T >::init(), libMesh::EpetraVector< T >::init(), libMesh::PetscVector< T >::init(), libMesh::SystemSubsetBySubdomain::init(), libMesh::EigenSystem::init_data(), libMesh::EigenSystem::init_matrices(), libMesh::ParmetisPartitioner::initialize(), libMesh::OptimizationSystem::initialize_equality_constraints_storage(), libMesh::OptimizationSystem::initialize_inequality_constraints_storage(), libMesh::MeshTools::libmesh_assert_parallel_consistent_procids< Elem >(), libMesh::MeshTools::libmesh_assert_parallel_consistent_procids< Node >(), libMesh::MeshTools::libmesh_assert_topology_consistent_procids< Node >(), libMesh::MeshTools::libmesh_assert_valid_boundary_ids(), libMesh::MeshTools::libmesh_assert_valid_dof_ids(), libMesh::MeshTools::libmesh_assert_valid_neighbors(), libMesh::DistributedMesh::libmesh_assert_valid_parallel_flags(), libMesh::DistributedMesh::libmesh_assert_valid_parallel_object_ids(), libMesh::DistributedMesh::libmesh_assert_valid_parallel_p_levels(), libMesh::MeshTools::libmesh_assert_valid_refinement_flags(), libMesh::MeshTools::libmesh_assert_valid_unique_ids(), libMesh::libmesh_petsc_snes_residual_helper(), libMesh::MeshRefinement::limit_level_mismatch_at_edge(), libMesh::MeshRefinement::limit_level_mismatch_at_node(), libMesh::MeshRefinement::limit_overrefined_boundary(), libMesh::MeshRefinement::limit_underrefined_boundary(), libMesh::MeshRefinement::make_coarsening_compatible(), libMesh::MeshCommunication::make_elems_parallel_consistent(), libMesh::MeshRefinement::make_flags_parallel_consistent(), libMesh::MeshCommunication::make_new_node_proc_ids_parallel_consistent(), libMesh::MeshCommunication::make_new_nodes_parallel_consistent(), libMesh::MeshCommunication::make_node_ids_parallel_consistent(), libMesh::MeshCommunication::make_node_proc_ids_parallel_consistent(), libMesh::MeshCommunication::make_node_unique_ids_parallel_consistent(), libMesh::MeshCommunication::make_nodes_parallel_consistent(), libMesh::MeshCommunication::make_p_levels_parallel_consistent(), libMesh::MeshRefinement::make_refinement_compatible(), libMesh::DistributedVector< T >::max(), libMesh::FEMSystem::mesh_position_set(), libMesh::MeshSerializer::MeshSerializer(), libMesh::DistributedVector< T >::min(), libMesh::DistributedMesh::n_active_elem(), libMesh::MeshTools::n_active_levels(), libMesh::BoundaryInfo::n_boundary_conds(), libMesh::BoundaryInfo::n_edge_conds(), libMesh::CondensedEigenSystem::n_global_non_condensed_dofs(), libMesh::MeshTools::n_levels(), libMesh::BoundaryInfo::n_nodeset_conds(), libMesh::MeshTools::n_p_levels(), libMesh::BoundaryInfo::n_shellface_conds(), libMesh::DistributedMesh::parallel_max_elem_id(), libMesh::DistributedMesh::parallel_max_node_id(), libMesh::ReplicatedMesh::parallel_max_unique_id(), libMesh::DistributedMesh::parallel_max_unique_id(), libMesh::DistributedMesh::parallel_n_elem(), libMesh::DistributedMesh::parallel_n_nodes(), libMesh::SparsityPattern::Build::parallel_sync(), libMesh::MeshTools::paranoid_n_levels(), libMesh::Partitioner::partition(), libMesh::LinearPartitioner::partition_range(), libMesh::MetisPartitioner::partition_range(), libMesh::Partitioner::partition_unpartitioned_elements(), libMesh::petsc_auto_fieldsplit(), libMesh::System::point_gradient(), libMesh::System::point_hessian(), libMesh::System::point_value(), libMesh::MeshBase::prepare_for_use(), libMesh::SparseMatrix< T >::print(), libMesh::Nemesis_IO::read(), libMesh::XdrIO::read(), libMesh::CheckpointIO::read_header(), libMesh::XdrIO::read_header(), libMesh::XdrIO::read_serialized_bc_names(), libMesh::XdrIO::read_serialized_bcs_helper(), libMesh::XdrIO::read_serialized_connectivity(), libMesh::XdrIO::read_serialized_nodes(), libMesh::XdrIO::read_serialized_nodesets(), libMesh::XdrIO::read_serialized_subdomain_names(), libMesh::MeshBase::recalculate_n_partitions(), libMesh::MeshCommunication::redistribute(), libMesh::MeshRefinement::refine_and_coarsen_elements(), libMesh::DistributedMesh::renumber_dof_objects(), libMesh::CheckpointIO::select_split_config(), libMesh::MeshCommunication::send_coarse_ghosts(), libMesh::Partitioner::set_node_processor_ids(), libMesh::DofMap::set_nonlocal_dof_objects(), libMesh::Partitioner::set_parent_processor_ids(), libMesh::PetscDiffSolver::setup_petsc_data(), libMesh::LaplaceMeshSmoother::smooth(), libMesh::Parallel::Sort< KeyType, IdxType >::sort(), libMesh::split_mesh(), libMesh::MeshBase::subdomain_ids(), libMesh::BoundaryInfo::sync(), libMesh::Parallel::sync_element_data_by_parent_id(), libMesh::Parallel::sync_node_data_by_element_id(), libMesh::MeshRefinement::test_level_one(), libMesh::MeshRefinement::test_unflagged(), libMesh::MeshTools::total_weight(), libMesh::MeshRefinement::uniformly_coarsen(), libMesh::NameBasedIO::write(), libMesh::XdrIO::write(), libMesh::XdrIO::write_serialized_bcs_helper(), libMesh::XdrIO::write_serialized_connectivity(), libMesh::XdrIO::write_serialized_nodes(), libMesh::XdrIO::write_serialized_nodesets(), libMesh::DistributedVector< T >::zero_clone(), libMesh::EigenSparseVector< T >::zero_clone(), libMesh::LaspackVector< T >::zero_clone(), libMesh::EpetraVector< T >::zero_clone(), and libMesh::PetscVector< T >::zero_clone().
   { return _communicator; }
bool libMesh::UnstructuredMesh::contract () virtual inherited
Delete subactive (i.e. children of coarsened) elements. This removes all elements descended from currently active elements in the mesh.
Implements libMesh::MeshBase.
Definition at line 778 of file unstructured_mesh.C.
References libMesh::Elem::active(), libMesh::Elem::ancestor(), libMesh::MeshBase::clear_point_locator(), libMesh::Elem::contract(), libMesh::MeshBase::delete_elem(), libMesh::MeshBase::elements_begin(), libMesh::MeshBase::elements_end(), end, libMesh::MeshBase::ghosting_functors_begin(), libMesh::MeshBase::ghosting_functors_end(), libmesh_nullptr, libMesh::GhostingFunctor::mesh_reinit(), libMesh::Elem::parent(), libMesh::MeshBase::renumber_nodes_and_elements(), and libMesh::Elem::subactive().
 {
   LOG_SCOPE ("contract()", "Mesh");
   // Flag indicating if this call actually changes the mesh
   bool mesh_changed = false;
   element_iterator in        = elements_begin();
   const element_iterator end = elements_end();
 #ifdef DEBUG
   for ( ; in != end; ++in)
     if (*in != libmesh_nullptr)
       {
         Elem * el = *in;
         libmesh_assert(el->active() || el->subactive() || el->ancestor());
       }
   in = elements_begin();
 #endif
   // Loop over the elements.
   for ( ; in != end; ++in)
     if (*in != libmesh_nullptr)
       {
         Elem * el = *in;
         // Delete all the subactive ones
         if (el->subactive())
           {
             // No level-0 element should be subactive.
             // Note that we CAN'T test elem->level(), as that
             // touches elem->parent()->dim(), and elem->parent()
             // might have already been deleted!
             libmesh_assert(el->parent());
             // Delete the element
             // This just sets a pointer to NULL, and doesn't
             // invalidate any iterators
             this->delete_elem(el);
             // the mesh has certainly changed
             mesh_changed = true;
           }
         else
           {
             // Compress all the active ones
             if (el->active())
               el->contract();
             else
               libmesh_assert (el->ancestor());
           }
       }
   // Strip any newly-created NULL voids out of the element array
   this->renumber_nodes_and_elements();
   // FIXME: Need to understand why deleting subactive children
   // invalidates the point locator.  For now we will clear it explicitly
   this->clear_point_locator();
   // Allow our GhostingFunctor objects to reinit if necessary.
   std::set<GhostingFunctor *>::iterator        gf_it = this->ghosting_functors_begin();
   const std::set<GhostingFunctor *>::iterator gf_end = this->ghosting_functors_end();
   for (; gf_it != gf_end; ++gf_it)
     {
       GhostingFunctor *gf = *gf_it;
       libmesh_assert(gf);
       gf->mesh_reinit();
     }
   return mesh_changed;
 }
void libMesh::UnstructuredMesh::copy_nodes_and_elements (const UnstructuredMesh & other_mesh, const bool skip_find_neighbors = false) virtual inherited
Deep copy of another unstructured mesh class (used by subclass copy constructors)
Definition at line 73 of file unstructured_mesh.C.
References libMesh::MeshBase::_is_prepared, libMesh::MeshBase::_n_parts, libMesh::Elem::add_child(), libMesh::MeshBase::add_elem(), libMesh::MeshBase::add_point(), libMesh::MeshBase::allow_remote_element_removal(), libMesh::MeshBase::allow_renumbering(), libMesh::Elem::build(), libMesh::MeshBase::elem_ptr(), libMesh::MeshBase::element_ptr_range(), libMesh::MeshTools::libmesh_assert_valid_amr_elem_ids(), libmesh_nullptr, libMesh::MeshBase::n_elem(), libMesh::MeshBase::n_nodes(), libMesh::Elem::neighbor_ptr(), libMesh::MeshBase::node_ptr(), libMesh::MeshBase::node_ptr_range(), libMesh::Elem::parent(), libMesh::MeshBase::prepare_for_use(), libMesh::DofObject::processor_id(), libMesh::remote_elem, libMesh::MeshBase::reserve_elem(), libMesh::MeshBase::reserve_nodes(), libMesh::Elem::set_neighbor(), libMesh::DofObject::set_unique_id(), libMesh::MeshBase::skip_partitioning(), and libMesh::Elem::subdomain_id().
Referenced by libMesh::DistributedMesh::DistributedMesh(), libMesh::ReplicatedMesh::ReplicatedMesh(), and libMesh::ReplicatedMesh::stitching_helper().
 {
   LOG_SCOPE("copy_nodes_and_elements()", "UnstructuredMesh");
   // We expect to have at least as many processors as the other mesh
   // is partitioned into, so that our partitioning will still be
   // consistent afterwards.
   libmesh_assert_greater_equal (_n_parts, other_mesh._n_parts);
   // We're assuming our subclass data needs no copy
   libmesh_assert_equal_to (_is_prepared, other_mesh._is_prepared);
   // We're assuming the other mesh has proper element number ordering,
   // so that we add parents before their children.
 #ifdef DEBUG
   MeshTools::libmesh_assert_valid_amr_elem_ids(other_mesh);
 #endif
   //Copy in Nodes
   {
     //Preallocate Memory if necessary
     this->reserve_nodes(other_mesh.n_nodes());
     for (const auto & oldn : other_mesh.node_ptr_range())
       {
         // Add new nodes in old node Point locations
 #ifdef LIBMESH_ENABLE_UNIQUE_ID
         Node * newn =
 #endif
           this->add_point(*oldn, oldn->id(), oldn->processor_id());
 #ifdef LIBMESH_ENABLE_UNIQUE_ID
         newn->set_unique_id() = oldn->unique_id();
 #endif
       }
   }
   //Copy in Elements
   {
     //Preallocate Memory if necessary
     this->reserve_elem(other_mesh.n_elem());
     // Declare a map linking old and new elements, needed to copy the neighbor lists
     typedef std::unordered_map<const Elem *, Elem *> map_type;
     map_type old_elems_to_new_elems;
     // Loop over the elements
     for (const auto & old : other_mesh.element_ptr_range())
       {
         // Build a new element
         Elem * newparent = old->parent() ?
           this->elem_ptr(old->parent()->id()) : libmesh_nullptr;
         std::unique_ptr<Elem> ap = Elem::build(old->type(), newparent);
         Elem * el = ap.release();
         el->subdomain_id() = old->subdomain_id();
         for (auto s : old->side_index_range())
           if (old->neighbor_ptr(s) == remote_elem)
             el->set_neighbor(s, const_cast<RemoteElem *>(remote_elem));
 #ifdef LIBMESH_ENABLE_AMR
         if (old->has_children())
           for (unsigned int c = 0, nc = old->n_children(); c != nc; ++c)
             if (old->child_ptr(c) == remote_elem)
               el->add_child(const_cast<RemoteElem *>(remote_elem), c);
         //Create the parent's child pointers if necessary
         if (newparent)
           {
             unsigned int oldc = old->parent()->which_child_am_i(old);
             newparent->add_child(el, oldc);
           }
         // Copy the refinement flags
         el->set_refinement_flag(old->refinement_flag());
         // Use hack_p_level since we may not have sibling elements
         // added yet
         el->hack_p_level(old->p_level());
         el->set_p_refinement_flag(old->p_refinement_flag());
 #endif // #ifdef LIBMESH_ENABLE_AMR
         //Assign all the nodes
         for (auto i : el->node_index_range())
           el->set_node(i) = this->node_ptr(old->node_id(i));
         // And start it off in the same subdomain
         el->processor_id() = old->processor_id();
         // Give it the same element and unique ids
         el->set_id(old->id());
 #ifdef LIBMESH_ENABLE_UNIQUE_ID
         el->set_unique_id() = old->unique_id();
 #endif
         //Hold onto it
         if (!skip_find_neighbors)
           {
             this->add_elem(el);
           }
         else
           {
             Elem * new_el = this->add_elem(el);
             old_elems_to_new_elems[old] = new_el;
           }
         // Add the link between the original element and this copy to the map
         if (skip_find_neighbors)
           old_elems_to_new_elems[old] = el;
       }
     // Loop (again) over the elements to fill in the neighbors
     if (skip_find_neighbors)
       {
         for (const auto & old_elem : other_mesh.element_ptr_range())
           {
             Elem * new_elem = old_elems_to_new_elems[old_elem];
             for (auto s : old_elem->side_index_range())
               {
                 const Elem * old_neighbor = old_elem->neighbor_ptr(s);
                 Elem * new_neighbor = old_elems_to_new_elems[old_neighbor];
                 new_elem->set_neighbor(s, new_neighbor);
               }
           }
       }
   }
   //Finally prepare the new Mesh for use.  Keep the same numbering and
   //partitioning for now.
   this->allow_renumbering(false);
   this->allow_remote_element_removal(false);
   this->skip_partitioning(true);
   this->prepare_for_use(false, skip_find_neighbors);
   //But in the long term, use the same renumbering and partitioning
   //policies as our source mesh.
   this->allow_renumbering(other_mesh.allow_renumbering());
   this->allow_remote_element_removal(other_mesh.allow_remote_element_removal());
   this->skip_partitioning(other_mesh.skip_partitioning());
 }
void libMesh::UnstructuredMesh::create_pid_mesh (UnstructuredMesh & pid_mesh, const processor_id_type pid) const inherited
Generates a new mesh containing all the elements which are assigned to processor pid. This mesh is written to the pid_mesh reference which you must create and pass to the function.
Definition at line 657 of file unstructured_mesh.C.
References libMesh::MeshBase::active_pid_elements_begin(), libMesh::MeshBase::active_pid_elements_end(), libMesh::UnstructuredMesh::create_submesh(), libMesh::ParallelObject::n_processors(), and libMesh::out.
 {
   // Issue a warning if the number the number of processors
   // currently available is less that that requested for
   // partitioning.  This is not necessarily an error since
   // you may run on one processor and still partition the
   // mesh into several partitions.
 #ifdef DEBUG
   if (this->n_processors() < pid)
     {
       libMesh::out << "WARNING:  You are creating a "
                    << "mesh for a processor id (="
                    << pid
                    << ") greater than "
                    << "the number of processors available for "
                    << "the calculation. (="
                    << this->n_processors()
                    << ")."
                    << std::endl;
     }
 #endif
   // Create iterators to loop over the list of elements
   //   const_active_pid_elem_iterator       it(this->elements_begin(),   pid);
   //   const const_active_pid_elem_iterator it_end(this->elements_end(), pid);
   const_element_iterator       it     = this->active_pid_elements_begin(pid);
   const const_element_iterator it_end = this->active_pid_elements_end(pid);
   this->create_submesh (pid_mesh, it, it_end);
 }
void libMesh::UnstructuredMesh::create_submesh (UnstructuredMesh & new_mesh, const_element_iterator & it, const const_element_iterator & it_end) const inherited
Constructs a mesh called "new_mesh" from the current mesh by iterating over the elements between it and it_end and adding them to the new mesh.
Definition at line 697 of file unstructured_mesh.C.
References libMesh::MeshBase::add_elem(), libMesh::MeshBase::add_point(), libMesh::BoundaryInfo::add_side(), libMesh::BoundaryInfo::boundary_ids(), libMesh::Elem::build(), libMesh::MeshBase::clear(), libMesh::MeshBase::delete_remote_elements(), libMesh::MeshBase::get_boundary_info(), libMesh::DofObject::id(), libMesh::MeshBase::is_serial(), libMesh::MeshBase::n_elem(), libMesh::MeshBase::n_nodes(), libMesh::Elem::node_id(), libMesh::Elem::node_index_range(), libMesh::Elem::node_ptr(), libMesh::MeshBase::node_ptr(), libMesh::Elem::point(), libMesh::MeshBase::prepare_for_use(), libMesh::DofObject::processor_id(), libMesh::MeshBase::query_node_ptr(), libMesh::DofObject::set_id(), libMesh::Elem::set_node(), libMesh::DofObject::set_unique_id(), libMesh::Elem::side_index_range(), libMesh::Elem::subdomain_id(), libMesh::Elem::type(), and libMesh::DofObject::unique_id().
Referenced by libMesh::UnstructuredMesh::create_pid_mesh().
 {
   // Just in case the subdomain_mesh already has some information
   // in it, get rid of it.
   new_mesh.clear();
   // If we're not serial, our submesh isn't either.
   // There are no remote elements to delete on an empty mesh, but
   // calling the method to do so marks the mesh as parallel.
   if (!this->is_serial())
     new_mesh.delete_remote_elements();
   // Fail if (*this == new_mesh), we cannot create a submesh inside ourself!
   // This may happen if the user accidentally passes the original mesh into
   // this function!  We will check this by making sure we did not just
   // clear ourself.
   libmesh_assert_not_equal_to (this->n_nodes(), 0);
   libmesh_assert_not_equal_to (this->n_elem(), 0);
   // Container to catch boundary IDs handed back by BoundaryInfo
   std::vector<boundary_id_type> bc_ids;
   for (; it != it_end; ++it)
     {
       const Elem * old_elem = *it;
       // Add an equivalent element type to the new_mesh.
       // Copy ids for this element.
       Elem * new_elem = Elem::build(old_elem->type()).release();
       new_elem->set_id() = old_elem->id();
 #ifdef LIBMESH_ENABLE_UNIQUE_ID
       new_elem->set_unique_id() = old_elem->unique_id();
 #endif
       new_elem->subdomain_id() = old_elem->subdomain_id();
       new_elem->processor_id() = old_elem->processor_id();
       new_mesh.add_elem (new_elem);
       libmesh_assert(new_elem);
       // Loop over the nodes on this element.
       for (auto n : old_elem->node_index_range())
         {
           const dof_id_type this_node_id = old_elem->node_id(n);
           // Add this node to the new mesh if it's not there already
           if (!new_mesh.query_node_ptr(this_node_id))
             {
 #ifdef LIBMESH_ENABLE_UNIQUE_ID
               Node *newn =
 #endif
                 new_mesh.add_point (old_elem->point(n),
                                     this_node_id,
                                     old_elem->node_ptr(n)->processor_id());
 #ifdef LIBMESH_ENABLE_UNIQUE_ID
               newn->set_unique_id() = old_elem->node_ptr(n)->unique_id();
 #endif
             }
           // Define this element's connectivity on the new mesh
           new_elem->set_node(n) = new_mesh.node_ptr(this_node_id);
         }
       // Maybe add boundary conditions for this element
       for (auto s : old_elem->side_index_range())
         {
           this->get_boundary_info().boundary_ids(old_elem, s, bc_ids);
           new_mesh.get_boundary_info().add_side (new_elem, s, bc_ids);
         }
     } // end loop over elements
   // Prepare the new_mesh for use
   new_mesh.prepare_for_use(/*skip_renumber =*/false);
 }
void libMesh::ReplicatedMesh::delete_elem (Elem * e) virtual inherited
Removes element e from the mesh. This method must be implemented in derived classes in such a way that it does not invalidate element iterators. Users should call MeshBase::prepare_for_use() after elements are added to and/or deleted from the mesh.
Note
Calling this method may produce isolated nodes, i.e. nodes not connected to any element.
Implements libMesh::MeshBase.
Definition at line 346 of file replicated_mesh.C.
References libMesh::ReplicatedMesh::_elements, libMesh::MeshBase::get_boundary_info(), libMesh::DofObject::id(), libmesh_nullptr, and libMesh::BoundaryInfo::remove().
Referenced by libMesh::ReplicatedMesh::insert_elem(), and libMesh::ReplicatedMesh::reserve_elem().
 {
   libmesh_assert(e);
   // Initialize an iterator to eventually point to the element we want to delete
   std::vector<Elem *>::iterator pos = _elements.end();
   // In many cases, e->id() gives us a clue as to where e
   // is located in the _elements vector.  Try that first
   // before trying the O(n_elem) search.
   libmesh_assert_less (e->id(), _elements.size());
   if (_elements[e->id()] == e)
     {
       // We found it!
       pos = _elements.begin();
       std::advance(pos, e->id());
     }
   else
     {
       // This search is O(n_elem)
       pos = std::find (_elements.begin(),
                        _elements.end(),
                        e);
     }
   // Huh? Element not in the vector?
   libmesh_assert (pos != _elements.end());
   // Remove the element from the BoundaryInfo object
   this->get_boundary_info().remove(e);
   // delete the element
   delete e;
   // explicitly NULL the pointer
   *pos = libmesh_nullptr;
 }
void libMesh::ReplicatedMesh::delete_node (Node * n) virtual inherited
Removes the Node n from the mesh.
Implements libMesh::MeshBase.
Definition at line 519 of file replicated_mesh.C.
References libMesh::ReplicatedMesh::_nodes, libMesh::MeshBase::get_boundary_info(), libMesh::DofObject::id(), libmesh_nullptr, and libMesh::BoundaryInfo::remove().
Referenced by libMesh::ReplicatedMesh::reserve_elem(), and libMesh::ReplicatedMesh::stitching_helper().
 {
   libmesh_assert(n);
   libmesh_assert_less (n->id(), _nodes.size());
   // Initialize an iterator to eventually point to the element we want
   // to delete
   std::vector<Node *>::iterator pos;
   // In many cases, e->id() gives us a clue as to where e
   // is located in the _elements vector.  Try that first
   // before trying the O(n_elem) search.
   if (_nodes[n->id()] == n)
     {
       pos = _nodes.begin();
       std::advance(pos, n->id());
     }
   else
     {
       pos = std::find (_nodes.begin(),
                        _nodes.end(),
                        n);
     }
   // Huh? Node not in the vector?
   libmesh_assert (pos != _nodes.end());
   // Delete the node from the BoundaryInfo object
   this->get_boundary_info().remove(n);
   // delete the node
   delete n;
   // explicitly NULL the pointer
   *pos = libmesh_nullptr;
 }
virtual void libMesh::MeshBase::delete_remote_elements () inline virtual inherited
When supported, deletes all nonlocal elements of the mesh except for "ghosts" which touch a local element, and deletes all nodes which are not part of a local or ghost element
Reimplemented in libMesh::DistributedMesh.
Definition at line 183 of file mesh_base.h.
References libMesh::MeshBase::mesh_dimension().
Referenced by libMesh::MeshTools::Generation::build_extrusion(), libMesh::UnstructuredMesh::create_submesh(), libMesh::MeshBase::prepare_for_use(), libMesh::Nemesis_IO::read(), libMesh::BoundaryInfo::sync(), and libMesh::MeshSerializer::~MeshSerializer().
 {}
void libMesh::MeshBase::detect_interior_parents () inherited
Search the mesh for elements that have a neighboring element of dim+1 and set that element as the interior parent
Definition at line 680 of file mesh_base.C.
References libMesh::MeshBase::active_elements_begin(), libMesh::MeshBase::active_elements_end(), libMesh::Elem::dim(), libMesh::MeshBase::elem(), libMesh::MeshBase::elem_dimensions(), libMesh::MeshBase::elem_ptr(), libMesh::MeshBase::elem_ref(), libMesh::MeshBase::elements_begin(), end, libMesh::DofObject::id(), libMesh::Elem::interior_parent(), libMesh::MeshBase::max_elem_id(), libMesh::Elem::n_vertices(), libMesh::Elem::node_id(), and libMesh::Elem::set_interior_parent().
Referenced by libMesh::MeshBase::get_subdomain_name_map(), and libMesh::MeshBase::prepare_for_use().
 {
   // This requires an inspection on every processor
   parallel_object_only();
   // Check if the mesh contains mixed dimensions. If so, then set interior parents, otherwise return.
   if (this->elem_dimensions().size() == 1)
     return;
   //This map will be used to set interior parents
   std::unordered_map<dof_id_type, std::vector<dof_id_type>> node_to_elem;
   const_element_iterator el  = this->active_elements_begin();
   const_element_iterator end = this->active_elements_end();
   for (; el!=end; ++el)
     {
       const Elem * elem = *el;
       // Populating the node_to_elem map, same as MeshTools::build_nodes_to_elem_map
       for (unsigned int n=0; n<elem->n_vertices(); n++)
         {
           libmesh_assert_less (elem->id(), this->max_elem_id());
           node_to_elem[elem->node_id(n)].push_back(elem->id());
         }
     }
   // Automatically set interior parents
   el = this->elements_begin();
   for (; el!=end; ++el)
     {
       Elem * element = *el;
       // Ignore an 3D element or an element that already has an interior parent
       if (element->dim()>=LIBMESH_DIM || element->interior_parent())
         continue;
       // Start by generating a SET of elements that are dim+1 to the current
       // element at each vertex of the current element, thus ignoring interior nodes.
       // If one of the SET of elements is empty, then we will not have an interior parent
       // since an interior parent must be connected to all vertices of the current element
       std::vector<std::set<dof_id_type>> neighbors( element->n_vertices() );
       bool found_interior_parents = false;
       for (dof_id_type n=0; n < element->n_vertices(); n++)
         {
           std::vector<dof_id_type> & element_ids = node_to_elem[element->node_id(n)];
           for (std::vector<dof_id_type>::iterator e_it = element_ids.begin();
                e_it != element_ids.end(); e_it++)
             {
               dof_id_type eid = *e_it;
               if (this->elem_ref(eid).dim() == element->dim()+1)
                 neighbors[n].insert(eid);
             }
           if (neighbors[n].size()>0)
             {
               found_interior_parents = true;
             }
           else
             {
               // We have found an empty set, no reason to continue
               // Ensure we set this flag to false before the break since it could have
               // been set to true for previous vertex
               found_interior_parents = false;
               break;
             }
         }
       // If we have successfully generated a set of elements for each vertex, we will compare
       // the set for vertex 0 will the sets for the vertices until we find a id that exists in
       // all sets.  If found, this is our an interior parent id.  The interior parent id found
       // will be the lowest element id if there is potential for multiple interior parents.
       if (found_interior_parents)
         {
           std::set<dof_id_type> & neighbors_0 = neighbors[0];
           for (std::set<dof_id_type>::iterator e_it = neighbors_0.begin();
                e_it != neighbors_0.end(); e_it++)
             {
               found_interior_parents=false;
               dof_id_type interior_parent_id = *e_it;
               for (dof_id_type n=1; n < element->n_vertices(); n++)
                 {
                   if (neighbors[n].find(interior_parent_id)!=neighbors[n].end())
                     {
                       found_interior_parents=true;
                     }
                   else
                     {
                       found_interior_parents=false;
                       break;
                     }
                 }
               if (found_interior_parents)
                 {
                   element->set_interior_parent(this->elem_ptr(interior_parent_id));
                   break;
                 }
             }
         }
     }
 }
virtual const Elem* libMesh::MeshBase::elem (const dof_id_type i) const inline virtual inherited
Returns
A pointer to the element, which should be present in this processor's subset of the mesh data structure.
Deprecated:
Use the less confusingly-named elem_ptr() instead.
Definition at line 524 of file mesh_base.h.
References libMesh::MeshBase::elem_ptr().
Referenced by libMesh::MeshBase::detect_interior_parents().
   {
     libmesh_deprecated();
     return this->elem_ptr(i);
   }
virtual Elem* libMesh::MeshBase::elem (const dof_id_type i) inline virtual inherited
Returns
A writable pointer to the element, which should be present in this processor's subset of the mesh data structure.
Deprecated:
Use the less confusingly-named elem_ptr() instead.
Definition at line 539 of file mesh_base.h.
References libMesh::MeshBase::elem_ptr(), and libMesh::MeshBase::query_elem_ptr().
   {
     libmesh_deprecated();
     return this->elem_ptr(i);
   }
const std::set<unsigned char>& libMesh::MeshBase::elem_dimensions () const inline inherited
Returns
A const reference to a std::set of element dimensions present in the mesh.
Definition at line 207 of file mesh_base.h.
References libMesh::MeshBase::_elem_dims, libMesh::MeshBase::n_nodes(), libMesh::MeshBase::n_nodes_on_proc(), libMesh::MeshBase::parallel_n_nodes(), libMesh::MeshBase::set_spatial_dimension(), and libMesh::MeshBase::spatial_dimension().
Referenced by libMesh::ExactSolution::_compute_error(), libMesh::System::calculate_norm(), libMesh::MeshBase::detect_interior_parents(), and libMesh::TreeNode< N >::insert().
   { return _elem_dims; }
const Elem * libMesh::ReplicatedMesh::elem_ptr (const dof_id_type i) const virtual inherited
Returns
A pointer to the element, which should be present in this processor's subset of the mesh data structure.
Implements libMesh::MeshBase.
Definition at line 236 of file replicated_mesh.C.
References libMesh::ReplicatedMesh::_elements, and libMesh::ReplicatedMesh::n_elem().
Referenced by libMesh::ReplicatedMesh::reserve_elem(), and libMesh::ReplicatedMesh::stitching_helper().
 {
   libmesh_assert_less (i, this->n_elem());
   libmesh_assert(_elements[i]);
   libmesh_assert_equal_to (_elements[i]->id(), i); // This will change soon
   return _elements[i];
 }
Elem * libMesh::ReplicatedMesh::elem_ptr (const dof_id_type i) virtual inherited
Returns
A writable pointer to the element, which should be present in this processor's subset of the mesh data structure.
Implements libMesh::MeshBase.
Definition at line 248 of file replicated_mesh.C.
References libMesh::ReplicatedMesh::_elements, and libMesh::ReplicatedMesh::n_elem().
 {
   libmesh_assert_less (i, this->n_elem());
   libmesh_assert(_elements[i]);
   libmesh_assert_equal_to (_elements[i]->id(), i); // This will change soon
   return _elements[i];
 }
virtual const Elem& libMesh::MeshBase::elem_ref (const dof_id_type i) const inline virtual inherited
Returns
A reference to the element, which should be present in this processor's subset of the mesh data structure.
Definition at line 491 of file mesh_base.h.
References libMesh::MeshBase::elem_ptr().
Referenced by libMesh::SyncRefinementFlags::act_on_data(), libMesh::AbaqusIO::assign_sideset_ids(), libMesh::AbaqusIO::assign_subdomain_ids(), libMesh::Nemesis_IO_Helper::build_element_and_node_maps(), libMesh::InfElemBuilder::build_inf_elem(), libMesh::Nemesis_IO_Helper::compute_num_global_sidesets(), libMesh::MeshBase::detect_interior_parents(), libMesh::SyncRefinementFlags::gather_data(), libMesh::MeshRefinement::make_coarsening_compatible(), libMesh::ExodusII_IO::read(), libMesh::CheckpointIO::read_remote_elem(), libMesh::Parallel::sync_element_data_by_parent_id(), libMesh::Parallel::sync_node_data_by_element_id(), libMesh::MeshRefinement::uniformly_coarsen(), libMesh::FroIO::write(), libMesh::Nemesis_IO_Helper::write_elements(), libMesh::ExodusII_IO_Helper::write_elements(), libMesh::Nemesis_IO_Helper::write_sidesets(), and libMesh::ExodusII_IO_Helper::write_sidesets().
{
     return *this->elem_ptr(i);
   }
virtual Elem& libMesh::MeshBase::elem_ref (const dof_id_type i) inline virtual inherited
Returns
A writable reference to the element, which should be present in this processor's subset of the mesh data structure.
Definition at line 500 of file mesh_base.h.
References libMesh::MeshBase::elem_ptr().
{
     return *this->elem_ptr(i);
   }
virtual SimpleRange<element_iterator> libMesh::ReplicatedMesh::element_ptr_range () inline virtual inherited
Implements libMesh::MeshBase.
Definition at line 244 of file replicated_mesh.h.
References libMesh::ReplicatedMesh::elements_begin(), and libMesh::ReplicatedMesh::elements_end().
 { return {elements_begin(), elements_end()}; }
virtual SimpleRange<const_element_iterator> libMesh::ReplicatedMesh::element_ptr_range () const inline virtual inherited
Implements libMesh::MeshBase.
Definition at line 245 of file replicated_mesh.h.
References libMesh::ReplicatedMesh::active_elements_begin(), libMesh::ReplicatedMesh::active_elements_end(), libMesh::ReplicatedMesh::elements_begin(), and libMesh::ReplicatedMesh::elements_end().
 { return {elements_begin(), elements_end()}; }
virtual element_iterator libMesh::ReplicatedMesh::elements_begin () virtual inherited
Elem iterator accessor functions.
Implements libMesh::MeshBase.
Referenced by libMesh::ReplicatedMesh::element_ptr_range(), libMesh::ReplicatedMesh::reserve_elem(), and libMesh::ReplicatedMesh::stitching_helper().
virtual const_element_iterator libMesh::ReplicatedMesh::elements_begin () const virtual inherited
Implements libMesh::MeshBase.
virtual element_iterator libMesh::ReplicatedMesh::elements_end () virtual inherited
Implements libMesh::MeshBase.
Referenced by libMesh::ReplicatedMesh::element_ptr_range(), libMesh::ReplicatedMesh::reserve_elem(), and libMesh::ReplicatedMesh::stitching_helper().
virtual const_element_iterator libMesh::ReplicatedMesh::elements_end () const virtual inherited
Implements libMesh::MeshBase.
virtual element_iterator libMesh::ReplicatedMesh::evaluable_elements_begin (const DofMap & dof_map, unsigned int var_num = libMesh::invalid_uint) virtual inherited
Iterate over elements in the Mesh where the solution (as distributed by the given DofMap) can be evaluated, for the given variable var_num, or for all variables by default.
Implements libMesh::MeshBase.
Referenced by libMesh::ReplicatedMesh::active_local_element_ptr_range().
virtual const_element_iterator libMesh::ReplicatedMesh::evaluable_elements_begin (const DofMap & dof_map, unsigned int var_num = libMesh::invalid_uint) const virtual inherited
Implements libMesh::MeshBase.
virtual element_iterator libMesh::ReplicatedMesh::evaluable_elements_end (const DofMap & dof_map, unsigned int var_num = libMesh::invalid_uint) virtual inherited
Implements libMesh::MeshBase.
Referenced by libMesh::ReplicatedMesh::active_local_element_ptr_range().
virtual const_element_iterator libMesh::ReplicatedMesh::evaluable_elements_end (const DofMap & dof_map, unsigned int var_num = libMesh::invalid_uint) const virtual inherited
Implements libMesh::MeshBase.
virtual node_iterator libMesh::ReplicatedMesh::evaluable_nodes_begin (const DofMap & dof_map, unsigned int var_num = libMesh::invalid_uint) virtual inherited
Iterate over nodes in the Mesh where the solution (as distributed by the given DofMap) can be evaluated, for the given variable var_num, or for all variables by default.
Implements libMesh::MeshBase.
Referenced by libMesh::ReplicatedMesh::local_node_ptr_range().
virtual const_node_iterator libMesh::ReplicatedMesh::evaluable_nodes_begin (const DofMap & dof_map, unsigned int var_num = libMesh::invalid_uint) const virtual inherited
Implements libMesh::MeshBase.
virtual node_iterator libMesh::ReplicatedMesh::evaluable_nodes_end (const DofMap & dof_map, unsigned int var_num = libMesh::invalid_uint) virtual inherited
Implements libMesh::MeshBase.
Referenced by libMesh::ReplicatedMesh::local_node_ptr_range().
virtual const_node_iterator libMesh::ReplicatedMesh::evaluable_nodes_end (const DofMap & dof_map, unsigned int var_num = libMesh::invalid_uint) const virtual inherited
Implements libMesh::MeshBase.
virtual element_iterator libMesh::ReplicatedMesh::facelocal_elements_begin () virtual inherited
Iterate over elements which are on or have a neighbor on the current processor.
Implements libMesh::MeshBase.
Referenced by libMesh::ReplicatedMesh::active_element_ptr_range().
virtual const_element_iterator libMesh::ReplicatedMesh::facelocal_elements_begin () const virtual inherited
Implements libMesh::MeshBase.
virtual element_iterator libMesh::ReplicatedMesh::facelocal_elements_end () virtual inherited
Implements libMesh::MeshBase.
Referenced by libMesh::ReplicatedMesh::active_element_ptr_range().
virtual const_element_iterator libMesh::ReplicatedMesh::facelocal_elements_end () const virtual inherited
Implements libMesh::MeshBase.
void libMesh::UnstructuredMesh::find_neighbors (const bool reset_remote_elements = false, const bool reset_current_list = true) virtual inherited
Other functions from MeshBase requiring re-definition.
Here we look at all of the child elements which don't already have valid neighbors.
If a child element has a NULL neighbor it is either because it is on the boundary or because its neighbor is at a different level. In the latter case we must get the neighbor from the parent.
If a child element has a remote_elem neighbor on a boundary it shares with its parent, that info may have become out-dated through coarsening of the neighbor's parent. In this case, if the parent's neighbor is active then the child should share it.
Furthermore, that neighbor better be active, otherwise we missed a child somewhere.
We also need to look through children ordered by increasing refinement level in order to add new interior_parent() links in boundary elements which have just been generated by refinement, and fix links in boundary elements whose previous interior_parent() has just been coarsened away.
Implements libMesh::MeshBase.
Definition at line 232 of file unstructured_mesh.C.
References libMesh::Elem::active(), libMesh::Elem::ancestor(), libMesh::Elem::centroid(), libMesh::Elem::child_ptr(), libMesh::Elem::child_ref_range(), libMesh::Elem::dim(), libMesh::MeshBase::elements_begin(), libMesh::MeshBase::elements_end(), end, libMesh::err, libMesh::Elem::has_children(), libMesh::Elem::hmin(), libMesh::DofObject::id(), libMesh::Elem::interior_parent(), libMesh::Elem::is_ancestor_of(), libMesh::Elem::is_child_on_side(), libMesh::Elem::key(), libMesh::Elem::level(), libMesh::MeshBase::level_elements_begin(), libMesh::MeshBase::level_elements_end(), libMesh::MeshTools::libmesh_assert_valid_amr_interior_parents(), libMesh::MeshTools::libmesh_assert_valid_neighbors(), libmesh_nullptr, libMesh::Elem::n_children(), libMesh::MeshTools::n_levels(), libMesh::Elem::neighbor_ptr(), libMesh::Elem::neighbor_ptr_range(), libMesh::Elem::node_ref_range(), libMesh::Elem::parent(), libMesh::ParallelObject::processor_id(), libMesh::DofObject::processor_id(), libMesh::Real, libMesh::remote_elem, libMesh::Elem::set_interior_parent(), libMesh::Elem::set_neighbor(), libMesh::Elem::side_index_range(), libMesh::Elem::side_ptr(), libMesh::Elem::subactive(), libMesh::TOLERANCE, libMesh::Elem::which_child_am_i(), and libMesh::NameBasedIO::write().
Referenced by libMesh::TriangleWrapper::copy_tri_to_mesh(), libMesh::MeshCommunication::gather(), libMesh::MeshCommunication::gather_neighboring_elements(), and libMesh::DistributedMesh::redistribute().
 {
   // We might actually want to run this on an empty mesh
   // (e.g. the boundary mesh for a nonexistent bcid!)
   // libmesh_assert_not_equal_to (this->n_nodes(), 0);
   // libmesh_assert_not_equal_to (this->n_elem(), 0);
   // This function must be run on all processors at once
   parallel_object_only();
   LOG_SCOPE("find_neighbors()", "Mesh");
   const element_iterator el_end = this->elements_end();
   //TODO:[BSK] This should be removed later?!
   if (reset_current_list)
     for (element_iterator el = this->elements_begin(); el != el_end; ++el)
       {
         Elem * e = *el;
         for (auto s : e->side_index_range())
           if (e->neighbor_ptr(s) != remote_elem ||
               reset_remote_elements)
             e->set_neighbor(s, libmesh_nullptr);
       }
   // Find neighboring elements by first finding elements
   // with identical side keys and then check to see if they
   // are neighbors
   {
     // data structures -- Use the hash_multimap if available
     typedef unsigned int                    key_type;
     typedef std::pair<Elem *, unsigned char> val_type;
     typedef std::pair<key_type, val_type>   key_val_pair;
     typedef std::unordered_multimap<key_type, val_type> map_type;
     // A map from side keys to corresponding elements & side numbers
     map_type side_to_elem_map;
     for (element_iterator el = this->elements_begin(); el != el_end; ++el)
       {
         Elem * element = *el;
         for (auto ms : element->side_index_range())
           {
           next_side:
             // If we haven't yet found a neighbor on this side, try.
             // Even if we think our neighbor is remote, that
             // information may be out of date.
             if (element->neighbor_ptr(ms) == libmesh_nullptr ||
                 element->neighbor_ptr(ms) == remote_elem)
               {
                 // Get the key for the side of this element
                 const unsigned int key = element->key(ms);
                 // Look for elements that have an identical side key
                 std::pair <map_type::iterator, map_type::iterator>
                   bounds = side_to_elem_map.equal_range(key);
                 // May be multiple keys, check all the possible
                 // elements which _might_ be neighbors.
                 if (bounds.first != bounds.second)
                   {
                     // Get the side for this element
                     const std::unique_ptr<Elem> my_side(element->side_ptr(ms));
                     // Look at all the entries with an equivalent key
                     while (bounds.first != bounds.second)
                       {
                         // Get the potential element
                         Elem * neighbor = bounds.first->second.first;
                         // Get the side for the neighboring element
                         const unsigned int ns = bounds.first->second.second;
                         const std::unique_ptr<Elem> their_side(neighbor->side_ptr(ns));
                         //libmesh_assert(my_side.get());
                         //libmesh_assert(their_side.get());
                         // If found a match with my side
                         //
                         // We need special tests here for 1D:
                         // since parents and children have an equal
                         // side (i.e. a node), we need to check
                         // ns != ms, and we also check level() to
                         // avoid setting our neighbor pointer to
                         // any of our neighbor's descendants
                         if ((*my_side == *their_side) &&
                             (element->level() == neighbor->level()) &&
                             ((element->dim() != 1) || (ns != ms)))
{
                             // So share a side.  Is this a mixed pair
                             // of subactive and active/ancestor
                             // elements?
                             // If not, then we're neighbors.
                             // If so, then the subactive's neighbor is
                             if (element->subactive() ==
                                 neighbor->subactive())
{
                                 // an element is only subactive if it has
                                 // been coarsened but not deleted
                                 element->set_neighbor (ms,neighbor);
                                 neighbor->set_neighbor(ns,element);
                               }
                             else if (element->subactive())
{
                                 element->set_neighbor(ms,neighbor);
                               }
                             else if (neighbor->subactive())
{
                                 neighbor->set_neighbor(ns,element);
                               }
                             side_to_elem_map.erase (bounds.first);
                             // get out of this nested crap
                             goto next_side;
                           }
                         ++bounds.first;
                       }
                   }
                 // didn't find a match...
                 // Build the map entry for this element
                 key_val_pair kvp;
                 kvp.first         = key;
                 kvp.second.first  = element;
                 kvp.second.second = ms;
                 side_to_elem_map.insert (kvp);
               }
           }
       }
   }
 #ifdef LIBMESH_ENABLE_AMR
   const unsigned int n_levels = MeshTools::n_levels(*this);
   for (unsigned int level = 1; level < n_levels; ++level)
     {
       element_iterator end = this->level_elements_end(level);
       for (element_iterator el = this->level_elements_begin(level);
            el != end; ++el)
         {
           Elem * current_elem = *el;
           libmesh_assert(current_elem);
           Elem * parent = current_elem->parent();
           libmesh_assert(parent);
           const unsigned int my_child_num = parent->which_child_am_i(current_elem);
           for (auto s : current_elem->side_index_range())
             {
               if (current_elem->neighbor_ptr(s) == libmesh_nullptr ||
                   (current_elem->neighbor_ptr(s) == remote_elem &&
                    parent->is_child_on_side(my_child_num, s)))
                 {
                   Elem * neigh = parent->neighbor_ptr(s);
                   // If neigh was refined and had non-subactive children
                   // made remote earlier, then our current elem should
                   // actually have one of those remote children as a
                   // neighbor
                   if (neigh &&
                       (neigh->ancestor() ||
                        // If neigh has subactive children which should have
                        // matched as neighbors of the current element but
                        // did not, then those likewise must be remote
                        // children.
                        (current_elem->subactive() && neigh->has_children() &&
                         (neigh->level()+1) == current_elem->level())))
                     {
 #ifdef DEBUG
                       // Let's make sure that "had children made remote"
                       // situation is actually the case
                       libmesh_assert(neigh->has_children());
                       bool neigh_has_remote_children = false;
                       for (auto & child : neigh->child_ref_range())
                         if (&child == remote_elem)
                           neigh_has_remote_children = true;
                       libmesh_assert(neigh_has_remote_children);
                       // And let's double-check that we don't have
                       // a remote_elem neighboring an active local element
                       if (current_elem->active())
                         libmesh_assert_not_equal_to (current_elem->processor_id(),
                                                      this->processor_id());
 #endif // DEBUG
                       neigh = const_cast<RemoteElem *>(remote_elem);
                     }
                   // If neigh and current_elem are more than one level
                   // apart, figuring out whether we have a remote
                   // neighbor here becomes much harder.
                   else if (neigh && (current_elem->subactive() &&
                                      neigh->has_children()))
                     {
                       // Find the deepest descendant of neigh which
                       // we could consider for a neighbor.  If we run
                       // out of neigh children, then that's our
                       // neighbor.  If we find a potential neighbor
                       // with remote_children and we don't find any
                       // potential neighbors among its non-remote
                       // children, then our neighbor must be remote.
                       while (neigh != remote_elem &&
                              neigh->has_children())
{
                           bool found_neigh = false;
                           for (unsigned int c = 0, nc = neigh->n_children();
                                !found_neigh && c != nc; ++c)
{
                               Elem * child = neigh->child_ptr(c);
                               if (child == remote_elem)
                                 continue;
                               for (auto ncn : child->neighbor_ptr_range())
{
                                   if (ncn != remote_elem &&
                                       ncn->is_ancestor_of(current_elem))
{
                                       neigh = ncn;
                                       found_neigh = true;
                                       break;
                                     }
                                 }
                             }
                           if (!found_neigh)
                             neigh = const_cast<RemoteElem *>(remote_elem);
                         }
                     }
                   current_elem->set_neighbor(s, neigh);
 #ifdef DEBUG
                   if (neigh != libmesh_nullptr && neigh != remote_elem)
                     // We ignore subactive elements here because
                     // we don't care about neighbors of subactive element.
                     if ((!neigh->active()) && (!current_elem->subactive()))
                       {
                         libMesh::err << "On processor " << this->processor_id()
                                      << std::endl;
                         libMesh::err << "Bad element ID = " << current_elem->id()
                                      << ", Side " << s << ", Bad neighbor ID = " << neigh->id() << std::endl;
                         libMesh::err << "Bad element proc_ID = " << current_elem->processor_id()
                                      << ", Bad neighbor proc_ID = " << neigh->processor_id() << std::endl;
                         libMesh::err << "Bad element size = " << current_elem->hmin()
                                      << ", Bad neighbor size = " << neigh->hmin() << std::endl;
                         libMesh::err << "Bad element center = " << current_elem->centroid()
                                      << ", Bad neighbor center = " << neigh->centroid() << std::endl;
                         libMesh::err << "ERROR: "
                                      << (current_elem->active()?"Active":"Ancestor")
                                      << " Element at level "
                                      << current_elem->level() << std::endl;
                         libMesh::err << "with "
                                      << (parent->active()?"active":
                                          (parent->subactive()?"subactive":"ancestor"))
                                      << " parent share "
                                      << (neigh->subactive()?"subactive":"ancestor")
                                      << " neighbor at level " << neigh->level()
                                      << std::endl;
                         NameBasedIO(*this).write ("bad_mesh.gmv");
                         libmesh_error_msg("Problematic mesh written to bad_mesh.gmv.");
                       }
 #endif // DEBUG
                 }
             }
           // We can skip to the next element if we're full-dimension
           // and therefore don't have any interior parents
           if (current_elem->dim() >= LIBMESH_DIM)
             continue;
           // We have no interior parents unless we can find one later
           current_elem->set_interior_parent(libmesh_nullptr);
           Elem * pip = parent->interior_parent();
           if (!pip)
             continue;
           // If there's no interior_parent children, whether due to a
           // remote element or a non-conformity, then there's no
           // children to search.
           if (pip == remote_elem || pip->active())
             {
               current_elem->set_interior_parent(pip);
               continue;
             }
           // For node comparisons we'll need a sensible tolerance
           Real node_tolerance = current_elem->hmin() * TOLERANCE;
           // Otherwise our interior_parent should be a child of our
           // parent's interior_parent.
           for (auto & child : pip->child_ref_range())
             {
               // If we have a remote_elem, that might be our
               // interior_parent.  We'll set it provisionally now and
               // keep trying to find something better.
               if (&child == remote_elem)
                 {
                   current_elem->set_interior_parent
                     (const_cast<RemoteElem *>(remote_elem));
                   continue;
                 }
               bool child_contains_our_nodes = true;
               for (auto & n : current_elem->node_ref_range())
                 {
                   bool child_contains_this_node = false;
                   for (auto & cn : child.node_ref_range())
                     if (cn.absolute_fuzzy_equals
                         (n, node_tolerance))
                       {
                         child_contains_this_node = true;
                         break;
                       }
                   if (!child_contains_this_node)
                     {
                       child_contains_our_nodes = false;
                       break;
                     }
                 }
               if (child_contains_our_nodes)
                 {
                   current_elem->set_interior_parent(&child);
                   break;
                 }
             }
           // We should have found *some* interior_parent at this
           // point, whether semilocal or remote.
           libmesh_assert(current_elem->interior_parent());
         }
     }
 #endif // AMR
 #ifdef DEBUG
   MeshTools::libmesh_assert_valid_neighbors(*this,
                                             !reset_remote_elements);
   MeshTools::libmesh_assert_valid_amr_interior_parents(*this);
 #endif
 }
void libMesh::ReplicatedMesh::fix_broken_node_and_element_numbering () virtual inherited
There is no reason for a user to ever call this function.
This function restores a previously broken element/node numbering such that mesh.node_ref(n).id() == n.
Implements libMesh::MeshBase.
Definition at line 791 of file replicated_mesh.C.
References libMesh::ReplicatedMesh::_elements, libMesh::ReplicatedMesh::_nodes, and libmesh_nullptr.
Referenced by libMesh::ReplicatedMesh::reserve_elem().
 {
   // Nodes first
   for (std::size_t n=0; n<this->_nodes.size(); n++)
     if (this->_nodes[n] != libmesh_nullptr)
       this->_nodes[n]->set_id() = cast_int<dof_id_type>(n);
   // Elements next
   for (std::size_t e=0; e<this->_elements.size(); e++)
     if (this->_elements[e] != libmesh_nullptr)
       this->_elements[e]->set_id() = cast_int<dof_id_type>(e);
 }
virtual element_iterator libMesh::ReplicatedMesh::flagged_elements_begin (unsigned char rflag) virtual inherited
Iterate over all elements with a specified refinement flag.
Implements libMesh::MeshBase.
Referenced by libMesh::ReplicatedMesh::active_local_element_ptr_range().
virtual const_element_iterator libMesh::ReplicatedMesh::flagged_elements_begin (unsigned char rflag) const virtual inherited
Implements libMesh::MeshBase.
virtual element_iterator libMesh::ReplicatedMesh::flagged_elements_end (unsigned char rflag) virtual inherited
Implements libMesh::MeshBase.
Referenced by libMesh::ReplicatedMesh::active_local_element_ptr_range().
virtual const_element_iterator libMesh::ReplicatedMesh::flagged_elements_end (unsigned char rflag) const virtual inherited
Implements libMesh::MeshBase.
virtual element_iterator libMesh::ReplicatedMesh::flagged_pid_elements_begin (unsigned char rflag, processor_id_type pid) virtual inherited
Iterate over all elements with a specified refinement flag on a specified processor.
Implements libMesh::MeshBase.
Referenced by libMesh::ReplicatedMesh::active_local_element_ptr_range().
virtual const_element_iterator libMesh::ReplicatedMesh::flagged_pid_elements_begin (unsigned char rflag, processor_id_type pid) const virtual inherited
Implements libMesh::MeshBase.
virtual element_iterator libMesh::ReplicatedMesh::flagged_pid_elements_end (unsigned char rflag, processor_id_type pid) virtual inherited
Implements libMesh::MeshBase.
Referenced by libMesh::ReplicatedMesh::active_local_element_ptr_range().
virtual const_element_iterator libMesh::ReplicatedMesh::flagged_pid_elements_end (unsigned char rflag, processor_id_type pid) const virtual inherited
Implements libMesh::MeshBase.
virtual void libMesh::MeshBase::gather_to_zero () inline virtual inherited
Gathers all elements and nodes of the mesh onto processor zero
Reimplemented in libMesh::DistributedMesh.
Definition at line 176 of file mesh_base.h.
Referenced by libMesh::MeshSerializer::MeshSerializer().
 {}
const BoundaryInfo& libMesh::MeshBase::get_boundary_info () const inline inherited
The information about boundary ids on the mesh
Definition at line 118 of file mesh_base.h.
References libMesh::MeshBase::boundary_info.
Referenced by libMesh::MeshRefinement::_coarsen_elements(), libMesh::MeshTools::Subdivision::add_boundary_ghosts(), libMesh::UnstructuredMesh::all_first_order(), libMesh::UnstructuredMesh::all_second_order(), libMesh::MeshTools::Subdivision::all_subdivision(), libMesh::MeshTools::Modification::all_tri(), libMesh::AbaqusIO::assign_boundary_node_ids(), libMesh::AbaqusIO::assign_sideset_ids(), libMesh::MeshCommunication::broadcast(), libMesh::MeshTools::Generation::build_cube(), libMesh::MeshTools::Generation::build_delaunay_square(), libMesh::MeshTools::Generation::build_extrusion(), libMesh::MeshTools::Generation::build_sphere(), libMesh::MeshTools::Modification::change_boundary_id(), libMesh::DofMap::check_dirichlet_bcid_consistency(), libMesh::MeshBase::clear(), libMesh::Nemesis_IO_Helper::compute_num_global_nodesets(), libMesh::Nemesis_IO_Helper::compute_num_global_sidesets(), libMesh::FEGenericBase< OutputType >::compute_periodic_constraints(), libMesh::FEAbstract::compute_periodic_node_constraints(), libMesh::UnstructuredMesh::create_submesh(), libMesh::TetGenMeshInterface::delete_2D_hull_elements(), libMesh::ReplicatedMesh::delete_elem(), libMesh::DistributedMesh::delete_elem(), libMesh::ReplicatedMesh::delete_node(), libMesh::DistributedMesh::delete_node(), libMesh::MeshCommunication::delete_remote_elements(), libMesh::DistributedMesh::DistributedMesh(), libMesh::MeshTools::Modification::flatten(), libMesh::UNVIO::groups_in(), libMesh::ExodusII_IO_Helper::initialize(), libMesh::MeshTools::libmesh_assert_valid_boundary_ids(), libMesh::Parallel::Packing< const Node * >::pack(), libMesh::Parallel::Packing< const Elem * >::pack(), libMesh::Parallel::Packing< const Node * >::packable_size(), libMesh::Parallel::Packing< const Elem * >::packable_size(), libMesh::TetGenMeshInterface::pointset_convexhull(), libMesh::Nemesis_IO::prepare_to_write_nodal_data(), libMesh::AbaqusIO::read(), libMesh::Nemesis_IO::read(), libMesh::ExodusII_IO::read(), libMesh::CheckpointIO::read_bcs(), libMesh::CheckpointIO::read_header(), libMesh::CheckpointIO::read_nodesets(), libMesh::ReplicatedMesh::renumber_nodes_and_elements(), libMesh::DistributedMesh::renumber_nodes_and_elements(), libMesh::ReplicatedMesh::ReplicatedMesh(), libMesh::ReplicatedMesh::stitching_helper(), libMesh::BoundaryInfo::sync(), libMesh::Elem::topological_neighbor(), libMesh::Parallel::Packing< Node * >::unpack(), libMesh::Parallel::Packing< Elem * >::unpack(), libMesh::FroIO::write(), libMesh::Nemesis_IO::write(), libMesh::ExodusII_IO::write(), libMesh::XdrIO::write(), libMesh::CheckpointIO::write(), libMesh::ExodusII_IO::write_nodal_data_common(), libMesh::Nemesis_IO_Helper::write_nodesets(), libMesh::ExodusII_IO_Helper::write_nodesets(), libMesh::Nemesis_IO_Helper::write_sidesets(), and libMesh::ExodusII_IO_Helper::write_sidesets().
 { return *boundary_info; }
BoundaryInfo& libMesh::MeshBase::get_boundary_info () inline inherited
Writable information about boundary ids on the mesh
Definition at line 123 of file mesh_base.h.
References libMesh::MeshBase::boundary_info, and libMesh::MeshBase::clear().
 { return *boundary_info; }
bool libMesh::MeshBase::get_count_lower_dim_elems_in_point_locator () const inherited
Get the current value of _count_lower_dim_elems_in_point_locator.
Definition at line 571 of file mesh_base.C.
References libMesh::MeshBase::_count_lower_dim_elems_in_point_locator.
Referenced by libMesh::TreeNode< N >::insert().
 {
   return _count_lower_dim_elems_in_point_locator;
 }
subdomain_id_type libMesh::MeshBase::get_id_by_name (const std::string & name) const inherited
Returns
The id of the named subdomain if it exists, Elem::invalid_subdomain_id otherwise.
Definition at line 598 of file mesh_base.C.
References libMesh::MeshBase::_block_id_to_name, and libMesh::Elem::invalid_subdomain_id.
Referenced by libMesh::MeshBase::libmesh_assert_valid_parallel_ids().
 {
   // Linear search over the map values.
   std::map<subdomain_id_type, std::string>::const_iterator
     iter = _block_id_to_name.begin(),
     end_iter = _block_id_to_name.end();
   for ( ; iter != end_iter; ++iter)
     if (iter->second == name)
       return iter->first;
   // If we made it here without returning, we don't have a subdomain
   // with the requested name, so return Elem::invalid_subdomain_id.
   return Elem::invalid_subdomain_id;
 }
std::string libMesh::MeshBase::get_info () const inherited
Returns
A string containing relevant information about the mesh.
Definition at line 416 of file mesh_base.C.
References libMesh::MeshBase::_elem_dims, libMesh::MeshBase::n_active_elem(), libMesh::MeshBase::n_elem(), libMesh::MeshBase::n_local_elem(), libMesh::MeshBase::n_local_nodes(), libMesh::MeshBase::n_nodes(), libMesh::MeshBase::n_partitions(), libMesh::ParallelObject::n_processors(), libMesh::MeshBase::n_subdomains(), libMesh::n_threads(), libMesh::ParallelObject::processor_id(), and libMesh::MeshBase::spatial_dimension().
Referenced by libMesh::MeshBase::n_partitions(), and libMesh::MeshBase::print_info().
 {
   std::ostringstream oss;
   oss << " Mesh Information:"                                  << '\n';
   if (!_elem_dims.empty())
     {
       oss << "  elem_dimensions()={";
       std::copy(_elem_dims.begin(),
                 --_elem_dims.end(), // --end() is valid if the set is non-empty
                 std::ostream_iterator<unsigned int>(oss, ", "));
       oss << cast_int<unsigned int>(*_elem_dims.rbegin());
       oss << "}\n";
     }
   oss << "  spatial_dimension()=" << this->spatial_dimension() << '\n'
       << "  n_nodes()="           << this->n_nodes()           << '\n'
       << "    n_local_nodes()="   << this->n_local_nodes()     << '\n'
       << "  n_elem()="            << this->n_elem()            << '\n'
       << "    n_local_elem()="    << this->n_local_elem()      << '\n'
 #ifdef LIBMESH_ENABLE_AMR
       << "    n_active_elem()="   << this->n_active_elem()     << '\n'
 #endif
       << "  n_subdomains()="      << static_cast<std::size_t>(this->n_subdomains()) << '\n'
       << "  n_partitions()="      << static_cast<std::size_t>(this->n_partitions()) << '\n'
       << "  n_processors()="      << static_cast<std::size_t>(this->n_processors()) << '\n'
       << "  n_threads()="         << static_cast<std::size_t>(libMesh::n_threads()) << '\n'
       << "  processor_id()="      << static_cast<std::size_t>(this->processor_id()) << '\n';
   return oss.str();
 }
const std::map<subdomain_id_type, std::string>& libMesh::MeshBase::get_subdomain_name_map () const inline inherited
Definition at line 1296 of file mesh_base.h.
References libMesh::MeshBase::_block_id_to_name, libMesh::MeshBase::cache_elem_dims(), and libMesh::MeshBase::detect_interior_parents().
Referenced by libMesh::XdrIO::write_serialized_subdomain_names(), and libMesh::CheckpointIO::write_subdomain_names().
   { return _block_id_to_name; }
virtual element_iterator libMesh::ReplicatedMesh::ghost_elements_begin () virtual inherited
Iterate over "ghost" elements in the Mesh. A ghost element is one which is not local, but is semilocal.
Implements libMesh::MeshBase.
Referenced by libMesh::ReplicatedMesh::active_local_element_ptr_range().
virtual const_element_iterator libMesh::ReplicatedMesh::ghost_elements_begin () const virtual inherited
Implements libMesh::MeshBase.
virtual element_iterator libMesh::ReplicatedMesh::ghost_elements_end () virtual inherited
Implements libMesh::MeshBase.
Referenced by libMesh::ReplicatedMesh::active_local_element_ptr_range().
virtual const_element_iterator libMesh::ReplicatedMesh::ghost_elements_end () const virtual inherited
Implements libMesh::MeshBase.
std::set<GhostingFunctor *>::const_iterator libMesh::MeshBase::ghosting_functors_begin () const inline inherited
Beginning of range of ghosting functors
Definition at line 799 of file mesh_base.h.
References libMesh::MeshBase::_ghosting_functors.
Referenced by libMesh::UnstructuredMesh::contract(), libMesh::MeshCommunication::delete_remote_elements(), libMesh::MeshBase::prepare_for_use(), libMesh::query_ghosting_functors(), libMesh::MeshCommunication::redistribute(), and libMesh::MeshCommunication::send_coarse_ghosts().
   { return _ghosting_functors.begin(); }
std::set<GhostingFunctor *>::const_iterator libMesh::MeshBase::ghosting_functors_end () const inline inherited
End of range of ghosting functors
Definition at line 805 of file mesh_base.h.
References libMesh::MeshBase::_ghosting_functors, libMesh::MeshBase::n_subdomains(), and libMesh::MeshBase::subdomain_ids().
Referenced by libMesh::UnstructuredMesh::contract(), libMesh::MeshCommunication::delete_remote_elements(), libMesh::MeshBase::prepare_for_use(), libMesh::query_ghosting_functors(), libMesh::MeshCommunication::redistribute(), and libMesh::MeshCommunication::send_coarse_ghosts().
   { return _ghosting_functors.end(); }
Elem * libMesh::ReplicatedMesh::insert_elem (Elem * e) virtual inherited
Insert elem e to the element array, preserving its id and replacing/deleting any existing element with the same id.
Users should call MeshBase::prepare_for_use() after elements are added to and/or deleted from the mesh.
Implements libMesh::MeshBase.
Definition at line 322 of file replicated_mesh.C.
References libMesh::ReplicatedMesh::_elements, libMesh::MeshBase::_next_unique_id, libMesh::ReplicatedMesh::delete_elem(), libMesh::DofObject::id(), libMesh::DofObject::set_unique_id(), and libMesh::DofObject::valid_unique_id().
Referenced by libMesh::ReplicatedMesh::reserve_elem().
 {
 #ifdef LIBMESH_ENABLE_UNIQUE_ID
   if (!e->valid_unique_id())
     e->set_unique_id() = _next_unique_id++;
 #endif
   dof_id_type eid = e->id();
   libmesh_assert_less (eid, _elements.size());
   Elem * oldelem = _elements[eid];
   if (oldelem)
     {
       libmesh_assert_equal_to (oldelem->id(), eid);
       this->delete_elem(oldelem);
     }
   _elements[e->id()] = e;
   return e;
 }
Node * libMesh::ReplicatedMesh::insert_node (Node * n) virtual inherited
Insert Node n into the Mesh at a location consistent with n->id(), allocating extra storage if necessary. Throws an error if: .) n==NULL .) n->id() == DofObject::invalid_id .) A node already exists in position n->id().
This function differs from the ReplicatedMesh::add_node() function, which is only capable of appending nodes at the end of the nodes storage.
Implements libMesh::MeshBase.
Definition at line 476 of file replicated_mesh.C.
References libMesh::MeshBase::_next_unique_id, libMesh::ReplicatedMesh::_nodes, libMesh::DofObject::id(), libMesh::DofObject::invalid_id, libmesh_nullptr, libMesh::DofObject::set_unique_id(), and libMesh::DofObject::valid_unique_id().
Referenced by libMesh::ReplicatedMesh::reserve_elem().
 {
   if (!n)
     libmesh_error_msg("Error, attempting to insert NULL node.");
   if (n->id() == DofObject::invalid_id)
     libmesh_error_msg("Error, cannot insert node with invalid id.");
   if (n->id() < _nodes.size())
     {
       // Don't allow inserting on top of an existing Node.
       // Doing so doesn't have to be *error*, in the case where a
       // redundant insert is done, but when that happens we ought to
       // always be able to make the code more efficient by avoiding
       // the redundant insert, so let's keep screaming "Error" here.
       if (_nodes[ n->id() ] != libmesh_nullptr)
         libmesh_error_msg("Error, cannot insert node on top of existing node.");
     }
   else
     {
       // Allocate just enough space to store the new node.  This will
       // cause highly non-ideal memory allocation behavior if called
       // repeatedly...
       _nodes.resize(n->id() + 1);
     }
 #ifdef LIBMESH_ENABLE_UNIQUE_ID
   if (!n->valid_unique_id())
     n->set_unique_id() = _next_unique_id++;
 #endif
   // We have enough space and this spot isn't already occupied by
   // another node, so go ahead and add it.
   _nodes[ n->id() ] = n;
   // If we made it this far, we just inserted the node the user handed
   // us, so we can give it right back.
   return n;
 }
bool libMesh::MeshBase::is_prepared () const inline inherited
Returns
true if the mesh has been prepared via a call to prepare_for_use, false otherwise.
Definition at line 134 of file mesh_base.h.
References libMesh::MeshBase::_is_prepared.
Referenced by libMesh::DofMap::build_sparsity(), libMesh::DofMap::create_dof_constraints(), libMesh::DofMap::distribute_dofs(), and libMesh::DofMap::reinit().
   { return _is_prepared; }
virtual bool libMesh::MeshBase::is_replicated () const inline virtual inherited
Returns
true if new elements and nodes can and should be created in synchronization on all processors, false otherwise
Reimplemented in libMesh::DistributedMesh.
Definition at line 163 of file mesh_base.h.
Referenced by libMesh::MeshRefinement::_refine_elements(), libMesh::MeshRefinement::make_coarsening_compatible(), libMesh::CheckpointIO::read(), and libMesh::MeshRefinement::uniformly_coarsen().
   { return true; }
virtual bool libMesh::MeshBase::is_serial () const inline virtual inherited
Returns
true if all elements and nodes of the mesh exist on the current processor, false otherwise
Reimplemented in libMesh::DistributedMesh.
Definition at line 141 of file mesh_base.h.
Referenced by libMesh::MeshRefinement::_coarsen_elements(), libMesh::MeshRefinement::_smooth_flags(), libMesh::BoundaryInfo::add_elements(), libMesh::UnstructuredMesh::all_second_order(), libMesh::MeshTools::Modification::all_tri(), libMesh::EquationSystems::allgather(), libMesh::DofMap::allgather_recursive_constraints(), libMesh::MeshTools::Generation::build_extrusion(), libMesh::InfElemBuilder::build_inf_elem(), libMesh::BoundaryInfo::build_node_list_from_side_list(), libMesh::DofMap::create_dof_constraints(), libMesh::UnstructuredMesh::create_submesh(), libMesh::LocationMap< T >::init(), libMesh::TopologyMap::init(), libMesh::MeshRefinement::make_coarsening_compatible(), libMesh::MeshSerializer::MeshSerializer(), libMesh::BoundaryInfo::n_boundary_conds(), libMesh::BoundaryInfo::n_edge_conds(), libMesh::BoundaryInfo::n_nodeset_conds(), libMesh::BoundaryInfo::n_shellface_conds(), libMesh::MeshBase::partition(), libMesh::MetisPartitioner::partition_range(), libMesh::LinearPartitioner::partition_range(), libMesh::SFCPartitioner::partition_range(), libMesh::CentroidPartitioner::partition_range(), libMesh::System::point_gradient(), libMesh::System::point_hessian(), libMesh::System::point_value(), libMesh::MeshBase::prepare_for_use(), libMesh::Nemesis_IO::read(), libMesh::DofMap::scatter_constraints(), libMesh::MeshCommunication::send_coarse_ghosts(), libMesh::Partitioner::set_parent_processor_ids(), libMesh::BoundaryInfo::sync(), libMesh::MeshTools::total_weight(), libMesh::CheckpointIO::write(), and libMesh::XdrIO::write_parallel().
   { return true; }
virtual bool libMesh::MeshBase::is_serial_on_zero () const inline virtual inherited
Returns
true if all elements and nodes of the mesh exist on the processor 0, false otherwise
Reimplemented in libMesh::DistributedMesh.
Definition at line 148 of file mesh_base.h.
   { return true; }
virtual element_iterator libMesh::ReplicatedMesh::level_elements_begin (unsigned int level) virtual inherited
Iterate over elements of a given level.
Implements libMesh::MeshBase.
Referenced by libMesh::ReplicatedMesh::active_local_element_ptr_range().
virtual const_element_iterator libMesh::ReplicatedMesh::level_elements_begin (unsigned int level) const virtual inherited
Implements libMesh::MeshBase.
virtual element_iterator libMesh::ReplicatedMesh::level_elements_end (unsigned int level) virtual inherited
Implements libMesh::MeshBase.
Referenced by libMesh::ReplicatedMesh::active_local_element_ptr_range().
virtual const_element_iterator libMesh::ReplicatedMesh::level_elements_end (unsigned int level) const virtual inherited
Implements libMesh::MeshBase.
virtual void libMesh::MeshBase::libmesh_assert_valid_parallel_ids () const inline virtual inherited
Verify id and processor_id consistency of our elements and nodes containers. Calls libmesh_assert() on each possible failure. Currently only implemented on DistributedMesh; a serial data structure is much harder to get out of sync.
Reimplemented in libMesh::DistributedMesh.
Definition at line 966 of file mesh_base.h.
References libMesh::MeshBase::active_element_ptr_range(), libMesh::MeshBase::active_elements_begin(), libMesh::MeshBase::active_elements_end(), libMesh::MeshBase::active_local_element_ptr_range(), libMesh::MeshBase::active_local_elements_begin(), libMesh::MeshBase::active_local_elements_end(), libMesh::MeshBase::active_local_subdomain_elements_begin(), libMesh::MeshBase::active_local_subdomain_elements_end(), libMesh::MeshBase::active_nodes_begin(), libMesh::MeshBase::active_nodes_end(), libMesh::MeshBase::active_not_local_elements_begin(), libMesh::MeshBase::active_not_local_elements_end(), libMesh::MeshBase::active_pid_elements_begin(), libMesh::MeshBase::active_pid_elements_end(), libMesh::MeshBase::active_semilocal_elements_begin(), libMesh::MeshBase::active_semilocal_elements_end(), libMesh::MeshBase::active_subdomain_elements_begin(), libMesh::MeshBase::active_subdomain_elements_end(), libMesh::MeshBase::active_subdomain_set_elements_begin(), libMesh::MeshBase::active_subdomain_set_elements_end(), libMesh::MeshBase::active_type_elements_begin(), libMesh::MeshBase::active_type_elements_end(), libMesh::MeshBase::active_unpartitioned_elements_begin(), libMesh::MeshBase::active_unpartitioned_elements_end(), libMesh::MeshBase::ancestor_elements_begin(), libMesh::MeshBase::ancestor_elements_end(), libMesh::MeshBase::bid_nodes_begin(), libMesh::MeshBase::bid_nodes_end(), libMesh::MeshBase::bnd_nodes_begin(), libMesh::MeshBase::bnd_nodes_end(), libMesh::MeshBase::element_ptr_range(), libMesh::MeshBase::elements_begin(), libMesh::MeshBase::elements_end(), libMesh::MeshBase::evaluable_elements_begin(), libMesh::MeshBase::evaluable_elements_end(), libMesh::MeshBase::evaluable_nodes_begin(), libMesh::MeshBase::evaluable_nodes_end(), libMesh::MeshBase::facelocal_elements_begin(), libMesh::MeshBase::facelocal_elements_end(), libMesh::MeshBase::flagged_elements_begin(), libMesh::MeshBase::flagged_elements_end(), libMesh::MeshBase::flagged_pid_elements_begin(), libMesh::MeshBase::flagged_pid_elements_end(), libMesh::MeshBase::get_id_by_name(), libMesh::MeshBase::ghost_elements_begin(), libMesh::MeshBase::ghost_elements_end(), libMesh::invalid_uint, libMesh::MeshBase::level_elements_begin(), libMesh::MeshBase::level_elements_end(), libMesh::MeshBase::local_elements_begin(), libMesh::MeshBase::local_elements_end(), libMesh::MeshBase::local_level_elements_begin(), libMesh::MeshBase::local_level_elements_end(), libMesh::MeshBase::local_node_ptr_range(), libMesh::MeshBase::local_nodes_begin(), libMesh::MeshBase::local_nodes_end(), libMesh::MeshBase::local_not_level_elements_begin(), libMesh::MeshBase::local_not_level_elements_end(), libMesh::MeshBase::node_ptr_range(), libMesh::MeshBase::nodes_begin(), libMesh::MeshBase::nodes_end(), libMesh::MeshBase::not_active_elements_begin(), libMesh::MeshBase::not_active_elements_end(), libMesh::MeshBase::not_ancestor_elements_begin(), libMesh::MeshBase::not_ancestor_elements_end(), libMesh::MeshBase::not_level_elements_begin(), libMesh::MeshBase::not_level_elements_end(), libMesh::MeshBase::not_local_elements_begin(), libMesh::MeshBase::not_local_elements_end(), libMesh::MeshBase::not_subactive_elements_begin(), libMesh::MeshBase::not_subactive_elements_end(), libMesh::MeshBase::pid_elements_begin(), libMesh::MeshBase::pid_elements_end(), libMesh::MeshBase::pid_nodes_begin(), libMesh::MeshBase::pid_nodes_end(), libMesh::MeshBase::semilocal_elements_begin(), libMesh::MeshBase::semilocal_elements_end(), libMesh::MeshBase::subactive_elements_begin(), libMesh::MeshBase::subactive_elements_end(), libMesh::MeshBase::subdomain_name(), libMesh::MeshBase::type_elements_begin(), libMesh::MeshBase::type_elements_end(), libMesh::MeshBase::unpartitioned_elements_begin(), and libMesh::MeshBase::unpartitioned_elements_end().
Referenced by libMesh::MeshRefinement::_refine_elements(), libMesh::InfElemBuilder::build_inf_elem(), and libMesh::MeshRefinement::refine_and_coarsen_elements().
 {}
virtual element_iterator libMesh::ReplicatedMesh::local_elements_begin () virtual inherited
Implements libMesh::MeshBase.
Referenced by libMesh::ReplicatedMesh::active_element_ptr_range().
virtual const_element_iterator libMesh::ReplicatedMesh::local_elements_begin () const virtual inherited
Implements libMesh::MeshBase.
virtual element_iterator libMesh::ReplicatedMesh::local_elements_end () virtual inherited
Implements libMesh::MeshBase.
Referenced by libMesh::ReplicatedMesh::active_element_ptr_range().
virtual const_element_iterator libMesh::ReplicatedMesh::local_elements_end () const virtual inherited
Implements libMesh::MeshBase.
virtual element_iterator libMesh::ReplicatedMesh::local_level_elements_begin (unsigned int level) virtual inherited
Implements libMesh::MeshBase.
Referenced by libMesh::ReplicatedMesh::active_local_element_ptr_range().
virtual const_element_iterator libMesh::ReplicatedMesh::local_level_elements_begin (unsigned int level) const virtual inherited
Implements libMesh::MeshBase.
virtual element_iterator libMesh::ReplicatedMesh::local_level_elements_end (unsigned int level) virtual inherited
Implements libMesh::MeshBase.
Referenced by libMesh::ReplicatedMesh::active_local_element_ptr_range().
virtual const_element_iterator libMesh::ReplicatedMesh::local_level_elements_end (unsigned int level) const virtual inherited
Implements libMesh::MeshBase.
virtual SimpleRange<node_iterator> libMesh::ReplicatedMesh::local_node_ptr_range () inline virtual inherited
Implements libMesh::MeshBase.
Definition at line 437 of file replicated_mesh.h.
References libMesh::ReplicatedMesh::local_nodes_begin(), and libMesh::ReplicatedMesh::local_nodes_end().
 { return {local_nodes_begin(), local_nodes_end()}; }
virtual SimpleRange<const_node_iterator> libMesh::ReplicatedMesh::local_node_ptr_range () const inline virtual inherited
Implements libMesh::MeshBase.
Definition at line 438 of file replicated_mesh.h.
References libMesh::ReplicatedMesh::bid_nodes_begin(), libMesh::ReplicatedMesh::bid_nodes_end(), libMesh::ReplicatedMesh::bnd_nodes_begin(), libMesh::ReplicatedMesh::bnd_nodes_end(), libMesh::ReplicatedMesh::evaluable_nodes_begin(), libMesh::ReplicatedMesh::evaluable_nodes_end(), libMesh::invalid_uint, libMesh::ReplicatedMesh::local_nodes_begin(), libMesh::ReplicatedMesh::local_nodes_end(), libMesh::ReplicatedMesh::pid_nodes_begin(), and libMesh::ReplicatedMesh::pid_nodes_end().
 { return {local_nodes_begin(), local_nodes_end()}; }
virtual node_iterator libMesh::ReplicatedMesh::local_nodes_begin () virtual inherited
Iterate over local nodes (nodes whose processor_id() matches the current processor).
Implements libMesh::MeshBase.
Referenced by libMesh::ReplicatedMesh::local_node_ptr_range(), and libMesh::ReplicatedMesh::node_ptr_range().
virtual const_node_iterator libMesh::ReplicatedMesh::local_nodes_begin () const virtual inherited
Implements libMesh::MeshBase.
virtual node_iterator libMesh::ReplicatedMesh::local_nodes_end () virtual inherited
Implements libMesh::MeshBase.
Referenced by libMesh::ReplicatedMesh::local_node_ptr_range(), and libMesh::ReplicatedMesh::node_ptr_range().
virtual const_node_iterator libMesh::ReplicatedMesh::local_nodes_end () const virtual inherited
Implements libMesh::MeshBase.
virtual element_iterator libMesh::ReplicatedMesh::local_not_level_elements_begin (unsigned int level) virtual inherited
Implements libMesh::MeshBase.
Referenced by libMesh::ReplicatedMesh::active_local_element_ptr_range().
virtual const_element_iterator libMesh::ReplicatedMesh::local_not_level_elements_begin (unsigned int level) const virtual inherited
Implements libMesh::MeshBase.
virtual element_iterator libMesh::ReplicatedMesh::local_not_level_elements_end (unsigned int level) virtual inherited
Implements libMesh::MeshBase.
Referenced by libMesh::ReplicatedMesh::active_local_element_ptr_range().
virtual const_element_iterator libMesh::ReplicatedMesh::local_not_level_elements_end (unsigned int level) const virtual inherited
Implements libMesh::MeshBase.
virtual dof_id_type libMesh::ReplicatedMesh::max_elem_id () const inline virtual inherited
Returns
A number greater than or equal to the maximum element id in the mesh.
Implements libMesh::MeshBase.
Definition at line 128 of file replicated_mesh.h.
References libMesh::ReplicatedMesh::_elements, and libMesh::ReplicatedMesh::parallel_max_unique_id().
Referenced by libMesh::ReplicatedMesh::stitching_helper().
   { return cast_int<dof_id_type>(_elements.size()); }
virtual dof_id_type libMesh::ReplicatedMesh::max_node_id () const inline virtual inherited
Returns
A number greater than or equal to the maximum node id in the mesh.
Implements libMesh::MeshBase.
Definition at line 114 of file replicated_mesh.h.
References libMesh::ReplicatedMesh::_nodes.
Referenced by libMesh::ReplicatedMesh::stitching_helper().
   { return cast_int<dof_id_type>(_nodes.size()); }
unsigned int libMesh::MeshBase::mesh_dimension () const inherited
Returns
The logical dimension of the mesh; i.e. the manifold dimension of the elements in the mesh. If we ever support multi-dimensional meshes (e.g. hexes and quads in the same mesh) then this will return the largest such dimension.
Definition at line 150 of file mesh_base.C.
References libMesh::MeshBase::_elem_dims.
Referenced by libMesh::UniformRefinementEstimator::_estimate_error(), libMesh::HPCoarsenTest::add_projection(), libMesh::UnstructuredMesh::all_second_order(), libMesh::MeshTools::Modification::all_tri(), libMesh::MeshTools::Generation::build_cube(), libMesh::EquationSystems::build_discontinuous_solution_vector(), libMesh::EquationSystems::build_parallel_solution_vector(), libMesh::MeshTools::Generation::build_sphere(), libMesh::EquationSystems::build_variable_names(), libMesh::MeshBase::cache_elem_dims(), libMesh::DofMap::create_dof_constraints(), libMesh::MeshBase::delete_remote_elements(), libMesh::MeshTools::Modification::distort(), libMesh::ExactErrorEstimator::estimate_error(), libMesh::MeshRefinement::flag_elements_by_elem_fraction(), libMesh::MeshRefinement::flag_elements_by_nelem_target(), libMesh::LaplaceMeshSmoother::init(), libMesh::PointLocatorTree::init(), libMesh::ExodusII_IO_Helper::initialize(), libMesh::FEInterface::n_vec_dim(), libMesh::WeightedPatchRecoveryErrorEstimator::EstimateError::operator()(), libMesh::PatchRecoveryErrorEstimator::EstimateError::operator()(), libMesh::GMVIO::read(), libMesh::Nemesis_IO::read(), libMesh::ExodusII_IO::read(), libMesh::VTKIO::read(), libMesh::XdrIO::read_serialized_connectivity(), libMesh::HPCoarsenTest::select_refinement(), libMesh::MeshTools::Modification::smooth(), libMesh::DofMap::use_coupled_neighbor_dofs(), libMesh::PostscriptIO::write(), libMesh::CheckpointIO::write(), libMesh::TecplotIO::write_binary(), libMesh::GMVIO::write_binary(), libMesh::GMVIO::write_discontinuous_gmv(), libMesh::UCDIO::write_nodal_data(), libMesh::EnsightIO::write_scalar_ascii(), libMesh::GnuPlotIO::write_solution(), and libMesh::EnsightIO::write_vector_ascii().
 {
   if (!_elem_dims.empty())
     return cast_int<unsigned int>(*_elem_dims.rbegin());
   return 0;
 }
dof_id_type libMesh::ReplicatedMesh::n_active_elem () const virtual inherited
Returns
The number of active elements in the mesh.
Implemented in terms of active_element_iterators.
Implements libMesh::MeshBase.
Definition at line 1500 of file replicated_mesh.C.
References libMesh::ReplicatedMesh::active_elements_begin(), and libMesh::ReplicatedMesh::active_elements_end().
Referenced by libMesh::ReplicatedMesh::parallel_n_elem().
 {
   return static_cast<dof_id_type>(std::distance (this->active_elements_begin(),
                                                  this->active_elements_end()));
 }
dof_id_type libMesh::MeshBase::n_active_elem_on_proc (const processor_id_type proc) const inherited
Returns
The number of active elements on processor proc.
Definition at line 377 of file mesh_base.C.
References libMesh::MeshBase::active_pid_elements_begin(), libMesh::MeshBase::active_pid_elements_end(), and libMesh::ParallelObject::n_processors().
Referenced by libMesh::MeshBase::n_active_local_elem(), and libMesh::MeshBase::n_unpartitioned_elem().
 {
   libmesh_assert_less (proc_id, this->n_processors());
   return static_cast<dof_id_type>(std::distance (this->active_pid_elements_begin(proc_id),
                                                  this->active_pid_elements_end  (proc_id)));
 }
dof_id_type libMesh::MeshBase::n_active_local_elem () const inline inherited
Returns
The number of active elements on the local processor.
Definition at line 390 of file mesh_base.h.
References libMesh::MeshBase::n_active_elem_on_proc(), libMesh::MeshBase::n_active_sub_elem(), libMesh::MeshBase::n_sub_elem(), libMesh::MeshBase::point(), and libMesh::ParallelObject::processor_id().
Referenced by libMesh::ParmetisPartitioner::assign_partitioning(), libMesh::ParmetisPartitioner::build_graph(), libMesh::VTKIO::cells_to_vtk(), and libMesh::ParmetisPartitioner::initialize().
   { return this->n_active_elem_on_proc (this->processor_id()); }
dof_id_type libMesh::MeshBase::n_active_sub_elem () const inherited
Same as n_sub_elem(), but only counts active elements.
Definition at line 401 of file mesh_base.C.
References libMesh::MeshBase::active_elements_begin(), libMesh::MeshBase::active_elements_end(), and end.
Referenced by libMesh::MeshBase::n_active_local_elem(), libMesh::TecplotIO::write_ascii(), libMesh::GMVIO::write_ascii_old_impl(), and libMesh::TecplotIO::write_binary().
 {
   dof_id_type ne=0;
   const_element_iterator       el  = this->active_elements_begin();
   const const_element_iterator end = this->active_elements_end();
   for (; el!=end; ++el)
     ne += (*el)->n_sub_elem();
   return ne;
 }
virtual dof_id_type libMesh::ReplicatedMesh::n_elem () const inline virtual inherited
Returns
The number of elements in the mesh.
The standard n_elem() function may return a cached value on distributed meshes, and so can be called by any processor at any time.
Implements libMesh::MeshBase.
Definition at line 120 of file replicated_mesh.h.
References libMesh::ReplicatedMesh::_elements.
Referenced by libMesh::ReplicatedMesh::elem_ptr(), and libMesh::ReplicatedMesh::query_elem_ptr().
   { return cast_int<dof_id_type>(_elements.size()); }
dof_id_type libMesh::MeshBase::n_elem_on_proc (const processor_id_type proc) const inherited
Returns
The number of elements on processor proc.
Definition at line 364 of file mesh_base.C.
References libMesh::DofObject::invalid_processor_id, libMesh::ParallelObject::n_processors(), libMesh::MeshBase::pid_elements_begin(), and libMesh::MeshBase::pid_elements_end().
Referenced by libMesh::MeshBase::n_local_elem(), libMesh::MeshBase::n_unpartitioned_elem(), and libMesh::MeshBase::set_next_unique_id().
 {
   // We're either counting a processor's elements or unpartitioned
   // elements
   libmesh_assert (proc_id < this->n_processors() ||
                   proc_id == DofObject::invalid_processor_id);
   return static_cast<dof_id_type>(std::distance (this->pid_elements_begin(proc_id),
                                                  this->pid_elements_end  (proc_id)));
 }
dof_id_type libMesh::MeshBase::n_local_elem () const inline inherited
Returns
The number of elements on the local processor.
Definition at line 373 of file mesh_base.h.
References libMesh::MeshBase::n_elem_on_proc(), and libMesh::ParallelObject::processor_id().
Referenced by libMesh::MeshBase::get_info(), and libMesh::DistributedMesh::parallel_n_elem().
   { return this->n_elem_on_proc (this->processor_id()); }
dof_id_type libMesh::MeshBase::n_local_nodes () const inline inherited
Returns
The number of nodes on the local processor.
Definition at line 273 of file mesh_base.h.
References libMesh::MeshBase::n_nodes_on_proc(), and libMesh::ParallelObject::processor_id().
Referenced by libMesh::MeshBase::get_info(), libMesh::VTKIO::nodes_to_vtk(), and libMesh::DistributedMesh::parallel_n_nodes().
   { return this->n_nodes_on_proc (this->processor_id()); }
virtual dof_id_type libMesh::ReplicatedMesh::n_nodes () const inline virtual inherited
Returns
The number of nodes in the mesh.
This function and others must be defined in derived classes since the MeshBase class has no specific storage for nodes or elements. The standard n_nodes() function may return a cached value on distributed meshes, and so can be called by any processor at any time.
Implements libMesh::MeshBase.
Definition at line 108 of file replicated_mesh.h.
References libMesh::ReplicatedMesh::_nodes.
Referenced by libMesh::ReplicatedMesh::node_ptr(), and libMesh::ReplicatedMesh::query_node_ptr().
   { return cast_int<dof_id_type>(_nodes.size()); }
dof_id_type libMesh::MeshBase::n_nodes_on_proc (const processor_id_type proc) const inherited
Returns
The number of nodes on processor proc.
Definition at line 351 of file mesh_base.C.
References libMesh::DofObject::invalid_processor_id, libMesh::ParallelObject::n_processors(), libMesh::MeshBase::pid_nodes_begin(), and libMesh::MeshBase::pid_nodes_end().
Referenced by libMesh::MeshBase::elem_dimensions(), libMesh::MeshBase::n_local_nodes(), and libMesh::MeshBase::n_unpartitioned_nodes().
 {
   // We're either counting a processor's nodes or unpartitioned
   // nodes
   libmesh_assert (proc_id < this->n_processors() ||
                   proc_id == DofObject::invalid_processor_id);
   return static_cast<dof_id_type>(std::distance (this->pid_nodes_begin(proc_id),
                                                  this->pid_nodes_end  (proc_id)));
 }
unsigned int libMesh::MeshBase::n_partitions () const inline inherited
Returns
The number of partitions which have been defined via a call to either mesh.partition() or by building a Partitioner object and calling partition.
Note
The partitioner object is responsible for setting this value.
Definition at line 834 of file mesh_base.h.
References libMesh::MeshBase::_n_parts, libMesh::MeshBase::all_first_order(), libMesh::MeshBase::all_second_order(), libMesh::MeshBase::get_info(), libmesh_nullptr, libMesh::Quality::name(), libMesh::MeshBase::operator<<, libMesh::out, libMesh::MeshBase::print_info(), libMesh::MeshBase::read(), and libMesh::MeshBase::write().
Referenced by libMesh::MeshBase::get_info(), libMesh::BoundaryInfo::sync(), libMesh::NameBasedIO::write(), libMesh::GMVIO::write_ascii_new_impl(), and libMesh::GMVIO::write_ascii_old_impl().
   { return _n_parts; }
processor_id_type libMesh::ParallelObject::n_processors () const inline inherited
Returns
The number of processors in the group.
Definition at line 93 of file parallel_object.h.
References libMesh::ParallelObject::_communicator, and libMesh::Parallel::Communicator::size().
Referenced by libMesh::ParmetisPartitioner::_do_repartition(), libMesh::BoundaryInfo::_find_id_maps(), libMesh::DistributedMesh::add_elem(), libMesh::DistributedMesh::add_node(), libMesh::LaplaceMeshSmoother::allgather_graph(), libMesh::FEMSystem::assembly(), libMesh::ParmetisPartitioner::assign_partitioning(), libMesh::AztecLinearSolver< T >::AztecLinearSolver(), libMesh::MeshCommunication::broadcast(), libMesh::BoundaryInfo::build_node_list_from_side_list(), libMesh::DistributedMesh::clear(), libMesh::Nemesis_IO_Helper::compute_border_node_ids(), libMesh::Nemesis_IO_Helper::construct_nemesis_filename(), libMesh::MeshTools::correct_node_proc_ids(), libMesh::UnstructuredMesh::create_pid_mesh(), libMesh::MeshTools::create_processor_bounding_box(), libMesh::DofMap::distribute_dofs(), libMesh::DofMap::distribute_local_dofs_node_major(), libMesh::DofMap::distribute_local_dofs_var_major(), libMesh::DistributedMesh::DistributedMesh(), libMesh::EnsightIO::EnsightIO(), libMesh::MeshCommunication::gather(), libMesh::MeshCommunication::gather_neighboring_elements(), libMesh::MeshBase::get_info(), libMesh::EquationSystems::get_solution(), libMesh::DistributedVector< T >::init(), libMesh::SystemSubsetBySubdomain::init(), libMesh::ParmetisPartitioner::initialize(), libMesh::Nemesis_IO_Helper::initialize(), libMesh::DistributedMesh::insert_elem(), libMesh::MeshTools::libmesh_assert_parallel_consistent_procids< Elem >(), libMesh::MeshTools::libmesh_assert_parallel_consistent_procids< Node >(), libMesh::MeshTools::libmesh_assert_topology_consistent_procids< Node >(), libMesh::MeshTools::libmesh_assert_valid_boundary_ids(), libMesh::MeshTools::libmesh_assert_valid_dof_ids(), libMesh::MeshTools::libmesh_assert_valid_neighbors(), libMesh::MeshTools::libmesh_assert_valid_refinement_flags(), libMesh::DofMap::local_variable_indices(), libMesh::MeshRefinement::make_coarsening_compatible(), libMesh::MeshBase::n_active_elem_on_proc(), libMesh::MeshBase::n_elem_on_proc(), libMesh::MeshBase::n_nodes_on_proc(), libMesh::SparsityPattern::Build::parallel_sync(), libMesh::Partitioner::partition(), libMesh::MeshBase::partition(), libMesh::Partitioner::partition_unpartitioned_elements(), libMesh::PetscLinearSolver< T >::PetscLinearSolver(), libMesh::System::point_gradient(), libMesh::System::point_hessian(), libMesh::System::point_value(), libMesh::SparseMatrix< T >::print(), libMesh::NameBasedIO::read(), libMesh::Nemesis_IO::read(), libMesh::CheckpointIO::read(), libMesh::CheckpointIO::read_connectivity(), libMesh::XdrIO::read_header(), libMesh::CheckpointIO::read_nodes(), libMesh::MeshCommunication::redistribute(), libMesh::DistributedMesh::renumber_dof_objects(), libMesh::Partitioner::repartition(), libMesh::MeshCommunication::send_coarse_ghosts(), libMesh::Partitioner::set_node_processor_ids(), libMesh::DofMap::set_nonlocal_dof_objects(), libMesh::Parallel::Sort< KeyType, IdxType >::sort(), libMesh::MeshRefinement::uniformly_coarsen(), libMesh::DistributedMesh::update_parallel_id_counts(), libMesh::GMVIO::write_binary(), libMesh::GMVIO::write_discontinuous_gmv(), libMesh::XdrIO::write_serialized_bcs_helper(), libMesh::XdrIO::write_serialized_connectivity(), libMesh::XdrIO::write_serialized_nodes(), and libMesh::XdrIO::write_serialized_nodesets().
   { return cast_int<processor_id_type>(_communicator.size()); }
dof_id_type libMesh::MeshBase::n_sub_elem () const inherited
Returns
The number of elements that will be written out in certain I/O formats.
For example, a 9-noded quadrilateral will be broken into 4 linear sub-elements for plotting purposes. Thus, for a mesh of 2 QUAD9 elements n_tecplot_elem() will return 8. Implemented in terms of element_iterators.
Definition at line 386 of file mesh_base.C.
References libMesh::MeshBase::elements_begin(), libMesh::MeshBase::elements_end(), and end.
Referenced by libMesh::MeshBase::n_active_local_elem().
 {
   dof_id_type ne=0;
   const_element_iterator       el  = this->elements_begin();
   const const_element_iterator end = this->elements_end();
   for (; el!=end; ++el)
     ne += (*el)->n_sub_elem();
   return ne;
 }
subdomain_id_type libMesh::MeshBase::n_subdomains () const inherited
Returns
The number of subdomains in the global mesh. Subdomains correspond to separate subsets of the mesh which could correspond e.g. to different materials in a solid mechanics application, or regions where different physical processes are important. The subdomain mapping is independent from the parallel decomposition.
Definition at line 336 of file mesh_base.C.
References libMesh::MeshBase::subdomain_ids().
Referenced by libMesh::MeshBase::get_info(), libMesh::MeshBase::ghosting_functors_end(), libMesh::XdrIO::write(), and libMesh::NameBasedIO::write_nodal_data().
 {
   // This requires an inspection on every processor
   parallel_object_only();
   std::set<subdomain_id_type> ids;
   this->subdomain_ids (ids);
   return cast_int<subdomain_id_type>(ids.size());
 }
dof_id_type libMesh::MeshBase::n_unpartitioned_elem () const inline inherited
Returns
The number of elements owned by no processor.
Definition at line 379 of file mesh_base.h.
References libMesh::DofObject::invalid_processor_id, libMesh::MeshBase::n_active_elem_on_proc(), and libMesh::MeshBase::n_elem_on_proc().
Referenced by libMesh::DistributedMesh::parallel_n_elem(), and libMesh::MeshBase::partition().
   { return this->n_elem_on_proc (DofObject::invalid_processor_id); }
dof_id_type libMesh::MeshBase::n_unpartitioned_nodes () const inline inherited
Returns
The number of nodes owned by no processor.
Definition at line 279 of file mesh_base.h.
References libMesh::DofObject::invalid_processor_id, libMesh::MeshBase::max_node_id(), and libMesh::MeshBase::n_nodes_on_proc().
Referenced by libMesh::DistributedMesh::parallel_n_nodes().
   { return this->n_nodes_on_proc (DofObject::invalid_processor_id); }
unique_id_type libMesh::MeshBase::next_unique_id () inline inherited
Returns
The next unique id to be used.
Definition at line 292 of file mesh_base.h.
References libMesh::MeshBase::_next_unique_id.
 { return _next_unique_id; }
virtual const Node& libMesh::MeshBase::node (const dof_id_type i) const inline virtual inherited
Returns
A constant reference (for reading only) to the node, which should be present in this processor's subset of the mesh data structure.
Deprecated:
Use the less confusingly-named node_ref() instead.
Definition at line 441 of file mesh_base.h.
References libMesh::MeshBase::node_ptr().
Referenced by libMesh::MeshBase::cache_elem_dims(), and libMesh::MeshTools::Modification::change_boundary_id().
   {
     libmesh_deprecated();
     return *this->node_ptr(i);
   }
virtual Node& libMesh::MeshBase::node (const dof_id_type i) inline virtual inherited
Returns
A reference to the node, which should be present in this processor's subset of the mesh data structure.
Deprecated:
Use the less confusingly-named node_ref() instead.
Definition at line 455 of file mesh_base.h.
References libMesh::MeshBase::node_ptr(), and libMesh::MeshBase::query_node_ptr().
   {
     libmesh_deprecated();
     return *this->node_ptr(i);
   }
const Node * libMesh::ReplicatedMesh::node_ptr (const dof_id_type i) const virtual inherited
Returns
A pointer to the node, which should be present in this processor's subset of the mesh data structure.
Implements libMesh::MeshBase.
Definition at line 186 of file replicated_mesh.C.
References libMesh::ReplicatedMesh::_nodes, and libMesh::ReplicatedMesh::n_nodes().
Referenced by libMesh::ReplicatedMesh::reserve_elem(), and libMesh::ReplicatedMesh::stitching_helper().
 {
   libmesh_assert_less (i, this->n_nodes());
   libmesh_assert(_nodes[i]);
   libmesh_assert_equal_to (_nodes[i]->id(), i); // This will change soon
   return _nodes[i];
 }
Node * libMesh::ReplicatedMesh::node_ptr (const dof_id_type i) virtual inherited
Returns
A writable pointer to the node, which should be present in this processor's subset of the mesh data structure.
Implements libMesh::MeshBase.
Definition at line 198 of file replicated_mesh.C.
References libMesh::ReplicatedMesh::_nodes, and libMesh::ReplicatedMesh::n_nodes().
 {
   libmesh_assert_less (i, this->n_nodes());
   libmesh_assert(_nodes[i]);
   libmesh_assert_equal_to (_nodes[i]->id(), i); // This will change soon
   return _nodes[i];
 }
virtual SimpleRange<node_iterator> libMesh::ReplicatedMesh::node_ptr_range () inline virtual inherited
Implements libMesh::MeshBase.
Definition at line 425 of file replicated_mesh.h.
References libMesh::ReplicatedMesh::nodes_begin(), and libMesh::ReplicatedMesh::nodes_end().
 { return {nodes_begin(), nodes_end()}; }
virtual SimpleRange<const_node_iterator> libMesh::ReplicatedMesh::node_ptr_range () const inline virtual inherited
Implements libMesh::MeshBase.
Definition at line 426 of file replicated_mesh.h.
References libMesh::ReplicatedMesh::active_nodes_begin(), libMesh::ReplicatedMesh::active_nodes_end(), libMesh::ReplicatedMesh::local_nodes_begin(), libMesh::ReplicatedMesh::local_nodes_end(), libMesh::ReplicatedMesh::nodes_begin(), and libMesh::ReplicatedMesh::nodes_end().
 { return {nodes_begin(), nodes_end()}; }
virtual const Node& libMesh::MeshBase::node_ref (const dof_id_type i) const inline virtual inherited
Returns
A constant reference (for reading only) to the node, which should be present in this processor's subset of the mesh data structure.
Definition at line 421 of file mesh_base.h.
References libMesh::MeshBase::node_ptr().
Referenced by libMesh::SyncNodalPositions::act_on_data(), libMesh::MeshTools::Generation::build_cube(), libMesh::InfElemBuilder::build_inf_elem(), libMesh::MeshCommunication::make_p_levels_parallel_consistent(), libMesh::ReplicatedMesh::point(), libMesh::DistributedMesh::point(), libMesh::Partitioner::set_node_processor_ids(), libMesh::LaplaceMeshSmoother::smooth(), libMesh::MeshTools::Modification::smooth(), and libMesh::ReplicatedMesh::stitching_helper().
{
     return *this->node_ptr(i);
   }
virtual Node& libMesh::MeshBase::node_ref (const dof_id_type i) inline virtual inherited
Returns
A reference to the node, which should be present in this processor's subset of the mesh data structure.
Definition at line 429 of file mesh_base.h.
References libMesh::MeshBase::node_ptr().
{
     return *this->node_ptr(i);
   }
virtual node_iterator libMesh::ReplicatedMesh::nodes_begin () virtual inherited
Node iterator accessor functions.
Implements libMesh::MeshBase.
Referenced by libMesh::ReplicatedMesh::active_local_element_ptr_range(), libMesh::ReplicatedMesh::node_ptr_range(), and libMesh::ReplicatedMesh::stitching_helper().
virtual const_node_iterator libMesh::ReplicatedMesh::nodes_begin () const virtual inherited
Implements libMesh::MeshBase.
virtual node_iterator libMesh::ReplicatedMesh::nodes_end () virtual inherited
Implements libMesh::MeshBase.
Referenced by libMesh::ReplicatedMesh::active_local_element_ptr_range(), libMesh::ReplicatedMesh::node_ptr_range(), and libMesh::ReplicatedMesh::stitching_helper().
virtual const_node_iterator libMesh::ReplicatedMesh::nodes_end () const virtual inherited
Implements libMesh::MeshBase.
virtual element_iterator libMesh::ReplicatedMesh::not_active_elements_begin () virtual inherited
Implements libMesh::MeshBase.
Referenced by libMesh::ReplicatedMesh::active_element_ptr_range().
virtual const_element_iterator libMesh::ReplicatedMesh::not_active_elements_begin () const virtual inherited
Implements libMesh::MeshBase.
virtual element_iterator libMesh::ReplicatedMesh::not_active_elements_end () virtual inherited
Implements libMesh::MeshBase.
Referenced by libMesh::ReplicatedMesh::active_element_ptr_range().
virtual const_element_iterator libMesh::ReplicatedMesh::not_active_elements_end () const virtual inherited
Implements libMesh::MeshBase.
virtual element_iterator libMesh::ReplicatedMesh::not_ancestor_elements_begin () virtual inherited
Implements libMesh::MeshBase.
Referenced by libMesh::ReplicatedMesh::active_element_ptr_range().
virtual const_element_iterator libMesh::ReplicatedMesh::not_ancestor_elements_begin () const virtual inherited
Implements libMesh::MeshBase.
virtual element_iterator libMesh::ReplicatedMesh::not_ancestor_elements_end () virtual inherited
Implements libMesh::MeshBase.
Referenced by libMesh::ReplicatedMesh::active_element_ptr_range().
virtual const_element_iterator libMesh::ReplicatedMesh::not_ancestor_elements_end () const virtual inherited
Implements libMesh::MeshBase.
virtual element_iterator libMesh::ReplicatedMesh::not_level_elements_begin (unsigned int level) virtual inherited
Implements libMesh::MeshBase.
Referenced by libMesh::ReplicatedMesh::active_local_element_ptr_range().
virtual const_element_iterator libMesh::ReplicatedMesh::not_level_elements_begin (unsigned int level) const virtual inherited
Implements libMesh::MeshBase.
virtual element_iterator libMesh::ReplicatedMesh::not_level_elements_end (unsigned int level) virtual inherited
Implements libMesh::MeshBase.
Referenced by libMesh::ReplicatedMesh::active_local_element_ptr_range().
virtual const_element_iterator libMesh::ReplicatedMesh::not_level_elements_end (unsigned int level) const virtual inherited
Implements libMesh::MeshBase.
virtual element_iterator libMesh::ReplicatedMesh::not_local_elements_begin () virtual inherited
Implements libMesh::MeshBase.
Referenced by libMesh::ReplicatedMesh::active_element_ptr_range().
virtual const_element_iterator libMesh::ReplicatedMesh::not_local_elements_begin () const virtual inherited
Implements libMesh::MeshBase.
virtual element_iterator libMesh::ReplicatedMesh::not_local_elements_end () virtual inherited
Implements libMesh::MeshBase.
Referenced by libMesh::ReplicatedMesh::active_element_ptr_range().
virtual const_element_iterator libMesh::ReplicatedMesh::not_local_elements_end () const virtual inherited
Implements libMesh::MeshBase.
virtual element_iterator libMesh::ReplicatedMesh::not_subactive_elements_begin () virtual inherited
Implements libMesh::MeshBase.
Referenced by libMesh::ReplicatedMesh::active_element_ptr_range().
virtual const_element_iterator libMesh::ReplicatedMesh::not_subactive_elements_begin () const virtual inherited
Implements libMesh::MeshBase.
virtual element_iterator libMesh::ReplicatedMesh::not_subactive_elements_end () virtual inherited
Implements libMesh::MeshBase.
Referenced by libMesh::ReplicatedMesh::active_element_ptr_range().
virtual const_element_iterator libMesh::ReplicatedMesh::not_subactive_elements_end () const virtual inherited
Implements libMesh::MeshBase.
unique_id_type libMesh::ReplicatedMesh::parallel_max_unique_id () const virtual inherited
Returns
A number greater than or equal to the maximum unique_id in the mesh.
Implements libMesh::MeshBase.
Definition at line 620 of file replicated_mesh.C.
References libMesh::MeshBase::_next_unique_id, libMesh::ParallelObject::comm(), and libMesh::Parallel::Communicator::max().
Referenced by libMesh::ReplicatedMesh::max_elem_id(), and libMesh::ReplicatedMesh::update_parallel_id_counts().
 {
   // This function must be run on all processors at once
   parallel_object_only();
   unique_id_type max_local = _next_unique_id;
   this->comm().max(max_local);
   return max_local;
 }
virtual dof_id_type libMesh::ReplicatedMesh::parallel_n_elem () const inline virtual inherited
Returns
The number of elements in the mesh.
The parallel_n_elem() function computes a parallel-synchronized value on distributed meshes, and so must be called in parallel only.
Implements libMesh::MeshBase.
Definition at line 123 of file replicated_mesh.h.
References libMesh::ReplicatedMesh::_elements, and libMesh::ReplicatedMesh::n_active_elem().
   { return cast_int<dof_id_type>(_elements.size()); }
virtual dof_id_type libMesh::ReplicatedMesh::parallel_n_nodes () const inline virtual inherited
Returns
The number of nodes in the mesh.
This function and others must be overridden in derived classes since the MeshBase class has no specific storage for nodes or elements. The parallel_n_nodes() function computes a parallel-synchronized value on distributed meshes, and so must be called in parallel only.
Implements libMesh::MeshBase.
Definition at line 111 of file replicated_mesh.h.
References libMesh::ReplicatedMesh::_nodes.
   { return cast_int<dof_id_type>(_nodes.size()); }
void libMesh::MeshBase::partition (const unsigned int n_parts) virtual inherited
Call the default partitioner (currently metis_partition()).
Definition at line 464 of file mesh_base.C.
References libMesh::MeshBase::is_serial(), libMesh::MeshBase::n_unpartitioned_elem(), libMesh::MeshBase::partitioner(), libMesh::MeshBase::recalculate_n_partitions(), libMesh::Partitioner::set_node_processor_ids(), libMesh::MeshBase::skip_partitioning(), and libMesh::MeshBase::update_post_partitioning().
Referenced by libMesh::split_mesh().
 {
   // If we get here and we have unpartitioned elements, we need that
   // fixed.
   if (this->n_unpartitioned_elem() > 0)
     {
       libmesh_assert (partitioner().get());
       libmesh_assert (this->is_serial());
       partitioner()->partition (*this, n_parts);
     }
   // NULL partitioner means don't repartition
   // Non-serial meshes may not be ready for repartitioning here.
   else if (!skip_partitioning() && partitioner().get())
     {
       partitioner()->partition (*this, n_parts);
     }
   else
     {
       // Adaptive coarsening may have "orphaned" nodes on processors
       // whose elements no longer share them.  We need to check for
       // and possibly fix that.
       Partitioner::set_node_processor_ids(*this);
       // Make sure locally cached partition count
       this->recalculate_n_partitions();
       // Make sure any other locally cached data is correct
       this->update_post_partitioning();
     }
 }
void libMesh::MeshBase::partition () inline inherited
Definition at line 728 of file mesh_base.h.
References libMesh::ParallelObject::n_processors().
Referenced by libMesh::MeshBase::prepare_for_use(), and libMesh::MeshBase::query_elem().
   { this->partition(this->n_processors()); }
virtual std::unique_ptr<Partitioner>& libMesh::MeshBase::partitioner () inline virtual inherited
A partitioner to use at each prepare_for_use()
Definition at line 113 of file mesh_base.h.
References libMesh::MeshBase::_partitioner.
Referenced by libMesh::UniformRefinementEstimator::_estimate_error(), libMesh::AdjointRefinementEstimator::estimate_error(), libMesh::MeshBase::partition(), and libMesh::BoundaryInfo::sync().
 { return _partitioner; }
virtual element_iterator libMesh::ReplicatedMesh::pid_elements_begin (processor_id_type proc_id) virtual inherited
Iterate over all elements with a specified processor id.
Implements libMesh::MeshBase.
Referenced by libMesh::ReplicatedMesh::active_local_element_ptr_range().
virtual const_element_iterator libMesh::ReplicatedMesh::pid_elements_begin (processor_id_type proc_id) const virtual inherited
Implements libMesh::MeshBase.
virtual element_iterator libMesh::ReplicatedMesh::pid_elements_end (processor_id_type proc_id) virtual inherited
Implements libMesh::MeshBase.
Referenced by libMesh::ReplicatedMesh::active_local_element_ptr_range().
virtual const_element_iterator libMesh::ReplicatedMesh::pid_elements_end (processor_id_type proc_id) const virtual inherited
Implements libMesh::MeshBase.
virtual node_iterator libMesh::ReplicatedMesh::pid_nodes_begin (processor_id_type proc_id) virtual inherited
Iterate over nodes with processor_id() == proc_id
Implements libMesh::MeshBase.
Referenced by libMesh::ReplicatedMesh::local_node_ptr_range().
virtual const_node_iterator libMesh::ReplicatedMesh::pid_nodes_begin (processor_id_type proc_id) const virtual inherited
Implements libMesh::MeshBase.
virtual node_iterator libMesh::ReplicatedMesh::pid_nodes_end (processor_id_type proc_id) virtual inherited
Implements libMesh::MeshBase.
Referenced by libMesh::ReplicatedMesh::local_node_ptr_range().
virtual const_node_iterator libMesh::ReplicatedMesh::pid_nodes_end (processor_id_type proc_id) const virtual inherited
Implements libMesh::MeshBase.
const Point & libMesh::ReplicatedMesh::point (const dof_id_type i) const virtual inherited
Returns
A constant reference (for reading only) to the point, which should be present in this processor's subset of the mesh data structure.
Implements libMesh::MeshBase.
Definition at line 178 of file replicated_mesh.C.
References libMesh::MeshBase::node_ref().
Referenced by libMesh::ReplicatedMesh::reserve_elem(), and libMesh::ReplicatedMesh::stitching_helper().
 {
   return this->node_ref(i);
 }
const PointLocatorBase & libMesh::MeshBase::point_locator () const inherited
Returns
A pointer to a PointLocatorBase object for this mesh, constructing a master PointLocator first if necessary.
Deprecated:
This should never be used in threaded or non-parallel_only code.
Definition at line 519 of file mesh_base.C.
References libMesh::MeshBase::_point_locator, libMesh::PointLocatorBase::build(), libMesh::Threads::in_threads, libmesh_nullptr, and libMesh::TREE_ELEMENTS.
 {
   libmesh_deprecated();
   if (_point_locator.get() == libmesh_nullptr)
     {
       // PointLocator construction may not be safe within threads
       libmesh_assert(!Threads::in_threads);
       _point_locator = PointLocatorBase::build(TREE_ELEMENTS, *this);
     }
   return *_point_locator;
 }
void libMesh::MeshBase::prepare_for_use (const bool skip_renumber_nodes_and_elements = false, const bool skip_find_neighbors = false) inherited
Prepare a newly created (or read) mesh for use. This involves 4 steps: 1.) call find_neighbors() 2.) call partition() 3.) call renumber_nodes_and_elements() 4.) call cache_elem_dims()
The argument to skip renumbering is now deprecated - to prevent a mesh from being renumbered, set allow_renumbering(false).
If this is a distributed mesh, local copies of remote elements will be deleted here - to keep those elements replicated during preparation, set allow_remote_element_removal(false).
Definition at line 176 of file mesh_base.C.
References libMesh::MeshBase::_allow_remote_element_removal, libMesh::MeshBase::_is_prepared, libMesh::MeshBase::_skip_renumber_nodes_and_elements, libMesh::MeshBase::allow_renumbering(), libMesh::MeshBase::cache_elem_dims(), libMesh::MeshBase::clear_point_locator(), libMesh::ParallelObject::comm(), libMesh::MeshBase::delete_remote_elements(), libMesh::MeshBase::detect_interior_parents(), libMesh::MeshBase::find_neighbors(), libMesh::MeshBase::ghosting_functors_begin(), libMesh::MeshBase::ghosting_functors_end(), libMesh::MeshBase::is_serial(), libMesh::MeshTools::libmesh_assert_valid_boundary_ids(), libMesh::MeshTools::libmesh_assert_valid_unique_ids(), libMesh::GhostingFunctor::mesh_reinit(), libMesh::MeshBase::partition(), libMesh::MeshBase::renumber_nodes_and_elements(), libMesh::MeshBase::update_parallel_id_counts(), and libMesh::Parallel::verify().
Referenced by libMesh::UnstructuredMesh::all_first_order(), libMesh::UnstructuredMesh::all_second_order(), libMesh::MeshTools::Subdivision::all_subdivision(), libMesh::MeshTools::Modification::all_tri(), libMesh::MeshTools::Generation::build_cube(), libMesh::MeshTools::Generation::build_extrusion(), libMesh::InfElemBuilder::build_inf_elem(), libMesh::MeshTools::Generation::build_sphere(), libMesh::MeshRefinement::coarsen_elements(), libMesh::UnstructuredMesh::copy_nodes_and_elements(), libMesh::UnstructuredMesh::create_submesh(), libMesh::MeshTools::Modification::flatten(), libMesh::MeshTools::Subdivision::prepare_subdivision_mesh(), libMesh::MeshBase::query_elem(), libMesh::GMVIO::read(), libMesh::UnstructuredMesh::read(), libMesh::MeshRefinement::refine_and_coarsen_elements(), libMesh::MeshRefinement::refine_elements(), libMesh::ReplicatedMesh::stitching_helper(), libMesh::BoundaryInfo::sync(), libMesh::TriangleInterface::triangulate(), libMesh::MeshRefinement::uniformly_coarsen(), and libMesh::MeshRefinement::uniformly_refine().
 {
   LOG_SCOPE("prepare_for_use()", "MeshBase");
   parallel_object_only();
   libmesh_assert(this->comm().verify(this->is_serial()));
   // A distributed mesh may have processors with no elements (or
   // processors with no elements of higher dimension, if we ever
   // support mixed-dimension meshes), but we want consistent
   // mesh_dimension anyways.
   //
   // cache_elem_dims() should get the elem_dimensions() and
   // mesh_dimension() correct later, and we don't need it earlier.
   // Renumber the nodes and elements so that they in contiguous
   // blocks.  By default, _skip_renumber_nodes_and_elements is false.
   //
   // We may currently change that by passing
   // skip_renumber_nodes_and_elements==true to this function, but we
   // should use the allow_renumbering() accessor instead.
   //
   // Instances where you if prepare_for_use() should not renumber the nodes
   // and elements include reading in e.g. an xda/r or gmv file. In
   // this case, the ordering of the nodes may depend on an accompanying
   // solution, and the node ordering cannot be changed.
   if (skip_renumber_nodes_and_elements)
     {
       libmesh_deprecated();
       this->allow_renumbering(false);
     }
   // Mesh modification operations might not leave us with consistent
   // id counts, but our partitioner might need that consistency.
   if (!_skip_renumber_nodes_and_elements)
     this->renumber_nodes_and_elements();
   else
     this->update_parallel_id_counts();
   // Let all the elements find their neighbors
   if (!skip_find_neighbors)
     this->find_neighbors();
   // The user may have set boundary conditions.  We require that the
   // boundary conditions were set consistently.  Because we examine
   // neighbors when evaluating non-raw boundary condition IDs, this
   // assert is only valid when our neighbor links are in place.
 #ifdef DEBUG
   MeshTools::libmesh_assert_valid_boundary_ids(*this);
 #endif
   // Search the mesh for all the dimensions of the elements
   // and cache them.
   this->cache_elem_dims();
   // Search the mesh for elements that have a neighboring element
   // of dim+1 and set that element as the interior parent
   this->detect_interior_parents();
   // Fix up node unique ids in case mesh generation code didn't take
   // exceptional care to do so.
   //  MeshCommunication().make_node_unique_ids_parallel_consistent(*this);
   // We're going to still require that mesh generation code gets
   // element unique ids consistent.
 #if defined(DEBUG) && defined(LIBMESH_ENABLE_UNIQUE_ID)
   MeshTools::libmesh_assert_valid_unique_ids(*this);
 #endif
   // Reset our PointLocator.  Any old locator is invalidated any time
   // the elements in the underlying elements in the mesh have changed,
   // so we clear it here.
   this->clear_point_locator();
   // Allow our GhostingFunctor objects to reinit if necessary.
   // Do this before partitioning and redistributing, and before
   // deleting remote elements.
   std::set<GhostingFunctor *>::iterator        gf_it = this->ghosting_functors_begin();
   const std::set<GhostingFunctor *>::iterator gf_end = this->ghosting_functors_end();
   for (; gf_it != gf_end; ++gf_it)
     {
       GhostingFunctor * gf = *gf_it;
       libmesh_assert(gf);
       gf->mesh_reinit();
     }
   // Partition the mesh.
   this->partition();
   // If we're using DistributedMesh, we'll probably want it
   // parallelized.
   if (this->_allow_remote_element_removal)
     this->delete_remote_elements();
   if (!_skip_renumber_nodes_and_elements)
     this->renumber_nodes_and_elements();
   // The mesh is now prepared for use.
   _is_prepared = true;
 #if defined(DEBUG) && defined(LIBMESH_ENABLE_UNIQUE_ID)
   MeshTools::libmesh_assert_valid_boundary_ids(*this);
   MeshTools::libmesh_assert_valid_unique_ids(*this);
 #endif
 }
void libMesh::MeshBase::print_info (std::ostream & os = libMesh::out) const inherited
Prints relevant information about the mesh.
Definition at line 450 of file mesh_base.C.
References libMesh::MeshBase::get_info().
Referenced by libMesh::InfElemBuilder::build_inf_elem(), libMesh::MeshBase::n_partitions(), and libMesh::operator<<().
 {
   os << this->get_info()
      << std::endl;
 }
processor_id_type libMesh::ParallelObject::processor_id () const inline inherited
Returns
The rank of this processor in the group.
Definition at line 99 of file parallel_object.h.
References libMesh::ParallelObject::_communicator, and libMesh::Parallel::Communicator::rank().
Referenced by libMesh::BoundaryInfo::_find_id_maps(), libMesh::EquationSystems::_read_impl(), libMesh::DistributedMesh::add_elem(), libMesh::BoundaryInfo::add_elements(), libMesh::DofMap::add_neighbors_to_send_list(), libMesh::DistributedMesh::add_node(), libMesh::MeshRefinement::add_node(), libMesh::MeshTools::Modification::all_tri(), libMesh::FEMSystem::assembly(), libMesh::ParmetisPartitioner::assign_partitioning(), libMesh::MeshCommunication::broadcast(), libMesh::EquationSystems::build_discontinuous_solution_vector(), libMesh::Nemesis_IO_Helper::build_element_and_node_maps(), libMesh::ParmetisPartitioner::build_graph(), libMesh::InfElemBuilder::build_inf_elem(), libMesh::BoundaryInfo::build_node_list_from_side_list(), libMesh::DofMap::build_sparsity(), libMesh::DistributedMesh::clear(), libMesh::ExodusII_IO_Helper::close(), libMesh::Nemesis_IO_Helper::compute_border_node_ids(), libMesh::Nemesis_IO_Helper::compute_communication_map_parameters(), libMesh::Nemesis_IO_Helper::compute_internal_and_border_elems_and_internal_nodes(), libMesh::Nemesis_IO_Helper::compute_node_communication_maps(), libMesh::Nemesis_IO_Helper::compute_num_global_elem_blocks(), libMesh::Nemesis_IO_Helper::compute_num_global_nodesets(), libMesh::Nemesis_IO_Helper::compute_num_global_sidesets(), libMesh::Nemesis_IO_Helper::construct_nemesis_filename(), libMesh::MeshTools::correct_node_proc_ids(), libMesh::ExodusII_IO_Helper::create(), libMesh::DistributedMesh::delete_elem(), libMesh::DistributedMesh::delete_node(), libMesh::MeshCommunication::delete_remote_elements(), libMesh::DofMap::distribute_dofs(), libMesh::DofMap::distribute_local_dofs_node_major(), libMesh::DofMap::distribute_local_dofs_var_major(), libMesh::DistributedMesh::DistributedMesh(), libMesh::EnsightIO::EnsightIO(), libMesh::MeshFunction::find_element(), libMesh::MeshFunction::find_elements(), libMesh::UnstructuredMesh::find_neighbors(), libMesh::MeshCommunication::gather(), libMesh::MeshCommunication::gather_neighboring_elements(), libMesh::Nemesis_IO_Helper::get_cmap_params(), libMesh::Nemesis_IO_Helper::get_eb_info_global(), libMesh::Nemesis_IO_Helper::get_elem_cmap(), libMesh::Nemesis_IO_Helper::get_elem_map(), libMesh::MeshBase::get_info(), libMesh::DofMap::get_info(), libMesh::Nemesis_IO_Helper::get_init_global(), libMesh::Nemesis_IO_Helper::get_init_info(), libMesh::Nemesis_IO_Helper::get_loadbal_param(), libMesh::Nemesis_IO_Helper::get_node_cmap(), libMesh::Nemesis_IO_Helper::get_node_map(), libMesh::Nemesis_IO_Helper::get_ns_param_global(), libMesh::EquationSystems::get_solution(), libMesh::Nemesis_IO_Helper::get_ss_param_global(), libMesh::SparsityPattern::Build::handle_vi_vj(), libMesh::DistributedVector< T >::init(), libMesh::SystemSubsetBySubdomain::init(), libMesh::ParmetisPartitioner::initialize(), libMesh::ExodusII_IO_Helper::initialize(), libMesh::ExodusII_IO_Helper::initialize_element_variables(), libMesh::ExodusII_IO_Helper::initialize_global_variables(), libMesh::ExodusII_IO_Helper::initialize_nodal_variables(), libMesh::DistributedMesh::insert_elem(), libMesh::DofMap::is_evaluable(), libMesh::SparsityPattern::Build::join(), libMesh::MeshTools::libmesh_assert_parallel_consistent_procids< Elem >(), libMesh::MeshTools::libmesh_assert_parallel_consistent_procids< Node >(), libMesh::MeshTools::libmesh_assert_valid_neighbors(), libMesh::DistributedMesh::libmesh_assert_valid_parallel_object_ids(), libMesh::DofMap::local_variable_indices(), libMesh::MeshRefinement::make_coarsening_compatible(), libMesh::MeshBase::n_active_local_elem(), libMesh::BoundaryInfo::n_boundary_conds(), libMesh::BoundaryInfo::n_edge_conds(), libMesh::System::n_local_dofs(), libMesh::MeshBase::n_local_elem(), libMesh::MeshBase::n_local_nodes(), libMesh::BoundaryInfo::n_nodeset_conds(), libMesh::BoundaryInfo::n_shellface_conds(), libMesh::WeightedPatchRecoveryErrorEstimator::EstimateError::operator()(), libMesh::SparsityPattern::Build::operator()(), libMesh::PatchRecoveryErrorEstimator::EstimateError::operator()(), libMesh::SparsityPattern::Build::parallel_sync(), libMesh::MetisPartitioner::partition_range(), libMesh::System::point_gradient(), libMesh::System::point_hessian(), libMesh::System::point_value(), libMesh::SparseMatrix< T >::print(), libMesh::NumericVector< T >::print_global(), libMesh::Nemesis_IO_Helper::put_cmap_params(), libMesh::Nemesis_IO_Helper::put_elem_cmap(), libMesh::Nemesis_IO_Helper::put_elem_map(), libMesh::Nemesis_IO_Helper::put_loadbal_param(), libMesh::Nemesis_IO_Helper::put_node_cmap(), libMesh::Nemesis_IO_Helper::put_node_map(), libMesh::NameBasedIO::read(), libMesh::Nemesis_IO::read(), libMesh::XdrIO::read(), libMesh::CheckpointIO::read(), libMesh::ExodusII_IO_Helper::read_elem_num_map(), libMesh::ExodusII_IO_Helper::read_global_values(), libMesh::CheckpointIO::read_header(), libMesh::XdrIO::read_header(), libMesh::ExodusII_IO_Helper::read_node_num_map(), libMesh::XdrIO::read_serialized_bc_names(), libMesh::XdrIO::read_serialized_bcs_helper(), libMesh::XdrIO::read_serialized_connectivity(), libMesh::XdrIO::read_serialized_nodes(), libMesh::XdrIO::read_serialized_nodesets(), libMesh::XdrIO::read_serialized_subdomain_names(), libMesh::MeshCommunication::redistribute(), libMesh::DistributedMesh::renumber_dof_objects(), libMesh::CheckpointIO::select_split_config(), libMesh::MeshCommunication::send_coarse_ghosts(), libMesh::Partitioner::set_node_processor_ids(), libMesh::DofMap::set_nonlocal_dof_objects(), libMesh::LaplaceMeshSmoother::smooth(), libMesh::MeshTools::total_weight(), libMesh::MeshRefinement::uniformly_coarsen(), libMesh::Parallel::Packing< Node * >::unpack(), libMesh::Parallel::Packing< Elem * >::unpack(), libMesh::DistributedMesh::update_parallel_id_counts(), libMesh::MeshTools::weight(), libMesh::NameBasedIO::write(), libMesh::XdrIO::write(), libMesh::CheckpointIO::write(), libMesh::EquationSystems::write(), libMesh::GMVIO::write_discontinuous_gmv(), libMesh::ExodusII_IO::write_element_data(), libMesh::ExodusII_IO_Helper::write_element_values(), libMesh::ExodusII_IO_Helper::write_elements(), libMesh::ExodusII_IO::write_global_data(), libMesh::ExodusII_IO_Helper::write_global_values(), libMesh::ExodusII_IO::write_information_records(), libMesh::ExodusII_IO_Helper::write_information_records(), libMesh::ExodusII_IO_Helper::write_nodal_coordinates(), libMesh::UCDIO::write_nodal_data(), libMesh::ExodusII_IO::write_nodal_data(), libMesh::ExodusII_IO::write_nodal_data_discontinuous(), libMesh::ExodusII_IO_Helper::write_nodal_values(), libMesh::Nemesis_IO_Helper::write_nodesets(), libMesh::ExodusII_IO_Helper::write_nodesets(), libMesh::XdrIO::write_serialized_bc_names(), libMesh::XdrIO::write_serialized_bcs_helper(), libMesh::XdrIO::write_serialized_connectivity(), libMesh::XdrIO::write_serialized_nodes(), libMesh::XdrIO::write_serialized_nodesets(), libMesh::XdrIO::write_serialized_subdomain_names(), libMesh::Nemesis_IO_Helper::write_sidesets(), libMesh::ExodusII_IO_Helper::write_sidesets(), libMesh::ExodusII_IO::write_timestep(), libMesh::ExodusII_IO_Helper::write_timestep(), and libMesh::ExodusII_IO::write_timestep_discontinuous().
   { return cast_int<processor_id_type>(_communicator.rank()); }
virtual const Elem* libMesh::MeshBase::query_elem (const dof_id_type i) const inline virtual inherited
Returns
A pointer to the element, or NULL if no such element exists in this processor's mesh data structure.
Deprecated:
Use the less confusingly-named query_elem_ptr() instead.
Definition at line 565 of file mesh_base.h.
References libMesh::MeshBase::query_elem_ptr().
   {
     libmesh_deprecated();
     return this->query_elem_ptr(i);
   }
virtual Elem* libMesh::MeshBase::query_elem (const dof_id_type i) inline virtual inherited
Returns
A writable pointer to the element, or NULL if no such element exists in this processor's mesh data structure.
Deprecated:
Use the less confusingly-named query_elem_ptr() instead.
Definition at line 579 of file mesh_base.h.
References libMesh::MeshBase::add_elem(), libMesh::MeshBase::add_node(), libMesh::MeshBase::add_point(), libMesh::MeshBase::contract(), libMesh::MeshBase::delete_elem(), libMesh::MeshBase::delete_node(), libMesh::MeshBase::find_neighbors(), libMesh::MeshBase::fix_broken_node_and_element_numbering(), libMesh::MeshBase::insert_elem(), libMesh::MeshBase::insert_node(), libMesh::DofObject::invalid_id, libMesh::DofObject::invalid_processor_id, libMesh::MeshBase::partition(), libMesh::MeshBase::prepare_for_use(), libMesh::MeshBase::query_elem_ptr(), libMesh::MeshBase::renumber_elem(), libMesh::MeshBase::renumber_node(), and libMesh::MeshBase::renumber_nodes_and_elements().
   {
     libmesh_deprecated();
     return this->query_elem_ptr(i);
   }
const Elem * libMesh::ReplicatedMesh::query_elem_ptr (const dof_id_type i) const virtual inherited
Returns
A pointer to the element, or NULL if no such element exists in this processor's mesh data structure.
Implements libMesh::MeshBase.
Definition at line 260 of file replicated_mesh.C.
References libMesh::ReplicatedMesh::_elements, libmesh_nullptr, and libMesh::ReplicatedMesh::n_elem().
Referenced by libMesh::ReplicatedMesh::reserve_elem().
 {
   if (i >= this->n_elem())
     return libmesh_nullptr;
   libmesh_assert (_elements[i] == libmesh_nullptr ||
                   _elements[i]->id() == i); // This will change soon
   return _elements[i];
 }
Elem * libMesh::ReplicatedMesh::query_elem_ptr (const dof_id_type i) virtual inherited
Returns
A writable pointer to the element, or NULL if no such element exists in this processor's mesh data structure.
Implements libMesh::MeshBase.
Definition at line 273 of file replicated_mesh.C.
References libMesh::ReplicatedMesh::_elements, libmesh_nullptr, and libMesh::ReplicatedMesh::n_elem().
 {
   if (i >= this->n_elem())
     return libmesh_nullptr;
   libmesh_assert (_elements[i] == libmesh_nullptr ||
                   _elements[i]->id() == i); // This will change soon
   return _elements[i];
 }
const Node * libMesh::ReplicatedMesh::query_node_ptr (const dof_id_type i) const virtual inherited
Returns
A pointer to the node, or NULL if no such node exists in this processor's mesh data structure.
Implements libMesh::MeshBase.
Definition at line 210 of file replicated_mesh.C.
References libMesh::ReplicatedMesh::_nodes, libmesh_nullptr, and libMesh::ReplicatedMesh::n_nodes().
Referenced by libMesh::ReplicatedMesh::reserve_elem().
 {
   if (i >= this->n_nodes())
     return libmesh_nullptr;
   libmesh_assert (_nodes[i] == libmesh_nullptr ||
                   _nodes[i]->id() == i); // This will change soon
   return _nodes[i];
 }
Node * libMesh::ReplicatedMesh::query_node_ptr (const dof_id_type i) virtual inherited
Returns
A writable pointer to the node, or NULL if no such node exists in this processor's mesh data structure.
Implements libMesh::MeshBase.
Definition at line 223 of file replicated_mesh.C.
References libMesh::ReplicatedMesh::_nodes, libmesh_nullptr, and libMesh::ReplicatedMesh::n_nodes().
 {
   if (i >= this->n_nodes())
     return libmesh_nullptr;
   libmesh_assert (_nodes[i] == libmesh_nullptr ||
                   _nodes[i]->id() == i); // This will change soon
   return _nodes[i];
 }
void libMesh::UnstructuredMesh::read (const std::string & name, void * mesh_data = libmesh_nullptr, bool skip_renumber_nodes_and_elements = false, bool skip_find_neighbors = false) virtual inherited
Reads the file specified by name. Attempts to figure out the proper method by the file extension. This is now the only way to read a mesh. The UnstructuredMesh then initializes its data structures and is ready for use.
The skip_renumber_nodes_and_elements argument is now deprecated - to disallow renumbering, set MeshBase::allow_renumbering(false).
Set skip_find_neighbors=true to skip the find-neighbors operation during prepare_for_use. This operation isn't always necessary and it can be time-consuming, which is why we provide an option to skip it.
Implements libMesh::MeshBase.
Definition at line 605 of file unstructured_mesh.C.
References libMesh::MeshBase::allow_renumbering(), libMesh::MeshBase::prepare_for_use(), and libMesh::NameBasedIO::read().
 {
   // Set the skip_renumber_nodes_and_elements flag on all processors
   // if necessary.
   // This ensures that renumber_nodes_and_elements is *not* called
   // during prepare_for_use() for certain types of mesh files.
   // This is required in cases where there is an associated solution
   // file which expects a certain ordering of the nodes.
   if (name.rfind(".gmv") + 4 == name.size())
     this->allow_renumbering(false);
   NameBasedIO(*this).read(name);
   if (skip_renumber_nodes_and_elements)
     {
       // Use MeshBase::allow_renumbering() yourself instead.
       libmesh_deprecated();
       this->allow_renumbering(false);
     }
   // Done reading the mesh.  Now prepare it for use.
   this->prepare_for_use(/*skip_renumber (deprecated)*/ false,
                         skip_find_neighbors);
 }
unsigned int libMesh::MeshBase::recalculate_n_partitions () inherited
In a few (very rare) cases, the user may have manually tagged the elements with specific processor IDs by hand, without using a partitioner. In this case, the Mesh will not know that the total number of partitions, _n_parts, has changed, unless you call this function. This is an O(N active elements) calculation. The return value is the number of partitions, and _n_parts is also set by this function.
Definition at line 495 of file mesh_base.C.
References libMesh::MeshBase::_n_parts, libMesh::MeshBase::active_local_elements_begin(), libMesh::MeshBase::active_local_elements_end(), libMesh::ParallelObject::comm(), end, std::max(), and libMesh::Parallel::Communicator::max().
Referenced by libMesh::MeshBase::partition().
 {
   // This requires an inspection on every processor
   parallel_object_only();
   const_element_iterator el  = this->active_local_elements_begin();
   const_element_iterator end = this->active_local_elements_end();
   unsigned int max_proc_id=0;
   for (; el!=end; ++el)
     max_proc_id = std::max(max_proc_id, static_cast<unsigned int>((*el)->processor_id()));
   // The number of partitions is one more than the max processor ID.
   _n_parts = max_proc_id+1;
   this->comm().max(_n_parts);
   return _n_parts;
 }
virtual void libMesh::MeshBase::redistribute () inline virtual inherited
Redistribute elements between processors. This gets called automatically by the Partitioner, and is a no-op in the case of a ReplicatedMesh or serialized DistributedMesh
Reimplemented in libMesh::DistributedMesh.
Definition at line 736 of file mesh_base.h.
Referenced by libMesh::Partitioner::partition().
 {}
void libMesh::MeshBase::remove_ghosting_functor (GhostingFunctor & ghosting_functor) inherited
Removes a functor which was previously added to the set of ghosting functors.
Definition at line 307 of file mesh_base.C.
References libMesh::MeshBase::_ghosting_functors.
Referenced by libMesh::MeshBase::add_ghosting_functor(), libMesh::DofMap::clear(), libMesh::DofMap::remove_algebraic_ghosting_functor(), libMesh::DofMap::remove_coupling_functor(), and libMesh::DofMap::~DofMap().
 {
   // We should only be trying to remove ghosting functors we actually
   // have
   libmesh_assert(_ghosting_functors.count(&ghosting_functor));
   _ghosting_functors.erase(&ghosting_functor);
 }
void libMesh::ReplicatedMesh::renumber_elem (dof_id_type old_id, dof_id_type new_id) virtual inherited
Changes the id of element old_id, both by changing elem(old_id)->id() and by moving elem(old_id) in the mesh's internal container. No element with the id new_id should already exist.
Implements libMesh::MeshBase.
Definition at line 388 of file replicated_mesh.C.
References libMesh::ReplicatedMesh::_elements, libmesh_nullptr, and libMesh::DofObject::set_id().
Referenced by libMesh::ReplicatedMesh::reserve_elem().
 {
   // This doesn't get used in serial yet
   Elem * el = _elements[old_id];
   libmesh_assert (el);
   el->set_id(new_id);
   libmesh_assert (!_elements[new_id]);
   _elements[new_id] = el;
   _elements[old_id] = libmesh_nullptr;
 }
void libMesh::ReplicatedMesh::renumber_node (dof_id_type old_id, dof_id_type new_id) virtual inherited
Changes the id of node old_id, both by changing node(old_id)->id() and by moving node(old_id) in the mesh's internal container. No element with the id new_id should already exist.
Implements libMesh::MeshBase.
Definition at line 558 of file replicated_mesh.C.
References libMesh::ReplicatedMesh::_nodes, libmesh_nullptr, and libMesh::DofObject::set_id().
Referenced by libMesh::ReplicatedMesh::reserve_elem().
 {
   // This doesn't get used in serial yet
   Node * nd = _nodes[old_id];
   libmesh_assert (nd);
   nd->set_id(new_id);
   libmesh_assert (!_nodes[new_id]);
   _nodes[new_id] = nd;
   _nodes[old_id] = libmesh_nullptr;
 }
void libMesh::ReplicatedMesh::renumber_nodes_and_elements () virtual inherited
Remove NULL elements from arrays
Implements libMesh::MeshBase.
Definition at line 633 of file replicated_mesh.C.
References libMesh::ReplicatedMesh::_elements, libMesh::ReplicatedMesh::_nodes, libMesh::MeshBase::_skip_renumber_nodes_and_elements, end, libMesh::MeshBase::get_boundary_info(), libmesh_nullptr, libMesh::Elem::node_ref_range(), libMesh::BoundaryInfo::remove(), libMesh::DofObject::set_id(), swap(), and libMesh::ReplicatedMesh::update_parallel_id_counts().
Referenced by libMesh::ReplicatedMesh::clone().
 {
   LOG_SCOPE("renumber_nodes_and_elem()", "Mesh");
   // node and element id counters
   dof_id_type next_free_elem = 0;
   dof_id_type next_free_node = 0;
   // Will hold the set of nodes that are currently connected to elements
   std::unordered_set<Node *> connected_nodes;
   // Loop over the elements.  Note that there may
   // be NULLs in the _elements vector from the coarsening
   // process.  Pack the elements in to a contiguous array
   // and then trim any excess.
   {
     std::vector<Elem *>::iterator in        = _elements.begin();
     std::vector<Elem *>::iterator out_iter  = _elements.begin();
     const std::vector<Elem *>::iterator end = _elements.end();
     for (; in != end; ++in)
       if (*in != libmesh_nullptr)
         {
           Elem * el = *in;
           *out_iter = *in;
           ++out_iter;
           // Increment the element counter
           el->set_id (next_free_elem++);
           if (_skip_renumber_nodes_and_elements)
             {
               // Add this elements nodes to the connected list
               for (auto & n : el->node_ref_range())
                 connected_nodes.insert(&n);
             }
           else  // We DO want node renumbering
             {
               // Loop over this element's nodes.  Number them,
               // if they have not been numbered already.  Also,
               // position them in the _nodes vector so that they
               // are packed contiguously from the beginning.
               for (auto & n : el->node_ref_range())
                 if (n.id() == next_free_node)    // don't need to process
                   next_free_node++;                      // [(src == dst) below]
                 else if (n.id() > next_free_node) // need to process
                   {
                     // The source and destination indices
                     // for this node
                     const dof_id_type src_idx = n.id();
                     const dof_id_type dst_idx = next_free_node++;
                     // ensure we want to swap a valid nodes
                     libmesh_assert(_nodes[src_idx]);
                     // Swap the source and destination nodes
                     std::swap(_nodes[src_idx],
                               _nodes[dst_idx] );
                     // Set proper indices where that makes sense
                     if (_nodes[src_idx] != libmesh_nullptr)
                       _nodes[src_idx]->set_id (src_idx);
                     _nodes[dst_idx]->set_id (dst_idx);
                   }
             }
         }
     // Erase any additional storage. These elements have been
     // copied into NULL voids by the procedure above, and are
     // thus repeated and unnecessary.
     _elements.erase (out_iter, end);
   }
   if (_skip_renumber_nodes_and_elements)
     {
       // Loop over the nodes.  Note that there may
       // be NULLs in the _nodes vector from the coarsening
       // process.  Pack the nodes in to a contiguous array
       // and then trim any excess.
       std::vector<Node *>::iterator in        = _nodes.begin();
       std::vector<Node *>::iterator out_iter  = _nodes.begin();
       const std::vector<Node *>::iterator end = _nodes.end();
       for (; in != end; ++in)
         if (*in != libmesh_nullptr)
           {
             // This is a reference so that if we change the pointer it will change in the vector
             Node * & nd = *in;
             // If this node is still connected to an elem, put it in the list
             if (connected_nodes.find(nd) != connected_nodes.end())
               {
                 *out_iter = nd;
                 ++out_iter;
                 // Increment the node counter
                 nd->set_id (next_free_node++);
               }
             else // This node is orphaned, delete it!
               {
                 this->get_boundary_info().remove (nd);
                 // delete the node
                 delete nd;
                 nd = libmesh_nullptr;
               }
           }
       // Erase any additional storage.  Whatever was
       _nodes.erase (out_iter, end);
     }
   else // We really DO want node renumbering
     {
       // Any nodes in the vector >= _nodes[next_free_node]
       // are not connected to any elements and may be deleted
       // if desired.
       // (This code block will erase the unused nodes)
       // Now, delete the unused nodes
       {
         std::vector<Node *>::iterator nd        = _nodes.begin();
         const std::vector<Node *>::iterator end = _nodes.end();
         std::advance (nd, next_free_node);
         for (std::vector<Node *>::iterator it=nd;
              it != end; ++it)
           {
             // Mesh modification code might have already deleted some
             // nodes
             if (*it == libmesh_nullptr)
               continue;
             // remove any boundary information associated with
             // this node
             this->get_boundary_info().remove (*it);
             // delete the node
             delete *it;
             *it = libmesh_nullptr;
           }
         _nodes.erase (nd, end);
       }
     }
   libmesh_assert_equal_to (next_free_elem, _elements.size());
   libmesh_assert_equal_to (next_free_node, _nodes.size());
   this->update_parallel_id_counts();
 }
virtual void libMesh::ReplicatedMesh::reserve_elem (const dof_id_type ne) inline virtual inherited
Reserves space for a known number of elements.
Note
This method may or may not do anything, depending on the actual Mesh implementation. If you know the number of elements you will add and call this method before repeatedly calling add_point() the implementation will be more efficient.
Implements libMesh::MeshBase.
Definition at line 135 of file replicated_mesh.h.
References libMesh::ReplicatedMesh::_elements, libMesh::ReplicatedMesh::add_elem(), libMesh::ReplicatedMesh::add_node(), libMesh::ReplicatedMesh::add_point(), libMesh::ReplicatedMesh::delete_elem(), libMesh::ReplicatedMesh::delete_node(), libMesh::ReplicatedMesh::elem_ptr(), libMesh::ReplicatedMesh::elements_begin(), libMesh::ReplicatedMesh::elements_end(), libMesh::ReplicatedMesh::fix_broken_node_and_element_numbering(), libMesh::ReplicatedMesh::insert_elem(), libMesh::ReplicatedMesh::insert_node(), libMesh::DofObject::invalid_id, libMesh::DofObject::invalid_processor_id, libMesh::ReplicatedMesh::node_ptr(), libMesh::ReplicatedMesh::point(), libMesh::ReplicatedMesh::query_elem_ptr(), libMesh::ReplicatedMesh::query_node_ptr(), libMesh::Real, libMesh::ReplicatedMesh::renumber_elem(), libMesh::ReplicatedMesh::renumber_node(), libMesh::ReplicatedMesh::stitch_meshes(), libMesh::ReplicatedMesh::stitch_surfaces(), libMesh::TOLERANCE, and libMesh::ReplicatedMesh::update_parallel_id_counts().
   { _elements.reserve (ne); }
virtual void libMesh::ReplicatedMesh::reserve_nodes (const dof_id_type nn) inline virtual inherited
Reserves space for a known number of nodes.
Note
This method may or may not do anything, depending on the actual Mesh implementation. If you know the number of nodes you will add and call this method before repeatedly calling add_point() the implementation will be more efficient.
Implements libMesh::MeshBase.
Definition at line 117 of file replicated_mesh.h.
References libMesh::ReplicatedMesh::_nodes.
   { _nodes.reserve (nn); }
virtual element_iterator libMesh::ReplicatedMesh::semilocal_elements_begin () virtual inherited
Iterate over elements for which elem->is_semilocal() is true for the current processor.
Implements libMesh::MeshBase.
Referenced by libMesh::ReplicatedMesh::active_element_ptr_range().
virtual const_element_iterator libMesh::ReplicatedMesh::semilocal_elements_begin () const virtual inherited
Implements libMesh::MeshBase.
virtual element_iterator libMesh::ReplicatedMesh::semilocal_elements_end () virtual inherited
Implements libMesh::MeshBase.
Referenced by libMesh::ReplicatedMesh::active_element_ptr_range().
virtual const_element_iterator libMesh::ReplicatedMesh::semilocal_elements_end () const virtual inherited
Implements libMesh::MeshBase.
void libMesh::MeshBase::set_count_lower_dim_elems_in_point_locator (bool count_lower_dim_elems) inherited
In the point locator, do we count lower dimensional elements when we refine point locator regions? This is relevant in tree-based point locators, for example.
Definition at line 564 of file mesh_base.C.
References libMesh::MeshBase::_count_lower_dim_elems_in_point_locator.
 {
   _count_lower_dim_elems_in_point_locator = count_lower_dim_elems;
 }
virtual void libMesh::MeshBase::set_distributed () inline virtual inherited
Asserts that not all elements and nodes of the mesh necessarily exist on the current processor. Only valid to call on classes which can be created in a distributed form.
Reimplemented in libMesh::DistributedMesh.
Definition at line 156 of file mesh_base.h.
Referenced by libMesh::CheckpointIO::read().
   { libmesh_error(); }
void libMesh::MeshBase::set_mesh_dimension (unsigned char d) inline inherited
Resets the logical dimension of the mesh. If the mesh has elements of multiple dimensions, this should be set to the largest dimension. E.g. if the mesh has 1D and 2D elements, this should be set to 2. If the mesh has 2D and 3D elements, this should be set to 3.
Definition at line 200 of file mesh_base.h.
References libMesh::MeshBase::_elem_dims.
Referenced by libMesh::MeshTools::Generation::build_cube(), libMesh::MeshTools::Generation::build_delaunay_square(), libMesh::MeshTools::Generation::build_sphere(), libMesh::TriangleWrapper::copy_tri_to_mesh(), libMesh::AbaqusIO::read(), libMesh::GMVIO::read(), libMesh::Nemesis_IO::read(), libMesh::ExodusII_IO::read(), libMesh::VTKIO::read(), libMesh::CheckpointIO::read_connectivity(), libMesh::CheckpointIO::read_header(), libMesh::XdrIO::read_serialized_connectivity(), libMesh::OFFIO::read_stream(), libMesh::MatlabIO::read_stream(), and libMesh::TriangleInterface::triangulate().
   { _elem_dims.clear(); _elem_dims.insert(d); }
unsigned int& libMesh::MeshBase::set_n_partitions () inline protected inherited
Returns
A writable reference to the number of partitions.
Definition at line 1330 of file mesh_base.h.
References libMesh::MeshBase::_n_parts.
Referenced by libMesh::Partitioner::partition(), libMesh::Partitioner::repartition(), and libMesh::BoundaryInfo::sync().
   { return _n_parts; }
void libMesh::MeshBase::set_next_unique_id (unique_id_type id) inline inherited
Sets the next unique id to be used.
Definition at line 297 of file mesh_base.h.
References libMesh::MeshBase::_next_unique_id, libMesh::MeshBase::max_elem_id(), libMesh::MeshBase::n_active_elem(), libMesh::MeshBase::n_elem(), libMesh::MeshBase::n_elem_on_proc(), libMesh::MeshBase::parallel_max_unique_id(), libMesh::MeshBase::parallel_n_elem(), libMesh::MeshBase::reserve_elem(), libMesh::MeshBase::reserve_nodes(), and libMesh::MeshBase::update_parallel_id_counts().
 { _next_unique_id = id; }
void libMesh::MeshBase::set_spatial_dimension (unsigned char d) inherited
Sets the "spatial dimension" of the Mesh. See the documentation for Mesh::spatial_dimension() for more information.
Definition at line 166 of file mesh_base.C.
References libMesh::MeshBase::_spatial_dimension.
Referenced by libMesh::MeshTools::Generation::build_cube(), and libMesh::MeshBase::elem_dimensions().
 {
   // The user can set the _spatial_dimension however they wish,
   // libMesh will only *increase* the spatial dimension, however,
   // never decrease it.
   _spatial_dimension = d;
 }
std::map<subdomain_id_type, std::string>& libMesh::MeshBase::set_subdomain_name_map () inline inherited
Returns
A writable reference to the whole subdomain name map
Definition at line 1294 of file mesh_base.h.
References libMesh::MeshBase::_block_id_to_name.
Referenced by libMesh::MeshCommunication::broadcast(), libMesh::CheckpointIO::read_header(), libMesh::XdrIO::read_serialized_subdomain_names(), and libMesh::CheckpointIO::read_subdomain_names().
   { return _block_id_to_name; }
void libMesh::MeshBase::skip_partitioning (bool skip) inline inherited
If true is passed in then this mesh will no longer be (re)partitioned. It would probably be a bad idea to call this on a DistributedMesh before the first partitioning has happened... because no elements would get assigned to your processor pool.
Note
Turning on skip_partitioning() can have adverse effects on your performance when using AMR... i.e. you could get large load imbalances. However you might still want to use this if the communication and computation of the rebalance and repartition is too high for your application.
Definition at line 775 of file mesh_base.h.
References libMesh::MeshBase::_skip_partitioning.
Referenced by libMesh::UnstructuredMesh::copy_nodes_and_elements().
 { _skip_partitioning = skip; }
bool libMesh::MeshBase::skip_partitioning () const inline inherited
Definition at line 776 of file mesh_base.h.
References libMesh::MeshBase::_skip_partitioning.
Referenced by libMesh::UnstructuredMesh::copy_nodes_and_elements(), and libMesh::MeshBase::partition().
 { return _skip_partitioning; }
unsigned int libMesh::MeshBase::spatial_dimension () const inherited
Returns
The "spatial dimension" of the mesh.
The spatial dimension is defined as:
1 - for an exactly x-aligned mesh of 1D elements 2 - for an exactly x-y planar mesh of 2D elements 3 - otherwise
No tolerance checks are performed to determine whether the Mesh is x-aligned or x-y planar, only strict equality with zero in the higher dimensions is checked. Also, x-z and y-z planar meshes are considered to have spatial dimension == 3.
The spatial dimension is updated during prepare_for_use() based on the dimensions of the various elements present in the Mesh, but is never automatically decreased by this function.
For example, if the user calls set_spatial_dimension(2) and then later inserts 3D elements into the mesh, Mesh::spatial_dimension() will return 3 after the next call to prepare_for_use(). On the other hand, if the user calls set_spatial_dimension(3) and then inserts only x-aligned 1D elements into the Mesh, mesh.spatial_dimension() will remain 3.
Definition at line 159 of file mesh_base.C.
References libMesh::MeshBase::_spatial_dimension.
Referenced by libMesh::MeshBase::elem_dimensions(), libMesh::MeshBase::get_info(), and libMesh::ExodusII_IO_Helper::initialize().
 {
   return cast_int<unsigned int>(_spatial_dimension);
 }
void libMesh::ReplicatedMesh::stitch_meshes (ReplicatedMesh & other_mesh, boundary_id_type this_mesh_boundary, boundary_id_type other_mesh_boundary, Real tol = TOLERANCE, bool clear_stitched_boundary_ids = false, bool verbose = true, bool use_binary_search = true, bool enforce_all_nodes_match_on_boundaries = false) inherited
Stitch other_mesh to this mesh so that this mesh is the union of the two meshes. this_mesh_boundary and other_mesh_boundary are used to specify a dim-1 dimensional surface on which we seek to merge any "overlapping" nodes, where we use the parameter tol as a relative tolerance (relative to the smallest edge length on the surfaces being stitched) to determine whether or not nodes are overlapping. If clear_stitched_boundary_ids==true, this function clears boundary_info IDs in this mesh associated this_mesh_boundary and other_mesh_boundary. If use_binary_search is true, we use an optimized "sort then binary search" algorithm for finding matching nodes. Otherwise we use a N^2 algorithm (which can be more reliable at dealing with slightly misaligned meshes). If enforce_all_nodes_match_on_boundaries is true, we throw an error if the number of nodes on the specified boundaries don't match the number of nodes that were merged. This is a helpful error check in some cases. If skip_find_neighbors is true, a faster stitching method is used, where the lists of neighbors for each elements are copied as well and patched, without calling the time-consuming find_neighbors() function.
Note that the element IDs for elements in the stitched mesh corresponding to "this" mesh will be unchanged. The IDs for elements corresponding to other_mesh will be incremented by this->max_elem_id().
There is no simple a priori relationship between node IDs in "this" mesh and other_mesh and node IDs in the stitched mesh because the number of nodes (and hence the node IDs) in the stitched mesh depend on how many nodes are stitched.
Definition at line 805 of file replicated_mesh.C.
References libMesh::ReplicatedMesh::stitching_helper().
Referenced by libMesh::ReplicatedMesh::reserve_elem().
 {
   LOG_SCOPE("stitch_meshes()", "ReplicatedMesh");
   stitching_helper(&other_mesh,
                    this_mesh_boundary_id,
                    other_mesh_boundary_id,
                    tol,
                    clear_stitched_boundary_ids,
                    verbose,
                    use_binary_search,
                    enforce_all_nodes_match_on_boundaries,
                    true);
 }
void libMesh::ReplicatedMesh::stitch_surfaces (boundary_id_type boundary_id_1, boundary_id_type boundary_id_2, Real tol = TOLERANCE, bool clear_stitched_boundary_ids = false, bool verbose = true, bool use_binary_search = true, bool enforce_all_nodes_match_on_boundaries = false) inherited
Similar to stitch_meshes, except that we stitch two adjacent surfaces within this mesh.
Definition at line 826 of file replicated_mesh.C.
References libmesh_nullptr, and libMesh::ReplicatedMesh::stitching_helper().
Referenced by libMesh::ReplicatedMesh::reserve_elem().
 {
   stitching_helper(libmesh_nullptr,
                    boundary_id_1,
                    boundary_id_2,
                    tol,
                    clear_stitched_boundary_ids,
                    verbose,
                    use_binary_search,
                    enforce_all_nodes_match_on_boundaries,
                    true);
 }
std::unique_ptr< PointLocatorBase > libMesh::MeshBase::sub_point_locator () const inherited
Returns
A pointer to a subordinate PointLocatorBase object for this mesh, constructing a master PointLocator first if necessary. This should not be used in threaded or non-parallel_only code unless the master has already been constructed.
Definition at line 536 of file mesh_base.C.
References libMesh::MeshBase::_point_locator, libMesh::PointLocatorBase::build(), libMesh::Threads::in_threads, libmesh_nullptr, and libMesh::TREE_ELEMENTS.
Referenced by libMesh::DofMap::create_dof_constraints(), libMesh::MeshFunction::init(), libMesh::MeshRefinement::make_coarsening_compatible(), libMesh::MeshRefinement::make_refinement_compatible(), libMesh::DefaultCoupling::mesh_reinit(), libMesh::PointNeighborCoupling::mesh_reinit(), libMesh::DefaultCoupling::operator()(), libMesh::PointNeighborCoupling::operator()(), libMesh::System::point_gradient(), libMesh::System::point_hessian(), libMesh::System::point_value(), and libMesh::MeshRefinement::test_level_one().
 {
   // If there's no master point locator, then we need one.
   if (_point_locator.get() == libmesh_nullptr)
     {
       // PointLocator construction may not be safe within threads
       libmesh_assert(!Threads::in_threads);
       // And it may require parallel communication
       parallel_object_only();
       _point_locator = PointLocatorBase::build(TREE_ELEMENTS, *this);
     }
   // Otherwise there was a master point locator, and we can grab a
   // sub-locator easily.
   return PointLocatorBase::build(TREE_ELEMENTS, *this, _point_locator.get());
 }
virtual element_iterator libMesh::ReplicatedMesh::subactive_elements_begin () virtual inherited
Iterate over elements for which elem->subactive() is true.
Implements libMesh::MeshBase.
Referenced by libMesh::ReplicatedMesh::active_element_ptr_range().
virtual const_element_iterator libMesh::ReplicatedMesh::subactive_elements_begin () const virtual inherited
Implements libMesh::MeshBase.
virtual element_iterator libMesh::ReplicatedMesh::subactive_elements_end () virtual inherited
Implements libMesh::MeshBase.
Referenced by libMesh::ReplicatedMesh::active_element_ptr_range().
virtual const_element_iterator libMesh::ReplicatedMesh::subactive_elements_end () const virtual inherited
Implements libMesh::MeshBase.
void libMesh::MeshBase::subdomain_ids (std::set< subdomain_id_type > & ids) const inherited
Constructs a list of all subdomain identifiers in the global mesh. Subdomains correspond to separate subsets of the mesh which could correspond e.g. to different materials in a solid mechanics application, or regions where different physical processes are important. The subdomain mapping is independent from the parallel decomposition.
Definition at line 317 of file mesh_base.C.
References libMesh::MeshBase::active_local_elements_begin(), libMesh::MeshBase::active_local_elements_end(), libMesh::ParallelObject::comm(), end, and libMesh::Parallel::Communicator::set_union().
Referenced by libMesh::MeshBase::ghosting_functors_end(), libMesh::MeshBase::n_subdomains(), and libMesh::TecplotIO::TecplotIO().
 {
   // This requires an inspection on every processor
   parallel_object_only();
   ids.clear();
   const_element_iterator el  = this->active_local_elements_begin();
   const_element_iterator end = this->active_local_elements_end();
   for (; el!=end; ++el)
     ids.insert((*el)->subdomain_id());
   // Some subdomains may only live on other processors
   this->comm().set_union(ids);
 }
std::string & libMesh::MeshBase::subdomain_name (subdomain_id_type id) inherited
Returns
A writable reference for getting/setting an optional name for a subdomain.
Definition at line 578 of file mesh_base.C.
References libMesh::MeshBase::_block_id_to_name.
Referenced by libMesh::AbaqusIO::assign_subdomain_ids(), DMlibMeshSetSystem_libMesh(), libMesh::UNVIO::groups_in(), libMesh::MeshBase::libmesh_assert_valid_parallel_ids(), libMesh::ExodusII_IO::read(), libMesh::TecplotIO::write_binary(), libMesh::Nemesis_IO_Helper::write_elements(), and libMesh::ExodusII_IO_Helper::write_elements().
 {
   return _block_id_to_name[id];
 }
const std::string & libMesh::MeshBase::subdomain_name (subdomain_id_type id) const inherited
Definition at line 583 of file mesh_base.C.
References libMesh::MeshBase::_block_id_to_name.
 {
   // An empty string to return when no matching subdomain name is found
   static const std::string empty;
   std::map<subdomain_id_type, std::string>::const_iterator iter = _block_id_to_name.find(id);
   if (iter == _block_id_to_name.end())
     return empty;
   else
     return iter->second;
 }
virtual element_iterator libMesh::ReplicatedMesh::type_elements_begin (ElemType type) virtual inherited
Iterate over all elements with a specified geometric type.
Implements libMesh::MeshBase.
Referenced by libMesh::ReplicatedMesh::active_local_element_ptr_range().
virtual const_element_iterator libMesh::ReplicatedMesh::type_elements_begin (ElemType type) const virtual inherited
Implements libMesh::MeshBase.
virtual element_iterator libMesh::ReplicatedMesh::type_elements_end (ElemType type) virtual inherited
Implements libMesh::MeshBase.
Referenced by libMesh::ReplicatedMesh::active_local_element_ptr_range().
virtual const_element_iterator libMesh::ReplicatedMesh::type_elements_end (ElemType type) const virtual inherited
Implements libMesh::MeshBase.
virtual element_iterator libMesh::ReplicatedMesh::unpartitioned_elements_begin () virtual inherited
Iterate over unpartitioned elements in the Mesh.
Implements libMesh::MeshBase.
Referenced by libMesh::ReplicatedMesh::active_local_element_ptr_range().
virtual const_element_iterator libMesh::ReplicatedMesh::unpartitioned_elements_begin () const virtual inherited
Implements libMesh::MeshBase.
virtual element_iterator libMesh::ReplicatedMesh::unpartitioned_elements_end () virtual inherited
Implements libMesh::MeshBase.
Referenced by libMesh::ReplicatedMesh::active_local_element_ptr_range().
virtual const_element_iterator libMesh::ReplicatedMesh::unpartitioned_elements_end () const virtual inherited
Implements libMesh::MeshBase.
void libMesh::ReplicatedMesh::update_parallel_id_counts () virtual inherited
Updates parallel caches so that methods like n_elem() accurately reflect changes on other processors
Implements libMesh::MeshBase.
Definition at line 610 of file replicated_mesh.C.
References libMesh::MeshBase::_next_unique_id, and libMesh::ReplicatedMesh::parallel_max_unique_id().
Referenced by libMesh::ReplicatedMesh::renumber_nodes_and_elements(), and libMesh::ReplicatedMesh::reserve_elem().
 {
 #ifdef LIBMESH_ENABLE_UNIQUE_ID
   _next_unique_id = this->parallel_max_unique_id();
 #endif
 }
virtual void libMesh::MeshBase::update_post_partitioning () inline virtual inherited
Recalculate any cached data after elements and nodes have been repartitioned.
Reimplemented in libMesh::DistributedMesh.
Definition at line 742 of file mesh_base.h.
Referenced by libMesh::Partitioner::partition(), libMesh::MeshBase::partition(), and libMesh::Nemesis_IO::read().
 {}
void libMesh::UnstructuredMesh::write (const std::string & name) virtual inherited
Write the file specified by name. Attempts to figure out the proper method by the file extension.
Implements libMesh::MeshBase.
Definition at line 635 of file unstructured_mesh.C.
References libMesh::NameBasedIO::write().
 {
   LOG_SCOPE("write()", "Mesh");
   NameBasedIO(*this).write(name);
 }
void libMesh::UnstructuredMesh::write (const std::string & name, const std::vector< Number > & values, const std::vector< std::string > & variable_names) inherited
Write to the file specified by name. Attempts to figure out the proper method by the file extension. Also writes data.
Definition at line 644 of file unstructured_mesh.C.
References libMesh::NameBasedIO::write_nodal_data().
 {
   LOG_SCOPE("write()", "Mesh");
   NameBasedIO(*this).write_nodal_data(name, v, vn);
 }
Member Data Documentation
bool libMesh::MeshBase::_allow_remote_element_removal protected inherited
If this is false then even on DistributedMesh remote elements will not be deleted during mesh preparation.
This is true by default.
Definition at line 1398 of file mesh_base.h.
Referenced by libMesh::MeshBase::allow_remote_element_removal(), and libMesh::MeshBase::prepare_for_use().
std::map<subdomain_id_type, std::string> libMesh::MeshBase::_block_id_to_name protected inherited
This structure maintains the mapping of named blocks for file formats that support named blocks. Currently this is only implemented for ExodusII
Definition at line 1405 of file mesh_base.h.
Referenced by libMesh::MeshBase::get_id_by_name(), libMesh::MeshBase::get_subdomain_name_map(), libMesh::MeshBase::set_subdomain_name_map(), and libMesh::MeshBase::subdomain_name().
const Parallel::Communicator& libMesh::ParallelObject::_communicator protected inherited
Definition at line 105 of file parallel_object.h.
Referenced by libMesh::EquationSystems::build_parallel_solution_vector(), libMesh::ParallelObject::comm(), libMesh::EquationSystems::get_solution(), libMesh::ParallelObject::n_processors(), libMesh::ParallelObject::operator=(), and libMesh::ParallelObject::processor_id().
bool libMesh::MeshBase::_count_lower_dim_elems_in_point_locator protected inherited
Do we count lower dimensional elements in point locator refinement? This is relevant in tree-based point locators, for example.
Definition at line 1363 of file mesh_base.h.
Referenced by libMesh::MeshBase::get_count_lower_dim_elems_in_point_locator(), and libMesh::MeshBase::set_count_lower_dim_elems_in_point_locator().
std::unique_ptr<GhostingFunctor> libMesh::MeshBase::_default_ghosting protected inherited
The default geometric GhostingFunctor, used to implement standard libMesh element ghosting behavior. We use a base class pointer here to avoid dragging in more header dependencies.
Definition at line 1425 of file mesh_base.h.
Referenced by libMesh::MeshBase::MeshBase().
std::set<unsigned char> libMesh::MeshBase::_elem_dims protected inherited
We cache the dimension of the elements present in the mesh. So, if we have a mesh with 1D and 2D elements, this structure will contain 1 and 2.
Definition at line 1412 of file mesh_base.h.
Referenced by libMesh::MeshBase::cache_elem_dims(), libMesh::MeshBase::clear(), libMesh::MeshBase::elem_dimensions(), libMesh::MeshBase::get_info(), libMesh::MeshBase::mesh_dimension(), libMesh::MeshBase::MeshBase(), and libMesh::MeshBase::set_mesh_dimension().
std::vector<Elem *> libMesh::ReplicatedMesh::_elements protected inherited
The elements in the mesh.
Definition at line 479 of file replicated_mesh.h.
Referenced by libMesh::ReplicatedMesh::add_elem(), libMesh::ReplicatedMesh::clear(), libMesh::ReplicatedMesh::delete_elem(), libMesh::ReplicatedMesh::elem_ptr(), libMesh::ReplicatedMesh::fix_broken_node_and_element_numbering(), libMesh::ReplicatedMesh::insert_elem(), libMesh::ReplicatedMesh::max_elem_id(), libMesh::ReplicatedMesh::n_elem(), libMesh::ReplicatedMesh::parallel_n_elem(), libMesh::ReplicatedMesh::query_elem_ptr(), libMesh::ReplicatedMesh::renumber_elem(), libMesh::ReplicatedMesh::renumber_nodes_and_elements(), and libMesh::ReplicatedMesh::reserve_elem().
std::set<GhostingFunctor *> libMesh::MeshBase::_ghosting_functors protected inherited
The list of all GhostingFunctor objects to be used when distributing a DistributedMesh.
Basically unused by ReplicatedMesh for now, but belongs to MeshBase because the cost is trivial.
Definition at line 1434 of file mesh_base.h.
Referenced by libMesh::MeshBase::add_ghosting_functor(), libMesh::MeshBase::ghosting_functors_begin(), libMesh::MeshBase::ghosting_functors_end(), libMesh::MeshBase::MeshBase(), and libMesh::MeshBase::remove_ghosting_functor().
bool libMesh::MeshBase::_is_prepared protected inherited
Flag indicating if the mesh has been prepared for use.
Definition at line 1348 of file mesh_base.h.
Referenced by libMesh::UnstructuredMesh::all_first_order(), libMesh::UnstructuredMesh::all_second_order(), libMesh::MeshBase::clear(), libMesh::UnstructuredMesh::copy_nodes_and_elements(), libMesh::MeshBase::is_prepared(), and libMesh::MeshBase::prepare_for_use().
unsigned int libMesh::MeshBase::_n_parts protected inherited
The number of partitions the mesh has. This is set by the partitioners, and may not be changed directly by the user.
Note
The number of partitions need not equal this->n_processors(), consider for example the case where you simply want to partition a mesh on one processor and view the result in GMV.
Definition at line 1343 of file mesh_base.h.
Referenced by libMesh::MeshBase::clear(), libMesh::UnstructuredMesh::copy_nodes_and_elements(), libMesh::MeshBase::n_partitions(), libMesh::MeshBase::recalculate_n_partitions(), and libMesh::MeshBase::set_n_partitions().
unique_id_type libMesh::MeshBase::_next_unique_id protected inherited
The next available unique id for assigning ids to DOF objects
Definition at line 1377 of file mesh_base.h.
Referenced by libMesh::ReplicatedMesh::add_elem(), libMesh::DistributedMesh::add_elem(), libMesh::ReplicatedMesh::add_node(), libMesh::DistributedMesh::add_node(), libMesh::ReplicatedMesh::add_point(), libMesh::DistributedMesh::DistributedMesh(), libMesh::ReplicatedMesh::insert_elem(), libMesh::DistributedMesh::insert_elem(), libMesh::ReplicatedMesh::insert_node(), libMesh::MeshBase::next_unique_id(), libMesh::ReplicatedMesh::parallel_max_unique_id(), libMesh::DistributedMesh::parallel_max_unique_id(), libMesh::ReplicatedMesh::ReplicatedMesh(), libMesh::MeshBase::set_next_unique_id(), libMesh::ReplicatedMesh::update_parallel_id_counts(), and libMesh::DistributedMesh::update_parallel_id_counts().
std::vector<Node *> libMesh::ReplicatedMesh::_nodes protected inherited
The vertices (spatial coordinates) of the mesh.
Definition at line 474 of file replicated_mesh.h.
Referenced by libMesh::ReplicatedMesh::add_node(), libMesh::ReplicatedMesh::add_point(), libMesh::ReplicatedMesh::clear(), libMesh::ReplicatedMesh::delete_node(), libMesh::ReplicatedMesh::fix_broken_node_and_element_numbering(), libMesh::ReplicatedMesh::insert_node(), libMesh::ReplicatedMesh::max_node_id(), libMesh::ReplicatedMesh::n_nodes(), libMesh::ReplicatedMesh::node_ptr(), libMesh::ReplicatedMesh::parallel_n_nodes(), libMesh::ReplicatedMesh::query_node_ptr(), libMesh::ReplicatedMesh::renumber_node(), libMesh::ReplicatedMesh::renumber_nodes_and_elements(), and libMesh::ReplicatedMesh::reserve_nodes().
std::unique_ptr<Partitioner> libMesh::MeshBase::_partitioner protected inherited
A partitioner to use at each prepare_for_use().
This will be built in the constructor of each derived class, but can be replaced by the user through the partitioner() accessor.
Definition at line 1371 of file mesh_base.h.
Referenced by libMesh::DistributedMesh::DistributedMesh(), libMesh::MeshBase::MeshBase(), libMesh::MeshBase::partitioner(), and libMesh::ReplicatedMesh::ReplicatedMesh().
std::unique_ptr<PointLocatorBase> libMesh::MeshBase::_point_locator mutable protected inherited
A PointLocator class for this mesh. This will not actually be built unless needed. Further, since we want our point_locator() method to be const (yet do the dynamic allocating) this needs to be mutable. Since the PointLocatorBase::build() member is used, and it operates on a constant reference to the mesh, this is OK.
Definition at line 1357 of file mesh_base.h.
Referenced by libMesh::MeshBase::clear_point_locator(), libMesh::MeshBase::point_locator(), and libMesh::MeshBase::sub_point_locator().
bool libMesh::MeshBase::_skip_partitioning protected inherited
If this is true then no partitioning should be done.
Definition at line 1383 of file mesh_base.h.
Referenced by libMesh::MeshBase::skip_partitioning().
bool libMesh::MeshBase::_skip_renumber_nodes_and_elements protected inherited
If this is true then renumbering will be kept to a minimum.
This is set when prepare_for_use() is called.
Definition at line 1390 of file mesh_base.h.
Referenced by libMesh::MeshBase::allow_renumbering(), libMesh::MeshBase::prepare_for_use(), libMesh::ReplicatedMesh::renumber_nodes_and_elements(), and libMesh::DistributedMesh::renumber_nodes_and_elements().
unsigned char libMesh::MeshBase::_spatial_dimension protected inherited
The "spatial dimension" of the Mesh. See the documentation for Mesh::spatial_dimension() for more information.
Definition at line 1418 of file mesh_base.h.
Referenced by libMesh::MeshBase::cache_elem_dims(), libMesh::MeshBase::set_spatial_dimension(), and libMesh::MeshBase::spatial_dimension().
std::unique_ptr<BoundaryInfo> libMesh::MeshBase::boundary_info inherited
This class holds the boundary information. It can store nodes, edges, and faces with a corresponding id that facilitates setting boundary conditions.
Direct access to this class will be removed in future libMesh versions. Use the get_boundary_info() accessor instead.
Definition at line 1322 of file mesh_base.h.
Referenced by libMesh::MeshBase::get_boundary_info().
The documentation for this class was generated from the following file:
serial_mesh.h