libMesh: libMesh::TypeTensor< T > Class Template Reference
SomeWebsiteLogo
libMesh::TypeTensor< T > Class Template Reference
#include <tensor_tools.h>
Public Types
typedef T value_type
Public Member Functions
template<typename T2 >
TypeTensor (const TypeTensor< T2 > &p)
~TypeTensor ()
template<typename T2 >
void assign (const TypeTensor< T2 > &)
template<typename Scalar >
boostcopy::enable_if_c< ScalarTraits< Scalar >::value, TypeTensor & >::type operator= (const Scalar &libmesh_dbg_var(p))
const T & operator() (const unsigned int i, const unsigned int j) const
T & operator() (const unsigned int i, const unsigned int j)
ConstTypeTensorColumn< T > slice (const unsigned int i) const
TypeTensorColumn< T > slice (const unsigned int i)
TypeVector< T > row (const unsigned int r) const
template<typename T2 >
TypeTensor< typename CompareTypes< T, T2 >::supertype > operator+ (const TypeTensor< T2 > &) const
template<typename T2 >
const TypeTensor< T > & operator+= (const TypeTensor< T2 > &)
template<typename T2 >
void add (const TypeTensor< T2 > &)
template<typename T2 >
void add_scaled (const TypeTensor< T2 > &, const T)
template<typename T2 >
TypeTensor< typename CompareTypes< T, T2 >::supertype > operator- (const TypeTensor< T2 > &) const
template<typename T2 >
const TypeTensor< T > & operator-= (const TypeTensor< T2 > &)
template<typename T2 >
void subtract (const TypeTensor< T2 > &)
template<typename T2 >
void subtract_scaled (const TypeTensor< T2 > &, const T)
TypeTensor< T > operator- () const
template<typename Scalar >
boostcopy::enable_if_c< ScalarTraits< Scalar >::value, TypeTensor< typename CompareTypes< T, Scalar >::supertype > >::type operator* (const Scalar) const
template<typename Scalar >
const TypeTensor< T > & operator*= (const Scalar)
template<typename Scalar >
boostcopy::enable_if_c< ScalarTraits< Scalar >::value, TypeTensor< typename CompareTypes< T, Scalar >::supertype > >::type operator/ (const Scalar) const
const TypeTensor< T > & operator/= (const T)
template<typename T2 >
TypeTensor< T > operator* (const TypeTensor< T2 > &) const
template<typename T2 >
CompareTypes< T, T2 >::supertype contract (const TypeTensor< T2 > &) const
template<typename T2 >
TypeVector< typename CompareTypes< T, T2 >::supertype > operator* (const TypeVector< T2 > &) const
TypeTensor< T > transpose () const
TypeTensor< T > inverse () const
void solve (const TypeVector< T > &b, TypeVector< T > &x) const
Real size () const
Real norm () const
Real size_sq () const
Real norm_sq () const
T det () const
T tr () const
void zero ()
bool operator== (const TypeTensor< T > &rhs) const
bool operator< (const TypeTensor< T > &rhs) const
bool operator> (const TypeTensor< T > &rhs) const
void print (std::ostream &os=libMesh::out) const
void write_unformatted (std::ostream &out, const bool newline=true) const
template<>
bool operator< (const TypeTensor< Real > &rhs) const
template<>
bool operator> (const TypeTensor< Real > &rhs) const
template<>
bool operator< (const TypeTensor< Complex > &rhs) const
template<>
bool operator> (const TypeTensor< Complex > &rhs) const
Protected Member Functions
TypeTensor ()
TypeTensor (const T xx, const T xy=0, const T xz=0, const T yx=0, const T yy=0, const T yz=0, const T zx=0, const T zy=0, const T zz=0)
template<typename Scalar >
TypeTensor (const Scalar xx, const Scalar xy=0, const Scalar xz=0, const Scalar yx=0, const Scalar yy=0, const Scalar yz=0, const Scalar zx=0, const Scalar zy=0, typename boostcopy::enable_if_c< ScalarTraits< Scalar >::value, const Scalar >::type zz=0)
template<typename T2 >
TypeTensor (const TypeVector< T2 > &vx)
template<typename T2 >
TypeTensor (const TypeVector< T2 > &vx, const TypeVector< T2 > &vy)
template<typename T2 >
TypeTensor (const TypeVector< T2 > &vx, const TypeVector< T2 > &vy, const TypeVector< T2 > &vz)
Protected Attributes
T _coords [LIBMESH_DIM *LIBMESH_DIM]
Friends
template<typename T2 >
class TypeTensor
std::ostream & operator<< (std::ostream &os, const TypeTensor< T > &t)
Detailed Description
template<typename T>
class libMesh::TypeTensor< T >
This class defines a tensor in LIBMESH_DIM dimensional space of type T. T may either be Real or Complex. The default constructor for this class is protected, suggesting that you should not instantiate one of these directly.
Author
Roy Stogner
Date
2004
Definition at line 32 of file tensor_tools.h.
Member Typedef Documentation
template<typename T> typedef T libMesh::TypeTensor< T >::value_type
Helper typedef for C++98 generic programming.
Definition at line 117 of file type_tensor.h.
Constructor & Destructor Documentation
template<typename T > libMesh::TypeTensor< T >::TypeTensor () inline protected
Empty constructor. Gives the tensor 0 in LIBMESH_DIM dimensions.
Definition at line 483 of file type_tensor.h.
References libMesh::TypeTensor< T >::_coords.
Referenced by libMesh::TypeTensor< T >::inverse(), libMesh::TypeTensor< T >::operator+(), libMesh::TypeTensor< T >::operator-(), and libMesh::TypeTensor< T >::transpose().
 {
   _coords[0] = 0;
 #if LIBMESH_DIM > 1
   _coords[1] = 0;
   _coords[2] = 0;
   _coords[3] = 0;
 #endif
 #if LIBMESH_DIM > 2
   _coords[4] = 0;
   _coords[5] = 0;
   _coords[6] = 0;
   _coords[7] = 0;
   _coords[8] = 0;
 #endif
 }
template<typename T > libMesh::TypeTensor< T >::TypeTensor (const T xx, const T xy = 0, const T xz = 0, const T yx = 0, const T yy = 0, const T yz = 0, const T zx = 0, const T zy = 0, const T zz = 0) inline explicit protected
Constructor-from-T. By default sets higher dimensional entries to 0. This is a poor constructor for 2D tensors - if the default arguments are to be overridden it requires that the "xz = 0." etc. arguments also be given explicitly.
Definition at line 506 of file type_tensor.h.
References libMesh::TypeTensor< T >::_coords.
 {
   _coords[0] = xx;
 #if LIBMESH_DIM == 2
   _coords[1] = xy;
   _coords[2] = yx;
   _coords[3] = yy;
 #endif
 #if LIBMESH_DIM == 3
   _coords[1] = xy;
   _coords[2] = xz;
   _coords[3] = yx;
   _coords[4] = yy;
   _coords[5] = yz;
   _coords[6] = zx;
   _coords[7] = zy;
   _coords[8] = zz;
 #endif
 }
template<typename T > template<typename Scalar > libMesh::TypeTensor< T >::TypeTensor (const Scalar xx, const Scalar xy = 0, const Scalar xz = 0, const Scalar yx = 0, const Scalar yy = 0, const Scalar yz = 0, const Scalar zx = 0, const Scalar zy = 0, typename boostcopy::enable_if_c< ScalarTraits< Scalar >::value, const Scalar >::type zz = 0) inline explicit protected
Constructor-from-Scalar.
Definition at line 540 of file type_tensor.h.
References libMesh::TypeTensor< T >::_coords.
 {
   _coords[0] = xx;
 #if LIBMESH_DIM == 2
   _coords[1] = xy;
   _coords[2] = yx;
   _coords[3] = yy;
 #endif
 #if LIBMESH_DIM == 3
   _coords[1] = xy;
   _coords[2] = xz;
   _coords[3] = yx;
   _coords[4] = yy;
   _coords[5] = yz;
   _coords[6] = zx;
   _coords[7] = zy;
   _coords[8] = zz;
 #endif
 }
template<typename T > template<typename T2 > libMesh::TypeTensor< T >::TypeTensor (const TypeVector< T2 > & vx) protected
Constructor. Assigns each vector to a different row of the tensor. We're in LIBMESH_DIM space dimensions and so LIBMESH_DIM many vectors are needed.
Definition at line 587 of file type_tensor.h.
References libMesh::TypeTensor< T >::_coords.
 {
   libmesh_assert_equal_to (LIBMESH_DIM, 1);
   _coords[0] = vx(0);
 }
template<typename T > template<typename T2 > libMesh::TypeTensor< T >::TypeTensor (const TypeVector< T2 > & vx, const TypeVector< T2 > & vy) protected
Definition at line 595 of file type_tensor.h.
References libMesh::TypeTensor< T >::_coords.
 {
   libmesh_assert_equal_to (LIBMESH_DIM, 2);
   _coords[0] = vx(0);
   _coords[1] = vx(1);
   _coords[2] = vy(0);
   _coords[3] = vy(1);
 }
template<typename T > template<typename T2 > libMesh::TypeTensor< T >::TypeTensor (const TypeVector< T2 > & vx, const TypeVector< T2 > & vy, const TypeVector< T2 > & vz) protected
Definition at line 607 of file type_tensor.h.
References libMesh::TypeTensor< T >::_coords.
 {
   libmesh_assert_equal_to (LIBMESH_DIM, 3);
   _coords[0] = vx(0);
   _coords[1] = vx(1);
   _coords[2] = vx(2);
   _coords[3] = vy(0);
   _coords[4] = vy(1);
   _coords[5] = vy(2);
   _coords[6] = vz(0);
   _coords[7] = vz(1);
   _coords[8] = vz(2);
 }
template<typename T > template<typename T2 > libMesh::TypeTensor< T >::TypeTensor (const TypeTensor< T2 > & p) inline
Copy-constructor.
Definition at line 577 of file type_tensor.h.
References libMesh::TypeTensor< T >::_coords.
 {
   // copy the nodes from vector p to me
   for (unsigned int i=0; i<LIBMESH_DIM*LIBMESH_DIM; i++)
     _coords[i] = p._coords[i];
 }
template<typename T > libMesh::TypeTensor< T >::~TypeTensor () inline
Destructor.
Definition at line 628 of file type_tensor.h.
 {
 }
Member Function Documentation
template<typename T > template<typename T2 > void libMesh::TypeTensor< T >::add (const TypeTensor< T2 > & p) inline
Add to this tensor without creating a temporary.
Definition at line 766 of file type_tensor.h.
References libMesh::TypeTensor< T >::_coords.
Referenced by libMesh::TypeTensor< T >::operator+=(), and libMesh::TypeTensor< T >::operator=().
 {
   for (unsigned int i=0; i<LIBMESH_DIM*LIBMESH_DIM; i++)
     _coords[i] += p._coords[i];
 }
template<typename T > template<typename T2 > void libMesh::TypeTensor< T >::add_scaled (const TypeTensor< T2 > & p, const T factor) inline
Add a scaled tensor to this tensor without creating a temporary.
Definition at line 777 of file type_tensor.h.
References libMesh::TypeTensor< T >::_coords.
Referenced by libMesh::HPCoarsenTest::add_projection(), libMesh::System::calculate_norm(), libMesh::MeshFunction::hessian(), libMesh::WeightedPatchRecoveryErrorEstimator::EstimateError::operator()(), libMesh::PatchRecoveryErrorEstimator::EstimateError::operator()(), libMesh::TypeTensor< T >::operator=(), libMesh::System::point_hessian(), and libMesh::HPCoarsenTest::select_refinement().
 {
   for (unsigned int i=0; i<LIBMESH_DIM*LIBMESH_DIM; i++)
     _coords[i] += factor*p._coords[i];
 }
template<typename T > template<typename T2 > void libMesh::TypeTensor< T >::assign (const TypeTensor< T2 > & p) inline
Assign to this tensor without creating a temporary.
Definition at line 637 of file type_tensor.h.
References libMesh::TypeTensor< T >::_coords.
 {
   for (unsigned int i=0; i<LIBMESH_DIM*LIBMESH_DIM; i++)
     _coords[i] = p._coords[i];
 }
template<typename T > template<typename T2 > CompareTypes< T, T2 >::supertype libMesh::TypeTensor< T >::contract (const TypeTensor< T2 > & t) const inline
Multiply 2 tensors together, i.e. dyadic product, The tensors may contain different numeric types.
Returns
A copy of the result, this tensor is unchanged.
Multiply 2 tensors together, i.e. sum Aij*Bij. The tensors may be of different types.
Definition at line 1175 of file type_tensor.h.
References libMesh::TypeTensor< T >::_coords, and libMesh::Parallel::sum().
Referenced by libMesh::HPCoarsenTest::add_projection(), libMesh::TensorTools::inner_product(), libMesh::TypeTensor< T >::operator=(), and libMesh::HPCoarsenTest::select_refinement().
 {
   typename CompareTypes<T,T2>::supertype sum = 0.;
   for (unsigned int i=0; i<LIBMESH_DIM*LIBMESH_DIM; i++)
     sum += _coords[i]*t._coords[i];
   return sum;
 }
template<typename T > T libMesh::TypeTensor< T >::det () const inline
Returns
The determinant of the tensor.
Because these are 3x3 tensors at most, we don't do an LU decomposition like DenseMatrix does.
Definition at line 1208 of file type_tensor.h.
References libMesh::TypeTensor< T >::_coords.
Referenced by libMesh::TypeTensor< T >::operator=(), and libMesh::Sphere::Sphere().
 {
 #if LIBMESH_DIM == 1
   return _coords[0];
 #endif
 #if LIBMESH_DIM == 2
   return (_coords[0] * _coords[3]
           - _coords[1] * _coords[2]);
 #endif
 #if LIBMESH_DIM == 3
   return (_coords[0] * _coords[4] * _coords[8]
           + _coords[1] * _coords[5] * _coords[6]
           + _coords[2] * _coords[3] * _coords[7]
           - _coords[0] * _coords[5] * _coords[7]
           - _coords[1] * _coords[3] * _coords[8]
           - _coords[2] * _coords[4] * _coords[6]);
 #endif
 }
template<typename T > TypeTensor< T > libMesh::TypeTensor< T >::inverse () const inline
Returns
The inverse of this tensor as an independent object.
Definition at line 1022 of file type_tensor.h.
References libMesh::TypeTensor< T >::_coords, A, and libMesh::TypeTensor< T >::TypeTensor().
Referenced by libMesh::TypeTensor< T >::operator=().
 {
 #if LIBMESH_DIM == 1
   if (_coords[0] == static_cast<T>(0.))
     libmesh_convergence_failure();
   return TypeTensor(1. / _coords[0]);
 #endif
 #if LIBMESH_DIM == 2
   // Get convenient reference to this.
   const TypeTensor<T> & A = *this;
   // Use temporary variables, avoid multiple accesses
   T a = A(0,0), b = A(0,1),
     c = A(1,0), d = A(1,1);
   // Make sure det = ad - bc is not zero
   T my_det = a*d - b*c;
   if (my_det == static_cast<T>(0.))
     libmesh_convergence_failure();
   return TypeTensor(d/my_det, -b/my_det, -c/my_det, a/my_det);
 #endif
 #if LIBMESH_DIM == 3
   // Get convenient reference to this.
   const TypeTensor<T> & A = *this;
   T a11 = A(0,0), a12 = A(0,1), a13 = A(0,2),
     a21 = A(1,0), a22 = A(1,1), a23 = A(1,2),
     a31 = A(2,0), a32 = A(2,1), a33 = A(2,2);
   T my_det = a11*(a33*a22-a32*a23) - a21*(a33*a12-a32*a13) + a31*(a23*a12-a22*a13);
   if (my_det == static_cast<T>(0.))
     libmesh_convergence_failure();
   // Inline comment characters are for lining up columns.
   return TypeTensor(  (a33*a22-a32*a23)/my_det, -(a33*a12-a32*a13)/my_det,  (a23*a12-a22*a13)/my_det,
                      -(a33*a21-a31*a23)/my_det,  (a33*a11-a31*a13)/my_det, -(a23*a11-a21*a13)/my_det,
                       (a32*a21-a31*a22)/my_det, -(a32*a11-a31*a12)/my_det,  (a22*a11-a21*a12)/my_det);
 #endif
 }
template<typename T > Real libMesh::TypeTensor< T >::norm () const inline
Returns
The Frobenius norm of the tensor, i.e. the square-root of the sum of the elements squared.
Definition at line 1199 of file type_tensor.h.
References libMesh::TypeTensor< T >::norm_sq().
Referenced by libMesh::System::calculate_norm(), libMesh::TypeTensor< T >::operator=(), and libMesh::TypeTensor< T >::size().
 {
   return std::sqrt(this->norm_sq());
 }
template<typename T > Real libMesh::TypeTensor< T >::norm_sq () const inline
Returns
The Frobenius norm of the tensor squared, i.e. sum of the element magnitudes squared.
Definition at line 1270 of file type_tensor.h.
References libMesh::TypeTensor< T >::_coords, libMesh::TensorTools::norm_sq(), libMesh::Real, and libMesh::Parallel::sum().
Referenced by libMesh::UniformRefinementEstimator::_estimate_error(), libMesh::System::calculate_norm(), libMesh::ExactErrorEstimator::find_squared_element_error(), libMesh::TypeTensor< T >::norm(), libMesh::TypeTensor< T >::operator=(), libMesh::HPCoarsenTest::select_refinement(), and libMesh::TypeTensor< T >::size_sq().
 {
   Real sum = 0.;
   for (unsigned int i=0; i<LIBMESH_DIM*LIBMESH_DIM; i++)
     sum += TensorTools::norm_sq(_coords[i]);
   return sum;
 }
template<typename T > const T & libMesh::TypeTensor< T >::operator() (const unsigned int i, const unsigned int j) const inline
Returns
A const reference to the (i,j) entry of the tensor.
Definition at line 647 of file type_tensor.h.
References libMesh::TypeTensor< T >::_coords.
Referenced by libMesh::TypeTensor< T >::operator=().
 {
   libmesh_assert_less (i, 3);
   libmesh_assert_less (j, 3);
 #if LIBMESH_DIM < 3
   const static T my_zero = 0;
   if (i >= LIBMESH_DIM || j >= LIBMESH_DIM)
     return my_zero;
 #endif
   return _coords[i*LIBMESH_DIM+j];
 }
template<typename T > T & libMesh::TypeTensor< T >::operator() (const unsigned int i, const unsigned int j) inline
Returns
A writable reference to the (i,j) entry of the tensor.
Definition at line 666 of file type_tensor.h.
References libMesh::TypeTensor< T >::_coords.
 {
 #if LIBMESH_DIM < 3
   if (i >= LIBMESH_DIM || j >= LIBMESH_DIM)
     libmesh_error_msg("ERROR:  You are assigning to a tensor component that is out of range for the compiled LIBMESH_DIM!");
 #endif
   libmesh_assert_less (i, LIBMESH_DIM);
   libmesh_assert_less (j, LIBMESH_DIM);
   return _coords[i*LIBMESH_DIM+j];
 }
template<typename T > template<typename Scalar > boostcopy::enable_if_c< ScalarTraits< Scalar >::value, TypeTensor< typename CompareTypes< T, Scalar >::supertype > >::type libMesh::TypeTensor< T >::operator* (const Scalar factor) const inline
Multiply this tensor by a scalar value.
Returns
A copy of the result, this tensor is unchanged.
Definition at line 893 of file type_tensor.h.
References libMesh::TypeTensor< T >::_coords.
Referenced by libMesh::TypeTensor< T >::operator=().
 {
   typedef typename CompareTypes<T, Scalar>::supertype TS;
 #if LIBMESH_DIM == 1
   return TypeTensor<TS>(_coords[0]*factor);
 #endif
 #if LIBMESH_DIM == 2
   return TypeTensor<TS>(_coords[0]*factor,
                         _coords[1]*factor,
                         _coords[2]*factor,
                         _coords[3]*factor);
 #endif
 #if LIBMESH_DIM == 3
   return TypeTensor<TS>(_coords[0]*factor,
                         _coords[1]*factor,
                         _coords[2]*factor,
                         _coords[3]*factor,
                         _coords[4]*factor,
                         _coords[5]*factor,
                         _coords[6]*factor,
                         _coords[7]*factor,
                         _coords[8]*factor);
 #endif
 }
template<typename T > template<typename T2 > TypeTensor< T > libMesh::TypeTensor< T >::operator* (const TypeTensor< T2 > & p) const inline
Multiply 2 tensors together, i.e. matrix-matrix product. The tensors may contain different numeric types.
Returns
A copy of the result, this tensor is unchanged.
Definition at line 1154 of file type_tensor.h.
 {
   TypeTensor<T> returnval;
   for (unsigned int i=0; i<LIBMESH_DIM; i++)
     for (unsigned int j=0; j<LIBMESH_DIM; j++)
       for (unsigned int k=0; k<LIBMESH_DIM; k++)
         returnval(i,j) += (*this)(i,k)*p(k,j);
   return returnval;
 }
template<typename T > template<typename T2 > TypeVector< typename CompareTypes< T, T2 >::supertype > libMesh::TypeTensor< T >::operator* (const TypeVector< T2 > & p) const inline
Multiply this tensor by a vector, i.e. matrix-vector product. The tensor and vector may contain different numeric types.
Returns
A copy of the result vector, this tensor is unchanged.
Definition at line 1139 of file type_tensor.h.
 {
   TypeVector<typename CompareTypes<T,T2>::supertype> returnval;
   for (unsigned int i=0; i<LIBMESH_DIM; i++)
     for (unsigned int j=0; j<LIBMESH_DIM; j++)
       returnval(i) += (*this)(i,j)*p(j);
   return returnval;
 }
template<typename T > template<typename Scalar > const TypeTensor< T > & libMesh::TypeTensor< T >::operator*= (const Scalar factor) inline
Multiply this tensor by a scalar value in place.
Returns
A reference to *this.
Definition at line 940 of file type_tensor.h.
References libMesh::TypeTensor< T >::_coords.
Referenced by libMesh::TypeTensor< T >::operator=().
 {
   for (unsigned int i=0; i<LIBMESH_DIM*LIBMESH_DIM; i++)
     _coords[i] *= factor;
   return *this;
 }
template<typename T > template<typename T2 > TypeTensor< typename CompareTypes< T, T2 >::supertype > libMesh::TypeTensor< T >::operator+ (const TypeTensor< T2 > & p) const inline
Add another tensor to this tensor.
Returns
A copy of the result, this tensor is unchanged.
Definition at line 720 of file type_tensor.h.
References libMesh::TypeTensor< T >::_coords, and libMesh::TypeTensor< T >::TypeTensor().
Referenced by libMesh::TypeTensor< T >::operator=().
 {
 #if LIBMESH_DIM == 1
   return TypeTensor(_coords[0] + p._coords[0]);
 #endif
 #if LIBMESH_DIM == 2
   return TypeTensor(_coords[0] + p._coords[0],
                     _coords[1] + p._coords[1],
                     0.,
                     _coords[2] + p._coords[2],
                     _coords[3] + p._coords[3]);
 #endif
 #if LIBMESH_DIM == 3
   return TypeTensor(_coords[0] + p._coords[0],
                     _coords[1] + p._coords[1],
                     _coords[2] + p._coords[2],
                     _coords[3] + p._coords[3],
                     _coords[4] + p._coords[4],
                     _coords[5] + p._coords[5],
                     _coords[6] + p._coords[6],
                     _coords[7] + p._coords[7],
                     _coords[8] + p._coords[8]);
 #endif
 }
template<typename T > template<typename T2 > const TypeTensor< T > & libMesh::TypeTensor< T >::operator+= (const TypeTensor< T2 > & p) inline
Add to this tensor.
Returns
A reference to *this.
Definition at line 754 of file type_tensor.h.
References libMesh::TypeTensor< T >::add().
Referenced by libMesh::TypeTensor< T >::operator=().
 {
   this->add (p);
   return *this;
 }
template<typename T > template<typename T2 > TypeTensor< typename CompareTypes< T, T2 >::supertype > libMesh::TypeTensor< T >::operator- (const TypeTensor< T2 > & p) const inline
Subtract a tensor from this tensor.
Returns
A copy of the result, this tensor is unchanged.
Definition at line 790 of file type_tensor.h.
References libMesh::TypeTensor< T >::_coords, and libMesh::TypeTensor< T >::TypeTensor().
 {
 #if LIBMESH_DIM == 1
   return TypeTensor(_coords[0] - p._coords[0]);
 #endif
 #if LIBMESH_DIM == 2
   return TypeTensor(_coords[0] - p._coords[0],
                     _coords[1] - p._coords[1],
                     0.,
                     _coords[2] - p._coords[2],
                     _coords[3] - p._coords[3]);
 #endif
 #if LIBMESH_DIM == 3
   return TypeTensor(_coords[0] - p._coords[0],
                     _coords[1] - p._coords[1],
                     _coords[2] - p._coords[2],
                     _coords[3] - p._coords[3],
                     _coords[4] - p._coords[4],
                     _coords[5] - p._coords[5],
                     _coords[6] - p._coords[6],
                     _coords[7] - p._coords[7],
                     _coords[8] - p._coords[8]);
 #endif
 }
template<typename T > TypeTensor< T > libMesh::TypeTensor< T >::operator- () const inline
Returns
The negative of this tensor in a separate copy.
Definition at line 857 of file type_tensor.h.
References libMesh::TypeTensor< T >::_coords, and libMesh::TypeTensor< T >::TypeTensor().
Referenced by libMesh::TypeTensor< T >::operator=().
 {
 #if LIBMESH_DIM == 1
   return TypeTensor(-_coords[0]);
 #endif
 #if LIBMESH_DIM == 2
   return TypeTensor(-_coords[0],
                     -_coords[1],
                     -_coords[2],
                     -_coords[3]);
 #endif
 #if LIBMESH_DIM == 3
   return TypeTensor(-_coords[0],
                     -_coords[1],
                     -_coords[2],
                     -_coords[3],
                     -_coords[4],
                     -_coords[5],
                     -_coords[6],
                     -_coords[7],
                     -_coords[8]);
 #endif
 }
template<typename T > template<typename T2 > const TypeTensor< T > & libMesh::TypeTensor< T >::operator-= (const TypeTensor< T2 > & p) inline
Subtract from this tensor.
Returns
A reference to *this.
Definition at line 824 of file type_tensor.h.
References libMesh::TypeTensor< T >::subtract().
Referenced by libMesh::TypeTensor< T >::operator=().
 {
   this->subtract (p);
   return *this;
 }
template<typename T > template<typename Scalar > boostcopy::enable_if_c< ScalarTraits< Scalar >::value, TypeTensor< typename CompareTypes< T, Scalar >::supertype > >::type libMesh::TypeTensor< T >::operator/ (const Scalar factor) const inline
Divide each entry of this tensor by a scalar value.
Returns
A copy of the result, this tensor is unchanged.
Definition at line 957 of file type_tensor.h.
References libMesh::TypeTensor< T >::_coords.
Referenced by libMesh::TypeTensor< T >::operator=().
 {
   libmesh_assert_not_equal_to (factor, static_cast<T>(0.));
   typedef typename CompareTypes<T, Scalar>::supertype TS;
 #if LIBMESH_DIM == 1
   return TypeTensor<TS>(_coords[0]/factor);
 #endif
 #if LIBMESH_DIM == 2
   return TypeTensor<TS>(_coords[0]/factor,
                         _coords[1]/factor,
                         _coords[2]/factor,
                         _coords[3]/factor);
 #endif
 #if LIBMESH_DIM == 3
   return TypeTensor<TS>(_coords[0]/factor,
                         _coords[1]/factor,
                         _coords[2]/factor,
                         _coords[3]/factor,
                         _coords[4]/factor,
                         _coords[5]/factor,
                         _coords[6]/factor,
                         _coords[7]/factor,
                         _coords[8]/factor);
 #endif
 }
template<typename T > const TypeTensor< T > & libMesh::TypeTensor< T >::operator/= (const T factor) inline
Divide each entry of this tensor by a scalar value.
Returns
A reference to *this.
Definition at line 1122 of file type_tensor.h.
References libMesh::TypeTensor< T >::_coords.
Referenced by libMesh::TypeTensor< T >::operator=().
 {
   libmesh_assert_not_equal_to (factor, static_cast<T>(0.));
   for (unsigned int i=0; i<LIBMESH_DIM*LIBMESH_DIM; i++)
     _coords[i] /= factor;
   return *this;
 }
template<> bool libMesh::TypeTensor< Real >::operator< (const TypeTensor< Real > & rhs) const
Definition at line 113 of file type_tensor.C.
 {
   for (unsigned int i=0; i<LIBMESH_DIM; i++)
     for (unsigned int j=0; j<LIBMESH_DIM; j++)
       {
         if ((*this)(i,j) < rhs(i,j))
           return true;
         if ((*this)(i,j) > rhs(i,j))
           return false;
       }
   return false;
 }
template<> bool libMesh::TypeTensor< Complex >::operator< (const TypeTensor< Complex > & rhs) const
Definition at line 146 of file type_tensor.C.
 {
   for (unsigned int i=0; i<LIBMESH_DIM; i++)
     for (unsigned int j=0; j<LIBMESH_DIM; j++)
       {
         if ((*this)(i,j).real() < rhs(i,j).real())
           return true;
         if ((*this)(i,j).real() > rhs(i,j).real())
           return false;
         if ((*this)(i,j).imag() < rhs(i,j).imag())
           return true;
         if ((*this)(i,j).imag() > rhs(i,j).imag())
           return false;
       }
   return false;
 }
template<typename T> bool libMesh::TypeTensor< T >::operator< (const TypeTensor< T > & rhs) const
Returns
true if this tensor is "less" than another. Useful for sorting.
template<typename T> template<typename Scalar > boostcopy::enable_if_c< ScalarTraits<Scalar>::value, TypeTensor &>::type libMesh::TypeTensor< T >::operator= (const Scalar & libmesh_dbg_varp) inline
Assignment-from-scalar operator. Used only to zero out vectors.
Returns
A reference to *this.
Definition at line 145 of file type_tensor.h.
References libMesh::TypeTensor< T >::add(), libMesh::TypeTensor< T >::add_scaled(), libMesh::TypeTensor< T >::contract(), libMesh::TypeTensor< T >::det(), libMesh::TypeTensor< T >::inverse(), libMesh::TypeTensor< T >::norm(), libMesh::TypeTensor< T >::norm_sq(), libMesh::TypeTensor< T >::operator()(), libMesh::TypeTensor< T >::operator*(), libMesh::TypeTensor< T >::operator*=(), libMesh::TypeTensor< T >::operator+(), libMesh::TypeTensor< T >::operator+=(), libMesh::TypeTensor< T >::operator-(), libMesh::TypeTensor< T >::operator-=(), libMesh::TypeTensor< T >::operator/(), libMesh::TypeTensor< T >::operator/=(), libMesh::TypeTensor< T >::operator==(), libMesh::TypeTensor< T >::operator>(), libMesh::out, libMesh::TypeTensor< T >::print(), libMesh::Real, libMesh::TypeTensor< T >::row(), libMesh::TypeTensor< T >::size(), libMesh::TypeTensor< T >::size_sq(), libMesh::TypeTensor< T >::slice(), libMesh::TypeTensor< T >::solve(), libMesh::TypeTensor< T >::subtract(), libMesh::TypeTensor< T >::subtract_scaled(), libMesh::TypeTensor< T >::tr(), libMesh::TypeTensor< T >::transpose(), and libMesh::TypeTensor< T >::zero().
   { libmesh_assert_equal_to (p, Scalar(0)); this->zero(); return *this; }
template<typename T > bool libMesh::TypeTensor< T >::operator== (const TypeTensor< T > & rhs) const inline
Returns
true if two tensors are equal, false otherwise.
Definition at line 1282 of file type_tensor.h.
References libMesh::TypeTensor< T >::_coords, std::abs(), and libMesh::TOLERANCE.
Referenced by libMesh::TypeTensor< T >::operator=().
 {
 #if LIBMESH_DIM == 1
   return (std::abs(_coords[0] - rhs._coords[0])
           < TOLERANCE);
 #endif
 #if LIBMESH_DIM == 2
   return ((std::abs(_coords[0] - rhs._coords[0]) +
            std::abs(_coords[1] - rhs._coords[1]) +
            std::abs(_coords[2] - rhs._coords[2]) +
            std::abs(_coords[3] - rhs._coords[3]))
           < 4.*TOLERANCE);
 #endif
 #if LIBMESH_DIM == 3
   return ((std::abs(_coords[0] - rhs._coords[0]) +
            std::abs(_coords[1] - rhs._coords[1]) +
            std::abs(_coords[2] - rhs._coords[2]) +
            std::abs(_coords[3] - rhs._coords[3]) +
            std::abs(_coords[4] - rhs._coords[4]) +
            std::abs(_coords[5] - rhs._coords[5]) +
            std::abs(_coords[6] - rhs._coords[6]) +
            std::abs(_coords[7] - rhs._coords[7]) +
            std::abs(_coords[8] - rhs._coords[8]))
           < 9.*TOLERANCE);
 #endif
 }
template<> bool libMesh::TypeTensor< Real >::operator> (const TypeTensor< Real > & rhs) const
Definition at line 129 of file type_tensor.C.
 {
   for (unsigned int i=0; i<LIBMESH_DIM; i++)
     for (unsigned int j=0; j<LIBMESH_DIM; j++)
       {
         if ((*this)(i,j) > rhs(i,j))
           return true;
         if ((*this)(i,j) < rhs(i,j))
           return false;
       }
   return false;
 }
template<> bool libMesh::TypeTensor< Complex >::operator> (const TypeTensor< Complex > & rhs) const
Definition at line 166 of file type_tensor.C.
 {
   for (unsigned int i=0; i<LIBMESH_DIM; i++)
     for (unsigned int j=0; j<LIBMESH_DIM; j++)
       {
         if ((*this)(i,j).real() > rhs(i,j).real())
           return true;
         if ((*this)(i,j).real() < rhs(i,j).real())
           return false;
         if ((*this)(i,j).imag() > rhs(i,j).imag())
           return true;
         if ((*this)(i,j).imag() < rhs(i,j).imag())
           return false;
       }
   return false;
 }
template<typename T> bool libMesh::TypeTensor< T >::operator> (const TypeTensor< T > & rhs) const
Returns
true if this tensor is "greater" than another.
Referenced by libMesh::TypeTensor< T >::operator=().
template<typename T > void libMesh::TypeTensor< T >::print (std::ostream & os = libMesh::out) const
Formatted print to a stream which defaults to libMesh::out.
Definition at line 39 of file type_tensor.C.
Referenced by libMesh::TypeTensor< T >::operator=().
 {
 #if LIBMESH_DIM == 1
   os << "x=" << (*this)(0,0) << std::endl;
 #endif
 #if LIBMESH_DIM == 2
   os << "(xx,xy)=("
      << std::setw(8) << (*this)(0,0) << ", "
      << std::setw(8) << (*this)(0,1) << ")"
      << std::endl;
   os << "(yx,yy)=("
      << std::setw(8) << (*this)(1,0) << ", "
      << std::setw(8) << (*this)(1,1) << ")"
      << std::endl;
 #endif
 #if LIBMESH_DIM == 3
   os <<  "(xx,xy,xz)=("
      << std::setw(8) << (*this)(0,0) << ", "
      << std::setw(8) << (*this)(0,1) << ", "
      << std::setw(8) << (*this)(0,2) << ")"
      << std::endl;
   os <<  "(yx,yy,yz)=("
      << std::setw(8) << (*this)(1,0) << ", "
      << std::setw(8) << (*this)(1,1) << ", "
      << std::setw(8) << (*this)(1,2) << ")"
      << std::endl;
   os <<  "(zx,zy,zz)=("
      << std::setw(8) << (*this)(2,0) << ", "
      << std::setw(8) << (*this)(2,1) << ", "
      << std::setw(8) << (*this)(2,2) << ")"
      << std::endl;
 #endif
 }
template<typename T > TypeVector< T > libMesh::TypeTensor< T >::row (const unsigned int r) const inline
Returns
A copy of one row of the tensor as a TypeVector.
Definition at line 706 of file type_tensor.h.
References libMesh::TypeVector< T >::_coords, and libMesh::TypeTensor< T >::_coords.
Referenced by libMesh::TypeTensor< T >::operator=().
 {
   TypeVector<T> return_vector;
   for (unsigned int j=0; j<LIBMESH_DIM; j++)
     return_vector._coords[j] = _coords[r*LIBMESH_DIM + j];
   return return_vector;
 }
template<typename T > Real libMesh::TypeTensor< T >::size () const inline
Returns
The Frobenius norm of the tensor, i.e. the square-root of the sum of the elements squared.
Deprecated:
Use the norm() function instead.
Definition at line 1188 of file type_tensor.h.
References libMesh::TypeTensor< T >::norm().
Referenced by libMesh::TypeTensor< T >::operator=().
 {
   libmesh_deprecated();
   return this->norm();
 }
template<typename T > Real libMesh::TypeTensor< T >::size_sq () const inline
Returns
The Frobenius norm of the tensor squared, i.e. sum of the element magnitudes squared.
Deprecated:
Use the norm_sq() function instead.
Definition at line 1259 of file type_tensor.h.
References libMesh::TypeTensor< T >::norm_sq().
Referenced by libMesh::TypeTensor< T >::operator=().
 {
   libmesh_deprecated();
   return this->norm_sq();
 }
template<typename T > ConstTypeTensorColumn< T > libMesh::TypeTensor< T >::slice (const unsigned int i) const inline
Returns
A proxy for the column of the tensor.
Definition at line 686 of file type_tensor.h.
Referenced by libMesh::TypeTensor< T >::operator=().
 {
   libmesh_assert_less (i, LIBMESH_DIM);
   return ConstTypeTensorColumn<T>(*this, i);
 }
template<typename T > TypeTensorColumn< T > libMesh::TypeTensor< T >::slice (const unsigned int i) inline
Returns
A writable proxy for the column of the tensor.
Definition at line 696 of file type_tensor.h.
 {
   libmesh_assert_less (i, LIBMESH_DIM);
   return TypeTensorColumn<T>(*this, i);
 }
template<typename T > void libMesh::TypeTensor< T >::solve (const TypeVector< T > & b, TypeVector< T > & x) const inline
Solve the 2x2 or 3x3 system of equations A*x = b for x by directly inverting A and multiplying it by b.
Returns
The solution in the x vector.
Definition at line 1071 of file type_tensor.h.
References libMesh::TypeTensor< T >::_coords.
Referenced by libMesh::TypeTensor< T >::operator=().
 {
 #if LIBMESH_DIM == 1
   if (_coords[0] == static_cast<T>(0.))
     libmesh_convergence_failure();
   x(0) = b(0) / _coords[0];
 #endif
 #if LIBMESH_DIM == 2
   T my_det = _coords[0]*_coords[3] - _coords[1]*_coords[2];
   if (my_det == static_cast<T>(0.))
     libmesh_convergence_failure();
   T my_det_inv = 1./my_det;
   x(0) = my_det_inv*( _coords[3]*b(0) - _coords[1]*b(1));
   x(1) = my_det_inv*(-_coords[2]*b(0) + _coords[0]*b(1));
 #endif
 #if LIBMESH_DIM == 3
   T my_det =
     //           a11*(a33       *a22        - a32       *a23)
       _coords[0]*(_coords[8]*_coords[4] - _coords[7]*_coords[5])
     //          -a21*(a33       *a12        - a32       *a13)
      -_coords[3]*(_coords[8]*_coords[1] - _coords[7]*_coords[2]) +
     //          +a31*(a23       *a12        - a22       *a13)
      +_coords[6]*(_coords[5]*_coords[1] - _coords[4]*_coords[2]);
   if (my_det == static_cast<T>(0.))
     libmesh_convergence_failure();
   T my_det_inv = 1./my_det;
   x(0) = my_det_inv*((_coords[8]*_coords[4] - _coords[7]*_coords[5])*b(0) -
                      (_coords[8]*_coords[1] - _coords[7]*_coords[2])*b(1) +
                      (_coords[5]*_coords[1] - _coords[4]*_coords[2])*b(2));
   x(1) = my_det_inv*((_coords[6]*_coords[5] - _coords[8]*_coords[3])*b(0) +
                      (_coords[8]*_coords[0] - _coords[6]*_coords[2])*b(1) -
                      (_coords[5]*_coords[0] - _coords[3]*_coords[2])*b(2));
   x(2) = my_det_inv*((_coords[7]*_coords[3] - _coords[6]*_coords[4])*b(0) -
                      (_coords[7]*_coords[0] - _coords[6]*_coords[1])*b(1) +
                      (_coords[4]*_coords[0] - _coords[3]*_coords[1])*b(2));
 #endif
 }
template<typename T > template<typename T2 > void libMesh::TypeTensor< T >::subtract (const TypeTensor< T2 > & p) inline
Subtract from this tensor without creating a temporary.
Definition at line 836 of file type_tensor.h.
References libMesh::TypeTensor< T >::_coords.
Referenced by libMesh::TypeTensor< T >::operator-=(), and libMesh::TypeTensor< T >::operator=().
 {
   for (unsigned int i=0; i<LIBMESH_DIM*LIBMESH_DIM; i++)
     _coords[i] -= p._coords[i];
 }
template<typename T > template<typename T2 > void libMesh::TypeTensor< T >::subtract_scaled (const TypeTensor< T2 > & p, const T factor) inline
Subtract a scaled value from this tensor without creating a temporary.
Definition at line 847 of file type_tensor.h.
References libMesh::TypeTensor< T >::_coords.
Referenced by libMesh::TypeTensor< T >::operator=(), and libMesh::HPCoarsenTest::select_refinement().
 {
   for (unsigned int i=0; i<LIBMESH_DIM*LIBMESH_DIM; i++)
     _coords[i] -= factor*p._coords[i];
 }
template<typename T > T libMesh::TypeTensor< T >::tr () const inline
Returns
The trace of the tensor.
Definition at line 1231 of file type_tensor.h.
References libMesh::TypeTensor< T >::_coords.
Referenced by libMesh::TypeTensor< T >::operator=().
 {
 #if LIBMESH_DIM == 1
   return _coords[0];
 #endif
 #if LIBMESH_DIM == 2
   return _coords[0] + _coords[3];
 #endif
 #if LIBMESH_DIM == 3
   return _coords[0] + _coords[4] + _coords[8];
 #endif
 }
template<typename T > TypeTensor< T > libMesh::TypeTensor< T >::transpose () const inline
Returns
The transpose of this tensor (with complex numbers not conjugated).
Definition at line 992 of file type_tensor.h.
References libMesh::TypeTensor< T >::_coords, and libMesh::TypeTensor< T >::TypeTensor().
Referenced by libMesh::TypeTensor< T >::operator=().
 {
 #if LIBMESH_DIM == 1
   return TypeTensor(_coords[0]);
 #endif
 #if LIBMESH_DIM == 2
   return TypeTensor(_coords[0],
                     _coords[2],
                     _coords[1],
                     _coords[3]);
 #endif
 #if LIBMESH_DIM == 3
   return TypeTensor(_coords[0],
                     _coords[3],
                     _coords[6],
                     _coords[1],
                     _coords[4],
                     _coords[7],
                     _coords[2],
                     _coords[5],
                     _coords[8]);
 #endif
 }
template<typename T > void libMesh::TypeTensor< T >::write_unformatted (std::ostream & out, const bool newline = true) const
Unformatted print to the stream out. Simply prints the elements of the tensor separated by spaces and newlines.
Definition at line 83 of file type_tensor.C.
 {
   libmesh_assert (out_stream);
   out_stream << std::setiosflags(std::ios::showpoint)
              << (*this)(0,0) << " "
              << (*this)(0,1) << " "
              << (*this)(0,2) << " ";
   if (newline)
     out_stream << '\n';
   out_stream << std::setiosflags(std::ios::showpoint)
              << (*this)(1,0) << " "
              << (*this)(1,1) << " "
              << (*this)(1,2) << " ";
   if (newline)
     out_stream << '\n';
   out_stream << std::setiosflags(std::ios::showpoint)
              << (*this)(2,0) << " "
              << (*this)(2,1) << " "
              << (*this)(2,2) << " ";
   if (newline)
     out_stream << '\n';
 }
template<typename T > void libMesh::TypeTensor< T >::zero () inline
Set all entries of the tensor to 0.
Definition at line 1248 of file type_tensor.h.
References libMesh::TypeTensor< T >::_coords.
Referenced by libMesh::TensorValue< T >::operator=(), and libMesh::TypeTensor< T >::operator=().
 {
   for (unsigned int i=0; i<LIBMESH_DIM*LIBMESH_DIM; i++)
     _coords[i] = 0.;
 }
Friends And Related Function Documentation
template<typename T> std::ostream& operator<< (std::ostream & os, const TypeTensor< T > & t) friend
Formatted print as above but supports the syntax:
std::cout << t << std::endl;
Definition at line 400 of file type_tensor.h.
   {
     t.print(os);
     return os;
   }
template<typename T> template<typename T2 > friend class TypeTensor friend
Definition at line 52 of file type_tensor.h.
Member Data Documentation
template<typename T> T libMesh::TypeTensor< T >::_coords[LIBMESH_DIM *LIBMESH_DIM] protected
The coordinates of the TypeTensor
Definition at line 417 of file type_tensor.h.
Referenced by libMesh::TypeTensor< T >::add(), libMesh::TypeTensor< T >::add_scaled(), libMesh::TypeTensor< T >::assign(), libMesh::TypeTensor< T >::contract(), libMesh::TypeTensor< T >::det(), libMesh::TypeTensor< T >::inverse(), libMesh::TypeTensor< T >::norm_sq(), libMesh::TypeTensor< T >::operator()(), libMesh::TypeTensor< T >::operator*(), libMesh::TypeTensor< T >::operator*=(), libMesh::TypeTensor< T >::operator+(), libMesh::TypeTensor< T >::operator-(), libMesh::TypeTensor< T >::operator/(), libMesh::TypeTensor< T >::operator/=(), libMesh::TypeTensor< T >::operator==(), libMesh::TypeTensor< T >::row(), libMesh::TypeTensor< T >::solve(), libMesh::TypeTensor< T >::subtract(), libMesh::TypeTensor< T >::subtract_scaled(), libMesh::TypeTensor< T >::tr(), libMesh::TypeTensor< T >::transpose(), libMesh::TypeTensor< T >::TypeTensor(), and libMesh::TypeTensor< T >::zero().
The documentation for this class was generated from the following files:
tensor_tools.h
type_tensor.h
type_tensor.C