libMesh: libMesh::ZeroFunction< Output > Class Template Reference
SomeWebsiteLogo
libMesh::ZeroFunction< Output > Class Template Reference
ConstFunction that simply returns 0.
#include <zero_function.h>
Public Member Functions
ZeroFunction ()
ZeroFunction (ZeroFunction &&)=default
ZeroFunction (const ZeroFunction &)=default
ZeroFunction & operator= (const ZeroFunction &)=default
ZeroFunction & operator= (ZeroFunction &&)=default
virtual ~ZeroFunction ()=default
virtual std::unique_ptr< FunctionBase< Output > > clone () const override
virtual Output operator() (const Point &, const Real=0) override
virtual void operator() (const Point &, const Real, DenseVector< Output > &output) override
void operator() (const Point &p, DenseVector< Output > &output)
virtual void init ()
virtual void clear ()
virtual Output component (unsigned int i, const Point &p, Real time=0.)
bool initialized () const
void set_is_time_dependent (bool is_time_dependent)
bool is_time_dependent () const
Protected Attributes
const FunctionBase * _master
bool _initialized
bool _is_time_dependent
Detailed Description
template<typename Output = Number>
class libMesh::ZeroFunction< Output >
ConstFunction that simply returns 0.
ConstFunction that simply returns 0.
Author
Roy Stogner
Date
2012
Definition at line 36 of file zero_function.h.
Constructor & Destructor Documentation
ZeroFunction() [1/3]
template<typename Output = Number> libMesh::ZeroFunction< Output >::ZeroFunction () inline
Definition at line 39 of file zero_function.h.
 : ConstFunction<Output>(0) {}
ZeroFunction() [2/3]
template<typename Output = Number> libMesh::ZeroFunction< Output >::ZeroFunction (ZeroFunction< Output > &&) default
The 5 special functions can be defaulted for this class.
ZeroFunction() [3/3]
template<typename Output = Number> libMesh::ZeroFunction< Output >::ZeroFunction (const ZeroFunction< Output > &) default
~ZeroFunction()
template<typename Output = Number> virtual libMesh::ZeroFunction< Output >::~ZeroFunction () virtual default
Member Function Documentation
clear()
template<typename Output = Number> virtual void libMesh::FunctionBase< Output >::clear () inline virtual inherited
Clears the function.
Reimplemented in libMesh::ParsedFunction< Output, OutputGradient >, libMesh::ParsedFunction< T >, libMesh::MeshFunction, and libMesh::AnalyticFunction< Output >.
Definition at line 92 of file function_base.h.
 {}
clone()
template<typename Output = Number> virtual std::unique_ptr<FunctionBase<Output> > libMesh::ZeroFunction< Output >::clone () const inline override virtual
Returns
A new copy of the function.
The new copy should be as "deep" as necessary to allow independent destruction and simultaneous evaluations of the copies in different threads.
Reimplemented from libMesh::ConstFunction< Output >.
Definition at line 50 of file zero_function.h.
   {
     return libmesh_make_unique<ZeroFunction<Output>>();
   }
component()
template<typename Output > Output libMesh::FunctionBase< Output >::component (unsigned int i, const Point & p, Real time = 0.) inline virtual inherited
Returns
The vector component i at coordinate p and time time.
Note
Subclasses aren't required to override this, since the default implementation is based on the full vector evaluation, which is often correct.
Subclasses are recommended to override this, since the default implementation is based on a vector evaluation, which is usually unnecessarily inefficient.
Reimplemented in libMesh::CompositeFunction< Output >, libMesh::ParsedFunction< Output, OutputGradient >, libMesh::ParsedFunction< T >, and libMesh::WrappedFunction< Output >.
Definition at line 228 of file function_base.h.
 {
   DenseVector<Output> outvec(i+1);
   (*this)(p, time, outvec);
   return outvec(i);
 }
init()
template<typename Output = Number> virtual void libMesh::FunctionBase< Output >::init () inline virtual inherited
The actual initialization process.
Reimplemented in libMesh::ParsedFunction< Output, OutputGradient >, libMesh::ParsedFunction< T >, libMesh::MeshFunction, and libMesh::AnalyticFunction< Output >.
Definition at line 87 of file function_base.h.
Referenced by libMesh::MeshFunction::clone().
 {}
initialized()
template<typename Output > bool libMesh::FunctionBase< Output >::initialized () const inline inherited
Returns
true when this object is properly initialized and ready for use, false otherwise.
Definition at line 206 of file function_base.h.
 {
   return (this->_initialized);
 }
is_time_dependent()
template<typename Output > bool libMesh::FunctionBase< Output >::is_time_dependent () const inline inherited
Returns
true when the function this object represents is actually time-dependent, false otherwise.
Definition at line 220 of file function_base.h.
Referenced by libMesh::CompositeFunction< Output >::attach_subfunction().
 {
   return (this->_is_time_dependent);
 }
operator()() [1/3]
template<typename Output = Number> virtual Output libMesh::ConstFunction< Output >::operator() (const Point & p, const Real time = 0) inline override virtual inherited
Returns
The scalar function value at coordinate p and time time, which defaults to zero.
Pure virtual, so you have to override it.
Implements libMesh::FunctionBase< Output >.
Definition at line 61 of file const_function.h.
References libMesh::ConstFunction< Output >::_c.
   { return _c; }
operator()() [2/3]
template<typename Output = Number> virtual void libMesh::ConstFunction< Output >::operator() (const Point & p, const Real time, DenseVector< Output > & output) inline override virtual inherited
Evaluation function for time-dependent vector-valued functions. Sets output values in the passed-in output DenseVector.
Pure virtual, so you have to override it.
Implements libMesh::FunctionBase< Output >.
Definition at line 65 of file const_function.h.
References libMesh::ConstFunction< Output >::_c, and libMesh::DenseVector< T >::size().
   {
     unsigned int size = output.size();
     for (unsigned int i=0; i != size; ++i)
       output(i) = _c;
   }
operator()() [3/3]
template<typename Output> void libMesh::FunctionBase< Output >::operator() (const Point & p, DenseVector< Output > & output) inline inherited
Evaluation function for time-independent vector-valued functions. Sets output values in the passed-in output DenseVector.
Definition at line 241 of file function_base.h.
 {
   // Call the time-dependent function with t=0.
   this->operator()(p, 0., output);
 }
operator=() [1/2]
template<typename Output = Number> ZeroFunction& libMesh::ZeroFunction< Output >::operator= (const ZeroFunction< Output > &) default
operator=() [2/2]
template<typename Output = Number> ZeroFunction& libMesh::ZeroFunction< Output >::operator= (ZeroFunction< Output > &&) default
set_is_time_dependent()
template<typename Output > void libMesh::FunctionBase< Output >::set_is_time_dependent (bool is_time_dependent) inline inherited
Function to set whether this is a time-dependent function or not. This is intended to be only used by subclasses who cannot natively determine time-dependence. In such a case, this function should be used immediately following construction.
Definition at line 213 of file function_base.h.
 {
   this->_is_time_dependent = is_time_dependent;
 }
Member Data Documentation
_initialized
template<typename Output = Number> bool libMesh::FunctionBase< Output >::_initialized protected inherited
When init() was called so that everything is ready for calls to operator() (...), then this bool is true.
Definition at line 180 of file function_base.h.
Referenced by libMesh::AnalyticFunction< Output >::AnalyticFunction(), libMesh::ConstFunction< Output >::ConstFunction(), and libMesh::WrappedFunction< Output >::WrappedFunction().
_is_time_dependent
template<typename Output = Number> bool libMesh::FunctionBase< Output >::_is_time_dependent protected inherited
Cache whether or not this function is actually time-dependent.
Definition at line 185 of file function_base.h.
Referenced by libMesh::CompositeFunction< Output >::attach_subfunction(), and libMesh::ConstFunction< Output >::ConstFunction().
_master
template<typename Output = Number> const FunctionBase* libMesh::FunctionBase< Output >::_master protected inherited
Const pointer to our master, initialized to nullptr. There may be cases where multiple functions are required, but to save memory, one master handles some centralized data.
Definition at line 174 of file function_base.h.
The documentation for this class was generated from the following file:
zero_function.h