libMesh: libMesh::TransientRBAssemblyExpansion Class Reference
SomeWebsiteLogo
libMesh::TransientRBAssemblyExpansion Class Reference
#include <transient_rb_assembly_expansion.h>
Public Member Functions
TransientRBAssemblyExpansion ()
void perform_M_interior_assembly (unsigned int q, FEMContext &context)
void perform_M_boundary_assembly (unsigned int q, FEMContext &context)
unsigned int get_n_M_terms () const
void attach_M_assembly (ElemAssembly *A_q_assembly)
ElemAssembly & get_M_assembly (unsigned int q)
void perform_A_interior_assembly (unsigned int q, FEMContext &context)
void perform_A_boundary_assembly (unsigned int q, FEMContext &context)
void perform_F_interior_assembly (unsigned int q, FEMContext &context)
void perform_F_boundary_assembly (unsigned int q, FEMContext &context)
void perform_output_interior_assembly (unsigned int output_index, unsigned int q_l, FEMContext &context)
void perform_output_boundary_assembly (unsigned int output_index, unsigned int q_l, FEMContext &context)
unsigned int get_n_A_terms () const
unsigned int get_n_F_terms () const
unsigned int get_n_outputs () const
unsigned int get_n_output_terms (unsigned int output_index) const
void attach_A_assembly (ElemAssembly *Aq_assembly)
void attach_multiple_A_assembly (std::vector< ElemAssembly * > Aq_assembly)
void attach_F_assembly (ElemAssembly *Fq_assembly)
void attach_multiple_F_assembly (std::vector< ElemAssembly * > Fq_assembly)
virtual void attach_output_assembly (std::vector< ElemAssembly * > output_assembly)
virtual void attach_output_assembly (ElemAssembly *output_assembly)
ElemAssembly & get_A_assembly (unsigned int q)
ElemAssembly & get_F_assembly (unsigned int q)
ElemAssembly & get_output_assembly (unsigned int output_index, unsigned int q_l)
Static Public Member Functions
static std::string get_info ()
static void print_info (std::ostream &out=libMesh::out)
static unsigned int n_objects ()
static void enable_print_counter_info ()
static void disable_print_counter_info ()
Static Protected Attributes
static Threads::atomic< unsigned int > _n_objects
static Threads::spin_mutex _mutex
static bool _enable_print_counter = true
Private Attributes
std::vector< ElemAssembly * > _M_assembly_vector
Detailed Description
This extends RBAssemblyExpansion to provide an assembly expansion for the case of time-dependent PDEs. This just requires an extra set of ElemAssembly functors for the time-derivative term.
Author
David J. Knezevic
Date
2011
Definition at line 40 of file transient_rb_assembly_expansion.h.
Constructor & Destructor Documentation
libMesh::TransientRBAssemblyExpansion::TransientRBAssemblyExpansion ()
Constructor.
Member Function Documentation
void libMesh::RBAssemblyExpansion::attach_A_assembly (ElemAssembly * Aq_assembly) inherited
Attach ElemAssembly object for the left-hand side (both interior and boundary assembly).
void libMesh::RBAssemblyExpansion::attach_F_assembly (ElemAssembly * Fq_assembly) inherited
Attach ElemAssembly object for the right-hand side (both interior and boundary assembly).
void libMesh::TransientRBAssemblyExpansion::attach_M_assembly (ElemAssembly * A_q_assembly)
Attach ElemAssembly object for the time-derivative (both interior and boundary assembly).
void libMesh::RBAssemblyExpansion::attach_multiple_A_assembly (std::vector< ElemAssembly * > Aq_assembly) inherited
Attach multiple ElemAssembly objects for the left-hand side (both interior and boundary assembly).
void libMesh::RBAssemblyExpansion::attach_multiple_F_assembly (std::vector< ElemAssembly * > Fq_assembly) inherited
Attach multiple ElemAssembly objects for the right-hand side (both interior and boundary assembly).
virtual void libMesh::RBAssemblyExpansion::attach_output_assembly (std::vector< ElemAssembly * > output_assembly) virtual inherited
Attach ElemAssembly object for an output (both interior and boundary assembly). In this case we pass in vector arguments to allow for Q_l > 1.
virtual void libMesh::RBAssemblyExpansion::attach_output_assembly (ElemAssembly * output_assembly) virtual inherited
Attach ElemAssembly object for an output (both interior and boundary assembly). This function provides simpler syntax in the case that Q_l = 1; we do not need to use a vector in this case.
void libMesh::ReferenceCounter::disable_print_counter_info () static inherited
Definition at line 106 of file reference_counter.C.
References libMesh::ReferenceCounter::_enable_print_counter.
Referenced by libMesh::LibMeshInit::LibMeshInit().
 {
   _enable_print_counter = false;
   return;
 }
void libMesh::ReferenceCounter::enable_print_counter_info () static inherited
Methods to enable/disable the reference counter output from print_info()
Definition at line 100 of file reference_counter.C.
References libMesh::ReferenceCounter::_enable_print_counter.
 {
   _enable_print_counter = true;
   return;
 }
ElemAssembly& libMesh::RBAssemblyExpansion::get_A_assembly (unsigned int q) inherited
Return a reference to the specified A_assembly object.
ElemAssembly& libMesh::RBAssemblyExpansion::get_F_assembly (unsigned int q) inherited
Return a reference to the specified F_assembly object.
std::string libMesh::ReferenceCounter::get_info () static inherited
Gets a string containing the reference information.
Definition at line 47 of file reference_counter.C.
References libMesh::Quality::name().
 {
 #if defined(LIBMESH_ENABLE_REFERENCE_COUNTING) && defined(DEBUG)
   std::ostringstream oss;
   oss << '\n'
       << " ---------------------------------------------------------------------------- \n"
       << "| Reference count information                                                |\n"
       << " ---------------------------------------------------------------------------- \n";
   for (Counts::iterator it = _counts.begin();
        it != _counts.end(); ++it)
     {
       const std::string name(it->first);
       const unsigned int creations    = it->second.first;
       const unsigned int destructions = it->second.second;
       oss << "| " << name << " reference count information:\n"
           << "|  Creations:    " << creations    << '\n'
           << "|  Destructions: " << destructions << '\n';
     }
   oss << " ---------------------------------------------------------------------------- \n";
   return oss.str();
 #else
   return "";
 #endif
 }
ElemAssembly& libMesh::TransientRBAssemblyExpansion::get_M_assembly (unsigned int q)
Return a reference to the specified M_assembly object.
unsigned int libMesh::RBAssemblyExpansion::get_n_A_terms () const inherited
Get Q_a, the number of terms in the affine expansion for the bilinear form.
unsigned int libMesh::RBAssemblyExpansion::get_n_F_terms () const inherited
Get Q_f, the number of terms in the affine expansion for the right-hand side.
unsigned int libMesh::TransientRBAssemblyExpansion::get_n_M_terms () const
Get Q_m, the number of terms in the affine expansion for the bilinear form.
unsigned int libMesh::RBAssemblyExpansion::get_n_output_terms (unsigned int output_index) const inherited
Get the number of affine terms associated with the specified output.
unsigned int libMesh::RBAssemblyExpansion::get_n_outputs () const inherited
Get n_outputs, the number output functionals.
ElemAssembly& libMesh::RBAssemblyExpansion::get_output_assembly (unsigned int output_index, unsigned int q_l) inherited
Return a reference to the specified output assembly object.
static unsigned int libMesh::ReferenceCounter::n_objects () inline static inherited
Prints the number of outstanding (created, but not yet destroyed) objects.
Definition at line 75 of file reference_counter.h.
References libMesh::ReferenceCounter::_n_objects.
Referenced by libMesh::LibMeshInit::~LibMeshInit().
   { return _n_objects; }
void libMesh::RBAssemblyExpansion::perform_A_boundary_assembly (unsigned int q, FEMContext & context) inherited
Perform the specified A boundary assembly.
void libMesh::RBAssemblyExpansion::perform_A_interior_assembly (unsigned int q, FEMContext & context) inherited
Perform the specified A interior assembly.
void libMesh::RBAssemblyExpansion::perform_F_boundary_assembly (unsigned int q, FEMContext & context) inherited
Perform the specified F boundary assembly.
void libMesh::RBAssemblyExpansion::perform_F_interior_assembly (unsigned int q, FEMContext & context) inherited
Perform the specified F interior assembly.
void libMesh::TransientRBAssemblyExpansion::perform_M_boundary_assembly (unsigned int q, FEMContext & context)
Perform the specified M boundary assembly.
void libMesh::TransientRBAssemblyExpansion::perform_M_interior_assembly (unsigned int q, FEMContext & context)
Perform the specified M interior assembly.
void libMesh::RBAssemblyExpansion::perform_output_boundary_assembly (unsigned int output_index, unsigned int q_l, FEMContext & context) inherited
Perform the specified output assembly.
void libMesh::RBAssemblyExpansion::perform_output_interior_assembly (unsigned int output_index, unsigned int q_l, FEMContext & context) inherited
Perform the specified output assembly.
void libMesh::ReferenceCounter::print_info (std::ostream & out = libMesh::out) static inherited
Prints the reference information, by default to libMesh::out.
Definition at line 95 of file reference_counter.C.
Referenced by libMesh::LibMeshInit::~LibMeshInit().
 {}
Member Data Documentation
bool libMesh::ReferenceCounter::_enable_print_counter = true static protected inherited
Flag to control whether reference count information is printed when print_info is called.
Definition at line 133 of file reference_counter.h.
Referenced by libMesh::ReferenceCounter::disable_print_counter_info(), and libMesh::ReferenceCounter::enable_print_counter_info().
std::vector<ElemAssembly *> libMesh::TransientRBAssemblyExpansion::_M_assembly_vector private
Vectors storing the function pointers to the assembly routines for the time-derivative operators, both interior and boundary assembly.
Definition at line 85 of file transient_rb_assembly_expansion.h.
Threads::spin_mutex libMesh::ReferenceCounter::_mutex static protected inherited
Mutual exclusion object to enable thread-safe reference counting.
Definition at line 127 of file reference_counter.h.
Threads::atomic< unsigned int > libMesh::ReferenceCounter::_n_objects static protected inherited
The number of objects. Print the reference count information when the number returns to 0.
Definition at line 122 of file reference_counter.h.
Referenced by libMesh::ReferenceCounter::n_objects(), libMesh::ReferenceCounter::ReferenceCounter(), and libMesh::ReferenceCounter::~ReferenceCounter().
The documentation for this class was generated from the following file:
transient_rb_assembly_expansion.h