libMesh: libMesh::LaspackVector< T > Class Template Reference
SomeWebsiteLogo
libMesh::LaspackVector< T > Class Template Reference
#include <laspack_matrix.h>
Public Member Functions
LaspackVector (const Parallel::Communicator &comm, const ParallelType=AUTOMATIC)
LaspackVector (const Parallel::Communicator &comm, const numeric_index_type n, const ParallelType=AUTOMATIC)
LaspackVector (const Parallel::Communicator &comm, const numeric_index_type n, const numeric_index_type n_local, const ParallelType=AUTOMATIC)
LaspackVector (const Parallel::Communicator &comm, const numeric_index_type N, const numeric_index_type n_local, const std::vector< numeric_index_type > &ghost, const ParallelType=AUTOMATIC)
LaspackVector< T > & operator= (const LaspackVector< T > &v)
LaspackVector (LaspackVector &&)=delete
LaspackVector (const LaspackVector &)=delete
LaspackVector & operator= (LaspackVector &&)=delete
virtual ~LaspackVector ()
virtual void close () override
virtual void clear () override
virtual void zero () override
virtual std::unique_ptr< NumericVector< T > > zero_clone () const override
virtual std::unique_ptr< NumericVector< T > > clone () const override
virtual void init (const numeric_index_type N, const numeric_index_type n_local, const bool fast=false, const ParallelType ptype=AUTOMATIC) override
virtual void init (const numeric_index_type N, const bool fast=false, const ParallelType ptype=AUTOMATIC) override
virtual void init (const numeric_index_type N, const numeric_index_type n_local, const std::vector< numeric_index_type > &ghost, const bool fast=false, const ParallelType=AUTOMATIC) override
virtual void init (const NumericVector< T > &other, const bool fast=false) override
virtual NumericVector< T > & operator= (const T s) override
virtual NumericVector< T > & operator= (const NumericVector< T > &v) override
virtual NumericVector< T > & operator= (const std::vector< T > &v) override
virtual Real min () const override
virtual Real max () const override
virtual T sum () const override
virtual Real l1_norm () const override
virtual Real l2_norm () const override
virtual Real linfty_norm () const override
virtual numeric_index_type size () const override
virtual numeric_index_type local_size () const override
virtual numeric_index_type first_local_index () const override
virtual numeric_index_type last_local_index () const override
virtual T operator() (const numeric_index_type i) const override
virtual NumericVector< T > & operator+= (const NumericVector< T > &v) override
virtual NumericVector< T > & operator-= (const NumericVector< T > &v) override
virtual NumericVector< T > & operator/= (const NumericVector< T > &v) override
virtual void reciprocal () override
virtual void conjugate () override
virtual void set (const numeric_index_type i, const T value) override
virtual void add (const numeric_index_type i, const T value) override
virtual void add (const T s) override
virtual void add (const NumericVector< T > &v) override
virtual void add (const T a, const NumericVector< T > &v) override
virtual void add_vector (const NumericVector< T > &v, const SparseMatrix< T > &A) override
virtual void add_vector_transpose (const NumericVector< T > &v, const SparseMatrix< T > &A) override
virtual void scale (const T factor) override
virtual void abs () override
virtual T dot (const NumericVector< T > &v) const override
virtual void localize (std::vector< T > &v_local) const override
virtual void localize (NumericVector< T > &v_local) const override
virtual void localize (NumericVector< T > &v_local, const std::vector< numeric_index_type > &send_list) const override
virtual void localize (std::vector< T > &v_local, const std::vector< numeric_index_type > &indices) const override
virtual void localize (const numeric_index_type first_local_idx, const numeric_index_type last_local_idx, const std::vector< numeric_index_type > &send_list) override
virtual void localize_to_one (std::vector< T > &v_local, const processor_id_type proc_id=0) const override
virtual void pointwise_mult (const NumericVector< T > &vec1, const NumericVector< T > &vec2) override
virtual void swap (NumericVector< T > &v) override
virtual bool initialized () const
ParallelType type () const
ParallelType & type ()
virtual bool closed () const
virtual Real subset_l1_norm (const std::set< numeric_index_type > &indices) const
virtual Real subset_l2_norm (const std::set< numeric_index_type > &indices) const
virtual Real subset_linfty_norm (const std::set< numeric_index_type > &indices) const
virtual T el (const numeric_index_type i) const
virtual void get (const std::vector< numeric_index_type > &index, T *values) const
void get (const std::vector< numeric_index_type > &index, std::vector< T > &values) const
NumericVector< T > & operator*= (const T a)
NumericVector< T > & operator/= (const T a)
virtual void add_vector (const T *v, const std::vector< numeric_index_type > &dof_indices)
void add_vector (const std::vector< T > &v, const std::vector< numeric_index_type > &dof_indices)
virtual void add_vector (const NumericVector< T > &v, const std::vector< numeric_index_type > &dof_indices)
void add_vector (const DenseVector< T > &v, const std::vector< numeric_index_type > &dof_indices)
void add_vector (const NumericVector< T > &v, const ShellMatrix< T > &A)
virtual void insert (const T *v, const std::vector< numeric_index_type > &dof_indices)
void insert (const std::vector< T > &v, const std::vector< numeric_index_type > &dof_indices)
virtual void insert (const NumericVector< T > &v, const std::vector< numeric_index_type > &dof_indices)
void insert (const DenseVector< T > &v, const std::vector< numeric_index_type > &dof_indices)
void insert (const DenseSubVector< T > &v, const std::vector< numeric_index_type > &dof_indices)
virtual int compare (const NumericVector< T > &other_vector, const Real threshold=TOLERANCE) const
virtual int local_relative_compare (const NumericVector< T > &other_vector, const Real threshold=TOLERANCE) const
virtual int global_relative_compare (const NumericVector< T > &other_vector, const Real threshold=TOLERANCE) const
virtual void print (std::ostream &os=libMesh::out) const
template<>
void print (std::ostream &os) const
virtual void print_global (std::ostream &os=libMesh::out) const
template<>
void print_global (std::ostream &os) const
virtual void print_matlab (const std::string &="") const
virtual void create_subvector (NumericVector< T > &, const std::vector< numeric_index_type > &) const
const Parallel::Communicator & comm () const
processor_id_type n_processors () const
processor_id_type processor_id () const
Static Public Member Functions
static std::unique_ptr< NumericVector< T > > build (const Parallel::Communicator &comm, const SolverPackage solver_package=libMesh::default_solver_package())
static std::string get_info ()
static void print_info (std::ostream &out=libMesh::out)
static unsigned int n_objects ()
static void enable_print_counter_info ()
static void disable_print_counter_info ()
Protected Types
typedef std::map< std::string, std::pair< unsigned int, unsigned int > > Counts
Protected Member Functions
void increment_constructor_count (const std::string &name)
void increment_destructor_count (const std::string &name)
Protected Attributes
bool _is_closed
bool _is_initialized
ParallelType _type
const Parallel::Communicator & _communicator
Static Protected Attributes
static Counts _counts
static Threads::atomic< unsigned int > _n_objects
static Threads::spin_mutex _mutex
static bool _enable_print_counter = true
Private Attributes
QVector _vec
Friends
class LaspackLinearSolver< T >
Detailed Description
template<typename T>
class libMesh::LaspackVector< T >
This class provides a nice interface to the Laspack C-based data structures for serial vectors. All overridden virtual functions are documented in numeric_vector.h.
Author
Benjamin S. Kirk
Date
2002
Definition at line 42 of file laspack_matrix.h.
Member Typedef Documentation
Counts
typedef std::map<std::string, std::pair<unsigned int, unsigned int> > libMesh::ReferenceCounter::Counts protected inherited
Data structure to log the information. The log is identified by the class name.
Definition at line 117 of file reference_counter.h.
Constructor & Destructor Documentation
LaspackVector() [1/6]
template<typename T > libMesh::LaspackVector< T >::LaspackVector (const Parallel::Communicator & comm, const ParallelType ptype = AUTOMATIC) inline explicit
Dummy-Constructor. Dimension=0
Definition at line 248 of file laspack_vector.h.
References libMesh::NumericVector< T >::_type.
   : NumericVector<T>(comm, ptype)
 {
   this->_type = ptype;
 }
LaspackVector() [2/6]
template<typename T > libMesh::LaspackVector< T >::LaspackVector (const Parallel::Communicator & comm, const numeric_index_type n, const ParallelType ptype = AUTOMATIC) inline explicit
Constructor. Set dimension to n and initialize all elements with zero.
Definition at line 259 of file laspack_vector.h.
References libMesh::LaspackVector< T >::init().
   : NumericVector<T>(comm, ptype)
 {
   this->init(n, n, false, ptype);
 }
LaspackVector() [3/6]
template<typename T > libMesh::LaspackVector< T >::LaspackVector (const Parallel::Communicator & comm, const numeric_index_type n, const numeric_index_type n_local, const ParallelType ptype = AUTOMATIC) inline
Constructor. Set local dimension to n_local, the global dimension to n, and initialize all elements with zero.
Definition at line 271 of file laspack_vector.h.
References libMesh::LaspackVector< T >::init().
   : NumericVector<T>(comm, ptype)
 {
   this->init(n, n_local, false, ptype);
 }
LaspackVector() [4/6]
template<typename T > libMesh::LaspackVector< T >::LaspackVector (const Parallel::Communicator & comm, const numeric_index_type N, const numeric_index_type n_local, const std::vector< numeric_index_type > & ghost, const ParallelType ptype = AUTOMATIC) inline
Constructor. Set local dimension to n_local, the global dimension to n, but additionally reserve memory for the indices specified by the ghost argument.
Definition at line 284 of file laspack_vector.h.
References libMesh::LaspackVector< T >::init().
   : NumericVector<T>(comm, ptype)
 {
   this->init(N, n_local, ghost, false, ptype);
 }
LaspackVector() [5/6]
template<typename T> libMesh::LaspackVector< T >::LaspackVector (LaspackVector< T > &&) delete
This class manages a C-style struct (QVector) manually, so we don't want to allow any automatic copy/move functions to be generated, and we can't default the destructor.
LaspackVector() [6/6]
template<typename T> libMesh::LaspackVector< T >::LaspackVector (const LaspackVector< T > &) delete
~LaspackVector()
template<typename T > libMesh::LaspackVector< T >::~LaspackVector () inline virtual
Definition at line 298 of file laspack_vector.h.
 {
   this->clear ();
 }
Member Function Documentation
abs()
template<typename T > void libMesh::LaspackVector< T >::abs () override virtual
Sets for each entry in the vector.
Implements libMesh::NumericVector< T >.
Definition at line 237 of file laspack_vector.C.
References std::abs(), and libMesh::initialized().
 {
   libmesh_assert (this->initialized());
   const numeric_index_type n = this->size();
   for (numeric_index_type i=0; i!=n; ++i)
     this->set(i,std::abs((*this)(i)));
 }
add() [1/4]
template<typename T > void libMesh::LaspackVector< T >::add (const numeric_index_type i, const T value) inline override virtual
Adds value to each entry of the vector.
Implements libMesh::NumericVector< T >.
Definition at line 510 of file laspack_vector.h.
References libMesh::initialized(), and value.
 {
   libmesh_assert (this->initialized());
   libmesh_assert_less (i, this->size());
   V_AddCmp (&_vec, i+1, value);
 #ifndef NDEBUG
   this->_is_closed = false;
 #endif
 }
add() [2/4]
template<typename T > void libMesh::LaspackVector< T >::add (const T s) override virtual
Adds s to each entry of the vector,
Implements libMesh::NumericVector< T >.
Definition at line 156 of file laspack_vector.C.
 {
   const numeric_index_type n = this->size();
   for (numeric_index_type i=0; i<n; i++)
     this->add (i, v);
 #ifndef NDEBUG
   this->_is_closed = false;
 #endif
 }
add() [3/4]
template<typename T > void libMesh::LaspackVector< T >::add (const NumericVector< T > & v) override virtual
Adds v to this, . Equivalent to calling operator+=().
Implements libMesh::NumericVector< T >.
Definition at line 172 of file laspack_vector.C.
 {
   this->add (1., v);
 }
add() [4/4]
template<typename T > void libMesh::LaspackVector< T >::add (const T a, const NumericVector< T > & v) override virtual
Vector addition with a scalar multiple, . Equivalent to calling operator+=().
Implements libMesh::NumericVector< T >.
Definition at line 180 of file laspack_vector.C.
References libMesh::LaspackVector< T >::size().
 {
   // Make sure the vector passed in is really a LaspackVector
   const LaspackVector * v = cast_ptr<const LaspackVector *>(&v_in);
 #ifndef NDEBUG
   const bool was_closed = this->_is_closed;
 #endif
   libmesh_assert(v);
   libmesh_assert_equal_to (this->size(), v->size());
   for (numeric_index_type i=0; i<v->size(); i++)
     this->add (i, a*(*v)(i));
 #ifndef NDEBUG
   this->_is_closed = was_closed;
 #endif
 }
add_vector() [1/6]
template<typename T > void libMesh::LaspackVector< T >::add_vector (const NumericVector< T > & v, const SparseMatrix< T > & A) override virtual
Computes , i.e. adds the product of a SparseMatrix A and a NumericVector v to this.
Implements libMesh::NumericVector< T >.
Definition at line 203 of file laspack_vector.C.
References libMesh::LaspackVector< T >::_vec.
 {
   // Make sure the data passed in are really in Laspack types
   const LaspackVector<T> * vec = cast_ptr<const LaspackVector<T> *>(&vec_in);
   const LaspackMatrix<T> * mat = cast_ptr<const LaspackMatrix<T> *>(&mat_in);
   libmesh_assert(vec);
   libmesh_assert(mat);
   // += mat*vec
   AddAsgn_VV (&_vec, Mul_QV(const_cast<QMatrix*>(&mat->_QMat),
                             const_cast<QVector*>(&vec->_vec)));
 }
add_vector() [2/6]
template<typename T> void libMesh::NumericVector< T >::add_vector (const T * v, const std::vector< numeric_index_type > & dof_indices) virtual inherited
Computes , where v is a pointer and each dof_indices[i] specifies where to add value v[i]. This should be overridden in subclasses for efficiency.
Reimplemented in libMesh::PetscVector< T >, and libMesh::EpetraVector< T >.
Definition at line 362 of file numeric_vector.C.
Referenced by libMesh::LinearImplicitSystem::assembly(), libMesh::NewmarkSystem::update_rhs(), and libMesh::SparseMatrix< ValOut >::vector_mult_add().
 {
   for (std::size_t i=0, n = dof_indices.size(); i != n; i++)
     this->add (dof_indices[i], v[i]);
 }
add_vector() [3/6]
template<typename T> void libMesh::NumericVector< T >::add_vector (const std::vector< T > & v, const std::vector< numeric_index_type > & dof_indices) inline inherited
Computes , where v is a std::vector and each dof_indices[i] specifies where to add value v[i].
Definition at line 835 of file numeric_vector.h.
 {
   libmesh_assert(v.size() == dof_indices.size());
   if (!v.empty())
     this->add_vector(v.data(), dof_indices);
 }
add_vector() [4/6]
template<typename T> void libMesh::NumericVector< T >::add_vector (const NumericVector< T > & v, const std::vector< numeric_index_type > & dof_indices) virtual inherited
Computes , where v is a NumericVector and each dof_indices[i] specifies where to add value v(i).
Definition at line 372 of file numeric_vector.C.
 {
   const std::size_t n = dof_indices.size();
   libmesh_assert_equal_to(v.size(), n);
   for (numeric_index_type i=0; i != n; i++)
     this->add (dof_indices[i], v(i));
 }
add_vector() [5/6]
template<typename T> void libMesh::NumericVector< T >::add_vector (const DenseVector< T > & v, const std::vector< numeric_index_type > & dof_indices) inline inherited
Computes , where v is a DenseVector and each dof_indices[i] specifies where to add value v(i).
Definition at line 847 of file numeric_vector.h.
 {
   libmesh_assert(v.size() == dof_indices.size());
   if (!v.empty())
     this->add_vector(&v(0), dof_indices);
 }
add_vector() [6/6]
template<typename T> void libMesh::NumericVector< T >::add_vector (const NumericVector< T > & v, const ShellMatrix< T > & A) inherited
Computes , i.e. adds the product of a ShellMatrix A and a NumericVector v to this.
Definition at line 384 of file numeric_vector.C.
 {
   a.vector_mult_add(*this,v);
 }
add_vector_transpose()
template<typename T > void libMesh::LaspackVector< T >::add_vector_transpose (const NumericVector< T > & v, const SparseMatrix< T > & A) override virtual
Computes , i.e. adds the product of the transpose of a SparseMatrix A and a NumericVector v to this.
Implements libMesh::NumericVector< T >.
Definition at line 220 of file laspack_vector.C.
 {
   libmesh_not_implemented();
 }
build()
template<typename T > std::unique_ptr< NumericVector< T > > libMesh::NumericVector< T >::build (const Parallel::Communicator & comm, const SolverPackage solver_package = libMesh::default_solver_package()) static inherited
Builds a NumericVector on the processors in communicator comm using the linear solver package specified by solver_package
Definition at line 48 of file numeric_vector.C.
Referenced by libMesh::ExactSolution::_compute_error(), libMesh::UniformRefinementEstimator::_estimate_error(), libMesh::System::add_vector(), libMesh::EquationSystems::build_parallel_elemental_solution_vector(), libMesh::EquationSystems::build_parallel_solution_vector(), libMesh::System::calculate_norm(), libMesh::AdjointRefinementEstimator::estimate_error(), libMesh::ExactErrorEstimator::estimate_error(), and libMesh::CondensedEigenSystem::get_eigenpair().
 {
   // Build the appropriate vector
   switch (solver_package)
     {
 #ifdef LIBMESH_HAVE_LASPACK
     case LASPACK_SOLVERS:
       return libmesh_make_unique<LaspackVector<T>>(comm, AUTOMATIC);
 #endif
 #ifdef LIBMESH_HAVE_PETSC
     case PETSC_SOLVERS:
       return libmesh_make_unique<PetscVector<T>>(comm, AUTOMATIC);
 #endif
 #ifdef LIBMESH_TRILINOS_HAVE_EPETRA
     case TRILINOS_SOLVERS:
       return libmesh_make_unique<EpetraVector<T>>(comm, AUTOMATIC);
 #endif
 #ifdef LIBMESH_HAVE_EIGEN
     case EIGEN_SOLVERS:
       return libmesh_make_unique<EigenSparseVector<T>>(comm, AUTOMATIC);
 #endif
     default:
       return libmesh_make_unique<DistributedVector<T>>(comm, AUTOMATIC);
     }
 }
clear()
template<typename T > void libMesh::LaspackVector< T >::clear () inline override virtual
Restores the NumericVector<T> to a pristine state.
Reimplemented from libMesh::NumericVector< T >.
Definition at line 394 of file laspack_vector.h.
References libMesh::libMeshPrivateData::_is_initialized, and libMesh::initialized().
 {
   if (this->initialized())
     {
       V_Destr (&_vec);
     }
   this->_is_initialized = false;
 #ifndef NDEBUG
   this->_is_closed = false;
 #endif
 }
clone()
template<typename T > std::unique_ptr< NumericVector< T > > libMesh::LaspackVector< T >::clone () const inline override virtual
Returns
A copy of this vector wrapped in a smart pointer.
Note
This must be overridden in the derived classes.
Implements libMesh::NumericVector< T >.
Definition at line 435 of file laspack_vector.h.
References libMesh::NumericVector< T >::init().
 {
   NumericVector<T> * cloned_vector = new LaspackVector<T>(this->comm());
   cloned_vector->init(*this, true);
   *cloned_vector = *this;
   return std::unique_ptr<NumericVector<T>>(cloned_vector);
 }
close()
template<typename T > void libMesh::LaspackVector< T >::close () inline override virtual
Calls the NumericVector's internal assembly routines, ensuring that the values are consistent across processors.
Implements libMesh::NumericVector< T >.
Definition at line 381 of file laspack_vector.h.
References libMesh::initialized().
 {
   libmesh_assert (this->initialized());
 #ifndef NDEBUG
   this->_is_closed = true;
 #endif
 }
closed()
template<typename T> virtual bool libMesh::NumericVector< T >::closed () const inline virtual inherited
Returns
true if the vector is closed and ready for computation, false otherwise.
Definition at line 165 of file numeric_vector.h.
Referenced by libMesh::DofMap::enforce_adjoint_constraints_exactly(), libMesh::DofMap::enforce_constraints_exactly(), libMesh::DofMap::max_constraint_error(), libMesh::EigenSparseVector< T >::operator=(), libMesh::LaspackVector< T >::operator=(), and libMesh::PetscVector< T >::operator=().
 { return _is_closed; }
comm()
const Parallel::Communicator& libMesh::ParallelObject::comm () const inline inherited
Returns
A reference to the Parallel::Communicator object used by this mesh.
Definition at line 89 of file parallel_object.h.
References libMesh::ParallelObject::_communicator.
Referenced by libMesh::__libmesh_petsc_diff_solver_jacobian(), libMesh::__libmesh_petsc_diff_solver_monitor(), libMesh::__libmesh_petsc_diff_solver_residual(), libMesh::__libmesh_tao_equality_constraints(), libMesh::__libmesh_tao_equality_constraints_jacobian(), libMesh::__libmesh_tao_gradient(), libMesh::__libmesh_tao_hessian(), libMesh::__libmesh_tao_inequality_constraints(), libMesh::__libmesh_tao_inequality_constraints_jacobian(), libMesh::__libmesh_tao_objective(), libMesh::MeshRefinement::_coarsen_elements(), libMesh::ExactSolution::_compute_error(), libMesh::UniformRefinementEstimator::_estimate_error(), libMesh::BoundaryInfo::_find_id_maps(), libMesh::SlepcEigenSolver< T >::_petsc_shell_matrix_get_diagonal(), libMesh::PetscLinearSolver< T >::_petsc_shell_matrix_get_diagonal(), libMesh::SlepcEigenSolver< T >::_petsc_shell_matrix_mult(), libMesh::PetscLinearSolver< T >::_petsc_shell_matrix_mult(), libMesh::PetscLinearSolver< T >::_petsc_shell_matrix_mult_add(), libMesh::EquationSystems::_read_impl(), libMesh::MeshRefinement::_refine_elements(), libMesh::MeshRefinement::_smooth_flags(), libMesh::PetscDMWrapper::add_dofs_helper(), libMesh::PetscDMWrapper::add_dofs_to_section(), libMesh::ImplicitSystem::add_matrix(), libMesh::System::add_vector(), libMesh::UnstructuredMesh::all_second_order(), libMesh::MeshTools::Modification::all_tri(), libMesh::LaplaceMeshSmoother::allgather_graph(), libMesh::FEMSystem::assemble_qoi(), libMesh::MeshCommunication::assign_global_indices(), libMesh::DofMap::attach_matrix(), libMesh::MeshTools::Generation::build_extrusion(), libMesh::BoundaryInfo::build_node_list_from_side_list(), libMesh::EquationSystems::build_parallel_elemental_solution_vector(), libMesh::EquationSystems::build_parallel_solution_vector(), libMesh::PetscDMWrapper::build_section(), libMesh::PetscDMWrapper::build_sf(), libMesh::MeshBase::cache_elem_dims(), libMesh::System::calculate_norm(), libMesh::DofMap::check_dirichlet_bcid_consistency(), libMesh::PetscDMWrapper::check_section_n_dofs(), libMesh::Nemesis_IO_Helper::compute_num_global_elem_blocks(), libMesh::Nemesis_IO_Helper::compute_num_global_nodesets(), libMesh::Nemesis_IO_Helper::compute_num_global_sidesets(), libMesh::Problem_Interface::computeF(), libMesh::Problem_Interface::computeJacobian(), libMesh::Problem_Interface::computePreconditioner(), libMesh::ExodusII_IO::copy_elemental_solution(), libMesh::MeshTools::correct_node_proc_ids(), libMesh::MeshTools::create_bounding_box(), libMesh::MeshTools::create_nodal_bounding_box(), libMesh::MeshRefinement::create_parent_error_vector(), libMesh::MeshTools::create_processor_bounding_box(), libMesh::MeshTools::create_subdomain_bounding_box(), libMesh::MeshCommunication::delete_remote_elements(), libMesh::DofMap::distribute_dofs(), DMlibMeshFunction(), DMlibMeshJacobian(), DMlibMeshSetSystem_libMesh(), DMVariableBounds_libMesh(), libMesh::MeshRefinement::eliminate_unrefined_patches(), libMesh::EpetraVector< T >::EpetraVector(), libMesh::WeightedPatchRecoveryErrorEstimator::estimate_error(), libMesh::PatchRecoveryErrorEstimator::estimate_error(), libMesh::JumpErrorEstimator::estimate_error(), libMesh::AdjointRefinementEstimator::estimate_error(), libMesh::ExactErrorEstimator::estimate_error(), libMesh::MeshRefinement::flag_elements_by_elem_fraction(), libMesh::MeshRefinement::flag_elements_by_error_fraction(), libMesh::MeshRefinement::flag_elements_by_nelem_target(), libMesh::CondensedEigenSystem::get_eigenpair(), libMesh::DofMap::get_info(), libMesh::ImplicitSystem::get_linear_solver(), libMesh::LocationMap< T >::init(), libMesh::TimeSolver::init(), libMesh::SystemSubsetBySubdomain::init(), libMesh::PetscDMWrapper::init_and_attach_petscdm(), libMesh::EigenSystem::init_data(), libMesh::EigenSystem::init_matrices(), libMesh::OptimizationSystem::initialize_equality_constraints_storage(), libMesh::OptimizationSystem::initialize_inequality_constraints_storage(), libMesh::MeshTools::libmesh_assert_consistent_distributed(), libMesh::MeshTools::libmesh_assert_consistent_distributed_nodes(), libMesh::MeshTools::libmesh_assert_contiguous_dof_ids(), libMesh::MeshTools::libmesh_assert_parallel_consistent_new_node_procids(), libMesh::MeshTools::libmesh_assert_parallel_consistent_procids< Elem >(), libMesh::MeshTools::libmesh_assert_parallel_consistent_procids< Node >(), libMesh::MeshTools::libmesh_assert_topology_consistent_procids< Node >(), libMesh::MeshTools::libmesh_assert_valid_boundary_ids(), libMesh::MeshTools::libmesh_assert_valid_dof_ids(), libMesh::MeshTools::libmesh_assert_valid_neighbors(), libMesh::DistributedMesh::libmesh_assert_valid_parallel_flags(), libMesh::DistributedMesh::libmesh_assert_valid_parallel_object_ids(), libMesh::DistributedMesh::libmesh_assert_valid_parallel_p_levels(), libMesh::MeshTools::libmesh_assert_valid_refinement_flags(), libMesh::MeshTools::libmesh_assert_valid_unique_ids(), libMesh::libmesh_petsc_snes_fd_residual(), libMesh::libmesh_petsc_snes_jacobian(), libMesh::libmesh_petsc_snes_mffd_residual(), libMesh::libmesh_petsc_snes_postcheck(), libMesh::libmesh_petsc_snes_residual(), libMesh::libmesh_petsc_snes_residual_helper(), libMesh::MeshRefinement::limit_level_mismatch_at_edge(), libMesh::MeshRefinement::limit_level_mismatch_at_node(), libMesh::MeshRefinement::limit_overrefined_boundary(), libMesh::MeshRefinement::limit_underrefined_boundary(), libMesh::MeshRefinement::make_coarsening_compatible(), libMesh::MeshCommunication::make_elems_parallel_consistent(), libMesh::MeshRefinement::make_flags_parallel_consistent(), libMesh::MeshCommunication::make_new_node_proc_ids_parallel_consistent(), libMesh::MeshCommunication::make_new_nodes_parallel_consistent(), libMesh::MeshCommunication::make_node_ids_parallel_consistent(), libMesh::MeshCommunication::make_node_proc_ids_parallel_consistent(), libMesh::MeshCommunication::make_node_unique_ids_parallel_consistent(), libMesh::MeshCommunication::make_nodes_parallel_consistent(), libMesh::MeshCommunication::make_p_levels_parallel_consistent(), libMesh::MeshRefinement::make_refinement_compatible(), libMesh::FEMSystem::mesh_position_set(), libMesh::DistributedMesh::n_active_elem(), libMesh::MeshTools::n_active_levels(), libMesh::BoundaryInfo::n_boundary_conds(), libMesh::BoundaryInfo::n_edge_conds(), libMesh::CondensedEigenSystem::n_global_non_condensed_dofs(), libMesh::MeshTools::n_levels(), libMesh::BoundaryInfo::n_nodeset_conds(), libMesh::MeshTools::n_p_levels(), libMesh::BoundaryInfo::n_shellface_conds(), libMesh::DistributedMesh::parallel_max_elem_id(), libMesh::DistributedMesh::parallel_max_node_id(), libMesh::ReplicatedMesh::parallel_max_unique_id(), libMesh::DistributedMesh::parallel_max_unique_id(), libMesh::DistributedMesh::parallel_n_elem(), libMesh::DistributedMesh::parallel_n_nodes(), libMesh::SparsityPattern::Build::parallel_sync(), libMesh::MeshTools::paranoid_n_levels(), libMesh::petsc_auto_fieldsplit(), libMesh::System::point_gradient(), libMesh::System::point_hessian(), libMesh::System::point_value(), libMesh::MeshBase::prepare_for_use(), libMesh::Nemesis_IO::read(), libMesh::XdrIO::read(), libMesh::CheckpointIO::read_header(), libMesh::XdrIO::read_header(), libMesh::System::read_header(), libMesh::System::read_legacy_data(), libMesh::System::read_SCALAR_dofs(), libMesh::XdrIO::read_serialized_bc_names(), libMesh::XdrIO::read_serialized_bcs_helper(), libMesh::System::read_serialized_blocked_dof_objects(), libMesh::XdrIO::read_serialized_connectivity(), libMesh::XdrIO::read_serialized_nodes(), libMesh::XdrIO::read_serialized_nodesets(), libMesh::XdrIO::read_serialized_subdomain_names(), libMesh::System::read_serialized_vector(), libMesh::MeshBase::recalculate_n_partitions(), libMesh::MeshRefinement::refine_and_coarsen_elements(), libMesh::DistributedMesh::renumber_dof_objects(), libMesh::CheckpointIO::select_split_config(), libMesh::DofMap::set_nonlocal_dof_objects(), libMesh::PetscDMWrapper::set_point_range_in_section(), libMesh::PetscDiffSolver::setup_petsc_data(), libMesh::LaplaceMeshSmoother::smooth(), libMesh::split_mesh(), libMesh::MeshBase::subdomain_ids(), libMesh::BoundaryInfo::sync(), libMesh::MeshRefinement::test_level_one(), libMesh::MeshRefinement::test_unflagged(), libMesh::MeshTools::total_weight(), libMesh::MeshRefinement::uniformly_coarsen(), libMesh::NameBasedIO::write(), libMesh::XdrIO::write(), libMesh::System::write_SCALAR_dofs(), libMesh::XdrIO::write_serialized_bcs_helper(), libMesh::System::write_serialized_blocked_dof_objects(), libMesh::XdrIO::write_serialized_connectivity(), libMesh::XdrIO::write_serialized_nodes(), and libMesh::XdrIO::write_serialized_nodesets().
   { return _communicator; }
compare()
template<typename T> int libMesh::NumericVector< T >::compare (const NumericVector< T > & other_vector, const Real threshold = TOLERANCE) const virtual inherited
Returns
-1 when this is equivalent to other_vector (up to the given threshold), or the first index where abs(a[i]-b[i]) exceeds the threshold.
Definition at line 104 of file numeric_vector.C.
 {
   libmesh_assert (this->initialized());
   libmesh_assert (other_vector.initialized());
   libmesh_assert_equal_to (this->first_local_index(), other_vector.first_local_index());
   libmesh_assert_equal_to (this->last_local_index(), other_vector.last_local_index());
   int first_different_i = std::numeric_limits<int>::max();
   numeric_index_type i = first_local_index();
   do
     {
       if (std::abs((*this)(i) - other_vector(i)) > threshold)
         first_different_i = i;
       else
         i++;
     }
   while (first_different_i==std::numeric_limits<int>::max()
          && i<last_local_index());
   // Find the correct first differing index in parallel
   this->comm().min(first_different_i);
   if (first_different_i == std::numeric_limits<int>::max())
     return -1;
   return first_different_i;
 }
conjugate()
template<typename T > void libMesh::LaspackVector< T >::conjugate () override virtual
Negates the imaginary component of each entry in the vector.
Implements libMesh::NumericVector< T >.
Definition at line 142 of file laspack_vector.C.
References libMesh::libmesh_conj().
 {
   const numeric_index_type n = this->size();
   for (numeric_index_type i=0; i<n; i++)
     {
       T v = (*this)(i);
       this->set(i, libmesh_conj(v) );
     }
 }
create_subvector()
template<typename T> virtual void libMesh::NumericVector< T >::create_subvector (NumericVector< T > & , const std::vector< numeric_index_type > &) const inline virtual inherited
Fills in subvector from this vector using the indices in rows. Similar to the create_submatrix() routine for the SparseMatrix class, it is currently only implemented for PetscVectors.
Reimplemented in libMesh::PetscVector< T >, and libMesh::EpetraVector< T >.
Definition at line 692 of file numeric_vector.h.
   {
     libmesh_not_implemented();
   }
disable_print_counter_info()
void libMesh::ReferenceCounter::disable_print_counter_info () static inherited
Definition at line 106 of file reference_counter.C.
References libMesh::ReferenceCounter::_enable_print_counter.
Referenced by libMesh::LibMeshInit::LibMeshInit().
 {
   _enable_print_counter = false;
   return;
 }
dot()
template<typename T > T libMesh::LaspackVector< T >::dot (const NumericVector< T > & v) const override virtual
Returns
, the dot product of (*this) with the vector v.
Uses the complex-conjugate of v in the complex-valued case.
Implements libMesh::NumericVector< T >.
Definition at line 248 of file laspack_vector.C.
References libMesh::LaspackVector< T >::_vec, and libMesh::initialized().
 {
   libmesh_assert (this->initialized());
   // Make sure the NumericVector passed in is really a LaspackVector
   const LaspackVector<T> * v = cast_ptr<const LaspackVector<T> *>(&v_in);
   libmesh_assert(v);
   return Mul_VV (const_cast<QVector*>(&(this->_vec)),
                  const_cast<QVector*>(&(v->_vec)));
 }
el()
template<typename T> virtual T libMesh::NumericVector< T >::el (const numeric_index_type i) const inline virtual inherited
Returns
(*this)(i).
Definition at line 346 of file numeric_vector.h.
 { return (*this)(i); }
enable_print_counter_info()
void libMesh::ReferenceCounter::enable_print_counter_info () static inherited
Methods to enable/disable the reference counter output from print_info()
Definition at line 100 of file reference_counter.C.
References libMesh::ReferenceCounter::_enable_print_counter.
 {
   _enable_print_counter = true;
   return;
 }
first_local_index()
template<typename T > numeric_index_type libMesh::LaspackVector< T >::first_local_index () const inline override virtual
Returns
The index of the first vector element actually stored on this processor.
Note
The minimum for this index is 0.
Implements libMesh::NumericVector< T >.
Definition at line 472 of file laspack_vector.h.
References libMesh::initialized().
 {
   libmesh_assert (this->initialized());
   return 0;
 }
get() [1/2]
template<typename T> void libMesh::NumericVector< T >::get (const std::vector< numeric_index_type > & index, T * values) const inline virtual inherited
Access multiple components at once. values will not be reallocated; it should already have enough space. The default implementation calls operator() for each index, but some implementations may supply faster methods here.
Reimplemented in libMesh::PetscVector< T >.
Definition at line 806 of file numeric_vector.h.
Referenced by libMesh::UniformRefinementEstimator::_estimate_error(), libMesh::DofMap::enforce_adjoint_constraints_exactly(), libMesh::DofMap::enforce_constraints_exactly(), libMesh::AdjointRefinementEstimator::estimate_error(), and libMesh::FEMContext::pre_fe_reinit().
 {
   const std::size_t num = index.size();
   for (std::size_t i=0; i<num; i++)
     {
       values[i] = (*this)(index[i]);
     }
 }
get() [2/2]
template<typename T> void libMesh::NumericVector< T >::get (const std::vector< numeric_index_type > & index, std::vector< T > & values) const inline inherited
Access multiple components at once. values will be resized, if necessary, and filled. The default implementation calls operator() for each index, but some implementations may supply faster methods here.
Definition at line 820 of file numeric_vector.h.
 {
   const std::size_t num = index.size();
   values.resize(num);
   if (!num)
     return;
   this->get(index, values.data());
 }
get_info()
std::string libMesh::ReferenceCounter::get_info () static inherited
Gets a string containing the reference information.
Definition at line 47 of file reference_counter.C.
References libMesh::ReferenceCounter::_counts, and libMesh::Quality::name().
Referenced by libMesh::ReferenceCounter::print_info().
 {
 #if defined(LIBMESH_ENABLE_REFERENCE_COUNTING) && defined(DEBUG)
   std::ostringstream oss;
   oss << '\n'
       << " ---------------------------------------------------------------------------- \n"
       << "| Reference count information                                                |\n"
       << " ---------------------------------------------------------------------------- \n";
   for (const auto & pr : _counts)
     {
       const std::string name(pr.first);
       const unsigned int creations    = pr.second.first;
       const unsigned int destructions = pr.second.second;
       oss << "| " << name << " reference count information:\n"
           << "|  Creations:    " << creations    << '\n'
           << "|  Destructions: " << destructions << '\n';
     }
   oss << " ---------------------------------------------------------------------------- \n";
   return oss.str();
 #else
   return "";
 #endif
 }
global_relative_compare()
template<typename T> int libMesh::NumericVector< T >::global_relative_compare (const NumericVector< T > & other_vector, const Real threshold = TOLERANCE) const virtual inherited
Returns
-1 when this is equivalent to other_vector (up to the given global relative threshold), or the first index where abs(a[i]-b[i])/max_j(a[j],b[j]) exceeds the threshold.
Definition at line 169 of file numeric_vector.C.
 {
   libmesh_assert (this->initialized());
   libmesh_assert (other_vector.initialized());
   libmesh_assert_equal_to (this->first_local_index(), other_vector.first_local_index());
   libmesh_assert_equal_to (this->last_local_index(), other_vector.last_local_index());
   int first_different_i = std::numeric_limits<int>::max();
   numeric_index_type i = first_local_index();
   const Real my_norm = this->linfty_norm();
   const Real other_norm = other_vector.linfty_norm();
   const Real abs_threshold = std::max(my_norm, other_norm) * threshold;
   do
     {
       if (std::abs((*this)(i) - other_vector(i) ) > abs_threshold)
         first_different_i = i;
       else
         i++;
     }
   while (first_different_i==std::numeric_limits<int>::max()
          && i<last_local_index());
   // Find the correct first differing index in parallel
   this->comm().min(first_different_i);
   if (first_different_i == std::numeric_limits<int>::max())
     return -1;
   return first_different_i;
 }
increment_constructor_count()
void libMesh::ReferenceCounter::increment_constructor_count (const std::string & name) inline protected inherited
Increments the construction counter. Should be called in the constructor of any derived class that will be reference counted.
Definition at line 181 of file reference_counter.h.
References libMesh::ReferenceCounter::_counts, libMesh::Quality::name(), and libMesh::Threads::spin_mtx.
Referenced by libMesh::ReferenceCountedObject< RBParametrized >::ReferenceCountedObject().
 {
   Threads::spin_mutex::scoped_lock lock(Threads::spin_mtx);
   std::pair<unsigned int, unsigned int> & p = _counts[name];
   p.first++;
 }
increment_destructor_count()
void libMesh::ReferenceCounter::increment_destructor_count (const std::string & name) inline protected inherited
Increments the destruction counter. Should be called in the destructor of any derived class that will be reference counted.
Definition at line 194 of file reference_counter.h.
References libMesh::ReferenceCounter::_counts, libMesh::Quality::name(), and libMesh::Threads::spin_mtx.
Referenced by libMesh::ReferenceCountedObject< RBParametrized >::~ReferenceCountedObject().
 {
   Threads::spin_mutex::scoped_lock lock(Threads::spin_mtx);
   std::pair<unsigned int, unsigned int> & p = _counts[name];
   p.second++;
 }
init() [1/4]
template<typename T> virtual void libMesh::LaspackVector< T >::init (const numeric_index_type n, const numeric_index_type n_local, const bool fast = false, const ParallelType ptype = AUTOMATIC) override virtual
Change the dimension of the vector to n. The reserved memory for this vector remains unchanged if possible. If n==0, all memory is freed. Therefore, if you want to resize the vector and release the memory not needed, you have to first call init(0) and then init(n). This behaviour is analogous to that of the STL containers.
On fast==false, the vector is filled by zeros.
Implements libMesh::NumericVector< T >.
Referenced by libMesh::LaspackVector< T >::LaspackVector().
init() [2/4]
template<typename T > void libMesh::LaspackVector< T >::init (const numeric_index_type n, const bool fast = false, const ParallelType ptype = AUTOMATIC) inline override virtual
Call init() with n_local = N.
Implements libMesh::NumericVector< T >.
Definition at line 346 of file laspack_vector.h.
References libMesh::TriangleWrapper::init().
 {
   this->init(n,n,fast,ptype);
 }
init() [3/4]
template<typename T> virtual void libMesh::LaspackVector< T >::init (const numeric_index_type n, const numeric_index_type n_local, const std::vector< numeric_index_type > & ghost, const bool fast = false, const ParallelType ptype = AUTOMATIC) override virtual
Create a vector that holds tha local indices plus those specified in the ghost argument.
Implements libMesh::NumericVector< T >.
init() [4/4]
template<class T > void libMesh::LaspackVector< T >::init (const NumericVector< T > & other, const bool fast = false) override virtual
Creates a vector that has the same dimension and storage type as other, including ghost dofs.
Implements libMesh::NumericVector< T >.
Definition at line 371 of file laspack_vector.h.
References libMesh::TriangleWrapper::init(), libMesh::NumericVector< T >::local_size(), libMesh::NumericVector< T >::size(), and libMesh::NumericVector< T >::type().
 {
   this->init(other.size(),other.local_size(),fast,other.type());
 }
initialized()
template<typename T> virtual bool libMesh::NumericVector< T >::initialized () const inline virtual inherited
Returns
true if the vector has been initialized, false otherwise.
Definition at line 149 of file numeric_vector.h.
Referenced by libMesh::ImplicitSystem::assemble(), libMesh::NumericVector< Number >::compare(), libMesh::PetscVector< T >::create_subvector(), libMesh::NumericVector< Number >::global_relative_compare(), libMesh::PetscVector< T >::init(), and libMesh::NumericVector< Number >::local_relative_compare().
 { return _is_initialized; }
insert() [1/5]
template<typename T> void libMesh::NumericVector< T >::insert (const T * v, const std::vector< numeric_index_type > & dof_indices) virtual inherited
Inserts the entries of v in *this at the locations specified by v.
Reimplemented in libMesh::PetscVector< T >, and libMesh::EpetraVector< T >.
Definition at line 82 of file numeric_vector.C.
 {
   for (numeric_index_type i=0; i<dof_indices.size(); i++)
     this->set (dof_indices[i], v[i]);
 }
insert() [2/5]
template<typename T> void libMesh::NumericVector< T >::insert (const std::vector< T > & v, const std::vector< numeric_index_type > & dof_indices) inline inherited
Inserts the entries of v in *this at the locations specified by v.
Definition at line 859 of file numeric_vector.h.
 {
   libmesh_assert(v.size() == dof_indices.size());
   if (!v.empty())
     this->insert(v.data(), dof_indices);
 }
insert() [3/5]
template<typename T> void libMesh::NumericVector< T >::insert (const NumericVector< T > & v, const std::vector< numeric_index_type > & dof_indices) virtual inherited
Inserts the entries of v in *this at the locations specified by v.
Definition at line 92 of file numeric_vector.C.
 {
   libmesh_assert_equal_to (V.size(), dof_indices.size());
   for (numeric_index_type i=0; i<dof_indices.size(); i++)
     this->set (dof_indices[i], V(i));
 }
insert() [4/5]
template<typename T> void libMesh::NumericVector< T >::insert (const DenseVector< T > & v, const std::vector< numeric_index_type > & dof_indices) inline inherited
Inserts the entries of v in *this at the locations specified by v.
Definition at line 871 of file numeric_vector.h.
 {
   libmesh_assert(v.size() == dof_indices.size());
   if (!v.empty())
     this->insert(&v(0), dof_indices);
 }
insert() [5/5]
template<typename T> void libMesh::NumericVector< T >::insert (const DenseSubVector< T > & v, const std::vector< numeric_index_type > & dof_indices) inline inherited
Inserts the entries of v in *this at the locations specified by v.
Definition at line 883 of file numeric_vector.h.
 {
   libmesh_assert(v.size() == dof_indices.size());
   if (!v.empty())
     this->insert(&v(0), dof_indices);
 }
l1_norm()
template<typename T > Real libMesh::LaspackVector< T >::l1_norm () const override virtual
Returns
The -norm of the vector, i.e. the sum of the absolute values of the entries.
Implements libMesh::NumericVector< T >.
Definition at line 54 of file laspack_vector.C.
References libMesh::closed(), and libMesh::Real.
 {
   libmesh_assert (this->closed());
   return static_cast<Real>(l1Norm_V(const_cast<QVector*>(&_vec)));
 }
l2_norm()
template<typename T > Real libMesh::LaspackVector< T >::l2_norm () const override virtual
Returns
The -norm of the vector, i.e. the square root of the sum of the squares of the entries.
Implements libMesh::NumericVector< T >.
Definition at line 64 of file laspack_vector.C.
References libMesh::closed(), and libMesh::Real.
 {
   libmesh_assert (this->closed());
   return static_cast<Real>(l2Norm_V(const_cast<QVector*>(&_vec)));
 }
last_local_index()
template<typename T > numeric_index_type libMesh::LaspackVector< T >::last_local_index () const inline override virtual
Returns
The index+1 of the last vector element actually stored on this processor.
Note
The maximum for this index is size().
Implements libMesh::NumericVector< T >.
Definition at line 483 of file laspack_vector.h.
References libMesh::initialized().
 {
   libmesh_assert (this->initialized());
   return this->size();
 }
linfty_norm()
template<typename T > Real libMesh::LaspackVector< T >::linfty_norm () const override virtual
Returns
The -norm of the vector, i.e. the maximum absolute value of the entries of the vector.
Implements libMesh::NumericVector< T >.
Definition at line 74 of file laspack_vector.C.
References libMesh::closed(), and libMesh::Real.
 {
   libmesh_assert (this->closed());
   return static_cast<Real>(MaxNorm_V(const_cast<QVector*>(&_vec)));
 }
local_relative_compare()
template<typename T> int libMesh::NumericVector< T >::local_relative_compare (const NumericVector< T > & other_vector, const Real threshold = TOLERANCE) const virtual inherited
Returns
-1 when this is equivalent to other_vector, (up to the given local relative threshold), or the first index where abs(a[i]-b[i])/max(a[i],b[i]) exceeds the threshold.
Definition at line 136 of file numeric_vector.C.
 {
   libmesh_assert (this->initialized());
   libmesh_assert (other_vector.initialized());
   libmesh_assert_equal_to (this->first_local_index(), other_vector.first_local_index());
   libmesh_assert_equal_to (this->last_local_index(), other_vector.last_local_index());
   int first_different_i = std::numeric_limits<int>::max();
   numeric_index_type i = first_local_index();
   do
     {
       if (std::abs((*this)(i) - other_vector(i)) > threshold *
           std::max(std::abs((*this)(i)), std::abs(other_vector(i))))
         first_different_i = i;
       else
         i++;
     }
   while (first_different_i==std::numeric_limits<int>::max()
          && i<last_local_index());
   // Find the correct first differing index in parallel
   this->comm().min(first_different_i);
   if (first_different_i == std::numeric_limits<int>::max())
     return -1;
   return first_different_i;
 }
local_size()
template<typename T > numeric_index_type libMesh::LaspackVector< T >::local_size () const inline override virtual
Returns
The local size of the vector, i.e. index_stop - index_start.
Implements libMesh::NumericVector< T >.
Definition at line 461 of file laspack_vector.h.
References libMesh::initialized().
 {
   libmesh_assert (this->initialized());
   return this->size();
 }
localize() [1/5]
template<typename T > void libMesh::LaspackVector< T >::localize (std::vector< T > & v_local) const override virtual
Creates a copy of the global vector in the local vector v_local.
Implements libMesh::NumericVector< T >.
Definition at line 395 of file laspack_vector.C.
 {
   v_local.resize(this->size());
   for (numeric_index_type i=0; i<v_local.size(); i++)
     v_local[i] = (*this)(i);
 }
localize() [2/5]
template<typename T > void libMesh::LaspackVector< T >::localize (NumericVector< T > & v_local) const override virtual
Same, but fills a NumericVector<T> instead of a std::vector.
Implements libMesh::NumericVector< T >.
Definition at line 335 of file laspack_vector.C.
 {
   // Make sure the NumericVector passed in is really a LaspackVector
   LaspackVector<T> * v_local =
     cast_ptr<LaspackVector<T> *>(&v_local_in);
   libmesh_assert(v_local);
   *v_local = *this;
 }
localize() [3/5]
template<typename T> virtual void libMesh::LaspackVector< T >::localize (NumericVector< T > & v_local, const std::vector< numeric_index_type > & send_list) const override virtual
Creates a local vector v_local containing only information relevant to this processor, as defined by the send_list.
Implements libMesh::NumericVector< T >.
localize() [4/5]
template<typename T > void libMesh::LaspackVector< T >::localize (std::vector< T > & v_local, const std::vector< numeric_index_type > & indices) const override virtual
Fill in the local std::vector "v_local" with the global indices given in "indices".
Note
The indices can be different on every processor, and the same index can be localized to more than one processor. The resulting v_local can be shorter than the original, and the entries will be in the order specified by indices.
Example:
*   On 4 procs *this = {a, b, c, d, e, f, g, h, i} is a parallel vector.
*   On each proc, the indices arrays are set up as:
*   proc0, indices = {1,2,4,5}
*   proc1, indices = {2,5,6,8}
*   proc2, indices = {2,3,6,7}
*   proc3, indices = {0,1,2,3}
*
*   After calling this version of localize, the v_local vectors are:
*   proc0, v_local = {b,c,e,f}
*   proc1, v_local = {c,f,g,i}
*   proc2, v_local = {c,d,g,h}
*   proc3, v_local = {a,b,c,d}
*
This function is useful in parallel I/O routines, when you have a parallel vector of solution values which you want to write a subset of.
Implements libMesh::NumericVector< T >.
Definition at line 365 of file laspack_vector.C.
 {
   // LaspackVectors are serial, so we can just copy values
   v_local.resize(indices.size());
   for (numeric_index_type i=0; i<v_local.size(); i++)
     v_local[i] = (*this)(indices[i]);
 }
localize() [5/5]
template<typename T> virtual void libMesh::LaspackVector< T >::localize (const numeric_index_type first_local_idx, const numeric_index_type last_local_idx, const std::vector< numeric_index_type > & send_list) override virtual
Updates a local vector with selected values from neighboring processors, as defined by send_list.
Implements libMesh::NumericVector< T >.
localize_to_one()
template<typename T> void libMesh::LaspackVector< T >::localize_to_one (std::vector< T > & v_local, const processor_id_type proc_id = 0) const override virtual
Creates a local copy of the global vector in v_local only on processor proc_id. By default the data is sent to processor 0. This method is useful for outputting data from one processor.
Implements libMesh::NumericVector< T >.
Definition at line 407 of file laspack_vector.C.
 {
   libmesh_assert_equal_to (pid, 0);
   this->localize (v_local);
 }
max()
template<typename T > Real libMesh::LaspackVector< T >::max () const override virtual
Returns
The maximum entry in the vector, or the maximum real part in the case of complex numbers.
Implements libMesh::NumericVector< T >.
Definition at line 427 of file laspack_vector.C.
References libMesh::initialized(), libMesh::libmesh_real(), std::max(), and libMesh::Real.
 {
   libmesh_assert (this->initialized());
   if (!this->size())
     return -std::numeric_limits<Real>::max();
   Real the_max = libmesh_real((*this)(0));
   const numeric_index_type n = this->size();
   for (numeric_index_type i=1; i<n; i++)
     the_max = std::max (the_max, libmesh_real((*this)(i)));
   return the_max;
 }
min()
template<typename T > Real libMesh::LaspackVector< T >::min () const override virtual
Returns
The minimum entry in the vector, or the minimum real part in the case of complex numbers.
Implements libMesh::NumericVector< T >.
Definition at line 446 of file laspack_vector.C.
References libMesh::initialized(), libMesh::libmesh_real(), std::max(), std::min(), and libMesh::Real.
 {
   libmesh_assert (this->initialized());
   if (!this->size())
     return std::numeric_limits<Real>::max();
   Real the_min = libmesh_real((*this)(0));
   const numeric_index_type n = this->size();
   for (numeric_index_type i=1; i<n; i++)
     the_min = std::min (the_min, libmesh_real((*this)(i)));
   return the_min;
 }
n_objects()
static unsigned int libMesh::ReferenceCounter::n_objects () inline static inherited
Prints the number of outstanding (created, but not yet destroyed) objects.
Definition at line 83 of file reference_counter.h.
References libMesh::ReferenceCounter::_n_objects.
   { return _n_objects; }
n_processors()
processor_id_type libMesh::ParallelObject::n_processors () const inline inherited
Returns
The number of processors in the group.
Definition at line 95 of file parallel_object.h.
References libMesh::ParallelObject::_communicator, and libMesh::Parallel::Communicator::size().
Referenced by libMesh::BoundaryInfo::_find_id_maps(), libMesh::PetscDMWrapper::add_dofs_to_section(), libMesh::DistributedMesh::add_elem(), libMesh::DistributedMesh::add_node(), libMesh::LaplaceMeshSmoother::allgather_graph(), libMesh::FEMSystem::assembly(), libMesh::AztecLinearSolver< T >::AztecLinearSolver(), libMesh::BoundaryInfo::build_node_list_from_side_list(), libMesh::EquationSystems::build_parallel_elemental_solution_vector(), libMesh::DistributedMesh::clear(), libMesh::Nemesis_IO_Helper::compute_border_node_ids(), libMesh::Nemesis_IO_Helper::construct_nemesis_filename(), libMesh::UnstructuredMesh::create_pid_mesh(), libMesh::MeshTools::create_processor_bounding_box(), libMesh::DofMap::distribute_dofs(), libMesh::DofMap::distribute_local_dofs_node_major(), libMesh::DofMap::distribute_local_dofs_var_major(), libMesh::EnsightIO::EnsightIO(), libMesh::MeshBase::get_info(), libMesh::SystemSubsetBySubdomain::init(), libMesh::PetscDMWrapper::init_and_attach_petscdm(), libMesh::Nemesis_IO_Helper::initialize(), libMesh::DistributedMesh::insert_elem(), libMesh::MeshTools::libmesh_assert_contiguous_dof_ids(), libMesh::MeshTools::libmesh_assert_parallel_consistent_new_node_procids(), libMesh::MeshTools::libmesh_assert_parallel_consistent_procids< Elem >(), libMesh::MeshTools::libmesh_assert_parallel_consistent_procids< Node >(), libMesh::MeshTools::libmesh_assert_topology_consistent_procids< Node >(), libMesh::MeshTools::libmesh_assert_valid_boundary_ids(), libMesh::MeshTools::libmesh_assert_valid_dof_ids(), libMesh::MeshTools::libmesh_assert_valid_neighbors(), libMesh::MeshTools::libmesh_assert_valid_refinement_flags(), libMesh::DofMap::local_variable_indices(), libMesh::MeshRefinement::make_coarsening_compatible(), libMesh::MeshBase::n_active_elem_on_proc(), libMesh::MeshBase::n_elem_on_proc(), libMesh::MeshBase::n_nodes_on_proc(), libMesh::MeshBase::partition(), libMesh::PetscLinearSolver< T >::PetscLinearSolver(), libMesh::System::point_gradient(), libMesh::System::point_hessian(), libMesh::System::point_value(), libMesh::NameBasedIO::read(), libMesh::Nemesis_IO::read(), libMesh::CheckpointIO::read(), libMesh::CheckpointIO::read_connectivity(), libMesh::XdrIO::read_header(), libMesh::CheckpointIO::read_nodes(), libMesh::System::read_parallel_data(), libMesh::System::read_SCALAR_dofs(), libMesh::System::read_serialized_blocked_dof_objects(), libMesh::System::read_serialized_vector(), libMesh::DistributedMesh::renumber_dof_objects(), libMesh::DofMap::set_nonlocal_dof_objects(), libMesh::PetscDMWrapper::set_point_range_in_section(), libMesh::MeshRefinement::uniformly_coarsen(), libMesh::DistributedMesh::update_parallel_id_counts(), libMesh::GMVIO::write_binary(), libMesh::GMVIO::write_discontinuous_gmv(), libMesh::System::write_parallel_data(), libMesh::System::write_SCALAR_dofs(), libMesh::XdrIO::write_serialized_bcs_helper(), libMesh::System::write_serialized_blocked_dof_objects(), libMesh::XdrIO::write_serialized_connectivity(), libMesh::XdrIO::write_serialized_nodes(), and libMesh::XdrIO::write_serialized_nodesets().
   { return cast_int<processor_id_type>(_communicator.size()); }
operator()()
template<typename T > T libMesh::LaspackVector< T >::operator() (const numeric_index_type i) const inline override virtual
Returns
A copy of the ith entry of the vector.
Implements libMesh::NumericVector< T >.
Definition at line 526 of file laspack_vector.h.
References libMesh::initialized().
 {
   libmesh_assert (this->initialized());
   libmesh_assert ( ((i >= this->first_local_index()) &&
                     (i <  this->last_local_index())) );
   return static_cast<T>(V_GetCmp(const_cast<QVector*>(&_vec), i+1));
 }
operator*=()
template<typename T> NumericVector<T>& libMesh::NumericVector< T >::operator*= (const T a) inline inherited
Scales the vector by a, . Equivalent to u.scale(a)
Returns
A reference to *this.
Definition at line 391 of file numeric_vector.h.
 { this->scale(a); return *this; }
operator+=()
template<typename T > NumericVector< T > & libMesh::LaspackVector< T >::operator+= (const NumericVector< T > & v) override virtual
Adds v to *this, . Equivalent to u.add(1, v).
Returns
A reference to *this.
Implements libMesh::NumericVector< T >.
Definition at line 84 of file laspack_vector.C.
References libMesh::closed().
 {
   libmesh_assert (this->closed());
   this->add(1., v);
   return *this;
 }
operator-=()
template<typename T > NumericVector< T > & libMesh::LaspackVector< T >::operator-= (const NumericVector< T > & v) override virtual
Subtracts v from *this, . Equivalent to u.add(-1, v).
Returns
A reference to *this.
Implements libMesh::NumericVector< T >.
Definition at line 97 of file laspack_vector.C.
References libMesh::closed().
 {
   libmesh_assert (this->closed());
   this->add(-1., v);
   return *this;
 }
operator/=() [1/2]
template<typename T > NumericVector< T > & libMesh::LaspackVector< T >::operator/= (const NumericVector< T > &) override virtual
Computes the pointwise division of this vector's entries by another's,
Returns
A reference to *this.
Implements libMesh::NumericVector< T >.
Definition at line 109 of file laspack_vector.C.
References libMesh::NumericVector< T >::size().
 {
   libmesh_assert_equal_to(size(), v.size());
   const numeric_index_type n = this->size();
   for (numeric_index_type i=0; i<n; i++)
     this->set(i, (*this)(i) / v(i));
   return *this;
 }
operator/=() [2/2]
template<typename T> NumericVector<T>& libMesh::NumericVector< T >::operator/= (const T a) inline inherited
Scales the vector by 1/a, . Equivalent to u.scale(1./a)
Returns
A reference to *this.
Definition at line 400 of file numeric_vector.h.
 { this->scale(1./a); return *this; }
operator=() [1/5]
template<typename T > LaspackVector< T > & libMesh::LaspackVector< T >::operator= (const LaspackVector< T > & v)
Copy assignment operator. Calls Asgn_VV() to assign the contents of one vector to another.
Returns
A reference to *this as the derived type.
Definition at line 295 of file laspack_vector.C.
References libMesh::LaspackVector< T >::_vec, libMesh::NumericVector< T >::closed(), libMesh::initialized(), and libMesh::LaspackVector< T >::size().
 {
   libmesh_assert (this->initialized());
   libmesh_assert (v.closed());
   libmesh_assert_equal_to (this->size(), v.size());
   if (v.size() != 0)
     Asgn_VV (const_cast<QVector*>(&_vec),
              const_cast<QVector*>(&v._vec)
              );
 #ifndef NDEBUG
   this->_is_closed = true;
 #endif
   return *this;
 }
operator=() [2/5]
template<typename T> LaspackVector& libMesh::LaspackVector< T >::operator= (LaspackVector< T > &&) delete
operator=() [3/5]
template<typename T > NumericVector< T > & libMesh::LaspackVector< T >::operator= (const T s) override virtual
Sets all entries of the vector to the value s.
Returns
A reference to *this.
Implements libMesh::NumericVector< T >.
Definition at line 264 of file laspack_vector.C.
References libMesh::closed(), and libMesh::initialized().
 {
   libmesh_assert (this->initialized());
   libmesh_assert (this->closed());
   V_SetAllCmp (&_vec, s);
   return *this;
 }
operator=() [4/5]
template<typename T > NumericVector< T > & libMesh::LaspackVector< T >::operator= (const NumericVector< T > & v) override virtual
This looks like a copy assignment operator, but note that, unlike normal copy assignment operators, it is pure virtual. This function should be overridden in derived classes so that they can be copied correctly via references to the base class. This design usually isn't a good idea in general, but in this context it works because we usually don't have a mix of different kinds of NumericVectors active in the library at a single time.
Returns
A reference to *this as the base type.
Implements libMesh::NumericVector< T >.
Definition at line 278 of file laspack_vector.C.
 {
   // Make sure the NumericVector passed in is really a LaspackVector
   const LaspackVector<T> * v =
     cast_ptr<const LaspackVector<T> *>(&v_in);
   libmesh_assert(v);
   *this = *v;
   return *this;
 }
operator=() [5/5]
template<typename T > NumericVector< T > & libMesh::LaspackVector< T >::operator= (const std::vector< T > & v) override virtual
Sets (*this)(i) = v(i) for each entry of the vector.
Returns
A reference to *this as the base type.
Case 1: The vector is the same size of The global vector. Only add the local components.
Implements libMesh::NumericVector< T >.
Definition at line 317 of file laspack_vector.C.
 {
   if (this->size() == v.size())
     for (numeric_index_type i=0; i<v.size(); i++)
       this->set (i, v[i]);
   else
     libmesh_error_msg("this->size() = " << this->size() << " must be equal to v.size() = " << v.size());
   return *this;
 }
pointwise_mult()
template<typename T > void libMesh::LaspackVector< T >::pointwise_mult (const NumericVector< T > & vec1, const NumericVector< T > & vec2) override virtual
Computes (summation not implied) i.e. the pointwise (component-wise) product of vec1 and vec2, and stores the result in *this.
Implements libMesh::NumericVector< T >.
Definition at line 418 of file laspack_vector.C.
 {
   libmesh_not_implemented();
 }
print() [1/2]
template<typename T > void libMesh::NumericVector< T >::print (std::ostream & os = libMesh::out) const inline virtual inherited
Prints the local contents of the vector, by default to libMesh::out
Definition at line 916 of file numeric_vector.h.
 {
   libmesh_assert (this->initialized());
   os << "Size\tglobal =  " << this->size()
      << "\t\tlocal =  " << this->local_size() << std::endl;
   os << "#\tValue" << std::endl;
   for (numeric_index_type i=this->first_local_index(); i<this->last_local_index(); i++)
     os << i << "\t" << (*this)(i) << std::endl;
 }
print() [2/2]
template<> void libMesh::NumericVector< Complex >::print (std::ostream & os) const inline inherited
Definition at line 898 of file numeric_vector.h.
 {
   libmesh_assert (this->initialized());
   os << "Size\tglobal =  " << this->size()
      << "\t\tlocal =  " << this->local_size() << std::endl;
   // std::complex<>::operator<<() is defined, but use this form
   os << "#\tReal part\t\tImaginary part" << std::endl;
   for (numeric_index_type i=this->first_local_index(); i<this->last_local_index(); i++)
     os << i << "\t"
        << (*this)(i).real() << "\t\t"
        << (*this)(i).imag() << std::endl;
 }
print_global() [1/2]
template<typename T > void libMesh::NumericVector< T >::print_global (std::ostream & os = libMesh::out) const inline virtual inherited
Prints the global contents of the vector, by default to libMesh::out
Definition at line 953 of file numeric_vector.h.
 {
   libmesh_assert (this->initialized());
   std::vector<T> v(this->size());
   this->localize(v);
   // Right now we only want one copy of the output
   if (this->processor_id())
     return;
   os << "Size\tglobal =  " << this->size() << std::endl;
   os << "#\tValue" << std::endl;
   for (numeric_index_type i=0; i!=v.size(); i++)
     os << i << "\t" << v[i] << std::endl;
 }
print_global() [2/2]
template<> void libMesh::NumericVector< Complex >::print_global (std::ostream & os) const inline inherited
Definition at line 931 of file numeric_vector.h.
 {
   libmesh_assert (this->initialized());
   std::vector<Complex> v(this->size());
   this->localize(v);
   // Right now we only want one copy of the output
   if (this->processor_id())
     return;
   os << "Size\tglobal =  " << this->size() << std::endl;
   os << "#\tReal part\t\tImaginary part" << std::endl;
   for (numeric_index_type i=0; i!=v.size(); i++)
     os << i << "\t"
        << v[i].real() << "\t\t"
        << v[i].imag() << std::endl;
 }
print_info()
void libMesh::ReferenceCounter::print_info (std::ostream & out = libMesh::out) static inherited
Prints the reference information, by default to libMesh::out.
Definition at line 87 of file reference_counter.C.
References libMesh::ReferenceCounter::_enable_print_counter, and libMesh::ReferenceCounter::get_info().
 {
   if (_enable_print_counter)
     out_stream << ReferenceCounter::get_info();
 }
print_matlab()
template<typename T> virtual void libMesh::NumericVector< T >::print_matlab (const std::string & = "") const inline virtual inherited
Print the contents of the vector in Matlab's sparse matrix format. Optionally prints the vector to the file named name. If name is not specified it is dumped to the screen.
Reimplemented in libMesh::PetscVector< T >.
Definition at line 681 of file numeric_vector.h.
   {
     libmesh_not_implemented();
   }
processor_id()
processor_id_type libMesh::ParallelObject::processor_id () const inline inherited
Returns
The rank of this processor in the group.
Definition at line 101 of file parallel_object.h.
References libMesh::ParallelObject::_communicator, and libMesh::Parallel::Communicator::rank().
Referenced by libMesh::BoundaryInfo::_find_id_maps(), libMesh::EquationSystems::_read_impl(), libMesh::PetscDMWrapper::add_dofs_to_section(), libMesh::DistributedMesh::add_elem(), libMesh::BoundaryInfo::add_elements(), libMesh::DofMap::add_neighbors_to_send_list(), libMesh::DistributedMesh::add_node(), libMesh::UnstructuredMesh::all_second_order(), libMesh::MeshTools::Modification::all_tri(), libMesh::FEMSystem::assembly(), libMesh::EquationSystems::build_discontinuous_solution_vector(), libMesh::Nemesis_IO_Helper::build_element_and_node_maps(), libMesh::InfElemBuilder::build_inf_elem(), libMesh::BoundaryInfo::build_node_list_from_side_list(), libMesh::EquationSystems::build_parallel_elemental_solution_vector(), libMesh::DistributedMesh::clear(), libMesh::ExodusII_IO_Helper::close(), libMesh::Nemesis_IO_Helper::compute_border_node_ids(), libMesh::Nemesis_IO_Helper::compute_communication_map_parameters(), libMesh::Nemesis_IO_Helper::compute_internal_and_border_elems_and_internal_nodes(), libMesh::Nemesis_IO_Helper::compute_node_communication_maps(), libMesh::Nemesis_IO_Helper::compute_num_global_elem_blocks(), libMesh::Nemesis_IO_Helper::compute_num_global_nodesets(), libMesh::Nemesis_IO_Helper::compute_num_global_sidesets(), libMesh::Nemesis_IO_Helper::construct_nemesis_filename(), libMesh::MeshTools::correct_node_proc_ids(), libMesh::ExodusII_IO_Helper::create(), libMesh::DistributedMesh::delete_elem(), libMesh::DistributedMesh::delete_node(), libMesh::MeshCommunication::delete_remote_elements(), libMesh::DofMap::distribute_dofs(), libMesh::DofMap::distribute_local_dofs_node_major(), libMesh::DofMap::distribute_local_dofs_var_major(), libMesh::DistributedMesh::DistributedMesh(), libMesh::DofMap::end_dof(), libMesh::DofMap::end_old_dof(), libMesh::EnsightIO::EnsightIO(), libMesh::MeshFunction::find_element(), libMesh::MeshFunction::find_elements(), libMesh::UnstructuredMesh::find_neighbors(), libMesh::DofMap::first_dof(), libMesh::DofMap::first_old_dof(), libMesh::Nemesis_IO_Helper::get_cmap_params(), libMesh::Nemesis_IO_Helper::get_eb_info_global(), libMesh::Nemesis_IO_Helper::get_elem_cmap(), libMesh::Nemesis_IO_Helper::get_elem_map(), libMesh::MeshBase::get_info(), libMesh::DofMap::get_info(), libMesh::Nemesis_IO_Helper::get_init_global(), libMesh::Nemesis_IO_Helper::get_init_info(), libMesh::Nemesis_IO_Helper::get_loadbal_param(), libMesh::Nemesis_IO_Helper::get_node_cmap(), libMesh::Nemesis_IO_Helper::get_node_map(), libMesh::Nemesis_IO_Helper::get_ns_param_global(), libMesh::Nemesis_IO_Helper::get_ss_param_global(), libMesh::SparsityPattern::Build::handle_vi_vj(), libMesh::SystemSubsetBySubdomain::init(), libMesh::ExodusII_IO_Helper::initialize(), libMesh::ExodusII_IO_Helper::initialize_element_variables(), libMesh::ExodusII_IO_Helper::initialize_global_variables(), libMesh::ExodusII_IO_Helper::initialize_nodal_variables(), libMesh::DistributedMesh::insert_elem(), libMesh::DofMap::is_evaluable(), libMesh::SparsityPattern::Build::join(), libMesh::DofMap::last_dof(), libMesh::MeshTools::libmesh_assert_consistent_distributed(), libMesh::MeshTools::libmesh_assert_consistent_distributed_nodes(), libMesh::MeshTools::libmesh_assert_contiguous_dof_ids(), libMesh::MeshTools::libmesh_assert_parallel_consistent_procids< Elem >(), libMesh::MeshTools::libmesh_assert_valid_neighbors(), libMesh::DistributedMesh::libmesh_assert_valid_parallel_object_ids(), libMesh::DofMap::local_variable_indices(), libMesh::MeshRefinement::make_coarsening_compatible(), libMesh::MeshBase::n_active_local_elem(), libMesh::BoundaryInfo::n_boundary_conds(), libMesh::BoundaryInfo::n_edge_conds(), libMesh::DofMap::n_local_dofs(), libMesh::System::n_local_dofs(), libMesh::MeshBase::n_local_elem(), libMesh::MeshBase::n_local_nodes(), libMesh::BoundaryInfo::n_nodeset_conds(), libMesh::BoundaryInfo::n_shellface_conds(), libMesh::SparsityPattern::Build::operator()(), libMesh::DistributedMesh::own_node(), libMesh::System::point_gradient(), libMesh::System::point_hessian(), libMesh::System::point_value(), libMesh::Nemesis_IO_Helper::put_cmap_params(), libMesh::Nemesis_IO_Helper::put_elem_cmap(), libMesh::Nemesis_IO_Helper::put_elem_map(), libMesh::Nemesis_IO_Helper::put_loadbal_param(), libMesh::Nemesis_IO_Helper::put_node_cmap(), libMesh::Nemesis_IO_Helper::put_node_map(), libMesh::NameBasedIO::read(), libMesh::Nemesis_IO::read(), libMesh::XdrIO::read(), libMesh::CheckpointIO::read(), libMesh::ExodusII_IO_Helper::read_elem_num_map(), libMesh::ExodusII_IO_Helper::read_global_values(), libMesh::CheckpointIO::read_header(), libMesh::XdrIO::read_header(), libMesh::System::read_header(), libMesh::System::read_legacy_data(), libMesh::ExodusII_IO_Helper::read_node_num_map(), libMesh::System::read_parallel_data(), libMesh::System::read_SCALAR_dofs(), libMesh::XdrIO::read_serialized_bc_names(), libMesh::XdrIO::read_serialized_bcs_helper(), libMesh::System::read_serialized_blocked_dof_objects(), libMesh::XdrIO::read_serialized_connectivity(), libMesh::System::read_serialized_data(), libMesh::XdrIO::read_serialized_nodes(), libMesh::XdrIO::read_serialized_nodesets(), libMesh::XdrIO::read_serialized_subdomain_names(), libMesh::System::read_serialized_vector(), libMesh::System::read_serialized_vectors(), libMesh::DistributedMesh::renumber_dof_objects(), libMesh::CheckpointIO::select_split_config(), libMesh::DofMap::set_nonlocal_dof_objects(), libMesh::PetscDMWrapper::set_point_range_in_section(), libMesh::LaplaceMeshSmoother::smooth(), libMesh::MeshTools::total_weight(), libMesh::MeshRefinement::uniformly_coarsen(), libMesh::Parallel::Packing< T >::unpack(), libMesh::DistributedMesh::update_parallel_id_counts(), libMesh::NameBasedIO::write(), libMesh::XdrIO::write(), libMesh::CheckpointIO::write(), libMesh::EquationSystems::write(), libMesh::GMVIO::write_discontinuous_gmv(), libMesh::ExodusII_IO::write_element_data(), libMesh::ExodusII_IO_Helper::write_element_values(), libMesh::ExodusII_IO_Helper::write_elements(), libMesh::ExodusII_IO::write_global_data(), libMesh::ExodusII_IO_Helper::write_global_values(), libMesh::System::write_header(), libMesh::ExodusII_IO::write_information_records(), libMesh::ExodusII_IO_Helper::write_information_records(), libMesh::ExodusII_IO_Helper::write_nodal_coordinates(), libMesh::UCDIO::write_nodal_data(), libMesh::ExodusII_IO::write_nodal_data(), libMesh::ExodusII_IO::write_nodal_data_discontinuous(), libMesh::ExodusII_IO_Helper::write_nodal_values(), libMesh::Nemesis_IO_Helper::write_nodesets(), libMesh::ExodusII_IO_Helper::write_nodesets(), libMesh::System::write_parallel_data(), libMesh::System::write_SCALAR_dofs(), libMesh::XdrIO::write_serialized_bc_names(), libMesh::XdrIO::write_serialized_bcs_helper(), libMesh::System::write_serialized_blocked_dof_objects(), libMesh::XdrIO::write_serialized_connectivity(), libMesh::System::write_serialized_data(), libMesh::XdrIO::write_serialized_nodes(), libMesh::XdrIO::write_serialized_nodesets(), libMesh::XdrIO::write_serialized_subdomain_names(), libMesh::System::write_serialized_vector(), libMesh::System::write_serialized_vectors(), libMesh::Nemesis_IO_Helper::write_sidesets(), libMesh::ExodusII_IO_Helper::write_sidesets(), libMesh::ExodusII_IO::write_timestep(), libMesh::ExodusII_IO_Helper::write_timestep(), and libMesh::ExodusII_IO::write_timestep_discontinuous().
   { return cast_int<processor_id_type>(_communicator.rank()); }
reciprocal()
template<typename T > void libMesh::LaspackVector< T >::reciprocal () override virtual
Computes the pointwise reciprocal,
Implements libMesh::NumericVector< T >.
Definition at line 124 of file laspack_vector.C.
 {
   const numeric_index_type n = this->size();
   for (numeric_index_type i=0; i<n; i++)
     {
       T v = (*this)(i);
       // Don't divide by zero!
       libmesh_assert_not_equal_to (v, T(0));
       this->set(i, 1. / v);
     }
 }
scale()
template<typename T > void libMesh::LaspackVector< T >::scale (const T factor) override virtual
Scale each element of the vector by the given factor.
Implements libMesh::NumericVector< T >.
Definition at line 229 of file laspack_vector.C.
References libMesh::initialized().
 {
   libmesh_assert (this->initialized());
   Asgn_VV(&_vec, Mul_SV (factor, &_vec));
 }
set()
template<typename T > void libMesh::LaspackVector< T >::set (const numeric_index_type i, const T value) inline override virtual
Sets v(i) = value.
Implements libMesh::NumericVector< T >.
Definition at line 494 of file laspack_vector.h.
References libMesh::initialized(), and value.
 {
   libmesh_assert (this->initialized());
   libmesh_assert_less (i, this->size());
   V_SetCmp (&_vec, i+1, value);
 #ifndef NDEBUG
   this->_is_closed = false;
 #endif
 }
size()
template<typename T > numeric_index_type libMesh::LaspackVector< T >::size () const inline override virtual
Returns
The size of the vector.
Implements libMesh::NumericVector< T >.
Definition at line 450 of file laspack_vector.h.
References libMesh::initialized().
Referenced by libMesh::LaspackVector< T >::add(), and libMesh::LaspackVector< T >::operator=().
 {
   libmesh_assert (this->initialized());
   return static_cast<numeric_index_type>(V_GetDim(const_cast<QVector*>(&_vec)));
 }
subset_l1_norm()
template<class T > Real libMesh::NumericVector< T >::subset_l1_norm (const std::set< numeric_index_type > & indices) const virtual inherited
Returns
The -norm of the vector, i.e. the sum of the absolute values for the specified entries in the vector.
Note
The indices must necessarily live on this processor.
Definition at line 311 of file numeric_vector.C.
Referenced by libMesh::System::discrete_var_norm().
 {
   const NumericVector<T> & v = *this;
   Real norm = 0;
   for (const auto & index : indices)
     norm += std::abs(v(index));
   this->comm().sum(norm);
   return norm;
 }
subset_l2_norm()
template<class T > Real libMesh::NumericVector< T >::subset_l2_norm (const std::set< numeric_index_type > & indices) const virtual inherited
Returns
The -norm of the vector, i.e. the square root of the sum of the squares of the elements for the specified entries in the vector.
Note
The indices must necessarily live on this processor.
Definition at line 326 of file numeric_vector.C.
Referenced by libMesh::System::discrete_var_norm().
 {
   const NumericVector<T> & v = *this;
   Real norm = 0;
   for (const auto & index : indices)
     norm += TensorTools::norm_sq(v(index));
   this->comm().sum(norm);
   return std::sqrt(norm);
 }
subset_linfty_norm()
template<class T > Real libMesh::NumericVector< T >::subset_linfty_norm (const std::set< numeric_index_type > & indices) const virtual inherited
Returns
The maximum absolute value of the specified entries of this vector, which is the -norm of a vector.
Note
The indices must necessarily live on this processor.
Definition at line 341 of file numeric_vector.C.
Referenced by libMesh::System::discrete_var_norm().
 {
   const NumericVector<T> & v = *this;
   Real norm = 0;
   for (const auto & index : indices)
     {
       Real value = std::abs(v(index));
       if (value > norm)
         norm = value;
     }
   this->comm().max(norm);
   return norm;
 }
sum()
template<typename T > T libMesh::LaspackVector< T >::sum () const override virtual
Returns
The sum of all values in the vector.
Implements libMesh::NumericVector< T >.
Definition at line 37 of file laspack_vector.C.
References libMesh::closed().
 {
   libmesh_assert (this->closed());
   T _sum = 0;
   const numeric_index_type n = this->size();
   for (numeric_index_type i=0; i!=n; ++i)
     _sum += (*this)(i);
   return _sum;
 }
swap()
template<typename T > void libMesh::LaspackVector< T >::swap (NumericVector< T > & v) inline override virtual
Swaps the contents of this with v. There should be enough indirection in subclasses to make this an O(1) header-swap operation.
Reimplemented from libMesh::NumericVector< T >.
Definition at line 540 of file laspack_vector.h.
References swap().
 {
   LaspackVector<T> & v = cast_ref<LaspackVector<T> &>(other);
   // This is all grossly dependent on Laspack version...
   std::swap(_vec.Name, v._vec.Name);
   std::swap(_vec.Dim, v._vec.Dim);
   std::swap(_vec.Instance, v._vec.Instance);
   std::swap(_vec.LockLevel, v._vec.LockLevel);
   std::swap(_vec.Multipl, v._vec.Multipl);
   std::swap(_vec.OwnData, v._vec.OwnData);
   // This should still be O(1), since _vec.Cmp is just a pointer to
   // data on the heap
   std::swap(_vec.Cmp, v._vec.Cmp);
 }
type() [1/2]
template<typename T> ParallelType libMesh::NumericVector< T >::type () const inline inherited
Returns
The type (SERIAL, PARALLEL, GHOSTED) of the vector.
Definition at line 154 of file numeric_vector.h.
Referenced by libMesh::DofMap::enforce_adjoint_constraints_exactly(), libMesh::DofMap::enforce_constraints_exactly(), libMesh::EpetraVector< T >::EpetraVector(), libMesh::MeshFunction::find_element(), libMesh::MeshFunction::find_elements(), libMesh::DistributedVector< T >::init(), libMesh::EigenSparseVector< T >::init(), libMesh::LaspackVector< T >::init(), libMesh::EpetraVector< T >::init(), libMesh::PetscVector< T >::localize(), libMesh::PetscVector< T >::operator=(), and libMesh::System::read_serialized_vector().
 { return _type; }
type() [2/2]
template<typename T> ParallelType& libMesh::NumericVector< T >::type () inline inherited
Returns
The type (SERIAL, PARALLEL, GHOSTED) of the vector.
Definition at line 159 of file numeric_vector.h.
 { return _type; }
zero()
template<typename T > void libMesh::LaspackVector< T >::zero () inline override virtual
Set all entries to zero. Equivalent to v = 0, but more obvious and faster.
Implements libMesh::NumericVector< T >.
Definition at line 410 of file laspack_vector.h.
References libMesh::closed(), and libMesh::initialized().
Referenced by libMesh::LaspackLinearSolver< T >::adjoint_solve(), and libMesh::LaspackLinearSolver< T >::solve().
 {
   libmesh_assert (this->initialized());
   libmesh_assert (this->closed());
   V_SetAllCmp (&_vec, 0.);
 }
zero_clone()
template<typename T > std::unique_ptr< NumericVector< T > > libMesh::LaspackVector< T >::zero_clone () const inline override virtual
Returns
A smart pointer to a copy of this vector with the same type, size, and partitioning, but with all zero entries.
Note
This must be overridden in the derived classes.
Implements libMesh::NumericVector< T >.
Definition at line 422 of file laspack_vector.h.
References libMesh::NumericVector< T >::init().
 {
   NumericVector<T> * cloned_vector = new LaspackVector<T>(this->comm());
   cloned_vector->init(*this);
   return std::unique_ptr<NumericVector<T>>(cloned_vector);
 }
Friends And Related Function Documentation
LaspackLinearSolver< T >
template<typename T> friend class LaspackLinearSolver< T > friend
Make other Laspack datatypes friends
Definition at line 239 of file laspack_vector.h.
Member Data Documentation
_communicator
const Parallel::Communicator& libMesh::ParallelObject::_communicator protected inherited
Definition at line 107 of file parallel_object.h.
Referenced by libMesh::EquationSystems::build_parallel_elemental_solution_vector(), libMesh::EquationSystems::build_parallel_solution_vector(), libMesh::ParallelObject::comm(), libMesh::ParallelObject::n_processors(), libMesh::ParallelObject::operator=(), and libMesh::ParallelObject::processor_id().
_counts
ReferenceCounter::Counts libMesh::ReferenceCounter::_counts static protected inherited
Actually holds the data.
Definition at line 122 of file reference_counter.h.
Referenced by libMesh::ReferenceCounter::get_info(), libMesh::ReferenceCounter::increment_constructor_count(), and libMesh::ReferenceCounter::increment_destructor_count().
_enable_print_counter
bool libMesh::ReferenceCounter::_enable_print_counter = true static protected inherited
Flag to control whether reference count information is printed when print_info is called.
Definition at line 141 of file reference_counter.h.
Referenced by libMesh::ReferenceCounter::disable_print_counter_info(), libMesh::ReferenceCounter::enable_print_counter_info(), and libMesh::ReferenceCounter::print_info().
_is_closed
template<typename T> bool libMesh::NumericVector< T >::_is_closed protected inherited
Flag which tracks whether the vector's values are consistent on all processors after insertion or addition of values has occurred on some or all processors.
Definition at line 712 of file numeric_vector.h.
Referenced by libMesh::NumericVector< Number >::closed(), libMesh::EpetraVector< T >::EpetraVector(), libMesh::DistributedVector< T >::localize(), libMesh::DistributedVector< T >::operator=(), and libMesh::PetscVector< T >::PetscVector().
_is_initialized
template<typename T> bool libMesh::NumericVector< T >::_is_initialized protected inherited
true once init() has been called.
Definition at line 717 of file numeric_vector.h.
Referenced by libMesh::PetscVector< T >::create_subvector(), libMesh::EpetraVector< T >::EpetraVector(), libMesh::NumericVector< Number >::initialized(), libMesh::DistributedVector< T >::localize(), libMesh::DistributedVector< T >::operator=(), and libMesh::PetscVector< T >::PetscVector().
_mutex
Threads::spin_mutex libMesh::ReferenceCounter::_mutex static protected inherited
Mutual exclusion object to enable thread-safe reference counting.
Definition at line 135 of file reference_counter.h.
_n_objects
Threads::atomic< unsigned int > libMesh::ReferenceCounter::_n_objects static protected inherited
The number of objects. Print the reference count information when the number returns to 0.
Definition at line 130 of file reference_counter.h.
Referenced by libMesh::ReferenceCounter::n_objects(), libMesh::ReferenceCounter::ReferenceCounter(), and libMesh::ReferenceCounter::~ReferenceCounter().
_type
template<typename T> ParallelType libMesh::NumericVector< T >::_type protected inherited
Type of vector.
Definition at line 722 of file numeric_vector.h.
Referenced by libMesh::DistributedVector< T >::DistributedVector(), libMesh::EigenSparseVector< T >::EigenSparseVector(), libMesh::EpetraVector< T >::EpetraVector(), libMesh::PetscVector< T >::init(), libMesh::LaspackVector< T >::LaspackVector(), libMesh::PetscVector< T >::operator=(), libMesh::PetscVector< T >::PetscVector(), and libMesh::NumericVector< Number >::type().
_vec
template<typename T> QVector libMesh::LaspackVector< T >::_vec private
Actual Laspack vector datatype to hold vector entries
Definition at line 234 of file laspack_vector.h.
Referenced by libMesh::LaspackVector< T >::add_vector(), libMesh::LaspackVector< T >::dot(), and libMesh::LaspackVector< T >::operator=().
The documentation for this class was generated from the following files:
laspack_matrix.h
laspack_vector.h
laspack_vector.C