libMesh: libMesh::Parallel::Packing< Elem * > Class Template Reference
SomeWebsiteLogo
libMesh::Parallel::Packing< Elem * > Class Template Reference
#include <parallel_elem.h>
Public Types
typedef largest_id_type buffer_type
Public Member Functions
template<>
Elem * unpack (std::vector< largest_id_type >::const_iterator in, MeshBase *mesh)
template<>
Elem * unpack (std::vector< largest_id_type >::const_iterator in, DistributedMesh *mesh)
template<>
Elem * unpack (std::vector< largest_id_type >::const_iterator in, ParallelMesh *mesh)
Static Public Member Functions
template<typename OutputIter , typename Context >
static void pack (Elem *const &object, OutputIter data_out, const Context *context)
template<typename Context >
static unsigned int packable_size (Elem *const &object, const Context *context)
template<typename BufferIter >
static unsigned int packed_size (BufferIter iter)
template<typename BufferIter , typename Context >
static Elem * unpack (BufferIter in, Context *ctx)
Detailed Description
template<>
class libMesh::Parallel::Packing< Elem * >
Definition at line 57 of file parallel_elem.h.
Member Typedef Documentation
typedef largest_id_type libMesh::Parallel::Packing< Elem * >::buffer_type
Definition at line 60 of file parallel_elem.h.
Member Function Documentation
template<typename OutputIter , typename Context > static void libMesh::Parallel::Packing< Elem * >::pack (Elem *const & object, OutputIter data_out, const Context * context) inline static
Definition at line 63 of file parallel_elem.h.
References libMesh::Parallel::Packing< T >::pack().
   { return Packing<const Elem *>::pack(object, data_out, context); }
template<typename Context > static unsigned int libMesh::Parallel::Packing< Elem * >::packable_size (Elem *const & object, const Context * context) inline static
Definition at line 69 of file parallel_elem.h.
References libMesh::Parallel::Packing< T >::packable_size().
   { return Packing<const Elem *>::packable_size(object, context); }
template<typename BufferIter > static unsigned int libMesh::Parallel::Packing< Elem * >::packed_size (BufferIter iter) inline static
Definition at line 74 of file parallel_elem.h.
References libMesh::ctx, and libMesh::Parallel::Packing< T >::packed_size().
   { return Packing<const Elem *>::packed_size(iter); }
template<typename BufferIter , typename Context > static Elem* libMesh::Parallel::Packing< Elem * >::unpack (BufferIter in, Context * ctx) static
template<> Elem* libMesh::Parallel::Packing< Elem * >::unpack (std::vector< largest_id_type >::const_iterator in, MeshBase * mesh)
Definition at line 356 of file parallel_elem.C.
References libMesh::Elem::active(), libMesh::Elem::add_child(), libMesh::BoundaryInfo::add_edge(), libMesh::BoundaryInfo::add_shellface(), libMesh::BoundaryInfo::add_side(), libMesh::Elem::build(), libMesh::Elem::child_ptr(), libMesh::Elem::dim(), libMesh::MeshBase::elem_ptr(), libMesh::MeshBase::get_boundary_info(), libMesh::Elem::hack_p_level(), libMesh::Elem::has_children(), libMesh::DofObject::id(), libMesh::Elem::interior_parent(), libMesh::INVALID_ELEM, libMesh::DofObject::invalid_id, libMesh::DofObject::invalid_processor_id, libMesh::Elem::INVALID_REFINEMENTSTATE, libMesh::Elem::level(), libMesh::libmesh_assert(), libmesh_nullptr, libMesh::Elem::make_links_to_me_local(), libMesh::Elem::n_children(), libMesh::Elem::n_edges(), libMesh::Elem::n_neighbors(), n_nodes, libMesh::Elem::n_nodes(), libMesh::n_processors(), libMesh::Elem::n_sides(), libMesh::Elem::neighbor_ptr(), libMesh::Elem::node_id(), libMesh::MeshBase::node_ptr(), libMesh::Elem::p_level(), libMesh::Elem::p_refinement_flag(), libMesh::DofObject::packed_indexing_size(), libMesh::Elem::parent(), libMesh::processor_id(), libMesh::ParallelObject::processor_id(), libMesh::DofObject::processor_id(), libMesh::MeshBase::query_elem_ptr(), libMesh::Elem::refinement_flag(), libMesh::remote_elem, libMesh::DofObject::set_id(), libMesh::Elem::set_interior_parent(), libMesh::Elem::set_neighbor(), libMesh::Elem::set_node(), libMesh::Elem::set_p_level(), libMesh::Elem::set_p_refinement_flag(), libMesh::Elem::set_refinement_flag(), libMesh::DofObject::set_unique_id(), libMesh::Elem::subactive(), libMesh::Elem::subdomain_id(), libMesh::Elem::type(), libMesh::Elem::type_to_n_nodes_map, and libMesh::DofObject::unpack_indexing().
 {
 #ifndef NDEBUG
   const std::vector<largest_id_type>::const_iterator original_in = in;
   const largest_id_type incoming_header = *in++;
   libmesh_assert_equal_to (incoming_header, elem_magic_header);
 #endif
   // int 0: level
   const unsigned int level =
     cast_int<unsigned int>(*in++);
 #ifdef LIBMESH_ENABLE_AMR
   // int 1: p level
   const unsigned int p_level =
     cast_int<unsigned int>(*in++);
   // int 2: refinement flag and encoded has_children
   const int rflag = cast_int<int>(*in++);
   const int invalid_rflag =
     cast_int<int>(Elem::INVALID_REFINEMENTSTATE);
   libmesh_assert_greater_equal (rflag, 0);
   libmesh_assert_less (rflag, invalid_rflag*2+1);
   const bool has_children = (rflag > invalid_rflag);
   const Elem::RefinementState refinement_flag = has_children ?
     cast_int<Elem::RefinementState>(rflag - invalid_rflag - 1) :
     cast_int<Elem::RefinementState>(rflag);
   // int 3: p refinement flag
   const int pflag = cast_int<int>(*in++);
   libmesh_assert_greater_equal (pflag, 0);
   libmesh_assert_less (pflag, Elem::INVALID_REFINEMENTSTATE);
   const Elem::RefinementState p_refinement_flag =
     cast_int<Elem::RefinementState>(pflag);
 #else
   in += 3;
 #endif // LIBMESH_ENABLE_AMR
   // int 4: element type
   const int typeint = cast_int<int>(*in++);
   libmesh_assert_greater_equal (typeint, 0);
   libmesh_assert_less (typeint, INVALID_ELEM);
   const ElemType type =
     cast_int<ElemType>(typeint);
   const unsigned int n_nodes =
     Elem::type_to_n_nodes_map[type];
   // int 5: processor id
   const processor_id_type processor_id =
     cast_int<processor_id_type>(*in++);
   libmesh_assert (processor_id < mesh->n_processors() ||
                   processor_id == DofObject::invalid_processor_id);
   // int 6: subdomain id
   const subdomain_id_type subdomain_id =
     cast_int<subdomain_id_type>(*in++);
   // int 7: dof object id
   const dof_id_type id =
     cast_int<dof_id_type>(*in++);
   libmesh_assert_not_equal_to (id, DofObject::invalid_id);
 #ifdef LIBMESH_ENABLE_UNIQUE_ID
   // int 8: dof object unique id
   const unique_id_type unique_id =
     cast_int<unique_id_type>(*in++);
 #endif
 #ifdef LIBMESH_ENABLE_AMR
   // int 9: parent dof object id.
   // Note: If level==0, then (*in) == invalid_id.  In
   // this case, the equality check in cast_int<unsigned>(*in) will
   // never succeed.  Therefore, we should only attempt the more
   // rigorous cast verification in cases where level != 0.
   const dof_id_type parent_id =
     (level == 0)
     ? static_cast<dof_id_type>(*in++)
     : cast_int<dof_id_type>(*in++);
   libmesh_assert (level == 0 || parent_id != DofObject::invalid_id);
   libmesh_assert (level != 0 || parent_id == DofObject::invalid_id);
   // int 10: local child id
   // Note: If level==0, then which_child_am_i is not valid, so don't
   // do the more rigorous cast verification.
   const unsigned int which_child_am_i =
     (level == 0)
     ? static_cast<unsigned int>(*in++)
     : cast_int<unsigned int>(*in++);
 #else
   in += 2;
 #endif // LIBMESH_ENABLE_AMR
   const dof_id_type interior_parent_id =
     static_cast<dof_id_type>(*in++);
   // Make sure we don't miscount above when adding the "magic" header
   // plus the real data header
   libmesh_assert_equal_to (in - original_in, header_size + 1);
   Elem * elem = mesh->query_elem_ptr(id);
   // if we already have this element, make sure its
   // properties match, and update any missing neighbor
   // links, but then go on
   if (elem)
     {
       libmesh_assert_equal_to (elem->level(), level);
       libmesh_assert_equal_to (elem->id(), id);
       //#ifdef LIBMESH_ENABLE_UNIQUE_ID
       // No check for unique id sanity
       //#endif
       libmesh_assert_equal_to (elem->processor_id(), processor_id);
       libmesh_assert_equal_to (elem->subdomain_id(), subdomain_id);
       libmesh_assert_equal_to (elem->type(), type);
       libmesh_assert_equal_to (elem->n_nodes(), n_nodes);
 #ifndef NDEBUG
       // All our nodes should be correct
       for (unsigned int i=0; i != n_nodes; ++i)
         libmesh_assert(elem->node_id(i) ==
                        cast_int<dof_id_type>(*in++));
 #else
       in += n_nodes;
 #endif
 #ifdef LIBMESH_ENABLE_AMR
       libmesh_assert_equal_to (elem->refinement_flag(), refinement_flag);
       libmesh_assert_equal_to (elem->has_children(), has_children);
 #ifdef DEBUG
       if (elem->active())
         {
           libmesh_assert_equal_to (elem->p_level(), p_level);
           libmesh_assert_equal_to (elem->p_refinement_flag(), p_refinement_flag);
         }
 #endif
       libmesh_assert (!level || elem->parent() != libmesh_nullptr);
       libmesh_assert (!level || elem->parent()->id() == parent_id);
       libmesh_assert (!level || elem->parent()->child_ptr(which_child_am_i) == elem);
 #endif
       // Our interior_parent link should be "close to" correct - we
       // may have to update it, but we can check for some
       // inconsistencies.
       {
         // If the sending processor sees no interior_parent here, we'd
         // better agree.
         if (interior_parent_id == DofObject::invalid_id)
           {
             if (elem->dim() < LIBMESH_DIM)
               libmesh_assert (!(elem->interior_parent()));
           }
         // If the sending processor has a remote_elem interior_parent,
         // then all we know is that we'd better have *some*
         // interior_parent
         else if (interior_parent_id == remote_elem->id())
           {
             libmesh_assert(elem->interior_parent());
           }
         else
           {
             Elem * ip = mesh->query_elem_ptr(interior_parent_id);
             // The sending processor sees an interior parent here, so
             // if we don't have that interior element, then we'd
             // better have a remote_elem signifying that fact.
             if (!ip)
               libmesh_assert_equal_to (elem->interior_parent(), remote_elem);
             else
               {
                 // The sending processor has an interior_parent here,
                 // and we have that element, but that does *NOT* mean
                 // we're already linking to it.  Perhaps we initially
                 // received elem from a processor on which the
                 // interior_parent link was remote?
                 libmesh_assert(elem->interior_parent() == ip ||
                                elem->interior_parent() == remote_elem);
                 // If the link was originally remote, update it
                 if (elem->interior_parent() == remote_elem)
                   {
                     elem->set_interior_parent(ip);
                   }
               }
           }
       }
       // Our neighbor links should be "close to" correct - we may have
       // to update a remote_elem link, and we can check for possible
       // inconsistencies along the way.
       //
       // For subactive elements, we don't bother keeping neighbor
       // links in good shape, so there's nothing we need to set or can
       // safely assert here.
       if (!elem->subactive())
         for (unsigned int n=0; n != elem->n_neighbors(); ++n)
           {
             const dof_id_type neighbor_id =
               cast_int<dof_id_type>(*in++);
             // If the sending processor sees a domain boundary here,
             // we'd better agree.
             if (neighbor_id == DofObject::invalid_id)
               {
                 libmesh_assert (!(elem->neighbor_ptr(n)));
                 continue;
               }
             // If the sending processor has a remote_elem neighbor here,
             // then all we know is that we'd better *not* have a domain
             // boundary.
             if (neighbor_id == remote_elem->id())
               {
                 libmesh_assert(elem->neighbor_ptr(n));
                 continue;
               }
             Elem * neigh = mesh->query_elem_ptr(neighbor_id);
             // The sending processor sees a neighbor here, so if we
             // don't have that neighboring element, then we'd better
             // have a remote_elem signifying that fact.
             if (!neigh)
               {
                 libmesh_assert_equal_to (elem->neighbor_ptr(n), remote_elem);
                 continue;
               }
             // The sending processor has a neighbor here, and we have
             // that element, but that does *NOT* mean we're already
             // linking to it.  Perhaps we initially received both elem
             // and neigh from processors on which their mutual link was
             // remote?
             libmesh_assert(elem->neighbor_ptr(n) == neigh ||
                            elem->neighbor_ptr(n) == remote_elem);
             // If the link was originally remote, we should update it,
             // and make sure the appropriate parts of its family link
             // back to us.
             if (elem->neighbor_ptr(n) == remote_elem)
               {
                 elem->set_neighbor(n, neigh);
                 elem->make_links_to_me_local(n);
               }
           }
       // Our p level and refinement flags should be "close to" correct
       // if we're not an active element - we might have a p level
       // increased or decreased by changes in remote_elem children.
       //
       // But if we have remote_elem children, then we shouldn't be
       // doing a projection on this inactive element on this
       // processor, so we won't need correct p settings.  Couldn't
       // hurt to update, though.
 #ifdef LIBMESH_ENABLE_AMR
       if (elem->processor_id() != mesh->processor_id())
         {
           elem->hack_p_level(p_level);
           elem->set_p_refinement_flag(p_refinement_flag);
         }
 #endif // LIBMESH_ENABLE_AMR
       // FIXME: We should add some debug mode tests to ensure that the
       // encoded indexing and boundary conditions are consistent.
     }
   else
     {
       // We don't already have the element, so we need to create it.
       // Find the parent if necessary
       Elem * parent = libmesh_nullptr;
 #ifdef LIBMESH_ENABLE_AMR
       // Find a child element's parent
       if (level > 0)
         {
           // Note that we must be very careful to construct the send
           // connectivity so that parents are encountered before
           // children.  If we get here and can't find the parent that
           // is a fatal error.
           parent = mesh->elem_ptr(parent_id);
         }
       // Or assert that the sending processor sees no parent
       else
         libmesh_assert_equal_to (parent_id, DofObject::invalid_id);
 #else
       // No non-level-0 elements without AMR
       libmesh_assert_equal_to (level, 0);
 #endif
       elem = Elem::build(type,parent).release();
       libmesh_assert (elem);
 #ifdef LIBMESH_ENABLE_AMR
       if (level != 0)
         {
           // Since this is a newly created element, the parent must
           // have previously thought of this child as a remote element.
           libmesh_assert_equal_to (parent->child_ptr(which_child_am_i), remote_elem);
           parent->add_child(elem, which_child_am_i);
         }
       // Assign the refinement flags and levels
       elem->set_p_level(p_level);
       elem->set_refinement_flag(refinement_flag);
       elem->set_p_refinement_flag(p_refinement_flag);
       libmesh_assert_equal_to (elem->level(), level);
       // If this element should have children, assign remote_elem to
       // all of them for now, for consistency.  Later unpacked
       // elements may overwrite that.
       if (has_children)
         for (unsigned int c=0; c != elem->n_children(); ++c)
           elem->add_child(const_cast<RemoteElem *>(remote_elem), c);
 #endif // LIBMESH_ENABLE_AMR
       // Assign the IDs
       elem->subdomain_id()  = subdomain_id;
       elem->processor_id()  = processor_id;
       elem->set_id()        = id;
 #ifdef LIBMESH_ENABLE_UNIQUE_ID
       elem->set_unique_id() = unique_id;
 #endif
       // Assign the connectivity
       libmesh_assert_equal_to (elem->n_nodes(), n_nodes);
       for (unsigned int n=0; n != n_nodes; n++)
         elem->set_node(n) =
           mesh->node_ptr
           (cast_int<dof_id_type>(*in++));
       // Set interior_parent if found
       {
         // We may be unpacking an element that was a ghost element on the
         // sender, in which case the element's interior_parent may not be
         // known by the packed element.  We'll have to set such
         // interior_parents to remote_elem ourselves and wait for a
         // later packed element to give us better information.
         if (interior_parent_id == remote_elem->id())
           {
             elem->set_interior_parent
               (const_cast<RemoteElem *>(remote_elem));
           }
         else if (interior_parent_id != DofObject::invalid_id)
           {
             // If we don't have the interior parent element, then it's
             // a remote_elem until we get it.
             Elem * ip = mesh->query_elem_ptr(interior_parent_id);
             if (!ip )
               elem->set_interior_parent
                 (const_cast<RemoteElem *>(remote_elem));
             else
               elem->set_interior_parent(ip);
           }
       }
       for (unsigned int n=0; n<elem->n_neighbors(); n++)
         {
           const dof_id_type neighbor_id =
             cast_int<dof_id_type>(*in++);
           if (neighbor_id == DofObject::invalid_id)
             continue;
           // We may be unpacking an element that was a ghost element on the
           // sender, in which case the element's neighbors may not all be
           // known by the packed element.  We'll have to set such
           // neighbors to remote_elem ourselves and wait for a later
           // packed element to give us better information.
           if (neighbor_id == remote_elem->id())
             {
               elem->set_neighbor(n, const_cast<RemoteElem *>(remote_elem));
               continue;
             }
           // If we don't have the neighbor element, then it's a
           // remote_elem until we get it.
           Elem * neigh = mesh->query_elem_ptr(neighbor_id);
           if (!neigh)
             {
               elem->set_neighbor(n, const_cast<RemoteElem *>(remote_elem));
               continue;
             }
           // If we have the neighbor element, then link to it, and
           // make sure the appropriate parts of its family link back
           // to us.
           elem->set_neighbor(n, neigh);
           elem->make_links_to_me_local(n);
         }
       elem->unpack_indexing(in);
     }
   in += elem->packed_indexing_size();
   // If this is a coarse element,
   // add any element side or edge boundary condition ids
   if (level == 0)
     {
       for (unsigned short s = 0; s != elem->n_sides(); ++s)
         {
           const boundary_id_type num_bcs =
             cast_int<boundary_id_type>(*in++);
           for (boundary_id_type bc_it=0; bc_it < num_bcs; bc_it++)
             mesh->get_boundary_info().add_side
               (elem, s, cast_int<boundary_id_type>(*in++));
         }
       for (unsigned short e = 0; e != elem->n_edges(); ++e)
         {
           const boundary_id_type num_bcs =
             cast_int<boundary_id_type>(*in++);
           for (boundary_id_type bc_it=0; bc_it < num_bcs; bc_it++)
             mesh->get_boundary_info().add_edge
               (elem, e, cast_int<boundary_id_type>(*in++));
         }
       for (unsigned short sf=0; sf != 2; ++sf)
         {
           const boundary_id_type num_bcs =
             cast_int<boundary_id_type>(*in++);
           for (boundary_id_type bc_it=0; bc_it < num_bcs; bc_it++)
             mesh->get_boundary_info().add_shellface
               (elem, sf, cast_int<boundary_id_type>(*in++));
         }
     }
   // Return the new element
   return elem;
 }
template<> Elem* libMesh::Parallel::Packing< Elem * >::unpack (std::vector< largest_id_type >::const_iterator in, DistributedMesh * mesh)
Definition at line 807 of file parallel_elem.C.
References libMesh::Parallel::Packing< T >::unpack().
 {
   return unpack(in, static_cast<MeshBase*>(mesh));
 }
template<> Elem* libMesh::Parallel::Packing< Elem * >::unpack (std::vector< largest_id_type >::const_iterator in, ParallelMesh * mesh)
Definition at line 818 of file parallel_elem.C.
References libMesh::Parallel::Packing< T >::unpack().
 {
   return unpack(in, static_cast<MeshBase*>(mesh));
 }
The documentation for this class was generated from the following files:
parallel_elem.h
parallel_elem.C