libMesh: libMesh::SecondOrderUnsteadySolver Class Reference
SomeWebsiteLogo
libMesh::SecondOrderUnsteadySolver Class Reference abstract
#include <second_order_unsteady_solver.h>
Public Types
typedef DifferentiableSystem sys_type
Public Member Functions
SecondOrderUnsteadySolver (sys_type &s)
virtual ~SecondOrderUnsteadySolver ()
virtual unsigned int time_order () const override
virtual void init () override
virtual void init_data () override
virtual void reinit () override
virtual void retrieve_timestep () override
void project_initial_rate (FunctionBase< Number > *f, FunctionBase< Gradient > *g=nullptr)
Number old_solution_rate (const dof_id_type global_dof_number) const
Number old_solution_accel (const dof_id_type global_dof_number) const
virtual void solve () override
virtual void advance_timestep () override
virtual void adjoint_advance_timestep () override
virtual Real error_order () const =0
Number old_nonlinear_solution (const dof_id_type global_dof_number) const
virtual Real du (const SystemNorm &norm) const override
virtual bool is_steady () const override
virtual bool element_residual (bool request_jacobian, DiffContext &)=0
virtual bool side_residual (bool request_jacobian, DiffContext &)=0
virtual bool nonlocal_residual (bool request_jacobian, DiffContext &)=0
virtual void before_timestep ()
const sys_type & system () const
sys_type & system ()
virtual std::unique_ptr< DiffSolver > & diff_solver ()
virtual std::unique_ptr< LinearSolver< Number > > & linear_solver ()
void set_solution_history (const SolutionHistory &_solution_history)
bool is_adjoint () const
void set_is_adjoint (bool _is_adjoint_value)
Static Public Member Functions
static std::string get_info ()
static void print_info (std::ostream &out=libMesh::out)
static unsigned int n_objects ()
static void enable_print_counter_info ()
static void disable_print_counter_info ()
Public Attributes
std::unique_ptr< NumericVector< Number > > old_local_nonlinear_solution
bool quiet
unsigned int reduce_deltat_on_diffsolver_failure
Protected Types
typedef bool(DifferentiablePhysics::* ResFuncType) (bool, DiffContext &)
typedef void(DiffContext::* ReinitFuncType) (Real)
typedef std::map< std::string, std::pair< unsigned int, unsigned int > > Counts
Protected Member Functions
void increment_constructor_count (const std::string &name)
void increment_destructor_count (const std::string &name)
Protected Attributes
std::unique_ptr< NumericVector< Number > > _old_local_solution_rate
std::unique_ptr< NumericVector< Number > > _old_local_solution_accel
bool first_solve
bool first_adjoint_step
std::unique_ptr< DiffSolver > _diff_solver
std::unique_ptr< LinearSolver< Number > > _linear_solver
sys_type & _system
std::unique_ptr< SolutionHistory > solution_history
Static Protected Attributes
static Counts _counts
static Threads::atomic< unsigned int > _n_objects
static Threads::spin_mutex _mutex
static bool _enable_print_counter = true
Detailed Description
Generic class from which second order UnsteadySolvers should subclass.
Subclasses of this class are meant to solve problems of the form
This class is part of the new DifferentiableSystem framework, which is still experimental. Users of this framework should beware of bugs and future API changes.
Author
Paul T. Bauman
Date
2015
Definition at line 38 of file second_order_unsteady_solver.h.
Member Typedef Documentation
Counts
typedef std::map<std::string, std::pair<unsigned int, unsigned int> > libMesh::ReferenceCounter::Counts protected inherited
Data structure to log the information. The log is identified by the class name.
Definition at line 117 of file reference_counter.h.
ReinitFuncType
typedef void(DiffContext::* libMesh::TimeSolver::ReinitFuncType) (Real) protected inherited
Definition at line 273 of file time_solver.h.
ResFuncType
typedef bool(DifferentiablePhysics::* libMesh::TimeSolver::ResFuncType) (bool, DiffContext &) protected inherited
Definitions of argument types for use in refactoring subclasses.
Definition at line 271 of file time_solver.h.
sys_type
typedef DifferentiableSystem libMesh::TimeSolver::sys_type inherited
The type of system
Definition at line 65 of file time_solver.h.
Constructor & Destructor Documentation
SecondOrderUnsteadySolver()
libMesh::SecondOrderUnsteadySolver::SecondOrderUnsteadySolver (sys_type & s) explicit
Constructor. Requires a reference to the system to be solved.
Definition at line 25 of file second_order_unsteady_solver.C.
   : UnsteadySolver(s),
     _old_local_solution_rate(NumericVector<Number>::build(s.comm())),
     _old_local_solution_accel(NumericVector<Number>::build(s.comm()))
 {}
~SecondOrderUnsteadySolver()
libMesh::SecondOrderUnsteadySolver::~SecondOrderUnsteadySolver () virtual
Destructor.
Definition at line 31 of file second_order_unsteady_solver.C.
 {}
Member Function Documentation
adjoint_advance_timestep()
void libMesh::UnsteadySolver::adjoint_advance_timestep () override virtual inherited
This method advances the adjoint solution to the previous timestep, after an adjoint_solve() has been performed. This will be done before every UnsteadySolver::adjoint_solve().
Reimplemented from libMesh::TimeSolver.
Reimplemented in libMesh::NewmarkSolver.
Definition at line 178 of file unsteady_solver.C.
References libMesh::TimeSolver::_system, libMesh::DifferentiableSystem::deltat, libMesh::UnsteadySolver::first_adjoint_step, libMesh::System::get_dof_map(), libMesh::DofMap::get_send_list(), libMesh::System::get_vector(), libMesh::NumericVector< T >::localize(), libMesh::UnsteadySolver::old_local_nonlinear_solution, libMesh::TimeSolver::solution_history, and libMesh::System::time.
 {
   // On the first call of this function, we dont save the adjoint solution or
   // decrement the time, we just call the retrieve function below
   if (!first_adjoint_step)
     {
       // Call the store function to store the last adjoint before decrementing the time
       solution_history->store();
       // Decrement the system time
       _system.time -= _system.deltat;
     }
   else
     {
       first_adjoint_step = false;
     }
   // Retrieve the primal solution vectors at this time using the
   // solution_history object
   solution_history->retrieve();
   // Dont forget to localize the old_nonlinear_solution !
   _system.get_vector("_old_nonlinear_solution").localize
     (*old_local_nonlinear_solution,
      _system.get_dof_map().get_send_list());
 }
advance_timestep()
void libMesh::UnsteadySolver::advance_timestep () override virtual inherited
This method advances the solution to the next timestep, after a solve() has been performed. Often this will be done after every UnsteadySolver::solve(), but adaptive mesh refinement and/or adaptive time step selection may require some solve() steps to be repeated.
Reimplemented from libMesh::TimeSolver.
Reimplemented in libMesh::AdaptiveTimeSolver, and libMesh::NewmarkSolver.
Definition at line 152 of file unsteady_solver.C.
References libMesh::TimeSolver::_system, libMesh::DifferentiableSystem::deltat, libMesh::UnsteadySolver::first_solve, libMesh::System::get_dof_map(), libMesh::DofMap::get_send_list(), libMesh::System::get_vector(), libMesh::NumericVector< T >::localize(), libMesh::UnsteadySolver::old_local_nonlinear_solution, libMesh::System::solution, libMesh::TimeSolver::solution_history, and libMesh::System::time.
Referenced by libMesh::NewmarkSolver::advance_timestep(), and libMesh::UnsteadySolver::solve().
 {
   if (!first_solve)
     {
       // Store the solution, does nothing by default
       // User has to attach appropriate solution_history object for this to
       // actually store anything anywhere
       solution_history->store();
       _system.time += _system.deltat;
     }
   NumericVector<Number> & old_nonlinear_soln =
     _system.get_vector("_old_nonlinear_solution");
   NumericVector<Number> & nonlinear_solution =
     *(_system.solution);
   old_nonlinear_soln = nonlinear_solution;
   old_nonlinear_soln.localize
     (*old_local_nonlinear_solution,
      _system.get_dof_map().get_send_list());
 }
before_timestep()
virtual void libMesh::TimeSolver::before_timestep () inline virtual inherited
This method is for subclasses or users to override to do arbitrary processing between timesteps
Definition at line 167 of file time_solver.h.
 {}
diff_solver()
virtual std::unique_ptr<DiffSolver>& libMesh::TimeSolver::diff_solver () inline virtual inherited
An implicit linear or nonlinear solver to use at each timestep.
Reimplemented in libMesh::AdaptiveTimeSolver.
Definition at line 182 of file time_solver.h.
References libMesh::TimeSolver::_diff_solver.
Referenced by libMesh::TimeSolver::init(), libMesh::TimeSolver::init_data(), libMesh::TimeSolver::reinit(), and libMesh::TimeSolver::solve().
 { return _diff_solver; }
disable_print_counter_info()
void libMesh::ReferenceCounter::disable_print_counter_info () static inherited
Definition at line 106 of file reference_counter.C.
References libMesh::ReferenceCounter::_enable_print_counter.
Referenced by libMesh::LibMeshInit::LibMeshInit().
 {
   _enable_print_counter = false;
   return;
 }
du()
Real libMesh::UnsteadySolver::du (const SystemNorm & norm) const override virtual inherited
Computes the size of ||u^{n+1} - u^{n}|| in some norm.
Note
While you can always call this function, its result may or may not be very meaningful. For example, if you call this function right after calling advance_timestep() then you'll get a result of zero since old_nonlinear_solution is set equal to nonlinear_solution in this function.
Implements libMesh::TimeSolver.
Definition at line 227 of file unsteady_solver.C.
References libMesh::TimeSolver::_system, libMesh::System::calculate_norm(), libMesh::System::get_vector(), and libMesh::System::solution.
 {
   std::unique_ptr<NumericVector<Number>> solution_copy =
     _system.solution->clone();
   solution_copy->add(-1., _system.get_vector("_old_nonlinear_solution"));
   solution_copy->close();
   return _system.calculate_norm(*solution_copy, norm);
 }
element_residual()
virtual bool libMesh::TimeSolver::element_residual (bool request_jacobian, DiffContext &) pure virtual inherited
This method uses the DifferentiablePhysics element_time_derivative(), element_constraint(), and mass_residual() to build a full residual on an element. What combination
it uses will depend on the type of solver. See the subclasses for more details.
Implemented in libMesh::EigenTimeSolver, libMesh::NewmarkSolver, libMesh::AdaptiveTimeSolver, libMesh::SteadySolver, libMesh::Euler2Solver, and libMesh::EulerSolver.
Referenced by libMesh::FEMSystem::numerical_elem_jacobian().
enable_print_counter_info()
void libMesh::ReferenceCounter::enable_print_counter_info () static inherited
Methods to enable/disable the reference counter output from print_info()
Definition at line 100 of file reference_counter.C.
References libMesh::ReferenceCounter::_enable_print_counter.
 {
   _enable_print_counter = true;
   return;
 }
error_order()
virtual Real libMesh::UnsteadySolver::error_order () const pure virtual inherited
This method should return the expected convergence order of the (non-local) error of the time discretization scheme - e.g. 2 for the O(deltat^2) Crank-Nicholson, or 1 for the O(deltat) Backward Euler.
Useful for adaptive timestepping schemes.
Implemented in libMesh::NewmarkSolver, libMesh::AdaptiveTimeSolver, libMesh::Euler2Solver, and libMesh::EulerSolver.
get_info()
std::string libMesh::ReferenceCounter::get_info () static inherited
Gets a string containing the reference information.
Definition at line 47 of file reference_counter.C.
References libMesh::ReferenceCounter::_counts, and libMesh::Quality::name().
Referenced by libMesh::ReferenceCounter::print_info().
 {
 #if defined(LIBMESH_ENABLE_REFERENCE_COUNTING) && defined(DEBUG)
   std::ostringstream oss;
   oss << '\n'
       << " ---------------------------------------------------------------------------- \n"
       << "| Reference count information                                                |\n"
       << " ---------------------------------------------------------------------------- \n";
   for (const auto & pr : _counts)
     {
       const std::string name(pr.first);
       const unsigned int creations    = pr.second.first;
       const unsigned int destructions = pr.second.second;
       oss << "| " << name << " reference count information:\n"
           << "|  Creations:    " << creations    << '\n'
           << "|  Destructions: " << destructions << '\n';
     }
   oss << " ---------------------------------------------------------------------------- \n";
   return oss.str();
 #else
   return "";
 #endif
 }
increment_constructor_count()
void libMesh::ReferenceCounter::increment_constructor_count (const std::string & name) inline protected inherited
Increments the construction counter. Should be called in the constructor of any derived class that will be reference counted.
Definition at line 181 of file reference_counter.h.
References libMesh::ReferenceCounter::_counts, libMesh::Quality::name(), and libMesh::Threads::spin_mtx.
Referenced by libMesh::ReferenceCountedObject< RBParametrized >::ReferenceCountedObject().
 {
   Threads::spin_mutex::scoped_lock lock(Threads::spin_mtx);
   std::pair<unsigned int, unsigned int> & p = _counts[name];
   p.first++;
 }
increment_destructor_count()
void libMesh::ReferenceCounter::increment_destructor_count (const std::string & name) inline protected inherited
Increments the destruction counter. Should be called in the destructor of any derived class that will be reference counted.
Definition at line 194 of file reference_counter.h.
References libMesh::ReferenceCounter::_counts, libMesh::Quality::name(), and libMesh::Threads::spin_mtx.
Referenced by libMesh::ReferenceCountedObject< RBParametrized >::~ReferenceCountedObject().
 {
   Threads::spin_mutex::scoped_lock lock(Threads::spin_mtx);
   std::pair<unsigned int, unsigned int> & p = _counts[name];
   p.second++;
 }
init()
void libMesh::SecondOrderUnsteadySolver::init () override virtual
The initialization function. This method is used to initialize internal data structures before a simulation begins.
Reimplemented from libMesh::UnsteadySolver.
Definition at line 34 of file second_order_unsteady_solver.C.
References libMesh::TimeSolver::_system, libMesh::System::add_vector(), and libMesh::UnsteadySolver::init().
 {
   UnsteadySolver::init();
   _system.add_vector("_old_solution_rate");
   _system.add_vector("_old_solution_accel");
 }
init_data()
void libMesh::SecondOrderUnsteadySolver::init_data () override virtual
The data initialization function. This method is used to initialize internal data structures after the underlying System has been initialized
Reimplemented from libMesh::UnsteadySolver.
Definition at line 42 of file second_order_unsteady_solver.C.
References _old_local_solution_accel, _old_local_solution_rate, libMesh::TimeSolver::_system, libMesh::System::get_dof_map(), libMesh::DofMap::get_send_list(), libMesh::GHOSTED, libMesh::UnsteadySolver::init_data(), libMesh::System::n_dofs(), libMesh::System::n_local_dofs(), and libMesh::SERIAL.
 {
   UnsteadySolver::init_data();
 #ifdef LIBMESH_ENABLE_GHOSTED
   _old_local_solution_rate->init (_system.n_dofs(), _system.n_local_dofs(),
                                   _system.get_dof_map().get_send_list(), false,
                                   GHOSTED);
   _old_local_solution_accel->init (_system.n_dofs(), _system.n_local_dofs(),
                                    _system.get_dof_map().get_send_list(), false,
                                    GHOSTED);
 #else
   _old_local_solution_rate->init (_system.n_dofs(), false, SERIAL);
   _old_local_solution_accel->init (_system.n_dofs(), false, SERIAL);
 #endif
 }
is_adjoint()
bool libMesh::TimeSolver::is_adjoint () const inline inherited
Accessor for querying whether we need to do a primal or adjoint solve
Definition at line 233 of file time_solver.h.
References libMesh::TimeSolver::_is_adjoint.
Referenced by libMesh::FEMSystem::build_context().
   { return _is_adjoint; }
is_steady()
virtual bool libMesh::UnsteadySolver::is_steady () const inline override virtual inherited
This is not a steady-state solver.
Implements libMesh::TimeSolver.
Definition at line 154 of file unsteady_solver.h.
 { return false; }
linear_solver()
virtual std::unique_ptr<LinearSolver<Number> >& libMesh::TimeSolver::linear_solver () inline virtual inherited
An implicit linear solver to use for adjoint and sensitivity problems.
Reimplemented in libMesh::AdaptiveTimeSolver.
Definition at line 187 of file time_solver.h.
References libMesh::TimeSolver::_linear_solver.
Referenced by libMesh::TimeSolver::init(), libMesh::TimeSolver::init_data(), and libMesh::TimeSolver::reinit().
 { return _linear_solver; }
n_objects()
static unsigned int libMesh::ReferenceCounter::n_objects () inline static inherited
Prints the number of outstanding (created, but not yet destroyed) objects.
Definition at line 83 of file reference_counter.h.
References libMesh::ReferenceCounter::_n_objects.
   { return _n_objects; }
nonlocal_residual()
virtual bool libMesh::TimeSolver::nonlocal_residual (bool request_jacobian, DiffContext &) pure virtual inherited
This method uses the DifferentiablePhysics nonlocal_time_derivative(), nonlocal_constraint(), and nonlocal_mass_residual() to build a full residual of non-local terms.
What combination it uses will depend on the type of solver. See the subclasses for more details.
Implemented in libMesh::NewmarkSolver, libMesh::EigenTimeSolver, libMesh::SteadySolver, libMesh::AdaptiveTimeSolver, libMesh::Euler2Solver, and libMesh::EulerSolver.
Referenced by libMesh::FEMSystem::numerical_nonlocal_jacobian().
old_nonlinear_solution()
Number libMesh::UnsteadySolver::old_nonlinear_solution (const dof_id_type global_dof_number) const inherited
Returns
The old nonlinear solution for the specified global DOF.
Definition at line 216 of file unsteady_solver.C.
References libMesh::TimeSolver::_system, libMesh::System::get_dof_map(), libMesh::DofMap::n_dofs(), and libMesh::UnsteadySolver::old_local_nonlinear_solution.
Referenced by libMesh::EulerSolver::_general_residual(), libMesh::Euler2Solver::_general_residual(), and libMesh::NewmarkSolver::_general_residual().
 {
   libmesh_assert_less (global_dof_number, _system.get_dof_map().n_dofs());
   libmesh_assert_less (global_dof_number, old_local_nonlinear_solution->size());
   return (*old_local_nonlinear_solution)(global_dof_number);
 }
old_solution_accel()
Number libMesh::SecondOrderUnsteadySolver::old_solution_accel (const dof_id_type global_dof_number) const
Returns
The solution acceleration at the previous time step, , for the specified global DOF.
Definition at line 116 of file second_order_unsteady_solver.C.
References _old_local_solution_accel, libMesh::TimeSolver::_system, libMesh::System::get_dof_map(), and libMesh::DofMap::n_dofs().
Referenced by libMesh::NewmarkSolver::_general_residual(), libMesh::NewmarkSolver::advance_timestep(), libMesh::NewmarkSolver::project_initial_accel(), and reinit().
 {
   libmesh_assert_less (global_dof_number, _system.get_dof_map().n_dofs());
   libmesh_assert_less (global_dof_number, _old_local_solution_accel->size());
   return (*_old_local_solution_accel)(global_dof_number);
 }
old_solution_rate()
Number libMesh::SecondOrderUnsteadySolver::old_solution_rate (const dof_id_type global_dof_number) const
Returns
The solution rate at the previous time step, , for the specified global DOF.
Definition at line 107 of file second_order_unsteady_solver.C.
References _old_local_solution_rate, libMesh::TimeSolver::_system, libMesh::System::get_dof_map(), and libMesh::DofMap::n_dofs().
Referenced by libMesh::NewmarkSolver::_general_residual(), libMesh::NewmarkSolver::advance_timestep(), project_initial_rate(), and reinit().
 {
   libmesh_assert_less (global_dof_number, _system.get_dof_map().n_dofs());
   libmesh_assert_less (global_dof_number, _old_local_solution_rate->size());
   return (*_old_local_solution_rate)(global_dof_number);
 }
print_info()
void libMesh::ReferenceCounter::print_info (std::ostream & out = libMesh::out) static inherited
Prints the reference information, by default to libMesh::out.
Definition at line 87 of file reference_counter.C.
References libMesh::ReferenceCounter::_enable_print_counter, and libMesh::ReferenceCounter::get_info().
 {
   if (_enable_print_counter)
     out_stream << ReferenceCounter::get_info();
 }
project_initial_rate()
void libMesh::SecondOrderUnsteadySolver::project_initial_rate (FunctionBase< Number > * f, FunctionBase< Gradient > * g = nullptr)
Specify non-zero initial velocity. Should be called before solve(). The function value f and its gradient g are user-provided cloneable functors. A gradient g is only required/used for projecting onto finite element spaces with continuous derivatives.
Definition at line 98 of file second_order_unsteady_solver.C.
References libMesh::TimeSolver::_system, libMesh::System::get_vector(), old_solution_rate(), and libMesh::System::project_vector().
 {
   NumericVector<Number> & old_solution_rate =
     _system.get_vector("_old_solution_rate");
   _system.project_vector( old_solution_rate, f, g );
 }
reinit()
void libMesh::SecondOrderUnsteadySolver::reinit () override virtual
The reinitialization function. This method is used to resize internal data vectors after a mesh change.
Reimplemented from libMesh::UnsteadySolver.
Definition at line 60 of file second_order_unsteady_solver.C.
References _old_local_solution_accel, _old_local_solution_rate, libMesh::TimeSolver::_system, libMesh::System::get_dof_map(), libMesh::DofMap::get_send_list(), libMesh::System::get_vector(), libMesh::GHOSTED, libMesh::System::n_dofs(), libMesh::System::n_local_dofs(), old_solution_accel(), old_solution_rate(), libMesh::UnsteadySolver::reinit(), and libMesh::SERIAL.
 {
   UnsteadySolver::reinit();
 #ifdef LIBMESH_ENABLE_GHOSTED
   _old_local_solution_rate->init (_system.n_dofs(), _system.n_local_dofs(),
                                   _system.get_dof_map().get_send_list(), false,
                                   GHOSTED);
   _old_local_solution_accel->init (_system.n_dofs(), _system.n_local_dofs(),
                                    _system.get_dof_map().get_send_list(), false,
                                    GHOSTED);
 #else
   _old_local_solution_rate->init (_system.n_dofs(), false, SERIAL);
   _old_local_solution_accel->init (_system.n_dofs(), false, SERIAL);
 #endif
   // localize the old solutions
   NumericVector<Number> & old_solution_rate =
     _system.get_vector("_old_solution_rate");
   NumericVector<Number> & old_solution_accel =
     _system.get_vector("_old_solution_accel");
   old_solution_rate.localize
     (*_old_local_solution_rate,
      _system.get_dof_map().get_send_list());
   old_solution_accel.localize
     (*_old_local_solution_accel,
      _system.get_dof_map().get_send_list());
 }
retrieve_timestep()
void libMesh::SecondOrderUnsteadySolver::retrieve_timestep () override virtual
This method retrieves all the stored solutions at the current system.time
Reimplemented from libMesh::UnsteadySolver.
Definition at line 93 of file second_order_unsteady_solver.C.
 {
   libmesh_not_implemented();
 }
set_is_adjoint()
void libMesh::TimeSolver::set_is_adjoint (bool _is_adjoint_value) inline inherited
Accessor for setting whether we need to do a primal or adjoint solve
Definition at line 240 of file time_solver.h.
References libMesh::TimeSolver::_is_adjoint.
Referenced by libMesh::DifferentiableSystem::adjoint_solve(), libMesh::FEMSystem::postprocess(), and libMesh::DifferentiableSystem::solve().
   { _is_adjoint = _is_adjoint_value; }
set_solution_history()
void libMesh::TimeSolver::set_solution_history (const SolutionHistory & _solution_history) inherited
A setter function users will employ if they need to do something other than save no solution history
Definition at line 97 of file time_solver.C.
References libMesh::SolutionHistory::clone(), and libMesh::TimeSolver::solution_history.
 {
   solution_history = _solution_history.clone();
 }
side_residual()
virtual bool libMesh::TimeSolver::side_residual (bool request_jacobian, DiffContext &) pure virtual inherited
This method uses the DifferentiablePhysics side_time_derivative(), side_constraint(), and side_mass_residual() to build a full residual on an element's side.
What combination it uses will depend on the type of solver. See the subclasses for more details.
Implemented in libMesh::NewmarkSolver, libMesh::EigenTimeSolver, libMesh::AdaptiveTimeSolver, libMesh::SteadySolver, libMesh::Euler2Solver, and libMesh::EulerSolver.
Referenced by libMesh::FEMSystem::numerical_side_jacobian().
solve()
void libMesh::UnsteadySolver::solve () override virtual inherited
This method solves for the solution at the next timestep. Usually we will only need to solve one (non)linear system per timestep, but more complex subclasses may override this.
Reimplemented from libMesh::TimeSolver.
Reimplemented in libMesh::NewmarkSolver, libMesh::AdaptiveTimeSolver, and libMesh::TwostepTimeSolver.
Definition at line 93 of file unsteady_solver.C.
References libMesh::TimeSolver::_diff_solver, libMesh::TimeSolver::_system, libMesh::UnsteadySolver::advance_timestep(), libMesh::DifferentiableSystem::deltat, libMesh::DiffSolver::DIVERGED_BACKTRACKING_FAILURE, libMesh::DiffSolver::DIVERGED_MAX_NONLINEAR_ITERATIONS, libMesh::UnsteadySolver::first_solve, libMesh::out, libMesh::TimeSolver::quiet, and libMesh::TimeSolver::reduce_deltat_on_diffsolver_failure.
Referenced by libMesh::NewmarkSolver::solve().
 {
   if (first_solve)
     {
       advance_timestep();
       first_solve = false;
     }
   unsigned int solve_result = _diff_solver->solve();
   // If we requested the UnsteadySolver to attempt reducing dt after a
   // failed DiffSolver solve, check the results of the solve now.
   if (reduce_deltat_on_diffsolver_failure)
     {
       bool backtracking_failed =
         solve_result & DiffSolver::DIVERGED_BACKTRACKING_FAILURE;
       bool max_iterations =
         solve_result & DiffSolver::DIVERGED_MAX_NONLINEAR_ITERATIONS;
       if (backtracking_failed || max_iterations)
         {
           // Cut timestep in half
           for (unsigned int nr=0; nr<reduce_deltat_on_diffsolver_failure; ++nr)
             {
               _system.deltat *= 0.5;
               libMesh::out << "Newton backtracking failed.  Trying with smaller timestep, dt="
                            << _system.deltat << std::endl;
               solve_result = _diff_solver->solve();
               // Check solve results with reduced timestep
               bool backtracking_still_failed =
                 solve_result & DiffSolver::DIVERGED_BACKTRACKING_FAILURE;
               bool backtracking_max_iterations =
                 solve_result & DiffSolver::DIVERGED_MAX_NONLINEAR_ITERATIONS;
               if (!backtracking_still_failed && !backtracking_max_iterations)
                 {
                   if (!quiet)
                     libMesh::out << "Reduced dt solve succeeded." << std::endl;
                   return;
                 }
             }
           // If we made it here, we still couldn't converge the solve after
           // reducing deltat
           libMesh::out << "DiffSolver::solve() did not succeed after "
                        << reduce_deltat_on_diffsolver_failure
                        << " attempts." << std::endl;
           libmesh_convergence_failure();
         } // end if (backtracking_failed || max_iterations)
     } // end if (reduce_deltat_on_diffsolver_failure)
 }
system() [1/2]
const sys_type& libMesh::TimeSolver::system () const inline inherited
Returns
A constant reference to the system we are solving.
Definition at line 172 of file time_solver.h.
References libMesh::TimeSolver::_system.
Referenced by libMesh::TimeSolver::reinit(), and libMesh::TimeSolver::solve().
 { return _system; }
system() [2/2]
sys_type& libMesh::TimeSolver::system () inline inherited
Returns
A writable reference to the system we are solving.
Definition at line 177 of file time_solver.h.
References libMesh::TimeSolver::_system.
 { return _system; }
time_order()
virtual unsigned int libMesh::SecondOrderUnsteadySolver::time_order () const inline override virtual
Returns
The maximum order of time derivatives for which the UnsteadySolver subclass is capable of handling.
For example, EulerSolver will have time_order() = 1 and NewmarkSolver will have time_order() = 2.
Implements libMesh::UnsteadySolver.
Definition at line 53 of file second_order_unsteady_solver.h.
   { return 2; }
Member Data Documentation
_counts
ReferenceCounter::Counts libMesh::ReferenceCounter::_counts static protected inherited
Actually holds the data.
Definition at line 122 of file reference_counter.h.
Referenced by libMesh::ReferenceCounter::get_info(), libMesh::ReferenceCounter::increment_constructor_count(), and libMesh::ReferenceCounter::increment_destructor_count().
_diff_solver
std::unique_ptr<DiffSolver> libMesh::TimeSolver::_diff_solver protected inherited
An implicit linear or nonlinear solver to use at each timestep.
Definition at line 248 of file time_solver.h.
Referenced by libMesh::NewmarkSolver::compute_initial_accel(), libMesh::TimeSolver::diff_solver(), and libMesh::UnsteadySolver::solve().
_enable_print_counter
bool libMesh::ReferenceCounter::_enable_print_counter = true static protected inherited
Flag to control whether reference count information is printed when print_info is called.
Definition at line 141 of file reference_counter.h.
Referenced by libMesh::ReferenceCounter::disable_print_counter_info(), libMesh::ReferenceCounter::enable_print_counter_info(), and libMesh::ReferenceCounter::print_info().
_linear_solver
std::unique_ptr<LinearSolver<Number> > libMesh::TimeSolver::_linear_solver protected inherited
An implicit linear solver to use for adjoint problems.
Definition at line 253 of file time_solver.h.
Referenced by libMesh::TimeSolver::linear_solver().
_mutex
Threads::spin_mutex libMesh::ReferenceCounter::_mutex static protected inherited
Mutual exclusion object to enable thread-safe reference counting.
Definition at line 135 of file reference_counter.h.
_n_objects
Threads::atomic< unsigned int > libMesh::ReferenceCounter::_n_objects static protected inherited
The number of objects. Print the reference count information when the number returns to 0.
Definition at line 130 of file reference_counter.h.
Referenced by libMesh::ReferenceCounter::n_objects(), libMesh::ReferenceCounter::ReferenceCounter(), and libMesh::ReferenceCounter::~ReferenceCounter().
_old_local_solution_accel
std::unique_ptr<NumericVector<Number> > libMesh::SecondOrderUnsteadySolver::_old_local_solution_accel protected
Serial vector of previous time step acceleration
Definition at line 112 of file second_order_unsteady_solver.h.
Referenced by libMesh::NewmarkSolver::advance_timestep(), init_data(), old_solution_accel(), and reinit().
_old_local_solution_rate
std::unique_ptr<NumericVector<Number> > libMesh::SecondOrderUnsteadySolver::_old_local_solution_rate protected
Serial vector of previous time step velocity
Definition at line 107 of file second_order_unsteady_solver.h.
Referenced by libMesh::NewmarkSolver::advance_timestep(), init_data(), old_solution_rate(), and reinit().
_system
sys_type& libMesh::TimeSolver::_system protected inherited
A reference to the system we are solving.
Definition at line 258 of file time_solver.h.
Referenced by libMesh::EulerSolver::_general_residual(), libMesh::Euler2Solver::_general_residual(), libMesh::SteadySolver::_general_residual(), libMesh::NewmarkSolver::_general_residual(), libMesh::UnsteadySolver::adjoint_advance_timestep(), libMesh::NewmarkSolver::advance_timestep(), libMesh::AdaptiveTimeSolver::advance_timestep(), libMesh::UnsteadySolver::advance_timestep(), libMesh::NewmarkSolver::compute_initial_accel(), libMesh::FirstOrderUnsteadySolver::compute_second_order_eqns(), libMesh::UnsteadySolver::du(), libMesh::EulerSolver::element_residual(), libMesh::Euler2Solver::element_residual(), libMesh::EigenTimeSolver::element_residual(), init(), libMesh::UnsteadySolver::init(), libMesh::TimeSolver::init(), libMesh::EigenTimeSolver::init(), init_data(), libMesh::UnsteadySolver::init_data(), libMesh::TimeSolver::init_data(), libMesh::EulerSolver::nonlocal_residual(), libMesh::Euler2Solver::nonlocal_residual(), libMesh::EigenTimeSolver::nonlocal_residual(), libMesh::UnsteadySolver::old_nonlinear_solution(), old_solution_accel(), old_solution_rate(), libMesh::NewmarkSolver::project_initial_accel(), project_initial_rate(), reinit(), libMesh::UnsteadySolver::reinit(), libMesh::TimeSolver::reinit(), libMesh::UnsteadySolver::retrieve_timestep(), libMesh::EigenTimeSolver::side_residual(), libMesh::TwostepTimeSolver::solve(), libMesh::UnsteadySolver::solve(), libMesh::EigenTimeSolver::solve(), and libMesh::TimeSolver::system().
first_adjoint_step
bool libMesh::UnsteadySolver::first_adjoint_step protected inherited
A bool that will be true the first time adjoint_advance_timestep() is called, (when the primal solution is to be used to set adjoint boundary conditions) and false thereafter
Definition at line 168 of file unsteady_solver.h.
Referenced by libMesh::UnsteadySolver::adjoint_advance_timestep().
first_solve
bool libMesh::UnsteadySolver::first_solve protected inherited
A bool that will be true the first time solve() is called, and false thereafter
Definition at line 162 of file unsteady_solver.h.
Referenced by libMesh::NewmarkSolver::advance_timestep(), libMesh::AdaptiveTimeSolver::advance_timestep(), libMesh::UnsteadySolver::advance_timestep(), libMesh::TwostepTimeSolver::solve(), and libMesh::UnsteadySolver::solve().
old_local_nonlinear_solution
std::unique_ptr<NumericVector<Number> > libMesh::UnsteadySolver::old_local_nonlinear_solution inherited
Serial vector of _system.get_vector("_old_nonlinear_solution")
Definition at line 138 of file unsteady_solver.h.
Referenced by libMesh::AdaptiveTimeSolver::AdaptiveTimeSolver(), libMesh::UnsteadySolver::adjoint_advance_timestep(), libMesh::UnsteadySolver::advance_timestep(), libMesh::AdaptiveTimeSolver::init(), libMesh::UnsteadySolver::init_data(), libMesh::UnsteadySolver::old_nonlinear_solution(), libMesh::UnsteadySolver::reinit(), libMesh::UnsteadySolver::retrieve_timestep(), and libMesh::AdaptiveTimeSolver::~AdaptiveTimeSolver().
quiet
bool libMesh::TimeSolver::quiet inherited
Print extra debugging information if quiet == false.
Definition at line 192 of file time_solver.h.
Referenced by libMesh::TwostepTimeSolver::solve(), libMesh::UnsteadySolver::solve(), and libMesh::EigenTimeSolver::solve().
reduce_deltat_on_diffsolver_failure
unsigned int libMesh::TimeSolver::reduce_deltat_on_diffsolver_failure inherited
This value (which defaults to zero) is the number of times the TimeSolver is allowed to halve deltat and let the DiffSolver repeat the latest failed solve with a reduced timestep.
Note
This has no effect for SteadySolvers.
You must set at least one of the DiffSolver flags "continue_after_max_iterations" or "continue_after_backtrack_failure" to allow the TimeSolver to retry the solve.
Definition at line 221 of file time_solver.h.
Referenced by libMesh::TwostepTimeSolver::solve(), and libMesh::UnsteadySolver::solve().
solution_history
std::unique_ptr<SolutionHistory> libMesh::TimeSolver::solution_history protected inherited
A std::unique_ptr to a SolutionHistory object. Default is NoSolutionHistory, which the user can override by declaring a different kind of SolutionHistory in the application
Definition at line 265 of file time_solver.h.
Referenced by libMesh::UnsteadySolver::adjoint_advance_timestep(), libMesh::UnsteadySolver::advance_timestep(), libMesh::UnsteadySolver::retrieve_timestep(), and libMesh::TimeSolver::set_solution_history().
The documentation for this class was generated from the following files:
second_order_unsteady_solver.h
second_order_unsteady_solver.C