libMesh: libMesh::Node Class Reference
SomeWebsiteLogo
libMesh::Node Class Reference
A geometric point in (x,y,z) space associated with a DOF.
#include <node.h>
Public Types
typedef Real value_type
typedef unsigned int index_type
Public Member Functions
Node (const Real x=0, const Real y=0, const Real z=0, const dof_id_type id=invalid_id)
Node (const Node &n)
Node (const Point &p, const dof_id_type id=invalid_id)
~Node ()
Node & operator= (const Point &p)
bool active () const
bool operator== (const Node &rhs) const
void print_info (std::ostream &os=libMesh::out) const
std::string get_info () const
unsigned int packed_size () const
unsigned int valence () const
void set_valence (unsigned int val)
processor_id_type choose_processor_id (processor_id_type pid1, processor_id_type pid2) const
void assign (const TypeVector< T2 > &)
const Real & operator() (const unsigned int i) const
Real & operator() (const unsigned int i)
const Real & slice (const unsigned int i) const
Real & slice (const unsigned int i)
TypeVector< typename CompareTypes< Real, T2 >::supertype > operator+ (const TypeVector< T2 > &) const
const TypeVector< Real > & operator+= (const TypeVector< T2 > &)
void add (const TypeVector< T2 > &)
void add_scaled (const TypeVector< T2 > &, const Real)
TypeVector< typename CompareTypes< Real, T2 >::supertype > operator- (const TypeVector< T2 > &) const
TypeVector< Real > operator- () const
const TypeVector< Real > & operator-= (const TypeVector< T2 > &)
void subtract (const TypeVector< T2 > &)
void subtract_scaled (const TypeVector< T2 > &, const Real)
boostcopy::enable_if_c< ScalarTraits< Scalar >::value, TypeVector< typename CompareTypes< Real, Scalar >::supertype > >::type operator* (const Scalar) const
CompareTypes< Real, T2 >::supertype operator* (const TypeVector< T2 > &) const
const TypeVector< Real > & operator*= (const Real)
boostcopy::enable_if_c< ScalarTraits< Scalar >::value, TypeVector< typename CompareTypes< Real, Scalar >::supertype > >::type operator/ (const Scalar) const
const TypeVector< Real > & operator/= (const Real)
CompareTypes< Real, T2 >::supertype contract (const TypeVector< T2 > &) const
TypeVector< typename CompareTypes< Real, T2 >::supertype > cross (const TypeVector< T2 > &v) const
TypeVector< Real > unit () const
Real size () const
Real norm () const
Real size_sq () const
Real norm_sq () const
void zero ()
bool relative_fuzzy_equals (const TypeVector< Real > &rhs, Real tol=TOLERANCE) const
bool absolute_fuzzy_equals (const TypeVector< Real > &rhs, Real tol=TOLERANCE) const
bool operator== (const TypeVector< Real > &rhs) const
bool operator!= (const TypeVector< Real > &rhs) const
bool operator< (const TypeVector< Real > &rhs) const
bool operator< (const TypeVector< Complex > &rhs) const
bool operator<= (const TypeVector< Real > &rhs) const
bool operator<= (const TypeVector< Complex > &rhs) const
bool operator> (const TypeVector< Real > &rhs) const
bool operator> (const TypeVector< Complex > &rhs) const
bool operator>= (const TypeVector< Real > &rhs) const
bool operator>= (const TypeVector< Complex > &rhs) const
void print (std::ostream &os=libMesh::out) const
void write_unformatted (std::ostream &out, const bool newline=true) const
void clear_old_dof_object ()
void set_old_dof_object ()
void clear_dofs ()
void invalidate_dofs (const unsigned int sys_num=libMesh::invalid_uint)
void invalidate_id ()
void invalidate_processor_id ()
void invalidate ()
unsigned int n_dofs (const unsigned int s, const unsigned int var=libMesh::invalid_uint) const
dof_id_type id () const
dof_id_type & set_id ()
void set_id (const dof_id_type dofid)
unique_id_type unique_id () const
unique_id_type & set_unique_id ()
bool valid_id () const
bool valid_unique_id () const
processor_id_type processor_id () const
processor_id_type & processor_id ()
void processor_id (const processor_id_type pid)
bool valid_processor_id () const
unsigned int n_systems () const
void set_n_systems (const unsigned int s)
void add_system ()
unsigned int n_var_groups (const unsigned int s) const
unsigned int n_vars (const unsigned int s, const unsigned int vg) const
unsigned int n_vars (const unsigned int s) const
void set_n_vars_per_group (const unsigned int s, const std::vector< unsigned int > &nvpg)
unsigned int n_comp (const unsigned int s, const unsigned int var) const
unsigned int n_comp_group (const unsigned int s, const unsigned int vg) const
void set_n_comp (const unsigned int s, const unsigned int var, const unsigned int ncomp)
void set_n_comp_group (const unsigned int s, const unsigned int vg, const unsigned int ncomp)
dof_id_type dof_number (const unsigned int s, const unsigned int var, const unsigned int comp) const
dof_id_type dof_number (const unsigned int s, const unsigned int vg, const unsigned int vig, const unsigned int comp, const unsigned int n_comp) const
std::pair< unsigned int, unsigned int > var_to_vg_and_offset (const unsigned int s, const unsigned int var) const
void set_dof_number (const unsigned int s, const unsigned int var, const unsigned int comp, const dof_id_type dn)
bool has_dofs (const unsigned int s=libMesh::invalid_uint) const
void set_vg_dof_base (const unsigned int s, const unsigned int vg, const dof_id_type db)
dof_id_type vg_dof_base (const unsigned int s, const unsigned int vg) const
unsigned int packed_indexing_size () const
void unpack_indexing (std::vector< largest_id_type >::const_iterator begin)
void pack_indexing (std::back_insert_iterator< std::vector< largest_id_type >> target) const
void debug_buffer () const
void print_dof_info () const
void set_buffer (const std::vector< dof_id_type > &buf)
Static Public Member Functions
static std::unique_ptr< Node > build (const Node &n)
static std::unique_ptr< Node > build (const Point &p, const dof_id_type id)
static std::unique_ptr< Node > build (const Real x, const Real y, const Real z, const dof_id_type id)
static unsigned int unpackable_indexing_size (std::vector< largest_id_type >::const_iterator begin)
static std::string get_info ()
static void print_info (std::ostream &out=libMesh::out)
static unsigned int n_objects ()
static void enable_print_counter_info ()
static void disable_print_counter_info ()
static std::string get_info ()
static void print_info (std::ostream &out=libMesh::out)
static unsigned int n_objects ()
static void enable_print_counter_info ()
static void disable_print_counter_info ()
Public Attributes
DofObject * old_dof_object
Static Public Attributes
static const dof_id_type invalid_id = static_cast<dof_id_type>(-1)
static const unique_id_type invalid_unique_id = static_cast<unique_id_type>(-1)
static const processor_id_type invalid_processor_id = static_cast<processor_id_type>(-1)
Protected Types
typedef std::map< std::string, std::pair< unsigned int, unsigned int > > Counts
typedef std::map< std::string, std::pair< unsigned int, unsigned int > > Counts
Protected Member Functions
void increment_constructor_count (const std::string &name)
void increment_destructor_count (const std::string &name)
void increment_constructor_count (const std::string &name)
void increment_destructor_count (const std::string &name)
Protected Attributes
Real _coords [LIBMESH_DIM]
Static Protected Attributes
static Counts _counts
static Threads::atomic< unsigned int > _n_objects
static Threads::spin_mutex _mutex
static bool _enable_print_counter = true
static Counts _counts
static Threads::atomic< unsigned int > _n_objects
static Threads::spin_mutex _mutex
static bool _enable_print_counter = true
Private Types
typedef unsigned char valence_idx_t
Private Attributes
valence_idx_t _valence
Friends
class MeshRefinement
class Elem
Detailed Description
A geometric point in (x,y,z) space associated with a DOF.
A Node is like a Point, but with more information. A Node is located in space and is associated with some (x,y,z) coordinates. Additionally, a Node may be enumerated with a global id. Finally, a Node may have an arbitrary number of degrees of freedom associated with it.
Author
Benjamin S. Kirk
Date
2003
Definition at line 52 of file node.h.
Member Typedef Documentation
Counts [1/2]
typedef std::map<std::string, std::pair<unsigned int, unsigned int> > libMesh::ReferenceCounter::Counts protected inherited
Data structure to log the information. The log is identified by the class name.
Definition at line 117 of file reference_counter.h.
Counts [2/2]
typedef std::map<std::string, std::pair<unsigned int, unsigned int> > libMesh::ReferenceCounter::Counts protected inherited
Data structure to log the information. The log is identified by the class name.
Definition at line 117 of file reference_counter.h.
index_type
typedef unsigned int libMesh::TypeVector< Real >::index_type inherited
Helper typedef for generic index programming
Definition at line 110 of file type_vector.h.
valence_idx_t
typedef unsigned char libMesh::Node::valence_idx_t private
Type used to store node valence.
Definition at line 200 of file node.h.
value_type
typedef Real libMesh::TypeVector< Real >::value_type inherited
Helper typedef for C++98 generic programming
Definition at line 105 of file type_vector.h.
Constructor & Destructor Documentation
Node() [1/3]
libMesh::Node::Node (const Real x = 0, const Real y = 0, const Real z = 0, const dof_id_type id = invalid_id) inline explicit
Constructor. By default sets all entries to 0. Gives the point 0 in LIBMESH_DIM dimensions with an id of Node::invalid_id.
Definition at line 228 of file node.h.
References libMesh::DofObject::set_id().
                                      :
   Point(x,y,z)
 #ifdef LIBMESH_ENABLE_NODE_VALENCE
   ,
   _valence(0)
 #endif
 {
   this->set_id() = dofid;
 }
 #ifdef LIBMESH_ENABLE_DEPRECATED
 inline
 Node::Node (const Node & n) :
   Point(n),
   DofObject(n),
   ReferenceCountedObject<Node>()
 #ifdef LIBMESH_ENABLE_NODE_VALENCE
   ,
   _valence(n._valence)
 #endif
 {
   libmesh_deprecated();
 }
 #endif
 inline
 Node::Node (const Point & p,
             const dof_id_type dofid) :
   Point(p)
 #ifdef LIBMESH_ENABLE_NODE_VALENCE
   ,
   _valence(0)
 #endif
 {
   // optionally assign the id.  We have
   // to do it like this otherwise
   // Node n = Point p would erase
   // the id!
   if (dofid != invalid_id)
     this->set_id() = dofid;
 }
 inline
 Node::~Node ()
 {
 }
Node() [2/3]
libMesh::Node::Node (const Node & n)
Copy-constructor.
Deprecated:
anyone copying a Node would almost certainly be better off copying the much cheaper Point or taking a reference to the Node.
Node() [3/3]
libMesh::Node::Node (const Point & p, const dof_id_type id = invalid_id) explicit
Copy-constructor from a Point. Optionally assigned the id.
~Node()
libMesh::Node::~Node ()
Destructor.
Member Function Documentation
absolute_fuzzy_equals()
bool libMesh::TypeVector< Real >::absolute_fuzzy_equals (const TypeVector< Real > & rhs, Real tol = TOLERANCE) const inline inherited
Returns
true if two vectors are equal to within an absolute tolerance of tol.
Definition at line 965 of file type_vector.h.
References std::abs().
 {
 #if LIBMESH_DIM == 1
   return (std::abs(_coords[0] - rhs._coords[0])
           <= tol);
 #endif
 #if LIBMESH_DIM == 2
   return (std::abs(_coords[0] - rhs._coords[0]) +
           std::abs(_coords[1] - rhs._coords[1])
           <= tol);
 #endif
 #if LIBMESH_DIM == 3
   return (std::abs(_coords[0] - rhs._coords[0]) +
           std::abs(_coords[1] - rhs._coords[1]) +
           std::abs(_coords[2] - rhs._coords[2])
           <= tol);
 #endif
 }
active()
bool libMesh::Node::active () const inline
Returns
true if the node is active. An active node is defined as one for which id() is not Node::invalid_id. Inactive nodes are nodes that are in the mesh but are not connected to any elements.
Definition at line 334 of file node.h.
References libMesh::DofObject::invalid_id.
 {
   return (this->id() != Node::invalid_id);
 }
add()
void libMesh::TypeVector< Real >::add (const TypeVector< T2 > & p) inline inherited
Add to this vector without creating a temporary.
Definition at line 603 of file type_vector.h.
 {
 #if LIBMESH_DIM == 1
   _coords[0] += p._coords[0];
 #endif
 #if LIBMESH_DIM == 2
   _coords[0] += p._coords[0];
   _coords[1] += p._coords[1];
 #endif
 #if LIBMESH_DIM == 3
   _coords[0] += p._coords[0];
   _coords[1] += p._coords[1];
   _coords[2] += p._coords[2];
 #endif
 }
add_scaled()
void libMesh::TypeVector< Real >::add_scaled (const TypeVector< T2 > & p, const Real factor) inline inherited
Add a scaled value to this vector without creating a temporary.
Definition at line 627 of file type_vector.h.
 {
 #if LIBMESH_DIM == 1
   _coords[0] += factor*p(0);
 #endif
 #if LIBMESH_DIM == 2
   _coords[0] += factor*p(0);
   _coords[1] += factor*p(1);
 #endif
 #if LIBMESH_DIM == 3
   _coords[0] += factor*p(0);
   _coords[1] += factor*p(1);
   _coords[2] += factor*p(2);
 #endif
 }
add_system()
void libMesh::DofObject::add_system () inherited
Adds an additional system to the DofObject
Definition at line 195 of file dof_object.C.
References libMesh::DofObject::_idx_buf, libMesh::DofObject::n_systems(), libMesh::DofObject::n_var_groups(), libMesh::DofObject::n_vars(), and libMesh::DofObject::set_n_systems().
 {
   // quick return?
   if (this->n_systems() == 0)
     {
       this->set_n_systems(1);
       return;
     }
   DofObject::index_buffer_t::iterator it = _idx_buf.begin();
   std::advance(it, this->n_systems());
   // this inserts the current vector size at the position for the new system - creating the
   // entry we need for the new system indicating there are 0 variables.
   _idx_buf.insert(it, cast_int<dof_id_type>(_idx_buf.size()));
   // cache this value before we screw it up!
   const unsigned int ns_orig = this->n_systems();
   // increment the number of systems and the offsets for each of
   // the systems including the new one we just added.
   for (unsigned int i=0; i<ns_orig+1; i++)
     _idx_buf[i]++;
   libmesh_assert_equal_to (this->n_systems(), (ns_orig+1));
   libmesh_assert_equal_to (this->n_vars(ns_orig), 0);
   libmesh_assert_equal_to (this->n_var_groups(ns_orig), 0);
 }
assign()
void libMesh::TypeVector< Real >::assign (const TypeVector< T2 > & p) inline inherited
Assign to this vector without creating a temporary.
Definition at line 532 of file type_vector.h.
 {
   for (unsigned int i=0; i<LIBMESH_DIM; i++)
     _coords[i] = p._coords[i];
 }
build() [1/3]
std::unique_ptr< Node > libMesh::Node::build (const Node & n) inline static
Returns
A Node copied from n and wrapped in a smart pointer.
Deprecated:
anyone copying a Node would almost certainly be better off copying the much cheaper Point or taking a reference to the Node.
Definition at line 304 of file node.h.
Referenced by libMesh::ReplicatedMesh::add_point(), and libMesh::DistributedMesh::add_point().
 {
   libmesh_deprecated();
   return libmesh_make_unique<Node>(n);
 }
build() [2/3]
std::unique_ptr< Node > libMesh::Node::build (const Point & p, const dof_id_type id) inline static
Returns
A Node copied from p with id == id and wrapped in a smart pointer.
Definition at line 314 of file node.h.
References libMesh::DofObject::id().
 {
   return libmesh_make_unique<Node>(p,id);
 }
build() [3/3]
std::unique_ptr< Node > libMesh::Node::build (const Real x, const Real y, const Real z, const dof_id_type id) inline static
Returns
A Node created from the specified (x,y,z) positions with id == id and wrapped in a smart pointer.
Definition at line 323 of file node.h.
References libMesh::DofObject::id().
 {
   return libmesh_make_unique<Node>(x,y,z,id);
 }
choose_processor_id()
processor_id_type libMesh::Node::choose_processor_id (processor_id_type pid1, processor_id_type pid2) const
Return which of pid1 and pid2 would be preferred by the current load-balancing heuristic applied to this node.
Definition at line 78 of file node.C.
References libMesh::DofObject::invalid_processor_id, std::max(), std::min(), and libMesh::on_command_line().
Referenced by libMesh::MeshTools::correct_node_proc_ids(), and libMesh::Partitioner::set_node_processor_ids().
 {
   if (pid1 == DofObject::invalid_processor_id)
     return pid2;
   // Do we want the new load-balanced node partitioning heuristic
   // instead of the default partitioner-friendlier heuristic?
   static bool load_balanced_nodes =
     libMesh::on_command_line ("--load-balanced-nodes");
   // For better load balancing, we can use the min
   // even-numberered nodes and the max for odd-numbered.
   if (load_balanced_nodes)
     {
       if (this->id() % 2 &&
           pid2 != DofObject::invalid_processor_id)
         return std::max(pid1, pid2);
       else
         return std::min(pid1, pid2);
     }
   // Our default behavior, which puts too many nodes on lower MPI
   // ranks but which keeps elements' nodes on the same partition more
   // often, is simply:
   return std::min(pid1, pid2);
 }
clear_dofs()
void libMesh::DofObject::clear_dofs () inline inherited
Clear the DofMap data structures and return to a pristine state.
Definition at line 621 of file dof_object.h.
References libMesh::DofObject::_idx_buf, and libMesh::DofObject::n_systems().
Referenced by libMesh::DofObject::set_n_systems(), and libMesh::DofObject::~DofObject().
 {
   // vector swap trick to force deallocation
   index_buffer_t().swap(_idx_buf);
   libmesh_assert_equal_to (this->n_systems(), 0);
   libmesh_assert (_idx_buf.empty());
 }
clear_old_dof_object()
void libMesh::DofObject::clear_old_dof_object () inherited
Sets the old_dof_object to nullptr
Definition at line 142 of file dof_object.C.
References libMesh::DofObject::old_dof_object.
Referenced by libMesh::DofObject::operator=(), libMesh::DofObject::set_old_dof_object(), libMesh::DofObject::unpack_indexing(), and libMesh::DofObject::~DofObject().
 {
   delete this->old_dof_object;
   this->old_dof_object = nullptr;
 }
contract()
CompareTypes< Real , T2 >::supertype libMesh::TypeVector< Real >::contract (const TypeVector< T2 > & p) const inline inherited
Returns
The result of TypeVector::operator*().
Definition at line 872 of file type_vector.h.
 {
   return (*this)*(p);
 }
cross()
TypeVector< typename CompareTypes< Real , T2 >::supertype > libMesh::TypeVector< Real >::cross (const TypeVector< T2 > & v) const inherited
Returns
The cross product of this vector with v.
Definition at line 882 of file type_vector.h.
 {
   typedef typename CompareTypes<T, T2>::supertype TS;
   libmesh_assert_equal_to (LIBMESH_DIM, 3);
   // |     i          j          k    |
   // |(*this)(0) (*this)(1) (*this)(2)|
   // |   p(0)       p(1)       p(2)   |
   return TypeVector<TS>( _coords[1]*p._coords[2] - _coords[2]*p._coords[1],
                          -_coords[0]*p._coords[2] + _coords[2]*p._coords[0],
                          _coords[0]*p._coords[1] - _coords[1]*p._coords[0]);
 }
debug_buffer()
void libMesh::DofObject::debug_buffer () const inherited
Print our buffer for debugging.
Definition at line 538 of file dof_object.C.
References libMesh::DofObject::_idx_buf, libMesh::MeshTools::Generation::Private::idx(), and libMesh::out.
 {
   libMesh::out << " [ ";
   for (const auto & idx : _idx_buf)
     libMesh::out << idx << " ";
   libMesh::out << "]\n";
 }
disable_print_counter_info() [1/2]
void libMesh::ReferenceCounter::disable_print_counter_info () static inherited
Definition at line 106 of file reference_counter.C.
References libMesh::ReferenceCounter::_enable_print_counter.
Referenced by libMesh::LibMeshInit::LibMeshInit().
 {
   _enable_print_counter = false;
   return;
 }
disable_print_counter_info() [2/2]
void libMesh::ReferenceCounter::disable_print_counter_info () static inherited
Definition at line 106 of file reference_counter.C.
References libMesh::ReferenceCounter::_enable_print_counter.
Referenced by libMesh::LibMeshInit::LibMeshInit().
 {
   _enable_print_counter = false;
   return;
 }
dof_number() [1/2]
dof_id_type libMesh::DofObject::dof_number (const unsigned int s, const unsigned int var, const unsigned int comp) const inline inherited
Returns
The global degree of freedom number for variable var, component comp for system s associated with this DofObject
When partitioning and DoF numbering have been performed by libMesh, every current DoF on this DofObject will belong to its processor.
Definition at line 833 of file dof_object.h.
References libMesh::DofObject::n_comp(), libMesh::DofObject::n_comp_group(), libMesh::DofObject::n_systems(), libMesh::DofObject::n_vars(), and libMesh::DofObject::var_to_vg_and_offset().
Referenced by libMesh::DofMap::_dof_indices(), libMesh::DofMap::allgather_recursive_constraints(), libMesh::FEGenericBase< FEOutputType< T >::type >::compute_periodic_constraints(), libMesh::DofMap::constrain_p_dofs(), libMesh::ExodusII_IO::copy_elemental_solution(), libMesh::ExodusII_IO::copy_nodal_solution(), libMesh::DofMap::distribute_dofs(), libMesh::DofMap::dof_indices(), libMesh::DofObject::DofObject(), libMesh::OldSolutionValue< Output, point_output >::eval_at_node(), libMesh::OldSolutionCoefs< Output, point_output >::eval_at_node(), get_info(), libMesh::Elem::get_info(), libMesh::DofMap::local_variable_indices(), libMesh::DofMap::old_dof_indices(), libMesh::BuildProjectionList::operator()(), libMesh::DofObject::operator=(), libMesh::DofObject::print_dof_info(), libMesh::HPCoarsenTest::select_refinement(), libMesh::DofObject::set_dof_number(), and libMesh::DofMap::set_nonlocal_dof_objects().
 {
   libmesh_assert_less (s,    this->n_systems());
   libmesh_assert_less (var,  this->n_vars(s));
   libmesh_assert_less (comp, this->n_comp(s,var));
   const std::pair<unsigned int, unsigned int>
     vg_vig = this->var_to_vg_and_offset(s,var);
   const unsigned int
     n_comp = this->n_comp_group(s,vg_vig.first);
   return this->dof_number(s, vg_vig.first, vg_vig.second,
                           comp, n_comp);
 }
dof_number() [2/2]
dof_id_type libMesh::DofObject::dof_number (const unsigned int s, const unsigned int vg, const unsigned int vig, const unsigned int comp, const unsigned int n_comp) const inline inherited
Returns
The global degree of freedom number for variable group vg, variable index vig within the group, component comp out of n_comp, for system s on this DofObject
Even users who need to call dof_number from user code probably don't want to call this overload.
Definition at line 854 of file dof_object.h.
References libMesh::DofObject::_idx_buf, libMesh::DofObject::invalid_id, libMesh::DofObject::n_comp(), libMesh::DofObject::n_systems(), libMesh::DofObject::n_var_groups(), libMesh::DofObject::n_vars(), and libMesh::DofObject::start_idx().
 {
   libmesh_assert_less (s,   this->n_systems());
   libmesh_assert_less (vg,  this->n_var_groups(s));
   libmesh_assert_less (vig, this->n_vars(s,vg));
   const unsigned int
     start_idx_sys = this->start_idx(s);
   libmesh_assert_less ((start_idx_sys + 2*vg + 1), _idx_buf.size());
   const dof_id_type
     base_idx = _idx_buf[start_idx_sys + 2*vg + 1];
   // if the first component is invalid, they
   // are all invalid
   if (base_idx == invalid_id)
     return invalid_id;
   // otherwise the index is the first component
   // index augmented by the component number
   else
     return cast_int<dof_id_type>(base_idx + vig*n_comp + comp);
 }
enable_print_counter_info() [1/2]
void libMesh::ReferenceCounter::enable_print_counter_info () static inherited
Methods to enable/disable the reference counter output from print_info()
Definition at line 100 of file reference_counter.C.
References libMesh::ReferenceCounter::_enable_print_counter.
 {
   _enable_print_counter = true;
   return;
 }
enable_print_counter_info() [2/2]
void libMesh::ReferenceCounter::enable_print_counter_info () static inherited
Methods to enable/disable the reference counter output from print_info()
Definition at line 100 of file reference_counter.C.
References libMesh::ReferenceCounter::_enable_print_counter.
 {
   _enable_print_counter = true;
   return;
 }
get_info() [1/3]
std::string libMesh::ReferenceCounter::get_info () static inherited
Gets a string containing the reference information.
Definition at line 47 of file reference_counter.C.
References libMesh::ReferenceCounter::_counts, and libMesh::Quality::name().
Referenced by libMesh::ReferenceCounter::print_info().
 {
 #if defined(LIBMESH_ENABLE_REFERENCE_COUNTING) && defined(DEBUG)
   std::ostringstream oss;
   oss << '\n'
       << " ---------------------------------------------------------------------------- \n"
       << "| Reference count information                                                |\n"
       << " ---------------------------------------------------------------------------- \n";
   for (const auto & pr : _counts)
     {
       const std::string name(pr.first);
       const unsigned int creations    = pr.second.first;
       const unsigned int destructions = pr.second.second;
       oss << "| " << name << " reference count information:\n"
           << "|  Creations:    " << creations    << '\n'
           << "|  Destructions: " << destructions << '\n';
     }
   oss << " ---------------------------------------------------------------------------- \n";
   return oss.str();
 #else
   return "";
 #endif
 }
get_info() [2/3]
std::string libMesh::ReferenceCounter::get_info () static inherited
Gets a string containing the reference information.
Definition at line 47 of file reference_counter.C.
References libMesh::ReferenceCounter::_counts, and libMesh::Quality::name().
Referenced by libMesh::ReferenceCounter::print_info().
 {
 #if defined(LIBMESH_ENABLE_REFERENCE_COUNTING) && defined(DEBUG)
   std::ostringstream oss;
   oss << '\n'
       << " ---------------------------------------------------------------------------- \n"
       << "| Reference count information                                                |\n"
       << " ---------------------------------------------------------------------------- \n";
   for (const auto & pr : _counts)
     {
       const std::string name(pr.first);
       const unsigned int creations    = pr.second.first;
       const unsigned int destructions = pr.second.second;
       oss << "| " << name << " reference count information:\n"
           << "|  Creations:    " << creations    << '\n'
           << "|  Destructions: " << destructions << '\n';
     }
   oss << " ---------------------------------------------------------------------------- \n";
   return oss.str();
 #else
   return "";
 #endif
 }
get_info() [3/3]
std::string libMesh::Node::get_info () const
Prints relevant information about the node to a string.
Definition at line 53 of file node.C.
References libMesh::DofObject::dof_number(), libMesh::DofObject::id(), libMesh::DofObject::n_comp(), libMesh::DofObject::n_systems(), libMesh::DofObject::n_vars(), libMesh::DofObject::processor_id(), and libMesh::DofObject::valid_id().
Referenced by print_info().
 {
   std::ostringstream oss;
   oss << "  Node id()=";
   if (this->valid_id())
     oss << this->id();
   else
     oss << "invalid";
   oss << ", processor_id()=" << this->processor_id() <<
     ", Point=" << *static_cast<const Point *>(this) << '\n';
   oss << "    DoFs=";
   for (unsigned int s=0; s != this->n_systems(); ++s)
     for (unsigned int v=0; v != this->n_vars(s); ++v)
       for (unsigned int c=0; c != this->n_comp(s,v); ++c)
         oss << '(' << s << '/' << v << '/' << this->dof_number(s,v,c) << ") ";
   return oss.str();
 }
has_dofs()
bool libMesh::DofObject::has_dofs (const unsigned int s = libMesh::invalid_uint) const inline inherited
Returns
true if any system has variables which have been assigned, false otherwise.
Definition at line 913 of file dof_object.h.
References libMesh::invalid_uint, libMesh::DofObject::n_systems(), and libMesh::DofObject::n_vars().
Referenced by libMesh::DofMap::old_dof_indices(), and libMesh::DofMap::reinit().
 {
   if (sys == libMesh::invalid_uint)
     {
       for (unsigned int s=0; s<this->n_systems(); s++)
         if (this->n_vars(s))
           return true;
     }
   else
     {
       libmesh_assert_less (sys, this->n_systems());
       if (this->n_vars(sys))
         return true;
     }
   return false;
 }
id()
dof_id_type libMesh::DofObject::id () const inline inherited
Returns
The id for this DofObject
Definition at line 655 of file dof_object.h.
References libMesh::DofObject::_id, and libMesh::DofObject::valid_id().
Referenced by libMesh::UniformRefinementEstimator::_estimate_error(), libMesh::BoundaryInfo::_find_id_maps(), libMesh::MeshTools::Subdivision::add_boundary_ghosts(), libMesh::ReplicatedMesh::add_elem(), libMesh::DistributedMesh::add_elem(), libMesh::BoundaryInfo::add_elements(), libMesh::TopologyMap::add_node(), libMesh::ReplicatedMesh::add_node(), libMesh::DistributedMesh::add_node(), libMesh::DistributedMesh::add_point(), libMesh::UnstructuredMesh::all_first_order(), libMesh::UnstructuredMesh::all_second_order(), libMesh::MeshTools::Modification::all_tri(), libMesh::DofMap::allgather_recursive_constraints(), build(), libMesh::Partitioner::build_graph(), libMesh::InfElemBuilder::build_inf_elem(), libMesh::FEGenericBase< FEOutputType< T >::type >::compute_periodic_constraints(), libMesh::FEMap::compute_single_point_map(), libMesh::MeshRefinement::create_parent_error_vector(), libMesh::ReplicatedMesh::delete_elem(), libMesh::DistributedMesh::delete_elem(), libMesh::ReplicatedMesh::delete_node(), libMesh::DistributedMesh::delete_node(), libMesh::MeshBase::detect_interior_parents(), libMesh::DistributedMesh::DistributedMesh(), libMesh::UNVIO::elements_out(), libMesh::JumpErrorEstimator::estimate_error(), libMesh::AdjointRefinementEstimator::estimate_error(), libMesh::ExactErrorEstimator::estimate_error(), libMesh::UnstructuredMesh::find_neighbors(), libMesh::MeshTools::find_nodal_neighbors(), libMesh::MeshRefinement::flag_elements_by_elem_fraction(), libMesh::MeshRefinement::flag_elements_by_error_fraction(), libMesh::MeshRefinement::flag_elements_by_error_tolerance(), libMesh::MeshTools::Modification::flatten(), get_info(), libMesh::Elem::get_info(), libMesh::DofMap::get_local_constraints(), libMesh::ParmetisPartitioner::initialize(), libMesh::TreeNode< N >::insert(), libMesh::ReplicatedMesh::insert_elem(), libMesh::DistributedMesh::insert_elem(), libMesh::ReplicatedMesh::insert_node(), libMesh::FE< Dim, LAGRANGE_VEC >::inverse_map(), libMesh::MeshTools::libmesh_assert_valid_amr_elem_ids(), libMesh::MeshTools::libmesh_assert_valid_neighbors(), libMesh::Tri3Subdivision::local_node_number(), libMesh::Elem::node_id(), libMesh::VTKIO::nodes_to_vtk(), libMesh::CompareElemIdsByLevel::operator()(), libMesh::WeightedPatchRecoveryErrorEstimator::EstimateError::operator()(), libMesh::PatchRecoveryErrorEstimator::EstimateError::operator()(), libMesh::DistributedMesh::own_node(), libMesh::Parallel::Packing< T >::pack(), libMesh::MetisPartitioner::partition_range(), libMesh::DofObject::print_dof_info(), libMesh::DistributedMesh::query_elem_ptr(), libMesh::DistributedMesh::query_node_ptr(), libMesh::Nemesis_IO::read(), libMesh::ExodusII_IO::read(), libMesh::AbaqusIO::read_elements(), libMesh::DistributedMesh::renumber_elem(), libMesh::DistributedMesh::renumber_node(), libMesh::DistributedMesh::renumber_nodes_and_elements(), libMesh::DofMap::scatter_constraints(), libMesh::DofMap::set_nonlocal_dof_objects(), libMesh::PetscDMWrapper::set_point_range_in_section(), libMesh::MeshTools::Modification::smooth(), libMesh::BoundaryInfo::sync(), libMesh::Parallel::sync_dofobject_data_by_id(), libMesh::Parallel::sync_element_data_by_parent_id(), libMesh::Parallel::sync_node_data_by_element_id_once(), libMesh::TetGenMeshInterface::triangulate_conformingDelaunayMesh_carvehole(), libMesh::Parallel::Packing< T >::unpack(), libMesh::GmshIO::write_mesh(), and libMesh::ExodusII_IO_Helper::write_nodal_coordinates().
 {
   libmesh_assert (this->valid_id());
   return _id;
 }
increment_constructor_count() [1/2]
void libMesh::ReferenceCounter::increment_constructor_count (const std::string & name) inline protected inherited
Increments the construction counter. Should be called in the constructor of any derived class that will be reference counted.
Definition at line 181 of file reference_counter.h.
References libMesh::ReferenceCounter::_counts, libMesh::Quality::name(), and libMesh::Threads::spin_mtx.
Referenced by libMesh::ReferenceCountedObject< RBParametrized >::ReferenceCountedObject().
 {
   Threads::spin_mutex::scoped_lock lock(Threads::spin_mtx);
   std::pair<unsigned int, unsigned int> & p = _counts[name];
   p.first++;
 }
increment_constructor_count() [2/2]
void libMesh::ReferenceCounter::increment_constructor_count (const std::string & name) inline protected inherited
Increments the construction counter. Should be called in the constructor of any derived class that will be reference counted.
Definition at line 181 of file reference_counter.h.
References libMesh::ReferenceCounter::_counts, libMesh::Quality::name(), and libMesh::Threads::spin_mtx.
Referenced by libMesh::ReferenceCountedObject< RBParametrized >::ReferenceCountedObject().
 {
   Threads::spin_mutex::scoped_lock lock(Threads::spin_mtx);
   std::pair<unsigned int, unsigned int> & p = _counts[name];
   p.first++;
 }
increment_destructor_count() [1/2]
void libMesh::ReferenceCounter::increment_destructor_count (const std::string & name) inline protected inherited
Increments the destruction counter. Should be called in the destructor of any derived class that will be reference counted.
Definition at line 194 of file reference_counter.h.
References libMesh::ReferenceCounter::_counts, libMesh::Quality::name(), and libMesh::Threads::spin_mtx.
Referenced by libMesh::ReferenceCountedObject< RBParametrized >::~ReferenceCountedObject().
 {
   Threads::spin_mutex::scoped_lock lock(Threads::spin_mtx);
   std::pair<unsigned int, unsigned int> & p = _counts[name];
   p.second++;
 }
increment_destructor_count() [2/2]
void libMesh::ReferenceCounter::increment_destructor_count (const std::string & name) inline protected inherited
Increments the destruction counter. Should be called in the destructor of any derived class that will be reference counted.
Definition at line 194 of file reference_counter.h.
References libMesh::ReferenceCounter::_counts, libMesh::Quality::name(), and libMesh::Threads::spin_mtx.
Referenced by libMesh::ReferenceCountedObject< RBParametrized >::~ReferenceCountedObject().
 {
   Threads::spin_mutex::scoped_lock lock(Threads::spin_mtx);
   std::pair<unsigned int, unsigned int> & p = _counts[name];
   p.second++;
 }
invalidate()
void libMesh::DofObject::invalidate () inline inherited
Invalidates all the indices for this DofObject
Definition at line 611 of file dof_object.h.
References libMesh::DofObject::invalidate_dofs(), libMesh::DofObject::invalidate_id(), and libMesh::DofObject::invalidate_processor_id().
Referenced by libMesh::DofObject::DofObject().
 {
   this->invalidate_dofs ();
   this->invalidate_id ();
   this->invalidate_processor_id ();
 }
invalidate_dofs()
void libMesh::DofObject::invalidate_dofs (const unsigned int sys_num = libMesh::invalid_uint) inline inherited
Sets all degree of freedom numbers to invalid_id
Definition at line 575 of file dof_object.h.
References libMesh::DofObject::invalid_id, libMesh::DofObject::n_comp_group(), libMesh::DofObject::n_systems(), libMesh::DofObject::n_var_groups(), and libMesh::DofObject::set_vg_dof_base().
Referenced by libMesh::DofObject::invalidate().
 {
   // If the user does not specify the system number...
   if (sys_num >= this->n_systems())
     {
       for (unsigned int s=0; s<this->n_systems(); s++)
         for (unsigned int vg=0; vg<this->n_var_groups(s); vg++)
           if (this->n_comp_group(s,vg))
             this->set_vg_dof_base(s,vg,invalid_id);
     }
   // ...otherwise invalidate the dofs for all systems
   else
     for (unsigned int vg=0; vg<this->n_var_groups(sys_num); vg++)
       if (this->n_comp_group(sys_num,vg))
         this->set_vg_dof_base(sys_num,vg,invalid_id);
 }
invalidate_id()
void libMesh::DofObject::invalidate_id () inline inherited
Sets the id to invalid_id
Definition at line 595 of file dof_object.h.
References libMesh::DofObject::invalid_id, and libMesh::DofObject::set_id().
Referenced by libMesh::DofObject::invalidate().
 {
   this->set_id (invalid_id);
 }
invalidate_processor_id()
void libMesh::DofObject::invalidate_processor_id () inline inherited
Sets the processor id to invalid_processor_id
Definition at line 603 of file dof_object.h.
References libMesh::DofObject::invalid_processor_id, and libMesh::DofObject::processor_id().
Referenced by libMesh::DofObject::invalidate(), and libMesh::Partitioner::set_parent_processor_ids().
 {
   this->processor_id (invalid_processor_id);
 }
n_comp()
unsigned int libMesh::DofObject::n_comp (const unsigned int s, const unsigned int var) const inline inherited
Returns
The number of components for variable var of system s associated with this DofObject. For example, the HIERARCHIC shape functions may have multiple DoFs associated with one node. Another example is the MONOMIALs, where only the elements hold the DoFs. For the different spatial directions, and orders, see FE.
Definition at line 803 of file dof_object.h.
References libMesh::DofObject::n_comp_group(), libMesh::DofObject::n_systems(), libMesh::DofObject::n_vars(), and libMesh::DofObject::var_to_vg().
Referenced by libMesh::DofMap::allgather_recursive_constraints(), libMesh::FEGenericBase< FEOutputType< T >::type >::compute_periodic_constraints(), libMesh::DofMap::constrain_p_dofs(), libMesh::ExodusII_IO::copy_elemental_solution(), libMesh::ExodusII_IO::copy_nodal_solution(), libMesh::DofMap::distribute_dofs(), libMesh::DofObject::dof_number(), libMesh::DofObject::DofObject(), libMesh::OldSolutionValue< Output, point_output >::eval_at_node(), libMesh::OldSolutionCoefs< Output, point_output >::eval_at_node(), get_info(), libMesh::Elem::get_info(), libMesh::DofMap::local_variable_indices(), libMesh::DofObject::n_dofs(), libMesh::DofObject::operator=(), libMesh::DofObject::print_dof_info(), libMesh::DofObject::set_dof_number(), libMesh::DofObject::set_n_vars_per_group(), and libMesh::DofMap::set_nonlocal_dof_objects().
 {
   libmesh_assert_less (s,   this->n_systems());
   libmesh_assert_less (var, this->n_vars(s));
   return this->n_comp_group(s,this->var_to_vg(s,var));
 }
n_comp_group()
unsigned int libMesh::DofObject::n_comp_group (const unsigned int s, const unsigned int vg) const inline inherited
Returns
The number of components for VariableGroup vg of system s associated with this DofObject. For example, the HIERARCHIC shape functions may have multiple DoFs associated with one node. Another example is the MONOMIALs, where only the elements hold the DoFs. For the different spatial directions, and orders, see FE.
Definition at line 816 of file dof_object.h.
References libMesh::DofObject::_idx_buf, libMesh::DofObject::n_systems(), libMesh::DofObject::n_var_groups(), libMesh::DofObject::ncv_magic, and libMesh::DofObject::start_idx().
Referenced by libMesh::DofMap::_dof_indices(), libMesh::DofMap::distribute_local_dofs_node_major(), libMesh::DofMap::distribute_local_dofs_var_major(), libMesh::DofMap::dof_indices(), libMesh::DofObject::dof_number(), libMesh::DofObject::invalidate_dofs(), libMesh::DofObject::n_comp(), libMesh::DofMap::old_dof_indices(), libMesh::BuildProjectionList::operator()(), libMesh::DofMap::reinit(), libMesh::DofObject::set_dof_number(), libMesh::DofObject::set_n_comp_group(), libMesh::DofObject::set_n_vars_per_group(), and libMesh::DofMap::set_nonlocal_dof_objects().
 {
   libmesh_assert_less (s,  this->n_systems());
   libmesh_assert_less (vg, this->n_var_groups(s));
   const unsigned int
     start_idx_sys = this->start_idx(s);
   libmesh_assert_less ((start_idx_sys + 2*vg), _idx_buf.size());
   return (_idx_buf[start_idx_sys + 2*vg] % ncv_magic);
 }
n_dofs()
unsigned int libMesh::DofObject::n_dofs (const unsigned int s, const unsigned int var = libMesh::invalid_uint) const inline inherited
Returns
The number of degrees of freedom associated with system s for this object. Optionally only counts degrees of freedom for variable number var
Definition at line 633 of file dof_object.h.
References libMesh::invalid_uint, libMesh::DofObject::n_comp(), libMesh::DofObject::n_systems(), and libMesh::DofObject::n_vars().
Referenced by libMesh::PetscDMWrapper::add_dofs_helper().
 {
   libmesh_assert_less (s, this->n_systems());
   unsigned int num = 0;
   // Count all variables
   if (var == libMesh::invalid_uint)
     for (unsigned int v=0; v<this->n_vars(s); v++)
       num += this->n_comp(s,v);
   // Only count specified variable
   else
     num = this->n_comp(s,var);
   return num;
 }
n_objects() [1/2]
static unsigned int libMesh::ReferenceCounter::n_objects () inline static inherited
Prints the number of outstanding (created, but not yet destroyed) objects.
Definition at line 83 of file reference_counter.h.
References libMesh::ReferenceCounter::_n_objects.
   { return _n_objects; }
n_objects() [2/2]
static unsigned int libMesh::ReferenceCounter::n_objects () inline static inherited
Prints the number of outstanding (created, but not yet destroyed) objects.
Definition at line 83 of file reference_counter.h.
References libMesh::ReferenceCounter::_n_objects.
   { return _n_objects; }
n_systems()
unsigned int libMesh::DofObject::n_systems () const inline inherited
Returns
The number of systems associated with this DofObject
Definition at line 749 of file dof_object.h.
References libMesh::DofObject::_idx_buf.
Referenced by libMesh::DofMap::_dof_indices(), libMesh::DofObject::add_system(), libMesh::DofObject::clear_dofs(), libMesh::DofObject::dof_number(), libMesh::DofObject::DofObject(), libMesh::DofObject::end_idx(), get_info(), libMesh::Elem::get_info(), libMesh::DofObject::has_dofs(), libMesh::DofObject::invalidate_dofs(), libMesh::DofObject::n_comp(), libMesh::DofObject::n_comp_group(), libMesh::DofObject::n_dofs(), libMesh::DofObject::n_var_groups(), libMesh::DofObject::n_vars(), libMesh::DofMap::old_dof_indices(), libMesh::DofObject::operator=(), libMesh::DofObject::print_dof_info(), libMesh::Elem::refine(), libMesh::DofObject::set_dof_number(), libMesh::DofObject::set_n_comp(), libMesh::DofObject::set_n_comp_group(), libMesh::DofObject::set_n_systems(), libMesh::DofObject::set_n_vars_per_group(), libMesh::DofObject::set_vg_dof_base(), libMesh::DofObject::start_idx(), and libMesh::DofObject::vg_dof_base().
 {
   return _idx_buf.empty() ?
     0 : cast_int<unsigned int>(_idx_buf[0]);
 }
n_var_groups()
unsigned int libMesh::DofObject::n_var_groups (const unsigned int s) const inline inherited
Returns
The number of VariableGroup variable groups associated with system s for this DofObject
Definition at line 758 of file dof_object.h.
References libMesh::DofObject::end_idx(), libMesh::DofObject::n_systems(), and libMesh::DofObject::start_idx().
Referenced by libMesh::DofObject::add_system(), libMesh::DofObject::dof_number(), libMesh::DofObject::DofObject(), libMesh::DofObject::invalidate_dofs(), libMesh::DofObject::n_comp_group(), libMesh::DofObject::n_vars(), libMesh::BuildProjectionList::operator()(), libMesh::DofObject::operator=(), libMesh::DofObject::set_n_comp_group(), libMesh::DofObject::set_n_systems(), libMesh::DofObject::set_n_vars_per_group(), libMesh::DofMap::set_nonlocal_dof_objects(), libMesh::DofObject::set_vg_dof_base(), libMesh::DofObject::var_to_vg(), libMesh::DofObject::var_to_vg_and_offset(), and libMesh::DofObject::vg_dof_base().
 {
   libmesh_assert_less (s, this->n_systems());
   return (this->end_idx(s) - this->start_idx(s)) / 2;
 }
n_vars() [1/2]
unsigned int libMesh::DofObject::n_vars (const unsigned int s, const unsigned int vg) const inline inherited
Returns
The number of Variable variables associated with VariableGroup vg in system s for this DofObject
Definition at line 768 of file dof_object.h.
References libMesh::DofObject::_idx_buf, libMesh::DofObject::n_systems(), libMesh::DofObject::n_var_groups(), libMesh::DofObject::ncv_magic_exp, and libMesh::DofObject::start_idx().
Referenced by libMesh::DofObject::add_system(), libMesh::DofMap::allgather_recursive_constraints(), libMesh::DofMap::distribute_dofs(), libMesh::DofObject::dof_number(), libMesh::DofObject::DofObject(), libMesh::OldSolutionValue< Output, point_output >::eval_at_node(), libMesh::OldSolutionCoefs< Output, point_output >::eval_at_node(), get_info(), libMesh::Elem::get_info(), libMesh::DofObject::has_dofs(), libMesh::DofObject::n_comp(), libMesh::DofObject::n_dofs(), libMesh::DofObject::n_vars(), libMesh::BuildProjectionList::operator()(), libMesh::DofObject::operator=(), libMesh::DofObject::print_dof_info(), libMesh::DofObject::set_dof_number(), libMesh::DofObject::set_n_comp(), libMesh::DofObject::set_n_comp_group(), libMesh::DofObject::set_n_systems(), libMesh::DofObject::set_n_vars_per_group(), libMesh::DofMap::set_nonlocal_dof_objects(), libMesh::DofObject::system_var_to_vg_var(), libMesh::DofObject::var_to_vg(), and libMesh::DofObject::var_to_vg_and_offset().
 {
   libmesh_assert_less (s,  this->n_systems());
   libmesh_assert_less (vg, this->n_var_groups(s));
   const unsigned int start_idx_sys = this->start_idx(s);
   libmesh_assert_less ((start_idx_sys + 2*vg), _idx_buf.size());
   return (cast_int<unsigned int>
           (_idx_buf[start_idx_sys + 2*vg]) >> ncv_magic_exp);
 }
n_vars() [2/2]
unsigned int libMesh::DofObject::n_vars (const unsigned int s) const inline inherited
Returns
The number of Variable variables associated with system s for this DofObject
Definition at line 785 of file dof_object.h.
References libMesh::DofObject::n_systems(), libMesh::DofObject::n_var_groups(), and libMesh::DofObject::n_vars().
 {
   libmesh_assert_less (s, this->n_systems());
   const unsigned int nvg = this->n_var_groups(s);
   unsigned int val=0;
   for (unsigned int vg=0; vg<nvg; vg++)
     val += this->n_vars(s,vg);
   return val;
 }
norm()
Real libMesh::TypeVector< Real >::norm () const inline inherited
Returns
The magnitude of the vector, i.e. the square-root of the sum of the elements squared.
Definition at line 912 of file type_vector.h.
References libMesh::TensorTools::norm_sq().
 {
   return std::sqrt(this->norm_sq());
 }
norm_sq()
Real libMesh::TypeVector< Real >::norm_sq () const inline inherited
Returns
The magnitude of the vector squared, i.e. the sum of the element magnitudes squared.
Definition at line 943 of file type_vector.h.
References libMesh::TensorTools::norm_sq().
 {
 #if LIBMESH_DIM == 1
   return (TensorTools::norm_sq(_coords[0]));
 #endif
 #if LIBMESH_DIM == 2
   return (TensorTools::norm_sq(_coords[0]) +
           TensorTools::norm_sq(_coords[1]));
 #endif
 #if LIBMESH_DIM == 3
   return (TensorTools::norm_sq(_coords[0]) +
           TensorTools::norm_sq(_coords[1]) +
           TensorTools::norm_sq(_coords[2]));
 #endif
 }
operator!=()
bool libMesh::TypeVector< Real >::operator!= (const TypeVector< Real > & rhs) const inline inherited
Returns
!(*this == rhs)
Definition at line 1037 of file type_vector.h.
 {
   return (!(*this == rhs));
 }
operator()() [1/2]
const Real & libMesh::TypeVector< Real >::operator() (const unsigned int i) const inline inherited
Returns
A const reference to the entry of the vector.
Definition at line 542 of file type_vector.h.
 {
   libmesh_assert_less (i, LIBMESH_DIM);
   return _coords[i];
 }
operator()() [2/2]
Real & libMesh::TypeVector< Real >::operator() (const unsigned int i) inline inherited
Returns
A writable reference to the entry of the vector.
Definition at line 553 of file type_vector.h.
 {
   libmesh_assert_less (i, LIBMESH_DIM);
   return _coords[i];
 }
operator*() [1/2]
boostcopy::enable_if_c< ScalarTraits< Scalar >::value, TypeVector< typename CompareTypes< Real , Scalar >::supertype > >::type libMesh::TypeVector< Real >::operator* (const Scalar factor) const inline inherited
Multiply this vector by a scalar value.
Returns
A copy of the result, this vector is unchanged.
Definition at line 739 of file type_vector.h.
 {
   typedef typename CompareTypes<T, Scalar>::supertype SuperType;
 #if LIBMESH_DIM == 1
   return TypeVector<SuperType>(_coords[0]*factor);
 #endif
 #if LIBMESH_DIM == 2
   return TypeVector<SuperType>(_coords[0]*factor,
                                _coords[1]*factor);
 #endif
 #if LIBMESH_DIM == 3
   return TypeVector<SuperType>(_coords[0]*factor,
                                _coords[1]*factor,
                                _coords[2]*factor);
 #endif
 }
operator*() [2/2]
CompareTypes< Real , T2 >::supertype libMesh::TypeVector< Real >::operator* (const TypeVector< T2 > & p) const inline inherited
Returns
The dot-product of this vector with another vector.
Note
The complex conjugate is not taken in the complex-valued case.
The vectors may contain different numeric types.
Definition at line 850 of file type_vector.h.
 {
 #if LIBMESH_DIM == 1
   return _coords[0]*p._coords[0];
 #endif
 #if LIBMESH_DIM == 2
   return (_coords[0]*p._coords[0] +
           _coords[1]*p._coords[1]);
 #endif
 #if LIBMESH_DIM == 3
   return (_coords[0]*p(0) +
           _coords[1]*p(1) +
           _coords[2]*p(2));
 #endif
 }
operator*=()
const TypeVector< Real > & libMesh::TypeVector< Real >::operator*= (const Real factor) inline inherited
Multiply this vector by a scalar value.
Returns
A reference to *this.
Definition at line 776 of file type_vector.h.
 {
 #if LIBMESH_DIM == 1
   _coords[0] *= factor;
 #endif
 #if LIBMESH_DIM == 2
   _coords[0] *= factor;
   _coords[1] *= factor;
 #endif
 #if LIBMESH_DIM == 3
   _coords[0] *= factor;
   _coords[1] *= factor;
   _coords[2] *= factor;
 #endif
   return *this;
 }
operator+()
TypeVector< typename CompareTypes< Real , T2 >::supertype > libMesh::TypeVector< Real >::operator+ (const TypeVector< T2 > & p) const inline inherited
Add two vectors.
Returns
A copy of the result, this vector is unchanged.
Definition at line 566 of file type_vector.h.
 {
   typedef typename CompareTypes<T, T2>::supertype TS;
 #if LIBMESH_DIM == 1
   return TypeVector<TS> (_coords[0] + p._coords[0]);
 #endif
 #if LIBMESH_DIM == 2
   return TypeVector<TS> (_coords[0] + p._coords[0],
                          _coords[1] + p._coords[1]);
 #endif
 #if LIBMESH_DIM == 3
   return TypeVector<TS> (_coords[0] + p._coords[0],
                          _coords[1] + p._coords[1],
                          _coords[2] + p._coords[2]);
 #endif
 }
operator+=()
const TypeVector< Real > & libMesh::TypeVector< Real >::operator+= (const TypeVector< T2 > & p) inline inherited
Add to this vector.
Returns
A reference to *this.
Definition at line 591 of file type_vector.h.
 {
   this->add (p);
   return *this;
 }
operator-() [1/2]
TypeVector< typename CompareTypes< Real , T2 >::supertype > libMesh::TypeVector< Real >::operator- (const TypeVector< T2 > & p) const inline inherited
Subtract from this vector.
Returns
A copy of the result, this vector is unchanged.
Definition at line 652 of file type_vector.h.
 {
   typedef typename CompareTypes<T, T2>::supertype TS;
 #if LIBMESH_DIM == 1
   return TypeVector<TS>(_coords[0] - p._coords[0]);
 #endif
 #if LIBMESH_DIM == 2
   return TypeVector<TS>(_coords[0] - p._coords[0],
                         _coords[1] - p._coords[1]);
 #endif
 #if LIBMESH_DIM == 3
   return TypeVector<TS>(_coords[0] - p._coords[0],
                         _coords[1] - p._coords[1],
                         _coords[2] - p._coords[2]);
 #endif
 }
operator-() [2/2]
TypeVector< Real > libMesh::TypeVector< Real >::operator- () const inline inherited
Returns
The negative of this vector in a separate copy.
Definition at line 711 of file type_vector.h.
 {
 #if LIBMESH_DIM == 1
   return TypeVector(-_coords[0]);
 #endif
 #if LIBMESH_DIM == 2
   return TypeVector(-_coords[0],
                     -_coords[1]);
 #endif
 #if LIBMESH_DIM == 3
   return TypeVector(-_coords[0],
                     -_coords[1],
                     -_coords[2]);
 #endif
 }
operator-=()
const TypeVector< Real > & libMesh::TypeVector< Real >::operator-= (const TypeVector< T2 > & p) inline inherited
Subtract from this vector.
Returns
A reference to *this.
Definition at line 678 of file type_vector.h.
 {
   this->subtract (p);
   return *this;
 }
operator/()
boostcopy::enable_if_c< ScalarTraits< Scalar >::value, TypeVector< typename CompareTypes< Real , Scalar >::supertype > >::type libMesh::TypeVector< Real >::operator/ (const Scalar factor) const inline inherited
Divide each entry of this vector by scalar value.
Returns
A copy of the result, this vector is unchanged.
Definition at line 804 of file type_vector.h.
 {
   libmesh_assert_not_equal_to (factor, static_cast<T>(0.));
   typedef typename CompareTypes<T, Scalar>::supertype TS;
 #if LIBMESH_DIM == 1
   return TypeVector<TS>(_coords[0]/factor);
 #endif
 #if LIBMESH_DIM == 2
   return TypeVector<TS>(_coords[0]/factor,
                         _coords[1]/factor);
 #endif
 #if LIBMESH_DIM == 3
   return TypeVector<TS>(_coords[0]/factor,
                         _coords[1]/factor,
                         _coords[2]/factor);
 #endif
 }
operator/=()
const TypeVector< Real > & libMesh::TypeVector< Real >::operator/= (const Real factor) inline inherited
Divide each entry of this vector by scalar value.
Returns
A reference to *this.
Definition at line 833 of file type_vector.h.
 {
   libmesh_assert_not_equal_to (factor, static_cast<T>(0.));
   for (unsigned int i=0; i<LIBMESH_DIM; i++)
     _coords[i] /= factor;
   return *this;
 }
operator<() [1/2]
bool libMesh::TypeVector< Complex >::operator< (const TypeVector< Complex > & rhs) const inherited
Definition at line 167 of file type_vector.C.
 {
   for (unsigned int i=0; i<LIBMESH_DIM; i++)
     {
       if ((*this)(i).real() < rhs(i).real())
         return true;
       if ((*this)(i).real() > rhs(i).real())
         return false;
       if ((*this)(i).imag() < rhs(i).imag())
         return true;
       if ((*this)(i).imag() > rhs(i).imag())
         return false;
     }
   return false;
 }
operator<() [2/2]
bool libMesh::TypeVector< Real >::operator< (const TypeVector< Real > & rhs) const inherited
Returns
true if this vector is "less" than rhs.
Useful for sorting. Also used for choosing some arbitrary basis function orientations.
Definition at line 109 of file type_vector.C.
 {
   for (unsigned int i=0; i<LIBMESH_DIM; i++)
     {
       if ((*this)(i) < rhs(i))
         return true;
       if ((*this)(i) > rhs(i))
         return false;
     }
   return false;
 }
operator<=() [1/2]
bool libMesh::TypeVector< Complex >::operator<= (const TypeVector< Complex > & rhs) const inherited
Definition at line 186 of file type_vector.C.
 {
   for (unsigned int i=0; i<LIBMESH_DIM; i++)
     {
       if ((*this)(i).real() < rhs(i).real())
         return true;
       if ((*this)(i).real() > rhs(i).real())
         return false;
       if ((*this)(i).imag() < rhs(i).imag())
         return true;
       if ((*this)(i).imag() > rhs(i).imag())
         return false;
     }
   return true;
 }
operator<=() [2/2]
bool libMesh::TypeVector< Real >::operator<= (const TypeVector< Real > & rhs) const inherited
Returns
true if this vector is <= to rhs.
Useful for sorting. Also used for choosing some arbitrary constraint equation directions.
Definition at line 123 of file type_vector.C.
 {
   for (unsigned int i=0; i<LIBMESH_DIM; i++)
     {
       if ((*this)(i) < rhs(i))
         return true;
       if ((*this)(i) > rhs(i))
         return false;
     }
   return true;
 }
operator=()
Node & libMesh::Node::operator= (const Point & p) inline
Assign to a node from a point.
Definition at line 287 of file node.h.
 {
   (*this)(0) = p(0);
 #if LIBMESH_DIM > 1
   (*this)(1) = p(1);
 #endif
 #if LIBMESH_DIM > 2
   (*this)(2) = p(2);
 #endif
   return *this;
 }
operator==() [1/2]
bool libMesh::Node::operator== (const Node & rhs) const
Returns
true if this node equals rhs, false otherwise.
Definition at line 37 of file node.C.
References libMesh::TypeVector< Real >::operator==().
 {
   // Explicitly calling the operator== defined in Point
   return this->Point::operator==(rhs);
 }
operator==() [2/2]
bool libMesh::TypeVector< Real >::operator== (const TypeVector< Real > & rhs) const inline inherited
Returns
true if this(i)==rhs(i) for each component of the vector.
Note
For floating point types T, the function absolute_fuzzy_equals() may be a more appropriate choice.
Definition at line 1015 of file type_vector.h.
Referenced by operator==().
 {
 #if LIBMESH_DIM == 1
   return (_coords[0] == rhs._coords[0]);
 #endif
 #if LIBMESH_DIM == 2
   return (_coords[0] == rhs._coords[0] &&
           _coords[1] == rhs._coords[1]);
 #endif
 #if LIBMESH_DIM == 3
   return (_coords[0] == rhs._coords[0] &&
           _coords[1] == rhs._coords[1] &&
           _coords[2] == rhs._coords[2]);
 #endif
 }
operator>() [1/2]
bool libMesh::TypeVector< Complex >::operator> (const TypeVector< Complex > & rhs) const inherited
Definition at line 205 of file type_vector.C.
 {
   for (unsigned int i=0; i<LIBMESH_DIM; i++)
     {
       if ((*this)(i).real() > rhs(i).real())
         return true;
       if ((*this)(i).real() < rhs(i).real())
         return false;
       if ((*this)(i).imag() > rhs(i).imag())
         return true;
       if ((*this)(i).imag() < rhs(i).imag())
         return false;
     }
   return false;
 }
operator>() [2/2]
bool libMesh::TypeVector< Real >::operator> (const TypeVector< Real > & rhs) const inherited
Returns
true if this vector is "greater" than rhs.
Useful for sorting. Also used for choosing some arbitrary basis function orientations.
Definition at line 138 of file type_vector.C.
 {
   for (unsigned int i=0; i<LIBMESH_DIM; i++)
     {
       if ((*this)(i) > rhs(i))
         return true;
       if ((*this)(i) < rhs(i))
         return false;
     }
   return false;
 }
operator>=() [1/2]
bool libMesh::TypeVector< Complex >::operator>= (const TypeVector< Complex > & rhs) const inherited
Definition at line 224 of file type_vector.C.
 {
   for (unsigned int i=0; i<LIBMESH_DIM; i++)
     {
       if ((*this)(i).real() > rhs(i).real())
         return true;
       if ((*this)(i).real() < rhs(i).real())
         return false;
       if ((*this)(i).imag() > rhs(i).imag())
         return true;
       if ((*this)(i).imag() < rhs(i).imag())
         return false;
     }
   return true;
 }
operator>=() [2/2]
bool libMesh::TypeVector< Real >::operator>= (const TypeVector< Real > & rhs) const inherited
Returns
true if this vector is >= rhs.
Useful for sorting. Also used for choosing some arbitrary constraint equation directions.
Definition at line 152 of file type_vector.C.
 {
   for (unsigned int i=0; i<LIBMESH_DIM; i++)
     {
       if ((*this)(i) > rhs(i))
         return true;
       if ((*this)(i) < rhs(i))
         return false;
     }
   return true;
 }
pack_indexing()
void libMesh::DofObject::pack_indexing (std::back_insert_iterator< std::vector< largest_id_type >> target) const inherited
A method for creating packed data from our index buffer - basically a copy with prepended size with our current implementation.
Definition at line 520 of file dof_object.C.
References libMesh::DofObject::_idx_buf, libMesh::DofObject::old_dof_object, and libMesh::DofObject::pack_indexing().
Referenced by libMesh::Parallel::Packing< T >::pack(), and libMesh::DofObject::pack_indexing().
 {
 #ifdef LIBMESH_ENABLE_AMR
   // We might need to pack old_dof_object too
   *target++ = (old_dof_object == nullptr) ? 0 : 1;
 #endif
   *target++ = _idx_buf.size();
   std::copy(_idx_buf.begin(), _idx_buf.end(), target);
 #ifdef LIBMESH_ENABLE_AMR
   if (old_dof_object)
     old_dof_object->pack_indexing(target);
 #endif
 }
packed_indexing_size()
unsigned int libMesh::DofObject::packed_indexing_size () const inherited
If we pack our indices into an buffer for communications, how many ints do we need?
Definition at line 445 of file dof_object.C.
References libMesh::DofObject::_idx_buf, libMesh::DofObject::old_dof_object, and libMesh::DofObject::packed_indexing_size().
Referenced by libMesh::Parallel::Packing< T >::packable_size(), libMesh::DofObject::packed_indexing_size(), packed_size(), and libMesh::Parallel::Packing< T >::unpack().
 {
   return
     cast_int<unsigned int> (
 #ifdef LIBMESH_ENABLE_AMR
                             ((old_dof_object == nullptr) ? 0 : old_dof_object->packed_indexing_size()) + 2 +
 #else
                             1 +
 #endif
                             _idx_buf.size());
 }
packed_size()
unsigned int libMesh::Node::packed_size () const inline
Definition at line 147 of file node.h.
References libMesh::DofObject::packed_indexing_size(), and libMesh::Real.
   {
     const unsigned int header_size = 2;
     // use "(a+b-1)/b" trick to get a/b to round up
     static const unsigned int idtypes_per_Real =
       (sizeof(Real) + sizeof(largest_id_type) - 1) / sizeof(largest_id_type);
     return header_size + LIBMESH_DIM*idtypes_per_Real +
       this->packed_indexing_size();
   }
print()
void libMesh::TypeVector< Real >::print (std::ostream & os = libMesh::out) const inherited
Formatted print, by default to libMesh::out.
Definition at line 64 of file type_vector.C.
 {
 #if LIBMESH_DIM == 1
   os << "x=" << (*this)(0);
 #endif
 #if LIBMESH_DIM == 2
   os << "(x,y)=("
      << std::setw(8) << (*this)(0) << ", "
      << std::setw(8) << (*this)(1) << ")";
 #endif
 #if LIBMESH_DIM == 3
   os <<  "(x,y,z)=("
      << std::setw(8) << (*this)(0) << ", "
      << std::setw(8) << (*this)(1) << ", "
      << std::setw(8) << (*this)(2) << ")";
 #endif
 }
print_dof_info()
void libMesh::DofObject::print_dof_info () const inherited
Print out info for debugging.
Definition at line 548 of file dof_object.C.
References libMesh::DofObject::dof_number(), libMesh::DofObject::id(), libMesh::DofObject::n_comp(), libMesh::DofObject::n_systems(), libMesh::DofObject::n_vars(), and libMesh::out.
 {
   libMesh::out << this->id() << " [ ";
   for (unsigned int s=0; s<this->n_systems(); s++)
     {
       libMesh::out << "s:" << s << " ";
       for (unsigned int var=0; var<this->n_vars(s); var++)
         {
           libMesh::out << "v:" << var << " ";
           for (unsigned int comp=0; comp<this->n_comp(s,var); comp++)
             {
               libMesh::out << "c:" << comp << " dof:" << this->dof_number(s,var,comp) << " ";
             }
         }
     }
   libMesh::out << "]\n";
 }
print_info() [1/3]
void libMesh::ReferenceCounter::print_info (std::ostream & out = libMesh::out) static inherited
Prints the reference information, by default to libMesh::out.
Definition at line 87 of file reference_counter.C.
References libMesh::ReferenceCounter::_enable_print_counter, and libMesh::ReferenceCounter::get_info().
 {
   if (_enable_print_counter)
     out_stream << ReferenceCounter::get_info();
 }
print_info() [2/3]
void libMesh::ReferenceCounter::print_info (std::ostream & out = libMesh::out) static inherited
Prints the reference information, by default to libMesh::out.
Definition at line 87 of file reference_counter.C.
References libMesh::ReferenceCounter::_enable_print_counter, and libMesh::ReferenceCounter::get_info().
 {
   if (_enable_print_counter)
     out_stream << ReferenceCounter::get_info();
 }
print_info() [3/3]
void libMesh::Node::print_info (std::ostream & os = libMesh::out) const
Prints relevant information about the node.
Definition at line 45 of file node.C.
References get_info().
Referenced by libMesh::operator<<().
 {
   os << this->get_info()
      << std::endl;
 }
processor_id() [1/3]
processor_id_type libMesh::DofObject::processor_id () const inline inherited
Returns
The processor that this DofObject belongs to.
When partitioning and DoF numbering have been performed by libMesh, every current DoF on this DofObject will belong to its processor.
Definition at line 717 of file dof_object.h.
References libMesh::DofObject::_processor_id.
Referenced by libMesh::BoundaryInfo::_find_id_maps(), libMesh::DistributedMesh::add_elem(), libMesh::BoundaryInfo::add_elements(), libMesh::DofMap::add_neighbors_to_send_list(), libMesh::DistributedMesh::add_node(), libMesh::MeshRefinement::add_node(), libMesh::ReplicatedMesh::add_point(), libMesh::DistributedMesh::add_point(), libMesh::UnstructuredMesh::all_first_order(), libMesh::UnstructuredMesh::all_second_order(), libMesh::MeshTools::Modification::all_tri(), libMesh::DofMap::allgather_recursive_constraints(), libMesh::Patch::build_around_element(), libMesh::MeshTools::Generation::build_extrusion(), libMesh::InfElemBuilder::build_inf_elem(), libMesh::Nemesis_IO_Helper::compute_num_global_nodesets(), libMesh::Nemesis_IO_Helper::compute_num_global_sidesets(), libMesh::UnstructuredMesh::copy_nodes_and_elements(), libMesh::UnstructuredMesh::create_submesh(), libMesh::DistributedMesh::delete_elem(), libMesh::DistributedMesh::delete_node(), libMesh::DofMap::distribute_dofs(), libMesh::DofMap::distribute_local_dofs_node_major(), libMesh::DofMap::distribute_local_dofs_var_major(), libMesh::Elem::Elem(), libMesh::MeshFunction::find_element(), libMesh::UnstructuredMesh::find_neighbors(), libMesh::MeshTools::Modification::flatten(), get_info(), libMesh::Elem::get_info(), libMesh::DofMap::get_info(), libMesh::DofMap::get_local_constraints(), libMesh::DistributedMesh::insert_elem(), libMesh::DofObject::invalidate_processor_id(), libMesh::MeshTools::libmesh_assert_consistent_distributed(), libMesh::MeshTools::libmesh_assert_consistent_distributed_nodes(), libMesh::MeshTools::libmesh_assert_parallel_consistent_new_node_procids(), libMesh::MeshTools::libmesh_assert_parallel_consistent_procids< Elem >(), libMesh::MeshTools::libmesh_assert_parallel_consistent_procids< Node >(), libMesh::MeshTools::libmesh_assert_topology_consistent_procids< Elem >(), libMesh::MeshTools::libmesh_assert_valid_amr_elem_ids(), libMesh::MeshTools::libmesh_assert_valid_neighbors(), libMesh::DofMap::local_variable_indices(), libMesh::MeshRefinement::make_coarsening_compatible(), libMesh::MeshCommunication::make_new_node_proc_ids_parallel_consistent(), libMesh::DistributedMesh::own_node(), libMesh::Parallel::Packing< T >::pack(), libMesh::XdrIO::pack_element(), libMesh::LinearPartitioner::partition_range(), libMesh::SFCPartitioner::partition_range(), libMesh::CentroidPartitioner::partition_range(), libMesh::System::point_gradient(), libMesh::System::point_hessian(), libMesh::System::point_value(), libMesh::DofObject::processor_id(), libMesh::Nemesis_IO::read(), libMesh::CheckpointIO::read_connectivity(), libMesh::XdrIO::read_serialized_connectivity(), libMesh::MeshBase::recalculate_n_partitions(), libMesh::Elem::refine(), libMesh::DofMap::scatter_constraints(), libMesh::Partitioner::set_node_processor_ids(), libMesh::DofMap::set_nonlocal_dof_objects(), libMesh::Partitioner::set_parent_processor_ids(), libMesh::Parallel::sync_dofobject_data_by_id(), libMesh::Parallel::sync_element_data_by_parent_id(), libMesh::Parallel::sync_node_data_by_element_id_once(), libMesh::Parallel::Packing< T >::unpack(), libMesh::GmshIO::write_mesh(), and libMesh::Nemesis_IO_Helper::write_sidesets().
 {
   return _processor_id;
 }
processor_id() [2/3]
processor_id_type & libMesh::DofObject::processor_id () inline inherited
Returns
The processor that this DofObject belongs to as a writable reference.
Definition at line 725 of file dof_object.h.
References libMesh::DofObject::_processor_id.
 {
   return _processor_id;
 }
processor_id() [3/3]
void libMesh::DofObject::processor_id (const processor_id_type pid) inline inherited
Sets the processor_id for this DofObject.
Definition at line 733 of file dof_object.h.
References libMesh::DofObject::processor_id().
 {
   this->processor_id() = pid;
 }
relative_fuzzy_equals()
bool libMesh::TypeVector< Real >::relative_fuzzy_equals (const TypeVector< Real > & rhs, Real tol = TOLERANCE) const inline inherited
Returns
true if two vectors are equal to within a relative tolerance of tol.
Definition at line 990 of file type_vector.h.
References std::abs().
 {
 #if LIBMESH_DIM == 1
   return this->absolute_fuzzy_equals(rhs, tol *
                                      (std::abs(_coords[0]) + std::abs(rhs._coords[0])));
 #endif
 #if LIBMESH_DIM == 2
   return this->absolute_fuzzy_equals(rhs, tol *
                                      (std::abs(_coords[0]) + std::abs(rhs._coords[0]) +
                                       std::abs(_coords[1]) + std::abs(rhs._coords[1])));
 #endif
 #if LIBMESH_DIM == 3
   return this->absolute_fuzzy_equals(rhs, tol *
                                      (std::abs(_coords[0]) + std::abs(rhs._coords[0]) +
                                       std::abs(_coords[1]) + std::abs(rhs._coords[1]) +
                                       std::abs(_coords[2]) + std::abs(rhs._coords[2])));
 #endif
 }
set_buffer()
void libMesh::DofObject::set_buffer (const std::vector< dof_id_type > & buf) inline inherited
Definition at line 535 of file dof_object.h.
References libMesh::DofObject::_idx_buf.
   { _idx_buf = buf; }
set_dof_number()
void libMesh::DofObject::set_dof_number (const unsigned int s, const unsigned int var, const unsigned int comp, const dof_id_type dn) inherited
Sets the global degree of freedom number for variable var, component comp for system s associated with this DofObject
Definition at line 409 of file dof_object.C.
References libMesh::DofObject::_idx_buf, libMesh::DofObject::dof_number(), libMesh::DofObject::invalid_id, libMesh::DofObject::n_comp(), libMesh::DofObject::n_comp_group(), libMesh::DofObject::n_systems(), libMesh::DofObject::n_vars(), libMesh::DofObject::start_idx(), libMesh::DofObject::system_var_to_vg_var(), and libMesh::DofObject::var_to_vg().
 {
   libmesh_assert_less (s,    this->n_systems());
   libmesh_assert_less (var,  this->n_vars(s));
   libmesh_assert_less (comp, this->n_comp(s,var));
   const unsigned int
     vg            = this->var_to_vg(s,var),
 #ifndef NDEBUG
     ncg           = this->n_comp_group(s,vg),
 #endif
     vig           = this->system_var_to_vg_var(s,vg,var),
     start_idx_sys = this->start_idx(s);
   libmesh_assert_less ((start_idx_sys + 2*vg + 1), _idx_buf.size());
   dof_id_type & base_idx = _idx_buf[start_idx_sys + 2*vg + 1];
   // We intend to change all dof numbers together or not at all
   if (comp || vig)
     libmesh_assert ((dn == invalid_id && base_idx == invalid_id) ||
                     (dn == base_idx + vig*ncg + comp));
   // only explicitly store the base index for vig==0, comp==0
   else
     base_idx = dn;
   libmesh_assert_equal_to (this->dof_number(s, var, comp), dn);
 }
set_id() [1/2]
dof_id_type & libMesh::DofObject::set_id () inline inherited
Returns
The id for this DofObject as a writable reference.
Definition at line 664 of file dof_object.h.
References libMesh::DofObject::_id.
Referenced by libMesh::GMVIO::_read_one_cell(), libMesh::ReplicatedMesh::add_elem(), libMesh::DistributedMesh::add_elem(), libMesh::ReplicatedMesh::add_node(), libMesh::DistributedMesh::add_node(), libMesh::UnstructuredMesh::all_first_order(), libMesh::MeshTools::Subdivision::all_subdivision(), libMesh::MeshTools::Generation::build_cube(), libMesh::MeshTools::Generation::build_extrusion(), libMesh::InfElemBuilder::build_inf_elem(), libMesh::UnstructuredMesh::create_submesh(), libMesh::UNVIO::elements_in(), libMesh::MeshTools::Modification::flatten(), libMesh::DofObject::invalidate_id(), Node(), libMesh::DistributedMesh::own_node(), libMesh::Nemesis_IO::read(), libMesh::ExodusII_IO::read(), libMesh::VTKIO::read(), libMesh::CheckpointIO::read_connectivity(), libMesh::UCDIO::read_implementation(), libMesh::GmshIO::read_mesh(), libMesh::XdrIO::read_serialized_connectivity(), libMesh::OFFIO::read_stream(), libMesh::MatlabIO::read_stream(), libMesh::RemoteElem::RemoteElem(), libMesh::ReplicatedMesh::renumber_elem(), libMesh::DistributedMesh::renumber_elem(), libMesh::ReplicatedMesh::renumber_node(), libMesh::DistributedMesh::renumber_node(), libMesh::ReplicatedMesh::renumber_nodes_and_elements(), libMesh::DofObject::set_id(), and libMesh::Parallel::Packing< T >::unpack().
 {
   return _id;
 }
set_id() [2/2]
void libMesh::DofObject::set_id (const dof_id_type dofid) inline inherited
Sets the id for this DofObject
Definition at line 151 of file dof_object.h.
References libMesh::DofObject::set_id().
   { this->set_id() = dofid; }
set_n_comp()
void libMesh::DofObject::set_n_comp (const unsigned int s, const unsigned int var, const unsigned int ncomp) inherited
Sets the number of components for Variable var of system s associated with this DofObject
Definition at line 340 of file dof_object.C.
References libMesh::DofObject::n_systems(), libMesh::DofObject::n_vars(), libMesh::DofObject::set_n_comp_group(), and libMesh::DofObject::var_to_vg().
 {
   libmesh_assert_less (s,   this->n_systems());
   libmesh_assert_less (var, this->n_vars(s));
   this->set_n_comp_group(s, this->var_to_vg(s,var), ncomp);
 }
set_n_comp_group()
void libMesh::DofObject::set_n_comp_group (const unsigned int s, const unsigned int vg, const unsigned int ncomp) inherited
Sets the number of components for VariableGroup vg of system s associated with this DofObject
Definition at line 352 of file dof_object.C.
References libMesh::DofObject::_idx_buf, libMesh::DofObject::invalid_id, libMesh::DofObject::n_comp_group(), libMesh::DofObject::n_systems(), libMesh::DofObject::n_var_groups(), libMesh::DofObject::n_vars(), libMesh::DofObject::ncv_magic, and libMesh::DofObject::start_idx().
Referenced by libMesh::DofMap::reinit(), libMesh::DofObject::set_n_comp(), libMesh::DofObject::set_n_vars_per_group(), and libMesh::DofMap::set_nonlocal_dof_objects().
 {
   libmesh_assert_less (s,  this->n_systems());
   libmesh_assert_less (vg, this->n_var_groups(s));
   // Check for trivial return
   if (ncomp == this->n_comp_group(s,vg)) return;
 #ifndef NDEBUG
   if (ncomp >= ncv_magic)
     {
       const index_t ncvm = ncv_magic;
       libmesh_error_msg("ERROR: ncomp must be less than DofObject::ncv_magic!\n" \
                         << "ncomp = "                                   \
                         << ncomp                                \
                         << ", ncv_magic = "                     \
                         << ncvm                                 \
                         << "\nrecompile and try again!");
     }
 #endif
   const unsigned int
     start_idx_sys = this->start_idx(s),
     n_vars_group  = this->n_vars(s,vg),
     base_offset   = start_idx_sys + 2*vg;
   libmesh_assert_less ((base_offset + 1), _idx_buf.size());
   // if (ncomp)
   //   libMesh::out << "s,vg,ncomp="
   //       << s  << ","
   //       << vg << ","
   //       << ncomp << '\n';
   // set the number of components, maintaining the number
   // of variables in the group
   _idx_buf[base_offset] = ncv_magic*n_vars_group + ncomp;
   // We use (invalid_id - 1) to signify no
   // components for this object
   _idx_buf[base_offset + 1] = (ncomp == 0) ? invalid_id - 1 : invalid_id;
   // this->debug_buffer();
   // libMesh::out << "s,vg = " << s << "," << vg << '\n'
   //     << "base_offset=" << base_offset << '\n'
   //     << "this->n_comp(s,vg)=" << this->n_comp(s,vg) << '\n'
   //     << "this->n_comp_group(s,vg)=" << this->n_comp_group(s,vg) << '\n'
   //     << "this->n_vars(s,vg)=" << this->n_vars(s,vg) << '\n'
   //     << "this->n_var_groups(s)=" << this->n_var_groups(s) << '\n';
   libmesh_assert_equal_to (ncomp, this->n_comp_group(s,vg));
 }
set_n_systems()
void libMesh::DofObject::set_n_systems (const unsigned int s) inherited
Sets the number of systems for this DofObject
Definition at line 165 of file dof_object.C.
References libMesh::DofObject::_idx_buf, libMesh::DofObject::clear_dofs(), libMesh::DofObject::n_systems(), libMesh::DofObject::n_var_groups(), and libMesh::DofObject::n_vars().
Referenced by libMesh::DofObject::add_system(), and libMesh::Elem::refine().
 {
   // Check for trivial return
   if (ns == this->n_systems())
     return;
   // Clear any existing data.  This is safe to call
   // even if we don't have any data.
   this->clear_dofs();
   // Set the new number of systems
   _idx_buf.resize(ns, ns);
   _idx_buf[0] = ns;
 #ifdef DEBUG
   // check that all systems now exist and that they have 0 size
   libmesh_assert_equal_to (ns, this->n_systems());
   for (unsigned int s=0; s<this->n_systems(); s++)
     {
       libmesh_assert_equal_to (this->n_vars(s),       0);
       libmesh_assert_equal_to (this->n_var_groups(s), 0);
     }
 #endif
 }
set_n_vars_per_group()
void libMesh::DofObject::set_n_vars_per_group (const unsigned int s, const std::vector< unsigned int > & nvpg) inherited
Sets number of variables in each group associated with system s for this DofObject. Implicit in this is also setting the number of VariableGroup variable groups for the system. Has the effect of setting the number of components to 0 even when called even with (nvg == this->n_var_groups(s)).
Definition at line 227 of file dof_object.C.
References libMesh::DofObject::_idx_buf, end, libMesh::DofObject::end_idx(), libMesh::DofObject::invalid_id, libMesh::DofObject::n_comp(), libMesh::DofObject::n_comp_group(), libMesh::DofObject::n_systems(), libMesh::DofObject::n_var_groups(), libMesh::DofObject::n_vars(), libMesh::DofObject::ncv_magic, libMesh::DofObject::set_n_comp_group(), and libMesh::DofObject::start_idx().
 {
   libmesh_assert_less (s, this->n_systems());
   // number of variable groups for this system - inferred
   const unsigned int nvg = cast_int<unsigned int>(nvpg.size());
   // BSK - note that for compatibility with the previous implementation
   // calling this method when (nvars == this->n_vars()) requires that
   // we invalidate the DOF indices and set the number of components to 0.
   // Note this was a bit of a surprise to me - there was no quick return in
   // the old method, which caused removal and readdition of the DOF indices
   // even in the case of (nvars == this->n_vars()), resulting in n_comp(s,v)
   // implicitly becoming 0 regardless of any previous value.
   // quick return?
   if (nvg == this->n_var_groups(s))
     {
       for (unsigned int vg=0; vg<nvg; vg++)
         {
           this->set_n_comp_group(s,vg,0);
           libmesh_assert_equal_to (this->n_vars(s,vg), nvpg[vg]);
         }
       return;
     }
   // since there is ample opportunity to screw up other systems, let us
   // cache their current sizes and later assert that they are unchanged.
 #ifdef DEBUG
   DofObject::index_buffer_t old_system_sizes;
   old_system_sizes.reserve(this->n_systems());
   for (unsigned int s_ctr=0; s_ctr<this->n_systems(); s_ctr++)
     old_system_sizes.push_back(this->n_var_groups(s_ctr));
 #endif
   // remove current indices if we have some
   if (this->n_var_groups(s) != 0)
     {
       const unsigned int old_nvg_s = this->n_var_groups(s);
       DofObject::index_buffer_t::iterator
         it  = _idx_buf.begin(),
         end = _idx_buf.begin();
       std::advance(it,  this->start_idx(s));
       std::advance(end, this->end_idx(s));
       _idx_buf.erase(it,end);
       for (unsigned int ctr=(s+1); ctr<this->n_systems(); ctr++)
         _idx_buf[ctr] -= 2*old_nvg_s;
     }
   // better not have any now!
   libmesh_assert_equal_to (this->n_var_groups(s), 0);
   // Make sure we didn't screw up any of our sizes!
 #ifdef DEBUG
   for (unsigned int s_ctr=0; s_ctr<this->n_systems(); s_ctr++)
     if (s_ctr != s)
       libmesh_assert_equal_to (this->n_var_groups(s_ctr), old_system_sizes[s_ctr]);
 #endif
   // OK, if the user requested 0 that is what we have
   if (nvg == 0)
     return;
   {
     // array to hold new indices
     DofObject::index_buffer_t var_idxs(2*nvg);
     for (unsigned int vg=0; vg<nvg; vg++)
       {
         var_idxs[2*vg    ] = ncv_magic*nvpg[vg] + 0;
         var_idxs[2*vg + 1] = invalid_id - 1;
       }
     DofObject::index_buffer_t::iterator it = _idx_buf.begin();
     std::advance(it, this->end_idx(s));
     _idx_buf.insert(it, var_idxs.begin(), var_idxs.end());
     for (unsigned int ctr=(s+1); ctr<this->n_systems(); ctr++)
       _idx_buf[ctr] += 2*nvg;
     // resize _idx_buf to fit so no memory is wasted.
     DofObject::index_buffer_t(_idx_buf).swap(_idx_buf);
   }
   libmesh_assert_equal_to (nvg, this->n_var_groups(s));
 #ifdef DEBUG
   libmesh_assert_equal_to (this->n_var_groups(s), nvpg.size());
   for (unsigned int vg=0; vg<this->n_var_groups(s); vg++)
     {
       libmesh_assert_equal_to (this->n_vars(s,vg), nvpg[vg]);
       libmesh_assert_equal_to (this->n_comp_group(s,vg), 0);
     }
   for (unsigned int v=0; v<this->n_vars(s); v++)
     libmesh_assert_equal_to (this->n_comp(s,v), 0);
   // again, all other system sizes should be unchanged!
   for (unsigned int s_ctr=0; s_ctr<this->n_systems(); s_ctr++)
     if (s_ctr != s)
       libmesh_assert_equal_to (this->n_var_groups(s_ctr), old_system_sizes[s_ctr]);
 #endif
 }
set_old_dof_object()
void libMesh::DofObject::set_old_dof_object () inherited
Sets the old_dof_object to a copy of this
Definition at line 150 of file dof_object.C.
References libMesh::DofObject::clear_old_dof_object(), libMesh::DofObject::DofObject(), and libMesh::DofObject::old_dof_object.
Referenced by libMesh::DofMap::reinit().
 {
   this->clear_old_dof_object();
   libmesh_assert (!this->old_dof_object);
   // Make a new DofObject, assign a copy of \p this.
   // Make sure the copy ctor for DofObject works!!
   this->old_dof_object = new DofObject(*this);
 }
set_unique_id()
unique_id_type & libMesh::DofObject::set_unique_id () inline inherited
Returns
The globally unique_id for this DofObject as a writable reference.
Definition at line 685 of file dof_object.h.
References libMesh::DofObject::_unique_id.
Referenced by libMesh::ReplicatedMesh::add_elem(), libMesh::DistributedMesh::add_elem(), libMesh::ReplicatedMesh::add_node(), libMesh::DistributedMesh::add_node(), libMesh::ReplicatedMesh::add_point(), libMesh::UnstructuredMesh::all_first_order(), libMesh::MeshTools::Generation::build_extrusion(), libMesh::InfElemBuilder::build_inf_elem(), libMesh::UnstructuredMesh::copy_nodes_and_elements(), libMesh::UnstructuredMesh::create_submesh(), libMesh::MeshTools::Modification::flatten(), libMesh::ReplicatedMesh::insert_elem(), libMesh::DistributedMesh::insert_elem(), libMesh::ReplicatedMesh::insert_node(), libMesh::Nemesis_IO::read(), libMesh::CheckpointIO::read_connectivity(), libMesh::CheckpointIO::read_nodes(), libMesh::XdrIO::read_serialized_connectivity(), libMesh::XdrIO::read_serialized_nodes(), and libMesh::Parallel::Packing< T >::unpack().
 {
 #ifdef LIBMESH_ENABLE_UNIQUE_ID
   return _unique_id;
 #else
   libmesh_not_implemented();
 #endif
 }
set_valence()
void libMesh::Node::set_valence (unsigned int val) inline
Sets the number of nodes connected with this node.
Definition at line 344 of file node.h.
References _valence.
 {
   _valence = cast_int<valence_idx_t>(val);
 }
set_vg_dof_base()
void libMesh::DofObject::set_vg_dof_base (const unsigned int s, const unsigned int vg, const dof_id_type db) inline inherited
VariableGroup DoF indices are indexed as id = base + var_in_vg*ncomp + comp This method allows for direct access to the base.
Definition at line 960 of file dof_object.h.
References libMesh::DofObject::_idx_buf, libMesh::DofObject::n_systems(), libMesh::DofObject::n_var_groups(), libMesh::DofObject::start_idx(), and libMesh::DofObject::vg_dof_base().
Referenced by libMesh::DofMap::distribute_local_dofs_node_major(), libMesh::DofMap::distribute_local_dofs_var_major(), libMesh::DofObject::invalidate_dofs(), libMesh::DofMap::reinit(), and libMesh::DofMap::set_nonlocal_dof_objects().
 {
   libmesh_assert_less (s,  this->n_systems());
   libmesh_assert_less (vg, this->n_var_groups(s));
   const unsigned int
     start_idx_sys = this->start_idx(s);
   libmesh_assert_less ((start_idx_sys + 2*vg + 1), _idx_buf.size());
   _idx_buf[start_idx_sys + 2*vg + 1] = db;
   libmesh_assert_equal_to (this->vg_dof_base(s,vg), db);
 }
size()
Real libMesh::TypeVector< Real >::size () const inline inherited
Returns
The magnitude of the vector, i.e. the square-root of the sum of the elements squared.
Deprecated:
Use the norm() function instead.
Definition at line 901 of file type_vector.h.
 {
   libmesh_deprecated();
   return this->norm();
 }
size_sq()
Real libMesh::TypeVector< Real >::size_sq () const inline inherited
Returns
The magnitude of the vector squared, i.e. the sum of the element magnitudes squared.
Deprecated:
Use the norm_sq() function instead.
Definition at line 932 of file type_vector.h.
References libMesh::TensorTools::norm_sq().
 {
   libmesh_deprecated();
   return this->norm_sq();
 }
slice() [1/2]
const Real & libMesh::TypeVector< Real >::slice (const unsigned int i) const inline inherited
Definition at line 143 of file type_vector.h.
 { return (*this)(i); }
slice() [2/2]
Real & libMesh::TypeVector< Real >::slice (const unsigned int i) inline inherited
Definition at line 149 of file type_vector.h.
 { return (*this)(i); }
subtract()
void libMesh::TypeVector< Real >::subtract (const TypeVector< T2 > & p) inline inherited
Subtract from this vector without creating a temporary.
Definition at line 690 of file type_vector.h.
 {
   for (unsigned int i=0; i<LIBMESH_DIM; i++)
     _coords[i] -= p._coords[i];
 }
subtract_scaled()
void libMesh::TypeVector< Real >::subtract_scaled (const TypeVector< T2 > & p, const Real factor) inline inherited
Subtract a scaled value from this vector without creating a temporary.
Definition at line 701 of file type_vector.h.
 {
   for (unsigned int i=0; i<LIBMESH_DIM; i++)
     _coords[i] -= factor*p(i);
 }
unique_id()
unique_id_type libMesh::DofObject::unique_id () const inline inherited
Returns
The globally unique_id for this DofObject
Definition at line 672 of file dof_object.h.
References libMesh::DofObject::_unique_id, libMesh::DofObject::invalid_unique_id, and libMesh::DofObject::valid_unique_id().
Referenced by libMesh::UnstructuredMesh::all_second_order(), libMesh::MeshTools::Modification::all_tri(), libMesh::MeshTools::Generation::build_extrusion(), libMesh::MeshTools::Modification::flatten(), libMesh::Elem::get_info(), libMesh::MeshTools::libmesh_assert_valid_unique_ids(), libMesh::Parallel::Packing< T >::pack(), libMesh::XdrIO::pack_element(), and libMesh::ExodusII_IO::read_elemental_variable().
 {
 #ifdef LIBMESH_ENABLE_UNIQUE_ID
   libmesh_assert (this->valid_unique_id());
   return _unique_id;
 #else
   return invalid_unique_id;
 #endif
 }
unit()
TypeVector< Real > libMesh::TypeVector< Real >::unit () const inherited
Returns
A unit vector in the direction of *this.
Definition at line 37 of file type_vector.C.
References libMesh::Real.
 {
   const Real length = norm();
   libmesh_assert_not_equal_to (length, static_cast<Real>(0.));
 #if LIBMESH_DIM == 1
   return TypeVector<T>(_coords[0]/length);
 #endif
 #if LIBMESH_DIM == 2
   return TypeVector<T>(_coords[0]/length,
                        _coords[1]/length);
 #endif
 #if LIBMESH_DIM == 3
   return TypeVector<T>(_coords[0]/length,
                        _coords[1]/length,
                        _coords[2]/length);
 #endif
 }
unpack_indexing()
void libMesh::DofObject::unpack_indexing (std::vector< largest_id_type >::const_iterator begin) inherited
A method for creating our index buffer from packed data - basically with our current implementation we investigate the size term and then copy.
Definition at line 482 of file dof_object.C.
References libMesh::DofObject::_idx_buf, libMesh::DofObject::clear_old_dof_object(), libMesh::DofObject::DofObject(), libMesh::DofObject::old_dof_object, and libMesh::DofObject::unpack_indexing().
Referenced by libMesh::Parallel::Packing< T >::unpack(), and libMesh::DofObject::unpack_indexing().
 {
   _idx_buf.clear();
 #ifdef LIBMESH_ENABLE_AMR
   this->clear_old_dof_object();
   const bool has_old_dof_object = cast_int<bool>(*begin++);
 #endif
   const largest_id_type size = *begin++;
   _idx_buf.reserve(size);
   std::copy(begin, begin+size, back_inserter(_idx_buf));
   // Check as best we can for internal consistency now
   libmesh_assert(_idx_buf.empty() ||
                  (_idx_buf[0] <= _idx_buf.size()));
 #ifdef DEBUG
   if (!_idx_buf.empty())
     for (unsigned int i=1; i < _idx_buf[0]; ++i)
       {
         libmesh_assert_greater_equal (_idx_buf[i], _idx_buf[i-1]);
         libmesh_assert_equal_to ((_idx_buf[i] - _idx_buf[i-1])%2, 0);
         libmesh_assert_less_equal (_idx_buf[i], _idx_buf.size());
       }
 #endif
 #ifdef LIBMESH_ENABLE_AMR
   if (has_old_dof_object)
     {
       this->old_dof_object = new DofObject();
       this->old_dof_object->unpack_indexing(begin+size);
     }
 #endif
 }
unpackable_indexing_size()
unsigned int libMesh::DofObject::unpackable_indexing_size (std::vector< largest_id_type >::const_iterator begin) static inherited
If we have indices packed into an buffer for communications, how much of that buffer applies to this dof object?
Definition at line 461 of file dof_object.C.
Referenced by libMesh::Parallel::Packing< T >::packed_size(), and libMesh::Parallel::Packing< T >::unpack().
 {
 #ifdef LIBMESH_ENABLE_AMR
   const bool has_old_dof_object = cast_int<bool>(*begin++);
   static const int dof_header_size = 2;
 #else
   static const bool has_old_dof_object = false;
   static const int dof_header_size = 1;
 #endif
   const largest_id_type this_indexing_size = *begin++;
   return cast_int<unsigned int>
     (dof_header_size + this_indexing_size +
      (has_old_dof_object ?
       unpackable_indexing_size(begin+this_indexing_size) : 0));
 }
valence()
unsigned int libMesh::Node::valence () const inline
Returns
The number of nodes connected with this node. Currently, this value is invalid (zero) except for subdivision meshes.
Definition at line 166 of file node.h.
References _valence, and libMesh::invalid_uint.
Referenced by libMesh::Tri3Subdivision::get_ordered_valence().
   {
 #ifdef LIBMESH_ENABLE_NODE_VALENCE
     return _valence;
 #else
     libmesh_not_implemented();
     return libMesh::invalid_uint;
 #endif
   }
valid_id()
bool libMesh::DofObject::valid_id () const inline inherited
Returns
true if this DofObject has a valid id set, false otherwise.
Definition at line 697 of file dof_object.h.
References libMesh::DofObject::_id, and libMesh::DofObject::invalid_id.
Referenced by libMesh::ReplicatedMesh::add_elem(), libMesh::DistributedMesh::add_elem(), libMesh::ReplicatedMesh::add_node(), libMesh::DistributedMesh::add_node(), get_info(), libMesh::Elem::get_info(), libMesh::DofObject::id(), and libMesh::Elem::libmesh_assert_valid_node_pointers().
 {
   return (DofObject::invalid_id != _id);
 }
valid_processor_id()
bool libMesh::DofObject::valid_processor_id () const inline inherited
Returns
true if this DofObject has a valid id set, false otherwise.
Definition at line 741 of file dof_object.h.
References libMesh::DofObject::_processor_id, and libMesh::DofObject::invalid_processor_id.
 {
   return (DofObject::invalid_processor_id != _processor_id);
 }
valid_unique_id()
bool libMesh::DofObject::valid_unique_id () const inline inherited
Returns
true if this DofObject has a valid unique_id set, false otherwise.
Definition at line 705 of file dof_object.h.
References libMesh::DofObject::_unique_id, and libMesh::DofObject::invalid_unique_id.
Referenced by libMesh::ReplicatedMesh::add_elem(), libMesh::DistributedMesh::add_elem(), libMesh::ReplicatedMesh::add_node(), libMesh::DistributedMesh::add_node(), libMesh::ReplicatedMesh::add_point(), libMesh::Elem::get_info(), libMesh::ReplicatedMesh::insert_elem(), libMesh::DistributedMesh::insert_elem(), libMesh::ReplicatedMesh::insert_node(), libMesh::Parallel::Packing< T >::pack(), and libMesh::DofObject::unique_id().
 {
 #ifdef LIBMESH_ENABLE_UNIQUE_ID
   return (DofObject::invalid_unique_id != _unique_id);
 #else
   return false;
 #endif
 }
var_to_vg_and_offset()
std::pair< unsigned int, unsigned int > libMesh::DofObject::var_to_vg_and_offset (const unsigned int s, const unsigned int var) const inline inherited
Returns
A pair consisting of the variable group number and the offset index from the start of that group for variable var on system s associated with this DofObject
Definition at line 887 of file dof_object.h.
References libMesh::DofObject::n_var_groups(), and libMesh::DofObject::n_vars().
Referenced by libMesh::DofMap::_dof_indices(), and libMesh::DofObject::dof_number().
 {
   std::pair<unsigned int, unsigned int> returnval(0,0);
   unsigned int & vg = returnval.first;
   unsigned int & offset = returnval.second;
   unsigned int vg_start = 0;
   for (; ; vg++)
     {
       libmesh_assert_less(vg, this->n_var_groups(s));
       const unsigned int vg_end = vg_start + this->n_vars(s,vg);
       if (var < vg_end)
         {
           offset = var - vg_start;
           return returnval;
         }
       vg_start = vg_end;
     }
 }
vg_dof_base()
dof_id_type libMesh::DofObject::vg_dof_base (const unsigned int s, const unsigned int vg) const inline inherited
VariableGroup DoF indices are indexed as id = base + var_in_vg*ncomp + comp This method allows for direct access to the base.
Definition at line 980 of file dof_object.h.
References libMesh::DofObject::_idx_buf, libMesh::DofObject::n_systems(), libMesh::DofObject::n_var_groups(), and libMesh::DofObject::start_idx().
Referenced by libMesh::DofMap::distribute_local_dofs_node_major(), libMesh::DofMap::distribute_local_dofs_var_major(), libMesh::DofMap::reinit(), libMesh::DofMap::set_nonlocal_dof_objects(), and libMesh::DofObject::set_vg_dof_base().
 {
   libmesh_assert_less (s,  this->n_systems());
   libmesh_assert_less (vg, this->n_var_groups(s));
   const unsigned int
     start_idx_sys = this->start_idx(s);
   libmesh_assert_less ((start_idx_sys + 2*vg + 1), _idx_buf.size());
   // #ifdef DEBUG
   //   std::cout << " [ ";
   //   for (std:size_t i=0; i<_idx_buf.size(); i++)
   //     std::cout << _idx_buf[i] << " ";
   //   std::cout << "]\n";
   // #endif
   return _idx_buf[start_idx_sys + 2*vg + 1];
 }
write_unformatted()
void libMesh::TypeVector< Real >::write_unformatted (std::ostream & out, const bool newline = true) const inherited
Unformatted print to the stream out. Simply prints the elements of the vector separated by spaces. Also prints a newline by default, however, this behavior can be controlled with the newline parameter.
Definition at line 92 of file type_vector.C.
 {
   libmesh_assert (os);
   os << std::setiosflags(std::ios::showpoint)
      << (*this)(0) << " "
      << (*this)(1) << " "
      << (*this)(2) << " ";
   if (newline)
     os << '\n';
 }
zero()
void libMesh::TypeVector< Real >::zero () inline inherited
Set all entries of the vector to 0.
Definition at line 921 of file type_vector.h.
 {
   for (unsigned int i=0; i<LIBMESH_DIM; i++)
     _coords[i] = 0.;
 }
Friends And Related Function Documentation
Elem
friend class Elem friend
Definition at line 194 of file node.h.
MeshRefinement
friend class MeshRefinement friend
This class need access to the node key information, but no one else should be able to mess with it.
Definition at line 193 of file node.h.
Member Data Documentation
_coords
Real libMesh::TypeVector< Real >::_coords[LIBMESH_DIM] protected inherited
The coordinates of the TypeVector.
Definition at line 409 of file type_vector.h.
_counts [1/2]
ReferenceCounter::Counts libMesh::ReferenceCounter::_counts static protected inherited
Actually holds the data.
Definition at line 122 of file reference_counter.h.
Referenced by libMesh::ReferenceCounter::get_info(), libMesh::ReferenceCounter::increment_constructor_count(), and libMesh::ReferenceCounter::increment_destructor_count().
_counts [2/2]
ReferenceCounter::Counts libMesh::ReferenceCounter::_counts static protected inherited
Actually holds the data.
Definition at line 122 of file reference_counter.h.
Referenced by libMesh::ReferenceCounter::get_info(), libMesh::ReferenceCounter::increment_constructor_count(), and libMesh::ReferenceCounter::increment_destructor_count().
_enable_print_counter [1/2]
bool libMesh::ReferenceCounter::_enable_print_counter = true static protected inherited
Flag to control whether reference count information is printed when print_info is called.
Definition at line 141 of file reference_counter.h.
Referenced by libMesh::ReferenceCounter::disable_print_counter_info(), libMesh::ReferenceCounter::enable_print_counter_info(), and libMesh::ReferenceCounter::print_info().
_enable_print_counter [2/2]
bool libMesh::ReferenceCounter::_enable_print_counter = true static protected inherited
Flag to control whether reference count information is printed when print_info is called.
Definition at line 141 of file reference_counter.h.
Referenced by libMesh::ReferenceCounter::disable_print_counter_info(), libMesh::ReferenceCounter::enable_print_counter_info(), and libMesh::ReferenceCounter::print_info().
_mutex [1/2]
Threads::spin_mutex libMesh::ReferenceCounter::_mutex static protected inherited
Mutual exclusion object to enable thread-safe reference counting.
Definition at line 135 of file reference_counter.h.
_mutex [2/2]
Threads::spin_mutex libMesh::ReferenceCounter::_mutex static protected inherited
Mutual exclusion object to enable thread-safe reference counting.
Definition at line 135 of file reference_counter.h.
_n_objects [1/2]
Threads::atomic< unsigned int > libMesh::ReferenceCounter::_n_objects static protected inherited
The number of objects. Print the reference count information when the number returns to 0.
Definition at line 130 of file reference_counter.h.
Referenced by libMesh::ReferenceCounter::n_objects(), libMesh::ReferenceCounter::ReferenceCounter(), and libMesh::ReferenceCounter::~ReferenceCounter().
_n_objects [2/2]
Threads::atomic< unsigned int > libMesh::ReferenceCounter::_n_objects static protected inherited
The number of objects. Print the reference count information when the number returns to 0.
Definition at line 130 of file reference_counter.h.
Referenced by libMesh::ReferenceCounter::n_objects(), libMesh::ReferenceCounter::ReferenceCounter(), and libMesh::ReferenceCounter::~ReferenceCounter().
_valence
valence_idx_t libMesh::Node::_valence private
The number of nodes connected with this node. Currently, this value is invalid (zero) except for subdivision meshes.
Definition at line 207 of file node.h.
Referenced by set_valence(), and valence().
invalid_id
const dof_id_type libMesh::DofObject::invalid_id = static_cast<dof_id_type>(-1) static inherited
An invalid id to distinguish an uninitialized DofObject
Definition at line 347 of file dof_object.h.
Referenced by libMesh::DofMap::_dof_indices(), active(), libMesh::TopologyMap::add_node(), libMesh::MeshRefinement::add_node(), libMesh::ReplicatedMesh::add_point(), libMesh::UnstructuredMesh::all_second_order(), libMesh::MeshTools::Modification::all_tri(), libMesh::Elem::bracketing_nodes(), libMesh::FEGenericBase< FEOutputType< T >::type >::compute_periodic_constraints(), libMesh::FEGenericBase< FEOutputType< T >::type >::compute_proj_constraints(), libMesh::DofMap::distribute_dofs(), libMesh::DofMap::distribute_local_dofs_node_major(), libMesh::DofMap::distribute_local_dofs_var_major(), libMesh::DofMap::dof_indices(), libMesh::DofObject::dof_number(), libMesh::TopologyMap::find(), libMesh::ReplicatedMesh::insert_node(), libMesh::DofObject::invalidate_dofs(), libMesh::DofObject::invalidate_id(), libMesh::MeshTools::libmesh_assert_valid_neighbors(), libMesh::DistributedMesh::libmesh_assert_valid_parallel_object_ids(), libMesh::Elem::node_id(), libMesh::DofMap::old_dof_indices(), libMesh::DistributedMesh::own_node(), libMesh::Parallel::Packing< T >::pack(), libMesh::XdrIO::pack_element(), libMesh::SFCPartitioner::partition_range(), libMesh::Elem::point(), libMesh::System::read_legacy_data(), libMesh::System::read_parallel_data(), libMesh::XdrIO::read_serialized_connectivity(), libMesh::DofMap::SCALAR_dof_indices(), libMesh::DofObject::set_dof_number(), libMesh::DofObject::set_n_comp_group(), libMesh::DofObject::set_n_vars_per_group(), libMesh::DofMap::set_nonlocal_dof_objects(), libMesh::Parallel::sync_node_data_by_element_id_once(), libMesh::Parallel::Packing< T >::unpack(), libMesh::DofObject::valid_id(), and libMesh::System::write_parallel_data().
invalid_processor_id
const processor_id_type libMesh::DofObject::invalid_processor_id = static_cast<processor_id_type>(-1) static inherited
An invalid processor_id to distinguish DoFs that have not been assigned to a processor.
Definition at line 358 of file dof_object.h.
Referenced by libMesh::BoundaryInfo::_find_id_maps(), libMesh::DistributedMesh::add_elem(), libMesh::DistributedMesh::add_node(), libMesh::MeshRefinement::add_node(), libMesh::MeshCommunication::allgather(), choose_processor_id(), libMesh::MeshTools::create_bounding_box(), libMesh::MeshTools::create_nodal_bounding_box(), libMesh::DistributedMesh::delete_elem(), libMesh::DistributedMesh::delete_node(), libMesh::Elem::Elem(), libMesh::MeshCommunication::find_global_indices(), libMesh::DistributedMesh::insert_elem(), libMesh::DofObject::invalidate_processor_id(), libMesh::MeshTools::libmesh_assert_consistent_distributed(), libMesh::MeshTools::libmesh_assert_consistent_distributed_nodes(), libMesh::DistributedMesh::libmesh_assert_valid_parallel_object_ids(), libMesh::DistributedMesh::n_active_elem(), libMesh::MeshBase::n_elem_on_proc(), libMesh::MeshBase::n_nodes_on_proc(), libMesh::MeshBase::n_unpartitioned_elem(), libMesh::MeshBase::n_unpartitioned_nodes(), libMesh::SparsityPattern::Build::operator()(), libMesh::Partitioner::processor_pairs_to_interface_nodes(), libMesh::DistributedMesh::renumber_dof_objects(), libMesh::Partitioner::set_node_processor_ids(), libMesh::DofMap::set_nonlocal_dof_objects(), libMesh::Partitioner::set_parent_processor_ids(), libMesh::Parallel::sync_dofobject_data_by_id(), libMesh::Parallel::sync_dofobject_data_by_xyz(), libMesh::Parallel::sync_element_data_by_parent_id(), libMesh::Parallel::sync_node_data_by_element_id_once(), libMesh::MeshTools::total_weight(), libMesh::Parallel::Packing< T >::unpack(), libMesh::DofObject::valid_processor_id(), and libMesh::CheckpointIO::write().
invalid_unique_id
const unique_id_type libMesh::DofObject::invalid_unique_id = static_cast<unique_id_type>(-1) static inherited
An invalid unique_id to distinguish an uninitialized DofObject
Definition at line 352 of file dof_object.h.
Referenced by libMesh::Parallel::Packing< T >::pack(), libMesh::DistributedMesh::renumber_dof_objects(), libMesh::DofObject::unique_id(), and libMesh::DofObject::valid_unique_id().
old_dof_object
DofObject* libMesh::DofObject::old_dof_object inherited
This object on the last mesh. Useful for projecting solutions from one mesh to another.
Definition at line 79 of file dof_object.h.
Referenced by libMesh::OldSolutionBase< Output, point_output >::check_old_context(), libMesh::DofObject::clear_old_dof_object(), libMesh::OldSolutionValue< Output, point_output >::eval_at_node(), libMesh::OldSolutionCoefs< Output, point_output >::eval_at_node(), libMesh::DofMap::old_dof_indices(), libMesh::BuildProjectionList::operator()(), libMesh::DofObject::operator=(), libMesh::DofObject::pack_indexing(), libMesh::DofObject::packed_indexing_size(), libMesh::DofMap::reinit(), libMesh::DofObject::set_old_dof_object(), and libMesh::DofObject::unpack_indexing().
The documentation for this class was generated from the following files:
node.h
node.C