libMesh: libMesh::TecplotIO Class Reference
SomeWebsiteLogo
libMesh::TecplotIO Class Reference
#include <tecplot_io.h>
Public Member Functions
TecplotIO (const MeshBase &, const bool binary=false, const double time=0., const int strand_offset=0)
virtual void write (const std::string &) override
virtual void write_nodal_data (const std::string &, const std::vector< Number > &, const std::vector< std::string > &) override
bool & binary ()
double & time ()
int & strand_offset ()
std::string & zone_title ()
bool & ascii_append ()
virtual void write_equation_systems (const std::string &, const EquationSystems &, const std::set< std::string > *system_names=nullptr)
virtual void write_discontinuous_equation_systems (const std::string &, const EquationSystems &, const std::set< std::string > *system_names=nullptr)
virtual void write_nodal_data (const std::string &, const NumericVector< Number > &, const std::vector< std::string > &)
virtual void write_nodal_data_discontinuous (const std::string &, const std::vector< Number > &, const std::vector< std::string > &)
unsigned int & ascii_precision ()
Protected Member Functions
const MeshBase & mesh () const
Protected Attributes
const bool _is_parallel_format
const bool _serial_only_needed_on_proc_0
Private Member Functions
void write_ascii (const std::string &, const std::vector< Number > *=nullptr, const std::vector< std::string > *=nullptr)
void write_binary (const std::string &, const std::vector< Number > *=nullptr, const std::vector< std::string > *=nullptr)
unsigned elem_dimension ()
Private Attributes
bool _binary
double _time
int _strand_offset
std::string _zone_title
bool _ascii_append
std::set< subdomain_id_type > _subdomain_ids
Detailed Description
This class implements writing meshes in the Tecplot format.
Author
Benjamin S. Kirk
Date
2004
Definition at line 43 of file tecplot_io.h.
Constructor & Destructor Documentation
TecplotIO()
libMesh::TecplotIO::TecplotIO (const MeshBase & mesh_in, const bool binary = false, const double time = 0., const int strand_offset = 0) explicit
Constructor. Takes a reference to a constant mesh object. This constructor will only allow us to write the mesh. The optional parameter binary can be used to switch between ASCII (false, the default) or binary (true) output files.
Definition at line 122 of file tecplot_io.C.
References _subdomain_ids, and libMesh::MeshBase::subdomain_ids().
                                                   :
   MeshOutput<MeshBase> (mesh_in),
   _binary (binary_in),
   _time (time_in),
   _strand_offset (strand_offset_in),
   _zone_title ("zone"),
   _ascii_append(false)
 {
   // Gather a list of subdomain ids in the mesh.
   // We must do this now, while we have every
   // processor's attention
   // (some of the write methods only execute on processor 0).
   mesh_in.subdomain_ids (_subdomain_ids);
 }
Member Function Documentation
ascii_append()
bool & libMesh::TecplotIO::ascii_append ()
Set to true to write multiple solutions to a single file (ASCII only). Tecplot will read multiple zones in a single file, but currently you have to repeat the mesh information each time.
Definition at line 169 of file tecplot_io.C.
References _ascii_append.
 {
   return _ascii_append;
 }
ascii_precision()
unsigned int & libMesh::MeshOutput< MeshBase >::ascii_precision () inline inherited
Return/set the precision to use when writing ASCII files.
By default we use numeric_limits<Real>::digits10 + 2, which should be enough to write out to ASCII and get the exact same Real back when reading in.
Definition at line 244 of file mesh_output.h.
Referenced by write_ascii(), libMesh::GMVIO::write_ascii_new_impl(), and libMesh::GMVIO::write_ascii_old_impl().
 {
   return _ascii_precision;
 }
binary()
bool & libMesh::TecplotIO::binary ()
Flag indicating whether or not to write a binary file (if the tecio.a library was found by configure).
Definition at line 142 of file tecplot_io.C.
References _binary.
Referenced by write(), and write_nodal_data().
 {
   return _binary;
 }
elem_dimension()
unsigned libMesh::TecplotIO::elem_dimension () private
Determines the logical spatial dimension of the elements in the Mesh. Ex: A 1D edge element living in 3D is a logically one-dimensional element as far as Tecplot is concerned. Throws an error if mixed-dimension element types are found, since I'm not sure how to handle that case currently.
Definition at line 205 of file tecplot_io.C.
References libMesh::MeshBase::active_element_ptr_range(), and libMesh::MeshOutput< MT >::mesh().
Referenced by write_ascii(), and write_binary().
 {
   // Get a constant reference to the mesh.
   const MeshBase & the_mesh = MeshOutput<MeshBase>::mesh();
   std::vector<unsigned> elem_dims(3);
   // Loop over all the elements and mark the proper dimension entry in
   // the elem_dims vector.
   for (const auto & elem : the_mesh.active_element_ptr_range())
     elem_dims[elem->dim() - 1] = 1;
   // Detect and disallow (for now) the writing of mixed dimension meshes.
   if (std::count(elem_dims.begin(), elem_dims.end(), 1) > 1)
     libmesh_error_msg("Error, cannot write Mesh with mixed element dimensions to Tecplot file!");
   if (elem_dims[0])
     return 1;
   else if (elem_dims[1])
     return 2;
   else if (elem_dims[2])
     return 3;
   else
     libmesh_error_msg("No 1, 2, or 3D elements detected!");
 }
mesh()
const MeshBase & libMesh::MeshOutput< MeshBase >::mesh () const inline protected inherited
Returns
The object as a read-only reference.
Definition at line 234 of file mesh_output.h.
Referenced by libMesh::FroIO::write(), write(), libMesh::MEDITIO::write(), libMesh::PostscriptIO::write(), libMesh::EnsightIO::write(), write_ascii(), write_binary(), write_nodal_data(), libMesh::MEDITIO::write_nodal_data(), and libMesh::GnuPlotIO::write_solution().
 {
   libmesh_assert(_obj);
   return *_obj;
 }
strand_offset()
int & libMesh::TecplotIO::strand_offset ()
Strand offset for this file. Each mesh block will be written to (strand_id=block_id+1+strand_offset). Written to newer binary formats that are time-aware, defaults to 0.
Definition at line 156 of file tecplot_io.C.
References _strand_offset.
Referenced by write_binary().
 {
   return _strand_offset;
 }
time()
double & libMesh::TecplotIO::time ()
Solution time for transient data. Written to newer binary formats that are time-aware.
Definition at line 149 of file tecplot_io.C.
References _time.
 {
   return _time;
 }
write()
void libMesh::TecplotIO::write (const std::string & fname) override virtual
This method implements writing a mesh to a specified file.
Implements libMesh::MeshOutput< MeshBase >.
Definition at line 175 of file tecplot_io.C.
References binary(), libMesh::MeshOutput< MeshBase >::mesh(), write_ascii(), and write_binary().
Referenced by libMesh::NameBasedIO::write().
 {
   if (this->mesh().processor_id() == 0)
     {
       if (this->binary())
         this->write_binary (fname);
       else
         this->write_ascii  (fname);
     }
 }
write_ascii()
void libMesh::TecplotIO::write_ascii (const std::string & fname, const std::vector< Number > * v = nullptr, const std::vector< std::string > * solution_names = nullptr) private
This method implements writing a mesh with nodal data to a specified file where the nodal data and variable names are optionally provided. This will write an ASCII file.
Definition at line 233 of file tecplot_io.C.
References _ascii_append, _time, std::abs(), libMesh::MeshBase::active_element_ptr_range(), libMesh::MeshOutput< MeshBase >::ascii_precision(), elem_dimension(), libMesh::MeshOutput< MeshBase >::mesh(), libMesh::MeshOutput< MT >::mesh(), libMesh::MeshBase::n_active_sub_elem(), libMesh::MeshBase::n_nodes(), n_vars, libMesh::out, libMesh::MeshBase::point(), libMesh::TECPLOT, and libMesh::TypeVector< T >::write_unformatted().
Referenced by write(), write_binary(), and write_nodal_data().
 {
   // Should only do this on processor 0!
   libmesh_assert_equal_to (this->mesh().processor_id(), 0);
   // Create an output stream, possibly in append mode.
   std::ofstream out_stream(fname.c_str(), _ascii_append ? std::ofstream::app : std::ofstream::out);
   // Make sure it opened correctly
   if (!out_stream.good())
     libmesh_file_error(fname.c_str());
   // Get a constant reference to the mesh.
   const MeshBase & the_mesh = MeshOutput<MeshBase>::mesh();
   // Write header to stream
   {
     {
       // TODO: We used to print out the SVN revision here when we did keyword expansions...
       out_stream << "# For a description of the Tecplot format see the Tecplot User's guide.\n"
                  << "#\n";
     }
     out_stream << "Variables=x,y,z";
     if (solution_names != nullptr)
       for (std::size_t n=0; n<solution_names->size(); n++)
         {
 #ifdef LIBMESH_USE_REAL_NUMBERS
           // Write variable names for real variables
           out_stream << "," << (*solution_names)[n];
 #else
           // Write variable names for complex variables
           out_stream << "," << "r_"   << (*solution_names)[n]
                      << "," << "i_"   << (*solution_names)[n]
                      << "," << "a_"   << (*solution_names)[n];
 #endif
         }
     out_stream << '\n';
     out_stream << "Zone f=fepoint, n=" << the_mesh.n_nodes() << ", e=" << the_mesh.n_active_sub_elem();
     // We cannot choose the element type simply based on the mesh
     // dimension... there might be 1D elements living in a 3D mesh.
     // So look at the elements which are actually in the Mesh, and
     // choose either "lineseg", "quadrilateral", or "brick" depending
     // on if the elements are 1, 2, or 3D.
     // Write the element type we've determined to the header.
     out_stream << ", et=";
     switch (this->elem_dimension())
       {
       case 1:
         out_stream << "lineseg";
         break;
       case 2:
         out_stream << "quadrilateral";
         break;
       case 3:
         out_stream << "brick";
         break;
       default:
         libmesh_error_msg("Unsupported element dimension: " << this->elem_dimension());
       }
     // Output the time in the header
     out_stream << ", t=\"T " << _time << "\"";
     // Use default mesh color = black
     out_stream << ", c=black\n";
   } // finished writing header
   for (unsigned int i=0; i<the_mesh.n_nodes(); i++)
     {
       // Print the point without a newline
       the_mesh.point(i).write_unformatted(out_stream, false);
       if ((v != nullptr) && (solution_names != nullptr))
         {
           const std::size_t n_vars = solution_names->size();
           for (std::size_t c=0; c<n_vars; c++)
             {
 #ifdef LIBMESH_USE_REAL_NUMBERS
               // Write real data
               out_stream << std::setprecision(this->ascii_precision())
                          << (*v)[i*n_vars + c] << " ";
 #else
               // Write complex data
               out_stream << std::setprecision(this->ascii_precision())
                          << (*v)[i*n_vars + c].real() << " "
                          << (*v)[i*n_vars + c].imag() << " "
                          << std::abs((*v)[i*n_vars + c]) << " ";
 #endif
             }
         }
       // Write a new line after the data for this node
       out_stream << '\n';
     }
   for (const auto & elem : the_mesh.active_element_ptr_range())
     elem->write_connectivity(out_stream, TECPLOT);
 }
write_binary()
void libMesh::TecplotIO::write_binary (const std::string & fname, const std::vector< Number > * vec = nullptr, const std::vector< std::string > * solution_names = nullptr) private
This method implements writing a mesh with nodal data to a specified file where the nodal data and variable names are optionally provided. This will write a binary file if the tecio.a library was found at compile time, otherwise a warning message will be printed and an ASCII file will be created.
Definition at line 352 of file tecplot_io.C.
References _subdomain_ids, _time, std::abs(), libMesh::MeshBase::active_element_ptr_range(), libMesh::MeshBase::active_subdomain_elements_begin(), libMesh::MeshBase::active_subdomain_elements_end(), libMesh::as_range(), elem_dimension(), libMesh::err, ierr, std::max(), libMesh::MeshOutput< MT >::mesh(), libMesh::MeshOutput< MeshBase >::mesh(), libMesh::MeshBase::mesh_dimension(), libMesh::MeshBase::n_active_sub_elem(), libMesh::MeshBase::n_nodes(), n_vars, libMesh::Quality::name(), libMesh::MeshBase::point(), strand_offset(), libMesh::MeshBase::subdomain_name(), libMesh::TECPLOT, write_ascii(), and zone_title().
Referenced by write(), and write_nodal_data().
 {
   //-----------------------------------------------------------
   // Call the ASCII output function if configure did not detect
   // the Tecplot binary API
 #ifndef LIBMESH_HAVE_TECPLOT_API
   libMesh::err << "WARNING: Tecplot Binary files require the Tecplot API." << std::endl
                << "Continuing with ASCII output."
                << std::endl;
   if (this->mesh().processor_id() == 0)
     this->write_ascii (fname, vec, solution_names);
   return;
   //------------------------------------------------------------
   // New binary formats, time aware and whatnot
 #elif defined(LIBMESH_HAVE_TECPLOT_API_112)
   // Get a constant reference to the mesh.
   const MeshBase & the_mesh = MeshOutput<MeshBase>::mesh();
   // Required variables
   std::string tecplot_variable_names;
   int
     ierr      =  0,
     file_type =  0, // full
     is_double =  0,
 #ifdef DEBUG
     tec_debug =  1,
 #else
     tec_debug =  0,
 #endif
     cell_type   = -1,
     nn_per_elem = -1;
   switch (this->elem_dimension())
     {
     case 1:
       cell_type   = 1;  // FELINESEG
       nn_per_elem = 2;
       break;
     case 2:
       cell_type   = 3; // FEQUADRILATERAL
       nn_per_elem = 4;
       break;
     case 3:
       cell_type   = 5; // FEBRICK
       nn_per_elem = 8;
       break;
     default:
       libmesh_error_msg("Unsupported element dimension: " << this->elem_dimension());
     }
   // Build a string containing all the variable names to pass to Tecplot
   {
     tecplot_variable_names += "x, y, z";
     if (solution_names != nullptr)
       {
         for (std::size_t name=0; name<solution_names->size(); name++)
           {
 #ifdef LIBMESH_USE_REAL_NUMBERS
             tecplot_variable_names += ", ";
             tecplot_variable_names += (*solution_names)[name];
 #else
             tecplot_variable_names += ", ";
             tecplot_variable_names += "r_";
             tecplot_variable_names += (*solution_names)[name];
             tecplot_variable_names += ", ";
             tecplot_variable_names += "i_";
             tecplot_variable_names += (*solution_names)[name];
             tecplot_variable_names += ", ";
             tecplot_variable_names += "a_";
             tecplot_variable_names += (*solution_names)[name];
 #endif
           }
       }
   }
   // Instantiate a TecplotMacros interface.  In 2D the most nodes per
   // face should be 4, in 3D it's 8.
   TecplotMacros tm(the_mesh.n_nodes(),
 #ifdef LIBMESH_USE_REAL_NUMBERS
                    (3 + ((solution_names == nullptr) ? 0 :
                          cast_int<unsigned int>(solution_names->size()))),
 #else
                    (3 + 3*((solution_names == nullptr) ? 0 :
                            cast_int<unsigned int>(solution_names->size()))),
 #endif
                    the_mesh.n_active_sub_elem(),
                    nn_per_elem
                    );
   // Copy the nodes and data to the TecplotMacros class. Note that we store
   // everything as a float here since the eye doesn't require a double to
   // understand what is going on
   for (unsigned int v=0; v<the_mesh.n_nodes(); v++)
     {
       tm.nd(0,v) = static_cast<float>(the_mesh.point(v)(0));
       tm.nd(1,v) = static_cast<float>(the_mesh.point(v)(1));
       tm.nd(2,v) = static_cast<float>(the_mesh.point(v)(2));
       if ((vec != nullptr) &&
           (solution_names != nullptr))
         {
           const std::size_t n_vars = solution_names->size();
           for (std::size_t c=0; c<n_vars; c++)
             {
 #ifdef LIBMESH_USE_REAL_NUMBERS
               tm.nd((3+c),v)     = static_cast<float>((*vec)[v*n_vars + c]);
 #else
               tm.nd((3+3*c),v)   = static_cast<float>((*vec)[v*n_vars + c].real());
               tm.nd((3+3*c+1),v) = static_cast<float>((*vec)[v*n_vars + c].imag());
               tm.nd((3+3*c+2),v) = static_cast<float>(std::abs((*vec)[v*n_vars + c]));
 #endif
             }
         }
     }
   // Initialize the file
   ierr = TECINI112 (nullptr,
                     const_cast<char *>(tecplot_variable_names.c_str()),
                     const_cast<char *>(fname.c_str()),
                     const_cast<char *>("."),
                     &file_type,
                     &tec_debug,
                     &is_double);
   if (ierr)
     libmesh_file_error(fname);
   // A zone for each subdomain
   bool firstzone=true;
   for (const auto & sbd_id : _subdomain_ids)
     {
       // Copy the connectivity for this subdomain
       {
         unsigned int n_subcells_in_subdomain=0;
         for (const auto & elem :
                as_range(the_mesh.active_subdomain_elements_begin(sbd_id),
                         the_mesh.active_subdomain_elements_end(sbd_id)))
           n_subcells_in_subdomain += elem->n_sub_elem();
         // update the connectivity array to include only the elements in this subdomain
         tm.set_n_cells (n_subcells_in_subdomain);
         unsigned int te = 0;
         for (const auto & elem :
                as_range(the_mesh.active_subdomain_elements_begin(sbd_id),
                         the_mesh.active_subdomain_elements_end(sbd_id)))
           {
             std::vector<dof_id_type> conn;
             for (unsigned int se=0; se<elem->n_sub_elem(); se++)
               {
                 elem->connectivity(se, TECPLOT, conn);
                 for (std::size_t node=0; node<conn.size(); node++)
                   tm.cd(node,te) = conn[node];
                 te++;
               }
           }
       }
       // Ready to call the Tecplot API for this subdomain
       {
         int
           num_nodes   = static_cast<int>(the_mesh.n_nodes()),
           num_cells   = static_cast<int>(tm.n_cells),
           num_faces   = 0,
           i_cell_max  = 0,
           j_cell_max  = 0,
           k_cell_max  = 0,
           strand_id   = std::max(sbd_id, static_cast<subdomain_id_type>(1)) + this->strand_offset(),
           parent_zone = 0,
           is_block    = 1,
           num_face_connect   = 0,
           face_neighbor_mode = 0,
           tot_num_face_nodes = 0,
           num_connect_boundary_faces = 0,
           tot_num_boundary_connect   = 0,
           share_connect_from_zone=0;
         std::vector<int>
           passive_var_list    (tm.n_vars, 0),
           share_var_from_zone (tm.n_vars, 1); // We only write data for the first zone, all other
         // zones will share from this one.
         // get the subdomain name from libMesh, if there is one.
         std::string subdomain_name = the_mesh.subdomain_name(sbd_id);
         std::ostringstream zone_name;
         zone_name << this->zone_title();
         // We will title this
         // "{zone_title()}_{subdomain_name}", or
         // "{zone_title()}_{subdomain_id}", or
         // "{zone_title()}"
         if (subdomain_name.size())
           {
             zone_name << "_";
             zone_name << subdomain_name;
           }
         else if (_subdomain_ids.size() > 1)
           {
             zone_name << "_";
             zone_name << sbd_id;
           }
         ierr = TECZNE112 (const_cast<char *>(zone_name.str().c_str()),
                           &cell_type,
                           &num_nodes,
                           &num_cells,
                           &num_faces,
                           &i_cell_max,
                           &j_cell_max,
                           &k_cell_max,
                           &_time,
                           &strand_id,
                           &parent_zone,
                           &is_block,
                           &num_face_connect,
                           &face_neighbor_mode,
                           &tot_num_face_nodes,
                           &num_connect_boundary_faces,
                           &tot_num_boundary_connect,
                           passive_var_list.data(),
                           nullptr, // = all are node centered
                           (firstzone) ? nullptr : share_var_from_zone.data(),
                           &share_connect_from_zone);
         if (ierr)
           libmesh_file_error(fname);
         // Write *all* the data for the first zone, then share it with the others
         if (firstzone)
           {
             int total = cast_int<int>
 #ifdef LIBMESH_USE_REAL_NUMBERS
               ((3 + ((solution_names == nullptr) ? 0 : solution_names->size()))*num_nodes);
 #else
             ((3 + 3*((solution_names == nullptr) ? 0 : solution_names->size()))*num_nodes);
 #endif
             ierr = TECDAT112 (&total,
                               tm.nodalData.data(),
                               &is_double);
             if (ierr)
               libmesh_file_error(fname);
           }
         // Write the connectivity
         ierr = TECNOD112 (tm.connData.data());
         if (ierr)
           libmesh_file_error(fname);
       }
       firstzone = false;
     }
   // Done, close the file.
   ierr = TECEND112 ();
   if (ierr)
     libmesh_file_error(fname);
   //------------------------------------------------------------
   // Legacy binary format
 #else
   // Get a constant reference to the mesh.
   const MeshBase & the_mesh = MeshOutput<MeshBase>::mesh();
   // Tecplot binary output only good for dim=2,3
   if (the_mesh.mesh_dimension() == 1)
     {
       this->write_ascii (fname, vec, solution_names);
       return;
     }
   // Required variables
   std::string tecplot_variable_names;
   int is_double =  0,
     tec_debug =  0,
     cell_type = ((the_mesh.mesh_dimension()==2) ? (1) : (3));
   // Build a string containing all the variable names to pass to Tecplot
   {
     tecplot_variable_names += "x, y, z";
     if (solution_names != nullptr)
       {
         for (std::size_t name=0; name<solution_names->size(); name++)
           {
 #ifdef LIBMESH_USE_REAL_NUMBERS
             tecplot_variable_names += ", ";
             tecplot_variable_names += (*solution_names)[name];
 #else
             tecplot_variable_names += ", ";
             tecplot_variable_names += "r_";
             tecplot_variable_names += (*solution_names)[name];
             tecplot_variable_names += ", ";
             tecplot_variable_names += "i_";
             tecplot_variable_names += (*solution_names)[name];
             tecplot_variable_names += ", ";
             tecplot_variable_names += "a_";
             tecplot_variable_names += (*solution_names)[name];
 #endif
           }
       }
   }
   // Instantiate a TecplotMacros interface.  In 2D the most nodes per
   // face should be 4, in 3D it's 8.
   TecplotMacros tm(cast_int<unsigned int>(the_mesh.n_nodes()),
                    cast_int<unsigned int>
 #ifdef LIBMESH_USE_REAL_NUMBERS
                    (3 + ((solution_names == nullptr) ? 0 : solution_names->size())),
 #else
                    (3 + 3*((solution_names == nullptr) ? 0 : solution_names->size())),
 #endif
                    cast_int<unsigned int>
                    (the_mesh.n_active_sub_elem()),
                    ((the_mesh.mesh_dimension() == 2) ? 4 : 8)
                    );
   // Copy the nodes and data to the TecplotMacros class. Note that we store
   // everything as a float here since the eye doesn't require a double to
   // understand what is going on
   for (unsigned int v=0; v<the_mesh.n_nodes(); v++)
     {
       tm.nd(0,v) = static_cast<float>(the_mesh.point(v)(0));
       tm.nd(1,v) = static_cast<float>(the_mesh.point(v)(1));
       tm.nd(2,v) = static_cast<float>(the_mesh.point(v)(2));
       if ((vec != nullptr) &&
           (solution_names != nullptr))
         {
           const std::size_t n_vars = solution_names->size();
           for (std::size_t c=0; c<n_vars; c++)
             {
 #ifdef LIBMESH_USE_REAL_NUMBERS
               tm.nd((3+c),v)     = static_cast<float>((*vec)[v*n_vars + c]);
 #else
               tm.nd((3+3*c),v)   = static_cast<float>((*vec)[v*n_vars + c].real());
               tm.nd((3+3*c+1),v) = static_cast<float>((*vec)[v*n_vars + c].imag());
               tm.nd((3+3*c+2),v) = static_cast<float>(std::abs((*vec)[v*n_vars + c]));
 #endif
             }
         }
     }
   // Copy the connectivity
   {
     unsigned int te = 0;
     for (const auto & elem : the_mesh.active_element_ptr_range())
       {
         std::vector<dof_id_type> conn;
         for (unsigned int se=0; se<elem->n_sub_elem(); se++)
           {
             elem->connectivity(se, TECPLOT, conn);
             for (std::size_t node=0; node<conn.size(); node++)
               tm.cd(node,te) = conn[node];
             te++;
           }
       }
   }
   // Ready to call the Tecplot API
   {
     int ierr = 0,
       num_nodes = static_cast<int>(the_mesh.n_nodes()),
       num_cells = static_cast<int>(the_mesh.n_active_sub_elem());
     ierr = TECINI (nullptr,
                    (char *) tecplot_variable_names.c_str(),
                    (char *) fname.c_str(),
                    (char *) ".",
                    &tec_debug,
                    &is_double);
     if (ierr)
       libmesh_file_error(fname);
     ierr = TECZNE (nullptr,
                    &num_nodes,
                    &num_cells,
                    &cell_type,
                    (char *) "FEBLOCK",
                    nullptr);
     if (ierr)
       libmesh_file_error(fname);
     int total =
 #ifdef LIBMESH_USE_REAL_NUMBERS
       ((3 + ((solution_names == nullptr) ? 0 : solution_names->size()))*num_nodes);
 #else
     ((3 + 3*((solution_names == nullptr) ? 0 : solution_names->size()))*num_nodes);
 #endif
     ierr = TECDAT (&total,
                    tm.nodalData.data(),
                    &is_double);
     if (ierr)
       libmesh_file_error(fname);
     ierr = TECNOD (tm.connData.data());
     if (ierr)
       libmesh_file_error(fname);
     ierr = TECEND ();
     if (ierr)
       libmesh_file_error(fname);
   }
 #endif
 }
write_discontinuous_equation_systems()
void libMesh::MeshOutput< MeshBase >::write_discontinuous_equation_systems (const std::string & fname, const EquationSystems & es, const std::set< std::string > * system_names = nullptr) virtual inherited
This method implements writing a mesh with discontinuous data to a specified file where the data is taken from the EquationSystems object.
Definition at line 92 of file mesh_output.C.
References libMesh::EquationSystems::build_discontinuous_solution_vector(), libMesh::EquationSystems::build_variable_names(), libMesh::EquationSystems::get_mesh(), and libMesh::out.
Referenced by libMesh::ExodusII_IO::write_timestep_discontinuous().
 {
   LOG_SCOPE("write_discontinuous_equation_systems()", "MeshOutput");
   // We may need to gather and/or renumber a DistributedMesh to output
   // it, making that const qualifier in our constructor a dirty lie
   MT & my_mesh = const_cast<MT &>(*_obj);
   // If we're asked to write data that's associated with a different
   // mesh, output files full of garbage are the result.
   libmesh_assert_equal_to(&es.get_mesh(), _obj);
   // A non-renumbered mesh may not have a contiguous numbering, and
   // that needs to be fixed before we can build a solution vector.
   if (my_mesh.max_elem_id() != my_mesh.n_elem() ||
       my_mesh.max_node_id() != my_mesh.n_nodes())
     {
       // If we were allowed to renumber then we should have already
       // been properly renumbered...
       libmesh_assert(!my_mesh.allow_renumbering());
       libmesh_do_once(libMesh::out <<
                       "Warning:  This MeshOutput subclass only supports meshes which are contiguously renumbered!"
                       << std::endl;);
       my_mesh.allow_renumbering(true);
       my_mesh.renumber_nodes_and_elements();
       // Not sure what good going back to false will do here, the
       // renumbering horses have already left the barn...
       my_mesh.allow_renumbering(false);
     }
   MeshSerializer serialize(const_cast<MT &>(*_obj), !_is_parallel_format, _serial_only_needed_on_proc_0);
   // Build the list of variable names that will be written.
   std::vector<std::string> names;
   es.build_variable_names  (names, nullptr, system_names);
   if (!_is_parallel_format)
     {
       // Build the nodal solution values & get the variable
       // names from the EquationSystems object
       std::vector<Number> soln;
       es.build_discontinuous_solution_vector (soln, system_names);
       this->write_nodal_data_discontinuous (fname, soln, names);
     }
   else // _is_parallel_format
     {
       libmesh_not_implemented();
     }
 }
write_equation_systems()
void libMesh::MeshOutput< MeshBase >::write_equation_systems (const std::string & fname, const EquationSystems & es, const std::set< std::string > * system_names = nullptr) virtual inherited
This method implements writing a mesh with data to a specified file where the data is taken from the EquationSystems object.
Reimplemented in libMesh::NameBasedIO.
Definition at line 31 of file mesh_output.C.
References libMesh::EquationSystems::build_parallel_solution_vector(), libMesh::EquationSystems::build_solution_vector(), libMesh::EquationSystems::build_variable_names(), libMesh::EquationSystems::get_mesh(), and libMesh::out.
Referenced by libMesh::Nemesis_IO::write_timestep(), and libMesh::ExodusII_IO::write_timestep().
 {
   LOG_SCOPE("write_equation_systems()", "MeshOutput");
   // We may need to gather and/or renumber a DistributedMesh to output
   // it, making that const qualifier in our constructor a dirty lie
   MT & my_mesh = const_cast<MT &>(*_obj);
   // If we're asked to write data that's associated with a different
   // mesh, output files full of garbage are the result.
   libmesh_assert_equal_to(&es.get_mesh(), _obj);
   // A non-renumbered mesh may not have a contiguous numbering, and
   // that needs to be fixed before we can build a solution vector.
   if (my_mesh.max_elem_id() != my_mesh.n_elem() ||
       my_mesh.max_node_id() != my_mesh.n_nodes())
     {
       // If we were allowed to renumber then we should have already
       // been properly renumbered...
       libmesh_assert(!my_mesh.allow_renumbering());
       libmesh_do_once(libMesh::out <<
                       "Warning:  This MeshOutput subclass only supports meshes which are contiguously renumbered!"
                       << std::endl;);
       my_mesh.allow_renumbering(true);
       my_mesh.renumber_nodes_and_elements();
       // Not sure what good going back to false will do here, the
       // renumbering horses have already left the barn...
       my_mesh.allow_renumbering(false);
     }
   MeshSerializer serialize(const_cast<MT &>(*_obj), !_is_parallel_format, _serial_only_needed_on_proc_0);
   // Build the list of variable names that will be written.
   std::vector<std::string> names;
   es.build_variable_names  (names, nullptr, system_names);
   if (!_is_parallel_format)
     {
       // Build the nodal solution values & get the variable
       // names from the EquationSystems object
       std::vector<Number> soln;
       es.build_solution_vector (soln, system_names);
       this->write_nodal_data (fname, soln, names);
     }
   else // _is_parallel_format
     {
       std::unique_ptr<NumericVector<Number>> parallel_soln =
         es.build_parallel_solution_vector(system_names);
       this->write_nodal_data (fname, *parallel_soln, names);
     }
 }
write_nodal_data() [1/2]
void libMesh::TecplotIO::write_nodal_data (const std::string & fname, const std::vector< Number > & soln, const std::vector< std::string > & names) override virtual
This method implements writing a mesh with nodal data to a specified file where the nodal data and variable names are provided.
Reimplemented from libMesh::MeshOutput< MeshBase >.
Definition at line 188 of file tecplot_io.C.
References binary(), libMesh::MeshOutput< MeshBase >::mesh(), write_ascii(), and write_binary().
Referenced by libMesh::NameBasedIO::write_nodal_data().
 {
   LOG_SCOPE("write_nodal_data()", "TecplotIO");
   if (this->mesh().processor_id() == 0)
     {
       if (this->binary())
         this->write_binary (fname, &soln, &names);
       else
         this->write_ascii  (fname, &soln, &names);
     }
 }
write_nodal_data() [2/2]
void libMesh::MeshOutput< MeshBase >::write_nodal_data (const std::string & fname, const NumericVector< Number > & parallel_soln, const std::vector< std::string > & names) virtual inherited
This method should be overridden by "parallel" output formats for writing nodal data. Instead of getting a localized copy of the nodal solution vector, it is passed a NumericVector of type=PARALLEL which is in node-major order i.e. (u0,v0,w0, u1,v1,w1, u2,v2,w2, u3,v3,w3, ...) and contains n_nodes*n_vars total entries. Then, it is up to the individual I/O class to extract the required solution values from this vector and write them in parallel.
If not implemented, localizes the parallel vector into a std::vector and calls the other version of this function.
Reimplemented in libMesh::Nemesis_IO.
Definition at line 150 of file mesh_output.C.
References libMesh::NumericVector< T >::localize().
 {
   // This is the fallback implementation for parallel I/O formats that
   // do not yet implement proper writing in parallel, and instead rely
   // on the full solution vector being available on all processors.
   std::vector<Number> soln;
   parallel_soln.localize(soln);
   this->write_nodal_data(fname, soln, names);
 }
write_nodal_data_discontinuous()
virtual void libMesh::MeshOutput< MeshBase >::write_nodal_data_discontinuous (const std::string & , const std::vector< Number > & , const std::vector< std::string > &) inline virtual inherited
This method implements writing a mesh with discontinuous data to a specified file where the nodal data and variables names are provided.
Reimplemented in libMesh::ExodusII_IO.
Definition at line 114 of file mesh_output.h.
   { libmesh_not_implemented(); }
zone_title()
std::string & libMesh::TecplotIO::zone_title ()
The zone title to write.
Definition at line 163 of file tecplot_io.C.
References _zone_title.
Referenced by write_binary().
 {
   return _zone_title;
 }
Member Data Documentation
_ascii_append
bool libMesh::TecplotIO::_ascii_append private
If true, when writing in ASCII format, open the file in std::ofstream::app mode.
Definition at line 167 of file tecplot_io.h.
Referenced by ascii_append(), and write_ascii().
_binary
bool libMesh::TecplotIO::_binary private
Flag to write binary data.
Definition at line 146 of file tecplot_io.h.
Referenced by binary().
_is_parallel_format
const bool libMesh::MeshOutput< MeshBase >::_is_parallel_format protected inherited
Flag specifying whether this format is parallel-capable. If this is false (default) I/O is only permitted when the mesh has been serialized.
Definition at line 159 of file mesh_output.h.
Referenced by libMesh::FroIO::write(), libMesh::PostscriptIO::write(), and libMesh::EnsightIO::write().
_serial_only_needed_on_proc_0
const bool libMesh::MeshOutput< MeshBase >::_serial_only_needed_on_proc_0 protected inherited
Flag specifying whether this format can be written by only serializing the mesh to processor zero
If this is false (default) the mesh will be serialized to all processors
Definition at line 168 of file mesh_output.h.
_strand_offset
int libMesh::TecplotIO::_strand_offset private
Offset for Tecplot's STRANDID.
Definition at line 156 of file tecplot_io.h.
Referenced by strand_offset().
_subdomain_ids
std::set<subdomain_id_type> libMesh::TecplotIO::_subdomain_ids private
The subdomains in the mesh.
Definition at line 172 of file tecplot_io.h.
Referenced by TecplotIO(), and write_binary().
_time
double libMesh::TecplotIO::_time private
Solution time.
Definition at line 151 of file tecplot_io.h.
Referenced by time(), write_ascii(), and write_binary().
_zone_title
std::string libMesh::TecplotIO::_zone_title private
The zone title to write.
Definition at line 161 of file tecplot_io.h.
Referenced by zone_title().
The documentation for this class was generated from the following files:
tecplot_io.h
tecplot_io.C