libMesh: libMesh::Parallel::StandardType< std::tuple< Types... > > Class Template Reference
SomeWebsiteLogo
libMesh::Parallel::StandardType< std::tuple< Types... > > Class Template Reference
#include <standard_type.h>
Public Member Functions
StandardType (const std::tuple< Types... > *example=nullptr)
StandardType (const StandardType< std::tuple< Types... >> &t)
~StandardType ()
operator const data_type & () const
operator data_type & ()
void commit ()
void free ()
Protected Attributes
data_type _datatype
Detailed Description
template<typename... Types>
class libMesh::Parallel::StandardType< std::tuple< Types... > >
Definition at line 261 of file standard_type.h.
Constructor & Destructor Documentation
StandardType() [1/2]
template<typename... Types> libMesh::Parallel::StandardType< std::tuple< Types... > >::StandardType (const std::tuple< Types... > * example = nullptr) inline explicit
Definition at line 265 of file standard_type.h.
References libMesh::Parallel::DataType::_datatype, and libMesh::Parallel::DataType::commit().
{
     // We need an example for MPI_Address to use
     static const std::tuple<Types...> t;
     if (!example)
       example = &t;
 #ifdef LIBMESH_HAVE_MPI
     MPI_Aint start;
     libmesh_call_mpi
       (MPI_Get_address (example, &start));
     const std::size_t tuplesize = sizeof...(Types);
     std::vector<std::unique_ptr<DataType>> subtypes;
     BuildStandardTypeVector<sizeof...(Types)>::build(subtypes, *example);
     std::array<MPI_Aint, sizeof...(Types)> displs;
     FillDisplacementArray<sizeof...(Types)>::fill(displs, *example);
     std::array<MPI_Datatype, sizeof...(Types)> types;
     std::array<int, sizeof...(Types)> blocklengths;
     for (std::size_t i = 0; i != tuplesize; ++i)
     {
       displs[i] -= start;
       types[i] = (data_type)(*subtypes[i]);
       blocklengths[i] = 1;
     }
     // create a prototype structure
     MPI_Datatype tmptype;
     libmesh_call_mpi
       (MPI_Type_create_struct (tuplesize, blocklengths.data(), displs.data(), types.data(),
                                &tmptype));
     libmesh_call_mpi
       (MPI_Type_commit (&tmptype));
     // resize the structure type to account for padding, if any
     libmesh_call_mpi
       (MPI_Type_create_resized (tmptype, 0,
                                 sizeof(std::tuple<Types...>),
                                 &_datatype));
     libmesh_call_mpi
       (MPI_Type_free (&tmptype));
     this->commit();
 #endif // LIBMESH_HAVE_MPI
   }
StandardType() [2/2]
template<typename... Types> libMesh::Parallel::StandardType< std::tuple< Types... > >::StandardType (const StandardType< std::tuple< Types... >> & t) inline
Definition at line 317 of file standard_type.h.
References libMesh::Parallel::DataType::_datatype.
   {
     libmesh_call_mpi
       (MPI_Type_dup (t._datatype, &_datatype));
   }
~StandardType()
template<typename... Types> libMesh::Parallel::StandardType< std::tuple< Types... > >::~StandardType () inline
Definition at line 323 of file standard_type.h.
References libMesh::Parallel::DataType::free().
 { this->free(); }
Member Function Documentation
commit()
void libMesh::Parallel::DataType::commit () inline inherited
Definition at line 103 of file data_type.h.
References libMesh::Parallel::DataType::_datatype.
Referenced by libMesh::Parallel::DataType::DataType(), libMesh::Parallel::StandardType< std::pair< T1, T2 > >::StandardType(), and StandardType().
   {
     libmesh_call_mpi
       (MPI_Type_commit (&_datatype));
   }
free()
void libMesh::Parallel::DataType::free () inline inherited
Definition at line 109 of file data_type.h.
References libMesh::Parallel::DataType::_datatype.
Referenced by libMesh::Parallel::StandardType< Hilbert::HilbertIndices >::~StandardType(), libMesh::Parallel::StandardType< TypeVector< T > >::~StandardType(), libMesh::Parallel::StandardType< VectorValue< T > >::~StandardType(), libMesh::Parallel::StandardType< std::pair< T1, T2 > >::~StandardType(), libMesh::Parallel::StandardType< Point >::~StandardType(), ~StandardType(), libMesh::Parallel::StandardType< std::complex< T > >::~StandardType(), libMesh::Parallel::StandardType< TypeTensor< T > >::~StandardType(), and libMesh::Parallel::StandardType< TensorValue< T > >::~StandardType().
   {
     libmesh_call_mpi
       (MPI_Type_free (&_datatype));
   }
operator const data_type &()
libMesh::Parallel::DataType::operator const data_type & () const inline inherited
Definition at line 91 of file data_type.h.
References libMesh::Parallel::DataType::_datatype.
   { return _datatype; }
operator data_type &()
libMesh::Parallel::DataType::operator data_type & () inline inherited
Definition at line 94 of file data_type.h.
References libMesh::Parallel::DataType::_datatype.
   { return _datatype; }
Member Data Documentation
_datatype
data_type libMesh::Parallel::DataType::_datatype protected inherited
Definition at line 117 of file data_type.h.
Referenced by libMesh::Parallel::DataType::commit(), libMesh::Parallel::DataType::DataType(), libMesh::Parallel::DataType::free(), libMesh::Parallel::DataType::operator const data_type &(), libMesh::Parallel::DataType::operator data_type &(), libMesh::Parallel::DataType::operator=(), libMesh::Parallel::StandardType< TypeVector< T > >::StandardType(), libMesh::Parallel::StandardType< Hilbert::HilbertIndices >::StandardType(), libMesh::Parallel::StandardType< VectorValue< T > >::StandardType(), libMesh::Parallel::StandardType< std::pair< T1, T2 > >::StandardType(), libMesh::Parallel::StandardType< Point >::StandardType(), and StandardType().
The documentation for this class was generated from the following file:
standard_type.h