libMesh: libMesh::VectorValue< T > Class Template Reference
SomeWebsiteLogo
libMesh::VectorValue< T > Class Template Reference
#include <exact_error_estimator.h>
Public Types
typedef T value_type
Public Member Functions
VectorValue ()
VectorValue (const T x, const T y=0, const T z=0)
template<typename Scalar1 , typename Scalar2 , typename Scalar3 >
VectorValue (typename boostcopy::enable_if_c< ScalarTraits< Scalar1 >::value, const Scalar1 >::type x, typename boostcopy::enable_if_c< ScalarTraits< Scalar2 >::value, const Scalar2 >::type y=0, typename boostcopy::enable_if_c< ScalarTraits< Scalar3 >::value, const Scalar3 >::type z=0)
template<typename Scalar >
VectorValue (const Scalar x, typename boostcopy::enable_if_c< ScalarTraits< Scalar >::value, const Scalar >::type *sfinae=libmesh_nullptr)
template<typename T2 >
VectorValue (const VectorValue< T2 > &p)
template<typename T2 >
VectorValue (const TypeVector< T2 > &p)
VectorValue (const TypeVector< Real > &p_re, const TypeVector< Real > &p_im)
template<typename Scalar >
boostcopy::enable_if_c< ScalarTraits< Scalar >::value, VectorValue & >::type operator= (const Scalar &libmesh_dbg_var(p))
template<typename T2 >
void assign (const TypeVector< T2 > &)
const T & operator() (const unsigned int i) const
T & operator() (const unsigned int i)
const T & slice (const unsigned int i) const
T & slice (const unsigned int i)
template<typename T2 >
TypeVector< typename CompareTypes< T, T2 >::supertype > operator+ (const TypeVector< T2 > &) const
template<typename T2 >
const TypeVector< T > & operator+= (const TypeVector< T2 > &)
template<typename T2 >
void add (const TypeVector< T2 > &)
template<typename T2 >
void add_scaled (const TypeVector< T2 > &, const T)
template<typename T2 >
TypeVector< typename CompareTypes< T, T2 >::supertype > operator- (const TypeVector< T2 > &) const
TypeVector< T > operator- () const
template<typename T2 >
const TypeVector< T > & operator-= (const TypeVector< T2 > &)
template<typename T2 >
void subtract (const TypeVector< T2 > &)
template<typename T2 >
void subtract_scaled (const TypeVector< T2 > &, const T)
template<typename Scalar >
boostcopy::enable_if_c< ScalarTraits< Scalar >::value, TypeVector< typename CompareTypes< T, Scalar >::supertype > >::type operator* (const Scalar) const
template<typename T2 >
CompareTypes< T, T2 >::supertype operator* (const TypeVector< T2 > &) const
const TypeVector< T > & operator*= (const T)
template<typename Scalar >
boostcopy::enable_if_c< ScalarTraits< Scalar >::value, TypeVector< typename CompareTypes< T, Scalar >::supertype > >::type operator/ (const Scalar) const
const TypeVector< T > & operator/= (const T)
template<typename T2 >
CompareTypes< T, T2 >::supertype contract (const TypeVector< T2 > &) const
template<typename T2 >
TypeVector< typename CompareTypes< T, T2 >::supertype > cross (const TypeVector< T2 > &v) const
TypeVector< T > unit () const
Real size () const
Real norm () const
Real size_sq () const
Real norm_sq () const
void zero ()
bool relative_fuzzy_equals (const TypeVector< T > &rhs, Real tol=TOLERANCE) const
bool absolute_fuzzy_equals (const TypeVector< T > &rhs, Real tol=TOLERANCE) const
bool operator== (const TypeVector< T > &rhs) const
bool operator!= (const TypeVector< T > &rhs) const
bool operator< (const TypeVector< T > &rhs) const
template<>
bool operator< (const TypeVector< Complex > &rhs) const
bool operator<= (const TypeVector< T > &rhs) const
template<>
bool operator<= (const TypeVector< Complex > &rhs) const
bool operator> (const TypeVector< T > &rhs) const
template<>
bool operator> (const TypeVector< Complex > &rhs) const
bool operator>= (const TypeVector< T > &rhs) const
template<>
bool operator>= (const TypeVector< Complex > &rhs) const
void print (std::ostream &os=libMesh::out) const
void write_unformatted (std::ostream &out, const bool newline=true) const
Protected Attributes
T _coords [LIBMESH_DIM]
Detailed Description
template<typename T>
class libMesh::VectorValue< T >
This class defines a vector in LIBMESH_DIM dimensional Real or Complex space. The typedef RealVectorValue always defines a real-valued vector, and NumberVectorValue defines a real or complex-valued vector depending on how the library was configured.
Author
Benjamin S. Kirk
Date
2003
Definition at line 48 of file exact_error_estimator.h.
Member Typedef Documentation
template<typename T> typedef T libMesh::TypeVector< T >::value_type inherited
Helper typedef for C++98 generic programming
Definition at line 107 of file type_vector.h.
Constructor & Destructor Documentation
template<typename T > libMesh::VectorValue< T >::VectorValue () inline
Empty constructor. Gives the vector 0 in LIBMESH_DIM dimensional T space.
Definition at line 139 of file vector_value.h.
                              :
   TypeVector<T> ()
 {
 }
template<typename T> libMesh::VectorValue< T >::VectorValue (const T x, const T y = 0, const T z = 0) inline
Constructor-from-T. By default sets higher dimensional entries to 0.
Definition at line 147 of file vector_value.h.
                                         :
   TypeVector<T> (x,y,z)
 {
 }
template<typename T > template<typename Scalar1 , typename Scalar2 , typename Scalar3 > libMesh::VectorValue< T >::VectorValue (typename boostcopy::enable_if_c< ScalarTraits< Scalar1 >::value, const Scalar1 >::type x, typename boostcopy::enable_if_c< ScalarTraits< Scalar2 >::value, const Scalar2 >::type y = 0, typename boostcopy::enable_if_c< ScalarTraits< Scalar3 >::value, const Scalar3 >::type z = 0) inline
Constructor-from-scalars. By default sets higher dimensional entries to 0.
Definition at line 159 of file vector_value.h.
                                                    :
   TypeVector<T> (x,y,z)
 {
 }
template<typename T > template<typename Scalar > libMesh::VectorValue< T >::VectorValue (const Scalar x, typename boostcopy::enable_if_c< ScalarTraits< Scalar >::value, const Scalar >::type * sfinae = libmesh_nullptr) inline
Constructor-from-scalar. Sets higher dimensional entries to 0. Necessary because for some reason the constructor-from-scalars alone is insufficient to let the compiler figure out VectorValue<Complex> v = 0;
Definition at line 176 of file vector_value.h.
                                                     :
   TypeVector<T> (x)
 {
 }
template<typename T > template<typename T2 > libMesh::VectorValue< T >::VectorValue (const VectorValue< T2 > & p) inline
Copy-constructor.
Definition at line 187 of file vector_value.h.
                                                       :
   TypeVector<T> (p)
 {
 }
template<typename T > template<typename T2 > libMesh::VectorValue< T >::VectorValue (const TypeVector< T2 > & p) inline
Copy-constructor.
Definition at line 197 of file vector_value.h.
                                                      :
   TypeVector<T> (p)
 {
 }
template<typename T> libMesh::VectorValue< T >::VectorValue (const TypeVector< Real > & p_re, const TypeVector< Real > & p_im) inline
Constructor that takes two TypeVector<Real> representing the real and imaginary part as arguments.
Definition at line 205 of file vector_value.h.
                                                             :
   TypeVector<T> (Complex (p_re(0), p_im(0)),
                  Complex (p_re(1), p_im(1)),
                  Complex (p_re(2), p_im(2)))
 {
 }
Member Function Documentation
template<typename T> bool libMesh::TypeVector< T >::absolute_fuzzy_equals (const TypeVector< T > & rhs, Real tol = TOLERANCE) const inline inherited
Returns
true if two vectors are equal to within an absolute tolerance of tol.
Definition at line 962 of file type_vector.h.
References libMesh::TypeVector< T >::_coords, and std::abs().
Referenced by libMesh::FEGenericBase< OutputType >::compute_periodic_constraints(), libMesh::LocationMap< T >::find(), libMesh::Elem::parent_bracketing_nodes(), libMesh::TypeVector< T >::relative_fuzzy_equals(), libMesh::TypeVector< Real >::slice(), and libMesh::ReplicatedMesh::stitching_helper().
 {
 #if LIBMESH_DIM == 1
   return (std::abs(_coords[0] - rhs._coords[0])
           <= tol);
 #endif
 #if LIBMESH_DIM == 2
   return (std::abs(_coords[0] - rhs._coords[0]) +
           std::abs(_coords[1] - rhs._coords[1])
           <= tol);
 #endif
 #if LIBMESH_DIM == 3
   return (std::abs(_coords[0] - rhs._coords[0]) +
           std::abs(_coords[1] - rhs._coords[1]) +
           std::abs(_coords[2] - rhs._coords[2])
           <= tol);
 #endif
 }
template<typename T > template<typename T2 > void libMesh::TypeVector< T >::add (const TypeVector< T2 > & p) inline inherited
Add to this vector without creating a temporary.
Definition at line 600 of file type_vector.h.
References libMesh::TypeVector< T >::_coords.
Referenced by libMesh::Elem::centroid(), libMesh::FE< Dim, T >::inverse_map(), libMesh::InfFE< Dim, T_radial, T_map >::inverse_map(), libMesh::TypeVector< T >::operator+=(), libMesh::TypeVector< Real >::slice(), libMesh::LaplaceMeshSmoother::smooth(), and libMesh::MeshTools::Modification::smooth().
 {
 #if LIBMESH_DIM == 1
   _coords[0] += p._coords[0];
 #endif
 #if LIBMESH_DIM == 2
   _coords[0] += p._coords[0];
   _coords[1] += p._coords[1];
 #endif
 #if LIBMESH_DIM == 3
   _coords[0] += p._coords[0];
   _coords[1] += p._coords[1];
   _coords[2] += p._coords[2];
 #endif
 }
template<typename T> template<typename T2 > void libMesh::TypeVector< T >::add_scaled (const TypeVector< T2 > & p, const T factor) inline inherited
Add a scaled value to this vector without creating a temporary.
Definition at line 624 of file type_vector.h.
References libMesh::TypeVector< T >::_coords.
Referenced by libMesh::MeshRefinement::add_node(), libMesh::HPCoarsenTest::add_projection(), libMesh::System::calculate_norm(), libMesh::Elem::coarsen(), libMesh::MeshFunction::discontinuous_gradient(), libMesh::MeshFunction::gradient(), libMesh::InfFE< Dim, T_radial, T_map >::inverse_map(), libMesh::InfFE< Dim, T_radial, T_map >::map(), libMesh::FE< Dim, T >::map(), libMesh::FE< Dim, T >::map_eta(), libMesh::FE< Dim, T >::map_xi(), libMesh::FE< Dim, T >::map_zeta(), libMesh::WeightedPatchRecoveryErrorEstimator::EstimateError::operator()(), libMesh::PatchRecoveryErrorEstimator::EstimateError::operator()(), libMesh::Elem::parent_bracketing_nodes(), libMesh::System::point_gradient(), libMesh::HPCoarsenTest::select_refinement(), libMesh::TypeVector< Real >::slice(), and libMesh::MeshTools::Modification::smooth().
 {
 #if LIBMESH_DIM == 1
   _coords[0] += factor*p(0);
 #endif
 #if LIBMESH_DIM == 2
   _coords[0] += factor*p(0);
   _coords[1] += factor*p(1);
 #endif
 #if LIBMESH_DIM == 3
   _coords[0] += factor*p(0);
   _coords[1] += factor*p(1);
   _coords[2] += factor*p(2);
 #endif
 }
template<typename T > template<typename T2 > void libMesh::TypeVector< T >::assign (const TypeVector< T2 > & p) inline inherited
Assign to this vector without creating a temporary.
Definition at line 529 of file type_vector.h.
References libMesh::TypeVector< T >::_coords.
 {
   for (unsigned int i=0; i<LIBMESH_DIM; i++)
     _coords[i] = p._coords[i];
 }
template<typename T > template<typename T2 > CompareTypes< T, T2 >::supertype libMesh::TypeVector< T >::contract (const TypeVector< T2 > & p) const inline inherited
Returns
The result of TypeVector::operator*().
Definition at line 869 of file type_vector.h.
Referenced by libMesh::TypeVector< Real >::slice().
 {
   return (*this)*(p);
 }
template<typename T > template<typename T2 > TypeVector< typename CompareTypes< T, T2 >::supertype > libMesh::TypeVector< T >::cross (const TypeVector< T2 > & v) const inherited
Returns
The cross product of this vector with v.
Definition at line 879 of file type_vector.h.
References libMesh::TypeVector< T >::_coords.
Referenced by libMesh::FEXYZMap::compute_face_map(), libMesh::FEMap::compute_face_map(), libMesh::Plane::create_from_three_points(), libMesh::TypeVector< Real >::slice(), and libMesh::Quad4::volume().
 {
   typedef typename CompareTypes<T, T2>::supertype TS;
   libmesh_assert_equal_to (LIBMESH_DIM, 3);
   // |     i          j          k    |
   // |(*this)(0) (*this)(1) (*this)(2)|
   // |   p(0)       p(1)       p(2)   |
   return TypeVector<TS>( _coords[1]*p._coords[2] - _coords[2]*p._coords[1],
                          -_coords[0]*p._coords[2] + _coords[2]*p._coords[0],
                          _coords[0]*p._coords[1] - _coords[1]*p._coords[0]);
 }
template<typename T > Real libMesh::TypeVector< T >::norm () const inline inherited
Returns
The magnitude of the vector, i.e. the square-root of the sum of the elements squared.
Definition at line 909 of file type_vector.h.
References libMesh::TypeVector< T >::norm_sq().
Referenced by libMesh::Sphere::above_surface(), libMesh::InfElemBuilder::build_inf_elem(), libMesh::System::calculate_norm(), libMesh::InfPrism::contains_point(), libMesh::InfHex::contains_point(), libMesh::FE< Dim, T >::inverse_map(), libMesh::InfFE< Dim, T_radial, T_map >::inverse_map(), libMesh::Tri3::min_and_max_angle(), libMesh::Tet4::min_and_max_angle(), libMesh::Sphere::on_surface(), libMesh::Tri::quality(), libMesh::TypeVector< T >::size(), libMesh::TypeVector< Real >::slice(), libMesh::MeshTools::Modification::smooth(), and libMesh::Sphere::surface_coords().
 {
   return std::sqrt(this->norm_sq());
 }
template<typename T > Real libMesh::TypeVector< T >::norm_sq () const inline inherited
Returns
The magnitude of the vector squared, i.e. the sum of the element magnitudes squared.
Definition at line 940 of file type_vector.h.
References libMesh::TypeVector< T >::_coords, and libMesh::TensorTools::norm_sq().
Referenced by libMesh::ExactSolution::_compute_error(), libMesh::UniformRefinementEstimator::_estimate_error(), libMesh::System::calculate_norm(), libMesh::InfQuad4::contains_point(), libMesh::InfPrism::contains_point(), libMesh::InfHex::contains_point(), libMesh::ExactErrorEstimator::find_squared_element_error(), libMesh::Elem::hmax(), libMesh::Elem::hmin(), libMesh::TypeVector< T >::norm(), libMesh::TensorTools::norm_sq(), libMesh::HPCoarsenTest::select_refinement(), libMesh::TypeVector< T >::size_sq(), libMesh::TypeVector< Real >::slice(), libMesh::Sphere::Sphere(), and libMesh::Edge3::volume().
 {
 #if LIBMESH_DIM == 1
   return (TensorTools::norm_sq(_coords[0]));
 #endif
 #if LIBMESH_DIM == 2
   return (TensorTools::norm_sq(_coords[0]) +
           TensorTools::norm_sq(_coords[1]));
 #endif
 #if LIBMESH_DIM == 3
   return (TensorTools::norm_sq(_coords[0]) +
           TensorTools::norm_sq(_coords[1]) +
           TensorTools::norm_sq(_coords[2]));
 #endif
 }
template<typename T> bool libMesh::TypeVector< T >::operator!= (const TypeVector< T > & rhs) const inline inherited
Returns
!(*this == rhs)
Definition at line 1034 of file type_vector.h.
Referenced by libMesh::TypeVector< Real >::slice().
 {
   return (!(*this == rhs));
 }
template<typename T > const T & libMesh::TypeVector< T >::operator() (const unsigned int i) const inline inherited
Returns
A const reference to the entry of the vector.
Definition at line 539 of file type_vector.h.
References libMesh::TypeVector< T >::_coords.
Referenced by libMesh::TypeVector< Real >::operator=(), and libMesh::TypeVector< Real >::slice().
 {
   libmesh_assert_less (i, LIBMESH_DIM);
   return _coords[i];
 }
template<typename T > T & libMesh::TypeVector< T >::operator() (const unsigned int i) inline inherited
Returns
A writable reference to the entry of the vector.
Definition at line 550 of file type_vector.h.
References libMesh::TypeVector< T >::_coords.
 {
   libmesh_assert_less (i, LIBMESH_DIM);
   return _coords[i];
 }
template<typename T > template<typename Scalar > boostcopy::enable_if_c< ScalarTraits< Scalar >::value, TypeVector< typename CompareTypes< T, Scalar >::supertype > >::type libMesh::TypeVector< T >::operator* (const Scalar factor) const inline inherited
Multiply this vector by a scalar value.
Returns
A copy of the result, this vector is unchanged.
Definition at line 736 of file type_vector.h.
References libMesh::TypeVector< T >::_coords.
Referenced by libMesh::TypeVector< Real >::slice().
 {
   typedef typename CompareTypes<T, Scalar>::supertype SuperType;
 #if LIBMESH_DIM == 1
   return TypeVector<SuperType>(_coords[0]*factor);
 #endif
 #if LIBMESH_DIM == 2
   return TypeVector<SuperType>(_coords[0]*factor,
                                _coords[1]*factor);
 #endif
 #if LIBMESH_DIM == 3
   return TypeVector<SuperType>(_coords[0]*factor,
                                _coords[1]*factor,
                                _coords[2]*factor);
 #endif
 }
template<typename T > template<typename T2 > CompareTypes< T, T2 >::supertype libMesh::TypeVector< T >::operator* (const TypeVector< T2 > & p) const inline inherited
Returns
The dot-product of this vector with another vector.
Note
The complex conjugate is not taken in the complex-valued case.
The vectors may contain different numeric types.
Definition at line 847 of file type_vector.h.
References libMesh::TypeVector< T >::_coords.
 {
 #if LIBMESH_DIM == 1
   return _coords[0]*p._coords[0];
 #endif
 #if LIBMESH_DIM == 2
   return (_coords[0]*p._coords[0] +
           _coords[1]*p._coords[1]);
 #endif
 #if LIBMESH_DIM == 3
   return (_coords[0]*p(0) +
           _coords[1]*p(1) +
           _coords[2]*p(2));
 #endif
 }
template<typename T> const TypeVector< T > & libMesh::TypeVector< T >::operator*= (const T factor) inline inherited
Multiply this vector by a scalar value.
Returns
A reference to *this.
Definition at line 773 of file type_vector.h.
References libMesh::TypeVector< T >::_coords.
Referenced by libMesh::TypeVector< Real >::slice().
 {
 #if LIBMESH_DIM == 1
   _coords[0] *= factor;
 #endif
 #if LIBMESH_DIM == 2
   _coords[0] *= factor;
   _coords[1] *= factor;
 #endif
 #if LIBMESH_DIM == 3
   _coords[0] *= factor;
   _coords[1] *= factor;
   _coords[2] *= factor;
 #endif
   return *this;
 }
template<typename T > template<typename T2 > TypeVector< typename CompareTypes< T, T2 >::supertype > libMesh::TypeVector< T >::operator+ (const TypeVector< T2 > & p) const inline inherited
Add two vectors.
Returns
A copy of the result, this vector is unchanged.
Definition at line 563 of file type_vector.h.
References libMesh::TypeVector< T >::_coords.
Referenced by libMesh::TypeVector< Real >::slice().
 {
   typedef typename CompareTypes<T, T2>::supertype TS;
 #if LIBMESH_DIM == 1
   return TypeVector<TS> (_coords[0] + p._coords[0]);
 #endif
 #if LIBMESH_DIM == 2
   return TypeVector<TS> (_coords[0] + p._coords[0],
                          _coords[1] + p._coords[1]);
 #endif
 #if LIBMESH_DIM == 3
   return TypeVector<TS> (_coords[0] + p._coords[0],
                          _coords[1] + p._coords[1],
                          _coords[2] + p._coords[2]);
 #endif
 }
template<typename T > template<typename T2 > const TypeVector< T > & libMesh::TypeVector< T >::operator+= (const TypeVector< T2 > & p) inline inherited
Add to this vector.
Returns
A reference to *this.
Definition at line 588 of file type_vector.h.
References libMesh::TypeVector< T >::add().
Referenced by libMesh::TypeVector< Real >::slice().
 {
   this->add (p);
   return *this;
 }
template<typename T > template<typename T2 > TypeVector< typename CompareTypes< T, T2 >::supertype > libMesh::TypeVector< T >::operator- (const TypeVector< T2 > & p) const inline inherited
Subtract from this vector.
Returns
A copy of the result, this vector is unchanged.
Definition at line 649 of file type_vector.h.
References libMesh::TypeVector< T >::_coords.
 {
   typedef typename CompareTypes<T, T2>::supertype TS;
 #if LIBMESH_DIM == 1
   return TypeVector<TS>(_coords[0] - p._coords[0]);
 #endif
 #if LIBMESH_DIM == 2
   return TypeVector<TS>(_coords[0] - p._coords[0],
                         _coords[1] - p._coords[1]);
 #endif
 #if LIBMESH_DIM == 3
   return TypeVector<TS>(_coords[0] - p._coords[0],
                         _coords[1] - p._coords[1],
                         _coords[2] - p._coords[2]);
 #endif
 }
template<typename T > TypeVector< T > libMesh::TypeVector< T >::operator- () const inline inherited
Returns
The negative of this vector in a separate copy.
Definition at line 708 of file type_vector.h.
References libMesh::TypeVector< T >::_coords, and libMesh::TypeVector< T >::TypeVector().
Referenced by libMesh::TypeVector< Real >::slice().
 {
 #if LIBMESH_DIM == 1
   return TypeVector(-_coords[0]);
 #endif
 #if LIBMESH_DIM == 2
   return TypeVector(-_coords[0],
                     -_coords[1]);
 #endif
 #if LIBMESH_DIM == 3
   return TypeVector(-_coords[0],
                     -_coords[1],
                     -_coords[2]);
 #endif
 }
template<typename T > template<typename T2 > const TypeVector< T > & libMesh::TypeVector< T >::operator-= (const TypeVector< T2 > & p) inline inherited
Subtract from this vector.
Returns
A reference to *this.
Definition at line 675 of file type_vector.h.
References libMesh::TypeVector< T >::subtract().
Referenced by libMesh::TypeVector< Real >::slice().
 {
   this->subtract (p);
   return *this;
 }
template<typename T > template<typename Scalar > boostcopy::enable_if_c< ScalarTraits< Scalar >::value, TypeVector< typename CompareTypes< T, Scalar >::supertype > >::type libMesh::TypeVector< T >::operator/ (const Scalar factor) const inline inherited
Divide each entry of this vector by scalar value.
Returns
A copy of the result, this vector is unchanged.
Definition at line 801 of file type_vector.h.
References libMesh::TypeVector< T >::_coords.
Referenced by libMesh::TypeVector< Real >::slice().
 {
   libmesh_assert_not_equal_to (factor, static_cast<T>(0.));
   typedef typename CompareTypes<T, Scalar>::supertype TS;
 #if LIBMESH_DIM == 1
   return TypeVector<TS>(_coords[0]/factor);
 #endif
 #if LIBMESH_DIM == 2
   return TypeVector<TS>(_coords[0]/factor,
                         _coords[1]/factor);
 #endif
 #if LIBMESH_DIM == 3
   return TypeVector<TS>(_coords[0]/factor,
                         _coords[1]/factor,
                         _coords[2]/factor);
 #endif
 }
template<typename T> const TypeVector< T > & libMesh::TypeVector< T >::operator/= (const T factor) inline inherited
Divide each entry of this vector by scalar value.
Returns
A reference to *this.
Definition at line 830 of file type_vector.h.
References libMesh::TypeVector< T >::_coords.
Referenced by libMesh::TypeVector< Real >::slice().
 {
   libmesh_assert_not_equal_to (factor, static_cast<T>(0.));
   for (unsigned int i=0; i<LIBMESH_DIM; i++)
     _coords[i] /= factor;
   return *this;
 }
template<> bool libMesh::TypeVector< Complex >::operator< (const TypeVector< Complex > & rhs) const inherited
Definition at line 167 of file type_vector.C.
 {
   for (unsigned int i=0; i<LIBMESH_DIM; i++)
     {
       if ((*this)(i).real() < rhs(i).real())
         return true;
       if ((*this)(i).real() > rhs(i).real())
         return false;
       if ((*this)(i).imag() < rhs(i).imag())
         return true;
       if ((*this)(i).imag() > rhs(i).imag())
         return false;
     }
   return false;
 }
template<typename T> bool libMesh::TypeVector< T >::operator< (const TypeVector< T > & rhs) const inherited
Returns
true if this vector is "less" than rhs.
Useful for sorting. Also used for choosing some arbitrary basis function orientations.
Definition at line 109 of file type_vector.C.
 {
   for (unsigned int i=0; i<LIBMESH_DIM; i++)
     {
       if ((*this)(i) < rhs(i))
         return true;
       if ((*this)(i) > rhs(i))
         return false;
     }
   return false;
 }
template<> bool libMesh::TypeVector< Complex >::operator<= (const TypeVector< Complex > & rhs) const inherited
Definition at line 186 of file type_vector.C.
 {
   for (unsigned int i=0; i<LIBMESH_DIM; i++)
     {
       if ((*this)(i).real() < rhs(i).real())
         return true;
       if ((*this)(i).real() > rhs(i).real())
         return false;
       if ((*this)(i).imag() < rhs(i).imag())
         return true;
       if ((*this)(i).imag() > rhs(i).imag())
         return false;
     }
   return true;
 }
template<typename T> bool libMesh::TypeVector< T >::operator<= (const TypeVector< T > & rhs) const inherited
Returns
true if this vector is <= to rhs.
Useful for sorting. Also used for choosing some arbitrary constraint equation directions.
Definition at line 123 of file type_vector.C.
 {
   for (unsigned int i=0; i<LIBMESH_DIM; i++)
     {
       if ((*this)(i) < rhs(i))
         return true;
       if ((*this)(i) > rhs(i))
         return false;
     }
   return true;
 }
template<typename T> template<typename Scalar > boostcopy::enable_if_c< ScalarTraits<Scalar>::value, VectorValue &>::type libMesh::VectorValue< T >::operator= (const Scalar & libmesh_dbg_varp) inline
Assignment-from-scalar operator. Used only to zero out vectors.
Definition at line 117 of file vector_value.h.
   { libmesh_assert_equal_to (p, Scalar(0)); this->zero(); return *this; }
template<typename T> bool libMesh::TypeVector< T >::operator== (const TypeVector< T > & rhs) const inline inherited
Returns
true if this(i)==rhs(i) for each component of the vector.
Note
For floating point types T, the function absolute_fuzzy_equals() may be a more appropriate choice.
Definition at line 1012 of file type_vector.h.
References libMesh::TypeVector< T >::_coords.
Referenced by libMesh::TypeVector< Real >::slice().
 {
 #if LIBMESH_DIM == 1
   return (_coords[0] == rhs._coords[0]);
 #endif
 #if LIBMESH_DIM == 2
   return (_coords[0] == rhs._coords[0] &&
           _coords[1] == rhs._coords[1]);
 #endif
 #if LIBMESH_DIM == 3
   return (_coords[0] == rhs._coords[0] &&
           _coords[1] == rhs._coords[1] &&
           _coords[2] == rhs._coords[2]);
 #endif
 }
template<> bool libMesh::TypeVector< Complex >::operator> (const TypeVector< Complex > & rhs) const inherited
Definition at line 205 of file type_vector.C.
 {
   for (unsigned int i=0; i<LIBMESH_DIM; i++)
     {
       if ((*this)(i).real() > rhs(i).real())
         return true;
       if ((*this)(i).real() < rhs(i).real())
         return false;
       if ((*this)(i).imag() > rhs(i).imag())
         return true;
       if ((*this)(i).imag() < rhs(i).imag())
         return false;
     }
   return false;
 }
template<typename T> bool libMesh::TypeVector< T >::operator> (const TypeVector< T > & rhs) const inherited
Returns
true if this vector is "greater" than rhs.
Useful for sorting. Also used for choosing some arbitrary basis function orientations.
Definition at line 138 of file type_vector.C.
Referenced by libMesh::TypeVector< Real >::slice().
 {
   for (unsigned int i=0; i<LIBMESH_DIM; i++)
     {
       if ((*this)(i) > rhs(i))
         return true;
       if ((*this)(i) < rhs(i))
         return false;
     }
   return false;
 }
template<> bool libMesh::TypeVector< Complex >::operator>= (const TypeVector< Complex > & rhs) const inherited
Definition at line 224 of file type_vector.C.
 {
   for (unsigned int i=0; i<LIBMESH_DIM; i++)
     {
       if ((*this)(i).real() > rhs(i).real())
         return true;
       if ((*this)(i).real() < rhs(i).real())
         return false;
       if ((*this)(i).imag() > rhs(i).imag())
         return true;
       if ((*this)(i).imag() < rhs(i).imag())
         return false;
     }
   return true;
 }
template<typename T> bool libMesh::TypeVector< T >::operator>= (const TypeVector< T > & rhs) const inherited
Returns
true if this vector is >= rhs.
Useful for sorting. Also used for choosing some arbitrary constraint equation directions.
Definition at line 152 of file type_vector.C.
Referenced by libMesh::TypeVector< Real >::slice().
 {
   for (unsigned int i=0; i<LIBMESH_DIM; i++)
     {
       if ((*this)(i) > rhs(i))
         return true;
       if ((*this)(i) < rhs(i))
         return false;
     }
   return true;
 }
template<typename T > void libMesh::TypeVector< T >::print (std::ostream & os = libMesh::out) const inherited
Formatted print, by default to libMesh::out.
Definition at line 64 of file type_vector.C.
Referenced by libMesh::TypeVector< Real >::slice().
 {
 #if LIBMESH_DIM == 1
   os << "x=" << (*this)(0);
 #endif
 #if LIBMESH_DIM == 2
   os << "(x,y)=("
      << std::setw(8) << (*this)(0) << ", "
      << std::setw(8) << (*this)(1) << ")";
 #endif
 #if LIBMESH_DIM == 3
   os <<  "(x,y,z)=("
      << std::setw(8) << (*this)(0) << ", "
      << std::setw(8) << (*this)(1) << ", "
      << std::setw(8) << (*this)(2) << ")";
 #endif
 }
template<typename T> bool libMesh::TypeVector< T >::relative_fuzzy_equals (const TypeVector< T > & rhs, Real tol = TOLERANCE) const inline inherited
Returns
true if two vectors are equal to within a relative tolerance of tol.
Definition at line 987 of file type_vector.h.
References libMesh::TypeVector< T >::_coords, std::abs(), and libMesh::TypeVector< T >::absolute_fuzzy_equals().
Referenced by libMesh::Quad4::has_affine_map(), libMesh::Prism6::has_affine_map(), libMesh::Quad9::has_affine_map(), libMesh::Quad8::has_affine_map(), libMesh::Hex8::has_affine_map(), libMesh::Hex27::has_affine_map(), libMesh::Hex20::has_affine_map(), libMesh::Prism18::has_affine_map(), libMesh::Prism15::has_affine_map(), libMesh::TypeVector< Real >::slice(), libMesh::Quad4::volume(), and libMesh::Tri6::volume().
 {
 #if LIBMESH_DIM == 1
   return this->absolute_fuzzy_equals(rhs, tol *
                                      (std::abs(_coords[0]) + std::abs(rhs._coords[0])));
 #endif
 #if LIBMESH_DIM == 2
   return this->absolute_fuzzy_equals(rhs, tol *
                                      (std::abs(_coords[0]) + std::abs(rhs._coords[0]) +
                                       std::abs(_coords[1]) + std::abs(rhs._coords[1])));
 #endif
 #if LIBMESH_DIM == 3
   return this->absolute_fuzzy_equals(rhs, tol *
                                      (std::abs(_coords[0]) + std::abs(rhs._coords[0]) +
                                       std::abs(_coords[1]) + std::abs(rhs._coords[1]) +
                                       std::abs(_coords[2]) + std::abs(rhs._coords[2])));
 #endif
 }
template<typename T > Real libMesh::TypeVector< T >::size () const inline inherited
Returns
The magnitude of the vector, i.e. the square-root of the sum of the elements squared.
Deprecated:
Use the norm() function instead.
Definition at line 898 of file type_vector.h.
References libMesh::TypeVector< T >::norm().
Referenced by libMesh::DofMap::allgather_recursive_constraints(), libMesh::DofMap::get_info(), libMesh::FEInterface::inverse_map(), libMesh::FE< Dim, T >::inverse_map(), libMesh::InfFE< Dim, T_radial, T_map >::inverse_map(), libMesh::DofMap::old_dof_indices(), libMesh::DofMap::scatter_constraints(), and libMesh::TypeVector< Real >::slice().
 {
   libmesh_deprecated();
   return this->norm();
 }
template<typename T > Real libMesh::TypeVector< T >::size_sq () const inline inherited
Returns
The magnitude of the vector squared, i.e. the sum of the element magnitudes squared.
Deprecated:
Use the norm_sq() function instead.
Definition at line 929 of file type_vector.h.
References libMesh::TypeVector< T >::norm_sq().
Referenced by libMesh::TypeVector< Real >::slice().
 {
   libmesh_deprecated();
   return this->norm_sq();
 }
template<typename T> const T& libMesh::TypeVector< T >::slice (const unsigned int i) const inline inherited
Definition at line 140 of file type_vector.h.
 { return (*this)(i); }
template<typename T> T& libMesh::TypeVector< T >::slice (const unsigned int i) inline inherited
Definition at line 146 of file type_vector.h.
 { return (*this)(i); }
template<typename T > template<typename T2 > void libMesh::TypeVector< T >::subtract (const TypeVector< T2 > & p) inline inherited
Subtract from this vector without creating a temporary.
Definition at line 687 of file type_vector.h.
References libMesh::TypeVector< T >::_coords.
Referenced by libMesh::TypeVector< T >::operator-=(), and libMesh::TypeVector< Real >::slice().
 {
   for (unsigned int i=0; i<LIBMESH_DIM; i++)
     _coords[i] -= p._coords[i];
 }
template<typename T> template<typename T2 > void libMesh::TypeVector< T >::subtract_scaled (const TypeVector< T2 > & p, const T factor) inline inherited
Subtract a scaled value from this vector without creating a temporary.
Definition at line 698 of file type_vector.h.
References libMesh::TypeVector< T >::_coords.
Referenced by libMesh::HPCoarsenTest::select_refinement(), and libMesh::TypeVector< Real >::slice().
 {
   for (unsigned int i=0; i<LIBMESH_DIM; i++)
     _coords[i] -= factor*p(i);
 }
template<typename T > TypeVector< T > libMesh::TypeVector< T >::unit () const inherited
Returns
A unit vector in the direction of *this.
Definition at line 37 of file type_vector.C.
References libMesh::Real.
Referenced by libMesh::FEXYZMap::compute_face_map(), libMesh::FEMap::compute_face_map(), libMesh::Plane::create_from_point_normal(), libMesh::Plane::create_from_three_points(), libMesh::MeshTools::Modification::distort(), libMesh::TypeVector< Real >::slice(), and libMesh::Sphere::unit_normal().
 {
   const Real length = norm();
   libmesh_assert_not_equal_to (length, static_cast<Real>(0.));
 #if LIBMESH_DIM == 1
   return TypeVector<T>(_coords[0]/length);
 #endif
 #if LIBMESH_DIM == 2
   return TypeVector<T>(_coords[0]/length,
                        _coords[1]/length);
 #endif
 #if LIBMESH_DIM == 3
   return TypeVector<T>(_coords[0]/length,
                        _coords[1]/length,
                        _coords[2]/length);
 #endif
 }
template<typename T > void libMesh::TypeVector< T >::write_unformatted (std::ostream & out, const bool newline = true) const inherited
Unformatted print to the stream out. Simply prints the elements of the vector separated by spaces. Also prints a newline by default, however, this behavior can be controlled with the newline parameter.
Definition at line 92 of file type_vector.C.
Referenced by libMesh::InfElemBuilder::build_inf_elem(), and libMesh::TecplotIO::write_ascii().
 {
   libmesh_assert (os);
   os << std::setiosflags(std::ios::showpoint)
      << (*this)(0) << " "
      << (*this)(1) << " "
      << (*this)(2) << " ";
   if (newline)
     os << '\n';
 }
template<typename T > void libMesh::TypeVector< T >::zero () inline inherited
Set all entries of the vector to 0.
Definition at line 918 of file type_vector.h.
References libMesh::TypeVector< T >::_coords.
Referenced by libMesh::VectorValue< Real >::operator=(), libMesh::TypeVector< Real >::operator=(), and libMesh::TypeVector< Real >::slice().
 {
   for (unsigned int i=0; i<LIBMESH_DIM; i++)
     _coords[i] = 0.;
 }
Member Data Documentation
template<typename T> T libMesh::TypeVector< T >::_coords[LIBMESH_DIM] protected inherited
The coordinates of the TypeVector.
Definition at line 406 of file type_vector.h.
Referenced by libMesh::TypeVector< T >::absolute_fuzzy_equals(), libMesh::TypeVector< T >::add(), libMesh::TypeVector< T >::add_scaled(), libMesh::TypeVector< T >::assign(), libMesh::TypeVector< T >::cross(), libMesh::TypeVector< T >::norm_sq(), libMesh::TypeVector< T >::operator()(), libMesh::TypeVector< T >::operator*(), libMesh::TypeVector< T >::operator*=(), libMesh::TypeVector< T >::operator+(), libMesh::TypeVector< T >::operator-(), libMesh::TypeVector< T >::operator/(), libMesh::TypeVector< T >::operator/=(), libMesh::TypeVector< T >::operator==(), libMesh::TypeVector< T >::relative_fuzzy_equals(), libMesh::TypeTensor< T >::row(), libMesh::TypeVector< T >::subtract(), libMesh::TypeVector< T >::subtract_scaled(), libMesh::TypeVector< T >::TypeVector(), and libMesh::TypeVector< T >::zero().
The documentation for this class was generated from the following files:
exact_error_estimator.h
vector_value.h