libMesh: libMesh::ConstFEMFunction< Output > Class Template Reference
SomeWebsiteLogo
libMesh::ConstFEMFunction< Output > Class Template Reference
FEMFunction that returns a single value.
#include <const_fem_function.h>
Public Member Functions
ConstFEMFunction (const Output c)
~ConstFEMFunction ()
virtual UniquePtr< FEMFunctionBase< Output > > clone () const
virtual Output operator() (const FEMContext &, const Point &, const Real=0.)
virtual void operator() (const FEMContext &, const Point &, const Real, DenseVector< Output > &output)
virtual void init_context (const FEMContext &)
void operator() (const FEMContext &, const Point &p, DenseVector< Output > &output)
virtual Output component (const FEMContext &, unsigned int i, const Point &p, Real time=0.)
Private Attributes
Output _c
Detailed Description
template<typename Output = Number>
class libMesh::ConstFEMFunction< Output >
FEMFunction that returns a single value.
FEMFunction that returns a single value, regardless of the time and location inputs.
Author
Roy Stogner
Date
2012
Definition at line 41 of file const_fem_function.h.
Constructor & Destructor Documentation
template<typename Output = Number> libMesh::ConstFEMFunction< Output >::ConstFEMFunction (const Output c) inline
Definition at line 44 of file const_fem_function.h.
Referenced by libMesh::ConstFEMFunction< Output >::clone().
 : _c(c) {}
template<typename Output = Number> libMesh::ConstFEMFunction< Output >::~ConstFEMFunction () inline
Definition at line 46 of file const_fem_function.h.
 {}
Member Function Documentation
template<typename Output = Number> virtual UniquePtr<FEMFunctionBase<Output> > libMesh::ConstFEMFunction< Output >::clone () const inline virtual
Returns
A new copy of the function.
The new copy should be as "deep" as necessary to allow independent destruction and simultaneous evaluations of the copies in different threads.
Implements libMesh::FEMFunctionBase< Output >.
Definition at line 48 of file const_fem_function.h.
References libMesh::ConstFEMFunction< Output >::ConstFEMFunction().
   {return UniquePtr<FEMFunctionBase<Output> >( new ConstFEMFunction(*this) ); }
template<typename Output > Output libMesh::FEMFunctionBase< Output >::component (const FEMContext & context, unsigned int i, const Point & p, Real time = 0.) inline virtual inherited
Returns
The vector component i at coordinate p and time time.
Note
Subclasses aren't required to override this, since the default implementation is based on the full vector evaluation, which is often correct.
Subclasses are recommended to override this, since the default implementation is based on a vector evaluation, which is usually unnecessarily inefficient.
Reimplemented in libMesh::CompositeFEMFunction< Output >, libMesh::ParsedFEMFunction< Output >, libMesh::ParsedFEMFunction< T >, and libMesh::WrappedFunctor< Output >.
Definition at line 131 of file fem_function_base.h.
Referenced by libMesh::FEMFunctionBase< Output >::init_context(), and libMesh::System::project_vector().
 {
   DenseVector<Output> outvec(i+1);
   (*this)(context, p, time, outvec);
   return outvec(i);
 }
template<typename Output = Number> virtual void libMesh::FEMFunctionBase< Output >::init_context (const FEMContext &) inline virtual inherited
Prepares a context object for use.
Most problems will want to reimplement this for efficiency, in order to call FE::get_*() as their particular function requires.
Reimplemented in libMesh::ParsedFEMFunction< Output >, and libMesh::ParsedFEMFunction< T >.
Definition at line 71 of file fem_function_base.h.
References libMesh::FEMFunctionBase< Output >::clone(), libMesh::FEMFunctionBase< Output >::component(), libMesh::FEMFunctionBase< Output >::operator()(), and libMesh::Real.
 {}
template<typename Output = Number> virtual Output libMesh::ConstFEMFunction< Output >::operator() (const FEMContext & , const Point & p, const Real time = 0.) inline virtual
Returns
The scalar function value at coordinate p and time time, which defaults to zero.
Pure virtual, so you have to override it.
Implements libMesh::FEMFunctionBase< Output >.
Definition at line 51 of file const_fem_function.h.
References libMesh::ConstFEMFunction< Output >::_c.
   { return _c; }
template<typename Output = Number> virtual void libMesh::ConstFEMFunction< Output >::operator() (const FEMContext & , const Point & p, const Real time, DenseVector< Output > & output) inline virtual
Evaluation function for time-dependent vector-valued functions. Sets output values in the passed-in output DenseVector.
Pure virtual, so you have to override it.
Implements libMesh::FEMFunctionBase< Output >.
Definition at line 56 of file const_fem_function.h.
References libMesh::ConstFEMFunction< Output >::_c, and libMesh::DenseVector< T >::size().
   {
     for (std::size_t i = 0; i < output.size(); i++)
       output(i) = _c;
   }
template<typename Output > void libMesh::FEMFunctionBase< Output >::operator() (const FEMContext & context, const Point & p, DenseVector< Output > & output) inline inherited
Evaluation function for time-independent vector-valued functions. Sets output values in the passed-in output DenseVector.
Definition at line 143 of file fem_function_base.h.
References libMesh::FEMFunctionBase< Output >::operator()().
 {
   // Call the time-dependent function with t=0.
   this->operator()(context, p, 0., output);
 }
Member Data Documentation
template<typename Output = Number> Output libMesh::ConstFEMFunction< Output >::_c private
Definition at line 66 of file const_fem_function.h.
Referenced by libMesh::ConstFEMFunction< Output >::operator()().
The documentation for this class was generated from the following file:
const_fem_function.h