libMesh: libMesh::Threads::spin_mutex::scoped_lock Class Reference
SomeWebsiteLogo
libMesh::Threads::spin_mutex::scoped_lock Class Reference
#include <threads_none.h>
Public Member Functions
scoped_lock ()
scoped_lock (spin_mutex &)
void acquire (spin_mutex &)
void release ()
scoped_lock ()
scoped_lock (spin_mutex &in_smutex)
~scoped_lock ()
void acquire (spin_mutex &in_smutex)
void release ()
scoped_lock ()
scoped_lock (spin_mutex &in_smutex)
~scoped_lock ()
void acquire (spin_mutex &in_smutex)
void release ()
scoped_lock ()
scoped_lock (spin_mutex &in_smutex)
~scoped_lock ()
void acquire (spin_mutex &in_smutex)
void release ()
Private Attributes
spin_mutex * smutex
Detailed Description
Definition at line 134 of file threads_none.h.
Constructor & Destructor Documentation
libMesh::Threads::spin_mutex::scoped_lock::scoped_lock () inline
Definition at line 137 of file threads_none.h.
 {}
libMesh::Threads::spin_mutex::scoped_lock::scoped_lock (spin_mutex &) inline explicit
Definition at line 138 of file threads_none.h.
 {}
libMesh::Threads::spin_mutex::scoped_lock::scoped_lock () inline
Definition at line 97 of file threads_pthread.h.
 : smutex(libmesh_nullptr) {}
libMesh::Threads::spin_mutex::scoped_lock::scoped_lock (spin_mutex & in_smutex) inline explicit
Definition at line 98 of file threads_pthread.h.
References libMesh::Threads::spin_mutex::lock(), and smutex.
 : smutex(&in_smutex) { smutex->lock(); }
libMesh::Threads::spin_mutex::scoped_lock::~scoped_lock () inline
Definition at line 100 of file threads_pthread.h.
References release().
 { release(); }
libMesh::Threads::spin_mutex::scoped_lock::scoped_lock () inline
Definition at line 125 of file threads_pthread.h.
 : smutex(libmesh_nullptr) {}
libMesh::Threads::spin_mutex::scoped_lock::scoped_lock (spin_mutex & in_smutex) inline explicit
Definition at line 126 of file threads_pthread.h.
References libMesh::Threads::spin_mutex::lock(), and smutex.
 : smutex(&in_smutex) { smutex->lock(); }
libMesh::Threads::spin_mutex::scoped_lock::~scoped_lock () inline
Definition at line 128 of file threads_pthread.h.
References release().
 { release(); }
libMesh::Threads::spin_mutex::scoped_lock::scoped_lock () inline
Definition at line 155 of file threads_pthread.h.
 : smutex(libmesh_nullptr) {}
libMesh::Threads::spin_mutex::scoped_lock::scoped_lock (spin_mutex & in_smutex) inline explicit
Definition at line 156 of file threads_pthread.h.
References libMesh::Threads::spin_mutex::lock(), and smutex.
 : smutex(&in_smutex) { smutex->lock(); }
libMesh::Threads::spin_mutex::scoped_lock::~scoped_lock () inline
Definition at line 158 of file threads_pthread.h.
References release().
 { release(); }
Member Function Documentation
void libMesh::Threads::spin_mutex::scoped_lock::acquire (spin_mutex & in_smutex) inline
Definition at line 102 of file threads_pthread.h.
References libMesh::Threads::spin_mutex::lock(), and smutex.
 { smutex = &in_smutex; smutex->lock(); }
void libMesh::Threads::spin_mutex::scoped_lock::acquire (spin_mutex & in_smutex) inline
Definition at line 130 of file threads_pthread.h.
References libMesh::Threads::spin_mutex::lock(), and smutex.
 { smutex = &in_smutex; smutex->lock(); }
void libMesh::Threads::spin_mutex::scoped_lock::acquire (spin_mutex &) inline
Definition at line 139 of file threads_none.h.
 {}
void libMesh::Threads::spin_mutex::scoped_lock::acquire (spin_mutex & in_smutex) inline
Definition at line 160 of file threads_pthread.h.
References libMesh::Threads::spin_mutex::lock(), and smutex.
 { smutex = &in_smutex; smutex->lock(); }
void libMesh::Threads::spin_mutex::scoped_lock::release () inline
Definition at line 103 of file threads_pthread.h.
References libmesh_nullptr, smutex, and libMesh::Threads::spin_mutex::unlock().
 { if (smutex) smutex->unlock(); smutex = libmesh_nullptr; }
void libMesh::Threads::spin_mutex::scoped_lock::release () inline
Definition at line 131 of file threads_pthread.h.
References libmesh_nullptr, smutex, and libMesh::Threads::spin_mutex::unlock().
 { if (smutex) smutex->unlock(); smutex = libmesh_nullptr; }
void libMesh::Threads::spin_mutex::scoped_lock::release () inline
Definition at line 140 of file threads_none.h.
Referenced by ~scoped_lock(), and libMesh::Threads::recursive_mutex::scoped_lock::~scoped_lock().
 {}
void libMesh::Threads::spin_mutex::scoped_lock::release () inline
Definition at line 161 of file threads_pthread.h.
References libmesh_nullptr, smutex, and libMesh::Threads::spin_mutex::unlock().
 { if (smutex) smutex->unlock(); smutex = libmesh_nullptr; }
Member Data Documentation
spin_mutex * libMesh::Threads::spin_mutex::scoped_lock::smutex private
Definition at line 106 of file threads_pthread.h.
Referenced by acquire(), libMesh::Threads::atomic< unsigned int >::operator++(), libMesh::Threads::atomic< unsigned int >::operator+=(), libMesh::Threads::atomic< unsigned int >::operator--(), libMesh::Threads::atomic< unsigned int >::operator-=(), libMesh::Threads::atomic< unsigned int >::operator=(), release(), and scoped_lock().
The documentation for this class was generated from the following files:
threads_none.h
threads_pthread.h