libMesh: libMesh::Parallel::DataType Class Reference
SomeWebsiteLogo
libMesh::Parallel::DataType Class Reference
#include <data_type.h>
Public Member Functions
DataType ()
DataType (const DataType &other)
DataType (const data_type &type)
DataType (const DataType &other, unsigned int count)
DataType & operator= (const DataType &other)
DataType & operator= (const data_type &type)
operator const data_type & () const
operator data_type & ()
void commit ()
void free ()
Protected Attributes
data_type _datatype
Detailed Description
Encapsulates the MPI_Datatype.
Definition at line 63 of file data_type.h.
Constructor & Destructor Documentation
DataType() [1/4]
libMesh::Parallel::DataType::DataType () inline
Definition at line 66 of file data_type.h.
Referenced by libMesh::Parallel::StandardType< Hilbert::HilbertIndices >::StandardType().
 : _datatype() {}
DataType() [2/4]
libMesh::Parallel::DataType::DataType (const DataType & other) inline
Definition at line 68 of file data_type.h.
                                     :
     _datatype(other._datatype)
   {}
DataType() [3/4]
libMesh::Parallel::DataType::DataType (const data_type & type) inline
Definition at line 72 of file data_type.h.
                                     :
     _datatype(type)
   {}
DataType() [4/4]
libMesh::Parallel::DataType::DataType (const DataType & other, unsigned int count) inline
Definition at line 76 of file data_type.h.
References _datatype, commit(), and libMesh::libmesh_ignore().
   {
     // FIXME - if we nest an inner type here will we run into bug
     // https://github.com/libMesh/libmesh/issues/631 again?
     libmesh_call_mpi(MPI_Type_contiguous(count, other._datatype, &_datatype));
     libmesh_ignore(other, count); // ifndef LIBMESH_HAVE_MPI
     this->commit();
   }
Member Function Documentation
commit()
void libMesh::Parallel::DataType::commit () inline
Definition at line 103 of file data_type.h.
References _datatype.
Referenced by DataType(), libMesh::Parallel::StandardType< std::pair< T1, T2 > >::StandardType(), and libMesh::Parallel::StandardType< std::tuple< Types... > >::StandardType().
   {
     libmesh_call_mpi
       (MPI_Type_commit (&_datatype));
   }
free()
void libMesh::Parallel::DataType::free () inline
Definition at line 109 of file data_type.h.
References _datatype.
Referenced by libMesh::Parallel::StandardType< Hilbert::HilbertIndices >::~StandardType(), libMesh::Parallel::StandardType< TypeVector< T > >::~StandardType(), libMesh::Parallel::StandardType< VectorValue< T > >::~StandardType(), libMesh::Parallel::StandardType< std::pair< T1, T2 > >::~StandardType(), libMesh::Parallel::StandardType< Point >::~StandardType(), libMesh::Parallel::StandardType< std::tuple< Types... > >::~StandardType(), libMesh::Parallel::StandardType< std::complex< T > >::~StandardType(), libMesh::Parallel::StandardType< TypeTensor< T > >::~StandardType(), and libMesh::Parallel::StandardType< TensorValue< T > >::~StandardType().
   {
     libmesh_call_mpi
       (MPI_Type_free (&_datatype));
   }
operator const data_type &()
libMesh::Parallel::DataType::operator const data_type & () const inline
Definition at line 91 of file data_type.h.
References _datatype.
   { return _datatype; }
operator data_type &()
libMesh::Parallel::DataType::operator data_type & () inline
Definition at line 94 of file data_type.h.
References _datatype.
   { return _datatype; }
operator=() [1/2]
DataType& libMesh::Parallel::DataType::operator= (const DataType & other) inline
Definition at line 85 of file data_type.h.
References _datatype.
   { _datatype = other._datatype; return *this; }
operator=() [2/2]
DataType& libMesh::Parallel::DataType::operator= (const data_type & type) inline
Definition at line 88 of file data_type.h.
References _datatype.
   { _datatype = type; return *this; }
Member Data Documentation
_datatype
data_type libMesh::Parallel::DataType::_datatype protected
Definition at line 117 of file data_type.h.
Referenced by commit(), DataType(), free(), operator const data_type &(), operator data_type &(), operator=(), libMesh::Parallel::StandardType< TypeVector< T > >::StandardType(), libMesh::Parallel::StandardType< Hilbert::HilbertIndices >::StandardType(), libMesh::Parallel::StandardType< VectorValue< T > >::StandardType(), libMesh::Parallel::StandardType< std::pair< T1, T2 > >::StandardType(), libMesh::Parallel::StandardType< Point >::StandardType(), and libMesh::Parallel::StandardType< std::tuple< Types... > >::StandardType().
The documentation for this class was generated from the following file:
data_type.h