libMesh: libMesh::UnstructuredMesh Class Reference
SomeWebsiteLogo
libMesh::UnstructuredMesh Class Reference abstract
#include <unstructured_mesh.h>
Public Types
typedef Predicates::multi_predicate Predicate
Public Member Functions
UnstructuredMesh (const Parallel::Communicator &comm_in, unsigned char dim=1)
UnstructuredMesh (unsigned char dim=1)
virtual ~UnstructuredMesh ()
virtual void read (const std::string &name, MeshData *mesh_data=libmesh_nullptr, bool skip_renumber_nodes_and_elements=false) libmesh_override
virtual void write (const std::string &name, MeshData *mesh_data=libmesh_nullptr) libmesh_override
void write (const std::string &name, const std::vector< Number > &values, const std::vector< std::string > &variable_names)
virtual void all_first_order () libmesh_override
virtual void all_second_order (const bool full_ordered=true) libmesh_override
void create_pid_mesh (UnstructuredMesh &pid_mesh, const processor_id_type pid) const
void create_submesh (UnstructuredMesh &new_mesh, const_element_iterator &it, const const_element_iterator &it_end) const
virtual void copy_nodes_and_elements (const UnstructuredMesh &other_mesh, const bool skip_find_neighbors=false)
virtual void find_neighbors (const bool reset_remote_elements=false, const bool reset_current_list=true) libmesh_override
virtual bool contract () libmesh_override
virtual UniquePtr< MeshBase > clone () const =0
virtual UniquePtr< Partitioner > & partitioner ()
const BoundaryInfo & get_boundary_info () const
BoundaryInfo & get_boundary_info ()
virtual void clear ()
bool is_prepared () const
virtual bool is_serial () const
virtual void allgather ()
virtual void delete_remote_elements ()
unsigned int mesh_dimension () const
void set_mesh_dimension (unsigned char d)
const std::set< unsigned char > & elem_dimensions () const
unsigned int spatial_dimension () const
void set_spatial_dimension (unsigned char d)
virtual dof_id_type n_nodes () const =0
virtual dof_id_type parallel_n_nodes () const =0
dof_id_type n_nodes_on_proc (const processor_id_type proc) const
dof_id_type n_local_nodes () const
dof_id_type n_unpartitioned_nodes () const
virtual dof_id_type max_node_id () const =0
unique_id_type next_unique_id ()
void set_next_unique_id (unique_id_type id)
virtual void reserve_nodes (const dof_id_type nn)=0
virtual dof_id_type n_elem () const =0
virtual dof_id_type parallel_n_elem () const =0
virtual dof_id_type max_elem_id () const =0
virtual unique_id_type parallel_max_unique_id () const =0
virtual void reserve_elem (const dof_id_type ne)=0
virtual void update_parallel_id_counts ()=0
virtual dof_id_type n_active_elem () const =0
dof_id_type n_elem_on_proc (const processor_id_type proc) const
dof_id_type n_local_elem () const
dof_id_type n_unpartitioned_elem () const
dof_id_type n_active_elem_on_proc (const processor_id_type proc) const
dof_id_type n_active_local_elem () const
dof_id_type n_sub_elem () const
dof_id_type n_active_sub_elem () const
virtual const Point & point (const dof_id_type i) const =0
virtual const Node & node (const dof_id_type i) const =0
virtual Node & node (const dof_id_type i)=0
virtual const Node * node_ptr (const dof_id_type i) const =0
virtual Node * node_ptr (const dof_id_type i)=0
virtual const Node * query_node_ptr (const dof_id_type i) const =0
virtual Node * query_node_ptr (const dof_id_type i)=0
virtual const Elem * elem (const dof_id_type i) const =0
virtual Elem * elem (const dof_id_type i)=0
virtual const Elem * query_elem (const dof_id_type i) const =0
virtual Elem * query_elem (const dof_id_type i)=0
virtual Node * add_point (const Point &p, const dof_id_type id=DofObject::invalid_id, const processor_id_type proc_id=DofObject::invalid_processor_id)=0
virtual Node * add_node (Node *n)=0
virtual Node * insert_node (Node *n)=0
virtual void delete_node (Node *n)=0
virtual void renumber_node (dof_id_type old_id, dof_id_type new_id)=0
virtual Elem * add_elem (Elem *e)=0
virtual Elem * insert_elem (Elem *e)=0
virtual void delete_elem (Elem *e)=0
virtual void renumber_elem (dof_id_type old_id, dof_id_type new_id)=0
virtual void renumber_nodes_and_elements ()=0
virtual void fix_broken_node_and_element_numbering ()=0
void prepare_for_use (const bool skip_renumber_nodes_and_elements=false, const bool skip_find_neighbors=false)
virtual void partition (const unsigned int n_parts)
void partition ()
virtual void redistribute ()
virtual void update_post_partitioning ()
void allow_renumbering (bool allow)
bool allow_renumbering () const
void skip_partitioning (bool skip)
bool skip_partitioning () const
void subdomain_ids (std::set< subdomain_id_type > &ids) const
subdomain_id_type n_subdomains () const
unsigned int n_partitions () const
std::string get_info () const
void print_info (std::ostream &os=libMesh::out) const
unsigned int recalculate_n_partitions ()
const PointLocatorBase & point_locator () const
UniquePtr< PointLocatorBase > sub_point_locator () const
void clear_point_locator ()
virtual void libmesh_assert_valid_parallel_ids () const
std::string & subdomain_name (subdomain_id_type id)
const std::string & subdomain_name (subdomain_id_type id) const
subdomain_id_type get_id_by_name (const std::string &name) const
virtual element_iterator elements_begin ()=0
virtual const_element_iterator elements_begin () const =0
virtual element_iterator elements_end ()=0
virtual const_element_iterator elements_end () const =0
virtual element_iterator ancestor_elements_begin ()=0
virtual const_element_iterator ancestor_elements_begin () const =0
virtual element_iterator ancestor_elements_end ()=0
virtual const_element_iterator ancestor_elements_end () const =0
virtual element_iterator subactive_elements_begin ()=0
virtual const_element_iterator subactive_elements_begin () const =0
virtual element_iterator subactive_elements_end ()=0
virtual const_element_iterator subactive_elements_end () const =0
virtual element_iterator semilocal_elements_begin ()=0
virtual const_element_iterator semilocal_elements_begin () const =0
virtual element_iterator semilocal_elements_end ()=0
virtual const_element_iterator semilocal_elements_end () const =0
virtual element_iterator facelocal_elements_begin ()=0
virtual const_element_iterator facelocal_elements_begin () const =0
virtual element_iterator facelocal_elements_end ()=0
virtual const_element_iterator facelocal_elements_end () const =0
virtual element_iterator level_elements_begin (unsigned int level)=0
virtual const_element_iterator level_elements_begin (unsigned int level) const =0
virtual element_iterator level_elements_end (unsigned int level)=0
virtual const_element_iterator level_elements_end (unsigned int level) const =0
virtual element_iterator pid_elements_begin (processor_id_type proc_id)=0
virtual const_element_iterator pid_elements_begin (processor_id_type proc_id) const =0
virtual element_iterator pid_elements_end (processor_id_type proc_id)=0
virtual const_element_iterator pid_elements_end (processor_id_type proc_id) const =0
virtual element_iterator type_elements_begin (ElemType type)=0
virtual const_element_iterator type_elements_begin (ElemType type) const =0
virtual element_iterator type_elements_end (ElemType type)=0
virtual const_element_iterator type_elements_end (ElemType type) const =0
virtual element_iterator unpartitioned_elements_begin ()=0
virtual const_element_iterator unpartitioned_elements_begin () const =0
virtual element_iterator unpartitioned_elements_end ()=0
virtual const_element_iterator unpartitioned_elements_end () const =0
virtual element_iterator ghost_elements_begin ()=0
virtual const_element_iterator ghost_elements_begin () const =0
virtual element_iterator ghost_elements_end ()=0
virtual const_element_iterator ghost_elements_end () const =0
virtual element_iterator active_elements_begin ()=0
virtual const_element_iterator active_elements_begin () const =0
virtual element_iterator active_elements_end ()=0
virtual const_element_iterator active_elements_end () const =0
virtual element_iterator local_elements_begin ()=0
virtual const_element_iterator local_elements_begin () const =0
virtual element_iterator local_elements_end ()=0
virtual const_element_iterator local_elements_end () const =0
virtual element_iterator active_type_elements_begin (ElemType type)=0
virtual const_element_iterator active_type_elements_begin (ElemType type) const =0
virtual element_iterator active_type_elements_end (ElemType type)=0
virtual const_element_iterator active_type_elements_end (ElemType type) const =0
virtual element_iterator active_pid_elements_begin (processor_id_type proc_id)=0
virtual const_element_iterator active_pid_elements_begin (processor_id_type proc_id) const =0
virtual element_iterator active_pid_elements_end (processor_id_type proc_id)=0
virtual const_element_iterator active_pid_elements_end (processor_id_type proc_id) const =0
virtual element_iterator active_subdomain_elements_begin (subdomain_id_type subdomain_id)=0
virtual const_element_iterator active_subdomain_elements_begin (subdomain_id_type subdomain_id) const =0
virtual element_iterator active_subdomain_elements_end (subdomain_id_type subdomain_id)=0
virtual const_element_iterator active_subdomain_elements_end (subdomain_id_type subdomain_id) const =0
virtual element_iterator active_local_subdomain_elements_begin (subdomain_id_type subdomain_id)=0
virtual const_element_iterator active_local_subdomain_elements_begin (subdomain_id_type subdomain_id) const =0
virtual element_iterator active_local_subdomain_elements_end (subdomain_id_type subdomain_id)=0
virtual const_element_iterator active_local_subdomain_elements_end (subdomain_id_type subdomain_id) const =0
virtual element_iterator local_level_elements_begin (unsigned int level)=0
virtual const_element_iterator local_level_elements_begin (unsigned int level) const =0
virtual element_iterator local_level_elements_end (unsigned int level)=0
virtual const_element_iterator local_level_elements_end (unsigned int level) const =0
virtual element_iterator local_not_level_elements_begin (unsigned int level)=0
virtual const_element_iterator local_not_level_elements_begin (unsigned int level) const =0
virtual element_iterator local_not_level_elements_end (unsigned int level)=0
virtual const_element_iterator local_not_level_elements_end (unsigned int level) const =0
virtual element_iterator not_level_elements_begin (unsigned int level)=0
virtual const_element_iterator not_level_elements_begin (unsigned int level) const =0
virtual element_iterator not_level_elements_end (unsigned int level)=0
virtual const_element_iterator not_level_elements_end (unsigned int level) const =0
virtual element_iterator active_local_elements_begin ()=0
virtual const_element_iterator active_local_elements_begin () const =0
virtual element_iterator active_local_elements_end ()=0
virtual const_element_iterator active_local_elements_end () const =0
virtual element_iterator active_not_local_elements_begin ()=0
virtual const_element_iterator active_not_local_elements_begin () const =0
virtual element_iterator active_not_local_elements_end ()=0
virtual const_element_iterator active_not_local_elements_end () const =0
virtual element_iterator not_local_elements_begin ()=0
virtual const_element_iterator not_local_elements_begin () const =0
virtual element_iterator not_local_elements_end ()=0
virtual const_element_iterator not_local_elements_end () const =0
virtual element_iterator not_subactive_elements_begin ()=0
virtual const_element_iterator not_subactive_elements_begin () const =0
virtual element_iterator not_subactive_elements_end ()=0
virtual const_element_iterator not_subactive_elements_end () const =0
virtual element_iterator not_active_elements_begin ()=0
virtual const_element_iterator not_active_elements_begin () const =0
virtual element_iterator not_active_elements_end ()=0
virtual const_element_iterator not_active_elements_end () const =0
virtual element_iterator not_ancestor_elements_begin ()=0
virtual const_element_iterator not_ancestor_elements_begin () const =0
virtual element_iterator not_ancestor_elements_end ()=0
virtual const_element_iterator not_ancestor_elements_end () const =0
virtual node_iterator nodes_begin ()=0
virtual const_node_iterator nodes_begin () const =0
virtual node_iterator nodes_end ()=0
virtual const_node_iterator nodes_end () const =0
virtual node_iterator active_nodes_begin ()=0
virtual const_node_iterator active_nodes_begin () const =0
virtual node_iterator active_nodes_end ()=0
virtual const_node_iterator active_nodes_end () const =0
virtual node_iterator local_nodes_begin ()=0
virtual const_node_iterator local_nodes_begin () const =0
virtual node_iterator local_nodes_end ()=0
virtual const_node_iterator local_nodes_end () const =0
virtual node_iterator pid_nodes_begin (processor_id_type proc_id)=0
virtual const_node_iterator pid_nodes_begin (processor_id_type proc_id) const =0
virtual node_iterator pid_nodes_end (processor_id_type proc_id)=0
virtual const_node_iterator pid_nodes_end (processor_id_type proc_id) const =0
virtual node_iterator bid_nodes_begin (boundary_id_type bndry_id)=0
virtual const_node_iterator bid_nodes_begin (boundary_id_type bndry_id) const =0
virtual node_iterator bid_nodes_end (boundary_id_type bndry_id)=0
virtual const_node_iterator bid_nodes_end (boundary_id_type bndry_id) const =0
virtual node_iterator bnd_nodes_begin ()=0
virtual const_node_iterator bnd_nodes_begin () const =0
virtual node_iterator bnd_nodes_end ()=0
virtual const_node_iterator bnd_nodes_end () const =0
std::map< subdomain_id_type, std::string > & set_subdomain_name_map ()
const std::map< subdomain_id_type, std::string > & get_subdomain_name_map () const
void cache_elem_dims ()
void detect_interior_parents ()
const Parallel::Communicator & comm () const
processor_id_type n_processors () const
processor_id_type processor_id () const
Public Attributes
UniquePtr< BoundaryInfo > boundary_info
Protected Member Functions
unsigned int & set_n_partitions ()
Protected Attributes
unsigned int _n_parts
bool _is_prepared
UniquePtr< PointLocatorBase > _point_locator
UniquePtr< Partitioner > _partitioner
unique_id_type _next_unique_id
bool _skip_partitioning
bool _skip_renumber_nodes_and_elements
std::map< subdomain_id_type, std::string > _block_id_to_name
std::set< unsigned char > _elem_dims
unsigned char _spatial_dimension
const Parallel::Communicator & _communicator
Detailed Description
The UnstructuredMesh class is derived from the MeshBase class. The user will typically want to instantiate and use the Mesh class in her applications, which is currently a simple derived class of UnstructuredMesh. In order to use the adaptive mesh refinment capabilities of the library, first instantiate a MeshRefinement object with a reference to this class. Then call the appropriate refinement functions from that object. To interact with the boundary, instantiate a BoundaryMesh with a reference to this class, and then use that object's functionality.
Definition at line 48 of file unstructured_mesh.h.
Member Typedef Documentation
typedef Predicates::multi_predicate libMesh::MeshBase::Predicate inherited
We need an empty, generic class to act as a predicate for this and derived mesh classes.
Definition at line 686 of file mesh_base.h.
Constructor & Destructor Documentation
libMesh::UnstructuredMesh::UnstructuredMesh (const Parallel::Communicator & comm_in, unsigned char dim = 1) explicit
Constructor. Takes dim, the dimension of the mesh. The mesh dimension can be changed (and may automatically be changed by mesh generation/loading) later.
Definition at line 54 of file unstructured_mesh.C.
References libMesh::initialized(), and libMesh::libmesh_assert().
                                                      :
   MeshBase (comm_in,d)
 {
   libmesh_assert (libMesh::initialized());
 }
libMesh::UnstructuredMesh::UnstructuredMesh (unsigned char dim = 1)
Deprecated constructor. Takes dim, the dimension of the mesh. The mesh dimension can be changed (and may automatically be changed by mesh generation/loading) later.
Definition at line 64 of file unstructured_mesh.C.
References libMesh::initialized(), and libMesh::libmesh_assert().
                                                    :
   MeshBase (d)
 {
   libmesh_assert (libMesh::initialized());
 }
libMesh::UnstructuredMesh::~UnstructuredMesh () virtual
Destructor.
Definition at line 223 of file unstructured_mesh.C.
References libMesh::closed().
 {
   //  this->clear ();  // Nothing to clear at this level
   libmesh_exceptionless_assert (!libMesh::closed());
 }
Member Function Documentation
virtual element_iterator libMesh::MeshBase::active_elements_begin () pure virtual inherited
Active, local, and negation forms of the element iterators described above. An "active" element is an element without children (i.e. has not been refined). A "local" element is one whose processor_id() matches the current processor.
Implemented in libMesh::ParallelMesh, and libMesh::SerialMesh.
Referenced by libMesh::MetisPartitioner::_do_partition(), libMesh::LinearPartitioner::_do_partition(), libMesh::SFCPartitioner::_do_partition(), libMesh::DofMap::add_neighbors_to_send_list(), libMesh::ParmetisPartitioner::assign_partitioning(), libMesh::AbaqusIO::assign_sideset_ids(), libMesh::EquationSystems::build_discontinuous_solution_vector(), libMesh::ParmetisPartitioner::build_graph(), libMesh::InfElemBuilder::build_inf_elem(), libMesh::BoundaryInfo::build_side_list_from_node_list(), libMesh::MeshBase::cache_elem_dims(), libMesh::Nemesis_IO_Helper::compute_border_node_ids(), libMesh::MeshTools::correct_node_proc_ids(), libMesh::MeshBase::detect_interior_parents(), libMesh::MeshTools::Modification::distort(), DMlibMeshSetSystem_libMesh(), libMesh::TecplotIO::elem_dimension(), libMesh::MeshRefinement::eliminate_unrefined_patches(), libMesh::PointLocatorTree::enable_out_of_mesh_mode(), libMesh::LocationMap< T >::fill(), libMesh::MeshTools::find_boundary_nodes(), libMesh::MeshRefinement::flag_elements_by_elem_fraction(), libMesh::MeshRefinement::flag_elements_by_error_fraction(), libMesh::MeshRefinement::flag_elements_by_error_tolerance(), libMesh::MeshRefinement::flag_elements_by_mean_stddev(), libMesh::MeshTools::Modification::flatten(), libMesh::BoundaryInfo::get_side_and_node_maps(), libMesh::UNVIO::groups_in(), libMesh::PointLocatorList::init(), libMesh::ParmetisPartitioner::initialize(), libMesh::ExodusII_IO_Helper::initialize(), libMesh::DofMap::invalidate_dofs(), libMesh::MeshTools::libmesh_assert_valid_elem_ids(), libMesh::MeshRefinement::limit_level_mismatch_at_edge(), libMesh::MeshRefinement::limit_level_mismatch_at_node(), libMesh::MeshRefinement::limit_overrefined_boundary(), libMesh::MeshRefinement::limit_underrefined_boundary(), libMesh::MeshRefinement::make_coarsening_compatible(), libMesh::MeshCommunication::make_elems_parallel_consistent(), libMesh::MeshRefinement::make_refinement_compatible(), libMesh::CheckpointIO::n_active_levels_on_processor(), libMesh::MeshBase::n_active_sub_elem(), libMesh::PointLocatorTree::perform_linear_search(), libMesh::System::read_legacy_data(), libMesh::VariationalMeshSmoother::readgr(), libMesh::DofMap::reinit(), libMesh::Partitioner::set_node_processor_ids(), libMesh::LaplaceMeshSmoother::smooth(), libMesh::Tree< N >::Tree(), libMesh::MeshRefinement::uniformly_coarsen(), libMesh::MeshRefinement::uniformly_p_coarsen(), libMesh::MeshRefinement::uniformly_p_refine(), libMesh::MeshRefinement::uniformly_refine(), libMesh::FroIO::write(), libMesh::PostscriptIO::write(), libMesh::TetGenIO::write(), libMesh::MEDITIO::write_ascii(), libMesh::TecplotIO::write_ascii(), libMesh::GMVIO::write_ascii_new_impl(), libMesh::GMVIO::write_ascii_old_impl(), libMesh::TecplotIO::write_binary(), libMesh::GMVIO::write_binary(), libMesh::GMVIO::write_discontinuous_gmv(), libMesh::ExodusII_IO_Helper::write_element_values(), libMesh::ExodusII_IO_Helper::write_elements(), libMesh::ExodusII_IO_Helper::write_nodal_coordinates(), libMesh::ExodusII_IO::write_nodal_data_discontinuous(), libMesh::GmshIO::write_post(), and libMesh::GnuPlotIO::write_solution().
virtual const_element_iterator libMesh::MeshBase::active_elements_begin () const pure virtual inherited
Implemented in libMesh::ParallelMesh, and libMesh::SerialMesh.
virtual element_iterator libMesh::MeshBase::active_elements_end () pure virtual inherited
Implemented in libMesh::ParallelMesh, and libMesh::SerialMesh.
Referenced by libMesh::MetisPartitioner::_do_partition(), libMesh::LinearPartitioner::_do_partition(), libMesh::SFCPartitioner::_do_partition(), libMesh::DofMap::add_neighbors_to_send_list(), libMesh::ParmetisPartitioner::assign_partitioning(), libMesh::AbaqusIO::assign_sideset_ids(), libMesh::EquationSystems::build_discontinuous_solution_vector(), libMesh::ParmetisPartitioner::build_graph(), libMesh::InfElemBuilder::build_inf_elem(), libMesh::BoundaryInfo::build_side_list_from_node_list(), libMesh::MeshBase::cache_elem_dims(), libMesh::Nemesis_IO_Helper::compute_border_node_ids(), libMesh::MeshTools::correct_node_proc_ids(), libMesh::MeshBase::detect_interior_parents(), libMesh::MeshTools::Modification::distort(), DMlibMeshSetSystem_libMesh(), libMesh::TecplotIO::elem_dimension(), libMesh::MeshRefinement::eliminate_unrefined_patches(), libMesh::PointLocatorTree::enable_out_of_mesh_mode(), libMesh::LocationMap< T >::fill(), libMesh::MeshTools::find_boundary_nodes(), libMesh::MeshRefinement::flag_elements_by_error_fraction(), libMesh::MeshRefinement::flag_elements_by_error_tolerance(), libMesh::MeshRefinement::flag_elements_by_mean_stddev(), libMesh::MeshTools::Modification::flatten(), libMesh::BoundaryInfo::get_side_and_node_maps(), libMesh::UNVIO::groups_in(), libMesh::PointLocatorList::init(), libMesh::ParmetisPartitioner::initialize(), libMesh::ExodusII_IO_Helper::initialize(), libMesh::DofMap::invalidate_dofs(), libMesh::MeshTools::libmesh_assert_valid_elem_ids(), libMesh::MeshRefinement::limit_level_mismatch_at_edge(), libMesh::MeshRefinement::limit_level_mismatch_at_node(), libMesh::MeshRefinement::limit_overrefined_boundary(), libMesh::MeshRefinement::limit_underrefined_boundary(), libMesh::MeshRefinement::make_coarsening_compatible(), libMesh::MeshCommunication::make_elems_parallel_consistent(), libMesh::MeshRefinement::make_refinement_compatible(), libMesh::CheckpointIO::n_active_levels_on_processor(), libMesh::MeshBase::n_active_sub_elem(), libMesh::PointLocatorTree::perform_linear_search(), libMesh::System::read_legacy_data(), libMesh::VariationalMeshSmoother::readgr(), libMesh::DofMap::reinit(), libMesh::Partitioner::set_node_processor_ids(), libMesh::LaplaceMeshSmoother::smooth(), libMesh::Tree< N >::Tree(), libMesh::MeshRefinement::uniformly_coarsen(), libMesh::MeshRefinement::uniformly_p_coarsen(), libMesh::MeshRefinement::uniformly_p_refine(), libMesh::MeshRefinement::uniformly_refine(), libMesh::FroIO::write(), libMesh::PostscriptIO::write(), libMesh::TetGenIO::write(), libMesh::MEDITIO::write_ascii(), libMesh::TecplotIO::write_ascii(), libMesh::GMVIO::write_ascii_new_impl(), libMesh::GMVIO::write_ascii_old_impl(), libMesh::TecplotIO::write_binary(), libMesh::GMVIO::write_binary(), libMesh::GMVIO::write_discontinuous_gmv(), libMesh::ExodusII_IO_Helper::write_element_values(), libMesh::ExodusII_IO_Helper::write_elements(), libMesh::ExodusII_IO_Helper::write_nodal_coordinates(), libMesh::ExodusII_IO::write_nodal_data_discontinuous(), libMesh::GmshIO::write_post(), and libMesh::GnuPlotIO::write_solution().
virtual const_element_iterator libMesh::MeshBase::active_elements_end () const pure virtual inherited
Implemented in libMesh::ParallelMesh, and libMesh::SerialMesh.
virtual element_iterator libMesh::MeshBase::active_local_elements_begin () pure virtual inherited
Implemented in libMesh::ParallelMesh, and libMesh::SerialMesh.
Referenced by libMesh::ExactSolution::_compute_error(), libMesh::UniformRefinementEstimator::_estimate_error(), libMesh::DofMap::add_neighbors_to_send_list(), libMesh::FEMSystem::assemble_qoi(), libMesh::FEMSystem::assemble_qoi_derivative(), libMesh::FEMSystem::assembly(), libMesh::Nemesis_IO_Helper::build_element_and_node_maps(), libMesh::ParmetisPartitioner::build_graph(), libMesh::EquationSystems::build_solution_vector(), libMesh::DofMap::build_sparsity(), libMesh::System::calculate_norm(), libMesh::VTKIO::cells_to_vtk(), libMesh::Nemesis_IO_Helper::compute_internal_and_border_elems_and_internal_nodes(), libMesh::Nemesis_IO_Helper::compute_num_global_elem_blocks(), libMesh::MeshRefinement::create_parent_error_vector(), libMesh::DofMap::distribute_local_dofs_node_major(), libMesh::DofMap::distribute_local_dofs_var_major(), libMesh::WeightedPatchRecoveryErrorEstimator::estimate_error(), libMesh::PatchRecoveryErrorEstimator::estimate_error(), libMesh::JumpErrorEstimator::estimate_error(), libMesh::AdjointRefinementEstimator::estimate_error(), libMesh::MeshTools::find_hanging_nodes_and_parents(), libMesh::MeshRefinement::flag_elements_by_elem_fraction(), libMesh::MeshRefinement::flag_elements_by_error_fraction(), libMesh::MeshRefinement::flag_elements_by_nelem_target(), libMesh::for(), libMesh::EquationSystems::get_solution(), libMesh::LaplaceMeshSmoother::init(), libMesh::SystemSubsetBySubdomain::init(), libMesh::ParmetisPartitioner::initialize(), libMesh::MeshTools::libmesh_assert_valid_procids< Node >(), libMesh::System::local_dof_indices(), libMesh::DofMap::local_variable_indices(), libMesh::DofMap::max_constraint_error(), libMesh::FEMSystem::mesh_position_get(), libMesh::FEMSystem::mesh_position_set(), libMesh::MeshTools::n_active_local_levels(), libMesh::PointLocatorTree::perform_linear_search(), libMesh::ErrorVector::plot_error(), libMesh::FEMSystem::postprocess(), libMesh::System::project_vector(), libMesh::MeshBase::recalculate_n_partitions(), libMesh::HPSingularity::select_refinement(), libMesh::HPCoarsenTest::select_refinement(), libMesh::MeshBase::subdomain_ids(), libMesh::MeshRefinement::test_level_one(), libMesh::MeshRefinement::test_unflagged(), libMesh::Tree< N >::Tree(), libMesh::Nemesis_IO_Helper::write_exodus_initialization_info(), libMesh::EnsightIO::write_geometry_ascii(), libMesh::EnsightIO::write_scalar_ascii(), libMesh::EnsightIO::write_vector_ascii(), and libMesh::System::zero_variable().
virtual const_element_iterator libMesh::MeshBase::active_local_elements_begin () const pure virtual inherited
Implemented in libMesh::ParallelMesh, and libMesh::SerialMesh.
virtual element_iterator libMesh::MeshBase::active_local_elements_end () pure virtual inherited
Implemented in libMesh::ParallelMesh, and libMesh::SerialMesh.
Referenced by libMesh::ExactSolution::_compute_error(), libMesh::UniformRefinementEstimator::_estimate_error(), libMesh::DofMap::add_neighbors_to_send_list(), libMesh::FEMSystem::assemble_qoi(), libMesh::FEMSystem::assemble_qoi_derivative(), libMesh::FEMSystem::assembly(), libMesh::Nemesis_IO_Helper::build_element_and_node_maps(), libMesh::ParmetisPartitioner::build_graph(), libMesh::EquationSystems::build_solution_vector(), libMesh::DofMap::build_sparsity(), libMesh::System::calculate_norm(), libMesh::VTKIO::cells_to_vtk(), libMesh::Nemesis_IO_Helper::compute_internal_and_border_elems_and_internal_nodes(), libMesh::Nemesis_IO_Helper::compute_num_global_elem_blocks(), libMesh::MeshRefinement::create_parent_error_vector(), libMesh::DofMap::distribute_local_dofs_node_major(), libMesh::DofMap::distribute_local_dofs_var_major(), libMesh::WeightedPatchRecoveryErrorEstimator::estimate_error(), libMesh::PatchRecoveryErrorEstimator::estimate_error(), libMesh::JumpErrorEstimator::estimate_error(), libMesh::AdjointRefinementEstimator::estimate_error(), libMesh::MeshTools::find_hanging_nodes_and_parents(), libMesh::MeshRefinement::flag_elements_by_elem_fraction(), libMesh::MeshRefinement::flag_elements_by_error_fraction(), libMesh::MeshRefinement::flag_elements_by_nelem_target(), libMesh::for(), libMesh::EquationSystems::get_solution(), libMesh::LaplaceMeshSmoother::init(), libMesh::SystemSubsetBySubdomain::init(), libMesh::ParmetisPartitioner::initialize(), libMesh::MeshTools::libmesh_assert_valid_procids< Node >(), libMesh::System::local_dof_indices(), libMesh::DofMap::local_variable_indices(), libMesh::DofMap::max_constraint_error(), libMesh::FEMSystem::mesh_position_get(), libMesh::FEMSystem::mesh_position_set(), libMesh::MeshTools::n_active_local_levels(), libMesh::PointLocatorTree::perform_linear_search(), libMesh::ErrorVector::plot_error(), libMesh::FEMSystem::postprocess(), libMesh::MeshBase::recalculate_n_partitions(), libMesh::HPSingularity::select_refinement(), libMesh::HPCoarsenTest::select_refinement(), libMesh::MeshBase::subdomain_ids(), libMesh::MeshRefinement::test_level_one(), libMesh::MeshRefinement::test_unflagged(), libMesh::Tree< N >::Tree(), libMesh::Nemesis_IO_Helper::write_exodus_initialization_info(), libMesh::EnsightIO::write_geometry_ascii(), libMesh::EnsightIO::write_scalar_ascii(), libMesh::EnsightIO::write_vector_ascii(), and libMesh::System::zero_variable().
virtual const_element_iterator libMesh::MeshBase::active_local_elements_end () const pure virtual inherited
Implemented in libMesh::ParallelMesh, and libMesh::SerialMesh.
virtual element_iterator libMesh::MeshBase::active_local_subdomain_elements_begin (subdomain_id_type subdomain_id) pure virtual inherited
Implemented in libMesh::ParallelMesh, and libMesh::SerialMesh.
Referenced by DMCreateDomainDecomposition_libMesh(), and DMCreateFieldDecomposition_libMesh().
virtual const_element_iterator libMesh::MeshBase::active_local_subdomain_elements_begin (subdomain_id_type subdomain_id) const pure virtual inherited
Implemented in libMesh::ParallelMesh, and libMesh::SerialMesh.
virtual element_iterator libMesh::MeshBase::active_local_subdomain_elements_end (subdomain_id_type subdomain_id) pure virtual inherited
Implemented in libMesh::ParallelMesh, and libMesh::SerialMesh.
Referenced by DMCreateDomainDecomposition_libMesh(), and DMCreateFieldDecomposition_libMesh().
virtual const_element_iterator libMesh::MeshBase::active_local_subdomain_elements_end (subdomain_id_type subdomain_id) const pure virtual inherited
Implemented in libMesh::ParallelMesh, and libMesh::SerialMesh.
virtual node_iterator libMesh::MeshBase::active_nodes_begin () pure virtual inherited
Iterate over only the active nodes in the Mesh.
Implemented in libMesh::ParallelMesh, and libMesh::SerialMesh.
virtual const_node_iterator libMesh::MeshBase::active_nodes_begin () const pure virtual inherited
Implemented in libMesh::ParallelMesh, and libMesh::SerialMesh.
virtual node_iterator libMesh::MeshBase::active_nodes_end () pure virtual inherited
Implemented in libMesh::ParallelMesh, and libMesh::SerialMesh.
virtual const_node_iterator libMesh::MeshBase::active_nodes_end () const pure virtual inherited
Implemented in libMesh::ParallelMesh, and libMesh::SerialMesh.
virtual element_iterator libMesh::MeshBase::active_not_local_elements_begin () pure virtual inherited
Implemented in libMesh::ParallelMesh, and libMesh::SerialMesh.
Referenced by libMesh::DofMap::allgather_recursive_constraints(), and libMesh::DofMap::scatter_constraints().
virtual const_element_iterator libMesh::MeshBase::active_not_local_elements_begin () const pure virtual inherited
Implemented in libMesh::ParallelMesh, and libMesh::SerialMesh.
virtual element_iterator libMesh::MeshBase::active_not_local_elements_end () pure virtual inherited
Implemented in libMesh::ParallelMesh, and libMesh::SerialMesh.
Referenced by libMesh::DofMap::allgather_recursive_constraints(), and libMesh::DofMap::scatter_constraints().
virtual const_element_iterator libMesh::MeshBase::active_not_local_elements_end () const pure virtual inherited
Implemented in libMesh::ParallelMesh, and libMesh::SerialMesh.
virtual element_iterator libMesh::MeshBase::active_pid_elements_begin (processor_id_type proc_id) pure virtual inherited
Implemented in libMesh::ParallelMesh, and libMesh::SerialMesh.
Referenced by create_pid_mesh(), libMesh::ParmetisPartitioner::initialize(), and libMesh::MeshBase::n_active_elem_on_proc().
virtual const_element_iterator libMesh::MeshBase::active_pid_elements_begin (processor_id_type proc_id) const pure virtual inherited
Implemented in libMesh::ParallelMesh, and libMesh::SerialMesh.
virtual element_iterator libMesh::MeshBase::active_pid_elements_end (processor_id_type proc_id) pure virtual inherited
Implemented in libMesh::ParallelMesh, and libMesh::SerialMesh.
Referenced by create_pid_mesh(), libMesh::ParmetisPartitioner::initialize(), and libMesh::MeshBase::n_active_elem_on_proc().
virtual const_element_iterator libMesh::MeshBase::active_pid_elements_end (processor_id_type proc_id) const pure virtual inherited
Implemented in libMesh::ParallelMesh, and libMesh::SerialMesh.
virtual element_iterator libMesh::MeshBase::active_subdomain_elements_begin (subdomain_id_type subdomain_id) pure virtual inherited
Implemented in libMesh::ParallelMesh, and libMesh::SerialMesh.
Referenced by libMesh::TecplotIO::write_binary().
virtual const_element_iterator libMesh::MeshBase::active_subdomain_elements_begin (subdomain_id_type subdomain_id) const pure virtual inherited
Implemented in libMesh::ParallelMesh, and libMesh::SerialMesh.
virtual element_iterator libMesh::MeshBase::active_subdomain_elements_end (subdomain_id_type subdomain_id) pure virtual inherited
Implemented in libMesh::ParallelMesh, and libMesh::SerialMesh.
Referenced by libMesh::TecplotIO::write_binary().
virtual const_element_iterator libMesh::MeshBase::active_subdomain_elements_end (subdomain_id_type subdomain_id) const pure virtual inherited
Implemented in libMesh::ParallelMesh, and libMesh::SerialMesh.
virtual element_iterator libMesh::MeshBase::active_type_elements_begin (ElemType type) pure virtual inherited
Implemented in libMesh::ParallelMesh, and libMesh::SerialMesh.
Referenced by libMesh::MeshTools::n_active_elem_of_type().
virtual const_element_iterator libMesh::MeshBase::active_type_elements_begin (ElemType type) const pure virtual inherited
Implemented in libMesh::ParallelMesh, and libMesh::SerialMesh.
virtual element_iterator libMesh::MeshBase::active_type_elements_end (ElemType type) pure virtual inherited
Implemented in libMesh::ParallelMesh, and libMesh::SerialMesh.
Referenced by libMesh::MeshTools::n_active_elem_of_type().
virtual const_element_iterator libMesh::MeshBase::active_type_elements_end (ElemType type) const pure virtual inherited
Implemented in libMesh::ParallelMesh, and libMesh::SerialMesh.
virtual Elem* libMesh::MeshBase::add_elem (Elem * e) pure virtual inherited
Add elem e to the end of the element array. To add an element locally, set e->processor_id() before adding it. To ensure a specific element id, call e->set_id() before adding it; only do this in parallel if you are manually keeping ids consistent.
Users should call MeshBase::prepare_for_use() after elements are added to and/or deleted from the mesh.
Implemented in libMesh::ParallelMesh, and libMesh::SerialMesh.
Referenced by libMesh::GMVIO::_read_one_cell(), libMesh::MeshTools::Subdivision::add_boundary_ghosts(), libMesh::MeshRefinement::add_elem(), libMesh::BoundaryInfo::add_elements(), libMesh::MeshTools::Modification::all_tri(), libMesh::MeshTools::Generation::build_cube(), libMesh::MeshTools::Generation::build_extrusion(), libMesh::InfElemBuilder::build_inf_elem(), copy_nodes_and_elements(), libMesh::TriangleWrapper::copy_tri_to_mesh(), create_submesh(), libMesh::UNVIO::elements_in(), libMesh::MeshTools::Modification::flatten(), libMesh::mesh_inserter_iterator< T >::operator=(), libMesh::TetGenMeshInterface::pointset_convexhull(), libMesh::Nemesis_IO::read(), libMesh::ExodusII_IO::read(), libMesh::VTKIO::read(), libMesh::CheckpointIO::read_connectivity(), libMesh::AbaqusIO::read_elements(), libMesh::LegacyXdrIO::read_mesh(), libMesh::XdrIO::read_serialized_connectivity(), libMesh::OFFIO::read_stream(), libMesh::MatlabIO::read_stream(), libMesh::TetGenMeshInterface::triangulate_conformingDelaunayMesh_carvehole(), and libMesh::TetGenMeshInterface::triangulate_pointset().
virtual Node* libMesh::MeshBase::add_node (Node * n) pure virtual inherited
Add Node n to the end of the vertex array.
Implemented in libMesh::ParallelMesh, and libMesh::SerialMesh.
virtual Node* libMesh::MeshBase::add_point (const Point & p, const dof_id_type id = DofObject::invalid_id, const processor_id_type proc_id = DofObject::invalid_processor_id) pure virtual inherited
Add a new Node at Point p to the end of the vertex array, with processor_id procid. Use DofObject::invalid_processor_id (default) to add a node to all processors, or this->processor_id() to add a node to the local processor only. If adding a node locally, passing an id other than DofObject::invalid_id will set that specific node id. Only do this in parallel if you are manually keeping ids consistent.
Implemented in libMesh::ParallelMesh, and libMesh::SerialMesh.
Referenced by libMesh::MeshTools::Subdivision::add_boundary_ghosts(), libMesh::MeshRefinement::add_node(), all_second_order(), libMesh::MeshTools::Modification::all_tri(), libMesh::MeshTools::Generation::build_cube(), libMesh::MeshTools::Generation::build_delaunay_square(), libMesh::MeshTools::Generation::build_extrusion(), libMesh::InfElemBuilder::build_inf_elem(), copy_nodes_and_elements(), libMesh::TriangleWrapper::copy_tri_to_mesh(), create_submesh(), libMesh::UNVIO::nodes_in(), libMesh::mesh_inserter_iterator< T >::operator=(), libMesh::Nemesis_IO::read(), libMesh::ExodusII_IO::read(), libMesh::VTKIO::read(), libMesh::LegacyXdrIO::read_mesh(), libMesh::AbaqusIO::read_nodes(), libMesh::CheckpointIO::read_nodes(), libMesh::XdrIO::read_serialized_connectivity(), libMesh::OFFIO::read_stream(), libMesh::MatlabIO::read_stream(), libMesh::BoundaryInfo::sync(), libMesh::TriangleInterface::triangulate(), and libMesh::TetGenMeshInterface::triangulate_conformingDelaunayMesh_carvehole().
void libMesh::UnstructuredMesh::all_first_order () virtual
Converts a mesh with higher-order elements into a mesh with linear elements. For example, a mesh consisting of Tet10 will be converted to a mesh with Tet4 etc.
Prepare to identify (and then delete) a bunch of no-longer-used nodes.
Loop over the high-ordered elements. First make sure they are indeed high-order, and then replace them with an equivalent first-order element.
If the second order element had any boundary conditions they should be transfered to the first-order element. The old boundary conditions will be removed from the BoundaryInfo data structure by insert_elem.
Implements libMesh::MeshBase.
Definition at line 311 of file mesh_modification.C.
References libMesh::MeshBase::_is_prepared, libMesh::Elem::add_child(), libMesh::BoundaryInfo::add_side(), libMesh::Elem::build(), libMesh::Elem::child(), libMesh::MeshBase::delete_node(), libMesh::MeshBase::elements_begin(), libMesh::MeshBase::elements_end(), libMesh::Elem::first_order_equivalent_type(), libMesh::MeshBase::get_boundary_info(), libMesh::Elem::get_node(), libMesh::Elem::has_children(), libMesh::DofObject::id(), libMesh::MeshBase::insert_elem(), libMesh::libmesh_assert(), libMesh::MeshBase::max_node_id(), libMesh::Elem::n_children(), libMesh::Elem::n_sides(), libMesh::Elem::n_vertices(), libMesh::Elem::neighbor(), libMesh::Elem::node(), libMesh::MeshBase::nodes_begin(), libMesh::MeshBase::nodes_end(), libMesh::Elem::p_level(), libMesh::Elem::p_refinement_flag(), libMesh::Elem::parent(), libMesh::MeshBase::prepare_for_use(), libMesh::DofObject::processor_id(), libMesh::BoundaryInfo::raw_boundary_ids(), libMesh::Elem::refinement_flag(), libMesh::remote_elem, libMesh::MeshBase::renumber_nodes_and_elements(), libMesh::Elem::replace_child(), libMesh::DofObject::set_id(), libMesh::Elem::set_neighbor(), libMesh::Elem::set_node(), libMesh::Partitioner::set_node_processor_ids(), libMesh::Elem::set_p_level(), libMesh::Elem::set_p_refinement_flag(), libMesh::Elem::set_parent(), libMesh::Elem::set_refinement_flag(), libMesh::DofObject::set_unique_id(), libMesh::START_LOG(), libMesh::STOP_LOG(), libMesh::Elem::subdomain_id(), libMesh::Elem::type(), libMesh::DofObject::unique_id(), and libMesh::Elem::which_child_am_i().
 {
   /*
    * when the mesh is not prepared,
    * at least renumber the nodes and
    * elements, so that the node ids
    * are correct
    */
   if (!this->_is_prepared)
     this->renumber_nodes_and_elements ();
   START_LOG("all_first_order()", "Mesh");
   std::vector<bool> node_touched_by_me(this->max_node_id(), false);
   element_iterator endit = elements_end();
   for (element_iterator it = elements_begin();
        it != endit; ++it)
     {
       Elem * so_elem = *it;
       libmesh_assert(so_elem);
       /*
        * build the first-order equivalent, add to
        * the new_elements list.
        */
       Elem * lo_elem = Elem::build
         (Elem::first_order_equivalent_type
          (so_elem->type()), so_elem->parent()).release();
       for (unsigned int s=0; s != so_elem->n_sides(); ++s)
         if (so_elem->neighbor(s) == remote_elem)
           lo_elem->set_neighbor(s, const_cast<RemoteElem *>(remote_elem));
 #ifdef LIBMESH_ENABLE_AMR
       /*
        * Reset the parent links of any child elements
        */
       if (so_elem->has_children())
         for (unsigned int c=0; c != so_elem->n_children(); ++c)
           {
             so_elem->child(c)->set_parent(lo_elem);
             lo_elem->add_child(so_elem->child(c), c);
           }
       /*
        * Reset the child link of any parent element
        */
       if (so_elem->parent())
         {
           unsigned int c =
             so_elem->parent()->which_child_am_i(so_elem);
           lo_elem->parent()->replace_child(lo_elem, c);
         }
       /*
        * Copy as much data to the new element as makes sense
        */
       lo_elem->set_p_level(so_elem->p_level());
       lo_elem->set_refinement_flag(so_elem->refinement_flag());
       lo_elem->set_p_refinement_flag(so_elem->p_refinement_flag());
 #endif
       libmesh_assert_equal_to (lo_elem->n_vertices(), so_elem->n_vertices());
       /*
        * By definition the vertices of the linear and
        * second order element are identically numbered.
        * transfer these.
        */
       for (unsigned int v=0; v < so_elem->n_vertices(); v++)
         {
           lo_elem->set_node(v) = so_elem->get_node(v);
           node_touched_by_me[lo_elem->node(v)] = true;
         }
       libmesh_assert_equal_to (lo_elem->n_sides(), so_elem->n_sides());
       std::vector<boundary_id_type> bndry_ids;
       for (unsigned short s=0; s<so_elem->n_sides(); s++)
         {
           this->get_boundary_info().raw_boundary_ids (so_elem, s, bndry_ids);
           this->get_boundary_info().add_side (lo_elem, s, bndry_ids);
         }
       /*
        * The new first-order element is ready.
        * Inserting it into the mesh will replace and delete
        * the second-order element.
        */
       lo_elem->set_id(so_elem->id());
 #ifdef LIBMESH_ENABLE_UNIQUE_ID
       lo_elem->set_unique_id() = so_elem->unique_id();
 #endif
       lo_elem->processor_id() = so_elem->processor_id();
       lo_elem->subdomain_id() = so_elem->subdomain_id();
       this->insert_elem(lo_elem);
     }
   const MeshBase::node_iterator nd_end = this->nodes_end();
   MeshBase::node_iterator nd = this->nodes_begin();
   while (nd != nd_end)
     {
       Node * the_node = *nd;
       ++nd;
       if (!node_touched_by_me[the_node->id()])
         this->delete_node(the_node);
     }
   STOP_LOG("all_first_order()", "Mesh");
   // On hanging nodes that used to also be second order nodes, we
   // might now have an invalid nodal processor_id()
   Partitioner::set_node_processor_ids(*this);
   // delete or renumber nodes, etc
   this->prepare_for_use(/*skip_renumber =*/ false);
 }
void libMesh::UnstructuredMesh::all_second_order (const bool full_ordered = true) virtual
Converts a (conforming, non-refined) mesh with linear elements into a mesh with second-order elements. For example, a mesh consisting of Tet4 will be converted to a mesh with Tet10 etc. Note that for some elements like Hex8 there exist two higher order equivalents, Hex20 and Hex27. When full_ordered is true (default), then Hex27 is built. Otherwise, Hex20 is built. The same holds obviously for Quad4, Prism6 ...
Loop over the low-ordered elements in the elements vector. First make sure they _are indeed low-order, and then replace them with an equivalent second-order element. Don't forget to delete the low-order element, or else it will leak!
If the linear element had any boundary conditions they should be transfered to the second-order element. The old boundary conditions will be removed from the BoundaryInfo data structure by insert_elem.
Also, prepare_for_use() will reconstruct most of our neighbor links, but if we have any remote_elem links in a distributed mesh, they need to be preserved. We do that in the same loop here.
Implements libMesh::MeshBase.
Definition at line 447 of file mesh_modification.C.
References libMesh::MeshBase::_is_prepared, libMesh::MeshBase::add_point(), libMesh::BoundaryInfo::add_side(), libMesh::Elem::build(), libMesh::ParallelObject::comm(), libMesh::Elem::default_order(), libMesh::MeshBase::elements_begin(), libMesh::MeshBase::elements_end(), libMesh::FIRST, libMesh::MeshBase::get_boundary_info(), libMesh::Elem::get_node(), libMesh::DofObject::id(), libMesh::MeshBase::insert_elem(), libMesh::DofObject::invalid_id, libMesh::MeshBase::is_serial(), libMesh::Elem::level(), libMesh::libmesh_assert(), libMesh::MeshCommunication::make_nodes_parallel_consistent(), libMesh::Parallel::Communicator::max(), libMesh::MeshBase::mesh_dimension(), libMesh::MeshBase::n_elem(), libMesh::MeshBase::n_nodes(), libMesh::Elem::n_sides(), libMesh::Elem::n_vertices(), libMesh::Elem::neighbor(), libMesh::MeshBase::node(), libMesh::MeshBase::point(), libMesh::MeshBase::prepare_for_use(), libMesh::ParallelObject::processor_id(), libMesh::DofObject::processor_id(), libMesh::BoundaryInfo::raw_boundary_ids(), libMesh::Real, libMesh::remote_elem, libMesh::MeshBase::renumber_nodes_and_elements(), libMesh::MeshBase::reserve_nodes(), libMesh::Elem::second_order_equivalent_type(), libMesh::START_LOG(), libMesh::STOP_LOG(), libMesh::Elem::subdomain_id(), libMesh::Elem::type(), and libMesh::DofObject::unique_id().
Referenced by libMesh::MeshTools::Generation::build_cube().
 {
   // This function must be run on all processors at once
   parallel_object_only();
   /*
    * when the mesh is not prepared,
    * at least renumber the nodes and
    * elements, so that the node ids
    * are correct
    */
   if (!this->_is_prepared)
     this->renumber_nodes_and_elements ();
   /*
    * If the mesh is empty
    * then we have nothing to do
    */
   if (!this->n_elem())
     return;
   /*
    * If the mesh is already second order
    * then we have nothing to do.
    * We have to test for this in a round-about way to avoid
    * a bug on distributed parallel meshes with more processors
    * than elements.
    */
   bool already_second_order = false;
   if (this->elements_begin() != this->elements_end() &&
       (*(this->elements_begin()))->default_order() != FIRST)
     already_second_order = true;
   this->comm().max(already_second_order);
   if (already_second_order)
     return;
   START_LOG("all_second_order()", "Mesh");
   /*
    * this map helps in identifying second order
    * nodes.  Namely, a second-order node:
    * - edge node
    * - face node
    * - bubble node
    * is uniquely defined through a set of adjacent
    * vertices.  This set of adjacent vertices is
    * used to identify already added higher-order
    * nodes.  We are safe to use node id's since we
    * make sure that these are correctly numbered.
    */
   std::map<std::vector<dof_id_type>, Node *> adj_vertices_to_so_nodes;
   /*
    * for speed-up of the \p add_point() method, we
    * can reserve memory.  Guess the number of additional
    * nodes for different dimensions
    */
   switch (this->mesh_dimension())
     {
     case 1:
       /*
        * in 1D, there can only be order-increase from Edge2
        * to Edge3.  Something like 1/2 of n_nodes() have
        * to be added
        */
       this->reserve_nodes(static_cast<unsigned int>
                           (1.5*static_cast<double>(this->n_nodes())));
       break;
     case 2:
       /*
        * in 2D, either refine from Tri3 to Tri6 (double the nodes)
        * or from Quad4 to Quad8 (again, double) or Quad9 (2.25 that much)
        */
       this->reserve_nodes(static_cast<unsigned int>
                           (2*static_cast<double>(this->n_nodes())));
       break;
     case 3:
       /*
        * in 3D, either refine from Tet4 to Tet10 (factor = 2.5) up to
        * Hex8 to Hex27 (something  > 3).  Since in 3D there _are_ already
        * quite some nodes, and since we do not want to overburden the memory by
        * a too conservative guess, use the lower bound
        */
       this->reserve_nodes(static_cast<unsigned int>
                           (2.5*static_cast<double>(this->n_nodes())));
       break;
     default:
       // Hm?
       libmesh_error_msg("Unknown mesh dimension " << this->mesh_dimension());
     }
   /*
    * form a vector that will hold the node id's of
    * the vertices that are adjacent to the son-th
    * second-order node.  Pull this outside of the
    * loop so that silly compilers don't repeatedly
    * create and destroy the vector.
    */
   std::vector<dof_id_type> adjacent_vertices_ids;
   const_element_iterator endit = elements_end();
   for (const_element_iterator it = elements_begin();
        it != endit; ++it)
     {
       // the linear-order element
       const Elem * lo_elem = *it;
       libmesh_assert(lo_elem);
       // make sure it is linear order
       if (lo_elem->default_order() != FIRST)
         libmesh_error_msg("ERROR: This is not a linear element: type=" << lo_elem->type());
       // this does _not_ work for refined elements
       libmesh_assert_equal_to (lo_elem->level (), 0);
       /*
        * build the second-order equivalent, add to
        * the new_elements list.  Note that this here
        * is the only point where \p full_ordered
        * is necessary.  The remaining code works well
        * for either type of seconrd-order equivalent, e.g.
        * Hex20 or Hex27, as equivalents for Hex8
        */
       Elem * so_elem =
         Elem::build (Elem::second_order_equivalent_type(lo_elem->type(),
                                                         full_ordered) ).release();
       libmesh_assert_equal_to (lo_elem->n_vertices(), so_elem->n_vertices());
       /*
        * By definition the vertices of the linear and
        * second order element are identically numbered.
        * transfer these.
        */
       for (unsigned int v=0; v < lo_elem->n_vertices(); v++)
         so_elem->set_node(v) = lo_elem->get_node(v);
       /*
        * Now handle the additional mid-side nodes.  This
        * is simply handled through a map that remembers
        * the already-added nodes.  This map maps the global
        * ids of the vertices (that uniquely define this
        * higher-order node) to the new node.
        * Notation: son = second-order node
        */
       const unsigned int son_begin = so_elem->n_vertices();
       const unsigned int son_end   = so_elem->n_nodes();
       for (unsigned int son=son_begin; son<son_end; son++)
         {
           const unsigned int n_adjacent_vertices =
             so_elem->n_second_order_adjacent_vertices(son);
           adjacent_vertices_ids.resize(n_adjacent_vertices);
           for (unsigned int v=0; v<n_adjacent_vertices; v++)
             adjacent_vertices_ids[v] =
               so_elem->node( so_elem->second_order_adjacent_vertex(son,v) );
           /*
            * \p adjacent_vertices_ids is now in order of the current
            * side.  sort it, so that comparisons  with the
            * \p adjacent_vertices_ids created through other elements'
            * sides can match
            */
           std::sort(adjacent_vertices_ids.begin(),
                     adjacent_vertices_ids.end());
           // does this set of vertices already has a mid-node added?
           std::pair<std::map<std::vector<dof_id_type>, Node *>::iterator,
                     std::map<std::vector<dof_id_type>, Node *>::iterator>
             pos = adj_vertices_to_so_nodes.equal_range (adjacent_vertices_ids);
           // no, not added yet
           if (pos.first == pos.second)
             {
               /*
                * for this set of vertices, there is no
                * second_order node yet.  Add it.
                *
                * compute the location of the new node as
                * the average over the adjacent vertices.
                */
               Point new_location = this->point(adjacent_vertices_ids[0]);
               for (unsigned int v=1; v<n_adjacent_vertices; v++)
                 new_location += this->point(adjacent_vertices_ids[v]);
               new_location /= static_cast<Real>(n_adjacent_vertices);
               /* Add the new point to the mesh, giving it a globally
                * well-defined processor id.
                */
               Node * so_node = this->add_point
                 (new_location, DofObject::invalid_id,
                  this->node(adjacent_vertices_ids[0]).processor_id());
               /*
                * insert the new node with its defining vertex
                * set into the map, and relocate pos to this
                * new entry, so that the so_elem can use
                * \p pos for inserting the node
                */
               adj_vertices_to_so_nodes.insert(pos.first,
                                               std::make_pair(adjacent_vertices_ids,
                                                              so_node));
               so_elem->set_node(son) = so_node;
             }
           // yes, already added.
           else
             {
               libmesh_assert(pos.first->second);
               so_elem->set_node(son) = pos.first->second;
             }
         }
       libmesh_assert_equal_to (lo_elem->n_sides(), so_elem->n_sides());
       std::vector<boundary_id_type> bndry_ids;
       for (unsigned short s=0; s<lo_elem->n_sides(); s++)
         {
           this->get_boundary_info().raw_boundary_ids (lo_elem, s, bndry_ids);
           this->get_boundary_info().add_side (so_elem, s, bndry_ids);
           if (lo_elem->neighbor(s) == remote_elem)
             so_elem->set_neighbor(s, const_cast<RemoteElem *>(remote_elem));
         }
       /*
        * The new second-order element is ready.
        * Inserting it into the mesh will replace and delete
        * the first-order element.
        */
       so_elem->set_id(lo_elem->id());
 #ifdef LIBMESH_ENABLE_UNIQUE_ID
       so_elem->set_unique_id() = lo_elem->unique_id();
 #endif
       so_elem->processor_id() = lo_elem->processor_id();
       so_elem->subdomain_id() = lo_elem->subdomain_id();
       this->insert_elem(so_elem);
     }
   // we can clear the map
   adj_vertices_to_so_nodes.clear();
   STOP_LOG("all_second_order()", "Mesh");
   // In a ParallelMesh our ghost node processor ids may be bad,
   // the ids of nodes touching remote elements may be inconsistent,
   // and unique_ids of newly added non-local nodes remain unset.
   // make_nodes_parallel_consistent() will fix all this.
   if (!this->is_serial())
     MeshCommunication().make_nodes_parallel_consistent (*this);
   // renumber nodes, elements etc
   this->prepare_for_use(/*skip_renumber =*/ false);
 }
virtual void libMesh::MeshBase::allgather () inline virtual inherited
Gathers all elements and nodes of the mesh onto every processor
Reimplemented in libMesh::ParallelMesh.
Definition at line 141 of file mesh_base.h.
Referenced by libMesh::EquationSystems::allgather(), and libMesh::MeshSerializer::MeshSerializer().
 {}
void libMesh::MeshBase::allow_renumbering (bool allow) inline inherited
If false is passed in then this mesh will no longer be renumbered when being prepared for use. This may slightly adversely affect performance during subsequent element access, particulary when using a distributed mesh.
Definition at line 589 of file mesh_base.h.
References libMesh::MeshBase::_skip_renumber_nodes_and_elements.
Referenced by copy_nodes_and_elements(), libMesh::AdjointRefinementEstimator::estimate_error(), libMesh::ErrorVector::plot_error(), and libMesh::NameBasedIO::read().
 { _skip_renumber_nodes_and_elements = !allow; }
bool libMesh::MeshBase::allow_renumbering () const inline inherited
Definition at line 590 of file mesh_base.h.
References libMesh::MeshBase::_skip_renumber_nodes_and_elements.
Referenced by copy_nodes_and_elements(), libMesh::MeshBase::prepare_for_use(), and read().
 { return !_skip_renumber_nodes_and_elements; }
virtual element_iterator libMesh::MeshBase::ancestor_elements_begin () pure virtual inherited
Iterate over elements for which elem->ancestor() returns true.
Implemented in libMesh::ParallelMesh, and libMesh::SerialMesh.
virtual const_element_iterator libMesh::MeshBase::ancestor_elements_begin () const pure virtual inherited
Implemented in libMesh::ParallelMesh, and libMesh::SerialMesh.
virtual element_iterator libMesh::MeshBase::ancestor_elements_end () pure virtual inherited
Implemented in libMesh::ParallelMesh, and libMesh::SerialMesh.
virtual const_element_iterator libMesh::MeshBase::ancestor_elements_end () const pure virtual inherited
Implemented in libMesh::ParallelMesh, and libMesh::SerialMesh.
virtual node_iterator libMesh::MeshBase::bid_nodes_begin (boundary_id_type bndry_id) pure virtual inherited
Iterate over nodes for which BoundaryInfo::has_boundary_id(node, bndry_id) returns true.
Implemented in libMesh::ParallelMesh, and libMesh::SerialMesh.
virtual const_node_iterator libMesh::MeshBase::bid_nodes_begin (boundary_id_type bndry_id) const pure virtual inherited
Implemented in libMesh::ParallelMesh, and libMesh::SerialMesh.
virtual node_iterator libMesh::MeshBase::bid_nodes_end (boundary_id_type bndry_id) pure virtual inherited
Implemented in libMesh::ParallelMesh, and libMesh::SerialMesh.
virtual const_node_iterator libMesh::MeshBase::bid_nodes_end (boundary_id_type bndry_id) const pure virtual inherited
Implemented in libMesh::ParallelMesh, and libMesh::SerialMesh.
virtual node_iterator libMesh::MeshBase::bnd_nodes_begin () pure virtual inherited
Iterate over nodes for which BoundaryInfo::n_boundary_ids(node) > 0.
Implemented in libMesh::ParallelMesh, and libMesh::SerialMesh.
virtual const_node_iterator libMesh::MeshBase::bnd_nodes_begin () const pure virtual inherited
Implemented in libMesh::ParallelMesh, and libMesh::SerialMesh.
virtual node_iterator libMesh::MeshBase::bnd_nodes_end () pure virtual inherited
Implemented in libMesh::ParallelMesh, and libMesh::SerialMesh.
virtual const_node_iterator libMesh::MeshBase::bnd_nodes_end () const pure virtual inherited
Implemented in libMesh::ParallelMesh, and libMesh::SerialMesh.
void libMesh::MeshBase::cache_elem_dims () inherited
Search the mesh and cache the different dimenions of the elements present in the mesh. This is done in prepare_for_use(), but can be done manually by other classes after major mesh modifications.
Definition at line 540 of file mesh_base.C.
References libMesh::MeshBase::_elem_dims, libMesh::MeshBase::_spatial_dimension, libMesh::MeshBase::active_elements_begin(), libMesh::MeshBase::active_elements_end(), libMesh::ParallelObject::comm(), end, libMesh::MeshBase::mesh_dimension(), libMesh::MeshBase::node(), libMesh::MeshBase::nodes_begin(), libMesh::MeshBase::nodes_end(), and libMesh::Parallel::Communicator::set_union().
Referenced by libMesh::MeshBase::prepare_for_use().
 {
   // This requires an inspection on every processor
   parallel_object_only();
   // Need to clear _elem_dims first in case all elements of a
   // particular dimension have been deleted.
   _elem_dims.clear();
   const_element_iterator el  = this->active_elements_begin();
   const_element_iterator end = this->active_elements_end();
   for (; el!=end; ++el)
     _elem_dims.insert((*el)->dim());
   // Some different dimension elements may only live on other processors
   this->comm().set_union(_elem_dims);
   // If the largest element dimension found is larger than the current
   // _spatial_dimension, increase _spatial_dimension.
   unsigned int max_dim = this->mesh_dimension();
   if (max_dim > _spatial_dimension)
     _spatial_dimension = cast_int<unsigned char>(max_dim);
   // _spatial_dimension may need to increase from 1->2 or 2->3 if the
   // mesh is full of 1D elements but they are not x-aligned, or the
   // mesh is full of 2D elements but they are not in the x-y plane.
   // If the mesh is x-aligned or x-y planar, we will end up checking
   // every node's coordinates and not breaking out of the loop
   // early...
   if (_spatial_dimension < 3)
     {
       const_node_iterator node_it  = this->nodes_begin();
       const_node_iterator node_end = this->nodes_end();
       for (; node_it != node_end; ++node_it)
         {
           Node & node = **node_it;
           // Note: the exact floating point comparison is intentional,
           // we don't want to get tripped up by tolerances.
           if (node(1) != 0.)
             {
               _spatial_dimension = 2;
 #if LIBMESH_DIM == 2
               // If libmesh is compiled in 2D mode, this is the
               // largest spatial dimension possible so we can break
               // out.
               break;
 #endif
             }
 #if LIBMESH_DIM > 2
           if (node(2) != 0.)
             {
               // Spatial dimension can't get any higher than this, so
               // we can break out.
               _spatial_dimension = 3;
               break;
             }
 #endif
         }
     }
 }
void libMesh::MeshBase::clear () virtual inherited
Deletes all the data that are currently stored.
Reimplemented in libMesh::ParallelMesh, and libMesh::SerialMesh.
Definition at line 238 of file mesh_base.C.
References libMesh::MeshBase::_elem_dims, libMesh::MeshBase::_is_prepared, libMesh::MeshBase::_n_parts, libMesh::BoundaryInfo::clear(), libMesh::MeshBase::clear_point_locator(), and libMesh::MeshBase::get_boundary_info().
Referenced by libMesh::MeshTools::Generation::build_cube(), libMesh::MeshTools::Generation::build_delaunay_square(), libMesh::SerialMesh::clear(), libMesh::ParallelMesh::clear(), libMesh::TriangleWrapper::copy_tri_to_mesh(), create_submesh(), libMesh::AbaqusIO::read(), libMesh::GMVIO::read(), libMesh::ExodusII_IO::read(), libMesh::VTKIO::read(), libMesh::LegacyXdrIO::read_ascii(), libMesh::LegacyXdrIO::read_mesh(), libMesh::OFFIO::read_stream(), libMesh::MatlabIO::read_stream(), libMesh::BoundaryInfo::sync(), libMesh::TriangleInterface::triangulate(), and libMesh::MeshBase::~MeshBase().
 {
   // Reset the number of partitions
   _n_parts = 1;
   // Reset the _is_prepared flag
   _is_prepared = false;
   // Clear boundary information
   this->get_boundary_info().clear();
   // Clear element dimensions
   _elem_dims.clear();
   // Clear our point locator.
   this->clear_point_locator();
 }
void libMesh::MeshBase::clear_point_locator () inherited
Releases the current PointLocator object.
Definition at line 497 of file mesh_base.C.
References libMesh::MeshBase::_point_locator, and libmesh_nullptr.
Referenced by libMesh::MeshBase::clear(), contract(), and libMesh::MeshBase::prepare_for_use().
 {
   _point_locator.reset(libmesh_nullptr);
 }
virtual UniquePtr<MeshBase> libMesh::MeshBase::clone () const pure virtual inherited
Virtual "copy constructor"
Implemented in libMesh::ParallelMesh, and libMesh::SerialMesh.
Referenced by libMesh::ErrorVector::plot_error().
const Parallel::Communicator& libMesh::ParallelObject::comm () const inline inherited
Returns
a reference to the Parallel::Communicator object used by this mesh.
Definition at line 87 of file parallel_object.h.
References libMesh::ParallelObject::_communicator.
Referenced by libMesh::__libmesh_petsc_diff_solver_monitor(), libMesh::__libmesh_petsc_diff_solver_residual(), libMesh::__libmesh_petsc_snes_jacobian(), libMesh::__libmesh_petsc_snes_postcheck(), libMesh::__libmesh_petsc_snes_residual(), libMesh::__libmesh_tao_equality_constraints(), libMesh::__libmesh_tao_equality_constraints_jacobian(), libMesh::__libmesh_tao_gradient(), libMesh::__libmesh_tao_hessian(), libMesh::__libmesh_tao_inequality_constraints(), libMesh::__libmesh_tao_inequality_constraints_jacobian(), libMesh::__libmesh_tao_objective(), libMesh::MeshRefinement::_coarsen_elements(), libMesh::ExactSolution::_compute_error(), libMesh::MetisPartitioner::_do_partition(), libMesh::ParmetisPartitioner::_do_repartition(), libMesh::UniformRefinementEstimator::_estimate_error(), libMesh::BoundaryInfo::_find_id_maps(), libMesh::PetscLinearSolver< T >::_petsc_shell_matrix_get_diagonal(), libMesh::SlepcEigenSolver< T >::_petsc_shell_matrix_get_diagonal(), libMesh::PetscLinearSolver< T >::_petsc_shell_matrix_mult(), libMesh::SlepcEigenSolver< T >::_petsc_shell_matrix_mult(), libMesh::PetscLinearSolver< T >::_petsc_shell_matrix_mult_add(), libMesh::EquationSystems::_read_impl(), libMesh::MeshRefinement::_refine_elements(), libMesh::MeshRefinement::_smooth_flags(), libMesh::ImplicitSystem::add_matrix(), libMesh::System::add_vector(), all_second_order(), libMesh::MeshTools::Modification::all_tri(), libMesh::LaplaceMeshSmoother::allgather_graph(), libMesh::FEMSystem::assemble_qoi(), libMesh::MeshCommunication::assign_global_indices(), libMesh::ParmetisPartitioner::assign_partitioning(), libMesh::DofMap::attach_matrix(), libMesh::MeshTools::bounding_box(), libMesh::EquationSystems::build_solution_vector(), libMesh::MeshBase::cache_elem_dims(), libMesh::System::calculate_norm(), libMesh::Nemesis_IO_Helper::compute_num_global_elem_blocks(), libMesh::Nemesis_IO_Helper::compute_num_global_nodesets(), libMesh::Nemesis_IO_Helper::compute_num_global_sidesets(), libMesh::Problem_Interface::computeF(), libMesh::Problem_Interface::computeJacobian(), libMesh::Problem_Interface::computePreconditioner(), libMesh::MeshTools::correct_node_proc_ids(), libMesh::MeshRefinement::create_parent_error_vector(), libMesh::MeshCommunication::delete_remote_elements(), libMesh::DofMap::distribute_dofs(), DMlibMeshFunction(), DMlibMeshJacobian(), DMlibMeshSetSystem_libMesh(), DMVariableBounds_libMesh(), libMesh::MeshRefinement::eliminate_unrefined_patches(), libMesh::WeightedPatchRecoveryErrorEstimator::estimate_error(), libMesh::JumpErrorEstimator::estimate_error(), libMesh::PatchRecoveryErrorEstimator::estimate_error(), libMesh::AdjointRefinementEstimator::estimate_error(), libMesh::MeshRefinement::flag_elements_by_elem_fraction(), libMesh::MeshRefinement::flag_elements_by_error_fraction(), libMesh::MeshRefinement::flag_elements_by_nelem_target(), libMesh::for(), libMesh::CondensedEigenSystem::get_eigenpair(), libMesh::ImplicitSystem::get_linear_solver(), libMesh::EquationSystems::get_solution(), libMesh::LocationMap< T >::init(), libMesh::TopologyMap::init(), libMesh::TimeSolver::init(), libMesh::SystemSubsetBySubdomain::init(), libMesh::EigenSystem::init_data(), libMesh::EigenSystem::init_matrices(), libMesh::ParmetisPartitioner::initialize(), libMesh::OptimizationSystem::initialize_equality_constraints_storage(), libMesh::OptimizationSystem::initialize_inequality_constraints_storage(), libMesh::MeshTools::libmesh_assert_valid_dof_ids(), libMesh::MeshTools::libmesh_assert_valid_neighbors(), libMesh::ParallelMesh::libmesh_assert_valid_parallel_flags(), libMesh::ParallelMesh::libmesh_assert_valid_parallel_object_ids(), libMesh::ParallelMesh::libmesh_assert_valid_parallel_p_levels(), libMesh::MeshTools::libmesh_assert_valid_procids< Elem >(), libMesh::MeshTools::libmesh_assert_valid_procids< Node >(), libMesh::MeshTools::libmesh_assert_valid_refinement_flags(), libMesh::MeshTools::libmesh_assert_valid_unique_ids(), libMesh::MeshRefinement::limit_level_mismatch_at_edge(), libMesh::MeshRefinement::limit_level_mismatch_at_node(), libMesh::MeshRefinement::limit_overrefined_boundary(), libMesh::MeshRefinement::limit_underrefined_boundary(), libMesh::MeshRefinement::make_coarsening_compatible(), libMesh::MeshCommunication::make_elems_parallel_consistent(), libMesh::MeshRefinement::make_flags_parallel_consistent(), libMesh::MeshCommunication::make_node_ids_parallel_consistent(), libMesh::MeshCommunication::make_node_proc_ids_parallel_consistent(), libMesh::MeshCommunication::make_node_unique_ids_parallel_consistent(), libMesh::MeshCommunication::make_nodes_parallel_consistent(), libMesh::MeshCommunication::make_p_levels_parallel_consistent(), libMesh::MeshRefinement::make_refinement_compatible(), libMesh::FEMSystem::mesh_position_set(), libMesh::MeshSerializer::MeshSerializer(), libMesh::ParallelMesh::n_active_elem(), libMesh::MeshTools::n_active_levels(), libMesh::BoundaryInfo::n_boundary_conds(), libMesh::BoundaryInfo::n_edge_conds(), libMesh::CondensedEigenSystem::n_global_non_condensed_dofs(), libMesh::MeshTools::n_levels(), libMesh::BoundaryInfo::n_nodeset_conds(), libMesh::MeshTools::n_p_levels(), libMesh::ParallelMesh::parallel_max_elem_id(), libMesh::ParallelMesh::parallel_max_node_id(), libMesh::SerialMesh::parallel_max_unique_id(), libMesh::ParallelMesh::parallel_max_unique_id(), libMesh::ParallelMesh::parallel_n_elem(), libMesh::ParallelMesh::parallel_n_nodes(), libMesh::Partitioner::partition(), libMesh::Partitioner::partition_unpartitioned_elements(), libMesh::petsc_auto_fieldsplit(), libMesh::System::point_gradient(), libMesh::System::point_hessian(), libMesh::System::point_value(), libMesh::MeshBase::prepare_for_use(), libMesh::System::project_vector(), libMesh::Nemesis_IO::read(), libMesh::XdrIO::read(), libMesh::System::read_header(), libMesh::System::read_legacy_data(), libMesh::System::read_SCALAR_dofs(), libMesh::XdrIO::read_serialized_bc_names(), libMesh::XdrIO::read_serialized_bcs(), libMesh::System::read_serialized_blocked_dof_objects(), libMesh::XdrIO::read_serialized_connectivity(), libMesh::System::read_serialized_data(), libMesh::XdrIO::read_serialized_nodes(), libMesh::XdrIO::read_serialized_nodesets(), libMesh::XdrIO::read_serialized_subdomain_names(), libMesh::System::read_serialized_vector(), libMesh::MeshBase::recalculate_n_partitions(), libMesh::ParallelMesh::renumber_dof_objects(), libMesh::Partitioner::set_node_processor_ids(), libMesh::DofMap::set_nonlocal_dof_objects(), libMesh::LaplaceMeshSmoother::smooth(), libMesh::MeshBase::subdomain_ids(), libMesh::BoundaryInfo::sync(), libMesh::Parallel::sync_element_data_by_parent_id(), libMesh::Parallel::sync_node_data_by_element_id(), libMesh::MeshRefinement::test_level_one(), libMesh::MeshRefinement::test_unflagged(), libMesh::MeshTools::total_weight(), libMesh::NameBasedIO::write(), libMesh::CheckpointIO::write(), libMesh::XdrIO::write(), libMesh::LegacyXdrIO::write_mesh(), libMesh::System::write_SCALAR_dofs(), libMesh::XdrIO::write_serialized_bcs(), libMesh::System::write_serialized_blocked_dof_objects(), libMesh::XdrIO::write_serialized_connectivity(), libMesh::XdrIO::write_serialized_nodes(), libMesh::XdrIO::write_serialized_nodesets(), and libMesh::DivaIO::write_stream().
   { return _communicator; }
bool libMesh::UnstructuredMesh::contract () virtual
Delete subactive (i.e. children of coarsened) elements. This removes all elements descended from currently active elements in the mesh.
Implements libMesh::MeshBase.
Definition at line 775 of file unstructured_mesh.C.
References libMesh::Elem::active(), libMesh::Elem::ancestor(), libMesh::MeshBase::clear_point_locator(), libMesh::Elem::contract(), libMesh::MeshBase::delete_elem(), libMesh::MeshBase::elements_begin(), libMesh::MeshBase::elements_end(), end, libMesh::libmesh_assert(), libmesh_nullptr, libMesh::Elem::parent(), libMesh::MeshBase::renumber_nodes_and_elements(), libMesh::START_LOG(), libMesh::STOP_LOG(), and libMesh::Elem::subactive().
 {
   START_LOG ("contract()", "Mesh");
   // Flag indicating if this call actually changes the mesh
   bool mesh_changed = false;
   element_iterator in        = elements_begin();
   const element_iterator end = elements_end();
 #ifdef DEBUG
   for ( ; in != end; ++in)
     if (*in != libmesh_nullptr)
       {
         Elem * el = *in;
         libmesh_assert(el->active() || el->subactive() || el->ancestor());
       }
   in = elements_begin();
 #endif
   // Loop over the elements.
   for ( ; in != end; ++in)
     if (*in != libmesh_nullptr)
       {
         Elem * el = *in;
         // Delete all the subactive ones
         if (el->subactive())
           {
             // No level-0 element should be subactive.
             // Note that we CAN'T test elem->level(), as that
             // touches elem->parent()->dim(), and elem->parent()
             // might have already been deleted!
             libmesh_assert(el->parent());
             // Delete the element
             // This just sets a pointer to NULL, and doesn't
             // invalidate any iterators
             this->delete_elem(el);
             // the mesh has certainly changed
             mesh_changed = true;
           }
         else
           {
             // Compress all the active ones
             if (el->active())
               el->contract();
             else
               libmesh_assert (el->ancestor());
           }
       }
   // Strip any newly-created NULL voids out of the element array
   this->renumber_nodes_and_elements();
   // FIXME: Need to understand why deleting subactive children
   // invalidates the point locator.  For now we will clear it explicitly
   this->clear_point_locator();
   STOP_LOG ("contract()", "Mesh");
   return mesh_changed;
 }
void libMesh::UnstructuredMesh::copy_nodes_and_elements (const UnstructuredMesh & other_mesh, const bool skip_find_neighbors = false) virtual
Deep copy of another unstructured mesh class (used by subclass copy constructors)
Definition at line 73 of file unstructured_mesh.C.
References libMesh::MeshBase::_elem_dims, libMesh::MeshBase::_is_prepared, libMesh::MeshBase::_n_parts, libMesh::Elem::add_child(), libMesh::MeshBase::add_elem(), libMesh::MeshBase::add_point(), libMesh::MeshBase::allow_renumbering(), libMesh::Elem::build(), libMesh::Elem::child(), libMesh::MeshBase::elem(), libMesh::MeshBase::elements_begin(), libMesh::MeshBase::elements_end(), end, equal(), libMesh::Elem::has_children(), libMesh::DofObject::id(), libMesh::libmesh_assert(), libMesh::MeshTools::libmesh_assert_valid_amr_elem_ids(), libmesh_nullptr, libMesh::Elem::n_children(), libMesh::MeshBase::n_elem(), libMesh::Elem::n_neighbors(), libMesh::MeshBase::n_nodes(), libMesh::Elem::n_sides(), libMesh::Elem::neighbor(), libMesh::Elem::node(), libMesh::MeshBase::node(), libMesh::MeshBase::nodes_begin(), libMesh::MeshBase::nodes_end(), libMesh::Elem::p_level(), libMesh::Elem::p_refinement_flag(), libMesh::Elem::parent(), libMesh::MeshBase::prepare_for_use(), libMesh::DofObject::processor_id(), libMesh::Elem::refinement_flag(), libMesh::remote_elem, libMesh::MeshBase::reserve_elem(), libMesh::MeshBase::reserve_nodes(), libMesh::Elem::set_neighbor(), libMesh::DofObject::set_unique_id(), libMesh::MeshBase::skip_partitioning(), libMesh::Elem::subdomain_id(), libMesh::Elem::type(), libMesh::DofObject::unique_id(), and libMesh::Elem::which_child_am_i().
Referenced by libMesh::ParallelMesh::ParallelMesh(), libMesh::SerialMesh::SerialMesh(), and libMesh::SerialMesh::stitching_helper().
 {
   // We're assuming our subclass data needs no copy
   libmesh_assert_equal_to (_n_parts, other_mesh._n_parts);
   libmesh_assert (std::equal(_elem_dims.begin(), _elem_dims.end(), other_mesh._elem_dims.begin()));
   libmesh_assert_equal_to (_is_prepared, other_mesh._is_prepared);
   // We're assuming the other mesh has proper element number ordering,
   // so that we add parents before their children.
 #ifdef DEBUG
   MeshTools::libmesh_assert_valid_amr_elem_ids(other_mesh);
 #endif
   //Copy in Nodes
   {
     //Preallocate Memory if necessary
     this->reserve_nodes(other_mesh.n_nodes());
     const_node_iterator it = other_mesh.nodes_begin();
     const_node_iterator end = other_mesh.nodes_end();
     for (; it != end; ++it)
       {
         const Node * oldn = *it;
         // Add new nodes in old node Point locations
 #ifdef LIBMESH_ENABLE_UNIQUE_ID
         Node *newn =
 #endif
           this->add_point(*oldn, oldn->id(), oldn->processor_id());
 #ifdef LIBMESH_ENABLE_UNIQUE_ID
         newn->set_unique_id() = oldn->unique_id();
 #endif
       }
   }
   //Copy in Elements
   {
     //Preallocate Memory if necessary
     this->reserve_elem(other_mesh.n_elem());
     // Declare a map linking old and new elements, needed to copy the neighbor lists
     std::map<const Elem *, Elem *> old_elems_to_new_elems;
     // Loop over the elements
     MeshBase::const_element_iterator it = other_mesh.elements_begin();
     const MeshBase::const_element_iterator end = other_mesh.elements_end();
     // FIXME: Where do we set element IDs??
     for (; it != end; ++it)
       {
         //Look at the old element
         const Elem * old = *it;
         //Build a new element
         Elem * newparent = old->parent() ?
           this->elem(old->parent()->id()) : libmesh_nullptr;
         UniquePtr<Elem> ap = Elem::build(old->type(), newparent);
         Elem * el = ap.release();
         el->subdomain_id() = old->subdomain_id();
         for (unsigned int s=0; s != old->n_sides(); ++s)
           if (old->neighbor(s) == remote_elem)
             el->set_neighbor(s, const_cast<RemoteElem *>(remote_elem));
 #ifdef LIBMESH_ENABLE_AMR
         if (old->has_children())
           for (unsigned int c=0; c != old->n_children(); ++c)
             if (old->child(c) == remote_elem)
               el->add_child(const_cast<RemoteElem *>(remote_elem), c);
         //Create the parent's child pointers if necessary
         if (newparent)
           {
             unsigned int oldc = old->parent()->which_child_am_i(old);
             newparent->add_child(el, oldc);
           }
         // Copy the refinement flags
         el->set_refinement_flag(old->refinement_flag());
         // Use hack_p_level since we may not have sibling elements
         // added yet
         el->hack_p_level(old->p_level());
         el->set_p_refinement_flag(old->p_refinement_flag());
 #endif // #ifdef LIBMESH_ENABLE_AMR
         //Assign all the nodes
         for(unsigned int i=0;i<el->n_nodes();i++)
           el->set_node(i) = &this->node(old->node(i));
         // And start it off in the same subdomain
         el->processor_id() = old->processor_id();
         // Give it the same ids
         el->set_id(old->id());
 #ifdef LIBMESH_ENABLE_UNIQUE_ID
         el->set_unique_id() = old->unique_id();
 #endif
         //Hold onto it
         if(!skip_find_neighbors)
           {
             this->add_elem(el);
           }
         else
           {
             Elem * new_el = this->add_elem(el);
             old_elems_to_new_elems[old] = new_el;
           }
         // Add the link between the original element and this copy to the map
         if(skip_find_neighbors)
           old_elems_to_new_elems[old] = el;
       }
     // Loop (again) over the elements to fill in the neighbors
     if(skip_find_neighbors)
       {
         it = other_mesh.elements_begin();
         for (; it != end; ++it)
           {
             Elem * old_elem = *it;
             Elem * new_elem = old_elems_to_new_elems[old_elem];
             for (unsigned int s=0; s != old_elem->n_neighbors(); ++s)
               {
                 const Elem * old_neighbor = old_elem->neighbor(s);
                 Elem * new_neighbor = old_elems_to_new_elems[old_neighbor];
                 new_elem->set_neighbor(s, new_neighbor);
               }
           }
       }
   }
   //Finally prepare the new Mesh for use.  Keep the same numbering and
   //partitioning but also the same renumbering and partitioning
   //policies as our source mesh.
   this->allow_renumbering(false);
   this->skip_partitioning(true);
   this->prepare_for_use(false, skip_find_neighbors);
   this->allow_renumbering(other_mesh.allow_renumbering());
   this->skip_partitioning(other_mesh.skip_partitioning());
 }
void libMesh::UnstructuredMesh::create_pid_mesh (UnstructuredMesh & pid_mesh, const processor_id_type pid) const
Generates a new mesh containing all the elements which are assigned to processor pid. This mesh is written to the pid_mesh reference which you must create and pass to the function.
Definition at line 654 of file unstructured_mesh.C.
References libMesh::MeshBase::active_pid_elements_begin(), libMesh::MeshBase::active_pid_elements_end(), create_submesh(), libMesh::ParallelObject::n_processors(), and libMesh::out.
 {
   // Issue a warning if the number the number of processors
   // currently available is less that that requested for
   // partitioning.  This is not necessarily an error since
   // you may run on one processor and still partition the
   // mesh into several partitions.
 #ifdef DEBUG
   if (this->n_processors() < pid)
     {
       libMesh::out << "WARNING:  You are creating a "
                    << "mesh for a processor id (="
                    << pid
                    << ") greater than "
                    << "the number of processors available for "
                    << "the calculation. (="
                    << this->n_processors()
                    << ")."
                    << std::endl;
     }
 #endif
   // Create iterators to loop over the list of elements
   //   const_active_pid_elem_iterator       it(this->elements_begin(),   pid);
   //   const const_active_pid_elem_iterator it_end(this->elements_end(), pid);
   const_element_iterator       it     = this->active_pid_elements_begin(pid);
   const const_element_iterator it_end = this->active_pid_elements_end(pid);
   this->create_submesh (pid_mesh, it, it_end);
 }
void libMesh::UnstructuredMesh::create_submesh (UnstructuredMesh & new_mesh, const_element_iterator & it, const const_element_iterator & it_end) const
Constructs a mesh called "new_mesh" from the current mesh by iterating over the elements between it and it_end and adding them to the new mesh.
Definition at line 694 of file unstructured_mesh.C.
References libMesh::MeshBase::add_elem(), libMesh::MeshBase::add_point(), libMesh::BoundaryInfo::add_side(), libMesh::BoundaryInfo::boundary_ids(), libMesh::Elem::build(), libMesh::MeshBase::clear(), libMesh::MeshBase::delete_remote_elements(), libMesh::MeshBase::get_boundary_info(), libMesh::Elem::get_node(), libMesh::DofObject::id(), libMesh::MeshBase::is_serial(), libMesh::libmesh_assert(), libMesh::MeshBase::n_elem(), libMesh::MeshBase::n_nodes(), libMesh::Elem::n_nodes(), libMesh::Elem::n_sides(), libMesh::Elem::node(), libMesh::MeshBase::node_ptr(), libMesh::Elem::point(), libMesh::MeshBase::prepare_for_use(), libMesh::DofObject::processor_id(), libMesh::MeshBase::query_node_ptr(), libMesh::DofObject::set_id(), libMesh::Elem::set_node(), libMesh::DofObject::set_unique_id(), libMesh::Elem::subdomain_id(), libMesh::Elem::type(), and libMesh::DofObject::unique_id().
Referenced by create_pid_mesh().
 {
   // Just in case the subdomain_mesh already has some information
   // in it, get rid of it.
   new_mesh.clear();
   // If we're not serial, our submesh isn't either.
   // There are no remote elements to delete on an empty mesh, but
   // calling the method to do so marks the mesh as parallel.
   if (!this->is_serial())
     new_mesh.delete_remote_elements();
   // Fail if (*this == new_mesh), we cannot create a submesh inside ourself!
   // This may happen if the user accidently passes the original mesh into
   // this function!  We will check this by making sure we did not just
   // clear ourself.
   libmesh_assert_not_equal_to (this->n_nodes(), 0);
   libmesh_assert_not_equal_to (this->n_elem(), 0);
   // Container to catch boundary IDs handed back by BoundaryInfo
   std::vector<boundary_id_type> bc_ids;
   for (; it != it_end; ++it)
     {
       const Elem * old_elem = *it;
       // Add an equivalent element type to the new_mesh.
       // Copy ids for this element.
       Elem * new_elem = Elem::build(old_elem->type()).release();
       new_elem->set_id() = old_elem->id();
 #ifdef LIBMESH_ENABLE_UNIQUE_ID
       new_elem->set_unique_id() = old_elem->unique_id();
 #endif
       new_elem->subdomain_id() = old_elem->subdomain_id();
       new_elem->processor_id() = old_elem->processor_id();
       new_mesh.add_elem (new_elem);
       libmesh_assert(new_elem);
       // Loop over the nodes on this element.
       for (unsigned int n=0; n<old_elem->n_nodes(); n++)
         {
           const dof_id_type node_id = old_elem->node(n);
           // Add this node to the new mesh if it's not there already
           if (!new_mesh.query_node_ptr(node_id))
             {
 #ifdef LIBMESH_ENABLE_UNIQUE_ID
               Node *newn =
 #endif
                 new_mesh.add_point (old_elem->point(n),
                                     node_id,
                                     old_elem->get_node(n)->processor_id());
 #ifdef LIBMESH_ENABLE_UNIQUE_ID
               newn->set_unique_id() = old_elem->get_node(n)->unique_id();
 #endif
             }
           // Define this element's connectivity on the new mesh
           new_elem->set_node(n) = new_mesh.node_ptr(node_id);
         }
       // Maybe add boundary conditions for this element
       for (unsigned short s=0; s<old_elem->n_sides(); s++)
         {
           this->get_boundary_info().boundary_ids(old_elem, s, bc_ids);
           new_mesh.get_boundary_info().add_side (new_elem, s, bc_ids);
         }
     } // end loop over elements
   // Prepare the new_mesh for use
   new_mesh.prepare_for_use(/*skip_renumber =*/false);
 }
virtual void libMesh::MeshBase::delete_elem (Elem * e) pure virtual inherited
Removes element e from the mesh. Note that calling this method may produce isolated nodes, i.e. nodes not connected to any element. This method must be implemented in derived classes in such a way that it does not invalidate element iterators.
Users should call MeshBase::prepare_for_use() after elements are added to and/or deleted from the mesh.
Implemented in libMesh::ParallelMesh, and libMesh::SerialMesh.
Referenced by libMesh::MeshTools::Modification::all_tri(), libMesh::MeshTools::Generation::build_cube(), contract(), libMesh::TetGenMeshInterface::delete_2D_hull_elements(), libMesh::MeshTools::Modification::flatten(), libMesh::TetGenMeshInterface::pointset_convexhull(), libMesh::AbaqusIO::read(), and libMesh::UNVIO::read_implementation().
virtual void libMesh::MeshBase::delete_node (Node * n) pure virtual inherited
Removes the Node n from the mesh.
Implemented in libMesh::ParallelMesh, and libMesh::SerialMesh.
Referenced by all_first_order().
virtual void libMesh::MeshBase::delete_remote_elements () inline virtual inherited
When supported, deletes all nonlocal elements of the mesh except for "ghosts" which touch a local element, and deletes all nodes which are not part of a local or ghost element
Reimplemented in libMesh::ParallelMesh.
Definition at line 148 of file mesh_base.h.
Referenced by libMesh::MeshTools::Generation::build_extrusion(), create_submesh(), libMesh::EquationSystems::init(), libMesh::MeshBase::prepare_for_use(), libMesh::Nemesis_IO::read(), libMesh::BoundaryInfo::sync(), and libMesh::MeshSerializer::~MeshSerializer().
 {}
void libMesh::MeshBase::detect_interior_parents () inherited
Search the mesh for elements that have a neighboring element of dim+1 and set that element as the interior parent
Definition at line 604 of file mesh_base.C.
References libMesh::MeshBase::active_elements_begin(), libMesh::MeshBase::active_elements_end(), libMesh::Elem::dim(), libMesh::MeshBase::elem(), libMesh::MeshBase::elem_dimensions(), libMesh::MeshBase::elements_begin(), end, libMesh::DofObject::id(), libMesh::Elem::interior_parent(), libMesh::MeshBase::max_elem_id(), libMesh::Elem::n_vertices(), libMesh::Elem::node(), and libMesh::Elem::set_interior_parent().
Referenced by libMesh::MeshBase::prepare_for_use().
 {
   // This requires an inspection on every processor
   parallel_object_only();
   // Check if the mesh contains mixed dimensions. If so, then set interior parents, otherwise return.
   if (this->elem_dimensions().size() == 1)
     return;
   //This map will be used to set interior parents
   LIBMESH_BEST_UNORDERED_MAP<dof_id_type, std::vector<dof_id_type> > node_to_elem;
   const_element_iterator el  = this->active_elements_begin();
   const_element_iterator end = this->active_elements_end();
   for (; el!=end; ++el)
     {
       const Elem * elem = *el;
       // Populating the node_to_elem map, same as MeshTools::build_nodes_to_elem_map
       for (unsigned int n=0; n<elem->n_vertices(); n++)
         {
           libmesh_assert_less (elem->id(), this->max_elem_id());
           node_to_elem[elem->node(n)].push_back(elem->id());
         }
     }
   // Automatically set interior parents
   el = this->elements_begin();
   for (; el!=end; ++el)
     {
       Elem * element = *el;
       // Ignore an 3D element or an element that already has an interior parent
       if (element->dim()>=LIBMESH_DIM || element->interior_parent())
         continue;
       // Start by generating a SET of elements that are dim+1 to the current
       // element at each vertex of the current element, thus ignoring interior nodes.
       // If one of the SET of elements is empty, then we will not have an interior parent
       // since an interior parent must be connected to all vertices of the current element
       std::vector< std::set<dof_id_type> > neighbors( element->n_vertices() );
       bool found_interior_parents = false;
       for (dof_id_type n=0; n < element->n_vertices(); n++)
         {
           std::vector<dof_id_type> & element_ids = node_to_elem[element->node(n)];
           for (std::vector<dof_id_type>::iterator e_it = element_ids.begin();
                e_it != element_ids.end(); e_it++)
             {
               dof_id_type eid = *e_it;
               if (this->elem(eid)->dim() == element->dim()+1)
                 neighbors[n].insert(eid);
             }
           if (neighbors[n].size()>0)
             {
               found_interior_parents = true;
             }
           else
             {
               // We have found an empty set, no reason to continue
               // Ensure we set this flag to false before the break since it could have
               // been set to true for previous vertex
               found_interior_parents = false;
               break;
             }
         }
       // If we have successfully generated a set of elements for each vertex, we will compare
       // the set for vertex 0 will the sets for the vertices until we find a id that exists in
       // all sets.  If found, this is our an interior parent id.  The interior parent id found
       // will be the lowest element id if there is potential for multiple interior parents.
       if (found_interior_parents)
         {
           std::set<dof_id_type> & neighbors_0 = neighbors[0];
           for (std::set<dof_id_type>::iterator e_it = neighbors_0.begin();
                e_it != neighbors_0.end(); e_it++)
             {
               found_interior_parents=false;
               dof_id_type interior_parent_id = *e_it;
               for (dof_id_type n=1; n < element->n_vertices(); n++)
                 {
                   if (neighbors[n].find(interior_parent_id)!=neighbors[n].end())
                     {
                       found_interior_parents=true;
                     }
                   else
                     {
                       found_interior_parents=false;
                       break;
                     }
                 }
               if (found_interior_parents)
                 {
                   element->set_interior_parent(this->elem(interior_parent_id));
                   break;
                 }
             }
         }
     }
 }
virtual const Elem* libMesh::MeshBase::elem (const dof_id_type i) const pure virtual inherited
Return a pointer to the element, which should be present in this processor's subset of the mesh data structure.
Implemented in libMesh::ParallelMesh, and libMesh::SerialMesh.
Referenced by libMesh::MeshTools::Subdivision::add_boundary_ghosts(), libMesh::BoundaryInfo::add_edge(), libMesh::BoundaryInfo::add_elements(), libMesh::BoundaryInfo::add_side(), libMesh::AbaqusIO::assign_sideset_ids(), libMesh::AbaqusIO::assign_subdomain_ids(), libMesh::Nemesis_IO_Helper::build_element_and_node_maps(), libMesh::InfElemBuilder::build_inf_elem(), libMesh::MeshTools::Modification::change_boundary_id(), libMesh::Nemesis_IO_Helper::compute_num_global_sidesets(), copy_nodes_and_elements(), libMesh::MeshBase::detect_interior_parents(), libMesh::DofMap::elem_ptr(), libMesh::MeshData::foreign_id_to_elem(), libMesh::UNVIO::groups_in(), libMesh::ErrorVector::is_active_elem(), libMesh::BoundaryInfo::operator=(), libMesh::Nemesis_IO::read(), libMesh::ExodusII_IO::read(), libMesh::CheckpointIO::read_connectivity(), libMesh::XdrIO::read_serialized_connectivity(), libMesh::MeshTools::subdomain_bounding_box(), libMesh::Parallel::sync_element_data_by_parent_id(), libMesh::Parallel::sync_node_data_by_element_id(), libMesh::Elem::topological_neighbor(), libMesh::Parallel::Packing< Elem * >::unpack(), libMesh::FroIO::write(), libMesh::Nemesis_IO_Helper::write_elements(), libMesh::ExodusII_IO_Helper::write_elements(), libMesh::LegacyXdrIO::write_mesh(), libMesh::Nemesis_IO_Helper::write_sidesets(), libMesh::ExodusII_IO_Helper::write_sidesets(), and libMesh::DivaIO::write_stream().
virtual Elem* libMesh::MeshBase::elem (const dof_id_type i) pure virtual inherited
Return a writeable pointer to the element, which should be present in this processor's subset of the mesh data structure.
Implemented in libMesh::ParallelMesh, and libMesh::SerialMesh.
const std::set<unsigned char>& libMesh::MeshBase::elem_dimensions () const inline inherited
Returns
set of dimensions of elements present in the mesh.
Definition at line 171 of file mesh_base.h.
References libMesh::MeshBase::_elem_dims.
Referenced by libMesh::ExactSolution::_compute_error(), libMesh::System::calculate_norm(), and libMesh::MeshBase::detect_interior_parents().
   { return _elem_dims; }
virtual element_iterator libMesh::MeshBase::elements_begin () pure virtual inherited
Iterate over all the elements in the Mesh.
Implemented in libMesh::ParallelMesh, and libMesh::SerialMesh.
Referenced by libMesh::EquationSystems::_add_system_to_nodes_and_elems(), libMesh::MeshRefinement::_coarsen_elements(), libMesh::BoundaryInfo::_find_id_maps(), libMesh::MeshRefinement::_refine_elements(), libMesh::BoundaryInfo::add_elements(), libMesh::MeshRefinement::add_p_to_h_refinement(), libMesh::VariationalMeshSmoother::adjust_adapt_data(), all_first_order(), all_second_order(), libMesh::MeshTools::Subdivision::all_subdivision(), libMesh::MeshTools::Modification::all_tri(), libMesh::EquationSystems::allgather(), libMesh::MeshData::assign(), libMesh::MeshCommunication::assign_global_indices(), libMesh::MeshTools::Generation::build_cube(), libMesh::MeshTools::Generation::build_delaunay_square(), libMesh::MeshTools::Generation::build_extrusion(), libMesh::MeshTools::build_nodes_to_elem_map(), libMesh::MeshTools::Modification::change_subdomain_id(), libMesh::TetGenMeshInterface::check_hull_integrity(), libMesh::MeshRefinement::clean_refinement_flags(), libMesh::MeshRefinement::coarsen_elements(), libMesh::CentroidPartitioner::compute_centroids(), contract(), copy_nodes_and_elements(), libMesh::TetGenMeshInterface::delete_2D_hull_elements(), libMesh::MeshBase::detect_interior_parents(), libMesh::DofMap::distribute_dofs(), libMesh::MeshTools::elem_types(), libMesh::UNVIO::elements_out(), libMesh::TopologyMap::fill(), find_neighbors(), libMesh::MeshTools::Modification::flatten(), libMesh::MeshTools::get_not_subactive_node_ids(), libMesh::EquationSystems::init(), libMesh::MeshTools::libmesh_assert_connected_nodes(), libMesh::MeshTools::libmesh_assert_equal_n_systems(), libMesh::MeshTools::libmesh_assert_no_links_to_elem(), libMesh::MeshTools::libmesh_assert_old_dof_objects(), libMesh::MeshTools::libmesh_assert_valid_amr_elem_ids(), libMesh::MeshTools::libmesh_assert_valid_amr_interior_parents(), libMesh::MeshTools::libmesh_assert_valid_neighbors(), libMesh::MeshTools::libmesh_assert_valid_node_pointers(), libMesh::MeshTools::libmesh_assert_valid_procids< Elem >(), libMesh::MeshTools::libmesh_assert_valid_refinement_flags(), libMesh::MeshTools::libmesh_assert_valid_refinement_tree(), libMesh::MeshRefinement::make_coarsening_compatible(), libMesh::MeshRefinement::make_flags_parallel_consistent(), libMesh::MeshCommunication::make_node_ids_parallel_consistent(), libMesh::MeshCommunication::make_node_proc_ids_parallel_consistent(), libMesh::MeshCommunication::make_p_levels_parallel_consistent(), libMesh::MeshBase::n_sub_elem(), libMesh::ErrorVector::plot_error(), libMesh::TetGenMeshInterface::pointset_convexhull(), libMesh::MeshTools::Subdivision::prepare_subdivision_mesh(), libMesh::AbaqusIO::read(), libMesh::UNVIO::read_implementation(), libMesh::MeshRefinement::refine_and_coarsen_elements(), libMesh::MeshRefinement::refine_elements(), libMesh::EquationSystems::reinit(), libMesh::DofMap::reinit(), libMesh::Partitioner::single_partition(), libMesh::MeshRefinement::switch_h_to_p_refinement(), libMesh::BoundaryInfo::sync(), libMesh::MeshTools::Subdivision::tag_boundary_ghosts(), libMesh::MeshTools::total_weight(), libMesh::TetGenMeshInterface::triangulate_conformingDelaunayMesh_carvehole(), libMesh::UCDIO::write_interior_elems(), and libMesh::LegacyXdrIO::write_mesh().
virtual const_element_iterator libMesh::MeshBase::elements_begin () const pure virtual inherited
Implemented in libMesh::ParallelMesh, and libMesh::SerialMesh.
virtual element_iterator libMesh::MeshBase::elements_end () pure virtual inherited
Implemented in libMesh::ParallelMesh, and libMesh::SerialMesh.
Referenced by libMesh::EquationSystems::_add_system_to_nodes_and_elems(), libMesh::MeshRefinement::_coarsen_elements(), libMesh::BoundaryInfo::_find_id_maps(), libMesh::MeshRefinement::_refine_elements(), libMesh::BoundaryInfo::add_elements(), libMesh::MeshRefinement::add_p_to_h_refinement(), libMesh::VariationalMeshSmoother::adjust_adapt_data(), all_first_order(), all_second_order(), libMesh::MeshTools::Subdivision::all_subdivision(), libMesh::MeshTools::Modification::all_tri(), libMesh::EquationSystems::allgather(), libMesh::MeshData::assign(), libMesh::MeshCommunication::assign_global_indices(), libMesh::MeshTools::Generation::build_cube(), libMesh::MeshTools::Generation::build_delaunay_square(), libMesh::MeshTools::Generation::build_extrusion(), libMesh::MeshTools::build_nodes_to_elem_map(), libMesh::MeshTools::Modification::change_subdomain_id(), libMesh::TetGenMeshInterface::check_hull_integrity(), libMesh::MeshRefinement::clean_refinement_flags(), libMesh::MeshRefinement::coarsen_elements(), libMesh::CentroidPartitioner::compute_centroids(), contract(), copy_nodes_and_elements(), libMesh::TetGenMeshInterface::delete_2D_hull_elements(), libMesh::DofMap::distribute_dofs(), libMesh::MeshTools::elem_types(), libMesh::UNVIO::elements_out(), libMesh::TopologyMap::fill(), find_neighbors(), libMesh::MeshTools::Modification::flatten(), libMesh::MeshTools::get_not_subactive_node_ids(), libMesh::EquationSystems::init(), libMesh::MeshTools::libmesh_assert_connected_nodes(), libMesh::MeshTools::libmesh_assert_equal_n_systems(), libMesh::MeshTools::libmesh_assert_no_links_to_elem(), libMesh::MeshTools::libmesh_assert_old_dof_objects(), libMesh::MeshTools::libmesh_assert_valid_amr_elem_ids(), libMesh::MeshTools::libmesh_assert_valid_amr_interior_parents(), libMesh::MeshTools::libmesh_assert_valid_neighbors(), libMesh::MeshTools::libmesh_assert_valid_node_pointers(), libMesh::MeshTools::libmesh_assert_valid_procids< Elem >(), libMesh::MeshTools::libmesh_assert_valid_refinement_flags(), libMesh::MeshTools::libmesh_assert_valid_refinement_tree(), libMesh::MeshRefinement::make_coarsening_compatible(), libMesh::MeshRefinement::make_flags_parallel_consistent(), libMesh::MeshCommunication::make_node_ids_parallel_consistent(), libMesh::MeshCommunication::make_node_proc_ids_parallel_consistent(), libMesh::MeshCommunication::make_p_levels_parallel_consistent(), libMesh::MeshBase::n_sub_elem(), libMesh::ErrorVector::plot_error(), libMesh::TetGenMeshInterface::pointset_convexhull(), libMesh::MeshTools::Subdivision::prepare_subdivision_mesh(), libMesh::AbaqusIO::read(), libMesh::UNVIO::read_implementation(), libMesh::MeshRefinement::refine_and_coarsen_elements(), libMesh::MeshRefinement::refine_elements(), libMesh::EquationSystems::reinit(), libMesh::DofMap::reinit(), libMesh::Partitioner::single_partition(), libMesh::MeshRefinement::switch_h_to_p_refinement(), libMesh::BoundaryInfo::sync(), libMesh::MeshTools::Subdivision::tag_boundary_ghosts(), libMesh::MeshTools::total_weight(), libMesh::TetGenMeshInterface::triangulate_conformingDelaunayMesh_carvehole(), libMesh::UCDIO::write_interior_elems(), and libMesh::LegacyXdrIO::write_mesh().
virtual const_element_iterator libMesh::MeshBase::elements_end () const pure virtual inherited
Implemented in libMesh::ParallelMesh, and libMesh::SerialMesh.
virtual element_iterator libMesh::MeshBase::facelocal_elements_begin () pure virtual inherited
Iterate over elements which are on or have a neighbor on the current processor.
Implemented in libMesh::ParallelMesh, and libMesh::SerialMesh.
virtual const_element_iterator libMesh::MeshBase::facelocal_elements_begin () const pure virtual inherited
Implemented in libMesh::ParallelMesh, and libMesh::SerialMesh.
virtual element_iterator libMesh::MeshBase::facelocal_elements_end () pure virtual inherited
Implemented in libMesh::ParallelMesh, and libMesh::SerialMesh.
virtual const_element_iterator libMesh::MeshBase::facelocal_elements_end () const pure virtual inherited
Implemented in libMesh::ParallelMesh, and libMesh::SerialMesh.
void libMesh::UnstructuredMesh::find_neighbors (const bool reset_remote_elements = false, const bool reset_current_list = true) virtual
Other functions from MeshBase requiring re-definition.
Here we look at all of the child elements which don't already have valid neighbors.
If a child element has a NULL neighbor it is either because it is on the boundary or because its neighbor is at a different level. In the latter case we must get the neighbor from the parent.
If a child element has a remote_elem neighbor on a boundary it shares with its parent, that info may have become out-dated through coarsening of the neighbor's parent. In this case, if the parent's neighbor is active then the child should share it.
Furthermore, that neighbor better be active, otherwise we missed a child somewhere.
We also need to look through children ordered by increasing refinement level in order to add new interior_parent() links in boundary elements which have just been generated by refinement, and fix links in boundary elements whose previous interior_parent() has just been coarsened away.
Implements libMesh::MeshBase.
Definition at line 234 of file unstructured_mesh.C.
References libMesh::TypeVector< T >::absolute_fuzzy_equals(), libMesh::Elem::active(), libMesh::Elem::ancestor(), libMesh::Elem::centroid(), libMesh::Elem::child(), libMesh::Elem::dim(), libMesh::MeshBase::elements_begin(), libMesh::MeshBase::elements_end(), end, libMesh::err, libMesh::Elem::has_children(), libMesh::Elem::hmin(), libMesh::DofObject::id(), libMesh::Elem::interior_parent(), libMesh::Elem::is_child_on_side(), libMesh::Elem::key(), libMesh::Elem::level(), libMesh::MeshBase::level_elements_begin(), libMesh::MeshBase::level_elements_end(), libMesh::libmesh_assert(), libMesh::MeshTools::libmesh_assert_valid_amr_interior_parents(), libMesh::MeshTools::libmesh_assert_valid_neighbors(), libmesh_nullptr, libMesh::Elem::n_children(), libMesh::MeshTools::n_levels(), libMesh::Elem::n_neighbors(), libMesh::Elem::n_nodes(), libMesh::Elem::neighbor(), libMesh::Elem::parent(), libMesh::Elem::point(), libMesh::ParallelObject::processor_id(), libMesh::DofObject::processor_id(), libMesh::Real, libMesh::remote_elem, libMesh::Elem::set_interior_parent(), libMesh::Elem::set_neighbor(), libMesh::Elem::side(), libMesh::START_LOG(), libMesh::STOP_LOG(), libMesh::Elem::subactive(), libMesh::TOLERANCE, libMesh::Elem::which_child_am_i(), and libMesh::NameBasedIO::write().
Referenced by libMesh::TriangleWrapper::copy_tri_to_mesh(), and libMesh::ParallelMesh::redistribute().
 {
   // We might actually want to run this on an empty mesh
   // (e.g. the boundary mesh for a nonexistant bcid!)
   // libmesh_assert_not_equal_to (this->n_nodes(), 0);
   // libmesh_assert_not_equal_to (this->n_elem(), 0);
   // This function must be run on all processors at once
   parallel_object_only();
   START_LOG("find_neighbors()", "Mesh");
   const element_iterator el_end = this->elements_end();
   //TODO:[BSK] This should be removed later?!
   if (reset_current_list)
     for (element_iterator el = this->elements_begin(); el != el_end; ++el)
       {
         Elem * e = *el;
         for (unsigned int s=0; s<e->n_neighbors(); s++)
           if (e->neighbor(s) != remote_elem ||
               reset_remote_elements)
             e->set_neighbor(s, libmesh_nullptr);
       }
   // Find neighboring elements by first finding elements
   // with identical side keys and then check to see if they
   // are neighbors
   {
     // data structures -- Use the hash_multimap if available
     typedef unsigned int                    key_type;
     typedef std::pair<Elem *, unsigned char> val_type;
     typedef std::pair<key_type, val_type>   key_val_pair;
     typedef LIBMESH_BEST_UNORDERED_MULTIMAP<key_type, val_type> map_type;
     // A map from side keys to corresponding elements & side numbers
     map_type side_to_elem_map;
     for (element_iterator el = this->elements_begin(); el != el_end; ++el)
       {
         Elem * element = *el;
         for (unsigned char ms=0; ms<element->n_neighbors(); ms++)
           {
           next_side:
             // If we haven't yet found a neighbor on this side, try.
             // Even if we think our neighbor is remote, that
             // information may be out of date.
             if (element->neighbor(ms) == libmesh_nullptr ||
                 element->neighbor(ms) == remote_elem)
               {
                 // Get the key for the side of this element
                 const unsigned int key = element->key(ms);
                 // Look for elements that have an identical side key
                 std::pair <map_type::iterator, map_type::iterator>
                   bounds = side_to_elem_map.equal_range(key);
                 // May be multiple keys, check all the possible
                 // elements which _might_ be neighbors.
                 if (bounds.first != bounds.second)
                   {
                     // Get the side for this element
                     const UniquePtr<Elem> my_side(element->side(ms));
                     // Look at all the entries with an equivalent key
                     while (bounds.first != bounds.second)
                       {
                         // Get the potential element
                         Elem * neighbor = bounds.first->second.first;
                         // Get the side for the neighboring element
                         const unsigned int ns = bounds.first->second.second;
                         const UniquePtr<Elem> their_side(neighbor->side(ns));
                         //libmesh_assert(my_side.get());
                         //libmesh_assert(their_side.get());
                         // If found a match with my side
                         //
                         // We need special tests here for 1D:
                         // since parents and children have an equal
                         // side (i.e. a node), we need to check
                         // ns != ms, and we also check level() to
                         // avoid setting our neighbor pointer to
                         // any of our neighbor's descendants
                         if( (*my_side == *their_side) &&
                             (element->level() == neighbor->level()) &&
                             ((element->dim() != 1) || (ns != ms)) )
{
                             // So share a side.  Is this a mixed pair
                             // of subactive and active/ancestor
                             // elements?
                             // If not, then we're neighbors.
                             // If so, then the subactive's neighbor is
                             if (element->subactive() ==
                                 neighbor->subactive())
{
                                 // an element is only subactive if it has
                                 // been coarsened but not deleted
                                 element->set_neighbor (ms,neighbor);
                                 neighbor->set_neighbor(ns,element);
                               }
                             else if (element->subactive())
{
                                 element->set_neighbor(ms,neighbor);
                               }
                             else if (neighbor->subactive())
{
                                 neighbor->set_neighbor(ns,element);
                               }
                             side_to_elem_map.erase (bounds.first);
                             // get out of this nested crap
                             goto next_side;
                           }
                         ++bounds.first;
                       }
                   }
                 // didn't find a match...
                 // Build the map entry for this element
                 key_val_pair kvp;
                 kvp.first         = key;
                 kvp.second.first  = element;
                 kvp.second.second = ms;
                 // use the lower bound as a hint for
                 // where to put it.
 #if defined(LIBMESH_HAVE_UNORDERED_MAP) || defined(LIBMESH_HAVE_TR1_UNORDERED_MAP) || defined(LIBMESH_HAVE_HASH_MAP) || defined(LIBMESH_HAVE_EXT_HASH_MAP)
                 side_to_elem_map.insert (kvp);
 #else
                 side_to_elem_map.insert (bounds.first,kvp);
 #endif
               }
           }
       }
   }
 #ifdef LIBMESH_ENABLE_AMR
   const unsigned int n_levels = MeshTools::n_levels(*this);
   for (unsigned int level = 1; level < n_levels; ++level)
     {
       element_iterator end = this->level_elements_end(level);
       for (element_iterator el = this->level_elements_begin(level);
            el != end; ++el)
         {
           Elem * current_elem = *el;
           libmesh_assert(current_elem);
           Elem * parent = current_elem->parent();
           libmesh_assert(parent);
           const unsigned int my_child_num = parent->which_child_am_i(current_elem);
           for (unsigned int s=0; s < current_elem->n_neighbors(); s++)
             {
               if (current_elem->neighbor(s) == libmesh_nullptr ||
                   (current_elem->neighbor(s) == remote_elem &&
                    parent->is_child_on_side(my_child_num, s)))
                 {
                   Elem * neigh = parent->neighbor(s);
                   // If neigh was refined and had non-subactive children
                   // made remote earlier, then a non-subactive elem should
                   // actually have one of those remote children as a
                   // neighbor
                   if (neigh && (neigh->ancestor()) && (!current_elem->subactive()))
                     {
 #ifdef DEBUG
                       // Let's make sure that "had children made remote"
                       // situation is actually the case
                       libmesh_assert(neigh->has_children());
                       bool neigh_has_remote_children = false;
                       for (unsigned int c = 0; c != neigh->n_children(); ++c)
{
                           if (neigh->child(c) == remote_elem)
                             neigh_has_remote_children = true;
                         }
                       libmesh_assert(neigh_has_remote_children);
                       // And let's double-check that we don't have
                       // a remote_elem neighboring a local element
                       libmesh_assert_not_equal_to (current_elem->processor_id(),
                                                    this->processor_id());
 #endif // DEBUG
                       neigh = const_cast<RemoteElem *>(remote_elem);
                     }
                   if (!current_elem->subactive())
                     current_elem->set_neighbor(s, neigh);
 #ifdef DEBUG
                   if (neigh != libmesh_nullptr && neigh != remote_elem)
                     // We ignore subactive elements here because
                     // we don't care about neighbors of subactive element.
                     if ((!neigh->active()) && (!current_elem->subactive()))
                       {
                         libMesh::err << "On processor " << this->processor_id()
                                      << std::endl;
                         libMesh::err << "Bad element ID = " << current_elem->id()
                                      << ", Side " << s << ", Bad neighbor ID = " << neigh->id() << std::endl;
                         libMesh::err << "Bad element proc_ID = " << current_elem->processor_id()
                                      << ", Bad neighbor proc_ID = " << neigh->processor_id() << std::endl;
                         libMesh::err << "Bad element size = " << current_elem->hmin()
                                      << ", Bad neighbor size = " << neigh->hmin() << std::endl;
                         libMesh::err << "Bad element center = " << current_elem->centroid()
                                      << ", Bad neighbor center = " << neigh->centroid() << std::endl;
                         libMesh::err << "ERROR: "
                                      << (current_elem->active()?"Active":"Ancestor")
                                      << " Element at level "
                                      << current_elem->level() << std::endl;
                         libMesh::err << "with "
                                      << (parent->active()?"active":
                                          (parent->subactive()?"subactive":"ancestor"))
                                      << " parent share "
                                      << (neigh->subactive()?"subactive":"ancestor")
                                      << " neighbor at level " << neigh->level()
                                      << std::endl;
                         NameBasedIO(*this).write ("bad_mesh.gmv");
                         libmesh_error_msg("Problematic mesh written to bad_mesh.gmv.");
                       }
 #endif // DEBUG
                 }
             }
           // We can skip to the next element if we're full-dimension
           // and therefore don't have any interior parents
           if (current_elem->dim() >= LIBMESH_DIM)
             continue;
           // We have no interior parents unless we can find one later
           current_elem->set_interior_parent(libmesh_nullptr);
           Elem * pip = parent->interior_parent();
           if (!pip)
             continue;
           // If there's no interior_parent children, whether due to a
           // remote element or a non-conformity, then there's no
           // children to search.
           if (pip == remote_elem || pip->active())
             {
               current_elem->set_interior_parent(pip);
               continue;
             }
           // For node comparisons we'll need a sensible tolerance
           Real node_tolerance = current_elem->hmin() * TOLERANCE;
           // Otherwise our interior_parent should be a child of our
           // parent's interior_parent.
           for (unsigned int c=0; c != pip->n_children(); ++c)
             {
               Elem * child = pip->child(c);
               // If we have a remote_elem, that might be our
               // interior_parent.  We'll set it provisionally now and
               // keep trying to find something better.
               if (child == remote_elem)
                 {
                   current_elem->set_interior_parent
                     (const_cast<RemoteElem *>(remote_elem));
                   continue;
                 }
               bool child_contains_our_nodes = true;
               for (unsigned int n=0; n != current_elem->n_nodes();
                    ++n)
                 {
                   bool child_contains_this_node = false;
                   for (unsigned int cn=0; cn != child->n_nodes();
                        ++cn)
                     if (child->point(cn).absolute_fuzzy_equals
                         (current_elem->point(n), node_tolerance))
                       {
                         child_contains_this_node = true;
                         break;
                       }
                   if (!child_contains_this_node)
                     {
                       child_contains_our_nodes = false;
                       break;
                     }
                 }
               if (child_contains_our_nodes)
                 {
                   current_elem->set_interior_parent(child);
                   break;
                 }
             }
           // We should have found *some* interior_parent at this
           // point, whether semilocal or remote.
           libmesh_assert(current_elem->interior_parent());
         }
     }
 #endif // AMR
 #ifdef DEBUG
   MeshTools::libmesh_assert_valid_neighbors(*this,
                                             !reset_remote_elements);
   MeshTools::libmesh_assert_valid_amr_interior_parents(*this);
 #endif
   STOP_LOG("find_neighbors()", "Mesh");
 }
virtual void libMesh::MeshBase::fix_broken_node_and_element_numbering () pure virtual inherited
There is no reason for a user to ever call this function.
This function restores a previously broken element/node numbering such that mesh.node(n)->id() == n.
Implemented in libMesh::ParallelMesh, and libMesh::SerialMesh.
Referenced by libMesh::EquationSystems::_read_impl().
const BoundaryInfo& libMesh::MeshBase::get_boundary_info () const inline inherited
The information about boundary ids on the mesh
Definition at line 111 of file mesh_base.h.
References libMesh::MeshBase::boundary_info.
Referenced by libMesh::MeshRefinement::_coarsen_elements(), libMesh::MeshTools::Subdivision::add_boundary_ghosts(), all_first_order(), all_second_order(), libMesh::MeshTools::Subdivision::all_subdivision(), libMesh::MeshTools::Modification::all_tri(), libMesh::AbaqusIO::assign_boundary_node_ids(), libMesh::AbaqusIO::assign_sideset_ids(), libMesh::MeshTools::Generation::build_cube(), libMesh::MeshTools::Generation::build_delaunay_square(), libMesh::MeshTools::Generation::build_extrusion(), libMesh::MeshTools::Modification::change_boundary_id(), libMesh::MeshBase::clear(), libMesh::Nemesis_IO_Helper::compute_num_global_nodesets(), libMesh::Nemesis_IO_Helper::compute_num_global_sidesets(), libMesh::FEGenericBase< OutputType >::compute_periodic_constraints(), libMesh::FEAbstract::compute_periodic_node_constraints(), create_submesh(), libMesh::SerialMesh::delete_elem(), libMesh::ParallelMesh::delete_elem(), libMesh::SerialMesh::delete_node(), libMesh::ParallelMesh::delete_node(), libMesh::MeshTools::Modification::flatten(), libMesh::UNVIO::groups_in(), libMesh::ExodusII_IO_Helper::initialize(), libMesh::BoundaryProjectSolution::operator()(), libMesh::Parallel::Packing< const Node * >::pack(), libMesh::Parallel::Packing< const Elem * >::pack(), libMesh::Parallel::Packing< const Node * >::packable_size(), libMesh::Parallel::Packing< const Elem * >::packable_size(), libMesh::ParallelMesh::ParallelMesh(), libMesh::AbaqusIO::read(), libMesh::Nemesis_IO::read(), libMesh::ExodusII_IO::read(), libMesh::CheckpointIO::read_bcs(), libMesh::LegacyXdrIO::read_mesh(), libMesh::CheckpointIO::read_nodesets(), libMesh::SerialMesh::renumber_nodes_and_elements(), libMesh::ParallelMesh::renumber_nodes_and_elements(), libMesh::SerialMesh::SerialMesh(), libMesh::SerialMesh::stitching_helper(), libMesh::Elem::topological_neighbor(), libMesh::Parallel::Packing< Node * >::unpack(), libMesh::Parallel::Packing< Elem * >::unpack(), libMesh::FroIO::write(), libMesh::Nemesis_IO::write(), libMesh::ExodusII_IO::write(), libMesh::XdrIO::write(), libMesh::LegacyXdrIO::write_mesh(), libMesh::Nemesis_IO::write_nodal_data(), libMesh::ExodusII_IO::write_nodal_data_common(), libMesh::Nemesis_IO_Helper::write_nodesets(), libMesh::ExodusII_IO_Helper::write_nodesets(), libMesh::Nemesis_IO_Helper::write_sidesets(), libMesh::ExodusII_IO_Helper::write_sidesets(), libMesh::LegacyXdrIO::write_soln(), and libMesh::DivaIO::write_stream().
 { return *boundary_info; }
BoundaryInfo& libMesh::MeshBase::get_boundary_info () inline inherited
Writeable information about boundary ids on the mesh
Definition at line 116 of file mesh_base.h.
References libMesh::MeshBase::boundary_info.
 { return *boundary_info; }
subdomain_id_type libMesh::MeshBase::get_id_by_name (const std::string & name) const inherited
Returns the id of the named subdomain if it exists, Elem::invalid_subdomain_id otherwise.
Definition at line 524 of file mesh_base.C.
References libMesh::MeshBase::_block_id_to_name, and libMesh::Elem::invalid_subdomain_id.
 {
   // Linear search over the map values.
   std::map<subdomain_id_type, std::string>::const_iterator
     iter = _block_id_to_name.begin(),
     end_iter = _block_id_to_name.end();
   for ( ; iter != end_iter; ++iter)
     if (iter->second == name)
       return iter->first;
   // If we made it here without returning, we don't have a subdomain
   // with the requested name, so return Elem::invalid_subdomain_id.
   return Elem::invalid_subdomain_id;
 }
std::string libMesh::MeshBase::get_info () const inherited
Returns
a string containing relevant information about the mesh.
Definition at line 357 of file mesh_base.C.
References libMesh::MeshBase::_elem_dims, libMesh::MeshBase::n_active_elem(), libMesh::MeshBase::n_elem(), libMesh::MeshBase::n_local_elem(), libMesh::MeshBase::n_local_nodes(), libMesh::MeshBase::n_nodes(), libMesh::MeshBase::n_partitions(), libMesh::ParallelObject::n_processors(), libMesh::MeshBase::n_subdomains(), libMesh::n_threads, libMesh::ParallelObject::processor_id(), and libMesh::MeshBase::spatial_dimension().
Referenced by libMesh::MeshBase::print_info().
 {
   std::ostringstream oss;
   oss << " Mesh Information:"                                  << '\n';
   if (!_elem_dims.empty())
     {
       oss << "  elem_dimensions()={";
       std::copy(_elem_dims.begin(),
                 --_elem_dims.end(), // --end() is valid if the set is non-empty
                 std::ostream_iterator<unsigned int>(oss, ", "));
       oss << cast_int<unsigned int>(*_elem_dims.rbegin());
       oss << "}\n";
     }
   oss << "  spatial_dimension()=" << this->spatial_dimension() << '\n'
       << "  n_nodes()="           << this->n_nodes()           << '\n'
       << "    n_local_nodes()="   << this->n_local_nodes()     << '\n'
       << "  n_elem()="            << this->n_elem()            << '\n'
       << "    n_local_elem()="    << this->n_local_elem()      << '\n'
 #ifdef LIBMESH_ENABLE_AMR
       << "    n_active_elem()="   << this->n_active_elem()     << '\n'
 #endif
       << "  n_subdomains()="      << static_cast<std::size_t>(this->n_subdomains()) << '\n'
       << "  n_partitions()="      << static_cast<std::size_t>(this->n_partitions()) << '\n'
       << "  n_processors()="      << static_cast<std::size_t>(this->n_processors()) << '\n'
       << "  n_threads()="         << static_cast<std::size_t>(libMesh::n_threads()) << '\n'
       << "  processor_id()="      << static_cast<std::size_t>(this->processor_id()) << '\n';
   return oss.str();
 }
const std::map<subdomain_id_type, std::string>& libMesh::MeshBase::get_subdomain_name_map () const inline inherited
Definition at line 983 of file mesh_base.h.
References libMesh::MeshBase::_block_id_to_name.
Referenced by libMesh::XdrIO::write_serialized_subdomain_names(), and libMesh::CheckpointIO::write_subdomain_names().
   { return _block_id_to_name; }
virtual element_iterator libMesh::MeshBase::ghost_elements_begin () pure virtual inherited
Iterate over "ghost" elements in the Mesh. A ghost element is one which is not local, but is semilocal.
Implemented in libMesh::ParallelMesh, and libMesh::SerialMesh.
virtual const_element_iterator libMesh::MeshBase::ghost_elements_begin () const pure virtual inherited
Implemented in libMesh::ParallelMesh, and libMesh::SerialMesh.
virtual element_iterator libMesh::MeshBase::ghost_elements_end () pure virtual inherited
Implemented in libMesh::ParallelMesh, and libMesh::SerialMesh.
virtual const_element_iterator libMesh::MeshBase::ghost_elements_end () const pure virtual inherited
Implemented in libMesh::ParallelMesh, and libMesh::SerialMesh.
virtual Elem* libMesh::MeshBase::insert_elem (Elem * e) pure virtual inherited
Insert elem e to the element array, preserving its id and replacing/deleting any existing element with the same id.
Users should call MeshBase::prepare_for_use() after elements are added to and/or deleted from the mesh.
Implemented in libMesh::ParallelMesh, and libMesh::SerialMesh.
Referenced by all_first_order(), all_second_order(), and libMesh::MeshTools::Subdivision::all_subdivision().
virtual Node* libMesh::MeshBase::insert_node (Node * n) pure virtual inherited
Insert Node n into the Mesh at a location consistent with n->id(), allocating extra storage if necessary. Will error rather than overwriting an existing Node. Primarily intended for use with the mesh_inserter_iterator, only use if you know what you are doing...
Implemented in libMesh::ParallelMesh, and libMesh::SerialMesh.
Referenced by libMesh::mesh_inserter_iterator< T >::operator=().
bool libMesh::MeshBase::is_prepared () const inline inherited
Returns
true if the mesh has been prepared via a call to prepare_for_use, false otherwise.
Definition at line 127 of file mesh_base.h.
References libMesh::MeshBase::_is_prepared.
Referenced by libMesh::DofMap::build_sparsity(), libMesh::DofMap::create_dof_constraints(), libMesh::DofMap::distribute_dofs(), and libMesh::DofMap::reinit().
   { return _is_prepared; }
virtual bool libMesh::MeshBase::is_serial () const inline virtual inherited
Returns
true if all elements and nodes of the mesh exist on the current processor, false otherwise
Reimplemented in libMesh::ParallelMesh.
Definition at line 134 of file mesh_base.h.
Referenced by libMesh::MeshRefinement::_coarsen_elements(), libMesh::MetisPartitioner::_do_partition(), libMesh::MeshRefinement::_refine_elements(), libMesh::MeshRefinement::_smooth_flags(), libMesh::BoundaryInfo::add_elements(), all_second_order(), libMesh::MeshTools::Modification::all_tri(), libMesh::EquationSystems::allgather(), libMesh::DofMap::allgather_recursive_constraints(), libMesh::MeshTools::Generation::build_extrusion(), libMesh::InfElemBuilder::build_inf_elem(), libMesh::DofMap::create_dof_constraints(), create_submesh(), libMesh::LocationMap< T >::init(), libMesh::TopologyMap::init(), libMesh::MeshRefinement::make_coarsening_compatible(), libMesh::MeshSerializer::MeshSerializer(), libMesh::BoundaryInfo::n_boundary_conds(), libMesh::BoundaryInfo::n_edge_conds(), libMesh::BoundaryInfo::n_nodeset_conds(), libMesh::MeshBase::partition(), libMesh::MeshBase::prepare_for_use(), libMesh::Nemesis_IO::read(), libMesh::DofMap::scatter_constraints(), libMesh::BoundaryInfo::sync(), libMesh::MeshTools::total_weight(), libMesh::EquationSystems::write(), libMesh::LegacyXdrIO::write_mesh(), and libMesh::XdrIO::write_parallel().
   { return true; }
virtual element_iterator libMesh::MeshBase::level_elements_begin (unsigned int level) pure virtual inherited
Iterate over elements of a given level.
Implemented in libMesh::ParallelMesh, and libMesh::SerialMesh.
Referenced by find_neighbors(), libMesh::MeshRefinement::make_coarsening_compatible(), and libMesh::MeshTools::Modification::smooth().
virtual const_element_iterator libMesh::MeshBase::level_elements_begin (unsigned int level) const pure virtual inherited
Implemented in libMesh::ParallelMesh, and libMesh::SerialMesh.
virtual element_iterator libMesh::MeshBase::level_elements_end (unsigned int level) pure virtual inherited
Implemented in libMesh::ParallelMesh, and libMesh::SerialMesh.
Referenced by find_neighbors(), libMesh::MeshRefinement::make_coarsening_compatible(), and libMesh::MeshTools::Modification::smooth().
virtual const_element_iterator libMesh::MeshBase::level_elements_end (unsigned int level) const pure virtual inherited
Implemented in libMesh::ParallelMesh, and libMesh::SerialMesh.
virtual void libMesh::MeshBase::libmesh_assert_valid_parallel_ids () const inline virtual inherited
Verify id and processor_id consistency of our elements and nodes containers. Calls libmesh_assert() on each possible failure. Currently only implemented on ParallelMesh; a serial data structure is much harder to get out of sync.
Reimplemented in libMesh::ParallelMesh.
Definition at line 746 of file mesh_base.h.
Referenced by libMesh::MeshRefinement::_refine_elements(), libMesh::InfElemBuilder::build_inf_elem(), and libMesh::MeshRefinement::refine_and_coarsen_elements().
 {}
virtual element_iterator libMesh::MeshBase::local_elements_begin () pure virtual inherited
Implemented in libMesh::ParallelMesh, and libMesh::SerialMesh.
Referenced by libMesh::MeshCommunication::assign_global_indices(), libMesh::MeshCommunication::check_for_duplicate_global_indices(), libMesh::DofMap::create_dof_constraints(), libMesh::EquationSystems::get_solution(), libMesh::MeshTools::libmesh_assert_valid_remote_elems(), libMesh::MeshTools::n_local_levels(), and libMesh::MeshTools::n_p_levels().
virtual const_element_iterator libMesh::MeshBase::local_elements_begin () const pure virtual inherited
Implemented in libMesh::ParallelMesh, and libMesh::SerialMesh.
virtual element_iterator libMesh::MeshBase::local_elements_end () pure virtual inherited
Implemented in libMesh::ParallelMesh, and libMesh::SerialMesh.
Referenced by libMesh::MeshCommunication::assign_global_indices(), libMesh::MeshCommunication::check_for_duplicate_global_indices(), libMesh::DofMap::create_dof_constraints(), libMesh::EquationSystems::get_solution(), libMesh::MeshTools::libmesh_assert_valid_remote_elems(), libMesh::MeshTools::n_local_levels(), libMesh::MeshTools::n_p_levels(), and libMesh::XdrIO::write_serialized_connectivity().
virtual const_element_iterator libMesh::MeshBase::local_elements_end () const pure virtual inherited
Implemented in libMesh::ParallelMesh, and libMesh::SerialMesh.
virtual element_iterator libMesh::MeshBase::local_level_elements_begin (unsigned int level) pure virtual inherited
Implemented in libMesh::ParallelMesh, and libMesh::SerialMesh.
Referenced by libMesh::XdrIO::write_serialized_connectivity().
virtual const_element_iterator libMesh::MeshBase::local_level_elements_begin (unsigned int level) const pure virtual inherited
Implemented in libMesh::ParallelMesh, and libMesh::SerialMesh.
virtual element_iterator libMesh::MeshBase::local_level_elements_end (unsigned int level) pure virtual inherited
Implemented in libMesh::ParallelMesh, and libMesh::SerialMesh.
Referenced by libMesh::XdrIO::write_serialized_connectivity().
virtual const_element_iterator libMesh::MeshBase::local_level_elements_end (unsigned int level) const pure virtual inherited
Implemented in libMesh::ParallelMesh, and libMesh::SerialMesh.
virtual node_iterator libMesh::MeshBase::local_nodes_begin () pure virtual inherited
Iterate over local nodes (nodes whose processor_id() matches the current processor).
Implemented in libMesh::ParallelMesh, and libMesh::SerialMesh.
Referenced by libMesh::MeshCommunication::assign_global_indices(), libMesh::MeshTools::bounding_box(), libMesh::EquationSystems::build_solution_vector(), libMesh::MeshCommunication::check_for_duplicate_global_indices(), libMesh::DofMap::distribute_local_dofs_node_major(), libMesh::DofMap::distribute_local_dofs_var_major(), libMesh::MeshTools::libmesh_assert_valid_procids< Node >(), libMesh::DofMap::local_variable_indices(), libMesh::VTKIO::nodes_to_vtk(), libMesh::LaplaceMeshSmoother::smooth(), libMesh::XdrIO::write_serialized_nodes(), and libMesh::System::zero_variable().
virtual const_node_iterator libMesh::MeshBase::local_nodes_begin () const pure virtual inherited
Implemented in libMesh::ParallelMesh, and libMesh::SerialMesh.
virtual node_iterator libMesh::MeshBase::local_nodes_end () pure virtual inherited
Implemented in libMesh::ParallelMesh, and libMesh::SerialMesh.
Referenced by libMesh::MeshCommunication::assign_global_indices(), libMesh::MeshTools::bounding_box(), libMesh::EquationSystems::build_solution_vector(), libMesh::MeshCommunication::check_for_duplicate_global_indices(), libMesh::DofMap::distribute_local_dofs_node_major(), libMesh::DofMap::distribute_local_dofs_var_major(), libMesh::MeshTools::libmesh_assert_valid_procids< Node >(), libMesh::DofMap::local_variable_indices(), libMesh::VTKIO::nodes_to_vtk(), libMesh::LaplaceMeshSmoother::smooth(), libMesh::XdrIO::write_serialized_nodes(), and libMesh::System::zero_variable().
virtual const_node_iterator libMesh::MeshBase::local_nodes_end () const pure virtual inherited
Implemented in libMesh::ParallelMesh, and libMesh::SerialMesh.
virtual element_iterator libMesh::MeshBase::local_not_level_elements_begin (unsigned int level) pure virtual inherited
Implemented in libMesh::ParallelMesh, and libMesh::SerialMesh.
virtual const_element_iterator libMesh::MeshBase::local_not_level_elements_begin (unsigned int level) const pure virtual inherited
Implemented in libMesh::ParallelMesh, and libMesh::SerialMesh.
virtual element_iterator libMesh::MeshBase::local_not_level_elements_end (unsigned int level) pure virtual inherited
Implemented in libMesh::ParallelMesh, and libMesh::SerialMesh.
virtual const_element_iterator libMesh::MeshBase::local_not_level_elements_end (unsigned int level) const pure virtual inherited
Implemented in libMesh::ParallelMesh, and libMesh::SerialMesh.
virtual dof_id_type libMesh::MeshBase::max_elem_id () const pure virtual inherited
Returns a number greater than or equal to the maximum element id in the mesh.
Implemented in libMesh::ParallelMesh, and libMesh::SerialMesh.
Referenced by libMesh::UniformRefinementEstimator::_estimate_error(), libMesh::BoundaryInfo::add_elements(), libMesh::MeshTools::Modification::all_tri(), libMesh::InfElemBuilder::build_inf_elem(), libMesh::MeshBase::detect_interior_parents(), libMesh::WeightedPatchRecoveryErrorEstimator::estimate_error(), libMesh::JumpErrorEstimator::estimate_error(), libMesh::PatchRecoveryErrorEstimator::estimate_error(), libMesh::AdjointRefinementEstimator::estimate_error(), libMesh::AdjointResidualErrorEstimator::estimate_error(), libMesh::MeshRefinement::flag_elements_by_nelem_target(), libMesh::EquationSystems::get_solution(), libMesh::MeshTools::libmesh_assert_valid_dof_ids(), libMesh::MeshTools::libmesh_assert_valid_neighbors(), libMesh::MeshTools::libmesh_assert_valid_procids< Elem >(), libMesh::MeshTools::libmesh_assert_valid_refinement_flags(), libMesh::MeshTools::libmesh_assert_valid_unique_ids(), libMesh::ErrorVector::plot_error(), and libMesh::HPCoarsenTest::select_refinement().
virtual dof_id_type libMesh::MeshBase::max_node_id () const pure virtual inherited
Returns a number greater than or equal to the maximum node id in the mesh.
Implemented in libMesh::ParallelMesh, and libMesh::SerialMesh.
Referenced by libMesh::DofMap::add_neighbors_to_send_list(), all_first_order(), libMesh::InfElemBuilder::build_inf_elem(), libMesh::EquationSystems::build_solution_vector(), libMesh::MeshTools::libmesh_assert_valid_dof_ids(), libMesh::MeshTools::libmesh_assert_valid_procids< Node >(), libMesh::MeshTools::libmesh_assert_valid_unique_ids(), libMesh::ErrorVector::plot_error(), and libMesh::GMVIO::write_ascii_old_impl().
unsigned int libMesh::MeshBase::mesh_dimension () const inherited
Returns
the logical dimension of the mesh; i.e. the manifold dimension of the elements in the mesh. If we ever support multi-dimensional meshes (e.g. hexes and quads in the same mesh) then this will return the largest such dimension.
Definition at line 127 of file mesh_base.C.
References libMesh::MeshBase::_elem_dims.
Referenced by libMesh::UniformRefinementEstimator::_estimate_error(), libMesh::HPCoarsenTest::add_projection(), all_second_order(), libMesh::MeshTools::Modification::all_tri(), libMesh::MeshTools::Generation::build_cube(), libMesh::EquationSystems::build_discontinuous_solution_vector(), libMesh::EquationSystems::build_solution_vector(), libMesh::EquationSystems::build_variable_names(), libMesh::MeshBase::cache_elem_dims(), libMesh::DofMap::create_dof_constraints(), libMesh::MeshTools::Modification::distort(), libMesh::MeshRefinement::flag_elements_by_elem_fraction(), libMesh::MeshRefinement::flag_elements_by_nelem_target(), libMesh::LaplaceMeshSmoother::init(), libMesh::PointLocatorTree::init(), libMesh::ExodusII_IO_Helper::initialize(), libMesh::FEInterface::n_vec_dim(), libMesh::WeightedPatchRecoveryErrorEstimator::EstimateError::operator()(), libMesh::PatchRecoveryErrorEstimator::EstimateError::operator()(), libMesh::BoundaryProjectSolution::operator()(), libMesh::Nemesis_IO::read(), libMesh::GMVIO::read(), libMesh::ExodusII_IO::read(), libMesh::VTKIO::read(), libMesh::System::read_header(), libMesh::LegacyXdrIO::read_mesh(), libMesh::XdrIO::read_serialized_connectivity(), libMesh::HPCoarsenTest::select_refinement(), libMesh::MeshTools::Modification::smooth(), libMesh::DofMap::use_coupled_neighbor_dofs(), libMesh::PostscriptIO::write(), libMesh::TecplotIO::write_binary(), libMesh::GMVIO::write_binary(), libMesh::GMVIO::write_discontinuous_gmv(), libMesh::UCDIO::write_nodal_data(), libMesh::EnsightIO::write_scalar_ascii(), libMesh::GnuPlotIO::write_solution(), libMesh::DivaIO::write_stream(), and libMesh::EnsightIO::write_vector_ascii().
 {
   if (!_elem_dims.empty())
     return cast_int<unsigned int>(*_elem_dims.rbegin());
   return 0;
 }
virtual dof_id_type libMesh::MeshBase::n_active_elem () const pure virtual inherited
Returns the number of active elements in the mesh. Implemented in terms of active_element_iterators.
Implemented in libMesh::ParallelMesh, and libMesh::SerialMesh.
Referenced by libMesh::MetisPartitioner::_do_partition(), libMesh::LinearPartitioner::_do_partition(), libMesh::SFCPartitioner::_do_partition(), libMesh::MeshRefinement::flag_elements_by_error_tolerance(), libMesh::MeshRefinement::flag_elements_by_nelem_target(), libMesh::MeshTools::Modification::flatten(), libMesh::MeshBase::get_info(), libMesh::PointLocatorList::init(), libMesh::ExodusII_IO_Helper::initialize(), libMesh::VariationalMeshSmoother::metr_data_gen(), libMesh::Partitioner::partition(), libMesh::Partitioner::repartition(), libMesh::VariationalMeshSmoother::smooth(), libMesh::GMVIO::write_ascii_new_impl(), libMesh::GMVIO::write_ascii_old_impl(), libMesh::GMVIO::write_binary(), libMesh::GMVIO::write_discontinuous_gmv(), libMesh::ExodusII_IO_Helper::write_elements(), and libMesh::GnuPlotIO::write_solution().
dof_id_type libMesh::MeshBase::n_active_elem_on_proc (const processor_id_type proc) const inherited
Returns the number of active elements on processor proc.
Definition at line 318 of file mesh_base.C.
References libMesh::MeshBase::active_pid_elements_begin(), libMesh::MeshBase::active_pid_elements_end(), and libMesh::ParallelObject::n_processors().
Referenced by libMesh::MeshBase::n_active_local_elem().
 {
   libmesh_assert_less (proc_id, this->n_processors());
   return static_cast<dof_id_type>(std::distance (this->active_pid_elements_begin(proc_id),
                                                  this->active_pid_elements_end  (proc_id)));
 }
dof_id_type libMesh::MeshBase::n_active_local_elem () const inline inherited
Returns the number of active elements on the local processor.
Definition at line 343 of file mesh_base.h.
References libMesh::MeshBase::n_active_elem_on_proc(), and libMesh::ParallelObject::processor_id().
Referenced by libMesh::ParmetisPartitioner::assign_partitioning(), libMesh::ParmetisPartitioner::build_graph(), libMesh::VTKIO::cells_to_vtk(), and libMesh::ParmetisPartitioner::initialize().
   { return this->n_active_elem_on_proc (this->processor_id()); }
dof_id_type libMesh::MeshBase::n_active_sub_elem () const inherited
Same, but only counts active elements.
Definition at line 342 of file mesh_base.C.
References libMesh::MeshBase::active_elements_begin(), libMesh::MeshBase::active_elements_end(), and end.
Referenced by libMesh::TecplotIO::write_ascii(), libMesh::GMVIO::write_ascii_old_impl(), and libMesh::TecplotIO::write_binary().
 {
   dof_id_type ne=0;
   const_element_iterator       el  = this->active_elements_begin();
   const const_element_iterator end = this->active_elements_end();
   for (; el!=end; ++el)
     ne += (*el)->n_sub_elem();
   return ne;
 }
virtual dof_id_type libMesh::MeshBase::n_elem () const pure virtual inherited
Returns the number of elements in the mesh. The standard n_elem() function may return a cached value on distributed meshes, and so can be called by any processor at any time.
Implemented in libMesh::ParallelMesh, and libMesh::SerialMesh.
Referenced by libMesh::SFCPartitioner::_do_partition(), libMesh::CentroidPartitioner::_do_partition(), libMesh::UniformRefinementEstimator::_estimate_error(), libMesh::MeshTools::Subdivision::add_boundary_ghosts(), all_second_order(), libMesh::MeshTools::Subdivision::all_subdivision(), libMesh::MeshTools::Modification::all_tri(), libMesh::MeshCommunication::assign_global_indices(), libMesh::MeshTools::Generation::build_cube(), libMesh::MeshTools::Generation::build_extrusion(), libMesh::InfElemBuilder::build_inf_elem(), libMesh::MeshTools::build_nodes_to_elem_map(), libMesh::TetGenMeshInterface::check_hull_integrity(), libMesh::CentroidPartitioner::compute_centroids(), copy_nodes_and_elements(), libMesh::DofMap::create_dof_constraints(), create_submesh(), libMesh::MeshTools::Modification::distort(), libMesh::AdjointRefinementEstimator::estimate_error(), libMesh::MeshRefinement::flag_elements_by_elem_fraction(), libMesh::MeshBase::get_info(), libMesh::EquationSystems::get_solution(), libMesh::ExodusII_IO_Helper::initialize(), libMesh::ErrorVector::plot_error(), libMesh::Nemesis_IO::read(), libMesh::System::read_serialized_vector(), libMesh::System::read_serialized_vectors(), libMesh::MeshTools::Modification::redistribute(), libMesh::MeshTools::subdomain_bounding_box(), libMesh::TetGenMeshInterface::triangulate_conformingDelaunayMesh_carvehole(), libMesh::FroIO::write(), libMesh::TetGenIO::write(), libMesh::XdrIO::write(), libMesh::ExodusII_IO_Helper::write_element_values(), libMesh::LegacyXdrIO::write_mesh(), libMesh::UCDIO::write_nodal_data(), libMesh::XdrIO::write_serialized_connectivity(), libMesh::System::write_serialized_vectors(), and libMesh::DivaIO::write_stream().
dof_id_type libMesh::MeshBase::n_elem_on_proc (const processor_id_type proc) const inherited
Returns the number of elements on processor proc.
Definition at line 305 of file mesh_base.C.
References libMesh::DofObject::invalid_processor_id, libMesh::libmesh_assert(), libMesh::ParallelObject::n_processors(), libMesh::MeshBase::pid_elements_begin(), and libMesh::MeshBase::pid_elements_end().
Referenced by libMesh::MeshBase::n_local_elem(), and libMesh::MeshBase::n_unpartitioned_elem().
 {
   // We're either counting a processor's elements or unpartitioned
   // elements
   libmesh_assert (proc_id < this->n_processors() ||
                   proc_id == DofObject::invalid_processor_id);
   return static_cast<dof_id_type>(std::distance (this->pid_elements_begin(proc_id),
                                                  this->pid_elements_end  (proc_id)));
 }
dof_id_type libMesh::MeshBase::n_local_elem () const inline inherited
Returns the number of elements on the local processor.
Definition at line 326 of file mesh_base.h.
References libMesh::MeshBase::n_elem_on_proc(), and libMesh::ParallelObject::processor_id().
Referenced by libMesh::MeshBase::get_info(), and libMesh::ParallelMesh::parallel_n_elem().
   { return this->n_elem_on_proc (this->processor_id()); }
dof_id_type libMesh::MeshBase::n_local_nodes () const inline inherited
Returns the number of nodes on the local processor.
Definition at line 232 of file mesh_base.h.
References libMesh::MeshBase::n_nodes_on_proc(), and libMesh::ParallelObject::processor_id().
Referenced by libMesh::MeshBase::get_info(), libMesh::VTKIO::nodes_to_vtk(), and libMesh::ParallelMesh::parallel_n_nodes().
   { return this->n_nodes_on_proc (this->processor_id()); }
virtual dof_id_type libMesh::MeshBase::n_nodes () const pure virtual inherited
Returns the number of nodes in the mesh. This function and others must be defined in derived classes since the MeshBase class has no specific storage for nodes or elements. The standard n_nodes() function may return a cached value on distributed meshes, and so can be called by any processor at any time.
Implemented in libMesh::ParallelMesh, and libMesh::SerialMesh.
Referenced by all_second_order(), libMesh::LaplaceMeshSmoother::allgather_graph(), libMesh::MeshCommunication::assign_global_indices(), libMesh::MeshTools::Generation::build_cube(), libMesh::MeshTools::Generation::build_delaunay_square(), libMesh::MeshTools::Generation::build_extrusion(), libMesh::MeshTools::build_nodes_to_elem_map(), libMesh::EquationSystems::build_solution_vector(), copy_nodes_and_elements(), create_submesh(), libMesh::MeshTools::Modification::distort(), libMesh::TetGenMeshInterface::fill_pointlist(), libMesh::MeshTools::find_boundary_nodes(), libMesh::MeshBase::get_info(), libMesh::LaplaceMeshSmoother::init(), libMesh::TreeNode< N >::insert(), libMesh::MeshRefinement::limit_level_mismatch_at_node(), libMesh::VariationalMeshSmoother::metr_data_gen(), libMesh::ErrorVector::plot_error(), libMesh::Nemesis_IO::read(), libMesh::AbaqusIO::read_nodes(), libMesh::System::read_serialized_vector(), libMesh::System::read_serialized_vectors(), libMesh::MeshTools::Modification::redistribute(), libMesh::LaplaceMeshSmoother::smooth(), libMesh::VariationalMeshSmoother::smooth(), libMesh::MeshTools::Modification::smooth(), libMesh::MeshTools::subdomain_bounding_box(), libMesh::VTKIO::system_vectors_to_vtk(), libMesh::TreeNode< N >::transform_nodes_to_elements(), libMesh::MeshData::translate(), libMesh::TriangleInterface::triangulate(), libMesh::TetGenMeshInterface::triangulate_conformingDelaunayMesh_carvehole(), libMesh::FroIO::write(), libMesh::TetGenIO::write(), libMesh::XdrIO::write(), libMesh::MEDITIO::write_ascii(), libMesh::TecplotIO::write_ascii(), libMesh::GMVIO::write_ascii_new_impl(), libMesh::GMVIO::write_ascii_old_impl(), libMesh::TecplotIO::write_binary(), libMesh::GMVIO::write_binary(), libMesh::UCDIO::write_header(), libMesh::VTKIO::write_nodal_data(), libMesh::ExodusII_IO::write_nodal_data(), libMesh::GmshIO::write_post(), libMesh::XdrIO::write_serialized_nodes(), libMesh::System::write_serialized_vectors(), libMesh::UCDIO::write_soln(), libMesh::LegacyXdrIO::write_soln(), libMesh::DivaIO::write_stream(), and libMesh::VariationalMeshSmoother::writegr().
dof_id_type libMesh::MeshBase::n_nodes_on_proc (const processor_id_type proc) const inherited
Returns the number of nodes on processor proc.
Definition at line 292 of file mesh_base.C.
References libMesh::DofObject::invalid_processor_id, libMesh::libmesh_assert(), libMesh::ParallelObject::n_processors(), libMesh::MeshBase::pid_nodes_begin(), and libMesh::MeshBase::pid_nodes_end().
Referenced by libMesh::MeshBase::n_local_nodes(), and libMesh::MeshBase::n_unpartitioned_nodes().
 {
   // We're either counting a processor's nodes or unpartitioned
   // nodes
   libmesh_assert (proc_id < this->n_processors() ||
                   proc_id == DofObject::invalid_processor_id);
   return static_cast<dof_id_type>(std::distance (this->pid_nodes_begin(proc_id),
                                                  this->pid_nodes_end  (proc_id)));
 }
unsigned int libMesh::MeshBase::n_partitions () const inline inherited
Returns the number of partitions which have been defined via a call to either mesh.partition() or by building a Partitioner object and calling partition. Note that the partitioner objects are responsible for setting this value.
Definition at line 631 of file mesh_base.h.
References libMesh::MeshBase::_n_parts.
Referenced by libMesh::MeshBase::get_info(), libMesh::BoundaryInfo::sync(), libMesh::NameBasedIO::write(), libMesh::GMVIO::write_ascii_new_impl(), and libMesh::GMVIO::write_ascii_old_impl().
   { return _n_parts; }
processor_id_type libMesh::ParallelObject::n_processors () const inline inherited
Returns
the number of processors in the group.
Definition at line 93 of file parallel_object.h.
References libMesh::ParallelObject::_communicator, and libMesh::Parallel::Communicator::size().
Referenced by libMesh::ParmetisPartitioner::_do_repartition(), libMesh::BoundaryInfo::_find_id_maps(), libMesh::ParallelMesh::add_elem(), libMesh::ParallelMesh::add_node(), libMesh::LaplaceMeshSmoother::allgather_graph(), libMesh::FEMSystem::assembly(), libMesh::ParmetisPartitioner::assign_partitioning(), libMesh::AztecLinearSolver< T >::AztecLinearSolver(), libMesh::ParallelMesh::clear(), libMesh::Nemesis_IO_Helper::compute_border_node_ids(), libMesh::Nemesis_IO_Helper::construct_nemesis_filename(), create_pid_mesh(), libMesh::DofMap::distribute_dofs(), libMesh::DofMap::distribute_local_dofs_node_major(), libMesh::DofMap::distribute_local_dofs_var_major(), libMesh::EnsightIO::EnsightIO(), libMesh::MeshBase::get_info(), libMesh::EquationSystems::init(), libMesh::SystemSubsetBySubdomain::init(), libMesh::ParmetisPartitioner::initialize(), libMesh::Nemesis_IO_Helper::initialize(), libMesh::ParallelMesh::insert_elem(), libMesh::MeshTools::libmesh_assert_valid_dof_ids(), libMesh::MeshTools::libmesh_assert_valid_neighbors(), libMesh::MeshTools::libmesh_assert_valid_procids< Elem >(), libMesh::MeshTools::libmesh_assert_valid_procids< Node >(), libMesh::MeshTools::libmesh_assert_valid_refinement_flags(), libMesh::DofMap::local_variable_indices(), libMesh::MeshBase::n_active_elem_on_proc(), libMesh::MeshBase::n_elem_on_proc(), libMesh::MeshBase::n_nodes_on_proc(), libMesh::Partitioner::partition(), libMesh::MeshBase::partition(), libMesh::Partitioner::partition_unpartitioned_elements(), libMesh::PetscLinearSolver< T >::PetscLinearSolver(), libMesh::System::point_gradient(), libMesh::System::point_hessian(), libMesh::System::point_value(), libMesh::MeshTools::processor_bounding_box(), libMesh::System::project_vector(), libMesh::NameBasedIO::read(), libMesh::Nemesis_IO::read(), libMesh::CheckpointIO::read(), libMesh::XdrIO::read(), libMesh::System::read_parallel_data(), libMesh::System::read_SCALAR_dofs(), libMesh::System::read_serialized_blocked_dof_objects(), libMesh::System::read_serialized_vector(), libMesh::ParallelMesh::renumber_dof_objects(), libMesh::Partitioner::repartition(), libMesh::Partitioner::set_node_processor_ids(), libMesh::DofMap::set_nonlocal_dof_objects(), libMesh::ParallelMesh::update_parallel_id_counts(), libMesh::CheckpointIO::write(), libMesh::GMVIO::write_binary(), libMesh::GMVIO::write_discontinuous_gmv(), libMesh::System::write_parallel_data(), libMesh::System::write_SCALAR_dofs(), libMesh::XdrIO::write_serialized_bcs(), libMesh::System::write_serialized_blocked_dof_objects(), libMesh::XdrIO::write_serialized_connectivity(), libMesh::XdrIO::write_serialized_nodes(), and libMesh::XdrIO::write_serialized_nodesets().
   { return cast_int<processor_id_type>(_communicator.size()); }
dof_id_type libMesh::MeshBase::n_sub_elem () const inherited
This function returns the number of elements that will be written out in the Tecplot format. For example, a 9-noded quadrilateral will be broken into 4 linear sub-elements for plotting purposes. Thus, for a mesh of 2 QUAD9 elements n_tecplot_elem() will return 8. Implemented in terms of element_iterators.
Definition at line 327 of file mesh_base.C.
References libMesh::MeshBase::elements_begin(), libMesh::MeshBase::elements_end(), and end.
 {
   dof_id_type ne=0;
   const_element_iterator       el  = this->elements_begin();
   const const_element_iterator end = this->elements_end();
   for (; el!=end; ++el)
     ne += (*el)->n_sub_elem();
   return ne;
 }
subdomain_id_type libMesh::MeshBase::n_subdomains () const inherited
Returns the number of subdomains in the global mesh. Subdomains correspond to separate subsets of the mesh which could correspond e.g. to different materials in a solid mechanics application, or regions where different physical processes are important. The subdomain mapping is independent from the parallel decomposition.
Definition at line 277 of file mesh_base.C.
References libMesh::MeshBase::subdomain_ids().
Referenced by libMesh::MeshBase::get_info(), libMesh::XdrIO::write(), and libMesh::NameBasedIO::write_nodal_data().
 {
   // This requires an inspection on every processor
   parallel_object_only();
   std::set<subdomain_id_type> ids;
   this->subdomain_ids (ids);
   return cast_int<subdomain_id_type>(ids.size());
 }
dof_id_type libMesh::MeshBase::n_unpartitioned_elem () const inline inherited
Returns the number of elements owned by no processor.
Definition at line 332 of file mesh_base.h.
References libMesh::DofObject::invalid_processor_id, and libMesh::MeshBase::n_elem_on_proc().
Referenced by libMesh::ParallelMesh::parallel_n_elem(), and libMesh::MeshBase::partition().
   { return this->n_elem_on_proc (DofObject::invalid_processor_id); }
dof_id_type libMesh::MeshBase::n_unpartitioned_nodes () const inline inherited
Returns the number of nodes owned by no processor.
Definition at line 238 of file mesh_base.h.
References libMesh::DofObject::invalid_processor_id, and libMesh::MeshBase::n_nodes_on_proc().
Referenced by libMesh::ParallelMesh::parallel_n_nodes().
   { return this->n_nodes_on_proc (DofObject::invalid_processor_id); }
unique_id_type libMesh::MeshBase::next_unique_id () inline inherited
Returns the next unique id to be used.
Definition at line 251 of file mesh_base.h.
References libMesh::MeshBase::_next_unique_id.
 { return _next_unique_id; }
virtual const Node& libMesh::MeshBase::node (const dof_id_type i) const pure virtual inherited
Return a constant reference (for reading only) to the node, which should be present in this processor's subset of the mesh data structure.
Implemented in libMesh::ParallelMesh, and libMesh::SerialMesh.
Referenced by all_second_order(), libMesh::MeshTools::Modification::all_tri(), libMesh::MeshTools::Generation::build_cube(), libMesh::InfElemBuilder::build_inf_elem(), libMesh::MeshBase::cache_elem_dims(), copy_nodes_and_elements(), libMesh::LaplaceMeshSmoother::smooth(), libMesh::MeshTools::Modification::smooth(), and libMesh::LegacyXdrIO::write_mesh().
virtual Node& libMesh::MeshBase::node (const dof_id_type i) pure virtual inherited
Return a reference to the node, which should be present in this processor's subset of the mesh data structure.
Implemented in libMesh::ParallelMesh, and libMesh::SerialMesh.
virtual const Node* libMesh::MeshBase::node_ptr (const dof_id_type i) const pure virtual inherited
Return a pointer to the node, which should be present in this processor's subset of the mesh data structure.
Implemented in libMesh::ParallelMesh, and libMesh::SerialMesh.
Referenced by libMesh::GMVIO::_read_one_cell(), libMesh::SyncNodalPositions::act_on_data(), libMesh::BoundaryInfo::add_node(), libMesh::MeshRefinement::add_node(), libMesh::DofMap::allgather_recursive_constraints(), libMesh::AbaqusIO::assign_boundary_node_ids(), libMesh::TetGenMeshInterface::assign_nodes_to_elem(), libMesh::MeshTools::Generation::build_cube(), libMesh::MeshTools::Generation::build_extrusion(), libMesh::VTKIO::cells_to_vtk(), libMesh::MeshTools::Modification::change_boundary_id(), libMesh::Nemesis_IO_Helper::compute_num_global_nodesets(), libMesh::TriangleWrapper::copy_tri_to_mesh(), create_submesh(), libMesh::MeshTools::Modification::distort(), libMesh::UNVIO::elements_in(), libMesh::MeshData::foreign_id_to_node(), libMesh::SyncNodalPositions::gather_data(), libMesh::DofMap::node_ptr(), libMesh::BoundaryInfo::operator=(), libMesh::Nemesis_IO::read(), libMesh::ExodusII_IO::read(), libMesh::VTKIO::read(), libMesh::CheckpointIO::read_connectivity(), libMesh::AbaqusIO::read_elements(), libMesh::LegacyXdrIO::read_mesh(), libMesh::OFFIO::read_stream(), libMesh::MatlabIO::read_stream(), libMesh::DofMap::scatter_constraints(), libMesh::Partitioner::set_node_processor_ids(), libMesh::LaplaceMeshSmoother::smooth(), libMesh::BoundaryInfo::sync(), libMesh::Parallel::Packing< Elem * >::unpack(), and libMesh::Nemesis_IO_Helper::write_nodal_coordinates().
virtual Node* libMesh::MeshBase::node_ptr (const dof_id_type i) pure virtual inherited
Return a writeable pointer to the node, which should be present in this processor's subset of the mesh data structure.
Implemented in libMesh::ParallelMesh, and libMesh::SerialMesh.
virtual node_iterator libMesh::MeshBase::nodes_begin () pure virtual inherited
Iterate over all the nodes in the Mesh.
Implemented in libMesh::ParallelMesh, and libMesh::SerialMesh.
Referenced by libMesh::EquationSystems::_add_system_to_nodes_and_elems(), all_first_order(), libMesh::EquationSystems::allgather(), libMesh::MeshCommunication::assign_global_indices(), libMesh::MeshTools::Generation::build_extrusion(), libMesh::MeshBase::cache_elem_dims(), copy_nodes_and_elements(), libMesh::DofMap::distribute_dofs(), libMesh::LocationMap< T >::fill(), libMesh::TetGenMeshInterface::fill_pointlist(), libMesh::LocationMap< T >::init(), libMesh::EquationSystems::init(), libMesh::ExodusII_IO_Helper::initialize(), libMesh::DofMap::invalidate_dofs(), libMesh::MeshTools::libmesh_assert_connected_nodes(), libMesh::MeshTools::libmesh_assert_equal_n_systems(), libMesh::MeshCommunication::make_node_unique_ids_parallel_consistent(), libMesh::FEMSystem::mesh_position_set(), libMesh::UNVIO::nodes_out(), libMesh::MeshTools::Subdivision::prepare_subdivision_mesh(), libMesh::System::read_legacy_data(), libMesh::VariationalMeshSmoother::readgr(), libMesh::MeshTools::Modification::redistribute(), libMesh::EquationSystems::reinit(), libMesh::DofMap::reinit(), libMesh::MeshTools::Modification::rotate(), libMesh::MeshTools::Modification::scale(), libMesh::Partitioner::set_node_processor_ids(), libMesh::Partitioner::single_partition(), libMesh::LaplaceMeshSmoother::smooth(), libMesh::BoundaryInfo::sync(), libMesh::MeshTools::Modification::translate(), libMesh::MeshData::translate(), libMesh::Tree< N >::Tree(), libMesh::TriangleInterface::triangulate(), libMesh::ExodusII_IO_Helper::write_nodal_coordinates(), libMesh::UCDIO::write_nodes(), libMesh::CheckpointIO::write_nodes(), and libMesh::VariationalMeshSmoother::writegr().
virtual const_node_iterator libMesh::MeshBase::nodes_begin () const pure virtual inherited
Implemented in libMesh::ParallelMesh, and libMesh::SerialMesh.
virtual node_iterator libMesh::MeshBase::nodes_end () pure virtual inherited
Implemented in libMesh::ParallelMesh, and libMesh::SerialMesh.
Referenced by libMesh::EquationSystems::_add_system_to_nodes_and_elems(), all_first_order(), libMesh::EquationSystems::allgather(), libMesh::MeshCommunication::assign_global_indices(), libMesh::MeshTools::Generation::build_extrusion(), libMesh::MeshBase::cache_elem_dims(), copy_nodes_and_elements(), libMesh::DofMap::distribute_dofs(), libMesh::LocationMap< T >::fill(), libMesh::TetGenMeshInterface::fill_pointlist(), libMesh::LocationMap< T >::init(), libMesh::EquationSystems::init(), libMesh::ExodusII_IO_Helper::initialize(), libMesh::DofMap::invalidate_dofs(), libMesh::MeshTools::libmesh_assert_connected_nodes(), libMesh::MeshTools::libmesh_assert_equal_n_systems(), libMesh::MeshCommunication::make_node_unique_ids_parallel_consistent(), libMesh::FEMSystem::mesh_position_set(), libMesh::UNVIO::nodes_out(), libMesh::MeshTools::Subdivision::prepare_subdivision_mesh(), libMesh::System::read_legacy_data(), libMesh::VariationalMeshSmoother::readgr(), libMesh::MeshTools::Modification::redistribute(), libMesh::EquationSystems::reinit(), libMesh::DofMap::reinit(), libMesh::MeshTools::Modification::rotate(), libMesh::MeshTools::Modification::scale(), libMesh::Partitioner::set_node_processor_ids(), libMesh::Partitioner::single_partition(), libMesh::LaplaceMeshSmoother::smooth(), libMesh::BoundaryInfo::sync(), libMesh::MeshTools::Modification::translate(), libMesh::MeshData::translate(), libMesh::Tree< N >::Tree(), libMesh::TriangleInterface::triangulate(), libMesh::ExodusII_IO_Helper::write_nodal_coordinates(), libMesh::UCDIO::write_nodes(), libMesh::CheckpointIO::write_nodes(), and libMesh::VariationalMeshSmoother::writegr().
virtual const_node_iterator libMesh::MeshBase::nodes_end () const pure virtual inherited
Implemented in libMesh::ParallelMesh, and libMesh::SerialMesh.
virtual element_iterator libMesh::MeshBase::not_active_elements_begin () pure virtual inherited
Implemented in libMesh::ParallelMesh, and libMesh::SerialMesh.
Referenced by libMesh::Partitioner::set_node_processor_ids().
virtual const_element_iterator libMesh::MeshBase::not_active_elements_begin () const pure virtual inherited
Implemented in libMesh::ParallelMesh, and libMesh::SerialMesh.
virtual element_iterator libMesh::MeshBase::not_active_elements_end () pure virtual inherited
Implemented in libMesh::ParallelMesh, and libMesh::SerialMesh.
Referenced by libMesh::Partitioner::set_node_processor_ids().
virtual const_element_iterator libMesh::MeshBase::not_active_elements_end () const pure virtual inherited
Implemented in libMesh::ParallelMesh, and libMesh::SerialMesh.
virtual element_iterator libMesh::MeshBase::not_ancestor_elements_begin () pure virtual inherited
Implemented in libMesh::ParallelMesh, and libMesh::SerialMesh.
virtual const_element_iterator libMesh::MeshBase::not_ancestor_elements_begin () const pure virtual inherited
Implemented in libMesh::ParallelMesh, and libMesh::SerialMesh.
virtual element_iterator libMesh::MeshBase::not_ancestor_elements_end () pure virtual inherited
Implemented in libMesh::ParallelMesh, and libMesh::SerialMesh.
virtual const_element_iterator libMesh::MeshBase::not_ancestor_elements_end () const pure virtual inherited
Implemented in libMesh::ParallelMesh, and libMesh::SerialMesh.
virtual element_iterator libMesh::MeshBase::not_level_elements_begin (unsigned int level) pure virtual inherited
Implemented in libMesh::ParallelMesh, and libMesh::SerialMesh.
virtual const_element_iterator libMesh::MeshBase::not_level_elements_begin (unsigned int level) const pure virtual inherited
Implemented in libMesh::ParallelMesh, and libMesh::SerialMesh.
virtual element_iterator libMesh::MeshBase::not_level_elements_end (unsigned int level) pure virtual inherited
Implemented in libMesh::ParallelMesh, and libMesh::SerialMesh.
virtual const_element_iterator libMesh::MeshBase::not_level_elements_end (unsigned int level) const pure virtual inherited
Implemented in libMesh::ParallelMesh, and libMesh::SerialMesh.
virtual element_iterator libMesh::MeshBase::not_local_elements_begin () pure virtual inherited
Implemented in libMesh::ParallelMesh, and libMesh::SerialMesh.
virtual const_element_iterator libMesh::MeshBase::not_local_elements_begin () const pure virtual inherited
Implemented in libMesh::ParallelMesh, and libMesh::SerialMesh.
virtual element_iterator libMesh::MeshBase::not_local_elements_end () pure virtual inherited
Implemented in libMesh::ParallelMesh, and libMesh::SerialMesh.
virtual const_element_iterator libMesh::MeshBase::not_local_elements_end () const pure virtual inherited
Implemented in libMesh::ParallelMesh, and libMesh::SerialMesh.
virtual element_iterator libMesh::MeshBase::not_subactive_elements_begin () pure virtual inherited
Implemented in libMesh::ParallelMesh, and libMesh::SerialMesh.
virtual const_element_iterator libMesh::MeshBase::not_subactive_elements_begin () const pure virtual inherited
Implemented in libMesh::ParallelMesh, and libMesh::SerialMesh.
virtual element_iterator libMesh::MeshBase::not_subactive_elements_end () pure virtual inherited
Implemented in libMesh::ParallelMesh, and libMesh::SerialMesh.
virtual const_element_iterator libMesh::MeshBase::not_subactive_elements_end () const pure virtual inherited
Implemented in libMesh::ParallelMesh, and libMesh::SerialMesh.
virtual unique_id_type libMesh::MeshBase::parallel_max_unique_id () const pure virtual inherited
Returns a number greater than or equal to the maximum unique_id in the mesh.
Implemented in libMesh::ParallelMesh, and libMesh::SerialMesh.
Referenced by libMesh::BoundaryInfo::add_elements(), libMesh::MeshTools::Modification::all_tri(), and libMesh::ParallelMesh::ParallelMesh().
virtual dof_id_type libMesh::MeshBase::parallel_n_elem () const pure virtual inherited
Returns the number of elements in the mesh. The parallel_n_elem() function returns a newly calculated parallel-synchronized value on distributed meshes, and so must be called in parallel only.
Implemented in libMesh::ParallelMesh, and libMesh::SerialMesh.
Referenced by libMesh::Nemesis_IO_Helper::initialize(), and libMesh::Nemesis_IO::read().
virtual dof_id_type libMesh::MeshBase::parallel_n_nodes () const pure virtual inherited
Returns the number of nodes in the mesh. This function and others must be defined in derived classes since the MeshBase class has no specific storage for nodes or elements. The parallel_n_nodes() function returns a newly calculated parallel-synchronized value on distributed meshes, and so must be called in parallel only.
Implemented in libMesh::ParallelMesh, and libMesh::SerialMesh.
Referenced by libMesh::Nemesis_IO_Helper::initialize(), and libMesh::Nemesis_IO::read().
void libMesh::MeshBase::partition (const unsigned int n_parts) virtual inherited
Call the default partitioner (currently metis_partition()).
Definition at line 405 of file mesh_base.C.
References libMesh::MeshBase::is_serial(), libMesh::libmesh_assert(), libMesh::MeshBase::n_unpartitioned_elem(), libMesh::MeshBase::partitioner(), libMesh::MeshBase::recalculate_n_partitions(), libMesh::Partitioner::set_node_processor_ids(), libMesh::MeshBase::skip_partitioning(), and libMesh::MeshBase::update_post_partitioning().
 {
   // If we get here and we have unpartitioned elements, we need that
   // fixed.
   if (this->n_unpartitioned_elem() > 0)
     {
       libmesh_assert (partitioner().get());
       libmesh_assert (this->is_serial());
       partitioner()->partition (*this, n_parts);
     }
   // NULL partitioner means don't repartition
   // Non-serial meshes may not be ready for repartitioning here.
   else if(!skip_partitioning() &&
           partitioner().get())
     {
       partitioner()->partition (*this, n_parts);
     }
   else
     {
       // Adaptive coarsening may have "orphaned" nodes on processors
       // whose elements no longer share them.  We need to check for
       // and possibly fix that.
       Partitioner::set_node_processor_ids(*this);
       // Make sure locally cached partition count
       this->recalculate_n_partitions();
       // Make sure any other locally cached data is correct
       this->update_post_partitioning();
     }
 }
void libMesh::MeshBase::partition () inline inherited
Definition at line 567 of file mesh_base.h.
References libMesh::ParallelObject::n_processors().
Referenced by libMesh::MeshBase::prepare_for_use().
   { this->partition(this->n_processors()); }
virtual UniquePtr<Partitioner>& libMesh::MeshBase::partitioner () inline virtual inherited
A partitioner to use at each prepare_for_use()
Definition at line 106 of file mesh_base.h.
References libMesh::MeshBase::_partitioner.
Referenced by libMesh::UniformRefinementEstimator::_estimate_error(), libMesh::AdjointRefinementEstimator::estimate_error(), libMesh::MeshBase::partition(), and libMesh::BoundaryInfo::sync().
 { return _partitioner; }
virtual element_iterator libMesh::MeshBase::pid_elements_begin (processor_id_type proc_id) pure virtual inherited
Iterate over all elements with a specified processor id.
Implemented in libMesh::ParallelMesh, and libMesh::SerialMesh.
Referenced by libMesh::BoundaryInfo::_find_id_maps(), libMesh::MeshBase::n_elem_on_proc(), libMesh::MeshTools::processor_bounding_box(), and libMesh::MeshTools::weight().
virtual const_element_iterator libMesh::MeshBase::pid_elements_begin (processor_id_type proc_id) const pure virtual inherited
Implemented in libMesh::ParallelMesh, and libMesh::SerialMesh.
virtual element_iterator libMesh::MeshBase::pid_elements_end (processor_id_type proc_id) pure virtual inherited
Implemented in libMesh::ParallelMesh, and libMesh::SerialMesh.
Referenced by libMesh::BoundaryInfo::_find_id_maps(), libMesh::MeshBase::n_elem_on_proc(), libMesh::MeshTools::processor_bounding_box(), and libMesh::MeshTools::weight().
virtual const_element_iterator libMesh::MeshBase::pid_elements_end (processor_id_type proc_id) const pure virtual inherited
Implemented in libMesh::ParallelMesh, and libMesh::SerialMesh.
virtual node_iterator libMesh::MeshBase::pid_nodes_begin (processor_id_type proc_id) pure virtual inherited
Iterate over nodes with processor_id() == proc_id
Implemented in libMesh::ParallelMesh, and libMesh::SerialMesh.
Referenced by libMesh::MeshTools::bounding_box(), and libMesh::MeshBase::n_nodes_on_proc().
virtual const_node_iterator libMesh::MeshBase::pid_nodes_begin (processor_id_type proc_id) const pure virtual inherited
Implemented in libMesh::ParallelMesh, and libMesh::SerialMesh.
virtual node_iterator libMesh::MeshBase::pid_nodes_end (processor_id_type proc_id) pure virtual inherited
Implemented in libMesh::ParallelMesh, and libMesh::SerialMesh.
Referenced by libMesh::MeshTools::bounding_box(), and libMesh::MeshBase::n_nodes_on_proc().
virtual const_node_iterator libMesh::MeshBase::pid_nodes_end (processor_id_type proc_id) const pure virtual inherited
Implemented in libMesh::ParallelMesh, and libMesh::SerialMesh.
virtual const Point& libMesh::MeshBase::point (const dof_id_type i) const pure virtual inherited
Return a constant reference (for reading only) to the point, which should be present in this processor's subset of the mesh data structure.
Implemented in libMesh::ParallelMesh, and libMesh::SerialMesh.
Referenced by all_second_order(), libMesh::InfElemBuilder::build_inf_elem(), libMesh::LaplaceMeshSmoother::smooth(), libMesh::MeshTools::subdomain_bounding_box(), libMesh::FroIO::write(), libMesh::TetGenIO::write(), libMesh::MEDITIO::write_ascii(), libMesh::TecplotIO::write_ascii(), libMesh::GMVIO::write_ascii_new_impl(), libMesh::GMVIO::write_ascii_old_impl(), libMesh::TecplotIO::write_binary(), libMesh::GMVIO::write_binary(), libMesh::GnuPlotIO::write_solution(), and libMesh::DivaIO::write_stream().
const PointLocatorBase & libMesh::MeshBase::point_locator () const inherited
returns a pointer to a PointLocatorBase object for this mesh, constructing a master PointLocator first if necessary. This should never be used in threaded or non-parallel_only code, and so is deprecated.
Definition at line 460 of file mesh_base.C.
References libMesh::MeshBase::_point_locator, libMesh::PointLocatorBase::build(), libMesh::Threads::in_threads, libMesh::libmesh_assert(), libmesh_nullptr, and libMesh::TREE_ELEMENTS.
 {
   libmesh_deprecated();
   if (_point_locator.get() == libmesh_nullptr)
     {
       // PointLocator construction may not be safe within threads
       libmesh_assert(!Threads::in_threads);
       _point_locator.reset (PointLocatorBase::build(TREE_ELEMENTS, *this).release());
     }
   return *_point_locator;
 }
void libMesh::MeshBase::prepare_for_use (const bool skip_renumber_nodes_and_elements = false, const bool skip_find_neighbors = false) inherited
Prepare a newly created (or read) mesh for use. This involves 4 steps: 1.) call find_neighbors() 2.) call partition() 3.) call renumber_nodes_and_elements() 4.) call cache_elem_dims()
The argument to skip renumbering is now deprecated - to prevent a mesh from being renumbered, set allow_renumbering(false).
Definition at line 153 of file mesh_base.C.
References libMesh::MeshBase::_is_prepared, libMesh::MeshBase::_skip_renumber_nodes_and_elements, libMesh::MeshBase::allow_renumbering(), libMesh::MeshBase::cache_elem_dims(), libMesh::MeshBase::clear_point_locator(), libMesh::ParallelObject::comm(), libMesh::MeshBase::delete_remote_elements(), libMesh::MeshBase::detect_interior_parents(), libMesh::MeshBase::find_neighbors(), libMesh::MeshBase::is_serial(), libMesh::libmesh_assert(), libMesh::MeshTools::libmesh_assert_valid_unique_ids(), libMesh::MeshBase::partition(), libMesh::MeshBase::renumber_nodes_and_elements(), libMesh::MeshBase::update_parallel_id_counts(), and libMesh::Parallel::verify().
Referenced by all_first_order(), all_second_order(), libMesh::MeshTools::Subdivision::all_subdivision(), libMesh::MeshTools::Modification::all_tri(), libMesh::MeshTools::Generation::build_cube(), libMesh::MeshTools::Generation::build_extrusion(), libMesh::InfElemBuilder::build_inf_elem(), libMesh::MeshRefinement::coarsen_elements(), copy_nodes_and_elements(), create_submesh(), libMesh::MeshTools::Modification::flatten(), libMesh::MeshTools::Subdivision::prepare_subdivision_mesh(), libMesh::GMVIO::read(), read(), libMesh::MeshRefinement::refine_and_coarsen_elements(), libMesh::MeshRefinement::refine_elements(), libMesh::SerialMesh::stitching_helper(), libMesh::BoundaryInfo::sync(), libMesh::MeshRefinement::uniformly_coarsen(), and libMesh::MeshRefinement::uniformly_refine().
 {
   parallel_object_only();
   libmesh_assert(this->comm().verify(this->is_serial()));
   // A distributed mesh may have processors with no elements (or
   // processors with no elements of higher dimension, if we ever
   // support mixed-dimension meshes), but we want consistent
   // mesh_dimension anyways.
   //
   // cache_elem_dims() should get the elem_dimensions() and
   // mesh_dimension() correct later, and we don't need it earlier.
   // Renumber the nodes and elements so that they in contiguous
   // blocks.  By default, _skip_renumber_nodes_and_elements is false.
   //
   // We may currently change that by passing
   // skip_renumber_nodes_and_elements==true to this function, but we
   // should use the allow_renumbering() accessor instead.
   //
   // Instances where you if prepare_for_use() should not renumber the nodes
   // and elements include reading in e.g. an xda/r or gmv file. In
   // this case, the ordering of the nodes may depend on an accompanying
   // solution, and the node ordering cannot be changed.
   if (skip_renumber_nodes_and_elements)
     {
       libmesh_deprecated();
       this->allow_renumbering(false);
     }
   // Mesh modification operations might not leave us with consistent
   // id counts, but our partitioner might need that consistency.
   if(!_skip_renumber_nodes_and_elements)
     this->renumber_nodes_and_elements();
   else
     this->update_parallel_id_counts();
   // Let all the elements find their neighbors
   if(!skip_find_neighbors)
     this->find_neighbors();
   // Search the mesh for all the dimensions of the elements
   // and cache them.
   this->cache_elem_dims();
   // Search the mesh for elements that have a neighboring element
   // of dim+1 and set that element as the interior parent
   this->detect_interior_parents();
   // Fix up node unique ids in case mesh generation code didn't take
   // exceptional care to do so.
 //  MeshCommunication().make_node_unique_ids_parallel_consistent(*this);
   // We're going to still require that mesh generation code gets
   // element unique ids consistent.
 #if defined(DEBUG) && defined(LIBMESH_ENABLE_UNIQUE_ID)
   MeshTools::libmesh_assert_valid_unique_ids(*this);
 #endif
   // Partition the mesh.
   this->partition();
   // If we're using ParallelMesh, we'll want it parallelized.
   this->delete_remote_elements();
   if(!_skip_renumber_nodes_and_elements)
     this->renumber_nodes_and_elements();
   // Reset our PointLocator.  This needs to happen any time the elements
   // in the underlying elements in the mesh have changed, so we do it here.
   this->clear_point_locator();
   // The mesh is now prepared for use.
   _is_prepared = true;
 #if defined(DEBUG) && defined(LIBMESH_ENABLE_UNIQUE_ID)
   MeshTools::libmesh_assert_valid_unique_ids(*this);
 #endif
 }
void libMesh::MeshBase::print_info (std::ostream & os = libMesh::out) const inherited
Prints relevant information about the mesh.
Definition at line 391 of file mesh_base.C.
References libMesh::MeshBase::get_info().
Referenced by libMesh::InfElemBuilder::build_inf_elem(), and libMesh::operator<<().
 {
   os << this->get_info()
      << std::endl;
 }
processor_id_type libMesh::ParallelObject::processor_id () const inline inherited
Returns
the rank of this processor in the group.
Definition at line 99 of file parallel_object.h.
References libMesh::ParallelObject::_communicator, and libMesh::Parallel::Communicator::rank().
Referenced by libMesh::MetisPartitioner::_do_partition(), libMesh::BoundaryInfo::_find_id_maps(), libMesh::EquationSystems::_read_impl(), libMesh::ParallelMesh::add_elem(), libMesh::BoundaryInfo::add_elements(), libMesh::DofMap::add_neighbors_to_send_list(), libMesh::ParallelMesh::add_node(), all_second_order(), libMesh::MeshTools::Modification::all_tri(), libMesh::FEMSystem::assembly(), libMesh::ParmetisPartitioner::assign_partitioning(), libMesh::EquationSystems::build_discontinuous_solution_vector(), libMesh::Nemesis_IO_Helper::build_element_and_node_maps(), libMesh::ParmetisPartitioner::build_graph(), libMesh::InfElemBuilder::build_inf_elem(), libMesh::DofMap::build_sparsity(), libMesh::ParallelMesh::clear(), libMesh::ExodusII_IO_Helper::close(), libMesh::Nemesis_IO_Helper::compute_border_node_ids(), libMesh::Nemesis_IO_Helper::compute_communication_map_parameters(), libMesh::Nemesis_IO_Helper::compute_internal_and_border_elems_and_internal_nodes(), libMesh::Nemesis_IO_Helper::compute_node_communication_maps(), libMesh::Nemesis_IO_Helper::compute_num_global_elem_blocks(), libMesh::Nemesis_IO_Helper::compute_num_global_nodesets(), libMesh::Nemesis_IO_Helper::compute_num_global_sidesets(), libMesh::Nemesis_IO_Helper::construct_nemesis_filename(), libMesh::ExodusII_IO_Helper::create(), libMesh::ParallelMesh::delete_elem(), libMesh::ParallelMesh::delete_node(), libMesh::DofMap::distribute_dofs(), libMesh::DofMap::distribute_local_dofs_node_major(), libMesh::DofMap::distribute_local_dofs_var_major(), libMesh::DofMap::end_dof(), libMesh::DofMap::end_old_dof(), libMesh::EnsightIO::EnsightIO(), libMesh::MeshFunction::find_element(), find_neighbors(), libMesh::DofMap::first_dof(), libMesh::DofMap::first_old_dof(), libMesh::Nemesis_IO_Helper::get_cmap_params(), libMesh::Nemesis_IO_Helper::get_eb_info_global(), libMesh::Nemesis_IO_Helper::get_elem_cmap(), libMesh::Nemesis_IO_Helper::get_elem_map(), libMesh::MeshBase::get_info(), libMesh::Nemesis_IO_Helper::get_init_global(), libMesh::Nemesis_IO_Helper::get_init_info(), libMesh::Nemesis_IO_Helper::get_loadbal_param(), libMesh::Nemesis_IO_Helper::get_node_cmap(), libMesh::Nemesis_IO_Helper::get_node_map(), libMesh::Nemesis_IO_Helper::get_ns_param_global(), libMesh::Nemesis_IO_Helper::get_ss_param_global(), libMesh::SystemSubsetBySubdomain::init(), libMesh::ParmetisPartitioner::initialize(), libMesh::ExodusII_IO_Helper::initialize(), libMesh::ExodusII_IO_Helper::initialize_element_variables(), libMesh::ExodusII_IO_Helper::initialize_global_variables(), libMesh::ExodusII_IO_Helper::initialize_nodal_variables(), libMesh::ParallelMesh::insert_elem(), libMesh::DofMap::last_dof(), libMesh::MeshTools::libmesh_assert_valid_neighbors(), libMesh::ParallelMesh::libmesh_assert_valid_parallel_object_ids(), libMesh::MeshTools::libmesh_assert_valid_procids< Elem >(), libMesh::MeshTools::libmesh_assert_valid_procids< Node >(), libMesh::DofMap::local_variable_indices(), libMesh::MeshRefinement::make_coarsening_compatible(), libMesh::MeshBase::n_active_local_elem(), libMesh::BoundaryInfo::n_boundary_conds(), libMesh::BoundaryInfo::n_edge_conds(), libMesh::DofMap::n_local_dofs(), libMesh::System::n_local_dofs(), libMesh::MeshBase::n_local_elem(), libMesh::MeshBase::n_local_nodes(), libMesh::BoundaryInfo::n_nodeset_conds(), libMesh::WeightedPatchRecoveryErrorEstimator::EstimateError::operator()(), libMesh::SparsityPattern::Build::operator()(), libMesh::PatchRecoveryErrorEstimator::EstimateError::operator()(), libMesh::System::point_gradient(), libMesh::System::point_hessian(), libMesh::System::point_value(), libMesh::System::project_vector(), libMesh::Nemesis_IO_Helper::put_cmap_params(), libMesh::Nemesis_IO_Helper::put_elem_cmap(), libMesh::Nemesis_IO_Helper::put_elem_map(), libMesh::Nemesis_IO_Helper::put_loadbal_param(), libMesh::Nemesis_IO_Helper::put_node_cmap(), libMesh::Nemesis_IO_Helper::put_node_map(), libMesh::NameBasedIO::read(), libMesh::Nemesis_IO::read(), libMesh::CheckpointIO::read(), libMesh::XdrIO::read(), libMesh::ExodusII_IO_Helper::read_elem_num_map(), libMesh::System::read_header(), libMesh::System::read_legacy_data(), libMesh::ExodusII_IO_Helper::read_node_num_map(), libMesh::System::read_parallel_data(), libMesh::System::read_SCALAR_dofs(), libMesh::XdrIO::read_serialized_bc_names(), libMesh::XdrIO::read_serialized_bcs(), libMesh::System::read_serialized_blocked_dof_objects(), libMesh::XdrIO::read_serialized_connectivity(), libMesh::System::read_serialized_data(), libMesh::XdrIO::read_serialized_nodes(), libMesh::XdrIO::read_serialized_nodesets(), libMesh::XdrIO::read_serialized_subdomain_names(), libMesh::System::read_serialized_vector(), libMesh::System::read_serialized_vectors(), libMesh::MeshData::read_xdr(), libMesh::ParallelMesh::renumber_dof_objects(), libMesh::Partitioner::set_node_processor_ids(), libMesh::DofMap::set_nonlocal_dof_objects(), libMesh::LaplaceMeshSmoother::smooth(), libMesh::MeshTools::total_weight(), libMesh::Parallel::Packing< Node * >::unpack(), libMesh::Parallel::Packing< Elem * >::unpack(), libMesh::ParallelMesh::update_parallel_id_counts(), libMesh::MeshTools::weight(), libMesh::NameBasedIO::write(), libMesh::ExodusII_IO::write(), libMesh::CheckpointIO::write(), libMesh::XdrIO::write(), libMesh::EquationSystems::write(), libMesh::GMVIO::write_discontinuous_gmv(), libMesh::ExodusII_IO::write_element_data(), libMesh::ExodusII_IO_Helper::write_element_values(), libMesh::ExodusII_IO_Helper::write_elements(), libMesh::ExodusII_IO::write_global_data(), libMesh::ExodusII_IO_Helper::write_global_values(), libMesh::System::write_header(), libMesh::ExodusII_IO::write_information_records(), libMesh::ExodusII_IO_Helper::write_information_records(), libMesh::ExodusII_IO_Helper::write_nodal_coordinates(), libMesh::UCDIO::write_nodal_data(), libMesh::ExodusII_IO::write_nodal_data(), libMesh::ExodusII_IO::write_nodal_data_discontinuous(), libMesh::ExodusII_IO_Helper::write_nodal_values(), libMesh::Nemesis_IO_Helper::write_nodesets(), libMesh::ExodusII_IO_Helper::write_nodesets(), libMesh::System::write_parallel_data(), libMesh::System::write_SCALAR_dofs(), libMesh::XdrIO::write_serialized_bc_names(), libMesh::XdrIO::write_serialized_bcs(), libMesh::System::write_serialized_blocked_dof_objects(), libMesh::XdrIO::write_serialized_connectivity(), libMesh::System::write_serialized_data(), libMesh::XdrIO::write_serialized_nodes(), libMesh::XdrIO::write_serialized_nodesets(), libMesh::XdrIO::write_serialized_subdomain_names(), libMesh::System::write_serialized_vector(), libMesh::System::write_serialized_vectors(), libMesh::Nemesis_IO_Helper::write_sidesets(), libMesh::ExodusII_IO_Helper::write_sidesets(), libMesh::ExodusII_IO::write_timestep(), and libMesh::ExodusII_IO_Helper::write_timestep().
   { return cast_int<processor_id_type>(_communicator.rank()); }
virtual const Elem* libMesh::MeshBase::query_elem (const dof_id_type i) const pure virtual inherited
Return a pointer to the element, or NULL if no such element exists in this processor's mesh data structure.
Implemented in libMesh::ParallelMesh, and libMesh::SerialMesh.
Referenced by libMesh::MeshRefinement::flag_elements_by_nelem_target(), libMesh::MeshTools::libmesh_assert_valid_dof_ids(), libMesh::MeshTools::libmesh_assert_valid_neighbors(), libMesh::MeshTools::libmesh_assert_valid_procids< Elem >(), libMesh::MeshTools::libmesh_assert_valid_unique_ids(), and libMesh::Parallel::Packing< Elem * >::unpack().
virtual Elem* libMesh::MeshBase::query_elem (const dof_id_type i) pure virtual inherited
Return a writeable pointer to the element, or NULL if no such element exists in this processor's mesh data structure.
Implemented in libMesh::ParallelMesh, and libMesh::SerialMesh.
virtual const Node* libMesh::MeshBase::query_node_ptr (const dof_id_type i) const pure virtual inherited
Return a pointer to the node, or NULL if no such node exists in this processor's mesh data structure.
Implemented in libMesh::ParallelMesh, and libMesh::SerialMesh.
Referenced by create_submesh(), libMesh::MeshTools::libmesh_assert_valid_dof_ids(), libMesh::MeshTools::libmesh_assert_valid_procids< Node >(), libMesh::MeshTools::libmesh_assert_valid_unique_ids(), and libMesh::Parallel::Packing< Node * >::unpack().
virtual Node* libMesh::MeshBase::query_node_ptr (const dof_id_type i) pure virtual inherited
Return a writeable pointer to the node, or NULL if no such node exists in this processor's mesh data structure.
Implemented in libMesh::ParallelMesh, and libMesh::SerialMesh.
void libMesh::UnstructuredMesh::read (const std::string & name, MeshData * mesh_data = libmesh_nullptr, bool skip_renumber_nodes_and_elements = false) virtual
Reads the file specified by name. Attempts to figure out the proper method by the file extension. This is now the only way to read a mesh. The UnstructuredMesh then initializes its data structures and is ready for use.
In order to read the UNV and TetGen file types, you must also pass a separate pointer to the MeshData object you will use with this mesh, since these read methods expect it.
The skip_renumber_nodes_and_elements argument is now deprecated - to disallow renumbering, set MeshBase::allow_renumbering(false)
Implements libMesh::MeshBase.
Definition at line 578 of file unstructured_mesh.C.
References libMesh::MeshBase::allow_renumbering(), libMesh::MeshBase::prepare_for_use(), libMesh::NameBasedIO::read(), libMesh::TetGenIO::read(), and libMesh::UNVIO::read().
 {
   // Set the skip_renumber_nodes_and_elements flag on all processors
   // if necessary.
   // This ensures that renumber_nodes_and_elements is *not* called
   // during prepare_for_use() for certain types of mesh files.
   // This is required in cases where there is an associated solution
   // file which expects a certain ordering of the nodes.
   if(name.rfind(".gmv")+4==name.size())
     {
       skip_renumber_nodes_and_elements =  true;
     }
   if (mesh_data)
     {
       libmesh_deprecated();
       if (name.rfind(".unv") < name.size())
         UNVIO(*this, mesh_data).read (name);
       else if ((name.rfind(".node")  < name.size()) ||
                (name.rfind(".ele")   < name.size()))
         TetGenIO(*this,mesh_data).read (name);
     }
   else
     NameBasedIO(*this).read(name);
   if (skip_renumber_nodes_and_elements)
     {
       // Use MeshBase::allow_renumbering() yourself instead.
       libmesh_deprecated();
       this->allow_renumbering(false);
     }
   // Done reading the mesh.  Now prepare it for use.
   this->prepare_for_use();
 }
unsigned int libMesh::MeshBase::recalculate_n_partitions () inherited
In a few (very rare) cases, the user may have manually tagged the elements with specific processor IDs by hand, without using a partitioner. In this case, the Mesh will not know that the total number of partitions, _n_parts, has changed, unless you call this function. This is an O(N active elements) calculation. The return value is the number of partitions, and _n_parts is also set by this function.
Definition at line 437 of file mesh_base.C.
References libMesh::MeshBase::_n_parts, libMesh::MeshBase::active_local_elements_begin(), libMesh::MeshBase::active_local_elements_end(), libMesh::ParallelObject::comm(), end, std::max(), and libMesh::Parallel::Communicator::max().
Referenced by libMesh::MeshBase::partition().
 {
   // This requires an inspection on every processor
   parallel_object_only();
   const_element_iterator el  = this->active_local_elements_begin();
   const_element_iterator end = this->active_local_elements_end();
   unsigned int max_proc_id=0;
   for (; el!=end; ++el)
     max_proc_id = std::max(max_proc_id, static_cast<unsigned int>((*el)->processor_id()));
   // The number of partitions is one more than the max processor ID.
   _n_parts = max_proc_id+1;
   this->comm().max(_n_parts);
   return _n_parts;
 }
virtual void libMesh::MeshBase::redistribute () inline virtual inherited
Redistribute elements between processors. This gets called automatically by the Partitioner, and is a no-op in the case of a SerialMesh or serialized ParallelMesh
Reimplemented in libMesh::ParallelMesh.
Definition at line 575 of file mesh_base.h.
Referenced by libMesh::Partitioner::partition().
 {}
virtual void libMesh::MeshBase::renumber_elem (dof_id_type old_id, dof_id_type new_id) pure virtual inherited
Changes the id of element old_id, both by changing elem(old_id)->id() and by moving elem(old_id) in the mesh's internal container. No element with the id new_id should already exist.
Implemented in libMesh::ParallelMesh, and libMesh::SerialMesh.
virtual void libMesh::MeshBase::renumber_node (dof_id_type old_id, dof_id_type new_id) pure virtual inherited
Changes the id of node old_id, both by changing node(old_id)->id() and by moving node(old_id) in the mesh's internal container. No element with the id new_id should already exist.
Implemented in libMesh::ParallelMesh, and libMesh::SerialMesh.
virtual void libMesh::MeshBase::renumber_nodes_and_elements () pure virtual inherited
After partitoning a mesh it is useful to renumber the nodes and elements so that they lie in contiguous blocks on the processors. This method does just that.
Implemented in libMesh::ParallelMesh, and libMesh::SerialMesh.
Referenced by all_first_order(), all_second_order(), contract(), libMesh::ErrorVector::plot_error(), and libMesh::MeshBase::prepare_for_use().
virtual void libMesh::MeshBase::reserve_elem (const dof_id_type ne) pure virtual inherited
Reserves space for a known number of elements. Note that this method may or may not do anything, depending on the actual Mesh implementation. If you know the number of elements you will add and call this method before repeatedly calling add_point() the implementation will be more efficient.
Implemented in libMesh::ParallelMesh, and libMesh::SerialMesh.
Referenced by libMesh::MeshTools::Generation::build_cube(), libMesh::MeshTools::Generation::build_extrusion(), copy_nodes_and_elements(), libMesh::ExodusII_IO::read(), libMesh::XdrIO::read(), and libMesh::LegacyXdrIO::read_mesh().
virtual void libMesh::MeshBase::reserve_nodes (const dof_id_type nn) pure virtual inherited
Reserves space for a known number of nodes. Note that this method may or may not do anything, depending on the actual Mesh implementation. If you know the number of nodes you will add and call this method before repeatedly calling add_point() the implementation will be more efficient.
Implemented in libMesh::ParallelMesh, and libMesh::SerialMesh.
Referenced by all_second_order(), libMesh::MeshTools::Generation::build_cube(), libMesh::MeshTools::Generation::build_extrusion(), copy_nodes_and_elements(), libMesh::ExodusII_IO::read(), libMesh::XdrIO::read(), and libMesh::LegacyXdrIO::read_mesh().
virtual element_iterator libMesh::MeshBase::semilocal_elements_begin () pure virtual inherited
Iterate over elements for which elem->is_semilocal() returns true for the current processor.
Implemented in libMesh::ParallelMesh, and libMesh::SerialMesh.
virtual const_element_iterator libMesh::MeshBase::semilocal_elements_begin () const pure virtual inherited
Implemented in libMesh::ParallelMesh, and libMesh::SerialMesh.
virtual element_iterator libMesh::MeshBase::semilocal_elements_end () pure virtual inherited
Implemented in libMesh::ParallelMesh, and libMesh::SerialMesh.
virtual const_element_iterator libMesh::MeshBase::semilocal_elements_end () const pure virtual inherited
Implemented in libMesh::ParallelMesh, and libMesh::SerialMesh.
void libMesh::MeshBase::set_mesh_dimension (unsigned char d) inline inherited
Resets the logical dimension of the mesh. If the mesh has elements of multiple dimensions, this should be set to the largest dimension. E.g. if the mesh has 1D and 2D elements, this should be set to 2. If the mesh has 2D and 3D elements, this should be set to 3.
Definition at line 165 of file mesh_base.h.
References libMesh::MeshBase::_elem_dims.
Referenced by libMesh::MeshTools::Generation::build_cube(), libMesh::MeshTools::Generation::build_delaunay_square(), libMesh::TriangleWrapper::copy_tri_to_mesh(), libMesh::AbaqusIO::read(), libMesh::Nemesis_IO::read(), libMesh::GMVIO::read(), libMesh::ExodusII_IO::read(), libMesh::VTKIO::read(), libMesh::CheckpointIO::read_connectivity(), libMesh::LegacyXdrIO::read_mesh(), libMesh::XdrIO::read_serialized_connectivity(), libMesh::OFFIO::read_stream(), libMesh::MatlabIO::read_stream(), and libMesh::TriangleInterface::triangulate().
   { _elem_dims.clear(); _elem_dims.insert(d); }
unsigned int& libMesh::MeshBase::set_n_partitions () inline protected inherited
Returns a writeable reference to the number of partitions.
Definition at line 1017 of file mesh_base.h.
References libMesh::MeshBase::_n_parts.
Referenced by libMesh::Partitioner::partition(), libMesh::Partitioner::repartition(), and libMesh::BoundaryInfo::sync().
   { return _n_parts; }
void libMesh::MeshBase::set_next_unique_id (unique_id_type id) inline inherited
Sets the next unique id to be used.
Definition at line 256 of file mesh_base.h.
References libMesh::MeshBase::_next_unique_id.
 { _next_unique_id = id; }
void libMesh::MeshBase::set_spatial_dimension (unsigned char d) inherited
Sets the "spatial dimension" of the Mesh. See the documentation for Mesh::spatial_dimension() for more information.
Definition at line 143 of file mesh_base.C.
References libMesh::MeshBase::_spatial_dimension.
Referenced by libMesh::MeshTools::Generation::build_cube().
 {
   // The user can set the _spatial_dimension however they wish,
   // libMesh will only *increase* the spatial dimension, however,
   // never decrease it.
   _spatial_dimension = d;
 }
std::map<subdomain_id_type, std::string>& libMesh::MeshBase::set_subdomain_name_map () inline inherited
Return a writeable reference to the whole subdomain name map
Definition at line 981 of file mesh_base.h.
References libMesh::MeshBase::_block_id_to_name.
Referenced by libMesh::XdrIO::read_serialized_subdomain_names(), and libMesh::CheckpointIO::read_subdomain_names().
   { return _block_id_to_name; }
void libMesh::MeshBase::skip_partitioning (bool skip) inline inherited
If true is passed in then this mesh will no longer be (re)partitioned. It would probably be a bad idea to call this on a Serial Mesh before the first partitioning has happened... because no elements would get assigned to your processor pool.
Note that turning on skip_partitioning() can have adverse effects on your performance when using AMR... ie you could get large load imbalances.
However you might still want to use this if the communication and computation of the rebalance and repartition is too high for your application.
Definition at line 604 of file mesh_base.h.
References libMesh::MeshBase::_skip_partitioning.
Referenced by copy_nodes_and_elements().
 { _skip_partitioning = skip; }
bool libMesh::MeshBase::skip_partitioning () const inline inherited
Definition at line 605 of file mesh_base.h.
References libMesh::MeshBase::_skip_partitioning.
Referenced by copy_nodes_and_elements(), and libMesh::MeshBase::partition().
 { return _skip_partitioning; }
unsigned int libMesh::MeshBase::spatial_dimension () const inherited
Returns the "spatial dimension" of the mesh. The spatial dimension is defined as:
1 - for an exactly x-aligned mesh of 1D elements 2 - for an exactly x-y planar mesh of 2D elements 3 - otherwise
No tolerance checks are performed to determine whether the Mesh is x-aligned or x-y planar, only strict equality with zero in the higher dimensions is checked. Also, x-z and y-z planar meshes are considered to have spatial dimension == 3.
The spatial dimension is updated during prepare_for_use() based on the dimensions of the various elements present in the Mesh, but is never automatically decreased by this function.
For example, if the user calls set_spatial_dimension(2) and then later inserts 3D elements into the mesh, Mesh::spatial_dimension() will return 3 after the next call to prepare_for_use(). On the other hand, if the user calls set_spatial_dimension(3) and then inserts only x-aligned 1D elements into the Mesh, mesh.spatial_dimension() will remain 3.
Definition at line 136 of file mesh_base.C.
References libMesh::MeshBase::_spatial_dimension.
Referenced by libMesh::MeshBase::get_info(), and libMesh::ExodusII_IO_Helper::initialize().
 {
   return cast_int<unsigned int>(_spatial_dimension);
 }
UniquePtr< PointLocatorBase > libMesh::MeshBase::sub_point_locator () const inherited
returns a pointer to a subordinate PointLocatorBase object for this mesh, constructing a master PointLocator first if necessary. This should not be used in threaded or non-parallel_only code unless the master has already been constructed.
Definition at line 476 of file mesh_base.C.
References libMesh::MeshBase::_point_locator, libMesh::PointLocatorBase::build(), libMesh::Threads::in_threads, libMesh::libmesh_assert(), libmesh_nullptr, and libMesh::TREE_ELEMENTS.
Referenced by libMesh::DofMap::create_dof_constraints(), libMesh::MeshFunction::init(), libMesh::MeshRefinement::make_coarsening_compatible(), libMesh::MeshRefinement::make_refinement_compatible(), libMesh::System::point_gradient(), libMesh::System::point_hessian(), libMesh::System::point_value(), libMesh::SerialMesh::stitching_helper(), and libMesh::MeshRefinement::test_level_one().
 {
   // If there's no master point locator, then we need one.
   if (_point_locator.get() == libmesh_nullptr)
     {
       // PointLocator construction may not be safe within threads
       libmesh_assert(!Threads::in_threads);
       // And it may require parallel communication
       parallel_object_only();
       _point_locator.reset (PointLocatorBase::build(TREE_ELEMENTS, *this).release());
     }
   // Otherwise there was a master point locator, and we can grab a
   // sub-locator easily.
   return PointLocatorBase::build(TREE_ELEMENTS, *this, _point_locator.get());
 }
virtual element_iterator libMesh::MeshBase::subactive_elements_begin () pure virtual inherited
Iterate over elements for which elem->subactive() returns true.
Implemented in libMesh::ParallelMesh, and libMesh::SerialMesh.
Referenced by libMesh::Partitioner::set_node_processor_ids().
virtual const_element_iterator libMesh::MeshBase::subactive_elements_begin () const pure virtual inherited
Implemented in libMesh::ParallelMesh, and libMesh::SerialMesh.
virtual element_iterator libMesh::MeshBase::subactive_elements_end () pure virtual inherited
Implemented in libMesh::ParallelMesh, and libMesh::SerialMesh.
Referenced by libMesh::Partitioner::set_node_processor_ids().
virtual const_element_iterator libMesh::MeshBase::subactive_elements_end () const pure virtual inherited
Implemented in libMesh::ParallelMesh, and libMesh::SerialMesh.
void libMesh::MeshBase::subdomain_ids (std::set< subdomain_id_type > & ids) const inherited
Constructs a list of all subdomain identifiers in the global mesh. Subdomains correspond to separate subsets of the mesh which could correspond e.g. to different materials in a solid mechanics application, or regions where different physical processes are important. The subdomain mapping is independent from the parallel decomposition.
Definition at line 258 of file mesh_base.C.
References libMesh::MeshBase::active_local_elements_begin(), libMesh::MeshBase::active_local_elements_end(), libMesh::ParallelObject::comm(), end, and libMesh::Parallel::Communicator::set_union().
Referenced by libMesh::MeshBase::n_subdomains(), and libMesh::TecplotIO::TecplotIO().
 {
   // This requires an inspection on every processor
   parallel_object_only();
   ids.clear();
   const_element_iterator el  = this->active_local_elements_begin();
   const_element_iterator end = this->active_local_elements_end();
   for (; el!=end; ++el)
     ids.insert((*el)->subdomain_id());
   // Some subdomains may only live on other processors
   this->comm().set_union(ids);
 }
std::string & libMesh::MeshBase::subdomain_name (subdomain_id_type id) inherited
Returns a writable reference for getting/setting an optional name for a subdomain.
Definition at line 504 of file mesh_base.C.
References libMesh::MeshBase::_block_id_to_name.
Referenced by libMesh::AbaqusIO::assign_subdomain_ids(), DMlibMeshSetSystem_libMesh(), libMesh::UNVIO::groups_in(), libMesh::ExodusII_IO::read(), libMesh::TecplotIO::write_binary(), and libMesh::ExodusII_IO_Helper::write_elements().
 {
   return _block_id_to_name[id];
 }
const std::string & libMesh::MeshBase::subdomain_name (subdomain_id_type id) const inherited
Definition at line 509 of file mesh_base.C.
References libMesh::MeshBase::_block_id_to_name.
 {
   // An empty string to return when no matching subdomain name is found
   static const std::string empty;
   std::map<subdomain_id_type, std::string>::const_iterator iter = _block_id_to_name.find(id);
   if (iter == _block_id_to_name.end())
     return empty;
   else
     return iter->second;
 }
virtual element_iterator libMesh::MeshBase::type_elements_begin (ElemType type) pure virtual inherited
Iterate over all elements with a specified geometric type.
Implemented in libMesh::ParallelMesh, and libMesh::SerialMesh.
Referenced by libMesh::MeshTools::n_elem_of_type(), and libMesh::MeshTools::n_non_subactive_elem_of_type_at_level().
virtual const_element_iterator libMesh::MeshBase::type_elements_begin (ElemType type) const pure virtual inherited
Implemented in libMesh::ParallelMesh, and libMesh::SerialMesh.
virtual element_iterator libMesh::MeshBase::type_elements_end (ElemType type) pure virtual inherited
Implemented in libMesh::ParallelMesh, and libMesh::SerialMesh.
Referenced by libMesh::MeshTools::n_elem_of_type(), and libMesh::MeshTools::n_non_subactive_elem_of_type_at_level().
virtual const_element_iterator libMesh::MeshBase::type_elements_end (ElemType type) const pure virtual inherited
Implemented in libMesh::ParallelMesh, and libMesh::SerialMesh.
virtual element_iterator libMesh::MeshBase::unpartitioned_elements_begin () pure virtual inherited
Iterate over unpartitioned elements in the Mesh.
Implemented in libMesh::ParallelMesh, and libMesh::SerialMesh.
Referenced by libMesh::MeshTools::n_active_levels(), libMesh::MeshTools::n_levels(), libMesh::MeshTools::n_p_levels(), libMesh::Partitioner::partition_unpartitioned_elements(), and libMesh::Partitioner::set_node_processor_ids().
virtual const_element_iterator libMesh::MeshBase::unpartitioned_elements_begin () const pure virtual inherited
Implemented in libMesh::ParallelMesh, and libMesh::SerialMesh.
virtual element_iterator libMesh::MeshBase::unpartitioned_elements_end () pure virtual inherited
Implemented in libMesh::ParallelMesh, and libMesh::SerialMesh.
Referenced by libMesh::MeshTools::n_active_levels(), libMesh::MeshTools::n_levels(), libMesh::MeshTools::n_p_levels(), libMesh::Partitioner::partition_unpartitioned_elements(), and libMesh::Partitioner::set_node_processor_ids().
virtual const_element_iterator libMesh::MeshBase::unpartitioned_elements_end () const pure virtual inherited
Implemented in libMesh::ParallelMesh, and libMesh::SerialMesh.
virtual void libMesh::MeshBase::update_parallel_id_counts () pure virtual inherited
Updates parallel caches so that methods like n_elem() accurately reflect changes on other processors
Implemented in libMesh::ParallelMesh, and libMesh::SerialMesh.
Referenced by libMesh::MeshRefinement::_coarsen_elements(), libMesh::MeshRefinement::_refine_elements(), and libMesh::MeshBase::prepare_for_use().
virtual void libMesh::MeshBase::update_post_partitioning () inline virtual inherited
Recalculate any cached data after elements and nodes have been repartitioned.
Reimplemented in libMesh::ParallelMesh.
Definition at line 581 of file mesh_base.h.
Referenced by libMesh::Partitioner::partition(), libMesh::MeshBase::partition(), and libMesh::Nemesis_IO::read().
 {}
void libMesh::UnstructuredMesh::write (const std::string & name, MeshData * mesh_data = libmesh_nullptr) virtual
Write the file specified by name. Attempts to figure out the proper method by the file extension.
In order to write the UNV and TetGen file types, you must also pass a separate pointer to the MeshData object you have been using with this mesh, since these write methods expect it.
Implements libMesh::MeshBase.
Definition at line 618 of file unstructured_mesh.C.
References libMesh::START_LOG(), libMesh::STOP_LOG(), libMesh::NameBasedIO::write(), and libMesh::UNVIO::write().
 {
   START_LOG("write()", "Mesh");
   if (mesh_data)
     {
       libmesh_deprecated();
       if (name.rfind(".unv") < name.size())
         UNVIO(*this, mesh_data).write (name);
       else
         libmesh_error_msg("Only UNV output supports MeshData");
     }
   NameBasedIO(*this).write(name);
   STOP_LOG("write()", "Mesh");
 }
void libMesh::UnstructuredMesh::write (const std::string & name, const std::vector< Number > & values, const std::vector< std::string > & variable_names)
Write to the file specified by name. Attempts to figure out the proper method by the file extension. Also writes data.
Definition at line 639 of file unstructured_mesh.C.
References libMesh::START_LOG(), libMesh::STOP_LOG(), and libMesh::NameBasedIO::write_nodal_data().
 {
   START_LOG("write()", "Mesh");
   NameBasedIO(*this).write_nodal_data(name, v, vn);
   STOP_LOG("write()", "Mesh");
 }
Member Data Documentation
std::map<subdomain_id_type, std::string> libMesh::MeshBase::_block_id_to_name protected inherited
This structure maintains the mapping of named blocks for file formats that support named blocks. Currently this is only implemented for ExodusII
Definition at line 1077 of file mesh_base.h.
Referenced by libMesh::MeshBase::get_id_by_name(), libMesh::MeshBase::get_subdomain_name_map(), libMesh::MeshBase::set_subdomain_name_map(), and libMesh::MeshBase::subdomain_name().
const Parallel::Communicator& libMesh::ParallelObject::_communicator protected inherited
Definition at line 105 of file parallel_object.h.
Referenced by libMesh::EquationSystems::build_solution_vector(), libMesh::ParallelObject::comm(), libMesh::EquationSystems::get_solution(), libMesh::ParallelObject::n_processors(), libMesh::ParallelObject::operator=(), and libMesh::ParallelObject::processor_id().
std::set<unsigned char> libMesh::MeshBase::_elem_dims protected inherited
We cache the dimension of the elements present in the mesh. So, if we have a mesh with 1D and 2D elements, this structure will contain 1 and 2.
Definition at line 1084 of file mesh_base.h.
Referenced by libMesh::MeshBase::cache_elem_dims(), libMesh::MeshBase::clear(), copy_nodes_and_elements(), libMesh::MeshBase::elem_dimensions(), libMesh::MeshBase::get_info(), libMesh::MeshBase::mesh_dimension(), libMesh::MeshBase::MeshBase(), and libMesh::MeshBase::set_mesh_dimension().
bool libMesh::MeshBase::_is_prepared protected inherited
Flag indicating if the mesh has been prepared for use.
Definition at line 1034 of file mesh_base.h.
Referenced by all_first_order(), all_second_order(), libMesh::MeshBase::clear(), copy_nodes_and_elements(), libMesh::MeshBase::is_prepared(), and libMesh::MeshBase::prepare_for_use().
unsigned int libMesh::MeshBase::_n_parts protected inherited
The number of partitions the mesh has. This is set by the partitioners, and may not be changed directly by the user. NOTE The number of partitions need not equal this->n_processors(), consider for example the case where you simply want to partition a mesh on one processor and view the result in GMV.
Definition at line 1029 of file mesh_base.h.
Referenced by libMesh::MeshBase::clear(), copy_nodes_and_elements(), libMesh::MeshBase::n_partitions(), libMesh::MeshBase::recalculate_n_partitions(), and libMesh::MeshBase::set_n_partitions().
unique_id_type libMesh::MeshBase::_next_unique_id protected inherited
The next available unique id for assigning ids to DOF objects
Definition at line 1057 of file mesh_base.h.
Referenced by libMesh::SerialMesh::add_elem(), libMesh::ParallelMesh::add_elem(), libMesh::SerialMesh::add_node(), libMesh::ParallelMesh::add_node(), libMesh::SerialMesh::add_point(), libMesh::SerialMesh::insert_elem(), libMesh::ParallelMesh::insert_elem(), libMesh::SerialMesh::insert_node(), libMesh::MeshBase::next_unique_id(), libMesh::SerialMesh::parallel_max_unique_id(), libMesh::ParallelMesh::parallel_max_unique_id(), libMesh::ParallelMesh::ParallelMesh(), libMesh::SerialMesh::SerialMesh(), libMesh::MeshBase::set_next_unique_id(), libMesh::SerialMesh::update_parallel_id_counts(), and libMesh::ParallelMesh::update_parallel_id_counts().
UniquePtr<Partitioner> libMesh::MeshBase::_partitioner protected inherited
A partitioner to use at each prepare_for_use().
This will be built in the constructor of each derived class, but can be replaced by the user through the partitioner() accessor.
Definition at line 1051 of file mesh_base.h.
Referenced by libMesh::MeshBase::MeshBase(), libMesh::MeshBase::partitioner(), and libMesh::SerialMesh::SerialMesh().
UniquePtr<PointLocatorBase> libMesh::MeshBase::_point_locator mutable protected inherited
A PointLocator class for this mesh. This will not actually be built unless needed. Further, since we want our point_locator() method to be const (yet do the dynamic allocating) this needs to be mutable. Since the PointLocatorBase::build() member is used, and it operates on a constant reference to the mesh, this is OK.
Definition at line 1043 of file mesh_base.h.
Referenced by libMesh::MeshBase::clear_point_locator(), libMesh::MeshBase::point_locator(), and libMesh::MeshBase::sub_point_locator().
bool libMesh::MeshBase::_skip_partitioning protected inherited
If this is true then no partitioning should be done.
Definition at line 1063 of file mesh_base.h.
Referenced by libMesh::MeshBase::skip_partitioning().
bool libMesh::MeshBase::_skip_renumber_nodes_and_elements protected inherited
If this is true then renumbering will be kept to a miniumum.
This is set when prepare_for_use() is called.
Definition at line 1070 of file mesh_base.h.
Referenced by libMesh::MeshBase::allow_renumbering(), libMesh::MeshBase::prepare_for_use(), libMesh::SerialMesh::renumber_nodes_and_elements(), and libMesh::ParallelMesh::renumber_nodes_and_elements().
unsigned char libMesh::MeshBase::_spatial_dimension protected inherited
The "spatial dimension" of the Mesh. See the documentation for Mesh::spatial_dimension() for more information.
Definition at line 1090 of file mesh_base.h.
Referenced by libMesh::MeshBase::cache_elem_dims(), libMesh::MeshBase::set_spatial_dimension(), and libMesh::MeshBase::spatial_dimension().
UniquePtr<BoundaryInfo> libMesh::MeshBase::boundary_info inherited
This class holds the boundary information. It can store nodes, edges, and faces with a corresponding id that facilitates setting boundary conditions.
Direct access to this class will be removed in future libMesh versions. Use the get_boundary_info() accessor instead.
Definition at line 1009 of file mesh_base.h.
Referenced by libMesh::MeshBase::get_boundary_info(), and libMesh::BoundaryInfo::sync().
The documentation for this class was generated from the following files:
unstructured_mesh.h
mesh_modification.C
unstructured_mesh.C