libMesh: libMesh::NonlinearImplicitSystem::ComputeJacobian Class Reference
SomeWebsiteLogo
libMesh::NonlinearImplicitSystem::ComputeJacobian Class Reference abstract
#include <nonlinear_implicit_system.h>
Public Member Functions
virtual ~ComputeJacobian ()
virtual void jacobian (const NumericVector< Number > &X, SparseMatrix< Number > &J, sys_type &S)=0
Detailed Description
Abstract base class to be used to calculate the Jacobian of a nonlinear system.
Definition at line 103 of file nonlinear_implicit_system.h.
Constructor & Destructor Documentation
~ComputeJacobian()
virtual libMesh::NonlinearImplicitSystem::ComputeJacobian::~ComputeJacobian () inline virtual
Definition at line 106 of file nonlinear_implicit_system.h.
 {}
Member Function Documentation
jacobian()
virtual void libMesh::NonlinearImplicitSystem::ComputeJacobian::jacobian (const NumericVector< Number > & X, SparseMatrix< Number > & J, sys_type & S) pure virtual
Jacobian function. This function will be called to compute the jacobian and must be implemented by the user in a derived class.
Referenced by libMesh::Problem_Interface::computeJacobian(), libMesh::Problem_Interface::computePreconditioner(), and libMesh::libmesh_petsc_snes_jacobian().
The documentation for this class was generated from the following file:
nonlinear_implicit_system.h