libMesh: libMesh::QSimpson Class Reference
SomeWebsiteLogo
libMesh::QSimpson Class Reference
Implements Simpson's rule, i.e. nodal quadrature for quadratic elements.
#include <quadrature_simpson.h>
Public Member Functions
QSimpson (unsigned int dim, Order order=THIRD)
QSimpson (const QSimpson &)=default
QSimpson (QSimpson &&)=default
QSimpson & operator= (const QSimpson &)=default
QSimpson & operator= (QSimpson &&)=default
virtual ~QSimpson ()=default
virtual QuadratureType type () const override
ElemType get_elem_type () const
unsigned int get_p_level () const
unsigned int n_points () const
unsigned int get_dim () const
const std::vector< Point > & get_points () const
std::vector< Point > & get_points ()
const std::vector< Real > & get_weights () const
std::vector< Real > & get_weights ()
Point qp (const unsigned int i) const
Real w (const unsigned int i) const
virtual void init (const ElemType type=INVALID_ELEM, unsigned int p_level=0)
virtual void init (const Elem &elem, const std::vector< Real > &vertex_distance_func, unsigned int p_level=0)
Order get_order () const
void print_info (std::ostream &os=libMesh::out) const
void scale (std::pair< Real, Real > old_range, std::pair< Real, Real > new_range)
virtual bool shapes_need_reinit ()
Static Public Member Functions
static std::unique_ptr< QBase > build (const std::string &name, const unsigned int dim, const Order order=INVALID_ORDER)
static std::unique_ptr< QBase > build (const QuadratureType qt, const unsigned int dim, const Order order=INVALID_ORDER)
static void print_info (std::ostream &out=libMesh::out)
static std::string get_info ()
static unsigned int n_objects ()
static void enable_print_counter_info ()
static void disable_print_counter_info ()
Public Attributes
bool allow_rules_with_negative_weights
Protected Types
typedef std::map< std::string, std::pair< unsigned int, unsigned int > > Counts
Protected Member Functions
virtual void init_0D (const ElemType type=INVALID_ELEM, unsigned int p_level=0)
void tensor_product_quad (const QBase &q1D)
void tensor_product_hex (const QBase &q1D)
void tensor_product_prism (const QBase &q1D, const QBase &q2D)
void increment_constructor_count (const std::string &name)
void increment_destructor_count (const std::string &name)
Protected Attributes
unsigned int _dim
Order _order
ElemType _type
unsigned int _p_level
std::vector< Point > _points
std::vector< Real > _weights
Static Protected Attributes
static Counts _counts
static Threads::atomic< unsigned int > _n_objects
static Threads::spin_mutex _mutex
static bool _enable_print_counter = true
Private Member Functions
virtual void init_1D (const ElemType _type=INVALID_ELEM, unsigned int p_level=0) override
virtual void init_2D (const ElemType _type=INVALID_ELEM, unsigned int p_level=0) override
virtual void init_3D (const ElemType _type=INVALID_ELEM, unsigned int p_level=0) override
Detailed Description
Implements Simpson's rule, i.e. nodal quadrature for quadratic elements.
This class implements Simpson quadrature. This is the same thing as Newton-Cotes quadrature with three points. Simpson's rule can integrate polynomials of degree three exactly.
Author
John W. Peterson
Date
2003
Definition at line 38 of file quadrature_simpson.h.
Member Typedef Documentation
Counts
typedef std::map<std::string, std::pair<unsigned int, unsigned int> > libMesh::ReferenceCounter::Counts protected inherited
Data structure to log the information. The log is identified by the class name.
Definition at line 117 of file reference_counter.h.
Constructor & Destructor Documentation
QSimpson() [1/3]
libMesh::QSimpson::QSimpson (unsigned int dim, Order order = THIRD) inline explicit
Constructor. Declares the order of the quadrature rule. We explicitly call the init function in 1D since the other tensor-product rules require this one.
Note
The element type, EDGE2, will not be used internally, however if we called the function with INVALID_ELEM it would try to be smart and return, thinking it had already done the work.
Definition at line 52 of file quadrature_simpson.h.
References libMesh::QBase::_dim, libMesh::EDGE2, and libMesh::QBase::init().
                                :
     QBase(dim, order)
   {
     if (_dim == 1)
       init(EDGE2);
   }
QSimpson() [2/3]
libMesh::QSimpson::QSimpson (const QSimpson &) default
Copy/move ctor, copy/move assignment operator, and destructor are all explicitly defaulted for this simple class.
QSimpson() [3/3]
libMesh::QSimpson::QSimpson (QSimpson &&) default
~QSimpson()
virtual libMesh::QSimpson::~QSimpson () virtual default
Member Function Documentation
build() [1/2]
std::unique_ptr< QBase > libMesh::QBase::build (const std::string & name, const unsigned int dim, const Order order = INVALID_ORDER) static inherited
Builds a specific quadrature rule based on the name string. This enables selection of the quadrature rule at run-time. The input parameter name must be mappable through the Utility::string_to_enum<>() function.
This function allocates memory, therefore a std::unique_ptr<QBase> is returned so that the user does not accidentally leak it.
Definition at line 40 of file quadrature_build.C.
References libMesh::QBase::_dim, libMesh::QBase::_order, and libMesh::QBase::type().
Referenced by libMesh::InfFE< Dim, T_radial, T_map >::attach_quadrature_rule().
 {
   return QBase::build (Utility::string_to_enum<QuadratureType> (type),
                        _dim,
                        _order);
 }
build() [2/2]
std::unique_ptr< QBase > libMesh::QBase::build (const QuadratureType qt, const unsigned int dim, const Order order = INVALID_ORDER) static inherited
Builds a specific quadrature rule based on the QuadratureType. This enables selection of the quadrature rule at run-time.
This function allocates memory, therefore a std::unique_ptr<QBase> is returned so that the user does not accidentally leak it.
Definition at line 51 of file quadrature_build.C.
References libMesh::QBase::_dim, libMesh::QBase::_order, libMesh::FIRST, libMesh::FORTYTHIRD, libMesh::out, libMesh::QCLOUGH, libMesh::QCONICAL, libMesh::QGAUSS, libMesh::QGAUSS_LOBATTO, libMesh::QGRID, libMesh::QGRUNDMANN_MOLLER, libMesh::QJACOBI_1_0, libMesh::QJACOBI_2_0, libMesh::QMONOMIAL, libMesh::QSIMPSON, libMesh::QTRAP, libMesh::THIRD, and libMesh::TWENTYTHIRD.
 {
   switch (_qt)
     {
     case QCLOUGH:
       {
 #ifdef DEBUG
         if (_order > TWENTYTHIRD)
           {
             libMesh::out << "WARNING: Clough quadrature implemented" << std::endl
                          << " up to TWENTYTHIRD order." << std::endl;
           }
 #endif
         return libmesh_make_unique<QClough>(_dim, _order);
       }
     case QGAUSS:
       {
 #ifdef DEBUG
         if (_order > FORTYTHIRD)
           {
             libMesh::out << "WARNING: Gauss quadrature implemented" << std::endl
                          << " up to FORTYTHIRD order." << std::endl;
           }
 #endif
         return libmesh_make_unique<QGauss>(_dim, _order);
       }
     case QJACOBI_1_0:
       {
 #ifdef DEBUG
         if (_order > FORTYTHIRD)
           {
             libMesh::out << "WARNING: Jacobi(1,0) quadrature implemented" << std::endl
                          << " up to FORTYTHIRD order." << std::endl;
           }
         if (_dim > 1)
           {
             libMesh::out << "WARNING: Jacobi(1,0) quadrature implemented" << std::endl
                          << " in 1D only." << std::endl;
           }
 #endif
         return libmesh_make_unique<QJacobi>(_dim, _order, 1, 0);
       }
     case QJACOBI_2_0:
       {
 #ifdef DEBUG
         if (_order > FORTYTHIRD)
           {
             libMesh::out << "WARNING: Jacobi(2,0) quadrature implemented" << std::endl
                          << " up to FORTYTHIRD order." << std::endl;
           }
         if (_dim > 1)
           {
             libMesh::out << "WARNING: Jacobi(2,0) quadrature implemented" << std::endl
                          << " in 1D only." << std::endl;
           }
 #endif
         return libmesh_make_unique<QJacobi>(_dim, _order, 2, 0);
       }
     case QSIMPSON:
       {
 #ifdef DEBUG
         if (_order > THIRD)
           {
             libMesh::out << "WARNING: Simpson rule provides only" << std::endl
                          << " THIRD order!" << std::endl;
           }
 #endif
         return libmesh_make_unique<QSimpson>(_dim);
       }
     case QTRAP:
       {
 #ifdef DEBUG
         if (_order > FIRST)
           {
             libMesh::out << "WARNING: Trapezoidal rule provides only" << std::endl
                          << " FIRST order!" << std::endl;
           }
 #endif
         return libmesh_make_unique<QTrap>(_dim);
       }
     case QGRID:
       return libmesh_make_unique<QGrid>(_dim, _order);
     case QGRUNDMANN_MOLLER:
       return libmesh_make_unique<QGrundmann_Moller>(_dim, _order);
     case QMONOMIAL:
       return libmesh_make_unique<QMonomial>(_dim, _order);
     case QGAUSS_LOBATTO:
       return libmesh_make_unique<QGaussLobatto>(_dim, _order);
     case QCONICAL:
       return libmesh_make_unique<QConical>(_dim, _order);
     default:
       libmesh_error_msg("ERROR: Bad qt=" << _qt);
     }
 }
disable_print_counter_info()
void libMesh::ReferenceCounter::disable_print_counter_info () static inherited
Definition at line 106 of file reference_counter.C.
References libMesh::ReferenceCounter::_enable_print_counter.
Referenced by libMesh::LibMeshInit::LibMeshInit().
 {
   _enable_print_counter = false;
   return;
 }
enable_print_counter_info()
void libMesh::ReferenceCounter::enable_print_counter_info () static inherited
Methods to enable/disable the reference counter output from print_info()
Definition at line 100 of file reference_counter.C.
References libMesh::ReferenceCounter::_enable_print_counter.
 {
   _enable_print_counter = true;
   return;
 }
get_dim()
unsigned int libMesh::QBase::get_dim () const inline inherited
Returns
The spatial dimension of the quadrature rule.
Definition at line 136 of file quadrature.h.
References libMesh::QBase::_dim.
Referenced by libMesh::InfFE< Dim, T_radial, T_map >::attach_quadrature_rule(), libMesh::QConical::conical_product_pyramid(), libMesh::QConical::conical_product_tet(), and libMesh::QConical::conical_product_tri().
 { return _dim; }
get_elem_type()
ElemType libMesh::QBase::get_elem_type () const inline inherited
Returns
The element type we're currently using.
Definition at line 117 of file quadrature.h.
References libMesh::QBase::_type.
 { return _type; }
get_info()
std::string libMesh::ReferenceCounter::get_info () static inherited
Gets a string containing the reference information.
Definition at line 47 of file reference_counter.C.
References libMesh::ReferenceCounter::_counts, and libMesh::Quality::name().
Referenced by libMesh::ReferenceCounter::print_info().
 {
 #if defined(LIBMESH_ENABLE_REFERENCE_COUNTING) && defined(DEBUG)
   std::ostringstream oss;
   oss << '\n'
       << " ---------------------------------------------------------------------------- \n"
       << "| Reference count information                                                |\n"
       << " ---------------------------------------------------------------------------- \n";
   for (const auto & pr : _counts)
     {
       const std::string name(pr.first);
       const unsigned int creations    = pr.second.first;
       const unsigned int destructions = pr.second.second;
       oss << "| " << name << " reference count information:\n"
           << "|  Creations:    " << creations    << '\n'
           << "|  Destructions: " << destructions << '\n';
     }
   oss << " ---------------------------------------------------------------------------- \n";
   return oss.str();
 #else
   return "";
 #endif
 }
get_order()
Order libMesh::QBase::get_order () const inline inherited
Returns
The order of the quadrature rule.
Definition at line 203 of file quadrature.h.
References libMesh::QBase::_order, and libMesh::QBase::_p_level.
Referenced by libMesh::InfFE< Dim, T_radial, T_map >::attach_quadrature_rule().
 { return static_cast<Order>(_order + _p_level); }
get_p_level()
unsigned int libMesh::QBase::get_p_level () const inline inherited
Returns
The p-refinement level we're currently using.
Definition at line 122 of file quadrature.h.
References libMesh::QBase::_p_level.
 { return _p_level; }
get_points() [1/2]
const std::vector<Point>& libMesh::QBase::get_points () const inline inherited
Returns
A std::vector containing the quadrature point locations in reference element space.
Definition at line 142 of file quadrature.h.
References libMesh::QBase::_points.
Referenced by libMesh::QClough::init_1D(), libMesh::QConical::init_1D(), libMesh::QMonomial::init_1D(), libMesh::QGrundmann_Moller::init_1D(), libMesh::QClough::init_2D(), libMesh::QGauss::init_2D(), libMesh::QMonomial::init_2D(), libMesh::QGauss::init_3D(), and libMesh::QMonomial::init_3D().
 { return _points; }
get_points() [2/2]
std::vector<Point>& libMesh::QBase::get_points () inline inherited
Returns
A std::vector containing the quadrature point locations in reference element space as a writable reference.
Definition at line 148 of file quadrature.h.
References libMesh::QBase::_points.
 { return _points; }
get_weights() [1/2]
const std::vector<Real>& libMesh::QBase::get_weights () const inline inherited
Returns
A constant reference to a std::vector containing the quadrature weights.
Definition at line 154 of file quadrature.h.
References libMesh::QBase::_weights.
Referenced by libMesh::QClough::init_1D(), libMesh::QConical::init_1D(), libMesh::QMonomial::init_1D(), libMesh::QGrundmann_Moller::init_1D(), libMesh::QClough::init_2D(), libMesh::QGauss::init_2D(), libMesh::QMonomial::init_2D(), libMesh::QGauss::init_3D(), and libMesh::QMonomial::init_3D().
 { return _weights; }
get_weights() [2/2]
std::vector<Real>& libMesh::QBase::get_weights () inline inherited
Returns
A writable references to a std::vector containing the quadrature weights.
Definition at line 160 of file quadrature.h.
References libMesh::QBase::_weights.
 { return _weights; }
increment_constructor_count()
void libMesh::ReferenceCounter::increment_constructor_count (const std::string & name) inline protected inherited
Increments the construction counter. Should be called in the constructor of any derived class that will be reference counted.
Definition at line 181 of file reference_counter.h.
References libMesh::ReferenceCounter::_counts, libMesh::Quality::name(), and libMesh::Threads::spin_mtx.
Referenced by libMesh::ReferenceCountedObject< RBParametrized >::ReferenceCountedObject().
 {
   Threads::spin_mutex::scoped_lock lock(Threads::spin_mtx);
   std::pair<unsigned int, unsigned int> & p = _counts[name];
   p.first++;
 }
increment_destructor_count()
void libMesh::ReferenceCounter::increment_destructor_count (const std::string & name) inline protected inherited
Increments the destruction counter. Should be called in the destructor of any derived class that will be reference counted.
Definition at line 194 of file reference_counter.h.
References libMesh::ReferenceCounter::_counts, libMesh::Quality::name(), and libMesh::Threads::spin_mtx.
Referenced by libMesh::ReferenceCountedObject< RBParametrized >::~ReferenceCountedObject().
 {
   Threads::spin_mutex::scoped_lock lock(Threads::spin_mtx);
   std::pair<unsigned int, unsigned int> & p = _counts[name];
   p.second++;
 }
init() [1/2]
void libMesh::QBase::init (const ElemType type = INVALID_ELEM, unsigned int p_level = 0) virtual inherited
Initializes the data structures for a quadrature rule for an element of type type.
Definition at line 28 of file quadrature.C.
References libMesh::QBase::_dim, libMesh::QBase::_p_level, libMesh::QBase::_type, libMesh::QBase::init_0D(), libMesh::QBase::init_1D(), libMesh::QBase::init_2D(), and libMesh::QBase::init_3D().
Referenced by libMesh::QBase::init(), libMesh::QClough::init_1D(), libMesh::QMonomial::init_1D(), libMesh::QClough::init_2D(), libMesh::QGaussLobatto::init_2D(), libMesh::QGrid::init_2D(), libMesh::QTrap::init_2D(), init_2D(), libMesh::QGauss::init_2D(), libMesh::QMonomial::init_2D(), libMesh::QGaussLobatto::init_3D(), libMesh::QTrap::init_3D(), libMesh::QGrid::init_3D(), libMesh::QGauss::init_3D(), init_3D(), libMesh::QMonomial::init_3D(), libMesh::QGauss::QGauss(), libMesh::QGaussLobatto::QGaussLobatto(), libMesh::QJacobi::QJacobi(), QSimpson(), and libMesh::QTrap::QTrap().
 {
   // check to see if we have already
   // done the work for this quadrature rule
   if (t == _type && p == _p_level)
     return;
   else
     {
       _type = t;
       _p_level = p;
     }
   switch(_dim)
     {
     case 0:
       this->init_0D(_type,_p_level);
       return;
     case 1:
       this->init_1D(_type,_p_level);
       return;
     case 2:
       this->init_2D(_type,_p_level);
       return;
     case 3:
       this->init_3D(_type,_p_level);
       return;
     default:
       libmesh_error_msg("Invalid dimension _dim = " << _dim);
     }
 }
init() [2/2]
void libMesh::QBase::init (const Elem & elem, const std::vector< Real > & vertex_distance_func, unsigned int p_level = 0) virtual inherited
Initializes the data structures for an element potentially "cut" by a signed distance function. The array vertex_distance_func contains vertex values of the signed distance function. If the signed distance function changes sign on the vertices, then the element is considered to be cut.) This interface can be extended by derived classes in order to subdivide the element and construct a composite quadrature rule.
Definition at line 72 of file quadrature.C.
References libMesh::QBase::init(), and libMesh::Elem::type().
 {
   // dispatch generic implementation
   this->init(elem.type(), p_level);
 }
init_0D()
void libMesh::QBase::init_0D (const ElemType type = INVALID_ELEM, unsigned int p_level = 0) protected virtual inherited
Initializes the 0D quadrature rule by filling the points and weights vectors with the appropriate values. Generally this is just one point with weight 1.
Definition at line 82 of file quadrature.C.
References libMesh::QBase::_points, and libMesh::QBase::_weights.
Referenced by libMesh::QBase::init().
 {
   _points.resize(1);
   _weights.resize(1);
   _points[0] = Point(0.);
   _weights[0] = 1.0;
 }
init_1D()
void libMesh::QSimpson::init_1D (const ElemType type = INVALID_ELEM, unsigned int p_level = 0) override private virtual
Initializes the 1D quadrature rule by filling the points and weights vectors with the appropriate values. The order of the rule will be defined by the implementing class. It is assumed that derived quadrature rules will at least define the init_1D function, therefore it is pure virtual.
Implements libMesh::QBase.
Definition at line 28 of file quadrature_simpson_1D.C.
References libMesh::QBase::_points, libMesh::QBase::_weights, and libMesh::Real.
 {
   //----------------------------------------------------------------------
   // 1D quadrature rules
   _points.resize(3);
   _weights.resize(3);
   _points[0](0) = -1.;
   _points[1](0) =  0.;
   _points[2](0) =  1.;
   _weights[0] = Real(1)/3;
   _weights[1] = Real(4)/3;
   _weights[2] = Real(1)/3;
   return;
 }
init_2D()
void libMesh::QSimpson::init_2D (const ElemType = INVALID_ELEM, unsigned int = 0) override private virtual
Initializes the 2D quadrature rule by filling the points and weights vectors with the appropriate values. The order of the rule will be defined by the implementing class. Should not be pure virtual since a derived quadrature rule may only be defined in 1D. If not redefined, gives an error (when DEBUG is defined) when called.
Reimplemented from libMesh::QBase.
Definition at line 28 of file quadrature_simpson_2D.C.
References libMesh::QBase::_points, libMesh::QBase::_weights, libMesh::EDGE2, libMesh::QBase::init(), libMesh::QUAD4, libMesh::QUAD8, libMesh::QUAD9, libMesh::QUADSHELL4, libMesh::QUADSHELL8, libMesh::Real, libMesh::QBase::tensor_product_quad(), libMesh::TRI3, libMesh::TRI6, and libMesh::TRISHELL3.
 {
 #if LIBMESH_DIM > 1
   //-----------------------------------------------------------------------
   // 2D quadrature rules
   switch (type_in)
     {
       //---------------------------------------------
       // Quadrilateral quadrature rules
     case QUAD4:
     case QUADSHELL4:
     case QUAD8:
     case QUADSHELL8:
     case QUAD9:
       {
         // We compute the 2D quadrature rule as a tensor
         // product of the 1D quadrature rule.
         QSimpson q1D(1);
         q1D.init(EDGE2);
         tensor_product_quad( q1D );
         return;
       }
       //---------------------------------------------
       // Triangle quadrature rules
     case TRI3:
     case TRISHELL3:
     case TRI6:
       {
         // I'm not sure if you would call this Simpson's
         // rule for triangles.  What it *Really* is is
         // four trapezoidal rules combined to give a six
         // point rule.  The points lie at the nodal locations
         // of the TRI6, so you can get diagonal element
         // stiffness matrix entries for quadratic elements.
         // This rule should be able to integrate a little
         // better than linears exactly.
         _points.resize(6);
         _weights.resize(6);
         _points[0](0) = 0.;
         _points[0](1) = 0.;
         _points[1](0) = 1.;
         _points[1](1) = 0.;
         _points[2](0) = 0.;
         _points[2](1) = 1.;
         _points[3](0) = 0.5;
         _points[3](1) = 0.;
         _points[4](0) = 0.;
         _points[4](1) = 0.5;
         _points[5](0) = 0.5;
         _points[5](1) = 0.5;
         _weights[0] = Real(1)/24;
         _weights[1] = Real(1)/24;
         _weights[2] = Real(1)/24;
         _weights[3] = 0.125;                            // 1./8.
         _weights[4] = 0.125;                            // 1./8.
         _weights[5] = 0.125;                            // 1./8.
         return;
       }
       //---------------------------------------------
       // Unsupported type
     default:
       libmesh_error_msg("Element type not supported!:" << type_in);
     }
 #endif
 }
init_3D()
void libMesh::QSimpson::init_3D (const ElemType = INVALID_ELEM, unsigned int = 0) override private virtual
Initializes the 3D quadrature rule by filling the points and weights vectors with the appropriate values. The order of the rule will be defined by the implementing class. Should not be pure virtual since a derived quadrature rule may only be defined in 1D. If not redefined, gives an error (when DEBUG is defined) when called.
Reimplemented from libMesh::QBase.
Definition at line 30 of file quadrature_simpson_3D.C.
References libMesh::QBase::_points, libMesh::QBase::_weights, libMesh::EDGE2, libMesh::HEX20, libMesh::HEX27, libMesh::HEX8, libMesh::QBase::init(), libMesh::PRISM15, libMesh::PRISM18, libMesh::PRISM6, libMesh::Real, libMesh::QBase::tensor_product_hex(), libMesh::QBase::tensor_product_prism(), libMesh::TET10, libMesh::TET4, and libMesh::TRI3.
 {
 #if LIBMESH_DIM == 3
   //-----------------------------------------------------------------------
   // 3D quadrature rules
   switch (type_in)
     {
       //---------------------------------------------
       // Hex quadrature rules
     case HEX8:
     case HEX20:
     case HEX27:
       {
         // We compute the 3D quadrature rule as a tensor
         // product of the 1D quadrature rule.
         QSimpson q1D(1);
         q1D.init(EDGE2);
         tensor_product_hex( q1D );
         return;
       }
       //---------------------------------------------
       // Tetrahedral quadrature rules
     case TET4:
     case TET10:
       {
         // This rule is created by combining 8 subtets
         // which use the trapezoidal rule.  The weights
         // may seem a bit odd, but they are correct,
         // and should add up to 1/6, the volume of the
         // reference tet.  The points of this rule are
         // at the nodal points of the TET10, allowing
         // you to generate diagonal element stiffness
         // matrices when using quadratic elements.
         // It should be able to integrate something
         // better than linears, but I'm not sure how
         // high.
         _points.resize(10);
         _weights.resize(10);
         _points[0](0) = 0.;   _points[5](0) = .5;
         _points[0](1) = 0.;   _points[5](1) = .5;
         _points[0](2) = 0.;   _points[5](2) = 0.;
         _points[1](0) = 1.;   _points[6](0) = 0.;
         _points[1](1) = 0.;   _points[6](1) = .5;
         _points[1](2) = 0.;   _points[6](2) = 0.;
         _points[2](0) = 0.;   _points[7](0) = 0.;
         _points[2](1) = 1.;   _points[7](1) = 0.;
         _points[2](2) = 0.;   _points[7](2) = .5;
         _points[3](0) = 0.;   _points[8](0) = .5;
         _points[3](1) = 0.;   _points[8](1) = 0.;
         _points[3](2) = 1.;   _points[8](2) = .5;
         _points[4](0) = .5;   _points[9](0) = 0.;
         _points[4](1) = 0.;   _points[9](1) = .5;
         _points[4](2) = 0.;   _points[9](2) = .5;
         _weights[0] = Real(1)/192;
         _weights[1] = _weights[0];
         _weights[2] = _weights[0];
         _weights[3] = _weights[0];
         _weights[4] = Real(14)/576;
         _weights[5] = _weights[4];
         _weights[6] = _weights[4];
         _weights[7] = _weights[4];
         _weights[8] = _weights[4];
         _weights[9] = _weights[4];
         return;
       }
       //---------------------------------------------
       // Prism quadrature rules
     case PRISM6:
     case PRISM15:
     case PRISM18:
       {
         // We compute the 3D quadrature rule as a tensor
         // product of the 1D quadrature rule and a 2D
         // triangle quadrature rule
         QSimpson q1D(1);
         QSimpson q2D(2);
         // Initialize
         q1D.init(EDGE2);
         q2D.init(TRI3);
         tensor_product_prism(q1D, q2D);
         return;
       }
       //---------------------------------------------
       // Unsupported type
     default:
       libmesh_error_msg("ERROR: Unsupported type: " << type_in);
     }
 #endif
 }
n_objects()
static unsigned int libMesh::ReferenceCounter::n_objects () inline static inherited
Prints the number of outstanding (created, but not yet destroyed) objects.
Definition at line 83 of file reference_counter.h.
References libMesh::ReferenceCounter::_n_objects.
   { return _n_objects; }
n_points()
unsigned int libMesh::QBase::n_points () const inline inherited
Returns
The number of points associated with the quadrature rule.
Definition at line 127 of file quadrature.h.
References libMesh::QBase::_points.
Referenced by libMesh::ExactSolution::_compute_error(), libMesh::System::calculate_norm(), libMesh::FirstOrderUnsteadySolver::compute_second_order_eqns(), libMesh::QConical::conical_product_pyramid(), libMesh::QConical::conical_product_tet(), libMesh::QConical::conical_product_tri(), libMesh::QBase::print_info(), libMesh::QBase::tensor_product_hex(), libMesh::QBase::tensor_product_prism(), and libMesh::QBase::tensor_product_quad().
   {
     libmesh_assert (!_points.empty());
     return cast_int<unsigned int>(_points.size());
   }
operator=() [1/2]
QSimpson& libMesh::QSimpson::operator= (const QSimpson &) default
operator=() [2/2]
QSimpson& libMesh::QSimpson::operator= (QSimpson &&) default
print_info() [1/2]
void libMesh::ReferenceCounter::print_info (std::ostream & out = libMesh::out) static inherited
Prints the reference information, by default to libMesh::out.
Definition at line 87 of file reference_counter.C.
References libMesh::ReferenceCounter::_enable_print_counter, and libMesh::ReferenceCounter::get_info().
 {
   if (_enable_print_counter)
     out_stream << ReferenceCounter::get_info();
 }
print_info() [2/2]
void libMesh::QBase::print_info (std::ostream & os = libMesh::out) const inline inherited
Prints information relevant to the quadrature rule, by default to libMesh::out.
Definition at line 378 of file quadrature.h.
References libMesh::QBase::_points, libMesh::QBase::_weights, libMesh::QBase::n_points(), and libMesh::Real.
Referenced by libMesh::operator<<().
 {
   libmesh_assert(!_points.empty());
   libmesh_assert(!_weights.empty());
   Real summed_weights=0;
   os << "N_Q_Points=" << this->n_points() << std::endl << std::endl;
   for (unsigned int qpoint=0; qpoint<this->n_points(); qpoint++)
     {
       os << " Point " << qpoint << ":\n"
          << "  "
          << _points[qpoint]
          << "\n Weight:\n "
          << "  w=" << _weights[qpoint] << "\n" << std::endl;
       summed_weights += _weights[qpoint];
     }
   os << "Summed Weights: " << summed_weights << std::endl;
 }
qp()
Point libMesh::QBase::qp (const unsigned int i) const inline inherited
Returns
The quadrature point in reference element space.
Definition at line 165 of file quadrature.h.
References libMesh::QBase::_points.
Referenced by libMesh::QConical::conical_product_pyramid(), libMesh::QConical::conical_product_tet(), libMesh::QConical::conical_product_tri(), libMesh::QBase::tensor_product_hex(), libMesh::QBase::tensor_product_prism(), and libMesh::QBase::tensor_product_quad().
   {
     libmesh_assert_less (i, _points.size());
     return _points[i];
   }
scale()
void libMesh::QBase::scale (std::pair< Real, Real > old_range, std::pair< Real, Real > new_range) inherited
Maps the points of a 1D quadrature rule defined by "old_range" to another 1D interval defined by "new_range" and scales the weights accordingly.
Definition at line 93 of file quadrature.C.
References libMesh::QBase::_dim, libMesh::QBase::_points, libMesh::QBase::_weights, and libMesh::Real.
Referenced by libMesh::QConical::conical_product_tet(), and libMesh::QConical::conical_product_tri().
 {
   // Make sure we are in 1D
   libmesh_assert_equal_to (_dim, 1);
   Real
     h_new = new_range.second - new_range.first,
     h_old = old_range.second - old_range.first;
   // Make sure that we have sane ranges
   libmesh_assert_greater (h_new, 0.);
   libmesh_assert_greater (h_old, 0.);
   // Make sure there are some points
   libmesh_assert_greater (_points.size(), 0);
   // Compute the scale factor
   Real scfact = h_new/h_old;
   // We're mapping from old_range -> new_range
   for (std::size_t i=0; i<_points.size(); i++)
     {
       _points[i](0) = new_range.first +
         (_points[i](0) - old_range.first) * scfact;
       // Scale the weights
       _weights[i] *= scfact;
     }
 }
shapes_need_reinit()
virtual bool libMesh::QBase::shapes_need_reinit () inline virtual inherited
Returns
true if the shape functions need to be recalculated, false otherwise.
This may be required if the number of quadrature points or their position changes.
Definition at line 231 of file quadrature.h.
 { return false; }
tensor_product_hex()
void libMesh::QBase::tensor_product_hex (const QBase & q1D) protected inherited
Computes the tensor product quadrature rule [q1D x q1D x q1D] from the 1D rule q1D. Used in the init_3D routines for hexahedral element types.
Definition at line 154 of file quadrature.C.
References libMesh::QBase::_points, libMesh::QBase::_weights, libMesh::QBase::n_points(), libMesh::QBase::qp(), and libMesh::QBase::w().
Referenced by libMesh::QGaussLobatto::init_3D(), libMesh::QTrap::init_3D(), libMesh::QGrid::init_3D(), init_3D(), and libMesh::QGauss::init_3D().
 {
   const unsigned int np = q1D.n_points();
   _points.resize(np * np * np);
   _weights.resize(np * np * np);
   unsigned int q=0;
   for (unsigned int k=0; k<np; k++)
     for (unsigned int j=0; j<np; j++)
       for (unsigned int i=0; i<np; i++)
         {
           _points[q](0) = q1D.qp(i)(0);
           _points[q](1) = q1D.qp(j)(0);
           _points[q](2) = q1D.qp(k)(0);
           _weights[q] = q1D.w(i) * q1D.w(j) * q1D.w(k);
           q++;
         }
 }
tensor_product_prism()
void libMesh::QBase::tensor_product_prism (const QBase & q1D, const QBase & q2D) protected inherited
Computes the tensor product of a 1D quadrature rule and a 2D quadrature rule. Used in the init_3D routines for prismatic element types.
Definition at line 181 of file quadrature.C.
References libMesh::QBase::_points, libMesh::QBase::_weights, libMesh::QBase::n_points(), libMesh::QBase::qp(), and libMesh::QBase::w().
Referenced by libMesh::QGrid::init_3D(), libMesh::QTrap::init_3D(), init_3D(), and libMesh::QGauss::init_3D().
 {
   const unsigned int n_points1D = q1D.n_points();
   const unsigned int n_points2D = q2D.n_points();
   _points.resize  (n_points1D * n_points2D);
   _weights.resize (n_points1D * n_points2D);
   unsigned int q=0;
   for (unsigned int j=0; j<n_points1D; j++)
     for (unsigned int i=0; i<n_points2D; i++)
       {
         _points[q](0) = q2D.qp(i)(0);
         _points[q](1) = q2D.qp(i)(1);
         _points[q](2) = q1D.qp(j)(0);
         _weights[q] = q2D.w(i) * q1D.w(j);
         q++;
       }
 }
tensor_product_quad()
void libMesh::QBase::tensor_product_quad (const QBase & q1D) protected inherited
Constructs a 2D rule from the tensor product of q1D with itself. Used in the init_2D() routines for quadrilateral element types.
Definition at line 127 of file quadrature.C.
References libMesh::QBase::_points, libMesh::QBase::_weights, libMesh::QBase::n_points(), libMesh::QBase::qp(), and libMesh::QBase::w().
Referenced by libMesh::QGaussLobatto::init_2D(), libMesh::QTrap::init_2D(), libMesh::QGrid::init_2D(), init_2D(), and libMesh::QGauss::init_2D().
 {
   const unsigned int np = q1D.n_points();
   _points.resize(np * np);
   _weights.resize(np * np);
   unsigned int q=0;
   for (unsigned int j=0; j<np; j++)
     for (unsigned int i=0; i<np; i++)
       {
         _points[q](0) = q1D.qp(i)(0);
         _points[q](1) = q1D.qp(j)(0);
         _weights[q] = q1D.w(i)*q1D.w(j);
         q++;
       }
 }
type()
QuadratureType libMesh::QSimpson::type () const override virtual
Returns
QSIMPSON.
Implements libMesh::QBase.
Definition at line 26 of file quadrature_simpson.C.
References libMesh::QSIMPSON.
 {
   return QSIMPSON;
 }
w()
Real libMesh::QBase::w (const unsigned int i) const inline inherited
Returns
The quadrature weight.
Definition at line 174 of file quadrature.h.
References libMesh::QBase::_weights.
Referenced by libMesh::QConical::conical_product_pyramid(), libMesh::QConical::conical_product_tet(), libMesh::QConical::conical_product_tri(), libMesh::QBase::tensor_product_hex(), libMesh::QBase::tensor_product_prism(), and libMesh::QBase::tensor_product_quad().
   {
     libmesh_assert_less (i, _weights.size());
     return _weights[i];
   }
Member Data Documentation
_counts
ReferenceCounter::Counts libMesh::ReferenceCounter::_counts static protected inherited
Actually holds the data.
Definition at line 122 of file reference_counter.h.
Referenced by libMesh::ReferenceCounter::get_info(), libMesh::ReferenceCounter::increment_constructor_count(), and libMesh::ReferenceCounter::increment_destructor_count().
_dim
unsigned int libMesh::QBase::_dim protected inherited
The spatial dimension of the quadrature rule.
Definition at line 325 of file quadrature.h.
Referenced by libMesh::QBase::build(), libMesh::QBase::get_dim(), libMesh::QBase::init(), libMesh::QGaussLobatto::QGaussLobatto(), libMesh::QJacobi::QJacobi(), QSimpson(), libMesh::QTrap::QTrap(), and libMesh::QBase::scale().
_enable_print_counter
bool libMesh::ReferenceCounter::_enable_print_counter = true static protected inherited
Flag to control whether reference count information is printed when print_info is called.
Definition at line 141 of file reference_counter.h.
Referenced by libMesh::ReferenceCounter::disable_print_counter_info(), libMesh::ReferenceCounter::enable_print_counter_info(), and libMesh::ReferenceCounter::print_info().
_mutex
Threads::spin_mutex libMesh::ReferenceCounter::_mutex static protected inherited
Mutual exclusion object to enable thread-safe reference counting.
Definition at line 135 of file reference_counter.h.
_n_objects
Threads::atomic< unsigned int > libMesh::ReferenceCounter::_n_objects static protected inherited
The number of objects. Print the reference count information when the number returns to 0.
Definition at line 130 of file reference_counter.h.
Referenced by libMesh::ReferenceCounter::n_objects(), libMesh::ReferenceCounter::ReferenceCounter(), and libMesh::ReferenceCounter::~ReferenceCounter().
_order
Order libMesh::QBase::_order protected inherited
The polynomial order which the quadrature rule is capable of integrating exactly.
Definition at line 331 of file quadrature.h.
Referenced by libMesh::QBase::build(), libMesh::QConical::conical_product_pyramid(), libMesh::QConical::conical_product_tet(), libMesh::QConical::conical_product_tri(), libMesh::QBase::get_order(), libMesh::QClough::init_1D(), libMesh::QGaussLobatto::init_1D(), libMesh::QConical::init_1D(), libMesh::QGrid::init_1D(), libMesh::QGauss::init_1D(), libMesh::QJacobi::init_1D(), libMesh::QMonomial::init_1D(), libMesh::QGrundmann_Moller::init_1D(), libMesh::QClough::init_2D(), libMesh::QGaussLobatto::init_2D(), libMesh::QGrid::init_2D(), libMesh::QGauss::init_2D(), libMesh::QMonomial::init_2D(), libMesh::QGrundmann_Moller::init_2D(), libMesh::QGaussLobatto::init_3D(), libMesh::QGrid::init_3D(), libMesh::QGauss::init_3D(), libMesh::QMonomial::init_3D(), and libMesh::QGrundmann_Moller::init_3D().
_p_level
unsigned int libMesh::QBase::_p_level protected inherited
The p-level of the element for which the current values have been computed.
Definition at line 343 of file quadrature.h.
Referenced by libMesh::QBase::get_order(), libMesh::QBase::get_p_level(), and libMesh::QBase::init().
_points
std::vector<Point> libMesh::QBase::_points protected inherited
The locations of the quadrature points in reference element space.
Definition at line 349 of file quadrature.h.
Referenced by libMesh::QConical::conical_product_pyramid(), libMesh::QConical::conical_product_tet(), libMesh::QConical::conical_product_tri(), libMesh::QGauss::dunavant_rule(), libMesh::QGauss::dunavant_rule2(), libMesh::QBase::get_points(), libMesh::QGrundmann_Moller::gm_rule(), libMesh::QBase::init_0D(), libMesh::QClough::init_1D(), libMesh::QGaussLobatto::init_1D(), libMesh::QConical::init_1D(), libMesh::QTrap::init_1D(), libMesh::QGrid::init_1D(), init_1D(), libMesh::QGauss::init_1D(), libMesh::QJacobi::init_1D(), libMesh::QMonomial::init_1D(), libMesh::QGrundmann_Moller::init_1D(), libMesh::QClough::init_2D(), libMesh::QTrap::init_2D(), libMesh::QGrid::init_2D(), libMesh::QGauss::init_2D(), init_2D(), libMesh::QMonomial::init_2D(), libMesh::QGrid::init_3D(), libMesh::QTrap::init_3D(), libMesh::QGauss::init_3D(), init_3D(), libMesh::QMonomial::init_3D(), libMesh::QGrundmann_Moller::init_3D(), libMesh::QGauss::keast_rule(), libMesh::QMonomial::kim_rule(), libMesh::QBase::n_points(), libMesh::QBase::print_info(), libMesh::QBase::qp(), libMesh::QBase::scale(), libMesh::QMonomial::stroud_rule(), libMesh::QBase::tensor_product_hex(), libMesh::QBase::tensor_product_prism(), libMesh::QBase::tensor_product_quad(), and libMesh::QMonomial::wissmann_rule().
_type
ElemType libMesh::QBase::_type protected inherited
The type of element for which the current values have been computed.
Definition at line 337 of file quadrature.h.
Referenced by libMesh::QBase::get_elem_type(), and libMesh::QBase::init().
_weights
std::vector<Real> libMesh::QBase::_weights protected inherited
The quadrature weights. The order of the weights matches the ordering of the _points vector.
Definition at line 355 of file quadrature.h.
Referenced by libMesh::QConical::conical_product_pyramid(), libMesh::QConical::conical_product_tet(), libMesh::QConical::conical_product_tri(), libMesh::QGauss::dunavant_rule(), libMesh::QGauss::dunavant_rule2(), libMesh::QBase::get_weights(), libMesh::QGrundmann_Moller::gm_rule(), libMesh::QBase::init_0D(), libMesh::QClough::init_1D(), libMesh::QGaussLobatto::init_1D(), libMesh::QConical::init_1D(), libMesh::QTrap::init_1D(), libMesh::QGrid::init_1D(), init_1D(), libMesh::QGauss::init_1D(), libMesh::QJacobi::init_1D(), libMesh::QMonomial::init_1D(), libMesh::QGrundmann_Moller::init_1D(), libMesh::QClough::init_2D(), libMesh::QTrap::init_2D(), libMesh::QGrid::init_2D(), init_2D(), libMesh::QGauss::init_2D(), libMesh::QMonomial::init_2D(), libMesh::QGrid::init_3D(), libMesh::QTrap::init_3D(), init_3D(), libMesh::QGauss::init_3D(), libMesh::QMonomial::init_3D(), libMesh::QGrundmann_Moller::init_3D(), libMesh::QGauss::keast_rule(), libMesh::QMonomial::kim_rule(), libMesh::QBase::print_info(), libMesh::QBase::scale(), libMesh::QMonomial::stroud_rule(), libMesh::QBase::tensor_product_hex(), libMesh::QBase::tensor_product_prism(), libMesh::QBase::tensor_product_quad(), libMesh::QBase::w(), and libMesh::QMonomial::wissmann_rule().
allow_rules_with_negative_weights
bool libMesh::QBase::allow_rules_with_negative_weights inherited
Flag (default true) controlling the use of quadrature rules with negative weights. Set this to false to require rules with all positive weights.
Rules with negative weights can be unsuitable for some problems. For example, it is possible for a rule with negative weights to obtain a negative result when integrating a positive function.
A particular example: if rules with negative weights are not allowed, a request for TET,THIRD (5 points) will return the TET,FIFTH (14 points) rule instead, nearly tripling the computational effort required!
Definition at line 246 of file quadrature.h.
Referenced by libMesh::QGrundmann_Moller::init_2D(), libMesh::QGauss::init_3D(), libMesh::QMonomial::init_3D(), and libMesh::QGrundmann_Moller::init_3D().
The documentation for this class was generated from the following files:
quadrature_simpson.h
quadrature_simpson.C
quadrature_simpson_1D.C
quadrature_simpson_2D.C
quadrature_simpson_3D.C