libMesh: libMesh::Parallel::StandardType< std::complex< T > > Class Template Reference
SomeWebsiteLogo
libMesh::Parallel::StandardType< std::complex< T > > Class Template Reference
#include <standard_type.h>
Public Member Functions
StandardType (const std::complex< T > *=nullptr)
~StandardType ()
operator const data_type & () const
operator data_type & ()
void commit ()
void free ()
Protected Attributes
data_type _datatype
Detailed Description
template<typename T>
class libMesh::Parallel::StandardType< std::complex< T > >
Definition at line 328 of file standard_type.h.
Constructor & Destructor Documentation
StandardType()
template<typename T > libMesh::Parallel::StandardType< std::complex< T > >::StandardType (const std::complex< T > * = nullptr) inline explicit
Definition at line 332 of file standard_type.h.
                                                   :
     DataType(StandardType<T>(nullptr), 2) {}
~StandardType()
template<typename T > libMesh::Parallel::StandardType< std::complex< T > >::~StandardType () inline
Definition at line 335 of file standard_type.h.
References libMesh::Parallel::DataType::free().
 { this->free(); }
Member Function Documentation
commit()
void libMesh::Parallel::DataType::commit () inline inherited
Definition at line 103 of file data_type.h.
References libMesh::Parallel::DataType::_datatype.
Referenced by libMesh::Parallel::DataType::DataType(), libMesh::Parallel::StandardType< std::pair< T1, T2 > >::StandardType(), and libMesh::Parallel::StandardType< std::tuple< Types... > >::StandardType().
   {
     libmesh_call_mpi
       (MPI_Type_commit (&_datatype));
   }
free()
void libMesh::Parallel::DataType::free () inline inherited
Definition at line 109 of file data_type.h.
References libMesh::Parallel::DataType::_datatype.
Referenced by libMesh::Parallel::StandardType< Hilbert::HilbertIndices >::~StandardType(), libMesh::Parallel::StandardType< TypeVector< T > >::~StandardType(), libMesh::Parallel::StandardType< VectorValue< T > >::~StandardType(), libMesh::Parallel::StandardType< std::pair< T1, T2 > >::~StandardType(), libMesh::Parallel::StandardType< Point >::~StandardType(), libMesh::Parallel::StandardType< std::tuple< Types... > >::~StandardType(), ~StandardType(), libMesh::Parallel::StandardType< TypeTensor< T > >::~StandardType(), and libMesh::Parallel::StandardType< TensorValue< T > >::~StandardType().
   {
     libmesh_call_mpi
       (MPI_Type_free (&_datatype));
   }
operator const data_type &()
libMesh::Parallel::DataType::operator const data_type & () const inline inherited
Definition at line 91 of file data_type.h.
References libMesh::Parallel::DataType::_datatype.
   { return _datatype; }
operator data_type &()
libMesh::Parallel::DataType::operator data_type & () inline inherited
Definition at line 94 of file data_type.h.
References libMesh::Parallel::DataType::_datatype.
   { return _datatype; }
Member Data Documentation
_datatype
data_type libMesh::Parallel::DataType::_datatype protected inherited
Definition at line 117 of file data_type.h.
Referenced by libMesh::Parallel::DataType::commit(), libMesh::Parallel::DataType::DataType(), libMesh::Parallel::DataType::free(), libMesh::Parallel::DataType::operator const data_type &(), libMesh::Parallel::DataType::operator data_type &(), libMesh::Parallel::DataType::operator=(), libMesh::Parallel::StandardType< TypeVector< T > >::StandardType(), libMesh::Parallel::StandardType< Hilbert::HilbertIndices >::StandardType(), libMesh::Parallel::StandardType< VectorValue< T > >::StandardType(), libMesh::Parallel::StandardType< std::pair< T1, T2 > >::StandardType(), libMesh::Parallel::StandardType< Point >::StandardType(), and libMesh::Parallel::StandardType< std::tuple< Types... > >::StandardType().
The documentation for this class was generated from the following file:
standard_type.h