libMesh: libMesh::OFFIO Class Reference
SomeWebsiteLogo
libMesh::OFFIO Class Reference
#include <off_io.h>
Public Member Functions
OFFIO (MeshBase &)
virtual void read (const std::string &name)
Protected Member Functions
MeshBase & mesh ()
void skip_comment_lines (std::istream &in, const char comment_start)
Protected Attributes
std::vector< bool > elems_of_dimension
Private Member Functions
virtual void read_stream (std::istream &in)
Detailed Description
This class is repsonsible for reading an unstructured, triangulated surface in the standard OFF OOGL format.
Definition at line 43 of file off_io.h.
Constructor & Destructor Documentation
libMesh::OFFIO::OFFIO (MeshBase & mesh_in) inline explicit
Constructor. Takes a non-const Mesh reference which it will fill up with elements.
Definition at line 72 of file off_io.h.
                                :
   MeshInput<MeshBase> (mesh_in)
 {}
Member Function Documentation
MeshBase & libMesh::MeshInput< MeshBase >::mesh () protected inherited
Returns the object as a writeable reference.
Referenced by libMesh::GMVIO::_read_one_cell(), libMesh::VTKIO::cells_to_vtk(), libMesh::TetGenIO::element_in(), libMesh::UNVIO::elements_in(), libMesh::UNVIO::elements_out(), libMesh::UNVIO::groups_in(), libMesh::TetGenIO::node_in(), libMesh::UNVIO::nodes_in(), libMesh::UNVIO::nodes_out(), libMesh::VTKIO::nodes_to_vtk(), libMesh::ExodusII_IO::read(), libMesh::GMVIO::read(), libMesh::CheckpointIO::read(), libMesh::XdrIO::read(), libMesh::VTKIO::read(), libMesh::LegacyXdrIO::read_ascii(), libMesh::CheckpointIO::read_bcs(), libMesh::CheckpointIO::read_connectivity(), libMesh::UCDIO::read_implementation(), libMesh::UNVIO::read_implementation(), libMesh::GmshIO::read_mesh(), libMesh::CheckpointIO::read_nodes(), libMesh::CheckpointIO::read_nodesets(), libMesh::XdrIO::read_serialized_bcs(), libMesh::XdrIO::read_serialized_connectivity(), libMesh::XdrIO::read_serialized_nodes(), libMesh::XdrIO::read_serialized_nodesets(), libMesh::XdrIO::read_serialized_subdomain_names(), read_stream(), libMesh::MatlabIO::read_stream(), libMesh::CheckpointIO::read_subdomain_names(), libMesh::TetGenIO::write(), libMesh::ExodusII_IO::write(), libMesh::CheckpointIO::write(), libMesh::XdrIO::write(), libMesh::GMVIO::write_ascii_new_impl(), libMesh::GMVIO::write_ascii_old_impl(), libMesh::CheckpointIO::write_bcs(), libMesh::GMVIO::write_binary(), libMesh::CheckpointIO::write_connectivity(), libMesh::GMVIO::write_discontinuous_gmv(), libMesh::ExodusII_IO::write_element_data(), libMesh::UCDIO::write_implementation(), libMesh::GmshIO::write_mesh(), libMesh::UCDIO::write_nodal_data(), libMesh::VTKIO::write_nodal_data(), libMesh::ExodusII_IO::write_nodal_data(), libMesh::ExodusII_IO::write_nodal_data_common(), libMesh::ExodusII_IO::write_nodal_data_discontinuous(), libMesh::CheckpointIO::write_nodes(), libMesh::CheckpointIO::write_nodesets(), libMesh::XdrIO::write_parallel(), libMesh::GmshIO::write_post(), libMesh::XdrIO::write_serialized_bcs(), libMesh::XdrIO::write_serialized_connectivity(), libMesh::XdrIO::write_serialized_nodes(), libMesh::XdrIO::write_serialized_nodesets(), libMesh::XdrIO::write_serialized_subdomain_names(), and libMesh::CheckpointIO::write_subdomain_names().
void libMesh::OFFIO::read (const std::string & name) virtual
Reads in an OFF OOGL data file based on the string you pass it.
Implements libMesh::MeshInput< MeshBase >.
Definition at line 35 of file off_io.C.
References read_stream().
Referenced by libMesh::UnstructuredMesh::read().
 {
   std::ifstream in (name.c_str());
   read_stream(in);
 }
void libMesh::OFFIO::read_stream (std::istream & in) private virtual
Implementation of the read() function. This function is called by the public interface function and implements reading the file.
Definition at line 44 of file off_io.C.
References libMesh::MeshBase::add_elem(), libMesh::MeshBase::add_point(), libMesh::MeshBase::clear(), libMesh::libmesh_assert(), libMesh::MeshInput< MeshBase >::mesh(), libMesh::MeshInput< MT >::mesh(), libMesh::MeshBase::node_ptr(), libMesh::processor_id(), libMesh::Real, libMesh::DofObject::set_id(), libMesh::MeshBase::set_mesh_dimension(), libMesh::Elem::set_node(), and libMesh::x.
Referenced by read().
 {
   // This is a serial-only process for now;
   // the Mesh should be read on processor 0 and
   // broadcast later
   libmesh_assert_equal_to (this->mesh().processor_id(), 0);
   // Get a reference to the mesh
   MeshBase& the_mesh = MeshInput<MeshBase>::mesh();
   // Clear any existing mesh data
   the_mesh.clear();
   // Check the input buffer
   libmesh_assert (in.good());
   unsigned int nn, ne, nf;
   std::string label;
   // Read the first string.  It should say "OFF"
   in >> label;
   libmesh_assert_equal_to (label, "OFF");
   // read the number of nodes, faces, and edges
   in >> nn >> nf >> ne;
   Real x=0., y=0., z=0.;
   // Read the nodes
   for (unsigned int n=0; n<nn; n++)
     {
       libmesh_assert (in.good());
       in >> x
          >> y
          >> z;
       the_mesh.add_point ( Point(x,y,z), n );
     }
   unsigned int nv, nid;
   // Read the elements
   for (unsigned int e=0; e<nf; e++)
     {
       libmesh_assert (in.good());
       // The number of vertices in the element
       in >> nv;
       libmesh_assert(nv == 2 || nv == 3);
       if (e == 0)
         {
           the_mesh.set_mesh_dimension(cast_int<unsigned char>(nv-1));
           if (nv == 3)
             {
 #if LIBMESH_DIM < 2
               libmesh_error_msg("Cannot open dimension 2 mesh file when configured without 2D support.");
 #endif
             }
         }
       Elem* elem;
       switch (nv)
         {
         case 2:
           elem = new Edge2;
           break;
         case 3:
           elem = new Tri3;
           break;
         default:
           libmesh_error_msg("Unsupported nv = " << nv);
         }
       elem->set_id(e);
       the_mesh.add_elem (elem);
       for (unsigned int i=0; i<nv; i++)
         {
           in >> nid;
           elem->set_node(i) = the_mesh.node_ptr(nid);
         }
     }
 }
void libMesh::MeshInput< MeshBase >::skip_comment_lines (std::istream & in, const char comment_start) protected inherited
Reads input from in, skipping all the lines that start with the character comment_start.
Referenced by libMesh::TetGenIO::read(), and libMesh::UCDIO::read_implementation().
Member Data Documentation
std::vector<bool> libMesh::MeshInput< MeshBase >::elems_of_dimension protected inherited
A vector of bools describing what dimension elements have been encountered when reading a mesh.
Definition at line 93 of file mesh_input.h.
Referenced by libMesh::GMVIO::_read_one_cell(), libMesh::UNVIO::elements_in(), libMesh::UNVIO::max_elem_dimension_seen(), libMesh::AbaqusIO::max_elem_dimension_seen(), libMesh::AbaqusIO::read(), libMesh::Nemesis_IO::read(), libMesh::ExodusII_IO::read(), libMesh::GMVIO::read(), libMesh::VTKIO::read(), libMesh::AbaqusIO::read_elements(), libMesh::UCDIO::read_implementation(), libMesh::UNVIO::read_implementation(), libMesh::LegacyXdrIO::read_mesh(), and libMesh::XdrIO::read_serialized_connectivity().
The documentation for this class was generated from the following files:
off_io.h
off_io.C