libMesh: libMesh::TriangleInterface::Hole Class Reference
SomeWebsiteLogo
libMesh::TriangleInterface::Hole Class Reference abstract
Class for parameterizing 2D holes to be meshed with Triangle.
#include <mesh_triangle_holes.h>
Public Member Functions
Hole ()
virtual ~Hole ()
virtual unsigned int n_points () const =0
virtual Point point (const unsigned int n) const =0
virtual Point inside () const =0
Detailed Description
Class for parameterizing 2D holes to be meshed with Triangle.
An abstract class for defining a 2-dimensional hole. We assume that the connectivity of the hole is implicit in the numbering of the points, i.e. node 0 is connected to node 1, node 1 is connected to node 2, etc, and the last node "wraps around" to connect back to node 0.
Author
John W. Peterson
Date
2011
Definition at line 44 of file mesh_triangle_holes.h.
Constructor & Destructor Documentation
libMesh::TriangleInterface::Hole::Hole () inline
Constructor
Definition at line 50 of file mesh_triangle_holes.h.
 {}
virtual libMesh::TriangleInterface::Hole::~Hole () inline virtual
Destructor
Definition at line 55 of file mesh_triangle_holes.h.
References inside(), n_points(), and point().
 {}
Member Function Documentation
virtual Point libMesh::TriangleInterface::Hole::inside () const pure virtual
Return an (arbitrary) point which lies inside the hole.
Implemented in libMesh::TriangleInterface::ArbitraryHole, and libMesh::TriangleInterface::PolygonHole.
Referenced by ~Hole().
virtual unsigned int libMesh::TriangleInterface::Hole::n_points () const pure virtual
The number of geometric points which define the hole.
Implemented in libMesh::TriangleInterface::ArbitraryHole, and libMesh::TriangleInterface::PolygonHole.
Referenced by ~Hole().
virtual Point libMesh::TriangleInterface::Hole::point (const unsigned int n) const pure virtual
Return the nth point defining the hole.
Implemented in libMesh::TriangleInterface::ArbitraryHole, and libMesh::TriangleInterface::PolygonHole.
Referenced by ~Hole().
The documentation for this class was generated from the following file:
mesh_triangle_holes.h