libMesh: libMesh::MatlabIO Class Reference
SomeWebsiteLogo
libMesh::MatlabIO Class Reference
#include <matlab_io.h>
Public Member Functions
MatlabIO (MeshBase &)
virtual void read (const std::string &name) libmesh_override
Protected Member Functions
MeshBase & mesh ()
void set_n_partitions (unsigned int n_parts)
void skip_comment_lines (std::istream &in, const char comment_start)
Protected Attributes
std::vector< bool > elems_of_dimension
Private Member Functions
void read_stream (std::istream &in)
Detailed Description
This class implements reading meshes in the Matlab PDE toolkit in a proprietary format.
A VALID INPUT FILE for this type of mesh should be generated in Matlab with the following steps: 1.) Draw the domain and triangulate it in the GUI 2.) Export the mesh to matlab using Mesh->Export Mesh 3.) Create a file with this script: fid = fopen('filename', 'w'); fprintf(fid, 'd d
', length(p), length(t)); fprintf(fid, 'f f
', p); fprintf(fid, 'd d d d
', t); fclose(fid);
What's going on here? There is no standard for exporting PDE toolkit meshes to files in Matlab. When you choose "export mesh" in the GUI, it returns three matrices that it likes to call p, e, and t. All meshes (as far as I can tell) that come from the PDE toolkit are 2D triangle meshes.
p is the point matrix... Row 1: x coordinate Row 2: y coordinate
e is the edge matrix ... Row 1: starting point number (dummy) Row 2: ending point number (dummy) Row 3: starting parameter value (?) (dummy) Row 4: ending parameter value (?) (dummy) Row 5: boundary segment number (?) (dummy) Row 6: left-hand subdomain number (dummy) Row 7: right-hand subdomain number (dummy)
t is the triangle matrix ... Row 1: Node number 1 Row 2: Node number 2 Row 3: Node number 3 Row 4: subdomain number (dummy)
There are some important things to notice here: o The implied ordering of the p matrix is 1..N o The e matrix is entirely irrelevant in this code o All of the matrices are row based
Author
John W. Peterson
Date
2004
Definition at line 83 of file matlab_io.h.
Constructor & Destructor Documentation
libMesh::MatlabIO::MatlabIO (MeshBase & mesh_in) inline explicit
Constructor. Takes a non-const Mesh reference which it will fill up with elements.
Definition at line 112 of file matlab_io.h.
                                       :
   MeshInput<MeshBase>  (mesh_in)
 {}
Member Function Documentation
MeshBase & libMesh::MeshInput< MeshBase >::mesh () protected inherited
Returns the object as a writeable reference.
Referenced by libMesh::GMVIO::_read_one_cell(), libMesh::CheckpointIO::build_elem_list(), libMesh::CheckpointIO::build_node_list(), libMesh::CheckpointIO::current_n_processors(), libMesh::TetGenIO::element_in(), libMesh::UNVIO::elements_in(), libMesh::UNVIO::elements_out(), libMesh::UNVIO::groups_in(), libMesh::TetGenIO::node_in(), libMesh::UNVIO::nodes_in(), libMesh::UNVIO::nodes_out(), libMesh::GMVIO::read(), libMesh::ExodusII_IO::read(), libMesh::CheckpointIO::read(), libMesh::XdrIO::read(), libMesh::CheckpointIO::read_bcs(), libMesh::CheckpointIO::read_connectivity(), libMesh::UCDIO::read_implementation(), libMesh::UNVIO::read_implementation(), libMesh::GmshIO::read_mesh(), libMesh::CheckpointIO::read_nodes(), libMesh::CheckpointIO::read_nodesets(), libMesh::XdrIO::read_serialized_bcs_helper(), libMesh::XdrIO::read_serialized_connectivity(), libMesh::XdrIO::read_serialized_nodes(), libMesh::XdrIO::read_serialized_nodesets(), libMesh::XdrIO::read_serialized_subdomain_names(), libMesh::OFFIO::read_stream(), read_stream(), libMesh::CheckpointIO::read_subdomain_names(), libMesh::UCDIO::UCDIO(), libMesh::VTKIO::VTKIO(), libMesh::TetGenIO::write(), libMesh::ExodusII_IO::write(), libMesh::CheckpointIO::write(), libMesh::XdrIO::write(), libMesh::GMVIO::write_ascii_new_impl(), libMesh::GMVIO::write_ascii_old_impl(), libMesh::CheckpointIO::write_bcs(), libMesh::GMVIO::write_binary(), libMesh::CheckpointIO::write_connectivity(), libMesh::GMVIO::write_discontinuous_gmv(), libMesh::ExodusII_IO::write_element_data(), libMesh::UCDIO::write_implementation(), libMesh::GmshIO::write_mesh(), libMesh::UCDIO::write_nodal_data(), libMesh::ExodusII_IO::write_nodal_data(), libMesh::ExodusII_IO::write_nodal_data_common(), libMesh::ExodusII_IO::write_nodal_data_discontinuous(), libMesh::CheckpointIO::write_nodes(), libMesh::CheckpointIO::write_nodesets(), libMesh::XdrIO::write_parallel(), libMesh::GmshIO::write_post(), libMesh::XdrIO::write_serialized_bcs_helper(), libMesh::XdrIO::write_serialized_connectivity(), libMesh::XdrIO::write_serialized_nodes(), libMesh::XdrIO::write_serialized_nodesets(), libMesh::XdrIO::write_serialized_subdomain_names(), and libMesh::CheckpointIO::write_subdomain_names().
void libMesh::MatlabIO::read (const std::string & name) virtual
Reads in a matlab data file based on the string you pass it.
Implements libMesh::MeshInput< MeshBase >.
Definition at line 33 of file matlab_io.C.
References read_stream().
Referenced by libMesh::NameBasedIO::read().
 {
   std::ifstream in (name.c_str());
   this->read_stream(in);
 }
void libMesh::MatlabIO::read_stream (std::istream & in) private
Implementation of the read() function. This function is called by the public interface function and implements reading the file.
Definition at line 41 of file matlab_io.C.
References libMesh::MeshBase::add_elem(), libMesh::MeshBase::add_point(), libMesh::MeshBase::clear(), libMesh::libmesh_assert(), libMesh::MeshInput< MeshBase >::mesh(), libMesh::MeshInput< MT >::mesh(), libMesh::MeshBase::node_ptr(), libMesh::processor_id(), libMesh::Real, libMesh::DofObject::set_id(), libMesh::MeshBase::set_mesh_dimension(), libMesh::Elem::set_node(), and libMesh::x.
Referenced by read().
 {
   // This is a serial-only process for now;
   // the Mesh should be read on processor 0 and
   // broadcast later
   libmesh_assert_equal_to (this->mesh().processor_id(), 0);
   // Get a reference to the mesh
   MeshBase & the_mesh = MeshInput<MeshBase>::mesh();
   // Clear any existing mesh data
   the_mesh.clear();
   // PDE toolkit only works in 2D
   the_mesh.set_mesh_dimension(2);
 #if LIBMESH_DIM < 2
   libmesh_error_msg("Cannot open dimension 2 mesh file when configured without 2D support.");
 #endif
   // Check the input buffer
   libmesh_assert (in.good());
   unsigned int nNodes=0, nElem=0;
   in >> nNodes   // Read the number of nodes
      >> nElem;   // Read the number of elements
   // Sort of check that it worked
   libmesh_assert_greater (nNodes, 0);
   libmesh_assert_greater (nElem, 0);
   // Read the nodal coordinates
   {
     Real x=0., y=0., z=0.;
     for (unsigned int i=0; i<nNodes; i++)
       {
         in >> x   // x-coordinate value
            >> y;  // y-coordinate value
         the_mesh.add_point ( Point(x,y,z), i);
       }
   }
   // Read the elements (elements)
   {
     unsigned int node=0, dummy=0;
     for (unsigned int i=0; i<nElem; i++)
       {
         Elem * elem = new Tri3; // Always build a triangle
         elem->set_id(i);
         the_mesh.add_elem (elem);
         for (unsigned int n=0; n<3; n++)  // Always read three 3 nodes
           {
             in >> node;
             elem->set_node(n) = the_mesh.node_ptr(node-1);  // Assign the node number
           }
         // There is an additional subdomain number here,
         // so we read it and get rid of it!
         in >> dummy;
       }
   }
 }
void libMesh::MeshInput< MeshBase >::set_n_partitions (unsigned int n_parts) inline protected inherited
Sets the number of partitions in the mesh. Typically this gets done by the partitioner, but some parallel file formats begin "pre-partitioned".
Definition at line 91 of file mesh_input.h.
References libMesh::MeshInput< MT >::mesh().
Referenced by libMesh::Nemesis_IO::read(), and libMesh::XdrIO::read().
 { this->mesh().set_n_partitions() = n_parts; }
void libMesh::MeshInput< MeshBase >::skip_comment_lines (std::istream & in, const char comment_start) protected inherited
Reads input from in, skipping all the lines that start with the character comment_start.
Referenced by libMesh::TetGenIO::read(), and libMesh::UCDIO::read_implementation().
Member Data Documentation
std::vector<bool> libMesh::MeshInput< MeshBase >::elems_of_dimension protected inherited
A vector of bools describing what dimension elements have been encountered when reading a mesh.
Definition at line 97 of file mesh_input.h.
Referenced by libMesh::GMVIO::_read_one_cell(), libMesh::UNVIO::elements_in(), libMesh::UNVIO::max_elem_dimension_seen(), libMesh::AbaqusIO::max_elem_dimension_seen(), libMesh::AbaqusIO::read(), libMesh::GMVIO::read(), libMesh::Nemesis_IO::read(), libMesh::ExodusII_IO::read(), libMesh::VTKIO::read(), libMesh::AbaqusIO::read_elements(), libMesh::UCDIO::read_implementation(), libMesh::UNVIO::read_implementation(), and libMesh::XdrIO::read_serialized_connectivity().
The documentation for this class was generated from the following files:
matlab_io.h
matlab_io.C