libMesh: libMesh::Parallel::Packing< const Elem * > Class Template Reference
SomeWebsiteLogo
libMesh::Parallel::Packing< const Elem * > Class Template Reference
#include <parallel_elem.h>
Public Types
typedef largest_id_type buffer_type
Public Member Functions
template<>
unsigned int packed_size (std::vector< largest_id_type >::const_iterator in)
template<>
unsigned int packed_size (std::vector< largest_id_type >::iterator in)
template<>
unsigned int packable_size (const Elem *const &elem, const MeshBase *mesh)
template<>
unsigned int packable_size (const Elem *const &elem, const DistributedMesh *mesh)
template<>
unsigned int packable_size (const Elem *const &elem, const ParallelMesh *mesh)
template<>
void pack (const Elem *const &elem, std::back_insert_iterator< std::vector< largest_id_type > > data_out, const MeshBase *mesh)
template<>
void pack (const Elem *const &elem, std::back_insert_iterator< std::vector< largest_id_type > > data_out, const DistributedMesh *mesh)
template<>
void pack (const Elem *const &elem, std::back_insert_iterator< std::vector< largest_id_type > > data_out, const ParallelMesh *mesh)
Static Public Member Functions
template<typename OutputIter , typename Context >
static void pack (const Elem *const &object, OutputIter data_out, const Context *context)
template<typename Context >
static unsigned int packable_size (const Elem *const &object, const Context *context)
template<typename BufferIter >
static unsigned int packed_size (BufferIter iter)
template<typename BufferIter , typename Context >
static const Elem * unpack (BufferIter in, Context *ctx)
Detailed Description
template<>
class libMesh::Parallel::Packing< const Elem * >
Definition at line 35 of file parallel_elem.h.
Member Typedef Documentation
typedef largest_id_type libMesh::Parallel::Packing< const Elem * >::buffer_type
Definition at line 38 of file parallel_elem.h.
Member Function Documentation
template<typename OutputIter , typename Context > static void libMesh::Parallel::Packing< const Elem * >::pack (const Elem *const & object, OutputIter data_out, const Context * context) static
template<> void libMesh::Parallel::Packing< const Elem * >::pack (const Elem *const & elem, std::back_insert_iterator< std::vector< largest_id_type > > data_out, const MeshBase * mesh)
Definition at line 203 of file parallel_elem.C.
References libMesh::BoundaryInfo::boundary_ids(), libMesh::Elem::dim(), libMesh::BoundaryInfo::edge_boundary_ids(), libMesh::MeshBase::get_boundary_info(), libMesh::Elem::has_children(), libMesh::DofObject::id(), libMesh::Elem::interior_parent(), libMesh::DofObject::invalid_id, libMesh::Elem::INVALID_REFINEMENTSTATE, libMesh::DofObject::invalid_unique_id, libMesh::Elem::level(), libMesh::libmesh_assert(), libMesh::Elem::n_edges(), libMesh::Elem::n_neighbors(), libMesh::Elem::n_nodes(), libMesh::Elem::n_sides(), libMesh::Elem::neighbor_ptr(), libMesh::Elem::node_id(), libMesh::Elem::p_level(), libMesh::Elem::p_refinement_flag(), libMesh::DofObject::pack_indexing(), libMesh::Elem::parent(), libMesh::DofObject::processor_id(), libMesh::Elem::refinement_flag(), libMesh::BoundaryInfo::shellface_boundary_ids(), libMesh::Elem::subdomain_id(), libMesh::Elem::type(), libMesh::DofObject::unique_id(), libMesh::DofObject::valid_unique_id(), and libMesh::Elem::which_child_am_i().
 {
   libmesh_assert(elem);
 #ifndef NDEBUG
   *data_out++ = elem_magic_header;
 #endif
 #ifdef LIBMESH_ENABLE_AMR
   *data_out++ = (static_cast<largest_id_type>(elem->level()));
   *data_out++ = (static_cast<largest_id_type>(elem->p_level()));
   // Encode both the refinement flag and whether the element has
   // children together.  This coding is unambiguous because our
   // refinement state encoding starts at 0 and ends at
   // INVALID_REFINEMENTSTATE
   largest_id_type refinement_info =
     static_cast<largest_id_type>(elem->refinement_flag());
   if (elem->has_children())
     refinement_info +=
       static_cast<largest_id_type>(Elem::INVALID_REFINEMENTSTATE) + 1;
   *data_out++ = (refinement_info);
   *data_out++ = (static_cast<largest_id_type>(elem->p_refinement_flag()));
 #else
   *data_out++ = (0);
   *data_out++ = (0);
   *data_out++ = (0);
   *data_out++ = (0);
 #endif
   *data_out++ = (static_cast<largest_id_type>(elem->type()));
   *data_out++ = (elem->processor_id());
   *data_out++ = (elem->subdomain_id());
   *data_out++ = (elem->id());
 #ifdef LIBMESH_ENABLE_UNIQUE_ID
   if (elem->valid_unique_id())
     *data_out++ = (static_cast<largest_id_type>(elem->unique_id()));
   else
     // OK to send invalid unique id, we must not own this DOF
     *data_out++ = (static_cast<largest_id_type>(DofObject::invalid_unique_id));
 #endif
 #ifdef LIBMESH_ENABLE_AMR
   // use parent_ID of invalid_id to indicate a level 0 element
   if (elem->level() == 0)
     {
       *data_out++ =(DofObject::invalid_id);
       *data_out++ =(DofObject::invalid_id);
     }
   else
     {
       *data_out++ =(elem->parent()->id());
       *data_out++ =(elem->parent()->which_child_am_i(elem));
     }
 #else
   *data_out++ = (DofObject::invalid_id);
   *data_out++ = (DofObject::invalid_id);
 #endif
   if ((elem->dim() < LIBMESH_DIM) &&
       elem->interior_parent())
     *data_out++ =(elem->interior_parent()->id());
   else
     *data_out++ =(DofObject::invalid_id);
   for (unsigned int n=0; n<elem->n_nodes(); n++)
     *data_out++ = (elem->node_id(n));
   for (unsigned int n=0; n<elem->n_neighbors(); n++)
     {
       const Elem * neigh = elem->neighbor_ptr(n);
       if (neigh)
         *data_out++ = (neigh->id());
       else
         *data_out++ = (DofObject::invalid_id);
     }
   // Add any DofObject indices
   elem->pack_indexing(data_out);
   // If this is a coarse element,
   // Add any element side boundary condition ids
   if (elem->level() == 0)
     {
       std::vector<boundary_id_type> bcs;
       for (unsigned short s = 0; s != elem->n_sides(); ++s)
         {
           mesh->get_boundary_info().boundary_ids(elem, s, bcs);
           *data_out++ =(bcs.size());
           for (std::vector<boundary_id_type>::iterator bc_it=bcs.begin();
                bc_it != bcs.end(); ++bc_it)
             *data_out++ =(*bc_it);
         }
       for (unsigned short e = 0; e != elem->n_edges(); ++e)
         {
           mesh->get_boundary_info().edge_boundary_ids(elem, e, bcs);
           *data_out++ =(bcs.size());
           for (std::vector<boundary_id_type>::iterator bc_it=bcs.begin();
                bc_it != bcs.end(); ++bc_it)
             *data_out++ =(*bc_it);
         }
       for (unsigned short sf=0; sf != 2; ++sf)
         {
           mesh->get_boundary_info().shellface_boundary_ids(elem, sf, bcs);
           *data_out++ =(bcs.size());
           for (std::vector<boundary_id_type>::iterator bc_it=bcs.begin();
                bc_it != bcs.end(); ++bc_it)
             *data_out++ =(*bc_it);
         }
     }
 }
template<> void libMesh::Parallel::Packing< const Elem * >::pack (const Elem *const & elem, std::back_insert_iterator< std::vector< largest_id_type > > data_out, const DistributedMesh * mesh)
Definition at line 331 of file parallel_elem.C.
References libMesh::Parallel::Packing< T >::pack().
 {
   pack(elem, data_out, static_cast<const MeshBase*>(mesh));
 }
template<> void libMesh::Parallel::Packing< const Elem * >::pack (const Elem *const & elem, std::back_insert_iterator< std::vector< largest_id_type > > data_out, const ParallelMesh * mesh)
Definition at line 343 of file parallel_elem.C.
References libMesh::Parallel::Packing< T >::pack().
 {
   pack(elem, data_out, static_cast<const MeshBase*>(mesh));
 }
template<typename Context > static unsigned int libMesh::Parallel::Packing< const Elem * >::packable_size (const Elem *const & object, const Context * context) static
template<> unsigned int libMesh::Parallel::Packing< const Elem * >::packable_size (const Elem *const & elem, const MeshBase * mesh)
Definition at line 145 of file parallel_elem.C.
References libMesh::MeshBase::get_boundary_info(), libMesh::Elem::level(), libMesh::BoundaryInfo::n_boundary_ids(), libMesh::BoundaryInfo::n_edge_boundary_ids(), libMesh::Elem::n_edges(), libMesh::Elem::n_neighbors(), libMesh::Elem::n_nodes(), libMesh::BoundaryInfo::n_shellface_boundary_ids(), libMesh::Elem::n_sides(), and libMesh::DofObject::packed_indexing_size().
 {
   unsigned int total_packed_bcs = 0;
   if (elem->level() == 0)
     {
       total_packed_bcs += elem->n_sides();
       for (unsigned short s = 0; s != elem->n_sides(); ++s)
         total_packed_bcs +=
           mesh->get_boundary_info().n_boundary_ids(elem,s);
       total_packed_bcs += elem->n_edges();
       for (unsigned short e = 0; e != elem->n_edges(); ++e)
         total_packed_bcs +=
           mesh->get_boundary_info().n_edge_boundary_ids(elem,e);
       total_packed_bcs += 2; // shellfaces
       for (unsigned short sf=0; sf != 2; ++sf)
         total_packed_bcs +=
           mesh->get_boundary_info().n_shellface_boundary_ids(elem,sf);
     }
   return
 #ifndef NDEBUG
     1 + // add an int for the magic header when testing
 #endif
     header_size + elem->n_nodes() +
     elem->n_neighbors() +
     elem->packed_indexing_size() + total_packed_bcs;
 }
template<> unsigned int libMesh::Parallel::Packing< const Elem * >::packable_size (const Elem *const & elem, const DistributedMesh * mesh)
Definition at line 181 of file parallel_elem.C.
References libMesh::Parallel::Packing< T >::packable_size().
 {
   return packable_size(elem, static_cast<const MeshBase *>(mesh));
 }
template<> unsigned int libMesh::Parallel::Packing< const Elem * >::packable_size (const Elem *const & elem, const ParallelMesh * mesh)
Definition at line 192 of file parallel_elem.C.
References libMesh::Parallel::Packing< T >::packable_size().
 {
   return packable_size(elem, static_cast<const MeshBase *>(mesh));
 }
template<typename BufferIter > static unsigned int libMesh::Parallel::Packing< const Elem * >::packed_size (BufferIter iter) static
template<> unsigned int libMesh::Parallel::Packing< const Elem * >::packed_size (std::vector< largest_id_type >::const_iterator in)
Definition at line 59 of file parallel_elem.C.
References libMesh::INVALID_ELEM, n_nodes, libMesh::Elem::type_to_n_edges_map, libMesh::Elem::type_to_n_nodes_map, libMesh::Elem::type_to_n_sides_map, and libMesh::DofObject::unpackable_indexing_size().
 {
 #ifndef NDEBUG
   const largest_id_type packed_header = *in++;
   libmesh_assert_equal_to (packed_header, elem_magic_header);
 #endif
   // int 0: level
   const unsigned int level =
     cast_int<unsigned int>(*in);
   // int 4: element type
   const int typeint = cast_int<int>(*(in+4));
   libmesh_assert_greater_equal (typeint, 0);
   libmesh_assert_less (typeint, INVALID_ELEM);
   const ElemType type =
     cast_int<ElemType>(typeint);
   const unsigned int n_nodes =
     Elem::type_to_n_nodes_map[type];
   const unsigned int n_sides =
     Elem::type_to_n_sides_map[type];
   const unsigned int n_edges =
     Elem::type_to_n_edges_map[type];
   const unsigned int pre_indexing_size =
     header_size + n_nodes + n_sides;
   const unsigned int indexing_size =
     DofObject::unpackable_indexing_size(in+pre_indexing_size);
   unsigned int total_packed_bc_data = 0;
   if (level == 0)
     {
       for (unsigned int s = 0; s != n_sides; ++s)
         {
           const int n_bcs = cast_int<int>
             (*(in + pre_indexing_size + indexing_size +
                total_packed_bc_data++));
           libmesh_assert_greater_equal (n_bcs, 0);
           total_packed_bc_data += n_bcs;
         }
       for (unsigned int e = 0; e != n_edges; ++e)
         {
           const int n_bcs = cast_int<int>
             (*(in + pre_indexing_size + indexing_size +
                total_packed_bc_data++));
           libmesh_assert_greater_equal (n_bcs, 0);
           total_packed_bc_data += n_bcs;
         }
       for (unsigned short sf=0; sf != 2; ++sf)
         {
           const int n_bcs = cast_int<int>
             (*(in + pre_indexing_size + indexing_size +
                total_packed_bc_data++));
           libmesh_assert_greater_equal (n_bcs, 0);
           total_packed_bc_data += n_bcs;
         }
     }
   return
 #ifndef NDEBUG
     1 + // Account for magic header
 #endif
     pre_indexing_size + indexing_size + total_packed_bc_data;
 }
template<> unsigned int libMesh::Parallel::Packing< const Elem * >::packed_size (std::vector< largest_id_type >::iterator in)
Definition at line 135 of file parallel_elem.C.
References libMesh::Parallel::Packing< T >::packed_size().
 {
   return packed_size(std::vector<largest_id_type>::const_iterator(in));
 }
template<typename BufferIter , typename Context > const Elem * libMesh::Parallel::Packing< const Elem * >::unpack (BufferIter in, Context * ctx) inline static
Definition at line 85 of file parallel_elem.h.
References libMesh::Parallel::Packing< T >::unpack().
 { return Packing<Elem*>::unpack(in, ctx); }
The documentation for this class was generated from the following files:
parallel_elem.h
parallel_elem.C