libMesh: libMesh::DirichletBoundary Class Reference
SomeWebsiteLogo
libMesh::DirichletBoundary Class Reference
Class for specifying Dirichlet boundary conditions as constraints.
#include <dirichlet_boundaries.h>
Public Member Functions
DirichletBoundary (const std::set< boundary_id_type > &b_in, const std::vector< unsigned int > &variables_in, const FunctionBase< Number > *f_in, const FunctionBase< Gradient > *g_in=libmesh_nullptr)
DirichletBoundary (const std::set< boundary_id_type > &b_in, const std::vector< unsigned int > &variables_in, const FunctionBase< Number > &f_in, VariableIndexing type=SYSTEM_VARIABLE_ORDER)
DirichletBoundary (const std::set< boundary_id_type > &b_in, const std::vector< unsigned int > &variables_in, const FunctionBase< Number > &f_in, const FunctionBase< Gradient > &g_in, VariableIndexing type=SYSTEM_VARIABLE_ORDER)
DirichletBoundary (const std::set< boundary_id_type > &b_in, const std::vector< unsigned int > &variables_in, const System &f_sys_in, const FEMFunctionBase< Number > *f_in, const FEMFunctionBase< Gradient > *g_in=libmesh_nullptr)
DirichletBoundary (const std::set< boundary_id_type > &b_in, const std::vector< unsigned int > &variables_in, const System &f_sys_in, const FEMFunctionBase< Number > &f_in, VariableIndexing type=SYSTEM_VARIABLE_ORDER)
DirichletBoundary (const std::set< boundary_id_type > &b_in, const std::vector< unsigned int > &variables_in, const System &f_sys_in, const FEMFunctionBase< Number > &f_in, const FEMFunctionBase< Gradient > &g_in, VariableIndexing type=SYSTEM_VARIABLE_ORDER)
DirichletBoundary (const DirichletBoundary &dirichlet_in)
~DirichletBoundary ()
Public Attributes
std::set< boundary_id_type > b
std::vector< unsigned int > variables
UniquePtr< FunctionBase< Number > > f
UniquePtr< FunctionBase< Gradient > > g
UniquePtr< FEMFunctionBase< Number > > f_fem
UniquePtr< FEMFunctionBase< Gradient > > g_fem
const System * f_system
Detailed Description
Class for specifying Dirichlet boundary conditions as constraints.
This class allows one to associate Dirichlet boundary values with a given set of mesh boundary ids and system variable ids.
Dirichlet values must be supplied as the input function "f"; when using some specialized elements, gradient values must be supplied via the input function "g".
Dirichlet functions may be subclasses of FunctionBase or FEMFunctionBase; in the latter case the user must also supply a reference to the System on which the FEMFunctionBase will be evaluated.
Dirichlet functions are allowed to return NaN; if this is encountered, then the degree of freedom values in a patch around the location of the returned NaN will be left unconstrained. E.g. a NaN on a boundary edge in 3D would leave that edge and the two adjoining face interiors unconstrained, but would still permit the other edge and node DoFs around those faces to be constrained.
Author
Roy Stogner
Date
2012
Definition at line 88 of file dirichlet_boundaries.h.
Constructor & Destructor Documentation
libMesh::DirichletBoundary::DirichletBoundary (const std::set< boundary_id_type > & b_in, const std::vector< unsigned int > & variables_in, const FunctionBase< Number > * f_in, const FunctionBase< Gradient > * g_in = libmesh_nullptr)
Constructor for a system-variable-order boundary using pointers-to-functors.
Definition at line 34 of file dirichlet_boundary.C.
References libMesh::libmesh_assert().
Referenced by DirichletBoundary().
                                         :
   b(b_in),
   variables(variables_in),
   f(f_in ? f_in->clone() : UniquePtr<FunctionBase<Number> >()),
   g(g_in ? g_in->clone() : UniquePtr<FunctionBase<Gradient> >()),
   f_fem(UniquePtr<FEMFunctionBase<Number> >()),
   g_fem(UniquePtr<FEMFunctionBase<Gradient> >()),
   f_system(libmesh_nullptr)
 {
   libmesh_assert(f.get());
   f->init();
   if (g.get())
     g->init();
 }
libMesh::DirichletBoundary::DirichletBoundary (const std::set< boundary_id_type > & b_in, const std::vector< unsigned int > & variables_in, const FunctionBase< Number > & f_in, VariableIndexing type = SYSTEM_VARIABLE_ORDER)
Constructor for a boundary from reference-to-functor.
Defaults to system variable indexing for backwards compatibility, but most users will prefer local indexing.
Definition at line 54 of file dirichlet_boundary.C.
References libMesh::CompositeFunction< Output >::attach_subfunction(), libMesh::FunctionBase< Output >::clone(), DirichletBoundary(), and libMesh::LOCAL_VARIABLE_ORDER.
                           :
   b(b_in),
   variables(variables_in),
   f(UniquePtr<FunctionBase<Number> >()),
   g(UniquePtr<FunctionBase<Gradient> >()),
   f_fem(UniquePtr<FEMFunctionBase<Number> >()),
   g_fem(UniquePtr<FEMFunctionBase<Gradient> >()),
   f_system(libmesh_nullptr)
 {
   if (type == LOCAL_VARIABLE_ORDER)
     {
       CompositeFunction<Number> * c =
         new CompositeFunction<Number>();
       c->attach_subfunction(f_in, variables_in);
       f.reset(c);
     }
   else
     {
       f.reset(f_in.clone().release());
     }
   f->init();
 }
libMesh::DirichletBoundary::DirichletBoundary (const std::set< boundary_id_type > & b_in, const std::vector< unsigned int > & variables_in, const FunctionBase< Number > & f_in, const FunctionBase< Gradient > & g_in, VariableIndexing type = SYSTEM_VARIABLE_ORDER)
Constructor for a system-variable-order boundary from references-to-functors.
Defaults to system variable indexing for backwards compatibility, but most users will prefer local indexing.
Definition at line 82 of file dirichlet_boundary.C.
References libMesh::CompositeFunction< Output >::attach_subfunction(), libMesh::FunctionBase< Output >::clone(), DirichletBoundary(), and libMesh::LOCAL_VARIABLE_ORDER.
                           :
   b(b_in),
   variables(variables_in),
   f(UniquePtr<FunctionBase<Number> >()),
   g(UniquePtr<FunctionBase<Gradient> >()),
   f_fem(UniquePtr<FEMFunctionBase<Number> >()),
   g_fem(UniquePtr<FEMFunctionBase<Gradient> >()),
   f_system(libmesh_nullptr)
 {
   if (type == LOCAL_VARIABLE_ORDER)
     {
       CompositeFunction<Number> * cf =
         new CompositeFunction<Number>();
       cf->attach_subfunction(f_in, variables_in);
       f.reset(cf);
       CompositeFunction<Gradient> * cg =
         new CompositeFunction<Gradient>();
       cg->attach_subfunction(g_in, variables_in);
       g.reset(cg);
     }
   else
     {
       f.reset(f_in.clone().release());
       g.reset(g_in.clone().release());
     }
   f->init();
   g->init();
 }
libMesh::DirichletBoundary::DirichletBoundary (const std::set< boundary_id_type > & b_in, const std::vector< unsigned int > & variables_in, const System & f_sys_in, const FEMFunctionBase< Number > * f_in, const FEMFunctionBase< Gradient > * g_in = libmesh_nullptr)
Constructor for a system-variable-order boundary from pointers-to-fem-functors.
Definition at line 118 of file dirichlet_boundary.C.
References DirichletBoundary(), and libMesh::libmesh_assert().
                                            :
   b(b_in),
   variables(variables_in),
   f(UniquePtr<FunctionBase<Number> >()),
   g(UniquePtr<FunctionBase<Gradient> >()),
   f_fem(f_in ? f_in->clone() : UniquePtr<FEMFunctionBase<Number> >()),
   g_fem(g_in ? g_in->clone() : UniquePtr<FEMFunctionBase<Gradient> >()),
   f_system(&f_sys_in)
 {
   libmesh_assert(f_fem.get());
 }
libMesh::DirichletBoundary::DirichletBoundary (const std::set< boundary_id_type > & b_in, const std::vector< unsigned int > & variables_in, const System & f_sys_in, const FEMFunctionBase< Number > & f_in, VariableIndexing type = SYSTEM_VARIABLE_ORDER)
Constructor for a system-variable-order boundary from reference-to-fem-functor.
Defaults to system variable indexing for backwards compatibility, but most users will prefer local indexing.
Definition at line 136 of file dirichlet_boundary.C.
References libMesh::CompositeFEMFunction< Output >::attach_subfunction(), libMesh::FEMFunctionBase< Output >::clone(), DirichletBoundary(), and libMesh::LOCAL_VARIABLE_ORDER.
                           :
   b(b_in),
   variables(variables_in),
   f(UniquePtr<FunctionBase<Number> >()),
   g(UniquePtr<FunctionBase<Gradient> >()),
   f_fem(UniquePtr<FEMFunctionBase<Number> >()),
   g_fem(UniquePtr<FEMFunctionBase<Gradient> >()),
   f_system(&f_sys_in)
 {
   if (type == LOCAL_VARIABLE_ORDER)
     {
       CompositeFEMFunction<Number> * c = new CompositeFEMFunction<Number>();
       c->attach_subfunction(f_in, variables_in);
       f_fem.reset(c);
     }
   else
     {
       f_fem.reset(f_in.clone().release());
     }
 }
libMesh::DirichletBoundary::DirichletBoundary (const std::set< boundary_id_type > & b_in, const std::vector< unsigned int > & variables_in, const System & f_sys_in, const FEMFunctionBase< Number > & f_in, const FEMFunctionBase< Gradient > & g_in, VariableIndexing type = SYSTEM_VARIABLE_ORDER)
Constructor for a system-variable-order boundary from references-to-fem-functors.
Defaults to system variable indexing for backwards compatibility, but most users will prefer local indexing.
Definition at line 163 of file dirichlet_boundary.C.
References libMesh::CompositeFEMFunction< Output >::attach_subfunction(), libMesh::FEMFunctionBase< Output >::clone(), DirichletBoundary(), and libMesh::LOCAL_VARIABLE_ORDER.
                           :
   b(b_in),
   variables(variables_in),
   f(UniquePtr<FunctionBase<Number> >()),
   g(UniquePtr<FunctionBase<Gradient> >()),
   f_fem(UniquePtr<FEMFunctionBase<Number> >()),
   g_fem(UniquePtr<FEMFunctionBase<Gradient> >()),
   f_system(&f_sys_in)
 {
   if (type == LOCAL_VARIABLE_ORDER)
     {
       CompositeFEMFunction<Number> * cf =
         new CompositeFEMFunction<Number>();
       cf->attach_subfunction(f_in, variables_in);
       f_fem.reset(cf);
       CompositeFEMFunction<Gradient> * cg =
         new CompositeFEMFunction<Gradient>();
       cg->attach_subfunction(g_in, variables_in);
       g_fem.reset(cg);
     }
   else
     {
       f_fem.reset(f_in.clone().release());
       g_fem.reset(g_in.clone().release());
     }
 }
libMesh::DirichletBoundary::DirichletBoundary (const DirichletBoundary & dirichlet_in)
Copy constructor. Deep copies (clones) functors; shallow copies any System reference
Definition at line 197 of file dirichlet_boundary.C.
References libMesh::libmesh_assert().
                                            :
   b(dirichlet_in.b),
   variables(dirichlet_in.variables),
   f(dirichlet_in.f.get() ?
     dirichlet_in.f->clone() : UniquePtr<FunctionBase<Number> >()),
   g(dirichlet_in.g.get() ?
     dirichlet_in.g->clone() : UniquePtr<FunctionBase<Gradient> >()),
   f_fem(dirichlet_in.f_fem.get() ?
         dirichlet_in.f_fem->clone() : UniquePtr<FEMFunctionBase<Number> >()),
   g_fem(dirichlet_in.g_fem.get() ?
         dirichlet_in.g_fem->clone() : UniquePtr<FEMFunctionBase<Gradient> >()),
   f_system(dirichlet_in.f_system)
 {
   libmesh_assert(f.get() || f_fem.get());
   libmesh_assert(!(f.get() && f_fem.get()));
   libmesh_assert(!(f.get() && g_fem.get()));
   libmesh_assert(!(f_fem.get() && g.get()));
   libmesh_assert(!(f_fem.get() && !f_system));
   if (f.get())
     f->init();
   if (g.get())
     g->init();
 }
libMesh::DirichletBoundary::~DirichletBoundary ()
Standard destructor
Definition at line 222 of file dirichlet_boundary.C.
 {}
Member Data Documentation
std::set<boundary_id_type> libMesh::DirichletBoundary::b
Definition at line 173 of file dirichlet_boundaries.h.
Referenced by libMesh::DifferentiableSystem::add_dot_var_dirichlet_bcs(), libMesh::DofMap::check_dirichlet_bcid_consistency(), libMesh::DofMap::remove_adjoint_dirichlet_boundary(), and libMesh::DofMap::remove_dirichlet_boundary().
UniquePtr<FunctionBase<Number> > libMesh::DirichletBoundary::f
Definition at line 176 of file dirichlet_boundaries.h.
Referenced by libMesh::DifferentiableSystem::add_dot_var_dirichlet_bcs().
UniquePtr<FEMFunctionBase<Number> > libMesh::DirichletBoundary::f_fem
Definition at line 179 of file dirichlet_boundaries.h.
Referenced by libMesh::DifferentiableSystem::add_dot_var_dirichlet_bcs().
const System* libMesh::DirichletBoundary::f_system
Definition at line 182 of file dirichlet_boundaries.h.
UniquePtr<FunctionBase<Gradient> > libMesh::DirichletBoundary::g
Definition at line 177 of file dirichlet_boundaries.h.
UniquePtr<FEMFunctionBase<Gradient> > libMesh::DirichletBoundary::g_fem
Definition at line 180 of file dirichlet_boundaries.h.
std::vector<unsigned int> libMesh::DirichletBoundary::variables
Definition at line 174 of file dirichlet_boundaries.h.
Referenced by libMesh::DifferentiableSystem::add_dot_var_dirichlet_bcs(), libMesh::DofMap::remove_adjoint_dirichlet_boundary(), and libMesh::DofMap::remove_dirichlet_boundary().
The documentation for this class was generated from the following files:
dirichlet_boundaries.h
dirichlet_boundary.C