libMesh: libMesh::ParameterMultiPointer< T > Class Template Reference
SomeWebsiteLogo
libMesh::ParameterMultiPointer< T > Class Template Reference
Stores multiple user-provided pointers.
#include <parameter_multipointer.h>
Public Member Functions
ParameterMultiPointer ()
ParameterMultiPointer (T *param_ptr)
virtual ParameterAccessor< T > & operator= (T *) libmesh_override
virtual void set (const T &new_value) libmesh_override
virtual const T & get () const libmesh_override
virtual UniquePtr< ParameterAccessor< T > > clone () const libmesh_override
void push_back (T *new_ptr)
std::size_t size () const
ParameterProxy< T > operator* ()
ConstParameterProxy< T > operator* () const
Private Attributes
std::vector< T * > _ptrs
Detailed Description
template<typename T = Number>
class libMesh::ParameterMultiPointer< T >
Stores multiple user-provided pointers.
Accessor object allowing reading and modification of the independent variables in a parameter sensitivity calculation.
This is a slightly flexible ParameterAccessor subclass: it stores all user-provided pointers to copies of the parameter, and modifies the value at each location in memory.
Author
Roy Stogner
Date
2015
Definition at line 47 of file parameter_multipointer.h.
Constructor & Destructor Documentation
template<typename T = Number> libMesh::ParameterMultiPointer< T >::ParameterMultiPointer () inline
Constructor: no parameters attached yet
Definition at line 53 of file parameter_multipointer.h.
 {}
template<typename T = Number> libMesh::ParameterMultiPointer< T >::ParameterMultiPointer (T * param_ptr) inline
Constructor: take the first raw pointer to the parameter
Definition at line 58 of file parameter_multipointer.h.
 : _ptrs(1, param_ptr) {}
Member Function Documentation
template<typename T = Number> virtual UniquePtr<ParameterAccessor<T> > libMesh::ParameterMultiPointer< T >::clone () const inline virtual
Returns a new copy of the accessor.
Implements libMesh::ParameterAccessor< T >.
Definition at line 108 of file parameter_multipointer.h.
References libMesh::ParameterMultiPointer< T >::_ptrs.
   {
     ParameterMultiPointer * pmp = new ParameterMultiPointer<T>();
     pmp->_ptrs = _ptrs;
     return UniquePtr<ParameterAccessor<T> >(pmp);
   }
template<typename T = Number> virtual const T& libMesh::ParameterMultiPointer< T >::get () const inline virtual
Getter: get the value of the parameter we access.
Implements libMesh::ParameterAccessor< T >.
Definition at line 92 of file parameter_multipointer.h.
References libMesh::ParameterMultiPointer< T >::_ptrs, and libMesh::libmesh_assert().
   {
     libmesh_assert(!_ptrs.empty());
     T & val = *_ptrs[0];
 #ifndef NDEBUG
     // If you're already using inconsistent parameters we can't help
     // you.
     for (std::size_t i=1; i < _ptrs.size(); ++i)
       libmesh_assert_equal_to(*_ptrs[i], val);
 #endif
     return val;
   }
template<typename T = Number> ParameterProxy<T> libMesh::ParameterAccessor< T >::operator* () inline inherited
Proxy: for backward compatibility, we allow codes to treat a ParameterAccessor as if it were a simple pointer-to-value. We can't safely allow "Number * n = parameter_vector[p]" to compile, but we can allow "*parameter_vector[p] += deltap" to work.
Definition at line 86 of file parameter_accessor.h.
 { return ParameterProxy<T>(*this); }
template<typename T = Number> ConstParameterProxy<T> libMesh::ParameterAccessor< T >::operator* () const inline inherited
Definition at line 88 of file parameter_accessor.h.
References libMesh::ParameterAccessor< T >::clone().
 { return ConstParameterProxy<T>(*this); }
template<typename T = Number> virtual ParameterAccessor<T>& libMesh::ParameterMultiPointer< T >::operator= (T *) inline virtual
A simple reseater won't work with a multipointer
Reimplemented from libMesh::ParameterAccessor< T >.
Definition at line 64 of file parameter_multipointer.h.
   {
     libmesh_error();
     return *this;
   }
template<typename T = Number> void libMesh::ParameterMultiPointer< T >::push_back (T * new_ptr) inline
Definition at line 116 of file parameter_multipointer.h.
References libMesh::ParameterMultiPointer< T >::_ptrs.
 { _ptrs.push_back(new_ptr); }
template<typename T = Number> virtual void libMesh::ParameterMultiPointer< T >::set (const T & new_value) inline virtual
Setter: change the value of the parameter we access.
Implements libMesh::ParameterAccessor< T >.
Definition at line 73 of file parameter_multipointer.h.
References libMesh::ParameterMultiPointer< T >::_ptrs, and libMesh::libmesh_assert().
   {
     libmesh_assert(!_ptrs.empty());
 #ifndef NDEBUG
     // Compare other values to the last one we'll change
     const T & val = *_ptrs.back();
 #endif
     for (std::size_t i=0; i != _ptrs.size(); ++i)
       {
         // If you're already using inconsistent parameters we can't
         // help you.
         libmesh_assert_equal_to(*_ptrs[i], val);
         *_ptrs[i] = new_value;
       }
   }
template<typename T = Number> std::size_t libMesh::ParameterMultiPointer< T >::size () const inline
Returns the number of data associated with this parameter. Useful for testing if the multipointer is empty/invalid.
Definition at line 122 of file parameter_multipointer.h.
References libMesh::ParameterMultiPointer< T >::_ptrs.
 { return _ptrs.size(); }
Member Data Documentation
template<typename T = Number> std::vector<T *> libMesh::ParameterMultiPointer< T >::_ptrs private
Definition at line 125 of file parameter_multipointer.h.
Referenced by libMesh::ParameterMultiPointer< T >::clone(), libMesh::ParameterMultiPointer< T >::get(), libMesh::ParameterMultiPointer< T >::push_back(), libMesh::ParameterMultiPointer< T >::set(), and libMesh::ParameterMultiPointer< T >::size().
The documentation for this class was generated from the following file:
parameter_multipointer.h