libMesh: libMesh::AnalyticFunction< Output > Class Template Reference
SomeWebsiteLogo
libMesh::AnalyticFunction< Output > Class Template Reference
#include <analytic_function.h>
Public Types
typedef Output(* OutputFunction) (const Point &p, const Real time)
typedef void(* OutputVectorFunction) (DenseVector< Output > &output, const Point &p, const Real time)
Public Member Functions
AnalyticFunction (OutputFunction fptr)
AnalyticFunction (OutputVectorFunction fptr)
~AnalyticFunction ()
virtual void init () libmesh_override
virtual void clear () libmesh_override
virtual std::unique_ptr< FunctionBase< Output > > clone () const libmesh_override
virtual Output operator() (const Point &p, const Real time=0.) libmesh_override
virtual void operator() (const Point &p, const Real time, DenseVector< Output > &output) libmesh_override
void operator() (const Point &p, DenseVector< Output > &output)
virtual Output component (unsigned int i, const Point &p, Real time=0.)
bool initialized () const
void set_is_time_dependent (bool is_time_dependent)
bool is_time_dependent () const
Public Attributes
OutputFunction _number_fptr
OutputVectorFunction _vector_fptr
Protected Attributes
const FunctionBase * _master
bool _initialized
bool _is_time_dependent
Detailed Description
template<typename Output = Number>
class libMesh::AnalyticFunction< Output >
This class provides function-like objects for which an analytical expression can be provided. The user may either provide vector-return or number-return functions. All overridden virtual functions are documented in function_base.h.
Author
Daniel Dreyer
Date
2003
Definition at line 46 of file analytic_function.h.
Member Typedef Documentation
template<typename Output = Number> typedef Output(* libMesh::AnalyticFunction< Output >::OutputFunction) (const Point &p, const Real time)
Constructor. Takes a function pointer for scalar return values.
Definition at line 54 of file analytic_function.h.
template<typename Output = Number> typedef void(* libMesh::AnalyticFunction< Output >::OutputVectorFunction) (DenseVector< Output > &output, const Point &p, const Real time)
Constructor. Takes a function pointer for vector valued functions.
Definition at line 61 of file analytic_function.h.
Constructor & Destructor Documentation
template<typename Output > libMesh::AnalyticFunction< Output >::AnalyticFunction (OutputFunction fptr)
Definition at line 127 of file analytic_function.h.
References libMesh::FunctionBase< Output >::_initialized.
                                                                :
   FunctionBase<Output> (),
   _number_fptr (fptr),
   _vector_fptr (libmesh_nullptr)
 {
   libmesh_assert(fptr);
   this->_initialized = true;
 }
template<typename Output > libMesh::AnalyticFunction< Output >::AnalyticFunction (OutputVectorFunction fptr) inline
Definition at line 140 of file analytic_function.h.
References libMesh::FunctionBase< Output >::_initialized.
                                                                      :
   FunctionBase<Output> (),
   _number_fptr (libmesh_nullptr),
   _vector_fptr (fptr)
 {
   libmesh_assert(fptr);
   this->_initialized = true;
 }
template<typename Output > libMesh::AnalyticFunction< Output >::~AnalyticFunction () inline
Destructor.
Definition at line 153 of file analytic_function.h.
 {
 }
Member Function Documentation
template<typename Output > void libMesh::AnalyticFunction< Output >::clear () inline virtual
Clears the function.
Reimplemented from libMesh::FunctionBase< Output >.
Definition at line 173 of file analytic_function.h.
References libMesh::FunctionBase< Output >::_initialized, and libmesh_nullptr.
 {
   // We probably need a method to reset these later...
   _number_fptr = libmesh_nullptr;
   _vector_fptr = libmesh_nullptr;
   // definitely not ready
   this->_initialized = false;
 }
template<typename Output > std::unique_ptr< FunctionBase< Output > > libMesh::AnalyticFunction< Output >::clone () const inline virtual
Returns
A new copy of the function.
The new copy should be as "deep" as necessary to allow independent destruction and simultaneous evaluations of the copies in different threads.
Implements libMesh::FunctionBase< Output >.
Definition at line 188 of file analytic_function.h.
References libMesh::AnalyticFunction< Output >::_number_fptr.
 {
   return std::unique_ptr<FunctionBase<Output>>
     ( _number_fptr ?
       new AnalyticFunction<Output>(_number_fptr) :
       new AnalyticFunction<Output>(_vector_fptr) );
 }
template<typename Output > Output libMesh::FunctionBase< Output >::component (unsigned int i, const Point & p, Real time = 0.) inline virtual inherited
Returns
The vector component i at coordinate p and time time.
Note
Subclasses aren't required to override this, since the default implementation is based on the full vector evaluation, which is often correct.
Subclasses are recommended to override this, since the default implementation is based on a vector evaluation, which is usually unnecessarily inefficient.
Reimplemented in libMesh::CompositeFunction< Output >, libMesh::ParsedFunction< Output, OutputGradient >, libMesh::ParsedFunction< T >, and libMesh::WrappedFunction< Output >.
Definition at line 231 of file function_base.h.
Referenced by libMesh::FunctionBase< Real >::clear().
 {
   DenseVector<Output> outvec(i+1);
   (*this)(p, time, outvec);
   return outvec(i);
 }
template<typename Output > void libMesh::AnalyticFunction< Output >::init () virtual
The actual initialization process.
Reimplemented from libMesh::FunctionBase< Output >.
Definition at line 160 of file analytic_function.h.
References libMesh::FunctionBase< Output >::_initialized, and libmesh_nullptr.
 {
   // dumb double-test
   libmesh_assert ((_number_fptr != libmesh_nullptr) || (_vector_fptr != libmesh_nullptr));
   // definitely ready
   this->_initialized = true;
 }
template<typename Output > bool libMesh::FunctionBase< Output >::initialized () const inline inherited
Returns
true when this object is properly initialized and ready for use, false otherwise.
Definition at line 209 of file function_base.h.
References libMesh::FunctionBase< Output >::_initialized.
Referenced by libMesh::FunctionBase< Real >::clear(), and libMesh::AnalyticFunction< Output >::operator()().
 {
   return (this->_initialized);
 }
template<typename Output > bool libMesh::FunctionBase< Output >::is_time_dependent () const inline inherited
Returns
true when the function this object represents is actually time-dependent, false otherwise.
Definition at line 223 of file function_base.h.
References libMesh::FunctionBase< Output >::_is_time_dependent.
Referenced by libMesh::CompositeFunction< Output >::attach_subfunction(), libMesh::FunctionBase< Real >::clear(), libMesh::ParsedFunction< Output, OutputGradient >::expression_is_time_dependent(), and libMesh::FunctionBase< Output >::set_is_time_dependent().
 {
   return (this->_is_time_dependent);
 }
template<typename Output > Output libMesh::AnalyticFunction< Output >::operator() (const Point & p, const Real time = 0.) inline virtual
Returns
The scalar function value at coordinate p and time time, which defaults to zero.
Pure virtual, so you have to override it.
Implements libMesh::FunctionBase< Output >.
Definition at line 104 of file analytic_function.h.
References libMesh::AnalyticFunction< Output >::_number_fptr, and libMesh::FunctionBase< Output >::initialized().
 {
   libmesh_assert (this->initialized());
   return (this->_number_fptr(p, time));
 }
template<typename Output > void libMesh::AnalyticFunction< Output >::operator() (const Point & p, const Real time, DenseVector< Output > & output) inline virtual
Evaluation function for time-dependent vector-valued functions. Sets output values in the passed-in output DenseVector.
Pure virtual, so you have to override it.
Implements libMesh::FunctionBase< Output >.
Definition at line 115 of file analytic_function.h.
References libMesh::AnalyticFunction< Output >::_vector_fptr, and libMesh::FunctionBase< Output >::initialized().
 {
   libmesh_assert (this->initialized());
   this->_vector_fptr(output, p, time);
   return;
 }
template<typename Output> void libMesh::FunctionBase< Output >::operator() (const Point & p, DenseVector< Output > & output) inline inherited
Evaluation function for time-independent vector-valued functions. Sets output values in the passed-in output DenseVector.
Definition at line 244 of file function_base.h.
References libMesh::FunctionBase< Output >::operator()().
 {
   // Call the time-dependent function with t=0.
   this->operator()(p, 0., output);
 }
template<typename Output > void libMesh::FunctionBase< Output >::set_is_time_dependent (bool is_time_dependent) inline inherited
Function to set whether this is a time-dependent function or not. This is intended to be only used by subclasses who cannot natively determine time-dependence. In such a case, this function should be used immediately following construction.
Definition at line 216 of file function_base.h.
References libMesh::FunctionBase< Output >::_is_time_dependent, and libMesh::FunctionBase< Output >::is_time_dependent().
Referenced by libMesh::FunctionBase< Real >::clear().
 {
   this->_is_time_dependent = is_time_dependent;
 }
Member Data Documentation
template<typename Output = Number> bool libMesh::FunctionBase< Output >::_initialized protected inherited
When init() was called so that everything is ready for calls to operator() (...), then this bool is true.
Definition at line 175 of file function_base.h.
Referenced by libMesh::AnalyticFunction< Output >::AnalyticFunction(), libMesh::AnalyticFunction< Output >::clear(), libMesh::ConstFunction< Output >::ConstFunction(), libMesh::AnalyticFunction< Output >::init(), libMesh::FunctionBase< Output >::initialized(), libMesh::ParsedFunction< Output, OutputGradient >::ParsedFunction(), and libMesh::WrappedFunction< Output >::WrappedFunction().
template<typename Output = Number> bool libMesh::FunctionBase< Output >::_is_time_dependent protected inherited
Cache whether or not this function is actually time-dependent.
Definition at line 180 of file function_base.h.
Referenced by libMesh::CompositeFunction< Output >::attach_subfunction(), libMesh::ConstFunction< Output >::ConstFunction(), libMesh::FunctionBase< Output >::is_time_dependent(), libMesh::ParsedFunction< Output, OutputGradient >::reparse(), and libMesh::FunctionBase< Output >::set_is_time_dependent().
template<typename Output = Number> const FunctionBase* libMesh::FunctionBase< Output >::_master protected inherited
Const pointer to our master, initialized to NULL. There may be cases where multiple functions are required, but to save memory, one master handles some centralized data.
Definition at line 169 of file function_base.h.
template<typename Output = Number> OutputFunction libMesh::AnalyticFunction< Output >::_number_fptr
Pointer to user-provided function that computes the boundary values when an analytical expression is available.
Definition at line 77 of file analytic_function.h.
Referenced by libMesh::AnalyticFunction< Output >::clone(), and libMesh::AnalyticFunction< Output >::operator()().
template<typename Output = Number> OutputVectorFunction libMesh::AnalyticFunction< Output >::_vector_fptr
Pointer to user-provided vector valued function.
Definition at line 82 of file analytic_function.h.
Referenced by libMesh::AnalyticFunction< Output >::operator()().
The documentation for this class was generated from the following file:
analytic_function.h