libMesh: libMesh::CompositeFunction< Output > Class Template Reference
SomeWebsiteLogo
libMesh::CompositeFunction< Output > Class Template Reference
A function that returns a vector whose components are defined by multiple functions.
#include <composite_function.h>
Public Member Functions
CompositeFunction ()=default
CompositeFunction (CompositeFunction &&)=default
CompositeFunction & operator= (CompositeFunction &&)=default
CompositeFunction (const CompositeFunction &)=delete
CompositeFunction & operator= (const CompositeFunction &)=delete
virtual ~CompositeFunction ()=default
void attach_subfunction (const FunctionBase< Output > &f, const std::vector< unsigned int > &index_map)
virtual Output operator() (const Point &p, const Real time=0) override
virtual void operator() (const Point &p, const Real time, DenseVector< Output > &output) override
virtual Output component (unsigned int i, const Point &p, Real time) override
virtual std::unique_ptr< FunctionBase< Output > > clone () const override
unsigned int n_subfunctions () const
unsigned int n_components () const
virtual void init ()
virtual void clear ()
void operator() (const Point &p, DenseVector< Output > &output)
bool initialized () const
void set_is_time_dependent (bool is_time_dependent)
bool is_time_dependent () const
Protected Attributes
const FunctionBase * _master
bool _initialized
bool _is_time_dependent
Private Attributes
std::vector< std::unique_ptr< FunctionBase< Output > > > subfunctions
std::vector< std::vector< unsigned int > > index_maps
std::vector< std::pair< unsigned int, unsigned int > > reverse_index_map
Detailed Description
template<typename Output = Number>
class libMesh::CompositeFunction< Output >
A function that returns a vector whose components are defined by multiple functions.
A function which is defined by composing the result of different functions into a single vector. All overridden virtual functions are documented in function_base.h.
Author
Roy Stogner
Date
2012 Function which is a function of another function.
Definition at line 48 of file composite_function.h.
Constructor & Destructor Documentation
CompositeFunction() [1/3]
template<typename Output = Number> libMesh::CompositeFunction< Output >::CompositeFunction () explicit default
Referenced by libMesh::CompositeFunction< Output >::clone().
CompositeFunction() [2/3]
template<typename Output = Number> libMesh::CompositeFunction< Output >::CompositeFunction (CompositeFunction< Output > &&) default
This class can be default move constructed and assigned.
CompositeFunction() [3/3]
template<typename Output = Number> libMesh::CompositeFunction< Output >::CompositeFunction (const CompositeFunction< Output > &) delete
This class contains unique_ptr members so it can't be default copied or assigned.
~CompositeFunction()
template<typename Output = Number> virtual libMesh::CompositeFunction< Output >::~CompositeFunction () virtual default
The subfunctions vector is automatically cleaned up.
Member Function Documentation
attach_subfunction()
template<typename Output = Number> void libMesh::CompositeFunction< Output >::attach_subfunction (const FunctionBase< Output > & f, const std::vector< unsigned int > & index_map) inline
Attach a new subfunction, along with a map from the indices of the attached subfunction to the indices of the composed function.
The composed function will return a vector whose value at index index_map[i] is the value of the attached function at index i, i.e., (*this)(x, t)(index_map[i]) will return f(x, t)(i).
Definition at line 81 of file composite_function.h.
References libMesh::FunctionBase< Output >::_is_time_dependent, libMesh::FunctionBase< Output >::clone(), libMesh::CompositeFunction< Output >::index_maps, libMesh::invalid_uint, libMesh::FunctionBase< Output >::is_time_dependent(), libMesh::CompositeFunction< Output >::reverse_index_map, and libMesh::CompositeFunction< Output >::subfunctions.
Referenced by libMesh::CompositeFunction< Output >::clone().
   {
     const unsigned int subfunction_index =
       cast_int<unsigned int>(subfunctions.size());
     libmesh_assert_equal_to(subfunctions.size(), index_maps.size());
     subfunctions.push_back(f.clone());
     index_maps.push_back(index_map);
     unsigned int max_index =
       *std::max_element(index_map.begin(), index_map.end());
     if (max_index >= reverse_index_map.size())
       reverse_index_map.resize
         (max_index+1, std::make_pair(libMesh::invalid_uint,
                                      libMesh::invalid_uint));
     for (std::size_t j=0; j != index_map.size(); ++j)
       {
         libmesh_assert_less(index_map[j], reverse_index_map.size());
         libmesh_assert_equal_to(reverse_index_map[index_map[j]].first,
                                 libMesh::invalid_uint);
         libmesh_assert_equal_to(reverse_index_map[index_map[j]].second,
                                 libMesh::invalid_uint);
         reverse_index_map[index_map[j]] =
           std::make_pair(subfunction_index, j);
       }
     // Now check for time dependence
     // We only check the function we just added instead of researching all subfunctions
     // If this is the first subfunction, then that determines the time-dependence.
     if (subfunctions.size() == 1)
       this->_is_time_dependent = subfunctions[0]->is_time_dependent();
     // Otherwise, we have more than 1 function already.
     // If _is_time_dependent is true, then one of the previous
     // subfunctions is time-dependent and thus this CompositeFunction
     // time-dependent. If _is_time_dependent is false, then the subfunction
     // just added determines the time-dependence.
     else if (!this->_is_time_dependent)
       this->_is_time_dependent = (subfunctions.back())->is_time_dependent();
   }
clear()
template<typename Output = Number> virtual void libMesh::FunctionBase< Output >::clear () inline virtual inherited
Clears the function.
Reimplemented in libMesh::ParsedFunction< Output, OutputGradient >, libMesh::ParsedFunction< T >, libMesh::MeshFunction, and libMesh::AnalyticFunction< Output >.
Definition at line 92 of file function_base.h.
 {}
clone()
template<typename Output = Number> virtual std::unique_ptr<FunctionBase<Output> > libMesh::CompositeFunction< Output >::clone () const inline override virtual
Returns
A new copy of the function.
The new copy should be as "deep" as necessary to allow independent destruction and simultaneous evaluations of the copies in different threads.
Implements libMesh::FunctionBase< Output >.
Definition at line 168 of file composite_function.h.
References libMesh::CompositeFunction< Output >::attach_subfunction(), libMesh::CompositeFunction< Output >::CompositeFunction(), libMesh::CompositeFunction< Output >::index_maps, and libMesh::CompositeFunction< Output >::subfunctions.
   {
     CompositeFunction * returnval = new CompositeFunction();
     for (std::size_t i=0; i != subfunctions.size(); ++i)
       returnval->attach_subfunction(*subfunctions[i], index_maps[i]);
     return std::unique_ptr<FunctionBase<Output>> (returnval);
   }
component()
template<typename Output = Number> virtual Output libMesh::CompositeFunction< Output >::component (unsigned int i, const Point & p, Real time) inline override virtual
Returns
The vector component i at coordinate p and time time.
Note
Subclasses aren't required to override this, since the default implementation is based on the full vector evaluation, which is often correct.
Subclasses are recommended to override this, since the default implementation is based on a vector evaluation, which is usually unnecessarily inefficient.
Reimplemented from libMesh::FunctionBase< Output >.
Definition at line 152 of file composite_function.h.
References libMesh::invalid_uint, libMesh::CompositeFunction< Output >::reverse_index_map, and libMesh::CompositeFunction< Output >::subfunctions.
Referenced by libMesh::CompositeFunction< Output >::operator()().
   {
     if (i >= reverse_index_map.size() ||
         reverse_index_map[i].first == libMesh::invalid_uint)
       return 0;
     libmesh_assert_less(reverse_index_map[i].first,
                         subfunctions.size());
     libmesh_assert_not_equal_to(reverse_index_map[i].second,
                                 libMesh::invalid_uint);
     return subfunctions[reverse_index_map[i].first]->
       component(reverse_index_map[i].second,p,time);
   }
init()
template<typename Output = Number> virtual void libMesh::FunctionBase< Output >::init () inline virtual inherited
The actual initialization process.
Reimplemented in libMesh::ParsedFunction< Output, OutputGradient >, libMesh::ParsedFunction< T >, libMesh::MeshFunction, and libMesh::AnalyticFunction< Output >.
Definition at line 87 of file function_base.h.
Referenced by libMesh::MeshFunction::clone().
 {}
initialized()
template<typename Output > bool libMesh::FunctionBase< Output >::initialized () const inline inherited
Returns
true when this object is properly initialized and ready for use, false otherwise.
Definition at line 206 of file function_base.h.
 {
   return (this->_initialized);
 }
is_time_dependent()
template<typename Output > bool libMesh::FunctionBase< Output >::is_time_dependent () const inline inherited
Returns
true when the function this object represents is actually time-dependent, false otherwise.
Definition at line 220 of file function_base.h.
Referenced by libMesh::CompositeFunction< Output >::attach_subfunction().
 {
   return (this->_is_time_dependent);
 }
n_components()
template<typename Output = Number> unsigned int libMesh::CompositeFunction< Output >::n_components () const inline
Definition at line 181 of file composite_function.h.
References libMesh::CompositeFunction< Output >::reverse_index_map.
   {
     return reverse_index_map.size();
   }
n_subfunctions()
template<typename Output = Number> unsigned int libMesh::CompositeFunction< Output >::n_subfunctions () const inline
Definition at line 176 of file composite_function.h.
References libMesh::CompositeFunction< Output >::subfunctions.
   {
     return subfunctions.size();
   }
operator()() [1/3]
template<typename Output> void libMesh::FunctionBase< Output >::operator() (const Point & p, DenseVector< Output > & output) inline inherited
Evaluation function for time-independent vector-valued functions. Sets output values in the passed-in output DenseVector.
Definition at line 241 of file function_base.h.
 {
   // Call the time-dependent function with t=0.
   this->operator()(p, 0., output);
 }
operator()() [2/3]
template<typename Output = Number> virtual Output libMesh::CompositeFunction< Output >::operator() (const Point & p, const Real time = 0) inline override virtual
Returns
The scalar function value at coordinate p and time time, which defaults to zero.
Pure virtual, so you have to override it.
Implements libMesh::FunctionBase< Output >.
Definition at line 125 of file composite_function.h.
References libMesh::CompositeFunction< Output >::component().
   {
     return this->component(0,p,time);
   }
operator()() [3/3]
template<typename Output = Number> virtual void libMesh::CompositeFunction< Output >::operator() (const Point & p, const Real time, DenseVector< Output > & output) inline override virtual
Evaluation function for time-dependent vector-valued functions. Sets output values in the passed-in output DenseVector.
Pure virtual, so you have to override it.
Implements libMesh::FunctionBase< Output >.
Definition at line 131 of file composite_function.h.
References libMesh::CompositeFunction< Output >::index_maps, libMesh::DenseVector< T >::resize(), libMesh::CompositeFunction< Output >::reverse_index_map, libMesh::DenseVector< T >::size(), libMesh::CompositeFunction< Output >::subfunctions, and libMesh::DenseVector< T >::zero().
   {
     libmesh_assert_greater_equal (output.size(),
                                   reverse_index_map.size());
     // Necessary in case we have output components not covered by
     // any subfunctions
     output.zero();
     DenseVector<Output> temp;
     for (std::size_t i=0; i != subfunctions.size(); ++i)
       {
         temp.resize(cast_int<unsigned int>(index_maps[i].size()));
         (*subfunctions[i])(p, time, temp);
         for (unsigned int j=0; j != temp.size(); ++j)
           output(index_maps[i][j]) = temp(j);
       }
   }
operator=() [1/2]
template<typename Output = Number> CompositeFunction& libMesh::CompositeFunction< Output >::operator= (CompositeFunction< Output > &&) default
operator=() [2/2]
template<typename Output = Number> CompositeFunction& libMesh::CompositeFunction< Output >::operator= (const CompositeFunction< Output > &) delete
set_is_time_dependent()
template<typename Output > void libMesh::FunctionBase< Output >::set_is_time_dependent (bool is_time_dependent) inline inherited
Function to set whether this is a time-dependent function or not. This is intended to be only used by subclasses who cannot natively determine time-dependence. In such a case, this function should be used immediately following construction.
Definition at line 213 of file function_base.h.
 {
   this->_is_time_dependent = is_time_dependent;
 }
Member Data Documentation
_initialized
template<typename Output = Number> bool libMesh::FunctionBase< Output >::_initialized protected inherited
When init() was called so that everything is ready for calls to operator() (...), then this bool is true.
Definition at line 180 of file function_base.h.
Referenced by libMesh::AnalyticFunction< Output >::AnalyticFunction(), libMesh::ConstFunction< Output >::ConstFunction(), and libMesh::WrappedFunction< Output >::WrappedFunction().
_is_time_dependent
template<typename Output = Number> bool libMesh::FunctionBase< Output >::_is_time_dependent protected inherited
Cache whether or not this function is actually time-dependent.
Definition at line 185 of file function_base.h.
Referenced by libMesh::CompositeFunction< Output >::attach_subfunction(), and libMesh::ConstFunction< Output >::ConstFunction().
_master
template<typename Output = Number> const FunctionBase* libMesh::FunctionBase< Output >::_master protected inherited
Const pointer to our master, initialized to nullptr. There may be cases where multiple functions are required, but to save memory, one master handles some centralized data.
Definition at line 174 of file function_base.h.
index_maps
template<typename Output = Number> std::vector<std::vector<unsigned int> > libMesh::CompositeFunction< Output >::index_maps private
Definition at line 191 of file composite_function.h.
Referenced by libMesh::CompositeFunction< Output >::attach_subfunction(), libMesh::CompositeFunction< Output >::clone(), and libMesh::CompositeFunction< Output >::operator()().
reverse_index_map
template<typename Output = Number> std::vector<std::pair<unsigned int, unsigned int> > libMesh::CompositeFunction< Output >::reverse_index_map private
Definition at line 194 of file composite_function.h.
Referenced by libMesh::CompositeFunction< Output >::attach_subfunction(), libMesh::CompositeFunction< Output >::component(), libMesh::CompositeFunction< Output >::n_components(), and libMesh::CompositeFunction< Output >::operator()().
subfunctions
template<typename Output = Number> std::vector<std::unique_ptr<FunctionBase<Output> > > libMesh::CompositeFunction< Output >::subfunctions private
Definition at line 188 of file composite_function.h.
Referenced by libMesh::CompositeFunction< Output >::attach_subfunction(), libMesh::CompositeFunction< Output >::clone(), libMesh::CompositeFunction< Output >::component(), libMesh::CompositeFunction< Output >::n_subfunctions(), and libMesh::CompositeFunction< Output >::operator()().
The documentation for this class was generated from the following file:
composite_function.h