libMesh: libMesh::UCDIO Class Reference
SomeWebsiteLogo
libMesh::UCDIO Class Reference
#include <ucd_io.h>
Public Member Functions
UCDIO (MeshBase &mesh)
UCDIO (const MeshBase &mesh)
virtual void read (const std::string &) override
virtual void write (const std::string &) override
virtual void write_nodal_data (const std::string &fname, const std::vector< Number > &soln, const std::vector< std::string > &names) override
virtual void write_equation_systems (const std::string &, const EquationSystems &, const std::set< std::string > *system_names=nullptr)
virtual void write_discontinuous_equation_systems (const std::string &, const EquationSystems &, const std::set< std::string > *system_names=nullptr)
virtual void write_nodal_data (const std::string &, const NumericVector< Number > &, const std::vector< std::string > &)
virtual void write_nodal_data_discontinuous (const std::string &, const std::vector< Number > &, const std::vector< std::string > &)
unsigned int & ascii_precision ()
Protected Member Functions
MeshBase & mesh ()
void set_n_partitions (unsigned int n_parts)
void skip_comment_lines (std::istream &in, const char comment_start)
const MeshBase & mesh () const
Protected Attributes
std::vector< bool > elems_of_dimension
const bool _is_parallel_format
const bool _serial_only_needed_on_proc_0
Private Member Functions
void read_implementation (std::istream &in_stream)
void write_implementation (std::ostream &out_stream)
void write_header (std::ostream &out, const MeshBase &mesh, dof_id_type n_elems, unsigned int n_vars)
void write_nodes (std::ostream &out, const MeshBase &mesh)
void write_interior_elems (std::ostream &out, const MeshBase &mesh)
void write_soln (std::ostream &out, const MeshBase &mesh, const std::vector< std::string > &names, const std::vector< Number > &soln)
Static Private Member Functions
static std::map< ElemType, std::string > build_writing_element_map ()
static std::map< std::string, ElemType > build_reading_element_map ()
Static Private Attributes
static std::map< ElemType, std::string > _writing_element_map = UCDIO::build_writing_element_map()
static std::map< std::string, ElemType > _reading_element_map = UCDIO::build_reading_element_map()
Detailed Description
This class implements reading & writing meshes in the AVS's UCD format.
Author
Benjamin S. Kirk
Date
2004
Definition at line 52 of file ucd_io.h.
Constructor & Destructor Documentation
UCDIO() [1/2]
libMesh::UCDIO::UCDIO (MeshBase & mesh) inline explicit
Constructor. Takes a writable reference to a mesh object. This is the constructor required to read a mesh.
Definition at line 62 of file ucd_io.h.
                           :
     MeshInput<MeshBase> (mesh),
     MeshOutput<MeshBase>(mesh)
   {}
UCDIO() [2/2]
libMesh::UCDIO::UCDIO (const MeshBase & mesh) inline explicit
Constructor. Takes a reference to a constant mesh object. This constructor will only allow us to write the mesh.
Definition at line 72 of file ucd_io.h.
                                 :
     MeshOutput<MeshBase> (mesh)
   {}
Member Function Documentation
ascii_precision()
unsigned int & libMesh::MeshOutput< MeshBase >::ascii_precision () inline inherited
Return/set the precision to use when writing ASCII files.
By default we use numeric_limits<Real>::digits10 + 2, which should be enough to write out to ASCII and get the exact same Real back when reading in.
Definition at line 244 of file mesh_output.h.
Referenced by libMesh::TecplotIO::write_ascii(), libMesh::GMVIO::write_ascii_new_impl(), and libMesh::GMVIO::write_ascii_old_impl().
 {
   return _ascii_precision;
 }
build_reading_element_map()
std::map< std::string, ElemType > libMesh::UCDIO::build_reading_element_map () static private
Definition at line 68 of file ucd_io.C.
References libMesh::EDGE2, libMesh::HEX8, libMesh::PRISM6, libMesh::PYRAMID5, libMesh::QUAD4, libMesh::TET4, and libMesh::TRI3.
 {
   std::map<std::string, ElemType> ret;
   ret["edge"]    = EDGE2;
   ret["tri"]     = TRI3;
   ret["quad"]    = QUAD4;
   ret["tet"]     = TET4;
   ret["hex"]     = HEX8;
   ret["prism"]   = PRISM6;
   ret["pyramid"] = PYRAMID5;
   return ret;
 }
build_writing_element_map()
std::map< ElemType, std::string > libMesh::UCDIO::build_writing_element_map () static private
Definition at line 52 of file ucd_io.C.
References libMesh::EDGE2, libMesh::HEX8, libMesh::PRISM6, libMesh::PYRAMID5, libMesh::QUAD4, libMesh::TET4, and libMesh::TRI3.
 {
   std::map<ElemType, std::string> ret;
   ret[EDGE2]    = "edge";
   ret[TRI3]     = "tri";
   ret[QUAD4]    = "quad";
   ret[TET4]     = "tet";
   ret[HEX8]     = "hex";
   ret[PRISM6]   = "prism";
   ret[PYRAMID5] = "pyramid";
   return ret;
 }
mesh() [1/2]
MeshBase & libMesh::MeshInput< MeshBase >::mesh () inline protected inherited
Returns
The object as a writable reference.
Definition at line 169 of file mesh_input.h.
Referenced by libMesh::GMVIO::_read_one_cell(), libMesh::VTKIO::cells_to_vtk(), libMesh::TetGenIO::element_in(), libMesh::UNVIO::elements_in(), libMesh::UNVIO::elements_out(), libMesh::UNVIO::groups_in(), libMesh::TetGenIO::node_in(), libMesh::UNVIO::nodes_in(), libMesh::UNVIO::nodes_out(), libMesh::VTKIO::nodes_to_vtk(), libMesh::Nemesis_IO::prepare_to_write_nodal_data(), libMesh::Nemesis_IO::read(), libMesh::ExodusII_IO::read(), libMesh::GMVIO::read(), libMesh::XdrIO::read(), libMesh::CheckpointIO::read(), libMesh::VTKIO::read(), libMesh::CheckpointIO::read_bcs(), libMesh::CheckpointIO::read_connectivity(), libMesh::CheckpointIO::read_header(), libMesh::XdrIO::read_header(), read_implementation(), libMesh::UNVIO::read_implementation(), libMesh::GmshIO::read_mesh(), libMesh::CheckpointIO::read_nodes(), libMesh::CheckpointIO::read_nodesets(), libMesh::CheckpointIO::read_remote_elem(), libMesh::XdrIO::read_serialized_bcs_helper(), libMesh::XdrIO::read_serialized_connectivity(), libMesh::XdrIO::read_serialized_nodes(), libMesh::XdrIO::read_serialized_nodesets(), libMesh::XdrIO::read_serialized_subdomain_names(), libMesh::OFFIO::read_stream(), libMesh::MatlabIO::read_stream(), libMesh::CheckpointIO::read_subdomain_names(), libMesh::TetGenIO::write(), libMesh::Nemesis_IO::write(), libMesh::ExodusII_IO::write(), libMesh::XdrIO::write(), libMesh::CheckpointIO::write(), libMesh::GMVIO::write_ascii_new_impl(), libMesh::GMVIO::write_ascii_old_impl(), libMesh::GMVIO::write_binary(), libMesh::GMVIO::write_discontinuous_gmv(), libMesh::Nemesis_IO::write_element_data(), libMesh::ExodusII_IO::write_element_data(), write_header(), write_implementation(), write_interior_elems(), libMesh::GmshIO::write_mesh(), libMesh::VTKIO::write_nodal_data(), write_nodal_data(), libMesh::ExodusII_IO::write_nodal_data(), libMesh::ExodusII_IO::write_nodal_data_common(), libMesh::ExodusII_IO::write_nodal_data_discontinuous(), write_nodes(), libMesh::CheckpointIO::write_nodesets(), libMesh::XdrIO::write_parallel(), libMesh::GmshIO::write_post(), libMesh::XdrIO::write_serialized_bcs_helper(), libMesh::XdrIO::write_serialized_connectivity(), libMesh::XdrIO::write_serialized_nodes(), libMesh::XdrIO::write_serialized_nodesets(), libMesh::XdrIO::write_serialized_subdomain_names(), write_soln(), and libMesh::CheckpointIO::write_subdomain_names().
 {
   if (_obj == nullptr)
     libmesh_error_msg("ERROR: _obj should not be nullptr!");
   return *_obj;
 }
mesh() [2/2]
const MeshBase & libMesh::MeshOutput< MeshBase >::mesh () const inline protected inherited
Returns
The object as a read-only reference.
Definition at line 234 of file mesh_output.h.
Referenced by libMesh::FroIO::write(), libMesh::TecplotIO::write(), libMesh::MEDITIO::write(), libMesh::PostscriptIO::write(), libMesh::EnsightIO::write(), libMesh::TecplotIO::write_ascii(), libMesh::TecplotIO::write_binary(), libMesh::TecplotIO::write_nodal_data(), libMesh::MEDITIO::write_nodal_data(), and libMesh::GnuPlotIO::write_solution().
 {
   libmesh_assert(_obj);
   return *_obj;
 }
read()
void libMesh::UCDIO::read (const std::string & file_name) override virtual
This method implements reading a mesh from a specified file in UCD format.
Implements libMesh::MeshInput< MeshBase >.
Definition at line 82 of file ucd_io.C.
References read_implementation().
Referenced by libMesh::NameBasedIO::read().
 {
   if (file_name.rfind(".gz") < file_name.size())
     {
 #ifdef LIBMESH_HAVE_GZSTREAM
       igzstream in_stream (file_name.c_str());
       this->read_implementation (in_stream);
 #else
       libmesh_error_msg("ERROR:  You must have the zlib.h header files and libraries to read and write compressed streams.");
 #endif
     }
   else
     {
       std::ifstream in_stream (file_name.c_str());
       this->read_implementation (in_stream);
     }
 }
read_implementation()
void libMesh::UCDIO::read_implementation (std::istream & in_stream) private
The actual implementation of the read function. The public read interface simply decides which type of stream to pass the implementation.
Definition at line 124 of file ucd_io.C.
References _reading_element_map, libMesh::MeshBase::add_elem(), libMesh::MeshBase::add_point(), libMesh::Elem::build(), libMesh::Elem::dim(), libMesh::MeshInput< MeshBase >::elems_of_dimension, libMesh::MeshInput< MT >::mesh(), libMesh::MeshInput< MeshBase >::mesh(), libMesh::MeshBase::mesh_dimension(), libMesh::MeshBase::n_nodes(), libMesh::Elem::n_nodes(), libMesh::MeshBase::node_ptr(), libMesh::DofObject::set_id(), libMesh::MeshBase::set_mesh_dimension(), libMesh::Elem::set_node(), libMesh::MeshInput< MeshBase >::skip_comment_lines(), and libMesh::Elem::subdomain_id().
Referenced by read().
 {
   // This is a serial-only process for now;
   // the Mesh should be read on processor 0 and
   // broadcast later
   libmesh_assert_equal_to (MeshOutput<MeshBase>::mesh().processor_id(), 0);
   // Check input buffer
   libmesh_assert (in.good());
   MeshBase & mesh = MeshInput<MeshBase>::mesh();
   // Keep track of what kinds of elements this file contains
   elems_of_dimension.clear();
   elems_of_dimension.resize(4, false);
   this->skip_comment_lines (in, '#');
   unsigned int nNodes=0, nElem=0, dummy=0;
   in >> nNodes   // Read the number of nodes from the stream
      >> nElem    // Read the number of elements from the stream
      >> dummy
      >> dummy
      >> dummy;
   // Read the nodal coordinates. Note that UCD format always
   // stores (x,y,z), and in 2D z=0. We don't need to store this,
   // however.  So, we read in x,y,z for each node and make a point
   // in the proper way based on what dimension we're in
   {
     Point xyz;
     for (unsigned int i=0; i<nNodes; i++)
       {
         libmesh_assert (in.good());
         in >> dummy   // Point number
            >> xyz(0)  // x-coordinate value
            >> xyz(1)  // y-coordinate value
            >> xyz(2); // z-coordinate value
         // Build the node
         mesh.add_point (xyz, i);
       }
   }
   // Read the elements from the stream. Notice that the UCD node-numbering
   // scheme is 1-based, and we just created a 0-based scheme above
   // (which is of course what we want). So, when we read in the nodal
   // connectivity for each element we need to take 1 off the value of
   // each node so that we get the right thing.
   {
     unsigned int material_id=0, node=0;
     std::string type;
     for (unsigned int i=0; i<nElem; i++)
       {
         libmesh_assert (in.good());
         // The cell type can be either tri, quad, tet, hex, or prism.
         in >> dummy        // Cell number, means nothing to us
            >> material_id  // We'll use this for the element subdomain id.
            >> type;        // string describing cell type
         // Convert the UCD type string to a libmesh ElementType
         auto it = _reading_element_map.find(type);
         if (it == _reading_element_map.end())
           libmesh_error_msg("Unsupported element type = " << type);
         // Build the required type and release it into our custody.
         Elem * elem = Elem::build(it->second).release();
         for (unsigned int n=0; n<elem->n_nodes(); n++)
           {
             libmesh_assert (in.good());
             in >> node; // read the current node
             node -= 1;  // UCD is 1-based, so subtract
             libmesh_assert_less (node, mesh.n_nodes());
             // assign the node
             elem->set_node(n) = mesh.node_ptr(node);
           }
         elems_of_dimension[elem->dim()] = true;
         // Set the element's subdomain ID based on the material_id.
         elem->subdomain_id() = cast_int<subdomain_id_type>(material_id);
         // Add the element to the mesh
         elem->set_id(i);
         mesh.add_elem (elem);
       }
     // Set the mesh dimension to the largest encountered for an element
     for (unsigned char i=0; i!=4; ++i)
       if (elems_of_dimension[i])
         mesh.set_mesh_dimension(i);
 #if LIBMESH_DIM < 3
     if (mesh.mesh_dimension() > LIBMESH_DIM)
       libmesh_error_msg("Cannot open dimension " \
                         << mesh.mesh_dimension() \
                         << " mesh file when configured without " \
                         << mesh.mesh_dimension() \
                         << "D support.");
 #endif
   }
 }
set_n_partitions()
void libMesh::MeshInput< MeshBase >::set_n_partitions (unsigned int n_parts) inline protected inherited
Sets the number of partitions in the mesh. Typically this gets done by the partitioner, but some parallel file formats begin "pre-partitioned".
Definition at line 91 of file mesh_input.h.
References libMesh::MeshInput< MT >::mesh().
Referenced by libMesh::Nemesis_IO::read(), and libMesh::XdrIO::read_header().
 { this->mesh().set_n_partitions() = n_parts; }
skip_comment_lines()
void libMesh::MeshInput< MeshBase >::skip_comment_lines (std::istream & in, const char comment_start) protected inherited
Reads input from in, skipping all the lines that start with the character comment_start.
Definition at line 179 of file mesh_input.h.
Referenced by libMesh::TetGenIO::read(), and read_implementation().
 {
   char c, line[256];
   while (in.get(c), c==comment_start)
     in.getline (line, 255);
   // put back first character of
   // first non-comment line
   in.putback (c);
 }
write()
void libMesh::UCDIO::write (const std::string & file_name) override virtual
This method implements writing a mesh to a specified file in UCD format.
Implements libMesh::MeshOutput< MeshBase >.
Definition at line 103 of file ucd_io.C.
References write_implementation().
Referenced by libMesh::NameBasedIO::write().
 {
   if (file_name.rfind(".gz") < file_name.size())
     {
 #ifdef LIBMESH_HAVE_GZSTREAM
       ogzstream out_stream (file_name.c_str());
       this->write_implementation (out_stream);
 #else
       libmesh_error_msg("ERROR:  You must have the zlib.h header files and libraries to read and write compressed streams.");
 #endif
     }
   else
     {
       std::ofstream out_stream (file_name.c_str());
       this->write_implementation (out_stream);
     }
 }
write_discontinuous_equation_systems()
void libMesh::MeshOutput< MeshBase >::write_discontinuous_equation_systems (const std::string & fname, const EquationSystems & es, const std::set< std::string > * system_names = nullptr) virtual inherited
This method implements writing a mesh with discontinuous data to a specified file where the data is taken from the EquationSystems object.
Definition at line 92 of file mesh_output.C.
References libMesh::EquationSystems::build_discontinuous_solution_vector(), libMesh::EquationSystems::build_variable_names(), libMesh::EquationSystems::get_mesh(), and libMesh::out.
Referenced by libMesh::ExodusII_IO::write_timestep_discontinuous().
 {
   LOG_SCOPE("write_discontinuous_equation_systems()", "MeshOutput");
   // We may need to gather and/or renumber a DistributedMesh to output
   // it, making that const qualifier in our constructor a dirty lie
   MT & my_mesh = const_cast<MT &>(*_obj);
   // If we're asked to write data that's associated with a different
   // mesh, output files full of garbage are the result.
   libmesh_assert_equal_to(&es.get_mesh(), _obj);
   // A non-renumbered mesh may not have a contiguous numbering, and
   // that needs to be fixed before we can build a solution vector.
   if (my_mesh.max_elem_id() != my_mesh.n_elem() ||
       my_mesh.max_node_id() != my_mesh.n_nodes())
     {
       // If we were allowed to renumber then we should have already
       // been properly renumbered...
       libmesh_assert(!my_mesh.allow_renumbering());
       libmesh_do_once(libMesh::out <<
                       "Warning:  This MeshOutput subclass only supports meshes which are contiguously renumbered!"
                       << std::endl;);
       my_mesh.allow_renumbering(true);
       my_mesh.renumber_nodes_and_elements();
       // Not sure what good going back to false will do here, the
       // renumbering horses have already left the barn...
       my_mesh.allow_renumbering(false);
     }
   MeshSerializer serialize(const_cast<MT &>(*_obj), !_is_parallel_format, _serial_only_needed_on_proc_0);
   // Build the list of variable names that will be written.
   std::vector<std::string> names;
   es.build_variable_names  (names, nullptr, system_names);
   if (!_is_parallel_format)
     {
       // Build the nodal solution values & get the variable
       // names from the EquationSystems object
       std::vector<Number> soln;
       es.build_discontinuous_solution_vector (soln, system_names);
       this->write_nodal_data_discontinuous (fname, soln, names);
     }
   else // _is_parallel_format
     {
       libmesh_not_implemented();
     }
 }
write_equation_systems()
void libMesh::MeshOutput< MeshBase >::write_equation_systems (const std::string & fname, const EquationSystems & es, const std::set< std::string > * system_names = nullptr) virtual inherited
This method implements writing a mesh with data to a specified file where the data is taken from the EquationSystems object.
Reimplemented in libMesh::NameBasedIO.
Definition at line 31 of file mesh_output.C.
References libMesh::EquationSystems::build_parallel_solution_vector(), libMesh::EquationSystems::build_solution_vector(), libMesh::EquationSystems::build_variable_names(), libMesh::EquationSystems::get_mesh(), and libMesh::out.
Referenced by libMesh::Nemesis_IO::write_timestep(), and libMesh::ExodusII_IO::write_timestep().
 {
   LOG_SCOPE("write_equation_systems()", "MeshOutput");
   // We may need to gather and/or renumber a DistributedMesh to output
   // it, making that const qualifier in our constructor a dirty lie
   MT & my_mesh = const_cast<MT &>(*_obj);
   // If we're asked to write data that's associated with a different
   // mesh, output files full of garbage are the result.
   libmesh_assert_equal_to(&es.get_mesh(), _obj);
   // A non-renumbered mesh may not have a contiguous numbering, and
   // that needs to be fixed before we can build a solution vector.
   if (my_mesh.max_elem_id() != my_mesh.n_elem() ||
       my_mesh.max_node_id() != my_mesh.n_nodes())
     {
       // If we were allowed to renumber then we should have already
       // been properly renumbered...
       libmesh_assert(!my_mesh.allow_renumbering());
       libmesh_do_once(libMesh::out <<
                       "Warning:  This MeshOutput subclass only supports meshes which are contiguously renumbered!"
                       << std::endl;);
       my_mesh.allow_renumbering(true);
       my_mesh.renumber_nodes_and_elements();
       // Not sure what good going back to false will do here, the
       // renumbering horses have already left the barn...
       my_mesh.allow_renumbering(false);
     }
   MeshSerializer serialize(const_cast<MT &>(*_obj), !_is_parallel_format, _serial_only_needed_on_proc_0);
   // Build the list of variable names that will be written.
   std::vector<std::string> names;
   es.build_variable_names  (names, nullptr, system_names);
   if (!_is_parallel_format)
     {
       // Build the nodal solution values & get the variable
       // names from the EquationSystems object
       std::vector<Number> soln;
       es.build_solution_vector (soln, system_names);
       this->write_nodal_data (fname, soln, names);
     }
   else // _is_parallel_format
     {
       std::unique_ptr<NumericVector<Number>> parallel_soln =
         es.build_parallel_solution_vector(system_names);
       this->write_nodal_data (fname, *parallel_soln, names);
     }
 }
write_header()
void libMesh::UCDIO::write_header (std::ostream & out, const MeshBase & mesh, dof_id_type n_elems, unsigned int n_vars) private
Write UCD format header
Definition at line 262 of file ucd_io.C.
References libMesh::MeshInput< MeshBase >::mesh(), libMesh::MeshBase::n_nodes(), and n_vars.
Referenced by write_implementation(), and write_nodal_data().
 {
   libmesh_assert (out_stream.good());
   // TODO: We could print out the libmesh revision used to write this file here.
   out_stream << "# For a description of the UCD format see the AVS Developer's guide.\n"
              << "#\n";
   // Write the mesh info
   out_stream << mesh.n_nodes() << " "
              << n_elems  << " "
              << n_vars << " "
              << " 0 0\n";
 }
write_implementation()
void libMesh::UCDIO::write_implementation (std::ostream & out_stream) private
The actual implementation of the write function. The public write interface simply decides which type of stream to pass the implementation.
Definition at line 239 of file ucd_io.C.
References libMesh::MeshInput< MeshBase >::mesh(), libMesh::MeshOutput< MT >::mesh(), libMesh::MeshBase::mesh_dimension(), libMesh::MeshBase::n_elem(), write_header(), write_interior_elems(), and write_nodes().
Referenced by write().
 {
   libmesh_assert (out_stream.good());
   const MeshBase & mesh = MeshOutput<MeshBase>::mesh();
   // UCD doesn't work any dimension except 3?
   if (mesh.mesh_dimension() != 3)
     libmesh_error_msg("Error: Can't write boundary elements for meshes of dimension less than 3. " \
                       << "Mesh dimension = " << mesh.mesh_dimension());
   // Write header
   this->write_header(out_stream, mesh, mesh.n_elem(), 0);
   // Write the node coordinates
   this->write_nodes(out_stream, mesh);
   // Write the elements
   this->write_interior_elems(out_stream, mesh);
 }
write_interior_elems()
void libMesh::UCDIO::write_interior_elems (std::ostream & out, const MeshBase & mesh) private
Write element information
Definition at line 299 of file ucd_io.C.
References _writing_element_map, libMesh::MeshBase::element_ptr_range(), libMesh::MeshInput< MeshBase >::mesh(), and libMesh::UCD.
Referenced by write_implementation(), and write_nodal_data().
 {
   // 1-based element number for UCD
   unsigned int e=1;
   // Write element information
   for (const auto & elem : mesh.element_ptr_range())
     {
       libmesh_assert (out_stream.good());
       // Look up the corresponding UCD element type in the static map.
       const ElemType etype = elem->type();
       auto it = _writing_element_map.find(etype);
       if (it == _writing_element_map.end())
         libmesh_error_msg("Error: Unsupported ElemType " << etype << " for UCDIO.");
       // Write the element's subdomain ID as the UCD "material_id".
       out_stream << e++ << " " << elem->subdomain_id() << " " << it->second << "\t";
       elem->write_connectivity(out_stream, UCD);
     }
 }
write_nodal_data() [1/2]
void libMesh::UCDIO::write_nodal_data (const std::string & fname, const std::vector< Number > & soln, const std::vector< std::string > & names) override virtual
This method implements writing a mesh and solution to a specified file in UCD format. This is internally called by MeshOutput::write_equation_systems
Reimplemented from libMesh::MeshOutput< MeshBase >.
Definition at line 324 of file ucd_io.C.
References libMesh::MeshInput< MeshBase >::mesh(), libMesh::MeshOutput< MT >::mesh(), libMesh::MeshBase::mesh_dimension(), libMesh::MeshBase::n_elem(), libMesh::MeshTools::n_elem(), libMesh::ParallelObject::processor_id(), write_header(), write_interior_elems(), write_nodes(), and write_soln().
Referenced by libMesh::NameBasedIO::write_nodal_data().
 {
   const MeshBase & mesh = MeshOutput<MeshBase>::mesh();
   const dof_id_type n_elem = mesh.n_elem();
   // Only processor 0 does the writing
   if (mesh.processor_id())
     return;
   std::ofstream out_stream(fname.c_str());
   // UCD doesn't work in 1D
   libmesh_assert (mesh.mesh_dimension() != 1);
   // Write header
   this->write_header(out_stream,mesh,n_elem,
                      cast_int<unsigned int>(names.size()));
   // Write the node coordinates
   this->write_nodes(out_stream, mesh);
   // Write the elements
   this->write_interior_elems(out_stream, mesh);
   // Write the solution
   this->write_soln(out_stream, mesh, names, soln);
 }
write_nodal_data() [2/2]
void libMesh::MeshOutput< MeshBase >::write_nodal_data (const std::string & fname, const NumericVector< Number > & parallel_soln, const std::vector< std::string > & names) virtual inherited
This method should be overridden by "parallel" output formats for writing nodal data. Instead of getting a localized copy of the nodal solution vector, it is passed a NumericVector of type=PARALLEL which is in node-major order i.e. (u0,v0,w0, u1,v1,w1, u2,v2,w2, u3,v3,w3, ...) and contains n_nodes*n_vars total entries. Then, it is up to the individual I/O class to extract the required solution values from this vector and write them in parallel.
If not implemented, localizes the parallel vector into a std::vector and calls the other version of this function.
Reimplemented in libMesh::Nemesis_IO.
Definition at line 150 of file mesh_output.C.
References libMesh::NumericVector< T >::localize().
 {
   // This is the fallback implementation for parallel I/O formats that
   // do not yet implement proper writing in parallel, and instead rely
   // on the full solution vector being available on all processors.
   std::vector<Number> soln;
   parallel_soln.localize(soln);
   this->write_nodal_data(fname, soln, names);
 }
write_nodal_data_discontinuous()
virtual void libMesh::MeshOutput< MeshBase >::write_nodal_data_discontinuous (const std::string & , const std::vector< Number > & , const std::vector< std::string > &) inline virtual inherited
This method implements writing a mesh with discontinuous data to a specified file where the nodal data and variables names are provided.
Reimplemented in libMesh::ExodusII_IO.
Definition at line 114 of file mesh_output.h.
   { libmesh_not_implemented(); }
write_nodes()
void libMesh::UCDIO::write_nodes (std::ostream & out, const MeshBase & mesh) private
Write node information
Definition at line 281 of file ucd_io.C.
References libMesh::MeshInput< MeshBase >::mesh(), and libMesh::MeshBase::node_ptr_range().
Referenced by write_implementation(), and write_nodal_data().
 {
   // 1-based node number for UCD
   unsigned int n=1;
   // Write the node coordinates
   for (auto & node : mesh.node_ptr_range())
     {
       libmesh_assert (out_stream.good());
       out_stream << n++ << "\t";
       node->write_unformatted(out_stream);
     }
 }
write_soln()
void libMesh::UCDIO::write_soln (std::ostream & out, const MeshBase & mesh, const std::vector< std::string > & names, const std::vector< Number > & soln) private
Writes all nodal solution variables
Definition at line 357 of file ucd_io.C.
References libMesh::MeshTools::Generation::Private::idx(), libMesh::MeshInput< MeshBase >::mesh(), libMesh::MeshBase::n_nodes(), and libMesh::Quality::name().
Referenced by write_nodal_data().
 {
   libmesh_assert (out_stream.good());
   // First write out how many variables and how many components per variable
   out_stream << names.size();
   for (std::size_t i = 0; i < names.size(); i++)
     {
       libmesh_assert (out_stream.good());
       // Each named variable has only 1 component
       out_stream << " 1";
     }
   out_stream << std::endl;
   // Now write out variable names and units. Since we don't store units
   // We just write out dummy.
   for (const auto & name : names)
     {
       libmesh_assert (out_stream.good());
       out_stream << name << ", dummy" << std::endl;
     }
   // Now, for each node, write out the solution variables.
   // We use a 1-based node numbering for UCD.
   std::size_t nv = names.size();
   for (std::size_t n = 1; n <= mesh.n_nodes(); n++)
     {
       libmesh_assert (out_stream.good());
       out_stream << n;
       for (std::size_t var = 0; var != nv; var++)
         {
           std::size_t idx = nv*(n-1) + var;
           out_stream << " " << soln[idx];
         }
       out_stream << std::endl;
     }
 }
Member Data Documentation
_is_parallel_format
const bool libMesh::MeshOutput< MeshBase >::_is_parallel_format protected inherited
Flag specifying whether this format is parallel-capable. If this is false (default) I/O is only permitted when the mesh has been serialized.
Definition at line 159 of file mesh_output.h.
Referenced by libMesh::FroIO::write(), libMesh::PostscriptIO::write(), and libMesh::EnsightIO::write().
_reading_element_map
std::map< std::string, ElemType > libMesh::UCDIO::_reading_element_map = UCDIO::build_reading_element_map() static private
Definition at line 153 of file ucd_io.h.
Referenced by read_implementation().
_serial_only_needed_on_proc_0
const bool libMesh::MeshOutput< MeshBase >::_serial_only_needed_on_proc_0 protected inherited
Flag specifying whether this format can be written by only serializing the mesh to processor zero
If this is false (default) the mesh will be serialized to all processors
Definition at line 168 of file mesh_output.h.
_writing_element_map
std::map< ElemType, std::string > libMesh::UCDIO::_writing_element_map = UCDIO::build_writing_element_map() static private
Definition at line 149 of file ucd_io.h.
Referenced by write_interior_elems().
elems_of_dimension
std::vector<bool> libMesh::MeshInput< MeshBase >::elems_of_dimension protected inherited
A vector of bools describing what dimension elements have been encountered when reading a mesh.
Definition at line 97 of file mesh_input.h.
Referenced by libMesh::GMVIO::_read_one_cell(), libMesh::UNVIO::elements_in(), libMesh::UNVIO::max_elem_dimension_seen(), libMesh::AbaqusIO::max_elem_dimension_seen(), libMesh::AbaqusIO::read(), libMesh::Nemesis_IO::read(), libMesh::ExodusII_IO::read(), libMesh::GMVIO::read(), libMesh::VTKIO::read(), libMesh::AbaqusIO::read_elements(), read_implementation(), libMesh::UNVIO::read_implementation(), and libMesh::XdrIO::read_serialized_connectivity().
The documentation for this class was generated from the following files:
ucd_io.h
ucd_io.C