libMesh: libMesh::Parallel::StandardType< Point > Class Template Reference
SomeWebsiteLogo
libMesh::Parallel::StandardType< Point > Class Template Reference
#include <parallel_algebra.h>
Public Member Functions
StandardType (const Point *example=nullptr)
StandardType (const StandardType< Point > &libmesh_mpi_var(t))
~StandardType ()
operator const data_type & () const
operator data_type & ()
void commit ()
void free ()
Protected Attributes
data_type _datatype
Detailed Description
template<>
class libMesh::Parallel::StandardType< Point >
Definition at line 176 of file parallel_algebra.h.
Constructor & Destructor Documentation
StandardType() [1/2]
libMesh::Parallel::StandardType< Point >::StandardType (const Point * example = nullptr) inline explicit
Definition at line 180 of file parallel_algebra.h.
References libMesh::Parallel::DataType::_datatype, and libMesh::libmesh_ignore().
   {
     // Prevent unused variable warnings when !LIBMESH_HAVE_MPI
     libmesh_ignore(example);
 #ifdef LIBMESH_HAVE_MPI
     // We need an example for MPI_Address to use
     Point * ex;
     std::unique_ptr<Point> temp;
     if (example)
       ex = const_cast<Point *>(example);
     else
       {
         temp.reset(new Point());
         ex = temp.get();
       }
     StandardType<Real> T_type(&((*ex)(0)));
     int blocklength = LIBMESH_DIM;
     MPI_Aint displs, start;
     MPI_Datatype tmptype, type = T_type;
     libmesh_call_mpi
       (MPI_Get_address (ex, &start));
     libmesh_call_mpi
       (MPI_Get_address (&((*ex)(0)), &displs));
     // subtract off offset to first value from the beginning of the structure
     displs -= start;
     // create a prototype structure
     libmesh_call_mpi
       (MPI_Type_create_struct (1, &blocklength, &displs, &type,
                                &tmptype));
     libmesh_call_mpi
       (MPI_Type_commit (&tmptype));
     // resize the structure type to account for padding, if any
     libmesh_call_mpi
       (MPI_Type_create_resized (tmptype, 0, sizeof(Point),
                                 &_datatype));
     libmesh_call_mpi
       (MPI_Type_commit (&_datatype));
     libmesh_call_mpi
       (MPI_Type_free (&tmptype));
 #endif // #ifdef LIBMESH_HAVE_MPI
   }
StandardType() [2/2]
libMesh::Parallel::StandardType< Point >::StandardType (const StandardType< Point > & libmesh_mpi_vart) inline
Definition at line 233 of file parallel_algebra.h.
References libMesh::Parallel::DataType::_datatype.
     : DataType()
   {
     libmesh_call_mpi (MPI_Type_dup (t._datatype, &_datatype));
   }
~StandardType()
libMesh::Parallel::StandardType< Point >::~StandardType () inline
Definition at line 239 of file parallel_algebra.h.
References libMesh::Parallel::DataType::free().
 { this->free(); }
Member Function Documentation
commit()
void libMesh::Parallel::DataType::commit () inline inherited
Definition at line 103 of file data_type.h.
References libMesh::Parallel::DataType::_datatype.
Referenced by libMesh::Parallel::DataType::DataType(), libMesh::Parallel::StandardType< std::pair< T1, T2 > >::StandardType(), and libMesh::Parallel::StandardType< std::tuple< Types... > >::StandardType().
   {
     libmesh_call_mpi
       (MPI_Type_commit (&_datatype));
   }
free()
void libMesh::Parallel::DataType::free () inline inherited
Definition at line 109 of file data_type.h.
References libMesh::Parallel::DataType::_datatype.
Referenced by libMesh::Parallel::StandardType< Hilbert::HilbertIndices >::~StandardType(), libMesh::Parallel::StandardType< TypeVector< T > >::~StandardType(), libMesh::Parallel::StandardType< VectorValue< T > >::~StandardType(), libMesh::Parallel::StandardType< std::pair< T1, T2 > >::~StandardType(), ~StandardType(), libMesh::Parallel::StandardType< std::tuple< Types... > >::~StandardType(), libMesh::Parallel::StandardType< std::complex< T > >::~StandardType(), libMesh::Parallel::StandardType< TypeTensor< T > >::~StandardType(), and libMesh::Parallel::StandardType< TensorValue< T > >::~StandardType().
   {
     libmesh_call_mpi
       (MPI_Type_free (&_datatype));
   }
operator const data_type &()
libMesh::Parallel::DataType::operator const data_type & () const inline inherited
Definition at line 91 of file data_type.h.
References libMesh::Parallel::DataType::_datatype.
   { return _datatype; }
operator data_type &()
libMesh::Parallel::DataType::operator data_type & () inline inherited
Definition at line 94 of file data_type.h.
References libMesh::Parallel::DataType::_datatype.
   { return _datatype; }
Member Data Documentation
_datatype
data_type libMesh::Parallel::DataType::_datatype protected inherited
Definition at line 117 of file data_type.h.
Referenced by libMesh::Parallel::DataType::commit(), libMesh::Parallel::DataType::DataType(), libMesh::Parallel::DataType::free(), libMesh::Parallel::DataType::operator const data_type &(), libMesh::Parallel::DataType::operator data_type &(), libMesh::Parallel::DataType::operator=(), libMesh::Parallel::StandardType< TypeVector< T > >::StandardType(), libMesh::Parallel::StandardType< Hilbert::HilbertIndices >::StandardType(), libMesh::Parallel::StandardType< VectorValue< T > >::StandardType(), libMesh::Parallel::StandardType< std::pair< T1, T2 > >::StandardType(), StandardType(), and libMesh::Parallel::StandardType< std::tuple< Types... > >::StandardType().
The documentation for this class was generated from the following file:
parallel_algebra.h