libMesh: libMesh::safe_bool< T > Class Template Reference
SomeWebsiteLogo
libMesh::safe_bool< T > Class Template Reference
#include <safe_bool.h>
Public Member Functions
operator bool_type () const
Protected Member Functions
~safe_bool ()
Private Types
typedef void(safe_bool_base::* bool_type) () const
Private Member Functions
void this_type_does_not_support_comparisons () const
Detailed Description
template<typename T>
class libMesh::safe_bool< T >
Definition at line 60 of file safe_bool.h.
Member Typedef Documentation
typedef void(safe_bool_base::* libMesh::safe_bool_base::bool_type) () const inherited
Definition at line 47 of file safe_bool.h.
Constructor & Destructor Documentation
template<typename T> libMesh::safe_bool< T >::~safe_bool () inline protected
Definition at line 71 of file safe_bool.h.
 {}
Member Function Documentation
template<typename T> libMesh::safe_bool< T >::operator bool_type () const inline
Definition at line 65 of file safe_bool.h.
   {
     return (static_cast<const T*>(this))->boolean_test()
       ? &safe_bool_base::this_type_does_not_support_comparisons : 0;
   }
void libMesh::safe_bool_base::this_type_does_not_support_comparisons () const inline inherited
Definition at line 48 of file safe_bool.h.
Referenced by libMesh::safe_bool< AutoPtr< Tp > >::operator bool_type(), libMesh::operator!=(), and libMesh::operator==().
 {}
The documentation for this class was generated from the following file:
safe_bool.h