libMesh: libMesh::PetscMatrix< T > Class Template Reference
SomeWebsiteLogo
libMesh::PetscMatrix< T > Class Template Reference
SparseMatrix interface to PETSc Mat.
#include <petsc_linear_solver.h>
Public Member Functions
PetscMatrix (const Parallel::Communicator &comm_in)
PetscMatrix (Mat m, const Parallel::Communicator &comm_in)
PetscMatrix (PetscMatrix &&)=delete
PetscMatrix (const PetscMatrix &)=delete
PetscMatrix & operator= (const PetscMatrix &)=delete
PetscMatrix & operator= (PetscMatrix &&)=delete
virtual ~PetscMatrix ()
void set_matrix_type (PetscMatrixType mat_type)
virtual void init (const numeric_index_type m, const numeric_index_type n, const numeric_index_type m_l, const numeric_index_type n_l, const numeric_index_type nnz=30, const numeric_index_type noz=10, const numeric_index_type blocksize=1) override
void init (const numeric_index_type m, const numeric_index_type n, const numeric_index_type m_l, const numeric_index_type n_l, const std::vector< numeric_index_type > &n_nz, const std::vector< numeric_index_type > &n_oz, const numeric_index_type blocksize=1)
virtual void init () override
void update_preallocation_and_zero ()
virtual void clear () override
virtual void zero () override
virtual void zero_rows (std::vector< numeric_index_type > &rows, T diag_value=0.0) override
virtual void close () override
virtual void flush () override
virtual numeric_index_type m () const override
virtual numeric_index_type n () const override
virtual numeric_index_type row_start () const override
virtual numeric_index_type row_stop () const override
virtual void set (const numeric_index_type i, const numeric_index_type j, const T value) override
virtual void add (const numeric_index_type i, const numeric_index_type j, const T value) override
virtual void add_matrix (const DenseMatrix< T > &dm, const std::vector< numeric_index_type > &rows, const std::vector< numeric_index_type > &cols) override
virtual void add_matrix (const DenseMatrix< T > &dm, const std::vector< numeric_index_type > &dof_indices) override
virtual void add_block_matrix (const DenseMatrix< T > &dm, const std::vector< numeric_index_type > &brows, const std::vector< numeric_index_type > &bcols) override
virtual void add_block_matrix (const DenseMatrix< T > &dm, const std::vector< numeric_index_type > &dof_indices) override
virtual void add (const T a, const SparseMatrix< T > &X) override
virtual T operator() (const numeric_index_type i, const numeric_index_type j) const override
virtual Real l1_norm () const override
virtual Real linfty_norm () const override
virtual bool closed () const override
virtual void print_personal (std::ostream &os=libMesh::out) const override
virtual void print_matlab (const std::string &name="") const override
virtual void get_diagonal (NumericVector< T > &dest) const override
virtual void get_transpose (SparseMatrix< T > &dest) const override
void swap (PetscMatrix< T > &)
Mat mat ()
virtual bool initialized () const
void attach_dof_map (const DofMap &dof_map)
virtual bool need_full_sparsity_pattern () const
virtual void update_sparsity_pattern (const SparsityPattern::Graph &)
void print (std::ostream &os=libMesh::out, const bool sparse=false) const
template<>
void print (std::ostream &os, const bool sparse) const
virtual void create_submatrix (SparseMatrix< T > &submatrix, const std::vector< numeric_index_type > &rows, const std::vector< numeric_index_type > &cols) const
virtual void reinit_submatrix (SparseMatrix< T > &submatrix, const std::vector< numeric_index_type > &rows, const std::vector< numeric_index_type > &cols) const
void vector_mult (NumericVector< T > &dest, const NumericVector< T > &arg) const
void vector_mult_add (NumericVector< T > &dest, const NumericVector< T > &arg) const
const Parallel::Communicator & comm () const
processor_id_type n_processors () const
processor_id_type processor_id () const
Static Public Member Functions
static std::unique_ptr< SparseMatrix< T > > build (const Parallel::Communicator &comm, const SolverPackage solver_package=libMesh::default_solver_package())
static std::string get_info ()
static void print_info (std::ostream &out=libMesh::out)
static unsigned int n_objects ()
static void enable_print_counter_info ()
static void disable_print_counter_info ()
Protected Types
typedef std::map< std::string, std::pair< unsigned int, unsigned int > > Counts
Protected Member Functions
virtual void _get_submatrix (SparseMatrix< T > &submatrix, const std::vector< numeric_index_type > &rows, const std::vector< numeric_index_type > &cols, const bool reuse_submatrix) const override
void increment_constructor_count (const std::string &name)
void increment_destructor_count (const std::string &name)
Protected Attributes
DofMap const * _dof_map
bool _is_initialized
const Parallel::Communicator & _communicator
Static Protected Attributes
static Counts _counts
static Threads::atomic< unsigned int > _n_objects
static Threads::spin_mutex _mutex
static bool _enable_print_counter = true
Private Attributes
Mat _mat
bool _destroy_mat_on_exit
PetscMatrixType _mat_type
Detailed Description
template<typename T>
class libMesh::PetscMatrix< T >
SparseMatrix interface to PETSc Mat.
This class provides a nice interface to the PETSc C-based data structures for parallel, sparse matrices. All overridden virtual functions are documented in sparse_matrix.h.
Author
Benjamin S. Kirk
Date
2002
Definition at line 90 of file petsc_linear_solver.h.
Member Typedef Documentation
Counts
typedef std::map<std::string, std::pair<unsigned int, unsigned int> > libMesh::ReferenceCounter::Counts protected inherited
Data structure to log the information. The log is identified by the class name.
Definition at line 117 of file reference_counter.h.
Constructor & Destructor Documentation
PetscMatrix() [1/4]
template<typename T > libMesh::PetscMatrix< T >::PetscMatrix (const Parallel::Communicator & comm_in) explicit
Constructor; initializes the matrix to be empty, without any structure, i.e. the matrix is not usable at all. This constructor is therefore only useful for matrices which are members of a class. All other matrices should be created at a point in the data flow where all necessary information is available.
You have to initialize the matrix before usage with init(...).
Definition at line 90 of file petsc_matrix.C.
                                                                 :
   SparseMatrix<T>(comm_in),
   _destroy_mat_on_exit(true),
   _mat_type(AIJ)
 {}
PetscMatrix() [2/4]
template<typename T > libMesh::PetscMatrix< T >::PetscMatrix (Mat m, const Parallel::Communicator & comm_in) explicit
Constructor. Creates a PetscMatrix assuming you already have a valid Mat object. In this case, m is NOT destroyed by the PetscMatrix destructor when this object goes out of scope. This allows ownership of m to remain with the original creator, and to simply provide additional functionality with the PetscMatrix.
Definition at line 101 of file petsc_matrix.C.
References libMesh::SparseMatrix< T >::_is_initialized, and libMesh::PetscMatrix< T >::_mat.
                                                                   :
   SparseMatrix<T>(comm_in),
   _destroy_mat_on_exit(false),
   _mat_type(AIJ)
 {
   this->_mat = mat_in;
   this->_is_initialized = true;
 }
PetscMatrix() [3/4]
template<typename T> libMesh::PetscMatrix< T >::PetscMatrix (PetscMatrix< T > &&) delete
This class manages a C-style struct (Mat) manually, so we don't want to allow any automatic copy/move functions to be generated, and we can't default the destructor.
PetscMatrix() [4/4]
template<typename T> libMesh::PetscMatrix< T >::PetscMatrix (const PetscMatrix< T > &) delete
~PetscMatrix()
template<typename T > libMesh::PetscMatrix< T >::~PetscMatrix () virtual
Definition at line 115 of file petsc_matrix.C.
 {
   this->clear();
 }
Member Function Documentation
_get_submatrix()
template<typename T > void libMesh::PetscMatrix< T >::_get_submatrix (SparseMatrix< T > & submatrix, const std::vector< numeric_index_type > & rows, const std::vector< numeric_index_type > & cols, const bool reuse_submatrix) const override protected virtual
This function either creates or re-initializes a matrix called submatrix which is defined by the indices given in the rows and cols vectors.
This function is implemented in terms of MatGetSubMatrix(). The reuse_submatrix parameter determines whether or not PETSc will treat submatrix as one which has already been used (had memory allocated) or as a new matrix.
Reimplemented from libMesh::SparseMatrix< T >.
Definition at line 849 of file petsc_matrix.C.
References libMesh::SparseMatrix< T >::_is_initialized, libMesh::PetscMatrix< T >::_mat, libMesh::SparseMatrix< T >::clear(), libMesh::PetscMatrix< T >::close(), libMesh::closed(), ierr, libMesh::SparseMatrix< T >::initialized(), libMesh::numeric_petsc_cast(), and PETSC_USE_POINTER.
 {
   if (!this->closed())
     {
       libmesh_deprecated();
       libmesh_warning("The matrix must be assembled before calling PetscMatrix::create_submatrix().\n"
                       "Please update your code, as this warning will become an error in a future release.");
       const_cast<PetscMatrix<T> *>(this)->close();
     }
   // Make sure the SparseMatrix passed in is really a PetscMatrix
   PetscMatrix<T> * petsc_submatrix = cast_ptr<PetscMatrix<T> *>(&submatrix);
   // If we're not reusing submatrix and submatrix is already initialized
   // then we need to clear it, otherwise we get a memory leak.
   if (!reuse_submatrix && submatrix.initialized())
     submatrix.clear();
   // Construct row and column index sets.
   PetscErrorCode ierr=0;
   IS isrow, iscol;
   ierr = ISCreateLibMesh(this->comm().get(),
                          cast_int<PetscInt>(rows.size()),
                          numeric_petsc_cast(rows.data()),
                          PETSC_USE_POINTER,
                          &isrow); LIBMESH_CHKERR(ierr);
   ierr = ISCreateLibMesh(this->comm().get(),
                          cast_int<PetscInt>(cols.size()),
                          numeric_petsc_cast(cols.data()),
                          PETSC_USE_POINTER,
                          &iscol); LIBMESH_CHKERR(ierr);
   // Extract submatrix
   ierr = LibMeshCreateSubMatrix(_mat,
                                 isrow,
                                 iscol,
 #if PETSC_RELEASE_LESS_THAN(3,0,1)
                                 PETSC_DECIDE,
 #endif
                                 (reuse_submatrix ? MAT_REUSE_MATRIX : MAT_INITIAL_MATRIX),
                                 &(petsc_submatrix->_mat));  LIBMESH_CHKERR(ierr);
   // Specify that the new submatrix is initialized and close it.
   petsc_submatrix->_is_initialized = true;
   petsc_submatrix->close();
   // Clean up PETSc data structures
   ierr = LibMeshISDestroy(&isrow); LIBMESH_CHKERR(ierr);
   ierr = LibMeshISDestroy(&iscol); LIBMESH_CHKERR(ierr);
 }
add() [1/2]
template<typename T > void libMesh::PetscMatrix< T >::add (const numeric_index_type i, const numeric_index_type j, const T value) override virtual
Add value to the element (i,j). Throws an error if the entry does not exist. Zero values can be "added" to non-existent entries.
Implements libMesh::SparseMatrix< T >.
Definition at line 1074 of file petsc_matrix.C.
References ierr, libMesh::initialized(), and value.
 {
   libmesh_assert (this->initialized());
   PetscErrorCode ierr=0;
   PetscInt i_val=i, j_val=j;
   PetscScalar petsc_value = static_cast<PetscScalar>(value);
   ierr = MatSetValues(_mat, 1, &i_val, 1, &j_val,
                       &petsc_value, ADD_VALUES);
   LIBMESH_CHKERR(ierr);
 }
add() [2/2]
template<typename T > void libMesh::PetscMatrix< T >::add (const T a, const SparseMatrix< T > & X) override virtual
Compute A += a*X for scalar a, matrix X.
Note
The matrices A and X need to have the same nonzero pattern, otherwise PETSc will crash!
It is advisable to not only allocate appropriate memory with init(), but also explicitly zero the terms of this whenever you add a non-zero value to X.
X will be closed, if not already done, before performing any work.
Implements libMesh::SparseMatrix< T >.
Definition at line 1105 of file petsc_matrix.C.
References libMesh::PetscMatrix< T >::_mat, libMesh::PetscMatrix< T >::closed(), ierr, libMesh::initialized(), libMesh::SparseMatrix< T >::m(), and libMesh::SparseMatrix< T >::n().
 {
   libmesh_assert (this->initialized());
   // sanity check. but this cannot avoid
   // crash due to incompatible sparsity structure...
   libmesh_assert_equal_to (this->m(), X_in.m());
   libmesh_assert_equal_to (this->n(), X_in.n());
   PetscScalar a = static_cast<PetscScalar>      (a_in);
   const PetscMatrix<T> * X = cast_ptr<const PetscMatrix<T> *> (&X_in);
   libmesh_assert (X);
   PetscErrorCode ierr=0;
   // the matrix from which we copy the values has to be assembled/closed
   libmesh_assert(X->closed());
   semiparallel_only();
   ierr = MatAXPY(_mat, a, X->_mat, DIFFERENT_NONZERO_PATTERN);
   LIBMESH_CHKERR(ierr);
 }
add_block_matrix() [1/2]
template<typename T > void libMesh::PetscMatrix< T >::add_block_matrix (const DenseMatrix< T > & dm, const std::vector< numeric_index_type > & brows, const std::vector< numeric_index_type > & bcols) override virtual
Add the full matrix dm to the SparseMatrix. This is useful for adding an element matrix at assembly time. The matrix is assumed blocked, and brow, bcol correspond to the block row and column indices.
Reimplemented from libMesh::SparseMatrix< T >.
Definition at line 805 of file petsc_matrix.C.
References libMesh::DenseMatrix< T >::get_values(), ierr, libMesh::initialized(), libMesh::DenseMatrixBase< T >::m(), libMesh::DenseMatrixBase< T >::n(), and libMesh::numeric_petsc_cast().
Referenced by libMesh::PetscMatrix< T >::add_block_matrix().
 {
   libmesh_assert (this->initialized());
   const numeric_index_type n_brows =
     cast_int<numeric_index_type>(brows.size());
   const numeric_index_type n_bcols =
     cast_int<numeric_index_type>(bcols.size());
   PetscErrorCode ierr=0;
 #ifndef NDEBUG
   const numeric_index_type n_rows  =
     cast_int<numeric_index_type>(dm.m());
   const numeric_index_type n_cols  =
     cast_int<numeric_index_type>(dm.n());
   const numeric_index_type blocksize = n_rows / n_brows;
   libmesh_assert_equal_to (n_cols / n_bcols, blocksize);
   libmesh_assert_equal_to (blocksize*n_brows, n_rows);
   libmesh_assert_equal_to (blocksize*n_bcols, n_cols);
   PetscInt petsc_blocksize;
   ierr = MatGetBlockSize(_mat, &petsc_blocksize);
   LIBMESH_CHKERR(ierr);
   libmesh_assert_equal_to (blocksize, static_cast<numeric_index_type>(petsc_blocksize));
 #endif
   // These casts are required for PETSc <= 2.1.5
   ierr = MatSetValuesBlocked(_mat,
                              n_brows, numeric_petsc_cast(brows.data()),
                              n_bcols, numeric_petsc_cast(bcols.data()),
                              const_cast<PetscScalar *>(dm.get_values().data()),
                              ADD_VALUES);
   LIBMESH_CHKERR(ierr);
 }
add_block_matrix() [2/2]
template<typename T> virtual void libMesh::PetscMatrix< T >::add_block_matrix (const DenseMatrix< T > & dm, const std::vector< numeric_index_type > & dof_indices) inline override virtual
Same as add_block_matrix(), but assumes the row and column maps are the same. Thus the matrix dm must be square.
Reimplemented from libMesh::SparseMatrix< T >.
Definition at line 191 of file petsc_matrix.h.
References libMesh::PetscMatrix< T >::add_block_matrix().
   { this->add_block_matrix (dm, dof_indices, dof_indices); }
add_matrix() [1/2]
template<typename T > void libMesh::PetscMatrix< T >::add_matrix (const DenseMatrix< T > & dm, const std::vector< numeric_index_type > & rows, const std::vector< numeric_index_type > & cols) override virtual
Add the full matrix dm to the SparseMatrix. This is useful for adding an element matrix at assembly time.
Implements libMesh::SparseMatrix< T >.
Definition at line 778 of file petsc_matrix.C.
References libMesh::DenseMatrix< T >::get_values(), ierr, libMesh::initialized(), libMesh::DenseMatrixBase< T >::m(), libMesh::DenseMatrixBase< T >::n(), and libMesh::numeric_petsc_cast().
 {
   libmesh_assert (this->initialized());
   const numeric_index_type n_rows = dm.m();
   const numeric_index_type n_cols = dm.n();
   libmesh_assert_equal_to (rows.size(), n_rows);
   libmesh_assert_equal_to (cols.size(), n_cols);
   PetscErrorCode ierr=0;
   ierr = MatSetValues(_mat,
                       n_rows, numeric_petsc_cast(rows.data()),
                       n_cols, numeric_petsc_cast(cols.data()),
                       const_cast<PetscScalar *>(dm.get_values().data()),
                       ADD_VALUES);
   LIBMESH_CHKERR(ierr);
 }
add_matrix() [2/2]
template<typename T > void libMesh::PetscMatrix< T >::add_matrix (const DenseMatrix< T > & dm, const std::vector< numeric_index_type > & dof_indices) override virtual
Same as add_matrix, but assumes the row and column maps are the same. Thus the matrix dm must be square.
Implements libMesh::SparseMatrix< T >.
Definition at line 1092 of file petsc_matrix.C.
 {
   this->add_matrix (dm, dof_indices, dof_indices);
 }
attach_dof_map()
template<typename T> void libMesh::SparseMatrix< T >::attach_dof_map (const DofMap & dof_map) inline inherited
Get a pointer to the DofMap to use.
Definition at line 109 of file sparse_matrix.h.
Referenced by libMesh::__libmesh_tao_hessian(), and libMesh::DofMap::attach_matrix().
   { _dof_map = &dof_map; }
build()
template<typename T > std::unique_ptr< SparseMatrix< T > > libMesh::SparseMatrix< T >::build (const Parallel::Communicator & comm, const SolverPackage solver_package = libMesh::default_solver_package()) static inherited
Builds a SparseMatrix<T> using the linear solver package specified by solver_package
Definition at line 130 of file sparse_matrix.C.
Referenced by libMesh::ImplicitSystem::add_matrix(), libMesh::EigenSystem::init_data(), and libMesh::EigenSystem::init_matrices().
 {
   // Avoid unused parameter warnings when no solver packages are enabled.
   libmesh_ignore(comm);
   // Build the appropriate vector
   switch (solver_package)
     {
 #ifdef LIBMESH_HAVE_LASPACK
     case LASPACK_SOLVERS:
       return libmesh_make_unique<LaspackMatrix<T>>(comm);
 #endif
 #ifdef LIBMESH_HAVE_PETSC
     case PETSC_SOLVERS:
       return libmesh_make_unique<PetscMatrix<T>>(comm);
 #endif
 #ifdef LIBMESH_TRILINOS_HAVE_EPETRA
     case TRILINOS_SOLVERS:
       return libmesh_make_unique<EpetraMatrix<T>>(comm);
 #endif
 #ifdef LIBMESH_HAVE_EIGEN
     case EIGEN_SOLVERS:
       return libmesh_make_unique<EigenSparseMatrix<T>>(comm);
 #endif
     default:
       libmesh_error_msg("ERROR:  Unrecognized solver package: " << solver_package);
     }
 }
clear()
template<typename T > void libMesh::PetscMatrix< T >::clear () override virtual
Restores the SparseMatrix<T> to a pristine state.
Implements libMesh::SparseMatrix< T >.
Definition at line 528 of file petsc_matrix.C.
References libMesh::libMeshPrivateData::_is_initialized, ierr, and libMesh::initialized().
 {
   PetscErrorCode ierr=0;
   if ((this->initialized()) && (this->_destroy_mat_on_exit))
     {
       semiparallel_only();
       ierr = LibMeshMatDestroy (&_mat);
       LIBMESH_CHKERR(ierr);
       this->_is_initialized = false;
     }
 }
close()
template<typename T > void libMesh::PetscMatrix< T >::close () override virtual
Calls the SparseMatrix's internal assembly routines, ensuring that the values are consistent across processors.
Implements libMesh::SparseMatrix< T >.
Definition at line 957 of file petsc_matrix.C.
References ierr.
Referenced by libMesh::PetscMatrix< T >::_get_submatrix(), libMesh::PetscLinearSolver< T >::adjoint_solve(), libMesh::PetscMatrix< T >::get_transpose(), libMesh::PetscLinearSolver< T >::solve(), libMesh::SlepcEigenSolver< T >::solve_generalized(), and libMesh::SlepcEigenSolver< T >::solve_standard().
 {
   semiparallel_only();
   // BSK - 1/19/2004
   // strictly this check should be OK, but it seems to
   // fail on matrix-free matrices.  Do they falsely
   // state they are assembled?  Check with the developers...
   //   if (this->closed())
   //     return;
   PetscErrorCode ierr=0;
   ierr = MatAssemblyBegin (_mat, MAT_FINAL_ASSEMBLY);
   LIBMESH_CHKERR(ierr);
   ierr = MatAssemblyEnd   (_mat, MAT_FINAL_ASSEMBLY);
   LIBMESH_CHKERR(ierr);
 }
closed()
template<typename T > bool libMesh::PetscMatrix< T >::closed () const override virtual
Returns
true if the matrix has been assembled.
Implements libMesh::SparseMatrix< T >.
Definition at line 1194 of file petsc_matrix.C.
References ierr, and libMesh::initialized().
Referenced by libMesh::PetscMatrix< T >::add().
 {
   libmesh_assert (this->initialized());
   PetscErrorCode ierr=0;
   PetscBool assembled;
   ierr = MatAssembled(_mat, &assembled);
   LIBMESH_CHKERR(ierr);
   return (assembled == PETSC_TRUE);
 }
comm()
const Parallel::Communicator& libMesh::ParallelObject::comm () const inline inherited
Returns
A reference to the Parallel::Communicator object used by this mesh.
Definition at line 89 of file parallel_object.h.
References libMesh::ParallelObject::_communicator.
Referenced by libMesh::__libmesh_petsc_diff_solver_jacobian(), libMesh::__libmesh_petsc_diff_solver_monitor(), libMesh::__libmesh_petsc_diff_solver_residual(), libMesh::__libmesh_tao_equality_constraints(), libMesh::__libmesh_tao_equality_constraints_jacobian(), libMesh::__libmesh_tao_gradient(), libMesh::__libmesh_tao_hessian(), libMesh::__libmesh_tao_inequality_constraints(), libMesh::__libmesh_tao_inequality_constraints_jacobian(), libMesh::__libmesh_tao_objective(), libMesh::MeshRefinement::_coarsen_elements(), libMesh::ExactSolution::_compute_error(), libMesh::UniformRefinementEstimator::_estimate_error(), libMesh::BoundaryInfo::_find_id_maps(), libMesh::SlepcEigenSolver< T >::_petsc_shell_matrix_get_diagonal(), libMesh::PetscLinearSolver< T >::_petsc_shell_matrix_get_diagonal(), libMesh::SlepcEigenSolver< T >::_petsc_shell_matrix_mult(), libMesh::PetscLinearSolver< T >::_petsc_shell_matrix_mult(), libMesh::PetscLinearSolver< T >::_petsc_shell_matrix_mult_add(), libMesh::EquationSystems::_read_impl(), libMesh::MeshRefinement::_refine_elements(), libMesh::MeshRefinement::_smooth_flags(), libMesh::PetscDMWrapper::add_dofs_helper(), libMesh::PetscDMWrapper::add_dofs_to_section(), libMesh::ImplicitSystem::add_matrix(), libMesh::System::add_vector(), libMesh::UnstructuredMesh::all_second_order(), libMesh::MeshTools::Modification::all_tri(), libMesh::LaplaceMeshSmoother::allgather_graph(), libMesh::FEMSystem::assemble_qoi(), libMesh::MeshCommunication::assign_global_indices(), libMesh::DofMap::attach_matrix(), libMesh::MeshTools::Generation::build_extrusion(), libMesh::BoundaryInfo::build_node_list_from_side_list(), libMesh::EquationSystems::build_parallel_elemental_solution_vector(), libMesh::EquationSystems::build_parallel_solution_vector(), libMesh::PetscDMWrapper::build_section(), libMesh::PetscDMWrapper::build_sf(), libMesh::MeshBase::cache_elem_dims(), libMesh::System::calculate_norm(), libMesh::DofMap::check_dirichlet_bcid_consistency(), libMesh::PetscDMWrapper::check_section_n_dofs(), libMesh::Nemesis_IO_Helper::compute_num_global_elem_blocks(), libMesh::Nemesis_IO_Helper::compute_num_global_nodesets(), libMesh::Nemesis_IO_Helper::compute_num_global_sidesets(), libMesh::Problem_Interface::computeF(), libMesh::Problem_Interface::computeJacobian(), libMesh::Problem_Interface::computePreconditioner(), libMesh::ExodusII_IO::copy_elemental_solution(), libMesh::MeshTools::correct_node_proc_ids(), libMesh::MeshTools::create_bounding_box(), libMesh::MeshTools::create_nodal_bounding_box(), libMesh::MeshRefinement::create_parent_error_vector(), libMesh::MeshTools::create_processor_bounding_box(), libMesh::MeshTools::create_subdomain_bounding_box(), libMesh::MeshCommunication::delete_remote_elements(), libMesh::DofMap::distribute_dofs(), DMlibMeshFunction(), DMlibMeshJacobian(), DMlibMeshSetSystem_libMesh(), DMVariableBounds_libMesh(), libMesh::MeshRefinement::eliminate_unrefined_patches(), libMesh::EpetraVector< T >::EpetraVector(), libMesh::WeightedPatchRecoveryErrorEstimator::estimate_error(), libMesh::PatchRecoveryErrorEstimator::estimate_error(), libMesh::JumpErrorEstimator::estimate_error(), libMesh::AdjointRefinementEstimator::estimate_error(), libMesh::ExactErrorEstimator::estimate_error(), libMesh::MeshRefinement::flag_elements_by_elem_fraction(), libMesh::MeshRefinement::flag_elements_by_error_fraction(), libMesh::MeshRefinement::flag_elements_by_nelem_target(), libMesh::CondensedEigenSystem::get_eigenpair(), libMesh::DofMap::get_info(), libMesh::ImplicitSystem::get_linear_solver(), libMesh::LocationMap< T >::init(), libMesh::TimeSolver::init(), libMesh::SystemSubsetBySubdomain::init(), libMesh::PetscDMWrapper::init_and_attach_petscdm(), libMesh::EigenSystem::init_data(), libMesh::EigenSystem::init_matrices(), libMesh::OptimizationSystem::initialize_equality_constraints_storage(), libMesh::OptimizationSystem::initialize_inequality_constraints_storage(), libMesh::MeshTools::libmesh_assert_consistent_distributed(), libMesh::MeshTools::libmesh_assert_consistent_distributed_nodes(), libMesh::MeshTools::libmesh_assert_contiguous_dof_ids(), libMesh::MeshTools::libmesh_assert_parallel_consistent_new_node_procids(), libMesh::MeshTools::libmesh_assert_parallel_consistent_procids< Elem >(), libMesh::MeshTools::libmesh_assert_parallel_consistent_procids< Node >(), libMesh::MeshTools::libmesh_assert_topology_consistent_procids< Node >(), libMesh::MeshTools::libmesh_assert_valid_boundary_ids(), libMesh::MeshTools::libmesh_assert_valid_dof_ids(), libMesh::MeshTools::libmesh_assert_valid_neighbors(), libMesh::DistributedMesh::libmesh_assert_valid_parallel_flags(), libMesh::DistributedMesh::libmesh_assert_valid_parallel_object_ids(), libMesh::DistributedMesh::libmesh_assert_valid_parallel_p_levels(), libMesh::MeshTools::libmesh_assert_valid_refinement_flags(), libMesh::MeshTools::libmesh_assert_valid_unique_ids(), libMesh::libmesh_petsc_snes_fd_residual(), libMesh::libmesh_petsc_snes_jacobian(), libMesh::libmesh_petsc_snes_mffd_residual(), libMesh::libmesh_petsc_snes_postcheck(), libMesh::libmesh_petsc_snes_residual(), libMesh::libmesh_petsc_snes_residual_helper(), libMesh::MeshRefinement::limit_level_mismatch_at_edge(), libMesh::MeshRefinement::limit_level_mismatch_at_node(), libMesh::MeshRefinement::limit_overrefined_boundary(), libMesh::MeshRefinement::limit_underrefined_boundary(), libMesh::MeshRefinement::make_coarsening_compatible(), libMesh::MeshCommunication::make_elems_parallel_consistent(), libMesh::MeshRefinement::make_flags_parallel_consistent(), libMesh::MeshCommunication::make_new_node_proc_ids_parallel_consistent(), libMesh::MeshCommunication::make_new_nodes_parallel_consistent(), libMesh::MeshCommunication::make_node_ids_parallel_consistent(), libMesh::MeshCommunication::make_node_proc_ids_parallel_consistent(), libMesh::MeshCommunication::make_node_unique_ids_parallel_consistent(), libMesh::MeshCommunication::make_nodes_parallel_consistent(), libMesh::MeshCommunication::make_p_levels_parallel_consistent(), libMesh::MeshRefinement::make_refinement_compatible(), libMesh::FEMSystem::mesh_position_set(), libMesh::DistributedMesh::n_active_elem(), libMesh::MeshTools::n_active_levels(), libMesh::BoundaryInfo::n_boundary_conds(), libMesh::BoundaryInfo::n_edge_conds(), libMesh::CondensedEigenSystem::n_global_non_condensed_dofs(), libMesh::MeshTools::n_levels(), libMesh::BoundaryInfo::n_nodeset_conds(), libMesh::MeshTools::n_p_levels(), libMesh::BoundaryInfo::n_shellface_conds(), libMesh::DistributedMesh::parallel_max_elem_id(), libMesh::DistributedMesh::parallel_max_node_id(), libMesh::ReplicatedMesh::parallel_max_unique_id(), libMesh::DistributedMesh::parallel_max_unique_id(), libMesh::DistributedMesh::parallel_n_elem(), libMesh::DistributedMesh::parallel_n_nodes(), libMesh::SparsityPattern::Build::parallel_sync(), libMesh::MeshTools::paranoid_n_levels(), libMesh::petsc_auto_fieldsplit(), libMesh::System::point_gradient(), libMesh::System::point_hessian(), libMesh::System::point_value(), libMesh::MeshBase::prepare_for_use(), libMesh::Nemesis_IO::read(), libMesh::XdrIO::read(), libMesh::CheckpointIO::read_header(), libMesh::XdrIO::read_header(), libMesh::System::read_header(), libMesh::System::read_legacy_data(), libMesh::System::read_SCALAR_dofs(), libMesh::XdrIO::read_serialized_bc_names(), libMesh::XdrIO::read_serialized_bcs_helper(), libMesh::System::read_serialized_blocked_dof_objects(), libMesh::XdrIO::read_serialized_connectivity(), libMesh::XdrIO::read_serialized_nodes(), libMesh::XdrIO::read_serialized_nodesets(), libMesh::XdrIO::read_serialized_subdomain_names(), libMesh::System::read_serialized_vector(), libMesh::MeshBase::recalculate_n_partitions(), libMesh::MeshRefinement::refine_and_coarsen_elements(), libMesh::DistributedMesh::renumber_dof_objects(), libMesh::CheckpointIO::select_split_config(), libMesh::DofMap::set_nonlocal_dof_objects(), libMesh::PetscDMWrapper::set_point_range_in_section(), libMesh::PetscDiffSolver::setup_petsc_data(), libMesh::LaplaceMeshSmoother::smooth(), libMesh::split_mesh(), libMesh::MeshBase::subdomain_ids(), libMesh::BoundaryInfo::sync(), libMesh::MeshRefinement::test_level_one(), libMesh::MeshRefinement::test_unflagged(), libMesh::MeshTools::total_weight(), libMesh::MeshRefinement::uniformly_coarsen(), libMesh::NameBasedIO::write(), libMesh::XdrIO::write(), libMesh::System::write_SCALAR_dofs(), libMesh::XdrIO::write_serialized_bcs_helper(), libMesh::System::write_serialized_blocked_dof_objects(), libMesh::XdrIO::write_serialized_connectivity(), libMesh::XdrIO::write_serialized_nodes(), and libMesh::XdrIO::write_serialized_nodesets().
   { return _communicator; }
create_submatrix()
template<typename T> virtual void libMesh::SparseMatrix< T >::create_submatrix (SparseMatrix< T > & submatrix, const std::vector< numeric_index_type > & rows, const std::vector< numeric_index_type > & cols) const inline virtual inherited
This function creates a matrix called "submatrix" which is defined by the row and column indices given in the "rows" and "cols" entries. Currently this operation is only defined for the PetscMatrix type.
Definition at line 354 of file sparse_matrix.h.
   {
     this->_get_submatrix(submatrix,
                          rows,
                          cols,
                          false); // false means DO NOT REUSE submatrix
   }
disable_print_counter_info()
void libMesh::ReferenceCounter::disable_print_counter_info () static inherited
Definition at line 106 of file reference_counter.C.
References libMesh::ReferenceCounter::_enable_print_counter.
Referenced by libMesh::LibMeshInit::LibMeshInit().
 {
   _enable_print_counter = false;
   return;
 }
enable_print_counter_info()
void libMesh::ReferenceCounter::enable_print_counter_info () static inherited
Methods to enable/disable the reference counter output from print_info()
Definition at line 100 of file reference_counter.C.
References libMesh::ReferenceCounter::_enable_print_counter.
 {
   _enable_print_counter = true;
   return;
 }
flush()
template<typename T > void libMesh::PetscMatrix< T >::flush () override virtual
For PETSc matrix , this function is similar to close but without shrinking memory. This is useful when we want to switch between ADD_VALUES and INSERT_VALUES. close should be called before using the matrix.
Reimplemented from libMesh::SparseMatrix< T >.
Definition at line 977 of file petsc_matrix.C.
References ierr.
 {
   semiparallel_only();
   PetscErrorCode ierr=0;
   ierr = MatAssemblyBegin (_mat, MAT_FLUSH_ASSEMBLY);
   LIBMESH_CHKERR(ierr);
   ierr = MatAssemblyEnd   (_mat, MAT_FLUSH_ASSEMBLY);
   LIBMESH_CHKERR(ierr);
 }
get_diagonal()
template<typename T > void libMesh::PetscMatrix< T >::get_diagonal (NumericVector< T > & dest) const override virtual
Copies the diagonal part of the matrix into dest.
Implements libMesh::SparseMatrix< T >.
Definition at line 908 of file petsc_matrix.C.
References ierr, and libMesh::PetscVector< T >::vec().
 {
   // Make sure the NumericVector passed in is really a PetscVector
   PetscVector<T> & petsc_dest = cast_ref<PetscVector<T> &>(dest);
   // Needs a const_cast since PETSc does not work with const.
   PetscErrorCode ierr =
     MatGetDiagonal(const_cast<PetscMatrix<T> *>(this)->mat(),petsc_dest.vec()); LIBMESH_CHKERR(ierr);
 }
get_info()
std::string libMesh::ReferenceCounter::get_info () static inherited
Gets a string containing the reference information.
Definition at line 47 of file reference_counter.C.
References libMesh::ReferenceCounter::_counts, and libMesh::Quality::name().
Referenced by libMesh::ReferenceCounter::print_info().
 {
 #if defined(LIBMESH_ENABLE_REFERENCE_COUNTING) && defined(DEBUG)
   std::ostringstream oss;
   oss << '\n'
       << " ---------------------------------------------------------------------------- \n"
       << "| Reference count information                                                |\n"
       << " ---------------------------------------------------------------------------- \n";
   for (const auto & pr : _counts)
     {
       const std::string name(pr.first);
       const unsigned int creations    = pr.second.first;
       const unsigned int destructions = pr.second.second;
       oss << "| " << name << " reference count information:\n"
           << "|  Creations:    " << creations    << '\n'
           << "|  Destructions: " << destructions << '\n';
     }
   oss << " ---------------------------------------------------------------------------- \n";
   return oss.str();
 #else
   return "";
 #endif
 }
get_transpose()
template<typename T > void libMesh::PetscMatrix< T >::get_transpose (SparseMatrix< T > & dest) const override virtual
Copies the transpose of the matrix into dest, which may be *this.
Implements libMesh::SparseMatrix< T >.
Definition at line 921 of file petsc_matrix.C.
References libMesh::SparseMatrix< T >::_is_initialized, libMesh::PetscMatrix< T >::_mat, libMesh::SparseMatrix< T >::clear(), libMesh::PetscMatrix< T >::close(), and ierr.
 {
   // Make sure the SparseMatrix passed in is really a PetscMatrix
   PetscMatrix<T> & petsc_dest = cast_ref<PetscMatrix<T> &>(dest);
   // If we aren't reusing the matrix then need to clear dest,
   // otherwise we get a memory leak
   if (&petsc_dest != this)
     dest.clear();
   PetscErrorCode ierr;
 #if PETSC_VERSION_LESS_THAN(3,0,0)
   if (&petsc_dest == this)
     ierr = MatTranspose(_mat,PETSC_NULL);
   else
     ierr = MatTranspose(_mat,&petsc_dest._mat);
   LIBMESH_CHKERR(ierr);
 #else
   // FIXME - we can probably use MAT_REUSE_MATRIX in more situations
   if (&petsc_dest == this)
     ierr = MatTranspose(_mat,MAT_REUSE_MATRIX,&petsc_dest._mat);
   else
     ierr = MatTranspose(_mat,MAT_INITIAL_MATRIX,&petsc_dest._mat);
   LIBMESH_CHKERR(ierr);
 #endif
   // Specify that the transposed matrix is initialized and close it.
   petsc_dest._is_initialized = true;
   petsc_dest.close();
 }
increment_constructor_count()
void libMesh::ReferenceCounter::increment_constructor_count (const std::string & name) inline protected inherited
Increments the construction counter. Should be called in the constructor of any derived class that will be reference counted.
Definition at line 181 of file reference_counter.h.
References libMesh::ReferenceCounter::_counts, libMesh::Quality::name(), and libMesh::Threads::spin_mtx.
Referenced by libMesh::ReferenceCountedObject< RBParametrized >::ReferenceCountedObject().
 {
   Threads::spin_mutex::scoped_lock lock(Threads::spin_mtx);
   std::pair<unsigned int, unsigned int> & p = _counts[name];
   p.first++;
 }
increment_destructor_count()
void libMesh::ReferenceCounter::increment_destructor_count (const std::string & name) inline protected inherited
Increments the destruction counter. Should be called in the destructor of any derived class that will be reference counted.
Definition at line 194 of file reference_counter.h.
References libMesh::ReferenceCounter::_counts, libMesh::Quality::name(), and libMesh::Threads::spin_mtx.
Referenced by libMesh::ReferenceCountedObject< RBParametrized >::~ReferenceCountedObject().
 {
   Threads::spin_mutex::scoped_lock lock(Threads::spin_mtx);
   std::pair<unsigned int, unsigned int> & p = _counts[name];
   p.second++;
 }
init() [1/3]
template<typename T > void libMesh::PetscMatrix< T >::init (const numeric_index_type m, const numeric_index_type n, const numeric_index_type m_l, const numeric_index_type n_l, const numeric_index_type nnz = 30, const numeric_index_type noz = 10, const numeric_index_type blocksize = 1) override virtual
Initialize SparseMatrix with the specified sizes.
Parameters
m The global number of rows.
n The global number of columns.
m_l The local number of rows.
n_l The local number of columns.
nnz The number of on-diagonal nonzeros per row (defaults to 30).
noz The number of off-diagonal nonzeros per row (defaults to 10).
blocksize Optional value indicating dense coupled blocks for systems with multiple variables all of the same type.
Implements libMesh::SparseMatrix< T >.
Definition at line 127 of file petsc_matrix.C.
References libMesh::libMeshPrivateData::_is_initialized, libMesh::AIJ, libMesh::HYPRE, ierr, libMesh::initialized(), libMesh::libmesh_ignore(), and libMesh::zero.
 {
   // So compilers don't warn when !LIBMESH_ENABLE_BLOCKED_STORAGE
   libmesh_ignore(blocksize_in);
   // Clear initialized matrices
   if (this->initialized())
     this->clear();
   this->_is_initialized = true;
   PetscErrorCode ierr = 0;
   PetscInt m_global   = static_cast<PetscInt>(m_in);
   PetscInt n_global   = static_cast<PetscInt>(n_in);
   PetscInt m_local    = static_cast<PetscInt>(m_l);
   PetscInt n_local    = static_cast<PetscInt>(n_l);
   PetscInt n_nz       = static_cast<PetscInt>(nnz);
   PetscInt n_oz       = static_cast<PetscInt>(noz);
   ierr = MatCreate(this->comm().get(), &_mat);
   LIBMESH_CHKERR(ierr);
   ierr = MatSetSizes(_mat, m_local, n_local, m_global, n_global);
   LIBMESH_CHKERR(ierr);
 #ifdef LIBMESH_ENABLE_BLOCKED_STORAGE
   PetscInt blocksize  = static_cast<PetscInt>(blocksize_in);
   if (blocksize > 1)
     {
       // specified blocksize, bs>1.
       // double check sizes.
       libmesh_assert_equal_to (m_local  % blocksize, 0);
       libmesh_assert_equal_to (n_local  % blocksize, 0);
       libmesh_assert_equal_to (m_global % blocksize, 0);
       libmesh_assert_equal_to (n_global % blocksize, 0);
       libmesh_assert_equal_to (n_nz     % blocksize, 0);
       libmesh_assert_equal_to (n_oz     % blocksize, 0);
       ierr = MatSetType(_mat, MATBAIJ); // Automatically chooses seqbaij or mpibaij
       LIBMESH_CHKERR(ierr);
       ierr = MatSetBlockSize(_mat, blocksize);
       LIBMESH_CHKERR(ierr);
       ierr = MatSeqBAIJSetPreallocation(_mat, blocksize, n_nz/blocksize, PETSC_NULL);
       LIBMESH_CHKERR(ierr);
       ierr = MatMPIBAIJSetPreallocation(_mat, blocksize,
                                         n_nz/blocksize, PETSC_NULL,
                                         n_oz/blocksize, PETSC_NULL);
       LIBMESH_CHKERR(ierr);
     }
   else
 #endif
     {
       switch (_mat_type) {
         case AIJ:
           ierr = MatSetType(_mat, MATAIJ); // Automatically chooses seqaij or mpiaij
           LIBMESH_CHKERR(ierr);
           ierr = MatSeqAIJSetPreallocation(_mat, n_nz, PETSC_NULL);
           LIBMESH_CHKERR(ierr);
           ierr = MatMPIAIJSetPreallocation(_mat, n_nz, PETSC_NULL, n_oz, PETSC_NULL);
           LIBMESH_CHKERR(ierr);
           break;
         case HYPRE:
 #if !PETSC_VERSION_LESS_THAN(3,9,4) && LIBMESH_HAVE_PETSC_HYPRE
           ierr = MatSetType(_mat, MATHYPRE);
           LIBMESH_CHKERR(ierr);
           ierr = MatHYPRESetPreallocation(_mat, n_nz, PETSC_NULL, n_oz, PETSC_NULL);
           LIBMESH_CHKERR(ierr);
 #else
           libmesh_error_msg("PETSc 3.9.4 or higher with hypre is required for MatHypre");
 #endif
           break;
         default: libmesh_error_msg("Unsupported petsc matrix type");
       }
     }
   // Make it an error for PETSc to allocate new nonzero entries during assembly
 #if PETSC_VERSION_LESS_THAN(3,0,0)
   ierr = MatSetOption(_mat, MAT_NEW_NONZERO_ALLOCATION_ERR);
 #else
   ierr = MatSetOption(_mat, MAT_NEW_NONZERO_ALLOCATION_ERR, PETSC_TRUE);
 #endif
   LIBMESH_CHKERR(ierr);
   // Is prefix information available somewhere? Perhaps pass in the system name?
   ierr = MatSetOptionsPrefix(_mat, "");
   LIBMESH_CHKERR(ierr);
   ierr = MatSetFromOptions(_mat);
   LIBMESH_CHKERR(ierr);
   this->zero ();
 }
init() [2/3]
template<typename T > void libMesh::PetscMatrix< T >::init (const numeric_index_type m, const numeric_index_type n, const numeric_index_type m_l, const numeric_index_type n_l, const std::vector< numeric_index_type > & n_nz, const std::vector< numeric_index_type > & n_oz, const numeric_index_type blocksize = 1)
Initialize a PETSc matrix.
Parameters
m The global number of rows.
n The global number of columns.
m_l The local number of rows.
n_l The local number of columns.
n_nz array containing the number of nonzeros in each row of the DIAGONAL portion of the local submatrix.
n_oz Array containing the number of nonzeros in each row of the OFF-DIAGONAL portion of the local submatrix.
blocksize Optional value indicating dense coupled blocks for systems with multiple variables all of the same type.
Definition at line 229 of file petsc_matrix.C.
References libMesh::libMeshPrivateData::_is_initialized, libMesh::AIJ, libMesh::HYPRE, ierr, libMesh::initialized(), libMesh::libmesh_ignore(), libMesh::numeric_petsc_cast(), and libMesh::zero.
 {
   // So compilers don't warn when !LIBMESH_ENABLE_BLOCKED_STORAGE
   libmesh_ignore(blocksize_in);
   // Clear initialized matrices
   if (this->initialized())
     this->clear();
   this->_is_initialized = true;
   // Make sure the sparsity pattern isn't empty unless the matrix is 0x0
   libmesh_assert_equal_to (n_nz.size(), m_l);
   libmesh_assert_equal_to (n_oz.size(), m_l);
   PetscErrorCode ierr = 0;
   PetscInt m_global   = static_cast<PetscInt>(m_in);
   PetscInt n_global   = static_cast<PetscInt>(n_in);
   PetscInt m_local    = static_cast<PetscInt>(m_l);
   PetscInt n_local    = static_cast<PetscInt>(n_l);
   ierr = MatCreate(this->comm().get(), &_mat);
   LIBMESH_CHKERR(ierr);
   ierr = MatSetSizes(_mat, m_local, n_local, m_global, n_global);
   LIBMESH_CHKERR(ierr);
 #ifdef LIBMESH_ENABLE_BLOCKED_STORAGE
   PetscInt blocksize  = static_cast<PetscInt>(blocksize_in);
   if (blocksize > 1)
     {
       // specified blocksize, bs>1.
       // double check sizes.
       libmesh_assert_equal_to (m_local  % blocksize, 0);
       libmesh_assert_equal_to (n_local  % blocksize, 0);
       libmesh_assert_equal_to (m_global % blocksize, 0);
       libmesh_assert_equal_to (n_global % blocksize, 0);
       ierr = MatSetType(_mat, MATBAIJ); // Automatically chooses seqbaij or mpibaij
       LIBMESH_CHKERR(ierr);
       ierr = MatSetBlockSize(_mat, blocksize);
       LIBMESH_CHKERR(ierr);
       // transform the per-entry n_nz and n_oz arrays into their block counterparts.
       std::vector<numeric_index_type> b_n_nz, b_n_oz;
       transform_preallocation_arrays (blocksize,
                                       n_nz, n_oz,
                                       b_n_nz, b_n_oz);
       ierr = MatSeqBAIJSetPreallocation (_mat,
                                          blocksize,
                                          0,
                                          numeric_petsc_cast(b_n_nz.empty() ? nullptr : b_n_nz.data()));
       LIBMESH_CHKERR(ierr);
       ierr = MatMPIBAIJSetPreallocation (_mat,
                                          blocksize,
                                          0,
                                          numeric_petsc_cast(b_n_nz.empty() ? nullptr : b_n_nz.data()),
                                          0,
                                          numeric_petsc_cast(b_n_oz.empty() ? nullptr : b_n_oz.data()));
       LIBMESH_CHKERR(ierr);
     }
   else
 #endif
     {
       switch (_mat_type) {
         case AIJ:
           ierr = MatSetType(_mat, MATAIJ); // Automatically chooses seqaij or mpiaij
           LIBMESH_CHKERR(ierr);
           ierr = MatSeqAIJSetPreallocation (_mat,
                                             0,
                                             numeric_petsc_cast(n_nz.empty() ? nullptr : n_nz.data()));
           LIBMESH_CHKERR(ierr);
           ierr = MatMPIAIJSetPreallocation (_mat,
                                             0,
                                             numeric_petsc_cast(n_nz.empty() ? nullptr : n_nz.data()),
                                             0,
                                             numeric_petsc_cast(n_oz.empty() ? nullptr : n_oz.data()));
           break;
         case HYPRE:
 #if !PETSC_VERSION_LESS_THAN(3,9,4) && LIBMESH_HAVE_PETSC_HYPRE
           ierr = MatSetType(_mat, MATHYPRE);
           LIBMESH_CHKERR(ierr);
           ierr = MatHYPRESetPreallocation (_mat,
                                            0,
                                            numeric_petsc_cast(n_nz.empty() ? nullptr : n_nz.data()),
                                            0,
                                            numeric_petsc_cast(n_oz.empty() ? nullptr : n_oz.data()));
           LIBMESH_CHKERR(ierr);
 #else
           libmesh_error_msg("PETSc 3.9.4 or higher with hypre is required for MatHypre");
 #endif
           break;
         default: libmesh_error_msg("Unsupported petsc matrix type");
       }
     }
   // Is prefix information available somewhere? Perhaps pass in the system name?
   ierr = MatSetOptionsPrefix(_mat, "");
   LIBMESH_CHKERR(ierr);
   ierr = MatSetFromOptions(_mat);
   LIBMESH_CHKERR(ierr);
   this->zero();
 }
init() [3/3]
template<typename T > void libMesh::PetscMatrix< T >::init () override virtual
Initialize this matrix using the sparsity structure computed by dof_map.
Implements libMesh::SparseMatrix< T >.
Definition at line 348 of file petsc_matrix.C.
References libMesh::libMeshPrivateData::_is_initialized, libMesh::AIJ, libMesh::HYPRE, ierr, libMesh::initialized(), libMesh::numeric_petsc_cast(), and libMesh::zero.
 {
   libmesh_assert(this->_dof_map);
   // Clear initialized matrices
   if (this->initialized())
     this->clear();
   this->_is_initialized = true;
   const numeric_index_type my_m = this->_dof_map->n_dofs();
   const numeric_index_type my_n = my_m;
   const numeric_index_type n_l  = this->_dof_map->n_dofs_on_processor(this->processor_id());
   const numeric_index_type m_l  = n_l;
   const std::vector<numeric_index_type> & n_nz = this->_dof_map->get_n_nz();
   const std::vector<numeric_index_type> & n_oz = this->_dof_map->get_n_oz();
   // Make sure the sparsity pattern isn't empty unless the matrix is 0x0
   libmesh_assert_equal_to (n_nz.size(), m_l);
   libmesh_assert_equal_to (n_oz.size(), m_l);
   PetscErrorCode ierr = 0;
   PetscInt m_global   = static_cast<PetscInt>(my_m);
   PetscInt n_global   = static_cast<PetscInt>(my_n);
   PetscInt m_local    = static_cast<PetscInt>(m_l);
   PetscInt n_local    = static_cast<PetscInt>(n_l);
   ierr = MatCreate(this->comm().get(), &_mat);
   LIBMESH_CHKERR(ierr);
   ierr = MatSetSizes(_mat, m_local, n_local, m_global, n_global);
   LIBMESH_CHKERR(ierr);
 #ifdef LIBMESH_ENABLE_BLOCKED_STORAGE
   PetscInt blocksize  = static_cast<PetscInt>(this->_dof_map->block_size());
   if (blocksize > 1)
     {
       // specified blocksize, bs>1.
       // double check sizes.
       libmesh_assert_equal_to (m_local  % blocksize, 0);
       libmesh_assert_equal_to (n_local  % blocksize, 0);
       libmesh_assert_equal_to (m_global % blocksize, 0);
       libmesh_assert_equal_to (n_global % blocksize, 0);
       ierr = MatSetType(_mat, MATBAIJ); // Automatically chooses seqbaij or mpibaij
       LIBMESH_CHKERR(ierr);
       ierr = MatSetBlockSize(_mat, blocksize);
       LIBMESH_CHKERR(ierr);
       // transform the per-entry n_nz and n_oz arrays into their block counterparts.
       std::vector<numeric_index_type> b_n_nz, b_n_oz;
       transform_preallocation_arrays (blocksize,
                                       n_nz, n_oz,
                                       b_n_nz, b_n_oz);
       ierr = MatSeqBAIJSetPreallocation (_mat,
                                          blocksize,
                                          0,
                                          numeric_petsc_cast(b_n_nz.empty() ? nullptr : b_n_nz.data()));
       LIBMESH_CHKERR(ierr);
       ierr = MatMPIBAIJSetPreallocation (_mat,
                                          blocksize,
                                          0,
                                          numeric_petsc_cast(b_n_nz.empty() ? nullptr : b_n_nz.data()),
                                          0,
                                          numeric_petsc_cast(b_n_oz.empty() ? nullptr : b_n_oz.data()));
       LIBMESH_CHKERR(ierr);
     }
   else
 #endif
     {
       switch (_mat_type) {
         case AIJ:
           ierr = MatSetType(_mat, MATAIJ); // Automatically chooses seqaij or mpiaij
           LIBMESH_CHKERR(ierr);
           ierr = MatSeqAIJSetPreallocation (_mat,
                                             0,
                                             numeric_petsc_cast(n_nz.empty() ? nullptr : n_nz.data()));
           LIBMESH_CHKERR(ierr);
           ierr = MatMPIAIJSetPreallocation (_mat,
                                             0,
                                             numeric_petsc_cast(n_nz.empty() ? nullptr : n_nz.data()),
                                             0,
                                             numeric_petsc_cast(n_oz.empty() ? nullptr : n_oz.data()));
           break;
         case HYPRE:
 #if !PETSC_VERSION_LESS_THAN(3,9,4) && LIBMESH_HAVE_PETSC_HYPRE
           ierr = MatSetType(_mat, MATHYPRE);
           LIBMESH_CHKERR(ierr);
           ierr = MatHYPRESetPreallocation (_mat,
                                            0,
                                            numeric_petsc_cast(n_nz.empty() ? nullptr : n_nz.data()),
                                            0,
                                            numeric_petsc_cast(n_oz.empty() ? nullptr : n_oz.data()));
           LIBMESH_CHKERR(ierr);
 #else
           libmesh_error_msg("PETSc 3.9.4 or higher with hypre is required for MatHypre");
 #endif
           break;
         default: libmesh_error_msg("Unsupported petsc matrix type");
       }
     }
   // Is prefix information available somewhere? Perhaps pass in the system name?
   ierr = MatSetOptionsPrefix(_mat, "");
   LIBMESH_CHKERR(ierr);
   ierr = MatSetFromOptions(_mat);
   LIBMESH_CHKERR(ierr);
   this->zero();
 }
initialized()
template<typename T> virtual bool libMesh::SparseMatrix< T >::initialized () const inline virtual inherited
Returns
true if the matrix has been initialized, false otherwise.
Definition at line 104 of file sparse_matrix.h.
Referenced by libMesh::PetscMatrix< T >::_get_submatrix(), libMesh::ImplicitSystem::assemble(), and libMesh::ImplicitSystem::init_matrices().
 { return _is_initialized; }
l1_norm()
template<typename T > Real libMesh::PetscMatrix< T >::l1_norm () const override virtual
Returns
The -norm of the matrix, that is the max column sum:
This is the natural matrix norm that is compatible with the -norm for vectors, i.e. . (cf. Haemmerlin-Hoffmann : Numerische Mathematik)
Implements libMesh::SparseMatrix< T >.
Definition at line 546 of file petsc_matrix.C.
References libMesh::closed(), ierr, libMesh::initialized(), libMesh::Real, and value.
 {
   libmesh_assert (this->initialized());
   semiparallel_only();
   PetscErrorCode ierr=0;
   PetscReal petsc_value;
   Real value;
   libmesh_assert (this->closed());
   ierr = MatNorm(_mat, NORM_1, &petsc_value);
   LIBMESH_CHKERR(ierr);
   value = static_cast<Real>(petsc_value);
   return value;
 }
linfty_norm()
template<typename T > Real libMesh::PetscMatrix< T >::linfty_norm () const override virtual
Returns
The -norm of the matrix, that is the max row sum:
This is the natural matrix norm that is compatible to the -norm of vectors, i.e. . (cf. Haemmerlin-Hoffmann : Numerische Mathematik)
Implements libMesh::SparseMatrix< T >.
Definition at line 569 of file petsc_matrix.C.
References libMesh::closed(), ierr, libMesh::initialized(), libMesh::Real, and value.
 {
   libmesh_assert (this->initialized());
   semiparallel_only();
   PetscErrorCode ierr=0;
   PetscReal petsc_value;
   Real value;
   libmesh_assert (this->closed());
   ierr = MatNorm(_mat, NORM_INFINITY, &petsc_value);
   LIBMESH_CHKERR(ierr);
   value = static_cast<Real>(petsc_value);
   return value;
 }
m()
template<typename T > numeric_index_type libMesh::PetscMatrix< T >::m () const override virtual
Returns
The row-dimension of the matrix.
Implements libMesh::SparseMatrix< T >.
Definition at line 992 of file petsc_matrix.C.
References ierr, and libMesh::initialized().
 {
   libmesh_assert (this->initialized());
   PetscInt petsc_m=0, petsc_n=0;
   PetscErrorCode ierr=0;
   ierr = MatGetSize (_mat, &petsc_m, &petsc_n);
   LIBMESH_CHKERR(ierr);
   return static_cast<numeric_index_type>(petsc_m);
 }
mat()
template<typename T> Mat libMesh::PetscMatrix< T >::mat () inline
Returns
The raw PETSc matrix pointer.
Note
This is generally not required in user-level code.
Don't do anything crazy like calling LibMeshMatDestroy() on it, or very bad things will likely happen!
Definition at line 247 of file petsc_matrix.h.
References libMesh::PetscMatrix< T >::_mat.
Referenced by libMesh::PetscLinearSolver< T >::adjoint_solve(), libMesh::PetscPreconditioner< T >::init(), libMesh::PetscLinearSolver< T >::init(), libMesh::PetscDiffSolver::solve(), libMesh::TaoOptimizationSolver< T >::solve(), libMesh::PetscNonlinearSolver< Number >::solve(), libMesh::PetscLinearSolver< T >::solve(), libMesh::SlepcEigenSolver< T >::solve_generalized(), and libMesh::SlepcEigenSolver< T >::solve_standard().
 { libmesh_assert (_mat); return _mat; }
n()
template<typename T > numeric_index_type libMesh::PetscMatrix< T >::n () const override virtual
Returns
The column-dimension of the matrix.
Implements libMesh::SparseMatrix< T >.
Definition at line 1008 of file petsc_matrix.C.
References ierr, and libMesh::initialized().
 {
   libmesh_assert (this->initialized());
   PetscInt petsc_m=0, petsc_n=0;
   PetscErrorCode ierr=0;
   ierr = MatGetSize (_mat, &petsc_m, &petsc_n);
   LIBMESH_CHKERR(ierr);
   return static_cast<numeric_index_type>(petsc_n);
 }
n_objects()
static unsigned int libMesh::ReferenceCounter::n_objects () inline static inherited
Prints the number of outstanding (created, but not yet destroyed) objects.
Definition at line 83 of file reference_counter.h.
References libMesh::ReferenceCounter::_n_objects.
   { return _n_objects; }
n_processors()
processor_id_type libMesh::ParallelObject::n_processors () const inline inherited
Returns
The number of processors in the group.
Definition at line 95 of file parallel_object.h.
References libMesh::ParallelObject::_communicator, and libMesh::Parallel::Communicator::size().
Referenced by libMesh::BoundaryInfo::_find_id_maps(), libMesh::PetscDMWrapper::add_dofs_to_section(), libMesh::DistributedMesh::add_elem(), libMesh::DistributedMesh::add_node(), libMesh::LaplaceMeshSmoother::allgather_graph(), libMesh::FEMSystem::assembly(), libMesh::AztecLinearSolver< T >::AztecLinearSolver(), libMesh::BoundaryInfo::build_node_list_from_side_list(), libMesh::EquationSystems::build_parallel_elemental_solution_vector(), libMesh::DistributedMesh::clear(), libMesh::Nemesis_IO_Helper::compute_border_node_ids(), libMesh::Nemesis_IO_Helper::construct_nemesis_filename(), libMesh::UnstructuredMesh::create_pid_mesh(), libMesh::MeshTools::create_processor_bounding_box(), libMesh::DofMap::distribute_dofs(), libMesh::DofMap::distribute_local_dofs_node_major(), libMesh::DofMap::distribute_local_dofs_var_major(), libMesh::EnsightIO::EnsightIO(), libMesh::MeshBase::get_info(), libMesh::SystemSubsetBySubdomain::init(), libMesh::PetscDMWrapper::init_and_attach_petscdm(), libMesh::Nemesis_IO_Helper::initialize(), libMesh::DistributedMesh::insert_elem(), libMesh::MeshTools::libmesh_assert_contiguous_dof_ids(), libMesh::MeshTools::libmesh_assert_parallel_consistent_new_node_procids(), libMesh::MeshTools::libmesh_assert_parallel_consistent_procids< Elem >(), libMesh::MeshTools::libmesh_assert_parallel_consistent_procids< Node >(), libMesh::MeshTools::libmesh_assert_topology_consistent_procids< Node >(), libMesh::MeshTools::libmesh_assert_valid_boundary_ids(), libMesh::MeshTools::libmesh_assert_valid_dof_ids(), libMesh::MeshTools::libmesh_assert_valid_neighbors(), libMesh::MeshTools::libmesh_assert_valid_refinement_flags(), libMesh::DofMap::local_variable_indices(), libMesh::MeshRefinement::make_coarsening_compatible(), libMesh::MeshBase::n_active_elem_on_proc(), libMesh::MeshBase::n_elem_on_proc(), libMesh::MeshBase::n_nodes_on_proc(), libMesh::MeshBase::partition(), libMesh::PetscLinearSolver< T >::PetscLinearSolver(), libMesh::System::point_gradient(), libMesh::System::point_hessian(), libMesh::System::point_value(), libMesh::NameBasedIO::read(), libMesh::Nemesis_IO::read(), libMesh::CheckpointIO::read(), libMesh::CheckpointIO::read_connectivity(), libMesh::XdrIO::read_header(), libMesh::CheckpointIO::read_nodes(), libMesh::System::read_parallel_data(), libMesh::System::read_SCALAR_dofs(), libMesh::System::read_serialized_blocked_dof_objects(), libMesh::System::read_serialized_vector(), libMesh::DistributedMesh::renumber_dof_objects(), libMesh::DofMap::set_nonlocal_dof_objects(), libMesh::PetscDMWrapper::set_point_range_in_section(), libMesh::MeshRefinement::uniformly_coarsen(), libMesh::DistributedMesh::update_parallel_id_counts(), libMesh::GMVIO::write_binary(), libMesh::GMVIO::write_discontinuous_gmv(), libMesh::System::write_parallel_data(), libMesh::System::write_SCALAR_dofs(), libMesh::XdrIO::write_serialized_bcs_helper(), libMesh::System::write_serialized_blocked_dof_objects(), libMesh::XdrIO::write_serialized_connectivity(), libMesh::XdrIO::write_serialized_nodes(), and libMesh::XdrIO::write_serialized_nodesets().
   { return cast_int<processor_id_type>(_communicator.size()); }
need_full_sparsity_pattern()
template<typename T> virtual bool libMesh::SparseMatrix< T >::need_full_sparsity_pattern () const inline virtual inherited
Returns
true if this sparse matrix format needs to be fed the graph of the sparse matrix.
This is true for LaspackMatrix, but not PetscMatrix. In the case where the full graph is not required, we can efficiently approximate it to provide a good estimate of the required size of the sparse matrix.
Reimplemented in libMesh::EpetraMatrix< T >, and libMesh::LaspackMatrix< T >.
Definition at line 121 of file sparse_matrix.h.
Referenced by libMesh::DofMap::attach_matrix().
   { return false; }
operator()()
template<typename T > T libMesh::PetscMatrix< T >::operator() (const numeric_index_type i, const numeric_index_type j) const override virtual
Returns
A copy of matrix entry (i,j).
Note
This may be an expensive operation, and you should always be careful where you call this function.
Implements libMesh::SparseMatrix< T >.
Definition at line 1134 of file petsc_matrix.C.
References libMesh::closed(), ierr, libMesh::initialized(), and value.
 {
   libmesh_assert (this->initialized());
   // PETSc 2.2.1 & newer
   const PetscScalar * petsc_row;
   const PetscInt    * petsc_cols;
   // If the entry is not in the sparse matrix, it is 0.
   T value=0.;
   PetscErrorCode
     ierr=0;
   PetscInt
     ncols=0,
     i_val=static_cast<PetscInt>(i_in),
     j_val=static_cast<PetscInt>(j_in);
   // the matrix needs to be closed for this to work
   // this->close();
   // but closing it is a semiparallel operation; we want operator()
   // to run on one processor.
   libmesh_assert(this->closed());
   ierr = MatGetRow(_mat, i_val, &ncols, &petsc_cols, &petsc_row);
   LIBMESH_CHKERR(ierr);
   // Perform a binary search to find the contiguous index in
   // petsc_cols (resp. petsc_row) corresponding to global index j_val
   std::pair<const PetscInt *, const PetscInt *> p =
     std::equal_range (petsc_cols, petsc_cols + ncols, j_val);
   // Found an entry for j_val
   if (p.first != p.second)
     {
       // The entry in the contiguous row corresponding
       // to the j_val column of interest
       const std::size_t j =
         std::distance (const_cast<PetscInt *>(petsc_cols),
                        const_cast<PetscInt *>(p.first));
       libmesh_assert_less (static_cast<PetscInt>(j), ncols);
       libmesh_assert_equal_to (petsc_cols[j], j_val);
       value = static_cast<T> (petsc_row[j]);
     }
   ierr  = MatRestoreRow(_mat, i_val,
                         &ncols, &petsc_cols, &petsc_row);
   LIBMESH_CHKERR(ierr);
   return value;
 }
operator=() [1/2]
template<typename T> PetscMatrix& libMesh::PetscMatrix< T >::operator= (const PetscMatrix< T > &) delete
operator=() [2/2]
template<typename T> PetscMatrix& libMesh::PetscMatrix< T >::operator= (PetscMatrix< T > &&) delete
print() [1/2]
template<> void libMesh::SparseMatrix< Complex >::print (std::ostream & os, const bool sparse) const inherited
Definition at line 96 of file sparse_matrix.C.
 {
   // std::complex<>::operator<<() is defined, but use this form
   if (sparse)
     {
       libmesh_not_implemented();
     }
   os << "Real part:" << std::endl;
   for (numeric_index_type i=0; i<this->m(); i++)
     {
       for (numeric_index_type j=0; j<this->n(); j++)
         os << std::setw(8) << (*this)(i,j).real() << " ";
       os << std::endl;
     }
   os << std::endl << "Imaginary part:" << std::endl;
   for (numeric_index_type i=0; i<this->m(); i++)
     {
       for (numeric_index_type j=0; j<this->n(); j++)
         os << std::setw(8) << (*this)(i,j).imag() << " ";
       os << std::endl;
     }
 }
print() [2/2]
template<typename T > void libMesh::SparseMatrix< T >::print (std::ostream & os = libMesh::out, const bool sparse = false) const inherited
Print the contents of the matrix to the screen in a uniform style, regardless of matrix/solver package being used.
Definition at line 200 of file sparse_matrix.C.
Referenced by libMesh::EigenSparseMatrix< T >::print_personal(), and libMesh::LaspackMatrix< T >::print_personal().
 {
   parallel_object_only();
   libmesh_assert (this->initialized());
   if (!this->_dof_map)
     libmesh_error_msg("Error!  Trying to print a matrix with no dof_map set!");
   // We'll print the matrix from processor 0 to make sure
   // it's serialized properly
   if (this->processor_id() == 0)
     {
       libmesh_assert_equal_to (this->_dof_map->first_dof(), 0);
       for (numeric_index_type i=this->_dof_map->first_dof();
            i!=this->_dof_map->end_dof(); ++i)
         {
           if (sparse)
             {
               for (numeric_index_type j=0; j<this->n(); j++)
                 {
                   T c = (*this)(i,j);
                   if (c != static_cast<T>(0.0))
                     {
                       os << i << " " << j << " " << c << std::endl;
                     }
                 }
             }
           else
             {
               for (numeric_index_type j=0; j<this->n(); j++)
                 os << (*this)(i,j) << " ";
               os << std::endl;
             }
         }
       std::vector<numeric_index_type> ibuf, jbuf;
       std::vector<T> cbuf;
       numeric_index_type currenti = this->_dof_map->end_dof();
       for (processor_id_type p=1; p < this->n_processors(); ++p)
         {
           this->comm().receive(p, ibuf);
           this->comm().receive(p, jbuf);
           this->comm().receive(p, cbuf);
           libmesh_assert_equal_to (ibuf.size(), jbuf.size());
           libmesh_assert_equal_to (ibuf.size(), cbuf.size());
           if (ibuf.empty())
             continue;
           libmesh_assert_greater_equal (ibuf.front(), currenti);
           libmesh_assert_greater_equal (ibuf.back(), ibuf.front());
           std::size_t currentb = 0;
           for (;currenti <= ibuf.back(); ++currenti)
             {
               if (sparse)
                 {
                   for (numeric_index_type j=0; j<this->n(); j++)
                     {
                       if (currentb < ibuf.size() &&
                           ibuf[currentb] == currenti &&
                           jbuf[currentb] == j)
{
                           os << currenti << " " << j << " " << cbuf[currentb] << std::endl;
                           currentb++;
                         }
                     }
                 }
               else
                 {
                   for (numeric_index_type j=0; j<this->n(); j++)
                     {
                       if (currentb < ibuf.size() &&
                           ibuf[currentb] == currenti &&
                           jbuf[currentb] == j)
{
                           os << cbuf[currentb] << " ";
                           currentb++;
                         }
                       else
                         os << static_cast<T>(0.0) << " ";
                     }
                   os << std::endl;
                 }
             }
         }
       if (!sparse)
         {
           for (; currenti != this->m(); ++currenti)
             {
               for (numeric_index_type j=0; j<this->n(); j++)
                 os << static_cast<T>(0.0) << " ";
               os << std::endl;
             }
         }
     }
   else
     {
       std::vector<numeric_index_type> ibuf, jbuf;
       std::vector<T> cbuf;
       // We'll assume each processor has access to entire
       // matrix rows, so (*this)(i,j) is valid if i is a local index.
       for (numeric_index_type i=this->_dof_map->first_dof();
            i!=this->_dof_map->end_dof(); ++i)
         {
           for (numeric_index_type j=0; j<this->n(); j++)
             {
               T c = (*this)(i,j);
               if (c != static_cast<T>(0.0))
                 {
                   ibuf.push_back(i);
                   jbuf.push_back(j);
                   cbuf.push_back(c);
                 }
             }
         }
       this->comm().send(0,ibuf);
       this->comm().send(0,jbuf);
       this->comm().send(0,cbuf);
     }
 }
print_info()
void libMesh::ReferenceCounter::print_info (std::ostream & out = libMesh::out) static inherited
Prints the reference information, by default to libMesh::out.
Definition at line 87 of file reference_counter.C.
References libMesh::ReferenceCounter::_enable_print_counter, and libMesh::ReferenceCounter::get_info().
 {
   if (_enable_print_counter)
     out_stream << ReferenceCounter::get_info();
 }
print_matlab()
template<typename T > void libMesh::PetscMatrix< T >::print_matlab (const std::string & = "") const override virtual
Print the contents of the matrix in Matlab's sparse matrix format. Optionally prints the matrix to the file named name. If name is not specified it is dumped to the screen.
Create an ASCII file containing the matrix if a filename was provided.
Otherwise the matrix will be dumped to the screen.
Destroy the viewer.
Reimplemented from libMesh::SparseMatrix< T >.
Definition at line 592 of file petsc_matrix.C.
References libMesh::closed(), ierr, libMesh::initialized(), and libMesh::Quality::name().
 {
   libmesh_assert (this->initialized());
   semiparallel_only();
   if (!this->closed())
     {
       libmesh_deprecated();
       libmesh_warning("The matrix must be assembled before calling PetscMatrix::print_matlab().\n"
                       "Please update your code, as this warning will become an error in a future release.");
       const_cast<PetscMatrix<T> *>(this)->close();
     }
   PetscErrorCode ierr=0;
   PetscViewer petsc_viewer;
   ierr = PetscViewerCreate (this->comm().get(),
                             &petsc_viewer);
   LIBMESH_CHKERR(ierr);
   if (name != "")
     {
       ierr = PetscViewerASCIIOpen( this->comm().get(),
                                    name.c_str(),
                                    &petsc_viewer);
       LIBMESH_CHKERR(ierr);
 #if PETSC_VERSION_LESS_THAN(3,7,0)
       ierr = PetscViewerSetFormat (petsc_viewer,
                                    PETSC_VIEWER_ASCII_MATLAB);
 #else
       ierr = PetscViewerPushFormat (petsc_viewer,
                                     PETSC_VIEWER_ASCII_MATLAB);
 #endif
       LIBMESH_CHKERR(ierr);
       ierr = MatView (_mat, petsc_viewer);
       LIBMESH_CHKERR(ierr);
     }
   else
     {
 #if PETSC_VERSION_LESS_THAN(3,7,0)
       ierr = PetscViewerSetFormat (PETSC_VIEWER_STDOUT_WORLD,
                                    PETSC_VIEWER_ASCII_MATLAB);
 #else
       ierr = PetscViewerPushFormat (PETSC_VIEWER_STDOUT_WORLD,
                                     PETSC_VIEWER_ASCII_MATLAB);
 #endif
       LIBMESH_CHKERR(ierr);
       ierr = MatView (_mat, PETSC_VIEWER_STDOUT_WORLD);
       LIBMESH_CHKERR(ierr);
     }
   ierr = LibMeshPetscViewerDestroy (&petsc_viewer);
   LIBMESH_CHKERR(ierr);
 }
print_personal()
template<typename T > void libMesh::PetscMatrix< T >::print_personal (std::ostream & os = libMesh::out) const override virtual
Print the contents of the matrix to the screen with the PETSc viewer. This function only allows printing to standard out since we have limited ourselves to one PETSc implementation for writing.
Implements libMesh::SparseMatrix< T >.
Definition at line 671 of file petsc_matrix.C.
References libMesh::closed(), ierr, and libMesh::initialized().
 {
   libmesh_assert (this->initialized());
   // Routine must be called in parallel on parallel matrices
   // and serial on serial matrices.
   semiparallel_only();
   // #ifndef NDEBUG
   //   if (os != std::cout)
   //     libMesh::err << "Warning! PETSc can only print to std::cout!" << std::endl;
   // #endif
   // Matrix must be in an assembled state to be printed
   if (!this->closed())
     {
       libmesh_deprecated();
       libmesh_warning("The matrix must be assembled before calling PetscMatrix::print_personal().\n"
                       "Please update your code, as this warning will become an error in a future release.");
       const_cast<PetscMatrix<T> *>(this)->close();
     }
   PetscErrorCode ierr=0;
   // Print to screen if ostream is stdout
   if (os.rdbuf() == std::cout.rdbuf())
     {
       ierr = MatView(_mat, PETSC_VIEWER_STDOUT_SELF);
       LIBMESH_CHKERR(ierr);
     }
   // Otherwise, print to the requested file, in a roundabout way...
   else
     {
       // We will create a temporary filename, and file, for PETSc to
       // write to.
       std::string temp_filename;
       {
         // Template for temporary filename
         char c[] = "temp_petsc_matrix.XXXXXX";
         // Generate temporary, unique filename only on processor 0.  We will
         // use this filename for PetscViewerASCIIOpen, before copying it into
         // the user's stream
         if (this->processor_id() == 0)
           {
             int fd = mkstemp(c);
             // Check to see that mkstemp did not fail.
             if (fd == -1)
               libmesh_error_msg("mkstemp failed in PetscMatrix::print_personal()");
             // mkstemp returns a file descriptor for an open file,
             // so let's close it before we hand it to PETSc!
             ::close (fd);
           }
         // Store temporary filename as string, makes it easier to broadcast
         temp_filename = c;
       }
       // Now broadcast the filename from processor 0 to all processors.
       this->comm().broadcast(temp_filename);
       // PetscViewer object for passing to MatView
       PetscViewer petsc_viewer;
       // This PETSc function only takes a string and handles the opening/closing
       // of the file internally.  Since print_personal() takes a reference to
       // an ostream, we have to do an extra step...  print_personal() should probably
       // have a version that takes a string to get rid of this problem.
       ierr = PetscViewerASCIIOpen( this->comm().get(),
                                    temp_filename.c_str(),
                                    &petsc_viewer);
       LIBMESH_CHKERR(ierr);
       // Probably don't need to set the format if it's default...
       //      ierr = PetscViewerSetFormat (petsc_viewer,
       //   PETSC_VIEWER_DEFAULT);
       //      LIBMESH_CHKERR(ierr);
       // Finally print the matrix using the viewer
       ierr = MatView (_mat, petsc_viewer);
       LIBMESH_CHKERR(ierr);
       if (this->processor_id() == 0)
         {
           // Now the inefficient bit: open temp_filename as an ostream and copy the contents
           // into the user's desired ostream.  We can't just do a direct file copy, we don't even have the filename!
           std::ifstream input_stream(temp_filename.c_str());
           os << input_stream.rdbuf();  // The "most elegant" way to copy one stream into another.
           // os.close(); // close not defined in ostream
           // Now remove the temporary file
           input_stream.close();
           std::remove(temp_filename.c_str());
         }
     }
 }
processor_id()
processor_id_type libMesh::ParallelObject::processor_id () const inline inherited
Returns
The rank of this processor in the group.
Definition at line 101 of file parallel_object.h.
References libMesh::ParallelObject::_communicator, and libMesh::Parallel::Communicator::rank().
Referenced by libMesh::BoundaryInfo::_find_id_maps(), libMesh::EquationSystems::_read_impl(), libMesh::PetscDMWrapper::add_dofs_to_section(), libMesh::DistributedMesh::add_elem(), libMesh::BoundaryInfo::add_elements(), libMesh::DofMap::add_neighbors_to_send_list(), libMesh::DistributedMesh::add_node(), libMesh::UnstructuredMesh::all_second_order(), libMesh::MeshTools::Modification::all_tri(), libMesh::FEMSystem::assembly(), libMesh::EquationSystems::build_discontinuous_solution_vector(), libMesh::Nemesis_IO_Helper::build_element_and_node_maps(), libMesh::InfElemBuilder::build_inf_elem(), libMesh::BoundaryInfo::build_node_list_from_side_list(), libMesh::EquationSystems::build_parallel_elemental_solution_vector(), libMesh::DistributedMesh::clear(), libMesh::ExodusII_IO_Helper::close(), libMesh::Nemesis_IO_Helper::compute_border_node_ids(), libMesh::Nemesis_IO_Helper::compute_communication_map_parameters(), libMesh::Nemesis_IO_Helper::compute_internal_and_border_elems_and_internal_nodes(), libMesh::Nemesis_IO_Helper::compute_node_communication_maps(), libMesh::Nemesis_IO_Helper::compute_num_global_elem_blocks(), libMesh::Nemesis_IO_Helper::compute_num_global_nodesets(), libMesh::Nemesis_IO_Helper::compute_num_global_sidesets(), libMesh::Nemesis_IO_Helper::construct_nemesis_filename(), libMesh::MeshTools::correct_node_proc_ids(), libMesh::ExodusII_IO_Helper::create(), libMesh::DistributedMesh::delete_elem(), libMesh::DistributedMesh::delete_node(), libMesh::MeshCommunication::delete_remote_elements(), libMesh::DofMap::distribute_dofs(), libMesh::DofMap::distribute_local_dofs_node_major(), libMesh::DofMap::distribute_local_dofs_var_major(), libMesh::DistributedMesh::DistributedMesh(), libMesh::DofMap::end_dof(), libMesh::DofMap::end_old_dof(), libMesh::EnsightIO::EnsightIO(), libMesh::MeshFunction::find_element(), libMesh::MeshFunction::find_elements(), libMesh::UnstructuredMesh::find_neighbors(), libMesh::DofMap::first_dof(), libMesh::DofMap::first_old_dof(), libMesh::Nemesis_IO_Helper::get_cmap_params(), libMesh::Nemesis_IO_Helper::get_eb_info_global(), libMesh::Nemesis_IO_Helper::get_elem_cmap(), libMesh::Nemesis_IO_Helper::get_elem_map(), libMesh::MeshBase::get_info(), libMesh::DofMap::get_info(), libMesh::Nemesis_IO_Helper::get_init_global(), libMesh::Nemesis_IO_Helper::get_init_info(), libMesh::Nemesis_IO_Helper::get_loadbal_param(), libMesh::Nemesis_IO_Helper::get_node_cmap(), libMesh::Nemesis_IO_Helper::get_node_map(), libMesh::Nemesis_IO_Helper::get_ns_param_global(), libMesh::Nemesis_IO_Helper::get_ss_param_global(), libMesh::SparsityPattern::Build::handle_vi_vj(), libMesh::SystemSubsetBySubdomain::init(), libMesh::ExodusII_IO_Helper::initialize(), libMesh::ExodusII_IO_Helper::initialize_element_variables(), libMesh::ExodusII_IO_Helper::initialize_global_variables(), libMesh::ExodusII_IO_Helper::initialize_nodal_variables(), libMesh::DistributedMesh::insert_elem(), libMesh::DofMap::is_evaluable(), libMesh::SparsityPattern::Build::join(), libMesh::DofMap::last_dof(), libMesh::MeshTools::libmesh_assert_consistent_distributed(), libMesh::MeshTools::libmesh_assert_consistent_distributed_nodes(), libMesh::MeshTools::libmesh_assert_contiguous_dof_ids(), libMesh::MeshTools::libmesh_assert_parallel_consistent_procids< Elem >(), libMesh::MeshTools::libmesh_assert_valid_neighbors(), libMesh::DistributedMesh::libmesh_assert_valid_parallel_object_ids(), libMesh::DofMap::local_variable_indices(), libMesh::MeshRefinement::make_coarsening_compatible(), libMesh::MeshBase::n_active_local_elem(), libMesh::BoundaryInfo::n_boundary_conds(), libMesh::BoundaryInfo::n_edge_conds(), libMesh::DofMap::n_local_dofs(), libMesh::System::n_local_dofs(), libMesh::MeshBase::n_local_elem(), libMesh::MeshBase::n_local_nodes(), libMesh::BoundaryInfo::n_nodeset_conds(), libMesh::BoundaryInfo::n_shellface_conds(), libMesh::SparsityPattern::Build::operator()(), libMesh::DistributedMesh::own_node(), libMesh::System::point_gradient(), libMesh::System::point_hessian(), libMesh::System::point_value(), libMesh::Nemesis_IO_Helper::put_cmap_params(), libMesh::Nemesis_IO_Helper::put_elem_cmap(), libMesh::Nemesis_IO_Helper::put_elem_map(), libMesh::Nemesis_IO_Helper::put_loadbal_param(), libMesh::Nemesis_IO_Helper::put_node_cmap(), libMesh::Nemesis_IO_Helper::put_node_map(), libMesh::NameBasedIO::read(), libMesh::Nemesis_IO::read(), libMesh::XdrIO::read(), libMesh::CheckpointIO::read(), libMesh::ExodusII_IO_Helper::read_elem_num_map(), libMesh::ExodusII_IO_Helper::read_global_values(), libMesh::CheckpointIO::read_header(), libMesh::XdrIO::read_header(), libMesh::System::read_header(), libMesh::System::read_legacy_data(), libMesh::ExodusII_IO_Helper::read_node_num_map(), libMesh::System::read_parallel_data(), libMesh::System::read_SCALAR_dofs(), libMesh::XdrIO::read_serialized_bc_names(), libMesh::XdrIO::read_serialized_bcs_helper(), libMesh::System::read_serialized_blocked_dof_objects(), libMesh::XdrIO::read_serialized_connectivity(), libMesh::System::read_serialized_data(), libMesh::XdrIO::read_serialized_nodes(), libMesh::XdrIO::read_serialized_nodesets(), libMesh::XdrIO::read_serialized_subdomain_names(), libMesh::System::read_serialized_vector(), libMesh::System::read_serialized_vectors(), libMesh::DistributedMesh::renumber_dof_objects(), libMesh::CheckpointIO::select_split_config(), libMesh::DofMap::set_nonlocal_dof_objects(), libMesh::PetscDMWrapper::set_point_range_in_section(), libMesh::LaplaceMeshSmoother::smooth(), libMesh::MeshTools::total_weight(), libMesh::MeshRefinement::uniformly_coarsen(), libMesh::Parallel::Packing< T >::unpack(), libMesh::DistributedMesh::update_parallel_id_counts(), libMesh::NameBasedIO::write(), libMesh::XdrIO::write(), libMesh::CheckpointIO::write(), libMesh::EquationSystems::write(), libMesh::GMVIO::write_discontinuous_gmv(), libMesh::ExodusII_IO::write_element_data(), libMesh::ExodusII_IO_Helper::write_element_values(), libMesh::ExodusII_IO_Helper::write_elements(), libMesh::ExodusII_IO::write_global_data(), libMesh::ExodusII_IO_Helper::write_global_values(), libMesh::System::write_header(), libMesh::ExodusII_IO::write_information_records(), libMesh::ExodusII_IO_Helper::write_information_records(), libMesh::ExodusII_IO_Helper::write_nodal_coordinates(), libMesh::UCDIO::write_nodal_data(), libMesh::ExodusII_IO::write_nodal_data(), libMesh::ExodusII_IO::write_nodal_data_discontinuous(), libMesh::ExodusII_IO_Helper::write_nodal_values(), libMesh::Nemesis_IO_Helper::write_nodesets(), libMesh::ExodusII_IO_Helper::write_nodesets(), libMesh::System::write_parallel_data(), libMesh::System::write_SCALAR_dofs(), libMesh::XdrIO::write_serialized_bc_names(), libMesh::XdrIO::write_serialized_bcs_helper(), libMesh::System::write_serialized_blocked_dof_objects(), libMesh::XdrIO::write_serialized_connectivity(), libMesh::System::write_serialized_data(), libMesh::XdrIO::write_serialized_nodes(), libMesh::XdrIO::write_serialized_nodesets(), libMesh::XdrIO::write_serialized_subdomain_names(), libMesh::System::write_serialized_vector(), libMesh::System::write_serialized_vectors(), libMesh::Nemesis_IO_Helper::write_sidesets(), libMesh::ExodusII_IO_Helper::write_sidesets(), libMesh::ExodusII_IO::write_timestep(), libMesh::ExodusII_IO_Helper::write_timestep(), and libMesh::ExodusII_IO::write_timestep_discontinuous().
   { return cast_int<processor_id_type>(_communicator.rank()); }
reinit_submatrix()
template<typename T> virtual void libMesh::SparseMatrix< T >::reinit_submatrix (SparseMatrix< T > & submatrix, const std::vector< numeric_index_type > & rows, const std::vector< numeric_index_type > & cols) const inline virtual inherited
This function is similar to the one above, but it allows you to reuse the existing sparsity pattern of "submatrix" instead of reallocating it again. This should hopefully be more efficient if you are frequently extracting submatrices of the same size.
Definition at line 370 of file sparse_matrix.h.
   {
     this->_get_submatrix(submatrix,
                          rows,
                          cols,
                          true); // true means REUSE submatrix
   }
row_start()
template<typename T > numeric_index_type libMesh::PetscMatrix< T >::row_start () const override virtual
Returns
The index of the first matrix row stored on this processor.
Implements libMesh::SparseMatrix< T >.
Definition at line 1024 of file petsc_matrix.C.
References ierr, libMesh::initialized(), and libMesh::MacroFunctions::stop().
 {
   libmesh_assert (this->initialized());
   PetscInt start=0, stop=0;
   PetscErrorCode ierr=0;
   ierr = MatGetOwnershipRange(_mat, &start, &stop);
   LIBMESH_CHKERR(ierr);
   return static_cast<numeric_index_type>(start);
 }
row_stop()
template<typename T > numeric_index_type libMesh::PetscMatrix< T >::row_stop () const override virtual
Returns
The index of the last matrix row (+1) stored on this processor.
Implements libMesh::SparseMatrix< T >.
Definition at line 1040 of file petsc_matrix.C.
References ierr, libMesh::initialized(), and libMesh::MacroFunctions::stop().
 {
   libmesh_assert (this->initialized());
   PetscInt start=0, stop=0;
   PetscErrorCode ierr=0;
   ierr = MatGetOwnershipRange(_mat, &start, &stop);
   LIBMESH_CHKERR(ierr);
   return static_cast<numeric_index_type>(stop);
 }
set()
template<typename T > void libMesh::PetscMatrix< T >::set (const numeric_index_type i, const numeric_index_type j, const T value) override virtual
Set the element (i,j) to value. Throws an error if the entry does not exist. Zero values can be "stored" in non-existent fields.
Implements libMesh::SparseMatrix< T >.
Definition at line 1056 of file petsc_matrix.C.
References ierr, libMesh::initialized(), and value.
 {
   libmesh_assert (this->initialized());
   PetscErrorCode ierr=0;
   PetscInt i_val=i, j_val=j;
   PetscScalar petsc_value = static_cast<PetscScalar>(value);
   ierr = MatSetValues(_mat, 1, &i_val, 1, &j_val,
                       &petsc_value, INSERT_VALUES);
   LIBMESH_CHKERR(ierr);
 }
set_matrix_type()
template<typename T > void libMesh::PetscMatrix< T >::set_matrix_type (PetscMatrixType mat_type)
Definition at line 121 of file petsc_matrix.C.
 {
   _mat_type = mat_type;
 }
swap()
template<typename T > void libMesh::PetscMatrix< T >::swap (PetscMatrix< T > & m_in)
Swaps the internal data pointers of two PetscMatrices, no actual values are swapped.
Definition at line 1210 of file petsc_matrix.C.
References libMesh::PetscMatrix< T >::_destroy_mat_on_exit, libMesh::PetscMatrix< T >::_mat, and swap().
Referenced by libMesh::__libmesh_petsc_diff_solver_jacobian().
 {
   std::swap(_mat, m_in._mat);
   std::swap(_destroy_mat_on_exit, m_in._destroy_mat_on_exit);
 }
update_preallocation_and_zero()
template<typename T > void libMesh::PetscMatrix< T >::update_preallocation_and_zero ()
Update the sparsity pattern based on dof_map, and set the matrix to zero. This is useful in cases where the sparsity pattern changes during a computation.
Definition at line 468 of file petsc_matrix.C.
 {
   libmesh_not_implemented();
 }
update_sparsity_pattern()
template<typename T> virtual void libMesh::SparseMatrix< T >::update_sparsity_pattern (const SparsityPattern::Graph &) inline virtual inherited
Updates the matrix sparsity pattern. When your SparseMatrix<T> implementation does not need this data, simply do not override this method.
Reimplemented in libMesh::EpetraMatrix< T >, and libMesh::LaspackMatrix< T >.
Definition at line 129 of file sparse_matrix.h.
Referenced by libMesh::DofMap::attach_matrix().
 {}
vector_mult()
template<typename T> void libMesh::SparseMatrix< T >::vector_mult (NumericVector< T > & dest, const NumericVector< T > & arg) const inherited
Multiplies the matrix by the NumericVector arg and stores the result in NumericVector dest.
Definition at line 170 of file sparse_matrix.C.
Referenced by libMesh::ImplicitSystem::qoi_parameter_hessian(), and libMesh::ImplicitSystem::qoi_parameter_hessian_vector_product().
 {
   dest.zero();
   this->vector_mult_add(dest,arg);
 }
vector_mult_add()
template<typename T> void libMesh::SparseMatrix< T >::vector_mult_add (NumericVector< T > & dest, const NumericVector< T > & arg) const inherited
Multiplies the matrix by the NumericVector arg and adds the result to the NumericVector dest.
Definition at line 180 of file sparse_matrix.C.
Referenced by libMesh::ImplicitSystem::weighted_sensitivity_adjoint_solve().
 {
   /* This functionality is actually implemented in the \p
      NumericVector class.  */
   dest.add_vector(arg,*this);
 }
zero()
template<typename T > void libMesh::PetscMatrix< T >::zero () override virtual
Set all entries to 0.
Implements libMesh::SparseMatrix< T >.
Definition at line 475 of file petsc_matrix.C.
References ierr, and libMesh::initialized().
 {
   libmesh_assert (this->initialized());
   semiparallel_only();
   PetscErrorCode ierr=0;
   PetscInt m_l, n_l;
   ierr = MatGetLocalSize(_mat,&m_l,&n_l);
   LIBMESH_CHKERR(ierr);
   if (n_l)
     {
       ierr = MatZeroEntries(_mat);
       LIBMESH_CHKERR(ierr);
     }
 }
zero_rows()
template<typename T > void libMesh::PetscMatrix< T >::zero_rows (std::vector< numeric_index_type > & rows, T diag_value = 0.0) override virtual
Sets all row entries to 0 then puts diag_value in the diagonal entry.
Reimplemented from libMesh::SparseMatrix< T >.
Definition at line 496 of file petsc_matrix.C.
References ierr, libMesh::initialized(), and libMesh::numeric_petsc_cast().
 {
   libmesh_assert (this->initialized());
   semiparallel_only();
   PetscErrorCode ierr=0;
 #if PETSC_RELEASE_LESS_THAN(3,1,1)
   if (!rows.empty())
     ierr = MatZeroRows(_mat, rows.size(),
                        numeric_petsc_cast(rows.data()), diag_value);
   else
     ierr = MatZeroRows(_mat, 0, PETSC_NULL, diag_value);
 #else
   // As of petsc-dev at the time of 3.1.0, MatZeroRows now takes two additional
   // optional arguments.  The optional arguments (x,b) can be used to specify the
   // solutions for the zeroed rows (x) and right hand side (b) to update.
   // Could be useful for setting boundary conditions...
   if (!rows.empty())
     ierr = MatZeroRows(_mat, cast_int<PetscInt>(rows.size()),
                        numeric_petsc_cast(rows.data()), diag_value,
                        PETSC_NULL, PETSC_NULL);
   else
     ierr = MatZeroRows(_mat, 0, PETSC_NULL, diag_value, PETSC_NULL,
                        PETSC_NULL);
 #endif
   LIBMESH_CHKERR(ierr);
 }
Member Data Documentation
_communicator
const Parallel::Communicator& libMesh::ParallelObject::_communicator protected inherited
Definition at line 107 of file parallel_object.h.
Referenced by libMesh::EquationSystems::build_parallel_elemental_solution_vector(), libMesh::EquationSystems::build_parallel_solution_vector(), libMesh::ParallelObject::comm(), libMesh::ParallelObject::n_processors(), libMesh::ParallelObject::operator=(), and libMesh::ParallelObject::processor_id().
_counts
ReferenceCounter::Counts libMesh::ReferenceCounter::_counts static protected inherited
Actually holds the data.
Definition at line 122 of file reference_counter.h.
Referenced by libMesh::ReferenceCounter::get_info(), libMesh::ReferenceCounter::increment_constructor_count(), and libMesh::ReferenceCounter::increment_destructor_count().
_destroy_mat_on_exit
template<typename T> bool libMesh::PetscMatrix< T >::_destroy_mat_on_exit private
This boolean value should only be set to false for the constructor which takes a PETSc Mat object.
Definition at line 277 of file petsc_matrix.h.
Referenced by libMesh::PetscMatrix< T >::swap().
_dof_map
template<typename T> DofMap const* libMesh::SparseMatrix< T >::_dof_map protected inherited
The DofMap object associated with this object.
Definition at line 425 of file sparse_matrix.h.
Referenced by libMesh::SparseMatrix< ValOut >::attach_dof_map().
_enable_print_counter
bool libMesh::ReferenceCounter::_enable_print_counter = true static protected inherited
Flag to control whether reference count information is printed when print_info is called.
Definition at line 141 of file reference_counter.h.
Referenced by libMesh::ReferenceCounter::disable_print_counter_info(), libMesh::ReferenceCounter::enable_print_counter_info(), and libMesh::ReferenceCounter::print_info().
_is_initialized
template<typename T> bool libMesh::SparseMatrix< T >::_is_initialized protected inherited
Flag indicating whether or not the matrix has been initialized.
Definition at line 430 of file sparse_matrix.h.
Referenced by libMesh::PetscMatrix< T >::_get_submatrix(), libMesh::EpetraMatrix< T >::EpetraMatrix(), libMesh::PetscMatrix< T >::get_transpose(), libMesh::SparseMatrix< ValOut >::initialized(), and libMesh::PetscMatrix< T >::PetscMatrix().
_mat
template<typename T> Mat libMesh::PetscMatrix< T >::_mat private
PETSc matrix datatype to store values.
Definition at line 271 of file petsc_matrix.h.
Referenced by libMesh::PetscMatrix< T >::_get_submatrix(), libMesh::PetscMatrix< T >::add(), libMesh::PetscMatrix< T >::get_transpose(), libMesh::PetscMatrix< T >::mat(), libMesh::PetscMatrix< T >::PetscMatrix(), and libMesh::PetscMatrix< T >::swap().
_mat_type
template<typename T> PetscMatrixType libMesh::PetscMatrix< T >::_mat_type private
Definition at line 279 of file petsc_matrix.h.
_mutex
Threads::spin_mutex libMesh::ReferenceCounter::_mutex static protected inherited
Mutual exclusion object to enable thread-safe reference counting.
Definition at line 135 of file reference_counter.h.
_n_objects
Threads::atomic< unsigned int > libMesh::ReferenceCounter::_n_objects static protected inherited
The number of objects. Print the reference count information when the number returns to 0.
Definition at line 130 of file reference_counter.h.
Referenced by libMesh::ReferenceCounter::n_objects(), libMesh::ReferenceCounter::ReferenceCounter(), and libMesh::ReferenceCounter::~ReferenceCounter().
The documentation for this class was generated from the following files:
petsc_linear_solver.h
petsc_matrix.h
petsc_matrix.C