libMesh: libMesh::NewmarkSolver Class Reference
SomeWebsiteLogo
libMesh::NewmarkSolver Class Reference
#include <newmark_solver.h>
Public Types
typedef UnsteadySolver Parent
typedef DifferentiableSystem sys_type
Public Member Functions
NewmarkSolver (sys_type &s)
virtual ~NewmarkSolver ()
virtual void advance_timestep () libmesh_override
virtual void adjoint_advance_timestep () libmesh_override
virtual void compute_initial_accel ()
void project_initial_accel (FunctionBase< Number > *f, FunctionBase< Gradient > *g=libmesh_nullptr)
void set_initial_accel_avail (bool initial_accel_set)
virtual Real error_order () const libmesh_override
virtual void solve () libmesh_override
virtual bool element_residual (bool request_jacobian, DiffContext &) libmesh_override
virtual bool side_residual (bool request_jacobian, DiffContext &) libmesh_override
virtual bool nonlocal_residual (bool request_jacobian, DiffContext &) libmesh_override
void set_beta (Real beta)
void set_gamma (Real gamma)
virtual unsigned int time_order () const libmesh_override
virtual void init () libmesh_override
virtual void init_data () libmesh_override
virtual void reinit () libmesh_override
virtual void retrieve_timestep () libmesh_override
void project_initial_rate (FunctionBase< Number > *f, FunctionBase< Gradient > *g=libmesh_nullptr)
Number old_solution_rate (const dof_id_type global_dof_number) const
Number old_solution_accel (const dof_id_type global_dof_number) const
Number old_nonlinear_solution (const dof_id_type global_dof_number) const
virtual Real du (const SystemNorm &norm) const libmesh_override
virtual bool is_steady () const libmesh_override
virtual void before_timestep ()
const sys_type & system () const
sys_type & system ()
virtual UniquePtr< DiffSolver > & diff_solver ()
virtual UniquePtr< LinearSolver< Number > > & linear_solver ()
void set_solution_history (const SolutionHistory &_solution_history)
bool is_adjoint () const
void set_is_adjoint (bool _is_adjoint_value)
Static Public Member Functions
static std::string get_info ()
static void print_info (std::ostream &out=libMesh::out)
static unsigned int n_objects ()
static void enable_print_counter_info ()
static void disable_print_counter_info ()
Public Attributes
UniquePtr< NumericVector< Number > > old_local_nonlinear_solution
bool quiet
unsigned int reduce_deltat_on_diffsolver_failure
Protected Types
typedef bool(DifferentiablePhysics::* ResFuncType) (bool, DiffContext &)
typedef void(DiffContext::* ReinitFuncType) (Real)
typedef std::map< std::string, std::pair< unsigned int, unsigned int > > Counts
Protected Member Functions
virtual bool _general_residual (bool request_jacobian, DiffContext &, ResFuncType mass, ResFuncType damping, ResFuncType time_deriv, ResFuncType constraint, ReinitFuncType reinit)
void increment_constructor_count (const std::string &name)
void increment_destructor_count (const std::string &name)
Protected Attributes
Real _beta
Real _gamma
bool _is_accel_solve
bool _initial_accel_set
UniquePtr< NumericVector< Number > > _old_local_solution_rate
UniquePtr< NumericVector< Number > > _old_local_solution_accel
bool first_solve
bool first_adjoint_step
UniquePtr< DiffSolver > _diff_solver
UniquePtr< LinearSolver< Number > > _linear_solver
sys_type & _system
UniquePtr< SolutionHistory > solution_history
Static Protected Attributes
static Counts _counts
static Threads::atomic< unsigned int > _n_objects
static Threads::spin_mutex _mutex
static bool _enable_print_counter = true
Detailed Description
This class defines a Newmark time integrator for second order (in time) DifferentiableSystems. There are two parameters and (defaulting to 0.5 and 0.25, respectively).
Note
Projectors are included for the initial velocity and acceleration; the initial displacement can be set by calling System::project_solution().
This class is part of the new DifferentiableSystem framework, which is still experimental. Users of this framework should beware of bugs and future API changes.
Author
Paul T. Bauman
Date
2015
Definition at line 46 of file newmark_solver.h.
Member Typedef Documentation
typedef std::map<std::string, std::pair<unsigned int, unsigned int> > libMesh::ReferenceCounter::Counts protected inherited
Data structure to log the information. The log is identified by the class name.
Definition at line 119 of file reference_counter.h.
typedef UnsteadySolver libMesh::NewmarkSolver::Parent
The parent class
Definition at line 52 of file newmark_solver.h.
typedef void(DiffContext::* libMesh::TimeSolver::ReinitFuncType) (Real) protected inherited
Definition at line 272 of file time_solver.h.
typedef bool(DifferentiablePhysics::* libMesh::TimeSolver::ResFuncType) (bool, DiffContext &) protected inherited
Definitions of argument types for use in refactoring subclasses.
Definition at line 270 of file time_solver.h.
typedef DifferentiableSystem libMesh::TimeSolver::sys_type inherited
The type of system
Definition at line 64 of file time_solver.h.
Constructor & Destructor Documentation
libMesh::NewmarkSolver::NewmarkSolver (sys_type & s) explicit
Constructor. Requires a reference to the system to be solved.
Definition at line 25 of file newmark_solver.C.
   : SecondOrderUnsteadySolver(s),
     _beta(0.25),
     _gamma(0.5),
     _is_accel_solve(false),
     _initial_accel_set(false)
 {}
libMesh::NewmarkSolver::~NewmarkSolver () virtual
Destructor.
Definition at line 33 of file newmark_solver.C.
 {}
Member Function Documentation
bool libMesh::NewmarkSolver::_general_residual (bool request_jacobian, DiffContext & context, ResFuncType mass, ResFuncType damping, ResFuncType time_deriv, ResFuncType constraint, ReinitFuncType reinit) protected virtual
This method is the underlying implementation of the public residual methods.
Definition at line 205 of file newmark_solver.C.
References _beta, _gamma, _is_accel_solve, libMesh::TimeSolver::_system, libMesh::DenseVector< T >::add(), libMesh::DifferentiableSystem::deltat, libMesh::DiffContext::elem_solution_accel_derivative, libMesh::DiffContext::elem_solution_derivative, libMesh::DiffContext::elem_solution_rate_derivative, libMesh::DiffContext::get_dof_indices(), libMesh::DiffContext::get_elem_fixed_solution(), libMesh::DiffContext::get_elem_jacobian(), libMesh::DiffContext::get_elem_solution(), libMesh::DiffContext::get_elem_solution_accel(), libMesh::DiffContext::get_elem_solution_rate(), libMesh::DifferentiableSystem::get_physics(), libMesh::UnsteadySolver::old_nonlinear_solution(), libMesh::SecondOrderUnsteadySolver::old_solution_accel(), libMesh::SecondOrderUnsteadySolver::old_solution_rate(), libMesh::Real, libMesh::DenseVector< T >::size(), libMesh::DenseMatrix< T >::swap(), and libMesh::System::use_fixed_solution.
Referenced by element_residual(), nonlocal_residual(), and side_residual().
 {
   unsigned int n_dofs = context.get_elem_solution().size();
   // We might need to save the old jacobian in case one of our physics
   // terms later is unable to update it analytically.
   DenseMatrix<Number> old_elem_jacobian(n_dofs, n_dofs);
   // Local velocity at old time step
   DenseVector<Number> old_elem_solution_rate(n_dofs);
   for (unsigned int i=0; i != n_dofs; ++i)
     old_elem_solution_rate(i) =
       old_solution_rate(context.get_dof_indices()[i]);
   // The user is computing the initial acceleration
   // So upstream we've swapped _system.solution and _old_local_solution_accel
   // So we need to give the context the correct entries since we're solving for
   // acceleration here.
   if (_is_accel_solve)
     {
       // System._solution is actually the acceleration right now so we need
       // to reset the elem_solution to the right thing, which in this case
       // is the initial guess for displacement, which got swapped into
       // _old_solution_accel vector
       DenseVector<Number> old_elem_solution(n_dofs);
       for (unsigned int i=0; i != n_dofs; ++i)
         old_elem_solution(i) =
           old_solution_accel(context.get_dof_indices()[i]);
       context.elem_solution_derivative = 0.0;
       context.elem_solution_rate_derivative = 0.0;
       context.elem_solution_accel_derivative = 1.0;
       // Acceleration is currently the unknown so it's already sitting
       // in elem_solution() thanks to FEMContext::pre_fe_reinit
       context.get_elem_solution_accel() = context.get_elem_solution();
       // Now reset elem_solution() to what the user is expecting
       context.get_elem_solution() = old_elem_solution;
       context.get_elem_solution_rate() = old_elem_solution_rate;
       // The user's Jacobians will be targeting derivatives w.r.t. u_{n+1}.
       // Although the vast majority of cases will have the correct analytic
       // Jacobians in this iteration, since we reset elem_solution_derivative*,
       // if there are coupled/overlapping problems, there could be
       // mismatches in the Jacobian. So we force finite differencing for
       // the first iteration.
       request_jacobian = false;
     }
   // Otherwise, the unknowns are the displacements and everything is straight
   // foward and is what you think it is
   else
     {
       if (request_jacobian)
         old_elem_jacobian.swap(context.get_elem_jacobian());
       // Local displacement at old timestep
       DenseVector<Number> old_elem_solution(n_dofs);
       for (unsigned int i=0; i != n_dofs; ++i)
         old_elem_solution(i) =
           old_nonlinear_solution(context.get_dof_indices()[i]);
       // Local acceleration at old time step
       DenseVector<Number> old_elem_solution_accel(n_dofs);
       for (unsigned int i=0; i != n_dofs; ++i)
         old_elem_solution_accel(i) =
           old_solution_accel(context.get_dof_indices()[i]);
       // Convenience
       libMesh::Real dt = _system.deltat;
       context.elem_solution_derivative = 1.0;
       // Local velocity at current time step
       // v_{n+1} = gamma/(beta*Delta t)*(x_{n+1}-x_n)
       //         + (1-(gamma/beta))*v_n
       //         + (1-gamma/(2*beta))*(Delta t)*a_n
       context.elem_solution_rate_derivative = (_gamma/(_beta*dt));
       context.get_elem_solution_rate()  = context.get_elem_solution();
       context.get_elem_solution_rate() -= old_elem_solution;
       context.get_elem_solution_rate() *= context.elem_solution_rate_derivative;
       context.get_elem_solution_rate().add( (1.0-_gamma/_beta), old_elem_solution_rate);
       context.get_elem_solution_rate().add( (1.0-_gamma/(2.0*_beta))*dt, old_elem_solution_accel);
       // Local acceleration at current time step
       // a_{n+1} = (1/(beta*(Delta t)^2))*(x_{n+1}-x_n)
       //         - 1/(beta*Delta t)*v_n
       //         - (1/(2*beta)-1)*a_n
       context.elem_solution_accel_derivative = 1.0/(_beta*dt*dt);
       context.get_elem_solution_accel()  = context.get_elem_solution();
       context.get_elem_solution_accel() -= old_elem_solution;
       context.get_elem_solution_accel() *= context.elem_solution_accel_derivative;
       context.get_elem_solution_accel().add(-1.0/(_beta*dt), old_elem_solution_rate);
       context.get_elem_solution_accel().add(-(1.0/(2.0*_beta)-1.0), old_elem_solution_accel);
       // Move the mesh into place first if necessary, set t = t_{n+1}
       (context.*reinit_func)(1.);
     }
   // If a fixed solution is requested, we'll use x_{n+1}
   if (_system.use_fixed_solution)
     context.get_elem_fixed_solution() = context.get_elem_solution();
   // Get the time derivative at t_{n+1}, F(u_{n+1})
   bool jacobian_computed = (_system.get_physics()->*time_deriv)(request_jacobian, context);
   // Damping at t_{n+1}, C(u_{n+1})
   jacobian_computed = (_system.get_physics()->*damping)(jacobian_computed, context) &&
     jacobian_computed;
   // Mass at t_{n+1}, M(u_{n+1})
   jacobian_computed = (_system.get_physics()->*mass)(jacobian_computed, context) &&
     jacobian_computed;
   // Add the constraint term
   jacobian_computed = (_system.get_physics()->*constraint)(jacobian_computed, context) &&
     jacobian_computed;
   // Add back (or restore) the old jacobian
   if (request_jacobian)
     {
       if (jacobian_computed)
         context.get_elem_jacobian() += old_elem_jacobian;
       else
         context.get_elem_jacobian().swap(old_elem_jacobian);
     }
   return jacobian_computed;
 }
void libMesh::NewmarkSolver::adjoint_advance_timestep () virtual
This method advances the adjoint solution to the previous timestep, after an adjoint_solve() has been performed. This will be done before every UnsteadySolver::adjoint_solve().
Reimplemented from libMesh::UnsteadySolver.
Definition at line 101 of file newmark_solver.C.
 {
   libmesh_not_implemented();
 }
void libMesh::NewmarkSolver::advance_timestep () virtual
This method advances the solution to the next timestep, after a solve() has been performed. Often this will be done after every UnsteadySolver::solve(), but adaptive mesh refinement and/or adaptive time step selection may require some solve() steps to be repeated.
Reimplemented from libMesh::UnsteadySolver.
Definition at line 43 of file newmark_solver.C.
References _beta, _gamma, libMesh::SecondOrderUnsteadySolver::_old_local_solution_accel, libMesh::SecondOrderUnsteadySolver::_old_local_solution_rate, libMesh::TimeSolver::_system, libMesh::NumericVector< T >::add(), libMesh::UnsteadySolver::advance_timestep(), libMesh::NumericVector< T >::clone(), libMesh::DifferentiableSystem::deltat, libMesh::UnsteadySolver::first_solve, libMesh::System::get_dof_map(), libMesh::DofMap::get_send_list(), libMesh::System::get_vector(), libMesh::NumericVector< T >::localize(), libMesh::SecondOrderUnsteadySolver::old_solution_accel(), libMesh::SecondOrderUnsteadySolver::old_solution_rate(), and libMesh::System::solution.
 {
   // We need to update velocity and acceleration before
   // we update the nonlinear solution (displacement) and
   // delta_t
   NumericVector<Number> & old_solution_rate =
     _system.get_vector("_old_solution_rate");
   NumericVector<Number> & old_solution_accel =
     _system.get_vector("_old_solution_accel");
   if (!first_solve)
     {
       NumericVector<Number> & old_nonlinear_soln =
         _system.get_vector("_old_nonlinear_solution");
       NumericVector<Number> & nonlinear_solution =
         *(_system.solution);
       // We need to cache the new solution_rate before updating the old_solution_rate
       // so we can update acceleration with the proper old_solution_rate
       // v_{n+1} = gamma/(beta*Delta t)*(x_{n+1}-x_n)
       //         - ((gamma/beta)-1)*v_n
       //         - (gamma/(2*beta)-1)*(Delta t)*a_n
       UniquePtr<NumericVector<Number> > new_solution_rate = nonlinear_solution.clone();
       (*new_solution_rate) -= old_nonlinear_soln;
       (*new_solution_rate) *= (_gamma/(_beta*_system.deltat));
       new_solution_rate->add( (1.0-_gamma/_beta), old_solution_rate );
       new_solution_rate->add( (1.0-_gamma/(2.0*_beta))*_system.deltat, old_solution_accel );
       // a_{n+1} = (1/(beta*(Delta t)^2))*(x_{n+1}-x_n)
       //         - 1/(beta*Delta t)*v_n
       //         - (1-1/(2*beta))*a_n
       UniquePtr<NumericVector<Number> > new_solution_accel = old_solution_accel.clone();
       (*new_solution_accel) *=  -(1.0/(2.0*_beta)-1.0);
       new_solution_accel->add( -1.0/(_beta*_system.deltat), old_solution_rate );
       new_solution_accel->add( 1.0/(_beta*_system.deltat*_system.deltat), nonlinear_solution );
       new_solution_accel->add( -1.0/(_beta*_system.deltat*_system.deltat), old_nonlinear_soln );
       // Now update old_solution_rate
       old_solution_rate = (*new_solution_rate);
       old_solution_accel = (*new_solution_accel);
     }
   // Localize updated vectors
   old_solution_rate.localize
     (*_old_local_solution_rate,
      _system.get_dof_map().get_send_list());
   old_solution_accel.localize
     (*_old_local_solution_accel,
      _system.get_dof_map().get_send_list());
   // Now we can finish advancing the timestep
   UnsteadySolver::advance_timestep();
 }
virtual void libMesh::TimeSolver::before_timestep () inline virtual inherited
This method is for subclasses or users to override to do arbitrary processing between timesteps
Definition at line 166 of file time_solver.h.
 {}
void libMesh::NewmarkSolver::compute_initial_accel () virtual
This method uses the specified initial displacement and velocity to compute the initial acceleration .
Definition at line 106 of file newmark_solver.C.
References libMesh::TimeSolver::_diff_solver, _is_accel_solve, libMesh::TimeSolver::_system, libMesh::System::get_vector(), set_initial_accel_avail(), libMesh::System::solution, and libMesh::System::update().
 {
   // We need to compute the initial acceleration based off of
   // the initial position and velocity and, thus, acceleration
   // is the unknown in diff_solver and not the displacement. So,
   // We swap solution and acceleration. NewarkSolver::_general_residual
   // will check _is_accel_solve and provide the correct
   // values to the FEMContext assuming this swap was made.
   this->_is_accel_solve = true;
   //solution->accel, accel->solution
   _system.solution->swap(_system.get_vector("_old_solution_accel"));
   _system.update();
   this->_diff_solver->solve();
   // solution->solution, accel->accel
   _system.solution->swap(_system.get_vector("_old_solution_accel"));
   _system.update();
   // We're done, so no longer doing an acceleration solve
   this->_is_accel_solve = false;
   this->set_initial_accel_avail(true);
 }
virtual UniquePtr<DiffSolver>& libMesh::TimeSolver::diff_solver () inline virtual inherited
An implicit linear or nonlinear solver to use at each timestep.
Reimplemented in libMesh::AdaptiveTimeSolver.
Definition at line 181 of file time_solver.h.
References libMesh::TimeSolver::_diff_solver.
Referenced by libMesh::TimeSolver::init(), libMesh::TimeSolver::init_data(), libMesh::TimeSolver::reinit(), and libMesh::TimeSolver::solve().
 { return _diff_solver; }
void libMesh::ReferenceCounter::disable_print_counter_info () static inherited
Definition at line 107 of file reference_counter.C.
References libMesh::ReferenceCounter::_enable_print_counter.
Referenced by libMesh::LibMeshInit::LibMeshInit(), and libMesh::ReferenceCounter::n_objects().
 {
   _enable_print_counter = false;
   return;
 }
Real libMesh::UnsteadySolver::du (const SystemNorm & norm) const virtual inherited
Computes the size of ||u^{n+1} - u^{n}|| in some norm.
Note
While you can always call this function, its result may or may not be very meaningful. For example, if you call this function right after calling advance_timestep() then you'll get a result of zero since old_nonlinear_solution is set equal to nonlinear_solution in this function.
Implements libMesh::TimeSolver.
Definition at line 227 of file unsteady_solver.C.
References libMesh::TimeSolver::_system, libMesh::System::calculate_norm(), libMesh::System::get_vector(), and libMesh::System::solution.
 {
   UniquePtr<NumericVector<Number> > solution_copy =
     _system.solution->clone();
   solution_copy->add(-1., _system.get_vector("_old_nonlinear_solution"));
   solution_copy->close();
   return _system.calculate_norm(*solution_copy, norm);
 }
bool libMesh::NewmarkSolver::element_residual (bool request_jacobian, DiffContext & context) virtual
This method uses the DifferentiablePhysics' element_time_derivative() and element_constraint() to build a full residual on an element. What combination it uses will depend on theta.
Implements libMesh::TimeSolver.
Definition at line 163 of file newmark_solver.C.
References libMesh::DifferentiablePhysics::_eulerian_time_deriv(), _general_residual(), libMesh::DifferentiablePhysics::damping_residual(), libMesh::DiffContext::elem_reinit(), libMesh::DifferentiablePhysics::element_constraint(), and libMesh::DifferentiablePhysics::mass_residual().
 {
   return this->_general_residual(request_jacobian,
                                  context,
                                  &DifferentiablePhysics::mass_residual,
                                  &DifferentiablePhysics::damping_residual,
                                  &DifferentiablePhysics::_eulerian_time_deriv,
                                  &DifferentiablePhysics::element_constraint,
                                  &DiffContext::elem_reinit);
 }
void libMesh::ReferenceCounter::enable_print_counter_info () static inherited
Methods to enable/disable the reference counter output from print_info()
Definition at line 101 of file reference_counter.C.
References libMesh::ReferenceCounter::_enable_print_counter.
Referenced by libMesh::ReferenceCounter::n_objects().
 {
   _enable_print_counter = true;
   return;
 }
Real libMesh::NewmarkSolver::error_order () const virtual
Error convergence order: 2 for , 1 otherwise
Implements libMesh::UnsteadySolver.
Definition at line 36 of file newmark_solver.C.
References _gamma.
 {
   if (_gamma == 0.5)
     return 2.;
   return 1.;
 }
std::string libMesh::ReferenceCounter::get_info () static inherited
Gets a string containing the reference information.
Definition at line 47 of file reference_counter.C.
References libMesh::ReferenceCounter::_counts, and libMesh::Quality::name().
Referenced by libMesh::ReferenceCounter::print_info().
 {
 #if defined(LIBMESH_ENABLE_REFERENCE_COUNTING) && defined(DEBUG)
   std::ostringstream oss;
   oss << '\n'
       << " ---------------------------------------------------------------------------- \n"
       << "| Reference count information                                                |\n"
       << " ---------------------------------------------------------------------------- \n";
   for (Counts::iterator it = _counts.begin();
        it != _counts.end(); ++it)
     {
       const std::string name(it->first);
       const unsigned int creations    = it->second.first;
       const unsigned int destructions = it->second.second;
       oss << "| " << name << " reference count information:\n"
           << "|  Creations:    " << creations    << '\n'
           << "|  Destructions: " << destructions << '\n';
     }
   oss << " ---------------------------------------------------------------------------- \n";
   return oss.str();
 #else
   return "";
 #endif
 }
void libMesh::ReferenceCounter::increment_constructor_count (const std::string & name) inline protected inherited
Increments the construction counter. Should be called in the constructor of any derived class that will be reference counted.
Definition at line 185 of file reference_counter.h.
References libMesh::ReferenceCounter::_counts, libMesh::Quality::name(), and libMesh::Threads::spin_mtx.
Referenced by libMesh::ReferenceCounter::n_objects(), and libMesh::ReferenceCountedObject< RBParametrized >::ReferenceCountedObject().
 {
   Threads::spin_mutex::scoped_lock lock(Threads::spin_mtx);
   std::pair<unsigned int, unsigned int> & p = _counts[name];
   p.first++;
 }
void libMesh::ReferenceCounter::increment_destructor_count (const std::string & name) inline protected inherited
Increments the destruction counter. Should be called in the destructor of any derived class that will be reference counted.
Definition at line 198 of file reference_counter.h.
References libMesh::ReferenceCounter::_counts, libMesh::Quality::name(), and libMesh::Threads::spin_mtx.
Referenced by libMesh::ReferenceCounter::n_objects(), and libMesh::ReferenceCountedObject< RBParametrized >::~ReferenceCountedObject().
 {
   Threads::spin_mutex::scoped_lock lock(Threads::spin_mtx);
   std::pair<unsigned int, unsigned int> & p = _counts[name];
   p.second++;
 }
void libMesh::SecondOrderUnsteadySolver::init () virtual inherited
The initialization function. This method is used to initialize internal data structures before a simulation begins.
Reimplemented from libMesh::UnsteadySolver.
Definition at line 34 of file second_order_unsteady_solver.C.
References libMesh::TimeSolver::_system, libMesh::System::add_vector(), and libMesh::UnsteadySolver::init().
Referenced by libMesh::SecondOrderUnsteadySolver::time_order().
 {
   UnsteadySolver::init();
   _system.add_vector("_old_solution_rate");
   _system.add_vector("_old_solution_accel");
 }
void libMesh::SecondOrderUnsteadySolver::init_data () virtual inherited
The data initialization function. This method is used to initialize internal data structures after the underlying System has been initialized
Reimplemented from libMesh::UnsteadySolver.
Definition at line 42 of file second_order_unsteady_solver.C.
References libMesh::SecondOrderUnsteadySolver::_old_local_solution_accel, libMesh::SecondOrderUnsteadySolver::_old_local_solution_rate, libMesh::TimeSolver::_system, libMesh::System::get_dof_map(), libMesh::DofMap::get_send_list(), libMesh::GHOSTED, libMesh::UnsteadySolver::init_data(), libMesh::System::n_dofs(), libMesh::System::n_local_dofs(), and libMesh::SERIAL.
Referenced by libMesh::SecondOrderUnsteadySolver::time_order().
 {
   UnsteadySolver::init_data();
 #ifdef LIBMESH_ENABLE_GHOSTED
   _old_local_solution_rate->init (_system.n_dofs(), _system.n_local_dofs(),
                                   _system.get_dof_map().get_send_list(), false,
                                   GHOSTED);
   _old_local_solution_accel->init (_system.n_dofs(), _system.n_local_dofs(),
                                    _system.get_dof_map().get_send_list(), false,
                                    GHOSTED);
 #else
   _old_local_solution_rate->init (_system.n_dofs(), false, SERIAL);
   _old_local_solution_accel->init (_system.n_dofs(), false, SERIAL);
 #endif
 }
bool libMesh::TimeSolver::is_adjoint () const inline inherited
Accessor for querying whether we need to do a primal or adjoint solve
Definition at line 232 of file time_solver.h.
References libMesh::TimeSolver::_is_adjoint.
Referenced by libMesh::FEMSystem::build_context().
   { return _is_adjoint; }
virtual bool libMesh::UnsteadySolver::is_steady () const inline virtual inherited
This is not a steady-state solver.
Implements libMesh::TimeSolver.
Definition at line 153 of file unsteady_solver.h.
 { return false; }
virtual UniquePtr<LinearSolver<Number> >& libMesh::TimeSolver::linear_solver () inline virtual inherited
An implicit linear solver to use for adjoint and sensitivity problems.
Reimplemented in libMesh::AdaptiveTimeSolver.
Definition at line 186 of file time_solver.h.
References libMesh::TimeSolver::_linear_solver.
Referenced by libMesh::TimeSolver::init(), libMesh::TimeSolver::init_data(), and libMesh::TimeSolver::reinit().
 { return _linear_solver; }
static unsigned int libMesh::ReferenceCounter::n_objects () inline static inherited
Prints the number of outstanding (created, but not yet destroyed) objects.
Definition at line 85 of file reference_counter.h.
References libMesh::ReferenceCounter::_n_objects, libMesh::ReferenceCounter::disable_print_counter_info(), libMesh::ReferenceCounter::enable_print_counter_info(), libMesh::ReferenceCounter::increment_constructor_count(), libMesh::ReferenceCounter::increment_destructor_count(), and libMesh::Quality::name().
Referenced by libMesh::System::hide_output(), and libMesh::LibMeshInit::LibMeshInit().
   { return _n_objects; }
bool libMesh::NewmarkSolver::nonlocal_residual (bool request_jacobian, DiffContext & context) virtual
This method uses the DifferentiablePhysics' nonlocal_time_derivative() and nonlocal_constraint() to build a full residual for non-local terms. What combination it uses will depend on theta.
Implements libMesh::TimeSolver.
Definition at line 191 of file newmark_solver.C.
References _general_residual(), libMesh::DifferentiablePhysics::nonlocal_constraint(), libMesh::DifferentiablePhysics::nonlocal_damping_residual(), libMesh::DifferentiablePhysics::nonlocal_mass_residual(), libMesh::DiffContext::nonlocal_reinit(), and libMesh::DifferentiablePhysics::nonlocal_time_derivative().
 {
   return this->_general_residual(request_jacobian,
                                  context,
                                  &DifferentiablePhysics::nonlocal_mass_residual,
                                  &DifferentiablePhysics::nonlocal_damping_residual,
                                  &DifferentiablePhysics::nonlocal_time_derivative,
                                  &DifferentiablePhysics::nonlocal_constraint,
                                  &DiffContext::nonlocal_reinit);
 }
Number libMesh::UnsteadySolver::old_nonlinear_solution (const dof_id_type global_dof_number) const inherited
Returns
The old nonlinear solution for the specified global DOF.
Definition at line 216 of file unsteady_solver.C.
References libMesh::TimeSolver::_system, libMesh::System::get_dof_map(), libMesh::DofMap::n_dofs(), and libMesh::UnsteadySolver::old_local_nonlinear_solution.
Referenced by libMesh::EulerSolver::_general_residual(), libMesh::Euler2Solver::_general_residual(), and _general_residual().
 {
   libmesh_assert_less (global_dof_number, _system.get_dof_map().n_dofs());
   libmesh_assert_less (global_dof_number, old_local_nonlinear_solution->size());
   return (*old_local_nonlinear_solution)(global_dof_number);
 }
Number libMesh::SecondOrderUnsteadySolver::old_solution_accel (const dof_id_type global_dof_number) const inherited
Returns
The solution acceleration at the previous time step, , for the specified global DOF.
Definition at line 116 of file second_order_unsteady_solver.C.
References libMesh::SecondOrderUnsteadySolver::_old_local_solution_accel, libMesh::TimeSolver::_system, libMesh::System::get_dof_map(), and libMesh::DofMap::n_dofs().
Referenced by _general_residual(), advance_timestep(), project_initial_accel(), libMesh::SecondOrderUnsteadySolver::reinit(), and libMesh::SecondOrderUnsteadySolver::time_order().
 {
   libmesh_assert_less (global_dof_number, _system.get_dof_map().n_dofs());
   libmesh_assert_less (global_dof_number, _old_local_solution_accel->size());
   return (*_old_local_solution_accel)(global_dof_number);
 }
Number libMesh::SecondOrderUnsteadySolver::old_solution_rate (const dof_id_type global_dof_number) const inherited
Returns
The solution rate at the previous time step, , for the specified global DOF.
Definition at line 107 of file second_order_unsteady_solver.C.
References libMesh::SecondOrderUnsteadySolver::_old_local_solution_rate, libMesh::TimeSolver::_system, libMesh::System::get_dof_map(), and libMesh::DofMap::n_dofs().
Referenced by _general_residual(), advance_timestep(), libMesh::SecondOrderUnsteadySolver::project_initial_rate(), libMesh::SecondOrderUnsteadySolver::reinit(), and libMesh::SecondOrderUnsteadySolver::time_order().
 {
   libmesh_assert_less (global_dof_number, _system.get_dof_map().n_dofs());
   libmesh_assert_less (global_dof_number, _old_local_solution_rate->size());
   return (*_old_local_solution_rate)(global_dof_number);
 }
void libMesh::ReferenceCounter::print_info (std::ostream & out = libMesh::out) static inherited
Prints the reference information, by default to libMesh::out.
Definition at line 88 of file reference_counter.C.
References libMesh::ReferenceCounter::_enable_print_counter, and libMesh::ReferenceCounter::get_info().
Referenced by libMesh::LibMeshInit::LibMeshInit().
 {
   if (_enable_print_counter)
     out_stream << ReferenceCounter::get_info();
 }
void libMesh::NewmarkSolver::project_initial_accel (FunctionBase< Number > * f, FunctionBase< Gradient > * g = libmesh_nullptr)
Specify non-zero initial acceleration. Should be called before solve(). This is an alternative to compute_initial_acceleration() if the initial acceleration is actually known. The function value f and its gradient g are user-provided cloneable functors. A gradient g is only required/used for projecting onto finite element spaces with continuous derivatives.
Definition at line 132 of file newmark_solver.C.
References libMesh::TimeSolver::_system, libMesh::System::get_vector(), libMesh::SecondOrderUnsteadySolver::old_solution_accel(), libMesh::System::project_vector(), and set_initial_accel_avail().
 {
   NumericVector<Number> & old_solution_accel =
     _system.get_vector("_old_solution_accel");
   _system.project_vector( old_solution_accel, f, g );
   this->set_initial_accel_avail(true);
 }
void libMesh::SecondOrderUnsteadySolver::project_initial_rate (FunctionBase< Number > * f, FunctionBase< Gradient > * g = libmesh_nullptr) inherited
Specify non-zero initial velocity. Should be called before solve(). The function value f and its gradient g are user-provided cloneable functors. A gradient g is only required/used for projecting onto finite element spaces with continuous derivatives.
Definition at line 98 of file second_order_unsteady_solver.C.
References libMesh::TimeSolver::_system, libMesh::System::get_vector(), libMesh::SecondOrderUnsteadySolver::old_solution_rate(), and libMesh::System::project_vector().
Referenced by libMesh::SecondOrderUnsteadySolver::time_order().
 {
   NumericVector<Number> & old_solution_rate =
     _system.get_vector("_old_solution_rate");
   _system.project_vector( old_solution_rate, f, g );
 }
void libMesh::SecondOrderUnsteadySolver::reinit () virtual inherited
The reinitialization function. This method is used to resize internal data vectors after a mesh change.
Reimplemented from libMesh::UnsteadySolver.
Definition at line 60 of file second_order_unsteady_solver.C.
References libMesh::SecondOrderUnsteadySolver::_old_local_solution_accel, libMesh::SecondOrderUnsteadySolver::_old_local_solution_rate, libMesh::TimeSolver::_system, libMesh::System::get_dof_map(), libMesh::DofMap::get_send_list(), libMesh::System::get_vector(), libMesh::GHOSTED, libMesh::NumericVector< T >::localize(), libMesh::System::n_dofs(), libMesh::System::n_local_dofs(), libMesh::SecondOrderUnsteadySolver::old_solution_accel(), libMesh::SecondOrderUnsteadySolver::old_solution_rate(), libMesh::UnsteadySolver::reinit(), and libMesh::SERIAL.
Referenced by libMesh::SecondOrderUnsteadySolver::time_order().
 {
   UnsteadySolver::reinit();
 #ifdef LIBMESH_ENABLE_GHOSTED
   _old_local_solution_rate->init (_system.n_dofs(), _system.n_local_dofs(),
                                   _system.get_dof_map().get_send_list(), false,
                                   GHOSTED);
   _old_local_solution_accel->init (_system.n_dofs(), _system.n_local_dofs(),
                                    _system.get_dof_map().get_send_list(), false,
                                    GHOSTED);
 #else
   _old_local_solution_rate->init (_system.n_dofs(), false, SERIAL);
   _old_local_solution_accel->init (_system.n_dofs(), false, SERIAL);
 #endif
   // localize the old solutions
   NumericVector<Number> & old_solution_rate =
     _system.get_vector("_old_solution_rate");
   NumericVector<Number> & old_solution_accel =
     _system.get_vector("_old_solution_accel");
   old_solution_rate.localize
     (*_old_local_solution_rate,
      _system.get_dof_map().get_send_list());
   old_solution_accel.localize
     (*_old_local_solution_accel,
      _system.get_dof_map().get_send_list());
 }
void libMesh::SecondOrderUnsteadySolver::retrieve_timestep () virtual inherited
This method retrieves all the stored solutions at the current system.time
Reimplemented from libMesh::UnsteadySolver.
Definition at line 93 of file second_order_unsteady_solver.C.
Referenced by libMesh::SecondOrderUnsteadySolver::time_order().
 {
   libmesh_not_implemented();
 }
void libMesh::NewmarkSolver::set_beta (Real beta) inline
Setter for
Definition at line 149 of file newmark_solver.h.
References _beta.
   { _beta = beta; }
void libMesh::NewmarkSolver::set_gamma (Real gamma) inline
Setter for .
Note
The method is second order only for .
Definition at line 157 of file newmark_solver.h.
References _gamma.
   { _gamma = gamma; }
void libMesh::NewmarkSolver::set_initial_accel_avail (bool initial_accel_set)
Allow the user to (re)set whether the initial acceleration is available. This is not needed if either compute_initial_accel() or project_initial_accel() are called. This is useful is the user is restarting a calculation and the acceleration is available from the restart.
Definition at line 143 of file newmark_solver.C.
References _initial_accel_set.
Referenced by compute_initial_accel(), and project_initial_accel().
 {
   _initial_accel_set = initial_accel_set;
 }
void libMesh::TimeSolver::set_is_adjoint (bool _is_adjoint_value) inline inherited
Accessor for setting whether we need to do a primal or adjoint solve
Definition at line 239 of file time_solver.h.
References libMesh::TimeSolver::_is_adjoint.
Referenced by libMesh::DifferentiableSystem::adjoint_solve(), libMesh::FEMSystem::postprocess(), and libMesh::DifferentiableSystem::solve().
   { _is_adjoint = _is_adjoint_value; }
void libMesh::TimeSolver::set_solution_history (const SolutionHistory & _solution_history) inherited
A setter function users will employ if they need to do something other than save no solution history
Definition at line 97 of file time_solver.C.
References libMesh::SolutionHistory::clone(), and libMesh::TimeSolver::solution_history.
 {
   solution_history = _solution_history.clone();
 }
bool libMesh::NewmarkSolver::side_residual (bool request_jacobian, DiffContext & context) virtual
This method uses the DifferentiablePhysics' side_time_derivative() and side_constraint() to build a full residual on an element's side. What combination it uses will depend on theta.
Implements libMesh::TimeSolver.
Definition at line 177 of file newmark_solver.C.
References _general_residual(), libMesh::DiffContext::elem_side_reinit(), libMesh::DifferentiablePhysics::side_constraint(), libMesh::DifferentiablePhysics::side_damping_residual(), libMesh::DifferentiablePhysics::side_mass_residual(), and libMesh::DifferentiablePhysics::side_time_derivative().
 {
   return this->_general_residual(request_jacobian,
                                  context,
                                  &DifferentiablePhysics::side_mass_residual,
                                  &DifferentiablePhysics::side_damping_residual,
                                  &DifferentiablePhysics::side_time_derivative,
                                  &DifferentiablePhysics::side_constraint,
                                  &DiffContext::elem_side_reinit);
 }
void libMesh::NewmarkSolver::solve () virtual
This method solves for the solution at the next timestep. Usually we will only need to solve one (non)linear system per timestep, but more complex subclasses may override this.
Reimplemented from libMesh::UnsteadySolver.
Definition at line 148 of file newmark_solver.C.
References _initial_accel_set, and libMesh::UnsteadySolver::solve().
 {
   // First, check that the initial accel was set one way or another
   if (!_initial_accel_set)
     {
       std::string error = "ERROR: Must first set initial acceleration using one of:\n";
       error += "NewmarkSolver::compute_initial_accel()\n";
       error += "NewmarkSolver::project_initial_accel()\n";
       libmesh_error_msg(error);
     }
   // That satisfied, now we can solve
   UnsteadySolver::solve();
 }
const sys_type& libMesh::TimeSolver::system () const inline inherited
Returns
A constant reference to the system we are solving.
Definition at line 171 of file time_solver.h.
References libMesh::TimeSolver::_system.
Referenced by libMesh::TimeSolver::reinit(), and libMesh::TimeSolver::solve().
 { return _system; }
sys_type& libMesh::TimeSolver::system () inline inherited
Returns
A writable reference to the system we are solving.
Definition at line 176 of file time_solver.h.
References libMesh::TimeSolver::_system.
 { return _system; }
virtual unsigned int libMesh::SecondOrderUnsteadySolver::time_order () const inline virtual inherited
Returns
The maximum order of time derivatives for which the UnsteadySolver subclass is capable of handling.
For example, EulerSolver will have time_order() = 1 and NewmarkSolver will have time_order() = 2.
Implements libMesh::UnsteadySolver.
Definition at line 53 of file second_order_unsteady_solver.h.
References libMesh::SecondOrderUnsteadySolver::init(), libMesh::SecondOrderUnsteadySolver::init_data(), libmesh_nullptr, libMesh::SecondOrderUnsteadySolver::old_solution_accel(), libMesh::SecondOrderUnsteadySolver::old_solution_rate(), libMesh::SecondOrderUnsteadySolver::project_initial_rate(), libMesh::SecondOrderUnsteadySolver::reinit(), and libMesh::SecondOrderUnsteadySolver::retrieve_timestep().
   { return 2; }
Member Data Documentation
Real libMesh::NewmarkSolver::_beta protected
The value for the to employ. Method is unconditionally stable for
Definition at line 167 of file newmark_solver.h.
Referenced by _general_residual(), advance_timestep(), and set_beta().
ReferenceCounter::Counts libMesh::ReferenceCounter::_counts static protected inherited
Actually holds the data.
Definition at line 124 of file reference_counter.h.
Referenced by libMesh::ReferenceCounter::get_info(), libMesh::ReferenceCounter::increment_constructor_count(), and libMesh::ReferenceCounter::increment_destructor_count().
UniquePtr<DiffSolver> libMesh::TimeSolver::_diff_solver protected inherited
An implicit linear or nonlinear solver to use at each timestep.
Definition at line 247 of file time_solver.h.
Referenced by compute_initial_accel(), libMesh::TimeSolver::diff_solver(), and libMesh::UnsteadySolver::solve().
bool libMesh::ReferenceCounter::_enable_print_counter = true static protected inherited
Flag to control whether reference count information is printed when print_info is called.
Definition at line 143 of file reference_counter.h.
Referenced by libMesh::ReferenceCounter::disable_print_counter_info(), libMesh::ReferenceCounter::enable_print_counter_info(), and libMesh::ReferenceCounter::print_info().
Real libMesh::NewmarkSolver::_gamma protected
The value for to employ. Newmark is 2nd order iff .
Definition at line 173 of file newmark_solver.h.
Referenced by _general_residual(), advance_timestep(), error_order(), and set_gamma().
bool libMesh::NewmarkSolver::_initial_accel_set protected
This method requires an initial acceleration. So, we force the user to call either compute_initial_accel or project_initial_accel to set the initial acceleration.
Definition at line 187 of file newmark_solver.h.
Referenced by set_initial_accel_avail(), and solve().
bool libMesh::NewmarkSolver::_is_accel_solve protected
Need to be able to indicate to _general_residual if we are doing an acceleration solve or not.
Definition at line 179 of file newmark_solver.h.
Referenced by _general_residual(), and compute_initial_accel().
UniquePtr<LinearSolver<Number> > libMesh::TimeSolver::_linear_solver protected inherited
An implicit linear solver to use for adjoint problems.
Definition at line 252 of file time_solver.h.
Referenced by libMesh::TimeSolver::linear_solver().
Threads::spin_mutex libMesh::ReferenceCounter::_mutex static protected inherited
Mutual exclusion object to enable thread-safe reference counting.
Definition at line 137 of file reference_counter.h.
Threads::atomic< unsigned int > libMesh::ReferenceCounter::_n_objects static protected inherited
The number of objects. Print the reference count information when the number returns to 0.
Definition at line 132 of file reference_counter.h.
Referenced by libMesh::ReferenceCounter::n_objects(), libMesh::ReferenceCounter::ReferenceCounter(), and libMesh::ReferenceCounter::~ReferenceCounter().
UniquePtr<NumericVector<Number> > libMesh::SecondOrderUnsteadySolver::_old_local_solution_accel protected inherited
Serial vector of previous time step accleration
Definition at line 112 of file second_order_unsteady_solver.h.
Referenced by advance_timestep(), libMesh::SecondOrderUnsteadySolver::init_data(), libMesh::SecondOrderUnsteadySolver::old_solution_accel(), and libMesh::SecondOrderUnsteadySolver::reinit().
UniquePtr<NumericVector<Number> > libMesh::SecondOrderUnsteadySolver::_old_local_solution_rate protected inherited
Serial vector of previous time step velocity
Definition at line 107 of file second_order_unsteady_solver.h.
Referenced by advance_timestep(), libMesh::SecondOrderUnsteadySolver::init_data(), libMesh::SecondOrderUnsteadySolver::old_solution_rate(), and libMesh::SecondOrderUnsteadySolver::reinit().
sys_type& libMesh::TimeSolver::_system protected inherited
A reference to the system we are solving.
Definition at line 257 of file time_solver.h.
Referenced by libMesh::EulerSolver::_general_residual(), libMesh::Euler2Solver::_general_residual(), libMesh::SteadySolver::_general_residual(), _general_residual(), libMesh::UnsteadySolver::adjoint_advance_timestep(), advance_timestep(), libMesh::AdaptiveTimeSolver::advance_timestep(), libMesh::UnsteadySolver::advance_timestep(), compute_initial_accel(), libMesh::FirstOrderUnsteadySolver::compute_second_order_eqns(), libMesh::UnsteadySolver::du(), libMesh::EulerSolver::element_residual(), libMesh::Euler2Solver::element_residual(), libMesh::EigenTimeSolver::element_residual(), libMesh::SecondOrderUnsteadySolver::init(), libMesh::UnsteadySolver::init(), libMesh::TimeSolver::init(), libMesh::EigenTimeSolver::init(), libMesh::SecondOrderUnsteadySolver::init_data(), libMesh::UnsteadySolver::init_data(), libMesh::TimeSolver::init_data(), libMesh::EulerSolver::nonlocal_residual(), libMesh::Euler2Solver::nonlocal_residual(), libMesh::EigenTimeSolver::nonlocal_residual(), libMesh::UnsteadySolver::old_nonlinear_solution(), libMesh::SecondOrderUnsteadySolver::old_solution_accel(), libMesh::SecondOrderUnsteadySolver::old_solution_rate(), project_initial_accel(), libMesh::SecondOrderUnsteadySolver::project_initial_rate(), libMesh::SecondOrderUnsteadySolver::reinit(), libMesh::UnsteadySolver::reinit(), libMesh::TimeSolver::reinit(), libMesh::UnsteadySolver::retrieve_timestep(), libMesh::EigenTimeSolver::side_residual(), libMesh::TwostepTimeSolver::solve(), libMesh::UnsteadySolver::solve(), libMesh::EigenTimeSolver::solve(), and libMesh::TimeSolver::system().
bool libMesh::UnsteadySolver::first_adjoint_step protected inherited
A bool that will be true the first time adjoint_advance_timestep() is called, (when the primal solution is to be used to set adjoint boundary conditions) and false thereafter
Definition at line 167 of file unsteady_solver.h.
Referenced by libMesh::UnsteadySolver::adjoint_advance_timestep().
bool libMesh::UnsteadySolver::first_solve protected inherited
A bool that will be true the first time solve() is called, and false thereafter
Definition at line 161 of file unsteady_solver.h.
Referenced by advance_timestep(), libMesh::AdaptiveTimeSolver::advance_timestep(), libMesh::UnsteadySolver::advance_timestep(), libMesh::TwostepTimeSolver::solve(), and libMesh::UnsteadySolver::solve().
UniquePtr<NumericVector<Number> > libMesh::UnsteadySolver::old_local_nonlinear_solution inherited
Serial vector of _system.get_vector("_old_nonlinear_solution")
Definition at line 137 of file unsteady_solver.h.
Referenced by libMesh::AdaptiveTimeSolver::AdaptiveTimeSolver(), libMesh::UnsteadySolver::adjoint_advance_timestep(), libMesh::UnsteadySolver::advance_timestep(), libMesh::AdaptiveTimeSolver::init(), libMesh::UnsteadySolver::init_data(), libMesh::UnsteadySolver::old_nonlinear_solution(), libMesh::UnsteadySolver::reinit(), libMesh::UnsteadySolver::retrieve_timestep(), and libMesh::AdaptiveTimeSolver::~AdaptiveTimeSolver().
bool libMesh::TimeSolver::quiet inherited
Print extra debugging information if quiet == false.
Definition at line 191 of file time_solver.h.
Referenced by libMesh::TwostepTimeSolver::solve(), libMesh::UnsteadySolver::solve(), and libMesh::EigenTimeSolver::solve().
unsigned int libMesh::TimeSolver::reduce_deltat_on_diffsolver_failure inherited
This value (which defaults to zero) is the number of times the TimeSolver is allowed to halve deltat and let the DiffSolver repeat the latest failed solve with a reduced timestep.
Note
This has no effect for SteadySolvers.
You must set at least one of the DiffSolver flags "continue_after_max_iterations" or "continue_after_backtrack_failure" to allow the TimeSolver to retry the solve.
Definition at line 220 of file time_solver.h.
Referenced by libMesh::TwostepTimeSolver::solve(), and libMesh::UnsteadySolver::solve().
UniquePtr<SolutionHistory> libMesh::TimeSolver::solution_history protected inherited
A UniquePtr to a SolutionHistory object. Default is NoSolutionHistory, which the user can override by declaring a different kind of SolutionHistory in the application
Definition at line 264 of file time_solver.h.
Referenced by libMesh::UnsteadySolver::adjoint_advance_timestep(), libMesh::UnsteadySolver::advance_timestep(), libMesh::UnsteadySolver::retrieve_timestep(), and libMesh::TimeSolver::set_solution_history().
The documentation for this class was generated from the following files:
newmark_solver.h
newmark_solver.C