libMesh: libMesh::MeshRefinement::ElementFlagging Class Reference
SomeWebsiteLogo
libMesh::MeshRefinement::ElementFlagging Class Reference abstract
#include <mesh_refinement.h>
Public Member Functions
virtual ~ElementFlagging ()
virtual void flag_elements ()=0
Detailed Description
Abstract base class to be used for user-specified element flagging. This can be used instead of or to augment traditional error indicator based refinement. This simply provides a base class that can be derived from and then passed to the flag_elements_by () method.
Definition at line 85 of file mesh_refinement.h.
Constructor & Destructor Documentation
virtual libMesh::MeshRefinement::ElementFlagging::~ElementFlagging () inline virtual
Destructor. Virtual because we will have virtual functions.
Definition at line 91 of file mesh_refinement.h.
References libMesh::MeshRefinement::add_elem(), libMesh::MeshRefinement::add_node(), libMesh::MeshRefinement::add_p_to_h_refinement(), libMesh::MeshRefinement::clean_refinement_flags(), libMesh::MeshRefinement::clear(), libMesh::MeshRefinement::coarsen_elements(), libMesh::MeshRefinement::coarsen_fraction(), flag_elements(), libMesh::MeshRefinement::flag_elements_by(), libMesh::MeshRefinement::flag_elements_by_elem_fraction(), libMesh::MeshRefinement::flag_elements_by_error_fraction(), libMesh::MeshRefinement::flag_elements_by_error_tolerance(), libMesh::MeshRefinement::flag_elements_by_mean_stddev(), libMesh::MeshRefinement::flag_elements_by_nelem_target(), libMesh::invalid_uint, libMesh::MeshTools::max_level(), libMesh::Real, libMesh::MeshRefinement::refine_and_coarsen_elements(), libMesh::MeshRefinement::refine_elements(), libMesh::MeshRefinement::refine_fraction(), libMesh::MeshRefinement::set_periodic_boundaries_ptr(), libMesh::MeshRefinement::switch_h_to_p_refinement(), libMesh::MeshRefinement::test_level_one(), libMesh::MeshRefinement::test_unflagged(), libMesh::MeshRefinement::uniformly_coarsen(), libMesh::MeshRefinement::uniformly_p_coarsen(), libMesh::MeshRefinement::uniformly_p_refine(), libMesh::MeshRefinement::uniformly_refine(), and libMesh::MeshRefinement::~MeshRefinement().
 {}
Member Function Documentation
virtual void libMesh::MeshRefinement::ElementFlagging::flag_elements () pure virtual
Callback function to be used for marking elements for refinement.
Referenced by libMesh::MeshRefinement::flag_elements_by(), and ~ElementFlagging().
The documentation for this class was generated from the following file:
mesh_refinement.h