libMesh: libMesh::BuildProjectionList Class Reference
SomeWebsiteLogo
libMesh::BuildProjectionList Class Reference
Public Member Functions
BuildProjectionList (const System &system_in)
BuildProjectionList (BuildProjectionList &other, Threads::split)
void unique ()
void operator() (const ConstElemRange &range)
void join (const BuildProjectionList &other)
Public Attributes
std::vector< dof_id_type > send_list
Private Attributes
const System & system
Detailed Description
This class builds the send_list of old dof indices whose coefficients are needed to perform a projection. This may be executed in parallel on multiple threads. The end result is a send_list vector which is unsorted and may contain duplicate elements. The unique() method can be used to sort and create a unique list.
Definition at line 491 of file system_projection.C.
Constructor & Destructor Documentation
libMesh::BuildProjectionList::BuildProjectionList (const System & system_in) inline
Definition at line 497 of file system_projection.C.
                                                  :
     system(system_in),
     send_list()
   {}
libMesh::BuildProjectionList::BuildProjectionList (BuildProjectionList & other, Threads::split) inline
Definition at line 502 of file system_projection.C.
                                                                   :
     system(other.system),
     send_list()
   {}
Member Function Documentation
void libMesh::BuildProjectionList::join (const BuildProjectionList & other)
Definition at line 2119 of file system_projection.C.
References send_list.
 {
   // Joining simply requires I add the dof indices from the other object
   this->send_list.insert(this->send_list.end(),
                          other.send_list.begin(),
                          other.send_list.end());
 }
void libMesh::BuildProjectionList::operator() (const ConstElemRange & range)
Definition at line 2027 of file system_projection.C.
References libMesh::StoredRange< iterator_type, object_type >::begin(), libMesh::Elem::child_ptr(), libMesh::DofObject::dof_number(), libMesh::StoredRange< iterator_type, object_type >::end(), libMesh::DofMap::end_old_dof(), libMesh::DofMap::first_old_dof(), libMesh::System::get_dof_map(), libMesh::Elem::JUST_COARSENED, libMesh::Elem::JUST_REFINED, libMesh::libmesh_assert(), libMesh::Elem::n_children(), libMesh::DofObject::n_comp(), libMesh::Elem::n_nodes(), libMesh::DofObject::n_vars(), libMesh::Elem::node_ptr(), libMesh::System::number(), libMesh::DofMap::old_dof_indices(), libMesh::DofObject::old_dof_object, libMesh::Elem::parent(), libMesh::Elem::refinement_flag(), send_list, libMesh::swap(), and system.
 {
   // The DofMap for this system
   const DofMap & dof_map = system.get_dof_map();
   const dof_id_type first_old_dof = dof_map.first_old_dof();
   const dof_id_type end_old_dof   = dof_map.end_old_dof();
   // We can handle all the variables at once.
   // The old global DOF indices
   std::vector<dof_id_type> di;
   // Iterate over the elements in the range
   for (ConstElemRange::const_iterator elem_it=range.begin(); elem_it != range.end(); ++elem_it)
     {
       const Elem * elem = *elem_it;
       // If this element doesn't have an old_dof_object with dofs for the
       // current system, then it must be newly added, so the user
       // is responsible for setting the new dofs.
       // ... but we need a better way to test for that; the code
       // below breaks on any FE type for which the elem stores no
       // dofs.
       // if (!elem->old_dof_object || !elem->old_dof_object->has_dofs(system.number()))
       //  continue;
       // Examining refinement flags instead should distinguish
       // between refinement-added and user-added elements lacking
       // old_dof_object
       if (!elem->old_dof_object &&
           elem->refinement_flag() != Elem::JUST_REFINED &&
           elem->refinement_flag() != Elem::JUST_COARSENED)
         continue;
       const Elem * parent = elem->parent();
       if (elem->refinement_flag() == Elem::JUST_REFINED)
         {
           libmesh_assert(parent);
           // We used to hack_p_level here, but that wasn't thread-safe
           // so now we take p refinement flags into account in
           // old_dof_indices
           dof_map.old_dof_indices (parent, di);
           for (unsigned int n=0; n != elem->n_nodes(); ++n)
             {
               const Node * node = elem->node_ptr(n);
               const DofObject * old_dofs = node->old_dof_object;
               if (old_dofs)
                 {
                   const unsigned int sysnum = system.number();
                   const unsigned int nv = old_dofs->n_vars(sysnum);
                   for (unsigned int v=0; v != nv; ++v)
                     {
                       const unsigned int nc =
                         old_dofs->n_comp(sysnum, v);
                       for (unsigned int c=0; c != nc; ++c)
                         di.push_back
                           (old_dofs->dof_number(sysnum, v, c));
                     }
                 }
             }
           std::sort(di.begin(), di.end());
           std::vector<dof_id_type>::iterator new_end =
             std::unique(di.begin(), di.end());
           std::vector<dof_id_type>(di.begin(), new_end).swap(di);
         }
       else if (elem->refinement_flag() == Elem::JUST_COARSENED)
         {
           std::vector<dof_id_type> di_child;
           di.clear();
           for (unsigned int c=0; c != elem->n_children(); ++c)
             {
               dof_map.old_dof_indices (elem->child_ptr(c), di_child);
               di.insert(di.end(), di_child.begin(), di_child.end());
             }
         }
       else
         dof_map.old_dof_indices (elem, di);
       for (unsigned int i=0; i != di.size(); ++i)
         if (di[i] < first_old_dof || di[i] >= end_old_dof)
           this->send_list.push_back(di[i]);
     }  // end elem loop
 }
void libMesh::BuildProjectionList::unique ()
Definition at line 2007 of file system_projection.C.
References send_list, and libMesh::swap().
 {
   // Sort the send list.  After this duplicated
   // elements will be adjacent in the vector
   std::sort(this->send_list.begin(),
             this->send_list.end());
   // Now use std::unique to remove duplicate entries
   std::vector<dof_id_type>::iterator new_end =
     std::unique (this->send_list.begin(),
                  this->send_list.end());
   // Remove the end of the send_list.  Use the "swap trick"
   // from Effective STL
   std::vector<dof_id_type>
     (this->send_list.begin(), new_end).swap (this->send_list);
 }
Member Data Documentation
std::vector<dof_id_type> libMesh::BuildProjectionList::send_list
Definition at line 510 of file system_projection.C.
Referenced by join(), operator()(), and unique().
const System& libMesh::BuildProjectionList::system private
Definition at line 494 of file system_projection.C.
Referenced by operator()().
The documentation for this class was generated from the following file:
system_projection.C