libMesh: libMesh::Parallel::Packing< const Node * > Class Template Reference
SomeWebsiteLogo
libMesh::Parallel::Packing< const Node * > Class Template Reference
#include <parallel_node.h>
Public Types
typedef largest_id_type buffer_type
Public Member Functions
template<>
unsigned int packable_size (const Node *const &node, const MeshBase *mesh)
template<>
unsigned int packed_size (const std::vector< largest_id_type >::const_iterator in)
template<>
unsigned int packed_size (const std::vector< largest_id_type >::iterator in)
template<>
unsigned int packable_size (const Node *const &node, const DistributedMesh *mesh)
template<>
unsigned int packable_size (const Node *const &node, const ParallelMesh *mesh)
template<>
void pack (const Node *const &node, std::back_insert_iterator< std::vector< largest_id_type > > data_out, const MeshBase *mesh)
template<>
void pack (const Node *const &node, std::back_insert_iterator< std::vector< largest_id_type > > data_out, const DistributedMesh *mesh)
template<>
void pack (const Node *const &node, std::back_insert_iterator< std::vector< largest_id_type > > data_out, const ParallelMesh *mesh)
Static Public Member Functions
template<typename OutputIter , typename Context >
static void pack (const Node *const &object, OutputIter data_out, const Context *context)
template<typename Context >
static unsigned int packable_size (const Node *const &object, const Context *context)
template<typename BufferIter >
static unsigned int packed_size (BufferIter iter)
template<typename BufferIter , typename Context >
static const Node * unpack (BufferIter in, Context *ctx)
Detailed Description
template<>
class libMesh::Parallel::Packing< const Node * >
Definition at line 35 of file parallel_node.h.
Member Typedef Documentation
typedef largest_id_type libMesh::Parallel::Packing< const Node * >::buffer_type
Definition at line 38 of file parallel_node.h.
Member Function Documentation
template<typename OutputIter , typename Context > static void libMesh::Parallel::Packing< const Node * >::pack (const Node *const & object, OutputIter data_out, const Context * context) static
template<> void libMesh::Parallel::Packing< const Node * >::pack (const Node *const & node, std::back_insert_iterator< std::vector< largest_id_type > > data_out, const MeshBase * mesh)
Definition at line 131 of file parallel_node.C.
References libMesh::BoundaryInfo::boundary_ids(), libMesh::MeshBase::get_boundary_info(), libMesh::DofObject::id(), libMesh::DofObject::invalid_unique_id, libmesh_assert, LIBMESH_DIM, std::max(), libMesh::DofObject::pack_indexing(), libMesh::DofObject::processor_id(), libMesh::DofObject::unique_id(), and libMesh::DofObject::valid_unique_id().
 {
   libmesh_assert(node);
 #ifndef NDEBUG
   *data_out++ = (node_magic_header);
 #endif
   *data_out++ = (static_cast<largest_id_type>(node->processor_id()));
   *data_out++ = (static_cast<largest_id_type>(node->id()));
 #ifdef LIBMESH_ENABLE_UNIQUE_ID
   if (node->valid_unique_id())
     *data_out++ = (static_cast<largest_id_type>(node->unique_id()));
   else
     // OK to send invalid unique id, we must not own this DOF
     *data_out++ = (static_cast<largest_id_type>(DofObject::invalid_unique_id));
 #endif
   // use "(a+b-1)/b" trick to get a/b to round up
   static const unsigned int idtypes_per_Real =
     (sizeof(Real) + sizeof(largest_id_type) - 1) / sizeof(largest_id_type);
   for (unsigned int i=0; i != LIBMESH_DIM; ++i)
     {
       const largest_id_type * Real_as_idtypes =
         reinterpret_cast<const largest_id_type *>(&((*node)(i)));
       for (unsigned int j=0; j != idtypes_per_Real; ++j)
         {
           *data_out++ =(Real_as_idtypes[j]);
         }
     }
   // Add any DofObject indices
   node->pack_indexing(data_out);
   // Add any nodal boundary condition ids
   std::vector<boundary_id_type> bcs;
   mesh->get_boundary_info().boundary_ids(node, bcs);
   libmesh_assert(bcs.size() < std::numeric_limits<largest_id_type>::max());
   *data_out++ =(bcs.size());
   for (std::vector<boundary_id_type>::iterator bc_it=bcs.begin();
        bc_it != bcs.end(); ++bc_it)
     *data_out++ =(*bc_it);
 }
template<> void libMesh::Parallel::Packing< const Node * >::pack (const Node *const & node, std::back_insert_iterator< std::vector< largest_id_type > > data_out, const DistributedMesh * mesh)
Definition at line 187 of file parallel_node.C.
References libMesh::Parallel::Packing< T >::pack().
 {
   pack(node, data_out, static_cast<const MeshBase*>(mesh));
 }
template<> void libMesh::Parallel::Packing< const Node * >::pack (const Node *const & node, std::back_insert_iterator< std::vector< largest_id_type > > data_out, const ParallelMesh * mesh)
Definition at line 199 of file parallel_node.C.
References libMesh::Parallel::Packing< T >::pack().
 {
   pack(node, data_out, static_cast<const MeshBase*>(mesh));
 }
template<typename Context > static unsigned int libMesh::Parallel::Packing< const Node * >::packable_size (const Node *const & object, const Context * context) static
template<> unsigned int libMesh::Parallel::Packing< const Node * >::packable_size (const Node *const & node, const MeshBase * mesh)
Definition at line 59 of file parallel_node.C.
References libMesh::MeshBase::get_boundary_info(), LIBMESH_DIM, libMesh::BoundaryInfo::n_boundary_ids(), and libMesh::DofObject::packed_indexing_size().
 {
   return
 #ifndef NDEBUG
     1 + // add an int for the magic header when testing
 #endif
     header_size + LIBMESH_DIM*idtypes_per_Real +
     node->packed_indexing_size() +
     1 + mesh->get_boundary_info().n_boundary_ids(node);
 }
template<> unsigned int libMesh::Parallel::Packing< const Node * >::packable_size (const Node *const & node, const DistributedMesh * mesh)
Definition at line 109 of file parallel_node.C.
References libMesh::Parallel::Packing< T >::packable_size().
 {
   return packable_size(node, static_cast<const MeshBase *>(mesh));
 }
template<> unsigned int libMesh::Parallel::Packing< const Node * >::packable_size (const Node *const & node, const ParallelMesh * mesh)
Definition at line 120 of file parallel_node.C.
References libMesh::Parallel::Packing< T >::packable_size().
 {
   return packable_size(node, static_cast<const MeshBase *>(mesh));
 }
template<typename BufferIter > static unsigned int libMesh::Parallel::Packing< const Node * >::packed_size (BufferIter iter) static
template<> unsigned int libMesh::Parallel::Packing< const Node * >::packed_size (const std::vector< largest_id_type >::const_iterator in)
Definition at line 76 of file parallel_node.C.
References libmesh_assert_greater_equal, LIBMESH_DIM, and libMesh::DofObject::unpackable_indexing_size().
 {
   const unsigned int pre_indexing_size =
 #ifndef NDEBUG
     1 + // add an int for the magic header when testing
 #endif
     header_size + LIBMESH_DIM*idtypes_per_Real;
   const unsigned int indexing_size =
     DofObject::unpackable_indexing_size(in+pre_indexing_size);
   const int n_bcs = cast_int<int>
     (*(in + pre_indexing_size + indexing_size));
   libmesh_assert_greater_equal (n_bcs, 0);
   return pre_indexing_size + indexing_size + 1 + n_bcs;
 }
template<> unsigned int libMesh::Parallel::Packing< const Node * >::packed_size (const std::vector< largest_id_type >::iterator in)
Definition at line 99 of file parallel_node.C.
References libMesh::Parallel::Packing< T >::packed_size().
 {
   return packed_size(std::vector<largest_id_type>::const_iterator(in));
 }
template<typename BufferIter , typename Context > const Node * libMesh::Parallel::Packing< const Node * >::unpack (BufferIter in, Context * ctx) inline static
Definition at line 85 of file parallel_node.h.
References libMesh::Parallel::Packing< T >::unpack().
 { return Packing<Node *>::unpack(in, ctx); }
The documentation for this class was generated from the following files:
parallel_node.h
parallel_node.C