libMesh: libMesh::SlepcEigenSolver< T > Class Template Reference
SomeWebsiteLogo
libMesh::SlepcEigenSolver< T > Class Template Reference
EigenSolver implementation based on SLEPc.
#include <slepc_eigen_solver.h>
Public Member Functions
SlepcEigenSolver (const Parallel::Communicator &comm_in)
~SlepcEigenSolver ()
virtual void clear () override
virtual void init () override
virtual std::pair< unsigned int, unsigned int > solve_standard (SparseMatrix< T > &matrix_A, int nev, int ncv, const double tol, const unsigned int m_its) override
virtual std::pair< unsigned int, unsigned int > solve_standard (ShellMatrix< T > &shell_matrix, int nev, int ncv, const double tol, const unsigned int m_its) override
virtual std::pair< unsigned int, unsigned int > solve_generalized (SparseMatrix< T > &matrix_A, SparseMatrix< T > &matrix_B, int nev, int ncv, const double tol, const unsigned int m_its) override
virtual std::pair< unsigned int, unsigned int > solve_generalized (ShellMatrix< T > &matrix_A, SparseMatrix< T > &matrix_B, int nev, int ncv, const double tol, const unsigned int m_its) override
virtual std::pair< unsigned int, unsigned int > solve_generalized (SparseMatrix< T > &matrix_A, ShellMatrix< T > &matrix_B, int nev, int ncv, const double tol, const unsigned int m_its) override
virtual std::pair< unsigned int, unsigned int > solve_generalized (ShellMatrix< T > &matrix_A, ShellMatrix< T > &matrix_B, int nev, int ncv, const double tol, const unsigned int m_its) override
virtual std::pair< Real, Real > get_eigenpair (dof_id_type i, NumericVector< T > &solution_in) override
virtual std::pair< Real, Real > get_eigenvalue (dof_id_type i) override
Real get_relative_error (unsigned int i)
virtual void attach_deflation_space (NumericVector< T > &deflation_vector) override
virtual void set_initial_space (NumericVector< T > &initial_space_in) override
EPS eps ()
bool initialized () const
bool get_close_matrix_before_solve () const
void set_close_matrix_before_solve (bool val)
EigenSolverType eigen_solver_type () const
EigenProblemType eigen_problem_type () const
PositionOfSpectrum position_of_spectrum () const
void set_eigensolver_type (const EigenSolverType est)
void set_eigenproblem_type (EigenProblemType ept)
void set_position_of_spectrum (PositionOfSpectrum pos)
void set_position_of_spectrum (Real pos)
void set_position_of_spectrum (Real pos, PositionOfSpectrum target)
void set_solver_configuration (SolverConfiguration &solver_configuration)
const Parallel::Communicator & comm () const
processor_id_type n_processors () const
processor_id_type processor_id () const
Static Public Member Functions
static std::unique_ptr< EigenSolver< T > > build (const Parallel::Communicator &comm_in, const SolverPackage solver_package=SLEPC_SOLVERS)
static std::string get_info ()
static void print_info (std::ostream &out=libMesh::out)
static unsigned int n_objects ()
static void enable_print_counter_info ()
static void disable_print_counter_info ()
Protected Types
typedef std::map< std::string, std::pair< unsigned int, unsigned int > > Counts
Protected Member Functions
void increment_constructor_count (const std::string &name)
void increment_destructor_count (const std::string &name)
Protected Attributes
EigenSolverType _eigen_solver_type
EigenProblemType _eigen_problem_type
PositionOfSpectrum _position_of_spectrum
bool _is_initialized
SolverConfiguration * _solver_configuration
Real _target_val
bool _close_matrix_before_solve
const Parallel::Communicator & _communicator
Static Protected Attributes
static Counts _counts
static Threads::atomic< unsigned int > _n_objects
static Threads::spin_mutex _mutex
static bool _enable_print_counter = true
Private Member Functions
std::pair< unsigned int, unsigned int > _solve_standard_helper (Mat mat, int nev, int ncv, const double tol, const unsigned int m_its)
std::pair< unsigned int, unsigned int > _solve_generalized_helper (Mat mat_A, Mat mat_B, int nev, int ncv, const double tol, const unsigned int m_its)
void set_slepc_solver_type ()
void set_slepc_problem_type ()
void set_slepc_position_of_spectrum ()
Static Private Member Functions
static PetscErrorCode _petsc_shell_matrix_mult (Mat mat, Vec arg, Vec dest)
static PetscErrorCode _petsc_shell_matrix_get_diagonal (Mat mat, Vec dest)
Private Attributes
EPS _eps
Detailed Description
template<typename T>
class libMesh::SlepcEigenSolver< T >
EigenSolver implementation based on SLEPc.
This class provides an interface to the SLEPc eigenvalue solver library from http://slepc.upv.es/.
Author
Steffen Peterson
Date
2005
Definition at line 50 of file slepc_eigen_solver.h.
Member Typedef Documentation
Counts
typedef std::map<std::string, std::pair<unsigned int, unsigned int> > libMesh::ReferenceCounter::Counts protected inherited
Data structure to log the information. The log is identified by the class name.
Definition at line 117 of file reference_counter.h.
Constructor & Destructor Documentation
SlepcEigenSolver()
template<typename T > libMesh::SlepcEigenSolver< T >::SlepcEigenSolver (const Parallel::Communicator & comm_in)
Constructor. Initializes Petsc data structures
Definition at line 43 of file slepc_eigen_solver.C.
References libMesh::EigenSolver< T >::_eigen_problem_type, libMesh::EigenSolver< T >::_eigen_solver_type, libMesh::ARNOLDI, and libMesh::NHEP.
                                                                            :
   EigenSolver<T>(comm_in)
 {
   this->_eigen_solver_type  = ARNOLDI;
   this->_eigen_problem_type = NHEP;
 }
~SlepcEigenSolver()
template<typename T > libMesh::SlepcEigenSolver< T >::~SlepcEigenSolver ()
Destructor.
Definition at line 53 of file slepc_eigen_solver.C.
 {
   this->clear ();
 }
Member Function Documentation
_petsc_shell_matrix_get_diagonal()
template<typename T > PetscErrorCode libMesh::SlepcEigenSolver< T >::_petsc_shell_matrix_get_diagonal (Mat mat, Vec dest) static private
Internal function if shell matrix mode is used, this just calls the shell matrix's get_diagonal function. Required in order to use Jacobi preconditioning.
Definition at line 889 of file slepc_eigen_solver.C.
References libMesh::ParallelObject::comm(), libMesh::ShellMatrix< T >::get_diagonal(), and ierr.
 {
   // Get the matrix context.
   PetscErrorCode ierr=0;
   void * ctx;
   ierr = MatShellGetContext(mat,&ctx);
   Parallel::communicator comm;
   PetscObjectGetComm((PetscObject)mat,&comm);
   CHKERRABORT(comm,ierr);
   // Get user shell matrix object.
   const ShellMatrix<T> & shell_matrix = *static_cast<const ShellMatrix<T> *>(ctx);
   // Make \p NumericVector instances around the vector.
   PetscVector<T> dest_global(dest, shell_matrix.comm());
   // Call the user function.
   shell_matrix.get_diagonal(dest_global);
   return ierr;
 }
_petsc_shell_matrix_mult()
template<typename T > PetscErrorCode libMesh::SlepcEigenSolver< T >::_petsc_shell_matrix_mult (Mat mat, Vec arg, Vec dest) static private
Internal function if shell matrix mode is used, this just calls the shell matrix's matrix multiplication function. See PetscLinearSolver for a similar implementation.
Definition at line 864 of file slepc_eigen_solver.C.
References libMesh::ParallelObject::comm(), ierr, and libMesh::ShellMatrix< T >::vector_mult().
 {
   // Get the matrix context.
   PetscErrorCode ierr=0;
   void * ctx;
   ierr = MatShellGetContext(mat,&ctx);
   Parallel::communicator comm;
   PetscObjectGetComm((PetscObject)mat,&comm);
   CHKERRABORT(comm,ierr);
   // Get user shell matrix object.
   const ShellMatrix<T> & shell_matrix = *static_cast<const ShellMatrix<T> *>(ctx);
   // Make \p NumericVector instances around the vectors.
   PetscVector<T> arg_global(arg,   shell_matrix.comm());
   PetscVector<T> dest_global(dest, shell_matrix.comm());
   // Call the user function.
   shell_matrix.vector_mult(dest_global,arg_global);
   return ierr;
 }
_solve_generalized_helper()
template<typename T > std::pair< unsigned int, unsigned int > libMesh::SlepcEigenSolver< T >::_solve_generalized_helper (Mat mat_A, Mat mat_B, int nev, int ncv, const double tol, const unsigned int m_its) private
Helper function that actually performs the generalized eigensolve.
Definition at line 459 of file slepc_eigen_solver.C.
References ierr.
 {
   LOG_SCOPE("solve_generalized()", "SlepcEigenSolver");
   PetscErrorCode ierr=0;
   // converged eigen pairs and number of iterations
   PetscInt nconv=0;
   PetscInt its=0;
 #ifdef  DEBUG
   // The relative error.
   PetscReal error, re, im;
   // Pointer to vectors of the real parts, imaginary parts.
   PetscScalar kr, ki;
 #endif
   // Set operators.
   ierr = EPSSetOperators (_eps, mat_A, mat_B);
   LIBMESH_CHKERR(ierr);
   //set the problem type and the position of the spectrum
   set_slepc_problem_type();
   set_slepc_position_of_spectrum();
   // Set eigenvalues to be computed.
 #if SLEPC_VERSION_LESS_THAN(3,0,0)
   ierr = EPSSetDimensions (_eps, nev, ncv);
 #else
   ierr = EPSSetDimensions (_eps, nev, ncv, PETSC_DECIDE);
 #endif
   LIBMESH_CHKERR(ierr);
   // Set the tolerance and maximum iterations.
   ierr = EPSSetTolerances (_eps, tol, m_its);
   LIBMESH_CHKERR(ierr);
   // Set runtime options, e.g.,
   //      -eps_type <type>, -eps_nev <nev>, -eps_ncv <ncv>
   // Similar to PETSc, these options will override those specified
   // above as long as EPSSetFromOptions() is called _after_ any
   // other customization routines.
   ierr = EPSSetFromOptions (_eps);
   LIBMESH_CHKERR(ierr);
   // If the SolverConfiguration object is provided, use it to override
   // solver options.
   if (this->_solver_configuration)
     {
       this->_solver_configuration->configure_solver();
     }
   // Solve the eigenproblem.
   ierr = EPSSolve (_eps);
   LIBMESH_CHKERR(ierr);
   // Get the number of iterations.
   ierr = EPSGetIterationNumber (_eps, &its);
   LIBMESH_CHKERR(ierr);
   // Get number of converged eigenpairs.
   ierr = EPSGetConverged(_eps,&nconv);
   LIBMESH_CHKERR(ierr);
 #ifdef DEBUG
   // ierr = PetscPrintf(this->comm().get(),
   //         "\n Number of iterations: %d\n"
   //         " Number of converged eigenpairs: %d\n\n", its, nconv);
   // Display eigenvalues and relative errors.
   ierr = PetscPrintf(this->comm().get(),
                      "           k           ||Ax-kx||/|kx|\n"
                      "   ----------------- -----------------\n" );
   LIBMESH_CHKERR(ierr);
   for (PetscInt i=0; i<nconv; i++ )
     {
       ierr = EPSGetEigenpair(_eps, i, &kr, &ki, PETSC_NULL, PETSC_NULL);
       LIBMESH_CHKERR(ierr);
 #if SLEPC_VERSION_LESS_THAN(3,6,0)
       ierr = EPSComputeRelativeError(_eps, i, &error);
 #else
       ierr = EPSComputeError(_eps, i, EPS_ERROR_RELATIVE, &error);
 #endif
       LIBMESH_CHKERR(ierr);
 #ifdef LIBMESH_USE_COMPLEX_NUMBERS
       re = PetscRealPart(kr);
       im = PetscImaginaryPart(kr);
 #else
       re = kr;
       im = ki;
 #endif
       if (im != .0)
         {
           ierr = PetscPrintf(this->comm().get()," %9f%+9f i %12f\n", re, im, error);
           LIBMESH_CHKERR(ierr);
         }
       else
         {
           ierr = PetscPrintf(this->comm().get(),"   %12f       %12f\n", re, error);
           LIBMESH_CHKERR(ierr);
         }
     }
   ierr = PetscPrintf(this->comm().get(),"\n" );
   LIBMESH_CHKERR(ierr);
 #endif // DEBUG
   // return the number of converged eigenpairs
   // and the number of iterations
   return std::make_pair(nconv, its);
 }
_solve_standard_helper()
template<typename T > std::pair< unsigned int, unsigned int > libMesh::SlepcEigenSolver< T >::_solve_standard_helper (Mat mat, int nev, int ncv, const double tol, const unsigned int m_its) private
Helper function that actually performs the standard eigensolve.
Definition at line 163 of file slepc_eigen_solver.C.
References ierr.
 {
   LOG_SCOPE("solve_standard()", "SlepcEigenSolver");
   PetscErrorCode ierr=0;
   // converged eigen pairs and number of iterations
   PetscInt nconv=0;
   PetscInt its=0;
 #ifdef  DEBUG
   // The relative error.
   PetscReal error, re, im;
   // Pointer to vectors of the real parts, imaginary parts.
   PetscScalar kr, ki;
 #endif
   // Set operators.
   ierr = EPSSetOperators (_eps, mat, PETSC_NULL);
   LIBMESH_CHKERR(ierr);
   //set the problem type and the position of the spectrum
   set_slepc_problem_type();
   set_slepc_position_of_spectrum();
   // Set eigenvalues to be computed.
 #if SLEPC_VERSION_LESS_THAN(3,0,0)
   ierr = EPSSetDimensions (_eps, nev, ncv);
 #else
   ierr = EPSSetDimensions (_eps, nev, ncv, PETSC_DECIDE);
 #endif
   LIBMESH_CHKERR(ierr);
   // Set the tolerance and maximum iterations.
   ierr = EPSSetTolerances (_eps, tol, m_its);
   LIBMESH_CHKERR(ierr);
   // Set runtime options, e.g.,
   //      -eps_type <type>, -eps_nev <nev>, -eps_ncv <ncv>
   // Similar to PETSc, these options will override those specified
   // above as long as EPSSetFromOptions() is called _after_ any
   // other customization routines.
   ierr = EPSSetFromOptions (_eps);
   LIBMESH_CHKERR(ierr);
   // If the SolverConfiguration object is provided, use it to override
   // solver options.
   if (this->_solver_configuration)
     {
       this->_solver_configuration->configure_solver();
     }
   // Solve the eigenproblem.
   ierr = EPSSolve (_eps);
   LIBMESH_CHKERR(ierr);
   // Get the number of iterations.
   ierr = EPSGetIterationNumber (_eps, &its);
   LIBMESH_CHKERR(ierr);
   // Get number of converged eigenpairs.
   ierr = EPSGetConverged(_eps,&nconv);
   LIBMESH_CHKERR(ierr);
 #ifdef DEBUG
   // ierr = PetscPrintf(this->comm().get(),
   //         "\n Number of iterations: %d\n"
   //         " Number of converged eigenpairs: %d\n\n", its, nconv);
   // Display eigenvalues and relative errors.
   ierr = PetscPrintf(this->comm().get(),
                      "           k           ||Ax-kx||/|kx|\n"
                      "   ----------------- -----------------\n" );
   LIBMESH_CHKERR(ierr);
   for (PetscInt i=0; i<nconv; i++ )
     {
       ierr = EPSGetEigenpair(_eps, i, &kr, &ki, PETSC_NULL, PETSC_NULL);
       LIBMESH_CHKERR(ierr);
 #if SLEPC_VERSION_LESS_THAN(3,6,0)
       ierr = EPSComputeRelativeError(_eps, i, &error);
 #else
       ierr = EPSComputeError(_eps, i, EPS_ERROR_RELATIVE, &error);
 #endif
       LIBMESH_CHKERR(ierr);
 #ifdef LIBMESH_USE_COMPLEX_NUMBERS
       re = PetscRealPart(kr);
       im = PetscImaginaryPart(kr);
 #else
       re = kr;
       im = ki;
 #endif
       if (im != .0)
         {
           ierr = PetscPrintf(this->comm().get()," %9f%+9f i %12f\n", re, im, error);
           LIBMESH_CHKERR(ierr);
         }
       else
         {
           ierr = PetscPrintf(this->comm().get(),"   %12f       %12f\n", re, error);
           LIBMESH_CHKERR(ierr);
         }
     }
   ierr = PetscPrintf(this->comm().get(),"\n" );
   LIBMESH_CHKERR(ierr);
 #endif // DEBUG
   // return the number of converged eigenpairs
   // and the number of iterations
   return std::make_pair(nconv, its);
 }
attach_deflation_space()
template<typename T > void libMesh::SlepcEigenSolver< T >::attach_deflation_space (NumericVector< T > & deflation_vector) override virtual
Attach a deflation space defined by a single vector.
Implements libMesh::EigenSolver< T >.
Definition at line 814 of file slepc_eigen_solver.C.
References ierr, libMesh::TriangleWrapper::init(), and libMesh::PetscVector< T >::vec().
 {
   this->init();
   PetscErrorCode ierr = 0;
   // Make sure the input vector is actually a PetscVector
   PetscVector<T> * deflation_vector_petsc_vec =
     dynamic_cast<PetscVector<T> *>(&deflation_vector_in);
   if (!deflation_vector_petsc_vec)
     libmesh_error_msg("Error attaching deflation space: input vector must be a PetscVector.");
   // Get a handle for the underlying Vec.
   Vec deflation_vector = deflation_vector_petsc_vec->vec();
 #if SLEPC_VERSION_LESS_THAN(3,1,0)
   ierr = EPSAttachDeflationSpace(_eps, 1, &deflation_vector, PETSC_FALSE);
 #else
   ierr = EPSSetDeflationSpace(_eps, 1, &deflation_vector);
 #endif
   LIBMESH_CHKERR(ierr);
 }
build()
template<typename T > std::unique_ptr< EigenSolver< T > > libMesh::EigenSolver< T >::build (const Parallel::Communicator & comm_in, const SolverPackage solver_package = SLEPC_SOLVERS) static inherited
Builds an EigenSolver using the linear solver package specified by solver_package
Definition at line 59 of file eigen_solver.C.
References libMesh::SLEPC_SOLVERS.
 {
   // Build the appropriate solver
   switch (solver_package)
     {
 #ifdef LIBMESH_HAVE_SLEPC
     case SLEPC_SOLVERS:
       return libmesh_make_unique<SlepcEigenSolver<T>>(comm);
 #endif
     default:
       libmesh_error_msg("ERROR:  Unrecognized eigen solver package: " << solver_package);
     }
   return std::unique_ptr<EigenSolver<T>>();
 }
clear()
template<typename T > void libMesh::SlepcEigenSolver< T >::clear () override virtual
Release all memory and clear data structures.
Reimplemented from libMesh::EigenSolver< T >.
Definition at line 61 of file slepc_eigen_solver.C.
References libMesh::libMeshPrivateData::_is_initialized, ierr, libMesh::initialized(), and libMesh::KRYLOVSCHUR.
 {
   if (this->initialized())
     {
       this->_is_initialized = false;
       PetscErrorCode ierr=0;
       ierr = LibMeshEPSDestroy(&_eps);
       LIBMESH_CHKERR(ierr);
       // SLEPc default eigenproblem solver
       this->_eigen_solver_type = KRYLOVSCHUR;
     }
 }
comm()
const Parallel::Communicator& libMesh::ParallelObject::comm () const inline inherited
Returns
A reference to the Parallel::Communicator object used by this mesh.
Definition at line 89 of file parallel_object.h.
References libMesh::ParallelObject::_communicator.
Referenced by libMesh::__libmesh_petsc_diff_solver_jacobian(), libMesh::__libmesh_petsc_diff_solver_monitor(), libMesh::__libmesh_petsc_diff_solver_residual(), libMesh::__libmesh_tao_equality_constraints(), libMesh::__libmesh_tao_equality_constraints_jacobian(), libMesh::__libmesh_tao_gradient(), libMesh::__libmesh_tao_hessian(), libMesh::__libmesh_tao_inequality_constraints(), libMesh::__libmesh_tao_inequality_constraints_jacobian(), libMesh::__libmesh_tao_objective(), libMesh::MeshRefinement::_coarsen_elements(), libMesh::ExactSolution::_compute_error(), libMesh::UniformRefinementEstimator::_estimate_error(), libMesh::BoundaryInfo::_find_id_maps(), libMesh::SlepcEigenSolver< T >::_petsc_shell_matrix_get_diagonal(), libMesh::PetscLinearSolver< T >::_petsc_shell_matrix_get_diagonal(), libMesh::SlepcEigenSolver< T >::_petsc_shell_matrix_mult(), libMesh::PetscLinearSolver< T >::_petsc_shell_matrix_mult(), libMesh::PetscLinearSolver< T >::_petsc_shell_matrix_mult_add(), libMesh::EquationSystems::_read_impl(), libMesh::MeshRefinement::_refine_elements(), libMesh::MeshRefinement::_smooth_flags(), libMesh::PetscDMWrapper::add_dofs_helper(), libMesh::PetscDMWrapper::add_dofs_to_section(), libMesh::ImplicitSystem::add_matrix(), libMesh::System::add_vector(), libMesh::UnstructuredMesh::all_second_order(), libMesh::MeshTools::Modification::all_tri(), libMesh::LaplaceMeshSmoother::allgather_graph(), libMesh::FEMSystem::assemble_qoi(), libMesh::MeshCommunication::assign_global_indices(), libMesh::DofMap::attach_matrix(), libMesh::MeshTools::Generation::build_extrusion(), libMesh::BoundaryInfo::build_node_list_from_side_list(), libMesh::EquationSystems::build_parallel_elemental_solution_vector(), libMesh::EquationSystems::build_parallel_solution_vector(), libMesh::PetscDMWrapper::build_section(), libMesh::PetscDMWrapper::build_sf(), libMesh::MeshBase::cache_elem_dims(), libMesh::System::calculate_norm(), libMesh::DofMap::check_dirichlet_bcid_consistency(), libMesh::PetscDMWrapper::check_section_n_dofs(), libMesh::Nemesis_IO_Helper::compute_num_global_elem_blocks(), libMesh::Nemesis_IO_Helper::compute_num_global_nodesets(), libMesh::Nemesis_IO_Helper::compute_num_global_sidesets(), libMesh::Problem_Interface::computeF(), libMesh::Problem_Interface::computeJacobian(), libMesh::Problem_Interface::computePreconditioner(), libMesh::ExodusII_IO::copy_elemental_solution(), libMesh::MeshTools::correct_node_proc_ids(), libMesh::MeshTools::create_bounding_box(), libMesh::MeshTools::create_nodal_bounding_box(), libMesh::MeshRefinement::create_parent_error_vector(), libMesh::MeshTools::create_processor_bounding_box(), libMesh::MeshTools::create_subdomain_bounding_box(), libMesh::MeshCommunication::delete_remote_elements(), libMesh::DofMap::distribute_dofs(), DMlibMeshFunction(), DMlibMeshJacobian(), DMlibMeshSetSystem_libMesh(), DMVariableBounds_libMesh(), libMesh::MeshRefinement::eliminate_unrefined_patches(), libMesh::EpetraVector< T >::EpetraVector(), libMesh::WeightedPatchRecoveryErrorEstimator::estimate_error(), libMesh::PatchRecoveryErrorEstimator::estimate_error(), libMesh::JumpErrorEstimator::estimate_error(), libMesh::AdjointRefinementEstimator::estimate_error(), libMesh::ExactErrorEstimator::estimate_error(), libMesh::MeshRefinement::flag_elements_by_elem_fraction(), libMesh::MeshRefinement::flag_elements_by_error_fraction(), libMesh::MeshRefinement::flag_elements_by_nelem_target(), libMesh::CondensedEigenSystem::get_eigenpair(), libMesh::DofMap::get_info(), libMesh::ImplicitSystem::get_linear_solver(), libMesh::LocationMap< T >::init(), libMesh::TimeSolver::init(), libMesh::SystemSubsetBySubdomain::init(), libMesh::PetscDMWrapper::init_and_attach_petscdm(), libMesh::EigenSystem::init_data(), libMesh::EigenSystem::init_matrices(), libMesh::OptimizationSystem::initialize_equality_constraints_storage(), libMesh::OptimizationSystem::initialize_inequality_constraints_storage(), libMesh::MeshTools::libmesh_assert_consistent_distributed(), libMesh::MeshTools::libmesh_assert_consistent_distributed_nodes(), libMesh::MeshTools::libmesh_assert_contiguous_dof_ids(), libMesh::MeshTools::libmesh_assert_parallel_consistent_new_node_procids(), libMesh::MeshTools::libmesh_assert_parallel_consistent_procids< Elem >(), libMesh::MeshTools::libmesh_assert_parallel_consistent_procids< Node >(), libMesh::MeshTools::libmesh_assert_topology_consistent_procids< Node >(), libMesh::MeshTools::libmesh_assert_valid_boundary_ids(), libMesh::MeshTools::libmesh_assert_valid_dof_ids(), libMesh::MeshTools::libmesh_assert_valid_neighbors(), libMesh::DistributedMesh::libmesh_assert_valid_parallel_flags(), libMesh::DistributedMesh::libmesh_assert_valid_parallel_object_ids(), libMesh::DistributedMesh::libmesh_assert_valid_parallel_p_levels(), libMesh::MeshTools::libmesh_assert_valid_refinement_flags(), libMesh::MeshTools::libmesh_assert_valid_unique_ids(), libMesh::libmesh_petsc_snes_fd_residual(), libMesh::libmesh_petsc_snes_jacobian(), libMesh::libmesh_petsc_snes_mffd_residual(), libMesh::libmesh_petsc_snes_postcheck(), libMesh::libmesh_petsc_snes_residual(), libMesh::libmesh_petsc_snes_residual_helper(), libMesh::MeshRefinement::limit_level_mismatch_at_edge(), libMesh::MeshRefinement::limit_level_mismatch_at_node(), libMesh::MeshRefinement::limit_overrefined_boundary(), libMesh::MeshRefinement::limit_underrefined_boundary(), libMesh::MeshRefinement::make_coarsening_compatible(), libMesh::MeshCommunication::make_elems_parallel_consistent(), libMesh::MeshRefinement::make_flags_parallel_consistent(), libMesh::MeshCommunication::make_new_node_proc_ids_parallel_consistent(), libMesh::MeshCommunication::make_new_nodes_parallel_consistent(), libMesh::MeshCommunication::make_node_ids_parallel_consistent(), libMesh::MeshCommunication::make_node_proc_ids_parallel_consistent(), libMesh::MeshCommunication::make_node_unique_ids_parallel_consistent(), libMesh::MeshCommunication::make_nodes_parallel_consistent(), libMesh::MeshCommunication::make_p_levels_parallel_consistent(), libMesh::MeshRefinement::make_refinement_compatible(), libMesh::FEMSystem::mesh_position_set(), libMesh::DistributedMesh::n_active_elem(), libMesh::MeshTools::n_active_levels(), libMesh::BoundaryInfo::n_boundary_conds(), libMesh::BoundaryInfo::n_edge_conds(), libMesh::CondensedEigenSystem::n_global_non_condensed_dofs(), libMesh::MeshTools::n_levels(), libMesh::BoundaryInfo::n_nodeset_conds(), libMesh::MeshTools::n_p_levels(), libMesh::BoundaryInfo::n_shellface_conds(), libMesh::DistributedMesh::parallel_max_elem_id(), libMesh::DistributedMesh::parallel_max_node_id(), libMesh::ReplicatedMesh::parallel_max_unique_id(), libMesh::DistributedMesh::parallel_max_unique_id(), libMesh::DistributedMesh::parallel_n_elem(), libMesh::DistributedMesh::parallel_n_nodes(), libMesh::SparsityPattern::Build::parallel_sync(), libMesh::MeshTools::paranoid_n_levels(), libMesh::petsc_auto_fieldsplit(), libMesh::System::point_gradient(), libMesh::System::point_hessian(), libMesh::System::point_value(), libMesh::MeshBase::prepare_for_use(), libMesh::Nemesis_IO::read(), libMesh::XdrIO::read(), libMesh::CheckpointIO::read_header(), libMesh::XdrIO::read_header(), libMesh::System::read_header(), libMesh::System::read_legacy_data(), libMesh::System::read_SCALAR_dofs(), libMesh::XdrIO::read_serialized_bc_names(), libMesh::XdrIO::read_serialized_bcs_helper(), libMesh::System::read_serialized_blocked_dof_objects(), libMesh::XdrIO::read_serialized_connectivity(), libMesh::XdrIO::read_serialized_nodes(), libMesh::XdrIO::read_serialized_nodesets(), libMesh::XdrIO::read_serialized_subdomain_names(), libMesh::System::read_serialized_vector(), libMesh::MeshBase::recalculate_n_partitions(), libMesh::MeshRefinement::refine_and_coarsen_elements(), libMesh::DistributedMesh::renumber_dof_objects(), libMesh::CheckpointIO::select_split_config(), libMesh::DofMap::set_nonlocal_dof_objects(), libMesh::PetscDMWrapper::set_point_range_in_section(), libMesh::PetscDiffSolver::setup_petsc_data(), libMesh::LaplaceMeshSmoother::smooth(), libMesh::split_mesh(), libMesh::MeshBase::subdomain_ids(), libMesh::BoundaryInfo::sync(), libMesh::MeshRefinement::test_level_one(), libMesh::MeshRefinement::test_unflagged(), libMesh::MeshTools::total_weight(), libMesh::MeshRefinement::uniformly_coarsen(), libMesh::NameBasedIO::write(), libMesh::XdrIO::write(), libMesh::System::write_SCALAR_dofs(), libMesh::XdrIO::write_serialized_bcs_helper(), libMesh::System::write_serialized_blocked_dof_objects(), libMesh::XdrIO::write_serialized_connectivity(), libMesh::XdrIO::write_serialized_nodes(), and libMesh::XdrIO::write_serialized_nodesets().
   { return _communicator; }
disable_print_counter_info()
void libMesh::ReferenceCounter::disable_print_counter_info () static inherited
Definition at line 106 of file reference_counter.C.
References libMesh::ReferenceCounter::_enable_print_counter.
Referenced by libMesh::LibMeshInit::LibMeshInit().
 {
   _enable_print_counter = false;
   return;
 }
eigen_problem_type()
template<typename T > EigenProblemType libMesh::EigenSolver< T >::eigen_problem_type () const inline inherited
Returns
The type of the eigen problem.
Definition at line 135 of file eigen_solver.h.
References libMesh::EigenSolver< T >::_eigen_problem_type.
 { return _eigen_problem_type;}
eigen_solver_type()
template<typename T > EigenSolverType libMesh::EigenSolver< T >::eigen_solver_type () const inline inherited
Returns
The type of eigensolver to use.
Definition at line 130 of file eigen_solver.h.
References libMesh::EigenSolver< T >::_eigen_solver_type.
 { return _eigen_solver_type; }
enable_print_counter_info()
void libMesh::ReferenceCounter::enable_print_counter_info () static inherited
Methods to enable/disable the reference counter output from print_info()
Definition at line 100 of file reference_counter.C.
References libMesh::ReferenceCounter::_enable_print_counter.
 {
   _enable_print_counter = true;
   return;
 }
eps()
template<typename T > EPS libMesh::SlepcEigenSolver< T >::eps () inline
Returns
The raw SLEPc EPS pointer.
Definition at line 214 of file slepc_eigen_solver.h.
References libMesh::SlepcEigenSolver< T >::_eps, and libMesh::SlepcEigenSolver< T >::init().
 { this->init(); return _eps; }
get_close_matrix_before_solve()
template<typename T > bool libMesh::EigenSolver< T >::get_close_matrix_before_solve () const inline inherited
Returns
The value of the flag which controls whether libmesh closes the eigenproblem matrices before solving. true by default.
Definition at line 101 of file eigen_solver.h.
References libMesh::EigenSolver< T >::_close_matrix_before_solve.
   {
     libmesh_experimental();
     return _close_matrix_before_solve;
   }
get_eigenpair()
template<typename T > std::pair< Real, Real > libMesh::SlepcEigenSolver< T >::get_eigenpair (dof_id_type i, NumericVector< T > & solution_in) override virtual
Returns
The real and imaginary part of the ith eigenvalue and copies the respective eigenvector to the solution vector.
Note
The eigenpair may be complex even for real-valued matrices.
Implements libMesh::EigenSolver< T >.
Definition at line 738 of file slepc_eigen_solver.C.
References libMesh::PetscVector< T >::close(), ierr, and libMesh::PetscVector< T >::vec().
 {
   PetscErrorCode ierr=0;
   PetscReal re, im;
   // Make sure the NumericVector passed in is really a PetscVector
   PetscVector<T> * solution = dynamic_cast<PetscVector<T> *>(&solution_in);
   if (!solution)
     libmesh_error_msg("Error getting eigenvector: input vector must be a PetscVector.");
   // real and imaginary part of the ith eigenvalue.
   PetscScalar kr, ki;
   solution->close();
   ierr = EPSGetEigenpair(_eps, i, &kr, &ki, solution->vec(), PETSC_NULL);
   LIBMESH_CHKERR(ierr);
 #ifdef LIBMESH_USE_COMPLEX_NUMBERS
   re = PetscRealPart(kr);
   im = PetscImaginaryPart(kr);
 #else
   re = kr;
   im = ki;
 #endif
   return std::make_pair(re, im);
 }
get_eigenvalue()
template<typename T > std::pair< Real, Real > libMesh::SlepcEigenSolver< T >::get_eigenvalue (dof_id_type i) override virtual
Same as above, but does not copy the eigenvector.
Implements libMesh::EigenSolver< T >.
Definition at line 772 of file slepc_eigen_solver.C.
References ierr.
 {
   PetscErrorCode ierr=0;
   PetscReal re, im;
   // real and imaginary part of the ith eigenvalue.
   PetscScalar kr, ki;
   ierr = EPSGetEigenvalue(_eps, i, &kr, &ki);
   LIBMESH_CHKERR(ierr);
 #ifdef LIBMESH_USE_COMPLEX_NUMBERS
   re = PetscRealPart(kr);
   im = PetscImaginaryPart(kr);
 #else
   re = kr;
   im = ki;
 #endif
   return std::make_pair(re, im);
 }
get_info()
std::string libMesh::ReferenceCounter::get_info () static inherited
Gets a string containing the reference information.
Definition at line 47 of file reference_counter.C.
References libMesh::ReferenceCounter::_counts, and libMesh::Quality::name().
Referenced by libMesh::ReferenceCounter::print_info().
 {
 #if defined(LIBMESH_ENABLE_REFERENCE_COUNTING) && defined(DEBUG)
   std::ostringstream oss;
   oss << '\n'
       << " ---------------------------------------------------------------------------- \n"
       << "| Reference count information                                                |\n"
       << " ---------------------------------------------------------------------------- \n";
   for (const auto & pr : _counts)
     {
       const std::string name(pr.first);
       const unsigned int creations    = pr.second.first;
       const unsigned int destructions = pr.second.second;
       oss << "| " << name << " reference count information:\n"
           << "|  Creations:    " << creations    << '\n'
           << "|  Destructions: " << destructions << '\n';
     }
   oss << " ---------------------------------------------------------------------------- \n";
   return oss.str();
 #else
   return "";
 #endif
 }
get_relative_error()
template<typename T > Real libMesh::SlepcEigenSolver< T >::get_relative_error (unsigned int i)
Returns
The relative error of the ith eigenpair (or the equivalent for a general eigenvalue problem).
Definition at line 797 of file slepc_eigen_solver.C.
References ierr.
 {
   PetscErrorCode ierr=0;
   PetscReal error;
 #if SLEPC_VERSION_LESS_THAN(3,6,0)
   ierr = EPSComputeRelativeError(_eps, i, &error);
 #else
   ierr = EPSComputeError(_eps, i, EPS_ERROR_RELATIVE, &error);
 #endif
   LIBMESH_CHKERR(ierr);
   return error;
 }
increment_constructor_count()
void libMesh::ReferenceCounter::increment_constructor_count (const std::string & name) inline protected inherited
Increments the construction counter. Should be called in the constructor of any derived class that will be reference counted.
Definition at line 181 of file reference_counter.h.
References libMesh::ReferenceCounter::_counts, libMesh::Quality::name(), and libMesh::Threads::spin_mtx.
Referenced by libMesh::ReferenceCountedObject< RBParametrized >::ReferenceCountedObject().
 {
   Threads::spin_mutex::scoped_lock lock(Threads::spin_mtx);
   std::pair<unsigned int, unsigned int> & p = _counts[name];
   p.first++;
 }
increment_destructor_count()
void libMesh::ReferenceCounter::increment_destructor_count (const std::string & name) inline protected inherited
Increments the destruction counter. Should be called in the destructor of any derived class that will be reference counted.
Definition at line 194 of file reference_counter.h.
References libMesh::ReferenceCounter::_counts, libMesh::Quality::name(), and libMesh::Threads::spin_mtx.
Referenced by libMesh::ReferenceCountedObject< RBParametrized >::~ReferenceCountedObject().
 {
   Threads::spin_mutex::scoped_lock lock(Threads::spin_mtx);
   std::pair<unsigned int, unsigned int> & p = _counts[name];
   p.second++;
 }
init()
template<typename T > void libMesh::SlepcEigenSolver< T >::init () override virtual
Initialize data structures if not done so already.
Implements libMesh::EigenSolver< T >.
Definition at line 80 of file slepc_eigen_solver.C.
References libMesh::libMeshPrivateData::_is_initialized, ierr, and libMesh::initialized().
Referenced by libMesh::SlepcEigenSolver< T >::eps().
 {
   PetscErrorCode ierr=0;
   // Initialize the data structures if not done so already.
   if (!this->initialized())
     {
       this->_is_initialized = true;
       // Create the eigenproblem solver context
       ierr = EPSCreate (this->comm().get(), &_eps);
       LIBMESH_CHKERR(ierr);
       // Set user-specified  solver
       set_slepc_solver_type();
     }
 }
initialized()
template<typename T > bool libMesh::EigenSolver< T >::initialized () const inline inherited
Returns
true if the data structures are initialized, false otherwise.
Definition at line 94 of file eigen_solver.h.
References libMesh::EigenSolver< T >::_is_initialized.
 { return _is_initialized; }
n_objects()
static unsigned int libMesh::ReferenceCounter::n_objects () inline static inherited
Prints the number of outstanding (created, but not yet destroyed) objects.
Definition at line 83 of file reference_counter.h.
References libMesh::ReferenceCounter::_n_objects.
   { return _n_objects; }
n_processors()
processor_id_type libMesh::ParallelObject::n_processors () const inline inherited
Returns
The number of processors in the group.
Definition at line 95 of file parallel_object.h.
References libMesh::ParallelObject::_communicator, and libMesh::Parallel::Communicator::size().
Referenced by libMesh::BoundaryInfo::_find_id_maps(), libMesh::PetscDMWrapper::add_dofs_to_section(), libMesh::DistributedMesh::add_elem(), libMesh::DistributedMesh::add_node(), libMesh::LaplaceMeshSmoother::allgather_graph(), libMesh::FEMSystem::assembly(), libMesh::AztecLinearSolver< T >::AztecLinearSolver(), libMesh::BoundaryInfo::build_node_list_from_side_list(), libMesh::EquationSystems::build_parallel_elemental_solution_vector(), libMesh::DistributedMesh::clear(), libMesh::Nemesis_IO_Helper::compute_border_node_ids(), libMesh::Nemesis_IO_Helper::construct_nemesis_filename(), libMesh::UnstructuredMesh::create_pid_mesh(), libMesh::MeshTools::create_processor_bounding_box(), libMesh::DofMap::distribute_dofs(), libMesh::DofMap::distribute_local_dofs_node_major(), libMesh::DofMap::distribute_local_dofs_var_major(), libMesh::EnsightIO::EnsightIO(), libMesh::MeshBase::get_info(), libMesh::SystemSubsetBySubdomain::init(), libMesh::PetscDMWrapper::init_and_attach_petscdm(), libMesh::Nemesis_IO_Helper::initialize(), libMesh::DistributedMesh::insert_elem(), libMesh::MeshTools::libmesh_assert_contiguous_dof_ids(), libMesh::MeshTools::libmesh_assert_parallel_consistent_new_node_procids(), libMesh::MeshTools::libmesh_assert_parallel_consistent_procids< Elem >(), libMesh::MeshTools::libmesh_assert_parallel_consistent_procids< Node >(), libMesh::MeshTools::libmesh_assert_topology_consistent_procids< Node >(), libMesh::MeshTools::libmesh_assert_valid_boundary_ids(), libMesh::MeshTools::libmesh_assert_valid_dof_ids(), libMesh::MeshTools::libmesh_assert_valid_neighbors(), libMesh::MeshTools::libmesh_assert_valid_refinement_flags(), libMesh::DofMap::local_variable_indices(), libMesh::MeshRefinement::make_coarsening_compatible(), libMesh::MeshBase::n_active_elem_on_proc(), libMesh::MeshBase::n_elem_on_proc(), libMesh::MeshBase::n_nodes_on_proc(), libMesh::MeshBase::partition(), libMesh::PetscLinearSolver< T >::PetscLinearSolver(), libMesh::System::point_gradient(), libMesh::System::point_hessian(), libMesh::System::point_value(), libMesh::NameBasedIO::read(), libMesh::Nemesis_IO::read(), libMesh::CheckpointIO::read(), libMesh::CheckpointIO::read_connectivity(), libMesh::XdrIO::read_header(), libMesh::CheckpointIO::read_nodes(), libMesh::System::read_parallel_data(), libMesh::System::read_SCALAR_dofs(), libMesh::System::read_serialized_blocked_dof_objects(), libMesh::System::read_serialized_vector(), libMesh::DistributedMesh::renumber_dof_objects(), libMesh::DofMap::set_nonlocal_dof_objects(), libMesh::PetscDMWrapper::set_point_range_in_section(), libMesh::MeshRefinement::uniformly_coarsen(), libMesh::DistributedMesh::update_parallel_id_counts(), libMesh::GMVIO::write_binary(), libMesh::GMVIO::write_discontinuous_gmv(), libMesh::System::write_parallel_data(), libMesh::System::write_SCALAR_dofs(), libMesh::XdrIO::write_serialized_bcs_helper(), libMesh::System::write_serialized_blocked_dof_objects(), libMesh::XdrIO::write_serialized_connectivity(), libMesh::XdrIO::write_serialized_nodes(), and libMesh::XdrIO::write_serialized_nodesets().
   { return cast_int<processor_id_type>(_communicator.size()); }
position_of_spectrum()
template<typename T > PositionOfSpectrum libMesh::EigenSolver< T >::position_of_spectrum () const inline inherited
Returns
The position of the spectrum to compute.
Definition at line 140 of file eigen_solver.h.
References libMesh::EigenSolver< T >::_position_of_spectrum.
   { return _position_of_spectrum;}
print_info()
void libMesh::ReferenceCounter::print_info (std::ostream & out = libMesh::out) static inherited
Prints the reference information, by default to libMesh::out.
Definition at line 87 of file reference_counter.C.
References libMesh::ReferenceCounter::_enable_print_counter, and libMesh::ReferenceCounter::get_info().
 {
   if (_enable_print_counter)
     out_stream << ReferenceCounter::get_info();
 }
processor_id()
processor_id_type libMesh::ParallelObject::processor_id () const inline inherited
Returns
The rank of this processor in the group.
Definition at line 101 of file parallel_object.h.
References libMesh::ParallelObject::_communicator, and libMesh::Parallel::Communicator::rank().
Referenced by libMesh::BoundaryInfo::_find_id_maps(), libMesh::EquationSystems::_read_impl(), libMesh::PetscDMWrapper::add_dofs_to_section(), libMesh::DistributedMesh::add_elem(), libMesh::BoundaryInfo::add_elements(), libMesh::DofMap::add_neighbors_to_send_list(), libMesh::DistributedMesh::add_node(), libMesh::UnstructuredMesh::all_second_order(), libMesh::MeshTools::Modification::all_tri(), libMesh::FEMSystem::assembly(), libMesh::EquationSystems::build_discontinuous_solution_vector(), libMesh::Nemesis_IO_Helper::build_element_and_node_maps(), libMesh::InfElemBuilder::build_inf_elem(), libMesh::BoundaryInfo::build_node_list_from_side_list(), libMesh::EquationSystems::build_parallel_elemental_solution_vector(), libMesh::DistributedMesh::clear(), libMesh::ExodusII_IO_Helper::close(), libMesh::Nemesis_IO_Helper::compute_border_node_ids(), libMesh::Nemesis_IO_Helper::compute_communication_map_parameters(), libMesh::Nemesis_IO_Helper::compute_internal_and_border_elems_and_internal_nodes(), libMesh::Nemesis_IO_Helper::compute_node_communication_maps(), libMesh::Nemesis_IO_Helper::compute_num_global_elem_blocks(), libMesh::Nemesis_IO_Helper::compute_num_global_nodesets(), libMesh::Nemesis_IO_Helper::compute_num_global_sidesets(), libMesh::Nemesis_IO_Helper::construct_nemesis_filename(), libMesh::MeshTools::correct_node_proc_ids(), libMesh::ExodusII_IO_Helper::create(), libMesh::DistributedMesh::delete_elem(), libMesh::DistributedMesh::delete_node(), libMesh::MeshCommunication::delete_remote_elements(), libMesh::DofMap::distribute_dofs(), libMesh::DofMap::distribute_local_dofs_node_major(), libMesh::DofMap::distribute_local_dofs_var_major(), libMesh::DistributedMesh::DistributedMesh(), libMesh::DofMap::end_dof(), libMesh::DofMap::end_old_dof(), libMesh::EnsightIO::EnsightIO(), libMesh::MeshFunction::find_element(), libMesh::MeshFunction::find_elements(), libMesh::UnstructuredMesh::find_neighbors(), libMesh::DofMap::first_dof(), libMesh::DofMap::first_old_dof(), libMesh::Nemesis_IO_Helper::get_cmap_params(), libMesh::Nemesis_IO_Helper::get_eb_info_global(), libMesh::Nemesis_IO_Helper::get_elem_cmap(), libMesh::Nemesis_IO_Helper::get_elem_map(), libMesh::MeshBase::get_info(), libMesh::DofMap::get_info(), libMesh::Nemesis_IO_Helper::get_init_global(), libMesh::Nemesis_IO_Helper::get_init_info(), libMesh::Nemesis_IO_Helper::get_loadbal_param(), libMesh::Nemesis_IO_Helper::get_node_cmap(), libMesh::Nemesis_IO_Helper::get_node_map(), libMesh::Nemesis_IO_Helper::get_ns_param_global(), libMesh::Nemesis_IO_Helper::get_ss_param_global(), libMesh::SparsityPattern::Build::handle_vi_vj(), libMesh::SystemSubsetBySubdomain::init(), libMesh::ExodusII_IO_Helper::initialize(), libMesh::ExodusII_IO_Helper::initialize_element_variables(), libMesh::ExodusII_IO_Helper::initialize_global_variables(), libMesh::ExodusII_IO_Helper::initialize_nodal_variables(), libMesh::DistributedMesh::insert_elem(), libMesh::DofMap::is_evaluable(), libMesh::SparsityPattern::Build::join(), libMesh::DofMap::last_dof(), libMesh::MeshTools::libmesh_assert_consistent_distributed(), libMesh::MeshTools::libmesh_assert_consistent_distributed_nodes(), libMesh::MeshTools::libmesh_assert_contiguous_dof_ids(), libMesh::MeshTools::libmesh_assert_parallel_consistent_procids< Elem >(), libMesh::MeshTools::libmesh_assert_valid_neighbors(), libMesh::DistributedMesh::libmesh_assert_valid_parallel_object_ids(), libMesh::DofMap::local_variable_indices(), libMesh::MeshRefinement::make_coarsening_compatible(), libMesh::MeshBase::n_active_local_elem(), libMesh::BoundaryInfo::n_boundary_conds(), libMesh::BoundaryInfo::n_edge_conds(), libMesh::DofMap::n_local_dofs(), libMesh::System::n_local_dofs(), libMesh::MeshBase::n_local_elem(), libMesh::MeshBase::n_local_nodes(), libMesh::BoundaryInfo::n_nodeset_conds(), libMesh::BoundaryInfo::n_shellface_conds(), libMesh::SparsityPattern::Build::operator()(), libMesh::DistributedMesh::own_node(), libMesh::System::point_gradient(), libMesh::System::point_hessian(), libMesh::System::point_value(), libMesh::Nemesis_IO_Helper::put_cmap_params(), libMesh::Nemesis_IO_Helper::put_elem_cmap(), libMesh::Nemesis_IO_Helper::put_elem_map(), libMesh::Nemesis_IO_Helper::put_loadbal_param(), libMesh::Nemesis_IO_Helper::put_node_cmap(), libMesh::Nemesis_IO_Helper::put_node_map(), libMesh::NameBasedIO::read(), libMesh::Nemesis_IO::read(), libMesh::XdrIO::read(), libMesh::CheckpointIO::read(), libMesh::ExodusII_IO_Helper::read_elem_num_map(), libMesh::ExodusII_IO_Helper::read_global_values(), libMesh::CheckpointIO::read_header(), libMesh::XdrIO::read_header(), libMesh::System::read_header(), libMesh::System::read_legacy_data(), libMesh::ExodusII_IO_Helper::read_node_num_map(), libMesh::System::read_parallel_data(), libMesh::System::read_SCALAR_dofs(), libMesh::XdrIO::read_serialized_bc_names(), libMesh::XdrIO::read_serialized_bcs_helper(), libMesh::System::read_serialized_blocked_dof_objects(), libMesh::XdrIO::read_serialized_connectivity(), libMesh::System::read_serialized_data(), libMesh::XdrIO::read_serialized_nodes(), libMesh::XdrIO::read_serialized_nodesets(), libMesh::XdrIO::read_serialized_subdomain_names(), libMesh::System::read_serialized_vector(), libMesh::System::read_serialized_vectors(), libMesh::DistributedMesh::renumber_dof_objects(), libMesh::CheckpointIO::select_split_config(), libMesh::DofMap::set_nonlocal_dof_objects(), libMesh::PetscDMWrapper::set_point_range_in_section(), libMesh::LaplaceMeshSmoother::smooth(), libMesh::MeshTools::total_weight(), libMesh::MeshRefinement::uniformly_coarsen(), libMesh::Parallel::Packing< T >::unpack(), libMesh::DistributedMesh::update_parallel_id_counts(), libMesh::NameBasedIO::write(), libMesh::XdrIO::write(), libMesh::CheckpointIO::write(), libMesh::EquationSystems::write(), libMesh::GMVIO::write_discontinuous_gmv(), libMesh::ExodusII_IO::write_element_data(), libMesh::ExodusII_IO_Helper::write_element_values(), libMesh::ExodusII_IO_Helper::write_elements(), libMesh::ExodusII_IO::write_global_data(), libMesh::ExodusII_IO_Helper::write_global_values(), libMesh::System::write_header(), libMesh::ExodusII_IO::write_information_records(), libMesh::ExodusII_IO_Helper::write_information_records(), libMesh::ExodusII_IO_Helper::write_nodal_coordinates(), libMesh::UCDIO::write_nodal_data(), libMesh::ExodusII_IO::write_nodal_data(), libMesh::ExodusII_IO::write_nodal_data_discontinuous(), libMesh::ExodusII_IO_Helper::write_nodal_values(), libMesh::Nemesis_IO_Helper::write_nodesets(), libMesh::ExodusII_IO_Helper::write_nodesets(), libMesh::System::write_parallel_data(), libMesh::System::write_SCALAR_dofs(), libMesh::XdrIO::write_serialized_bc_names(), libMesh::XdrIO::write_serialized_bcs_helper(), libMesh::System::write_serialized_blocked_dof_objects(), libMesh::XdrIO::write_serialized_connectivity(), libMesh::System::write_serialized_data(), libMesh::XdrIO::write_serialized_nodes(), libMesh::XdrIO::write_serialized_nodesets(), libMesh::XdrIO::write_serialized_subdomain_names(), libMesh::System::write_serialized_vector(), libMesh::System::write_serialized_vectors(), libMesh::Nemesis_IO_Helper::write_sidesets(), libMesh::ExodusII_IO_Helper::write_sidesets(), libMesh::ExodusII_IO::write_timestep(), libMesh::ExodusII_IO_Helper::write_timestep(), and libMesh::ExodusII_IO::write_timestep_discontinuous().
   { return cast_int<processor_id_type>(_communicator.rank()); }
set_close_matrix_before_solve()
template<typename T > void libMesh::EigenSolver< T >::set_close_matrix_before_solve (bool val) inline inherited
Set the flag which controls whether libmesh closes the eigenproblem matrices before solving.
Definition at line 111 of file eigen_solver.h.
References libMesh::EigenSolver< T >::_close_matrix_before_solve.
   {
     libmesh_experimental();
     _close_matrix_before_solve = val;
   }
set_eigenproblem_type()
template<typename T > void libMesh::EigenSolver< T >::set_eigenproblem_type (EigenProblemType ept) inline inherited
Sets the type of the eigenproblem.
Definition at line 152 of file eigen_solver.h.
References libMesh::EigenSolver< T >::_eigen_problem_type.
   {_eigen_problem_type = ept;}
set_eigensolver_type()
template<typename T > void libMesh::EigenSolver< T >::set_eigensolver_type (const EigenSolverType est) inline inherited
Sets the type of eigensolver to use.
Definition at line 146 of file eigen_solver.h.
References libMesh::EigenSolver< T >::_eigen_solver_type.
   { _eigen_solver_type = est; }
set_initial_space()
template<typename T > void libMesh::SlepcEigenSolver< T >::set_initial_space (NumericVector< T > & initial_space_in) override virtual
Use initial_space_in as the initial guess.
Implements libMesh::EigenSolver< T >.
Definition at line 839 of file slepc_eigen_solver.C.
References ierr, libMesh::TriangleWrapper::init(), and libMesh::PetscVector< T >::vec().
 {
 #if SLEPC_VERSION_LESS_THAN(3,1,0)
   libmesh_error_msg("SLEPc 3.1 is required to call EigenSolver::set_initial_space()");
 #else
   this->init();
   PetscErrorCode ierr = 0;
   // Make sure the input vector is actually a PetscVector
   PetscVector<T> * initial_space_petsc_vec =
     dynamic_cast<PetscVector<T> *>(&initial_space_in);
   if (!initial_space_petsc_vec)
     libmesh_error_msg("Error attaching initial space: input vector must be a PetscVector.");
   // Get a handle for the underlying Vec.
   Vec initial_vector = initial_space_petsc_vec->vec();
   ierr = EPSSetInitialSpace(_eps, 1, &initial_vector);
   LIBMESH_CHKERR(ierr);
 #endif
 }
set_position_of_spectrum() [1/3]
template<typename T > void libMesh::EigenSolver< T >::set_position_of_spectrum (PositionOfSpectrum pos) inline inherited
Sets the position of the spectrum.
Definition at line 158 of file eigen_solver.h.
References libMesh::EigenSolver< T >::_position_of_spectrum.
   {_position_of_spectrum= pos;}
set_position_of_spectrum() [2/3]
template<typename T > void libMesh::EigenSolver< T >::set_position_of_spectrum (Real pos) inherited
Definition at line 86 of file eigen_solver.C.
References libMesh::TARGET_MAGNITUDE, and libMesh::TARGET_REAL.
 {
   if (pos >= 0)
     _position_of_spectrum = TARGET_MAGNITUDE;
   else
     _position_of_spectrum = TARGET_REAL;
   _target_val = pos;
 }
set_position_of_spectrum() [3/3]
template<typename T > void libMesh::EigenSolver< T >::set_position_of_spectrum (Real pos, PositionOfSpectrum target) inherited
Definition at line 97 of file eigen_solver.C.
 {
   _position_of_spectrum = target;
   _target_val = pos;
 }
set_slepc_position_of_spectrum()
template<typename T > void libMesh::SlepcEigenSolver< T >::set_slepc_position_of_spectrum () private
Tells Slepc to compute the spectrum at the position stored in _position_of_spectrum
Definition at line 656 of file slepc_eigen_solver.C.
References ierr, libMesh::LARGEST_IMAGINARY, libMesh::LARGEST_MAGNITUDE, libMesh::LARGEST_REAL, libMesh::SMALLEST_IMAGINARY, libMesh::SMALLEST_MAGNITUDE, libMesh::SMALLEST_REAL, libMesh::TARGET_IMAGINARY, libMesh::TARGET_MAGNITUDE, and libMesh::TARGET_REAL.
 {
   PetscErrorCode ierr = 0;
   switch (this->_position_of_spectrum)
     {
     case LARGEST_MAGNITUDE:
       {
         ierr = EPSSetWhichEigenpairs (_eps, EPS_LARGEST_MAGNITUDE);
         LIBMESH_CHKERR(ierr);
         return;
       }
     case SMALLEST_MAGNITUDE:
       {
         ierr = EPSSetWhichEigenpairs (_eps, EPS_SMALLEST_MAGNITUDE);
         LIBMESH_CHKERR(ierr);
         return;
       }
     case LARGEST_REAL:
       {
         ierr = EPSSetWhichEigenpairs (_eps, EPS_LARGEST_REAL);
         LIBMESH_CHKERR(ierr);
         return;
       }
     case SMALLEST_REAL:
       {
         ierr = EPSSetWhichEigenpairs (_eps, EPS_SMALLEST_REAL);
         LIBMESH_CHKERR(ierr);
         return;
       }
     case LARGEST_IMAGINARY:
       {
         ierr = EPSSetWhichEigenpairs (_eps, EPS_LARGEST_IMAGINARY);
         LIBMESH_CHKERR(ierr);
         return;
       }
     case SMALLEST_IMAGINARY:
       {
         ierr = EPSSetWhichEigenpairs (_eps, EPS_SMALLEST_IMAGINARY);
         LIBMESH_CHKERR(ierr);
         return;
       }
       // The EPS_TARGET_XXX enums were added in SLEPc 3.1
 #if !SLEPC_VERSION_LESS_THAN(3,1,0)
     case TARGET_MAGNITUDE:
       {
         ierr = EPSSetTarget(_eps, this->_target_val);
         LIBMESH_CHKERR(ierr);
         ierr = EPSSetWhichEigenpairs (_eps, EPS_TARGET_MAGNITUDE);
         LIBMESH_CHKERR(ierr);
         return;
       }
     case TARGET_REAL:
       {
         ierr = EPSSetTarget(_eps, this->_target_val);
         LIBMESH_CHKERR(ierr);
         ierr = EPSSetWhichEigenpairs (_eps, EPS_TARGET_REAL);
         LIBMESH_CHKERR(ierr);
         return;
       }
     case TARGET_IMAGINARY:
       {
         ierr = EPSSetTarget(_eps, this->_target_val);
         LIBMESH_CHKERR(ierr);
         ierr = EPSSetWhichEigenpairs (_eps, EPS_TARGET_IMAGINARY);
         LIBMESH_CHKERR(ierr);
         return;
       }
 #endif
     default:
       libmesh_error_msg("ERROR:  Unsupported SLEPc position of spectrum: " << this->_position_of_spectrum);
     }
 }
set_slepc_problem_type()
template<typename T > void libMesh::SlepcEigenSolver< T >::set_slepc_problem_type () private
Tells Slepc to deal with the type of problem stored in _eigen_problem_type
Definition at line 626 of file slepc_eigen_solver.C.
References libMesh::err, libMesh::GHEP, libMesh::GHIEP, libMesh::GNHEP, libMesh::HEP, ierr, and libMesh::NHEP.
 {
   PetscErrorCode ierr = 0;
   switch (this->_eigen_problem_type)
     {
     case NHEP:
       ierr = EPSSetProblemType (_eps, EPS_NHEP);  LIBMESH_CHKERR(ierr); return;
     case GNHEP:
       ierr = EPSSetProblemType (_eps, EPS_GNHEP); LIBMESH_CHKERR(ierr); return;
     case HEP:
       ierr = EPSSetProblemType (_eps, EPS_HEP);   LIBMESH_CHKERR(ierr); return;
     case GHEP:
       ierr = EPSSetProblemType (_eps, EPS_GHEP);  LIBMESH_CHKERR(ierr); return;
 #if !SLEPC_VERSION_LESS_THAN(3,3,0)
       // EPS_GHIEP added in 3.3.0
     case GHIEP:
       ierr = EPSSetProblemType (_eps, EPS_GHIEP);  LIBMESH_CHKERR(ierr); return;
 #endif
     default:
       libMesh::err << "ERROR:  Unsupported SLEPc Eigen Problem: "
                    << this->_eigen_problem_type        << std::endl
                    << "Continuing with SLEPc defaults" << std::endl;
     }
 }
set_slepc_solver_type()
template<typename T > void libMesh::SlepcEigenSolver< T >::set_slepc_solver_type () private
Tells Slepc to use the user-specified solver stored in _eigen_solver_type
Definition at line 594 of file slepc_eigen_solver.C.
References libMesh::ARNOLDI, libMesh::Utility::enum_to_string(), libMesh::err, ierr, libMesh::KRYLOVSCHUR, libMesh::LANCZOS, libMesh::LAPACK, libMesh::POWER, and libMesh::SUBSPACE.
 {
   PetscErrorCode ierr = 0;
   switch (this->_eigen_solver_type)
     {
     case POWER:
       ierr = EPSSetType (_eps, EPSPOWER);    LIBMESH_CHKERR(ierr); return;
     case SUBSPACE:
       ierr = EPSSetType (_eps, EPSSUBSPACE); LIBMESH_CHKERR(ierr); return;
     case LAPACK:
       ierr = EPSSetType (_eps, EPSLAPACK);   LIBMESH_CHKERR(ierr); return;
     case ARNOLDI:
       ierr = EPSSetType (_eps, EPSARNOLDI);  LIBMESH_CHKERR(ierr); return;
     case LANCZOS:
       ierr = EPSSetType (_eps, EPSLANCZOS);  LIBMESH_CHKERR(ierr); return;
     case KRYLOVSCHUR:
       ierr = EPSSetType (_eps, EPSKRYLOVSCHUR);  LIBMESH_CHKERR(ierr); return;
       // case ARPACK:
       // ierr = EPSSetType (_eps, (char *) EPSARPACK);   LIBMESH_CHKERR(ierr); return;
     default:
       libMesh::err << "ERROR:  Unsupported SLEPc Eigen Solver: "
                    << Utility::enum_to_string(this->_eigen_solver_type) << std::endl
                    << "Continuing with SLEPc defaults" << std::endl;
     }
 }
set_solver_configuration()
template<typename T > void libMesh::EigenSolver< T >::set_solver_configuration (SolverConfiguration & solver_configuration) inherited
Set the solver configuration object.
Definition at line 80 of file eigen_solver.C.
 {
   _solver_configuration = &solver_configuration;
 }
solve_generalized() [1/4]
template<typename T > std::pair< unsigned int, unsigned int > libMesh::SlepcEigenSolver< T >::solve_generalized (SparseMatrix< T > & matrix_A, SparseMatrix< T > & matrix_B, int nev, int ncv, const double tol, const unsigned int m_its) override virtual
This function calls the SLEPc solver to compute the eigenpairs for the generalized eigenproblem defined by the matrix_A and matrix_B, which are of type SparseMatrix. The argument nev is the number of eigenpairs to be computed and ncv is the number of basis vectors to be used in the solution procedure. Return values are the number of converged eigen values and the number of the iterations carried out by the eigen solver.
Implements libMesh::EigenSolver< T >.
Definition at line 290 of file slepc_eigen_solver.C.
References libMesh::PetscMatrix< T >::close(), libMesh::TriangleWrapper::init(), and libMesh::PetscMatrix< T >::mat().
 {
   this->init ();
   // Make sure the data passed in are really of Petsc types
   PetscMatrix<T> * matrix_A = dynamic_cast<PetscMatrix<T> *>(&matrix_A_in);
   PetscMatrix<T> * matrix_B = dynamic_cast<PetscMatrix<T> *>(&matrix_B_in);
   if (!matrix_A || !matrix_B)
     libmesh_error_msg("Error: inputs to solve_generalized() must be of type PetscMatrix.");
   // Close the matrix and vectors in case this wasn't already done.
   if (this->_close_matrix_before_solve)
     {
       matrix_A->close ();
       matrix_B->close ();
     }
   return _solve_generalized_helper (matrix_A->mat(), matrix_B->mat(), nev, ncv, tol, m_its);
 }
solve_generalized() [2/4]
template<typename T > std::pair< unsigned int, unsigned int > libMesh::SlepcEigenSolver< T >::solve_generalized (ShellMatrix< T > & matrix_A, SparseMatrix< T > & matrix_B, int nev, int ncv, const double tol, const unsigned int m_its) override virtual
Solve generalized eigenproblem when matrix_A is of type ShellMatrix, matrix_B is of type SparseMatrix.
Implements libMesh::EigenSolver< T >.
Definition at line 318 of file slepc_eigen_solver.C.
References libMesh::PetscMatrix< T >::close(), ierr, libMesh::TriangleWrapper::init(), libMesh::ShellMatrix< T >::m(), libMesh::PetscMatrix< T >::mat(), and libMesh::ShellMatrix< T >::n().
 {
   this->init ();
   PetscErrorCode ierr=0;
   // Prepare the matrix. Note that the const_cast is only necessary
   // because PETSc does not accept a const void *.  Inside the member
   // function _petsc_shell_matrix() below, the pointer is casted back
   // to a const ShellMatrix<T> *.
   Mat mat_A;
   ierr = MatCreateShell(this->comm().get(),
                         shell_matrix_A.m(), // Specify the number of local rows
                         shell_matrix_A.n(), // Specify the number of local columns
                         PETSC_DETERMINE,
                         PETSC_DETERMINE,
                         const_cast<void *>(static_cast<const void *>(&shell_matrix_A)),
                         &mat_A);
   LIBMESH_CHKERR(ierr);
   PetscMatrix<T> * matrix_B = dynamic_cast<PetscMatrix<T> *>(&matrix_B_in);
   if (!matrix_B)
     libmesh_error_msg("Error: inputs to solve_generalized() must be of type PetscMatrix.");
   // Close the matrix and vectors in case this wasn't already done.
   if (this->_close_matrix_before_solve)
     matrix_B->close ();
   ierr = MatShellSetOperation(mat_A,MATOP_MULT,reinterpret_cast<void(*)(void)>(_petsc_shell_matrix_mult));
   LIBMESH_CHKERR(ierr);
   ierr = MatShellSetOperation(mat_A,MATOP_GET_DIAGONAL,reinterpret_cast<void(*)(void)>(_petsc_shell_matrix_get_diagonal));
   LIBMESH_CHKERR(ierr);
   return _solve_generalized_helper (mat_A, matrix_B->mat(), nev, ncv, tol, m_its);
 }
solve_generalized() [3/4]
template<typename T > std::pair< unsigned int, unsigned int > libMesh::SlepcEigenSolver< T >::solve_generalized (SparseMatrix< T > & matrix_A, ShellMatrix< T > & matrix_B, int nev, int ncv, const double tol, const unsigned int m_its) override virtual
Solve generalized eigenproblem when matrix_A is of type SparseMatrix, matrix_B is of type ShellMatrix. When using this function, one should use the command line options: -st_ksp_type gmres -st_pc_type none or -st_ksp_type gmres -st_pc_type jacobi or similar.
Implements libMesh::EigenSolver< T >.
Definition at line 362 of file slepc_eigen_solver.C.
References libMesh::PetscMatrix< T >::close(), ierr, libMesh::TriangleWrapper::init(), libMesh::ShellMatrix< T >::m(), libMesh::PetscMatrix< T >::mat(), and libMesh::ShellMatrix< T >::n().
 {
   this->init ();
   PetscErrorCode ierr=0;
   PetscMatrix<T> * matrix_A = dynamic_cast<PetscMatrix<T> *>(&matrix_A_in);
   if (!matrix_A)
     libmesh_error_msg("Error: inputs to solve_generalized() must be of type PetscMatrix.");
   // Close the matrix and vectors in case this wasn't already done.
   if (this->_close_matrix_before_solve)
     matrix_A->close ();
   // Prepare the matrix.  Note that the const_cast is only necessary
   // because PETSc does not accept a const void *.  Inside the member
   // function _petsc_shell_matrix() below, the pointer is casted back
   // to a const ShellMatrix<T> *.
   Mat mat_B;
   ierr = MatCreateShell(this->comm().get(),
                         shell_matrix_B.m(), // Specify the number of local rows
                         shell_matrix_B.n(), // Specify the number of local columns
                         PETSC_DETERMINE,
                         PETSC_DETERMINE,
                         const_cast<void *>(static_cast<const void *>(&shell_matrix_B)),
                         &mat_B);
   LIBMESH_CHKERR(ierr);
   ierr = MatShellSetOperation(mat_B,MATOP_MULT,reinterpret_cast<void(*)(void)>(_petsc_shell_matrix_mult));
   LIBMESH_CHKERR(ierr);
   ierr = MatShellSetOperation(mat_B,MATOP_GET_DIAGONAL,reinterpret_cast<void(*)(void)>(_petsc_shell_matrix_get_diagonal));
   LIBMESH_CHKERR(ierr);
   return _solve_generalized_helper (matrix_A->mat(), mat_B, nev, ncv, tol, m_its);
 }
solve_generalized() [4/4]
template<typename T > std::pair< unsigned int, unsigned int > libMesh::SlepcEigenSolver< T >::solve_generalized (ShellMatrix< T > & matrix_A, ShellMatrix< T > & matrix_B, int nev, int ncv, const double tol, const unsigned int m_its) override virtual
Solve generalized eigenproblem when both matrix_A and matrix_B are of type ShellMatrix. When using this function, one should use the command line options: -st_ksp_type gmres -st_pc_type none or -st_ksp_type gmres -st_pc_type jacobi or similar.
Implements libMesh::EigenSolver< T >.
Definition at line 407 of file slepc_eigen_solver.C.
References ierr, libMesh::TriangleWrapper::init(), libMesh::ShellMatrix< T >::m(), and libMesh::ShellMatrix< T >::n().
 {
   this->init ();
   PetscErrorCode ierr=0;
   // Prepare the matrices.  Note that the const_casts are only
   // necessary because PETSc does not accept a const void *.  Inside
   // the member function _petsc_shell_matrix() below, the pointer is
   // casted back to a const ShellMatrix<T> *.
   Mat mat_A;
   ierr = MatCreateShell(this->comm().get(),
                         shell_matrix_A.m(), // Specify the number of local rows
                         shell_matrix_A.n(), // Specify the number of local columns
                         PETSC_DETERMINE,
                         PETSC_DETERMINE,
                         const_cast<void *>(static_cast<const void *>(&shell_matrix_A)),
                         &mat_A);
   LIBMESH_CHKERR(ierr);
   Mat mat_B;
   ierr = MatCreateShell(this->comm().get(),
                         shell_matrix_B.m(), // Specify the number of local rows
                         shell_matrix_B.n(), // Specify the number of local columns
                         PETSC_DETERMINE,
                         PETSC_DETERMINE,
                         const_cast<void *>(static_cast<const void *>(&shell_matrix_B)),
                         &mat_B);
   LIBMESH_CHKERR(ierr);
   ierr = MatShellSetOperation(mat_A,MATOP_MULT,reinterpret_cast<void(*)(void)>(_petsc_shell_matrix_mult));
   LIBMESH_CHKERR(ierr);
   ierr = MatShellSetOperation(mat_A,MATOP_GET_DIAGONAL,reinterpret_cast<void(*)(void)>(_petsc_shell_matrix_get_diagonal));
   LIBMESH_CHKERR(ierr);
   ierr = MatShellSetOperation(mat_B,MATOP_MULT,reinterpret_cast<void(*)(void)>(_petsc_shell_matrix_mult));
   LIBMESH_CHKERR(ierr);
   ierr = MatShellSetOperation(mat_B,MATOP_GET_DIAGONAL,reinterpret_cast<void(*)(void)>(_petsc_shell_matrix_get_diagonal));
   LIBMESH_CHKERR(ierr);
   return _solve_generalized_helper (mat_A, mat_B, nev, ncv, tol, m_its);
 }
solve_standard() [1/2]
template<typename T > std::pair< unsigned int, unsigned int > libMesh::SlepcEigenSolver< T >::solve_standard (SparseMatrix< T > & matrix_A, int nev, int ncv, const double tol, const unsigned int m_its) override virtual
This function calls the SLEPc solver to compute the eigenpairs of the SparseMatrix matrix_A. nev is the number of eigenpairs to be computed and ncv is the number of basis vectors to be used in the solution procedure. Return values are the number of converged eigen values and the number of the iterations carried out by the eigen solver.
Implements libMesh::EigenSolver< T >.
Definition at line 103 of file slepc_eigen_solver.C.
References libMesh::PetscMatrix< T >::close(), libMesh::TriangleWrapper::init(), and libMesh::PetscMatrix< T >::mat().
 {
   LOG_SCOPE("solve_standard()", "SlepcEigenSolver");
   this->init ();
   // Make sure the SparseMatrix passed in is really a PetscMatrix
   PetscMatrix<T> * matrix_A = dynamic_cast<PetscMatrix<T> *>(&matrix_A_in);
   if (!matrix_A)
     libmesh_error_msg("Error: input matrix to solve_standard() must be a PetscMatrix.");
   // Close the matrix and vectors in case this wasn't already done.
   if (this->_close_matrix_before_solve)
     matrix_A->close ();
   return _solve_standard_helper(matrix_A->mat(), nev, ncv, tol, m_its);
 }
solve_standard() [2/2]
template<typename T > std::pair< unsigned int, unsigned int > libMesh::SlepcEigenSolver< T >::solve_standard (ShellMatrix< T > & shell_matrix, int nev, int ncv, const double tol, const unsigned int m_its) override virtual
Same as above except that matrix_A is a ShellMatrix in this case.
Implements libMesh::EigenSolver< T >.
Definition at line 129 of file slepc_eigen_solver.C.
References ierr, libMesh::TriangleWrapper::init(), libMesh::ShellMatrix< T >::m(), and libMesh::ShellMatrix< T >::n().
 {
   this->init ();
   PetscErrorCode ierr=0;
   // Prepare the matrix.  Note that the const_cast is only necessary
   // because PETSc does not accept a const void *.  Inside the member
   // function _petsc_shell_matrix() below, the pointer is casted back
   // to a const ShellMatrix<T> *.
   Mat mat;
   ierr = MatCreateShell(this->comm().get(),
                         shell_matrix.m(), // Specify the number of local rows
                         shell_matrix.n(), // Specify the number of local columns
                         PETSC_DETERMINE,
                         PETSC_DETERMINE,
                         const_cast<void *>(static_cast<const void *>(&shell_matrix)),
                         &mat);
   LIBMESH_CHKERR(ierr);
   ierr = MatShellSetOperation(mat,MATOP_MULT,reinterpret_cast<void(*)(void)>(_petsc_shell_matrix_mult));
   LIBMESH_CHKERR(ierr);
   ierr = MatShellSetOperation(mat,MATOP_GET_DIAGONAL,reinterpret_cast<void(*)(void)>(_petsc_shell_matrix_get_diagonal));
   LIBMESH_CHKERR(ierr);
   return _solve_standard_helper(mat, nev, ncv, tol, m_its);
 }
Member Data Documentation
_close_matrix_before_solve
template<typename T > bool libMesh::EigenSolver< T >::_close_matrix_before_solve protected inherited
Definition at line 305 of file eigen_solver.h.
Referenced by libMesh::EigenSolver< T >::get_close_matrix_before_solve(), and libMesh::EigenSolver< T >::set_close_matrix_before_solve().
_communicator
const Parallel::Communicator& libMesh::ParallelObject::_communicator protected inherited
Definition at line 107 of file parallel_object.h.
Referenced by libMesh::EquationSystems::build_parallel_elemental_solution_vector(), libMesh::EquationSystems::build_parallel_solution_vector(), libMesh::ParallelObject::comm(), libMesh::ParallelObject::n_processors(), libMesh::ParallelObject::operator=(), and libMesh::ParallelObject::processor_id().
_counts
ReferenceCounter::Counts libMesh::ReferenceCounter::_counts static protected inherited
Actually holds the data.
Definition at line 122 of file reference_counter.h.
Referenced by libMesh::ReferenceCounter::get_info(), libMesh::ReferenceCounter::increment_constructor_count(), and libMesh::ReferenceCounter::increment_destructor_count().
_eigen_problem_type
template<typename T > EigenProblemType libMesh::EigenSolver< T >::_eigen_problem_type protected inherited
Enum stating which type of eigen problem we deal with.
Definition at line 285 of file eigen_solver.h.
Referenced by libMesh::EigenSolver< T >::eigen_problem_type(), libMesh::EigenSolver< T >::set_eigenproblem_type(), and libMesh::SlepcEigenSolver< T >::SlepcEigenSolver().
_eigen_solver_type
template<typename T > EigenSolverType libMesh::EigenSolver< T >::_eigen_solver_type protected inherited
Enum stating which type of eigensolver to use.
Definition at line 280 of file eigen_solver.h.
Referenced by libMesh::EigenSolver< T >::eigen_solver_type(), libMesh::EigenSolver< T >::set_eigensolver_type(), and libMesh::SlepcEigenSolver< T >::SlepcEigenSolver().
_enable_print_counter
bool libMesh::ReferenceCounter::_enable_print_counter = true static protected inherited
Flag to control whether reference count information is printed when print_info is called.
Definition at line 141 of file reference_counter.h.
Referenced by libMesh::ReferenceCounter::disable_print_counter_info(), libMesh::ReferenceCounter::enable_print_counter_info(), and libMesh::ReferenceCounter::print_info().
_eps
template<typename T > EPS libMesh::SlepcEigenSolver< T >::_eps private
Eigenproblem solver context
Definition at line 272 of file slepc_eigen_solver.h.
Referenced by libMesh::SlepcEigenSolver< T >::eps().
_is_initialized
template<typename T > bool libMesh::EigenSolver< T >::_is_initialized protected inherited
Flag indicating if the data structures have been initialized.
Definition at line 295 of file eigen_solver.h.
Referenced by libMesh::EigenSolver< T >::initialized().
_mutex
Threads::spin_mutex libMesh::ReferenceCounter::_mutex static protected inherited
Mutual exclusion object to enable thread-safe reference counting.
Definition at line 135 of file reference_counter.h.
_n_objects
Threads::atomic< unsigned int > libMesh::ReferenceCounter::_n_objects static protected inherited
The number of objects. Print the reference count information when the number returns to 0.
Definition at line 130 of file reference_counter.h.
Referenced by libMesh::ReferenceCounter::n_objects(), libMesh::ReferenceCounter::ReferenceCounter(), and libMesh::ReferenceCounter::~ReferenceCounter().
_position_of_spectrum
template<typename T > PositionOfSpectrum libMesh::EigenSolver< T >::_position_of_spectrum protected inherited
Enum stating where to evaluate the spectrum.
Definition at line 290 of file eigen_solver.h.
Referenced by libMesh::EigenSolver< T >::position_of_spectrum(), and libMesh::EigenSolver< T >::set_position_of_spectrum().
_solver_configuration
template<typename T > SolverConfiguration* libMesh::EigenSolver< T >::_solver_configuration protected inherited
Optionally store a SolverOptions object that can be used to set parameters like solver type, tolerances and iteration limits.
Definition at line 301 of file eigen_solver.h.
_target_val
template<typename T > Real libMesh::EigenSolver< T >::_target_val protected inherited
Definition at line 303 of file eigen_solver.h.
The documentation for this class was generated from the following files:
slepc_eigen_solver.h
slepc_eigen_solver.C