libMesh: libMesh::OldSolutionValue< Output, point_output > Class Template Reference
SomeWebsiteLogo
libMesh::OldSolutionValue< Output, point_output > Class Template Reference
#include <generic_projector.h>
Public Member Functions
OldSolutionValue (const libMesh::System &sys_in, const NumericVector< Number > &old_sol)
OldSolutionValue (const OldSolutionValue &in)
Output eval_at_node (const FEMContext &c, unsigned int i, unsigned int elem_dim, const Node &n, Real=0.)
Output eval_at_point (const FEMContext &c, unsigned int i, const Point &p, Real=0.)
void eval_old_dofs (const FEMContext &c, unsigned int var, std::vector< Output > &values)
template<>
Number eval_at_node (const FEMContext &c, unsigned int i, unsigned int, const Node &n, Real)
template<>
Gradient eval_at_node (const FEMContext &c, unsigned int i, unsigned int elem_dim, const Node &n, Real)
template<>
void get_shape_outputs (FEBase &fe)
template<>
void get_shape_outputs (FEBase &fe)
template<>
void get_shape_outputs (FEBase &fe)
template<>
void get_shape_outputs (FEBase &fe)
void init_context (FEMContext &c)
bool is_grid_projection ()
Static Public Member Functions
static void get_shape_outputs (FEBase &fe)
Protected Member Functions
template<>
const Real out_of_elem_tol
template<>
const Real out_of_elem_tol
template<>
const Real out_of_elem_tol
template<>
const Real out_of_elem_tol
void check_old_context (const FEMContext &c)
bool check_old_context (const FEMContext &c, const Point &p)
Protected Attributes
const Elem * last_elem
const System & sys
FEMContext old_context
std::vector< unsigned int > component_to_var
Static Protected Attributes
static const Real out_of_elem_tol
Private Attributes
const NumericVector< Number > & old_solution
Detailed Description
template<typename Output, void(FEMContext::*)(unsigned int, const Point &, Output &, const Real) const point_output>
class libMesh::OldSolutionValue< Output, point_output >
The OldSolutionValue input functor class can be used with GenericProjector to read values from a solution on a just-refined-and-coarsened mesh.
Author
Roy H. Stogner
Date
2016
Definition at line 382 of file generic_projector.h.
Constructor & Destructor Documentation
OldSolutionValue() [1/2]
template<typename Output , void(FEMContext::*)(unsigned int, const Point &, Output &, const Real) const point_output> libMesh::OldSolutionValue< Output, point_output >::OldSolutionValue (const libMesh::System & sys_in, const NumericVector< Number > & old_sol) inline
Definition at line 385 of file generic_projector.h.
References libMesh::FEMContext::OLD.
                                                           :
     OldSolutionBase<Output, point_output>(sys_in),
     old_solution(old_sol)
   {
     this->old_context.set_algebraic_type(FEMContext::OLD);
     this->old_context.set_custom_solution(&old_solution);
   }
OldSolutionValue() [2/2]
template<typename Output , void(FEMContext::*)(unsigned int, const Point &, Output &, const Real) const point_output> libMesh::OldSolutionValue< Output, point_output >::OldSolutionValue (const OldSolutionValue< Output, point_output > & in) inline
Definition at line 394 of file generic_projector.h.
References libMesh::FEMContext::OLD.
                                                 :
     OldSolutionBase<Output, point_output>(in.sys),
     old_solution(in.old_solution)
   {
     this->old_context.set_algebraic_type(FEMContext::OLD);
     this->old_context.set_custom_solution(&old_solution);
   }
Member Function Documentation
check_old_context() [1/2]
template<typename Output , void(FEMContext::*)(unsigned int, const Point &, Output &, const Real) const point_output> void libMesh::OldSolutionBase< Output, point_output >::check_old_context (const FEMContext & c) inline protected inherited
Definition at line 259 of file generic_projector.h.
References libMesh::FEMContext::get_elem(), libMesh::Elem::JUST_COARSENED, libMesh::Elem::JUST_REFINED, libMesh::DofObject::old_dof_object, libMesh::Elem::parent(), and libMesh::Elem::refinement_flag().
   {
     LOG_SCOPE ("check_old_context(c)", "OldSolutionBase");
     const Elem & elem = c.get_elem();
     if (last_elem != &elem)
       {
         if (elem.refinement_flag() == Elem::JUST_REFINED)
           {
             old_context.pre_fe_reinit(sys, elem.parent());
           }
         else if (elem.refinement_flag() == Elem::JUST_COARSENED)
           {
             libmesh_error();
           }
         else
           {
             if (!elem.old_dof_object)
               {
                 libmesh_error();
               }
             old_context.pre_fe_reinit(sys, &elem);
           }
         last_elem = &elem;
       }
     else
       {
         libmesh_assert(old_context.has_elem());
       }
   }
check_old_context() [2/2]
template<typename Output , void(FEMContext::*)(unsigned int, const Point &, Output &, const Real) const point_output> bool libMesh::OldSolutionBase< Output, point_output >::check_old_context (const FEMContext & c, const Point & p) inline protected inherited
Definition at line 292 of file generic_projector.h.
References libMesh::Elem::child_ref_range(), libMesh::FEMContext::get_elem(), libMesh::Elem::hmax(), libMesh::Elem::JUST_COARSENED, libMesh::Elem::JUST_REFINED, libMesh::DofObject::old_dof_object, libMesh::Elem::parent(), libMesh::Real, and libMesh::Elem::refinement_flag().
   {
     LOG_SCOPE ("check_old_context(c,p)", "OldSolutionBase");
     const Elem & elem = c.get_elem();
     if (last_elem != &elem)
       {
         if (elem.refinement_flag() == Elem::JUST_REFINED)
           {
             old_context.pre_fe_reinit(sys, elem.parent());
           }
         else if (elem.refinement_flag() == Elem::JUST_COARSENED)
           {
             // Find the child with this point.  Use out_of_elem_tol
             // (in physical space, which may correspond to a large
             // tolerance in master space!) to allow for out-of-element
             // finite differencing of mixed gradient terms.  Pray we
             // have no quadrature locations which are within 1e-5 of
             // the element subdivision boundary but are not exactly on
             // that boundary.
             const Real master_tol = out_of_elem_tol / elem.hmax() * 2;
             for (auto & child : elem.child_ref_range())
               if (child.close_to_point(p, master_tol))
                 {
                   old_context.pre_fe_reinit(sys, &child);
                   break;
                 }
             libmesh_assert
               (old_context.get_elem().close_to_point(p, master_tol));
           }
         else
           {
             if (!elem.old_dof_object)
               return false;
             old_context.pre_fe_reinit(sys, &elem);
           }
         last_elem = &elem;
       }
     else
       {
         libmesh_assert(old_context.has_elem());
         const Real master_tol = out_of_elem_tol / elem.hmax() * 2;
         if (!old_context.get_elem().close_to_point(p, master_tol))
           {
             libmesh_assert_equal_to
               (elem.refinement_flag(), Elem::JUST_COARSENED);
             for (auto & child : elem.child_ref_range())
               if (child.close_to_point(p, master_tol))
                 {
                   old_context.pre_fe_reinit(sys, &child);
                   break;
                 }
             libmesh_assert
               (old_context.get_elem().close_to_point(p, master_tol));
           }
       }
     return true;
   }
eval_at_node() [1/3]
template<typename Output , void(FEMContext::*)(unsigned int, const Point &, Output &, const Real) const point_output> Output libMesh::OldSolutionValue< Output, point_output >::eval_at_node (const FEMContext & c, unsigned int i, unsigned int elem_dim, const Node & n, Real = 0.)
eval_at_node() [2/3]
template<> Number libMesh::OldSolutionValue< Number, &FEMContext::point_value >::eval_at_node (const FEMContext & c, unsigned int i, unsigned int, const Node & n, Real) inline
Definition at line 487 of file generic_projector.h.
References libMesh::DofObject::dof_number(), libMesh::DofObject::n_comp(), libMesh::DofObject::n_vars(), and libMesh::DofObject::old_dof_object.
 {
   LOG_SCOPE ("Number eval_at_node()", "OldSolutionValue");
   // Handle offset from non-scalar components in previous variables
   libmesh_assert_less(i, this->component_to_var.size());
   unsigned int var = this->component_to_var[i];
   // Optimize for the common case, where this node was part of the
   // old solution.
   //
   // Be sure to handle cases where the variable wasn't defined on
   // this node (due to changing subdomain support) or where the
   // variable has no components on this node (due to Elem order
   // exceeding FE order)
   if (n.old_dof_object &&
       n.old_dof_object->n_vars(sys.number()) &&
       n.old_dof_object->n_comp(sys.number(), var))
     {
       const dof_id_type old_id =
         n.old_dof_object->dof_number(sys.number(), var, 0);
       return old_solution(old_id);
     }
   return this->eval_at_point(c, i, n, 0);
 }
eval_at_node() [3/3]
template<> Gradient libMesh::OldSolutionValue< Gradient, &FEMContext::point_gradient >::eval_at_node (const FEMContext & c, unsigned int i, unsigned int elem_dim, const Node & n, Real) inline
Definition at line 524 of file generic_projector.h.
References libMesh::DofObject::dof_number(), libMesh::DofObject::n_comp(), libMesh::DofObject::n_vars(), and libMesh::DofObject::old_dof_object.
 {
   LOG_SCOPE ("Gradient eval_at_node()", "OldSolutionValue");
   // Handle offset from non-scalar components in previous variables
   libmesh_assert_less(i, this->component_to_var.size());
   unsigned int var = this->component_to_var[i];
   // Optimize for the common case, where this node was part of the
   // old solution.
   //
   // Be sure to handle cases where the variable wasn't defined on
   // this node (due to changing subdomain support) or where the
   // variable has no components on this node (due to Elem order
   // exceeding FE order)
   if (n.old_dof_object &&
       n.old_dof_object->n_vars(sys.number()) &&
       n.old_dof_object->n_comp(sys.number(), var))
     {
       Gradient g;
       for (unsigned int d = 0; d != elem_dim; ++d)
         {
           const dof_id_type old_id =
             n.old_dof_object->dof_number(sys.number(), var, d+1);
           g(d) = old_solution(old_id);
         }
       return g;
     }
   return this->eval_at_point(c, i, n, 0);
 }
eval_at_point()
template<typename Output , void(FEMContext::*)(unsigned int, const Point &, Output &, const Real) const point_output> Output libMesh::OldSolutionValue< Output, point_output >::eval_at_point (const FEMContext & c, unsigned int i, const Point & p, Real = 0.) inline
Definition at line 409 of file generic_projector.h.
   {
     LOG_SCOPE ("eval_at_point()", "OldSolutionValue");
     if (!this->check_old_context(c, p))
       return 0;
     // Handle offset from non-scalar components in previous variables
     libmesh_assert_less(i, this->component_to_var.size());
     unsigned int var = this->component_to_var[i];
     Output n;
     (this->old_context.*point_output)(var, p, n, this->out_of_elem_tol);
     return n;
   }
eval_old_dofs()
template<typename Output , void(FEMContext::*)(unsigned int, const Point &, Output &, const Real) const point_output> void libMesh::OldSolutionValue< Output, point_output >::eval_old_dofs (const FEMContext & c, unsigned int var, std::vector< Output > & values) inline
Definition at line 428 of file generic_projector.h.
   {
     LOG_SCOPE ("eval_old_dofs()", "OldSolutionValue");
     this->check_old_context(c);
     const std::vector<dof_id_type> & old_dof_indices =
       this->old_context.get_dof_indices(var);
     libmesh_assert_equal_to (old_dof_indices.size(), values.size());
     old_solution.get(old_dof_indices, values);
   }
get_shape_outputs() [1/5]
template<typename Output , void(FEMContext::*)(unsigned int, const Point &, Output &, const Real) const point_output> static void libMesh::OldSolutionBase< Output, point_output >::get_shape_outputs (FEBase & fe) static inherited
get_shape_outputs() [2/5]
template<> void libMesh::OldSolutionBase< Number, &FEMContext::point_value >::get_shape_outputs (FEBase & fe) inline inherited
Definition at line 451 of file generic_projector.h.
References libMesh::FEGenericBase< OutputType >::get_phi().
 {
   fe.get_phi();
 }
get_shape_outputs() [3/5]
template<> void libMesh::OldSolutionBase< Gradient, &FEMContext::point_gradient >::get_shape_outputs (FEBase & fe) inline inherited
Definition at line 459 of file generic_projector.h.
References libMesh::FEGenericBase< OutputType >::get_dphi().
 {
   fe.get_dphi();
 }
get_shape_outputs() [4/5]
template<> void libMesh::OldSolutionBase< Real, &FEMContext::point_value >::get_shape_outputs (FEBase & fe) inline inherited
Definition at line 468 of file generic_projector.h.
References libMesh::FEGenericBase< OutputType >::get_phi().
 {
   fe.get_phi();
 }
get_shape_outputs() [5/5]
template<> void libMesh::OldSolutionBase< RealGradient, &FEMContext::point_gradient >::get_shape_outputs (FEBase & fe) inline inherited
Definition at line 476 of file generic_projector.h.
References libMesh::FEGenericBase< OutputType >::get_dphi().
 {
   fe.get_dphi();
 }
init_context()
template<typename Output , void(FEMContext::*)(unsigned int, const Point &, Output &, const Real) const point_output> void libMesh::OldSolutionBase< Output, point_output >::init_context (FEMContext & c) inline inherited
Definition at line 237 of file generic_projector.h.
References libMesh::FEMContext::DOFS_ONLY, and libMesh::FEMContext::set_algebraic_type().
   {
     c.set_algebraic_type(FEMContext::DOFS_ONLY);
     // Loop over variables, to prerequest
     for (unsigned int var=0; var!=sys.n_vars(); ++var)
       {
         FEBase * fe = nullptr;
         const std::set<unsigned char> & elem_dims =
           old_context.elem_dimensions();
         for (const auto & dim : elem_dims)
           {
             old_context.get_element_fe(var, fe, dim);
             get_shape_outputs(*fe);
           }
       }
   }
is_grid_projection()
template<typename Output , void(FEMContext::*)(unsigned int, const Point &, Output &, const Real) const point_output> bool libMesh::OldSolutionBase< Output, point_output >::is_grid_projection () inline inherited
Definition at line 256 of file generic_projector.h.
 { return true; }
out_of_elem_tol() [1/4]
template<> const Real libMesh::OldSolutionBase< Number, &FEMContext::point_value >::out_of_elem_tol () protected inherited
Definition at line 565 of file generic_projector.h.
out_of_elem_tol() [2/4]
template<> const Real libMesh::OldSolutionBase< Gradient, &FEMContext::point_gradient >::out_of_elem_tol () protected inherited
Definition at line 568 of file generic_projector.h.
out_of_elem_tol() [3/4]
template<> const Real libMesh::OldSolutionBase< Real, &FEMContext::point_value >::out_of_elem_tol () protected inherited
Definition at line 572 of file generic_projector.h.
out_of_elem_tol() [4/4]
template<> const Real libMesh::OldSolutionBase< RealGradient, &FEMContext::point_gradient >::out_of_elem_tol () protected inherited
Definition at line 575 of file generic_projector.h.
Member Data Documentation
component_to_var
template<typename Output , void(FEMContext::*)(unsigned int, const Point &, Output &, const Real) const point_output> std::vector<unsigned int> libMesh::OldSolutionBase< Output, point_output >::component_to_var protected inherited
Definition at line 363 of file generic_projector.h.
last_elem
template<typename Output , void(FEMContext::*)(unsigned int, const Point &, Output &, const Real) const point_output> const Elem* libMesh::OldSolutionBase< Output, point_output >::last_elem protected inherited
Definition at line 360 of file generic_projector.h.
old_context
template<typename Output , void(FEMContext::*)(unsigned int, const Point &, Output &, const Real) const point_output> FEMContext libMesh::OldSolutionBase< Output, point_output >::old_context protected inherited
Definition at line 362 of file generic_projector.h.
old_solution
template<typename Output , void(FEMContext::*)(unsigned int, const Point &, Output &, const Real) const point_output> const NumericVector<Number>& libMesh::OldSolutionValue< Output, point_output >::old_solution private
Definition at line 445 of file generic_projector.h.
out_of_elem_tol
template<typename Output , void(FEMContext::*)(unsigned int, const Point &, Output &, const Real) const point_output> const Real libMesh::OldSolutionBase< Output, point_output >::out_of_elem_tol static protected inherited
Definition at line 365 of file generic_projector.h.
sys
template<typename Output , void(FEMContext::*)(unsigned int, const Point &, Output &, const Real) const point_output> const System& libMesh::OldSolutionBase< Output, point_output >::sys protected inherited
Definition at line 361 of file generic_projector.h.
The documentation for this class was generated from the following file:
generic_projector.h