libMesh: libMesh::DefaultCoupling Class Reference
SomeWebsiteLogo
libMesh::DefaultCoupling Class Reference
#include <default_coupling.h>
Public Types
typedef LIBMESH_BEST_UNORDERED_MAP< const Elem *, const CouplingMatrix * > map_type
Public Member Functions
DefaultCoupling ()
void set_dof_coupling (const CouplingMatrix *dof_coupling)
unsigned int n_levels ()
void set_n_levels (unsigned int n_levels)
void set_periodic_boundaries (const PeriodicBoundaries *periodic_bcs)
void set_mesh (const MeshBase *mesh)
virtual void mesh_reinit () libmesh_override
virtual void redistribute () libmesh_override
virtual void delete_remote_elements () libmesh_override
virtual void operator() (const MeshBase::const_element_iterator &range_begin, const MeshBase::const_element_iterator &range_end, processor_id_type p, map_type &coupled_elements) libmesh_override
virtual void dofmap_reinit ()
Static Public Member Functions
static std::string get_info ()
static void print_info (std::ostream &out=libMesh::out)
static unsigned int n_objects ()
static void enable_print_counter_info ()
static void disable_print_counter_info ()
Protected Types
typedef std::map< std::string, std::pair< unsigned int, unsigned int > > Counts
Protected Member Functions
void increment_constructor_count (const std::string &name)
void increment_destructor_count (const std::string &name)
Static Protected Attributes
static Counts _counts
static Threads::atomic< unsigned int > _n_objects
static Threads::spin_mutex _mutex
static bool _enable_print_counter = true
Private Attributes
const CouplingMatrix * _dof_coupling
const PeriodicBoundaries * _periodic_bcs
const MeshBase * _mesh
unsigned int _n_levels
Detailed Description
This class implements the default algebraic coupling in libMesh: elements couple to themselves, but may also couple to neighbors both locally and across periodic boundary conditions.
Author
Roy H. Stogner
Date
2016
Definition at line 41 of file default_coupling.h.
Member Typedef Documentation
typedef std::map<std::string, std::pair<unsigned int, unsigned int> > libMesh::ReferenceCounter::Counts protected inherited
Data structure to log the information. The log is identified by the class name.
Definition at line 110 of file reference_counter.h.
typedef LIBMESH_BEST_UNORDERED_MAP<const Elem*, const CouplingMatrix*> libMesh::GhostingFunctor::map_type inherited
What elements do we care about and what variables do we care about on each element?
Definition at line 140 of file ghosting_functor.h.
Constructor & Destructor Documentation
libMesh::DefaultCoupling::DefaultCoupling () inline
Constructor.
Definition at line 48 of file default_coupling.h.
                     :
     _dof_coupling(libmesh_nullptr),
 #ifdef LIBMESH_ENABLE_PERIODIC
     _periodic_bcs(libmesh_nullptr),
 #endif
     _mesh(libmesh_nullptr),
     _n_levels(0)
  {}
Member Function Documentation
virtual void libMesh::DefaultCoupling::delete_remote_elements () inline virtual
GhostingFunctor subclasses with relatively long-lasting caches may want to delete the no-longer-relevant parts of those caches after a redistribution is complete.
Reimplemented from libMesh::GhostingFunctor.
Definition at line 87 of file default_coupling.h.
References mesh_reinit().
   { this->mesh_reinit(); }
void libMesh::ReferenceCounter::disable_print_counter_info () static inherited
Definition at line 106 of file reference_counter.C.
References libMesh::ReferenceCounter::_enable_print_counter.
 {
   _enable_print_counter = false;
   return;
 }
virtual void libMesh::GhostingFunctor::dofmap_reinit () inline virtual inherited
For algebraic ghosting or coupling functors we also call dofmap_reinit() later, after dofs have been distributed on the new mesh but before the functors have been queried for send_list or sparsity pattern calculations.
Definition at line 171 of file ghosting_functor.h.
Referenced by libMesh::DofMap::distribute_dofs().
 {};
void libMesh::ReferenceCounter::enable_print_counter_info () static inherited
Methods to enable/disable the reference counter output from print_info()
Definition at line 100 of file reference_counter.C.
References libMesh::ReferenceCounter::_enable_print_counter.
 {
   _enable_print_counter = true;
   return;
 }
std::string libMesh::ReferenceCounter::get_info () static inherited
Gets a string containing the reference information.
Definition at line 47 of file reference_counter.C.
References libMesh::ReferenceCounter::_counts, and libMesh::Quality::name().
Referenced by libMesh::ReferenceCounter::print_info().
 {
 #if defined(LIBMESH_ENABLE_REFERENCE_COUNTING) && defined(DEBUG)
   std::ostringstream oss;
   oss << '\n'
       << " ---------------------------------------------------------------------------- \n"
       << "| Reference count information                                                |\n"
       << " ---------------------------------------------------------------------------- \n";
   for (Counts::iterator it = _counts.begin();
        it != _counts.end(); ++it)
     {
       const std::string name(it->first);
       const unsigned int creations    = it->second.first;
       const unsigned int destructions = it->second.second;
       oss << "| " << name << " reference count information:\n"
           << "|  Creations:    " << creations    << '\n'
           << "|  Destructions: " << destructions << '\n';
     }
   oss << " ---------------------------------------------------------------------------- \n";
   return oss.str();
 #else
   return "";
 #endif
 }
void libMesh::ReferenceCounter::increment_constructor_count (const std::string & name) inline protected inherited
Increments the construction counter. Should be called in the constructor of any derived class that will be reference counted.
Definition at line 160 of file reference_counter.h.
References libMesh::ReferenceCounter::_counts, libMesh::Quality::name(), and libMesh::Threads::spin_mtx.
Referenced by libMesh::ReferenceCountedObject< RBParametrized >::ReferenceCountedObject().
 {
   Threads::spin_mutex::scoped_lock lock(Threads::spin_mtx);
   std::pair<unsigned int, unsigned int> & p = _counts[name];
   p.first++;
 }
void libMesh::ReferenceCounter::increment_destructor_count (const std::string & name) inline protected inherited
Increments the destruction counter. Should be called in the destructor of any derived class that will be reference counted.
Definition at line 173 of file reference_counter.h.
References libMesh::ReferenceCounter::_counts, libMesh::Quality::name(), and libMesh::Threads::spin_mtx.
Referenced by libMesh::ReferenceCountedObject< RBParametrized >::~ReferenceCountedObject().
 {
   Threads::spin_mutex::scoped_lock lock(Threads::spin_mtx);
   std::pair<unsigned int, unsigned int> & p = _counts[name];
   p.second++;
 }
void libMesh::DefaultCoupling::mesh_reinit () virtual
If we have periodic boundaries, then we'll need the mesh to have an updated point locator whenever we're about to query them.
Reimplemented from libMesh::GhostingFunctor.
Definition at line 52 of file default_coupling.C.
References _mesh, _periodic_bcs, libMesh::libmesh_assert(), and libMesh::MeshBase::sub_point_locator().
Referenced by delete_remote_elements(), and redistribute().
 {
   // Unless we have periodic boundary conditions, we don't need
   // anything precomputed.
 #ifdef LIBMESH_ENABLE_PERIODIC
   if (!_periodic_bcs || _periodic_bcs->empty())
     return;
 #endif
   // If we do have periodic boundary conditions, we'll need a master
   // point locator, so we'd better have a mesh to build it on.
   libmesh_assert(_mesh);
   // Make sure an up-to-date master point locator has been
   // constructed; we'll need to grab sub-locators soon.
   _mesh->sub_point_locator();
 }
unsigned int libMesh::DefaultCoupling::n_levels () inline
Definition at line 61 of file default_coupling.h.
References _n_levels.
Referenced by set_n_levels().
   { return _n_levels; }
static unsigned int libMesh::ReferenceCounter::n_objects () inline static inherited
Prints the number of outstanding (created, but not yet destroyed) objects.
Definition at line 76 of file reference_counter.h.
References libMesh::ReferenceCounter::_n_objects.
   { return _n_objects; }
void libMesh::DefaultCoupling::operator() (const MeshBase::const_element_iterator & range_begin, const MeshBase::const_element_iterator & range_end, processor_id_type p, map_type & coupled_elements) virtual
For the specified range of active elements, find the elements which will be coupled to them in the sparsity pattern.
This will be only the elements themselves by default, but will include side neighbors if an all-discontinuous-variable system is detected and/or if the user specified –implicit_neighbor_dofs on the command line or used set_implicit_neighbor_dofs() in their code.
Implements libMesh::GhostingFunctor.
Definition at line 73 of file default_coupling.C.
References libMesh::Elem::active_family_tree_by_neighbor(), libMesh::Elem::active_family_tree_by_topological_neighbor(), libMesh::libmesh_assert(), libMesh::Elem::n_sides(), libMesh::Elem::neighbor_ptr(), libMesh::DofObject::processor_id(), libMesh::remote_elem, and libMesh::Elem::topological_neighbor().
 {
   LOG_SCOPE("operator()", "DefaultCoupling");
 #ifdef LIBMESH_ENABLE_PERIODIC
   bool check_periodic_bcs =
     (_periodic_bcs && !_periodic_bcs->empty());
   UniquePtr<PointLocatorBase> point_locator;
   if (check_periodic_bcs)
     {
       libmesh_assert(_mesh);
       point_locator = _mesh->sub_point_locator();
     }
 #endif
   if (!this->_n_levels)
     {
       for (MeshBase::const_element_iterator elem_it = range_begin;
            elem_it != range_end; ++elem_it)
         {
           const Elem * const elem = *elem_it;
           if (elem->processor_id() != p)
             coupled_elements.insert (std::make_pair(elem,_dof_coupling));
         }
       return;
     }
   typedef LIBMESH_BEST_UNORDERED_SET<const Elem*> set_type;
   set_type next_elements_to_check(range_begin, range_end);
   set_type elements_to_check;
   set_type elements_checked;
   for (unsigned int i=0; i != this->_n_levels; ++i)
     {
       elements_to_check.swap(next_elements_to_check);
       next_elements_to_check.clear();
       elements_checked.insert(elements_to_check.begin(), elements_to_check.end());
       for (set_type::const_iterator elem_it  = elements_to_check.begin(),
                                     elem_end = elements_to_check.end();
            elem_it != elem_end; ++elem_it)
         {
           std::vector<const Elem *> active_neighbors;
           const Elem * const elem = *elem_it;
           if (elem->processor_id() != p)
             coupled_elements.insert (std::make_pair(elem,_dof_coupling));
           for (unsigned int s=0; s<elem->n_sides(); s++)
             {
               const Elem *neigh = elem->neighbor_ptr(s);
               // If we have a neighbor here
               if (neigh)
                 {
                   // Mesh ghosting might ask us about what we want to
                   // distribute along with non-local elements, and those
                   // non-local elements might have remote neighbors, and
                   // if they do then we can't say anything about them.
                   if (neigh == remote_elem)
                     continue;
                 }
 #ifdef LIBMESH_ENABLE_PERIODIC
               // We might still have a periodic neighbor here
               else if (check_periodic_bcs)
                 {
                   libmesh_assert(_mesh);
                   neigh = elem->topological_neighbor
                     (s, *_mesh, *point_locator, _periodic_bcs);
                 }
 #endif
               // With no regular *or* periodic neighbors we have nothing
               // to do.
               if (!neigh)
                 continue;
               // With any kind of neighbor, we need to couple to all the
               // active descendants on our side.
 #ifdef LIBMESH_ENABLE_AMR
               if (neigh == elem->neighbor_ptr(s))
                 neigh->active_family_tree_by_neighbor(active_neighbors,elem);
 #  ifdef LIBMESH_ENABLE_PERIODIC
               else
                 neigh->active_family_tree_by_topological_neighbor
                   (active_neighbors,elem,*_mesh,*point_locator,_periodic_bcs);
 #  endif
 #else
               active_neighbors.clear();
               active_neighbors.push_back(neigh);
 #endif
               for (std::size_t a=0; a != active_neighbors.size(); ++a)
                 {
                   const Elem * neighbor = active_neighbors[a];
                   if (!elements_checked.count(neighbor))
                     next_elements_to_check.insert(neighbor);
                   if (neighbor->processor_id() != p)
                     coupled_elements.insert
                       (std::make_pair(neighbor, _dof_coupling));
                 }
             }
         }
     }
 }
void libMesh::ReferenceCounter::print_info (std::ostream & out = libMesh::out) static inherited
Prints the reference information, by default to libMesh::out.
Definition at line 88 of file reference_counter.C.
References libMesh::ReferenceCounter::_enable_print_counter, and libMesh::ReferenceCounter::get_info().
 {
   if( _enable_print_counter ) out_stream << ReferenceCounter::get_info();
 }
virtual void libMesh::DefaultCoupling::redistribute () inline virtual
GhostingFunctor subclasses with relatively long-lasting caches may want to redistribute those caches whenever the relevant Mesh is redistributed; we will give them an opportunity when that happens. At the point in the code where this is called, element processor ids have been set to their new destinations, and those elements have been copied to their new destinations, but the elements have not yet been deleted by the processors which previously held them..
Reimplemented from libMesh::GhostingFunctor.
Definition at line 84 of file default_coupling.h.
References mesh_reinit().
   { this->mesh_reinit(); }
void libMesh::DefaultCoupling::set_dof_coupling (const CouplingMatrix * dof_coupling)
Definition at line 34 of file default_coupling.C.
References _dof_coupling, and libMesh::CouplingMatrix::empty().
 {
   // We used to treat an empty 0x0 _dof_coupling matrix as if it
   // were an NxN all-ones matrix.  We'd like to stop supporting this
   // behavior, but for now we'll just warn about it, while supporting
   // it via the preferred mechanism: a NULL _dof_coupling
   // matrix pointer is interpreted as a full coupling matrix.
   if (dof_coupling && dof_coupling->empty())
     {
       libmesh_deprecated();
       _dof_coupling = NULL;
     }
   else
     _dof_coupling = dof_coupling;
 }
void libMesh::DefaultCoupling::set_mesh (const MeshBase * mesh) inline
Definition at line 75 of file default_coupling.h.
References _mesh, and mesh.
   { _mesh = mesh; }
void libMesh::DefaultCoupling::set_n_levels (unsigned int n_levels) inline
Definition at line 65 of file default_coupling.h.
References _n_levels, and n_levels().
   { _n_levels = n_levels; }
void libMesh::DefaultCoupling::set_periodic_boundaries (const PeriodicBoundaries * periodic_bcs) inline
Definition at line 70 of file default_coupling.h.
References _periodic_bcs.
   { _periodic_bcs = periodic_bcs; }
Member Data Documentation
ReferenceCounter::Counts libMesh::ReferenceCounter::_counts static protected inherited
Actually holds the data.
Definition at line 115 of file reference_counter.h.
Referenced by libMesh::ReferenceCounter::get_info(), libMesh::ReferenceCounter::increment_constructor_count(), and libMesh::ReferenceCounter::increment_destructor_count().
const CouplingMatrix* libMesh::DefaultCoupling::_dof_coupling private
Definition at line 107 of file default_coupling.h.
Referenced by set_dof_coupling().
bool libMesh::ReferenceCounter::_enable_print_counter = true static protected inherited
Flag to control whether reference count information is printed when print_info is called.
Definition at line 134 of file reference_counter.h.
Referenced by libMesh::ReferenceCounter::disable_print_counter_info(), libMesh::ReferenceCounter::enable_print_counter_info(), and libMesh::ReferenceCounter::print_info().
const MeshBase* libMesh::DefaultCoupling::_mesh private
Definition at line 111 of file default_coupling.h.
Referenced by mesh_reinit(), and set_mesh().
Threads::spin_mutex libMesh::ReferenceCounter::_mutex static protected inherited
Mutual exclusion object to enable thread-safe reference counting.
Definition at line 128 of file reference_counter.h.
unsigned int libMesh::DefaultCoupling::_n_levels private
Definition at line 112 of file default_coupling.h.
Referenced by n_levels(), and set_n_levels().
Threads::atomic< unsigned int > libMesh::ReferenceCounter::_n_objects static protected inherited
The number of objects. Print the reference count information when the number returns to 0.
Definition at line 123 of file reference_counter.h.
Referenced by libMesh::ReferenceCounter::n_objects(), libMesh::ReferenceCounter::ReferenceCounter(), and libMesh::ReferenceCounter::~ReferenceCounter().
const PeriodicBoundaries* libMesh::DefaultCoupling::_periodic_bcs private
Definition at line 109 of file default_coupling.h.
Referenced by mesh_reinit(), and set_periodic_boundaries().
The documentation for this class was generated from the following files:
default_coupling.h
default_coupling.C