libMesh: libMesh::ExodusII_IO Class Reference
SomeWebsiteLogo
libMesh::ExodusII_IO Class Reference
Handles reading and writing of Exodus binary files.
#include <exodusII_io.h>
Public Member Functions
ExodusII_IO (MeshBase &mesh, bool single_precision=false)
virtual ~ExodusII_IO ()
virtual void read (const std::string &name) override
virtual void write (const std::string &fname) override
void verbose (bool set_verbosity)
const std::vector< Real > & get_time_steps ()
int get_num_time_steps ()
void copy_nodal_solution (System &system, std::string var_name, unsigned int timestep=1)
void copy_nodal_solution (System &system, std::string system_var_name, std::string exodus_var_name, unsigned int timestep=1)
void copy_elemental_solution (System &system, std::string system_var_name, std::string exodus_var_name, unsigned int timestep=1)
void read_elemental_variable (std::string elemental_var_name, unsigned int timestep, std::map< unsigned int, Real > &unique_id_to_value_map)
void read_global_variable (std::vector< std::string > global_var_names, unsigned int timestep, std::vector< Real > &global_values)
void write_discontinuous_exodusII (const std::string &name, const EquationSystems &es, const std::set< std::string > *system_names=nullptr)
void write_timestep_discontinuous (const std::string &fname, const EquationSystems &es, const int timestep, const Real time, const std::set< std::string > *system_names=nullptr)
void write_element_data (const EquationSystems &es)
virtual void write_nodal_data (const std::string &, const std::vector< Number > &, const std::vector< std::string > &) override
void write_nodal_data_discontinuous (const std::string &, const std::vector< Number > &, const std::vector< std::string > &) override
void write_global_data (const std::vector< Number > &, const std::vector< std::string > &)
void write_information_records (const std::vector< std::string > &)
void write_timestep (const std::string &fname, const EquationSystems &es, const int timestep, const Real time, const std::set< std::string > *system_names=nullptr)
void set_output_variables (const std::vector< std::string > &output_variables, bool allow_empty=true)
void use_mesh_dimension_instead_of_spatial_dimension (bool val)
void write_as_dimension (unsigned dim)
void set_coordinate_offset (Point p)
void append (bool val)
const std::vector< std::string > & get_elem_var_names ()
const std::vector< std::string > & get_nodal_var_names ()
ExodusII_IO_Helper & get_exio_helper ()
void write_nodal_data_common (std::string fname, const std::vector< std::string > &names, bool continuous=true)
virtual void write_equation_systems (const std::string &, const EquationSystems &, const std::set< std::string > *system_names=nullptr)
virtual void write_discontinuous_equation_systems (const std::string &, const EquationSystems &, const std::set< std::string > *system_names=nullptr)
virtual void write_nodal_data (const std::string &, const NumericVector< Number > &, const std::vector< std::string > &)
unsigned int & ascii_precision ()
const Parallel::Communicator & comm () const
processor_id_type n_processors () const
processor_id_type processor_id () const
Protected Member Functions
MeshBase & mesh ()
void set_n_partitions (unsigned int n_parts)
void skip_comment_lines (std::istream &in, const char comment_start)
const MeshBase & mesh () const
Protected Attributes
std::vector< bool > elems_of_dimension
const bool _is_parallel_format
const bool _serial_only_needed_on_proc_0
const Parallel::Communicator & _communicator
Private Attributes
std::unique_ptr< ExodusII_IO_Helper > exio_helper
int _timestep
bool _verbose
bool _append
std::vector< std::string > _output_variables
bool _allow_empty_variables
Detailed Description
Handles reading and writing of Exodus binary files.
The ExodusII_IO class implements reading meshes in the ExodusII file format from Sandia National Labs. By default, LibMesh expects ExodusII files to have a ".exd" or ".e" file extension.
Author
Benjamin Kirk
John Peterson
Date
2004
Definition at line 52 of file exodusII_io.h.
Constructor & Destructor Documentation
ExodusII_IO()
libMesh::ExodusII_IO::ExodusII_IO (MeshBase & mesh, bool single_precision = false) explicit
Constructor. Takes a writable reference to a mesh object. This is the constructor required to read a mesh.
Definition at line 45 of file exodusII_io.C.
                             :
   MeshInput<MeshBase> (mesh),
   MeshOutput<MeshBase> (mesh,
                         /* is_parallel_format = */ false,
                         /* serial_only_needed_on_proc_0 = */ true),
   ParallelObject(mesh),
 #ifdef LIBMESH_HAVE_EXODUS_API
   exio_helper(new ExodusII_IO_Helper(*this, false, true, single_precision)),
   _timestep(1),
   _verbose(false),
   _append(false),
 #endif
   _allow_empty_variables(false)
 {
 }
~ExodusII_IO()
libMesh::ExodusII_IO::~ExodusII_IO () virtual
Destructor.
Definition at line 133 of file exodusII_io.C.
References exio_helper.
 {
   exio_helper->close();
 }
Member Function Documentation
append()
void libMesh::ExodusII_IO::append (bool val)
If true, this flag will cause the ExodusII_IO object to attempt to open an existing file for writing, rather than creating a new file. Obviously this will only work if the file already exists.
Definition at line 450 of file exodusII_io.C.
References _append.
 {
   _append = val;
 }
ascii_precision()
unsigned int & libMesh::MeshOutput< MeshBase >::ascii_precision () inline inherited
Return/set the precision to use when writing ASCII files.
By default we use numeric_limits<Real>::digits10 + 2, which should be enough to write out to ASCII and get the exact same Real back when reading in.
Definition at line 244 of file mesh_output.h.
Referenced by libMesh::TecplotIO::write_ascii(), libMesh::GMVIO::write_ascii_new_impl(), and libMesh::GMVIO::write_ascii_old_impl().
 {
   return _ascii_precision;
 }
comm()
const Parallel::Communicator& libMesh::ParallelObject::comm () const inline inherited
Returns
A reference to the Parallel::Communicator object used by this mesh.
Definition at line 89 of file parallel_object.h.
References libMesh::ParallelObject::_communicator.
Referenced by libMesh::__libmesh_petsc_diff_solver_jacobian(), libMesh::__libmesh_petsc_diff_solver_monitor(), libMesh::__libmesh_petsc_diff_solver_residual(), libMesh::__libmesh_tao_equality_constraints(), libMesh::__libmesh_tao_equality_constraints_jacobian(), libMesh::__libmesh_tao_gradient(), libMesh::__libmesh_tao_hessian(), libMesh::__libmesh_tao_inequality_constraints(), libMesh::__libmesh_tao_inequality_constraints_jacobian(), libMesh::__libmesh_tao_objective(), libMesh::MeshRefinement::_coarsen_elements(), libMesh::ExactSolution::_compute_error(), libMesh::UniformRefinementEstimator::_estimate_error(), libMesh::BoundaryInfo::_find_id_maps(), libMesh::SlepcEigenSolver< T >::_petsc_shell_matrix_get_diagonal(), libMesh::PetscLinearSolver< T >::_petsc_shell_matrix_get_diagonal(), libMesh::SlepcEigenSolver< T >::_petsc_shell_matrix_mult(), libMesh::PetscLinearSolver< T >::_petsc_shell_matrix_mult(), libMesh::PetscLinearSolver< T >::_petsc_shell_matrix_mult_add(), libMesh::EquationSystems::_read_impl(), libMesh::MeshRefinement::_refine_elements(), libMesh::MeshRefinement::_smooth_flags(), libMesh::PetscDMWrapper::add_dofs_helper(), libMesh::PetscDMWrapper::add_dofs_to_section(), libMesh::ImplicitSystem::add_matrix(), libMesh::System::add_vector(), libMesh::UnstructuredMesh::all_second_order(), libMesh::MeshTools::Modification::all_tri(), libMesh::LaplaceMeshSmoother::allgather_graph(), libMesh::FEMSystem::assemble_qoi(), libMesh::MeshCommunication::assign_global_indices(), libMesh::DofMap::attach_matrix(), libMesh::MeshTools::Generation::build_extrusion(), libMesh::BoundaryInfo::build_node_list_from_side_list(), libMesh::EquationSystems::build_parallel_elemental_solution_vector(), libMesh::EquationSystems::build_parallel_solution_vector(), libMesh::PetscDMWrapper::build_section(), libMesh::PetscDMWrapper::build_sf(), libMesh::MeshBase::cache_elem_dims(), libMesh::System::calculate_norm(), libMesh::DofMap::check_dirichlet_bcid_consistency(), libMesh::PetscDMWrapper::check_section_n_dofs(), libMesh::Nemesis_IO_Helper::compute_num_global_elem_blocks(), libMesh::Nemesis_IO_Helper::compute_num_global_nodesets(), libMesh::Nemesis_IO_Helper::compute_num_global_sidesets(), libMesh::Problem_Interface::computeF(), libMesh::Problem_Interface::computeJacobian(), libMesh::Problem_Interface::computePreconditioner(), copy_elemental_solution(), libMesh::MeshTools::correct_node_proc_ids(), libMesh::MeshTools::create_bounding_box(), libMesh::MeshTools::create_nodal_bounding_box(), libMesh::MeshRefinement::create_parent_error_vector(), libMesh::MeshTools::create_processor_bounding_box(), libMesh::MeshTools::create_subdomain_bounding_box(), libMesh::MeshCommunication::delete_remote_elements(), libMesh::DofMap::distribute_dofs(), DMlibMeshFunction(), DMlibMeshJacobian(), DMlibMeshSetSystem_libMesh(), DMVariableBounds_libMesh(), libMesh::MeshRefinement::eliminate_unrefined_patches(), libMesh::EpetraVector< T >::EpetraVector(), libMesh::WeightedPatchRecoveryErrorEstimator::estimate_error(), libMesh::PatchRecoveryErrorEstimator::estimate_error(), libMesh::JumpErrorEstimator::estimate_error(), libMesh::AdjointRefinementEstimator::estimate_error(), libMesh::ExactErrorEstimator::estimate_error(), libMesh::MeshRefinement::flag_elements_by_elem_fraction(), libMesh::MeshRefinement::flag_elements_by_error_fraction(), libMesh::MeshRefinement::flag_elements_by_nelem_target(), libMesh::CondensedEigenSystem::get_eigenpair(), libMesh::DofMap::get_info(), libMesh::ImplicitSystem::get_linear_solver(), libMesh::LocationMap< T >::init(), libMesh::TimeSolver::init(), libMesh::SystemSubsetBySubdomain::init(), libMesh::PetscDMWrapper::init_and_attach_petscdm(), libMesh::EigenSystem::init_data(), libMesh::EigenSystem::init_matrices(), libMesh::OptimizationSystem::initialize_equality_constraints_storage(), libMesh::OptimizationSystem::initialize_inequality_constraints_storage(), libMesh::MeshTools::libmesh_assert_consistent_distributed(), libMesh::MeshTools::libmesh_assert_consistent_distributed_nodes(), libMesh::MeshTools::libmesh_assert_contiguous_dof_ids(), libMesh::MeshTools::libmesh_assert_parallel_consistent_new_node_procids(), libMesh::MeshTools::libmesh_assert_parallel_consistent_procids< Elem >(), libMesh::MeshTools::libmesh_assert_parallel_consistent_procids< Node >(), libMesh::MeshTools::libmesh_assert_topology_consistent_procids< Node >(), libMesh::MeshTools::libmesh_assert_valid_boundary_ids(), libMesh::MeshTools::libmesh_assert_valid_dof_ids(), libMesh::MeshTools::libmesh_assert_valid_neighbors(), libMesh::DistributedMesh::libmesh_assert_valid_parallel_flags(), libMesh::DistributedMesh::libmesh_assert_valid_parallel_object_ids(), libMesh::DistributedMesh::libmesh_assert_valid_parallel_p_levels(), libMesh::MeshTools::libmesh_assert_valid_refinement_flags(), libMesh::MeshTools::libmesh_assert_valid_unique_ids(), libMesh::libmesh_petsc_snes_fd_residual(), libMesh::libmesh_petsc_snes_jacobian(), libMesh::libmesh_petsc_snes_mffd_residual(), libMesh::libmesh_petsc_snes_postcheck(), libMesh::libmesh_petsc_snes_residual(), libMesh::libmesh_petsc_snes_residual_helper(), libMesh::MeshRefinement::limit_level_mismatch_at_edge(), libMesh::MeshRefinement::limit_level_mismatch_at_node(), libMesh::MeshRefinement::limit_overrefined_boundary(), libMesh::MeshRefinement::limit_underrefined_boundary(), libMesh::MeshRefinement::make_coarsening_compatible(), libMesh::MeshCommunication::make_elems_parallel_consistent(), libMesh::MeshRefinement::make_flags_parallel_consistent(), libMesh::MeshCommunication::make_new_node_proc_ids_parallel_consistent(), libMesh::MeshCommunication::make_new_nodes_parallel_consistent(), libMesh::MeshCommunication::make_node_ids_parallel_consistent(), libMesh::MeshCommunication::make_node_proc_ids_parallel_consistent(), libMesh::MeshCommunication::make_node_unique_ids_parallel_consistent(), libMesh::MeshCommunication::make_nodes_parallel_consistent(), libMesh::MeshCommunication::make_p_levels_parallel_consistent(), libMesh::MeshRefinement::make_refinement_compatible(), libMesh::FEMSystem::mesh_position_set(), libMesh::DistributedMesh::n_active_elem(), libMesh::MeshTools::n_active_levels(), libMesh::BoundaryInfo::n_boundary_conds(), libMesh::BoundaryInfo::n_edge_conds(), libMesh::CondensedEigenSystem::n_global_non_condensed_dofs(), libMesh::MeshTools::n_levels(), libMesh::BoundaryInfo::n_nodeset_conds(), libMesh::MeshTools::n_p_levels(), libMesh::BoundaryInfo::n_shellface_conds(), libMesh::DistributedMesh::parallel_max_elem_id(), libMesh::DistributedMesh::parallel_max_node_id(), libMesh::ReplicatedMesh::parallel_max_unique_id(), libMesh::DistributedMesh::parallel_max_unique_id(), libMesh::DistributedMesh::parallel_n_elem(), libMesh::DistributedMesh::parallel_n_nodes(), libMesh::SparsityPattern::Build::parallel_sync(), libMesh::MeshTools::paranoid_n_levels(), libMesh::petsc_auto_fieldsplit(), libMesh::System::point_gradient(), libMesh::System::point_hessian(), libMesh::System::point_value(), libMesh::MeshBase::prepare_for_use(), libMesh::Nemesis_IO::read(), libMesh::XdrIO::read(), libMesh::CheckpointIO::read_header(), libMesh::XdrIO::read_header(), libMesh::System::read_header(), libMesh::System::read_legacy_data(), libMesh::System::read_SCALAR_dofs(), libMesh::XdrIO::read_serialized_bc_names(), libMesh::XdrIO::read_serialized_bcs_helper(), libMesh::System::read_serialized_blocked_dof_objects(), libMesh::XdrIO::read_serialized_connectivity(), libMesh::XdrIO::read_serialized_nodes(), libMesh::XdrIO::read_serialized_nodesets(), libMesh::XdrIO::read_serialized_subdomain_names(), libMesh::System::read_serialized_vector(), libMesh::MeshBase::recalculate_n_partitions(), libMesh::MeshRefinement::refine_and_coarsen_elements(), libMesh::DistributedMesh::renumber_dof_objects(), libMesh::CheckpointIO::select_split_config(), libMesh::DofMap::set_nonlocal_dof_objects(), libMesh::PetscDMWrapper::set_point_range_in_section(), libMesh::PetscDiffSolver::setup_petsc_data(), libMesh::LaplaceMeshSmoother::smooth(), libMesh::split_mesh(), libMesh::MeshBase::subdomain_ids(), libMesh::BoundaryInfo::sync(), libMesh::MeshRefinement::test_level_one(), libMesh::MeshRefinement::test_unflagged(), libMesh::MeshTools::total_weight(), libMesh::MeshRefinement::uniformly_coarsen(), libMesh::NameBasedIO::write(), libMesh::XdrIO::write(), libMesh::System::write_SCALAR_dofs(), libMesh::XdrIO::write_serialized_bcs_helper(), libMesh::System::write_serialized_blocked_dof_objects(), libMesh::XdrIO::write_serialized_connectivity(), libMesh::XdrIO::write_serialized_nodes(), and libMesh::XdrIO::write_serialized_nodesets().
   { return _communicator; }
copy_elemental_solution()
void libMesh::ExodusII_IO::copy_elemental_solution (System & system, std::string system_var_name, std::string exodus_var_name, unsigned int timestep = 1)
If we read in a elemental solution while reading in a mesh, we can attempt to copy that elemental solution into an EquationSystems object.
Definition at line 513 of file exodusII_io.C.
References libMesh::ParallelObject::comm(), libMesh::CONSTANT, libMesh::DofObject::dof_number(), end, exio_helper, libMesh::MeshInput< MT >::mesh(), libMesh::MONOMIAL, libMesh::DofObject::n_comp(), libMesh::System::number(), libMesh::Parallel::Communicator::rank(), libMesh::System::solution, libMesh::System::update(), libMesh::System::variable_number(), and libMesh::System::variable_type().
 {
   if (system.comm().rank() == 0)
     {
       if (!exio_helper->opened_for_reading)
         libmesh_error_msg("ERROR, ExodusII file must be opened for reading before copying an elemental solution!");
       // Map from element ID to elemental variable value.  We need to use
       // a map here rather than a vector (e.g. elem_var_values) since the
       // libmesh element numbering can contain "holes".  This is the case
       // if we are reading elemental var values from an adaptively refined
       // mesh that has not been sequentially renumbered.
       std::map<dof_id_type, Real> elem_var_value_map;
       exio_helper->read_elemental_var_values(exodus_var_name, timestep, elem_var_value_map);
       const unsigned int var_num = system.variable_number(system_var_name);
       if (system.variable_type(var_num) != FEType(CONSTANT, MONOMIAL))
         libmesh_error_msg("Error! Trying to copy elemental solution into a variable that is not of CONSTANT MONOMIAL type.");
       std::map<dof_id_type, Real>::iterator
         it = elem_var_value_map.begin(),
         end = elem_var_value_map.end();
       for (; it!=end; ++it)
         {
           const Elem * elem = MeshInput<MeshBase>::mesh().query_elem_ptr(it->first);
           if (elem && elem->n_comp(system.number(), var_num) > 0)
             {
               dof_id_type dof_index = elem->dof_number(system.number(), var_num, 0);
               system.solution->set (dof_index, it->second);
             }
         }
     }
   system.solution->close();
   system.update();
 }
copy_nodal_solution() [1/2]
void libMesh::ExodusII_IO::copy_nodal_solution (System & system, std::string var_name, unsigned int timestep = 1)
Backward compatibility version of function that takes a single variable name.
Deprecated:
Use the version of copy_nodal_solution() that takes two names.
Definition at line 78 of file exodusII_io.C.
 {
   libmesh_deprecated();
   copy_nodal_solution(system, var_name, var_name, timestep);
 }
copy_nodal_solution() [2/2]
void libMesh::ExodusII_IO::copy_nodal_solution (System & system, std::string system_var_name, std::string exodus_var_name, unsigned int timestep = 1)
If we read in a nodal solution while reading in a mesh, we can attempt to copy that nodal solution into an EquationSystems object.
Definition at line 479 of file exodusII_io.C.
References libMesh::DofObject::dof_number(), exio_helper, libMesh::MeshInput< MT >::mesh(), libMesh::DofObject::n_comp(), libMesh::System::number(), libMesh::System::solution, libMesh::System::update(), and libMesh::System::variable_number().
 {
   if (!exio_helper->opened_for_reading)
     libmesh_error_msg("ERROR, ExodusII file must be opened for reading before copying a nodal solution!");
   exio_helper->read_nodal_var_values(exodus_var_name, timestep);
   const unsigned int var_num = system.variable_number(system_var_name);
   for (dof_id_type i=0,
        n_nodal = cast_int<dof_id_type>(exio_helper->nodal_var_values.size());
        i != n_nodal; ++i)
     {
       const Node * node = MeshInput<MeshBase>::mesh().query_node_ptr(i);
       if (node && node->n_comp(system.number(), var_num) > 0)
         {
           dof_id_type dof_index = node->dof_number(system.number(), var_num, 0);
           // If the dof_index is local to this processor, set the value
           if ((dof_index >= system.solution->first_local_index()) && (dof_index < system.solution->last_local_index()))
             system.solution->set (dof_index, exio_helper->nodal_var_values[i]);
         }
     }
   system.solution->close();
   system.update();
 }
get_elem_var_names()
const std::vector< std::string > & libMesh::ExodusII_IO::get_elem_var_names ()
Return list of the elemental variable names
Definition at line 1032 of file exodusII_io.C.
References libMesh::ExodusII_IO_Helper::ELEMENTAL, and exio_helper.
 {
   exio_helper->read_var_names(ExodusII_IO_Helper::ELEMENTAL);
   return exio_helper->elem_var_names;
 }
get_exio_helper()
ExodusII_IO_Helper & libMesh::ExodusII_IO::get_exio_helper ()
Return a reference to the ExodusII_IO_Helper object.
Definition at line 1038 of file exodusII_io.C.
References exio_helper.
 {
   // Provide a warning when accessing the helper object
   // since it is a non-public API and is likely to see
   // future API changes
   libmesh_experimental();
   return *exio_helper;
 }
get_nodal_var_names()
const std::vector< std::string > & libMesh::ExodusII_IO::get_nodal_var_names ()
Return list of the nodal variable names
Definition at line 1026 of file exodusII_io.C.
References exio_helper, and libMesh::ExodusII_IO_Helper::NODAL.
 {
   exio_helper->read_var_names(ExodusII_IO_Helper::NODAL);
   return exio_helper->nodal_var_names;
 }
get_num_time_steps()
int libMesh::ExodusII_IO::get_num_time_steps ()
Returns
The number of timesteps currently stored in the Exodus file.
Knowing the number of time steps currently stored in the file is sometimes necessary when appending, so we can know where to start writing new data. Throws an error if the file is not currently open for reading or writing.
Definition at line 468 of file exodusII_io.C.
References exio_helper.
 {
   if (!exio_helper->opened_for_reading && !exio_helper->opened_for_writing)
     libmesh_error_msg("ERROR, ExodusII file must be opened for reading or writing before calling ExodusII_IO::get_num_time_steps()!");
   exio_helper->read_num_time_steps();
   return exio_helper->num_time_steps;
 }
get_time_steps()
const std::vector< Real > & libMesh::ExodusII_IO::get_time_steps ()
Returns
An array containing the timesteps in the file.
Definition at line 457 of file exodusII_io.C.
References exio_helper.
 {
   if (!exio_helper->opened_for_reading)
     libmesh_error_msg("ERROR, ExodusII file must be opened for reading before calling ExodusII_IO::get_time_steps()!");
   exio_helper->read_time_steps();
   return exio_helper->time_steps;
 }
mesh() [1/2]
MeshBase & libMesh::MeshInput< MeshBase >::mesh () inline protected inherited
Returns
The object as a writable reference.
Definition at line 169 of file mesh_input.h.
Referenced by libMesh::GMVIO::_read_one_cell(), libMesh::VTKIO::cells_to_vtk(), libMesh::TetGenIO::element_in(), libMesh::UNVIO::elements_in(), libMesh::UNVIO::elements_out(), libMesh::UNVIO::groups_in(), libMesh::TetGenIO::node_in(), libMesh::UNVIO::nodes_in(), libMesh::UNVIO::nodes_out(), libMesh::VTKIO::nodes_to_vtk(), libMesh::Nemesis_IO::prepare_to_write_nodal_data(), libMesh::Nemesis_IO::read(), read(), libMesh::GMVIO::read(), libMesh::XdrIO::read(), libMesh::CheckpointIO::read(), libMesh::VTKIO::read(), libMesh::CheckpointIO::read_bcs(), libMesh::CheckpointIO::read_connectivity(), libMesh::CheckpointIO::read_header(), libMesh::XdrIO::read_header(), libMesh::UCDIO::read_implementation(), libMesh::UNVIO::read_implementation(), libMesh::GmshIO::read_mesh(), libMesh::CheckpointIO::read_nodes(), libMesh::CheckpointIO::read_nodesets(), libMesh::CheckpointIO::read_remote_elem(), libMesh::XdrIO::read_serialized_bcs_helper(), libMesh::XdrIO::read_serialized_connectivity(), libMesh::XdrIO::read_serialized_nodes(), libMesh::XdrIO::read_serialized_nodesets(), libMesh::XdrIO::read_serialized_subdomain_names(), libMesh::OFFIO::read_stream(), libMesh::MatlabIO::read_stream(), libMesh::CheckpointIO::read_subdomain_names(), libMesh::TetGenIO::write(), libMesh::Nemesis_IO::write(), write(), libMesh::XdrIO::write(), libMesh::CheckpointIO::write(), libMesh::GMVIO::write_ascii_new_impl(), libMesh::GMVIO::write_ascii_old_impl(), libMesh::GMVIO::write_binary(), libMesh::GMVIO::write_discontinuous_gmv(), libMesh::Nemesis_IO::write_element_data(), write_element_data(), libMesh::UCDIO::write_header(), libMesh::UCDIO::write_implementation(), libMesh::UCDIO::write_interior_elems(), libMesh::GmshIO::write_mesh(), libMesh::VTKIO::write_nodal_data(), libMesh::UCDIO::write_nodal_data(), write_nodal_data(), write_nodal_data_common(), write_nodal_data_discontinuous(), libMesh::UCDIO::write_nodes(), libMesh::CheckpointIO::write_nodesets(), libMesh::XdrIO::write_parallel(), libMesh::GmshIO::write_post(), libMesh::XdrIO::write_serialized_bcs_helper(), libMesh::XdrIO::write_serialized_connectivity(), libMesh::XdrIO::write_serialized_nodes(), libMesh::XdrIO::write_serialized_nodesets(), libMesh::XdrIO::write_serialized_subdomain_names(), libMesh::UCDIO::write_soln(), and libMesh::CheckpointIO::write_subdomain_names().
 {
   if (_obj == nullptr)
     libmesh_error_msg("ERROR: _obj should not be nullptr!");
   return *_obj;
 }
mesh() [2/2]
const MeshBase & libMesh::MeshOutput< MeshBase >::mesh () const inline protected inherited
Returns
The object as a read-only reference.
Definition at line 234 of file mesh_output.h.
Referenced by libMesh::FroIO::write(), libMesh::TecplotIO::write(), libMesh::MEDITIO::write(), libMesh::PostscriptIO::write(), libMesh::EnsightIO::write(), libMesh::TecplotIO::write_ascii(), libMesh::TecplotIO::write_binary(), libMesh::TecplotIO::write_nodal_data(), libMesh::MEDITIO::write_nodal_data(), and libMesh::GnuPlotIO::write_solution().
 {
   libmesh_assert(_obj);
   return *_obj;
 }
n_processors()
processor_id_type libMesh::ParallelObject::n_processors () const inline inherited
Returns
The number of processors in the group.
Definition at line 95 of file parallel_object.h.
References libMesh::ParallelObject::_communicator, and libMesh::Parallel::Communicator::size().
Referenced by libMesh::BoundaryInfo::_find_id_maps(), libMesh::PetscDMWrapper::add_dofs_to_section(), libMesh::DistributedMesh::add_elem(), libMesh::DistributedMesh::add_node(), libMesh::LaplaceMeshSmoother::allgather_graph(), libMesh::FEMSystem::assembly(), libMesh::AztecLinearSolver< T >::AztecLinearSolver(), libMesh::BoundaryInfo::build_node_list_from_side_list(), libMesh::EquationSystems::build_parallel_elemental_solution_vector(), libMesh::DistributedMesh::clear(), libMesh::Nemesis_IO_Helper::compute_border_node_ids(), libMesh::Nemesis_IO_Helper::construct_nemesis_filename(), libMesh::UnstructuredMesh::create_pid_mesh(), libMesh::MeshTools::create_processor_bounding_box(), libMesh::DofMap::distribute_dofs(), libMesh::DofMap::distribute_local_dofs_node_major(), libMesh::DofMap::distribute_local_dofs_var_major(), libMesh::EnsightIO::EnsightIO(), libMesh::MeshBase::get_info(), libMesh::SystemSubsetBySubdomain::init(), libMesh::PetscDMWrapper::init_and_attach_petscdm(), libMesh::Nemesis_IO_Helper::initialize(), libMesh::DistributedMesh::insert_elem(), libMesh::MeshTools::libmesh_assert_contiguous_dof_ids(), libMesh::MeshTools::libmesh_assert_parallel_consistent_new_node_procids(), libMesh::MeshTools::libmesh_assert_parallel_consistent_procids< Elem >(), libMesh::MeshTools::libmesh_assert_parallel_consistent_procids< Node >(), libMesh::MeshTools::libmesh_assert_topology_consistent_procids< Node >(), libMesh::MeshTools::libmesh_assert_valid_boundary_ids(), libMesh::MeshTools::libmesh_assert_valid_dof_ids(), libMesh::MeshTools::libmesh_assert_valid_neighbors(), libMesh::MeshTools::libmesh_assert_valid_refinement_flags(), libMesh::DofMap::local_variable_indices(), libMesh::MeshRefinement::make_coarsening_compatible(), libMesh::MeshBase::n_active_elem_on_proc(), libMesh::MeshBase::n_elem_on_proc(), libMesh::MeshBase::n_nodes_on_proc(), libMesh::MeshBase::partition(), libMesh::PetscLinearSolver< T >::PetscLinearSolver(), libMesh::System::point_gradient(), libMesh::System::point_hessian(), libMesh::System::point_value(), libMesh::NameBasedIO::read(), libMesh::Nemesis_IO::read(), libMesh::CheckpointIO::read(), libMesh::CheckpointIO::read_connectivity(), libMesh::XdrIO::read_header(), libMesh::CheckpointIO::read_nodes(), libMesh::System::read_parallel_data(), libMesh::System::read_SCALAR_dofs(), libMesh::System::read_serialized_blocked_dof_objects(), libMesh::System::read_serialized_vector(), libMesh::DistributedMesh::renumber_dof_objects(), libMesh::DofMap::set_nonlocal_dof_objects(), libMesh::PetscDMWrapper::set_point_range_in_section(), libMesh::MeshRefinement::uniformly_coarsen(), libMesh::DistributedMesh::update_parallel_id_counts(), libMesh::GMVIO::write_binary(), libMesh::GMVIO::write_discontinuous_gmv(), libMesh::System::write_parallel_data(), libMesh::System::write_SCALAR_dofs(), libMesh::XdrIO::write_serialized_bcs_helper(), libMesh::System::write_serialized_blocked_dof_objects(), libMesh::XdrIO::write_serialized_connectivity(), libMesh::XdrIO::write_serialized_nodes(), and libMesh::XdrIO::write_serialized_nodesets().
   { return cast_int<processor_id_type>(_communicator.size()); }
processor_id()
processor_id_type libMesh::ParallelObject::processor_id () const inline inherited
Returns
The rank of this processor in the group.
Definition at line 101 of file parallel_object.h.
References libMesh::ParallelObject::_communicator, and libMesh::Parallel::Communicator::rank().
Referenced by libMesh::BoundaryInfo::_find_id_maps(), libMesh::EquationSystems::_read_impl(), libMesh::PetscDMWrapper::add_dofs_to_section(), libMesh::DistributedMesh::add_elem(), libMesh::BoundaryInfo::add_elements(), libMesh::DofMap::add_neighbors_to_send_list(), libMesh::DistributedMesh::add_node(), libMesh::UnstructuredMesh::all_second_order(), libMesh::MeshTools::Modification::all_tri(), libMesh::FEMSystem::assembly(), libMesh::EquationSystems::build_discontinuous_solution_vector(), libMesh::Nemesis_IO_Helper::build_element_and_node_maps(), libMesh::InfElemBuilder::build_inf_elem(), libMesh::BoundaryInfo::build_node_list_from_side_list(), libMesh::EquationSystems::build_parallel_elemental_solution_vector(), libMesh::DistributedMesh::clear(), libMesh::ExodusII_IO_Helper::close(), libMesh::Nemesis_IO_Helper::compute_border_node_ids(), libMesh::Nemesis_IO_Helper::compute_communication_map_parameters(), libMesh::Nemesis_IO_Helper::compute_internal_and_border_elems_and_internal_nodes(), libMesh::Nemesis_IO_Helper::compute_node_communication_maps(), libMesh::Nemesis_IO_Helper::compute_num_global_elem_blocks(), libMesh::Nemesis_IO_Helper::compute_num_global_nodesets(), libMesh::Nemesis_IO_Helper::compute_num_global_sidesets(), libMesh::Nemesis_IO_Helper::construct_nemesis_filename(), libMesh::MeshTools::correct_node_proc_ids(), libMesh::ExodusII_IO_Helper::create(), libMesh::DistributedMesh::delete_elem(), libMesh::DistributedMesh::delete_node(), libMesh::MeshCommunication::delete_remote_elements(), libMesh::DofMap::distribute_dofs(), libMesh::DofMap::distribute_local_dofs_node_major(), libMesh::DofMap::distribute_local_dofs_var_major(), libMesh::DistributedMesh::DistributedMesh(), libMesh::DofMap::end_dof(), libMesh::DofMap::end_old_dof(), libMesh::EnsightIO::EnsightIO(), libMesh::MeshFunction::find_element(), libMesh::MeshFunction::find_elements(), libMesh::UnstructuredMesh::find_neighbors(), libMesh::DofMap::first_dof(), libMesh::DofMap::first_old_dof(), libMesh::Nemesis_IO_Helper::get_cmap_params(), libMesh::Nemesis_IO_Helper::get_eb_info_global(), libMesh::Nemesis_IO_Helper::get_elem_cmap(), libMesh::Nemesis_IO_Helper::get_elem_map(), libMesh::MeshBase::get_info(), libMesh::DofMap::get_info(), libMesh::Nemesis_IO_Helper::get_init_global(), libMesh::Nemesis_IO_Helper::get_init_info(), libMesh::Nemesis_IO_Helper::get_loadbal_param(), libMesh::Nemesis_IO_Helper::get_node_cmap(), libMesh::Nemesis_IO_Helper::get_node_map(), libMesh::Nemesis_IO_Helper::get_ns_param_global(), libMesh::Nemesis_IO_Helper::get_ss_param_global(), libMesh::SparsityPattern::Build::handle_vi_vj(), libMesh::SystemSubsetBySubdomain::init(), libMesh::ExodusII_IO_Helper::initialize(), libMesh::ExodusII_IO_Helper::initialize_element_variables(), libMesh::ExodusII_IO_Helper::initialize_global_variables(), libMesh::ExodusII_IO_Helper::initialize_nodal_variables(), libMesh::DistributedMesh::insert_elem(), libMesh::DofMap::is_evaluable(), libMesh::SparsityPattern::Build::join(), libMesh::DofMap::last_dof(), libMesh::MeshTools::libmesh_assert_consistent_distributed(), libMesh::MeshTools::libmesh_assert_consistent_distributed_nodes(), libMesh::MeshTools::libmesh_assert_contiguous_dof_ids(), libMesh::MeshTools::libmesh_assert_parallel_consistent_procids< Elem >(), libMesh::MeshTools::libmesh_assert_valid_neighbors(), libMesh::DistributedMesh::libmesh_assert_valid_parallel_object_ids(), libMesh::DofMap::local_variable_indices(), libMesh::MeshRefinement::make_coarsening_compatible(), libMesh::MeshBase::n_active_local_elem(), libMesh::BoundaryInfo::n_boundary_conds(), libMesh::BoundaryInfo::n_edge_conds(), libMesh::DofMap::n_local_dofs(), libMesh::System::n_local_dofs(), libMesh::MeshBase::n_local_elem(), libMesh::MeshBase::n_local_nodes(), libMesh::BoundaryInfo::n_nodeset_conds(), libMesh::BoundaryInfo::n_shellface_conds(), libMesh::SparsityPattern::Build::operator()(), libMesh::DistributedMesh::own_node(), libMesh::System::point_gradient(), libMesh::System::point_hessian(), libMesh::System::point_value(), libMesh::Nemesis_IO_Helper::put_cmap_params(), libMesh::Nemesis_IO_Helper::put_elem_cmap(), libMesh::Nemesis_IO_Helper::put_elem_map(), libMesh::Nemesis_IO_Helper::put_loadbal_param(), libMesh::Nemesis_IO_Helper::put_node_cmap(), libMesh::Nemesis_IO_Helper::put_node_map(), libMesh::NameBasedIO::read(), libMesh::Nemesis_IO::read(), libMesh::XdrIO::read(), libMesh::CheckpointIO::read(), libMesh::ExodusII_IO_Helper::read_elem_num_map(), libMesh::ExodusII_IO_Helper::read_global_values(), libMesh::CheckpointIO::read_header(), libMesh::XdrIO::read_header(), libMesh::System::read_header(), libMesh::System::read_legacy_data(), libMesh::ExodusII_IO_Helper::read_node_num_map(), libMesh::System::read_parallel_data(), libMesh::System::read_SCALAR_dofs(), libMesh::XdrIO::read_serialized_bc_names(), libMesh::XdrIO::read_serialized_bcs_helper(), libMesh::System::read_serialized_blocked_dof_objects(), libMesh::XdrIO::read_serialized_connectivity(), libMesh::System::read_serialized_data(), libMesh::XdrIO::read_serialized_nodes(), libMesh::XdrIO::read_serialized_nodesets(), libMesh::XdrIO::read_serialized_subdomain_names(), libMesh::System::read_serialized_vector(), libMesh::System::read_serialized_vectors(), libMesh::DistributedMesh::renumber_dof_objects(), libMesh::CheckpointIO::select_split_config(), libMesh::DofMap::set_nonlocal_dof_objects(), libMesh::PetscDMWrapper::set_point_range_in_section(), libMesh::LaplaceMeshSmoother::smooth(), libMesh::MeshTools::total_weight(), libMesh::MeshRefinement::uniformly_coarsen(), libMesh::Parallel::Packing< T >::unpack(), libMesh::DistributedMesh::update_parallel_id_counts(), libMesh::NameBasedIO::write(), libMesh::XdrIO::write(), libMesh::CheckpointIO::write(), libMesh::EquationSystems::write(), libMesh::GMVIO::write_discontinuous_gmv(), write_element_data(), libMesh::ExodusII_IO_Helper::write_element_values(), libMesh::ExodusII_IO_Helper::write_elements(), write_global_data(), libMesh::ExodusII_IO_Helper::write_global_values(), libMesh::System::write_header(), write_information_records(), libMesh::ExodusII_IO_Helper::write_information_records(), libMesh::ExodusII_IO_Helper::write_nodal_coordinates(), libMesh::UCDIO::write_nodal_data(), write_nodal_data(), write_nodal_data_discontinuous(), libMesh::ExodusII_IO_Helper::write_nodal_values(), libMesh::Nemesis_IO_Helper::write_nodesets(), libMesh::ExodusII_IO_Helper::write_nodesets(), libMesh::System::write_parallel_data(), libMesh::System::write_SCALAR_dofs(), libMesh::XdrIO::write_serialized_bc_names(), libMesh::XdrIO::write_serialized_bcs_helper(), libMesh::System::write_serialized_blocked_dof_objects(), libMesh::XdrIO::write_serialized_connectivity(), libMesh::System::write_serialized_data(), libMesh::XdrIO::write_serialized_nodes(), libMesh::XdrIO::write_serialized_nodesets(), libMesh::XdrIO::write_serialized_subdomain_names(), libMesh::System::write_serialized_vector(), libMesh::System::write_serialized_vectors(), libMesh::Nemesis_IO_Helper::write_sidesets(), libMesh::ExodusII_IO_Helper::write_sidesets(), write_timestep(), libMesh::ExodusII_IO_Helper::write_timestep(), and write_timestep_discontinuous().
   { return cast_int<processor_id_type>(_communicator.rank()); }
read()
void libMesh::ExodusII_IO::read (const std::string & name) override virtual
This method implements reading a mesh from a specified file. Open the file named name and read the mesh in Sandia National Lab's ExodusII format. This is the method to use for reading in meshes generated by cubit. Works in 2D for TRIs, TRI6s, QUAD s, and QUAD9s. Works in 3D for TET4s, TET10s, HEX8s, and HEX27s.
Implements libMesh::MeshInput< MeshBase >.
Definition at line 140 of file exodusII_io.C.
References libMesh::MeshBase::add_elem(), libMesh::BoundaryInfo::add_node(), libMesh::MeshBase::add_point(), libMesh::BoundaryInfo::add_shellface(), libMesh::BoundaryInfo::add_side(), libMesh::ExodusII_IO_Helper::ElementMaps::assign_conversion(), libMesh::Elem::build(), libMesh::MeshBase::clear(), libMesh::Elem::dim(), libMesh::MeshBase::elem_ref(), libMesh::MeshInput< MeshBase >::elems_of_dimension, libMesh::Utility::enum_to_string(), exio_helper, libMesh::MeshBase::get_boundary_info(), libMesh::ExodusII_IO_Helper::Conversion::get_shellface_index_offset(), libMesh::ExodusII_IO_Helper::Conversion::get_side_map(), libMesh::DofObject::id(), libMesh::index_range(), libMesh::ExodusII_IO_Helper::Conversion::invalid_id, libMesh::MeshInput< MT >::mesh(), libMesh::MeshInput< MeshBase >::mesh(), libMesh::MeshBase::mesh_dimension(), libMesh::MeshBase::node_ptr(), libMesh::BoundaryInfo::nodeset_name(), libMesh::MeshBase::reserve_elem(), libMesh::MeshBase::reserve_nodes(), libMesh::DofObject::set_id(), libMesh::MeshBase::set_mesh_dimension(), libMesh::Elem::set_node(), libMesh::BoundaryInfo::sideset_name(), libMesh::Elem::subdomain_id(), and libMesh::MeshBase::subdomain_name().
Referenced by libMesh::NameBasedIO::read(), and libMesh::Nemesis_IO::read().
 {
   // Get a reference to the mesh we are reading
   MeshBase & mesh = MeshInput<MeshBase>::mesh();
   // Clear any existing mesh data
   mesh.clear();
   // Keep track of what kinds of elements this file contains
   elems_of_dimension.clear();
   elems_of_dimension.resize(4, false);
   // Instantiate the ElementMaps interface
   ExodusII_IO_Helper::ElementMaps em;
   // Open the exodus file in EX_READ mode
   exio_helper->open(fname.c_str(), /*read_only=*/true);
   // Get header information from exodus file
   exio_helper->read_header();
   // Read the QA records
   exio_helper->read_qa_records();
   // Print header information
   exio_helper->print_header();
   // Read nodes from the exodus file
   exio_helper->read_nodes();
   // Reserve space for the nodes.
   mesh.reserve_nodes(exio_helper->num_nodes);
   // Read the node number map from the Exodus file.  This is
   // required if we want to preserve the numbering of nodes as it
   // exists in the Exodus file.  If the Exodus file does not contain
   // a node_num_map, the identity map is returned by this call.
   exio_helper->read_node_num_map();
   // Loop over the nodes, create Nodes with local processor_id 0.
   for (int i=0; i<exio_helper->num_nodes; i++)
     {
       // Use the node_num_map to get the correct ID for Exodus
       int exodus_id = exio_helper->node_num_map[i];
       // Catch the node that was added to the mesh
       Node * added_node = mesh.add_point (Point(exio_helper->x[i], exio_helper->y[i], exio_helper->z[i]), exodus_id-1);
       // If the Mesh assigned an ID different from what is in the
       // Exodus file, we should probably error.
       if (added_node->id() != static_cast<unsigned>(exodus_id-1))
         libmesh_error_msg("Error!  Mesh assigned node ID "    \
                           << added_node->id()                         \
                           << " which is different from the (zero-based) Exodus ID " \
                           << exodus_id-1                              \
                           << "!");
     }
   // This assert is no longer valid if the nodes are not numbered
   // sequentially starting from 1 in the Exodus file.
   // libmesh_assert_equal_to (static_cast<unsigned int>(exio_helper->num_nodes), mesh.n_nodes());
   // Get information about all the blocks
   exio_helper->read_block_info();
   // Reserve space for the elements
   mesh.reserve_elem(exio_helper->num_elem);
   // Read the element number map from the Exodus file.  This is
   // required if we want to preserve the numbering of elements as it
   // exists in the Exodus file.  If the Exodus file does not contain
   // an elem_num_map, the identity map is returned by this call.
   exio_helper->read_elem_num_map();
   // Read in the element connectivity for each block.
   int nelem_last_block = 0;
   // Loop over all the blocks
   for (int i=0; i<exio_helper->num_elem_blk; i++)
     {
       // Read the information for block i
       exio_helper->read_elem_in_block (i);
       int subdomain_id = exio_helper->get_block_id(i);
       // populate the map of names
       std::string subdomain_name = exio_helper->get_block_name(i);
       if (!subdomain_name.empty())
         mesh.subdomain_name(static_cast<subdomain_id_type>(subdomain_id)) = subdomain_name;
       // Set any relevant node/edge maps for this element
       const std::string type_str (exio_helper->get_elem_type());
       const ExodusII_IO_Helper::Conversion conv = em.assign_conversion(type_str);
       // Loop over all the faces in this block
       int jmax = nelem_last_block+exio_helper->num_elem_this_blk;
       for (int j=nelem_last_block; j<jmax; j++)
         {
           Elem * elem = Elem::build (conv.get_canonical_type()).release();
           libmesh_assert (elem);
           elem->subdomain_id() = static_cast<subdomain_id_type>(subdomain_id) ;
           // Use the elem_num_map to obtain the ID of this element in the Exodus file
           int exodus_id = exio_helper->elem_num_map[j];
           // Assign this element the same ID it had in the Exodus
           // file, but make it zero-based by subtracting 1.  Note:
           // some day we could use 1-based numbering in libmesh and
           // thus match the Exodus numbering exactly, but at the
           // moment libmesh is zero-based.
           elem->set_id(exodus_id-1);
           // Record that we have seen an element of dimension elem->dim()
           elems_of_dimension[elem->dim()] = true;
           // Catch the Elem pointer that the Mesh throws back
           elem = mesh.add_elem (elem);
           // If the Mesh assigned an ID different from what is in the
           // Exodus file, we should probably error.
           if (elem->id() != static_cast<unsigned>(exodus_id-1))
             libmesh_error_msg("Error!  Mesh assigned ID "       \
                               << elem->id()                             \
                               << " which is different from the (zero-based) Exodus ID " \
                               << exodus_id-1                            \
                               << "!");
           // Set all the nodes for this element
           for (int k=0; k<exio_helper->num_nodes_per_elem; k++)
             {
               // global index
               int gi = (j-nelem_last_block)*exio_helper->num_nodes_per_elem + conv.get_node_map(k);
               // The entries in 'connect' are actually (1-based)
               // indices into the node_num_map, so to get the right
               // node ID we:
               // 1.) Subtract 1 from connect[gi]
               // 2.) Pass it through node_num_map to get the corresponding Exodus ID
               // 3.) Subtract 1 from that, since libmesh node numbering is "zero"-based,
               //     even when the Exodus node numbering doesn't start with 1.
               int libmesh_node_id = exio_helper->node_num_map[exio_helper->connect[gi] - 1] - 1;
               // Set the node pointer in the Elem
               elem->set_node(k) = mesh.node_ptr(libmesh_node_id);
             }
         }
       // running sum of # of elements per block,
       // (should equal total number of elements in the end)
       nelem_last_block += exio_helper->num_elem_this_blk;
     }
   // This assert isn't valid if the Exodus file's numbering doesn't
   // start with 1!  For example, if Exodus's elem_num_map is 21, 22,
   // 23, 24, 25, 26, 27, 28, 29, 30, ... 84, then by the time you are
   // done with the loop above, mesh.n_elem() will report 84 and
   // nelem_last_block will be 64.
   // libmesh_assert_equal_to (static_cast<unsigned>(nelem_last_block), mesh.n_elem());
   // Set the mesh dimension to the largest encountered for an element
   for (unsigned char i=0; i!=4; ++i)
     if (elems_of_dimension[i])
       mesh.set_mesh_dimension(i);
   // Read in sideset information -- this is useful for applying boundary conditions
   {
     // Get basic information about all sidesets
     exio_helper->read_sideset_info();
     int offset=0;
     for (int i=0; i<exio_helper->num_side_sets; i++)
       {
         // Compute new offset
         offset += (i > 0 ? exio_helper->num_sides_per_set[i-1] : 0);
         exio_helper->read_sideset (i, offset);
         std::string sideset_name = exio_helper->get_side_set_name(i);
         if (!sideset_name.empty())
           mesh.get_boundary_info().sideset_name
             (cast_int<boundary_id_type>(exio_helper->get_side_set_id(i)))
             = sideset_name;
       }
     for (auto e : index_range(exio_helper->elem_list))
       {
         // The numbers in the Exodus file sidesets should be thought
         // of as (1-based) indices into the elem_num_map array.  So,
         // to get the right element ID we have to:
         // 1.) Subtract 1 from elem_list[e] (to get a zero-based index)
         // 2.) Pass it through elem_num_map (to get the corresponding Exodus ID)
         // 3.) Subtract 1 from that, since libmesh is "zero"-based,
         //     even when the Exodus numbering doesn't start with 1.
         dof_id_type libmesh_elem_id =
           cast_int<dof_id_type>(exio_helper->elem_num_map[exio_helper->elem_list[e] - 1] - 1);
         // Set any relevant node/edge maps for this element
         Elem & elem = mesh.elem_ref(libmesh_elem_id);
         const ExodusII_IO_Helper::Conversion conv = em.assign_conversion(elem.type());
         // Map the zero-based Exodus side numbering to the libmesh side numbering
         unsigned int raw_side_index = exio_helper->side_list[e]-1;
         std::size_t side_index_offset = conv.get_shellface_index_offset();
         if (raw_side_index < side_index_offset)
           {
             // We assume this is a "shell face"
             int mapped_shellface = raw_side_index;
             // Check for errors
             if (mapped_shellface == ExodusII_IO_Helper::Conversion::invalid_id)
               libmesh_error_msg("Invalid 1-based side id: "                 \
                                 << mapped_shellface                         \
                                 << " detected for "                         \
                                 << Utility::enum_to_string(elem.type()));
             // Add this (elem,shellface,id) triplet to the BoundaryInfo object.
             mesh.get_boundary_info().add_shellface (libmesh_elem_id,
                                                     cast_int<unsigned short>(mapped_shellface),
                                                     cast_int<boundary_id_type>(exio_helper->id_list[e]));
           }
         else
           {
             unsigned int side_index = static_cast<unsigned int>(raw_side_index - side_index_offset);
             int mapped_side = conv.get_side_map(side_index);
             // Check for errors
             if (mapped_side == ExodusII_IO_Helper::Conversion::invalid_id)
               libmesh_error_msg("Invalid 1-based side id: "                 \
                                 << side_index                               \
                                 << " detected for "                         \
                                 << Utility::enum_to_string(elem.type()));
             // Add this (elem,side,id) triplet to the BoundaryInfo object.
             mesh.get_boundary_info().add_side (libmesh_elem_id,
                                                cast_int<unsigned short>(mapped_side),
                                                cast_int<boundary_id_type>(exio_helper->id_list[e]));
           }
       }
   }
   // Read nodeset info
   {
     exio_helper->read_nodeset_info();
     for (int nodeset=0; nodeset<exio_helper->num_node_sets; nodeset++)
       {
         boundary_id_type nodeset_id =
           cast_int<boundary_id_type>(exio_helper->nodeset_ids[nodeset]);
         std::string nodeset_name = exio_helper->get_node_set_name(nodeset);
         if (!nodeset_name.empty())
           mesh.get_boundary_info().nodeset_name(nodeset_id) = nodeset_name;
         exio_helper->read_nodeset(nodeset);
         for (const auto & exodus_id : exio_helper->node_list)
           {
             // As before, the entries in 'node_list' are 1-based
             // indices into the node_num_map array, so we have to map
             // them.  See comment above.
             int libmesh_node_id = exio_helper->node_num_map[exodus_id - 1] - 1;
             mesh.get_boundary_info().add_node(cast_int<dof_id_type>(libmesh_node_id),
                                               nodeset_id);
           }
       }
   }
 #if LIBMESH_DIM < 3
   if (mesh.mesh_dimension() > LIBMESH_DIM)
     libmesh_error_msg("Cannot open dimension "        \
                       << mesh.mesh_dimension()            \
                       << " mesh file when configured without "        \
                       << mesh.mesh_dimension()                        \
                       << "D support.");
 #endif
 }
read_elemental_variable()
void libMesh::ExodusII_IO::read_elemental_variable (std::string elemental_var_name, unsigned int timestep, std::map< unsigned int, Real > & unique_id_to_value_map)
Given an elemental variable and a time step, returns a mapping from the elements (top parent) unique IDs to the value of the elemental variable at the corresponding time step index. Note that this function MUST only be called before renumbering! This function is essentially a wrapper for read_elemental_var_values from the exodus helper (which is not accessible outside this class).
Parameters
elemental_var_name Name of an elemental variable
timestep The corresponding time step index
unique_id_to_value_map The map to be filled
Definition at line 555 of file exodusII_io.C.
References exio_helper, libMesh::MeshInput< MT >::mesh(), libMesh::Elem::top_parent(), and libMesh::DofObject::unique_id().
 {
   // Note that this function MUST be called before renumbering
   std::map<dof_id_type, Real> elem_var_value_map;
   exio_helper->read_elemental_var_values(elemental_var_name, timestep, elem_var_value_map);
   for (auto & pr : elem_var_value_map)
     {
       const Elem * elem = MeshInput<MeshBase>::mesh().query_elem_ptr(pr.first);
       unique_id_to_value_map.insert(std::make_pair(elem->top_parent()->unique_id(), pr.second));
     }
 }
read_global_variable()
void libMesh::ExodusII_IO::read_global_variable (std::vector< std::string > global_var_names, unsigned int timestep, std::vector< Real > & global_values)
Given a vector of global variables and a time step, returns the values of the global variable at the corresponding time step index.
Parameters
global_var_names Vector of names of global variables
timestep The corresponding time step index
global_values The vector to be filled
Definition at line 570 of file exodusII_io.C.
References exio_helper, and libMesh::ExodusII_IO_Helper::GLOBAL.
 {
   std::size_t size = global_var_names.size();
   if (size == 0)
     libmesh_error_msg("ERROR, empty list of global variables to read from the Exodus file.");
   // read the values for all global variables
   std::vector<Real> values_from_exodus;
   exio_helper->read_var_names(ExodusII_IO_Helper::GLOBAL);
   exio_helper->read_global_values(values_from_exodus, timestep);
   std::vector<std::string> global_var_names_exodus = exio_helper->global_var_names;
   global_values.clear();
   for (std::size_t i = 0; i != size; ++i)
     {
       // for each global variable in global_var_names, look the corresponding one in global_var_names_from_exodus
       // and fill global_values accordingly
       auto it = find(global_var_names_exodus.begin(), global_var_names_exodus.end(), global_var_names[i]);
       if (it != global_var_names_exodus.end())
         global_values.push_back(values_from_exodus[it - global_var_names_exodus.begin()]);
       else
         libmesh_error_msg("ERROR, Global variable " << global_var_names[i] << \
                           " not found in Exodus file.");
     }
 }
set_coordinate_offset()
void libMesh::ExodusII_IO::set_coordinate_offset (Point p)
Allows you to set a vector that is added to the coordinates of all of the nodes. Effectively, this "moves" the mesh to a particular position.
Deprecated:
As requested by Roy in libmesh PR #90, this function was "deprecated on arrival". There is not really a suitable replacement for it in the works, however. The same effect could be achieved by calling MeshTools::Modification::translate() twice, but that approach seems inefficient in the case of very large problems with millions of nodes. That said, this should probably become a base class API so that it works for all the different IO subclasses.
Definition at line 442 of file exodusII_io.C.
References exio_helper.
 {
   libmesh_warning("This method may be deprecated in the future");
   exio_helper->set_coordinate_offset(p);
 }
set_n_partitions()
void libMesh::MeshInput< MeshBase >::set_n_partitions (unsigned int n_parts) inline protected inherited
Sets the number of partitions in the mesh. Typically this gets done by the partitioner, but some parallel file formats begin "pre-partitioned".
Definition at line 91 of file mesh_input.h.
References libMesh::MeshInput< MT >::mesh().
Referenced by libMesh::Nemesis_IO::read(), and libMesh::XdrIO::read_header().
 { this->mesh().set_n_partitions() = n_parts; }
set_output_variables()
void libMesh::ExodusII_IO::set_output_variables (const std::vector< std::string > & output_variables, bool allow_empty = true)
Sets the list of variable names to be included in the output. This is optional. If this is never called then all variables will be present. If this is called and an empty vector is supplied no variables will be output. Setting the allow_empty = false will result in empty vectors supplied here to also be populated with all variables.
Definition at line 68 of file exodusII_io.C.
References _allow_empty_variables, and _output_variables.
 {
   _output_variables = output_variables;
   _allow_empty_variables = allow_empty;
 }
skip_comment_lines()
void libMesh::MeshInput< MeshBase >::skip_comment_lines (std::istream & in, const char comment_start) protected inherited
Reads input from in, skipping all the lines that start with the character comment_start.
Definition at line 179 of file mesh_input.h.
Referenced by libMesh::TetGenIO::read(), and libMesh::UCDIO::read_implementation().
 {
   char c, line[256];
   while (in.get(c), c==comment_start)
     in.getline (line, 255);
   // put back first character of
   // first non-comment line
   in.putback (c);
 }
use_mesh_dimension_instead_of_spatial_dimension()
void libMesh::ExodusII_IO::use_mesh_dimension_instead_of_spatial_dimension (bool val)
In the general case, meshes containing 2D elements can be manifolds living in 3D space, thus by default we write all meshes with the Exodus dimension set to LIBMESH_DIM = mesh.spatial_dimension().
In certain cases, however, the user may know his 2D mesh actually lives in the z=0 plane, and therefore wants to write a truly 2D Exodus mesh. In such a case, he should call this function with val=true.
Definition at line 428 of file exodusII_io.C.
References exio_helper.
 {
   exio_helper->use_mesh_dimension_instead_of_spatial_dimension(val);
 }
verbose()
void libMesh::ExodusII_IO::verbose (bool set_verbosity)
Set the flag indicating if we should be verbose.
Definition at line 418 of file exodusII_io.C.
References _verbose, and exio_helper.
 {
   _verbose = set_verbosity;
   // Set the verbose flag in the helper object as well.
   exio_helper->verbose = _verbose;
 }
write()
void libMesh::ExodusII_IO::write (const std::string & fname) override virtual
This method implements writing a mesh to a specified file.
Implements libMesh::MeshOutput< MeshBase >.
Definition at line 879 of file exodusII_io.C.
References _append, _verbose, exio_helper, libMesh::MeshBase::get_boundary_info(), libMesh::MeshInput< MeshBase >::mesh(), libMesh::MeshOutput< MT >::mesh(), and libMesh::BoundaryInfo::n_edge_conds().
Referenced by libMesh::ErrorVector::plot_error(), and libMesh::NameBasedIO::write().
 {
   const MeshBase & mesh = MeshOutput<MeshBase>::mesh();
   // We may need to gather a DistributedMesh to output it, making that
   // const qualifier in our constructor a dirty lie
   // The "true" specifies that we only need the mesh serialized to processor 0
   MeshSerializer serialize(MeshInput<MeshBase>::mesh(), !MeshOutput<MeshBase>::_is_parallel_format, true);
   libmesh_assert( !exio_helper->opened_for_writing );
   // If the user has set the append flag here, it doesn't really make
   // sense: the intent of this function is to write a Mesh with no
   // data, while "appending" is really intended to add data to an
   // existing file.  If we're verbose, print a message to this effect.
   if (_append && _verbose)
     libmesh_warning("Warning: Appending in ExodusII_IO::write() does not make sense.\n"
                     "Creating a new file instead!");
   exio_helper->create(fname);
   exio_helper->initialize(fname,mesh);
   exio_helper->write_nodal_coordinates(mesh);
   exio_helper->write_elements(mesh);
   exio_helper->write_sidesets(mesh);
   exio_helper->write_nodesets(mesh);
   if ((mesh.get_boundary_info().n_edge_conds() > 0) && _verbose)
     libmesh_warning("Warning: Mesh contains edge boundary IDs, but these "
                     "are not supported by the ExodusII format.");
 }
write_as_dimension()
void libMesh::ExodusII_IO::write_as_dimension (unsigned dim)
Directly control the num_dim which is written to the Exodus file. If non-zero, this value supersedes all other dimensions, including: 1.) MeshBase::spatial_dimension() 2.) MeshBase::mesh_dimension() 3.) Any value passed to use_mesh_dimension_instead_of_spatial_dimension() This is useful/necessary for working around a bug in Paraview which prevents the "Plot Over Line" filter from working on 1D meshes.
Definition at line 435 of file exodusII_io.C.
References exio_helper.
 {
   exio_helper->write_as_dimension(dim);
 }
write_discontinuous_equation_systems()
void libMesh::MeshOutput< MeshBase >::write_discontinuous_equation_systems (const std::string & fname, const EquationSystems & es, const std::set< std::string > * system_names = nullptr) virtual inherited
This method implements writing a mesh with discontinuous data to a specified file where the data is taken from the EquationSystems object.
Definition at line 92 of file mesh_output.C.
References libMesh::EquationSystems::build_discontinuous_solution_vector(), libMesh::EquationSystems::build_variable_names(), libMesh::EquationSystems::get_mesh(), and libMesh::out.
Referenced by write_timestep_discontinuous().
 {
   LOG_SCOPE("write_discontinuous_equation_systems()", "MeshOutput");
   // We may need to gather and/or renumber a DistributedMesh to output
   // it, making that const qualifier in our constructor a dirty lie
   MT & my_mesh = const_cast<MT &>(*_obj);
   // If we're asked to write data that's associated with a different
   // mesh, output files full of garbage are the result.
   libmesh_assert_equal_to(&es.get_mesh(), _obj);
   // A non-renumbered mesh may not have a contiguous numbering, and
   // that needs to be fixed before we can build a solution vector.
   if (my_mesh.max_elem_id() != my_mesh.n_elem() ||
       my_mesh.max_node_id() != my_mesh.n_nodes())
     {
       // If we were allowed to renumber then we should have already
       // been properly renumbered...
       libmesh_assert(!my_mesh.allow_renumbering());
       libmesh_do_once(libMesh::out <<
                       "Warning:  This MeshOutput subclass only supports meshes which are contiguously renumbered!"
                       << std::endl;);
       my_mesh.allow_renumbering(true);
       my_mesh.renumber_nodes_and_elements();
       // Not sure what good going back to false will do here, the
       // renumbering horses have already left the barn...
       my_mesh.allow_renumbering(false);
     }
   MeshSerializer serialize(const_cast<MT &>(*_obj), !_is_parallel_format, _serial_only_needed_on_proc_0);
   // Build the list of variable names that will be written.
   std::vector<std::string> names;
   es.build_variable_names  (names, nullptr, system_names);
   if (!_is_parallel_format)
     {
       // Build the nodal solution values & get the variable
       // names from the EquationSystems object
       std::vector<Number> soln;
       es.build_discontinuous_solution_vector (soln, system_names);
       this->write_nodal_data_discontinuous (fname, soln, names);
     }
   else // _is_parallel_format
     {
       libmesh_not_implemented();
     }
 }
write_discontinuous_exodusII()
void libMesh::ExodusII_IO::write_discontinuous_exodusII (const std::string & name, const EquationSystems & es, const std::set< std::string > * system_names = nullptr)
Writes a exodusII file with discontinuous data
Definition at line 89 of file exodusII_io.C.
References libMesh::EquationSystems::build_discontinuous_solution_vector(), libMesh::EquationSystems::build_variable_names(), and write_nodal_data_discontinuous().
 {
   std::vector<std::string> solution_names;
   std::vector<Number>      v;
   es.build_variable_names  (solution_names, nullptr, system_names);
   es.build_discontinuous_solution_vector (v, system_names);
   this->write_nodal_data_discontinuous(name, v, solution_names);
 }
write_element_data()
void libMesh::ExodusII_IO::write_element_data (const EquationSystems & es)
Write out element solution.
Definition at line 599 of file exodusII_io.C.
References _output_variables, _timestep, std::abs(), libMesh::EquationSystems::build_elemental_solution_vector(), libMesh::EquationSystems::build_variable_names(), libMesh::CONSTANT, exio_helper, libMesh::EquationSystems::get_vars_active_subdomains(), libMesh::MeshInput< MeshBase >::mesh(), libMesh::MeshOutput< MT >::mesh(), libMesh::MONOMIAL, libMesh::ParallelObject::processor_id(), and value.
Referenced by libMesh::ErrorVector::plot_error().
 {
   // Be sure the file has been opened for writing!
   if (MeshOutput<MeshBase>::mesh().processor_id() == 0 && !exio_helper->opened_for_writing)
     libmesh_error_msg("ERROR, ExodusII file must be initialized before outputting element variables.");
   // This function currently only works on serialized meshes. We rely
   // on having a reference to a non-const MeshBase object from our
   // MeshInput parent class to construct a MeshSerializer object,
   // similar to what is done in ExodusII_IO::write().  Note that
   // calling ExodusII_IO::write_timestep() followed by
   // ExodusII_IO::write_element_data() when the underlying Mesh is a
   // DistributedMesh will result in an unnecessary additional
   // serialization/re-parallelization step.
   // The "true" specifies that we only need the mesh serialized to processor 0
   MeshSerializer serialize(MeshInput<MeshBase>::mesh(), !MeshOutput<MeshBase>::_is_parallel_format, true);
   // To be (possibly) filled with a filtered list of variable names to output.
   std::vector<std::string> names;
   // If _output_variables is populated, only output the monomials which are
   // also in the _output_variables vector.
   if (_output_variables.size() > 0)
     {
       std::vector<std::string> monomials;
       const FEType type(CONSTANT, MONOMIAL);
       // Create a list of monomial variable names
       es.build_variable_names(monomials, &type);
       // Filter that list against the _output_variables list.  Note: if names is still empty after
       // all this filtering, all the monomial variables will be gathered
       for (const auto & var : monomials)
         if (std::find(_output_variables.begin(), _output_variables.end(), var) != _output_variables.end())
           names.push_back(var);
     }
   // If we pass in a list of names to "get_solution" it'll filter the variables coming back
   std::vector<Number> soln;
   es.build_elemental_solution_vector(soln, names);
   // Also, store the list of subdomains on which each variable is active
   std::vector<std::set<subdomain_id_type>> vars_active_subdomains;
   es.get_vars_active_subdomains(names, vars_active_subdomains);
   if (soln.empty()) // If there is nothing to write just return
     return;
   // The data must ultimately be written block by block.  This means that this data
   // must be sorted appropriately.
   if (MeshOutput<MeshBase>::mesh().processor_id())
     return;
   const MeshBase & mesh = MeshOutput<MeshBase>::mesh();
 #ifdef LIBMESH_USE_COMPLEX_NUMBERS
   std::vector<std::string> complex_names = exio_helper->get_complex_names(names);
   std::vector<std::set<subdomain_id_type>> complex_vars_active_subdomains =
     exio_helper->get_complex_vars_active_subdomains(vars_active_subdomains);
   exio_helper->initialize_element_variables(complex_names, complex_vars_active_subdomains);
   unsigned int num_values = soln.size();
   unsigned int num_vars = names.size();
   unsigned int num_elems = num_values / num_vars;
   // This will contain the real and imaginary parts and the magnitude
   // of the values in soln
   std::vector<Real> complex_soln(3*num_values);
   for (unsigned i=0; i<num_vars; ++i)
     {
       for (unsigned int j=0; j<num_elems; ++j)
         {
           Number value = soln[i*num_vars + j];
           complex_soln[3*i*num_elems + j] = value.real();
         }
       for (unsigned int j=0; j<num_elems; ++j)
         {
           Number value = soln[i*num_vars + j];
           complex_soln[3*i*num_elems + num_elems +j] = value.imag();
         }
       for (unsigned int j=0; j<num_elems; ++j)
         {
           Number value = soln[i*num_vars + j];
           complex_soln[3*i*num_elems + 2*num_elems + j] = std::abs(value);
         }
     }
   exio_helper->write_element_values(mesh, complex_soln, _timestep, complex_vars_active_subdomains);
 #else
   exio_helper->initialize_element_variables(names, vars_active_subdomains);
   exio_helper->write_element_values(mesh, soln, _timestep, vars_active_subdomains);
 #endif
 }
write_equation_systems()
void libMesh::MeshOutput< MeshBase >::write_equation_systems (const std::string & fname, const EquationSystems & es, const std::set< std::string > * system_names = nullptr) virtual inherited
This method implements writing a mesh with data to a specified file where the data is taken from the EquationSystems object.
Reimplemented in libMesh::NameBasedIO.
Definition at line 31 of file mesh_output.C.
References libMesh::EquationSystems::build_parallel_solution_vector(), libMesh::EquationSystems::build_solution_vector(), libMesh::EquationSystems::build_variable_names(), libMesh::EquationSystems::get_mesh(), and libMesh::out.
Referenced by libMesh::Nemesis_IO::write_timestep(), and write_timestep().
 {
   LOG_SCOPE("write_equation_systems()", "MeshOutput");
   // We may need to gather and/or renumber a DistributedMesh to output
   // it, making that const qualifier in our constructor a dirty lie
   MT & my_mesh = const_cast<MT &>(*_obj);
   // If we're asked to write data that's associated with a different
   // mesh, output files full of garbage are the result.
   libmesh_assert_equal_to(&es.get_mesh(), _obj);
   // A non-renumbered mesh may not have a contiguous numbering, and
   // that needs to be fixed before we can build a solution vector.
   if (my_mesh.max_elem_id() != my_mesh.n_elem() ||
       my_mesh.max_node_id() != my_mesh.n_nodes())
     {
       // If we were allowed to renumber then we should have already
       // been properly renumbered...
       libmesh_assert(!my_mesh.allow_renumbering());
       libmesh_do_once(libMesh::out <<
                       "Warning:  This MeshOutput subclass only supports meshes which are contiguously renumbered!"
                       << std::endl;);
       my_mesh.allow_renumbering(true);
       my_mesh.renumber_nodes_and_elements();
       // Not sure what good going back to false will do here, the
       // renumbering horses have already left the barn...
       my_mesh.allow_renumbering(false);
     }
   MeshSerializer serialize(const_cast<MT &>(*_obj), !_is_parallel_format, _serial_only_needed_on_proc_0);
   // Build the list of variable names that will be written.
   std::vector<std::string> names;
   es.build_variable_names  (names, nullptr, system_names);
   if (!_is_parallel_format)
     {
       // Build the nodal solution values & get the variable
       // names from the EquationSystems object
       std::vector<Number> soln;
       es.build_solution_vector (soln, system_names);
       this->write_nodal_data (fname, soln, names);
     }
   else // _is_parallel_format
     {
       std::unique_ptr<NumericVector<Number>> parallel_soln =
         es.build_parallel_solution_vector(system_names);
       this->write_nodal_data (fname, *parallel_soln, names);
     }
 }
write_global_data()
void libMesh::ExodusII_IO::write_global_data (const std::vector< Number > & soln, const std::vector< std::string > & names)
Write out global variables.
Definition at line 809 of file exodusII_io.C.
References _timestep, std::abs(), exio_helper, libMesh::ParallelObject::processor_id(), and value.
 {
   if (MeshOutput<MeshBase>::mesh().processor_id())
     return;
   if (!exio_helper->opened_for_writing)
     libmesh_error_msg("ERROR, ExodusII file must be initialized before outputting global variables.");
 #ifdef LIBMESH_USE_COMPLEX_NUMBERS
   std::vector<std::string> complex_names = exio_helper->get_complex_names(names);
   exio_helper->initialize_global_variables(complex_names);
   unsigned int num_values = soln.size();
   unsigned int num_vars = names.size();
   unsigned int num_elems = num_values / num_vars;
   // This will contain the real and imaginary parts and the magnitude
   // of the values in soln
   std::vector<Real> complex_soln(3*num_values);
   for (unsigned i=0; i<num_vars; ++i)
     {
       for (unsigned int j=0; j<num_elems; ++j)
         {
           Number value = soln[i*num_vars + j];
           complex_soln[3*i*num_elems + j] = value.real();
         }
       for (unsigned int j=0; j<num_elems; ++j)
         {
           Number value = soln[i*num_vars + j];
           complex_soln[3*i*num_elems + num_elems +j] = value.imag();
         }
       for (unsigned int j=0; j<num_elems; ++j)
         {
           Number value = soln[i*num_vars + j];
           complex_soln[3*i*num_elems + 2*num_elems + j] = std::abs(value);
         }
     }
   exio_helper->write_global_values(complex_soln, _timestep);
 #else
   exio_helper->initialize_global_variables(names);
   exio_helper->write_global_values(soln, _timestep);
 #endif
 }
write_information_records()
void libMesh::ExodusII_IO::write_information_records (const std::vector< std::string > & records)
Write out information records.
Definition at line 796 of file exodusII_io.C.
References exio_helper, and libMesh::ParallelObject::processor_id().
 {
   if (MeshOutput<MeshBase>::mesh().processor_id())
     return;
   if (!exio_helper->opened_for_writing)
     libmesh_error_msg("ERROR, ExodusII file must be initialized before outputting information records.");
   exio_helper->write_information_records(records);
 }
write_nodal_data() [1/2]
void libMesh::MeshOutput< MeshBase >::write_nodal_data (const std::string & fname, const NumericVector< Number > & parallel_soln, const std::vector< std::string > & names) virtual inherited
This method should be overridden by "parallel" output formats for writing nodal data. Instead of getting a localized copy of the nodal solution vector, it is passed a NumericVector of type=PARALLEL which is in node-major order i.e. (u0,v0,w0, u1,v1,w1, u2,v2,w2, u3,v3,w3, ...) and contains n_nodes*n_vars total entries. Then, it is up to the individual I/O class to extract the required solution values from this vector and write them in parallel.
If not implemented, localizes the parallel vector into a std::vector and calls the other version of this function.
Reimplemented in libMesh::Nemesis_IO.
Definition at line 150 of file mesh_output.C.
References libMesh::NumericVector< T >::localize().
 {
   // This is the fallback implementation for parallel I/O formats that
   // do not yet implement proper writing in parallel, and instead rely
   // on the full solution vector being available on all processors.
   std::vector<Number> soln;
   parallel_soln.localize(soln);
   this->write_nodal_data(fname, soln, names);
 }
write_nodal_data() [2/2]
void libMesh::ExodusII_IO::write_nodal_data (const std::string & fname, const std::vector< Number > & soln, const std::vector< std::string > & names) override virtual
Write out a nodal solution.
Reimplemented from libMesh::MeshOutput< MeshBase >.
Definition at line 700 of file exodusII_io.C.
References _allow_empty_variables, _output_variables, _timestep, std::abs(), exio_helper, libMesh::MeshTools::Generation::Private::idx(), libMesh::MeshInput< MeshBase >::mesh(), libMesh::MeshOutput< MT >::mesh(), libMesh::MeshBase::n_nodes(), libMesh::MeshBase::node_ptr_range(), libMesh::ParallelObject::processor_id(), and write_nodal_data_common().
Referenced by libMesh::NameBasedIO::write_nodal_data().
 {
   LOG_SCOPE("write_nodal_data()", "ExodusII_IO");
   const MeshBase & mesh = MeshOutput<MeshBase>::mesh();
   int num_vars = cast_int<int>(names.size());
   dof_id_type num_nodes = mesh.n_nodes();
   // The names of the variables to be output
   std::vector<std::string> output_names;
   if (_allow_empty_variables || !_output_variables.empty())
     output_names = _output_variables;
   else
     output_names = names;
 #ifdef LIBMESH_USE_COMPLEX_NUMBERS
   std::vector<std::string> complex_names = exio_helper->get_complex_names(names);
   // Call helper function for opening/initializing data, giving it the
   // complex variable names
   this->write_nodal_data_common(fname, complex_names, /*continuous=*/true);
 #else
   // Call helper function for opening/initializing data
   this->write_nodal_data_common(fname, output_names, /*continuous=*/true);
 #endif
   if (mesh.processor_id())
     return;
   // This will count the number of variables actually output
   for (int c=0; c<num_vars; c++)
     {
       std::stringstream name_to_find;
       std::vector<std::string>::iterator pos =
         std::find(output_names.begin(), output_names.end(), names[c]);
       if (pos == output_names.end())
         continue;
       unsigned int variable_name_position =
         cast_int<unsigned int>(pos - output_names.begin());
       // Set up temporary vectors to be passed to Exodus to write the
       // nodal values for a single variable at a time.
 #ifdef LIBMESH_USE_REAL_NUMBERS
       std::vector<Number> cur_soln;
       // num_nodes is either exactly how much space we will need for
       // each vector, or a safe upper bound for the amount of memory
       // we will require when there are gaps in the numbering.
       cur_soln.reserve(num_nodes);
 #else
       std::vector<Real> real_parts;
       std::vector<Real> imag_parts;
       std::vector<Real> magnitudes;
       real_parts.reserve(num_nodes);
       imag_parts.reserve(num_nodes);
       magnitudes.reserve(num_nodes);
 #endif
       // There could be gaps in "soln", but it will always be in the
       // order of [num_vars * node_id + var_id]. We now copy the
       // proper solution values contiguously into "cur_soln",
       // removing the gaps.
       for (const auto & node : mesh.node_ptr_range())
         {
           dof_id_type idx = node->id()*num_vars + c;
 #ifdef LIBMESH_USE_REAL_NUMBERS
           cur_soln.push_back(soln[idx]);
 #else
           real_parts.push_back(soln[idx].real());
           imag_parts.push_back(soln[idx].imag());
           magnitudes.push_back(std::abs(soln[idx]));
 #endif
         }
       // Finally, actually call the Exodus API to write to file.
 #ifdef LIBMESH_USE_REAL_NUMBERS
       exio_helper->write_nodal_values(variable_name_position+1, cur_soln, _timestep);
 #else
       exio_helper->write_nodal_values(3*variable_name_position+1, real_parts, _timestep);
       exio_helper->write_nodal_values(3*variable_name_position+2, imag_parts, _timestep);
       exio_helper->write_nodal_values(3*variable_name_position+3, magnitudes, _timestep);
 #endif
     }
 }
write_nodal_data_common()
void libMesh::ExodusII_IO::write_nodal_data_common (std::string fname, const std::vector< std::string > & names, bool continuous = true)
This function factors out a bunch of code which is common to the write_nodal_data() and write_nodal_data_discontinuous() functions
Definition at line 970 of file exodusII_io.C.
References _append, _verbose, exio_helper, libMesh::MeshBase::get_boundary_info(), libMesh::MeshInput< MeshBase >::mesh(), libMesh::MeshOutput< MT >::mesh(), and libMesh::BoundaryInfo::n_edge_conds().
Referenced by write_nodal_data(), and write_nodal_data_discontinuous().
 {
   const MeshBase & mesh = MeshOutput<MeshBase>::mesh();
   // This function can be called multiple times, we only want to open
   // the ExodusII file the first time it's called.
   if (!exio_helper->opened_for_writing)
     {
       // If we're appending, open() the file with read_only=false,
       // otherwise create() it and write the contents of the mesh to
       // it.
       if (_append)
         {
           exio_helper->open(fname.c_str(), /*read_only=*/false);
           // If we're appending, it's not valid to call exio_helper->initialize()
           // or exio_helper->initialize_nodal_variables(), but we do need to set up
           // certain aspects of the Helper object itself, such as the number of nodes
           // and elements.  We do that by reading the header...
           exio_helper->read_header();
           // ...and reading the block info
           exio_helper->read_block_info();
         }
       else
         {
           exio_helper->create(fname);
           exio_helper->initialize(fname, mesh, !continuous);
           exio_helper->write_nodal_coordinates(mesh, !continuous);
           exio_helper->write_elements(mesh, !continuous);
           exio_helper->write_sidesets(mesh);
           exio_helper->write_nodesets(mesh);
           if ((mesh.get_boundary_info().n_edge_conds() > 0) && _verbose)
             libmesh_warning("Warning: Mesh contains edge boundary IDs, but these "
                             "are not supported by the ExodusII format.");
           exio_helper->initialize_nodal_variables(names);
         }
     }
   else
     {
       // We are already open for writing, so check that the filename
       // passed to this function matches the filename currently in use
       // by the helper.
       if (fname != exio_helper->current_filename)
         libmesh_error_msg("Error! This ExodusII_IO object is already associated with file: " \
                           << exio_helper->current_filename              \
                           << ", cannot use it with requested file: "    \
                           << fname);
     }
 }
write_nodal_data_discontinuous()
void libMesh::ExodusII_IO::write_nodal_data_discontinuous (const std::string & fname, const std::vector< Number > & soln, const std::vector< std::string > & names) override virtual
Write out a discontinuous nodal solution.
Reimplemented from libMesh::MeshOutput< MeshBase >.
Definition at line 912 of file exodusII_io.C.
References _timestep, std::abs(), libMesh::MeshBase::active_element_ptr_range(), exio_helper, libMesh::MeshInput< MeshBase >::mesh(), libMesh::MeshOutput< MT >::mesh(), libMesh::ParallelObject::processor_id(), and write_nodal_data_common().
Referenced by write_discontinuous_exodusII().
 {
   LOG_SCOPE("write_nodal_data_discontinuous()", "ExodusII_IO");
   const MeshBase & mesh = MeshOutput<MeshBase>::mesh();
   int num_vars = cast_int<int>(names.size());
   int num_nodes = 0;
   for (const auto & elem : mesh.active_element_ptr_range())
     num_nodes += elem->n_nodes();
 #ifdef LIBMESH_USE_COMPLEX_NUMBERS
   std::vector<std::string> complex_names = exio_helper->get_complex_names(names);
   // Call helper function for opening/initializing data, giving it the
   // complex variable names
   this->write_nodal_data_common(fname, complex_names, /*continuous=*/false);
 #else
   // Call helper function for opening/initializing data
   this->write_nodal_data_common(fname, names, /*continuous=*/false);
 #endif
   if (mesh.processor_id())
     return;
   for (int c=0; c<num_vars; c++)
     {
 #ifdef LIBMESH_USE_COMPLEX_NUMBERS
       std::vector<Real> real_parts(num_nodes);
       std::vector<Real> imag_parts(num_nodes);
       std::vector<Real> magnitudes(num_nodes);
       for (int i=0; i<num_nodes; ++i)
         {
           real_parts[i] = soln[i*num_vars + c].real();
           imag_parts[i] = soln[i*num_vars + c].imag();
           magnitudes[i] = std::abs(soln[i*num_vars + c]);
         }
       exio_helper->write_nodal_values(3*c+1,real_parts,_timestep);
       exio_helper->write_nodal_values(3*c+2,imag_parts,_timestep);
       exio_helper->write_nodal_values(3*c+3,magnitudes,_timestep);
 #else
       // Copy out this variable's solution
       std::vector<Number> cur_soln(num_nodes);
       for (int i=0; i<num_nodes; i++)
         cur_soln[i] = soln[i*num_vars + c];
       exio_helper->write_nodal_values(c+1,cur_soln,_timestep);
 #endif
     }
 }
write_timestep()
void libMesh::ExodusII_IO::write_timestep (const std::string & fname, const EquationSystems & es, const int timestep, const Real time, const std::set< std::string > * system_names = nullptr)
Writes out the solution at a specific timestep.
Parameters
fname Name of the file to write to
es EquationSystems object which contains the solution vector.
timestep The timestep to write out, should be 1 indexed.
time The current simulation time.
system_names Optional list of systems to write solutions for.
Definition at line 862 of file exodusII_io.C.
References _timestep, exio_helper, libMesh::ParallelObject::processor_id(), and libMesh::MeshOutput< MeshBase >::write_equation_systems().
 {
   _timestep = timestep;
   write_equation_systems(fname,es,system_names);
   if (MeshOutput<MeshBase>::mesh().processor_id())
     return;
   exio_helper->write_timestep(timestep, time);
 }
write_timestep_discontinuous()
void libMesh::ExodusII_IO::write_timestep_discontinuous (const std::string & fname, const EquationSystems & es, const int timestep, const Real time, const std::set< std::string > * system_names = nullptr)
Writes a discontinuous solution at a specific timestep
Parameters
fname Name of the file to be written
es EquationSystems object which contains the solution vector
timestep The timestep to write out. (should be 1 indexed)
time The current simulation time
system_names Optional list of systems to write solutions for.
Definition at line 104 of file exodusII_io.C.
References _timestep, exio_helper, libMesh::ParallelObject::processor_id(), and libMesh::MeshOutput< MeshBase >::write_discontinuous_equation_systems().
 {
   _timestep = timestep;
   write_discontinuous_equation_systems (fname,es,system_names);
   if (MeshOutput<MeshBase>::mesh().processor_id())
     return;
   exio_helper->write_timestep(timestep, time);
 }
Member Data Documentation
_allow_empty_variables
bool libMesh::ExodusII_IO::_allow_empty_variables private
If true, _output_variables is allowed to remain empty. If false, if _output_variables is empty it will be populated with a complete list of all variables By default, calling set_output_variables() sets this flag to true, but it provides an override.
Definition at line 354 of file exodusII_io.h.
Referenced by set_output_variables(), and write_nodal_data().
_append
bool libMesh::ExodusII_IO::_append private
Default false. If true, files will be opened with EX_WRITE rather than created from scratch when writing.
Definition at line 340 of file exodusII_io.h.
Referenced by append(), write(), and write_nodal_data_common().
_communicator
const Parallel::Communicator& libMesh::ParallelObject::_communicator protected inherited
Definition at line 107 of file parallel_object.h.
Referenced by libMesh::EquationSystems::build_parallel_elemental_solution_vector(), libMesh::EquationSystems::build_parallel_solution_vector(), libMesh::ParallelObject::comm(), libMesh::ParallelObject::n_processors(), libMesh::ParallelObject::operator=(), and libMesh::ParallelObject::processor_id().
_is_parallel_format
const bool libMesh::MeshOutput< MeshBase >::_is_parallel_format protected inherited
Flag specifying whether this format is parallel-capable. If this is false (default) I/O is only permitted when the mesh has been serialized.
Definition at line 159 of file mesh_output.h.
Referenced by libMesh::FroIO::write(), libMesh::PostscriptIO::write(), and libMesh::EnsightIO::write().
_output_variables
std::vector<std::string> libMesh::ExodusII_IO::_output_variables private
The names of the variables to be output. If this is empty then all variables are output.
Definition at line 347 of file exodusII_io.h.
Referenced by set_output_variables(), write_element_data(), and write_nodal_data().
_serial_only_needed_on_proc_0
const bool libMesh::MeshOutput< MeshBase >::_serial_only_needed_on_proc_0 protected inherited
Flag specifying whether this format can be written by only serializing the mesh to processor zero
If this is false (default) the mesh will be serialized to all processors
Definition at line 168 of file mesh_output.h.
_timestep
int libMesh::ExodusII_IO::_timestep private
Stores the current value of the timestep when calling ExodusII_IO::write_timestep().
Definition at line 329 of file exodusII_io.h.
Referenced by write_element_data(), write_global_data(), write_nodal_data(), write_nodal_data_discontinuous(), write_timestep(), and write_timestep_discontinuous().
_verbose
bool libMesh::ExodusII_IO::_verbose private
should we be verbose?
Definition at line 334 of file exodusII_io.h.
Referenced by verbose(), write(), and write_nodal_data_common().
elems_of_dimension
std::vector<bool> libMesh::MeshInput< MeshBase >::elems_of_dimension protected inherited
A vector of bools describing what dimension elements have been encountered when reading a mesh.
Definition at line 97 of file mesh_input.h.
Referenced by libMesh::GMVIO::_read_one_cell(), libMesh::UNVIO::elements_in(), libMesh::UNVIO::max_elem_dimension_seen(), libMesh::AbaqusIO::max_elem_dimension_seen(), libMesh::AbaqusIO::read(), libMesh::Nemesis_IO::read(), read(), libMesh::GMVIO::read(), libMesh::VTKIO::read(), libMesh::AbaqusIO::read_elements(), libMesh::UCDIO::read_implementation(), libMesh::UNVIO::read_implementation(), and libMesh::XdrIO::read_serialized_connectivity().
exio_helper
std::unique_ptr<ExodusII_IO_Helper> libMesh::ExodusII_IO::exio_helper private
Only attempt to instantiate an ExodusII helper class if the Exodus API is defined. This class will have no functionality when LIBMESH_HAVE_EXODUS_API is not defined.
Definition at line 323 of file exodusII_io.h.
Referenced by copy_elemental_solution(), copy_nodal_solution(), get_elem_var_names(), get_exio_helper(), get_nodal_var_names(), get_num_time_steps(), get_time_steps(), read(), read_elemental_variable(), read_global_variable(), set_coordinate_offset(), use_mesh_dimension_instead_of_spatial_dimension(), verbose(), write(), write_as_dimension(), write_element_data(), write_global_data(), write_information_records(), write_nodal_data(), write_nodal_data_common(), write_nodal_data_discontinuous(), write_timestep(), write_timestep_discontinuous(), and ~ExodusII_IO().
The documentation for this class was generated from the following files:
exodusII_io.h
exodusII_io.C