libMesh: libMesh::NloptOptimizationSolver< T > Class Template Reference
SomeWebsiteLogo
libMesh::NloptOptimizationSolver< T > Class Template Reference
#include <nlopt_optimization_solver.h>
Public Types
typedef OptimizationSystem sys_type
Public Member Functions
NloptOptimizationSolver (sys_type &system)
~NloptOptimizationSolver ()
virtual void clear () libmesh_override
virtual void init () libmesh_override
nlopt_opt get_nlopt_object ()
virtual void solve () libmesh_override
virtual void print_converged_reason () libmesh_override
virtual int get_converged_reason () libmesh_override
unsigned & get_iteration_count ()
bool initialized () const
virtual void get_dual_variables ()
const sys_type & system () const
sys_type & system ()
const Parallel::Communicator & comm () const
processor_id_type n_processors () const
processor_id_type processor_id () const
Static Public Member Functions
static UniquePtr< OptimizationSolver< T > > build (sys_type &s, const SolverPackage solver_package=libMesh::default_solver_package())
static std::string get_info ()
static void print_info (std::ostream &out=libMesh::out)
static unsigned int n_objects ()
static void enable_print_counter_info ()
static void disable_print_counter_info ()
Public Attributes
OptimizationSystem::ComputeObjective * objective_object
OptimizationSystem::ComputeGradient * gradient_object
OptimizationSystem::ComputeHessian * hessian_object
OptimizationSystem::ComputeEqualityConstraints * equality_constraints_object
OptimizationSystem::ComputeEqualityConstraintsJacobian * equality_constraints_jacobian_object
OptimizationSystem::ComputeInequalityConstraints * inequality_constraints_object
OptimizationSystem::ComputeInequalityConstraintsJacobian * inequality_constraints_jacobian_object
OptimizationSystem::ComputeLowerAndUpperBounds * lower_and_upper_bounds_object
unsigned int max_objective_function_evaluations
Real objective_function_relative_tolerance
bool verbose
Protected Types
typedef std::map< std::string, std::pair< unsigned int, unsigned int > > Counts
Protected Member Functions
void increment_constructor_count (const std::string &name)
void increment_destructor_count (const std::string &name)
Protected Attributes
nlopt_opt _opt
nlopt_result _result
unsigned _iteration_count
double _constraints_tolerance
sys_type & _system
bool _is_initialized
const Parallel::Communicator & _communicator
Static Protected Attributes
static Counts _counts
static Threads::atomic< unsigned int > _n_objects
static Threads::spin_mutex _mutex
static bool _enable_print_counter = true
Static Private Member Functions
static std::map< std::string, nlopt_algorithm > build_map ()
Static Private Attributes
static std::map< std::string, nlopt_algorithm > _nlopt_algorithms = NloptOptimizationSolver<T>::build_map()
Friends
double __libmesh_nlopt_objective (unsigned n, const double *x, double *gradient, void *data)
void __libmesh_nlopt_equality_constraints (unsigned m, double *result, unsigned n, const double *x, double *gradient, void *data)
void __libmesh_nlopt_inequality_constraints (unsigned m, double *result, unsigned n, const double *x, double *gradient, void *data)
Detailed Description
template<typename T>
class libMesh::NloptOptimizationSolver< T >
This class provides an interface to the NLopt optimization solvers. http://ab-initio.mit.edu/wiki/index.php/NLopt
Author
David Knezevic
John Peterson
Date
2015
Definition at line 70 of file nlopt_optimization_solver.h.
Member Typedef Documentation
typedef std::map<std::string, std::pair<unsigned int, unsigned int> > libMesh::ReferenceCounter::Counts protected inherited
Data structure to log the information. The log is identified by the class name.
Definition at line 119 of file reference_counter.h.
template<typename T> typedef OptimizationSystem libMesh::NloptOptimizationSolver< T >::sys_type
The type of system that we use in conjunction with this solver.
Definition at line 77 of file nlopt_optimization_solver.h.
Constructor & Destructor Documentation
template<typename T > libMesh::NloptOptimizationSolver< T >::NloptOptimizationSolver (sys_type & system) explicit
Constructor.
Definition at line 289 of file nlopt_optimization_solver.C.
   :
   OptimizationSolver<T>(system_in),
   _opt(libmesh_nullptr),
   _result(NLOPT_SUCCESS),
   _iteration_count(0),
   _constraints_tolerance(1.e-8)
 {
 }
template<typename T > libMesh::NloptOptimizationSolver< T >::~NloptOptimizationSolver ()
Destructor.
Definition at line 302 of file nlopt_optimization_solver.C.
References libMesh::NloptOptimizationSolver< T >::clear().
 {
   this->clear ();
 }
Member Function Documentation
template<typename T > UniquePtr< OptimizationSolver< T > > libMesh::OptimizationSolver< T >::build (sys_type & s, const SolverPackage solver_package = libMesh::default_solver_package()) static inherited
Builds an OptimizationSolver using the package specified by solver_package
Definition at line 62 of file optimization_solver.C.
References libMesh::libmesh_ignore(), libMesh::NLOPT_SOLVERS, and libMesh::PETSC_SOLVERS.
 {
   // Prevent unused variables warnings when Tao is not available
   libmesh_ignore(s);
   // Build the appropriate solver
   switch (solver_package)
     {
 #if defined(LIBMESH_HAVE_PETSC_TAO) && !defined(LIBMESH_USE_COMPLEX_NUMBERS)
     case PETSC_SOLVERS:
       return UniquePtr<OptimizationSolver<T> >(new TaoOptimizationSolver<T>(s));
 #endif // #if defined(LIBMESH_HAVE_PETSC_TAO) && !defined(LIBMESH_USE_COMPLEX_NUMBERS)
 #if defined(LIBMESH_HAVE_NLOPT) && !defined(LIBMESH_USE_COMPLEX_NUMBERS)
     case NLOPT_SOLVERS:
       return UniquePtr<OptimizationSolver<T> >(new NloptOptimizationSolver<T>(s));
 #endif // #if defined(LIBMESH_HAVE_NLOPT) && !defined(LIBMESH_USE_COMPLEX_NUMBERS)
     default:
       libmesh_error_msg("ERROR:  Unrecognized solver package: " << solver_package);
     }
   libmesh_error_msg("We'll never get here!");
   return UniquePtr<OptimizationSolver<T> >();
 }
template<typename T> static std::map<std::string, nlopt_algorithm> libMesh::NloptOptimizationSolver< T >::build_map () inline static private
Definition at line 182 of file nlopt_optimization_solver.h.
   {
     std::map<std::string, nlopt_algorithm> ret;
     ret["LD_SLSQP"]                   = NLOPT_LD_SLSQP;
     ret["LD_MMA"]                     = NLOPT_LD_MMA;
     ret["LD_CCSAQ"]                   = NLOPT_LD_CCSAQ;
     ret["LD_LBFGS"]                   = NLOPT_LD_LBFGS;
     ret["LD_LBFGS_NOCEDAL"]           = NLOPT_LD_LBFGS_NOCEDAL;
     ret["LD_TNEWTON"]                 = NLOPT_LD_TNEWTON;
     ret["LD_TNEWTON_RESTART"]         = NLOPT_LD_TNEWTON_RESTART;
     ret["LD_TNEWTON_PRECOND"]         = NLOPT_LD_TNEWTON_PRECOND;
     ret["LD_TNEWTON_PRECOND_RESTART"] = NLOPT_LD_TNEWTON_PRECOND_RESTART;
     ret["LD_AUGLAG"]                  = NLOPT_LD_AUGLAG;
     ret["LD_VAR1"]                    = NLOPT_LD_VAR1;
     ret["LD_VAR2"]                    = NLOPT_LD_VAR2;
     ret["LN_COBYLA"]                  = NLOPT_LN_COBYLA;
     ret["LN_BOBYQA"]                  = NLOPT_LN_BOBYQA;
     ret["LN_PRAXIS"]                  = NLOPT_LN_PRAXIS;
     ret["LN_NELDERMEAD"]              = NLOPT_LN_NELDERMEAD;
     ret["LN_SBPLX"]                   = NLOPT_LN_SBPLX;
     ret["GN_ISRES"]                   = NLOPT_GN_ISRES;
     return ret;
   }
template<typename T > void libMesh::NloptOptimizationSolver< T >::clear () virtual
Release all memory and clear data structures.
Reimplemented from libMesh::OptimizationSolver< T >.
Definition at line 310 of file nlopt_optimization_solver.C.
References libMesh::OptimizationSolver< T >::_is_initialized, libMesh::NloptOptimizationSolver< T >::_opt, and libMesh::OptimizationSolver< T >::initialized().
Referenced by libMesh::NloptOptimizationSolver< T >::~NloptOptimizationSolver().
 {
   if (this->initialized())
     {
       this->_is_initialized = false;
       nlopt_destroy(_opt);
     }
 }
const Parallel::Communicator& libMesh::ParallelObject::comm () const inline inherited
Returns
a reference to the Parallel::Communicator object used by this mesh.
Definition at line 87 of file parallel_object.h.
References libMesh::ParallelObject::_communicator.
Referenced by libMesh::__libmesh_petsc_diff_solver_monitor(), libMesh::__libmesh_petsc_diff_solver_residual(), libMesh::__libmesh_petsc_snes_jacobian(), libMesh::__libmesh_petsc_snes_postcheck(), libMesh::__libmesh_petsc_snes_residual(), libMesh::__libmesh_tao_equality_constraints(), libMesh::__libmesh_tao_equality_constraints_jacobian(), libMesh::__libmesh_tao_gradient(), libMesh::__libmesh_tao_hessian(), libMesh::__libmesh_tao_inequality_constraints(), libMesh::__libmesh_tao_inequality_constraints_jacobian(), libMesh::__libmesh_tao_objective(), libMesh::MeshRefinement::_coarsen_elements(), libMesh::ExactSolution::_compute_error(), libMesh::ParmetisPartitioner::_do_repartition(), libMesh::UniformRefinementEstimator::_estimate_error(), libMesh::BoundaryInfo::_find_id_maps(), libMesh::PetscLinearSolver< T >::_petsc_shell_matrix_get_diagonal(), libMesh::SlepcEigenSolver< T >::_petsc_shell_matrix_get_diagonal(), libMesh::PetscLinearSolver< T >::_petsc_shell_matrix_mult(), libMesh::SlepcEigenSolver< T >::_petsc_shell_matrix_mult(), libMesh::PetscLinearSolver< T >::_petsc_shell_matrix_mult_add(), libMesh::EquationSystems::_read_impl(), libMesh::MeshRefinement::_refine_elements(), libMesh::MeshRefinement::_smooth_flags(), libMesh::ImplicitSystem::add_matrix(), libMesh::System::add_vector(), libMesh::EigenSparseLinearSolver< T >::adjoint_solve(), libMesh::UnstructuredMesh::all_second_order(), libMesh::MeshTools::Modification::all_tri(), libMesh::LaplaceMeshSmoother::allgather_graph(), libMesh::FEMSystem::assemble_qoi(), libMesh::MeshCommunication::assign_global_indices(), libMesh::ParmetisPartitioner::assign_partitioning(), libMesh::DofMap::attach_matrix(), libMesh::Parallel::BinSorter< KeyType, IdxType >::binsort(), libMesh::Parallel::Sort< KeyType, IdxType >::binsort(), libMesh::MeshCommunication::broadcast(), libMesh::SparseMatrix< T >::build(), libMesh::MeshTools::Generation::build_extrusion(), libMesh::Parallel::Histogram< KeyType, IdxType >::build_histogram(), libMesh::PetscNonlinearSolver< T >::build_mat_null_space(), libMesh::BoundaryInfo::build_node_list_from_side_list(), libMesh::EquationSystems::build_parallel_solution_vector(), libMesh::MeshBase::cache_elem_dims(), libMesh::System::calculate_norm(), libMesh::DofMap::check_dirichlet_bcid_consistency(), libMesh::DistributedVector< T >::clone(), libMesh::EigenSparseVector< T >::clone(), libMesh::LaspackVector< T >::clone(), libMesh::EpetraVector< T >::clone(), libMesh::PetscVector< T >::clone(), libMesh::EpetraVector< T >::close(), libMesh::Parallel::Sort< KeyType, IdxType >::communicate_bins(), libMesh::Nemesis_IO_Helper::compute_num_global_elem_blocks(), libMesh::Nemesis_IO_Helper::compute_num_global_nodesets(), libMesh::Nemesis_IO_Helper::compute_num_global_sidesets(), libMesh::Problem_Interface::computeF(), libMesh::Problem_Interface::computeJacobian(), libMesh::Problem_Interface::computePreconditioner(), libMesh::MeshTools::correct_node_proc_ids(), libMesh::MeshTools::create_bounding_box(), libMesh::MeshTools::create_nodal_bounding_box(), libMesh::MeshRefinement::create_parent_error_vector(), libMesh::MeshTools::create_processor_bounding_box(), libMesh::MeshTools::create_subdomain_bounding_box(), libMesh::MeshCommunication::delete_remote_elements(), libMesh::DofMap::distribute_dofs(), DMlibMeshFunction(), DMlibMeshJacobian(), DMlibMeshSetSystem_libMesh(), DMVariableBounds_libMesh(), libMesh::MeshRefinement::eliminate_unrefined_patches(), libMesh::EpetraVector< T >::EpetraVector(), libMesh::WeightedPatchRecoveryErrorEstimator::estimate_error(), libMesh::PatchRecoveryErrorEstimator::estimate_error(), libMesh::JumpErrorEstimator::estimate_error(), libMesh::AdjointRefinementEstimator::estimate_error(), libMesh::ExactErrorEstimator::estimate_error(), libMesh::MeshRefinement::flag_elements_by_elem_fraction(), libMesh::MeshRefinement::flag_elements_by_error_fraction(), libMesh::MeshRefinement::flag_elements_by_nelem_target(), libMesh::MeshCommunication::gather(), libMesh::MeshCommunication::gather_neighboring_elements(), libMesh::CondensedEigenSystem::get_eigenpair(), libMesh::DofMap::get_info(), libMesh::ImplicitSystem::get_linear_solver(), libMesh::EquationSystems::get_solution(), libMesh::LocationMap< T >::init(), libMesh::PetscDiffSolver::init(), libMesh::TimeSolver::init(), libMesh::TopologyMap::init(), libMesh::TaoOptimizationSolver< T >::init(), libMesh::PetscNonlinearSolver< T >::init(), libMesh::DistributedVector< T >::init(), libMesh::EpetraVector< T >::init(), libMesh::PetscVector< T >::init(), libMesh::SystemSubsetBySubdomain::init(), libMesh::EigenSystem::init_data(), libMesh::EigenSystem::init_matrices(), libMesh::ParmetisPartitioner::initialize(), libMesh::OptimizationSystem::initialize_equality_constraints_storage(), libMesh::OptimizationSystem::initialize_inequality_constraints_storage(), libMesh::MeshTools::libmesh_assert_parallel_consistent_procids< Elem >(), libMesh::MeshTools::libmesh_assert_parallel_consistent_procids< Node >(), libMesh::MeshTools::libmesh_assert_topology_consistent_procids< Node >(), libMesh::MeshTools::libmesh_assert_valid_boundary_ids(), libMesh::MeshTools::libmesh_assert_valid_dof_ids(), libMesh::MeshTools::libmesh_assert_valid_neighbors(), libMesh::DistributedMesh::libmesh_assert_valid_parallel_flags(), libMesh::DistributedMesh::libmesh_assert_valid_parallel_object_ids(), libMesh::DistributedMesh::libmesh_assert_valid_parallel_p_levels(), libMesh::MeshTools::libmesh_assert_valid_refinement_flags(), libMesh::MeshTools::libmesh_assert_valid_unique_ids(), libMesh::MeshRefinement::limit_level_mismatch_at_edge(), libMesh::MeshRefinement::limit_level_mismatch_at_node(), libMesh::MeshRefinement::limit_overrefined_boundary(), libMesh::MeshRefinement::limit_underrefined_boundary(), libMesh::MeshRefinement::make_coarsening_compatible(), libMesh::MeshCommunication::make_elems_parallel_consistent(), libMesh::MeshRefinement::make_flags_parallel_consistent(), libMesh::MeshCommunication::make_new_node_proc_ids_parallel_consistent(), libMesh::MeshCommunication::make_new_nodes_parallel_consistent(), libMesh::MeshCommunication::make_node_ids_parallel_consistent(), libMesh::MeshCommunication::make_node_proc_ids_parallel_consistent(), libMesh::MeshCommunication::make_node_unique_ids_parallel_consistent(), libMesh::MeshCommunication::make_nodes_parallel_consistent(), libMesh::MeshCommunication::make_p_levels_parallel_consistent(), libMesh::MeshRefinement::make_refinement_compatible(), libMesh::DistributedVector< T >::max(), libMesh::FEMSystem::mesh_position_set(), libMesh::MeshSerializer::MeshSerializer(), libMesh::DistributedVector< T >::min(), libMesh::DistributedMesh::n_active_elem(), libMesh::MeshTools::n_active_levels(), libMesh::BoundaryInfo::n_boundary_conds(), libMesh::BoundaryInfo::n_edge_conds(), libMesh::CondensedEigenSystem::n_global_non_condensed_dofs(), libMesh::MeshTools::n_levels(), libMesh::BoundaryInfo::n_nodeset_conds(), libMesh::MeshTools::n_p_levels(), libMesh::BoundaryInfo::n_shellface_conds(), libMesh::DistributedMesh::parallel_max_elem_id(), libMesh::DistributedMesh::parallel_max_node_id(), libMesh::ReplicatedMesh::parallel_max_unique_id(), libMesh::DistributedMesh::parallel_max_unique_id(), libMesh::DistributedMesh::parallel_n_elem(), libMesh::DistributedMesh::parallel_n_nodes(), libMesh::SparsityPattern::Build::parallel_sync(), libMesh::MeshTools::paranoid_n_levels(), libMesh::Partitioner::partition(), libMesh::MetisPartitioner::partition_range(), libMesh::Partitioner::partition_unpartitioned_elements(), libMesh::petsc_auto_fieldsplit(), libMesh::System::point_gradient(), libMesh::System::point_hessian(), libMesh::System::point_value(), libMesh::MeshBase::prepare_for_use(), libMesh::SparseMatrix< T >::print(), libMesh::Nemesis_IO::read(), libMesh::CheckpointIO::read(), libMesh::XdrIO::read(), libMesh::XdrIO::read_serialized_bc_names(), libMesh::XdrIO::read_serialized_bcs_helper(), libMesh::XdrIO::read_serialized_connectivity(), libMesh::XdrIO::read_serialized_nodes(), libMesh::XdrIO::read_serialized_nodesets(), libMesh::XdrIO::read_serialized_subdomain_names(), libMesh::MeshBase::recalculate_n_partitions(), libMesh::MeshCommunication::redistribute(), libMesh::DistributedMesh::renumber_dof_objects(), libMesh::MeshCommunication::send_coarse_ghosts(), libMesh::Partitioner::set_node_processor_ids(), libMesh::DofMap::set_nonlocal_dof_objects(), libMesh::Partitioner::set_parent_processor_ids(), libMesh::LaplaceMeshSmoother::smooth(), libMesh::Parallel::Sort< KeyType, IdxType >::sort(), libMesh::MeshBase::subdomain_ids(), libMesh::BoundaryInfo::sync(), libMesh::Parallel::sync_element_data_by_parent_id(), libMesh::Parallel::sync_node_data_by_element_id(), libMesh::MeshRefinement::test_level_one(), libMesh::MeshRefinement::test_unflagged(), libMesh::MeshTools::total_weight(), libMesh::NameBasedIO::write(), libMesh::XdrIO::write(), libMesh::XdrIO::write_serialized_bcs_helper(), libMesh::XdrIO::write_serialized_connectivity(), libMesh::XdrIO::write_serialized_nodes(), libMesh::XdrIO::write_serialized_nodesets(), libMesh::DistributedVector< T >::zero_clone(), libMesh::LaspackVector< T >::zero_clone(), libMesh::EigenSparseVector< T >::zero_clone(), libMesh::EpetraVector< T >::zero_clone(), and libMesh::PetscVector< T >::zero_clone().
   { return _communicator; }
void libMesh::ReferenceCounter::disable_print_counter_info () static inherited
Definition at line 107 of file reference_counter.C.
References libMesh::ReferenceCounter::_enable_print_counter.
Referenced by libMesh::LibMeshInit::LibMeshInit(), and libMesh::ReferenceCounter::n_objects().
 {
   _enable_print_counter = false;
   return;
 }
void libMesh::ReferenceCounter::enable_print_counter_info () static inherited
Methods to enable/disable the reference counter output from print_info()
Definition at line 101 of file reference_counter.C.
References libMesh::ReferenceCounter::_enable_print_counter.
Referenced by libMesh::ReferenceCounter::n_objects().
 {
   _enable_print_counter = true;
   return;
 }
template<typename T > int libMesh::NloptOptimizationSolver< T >::get_converged_reason () virtual
Returns the currently-available (or most recently obtained, if the NLopt object has been destroyed) convergence reason. Refer to NLopt docs for the meaning of different the value.
Reimplemented from libMesh::OptimizationSolver< T >.
Definition at line 463 of file nlopt_optimization_solver.C.
References libMesh::NloptOptimizationSolver< T >::_result.
Referenced by libMesh::NloptOptimizationSolver< T >::get_nlopt_object(), and libMesh::NloptOptimizationSolver< T >::print_converged_reason().
 {
   return static_cast<int>(_result);
 }
template<typename T > virtual void libMesh::OptimizationSolver< T >::get_dual_variables () inline virtual inherited
Get the current values of dual variables associated with inequality and equality constraints. The variables will be stored in _system.lambda_eq and _system.lambda_ineq.
Reimplemented in libMesh::TaoOptimizationSolver< T >.
Definition at line 104 of file optimization_solver.h.
   { libmesh_not_implemented(); }
std::string libMesh::ReferenceCounter::get_info () static inherited
Gets a string containing the reference information.
Definition at line 47 of file reference_counter.C.
References libMesh::ReferenceCounter::_counts, and libMesh::Quality::name().
Referenced by libMesh::ReferenceCounter::print_info().
 {
 #if defined(LIBMESH_ENABLE_REFERENCE_COUNTING) && defined(DEBUG)
   std::ostringstream oss;
   oss << '\n'
       << " ---------------------------------------------------------------------------- \n"
       << "| Reference count information                                                |\n"
       << " ---------------------------------------------------------------------------- \n";
   for (Counts::iterator it = _counts.begin();
        it != _counts.end(); ++it)
     {
       const std::string name(it->first);
       const unsigned int creations    = it->second.first;
       const unsigned int destructions = it->second.second;
       oss << "| " << name << " reference count information:\n"
           << "|  Creations:    " << creations    << '\n'
           << "|  Destructions: " << destructions << '\n';
     }
   oss << " ---------------------------------------------------------------------------- \n";
   return oss.str();
 #else
   return "";
 #endif
 }
template<typename T> unsigned& libMesh::NloptOptimizationSolver< T >::get_iteration_count () inline
Returns a writeable reference to the current iteration count which can be incremented in the objective function.
Definition at line 127 of file nlopt_optimization_solver.h.
References libMesh::NloptOptimizationSolver< T >::_iteration_count.
Referenced by libMesh::__libmesh_nlopt_objective(), and libMesh::NloptOptimizationSolver< T >::solve().
 { return _iteration_count; }
template<typename T> nlopt_opt libMesh::NloptOptimizationSolver< T >::get_nlopt_object () inline
Returns the raw NLopt object.
Definition at line 103 of file nlopt_optimization_solver.h.
References libMesh::NloptOptimizationSolver< T >::_opt, libMesh::NloptOptimizationSolver< T >::get_converged_reason(), libMesh::NloptOptimizationSolver< T >::init(), libMesh::NloptOptimizationSolver< T >::print_converged_reason(), and libMesh::NloptOptimizationSolver< T >::solve().
 { this->init(); return _opt; }
void libMesh::ReferenceCounter::increment_constructor_count (const std::string & name) inline protected inherited
Increments the construction counter. Should be called in the constructor of any derived class that will be reference counted.
Definition at line 185 of file reference_counter.h.
References libMesh::ReferenceCounter::_counts, libMesh::Quality::name(), and libMesh::Threads::spin_mtx.
Referenced by libMesh::ReferenceCounter::n_objects(), and libMesh::ReferenceCountedObject< RBParametrized >::ReferenceCountedObject().
 {
   Threads::spin_mutex::scoped_lock lock(Threads::spin_mtx);
   std::pair<unsigned int, unsigned int> & p = _counts[name];
   p.first++;
 }
void libMesh::ReferenceCounter::increment_destructor_count (const std::string & name) inline protected inherited
Increments the destruction counter. Should be called in the destructor of any derived class that will be reference counted.
Definition at line 198 of file reference_counter.h.
References libMesh::ReferenceCounter::_counts, libMesh::Quality::name(), and libMesh::Threads::spin_mtx.
Referenced by libMesh::ReferenceCounter::n_objects(), and libMesh::ReferenceCountedObject< RBParametrized >::~ReferenceCountedObject().
 {
   Threads::spin_mutex::scoped_lock lock(Threads::spin_mtx);
   std::pair<unsigned int, unsigned int> & p = _counts[name];
   p.second++;
 }
template<typename T > void libMesh::NloptOptimizationSolver< T >::init () virtual
Initialize data structures if not done so already.
Implements libMesh::OptimizationSolver< T >.
Definition at line 323 of file nlopt_optimization_solver.C.
References libMesh::OptimizationSolver< T >::_is_initialized, libMesh::NloptOptimizationSolver< T >::_nlopt_algorithms, libMesh::NloptOptimizationSolver< T >::_opt, libMesh::command_line_next(), libMesh::OptimizationSolver< T >::initialized(), and libMesh::on_command_line().
Referenced by libMesh::NloptOptimizationSolver< T >::get_nlopt_object(), and libMesh::NloptOptimizationSolver< T >::solve().
 {
   // Initialize the data structures if not done so already.
   if (!this->initialized())
     {
       this->_is_initialized = true;
       // By default, use the LD_SLSQP solver
       std::string nlopt_algorithm_name = "LD_SLSQP";
       if (libMesh::on_command_line("--nlopt-algorithm"))
         nlopt_algorithm_name = libMesh::command_line_next ("--nlopt-algorithm",
                                                            nlopt_algorithm_name);
       // Convert string to an nlopt algorithm type
       std::map<std::string, nlopt_algorithm>::iterator it =
         _nlopt_algorithms.find(nlopt_algorithm_name);
       if (it == _nlopt_algorithms.end())
         libmesh_error_msg("Invalid nlopt algorithm requested on command line: " \
                           << nlopt_algorithm_name);
       _opt = nlopt_create(it->second, this->system().solution->size());
     }
 }
template<typename T > bool libMesh::OptimizationSolver< T >::initialized () const inline inherited
Returns
true if the data structures are initialized, false otherwise.
Definition at line 82 of file optimization_solver.h.
References libMesh::OptimizationSolver< T >::_is_initialized.
Referenced by libMesh::TaoOptimizationSolver< T >::clear(), libMesh::NloptOptimizationSolver< T >::clear(), libMesh::TaoOptimizationSolver< T >::get_converged_reason(), libMesh::TaoOptimizationSolver< T >::init(), and libMesh::NloptOptimizationSolver< T >::init().
 { return _is_initialized; }
static unsigned int libMesh::ReferenceCounter::n_objects () inline static inherited
Prints the number of outstanding (created, but not yet destroyed) objects.
Definition at line 85 of file reference_counter.h.
References libMesh::ReferenceCounter::_n_objects, libMesh::ReferenceCounter::disable_print_counter_info(), libMesh::ReferenceCounter::enable_print_counter_info(), libMesh::ReferenceCounter::increment_constructor_count(), libMesh::ReferenceCounter::increment_destructor_count(), and libMesh::Quality::name().
Referenced by libMesh::System::hide_output(), and libMesh::LibMeshInit::LibMeshInit().
   { return _n_objects; }
processor_id_type libMesh::ParallelObject::n_processors () const inline inherited
Returns
the number of processors in the group.
Definition at line 93 of file parallel_object.h.
References libMesh::ParallelObject::_communicator, and libMesh::Parallel::Communicator::size().
Referenced by libMesh::ParmetisPartitioner::_do_repartition(), libMesh::BoundaryInfo::_find_id_maps(), libMesh::DistributedMesh::add_elem(), libMesh::DistributedMesh::add_node(), libMesh::LaplaceMeshSmoother::allgather_graph(), libMesh::FEMSystem::assembly(), libMesh::ParmetisPartitioner::assign_partitioning(), libMesh::AztecLinearSolver< T >::AztecLinearSolver(), libMesh::MeshCommunication::broadcast(), libMesh::BoundaryInfo::build_node_list_from_side_list(), libMesh::DistributedMesh::clear(), libMesh::Nemesis_IO_Helper::compute_border_node_ids(), libMesh::Nemesis_IO_Helper::construct_nemesis_filename(), libMesh::MeshTools::correct_node_proc_ids(), libMesh::UnstructuredMesh::create_pid_mesh(), libMesh::MeshTools::create_processor_bounding_box(), libMesh::DofMap::distribute_dofs(), libMesh::DofMap::distribute_local_dofs_node_major(), libMesh::DofMap::distribute_local_dofs_var_major(), libMesh::DistributedMesh::DistributedMesh(), libMesh::EnsightIO::EnsightIO(), libMesh::MeshCommunication::gather(), libMesh::MeshCommunication::gather_neighboring_elements(), libMesh::MeshBase::get_info(), libMesh::EquationSystems::get_solution(), libMesh::DistributedVector< T >::init(), libMesh::SystemSubsetBySubdomain::init(), libMesh::ParmetisPartitioner::initialize(), libMesh::Nemesis_IO_Helper::initialize(), libMesh::DistributedMesh::insert_elem(), libMesh::MeshTools::libmesh_assert_parallel_consistent_procids< Elem >(), libMesh::MeshTools::libmesh_assert_parallel_consistent_procids< Node >(), libMesh::MeshTools::libmesh_assert_topology_consistent_procids< Node >(), libMesh::MeshTools::libmesh_assert_valid_boundary_ids(), libMesh::MeshTools::libmesh_assert_valid_dof_ids(), libMesh::MeshTools::libmesh_assert_valid_neighbors(), libMesh::MeshTools::libmesh_assert_valid_refinement_flags(), libMesh::DofMap::local_variable_indices(), libMesh::MeshBase::n_active_elem_on_proc(), libMesh::MeshBase::n_elem_on_proc(), libMesh::MeshBase::n_nodes_on_proc(), libMesh::SparsityPattern::Build::parallel_sync(), libMesh::Partitioner::partition(), libMesh::MeshBase::partition(), libMesh::Partitioner::partition_unpartitioned_elements(), libMesh::PetscLinearSolver< T >::PetscLinearSolver(), libMesh::System::point_gradient(), libMesh::System::point_hessian(), libMesh::System::point_value(), libMesh::SparseMatrix< T >::print(), libMesh::NameBasedIO::read(), libMesh::Nemesis_IO::read(), libMesh::CheckpointIO::read(), libMesh::XdrIO::read(), libMesh::CheckpointIO::read_connectivity(), libMesh::CheckpointIO::read_nodes(), libMesh::MeshCommunication::redistribute(), libMesh::DistributedMesh::renumber_dof_objects(), libMesh::Partitioner::repartition(), libMesh::MeshCommunication::send_coarse_ghosts(), libMesh::Partitioner::set_node_processor_ids(), libMesh::DofMap::set_nonlocal_dof_objects(), libMesh::Parallel::Sort< KeyType, IdxType >::sort(), libMesh::DistributedMesh::update_parallel_id_counts(), libMesh::GMVIO::write_binary(), libMesh::GMVIO::write_discontinuous_gmv(), libMesh::XdrIO::write_serialized_bcs_helper(), libMesh::XdrIO::write_serialized_connectivity(), libMesh::XdrIO::write_serialized_nodes(), and libMesh::XdrIO::write_serialized_nodesets().
   { return cast_int<processor_id_type>(_communicator.size()); }
template<typename T > void libMesh::NloptOptimizationSolver< T >::print_converged_reason () virtual
Prints a useful message about why the latest optimization solve con(di)verged.
Reimplemented from libMesh::OptimizationSolver< T >.
Definition at line 454 of file nlopt_optimization_solver.C.
References libMesh::NloptOptimizationSolver< T >::get_converged_reason(), and libMesh::out.
Referenced by libMesh::NloptOptimizationSolver< T >::get_nlopt_object().
 {
   libMesh::out << "NLopt optimization solver convergence/divergence reason: "
                << this->get_converged_reason() << std::endl;
 }
void libMesh::ReferenceCounter::print_info (std::ostream & out = libMesh::out) static inherited
Prints the reference information, by default to libMesh::out.
Definition at line 88 of file reference_counter.C.
References libMesh::ReferenceCounter::_enable_print_counter, and libMesh::ReferenceCounter::get_info().
Referenced by libMesh::LibMeshInit::LibMeshInit().
 {
   if (_enable_print_counter)
     out_stream << ReferenceCounter::get_info();
 }
processor_id_type libMesh::ParallelObject::processor_id () const inline inherited
Returns
the rank of this processor in the group.
Definition at line 99 of file parallel_object.h.
References libMesh::ParallelObject::_communicator, and libMesh::Parallel::Communicator::rank().
Referenced by libMesh::BoundaryInfo::_find_id_maps(), libMesh::EquationSystems::_read_impl(), libMesh::DistributedMesh::add_elem(), libMesh::BoundaryInfo::add_elements(), libMesh::DofMap::add_neighbors_to_send_list(), libMesh::DistributedMesh::add_node(), libMesh::MeshRefinement::add_node(), libMesh::MeshTools::Modification::all_tri(), libMesh::FEMSystem::assembly(), libMesh::ParmetisPartitioner::assign_partitioning(), libMesh::MeshCommunication::broadcast(), libMesh::EquationSystems::build_discontinuous_solution_vector(), libMesh::Nemesis_IO_Helper::build_element_and_node_maps(), libMesh::ParmetisPartitioner::build_graph(), libMesh::InfElemBuilder::build_inf_elem(), libMesh::BoundaryInfo::build_node_list_from_side_list(), libMesh::DofMap::build_sparsity(), libMesh::DistributedMesh::clear(), libMesh::ExodusII_IO_Helper::close(), libMesh::Nemesis_IO_Helper::compute_border_node_ids(), libMesh::Nemesis_IO_Helper::compute_communication_map_parameters(), libMesh::Nemesis_IO_Helper::compute_internal_and_border_elems_and_internal_nodes(), libMesh::Nemesis_IO_Helper::compute_node_communication_maps(), libMesh::Nemesis_IO_Helper::compute_num_global_elem_blocks(), libMesh::Nemesis_IO_Helper::compute_num_global_nodesets(), libMesh::Nemesis_IO_Helper::compute_num_global_sidesets(), libMesh::Nemesis_IO_Helper::construct_nemesis_filename(), libMesh::MeshTools::correct_node_proc_ids(), libMesh::ExodusII_IO_Helper::create(), libMesh::DistributedMesh::delete_elem(), libMesh::DistributedMesh::delete_node(), libMesh::MeshCommunication::delete_remote_elements(), libMesh::DofMap::distribute_dofs(), libMesh::DofMap::distribute_local_dofs_node_major(), libMesh::DofMap::distribute_local_dofs_var_major(), libMesh::DistributedMesh::DistributedMesh(), libMesh::EnsightIO::EnsightIO(), libMesh::MeshFunction::find_element(), libMesh::MeshFunction::find_elements(), libMesh::UnstructuredMesh::find_neighbors(), libMesh::MeshCommunication::gather(), libMesh::MeshCommunication::gather_neighboring_elements(), libMesh::Nemesis_IO_Helper::get_cmap_params(), libMesh::Nemesis_IO_Helper::get_eb_info_global(), libMesh::Nemesis_IO_Helper::get_elem_cmap(), libMesh::Nemesis_IO_Helper::get_elem_map(), libMesh::MeshBase::get_info(), libMesh::DofMap::get_info(), libMesh::Nemesis_IO_Helper::get_init_global(), libMesh::Nemesis_IO_Helper::get_init_info(), libMesh::Nemesis_IO_Helper::get_loadbal_param(), libMesh::Nemesis_IO_Helper::get_node_cmap(), libMesh::Nemesis_IO_Helper::get_node_map(), libMesh::Nemesis_IO_Helper::get_ns_param_global(), libMesh::EquationSystems::get_solution(), libMesh::Nemesis_IO_Helper::get_ss_param_global(), libMesh::SparsityPattern::Build::handle_vi_vj(), libMesh::DistributedVector< T >::init(), libMesh::SystemSubsetBySubdomain::init(), libMesh::ParmetisPartitioner::initialize(), libMesh::ExodusII_IO_Helper::initialize(), libMesh::ExodusII_IO_Helper::initialize_element_variables(), libMesh::ExodusII_IO_Helper::initialize_global_variables(), libMesh::ExodusII_IO_Helper::initialize_nodal_variables(), libMesh::DistributedMesh::insert_elem(), libMesh::DofMap::is_evaluable(), libMesh::SparsityPattern::Build::join(), libMesh::MeshTools::libmesh_assert_parallel_consistent_procids< Elem >(), libMesh::MeshTools::libmesh_assert_parallel_consistent_procids< Node >(), libMesh::MeshTools::libmesh_assert_valid_neighbors(), libMesh::DistributedMesh::libmesh_assert_valid_parallel_object_ids(), libMesh::DofMap::local_variable_indices(), libMesh::MeshRefinement::make_coarsening_compatible(), libMesh::MeshBase::n_active_local_elem(), libMesh::BoundaryInfo::n_boundary_conds(), libMesh::BoundaryInfo::n_edge_conds(), libMesh::System::n_local_dofs(), libMesh::MeshBase::n_local_elem(), libMesh::MeshBase::n_local_nodes(), libMesh::BoundaryInfo::n_nodeset_conds(), libMesh::BoundaryInfo::n_shellface_conds(), libMesh::WeightedPatchRecoveryErrorEstimator::EstimateError::operator()(), libMesh::SparsityPattern::Build::operator()(), libMesh::PatchRecoveryErrorEstimator::EstimateError::operator()(), libMesh::SparsityPattern::Build::parallel_sync(), libMesh::MetisPartitioner::partition_range(), libMesh::System::point_gradient(), libMesh::System::point_hessian(), libMesh::System::point_value(), libMesh::SparseMatrix< T >::print(), libMesh::NumericVector< T >::print_global(), libMesh::Nemesis_IO_Helper::put_cmap_params(), libMesh::Nemesis_IO_Helper::put_elem_cmap(), libMesh::Nemesis_IO_Helper::put_elem_map(), libMesh::Nemesis_IO_Helper::put_loadbal_param(), libMesh::Nemesis_IO_Helper::put_node_cmap(), libMesh::Nemesis_IO_Helper::put_node_map(), libMesh::NameBasedIO::read(), libMesh::Nemesis_IO::read(), libMesh::CheckpointIO::read(), libMesh::XdrIO::read(), libMesh::ExodusII_IO_Helper::read_elem_num_map(), libMesh::ExodusII_IO_Helper::read_node_num_map(), libMesh::XdrIO::read_serialized_bc_names(), libMesh::XdrIO::read_serialized_bcs_helper(), libMesh::XdrIO::read_serialized_connectivity(), libMesh::XdrIO::read_serialized_nodes(), libMesh::XdrIO::read_serialized_nodesets(), libMesh::XdrIO::read_serialized_subdomain_names(), libMesh::MeshCommunication::redistribute(), libMesh::DistributedMesh::renumber_dof_objects(), libMesh::MeshCommunication::send_coarse_ghosts(), libMesh::Partitioner::set_node_processor_ids(), libMesh::DofMap::set_nonlocal_dof_objects(), libMesh::LaplaceMeshSmoother::smooth(), libMesh::MeshTools::total_weight(), libMesh::Parallel::Packing< Node * >::unpack(), libMesh::Parallel::Packing< Elem * >::unpack(), libMesh::DistributedMesh::update_parallel_id_counts(), libMesh::MeshTools::weight(), libMesh::NameBasedIO::write(), libMesh::CheckpointIO::write(), libMesh::XdrIO::write(), libMesh::EquationSystems::write(), libMesh::GMVIO::write_discontinuous_gmv(), libMesh::ExodusII_IO::write_element_data(), libMesh::ExodusII_IO_Helper::write_element_values(), libMesh::ExodusII_IO_Helper::write_elements(), libMesh::ExodusII_IO::write_global_data(), libMesh::ExodusII_IO_Helper::write_global_values(), libMesh::ExodusII_IO::write_information_records(), libMesh::ExodusII_IO_Helper::write_information_records(), libMesh::ExodusII_IO_Helper::write_nodal_coordinates(), libMesh::UCDIO::write_nodal_data(), libMesh::ExodusII_IO::write_nodal_data(), libMesh::ExodusII_IO::write_nodal_data_discontinuous(), libMesh::ExodusII_IO_Helper::write_nodal_values(), libMesh::Nemesis_IO_Helper::write_nodesets(), libMesh::ExodusII_IO_Helper::write_nodesets(), libMesh::XdrIO::write_serialized_bc_names(), libMesh::XdrIO::write_serialized_bcs_helper(), libMesh::XdrIO::write_serialized_connectivity(), libMesh::XdrIO::write_serialized_nodes(), libMesh::XdrIO::write_serialized_nodesets(), libMesh::XdrIO::write_serialized_subdomain_names(), libMesh::Nemesis_IO_Helper::write_sidesets(), libMesh::ExodusII_IO_Helper::write_sidesets(), libMesh::ExodusII_IO::write_timestep(), and libMesh::ExodusII_IO_Helper::write_timestep().
   { return cast_int<processor_id_type>(_communicator.rank()); }
template<typename T > void libMesh::NloptOptimizationSolver< T >::solve () virtual
Call the NLopt solver.
Implements libMesh::OptimizationSolver< T >.
Definition at line 352 of file nlopt_optimization_solver.C.
References libMesh::NloptOptimizationSolver< T >::__libmesh_nlopt_equality_constraints, libMesh::NloptOptimizationSolver< T >::__libmesh_nlopt_inequality_constraints, libMesh::NloptOptimizationSolver< T >::__libmesh_nlopt_objective, libMesh::NloptOptimizationSolver< T >::_constraints_tolerance, libMesh::NloptOptimizationSolver< T >::_iteration_count, libMesh::NloptOptimizationSolver< T >::_opt, libMesh::NloptOptimizationSolver< T >::_result, libMesh::OptimizationSolver< T >::equality_constraints_object, libMesh::NloptOptimizationSolver< T >::get_iteration_count(), libMesh::System::get_vector(), ierr, libMesh::OptimizationSolver< T >::inequality_constraints_object, libMesh::NloptOptimizationSolver< T >::init(), libMesh::libmesh_assert(), libMesh::OptimizationSystem::ComputeLowerAndUpperBounds::lower_and_upper_bounds(), libMesh::OptimizationSolver< T >::lower_and_upper_bounds_object, libMesh::OptimizationSolver< T >::max_objective_function_evaluations, libMesh::OptimizationSolver< T >::objective_function_relative_tolerance, libMesh::OptimizationSolver< T >::objective_object, libMesh::out, libMesh::Real, libMesh::System::solution, libMesh::OptimizationSolver< T >::system(), and libMesh::x.
Referenced by libMesh::NloptOptimizationSolver< T >::get_nlopt_object().
 {
   LOG_SCOPE("solve()", "NloptOptimizationSolver");
   this->init ();
   unsigned int nlopt_size = this->system().solution->size();
   // We have to have an objective function
   libmesh_assert( this->objective_object );
   // Set routine for objective and (optionally) gradient evaluation
   {
     nlopt_result ierr =
       nlopt_set_min_objective(_opt,
                               __libmesh_nlopt_objective,
                               this);
     if (ierr < 0)
       libmesh_error_msg("NLopt failed to set min objective: " << ierr);
   }
   if (this->lower_and_upper_bounds_object)
     {
       // Need to actually compute the bounds vectors first
       this->lower_and_upper_bounds_object->lower_and_upper_bounds(this->system());
       std::vector<Real> nlopt_lb(nlopt_size);
       std::vector<Real> nlopt_ub(nlopt_size);
       for (unsigned int i=0; i<nlopt_size; i++)
         {
           nlopt_lb[i] = this->system().get_vector("lower_bounds")(i);
           nlopt_ub[i] = this->system().get_vector("upper_bounds")(i);
         }
       nlopt_set_lower_bounds(_opt, &nlopt_lb[0]);
       nlopt_set_upper_bounds(_opt, &nlopt_ub[0]);
     }
   // If we have an equality constraints object, tell NLopt about it.
   if (this->equality_constraints_object)
     {
       // NLopt requires a vector to specify the tolerance for each constraint.
       // NLopt makes a copy of this vector internally, so it's safe for us to
       // let it go out of scope.
       std::vector<double> equality_constraints_tolerances(this->system().C_eq->size(),
                                                           _constraints_tolerance);
       // It would be nice to call the C interface directly, at least it should return an error
       // code we could parse... unfortunately, there does not seem to be a way to extract
       // the underlying nlopt_opt object from the nlopt::opt class!
       nlopt_result ierr =
         nlopt_add_equality_mconstraint(_opt,
                                        equality_constraints_tolerances.size(),
                                        __libmesh_nlopt_equality_constraints,
                                        this,
                                        &equality_constraints_tolerances[0]);
       if (ierr < 0)
         libmesh_error_msg("NLopt failed to add equality constraint: " << ierr);
     }
   // If we have an inequality constraints object, tell NLopt about it.
   if (this->inequality_constraints_object)
     {
       // NLopt requires a vector to specify the tolerance for each constraint
       std::vector<double> inequality_constraints_tolerances(this->system().C_ineq->size(),
                                                             _constraints_tolerance);
       nlopt_add_inequality_mconstraint(_opt,
                                        inequality_constraints_tolerances.size(),
                                        __libmesh_nlopt_inequality_constraints,
                                        this,
                                        &inequality_constraints_tolerances[0]);
     }
   // Set a relative tolerance on the optimization parameters
   nlopt_set_ftol_rel(_opt, this->objective_function_relative_tolerance);
   // Set the maximum number of allowed objective function evaluations
   nlopt_set_maxeval(_opt, this->max_objective_function_evaluations);
   // Reset internal iteration counter
   this->_iteration_count = 0;
   // Perform the optimization
   std::vector<Real> x(nlopt_size);
   Real min_val = 0.;
   _result = nlopt_optimize(_opt, &x[0], &min_val);
   if (_result < 0)
     libMesh::out << "NLopt failed!" << std::endl;
   else
     libMesh::out << "NLopt obtained optimal value: "
                  << min_val
                  << " in "
                  << this->get_iteration_count()
                  << " iterations."
                  << std::endl;
 }
template<typename T > const sys_type& libMesh::OptimizationSolver< T >::system () const inline inherited
Returns
a constant reference to the system we are using to define the optimization problem.
Definition at line 171 of file optimization_solver.h.
References libMesh::OptimizationSolver< T >::_system.
Referenced by libMesh::__libmesh_nlopt_equality_constraints(), libMesh::__libmesh_nlopt_inequality_constraints(), libMesh::__libmesh_nlopt_objective(), libMesh::__libmesh_tao_equality_constraints(), libMesh::__libmesh_tao_equality_constraints_jacobian(), libMesh::__libmesh_tao_gradient(), libMesh::__libmesh_tao_hessian(), libMesh::__libmesh_tao_inequality_constraints(), libMesh::__libmesh_tao_inequality_constraints_jacobian(), libMesh::__libmesh_tao_objective(), libMesh::TaoOptimizationSolver< T >::get_dual_variables(), libMesh::TaoOptimizationSolver< T >::solve(), and libMesh::NloptOptimizationSolver< T >::solve().
 { return _system; }
template<typename T > sys_type& libMesh::OptimizationSolver< T >::system () inline inherited
Returns
a writeable reference to the system we are using to define the optimization problem.
Definition at line 177 of file optimization_solver.h.
References libMesh::OptimizationSolver< T >::_system.
 { return _system; }
Friends And Related Function Documentation
template<typename T> void __libmesh_nlopt_equality_constraints (unsigned m, double * result, unsigned n, const double * x, double * gradient, void * data) friend
Definition at line 109 of file nlopt_optimization_solver.C.
Referenced by libMesh::NloptOptimizationSolver< T >::solve().
 {
   LOG_SCOPE("equality_constraints()", "NloptOptimizationSolver");
   libmesh_assert(data);
   // data should be a pointer to the solver (it was passed in as void *)
   NloptOptimizationSolver<Number> * solver =
     static_cast<NloptOptimizationSolver<Number> *> (data);
   OptimizationSystem & sys = solver->system();
   // We'll use current_local_solution below, so let's ensure that it's consistent
   // with the vector x that was passed in.
   if (sys.solution->size() != n)
     libmesh_error_msg("Error: Input vector x has different length than sys.solution!");
   for (unsigned int i=sys.solution->first_local_index(); i<sys.solution->last_local_index(); i++)
     sys.solution->set(i, x[i]);
   sys.solution->close();
   // Impose constraints on the solution vector
   sys.get_dof_map().enforce_constraints_exactly(sys);
   // Update sys.current_local_solution based on the solution vector
   sys.update();
   // Call the user's equality constraints function if there is one.
   OptimizationSystem::ComputeEqualityConstraints * eco = solver->equality_constraints_object;
   if (eco)
     {
       eco->equality_constraints(*sys.current_local_solution,
                                 *sys.C_eq,
                                 sys);
       sys.C_eq->close();
       // Copy the values out of eq_constraints into 'result'.
       // TODO: Even better would be if we could use 'result' directly
       // as the storage of eq_constraints.  Perhaps a serial-only
       // NumericVector variant which supports this option?
       for (unsigned i=0; i<m; ++i)
         result[i] = (*sys.C_eq)(i);
       // If gradient != NULL, then the Jacobian matrix of the equality
       // constraints has been requested.  The incoming 'gradient'
       // array is of length m*n and d(c_i)/d(x_j) = gradient[n*i+j].
       if (gradient)
         {
           OptimizationSystem::ComputeEqualityConstraintsJacobian * eco_jac =
             solver->equality_constraints_jacobian_object;
           if (eco_jac)
             {
               eco_jac->equality_constraints_jacobian(*sys.current_local_solution,
                                                      *sys.C_eq_jac,
                                                      sys);
               sys.C_eq_jac->close();
               // copy the Jacobian data to the gradient array
               for (numeric_index_type i=0; i<m; i++)
                 {
                   std::set<numeric_index_type>::iterator it = sys.eq_constraint_jac_sparsity[i].begin();
                   std::set<numeric_index_type>::iterator it_end = sys.eq_constraint_jac_sparsity[i].end();
                   for ( ; it != it_end; ++it)
                     {
                       numeric_index_type dof_index = *it;
                       gradient[n*i+dof_index] = (*sys.C_eq_jac)(i,dof_index);
                     }
                 }
             }
           else
             libmesh_error_msg("Jacobian function not defined in __libmesh_nlopt_equality_constraints");
         }
     }
   else
     libmesh_error_msg("Constraints function not defined in __libmesh_nlopt_equality_constraints");
 }
template<typename T> void __libmesh_nlopt_inequality_constraints (unsigned m, double * result, unsigned n, const double * x, double * gradient, void * data) friend
Definition at line 196 of file nlopt_optimization_solver.C.
Referenced by libMesh::NloptOptimizationSolver< T >::solve().
 {
   LOG_SCOPE("inequality_constraints()", "NloptOptimizationSolver");
   libmesh_assert(data);
   // data should be a pointer to the solver (it was passed in as void *)
   NloptOptimizationSolver<Number> * solver =
     static_cast<NloptOptimizationSolver<Number> *> (data);
   OptimizationSystem & sys = solver->system();
   // We'll use current_local_solution below, so let's ensure that it's consistent
   // with the vector x that was passed in.
   if (sys.solution->size() != n)
     libmesh_error_msg("Error: Input vector x has different length than sys.solution!");
   for (unsigned int i=sys.solution->first_local_index(); i<sys.solution->last_local_index(); i++)
     sys.solution->set(i, x[i]);
   sys.solution->close();
   // Impose constraints on the solution vector
   sys.get_dof_map().enforce_constraints_exactly(sys);
   // Update sys.current_local_solution based on the solution vector
   sys.update();
   // Call the user's inequality constraints function if there is one.
   OptimizationSystem::ComputeInequalityConstraints * ineco = solver->inequality_constraints_object;
   if (ineco)
     {
       ineco->inequality_constraints(*sys.current_local_solution,
                                     *sys.C_ineq,
                                     sys);
       sys.C_ineq->close();
       // Copy the values out of ineq_constraints into 'result'.
       // TODO: Even better would be if we could use 'result' directly
       // as the storage of ineq_constraints.  Perhaps a serial-only
       // NumericVector variant which supports this option?
       for (unsigned i=0; i<m; ++i)
         result[i] = (*sys.C_ineq)(i);
       // If gradient != NULL, then the Jacobian matrix of the equality
       // constraints has been requested.  The incoming 'gradient'
       // array is of length m*n and d(c_i)/d(x_j) = gradient[n*i+j].
       if (gradient)
         {
           OptimizationSystem::ComputeInequalityConstraintsJacobian * ineco_jac =
             solver->inequality_constraints_jacobian_object;
           if (ineco_jac)
             {
               ineco_jac->inequality_constraints_jacobian(*sys.current_local_solution,
                                                          *sys.C_ineq_jac,
                                                          sys);
               sys.C_ineq_jac->close();
               // copy the Jacobian data to the gradient array
               for (numeric_index_type i=0; i<m; i++)
                 {
                   std::set<numeric_index_type>::iterator it = sys.ineq_constraint_jac_sparsity[i].begin();
                   std::set<numeric_index_type>::iterator it_end = sys.ineq_constraint_jac_sparsity[i].end();
                   for ( ; it != it_end; ++it)
                     {
                       numeric_index_type dof_index = *it;
                       gradient[n*i+dof_index] = (*sys.C_ineq_jac)(i,dof_index);
                     }
                 }
             }
           else
             libmesh_error_msg("Jacobian function not defined in __libmesh_nlopt_inequality_constraints");
         }
     }
   else
     libmesh_error_msg("Constraints function not defined in __libmesh_nlopt_inequality_constraints");
 }
template<typename T> double __libmesh_nlopt_objective (unsigned n, const double * x, double * gradient, void * data) friend
Definition at line 36 of file nlopt_optimization_solver.C.
Referenced by libMesh::NloptOptimizationSolver< T >::solve().
 {
   LOG_SCOPE("objective()", "NloptOptimizationSolver");
   // ctx should be a pointer to the solver (it was passed in as void *)
   NloptOptimizationSolver<Number> * solver =
     static_cast<NloptOptimizationSolver<Number> *> (data);
   OptimizationSystem & sys = solver->system();
   // We'll use current_local_solution below, so let's ensure that it's consistent
   // with the vector x that was passed in.
   for (unsigned int i=sys.solution->first_local_index();
        i<sys.solution->last_local_index(); i++)
     sys.solution->set(i, x[i]);
   // Make sure the solution vector is parallel-consistent
   sys.solution->close();
   // Impose constraints on X
   sys.get_dof_map().enforce_constraints_exactly(sys);
   // Update sys.current_local_solution based on X
   sys.update();
   Real objective;
   if (solver->objective_object != libmesh_nullptr)
     {
       objective =
         solver->objective_object->objective(
                                             *(sys.current_local_solution), sys);
     }
   else
     {
       libmesh_error_msg("Objective function not defined in __libmesh_nlopt_objective");
     }
   // If the gradient has been requested, fill it in
   if (gradient)
     {
       if (solver->gradient_object != libmesh_nullptr)
         {
           solver->gradient_object->gradient(
                                             *(sys.current_local_solution), *(sys.rhs), sys);
           // we've filled up sys.rhs with the gradient data, now copy it
           // to the nlopt data structure
           libmesh_assert(sys.rhs->size() == n);
           std::vector<double> grad;
           sys.rhs->localize_to_one(grad);
           for (unsigned i=0; i<n; ++i)
             gradient[i] = grad[i];
         }
       else
         libmesh_error_msg("Gradient function not defined in __libmesh_nlopt_objective");
     }
   // Increment the iteration count.
   solver->get_iteration_count()++;
   // Possibly print the current value of the objective function
   if (solver->verbose)
     libMesh::out << objective << std::endl;
   return objective;
 }
Member Data Documentation
const Parallel::Communicator& libMesh::ParallelObject::_communicator protected inherited
Definition at line 105 of file parallel_object.h.
Referenced by libMesh::EquationSystems::build_parallel_solution_vector(), libMesh::ParallelObject::comm(), libMesh::EquationSystems::get_solution(), libMesh::ParallelObject::n_processors(), libMesh::ParallelObject::operator=(), and libMesh::ParallelObject::processor_id().
template<typename T> double libMesh::NloptOptimizationSolver< T >::_constraints_tolerance protected
NLopt requires us to specify a tolerance for the constraints.
Definition at line 149 of file nlopt_optimization_solver.h.
Referenced by libMesh::NloptOptimizationSolver< T >::solve().
ReferenceCounter::Counts libMesh::ReferenceCounter::_counts static protected inherited
Actually holds the data.
Definition at line 124 of file reference_counter.h.
Referenced by libMesh::ReferenceCounter::get_info(), libMesh::ReferenceCounter::increment_constructor_count(), and libMesh::ReferenceCounter::increment_destructor_count().
bool libMesh::ReferenceCounter::_enable_print_counter = true static protected inherited
Flag to control whether reference count information is printed when print_info is called.
Definition at line 143 of file reference_counter.h.
Referenced by libMesh::ReferenceCounter::disable_print_counter_info(), libMesh::ReferenceCounter::enable_print_counter_info(), and libMesh::ReferenceCounter::print_info().
template<typename T > bool libMesh::OptimizationSolver< T >::_is_initialized protected inherited
Flag indicating if the data structures have been initialized.
Definition at line 204 of file optimization_solver.h.
Referenced by libMesh::TaoOptimizationSolver< T >::clear(), libMesh::NloptOptimizationSolver< T >::clear(), libMesh::TaoOptimizationSolver< T >::init(), libMesh::NloptOptimizationSolver< T >::init(), and libMesh::OptimizationSolver< T >::initialized().
template<typename T> unsigned libMesh::NloptOptimizationSolver< T >::_iteration_count protected
Stores the current iteration index (incremented at each call of __libmesh_nlopt_objective).
Definition at line 144 of file nlopt_optimization_solver.h.
Referenced by libMesh::NloptOptimizationSolver< T >::get_iteration_count(), and libMesh::NloptOptimizationSolver< T >::solve().
Threads::spin_mutex libMesh::ReferenceCounter::_mutex static protected inherited
Mutual exclusion object to enable thread-safe reference counting.
Definition at line 137 of file reference_counter.h.
Threads::atomic< unsigned int > libMesh::ReferenceCounter::_n_objects static protected inherited
The number of objects. Print the reference count information when the number returns to 0.
Definition at line 132 of file reference_counter.h.
Referenced by libMesh::ReferenceCounter::n_objects(), libMesh::ReferenceCounter::ReferenceCounter(), and libMesh::ReferenceCounter::~ReferenceCounter().
template<typename T> std::map< std::string, nlopt_algorithm > libMesh::NloptOptimizationSolver< T >::_nlopt_algorithms = NloptOptimizationSolver<T>::build_map() static private
Definition at line 174 of file nlopt_optimization_solver.h.
Referenced by libMesh::NloptOptimizationSolver< T >::init().
template<typename T> nlopt_opt libMesh::NloptOptimizationSolver< T >::_opt protected
Optimization solver context
Definition at line 134 of file nlopt_optimization_solver.h.
Referenced by libMesh::NloptOptimizationSolver< T >::clear(), libMesh::NloptOptimizationSolver< T >::get_nlopt_object(), libMesh::NloptOptimizationSolver< T >::init(), and libMesh::NloptOptimizationSolver< T >::solve().
template<typename T> nlopt_result libMesh::NloptOptimizationSolver< T >::_result protected
Store the result (i.e. convergence/divergence) for the most recent NLopt solve.
Definition at line 139 of file nlopt_optimization_solver.h.
Referenced by libMesh::NloptOptimizationSolver< T >::get_converged_reason(), and libMesh::NloptOptimizationSolver< T >::solve().
template<typename T > sys_type& libMesh::OptimizationSolver< T >::_system protected inherited
A reference to the system we are solving.
Definition at line 199 of file optimization_solver.h.
Referenced by libMesh::OptimizationSolver< T >::system().
template<typename T > OptimizationSystem::ComputeEqualityConstraintsJacobian* libMesh::OptimizationSolver< T >::equality_constraints_jacobian_object inherited
Object that computes the Jacobian of C_eq(X).
Definition at line 149 of file optimization_solver.h.
Referenced by libMesh::__libmesh_nlopt_equality_constraints(), libMesh::__libmesh_tao_equality_constraints_jacobian(), and libMesh::TaoOptimizationSolver< T >::solve().
template<typename T > OptimizationSystem::ComputeEqualityConstraints* libMesh::OptimizationSolver< T >::equality_constraints_object inherited
Object that computes the equality constraints vector C_eq(X). This will lead to the constraints C_eq(X) = 0 being imposed.
Definition at line 144 of file optimization_solver.h.
Referenced by libMesh::__libmesh_nlopt_equality_constraints(), libMesh::__libmesh_tao_equality_constraints(), libMesh::TaoOptimizationSolver< T >::solve(), and libMesh::NloptOptimizationSolver< T >::solve().
template<typename T > OptimizationSystem::ComputeGradient* libMesh::OptimizationSolver< T >::gradient_object inherited
Object that computes the gradient grad_f(X) of the objective function at the input iterate X.
Definition at line 132 of file optimization_solver.h.
Referenced by libMesh::__libmesh_nlopt_objective(), libMesh::__libmesh_tao_gradient(), and libMesh::TaoOptimizationSolver< T >::solve().
template<typename T > OptimizationSystem::ComputeHessian* libMesh::OptimizationSolver< T >::hessian_object inherited
Object that computes the Hessian H_f(X) of the objective function at the input iterate X.
Definition at line 138 of file optimization_solver.h.
Referenced by libMesh::__libmesh_tao_hessian(), and libMesh::TaoOptimizationSolver< T >::solve().
template<typename T > OptimizationSystem::ComputeInequalityConstraintsJacobian* libMesh::OptimizationSolver< T >::inequality_constraints_jacobian_object inherited
Object that computes the Jacobian of C_ineq(X).
Definition at line 160 of file optimization_solver.h.
Referenced by libMesh::__libmesh_nlopt_inequality_constraints(), libMesh::__libmesh_tao_inequality_constraints_jacobian(), and libMesh::TaoOptimizationSolver< T >::solve().
template<typename T > OptimizationSystem::ComputeInequalityConstraints* libMesh::OptimizationSolver< T >::inequality_constraints_object inherited
Object that computes the inequality constraints vector C_ineq(X). This will lead to the constraints C_ineq(X) >= 0 being imposed.
Definition at line 155 of file optimization_solver.h.
Referenced by libMesh::__libmesh_nlopt_inequality_constraints(), libMesh::__libmesh_tao_inequality_constraints(), libMesh::TaoOptimizationSolver< T >::solve(), and libMesh::NloptOptimizationSolver< T >::solve().
template<typename T > OptimizationSystem::ComputeLowerAndUpperBounds* libMesh::OptimizationSolver< T >::lower_and_upper_bounds_object inherited
Object that computes the lower and upper bounds vectors.
Definition at line 165 of file optimization_solver.h.
Referenced by libMesh::TaoOptimizationSolver< T >::solve(), and libMesh::NloptOptimizationSolver< T >::solve().
template<typename T > unsigned int libMesh::OptimizationSolver< T >::max_objective_function_evaluations inherited
Maximum number of objective function evaluations allowed.
Definition at line 182 of file optimization_solver.h.
Referenced by libMesh::TaoOptimizationSolver< T >::solve(), and libMesh::NloptOptimizationSolver< T >::solve().
template<typename T > Real libMesh::OptimizationSolver< T >::objective_function_relative_tolerance inherited
Required change in objective function which signals convergence.
Definition at line 187 of file optimization_solver.h.
Referenced by libMesh::TaoOptimizationSolver< T >::solve(), and libMesh::NloptOptimizationSolver< T >::solve().
template<typename T > OptimizationSystem::ComputeObjective* libMesh::OptimizationSolver< T >::objective_object inherited
Object that computes the objective function f(X) at the input iterate X.
Definition at line 126 of file optimization_solver.h.
Referenced by libMesh::__libmesh_nlopt_objective(), libMesh::__libmesh_tao_objective(), libMesh::TaoOptimizationSolver< T >::solve(), and libMesh::NloptOptimizationSolver< T >::solve().
template<typename T > bool libMesh::OptimizationSolver< T >::verbose inherited
Control how much is output from the OptimizationSolver as it's running.
Definition at line 192 of file optimization_solver.h.
Referenced by libMesh::__libmesh_nlopt_objective().
The documentation for this class was generated from the following files:
nlopt_optimization_solver.h
nlopt_optimization_solver.C