libMesh: libMesh::MeshSerializer Class Reference
SomeWebsiteLogo
libMesh::MeshSerializer Class Reference
#include <mesh_serializer.h>
Public Member Functions
MeshSerializer (MeshBase &mesh, bool need_serial=true)
~MeshSerializer ()
Private Attributes
MeshBase & _mesh
bool reparallelize
Detailed Description
Temporarily serialize a ParallelMesh for output; a distributed mesh is allgathered by the MeshSerializer constructor if need_serial is true, then remote elements are deleted again by the destructor.
Definition at line 38 of file mesh_serializer.h.
Constructor & Destructor Documentation
libMesh::MeshSerializer::MeshSerializer (MeshBase & mesh, bool need_serial = true)
Definition at line 27 of file mesh_serializer.C.
References _mesh, libMesh::MeshBase::allgather(), libMesh::ParallelObject::comm(), libMesh::MeshBase::is_serial(), libMesh::libmesh_parallel_only(), and reparallelize.
                                                                :
   _mesh(mesh),
   reparallelize(false)
 {
   libmesh_parallel_only(mesh.comm());
   if (need_serial && !_mesh.is_serial()) {
     reparallelize = true;
     _mesh.allgather();
   }
 }
libMesh::MeshSerializer::~MeshSerializer ()
Definition at line 40 of file mesh_serializer.C.
References _mesh, libMesh::MeshBase::delete_remote_elements(), and reparallelize.
 {
   if (reparallelize)
     _mesh.delete_remote_elements();
 }
Member Data Documentation
MeshBase& libMesh::MeshSerializer::_mesh private
Definition at line 46 of file mesh_serializer.h.
Referenced by MeshSerializer(), and ~MeshSerializer().
bool libMesh::MeshSerializer::reparallelize private
Definition at line 47 of file mesh_serializer.h.
Referenced by MeshSerializer(), and ~MeshSerializer().
The documentation for this class was generated from the following files:
mesh_serializer.h
mesh_serializer.C