libMesh: libMesh::DiffContext Class Reference
SomeWebsiteLogo
libMesh::DiffContext Class Reference
#include <diff_context.h>
Public Types
typedef std::map< const NumericVector< Number > *, std::pair< DenseVector< Number >, std::vector< std::unique_ptr< DenseSubVector< Number > > > > >::iterator localized_vectors_iterator
Public Member Functions
DiffContext (const System &)
virtual ~DiffContext ()
virtual void elem_reinit (Real)
virtual void elem_side_reinit (Real)
virtual void elem_edge_reinit (Real)
virtual void nonlocal_reinit (Real)
unsigned int n_vars () const
const System & get_system () const
const DenseVector< Number > & get_elem_solution () const
DenseVector< Number > & get_elem_solution ()
const DenseSubVector< Number > & get_elem_solution (unsigned int var) const
DenseSubVector< Number > & get_elem_solution (unsigned int var)
const DenseVector< Number > & get_elem_solution_rate () const
DenseVector< Number > & get_elem_solution_rate ()
const DenseSubVector< Number > & get_elem_solution_rate (unsigned int var) const
DenseSubVector< Number > & get_elem_solution_rate (unsigned int var)
const DenseVector< Number > & get_elem_solution_accel () const
DenseVector< Number > & get_elem_solution_accel ()
const DenseSubVector< Number > & get_elem_solution_accel (unsigned int var) const
DenseSubVector< Number > & get_elem_solution_accel (unsigned int var)
const DenseVector< Number > & get_elem_fixed_solution () const
DenseVector< Number > & get_elem_fixed_solution ()
const DenseSubVector< Number > & get_elem_fixed_solution (unsigned int var) const
DenseSubVector< Number > & get_elem_fixed_solution (unsigned int var)
const DenseVector< Number > & get_elem_residual () const
DenseVector< Number > & get_elem_residual ()
const DenseSubVector< Number > & get_elem_residual (unsigned int var) const
DenseSubVector< Number > & get_elem_residual (unsigned int var)
const DenseMatrix< Number > & get_elem_jacobian () const
DenseMatrix< Number > & get_elem_jacobian ()
const DenseSubMatrix< Number > & get_elem_jacobian (unsigned int var1, unsigned int var2) const
DenseSubMatrix< Number > & get_elem_jacobian (unsigned int var1, unsigned int var2)
const std::vector< Number > & get_qois () const
std::vector< Number > & get_qois ()
const std::vector< DenseVector< Number > > & get_qoi_derivatives () const
std::vector< DenseVector< Number > > & get_qoi_derivatives ()
const DenseSubVector< Number > & get_qoi_derivatives (std::size_t qoi, unsigned int var) const
DenseSubVector< Number > & get_qoi_derivatives (std::size_t qoi, unsigned int var)
const std::vector< dof_id_type > & get_dof_indices () const
std::vector< dof_id_type > & get_dof_indices ()
const std::vector< dof_id_type > & get_dof_indices (unsigned int var) const
std::vector< dof_id_type > & get_dof_indices (unsigned int var)
unsigned int n_dof_indices () const
unsigned int n_dof_indices (unsigned int var) const
Real get_system_time () const
Real get_time () const
void set_time (Real time_in)
Real get_elem_solution_derivative () const
Real get_elem_solution_rate_derivative () const
Real get_elem_solution_accel_derivative () const
Real get_fixed_solution_derivative () const
bool is_adjoint () const
bool & is_adjoint ()
void set_deltat_pointer (Real *dt)
Real get_deltat_value ()
void add_localized_vector (NumericVector< Number > &localized_vector, const System &sys)
DenseVector< Number > & get_localized_vector (const NumericVector< Number > &localized_vector)
const DenseVector< Number > & get_localized_vector (const NumericVector< Number > &localized_vector) const
DenseSubVector< Number > & get_localized_subvector (const NumericVector< Number > &localized_vector, unsigned int var)
const DenseSubVector< Number > & get_localized_subvector (const NumericVector< Number > &localized_vector, unsigned int var) const
Public Attributes
Real time
const Real system_time
Real elem_solution_derivative
Real elem_solution_rate_derivative
Real elem_solution_accel_derivative
Real fixed_solution_derivative
Protected Attributes
std::map< const NumericVector< Number > *, std::pair< DenseVector< Number >, std::vector< std::unique_ptr< DenseSubVector< Number > > > > > _localized_vectors
DenseVector< Number > _elem_solution
std::vector< std::unique_ptr< DenseSubVector< Number > > > _elem_subsolutions
DenseVector< Number > _elem_solution_rate
std::vector< std::unique_ptr< DenseSubVector< Number > > > _elem_subsolution_rates
DenseVector< Number > _elem_solution_accel
std::vector< std::unique_ptr< DenseSubVector< Number > > > _elem_subsolution_accels
DenseVector< Number > _elem_fixed_solution
std::vector< std::unique_ptr< DenseSubVector< Number > > > _elem_fixed_subsolutions
DenseVector< Number > _elem_residual
DenseMatrix< Number > _elem_jacobian
std::vector< Number > _elem_qoi
std::vector< DenseVector< Number > > _elem_qoi_derivative
std::vector< std::vector< std::unique_ptr< DenseSubVector< Number > > > > _elem_qoi_subderivatives
std::vector< std::unique_ptr< DenseSubVector< Number > > > _elem_subresiduals
std::vector< std::vector< std::unique_ptr< DenseSubMatrix< Number > > > > _elem_subjacobians
std::vector< dof_id_type > _dof_indices
std::vector< std::vector< dof_id_type > > _dof_indices_var
Private Attributes
Real * _deltat
const System & _system
bool _is_adjoint
Detailed Description
This class provides all data required for a physics package (e.g. a DifferentiableSystem subclass) to perform local element residual and jacobian integrations.
This class is part of the new DifferentiableSystem framework, which is still experimental. Users of this framework should beware of bugs and future API changes.
Author
Roy H. Stogner
Date
2009
Definition at line 55 of file diff_context.h.
Member Typedef Documentation
localized_vectors_iterator
typedef std::map<const NumericVector<Number> *, std::pair<DenseVector<Number>, std::vector<std::unique_ptr<DenseSubVector<Number> > > > >::iterator libMesh::DiffContext::localized_vectors_iterator
Typedef for the localized_vectors iterator
Definition at line 544 of file diff_context.h.
Constructor & Destructor Documentation
DiffContext()
libMesh::DiffContext::DiffContext (const System & sys) explicit
Constructor. Optionally initializes required data structures.
Definition at line 30 of file diff_context.C.
References _elem_fixed_solution, _elem_fixed_subsolutions, _elem_jacobian, _elem_qoi, _elem_qoi_derivative, _elem_qoi_subderivatives, _elem_residual, _elem_solution, _elem_solution_accel, _elem_solution_rate, _elem_subjacobians, _elem_subresiduals, _elem_subsolution_accels, _elem_subsolution_rates, _elem_subsolutions, libMesh::DifferentiablePhysics::get_second_order_vars(), libMesh::DifferentiableSystem::get_time_solver(), libMesh::TimeSolver::is_steady(), libMesh::System::n_vars(), libMesh::System::qoi, libMesh::UnsteadySolver::time_order(), and libMesh::System::use_fixed_solution.
                                             :
   time(sys.time),
   system_time(sys.time),
   elem_solution_derivative(1.),
   elem_solution_rate_derivative(1.),
   elem_solution_accel_derivative(1.),
   fixed_solution_derivative(0.),
   _dof_indices_var(sys.n_vars()),
   _deltat(nullptr),
   _system(sys),
   _is_adjoint(false)
 {
   // Finally initialize solution/residual/jacobian data structures
   unsigned int nv = sys.n_vars();
   _elem_subsolutions.reserve(nv);
   _elem_subresiduals.reserve(nv);
   _elem_subjacobians.resize(nv);
   _elem_subsolution_rates.reserve(nv);
   _elem_subsolution_accels.reserve(nv);
   if (sys.use_fixed_solution)
     _elem_fixed_subsolutions.reserve(nv);
   // If the user resizes sys.qoi, it will invalidate us
   std::size_t n_qoi = sys.qoi.size();
   _elem_qoi.resize(n_qoi);
   _elem_qoi_derivative.resize(n_qoi);
   _elem_qoi_subderivatives.resize(n_qoi);
   for (std::size_t q=0; q != n_qoi; ++q)
     _elem_qoi_subderivatives[q].reserve(nv);
   for (unsigned int i=0; i != nv; ++i)
     {
       _elem_subsolutions.emplace_back(libmesh_make_unique<DenseSubVector<Number>>(_elem_solution));
       _elem_subresiduals.emplace_back(libmesh_make_unique<DenseSubVector<Number>>(_elem_residual));
       for (std::size_t q=0; q != n_qoi; ++q)
         _elem_qoi_subderivatives[q].emplace_back(libmesh_make_unique<DenseSubVector<Number>>(_elem_qoi_derivative[q]));
       _elem_subjacobians[i].reserve(nv);
       // Only make space for these if we're using DiffSystem
       // This is assuming *only* DiffSystem is using elem_solution_rate/accel
       const DifferentiableSystem * diff_system = dynamic_cast<const DifferentiableSystem *>(&sys);
       if (diff_system)
         {
           // Now, we only need these if the solver is unsteady
           if (!diff_system->get_time_solver().is_steady())
             {
               _elem_subsolution_rates.emplace_back(libmesh_make_unique<DenseSubVector<Number>>(_elem_solution_rate));
               // We only need accel space if the TimeSolver is second order
               const UnsteadySolver & time_solver = cast_ref<const UnsteadySolver &>(diff_system->get_time_solver());
               if (time_solver.time_order() >= 2 || !diff_system->get_second_order_vars().empty())
                 _elem_subsolution_accels.emplace_back(libmesh_make_unique<DenseSubVector<Number>>(_elem_solution_accel));
             }
         }
       if (sys.use_fixed_solution)
         _elem_fixed_subsolutions.emplace_back(libmesh_make_unique<DenseSubVector<Number>>(_elem_fixed_solution));
       for (unsigned int j=0; j != nv; ++j)
         _elem_subjacobians[i].emplace_back(libmesh_make_unique<DenseSubMatrix<Number>>(_elem_jacobian));
     }
 }
~DiffContext()
libMesh::DiffContext::~DiffContext () virtual
Destructor.
Definition at line 98 of file diff_context.C.
 {
 }
Member Function Documentation
add_localized_vector()
void libMesh::DiffContext::add_localized_vector (NumericVector< Number > & localized_vector, const System & sys)
Adds a vector to the map of localized vectors. We can later evaluate interior_values, interior_gradients and side_values for these fields these vectors represent.
Definition at line 119 of file diff_context.C.
References _localized_vectors, and libMesh::System::n_vars().
 {
   // Make an empty pair keyed with a reference to this _localized_vector
   _localized_vectors[&localized_vector] = std::make_pair(DenseVector<Number>(), std::vector<std::unique_ptr<DenseSubVector<Number>>>());
   unsigned int nv = sys.n_vars();
   _localized_vectors[&localized_vector].second.reserve(nv);
   // Fill the DenseSubVector with nv copies of DenseVector
   for (unsigned int i=0; i != nv; ++i)
     _localized_vectors[&localized_vector].second.emplace_back(libmesh_make_unique<DenseSubVector<Number>>(_localized_vectors[&localized_vector].first));
 }
elem_edge_reinit()
virtual void libMesh::DiffContext::elem_edge_reinit (Real) inline virtual
Gives derived classes the opportunity to reinitialize data needed for an edge integration at a new point within a timestep
Reimplemented in libMesh::FEMContext.
Definition at line 88 of file diff_context.h.
 {}
elem_reinit()
virtual void libMesh::DiffContext::elem_reinit (Real) inline virtual
Gives derived classes the opportunity to reinitialize data (FE objects in FEMSystem, for example) needed for an interior integration at a new point within a timestep
Reimplemented in libMesh::FEMContext.
Definition at line 76 of file diff_context.h.
Referenced by libMesh::EulerSolver::element_residual(), libMesh::Euler2Solver::element_residual(), and libMesh::NewmarkSolver::element_residual().
 {}
elem_side_reinit()
virtual void libMesh::DiffContext::elem_side_reinit (Real) inline virtual
Gives derived classes the opportunity to reinitialize data needed for a side integration at a new point within a timestep
Reimplemented in libMesh::FEMContext.
Definition at line 82 of file diff_context.h.
Referenced by libMesh::EulerSolver::side_residual(), libMesh::Euler2Solver::side_residual(), and libMesh::NewmarkSolver::side_residual().
 {}
get_deltat_value()
Real libMesh::DiffContext::get_deltat_value ()
Returns
The value currently pointed to by this class's _deltat member
Definition at line 111 of file diff_context.C.
References _deltat.
Referenced by libMesh::FEMContext::_update_time_from_system().
 {
   libmesh_assert(_deltat);
   return *_deltat;
 }
get_dof_indices() [1/4]
const std::vector<dof_id_type>& libMesh::DiffContext::get_dof_indices () const inline
Accessor for element dof indices
Definition at line 367 of file diff_context.h.
References _dof_indices.
Referenced by libMesh::EulerSolver::_general_residual(), libMesh::Euler2Solver::_general_residual(), libMesh::NewmarkSolver::_general_residual(), libMesh::FirstOrderUnsteadySolver::compute_second_order_eqns(), libMesh::FEMContext::fixed_point_gradient(), libMesh::FEMContext::fixed_point_hessian(), libMesh::FEMContext::fixed_point_value(), libMesh::VectorSetAction< Val >::insert(), libMesh::MatrixFillAction< ValIn, ValOut >::insert(), libMesh::FEMContext::interior_curl(), libMesh::FEMContext::interior_div(), libMesh::FEMContext::interior_gradients(), libMesh::FEMContext::interior_hessians(), libMesh::FEMContext::interior_values(), libMesh::FEMSystem::mesh_position_get(), libMesh::DGFEMContext::neighbor_side_fe_reinit(), libMesh::FEMSystem::numerical_jacobian(), libMesh::GenericProjector< FFunctor, GFunctor, FValue, ProjectionAction >::operator()(), libMesh::FEMContext::point_curl(), libMesh::FEMContext::point_gradient(), libMesh::FEMContext::point_hessian(), libMesh::FEMContext::point_value(), libMesh::FEMContext::pre_fe_reinit(), libMesh::FEMContext::side_gradient(), libMesh::FEMContext::side_gradients(), libMesh::FEMContext::side_hessians(), libMesh::FEMContext::side_values(), libMesh::FEMContext::some_gradient(), libMesh::FEMContext::some_hessian(), and libMesh::FEMContext::some_value().
   { return _dof_indices; }
get_dof_indices() [2/4]
std::vector<dof_id_type>& libMesh::DiffContext::get_dof_indices () inline
Non-const accessor for element dof indices
Definition at line 373 of file diff_context.h.
References _dof_indices.
   { return _dof_indices; }
get_dof_indices() [3/4]
const std::vector<dof_id_type>& libMesh::DiffContext::get_dof_indices (unsigned int var) const inline
Accessor for element dof indices of a particular variable corresponding to the index argument.
Definition at line 380 of file diff_context.h.
References _dof_indices_var.
   {
     libmesh_assert_greater(_dof_indices_var.size(), var);
     return _dof_indices_var[var];
   }
get_dof_indices() [4/4]
std::vector<dof_id_type>& libMesh::DiffContext::get_dof_indices (unsigned int var) inline
Accessor for element dof indices of a particular variable corresponding to the index argument.
Definition at line 390 of file diff_context.h.
References _dof_indices_var.
   {
     libmesh_assert_greater(_dof_indices_var.size(), var);
     return _dof_indices_var[var];
   }
get_elem_fixed_solution() [1/4]
const DenseVector<Number>& libMesh::DiffContext::get_elem_fixed_solution () const inline
Accessor for element fixed solution.
Definition at line 215 of file diff_context.h.
References _elem_fixed_solution.
Referenced by libMesh::EulerSolver::_general_residual(), libMesh::Euler2Solver::_general_residual(), libMesh::SteadySolver::_general_residual(), libMesh::NewmarkSolver::_general_residual(), libMesh::FEMContext::fixed_interior_gradient(), libMesh::FEMContext::fixed_interior_hessian(), libMesh::FEMContext::fixed_interior_value(), libMesh::FEMContext::fixed_point_gradient(), libMesh::FEMContext::fixed_point_hessian(), libMesh::FEMContext::fixed_point_value(), libMesh::FEMContext::fixed_side_gradient(), libMesh::FEMContext::fixed_side_hessian(), libMesh::FEMContext::fixed_side_value(), and libMesh::FEMContext::pre_fe_reinit().
   { return _elem_fixed_solution; }
get_elem_fixed_solution() [2/4]
DenseVector<Number>& libMesh::DiffContext::get_elem_fixed_solution () inline
Non-const accessor for element fixed solution.
Definition at line 221 of file diff_context.h.
References _elem_fixed_solution.
   { return _elem_fixed_solution; }
get_elem_fixed_solution() [3/4]
const DenseSubVector<Number>& libMesh::DiffContext::get_elem_fixed_solution (unsigned int var) const inline
Accessor for element fixed solution of a particular variable corresponding to the variable index argument.
Definition at line 228 of file diff_context.h.
References _elem_fixed_subsolutions.
   {
     libmesh_assert_greater(_elem_fixed_subsolutions.size(), var);
     libmesh_assert(_elem_fixed_subsolutions[var]);
     return *(_elem_fixed_subsolutions[var]);
   }
get_elem_fixed_solution() [4/4]
DenseSubVector<Number>& libMesh::DiffContext::get_elem_fixed_solution (unsigned int var) inline
Accessor for element fixed solution of a particular variable corresponding to the variable index argument.
Definition at line 239 of file diff_context.h.
References _elem_fixed_subsolutions.
   {
     libmesh_assert_greater(_elem_fixed_subsolutions.size(), var);
     libmesh_assert(_elem_fixed_subsolutions[var]);
     return *(_elem_fixed_subsolutions[var]);
   }
get_elem_jacobian() [1/4]
const DenseMatrix<Number>& libMesh::DiffContext::get_elem_jacobian () const inline
Const accessor for element Jacobian.
Definition at line 283 of file diff_context.h.
References _elem_jacobian.
Referenced by libMesh::EulerSolver::_general_residual(), libMesh::Euler2Solver::_general_residual(), libMesh::NewmarkSolver::_general_residual(), libMesh::FEMSystem::assembly(), libMesh::FirstOrderUnsteadySolver::compute_second_order_eqns(), libMesh::EigenTimeSolver::element_residual(), libMesh::EigenTimeSolver::nonlocal_residual(), libMesh::FEMSystem::numerical_jacobian(), libMesh::FEMContext::pre_fe_reinit(), and libMesh::EigenTimeSolver::side_residual().
   { return _elem_jacobian; }
get_elem_jacobian() [2/4]
DenseMatrix<Number>& libMesh::DiffContext::get_elem_jacobian () inline
Non-const accessor for element Jacobian.
Definition at line 289 of file diff_context.h.
References _elem_jacobian.
   { return _elem_jacobian; }
get_elem_jacobian() [3/4]
const DenseSubMatrix<Number>& libMesh::DiffContext::get_elem_jacobian (unsigned int var1, unsigned int var2) const inline
Const accessor for element Jacobian of particular variables corresponding to the variable index arguments.
Definition at line 296 of file diff_context.h.
References _elem_subjacobians.
   {
     libmesh_assert_greater(_elem_subjacobians.size(), var1);
     libmesh_assert_greater(_elem_subjacobians[var1].size(), var2);
     libmesh_assert(_elem_subjacobians[var1][var2]);
     return *(_elem_subjacobians[var1][var2]);
   }
get_elem_jacobian() [4/4]
DenseSubMatrix<Number>& libMesh::DiffContext::get_elem_jacobian (unsigned int var1, unsigned int var2) inline
Non-const accessor for element Jacobian of particular variables corresponding to the variable index arguments.
Definition at line 308 of file diff_context.h.
References _elem_subjacobians.
   {
     libmesh_assert_greater(_elem_subjacobians.size(), var1);
     libmesh_assert_greater(_elem_subjacobians[var1].size(), var2);
     libmesh_assert(_elem_subjacobians[var1][var2]);
     return *(_elem_subjacobians[var1][var2]);
   }
get_elem_residual() [1/4]
const DenseVector<Number>& libMesh::DiffContext::get_elem_residual () const inline
Const accessor for element residual.
Definition at line 249 of file diff_context.h.
References _elem_residual.
Referenced by libMesh::Euler2Solver::_general_residual(), libMesh::FEMSystem::assembly(), libMesh::FirstOrderUnsteadySolver::compute_second_order_eqns(), libMesh::FEMSystem::numerical_jacobian(), and libMesh::FEMContext::pre_fe_reinit().
   { return _elem_residual; }
get_elem_residual() [2/4]
DenseVector<Number>& libMesh::DiffContext::get_elem_residual () inline
Non-const accessor for element residual.
Definition at line 255 of file diff_context.h.
References _elem_residual.
   { return _elem_residual; }
get_elem_residual() [3/4]
const DenseSubVector<Number>& libMesh::DiffContext::get_elem_residual (unsigned int var) const inline
Const accessor for element residual of a particular variable corresponding to the variable index argument.
Definition at line 262 of file diff_context.h.
References _elem_subresiduals.
   {
     libmesh_assert_greater(_elem_subresiduals.size(), var);
     libmesh_assert(_elem_subresiduals[var]);
     return *(_elem_subresiduals[var]);
   }
get_elem_residual() [4/4]
DenseSubVector<Number>& libMesh::DiffContext::get_elem_residual (unsigned int var) inline
Non-const accessor for element residual of a particular variable corresponding to the variable index argument.
Definition at line 273 of file diff_context.h.
References _elem_subresiduals.
   {
     libmesh_assert_greater(_elem_subresiduals.size(), var);
     libmesh_assert(_elem_subresiduals[var]);
     return *(_elem_subresiduals[var]);
   }
get_elem_solution() [1/4]
const DenseVector<Number>& libMesh::DiffContext::get_elem_solution () const inline
Accessor for element solution.
Definition at line 111 of file diff_context.h.
References _elem_solution.
Referenced by libMesh::FEMContext::_do_elem_position_set(), libMesh::EulerSolver::_general_residual(), libMesh::Euler2Solver::_general_residual(), libMesh::SteadySolver::_general_residual(), libMesh::NewmarkSolver::_general_residual(), libMesh::FEMContext::elem_position_get(), libMesh::FEMContext::interior_curl(), libMesh::FEMContext::interior_div(), libMesh::FEMContext::interior_gradient(), libMesh::FEMContext::interior_hessian(), libMesh::FEMContext::interior_value(), libMesh::FEMSystem::mesh_position_get(), libMesh::FEMSystem::numerical_jacobian(), libMesh::FEMContext::point_curl(), libMesh::FEMContext::point_gradient(), libMesh::FEMContext::point_hessian(), libMesh::FEMContext::point_value(), libMesh::FEMContext::pre_fe_reinit(), libMesh::FEMContext::side_gradient(), libMesh::FEMContext::side_hessian(), and libMesh::FEMContext::side_value().
   { return _elem_solution; }
get_elem_solution() [2/4]
DenseVector<Number>& libMesh::DiffContext::get_elem_solution () inline
Non-const accessor for element solution.
Definition at line 117 of file diff_context.h.
References _elem_solution.
   { return _elem_solution; }
get_elem_solution() [3/4]
const DenseSubVector<Number>& libMesh::DiffContext::get_elem_solution (unsigned int var) const inline
Accessor for element solution of a particular variable corresponding to the variable index argument.
Definition at line 124 of file diff_context.h.
References _elem_subsolutions.
   {
     libmesh_assert_greater(_elem_subsolutions.size(), var);
     libmesh_assert(_elem_subsolutions[var]);
     return *(_elem_subsolutions[var]);
   }
get_elem_solution() [4/4]
DenseSubVector<Number>& libMesh::DiffContext::get_elem_solution (unsigned int var) inline
Accessor for element solution of a particular variable corresponding to the variable index argument.
Definition at line 135 of file diff_context.h.
References _elem_subsolutions.
   {
     libmesh_assert_greater(_elem_subsolutions.size(), var);
     libmesh_assert(_elem_subsolutions[var]);
     return *(_elem_subsolutions[var]);
   }
get_elem_solution_accel() [1/4]
const DenseVector<Number>& libMesh::DiffContext::get_elem_solution_accel () const inline
Accessor for element solution accel of change w.r.t. time.
Definition at line 180 of file diff_context.h.
References _elem_solution_accel.
Referenced by libMesh::NewmarkSolver::_general_residual(), libMesh::FEMContext::interior_accel(), libMesh::FEMContext::pre_fe_reinit(), libMesh::FirstOrderUnsteadySolver::prepare_accel(), and libMesh::FEMContext::side_accel().
   { return _elem_solution_accel; }
get_elem_solution_accel() [2/4]
DenseVector<Number>& libMesh::DiffContext::get_elem_solution_accel () inline
Non-const accessor for element solution accel of change w.r.t. time.
Definition at line 187 of file diff_context.h.
References _elem_solution_accel.
   { return _elem_solution_accel; }
get_elem_solution_accel() [3/4]
const DenseSubVector<Number>& libMesh::DiffContext::get_elem_solution_accel (unsigned int var) const inline
Accessor for element solution accel for a particular variable corresponding to the variable index argument.
Definition at line 194 of file diff_context.h.
References _elem_subsolution_accels.
   {
     libmesh_assert_greater(_elem_subsolution_accels.size(), var);
     libmesh_assert(_elem_subsolution_accels[var]);
     return *(_elem_subsolution_accels[var]);
   }
get_elem_solution_accel() [4/4]
DenseSubVector<Number>& libMesh::DiffContext::get_elem_solution_accel (unsigned int var) inline
Accessor for element solution accel for a particular variable corresponding to the variable index argument.
Definition at line 205 of file diff_context.h.
References _elem_subsolution_accels.
   {
     libmesh_assert_greater(_elem_subsolution_accels.size(), var);
     libmesh_assert(_elem_subsolution_accels[var]);
     return *(_elem_subsolution_accels[var]);
   }
get_elem_solution_accel_derivative()
Real libMesh::DiffContext::get_elem_solution_accel_derivative () const inline
The derivative of the current elem_solution_accel w.r.t. the unknown solution. Corresponding Jacobian contributions should be multiplied by this amount, or may be skipped if get_elem_solution_accel_derivative() is 0.
Definition at line 454 of file diff_context.h.
References elem_solution_accel_derivative.
   { return elem_solution_accel_derivative; }
get_elem_solution_derivative()
Real libMesh::DiffContext::get_elem_solution_derivative () const inline
The derivative of the current elem_solution w.r.t. the unknown solution. Corresponding Jacobian contributions should be multiplied by this amount, or may be skipped if get_elem_solution_derivative() is 0.
Definition at line 436 of file diff_context.h.
References elem_solution_derivative.
Referenced by libMesh::FirstOrderUnsteadySolver::compute_second_order_eqns().
   { return elem_solution_derivative; }
get_elem_solution_rate() [1/4]
const DenseVector<Number>& libMesh::DiffContext::get_elem_solution_rate () const inline
Accessor for element solution rate of change w.r.t. time.
Definition at line 145 of file diff_context.h.
References _elem_solution_rate.
Referenced by libMesh::EulerSolver::_general_residual(), libMesh::Euler2Solver::_general_residual(), libMesh::NewmarkSolver::_general_residual(), libMesh::FEMContext::interior_rate(), libMesh::FEMContext::pre_fe_reinit(), libMesh::FirstOrderUnsteadySolver::prepare_accel(), and libMesh::FEMContext::side_rate().
   { return _elem_solution_rate; }
get_elem_solution_rate() [2/4]
DenseVector<Number>& libMesh::DiffContext::get_elem_solution_rate () inline
Non-const accessor for element solution rate of change w.r.t. time.
Definition at line 152 of file diff_context.h.
References _elem_solution_rate.
   { return _elem_solution_rate; }
get_elem_solution_rate() [3/4]
const DenseSubVector<Number>& libMesh::DiffContext::get_elem_solution_rate (unsigned int var) const inline
Accessor for element solution rate for a particular variable corresponding to the variable index argument.
Definition at line 159 of file diff_context.h.
References _elem_subsolution_rates.
   {
     libmesh_assert_greater(_elem_subsolution_rates.size(), var);
     libmesh_assert(_elem_subsolution_rates[var]);
     return *(_elem_subsolution_rates[var]);
   }
get_elem_solution_rate() [4/4]
DenseSubVector<Number>& libMesh::DiffContext::get_elem_solution_rate (unsigned int var) inline
Accessor for element solution rate for a particular variable corresponding to the variable index argument.
Definition at line 170 of file diff_context.h.
References _elem_subsolution_rates.
   {
     libmesh_assert_greater(_elem_subsolution_rates.size(), var);
     libmesh_assert(_elem_subsolution_rates[var]);
     return *(_elem_subsolution_rates[var]);
   }
get_elem_solution_rate_derivative()
Real libMesh::DiffContext::get_elem_solution_rate_derivative () const inline
The derivative of the current elem_solution_rate w.r.t. the unknown solution. Corresponding Jacobian contributions should be multiplied by this amount, or may be skipped if get_elem_solution_rate_derivative() is 0.
Definition at line 445 of file diff_context.h.
References elem_solution_rate_derivative.
Referenced by libMesh::FirstOrderUnsteadySolver::compute_second_order_eqns(), and libMesh::FirstOrderUnsteadySolver::prepare_accel().
   { return elem_solution_rate_derivative; }
get_fixed_solution_derivative()
Real libMesh::DiffContext::get_fixed_solution_derivative () const inline
The derivative of the current fixed_elem_solution w.r.t. the unknown solution. Corresponding Jacobian contributions should be multiplied by this amount, or may be skipped if get_fixed_elem_solution_derivative() is 0.
Definition at line 463 of file diff_context.h.
References fixed_solution_derivative.
   { return fixed_solution_derivative; }
get_localized_subvector() [1/2]
DenseSubVector< Number > & libMesh::DiffContext::get_localized_subvector (const NumericVector< Number > & localized_vector, unsigned int var)
Return a reference to DenseSubVector localization of localized_vector at variable var contained in the _localized_vectors map
Definition at line 148 of file diff_context.C.
References _localized_vectors.
Referenced by libMesh::FEMContext::interior_gradients(), libMesh::FEMContext::interior_hessians(), libMesh::FEMContext::interior_values(), libMesh::FEMContext::side_gradients(), libMesh::FEMContext::side_hessians(), and libMesh::FEMContext::side_values().
 {
   return *_localized_vectors[&localized_vector].second[var];
 }
get_localized_subvector() [2/2]
const DenseSubVector< Number > & libMesh::DiffContext::get_localized_subvector (const NumericVector< Number > & localized_vector, unsigned int var) const
const accessible version of get_localized_subvector function
Definition at line 154 of file diff_context.C.
References _localized_vectors.
 {
   auto localized_vectors_it = _localized_vectors.find(&localized_vector);
   libmesh_assert(localized_vectors_it != _localized_vectors.end());
   return *localized_vectors_it->second.second[var];
 }
get_localized_vector() [1/2]
DenseVector< Number > & libMesh::DiffContext::get_localized_vector (const NumericVector< Number > & localized_vector)
Return a reference to DenseVector localization of localized_vector contained in the _localized_vectors map
Definition at line 134 of file diff_context.C.
References _localized_vectors.
 {
   return _localized_vectors[&localized_vector].first;
 }
get_localized_vector() [2/2]
const DenseVector< Number > & libMesh::DiffContext::get_localized_vector (const NumericVector< Number > & localized_vector) const
const accessible version of get_localized_vector function
Definition at line 140 of file diff_context.C.
References _localized_vectors.
 {
   auto localized_vectors_it = _localized_vectors.find(&localized_vector);
   libmesh_assert(localized_vectors_it != _localized_vectors.end());
   return localized_vectors_it->second.first;
 }
get_qoi_derivatives() [1/4]
const std::vector<DenseVector<Number> >& libMesh::DiffContext::get_qoi_derivatives () const inline
Const accessor for QoI derivatives.
Definition at line 331 of file diff_context.h.
References _elem_qoi_derivative.
Referenced by libMesh::FEMContext::pre_fe_reinit().
   { return _elem_qoi_derivative; }
get_qoi_derivatives() [2/4]
std::vector<DenseVector<Number> >& libMesh::DiffContext::get_qoi_derivatives () inline
Non-const accessor for QoI derivatives.
Definition at line 337 of file diff_context.h.
References _elem_qoi_derivative.
   { return _elem_qoi_derivative; }
get_qoi_derivatives() [3/4]
const DenseSubVector<Number>& libMesh::DiffContext::get_qoi_derivatives (std::size_t qoi, unsigned int var) const inline
Const accessor for QoI derivative of a particular qoi and variable corresponding to the index arguments.
Definition at line 344 of file diff_context.h.
References _elem_qoi_subderivatives.
   {
     libmesh_assert_greater(_elem_qoi_subderivatives.size(), qoi);
     libmesh_assert_greater(_elem_qoi_subderivatives[qoi].size(), var);
     libmesh_assert(_elem_qoi_subderivatives[qoi][var]);
     return *(_elem_qoi_subderivatives[qoi][var]);
   }
get_qoi_derivatives() [4/4]
DenseSubVector<Number>& libMesh::DiffContext::get_qoi_derivatives (std::size_t qoi, unsigned int var) inline
Non-const accessor for QoI derivative of a particular qoi and variable corresponding to the index arguments.
Definition at line 356 of file diff_context.h.
References _elem_qoi_subderivatives.
   {
     libmesh_assert_greater(_elem_qoi_subderivatives.size(), qoi);
     libmesh_assert_greater(_elem_qoi_subderivatives[qoi].size(), var);
     libmesh_assert(_elem_qoi_subderivatives[qoi][var]);
     return *(_elem_qoi_subderivatives[qoi][var]);
   }
get_qois() [1/2]
const std::vector<Number>& libMesh::DiffContext::get_qois () const inline
Const accessor for QoI vector.
Definition at line 319 of file diff_context.h.
References _elem_qoi.
   { return _elem_qoi; }
get_qois() [2/2]
std::vector<Number>& libMesh::DiffContext::get_qois () inline
Non-const accessor for QoI vector.
Definition at line 325 of file diff_context.h.
References _elem_qoi.
   { return _elem_qoi; }
get_system()
const System& libMesh::DiffContext::get_system () const inline
Accessor for associated system.
Definition at line 105 of file diff_context.h.
References _system.
Referenced by libMesh::FirstOrderUnsteadySolver::compute_second_order_eqns(), and libMesh::DGFEMContext::neighbor_side_fe_reinit().
   { return _system; }
get_system_time()
Real libMesh::DiffContext::get_system_time () const inline
Accessor for the time variable stored in the system class.
Definition at line 415 of file diff_context.h.
References system_time.
Referenced by libMesh::FEMContext::_update_time_from_system().
   { return system_time; }
get_time()
Real libMesh::DiffContext::get_time () const inline
Accessor for the time for which the current nonlinear_solution is defined.
Definition at line 421 of file diff_context.h.
References time.
   { return time; }
is_adjoint() [1/2]
bool libMesh::DiffContext::is_adjoint () const inline
Accessor for querying whether we need to do a primal or adjoint solve
Definition at line 470 of file diff_context.h.
References _is_adjoint.
Referenced by libMesh::FEMSystem::build_context().
   { return _is_adjoint; }
is_adjoint() [2/2]
bool& libMesh::DiffContext::is_adjoint () inline
Accessor for setting whether we need to do a primal or adjoint solve
Definition at line 477 of file diff_context.h.
References _is_adjoint.
   { return _is_adjoint; }
n_dof_indices() [1/2]
unsigned int libMesh::DiffContext::n_dof_indices () const inline
Total number of dof indices on the element
Definition at line 399 of file diff_context.h.
References _dof_indices.
   { return cast_int<unsigned int>(_dof_indices.size()); }
n_dof_indices() [2/2]
unsigned int libMesh::DiffContext::n_dof_indices (unsigned int var) const inline
Total number of dof indices of the particular variable corresponding to the index argument
Definition at line 406 of file diff_context.h.
References _dof_indices_var.
   {
     libmesh_assert_greater(_dof_indices_var.size(), var);
     return cast_int<unsigned int>(_dof_indices_var[var].size());
   }
n_vars()
unsigned int libMesh::DiffContext::n_vars () const inline
Number of variables in solution.
Definition at line 99 of file diff_context.h.
References _dof_indices_var.
Referenced by libMesh::FirstOrderUnsteadySolver::compute_second_order_eqns(), libMesh::LaplacianErrorEstimator::init_context(), libMesh::DiscontinuityMeasure::init_context(), libMesh::KellyErrorEstimator::init_context(), and libMesh::FEMSystem::numerical_jacobian().
   { return cast_int<unsigned int>(_dof_indices_var.size()); }
nonlocal_reinit()
virtual void libMesh::DiffContext::nonlocal_reinit (Real) inline virtual
Gives derived classes the opportunity to reinitialize data needed for nonlocal calculations at a new point within a timestep
Reimplemented in libMesh::FEMContext.
Definition at line 94 of file diff_context.h.
Referenced by libMesh::EulerSolver::nonlocal_residual(), libMesh::Euler2Solver::nonlocal_residual(), and libMesh::NewmarkSolver::nonlocal_residual().
 {}
set_deltat_pointer()
void libMesh::DiffContext::set_deltat_pointer (Real * dt)
Points the _deltat member of this class at a timestep value stored in the creating System, for example DiffSystem::deltat
Definition at line 103 of file diff_context.C.
References _deltat.
Referenced by libMesh::FEMSystem::build_context(), libMesh::DifferentiableSystem::build_context(), and libMesh::FEMSystem::init_context().
 {
   // We may actually want to be able to set this pointer to nullptr, so
   // don't report an error for that.
   _deltat = dt;
 }
set_time()
void libMesh::DiffContext::set_time (Real time_in) inline
Set the time for which the current nonlinear_solution is defined.
Definition at line 427 of file diff_context.h.
References time.
Referenced by libMesh::FEMContext::_update_time_from_system().
   { time = time_in; }
Member Data Documentation
_deltat
Real* libMesh::DiffContext::_deltat private
Defaults to nullptr, can optionally be used to point to a timestep value in the System-derived class responsible for creating this DiffContext.
In DiffSystem's build_context() function, is assigned to point to the deltat member of that class.
Accessible via public get_deltat()/set_deltat() methods of this class.
Always test for nullptr before using!
Definition at line 653 of file diff_context.h.
Referenced by get_deltat_value(), and set_deltat_pointer().
_dof_indices
std::vector<dof_id_type> libMesh::DiffContext::_dof_indices protected
Global Degree of freedom index lists
Definition at line 637 of file diff_context.h.
Referenced by get_dof_indices(), and n_dof_indices().
_dof_indices_var
std::vector<std::vector<dof_id_type> > libMesh::DiffContext::_dof_indices_var protected
Definition at line 638 of file diff_context.h.
Referenced by get_dof_indices(), n_dof_indices(), and n_vars().
_elem_fixed_solution
DenseVector<Number> libMesh::DiffContext::_elem_fixed_solution protected
Element by element components of nonlinear_solution at a fixed point in a timestep, for optional use by e.g. stabilized methods
Definition at line 603 of file diff_context.h.
Referenced by DiffContext(), and get_elem_fixed_solution().
_elem_fixed_subsolutions
std::vector<std::unique_ptr<DenseSubVector<Number> > > libMesh::DiffContext::_elem_fixed_subsolutions protected
Definition at line 604 of file diff_context.h.
Referenced by DiffContext(), libMesh::FEMContext::fixed_point_gradient(), libMesh::FEMContext::fixed_point_hessian(), libMesh::FEMContext::fixed_point_value(), and get_elem_fixed_solution().
_elem_jacobian
DenseMatrix<Number> libMesh::DiffContext::_elem_jacobian protected
Element jacobian: derivatives of elem_residual with respect to elem_solution
Definition at line 615 of file diff_context.h.
Referenced by DiffContext(), and get_elem_jacobian().
_elem_qoi
std::vector<Number> libMesh::DiffContext::_elem_qoi protected
Element quantity of interest contributions
Definition at line 620 of file diff_context.h.
Referenced by DiffContext(), and get_qois().
_elem_qoi_derivative
std::vector<DenseVector<Number> > libMesh::DiffContext::_elem_qoi_derivative protected
Element quantity of interest derivative contributions
Definition at line 625 of file diff_context.h.
Referenced by DiffContext(), and get_qoi_derivatives().
_elem_qoi_subderivatives
std::vector<std::vector<std::unique_ptr<DenseSubVector<Number> > > > libMesh::DiffContext::_elem_qoi_subderivatives protected
Definition at line 626 of file diff_context.h.
Referenced by DiffContext(), get_qoi_derivatives(), and libMesh::FEMContext::pre_fe_reinit().
_elem_residual
DenseVector<Number> libMesh::DiffContext::_elem_residual protected
Element residual vector
Definition at line 609 of file diff_context.h.
Referenced by DiffContext(), and get_elem_residual().
_elem_solution
DenseVector<Number> libMesh::DiffContext::_elem_solution protected
Element by element components of nonlinear_solution as adjusted by a time_solver
Definition at line 581 of file diff_context.h.
Referenced by DiffContext(), and get_elem_solution().
_elem_solution_accel
DenseVector<Number> libMesh::DiffContext::_elem_solution_accel protected
Element by element components of du/dt as adjusted by a time_solver
Definition at line 595 of file diff_context.h.
Referenced by DiffContext(), and get_elem_solution_accel().
_elem_solution_rate
DenseVector<Number> libMesh::DiffContext::_elem_solution_rate protected
Element by element components of du/dt as adjusted by a time_solver
Definition at line 588 of file diff_context.h.
Referenced by DiffContext(), and get_elem_solution_rate().
_elem_subjacobians
std::vector<std::vector<std::unique_ptr<DenseSubMatrix<Number> > > > libMesh::DiffContext::_elem_subjacobians protected
Definition at line 632 of file diff_context.h.
Referenced by DiffContext(), and get_elem_jacobian().
_elem_subresiduals
std::vector<std::unique_ptr<DenseSubVector<Number> > > libMesh::DiffContext::_elem_subresiduals protected
Element residual subvectors and Jacobian submatrices
Definition at line 631 of file diff_context.h.
Referenced by DiffContext(), and get_elem_residual().
_elem_subsolution_accels
std::vector<std::unique_ptr<DenseSubVector<Number> > > libMesh::DiffContext::_elem_subsolution_accels protected
Definition at line 596 of file diff_context.h.
Referenced by DiffContext(), and get_elem_solution_accel().
_elem_subsolution_rates
std::vector<std::unique_ptr<DenseSubVector<Number> > > libMesh::DiffContext::_elem_subsolution_rates protected
Definition at line 589 of file diff_context.h.
Referenced by DiffContext(), and get_elem_solution_rate().
_elem_subsolutions
std::vector<std::unique_ptr<DenseSubVector<Number> > > libMesh::DiffContext::_elem_subsolutions protected
Definition at line 582 of file diff_context.h.
Referenced by DiffContext(), get_elem_solution(), libMesh::FEMContext::interior_curl(), libMesh::FEMContext::interior_div(), libMesh::FEMContext::point_curl(), libMesh::FEMContext::point_gradient(), libMesh::FEMContext::point_hessian(), libMesh::FEMContext::point_value(), and libMesh::FEMContext::side_gradient().
_is_adjoint
bool libMesh::DiffContext::_is_adjoint private
Is this context to be used for a primal or adjoint solve?
Definition at line 663 of file diff_context.h.
Referenced by is_adjoint().
_localized_vectors
std::map<const NumericVector<Number> *, std::pair<DenseVector<Number>, std::vector<std::unique_ptr<DenseSubVector<Number> > > > > libMesh::DiffContext::_localized_vectors protected
Contains pointers to vectors the user has asked to be localized, keyed with pairs of element localized versions of that vector and per variable views
Definition at line 575 of file diff_context.h.
Referenced by add_localized_vector(), get_localized_subvector(), get_localized_vector(), and libMesh::FEMContext::pre_fe_reinit().
_system
const System& libMesh::DiffContext::_system private
A reference to the system this context is constructed with
Definition at line 658 of file diff_context.h.
Referenced by get_system().
elem_solution_accel_derivative
Real libMesh::DiffContext::elem_solution_accel_derivative
The derivative of elem_solution_accel with respect to the current nonlinear solution, for use by systems with non default mass_residual terms.
Definition at line 514 of file diff_context.h.
Referenced by libMesh::NewmarkSolver::_general_residual(), get_elem_solution_accel_derivative(), and libMesh::FirstOrderUnsteadySolver::prepare_accel().
elem_solution_derivative
Real libMesh::DiffContext::elem_solution_derivative
The derivative of elem_solution with respect to the current nonlinear solution.
Definition at line 500 of file diff_context.h.
Referenced by libMesh::EulerSolver::_general_residual(), libMesh::Euler2Solver::_general_residual(), libMesh::NewmarkSolver::_general_residual(), libMesh::EigenTimeSolver::element_residual(), get_elem_solution_derivative(), and libMesh::EigenTimeSolver::side_residual().
elem_solution_rate_derivative
Real libMesh::DiffContext::elem_solution_rate_derivative
The derivative of elem_solution_rate with respect to the current nonlinear solution, for use by systems with non default mass_residual terms.
Definition at line 507 of file diff_context.h.
Referenced by libMesh::EulerSolver::_general_residual(), libMesh::Euler2Solver::_general_residual(), libMesh::NewmarkSolver::_general_residual(), libMesh::EigenTimeSolver::element_residual(), get_elem_solution_rate_derivative(), and libMesh::EigenTimeSolver::side_residual().
fixed_solution_derivative
Real libMesh::DiffContext::fixed_solution_derivative
The derivative of elem_fixed_solution with respect to the nonlinear solution, for use by systems constructing jacobians with elem_fixed_solution based methods
Definition at line 521 of file diff_context.h.
Referenced by libMesh::EulerSolver::_general_residual(), libMesh::Euler2Solver::_general_residual(), libMesh::SteadySolver::_general_residual(), and get_fixed_solution_derivative().
system_time
const Real libMesh::DiffContext::system_time
This is the time stored in the System class at the time this context was created, i.e. the time at the beginning of the current timestep. This value gets set in the constructor and unlike DiffContext::time, is not tweaked mid-timestep by transient solvers: it remains equal to the value it was assigned at construction.
Definition at line 494 of file diff_context.h.
Referenced by get_system_time().
time
Real libMesh::DiffContext::time
For time-dependent problems, this is the time t for which the current nonlinear_solution is defined. FIXME - this needs to be tweaked mid-timestep by all transient solvers!
Definition at line 485 of file diff_context.h.
Referenced by get_time(), libMesh::GenericProjector< FFunctor, GFunctor, FValue, ProjectionAction >::operator()(), and set_time().
The documentation for this class was generated from the following files:
diff_context.h
diff_context.C