libMesh: libMesh::MeshInput< MT > Class Template Reference
SomeWebsiteLogo
libMesh::MeshInput< MT > Class Template Reference abstract
#include <mesh_base.h>
Public Member Functions
virtual ~MeshInput ()
virtual void read (const std::string &)=0
Protected Member Functions
MeshInput (bool is_parallel_format=false)
MeshInput (MT &, const bool is_parallel_format=false)
MT & mesh ()
void set_n_partitions (unsigned int n_parts)
void skip_comment_lines (std::istream &in, const char comment_start)
Protected Attributes
std::vector< bool > elems_of_dimension
Private Attributes
MT * _obj
const bool _is_parallel_format
Detailed Description
template<class MT>
class libMesh::MeshInput< MT >
This class defines an abstract interface for Mesh input. Specific classes derived from this class actually implement reading various mesh formats.
Author
Benjamin S. Kirk
Date
2004
Definition at line 51 of file mesh_base.h.
Constructor & Destructor Documentation
template<class MT > libMesh::MeshInput< MT >::MeshInput (bool is_parallel_format = false) inline explicit protected
Default constructor. Will set the _obj to NULL, effectively rendering this object useless.
Definition at line 130 of file mesh_input.h.
                                                        :
   elems_of_dimension(),
   _obj (libmesh_nullptr),
   _is_parallel_format(is_parallel_format)
 {
 }
template<class MT> libMesh::MeshInput< MT >::MeshInput (MT & obj, const bool is_parallel_format = false) inline explicit protected
Constructor. Takes a writeable reference to an object. This is the constructor required to read an object.
Definition at line 141 of file mesh_input.h.
References libMesh::MeshInput< MT >::_is_parallel_format, libMesh::MeshInput< MT >::mesh(), libMesh::out, and libMesh::processor_id().
                                                                  :
   elems_of_dimension(),
   _obj (&obj),
   _is_parallel_format(is_parallel_format)
 {
   if (!_is_parallel_format && !this->mesh().is_serial())
     {
       if (this->mesh().processor_id() == 0)
         {
           libmesh_do_once(libMesh::out <<
                           "Warning:  This MeshOutput subclass only supports meshes which have been serialized!"
                           << std::endl;);
         }
     }
 }
template<class MT > libMesh::MeshInput< MT >::~MeshInput () inline virtual
Destructor.
Definition at line 161 of file mesh_input.h.
 {
 }
Member Function Documentation
template<class MT > MT & libMesh::MeshInput< MT >::mesh () inline protected
Returns the object as a writeable reference.
Definition at line 169 of file mesh_input.h.
References libmesh_nullptr.
Referenced by libMesh::GMVIO::_read_materials(), libMesh::GMVIO::_read_nodes(), libMesh::GMVIO::_read_one_cell(), libMesh::AbaqusIO::assign_boundary_node_ids(), libMesh::AbaqusIO::assign_sideset_ids(), libMesh::AbaqusIO::assign_subdomain_ids(), libMesh::ExodusII_IO::copy_elemental_solution(), libMesh::ExodusII_IO::copy_nodal_solution(), libMesh::GMVIO::copy_nodal_solution(), libMesh::TetGenIO::element_in(), libMesh::UNVIO::elements_in(), libMesh::UNVIO::groups_in(), libMesh::MeshInput< MT >::MeshInput(), libMesh::TetGenIO::node_in(), libMesh::UNVIO::nodes_in(), libMesh::AbaqusIO::read(), libMesh::NameBasedIO::read(), libMesh::TetGenIO::read(), libMesh::Nemesis_IO::read(), libMesh::GMVIO::read(), libMesh::ExodusII_IO::read(), libMesh::VTKIO::read(), libMesh::CheckpointIO::read(), libMesh::XdrIO::read(), libMesh::LegacyXdrIO::read_ascii(), libMesh::CheckpointIO::read_bcs(), libMesh::CheckpointIO::read_connectivity(), libMesh::AbaqusIO::read_elements(), libMesh::UCDIO::read_implementation(), libMesh::UNVIO::read_implementation(), libMesh::GmshIO::read_mesh(), libMesh::LegacyXdrIO::read_mesh(), libMesh::AbaqusIO::read_nodes(), libMesh::CheckpointIO::read_nodes(), libMesh::CheckpointIO::read_nodesets(), libMesh::XdrIO::read_serialized_bcs(), libMesh::XdrIO::read_serialized_connectivity(), libMesh::XdrIO::read_serialized_nodes(), libMesh::XdrIO::read_serialized_nodesets(), libMesh::XdrIO::read_serialized_subdomain_names(), libMesh::OFFIO::read_stream(), libMesh::MatlabIO::read_stream(), libMesh::CheckpointIO::read_subdomain_names(), libMesh::MeshInput< MeshBase >::set_n_partitions(), libMesh::NameBasedIO::write(), and libMesh::NameBasedIO::write_nodal_data().
 {
   if (_obj == libmesh_nullptr)
     libmesh_error_msg("ERROR: _obj should not be NULL!");
   return *_obj;
 }
template<class MT> virtual void libMesh::MeshInput< MT >::read (const std::string &) pure virtual
This method implements reading a mesh from a specified file.
Implemented in libMesh::MatlabIO, libMesh::XdrIO, libMesh::CheckpointIO, libMesh::VTKIO, libMesh::LegacyXdrIO, libMesh::UNVIO, libMesh::ExodusII_IO, libMesh::GmshIO, libMesh::GMVIO, libMesh::Nemesis_IO, libMesh::UCDIO, libMesh::TetGenIO, libMesh::NameBasedIO, libMesh::AbaqusIO, and libMesh::OFFIO.
template<class MT> void libMesh::MeshInput< MT >::set_n_partitions (unsigned int n_parts) inline protected
Sets the number of partitions in the mesh. Typically this gets done by the partitioner, but some parallel file formats begin "pre-partitioned".
Definition at line 91 of file mesh_input.h.
 { this->mesh().set_n_partitions() = n_parts; }
template<class MT > void libMesh::MeshInput< MT >::skip_comment_lines (std::istream & in, const char comment_start) protected
Reads input from in, skipping all the lines that start with the character comment_start.
Definition at line 179 of file mesh_input.h.
 {
   char c, line[256];
   while (in.get(c), c==comment_start)
     in.getline (line, 255);
   // put back first character of
   // first non-comment line
   in.putback (c);
 }
Member Data Documentation
template<class MT> const bool libMesh::MeshInput< MT >::_is_parallel_format private
Flag specifying whether this format is parallel-capable. If this is false (default) I/O is only permitted when the mesh has been serialized.
Definition at line 121 of file mesh_input.h.
Referenced by libMesh::MeshInput< MT >::MeshInput().
template<class MT> MT* libMesh::MeshInput< MT >::_obj private
A pointer to a non-const object object. This allows us to read the object from file.
Definition at line 114 of file mesh_input.h.
template<class MT> std::vector<bool> libMesh::MeshInput< MT >::elems_of_dimension protected
A vector of bools describing what dimension elements have been encountered when reading a mesh.
Definition at line 97 of file mesh_input.h.
The documentation for this class was generated from the following files:
mesh_base.h
mesh_input.h