libMesh: libMesh::AztecLinearSolver< T > Class Template Reference
SomeWebsiteLogo
libMesh::AztecLinearSolver< T > Class Template Reference
#include <trilinos_aztec_linear_solver.h>
Public Member Functions
AztecLinearSolver (const libMesh::Parallel::Communicator &comm LIBMESH_CAN_DEFAULT_TO_COMMWORLD)
~AztecLinearSolver ()
virtual void clear () libmesh_override
virtual void init (const char *name=libmesh_nullptr) libmesh_override
virtual std::pair< unsigned int, Real > solve (SparseMatrix< T > &matrix_in, NumericVector< T > &solution_in, NumericVector< T > &rhs_in, const double tol, const unsigned int m_its) libmesh_override
virtual std::pair< unsigned int, Real > solve (SparseMatrix< T > &matrix, SparseMatrix< T > &preconditioner, NumericVector< T > &solution, NumericVector< T > &rhs, const double tol, const unsigned int m_its) libmesh_override
virtual std::pair< unsigned int, Real > solve (const ShellMatrix< T > &shell_matrix, NumericVector< T > &solution_in, NumericVector< T > &rhs_in, const double tol, const unsigned int m_its) libmesh_override
virtual std::pair< unsigned int, Real > solve (const ShellMatrix< T > &shell_matrix, const SparseMatrix< T > &precond_matrix, NumericVector< T > &solution_in, NumericVector< T > &rhs_in, const double tol, const unsigned int m_its) libmesh_override
void get_residual_history (std::vector< double > &hist)
Real get_initial_residual ()
virtual void print_converged_reason () const libmesh_override
virtual LinearConvergenceReason get_converged_reason () const libmesh_override
bool initialized () const
virtual void init_names (const System &)
SolverType solver_type () const
void set_solver_type (const SolverType st)
PreconditionerType preconditioner_type () const
void set_preconditioner_type (const PreconditionerType pct)
void attach_preconditioner (Preconditioner< T > *preconditioner)
virtual void reuse_preconditioner (bool)
bool get_same_preconditioner ()
virtual void restrict_solve_to (const std::vector< unsigned int > *const dofs, const SubsetSolveMode subset_solve_mode=SUBSET_ZERO)
std::pair< unsigned int, Real > solve (SparseMatrix< T > &matrix, SparseMatrix< T > *precond_matrix, NumericVector< T > &, NumericVector< T > &, const double, const unsigned int)
std::pair< unsigned int, Real > solve (const ShellMatrix< T > &matrix, const SparseMatrix< T > *precond_matrix, NumericVector< T > &, NumericVector< T > &, const double, const unsigned int)
virtual std::pair< unsigned int, Real > adjoint_solve (SparseMatrix< T > &, NumericVector< T > &, NumericVector< T > &, const double, const unsigned int)
void set_solver_configuration (SolverConfiguration &solver_configuration)
const Parallel::Communicator & comm () const
processor_id_type n_processors () const
processor_id_type processor_id () const
Static Public Member Functions
static UniquePtr< LinearSolver< T > > build (const libMesh::Parallel::Communicator &comm_in, const SolverPackage solver_package=libMesh::default_solver_package())
static std::string get_info ()
static void print_info (std::ostream &out=libMesh::out)
static unsigned int n_objects ()
static void enable_print_counter_info ()
static void disable_print_counter_info ()
Protected Types
typedef std::map< std::string, std::pair< unsigned int, unsigned int > > Counts
Protected Member Functions
void increment_constructor_count (const std::string &name)
void increment_destructor_count (const std::string &name)
Protected Attributes
SolverType _solver_type
PreconditionerType _preconditioner_type
bool _is_initialized
Preconditioner< T > * _preconditioner
bool same_preconditioner
SolverConfiguration * _solver_configuration
const Parallel::Communicator & _communicator
Static Protected Attributes
static Counts _counts
static Threads::atomic< unsigned int > _n_objects
static Threads::spin_mutex _mutex
static bool _enable_print_counter = true
Private Member Functions
void set_solver_type ()
Private Attributes
Epetra_LinearProblem * _linear_problem
AztecOO * _linear_solver
Detailed Description
template<typename T>
class libMesh::AztecLinearSolver< T >
This class provides an interface to AztecOO iterative solvers that is compatible with the libMesh LinearSolver<>
Author
Benjamin Kirk
Date
2002-2008
Definition at line 51 of file trilinos_aztec_linear_solver.h.
Member Typedef Documentation
typedef std::map<std::string, std::pair<unsigned int, unsigned int> > libMesh::ReferenceCounter::Counts protected inherited
Data structure to log the information. The log is identified by the class name.
Definition at line 110 of file reference_counter.h.
Constructor & Destructor Documentation
template<typename T > libMesh::AztecLinearSolver< T >::AztecLinearSolver (const libMesh::Parallel::Communicator &comm LIBMESH_CAN_DEFAULT_TO_COMMWORLD) inline
Constructor. Initializes Aztec data structures
Definition at line 174 of file trilinos_aztec_linear_solver.h.
References libMesh::LinearSolver< T >::_preconditioner_type, libMesh::BLOCK_JACOBI_PRECOND, libMesh::ILU_PRECOND, and libMesh::ParallelObject::n_processors().
                                                                                  :
   LinearSolver<T>(comm)
 {
   if (this->n_processors() == 1)
     this->_preconditioner_type = ILU_PRECOND;
   else
     this->_preconditioner_type = BLOCK_JACOBI_PRECOND;
 }
template<typename T > libMesh::AztecLinearSolver< T >::~AztecLinearSolver () inline
Destructor.
Definition at line 187 of file trilinos_aztec_linear_solver.h.
References libMesh::AztecLinearSolver< T >::clear().
 {
   this->clear ();
 }
Member Function Documentation
template<typename T> std::pair< unsigned int, Real > libMesh::LinearSolver< T >::adjoint_solve (SparseMatrix< T > & mat, NumericVector< T > & sol, NumericVector< T > & rhs, const double tol, const unsigned int n_iter) virtual inherited
Function to solve the adjoint system. Note that this method will compute the preconditioner from the system matrix. This is not a pure virtual function and is defined linear_solver.C
Reimplemented in libMesh::PetscLinearSolver< T >, libMesh::LaspackLinearSolver< T >, and libMesh::EigenSparseLinearSolver< T >.
Definition at line 129 of file linear_solver.C.
References libMesh::SparseMatrix< T >::close(), and libMesh::SparseMatrix< T >::get_transpose().
Referenced by libMesh::ImplicitSystem::adjoint_solve(), and libMesh::LinearSolver< Number >::set_solver_type().
 {
   // Log how long the linear solve takes.
   LOG_SCOPE("adjoint_solve()", "LinearSolver");
   // Take the discrete adjoint
   mat.close();
   mat.get_transpose(mat);
   // Call the solve function for the relevant linear algebra library and
   // solve the transpose matrix
   const std::pair<unsigned int, Real> totalrval =  this->solve (mat, sol, rhs, tol, n_iter);
   // Now transpose back and restore the original matrix
   // by taking the discrete adjoint
   mat.get_transpose(mat);
   return totalrval;
 }
template<typename T> void libMesh::LinearSolver< T >::attach_preconditioner (Preconditioner< T > * preconditioner) inherited
Attaches a Preconditioner object to be used
Definition at line 102 of file linear_solver.C.
References libMesh::libMeshPrivateData::_is_initialized, and libMesh::SHELL_PRECOND.
Referenced by libMesh::LinearSolver< Number >::set_solver_type().
 {
   if (this->_is_initialized)
     libmesh_error_msg("Preconditioner must be attached before the solver is initialized!");
   _preconditioner_type = SHELL_PRECOND;
   _preconditioner = preconditioner;
 }
template<typename T > UniquePtr< LinearSolver< T > > libMesh::LinearSolver< T >::build (const libMesh::Parallel::Communicator & comm_in, const SolverPackage solver_package = libMesh::default_solver_package()) static inherited
Builds a LinearSolver using the linear solver package specified by solver_package
Definition at line 42 of file linear_solver.C.
References libMesh::EIGEN_SOLVERS, libMesh::LASPACK_SOLVERS, libMesh::PETSC_SOLVERS, and libMesh::TRILINOS_SOLVERS.
Referenced by libMesh::ImplicitSystem::get_linear_solver(), and libMesh::TimeSolver::init().
 {
   // Build the appropriate solver
   switch (solver_package)
     {
 #ifdef LIBMESH_HAVE_LASPACK
     case LASPACK_SOLVERS:
       return UniquePtr<LinearSolver<T> >(new LaspackLinearSolver<T>(comm));
 #endif
 #ifdef LIBMESH_HAVE_PETSC
     case PETSC_SOLVERS:
       return UniquePtr<LinearSolver<T> >(new PetscLinearSolver<T>(comm));
 #endif
 #ifdef LIBMESH_TRILINOS_HAVE_AZTECOO
     case TRILINOS_SOLVERS:
       return UniquePtr<LinearSolver<T> >(new AztecLinearSolver<T>(comm));
 #endif
 #ifdef LIBMESH_HAVE_EIGEN
     case EIGEN_SOLVERS:
       return UniquePtr<LinearSolver<T> >(new EigenSparseLinearSolver<T>(comm));
 #endif
     default:
       libmesh_error_msg("ERROR:  Unrecognized solver package: " << solver_package);
     }
   return UniquePtr<LinearSolver<T> >();
 }
template<typename T > void libMesh::AztecLinearSolver< T >::clear () virtual
Release all memory and clear data structures.
Reimplemented from libMesh::LinearSolver< T >.
Definition at line 40 of file trilinos_aztec_linear_solver.C.
References libMesh::libMeshPrivateData::_is_initialized, libMesh::BLOCK_JACOBI_PRECOND, libMesh::GMRES, libMesh::ILU_PRECOND, libMesh::initialized(), and libMesh::n_processors().
Referenced by libMesh::AztecLinearSolver< T >::~AztecLinearSolver().
 {
   if (this->initialized())
     {
       this->_is_initialized = false;
       // Mimic PETSc default solver and preconditioner
       this->_solver_type           = GMRES;
       if (this->n_processors() == 1)
         this->_preconditioner_type = ILU_PRECOND;
       else
         this->_preconditioner_type = BLOCK_JACOBI_PRECOND;
     }
 }
const Parallel::Communicator& libMesh::ParallelObject::comm () const inline inherited
Returns
a reference to the Parallel::Communicator object used by this mesh.
Definition at line 87 of file parallel_object.h.
References libMesh::ParallelObject::_communicator.
Referenced by libMesh::__libmesh_petsc_diff_solver_monitor(), libMesh::__libmesh_petsc_diff_solver_residual(), libMesh::__libmesh_petsc_snes_jacobian(), libMesh::__libmesh_petsc_snes_postcheck(), libMesh::__libmesh_petsc_snes_residual(), libMesh::__libmesh_tao_equality_constraints(), libMesh::__libmesh_tao_equality_constraints_jacobian(), libMesh::__libmesh_tao_gradient(), libMesh::__libmesh_tao_hessian(), libMesh::__libmesh_tao_inequality_constraints(), libMesh::__libmesh_tao_inequality_constraints_jacobian(), libMesh::__libmesh_tao_objective(), libMesh::MeshRefinement::_coarsen_elements(), libMesh::ExactSolution::_compute_error(), libMesh::ParmetisPartitioner::_do_repartition(), libMesh::UniformRefinementEstimator::_estimate_error(), libMesh::BoundaryInfo::_find_id_maps(), libMesh::PetscLinearSolver< T >::_petsc_shell_matrix_get_diagonal(), libMesh::SlepcEigenSolver< T >::_petsc_shell_matrix_get_diagonal(), libMesh::PetscLinearSolver< T >::_petsc_shell_matrix_mult(), libMesh::SlepcEigenSolver< T >::_petsc_shell_matrix_mult(), libMesh::PetscLinearSolver< T >::_petsc_shell_matrix_mult_add(), libMesh::EquationSystems::_read_impl(), libMesh::MeshRefinement::_refine_elements(), libMesh::MeshRefinement::_smooth_flags(), libMesh::ImplicitSystem::add_matrix(), libMesh::System::add_vector(), libMesh::EigenSparseLinearSolver< T >::adjoint_solve(), libMesh::UnstructuredMesh::all_second_order(), libMesh::MeshTools::Modification::all_tri(), libMesh::LaplaceMeshSmoother::allgather_graph(), libMesh::FEMSystem::assemble_qoi(), libMesh::MeshCommunication::assign_global_indices(), libMesh::ParmetisPartitioner::assign_partitioning(), libMesh::DofMap::attach_matrix(), libMesh::Parallel::BinSorter< KeyType, IdxType >::binsort(), libMesh::Parallel::Sort< KeyType, IdxType >::binsort(), libMesh::MeshTools::bounding_box(), libMesh::MeshCommunication::broadcast(), libMesh::SparseMatrix< T >::build(), libMesh::MeshTools::Generation::build_extrusion(), libMesh::Parallel::Histogram< KeyType, IdxType >::build_histogram(), libMesh::PetscNonlinearSolver< T >::build_mat_null_space(), libMesh::BoundaryInfo::build_node_list_from_side_list(), libMesh::EquationSystems::build_parallel_solution_vector(), libMesh::MeshBase::cache_elem_dims(), libMesh::System::calculate_norm(), libMesh::DofMap::check_dirichlet_bcid_consistency(), libMesh::DistributedVector< T >::clone(), libMesh::EigenSparseVector< T >::clone(), libMesh::LaspackVector< T >::clone(), libMesh::EpetraVector< T >::clone(), libMesh::PetscVector< T >::clone(), libMesh::EpetraVector< T >::close(), libMesh::Parallel::Sort< KeyType, IdxType >::communicate_bins(), libMesh::Nemesis_IO_Helper::compute_num_global_elem_blocks(), libMesh::Nemesis_IO_Helper::compute_num_global_nodesets(), libMesh::Nemesis_IO_Helper::compute_num_global_sidesets(), libMesh::Problem_Interface::computeF(), libMesh::Problem_Interface::computeJacobian(), libMesh::Problem_Interface::computePreconditioner(), libMesh::MeshTools::correct_node_proc_ids(), libMesh::MeshRefinement::create_parent_error_vector(), libMesh::MeshCommunication::delete_remote_elements(), libMesh::DofMap::distribute_dofs(), DMlibMeshFunction(), DMlibMeshJacobian(), DMlibMeshSetSystem_libMesh(), DMVariableBounds_libMesh(), libMesh::MeshRefinement::eliminate_unrefined_patches(), libMesh::EpetraVector< T >::EpetraVector(), libMesh::WeightedPatchRecoveryErrorEstimator::estimate_error(), libMesh::PatchRecoveryErrorEstimator::estimate_error(), libMesh::JumpErrorEstimator::estimate_error(), libMesh::AdjointRefinementEstimator::estimate_error(), libMesh::ExactErrorEstimator::estimate_error(), libMesh::MeshRefinement::flag_elements_by_elem_fraction(), libMesh::MeshRefinement::flag_elements_by_error_fraction(), libMesh::MeshRefinement::flag_elements_by_nelem_target(), libMesh::MeshCommunication::gather(), libMesh::MeshCommunication::gather_neighboring_elements(), libMesh::CondensedEigenSystem::get_eigenpair(), libMesh::DofMap::get_info(), libMesh::ImplicitSystem::get_linear_solver(), libMesh::EquationSystems::get_solution(), libMesh::LocationMap< T >::init(), libMesh::PetscDiffSolver::init(), libMesh::TimeSolver::init(), libMesh::TopologyMap::init(), libMesh::TaoOptimizationSolver< T >::init(), libMesh::PetscNonlinearSolver< T >::init(), libMesh::DistributedVector< T >::init(), libMesh::EpetraVector< T >::init(), libMesh::PetscVector< T >::init(), libMesh::SystemSubsetBySubdomain::init(), libMesh::EigenSystem::init_data(), libMesh::EigenSystem::init_matrices(), libMesh::ParmetisPartitioner::initialize(), libMesh::OptimizationSystem::initialize_equality_constraints_storage(), libMesh::OptimizationSystem::initialize_inequality_constraints_storage(), libMesh::MeshTools::libmesh_assert_parallel_consistent_procids< Elem >(), libMesh::MeshTools::libmesh_assert_parallel_consistent_procids< Node >(), libMesh::MeshTools::libmesh_assert_topology_consistent_procids< Node >(), libMesh::MeshTools::libmesh_assert_valid_boundary_ids(), libMesh::MeshTools::libmesh_assert_valid_dof_ids(), libMesh::MeshTools::libmesh_assert_valid_neighbors(), libMesh::DistributedMesh::libmesh_assert_valid_parallel_flags(), libMesh::DistributedMesh::libmesh_assert_valid_parallel_object_ids(), libMesh::DistributedMesh::libmesh_assert_valid_parallel_p_levels(), libMesh::MeshTools::libmesh_assert_valid_refinement_flags(), libMesh::MeshTools::libmesh_assert_valid_unique_ids(), libMesh::MeshRefinement::limit_level_mismatch_at_edge(), libMesh::MeshRefinement::limit_level_mismatch_at_node(), libMesh::MeshRefinement::limit_overrefined_boundary(), libMesh::MeshRefinement::limit_underrefined_boundary(), libMesh::MeshRefinement::make_coarsening_compatible(), libMesh::MeshCommunication::make_elems_parallel_consistent(), libMesh::MeshRefinement::make_flags_parallel_consistent(), libMesh::MeshCommunication::make_new_node_proc_ids_parallel_consistent(), libMesh::MeshCommunication::make_new_nodes_parallel_consistent(), libMesh::MeshCommunication::make_node_ids_parallel_consistent(), libMesh::MeshCommunication::make_node_proc_ids_parallel_consistent(), libMesh::MeshCommunication::make_node_unique_ids_parallel_consistent(), libMesh::MeshCommunication::make_nodes_parallel_consistent(), libMesh::MeshCommunication::make_p_levels_parallel_consistent(), libMesh::MeshRefinement::make_refinement_compatible(), libMesh::DistributedVector< T >::max(), libMesh::FEMSystem::mesh_position_set(), libMesh::MeshSerializer::MeshSerializer(), libMesh::DistributedVector< T >::min(), libMesh::DistributedMesh::n_active_elem(), libMesh::MeshTools::n_active_levels(), libMesh::BoundaryInfo::n_boundary_conds(), libMesh::BoundaryInfo::n_edge_conds(), libMesh::CondensedEigenSystem::n_global_non_condensed_dofs(), libMesh::MeshTools::n_levels(), libMesh::BoundaryInfo::n_nodeset_conds(), libMesh::MeshTools::n_p_levels(), libMesh::BoundaryInfo::n_shellface_conds(), libMesh::DistributedMesh::parallel_max_elem_id(), libMesh::DistributedMesh::parallel_max_node_id(), libMesh::ReplicatedMesh::parallel_max_unique_id(), libMesh::DistributedMesh::parallel_max_unique_id(), libMesh::DistributedMesh::parallel_n_elem(), libMesh::DistributedMesh::parallel_n_nodes(), libMesh::SparsityPattern::Build::parallel_sync(), libMesh::MeshTools::paranoid_n_levels(), libMesh::Partitioner::partition(), libMesh::MetisPartitioner::partition_range(), libMesh::Partitioner::partition_unpartitioned_elements(), libMesh::petsc_auto_fieldsplit(), libMesh::System::point_gradient(), libMesh::System::point_hessian(), libMesh::System::point_value(), libMesh::MeshBase::prepare_for_use(), libMesh::SparseMatrix< T >::print(), libMesh::MeshTools::processor_bounding_box(), libMesh::Nemesis_IO::read(), libMesh::XdrIO::read(), libMesh::XdrIO::read_serialized_bc_names(), libMesh::XdrIO::read_serialized_bcs_helper(), libMesh::XdrIO::read_serialized_connectivity(), libMesh::XdrIO::read_serialized_nodes(), libMesh::XdrIO::read_serialized_nodesets(), libMesh::XdrIO::read_serialized_subdomain_names(), libMesh::MeshBase::recalculate_n_partitions(), libMesh::MeshCommunication::redistribute(), libMesh::DistributedMesh::renumber_dof_objects(), libMesh::MeshCommunication::send_coarse_ghosts(), libMesh::Partitioner::set_node_processor_ids(), libMesh::DofMap::set_nonlocal_dof_objects(), libMesh::Partitioner::set_parent_processor_ids(), libMesh::LaplaceMeshSmoother::smooth(), libMesh::Parallel::Sort< KeyType, IdxType >::sort(), libMesh::MeshTools::subdomain_bounding_box(), libMesh::MeshBase::subdomain_ids(), libMesh::BoundaryInfo::sync(), libMesh::Parallel::sync_element_data_by_parent_id(), libMesh::Parallel::sync_node_data_by_element_id(), libMesh::MeshRefinement::test_level_one(), libMesh::MeshRefinement::test_unflagged(), libMesh::MeshTools::total_weight(), libMesh::NameBasedIO::write(), libMesh::XdrIO::write(), libMesh::XdrIO::write_serialized_bcs_helper(), libMesh::XdrIO::write_serialized_connectivity(), libMesh::XdrIO::write_serialized_nodes(), libMesh::XdrIO::write_serialized_nodesets(), libMesh::DistributedVector< T >::zero_clone(), libMesh::LaspackVector< T >::zero_clone(), libMesh::EigenSparseVector< T >::zero_clone(), libMesh::EpetraVector< T >::zero_clone(), and libMesh::PetscVector< T >::zero_clone().
   { return _communicator; }
void libMesh::ReferenceCounter::disable_print_counter_info () static inherited
Definition at line 106 of file reference_counter.C.
References libMesh::ReferenceCounter::_enable_print_counter.
Referenced by libMesh::LibMeshInit::LibMeshInit(), and libMesh::ReferenceCounter::n_objects().
 {
   _enable_print_counter = false;
   return;
 }
void libMesh::ReferenceCounter::enable_print_counter_info () static inherited
Methods to enable/disable the reference counter output from print_info()
Definition at line 100 of file reference_counter.C.
References libMesh::ReferenceCounter::_enable_print_counter.
Referenced by libMesh::ReferenceCounter::n_objects().
 {
   _enable_print_counter = true;
   return;
 }
template<typename T > LinearConvergenceReason libMesh::AztecLinearSolver< T >::get_converged_reason () const virtual
Returns the solver's convergence flag
Implements libMesh::LinearSolver< T >.
Definition at line 219 of file trilinos_aztec_linear_solver.C.
References libMesh::CONVERGED_RTOL_NORMAL, libMesh::DIVERGED_ITS, and libMesh::DIVERGED_NULL.
Referenced by libMesh::AztecLinearSolver< T >::solve().
 {
   const double *status = _linear_solver->GetAztecStatus();
   switch (static_cast<int>(status[AZ_why]))
     {
     case AZ_normal :
       return CONVERGED_RTOL_NORMAL;
     case AZ_maxits :
       return DIVERGED_ITS;
     }
   return DIVERGED_NULL;
 }
std::string libMesh::ReferenceCounter::get_info () static inherited
Gets a string containing the reference information.
Definition at line 47 of file reference_counter.C.
References libMesh::ReferenceCounter::_counts, and libMesh::Quality::name().
Referenced by libMesh::ReferenceCounter::print_info().
 {
 #if defined(LIBMESH_ENABLE_REFERENCE_COUNTING) && defined(DEBUG)
   std::ostringstream oss;
   oss << '\n'
       << " ---------------------------------------------------------------------------- \n"
       << "| Reference count information                                                |\n"
       << " ---------------------------------------------------------------------------- \n";
   for (Counts::iterator it = _counts.begin();
        it != _counts.end(); ++it)
     {
       const std::string name(it->first);
       const unsigned int creations    = it->second.first;
       const unsigned int destructions = it->second.second;
       oss << "| " << name << " reference count information:\n"
           << "|  Creations:    " << creations    << '\n'
           << "|  Destructions: " << destructions << '\n';
     }
   oss << " ---------------------------------------------------------------------------- \n";
   return oss.str();
 #else
   return "";
 #endif
 }
template<typename T > Real libMesh::AztecLinearSolver< T >::get_initial_residual ()
Returns just the initial residual for the solve just completed with this interface. Use this method instead of the one above if you just want the starting residual and not the entire history.
Definition at line 178 of file trilinos_aztec_linear_solver.C.
Referenced by libMesh::AztecLinearSolver< T >::solve().
 {
   return _linear_solver->TrueResidual();
 }
template<typename T > void libMesh::AztecLinearSolver< T >::get_residual_history (std::vector< double > & hist)
Fills the input vector with the sequence of residual norms from the latest iterative solve.
Definition at line 169 of file trilinos_aztec_linear_solver.C.
Referenced by libMesh::AztecLinearSolver< T >::solve().
 {
   libmesh_not_implemented();
 }
template<typename T > bool libMesh::LinearSolver< T >::get_same_preconditioner () inline inherited
Returns
same_preconditioner, which indicates if we reuse the same preconditioner for subsequent solves.
Definition at line 324 of file linear_solver.h.
References libMesh::LinearSolver< T >::same_preconditioner.
Referenced by libMesh::LinearSolver< Number >::set_solver_type().
 {
   return same_preconditioner;
 }
void libMesh::ReferenceCounter::increment_constructor_count (const std::string & name) inline protected inherited
Increments the construction counter. Should be called in the constructor of any derived class that will be reference counted.
Definition at line 160 of file reference_counter.h.
References libMesh::ReferenceCounter::_counts, libMesh::Quality::name(), and libMesh::Threads::spin_mtx.
Referenced by libMesh::ReferenceCounter::n_objects(), and libMesh::ReferenceCountedObject< RBParametrized >::ReferenceCountedObject().
 {
   Threads::spin_mutex::scoped_lock lock(Threads::spin_mtx);
   std::pair<unsigned int, unsigned int> & p = _counts[name];
   p.first++;
 }
void libMesh::ReferenceCounter::increment_destructor_count (const std::string & name) inline protected inherited
Increments the destruction counter. Should be called in the destructor of any derived class that will be reference counted.
Definition at line 173 of file reference_counter.h.
References libMesh::ReferenceCounter::_counts, libMesh::Quality::name(), and libMesh::Threads::spin_mtx.
Referenced by libMesh::ReferenceCounter::n_objects(), and libMesh::ReferenceCountedObject< RBParametrized >::~ReferenceCountedObject().
 {
   Threads::spin_mutex::scoped_lock lock(Threads::spin_mtx);
   std::pair<unsigned int, unsigned int> & p = _counts[name];
   p.second++;
 }
template<typename T > void libMesh::AztecLinearSolver< T >::init (const char * name = libmesh_nullptr) virtual
Initialize data structures if not done so already.
Implements libMesh::LinearSolver< T >.
Definition at line 59 of file trilinos_aztec_linear_solver.C.
References libMesh::libMeshPrivateData::_is_initialized, libMesh::BLOCK_JACOBI_PRECOND, libMesh::ICC_PRECOND, libMesh::ILU_PRECOND, libMesh::initialized(), and libMesh::LU_PRECOND.
 {
   // Initialize the data structures if not done so already.
   if (!this->initialized())
     {
       this->_is_initialized = true;
       _linear_solver = new AztecOO();
       set_solver_type();
       switch(this->_preconditioner_type)
         {
         case ILU_PRECOND:
           _linear_solver->SetAztecOption(AZ_precond,AZ_dom_decomp);
           _linear_solver->SetAztecOption(AZ_subdomain_solve,AZ_ilu);
           break;
         case BLOCK_JACOBI_PRECOND:
           _linear_solver->SetAztecOption(AZ_precond,AZ_Jacobi);
           break;
         case ICC_PRECOND:
           _linear_solver->SetAztecOption(AZ_precond,AZ_dom_decomp);
           _linear_solver->SetAztecOption(AZ_subdomain_solve,AZ_icc);
           break;
         case LU_PRECOND:
           _linear_solver->SetAztecOption(AZ_precond,AZ_dom_decomp);
           _linear_solver->SetAztecOption(AZ_subdomain_solve,AZ_lu);
           break;
         default:
           _linear_solver->SetAztecOption(AZ_precond,AZ_dom_decomp);
           _linear_solver->SetAztecOption(AZ_subdomain_solve,AZ_ilu);
         }
     }
 }
template<typename T> virtual void libMesh::LinearSolver< T >::init_names (const System &) inline virtual inherited
Apply names to the system to be solved. For most packages this is a no-op; for PETSc this sets an option prefix from the system name and sets field names from the system's variable names.
Since field names are applied to DoF numberings, this method must be called again after any System reinit.
Reimplemented in libMesh::PetscLinearSolver< T >.
Definition at line 107 of file linear_solver.h.
 {}
template<typename T> bool libMesh::LinearSolver< T >::initialized () const inline inherited
Returns
true if the data structures are initialized, false otherwise.
Definition at line 86 of file linear_solver.h.
Referenced by libMesh::EigenSparseLinearSolver< T >::clear(), and libMesh::EigenSparseLinearSolver< T >::init().
 { return _is_initialized; }
static unsigned int libMesh::ReferenceCounter::n_objects () inline static inherited
Prints the number of outstanding (created, but not yet destroyed) objects.
Definition at line 76 of file reference_counter.h.
References libMesh::ReferenceCounter::_n_objects, libMesh::ReferenceCounter::disable_print_counter_info(), libMesh::ReferenceCounter::enable_print_counter_info(), libMesh::ReferenceCounter::increment_constructor_count(), libMesh::ReferenceCounter::increment_destructor_count(), and libMesh::Quality::name().
Referenced by libMesh::System::hide_output(), and libMesh::LibMeshInit::LibMeshInit().
   { return _n_objects; }
processor_id_type libMesh::ParallelObject::n_processors () const inline inherited
Returns
the number of processors in the group.
Definition at line 93 of file parallel_object.h.
References libMesh::ParallelObject::_communicator, and libMesh::Parallel::Communicator::size().
Referenced by libMesh::ParmetisPartitioner::_do_repartition(), libMesh::BoundaryInfo::_find_id_maps(), libMesh::DistributedMesh::add_elem(), libMesh::DistributedMesh::add_node(), libMesh::LaplaceMeshSmoother::allgather_graph(), libMesh::FEMSystem::assembly(), libMesh::ParmetisPartitioner::assign_partitioning(), libMesh::AztecLinearSolver< T >::AztecLinearSolver(), libMesh::MeshCommunication::broadcast(), libMesh::BoundaryInfo::build_node_list_from_side_list(), libMesh::DistributedMesh::clear(), libMesh::Nemesis_IO_Helper::compute_border_node_ids(), libMesh::Nemesis_IO_Helper::construct_nemesis_filename(), libMesh::MeshTools::correct_node_proc_ids(), libMesh::UnstructuredMesh::create_pid_mesh(), libMesh::DofMap::distribute_dofs(), libMesh::DofMap::distribute_local_dofs_node_major(), libMesh::DofMap::distribute_local_dofs_var_major(), libMesh::DistributedMesh::DistributedMesh(), libMesh::EnsightIO::EnsightIO(), libMesh::MeshCommunication::gather(), libMesh::MeshCommunication::gather_neighboring_elements(), libMesh::MeshBase::get_info(), libMesh::EquationSystems::get_solution(), libMesh::DistributedVector< T >::init(), libMesh::SystemSubsetBySubdomain::init(), libMesh::ParmetisPartitioner::initialize(), libMesh::Nemesis_IO_Helper::initialize(), libMesh::DistributedMesh::insert_elem(), libMesh::MeshTools::libmesh_assert_parallel_consistent_procids< Elem >(), libMesh::MeshTools::libmesh_assert_parallel_consistent_procids< Node >(), libMesh::MeshTools::libmesh_assert_topology_consistent_procids< Node >(), libMesh::MeshTools::libmesh_assert_valid_boundary_ids(), libMesh::MeshTools::libmesh_assert_valid_dof_ids(), libMesh::MeshTools::libmesh_assert_valid_neighbors(), libMesh::MeshTools::libmesh_assert_valid_refinement_flags(), libMesh::DofMap::local_variable_indices(), libMesh::MeshBase::n_active_elem_on_proc(), libMesh::MeshBase::n_elem_on_proc(), libMesh::MeshBase::n_nodes_on_proc(), libMesh::SparsityPattern::Build::parallel_sync(), libMesh::Partitioner::partition(), libMesh::MeshBase::partition(), libMesh::Partitioner::partition_unpartitioned_elements(), libMesh::PetscLinearSolver< T >::PetscLinearSolver(), libMesh::System::point_gradient(), libMesh::System::point_hessian(), libMesh::System::point_value(), libMesh::SparseMatrix< T >::print(), libMesh::MeshTools::processor_bounding_box(), libMesh::NameBasedIO::read(), libMesh::Nemesis_IO::read(), libMesh::XdrIO::read(), libMesh::MeshCommunication::redistribute(), libMesh::DistributedMesh::renumber_dof_objects(), libMesh::Partitioner::repartition(), libMesh::MeshCommunication::send_coarse_ghosts(), libMesh::Partitioner::set_node_processor_ids(), libMesh::DofMap::set_nonlocal_dof_objects(), libMesh::Parallel::Sort< KeyType, IdxType >::sort(), libMesh::DistributedMesh::update_parallel_id_counts(), libMesh::GMVIO::write_binary(), libMesh::GMVIO::write_discontinuous_gmv(), libMesh::XdrIO::write_serialized_bcs_helper(), libMesh::XdrIO::write_serialized_connectivity(), libMesh::XdrIO::write_serialized_nodes(), and libMesh::XdrIO::write_serialized_nodesets().
   { return cast_int<processor_id_type>(_communicator.size()); }
template<typename T > PreconditionerType libMesh::LinearSolver< T >::preconditioner_type () const inherited
Returns the type of preconditioner to use.
Definition at line 82 of file linear_solver.C.
Referenced by libMesh::LinearSolver< Number >::set_solver_type().
 {
   if(_preconditioner)
     return _preconditioner->type();
   return _preconditioner_type;
 }
template<typename T > void libMesh::AztecLinearSolver< T >::print_converged_reason () const virtual
Prints a useful message about why the latest linear solve con(di)verged.
Reimplemented from libMesh::LinearSolver< T >.
Definition at line 186 of file trilinos_aztec_linear_solver.C.
References libMesh::out.
Referenced by libMesh::AztecLinearSolver< T >::solve().
 {
   const double *status = _linear_solver->GetAztecStatus();
   switch (static_cast<int>(status[AZ_why]))
     {
     case AZ_normal :
       libMesh::out << "AztecOO converged.\n";
       break;
     case AZ_maxits :
       libMesh::out << "AztecOO failed to converge within maximum iterations.\n";
       break;
     case AZ_param :
       libMesh::out << "AztecOO failed to support a user-requested parameter.\n";
       break;
     case AZ_breakdown :
       libMesh::out << "AztecOO encountered numerical breakdown.\n";
       break;
     case AZ_loss :
       libMesh::out << "AztecOO encountered numerical loss of precision.\n";
       break;
     case AZ_ill_cond :
       libMesh::out << "AztecOO encountered an ill-conditioned GMRES Hessian.\n";
       break;
     default:
       libMesh::out << "AztecOO reported an unrecognized condition.\n";
       break;
     }
 }
void libMesh::ReferenceCounter::print_info (std::ostream & out = libMesh::out) static inherited
Prints the reference information, by default to libMesh::out.
Definition at line 88 of file reference_counter.C.
References libMesh::ReferenceCounter::_enable_print_counter, and libMesh::ReferenceCounter::get_info().
Referenced by libMesh::LibMeshInit::LibMeshInit().
 {
   if( _enable_print_counter ) out_stream << ReferenceCounter::get_info();
 }
processor_id_type libMesh::ParallelObject::processor_id () const inline inherited
Returns
the rank of this processor in the group.
Definition at line 99 of file parallel_object.h.
References libMesh::ParallelObject::_communicator, and libMesh::Parallel::Communicator::rank().
Referenced by libMesh::BoundaryInfo::_find_id_maps(), libMesh::EquationSystems::_read_impl(), libMesh::DistributedMesh::add_elem(), libMesh::BoundaryInfo::add_elements(), libMesh::DofMap::add_neighbors_to_send_list(), libMesh::DistributedMesh::add_node(), libMesh::MeshRefinement::add_node(), libMesh::MeshTools::Modification::all_tri(), libMesh::FEMSystem::assembly(), libMesh::ParmetisPartitioner::assign_partitioning(), libMesh::MeshCommunication::broadcast(), libMesh::EquationSystems::build_discontinuous_solution_vector(), libMesh::Nemesis_IO_Helper::build_element_and_node_maps(), libMesh::ParmetisPartitioner::build_graph(), libMesh::InfElemBuilder::build_inf_elem(), libMesh::BoundaryInfo::build_node_list_from_side_list(), libMesh::DofMap::build_sparsity(), libMesh::DistributedMesh::clear(), libMesh::ExodusII_IO_Helper::close(), libMesh::Nemesis_IO_Helper::compute_border_node_ids(), libMesh::Nemesis_IO_Helper::compute_communication_map_parameters(), libMesh::Nemesis_IO_Helper::compute_internal_and_border_elems_and_internal_nodes(), libMesh::Nemesis_IO_Helper::compute_node_communication_maps(), libMesh::Nemesis_IO_Helper::compute_num_global_elem_blocks(), libMesh::Nemesis_IO_Helper::compute_num_global_nodesets(), libMesh::Nemesis_IO_Helper::compute_num_global_sidesets(), libMesh::Nemesis_IO_Helper::construct_nemesis_filename(), libMesh::MeshTools::correct_node_proc_ids(), libMesh::ExodusII_IO_Helper::create(), libMesh::DistributedMesh::delete_elem(), libMesh::DistributedMesh::delete_node(), libMesh::MeshCommunication::delete_remote_elements(), libMesh::DofMap::distribute_dofs(), libMesh::DofMap::distribute_local_dofs_node_major(), libMesh::DofMap::distribute_local_dofs_var_major(), libMesh::DistributedMesh::DistributedMesh(), libMesh::EnsightIO::EnsightIO(), libMesh::MeshFunction::find_element(), libMesh::MeshFunction::find_elements(), libMesh::UnstructuredMesh::find_neighbors(), libMesh::MeshCommunication::gather(), libMesh::MeshCommunication::gather_neighboring_elements(), libMesh::Nemesis_IO_Helper::get_cmap_params(), libMesh::Nemesis_IO_Helper::get_eb_info_global(), libMesh::Nemesis_IO_Helper::get_elem_cmap(), libMesh::Nemesis_IO_Helper::get_elem_map(), libMesh::MeshBase::get_info(), libMesh::DofMap::get_info(), libMesh::Nemesis_IO_Helper::get_init_global(), libMesh::Nemesis_IO_Helper::get_init_info(), libMesh::Nemesis_IO_Helper::get_loadbal_param(), libMesh::Nemesis_IO_Helper::get_node_cmap(), libMesh::Nemesis_IO_Helper::get_node_map(), libMesh::Nemesis_IO_Helper::get_ns_param_global(), libMesh::EquationSystems::get_solution(), libMesh::Nemesis_IO_Helper::get_ss_param_global(), libMesh::SparsityPattern::Build::handle_vi_vj(), libMesh::DistributedVector< T >::init(), libMesh::SystemSubsetBySubdomain::init(), libMesh::ParmetisPartitioner::initialize(), libMesh::ExodusII_IO_Helper::initialize(), libMesh::ExodusII_IO_Helper::initialize_element_variables(), libMesh::ExodusII_IO_Helper::initialize_global_variables(), libMesh::ExodusII_IO_Helper::initialize_nodal_variables(), libMesh::DistributedMesh::insert_elem(), libMesh::DofMap::is_evaluable(), libMesh::SparsityPattern::Build::join(), libMesh::MeshTools::libmesh_assert_parallel_consistent_procids< Elem >(), libMesh::MeshTools::libmesh_assert_parallel_consistent_procids< Node >(), libMesh::MeshTools::libmesh_assert_valid_neighbors(), libMesh::DistributedMesh::libmesh_assert_valid_parallel_object_ids(), libMesh::DofMap::local_variable_indices(), libMesh::MeshRefinement::make_coarsening_compatible(), libMesh::MeshBase::n_active_local_elem(), libMesh::BoundaryInfo::n_boundary_conds(), libMesh::BoundaryInfo::n_edge_conds(), libMesh::System::n_local_dofs(), libMesh::MeshBase::n_local_elem(), libMesh::MeshBase::n_local_nodes(), libMesh::BoundaryInfo::n_nodeset_conds(), libMesh::BoundaryInfo::n_shellface_conds(), libMesh::WeightedPatchRecoveryErrorEstimator::EstimateError::operator()(), libMesh::SparsityPattern::Build::operator()(), libMesh::PatchRecoveryErrorEstimator::EstimateError::operator()(), libMesh::SparsityPattern::Build::parallel_sync(), libMesh::MetisPartitioner::partition_range(), libMesh::System::point_gradient(), libMesh::System::point_hessian(), libMesh::System::point_value(), libMesh::SparseMatrix< T >::print(), libMesh::NumericVector< T >::print_global(), libMesh::Nemesis_IO_Helper::put_cmap_params(), libMesh::Nemesis_IO_Helper::put_elem_cmap(), libMesh::Nemesis_IO_Helper::put_elem_map(), libMesh::Nemesis_IO_Helper::put_loadbal_param(), libMesh::Nemesis_IO_Helper::put_node_cmap(), libMesh::Nemesis_IO_Helper::put_node_map(), libMesh::NameBasedIO::read(), libMesh::Nemesis_IO::read(), libMesh::XdrIO::read(), libMesh::ExodusII_IO_Helper::read_elem_num_map(), libMesh::ExodusII_IO_Helper::read_node_num_map(), libMesh::XdrIO::read_serialized_bc_names(), libMesh::XdrIO::read_serialized_bcs_helper(), libMesh::XdrIO::read_serialized_connectivity(), libMesh::XdrIO::read_serialized_nodes(), libMesh::XdrIO::read_serialized_nodesets(), libMesh::XdrIO::read_serialized_subdomain_names(), libMesh::MeshCommunication::redistribute(), libMesh::DistributedMesh::renumber_dof_objects(), libMesh::MeshCommunication::send_coarse_ghosts(), libMesh::Partitioner::set_node_processor_ids(), libMesh::DofMap::set_nonlocal_dof_objects(), libMesh::LaplaceMeshSmoother::smooth(), libMesh::MeshTools::total_weight(), libMesh::Parallel::Packing< Node * >::unpack(), libMesh::Parallel::Packing< Elem * >::unpack(), libMesh::DistributedMesh::update_parallel_id_counts(), libMesh::MeshTools::weight(), libMesh::NameBasedIO::write(), libMesh::XdrIO::write(), libMesh::EquationSystems::write(), libMesh::GMVIO::write_discontinuous_gmv(), libMesh::ExodusII_IO::write_element_data(), libMesh::ExodusII_IO_Helper::write_element_values(), libMesh::ExodusII_IO_Helper::write_elements(), libMesh::ExodusII_IO::write_global_data(), libMesh::ExodusII_IO_Helper::write_global_values(), libMesh::ExodusII_IO::write_information_records(), libMesh::ExodusII_IO_Helper::write_information_records(), libMesh::ExodusII_IO_Helper::write_nodal_coordinates(), libMesh::UCDIO::write_nodal_data(), libMesh::ExodusII_IO::write_nodal_data(), libMesh::ExodusII_IO::write_nodal_data_discontinuous(), libMesh::ExodusII_IO_Helper::write_nodal_values(), libMesh::Nemesis_IO_Helper::write_nodesets(), libMesh::ExodusII_IO_Helper::write_nodesets(), libMesh::XdrIO::write_serialized_bc_names(), libMesh::XdrIO::write_serialized_bcs_helper(), libMesh::XdrIO::write_serialized_connectivity(), libMesh::XdrIO::write_serialized_nodes(), libMesh::XdrIO::write_serialized_nodesets(), libMesh::XdrIO::write_serialized_subdomain_names(), libMesh::Nemesis_IO_Helper::write_sidesets(), libMesh::ExodusII_IO_Helper::write_sidesets(), libMesh::ExodusII_IO::write_timestep(), and libMesh::ExodusII_IO_Helper::write_timestep().
   { return cast_int<processor_id_type>(_communicator.rank()); }
template<typename T > void libMesh::LinearSolver< T >::restrict_solve_to (const std::vector< unsigned int > *const dofs, const SubsetSolveMode subset_solve_mode = SUBSET_ZERO) virtual inherited
After calling this method, all successive solves will be restricted to the given set of dofs, which must contain local dofs on each processor only and not contain any duplicates. This mode can be disabled by calling this method with dofs being a NULL pointer.
Reimplemented in libMesh::PetscLinearSolver< T >.
Definition at line 120 of file linear_solver.C.
References libmesh_nullptr.
Referenced by libMesh::LinearSolver< Number >::set_solver_type().
 {
   if (dofs != libmesh_nullptr)
     libmesh_not_implemented();
 }
template<typename T > void libMesh::LinearSolver< T >::reuse_preconditioner (bool reuse_flag) virtual inherited
Set the same_preconditioner flag, which indicates if we reuse the same preconditioner for subsequent solves.
Definition at line 113 of file linear_solver.C.
Referenced by libMesh::ImplicitSystem::disable_cache(), and libMesh::LinearSolver< Number >::set_solver_type().
 {
   same_preconditioner = reuse_flag;
 }
template<typename T > void libMesh::LinearSolver< T >::set_preconditioner_type (const PreconditionerType pct) inherited
Sets the type of preconditioner to use.
Definition at line 92 of file linear_solver.C.
Referenced by libMesh::LinearSolver< Number >::set_solver_type().
 {
   if(_preconditioner)
     _preconditioner->set_type(pct);
   else
     _preconditioner_type = pct;
 }
template<typename T > void libMesh::LinearSolver< T >::set_solver_configuration (SolverConfiguration & solver_configuration) inherited
Set the solver configuration object.
Definition at line 161 of file linear_solver.C.
Referenced by libMesh::LinearSolver< Number >::set_solver_type().
 {
   _solver_configuration = &solver_configuration;
 }
template<typename T> void libMesh::LinearSolver< T >::set_solver_type (const SolverType st) inline inherited
Sets the type of solver to use.
Definition at line 117 of file linear_solver.h.
   { _solver_type = st; }
template<typename T > void libMesh::AztecLinearSolver< T >::set_solver_type () private
Tells AztecOO to use the user-specified solver stored in _solver_type
Definition at line 236 of file trilinos_aztec_linear_solver.C.
References libMesh::BICGSTAB, libMesh::CG, libMesh::CGS, libMesh::Utility::enum_to_string(), libMesh::err, libMesh::GMRES, and libMesh::TFQMR.
Referenced by libMesh::AztecLinearSolver< T >::solve().
 {
   switch (this->_solver_type)
     {
     case CG:
       _linear_solver->SetAztecOption(AZ_solver, AZ_cg); return;
     case CGS:
       _linear_solver->SetAztecOption(AZ_solver, AZ_cgs); return;
     case TFQMR:
       _linear_solver->SetAztecOption(AZ_solver, AZ_tfqmr); return;
     case BICGSTAB:
       _linear_solver->SetAztecOption(AZ_solver, AZ_bicgstab); return;
     case GMRES:
       _linear_solver->SetAztecOption(AZ_solver, AZ_gmres); return;
     default:
       libMesh::err << "ERROR:  Unsupported AztecOO Solver: "
                    << Utility::enum_to_string(this->_solver_type) << std::endl
                    << "Continuing with AztecOO defaults" << std::endl;
     }
 }
template<typename T > virtual std::pair<unsigned int, Real> libMesh::AztecLinearSolver< T >::solve (SparseMatrix< T > & matrix_in, NumericVector< T > & solution_in, NumericVector< T > & rhs_in, const double tol, const unsigned int m_its) inline virtual
Call the Aztec solver. It calls the method below, using the same matrix for the system and preconditioner matrices.
Implements libMesh::LinearSolver< T >.
Definition at line 80 of file trilinos_aztec_linear_solver.h.
References libMesh::AztecLinearSolver< T >::get_converged_reason(), libMesh::AztecLinearSolver< T >::get_initial_residual(), libMesh::AztecLinearSolver< T >::get_residual_history(), libMesh::AztecLinearSolver< T >::print_converged_reason(), libMesh::Real, and libMesh::AztecLinearSolver< T >::set_solver_type().
   {
     return this->solve(matrix_in, matrix_in, solution_in, rhs_in, tol, m_its);
   }
template<typename T > std::pair< unsigned int, Real > libMesh::AztecLinearSolver< T >::solve (SparseMatrix< T > & matrix, SparseMatrix< T > & preconditioner, NumericVector< T > & solution, NumericVector< T > & rhs, const double tol, const unsigned int m_its) virtual
This method allows you to call a linear solver while specifying the matrix to use as the (left) preconditioning matrix. Note that the linear solver will not compute a preconditioner in this case, and will instead premultiply by the matrix you provide.
Implements libMesh::LinearSolver< T >.
Definition at line 103 of file trilinos_aztec_linear_solver.C.
References libMesh::EpetraMatrix< T >::close(), libMesh::TriangleWrapper::init(), and libMesh::EpetraMatrix< T >::mat().
 {
   LOG_SCOPE("solve()", "AztecLinearSolver");
   // Make sure the data passed in are really of Epetra types
   EpetraMatrix<T> * matrix   = cast_ptr<EpetraMatrix<T> *>(&matrix_in);
   EpetraMatrix<T> * precond  = cast_ptr<EpetraMatrix<T> *>(&precond_in);
   EpetraVector<T> * solution = cast_ptr<EpetraVector<T> *>(&solution_in);
   EpetraVector<T> * rhs      = cast_ptr<EpetraVector<T> *>(&rhs_in);
   this->init();
   // Close the matrices and vectors in case this wasn't already done.
   matrix->close ();
   precond->close ();
   solution->close ();
   rhs->close ();
   _linear_solver->SetAztecOption(AZ_max_iter,m_its);
   _linear_solver->SetAztecParam(AZ_tol,tol);
   Epetra_FECrsMatrix * emat = matrix->mat();
   Epetra_Vector * esol = solution->vec();
   Epetra_Vector * erhs = rhs->vec();
   _linear_solver->Iterate(emat, esol, erhs, m_its, tol);
   // return the # of its. and the final residual norm.
   return std::make_pair(_linear_solver->NumIters(), _linear_solver->TrueResidual());
 }
template<typename T > std::pair< unsigned int, Real > libMesh::AztecLinearSolver< T >::solve (const ShellMatrix< T > & shell_matrix, NumericVector< T > & solution_in, NumericVector< T > & rhs_in, const double tol, const unsigned int m_its) virtual
This function solves a system whose matrix is a shell matrix.
Implements libMesh::LinearSolver< T >.
Definition at line 143 of file trilinos_aztec_linear_solver.C.
 {
   libmesh_not_implemented();
 }
template<typename T > std::pair< unsigned int, Real > libMesh::AztecLinearSolver< T >::solve (const ShellMatrix< T > & shell_matrix, const SparseMatrix< T > & precond_matrix, NumericVector< T > & solution_in, NumericVector< T > & rhs_in, const double tol, const unsigned int m_its) virtual
This function solves a system whose matrix is a shell matrix, but a sparse matrix is used as preconditioning matrix, this allowing other preconditioners than JACOBI.
Implements libMesh::LinearSolver< T >.
Definition at line 156 of file trilinos_aztec_linear_solver.C.
 {
   libmesh_not_implemented();
 }
template<typename T> std::pair< unsigned int, Real > libMesh::LinearSolver< T >::solve (SparseMatrix< T > & matrix, SparseMatrix< T > * precond_matrix, NumericVector< T > & sol, NumericVector< T > & rhs, const double tol, const unsigned int n_iter) inline inherited
This function calls the solver "_solver_type" preconditioned with the "_preconditioner_type" preconditioner. The preconditioning matrix is used if it is provided, or the system matrix is used if precond_matrix is null
Definition at line 332 of file linear_solver.h.
References libMesh::LinearSolver< T >::solve().
 {
   if (pc_mat)
     return this->solve(mat, *pc_mat, sol, rhs, tol, n_iter);
   else
     return this->solve(mat, sol, rhs, tol, n_iter);
 }
template<typename T> std::pair< unsigned int, Real > libMesh::LinearSolver< T >::solve (const ShellMatrix< T > & matrix, const SparseMatrix< T > * precond_matrix, NumericVector< T > & sol, NumericVector< T > & rhs, const double tol, const unsigned int n_iter) inline inherited
This function solves a system whose matrix is a shell matrix, but an optional sparse matrix may be used as preconditioning matrix.
Definition at line 349 of file linear_solver.h.
References libMesh::LinearSolver< T >::solve().
 {
   if (pc_mat)
     return this->solve(mat, *pc_mat, sol, rhs, tol, n_iter);
   else
     return this->solve(mat, sol, rhs, tol, n_iter);
 }
template<typename T> SolverType libMesh::LinearSolver< T >::solver_type () const inline inherited
Returns the type of solver to use.
Definition at line 112 of file linear_solver.h.
 { return _solver_type; }
Member Data Documentation
const Parallel::Communicator& libMesh::ParallelObject::_communicator protected inherited
Definition at line 105 of file parallel_object.h.
Referenced by libMesh::EquationSystems::build_parallel_solution_vector(), libMesh::ParallelObject::comm(), libMesh::EquationSystems::get_solution(), libMesh::ParallelObject::n_processors(), libMesh::ParallelObject::operator=(), and libMesh::ParallelObject::processor_id().
ReferenceCounter::Counts libMesh::ReferenceCounter::_counts static protected inherited
Actually holds the data.
Definition at line 115 of file reference_counter.h.
Referenced by libMesh::ReferenceCounter::get_info(), libMesh::ReferenceCounter::increment_constructor_count(), and libMesh::ReferenceCounter::increment_destructor_count().
bool libMesh::ReferenceCounter::_enable_print_counter = true static protected inherited
Flag to control whether reference count information is printed when print_info is called.
Definition at line 134 of file reference_counter.h.
Referenced by libMesh::ReferenceCounter::disable_print_counter_info(), libMesh::ReferenceCounter::enable_print_counter_info(), and libMesh::ReferenceCounter::print_info().
template<typename T> bool libMesh::LinearSolver< T >::_is_initialized protected inherited
Flag indicating if the data structures have been initialized.
Definition at line 274 of file linear_solver.h.
Referenced by libMesh::EigenSparseLinearSolver< T >::clear(), libMesh::EigenSparseLinearSolver< T >::init(), and libMesh::LinearSolver< Number >::initialized().
template<typename T > Epetra_LinearProblem* libMesh::AztecLinearSolver< T >::_linear_problem private
The Epetra linear problem object.
Definition at line 162 of file trilinos_aztec_linear_solver.h.
template<typename T > AztecOO* libMesh::AztecLinearSolver< T >::_linear_solver private
The AztecOO solver object
Definition at line 167 of file trilinos_aztec_linear_solver.h.
Threads::spin_mutex libMesh::ReferenceCounter::_mutex static protected inherited
Mutual exclusion object to enable thread-safe reference counting.
Definition at line 128 of file reference_counter.h.
Threads::atomic< unsigned int > libMesh::ReferenceCounter::_n_objects static protected inherited
The number of objects. Print the reference count information when the number returns to 0.
Definition at line 123 of file reference_counter.h.
Referenced by libMesh::ReferenceCounter::n_objects(), libMesh::ReferenceCounter::ReferenceCounter(), and libMesh::ReferenceCounter::~ReferenceCounter().
template<typename T> Preconditioner<T>* libMesh::LinearSolver< T >::_preconditioner protected inherited
Holds the Preconditioner object to be used for the linear solves.
Definition at line 279 of file linear_solver.h.
template<typename T> PreconditionerType libMesh::LinearSolver< T >::_preconditioner_type protected inherited
Enum statitng with type of preconditioner to use.
Definition at line 269 of file linear_solver.h.
Referenced by libMesh::AztecLinearSolver< T >::AztecLinearSolver(), libMesh::EigenSparseLinearSolver< T >::clear(), and libMesh::PetscLinearSolver< T >::PetscLinearSolver().
template<typename T> SolverConfiguration* libMesh::LinearSolver< T >::_solver_configuration protected inherited
Optionally store a SolverOptions object that can be used to set parameters like solver type, tolerances and iteration limits.
Definition at line 293 of file linear_solver.h.
Referenced by libMesh::EigenSparseLinearSolver< T >::solve().
template<typename T> SolverType libMesh::LinearSolver< T >::_solver_type protected inherited
Enum stating which type of iterative solver to use.
Definition at line 264 of file linear_solver.h.
Referenced by libMesh::EigenSparseLinearSolver< T >::clear(), libMesh::EigenSparseLinearSolver< T >::EigenSparseLinearSolver(), libMesh::LinearSolver< Number >::set_solver_type(), libMesh::EigenSparseLinearSolver< T >::solve(), and libMesh::LinearSolver< Number >::solver_type().
template<typename T> bool libMesh::LinearSolver< T >::same_preconditioner protected inherited
Boolean flag to indicate whether we want to use an identical preconditioner to the previous solve. This can save substantial work in the cases where the system matrix is the same for successive solves.
Definition at line 287 of file linear_solver.h.
Referenced by libMesh::LinearSolver< T >::get_same_preconditioner().
The documentation for this class was generated from the following files:
trilinos_aztec_linear_solver.h
trilinos_aztec_linear_solver.C