libMesh: libMesh::SolverConfiguration Class Reference
SomeWebsiteLogo
libMesh::SolverConfiguration Class Reference abstract
#include <solver_configuration.h>
Public Member Functions
SolverConfiguration ()
virtual ~SolverConfiguration ()
virtual void set_options_during_init ()
virtual void configure_solver ()=0
virtual void respond_to_solve_failure (unsigned int)
Static Public Member Functions
static std::string get_info ()
static void print_info (std::ostream &out=libMesh::out)
static unsigned int n_objects ()
static void enable_print_counter_info ()
static void disable_print_counter_info ()
Public Attributes
std::map< std::string, Real > real_valued_data
std::map< std::string, int > int_valued_data
std::map< std::string, std::string > string_data
Protected Types
typedef std::map< std::string, std::pair< unsigned int, unsigned int > > Counts
Protected Member Functions
void increment_constructor_count (const std::string &name)
void increment_destructor_count (const std::string &name)
Static Protected Attributes
static Counts _counts
static Threads::atomic< unsigned int > _n_objects
static Threads::spin_mutex _mutex
static bool _enable_print_counter = true
Detailed Description
This class stores solver configuration data, e.g. tolerances and iteration limits. Override the pure virtual function configure_solver() in order to provide specific behavior for particular types of solvers (e.g. LinearSolver, EigenSolver, etc).
Author
David Knezevic
Date
2015
Definition at line 39 of file solver_configuration.h.
Member Typedef Documentation
typedef std::map<std::string, std::pair<unsigned int, unsigned int> > libMesh::ReferenceCounter::Counts protected inherited
Data structure to log the information. The log is identified by the class name.
Definition at line 119 of file reference_counter.h.
Constructor & Destructor Documentation
libMesh::SolverConfiguration::SolverConfiguration () inline
Constructor.
Definition at line 46 of file solver_configuration.h.
 {}
virtual libMesh::SolverConfiguration::~SolverConfiguration () inline virtual
Destructor.
Definition at line 51 of file solver_configuration.h.
 {}
Member Function Documentation
virtual void libMesh::SolverConfiguration::configure_solver () pure virtual
Apply solver options to a particular solver. Override in subclasses to provide specific behavior.
Referenced by set_options_during_init(), and libMesh::PetscNonlinearSolver< T >::solve().
void libMesh::ReferenceCounter::disable_print_counter_info () static inherited
Definition at line 107 of file reference_counter.C.
References libMesh::ReferenceCounter::_enable_print_counter.
Referenced by libMesh::LibMeshInit::LibMeshInit(), and libMesh::ReferenceCounter::n_objects().
 {
   _enable_print_counter = false;
   return;
 }
void libMesh::ReferenceCounter::enable_print_counter_info () static inherited
Methods to enable/disable the reference counter output from print_info()
Definition at line 101 of file reference_counter.C.
References libMesh::ReferenceCounter::_enable_print_counter.
Referenced by libMesh::ReferenceCounter::n_objects().
 {
   _enable_print_counter = true;
   return;
 }
std::string libMesh::ReferenceCounter::get_info () static inherited
Gets a string containing the reference information.
Definition at line 47 of file reference_counter.C.
References libMesh::ReferenceCounter::_counts, and libMesh::Quality::name().
Referenced by libMesh::ReferenceCounter::print_info().
 {
 #if defined(LIBMESH_ENABLE_REFERENCE_COUNTING) && defined(DEBUG)
   std::ostringstream oss;
   oss << '\n'
       << " ---------------------------------------------------------------------------- \n"
       << "| Reference count information                                                |\n"
       << " ---------------------------------------------------------------------------- \n";
   for (Counts::iterator it = _counts.begin();
        it != _counts.end(); ++it)
     {
       const std::string name(it->first);
       const unsigned int creations    = it->second.first;
       const unsigned int destructions = it->second.second;
       oss << "| " << name << " reference count information:\n"
           << "|  Creations:    " << creations    << '\n'
           << "|  Destructions: " << destructions << '\n';
     }
   oss << " ---------------------------------------------------------------------------- \n";
   return oss.str();
 #else
   return "";
 #endif
 }
void libMesh::ReferenceCounter::increment_constructor_count (const std::string & name) inline protected inherited
Increments the construction counter. Should be called in the constructor of any derived class that will be reference counted.
Definition at line 185 of file reference_counter.h.
References libMesh::ReferenceCounter::_counts, libMesh::Quality::name(), and libMesh::Threads::spin_mtx.
Referenced by libMesh::ReferenceCounter::n_objects(), and libMesh::ReferenceCountedObject< RBParametrized >::ReferenceCountedObject().
 {
   Threads::spin_mutex::scoped_lock lock(Threads::spin_mtx);
   std::pair<unsigned int, unsigned int> & p = _counts[name];
   p.first++;
 }
void libMesh::ReferenceCounter::increment_destructor_count (const std::string & name) inline protected inherited
Increments the destruction counter. Should be called in the destructor of any derived class that will be reference counted.
Definition at line 198 of file reference_counter.h.
References libMesh::ReferenceCounter::_counts, libMesh::Quality::name(), and libMesh::Threads::spin_mtx.
Referenced by libMesh::ReferenceCounter::n_objects(), and libMesh::ReferenceCountedObject< RBParametrized >::~ReferenceCountedObject().
 {
   Threads::spin_mutex::scoped_lock lock(Threads::spin_mtx);
   std::pair<unsigned int, unsigned int> & p = _counts[name];
   p.second++;
 }
static unsigned int libMesh::ReferenceCounter::n_objects () inline static inherited
Prints the number of outstanding (created, but not yet destroyed) objects.
Definition at line 85 of file reference_counter.h.
References libMesh::ReferenceCounter::_n_objects, libMesh::ReferenceCounter::disable_print_counter_info(), libMesh::ReferenceCounter::enable_print_counter_info(), libMesh::ReferenceCounter::increment_constructor_count(), libMesh::ReferenceCounter::increment_destructor_count(), and libMesh::Quality::name().
Referenced by libMesh::System::hide_output(), and libMesh::LibMeshInit::LibMeshInit().
   { return _n_objects; }
void libMesh::ReferenceCounter::print_info (std::ostream & out = libMesh::out) static inherited
Prints the reference information, by default to libMesh::out.
Definition at line 88 of file reference_counter.C.
References libMesh::ReferenceCounter::_enable_print_counter, and libMesh::ReferenceCounter::get_info().
Referenced by libMesh::LibMeshInit::LibMeshInit().
 {
   if (_enable_print_counter)
     out_stream << ReferenceCounter::get_info();
 }
virtual void libMesh::SolverConfiguration::respond_to_solve_failure (unsigned int) inline virtual
This method can be called after the solver has failed (e.g. on catching an exception thrown by a solver). It allows an appropriate response to the failure, e.g. terminate the program, or change configuation options and try again. solve_failure_count specifies the number of times we've tried to recover from a failure.
Definition at line 74 of file solver_configuration.h.
   {
     libmesh_error_msg("Solver error"); // by default just throw an error
   }
virtual void libMesh::SolverConfiguration::set_options_during_init () inline virtual
Apply options during initialization of a solver. Default is a no-op. Override in subclasses to provide specific behavior.
Definition at line 58 of file solver_configuration.h.
References configure_solver().
Referenced by libMesh::PetscNonlinearSolver< T >::init().
 {}
Member Data Documentation
ReferenceCounter::Counts libMesh::ReferenceCounter::_counts static protected inherited
Actually holds the data.
Definition at line 124 of file reference_counter.h.
Referenced by libMesh::ReferenceCounter::get_info(), libMesh::ReferenceCounter::increment_constructor_count(), and libMesh::ReferenceCounter::increment_destructor_count().
bool libMesh::ReferenceCounter::_enable_print_counter = true static protected inherited
Flag to control whether reference count information is printed when print_info is called.
Definition at line 143 of file reference_counter.h.
Referenced by libMesh::ReferenceCounter::disable_print_counter_info(), libMesh::ReferenceCounter::enable_print_counter_info(), and libMesh::ReferenceCounter::print_info().
Threads::spin_mutex libMesh::ReferenceCounter::_mutex static protected inherited
Mutual exclusion object to enable thread-safe reference counting.
Definition at line 137 of file reference_counter.h.
Threads::atomic< unsigned int > libMesh::ReferenceCounter::_n_objects static protected inherited
The number of objects. Print the reference count information when the number returns to 0.
Definition at line 132 of file reference_counter.h.
Referenced by libMesh::ReferenceCounter::n_objects(), libMesh::ReferenceCounter::ReferenceCounter(), and libMesh::ReferenceCounter::~ReferenceCounter().
std::map<std::string, int> libMesh::SolverConfiguration::int_valued_data
Store integer solver parameters in this map, e.g. iteration limits.
Definition at line 87 of file solver_configuration.h.
Referenced by libMesh::EigenSparseLinearSolver< T >::solve().
std::map<std::string, Real> libMesh::SolverConfiguration::real_valued_data
Store real-valued solver parameters in this map, e.g. solver tolerances.
Definition at line 82 of file solver_configuration.h.
std::map<std::string, std::string> libMesh::SolverConfiguration::string_data
Store string data in this map, e.g. "solver_type" : "gmres".
Definition at line 92 of file solver_configuration.h.
The documentation for this class was generated from the following file:
solver_configuration.h