libMesh: libMesh::EigenSolver< T > Class Template Reference
SomeWebsiteLogo
libMesh::EigenSolver< T > Class Template Reference abstract
Base class which defines the interface for solving eigenproblems.
#include <eigen_solver.h>
Public Member Functions
EigenSolver (const Parallel::Communicator &comm_in LIBMESH_CAN_DEFAULT_TO_COMMWORLD)
virtual ~EigenSolver ()
bool initialized () const
virtual void clear ()
virtual void init ()=0
EigenSolverType eigen_solver_type () const
EigenProblemType eigen_problem_type () const
PositionOfSpectrum position_of_spectrum () const
void set_eigensolver_type (const EigenSolverType est)
void set_eigenproblem_type (EigenProblemType ept)
void set_position_of_spectrum (PositionOfSpectrum pos)
void set_position_of_spectrum (Real pos)
void set_position_of_spectrum (Real pos, PositionOfSpectrum target)
virtual std::pair< unsigned int, unsigned int > solve_standard (SparseMatrix< T > &matrix_A, int nev, int ncv, const double tol, const unsigned int m_its)=0
virtual std::pair< unsigned int, unsigned int > solve_standard (ShellMatrix< T > &matrix_A, int nev, int ncv, const double tol, const unsigned int m_its)=0
virtual std::pair< unsigned int, unsigned int > solve_generalized (SparseMatrix< T > &matrix_A, SparseMatrix< T > &matrix_B, int nev, int ncv, const double tol, const unsigned int m_its)=0
virtual std::pair< unsigned int, unsigned int > solve_generalized (ShellMatrix< T > &matrix_A, SparseMatrix< T > &matrix_B, int nev, int ncv, const double tol, const unsigned int m_its)=0
virtual std::pair< unsigned int, unsigned int > solve_generalized (SparseMatrix< T > &matrix_A, ShellMatrix< T > &matrix_B, int nev, int ncv, const double tol, const unsigned int m_its)=0
virtual std::pair< unsigned int, unsigned int > solve_generalized (ShellMatrix< T > &matrix_A, ShellMatrix< T > &matrix_B, int nev, int ncv, const double tol, const unsigned int m_its)=0
virtual std::pair< Real, Real > get_eigenpair (dof_id_type i, NumericVector< T > &solution)=0
virtual std::pair< Real, Real > get_eigenvalue (dof_id_type i)=0
virtual void attach_deflation_space (NumericVector< T > &deflation_vector)=0
virtual void set_initial_space (NumericVector< T > &initial_space_in)=0
void set_solver_configuration (SolverConfiguration &solver_configuration)
const Parallel::Communicator & comm () const
processor_id_type n_processors () const
processor_id_type processor_id () const
Static Public Member Functions
static UniquePtr< EigenSolver< T > > build (const Parallel::Communicator &comm_in LIBMESH_CAN_DEFAULT_TO_COMMWORLD, const SolverPackage solver_package=SLEPC_SOLVERS)
static std::string get_info ()
static void print_info (std::ostream &out=libMesh::out)
static unsigned int n_objects ()
static void enable_print_counter_info ()
static void disable_print_counter_info ()
Protected Types
typedef std::map< std::string, std::pair< unsigned int, unsigned int > > Counts
Protected Member Functions
void increment_constructor_count (const std::string &name)
void increment_destructor_count (const std::string &name)
Protected Attributes
EigenSolverType _eigen_solver_type
EigenProblemType _eigen_problem_type
PositionOfSpectrum _position_of_spectrum
bool _is_initialized
SolverConfiguration * _solver_configuration
Real _target_val
const Parallel::Communicator & _communicator
Static Protected Attributes
static Counts _counts
static Threads::atomic< unsigned int > _n_objects
static Threads::spin_mutex _mutex
static bool _enable_print_counter = true
Detailed Description
template<typename T>
class libMesh::EigenSolver< T >
Base class which defines the interface for solving eigenproblems.
This class provides an interface to solvers for eigenvalue problems.
Author
Steffen Peterson
Date
2005
Definition at line 54 of file eigen_solver.h.
Member Typedef Documentation
typedef std::map<std::string, std::pair<unsigned int, unsigned int> > libMesh::ReferenceCounter::Counts protected inherited
Data structure to log the information. The log is identified by the class name.
Definition at line 119 of file reference_counter.h.
Constructor & Destructor Documentation
template<typename T > libMesh::EigenSolver< T >::EigenSolver (const Parallel::Communicator &comm_in LIBMESH_CAN_DEFAULT_TO_COMMWORLD) inline
Constructor. Initializes Solver data structures
Definition at line 280 of file eigen_solver.h.
                                                                  :
   ParallelObject(comm_in),
   _eigen_solver_type    (ARNOLDI),
   _eigen_problem_type   (NHEP),
   _position_of_spectrum (LARGEST_MAGNITUDE),
   _is_initialized       (false),
   _solver_configuration(libmesh_nullptr)
 {
 }
template<typename T > libMesh::EigenSolver< T >::~EigenSolver () inline virtual
Destructor.
Definition at line 294 of file eigen_solver.h.
References libMesh::EigenSolver< T >::clear().
 {
   this->clear ();
 }
Member Function Documentation
template<typename T > virtual void libMesh::EigenSolver< T >::attach_deflation_space (NumericVector< T > & deflation_vector) pure virtual
Attach a deflation space defined by a single vector.
Implemented in libMesh::SlepcEigenSolver< T >.
Referenced by libMesh::EigenSolver< T >::set_position_of_spectrum().
template<typename T > UniquePtr< EigenSolver< T > > libMesh::EigenSolver< T >::build (const Parallel::Communicator &comm_in LIBMESH_CAN_DEFAULT_TO_COMMWORLD, const SolverPackage solver_package = SLEPC_SOLVERS) static
Builds an EigenSolver using the linear solver package specified by solver_package
Definition at line 37 of file eigen_solver.C.
References libMesh::SLEPC_SOLVERS.
 {
   // Build the appropriate solver
   switch (solver_package)
     {
 #ifdef LIBMESH_HAVE_SLEPC
     case SLEPC_SOLVERS:
       return UniquePtr<EigenSolver<T> >(new SlepcEigenSolver<T>(comm));
 #endif
     default:
       libmesh_error_msg("ERROR:  Unrecognized eigen solver package: " << solver_package);
     }
   return UniquePtr<EigenSolver<T> >();
 }
template<typename T > virtual void libMesh::EigenSolver< T >::clear () inline virtual
Release all memory and clear data structures.
Reimplemented in libMesh::SlepcEigenSolver< T >.
Definition at line 88 of file eigen_solver.h.
References libMesh::EigenSolver< T >::init().
Referenced by libMesh::EigenSolver< T >::~EigenSolver().
 {}
const Parallel::Communicator& libMesh::ParallelObject::comm () const inline inherited
Returns
A reference to the Parallel::Communicator object used by this mesh.
Definition at line 87 of file parallel_object.h.
References libMesh::ParallelObject::_communicator.
Referenced by libMesh::__libmesh_petsc_diff_solver_monitor(), libMesh::__libmesh_petsc_diff_solver_residual(), libMesh::__libmesh_petsc_snes_jacobian(), libMesh::__libmesh_petsc_snes_postcheck(), libMesh::__libmesh_petsc_snes_residual(), libMesh::__libmesh_tao_equality_constraints(), libMesh::__libmesh_tao_equality_constraints_jacobian(), libMesh::__libmesh_tao_gradient(), libMesh::__libmesh_tao_hessian(), libMesh::__libmesh_tao_inequality_constraints(), libMesh::__libmesh_tao_inequality_constraints_jacobian(), libMesh::__libmesh_tao_objective(), libMesh::MeshRefinement::_coarsen_elements(), libMesh::ExactSolution::_compute_error(), libMesh::ParmetisPartitioner::_do_repartition(), libMesh::UniformRefinementEstimator::_estimate_error(), libMesh::BoundaryInfo::_find_id_maps(), libMesh::PetscLinearSolver< T >::_petsc_shell_matrix_get_diagonal(), libMesh::SlepcEigenSolver< T >::_petsc_shell_matrix_get_diagonal(), libMesh::PetscLinearSolver< T >::_petsc_shell_matrix_mult(), libMesh::SlepcEigenSolver< T >::_petsc_shell_matrix_mult(), libMesh::PetscLinearSolver< T >::_petsc_shell_matrix_mult_add(), libMesh::EquationSystems::_read_impl(), libMesh::MeshRefinement::_refine_elements(), libMesh::MeshRefinement::_smooth_flags(), libMesh::ImplicitSystem::add_matrix(), libMesh::System::add_vector(), libMesh::EigenSparseLinearSolver< T >::adjoint_solve(), libMesh::UnstructuredMesh::all_second_order(), libMesh::MeshTools::Modification::all_tri(), libMesh::LaplaceMeshSmoother::allgather_graph(), libMesh::FEMSystem::assemble_qoi(), libMesh::MeshCommunication::assign_global_indices(), libMesh::ParmetisPartitioner::assign_partitioning(), libMesh::DofMap::attach_matrix(), libMesh::Parallel::BinSorter< KeyType, IdxType >::binsort(), libMesh::Parallel::Sort< KeyType, IdxType >::binsort(), libMesh::MeshCommunication::broadcast(), libMesh::SparseMatrix< T >::build(), libMesh::MeshTools::Generation::build_extrusion(), libMesh::Parallel::Histogram< KeyType, IdxType >::build_histogram(), libMesh::PetscNonlinearSolver< T >::build_mat_null_space(), libMesh::BoundaryInfo::build_node_list_from_side_list(), libMesh::EquationSystems::build_parallel_solution_vector(), libMesh::MeshBase::cache_elem_dims(), libMesh::System::calculate_norm(), libMesh::DofMap::check_dirichlet_bcid_consistency(), libMesh::DistributedVector< T >::clone(), libMesh::EigenSparseVector< T >::clone(), libMesh::LaspackVector< T >::clone(), libMesh::EpetraVector< T >::clone(), libMesh::PetscVector< T >::clone(), libMesh::EpetraVector< T >::close(), libMesh::Parallel::Sort< KeyType, IdxType >::communicate_bins(), libMesh::Nemesis_IO_Helper::compute_num_global_elem_blocks(), libMesh::Nemesis_IO_Helper::compute_num_global_nodesets(), libMesh::Nemesis_IO_Helper::compute_num_global_sidesets(), libMesh::Problem_Interface::computeF(), libMesh::Problem_Interface::computeJacobian(), libMesh::Problem_Interface::computePreconditioner(), libMesh::MeshTools::correct_node_proc_ids(), libMesh::MeshTools::create_bounding_box(), libMesh::MeshTools::create_nodal_bounding_box(), libMesh::MeshRefinement::create_parent_error_vector(), libMesh::MeshTools::create_processor_bounding_box(), libMesh::MeshTools::create_subdomain_bounding_box(), libMesh::MeshCommunication::delete_remote_elements(), libMesh::DofMap::distribute_dofs(), DMlibMeshFunction(), DMlibMeshJacobian(), DMlibMeshSetSystem_libMesh(), DMVariableBounds_libMesh(), libMesh::MeshRefinement::eliminate_unrefined_patches(), libMesh::EpetraVector< T >::EpetraVector(), libMesh::WeightedPatchRecoveryErrorEstimator::estimate_error(), libMesh::PatchRecoveryErrorEstimator::estimate_error(), libMesh::JumpErrorEstimator::estimate_error(), libMesh::AdjointRefinementEstimator::estimate_error(), libMesh::ExactErrorEstimator::estimate_error(), libMesh::MeshRefinement::flag_elements_by_elem_fraction(), libMesh::MeshRefinement::flag_elements_by_error_fraction(), libMesh::MeshRefinement::flag_elements_by_nelem_target(), libMesh::MeshCommunication::gather(), libMesh::MeshCommunication::gather_neighboring_elements(), libMesh::CondensedEigenSystem::get_eigenpair(), libMesh::DofMap::get_info(), libMesh::ImplicitSystem::get_linear_solver(), libMesh::EquationSystems::get_solution(), libMesh::LocationMap< T >::init(), libMesh::PetscDiffSolver::init(), libMesh::TimeSolver::init(), libMesh::TopologyMap::init(), libMesh::TaoOptimizationSolver< T >::init(), libMesh::PetscNonlinearSolver< T >::init(), libMesh::DistributedVector< T >::init(), libMesh::EpetraVector< T >::init(), libMesh::PetscVector< T >::init(), libMesh::SystemSubsetBySubdomain::init(), libMesh::EigenSystem::init_data(), libMesh::EigenSystem::init_matrices(), libMesh::ParmetisPartitioner::initialize(), libMesh::OptimizationSystem::initialize_equality_constraints_storage(), libMesh::OptimizationSystem::initialize_inequality_constraints_storage(), libMesh::MeshTools::libmesh_assert_parallel_consistent_procids< Elem >(), libMesh::MeshTools::libmesh_assert_parallel_consistent_procids< Node >(), libMesh::MeshTools::libmesh_assert_topology_consistent_procids< Node >(), libMesh::MeshTools::libmesh_assert_valid_boundary_ids(), libMesh::MeshTools::libmesh_assert_valid_dof_ids(), libMesh::MeshTools::libmesh_assert_valid_neighbors(), libMesh::DistributedMesh::libmesh_assert_valid_parallel_flags(), libMesh::DistributedMesh::libmesh_assert_valid_parallel_object_ids(), libMesh::DistributedMesh::libmesh_assert_valid_parallel_p_levels(), libMesh::MeshTools::libmesh_assert_valid_refinement_flags(), libMesh::MeshTools::libmesh_assert_valid_unique_ids(), libMesh::MeshRefinement::limit_level_mismatch_at_edge(), libMesh::MeshRefinement::limit_level_mismatch_at_node(), libMesh::MeshRefinement::limit_overrefined_boundary(), libMesh::MeshRefinement::limit_underrefined_boundary(), libMesh::MeshRefinement::make_coarsening_compatible(), libMesh::MeshCommunication::make_elems_parallel_consistent(), libMesh::MeshRefinement::make_flags_parallel_consistent(), libMesh::MeshCommunication::make_new_node_proc_ids_parallel_consistent(), libMesh::MeshCommunication::make_new_nodes_parallel_consistent(), libMesh::MeshCommunication::make_node_ids_parallel_consistent(), libMesh::MeshCommunication::make_node_proc_ids_parallel_consistent(), libMesh::MeshCommunication::make_node_unique_ids_parallel_consistent(), libMesh::MeshCommunication::make_nodes_parallel_consistent(), libMesh::MeshCommunication::make_p_levels_parallel_consistent(), libMesh::MeshRefinement::make_refinement_compatible(), libMesh::DistributedVector< T >::max(), libMesh::FEMSystem::mesh_position_set(), libMesh::MeshSerializer::MeshSerializer(), libMesh::DistributedVector< T >::min(), libMesh::DistributedMesh::n_active_elem(), libMesh::MeshTools::n_active_levels(), libMesh::BoundaryInfo::n_boundary_conds(), libMesh::BoundaryInfo::n_edge_conds(), libMesh::CondensedEigenSystem::n_global_non_condensed_dofs(), libMesh::MeshTools::n_levels(), libMesh::BoundaryInfo::n_nodeset_conds(), libMesh::MeshTools::n_p_levels(), libMesh::BoundaryInfo::n_shellface_conds(), libMesh::DistributedMesh::parallel_max_elem_id(), libMesh::DistributedMesh::parallel_max_node_id(), libMesh::ReplicatedMesh::parallel_max_unique_id(), libMesh::DistributedMesh::parallel_max_unique_id(), libMesh::DistributedMesh::parallel_n_elem(), libMesh::DistributedMesh::parallel_n_nodes(), libMesh::SparsityPattern::Build::parallel_sync(), libMesh::MeshTools::paranoid_n_levels(), libMesh::Partitioner::partition(), libMesh::MetisPartitioner::partition_range(), libMesh::Partitioner::partition_unpartitioned_elements(), libMesh::petsc_auto_fieldsplit(), libMesh::System::point_gradient(), libMesh::System::point_hessian(), libMesh::System::point_value(), libMesh::MeshBase::prepare_for_use(), libMesh::SparseMatrix< T >::print(), libMesh::Nemesis_IO::read(), libMesh::CheckpointIO::read(), libMesh::XdrIO::read(), libMesh::XdrIO::read_serialized_bc_names(), libMesh::XdrIO::read_serialized_bcs_helper(), libMesh::XdrIO::read_serialized_connectivity(), libMesh::XdrIO::read_serialized_nodes(), libMesh::XdrIO::read_serialized_nodesets(), libMesh::XdrIO::read_serialized_subdomain_names(), libMesh::MeshBase::recalculate_n_partitions(), libMesh::MeshCommunication::redistribute(), libMesh::DistributedMesh::renumber_dof_objects(), libMesh::MeshCommunication::send_coarse_ghosts(), libMesh::Partitioner::set_node_processor_ids(), libMesh::DofMap::set_nonlocal_dof_objects(), libMesh::Partitioner::set_parent_processor_ids(), libMesh::LaplaceMeshSmoother::smooth(), libMesh::Parallel::Sort< KeyType, IdxType >::sort(), libMesh::MeshBase::subdomain_ids(), libMesh::BoundaryInfo::sync(), libMesh::Parallel::sync_element_data_by_parent_id(), libMesh::Parallel::sync_node_data_by_element_id(), libMesh::MeshRefinement::test_level_one(), libMesh::MeshRefinement::test_unflagged(), libMesh::MeshTools::total_weight(), libMesh::MeshRefinement::uniformly_coarsen(), libMesh::NameBasedIO::write(), libMesh::XdrIO::write(), libMesh::XdrIO::write_serialized_bcs_helper(), libMesh::XdrIO::write_serialized_connectivity(), libMesh::XdrIO::write_serialized_nodes(), libMesh::XdrIO::write_serialized_nodesets(), libMesh::DistributedVector< T >::zero_clone(), libMesh::LaspackVector< T >::zero_clone(), libMesh::EigenSparseVector< T >::zero_clone(), libMesh::EpetraVector< T >::zero_clone(), and libMesh::PetscVector< T >::zero_clone().
   { return _communicator; }
void libMesh::ReferenceCounter::disable_print_counter_info () static inherited
Definition at line 107 of file reference_counter.C.
References libMesh::ReferenceCounter::_enable_print_counter.
Referenced by libMesh::LibMeshInit::LibMeshInit(), and libMesh::ReferenceCounter::n_objects().
 {
   _enable_print_counter = false;
   return;
 }
template<typename T > EigenProblemType libMesh::EigenSolver< T >::eigen_problem_type () const inline
Returns
The type of the eigen problem.
Definition at line 103 of file eigen_solver.h.
References libMesh::EigenSolver< T >::_eigen_problem_type.
 { return _eigen_problem_type;}
template<typename T > EigenSolverType libMesh::EigenSolver< T >::eigen_solver_type () const inline
Returns
The type of eigensolver to use.
Definition at line 98 of file eigen_solver.h.
References libMesh::EigenSolver< T >::_eigen_solver_type.
 { return _eigen_solver_type; }
void libMesh::ReferenceCounter::enable_print_counter_info () static inherited
Methods to enable/disable the reference counter output from print_info()
Definition at line 101 of file reference_counter.C.
References libMesh::ReferenceCounter::_enable_print_counter.
Referenced by libMesh::ReferenceCounter::n_objects().
 {
   _enable_print_counter = true;
   return;
 }
template<typename T > virtual std::pair<Real, Real> libMesh::EigenSolver< T >::get_eigenpair (dof_id_type i, NumericVector< T > & solution) pure virtual
Returns
The ith eigenvalue (real and imaginary part), and copies the ith eigenvector into the solution vector.
Implemented in libMesh::SlepcEigenSolver< T >.
Referenced by libMesh::EigenSolver< T >::set_position_of_spectrum().
template<typename T > virtual std::pair<Real, Real> libMesh::EigenSolver< T >::get_eigenvalue (dof_id_type i) pure virtual
Returns
The ith eigenvalue (real and imaginary part).
Same as above function, except it does not copy the eigenvector.
Implemented in libMesh::SlepcEigenSolver< T >.
Referenced by libMesh::EigenSolver< T >::set_position_of_spectrum().
std::string libMesh::ReferenceCounter::get_info () static inherited
Gets a string containing the reference information.
Definition at line 47 of file reference_counter.C.
References libMesh::ReferenceCounter::_counts, and libMesh::Quality::name().
Referenced by libMesh::ReferenceCounter::print_info().
 {
 #if defined(LIBMESH_ENABLE_REFERENCE_COUNTING) && defined(DEBUG)
   std::ostringstream oss;
   oss << '\n'
       << " ---------------------------------------------------------------------------- \n"
       << "| Reference count information                                                |\n"
       << " ---------------------------------------------------------------------------- \n";
   for (Counts::iterator it = _counts.begin();
        it != _counts.end(); ++it)
     {
       const std::string name(it->first);
       const unsigned int creations    = it->second.first;
       const unsigned int destructions = it->second.second;
       oss << "| " << name << " reference count information:\n"
           << "|  Creations:    " << creations    << '\n'
           << "|  Destructions: " << destructions << '\n';
     }
   oss << " ---------------------------------------------------------------------------- \n";
   return oss.str();
 #else
   return "";
 #endif
 }
void libMesh::ReferenceCounter::increment_constructor_count (const std::string & name) inline protected inherited
Increments the construction counter. Should be called in the constructor of any derived class that will be reference counted.
Definition at line 185 of file reference_counter.h.
References libMesh::ReferenceCounter::_counts, libMesh::Quality::name(), and libMesh::Threads::spin_mtx.
Referenced by libMesh::ReferenceCounter::n_objects(), and libMesh::ReferenceCountedObject< RBParametrized >::ReferenceCountedObject().
 {
   Threads::spin_mutex::scoped_lock lock(Threads::spin_mtx);
   std::pair<unsigned int, unsigned int> & p = _counts[name];
   p.first++;
 }
void libMesh::ReferenceCounter::increment_destructor_count (const std::string & name) inline protected inherited
Increments the destruction counter. Should be called in the destructor of any derived class that will be reference counted.
Definition at line 198 of file reference_counter.h.
References libMesh::ReferenceCounter::_counts, libMesh::Quality::name(), and libMesh::Threads::spin_mtx.
Referenced by libMesh::ReferenceCounter::n_objects(), and libMesh::ReferenceCountedObject< RBParametrized >::~ReferenceCountedObject().
 {
   Threads::spin_mutex::scoped_lock lock(Threads::spin_mtx);
   std::pair<unsigned int, unsigned int> & p = _counts[name];
   p.second++;
 }
template<typename T > virtual void libMesh::EigenSolver< T >::init () pure virtual
Initialize data structures if not done so already.
Implemented in libMesh::SlepcEigenSolver< T >.
Referenced by libMesh::EigenSolver< T >::clear().
template<typename T > bool libMesh::EigenSolver< T >::initialized () const inline
Returns
true if the data structures are initialized, false otherwise.
Definition at line 82 of file eigen_solver.h.
References libMesh::EigenSolver< T >::_is_initialized.
 { return _is_initialized; }
static unsigned int libMesh::ReferenceCounter::n_objects () inline static inherited
Prints the number of outstanding (created, but not yet destroyed) objects.
Definition at line 85 of file reference_counter.h.
References libMesh::ReferenceCounter::_n_objects, libMesh::ReferenceCounter::disable_print_counter_info(), libMesh::ReferenceCounter::enable_print_counter_info(), libMesh::ReferenceCounter::increment_constructor_count(), libMesh::ReferenceCounter::increment_destructor_count(), and libMesh::Quality::name().
Referenced by libMesh::System::hide_output(), and libMesh::LibMeshInit::LibMeshInit().
   { return _n_objects; }
processor_id_type libMesh::ParallelObject::n_processors () const inline inherited
Returns
The number of processors in the group.
Definition at line 93 of file parallel_object.h.
References libMesh::ParallelObject::_communicator, and libMesh::Parallel::Communicator::size().
Referenced by libMesh::ParmetisPartitioner::_do_repartition(), libMesh::BoundaryInfo::_find_id_maps(), libMesh::DistributedMesh::add_elem(), libMesh::DistributedMesh::add_node(), libMesh::LaplaceMeshSmoother::allgather_graph(), libMesh::FEMSystem::assembly(), libMesh::ParmetisPartitioner::assign_partitioning(), libMesh::AztecLinearSolver< T >::AztecLinearSolver(), libMesh::MeshCommunication::broadcast(), libMesh::BoundaryInfo::build_node_list_from_side_list(), libMesh::DistributedMesh::clear(), libMesh::Nemesis_IO_Helper::compute_border_node_ids(), libMesh::Nemesis_IO_Helper::construct_nemesis_filename(), libMesh::MeshTools::correct_node_proc_ids(), libMesh::UnstructuredMesh::create_pid_mesh(), libMesh::MeshTools::create_processor_bounding_box(), libMesh::DofMap::distribute_dofs(), libMesh::DofMap::distribute_local_dofs_node_major(), libMesh::DofMap::distribute_local_dofs_var_major(), libMesh::DistributedMesh::DistributedMesh(), libMesh::EnsightIO::EnsightIO(), libMesh::MeshCommunication::gather(), libMesh::MeshCommunication::gather_neighboring_elements(), libMesh::MeshBase::get_info(), libMesh::EquationSystems::get_solution(), libMesh::DistributedVector< T >::init(), libMesh::SystemSubsetBySubdomain::init(), libMesh::ParmetisPartitioner::initialize(), libMesh::Nemesis_IO_Helper::initialize(), libMesh::DistributedMesh::insert_elem(), libMesh::MeshTools::libmesh_assert_parallel_consistent_procids< Elem >(), libMesh::MeshTools::libmesh_assert_parallel_consistent_procids< Node >(), libMesh::MeshTools::libmesh_assert_topology_consistent_procids< Node >(), libMesh::MeshTools::libmesh_assert_valid_boundary_ids(), libMesh::MeshTools::libmesh_assert_valid_dof_ids(), libMesh::MeshTools::libmesh_assert_valid_neighbors(), libMesh::MeshTools::libmesh_assert_valid_refinement_flags(), libMesh::DofMap::local_variable_indices(), libMesh::MeshRefinement::make_coarsening_compatible(), libMesh::MeshBase::n_active_elem_on_proc(), libMesh::MeshBase::n_elem_on_proc(), libMesh::MeshBase::n_nodes_on_proc(), libMesh::SparsityPattern::Build::parallel_sync(), libMesh::Partitioner::partition(), libMesh::MeshBase::partition(), libMesh::Partitioner::partition_unpartitioned_elements(), libMesh::PetscLinearSolver< T >::PetscLinearSolver(), libMesh::System::point_gradient(), libMesh::System::point_hessian(), libMesh::System::point_value(), libMesh::SparseMatrix< T >::print(), libMesh::NameBasedIO::read(), libMesh::Nemesis_IO::read(), libMesh::CheckpointIO::read(), libMesh::XdrIO::read(), libMesh::CheckpointIO::read_connectivity(), libMesh::CheckpointIO::read_nodes(), libMesh::MeshCommunication::redistribute(), libMesh::DistributedMesh::renumber_dof_objects(), libMesh::Partitioner::repartition(), libMesh::MeshCommunication::send_coarse_ghosts(), libMesh::Partitioner::set_node_processor_ids(), libMesh::DofMap::set_nonlocal_dof_objects(), libMesh::Parallel::Sort< KeyType, IdxType >::sort(), libMesh::MeshRefinement::uniformly_coarsen(), libMesh::DistributedMesh::update_parallel_id_counts(), libMesh::GMVIO::write_binary(), libMesh::GMVIO::write_discontinuous_gmv(), libMesh::XdrIO::write_serialized_bcs_helper(), libMesh::XdrIO::write_serialized_connectivity(), libMesh::XdrIO::write_serialized_nodes(), and libMesh::XdrIO::write_serialized_nodesets().
   { return cast_int<processor_id_type>(_communicator.size()); }
template<typename T > PositionOfSpectrum libMesh::EigenSolver< T >::position_of_spectrum () const inline
Returns
The position of the spectrum to compute.
Definition at line 108 of file eigen_solver.h.
References libMesh::EigenSolver< T >::_position_of_spectrum.
   { return _position_of_spectrum;}
void libMesh::ReferenceCounter::print_info (std::ostream & out = libMesh::out) static inherited
Prints the reference information, by default to libMesh::out.
Definition at line 88 of file reference_counter.C.
References libMesh::ReferenceCounter::_enable_print_counter, and libMesh::ReferenceCounter::get_info().
Referenced by libMesh::LibMeshInit::LibMeshInit().
 {
   if (_enable_print_counter)
     out_stream << ReferenceCounter::get_info();
 }
processor_id_type libMesh::ParallelObject::processor_id () const inline inherited
Returns
The rank of this processor in the group.
Definition at line 99 of file parallel_object.h.
References libMesh::ParallelObject::_communicator, and libMesh::Parallel::Communicator::rank().
Referenced by libMesh::BoundaryInfo::_find_id_maps(), libMesh::EquationSystems::_read_impl(), libMesh::DistributedMesh::add_elem(), libMesh::BoundaryInfo::add_elements(), libMesh::DofMap::add_neighbors_to_send_list(), libMesh::DistributedMesh::add_node(), libMesh::MeshRefinement::add_node(), libMesh::MeshTools::Modification::all_tri(), libMesh::FEMSystem::assembly(), libMesh::ParmetisPartitioner::assign_partitioning(), libMesh::MeshCommunication::broadcast(), libMesh::EquationSystems::build_discontinuous_solution_vector(), libMesh::Nemesis_IO_Helper::build_element_and_node_maps(), libMesh::ParmetisPartitioner::build_graph(), libMesh::InfElemBuilder::build_inf_elem(), libMesh::BoundaryInfo::build_node_list_from_side_list(), libMesh::DofMap::build_sparsity(), libMesh::DistributedMesh::clear(), libMesh::ExodusII_IO_Helper::close(), libMesh::Nemesis_IO_Helper::compute_border_node_ids(), libMesh::Nemesis_IO_Helper::compute_communication_map_parameters(), libMesh::Nemesis_IO_Helper::compute_internal_and_border_elems_and_internal_nodes(), libMesh::Nemesis_IO_Helper::compute_node_communication_maps(), libMesh::Nemesis_IO_Helper::compute_num_global_elem_blocks(), libMesh::Nemesis_IO_Helper::compute_num_global_nodesets(), libMesh::Nemesis_IO_Helper::compute_num_global_sidesets(), libMesh::Nemesis_IO_Helper::construct_nemesis_filename(), libMesh::MeshTools::correct_node_proc_ids(), libMesh::ExodusII_IO_Helper::create(), libMesh::DistributedMesh::delete_elem(), libMesh::DistributedMesh::delete_node(), libMesh::MeshCommunication::delete_remote_elements(), libMesh::DofMap::distribute_dofs(), libMesh::DofMap::distribute_local_dofs_node_major(), libMesh::DofMap::distribute_local_dofs_var_major(), libMesh::DistributedMesh::DistributedMesh(), libMesh::EnsightIO::EnsightIO(), libMesh::MeshFunction::find_element(), libMesh::MeshFunction::find_elements(), libMesh::UnstructuredMesh::find_neighbors(), libMesh::MeshCommunication::gather(), libMesh::MeshCommunication::gather_neighboring_elements(), libMesh::Nemesis_IO_Helper::get_cmap_params(), libMesh::Nemesis_IO_Helper::get_eb_info_global(), libMesh::Nemesis_IO_Helper::get_elem_cmap(), libMesh::Nemesis_IO_Helper::get_elem_map(), libMesh::MeshBase::get_info(), libMesh::DofMap::get_info(), libMesh::Nemesis_IO_Helper::get_init_global(), libMesh::Nemesis_IO_Helper::get_init_info(), libMesh::Nemesis_IO_Helper::get_loadbal_param(), libMesh::Nemesis_IO_Helper::get_node_cmap(), libMesh::Nemesis_IO_Helper::get_node_map(), libMesh::Nemesis_IO_Helper::get_ns_param_global(), libMesh::EquationSystems::get_solution(), libMesh::Nemesis_IO_Helper::get_ss_param_global(), libMesh::SparsityPattern::Build::handle_vi_vj(), libMesh::DistributedVector< T >::init(), libMesh::SystemSubsetBySubdomain::init(), libMesh::ParmetisPartitioner::initialize(), libMesh::ExodusII_IO_Helper::initialize(), libMesh::ExodusII_IO_Helper::initialize_element_variables(), libMesh::ExodusII_IO_Helper::initialize_global_variables(), libMesh::ExodusII_IO_Helper::initialize_nodal_variables(), libMesh::DistributedMesh::insert_elem(), libMesh::DofMap::is_evaluable(), libMesh::SparsityPattern::Build::join(), libMesh::MeshTools::libmesh_assert_parallel_consistent_procids< Elem >(), libMesh::MeshTools::libmesh_assert_parallel_consistent_procids< Node >(), libMesh::MeshTools::libmesh_assert_valid_neighbors(), libMesh::DistributedMesh::libmesh_assert_valid_parallel_object_ids(), libMesh::DofMap::local_variable_indices(), libMesh::MeshRefinement::make_coarsening_compatible(), libMesh::MeshBase::n_active_local_elem(), libMesh::BoundaryInfo::n_boundary_conds(), libMesh::BoundaryInfo::n_edge_conds(), libMesh::System::n_local_dofs(), libMesh::MeshBase::n_local_elem(), libMesh::MeshBase::n_local_nodes(), libMesh::BoundaryInfo::n_nodeset_conds(), libMesh::BoundaryInfo::n_shellface_conds(), libMesh::WeightedPatchRecoveryErrorEstimator::EstimateError::operator()(), libMesh::SparsityPattern::Build::operator()(), libMesh::PatchRecoveryErrorEstimator::EstimateError::operator()(), libMesh::SparsityPattern::Build::parallel_sync(), libMesh::MetisPartitioner::partition_range(), libMesh::System::point_gradient(), libMesh::System::point_hessian(), libMesh::System::point_value(), libMesh::SparseMatrix< T >::print(), libMesh::NumericVector< T >::print_global(), libMesh::Nemesis_IO_Helper::put_cmap_params(), libMesh::Nemesis_IO_Helper::put_elem_cmap(), libMesh::Nemesis_IO_Helper::put_elem_map(), libMesh::Nemesis_IO_Helper::put_loadbal_param(), libMesh::Nemesis_IO_Helper::put_node_cmap(), libMesh::Nemesis_IO_Helper::put_node_map(), libMesh::NameBasedIO::read(), libMesh::Nemesis_IO::read(), libMesh::CheckpointIO::read(), libMesh::XdrIO::read(), libMesh::ExodusII_IO_Helper::read_elem_num_map(), libMesh::ExodusII_IO_Helper::read_node_num_map(), libMesh::XdrIO::read_serialized_bc_names(), libMesh::XdrIO::read_serialized_bcs_helper(), libMesh::XdrIO::read_serialized_connectivity(), libMesh::XdrIO::read_serialized_nodes(), libMesh::XdrIO::read_serialized_nodesets(), libMesh::XdrIO::read_serialized_subdomain_names(), libMesh::MeshCommunication::redistribute(), libMesh::DistributedMesh::renumber_dof_objects(), libMesh::MeshCommunication::send_coarse_ghosts(), libMesh::Partitioner::set_node_processor_ids(), libMesh::DofMap::set_nonlocal_dof_objects(), libMesh::LaplaceMeshSmoother::smooth(), libMesh::MeshTools::total_weight(), libMesh::MeshRefinement::uniformly_coarsen(), libMesh::Parallel::Packing< Node * >::unpack(), libMesh::Parallel::Packing< Elem * >::unpack(), libMesh::DistributedMesh::update_parallel_id_counts(), libMesh::MeshTools::weight(), libMesh::NameBasedIO::write(), libMesh::CheckpointIO::write(), libMesh::XdrIO::write(), libMesh::EquationSystems::write(), libMesh::GMVIO::write_discontinuous_gmv(), libMesh::ExodusII_IO::write_element_data(), libMesh::ExodusII_IO_Helper::write_element_values(), libMesh::ExodusII_IO_Helper::write_elements(), libMesh::ExodusII_IO::write_global_data(), libMesh::ExodusII_IO_Helper::write_global_values(), libMesh::ExodusII_IO::write_information_records(), libMesh::ExodusII_IO_Helper::write_information_records(), libMesh::ExodusII_IO_Helper::write_nodal_coordinates(), libMesh::UCDIO::write_nodal_data(), libMesh::ExodusII_IO::write_nodal_data(), libMesh::ExodusII_IO::write_nodal_data_discontinuous(), libMesh::ExodusII_IO_Helper::write_nodal_values(), libMesh::Nemesis_IO_Helper::write_nodesets(), libMesh::ExodusII_IO_Helper::write_nodesets(), libMesh::XdrIO::write_serialized_bc_names(), libMesh::XdrIO::write_serialized_bcs_helper(), libMesh::XdrIO::write_serialized_connectivity(), libMesh::XdrIO::write_serialized_nodes(), libMesh::XdrIO::write_serialized_nodesets(), libMesh::XdrIO::write_serialized_subdomain_names(), libMesh::Nemesis_IO_Helper::write_sidesets(), libMesh::ExodusII_IO_Helper::write_sidesets(), libMesh::ExodusII_IO::write_timestep(), and libMesh::ExodusII_IO_Helper::write_timestep().
   { return cast_int<processor_id_type>(_communicator.rank()); }
template<typename T > void libMesh::EigenSolver< T >::set_eigenproblem_type (EigenProblemType ept) inline
Sets the type of the eigenproblem.
Definition at line 120 of file eigen_solver.h.
References libMesh::EigenSolver< T >::_eigen_problem_type.
   {_eigen_problem_type = ept;}
template<typename T > void libMesh::EigenSolver< T >::set_eigensolver_type (const EigenSolverType est) inline
Sets the type of eigensolver to use.
Definition at line 114 of file eigen_solver.h.
References libMesh::EigenSolver< T >::_eigen_solver_type.
   { _eigen_solver_type = est; }
template<typename T > virtual void libMesh::EigenSolver< T >::set_initial_space (NumericVector< T > & initial_space_in) pure virtual
Provide one basis vector for the initial guess
Implemented in libMesh::SlepcEigenSolver< T >.
Referenced by libMesh::EigenSolver< T >::set_position_of_spectrum().
template<typename T > void libMesh::EigenSolver< T >::set_position_of_spectrum (PositionOfSpectrum pos) inline
Sets the position of the spectrum.
Definition at line 126 of file eigen_solver.h.
References libMesh::EigenSolver< T >::_position_of_spectrum, libMesh::EigenSolver< T >::attach_deflation_space(), libMesh::EigenSolver< T >::get_eigenpair(), libMesh::EigenSolver< T >::get_eigenvalue(), libMesh::Real, libMesh::EigenSolver< T >::set_initial_space(), libMesh::EigenSolver< T >::set_solver_configuration(), libMesh::EigenSolver< T >::solve_generalized(), and libMesh::EigenSolver< T >::solve_standard().
   {_position_of_spectrum= pos;}
template<typename T > void libMesh::EigenSolver< T >::set_position_of_spectrum (Real pos)
Definition at line 64 of file eigen_solver.C.
References libMesh::TARGET_MAGNITUDE, and libMesh::TARGET_REAL.
 {
   if (pos >= 0)
     _position_of_spectrum = TARGET_MAGNITUDE;
   else
     _position_of_spectrum = TARGET_REAL;
   _target_val = pos;
 }
template<typename T > void libMesh::EigenSolver< T >::set_position_of_spectrum (Real pos, PositionOfSpectrum target)
Definition at line 75 of file eigen_solver.C.
 {
   _position_of_spectrum = target;
   _target_val = pos;
 }
template<typename T > void libMesh::EigenSolver< T >::set_solver_configuration (SolverConfiguration & solver_configuration)
Set the solver configuration object.
Definition at line 58 of file eigen_solver.C.
Referenced by libMesh::EigenSolver< T >::set_position_of_spectrum().
 {
   _solver_configuration = &solver_configuration;
 }
template<typename T > virtual std::pair<unsigned int, unsigned int> libMesh::EigenSolver< T >::solve_generalized (SparseMatrix< T > & matrix_A, SparseMatrix< T > & matrix_B, int nev, int ncv, const double tol, const unsigned int m_its) pure virtual
Solves the generalized eigenproblem involving SparseMatrices matrix_A and matrix_B.
Returns
The number of converged eigenpairs and the number of iterations.
Implemented in libMesh::SlepcEigenSolver< T >.
Referenced by libMesh::EigenSolver< T >::set_position_of_spectrum().
template<typename T > virtual std::pair<unsigned int, unsigned int> libMesh::EigenSolver< T >::solve_generalized (ShellMatrix< T > & matrix_A, SparseMatrix< T > & matrix_B, int nev, int ncv, const double tol, const unsigned int m_its) pure virtual
Solves the generalized eigenproblem with ShellMatrix matrix_A and SparseMatrix matrix_B.
Returns
The number of converged eigenpairs and the number of iterations.
Implemented in libMesh::SlepcEigenSolver< T >.
template<typename T > virtual std::pair<unsigned int, unsigned int> libMesh::EigenSolver< T >::solve_generalized (SparseMatrix< T > & matrix_A, ShellMatrix< T > & matrix_B, int nev, int ncv, const double tol, const unsigned int m_its) pure virtual
Solves the generalized eigenproblem with SparseMatrix matrix_A and ShellMatrix matrix_B.
Returns
The number of converged eigenpairs and the number of iterations.
Implemented in libMesh::SlepcEigenSolver< T >.
template<typename T > virtual std::pair<unsigned int, unsigned int> libMesh::EigenSolver< T >::solve_generalized (ShellMatrix< T > & matrix_A, ShellMatrix< T > & matrix_B, int nev, int ncv, const double tol, const unsigned int m_its) pure virtual
Solves the generalized eigenproblem involving ShellMatrices matrix_A and matrix_B.
Returns
The number of converged eigenpairs and the number of iterations.
Implemented in libMesh::SlepcEigenSolver< T >.
template<typename T > virtual std::pair<unsigned int, unsigned int> libMesh::EigenSolver< T >::solve_standard (SparseMatrix< T > & matrix_A, int nev, int ncv, const double tol, const unsigned int m_its) pure virtual
Solves the standard eigenproblem involving the SparseMatrix matrix_A.
Returns
The number of converged eigenpairs and the number of iterations.
Implemented in libMesh::SlepcEigenSolver< T >.
Referenced by libMesh::EigenSolver< T >::set_position_of_spectrum().
template<typename T > virtual std::pair<unsigned int, unsigned int> libMesh::EigenSolver< T >::solve_standard (ShellMatrix< T > & matrix_A, int nev, int ncv, const double tol, const unsigned int m_its) pure virtual
Solves the standard eigenproblem involving the ShellMatrix matrix_A.
Returns
The number of converged eigenpairs and the number of iterations.
Implemented in libMesh::SlepcEigenSolver< T >.
Member Data Documentation
const Parallel::Communicator& libMesh::ParallelObject::_communicator protected inherited
Definition at line 105 of file parallel_object.h.
Referenced by libMesh::EquationSystems::build_parallel_solution_vector(), libMesh::ParallelObject::comm(), libMesh::EquationSystems::get_solution(), libMesh::ParallelObject::n_processors(), libMesh::ParallelObject::operator=(), and libMesh::ParallelObject::processor_id().
ReferenceCounter::Counts libMesh::ReferenceCounter::_counts static protected inherited
Actually holds the data.
Definition at line 124 of file reference_counter.h.
Referenced by libMesh::ReferenceCounter::get_info(), libMesh::ReferenceCounter::increment_constructor_count(), and libMesh::ReferenceCounter::increment_destructor_count().
template<typename T > EigenProblemType libMesh::EigenSolver< T >::_eigen_problem_type protected
Enum stating which type of eigen problem we deal with.
Definition at line 253 of file eigen_solver.h.
Referenced by libMesh::EigenSolver< T >::eigen_problem_type(), libMesh::EigenSolver< T >::set_eigenproblem_type(), and libMesh::SlepcEigenSolver< T >::SlepcEigenSolver().
template<typename T > EigenSolverType libMesh::EigenSolver< T >::_eigen_solver_type protected
Enum stating which type of eigensolver to use.
Definition at line 248 of file eigen_solver.h.
Referenced by libMesh::EigenSolver< T >::eigen_solver_type(), libMesh::EigenSolver< T >::set_eigensolver_type(), and libMesh::SlepcEigenSolver< T >::SlepcEigenSolver().
bool libMesh::ReferenceCounter::_enable_print_counter = true static protected inherited
Flag to control whether reference count information is printed when print_info is called.
Definition at line 143 of file reference_counter.h.
Referenced by libMesh::ReferenceCounter::disable_print_counter_info(), libMesh::ReferenceCounter::enable_print_counter_info(), and libMesh::ReferenceCounter::print_info().
template<typename T > bool libMesh::EigenSolver< T >::_is_initialized protected
Flag indicating if the data structures have been initialized.
Definition at line 263 of file eigen_solver.h.
Referenced by libMesh::EigenSolver< T >::initialized().
Threads::spin_mutex libMesh::ReferenceCounter::_mutex static protected inherited
Mutual exclusion object to enable thread-safe reference counting.
Definition at line 137 of file reference_counter.h.
Threads::atomic< unsigned int > libMesh::ReferenceCounter::_n_objects static protected inherited
The number of objects. Print the reference count information when the number returns to 0.
Definition at line 132 of file reference_counter.h.
Referenced by libMesh::ReferenceCounter::n_objects(), libMesh::ReferenceCounter::ReferenceCounter(), and libMesh::ReferenceCounter::~ReferenceCounter().
template<typename T > PositionOfSpectrum libMesh::EigenSolver< T >::_position_of_spectrum protected
Enum stating where to evaluate the spectrum.
Definition at line 258 of file eigen_solver.h.
Referenced by libMesh::EigenSolver< T >::position_of_spectrum(), and libMesh::EigenSolver< T >::set_position_of_spectrum().
template<typename T > SolverConfiguration* libMesh::EigenSolver< T >::_solver_configuration protected
Optionally store a SolverOptions object that can be used to set parameters like solver type, tolerances and iteration limits.
Definition at line 269 of file eigen_solver.h.
template<typename T > Real libMesh::EigenSolver< T >::_target_val protected
Definition at line 271 of file eigen_solver.h.
The documentation for this class was generated from the following files:
eigen_solver.h
eigen_solver.C