libMesh: libMesh::Parallel::Sort< KeyType, IdxType > Class Template Reference
SomeWebsiteLogo
libMesh::Parallel::Sort< KeyType, IdxType > Class Template Reference
Object for performing parallel sorts using MPI.
#include <parallel_sort.h>
Public Member Functions
Sort (const Parallel::Communicator &comm, std::vector< KeyType > &d)
void sort ()
const std::vector< KeyType > & bin ()
const Parallel::Communicator & comm () const
processor_id_type n_processors () const
processor_id_type processor_id () const
Protected Attributes
const Parallel::Communicator & _communicator
Private Member Functions
void binsort ()
void communicate_bins ()
void sort_local_bin ()
template<>
void binsort ()
template<>
void communicate_bins ()
Private Attributes
const processor_id_type _n_procs
const processor_id_type _proc_id
bool _bin_is_sorted
std::vector< KeyType > & _data
std::vector< IdxType > _local_bin_sizes
std::vector< KeyType > _my_bin
Detailed Description
template<typename KeyType, typename IdxType = unsigned int>
class libMesh::Parallel::Sort< KeyType, IdxType >
Object for performing parallel sorts using MPI.
The parallel sorting method is templated on the type of data which is to be sorted. It may later be templated on other things if we are ambitious. This class knows about MPI, and knows how many processors there are. It is responsible for transmitting data between the processors and ensuring that the data is properly sorted between all the processors. We assume that a Sort is instantiated on all processors.
Author
Benjamin S. Kirk
John W. Peterson
Date
2007
Definition at line 53 of file parallel_sort.h.
Constructor & Destructor Documentation
template<typename KeyType , typename IdxType > libMesh::Parallel::Sort< KeyType, IdxType >::Sort (const Parallel::Communicator & comm, std::vector< KeyType > & d)
Constructor takes the number of processors, the processor id, and a reference to a vector of data to be sorted. This vector is sorted by the constructor, therefore, construction of a Sort object takes O(n log n) time, where n is the length of the vector.
Definition at line 41 of file parallel_sort.C.
References libMesh::Parallel::Sort< KeyType, IdxType >::_data, libMesh::Parallel::Sort< KeyType, IdxType >::_local_bin_sizes, and libMesh::Parallel::Sort< KeyType, IdxType >::_n_procs.
                                                     :
   ParallelObject(comm_in),
   _n_procs(cast_int<processor_id_type>(comm_in.size())),
   _proc_id(cast_int<processor_id_type>(comm_in.rank())),
   _bin_is_sorted(false),
   _data(d)
 {
   std::sort(_data.begin(), _data.end());
   // Allocate storage
   _local_bin_sizes.resize(_n_procs);
 }
Member Function Documentation
template<typename KeyType , typename IdxType > const std::vector< KeyType > & libMesh::Parallel::Sort< KeyType, IdxType >::bin ()
Return a constant reference to _my_bin. This allows us to do things like check if sorting was successful by printing _my_bin.
Definition at line 376 of file parallel_sort.C.
References libMesh::Parallel::Sort< KeyType, IdxType >::_bin_is_sorted, libMesh::Parallel::Sort< KeyType, IdxType >::_my_bin, and libMesh::out.
Referenced by libMesh::MeshCommunication::assign_global_indices(), and libMesh::MeshCommunication::find_global_indices().
 {
   if (!_bin_is_sorted)
     {
       libMesh::out << "Warning! Bin is not yet sorted!" << std::endl;
     }
   return _my_bin;
 }
template<typename KeyType , typename IdxType > void libMesh::Parallel::Sort< KeyType, IdxType >::binsort () private
Sorts the local data into bins across all processors. Right now it constructs a BenSorter<KeyType> object. In the future this could be a template parameter.
Definition at line 96 of file parallel_sort.C.
References libMesh::Parallel::Sort< KeyType, IdxType >::_data, libMesh::Parallel::Sort< KeyType, IdxType >::_local_bin_sizes, libMesh::Parallel::Sort< KeyType, IdxType >::_n_procs, libMesh::Parallel::BinSorter< KeyType, IdxType >::binsort(), libMesh::ParallelObject::comm(), libMesh::Parallel::Communicator::max(), and libMesh::Parallel::BinSorter< KeyType, IdxType >::sizeof_bin().
Referenced by libMesh::Parallel::Sort< KeyType, IdxType >::sort().
 {
   // Find the global min and max from all the
   // processors.
   std::vector<KeyType> global_min_max(2);
   // Insert the local min and max for this processor
   global_min_max[0] = -_data.front();
   global_min_max[1] =  _data.back();
   // Communicate to determine the global
   // min and max for all processors.
   this->comm().max(global_min_max);
   // Multiply the min by -1 to obtain the true min
   global_min_max[0] *= -1;
   // Bin-Sort based on the global min and max
   Parallel::BinSorter<KeyType> bs(this->comm(), _data);
   bs.binsort(_n_procs, global_min_max[1], global_min_max[0]);
   // Now save the local bin sizes in a vector so
   // we don't have to keep around the BinSorter.
   for (processor_id_type i=0; i<_n_procs; ++i)
     _local_bin_sizes[i] = bs.sizeof_bin(i);
 }
template<> void libMesh::Parallel::Sort< Parallel::DofObjectKey, unsigned int >::binsort () private
Definition at line 130 of file parallel_sort.C.
References libMesh::Parallel::Sort< KeyType, IdxType >::_data, libMesh::Parallel::Sort< KeyType, IdxType >::_local_bin_sizes, libMesh::Parallel::Sort< KeyType, IdxType >::_n_procs, libMesh::Parallel::BinSorter< KeyType, IdxType >::binsort(), libMesh::ParallelObject::comm(), dofobjectkey_max_op(), dofobjectkey_min_op(), std::max(), and libMesh::Parallel::BinSorter< KeyType, IdxType >::sizeof_bin().
 {
   // Find the global min and max from all the
   // processors.  Do this using MPI_Allreduce.
   Parallel::DofObjectKey
     local_min,  local_max,
     global_min, global_max;
   if (_data.empty())
     {
 #ifdef LIBMESH_ENABLE_UNIQUE_ID
       local_min.first.rack0 = local_min.first.rack1 = local_min.first.rack2 = static_cast<Hilbert::inttype>(-1);
       local_min.second = std::numeric_limits<unique_id_type>::max();
       local_max.first.rack0 = local_max.first.rack1 = local_max.first.rack2 = 0;
       local_max.second = 0;
 #else
       local_min.rack0 = local_min.rack1 = local_min.rack2 = static_cast<Hilbert::inttype>(-1);
       local_max.rack0 = local_max.rack1 = local_max.rack2 = 0;
 #endif
     }
   else
     {
       local_min = _data.front();
       local_max = _data.back();
     }
   MPI_Op hilbert_max, hilbert_min;
   MPI_Op_create       ((MPI_User_function*)dofobjectkey_max_op, true, &hilbert_max);
   MPI_Op_create       ((MPI_User_function*)dofobjectkey_min_op, true, &hilbert_min);
   // Communicate to determine the global
   // min and max for all processors.
   MPI_Allreduce(&local_min,
                 &global_min,
                 1,
                 Parallel::StandardType<Parallel::DofObjectKey>(&local_min),
                 hilbert_min,
                 this->comm().get());
   MPI_Allreduce(&local_max,
                 &global_max,
                 1,
                 Parallel::StandardType<Parallel::DofObjectKey>(&local_max),
                 hilbert_max,
                 this->comm().get());
   MPI_Op_free   (&hilbert_max);
   MPI_Op_free   (&hilbert_min);
   // Bin-Sort based on the global min and max
   Parallel::BinSorter<Parallel::DofObjectKey> bs(this->comm(),_data);
   bs.binsort(_n_procs, global_max, global_min);
   // Now save the local bin sizes in a vector so
   // we don't have to keep around the BinSorter.
   for (processor_id_type i=0; i<_n_procs; ++i)
     _local_bin_sizes[i] = bs.sizeof_bin(i);
 }
const Parallel::Communicator& libMesh::ParallelObject::comm () const inline inherited
Returns
A reference to the Parallel::Communicator object used by this mesh.
Definition at line 87 of file parallel_object.h.
References libMesh::ParallelObject::_communicator.
Referenced by libMesh::__libmesh_petsc_diff_solver_monitor(), libMesh::__libmesh_petsc_diff_solver_residual(), libMesh::__libmesh_petsc_snes_jacobian(), libMesh::__libmesh_petsc_snes_postcheck(), libMesh::__libmesh_petsc_snes_residual(), libMesh::__libmesh_tao_equality_constraints(), libMesh::__libmesh_tao_equality_constraints_jacobian(), libMesh::__libmesh_tao_gradient(), libMesh::__libmesh_tao_hessian(), libMesh::__libmesh_tao_inequality_constraints(), libMesh::__libmesh_tao_inequality_constraints_jacobian(), libMesh::__libmesh_tao_objective(), libMesh::MeshRefinement::_coarsen_elements(), libMesh::ExactSolution::_compute_error(), libMesh::ParmetisPartitioner::_do_repartition(), libMesh::UniformRefinementEstimator::_estimate_error(), libMesh::BoundaryInfo::_find_id_maps(), libMesh::PetscLinearSolver< T >::_petsc_shell_matrix_get_diagonal(), libMesh::SlepcEigenSolver< T >::_petsc_shell_matrix_get_diagonal(), libMesh::PetscLinearSolver< T >::_petsc_shell_matrix_mult(), libMesh::SlepcEigenSolver< T >::_petsc_shell_matrix_mult(), libMesh::PetscLinearSolver< T >::_petsc_shell_matrix_mult_add(), libMesh::EquationSystems::_read_impl(), libMesh::MeshRefinement::_refine_elements(), libMesh::MeshRefinement::_smooth_flags(), libMesh::ImplicitSystem::add_matrix(), libMesh::System::add_vector(), libMesh::EigenSparseLinearSolver< T >::adjoint_solve(), libMesh::UnstructuredMesh::all_second_order(), libMesh::MeshTools::Modification::all_tri(), libMesh::LaplaceMeshSmoother::allgather_graph(), libMesh::FEMSystem::assemble_qoi(), libMesh::MeshCommunication::assign_global_indices(), libMesh::ParmetisPartitioner::assign_partitioning(), libMesh::DofMap::attach_matrix(), libMesh::Parallel::BinSorter< KeyType, IdxType >::binsort(), libMesh::Parallel::Sort< KeyType, IdxType >::binsort(), libMesh::MeshCommunication::broadcast(), libMesh::SparseMatrix< T >::build(), libMesh::MeshTools::Generation::build_extrusion(), libMesh::Parallel::Histogram< KeyType, IdxType >::build_histogram(), libMesh::PetscNonlinearSolver< T >::build_mat_null_space(), libMesh::BoundaryInfo::build_node_list_from_side_list(), libMesh::EquationSystems::build_parallel_solution_vector(), libMesh::MeshBase::cache_elem_dims(), libMesh::System::calculate_norm(), libMesh::DofMap::check_dirichlet_bcid_consistency(), libMesh::DistributedVector< T >::clone(), libMesh::EigenSparseVector< T >::clone(), libMesh::LaspackVector< T >::clone(), libMesh::EpetraVector< T >::clone(), libMesh::PetscVector< T >::clone(), libMesh::EpetraVector< T >::close(), libMesh::Parallel::Sort< KeyType, IdxType >::communicate_bins(), libMesh::Nemesis_IO_Helper::compute_num_global_elem_blocks(), libMesh::Nemesis_IO_Helper::compute_num_global_nodesets(), libMesh::Nemesis_IO_Helper::compute_num_global_sidesets(), libMesh::Problem_Interface::computeF(), libMesh::Problem_Interface::computeJacobian(), libMesh::Problem_Interface::computePreconditioner(), libMesh::MeshTools::correct_node_proc_ids(), libMesh::MeshTools::create_bounding_box(), libMesh::MeshTools::create_nodal_bounding_box(), libMesh::MeshRefinement::create_parent_error_vector(), libMesh::MeshTools::create_processor_bounding_box(), libMesh::MeshTools::create_subdomain_bounding_box(), libMesh::MeshCommunication::delete_remote_elements(), libMesh::DofMap::distribute_dofs(), DMlibMeshFunction(), DMlibMeshJacobian(), DMlibMeshSetSystem_libMesh(), DMVariableBounds_libMesh(), libMesh::MeshRefinement::eliminate_unrefined_patches(), libMesh::EpetraVector< T >::EpetraVector(), libMesh::WeightedPatchRecoveryErrorEstimator::estimate_error(), libMesh::PatchRecoveryErrorEstimator::estimate_error(), libMesh::JumpErrorEstimator::estimate_error(), libMesh::AdjointRefinementEstimator::estimate_error(), libMesh::ExactErrorEstimator::estimate_error(), libMesh::MeshRefinement::flag_elements_by_elem_fraction(), libMesh::MeshRefinement::flag_elements_by_error_fraction(), libMesh::MeshRefinement::flag_elements_by_nelem_target(), libMesh::MeshCommunication::gather(), libMesh::MeshCommunication::gather_neighboring_elements(), libMesh::CondensedEigenSystem::get_eigenpair(), libMesh::DofMap::get_info(), libMesh::ImplicitSystem::get_linear_solver(), libMesh::EquationSystems::get_solution(), libMesh::LocationMap< T >::init(), libMesh::PetscDiffSolver::init(), libMesh::TimeSolver::init(), libMesh::TopologyMap::init(), libMesh::TaoOptimizationSolver< T >::init(), libMesh::PetscNonlinearSolver< T >::init(), libMesh::DistributedVector< T >::init(), libMesh::EpetraVector< T >::init(), libMesh::PetscVector< T >::init(), libMesh::SystemSubsetBySubdomain::init(), libMesh::EigenSystem::init_data(), libMesh::EigenSystem::init_matrices(), libMesh::ParmetisPartitioner::initialize(), libMesh::OptimizationSystem::initialize_equality_constraints_storage(), libMesh::OptimizationSystem::initialize_inequality_constraints_storage(), libMesh::MeshTools::libmesh_assert_parallel_consistent_procids< Elem >(), libMesh::MeshTools::libmesh_assert_parallel_consistent_procids< Node >(), libMesh::MeshTools::libmesh_assert_topology_consistent_procids< Node >(), libMesh::MeshTools::libmesh_assert_valid_boundary_ids(), libMesh::MeshTools::libmesh_assert_valid_dof_ids(), libMesh::MeshTools::libmesh_assert_valid_neighbors(), libMesh::DistributedMesh::libmesh_assert_valid_parallel_flags(), libMesh::DistributedMesh::libmesh_assert_valid_parallel_object_ids(), libMesh::DistributedMesh::libmesh_assert_valid_parallel_p_levels(), libMesh::MeshTools::libmesh_assert_valid_refinement_flags(), libMesh::MeshTools::libmesh_assert_valid_unique_ids(), libMesh::MeshRefinement::limit_level_mismatch_at_edge(), libMesh::MeshRefinement::limit_level_mismatch_at_node(), libMesh::MeshRefinement::limit_overrefined_boundary(), libMesh::MeshRefinement::limit_underrefined_boundary(), libMesh::MeshRefinement::make_coarsening_compatible(), libMesh::MeshCommunication::make_elems_parallel_consistent(), libMesh::MeshRefinement::make_flags_parallel_consistent(), libMesh::MeshCommunication::make_new_node_proc_ids_parallel_consistent(), libMesh::MeshCommunication::make_new_nodes_parallel_consistent(), libMesh::MeshCommunication::make_node_ids_parallel_consistent(), libMesh::MeshCommunication::make_node_proc_ids_parallel_consistent(), libMesh::MeshCommunication::make_node_unique_ids_parallel_consistent(), libMesh::MeshCommunication::make_nodes_parallel_consistent(), libMesh::MeshCommunication::make_p_levels_parallel_consistent(), libMesh::MeshRefinement::make_refinement_compatible(), libMesh::DistributedVector< T >::max(), libMesh::FEMSystem::mesh_position_set(), libMesh::MeshSerializer::MeshSerializer(), libMesh::DistributedVector< T >::min(), libMesh::DistributedMesh::n_active_elem(), libMesh::MeshTools::n_active_levels(), libMesh::BoundaryInfo::n_boundary_conds(), libMesh::BoundaryInfo::n_edge_conds(), libMesh::CondensedEigenSystem::n_global_non_condensed_dofs(), libMesh::MeshTools::n_levels(), libMesh::BoundaryInfo::n_nodeset_conds(), libMesh::MeshTools::n_p_levels(), libMesh::BoundaryInfo::n_shellface_conds(), libMesh::DistributedMesh::parallel_max_elem_id(), libMesh::DistributedMesh::parallel_max_node_id(), libMesh::ReplicatedMesh::parallel_max_unique_id(), libMesh::DistributedMesh::parallel_max_unique_id(), libMesh::DistributedMesh::parallel_n_elem(), libMesh::DistributedMesh::parallel_n_nodes(), libMesh::SparsityPattern::Build::parallel_sync(), libMesh::MeshTools::paranoid_n_levels(), libMesh::Partitioner::partition(), libMesh::MetisPartitioner::partition_range(), libMesh::Partitioner::partition_unpartitioned_elements(), libMesh::petsc_auto_fieldsplit(), libMesh::System::point_gradient(), libMesh::System::point_hessian(), libMesh::System::point_value(), libMesh::MeshBase::prepare_for_use(), libMesh::SparseMatrix< T >::print(), libMesh::Nemesis_IO::read(), libMesh::CheckpointIO::read(), libMesh::XdrIO::read(), libMesh::CheckpointIO::read_header(), libMesh::XdrIO::read_serialized_bc_names(), libMesh::XdrIO::read_serialized_bcs_helper(), libMesh::XdrIO::read_serialized_connectivity(), libMesh::XdrIO::read_serialized_nodes(), libMesh::XdrIO::read_serialized_nodesets(), libMesh::XdrIO::read_serialized_subdomain_names(), libMesh::MeshBase::recalculate_n_partitions(), libMesh::MeshCommunication::redistribute(), libMesh::DistributedMesh::renumber_dof_objects(), libMesh::MeshCommunication::send_coarse_ghosts(), libMesh::Partitioner::set_node_processor_ids(), libMesh::DofMap::set_nonlocal_dof_objects(), libMesh::Partitioner::set_parent_processor_ids(), libMesh::LaplaceMeshSmoother::smooth(), libMesh::Parallel::Sort< KeyType, IdxType >::sort(), libMesh::MeshBase::subdomain_ids(), libMesh::BoundaryInfo::sync(), libMesh::Parallel::sync_element_data_by_parent_id(), libMesh::Parallel::sync_node_data_by_element_id(), libMesh::MeshRefinement::test_level_one(), libMesh::MeshRefinement::test_unflagged(), libMesh::MeshTools::total_weight(), libMesh::MeshRefinement::uniformly_coarsen(), libMesh::NameBasedIO::write(), libMesh::XdrIO::write(), libMesh::XdrIO::write_serialized_bcs_helper(), libMesh::XdrIO::write_serialized_connectivity(), libMesh::XdrIO::write_serialized_nodes(), libMesh::XdrIO::write_serialized_nodesets(), libMesh::DistributedVector< T >::zero_clone(), libMesh::LaspackVector< T >::zero_clone(), libMesh::EigenSparseVector< T >::zero_clone(), libMesh::EpetraVector< T >::zero_clone(), and libMesh::PetscVector< T >::zero_clone().
   { return _communicator; }
template<typename KeyType , typename IdxType > void libMesh::Parallel::Sort< KeyType, IdxType >::communicate_bins () private
Communicates the bins from each processor to the appropriate processor. By the time this function is finished, each processor will hold only its own bin(s).
Definition at line 194 of file parallel_sort.C.
References libMesh::Parallel::Sort< KeyType, IdxType >::_data, libMesh::Parallel::Sort< KeyType, IdxType >::_local_bin_sizes, libMesh::Parallel::Sort< KeyType, IdxType >::_my_bin, libMesh::Parallel::Sort< KeyType, IdxType >::_n_procs, libMesh::Parallel::Sort< KeyType, IdxType >::_proc_id, libMesh::Parallel::Communicator::allgather(), libMesh::ParallelObject::comm(), libmesh_nullptr, and libMesh::Parallel::Communicator::sum().
Referenced by libMesh::Parallel::Sort< KeyType, IdxType >::sort().
 {
 #ifdef LIBMESH_HAVE_MPI
   // Create storage for the global bin sizes.  This
   // is the number of keys which will be held in
   // each bin over all processors.
   std::vector<IdxType> global_bin_sizes = _local_bin_sizes;
   // Sum to find the total number of entries in each bin.
   this->comm().sum(global_bin_sizes);
   // Create a vector to temporarily hold the results of MPI_Gatherv
   // calls.  The vector dest  may be saved away to _my_bin depending on which
   // processor is being MPI_Gatherv'd.
   std::vector<KeyType> dest;
   IdxType local_offset = 0;
   for (processor_id_type i=0; i<_n_procs; ++i)
     {
       // Vector to receive the total bin size for each
       // processor.  Processor i's bin size will be
       // held in proc_bin_size[i]
       std::vector<int> proc_bin_size;
       // Find the number of contributions coming from each
       // processor for this bin.  Note: allgather combines
       // the MPI_Gather and MPI_Bcast operations into one.
       this->comm().allgather(static_cast<int>(_local_bin_sizes[i]),
                              proc_bin_size);
       // Compute the offsets into my_bin for each processor's
       // portion of the bin.  These are basically partial sums
       // of the proc_bin_size vector.
       std::vector<int> displacements(_n_procs);
       for (processor_id_type j=1; j<_n_procs; ++j)
         displacements[j] = proc_bin_size[j-1] + displacements[j-1];
       // Resize the destination buffer
       dest.resize (global_bin_sizes[i]);
       // Points to the beginning of the bin to be sent
       void * sendbuf = (_data.size() > local_offset) ? &_data[local_offset] : libmesh_nullptr;
       // Enough storage to hold all bin contributions
       void * recvbuf = (dest.empty()) ? libmesh_nullptr : &dest[0];
       // If the sendbuf is NULL, make sure we aren't claiming to send something.
       if (sendbuf == libmesh_nullptr && _local_bin_sizes[i] != 0)
         libmesh_error_msg("Error: invalid MPI_Gatherv call constructed!");
       KeyType example;
       MPI_Gatherv(sendbuf,
                   _local_bin_sizes[i],                       // How much data is in the bin being sent.
                   Parallel::StandardType<KeyType>(&example), // The data type we are sorting
                   recvbuf,
                   &proc_bin_size[0],          // How much is to be received from each processor
                   &displacements[0],          // Offsets into the receive buffer
                   Parallel::StandardType<KeyType>(&example), // The data type we are sorting
                   i,                                         // The root process (we do this once for each proc)
                   this->comm().get());
       // Copy the destination buffer if it
       // corresponds to the bin for this processor
       if (i == _proc_id)
         _my_bin = dest;
       // Increment the local offset counter
       local_offset += _local_bin_sizes[i];
     }
 #endif // LIBMESH_HAVE_MPI
 }
template<> void libMesh::Parallel::Sort< Parallel::DofObjectKey, unsigned int >::communicate_bins () private
Definition at line 275 of file parallel_sort.C.
References libMesh::Parallel::Sort< KeyType, IdxType >::_data, libMesh::Parallel::Sort< KeyType, IdxType >::_local_bin_sizes, libMesh::Parallel::Sort< KeyType, IdxType >::_my_bin, libMesh::Parallel::Sort< KeyType, IdxType >::_n_procs, libMesh::Parallel::Sort< KeyType, IdxType >::_proc_id, libMesh::ParallelObject::comm(), and libmesh_nullptr.
 {
   // Create storage for the global bin sizes.  This
   // is the number of keys which will be held in
   // each bin over all processors.
   std::vector<unsigned int> global_bin_sizes(_n_procs);
   libmesh_assert_equal_to (_local_bin_sizes.size(), global_bin_sizes.size());
   // Sum to find the total number of entries in each bin.
   // This is stored in global_bin_sizes.  Note, we
   // explicitly know that we are communicating MPI_UNSIGNED's here.
   MPI_Allreduce(&_local_bin_sizes[0],
                 &global_bin_sizes[0],
                 _n_procs,
                 MPI_UNSIGNED,
                 MPI_SUM,
                 this->comm().get());
   // Create a vector to temporarily hold the results of MPI_Gatherv
   // calls.  The vector dest  may be saved away to _my_bin depending on which
   // processor is being MPI_Gatherv'd.
   std::vector<Parallel::DofObjectKey> dest;
   unsigned int local_offset = 0;
   for (unsigned int i=0; i<_n_procs; ++i)
     {
       // Vector to receive the total bin size for each
       // processor.  Processor i's bin size will be
       // held in proc_bin_size[i]
       std::vector<int> proc_bin_size(_n_procs);
       // Find the number of contributions coming from each
       // processor for this bin.  Note: Allgather combines
       // the MPI_Gather and MPI_Bcast operations into one.
       // Note: Here again we know that we are communicating
       // MPI_UNSIGNED's so there is no need to check the MPI_traits.
       MPI_Allgather(&_local_bin_sizes[i], // Source: # of entries on this proc in bin i
                     1,                    // Number of items to gather
                     MPI_UNSIGNED,
                     &proc_bin_size[0],    // Destination: Total # of entries in bin i
                     1,
                     MPI_INT,
                     this->comm().get());
       // Compute the offsets into my_bin for each processor's
       // portion of the bin.  These are basically partial sums
       // of the proc_bin_size vector.
       std::vector<int> displacements(_n_procs);
       for (unsigned int j=1; j<_n_procs; ++j)
         displacements[j] = proc_bin_size[j-1] + displacements[j-1];
       // Resize the destination buffer
       dest.resize (global_bin_sizes[i]);
       // Points to the beginning of the bin to be sent
       void * sendbuf = (_data.size() > local_offset) ? &_data[local_offset] : libmesh_nullptr;
       // Enough storage to hold all bin contributions
       void * recvbuf = (dest.empty()) ? libmesh_nullptr : &dest[0];
       // If the sendbuf is NULL, make sure we aren't claiming to send something.
       if (sendbuf == libmesh_nullptr && _local_bin_sizes[i] != 0)
         libmesh_error_msg("Error: invalid MPI_Gatherv call constructed!");
       Parallel::DofObjectKey example;
       MPI_Gatherv(sendbuf,
                   _local_bin_sizes[i],      // How much data is in the bin being sent.
                   Parallel::StandardType<Parallel::DofObjectKey>(&example), // The data type we are sorting
                   recvbuf,
                   &proc_bin_size[0], // How much is to be received from each processor
                   &displacements[0], // Offsets into the receive buffer
                   Parallel::StandardType<Parallel::DofObjectKey>(&example), // The data type we are sorting
                   i,                        // The root process (we do this once for each proc)
                   this->comm().get());
       // Copy the destination buffer if it
       // corresponds to the bin for this processor
       if (i == _proc_id)
         _my_bin = dest;
       // Increment the local offset counter
       local_offset += _local_bin_sizes[i];
     }
 }
processor_id_type libMesh::ParallelObject::n_processors () const inline inherited
Returns
The number of processors in the group.
Definition at line 93 of file parallel_object.h.
References libMesh::ParallelObject::_communicator, and libMesh::Parallel::Communicator::size().
Referenced by libMesh::ParmetisPartitioner::_do_repartition(), libMesh::BoundaryInfo::_find_id_maps(), libMesh::DistributedMesh::add_elem(), libMesh::DistributedMesh::add_node(), libMesh::LaplaceMeshSmoother::allgather_graph(), libMesh::FEMSystem::assembly(), libMesh::ParmetisPartitioner::assign_partitioning(), libMesh::AztecLinearSolver< T >::AztecLinearSolver(), libMesh::MeshCommunication::broadcast(), libMesh::BoundaryInfo::build_node_list_from_side_list(), libMesh::DistributedMesh::clear(), libMesh::Nemesis_IO_Helper::compute_border_node_ids(), libMesh::Nemesis_IO_Helper::construct_nemesis_filename(), libMesh::MeshTools::correct_node_proc_ids(), libMesh::UnstructuredMesh::create_pid_mesh(), libMesh::MeshTools::create_processor_bounding_box(), libMesh::DofMap::distribute_dofs(), libMesh::DofMap::distribute_local_dofs_node_major(), libMesh::DofMap::distribute_local_dofs_var_major(), libMesh::DistributedMesh::DistributedMesh(), libMesh::EnsightIO::EnsightIO(), libMesh::MeshCommunication::gather(), libMesh::MeshCommunication::gather_neighboring_elements(), libMesh::MeshBase::get_info(), libMesh::EquationSystems::get_solution(), libMesh::DistributedVector< T >::init(), libMesh::SystemSubsetBySubdomain::init(), libMesh::ParmetisPartitioner::initialize(), libMesh::Nemesis_IO_Helper::initialize(), libMesh::DistributedMesh::insert_elem(), libMesh::MeshTools::libmesh_assert_parallel_consistent_procids< Elem >(), libMesh::MeshTools::libmesh_assert_parallel_consistent_procids< Node >(), libMesh::MeshTools::libmesh_assert_topology_consistent_procids< Node >(), libMesh::MeshTools::libmesh_assert_valid_boundary_ids(), libMesh::MeshTools::libmesh_assert_valid_dof_ids(), libMesh::MeshTools::libmesh_assert_valid_neighbors(), libMesh::MeshTools::libmesh_assert_valid_refinement_flags(), libMesh::DofMap::local_variable_indices(), libMesh::MeshRefinement::make_coarsening_compatible(), libMesh::MeshBase::n_active_elem_on_proc(), libMesh::MeshBase::n_elem_on_proc(), libMesh::MeshBase::n_nodes_on_proc(), libMesh::SparsityPattern::Build::parallel_sync(), libMesh::Partitioner::partition(), libMesh::MeshBase::partition(), libMesh::Partitioner::partition_unpartitioned_elements(), libMesh::PetscLinearSolver< T >::PetscLinearSolver(), libMesh::System::point_gradient(), libMesh::System::point_hessian(), libMesh::System::point_value(), libMesh::SparseMatrix< T >::print(), libMesh::NameBasedIO::read(), libMesh::Nemesis_IO::read(), libMesh::CheckpointIO::read(), libMesh::XdrIO::read(), libMesh::CheckpointIO::read_connectivity(), libMesh::CheckpointIO::read_nodes(), libMesh::MeshCommunication::redistribute(), libMesh::DistributedMesh::renumber_dof_objects(), libMesh::Partitioner::repartition(), libMesh::MeshCommunication::send_coarse_ghosts(), libMesh::Partitioner::set_node_processor_ids(), libMesh::DofMap::set_nonlocal_dof_objects(), libMesh::Parallel::Sort< KeyType, IdxType >::sort(), libMesh::MeshRefinement::uniformly_coarsen(), libMesh::DistributedMesh::update_parallel_id_counts(), libMesh::GMVIO::write_binary(), libMesh::GMVIO::write_discontinuous_gmv(), libMesh::XdrIO::write_serialized_bcs_helper(), libMesh::XdrIO::write_serialized_connectivity(), libMesh::XdrIO::write_serialized_nodes(), and libMesh::XdrIO::write_serialized_nodesets().
   { return cast_int<processor_id_type>(_communicator.size()); }
processor_id_type libMesh::ParallelObject::processor_id () const inline inherited
Returns
The rank of this processor in the group.
Definition at line 99 of file parallel_object.h.
References libMesh::ParallelObject::_communicator, and libMesh::Parallel::Communicator::rank().
Referenced by libMesh::BoundaryInfo::_find_id_maps(), libMesh::EquationSystems::_read_impl(), libMesh::DistributedMesh::add_elem(), libMesh::BoundaryInfo::add_elements(), libMesh::DofMap::add_neighbors_to_send_list(), libMesh::DistributedMesh::add_node(), libMesh::MeshRefinement::add_node(), libMesh::MeshTools::Modification::all_tri(), libMesh::FEMSystem::assembly(), libMesh::ParmetisPartitioner::assign_partitioning(), libMesh::MeshCommunication::broadcast(), libMesh::EquationSystems::build_discontinuous_solution_vector(), libMesh::Nemesis_IO_Helper::build_element_and_node_maps(), libMesh::ParmetisPartitioner::build_graph(), libMesh::InfElemBuilder::build_inf_elem(), libMesh::BoundaryInfo::build_node_list_from_side_list(), libMesh::DofMap::build_sparsity(), libMesh::DistributedMesh::clear(), libMesh::ExodusII_IO_Helper::close(), libMesh::Nemesis_IO_Helper::compute_border_node_ids(), libMesh::Nemesis_IO_Helper::compute_communication_map_parameters(), libMesh::Nemesis_IO_Helper::compute_internal_and_border_elems_and_internal_nodes(), libMesh::Nemesis_IO_Helper::compute_node_communication_maps(), libMesh::Nemesis_IO_Helper::compute_num_global_elem_blocks(), libMesh::Nemesis_IO_Helper::compute_num_global_nodesets(), libMesh::Nemesis_IO_Helper::compute_num_global_sidesets(), libMesh::Nemesis_IO_Helper::construct_nemesis_filename(), libMesh::MeshTools::correct_node_proc_ids(), libMesh::ExodusII_IO_Helper::create(), libMesh::DistributedMesh::delete_elem(), libMesh::DistributedMesh::delete_node(), libMesh::MeshCommunication::delete_remote_elements(), libMesh::DofMap::distribute_dofs(), libMesh::DofMap::distribute_local_dofs_node_major(), libMesh::DofMap::distribute_local_dofs_var_major(), libMesh::DistributedMesh::DistributedMesh(), libMesh::EnsightIO::EnsightIO(), libMesh::MeshFunction::find_element(), libMesh::MeshFunction::find_elements(), libMesh::UnstructuredMesh::find_neighbors(), libMesh::MeshCommunication::gather(), libMesh::MeshCommunication::gather_neighboring_elements(), libMesh::Nemesis_IO_Helper::get_cmap_params(), libMesh::Nemesis_IO_Helper::get_eb_info_global(), libMesh::Nemesis_IO_Helper::get_elem_cmap(), libMesh::Nemesis_IO_Helper::get_elem_map(), libMesh::MeshBase::get_info(), libMesh::DofMap::get_info(), libMesh::Nemesis_IO_Helper::get_init_global(), libMesh::Nemesis_IO_Helper::get_init_info(), libMesh::Nemesis_IO_Helper::get_loadbal_param(), libMesh::Nemesis_IO_Helper::get_node_cmap(), libMesh::Nemesis_IO_Helper::get_node_map(), libMesh::Nemesis_IO_Helper::get_ns_param_global(), libMesh::EquationSystems::get_solution(), libMesh::Nemesis_IO_Helper::get_ss_param_global(), libMesh::SparsityPattern::Build::handle_vi_vj(), libMesh::DistributedVector< T >::init(), libMesh::SystemSubsetBySubdomain::init(), libMesh::ParmetisPartitioner::initialize(), libMesh::ExodusII_IO_Helper::initialize(), libMesh::ExodusII_IO_Helper::initialize_element_variables(), libMesh::ExodusII_IO_Helper::initialize_global_variables(), libMesh::ExodusII_IO_Helper::initialize_nodal_variables(), libMesh::DistributedMesh::insert_elem(), libMesh::DofMap::is_evaluable(), libMesh::SparsityPattern::Build::join(), libMesh::MeshTools::libmesh_assert_parallel_consistent_procids< Elem >(), libMesh::MeshTools::libmesh_assert_parallel_consistent_procids< Node >(), libMesh::MeshTools::libmesh_assert_valid_neighbors(), libMesh::DistributedMesh::libmesh_assert_valid_parallel_object_ids(), libMesh::DofMap::local_variable_indices(), libMesh::MeshRefinement::make_coarsening_compatible(), libMesh::MeshBase::n_active_local_elem(), libMesh::BoundaryInfo::n_boundary_conds(), libMesh::BoundaryInfo::n_edge_conds(), libMesh::System::n_local_dofs(), libMesh::MeshBase::n_local_elem(), libMesh::MeshBase::n_local_nodes(), libMesh::BoundaryInfo::n_nodeset_conds(), libMesh::BoundaryInfo::n_shellface_conds(), libMesh::WeightedPatchRecoveryErrorEstimator::EstimateError::operator()(), libMesh::SparsityPattern::Build::operator()(), libMesh::PatchRecoveryErrorEstimator::EstimateError::operator()(), libMesh::SparsityPattern::Build::parallel_sync(), libMesh::MetisPartitioner::partition_range(), libMesh::System::point_gradient(), libMesh::System::point_hessian(), libMesh::System::point_value(), libMesh::SparseMatrix< T >::print(), libMesh::NumericVector< T >::print_global(), libMesh::Nemesis_IO_Helper::put_cmap_params(), libMesh::Nemesis_IO_Helper::put_elem_cmap(), libMesh::Nemesis_IO_Helper::put_elem_map(), libMesh::Nemesis_IO_Helper::put_loadbal_param(), libMesh::Nemesis_IO_Helper::put_node_cmap(), libMesh::Nemesis_IO_Helper::put_node_map(), libMesh::NameBasedIO::read(), libMesh::Nemesis_IO::read(), libMesh::CheckpointIO::read(), libMesh::XdrIO::read(), libMesh::ExodusII_IO_Helper::read_elem_num_map(), libMesh::CheckpointIO::read_header(), libMesh::ExodusII_IO_Helper::read_node_num_map(), libMesh::XdrIO::read_serialized_bc_names(), libMesh::XdrIO::read_serialized_bcs_helper(), libMesh::XdrIO::read_serialized_connectivity(), libMesh::XdrIO::read_serialized_nodes(), libMesh::XdrIO::read_serialized_nodesets(), libMesh::XdrIO::read_serialized_subdomain_names(), libMesh::MeshCommunication::redistribute(), libMesh::DistributedMesh::renumber_dof_objects(), libMesh::MeshCommunication::send_coarse_ghosts(), libMesh::Partitioner::set_node_processor_ids(), libMesh::DofMap::set_nonlocal_dof_objects(), libMesh::LaplaceMeshSmoother::smooth(), libMesh::MeshTools::total_weight(), libMesh::MeshRefinement::uniformly_coarsen(), libMesh::Parallel::Packing< Node * >::unpack(), libMesh::Parallel::Packing< Elem * >::unpack(), libMesh::DistributedMesh::update_parallel_id_counts(), libMesh::MeshTools::weight(), libMesh::NameBasedIO::write(), libMesh::CheckpointIO::write(), libMesh::XdrIO::write(), libMesh::EquationSystems::write(), libMesh::GMVIO::write_discontinuous_gmv(), libMesh::ExodusII_IO::write_element_data(), libMesh::ExodusII_IO_Helper::write_element_values(), libMesh::ExodusII_IO_Helper::write_elements(), libMesh::ExodusII_IO::write_global_data(), libMesh::ExodusII_IO_Helper::write_global_values(), libMesh::ExodusII_IO::write_information_records(), libMesh::ExodusII_IO_Helper::write_information_records(), libMesh::ExodusII_IO_Helper::write_nodal_coordinates(), libMesh::UCDIO::write_nodal_data(), libMesh::ExodusII_IO::write_nodal_data(), libMesh::ExodusII_IO::write_nodal_data_discontinuous(), libMesh::ExodusII_IO_Helper::write_nodal_values(), libMesh::Nemesis_IO_Helper::write_nodesets(), libMesh::ExodusII_IO_Helper::write_nodesets(), libMesh::XdrIO::write_serialized_bc_names(), libMesh::XdrIO::write_serialized_bcs_helper(), libMesh::XdrIO::write_serialized_connectivity(), libMesh::XdrIO::write_serialized_nodes(), libMesh::XdrIO::write_serialized_nodesets(), libMesh::XdrIO::write_serialized_subdomain_names(), libMesh::Nemesis_IO_Helper::write_sidesets(), libMesh::ExodusII_IO_Helper::write_sidesets(), libMesh::ExodusII_IO::write_timestep(), and libMesh::ExodusII_IO_Helper::write_timestep().
   { return cast_int<processor_id_type>(_communicator.rank()); }
template<typename KeyType , typename IdxType > void libMesh::Parallel::Sort< KeyType, IdxType >::sort ()
This is the only method which needs to be called by the user. Its only responsibility is to call three private methods in the correct order.
Definition at line 58 of file parallel_sort.C.
References libMesh::Parallel::Sort< KeyType, IdxType >::_bin_is_sorted, libMesh::Parallel::Sort< KeyType, IdxType >::_data, libMesh::Parallel::Sort< KeyType, IdxType >::_local_bin_sizes, libMesh::Parallel::Sort< KeyType, IdxType >::_my_bin, libMesh::Parallel::Communicator::allgather(), libMesh::Parallel::Sort< KeyType, IdxType >::binsort(), libMesh::ParallelObject::comm(), libMesh::Parallel::Sort< KeyType, IdxType >::communicate_bins(), libMesh::ParallelObject::n_processors(), libMesh::Parallel::Sort< KeyType, IdxType >::sort_local_bin(), and libMesh::Parallel::Communicator::sum().
Referenced by libMesh::MeshCommunication::assign_global_indices(), and libMesh::MeshCommunication::find_global_indices().
 {
   // Find the global data size.  The sorting
   // algorithms assume they have a range to
   // work with, so catch the degenerate cases here
   IdxType global_data_size = cast_int<IdxType>(_data.size());
   this->comm().sum (global_data_size);
   if (global_data_size < 2)
     {
       // the entire global range is either empty
       // or contains only one element
       _my_bin = _data;
       this->comm().allgather (static_cast<IdxType>(_my_bin.size()),
                               _local_bin_sizes);
     }
   else
     {
       if (this->n_processors() > 1)
         {
           this->binsort();
           this->communicate_bins();
         }
       else
         _my_bin = _data;
       this->sort_local_bin();
     }
   // Set sorted flag to true
   _bin_is_sorted = true;
 }
template<typename KeyType , typename IdxType > void libMesh::Parallel::Sort< KeyType, IdxType >::sort_local_bin () private
After all the bins have been communicated, we can sort our local bin. This is nothing more than a call to std::sort
Definition at line 368 of file parallel_sort.C.
References libMesh::Parallel::Sort< KeyType, IdxType >::_my_bin.
Referenced by libMesh::Parallel::Sort< KeyType, IdxType >::sort().
 {
   std::sort(_my_bin.begin(), _my_bin.end());
 }
Member Data Documentation
template<typename KeyType, typename IdxType = unsigned int> bool libMesh::Parallel::Sort< KeyType, IdxType >::_bin_is_sorted private
Flag which lets you know if sorting is complete
Definition at line 98 of file parallel_sort.h.
Referenced by libMesh::Parallel::Sort< KeyType, IdxType >::bin(), and libMesh::Parallel::Sort< KeyType, IdxType >::sort().
const Parallel::Communicator& libMesh::ParallelObject::_communicator protected inherited
Definition at line 105 of file parallel_object.h.
Referenced by libMesh::EquationSystems::build_parallel_solution_vector(), libMesh::ParallelObject::comm(), libMesh::EquationSystems::get_solution(), libMesh::ParallelObject::n_processors(), libMesh::ParallelObject::operator=(), and libMesh::ParallelObject::processor_id().
template<typename KeyType, typename IdxType = unsigned int> std::vector<KeyType>& libMesh::Parallel::Sort< KeyType, IdxType >::_data private
The raw, unsorted data which will need to be sorted (in parallel) across all processors.
Definition at line 105 of file parallel_sort.h.
Referenced by libMesh::Parallel::Sort< KeyType, IdxType >::binsort(), libMesh::Parallel::Sort< KeyType, IdxType >::communicate_bins(), libMesh::Parallel::Sort< KeyType, IdxType >::Sort(), and libMesh::Parallel::Sort< KeyType, IdxType >::sort().
template<typename KeyType, typename IdxType = unsigned int> std::vector<IdxType> libMesh::Parallel::Sort< KeyType, IdxType >::_local_bin_sizes private
Vector which holds the size of each bin on this processor. It has size equal to _n_procs.
Definition at line 112 of file parallel_sort.h.
Referenced by libMesh::Parallel::Sort< KeyType, IdxType >::binsort(), libMesh::Parallel::Sort< KeyType, IdxType >::communicate_bins(), libMesh::Parallel::Sort< KeyType, IdxType >::Sort(), and libMesh::Parallel::Sort< KeyType, IdxType >::sort().
template<typename KeyType, typename IdxType = unsigned int> std::vector<KeyType> libMesh::Parallel::Sort< KeyType, IdxType >::_my_bin private
The bin which will eventually be held by this processor. It may be shorter or longer than _data. It will be dynamically resized when it is needed.
Definition at line 120 of file parallel_sort.h.
Referenced by libMesh::Parallel::Sort< KeyType, IdxType >::bin(), libMesh::Parallel::Sort< KeyType, IdxType >::communicate_bins(), libMesh::Parallel::Sort< KeyType, IdxType >::sort(), and libMesh::Parallel::Sort< KeyType, IdxType >::sort_local_bin().
template<typename KeyType, typename IdxType = unsigned int> const processor_id_type libMesh::Parallel::Sort< KeyType, IdxType >::_n_procs private
The number of processors to work with.
Definition at line 88 of file parallel_sort.h.
Referenced by libMesh::Parallel::Sort< KeyType, IdxType >::binsort(), libMesh::Parallel::Sort< KeyType, IdxType >::communicate_bins(), and libMesh::Parallel::Sort< KeyType, IdxType >::Sort().
template<typename KeyType, typename IdxType = unsigned int> const processor_id_type libMesh::Parallel::Sort< KeyType, IdxType >::_proc_id private
The identity of this processor.
Definition at line 93 of file parallel_sort.h.
Referenced by libMesh::Parallel::Sort< KeyType, IdxType >::communicate_bins().
The documentation for this class was generated from the following files:
parallel_sort.h
parallel_sort.C