libMesh: libMesh::TreeBase Class Reference
SomeWebsiteLogo
libMesh::TreeBase Class Reference abstract
#include <tree_base.h>
Public Member Functions
virtual ~TreeBase ()
virtual void print_nodes (std::ostream &out=libMesh::out) const =0
virtual void print_elements (std::ostream &out=libMesh::out) const =0
virtual unsigned int n_active_bins () const =0
virtual const Elem * find_element (const Point &p, const std::set< subdomain_id_type > *allowed_subdomains=libmesh_nullptr, Real relative_tol=TOLERANCE) const =0
Static Public Member Functions
static std::string get_info ()
static void print_info (std::ostream &out=libMesh::out)
static unsigned int n_objects ()
static void enable_print_counter_info ()
static void disable_print_counter_info ()
Protected Member Functions
TreeBase (const MeshBase &m)
Protected Attributes
const MeshBase & mesh
Static Protected Attributes
static Threads::atomic< unsigned int > _n_objects
static Threads::spin_mutex _mutex
static bool _enable_print_counter = true
Detailed Description
This is the base class for trees, it allows pointer usage of trees.
Definition at line 61 of file tree_base.h.
Constructor & Destructor Documentation
libMesh::TreeBase::TreeBase (const MeshBase & m) inline explicit protected
Constructor. Protected.
Definition at line 114 of file tree_base.h.
                                       :
   mesh(m)
 {
 }
virtual libMesh::TreeBase::~TreeBase () inline virtual
Destructor.
Definition at line 74 of file tree_base.h.
 {}
Member Function Documentation
void libMesh::ReferenceCounter::disable_print_counter_info () static inherited
Definition at line 106 of file reference_counter.C.
References libMesh::ReferenceCounter::_enable_print_counter.
Referenced by libMesh::LibMeshInit::LibMeshInit().
 {
   _enable_print_counter = false;
   return;
 }
void libMesh::ReferenceCounter::enable_print_counter_info () static inherited
Methods to enable/disable the reference counter output from print_info()
Definition at line 100 of file reference_counter.C.
References libMesh::ReferenceCounter::_enable_print_counter.
 {
   _enable_print_counter = true;
   return;
 }
virtual const Elem* libMesh::TreeBase::find_element (const Point & p, const std::set< subdomain_id_type > * allowed_subdomains = libmesh_nullptr, Real relative_tol = TOLERANCE) const pure virtual
Returns
a pointer to the element containing point p, optionally restricted to a set of allowed subdomains, optionally using a non-zero relative tolerance for searches.
Implemented in libMesh::Tree< N >.
Referenced by libMesh::PointLocatorTree::operator()().
std::string libMesh::ReferenceCounter::get_info () static inherited
Gets a string containing the reference information.
Definition at line 47 of file reference_counter.C.
References libMesh::Quality::name().
 {
 #if defined(LIBMESH_ENABLE_REFERENCE_COUNTING) && defined(DEBUG)
   std::ostringstream oss;
   oss << '\n'
       << " ---------------------------------------------------------------------------- \n"
       << "| Reference count information                                                |\n"
       << " ---------------------------------------------------------------------------- \n";
   for (Counts::iterator it = _counts.begin();
        it != _counts.end(); ++it)
     {
       const std::string name(it->first);
       const unsigned int creations    = it->second.first;
       const unsigned int destructions = it->second.second;
       oss << "| " << name << " reference count information:\n"
           << "|  Creations:    " << creations    << '\n'
           << "|  Destructions: " << destructions << '\n';
     }
   oss << " ---------------------------------------------------------------------------- \n";
   return oss.str();
 #else
   return "";
 #endif
 }
virtual unsigned int libMesh::TreeBase::n_active_bins () const pure virtual
Returns
the number of active bins.
Implemented in libMesh::Tree< N >.
static unsigned int libMesh::ReferenceCounter::n_objects () inline static inherited
Prints the number of outstanding (created, but not yet destroyed) objects.
Definition at line 75 of file reference_counter.h.
References libMesh::ReferenceCounter::_n_objects.
Referenced by libMesh::LibMeshInit::~LibMeshInit().
   { return _n_objects; }
virtual void libMesh::TreeBase::print_elements (std::ostream & out = libMesh::out) const pure virtual
Prints the nodes.
Implemented in libMesh::Tree< N >.
void libMesh::ReferenceCounter::print_info (std::ostream & out = libMesh::out) static inherited
Prints the reference information, by default to libMesh::out.
Definition at line 95 of file reference_counter.C.
Referenced by libMesh::LibMeshInit::~LibMeshInit().
 {}
virtual void libMesh::TreeBase::print_nodes (std::ostream & out = libMesh::out) const pure virtual
Prints the nodes.
Implemented in libMesh::Tree< N >.
Member Data Documentation
bool libMesh::ReferenceCounter::_enable_print_counter = true static protected inherited
Flag to control whether reference count information is printed when print_info is called.
Definition at line 133 of file reference_counter.h.
Referenced by libMesh::ReferenceCounter::disable_print_counter_info(), and libMesh::ReferenceCounter::enable_print_counter_info().
Threads::spin_mutex libMesh::ReferenceCounter::_mutex static protected inherited
Mutual exclusion object to enable thread-safe reference counting.
Definition at line 127 of file reference_counter.h.
Threads::atomic< unsigned int > libMesh::ReferenceCounter::_n_objects static protected inherited
The number of objects. Print the reference count information when the number returns to 0.
Definition at line 122 of file reference_counter.h.
Referenced by libMesh::ReferenceCounter::n_objects(), libMesh::ReferenceCounter::ReferenceCounter(), and libMesh::ReferenceCounter::~ReferenceCounter().
const MeshBase& libMesh::TreeBase::mesh protected
Constant reference to a mesh. Declared at construction.
Definition at line 106 of file tree_base.h.
Referenced by libMesh::Tree< N >::Tree().
The documentation for this class was generated from the following file:
tree_base.h