libMesh: libMesh::VariableGroup Class Reference
SomeWebsiteLogo
libMesh::VariableGroup Class Reference
#include <variable.h>
Public Member Functions
VariableGroup (System *sys, const std::vector< std::string > &var_names, const unsigned int var_number, const unsigned int first_scalar_num, const FEType &var_type)
VariableGroup (System *sys, const std::vector< std::string > &var_names, const unsigned int var_number, const unsigned int first_scalar_num, const FEType &var_type, const std::set< subdomain_id_type > &var_active_subdomains)
unsigned int n_variables () const
Variable variable (unsigned int v) const
Variable operator() (unsigned int v) const
const std::string & name (unsigned int v) const
unsigned int number (unsigned int v) const
unsigned int first_scalar_number (unsigned int v) const
void append (const std::string &var_name)
unsigned int number () const
System * system () const
const std::string & name () const
unsigned int number () const
unsigned int first_scalar_number () const
const FEType & type () const
unsigned int n_components () const
bool active_on_subdomain (subdomain_id_type sid) const
bool implicitly_active () const
const std::set< subdomain_id_type > & active_subdomains () const
Protected Attributes
std::vector< std::string > _names
System * _sys
std::string _name
std::set< subdomain_id_type > _active_subdomains
unsigned int _number
unsigned int _first_scalar_number
FEType _type
Detailed Description
This class defines a logically grouped set of variables in the system. VariableGroup is appropriate for representing several unknowns in the problem that are all approximated with the same finite element approximation family and (optionally) a list of subdomains to which the variables are restricted.
Definition at line 172 of file variable.h.
Constructor & Destructor Documentation
VariableGroup() [1/2]
libMesh::VariableGroup::VariableGroup (System * sys, const std::vector< std::string > & var_names, const unsigned int var_number, const unsigned int first_scalar_num, const FEType & var_type) inline
Constructor. Omits the subdomain mapping, hence this constructor creates a variable which is active on all subdomains.
Definition at line 180 of file variable.h.
                                           :
     Variable (sys,
               "var_group",
               var_number,
               first_scalar_num,
               var_type),
     _names(var_names)
   {}
VariableGroup() [2/2]
libMesh::VariableGroup::VariableGroup (System * sys, const std::vector< std::string > & var_names, const unsigned int var_number, const unsigned int first_scalar_num, const FEType & var_type, const std::set< subdomain_id_type > & var_active_subdomains) inline
Constructor. Takes a set which contains the subdomain indices for which this variable is active.
Definition at line 198 of file variable.h.
                                                                           :
     Variable (sys,
               "var_group",
               var_number,
               first_scalar_num,
               var_type,
               var_active_subdomains),
     _names(var_names)
   {}
Member Function Documentation
active_on_subdomain()
bool libMesh::Variable::active_on_subdomain (subdomain_id_type sid) const inline inherited
Returns
true if this variable is active on subdomain sid, false otherwise.
Note
We interpret the special case of an empty _active_subdomains container as active everywhere, i.e. for all subdomains.
Definition at line 136 of file variable.h.
References libMesh::Variable::_active_subdomains.
Referenced by libMesh::ExactSolution::_compute_error(), libMesh::DofMap::_dof_indices(), libMesh::EquationSystems::build_discontinuous_solution_vector(), libMesh::EquationSystems::build_parallel_elemental_solution_vector(), libMesh::EquationSystems::build_parallel_solution_vector(), libMesh::DofMap::distribute_local_dofs_node_major(), libMesh::DofMap::distribute_local_dofs_var_major(), libMesh::DofMap::dof_indices(), libMesh::DofMap::local_variable_indices(), libMesh::DofMap::old_dof_indices(), libMesh::GenericProjector< FFunctor, GFunctor, FValue, ProjectionAction >::operator()(), libMesh::BoundaryProjectSolution::operator()(), and libMesh::DofMap::reinit().
   { return (_active_subdomains.empty() || _active_subdomains.count(sid));  }
active_subdomains()
const std::set<subdomain_id_type>& libMesh::Variable::active_subdomains () const inline inherited
Returns
The set of subdomain ids this variable lives on.
Definition at line 150 of file variable.h.
References libMesh::Variable::_active_subdomains.
Referenced by libMesh::DifferentiableSystem::add_second_order_dot_vars(), libMesh::EquationSystems::get_vars_active_subdomains(), variable(), and libMesh::System::write_header().
   { return _active_subdomains; }
append()
void libMesh::VariableGroup::append (const std::string & var_name) inline
Appends a variable to the group. Really only can be used by System in a very limited window of opportunity - after the user specifies variables but before the system is initialized.
Definition at line 279 of file variable.h.
References _names.
Referenced by libMesh::System::add_variable().
   { _names.push_back (var_name); }
first_scalar_number() [1/2]
unsigned int libMesh::Variable::first_scalar_number () const inline inherited
Returns
The index of the first scalar component of this variable in the system.
Definition at line 113 of file variable.h.
References libMesh::Variable::_first_scalar_number.
Referenced by libMesh::System::n_components(), and variable().
   { return _first_scalar_number; }
first_scalar_number() [2/2]
unsigned int libMesh::VariableGroup::first_scalar_number (unsigned int v) const inline
Returns
The index of the first scalar component of this variable in the system.
Definition at line 268 of file variable.h.
References libMesh::Variable::_first_scalar_number, and n_variables().
   {
     libmesh_assert_less (v, this->n_variables());
     return _first_scalar_number+v;
   }
implicitly_active()
bool libMesh::Variable::implicitly_active () const inline inherited
Returns
true if this variable is active on all subdomains because it has no specified activity map. This can be used to perform more efficient computations in some places.
Definition at line 144 of file variable.h.
References libMesh::Variable::_active_subdomains.
   { return _active_subdomains.empty(); }
n_components()
unsigned int libMesh::Variable::n_components () const inline inherited
Returns
The number of components of this variable.
Definition at line 125 of file variable.h.
References libMesh::Variable::_type, libMesh::FEType::family, libMesh::OrderWrapper::get_order(), libMesh::FEType::order, libMesh::SCALAR, and libMesh::Variable::type().
Referenced by libMesh::System::n_components().
   { return type().family == SCALAR ? _type.order.get_order() : 1; }
n_variables()
unsigned int libMesh::VariableGroup::n_variables () const inline
Returns
The number of variables in this VariableGroup
Definition at line 217 of file variable.h.
References _names.
Referenced by libMesh::DofMap::add_variable_group(), libMesh::DofMap::distribute_local_dofs_node_major(), libMesh::DofMap::distribute_local_dofs_var_major(), libMesh::DofMap::dof_indices(), first_scalar_number(), libMesh::System::get_info(), name(), number(), libMesh::DofMap::old_dof_indices(), libMesh::DofMap::reinit(), and variable().
   { return cast_int<unsigned int>(_names.size()); }
name() [1/2]
const std::string& libMesh::Variable::name () const inline inherited
Returns
The user-specified name of the variable.
Definition at line 100 of file variable.h.
References libMesh::Variable::_name.
Referenced by libMesh::DifferentiableSystem::add_second_order_dot_vars(), DMlibMeshSetSystem_libMesh(), and variable().
   { return _name; }
name() [2/2]
const std::string& libMesh::VariableGroup::name (unsigned int v) const inline
Returns
The user-specified name of the variable.
Definition at line 246 of file variable.h.
References _names, and n_variables().
Referenced by libMesh::System::get_info().
   {
     libmesh_assert_less (v, this->n_variables());
     return _names[v];
   }
number() [1/3]
unsigned int libMesh::Variable::number () const inline inherited
Returns
The rank of this variable in the system.
Definition at line 106 of file variable.h.
References libMesh::Variable::_number.
Referenced by variable().
   { return _number; }
number() [2/3]
unsigned int libMesh::VariableGroup::number (unsigned int v) const inline
Returns
The rank of this variable in the system.
Definition at line 255 of file variable.h.
References libMesh::Variable::_number, and n_variables().
Referenced by libMesh::DofMap::dof_indices(), and libMesh::DofMap::old_dof_indices().
   {
     libmesh_assert_less (v, this->n_variables());
     return _number + v;
   }
number() [3/3]
unsigned int libMesh::Variable::number inline
Returns
The rank of this variable in the system.
Definition at line 106 of file variable.h.
   { return _number; }
operator()()
Variable libMesh::VariableGroup::operator() (unsigned int v) const inline
Support vg(v).
Returns
A Variable for v.
Definition at line 240 of file variable.h.
References variable().
   { return this->variable(v); }
system()
System* libMesh::Variable::system () const inline inherited
Returns
A pointer to the System this Variable is part of.
Definition at line 92 of file variable.h.
References libMesh::Variable::_sys.
Referenced by variable().
   {
     return _sys;
   }
type()
const FEType& libMesh::Variable::type () const inline inherited
Returns
The FEType for this variable.
Definition at line 119 of file variable.h.
References libMesh::Variable::_type.
Referenced by libMesh::DofMap::_dof_indices(), libMesh::PetscDMWrapper::add_dofs_to_section(), libMesh::DifferentiableSystem::add_second_order_dot_vars(), libMesh::FEMSystem::assembly(), libMesh::FirstOrderUnsteadySolver::compute_second_order_eqns(), libMesh::DofMap::distribute_dofs(), libMesh::DofMap::distribute_local_dofs_node_major(), libMesh::DofMap::distribute_local_dofs_var_major(), libMesh::DofMap::dof_indices(), libMesh::System::get_info(), libMesh::Variable::n_components(), libMesh::DofMap::old_dof_indices(), libMesh::GenericProjector< FFunctor, GFunctor, FValue, ProjectionAction >::operator()(), libMesh::BoundaryProjectSolution::operator()(), libMesh::System::read_parallel_data(), libMesh::System::read_SCALAR_dofs(), libMesh::System::read_serialized_vectors(), libMesh::DofMap::reinit(), libMesh::DofMap::SCALAR_dof_indices(), libMesh::PetscDMWrapper::set_point_range_in_section(), variable(), libMesh::System::write_parallel_data(), libMesh::System::write_serialized_vector(), and libMesh::System::write_serialized_vectors().
   { return _type; }
variable()
Variable libMesh::VariableGroup::variable (unsigned int v) const inline
Returns
A Variable object constructed for an individual member of our group.
Definition at line 224 of file variable.h.
References libMesh::Variable::active_subdomains(), libMesh::Variable::first_scalar_number(), n_variables(), libMesh::Variable::name(), libMesh::Variable::number(), libMesh::Variable::system(), libMesh::Variable::type(), and libMesh::Variable::Variable().
Referenced by operator()().
   {
     libmesh_assert_less (v, this->n_variables());
     return Variable (this->system(),
                      this->name(v),
                      this->number(v),
                      this->first_scalar_number(v),
                      this->type(),
                      this->active_subdomains());
   }
Member Data Documentation
_active_subdomains
std::set<subdomain_id_type> libMesh::Variable::_active_subdomains protected inherited
Definition at line 156 of file variable.h.
Referenced by libMesh::Variable::active_on_subdomain(), libMesh::Variable::active_subdomains(), and libMesh::Variable::implicitly_active().
_first_scalar_number
unsigned int libMesh::Variable::_first_scalar_number protected inherited
Definition at line 158 of file variable.h.
Referenced by libMesh::Variable::first_scalar_number(), and first_scalar_number().
_name
std::string libMesh::Variable::_name protected inherited
Definition at line 155 of file variable.h.
Referenced by libMesh::Variable::name().
_names
std::vector<std::string> libMesh::VariableGroup::_names protected
Definition at line 283 of file variable.h.
Referenced by append(), n_variables(), and name().
_number
unsigned int libMesh::Variable::_number protected inherited
Definition at line 157 of file variable.h.
Referenced by libMesh::Variable::number(), and number().
_sys
System* libMesh::Variable::_sys protected inherited
Definition at line 154 of file variable.h.
Referenced by libMesh::Variable::system().
_type
FEType libMesh::Variable::_type protected inherited
Definition at line 159 of file variable.h.
Referenced by libMesh::Variable::n_components(), and libMesh::Variable::type().
The documentation for this class was generated from the following file:
variable.h