libMesh: libMesh::DenseVectorBase< T > Class Template Reference
SomeWebsiteLogo
libMesh::DenseVectorBase< T > Class Template Reference abstract
#include <dense_matrix_base.h>
Public Member Functions
DenseVectorBase ()=default
DenseVectorBase (DenseVectorBase &&)=default
DenseVectorBase (const DenseVectorBase &)=default
DenseVectorBase & operator= (const DenseVectorBase &)=default
DenseVectorBase & operator= (DenseVectorBase &&)=default
virtual ~DenseVectorBase ()=default
virtual void zero ()=0
virtual T el (const unsigned int i) const =0
virtual T & el (const unsigned int i)=0
virtual unsigned int size () const =0
virtual bool empty () const
void print (std::ostream &os) const
void print_scientific (std::ostream &os, unsigned precision=8) const
Friends
std::ostream & operator<< (std::ostream &os, const DenseVectorBase< T > &v)
Detailed Description
template<typename T>
class libMesh::DenseVectorBase< T >
Defines an abstract dense vector base class for use in Finite Element-type computations. Specialized dense vectors, for example DenseSubVectors, can be derived from this class.
Author
John W. Peterson
Date
2003
Definition at line 33 of file dense_matrix_base.h.
Constructor & Destructor Documentation
DenseVectorBase() [1/3]
template<typename T> libMesh::DenseVectorBase< T >::DenseVectorBase () default
Constructor.
DenseVectorBase() [2/3]
template<typename T> libMesh::DenseVectorBase< T >::DenseVectorBase (DenseVectorBase< T > &&) default
The 5 special functions can be defaulted for this class, as it does not manage any memory itself.
DenseVectorBase() [3/3]
template<typename T> libMesh::DenseVectorBase< T >::DenseVectorBase (const DenseVectorBase< T > &) default
~DenseVectorBase()
template<typename T> virtual libMesh::DenseVectorBase< T >::~DenseVectorBase () virtual default
Member Function Documentation
el() [1/2]
template<typename T> virtual T libMesh::DenseVectorBase< T >::el (const unsigned int i) const pure virtual
Returns
The (i) element of the vector.
Implemented in libMesh::DenseVector< T >, libMesh::DenseVector< Number >, libMesh::DenseVector< Output >, and libMesh::DenseSubVector< T >.
Referenced by libMesh::DenseMatrixBase< T >::condense(), and libMesh::DofMap::extract_local_vector().
el() [2/2]
template<typename T> virtual T& libMesh::DenseVectorBase< T >::el (const unsigned int i) pure virtual
Returns
The (i) element of the vector as a writable reference.
Implemented in libMesh::DenseVector< T >, libMesh::DenseVector< Number >, libMesh::DenseVector< Output >, and libMesh::DenseSubVector< T >.
empty()
template<typename T> virtual bool libMesh::DenseVectorBase< T >::empty () const inline virtual
Returns
true iff size() is 0.
Reimplemented in libMesh::DenseVector< T >, libMesh::DenseVector< Number >, libMesh::DenseVector< Output >, and libMesh::DenseSubVector< T >.
Definition at line 84 of file dense_vector_base.h.
References libMesh::DenseVectorBase< T >::size().
 { return (this->size() == 0); }
operator=() [1/2]
template<typename T> DenseVectorBase& libMesh::DenseVectorBase< T >::operator= (const DenseVectorBase< T > &) default
operator=() [2/2]
template<typename T> DenseVectorBase& libMesh::DenseVectorBase< T >::operator= (DenseVectorBase< T > &&) default
print()
template<typename T > void libMesh::DenseVectorBase< T >::print (std::ostream & os) const
Pretty-print the vector to stdout.
Definition at line 51 of file dense_vector_base.C.
 {
   for (auto i : IntRange<int>(0, this->size()))
     os << std::setw(8)
        << this->el(i)
        << std::endl;
 }
print_scientific()
template<typename T > void libMesh::DenseVectorBase< T >::print_scientific (std::ostream & os, unsigned precision = 8) const
Prints the entries of the vector with additional decimal places in scientific notation.
Definition at line 31 of file dense_vector_base.C.
 {
   // save the initial format flags
   std::ios_base::fmtflags os_flags = os.flags();
   // Print the vector entries.
   for (auto i : IntRange<int>(0, this->size()))
     os << std::setw(10)
        << std::scientific
        << std::setprecision(precision)
        << this->el(i)
        << std::endl;
   // reset the original format flags
   os.flags(os_flags);
 }
size()
template<typename T> virtual unsigned int libMesh::DenseVectorBase< T >::size () const pure virtual
Returns
The size of the vector.
Implemented in libMesh::DenseVector< T >, libMesh::DenseVector< Number >, libMesh::DenseVector< Output >, and libMesh::DenseSubVector< T >.
Referenced by libMesh::DenseMatrixBase< T >::condense(), libMesh::DenseVectorBase< T >::empty(), and libMesh::DofMap::extract_local_vector().
zero()
template<typename T> virtual void libMesh::DenseVectorBase< T >::zero () pure virtual
Set every element in the vector to 0. Needs to be pure virtual since the storage method may be different in derived classes.
Implemented in libMesh::DenseVector< T >, libMesh::DenseVector< Number >, libMesh::DenseVector< Output >, and libMesh::DenseSubVector< T >.
Referenced by libMesh::DofMap::extract_local_vector().
Friends And Related Function Documentation
operator<<
template<typename T> std::ostream& operator<< (std::ostream & os, const DenseVectorBase< T > & v) friend
Same as above, but allows you to print using the usual stream syntax.
Definition at line 95 of file dense_vector_base.h.
   {
     v.print(os);
     return os;
   }
The documentation for this class was generated from the following files:
dense_matrix_base.h
dense_vector_base.h
dense_vector_base.C