libMesh: libMesh::RBEIMAssembly Class Reference
SomeWebsiteLogo
libMesh::RBEIMAssembly Class Reference
#include <rb_eim_assembly.h>
Public Member Functions
RBEIMAssembly (RBEIMConstruction &rb_eim_con_in, unsigned int basis_function_index_in)
virtual ~RBEIMAssembly ()
virtual void evaluate_basis_function (unsigned int var, const Elem &element, const QBase &element_qrule, std::vector< Number > &values)
RBEIMConstruction & get_rb_eim_construction ()
NumericVector< Number > & get_ghosted_basis_function ()
FEBase & get_fe ()
virtual void interior_assembly (FEMContext &)
virtual void boundary_assembly (FEMContext &)
virtual void get_nodal_rhs_values (std::map< numeric_index_type, Number > &values, const System &, const Node &)
Static Public Member Functions
static std::string get_info ()
static void print_info (std::ostream &out=libMesh::out)
static unsigned int n_objects ()
static void enable_print_counter_info ()
static void disable_print_counter_info ()
Protected Types
typedef std::map< std::string, std::pair< unsigned int, unsigned int > > Counts
Protected Member Functions
void increment_constructor_count (const std::string &name)
void increment_destructor_count (const std::string &name)
Static Protected Attributes
static Counts _counts
static Threads::atomic< unsigned int > _n_objects
static Threads::spin_mutex _mutex
static bool _enable_print_counter = true
Private Member Functions
void initialize_fe ()
Private Attributes
RBEIMConstruction & _rb_eim_con
unsigned int _basis_function_index
UniquePtr< NumericVector< Number > > _ghosted_basis_function
UniquePtr< FEBase > _fe
UniquePtr< QBase > _qrule
Detailed Description
This class provides functionality required to define an assembly object that arises from an "Empirical Interpolation Method" (EIM) approximation.
Author
David J. Knezevic
Date
2012
Definition at line 47 of file rb_eim_assembly.h.
Member Typedef Documentation
typedef std::map<std::string, std::pair<unsigned int, unsigned int> > libMesh::ReferenceCounter::Counts protected inherited
Data structure to log the information. The log is identified by the class name.
Definition at line 110 of file reference_counter.h.
Constructor & Destructor Documentation
libMesh::RBEIMAssembly::RBEIMAssembly (RBEIMConstruction & rb_eim_con_in, unsigned int basis_function_index_in)
Constructor.
virtual libMesh::RBEIMAssembly::~RBEIMAssembly () virtual
Destructor.
Member Function Documentation
virtual void libMesh::ElemAssembly::boundary_assembly (FEMContext &) inline virtual inherited
Perform the element boundary assembly.
Definition at line 60 of file elem_assembly.h.
 { }
void libMesh::ReferenceCounter::disable_print_counter_info () static inherited
Definition at line 106 of file reference_counter.C.
References libMesh::ReferenceCounter::_enable_print_counter.
Referenced by libMesh::LibMeshInit::LibMeshInit(), and libMesh::ReferenceCounter::n_objects().
 {
   _enable_print_counter = false;
   return;
 }
void libMesh::ReferenceCounter::enable_print_counter_info () static inherited
Methods to enable/disable the reference counter output from print_info()
Definition at line 100 of file reference_counter.C.
References libMesh::ReferenceCounter::_enable_print_counter.
Referenced by libMesh::ReferenceCounter::n_objects().
 {
   _enable_print_counter = true;
   return;
 }
virtual void libMesh::RBEIMAssembly::evaluate_basis_function (unsigned int var, const Elem & element, const QBase & element_qrule, std::vector< Number > & values) virtual
Evaluate variable var_number of this object's EIM basis function at the points qpoints. Fill values with the basis function values.
FEBase& libMesh::RBEIMAssembly::get_fe ()
Retrieve the FE object.
NumericVector<Number>& libMesh::RBEIMAssembly::get_ghosted_basis_function ()
Get a reference to the ghosted_basis_function.
std::string libMesh::ReferenceCounter::get_info () static inherited
Gets a string containing the reference information.
Definition at line 47 of file reference_counter.C.
References libMesh::ReferenceCounter::_counts, and libMesh::Quality::name().
Referenced by libMesh::ReferenceCounter::print_info().
 {
 #if defined(LIBMESH_ENABLE_REFERENCE_COUNTING) && defined(DEBUG)
   std::ostringstream oss;
   oss << '\n'
       << " ---------------------------------------------------------------------------- \n"
       << "| Reference count information                                                |\n"
       << " ---------------------------------------------------------------------------- \n";
   for (Counts::iterator it = _counts.begin();
        it != _counts.end(); ++it)
     {
       const std::string name(it->first);
       const unsigned int creations    = it->second.first;
       const unsigned int destructions = it->second.second;
       oss << "| " << name << " reference count information:\n"
           << "|  Creations:    " << creations    << '\n'
           << "|  Destructions: " << destructions << '\n';
     }
   oss << " ---------------------------------------------------------------------------- \n";
   return oss.str();
 #else
   return "";
 #endif
 }
virtual void libMesh::ElemAssembly::get_nodal_rhs_values (std::map< numeric_index_type, Number > & values, const System & , const Node &) inline virtual inherited
Get values to add to the RHS vector based on node. This allows one to impose point loads, for example.
Definition at line 67 of file elem_assembly.h.
   {
     // By default, just clear the values map
     values.clear();
   }
RBEIMConstruction& libMesh::RBEIMAssembly::get_rb_eim_construction ()
Get a reference to the RBEIMConstruction object.
void libMesh::ReferenceCounter::increment_constructor_count (const std::string & name) inline protected inherited
Increments the construction counter. Should be called in the constructor of any derived class that will be reference counted.
Definition at line 160 of file reference_counter.h.
References libMesh::ReferenceCounter::_counts, libMesh::Quality::name(), and libMesh::Threads::spin_mtx.
Referenced by libMesh::ReferenceCounter::n_objects(), and libMesh::ReferenceCountedObject< RBParametrized >::ReferenceCountedObject().
 {
   Threads::spin_mutex::scoped_lock lock(Threads::spin_mtx);
   std::pair<unsigned int, unsigned int> & p = _counts[name];
   p.first++;
 }
void libMesh::ReferenceCounter::increment_destructor_count (const std::string & name) inline protected inherited
Increments the destruction counter. Should be called in the destructor of any derived class that will be reference counted.
Definition at line 173 of file reference_counter.h.
References libMesh::ReferenceCounter::_counts, libMesh::Quality::name(), and libMesh::Threads::spin_mtx.
Referenced by libMesh::ReferenceCounter::n_objects(), and libMesh::ReferenceCountedObject< RBParametrized >::~ReferenceCountedObject().
 {
   Threads::spin_mutex::scoped_lock lock(Threads::spin_mtx);
   std::pair<unsigned int, unsigned int> & p = _counts[name];
   p.second++;
 }
void libMesh::RBEIMAssembly::initialize_fe () private
Initialize the FE object.
virtual void libMesh::ElemAssembly::interior_assembly (FEMContext &) inline virtual inherited
Perform the element interior assembly.
Definition at line 55 of file elem_assembly.h.
 { }
static unsigned int libMesh::ReferenceCounter::n_objects () inline static inherited
Prints the number of outstanding (created, but not yet destroyed) objects.
Definition at line 76 of file reference_counter.h.
References libMesh::ReferenceCounter::_n_objects, libMesh::ReferenceCounter::disable_print_counter_info(), libMesh::ReferenceCounter::enable_print_counter_info(), libMesh::ReferenceCounter::increment_constructor_count(), libMesh::ReferenceCounter::increment_destructor_count(), and libMesh::Quality::name().
Referenced by libMesh::System::hide_output(), and libMesh::LibMeshInit::LibMeshInit().
   { return _n_objects; }
void libMesh::ReferenceCounter::print_info (std::ostream & out = libMesh::out) static inherited
Prints the reference information, by default to libMesh::out.
Definition at line 88 of file reference_counter.C.
References libMesh::ReferenceCounter::_enable_print_counter, and libMesh::ReferenceCounter::get_info().
Referenced by libMesh::LibMeshInit::LibMeshInit().
 {
   if( _enable_print_counter ) out_stream << ReferenceCounter::get_info();
 }
Member Data Documentation
unsigned int libMesh::RBEIMAssembly::_basis_function_index private
The EIM basis function index (from rb_eim_eval) for this assembly object.
Definition at line 101 of file rb_eim_assembly.h.
ReferenceCounter::Counts libMesh::ReferenceCounter::_counts static protected inherited
Actually holds the data.
Definition at line 115 of file reference_counter.h.
Referenced by libMesh::ReferenceCounter::get_info(), libMesh::ReferenceCounter::increment_constructor_count(), and libMesh::ReferenceCounter::increment_destructor_count().
bool libMesh::ReferenceCounter::_enable_print_counter = true static protected inherited
Flag to control whether reference count information is printed when print_info is called.
Definition at line 134 of file reference_counter.h.
Referenced by libMesh::ReferenceCounter::disable_print_counter_info(), libMesh::ReferenceCounter::enable_print_counter_info(), and libMesh::ReferenceCounter::print_info().
UniquePtr<FEBase> libMesh::RBEIMAssembly::_fe private
We store an FE object and an associated quadrature rule.
Definition at line 113 of file rb_eim_assembly.h.
UniquePtr<NumericVector<Number> > libMesh::RBEIMAssembly::_ghosted_basis_function private
The basis function that we sample to evaluate the empirical interpolation approximation. This will be a GHOSTED vector to facilitate interpolation in the case of multiple processors.
Definition at line 108 of file rb_eim_assembly.h.
Threads::spin_mutex libMesh::ReferenceCounter::_mutex static protected inherited
Mutual exclusion object to enable thread-safe reference counting.
Definition at line 128 of file reference_counter.h.
Threads::atomic< unsigned int > libMesh::ReferenceCounter::_n_objects static protected inherited
The number of objects. Print the reference count information when the number returns to 0.
Definition at line 123 of file reference_counter.h.
Referenced by libMesh::ReferenceCounter::n_objects(), libMesh::ReferenceCounter::ReferenceCounter(), and libMesh::ReferenceCounter::~ReferenceCounter().
UniquePtr<QBase> libMesh::RBEIMAssembly::_qrule private
Definition at line 114 of file rb_eim_assembly.h.
RBEIMConstruction& libMesh::RBEIMAssembly::_rb_eim_con private
The RBEIMConstruction object that this RBEIMAssembly is based on.
Definition at line 96 of file rb_eim_assembly.h.
The documentation for this class was generated from the following file:
rb_eim_assembly.h