libMesh: libMesh::DenseSubVector< T > Class Template Reference
SomeWebsiteLogo
libMesh::DenseSubVector< T > Class Template Reference
#include <dense_subvector.h>
Public Member Functions
DenseSubVector (DenseVector< T > &new_parent, const unsigned int ioff=0, const unsigned int n=0)
virtual ~DenseSubVector ()
DenseVector< T > & parent ()
virtual void zero () libmesh_override
const T & operator() (const unsigned int i) const
T & operator() (const unsigned int i)
virtual T el (const unsigned int i) const libmesh_override
virtual T & el (const unsigned int i) libmesh_override
virtual unsigned int size () const libmesh_override
virtual bool empty () const libmesh_override
unsigned int i_off () const
void reposition (const unsigned int ioff, const unsigned int n)
Real min () const
Real max () const
Real l1_norm () const
Real l2_norm () const
Real linfty_norm () const
void print (std::ostream &os) const
void print_scientific (std::ostream &os, unsigned precision=8) const
Private Attributes
DenseVector< T > & _parent_vector
unsigned int _n
unsigned int _i_off
Detailed Description
template<typename T>
class libMesh::DenseSubVector< T >
Defines a dense subvector for use in finite element computations. Useful for storing element load vectors before summation into a global vector, particularly when you have systems of equations. All overridden virtual functions are documented in dense_vector_base.h.
Author
Benjamin S. Kirk
Date
2003
Definition at line 42 of file dense_subvector.h.
Constructor & Destructor Documentation
template<typename T > libMesh::DenseSubVector< T >::DenseSubVector (DenseVector< T > & new_parent, const unsigned int ioff = 0, const unsigned int n = 0) inline
Constructor. Creates a dense subvector of the vector parent. The subvector has dimensions , and the entry of the subvector is located at the location in the parent vector.
Definition at line 156 of file dense_subvector.h.
References libMesh::DenseSubVector< T >::reposition().
                                                         :
   _parent_vector(new_parent)
 {
   reposition (ioff, n);
 }
template<typename T> virtual libMesh::DenseSubVector< T >::~DenseSubVector () inline virtual
Destructor. Does nothing.
Definition at line 58 of file dense_subvector.h.
 {}
Member Function Documentation
template<typename T> virtual T libMesh::DenseSubVector< T >::el (const unsigned int i) const inline virtual
Returns
The (i) element of the vector.
Implements libMesh::DenseVectorBase< T >.
Definition at line 78 of file dense_subvector.h.
   { return (*this)(i); }
template<typename T> virtual T& libMesh::DenseSubVector< T >::el (const unsigned int i) inline virtual
Returns
The (i) element of the vector as a writable reference.
Implements libMesh::DenseVectorBase< T >.
Definition at line 81 of file dense_subvector.h.
   { return (*this)(i); }
template<typename T> virtual bool libMesh::DenseSubVector< T >::empty () const inline virtual
Returns
true iff size() is 0.
Reimplemented from libMesh::DenseVectorBase< T >.
Definition at line 87 of file dense_subvector.h.
References libMesh::DenseSubVector< T >::_n.
Referenced by libMesh::NumericVector< T >::insert().
   { return (_n == 0); }
template<typename T> unsigned int libMesh::DenseSubVector< T >::i_off () const inline
Returns
The row offset into the parent vector.
Definition at line 93 of file dense_subvector.h.
References libMesh::DenseSubVector< T >::_i_off, libMesh::DenseSubVector< T >::l1_norm(), libMesh::DenseSubVector< T >::l2_norm(), libMesh::DenseSubVector< T >::linfty_norm(), libMesh::DenseSubVector< T >::max(), libMesh::DenseSubVector< T >::min(), libMesh::Real, and libMesh::DenseSubVector< T >::reposition().
Referenced by libMesh::DenseSubVector< T >::l1_norm(), libMesh::DenseSubVector< T >::l2_norm(), libMesh::DenseSubVector< T >::linfty_norm(), libMesh::DenseSubVector< T >::max(), libMesh::DenseSubVector< T >::min(), libMesh::DenseSubVector< T >::operator()(), libMesh::DenseSubVector< T >::reposition(), and libMesh::DenseSubVector< T >::zero().
 { return _i_off; }
template<typename T > Real libMesh::DenseSubVector< T >::l1_norm () const inline
Returns
The -norm of the vector, i.e. the sum of the absolute values of the entries.
Definition at line 247 of file dense_subvector.h.
References libMesh::DenseSubVector< T >::_parent_vector, std::abs(), libMesh::DenseSubVector< T >::i_off(), libMesh::Real, and libMesh::DenseSubVector< T >::size().
Referenced by libMesh::DenseSubVector< T >::i_off().
 {
   Real my_norm = 0.;
   for (unsigned int i=0; i!=this->size(); i++)
     {
       my_norm += std::abs(_parent_vector (i + this->i_off()));
     }
   return my_norm;
 }
template<typename T > Real libMesh::DenseSubVector< T >::l2_norm () const inline
Returns
The -norm of the vector, i.e. the square root of the sum of the squares of the entries.
Definition at line 261 of file dense_subvector.h.
References libMesh::DenseSubVector< T >::_parent_vector, libMesh::DenseSubVector< T >::i_off(), libMesh::TensorTools::norm_sq(), libMesh::Real, and libMesh::DenseSubVector< T >::size().
Referenced by libMesh::DenseSubVector< T >::i_off().
 {
   Real my_norm = 0.;
   for (unsigned int i=0; i!=this->size(); i++)
     {
       my_norm += TensorTools::norm_sq(_parent_vector (i + this->i_off()));
     }
   return sqrt(my_norm);
 }
template<typename T > Real libMesh::DenseSubVector< T >::linfty_norm () const inline
Returns
The -norm of the vector, i.e. the maximum absolute value of the entries.
Definition at line 275 of file dense_subvector.h.
References libMesh::DenseSubVector< T >::_parent_vector, libMesh::DenseSubVector< T >::i_off(), libMesh::TensorTools::norm_sq(), libMesh::Real, and libMesh::DenseSubVector< T >::size().
Referenced by libMesh::DenseSubVector< T >::i_off().
 {
   if (!this->size())
     return 0.;
   Real my_norm = TensorTools::norm_sq(_parent_vector (this->i_off()));
   for (unsigned int i=1; i!=this->size(); i++)
     {
       Real current = TensorTools::norm_sq(_parent_vector (i + this->i_off()));
       my_norm = (my_norm > current? my_norm : current);
     }
   return sqrt(my_norm);
 }
template<typename T > Real libMesh::DenseSubVector< T >::max () const inline
Returns
The maximum element in the vector, or the maximum real part in the case of complex numbers.
Definition at line 230 of file dense_subvector.h.
References libMesh::DenseSubVector< T >::_parent_vector, libMesh::DenseSubVector< T >::i_off(), libMesh::libmesh_assert(), libMesh::libmesh_real(), libMesh::Real, and libMesh::DenseSubVector< T >::size().
Referenced by libMesh::DenseSubVector< T >::i_off().
 {
   libmesh_assert (this->size());
   Real my_max = libmesh_real(_parent_vector (this->i_off()));
   for (unsigned int i=1; i!=this->size(); i++)
     {
       Real current = libmesh_real(_parent_vector (i + this->i_off()));
       my_max = (my_max > current? my_max : current);
     }
   return my_max;
 }
template<typename T > Real libMesh::DenseSubVector< T >::min () const inline
Returns
The minimum element in the vector, or the minimum real part in the case of complex numbers.
Definition at line 213 of file dense_subvector.h.
References libMesh::DenseSubVector< T >::_parent_vector, libMesh::DenseSubVector< T >::i_off(), libMesh::libmesh_assert(), libMesh::libmesh_real(), libMesh::Real, and libMesh::DenseSubVector< T >::size().
Referenced by libMesh::DenseSubVector< T >::i_off().
 {
   libmesh_assert (this->size());
   Real my_min = libmesh_real(_parent_vector (this->i_off()));
   for (unsigned int i=1; i!=this->size(); i++)
     {
       Real current = libmesh_real(_parent_vector (i + this->i_off()));
       my_min = (my_min < current? my_min : current);
     }
   return my_min;
 }
template<typename T > const T & libMesh::DenseSubVector< T >::operator() (const unsigned int i) const inline
Returns
The (i,j) element of the subvector as a const reference.
Definition at line 192 of file dense_subvector.h.
References libMesh::DenseSubVector< T >::_parent_vector, libMesh::DenseSubVector< T >::i_off(), and libMesh::DenseSubVector< T >::size().
Referenced by libMesh::DenseSubVector< T >::parent().
 {
   libmesh_assert_less (i, this->size());
   libmesh_assert_less (i + this->i_off(), _parent_vector.size());
   return _parent_vector (i + this->i_off());
 }
template<typename T > T & libMesh::DenseSubVector< T >::operator() (const unsigned int i) inline
Returns
The (i,j) element of the subvector as a writable reference.
Definition at line 203 of file dense_subvector.h.
References libMesh::DenseSubVector< T >::_parent_vector, libMesh::DenseSubVector< T >::i_off(), and libMesh::DenseSubVector< T >::size().
 {
   libmesh_assert_less (i, this->size());
   libmesh_assert_less (i + this->i_off(), _parent_vector.size());
   return _parent_vector (i + this->i_off());
 }
template<typename T> DenseVector<T>& libMesh::DenseSubVector< T >::parent () inline
Returns
A reference to the parent vector.
Definition at line 63 of file dense_subvector.h.
References libMesh::DenseSubVector< T >::_parent_vector, libMesh::DenseSubVector< T >::operator()(), and libMesh::DenseSubVector< T >::zero().
Referenced by libMesh::DenseSubMatrix< T >::condense().
 { return _parent_vector; }
template<typename T > void libMesh::DenseVectorBase< T >::print (std::ostream & os) const inherited
Pretty-print the vector to stdout.
Definition at line 62 of file dense_vector_base.C.
Referenced by libMesh::DenseVectorBase< T >::empty().
 {
   for (unsigned int i=0; i<this->size(); i++)
     os << std::setw(8)
        << this->el(i)
        << std::endl;
 }
template<typename T > void libMesh::DenseVectorBase< T >::print_scientific (std::ostream & os, unsigned precision = 8) const inherited
Prints the entries of the vector with additional decimal places in scientific notation.
Definition at line 30 of file dense_vector_base.C.
 {
 #ifndef LIBMESH_BROKEN_IOSTREAM
   // save the initial format flags
   std::ios_base::fmtflags os_flags = os.flags();
   // Print the vector entries.
   for (unsigned int i=0; i<this->size(); i++)
     os << std::setw(10)
        << std::scientific
        << std::setprecision(precision)
        << this->el(i)
        << std::endl;
   // reset the original format flags
   os.flags(os_flags);
 #else
   // Print the matrix entries.
   for (unsigned int i=0; i<this->size(); i++)
     os << std::setprecision(precision)
        << this->el(i)
        << std::endl;
 #endif
 }
template<typename T > void libMesh::DenseSubVector< T >::reposition (const unsigned int ioff, const unsigned int n) inline
Changes the location of the subvector in the parent vector.
Definition at line 168 of file dense_subvector.h.
References libMesh::DenseSubVector< T >::_i_off, libMesh::DenseSubVector< T >::_n, libMesh::DenseSubVector< T >::_parent_vector, libMesh::DenseSubVector< T >::i_off(), and libMesh::DenseSubVector< T >::size().
Referenced by libMesh::DenseSubVector< T >::DenseSubVector(), and libMesh::DenseSubVector< T >::i_off().
 {
   _i_off = ioff;
   _n = n;
   // Make sure we still fit in the parent vector.
   libmesh_assert_less_equal ((this->i_off() + this->size()), _parent_vector.size());
 }
template<typename T> virtual unsigned int libMesh::DenseSubVector< T >::size () const inline virtual
Returns
The size of the vector.
Implements libMesh::DenseVectorBase< T >.
Definition at line 84 of file dense_subvector.h.
References libMesh::DenseSubVector< T >::_n.
Referenced by libMesh::NumericVector< T >::insert(), libMesh::DenseSubVector< T >::l1_norm(), libMesh::DenseSubVector< T >::l2_norm(), libMesh::DenseSubVector< T >::linfty_norm(), libMesh::DenseSubVector< T >::max(), libMesh::DenseSubVector< T >::min(), libMesh::DenseSubVector< T >::operator()(), libMesh::DenseSubVector< T >::reposition(), and libMesh::DenseSubVector< T >::zero().
   { return _n; }
template<typename T > void libMesh::DenseSubVector< T >::zero () inline virtual
Set every element in the vector to 0. Needs to be pure virtual since the storage method may be different in derived classes.
Implements libMesh::DenseVectorBase< T >.
Definition at line 182 of file dense_subvector.h.
References libMesh::DenseSubVector< T >::_parent_vector, libMesh::DenseSubVector< T >::i_off(), and libMesh::DenseSubVector< T >::size().
Referenced by libMesh::DenseSubVector< T >::parent().
 {
   for (unsigned int i=0; i<this->size(); i++)
     _parent_vector (i + this->i_off()) = 0.;
 }
Member Data Documentation
template<typename T> unsigned int libMesh::DenseSubVector< T >::_i_off private
The offset into the parent vector.
Definition at line 147 of file dense_subvector.h.
Referenced by libMesh::DenseSubVector< T >::i_off(), and libMesh::DenseSubVector< T >::reposition().
template<typename T> unsigned int libMesh::DenseSubVector< T >::_n private
The length of this subvector.
Definition at line 142 of file dense_subvector.h.
Referenced by libMesh::DenseSubVector< T >::empty(), libMesh::DenseSubVector< T >::reposition(), and libMesh::DenseSubVector< T >::size().
template<typename T> DenseVector<T>& libMesh::DenseSubVector< T >::_parent_vector private
The parent vector that contains this subvector.
Definition at line 137 of file dense_subvector.h.
Referenced by libMesh::DenseSubVector< T >::l1_norm(), libMesh::DenseSubVector< T >::l2_norm(), libMesh::DenseSubVector< T >::linfty_norm(), libMesh::DenseSubVector< T >::max(), libMesh::DenseSubVector< T >::min(), libMesh::DenseSubVector< T >::operator()(), libMesh::DenseSubVector< T >::parent(), libMesh::DenseSubVector< T >::reposition(), and libMesh::DenseSubVector< T >::zero().
The documentation for this class was generated from the following file:
dense_subvector.h