libMesh: libMesh::PetscVector< T > Class Template Reference
SomeWebsiteLogo
libMesh::PetscVector< T > Class Template Reference
NumericVector interface to PETSc Vec.
#include <petsc_vector.h>
Public Member Functions
PetscVector (const Parallel::Communicator &comm_in, const ParallelType type=AUTOMATIC)
PetscVector (const Parallel::Communicator &comm_in, const numeric_index_type n, const ParallelType type=AUTOMATIC)
PetscVector (const Parallel::Communicator &comm_in, const numeric_index_type n, const numeric_index_type n_local, const ParallelType type=AUTOMATIC)
PetscVector (const Parallel::Communicator &comm_in, const numeric_index_type N, const numeric_index_type n_local, const std::vector< numeric_index_type > &ghost, const ParallelType type=AUTOMATIC)
PetscVector (Vec v, const Parallel::Communicator &comm_in LIBMESH_CAN_DEFAULT_TO_COMMWORLD)
~PetscVector ()
virtual void close () libmesh_override
virtual void clear () libmesh_override
virtual void zero () libmesh_override
virtual std::unique_ptr< NumericVector< T > > zero_clone () const libmesh_override
virtual std::unique_ptr< NumericVector< T > > clone () const libmesh_override
virtual void init (const numeric_index_type N, const numeric_index_type n_local, const bool fast=false, const ParallelType type=AUTOMATIC) libmesh_override
virtual void init (const numeric_index_type N, const bool fast=false, const ParallelType type=AUTOMATIC) libmesh_override
virtual void init (const numeric_index_type N, const numeric_index_type n_local, const std::vector< numeric_index_type > &ghost, const bool fast=false, const ParallelType=AUTOMATIC) libmesh_override
virtual void init (const NumericVector< T > &other, const bool fast=false) libmesh_override
virtual NumericVector< T > & operator= (const T s) libmesh_override
virtual NumericVector< T > & operator= (const NumericVector< T > &v) libmesh_override
virtual NumericVector< T > & operator= (const std::vector< T > &v) libmesh_override
PetscVector< T > & operator= (const PetscVector< T > &v)
virtual Real min () const libmesh_override
virtual Real max () const libmesh_override
virtual T sum () const libmesh_override
virtual Real l1_norm () const libmesh_override
virtual Real l2_norm () const libmesh_override
virtual Real linfty_norm () const libmesh_override
virtual numeric_index_type size () const libmesh_override
virtual numeric_index_type local_size () const libmesh_override
virtual numeric_index_type first_local_index () const libmesh_override
virtual numeric_index_type last_local_index () const libmesh_override
numeric_index_type map_global_to_local_index (const numeric_index_type i) const
virtual T operator() (const numeric_index_type i) const libmesh_override
virtual void get (const std::vector< numeric_index_type > &index, T *values) const libmesh_override
PetscScalar * get_array ()
const PetscScalar * get_array_read () const
void restore_array ()
virtual NumericVector< T > & operator+= (const NumericVector< T > &v) libmesh_override
virtual NumericVector< T > & operator-= (const NumericVector< T > &v) libmesh_override
virtual void reciprocal () libmesh_override
virtual void conjugate () libmesh_override
virtual void set (const numeric_index_type i, const T value) libmesh_override
virtual void add (const numeric_index_type i, const T value) libmesh_override
virtual void add (const T s) libmesh_override
virtual void add (const NumericVector< T > &v) libmesh_override
virtual void add (const T a, const NumericVector< T > &v) libmesh_override
virtual void add_vector (const T *v, const std::vector< numeric_index_type > &dof_indices) libmesh_override
virtual void add_vector (const NumericVector< T > &v, const SparseMatrix< T > &A) libmesh_override
virtual void add_vector_transpose (const NumericVector< T > &v, const SparseMatrix< T > &A) libmesh_override
void add_vector_conjugate_transpose (const NumericVector< T > &v, const SparseMatrix< T > &A)
virtual void insert (const T *v, const std::vector< numeric_index_type > &dof_indices) libmesh_override
virtual void scale (const T factor) libmesh_override
virtual NumericVector< T > & operator/= (NumericVector< T > &v) libmesh_override
virtual void abs () libmesh_override
virtual T dot (const NumericVector< T > &v) const libmesh_override
T indefinite_dot (const NumericVector< T > &v) const
virtual void localize (std::vector< T > &v_local) const libmesh_override
virtual void localize (NumericVector< T > &v_local) const libmesh_override
virtual void localize (NumericVector< T > &v_local, const std::vector< numeric_index_type > &send_list) const libmesh_override
virtual void localize (std::vector< T > &v_local, const std::vector< numeric_index_type > &indices) const libmesh_override
virtual void localize (const numeric_index_type first_local_idx, const numeric_index_type last_local_idx, const std::vector< numeric_index_type > &send_list) libmesh_override
virtual void localize_to_one (std::vector< T > &v_local, const processor_id_type proc_id=0) const libmesh_override
virtual void pointwise_mult (const NumericVector< T > &vec1, const NumericVector< T > &vec2) libmesh_override
virtual void print_matlab (const std::string &name="") const libmesh_override
virtual void create_subvector (NumericVector< T > &subvector, const std::vector< numeric_index_type > &rows) const libmesh_override
virtual void swap (NumericVector< T > &v) libmesh_override
Vec vec ()
template<>
void localize_to_one (std::vector< Real > &v_local, const processor_id_type pid) const
template<>
void localize_to_one (std::vector< Complex > &v_local, const processor_id_type pid) const
virtual bool initialized () const
ParallelType type () const
ParallelType & type ()
virtual bool closed () const
virtual Real subset_l1_norm (const std::set< numeric_index_type > &indices) const
virtual Real subset_l2_norm (const std::set< numeric_index_type > &indices) const
virtual Real subset_linfty_norm (const std::set< numeric_index_type > &indices) const
virtual T el (const numeric_index_type i) const
void get (const std::vector< numeric_index_type > &index, std::vector< T > &values) const
NumericVector< T > & operator*= (const T a)
NumericVector< T > & operator/= (const T a)
void add_vector (const std::vector< T > &v, const std::vector< numeric_index_type > &dof_indices)
virtual void add_vector (const NumericVector< T > &v, const std::vector< numeric_index_type > &dof_indices)
void add_vector (const DenseVector< T > &v, const std::vector< numeric_index_type > &dof_indices)
void add_vector (const NumericVector< T > &v, const ShellMatrix< T > &A)
void insert (const std::vector< T > &v, const std::vector< numeric_index_type > &dof_indices)
virtual void insert (const NumericVector< T > &v, const std::vector< numeric_index_type > &dof_indices)
void insert (const DenseVector< T > &v, const std::vector< numeric_index_type > &dof_indices)
void insert (const DenseSubVector< T > &v, const std::vector< numeric_index_type > &dof_indices)
virtual int compare (const NumericVector< T > &other_vector, const Real threshold=TOLERANCE) const
virtual int local_relative_compare (const NumericVector< T > &other_vector, const Real threshold=TOLERANCE) const
virtual int global_relative_compare (const NumericVector< T > &other_vector, const Real threshold=TOLERANCE) const
virtual void print (std::ostream &os=libMesh::out) const
template<>
void print (std::ostream &os) const
virtual void print_global (std::ostream &os=libMesh::out) const
template<>
void print_global (std::ostream &os) const
const Parallel::Communicator & comm () const
processor_id_type n_processors () const
processor_id_type processor_id () const
Static Public Member Functions
static std::unique_ptr< NumericVector< T > > build (const Parallel::Communicator &comm, const SolverPackage solver_package=libMesh::default_solver_package())
static std::unique_ptr< NumericVector< T > > build (const SolverPackage solver_package=libMesh::default_solver_package())
static std::string get_info ()
static void print_info (std::ostream &out=libMesh::out)
static unsigned int n_objects ()
static void enable_print_counter_info ()
static void disable_print_counter_info ()
Protected Types
typedef std::map< std::string, std::pair< unsigned int, unsigned int > > Counts
Protected Member Functions
void increment_constructor_count (const std::string &name)
void increment_destructor_count (const std::string &name)
Protected Attributes
bool _is_closed
bool _is_initialized
ParallelType _type
const Parallel::Communicator & _communicator
Static Protected Attributes
static Counts _counts
static Threads::atomic< unsigned int > _n_objects
static Threads::spin_mutex _mutex
static bool _enable_print_counter = true
Private Types
typedef std::unordered_map< numeric_index_type, numeric_index_type > GlobalToLocalMap
Private Member Functions
void _get_array (bool read_only) const
void _restore_array () const
Private Attributes
Vec _vec
std::atomic< bool > _array_is_present
bool _array_is_present
numeric_index_type _first
numeric_index_type _last
numeric_index_type _local_size
Vec _local_form
const PetscScalar * _read_only_values
PetscScalar * _values
std::mutex _petsc_vector_mutex
Threads::spin_mutex _petsc_vector_mutex
GlobalToLocalMap _global_to_local_map
bool _destroy_vec_on_exit
bool _values_manually_retrieved
bool _values_read_only
Detailed Description
template<typename T>
class libMesh::PetscVector< T >
NumericVector interface to PETSc Vec.
This class provides a nice interface to PETSc's Vec object. All overridden virtual functions are documented in numeric_vector.h.
Author
Benjamin S. Kirk
Date
2002
Definition at line 64 of file petsc_vector.h.
Member Typedef Documentation
typedef std::map<std::string, std::pair<unsigned int, unsigned int> > libMesh::ReferenceCounter::Counts protected inherited
Data structure to log the information. The log is identified by the class name.
Definition at line 119 of file reference_counter.h.
template<typename T> typedef std::unordered_map<numeric_index_type,numeric_index_type> libMesh::PetscVector< T >::GlobalToLocalMap private
Type for map that maps global to local ghost cells.
Definition at line 418 of file petsc_vector.h.
Constructor & Destructor Documentation
template<typename T > libMesh::PetscVector< T >::PetscVector (const Parallel::Communicator & comm_in, const ParallelType type = AUTOMATIC) inline explicit
Dummy-Constructor. Dimension=0
Definition at line 451 of file petsc_vector.h.
References libMesh::NumericVector< T >::_type.
Referenced by libMesh::PetscVector< T >::PetscVector().
                                                                                            :
   NumericVector<T>(comm_in, ptype),
   _array_is_present(false),
   _first(0),
   _last(0),
   _local_form(libmesh_nullptr),
   _values(libmesh_nullptr),
   _global_to_local_map(),
   _destroy_vec_on_exit(true),
   _values_manually_retrieved(false),
   _values_read_only(false)
 {
   this->_type = ptype;
 }
template<typename T > libMesh::PetscVector< T >::PetscVector (const Parallel::Communicator & comm_in, const numeric_index_type n, const ParallelType type = AUTOMATIC) inline explicit
Constructor. Set dimension to n and initialize all elements with zero.
Definition at line 470 of file petsc_vector.h.
References libMesh::PetscVector< T >::init().
                                                        :
   NumericVector<T>(comm_in, ptype),
   _array_is_present(false),
   _local_form(libmesh_nullptr),
   _values(libmesh_nullptr),
   _global_to_local_map(),
   _destroy_vec_on_exit(true),
   _values_manually_retrieved(false),
   _values_read_only(false)
 {
   this->init(n, n, false, ptype);
 }
template<typename T > libMesh::PetscVector< T >::PetscVector (const Parallel::Communicator & comm_in, const numeric_index_type n, const numeric_index_type n_local, const ParallelType type = AUTOMATIC) inline
Constructor. Set local dimension to n_local, the global dimension to n, and initialize all elements with zero.
Definition at line 489 of file petsc_vector.h.
References libMesh::PetscVector< T >::init().
                                                        :
   NumericVector<T>(comm_in, ptype),
   _array_is_present(false),
   _local_form(libmesh_nullptr),
   _values(libmesh_nullptr),
   _global_to_local_map(),
   _destroy_vec_on_exit(true),
   _values_manually_retrieved(false),
   _values_read_only(false)
 {
   this->init(n, n_local, false, ptype);
 }
template<typename T > libMesh::PetscVector< T >::PetscVector (const Parallel::Communicator & comm_in, const numeric_index_type N, const numeric_index_type n_local, const std::vector< numeric_index_type > & ghost, const ParallelType type = AUTOMATIC) inline
Constructor. Set local dimension to n_local, the global dimension to n, but additionally reserve memory for the indices specified by the ghost argument.
Definition at line 509 of file petsc_vector.h.
References libMesh::PetscVector< T >::_array_is_present, libMesh::PetscVector< T >::_destroy_vec_on_exit, libMesh::PetscVector< T >::_global_to_local_map, libMesh::NumericVector< T >::_is_closed, libMesh::NumericVector< T >::_is_initialized, libMesh::PetscVector< T >::_local_form, libMesh::NumericVector< T >::_type, libMesh::PetscVector< T >::_values, libMesh::PetscVector< T >::_values_manually_retrieved, libMesh::PetscVector< T >::_values_read_only, libMesh::PetscVector< T >::_vec, libMesh::AUTOMATIC, libMesh::GHOSTED, ierr, libMesh::PetscVector< T >::init(), libmesh_nullptr, libMesh::PARALLEL, libMesh::PetscVector< T >::PetscVector(), and libMesh::SERIAL.
                                                        :
   NumericVector<T>(comm_in, ptype),
   _array_is_present(false),
   _local_form(libmesh_nullptr),
   _values(libmesh_nullptr),
   _global_to_local_map(),
   _destroy_vec_on_exit(true),
   _values_manually_retrieved(false),
   _values_read_only(false)
 {
   this->init(n, n_local, ghost, false, ptype);
 }
template<typename T> libMesh::PetscVector< T >::PetscVector (Vec v, const Parallel::Communicator &comm_in LIBMESH_CAN_DEFAULT_TO_COMMWORLD)
Constructor. Creates a PetscVector assuming you already have a valid PETSc Vec object. In this case, v is NOT destroyed by the PetscVector constructor when this object goes out of scope. This allows ownership of v to remain with the original creator, and to simply provide additional functionality with the PetscVector.
template<typename T > libMesh::PetscVector< T >::~PetscVector () inline
Destructor, deallocates memory. Made virtual to allow for derived classes to behave properly.
Definition at line 616 of file petsc_vector.h.
References libMesh::PetscVector< T >::clear().
 {
   this->clear ();
 }
Member Function Documentation
template<typename T > void libMesh::PetscVector< T >::_get_array (bool read_only) const private
Queries the array (and the local form if the vector is ghosted) from PETSc.
Parameters
read_only Whether or not a read only copy of the raw data
Definition at line 1348 of file petsc_vector.C.
References libMesh::GHOSTED, ierr, and libMesh::initialized().
Referenced by libMesh::PetscVector< T >::get(), libMesh::PetscVector< T >::get_array(), libMesh::PetscVector< T >::get_array_read(), and libMesh::PetscVector< T >::operator()().
 {
   libmesh_assert (this->initialized());
 #ifdef LIBMESH_HAVE_CXX11_THREAD
   std::atomic_thread_fence(std::memory_order_acquire);
 #else
   Threads::spin_mutex::scoped_lock lock(_petsc_vector_mutex);
 #endif
   // If the values have already been retrieved and we're currently
   // trying to get a non-read only view (ie read/write) and the
   // values are currently read only... then we need to restore
   // the array first... and then retrieve it again.
   if (_array_is_present && !read_only && _values_read_only)
     _restore_array();
   // If we already have a read/write array - and we're trying
   // to get a read only array - let's just use the read write
   if (_array_is_present && read_only && !_values_read_only)
     _read_only_values = _values;
   if (!_array_is_present)
     {
 #ifdef LIBMESH_HAVE_CXX11_THREAD
       std::lock_guard<std::mutex> lock(_petsc_vector_mutex);
 #endif
       if (!_array_is_present)
         {
           PetscErrorCode ierr=0;
           if (this->type() != GHOSTED)
             {
 #if PETSC_VERSION_LESS_THAN(3,2,0)
               // Vec{Get,Restore}ArrayRead were introduced in PETSc 3.2.0.  If you
               // have an older PETSc than that, we'll do an ugly
               // const_cast and call VecGetArray() instead.
               ierr = VecGetArray(_vec, const_cast<PetscScalar **>(&_values));
               _values_read_only = false;
 #else
               if (read_only)
                 {
                   ierr = VecGetArrayRead(_vec, &_read_only_values);
                   _values_read_only = true;
                 }
               else
                 {
                   ierr = VecGetArray(_vec, &_values);
                   _values_read_only = false;
                 }
 #endif
               LIBMESH_CHKERR(ierr);
               _local_size = this->local_size();
             }
           else
             {
               ierr = VecGhostGetLocalForm (_vec,&_local_form);
               LIBMESH_CHKERR(ierr);
 #if PETSC_VERSION_LESS_THAN(3,2,0)
               // Vec{Get,Restore}ArrayRead were introduced in PETSc 3.2.0.  If you
               // have an older PETSc than that, we'll do an ugly
               // const_cast and call VecGetArray() instead.
               ierr = VecGetArray(_local_form, const_cast<PetscScalar **>(&_values));
               _values_read_only = false;
 #else
               if (read_only)
                 {
                   ierr = VecGetArrayRead(_local_form, &_read_only_values);
                   _values_read_only = true;
                 }
               else
                 {
                   ierr = VecGetArray(_local_form, &_values);
                   _values_read_only = false;
                 }
 #endif
               LIBMESH_CHKERR(ierr);
               PetscInt my_local_size = 0;
               ierr = VecGetLocalSize(_local_form, &my_local_size);
               LIBMESH_CHKERR(ierr);
               _local_size = static_cast<numeric_index_type>(my_local_size);
             }
           { // cache ownership range
             PetscInt petsc_first=0, petsc_last=0;
             ierr = VecGetOwnershipRange (_vec, &petsc_first, &petsc_last);
             LIBMESH_CHKERR(ierr);
             _first = static_cast<numeric_index_type>(petsc_first);
             _last = static_cast<numeric_index_type>(petsc_last);
           }
 #ifdef LIBMESH_HAVE_CXX11_THREAD
           std::atomic_thread_fence(std::memory_order_release);
           _array_is_present.store(true, std::memory_order_relaxed);
 #else
           _array_is_present = true;
 #endif
         }
     }
 }
template<typename T > void libMesh::PetscVector< T >::_restore_array () const private
Restores the array (and the local form if the vector is ghosted) to PETSc.
Definition at line 1452 of file petsc_vector.C.
References libMesh::GHOSTED, ierr, libMesh::initialized(), and libmesh_nullptr.
Referenced by libMesh::PetscVector< T >::add(), libMesh::PetscVector< T >::clear(), libMesh::PetscVector< T >::close(), libMesh::PetscVector< T >::create_subvector(), libMesh::PetscVector< T >::init(), libMesh::PetscVector< T >::max(), libMesh::PetscVector< T >::min(), libMesh::PetscVector< T >::operator=(), libMesh::PetscVector< T >::restore_array(), and libMesh::PetscVector< T >::zero().
 {
   if (_values_manually_retrieved)
     libmesh_error_msg("PetscVector values were manually retrieved but are being automatically restored!");
 #ifdef LIBMESH_HAVE_CXX11_THREAD
   std::atomic_thread_fence(std::memory_order_acquire);
 #else
   Threads::spin_mutex::scoped_lock lock(_petsc_vector_mutex);
 #endif
   libmesh_assert (this->initialized());
   if (_array_is_present)
     {
 #ifdef LIBMESH_HAVE_CXX11_THREAD
       std::lock_guard<std::mutex> lock(_petsc_vector_mutex);
 #endif
       if (_array_is_present)
         {
           PetscErrorCode ierr=0;
           if (this->type() != GHOSTED)
             {
 #if PETSC_VERSION_LESS_THAN(3,2,0)
               // Vec{Get,Restore}ArrayRead were introduced in PETSc 3.2.0.  If you
               // have an older PETSc than that, we'll do an ugly
               // const_cast and call VecRestoreArray() instead.
               ierr = VecRestoreArray (_vec, const_cast<PetscScalar **>(&_values));
 #else
               if (_values_read_only)
                 ierr = VecRestoreArrayRead (_vec, &_read_only_values);
               else
                 ierr = VecRestoreArray (_vec, &_values);
 #endif
               LIBMESH_CHKERR(ierr);
               _values = libmesh_nullptr;
             }
           else
             {
 #if PETSC_VERSION_LESS_THAN(3,2,0)
               // Vec{Get,Restore}ArrayRead were introduced in PETSc 3.2.0.  If you
               // have an older PETSc than that, we'll do an ugly
               // const_cast and call VecRestoreArray() instead.
               ierr = VecRestoreArray (_local_form, const_cast<PetscScalar **>(&_values));
 #else
               if (_values_read_only)
                 ierr = VecRestoreArrayRead (_local_form, &_read_only_values);
               else
                 ierr = VecRestoreArray (_local_form, &_values);
 #endif
               LIBMESH_CHKERR(ierr);
               _values = libmesh_nullptr;
               ierr = VecGhostRestoreLocalForm (_vec,&_local_form);
               LIBMESH_CHKERR(ierr);
               _local_form = libmesh_nullptr;
               _local_size = 0;
             }
 #ifdef LIBMESH_HAVE_CXX11_THREAD
           std::atomic_thread_fence(std::memory_order_release);
           _array_is_present.store(false, std::memory_order_relaxed);
 #else
           _array_is_present = false;
 #endif
         }
     }
 }
template<typename T > void libMesh::PetscVector< T >::abs () virtual
Sets for each entry in the vector.
Implements libMesh::NumericVector< T >.
Definition at line 439 of file petsc_vector.C.
References libMesh::GHOSTED, and ierr.
 {
   this->_restore_array();
   PetscErrorCode ierr = 0;
   if (this->type() != GHOSTED)
     {
       ierr = VecAbs(_vec);
       LIBMESH_CHKERR(ierr);
     }
   else
     {
       Vec loc_vec;
       ierr = VecGhostGetLocalForm (_vec,&loc_vec);
       LIBMESH_CHKERR(ierr);
       ierr = VecAbs(loc_vec);
       LIBMESH_CHKERR(ierr);
       ierr = VecGhostRestoreLocalForm (_vec,&loc_vec);
       LIBMESH_CHKERR(ierr);
     }
 }
template<typename T > void libMesh::PetscVector< T >::add (const numeric_index_type i, const T value) virtual
Adds value to each entry of the vector.
Implements libMesh::NumericVector< T >.
Definition at line 180 of file petsc_vector.C.
References ierr, and value.
 {
   this->_restore_array();
   libmesh_assert_less (i, size());
   PetscErrorCode ierr=0;
   PetscInt i_val = static_cast<PetscInt>(i);
   PetscScalar petsc_value = static_cast<PetscScalar>(value);
   ierr = VecSetValues (_vec, 1, &i_val, &petsc_value, ADD_VALUES);
   LIBMESH_CHKERR(ierr);
   this->_is_closed = false;
 }
template<typename T > void libMesh::PetscVector< T >::add (const T s) virtual
Adds s to each entry of the vector,
Implements libMesh::NumericVector< T >.
Definition at line 321 of file petsc_vector.C.
 {
   this->_get_array(false);
   for (numeric_index_type i=0; i<_local_size; i++)
     _values[i] += v_in;
 }
template<typename T > void libMesh::PetscVector< T >::add (const NumericVector< T > & v) virtual
Adds v to this, . Equivalent to calling operator+=().
Implements libMesh::NumericVector< T >.
Definition at line 332 of file petsc_vector.C.
 {
   this->add (1., v);
 }
template<typename T > void libMesh::PetscVector< T >::add (const T a, const NumericVector< T > & v) virtual
Vector addition with a scalar multiple, . Equivalent to calling operator+=().
Implements libMesh::NumericVector< T >.
Definition at line 340 of file petsc_vector.C.
References libMesh::PetscVector< T >::_restore_array(), libMesh::PetscVector< T >::_vec, libMesh::GHOSTED, ierr, and libMesh::PetscVector< T >::size().
 {
   this->_restore_array();
   PetscErrorCode ierr = 0;
   PetscScalar a = static_cast<PetscScalar>(a_in);
   // Make sure the NumericVector passed in is really a PetscVector
   const PetscVector<T> * v = cast_ptr<const PetscVector<T> *>(&v_in);
   v->_restore_array();
   libmesh_assert_equal_to (this->size(), v->size());
   if (this->type() != GHOSTED)
     {
       ierr = VecAXPY(_vec, a, v->_vec);
       LIBMESH_CHKERR(ierr);
     }
   else
     {
       Vec loc_vec;
       Vec v_loc_vec;
       ierr = VecGhostGetLocalForm (_vec,&loc_vec);
       LIBMESH_CHKERR(ierr);
       ierr = VecGhostGetLocalForm (v->_vec,&v_loc_vec);
       LIBMESH_CHKERR(ierr);
       ierr = VecAXPY(loc_vec, a, v_loc_vec);
       LIBMESH_CHKERR(ierr);
       ierr = VecGhostRestoreLocalForm (v->_vec,&v_loc_vec);
       LIBMESH_CHKERR(ierr);
       ierr = VecGhostRestoreLocalForm (_vec,&loc_vec);
       LIBMESH_CHKERR(ierr);
     }
 }
template<typename T > void libMesh::PetscVector< T >::add_vector (const T * v, const std::vector< numeric_index_type > & dof_indices) virtual
Computes , where v is a pointer and each dof_indices[i] specifies where to add value v[i]. This should be overridden in subclasses for efficiency.
Reimplemented from libMesh::NumericVector< T >.
Definition at line 198 of file petsc_vector.C.
References ierr.
 {
   // If we aren't adding anything just return
   if (dof_indices.empty())
     return;
   this->_restore_array();
   PetscErrorCode ierr=0;
   const PetscInt * i_val = reinterpret_cast<const PetscInt *>(&dof_indices[0]);
   const PetscScalar * petsc_value = static_cast<const PetscScalar *>(v);
   ierr = VecSetValues (_vec, cast_int<PetscInt>(dof_indices.size()),
                        i_val, petsc_value, ADD_VALUES);
   LIBMESH_CHKERR(ierr);
   this->_is_closed = false;
 }
template<typename T > void libMesh::PetscVector< T >::add_vector (const NumericVector< T > & v, const SparseMatrix< T > & A) virtual
Computes , i.e. adds the product of a SparseMatrix A and a NumericVector v to this.
Implements libMesh::NumericVector< T >.
Definition at line 221 of file petsc_vector.C.
References libMesh::PetscVector< T >::_vec, A, and ierr.
 {
   this->_restore_array();
   // Make sure the data passed in are really of Petsc types
   const PetscVector<T> * v = cast_ptr<const PetscVector<T> *>(&v_in);
   const PetscMatrix<T> * A = cast_ptr<const PetscMatrix<T> *>(&A_in);
   PetscErrorCode ierr=0;
   // We shouldn't close() the matrix for you, as that would potentially modify the state of a const object.
   if (!A->closed())
     {
       libmesh_warning("Matrix A must be assembled before calling PetscVector::add_vector(v, A).\n"
                       "Please update your code, as this warning will become an error in a future release.");
       libmesh_deprecated();
       const_cast<PetscMatrix<T> *>(A)->close();
     }
   // The const_cast<> is not elegant, but it is required since PETSc
   // expects a non-const Mat.
   ierr = MatMultAdd(const_cast<PetscMatrix<T> *>(A)->mat(), v->_vec, _vec, _vec);
   LIBMESH_CHKERR(ierr);
 }
template<typename T> void libMesh::NumericVector< T >::add_vector (const std::vector< T > & v, const std::vector< numeric_index_type > & dof_indices) inline inherited
Computes , where v is a std::vector and each dof_indices[i] specifies where to add value v[i].
Definition at line 840 of file numeric_vector.h.
References libMesh::NumericVector< T >::add_vector().
 {
   libmesh_assert(v.size() == dof_indices.size());
   if (!v.empty())
     this->add_vector(&v[0], dof_indices);
 }
template<typename T> void libMesh::NumericVector< T >::add_vector (const NumericVector< T > & v, const std::vector< numeric_index_type > & dof_indices) virtual inherited
Computes , where v is a NumericVector and each dof_indices[i] specifies where to add value v(i).
Definition at line 394 of file numeric_vector.C.
References libMesh::NumericVector< T >::size().
 {
   int n = dof_indices.size();
   libmesh_assert_equal_to(v.size(), static_cast<unsigned>(n));
   for (int i=0; i<n; i++)
     this->add (dof_indices[i], v(i));
 }
template<typename T> void libMesh::NumericVector< T >::add_vector (const DenseVector< T > & v, const std::vector< numeric_index_type > & dof_indices) inline inherited
Computes , where v is a DenseVector and each dof_indices[i] specifies where to add value v(i).
Definition at line 852 of file numeric_vector.h.
References libMesh::NumericVector< T >::add_vector(), libMesh::DenseVector< T >::empty(), and libMesh::DenseVector< T >::size().
 {
   libmesh_assert(v.size() == dof_indices.size());
   if (!v.empty())
     this->add_vector(&v(0), dof_indices);
 }
template<typename T> void libMesh::NumericVector< T >::add_vector (const NumericVector< T > & v, const ShellMatrix< T > & A) inherited
Computes , i.e. adds the product of a ShellMatrix A and a NumericVector v to this.
Definition at line 406 of file numeric_vector.C.
References libMesh::ShellMatrix< T >::vector_mult_add().
 {
   a.vector_mult_add(*this,v);
 }
template<typename T > void libMesh::PetscVector< T >::add_vector_conjugate_transpose (const NumericVector< T > & v, const SparseMatrix< T > & A)
.
Adds the product of the conjugate-transpose of SparseMatrix A and a NumericVector v to this.
Definition at line 277 of file petsc_vector.C.
References libMesh::PetscVector< T >::_vec, A, and ierr.
 {
   libmesh_error_msg("MatMultHermitianTranspose was introduced in PETSc 3.1.0," \
                     << "No one has made it backwards compatible with older " \
                     << "versions of PETSc so far.");
 }
template<typename T > void libMesh::PetscVector< T >::add_vector_transpose (const NumericVector< T > & v, const SparseMatrix< T > & A) virtual
Computes , i.e. adds the product of the transpose of a SparseMatrix A and a NumericVector v to this.
Implements libMesh::NumericVector< T >.
Definition at line 249 of file petsc_vector.C.
References libMesh::PetscVector< T >::_vec, A, and ierr.
 {
   this->_restore_array();
   // Make sure the data passed in are really of Petsc types
   const PetscVector<T> * v = cast_ptr<const PetscVector<T> *>(&v_in);
   const PetscMatrix<T> * A = cast_ptr<const PetscMatrix<T> *>(&A_in);
   PetscErrorCode ierr=0;
   // We shouldn't close() the matrix for you, as that would potentially modify the state of a const object.
   if (!A->closed())
     {
       libmesh_warning("Matrix A must be assembled before calling PetscVector::add_vector_transpose(v, A).\n"
                       "Please update your code, as this warning will become an error in a future release.");
       libmesh_deprecated();
       const_cast<PetscMatrix<T> *>(A)->close();
     }
   // The const_cast<> is not elegant, but it is required since PETSc
   // expects a non-const Mat.
   ierr = MatMultTransposeAdd(const_cast<PetscMatrix<T> *>(A)->mat(), v->_vec, _vec, _vec);
   LIBMESH_CHKERR(ierr);
 }
template<typename T > std::unique_ptr< NumericVector< T > > libMesh::NumericVector< T >::build (const Parallel::Communicator & comm, const SolverPackage solver_package = libMesh::default_solver_package()) static inherited
Builds a NumericVector on the processors in communicator comm using the linear solver package specified by solver_package
Definition at line 47 of file numeric_vector.C.
References libMesh::AUTOMATIC, libMesh::EIGEN_SOLVERS, libMesh::LASPACK_SOLVERS, libMesh::PETSC_SOLVERS, and libMesh::TRILINOS_SOLVERS.
Referenced by libMesh::ExactSolution::_compute_error(), libMesh::UniformRefinementEstimator::_estimate_error(), libMesh::System::add_vector(), libMesh::NumericVector< T >::build(), libMesh::EquationSystems::build_parallel_solution_vector(), libMesh::System::calculate_norm(), libMesh::AdjointRefinementEstimator::estimate_error(), libMesh::ExactErrorEstimator::estimate_error(), libMesh::CondensedEigenSystem::get_eigenpair(), libMesh::EquationSystems::get_solution(), and libMesh::System::project_vector().
 {
   // Build the appropriate vector
   switch (solver_package)
     {
 #ifdef LIBMESH_HAVE_LASPACK
     case LASPACK_SOLVERS:
       return libmesh_make_unique<LaspackVector<T>>(comm, AUTOMATIC);
 #endif
 #ifdef LIBMESH_HAVE_PETSC
     case PETSC_SOLVERS:
       return libmesh_make_unique<PetscVector<T>>(comm, AUTOMATIC);
 #endif
 #ifdef LIBMESH_TRILINOS_HAVE_EPETRA
     case TRILINOS_SOLVERS:
       return libmesh_make_unique<EpetraVector<T>>(comm, AUTOMATIC);
 #endif
 #ifdef LIBMESH_HAVE_EIGEN
     case EIGEN_SOLVERS:
       return libmesh_make_unique<EigenSparseVector<T>>(comm, AUTOMATIC);
 #endif
     default:
       return libmesh_make_unique<DistributedVector<T>>(comm, AUTOMATIC);
     }
 }
template<typename T > std::unique_ptr< NumericVector< T > > libMesh::NumericVector< T >::build (const SolverPackage solver_package = libMesh::default_solver_package()) static inherited
Builds a NumericVector on the processors in communicator CommWorld using the linear solver package specified by solver_package.
Deprecated:
LIBMESH_DISABLE_COMMWORLD is now the default, use the build() method that takes a Parallel::Communicator instead.
Definition at line 83 of file numeric_vector.C.
References libMesh::NumericVector< T >::build(), and libMesh::CommWorld.
 {
   libmesh_deprecated();
   return NumericVector<T>::build(CommWorld, solver_package);
 }
template<typename T > void libMesh::PetscVector< T >::clear () inline virtual
Restores the NumericVector<T> to a pristine state.
Reimplemented from libMesh::NumericVector< T >.
Definition at line 835 of file petsc_vector.h.
References libMesh::PetscVector< T >::_destroy_vec_on_exit, libMesh::PetscVector< T >::_global_to_local_map, libMesh::NumericVector< T >::_is_closed, libMesh::NumericVector< T >::_is_initialized, libMesh::PetscVector< T >::_restore_array(), libMesh::PetscVector< T >::_vec, ierr, and libMesh::NumericVector< T >::initialized().
Referenced by libMesh::PetscVector< T >::init(), and libMesh::PetscVector< T >::~PetscVector().
 {
   parallel_object_only();
   if (this->initialized())
     this->_restore_array();
   if ((this->initialized()) && (this->_destroy_vec_on_exit))
     {
       PetscErrorCode ierr=0;
       ierr = LibMeshVecDestroy(&_vec);
       LIBMESH_CHKERR(ierr);
     }
   this->_is_closed = this->_is_initialized = false;
   _global_to_local_map.clear();
 }
template<typename T > std::unique_ptr< NumericVector< T > > libMesh::PetscVector< T >::clone () const inline virtual
Returns
A copy of this vector wrapped in a smart pointer.
Note
This must be overridden in the derived classes.
Implements libMesh::NumericVector< T >.
Definition at line 907 of file petsc_vector.h.
References libMesh::ParallelObject::comm(), libMesh::NumericVector< T >::init(), and libMesh::NumericVector< T >::type().
 {
   NumericVector<T> * cloned_vector = new PetscVector<T>(this->comm(), this->type());
   cloned_vector->init(*this, true);
   *cloned_vector = *this;
   return std::unique_ptr<NumericVector<T>>(cloned_vector);
 }
template<typename T > void libMesh::PetscVector< T >::close () inline virtual
Calls the NumericVector's internal assembly routines, ensuring that the values are consistent across processors.
Implements libMesh::NumericVector< T >.
Definition at line 807 of file petsc_vector.h.
References libMesh::NumericVector< T >::_is_closed, libMesh::PetscVector< T >::_restore_array(), libMesh::PetscVector< T >::_vec, libMesh::GHOSTED, ierr, and libMesh::NumericVector< T >::type().
Referenced by libMesh::__libmesh_petsc_diff_solver_monitor(), libMesh::SlepcEigenSolver< T >::get_eigenpair(), libMesh::PetscVector< T >::localize(), and libMesh::PetscLinearSolver< T >::solve().
 {
   parallel_object_only();
   this->_restore_array();
   PetscErrorCode ierr=0;
   ierr = VecAssemblyBegin(_vec);
   LIBMESH_CHKERR(ierr);
   ierr = VecAssemblyEnd(_vec);
   LIBMESH_CHKERR(ierr);
   if (this->type() == GHOSTED)
     {
       ierr = VecGhostUpdateBegin(_vec,INSERT_VALUES,SCATTER_FORWARD);
       LIBMESH_CHKERR(ierr);
       ierr = VecGhostUpdateEnd(_vec,INSERT_VALUES,SCATTER_FORWARD);
       LIBMESH_CHKERR(ierr);
     }
   this->_is_closed = true;
 }
template<typename T> virtual bool libMesh::NumericVector< T >::closed () const inline virtual inherited
Returns
true if the vector is closed and ready for computation, false otherwise.
Definition at line 154 of file numeric_vector.h.
Referenced by libMesh::DofMap::enforce_adjoint_constraints_exactly(), libMesh::DofMap::enforce_constraints_exactly(), libMesh::DofMap::max_constraint_error(), libMesh::EigenSparseVector< T >::operator=(), libMesh::LaspackVector< T >::operator=(), libMesh::PetscVector< T >::operator=(), libMesh::EigenSparseVector< T >::zero(), libMesh::LaspackVector< T >::zero(), libMesh::EpetraVector< T >::zero(), and libMesh::PetscVector< T >::zero().
 { return _is_closed; }
const Parallel::Communicator& libMesh::ParallelObject::comm () const inline inherited
Returns
A reference to the Parallel::Communicator object used by this mesh.
Definition at line 87 of file parallel_object.h.
References libMesh::ParallelObject::_communicator.
Referenced by libMesh::__libmesh_petsc_diff_solver_jacobian(), libMesh::__libmesh_petsc_diff_solver_monitor(), libMesh::__libmesh_petsc_diff_solver_residual(), libMesh::__libmesh_petsc_snes_fd_residual(), libMesh::__libmesh_petsc_snes_jacobian(), libMesh::__libmesh_petsc_snes_mffd_residual(), libMesh::__libmesh_petsc_snes_postcheck(), libMesh::__libmesh_petsc_snes_residual(), libMesh::__libmesh_tao_equality_constraints(), libMesh::__libmesh_tao_equality_constraints_jacobian(), libMesh::__libmesh_tao_gradient(), libMesh::__libmesh_tao_hessian(), libMesh::__libmesh_tao_inequality_constraints(), libMesh::__libmesh_tao_inequality_constraints_jacobian(), libMesh::__libmesh_tao_objective(), libMesh::MeshRefinement::_coarsen_elements(), libMesh::ExactSolution::_compute_error(), libMesh::ParmetisPartitioner::_do_repartition(), libMesh::UniformRefinementEstimator::_estimate_error(), libMesh::BoundaryInfo::_find_id_maps(), libMesh::PetscLinearSolver< T >::_petsc_shell_matrix_get_diagonal(), libMesh::SlepcEigenSolver< T >::_petsc_shell_matrix_get_diagonal(), libMesh::PetscLinearSolver< T >::_petsc_shell_matrix_mult(), libMesh::SlepcEigenSolver< T >::_petsc_shell_matrix_mult(), libMesh::PetscLinearSolver< T >::_petsc_shell_matrix_mult_add(), libMesh::EquationSystems::_read_impl(), libMesh::MeshRefinement::_refine_elements(), libMesh::MeshRefinement::_smooth_flags(), libMesh::ImplicitSystem::add_matrix(), libMesh::System::add_vector(), libMesh::EigenSparseLinearSolver< T >::adjoint_solve(), libMesh::UnstructuredMesh::all_second_order(), libMesh::MeshTools::Modification::all_tri(), libMesh::LaplaceMeshSmoother::allgather_graph(), libMesh::FEMSystem::assemble_qoi(), libMesh::MeshCommunication::assign_global_indices(), libMesh::ParmetisPartitioner::assign_partitioning(), libMesh::DofMap::attach_matrix(), libMesh::Parallel::BinSorter< KeyType, IdxType >::binsort(), libMesh::Parallel::Sort< KeyType, IdxType >::binsort(), libMesh::MeshCommunication::broadcast(), libMesh::SparseMatrix< T >::build(), libMesh::MeshTools::Generation::build_extrusion(), libMesh::Parallel::Histogram< KeyType, IdxType >::build_histogram(), libMesh::PetscNonlinearSolver< T >::build_mat_null_space(), libMesh::BoundaryInfo::build_node_list_from_side_list(), libMesh::EquationSystems::build_parallel_solution_vector(), libMesh::MeshBase::cache_elem_dims(), libMesh::System::calculate_norm(), libMesh::DofMap::check_dirichlet_bcid_consistency(), libMesh::DistributedVector< T >::clone(), libMesh::EigenSparseVector< T >::clone(), libMesh::LaspackVector< T >::clone(), libMesh::EpetraVector< T >::clone(), libMesh::PetscVector< T >::clone(), libMesh::EpetraVector< T >::close(), libMesh::Parallel::Sort< KeyType, IdxType >::communicate_bins(), libMesh::Nemesis_IO_Helper::compute_num_global_elem_blocks(), libMesh::Nemesis_IO_Helper::compute_num_global_nodesets(), libMesh::Nemesis_IO_Helper::compute_num_global_sidesets(), libMesh::Problem_Interface::computeF(), libMesh::Problem_Interface::computeJacobian(), libMesh::Problem_Interface::computePreconditioner(), libMesh::ExodusII_IO::copy_elemental_solution(), libMesh::MeshTools::correct_node_proc_ids(), libMesh::MeshTools::create_bounding_box(), libMesh::MeshTools::create_nodal_bounding_box(), libMesh::MeshRefinement::create_parent_error_vector(), libMesh::MeshTools::create_processor_bounding_box(), libMesh::MeshTools::create_subdomain_bounding_box(), libMesh::MeshCommunication::delete_remote_elements(), libMesh::DofMap::distribute_dofs(), DMlibMeshFunction(), DMlibMeshJacobian(), DMlibMeshSetSystem_libMesh(), DMVariableBounds_libMesh(), libMesh::MeshRefinement::eliminate_unrefined_patches(), libMesh::EpetraVector< T >::EpetraVector(), libMesh::WeightedPatchRecoveryErrorEstimator::estimate_error(), libMesh::PatchRecoveryErrorEstimator::estimate_error(), libMesh::JumpErrorEstimator::estimate_error(), libMesh::AdjointRefinementEstimator::estimate_error(), libMesh::ExactErrorEstimator::estimate_error(), libMesh::MeshRefinement::flag_elements_by_elem_fraction(), libMesh::MeshRefinement::flag_elements_by_error_fraction(), libMesh::MeshRefinement::flag_elements_by_nelem_target(), libMesh::MeshCommunication::gather(), libMesh::MeshCommunication::gather_neighboring_elements(), libMesh::CondensedEigenSystem::get_eigenpair(), libMesh::DofMap::get_info(), libMesh::ImplicitSystem::get_linear_solver(), libMesh::EquationSystems::get_solution(), libMesh::LocationMap< T >::init(), libMesh::TopologyMap::init(), libMesh::TimeSolver::init(), libMesh::TaoOptimizationSolver< T >::init(), libMesh::PetscNonlinearSolver< T >::init(), libMesh::DistributedVector< T >::init(), libMesh::EpetraVector< T >::init(), libMesh::PetscVector< T >::init(), libMesh::SystemSubsetBySubdomain::init(), libMesh::EigenSystem::init_data(), libMesh::EigenSystem::init_matrices(), libMesh::ParmetisPartitioner::initialize(), libMesh::OptimizationSystem::initialize_equality_constraints_storage(), libMesh::OptimizationSystem::initialize_inequality_constraints_storage(), libMesh::MeshTools::libmesh_assert_parallel_consistent_procids< Elem >(), libMesh::MeshTools::libmesh_assert_parallel_consistent_procids< Node >(), libMesh::MeshTools::libmesh_assert_topology_consistent_procids< Node >(), libMesh::MeshTools::libmesh_assert_valid_boundary_ids(), libMesh::MeshTools::libmesh_assert_valid_dof_ids(), libMesh::MeshTools::libmesh_assert_valid_neighbors(), libMesh::DistributedMesh::libmesh_assert_valid_parallel_flags(), libMesh::DistributedMesh::libmesh_assert_valid_parallel_object_ids(), libMesh::DistributedMesh::libmesh_assert_valid_parallel_p_levels(), libMesh::MeshTools::libmesh_assert_valid_refinement_flags(), libMesh::MeshTools::libmesh_assert_valid_unique_ids(), libMesh::libmesh_petsc_snes_residual_helper(), libMesh::MeshRefinement::limit_level_mismatch_at_edge(), libMesh::MeshRefinement::limit_level_mismatch_at_node(), libMesh::MeshRefinement::limit_overrefined_boundary(), libMesh::MeshRefinement::limit_underrefined_boundary(), libMesh::MeshRefinement::make_coarsening_compatible(), libMesh::MeshCommunication::make_elems_parallel_consistent(), libMesh::MeshRefinement::make_flags_parallel_consistent(), libMesh::MeshCommunication::make_new_node_proc_ids_parallel_consistent(), libMesh::MeshCommunication::make_new_nodes_parallel_consistent(), libMesh::MeshCommunication::make_node_ids_parallel_consistent(), libMesh::MeshCommunication::make_node_proc_ids_parallel_consistent(), libMesh::MeshCommunication::make_node_unique_ids_parallel_consistent(), libMesh::MeshCommunication::make_nodes_parallel_consistent(), libMesh::MeshCommunication::make_p_levels_parallel_consistent(), libMesh::MeshRefinement::make_refinement_compatible(), libMesh::DistributedVector< T >::max(), libMesh::FEMSystem::mesh_position_set(), libMesh::MeshSerializer::MeshSerializer(), libMesh::DistributedVector< T >::min(), libMesh::DistributedMesh::n_active_elem(), libMesh::MeshTools::n_active_levels(), libMesh::BoundaryInfo::n_boundary_conds(), libMesh::BoundaryInfo::n_edge_conds(), libMesh::CondensedEigenSystem::n_global_non_condensed_dofs(), libMesh::MeshTools::n_levels(), libMesh::BoundaryInfo::n_nodeset_conds(), libMesh::MeshTools::n_p_levels(), libMesh::BoundaryInfo::n_shellface_conds(), libMesh::DistributedMesh::parallel_max_elem_id(), libMesh::DistributedMesh::parallel_max_node_id(), libMesh::ReplicatedMesh::parallel_max_unique_id(), libMesh::DistributedMesh::parallel_max_unique_id(), libMesh::DistributedMesh::parallel_n_elem(), libMesh::DistributedMesh::parallel_n_nodes(), libMesh::SparsityPattern::Build::parallel_sync(), libMesh::MeshTools::paranoid_n_levels(), libMesh::Partitioner::partition(), libMesh::LinearPartitioner::partition_range(), libMesh::MetisPartitioner::partition_range(), libMesh::Partitioner::partition_unpartitioned_elements(), libMesh::petsc_auto_fieldsplit(), libMesh::System::point_gradient(), libMesh::System::point_hessian(), libMesh::System::point_value(), libMesh::MeshBase::prepare_for_use(), libMesh::SparseMatrix< T >::print(), libMesh::Nemesis_IO::read(), libMesh::XdrIO::read(), libMesh::CheckpointIO::read_header(), libMesh::XdrIO::read_header(), libMesh::XdrIO::read_serialized_bc_names(), libMesh::XdrIO::read_serialized_bcs_helper(), libMesh::XdrIO::read_serialized_connectivity(), libMesh::XdrIO::read_serialized_nodes(), libMesh::XdrIO::read_serialized_nodesets(), libMesh::XdrIO::read_serialized_subdomain_names(), libMesh::MeshBase::recalculate_n_partitions(), libMesh::MeshCommunication::redistribute(), libMesh::MeshRefinement::refine_and_coarsen_elements(), libMesh::DistributedMesh::renumber_dof_objects(), libMesh::CheckpointIO::select_split_config(), libMesh::MeshCommunication::send_coarse_ghosts(), libMesh::Partitioner::set_node_processor_ids(), libMesh::DofMap::set_nonlocal_dof_objects(), libMesh::Partitioner::set_parent_processor_ids(), libMesh::PetscDiffSolver::setup_petsc_data(), libMesh::LaplaceMeshSmoother::smooth(), libMesh::Parallel::Sort< KeyType, IdxType >::sort(), libMesh::split_mesh(), libMesh::MeshBase::subdomain_ids(), libMesh::BoundaryInfo::sync(), libMesh::Parallel::sync_element_data_by_parent_id(), libMesh::Parallel::sync_node_data_by_element_id(), libMesh::MeshRefinement::test_level_one(), libMesh::MeshRefinement::test_unflagged(), libMesh::MeshTools::total_weight(), libMesh::MeshRefinement::uniformly_coarsen(), libMesh::NameBasedIO::write(), libMesh::XdrIO::write(), libMesh::XdrIO::write_serialized_bcs_helper(), libMesh::XdrIO::write_serialized_connectivity(), libMesh::XdrIO::write_serialized_nodes(), libMesh::XdrIO::write_serialized_nodesets(), libMesh::DistributedVector< T >::zero_clone(), libMesh::EigenSparseVector< T >::zero_clone(), libMesh::LaspackVector< T >::zero_clone(), libMesh::EpetraVector< T >::zero_clone(), and libMesh::PetscVector< T >::zero_clone().
   { return _communicator; }
template<typename T> int libMesh::NumericVector< T >::compare (const NumericVector< T > & other_vector, const Real threshold = TOLERANCE) const virtual inherited
Returns
-1 when this is equivalent to other_vector (up to the given threshold), or the first index where abs(a[i]-b[i]) exceeds the threshold.
Definition at line 116 of file numeric_vector.C.
References std::abs(), libMesh::NumericVector< T >::first_local_index(), libMesh::NumericVector< T >::initialized(), libMesh::initialized(), libMesh::NumericVector< T >::last_local_index(), and std::max().
Referenced by libMesh::NumericVector< Number >::operator/=().
 {
   libmesh_assert (this->initialized());
   libmesh_assert (other_vector.initialized());
   libmesh_assert_equal_to (this->first_local_index(), other_vector.first_local_index());
   libmesh_assert_equal_to (this->last_local_index(), other_vector.last_local_index());
   int first_different_i = std::numeric_limits<int>::max();
   numeric_index_type i = first_local_index();
   do
     {
       if (std::abs((*this)(i) - other_vector(i)) > threshold)
         first_different_i = i;
       else
         i++;
     }
   while (first_different_i==std::numeric_limits<int>::max()
          && i<last_local_index());
   // Find the correct first differing index in parallel
   this->comm().min(first_different_i);
   if (first_different_i == std::numeric_limits<int>::max())
     return -1;
   return first_different_i;
 }
template<typename T > void libMesh::PetscVector< T >::conjugate () virtual
Negates the imaginary component of each entry in the vector.
Implements libMesh::NumericVector< T >.
Definition at line 168 of file petsc_vector.C.
References ierr.
 {
   PetscErrorCode ierr = 0;
   // We just call the PETSc VecConjugate
   ierr = VecConjugate(_vec);
   LIBMESH_CHKERR(ierr);
 }
template<typename T > void libMesh::PetscVector< T >::create_subvector (NumericVector< T > & , const std::vector< numeric_index_type > &) const virtual
Fills in subvector from this vector using the indices in rows. Similar to the create_submatrix() routine for the SparseMatrix class, it is currently only implemented for PetscVectors.
Reimplemented from libMesh::NumericVector< T >.
Definition at line 1259 of file petsc_vector.C.
References libMesh::NumericVector< T >::_is_initialized, libMesh::PetscVector< T >::_restore_array(), libMesh::PetscVector< T >::_vec, libMesh::MeshTools::Generation::Private::idx(), ierr, libMesh::NumericVector< T >::initialized(), libMesh::Utility::iota(), libMesh::numeric_petsc_cast(), and PETSC_USE_POINTER.
 {
   this->_restore_array();
   // PETSc data structures
   IS parent_is, subvector_is;
   VecScatter scatter;
   PetscErrorCode ierr = 0;
   // Make sure the passed in subvector is really a PetscVector
   PetscVector<T> * petsc_subvector = cast_ptr<PetscVector<T> *>(&subvector);
   // If the petsc_subvector is already initialized, we assume that the
   // user has already allocated the *correct* amount of space for it.
   // If not, we use the appropriate PETSc routines to initialize it.
   if (!petsc_subvector->initialized())
     {
       // Initialize the petsc_subvector to have enough space to hold
       // the entries which will be scattered into it.  Note: such an
       // init() function (where we let PETSc decide the number of local
       // entries) is not currently offered by the PetscVector
       // class.  Should we differentiate here between sequential and
       // parallel vector creation based on this->n_processors() ?
       ierr = VecCreateMPI(this->comm().get(),
                           PETSC_DECIDE,                    // n_local
                           cast_int<PetscInt>(rows.size()), // n_global
                           &(petsc_subvector->_vec));
       LIBMESH_CHKERR(ierr);
       ierr = VecSetFromOptions (petsc_subvector->_vec);
       LIBMESH_CHKERR(ierr);
       // Mark the subvector as initialized
       petsc_subvector->_is_initialized = true;
     }
   else
     {
       petsc_subvector->_restore_array();
     }
   // Use iota to fill an array with entries [0,1,2,3,4,...rows.size()]
   std::vector<PetscInt> idx(rows.size());
   Utility::iota (idx.begin(), idx.end(), 0);
   // Construct index sets
   ierr = ISCreateLibMesh(this->comm().get(),
                          rows.size(),
                          numeric_petsc_cast(&rows[0]),
                          PETSC_USE_POINTER,
                          &parent_is);
   LIBMESH_CHKERR(ierr);
   ierr = ISCreateLibMesh(this->comm().get(),
                          rows.size(),
                          &idx[0],
                          PETSC_USE_POINTER,
                          &subvector_is);
   LIBMESH_CHKERR(ierr);
   // Construct the scatter object
   ierr = VecScatterCreate(this->_vec,
                           parent_is,
                           petsc_subvector->_vec,
                           subvector_is,
                           &scatter); LIBMESH_CHKERR(ierr);
   // Actually perform the scatter
   ierr = VecScatterBegin(scatter,
                          this->_vec,
                          petsc_subvector->_vec,
                          INSERT_VALUES,
                          SCATTER_FORWARD); LIBMESH_CHKERR(ierr);
   ierr = VecScatterEnd(scatter,
                        this->_vec,
                        petsc_subvector->_vec,
                        INSERT_VALUES,
                        SCATTER_FORWARD); LIBMESH_CHKERR(ierr);
   // Clean up
   ierr = LibMeshISDestroy(&parent_is);       LIBMESH_CHKERR(ierr);
   ierr = LibMeshISDestroy(&subvector_is);    LIBMESH_CHKERR(ierr);
   ierr = LibMeshVecScatterDestroy(&scatter); LIBMESH_CHKERR(ierr);
 }
void libMesh::ReferenceCounter::disable_print_counter_info () static inherited
Definition at line 107 of file reference_counter.C.
References libMesh::ReferenceCounter::_enable_print_counter.
Referenced by libMesh::LibMeshInit::LibMeshInit(), and libMesh::ReferenceCounter::n_objects().
 {
   _enable_print_counter = false;
   return;
 }
template<typename T > T libMesh::PetscVector< T >::dot (const NumericVector< T > & v) const virtual
Returns
, the dot product of (*this) with the vector v.
Uses the complex-conjugate of v in the complex-valued case.
Implements libMesh::NumericVector< T >.
Definition at line 465 of file petsc_vector.C.
References libMesh::PetscVector< T >::_vec, ierr, and value.
 {
   this->_restore_array();
   // Error flag
   PetscErrorCode ierr = 0;
   // Return value
   PetscScalar value=0.;
   // Make sure the NumericVector passed in is really a PetscVector
   const PetscVector<T> * v = cast_ptr<const PetscVector<T> *>(&v_in);
   // 2.3.x (at least) style.  Untested for previous versions.
   ierr = VecDot(this->_vec, v->_vec, &value);
   LIBMESH_CHKERR(ierr);
   return static_cast<T>(value);
 }
template<typename T> virtual T libMesh::NumericVector< T >::el (const numeric_index_type i) const inline virtual inherited
Returns
(*this)(i).
Definition at line 342 of file numeric_vector.h.
 { return (*this)(i); }
void libMesh::ReferenceCounter::enable_print_counter_info () static inherited
Methods to enable/disable the reference counter output from print_info()
Definition at line 101 of file reference_counter.C.
References libMesh::ReferenceCounter::_enable_print_counter.
Referenced by libMesh::ReferenceCounter::n_objects().
 {
   _enable_print_counter = true;
   return;
 }
template<typename T > numeric_index_type libMesh::PetscVector< T >::first_local_index () const inline virtual
Returns
The index of the first vector element actually stored on this processor.
Note
The minimum for this index is 0.
Implements libMesh::NumericVector< T >.
Definition at line 956 of file petsc_vector.h.
References libMesh::PetscVector< T >::_array_is_present, libMesh::PetscVector< T >::_first, libMesh::PetscVector< T >::_vec, ierr, and libMesh::NumericVector< T >::initialized().
 {
   libmesh_assert (this->initialized());
   numeric_index_type first = 0;
   if (_array_is_present) // Can we use cached values?
     first = _first;
   else
     {
       PetscErrorCode ierr=0;
       PetscInt petsc_first=0, petsc_last=0;
       ierr = VecGetOwnershipRange (_vec, &petsc_first, &petsc_last);
       LIBMESH_CHKERR(ierr);
       first = static_cast<numeric_index_type>(petsc_first);
     }
   return first;
 }
template<typename T > void libMesh::PetscVector< T >::get (const std::vector< numeric_index_type > & index, T * values) const inline virtual
Access multiple components at once. values will not be reallocated; it should already have enough space. The default implementation calls operator() for each index, but some implementations may supply faster methods here.
Reimplemented from libMesh::NumericVector< T >.
Definition at line 1084 of file petsc_vector.h.
References libMesh::PetscVector< T >::_get_array(), libMesh::PetscVector< T >::_local_size, libMesh::PetscVector< T >::_read_only_values, libMesh::GHOSTED, libMesh::PetscVector< T >::map_global_to_local_index(), and libMesh::NumericVector< T >::type().
 {
   this->_get_array(true);
   const std::size_t num = index.size();
   for (std::size_t i=0; i<num; i++)
     {
       const numeric_index_type local_index = this->map_global_to_local_index(index[i]);
 #ifndef NDEBUG
       if (this->type() == GHOSTED)
         {
           libmesh_assert_less (local_index, _local_size);
         }
 #endif
       values[i] = static_cast<T>(_read_only_values[local_index]);
     }
 }
template<typename T> void libMesh::NumericVector< T >::get (const std::vector< numeric_index_type > & index, std::vector< T > & values) const inline inherited
Access multiple components at once. values will be resized, if necessary, and filled. The default implementation calls operator() for each index, but some implementations may supply faster methods here.
Definition at line 825 of file numeric_vector.h.
 {
   const std::size_t num = index.size();
   values.resize(num);
   if (!num)
     return;
   this->get(index, &values[0]);
 }
template<typename T > PetscScalar * libMesh::PetscVector< T >::get_array () inline
Get read/write access to the raw PETSc Vector data array.
Note
This is an advanced interface. In general you should avoid using it unless you know what you are doing!
Definition at line 1107 of file petsc_vector.h.
References libMesh::PetscVector< T >::_get_array(), libMesh::PetscVector< T >::_values, and libMesh::PetscVector< T >::_values_manually_retrieved.
 {
   _values_manually_retrieved = true;
   _get_array(false);
   return _values;
 }
template<typename T > const PetscScalar * libMesh::PetscVector< T >::get_array_read () const inline
Get read only access to the raw PETSc Vector data array.
Note
This is an advanced interface. In general you should avoid using it unless you know what you are doing!
Definition at line 1118 of file petsc_vector.h.
References libMesh::PetscVector< T >::_get_array(), libMesh::PetscVector< T >::_read_only_values, and libMesh::PetscVector< T >::_values_manually_retrieved.
 {
   _values_manually_retrieved = true;
   _get_array(true);
   return _read_only_values;
 }
std::string libMesh::ReferenceCounter::get_info () static inherited
Gets a string containing the reference information.
Definition at line 47 of file reference_counter.C.
References libMesh::ReferenceCounter::_counts, and libMesh::Quality::name().
Referenced by libMesh::ReferenceCounter::print_info().
 {
 #if defined(LIBMESH_ENABLE_REFERENCE_COUNTING) && defined(DEBUG)
   std::ostringstream oss;
   oss << '\n'
       << " ---------------------------------------------------------------------------- \n"
       << "| Reference count information                                                |\n"
       << " ---------------------------------------------------------------------------- \n";
   for (Counts::iterator it = _counts.begin();
        it != _counts.end(); ++it)
     {
       const std::string name(it->first);
       const unsigned int creations    = it->second.first;
       const unsigned int destructions = it->second.second;
       oss << "| " << name << " reference count information:\n"
           << "|  Creations:    " << creations    << '\n'
           << "|  Destructions: " << destructions << '\n';
     }
   oss << " ---------------------------------------------------------------------------- \n";
   return oss.str();
 #else
   return "";
 #endif
 }
template<typename T> int libMesh::NumericVector< T >::global_relative_compare (const NumericVector< T > & other_vector, const Real threshold = TOLERANCE) const virtual inherited
Returns
-1 when this is equivalent to other_vector (up to the given global relative threshold), or the first index where abs(a[i]-b[i])/max_j(a[j],b[j]) exceeds the threshold.
Definition at line 181 of file numeric_vector.C.
References std::abs(), libMesh::NumericVector< T >::first_local_index(), libMesh::NumericVector< T >::initialized(), libMesh::initialized(), libMesh::NumericVector< T >::last_local_index(), libMesh::NumericVector< T >::linfty_norm(), std::max(), and libMesh::Real.
Referenced by libMesh::NumericVector< Number >::operator/=().
 {
   libmesh_assert (this->initialized());
   libmesh_assert (other_vector.initialized());
   libmesh_assert_equal_to (this->first_local_index(), other_vector.first_local_index());
   libmesh_assert_equal_to (this->last_local_index(), other_vector.last_local_index());
   int first_different_i = std::numeric_limits<int>::max();
   numeric_index_type i = first_local_index();
   const Real my_norm = this->linfty_norm();
   const Real other_norm = other_vector.linfty_norm();
   const Real abs_threshold = std::max(my_norm, other_norm) * threshold;
   do
     {
       if (std::abs((*this)(i) - other_vector(i) ) > abs_threshold)
         first_different_i = i;
       else
         i++;
     }
   while (first_different_i==std::numeric_limits<int>::max()
          && i<last_local_index());
   // Find the correct first differing index in parallel
   this->comm().min(first_different_i);
   if (first_different_i == std::numeric_limits<int>::max())
     return -1;
   return first_different_i;
 }
void libMesh::ReferenceCounter::increment_constructor_count (const std::string & name) inline protected inherited
Increments the construction counter. Should be called in the constructor of any derived class that will be reference counted.
Definition at line 185 of file reference_counter.h.
References libMesh::ReferenceCounter::_counts, libMesh::Quality::name(), and libMesh::Threads::spin_mtx.
Referenced by libMesh::ReferenceCounter::n_objects(), and libMesh::ReferenceCountedObject< RBParametrized >::ReferenceCountedObject().
 {
   Threads::spin_mutex::scoped_lock lock(Threads::spin_mtx);
   std::pair<unsigned int, unsigned int> & p = _counts[name];
   p.first++;
 }
void libMesh::ReferenceCounter::increment_destructor_count (const std::string & name) inline protected inherited
Increments the destruction counter. Should be called in the destructor of any derived class that will be reference counted.
Definition at line 198 of file reference_counter.h.
References libMesh::ReferenceCounter::_counts, libMesh::Quality::name(), and libMesh::Threads::spin_mtx.
Referenced by libMesh::ReferenceCounter::n_objects(), and libMesh::ReferenceCountedObject< RBParametrized >::~ReferenceCountedObject().
 {
   Threads::spin_mutex::scoped_lock lock(Threads::spin_mtx);
   std::pair<unsigned int, unsigned int> & p = _counts[name];
   p.second++;
 }
template<typename T > T libMesh::PetscVector< T >::indefinite_dot (const NumericVector< T > & v) const
Returns
The dot product of (*this) with the vector v.
Note
Does not use the complex-conjugate of v in the complex-valued case.
Definition at line 486 of file petsc_vector.C.
References libMesh::PetscVector< T >::_vec, ierr, and value.
 {
   this->_restore_array();
   // Error flag
   PetscErrorCode ierr = 0;
   // Return value
   PetscScalar value=0.;
   // Make sure the NumericVector passed in is really a PetscVector
   const PetscVector<T> * v = cast_ptr<const PetscVector<T> *>(&v_in);
   // 2.3.x (at least) style.  Untested for previous versions.
   ierr = VecTDot(this->_vec, v->_vec, &value);
   LIBMESH_CHKERR(ierr);
   return static_cast<T>(value);
 }
template<typename T > void libMesh::PetscVector< T >::init (const numeric_index_type , const numeric_index_type , const bool = false, const ParallelType = AUTOMATIC) inline virtual
Change the dimension of the vector to N. The reserved memory for this vector remains unchanged if possible. If N==0, all memory is freed. Therefore, if you want to resize the vector and release the memory not needed, you have to first call init(0) and then init(N). This behaviour is analogous to that of the STL containers.
On fast==false, the vector is filled by zeros.
Implements libMesh::NumericVector< T >.
Definition at line 625 of file petsc_vector.h.
References libMesh::NumericVector< T >::_is_closed, libMesh::NumericVector< T >::_is_initialized, libMesh::NumericVector< T >::_type, libMesh::PetscVector< T >::_vec, libMesh::AUTOMATIC, libMesh::PetscVector< T >::clear(), libMesh::ParallelObject::comm(), ierr, libMesh::NumericVector< T >::initialized(), libMesh::PARALLEL, libMesh::SERIAL, and libMesh::PetscVector< T >::zero().
Referenced by libMesh::PetscVector< T >::init(), libMesh::PetscVector< T >::localize(), and libMesh::PetscVector< T >::PetscVector().
 {
   parallel_object_only();
   PetscErrorCode ierr=0;
   PetscInt petsc_n=static_cast<PetscInt>(n);
   PetscInt petsc_n_local=static_cast<PetscInt>(n_local);
   // Clear initialized vectors
   if (this->initialized())
     this->clear();
   if (ptype == AUTOMATIC)
     {
       if (n == n_local)
         this->_type = SERIAL;
       else
         this->_type = PARALLEL;
     }
   else
     this->_type = ptype;
   libmesh_assert ((this->_type==SERIAL && n==n_local) ||
                   this->_type==PARALLEL);
   // create a sequential vector if on only 1 processor
   if (this->_type == SERIAL)
     {
       ierr = VecCreateSeq (PETSC_COMM_SELF, petsc_n, &_vec);
       CHKERRABORT(PETSC_COMM_SELF,ierr);
       ierr = VecSetFromOptions (_vec);
       CHKERRABORT(PETSC_COMM_SELF,ierr);
     }
   // otherwise create an MPI-enabled vector
   else if (this->_type == PARALLEL)
     {
 #ifdef LIBMESH_HAVE_MPI
       libmesh_assert_less_equal (n_local, n);
       ierr = VecCreateMPI (this->comm().get(), petsc_n_local, petsc_n,
                            &_vec);
       LIBMESH_CHKERR(ierr);
 #else
       libmesh_assert_equal_to (n_local, n);
       ierr = VecCreateSeq (PETSC_COMM_SELF, petsc_n, &_vec);
       CHKERRABORT(PETSC_COMM_SELF,ierr);
 #endif
       ierr = VecSetFromOptions (_vec);
       LIBMESH_CHKERR(ierr);
     }
   else
     libmesh_error_msg("Unsupported type " << this->_type);
   this->_is_initialized = true;
   this->_is_closed = true;
   if (fast == false)
     this->zero ();
 }
template<typename T > void libMesh::PetscVector< T >::init (const numeric_index_type , const bool = false, const ParallelType = AUTOMATIC) inline virtual
Call init() with n_local = N.
Implements libMesh::NumericVector< T >.
Definition at line 695 of file petsc_vector.h.
References libMesh::PetscVector< T >::_global_to_local_map, libMesh::NumericVector< T >::_is_closed, libMesh::NumericVector< T >::_is_initialized, libMesh::NumericVector< T >::_type, libMesh::PetscVector< T >::_vec, libMesh::AUTOMATIC, libMesh::PetscVector< T >::clear(), libMesh::ParallelObject::comm(), libMesh::GHOSTED, ierr, libMesh::PetscVector< T >::init(), libMesh::NumericVector< T >::initialized(), and libMesh::PetscVector< T >::zero().
 {
   this->init(n,n,fast,ptype);
 }
template<typename T> virtual void libMesh::PetscVector< T >::init (const numeric_index_type , const numeric_index_type , const std::vector< numeric_index_type > & , const bool = false, const ParallelType = AUTOMATIC) virtual
Create a vector that holds tha local indices plus those specified in the ghost argument.
Implements libMesh::NumericVector< T >.
template<typename T > void libMesh::PetscVector< T >::init (const NumericVector< T > & other, const bool fast = false) inline virtual
Creates a vector that has the same dimension and storage type as other, including ghost dofs.
Implements libMesh::NumericVector< T >.
Definition at line 768 of file petsc_vector.h.
References libMesh::PetscVector< T >::_global_to_local_map, libMesh::NumericVector< T >::_is_closed, libMesh::NumericVector< T >::_is_initialized, libMesh::PetscVector< T >::_restore_array(), libMesh::NumericVector< T >::_type, libMesh::PetscVector< T >::_vec, libMesh::PetscVector< T >::clear(), ierr, libMesh::NumericVector< T >::initialized(), and libMesh::PetscVector< T >::zero().
 {
   parallel_object_only();
   // Clear initialized vectors
   if (this->initialized())
     this->clear();
   const PetscVector<T> & v = cast_ref<const PetscVector<T> &>(other);
   // Other vector should restore array.
   if (v.initialized())
     {
       v._restore_array();
     }
   this->_global_to_local_map = v._global_to_local_map;
   // Even if we're initializing sizes based on an uninitialized or
   // unclosed vector, *this* vector is being initialized now and is
   // initially closed.
   this->_is_closed      = true; // v._is_closed;
   this->_is_initialized = true; // v._is_initialized;
   this->_type = v._type;
   // We want to have a valid Vec, even if it's initially of size zero
   PetscErrorCode ierr = VecDuplicate (v._vec, &this->_vec);
   LIBMESH_CHKERR(ierr);
   if (fast == false)
     this->zero ();
 }
template<typename T> virtual bool libMesh::NumericVector< T >::initialized () const inline virtual inherited
Returns
true if the vector has been initialized, false otherwise.
Definition at line 138 of file numeric_vector.h.
Referenced by libMesh::DistributedVector< T >::add(), libMesh::EigenSparseVector< T >::add(), libMesh::LaspackVector< T >::add(), libMesh::ImplicitSystem::assemble(), libMesh::LaspackVector< T >::clear(), libMesh::EpetraVector< T >::clear(), libMesh::PetscVector< T >::clear(), libMesh::DistributedVector< T >::close(), libMesh::EigenSparseVector< T >::close(), libMesh::LaspackVector< T >::close(), libMesh::EpetraVector< T >::close(), libMesh::NumericVector< T >::compare(), libMesh::PetscVector< T >::create_subvector(), libMesh::DistributedVector< T >::first_local_index(), libMesh::LaspackVector< T >::first_local_index(), libMesh::EigenSparseVector< T >::first_local_index(), libMesh::EpetraVector< T >::first_local_index(), libMesh::PetscVector< T >::first_local_index(), libMesh::NumericVector< T >::global_relative_compare(), libMesh::DistributedVector< T >::init(), libMesh::EigenSparseVector< T >::init(), libMesh::PetscVector< T >::init(), libMesh::DistributedVector< T >::last_local_index(), libMesh::EigenSparseVector< T >::last_local_index(), libMesh::LaspackVector< T >::last_local_index(), libMesh::EpetraVector< T >::last_local_index(), libMesh::PetscVector< T >::last_local_index(), libMesh::NumericVector< T >::local_relative_compare(), libMesh::DistributedVector< T >::local_size(), libMesh::LaspackVector< T >::local_size(), libMesh::EigenSparseVector< T >::local_size(), libMesh::EpetraVector< T >::local_size(), libMesh::PetscVector< T >::local_size(), libMesh::PetscVector< T >::map_global_to_local_index(), libMesh::DistributedVector< T >::max(), libMesh::EpetraVector< T >::max(), libMesh::DistributedVector< T >::min(), libMesh::EpetraVector< T >::min(), libMesh::DistributedVector< T >::operator()(), libMesh::EigenSparseVector< T >::operator()(), libMesh::LaspackVector< T >::operator()(), libMesh::EpetraVector< T >::operator()(), libMesh::NumericVector< T >::print(), libMesh::NumericVector< T >::print_global(), libMesh::DistributedVector< T >::set(), libMesh::LaspackVector< T >::set(), libMesh::EigenSparseVector< T >::set(), libMesh::DistributedVector< T >::size(), libMesh::LaspackVector< T >::size(), libMesh::EigenSparseVector< T >::size(), libMesh::EpetraVector< T >::size(), libMesh::PetscVector< T >::size(), libMesh::DistributedVector< T >::zero(), libMesh::LaspackVector< T >::zero(), libMesh::EigenSparseVector< T >::zero(), libMesh::EpetraVector< T >::zero(), and libMesh::LaspackVector< T >::~LaspackVector().
 { return _is_initialized; }
template<typename T > void libMesh::PetscVector< T >::insert (const T * v, const std::vector< numeric_index_type > & dof_indices) virtual
Inserts the entries of v in *this at the locations specified by v.
Reimplemented from libMesh::NumericVector< T >.
Definition at line 380 of file petsc_vector.C.
References ierr, and libMesh::numeric_petsc_cast().
 {
   if (dof_indices.empty())
     return;
   this->_restore_array();
   PetscErrorCode ierr=0;
   PetscInt * idx_values = numeric_petsc_cast(&dof_indices[0]);
   ierr = VecSetValues (_vec, dof_indices.size(), idx_values, v, INSERT_VALUES);
   LIBMESH_CHKERR(ierr);
   this->_is_closed = false;
 }
template<typename T> void libMesh::NumericVector< T >::insert (const std::vector< T > & v, const std::vector< numeric_index_type > & dof_indices) inline inherited
Inserts the entries of v in *this at the locations specified by v.
Definition at line 864 of file numeric_vector.h.
References libMesh::NumericVector< T >::insert().
 {
   libmesh_assert(v.size() == dof_indices.size());
   if (!v.empty())
     this->insert(&v[0], dof_indices);
 }
template<typename T> void libMesh::NumericVector< T >::insert (const NumericVector< T > & v, const std::vector< numeric_index_type > & dof_indices) virtual inherited
Inserts the entries of v in *this at the locations specified by v.
Definition at line 104 of file numeric_vector.C.
References libMesh::NumericVector< T >::size().
 {
   libmesh_assert_equal_to (V.size(), dof_indices.size());
   for (numeric_index_type i=0; i<dof_indices.size(); i++)
     this->set (dof_indices[i], V(i));
 }
template<typename T> void libMesh::NumericVector< T >::insert (const DenseVector< T > & v, const std::vector< numeric_index_type > & dof_indices) inline inherited
Inserts the entries of v in *this at the locations specified by v.
Definition at line 876 of file numeric_vector.h.
References libMesh::DenseVector< T >::empty(), libMesh::NumericVector< T >::insert(), and libMesh::DenseVector< T >::size().
 {
   libmesh_assert(v.size() == dof_indices.size());
   if (!v.empty())
     this->insert(&v(0), dof_indices);
 }
template<typename T> void libMesh::NumericVector< T >::insert (const DenseSubVector< T > & v, const std::vector< numeric_index_type > & dof_indices) inline inherited
Inserts the entries of v in *this at the locations specified by v.
Definition at line 888 of file numeric_vector.h.
References libMesh::DenseSubVector< T >::empty(), libMesh::NumericVector< T >::insert(), and libMesh::DenseSubVector< T >::size().
 {
   libmesh_assert(v.size() == dof_indices.size());
   if (!v.empty())
     this->insert(&v(0), dof_indices);
 }
template<typename T > Real libMesh::PetscVector< T >::l1_norm () const virtual
Returns
The -norm of the vector, i.e. the sum of the absolute values of the entries.
Implements libMesh::NumericVector< T >.
Definition at line 57 of file petsc_vector.C.
References libMesh::closed(), ierr, libMesh::Real, and value.
 {
   this->_restore_array();
   libmesh_assert(this->closed());
   PetscErrorCode ierr=0;
   PetscReal value=0.;
   ierr = VecNorm (_vec, NORM_1, &value);
   LIBMESH_CHKERR(ierr);
   return static_cast<Real>(value);
 }
template<typename T > Real libMesh::PetscVector< T >::l2_norm () const virtual
Returns
The -norm of the vector, i.e. the square root of the sum of the squares of the entries.
Implements libMesh::NumericVector< T >.
Definition at line 74 of file petsc_vector.C.
References libMesh::closed(), ierr, libMesh::Real, and value.
 {
   this->_restore_array();
   libmesh_assert(this->closed());
   PetscErrorCode ierr=0;
   PetscReal value=0.;
   ierr = VecNorm (_vec, NORM_2, &value);
   LIBMESH_CHKERR(ierr);
   return static_cast<Real>(value);
 }
template<typename T > numeric_index_type libMesh::PetscVector< T >::last_local_index () const inline virtual
Returns
The index+1 of the last vector element actually stored on this processor.
Note
The maximum for this index is size().
Implements libMesh::NumericVector< T >.
Definition at line 980 of file petsc_vector.h.
References libMesh::PetscVector< T >::_array_is_present, libMesh::PetscVector< T >::_last, libMesh::PetscVector< T >::_vec, ierr, and libMesh::NumericVector< T >::initialized().
 {
   libmesh_assert (this->initialized());
   numeric_index_type last = 0;
   if (_array_is_present) // Can we use cached values?
     last = _last;
   else
     {
       PetscErrorCode ierr=0;
       PetscInt petsc_first=0, petsc_last=0;
       ierr = VecGetOwnershipRange (_vec, &petsc_first, &petsc_last);
       LIBMESH_CHKERR(ierr);
       last = static_cast<numeric_index_type>(petsc_last);
     }
   return last;
 }
template<typename T > Real libMesh::PetscVector< T >::linfty_norm () const virtual
Returns
The -norm of the vector, i.e. the maximum absolute value of the entries of the vector.
Implements libMesh::NumericVector< T >.
Definition at line 92 of file petsc_vector.C.
References libMesh::closed(), ierr, libMesh::Real, and value.
 {
   this->_restore_array();
   libmesh_assert(this->closed());
   PetscErrorCode ierr=0;
   PetscReal value=0.;
   ierr = VecNorm (_vec, NORM_INFINITY, &value);
   LIBMESH_CHKERR(ierr);
   return static_cast<Real>(value);
 }
template<typename T> int libMesh::NumericVector< T >::local_relative_compare (const NumericVector< T > & other_vector, const Real threshold = TOLERANCE) const virtual inherited
Returns
-1 when this is equivalent to other_vector, (up to the given local relative threshold), or the first index where abs(a[i]-b[i])/max(a[i],b[i]) exceeds the threshold.
Definition at line 148 of file numeric_vector.C.
References std::abs(), libMesh::NumericVector< T >::first_local_index(), libMesh::NumericVector< T >::initialized(), libMesh::initialized(), libMesh::NumericVector< T >::last_local_index(), and std::max().
Referenced by libMesh::NumericVector< Number >::operator/=().
 {
   libmesh_assert (this->initialized());
   libmesh_assert (other_vector.initialized());
   libmesh_assert_equal_to (this->first_local_index(), other_vector.first_local_index());
   libmesh_assert_equal_to (this->last_local_index(), other_vector.last_local_index());
   int first_different_i = std::numeric_limits<int>::max();
   numeric_index_type i = first_local_index();
   do
     {
       if (std::abs((*this)(i) - other_vector(i)) > threshold *
           std::max(std::abs((*this)(i)), std::abs(other_vector(i))))
         first_different_i = i;
       else
         i++;
     }
   while (first_different_i==std::numeric_limits<int>::max()
          && i<last_local_index());
   // Find the correct first differing index in parallel
   this->comm().min(first_different_i);
   if (first_different_i == std::numeric_limits<int>::max())
     return -1;
   return first_different_i;
 }
template<typename T > numeric_index_type libMesh::PetscVector< T >::local_size () const inline virtual
Returns
The local size of the vector, i.e. index_stop - index_start.
Implements libMesh::NumericVector< T >.
Definition at line 939 of file petsc_vector.h.
References libMesh::PetscVector< T >::_vec, ierr, and libMesh::NumericVector< T >::initialized().
Referenced by libMesh::PetscVector< T >::operator=().
 {
   libmesh_assert (this->initialized());
   PetscErrorCode ierr=0;
   PetscInt petsc_size=0;
   ierr = VecGetLocalSize(_vec, &petsc_size);
   LIBMESH_CHKERR(ierr);
   return static_cast<numeric_index_type>(petsc_size);
 }
template<typename T > void libMesh::PetscVector< T >::localize (std::vector< T > & v_local) const virtual
Creates a copy of the global vector in the local vector v_local.
Implements libMesh::NumericVector< T >.
Definition at line 928 of file petsc_vector.C.
References ierr.
Referenced by libMesh::PetscVector< T >::localize().
 {
   this->_restore_array();
   // This function must be run on all processors at once
   parallel_object_only();
   PetscErrorCode ierr=0;
   const PetscInt n = this->size();
   const PetscInt nl = this->local_size();
   PetscScalar * values;
   v_local.clear();
   v_local.resize(n, 0.);
   ierr = VecGetArray (_vec, &values);
   LIBMESH_CHKERR(ierr);
   numeric_index_type ioff = first_local_index();
   for (PetscInt i=0; i<nl; i++)
     v_local[i+ioff] = static_cast<T>(values[i]);
   ierr = VecRestoreArray (_vec, &values);
   LIBMESH_CHKERR(ierr);
   this->comm().sum(v_local);
 }
template<typename T > void libMesh::PetscVector< T >::localize (NumericVector< T > & v_local) const virtual
Same, but fills a NumericVector<T> instead of a std::vector.
Implements libMesh::NumericVector< T >.
Definition at line 659 of file petsc_vector.C.
References libMesh::PetscVector< T >::_vec, libMesh::PetscVector< T >::close(), libMesh::GHOSTED, libMesh::MeshTools::Generation::Private::idx(), ierr, libMesh::Utility::iota(), PETSC_USE_POINTER, libMesh::PetscVector< T >::size(), and libMesh::NumericVector< T >::type().
 {
   this->_restore_array();
   // Make sure the NumericVector passed in is really a PetscVector
   PetscVector<T> * v_local = cast_ptr<PetscVector<T> *>(&v_local_in);
   libmesh_assert(v_local);
   libmesh_assert_equal_to (v_local->size(), this->size());
   PetscErrorCode ierr = 0;
   const PetscInt n = this->size();
   IS is;
   VecScatter scatter;
   // Create idx, idx[i] = i;
   std::vector<PetscInt> idx(n); Utility::iota (idx.begin(), idx.end(), 0);
   // Create the index set & scatter object
   ierr = ISCreateLibMesh(this->comm().get(), n, &idx[0], PETSC_USE_POINTER, &is);
   LIBMESH_CHKERR(ierr);
   ierr = VecScatterCreate(_vec,          is,
                           v_local->_vec, is,
                           &scatter);
   LIBMESH_CHKERR(ierr);
   // Perform the scatter
   ierr = VecScatterBegin(scatter, _vec, v_local->_vec,
                          INSERT_VALUES, SCATTER_FORWARD);
   LIBMESH_CHKERR(ierr);
   ierr = VecScatterEnd  (scatter, _vec, v_local->_vec,
                          INSERT_VALUES, SCATTER_FORWARD);
   LIBMESH_CHKERR(ierr);
   // Clean up
   ierr = LibMeshISDestroy (&is);
   LIBMESH_CHKERR(ierr);
   ierr = LibMeshVecScatterDestroy(&scatter);
   LIBMESH_CHKERR(ierr);
   // Make sure ghost dofs are up to date
   if (v_local->type() == GHOSTED)
     v_local->close();
 }
template<typename T > void libMesh::PetscVector< T >::localize (NumericVector< T > & v_local, const std::vector< numeric_index_type > & send_list) const virtual
Creates a local vector v_local containing only information relevant to this processor, as defined by the send_list.
Implements libMesh::NumericVector< T >.
Definition at line 711 of file petsc_vector.C.
References libMesh::PetscVector< T >::_vec, libMesh::PetscVector< T >::close(), libMesh::GHOSTED, libMesh::MeshTools::Generation::Private::idx(), ierr, libMesh::PARALLEL, PETSC_USE_POINTER, libMesh::PetscVector< T >::size(), and libMesh::NumericVector< T >::type().
 {
   // FIXME: Workaround for a strange bug at large-scale.
   // If we have ghosting, PETSc lets us just copy the solution, and
   // doing so avoids a segfault?
   if (v_local_in.type() == GHOSTED &&
       this->type() == PARALLEL)
     {
       v_local_in = *this;
       return;
     }
   // Normal code path begins here
   this->_restore_array();
   // Make sure the NumericVector passed in is really a PetscVector
   PetscVector<T> * v_local = cast_ptr<PetscVector<T> *>(&v_local_in);
   libmesh_assert(v_local);
   libmesh_assert_equal_to (v_local->size(), this->size());
   libmesh_assert_less_equal (send_list.size(), v_local->size());
   PetscErrorCode ierr=0;
   const numeric_index_type n_sl =
     cast_int<numeric_index_type>(send_list.size());
   IS is;
   VecScatter scatter;
   std::vector<PetscInt> idx(n_sl + this->local_size());
   for (numeric_index_type i=0; i<n_sl; i++)
     idx[i] = static_cast<PetscInt>(send_list[i]);
   for (numeric_index_type i = 0; i != this->local_size(); ++i)
     idx[n_sl+i] = i + this->first_local_index();
   // Create the index set & scatter object
   if (idx.empty())
     ierr = ISCreateLibMesh(this->comm().get(),
                            n_sl+this->local_size(), PETSC_NULL, PETSC_USE_POINTER, &is);
   else
     ierr = ISCreateLibMesh(this->comm().get(),
                            n_sl+this->local_size(), &idx[0], PETSC_USE_POINTER, &is);
   LIBMESH_CHKERR(ierr);
   ierr = VecScatterCreate(_vec,          is,
                           v_local->_vec, is,
                           &scatter);
   LIBMESH_CHKERR(ierr);
   // Perform the scatter
   ierr = VecScatterBegin(scatter, _vec, v_local->_vec,
                          INSERT_VALUES, SCATTER_FORWARD);
   LIBMESH_CHKERR(ierr);
   ierr = VecScatterEnd  (scatter, _vec, v_local->_vec,
                          INSERT_VALUES, SCATTER_FORWARD);
   LIBMESH_CHKERR(ierr);
   // Clean up
   ierr = LibMeshISDestroy (&is);
   LIBMESH_CHKERR(ierr);
   ierr = LibMeshVecScatterDestroy(&scatter);
   LIBMESH_CHKERR(ierr);
   // Make sure ghost dofs are up to date
   if (v_local->type() == GHOSTED)
     v_local->close();
 }
template<typename T > void libMesh::PetscVector< T >::localize (std::vector< T > & v_local, const std::vector< numeric_index_type > & indices) const virtual
Fill in the local std::vector "v_local" with the global indices given in "indices".
Note
The indices can be different on every processor, and the same index can be localized to more than one processor. The resulting v_local can be shorter than the original, and the entries will be in the order specified by indices.
Example:
*   On 4 procs *this = {a, b, c, d, e, f, g, h, i} is a parallel vector.
*   On each proc, the indices arrays are set up as:
*   proc0, indices = {1,2,4,5}
*   proc1, indices = {2,5,6,8}
*   proc2, indices = {2,3,6,7}
*   proc3, indices = {0,1,2,3}
*
*   After calling this version of localize, the v_local vectors are:
*   proc0, v_local = {b,c,e,f}
*   proc1, v_local = {c,f,g,i}
*   proc2, v_local = {c,d,g,h}
*   proc3, v_local = {a,b,c,d}
*
This function is useful in parallel I/O routines, when you have a parallel vector of solution values which you want to write a subset of.
Implements libMesh::NumericVector< T >.
Definition at line 788 of file petsc_vector.C.
References ierr, libMesh::numeric_petsc_cast(), and PETSC_USE_POINTER.
 {
   // Error code used to check the status of all PETSc function calls.
   PetscErrorCode ierr = 0;
   // Create a sequential destination Vec with the right number of entries on each proc.
   Vec dest;
   ierr = VecCreateSeq(PETSC_COMM_SELF, indices.size(), &dest);
   LIBMESH_CHKERR(ierr);
   // Create an IS using the libmesh routine.  PETSc does not own the
   // IS memory in this case, it is automatically cleaned up by the
   // std::vector destructor.
   IS is;
   ierr = ISCreateLibMesh(this->comm().get(),
                          indices.size(),
                          numeric_petsc_cast(&indices[0]),
                          PETSC_USE_POINTER,
                          &is);
   LIBMESH_CHKERR(ierr);
   // Create the VecScatter object.  "NULL" means "use the identity IS".
   VecScatter scatter;
   ierr = VecScatterCreate(_vec,
                           /*src is=*/is,
                           /*dest vec=*/dest,
                           /*dest is=*/NULL,
                           &scatter);
   LIBMESH_CHKERR(ierr);
   // Do the scatter
   ierr = VecScatterBegin(scatter, _vec, dest, INSERT_VALUES, SCATTER_FORWARD);
   LIBMESH_CHKERR(ierr);
   ierr = VecScatterEnd(scatter, _vec, dest, INSERT_VALUES, SCATTER_FORWARD);
   LIBMESH_CHKERR(ierr);
   // Get access to the values stored in dest.
   PetscScalar * values;
   ierr = VecGetArray (dest, &values);
   LIBMESH_CHKERR(ierr);
   // Store values into the provided v_local. Make sure there is enough
   // space reserved and then clear out any existing entries before
   // inserting.
   v_local.reserve(indices.size());
   v_local.clear();
   v_local.insert(v_local.begin(), values, values+indices.size());
   // We are done using it, so restore the array.
   ierr = VecRestoreArray (dest, &values);
   LIBMESH_CHKERR(ierr);
   // Clean up PETSc data structures.
   ierr = LibMeshVecScatterDestroy(&scatter);
   LIBMESH_CHKERR(ierr);
   ierr = LibMeshISDestroy (&is);
   LIBMESH_CHKERR(ierr);
   ierr = LibMeshVecDestroy(&dest);
   LIBMESH_CHKERR(ierr);
 }
template<typename T > void libMesh::PetscVector< T >::localize (const numeric_index_type first_local_idx, const numeric_index_type last_local_idx, const std::vector< numeric_index_type > & send_list) virtual
Updates a local vector with selected values from neighboring processors, as defined by send_list.
Implements libMesh::NumericVector< T >.
Definition at line 856 of file petsc_vector.C.
References libMesh::PetscVector< T >::_vec, libMesh::PetscVector< T >::close(), libMesh::MeshTools::Generation::Private::idx(), ierr, libMesh::PetscVector< T >::init(), libMesh::Utility::iota(), libmesh_nullptr, libMesh::PetscVector< T >::localize(), libMesh::n_processors(), libMesh::PARALLEL, and PETSC_USE_POINTER.
 {
   this->_restore_array();
   libmesh_assert_less_equal (send_list.size(), this->size());
   libmesh_assert_less_equal (last_local_idx+1, this->size());
   const numeric_index_type my_size       = this->size();
   const numeric_index_type my_local_size = (last_local_idx - first_local_idx + 1);
   PetscErrorCode ierr=0;
   // Don't bother for serial cases
   //  if ((first_local_idx == 0) &&
   //      (my_local_size == my_size))
   // But we do need to stay in sync for degenerate cases
   if (this->n_processors() == 1)
     return;
   // Build a parallel vector, initialize it with the local
   // parts of (*this)
   PetscVector<T> parallel_vec(this->comm(), PARALLEL);
   parallel_vec.init (my_size, my_local_size, true, PARALLEL);
   // Copy part of *this into the parallel_vec
   {
     IS is;
     VecScatter scatter;
     // Create idx, idx[i] = i+first_local_idx;
     std::vector<PetscInt> idx(my_local_size);
     Utility::iota (idx.begin(), idx.end(), first_local_idx);
     // Create the index set & scatter object
     ierr = ISCreateLibMesh(this->comm().get(), my_local_size,
                            my_local_size ? &idx[0] : libmesh_nullptr, PETSC_USE_POINTER, &is);
     LIBMESH_CHKERR(ierr);
     ierr = VecScatterCreate(_vec,              is,
                             parallel_vec._vec, is,
                             &scatter);
     LIBMESH_CHKERR(ierr);
     ierr = VecScatterBegin(scatter, _vec, parallel_vec._vec,
                            INSERT_VALUES, SCATTER_FORWARD);
     LIBMESH_CHKERR(ierr);
     ierr = VecScatterEnd  (scatter, _vec, parallel_vec._vec,
                            INSERT_VALUES, SCATTER_FORWARD);
     LIBMESH_CHKERR(ierr);
     // Clean up
     ierr = LibMeshISDestroy (&is);
     LIBMESH_CHKERR(ierr);
     ierr = LibMeshVecScatterDestroy(&scatter);
     LIBMESH_CHKERR(ierr);
   }
   // localize like normal
   parallel_vec.close();
   parallel_vec.localize (*this, send_list);
   this->close();
 }
template<typename T> virtual void libMesh::PetscVector< T >::localize_to_one (std::vector< T > & v_local, const processor_id_type proc_id = 0) const virtual
Creates a local copy of the global vector in v_local only on processor proc_id. By default the data is sent to processor 0. This method is useful for outputting data from one processor.
Implements libMesh::NumericVector< T >.
template<> void libMesh::PetscVector< Real >::localize_to_one (std::vector< Real > & v_local, const processor_id_type pid) const
Definition at line 963 of file petsc_vector.C.
References ierr, libMesh::n_processors(), and libMesh::processor_id().
 {
   this->_restore_array();
   PetscErrorCode ierr=0;
   const PetscInt n  = size();
   const PetscInt nl = local_size();
   PetscScalar * values;
   // only one processor
   if (n_processors() == 1)
     {
       v_local.resize(n);
       ierr = VecGetArray (_vec, &values);
       LIBMESH_CHKERR(ierr);
       for (PetscInt i=0; i<n; i++)
         v_local[i] = static_cast<Real>(values[i]);
       ierr = VecRestoreArray (_vec, &values);
       LIBMESH_CHKERR(ierr);
     }
   // otherwise multiple processors
   else
     {
       if (pid == 0) // optimized version for localizing to 0
         {
           Vec vout;
           VecScatter ctx;
           ierr = VecScatterCreateToZero(_vec, &ctx, &vout);
           LIBMESH_CHKERR(ierr);
           ierr = VecScatterBegin(ctx, _vec, vout, INSERT_VALUES, SCATTER_FORWARD);
           LIBMESH_CHKERR(ierr);
           ierr = VecScatterEnd(ctx, _vec, vout, INSERT_VALUES, SCATTER_FORWARD);
           LIBMESH_CHKERR(ierr);
           if (processor_id() == 0)
             {
               v_local.resize(n);
               ierr = VecGetArray (vout, &values);
               LIBMESH_CHKERR(ierr);
               for (PetscInt i=0; i<n; i++)
                 v_local[i] = static_cast<Real>(values[i]);
               ierr = VecRestoreArray (vout, &values);
               LIBMESH_CHKERR(ierr);
             }
           ierr = LibMeshVecScatterDestroy(&ctx);
           LIBMESH_CHKERR(ierr);
           ierr = LibMeshVecDestroy(&vout);
           LIBMESH_CHKERR(ierr);
         }
       else
         {
           v_local.resize(n);
           numeric_index_type ioff = this->first_local_index();
           std::vector<Real> local_values (n, 0.);
           {
             ierr = VecGetArray (_vec, &values);
             LIBMESH_CHKERR(ierr);
             for (PetscInt i=0; i<nl; i++)
               local_values[i+ioff] = static_cast<Real>(values[i]);
             ierr = VecRestoreArray (_vec, &values);
             LIBMESH_CHKERR(ierr);
           }
           MPI_Reduce (&local_values[0], &v_local[0], n, MPI_REAL, MPI_SUM,
                       pid, this->comm().get());
         }
     }
 }
template<> void libMesh::PetscVector< Complex >::localize_to_one (std::vector< Complex > & v_local, const processor_id_type pid) const
Definition at line 1057 of file petsc_vector.C.
References ierr, and libMesh::n_processors().
 {
   this->_restore_array();
   PetscErrorCode ierr=0;
   const PetscInt n  = size();
   const PetscInt nl = local_size();
   PetscScalar * values;
   v_local.resize(n);
   for (PetscInt i=0; i<n; i++)
     v_local[i] = 0.;
   // only one processor
   if (n_processors() == 1)
     {
       ierr = VecGetArray (_vec, &values);
       LIBMESH_CHKERR(ierr);
       for (PetscInt i=0; i<n; i++)
         v_local[i] = static_cast<Complex>(values[i]);
       ierr = VecRestoreArray (_vec, &values);
       LIBMESH_CHKERR(ierr);
     }
   // otherwise multiple processors
   else
     {
       numeric_index_type ioff = this->first_local_index();
       /* in here the local values are stored, acting as send buffer for MPI
        * initialize to zero, since we collect using MPI_SUM
        */
       std::vector<Real> real_local_values(n, 0.);
       std::vector<Real> imag_local_values(n, 0.);
       {
         ierr = VecGetArray (_vec, &values);
         LIBMESH_CHKERR(ierr);
         // provide my local share to the real and imag buffers
         for (PetscInt i=0; i<nl; i++)
           {
             real_local_values[i+ioff] = static_cast<Complex>(values[i]).real();
             imag_local_values[i+ioff] = static_cast<Complex>(values[i]).imag();
           }
         ierr = VecRestoreArray (_vec, &values);
         LIBMESH_CHKERR(ierr);
       }
       /* have buffers of the real and imaginary part of v_local.
        * Once MPI_Reduce() collected all the real and imaginary
        * parts in these std::vector<Real>, the values can be
        * copied to v_local
        */
       std::vector<Real> real_v_local(n);
       std::vector<Real> imag_v_local(n);
       // collect entries from other proc's in real_v_local, imag_v_local
       MPI_Reduce (&real_local_values[0], &real_v_local[0], n,
                   MPI_REAL, MPI_SUM,
                   pid, this->comm().get());
       MPI_Reduce (&imag_local_values[0], &imag_v_local[0], n,
                   MPI_REAL, MPI_SUM,
                   pid, this->comm().get());
       // copy real_v_local and imag_v_local to v_local
       for (PetscInt i=0; i<n; i++)
         v_local[i] = Complex(real_v_local[i], imag_v_local[i]);
     }
 }
template<typename T > numeric_index_type libMesh::PetscVector< T >::map_global_to_local_index (const numeric_index_type i) const inline
Returns
The local index corresponding to global index i.
If the index is not a ghost cell, this is done by subtraction the number of the first local index. If it is a ghost cell, it has to be looked up in the map.
Definition at line 1004 of file petsc_vector.h.
References libMesh::PetscVector< T >::_array_is_present, libMesh::PetscVector< T >::_first, libMesh::PetscVector< T >::_global_to_local_map, libMesh::PetscVector< T >::_last, libMesh::PetscVector< T >::_vec, end, ierr, and libMesh::NumericVector< T >::initialized().
Referenced by libMesh::PetscVector< T >::get(), and libMesh::PetscVector< T >::operator()().
 {
   libmesh_assert (this->initialized());
   numeric_index_type first=0;
   numeric_index_type last=0;
   if (_array_is_present) // Can we use cached values?
     {
       first = _first;
       last = _last;
     }
   else
     {
       PetscErrorCode ierr=0;
       PetscInt petsc_first=0, petsc_last=0;
       ierr = VecGetOwnershipRange (_vec, &petsc_first, &petsc_last);
       LIBMESH_CHKERR(ierr);
       first = static_cast<numeric_index_type>(petsc_first);
       last = static_cast<numeric_index_type>(petsc_last);
     }
   if ((i>=first) && (i<last))
     {
       return i-first;
     }
   GlobalToLocalMap::const_iterator it = _global_to_local_map.find(i);
 #ifndef NDEBUG
   const GlobalToLocalMap::const_iterator end = _global_to_local_map.end();
   if (it == end)
     {
       std::ostringstream error_message;
       error_message << "No index " << i << " in ghosted vector.\n"
                     << "Vector contains [" << first << ',' << last << ")\n";
       GlobalToLocalMap::const_iterator b = _global_to_local_map.begin();
       if (b == end)
         {
           error_message << "And empty ghost array.\n";
         }
       else
         {
           error_message << "And ghost array {" << b->first;
           for (++b; b != end; ++b)
             error_message << ',' << b->first;
           error_message << "}\n";
         }
       libmesh_error_msg(error_message.str());
     }
   libmesh_assert (it != _global_to_local_map.end());
 #endif
   return it->second+last-first;
 }
template<typename T > Real libMesh::PetscVector< T >::max () const inline virtual
Returns
The maximum entry in the vector, or the maximum real part in the case of complex numbers.
Implements libMesh::NumericVector< T >.
Definition at line 1159 of file petsc_vector.h.
References libMesh::PetscVector< T >::_restore_array(), libMesh::PetscVector< T >::_vec, ierr, and libMesh::Real.
 {
   parallel_object_only();
   this->_restore_array();
   PetscErrorCode ierr=0;
   PetscInt index=0;
   PetscReal returnval=0.;
   ierr = VecMax (_vec, &index, &returnval);
   LIBMESH_CHKERR(ierr);
   // this return value is correct: VecMax returns a PetscReal
   return static_cast<Real>(returnval);
 }
template<typename T > Real libMesh::PetscVector< T >::min () const inline virtual
Returns
The minimum entry in the vector, or the minimum real part in the case of complex numbers.
Implements libMesh::NumericVector< T >.
Definition at line 1138 of file petsc_vector.h.
References libMesh::PetscVector< T >::_restore_array(), libMesh::PetscVector< T >::_vec, ierr, and libMesh::Real.
 {
   parallel_object_only();
   this->_restore_array();
   PetscErrorCode ierr=0;
   PetscInt index=0;
   PetscReal returnval=0.;
   ierr = VecMin (_vec, &index, &returnval);
   LIBMESH_CHKERR(ierr);
   // this return value is correct: VecMin returns a PetscReal
   return static_cast<Real>(returnval);
 }
static unsigned int libMesh::ReferenceCounter::n_objects () inline static inherited
Prints the number of outstanding (created, but not yet destroyed) objects.
Definition at line 85 of file reference_counter.h.
References libMesh::ReferenceCounter::_n_objects, libMesh::ReferenceCounter::disable_print_counter_info(), libMesh::ReferenceCounter::enable_print_counter_info(), libMesh::ReferenceCounter::increment_constructor_count(), libMesh::ReferenceCounter::increment_destructor_count(), and libMesh::Quality::name().
Referenced by libMesh::System::hide_output(), and libMesh::LibMeshInit::LibMeshInit().
   { return _n_objects; }
processor_id_type libMesh::ParallelObject::n_processors () const inline inherited
Returns
The number of processors in the group.
Definition at line 93 of file parallel_object.h.
References libMesh::ParallelObject::_communicator, and libMesh::Parallel::Communicator::size().
Referenced by libMesh::ParmetisPartitioner::_do_repartition(), libMesh::BoundaryInfo::_find_id_maps(), libMesh::DistributedMesh::add_elem(), libMesh::DistributedMesh::add_node(), libMesh::LaplaceMeshSmoother::allgather_graph(), libMesh::FEMSystem::assembly(), libMesh::ParmetisPartitioner::assign_partitioning(), libMesh::AztecLinearSolver< T >::AztecLinearSolver(), libMesh::MeshCommunication::broadcast(), libMesh::BoundaryInfo::build_node_list_from_side_list(), libMesh::DistributedMesh::clear(), libMesh::Nemesis_IO_Helper::compute_border_node_ids(), libMesh::Nemesis_IO_Helper::construct_nemesis_filename(), libMesh::MeshTools::correct_node_proc_ids(), libMesh::UnstructuredMesh::create_pid_mesh(), libMesh::MeshTools::create_processor_bounding_box(), libMesh::DofMap::distribute_dofs(), libMesh::DofMap::distribute_local_dofs_node_major(), libMesh::DofMap::distribute_local_dofs_var_major(), libMesh::DistributedMesh::DistributedMesh(), libMesh::EnsightIO::EnsightIO(), libMesh::MeshCommunication::gather(), libMesh::MeshCommunication::gather_neighboring_elements(), libMesh::MeshBase::get_info(), libMesh::EquationSystems::get_solution(), libMesh::DistributedVector< T >::init(), libMesh::SystemSubsetBySubdomain::init(), libMesh::ParmetisPartitioner::initialize(), libMesh::Nemesis_IO_Helper::initialize(), libMesh::DistributedMesh::insert_elem(), libMesh::MeshTools::libmesh_assert_parallel_consistent_procids< Elem >(), libMesh::MeshTools::libmesh_assert_parallel_consistent_procids< Node >(), libMesh::MeshTools::libmesh_assert_topology_consistent_procids< Node >(), libMesh::MeshTools::libmesh_assert_valid_boundary_ids(), libMesh::MeshTools::libmesh_assert_valid_dof_ids(), libMesh::MeshTools::libmesh_assert_valid_neighbors(), libMesh::MeshTools::libmesh_assert_valid_refinement_flags(), libMesh::DofMap::local_variable_indices(), libMesh::MeshRefinement::make_coarsening_compatible(), libMesh::MeshBase::n_active_elem_on_proc(), libMesh::MeshBase::n_elem_on_proc(), libMesh::MeshBase::n_nodes_on_proc(), libMesh::SparsityPattern::Build::parallel_sync(), libMesh::Partitioner::partition(), libMesh::MeshBase::partition(), libMesh::Partitioner::partition_unpartitioned_elements(), libMesh::PetscLinearSolver< T >::PetscLinearSolver(), libMesh::System::point_gradient(), libMesh::System::point_hessian(), libMesh::System::point_value(), libMesh::SparseMatrix< T >::print(), libMesh::NameBasedIO::read(), libMesh::Nemesis_IO::read(), libMesh::CheckpointIO::read(), libMesh::CheckpointIO::read_connectivity(), libMesh::XdrIO::read_header(), libMesh::CheckpointIO::read_nodes(), libMesh::MeshCommunication::redistribute(), libMesh::DistributedMesh::renumber_dof_objects(), libMesh::Partitioner::repartition(), libMesh::MeshCommunication::send_coarse_ghosts(), libMesh::Partitioner::set_node_processor_ids(), libMesh::DofMap::set_nonlocal_dof_objects(), libMesh::Parallel::Sort< KeyType, IdxType >::sort(), libMesh::MeshRefinement::uniformly_coarsen(), libMesh::DistributedMesh::update_parallel_id_counts(), libMesh::GMVIO::write_binary(), libMesh::GMVIO::write_discontinuous_gmv(), libMesh::XdrIO::write_serialized_bcs_helper(), libMesh::XdrIO::write_serialized_connectivity(), libMesh::XdrIO::write_serialized_nodes(), and libMesh::XdrIO::write_serialized_nodesets().
   { return cast_int<processor_id_type>(_communicator.size()); }
template<typename T > T libMesh::PetscVector< T >::operator() (const numeric_index_type i) const inline virtual
Returns
A copy of the ith entry of the vector.
Implements libMesh::NumericVector< T >.
Definition at line 1064 of file petsc_vector.h.
References libMesh::PetscVector< T >::_get_array(), libMesh::PetscVector< T >::_local_size, libMesh::PetscVector< T >::_read_only_values, libMesh::GHOSTED, libMesh::PetscVector< T >::map_global_to_local_index(), and libMesh::NumericVector< T >::type().
 {
   this->_get_array(true);
   const numeric_index_type local_index = this->map_global_to_local_index(i);
 #ifndef NDEBUG
   if (this->type() == GHOSTED)
     {
       libmesh_assert_less (local_index, _local_size);
     }
 #endif
   return static_cast<T>(_read_only_values[local_index]);
 }
template<typename T> NumericVector<T>& libMesh::NumericVector< T >::operator*= (const T a) inline inherited
Scales the vector by a, . Equivalent to u.scale(a)
Returns
A reference to *this.
Definition at line 387 of file numeric_vector.h.
 { this->scale(a); return *this; }
template<typename T > NumericVector< T > & libMesh::PetscVector< T >::operator+= (const NumericVector< T > & v) virtual
Adds v to *this, . Equivalent to u.add(1, v).
Returns
A reference to *this.
Implements libMesh::NumericVector< T >.
Definition at line 111 of file petsc_vector.C.
References libMesh::closed().
 {
   this->_restore_array();
   libmesh_assert(this->closed());
   this->add(1., v);
   return *this;
 }
template<typename T > NumericVector< T > & libMesh::PetscVector< T >::operator-= (const NumericVector< T > & v) virtual
Subtracts v from *this, . Equivalent to u.add(-1, v).
Returns
A reference to *this.
Implements libMesh::NumericVector< T >.
Definition at line 125 of file petsc_vector.C.
References libMesh::closed().
 {
   this->_restore_array();
   libmesh_assert(this->closed());
   this->add(-1., v);
   return *this;
 }
template<typename T > NumericVector< T > & libMesh::PetscVector< T >::operator/= (NumericVector< T > &) virtual
Computes the pointwise division of this vector's entries by another's,
Returns
A reference to *this.
Implements libMesh::NumericVector< T >.
Definition at line 426 of file petsc_vector.C.
References libMesh::PetscVector< T >::_vec, and ierr.
 {
   PetscErrorCode ierr = 0;
   const PetscVector<T> * v_vec = cast_ptr<const PetscVector<T> *>(&v);
   ierr = VecPointwiseDivide(_vec, _vec, v_vec->_vec);
   LIBMESH_CHKERR(ierr);
   return *this;
 }
template<typename T> NumericVector<T>& libMesh::NumericVector< T >::operator/= (const T a) inline inherited
Scales the vector by 1/a, . Equivalent to u.scale(1./a)
Returns
A reference to *this.
Definition at line 396 of file numeric_vector.h.
Referenced by libMesh::NumericVector< Number >::operator/=().
 { this->scale(1./a); return *this; }
template<typename T > NumericVector< T > & libMesh::PetscVector< T >::operator= (const T s) virtual
Sets all entries of the vector to the value s.
Returns
A reference to *this.
Implements libMesh::NumericVector< T >.
Definition at line 509 of file petsc_vector.C.
References libMesh::closed(), libMesh::GHOSTED, and ierr.
 {
   this->_restore_array();
   libmesh_assert(this->closed());
   PetscErrorCode ierr = 0;
   PetscScalar s = static_cast<PetscScalar>(s_in);
   if (this->size() != 0)
     {
       if (this->type() != GHOSTED)
         {
           ierr = VecSet(_vec, s);
           LIBMESH_CHKERR(ierr);
         }
       else
         {
           Vec loc_vec;
           ierr = VecGhostGetLocalForm (_vec,&loc_vec);
           LIBMESH_CHKERR(ierr);
           ierr = VecSet(loc_vec, s);
           LIBMESH_CHKERR(ierr);
           ierr = VecGhostRestoreLocalForm (_vec,&loc_vec);
           LIBMESH_CHKERR(ierr);
         }
     }
   return *this;
 }
template<typename T > NumericVector< T > & libMesh::PetscVector< T >::operator= (const NumericVector< T > & v) virtual
Sets (*this)(i) = v(i) for each entry of the vector.
Returns
A reference to *this as the base type.
Implements libMesh::NumericVector< T >.
Definition at line 545 of file petsc_vector.C.
 {
   // Make sure the NumericVector passed in is really a PetscVector
   const PetscVector<T> * v = cast_ptr<const PetscVector<T> *>(&v_in);
   *this = *v;
   return *this;
 }
template<typename T > NumericVector< T > & libMesh::PetscVector< T >::operator= (const std::vector< T > & v) virtual
Sets (*this)(i) = v(i) for each entry of the vector.
Returns
A reference to *this as the base type.
Case 1: The vector is the same size of The global vector. Only add the local components.
Case 2: The vector is the same size as our local piece. Insert directly to the local piece.
Implements libMesh::NumericVector< T >.
Definition at line 623 of file petsc_vector.C.
References libMesh::GHOSTED.
 {
   this->_get_array(false);
   if (this->size() == v.size())
     {
       numeric_index_type first = first_local_index();
       numeric_index_type last = last_local_index();
       for (numeric_index_type i=0; i<last-first; i++)
         _values[i] =  static_cast<PetscScalar>(v[first + i]);
     }
   else
     {
       for (numeric_index_type i=0; i<_local_size; i++)
         _values[i] = static_cast<PetscScalar>(v[i]);
     }
   // Make sure ghost dofs are up to date
   if (this->type() == GHOSTED)
     this->close();
   return *this;
 }
template<typename T > PetscVector< T > & libMesh::PetscVector< T >::operator= (const PetscVector< T > & v)
Sets (*this)(i) = v(i) for each entry of the vector.
Returns
A reference to *this as the derived type.
Definition at line 559 of file petsc_vector.C.
References libMesh::PetscVector< T >::_restore_array(), libMesh::NumericVector< T >::_type, libMesh::PetscVector< T >::_vec, libMesh::NumericVector< T >::closed(), libMesh::GHOSTED, ierr, libMesh::PetscVector< T >::local_size(), libMesh::PARALLEL, libMesh::SERIAL, libMesh::PetscVector< T >::size(), and libMesh::NumericVector< T >::type().
 {
   this->_restore_array();
   v._restore_array();
   libmesh_assert_equal_to (this->size(), v.size());
   libmesh_assert_equal_to (this->local_size(), v.local_size());
   libmesh_assert (v.closed());
   PetscErrorCode ierr = 0;
   if (((this->type()==PARALLEL) && (v.type()==GHOSTED)) ||
       ((this->type()==GHOSTED) && (v.type()==PARALLEL)) ||
       ((this->type()==GHOSTED) && (v.type()==SERIAL))   ||
       ((this->type()==SERIAL) && (v.type()==GHOSTED)))
     {
       /* Allow assignment of a ghosted to a parallel vector since this
          causes no difficulty.  See discussion in libmesh-devel of
          June 24, 2010.  */
       ierr = VecCopy (v._vec, this->_vec);
       LIBMESH_CHKERR(ierr);
     }
   else
     {
       /* In all other cases, we assert that both vectors are of equal
          type.  */
       libmesh_assert_equal_to (this->_type, v._type);
       if (v.size() != 0)
         {
           if (this->type() != GHOSTED)
             {
               ierr = VecCopy (v._vec, this->_vec);
               LIBMESH_CHKERR(ierr);
             }
           else
             {
               Vec loc_vec;
               Vec v_loc_vec;
               ierr = VecGhostGetLocalForm (_vec,&loc_vec);
               LIBMESH_CHKERR(ierr);
               ierr = VecGhostGetLocalForm (v._vec,&v_loc_vec);
               LIBMESH_CHKERR(ierr);
               ierr = VecCopy (v_loc_vec, loc_vec);
               LIBMESH_CHKERR(ierr);
               ierr = VecGhostRestoreLocalForm (v._vec,&v_loc_vec);
               LIBMESH_CHKERR(ierr);
               ierr = VecGhostRestoreLocalForm (_vec,&loc_vec);
               LIBMESH_CHKERR(ierr);
             }
         }
     }
   close();
   return *this;
 }
template<typename T > void libMesh::PetscVector< T >::pointwise_mult (const NumericVector< T > & vec1, const NumericVector< T > & vec2) virtual
Computes (summation not implied) i.e. the pointwise (component-wise) product of vec1 and vec2, and stores the result in *this.
Implements libMesh::NumericVector< T >.
Definition at line 1141 of file petsc_vector.C.
References libMesh::GHOSTED, and ierr.
 {
   this->_restore_array();
   PetscErrorCode ierr = 0;
   // Convert arguments to PetscVector*.
   const PetscVector<T> * vec1_petsc = cast_ptr<const PetscVector<T> *>(&vec1);
   const PetscVector<T> * vec2_petsc = cast_ptr<const PetscVector<T> *>(&vec2);
   // Call PETSc function.
   if (this->type() != GHOSTED)
     {
       ierr = VecPointwiseMult(this->vec(),
                               const_cast<PetscVector<T> *>(vec1_petsc)->vec(),
                               const_cast<PetscVector<T> *>(vec2_petsc)->vec());
       LIBMESH_CHKERR(ierr);
     }
   else
     {
       Vec loc_vec;
       Vec v1_loc_vec;
       Vec v2_loc_vec;
       ierr = VecGhostGetLocalForm (_vec,&loc_vec);
       LIBMESH_CHKERR(ierr);
       ierr = VecGhostGetLocalForm (const_cast<PetscVector<T> *>(vec1_petsc)->vec(),&v1_loc_vec);
       LIBMESH_CHKERR(ierr);
       ierr = VecGhostGetLocalForm (const_cast<PetscVector<T> *>(vec2_petsc)->vec(),&v2_loc_vec);
       LIBMESH_CHKERR(ierr);
       ierr = VecPointwiseMult(loc_vec,v1_loc_vec,v2_loc_vec);
       LIBMESH_CHKERR(ierr);
       ierr = VecGhostRestoreLocalForm (const_cast<PetscVector<T> *>(vec1_petsc)->vec(),&v1_loc_vec);
       LIBMESH_CHKERR(ierr);
       ierr = VecGhostRestoreLocalForm (const_cast<PetscVector<T> *>(vec2_petsc)->vec(),&v2_loc_vec);
       LIBMESH_CHKERR(ierr);
       ierr = VecGhostRestoreLocalForm (_vec,&loc_vec);
       LIBMESH_CHKERR(ierr);
     }
 }
template<typename T > void libMesh::NumericVector< T >::print (std::ostream & os = libMesh::out) const inline virtual inherited
Prints the local contents of the vector, by default to libMesh::out
Definition at line 921 of file numeric_vector.h.
References libMesh::NumericVector< T >::first_local_index(), libMesh::NumericVector< T >::initialized(), libMesh::NumericVector< T >::last_local_index(), libMesh::NumericVector< T >::local_size(), and libMesh::NumericVector< T >::size().
Referenced by libMesh::NumericVector< Number >::operator/=().
 {
   libmesh_assert (this->initialized());
   os << "Size\tglobal =  " << this->size()
      << "\t\tlocal =  " << this->local_size() << std::endl;
   os << "#\tValue" << std::endl;
   for (numeric_index_type i=this->first_local_index(); i<this->last_local_index(); i++)
     os << i << "\t" << (*this)(i) << std::endl;
 }
template<> void libMesh::NumericVector< Complex >::print (std::ostream & os) const inline inherited
Definition at line 903 of file numeric_vector.h.
References libMesh::NumericVector< T >::first_local_index(), libMesh::NumericVector< T >::initialized(), libMesh::NumericVector< T >::last_local_index(), libMesh::NumericVector< T >::local_size(), and libMesh::NumericVector< T >::size().
 {
   libmesh_assert (this->initialized());
   os << "Size\tglobal =  " << this->size()
      << "\t\tlocal =  " << this->local_size() << std::endl;
   // std::complex<>::operator<<() is defined, but use this form
   os << "#\tReal part\t\tImaginary part" << std::endl;
   for (numeric_index_type i=this->first_local_index(); i<this->last_local_index(); i++)
     os << i << "\t"
        << (*this)(i).real() << "\t\t"
        << (*this)(i).imag() << std::endl;
 }
template<typename T > void libMesh::NumericVector< T >::print_global (std::ostream & os = libMesh::out) const inline virtual inherited
Prints the global contents of the vector, by default to libMesh::out
Definition at line 958 of file numeric_vector.h.
References libMesh::NumericVector< T >::initialized(), libMesh::NumericVector< T >::localize(), libMesh::ParallelObject::processor_id(), and libMesh::NumericVector< T >::size().
Referenced by libMesh::NumericVector< Number >::operator/=().
 {
   libmesh_assert (this->initialized());
   std::vector<T> v(this->size());
   this->localize(v);
   // Right now we only want one copy of the output
   if (this->processor_id())
     return;
   os << "Size\tglobal =  " << this->size() << std::endl;
   os << "#\tValue" << std::endl;
   for (numeric_index_type i=0; i!=v.size(); i++)
     os << i << "\t" << v[i] << std::endl;
 }
template<> void libMesh::NumericVector< Complex >::print_global (std::ostream & os) const inline inherited
Definition at line 936 of file numeric_vector.h.
References libMesh::NumericVector< T >::initialized(), libMesh::NumericVector< T >::localize(), libMesh::ParallelObject::processor_id(), and libMesh::NumericVector< T >::size().
 {
   libmesh_assert (this->initialized());
   std::vector<Complex> v(this->size());
   this->localize(v);
   // Right now we only want one copy of the output
   if (this->processor_id())
     return;
   os << "Size\tglobal =  " << this->size() << std::endl;
   os << "#\tReal part\t\tImaginary part" << std::endl;
   for (numeric_index_type i=0; i!=v.size(); i++)
     os << i << "\t"
        << v[i].real() << "\t\t"
        << v[i].imag() << std::endl;
 }
void libMesh::ReferenceCounter::print_info (std::ostream & out = libMesh::out) static inherited
Prints the reference information, by default to libMesh::out.
Definition at line 88 of file reference_counter.C.
References libMesh::ReferenceCounter::_enable_print_counter, and libMesh::ReferenceCounter::get_info().
Referenced by libMesh::LibMeshInit::LibMeshInit().
 {
   if (_enable_print_counter)
     out_stream << ReferenceCounter::get_info();
 }
template<typename T > void libMesh::PetscVector< T >::print_matlab (const std::string & = "") const virtual
Print the contents of the vector in Matlab's sparse matrix format. Optionally prints the vector to the file named name. If name is not specified it is dumped to the screen.
Create an ASCII file containing the matrix if a filename was provided.
Otherwise the matrix will be dumped to the screen.
Destroy the viewer.
Reimplemented from libMesh::NumericVector< T >.
Definition at line 1188 of file petsc_vector.C.
References libMesh::closed(), and ierr.
 {
   this->_restore_array();
   libmesh_assert (this->closed());
   PetscErrorCode ierr=0;
   PetscViewer petsc_viewer;
   ierr = PetscViewerCreate (this->comm().get(),
                             &petsc_viewer);
   LIBMESH_CHKERR(ierr);
   if (name != "")
     {
       ierr = PetscViewerASCIIOpen( this->comm().get(),
                                    name.c_str(),
                                    &petsc_viewer);
       LIBMESH_CHKERR(ierr);
 #if PETSC_VERSION_LESS_THAN(3,7,0)
       ierr = PetscViewerSetFormat (petsc_viewer,
                                    PETSC_VIEWER_ASCII_MATLAB);
 #else
       ierr = PetscViewerPushFormat (petsc_viewer,
                                     PETSC_VIEWER_ASCII_MATLAB);
 #endif
       LIBMESH_CHKERR(ierr);
       ierr = VecView (_vec, petsc_viewer);
       LIBMESH_CHKERR(ierr);
     }
   else
     {
 #if PETSC_VERSION_LESS_THAN(3,7,0)
       ierr = PetscViewerSetFormat (PETSC_VIEWER_STDOUT_WORLD,
                                    PETSC_VIEWER_ASCII_MATLAB);
 #else
       ierr = PetscViewerPushFormat (PETSC_VIEWER_STDOUT_WORLD,
                                     PETSC_VIEWER_ASCII_MATLAB);
 #endif
       LIBMESH_CHKERR(ierr);
       ierr = VecView (_vec, PETSC_VIEWER_STDOUT_WORLD);
       LIBMESH_CHKERR(ierr);
     }
   ierr = LibMeshPetscViewerDestroy (&petsc_viewer);
   LIBMESH_CHKERR(ierr);
 }
processor_id_type libMesh::ParallelObject::processor_id () const inline inherited
Returns
The rank of this processor in the group.
Definition at line 99 of file parallel_object.h.
References libMesh::ParallelObject::_communicator, and libMesh::Parallel::Communicator::rank().
Referenced by libMesh::BoundaryInfo::_find_id_maps(), libMesh::EquationSystems::_read_impl(), libMesh::DistributedMesh::add_elem(), libMesh::BoundaryInfo::add_elements(), libMesh::DofMap::add_neighbors_to_send_list(), libMesh::DistributedMesh::add_node(), libMesh::MeshRefinement::add_node(), libMesh::MeshTools::Modification::all_tri(), libMesh::FEMSystem::assembly(), libMesh::ParmetisPartitioner::assign_partitioning(), libMesh::MeshCommunication::broadcast(), libMesh::EquationSystems::build_discontinuous_solution_vector(), libMesh::Nemesis_IO_Helper::build_element_and_node_maps(), libMesh::ParmetisPartitioner::build_graph(), libMesh::InfElemBuilder::build_inf_elem(), libMesh::BoundaryInfo::build_node_list_from_side_list(), libMesh::DofMap::build_sparsity(), libMesh::DistributedMesh::clear(), libMesh::ExodusII_IO_Helper::close(), libMesh::Nemesis_IO_Helper::compute_border_node_ids(), libMesh::Nemesis_IO_Helper::compute_communication_map_parameters(), libMesh::Nemesis_IO_Helper::compute_internal_and_border_elems_and_internal_nodes(), libMesh::Nemesis_IO_Helper::compute_node_communication_maps(), libMesh::Nemesis_IO_Helper::compute_num_global_elem_blocks(), libMesh::Nemesis_IO_Helper::compute_num_global_nodesets(), libMesh::Nemesis_IO_Helper::compute_num_global_sidesets(), libMesh::Nemesis_IO_Helper::construct_nemesis_filename(), libMesh::MeshTools::correct_node_proc_ids(), libMesh::ExodusII_IO_Helper::create(), libMesh::DistributedMesh::delete_elem(), libMesh::DistributedMesh::delete_node(), libMesh::MeshCommunication::delete_remote_elements(), libMesh::DofMap::distribute_dofs(), libMesh::DofMap::distribute_local_dofs_node_major(), libMesh::DofMap::distribute_local_dofs_var_major(), libMesh::DistributedMesh::DistributedMesh(), libMesh::EnsightIO::EnsightIO(), libMesh::MeshFunction::find_element(), libMesh::MeshFunction::find_elements(), libMesh::UnstructuredMesh::find_neighbors(), libMesh::MeshCommunication::gather(), libMesh::MeshCommunication::gather_neighboring_elements(), libMesh::Nemesis_IO_Helper::get_cmap_params(), libMesh::Nemesis_IO_Helper::get_eb_info_global(), libMesh::Nemesis_IO_Helper::get_elem_cmap(), libMesh::Nemesis_IO_Helper::get_elem_map(), libMesh::MeshBase::get_info(), libMesh::DofMap::get_info(), libMesh::Nemesis_IO_Helper::get_init_global(), libMesh::Nemesis_IO_Helper::get_init_info(), libMesh::Nemesis_IO_Helper::get_loadbal_param(), libMesh::Nemesis_IO_Helper::get_node_cmap(), libMesh::Nemesis_IO_Helper::get_node_map(), libMesh::Nemesis_IO_Helper::get_ns_param_global(), libMesh::EquationSystems::get_solution(), libMesh::Nemesis_IO_Helper::get_ss_param_global(), libMesh::SparsityPattern::Build::handle_vi_vj(), libMesh::DistributedVector< T >::init(), libMesh::SystemSubsetBySubdomain::init(), libMesh::ParmetisPartitioner::initialize(), libMesh::ExodusII_IO_Helper::initialize(), libMesh::ExodusII_IO_Helper::initialize_element_variables(), libMesh::ExodusII_IO_Helper::initialize_global_variables(), libMesh::ExodusII_IO_Helper::initialize_nodal_variables(), libMesh::DistributedMesh::insert_elem(), libMesh::DofMap::is_evaluable(), libMesh::SparsityPattern::Build::join(), libMesh::MeshTools::libmesh_assert_parallel_consistent_procids< Elem >(), libMesh::MeshTools::libmesh_assert_parallel_consistent_procids< Node >(), libMesh::MeshTools::libmesh_assert_valid_neighbors(), libMesh::DistributedMesh::libmesh_assert_valid_parallel_object_ids(), libMesh::DofMap::local_variable_indices(), libMesh::MeshRefinement::make_coarsening_compatible(), libMesh::MeshBase::n_active_local_elem(), libMesh::BoundaryInfo::n_boundary_conds(), libMesh::BoundaryInfo::n_edge_conds(), libMesh::System::n_local_dofs(), libMesh::MeshBase::n_local_elem(), libMesh::MeshBase::n_local_nodes(), libMesh::BoundaryInfo::n_nodeset_conds(), libMesh::BoundaryInfo::n_shellface_conds(), libMesh::WeightedPatchRecoveryErrorEstimator::EstimateError::operator()(), libMesh::SparsityPattern::Build::operator()(), libMesh::PatchRecoveryErrorEstimator::EstimateError::operator()(), libMesh::SparsityPattern::Build::parallel_sync(), libMesh::MetisPartitioner::partition_range(), libMesh::System::point_gradient(), libMesh::System::point_hessian(), libMesh::System::point_value(), libMesh::SparseMatrix< T >::print(), libMesh::NumericVector< T >::print_global(), libMesh::Nemesis_IO_Helper::put_cmap_params(), libMesh::Nemesis_IO_Helper::put_elem_cmap(), libMesh::Nemesis_IO_Helper::put_elem_map(), libMesh::Nemesis_IO_Helper::put_loadbal_param(), libMesh::Nemesis_IO_Helper::put_node_cmap(), libMesh::Nemesis_IO_Helper::put_node_map(), libMesh::NameBasedIO::read(), libMesh::Nemesis_IO::read(), libMesh::XdrIO::read(), libMesh::CheckpointIO::read(), libMesh::ExodusII_IO_Helper::read_elem_num_map(), libMesh::ExodusII_IO_Helper::read_global_values(), libMesh::CheckpointIO::read_header(), libMesh::XdrIO::read_header(), libMesh::ExodusII_IO_Helper::read_node_num_map(), libMesh::XdrIO::read_serialized_bc_names(), libMesh::XdrIO::read_serialized_bcs_helper(), libMesh::XdrIO::read_serialized_connectivity(), libMesh::XdrIO::read_serialized_nodes(), libMesh::XdrIO::read_serialized_nodesets(), libMesh::XdrIO::read_serialized_subdomain_names(), libMesh::MeshCommunication::redistribute(), libMesh::DistributedMesh::renumber_dof_objects(), libMesh::CheckpointIO::select_split_config(), libMesh::MeshCommunication::send_coarse_ghosts(), libMesh::Partitioner::set_node_processor_ids(), libMesh::DofMap::set_nonlocal_dof_objects(), libMesh::LaplaceMeshSmoother::smooth(), libMesh::MeshTools::total_weight(), libMesh::MeshRefinement::uniformly_coarsen(), libMesh::Parallel::Packing< Node * >::unpack(), libMesh::Parallel::Packing< Elem * >::unpack(), libMesh::DistributedMesh::update_parallel_id_counts(), libMesh::MeshTools::weight(), libMesh::NameBasedIO::write(), libMesh::XdrIO::write(), libMesh::CheckpointIO::write(), libMesh::EquationSystems::write(), libMesh::GMVIO::write_discontinuous_gmv(), libMesh::ExodusII_IO::write_element_data(), libMesh::ExodusII_IO_Helper::write_element_values(), libMesh::ExodusII_IO_Helper::write_elements(), libMesh::ExodusII_IO::write_global_data(), libMesh::ExodusII_IO_Helper::write_global_values(), libMesh::ExodusII_IO::write_information_records(), libMesh::ExodusII_IO_Helper::write_information_records(), libMesh::ExodusII_IO_Helper::write_nodal_coordinates(), libMesh::UCDIO::write_nodal_data(), libMesh::ExodusII_IO::write_nodal_data(), libMesh::ExodusII_IO::write_nodal_data_discontinuous(), libMesh::ExodusII_IO_Helper::write_nodal_values(), libMesh::Nemesis_IO_Helper::write_nodesets(), libMesh::ExodusII_IO_Helper::write_nodesets(), libMesh::XdrIO::write_serialized_bc_names(), libMesh::XdrIO::write_serialized_bcs_helper(), libMesh::XdrIO::write_serialized_connectivity(), libMesh::XdrIO::write_serialized_nodes(), libMesh::XdrIO::write_serialized_nodesets(), libMesh::XdrIO::write_serialized_subdomain_names(), libMesh::Nemesis_IO_Helper::write_sidesets(), libMesh::ExodusII_IO_Helper::write_sidesets(), libMesh::ExodusII_IO::write_timestep(), libMesh::ExodusII_IO_Helper::write_timestep(), and libMesh::ExodusII_IO::write_timestep_discontinuous().
   { return cast_int<processor_id_type>(_communicator.rank()); }
template<typename T > void libMesh::PetscVector< T >::reciprocal () virtual
Computes the pointwise reciprocal,
Implements libMesh::NumericVector< T >.
Definition at line 156 of file petsc_vector.C.
References ierr.
 {
   PetscErrorCode ierr = 0;
   // VecReciprocal has been in PETSc since at least 2.3.3 days
   ierr = VecReciprocal(_vec);
   LIBMESH_CHKERR(ierr);
 }
template<typename T > void libMesh::PetscVector< T >::restore_array () inline
Restore the data array.
Note
This MUST be called after get_array() or get_array_read() and before using any other interface functions on PetscVector.
Definition at line 1128 of file petsc_vector.h.
References libMesh::PetscVector< T >::_restore_array(), and libMesh::PetscVector< T >::_values_manually_retrieved.
 {
   // \note \p _values_manually_retrieved needs to be set to \p false
   // \e before calling \p _restore_array()!
   _values_manually_retrieved = false;
   _restore_array();
 }
template<typename T > void libMesh::PetscVector< T >::scale (const T factor) virtual
Scale each element of the vector by the given factor.
Implements libMesh::NumericVector< T >.
Definition at line 399 of file petsc_vector.C.
References libMesh::GHOSTED, and ierr.
 {
   this->_restore_array();
   PetscErrorCode ierr = 0;
   PetscScalar factor = static_cast<PetscScalar>(factor_in);
   if (this->type() != GHOSTED)
     {
       ierr = VecScale(_vec, factor);
       LIBMESH_CHKERR(ierr);
     }
   else
     {
       Vec loc_vec;
       ierr = VecGhostGetLocalForm (_vec,&loc_vec);
       LIBMESH_CHKERR(ierr);
       ierr = VecScale(loc_vec, factor);
       LIBMESH_CHKERR(ierr);
       ierr = VecGhostRestoreLocalForm (_vec,&loc_vec);
       LIBMESH_CHKERR(ierr);
     }
 }
template<typename T > void libMesh::PetscVector< T >::set (const numeric_index_type i, const T value) virtual
Sets v(i) = value.
Implements libMesh::NumericVector< T >.
Definition at line 138 of file petsc_vector.C.
References ierr, and value.
 {
   this->_restore_array();
   libmesh_assert_less (i, size());
   PetscErrorCode ierr=0;
   PetscInt i_val = static_cast<PetscInt>(i);
   PetscScalar petsc_value = static_cast<PetscScalar>(value);
   ierr = VecSetValues (_vec, 1, &i_val, &petsc_value, INSERT_VALUES);
   LIBMESH_CHKERR(ierr);
   this->_is_closed = false;
 }
template<typename T > numeric_index_type libMesh::PetscVector< T >::size () const inline virtual
Returns
The size of the vector.
Implements libMesh::NumericVector< T >.
Definition at line 919 of file petsc_vector.h.
References libMesh::PetscVector< T >::_vec, ierr, and libMesh::NumericVector< T >::initialized().
Referenced by libMesh::PetscVector< T >::add(), libMesh::PetscVector< T >::localize(), and libMesh::PetscVector< T >::operator=().
 {
   libmesh_assert (this->initialized());
   PetscErrorCode ierr=0;
   PetscInt petsc_size=0;
   if (!this->initialized())
     return 0;
   ierr = VecGetSize(_vec, &petsc_size);
   LIBMESH_CHKERR(ierr);
   return static_cast<numeric_index_type>(petsc_size);
 }
template<class T > Real libMesh::NumericVector< T >::subset_l1_norm (const std::set< numeric_index_type > & indices) const virtual inherited
Returns
The -norm of the vector, i.e. the sum of the absolute values for the specified entries in the vector.
Note
The indices must necessarily live on this processor.
Definition at line 323 of file numeric_vector.C.
References std::abs(), and libMesh::Real.
Referenced by libMesh::NumericVector< Number >::closed(), and libMesh::System::discrete_var_norm().
 {
   const NumericVector<T> & v = *this;
   std::set<numeric_index_type>::const_iterator it = indices.begin();
   const std::set<numeric_index_type>::const_iterator it_end = indices.end();
   Real norm = 0;
   for (; it!=it_end; ++it)
     norm += std::abs(v(*it));
   this->comm().sum(norm);
   return norm;
 }
template<class T > Real libMesh::NumericVector< T >::subset_l2_norm (const std::set< numeric_index_type > & indices) const virtual inherited
Returns
The -norm of the vector, i.e. the square root of the sum of the squares of the elements for the specified entries in the vector.
Note
The indices must necessarily live on this processor.
Definition at line 341 of file numeric_vector.C.
References libMesh::TensorTools::norm_sq(), and libMesh::Real.
Referenced by libMesh::NumericVector< Number >::closed(), and libMesh::System::discrete_var_norm().
 {
   const NumericVector<T> & v = *this;
   std::set<numeric_index_type>::const_iterator it = indices.begin();
   const std::set<numeric_index_type>::const_iterator it_end = indices.end();
   Real norm = 0;
   for (; it!=it_end; ++it)
     norm += TensorTools::norm_sq(v(*it));
   this->comm().sum(norm);
   return std::sqrt(norm);
 }
template<class T > Real libMesh::NumericVector< T >::subset_linfty_norm (const std::set< numeric_index_type > & indices) const virtual inherited
Returns
The maximum absolute value of the specified entries of this vector, which is the -norm of a vector.
Note
The indices must necessarily live on this processor.
Definition at line 359 of file numeric_vector.C.
References std::abs(), libMesh::Real, and value.
Referenced by libMesh::NumericVector< Number >::closed(), and libMesh::System::discrete_var_norm().
 {
   const NumericVector<T> & v = *this;
   std::set<numeric_index_type>::const_iterator it = indices.begin();
   const std::set<numeric_index_type>::const_iterator it_end = indices.end();
   Real norm = 0;
   for (; it!=it_end; ++it)
     {
       Real value = std::abs(v(*it));
       if (value > norm)
         norm = value;
     }
   this->comm().max(norm);
   return norm;
 }
template<typename T > T libMesh::PetscVector< T >::sum () const virtual
Returns
The sum of all values in the vector.
Implements libMesh::NumericVector< T >.
Definition at line 41 of file petsc_vector.C.
References libMesh::closed(), ierr, and value.
 {
   this->_restore_array();
   libmesh_assert(this->closed());
   PetscErrorCode ierr=0;
   PetscScalar value=0.;
   ierr = VecSum (_vec, &value);
   LIBMESH_CHKERR(ierr);
   return static_cast<T>(value);
 }
template<typename T > void libMesh::PetscVector< T >::swap (NumericVector< T > & v) inline virtual
Swaps the contents of this with v. There should be enough indirection in subclasses to make this an O(1) header-swap operation.
Reimplemented from libMesh::NumericVector< T >.
Definition at line 1180 of file petsc_vector.h.
References libMesh::PetscVector< T >::_array_is_present, libMesh::PetscVector< T >::_destroy_vec_on_exit, libMesh::PetscVector< T >::_global_to_local_map, libMesh::PetscVector< T >::_local_form, libMesh::PetscVector< T >::_values, libMesh::PetscVector< T >::_vec, swap(), and libMesh::NumericVector< T >::swap().
Referenced by libMesh::__libmesh_petsc_diff_solver_residual(), libMesh::__libmesh_petsc_snes_jacobian(), libMesh::__libmesh_petsc_snes_postcheck(), libMesh::__libmesh_tao_equality_constraints(), libMesh::__libmesh_tao_equality_constraints_jacobian(), libMesh::__libmesh_tao_gradient(), libMesh::__libmesh_tao_hessian(), libMesh::__libmesh_tao_inequality_constraints(), libMesh::__libmesh_tao_inequality_constraints_jacobian(), libMesh::__libmesh_tao_objective(), DMlibMeshFunction(), DMlibMeshJacobian(), and libMesh::libmesh_petsc_snes_residual_helper().
 {
   parallel_object_only();
   NumericVector<T>::swap(other);
   PetscVector<T> & v = cast_ref<PetscVector<T> &>(other);
   std::swap(_vec, v._vec);
   std::swap(_destroy_vec_on_exit, v._destroy_vec_on_exit);
   std::swap(_global_to_local_map, v._global_to_local_map);
 #ifdef LIBMESH_HAVE_CXX11_THREAD
   // Only truly atomic for v... but swap() doesn't really need to be thread safe!
   _array_is_present = v._array_is_present.exchange(_array_is_present);
 #else
   std::swap(_array_is_present, v._array_is_present);
 #endif
   std::swap(_local_form, v._local_form);
   std::swap(_values, v._values);
 }
template<typename T> ParallelType libMesh::NumericVector< T >::type () const inline inherited
Returns
The type (SERIAL, PARALLEL, GHOSTED) of the vector.
Definition at line 143 of file numeric_vector.h.
Referenced by libMesh::PetscVector< T >::clone(), libMesh::PetscVector< T >::close(), libMesh::DofMap::enforce_adjoint_constraints_exactly(), libMesh::DofMap::enforce_constraints_exactly(), libMesh::EpetraVector< T >::EpetraVector(), libMesh::MeshFunction::find_element(), libMesh::MeshFunction::find_elements(), libMesh::PetscVector< T >::get(), libMesh::DistributedVector< T >::init(), libMesh::EigenSparseVector< T >::init(), libMesh::LaspackVector< T >::init(), libMesh::EpetraVector< T >::init(), libMesh::PetscVector< T >::localize(), libMesh::PetscVector< T >::operator()(), libMesh::PetscVector< T >::operator=(), libMesh::System::project_vector(), libMesh::System::read_serialized_vector(), libMesh::PetscVector< T >::zero(), and libMesh::PetscVector< T >::zero_clone().
 { return _type; }
template<typename T> ParallelType& libMesh::NumericVector< T >::type () inline inherited
Returns
The type (SERIAL, PARALLEL, GHOSTED) of the vector.
Definition at line 148 of file numeric_vector.h.
 { return _type; }
template<typename T> Vec libMesh::PetscVector< T >::vec () inline
Returns
The raw PETSc Vec pointer.
Note
This is generally not required in user-level code.
Don't do anything crazy like calling LibMeshVecDestroy() on it, or very bad things will likely happen!
Definition at line 322 of file petsc_vector.h.
References libMesh::PetscVector< T >::_vec.
Referenced by libMesh::PetscPreconditioner< T >::apply(), libMesh::SlepcEigenSolver< T >::attach_deflation_space(), libMesh::PetscNonlinearSolver< T >::build_mat_null_space(), DMCreateGlobalVector_libMesh(), libMesh::PetscMatrix< T >::get_diagonal(), libMesh::TaoOptimizationSolver< T >::get_dual_variables(), libMesh::SlepcEigenSolver< T >::get_eigenpair(), libMesh::SlepcEigenSolver< T >::set_initial_space(), libMesh::PetscDiffSolver::solve(), and libMesh::PetscLinearSolver< T >::solve().
 { libmesh_assert (_vec); return _vec; }
template<typename T > void libMesh::PetscVector< T >::zero () inline virtual
Set all entries to zero. Equivalent to v = 0, but more obvious and faster.
Implements libMesh::NumericVector< T >.
Definition at line 859 of file petsc_vector.h.
References libMesh::PetscVector< T >::_restore_array(), libMesh::PetscVector< T >::_vec, libMesh::NumericVector< T >::closed(), libMesh::GHOSTED, ierr, and libMesh::NumericVector< T >::type().
Referenced by libMesh::__libmesh_petsc_snes_fd_residual(), libMesh::__libmesh_petsc_snes_mffd_residual(), libMesh::__libmesh_petsc_snes_residual(), libMesh::__libmesh_tao_equality_constraints(), libMesh::__libmesh_tao_gradient(), libMesh::__libmesh_tao_inequality_constraints(), libMesh::PetscVector< T >::init(), and libMesh::TaoOptimizationSolver< T >::solve().
 {
   parallel_object_only();
   libmesh_assert(this->closed());
   this->_restore_array();
   PetscErrorCode ierr=0;
   PetscScalar z=0.;
   if (this->type() != GHOSTED)
     {
       ierr = VecSet (_vec, z);
       LIBMESH_CHKERR(ierr);
     }
   else
     {
       /* Vectors that include ghost values require a special
          handling.  */
       Vec loc_vec;
       ierr = VecGhostGetLocalForm (_vec,&loc_vec);
       LIBMESH_CHKERR(ierr);
       ierr = VecSet (loc_vec, z);
       LIBMESH_CHKERR(ierr);
       ierr = VecGhostRestoreLocalForm (_vec,&loc_vec);
       LIBMESH_CHKERR(ierr);
     }
 }
template<typename T > std::unique_ptr< NumericVector< T > > libMesh::PetscVector< T >::zero_clone () const inline virtual
Returns
A smart pointer to a copy of this vector with the same type, size, and partitioning, but with all zero entries.
Note
This must be overridden in the derived classes.
Implements libMesh::NumericVector< T >.
Definition at line 896 of file petsc_vector.h.
References libMesh::ParallelObject::comm(), libMesh::NumericVector< T >::init(), and libMesh::NumericVector< T >::type().
 {
   NumericVector<T> * cloned_vector = new PetscVector<T>(this->comm(), this->type());
   cloned_vector->init(*this);
   return std::unique_ptr<NumericVector<T>>(cloned_vector);
 }
Member Data Documentation
template<typename T> std::atomic<bool> libMesh::PetscVector< T >::_array_is_present mutable private
If true, the actual PETSc array of the values of the vector is currently accessible. That means that the members _local_form and _values are valid.
Definition at line 339 of file petsc_vector.h.
Referenced by libMesh::PetscVector< T >::first_local_index(), libMesh::PetscVector< T >::last_local_index(), libMesh::PetscVector< T >::map_global_to_local_index(), libMesh::PetscVector< T >::PetscVector(), and libMesh::PetscVector< T >::swap().
template<typename T> bool libMesh::PetscVector< T >::_array_is_present mutable private
Definition at line 341 of file petsc_vector.h.
const Parallel::Communicator& libMesh::ParallelObject::_communicator protected inherited
Definition at line 105 of file parallel_object.h.
Referenced by libMesh::EquationSystems::build_parallel_solution_vector(), libMesh::ParallelObject::comm(), libMesh::EquationSystems::get_solution(), libMesh::ParallelObject::n_processors(), libMesh::ParallelObject::operator=(), and libMesh::ParallelObject::processor_id().
ReferenceCounter::Counts libMesh::ReferenceCounter::_counts static protected inherited
Actually holds the data.
Definition at line 124 of file reference_counter.h.
Referenced by libMesh::ReferenceCounter::get_info(), libMesh::ReferenceCounter::increment_constructor_count(), and libMesh::ReferenceCounter::increment_destructor_count().
template<typename T> bool libMesh::PetscVector< T >::_destroy_vec_on_exit private
This boolean value should only be set to false for the constructor which takes a PETSc Vec object.
Definition at line 430 of file petsc_vector.h.
Referenced by libMesh::PetscVector< T >::clear(), libMesh::PetscVector< T >::PetscVector(), and libMesh::PetscVector< T >::swap().
bool libMesh::ReferenceCounter::_enable_print_counter = true static protected inherited
Flag to control whether reference count information is printed when print_info is called.
Definition at line 143 of file reference_counter.h.
Referenced by libMesh::ReferenceCounter::disable_print_counter_info(), libMesh::ReferenceCounter::enable_print_counter_info(), and libMesh::ReferenceCounter::print_info().
template<typename T> numeric_index_type libMesh::PetscVector< T >::_first mutable private
First local index.
Only valid when _array_is_present
Definition at line 349 of file petsc_vector.h.
Referenced by libMesh::PetscVector< T >::first_local_index(), and libMesh::PetscVector< T >::map_global_to_local_index().
template<typename T> GlobalToLocalMap libMesh::PetscVector< T >::_global_to_local_map private
Map that maps global to local ghost cells (will be empty if not in ghost cell mode).
Definition at line 424 of file petsc_vector.h.
Referenced by libMesh::PetscVector< T >::clear(), libMesh::PetscVector< T >::init(), libMesh::PetscVector< T >::map_global_to_local_index(), libMesh::PetscVector< T >::PetscVector(), and libMesh::PetscVector< T >::swap().
template<typename T> bool libMesh::NumericVector< T >::_is_closed protected inherited
Flag which tracks whether the vector's values are consistent on all processors after insertion or addition of values has occurred on some or all processors.
Definition at line 708 of file numeric_vector.h.
Referenced by libMesh::EigenSparseVector< T >::add(), libMesh::LaspackVector< T >::add(), libMesh::DistributedVector< T >::clear(), libMesh::LaspackVector< T >::clear(), libMesh::EigenSparseVector< T >::clear(), libMesh::EpetraVector< T >::clear(), libMesh::PetscVector< T >::clear(), libMesh::NumericVector< T >::clear(), libMesh::DistributedVector< T >::close(), libMesh::LaspackVector< T >::close(), libMesh::EigenSparseVector< T >::close(), libMesh::EpetraVector< T >::close(), libMesh::PetscVector< T >::close(), libMesh::NumericVector< Number >::closed(), libMesh::EpetraVector< T >::EpetraVector(), libMesh::EigenSparseVector< T >::init(), libMesh::EpetraVector< T >::init(), libMesh::PetscVector< T >::init(), libMesh::DistributedVector< T >::localize(), libMesh::DistributedVector< T >::operator=(), libMesh::PetscVector< T >::PetscVector(), libMesh::EigenSparseVector< T >::set(), libMesh::LaspackVector< T >::set(), libMesh::EigenSparseVector< T >::swap(), libMesh::NumericVector< T >::swap(), and libMesh::LaspackVector< T >::~LaspackVector().
template<typename T> bool libMesh::NumericVector< T >::_is_initialized protected inherited
true once init() has been called.
Definition at line 713 of file numeric_vector.h.
Referenced by libMesh::DistributedVector< T >::clear(), libMesh::LaspackVector< T >::clear(), libMesh::EigenSparseVector< T >::clear(), libMesh::EpetraVector< T >::clear(), libMesh::PetscVector< T >::clear(), libMesh::NumericVector< T >::clear(), libMesh::PetscVector< T >::create_subvector(), libMesh::EpetraVector< T >::EpetraVector(), libMesh::DistributedVector< T >::init(), libMesh::EigenSparseVector< T >::init(), libMesh::EpetraVector< T >::init(), libMesh::PetscVector< T >::init(), libMesh::NumericVector< Number >::initialized(), libMesh::DistributedVector< T >::localize(), libMesh::DistributedVector< T >::operator=(), libMesh::PetscVector< T >::PetscVector(), libMesh::EigenSparseVector< T >::swap(), libMesh::NumericVector< T >::swap(), and libMesh::LaspackVector< T >::~LaspackVector().
template<typename T> numeric_index_type libMesh::PetscVector< T >::_last mutable private
Last local index.
Only valid when _array_is_present
Definition at line 356 of file petsc_vector.h.
Referenced by libMesh::PetscVector< T >::last_local_index(), and libMesh::PetscVector< T >::map_global_to_local_index().
template<typename T> Vec libMesh::PetscVector< T >::_local_form mutable private
PETSc vector datatype to hold the local form of a ghosted vector. The contents of this field are only valid if the vector is ghosted and _array_is_present is true.
Definition at line 368 of file petsc_vector.h.
Referenced by libMesh::PetscVector< T >::PetscVector(), and libMesh::PetscVector< T >::swap().
template<typename T> numeric_index_type libMesh::PetscVector< T >::_local_size mutable private
Size of the local values from _get_array()
Definition at line 361 of file petsc_vector.h.
Referenced by libMesh::PetscVector< T >::get(), and libMesh::PetscVector< T >::operator()().
Threads::spin_mutex libMesh::ReferenceCounter::_mutex static protected inherited
Mutual exclusion object to enable thread-safe reference counting.
Definition at line 137 of file reference_counter.h.
Threads::atomic< unsigned int > libMesh::ReferenceCounter::_n_objects static protected inherited
The number of objects. Print the reference count information when the number returns to 0.
Definition at line 132 of file reference_counter.h.
Referenced by libMesh::ReferenceCounter::n_objects(), libMesh::ReferenceCounter::ReferenceCounter(), and libMesh::ReferenceCounter::~ReferenceCounter().
template<typename T> std::mutex libMesh::PetscVector< T >::_petsc_vector_mutex mutable private
Mutex for _get_array and _restore_array. This is part of the object to keep down thread contention when reading frmo multiple PetscVectors simultaneously
Definition at line 396 of file petsc_vector.h.
template<typename T> Threads::spin_mutex libMesh::PetscVector< T >::_petsc_vector_mutex mutable private
Definition at line 398 of file petsc_vector.h.
template<typename T> const PetscScalar* libMesh::PetscVector< T >::_read_only_values mutable private
Pointer to the actual PETSc array of the values of the vector. This pointer is only valid if _array_is_present is true. We're using PETSc's VecGetArrayRead() function, which requires a constant PetscScalar *, but _get_array and _restore_array are const member functions, so _values also needs to be mutable (otherwise it is a "const PetscScalar * const" in that context).
Definition at line 378 of file petsc_vector.h.
Referenced by libMesh::PetscVector< T >::get(), libMesh::PetscVector< T >::get_array_read(), and libMesh::PetscVector< T >::operator()().
template<typename T> ParallelType libMesh::NumericVector< T >::_type protected inherited
Type of vector.
Definition at line 718 of file numeric_vector.h.
Referenced by libMesh::DistributedVector< T >::DistributedVector(), libMesh::EigenSparseVector< T >::EigenSparseVector(), libMesh::EpetraVector< T >::EpetraVector(), libMesh::DistributedVector< T >::init(), libMesh::EigenSparseVector< T >::init(), libMesh::EpetraVector< T >::init(), libMesh::PetscVector< T >::init(), libMesh::LaspackVector< T >::LaspackVector(), libMesh::PetscVector< T >::operator=(), libMesh::PetscVector< T >::PetscVector(), libMesh::EigenSparseVector< T >::swap(), libMesh::NumericVector< T >::swap(), libMesh::NumericVector< Number >::type(), and libMesh::LaspackVector< T >::~LaspackVector().
template<typename T> PetscScalar* libMesh::PetscVector< T >::_values mutable private
Pointer to the actual PETSc array of the values of the vector. This pointer is only valid if _array_is_present is true. We're using PETSc's VecGetArrayRead() function, which requires a constant PetscScalar *, but _get_array and _restore_array are const member functions, so _values also needs to be mutable (otherwise it is a "const PetscScalar * const" in that context).
Definition at line 388 of file petsc_vector.h.
Referenced by libMesh::PetscVector< T >::get_array(), libMesh::PetscVector< T >::PetscVector(), and libMesh::PetscVector< T >::swap().
template<typename T> bool libMesh::PetscVector< T >::_values_manually_retrieved mutable private
Whether or not the data array has been manually retrieved using get_array() or get_array_read()
Definition at line 436 of file petsc_vector.h.
Referenced by libMesh::PetscVector< T >::get_array(), libMesh::PetscVector< T >::get_array_read(), libMesh::PetscVector< T >::PetscVector(), and libMesh::PetscVector< T >::restore_array().
template<typename T> bool libMesh::PetscVector< T >::_values_read_only mutable private
Whether or not the data array is for read only access
Definition at line 441 of file petsc_vector.h.
Referenced by libMesh::PetscVector< T >::PetscVector().
template<typename T> Vec libMesh::PetscVector< T >::_vec private
Actual PETSc vector datatype to hold vector entries.
Definition at line 330 of file petsc_vector.h.
Referenced by libMesh::PetscVector< T >::add(), libMesh::PetscVector< T >::add_vector(), libMesh::PetscVector< T >::add_vector_conjugate_transpose(), libMesh::PetscVector< T >::add_vector_transpose(), libMesh::PetscVector< T >::clear(), libMesh::PetscVector< T >::close(), libMesh::PetscVector< T >::create_subvector(), libMesh::PetscVector< T >::dot(), libMesh::PetscVector< T >::first_local_index(), libMesh::PetscVector< T >::indefinite_dot(), libMesh::PetscVector< T >::init(), libMesh::PetscVector< T >::last_local_index(), libMesh::PetscVector< T >::local_size(), libMesh::PetscVector< T >::localize(), libMesh::PetscVector< T >::map_global_to_local_index(), libMesh::PetscVector< T >::max(), libMesh::PetscVector< T >::min(), libMesh::PetscVector< T >::operator/=(), libMesh::PetscVector< T >::operator=(), libMesh::PetscVector< T >::PetscVector(), libMesh::PetscVector< T >::size(), libMesh::PetscVector< T >::swap(), libMesh::PetscVector< T >::vec(), and libMesh::PetscVector< T >::zero().
The documentation for this class was generated from the following files:
petsc_vector.h
petsc_vector.C