libMesh: libMesh::LaspackLinearSolver< T > Class Template Reference
SomeWebsiteLogo
libMesh::LaspackLinearSolver< T > Class Template Reference
#include <laspack_linear_solver.h>
Public Member Functions
LaspackLinearSolver (const libMesh::Parallel::Communicator &comm)
~LaspackLinearSolver ()
virtual void clear () override
virtual void init (const char *name=nullptr) override
virtual std::pair< unsigned int, Real > solve (SparseMatrix< T > &matrix, NumericVector< T > &solution, NumericVector< T > &rhs, const double tol, const unsigned int m_its) override
virtual std::pair< unsigned int, Real > adjoint_solve (SparseMatrix< T > &matrix, NumericVector< T > &solution, NumericVector< T > &rhs, const double tol, const unsigned int m_its) override
virtual std::pair< unsigned int, Real > solve (SparseMatrix< T > &matrix, SparseMatrix< T > &pc, NumericVector< T > &solution, NumericVector< T > &rhs, const double tol, const unsigned int m_its) override
virtual std::pair< unsigned int, Real > solve (const ShellMatrix< T > &shell_matrix, NumericVector< T > &solution_in, NumericVector< T > &rhs_in, const double tol, const unsigned int m_its) override
virtual std::pair< unsigned int, Real > solve (const ShellMatrix< T > &shell_matrix, const SparseMatrix< T > &precond_matrix, NumericVector< T > &solution_in, NumericVector< T > &rhs_in, const double tol, const unsigned int m_its) override
virtual void print_converged_reason () const override
virtual LinearConvergenceReason get_converged_reason () const override
bool initialized () const
virtual void init_names (const System &)
SolverType solver_type () const
void set_solver_type (const SolverType st)
PreconditionerType preconditioner_type () const
void set_preconditioner_type (const PreconditionerType pct)
void attach_preconditioner (Preconditioner< T > *preconditioner)
virtual void reuse_preconditioner (bool)
bool get_same_preconditioner ()
virtual void restrict_solve_to (const std::vector< unsigned int > *const dofs, const SubsetSolveMode subset_solve_mode=SUBSET_ZERO)
std::pair< unsigned int, Real > solve (SparseMatrix< T > &matrix, SparseMatrix< T > *precond_matrix, NumericVector< T > &, NumericVector< T > &, const double, const unsigned int)
std::pair< unsigned int, Real > solve (const ShellMatrix< T > &matrix, const SparseMatrix< T > *precond_matrix, NumericVector< T > &, NumericVector< T > &, const double, const unsigned int)
void set_solver_configuration (SolverConfiguration &solver_configuration)
const Parallel::Communicator & comm () const
processor_id_type n_processors () const
processor_id_type processor_id () const
Static Public Member Functions
static std::unique_ptr< LinearSolver< T > > build (const libMesh::Parallel::Communicator &comm_in, const SolverPackage solver_package=libMesh::default_solver_package())
static std::string get_info ()
static void print_info (std::ostream &out=libMesh::out)
static unsigned int n_objects ()
static void enable_print_counter_info ()
static void disable_print_counter_info ()
Protected Types
typedef std::map< std::string, std::pair< unsigned int, unsigned int > > Counts
Protected Member Functions
void increment_constructor_count (const std::string &name)
void increment_destructor_count (const std::string &name)
Protected Attributes
SolverType _solver_type
PreconditionerType _preconditioner_type
bool _is_initialized
Preconditioner< T > * _preconditioner
bool same_preconditioner
SolverConfiguration * _solver_configuration
const Parallel::Communicator & _communicator
Static Protected Attributes
static Counts _counts
static Threads::atomic< unsigned int > _n_objects
static Threads::spin_mutex _mutex
static bool _enable_print_counter = true
Private Member Functions
void set_laspack_preconditioner_type ()
Private Attributes
PrecondProcType _precond_type
Detailed Description
template<typename T>
class libMesh::LaspackLinearSolver< T >
This class provides an interface to Laspack iterative solvers that is compatible with the libMesh LinearSolver<>
Author
Benjamin Kirk
Date
2002-2007
Definition at line 50 of file laspack_linear_solver.h.
Member Typedef Documentation
Counts
typedef std::map<std::string, std::pair<unsigned int, unsigned int> > libMesh::ReferenceCounter::Counts protected inherited
Data structure to log the information. The log is identified by the class name.
Definition at line 117 of file reference_counter.h.
Constructor & Destructor Documentation
LaspackLinearSolver()
template<typename T > libMesh::LaspackLinearSolver< T >::LaspackLinearSolver (const libMesh::Parallel::Communicator & comm) inline
Constructor. Initializes Laspack data structures
Definition at line 156 of file laspack_linear_solver.h.
                                                                                      :
   LinearSolver<T>(comm),
   _precond_type (ILUPrecond)
 {
 }
~LaspackLinearSolver()
template<typename T > libMesh::LaspackLinearSolver< T >::~LaspackLinearSolver () inline
Destructor.
Definition at line 166 of file laspack_linear_solver.h.
 {
   this->clear ();
 }
Member Function Documentation
adjoint_solve()
template<typename T > std::pair< unsigned int, Real > libMesh::LaspackLinearSolver< T >::adjoint_solve (SparseMatrix< T > & matrix, NumericVector< T > & solution, NumericVector< T > & rhs, const double tol, const unsigned int m_its) override virtual
Call the Laspack solver to solve A^T x = b
Reimplemented from libMesh::LinearSolver< T >.
Definition at line 284 of file laspack_linear_solver.C.
References libMesh::LaspackMatrix< T >::_QMat, libMesh::BICG, libMesh::BICGSTAB, libMesh::CG, libMesh::CGN, libMesh::CGS, libMesh::LaspackMatrix< T >::close(), libMesh::Utility::enum_to_string(), libMesh::err, libMesh::GMRES, libMesh::TriangleWrapper::init(), libMesh::JACOBI, libMesh::QMR, libMesh::SSOR, and libMesh::LaspackVector< T >::zero().
 {
   LOG_SCOPE("adjoint_solve()", "LaspackLinearSolver");
   this->init ();
   // Make sure the data passed in are really in Laspack types
   LaspackMatrix<T> * matrix   = cast_ptr<LaspackMatrix<T> *>(&matrix_in);
   LaspackVector<T> * solution = cast_ptr<LaspackVector<T> *>(&solution_in);
   LaspackVector<T> * rhs      = cast_ptr<LaspackVector<T> *>(&rhs_in);
   // Zero-out the solution to prevent the solver from exiting in 0
   // iterations (?)
   //TODO:[BSK] Why does Laspack do this?  Comment out this and try ex13...
   solution->zero();
   // Close the matrix and vectors in case this wasn't already done.
   matrix->close ();
   solution->close ();
   rhs->close ();
   // Set the preconditioner type
   this->set_laspack_preconditioner_type ();
   // Set the solver tolerance
   SetRTCAccuracy (tol);
   // Solve the linear system
   switch (this->_solver_type)
     {
       // Conjugate-Gradient
     case CG:
       {
         CGIter (Transp_Q(&matrix->_QMat),
                 &solution->_vec,
                 &rhs->_vec,
                 m_its,
                 _precond_type,
                 1.);
         break;
       }
       // Conjugate-Gradient Normalized
     case CGN:
       {
         CGNIter (Transp_Q(&matrix->_QMat),
                  &solution->_vec,
                  &rhs->_vec,
                  m_its,
                  _precond_type,
                  1.);
         break;
       }
       // Conjugate-Gradient Squared
     case CGS:
       {
         CGSIter (Transp_Q(&matrix->_QMat),
                  &solution->_vec,
                  &rhs->_vec,
                  m_its,
                  _precond_type,
                  1.);
         break;
       }
       // Bi-Conjugate Gradient
     case BICG:
       {
         BiCGIter (Transp_Q(&matrix->_QMat),
                   &solution->_vec,
                   &rhs->_vec,
                   m_its,
                   _precond_type,
                   1.);
         break;
       }
       // Bi-Conjugate Gradient Stabilized
     case BICGSTAB:
       {
         BiCGSTABIter (Transp_Q(&matrix->_QMat),
                       &solution->_vec,
                       &rhs->_vec,
                       m_its,
                       _precond_type,
                       1.);
         break;
       }
       // Quasi-Minimum Residual
     case QMR:
       {
         QMRIter (Transp_Q(&matrix->_QMat),
                  &solution->_vec,
                  &rhs->_vec,
                  m_its,
                  _precond_type,
                  1.);
         break;
       }
       // Symmetric over-relaxation
     case SSOR:
       {
         SSORIter (Transp_Q(&matrix->_QMat),
                   &solution->_vec,
                   &rhs->_vec,
                   m_its,
                   _precond_type,
                   1.);
         break;
       }
       // Jacobi Relaxation
     case JACOBI:
       {
         JacobiIter (Transp_Q(&matrix->_QMat),
                     &solution->_vec,
                     &rhs->_vec,
                     m_its,
                     _precond_type,
                     1.);
         break;
       }
       // Generalized Minimum Residual
     case GMRES:
       {
         SetGMRESRestart (30);
         GMRESIter (Transp_Q(&matrix->_QMat),
                    &solution->_vec,
                    &rhs->_vec,
                    m_its,
                    _precond_type,
                    1.);
         break;
       }
       // Unknown solver, use GMRES
     default:
       {
         libMesh::err << "ERROR:  Unsupported LASPACK Solver: "
                      << Utility::enum_to_string(this->_solver_type) << std::endl
                      << "Continuing with GMRES" << std::endl;
         this->_solver_type = GMRES;
         return this->solve (*matrix,
                             *solution,
                             *rhs,
                             tol,
                             m_its);
       }
     }
   // Check for an error
   if (LASResult() != LASOK)
     {
       WriteLASErrDescr(stdout);
       libmesh_error_msg("Exiting after LASPACK Error!");
     }
   // Get the convergence step # and residual
   return std::make_pair(GetLastNoIter(), GetLastAccuracy());
 }
attach_preconditioner()
template<typename T> void libMesh::LinearSolver< T >::attach_preconditioner (Preconditioner< T > * preconditioner) inherited
Attaches a Preconditioner object to be used
Definition at line 118 of file linear_solver.C.
 {
   if (this->_is_initialized)
     libmesh_error_msg("Preconditioner must be attached before the solver is initialized!");
   _preconditioner_type = SHELL_PRECOND;
   _preconditioner = preconditioner;
 }
build()
template<typename T > std::unique_ptr< LinearSolver< T > > libMesh::LinearSolver< T >::build (const libMesh::Parallel::Communicator & comm_in, const SolverPackage solver_package = libMesh::default_solver_package()) static inherited
Builds a LinearSolver using the linear solver package specified by solver_package
Definition at line 57 of file linear_solver.C.
Referenced by libMesh::ImplicitSystem::get_linear_solver(), and libMesh::TimeSolver::init().
 {
   // Avoid unused parameter warnings when no solver packages are enabled.
   libmesh_ignore(comm);
   // Build the appropriate solver
   switch (solver_package)
     {
 #ifdef LIBMESH_HAVE_LASPACK
     case LASPACK_SOLVERS:
       return libmesh_make_unique<LaspackLinearSolver<T>>(comm);
 #endif
 #ifdef LIBMESH_HAVE_PETSC
     case PETSC_SOLVERS:
       return libmesh_make_unique<PetscLinearSolver<T>>(comm);
 #endif
 #ifdef LIBMESH_TRILINOS_HAVE_AZTECOO
     case TRILINOS_SOLVERS:
       return libmesh_make_unique<AztecLinearSolver<T>>(comm);
 #endif
 #ifdef LIBMESH_HAVE_EIGEN
     case EIGEN_SOLVERS:
       return libmesh_make_unique<EigenSparseLinearSolver<T>>(comm);
 #endif
     default:
       libmesh_error_msg("ERROR:  Unrecognized solver package: " << solver_package);
     }
   return std::unique_ptr<LinearSolver<T>>();
 }
clear()
template<typename T > void libMesh::LaspackLinearSolver< T >::clear () override virtual
Release all memory and clear data structures.
Reimplemented from libMesh::LinearSolver< T >.
Definition at line 81 of file laspack_linear_solver.C.
References libMesh::libMeshPrivateData::_is_initialized, libMesh::GMRES, libMesh::ILU_PRECOND, and libMesh::initialized().
 {
   if (this->initialized())
     {
       this->_is_initialized = false;
       this->_solver_type         = GMRES;
       this->_preconditioner_type = ILU_PRECOND;
     }
 }
comm()
const Parallel::Communicator& libMesh::ParallelObject::comm () const inline inherited
Returns
A reference to the Parallel::Communicator object used by this mesh.
Definition at line 89 of file parallel_object.h.
References libMesh::ParallelObject::_communicator.
Referenced by libMesh::__libmesh_petsc_diff_solver_jacobian(), libMesh::__libmesh_petsc_diff_solver_monitor(), libMesh::__libmesh_petsc_diff_solver_residual(), libMesh::__libmesh_tao_equality_constraints(), libMesh::__libmesh_tao_equality_constraints_jacobian(), libMesh::__libmesh_tao_gradient(), libMesh::__libmesh_tao_hessian(), libMesh::__libmesh_tao_inequality_constraints(), libMesh::__libmesh_tao_inequality_constraints_jacobian(), libMesh::__libmesh_tao_objective(), libMesh::MeshRefinement::_coarsen_elements(), libMesh::ExactSolution::_compute_error(), libMesh::UniformRefinementEstimator::_estimate_error(), libMesh::BoundaryInfo::_find_id_maps(), libMesh::SlepcEigenSolver< T >::_petsc_shell_matrix_get_diagonal(), libMesh::PetscLinearSolver< T >::_petsc_shell_matrix_get_diagonal(), libMesh::SlepcEigenSolver< T >::_petsc_shell_matrix_mult(), libMesh::PetscLinearSolver< T >::_petsc_shell_matrix_mult(), libMesh::PetscLinearSolver< T >::_petsc_shell_matrix_mult_add(), libMesh::EquationSystems::_read_impl(), libMesh::MeshRefinement::_refine_elements(), libMesh::MeshRefinement::_smooth_flags(), libMesh::PetscDMWrapper::add_dofs_helper(), libMesh::PetscDMWrapper::add_dofs_to_section(), libMesh::ImplicitSystem::add_matrix(), libMesh::System::add_vector(), libMesh::UnstructuredMesh::all_second_order(), libMesh::MeshTools::Modification::all_tri(), libMesh::LaplaceMeshSmoother::allgather_graph(), libMesh::FEMSystem::assemble_qoi(), libMesh::MeshCommunication::assign_global_indices(), libMesh::DofMap::attach_matrix(), libMesh::MeshTools::Generation::build_extrusion(), libMesh::BoundaryInfo::build_node_list_from_side_list(), libMesh::EquationSystems::build_parallel_elemental_solution_vector(), libMesh::EquationSystems::build_parallel_solution_vector(), libMesh::PetscDMWrapper::build_section(), libMesh::PetscDMWrapper::build_sf(), libMesh::MeshBase::cache_elem_dims(), libMesh::System::calculate_norm(), libMesh::DofMap::check_dirichlet_bcid_consistency(), libMesh::PetscDMWrapper::check_section_n_dofs(), libMesh::Nemesis_IO_Helper::compute_num_global_elem_blocks(), libMesh::Nemesis_IO_Helper::compute_num_global_nodesets(), libMesh::Nemesis_IO_Helper::compute_num_global_sidesets(), libMesh::Problem_Interface::computeF(), libMesh::Problem_Interface::computeJacobian(), libMesh::Problem_Interface::computePreconditioner(), libMesh::ExodusII_IO::copy_elemental_solution(), libMesh::MeshTools::correct_node_proc_ids(), libMesh::MeshTools::create_bounding_box(), libMesh::MeshTools::create_nodal_bounding_box(), libMesh::MeshRefinement::create_parent_error_vector(), libMesh::MeshTools::create_processor_bounding_box(), libMesh::MeshTools::create_subdomain_bounding_box(), libMesh::MeshCommunication::delete_remote_elements(), libMesh::DofMap::distribute_dofs(), DMlibMeshFunction(), DMlibMeshJacobian(), DMlibMeshSetSystem_libMesh(), DMVariableBounds_libMesh(), libMesh::MeshRefinement::eliminate_unrefined_patches(), libMesh::EpetraVector< T >::EpetraVector(), libMesh::WeightedPatchRecoveryErrorEstimator::estimate_error(), libMesh::PatchRecoveryErrorEstimator::estimate_error(), libMesh::JumpErrorEstimator::estimate_error(), libMesh::AdjointRefinementEstimator::estimate_error(), libMesh::ExactErrorEstimator::estimate_error(), libMesh::MeshRefinement::flag_elements_by_elem_fraction(), libMesh::MeshRefinement::flag_elements_by_error_fraction(), libMesh::MeshRefinement::flag_elements_by_nelem_target(), libMesh::CondensedEigenSystem::get_eigenpair(), libMesh::DofMap::get_info(), libMesh::ImplicitSystem::get_linear_solver(), libMesh::LocationMap< T >::init(), libMesh::TimeSolver::init(), libMesh::SystemSubsetBySubdomain::init(), libMesh::PetscDMWrapper::init_and_attach_petscdm(), libMesh::EigenSystem::init_data(), libMesh::EigenSystem::init_matrices(), libMesh::OptimizationSystem::initialize_equality_constraints_storage(), libMesh::OptimizationSystem::initialize_inequality_constraints_storage(), libMesh::MeshTools::libmesh_assert_consistent_distributed(), libMesh::MeshTools::libmesh_assert_consistent_distributed_nodes(), libMesh::MeshTools::libmesh_assert_contiguous_dof_ids(), libMesh::MeshTools::libmesh_assert_parallel_consistent_new_node_procids(), libMesh::MeshTools::libmesh_assert_parallel_consistent_procids< Elem >(), libMesh::MeshTools::libmesh_assert_parallel_consistent_procids< Node >(), libMesh::MeshTools::libmesh_assert_topology_consistent_procids< Node >(), libMesh::MeshTools::libmesh_assert_valid_boundary_ids(), libMesh::MeshTools::libmesh_assert_valid_dof_ids(), libMesh::MeshTools::libmesh_assert_valid_neighbors(), libMesh::DistributedMesh::libmesh_assert_valid_parallel_flags(), libMesh::DistributedMesh::libmesh_assert_valid_parallel_object_ids(), libMesh::DistributedMesh::libmesh_assert_valid_parallel_p_levels(), libMesh::MeshTools::libmesh_assert_valid_refinement_flags(), libMesh::MeshTools::libmesh_assert_valid_unique_ids(), libMesh::libmesh_petsc_snes_fd_residual(), libMesh::libmesh_petsc_snes_jacobian(), libMesh::libmesh_petsc_snes_mffd_residual(), libMesh::libmesh_petsc_snes_postcheck(), libMesh::libmesh_petsc_snes_residual(), libMesh::libmesh_petsc_snes_residual_helper(), libMesh::MeshRefinement::limit_level_mismatch_at_edge(), libMesh::MeshRefinement::limit_level_mismatch_at_node(), libMesh::MeshRefinement::limit_overrefined_boundary(), libMesh::MeshRefinement::limit_underrefined_boundary(), libMesh::MeshRefinement::make_coarsening_compatible(), libMesh::MeshCommunication::make_elems_parallel_consistent(), libMesh::MeshRefinement::make_flags_parallel_consistent(), libMesh::MeshCommunication::make_new_node_proc_ids_parallel_consistent(), libMesh::MeshCommunication::make_new_nodes_parallel_consistent(), libMesh::MeshCommunication::make_node_ids_parallel_consistent(), libMesh::MeshCommunication::make_node_proc_ids_parallel_consistent(), libMesh::MeshCommunication::make_node_unique_ids_parallel_consistent(), libMesh::MeshCommunication::make_nodes_parallel_consistent(), libMesh::MeshCommunication::make_p_levels_parallel_consistent(), libMesh::MeshRefinement::make_refinement_compatible(), libMesh::FEMSystem::mesh_position_set(), libMesh::DistributedMesh::n_active_elem(), libMesh::MeshTools::n_active_levels(), libMesh::BoundaryInfo::n_boundary_conds(), libMesh::BoundaryInfo::n_edge_conds(), libMesh::CondensedEigenSystem::n_global_non_condensed_dofs(), libMesh::MeshTools::n_levels(), libMesh::BoundaryInfo::n_nodeset_conds(), libMesh::MeshTools::n_p_levels(), libMesh::BoundaryInfo::n_shellface_conds(), libMesh::DistributedMesh::parallel_max_elem_id(), libMesh::DistributedMesh::parallel_max_node_id(), libMesh::ReplicatedMesh::parallel_max_unique_id(), libMesh::DistributedMesh::parallel_max_unique_id(), libMesh::DistributedMesh::parallel_n_elem(), libMesh::DistributedMesh::parallel_n_nodes(), libMesh::SparsityPattern::Build::parallel_sync(), libMesh::MeshTools::paranoid_n_levels(), libMesh::petsc_auto_fieldsplit(), libMesh::System::point_gradient(), libMesh::System::point_hessian(), libMesh::System::point_value(), libMesh::MeshBase::prepare_for_use(), libMesh::Nemesis_IO::read(), libMesh::XdrIO::read(), libMesh::CheckpointIO::read_header(), libMesh::XdrIO::read_header(), libMesh::System::read_header(), libMesh::System::read_legacy_data(), libMesh::System::read_SCALAR_dofs(), libMesh::XdrIO::read_serialized_bc_names(), libMesh::XdrIO::read_serialized_bcs_helper(), libMesh::System::read_serialized_blocked_dof_objects(), libMesh::XdrIO::read_serialized_connectivity(), libMesh::XdrIO::read_serialized_nodes(), libMesh::XdrIO::read_serialized_nodesets(), libMesh::XdrIO::read_serialized_subdomain_names(), libMesh::System::read_serialized_vector(), libMesh::MeshBase::recalculate_n_partitions(), libMesh::MeshRefinement::refine_and_coarsen_elements(), libMesh::DistributedMesh::renumber_dof_objects(), libMesh::CheckpointIO::select_split_config(), libMesh::DofMap::set_nonlocal_dof_objects(), libMesh::PetscDMWrapper::set_point_range_in_section(), libMesh::PetscDiffSolver::setup_petsc_data(), libMesh::LaplaceMeshSmoother::smooth(), libMesh::split_mesh(), libMesh::MeshBase::subdomain_ids(), libMesh::BoundaryInfo::sync(), libMesh::MeshRefinement::test_level_one(), libMesh::MeshRefinement::test_unflagged(), libMesh::MeshTools::total_weight(), libMesh::MeshRefinement::uniformly_coarsen(), libMesh::NameBasedIO::write(), libMesh::XdrIO::write(), libMesh::System::write_SCALAR_dofs(), libMesh::XdrIO::write_serialized_bcs_helper(), libMesh::System::write_serialized_blocked_dof_objects(), libMesh::XdrIO::write_serialized_connectivity(), libMesh::XdrIO::write_serialized_nodes(), and libMesh::XdrIO::write_serialized_nodesets().
   { return _communicator; }
disable_print_counter_info()
void libMesh::ReferenceCounter::disable_print_counter_info () static inherited
Definition at line 106 of file reference_counter.C.
References libMesh::ReferenceCounter::_enable_print_counter.
Referenced by libMesh::LibMeshInit::LibMeshInit().
 {
   _enable_print_counter = false;
   return;
 }
enable_print_counter_info()
void libMesh::ReferenceCounter::enable_print_counter_info () static inherited
Methods to enable/disable the reference counter output from print_info()
Definition at line 100 of file reference_counter.C.
References libMesh::ReferenceCounter::_enable_print_counter.
 {
   _enable_print_counter = true;
   return;
 }
get_converged_reason()
template<typename T > LinearConvergenceReason libMesh::LaspackLinearSolver< T >::get_converged_reason () const override virtual
Returns
The solver's convergence flag.
Implements libMesh::LinearSolver< T >.
Definition at line 533 of file laspack_linear_solver.C.
References libMesh::CONVERGED_RTOL_NORMAL, and libMesh::DIVERGED_NULL.
 {
   switch (LASResult())
     {
     case LASOK : return CONVERGED_RTOL_NORMAL;
     default    : return DIVERGED_NULL;
     }
 }
get_info()
std::string libMesh::ReferenceCounter::get_info () static inherited
Gets a string containing the reference information.
Definition at line 47 of file reference_counter.C.
References libMesh::ReferenceCounter::_counts, and libMesh::Quality::name().
Referenced by libMesh::ReferenceCounter::print_info().
 {
 #if defined(LIBMESH_ENABLE_REFERENCE_COUNTING) && defined(DEBUG)
   std::ostringstream oss;
   oss << '\n'
       << " ---------------------------------------------------------------------------- \n"
       << "| Reference count information                                                |\n"
       << " ---------------------------------------------------------------------------- \n";
   for (const auto & pr : _counts)
     {
       const std::string name(pr.first);
       const unsigned int creations    = pr.second.first;
       const unsigned int destructions = pr.second.second;
       oss << "| " << name << " reference count information:\n"
           << "|  Creations:    " << creations    << '\n'
           << "|  Destructions: " << destructions << '\n';
     }
   oss << " ---------------------------------------------------------------------------- \n";
   return oss.str();
 #else
   return "";
 #endif
 }
get_same_preconditioner()
template<typename T > bool libMesh::LinearSolver< T >::get_same_preconditioner () inline inherited
Returns
same_preconditioner, which indicates if we reuse the same preconditioner for subsequent solves.
Definition at line 322 of file linear_solver.h.
 {
   return same_preconditioner;
 }
increment_constructor_count()
void libMesh::ReferenceCounter::increment_constructor_count (const std::string & name) inline protected inherited
Increments the construction counter. Should be called in the constructor of any derived class that will be reference counted.
Definition at line 181 of file reference_counter.h.
References libMesh::ReferenceCounter::_counts, libMesh::Quality::name(), and libMesh::Threads::spin_mtx.
Referenced by libMesh::ReferenceCountedObject< RBParametrized >::ReferenceCountedObject().
 {
   Threads::spin_mutex::scoped_lock lock(Threads::spin_mtx);
   std::pair<unsigned int, unsigned int> & p = _counts[name];
   p.first++;
 }
increment_destructor_count()
void libMesh::ReferenceCounter::increment_destructor_count (const std::string & name) inline protected inherited
Increments the destruction counter. Should be called in the destructor of any derived class that will be reference counted.
Definition at line 194 of file reference_counter.h.
References libMesh::ReferenceCounter::_counts, libMesh::Quality::name(), and libMesh::Threads::spin_mtx.
Referenced by libMesh::ReferenceCountedObject< RBParametrized >::~ReferenceCountedObject().
 {
   Threads::spin_mutex::scoped_lock lock(Threads::spin_mtx);
   std::pair<unsigned int, unsigned int> & p = _counts[name];
   p.second++;
 }
init()
template<typename T > void libMesh::LaspackLinearSolver< T >::init (const char * name = nullptr) override virtual
Initialize data structures if not done so already.
Implements libMesh::LinearSolver< T >.
Definition at line 95 of file laspack_linear_solver.C.
References libMesh::libMeshPrivateData::_is_initialized, and libMesh::initialized().
 {
   // Initialize the data structures if not done so already.
   if (!this->initialized())
     {
       this->_is_initialized = true;
     }
   // SetRTCAuxProc (print_iter_accuracy);
 }
init_names()
template<typename T> virtual void libMesh::LinearSolver< T >::init_names (const System &) inline virtual inherited
Apply names to the system to be solved. For most packages this is a no-op; for PETSc this sets an option prefix from the system name and sets field names from the system's variable names.
Since field names are applied to DoF numberings, this method must be called again after any System reinit.
Reimplemented in libMesh::PetscLinearSolver< T >.
Definition at line 117 of file linear_solver.h.
 {}
initialized()
template<typename T> bool libMesh::LinearSolver< T >::initialized () const inline inherited
Returns
true if the data structures are initialized, false otherwise.
Definition at line 96 of file linear_solver.h.
 { return _is_initialized; }
n_objects()
static unsigned int libMesh::ReferenceCounter::n_objects () inline static inherited
Prints the number of outstanding (created, but not yet destroyed) objects.
Definition at line 83 of file reference_counter.h.
References libMesh::ReferenceCounter::_n_objects.
   { return _n_objects; }
n_processors()
processor_id_type libMesh::ParallelObject::n_processors () const inline inherited
Returns
The number of processors in the group.
Definition at line 95 of file parallel_object.h.
References libMesh::ParallelObject::_communicator, and libMesh::Parallel::Communicator::size().
Referenced by libMesh::BoundaryInfo::_find_id_maps(), libMesh::PetscDMWrapper::add_dofs_to_section(), libMesh::DistributedMesh::add_elem(), libMesh::DistributedMesh::add_node(), libMesh::LaplaceMeshSmoother::allgather_graph(), libMesh::FEMSystem::assembly(), libMesh::AztecLinearSolver< T >::AztecLinearSolver(), libMesh::BoundaryInfo::build_node_list_from_side_list(), libMesh::EquationSystems::build_parallel_elemental_solution_vector(), libMesh::DistributedMesh::clear(), libMesh::Nemesis_IO_Helper::compute_border_node_ids(), libMesh::Nemesis_IO_Helper::construct_nemesis_filename(), libMesh::UnstructuredMesh::create_pid_mesh(), libMesh::MeshTools::create_processor_bounding_box(), libMesh::DofMap::distribute_dofs(), libMesh::DofMap::distribute_local_dofs_node_major(), libMesh::DofMap::distribute_local_dofs_var_major(), libMesh::EnsightIO::EnsightIO(), libMesh::MeshBase::get_info(), libMesh::SystemSubsetBySubdomain::init(), libMesh::PetscDMWrapper::init_and_attach_petscdm(), libMesh::Nemesis_IO_Helper::initialize(), libMesh::DistributedMesh::insert_elem(), libMesh::MeshTools::libmesh_assert_contiguous_dof_ids(), libMesh::MeshTools::libmesh_assert_parallel_consistent_new_node_procids(), libMesh::MeshTools::libmesh_assert_parallel_consistent_procids< Elem >(), libMesh::MeshTools::libmesh_assert_parallel_consistent_procids< Node >(), libMesh::MeshTools::libmesh_assert_topology_consistent_procids< Node >(), libMesh::MeshTools::libmesh_assert_valid_boundary_ids(), libMesh::MeshTools::libmesh_assert_valid_dof_ids(), libMesh::MeshTools::libmesh_assert_valid_neighbors(), libMesh::MeshTools::libmesh_assert_valid_refinement_flags(), libMesh::DofMap::local_variable_indices(), libMesh::MeshRefinement::make_coarsening_compatible(), libMesh::MeshBase::n_active_elem_on_proc(), libMesh::MeshBase::n_elem_on_proc(), libMesh::MeshBase::n_nodes_on_proc(), libMesh::MeshBase::partition(), libMesh::PetscLinearSolver< T >::PetscLinearSolver(), libMesh::System::point_gradient(), libMesh::System::point_hessian(), libMesh::System::point_value(), libMesh::NameBasedIO::read(), libMesh::Nemesis_IO::read(), libMesh::CheckpointIO::read(), libMesh::CheckpointIO::read_connectivity(), libMesh::XdrIO::read_header(), libMesh::CheckpointIO::read_nodes(), libMesh::System::read_parallel_data(), libMesh::System::read_SCALAR_dofs(), libMesh::System::read_serialized_blocked_dof_objects(), libMesh::System::read_serialized_vector(), libMesh::DistributedMesh::renumber_dof_objects(), libMesh::DofMap::set_nonlocal_dof_objects(), libMesh::PetscDMWrapper::set_point_range_in_section(), libMesh::MeshRefinement::uniformly_coarsen(), libMesh::DistributedMesh::update_parallel_id_counts(), libMesh::GMVIO::write_binary(), libMesh::GMVIO::write_discontinuous_gmv(), libMesh::System::write_parallel_data(), libMesh::System::write_SCALAR_dofs(), libMesh::XdrIO::write_serialized_bcs_helper(), libMesh::System::write_serialized_blocked_dof_objects(), libMesh::XdrIO::write_serialized_connectivity(), libMesh::XdrIO::write_serialized_nodes(), and libMesh::XdrIO::write_serialized_nodesets().
   { return cast_int<processor_id_type>(_communicator.size()); }
preconditioner_type()
template<typename T > PreconditionerType libMesh::LinearSolver< T >::preconditioner_type () const inherited
Returns
The type of preconditioner to use.
Definition at line 98 of file linear_solver.C.
 {
   if (_preconditioner)
     return _preconditioner->type();
   return _preconditioner_type;
 }
print_converged_reason()
template<typename T > void libMesh::LaspackLinearSolver< T >::print_converged_reason () const override virtual
Prints a useful message about why the latest linear solve con(di)verged.
Reimplemented from libMesh::LinearSolver< T >.
Definition at line 516 of file laspack_linear_solver.C.
References libMesh::out.
 {
   switch (LASResult())
     {
     case LASOK :
       libMesh::out << "Laspack converged.\n";
       break;
     default    :
       libMesh::out << "Laspack diverged.\n";
     }
   libMesh::out << "Detailed reporting is currently only supported"
                << "with Petsc 2.3.1 and later." << std::endl;
 }
print_info()
void libMesh::ReferenceCounter::print_info (std::ostream & out = libMesh::out) static inherited
Prints the reference information, by default to libMesh::out.
Definition at line 87 of file reference_counter.C.
References libMesh::ReferenceCounter::_enable_print_counter, and libMesh::ReferenceCounter::get_info().
 {
   if (_enable_print_counter)
     out_stream << ReferenceCounter::get_info();
 }
processor_id()
processor_id_type libMesh::ParallelObject::processor_id () const inline inherited
Returns
The rank of this processor in the group.
Definition at line 101 of file parallel_object.h.
References libMesh::ParallelObject::_communicator, and libMesh::Parallel::Communicator::rank().
Referenced by libMesh::BoundaryInfo::_find_id_maps(), libMesh::EquationSystems::_read_impl(), libMesh::PetscDMWrapper::add_dofs_to_section(), libMesh::DistributedMesh::add_elem(), libMesh::BoundaryInfo::add_elements(), libMesh::DofMap::add_neighbors_to_send_list(), libMesh::DistributedMesh::add_node(), libMesh::UnstructuredMesh::all_second_order(), libMesh::MeshTools::Modification::all_tri(), libMesh::FEMSystem::assembly(), libMesh::EquationSystems::build_discontinuous_solution_vector(), libMesh::Nemesis_IO_Helper::build_element_and_node_maps(), libMesh::InfElemBuilder::build_inf_elem(), libMesh::BoundaryInfo::build_node_list_from_side_list(), libMesh::EquationSystems::build_parallel_elemental_solution_vector(), libMesh::DistributedMesh::clear(), libMesh::ExodusII_IO_Helper::close(), libMesh::Nemesis_IO_Helper::compute_border_node_ids(), libMesh::Nemesis_IO_Helper::compute_communication_map_parameters(), libMesh::Nemesis_IO_Helper::compute_internal_and_border_elems_and_internal_nodes(), libMesh::Nemesis_IO_Helper::compute_node_communication_maps(), libMesh::Nemesis_IO_Helper::compute_num_global_elem_blocks(), libMesh::Nemesis_IO_Helper::compute_num_global_nodesets(), libMesh::Nemesis_IO_Helper::compute_num_global_sidesets(), libMesh::Nemesis_IO_Helper::construct_nemesis_filename(), libMesh::MeshTools::correct_node_proc_ids(), libMesh::ExodusII_IO_Helper::create(), libMesh::DistributedMesh::delete_elem(), libMesh::DistributedMesh::delete_node(), libMesh::MeshCommunication::delete_remote_elements(), libMesh::DofMap::distribute_dofs(), libMesh::DofMap::distribute_local_dofs_node_major(), libMesh::DofMap::distribute_local_dofs_var_major(), libMesh::DistributedMesh::DistributedMesh(), libMesh::DofMap::end_dof(), libMesh::DofMap::end_old_dof(), libMesh::EnsightIO::EnsightIO(), libMesh::MeshFunction::find_element(), libMesh::MeshFunction::find_elements(), libMesh::UnstructuredMesh::find_neighbors(), libMesh::DofMap::first_dof(), libMesh::DofMap::first_old_dof(), libMesh::Nemesis_IO_Helper::get_cmap_params(), libMesh::Nemesis_IO_Helper::get_eb_info_global(), libMesh::Nemesis_IO_Helper::get_elem_cmap(), libMesh::Nemesis_IO_Helper::get_elem_map(), libMesh::MeshBase::get_info(), libMesh::DofMap::get_info(), libMesh::Nemesis_IO_Helper::get_init_global(), libMesh::Nemesis_IO_Helper::get_init_info(), libMesh::Nemesis_IO_Helper::get_loadbal_param(), libMesh::Nemesis_IO_Helper::get_node_cmap(), libMesh::Nemesis_IO_Helper::get_node_map(), libMesh::Nemesis_IO_Helper::get_ns_param_global(), libMesh::Nemesis_IO_Helper::get_ss_param_global(), libMesh::SparsityPattern::Build::handle_vi_vj(), libMesh::SystemSubsetBySubdomain::init(), libMesh::ExodusII_IO_Helper::initialize(), libMesh::ExodusII_IO_Helper::initialize_element_variables(), libMesh::ExodusII_IO_Helper::initialize_global_variables(), libMesh::ExodusII_IO_Helper::initialize_nodal_variables(), libMesh::DistributedMesh::insert_elem(), libMesh::DofMap::is_evaluable(), libMesh::SparsityPattern::Build::join(), libMesh::DofMap::last_dof(), libMesh::MeshTools::libmesh_assert_consistent_distributed(), libMesh::MeshTools::libmesh_assert_consistent_distributed_nodes(), libMesh::MeshTools::libmesh_assert_contiguous_dof_ids(), libMesh::MeshTools::libmesh_assert_parallel_consistent_procids< Elem >(), libMesh::MeshTools::libmesh_assert_valid_neighbors(), libMesh::DistributedMesh::libmesh_assert_valid_parallel_object_ids(), libMesh::DofMap::local_variable_indices(), libMesh::MeshRefinement::make_coarsening_compatible(), libMesh::MeshBase::n_active_local_elem(), libMesh::BoundaryInfo::n_boundary_conds(), libMesh::BoundaryInfo::n_edge_conds(), libMesh::DofMap::n_local_dofs(), libMesh::System::n_local_dofs(), libMesh::MeshBase::n_local_elem(), libMesh::MeshBase::n_local_nodes(), libMesh::BoundaryInfo::n_nodeset_conds(), libMesh::BoundaryInfo::n_shellface_conds(), libMesh::SparsityPattern::Build::operator()(), libMesh::DistributedMesh::own_node(), libMesh::System::point_gradient(), libMesh::System::point_hessian(), libMesh::System::point_value(), libMesh::Nemesis_IO_Helper::put_cmap_params(), libMesh::Nemesis_IO_Helper::put_elem_cmap(), libMesh::Nemesis_IO_Helper::put_elem_map(), libMesh::Nemesis_IO_Helper::put_loadbal_param(), libMesh::Nemesis_IO_Helper::put_node_cmap(), libMesh::Nemesis_IO_Helper::put_node_map(), libMesh::NameBasedIO::read(), libMesh::Nemesis_IO::read(), libMesh::XdrIO::read(), libMesh::CheckpointIO::read(), libMesh::ExodusII_IO_Helper::read_elem_num_map(), libMesh::ExodusII_IO_Helper::read_global_values(), libMesh::CheckpointIO::read_header(), libMesh::XdrIO::read_header(), libMesh::System::read_header(), libMesh::System::read_legacy_data(), libMesh::ExodusII_IO_Helper::read_node_num_map(), libMesh::System::read_parallel_data(), libMesh::System::read_SCALAR_dofs(), libMesh::XdrIO::read_serialized_bc_names(), libMesh::XdrIO::read_serialized_bcs_helper(), libMesh::System::read_serialized_blocked_dof_objects(), libMesh::XdrIO::read_serialized_connectivity(), libMesh::System::read_serialized_data(), libMesh::XdrIO::read_serialized_nodes(), libMesh::XdrIO::read_serialized_nodesets(), libMesh::XdrIO::read_serialized_subdomain_names(), libMesh::System::read_serialized_vector(), libMesh::System::read_serialized_vectors(), libMesh::DistributedMesh::renumber_dof_objects(), libMesh::CheckpointIO::select_split_config(), libMesh::DofMap::set_nonlocal_dof_objects(), libMesh::PetscDMWrapper::set_point_range_in_section(), libMesh::LaplaceMeshSmoother::smooth(), libMesh::MeshTools::total_weight(), libMesh::MeshRefinement::uniformly_coarsen(), libMesh::Parallel::Packing< T >::unpack(), libMesh::DistributedMesh::update_parallel_id_counts(), libMesh::NameBasedIO::write(), libMesh::XdrIO::write(), libMesh::CheckpointIO::write(), libMesh::EquationSystems::write(), libMesh::GMVIO::write_discontinuous_gmv(), libMesh::ExodusII_IO::write_element_data(), libMesh::ExodusII_IO_Helper::write_element_values(), libMesh::ExodusII_IO_Helper::write_elements(), libMesh::ExodusII_IO::write_global_data(), libMesh::ExodusII_IO_Helper::write_global_values(), libMesh::System::write_header(), libMesh::ExodusII_IO::write_information_records(), libMesh::ExodusII_IO_Helper::write_information_records(), libMesh::ExodusII_IO_Helper::write_nodal_coordinates(), libMesh::UCDIO::write_nodal_data(), libMesh::ExodusII_IO::write_nodal_data(), libMesh::ExodusII_IO::write_nodal_data_discontinuous(), libMesh::ExodusII_IO_Helper::write_nodal_values(), libMesh::Nemesis_IO_Helper::write_nodesets(), libMesh::ExodusII_IO_Helper::write_nodesets(), libMesh::System::write_parallel_data(), libMesh::System::write_SCALAR_dofs(), libMesh::XdrIO::write_serialized_bc_names(), libMesh::XdrIO::write_serialized_bcs_helper(), libMesh::System::write_serialized_blocked_dof_objects(), libMesh::XdrIO::write_serialized_connectivity(), libMesh::System::write_serialized_data(), libMesh::XdrIO::write_serialized_nodes(), libMesh::XdrIO::write_serialized_nodesets(), libMesh::XdrIO::write_serialized_subdomain_names(), libMesh::System::write_serialized_vector(), libMesh::System::write_serialized_vectors(), libMesh::Nemesis_IO_Helper::write_sidesets(), libMesh::ExodusII_IO_Helper::write_sidesets(), libMesh::ExodusII_IO::write_timestep(), libMesh::ExodusII_IO_Helper::write_timestep(), and libMesh::ExodusII_IO::write_timestep_discontinuous().
   { return cast_int<processor_id_type>(_communicator.rank()); }
restrict_solve_to()
template<typename T > void libMesh::LinearSolver< T >::restrict_solve_to (const std::vector< unsigned int > *const dofs, const SubsetSolveMode subset_solve_mode = SUBSET_ZERO) virtual inherited
After calling this method, all successive solves will be restricted to the given set of dofs, which must contain local dofs on each processor only and not contain any duplicates. This mode can be disabled by calling this method with dofs being a nullptr.
Reimplemented in libMesh::PetscLinearSolver< T >.
Definition at line 136 of file linear_solver.C.
 {
   if (dofs != nullptr)
     libmesh_not_implemented();
 }
reuse_preconditioner()
template<typename T > void libMesh::LinearSolver< T >::reuse_preconditioner (bool reuse_flag) virtual inherited
Set the same_preconditioner flag, which indicates if we reuse the same preconditioner for subsequent solves.
Definition at line 129 of file linear_solver.C.
Referenced by libMesh::ImplicitSystem::disable_cache().
 {
   same_preconditioner = reuse_flag;
 }
set_laspack_preconditioner_type()
template<typename T > void libMesh::LaspackLinearSolver< T >::set_laspack_preconditioner_type () private
Tells LASPACK to use the user-specified preconditioner stored in _preconditioner_type
Definition at line 487 of file laspack_linear_solver.C.
References libMesh::err, libMesh::IDENTITY_PRECOND, libMesh::ILU_PRECOND, libMesh::JACOBI_PRECOND, and libMesh::SSOR_PRECOND.
 {
   switch (this->_preconditioner_type)
     {
     case IDENTITY_PRECOND:
       _precond_type = nullptr; return;
     case ILU_PRECOND:
       _precond_type = ILUPrecond; return;
     case JACOBI_PRECOND:
       _precond_type = JacobiPrecond; return;
     case SSOR_PRECOND:
       _precond_type = SSORPrecond; return;
     default:
       libMesh::err << "ERROR:  Unsupported LASPACK Preconditioner: "
                    << this->_preconditioner_type << std::endl
                    << "Continuing with ILU"      << std::endl;
       this->_preconditioner_type = ILU_PRECOND;
       this->set_laspack_preconditioner_type();
     }
 }
set_preconditioner_type()
template<typename T > void libMesh::LinearSolver< T >::set_preconditioner_type (const PreconditionerType pct) inherited
Sets the type of preconditioner to use.
Definition at line 108 of file linear_solver.C.
 {
   if (_preconditioner)
     _preconditioner->set_type(pct);
   else
     _preconditioner_type = pct;
 }
set_solver_configuration()
template<typename T > void libMesh::LinearSolver< T >::set_solver_configuration (SolverConfiguration & solver_configuration) inherited
Set the solver configuration object.
Definition at line 177 of file linear_solver.C.
 {
   _solver_configuration = &solver_configuration;
 }
set_solver_type()
template<typename T> void libMesh::LinearSolver< T >::set_solver_type (const SolverType st) inline inherited
Sets the type of solver to use.
Definition at line 127 of file linear_solver.h.
   { _solver_type = st; }
solve() [1/6]
template<typename T > std::pair< unsigned int, Real > libMesh::LaspackLinearSolver< T >::solve (SparseMatrix< T > & matrix, NumericVector< T > & solution, NumericVector< T > & rhs, const double tol, const unsigned int m_its) override virtual
Call the Laspack solver
Implements libMesh::LinearSolver< T >.
Definition at line 110 of file laspack_linear_solver.C.
References libMesh::LaspackMatrix< T >::_QMat, libMesh::BICG, libMesh::BICGSTAB, libMesh::CG, libMesh::CGN, libMesh::CGS, libMesh::LaspackMatrix< T >::close(), libMesh::Utility::enum_to_string(), libMesh::err, libMesh::GMRES, libMesh::TriangleWrapper::init(), libMesh::JACOBI, libMesh::QMR, libMesh::SSOR, and libMesh::LaspackVector< T >::zero().
 {
   LOG_SCOPE("solve()", "LaspackLinearSolver");
   this->init ();
   // Make sure the data passed in are really in Laspack types
   LaspackMatrix<T> * matrix   = cast_ptr<LaspackMatrix<T> *>(&matrix_in);
   LaspackVector<T> * solution = cast_ptr<LaspackVector<T> *>(&solution_in);
   LaspackVector<T> * rhs      = cast_ptr<LaspackVector<T> *>(&rhs_in);
   // Zero-out the solution to prevent the solver from exiting in 0
   // iterations (?)
   //TODO:[BSK] Why does Laspack do this?  Comment out this and try ex13...
   solution->zero();
   // Close the matrix and vectors in case this wasn't already done.
   matrix->close ();
   solution->close ();
   rhs->close ();
   // Set the preconditioner type
   this->set_laspack_preconditioner_type ();
   // Set the solver tolerance
   SetRTCAccuracy (tol);
   // Solve the linear system
   switch (this->_solver_type)
     {
       // Conjugate-Gradient
     case CG:
       {
         CGIter (&matrix->_QMat,
                 &solution->_vec,
                 &rhs->_vec,
                 m_its,
                 _precond_type,
                 1.);
         break;
       }
       // Conjugate-Gradient Normalized
     case CGN:
       {
         CGNIter (&matrix->_QMat,
                  &solution->_vec,
                  &rhs->_vec,
                  m_its,
                  _precond_type,
                  1.);
         break;
       }
       // Conjugate-Gradient Squared
     case CGS:
       {
         CGSIter (&matrix->_QMat,
                  &solution->_vec,
                  &rhs->_vec,
                  m_its,
                  _precond_type,
                  1.);
         break;
       }
       // Bi-Conjugate Gradient
     case BICG:
       {
         BiCGIter (&matrix->_QMat,
                   &solution->_vec,
                   &rhs->_vec,
                   m_its,
                   _precond_type,
                   1.);
         break;
       }
       // Bi-Conjugate Gradient Stabilized
     case BICGSTAB:
       {
         BiCGSTABIter (&matrix->_QMat,
                       &solution->_vec,
                       &rhs->_vec,
                       m_its,
                       _precond_type,
                       1.);
         break;
       }
       // Quasi-Minimum Residual
     case QMR:
       {
         QMRIter (&matrix->_QMat,
                  &solution->_vec,
                  &rhs->_vec,
                  m_its,
                  _precond_type,
                  1.);
         break;
       }
       // Symmetric over-relaxation
     case SSOR:
       {
         SSORIter (&matrix->_QMat,
                   &solution->_vec,
                   &rhs->_vec,
                   m_its,
                   _precond_type,
                   1.);
         break;
       }
       // Jacobi Relaxation
     case JACOBI:
       {
         JacobiIter (&matrix->_QMat,
                     &solution->_vec,
                     &rhs->_vec,
                     m_its,
                     _precond_type,
                     1.);
         break;
       }
       // Generalized Minimum Residual
     case GMRES:
       {
         SetGMRESRestart (30);
         GMRESIter (&matrix->_QMat,
                    &solution->_vec,
                    &rhs->_vec,
                    m_its,
                    _precond_type,
                    1.);
         break;
       }
       // Unknown solver, use GMRES
     default:
       {
         libMesh::err << "ERROR:  Unsupported LASPACK Solver: "
                      << Utility::enum_to_string(this->_solver_type) << std::endl
                      << "Continuing with GMRES" << std::endl;
         this->_solver_type = GMRES;
         return this->solve (*matrix,
                             *solution,
                             *rhs,
                             tol,
                             m_its);
       }
     }
   // Check for an error
   if (LASResult() != LASOK)
     {
       WriteLASErrDescr(stdout);
       libmesh_error_msg("Exiting after LASPACK Error!");
     }
   // Get the convergence step # and residual
   return std::make_pair(GetLastNoIter(), GetLastAccuracy());
 }
solve() [2/6]
template<typename T > std::pair< unsigned int, Real > libMesh::LaspackLinearSolver< T >::solve (SparseMatrix< T > & matrix, SparseMatrix< T > & pc, NumericVector< T > & solution, NumericVector< T > & rhs, const double tol, const unsigned int m_its) inline override virtual
Call the Laspack solver
Implements libMesh::LinearSolver< T >.
Definition at line 176 of file laspack_linear_solver.h.
 {
   libmesh_error_msg("ERROR: LASPACK does not support a user-supplied preconditioner!");
   std::pair<unsigned int, Real> p;
   return p;
 }
solve() [3/6]
template<typename T > std::pair< unsigned int, Real > libMesh::LaspackLinearSolver< T >::solve (const ShellMatrix< T > & shell_matrix, NumericVector< T > & solution_in, NumericVector< T > & rhs_in, const double tol, const unsigned int m_its) override virtual
This function solves a system whose matrix is a shell matrix.
Implements libMesh::LinearSolver< T >.
Definition at line 459 of file laspack_linear_solver.C.
 {
   libmesh_not_implemented();
   return std::make_pair(0,0.0);
 }
solve() [4/6]
template<typename T > std::pair< unsigned int, Real > libMesh::LaspackLinearSolver< T >::solve (const ShellMatrix< T > & shell_matrix, const SparseMatrix< T > & precond_matrix, NumericVector< T > & solution_in, NumericVector< T > & rhs_in, const double tol, const unsigned int m_its) override virtual
This function solves a system whose matrix is a shell matrix, but a sparse matrix is used as preconditioning matrix, this allowing other preconditioners than JACOBI.
Implements libMesh::LinearSolver< T >.
Definition at line 473 of file laspack_linear_solver.C.
 {
   libmesh_not_implemented();
   return std::make_pair(0,0.0);
 }
solve() [5/6]
template<typename T> std::pair< unsigned int, Real > libMesh::LinearSolver< T >::solve (SparseMatrix< T > & matrix, SparseMatrix< T > * precond_matrix, NumericVector< T > & sol, NumericVector< T > & rhs, const double tol, const unsigned int n_iter) inline inherited
This function calls the solver "_solver_type" preconditioned with the "_preconditioner_type" preconditioner. The preconditioning matrix is used if it is provided, or the system matrix is used if precond_matrix is null
Definition at line 330 of file linear_solver.h.
 {
   if (pc_mat)
     return this->solve(mat, *pc_mat, sol, rhs, tol, n_iter);
   else
     return this->solve(mat, sol, rhs, tol, n_iter);
 }
solve() [6/6]
template<typename T> std::pair< unsigned int, Real > libMesh::LinearSolver< T >::solve (const ShellMatrix< T > & matrix, const SparseMatrix< T > * precond_matrix, NumericVector< T > & sol, NumericVector< T > & rhs, const double tol, const unsigned int n_iter) inline inherited
This function solves a system whose matrix is a shell matrix, but an optional sparse matrix may be used as preconditioning matrix.
Definition at line 347 of file linear_solver.h.
 {
   if (pc_mat)
     return this->solve(mat, *pc_mat, sol, rhs, tol, n_iter);
   else
     return this->solve(mat, sol, rhs, tol, n_iter);
 }
solver_type()
template<typename T> SolverType libMesh::LinearSolver< T >::solver_type () const inline inherited
Returns
The type of solver to use.
Definition at line 122 of file linear_solver.h.
 { return _solver_type; }
Member Data Documentation
_communicator
const Parallel::Communicator& libMesh::ParallelObject::_communicator protected inherited
Definition at line 107 of file parallel_object.h.
Referenced by libMesh::EquationSystems::build_parallel_elemental_solution_vector(), libMesh::EquationSystems::build_parallel_solution_vector(), libMesh::ParallelObject::comm(), libMesh::ParallelObject::n_processors(), libMesh::ParallelObject::operator=(), and libMesh::ParallelObject::processor_id().
_counts
ReferenceCounter::Counts libMesh::ReferenceCounter::_counts static protected inherited
Actually holds the data.
Definition at line 122 of file reference_counter.h.
Referenced by libMesh::ReferenceCounter::get_info(), libMesh::ReferenceCounter::increment_constructor_count(), and libMesh::ReferenceCounter::increment_destructor_count().
_enable_print_counter
bool libMesh::ReferenceCounter::_enable_print_counter = true static protected inherited
Flag to control whether reference count information is printed when print_info is called.
Definition at line 141 of file reference_counter.h.
Referenced by libMesh::ReferenceCounter::disable_print_counter_info(), libMesh::ReferenceCounter::enable_print_counter_info(), and libMesh::ReferenceCounter::print_info().
_is_initialized
template<typename T> bool libMesh::LinearSolver< T >::_is_initialized protected inherited
Flag indicating if the data structures have been initialized.
Definition at line 287 of file linear_solver.h.
Referenced by libMesh::LinearSolver< Number >::initialized().
_mutex
Threads::spin_mutex libMesh::ReferenceCounter::_mutex static protected inherited
Mutual exclusion object to enable thread-safe reference counting.
Definition at line 135 of file reference_counter.h.
_n_objects
Threads::atomic< unsigned int > libMesh::ReferenceCounter::_n_objects static protected inherited
The number of objects. Print the reference count information when the number returns to 0.
Definition at line 130 of file reference_counter.h.
Referenced by libMesh::ReferenceCounter::n_objects(), libMesh::ReferenceCounter::ReferenceCounter(), and libMesh::ReferenceCounter::~ReferenceCounter().
_precond_type
template<typename T > PrecondProcType libMesh::LaspackLinearSolver< T >::_precond_type private
Preconditioner type
Definition at line 149 of file laspack_linear_solver.h.
_preconditioner
template<typename T> Preconditioner<T>* libMesh::LinearSolver< T >::_preconditioner protected inherited
Holds the Preconditioner object to be used for the linear solves.
Definition at line 292 of file linear_solver.h.
_preconditioner_type
template<typename T> PreconditionerType libMesh::LinearSolver< T >::_preconditioner_type protected inherited
Enum stating with type of preconditioner to use.
Definition at line 282 of file linear_solver.h.
Referenced by libMesh::AztecLinearSolver< T >::AztecLinearSolver(), and libMesh::PetscLinearSolver< T >::PetscLinearSolver().
_solver_configuration
template<typename T> SolverConfiguration* libMesh::LinearSolver< T >::_solver_configuration protected inherited
Optionally store a SolverOptions object that can be used to set parameters like solver type, tolerances and iteration limits.
Definition at line 306 of file linear_solver.h.
_solver_type
template<typename T> SolverType libMesh::LinearSolver< T >::_solver_type protected inherited
Enum stating which type of iterative solver to use.
Definition at line 277 of file linear_solver.h.
Referenced by libMesh::EigenSparseLinearSolver< T >::EigenSparseLinearSolver(), libMesh::LinearSolver< Number >::set_solver_type(), and libMesh::LinearSolver< Number >::solver_type().
same_preconditioner
template<typename T> bool libMesh::LinearSolver< T >::same_preconditioner protected inherited
Boolean flag to indicate whether we want to use an identical preconditioner to the previous solve. This can save substantial work in the cases where the system matrix is the same for successive solves.
Definition at line 300 of file linear_solver.h.
The documentation for this class was generated from the following files:
laspack_linear_solver.h
laspack_linear_solver.C