libMesh: libMesh::FEXYZ< Dim > Class Template Reference
SomeWebsiteLogo
libMesh::FEXYZ< Dim > Class Template Reference
#include <fe.h>
Public Types
typedef FEGenericBase< typename FEOutputType< T >::type >::OutputShape OutputShape
typedef TensorTools::IncrementRank< OutputShape >::type OutputGradient
typedef TensorTools::IncrementRank< OutputGradient >::type OutputTensor
typedef TensorTools::DecrementRank< OutputShape >::type OutputDivergence
typedef TensorTools::MakeNumber< OutputShape >::type OutputNumber
typedef TensorTools::IncrementRank< OutputNumber >::type OutputNumberGradient
typedef TensorTools::IncrementRank< OutputNumberGradient >::type OutputNumberTensor
typedef TensorTools::DecrementRank< OutputNumber >::type OutputNumberDivergence
Public Member Functions
FEXYZ (const FEType &fet)
virtual void reinit (const Elem *elem, const std::vector< Point > *const pts=libmesh_nullptr, const std::vector< Real > *const weights=libmesh_nullptr) libmesh_override
virtual void reinit (const Elem *elem, const unsigned int side, const Real tolerance=TOLERANCE, const std::vector< Point > *const pts=libmesh_nullptr, const std::vector< Real > *const weights=libmesh_nullptr) libmesh_override
template<>
void reinit (const Elem *, const unsigned int, const Real, const std::vector< Point > *const, const std::vector< Real > *const)
template<>
void reinit (const Elem *, const unsigned int, const Real, const std::vector< Point > *const, const std::vector< Real > *const)
virtual unsigned int n_shape_functions () const libmesh_override
virtual FEContinuity get_continuity () const libmesh_override
virtual bool is_hierarchic () const libmesh_override
virtual void edge_reinit (const Elem *elem, const unsigned int edge, const Real tolerance=TOLERANCE, const std::vector< Point > *const pts=libmesh_nullptr, const std::vector< Real > *const weights=libmesh_nullptr) libmesh_override
virtual void side_map (const Elem *elem, const Elem *side, const unsigned int s, const std::vector< Point > &reference_side_points, std::vector< Point > &reference_points) libmesh_override
virtual void attach_quadrature_rule (QBase *q) libmesh_override
virtual unsigned int n_quadrature_points () const libmesh_override
virtual bool shapes_need_reinit () const libmesh_override
const std::vector< std::vector< OutputShape > > & get_phi () const
const std::vector< std::vector< OutputGradient > > & get_dphi () const
const std::vector< std::vector< OutputShape > > & get_curl_phi () const
const std::vector< std::vector< OutputDivergence > > & get_div_phi () const
const std::vector< std::vector< OutputShape > > & get_dphidx () const
const std::vector< std::vector< OutputShape > > & get_dphidy () const
const std::vector< std::vector< OutputShape > > & get_dphidz () const
const std::vector< std::vector< OutputShape > > & get_dphidxi () const
const std::vector< std::vector< OutputShape > > & get_dphideta () const
const std::vector< std::vector< OutputShape > > & get_dphidzeta () const
void print_phi (std::ostream &os) const
void print_dphi (std::ostream &os) const
const std::vector< Point > & get_xyz () const
const std::vector< Real > & get_JxW () const
const std::vector< RealGradient > & get_dxyzdxi () const
const std::vector< RealGradient > & get_dxyzdeta () const
const std::vector< RealGradient > & get_dxyzdzeta () const
const std::vector< RealGradient > & get_d2xyzdxi2 () const
const std::vector< RealGradient > & get_d2xyzdeta2 () const
const std::vector< RealGradient > & get_d2xyzdxideta () const
const std::vector< Real > & get_dxidx () const
const std::vector< Real > & get_dxidy () const
const std::vector< Real > & get_dxidz () const
const std::vector< Real > & get_detadx () const
const std::vector< Real > & get_detady () const
const std::vector< Real > & get_detadz () const
const std::vector< Real > & get_dzetadx () const
const std::vector< Real > & get_dzetady () const
const std::vector< Real > & get_dzetadz () const
const std::vector< std::vector< Point > > & get_tangents () const
const std::vector< Point > & get_normals () const
const std::vector< Real > & get_curvatures () const
ElemType get_type () const
unsigned int get_p_level () const
FEType get_fe_type () const
Order get_order () const
void set_fe_order (int new_order)
FEFamily get_family () const
const FEMap & get_fe_map () const
void print_JxW (std::ostream &os) const
void print_xyz (std::ostream &os) const
void print_info (std::ostream &os) const
Static Public Member Functions
static OutputShape shape (const ElemType t, const Order o, const unsigned int i, const Point &p)
static OutputShape shape (const Elem *elem, const Order o, const unsigned int i, const Point &p)
static OutputShape shape_deriv (const ElemType t, const Order o, const unsigned int i, const unsigned int j, const Point &p)
static OutputShape shape_deriv (const Elem *elem, const Order o, const unsigned int i, const unsigned int j, const Point &p)
static OutputShape shape_second_deriv (const ElemType t, const Order o, const unsigned int i, const unsigned int j, const Point &p)
static OutputShape shape_second_deriv (const Elem *elem, const Order o, const unsigned int i, const unsigned int j, const Point &p)
static void nodal_soln (const Elem *elem, const Order o, const std::vector< Number > &elem_soln, std::vector< Number > &nodal_soln)
static unsigned int n_shape_functions (const ElemType t, const Order o)
static unsigned int n_dofs (const ElemType t, const Order o)
static unsigned int n_dofs_at_node (const ElemType t, const Order o, const unsigned int n)
static unsigned int n_dofs_per_elem (const ElemType t, const Order o)
static void dofs_on_side (const Elem *const elem, const Order o, unsigned int s, std::vector< unsigned int > &di)
static void dofs_on_edge (const Elem *const elem, const Order o, unsigned int e, std::vector< unsigned int > &di)
static Point inverse_map (const Elem *elem, const Point &p, const Real tolerance=TOLERANCE, const bool secure=true)
static void inverse_map (const Elem *elem, const std::vector< Point > &physical_points, std::vector< Point > &reference_points, const Real tolerance=TOLERANCE, const bool secure=true)
static Point map (const Elem *elem, const Point &reference_point)
static Point map_xi (const Elem *elem, const Point &reference_point)
static Point map_eta (const Elem *elem, const Point &reference_point)
static Point map_zeta (const Elem *elem, const Point &reference_point)
static UniquePtr< FEGenericBase > build (const unsigned int dim, const FEType &type)
static bool on_reference_element (const Point &p, const ElemType t, const Real eps=TOLERANCE)
static void get_refspace_nodes (const ElemType t, std::vector< Point > &nodes)
static void print_info (std::ostream &out=libMesh::out)
static std::string get_info ()
static unsigned int n_objects ()
static void enable_print_counter_info ()
static void disable_print_counter_info ()
Protected Member Functions
virtual void init_shape_functions (const std::vector< Point > &qp, const Elem *e) libmesh_override
virtual void compute_shape_functions (const Elem *elem, const std::vector< Point > &qp) libmesh_override
void compute_face_values (const Elem *elem, const Elem *side, const std::vector< Real > &weights)
void determine_calculations ()
Protected Attributes
std::vector< Point > cached_nodes
ElemType last_side
unsigned int last_edge
UniquePtr< FETransformationBase< FEOutputType< T >::type > > _fe_trans
std::vector< std::vector< OutputShape > > phi
std::vector< std::vector< OutputGradient > > dphi
std::vector< std::vector< OutputShape > > curl_phi
std::vector< std::vector< OutputDivergence > > div_phi
std::vector< std::vector< OutputShape > > dphidxi
std::vector< std::vector< OutputShape > > dphideta
std::vector< std::vector< OutputShape > > dphidzeta
std::vector< std::vector< OutputShape > > dphidx
std::vector< std::vector< OutputShape > > dphidy
std::vector< std::vector< OutputShape > > dphidz
UniquePtr< FEMap > _fe_map
const unsigned int dim
bool calculations_started
bool calculate_phi
bool calculate_dphi
bool calculate_d2phi
bool calculate_curl_phi
bool calculate_div_phi
bool calculate_dphiref
FEType fe_type
ElemType elem_type
unsigned int _p_level
QBase * qrule
bool shapes_on_quadrature
Static Protected Attributes
static Threads::atomic< unsigned int > _n_objects
static Threads::spin_mutex _mutex
static bool _enable_print_counter = true
Detailed Description
template<unsigned int Dim>
class libMesh::FEXYZ< Dim >
XYZ finite elements. These require specialization because the shape functions are defined in terms of physical XYZ coordinates rather than local coordinates.
Author
Benjamin S. Kirk
Date
2002-2007
Definition at line 819 of file fe.h.
Member Typedef Documentation
typedef TensorTools::DecrementRank<OutputShape>::type libMesh::FEGenericBase< FEOutputType< T >::type >::OutputDivergence inherited
Definition at line 135 of file fe_base.h.
typedef TensorTools::IncrementRank<OutputShape>::type libMesh::FEGenericBase< FEOutputType< T >::type >::OutputGradient inherited
Definition at line 133 of file fe_base.h.
typedef TensorTools::MakeNumber<OutputShape>::type libMesh::FEGenericBase< FEOutputType< T >::type >::OutputNumber inherited
Definition at line 136 of file fe_base.h.
typedef TensorTools::DecrementRank<OutputNumber>::type libMesh::FEGenericBase< FEOutputType< T >::type >::OutputNumberDivergence inherited
Definition at line 139 of file fe_base.h.
typedef TensorTools::IncrementRank<OutputNumber>::type libMesh::FEGenericBase< FEOutputType< T >::type >::OutputNumberGradient inherited
Definition at line 137 of file fe_base.h.
typedef TensorTools::IncrementRank<OutputNumberGradient>::type libMesh::FEGenericBase< FEOutputType< T >::type >::OutputNumberTensor inherited
Definition at line 138 of file fe_base.h.
typedef FEGenericBase<typename FEOutputType<T>::type>::OutputShape libMesh::FE< Dim, T >::OutputShape inherited
Definition at line 100 of file fe.h.
typedef TensorTools::IncrementRank<OutputGradient>::type libMesh::FEGenericBase< FEOutputType< T >::type >::OutputTensor inherited
Definition at line 134 of file fe_base.h.
Constructor & Destructor Documentation
template<unsigned int Dim> libMesh::FEXYZ< Dim >::FEXYZ (const FEType & fet) inline explicit
Constructor. Creates a monomial finite element to be used in dimension Dim.
Definition at line 828 of file fe.h.
                             :
     FE<Dim,XYZ> (fet)
   {}
Member Function Documentation
virtual void libMesh::FE< Dim, T >::attach_quadrature_rule (QBase * q) virtual inherited
Provides the class with the quadrature rule, which provides the locations (on a reference element) where the shape functions are to be calculated.
Implements libMesh::FEAbstract.
static UniquePtr<FEGenericBase> libMesh::FEGenericBase< FEOutputType< T >::type >::build (const unsigned int dim, const FEType & type) static inherited
Builds a specific finite element type. A UniquePtr<FEGenericBase> is returned to prevent a memory leak. This way the user need not remember to delete the object.
The build call will fail if the OutputType of this class is not compatible with the output required for the requested type
template<unsigned int Dim> void libMesh::FEXYZ< Dim >::compute_face_values (const Elem * elem, const Elem * side, const std::vector< Real > & weights) protected
Compute the map & shape functions for this face.
Definition at line 128 of file fe_xyz_boundary.C.
References libmesh_assert, libmesh_error_msg, LOG_SCOPE, and libMesh::FE< Dim, T >::shape().
 {
   libmesh_assert(elem);
   libmesh_assert(side);
   LOG_SCOPE("compute_face_values()", "FEXYZ");
   // The number of quadrature points.
   const std::size_t n_qp = qw.size();
   // Number of shape functions in the finite element approximation
   // space.
   const unsigned int n_approx_shape_functions =
     this->n_shape_functions(this->get_type(),
                             this->get_order());
   // Resize the shape functions and their gradients
   this->phi.resize    (n_approx_shape_functions);
   this->dphi.resize   (n_approx_shape_functions);
   this->dphidx.resize (n_approx_shape_functions);
   this->dphidy.resize (n_approx_shape_functions);
   this->dphidz.resize (n_approx_shape_functions);
   for (unsigned int i=0; i<n_approx_shape_functions; i++)
     {
       this->phi[i].resize    (n_qp);
       this->dphi[i].resize   (n_qp);
       this->dphidx[i].resize (n_qp);
       this->dphidy[i].resize (n_qp);
       this->dphidz[i].resize (n_qp);
     }
   this->_fe_map->compute_face_map(this->dim, qw, side);
   const std::vector<libMesh::Point> & xyz = this->_fe_map->get_xyz();
   switch (this->dim)
     {
       // A 2D finite element living in either 2D or 3D space.
       // This means the boundary is a 1D finite element, i.e.
       // and EDGE2 or EDGE3.
     case 2:
       {
         // compute the shape function values & gradients
         for (unsigned int i=0; i<n_approx_shape_functions; i++)
           for (std::size_t p=0; p<n_qp; p++)
             {
               this->phi[i][p] = FE<Dim,XYZ>::shape (elem, this->fe_type.order, i, xyz[p]);
               this->dphi[i][p](0) =
                 this->dphidx[i][p] = FE<Dim,XYZ>::shape_deriv (elem, this->fe_type.order, i, 0, xyz[p]);
               this->dphi[i][p](1) =
                 this->dphidy[i][p] = FE<Dim,XYZ>::shape_deriv (elem, this->fe_type.order, i, 1, xyz[p]);
 #if LIBMESH_DIM == 3
               this->dphi[i][p](2) = // can only assign to the Z component if LIBMESH_DIM==3
 #endif
                 this->dphidz[i][p] = 0.;
             }
         // done computing face values
         break;
       }
       // A 3D finite element living in 3D space.
     case 3:
       {
         // compute the shape function values & gradients
         for (unsigned int i=0; i<n_approx_shape_functions; i++)
           for (std::size_t p=0; p<n_qp; p++)
             {
               this->phi[i][p] = FE<Dim,XYZ>::shape (elem, this->fe_type.order, i, xyz[p]);
               this->dphi[i][p](0) =
                 this->dphidx[i][p] = FE<Dim,XYZ>::shape_deriv (elem, this->fe_type.order, i, 0, xyz[p]);
               this->dphi[i][p](1) =
                 this->dphidy[i][p] = FE<Dim,XYZ>::shape_deriv (elem, this->fe_type.order, i, 1, xyz[p]);
               this->dphi[i][p](2) =
                 this->dphidz[i][p] = FE<Dim,XYZ>::shape_deriv (elem, this->fe_type.order, i, 2, xyz[p]);
             }
         // done computing face values
         break;
       }
     default:
       libmesh_error_msg("Invalid dim " << this->dim);
     }
 }
template<unsigned int Dim> template void libMesh::FEXYZ< Dim >::compute_shape_functions (const Elem * elem, const std::vector< Point > & qp) protected virtual
After having updated the jacobian and the transformation from local to global coordinates in FEAbstract::compute_map(), the first derivatives of the shape functions are transformed to global coordinates, giving dphi, dphidx, dphidy, and dphidz. This method should rarely be re-defined in derived classes, but still should be usable for children. Therefore, keep it protected.
Reimplemented from libMesh::FEGenericBase< FEOutputType< T >::type >.
Definition at line 701 of file fe_xyz.C.
References libmesh_assert, libmesh_error_msg, LOG_SCOPE, and libMesh::FE< Dim, T >::shape_second_deriv().
 {
   libmesh_assert(elem);
   //-------------------------------------------------------------------------
   // Compute the shape function values (and derivatives)
   // at the Quadrature points.  Note that the actual values
   // have already been computed via init_shape_functions
   // Start logging the shape function computation
   LOG_SCOPE("compute_shape_functions()", "FE");
   const std::vector<Point> & xyz_qp = this->get_xyz();
   // Compute the value of the derivative shape function i at quadrature point p
   switch (this->dim)
     {
     case 1:
       {
         if (this->calculate_phi)
           for (unsigned int i=0; i<this->phi.size(); i++)
             for (unsigned int p=0; p<this->phi[i].size(); p++)
               this->phi[i][p] = FE<Dim,XYZ>::shape (elem, this->fe_type.order, i, xyz_qp[p]);
         if (this->calculate_dphi)
           for (unsigned int i=0; i<this->dphi.size(); i++)
             for (unsigned int p=0; p<this->dphi[i].size(); p++)
               {
                 this->dphi[i][p](0) =
                   this->dphidx[i][p] = FE<Dim,XYZ>::shape_deriv (elem, this->fe_type.order, i, 0, xyz_qp[p]);
                 this->dphi[i][p](1) = this->dphidy[i][p] = 0.;
                 this->dphi[i][p](2) = this->dphidz[i][p] = 0.;
               }
 #ifdef LIBMESH_ENABLE_SECOND_DERIVATIVES
         if (this->calculate_d2phi)
           for (unsigned int i=0; i<this->d2phi.size(); i++)
             for (unsigned int p=0; p<this->d2phi[i].size(); p++)
               {
                 this->d2phi[i][p](0,0) =
                   this->d2phidx2[i][p] = FE<Dim,XYZ>::shape_second_deriv (elem, this->fe_type.order, i, 0, xyz_qp[p]);
 #if LIBMESH_DIM>1
                 this->d2phi[i][p](0,1) = this->d2phidxdy[i][p] =
                   this->d2phi[i][p](1,0) = 0.;
                 this->d2phi[i][p](1,1) = this->d2phidy2[i][p] = 0.;
 #if LIBMESH_DIM>2
                 this->d2phi[i][p](0,2) = this->d2phidxdz[i][p] =
                   this->d2phi[i][p](2,0) = 0.;
                 this->d2phi[i][p](1,2) = this->d2phidydz[i][p] =
                   this->d2phi[i][p](2,1) = 0.;
                 this->d2phi[i][p](2,2) = this->d2phidz2[i][p] = 0.;
 #endif
 #endif
               }
 #endif // ifdef LIBMESH_ENABLE_SECOND_DERIVATIVES
         // All done
         break;
       }
     case 2:
       {
         if (this->calculate_phi)
           for (unsigned int i=0; i<this->phi.size(); i++)
             for (unsigned int p=0; p<this->phi[i].size(); p++)
               this->phi[i][p] = FE<Dim,XYZ>::shape (elem, this->fe_type.order, i, xyz_qp[p]);
         if (this->calculate_dphi)
           for (unsigned int i=0; i<this->dphi.size(); i++)
             for (unsigned int p=0; p<this->dphi[i].size(); p++)
               {
                 this->dphi[i][p](0) =
                   this->dphidx[i][p] = FE<Dim,XYZ>::shape_deriv (elem, this->fe_type.order, i, 0, xyz_qp[p]);
                 this->dphi[i][p](1) =
                   this->dphidy[i][p] = FE<Dim,XYZ>::shape_deriv (elem, this->fe_type.order, i, 1, xyz_qp[p]);
 #if LIBMESH_DIM == 3
                 this->dphi[i][p](2) = // can only assign to the Z component if LIBMESH_DIM==3
 #endif
                   this->dphidz[i][p] = 0.;
               }
 #ifdef LIBMESH_ENABLE_SECOND_DERIVATIVES
         if (this->calculate_d2phi)
           for (unsigned int i=0; i<this->d2phi.size(); i++)
             for (unsigned int p=0; p<this->d2phi[i].size(); p++)
               {
                 this->d2phi[i][p](0,0) =
                   this->d2phidx2[i][p] = FE<Dim,XYZ>::shape_second_deriv (elem, this->fe_type.order, i, 0, xyz_qp[p]);
                 this->d2phi[i][p](0,1) = this->d2phidxdy[i][p] =
                   this->d2phi[i][p](1,0) = FE<Dim,XYZ>::shape_second_deriv (elem, this->fe_type.order, i, 1, xyz_qp[p]);
                 this->d2phi[i][p](1,1) =
                   this->d2phidy2[i][p] = FE<Dim,XYZ>::shape_second_deriv (elem, this->fe_type.order, i, 2, xyz_qp[p]);
 #if LIBMESH_DIM>2
                 this->d2phi[i][p](0,2) = this->d2phidxdz[i][p] =
                   this->d2phi[i][p](2,0) = 0.;
                 this->d2phi[i][p](1,2) = this->d2phidydz[i][p] =
                   this->d2phi[i][p](2,1) = 0.;
                 this->d2phi[i][p](2,2) = this->d2phidz2[i][p] = 0.;
 #endif
               }
 #endif // ifdef LIBMESH_ENABLE_SECOND_DERIVATIVES
         // All done
         break;
       }
     case 3:
       {
         if (this->calculate_phi)
           for (unsigned int i=0; i<this->phi.size(); i++)
             for (unsigned int p=0; p<this->phi[i].size(); p++)
               this->phi[i][p] = FE<Dim,XYZ>::shape (elem, this->fe_type.order, i, xyz_qp[p]);
         if (this->calculate_dphi)
           for (unsigned int i=0; i<this->dphi.size(); i++)
             for (unsigned int p=0; p<this->dphi[i].size(); p++)
               {
                 this->dphi[i][p](0) =
                   this->dphidx[i][p] = FE<Dim,XYZ>::shape_deriv (elem, this->fe_type.order, i, 0, xyz_qp[p]);
                 this->dphi[i][p](1) =
                   this->dphidy[i][p] = FE<Dim,XYZ>::shape_deriv (elem, this->fe_type.order, i, 1, xyz_qp[p]);
                 this->dphi[i][p](2) =
                   this->dphidz[i][p] = FE<Dim,XYZ>::shape_deriv (elem, this->fe_type.order, i, 2, xyz_qp[p]);
               }
 #ifdef LIBMESH_ENABLE_SECOND_DERIVATIVES
         if (this->calculate_d2phi)
           for (unsigned int i=0; i<this->d2phi.size(); i++)
             for (unsigned int p=0; p<this->d2phi[i].size(); p++)
               {
                 this->d2phi[i][p](0,0) =
                   this->d2phidx2[i][p] = FE<Dim,XYZ>::shape_second_deriv (elem, this->fe_type.order, i, 0, xyz_qp[p]);
                 this->d2phi[i][p](0,1) = this->d2phidxdy[i][p] =
                   this->d2phi[i][p](1,0) = FE<Dim,XYZ>::shape_second_deriv (elem, this->fe_type.order, i, 1, xyz_qp[p]);
                 this->d2phi[i][p](1,1) =
                   this->d2phidy2[i][p] = FE<Dim,XYZ>::shape_second_deriv (elem, this->fe_type.order, i, 2, xyz_qp[p]);
                 this->d2phi[i][p](0,2) = this->d2phidxdz[i][p] =
                   this->d2phi[i][p](2,0) = FE<Dim,XYZ>::shape_second_deriv (elem, this->fe_type.order, i, 3, xyz_qp[p]);
                 this->d2phi[i][p](1,2) = this->d2phidydz[i][p] =
                   this->d2phi[i][p](2,1) = FE<Dim,XYZ>::shape_second_deriv (elem, this->fe_type.order, i, 4, xyz_qp[p]);
                 this->d2phi[i][p](2,2) = this->d2phidz2[i][p] = FE<Dim,XYZ>::shape_second_deriv (elem, this->fe_type.order, i, 5, xyz_qp[p]);
               }
 #endif // ifdef LIBMESH_ENABLE_SECOND_DERIVATIVES
         // All done
         break;
       }
     default:
       libmesh_error_msg("ERROR: Invalid dimension " << this->dim);
     }
 }
void libMesh::FEGenericBase< FEOutputType< T >::type >::determine_calculations () protected inherited
Determine which values are to be calculated, for both the FE itself and for the FEMap.
void libMesh::ReferenceCounter::disable_print_counter_info () static inherited
Definition at line 106 of file reference_counter.C.
References libMesh::ReferenceCounter::_enable_print_counter.
Referenced by libMesh::LibMeshInit::LibMeshInit().
 {
   _enable_print_counter = false;
   return;
 }
static void libMesh::FE< Dim, T >::dofs_on_edge (const Elem *const elem, const Order o, unsigned int e, std::vector< unsigned int > & di) static inherited
Fills the vector di with the local degree of freedom indices associated with edge e of element elem
On a p-refined element, o should be the base order of the element.
static void libMesh::FE< Dim, T >::dofs_on_side (const Elem *const elem, const Order o, unsigned int s, std::vector< unsigned int > & di) static inherited
Fills the vector di with the local degree of freedom indices associated with side s of element elem
On a p-refined element, o should be the base order of the element.
virtual void libMesh::FE< Dim, T >::edge_reinit (const Elem * elem, const unsigned int edge, const Real tolerance = TOLERANCE, const std::vector< Point > *const pts = libmesh_nullptr, const std::vector< Real > *const weights = libmesh_nullptr) virtual inherited
Reinitializes all the physical element-dependent data based on the edge. The tolerance paremeter is passed to the involved call to inverse_map(). By default the shape functions and associated data are computed at the quadrature points specified by the quadrature rule qrule, but may be any points specified on the reference side element specified in the optional argument pts.
Implements libMesh::FEAbstract.
void libMesh::ReferenceCounter::enable_print_counter_info () static inherited
Methods to enable/disable the reference counter output from print_info()
Definition at line 100 of file reference_counter.C.
References libMesh::ReferenceCounter::_enable_print_counter.
 {
   _enable_print_counter = true;
   return;
 }
virtual FEContinuity libMesh::FE< Dim, T >::get_continuity () const virtual inherited
Returns
the continuity level of the finite element.
Implements libMesh::FEAbstract.
const std::vector<std::vector<OutputShape> >& libMesh::FEGenericBase< FEOutputType< T >::type >::get_curl_phi () const inline inherited
Returns
the curl of the shape function at the quadrature points.
Definition at line 236 of file fe_base.h.
References libMesh::FEAbstract::calculate_curl_phi, libMesh::FEAbstract::calculate_dphiref, libMesh::FEAbstract::calculations_started, libMesh::FEGenericBase< OutputType >::curl_phi, and libmesh_assert.
   { libmesh_assert(!calculations_started || calculate_curl_phi);
     calculate_curl_phi = calculate_dphiref = true; return curl_phi; }
const std::vector<Real>& libMesh::FEAbstract::get_curvatures () const inline inherited
Returns
the curvatures for use in face integration.
Definition at line 376 of file fe_abstract.h.
References libMesh::FEAbstract::_fe_map.
   { return this->_fe_map->get_curvatures();}
const std::vector<RealGradient>& libMesh::FEAbstract::get_d2xyzdeta2 () const inline inherited
Returns
the second partial derivatives in eta.
Definition at line 263 of file fe_abstract.h.
References libMesh::FEAbstract::_fe_map.
   { return this->_fe_map->get_d2xyzdeta2(); }
const std::vector<RealGradient>& libMesh::FEAbstract::get_d2xyzdxi2 () const inline inherited
Returns
the second partial derivatives in xi.
Definition at line 257 of file fe_abstract.h.
References libMesh::FEAbstract::_fe_map.
   { return this->_fe_map->get_d2xyzdxi2(); }
const std::vector<RealGradient>& libMesh::FEAbstract::get_d2xyzdxideta () const inline inherited
Returns
the second partial derivatives in xi-eta.
Definition at line 279 of file fe_abstract.h.
References libMesh::FEAbstract::_fe_map.
   { return this->_fe_map->get_d2xyzdxideta(); }
const std::vector<Real>& libMesh::FEAbstract::get_detadx () const inline inherited
Returns
the deta/dx entry in the transformation matrix from physical to local coordinates.
Definition at line 323 of file fe_abstract.h.
References libMesh::FEAbstract::_fe_map.
   { return this->_fe_map->get_detadx(); }
const std::vector<Real>& libMesh::FEAbstract::get_detady () const inline inherited
Returns
the deta/dy entry in the transformation matrix from physical to local coordinates.
Definition at line 330 of file fe_abstract.h.
References libMesh::FEAbstract::_fe_map.
   { return this->_fe_map->get_detady(); }
const std::vector<Real>& libMesh::FEAbstract::get_detadz () const inline inherited
Returns
the deta/dz entry in the transformation matrix from physical to local coordinates.
Definition at line 337 of file fe_abstract.h.
References libMesh::FEAbstract::_fe_map.
   { return this->_fe_map->get_detadz(); }
const std::vector<std::vector<OutputDivergence> >& libMesh::FEGenericBase< FEOutputType< T >::type >::get_div_phi () const inline inherited
Returns
the divergence of the shape function at the quadrature points.
Definition at line 244 of file fe_base.h.
References libMesh::FEAbstract::calculate_div_phi, libMesh::FEAbstract::calculate_dphiref, libMesh::FEAbstract::calculations_started, libMesh::FEGenericBase< OutputType >::div_phi, and libmesh_assert.
   { libmesh_assert(!calculations_started || calculate_div_phi);
     calculate_div_phi = calculate_dphiref = true; return div_phi; }
const std::vector<std::vector<OutputGradient> >& libMesh::FEGenericBase< FEOutputType< T >::type >::get_dphi () const inline inherited
Returns
the shape function derivatives at the quadrature points.
Definition at line 228 of file fe_base.h.
References libMesh::FEAbstract::calculate_dphi, libMesh::FEAbstract::calculate_dphiref, libMesh::FEAbstract::calculations_started, libMesh::FEGenericBase< OutputType >::dphi, and libmesh_assert.
   { libmesh_assert(!calculations_started || calculate_dphi);
     calculate_dphi = calculate_dphiref = true; return dphi; }
const std::vector<std::vector<OutputShape> >& libMesh::FEGenericBase< FEOutputType< T >::type >::get_dphideta () const inline inherited
Returns
the shape function eta-derivative at the quadrature points.
Definition at line 284 of file fe_base.h.
References libMesh::FEAbstract::calculate_dphiref, libMesh::FEAbstract::calculations_started, libMesh::FEGenericBase< OutputType >::dphideta, and libmesh_assert.
   { libmesh_assert(!calculations_started || calculate_dphiref);
     calculate_dphiref = true; return dphideta; }
const std::vector<std::vector<OutputShape> >& libMesh::FEGenericBase< FEOutputType< T >::type >::get_dphidx () const inline inherited
Returns
the shape function x-derivative at the quadrature points.
Definition at line 252 of file fe_base.h.
References libMesh::FEAbstract::calculate_dphi, libMesh::FEAbstract::calculate_dphiref, libMesh::FEAbstract::calculations_started, libMesh::FEGenericBase< OutputType >::dphidx, and libmesh_assert.
   { libmesh_assert(!calculations_started || calculate_dphi);
     calculate_dphi = calculate_dphiref = true; return dphidx; }
const std::vector<std::vector<OutputShape> >& libMesh::FEGenericBase< FEOutputType< T >::type >::get_dphidxi () const inline inherited
Returns
the shape function xi-derivative at the quadrature points.
Definition at line 276 of file fe_base.h.
References libMesh::FEAbstract::calculate_dphiref, libMesh::FEAbstract::calculations_started, libMesh::FEGenericBase< OutputType >::dphidxi, and libmesh_assert.
   { libmesh_assert(!calculations_started || calculate_dphiref);
     calculate_dphiref = true; return dphidxi; }
const std::vector<std::vector<OutputShape> >& libMesh::FEGenericBase< FEOutputType< T >::type >::get_dphidy () const inline inherited
Returns
the shape function y-derivative at the quadrature points.
Definition at line 260 of file fe_base.h.
References libMesh::FEAbstract::calculate_dphi, libMesh::FEAbstract::calculate_dphiref, libMesh::FEAbstract::calculations_started, libMesh::FEGenericBase< OutputType >::dphidy, and libmesh_assert.
   { libmesh_assert(!calculations_started || calculate_dphi);
     calculate_dphi = calculate_dphiref = true; return dphidy; }
const std::vector<std::vector<OutputShape> >& libMesh::FEGenericBase< FEOutputType< T >::type >::get_dphidz () const inline inherited
Returns
the shape function z-derivative at the quadrature points.
Definition at line 268 of file fe_base.h.
References libMesh::FEAbstract::calculate_dphi, libMesh::FEAbstract::calculate_dphiref, libMesh::FEAbstract::calculations_started, libMesh::FEGenericBase< OutputType >::dphidz, and libmesh_assert.
   { libmesh_assert(!calculations_started || calculate_dphi);
     calculate_dphi = calculate_dphiref = true; return dphidz; }
const std::vector<std::vector<OutputShape> >& libMesh::FEGenericBase< FEOutputType< T >::type >::get_dphidzeta () const inline inherited
Returns
the shape function zeta-derivative at the quadrature points.
Definition at line 292 of file fe_base.h.
References libMesh::FEAbstract::calculate_dphiref, libMesh::FEAbstract::calculations_started, libMesh::FEGenericBase< OutputType >::dphidzeta, and libmesh_assert.
   { libmesh_assert(!calculations_started || calculate_dphiref);
     calculate_dphiref = true; return dphidzeta; }
const std::vector<Real>& libMesh::FEAbstract::get_dxidx () const inline inherited
Returns
the dxi/dx entry in the transformation matrix from physical to local coordinates.
Definition at line 302 of file fe_abstract.h.
References libMesh::FEAbstract::_fe_map.
   { return this->_fe_map->get_dxidx(); }
const std::vector<Real>& libMesh::FEAbstract::get_dxidy () const inline inherited
Returns
the dxi/dy entry in the transformation matrix from physical to local coordinates.
Definition at line 309 of file fe_abstract.h.
References libMesh::FEAbstract::_fe_map.
   { return this->_fe_map->get_dxidy(); }
const std::vector<Real>& libMesh::FEAbstract::get_dxidz () const inline inherited
Returns
the dxi/dz entry in the transformation matrix from physical to local coordinates.
Definition at line 316 of file fe_abstract.h.
References libMesh::FEAbstract::_fe_map.
   { return this->_fe_map->get_dxidz(); }
const std::vector<RealGradient>& libMesh::FEAbstract::get_dxyzdeta () const inline inherited
Returns
the element tangents in eta-direction at the quadrature points.
Definition at line 244 of file fe_abstract.h.
References libMesh::FEAbstract::_fe_map.
   { return this->_fe_map->get_dxyzdeta(); }
const std::vector<RealGradient>& libMesh::FEAbstract::get_dxyzdxi () const inline inherited
Returns
the element tangents in xi-direction at the quadrature points.
Definition at line 237 of file fe_abstract.h.
References libMesh::FEAbstract::_fe_map.
   { return this->_fe_map->get_dxyzdxi(); }
const std::vector<RealGradient>& libMesh::FEAbstract::get_dxyzdzeta () const inline inherited
Returns
the element tangents in zeta-direction at the quadrature points.
Definition at line 251 of file fe_abstract.h.
References libMesh::FEAbstract::_fe_map.
   { return _fe_map->get_dxyzdzeta(); }
const std::vector<Real>& libMesh::FEAbstract::get_dzetadx () const inline inherited
Returns
the dzeta/dx entry in the transformation matrix from physical to local coordinates.
Definition at line 344 of file fe_abstract.h.
References libMesh::FEAbstract::_fe_map.
   { return this->_fe_map->get_dzetadx(); }
const std::vector<Real>& libMesh::FEAbstract::get_dzetady () const inline inherited
Returns
the dzeta/dy entry in the transformation matrix from physical to local coordinates.
Definition at line 351 of file fe_abstract.h.
References libMesh::FEAbstract::_fe_map.
   { return this->_fe_map->get_dzetady(); }
const std::vector<Real>& libMesh::FEAbstract::get_dzetadz () const inline inherited
Returns
the dzeta/dz entry in the transformation matrix from physical to local coordinates.
Definition at line 358 of file fe_abstract.h.
References libMesh::FEAbstract::_fe_map.
   { return this->_fe_map->get_dzetadz(); }
FEFamily libMesh::FEAbstract::get_family () const inline inherited
Returns
the finite element family of this element.
Definition at line 440 of file fe_abstract.h.
References libMesh::FEAbstract::fe_type.
Referenced by libMesh::FE< Dim, T >::FE().
 { return fe_type.family; }
const FEMap& libMesh::FEAbstract::get_fe_map () const inline inherited
Returns
the mapping object
Definition at line 445 of file fe_abstract.h.
References libMesh::FEAbstract::_fe_map.
Referenced by libMesh::HCurlFETransformation< OutputShape >::init_map_d2phi(), libMesh::H1FETransformation< OutputShape >::init_map_d2phi(), libMesh::HCurlFETransformation< OutputShape >::init_map_dphi(), libMesh::H1FETransformation< OutputShape >::init_map_dphi(), libMesh::HCurlFETransformation< OutputShape >::init_map_phi(), libMesh::HCurlFETransformation< OutputShape >::map_curl(), libMesh::H1FETransformation< OutputShape >::map_curl(), libMesh::H1FETransformation< OutputShape >::map_div(), libMesh::H1FETransformation< OutputShape >::map_dphi(), and libMesh::HCurlFETransformation< OutputShape >::map_phi().
 { return *_fe_map.get(); }
FEType libMesh::FEAbstract::get_fe_type () const inline inherited
Returns
the FE Type (approximation order and family) of the finite element.
Definition at line 414 of file fe_abstract.h.
References libMesh::FEAbstract::fe_type.
Referenced by libMesh::FEMContext::build_new_fe(), libMesh::JumpErrorEstimator::estimate_error(), libMesh::HCurlFETransformation< OutputShape >::map_phi(), libMesh::H1FETransformation< OutputShape >::map_phi(), libMesh::GenericProjector< FFunctor, GFunctor, FValue, ProjectionAction >::operator()(), and libMesh::JumpErrorEstimator::reinit_sides().
 { return fe_type; }
std::string libMesh::ReferenceCounter::get_info () static inherited
Gets a string containing the reference information.
Definition at line 47 of file reference_counter.C.
References libMesh::Quality::name().
 {
 #if defined(LIBMESH_ENABLE_REFERENCE_COUNTING) && defined(DEBUG)
   std::ostringstream oss;
   oss << '\n'
       << " ---------------------------------------------------------------------------- \n"
       << "| Reference count information                                                |\n"
       << " ---------------------------------------------------------------------------- \n";
   for (Counts::iterator it = _counts.begin();
        it != _counts.end(); ++it)
     {
       const std::string name(it->first);
       const unsigned int creations    = it->second.first;
       const unsigned int destructions = it->second.second;
       oss << "| " << name << " reference count information:\n"
           << "|  Creations:    " << creations    << '\n'
           << "|  Destructions: " << destructions << '\n';
     }
   oss << " ---------------------------------------------------------------------------- \n";
   return oss.str();
 #else
   return "";
 #endif
 }
const std::vector<Real>& libMesh::FEAbstract::get_JxW () const inline inherited
Returns
the element Jacobian times the quadrature weight for each quadrature point.
Definition at line 230 of file fe_abstract.h.
References libMesh::FEAbstract::_fe_map.
Referenced by libMesh::ExactSolution::_compute_error(), libMesh::DiscontinuityMeasure::boundary_side_integration(), libMesh::KellyErrorEstimator::boundary_side_integration(), libMesh::System::calculate_norm(), libMesh::ExactErrorEstimator::find_squared_element_error(), libMesh::FEMSystem::init_context(), libMesh::DiscontinuityMeasure::internal_side_integration(), libMesh::KellyErrorEstimator::internal_side_integration(), and libMesh::GenericProjector< FFunctor, GFunctor, FValue, ProjectionAction >::operator()().
   { return this->_fe_map->get_JxW(); }
const std::vector<Point>& libMesh::FEAbstract::get_normals () const inline inherited
Returns
the outward pointing normal vectors for face integration.
Definition at line 370 of file fe_abstract.h.
References libMesh::FEAbstract::_fe_map.
Referenced by libMesh::KellyErrorEstimator::boundary_side_integration(), libMesh::ParsedFEMFunction< Output >::eval_args(), libMesh::ParsedFEMFunction< Output >::init_context(), libMesh::KellyErrorEstimator::init_context(), and libMesh::KellyErrorEstimator::internal_side_integration().
   { return this->_fe_map->get_normals(); }
Order libMesh::FEAbstract::get_order () const inline inherited
Returns
the approximation order of the finite element.
Definition at line 419 of file fe_abstract.h.
References libMesh::FEAbstract::_p_level, and libMesh::FEAbstract::fe_type.
 { return static_cast<Order>(fe_type.order + _p_level); }
unsigned int libMesh::FEAbstract::get_p_level () const inline inherited
Returns
the p refinement level that the current shape functions have been calculated for.
Definition at line 409 of file fe_abstract.h.
References libMesh::FEAbstract::_p_level.
 { return _p_level; }
const std::vector<std::vector<OutputShape> >& libMesh::FEGenericBase< FEOutputType< T >::type >::get_phi () const inline inherited
Returns
the shape function values at the quadrature points on the element.
Definition at line 220 of file fe_base.h.
References libMesh::FEAbstract::calculate_phi, libMesh::FEAbstract::calculations_started, libmesh_assert, and libMesh::FEGenericBase< OutputType >::phi.
   { libmesh_assert(!calculations_started || calculate_phi);
     calculate_phi = true; return phi; }
void libMesh::FEAbstract::get_refspace_nodes (const ElemType t, std::vector< Point > & nodes) static inherited
returns the reference space nodes coordinates given the element type
Definition at line 259 of file fe_abstract.C.
References libMesh::EDGE2, libMesh::EDGE3, libMesh::HEX20, libMesh::HEX27, libMesh::HEX8, libmesh_error_msg, libMesh::PRISM15, libMesh::PRISM18, libMesh::PRISM6, libMesh::PYRAMID13, libMesh::PYRAMID14, libMesh::PYRAMID5, libMesh::QUAD4, libMesh::QUAD8, libMesh::QUAD9, libMesh::QUADSHELL4, libMesh::TET10, libMesh::TET4, libMesh::TRI3, libMesh::TRI6, and libMesh::TRISHELL3.
 {
   switch(itemType)
     {
     case EDGE2:
       {
         nodes.resize(2);
         nodes[0] = Point (-1.,0.,0.);
         nodes[1] = Point (1.,0.,0.);
         return;
       }
     case EDGE3:
       {
         nodes.resize(3);
         nodes[0] = Point (-1.,0.,0.);
         nodes[1] = Point (1.,0.,0.);
         nodes[2] = Point (0.,0.,0.);
         return;
       }
     case TRI3:
     case TRISHELL3:
       {
         nodes.resize(3);
         nodes[0] = Point (0.,0.,0.);
         nodes[1] = Point (1.,0.,0.);
         nodes[2] = Point (0.,1.,0.);
         return;
       }
     case TRI6:
       {
         nodes.resize(6);
         nodes[0] = Point (0.,0.,0.);
         nodes[1] = Point (1.,0.,0.);
         nodes[2] = Point (0.,1.,0.);
         nodes[3] = Point (.5,0.,0.);
         nodes[4] = Point (.5,.5,0.);
         nodes[5] = Point (0.,.5,0.);
         return;
       }
     case QUAD4:
     case QUADSHELL4:
       {
         nodes.resize(4);
         nodes[0] = Point (-1.,-1.,0.);
         nodes[1] = Point (1.,-1.,0.);
         nodes[2] = Point (1.,1.,0.);
         nodes[3] = Point (-1.,1.,0.);
         return;
       }
     case QUAD8:
       {
         nodes.resize(8);
         nodes[0] = Point (-1.,-1.,0.);
         nodes[1] = Point (1.,-1.,0.);
         nodes[2] = Point (1.,1.,0.);
         nodes[3] = Point (-1.,1.,0.);
         nodes[4] = Point (0.,-1.,0.);
         nodes[5] = Point (1.,0.,0.);
         nodes[6] = Point (0.,1.,0.);
         nodes[7] = Point (-1.,0.,0.);
         return;
       }
     case QUAD9:
       {
         nodes.resize(9);
         nodes[0] = Point (-1.,-1.,0.);
         nodes[1] = Point (1.,-1.,0.);
         nodes[2] = Point (1.,1.,0.);
         nodes[3] = Point (-1.,1.,0.);
         nodes[4] = Point (0.,-1.,0.);
         nodes[5] = Point (1.,0.,0.);
         nodes[6] = Point (0.,1.,0.);
         nodes[7] = Point (-1.,0.,0.);
         nodes[8] = Point (0.,0.,0.);
         return;
       }
     case TET4:
       {
         nodes.resize(4);
         nodes[0] = Point (0.,0.,0.);
         nodes[1] = Point (1.,0.,0.);
         nodes[2] = Point (0.,1.,0.);
         nodes[3] = Point (0.,0.,1.);
         return;
       }
     case TET10:
       {
         nodes.resize(10);
         nodes[0] = Point (0.,0.,0.);
         nodes[1] = Point (1.,0.,0.);
         nodes[2] = Point (0.,1.,0.);
         nodes[3] = Point (0.,0.,1.);
         nodes[4] = Point (.5,0.,0.);
         nodes[5] = Point (.5,.5,0.);
         nodes[6] = Point (0.,.5,0.);
         nodes[7] = Point (0.,0.,.5);
         nodes[8] = Point (.5,0.,.5);
         nodes[9] = Point (0.,.5,.5);
         return;
       }
     case HEX8:
       {
         nodes.resize(8);
         nodes[0] = Point (-1.,-1.,-1.);
         nodes[1] = Point (1.,-1.,-1.);
         nodes[2] = Point (1.,1.,-1.);
         nodes[3] = Point (-1.,1.,-1.);
         nodes[4] = Point (-1.,-1.,1.);
         nodes[5] = Point (1.,-1.,1.);
         nodes[6] = Point (1.,1.,1.);
         nodes[7] = Point (-1.,1.,1.);
         return;
       }
     case HEX20:
       {
         nodes.resize(20);
         nodes[0] = Point (-1.,-1.,-1.);
         nodes[1] = Point (1.,-1.,-1.);
         nodes[2] = Point (1.,1.,-1.);
         nodes[3] = Point (-1.,1.,-1.);
         nodes[4] = Point (-1.,-1.,1.);
         nodes[5] = Point (1.,-1.,1.);
         nodes[6] = Point (1.,1.,1.);
         nodes[7] = Point (-1.,1.,1.);
         nodes[8] = Point (0.,-1.,-1.);
         nodes[9] = Point (1.,0.,-1.);
         nodes[10] = Point (0.,1.,-1.);
         nodes[11] = Point (-1.,0.,-1.);
         nodes[12] = Point (-1.,-1.,0.);
         nodes[13] = Point (1.,-1.,0.);
         nodes[14] = Point (1.,1.,0.);
         nodes[15] = Point (-1.,1.,0.);
         nodes[16] = Point (0.,-1.,1.);
         nodes[17] = Point (1.,0.,1.);
         nodes[18] = Point (0.,1.,1.);
         nodes[19] = Point (-1.,0.,1.);
         return;
       }
     case HEX27:
       {
         nodes.resize(27);
         nodes[0] = Point (-1.,-1.,-1.);
         nodes[1] = Point (1.,-1.,-1.);
         nodes[2] = Point (1.,1.,-1.);
         nodes[3] = Point (-1.,1.,-1.);
         nodes[4] = Point (-1.,-1.,1.);
         nodes[5] = Point (1.,-1.,1.);
         nodes[6] = Point (1.,1.,1.);
         nodes[7] = Point (-1.,1.,1.);
         nodes[8] = Point (0.,-1.,-1.);
         nodes[9] = Point (1.,0.,-1.);
         nodes[10] = Point (0.,1.,-1.);
         nodes[11] = Point (-1.,0.,-1.);
         nodes[12] = Point (-1.,-1.,0.);
         nodes[13] = Point (1.,-1.,0.);
         nodes[14] = Point (1.,1.,0.);
         nodes[15] = Point (-1.,1.,0.);
         nodes[16] = Point (0.,-1.,1.);
         nodes[17] = Point (1.,0.,1.);
         nodes[18] = Point (0.,1.,1.);
         nodes[19] = Point (-1.,0.,1.);
         nodes[20] = Point (0.,0.,-1.);
         nodes[21] = Point (0.,-1.,0.);
         nodes[22] = Point (1.,0.,0.);
         nodes[23] = Point (0.,1.,0.);
         nodes[24] = Point (-1.,0.,0.);
         nodes[25] = Point (0.,0.,1.);
         nodes[26] = Point (0.,0.,0.);
         return;
       }
     case PRISM6:
       {
         nodes.resize(6);
         nodes[0] = Point (0.,0.,-1.);
         nodes[1] = Point (1.,0.,-1.);
         nodes[2] = Point (0.,1.,-1.);
         nodes[3] = Point (0.,0.,1.);
         nodes[4] = Point (1.,0.,1.);
         nodes[5] = Point (0.,1.,1.);
         return;
       }
     case PRISM15:
       {
         nodes.resize(15);
         nodes[0] = Point (0.,0.,-1.);
         nodes[1] = Point (1.,0.,-1.);
         nodes[2] = Point (0.,1.,-1.);
         nodes[3] = Point (0.,0.,1.);
         nodes[4] = Point (1.,0.,1.);
         nodes[5] = Point (0.,1.,1.);
         nodes[6] = Point (.5,0.,-1.);
         nodes[7] = Point (.5,.5,-1.);
         nodes[8] = Point (0.,.5,-1.);
         nodes[9] = Point (0.,0.,0.);
         nodes[10] = Point (1.,0.,0.);
         nodes[11] = Point (0.,1.,0.);
         nodes[12] = Point (.5,0.,1.);
         nodes[13] = Point (.5,.5,1.);
         nodes[14] = Point (0.,.5,1.);
         return;
       }
     case PRISM18:
       {
         nodes.resize(18);
         nodes[0] = Point (0.,0.,-1.);
         nodes[1] = Point (1.,0.,-1.);
         nodes[2] = Point (0.,1.,-1.);
         nodes[3] = Point (0.,0.,1.);
         nodes[4] = Point (1.,0.,1.);
         nodes[5] = Point (0.,1.,1.);
         nodes[6] = Point (.5,0.,-1.);
         nodes[7] = Point (.5,.5,-1.);
         nodes[8] = Point (0.,.5,-1.);
         nodes[9] = Point (0.,0.,0.);
         nodes[10] = Point (1.,0.,0.);
         nodes[11] = Point (0.,1.,0.);
         nodes[12] = Point (.5,0.,1.);
         nodes[13] = Point (.5,.5,1.);
         nodes[14] = Point (0.,.5,1.);
         nodes[15] = Point (.5,0.,0.);
         nodes[16] = Point (.5,.5,0.);
         nodes[17] = Point (0.,.5,0.);
         return;
       }
     case PYRAMID5:
       {
         nodes.resize(5);
         nodes[0] = Point (-1.,-1.,0.);
         nodes[1] = Point (1.,-1.,0.);
         nodes[2] = Point (1.,1.,0.);
         nodes[3] = Point (-1.,1.,0.);
         nodes[4] = Point (0.,0.,1.);
         return;
       }
     case PYRAMID13:
       {
         nodes.resize(13);
         // base corners
         nodes[0] = Point (-1.,-1.,0.);
         nodes[1] = Point (1.,-1.,0.);
         nodes[2] = Point (1.,1.,0.);
         nodes[3] = Point (-1.,1.,0.);
         // apex
         nodes[4] = Point (0.,0.,1.);
         // base midedge
         nodes[5] = Point (0.,-1.,0.);
         nodes[6] = Point (1.,0.,0.);
         nodes[7] = Point (0.,1.,0.);
         nodes[8] = Point (-1,0.,0.);
         // lateral midedge
         nodes[9] = Point (-.5,-.5,.5);
         nodes[10] = Point (.5,-.5,.5);
         nodes[11] = Point (.5,.5,.5);
         nodes[12] = Point (-.5,.5,.5);
         return;
       }
     case PYRAMID14:
       {
         nodes.resize(14);
         // base corners
         nodes[0] = Point (-1.,-1.,0.);
         nodes[1] = Point (1.,-1.,0.);
         nodes[2] = Point (1.,1.,0.);
         nodes[3] = Point (-1.,1.,0.);
         // apex
         nodes[4] = Point (0.,0.,1.);
         // base midedge
         nodes[5] = Point (0.,-1.,0.);
         nodes[6] = Point (1.,0.,0.);
         nodes[7] = Point (0.,1.,0.);
         nodes[8] = Point (-1,0.,0.);
         // lateral midedge
         nodes[9] = Point (-.5,-.5,.5);
         nodes[10] = Point (.5,-.5,.5);
         nodes[11] = Point (.5,.5,.5);
         nodes[12] = Point (-.5,.5,.5);
         // base center
         nodes[13] = Point (0.,0.,0.);
         return;
       }
     default:
       libmesh_error_msg("ERROR: Unknown element type " << itemType);
     }
 }
const std::vector<std::vector<Point> >& libMesh::FEAbstract::get_tangents () const inline inherited
Returns
the tangent vectors for face integration.
Definition at line 364 of file fe_abstract.h.
References libMesh::FEAbstract::_fe_map.
   { return this->_fe_map->get_tangents(); }
ElemType libMesh::FEAbstract::get_type () const inline inherited
Returns
the element type that the current shape functions have been calculated for. Useful in determining when shape functions must be recomputed.
Definition at line 403 of file fe_abstract.h.
References libMesh::FEAbstract::elem_type.
 { return elem_type; }
const std::vector<Point>& libMesh::FEAbstract::get_xyz () const inline inherited
Returns
the xyz spatial locations of the quadrature points on the element.
Definition at line 223 of file fe_abstract.h.
References libMesh::FEAbstract::_fe_map.
Referenced by libMesh::ExactSolution::_compute_error(), libMesh::DiscontinuityMeasure::boundary_side_integration(), libMesh::KellyErrorEstimator::boundary_side_integration(), libMesh::JumpErrorEstimator::estimate_error(), libMesh::ParsedFEMFunction< Output >::eval_args(), libMesh::ExactErrorEstimator::find_squared_element_error(), libMesh::ParsedFEMFunction< Output >::init_context(), libMesh::DGFEMContext::neighbor_side_fe_reinit(), and libMesh::GenericProjector< FFunctor, GFunctor, FValue, ProjectionAction >::operator()().
   { return this->_fe_map->get_xyz(); }
template<unsigned int Dim> template void libMesh::FEXYZ< Dim >::init_shape_functions (const std::vector< Point > & qp, const Elem * e) protected virtual
Update the various member data fields phi, dphidxi, dphideta, dphidzeta, etc. for the current element. These data will be computed at the points qp, which are generally (but need not be) the quadrature points.
Reimplemented from libMesh::FE< Dim, XYZ >.
Definition at line 590 of file fe_xyz.C.
References libmesh_assert, LOG_SCOPE, and libMesh::MeshTools::weight().
 {
   libmesh_assert(elem);
   this->calculations_started = true;
   // If the user forgot to request anything, we'll be safe and
   // calculate everything:
 #ifdef LIBMESH_ENABLE_SECOND_DERIVATIVES
   if (!this->calculate_phi && !this->calculate_dphi && !this->calculate_d2phi)
     this->calculate_phi = this->calculate_dphi = this->calculate_d2phi = true;
 #else
   if (!this->calculate_phi && !this->calculate_dphi)
     this->calculate_phi = this->calculate_dphi = true;
 #endif // LIBMESH_ENABLE_SECOND_DERIVATIVES
   // Start logging the shape function initialization
   LOG_SCOPE("init_shape_functions()", "FE");
   // The number of quadrature points.
   const std::size_t n_qp = qp.size();
   // Number of shape functions in the finite element approximation
   // space.
   const unsigned int n_approx_shape_functions =
     this->n_shape_functions(this->get_type(),
                             this->get_order());
   // resize the vectors to hold current data
   // Phi are the shape functions used for the FE approximation
   {
     // (note: GCC 3.4.0 requires the use of this-> here)
     if (this->calculate_phi)
       this->phi.resize     (n_approx_shape_functions);
     if (this->calculate_dphi)
       {
         this->dphi.resize    (n_approx_shape_functions);
         this->dphidx.resize  (n_approx_shape_functions);
         this->dphidy.resize  (n_approx_shape_functions);
         this->dphidz.resize  (n_approx_shape_functions);
       }
 #ifdef LIBMESH_ENABLE_SECOND_DERIVATIVES
     if (this->calculate_d2phi)
       {
         this->d2phi.resize     (n_approx_shape_functions);
         this->d2phidx2.resize  (n_approx_shape_functions);
         this->d2phidxdy.resize (n_approx_shape_functions);
         this->d2phidxdz.resize (n_approx_shape_functions);
         this->d2phidy2.resize  (n_approx_shape_functions);
         this->d2phidydz.resize (n_approx_shape_functions);
         this->d2phidz2.resize  (n_approx_shape_functions);
         this->d2phidxi2.resize (n_approx_shape_functions);
       }
 #endif // ifdef LIBMESH_ENABLE_SECOND_DERIVATIVES
     for (unsigned int i=0; i<n_approx_shape_functions; i++)
       {
         if (this->calculate_phi)
           this->phi[i].resize           (n_qp);
         if (this->calculate_dphi)
           {
             this->dphi[i].resize        (n_qp);
             this->dphidx[i].resize      (n_qp);
             this->dphidy[i].resize      (n_qp);
             this->dphidz[i].resize      (n_qp);
           }
 #ifdef LIBMESH_ENABLE_SECOND_DERIVATIVES
         if (this->calculate_d2phi)
           {
             this->d2phi[i].resize       (n_qp);
             this->d2phidx2[i].resize    (n_qp);
             this->d2phidxdy[i].resize   (n_qp);
             this->d2phidxdz[i].resize   (n_qp);
             this->d2phidy2[i].resize    (n_qp);
             this->d2phidydz[i].resize   (n_qp);
             this->d2phidz2[i].resize    (n_qp);
           }
 #endif // ifdef LIBMESH_ENABLE_SECOND_DERIVATIVES
       }
   }
 #ifdef LIBMESH_ENABLE_INFINITE_ELEMENTS
   //------------------------------------------------------------
   // Initialize the data fields, which should only be used for infinite
   // elements, to some sensible values, so that using a FE with the
   // variational formulation of an InfFE, correct element matrices are
   // returned
   {
     this->weight.resize  (n_qp);
     this->dweight.resize (n_qp);
     this->dphase.resize  (n_qp);
     for (unsigned int p=0; p<n_qp; p++)
       {
         this->weight[p] = 1.;
         this->dweight[p].zero();
         this->dphase[p].zero();
       }
   }
 #endif // ifdef LIBMESH_ENABLE_INFINITE_ELEMENTS
 }
static Point libMesh::FE< Dim, T >::inverse_map (const Elem * elem, const Point & p, const Real tolerance = TOLERANCE, const bool secure = true) static inherited
Returns
the location (on the reference element) of the point p located in physical space. This function requires inverting the (possibly nonlinear) transformation map, so it is not trivial. The optional parameter tolerance defines how close is "good enough." The map inversion iteration computes the sequence , and the iteration is terminated when
static void libMesh::FE< Dim, T >::inverse_map (const Elem * elem, const std::vector< Point > & physical_points, std::vector< Point > & reference_points, const Real tolerance = TOLERANCE, const bool secure = true) static inherited
Takes a number points in physical space (in the physical_points vector) and finds their location on the reference element for the input element elem. The values on the reference element are returned in the vector reference_points. The optional parameter tolerance defines how close is "good enough." The map inversion iteration computes the sequence , and the iteration is terminated when
virtual bool libMesh::FE< Dim, T >::is_hierarchic () const virtual inherited
Returns
true if the finite element's higher order shape functions are hierarchic
Implements libMesh::FEAbstract.
static Point libMesh::FE< Dim, T >::map (const Elem * elem, const Point & reference_point) static inherited
Returns
the location (in physical space) of the point p located on the reference element.
static Point libMesh::FE< Dim, T >::map_eta (const Elem * elem, const Point & reference_point) static inherited
Returns
d(xyz)/deta (in physical space) of the point p located on the reference element.
static Point libMesh::FE< Dim, T >::map_xi (const Elem * elem, const Point & reference_point) static inherited
Returns
d(xyz)/dxi (in physical space) of the point p located on the reference element.
static Point libMesh::FE< Dim, T >::map_zeta (const Elem * elem, const Point & reference_point) static inherited
Returns
d(xyz)/dzeta (in physical space) of the point p located on the reference element.
static unsigned int libMesh::FE< Dim, T >::n_dofs (const ElemType t, const Order o) static inherited
Returns
the number of shape functions associated with this finite element.
On a p-refined element, o should be the total order of the element.
static unsigned int libMesh::FE< Dim, T >::n_dofs_at_node (const ElemType t, const Order o, const unsigned int n) static inherited
Returns
the number of dofs at node n for a finite element of type t and order o.
On a p-refined element, o should be the total order of the element.
static unsigned int libMesh::FE< Dim, T >::n_dofs_per_elem (const ElemType t, const Order o) static inherited
Returns
the number of dofs interior to the element, not associated with any interior nodes.
On a p-refined element, o should be the total order of the element.
static unsigned int libMesh::ReferenceCounter::n_objects () inline static inherited
Prints the number of outstanding (created, but not yet destroyed) objects.
Definition at line 75 of file reference_counter.h.
References libMesh::ReferenceCounter::_n_objects.
Referenced by libMesh::LibMeshInit::~LibMeshInit().
   { return _n_objects; }
virtual unsigned int libMesh::FE< Dim, T >::n_quadrature_points () const virtual inherited
Returns
the total number of quadrature points. Call this to get an upper bound for the for loop in your simulation for matrix assembly of the current element.
Implements libMesh::FEAbstract.
virtual unsigned int libMesh::FE< Dim, T >::n_shape_functions () const virtual inherited
Returns
the number of shape functions associated with this finite element.
Implements libMesh::FEAbstract.
static unsigned int libMesh::FE< Dim, T >::n_shape_functions (const ElemType t, const Order o) inline static inherited
Returns
the number of shape functions associated with a finite element of type t and approximation order o.
On a p-refined element, o should be the total order of the element.
Definition at line 223 of file fe.h.
   { return FE<Dim,T>::n_dofs (t,o); }
static void libMesh::FE< Dim, T >::nodal_soln (const Elem * elem, const Order o, const std::vector< Number > & elem_soln, std::vector< Number > & nodal_soln) static inherited
Build the nodal soln from the element soln. This is the solution that will be plotted.
On a p-refined element, o should be the base order of the element.
bool libMesh::FEAbstract::on_reference_element (const Point & p, const ElemType t, const Real eps = TOLERANCE) static inherited
Returns
true if the point p is located on the reference element for element type t, false otherwise. Since we are doing floating point comparisons here the parameter eps can be specified to indicate a tolerance. For example, becomes .
Definition at line 556 of file fe_abstract.C.
References libMesh::EDGE2, libMesh::EDGE3, libMesh::EDGE4, libMesh::HEX20, libMesh::HEX27, libMesh::HEX8, libMesh::INFHEX8, libMesh::INFPRISM6, libmesh_assert_greater_equal, libmesh_error_msg, libMesh::NODEELEM, libMesh::PRISM15, libMesh::PRISM18, libMesh::PRISM6, libMesh::PYRAMID13, libMesh::PYRAMID14, libMesh::PYRAMID5, libMesh::QUAD4, libMesh::QUAD8, libMesh::QUAD9, libMesh::QUADSHELL4, libMesh::TET10, libMesh::TET4, libMesh::TRI3, libMesh::TRI6, and libMesh::TRISHELL3.
Referenced by libMesh::FE< Dim, T >::inverse_map(), and libMesh::FEInterface::on_reference_element().
 {
   libmesh_assert_greater_equal (eps, 0.);
   const Real xi   = p(0);
 #if LIBMESH_DIM > 1
   const Real eta  = p(1);
 #else
   const Real eta  = 0.;
 #endif
 #if LIBMESH_DIM > 2
   const Real zeta = p(2);
 #else
   const Real zeta  = 0.;
 #endif
   switch (t)
     {
     case NODEELEM:
       {
         return (!xi && !eta && !zeta);
       }
     case EDGE2:
     case EDGE3:
     case EDGE4:
       {
         // The reference 1D element is [-1,1].
         if ((xi >= -1.-eps) &&
             (xi <=  1.+eps))
           return true;
         return false;
       }
     case TRI3:
     case TRISHELL3:
     case TRI6:
       {
         // The reference triangle is isocoles
         // and is bound by xi=0, eta=0, and xi+eta=1.
         if ((xi  >= 0.-eps) &&
             (eta >= 0.-eps) &&
             ((xi + eta) <= 1.+eps))
           return true;
         return false;
       }
     case QUAD4:
     case QUADSHELL4:
     case QUAD8:
     case QUAD9:
       {
         // The reference quadrilateral element is [-1,1]^2.
         if ((xi  >= -1.-eps) &&
             (xi  <=  1.+eps) &&
             (eta >= -1.-eps) &&
             (eta <=  1.+eps))
           return true;
         return false;
       }
     case TET4:
     case TET10:
       {
         // The reference tetrahedral is isocoles
         // and is bound by xi=0, eta=0, zeta=0,
         // and xi+eta+zeta=1.
         if ((xi   >= 0.-eps) &&
             (eta  >= 0.-eps) &&
             (zeta >= 0.-eps) &&
             ((xi + eta + zeta) <= 1.+eps))
           return true;
         return false;
       }
     case HEX8:
     case HEX20:
     case HEX27:
       {
         /*
           if ((xi   >= -1.) &&
           (xi   <=  1.) &&
           (eta  >= -1.) &&
           (eta  <=  1.) &&
           (zeta >= -1.) &&
           (zeta <=  1.))
           return true;
         */
         // The reference hexahedral element is [-1,1]^3.
         if ((xi   >= -1.-eps) &&
             (xi   <=  1.+eps) &&
             (eta  >= -1.-eps) &&
             (eta  <=  1.+eps) &&
             (zeta >= -1.-eps) &&
             (zeta <=  1.+eps))
           {
             //    libMesh::out << "Strange Point:\n";
             //    p.print();
             return true;
           }
         return false;
       }
     case PRISM6:
     case PRISM15:
     case PRISM18:
       {
         // Figure this one out...
         // inside the reference triange with zeta in [-1,1]
         if ((xi   >=  0.-eps) &&
             (eta  >=  0.-eps) &&
             (zeta >= -1.-eps) &&
             (zeta <=  1.+eps) &&
             ((xi + eta) <= 1.+eps))
           return true;
         return false;
       }
     case PYRAMID5:
     case PYRAMID13:
     case PYRAMID14:
       {
         // Check that the point is on the same side of all the faces
         // by testing whether:
         //
         // n_i.(x - x_i) <= 0
         //
         // for each i, where:
         //   n_i is the outward normal of face i,
         //   x_i is a point on face i.
         if ((-eta - 1. + zeta <= 0.+eps) &&
             (  xi - 1. + zeta <= 0.+eps) &&
             ( eta - 1. + zeta <= 0.+eps) &&
             ( -xi - 1. + zeta <= 0.+eps) &&
             (            zeta >= 0.-eps))
           return true;
         return false;
       }
 #ifdef LIBMESH_ENABLE_INFINITE_ELEMENTS
     case INFHEX8:
       {
         // The reference infhex8 is a [-1,1]^3.
         if ((xi   >= -1.-eps) &&
             (xi   <=  1.+eps) &&
             (eta  >= -1.-eps) &&
             (eta  <=  1.+eps) &&
             (zeta >= -1.-eps) &&
             (zeta <=  1.+eps))
           {
             return true;
           }
         return false;
       }
     case INFPRISM6:
       {
         // inside the reference triange with zeta in [-1,1]
         if ((xi   >=  0.-eps) &&
             (eta  >=  0.-eps) &&
             (zeta >= -1.-eps) &&
             (zeta <=  1.+eps) &&
             ((xi + eta) <= 1.+eps))
           {
             return true;
           }
         return false;
       }
 #endif
     default:
       libmesh_error_msg("ERROR: Unknown element type " << t);
     }
   // If we get here then the point is _not_ in the
   // reference element.   Better return false.
   return false;
 }
void libMesh::FEGenericBase< FEOutputType< T >::type >::print_dphi (std::ostream & os) const virtual inherited
Prints the value of each shape function's derivative at each quadrature point.
Implements libMesh::FEAbstract.
void libMesh::ReferenceCounter::print_info (std::ostream & out = libMesh::out) static inherited
Prints the reference information, by default to libMesh::out.
Definition at line 95 of file reference_counter.C.
Referenced by libMesh::LibMeshInit::~LibMeshInit().
 {}
void libMesh::FEAbstract::print_info (std::ostream & os) const inherited
Prints all the relevant information about the current element.
Definition at line 764 of file fe_abstract.C.
References libMesh::FEAbstract::print_dphi(), libMesh::FEAbstract::print_JxW(), libMesh::FEAbstract::print_phi(), and libMesh::FEAbstract::print_xyz().
Referenced by libMesh::operator<<().
 {
   os << "phi[i][j]: Shape function i at quadrature pt. j" << std::endl;
   this->print_phi(os);
   os << "dphi[i][j]: Shape function i's gradient at quadrature pt. j" << std::endl;
   this->print_dphi(os);
   os << "XYZ locations of the quadrature pts." << std::endl;
   this->print_xyz(os);
   os << "Values of JxW at the quadrature pts." << std::endl;
   this->print_JxW(os);
 }
void libMesh::FEAbstract::print_JxW (std::ostream & os) const inherited
Prints the Jacobian times the weight for each quadrature point.
Definition at line 751 of file fe_abstract.C.
References libMesh::FEAbstract::_fe_map.
Referenced by libMesh::FEAbstract::print_info().
 {
   this->_fe_map->print_JxW(os);
 }
void libMesh::FEGenericBase< FEOutputType< T >::type >::print_phi (std::ostream & os) const virtual inherited
Prints the value of each shape function at each quadrature point.
Implements libMesh::FEAbstract.
void libMesh::FEAbstract::print_xyz (std::ostream & os) const inherited
Prints the spatial location of each quadrature point (on the physical element).
Definition at line 758 of file fe_abstract.C.
References libMesh::FEAbstract::_fe_map.
Referenced by libMesh::FEAbstract::print_info().
 {
   this->_fe_map->print_xyz(os);
 }
template<> void libMesh::FEXYZ< 0 >::reinit (const Elem * elem, const unsigned int side, const Real tolerance, const std::vector< Point > * pts, const std::vector< Real > * weights) virtual
Reinitializes all the physical element-dependent data based on the side of face. The tolerance paremeter is passed to the involved call to inverse_map(). By default the shape functions and associated data are computed at the quadrature points specified by the quadrature rule qrule, but may be any points specified on the reference side element specified in the optional argument pts.
Reimplemented from libMesh::FE< Dim, XYZ >.
Definition at line 41 of file fe_xyz_boundary.C.
References libmesh_error_msg.
 {
   libmesh_error_msg("ERROR: This method only makes sense for 2D/3D elements!");
 }
template<> void libMesh::FEXYZ< 1 >::reinit (const Elem * elem, const unsigned int side, const Real tolerance, const std::vector< Point > * pts, const std::vector< Real > * weights) virtual
Reinitializes all the physical element-dependent data based on the side of face. The tolerance paremeter is passed to the involved call to inverse_map(). By default the shape functions and associated data are computed at the quadrature points specified by the quadrature rule qrule, but may be any points specified on the reference side element specified in the optional argument pts.
Reimplemented from libMesh::FE< Dim, XYZ >.
Definition at line 54 of file fe_xyz_boundary.C.
References libmesh_error_msg.
 {
   libmesh_error_msg("ERROR: This method only makes sense for 2D/3D elements!");
 }
template<unsigned int Dim> virtual void libMesh::FEXYZ< Dim >::reinit (const Elem * elem, const std::vector< Point > *const pts = libmesh_nullptr, const std::vector< Real > *const weights = libmesh_nullptr) inline virtual
Explicitly call base class method. This prevents some compilers being confused by partially overriding this virtual function.
Reimplemented from libMesh::FE< Dim, XYZ >.
Definition at line 836 of file fe.h.
References libMesh::FE< Dim, T >::reinit().
   { FE<Dim,XYZ>::reinit (elem, pts, weights); }
template<unsigned int Dim> void libMesh::FEXYZ< Dim >::reinit (const Elem * elem, const unsigned int side, const Real tolerance = TOLERANCE, const std::vector< Point > *const pts = libmesh_nullptr, const std::vector< Real > *const weights = libmesh_nullptr) virtual
Reinitializes all the physical element-dependent data based on the side of face.
Reimplemented from libMesh::FE< Dim, XYZ >.
Definition at line 67 of file fe_xyz_boundary.C.
References libMesh::Elem::build_side_ptr(), libmesh_assert, libmesh_assert_not_equal_to, libmesh_nullptr, libMesh::Elem::p_level(), side, and libMesh::Elem::type().
 {
   libmesh_assert(elem);
   libmesh_assert (this->qrule != libmesh_nullptr || pts != libmesh_nullptr);
   // We don't do this for 1D elements!
   libmesh_assert_not_equal_to (Dim, 1);
   // Build the side of interest
   const UniquePtr<const Elem> side(elem->build_side_ptr(s));
   // Initialize the shape functions at the user-specified
   // points
   if (pts != libmesh_nullptr)
     {
       // We can't get away without recomputing shape functions next
       // time
       this->shapes_on_quadrature = false;
       // Set the element type
       this->elem_type = elem->type();
       // Initialize the face shape functions
       this->_fe_map->template init_face_shape_functions<Dim>(*pts,  side.get());
       if (weights != libmesh_nullptr)
         {
           this->compute_face_values (elem, side.get(), *weights);
         }
       else
         {
           std::vector<Real> dummy_weights (pts->size(), 1.);
           // Compute data on the face for integration
           this->compute_face_values (elem, side.get(), dummy_weights);
         }
     }
   else
     {
       // initialize quadrature rule
       this->qrule->init(side->type(), elem->p_level());
       {
         // Set the element type
         this->elem_type = elem->type();
         // Initialize the face shape functions
         this->_fe_map->template init_face_shape_functions<Dim>(this->qrule->get_points(),  side.get());
       }
       // We can't get away without recomputing shape functions next
       // time
       this->shapes_on_quadrature = false;
       // Compute data on the face for integration
       this->compute_face_values (elem, side.get(), this->qrule->get_weights());
     }
 }
void libMesh::FEAbstract::set_fe_order (int new_order) inline inherited
Sets the base FE order of the finite element.
Definition at line 424 of file fe_abstract.h.
References libMesh::FEAbstract::fe_type.
 { fe_type.order = new_order; }
static OutputShape libMesh::FE< Dim, T >::shape (const ElemType t, const Order o, const unsigned int i, const Point & p) static inherited
Returns
the value of the shape function at point p. This method allows you to specify the imension, element type, and order directly. This allows the method to be static.
On a p-refined element, o should be the total order of the element.
static OutputShape libMesh::FE< Dim, T >::shape (const Elem * elem, const Order o, const unsigned int i, const Point & p) static inherited
Returns
the value of the shape function at point p. This method allows you to specify the imension, element type, and order directly. This allows the method to be static.
On a p-refined element, o should be the base order of the element.
static OutputShape libMesh::FE< Dim, T >::shape_deriv (const ElemType t, const Order o, const unsigned int i, const unsigned int j, const Point & p) static inherited
Returns
the derivative of the shape function at point p. This method allows you to specify the dimension, element type, and order directly.
On a p-refined element, o should be the total order of the element.
static OutputShape libMesh::FE< Dim, T >::shape_deriv (const Elem * elem, const Order o, const unsigned int i, const unsigned int j, const Point & p) static inherited
Returns
the derivative of the shape function. You must specify element type, and order directly.
On a p-refined element, o should be the base order of the element.
static OutputShape libMesh::FE< Dim, T >::shape_second_deriv (const ElemType t, const Order o, const unsigned int i, const unsigned int j, const Point & p) static inherited
Returns
the second derivative of the shape function at the point p. Note that cross-derivatives are also possible, i.e. j = 0 ==> d^2 phi / dxi^2 j = 1 ==> d^2 phi / dxi deta j = 2 ==> d^2 phi / deta^2 j = 3 ==> d^2 phi / dxi dzeta j = 4 ==> d^2 phi / deta dzeta j = 5 ==> d^2 phi / dzeta^2
Note: Computing second derivatives is not currently supported for all element types: C1 (Clough, Hermite and Subdivision), Lagrange, Hierarchic, L2_Hierarchic, and Monomial are supported. All other element types return an error when asked for second derivatives.
On a p-refined element, o should be the total order of the element.
static OutputShape libMesh::FE< Dim, T >::shape_second_deriv (const Elem * elem, const Order o, const unsigned int i, const unsigned int j, const Point & p) static inherited
Returns
the second derivative of the shape function at the point p. Note that cross-derivatives are also possible, i.e. j = 0 ==> d^2 phi / dxi^2 j = 1 ==> d^2 phi / dxi deta j = 2 ==> d^2 phi / deta^2 j = 3 ==> d^2 phi / dxi dzeta j = 4 ==> d^2 phi / deta dzeta j = 5 ==> d^2 phi / dzeta^2
Note: Computing second derivatives is not currently supported for all element types: C1 (Clough, Hermite and Subdivision), Lagrange, Hierarchic, L2_Hierarchic, and Monomial are supported. All other element types return an error when asked for second derivatives.
On a p-refined element, o should be the base order of the element.
virtual bool libMesh::FE< Dim, T >::shapes_need_reinit () const virtual inherited
Returns
true when the shape functions (for this FEFamily) depend on the particular element, and therefore needs to be re-initialized for each new element. false otherwise.
Implements libMesh::FEAbstract.
virtual void libMesh::FE< Dim, T >::side_map (const Elem * elem, const Elem * side, const unsigned int s, const std::vector< Point > & reference_side_points, std::vector< Point > & reference_points) virtual inherited
Computes the reference space quadrature points on the side of an element based on the side quadrature points.
Implements libMesh::FEAbstract.
Member Data Documentation
bool libMesh::ReferenceCounter::_enable_print_counter = true static protected inherited
Flag to control whether reference count information is printed when print_info is called.
Definition at line 133 of file reference_counter.h.
Referenced by libMesh::ReferenceCounter::disable_print_counter_info(), and libMesh::ReferenceCounter::enable_print_counter_info().
UniquePtr<FEMap> libMesh::FEAbstract::_fe_map protected inherited
Definition at line 510 of file fe_abstract.h.
Referenced by libMesh::FEAbstract::get_curvatures(), libMesh::FEAbstract::get_d2xyzdeta2(), libMesh::FEAbstract::get_d2xyzdxi2(), libMesh::FEAbstract::get_d2xyzdxideta(), libMesh::FEAbstract::get_detadx(), libMesh::FEAbstract::get_detady(), libMesh::FEAbstract::get_detadz(), libMesh::FEAbstract::get_dxidx(), libMesh::FEAbstract::get_dxidy(), libMesh::FEAbstract::get_dxidz(), libMesh::FEAbstract::get_dxyzdeta(), libMesh::FEAbstract::get_dxyzdxi(), libMesh::FEAbstract::get_dxyzdzeta(), libMesh::FEAbstract::get_dzetadx(), libMesh::FEAbstract::get_dzetady(), libMesh::FEAbstract::get_dzetadz(), libMesh::FEAbstract::get_fe_map(), libMesh::FEAbstract::get_JxW(), libMesh::FEAbstract::get_normals(), libMesh::FEAbstract::get_tangents(), libMesh::FEAbstract::get_xyz(), libMesh::FESubdivision::init_shape_functions(), libMesh::FEAbstract::print_JxW(), and libMesh::FEAbstract::print_xyz().
UniquePtr<FETransformationBase<FEOutputType< T >::type > > libMesh::FEGenericBase< FEOutputType< T >::type >::_fe_trans protected inherited
Object that handles computing shape function values, gradients, etc in the physical domain.
Definition at line 506 of file fe_base.h.
Threads::spin_mutex libMesh::ReferenceCounter::_mutex static protected inherited
Mutual exclusion object to enable thread-safe reference counting.
Definition at line 127 of file reference_counter.h.
Threads::atomic< unsigned int > libMesh::ReferenceCounter::_n_objects static protected inherited
The number of objects. Print the reference count information when the number returns to 0.
Definition at line 122 of file reference_counter.h.
Referenced by libMesh::ReferenceCounter::n_objects(), libMesh::ReferenceCounter::ReferenceCounter(), and libMesh::ReferenceCounter::~ReferenceCounter().
unsigned int libMesh::FEAbstract::_p_level protected inherited
The p refinement level the current data structures are set up for.
Definition at line 571 of file fe_abstract.h.
Referenced by libMesh::FEAbstract::get_order(), and libMesh::FEAbstract::get_p_level().
std::vector<Point> libMesh::FE< Dim, T >::cached_nodes protected inherited
An array of the node locations on the last element we computed on
Definition at line 470 of file fe.h.
bool libMesh::FEAbstract::calculate_curl_phi mutable protected inherited
Should we calculate shape function curls?
Definition at line 542 of file fe_abstract.h.
Referenced by libMesh::FEGenericBase< FEOutputType< T >::type >::get_curl_phi().
bool libMesh::FEAbstract::calculate_d2phi mutable protected inherited
Should we calculate shape function hessians?
Definition at line 537 of file fe_abstract.h.
bool libMesh::FEAbstract::calculate_div_phi mutable protected inherited
Should we calculate shape function divergences?
Definition at line 547 of file fe_abstract.h.
Referenced by libMesh::FEGenericBase< FEOutputType< T >::type >::get_div_phi().
bool libMesh::FEAbstract::calculate_dphi mutable protected inherited
Should we calculate shape function gradients?
Definition at line 532 of file fe_abstract.h.
Referenced by libMesh::FEGenericBase< FEOutputType< T >::type >::get_dphi(), libMesh::FEGenericBase< FEOutputType< T >::type >::get_dphidx(), libMesh::FEGenericBase< FEOutputType< T >::type >::get_dphidy(), and libMesh::FEGenericBase< FEOutputType< T >::type >::get_dphidz().
bool libMesh::FEAbstract::calculate_dphiref mutable protected inherited
Should we calculate reference shape function gradients?
Definition at line 552 of file fe_abstract.h.
Referenced by libMesh::FEGenericBase< FEOutputType< T >::type >::get_curl_phi(), libMesh::FEGenericBase< FEOutputType< T >::type >::get_div_phi(), libMesh::FEGenericBase< FEOutputType< T >::type >::get_dphi(), libMesh::FEGenericBase< FEOutputType< T >::type >::get_dphideta(), libMesh::FEGenericBase< FEOutputType< T >::type >::get_dphidx(), libMesh::FEGenericBase< FEOutputType< T >::type >::get_dphidxi(), libMesh::FEGenericBase< FEOutputType< T >::type >::get_dphidy(), libMesh::FEGenericBase< FEOutputType< T >::type >::get_dphidz(), and libMesh::FEGenericBase< FEOutputType< T >::type >::get_dphidzeta().
bool libMesh::FEAbstract::calculate_phi mutable protected inherited
Should we calculate shape functions?
Definition at line 527 of file fe_abstract.h.
Referenced by libMesh::FEGenericBase< FEOutputType< T >::type >::get_phi().
bool libMesh::FEAbstract::calculations_started mutable protected inherited
Have calculations with this object already been started? Then all get_* functions should already have been called.
Definition at line 522 of file fe_abstract.h.
Referenced by libMesh::FEGenericBase< FEOutputType< T >::type >::get_curl_phi(), libMesh::FEGenericBase< FEOutputType< T >::type >::get_div_phi(), libMesh::FEGenericBase< FEOutputType< T >::type >::get_dphi(), libMesh::FEGenericBase< FEOutputType< T >::type >::get_dphideta(), libMesh::FEGenericBase< FEOutputType< T >::type >::get_dphidx(), libMesh::FEGenericBase< FEOutputType< T >::type >::get_dphidxi(), libMesh::FEGenericBase< FEOutputType< T >::type >::get_dphidy(), libMesh::FEGenericBase< FEOutputType< T >::type >::get_dphidz(), libMesh::FEGenericBase< FEOutputType< T >::type >::get_dphidzeta(), libMesh::FEGenericBase< FEOutputType< T >::type >::get_phi(), and libMesh::FESubdivision::init_shape_functions().
std::vector<std::vector<OutputShape> > libMesh::FEGenericBase< FEOutputType< T >::type >::curl_phi protected inherited
Shape function curl values. Only defined for vector types.
Definition at line 521 of file fe_base.h.
const unsigned int libMesh::FEAbstract::dim protected inherited
The dimensionality of the object
Definition at line 516 of file fe_abstract.h.
std::vector<std::vector<OutputDivergence> > libMesh::FEGenericBase< FEOutputType< T >::type >::div_phi protected inherited
Shape function divergence values. Only defined for vector types.
Definition at line 526 of file fe_base.h.
std::vector<std::vector<OutputGradient> > libMesh::FEGenericBase< FEOutputType< T >::type >::dphi protected inherited
Shape function derivative values.
Definition at line 516 of file fe_base.h.
Referenced by libMesh::FESubdivision::init_shape_functions().
std::vector<std::vector<OutputShape> > libMesh::FEGenericBase< FEOutputType< T >::type >::dphideta protected inherited
Shape function derivatives in the eta direction.
Definition at line 536 of file fe_base.h.
Referenced by libMesh::FESubdivision::init_shape_functions().
std::vector<std::vector<OutputShape> > libMesh::FEGenericBase< FEOutputType< T >::type >::dphidx protected inherited
Shape function derivatives in the x direction.
Definition at line 546 of file fe_base.h.
std::vector<std::vector<OutputShape> > libMesh::FEGenericBase< FEOutputType< T >::type >::dphidxi protected inherited
Shape function derivatives in the xi direction.
Definition at line 531 of file fe_base.h.
Referenced by libMesh::FESubdivision::init_shape_functions().
std::vector<std::vector<OutputShape> > libMesh::FEGenericBase< FEOutputType< T >::type >::dphidy protected inherited
Shape function derivatives in the y direction.
Definition at line 551 of file fe_base.h.
std::vector<std::vector<OutputShape> > libMesh::FEGenericBase< FEOutputType< T >::type >::dphidz protected inherited
Shape function derivatives in the z direction.
Definition at line 556 of file fe_base.h.
std::vector<std::vector<OutputShape> > libMesh::FEGenericBase< FEOutputType< T >::type >::dphidzeta protected inherited
Shape function derivatives in the zeta direction.
Definition at line 541 of file fe_base.h.
ElemType libMesh::FEAbstract::elem_type protected inherited
The element type the current data structures are set up for.
Definition at line 565 of file fe_abstract.h.
Referenced by libMesh::FESubdivision::attach_quadrature_rule(), and libMesh::FEAbstract::get_type().
FEType libMesh::FEAbstract::fe_type protected inherited
The finite element type for this object. Note that this should be constant for the object.
Definition at line 559 of file fe_abstract.h.
Referenced by libMesh::FEAbstract::get_family(), libMesh::FEAbstract::get_fe_type(), libMesh::FEAbstract::get_order(), libMesh::FESubdivision::init_shape_functions(), and libMesh::FEAbstract::set_fe_order().
unsigned int libMesh::FE< Dim, T >::last_edge protected inherited
Definition at line 477 of file fe.h.
ElemType libMesh::FE< Dim, T >::last_side protected inherited
The last side and last edge we did a reinit on
Definition at line 475 of file fe.h.
std::vector<std::vector<OutputShape> > libMesh::FEGenericBase< FEOutputType< T >::type >::phi protected inherited
Shape function values.
Definition at line 511 of file fe_base.h.
Referenced by libMesh::FESubdivision::init_shape_functions().
QBase* libMesh::FEAbstract::qrule protected inherited
A pointer to the quadrature rule employed
Definition at line 576 of file fe_abstract.h.
Referenced by libMesh::FESubdivision::attach_quadrature_rule().
bool libMesh::FEAbstract::shapes_on_quadrature protected inherited
A flag indicating if current data structures correspond to quadrature rule points
Definition at line 582 of file fe_abstract.h.
The documentation for this class was generated from the following files:
fe.h
fe_xyz.C
fe_xyz_boundary.C