libMesh: libMesh::RBThetaExpansion Class Reference
SomeWebsiteLogo
libMesh::RBThetaExpansion Class Reference
#include <rb_theta_expansion.h>
Public Member Functions
RBThetaExpansion ()
virtual ~RBThetaExpansion ()
virtual Number eval_A_theta (unsigned int q, const RBParameters &mu)
virtual Number eval_F_theta (unsigned int q, const RBParameters &mu)
virtual Number eval_output_theta (unsigned int output_index, unsigned int q_l, const RBParameters &mu)
unsigned int get_n_A_terms () const
unsigned int get_n_F_terms () const
unsigned int get_n_outputs () const
unsigned int get_n_output_terms (unsigned int output_index) const
virtual void attach_A_theta (RBTheta *theta_q_a)
virtual void attach_multiple_A_theta (std::vector< std::unique_ptr< RBTheta >> &theta_q_a)
virtual void attach_F_theta (RBTheta *theta_q_f)
virtual void attach_multiple_F_theta (std::vector< std::unique_ptr< RBTheta >> &theta_q_f)
virtual void attach_output_theta (std::vector< std::unique_ptr< RBTheta >> &theta_q_l)
virtual void attach_output_theta (std::vector< RBTheta *> theta_q_l)
virtual void attach_output_theta (RBTheta *theta_q_l)
Static Public Member Functions
static std::string get_info ()
static void print_info (std::ostream &out=libMesh::out)
static unsigned int n_objects ()
static void enable_print_counter_info ()
static void disable_print_counter_info ()
Protected Types
typedef std::map< std::string, std::pair< unsigned int, unsigned int > > Counts
Protected Member Functions
void increment_constructor_count (const std::string &name)
void increment_destructor_count (const std::string &name)
Static Protected Attributes
static Counts _counts
static Threads::atomic< unsigned int > _n_objects
static Threads::spin_mutex _mutex
static bool _enable_print_counter = true
Private Attributes
std::vector< RBTheta * > _A_theta_vector
std::vector< RBTheta * > _F_theta_vector
std::vector< std::vector< RBTheta * > > _output_theta_vector
Detailed Description
This class stores the set of RBTheta functor objects that define the "parameter-dependent expansion" of a PDE.
Author
David J. Knezevic
Date
2011
Definition at line 44 of file rb_theta_expansion.h.
Member Typedef Documentation
Counts
typedef std::map<std::string, std::pair<unsigned int, unsigned int> > libMesh::ReferenceCounter::Counts protected inherited
Data structure to log the information. The log is identified by the class name.
Definition at line 117 of file reference_counter.h.
Constructor & Destructor Documentation
RBThetaExpansion()
libMesh::RBThetaExpansion::RBThetaExpansion ()
Constructor.
~RBThetaExpansion()
virtual libMesh::RBThetaExpansion::~RBThetaExpansion () inline virtual
Destructor.
Definition at line 56 of file rb_theta_expansion.h.
 {}
Member Function Documentation
attach_A_theta()
virtual void libMesh::RBThetaExpansion::attach_A_theta (RBTheta * theta_q_a) virtual
Attach a pointer to a functor object that defines one of the theta_q_a terms.
attach_F_theta()
virtual void libMesh::RBThetaExpansion::attach_F_theta (RBTheta * theta_q_f) virtual
Attach a pointer to a functor object that defines one of the theta_q_a terms.
attach_multiple_A_theta()
virtual void libMesh::RBThetaExpansion::attach_multiple_A_theta (std::vector< std::unique_ptr< RBTheta >> & theta_q_a) virtual
Attach a vector of pointers to functor objects that each define one of the theta_q_a terms.
attach_multiple_F_theta()
virtual void libMesh::RBThetaExpansion::attach_multiple_F_theta (std::vector< std::unique_ptr< RBTheta >> & theta_q_f) virtual
Attach a vector of pointers to functor objects that each define one of the theta_q_f terms.
attach_output_theta() [1/3]
virtual void libMesh::RBThetaExpansion::attach_output_theta (std::vector< std::unique_ptr< RBTheta >> & theta_q_l) virtual
Attach a vector of pointers to functor objects that define one of the outputs.
attach_output_theta() [2/3]
virtual void libMesh::RBThetaExpansion::attach_output_theta (std::vector< RBTheta *> theta_q_l) virtual
Attach a vector of pointers to functor objects that define one of the outputs.
attach_output_theta() [3/3]
virtual void libMesh::RBThetaExpansion::attach_output_theta (RBTheta * theta_q_l) virtual
Attach a pointer to a functor object that defines one of the outputs.
disable_print_counter_info()
void libMesh::ReferenceCounter::disable_print_counter_info () static inherited
Definition at line 106 of file reference_counter.C.
References libMesh::ReferenceCounter::_enable_print_counter.
Referenced by libMesh::LibMeshInit::LibMeshInit().
 {
   _enable_print_counter = false;
   return;
 }
enable_print_counter_info()
void libMesh::ReferenceCounter::enable_print_counter_info () static inherited
Methods to enable/disable the reference counter output from print_info()
Definition at line 100 of file reference_counter.C.
References libMesh::ReferenceCounter::_enable_print_counter.
 {
   _enable_print_counter = true;
   return;
 }
eval_A_theta()
virtual Number libMesh::RBThetaExpansion::eval_A_theta (unsigned int q, const RBParameters & mu) virtual
Evaluate theta_q_a at the current parameter. Override if the theta functions need to be treated differently in subclasses.
eval_F_theta()
virtual Number libMesh::RBThetaExpansion::eval_F_theta (unsigned int q, const RBParameters & mu) virtual
Evaluate theta_q_f at the current parameter.
eval_output_theta()
virtual Number libMesh::RBThetaExpansion::eval_output_theta (unsigned int output_index, unsigned int q_l, const RBParameters & mu) virtual
Evaluate theta_q_l at the current parameter.
get_info()
std::string libMesh::ReferenceCounter::get_info () static inherited
Gets a string containing the reference information.
Definition at line 47 of file reference_counter.C.
References libMesh::ReferenceCounter::_counts, and libMesh::Quality::name().
Referenced by libMesh::ReferenceCounter::print_info().
 {
 #if defined(LIBMESH_ENABLE_REFERENCE_COUNTING) && defined(DEBUG)
   std::ostringstream oss;
   oss << '\n'
       << " ---------------------------------------------------------------------------- \n"
       << "| Reference count information                                                |\n"
       << " ---------------------------------------------------------------------------- \n";
   for (const auto & pr : _counts)
     {
       const std::string name(pr.first);
       const unsigned int creations    = pr.second.first;
       const unsigned int destructions = pr.second.second;
       oss << "| " << name << " reference count information:\n"
           << "|  Creations:    " << creations    << '\n'
           << "|  Destructions: " << destructions << '\n';
     }
   oss << " ---------------------------------------------------------------------------- \n";
   return oss.str();
 #else
   return "";
 #endif
 }
get_n_A_terms()
unsigned int libMesh::RBThetaExpansion::get_n_A_terms () const
Get Q_a, the number of terms in the affine expansion for the bilinear form.
get_n_F_terms()
unsigned int libMesh::RBThetaExpansion::get_n_F_terms () const
Get Q_f, the number of terms in the affine expansion for the right-hand side.
get_n_output_terms()
unsigned int libMesh::RBThetaExpansion::get_n_output_terms (unsigned int output_index) const
Get the number of affine terms associated with the specified output.
get_n_outputs()
unsigned int libMesh::RBThetaExpansion::get_n_outputs () const
Get n_outputs, the number output functionals.
increment_constructor_count()
void libMesh::ReferenceCounter::increment_constructor_count (const std::string & name) inline protected inherited
Increments the construction counter. Should be called in the constructor of any derived class that will be reference counted.
Definition at line 181 of file reference_counter.h.
References libMesh::ReferenceCounter::_counts, libMesh::Quality::name(), and libMesh::Threads::spin_mtx.
Referenced by libMesh::ReferenceCountedObject< RBParametrized >::ReferenceCountedObject().
 {
   Threads::spin_mutex::scoped_lock lock(Threads::spin_mtx);
   std::pair<unsigned int, unsigned int> & p = _counts[name];
   p.first++;
 }
increment_destructor_count()
void libMesh::ReferenceCounter::increment_destructor_count (const std::string & name) inline protected inherited
Increments the destruction counter. Should be called in the destructor of any derived class that will be reference counted.
Definition at line 194 of file reference_counter.h.
References libMesh::ReferenceCounter::_counts, libMesh::Quality::name(), and libMesh::Threads::spin_mtx.
Referenced by libMesh::ReferenceCountedObject< RBParametrized >::~ReferenceCountedObject().
 {
   Threads::spin_mutex::scoped_lock lock(Threads::spin_mtx);
   std::pair<unsigned int, unsigned int> & p = _counts[name];
   p.second++;
 }
n_objects()
static unsigned int libMesh::ReferenceCounter::n_objects () inline static inherited
Prints the number of outstanding (created, but not yet destroyed) objects.
Definition at line 83 of file reference_counter.h.
References libMesh::ReferenceCounter::_n_objects.
   { return _n_objects; }
print_info()
void libMesh::ReferenceCounter::print_info (std::ostream & out = libMesh::out) static inherited
Prints the reference information, by default to libMesh::out.
Definition at line 87 of file reference_counter.C.
References libMesh::ReferenceCounter::_enable_print_counter, and libMesh::ReferenceCounter::get_info().
 {
   if (_enable_print_counter)
     out_stream << ReferenceCounter::get_info();
 }
Member Data Documentation
_A_theta_vector
std::vector<RBTheta *> libMesh::RBThetaExpansion::_A_theta_vector private
Vector storing the pointers to the RBTheta functors for A.
Definition at line 149 of file rb_theta_expansion.h.
_counts
ReferenceCounter::Counts libMesh::ReferenceCounter::_counts static protected inherited
Actually holds the data.
Definition at line 122 of file reference_counter.h.
Referenced by libMesh::ReferenceCounter::get_info(), libMesh::ReferenceCounter::increment_constructor_count(), and libMesh::ReferenceCounter::increment_destructor_count().
_enable_print_counter
bool libMesh::ReferenceCounter::_enable_print_counter = true static protected inherited
Flag to control whether reference count information is printed when print_info is called.
Definition at line 141 of file reference_counter.h.
Referenced by libMesh::ReferenceCounter::disable_print_counter_info(), libMesh::ReferenceCounter::enable_print_counter_info(), and libMesh::ReferenceCounter::print_info().
_F_theta_vector
std::vector<RBTheta *> libMesh::RBThetaExpansion::_F_theta_vector private
Vector storing the RBTheta functors for the affine expansion of the rhs.
Definition at line 154 of file rb_theta_expansion.h.
_mutex
Threads::spin_mutex libMesh::ReferenceCounter::_mutex static protected inherited
Mutual exclusion object to enable thread-safe reference counting.
Definition at line 135 of file reference_counter.h.
_n_objects
Threads::atomic< unsigned int > libMesh::ReferenceCounter::_n_objects static protected inherited
The number of objects. Print the reference count information when the number returns to 0.
Definition at line 130 of file reference_counter.h.
Referenced by libMesh::ReferenceCounter::n_objects(), libMesh::ReferenceCounter::ReferenceCounter(), and libMesh::ReferenceCounter::~ReferenceCounter().
_output_theta_vector
std::vector<std::vector<RBTheta *> > libMesh::RBThetaExpansion::_output_theta_vector private
Vector storing the RBTheta functors for the affine expansion of the outputs.
Definition at line 159 of file rb_theta_expansion.h.
The documentation for this class was generated from the following file:
rb_theta_expansion.h