libMesh: libMesh::GhostingFunctor Class Reference
SomeWebsiteLogo
libMesh::GhostingFunctor Class Reference abstract
#include <ghosting_functor.h>
Public Types
typedef LIBMESH_BEST_UNORDERED_MAP< const Elem *, const CouplingMatrix * > map_type
Public Member Functions
GhostingFunctor ()
virtual ~GhostingFunctor ()
virtual void operator() (const MeshBase::const_element_iterator &range_begin, const MeshBase::const_element_iterator &range_end, processor_id_type p, map_type &coupled_elements)=0
virtual void mesh_reinit ()
virtual void dofmap_reinit ()
virtual void redistribute ()
virtual void delete_remote_elements ()
Static Public Member Functions
static std::string get_info ()
static void print_info (std::ostream &out=libMesh::out)
static unsigned int n_objects ()
static void enable_print_counter_info ()
static void disable_print_counter_info ()
Protected Types
typedef std::map< std::string, std::pair< unsigned int, unsigned int > > Counts
Protected Member Functions
void increment_constructor_count (const std::string &name)
void increment_destructor_count (const std::string &name)
Static Protected Attributes
static Counts _counts
static Threads::atomic< unsigned int > _n_objects
static Threads::spin_mutex _mutex
static bool _enable_print_counter = true
Detailed Description
This abstract base class defines the interface by which library code and user code can report associations between elements. These associations between elements may be used to keep copies of non-local elements retained on a distributed mesh, may be used to keep element degrees of freedom properly communicated on a distributed vector, and/or may be used to insert coupling entries between elements' degrees of freedom to a sparsity matrix.
We can think of three levels of "element dependencies". An element K1 has a coupling dependency on K2 if the dofs on K1 might (modulo the coupling matrix) need sparsity pattern entries for dofs on K2. An element K1 has an algebraic dependency on K2 if a processor which owns K1 might need to examine the solution dof values on K2. An element K1 has a geometric dependency on K2 if a processor which owns K1 might need to examine the geometry of K2. For any element K, we could call the set of coupling-ghosted ("coupled") elements C(K), call the set of algebraic-ghosted ("evaluable") elements E(K), and call the set of geometry-ghosted ("ghosted") elements G(K).
It should be safe to assume that, for any element K, C(K) implies E(K) implies G(K). These will be one-way implications in some problems and equality relations in others.
We can think of these as operators on sets of elements in the obvious way, e.g.: G({K}) = {G(Ki) for all Ki in {K}}.
The user should omit from their implementations relations which we already have enough information to understand implicitly. For instance, K is obviously in C(K), so a GhostingFunctor should never bother telling us so. We may have a PeriodicBoundary, a hanging node constraint equation, or a user-defined constraint equation which creates a dependency between two elements; if so then we don't need the user to also tell us about that relation (although a PeriodicBoundary use will cause the library to create its own PeriodicGhostingFunctor for internal use).
Users may only care about a subset of variables in distant evaluable elements, so we could imagine defining E_v(K) for each variable number v, in which case E(K) under our previous definition is the union of E_v(K) forall v, and this is what would be included in G(K) when deciding what to ghost, but our send_list would only include the subset of variables we need, so communication and memory use would be much reduced. However, for efficiency and API simplicity, we instead define the isomorphic operator E'(K) which gives a set of ordered pairs of elements and variable-number-sets, from which a consistent E(K) would be derived by ignoring the variable-number-sets.
For C(K), there are similar issues: e.g. we may want some discontinuous variables to couple only within their own element but other discontinuous variables to couple in a DG/FVM way. This could extend to more than one variable index: i.e. a dof for variable v1 in element K1 would depend on a dof for variable v2 in element K2 iff K2 is in C_v1_v2(K1). This would induce a consistent E_v(K) = union of C_w_v(K) forall variable indices w. Again, the equivalent API alternative we use here is for C'(K) to return a set of ordered pairs of elements and variable-number-pair-sets.
We return variable-stuff-sets as pointers to CouplingMatrix. That way, in the common case where the user cares about all variables and couple to all variables, all the functor needs to return for variable-number-sets and variable-number-pair-sets is a NULL (which as in other libMesh APIs will be interpreted and documented to mean the full set). In the common case where the user wants coupling between elements to match coupling within elements, the functor can return the same pointer as DofMap::_coupling_matrix. Even in the less common cases, the user can store common variable-number-sets and variable-number-pair sets as CouplingMatrix members of a functor object of their subclass, and setting up a few of those matrices then setting lots of those pointers is cheap.
The definition of the CouplingMatrix for a variable-dependent E' should be consistent with the requirements that would have been imposed had that matrix been used for a C'. In other words, if the returned CouplingMatrix CM has CM(i,j)==true for any i, then variable j will be evaluable on the algebraically ghosted element.
Author
Roy H. Stogner
Date
2016
Definition at line 122 of file ghosting_functor.h.
Member Typedef Documentation
typedef std::map<std::string, std::pair<unsigned int, unsigned int> > libMesh::ReferenceCounter::Counts protected inherited
Data structure to log the information. The log is identified by the class name.
Definition at line 119 of file reference_counter.h.
typedef LIBMESH_BEST_UNORDERED_MAP<const Elem*, const CouplingMatrix*> libMesh::GhostingFunctor::map_type
What elements do we care about and what variables do we care about on each element?
Definition at line 140 of file ghosting_functor.h.
Constructor & Destructor Documentation
libMesh::GhostingFunctor::GhostingFunctor () inline
Constructor. Empty in the base class.
Definition at line 129 of file ghosting_functor.h.
 {}
virtual libMesh::GhostingFunctor::~GhostingFunctor () inline virtual
Virtual destructor; this is an abstract base class.
Definition at line 134 of file ghosting_functor.h.
 {}
Member Function Documentation
virtual void libMesh::GhostingFunctor::delete_remote_elements () inline virtual
GhostingFunctor subclasses with relatively long-lasting caches may want to delete the no-longer-relevant parts of those caches after a redistribution is complete.
Reimplemented in libMesh::PointNeighborCoupling, and libMesh::DefaultCoupling.
Definition at line 190 of file ghosting_functor.h.
Referenced by libMesh::MeshCommunication::delete_remote_elements().
 {};
void libMesh::ReferenceCounter::disable_print_counter_info () static inherited
Definition at line 107 of file reference_counter.C.
References libMesh::ReferenceCounter::_enable_print_counter.
Referenced by libMesh::LibMeshInit::LibMeshInit(), and libMesh::ReferenceCounter::n_objects().
 {
   _enable_print_counter = false;
   return;
 }
virtual void libMesh::GhostingFunctor::dofmap_reinit () inline virtual
For algebraic ghosting or coupling functors we also call dofmap_reinit() later, after dofs have been distributed on the new mesh but before the functors have been queried for send_list or sparsity pattern calculations.
Definition at line 171 of file ghosting_functor.h.
Referenced by libMesh::DofMap::distribute_dofs().
 {};
void libMesh::ReferenceCounter::enable_print_counter_info () static inherited
Methods to enable/disable the reference counter output from print_info()
Definition at line 101 of file reference_counter.C.
References libMesh::ReferenceCounter::_enable_print_counter.
Referenced by libMesh::ReferenceCounter::n_objects().
 {
   _enable_print_counter = true;
   return;
 }
std::string libMesh::ReferenceCounter::get_info () static inherited
Gets a string containing the reference information.
Definition at line 47 of file reference_counter.C.
References libMesh::ReferenceCounter::_counts, and libMesh::Quality::name().
Referenced by libMesh::ReferenceCounter::print_info().
 {
 #if defined(LIBMESH_ENABLE_REFERENCE_COUNTING) && defined(DEBUG)
   std::ostringstream oss;
   oss << '\n'
       << " ---------------------------------------------------------------------------- \n"
       << "| Reference count information                                                |\n"
       << " ---------------------------------------------------------------------------- \n";
   for (Counts::iterator it = _counts.begin();
        it != _counts.end(); ++it)
     {
       const std::string name(it->first);
       const unsigned int creations    = it->second.first;
       const unsigned int destructions = it->second.second;
       oss << "| " << name << " reference count information:\n"
           << "|  Creations:    " << creations    << '\n'
           << "|  Destructions: " << destructions << '\n';
     }
   oss << " ---------------------------------------------------------------------------- \n";
   return oss.str();
 #else
   return "";
 #endif
 }
void libMesh::ReferenceCounter::increment_constructor_count (const std::string & name) inline protected inherited
Increments the construction counter. Should be called in the constructor of any derived class that will be reference counted.
Definition at line 185 of file reference_counter.h.
References libMesh::ReferenceCounter::_counts, libMesh::Quality::name(), and libMesh::Threads::spin_mtx.
Referenced by libMesh::ReferenceCounter::n_objects(), and libMesh::ReferenceCountedObject< RBParametrized >::ReferenceCountedObject().
 {
   Threads::spin_mutex::scoped_lock lock(Threads::spin_mtx);
   std::pair<unsigned int, unsigned int> & p = _counts[name];
   p.first++;
 }
void libMesh::ReferenceCounter::increment_destructor_count (const std::string & name) inline protected inherited
Increments the destruction counter. Should be called in the destructor of any derived class that will be reference counted.
Definition at line 198 of file reference_counter.h.
References libMesh::ReferenceCounter::_counts, libMesh::Quality::name(), and libMesh::Threads::spin_mtx.
Referenced by libMesh::ReferenceCounter::n_objects(), and libMesh::ReferenceCountedObject< RBParametrized >::~ReferenceCountedObject().
 {
   Threads::spin_mutex::scoped_lock lock(Threads::spin_mtx);
   std::pair<unsigned int, unsigned int> & p = _counts[name];
   p.second++;
 }
virtual void libMesh::GhostingFunctor::mesh_reinit () inline virtual
GhostingFunctor subclasses which cache data will need to initialize that cache. We call mesh_reinit() whenever the relevant Mesh has changed, but before remote elements on a distributed mesh are deleted.
Reimplemented in libMesh::PointNeighborCoupling, and libMesh::DefaultCoupling.
Definition at line 163 of file ghosting_functor.h.
Referenced by libMesh::UnstructuredMesh::contract(), and libMesh::MeshBase::prepare_for_use().
 {};
static unsigned int libMesh::ReferenceCounter::n_objects () inline static inherited
Prints the number of outstanding (created, but not yet destroyed) objects.
Definition at line 85 of file reference_counter.h.
References libMesh::ReferenceCounter::_n_objects, libMesh::ReferenceCounter::disable_print_counter_info(), libMesh::ReferenceCounter::enable_print_counter_info(), libMesh::ReferenceCounter::increment_constructor_count(), libMesh::ReferenceCounter::increment_destructor_count(), and libMesh::Quality::name().
Referenced by libMesh::System::hide_output(), and libMesh::LibMeshInit::LibMeshInit().
   { return _n_objects; }
virtual void libMesh::GhostingFunctor::operator() (const MeshBase::const_element_iterator & range_begin, const MeshBase::const_element_iterator & range_end, processor_id_type p, map_type & coupled_elements) pure virtual
For the specified range of active elements, what other elements currently living (whether local or ghosted) on this processor need to be coupled/ghosted to accommodate them? Don't bother to return any results which already have processor_id p.
This API is new, and we should replace "ignoring those on processor p" with "ignoring those which match a predicate functor" eventually.
Implemented in libMesh::DefaultCoupling, libMesh::PointNeighborCoupling, libMesh::SiblingCoupling, and libMesh::GhostPointNeighbors.
void libMesh::ReferenceCounter::print_info (std::ostream & out = libMesh::out) static inherited
Prints the reference information, by default to libMesh::out.
Definition at line 88 of file reference_counter.C.
References libMesh::ReferenceCounter::_enable_print_counter, and libMesh::ReferenceCounter::get_info().
Referenced by libMesh::LibMeshInit::LibMeshInit().
 {
   if (_enable_print_counter)
     out_stream << ReferenceCounter::get_info();
 }
virtual void libMesh::GhostingFunctor::redistribute () inline virtual
GhostingFunctor subclasses with relatively long-lasting caches may want to redistribute those caches whenever the relevant Mesh is redistributed; we will give them an opportunity when that happens. At the point in the code where this is called, element processor ids have been set to their new destinations, and those elements have been copied to their new destinations, but the elements have not yet been deleted by the processors which previously held them..
Reimplemented in libMesh::PointNeighborCoupling, and libMesh::DefaultCoupling.
Definition at line 183 of file ghosting_functor.h.
Referenced by libMesh::MeshCommunication::redistribute().
 {};
Member Data Documentation
ReferenceCounter::Counts libMesh::ReferenceCounter::_counts static protected inherited
Actually holds the data.
Definition at line 124 of file reference_counter.h.
Referenced by libMesh::ReferenceCounter::get_info(), libMesh::ReferenceCounter::increment_constructor_count(), and libMesh::ReferenceCounter::increment_destructor_count().
bool libMesh::ReferenceCounter::_enable_print_counter = true static protected inherited
Flag to control whether reference count information is printed when print_info is called.
Definition at line 143 of file reference_counter.h.
Referenced by libMesh::ReferenceCounter::disable_print_counter_info(), libMesh::ReferenceCounter::enable_print_counter_info(), and libMesh::ReferenceCounter::print_info().
Threads::spin_mutex libMesh::ReferenceCounter::_mutex static protected inherited
Mutual exclusion object to enable thread-safe reference counting.
Definition at line 137 of file reference_counter.h.
Threads::atomic< unsigned int > libMesh::ReferenceCounter::_n_objects static protected inherited
The number of objects. Print the reference count information when the number returns to 0.
Definition at line 132 of file reference_counter.h.
Referenced by libMesh::ReferenceCounter::n_objects(), libMesh::ReferenceCounter::ReferenceCounter(), and libMesh::ReferenceCounter::~ReferenceCounter().
The documentation for this class was generated from the following file:
ghosting_functor.h