libMesh: libMesh::QGaussLobatto Class Reference
SomeWebsiteLogo
libMesh::QGaussLobatto Class Reference
Implements 1D and 2/3D tensor product Gauss-Lobatto quadrature rules.
#include <quadrature_gauss_lobatto.h>
Public Member Functions
QGaussLobatto (const unsigned int _dim, const Order _order=INVALID_ORDER)
~QGaussLobatto ()
virtual QuadratureType type () const libmesh_override
ElemType get_elem_type () const
unsigned int get_p_level () const
unsigned int n_points () const
unsigned int get_dim () const
const std::vector< Point > & get_points () const
std::vector< Point > & get_points ()
const std::vector< Real > & get_weights () const
std::vector< Real > & get_weights ()
Point qp (const unsigned int i) const
Real w (const unsigned int i) const
virtual void init (const ElemType type=INVALID_ELEM, unsigned int p_level=0)
virtual void init (const Elem &elem, const std::vector< Real > &vertex_distance_func, unsigned int p_level=0)
Order get_order () const
void print_info (std::ostream &os=libMesh::out) const
void scale (std::pair< Real, Real > old_range, std::pair< Real, Real > new_range)
virtual bool shapes_need_reinit ()
Static Public Member Functions
static UniquePtr< QBase > build (const std::string &name, const unsigned int dim, const Order order=INVALID_ORDER)
static UniquePtr< QBase > build (const QuadratureType qt, const unsigned int dim, const Order order=INVALID_ORDER)
static void print_info (std::ostream &out=libMesh::out)
static std::string get_info ()
static unsigned int n_objects ()
static void enable_print_counter_info ()
static void disable_print_counter_info ()
Public Attributes
bool allow_rules_with_negative_weights
Protected Types
typedef std::map< std::string, std::pair< unsigned int, unsigned int > > Counts
Protected Member Functions
virtual void init_0D (const ElemType type=INVALID_ELEM, unsigned int p_level=0)
void tensor_product_quad (const QBase &q1D)
void tensor_product_hex (const QBase &q1D)
void tensor_product_prism (const QBase &q1D, const QBase &q2D)
void increment_constructor_count (const std::string &name)
void increment_destructor_count (const std::string &name)
Protected Attributes
const unsigned int _dim
const Order _order
ElemType _type
unsigned int _p_level
std::vector< Point > _points
std::vector< Real > _weights
Static Protected Attributes
static Counts _counts
static Threads::atomic< unsigned int > _n_objects
static Threads::spin_mutex _mutex
static bool _enable_print_counter = true
Private Member Functions
virtual void init_1D (const ElemType _type=INVALID_ELEM, unsigned int p_level=0) libmesh_override
virtual void init_2D (const ElemType _type=INVALID_ELEM, unsigned int p_level=0) libmesh_override
virtual void init_3D (const ElemType _type=INVALID_ELEM, unsigned int p_level=0) libmesh_override
Detailed Description
Implements 1D and 2/3D tensor product Gauss-Lobatto quadrature rules.
This class implements Gauss-Lobatto quadrature for 1D elements and 2D/3D tensor product elements. Properties of Gauss-Lobatto quadrature rules: .) Include the "end-points" of the domain (have points on edges/faces in 2D/3D). .) Rules with n points can exactly integrate polynomials of degree 2n-3.
http://en.wikipedia.org/wiki/Gaussian_quadrature#Gauss.E2.80.93Lobatto_rules
Author
John W. Peterson
Date
2014
Definition at line 41 of file quadrature_gauss_lobatto.h.
Member Typedef Documentation
typedef std::map<std::string, std::pair<unsigned int, unsigned int> > libMesh::ReferenceCounter::Counts protected inherited
Data structure to log the information. The log is identified by the class name.
Definition at line 119 of file reference_counter.h.
Constructor & Destructor Documentation
libMesh::QGaussLobatto::QGaussLobatto (const unsigned int _dim, const Order _order = INVALID_ORDER)
Constructor. Declares the order of the quadrature rule.
Definition at line 33 of file quadrature_gauss_lobatto.C.
References libMesh::QBase::_dim, libMesh::EDGE2, and libMesh::QBase::init().
                                             : QBase(d,o)
 {
   // explicitly call the init function in 1D since the
   // other tensor-product rules require this one.
   // note that EDGE will not be used internally, however
   // if we called the function with INVALID_ELEM it would try to
   // be smart and return, thinking it had already done the work.
   if (_dim == 1)
     init(EDGE2);
 }
libMesh::QGaussLobatto::~QGaussLobatto ()
Destructor.
Definition at line 47 of file quadrature_gauss_lobatto.C.
 {
 }
Member Function Documentation
UniquePtr< QBase > libMesh::QBase::build (const std::string & name, const unsigned int dim, const Order order = INVALID_ORDER) static inherited
Builds a specific quadrature rule based on the name string. This enables selection of the quadrature rule at run-time. The input parameter name must be mappable through the Utility::string_to_enum<>() function.
This function allocates memory, therefore a UniquePtr<QBase> is returned so that the user does not accidentally leak it.
Definition at line 42 of file quadrature_build.C.
Referenced by libMesh::InfFE< Dim, T_radial, T_map >::attach_quadrature_rule(), and libMesh::QBase::~QBase().
 {
   return QBase::build (Utility::string_to_enum<QuadratureType> (type),
                        _dim,
                        _order);
 }
UniquePtr< QBase > libMesh::QBase::build (const QuadratureType qt, const unsigned int dim, const Order order = INVALID_ORDER) static inherited
Builds a specific quadrature rule based on the QuadratureType. This enables selection of the quadrature rule at run-time.
This function allocates memory, therefore a UniquePtr<QBase> is returned so that the user does not accidentally leak it.
Definition at line 53 of file quadrature_build.C.
References libMesh::FIRST, libMesh::FORTYTHIRD, libMesh::out, libMesh::QCLOUGH, libMesh::QCONICAL, libMesh::QGAUSS, libMesh::QGAUSS_LOBATTO, libMesh::QGRID, libMesh::QGRUNDMANN_MOLLER, libMesh::QJACOBI_1_0, libMesh::QJACOBI_2_0, libMesh::QMONOMIAL, libMesh::QSIMPSON, libMesh::QTRAP, libMesh::THIRD, and libMesh::TWENTYTHIRD.
 {
   switch (_qt)
     {
     case QCLOUGH:
       {
 #ifdef DEBUG
         if (_order > TWENTYTHIRD)
           {
             libMesh::out << "WARNING: Clough quadrature implemented" << std::endl
                          << " up to TWENTYTHIRD order." << std::endl;
           }
 #endif
         return UniquePtr<QBase>(new QClough(_dim, _order));
       }
     case QGAUSS:
       {
 #ifdef DEBUG
         if (_order > FORTYTHIRD)
           {
             libMesh::out << "WARNING: Gauss quadrature implemented" << std::endl
                          << " up to FORTYTHIRD order." << std::endl;
           }
 #endif
         return UniquePtr<QBase>(new QGauss(_dim, _order));
       }
     case QJACOBI_1_0:
       {
 #ifdef DEBUG
         if (_order > FORTYTHIRD)
           {
             libMesh::out << "WARNING: Jacobi(1,0) quadrature implemented" << std::endl
                          << " up to FORTYTHIRD order." << std::endl;
           }
         if (_dim > 1)
           {
             libMesh::out << "WARNING: Jacobi(1,0) quadrature implemented" << std::endl
                          << " in 1D only." << std::endl;
           }
 #endif
         return UniquePtr<QBase>(new QJacobi(_dim, _order, 1, 0));
       }
     case QJACOBI_2_0:
       {
 #ifdef DEBUG
         if (_order > FORTYTHIRD)
           {
             libMesh::out << "WARNING: Jacobi(2,0) quadrature implemented" << std::endl
                          << " up to FORTYTHIRD order." << std::endl;
           }
         if (_dim > 1)
           {
             libMesh::out << "WARNING: Jacobi(2,0) quadrature implemented" << std::endl
                          << " in 1D only." << std::endl;
           }
 #endif
         return UniquePtr<QBase>(new QJacobi(_dim, _order, 2, 0));
       }
     case QSIMPSON:
       {
 #ifdef DEBUG
         if (_order > THIRD)
           {
             libMesh::out << "WARNING: Simpson rule provides only" << std::endl
                          << " THIRD order!" << std::endl;
           }
 #endif
         return UniquePtr<QBase>(new QSimpson(_dim));
       }
     case QTRAP:
       {
 #ifdef DEBUG
         if (_order > FIRST)
           {
             libMesh::out << "WARNING: Trapezoidal rule provides only" << std::endl
                          << " FIRST order!" << std::endl;
           }
 #endif
         return UniquePtr<QBase>(new QTrap(_dim));
       }
     case QGRID:
       return UniquePtr<QBase>(new QGrid(_dim, _order));
     case QGRUNDMANN_MOLLER:
       return UniquePtr<QBase>(new QGrundmann_Moller(_dim, _order));
     case QMONOMIAL:
       return UniquePtr<QBase>(new QMonomial(_dim, _order));
     case QGAUSS_LOBATTO:
       return UniquePtr<QBase>(new QGaussLobatto(_dim, _order));
     case QCONICAL:
       return UniquePtr<QBase>(new QConical(_dim, _order));
     default:
       libmesh_error_msg("ERROR: Bad qt=" << _qt);
     }
   libmesh_error_msg("We'll never get here!");
   return UniquePtr<QBase>();
 }
void libMesh::ReferenceCounter::disable_print_counter_info () static inherited
Definition at line 107 of file reference_counter.C.
References libMesh::ReferenceCounter::_enable_print_counter.
Referenced by libMesh::LibMeshInit::LibMeshInit(), and libMesh::ReferenceCounter::n_objects().
 {
   _enable_print_counter = false;
   return;
 }
void libMesh::ReferenceCounter::enable_print_counter_info () static inherited
Methods to enable/disable the reference counter output from print_info()
Definition at line 101 of file reference_counter.C.
References libMesh::ReferenceCounter::_enable_print_counter.
Referenced by libMesh::ReferenceCounter::n_objects().
 {
   _enable_print_counter = true;
   return;
 }
unsigned int libMesh::QBase::get_dim () const inline inherited
Returns
The spatial dimension of the quadrature rule.
Definition at line 122 of file quadrature.h.
References libMesh::QBase::_dim.
Referenced by libMesh::InfFE< Dim, T_radial, T_map >::attach_quadrature_rule(), libMesh::QConical::conical_product_pyramid(), libMesh::QConical::conical_product_tet(), and libMesh::QConical::conical_product_tri().
 { return _dim; }
ElemType libMesh::QBase::get_elem_type () const inline inherited
Returns
The element type we're currently using.
Definition at line 103 of file quadrature.h.
References libMesh::QBase::_type.
 { return _type; }
std::string libMesh::ReferenceCounter::get_info () static inherited
Gets a string containing the reference information.
Definition at line 47 of file reference_counter.C.
References libMesh::ReferenceCounter::_counts, and libMesh::Quality::name().
Referenced by libMesh::ReferenceCounter::print_info().
 {
 #if defined(LIBMESH_ENABLE_REFERENCE_COUNTING) && defined(DEBUG)
   std::ostringstream oss;
   oss << '\n'
       << " ---------------------------------------------------------------------------- \n"
       << "| Reference count information                                                |\n"
       << " ---------------------------------------------------------------------------- \n";
   for (Counts::iterator it = _counts.begin();
        it != _counts.end(); ++it)
     {
       const std::string name(it->first);
       const unsigned int creations    = it->second.first;
       const unsigned int destructions = it->second.second;
       oss << "| " << name << " reference count information:\n"
           << "|  Creations:    " << creations    << '\n'
           << "|  Destructions: " << destructions << '\n';
     }
   oss << " ---------------------------------------------------------------------------- \n";
   return oss.str();
 #else
   return "";
 #endif
 }
Order libMesh::QBase::get_order () const inline inherited
Returns
The order of the quadrature rule.
Definition at line 189 of file quadrature.h.
References libMesh::QBase::_order, libMesh::QBase::_p_level, libMesh::QBase::operator<<, libMesh::out, libMesh::QBase::print_info(), and libMesh::QBase::scale().
Referenced by libMesh::InfFE< Dim, T_radial, T_map >::attach_quadrature_rule().
 { return static_cast<Order>(_order + _p_level); }
unsigned int libMesh::QBase::get_p_level () const inline inherited
Returns
The p-refinement level we're currently using.
Definition at line 108 of file quadrature.h.
References libMesh::QBase::_p_level.
 { return _p_level; }
const std::vector<Point>& libMesh::QBase::get_points () const inline inherited
Returns
A std::vector containing the quadrature point locations in reference element space.
Definition at line 128 of file quadrature.h.
References libMesh::QBase::_points.
Referenced by libMesh::FESubdivision::attach_quadrature_rule(), libMesh::QClough::init_1D(), libMesh::QConical::init_1D(), libMesh::QMonomial::init_1D(), libMesh::QGrundmann_Moller::init_1D(), libMesh::QClough::init_2D(), libMesh::QGauss::init_2D(), libMesh::QMonomial::init_2D(), libMesh::QGauss::init_3D(), and libMesh::QMonomial::init_3D().
 { return _points; }
std::vector<Point>& libMesh::QBase::get_points () inline inherited
Returns
A std::vector containing the quadrature point locations in reference element space as a writable reference.
Definition at line 134 of file quadrature.h.
References libMesh::QBase::_points.
 { return _points; }
const std::vector<Real>& libMesh::QBase::get_weights () const inline inherited
Returns
A constant reference to a std::vector containing the quadrature weights.
Definition at line 140 of file quadrature.h.
References libMesh::QBase::_weights.
Referenced by libMesh::FESubdivision::attach_quadrature_rule(), libMesh::QClough::init_1D(), libMesh::QConical::init_1D(), libMesh::QMonomial::init_1D(), libMesh::QGrundmann_Moller::init_1D(), libMesh::QClough::init_2D(), libMesh::QGauss::init_2D(), libMesh::QMonomial::init_2D(), libMesh::QGauss::init_3D(), and libMesh::QMonomial::init_3D().
 { return _weights; }
std::vector<Real>& libMesh::QBase::get_weights () inline inherited
Returns
A writable references to a std::vector containing the quadrature weights.
Definition at line 146 of file quadrature.h.
References libMesh::QBase::_weights.
 { return _weights; }
void libMesh::ReferenceCounter::increment_constructor_count (const std::string & name) inline protected inherited
Increments the construction counter. Should be called in the constructor of any derived class that will be reference counted.
Definition at line 185 of file reference_counter.h.
References libMesh::ReferenceCounter::_counts, libMesh::Quality::name(), and libMesh::Threads::spin_mtx.
Referenced by libMesh::ReferenceCounter::n_objects(), and libMesh::ReferenceCountedObject< RBParametrized >::ReferenceCountedObject().
 {
   Threads::spin_mutex::scoped_lock lock(Threads::spin_mtx);
   std::pair<unsigned int, unsigned int> & p = _counts[name];
   p.first++;
 }
void libMesh::ReferenceCounter::increment_destructor_count (const std::string & name) inline protected inherited
Increments the destruction counter. Should be called in the destructor of any derived class that will be reference counted.
Definition at line 198 of file reference_counter.h.
References libMesh::ReferenceCounter::_counts, libMesh::Quality::name(), and libMesh::Threads::spin_mtx.
Referenced by libMesh::ReferenceCounter::n_objects(), and libMesh::ReferenceCountedObject< RBParametrized >::~ReferenceCountedObject().
 {
   Threads::spin_mutex::scoped_lock lock(Threads::spin_mtx);
   std::pair<unsigned int, unsigned int> & p = _counts[name];
   p.second++;
 }
void libMesh::QBase::init (const ElemType type = INVALID_ELEM, unsigned int p_level = 0) virtual inherited
Initializes the data structures for a quadrature rule for an element of type type.
Definition at line 28 of file quadrature.C.
References libMesh::QBase::_dim, libMesh::QBase::_p_level, libMesh::QBase::_type, libMesh::QBase::init_0D(), libMesh::QBase::init_1D(), libMesh::QBase::init_2D(), and libMesh::QBase::init_3D().
Referenced by libMesh::FESubdivision::attach_quadrature_rule(), libMesh::QBase::init(), libMesh::QClough::init_1D(), libMesh::QMonomial::init_1D(), libMesh::QClough::init_2D(), init_2D(), libMesh::QTrap::init_2D(), libMesh::QGrid::init_2D(), libMesh::QSimpson::init_2D(), libMesh::QGauss::init_2D(), libMesh::QMonomial::init_2D(), init_3D(), libMesh::QTrap::init_3D(), libMesh::QGrid::init_3D(), libMesh::QGauss::init_3D(), libMesh::QSimpson::init_3D(), libMesh::QMonomial::init_3D(), libMesh::QGauss::QGauss(), QGaussLobatto(), libMesh::QJacobi::QJacobi(), libMesh::QSimpson::QSimpson(), libMesh::QTrap::QTrap(), and libMesh::QBase::w().
 {
   // check to see if we have already
   // done the work for this quadrature rule
   if (t == _type && p == _p_level)
     return;
   else
     {
       _type = t;
       _p_level = p;
     }
   switch(_dim)
     {
     case 0:
       this->init_0D(_type,_p_level);
       return;
     case 1:
       this->init_1D(_type,_p_level);
       return;
     case 2:
       this->init_2D(_type,_p_level);
       return;
     case 3:
       this->init_3D(_type,_p_level);
       return;
     default:
       libmesh_error_msg("Invalid dimension _dim = " << _dim);
     }
 }
void libMesh::QBase::init (const Elem & elem, const std::vector< Real > & vertex_distance_func, unsigned int p_level = 0) virtual inherited
Initializes the data structures for an element potentially "cut" by a signed distance function. The array vertex_distance_func contains vertex values of the signed distance function. If the signed distance function changes sign on the vertices, then the element is considered to be cut.) This interface can be extended by derived classes in order to subdivide the element and construct a composite quadrature rule.
Definition at line 72 of file quadrature.C.
References libMesh::QBase::init(), and libMesh::Elem::type().
 {
   // dispatch generic implementation
   this->init(elem.type(), p_level);
 }
void libMesh::QBase::init_0D (const ElemType type = INVALID_ELEM, unsigned int p_level = 0) protected virtual inherited
Initializes the 0D quadrature rule by filling the points and weights vectors with the appropriate values. Generally this is just one point with weight 1.
Definition at line 82 of file quadrature.C.
References libMesh::QBase::_points, and libMesh::QBase::_weights.
Referenced by libMesh::QBase::init().
 {
   _points.resize(1);
   _weights.resize(1);
   _points[0] = Point(0.);
   _weights[0] = 1.0;
 }
void libMesh::QGaussLobatto::init_1D (const ElemType type = INVALID_ELEM, unsigned int p_level = 0) private virtual
Initializes the 1D quadrature rule by filling the points and weights vectors with the appropriate values. The order of the rule will be defined by the implementing class. It is assumed that derived quadrature rules will at least define the init_1D function, therefore it is pure virtual.
Implements libMesh::QBase.
Definition at line 28 of file quadrature_gauss_lobatto_1D.C.
References libMesh::QBase::_order, libMesh::QBase::_points, libMesh::QBase::_weights, libMesh::CONSTANT, libMesh::EIGHTH, libMesh::EIGHTTEENTH, libMesh::ELEVENTH, libMesh::FIFTEENTH, libMesh::FIFTH, libMesh::FIRST, libMesh::FORTIETH, libMesh::FORTYFIRST, libMesh::FORTYSECOND, libMesh::FORTYTHIRD, libMesh::FOURTEENTH, libMesh::FOURTH, libMesh::NINETEENTH, libMesh::NINTH, libMesh::Real, libMesh::SECOND, libMesh::SEVENTEENTH, libMesh::SEVENTH, libMesh::SIXTEENTH, libMesh::SIXTH, libMesh::TENTH, libMesh::THIRD, libMesh::THIRTEENTH, libMesh::THIRTIETH, libMesh::THIRTYEIGHTH, libMesh::THIRTYFIFTH, libMesh::THIRTYFIRST, libMesh::THIRTYFOURTH, libMesh::THIRTYNINTH, libMesh::THIRTYSECOND, libMesh::THIRTYSEVENTH, libMesh::THIRTYSIXTH, libMesh::THIRTYTHIRD, libMesh::TWELFTH, libMesh::TWENTIETH, libMesh::TWENTYEIGHTH, libMesh::TWENTYFIFTH, libMesh::TWENTYFIRST, libMesh::TWENTYFOURTH, libMesh::TWENTYNINTH, libMesh::TWENTYSECOND, libMesh::TWENTYSEVENTH, libMesh::TWENTYSIXTH, and libMesh::TWENTYTHIRD.
Referenced by type().
 {
   //----------------------------------------------------------------------
   // 1D quadrature rules
   switch(_order + 2*p)
     {
       // Since Gauss-Lobatto rules must include the endpoints of the
       // domain, there is no 1-point rule.  The two-point
       // Gauss-Lobatto rule is equivalent to the trapezoidal rule.
     case CONSTANT:
     case FIRST:
       {
         _points.resize (2);
         _weights.resize(2);
         _points[0](0) = -1.0L;
         _points[1]    = -_points[0];
         _weights[0]   = 1.;
         _weights[1]   = _weights[0];
         return;
       }
       // The three-point Gauss-Lobatto rule is equivalent to Simpsons' rule.
       // It can integrate cubic polynomials exactly.
     case SECOND:
     case THIRD:
       {
         _points.resize (3);
         _weights.resize(3);
         _points[0](0) = -1.0L;
         _points[1]    = 0.0L;
         _points[2]    = -_points[0];
         _weights[0]   = Real(1)/3;
         _weights[1]   = Real(4)/3;
         _weights[2]   = _weights[0];
         return;
       }
       // The four-point Gauss-Lobatto rule can integrate 2*4-3 =
       // 5th-order polynomials exactly.
     case FOURTH:
     case FIFTH:
       {
         _points.resize (4);
         _weights.resize(4);
         _points[ 0](0) = -1.0L;
         _points[ 1](0) = -std::sqrt(1.0L/5.0L);
         _points[ 2]    = -_points[1];
         _points[ 3]    = -_points[0];
         _weights[ 0]   = Real(1)/6;
         _weights[ 1]   = Real(5)/6;
         _weights[ 2]   = _weights[1];
         _weights[ 3]   = _weights[0];
         return;
       }
       // The five-point Gauss-Lobatto rule can integrate 2*5-3 =
       // 7th-order polynomials exactly.
     case SIXTH:
     case SEVENTH:
       {
         _points.resize (5);
         _weights.resize(5);
         _points[ 0](0) = -1.0L;
         _points[ 1](0) = -std::sqrt(3.0L/7.0L);
         _points[ 2](0) = 0.;
         _points[ 3]    = -_points[1];
         _points[ 4]    = -_points[0];
         _weights[ 0]   = 0.1;
         _weights[ 1]   = Real(49)/90;
         _weights[ 2]   = Real(32)/45;
         _weights[ 3]   = _weights[1];
         _weights[ 4]   = _weights[0];
         return;
       }
       // 2*6-3 = 9
     case EIGHTH:
     case NINTH:
       {
         _points.resize (6);
         _weights.resize(6);
         _points[ 0](0) = -1.0000000000000000000000000000000e+00L;
         _points[ 1](0) = -7.6505532392946469285100297395934e-01L;
         _points[ 2](0) = -2.8523151648064509631415099404088e-01L;
         _points[ 3]    = -_points[2];
         _points[ 4]    = -_points[1];
         _points[ 5]    = -_points[0];
         _weights[ 0]   = 6.6666666666666666666666666666667e-02L;
         _weights[ 1]   = 3.7847495629784698031661280821202e-01L;
         _weights[ 2]   = 5.5485837703548635301672052512131e-01L;
         _weights[ 3]   = _weights[2];
         _weights[ 4]   = _weights[1];
         _weights[ 5]   = _weights[0];
         return;
       }
       // 2*7-3 = 11
     case TENTH:
     case ELEVENTH:
       {
         _points.resize (7);
         _weights.resize(7);
         _points[ 0](0) = -1.0000000000000000000000000000000e+00L;
         _points[ 1](0) = -8.3022389627856692987203221396747e-01L;
         _points[ 2](0) = -4.6884879347071421380377188190877e-01L;
         _points[ 3](0) = 0.;
         _points[ 4]    = -_points[2];
         _points[ 5]    = -_points[1];
         _points[ 6]    = -_points[0];
         _weights[ 0]   = 4.7619047619047619047619047619048e-02L;
         _weights[ 1]   = 2.7682604736156594801070040629007e-01L;
         _weights[ 2]   = 4.3174538120986262341787102228136e-01L;
         _weights[ 3]   = 4.8761904761904761904761904761905e-01L;
         _weights[ 4]   = _weights[2];
         _weights[ 5]   = _weights[1];
         _weights[ 6]   = _weights[0];
         return;
       }
       // 2*8-3 = 13
     case TWELFTH:
     case THIRTEENTH:
       {
         _points.resize (8);
         _weights.resize(8);
         _points[ 0](0) = -1.0000000000000000000000000000000e+00L;
         _points[ 1](0) = -8.7174014850960661533744576122066e-01L;
         _points[ 2](0) = -5.9170018143314230214451073139795e-01L;
         _points[ 3](0) = -2.0929921790247886876865726034535e-01L;
         _points[ 4]    = -_points[3];
         _points[ 5]    = -_points[2];
         _points[ 6]    = -_points[1];
         _points[ 7]    = -_points[0];
         _weights[ 0]   = 3.5714285714285714285714285714286e-02L;
         _weights[ 1]   = 2.1070422714350603938299206577576e-01L;
         _weights[ 2]   = 3.4112269248350436476424067710775e-01L;
         _weights[ 3]   = 4.1245879465870388156705297140221e-01L;
         _weights[ 4]   = _weights[3];
         _weights[ 5]   = _weights[2];
         _weights[ 6]   = _weights[1];
         _weights[ 7]   = _weights[0];
         return;
       }
       // 2*9-3 = 15
     case FOURTEENTH:
     case FIFTEENTH:
       {
         _points.resize (9);
         _weights.resize(9);
         _points[ 0](0) = -1.0000000000000000000000000000000e+00L;
         _points[ 1](0) = -8.9975799541146015731234524441834e-01L;
         _points[ 2](0) = -6.7718627951073775344588542709134e-01L;
         _points[ 3](0) = -3.6311746382617815871075206870866e-01L;
         _points[ 4](0) = 0.;
         _points[ 5]    = -_points[3];
         _points[ 6]    = -_points[2];
         _points[ 7]    = -_points[1];
         _points[ 8]    = -_points[0];
         _weights[ 0]   = 2.7777777777777777777777777777778e-02L;
         _weights[ 1]   = 1.6549536156080552504633972002921e-01L;
         _weights[ 2]   = 2.7453871250016173528070561857937e-01L;
         _weights[ 3]   = 3.4642851097304634511513153213972e-01L;
         _weights[ 4]   = 3.7151927437641723356009070294785e-01L;
         _weights[ 5]   = _weights[3];
         _weights[ 6]   = _weights[2];
         _weights[ 7]   = _weights[1];
         _weights[ 8]   = _weights[0];
         return;
       }
       // 2*10-3 = 17
     case SIXTEENTH:
     case SEVENTEENTH:
       {
         _points.resize (10);
         _weights.resize(10);
         _points[ 0](0) = -1.0000000000000000000000000000000e+00L;
         _points[ 1](0) = -9.1953390816645881382893266082234e-01L;
         _points[ 2](0) = -7.3877386510550507500310617485983e-01L;
         _points[ 3](0) = -4.7792494981044449566117509273126e-01L;
         _points[ 4](0) = -1.6527895766638702462621976595817e-01L;
         _points[ 5]    = -_points[4];
         _points[ 6]    = -_points[3];
         _points[ 7]    = -_points[2];
         _points[ 8]    = -_points[1];
         _points[ 9]    = -_points[0];
         _weights[ 0]   = 2.2222222222222222222222222222222e-02L;
         _weights[ 1]   = 1.3330599085107011112622717075539e-01L;
         _weights[ 2]   = 2.2488934206312645211945782173105e-01L;
         _weights[ 3]   = 2.9204268367968375787558225737444e-01L;
         _weights[ 4]   = 3.2753976118389745665651052791689e-01L;
         _weights[ 5]   = _weights[4];
         _weights[ 6]   = _weights[3];
         _weights[ 7]   = _weights[2];
         _weights[ 8]   = _weights[1];
         _weights[ 9]   = _weights[0];
         return;
       }
       // 2*11-3 = 19
     case EIGHTTEENTH:
     case NINETEENTH:
       {
         _points.resize (11);
         _weights.resize(11);
         _points[ 0](0) = -1.0000000000000000000000000000000e+00L;
         _points[ 1](0) = -9.3400143040805913433227413609938e-01L;
         _points[ 2](0) = -7.8448347366314441862241781610846e-01L;
         _points[ 3](0) = -5.6523532699620500647096396947775e-01L;
         _points[ 4](0) = -2.9575813558693939143191151555906e-01L;
         _points[ 5](0) = 0.;
         _points[ 6]    = -_points[4];
         _points[ 7]    = -_points[3];
         _points[ 8]    = -_points[2];
         _points[ 9]    = -_points[1];
         _points[10]    = -_points[0];
         _weights[ 0]   = 1.8181818181818181818181818181818e-02L;
         _weights[ 1]   = 1.0961227326699486446140344958035e-01L;
         _weights[ 2]   = 1.8716988178030520410814152189943e-01L;
         _weights[ 3]   = 2.4804810426402831404008486642187e-01L;
         _weights[ 4]   = 2.8687912477900808867922240333154e-01L;
         _weights[ 5]   = 3.0021759545569069378593188116998e-01L;
         _weights[ 6]   = _weights[4];
         _weights[ 7]   = _weights[3];
         _weights[ 8]   = _weights[2];
         _weights[ 9]   = _weights[1];
         _weights[10]   = _weights[0];
         return;
       }
       // 2*12-3 = 21
     case TWENTIETH:
     case TWENTYFIRST:
       {
         _points.resize (12);
         _weights.resize(12);
         _points[ 0](0) = -1.0000000000000000000000000000000e+00L;
         _points[ 1](0) = -9.4489927222288222340758013830322e-01L;
         _points[ 2](0) = -8.1927932164400667834864158171690e-01L;
         _points[ 3](0) = -6.3287615303186067766240485444366e-01L;
         _points[ 4](0) = -3.9953094096534893226434979156697e-01L;
         _points[ 5](0) = -1.3655293285492755486406185573969e-01L;
         _points[ 6]    = -_points[5];
         _points[ 7]    = -_points[4];
         _points[ 8]    = -_points[3];
         _points[ 9]    = -_points[2];
         _points[10]    = -_points[1];
         _points[11]    = -_points[0];
         _weights[ 0]   = 1.5151515151515151515151515151515e-02L;
         _weights[ 1]   = 9.1684517413196130668342594134079e-02L;
         _weights[ 2]   = 1.5797470556437011516467106270034e-01L;
         _weights[ 3]   = 2.1250841776102114535830207736687e-01L;
         _weights[ 4]   = 2.5127560319920128029324441214760e-01L;
         _weights[ 5]   = 2.7140524091069617700028833849960e-01L;
         _weights[ 6]   = _weights[5];
         _weights[ 7]   = _weights[4];
         _weights[ 8]   = _weights[3];
         _weights[ 9]   = _weights[2];
         _weights[10]   = _weights[1];
         _weights[11]   = _weights[0];
         return;
       }
       // 2*13-3 = 23
     case TWENTYSECOND:
     case TWENTYTHIRD:
       {
         _points.resize (13);
         _weights.resize(13);
         _points[ 0](0) = -1.0000000000000000000000000000000e+00L;
         _points[ 1](0) = -9.5330984664216391189690546475545e-01L;
         _points[ 2](0) = -8.4634756465187231686592560709875e-01L;
         _points[ 3](0) = -6.8618846908175742607275903956636e-01L;
         _points[ 4](0) = -4.8290982109133620174693723363693e-01L;
         _points[ 5](0) = -2.4928693010623999256867370037423e-01L;
         _points[ 6](0) = 0.;
         _points[ 7]    = -_points[5];
         _points[ 8]    = -_points[4];
         _points[ 9]    = -_points[3];
         _points[10]    = -_points[2];
         _points[11]    = -_points[1];
         _points[12]    = -_points[0];
         _weights[ 0]   = 1.2820512820512820512820512820513e-02L;
         _weights[ 1]   = 7.7801686746818927793588988333134e-02L;
         _weights[ 2]   = 1.3498192668960834911991476258937e-01L;
         _weights[ 3]   = 1.8364686520355009200749425874681e-01L;
         _weights[ 4]   = 2.2076779356611008608553400837940e-01L;
         _weights[ 5]   = 2.4401579030667635645857814836016e-01L;
         _weights[ 6]   = 2.5193084933344673604413864154124e-01L;
         _weights[ 7]   = _weights[5];
         _weights[ 8]   = _weights[4];
         _weights[ 9]   = _weights[3];
         _weights[10]   = _weights[2];
         _weights[11]   = _weights[1];
         _weights[12]   = _weights[0];
         return;
       }
       // 2*14-3 = 25
     case TWENTYFOURTH:
     case TWENTYFIFTH:
       {
         _points.resize (14);
         _weights.resize(14);
         _points[ 0](0) = -1.0000000000000000000000000000000e+00L;
         _points[ 1](0) = -9.5993504526726090135510016201542e-01L;
         _points[ 2](0) = -8.6780105383034725100022020290826e-01L;
         _points[ 3](0) = -7.2886859909132614058467240052088e-01L;
         _points[ 4](0) = -5.5063940292864705531662270585908e-01L;
         _points[ 5](0) = -3.4272401334271284504390340364167e-01L;
         _points[ 6](0) = -1.1633186888370386765877670973616e-01L;
         _points[ 7]    = -_points[6];
         _points[ 8]    = -_points[5];
         _points[ 9]    = -_points[4];
         _points[10]    = -_points[3];
         _points[11]    = -_points[2];
         _points[12]    = -_points[1];
         _points[13]    = -_points[0];
         _weights[ 0]   = 1.0989010989010989010989010989011e-02L;
         _weights[ 1]   = 6.6837284497681284634070660746053e-02L;
         _weights[ 2]   = 1.1658665589871165154099667065465e-01L;
         _weights[ 3]   = 1.6002185176295214241282099798759e-01L;
         _weights[ 4]   = 1.9482614937341611864033177837588e-01L;
         _weights[ 5]   = 2.1912625300977075487116252395417e-01L;
         _weights[ 6]   = 2.3161279446845705888962835729264e-01L;
         _weights[ 7]   = _weights[6];
         _weights[ 8]   = _weights[5];
         _weights[ 9]   = _weights[4];
         _weights[10]   = _weights[3];
         _weights[11]   = _weights[2];
         _weights[12]   = _weights[1];
         _weights[13]   = _weights[0];
         return;
       }
       // 2*15-3 = 27
     case TWENTYSIXTH:
     case TWENTYSEVENTH:
       {
         _points.resize (15);
         _weights.resize(15);
         _points[ 0](0) = -1.0000000000000000000000000000000e+00L;
         _points[ 1](0) = -9.6524592650383857279585139206960e-01L;
         _points[ 2](0) = -8.8508204422297629882540163148223e-01L;
         _points[ 3](0) = -7.6351968995181520070411847597629e-01L;
         _points[ 4](0) = -6.0625320546984571112352993863673e-01L;
         _points[ 5](0) = -4.2063805471367248092189693873858e-01L;
         _points[ 6](0) = -2.1535395536379423822567944627292e-01L;
         _points[ 7](0) = 0.;
         _points[ 8]    = -_points[6];
         _points[ 9]    = -_points[5];
         _points[10]    = -_points[4];
         _points[11]    = -_points[3];
         _points[12]    = -_points[2];
         _points[13]    = -_points[1];
         _points[14]    = -_points[0];
         _weights[ 0]   = 9.5238095238095238095238095238095e-03L;
         _weights[ 1]   = 5.8029893028601249096880584025282e-02L;
         _weights[ 2]   = 1.0166007032571806760366617078880e-01L;
         _weights[ 3]   = 1.4051169980242810946044680564367e-01L;
         _weights[ 4]   = 1.7278964725360094905207709940835e-01L;
         _weights[ 5]   = 1.9698723596461335609250034650741e-01L;
         _weights[ 6]   = 2.1197358592682092012743007697722e-01L;
         _weights[ 7]   = 2.1704811634881564951495021425091e-01L;
         _weights[ 8]   = _weights[6];
         _weights[ 9]   = _weights[5];
         _weights[10]   = _weights[4];
         _weights[11]   = _weights[3];
         _weights[12]   = _weights[2];
         _weights[13]   = _weights[1];
         _weights[14]   = _weights[0];
         return;
       }
       // 2*16-3 = 29
     case TWENTYEIGHTH:
     case TWENTYNINTH:
       {
         _points.resize (16);
         _weights.resize(16);
         _points[ 0](0) = -1.0000000000000000000000000000000e+00L;
         _points[ 1](0) = -9.6956804627021793295224273836746e-01L;
         _points[ 2](0) = -8.9920053309347209299462826151985e-01L;
         _points[ 3](0) = -7.9200829186181506393108827096315e-01L;
         _points[ 4](0) = -6.5238870288249308946788321964058e-01L;
         _points[ 5](0) = -4.8605942188713761178189078584687e-01L;
         _points[ 6](0) = -2.9983046890076320809835345472230e-01L;
         _points[ 7](0) = -1.0132627352194944784303300504592e-01L;
         _points[ 8]    = -_points[7];
         _points[ 9]    = -_points[6];
         _points[10]    = -_points[5];
         _points[11]    = -_points[4];
         _points[12]    = -_points[3];
         _points[13]    = -_points[2];
         _points[14]    = -_points[1];
         _points[15]    = -_points[0];
         _weights[ 0]   = 8.3333333333333333333333333333333e-03L;
         _weights[ 1]   = 5.0850361005919905403244919565455e-02L;
         _weights[ 2]   = 8.9393697325930800991052080166084e-02L;
         _weights[ 3]   = 1.2425538213251409834953633265731e-01L;
         _weights[ 4]   = 1.5402698080716428081564494048499e-01L;
         _weights[ 5]   = 1.7749191339170412530107566952836e-01L;
         _weights[ 6]   = 1.9369002382520358431691359885352e-01L;
         _weights[ 7]   = 2.0195830817822987148919912541094e-01L;
         _weights[ 8]   = _weights[7];
         _weights[ 9]   = _weights[6];
         _weights[10]   = _weights[5];
         _weights[11]   = _weights[4];
         _weights[12]   = _weights[3];
         _weights[13]   = _weights[2];
         _weights[14]   = _weights[1];
         _weights[15]   = _weights[0];
         return;
       }
       // 2*17-3 = 31
     case THIRTIETH:
     case THIRTYFIRST:
       {
         _points.resize (17);
         _weights.resize(17);
         _points[ 0](0) = -1.0000000000000000000000000000000e+00L;
         _points[ 1](0) = -9.7313217663141831415697950187372e-01L;
         _points[ 2](0) = -9.1087999591557359562380250639773e-01L;
         _points[ 3](0) = -8.1569625122177030710675055323753e-01L;
         _points[ 4](0) = -6.9102898062768470539491935737245e-01L;
         _points[ 5](0) = -5.4138539933010153912373340750406e-01L;
         _points[ 6](0) = -3.7217443356547704190723468073526e-01L;
         _points[ 7](0) = -1.8951197351831738830426301475311e-01L;
         _points[ 8](0) = 0.;
         _points[ 9]    = -_points[7];
         _points[10]    = -_points[6];
         _points[11]    = -_points[5];
         _points[12]    = -_points[4];
         _points[13]    = -_points[3];
         _points[14]    = -_points[2];
         _points[15]    = -_points[1];
         _points[16]    = -_points[0];
         _weights[ 0]   = 7.3529411764705882352941176470588e-03L;
         _weights[ 1]   = 4.4921940543254209647400954623212e-02L;
         _weights[ 2]   = 7.9198270503687119190264429952835e-02L;
         _weights[ 3]   = 1.1059290900702816137577270522008e-01L;
         _weights[ 4]   = 1.3798774620192655905620157495403e-01L;
         _weights[ 5]   = 1.6039466199762153951632836586475e-01L;
         _weights[ 6]   = 1.7700425351565787043694574536329e-01L;
         _weights[ 7]   = 1.8721633967761923589208848286062e-01L;
         _weights[ 8]   = 1.9066187475346943329940724702825e-01L;
         _weights[ 9]   = _weights[7];
         _weights[10]   = _weights[6];
         _weights[11]   = _weights[5];
         _weights[12]   = _weights[4];
         _weights[13]   = _weights[3];
         _weights[14]   = _weights[2];
         _weights[15]   = _weights[1];
         _weights[16]   = _weights[0];
         return;
       }
       // 2*18-3 = 33
     case THIRTYSECOND:
     case THIRTYTHIRD:
       {
         _points.resize (18);
         _weights.resize(18);
         _points[ 0](0) = -1.0000000000000000000000000000000e+00L;
         _points[ 1](0) = -9.7610555741219854286451892434170e-01L;
         _points[ 2](0) = -9.2064918534753387383785462543128e-01L;
         _points[ 3](0) = -8.3559353521809021371364636232794e-01L;
         _points[ 4](0) = -7.2367932928324268130621036530207e-01L;
         _points[ 5](0) = -5.8850483431866176117353589319356e-01L;
         _points[ 6](0) = -4.3441503691212397534228713674067e-01L;
         _points[ 7](0) = -2.6636265287828098416766533202560e-01L;
         _points[ 8](0) = -8.9749093484652111022645010088562e-02L;
         _points[ 9]    = -_points[8];
         _points[10]    = -_points[7];
         _points[11]    = -_points[6];
         _points[12]    = -_points[5];
         _points[13]    = -_points[4];
         _points[14]    = -_points[3];
         _points[15]    = -_points[2];
         _points[16]    = -_points[1];
         _points[17]    = -_points[0];
         _weights[ 0]   = 6.5359477124183006535947712418301e-03L;
         _weights[ 1]   = 3.9970628810914066137599176410101e-02L;
         _weights[ 2]   = 7.0637166885633664999222960167786e-02L;
         _weights[ 3]   = 9.9016271717502802394423605318672e-02L;
         _weights[ 4]   = 1.2421053313296710026339635889675e-01L;
         _weights[ 5]   = 1.4541196157380226798300321049443e-01L;
         _weights[ 6]   = 1.6193951723760248926432670670023e-01L;
         _weights[ 7]   = 1.7326210948945622601061440382668e-01L;
         _weights[ 8]   = 1.7901586343970308229381880694353e-01L;
         _weights[ 9]   = _weights[8];
         _weights[10]   = _weights[7];
         _weights[11]   = _weights[6];
         _weights[12]   = _weights[5];
         _weights[13]   = _weights[4];
         _weights[14]   = _weights[3];
         _weights[15]   = _weights[2];
         _weights[16]   = _weights[1];
         _weights[17]   = _weights[0];
         return;
       }
       // 2*19-3 = 35
     case THIRTYFOURTH:
     case THIRTYFIFTH:
       {
         _points.resize (19);
         _weights.resize(19);
         _points[ 0](0) = -1.0000000000000000000000000000000e+00L;
         _points[ 1](0) = -9.7861176622208009515263406311022e-01L;
         _points[ 2](0) = -9.2890152815258624371794025879655e-01L;
         _points[ 3](0) = -8.5246057779664609308595597004106e-01L;
         _points[ 4](0) = -7.5149420255261301416363748963394e-01L;
         _points[ 5](0) = -6.2890813726522049776683230622873e-01L;
         _points[ 6](0) = -4.8822928568071350277790963762492e-01L;
         _points[ 7](0) = -3.3350484782449861029850010384493e-01L;
         _points[ 8](0) = -1.6918602340928157137515415344488e-01L;
         _points[ 9](0) = 0.;
         _points[10]    = -_points[8];
         _points[11]    = -_points[7];
         _points[12]    = -_points[6];
         _points[13]    = -_points[5];
         _points[14]    = -_points[4];
         _points[15]    = -_points[3];
         _points[16]    = -_points[2];
         _points[17]    = -_points[1];
         _points[18]    = -_points[0];
         _weights[ 0]   = 5.8479532163742690058479532163743e-03L;
         _weights[ 1]   = 3.5793365186176477115425569035122e-02L;
         _weights[ 2]   = 6.3381891762629736851695690418317e-02L;
         _weights[ 3]   = 8.9131757099207084448008790556153e-02L;
         _weights[ 4]   = 1.1231534147730504407091001546378e-01L;
         _weights[ 5]   = 1.3226728044875077692604673390973e-01L;
         _weights[ 6]   = 1.4841394259593888500968064366841e-01L;
         _weights[ 7]   = 1.6029092404406124197991096818359e-01L;
         _weights[ 8]   = 1.6755658452714286727013727774026e-01L;
         _weights[ 9]   = 1.7000191928482723464467271561652e-01L;
         _weights[10]   = _weights[8];
         _weights[11]   = _weights[7];
         _weights[12]   = _weights[6];
         _weights[13]   = _weights[5];
         _weights[14]   = _weights[4];
         _weights[15]   = _weights[3];
         _weights[16]   = _weights[2];
         _weights[17]   = _weights[1];
         _weights[18]   = _weights[0];
         return;
       }
       // 2*20-3 = 37
     case THIRTYSIXTH:
     case THIRTYSEVENTH:
       {
         _points.resize (20);
         _weights.resize(20);
         _points[ 0](0) = -1.0000000000000000000000000000000e+00L;
         _points[ 1](0) = -9.8074370489391417192544643858423e-01L;
         _points[ 2](0) = -9.3593449881266543571618158493063e-01L;
         _points[ 3](0) = -8.6687797808995014130984721461629e-01L;
         _points[ 4](0) = -7.7536826095205587041431752759469e-01L;
         _points[ 5](0) = -6.6377640229031128984640332297116e-01L;
         _points[ 6](0) = -5.3499286403188626164813596182898e-01L;
         _points[ 7](0) = -3.9235318371390929938647470381582e-01L;
         _points[ 8](0) = -2.3955170592298649518240135692709e-01L;
         _points[ 9](0) = -8.0545937238821837975944518159554e-02L;
         _points[10]    = -_points[9];
         _points[11]    = -_points[8];
         _points[12]    = -_points[7];
         _points[13]    = -_points[6];
         _points[14]    = -_points[5];
         _points[15]    = -_points[4];
         _points[16]    = -_points[3];
         _points[17]    = -_points[2];
         _points[18]    = -_points[1];
         _points[19]    = -_points[0];
         _weights[ 0]   = 5.2631578947368421052631578947368e-03L;
         _weights[ 1]   = 3.2237123188488941491605028117294e-02L;
         _weights[ 2]   = 5.7181802127566826004753627173243e-02L;
         _weights[ 3]   = 8.0631763996119603144776846113721e-02L;
         _weights[ 4]   = 1.0199149969945081568378120573289e-01L;
         _weights[ 5]   = 1.2070922762867472509942970500239e-01L;
         _weights[ 6]   = 1.3630048235872418448978079298903e-01L;
         _weights[ 7]   = 1.4836155407091682581471301373397e-01L;
         _weights[ 8]   = 1.5658010264747548715816989679364e-01L;
         _weights[ 9]   = 1.6074328638784574900772672644908e-01L;
         _weights[10]   = _weights[9];
         _weights[11]   = _weights[8];
         _weights[12]   = _weights[7];
         _weights[13]   = _weights[6];
         _weights[14]   = _weights[5];
         _weights[15]   = _weights[4];
         _weights[16]   = _weights[3];
         _weights[17]   = _weights[2];
         _weights[18]   = _weights[1];
         _weights[19]   = _weights[0];
         return;
       }
       // 2*21-3 = 39
     case THIRTYEIGHTH:
     case THIRTYNINTH:
       {
         _points.resize (21);
         _weights.resize(21);
         _points[ 0](0) = -1.0000000000000000000000000000000e+00L;
         _points[ 1](0) = -9.8257229660454802823448127655541e-01L;
         _points[ 2](0) = -9.4197629695974553429610265066144e-01L;
         _points[ 3](0) = -8.7929475532359046445115359630494e-01L;
         _points[ 4](0) = -7.9600192607771240474431258966036e-01L;
         _points[ 5](0) = -6.9405102606222323262731639319467e-01L;
         _points[ 6](0) = -5.7583196026183068692702187033809e-01L;
         _points[ 7](0) = -4.4411578327900210119451634960735e-01L;
         _points[ 8](0) = -3.0198985650876488727535186785875e-01L;
         _points[ 9](0) = -1.5278551580218546600635832848567e-01L;
         _points[10](0) = 0.;
         _points[11]    = -_points[9];
         _points[12]    = -_points[8];
         _points[13]    = -_points[7];
         _points[14]    = -_points[6];
         _points[15]    = -_points[5];
         _points[16]    = -_points[4];
         _points[17]    = -_points[3];
         _points[18]    = -_points[2];
         _points[19]    = -_points[1];
         _points[20]    = -_points[0];
         _weights[ 0]   = 4.7619047619047619047619047619048e-03L;
         _weights[ 1]   = 2.9184840098505458609458543613171e-02L;
         _weights[ 2]   = 5.1843169000849625072722971852830e-02L;
         _weights[ 3]   = 7.3273918185074144252547861041894e-02L;
         _weights[ 4]   = 9.2985467957886065301137664149214e-02L;
         _weights[ 5]   = 1.1051708321912333526700048678439e-01L;
         _weights[ 6]   = 1.2545812119086894801515753570800e-01L;
         _weights[ 7]   = 1.3745846286004134358089961741515e-01L;
         _weights[ 8]   = 1.4623686244797745926727053063439e-01L;
         _weights[ 9]   = 1.5158757511168138445325068150529e-01L;
         _weights[10]   = 1.5338519033217494855158440506754e-01L;
         _weights[11]   = _weights[9];
         _weights[12]   = _weights[8];
         _weights[13]   = _weights[7];
         _weights[14]   = _weights[6];
         _weights[15]   = _weights[5];
         _weights[16]   = _weights[4];
         _weights[17]   = _weights[3];
         _weights[18]   = _weights[2];
         _weights[19]   = _weights[1];
         _weights[20]   = _weights[0];
         return;
       }
       // 2*22-3 = 41
     case FORTIETH:
     case FORTYFIRST:
       {
         _points.resize (22);
         _weights.resize(22);
         _points[ 0](0) = -1.0000000000000000000000000000000e+00L;
         _points[ 1](0) = -9.8415243845764617655228962221207e-01L;
         _points[ 2](0) = -9.4720428399922868052421376661573e-01L;
         _points[ 3](0) = -8.9006229019090447052965782577909e-01L;
         _points[ 4](0) = -8.1394892761192113604544184805614e-01L;
         _points[ 5](0) = -7.2048723996120215811988189639847e-01L;
         _points[ 6](0) = -6.1166943828425897122621160586993e-01L;
         _points[ 7](0) = -4.8981487518990234980875123568327e-01L;
         _points[ 8](0) = -3.5752071013891953806095728024018e-01L;
         _points[ 9](0) = -2.1760658515928504178795509346539e-01L;
         _points[10](0) = -7.3054540010898334761088790464107e-02L;
         _points[11]    = -_points[10];
         _points[12]    = -_points[9];
         _points[13]    = -_points[8];
         _points[14]    = -_points[7];
         _points[15]    = -_points[6];
         _points[16]    = -_points[5];
         _points[17]    = -_points[4];
         _points[18]    = -_points[3];
         _points[19]    = -_points[2];
         _points[20]    = -_points[1];
         _points[21]    = -_points[0];
         _weights[ 0]   = 4.3290043290043290043290043290043e-03L;
         _weights[ 1]   = 2.6545747682501757911627904520543e-02L;
         _weights[ 2]   = 4.7214465293740752123775734864792e-02L;
         _weights[ 3]   = 6.6865605864553076012404194157097e-02L;
         _weights[ 4]   = 8.5090060391838447815711236095748e-02L;
         _weights[ 5]   = 1.0150057480164767437243730374960e-01L;
         _weights[ 6]   = 1.1574764465393906659003636772146e-01L;
         _weights[ 7]   = 1.2752769665343027553084445930883e-01L;
         _weights[ 8]   = 1.3658968861374142668617736220617e-01L;
         _weights[ 9]   = 1.4274049227136140033623599356679e-01L;
         _weights[10]   = 1.4584901944424179361642043947997e-01L;
         _weights[11]   = _weights[10];
         _weights[12]   = _weights[9];
         _weights[13]   = _weights[8];
         _weights[14]   = _weights[7];
         _weights[15]   = _weights[6];
         _weights[16]   = _weights[5];
         _weights[17]   = _weights[4];
         _weights[18]   = _weights[3];
         _weights[19]   = _weights[2];
         _weights[20]   = _weights[1];
         _weights[21]   = _weights[0];
         return;
       }
       // 2*23-3 = 43
     case FORTYSECOND:
     case FORTYTHIRD:
       {
         _points.resize (23);
         _weights.resize(23);
         _points[ 0](0) = -1.0000000000000000000000000000000e+00L;
         _points[ 1](0) = -9.8552715587873257808146276673810e-01L;
         _points[ 2](0) = -9.5175795571071020413563967985143e-01L;
         _points[ 3](0) = -8.9945855804034501095016032034737e-01L;
         _points[ 4](0) = -8.2965109665128588622320061929000e-01L;
         _points[ 5](0) = -7.4369504117206068394516354306700e-01L;
         _points[ 6](0) = -6.4326364446013620847614553360277e-01L;
         _points[ 7](0) = -5.3031177113684416813011532015230e-01L;
         _points[ 8](0) = -4.0703793791447482919595048821510e-01L;
         _points[ 9](0) = -2.7584154894579306710687763267914e-01L;
         _points[10](0) = -1.3927620404066839859186261298277e-01L;
         _points[11](0) = 0.;
         _points[12]    = -_points[10];
         _points[13]    = -_points[9];
         _points[14]    = -_points[8];
         _points[15]    = -_points[7];
         _points[16]    = -_points[6];
         _points[17]    = -_points[5];
         _points[18]    = -_points[4];
         _points[19]    = -_points[3];
         _points[20]    = -_points[2];
         _points[21]    = -_points[1];
         _points[22]    = -_points[0];
         _weights[ 0]   = 3.9525691699604743083003952569170e-03L;
         _weights[ 1]   = 2.4248600771531736517399658937097e-02L;
         _weights[ 2]   = 4.3175871170241834748876465612042e-02L;
         _weights[ 3]   = 6.1252477129554206381382847440355e-02L;
         _weights[ 4]   = 7.8135449475569989741934255347965e-02L;
         _weights[ 5]   = 9.3497246163512341833500706906697e-02L;
         _weights[ 6]   = 1.0703910172433651153518362791547e-01L;
         _weights[ 7]   = 1.1849751066274913130212600472426e-01L;
         _weights[ 8]   = 1.2764947470175887663614855305567e-01L;
         _weights[ 9]   = 1.3431687263860381990156489770071e-01L;
         _weights[10]   = 1.3836993638580739452350273386294e-01L;
         _weights[11]   = 1.3972978001274736514015970647975e-01L;
         _weights[12]   = _weights[10];
         _weights[13]   = _weights[9];
         _weights[14]   = _weights[8];
         _weights[15]   = _weights[7];
         _weights[16]   = _weights[6];
         _weights[17]   = _weights[5];
         _weights[18]   = _weights[4];
         _weights[19]   = _weights[3];
         _weights[20]   = _weights[2];
         _weights[21]   = _weights[1];
         _weights[22]   = _weights[0];
         return;
       }
     default:
       libmesh_error_msg("Quadrature rule " << _order << " not supported!");
     }
 }
void libMesh::QGaussLobatto::init_2D (const ElemType = INVALID_ELEM, unsigned int = 0) private virtual
Initializes the 2D quadrature rule by filling the points and weights vectors with the appropriate values. The order of the rule will be defined by the implementing class. Should not be pure virtual since a derived quadrature rule may only be defined in 1D. If not redefined, gives an error (when DEBUG is defined) when called.
Reimplemented from libMesh::QBase.
Definition at line 26 of file quadrature_gauss_lobatto_2D.C.
References libMesh::QBase::_order, libMesh::EDGE2, libMesh::QBase::init(), libMesh::QUAD4, libMesh::QUAD8, libMesh::QUAD9, libMesh::QUADSHELL4, and libMesh::QBase::tensor_product_quad().
Referenced by type().
 {
   switch (type_in)
     {
     case QUAD4:
     case QUADSHELL4:
     case QUAD8:
     case QUAD9:
       {
         // We compute the 2D quadrature rule as a tensor
         // product of the 1D quadrature rule.
         QGaussLobatto q1D(1, _order);
         q1D.init(EDGE2, p);
         tensor_product_quad(q1D);
         return;
       }
       // We *could* fall back to a Gauss type rule for other types
       // elements, but the assumption here is that the user has asked
       // for a Gauss-Lobatto rule, i.e. a rule with integration points
       // on the element boundary, for a reason.
     default:
       libmesh_error_msg("Element type not supported!:" << type_in);
     }
 }
void libMesh::QGaussLobatto::init_3D (const ElemType = INVALID_ELEM, unsigned int = 0) private virtual
Initializes the 3D quadrature rule by filling the points and weights vectors with the appropriate values. The order of the rule will be defined by the implementing class. Should not be pure virtual since a derived quadrature rule may only be defined in 1D. If not redefined, gives an error (when DEBUG is defined) when called.
Reimplemented from libMesh::QBase.
Definition at line 26 of file quadrature_gauss_lobatto_3D.C.
References libMesh::QBase::_order, libMesh::EDGE2, libMesh::HEX20, libMesh::HEX27, libMesh::HEX8, libMesh::QBase::init(), and libMesh::QBase::tensor_product_hex().
Referenced by type().
 {
   switch (type_in)
     {
     case HEX8:
     case HEX20:
     case HEX27:
       {
         // We compute the 3D quadrature rule as a tensor
         // product of the 1D quadrature rule.
         QGaussLobatto q1D(1, _order);
         q1D.init(EDGE2, p);
         tensor_product_hex(q1D);
         return;
       }
       // We *could* fall back to a Gauss type rule for other types
       // elements, but the assumption here is that the user has asked
       // for a Gauss-Lobatto rule, i.e. a rule with integration points
       // on the element boundary, for a reason.
     default:
       libmesh_error_msg("ERROR: Unsupported type: " << type_in);
     }
 }
static unsigned int libMesh::ReferenceCounter::n_objects () inline static inherited
Prints the number of outstanding (created, but not yet destroyed) objects.
Definition at line 85 of file reference_counter.h.
References libMesh::ReferenceCounter::_n_objects, libMesh::ReferenceCounter::disable_print_counter_info(), libMesh::ReferenceCounter::enable_print_counter_info(), libMesh::ReferenceCounter::increment_constructor_count(), libMesh::ReferenceCounter::increment_destructor_count(), and libMesh::Quality::name().
Referenced by libMesh::System::hide_output(), and libMesh::LibMeshInit::LibMeshInit().
   { return _n_objects; }
unsigned int libMesh::QBase::n_points () const inline inherited
Returns
The number of points associated with the quadrature rule.
Definition at line 113 of file quadrature.h.
References libMesh::QBase::_points, and libMesh::libmesh_assert().
Referenced by libMesh::ExactSolution::_compute_error(), libMesh::System::calculate_norm(), libMesh::FirstOrderUnsteadySolver::compute_second_order_eqns(), libMesh::QConical::conical_product_pyramid(), libMesh::QConical::conical_product_tet(), libMesh::QConical::conical_product_tri(), libMesh::QBase::print_info(), libMesh::QBase::tensor_product_hex(), libMesh::QBase::tensor_product_prism(), and libMesh::QBase::tensor_product_quad().
   {
     libmesh_assert (!_points.empty());
     return cast_int<unsigned int>(_points.size());
   }
void libMesh::ReferenceCounter::print_info (std::ostream & out = libMesh::out) static inherited
Prints the reference information, by default to libMesh::out.
Definition at line 88 of file reference_counter.C.
References libMesh::ReferenceCounter::_enable_print_counter, and libMesh::ReferenceCounter::get_info().
Referenced by libMesh::LibMeshInit::LibMeshInit().
 {
   if (_enable_print_counter)
     out_stream << ReferenceCounter::get_info();
 }
void libMesh::QBase::print_info (std::ostream & os = libMesh::out) const inline inherited
Prints information relevant to the quadrature rule, by default to libMesh::out.
Definition at line 364 of file quadrature.h.
References libMesh::QBase::_points, libMesh::QBase::_weights, libMesh::libmesh_assert(), libMesh::QBase::n_points(), and libMesh::Real.
Referenced by libMesh::QBase::get_order(), and libMesh::operator<<().
 {
   libmesh_assert(!_points.empty());
   libmesh_assert(!_weights.empty());
   Real summed_weights=0;
   os << "N_Q_Points=" << this->n_points() << std::endl << std::endl;
   for (unsigned int qpoint=0; qpoint<this->n_points(); qpoint++)
     {
       os << " Point " << qpoint << ":\n"
          << "  "
          << _points[qpoint]
          << "\n Weight:\n "
          << "  w=" << _weights[qpoint] << "\n" << std::endl;
       summed_weights += _weights[qpoint];
     }
   os << "Summed Weights: " << summed_weights << std::endl;
 }
Point libMesh::QBase::qp (const unsigned int i) const inline inherited
Returns
The quadrature point in reference element space.
Definition at line 151 of file quadrature.h.
References libMesh::QBase::_points.
Referenced by libMesh::QConical::conical_product_pyramid(), libMesh::QConical::conical_product_tet(), libMesh::QConical::conical_product_tri(), libMesh::QBase::tensor_product_hex(), libMesh::QBase::tensor_product_prism(), and libMesh::QBase::tensor_product_quad().
   {
     libmesh_assert_less (i, _points.size());
     return _points[i];
   }
void libMesh::QBase::scale (std::pair< Real, Real > old_range, std::pair< Real, Real > new_range) inherited
Maps the points of a 1D quadrature rule defined by "old_range" to another 1D interval defined by "new_range" and scales the weights accordingly.
Definition at line 93 of file quadrature.C.
References libMesh::QBase::_dim, libMesh::QBase::_points, libMesh::QBase::_weights, and libMesh::Real.
Referenced by libMesh::QConical::conical_product_tet(), libMesh::QConical::conical_product_tri(), and libMesh::QBase::get_order().
 {
   // Make sure we are in 1D
   libmesh_assert_equal_to (_dim, 1);
   Real
     h_new = new_range.second - new_range.first,
     h_old = old_range.second - old_range.first;
   // Make sure that we have sane ranges
   libmesh_assert_greater (h_new, 0.);
   libmesh_assert_greater (h_old, 0.);
   // Make sure there are some points
   libmesh_assert_greater (_points.size(), 0);
   // Compute the scale factor
   Real scfact = h_new/h_old;
   // We're mapping from old_range -> new_range
   for (std::size_t i=0; i<_points.size(); i++)
     {
       _points[i](0) = new_range.first +
         (_points[i](0) - old_range.first) * scfact;
       // Scale the weights
       _weights[i] *= scfact;
     }
 }
virtual bool libMesh::QBase::shapes_need_reinit () inline virtual inherited
Returns
true if the shape functions need to be recalculated, false otherwise.
This may be required if the number of quadrature points or their position changes.
Definition at line 217 of file quadrature.h.
 { return false; }
void libMesh::QBase::tensor_product_hex (const QBase & q1D) protected inherited
Computes the tensor product quadrature rule [q1D x q1D x q1D] from the 1D rule q1D. Used in the init_3D routines for hexahedral element types.
Definition at line 154 of file quadrature.C.
References libMesh::QBase::_points, libMesh::QBase::_weights, libMesh::QBase::n_points(), libMesh::QBase::qp(), and libMesh::QBase::w().
Referenced by init_3D(), libMesh::QGrid::init_3D(), libMesh::QTrap::init_3D(), libMesh::QGauss::init_3D(), libMesh::QSimpson::init_3D(), and libMesh::QBase::init_3D().
 {
   const unsigned int np = q1D.n_points();
   _points.resize(np * np * np);
   _weights.resize(np * np * np);
   unsigned int q=0;
   for (unsigned int k=0; k<np; k++)
     for (unsigned int j=0; j<np; j++)
       for (unsigned int i=0; i<np; i++)
         {
           _points[q](0) = q1D.qp(i)(0);
           _points[q](1) = q1D.qp(j)(0);
           _points[q](2) = q1D.qp(k)(0);
           _weights[q] = q1D.w(i) * q1D.w(j) * q1D.w(k);
           q++;
         }
 }
void libMesh::QBase::tensor_product_prism (const QBase & q1D, const QBase & q2D) protected inherited
Computes the tensor product of a 1D quadrature rule and a 2D quadrature rule. Used in the init_3D routines for prismatic element types.
Definition at line 181 of file quadrature.C.
References libMesh::QBase::_points, libMesh::QBase::_weights, libMesh::QBase::n_points(), libMesh::QBase::qp(), and libMesh::QBase::w().
Referenced by libMesh::QGrid::init_3D(), libMesh::QTrap::init_3D(), libMesh::QSimpson::init_3D(), libMesh::QGauss::init_3D(), and libMesh::QBase::init_3D().
 {
   const unsigned int n_points1D = q1D.n_points();
   const unsigned int n_points2D = q2D.n_points();
   _points.resize  (n_points1D * n_points2D);
   _weights.resize (n_points1D * n_points2D);
   unsigned int q=0;
   for (unsigned int j=0; j<n_points1D; j++)
     for (unsigned int i=0; i<n_points2D; i++)
       {
         _points[q](0) = q2D.qp(i)(0);
         _points[q](1) = q2D.qp(i)(1);
         _points[q](2) = q1D.qp(j)(0);
         _weights[q] = q2D.w(i) * q1D.w(j);
         q++;
       }
 }
void libMesh::QBase::tensor_product_quad (const QBase & q1D) protected inherited
Constructs a 2D rule from the tensor product of q1D with itself. Used in the init_2D() routines for quadrilateral element types.
Definition at line 127 of file quadrature.C.
References libMesh::QBase::_points, libMesh::QBase::_weights, libMesh::QBase::n_points(), libMesh::QBase::qp(), and libMesh::QBase::w().
Referenced by init_2D(), libMesh::QGrid::init_2D(), libMesh::QTrap::init_2D(), libMesh::QGauss::init_2D(), libMesh::QSimpson::init_2D(), and libMesh::QBase::init_3D().
 {
   const unsigned int np = q1D.n_points();
   _points.resize(np * np);
   _weights.resize(np * np);
   unsigned int q=0;
   for (unsigned int j=0; j<np; j++)
     for (unsigned int i=0; i<np; i++)
       {
         _points[q](0) = q1D.qp(i)(0);
         _points[q](1) = q1D.qp(j)(0);
         _weights[q] = q1D.w(i)*q1D.w(j);
         q++;
       }
 }
virtual QuadratureType libMesh::QGaussLobatto::type () const inline virtual
Returns
QGAUSS_LOBATTO.
Implements libMesh::QBase.
Definition at line 59 of file quadrature_gauss_lobatto.h.
References libMesh::QBase::_type, init_1D(), init_2D(), init_3D(), libMesh::INVALID_ELEM, and libMesh::QGAUSS_LOBATTO.
 { return QGAUSS_LOBATTO; }
Real libMesh::QBase::w (const unsigned int i) const inline inherited
Returns
The quadrature weight.
Definition at line 160 of file quadrature.h.
References libMesh::QBase::_weights, libMesh::QBase::init(), libMesh::INVALID_ELEM, and libMesh::QBase::type().
Referenced by libMesh::QConical::conical_product_pyramid(), libMesh::QConical::conical_product_tet(), libMesh::QConical::conical_product_tri(), libMesh::QBase::tensor_product_hex(), libMesh::QBase::tensor_product_prism(), and libMesh::QBase::tensor_product_quad().
   {
     libmesh_assert_less (i, _weights.size());
     return _weights[i];
   }
Member Data Documentation
ReferenceCounter::Counts libMesh::ReferenceCounter::_counts static protected inherited
Actually holds the data.
Definition at line 124 of file reference_counter.h.
Referenced by libMesh::ReferenceCounter::get_info(), libMesh::ReferenceCounter::increment_constructor_count(), and libMesh::ReferenceCounter::increment_destructor_count().
const unsigned int libMesh::QBase::_dim protected inherited
The spatial dimension of the quadrature rule.
Definition at line 311 of file quadrature.h.
Referenced by libMesh::QBase::get_dim(), libMesh::QBase::init(), QGaussLobatto(), and libMesh::QBase::scale().
bool libMesh::ReferenceCounter::_enable_print_counter = true static protected inherited
Flag to control whether reference count information is printed when print_info is called.
Definition at line 143 of file reference_counter.h.
Referenced by libMesh::ReferenceCounter::disable_print_counter_info(), libMesh::ReferenceCounter::enable_print_counter_info(), and libMesh::ReferenceCounter::print_info().
Threads::spin_mutex libMesh::ReferenceCounter::_mutex static protected inherited
Mutual exclusion object to enable thread-safe reference counting.
Definition at line 137 of file reference_counter.h.
Threads::atomic< unsigned int > libMesh::ReferenceCounter::_n_objects static protected inherited
The number of objects. Print the reference count information when the number returns to 0.
Definition at line 132 of file reference_counter.h.
Referenced by libMesh::ReferenceCounter::n_objects(), libMesh::ReferenceCounter::ReferenceCounter(), and libMesh::ReferenceCounter::~ReferenceCounter().
const Order libMesh::QBase::_order protected inherited
The polynomial order which the quadrature rule is capable of integrating exactly.
Definition at line 317 of file quadrature.h.
Referenced by libMesh::QConical::conical_product_pyramid(), libMesh::QConical::conical_product_tet(), libMesh::QConical::conical_product_tri(), libMesh::QBase::get_order(), libMesh::QClough::init_1D(), init_1D(), libMesh::QConical::init_1D(), libMesh::QGrid::init_1D(), libMesh::QGauss::init_1D(), libMesh::QJacobi::init_1D(), libMesh::QMonomial::init_1D(), libMesh::QGrundmann_Moller::init_1D(), libMesh::QClough::init_2D(), init_2D(), libMesh::QGrid::init_2D(), libMesh::QGauss::init_2D(), libMesh::QMonomial::init_2D(), libMesh::QGrundmann_Moller::init_2D(), init_3D(), libMesh::QGrid::init_3D(), libMesh::QGauss::init_3D(), libMesh::QMonomial::init_3D(), and libMesh::QGrundmann_Moller::init_3D().
unsigned int libMesh::QBase::_p_level protected inherited
The p-level of the element for which the current values have been computed.
Definition at line 329 of file quadrature.h.
Referenced by libMesh::QBase::get_order(), libMesh::QBase::get_p_level(), and libMesh::QBase::init().
std::vector<Point> libMesh::QBase::_points protected inherited
The locations of the quadrature points in reference element space.
Definition at line 335 of file quadrature.h.
Referenced by libMesh::QConical::conical_product_pyramid(), libMesh::QConical::conical_product_tet(), libMesh::QConical::conical_product_tri(), libMesh::QGauss::dunavant_rule(), libMesh::QGauss::dunavant_rule2(), libMesh::QBase::get_points(), libMesh::QGrundmann_Moller::gm_rule(), libMesh::QBase::init_0D(), libMesh::QClough::init_1D(), init_1D(), libMesh::QConical::init_1D(), libMesh::QTrap::init_1D(), libMesh::QGrid::init_1D(), libMesh::QSimpson::init_1D(), libMesh::QGauss::init_1D(), libMesh::QJacobi::init_1D(), libMesh::QMonomial::init_1D(), libMesh::QGrundmann_Moller::init_1D(), libMesh::QClough::init_2D(), libMesh::QTrap::init_2D(), libMesh::QGrid::init_2D(), libMesh::QSimpson::init_2D(), libMesh::QGauss::init_2D(), libMesh::QMonomial::init_2D(), libMesh::QGrid::init_3D(), libMesh::QTrap::init_3D(), libMesh::QGauss::init_3D(), libMesh::QSimpson::init_3D(), libMesh::QMonomial::init_3D(), libMesh::QGrundmann_Moller::init_3D(), libMesh::QGauss::keast_rule(), libMesh::QMonomial::kim_rule(), libMesh::QBase::n_points(), libMesh::QBase::print_info(), libMesh::QBase::qp(), libMesh::QBase::scale(), libMesh::QMonomial::stroud_rule(), libMesh::QBase::tensor_product_hex(), libMesh::QBase::tensor_product_prism(), libMesh::QBase::tensor_product_quad(), and libMesh::QMonomial::wissmann_rule().
ElemType libMesh::QBase::_type protected inherited
The type of element for which the current values have been computed.
Definition at line 323 of file quadrature.h.
Referenced by libMesh::QBase::get_elem_type(), libMesh::QBase::init(), libMesh::QClough::type(), type(), libMesh::QConical::type(), libMesh::QGrid::type(), libMesh::QGauss::type(), libMesh::QSimpson::type(), libMesh::QTrap::type(), libMesh::QMonomial::type(), and libMesh::QGrundmann_Moller::type().
std::vector<Real> libMesh::QBase::_weights protected inherited
The quadrature weights. The order of the weights matches the ordering of the _points vector.
Definition at line 341 of file quadrature.h.
Referenced by libMesh::QConical::conical_product_pyramid(), libMesh::QConical::conical_product_tet(), libMesh::QConical::conical_product_tri(), libMesh::QGauss::dunavant_rule(), libMesh::QGauss::dunavant_rule2(), libMesh::QBase::get_weights(), libMesh::QGrundmann_Moller::gm_rule(), libMesh::QBase::init_0D(), libMesh::QClough::init_1D(), init_1D(), libMesh::QConical::init_1D(), libMesh::QTrap::init_1D(), libMesh::QGrid::init_1D(), libMesh::QSimpson::init_1D(), libMesh::QGauss::init_1D(), libMesh::QJacobi::init_1D(), libMesh::QMonomial::init_1D(), libMesh::QGrundmann_Moller::init_1D(), libMesh::QClough::init_2D(), libMesh::QTrap::init_2D(), libMesh::QGrid::init_2D(), libMesh::QGauss::init_2D(), libMesh::QSimpson::init_2D(), libMesh::QMonomial::init_2D(), libMesh::QGrid::init_3D(), libMesh::QTrap::init_3D(), libMesh::QSimpson::init_3D(), libMesh::QGauss::init_3D(), libMesh::QMonomial::init_3D(), libMesh::QGrundmann_Moller::init_3D(), libMesh::QGauss::keast_rule(), libMesh::QMonomial::kim_rule(), libMesh::QBase::print_info(), libMesh::QBase::scale(), libMesh::QMonomial::stroud_rule(), libMesh::QBase::tensor_product_hex(), libMesh::QBase::tensor_product_prism(), libMesh::QBase::tensor_product_quad(), libMesh::QBase::w(), and libMesh::QMonomial::wissmann_rule().
bool libMesh::QBase::allow_rules_with_negative_weights inherited
Flag (default true) controlling the use of quadrature rules with negative weights. Set this to false to require rules with all positive weights.
Rules with negative weights can be unsuitable for some problems. For example, it is possible for a rule with negative weights to obtain a negative result when integrating a positive function.
A particular example: if rules with negative weights are not allowed, a request for TET,THIRD (5 points) will return the TET,FIFTH (14 points) rule instead, nearly tripling the computational effort required!
Definition at line 232 of file quadrature.h.
Referenced by libMesh::QGrundmann_Moller::init_2D(), libMesh::QGauss::init_3D(), libMesh::QMonomial::init_3D(), and libMesh::QGrundmann_Moller::init_3D().
The documentation for this class was generated from the following files:
quadrature_gauss_lobatto.h
quadrature_gauss_lobatto.C
quadrature_gauss_lobatto_1D.C
quadrature_gauss_lobatto_2D.C
quadrature_gauss_lobatto_3D.C