libMesh: libMesh::Parallel::StandardType< unsigned long long > Class Template Reference
SomeWebsiteLogo
libMesh::Parallel::StandardType< unsigned long long > Class Template Reference
#include <parallel_implementation.h>
Public Member Functions
StandardType (const cxxtype *=libmesh_nullptr)
operator const data_type & () const
operator data_type & ()
void commit ()
void free ()
Protected Attributes
data_type _datatype
Detailed Description
template<>
class libMesh::Parallel::StandardType< unsigned long long >
Definition at line 162 of file parallel_implementation.h.
Constructor & Destructor Documentation
libMesh::Parallel::StandardType< unsigned long long >::StandardType (const cxxtype * = libmesh_nullptr) inline explicit
Definition at line 166 of file parallel_implementation.h.
References libMesh::Parallel::LIBMESH_PARALLEL_INTEGER_OPS().
                                                   :
     DataType(MPI_UNSIGNED_LONG)
   {
     libmesh_assert_equal_to(sizeof(unsigned long long),
                             sizeof(unsigned long));
   }
Member Function Documentation
void libMesh::Parallel::DataType::commit () inline inherited
Definition at line 335 of file parallel.h.
   {
 #ifdef LIBMESH_HAVE_MPI
     MPI_Type_commit (&_datatype);
 #endif
   }
void libMesh::Parallel::DataType::free () inline inherited
Definition at line 342 of file parallel.h.
Referenced by libMesh::Parallel::StandardType< std::complex< T > >::~StandardType(), libMesh::Parallel::StandardType< TypeTensor< T > >::~StandardType(), and libMesh::Parallel::StandardType< TensorValue< T > >::~StandardType().
   {
 #ifdef LIBMESH_HAVE_MPI
     MPI_Type_free (&_datatype);
 #endif
   }
libMesh::Parallel::DataType::operator const data_type & () const inline inherited
Definition at line 323 of file parallel.h.
   { return _datatype; }
libMesh::Parallel::DataType::operator data_type & () inline inherited
Definition at line 326 of file parallel.h.
   { return _datatype; }
Member Data Documentation
data_type libMesh::Parallel::DataType::_datatype protected inherited
Definition at line 351 of file parallel.h.
Referenced by libMesh::Parallel::DataType::DataType(), libMesh::Parallel::DataType::operator=(), libMesh::Parallel::StandardType< Hilbert::HilbertIndices >::StandardType(), libMesh::Parallel::StandardType< TypeVector< T > >::StandardType(), libMesh::Parallel::StandardType< VectorValue< T > >::StandardType(), libMesh::Parallel::StandardType< std::pair< T1, T2 > >::StandardType(), and libMesh::Parallel::StandardType< Point >::StandardType().
The documentation for this class was generated from the following file:
parallel_implementation.h