libMesh: exodusII.h File Reference
SomeWebsiteLogo
exodusII.h File Reference
Classes
struct ex_init_params
struct ex_block
struct ex_set
struct ex_block_params
struct ex_set_specs
struct ex_var_params
Typedefs
typedef enum ex_inquiry ex_inquiry
typedef enum ex_option_type ex_option_type
typedef enum ex_entity_type ex_entity_type
typedef enum ex_options ex_options
typedef int64_t ex_entity_id
typedef void void_int
typedef struct ex_init_params ex_init_params
typedef struct ex_block ex_block
typedef struct ex_set ex_set
typedef struct ex_block_params ex_block_params
typedef struct ex_set_specs ex_set_specs
typedef struct ex_var_params ex_var_params
Enumerations
enum ex_inquiry {
EX_INQ_FILE_TYPE = 1, EX_INQ_API_VERS = 2, EX_INQ_DB_VERS = 3, EX_INQ_TITLE = 4,
EX_INQ_DIM = 5, EX_INQ_NODES = 6, EX_INQ_ELEM = 7, EX_INQ_ELEM_BLK = 8,
EX_INQ_NODE_SETS = 9, EX_INQ_NS_NODE_LEN = 10, EX_INQ_SIDE_SETS = 11, EX_INQ_SS_NODE_LEN = 12,
EX_INQ_SS_ELEM_LEN = 13, EX_INQ_QA = 14, EX_INQ_INFO = 15, EX_INQ_TIME = 16,
EX_INQ_EB_PROP = 17, EX_INQ_NS_PROP = 18, EX_INQ_SS_PROP = 19, EX_INQ_NS_DF_LEN = 20,
EX_INQ_SS_DF_LEN = 21, EX_INQ_LIB_VERS = 22, EX_INQ_EM_PROP = 23, EX_INQ_NM_PROP = 24,
EX_INQ_ELEM_MAP = 25, EX_INQ_NODE_MAP = 26, EX_INQ_EDGE = 27, EX_INQ_EDGE_BLK = 28,
EX_INQ_EDGE_SETS = 29, EX_INQ_ES_LEN = 30, EX_INQ_ES_DF_LEN = 31, EX_INQ_EDGE_PROP = 32,
EX_INQ_ES_PROP = 33, EX_INQ_FACE = 34, EX_INQ_FACE_BLK = 35, EX_INQ_FACE_SETS = 36,
EX_INQ_FS_LEN = 37, EX_INQ_FS_DF_LEN = 38, EX_INQ_FACE_PROP = 39, EX_INQ_FS_PROP = 40,
EX_INQ_ELEM_SETS = 41, EX_INQ_ELS_LEN = 42, EX_INQ_ELS_DF_LEN = 43, EX_INQ_ELS_PROP = 44,
EX_INQ_EDGE_MAP = 45, EX_INQ_FACE_MAP = 46, EX_INQ_COORD_FRAMES = 47, EX_INQ_DB_MAX_ALLOWED_NAME_LENGTH = 48,
EX_INQ_DB_MAX_USED_NAME_LENGTH = 49, EX_INQ_MAX_READ_NAME_LENGTH = 50, EX_INQ_INVALID = -1
}
enum ex_option_type {
EX_OPT_MAX_NAME_LENGTH = 1, EX_OPT_COMPRESSION_TYPE, EX_OPT_COMPRESSION_LEVEL, EX_OPT_COMPRESSION_SHUFFLE,
EX_OPT_INTEGER_SIZE_API, EX_OPT_INTEGER_SIZE_DB
}
enum ex_entity_type {
EX_NODAL = 14, EX_NODE_BLOCK = 14, EX_NODE_SET = 2, EX_EDGE_BLOCK = 6,
EX_EDGE_SET = 7, EX_FACE_BLOCK = 8, EX_FACE_SET = 9, EX_ELEM_BLOCK = 1,
EX_ELEM_SET = 10, EX_SIDE_SET = 3, EX_ELEM_MAP = 4, EX_NODE_MAP = 5,
EX_EDGE_MAP = 11, EX_FACE_MAP = 12, EX_GLOBAL = 13, EX_COORDINATE = 15,
EX_INVALID = -1
}
enum ex_options { EX_DEFAULT = 0, EX_VERBOSE = 1, EX_DEBUG = 2, EX_ABORT = 4 }
Functions
EXODUS_EXPORT int ex_close (int exoid)
EXODUS_EXPORT int ex_copy (int in_exoid, int out_exoid)
EXODUS_EXPORT int ex_create_int (const char *path, int cmode, int *comp_ws, int *io_ws, int my_version)
EXODUS_EXPORT int ex_get_all_times (int exoid, void *time_values)
EXODUS_EXPORT int ex_get_coord_names (int exoid, char **coord_names)
EXODUS_EXPORT int ex_get_coord (int exoid, void *x_coor, void *y_coor, void *z_coor)
EXODUS_EXPORT int ex_get_n_coord (int exoid, int64_t start_node_num, int64_t num_nodes, void *x_coor, void *y_coor, void *z_coor)
EXODUS_EXPORT int ex_get_ids (int exoid, ex_entity_type obj_type, void_int *ids)
EXODUS_EXPORT int ex_get_coordinate_frames (int exoid, int *nframes, void_int *cf_ids, void *pt_coordinates, char *tags)
EXODUS_EXPORT int ex_get_glob_vars (int exoid, int time_step, int num_glob_vars, void *glob_var_vals)
EXODUS_EXPORT int ex_get_glob_var_time (int exoid, int glob_var_index, int beg_time_step, int end_time_step, void *glob_var_vals)
EXODUS_EXPORT int ex_get_info (int exoid, char **info)
EXODUS_EXPORT int ex_put_init_ext (int exoid, const ex_init_params *param)
EXODUS_EXPORT int ex_get_init_ext (int exoid, ex_init_params *param)
EXODUS_EXPORT int ex_get_init (int exoid, char *title, void_int *num_dim, void_int *num_nodes, void_int *num_elem, void_int *num_elem_blk, void_int *num_node_sets, void_int *num_side_sets)
EXODUS_EXPORT int ex_put_init (int exoid, const char *title, int64_t num_dim, int64_t num_nodes, int64_t num_elem, int64_t num_elem_blk, int64_t num_node_sets, int64_t num_side_sets)
EXODUS_EXPORT int ex_get_map_param (int exoid, int *num_node_maps, int *num_elem_maps)
EXODUS_EXPORT int ex_get_name (int exoid, ex_entity_type obj_type, ex_entity_id entity_id, char *name)
EXODUS_EXPORT int ex_get_names (int exoid, ex_entity_type obj_type, char **names)
EXODUS_EXPORT int ex_get_nset_var_tab (int exoid, int num_nodesets, int num_nset_var, int *nset_var_tab)
EXODUS_EXPORT int ex_get_n_nodal_var (int exoid, int time_step, int nodal_var_index, int64_t start_node, int64_t num_nodes, void *nodal_var_vals)
EXODUS_EXPORT int ex_get_prop_array (int exoid, ex_entity_type obj_type, const char *prop_name, void_int *values)
EXODUS_EXPORT int ex_get_prop (int exoid, ex_entity_type obj_type, ex_entity_id obj_id, const char *prop_name, void_int *value)
EXODUS_EXPORT int ex_get_partial_num_map (int exoid, ex_entity_type map_type, ex_entity_id map_id, int64_t ent_start, int64_t ent_count, void_int *elem_map)
EXODUS_EXPORT int ex_get_prop_names (int exoid, ex_entity_type obj_type, char **prop_names)
EXODUS_EXPORT int ex_get_qa (int exoid, char *qa_record[][4])
EXODUS_EXPORT int ex_get_time (int exoid, int time_step, void *time_value)
EXODUS_EXPORT int ex_get_variable_names (int exoid, ex_entity_type obj_type, int num_vars, char *var_names[])
EXODUS_EXPORT int ex_get_variable_name (int exoid, ex_entity_type obj_type, int var_num, char *var_name)
EXODUS_EXPORT int ex_get_variable_param (int exoid, ex_entity_type obj_type, int *num_vars)
EXODUS_EXPORT int ex_get_object_truth_vector (int exoid, ex_entity_type var_type, ex_entity_id object_id, int num_var, int *var_vector)
EXODUS_EXPORT int ex_get_truth_table (int exoid, ex_entity_type obj_type, int num_blk, int num_var, int *var_tab)
EXODUS_EXPORT int ex_open_int (const char *path, int mode, int *comp_ws, int *io_ws, float *version, int my_version)
EXODUS_EXPORT int ex_put_attr_param (int exoid, ex_entity_type obj_type, ex_entity_id obj_id, int num_attrs)
EXODUS_EXPORT int ex_get_attr_param (int exoid, ex_entity_type obj_type, ex_entity_id obj_id, int *num_attrs)
EXODUS_EXPORT int ex_put_all_var_param (int exoid, int num_g, int num_n, int num_e, int *elem_var_tab, int num_m, int *nset_var_tab, int num_s, int *sset_var_tab)
EXODUS_EXPORT int ex_put_concat_elem_block (int exoid, const void_int *elem_blk_id, char *elem_type[], const void_int *num_elem_this_blk, const void_int *num_nodes_per_elem, const void_int *num_attr, int define_maps)
EXODUS_EXPORT int ex_put_coord_names (int exoid, char *coord_names[])
EXODUS_EXPORT int ex_put_coord (int exoid, const void *x_coor, const void *y_coor, const void *z_coor)
EXODUS_EXPORT int ex_put_n_coord (int exoid, int64_t start_node_num, int64_t num_nodes, const void *x_coor, const void *y_coor, const void *z_coor)
EXODUS_EXPORT int ex_put_id_map (int exoid, ex_entity_type obj_type, const void_int *map)
EXODUS_EXPORT int ex_put_partial_id_map (int exoid, ex_entity_type obj_type, int64_t start_entity_num, int64_t num_entities, const void_int *map)
EXODUS_EXPORT int ex_put_n_elem_num_map (int exoid, int64_t start_ent, int64_t num_ents, const void_int *map)
EXODUS_EXPORT int ex_put_n_node_num_map (int exoid, int64_t start_ent, int64_t num_ents, const void_int *map)
EXODUS_EXPORT int ex_get_id_map (int exoid, ex_entity_type obj_type, void_int *map)
EXODUS_EXPORT int ex_put_coordinate_frames (int exoid, int nframes, const void_int *cf_ids, void *pt_coordinates, const char *tags)
EXODUS_EXPORT int ex_put_info (int exoid, int num_info, char *info[])
EXODUS_EXPORT int ex_put_map_param (int exoid, int num_node_maps, int num_elem_maps)
EXODUS_EXPORT int ex_put_name (int exoid, ex_entity_type obj_type, ex_entity_id entity_id, const char *name)
EXODUS_EXPORT int ex_put_names (int exoid, ex_entity_type obj_type, char *names[])
EXODUS_EXPORT int ex_put_n_one_attr (int exoid, ex_entity_type obj_type, ex_entity_id obj_id, int64_t start_num, int64_t num_ent, int attrib_index, const void *attrib)
EXODUS_EXPORT int ex_put_prop (int exoid, ex_entity_type obj_type, ex_entity_id obj_id, const char *prop_name, ex_entity_id value)
EXODUS_EXPORT int ex_put_prop_array (int exoid, ex_entity_type obj_type, const char *prop_name, const void_int *values)
EXODUS_EXPORT int ex_put_prop_names (int exoid, ex_entity_type obj_type, int num_props, char **prop_names)
EXODUS_EXPORT int ex_put_qa (int exoid, int num_qa_records, char *qa_record[][4])
EXODUS_EXPORT int ex_put_time (int exoid, int time_step, const void *time_value)
EXODUS_EXPORT int ex_put_variable_name (int exoid, ex_entity_type obj_type, int var_num, const char *var_name)
EXODUS_EXPORT int ex_put_variable_names (int exoid, ex_entity_type obj_type, int num_vars, char *var_names[])
EXODUS_EXPORT int ex_put_variable_param (int exoid, ex_entity_type obj_type, int num_vars)
EXODUS_EXPORT int ex_put_truth_table (int exoid, ex_entity_type obj_type, int num_blk, int num_var, int *var_tab)
EXODUS_EXPORT int ex_update (int exoid)
EXODUS_EXPORT int ex_get_num_props (int exoid, ex_entity_type obj_type)
EXODUS_EXPORT int ex_large_model (int exoid)
EXODUS_EXPORT size_t ex_header_size (int exoid)
EXODUS_EXPORT void ex_err (const char *module_name, const char *message, int err_num)
EXODUS_EXPORT void ex_get_err (const char **msg, const char **func, int *errcode)
EXODUS_EXPORT void ex_opts (int options)
EXODUS_EXPORT int ex_inquire (int exoid, int inquiry, void_int *, float *, char *)
EXODUS_EXPORT int64_t ex_inquire_int (int exoid, int inquiry)
EXODUS_EXPORT int ex_int64_status (int exoid)
EXODUS_EXPORT int ex_set_int64_status (int exoid, int mode)
EXODUS_EXPORT int ex_set_max_name_length (int exoid, int length)
EXODUS_EXPORT int ex_set_option (int exoid, ex_option_type option, int option_value)
EXODUS_EXPORT int ex_put_num_map (int exoid, ex_entity_type map_type, ex_entity_id map_id, const void_int *map)
EXODUS_EXPORT int ex_get_num_map (int exoid, ex_entity_type map_type, ex_entity_id map_id, void_int *map)
EXODUS_EXPORT int ex_put_block (int exoid, ex_entity_type blk_type, ex_entity_id blk_id, const char *entry_descrip, int64_t num_entries_this_blk, int64_t num_nodes_per_entry, int64_t num_edges_per_entry, int64_t num_faces_per_entry, int64_t num_attr_per_entry)
EXODUS_EXPORT int ex_get_block (int exoid, ex_entity_type blk_type, ex_entity_id blk_id, char *elem_type, void_int *num_entries_this_blk, void_int *num_nodes_per_entry, void_int *num_edges_per_entry, void_int *num_faces_per_entry, void_int *num_attr_per_entry)
EXODUS_EXPORT int ex_get_block_param (int exoid, ex_block *block)
EXODUS_EXPORT int ex_put_block_param (int exoid, const ex_block block)
EXODUS_EXPORT int ex_put_concat_all_blocks (int exoid, const ex_block_params *param)
EXODUS_EXPORT int ex_put_entity_count_per_polyhedra (int exoid, ex_entity_type blk_type, ex_entity_id blk_id, const int *entity_counts)
EXODUS_EXPORT int ex_get_entity_count_per_polyhedra (int exoid, ex_entity_type blk_type, ex_entity_id blk_id, int *entity_counts)
EXODUS_EXPORT int ex_put_conn (int exoid, ex_entity_type blk_type, ex_entity_id blk_id, const void_int *node_conn, const void_int *elem_edge_conn, const void_int *elem_face_conn)
EXODUS_EXPORT int ex_get_conn (int exoid, ex_entity_type blk_type, ex_entity_id blk_id, void_int *nodeconn, void_int *edgeconn, void_int *faceconn)
EXODUS_EXPORT int ex_get_n_conn (int exoid, ex_entity_type blk_type, ex_entity_id blk_id, int64_t start_num, int64_t num_ent, void_int *nodeconn, void_int *edgeconn, void_int *faceconn)
EXODUS_EXPORT int ex_put_attr (int exoid, ex_entity_type blk_type, ex_entity_id blk_id, const void *attrib)
EXODUS_EXPORT int ex_get_attr (int exoid, ex_entity_type obj_type, ex_entity_id obj_id, void *attrib)
EXODUS_EXPORT int ex_put_one_attr (int exoid, ex_entity_type obj_type, ex_entity_id obj_id, int attrib_index, const void *attrib)
EXODUS_EXPORT int ex_get_one_attr (int exoid, ex_entity_type obj_type, ex_entity_id obj_id, int attrib_index, void *attrib)
EXODUS_EXPORT int ex_get_n_one_attr (int exoid, ex_entity_type obj_type, ex_entity_id obj_id, int64_t start_num, int64_t num_ent, int attrib_index, void *attrib)
EXODUS_EXPORT int ex_put_attr_names (int exoid, ex_entity_type blk_type, ex_entity_id blk_id, char **names)
EXODUS_EXPORT int ex_get_attr_names (int exoid, ex_entity_type obj_type, ex_entity_id obj_id, char **names)
EXODUS_EXPORT int ex_put_set_param (int exoid, ex_entity_type set_type, ex_entity_id set_id, int64_t num_entries_in_set, int64_t num_dist_fact_in_set)
EXODUS_EXPORT int ex_get_set_param (int exoid, ex_entity_type set_type, ex_entity_id set_id, void_int *num_entry_in_set, void_int *num_dist_fact_in_set)
EXODUS_EXPORT int ex_put_set (int exoid, ex_entity_type set_type, ex_entity_id set_id, const void_int *set_entry_list, const void_int *set_extra_list)
EXODUS_EXPORT int ex_get_set (int exoid, ex_entity_type set_type, ex_entity_id set_id, void_int *set_entry_list, void_int *set_extra_list)
EXODUS_EXPORT int ex_put_set_dist_fact (int exoid, ex_entity_type set_type, ex_entity_id set_id, const void *set_dist_fact)
EXODUS_EXPORT int ex_get_set_dist_fact (int exoid, ex_entity_type set_type, ex_entity_id set_id, void *set_dist_fact)
EXODUS_EXPORT int ex_put_concat_sets (int exoid, ex_entity_type set_type, const struct ex_set_specs *set_specs)
EXODUS_EXPORT int ex_get_concat_sets (int exoid, ex_entity_type set_type, struct ex_set_specs *set_specs)
EXODUS_EXPORT int ex_put_sets (int exoid, size_t set_count, const struct ex_set *sets)
EXODUS_EXPORT int ex_get_sets (int exoid, size_t set_count, struct ex_set *sets)
EXODUS_EXPORT int ex_put_all_var_param_ext (int exoid, const ex_var_params *vp)
EXODUS_EXPORT int ex_put_var (int exoid, int time_step, ex_entity_type var_type, int var_index, ex_entity_id obj_id, int64_t num_entries_this_obj, const void *var_vals)
EXODUS_EXPORT int ex_put_n_var (int exoid, int time_step, ex_entity_type var_type, int var_index, ex_entity_id obj_id, int64_t start_index, int64_t num_entities, const void *var_vals)
EXODUS_EXPORT int ex_get_var (int exoid, int time_step, ex_entity_type var_type, int var_index, ex_entity_id obj_id, int64_t num_entry_this_obj, void *var_vals)
EXODUS_EXPORT int ex_get_n_var (int exoid, int time_step, ex_entity_type var_type, int var_index, ex_entity_id obj_id, int64_t start_index, int64_t num_entities, void *var_vals)
EXODUS_EXPORT int ex_get_n_elem_var (int exoid, int time_step, int elem_var_index, ex_entity_id elem_blk_id, int64_t num_elem_this_blk, int64_t start_elem_num, int64_t num_elem, void *elem_var_vals)
EXODUS_EXPORT int ex_get_var_time (int exoid, ex_entity_type var_type, int var_index, int64_t id, int beg_time_step, int end_time_step, void *var_vals)
EXODUS_EXPORT int ex_cvt_nodes_to_sides (int exoid, void_int *num_elem_per_set, void_int *num_nodes_per_set, void_int *side_sets_elem_index, void_int *side_sets_node_index, void_int *side_sets_elem_list, void_int *side_sets_node_list, void_int *side_sets_side_list)
EXODUS_EXPORT int ex_put_nodal_var (int exoid, int time_step, int nodal_var_index, int64_t num_nodes, const void *nodal_var_vals)
EXODUS_EXPORT int ex_put_n_nodal_var (int exoid, int time_step, int nodal_var_index, int64_t start_node, int64_t num_nodes, const void *nodal_var_vals)
EXODUS_EXPORT int ex_get_partial_elem_map (int exoid, ex_entity_id map_id, int64_t ent_start, int64_t ent_count, void_int *elem_map)
EXODUS_EXPORT int ex_put_partial_elem_map (int exoid, ex_entity_id map_id, int64_t ent_start, int64_t ent_count, const void_int *elem_map)
EXODUS_EXPORT int ex_put_partial_num_map (int exoid, ex_entity_type map_type, ex_entity_id map_id, int64_t ent_start, int64_t ent_count, const void_int *map)
EXODUS_EXPORT int ex_put_partial_set_dist_fact (int exoid, ex_entity_type set_type, ex_entity_id set_id, int64_t offset, int64_t num_to_put, const void *set_dist_fact)
EXODUS_EXPORT int ex_get_concat_side_set_node_count (int exoid, int *side_set_node_cnt_list)
EXODUS_EXPORT int ex_get_side_set_node_list_len (int exoid, ex_entity_id side_set_id, void_int *side_set_node_list_len)
EXODUS_EXPORT int ex_get_side_set_node_count (int exoid, ex_entity_id side_set_id, int *side_set_node_cnt_list)
EXODUS_EXPORT int ex_get_side_set_node_list (int exoid, ex_entity_id side_set_id, void_int *side_set_node_cnt_list, void_int *side_set_node_list)
EXODUS_EXPORT int ex_get_init_info (int exoid, int *num_proc, int *num_proc_in_f, char *ftype)
EXODUS_EXPORT int ex_put_init_info (int exoid, int num_proc, int num_proc_in_f, char *ftype)
EXODUS_EXPORT int ex_get_init_global (int exoid, void_int *num_nodes_g, void_int *num_elems_g, void_int *num_elem_blks_g, void_int *num_node_sets_g, void_int *num_side_sets_g)
EXODUS_EXPORT int ex_put_init_global (int exoid, int64_t num_nodes_g, int64_t num_elems_g, int64_t num_elem_blks_g, int64_t num_node_sets_g, int64_t num_side_sets_g)
EXODUS_EXPORT int ex_get_loadbal_param (int exoid, void_int *num_int_nodes, void_int *num_bor_nodes, void_int *num_ext_nodes, void_int *num_int_elems, void_int *num_bor_elems, void_int *num_node_cmaps, void_int *num_elem_cmaps, int processor)
EXODUS_EXPORT int ex_put_loadbal_param (int exoid, int64_t num_int_nodes, int64_t num_bor_nodes, int64_t num_ext_nodes, int64_t num_int_elems, int64_t num_bor_elems, int64_t num_node_cmaps, int64_t num_elem_cmaps, int processor)
EXODUS_EXPORT int ex_put_loadbal_param_cc (int exoid, void_int *num_int_nodes, void_int *num_bor_nodes, void_int *num_ext_nodes, void_int *num_int_elems, void_int *num_bor_elems, void_int *num_node_cmaps, void_int *num_elem_cmaps)
EXODUS_EXPORT int ex_get_ns_param_global (int exoid, void_int *ns_ids_glob, void_int *ns_n_cnt_glob, void_int *ns_df_cnt_glob)
EXODUS_EXPORT int ex_put_ns_param_global (int exoid, void_int *global_ids, void_int *global_n_cnts, void_int *global_df_cnts)
EXODUS_EXPORT int ex_get_ss_param_global (int exoid, void_int *ss_ids_glob, void_int *ss_s_cnt_glob, void_int *ss_df_cnt_glob)
EXODUS_EXPORT int ex_put_ss_param_global (int exoid, void_int *global_ids, void_int *global_el_cnts, void_int *global_df_cnts)
EXODUS_EXPORT int ex_get_eb_info_global (int exoid, void_int *el_blk_ids, void_int *el_blk_cnts)
EXODUS_EXPORT int ex_put_eb_info_global (int exoid, void_int *el_blk_ids, void_int *el_blk_cnts)
EXODUS_EXPORT int ex_get_n_side_set (int exoid, ex_entity_id side_set_id, int64_t start_side_num, int64_t num_sides, void_int *side_set_elem_list, void_int *side_set_side_list)
EXODUS_EXPORT int ex_put_n_side_set (int exoid, ex_entity_id side_set_id, int64_t start_side_num, int64_t num_sides, const void_int *side_set_elem_list, const void_int *side_set_side_list)
EXODUS_EXPORT int ex_get_n_side_set_df (int exoid, ex_entity_id side_set_id, int64_t start_num, int64_t num_df_to_get, void *side_set_df)
EXODUS_EXPORT int ex_put_n_side_set_df (int exoid, ex_entity_id side_set_id, int64_t start_num, int64_t num_df_to_get, void *side_set_df)
EXODUS_EXPORT int ex_get_n_node_set (int exoid, ex_entity_id node_set_id, int64_t start_node_num, int64_t num_node, void_int *node_set_node_list)
EXODUS_EXPORT int ex_put_n_node_set (int exoid, ex_entity_id node_set_id, int64_t start_node_num, int64_t num_node, const void_int *node_set_node_list)
EXODUS_EXPORT int ex_get_n_node_set_df (int exoid, ex_entity_id node_set_id, int64_t start_num, int64_t num_df_to_get, void *node_set_df)
EXODUS_EXPORT int ex_put_n_node_set_df (int exoid, ex_entity_id node_set_id, int64_t start_num, int64_t num_df_to_get, void *node_set_df)
EXODUS_EXPORT int ex_get_n_elem_conn (int exoid, ex_entity_id elem_blk_id, int64_t start_elem_num, int64_t num_elems, void_int *connect)
EXODUS_EXPORT int ex_put_n_elem_conn (int exoid, ex_entity_id elem_blk_id, int64_t start_elem_num, int64_t num_elems, const void_int *connect)
EXODUS_EXPORT int ex_get_n_elem_attr (int exoid, ex_entity_id elem_blk_id, int64_t start_elem_num, int64_t num_elems, void *attrib)
EXODUS_EXPORT int ex_put_n_elem_attr (int exoid, ex_entity_id elem_blk_id, int64_t start_elem_num, int64_t num_elems, void *attrib)
EXODUS_EXPORT int ex_get_elem_type (int exoid, ex_entity_id elem_blk_id, char *elem_type)
EXODUS_EXPORT int ex_put_elem_var_slab (int exoid, int time_step, int elem_var_index, ex_entity_id elem_blk_id, int64_t start_pos, int64_t num_vals, void *elem_var_vals)
EXODUS_EXPORT int ex_put_nodal_var_slab (int exoid, int time_step, int nodal_var_index, int64_t start_pos, int64_t num_vals, void *nodal_var_vals)
EXODUS_EXPORT int ex_get_n_elem_num_map (int exoid, int64_t start_ent, int64_t num_ents, void_int *elem_map)
EXODUS_EXPORT int ex_get_n_node_num_map (int exoid, int64_t start_ent, int64_t num_ents, void_int *node_map)
EXODUS_EXPORT int ex_get_processor_node_maps (int exoid, void_int *node_mapi, void_int *node_mapb, void_int *node_mape, int processor)
EXODUS_EXPORT int ex_put_processor_node_maps (int exoid, void_int *node_mapi, void_int *node_mapb, void_int *node_mape, int processor)
EXODUS_EXPORT int ex_get_processor_elem_maps (int exoid, void_int *elem_mapi, void_int *elem_mapb, int processor)
EXODUS_EXPORT int ex_put_processor_elem_maps (int exoid, void_int *elem_mapi, void_int *elem_mapb, int processor)
EXODUS_EXPORT int ex_get_cmap_params (int exoid, void_int *node_cmap_ids, void_int *node_cmap_node_cnts, void_int *elem_cmap_ids, void_int *elem_cmap_elem_cnts, int processor)
EXODUS_EXPORT int ex_put_cmap_params (int exoid, void_int *node_map_ids, void_int *node_map_node_cnts, void_int *elem_map_ids, void_int *elem_map_elem_cnts, int64_t processor)
EXODUS_EXPORT int ex_put_cmap_params_cc (int exoid, void_int *node_map_ids, void_int *node_map_node_cnts, void_int *node_proc_ptrs, void_int *elem_map_ids, void_int *elem_map_elem_cnts, void_int *elem_proc_ptrs)
EXODUS_EXPORT int ex_get_node_cmap (int exoid, ex_entity_id map_id, void_int *node_ids, void_int *proc_ids, int processor)
EXODUS_EXPORT int ex_put_node_cmap (int exoid, ex_entity_id map_id, void_int *node_ids, void_int *proc_ids, int processor)
EXODUS_EXPORT int ex_get_elem_cmap (int exoid, ex_entity_id map_id, void_int *elem_ids, void_int *side_ids, void_int *proc_ids, int processor)
EXODUS_EXPORT int ex_put_elem_cmap (int exoid, ex_entity_id map_id, void_int *elem_ids, void_int *side_ids, void_int *proc_ids, int processor)
EXODUS_EXPORT int ex_get_nodal_var (int exoid, int time_step, int nodal_var_index, int64_t num_nodes, void *nodal_var_vals)
EXODUS_EXPORT int ex_get_nodal_var_time (int exoid, int nodal_var_index, int64_t node_number, int beg_time_step, int end_time_step, void *nodal_var_vals)
EXODUS_EXPORT int ex_get_concat_node_sets (int exoid, void_int *node_set_ids, void_int *num_nodes_per_set, void_int *num_df_per_set, void_int *node_sets_node_index, void_int *node_sets_df_index, void_int *node_sets_node_list, void *node_sets_dist_fact)
EXODUS_EXPORT int ex_get_concat_side_sets (int exoid, void_int *side_set_ids, void_int *num_elem_per_set, void_int *num_dist_per_set, void_int *side_sets_elem_index, void_int *side_sets_dist_index, void_int *side_sets_elem_list, void_int *side_sets_side_list, void *side_sets_dist_fact)
EXODUS_EXPORT int ex_get_elem_attr (int exoid, ex_entity_id elem_blk_id, void *attrib)
EXODUS_EXPORT int ex_get_elem_attr_names (int exoid, ex_entity_id elem_blk_id, char **names)
EXODUS_EXPORT int ex_get_elem_blk_ids (int exoid, void_int *ids)
EXODUS_EXPORT int ex_get_elem_block (int exoid, ex_entity_id elem_blk_id, char *elem_type, void_int *num_elem_this_blk, void_int *num_nodes_per_elem, void_int *num_attr)
EXODUS_EXPORT int ex_get_elem_conn (int exoid, ex_entity_id elem_blk_id, void_int *connect)
EXODUS_EXPORT int ex_get_elem_map (int exoid, ex_entity_id map_id, void_int *elem_map)
EXODUS_EXPORT int ex_get_elem_num_map (int exoid, void_int *elem_map)
EXODUS_EXPORT int ex_get_elem_var (int exoid, int time_step, int elem_var_index, ex_entity_id elem_blk_id, int64_t num_elem_this_blk, void *elem_var_vals)
EXODUS_EXPORT int ex_get_elem_var_tab (int exoid, int num_elem_blk, int num_elem_var, int *elem_var_tab)
EXODUS_EXPORT int ex_get_elem_var_time (int exoid, int elem_var_index, int64_t elem_number, int beg_time_step, int end_time_step, void *elem_var_vals)
EXODUS_EXPORT int ex_get_map (int exoid, void_int *elem_map)
EXODUS_EXPORT int ex_get_node_map (int exoid, ex_entity_id map_id, void_int *node_map)
EXODUS_EXPORT int ex_get_node_num_map (int exoid, void_int *node_map)
EXODUS_EXPORT int ex_get_node_set_param (int exoid, ex_entity_id node_set_id, void_int *num_nodes_in_set, void_int *num_df_in_set)
EXODUS_EXPORT int ex_get_node_set (int exoid, ex_entity_id node_set_id, void_int *node_set_node_list)
EXODUS_EXPORT int ex_get_node_set_dist_fact (int exoid, ex_entity_id node_set_id, void *node_set_dist_fact)
EXODUS_EXPORT int ex_get_node_set_ids (int exoid, void_int *ids)
EXODUS_EXPORT int ex_get_nset_var (int exoid, int time_step, int nset_var_index, ex_entity_id nset_id, int64_t num_node_this_nset, void *nset_var_vals)
EXODUS_EXPORT int ex_get_one_elem_attr (int exoid, ex_entity_id elem_blk_id, int attrib_index, void *attrib)
EXODUS_EXPORT int ex_get_side_set (int exoid, ex_entity_id side_set_id, void_int *side_set_elem_list, void_int *side_set_side_list)
EXODUS_EXPORT int ex_get_side_set_dist_fact (int exoid, ex_entity_id side_set_id, void *side_set_dist_fact)
EXODUS_EXPORT int ex_get_side_set_ids (int exoid, void_int *ids)
EXODUS_EXPORT int ex_get_side_set_param (int exoid, ex_entity_id side_set_id, void_int *num_side_in_set, void_int *num_dist_fact_in_set)
EXODUS_EXPORT int ex_get_sset_var (int exoid, int time_step, int sset_var_index, ex_entity_id sset_id, int64_t num_side_this_sset, void *sset_var_vals)
EXODUS_EXPORT int ex_get_sset_var_tab (int exoid, int num_sidesets, int num_sset_var, int *sset_var_tab)
EXODUS_EXPORT int ex_get_var_names (int exoid, const char *var_type, int num_vars, char *var_names[])
EXODUS_EXPORT int ex_get_var_name (int exoid, const char *var_type, int var_num, char *var_name)
EXODUS_EXPORT int ex_get_var_param (int exoid, const char *var_type, int *num_vars)
EXODUS_EXPORT int ex_get_var_tab (int exoid, const char *var_type, int num_blk, int num_var, int *var_tab)
EXODUS_EXPORT int ex_put_concat_node_sets (int exoid, void_int *node_set_ids, void_int *num_nodes_per_set, void_int *num_dist_per_set, void_int *node_sets_node_index, void_int *node_sets_df_index, void_int *node_sets_node_list, void *node_sets_dist_fact)
EXODUS_EXPORT int ex_put_concat_side_sets (int exoid, void_int *side_set_ids, void_int *num_elem_per_set, void_int *num_dist_per_set, void_int *side_sets_elem_index, void_int *side_sets_dist_index, void_int *side_sets_elem_list, void_int *side_sets_side_list, void *side_sets_dist_fact)
EXODUS_EXPORT int ex_put_concat_var_param (int exoid, int num_g, int num_n, int num_e, int num_elem_blk, int *elem_var_tab)
EXODUS_EXPORT int ex_put_elem_attr_names (int exoid, ex_entity_id elem_blk_id, char *names[])
EXODUS_EXPORT int ex_put_elem_attr (int exoid, ex_entity_id elem_blk_id, const void *attrib)
EXODUS_EXPORT int ex_put_elem_block (int exoid, ex_entity_id elem_blk_id, const char *elem_type, int64_t num_elem_this_blk, int64_t num_nodes_per_elem, int64_t num_attr)
EXODUS_EXPORT int ex_put_elem_conn (int exoid, ex_entity_id elem_blk_id, const void_int *connect)
EXODUS_EXPORT int ex_put_elem_map (int exoid, ex_entity_id map_id, const void_int *elem_map)
EXODUS_EXPORT int ex_put_elem_num_map (int exoid, const void_int *elem_map)
EXODUS_EXPORT int ex_put_elem_var (int exoid, int time_step, int elem_var_index, ex_entity_id elem_blk_id, int64_t num_elem_this_blk, const void *elem_var_vals)
EXODUS_EXPORT int ex_put_elem_var_tab (int exoid, int num_elem_blk, int num_elem_var, int *elem_var_tab)
EXODUS_EXPORT int ex_put_glob_vars (int exoid, int time_step, int num_glob_vars, const void *glob_var_vals)
EXODUS_EXPORT int ex_put_map (int exoid, const void_int *elem_map)
EXODUS_EXPORT int ex_put_node_map (int exoid, ex_entity_id map_id, const void_int *node_map)
EXODUS_EXPORT int ex_put_node_num_map (int exoid, const void_int *node_map)
EXODUS_EXPORT int ex_put_node_set (int exoid, ex_entity_id node_set_id, const void_int *node_set_node_list)
EXODUS_EXPORT int ex_put_node_set_dist_fact (int exoid, ex_entity_id node_set_id, const void *node_set_dist_fact)
EXODUS_EXPORT int ex_put_node_set_param (int exoid, ex_entity_id node_set_id, int64_t num_nodes_in_set, int64_t num_dist_in_set)
EXODUS_EXPORT int ex_put_nset_var (int exoid, int time_step, int nset_var_index, ex_entity_id nset_id, int64_t num_nodes_this_nset, const void *nset_var_vals)
EXODUS_EXPORT int ex_put_nset_var_tab (int exoid, int num_nset, int num_nset_var, int *nset_var_tab)
EXODUS_EXPORT int ex_put_one_elem_attr (int exoid, ex_entity_id elem_blk_id, int attrib_index, const void *attrib)
EXODUS_EXPORT int ex_put_side_set (int exoid, ex_entity_id side_set_id, const void_int *side_set_elem_list, const void_int *side_set_side_list)
EXODUS_EXPORT int ex_put_side_set_dist_fact (int exoid, ex_entity_id side_set_id, const void *side_set_dist_fact)
EXODUS_EXPORT int ex_put_side_set_param (int exoid, ex_entity_id side_set_id, int64_t num_side_in_set, int64_t num_dist_fact_in_set)
EXODUS_EXPORT int ex_put_sset_var (int exoid, int time_step, int sset_var_index, ex_entity_id sset_id, int64_t num_faces_this_sset, const void *sset_var_vals)
EXODUS_EXPORT int ex_put_sset_var_tab (int exoid, int num_sset, int num_sset_var, int *sset_var_tab)
EXODUS_EXPORT int ex_put_var_name (int exoid, const char *var_type, int var_num, const char *var_name)
EXODUS_EXPORT int ex_put_var_names (int exoid, const char *var_type, int num_vars, char *var_names[])
EXODUS_EXPORT int ex_put_var_param (int exoid, const char *var_type, int num_vars)
EXODUS_EXPORT int ex_put_var_tab (int exoid, const char *var_type, int num_blk, int num_var, int *var_tab)
char * ex_name_of_object (ex_entity_type obj_type)
ex_entity_type ex_var_type_to_ex_entity_type (char var_type)
int ex_get_idx (int neid, const char *ne_var_name, int64_t *index, int pos)
Variables
int exerrval
int exoptval
Typedef Documentation
typedef int64_t ex_entity_id
Specifies that this argument is the id of an entity: element block, nodeset, sideset, ...
Definition at line 247 of file exodusII.h.
typedef enum ex_entity_type ex_entity_type
Definition at line 212 of file exodusII.h.
typedef enum ex_inquiry ex_inquiry
Definition at line 171 of file exodusII.h.
typedef enum ex_options ex_options
Definition at line 223 of file exodusII.h.
typedef void void_int
The mechanism for passing double/float and int/int64_t both use a void*; to avoid some confusion as to whether a function takes an integer or a float/double, the following typedef is used for the integer argument
Definition at line 254 of file exodusII.h.
Enumeration Type Documentation
enum ex_entity_type
Enumerator
EX_NODAL
nodal "block" for variables
EX_NODE_BLOCK
alias for EX_NODAL
EX_NODE_SET
node set property code
EX_EDGE_BLOCK
edge block property code
EX_EDGE_SET
edge set property code
EX_FACE_BLOCK
face block property code
EX_FACE_SET
face set property code
EX_ELEM_BLOCK
element block property code
EX_ELEM_SET
face set property code
EX_SIDE_SET
side set property code
EX_ELEM_MAP
element map property code
EX_NODE_MAP
node map property code
EX_EDGE_MAP
edge map property code
EX_FACE_MAP
face map property code
EX_GLOBAL
global "block" for variables
EX_COORDINATE
kluge so some internal wrapper functions work
EX_INVALID
Definition at line 191 of file exodusII.h.
                       {
     EX_NODAL       = 14,
     EX_NODE_BLOCK  = 14,
     EX_NODE_SET    =  2,
     EX_EDGE_BLOCK  =  6,
     EX_EDGE_SET    =  7,
     EX_FACE_BLOCK  =  8,
     EX_FACE_SET    =  9,
     EX_ELEM_BLOCK  =  1,
     EX_ELEM_SET    = 10,
     EX_SIDE_SET    =  3,
     EX_ELEM_MAP    =  4,
     EX_NODE_MAP    =  5,
     EX_EDGE_MAP    = 11,
     EX_FACE_MAP    = 12,
     EX_GLOBAL      = 13,
     EX_COORDINATE  = 15,
     EX_INVALID     = -1};
enum ex_inquiry
See also
ex_inquire()
Enumerator
EX_INQ_FILE_TYPE
inquire EXODUS II file type
EX_INQ_API_VERS
inquire API version number
EX_INQ_DB_VERS
inquire database version number
EX_INQ_TITLE
inquire database title
EX_INQ_DIM
inquire number of dimensions
EX_INQ_NODES
inquire number of nodes
EX_INQ_ELEM
inquire number of elements
EX_INQ_ELEM_BLK
inquire number of element blocks
EX_INQ_NODE_SETS
inquire number of node sets
EX_INQ_NS_NODE_LEN
inquire length of node set node list
EX_INQ_SIDE_SETS
inquire number of side sets
EX_INQ_SS_NODE_LEN
inquire length of side set node list
EX_INQ_SS_ELEM_LEN
inquire length of side set element list
EX_INQ_QA
inquire number of QA records
EX_INQ_INFO
inquire number of info records
EX_INQ_TIME
inquire number of time steps in the database
EX_INQ_EB_PROP
inquire number of element block properties
EX_INQ_NS_PROP
inquire number of node set properties
EX_INQ_SS_PROP
inquire number of side set properties
EX_INQ_NS_DF_LEN
inquire length of node set distribution factor list
EX_INQ_SS_DF_LEN
inquire length of side set distribution factor list
EX_INQ_LIB_VERS
inquire API Lib vers number
EX_INQ_EM_PROP
inquire number of element map properties
EX_INQ_NM_PROP
inquire number of node map properties
EX_INQ_ELEM_MAP
inquire number of element maps
EX_INQ_NODE_MAP
inquire number of node maps
EX_INQ_EDGE
inquire number of edges
EX_INQ_EDGE_BLK
inquire number of edge blocks
EX_INQ_EDGE_SETS
inquire number of edge sets
EX_INQ_ES_LEN
inquire length of concat edge set edge list
EX_INQ_ES_DF_LEN
inquire length of concat edge set dist factor list
EX_INQ_EDGE_PROP
inquire number of properties stored per edge block
EX_INQ_ES_PROP
inquire number of properties stored per edge set
EX_INQ_FACE
inquire number of faces
EX_INQ_FACE_BLK
inquire number of face blocks
EX_INQ_FACE_SETS
inquire number of face sets
EX_INQ_FS_LEN
inquire length of concat face set face list
EX_INQ_FS_DF_LEN
inquire length of concat face set dist factor list
EX_INQ_FACE_PROP
inquire number of properties stored per face block
EX_INQ_FS_PROP
inquire number of properties stored per face set
EX_INQ_ELEM_SETS
inquire number of element sets
EX_INQ_ELS_LEN
inquire length of concat element set element list
EX_INQ_ELS_DF_LEN
inquire length of concat element set dist factor list
EX_INQ_ELS_PROP
inquire number of properties stored per elem set
EX_INQ_EDGE_MAP
inquire number of edge maps
EX_INQ_FACE_MAP
inquire number of face maps
EX_INQ_COORD_FRAMES
inquire number of coordinate frames
EX_INQ_DB_MAX_ALLOWED_NAME_LENGTH
inquire size of MAX_NAME_LENGTH dimension on database
EX_INQ_DB_MAX_USED_NAME_LENGTH
inquire size of MAX_NAME_LENGTH dimension on database
EX_INQ_MAX_READ_NAME_LENGTH
inquire client-specified max size of returned names
EX_INQ_INVALID
Definition at line 118 of file exodusII.h.
                   {
     EX_INQ_FILE_TYPE       =  1,
     EX_INQ_API_VERS        =  2,
     EX_INQ_DB_VERS         =  3,
     EX_INQ_TITLE           =  4,
     EX_INQ_DIM             =  5,
     EX_INQ_NODES           =  6,
     EX_INQ_ELEM            =  7,
     EX_INQ_ELEM_BLK        =  8,
     EX_INQ_NODE_SETS       =  9,
     EX_INQ_NS_NODE_LEN     = 10,
     EX_INQ_SIDE_SETS       = 11,
     EX_INQ_SS_NODE_LEN     = 12,
     EX_INQ_SS_ELEM_LEN     = 13,
     EX_INQ_QA              = 14,
     EX_INQ_INFO            = 15,
     EX_INQ_TIME            = 16,
     EX_INQ_EB_PROP         = 17,
     EX_INQ_NS_PROP         = 18,
     EX_INQ_SS_PROP         = 19,
     EX_INQ_NS_DF_LEN       = 20,
     EX_INQ_SS_DF_LEN       = 21,
     EX_INQ_LIB_VERS        = 22,
     EX_INQ_EM_PROP         = 23,
     EX_INQ_NM_PROP         = 24,
     EX_INQ_ELEM_MAP        = 25,
     EX_INQ_NODE_MAP        = 26,
     EX_INQ_EDGE            = 27,
     EX_INQ_EDGE_BLK        = 28,
     EX_INQ_EDGE_SETS       = 29,
     EX_INQ_ES_LEN          = 30,
     EX_INQ_ES_DF_LEN       = 31,
     EX_INQ_EDGE_PROP       = 32,
     EX_INQ_ES_PROP         = 33,
     EX_INQ_FACE            = 34,
     EX_INQ_FACE_BLK        = 35,
     EX_INQ_FACE_SETS       = 36,
     EX_INQ_FS_LEN          = 37,
     EX_INQ_FS_DF_LEN       = 38,
     EX_INQ_FACE_PROP       = 39,
     EX_INQ_FS_PROP         = 40,
     EX_INQ_ELEM_SETS       = 41,
     EX_INQ_ELS_LEN         = 42,
     EX_INQ_ELS_DF_LEN      = 43,
     EX_INQ_ELS_PROP        = 44,
     EX_INQ_EDGE_MAP        = 45,
     EX_INQ_FACE_MAP        = 46,
     EX_INQ_COORD_FRAMES    = 47,
     EX_INQ_DB_MAX_ALLOWED_NAME_LENGTH  = 48,
     EX_INQ_DB_MAX_USED_NAME_LENGTH  = 49,
     EX_INQ_MAX_READ_NAME_LENGTH = 50,
     EX_INQ_INVALID         = -1};
enum ex_options
ex_opts() function codes - codes are OR'ed into exopts
Enumerator
EX_DEFAULT
EX_VERBOSE
verbose mode message flag
EX_DEBUG
debug mode def
EX_ABORT
abort mode flag def
Definition at line 217 of file exodusII.h.
                   {
     EX_DEFAULT  = 0,
     EX_VERBOSE  = 1,
     EX_DEBUG    = 2,
     EX_ABORT    = 4
   };
Function Documentation
EXODUS_EXPORT int ex_close (int exoid)
Referenced by libMesh::ExodusII_IO_Helper::close().
EXODUS_EXPORT int ex_copy (int in_exoid, int out_exoid)
EXODUS_EXPORT int ex_create_int (const char * path, int cmode, int * comp_ws, int * io_ws, int my_version)
EXODUS_EXPORT int ex_cvt_nodes_to_sides (int exoid, void_int * num_elem_per_set, void_int * num_nodes_per_set, void_int * side_sets_elem_index, void_int * side_sets_node_index, void_int * side_sets_elem_list, void_int * side_sets_node_list, void_int * side_sets_side_list)
EXODUS_EXPORT void ex_err (const char * module_name, const char * message, int err_num)
EXODUS_EXPORT int ex_get_all_times (int exoid, void * time_values)
Referenced by libMesh::ExodusII_IO_Helper::read_time_steps().
EXODUS_EXPORT int ex_get_attr (int exoid, ex_entity_type obj_type, ex_entity_id obj_id, void * attrib)
EXODUS_EXPORT int ex_get_attr_names (int exoid, ex_entity_type obj_type, ex_entity_id obj_id, char ** names)
EXODUS_EXPORT int ex_get_attr_param (int exoid, ex_entity_type obj_type, ex_entity_id obj_id, int * num_attrs)
EXODUS_EXPORT int ex_get_block (int exoid, ex_entity_type blk_type, ex_entity_id blk_id, char * elem_type, void_int * num_entries_this_blk, void_int * num_nodes_per_entry, void_int * num_edges_per_entry, void_int * num_faces_per_entry, void_int * num_attr_per_entry)
Deprecated:
Use ex_get_block_param()
EXODUS_EXPORT int ex_get_block_param (int exoid, ex_block * block)
EXODUS_EXPORT int ex_get_cmap_params (int exoid, void_int * node_cmap_ids, void_int * node_cmap_node_cnts, void_int * elem_cmap_ids, void_int * elem_cmap_elem_cnts, int processor)
EXODUS_EXPORT int ex_get_concat_node_sets (int exoid, void_int * node_set_ids, void_int * num_nodes_per_set, void_int * num_df_per_set, void_int * node_sets_node_index, void_int * node_sets_df_index, void_int * node_sets_node_list, void * node_sets_dist_fact)
EXODUS_EXPORT int ex_get_concat_sets (int exoid, ex_entity_type set_type, struct ex_set_specs * set_specs)
EXODUS_EXPORT int ex_get_concat_side_set_node_count (int exoid, int * side_set_node_cnt_list)
EXODUS_EXPORT int ex_get_concat_side_sets (int exoid, void_int * side_set_ids, void_int * num_elem_per_set, void_int * num_dist_per_set, void_int * side_sets_elem_index, void_int * side_sets_dist_index, void_int * side_sets_elem_list, void_int * side_sets_side_list, void * side_sets_dist_fact)
EXODUS_EXPORT int ex_get_conn (int exoid, ex_entity_type blk_type, ex_entity_id blk_id, void_int * nodeconn, void_int * edgeconn, void_int * faceconn)
EXODUS_EXPORT int ex_get_coord (int exoid, void * x_coor, void * y_coor, void * z_coor)
Referenced by libMesh::ExodusII_IO_Helper::read_nodes().
EXODUS_EXPORT int ex_get_coord_names (int exoid, char ** coord_names)
EXODUS_EXPORT int ex_get_coordinate_frames (int exoid, int * nframes, void_int * cf_ids, void * pt_coordinates, char * tags)
EXODUS_EXPORT int ex_get_eb_info_global (int exoid, void_int * el_blk_ids, void_int * el_blk_cnts)
EXODUS_EXPORT int ex_get_elem_attr (int exoid, ex_entity_id elem_blk_id, void * attrib)
EXODUS_EXPORT int ex_get_elem_attr_names (int exoid, ex_entity_id elem_blk_id, char ** names)
EXODUS_EXPORT int ex_get_elem_blk_ids (int exoid, void_int * ids)
Referenced by libMesh::ExodusII_IO_Helper::read_block_info().
EXODUS_EXPORT int ex_get_elem_block (int exoid, ex_entity_id elem_blk_id, char * elem_type, void_int * num_elem_this_blk, void_int * num_nodes_per_elem, void_int * num_attr)
Referenced by libMesh::ExodusII_IO_Helper::read_elem_in_block(), and libMesh::ExodusII_IO_Helper::read_elemental_var_values().
EXODUS_EXPORT int ex_get_elem_cmap (int exoid, ex_entity_id map_id, void_int * elem_ids, void_int * side_ids, void_int * proc_ids, int processor)
EXODUS_EXPORT int ex_get_elem_conn (int exoid, ex_entity_id elem_blk_id, void_int * connect)
Referenced by libMesh::ExodusII_IO_Helper::read_elem_in_block().
EXODUS_EXPORT int ex_get_elem_map (int exoid, ex_entity_id map_id, void_int * elem_map)
EXODUS_EXPORT int ex_get_elem_num_map (int exoid, void_int * elem_map)
Referenced by libMesh::ExodusII_IO_Helper::read_elem_num_map().
EXODUS_EXPORT int ex_get_elem_type (int exoid, ex_entity_id elem_blk_id, char * elem_type)
EXODUS_EXPORT int ex_get_elem_var (int exoid, int time_step, int elem_var_index, ex_entity_id elem_blk_id, int64_t num_elem_this_blk, void * elem_var_vals)
Referenced by libMesh::ExodusII_IO_Helper::read_elemental_var_values().
EXODUS_EXPORT int ex_get_elem_var_tab (int exoid, int num_elem_blk, int num_elem_var, int * elem_var_tab)
EXODUS_EXPORT int ex_get_elem_var_time (int exoid, int elem_var_index, int64_t elem_number, int beg_time_step, int end_time_step, void * elem_var_vals)
EXODUS_EXPORT int ex_get_entity_count_per_polyhedra (int exoid, ex_entity_type blk_type, ex_entity_id blk_id, int * entity_counts)
EXODUS_EXPORT void ex_get_err (const char ** msg, const char ** func, int * errcode)
EXODUS_EXPORT int ex_get_glob_var_time (int exoid, int glob_var_index, int beg_time_step, int end_time_step, void * glob_var_vals)
EXODUS_EXPORT int ex_get_glob_vars (int exoid, int time_step, int num_glob_vars, void * glob_var_vals)
Referenced by libMesh::ExodusII_IO_Helper::read_global_values().
EXODUS_EXPORT int ex_get_id_map (int exoid, ex_entity_type obj_type, void_int * map)
EXODUS_EXPORT int ex_get_ids (int exoid, ex_entity_type obj_type, void_int * ids)
int ex_get_idx (int neid, const char * ne_var_name, int64_t * index, int pos)
EXODUS_EXPORT int ex_get_info (int exoid, char ** info)
EXODUS_EXPORT int ex_get_init (int exoid, char * title, void_int * num_dim, void_int * num_nodes, void_int * num_elem, void_int * num_elem_blk, void_int * num_node_sets, void_int * num_side_sets)
Referenced by libMesh::ExodusII_IO_Helper::read_header().
EXODUS_EXPORT int ex_get_init_ext (int exoid, ex_init_params * param)
EXODUS_EXPORT int ex_get_init_global (int exoid, void_int * num_nodes_g, void_int * num_elems_g, void_int * num_elem_blks_g, void_int * num_node_sets_g, void_int * num_side_sets_g)
EXODUS_EXPORT int ex_get_init_info (int exoid, int * num_proc, int * num_proc_in_f, char * ftype)
EXODUS_EXPORT int ex_get_loadbal_param (int exoid, void_int * num_int_nodes, void_int * num_bor_nodes, void_int * num_ext_nodes, void_int * num_int_elems, void_int * num_bor_elems, void_int * num_node_cmaps, void_int * num_elem_cmaps, int processor)
EXODUS_EXPORT int ex_get_map (int exoid, void_int * elem_map)
EXODUS_EXPORT int ex_get_map_param (int exoid, int * num_node_maps, int * num_elem_maps)
EXODUS_EXPORT int ex_get_n_conn (int exoid, ex_entity_type blk_type, ex_entity_id blk_id, int64_t start_num, int64_t num_ent, void_int * nodeconn, void_int * edgeconn, void_int * faceconn)
EXODUS_EXPORT int ex_get_n_coord (int exoid, int64_t start_node_num, int64_t num_nodes, void * x_coor, void * y_coor, void * z_coor)
EXODUS_EXPORT int ex_get_n_elem_attr (int exoid, ex_entity_id elem_blk_id, int64_t start_elem_num, int64_t num_elems, void * attrib)
EXODUS_EXPORT int ex_get_n_elem_conn (int exoid, ex_entity_id elem_blk_id, int64_t start_elem_num, int64_t num_elems, void_int * connect)
EXODUS_EXPORT int ex_get_n_elem_num_map (int exoid, int64_t start_ent, int64_t num_ents, void_int * elem_map)
EXODUS_EXPORT int ex_get_n_elem_var (int exoid, int time_step, int elem_var_index, ex_entity_id elem_blk_id, int64_t num_elem_this_blk, int64_t start_elem_num, int64_t num_elem, void * elem_var_vals)
EXODUS_EXPORT int ex_get_n_nodal_var (int exoid, int time_step, int nodal_var_index, int64_t start_node, int64_t num_nodes, void * nodal_var_vals)
EXODUS_EXPORT int ex_get_n_node_num_map (int exoid, int64_t start_ent, int64_t num_ents, void_int * node_map)
EXODUS_EXPORT int ex_get_n_node_set (int exoid, ex_entity_id node_set_id, int64_t start_node_num, int64_t num_node, void_int * node_set_node_list)
EXODUS_EXPORT int ex_get_n_node_set_df (int exoid, ex_entity_id node_set_id, int64_t start_num, int64_t num_df_to_get, void * node_set_df)
EXODUS_EXPORT int ex_get_n_one_attr (int exoid, ex_entity_type obj_type, ex_entity_id obj_id, int64_t start_num, int64_t num_ent, int attrib_index, void * attrib)
EXODUS_EXPORT int ex_get_n_side_set (int exoid, ex_entity_id side_set_id, int64_t start_side_num, int64_t num_sides, void_int * side_set_elem_list, void_int * side_set_side_list)
EXODUS_EXPORT int ex_get_n_side_set_df (int exoid, ex_entity_id side_set_id, int64_t start_num, int64_t num_df_to_get, void * side_set_df)
EXODUS_EXPORT int ex_get_n_var (int exoid, int time_step, ex_entity_type var_type, int var_index, ex_entity_id obj_id, int64_t start_index, int64_t num_entities, void * var_vals)
EXODUS_EXPORT int ex_get_name (int exoid, ex_entity_type obj_type, ex_entity_id entity_id, char * name)
Referenced by libMesh::ExodusII_IO_Helper::read_block_info(), libMesh::ExodusII_IO_Helper::read_nodeset_info(), and libMesh::ExodusII_IO_Helper::read_sideset_info().
EXODUS_EXPORT int ex_get_names (int exoid, ex_entity_type obj_type, char ** names)
EXODUS_EXPORT int ex_get_nodal_var (int exoid, int time_step, int nodal_var_index, int64_t num_nodes, void * nodal_var_vals)
Referenced by libMesh::ExodusII_IO_Helper::read_nodal_var_values().
EXODUS_EXPORT int ex_get_nodal_var_time (int exoid, int nodal_var_index, int64_t node_number, int beg_time_step, int end_time_step, void * nodal_var_vals)
EXODUS_EXPORT int ex_get_node_cmap (int exoid, ex_entity_id map_id, void_int * node_ids, void_int * proc_ids, int processor)
EXODUS_EXPORT int ex_get_node_map (int exoid, ex_entity_id map_id, void_int * node_map)
EXODUS_EXPORT int ex_get_node_num_map (int exoid, void_int * node_map)
Referenced by libMesh::ExodusII_IO_Helper::read_node_num_map().
EXODUS_EXPORT int ex_get_node_set (int exoid, ex_entity_id node_set_id, void_int * node_set_node_list)
Referenced by libMesh::ExodusII_IO_Helper::read_nodeset().
EXODUS_EXPORT int ex_get_node_set_dist_fact (int exoid, ex_entity_id node_set_id, void * node_set_dist_fact)
EXODUS_EXPORT int ex_get_node_set_ids (int exoid, void_int * ids)
Referenced by libMesh::ExodusII_IO_Helper::read_nodeset_info().
EXODUS_EXPORT int ex_get_node_set_param (int exoid, ex_entity_id node_set_id, void_int * num_nodes_in_set, void_int * num_df_in_set)
Referenced by libMesh::ExodusII_IO_Helper::read_nodeset().
EXODUS_EXPORT int ex_get_ns_param_global (int exoid, void_int * ns_ids_glob, void_int * ns_n_cnt_glob, void_int * ns_df_cnt_glob)
EXODUS_EXPORT int ex_get_nset_var (int exoid, int time_step, int nset_var_index, ex_entity_id nset_id, int64_t num_node_this_nset, void * nset_var_vals)
EXODUS_EXPORT int ex_get_nset_var_tab (int exoid, int num_nodesets, int num_nset_var, int * nset_var_tab)
EXODUS_EXPORT int ex_get_num_map (int exoid, ex_entity_type map_type, ex_entity_id map_id, void_int * map)
EXODUS_EXPORT int ex_get_num_props (int exoid, ex_entity_type obj_type)
EXODUS_EXPORT int ex_get_object_truth_vector (int exoid, ex_entity_type var_type, ex_entity_id object_id, int num_var, int * var_vector)
EXODUS_EXPORT int ex_get_one_attr (int exoid, ex_entity_type obj_type, ex_entity_id obj_id, int attrib_index, void * attrib)
EXODUS_EXPORT int ex_get_one_elem_attr (int exoid, ex_entity_id elem_blk_id, int attrib_index, void * attrib)
EXODUS_EXPORT int ex_get_partial_elem_map (int exoid, ex_entity_id map_id, int64_t ent_start, int64_t ent_count, void_int * elem_map)
EXODUS_EXPORT int ex_get_partial_num_map (int exoid, ex_entity_type map_type, ex_entity_id map_id, int64_t ent_start, int64_t ent_count, void_int * elem_map)
EXODUS_EXPORT int ex_get_processor_elem_maps (int exoid, void_int * elem_mapi, void_int * elem_mapb, int processor)
EXODUS_EXPORT int ex_get_processor_node_maps (int exoid, void_int * node_mapi, void_int * node_mapb, void_int * node_mape, int processor)
EXODUS_EXPORT int ex_get_prop (int exoid, ex_entity_type obj_type, ex_entity_id obj_id, const char * prop_name, void_int * value)
EXODUS_EXPORT int ex_get_prop_array (int exoid, ex_entity_type obj_type, const char * prop_name, void_int * values)
EXODUS_EXPORT int ex_get_prop_names (int exoid, ex_entity_type obj_type, char ** prop_names)
EXODUS_EXPORT int ex_get_qa (int exoid, char * qa_record[][4])
Referenced by libMesh::ExodusII_IO_Helper::read_qa_records().
EXODUS_EXPORT int ex_get_set (int exoid, ex_entity_type set_type, ex_entity_id set_id, void_int * set_entry_list, void_int * set_extra_list)
EXODUS_EXPORT int ex_get_set_dist_fact (int exoid, ex_entity_type set_type, ex_entity_id set_id, void * set_dist_fact)
EXODUS_EXPORT int ex_get_set_param (int exoid, ex_entity_type set_type, ex_entity_id set_id, void_int * num_entry_in_set, void_int * num_dist_fact_in_set)
EXODUS_EXPORT int ex_get_sets (int exoid, size_t set_count, struct ex_set * sets)
EXODUS_EXPORT int ex_get_side_set (int exoid, ex_entity_id side_set_id, void_int * side_set_elem_list, void_int * side_set_side_list)
Referenced by libMesh::ExodusII_IO_Helper::read_sideset().
EXODUS_EXPORT int ex_get_side_set_dist_fact (int exoid, ex_entity_id side_set_id, void * side_set_dist_fact)
EXODUS_EXPORT int ex_get_side_set_ids (int exoid, void_int * ids)
Referenced by libMesh::ExodusII_IO_Helper::read_sideset_info().
EXODUS_EXPORT int ex_get_side_set_node_count (int exoid, ex_entity_id side_set_id, int * side_set_node_cnt_list)
EXODUS_EXPORT int ex_get_side_set_node_list (int exoid, ex_entity_id side_set_id, void_int * side_set_node_cnt_list, void_int * side_set_node_list)
EXODUS_EXPORT int ex_get_side_set_node_list_len (int exoid, ex_entity_id side_set_id, void_int * side_set_node_list_len)
EXODUS_EXPORT int ex_get_side_set_param (int exoid, ex_entity_id side_set_id, void_int * num_side_in_set, void_int * num_dist_fact_in_set)
Referenced by libMesh::ExodusII_IO_Helper::read_sideset().
EXODUS_EXPORT int ex_get_ss_param_global (int exoid, void_int * ss_ids_glob, void_int * ss_s_cnt_glob, void_int * ss_df_cnt_glob)
EXODUS_EXPORT int ex_get_sset_var (int exoid, int time_step, int sset_var_index, ex_entity_id sset_id, int64_t num_side_this_sset, void * sset_var_vals)
EXODUS_EXPORT int ex_get_sset_var_tab (int exoid, int num_sidesets, int num_sset_var, int * sset_var_tab)
EXODUS_EXPORT int ex_get_time (int exoid, int time_step, void * time_value)
EXODUS_EXPORT int ex_get_truth_table (int exoid, ex_entity_type obj_type, int num_blk, int num_var, int * var_tab)
EXODUS_EXPORT int ex_get_var (int exoid, int time_step, ex_entity_type var_type, int var_index, ex_entity_id obj_id, int64_t num_entry_this_obj, void * var_vals)
EXODUS_EXPORT int ex_get_var_name (int exoid, const char * var_type, int var_num, char * var_name)
EXODUS_EXPORT int ex_get_var_names (int exoid, const char * var_type, int num_vars, char * var_names[])
Referenced by libMesh::ExodusII_IO_Helper::read_var_names_impl().
EXODUS_EXPORT int ex_get_var_param (int exoid, const char * var_type, int * num_vars)
Referenced by libMesh::ExodusII_IO_Helper::read_header(), libMesh::ExodusII_IO_Helper::read_var_names_impl(), and libMesh::ExodusII_IO_Helper::write_element_values().
EXODUS_EXPORT int ex_get_var_tab (int exoid, const char * var_type, int num_blk, int num_var, int * var_tab)
EXODUS_EXPORT int ex_get_var_time (int exoid, ex_entity_type var_type, int var_index, int64_t id, int beg_time_step, int end_time_step, void * var_vals)
EXODUS_EXPORT int ex_get_variable_name (int exoid, ex_entity_type obj_type, int var_num, char * var_name)
EXODUS_EXPORT int ex_get_variable_names (int exoid, ex_entity_type obj_type, int num_vars, char * var_names[])
EXODUS_EXPORT int ex_get_variable_param (int exoid, ex_entity_type obj_type, int * num_vars)
EXODUS_EXPORT size_t ex_header_size (int exoid)
EXODUS_EXPORT int ex_inquire (int exoid, int inquiry, void_int * , float * , char *)
Referenced by libMesh::ExodusII_IO_Helper::inquire().
EXODUS_EXPORT int64_t ex_inquire_int (int exoid, int inquiry)
EXODUS_EXPORT int ex_int64_status (int exoid)
EXODUS_EXPORT int ex_large_model (int exoid)
char* ex_name_of_object (ex_entity_type obj_type)
EXODUS_EXPORT int ex_open_int (const char * path, int mode, int * comp_ws, int * io_ws, float * version, int my_version)
EXODUS_EXPORT void ex_opts (int options)
EXODUS_EXPORT int ex_put_all_var_param (int exoid, int num_g, int num_n, int num_e, int * elem_var_tab, int num_m, int * nset_var_tab, int num_s, int * sset_var_tab)
EXODUS_EXPORT int ex_put_all_var_param_ext (int exoid, const ex_var_params * vp)
EXODUS_EXPORT int ex_put_attr (int exoid, ex_entity_type blk_type, ex_entity_id blk_id, const void * attrib)
EXODUS_EXPORT int ex_put_attr_names (int exoid, ex_entity_type blk_type, ex_entity_id blk_id, char ** names)
EXODUS_EXPORT int ex_put_attr_param (int exoid, ex_entity_type obj_type, ex_entity_id obj_id, int num_attrs)
EXODUS_EXPORT int ex_put_block (int exoid, ex_entity_type blk_type, ex_entity_id blk_id, const char * entry_descrip, int64_t num_entries_this_blk, int64_t num_nodes_per_entry, int64_t num_edges_per_entry, int64_t num_faces_per_entry, int64_t num_attr_per_entry)
EXODUS_EXPORT int ex_put_block_param (int exoid, const ex_block block)
EXODUS_EXPORT int ex_put_cmap_params (int exoid, void_int * node_map_ids, void_int * node_map_node_cnts, void_int * elem_map_ids, void_int * elem_map_elem_cnts, int64_t processor)
EXODUS_EXPORT int ex_put_cmap_params_cc (int exoid, void_int * node_map_ids, void_int * node_map_node_cnts, void_int * node_proc_ptrs, void_int * elem_map_ids, void_int * elem_map_elem_cnts, void_int * elem_proc_ptrs)
EXODUS_EXPORT int ex_put_concat_all_blocks (int exoid, const ex_block_params * param)
EXODUS_EXPORT int ex_put_concat_elem_block (int exoid, const void_int * elem_blk_id, char * elem_type[], const void_int * num_elem_this_blk, const void_int * num_nodes_per_elem, const void_int * num_attr, int define_maps)
Referenced by libMesh::ExodusII_IO_Helper::write_elements().
EXODUS_EXPORT int ex_put_concat_node_sets (int exoid, void_int * node_set_ids, void_int * num_nodes_per_set, void_int * num_dist_per_set, void_int * node_sets_node_index, void_int * node_sets_df_index, void_int * node_sets_node_list, void * node_sets_dist_fact)
EXODUS_EXPORT int ex_put_concat_sets (int exoid, ex_entity_type set_type, const struct ex_set_specs * set_specs)
EXODUS_EXPORT int ex_put_concat_side_sets (int exoid, void_int * side_set_ids, void_int * num_elem_per_set, void_int * num_dist_per_set, void_int * side_sets_elem_index, void_int * side_sets_dist_index, void_int * side_sets_elem_list, void_int * side_sets_side_list, void * side_sets_dist_fact)
EXODUS_EXPORT int ex_put_concat_var_param (int exoid, int num_g, int num_n, int num_e, int num_elem_blk, int * elem_var_tab)
EXODUS_EXPORT int ex_put_conn (int exoid, ex_entity_type blk_type, ex_entity_id blk_id, const void_int * node_conn, const void_int * elem_edge_conn, const void_int * elem_face_conn)
EXODUS_EXPORT int ex_put_coord (int exoid, const void * x_coor, const void * y_coor, const void * z_coor)
Referenced by libMesh::Nemesis_IO_Helper::write_nodal_coordinates(), and libMesh::ExodusII_IO_Helper::write_nodal_coordinates().
EXODUS_EXPORT int ex_put_coord_names (int exoid, char * coord_names[])
EXODUS_EXPORT int ex_put_coordinate_frames (int exoid, int nframes, const void_int * cf_ids, void * pt_coordinates, const char * tags)
EXODUS_EXPORT int ex_put_eb_info_global (int exoid, void_int * el_blk_ids, void_int * el_blk_cnts)
EXODUS_EXPORT int ex_put_elem_attr (int exoid, ex_entity_id elem_blk_id, const void * attrib)
EXODUS_EXPORT int ex_put_elem_attr_names (int exoid, ex_entity_id elem_blk_id, char * names[])
EXODUS_EXPORT int ex_put_elem_block (int exoid, ex_entity_id elem_blk_id, const char * elem_type, int64_t num_elem_this_blk, int64_t num_nodes_per_elem, int64_t num_attr)
Referenced by libMesh::Nemesis_IO_Helper::write_elements().
EXODUS_EXPORT int ex_put_elem_cmap (int exoid, ex_entity_id map_id, void_int * elem_ids, void_int * side_ids, void_int * proc_ids, int processor)
EXODUS_EXPORT int ex_put_elem_conn (int exoid, ex_entity_id elem_blk_id, const void_int * connect)
Referenced by libMesh::Nemesis_IO_Helper::write_elements(), and libMesh::ExodusII_IO_Helper::write_elements().
EXODUS_EXPORT int ex_put_elem_map (int exoid, ex_entity_id map_id, const void_int * elem_map)
EXODUS_EXPORT int ex_put_elem_num_map (int exoid, const void_int * elem_map)
Referenced by libMesh::Nemesis_IO_Helper::write_elements(), and libMesh::ExodusII_IO_Helper::write_elements().
EXODUS_EXPORT int ex_put_elem_var (int exoid, int time_step, int elem_var_index, ex_entity_id elem_blk_id, int64_t num_elem_this_blk, const void * elem_var_vals)
Referenced by libMesh::ExodusII_IO_Helper::write_element_values().
EXODUS_EXPORT int ex_put_elem_var_slab (int exoid, int time_step, int elem_var_index, ex_entity_id elem_blk_id, int64_t start_pos, int64_t num_vals, void * elem_var_vals)
EXODUS_EXPORT int ex_put_elem_var_tab (int exoid, int num_elem_blk, int num_elem_var, int * elem_var_tab)
Referenced by libMesh::ExodusII_IO_Helper::initialize_element_variables().
EXODUS_EXPORT int ex_put_entity_count_per_polyhedra (int exoid, ex_entity_type blk_type, ex_entity_id blk_id, const int * entity_counts)
EXODUS_EXPORT int ex_put_glob_vars (int exoid, int time_step, int num_glob_vars, const void * glob_var_vals)
Referenced by libMesh::ExodusII_IO_Helper::write_global_values().
EXODUS_EXPORT int ex_put_id_map (int exoid, ex_entity_type obj_type, const void_int * map)
EXODUS_EXPORT int ex_put_info (int exoid, int num_info, char * info[])
Referenced by libMesh::ExodusII_IO_Helper::write_information_records().
EXODUS_EXPORT int ex_put_init (int exoid, const char * title, int64_t num_dim, int64_t num_nodes, int64_t num_elem, int64_t num_elem_blk, int64_t num_node_sets, int64_t num_side_sets)
Referenced by libMesh::ExodusII_IO_Helper::initialize(), and libMesh::Nemesis_IO_Helper::write_exodus_initialization_info().
EXODUS_EXPORT int ex_put_init_ext (int exoid, const ex_init_params * param)
EXODUS_EXPORT int ex_put_init_global (int exoid, int64_t num_nodes_g, int64_t num_elems_g, int64_t num_elem_blks_g, int64_t num_node_sets_g, int64_t num_side_sets_g)
EXODUS_EXPORT int ex_put_init_info (int exoid, int num_proc, int num_proc_in_f, char * ftype)
EXODUS_EXPORT int ex_put_loadbal_param (int exoid, int64_t num_int_nodes, int64_t num_bor_nodes, int64_t num_ext_nodes, int64_t num_int_elems, int64_t num_bor_elems, int64_t num_node_cmaps, int64_t num_elem_cmaps, int processor)
EXODUS_EXPORT int ex_put_loadbal_param_cc (int exoid, void_int * num_int_nodes, void_int * num_bor_nodes, void_int * num_ext_nodes, void_int * num_int_elems, void_int * num_bor_elems, void_int * num_node_cmaps, void_int * num_elem_cmaps)
EXODUS_EXPORT int ex_put_map (int exoid, const void_int * elem_map)
EXODUS_EXPORT int ex_put_map_param (int exoid, int num_node_maps, int num_elem_maps)
EXODUS_EXPORT int ex_put_n_coord (int exoid, int64_t start_node_num, int64_t num_nodes, const void * x_coor, const void * y_coor, const void * z_coor)
EXODUS_EXPORT int ex_put_n_elem_attr (int exoid, ex_entity_id elem_blk_id, int64_t start_elem_num, int64_t num_elems, void * attrib)
EXODUS_EXPORT int ex_put_n_elem_conn (int exoid, ex_entity_id elem_blk_id, int64_t start_elem_num, int64_t num_elems, const void_int * connect)
EXODUS_EXPORT int ex_put_n_elem_num_map (int exoid, int64_t start_ent, int64_t num_ents, const void_int * map)
EXODUS_EXPORT int ex_put_n_nodal_var (int exoid, int time_step, int nodal_var_index, int64_t start_node, int64_t num_nodes, const void * nodal_var_vals)
EXODUS_EXPORT int ex_put_n_node_num_map (int exoid, int64_t start_ent, int64_t num_ents, const void_int * map)
EXODUS_EXPORT int ex_put_n_node_set (int exoid, ex_entity_id node_set_id, int64_t start_node_num, int64_t num_node, const void_int * node_set_node_list)
EXODUS_EXPORT int ex_put_n_node_set_df (int exoid, ex_entity_id node_set_id, int64_t start_num, int64_t num_df_to_get, void * node_set_df)
EXODUS_EXPORT int ex_put_n_one_attr (int exoid, ex_entity_type obj_type, ex_entity_id obj_id, int64_t start_num, int64_t num_ent, int attrib_index, const void * attrib)
EXODUS_EXPORT int ex_put_n_side_set (int exoid, ex_entity_id side_set_id, int64_t start_side_num, int64_t num_sides, const void_int * side_set_elem_list, const void_int * side_set_side_list)
EXODUS_EXPORT int ex_put_n_side_set_df (int exoid, ex_entity_id side_set_id, int64_t start_num, int64_t num_df_to_get, void * side_set_df)
EXODUS_EXPORT int ex_put_n_var (int exoid, int time_step, ex_entity_type var_type, int var_index, ex_entity_id obj_id, int64_t start_index, int64_t num_entities, const void * var_vals)
EXODUS_EXPORT int ex_put_name (int exoid, ex_entity_type obj_type, ex_entity_id entity_id, const char * name)
EXODUS_EXPORT int ex_put_names (int exoid, ex_entity_type obj_type, char * names[])
Referenced by libMesh::Nemesis_IO_Helper::write_elements(), libMesh::ExodusII_IO_Helper::write_elements(), libMesh::Nemesis_IO_Helper::write_nodesets(), libMesh::ExodusII_IO_Helper::write_nodesets(), libMesh::Nemesis_IO_Helper::write_sidesets(), and libMesh::ExodusII_IO_Helper::write_sidesets().
EXODUS_EXPORT int ex_put_nodal_var (int exoid, int time_step, int nodal_var_index, int64_t num_nodes, const void * nodal_var_vals)
Referenced by libMesh::ExodusII_IO_Helper::write_nodal_values().
EXODUS_EXPORT int ex_put_nodal_var_slab (int exoid, int time_step, int nodal_var_index, int64_t start_pos, int64_t num_vals, void * nodal_var_vals)
EXODUS_EXPORT int ex_put_node_cmap (int exoid, ex_entity_id map_id, void_int * node_ids, void_int * proc_ids, int processor)
EXODUS_EXPORT int ex_put_node_map (int exoid, ex_entity_id map_id, const void_int * node_map)
EXODUS_EXPORT int ex_put_node_num_map (int exoid, const void_int * node_map)
Referenced by libMesh::Nemesis_IO_Helper::write_nodal_coordinates(), and libMesh::ExodusII_IO_Helper::write_nodal_coordinates().
EXODUS_EXPORT int ex_put_node_set (int exoid, ex_entity_id node_set_id, const void_int * node_set_node_list)
Referenced by libMesh::Nemesis_IO_Helper::write_nodesets(), and libMesh::ExodusII_IO_Helper::write_nodesets().
EXODUS_EXPORT int ex_put_node_set_dist_fact (int exoid, ex_entity_id node_set_id, const void * node_set_dist_fact)
EXODUS_EXPORT int ex_put_node_set_param (int exoid, ex_entity_id node_set_id, int64_t num_nodes_in_set, int64_t num_dist_in_set)
Referenced by libMesh::Nemesis_IO_Helper::write_nodesets(), and libMesh::ExodusII_IO_Helper::write_nodesets().
EXODUS_EXPORT int ex_put_ns_param_global (int exoid, void_int * global_ids, void_int * global_n_cnts, void_int * global_df_cnts)
EXODUS_EXPORT int ex_put_nset_var (int exoid, int time_step, int nset_var_index, ex_entity_id nset_id, int64_t num_nodes_this_nset, const void * nset_var_vals)
EXODUS_EXPORT int ex_put_nset_var_tab (int exoid, int num_nset, int num_nset_var, int * nset_var_tab)
EXODUS_EXPORT int ex_put_num_map (int exoid, ex_entity_type map_type, ex_entity_id map_id, const void_int * map)
EXODUS_EXPORT int ex_put_one_attr (int exoid, ex_entity_type obj_type, ex_entity_id obj_id, int attrib_index, const void * attrib)
EXODUS_EXPORT int ex_put_one_elem_attr (int exoid, ex_entity_id elem_blk_id, int attrib_index, const void * attrib)
EXODUS_EXPORT int ex_put_partial_elem_map (int exoid, ex_entity_id map_id, int64_t ent_start, int64_t ent_count, const void_int * elem_map)
EXODUS_EXPORT int ex_put_partial_id_map (int exoid, ex_entity_type obj_type, int64_t start_entity_num, int64_t num_entities, const void_int * map)
EXODUS_EXPORT int ex_put_partial_num_map (int exoid, ex_entity_type map_type, ex_entity_id map_id, int64_t ent_start, int64_t ent_count, const void_int * map)
EXODUS_EXPORT int ex_put_partial_set_dist_fact (int exoid, ex_entity_type set_type, ex_entity_id set_id, int64_t offset, int64_t num_to_put, const void * set_dist_fact)
EXODUS_EXPORT int ex_put_processor_elem_maps (int exoid, void_int * elem_mapi, void_int * elem_mapb, int processor)
EXODUS_EXPORT int ex_put_processor_node_maps (int exoid, void_int * node_mapi, void_int * node_mapb, void_int * node_mape, int processor)
EXODUS_EXPORT int ex_put_prop (int exoid, ex_entity_type obj_type, ex_entity_id obj_id, const char * prop_name, ex_entity_id value)
EXODUS_EXPORT int ex_put_prop_array (int exoid, ex_entity_type obj_type, const char * prop_name, const void_int * values)
EXODUS_EXPORT int ex_put_prop_names (int exoid, ex_entity_type obj_type, int num_props, char ** prop_names)
EXODUS_EXPORT int ex_put_qa (int exoid, int num_qa_records, char * qa_record[][4])
EXODUS_EXPORT int ex_put_set (int exoid, ex_entity_type set_type, ex_entity_id set_id, const void_int * set_entry_list, const void_int * set_extra_list)
EXODUS_EXPORT int ex_put_set_dist_fact (int exoid, ex_entity_type set_type, ex_entity_id set_id, const void * set_dist_fact)
EXODUS_EXPORT int ex_put_set_param (int exoid, ex_entity_type set_type, ex_entity_id set_id, int64_t num_entries_in_set, int64_t num_dist_fact_in_set)
EXODUS_EXPORT int ex_put_sets (int exoid, size_t set_count, const struct ex_set * sets)
Referenced by libMesh::ExodusII_IO_Helper::write_sidesets().
EXODUS_EXPORT int ex_put_side_set (int exoid, ex_entity_id side_set_id, const void_int * side_set_elem_list, const void_int * side_set_side_list)
Referenced by libMesh::Nemesis_IO_Helper::write_sidesets().
EXODUS_EXPORT int ex_put_side_set_dist_fact (int exoid, ex_entity_id side_set_id, const void * side_set_dist_fact)
EXODUS_EXPORT int ex_put_side_set_param (int exoid, ex_entity_id side_set_id, int64_t num_side_in_set, int64_t num_dist_fact_in_set)
Referenced by libMesh::Nemesis_IO_Helper::write_sidesets().
EXODUS_EXPORT int ex_put_ss_param_global (int exoid, void_int * global_ids, void_int * global_el_cnts, void_int * global_df_cnts)
EXODUS_EXPORT int ex_put_sset_var (int exoid, int time_step, int sset_var_index, ex_entity_id sset_id, int64_t num_faces_this_sset, const void * sset_var_vals)
EXODUS_EXPORT int ex_put_sset_var_tab (int exoid, int num_sset, int num_sset_var, int * sset_var_tab)
EXODUS_EXPORT int ex_put_time (int exoid, int time_step, const void * time_value)
Referenced by libMesh::ExodusII_IO_Helper::write_timestep().
EXODUS_EXPORT int ex_put_truth_table (int exoid, ex_entity_type obj_type, int num_blk, int num_var, int * var_tab)
EXODUS_EXPORT int ex_put_var (int exoid, int time_step, ex_entity_type var_type, int var_index, ex_entity_id obj_id, int64_t num_entries_this_obj, const void * var_vals)
EXODUS_EXPORT int ex_put_var_name (int exoid, const char * var_type, int var_num, const char * var_name)
EXODUS_EXPORT int ex_put_var_names (int exoid, const char * var_type, int num_vars, char * var_names[])
Referenced by libMesh::ExodusII_IO_Helper::write_var_names_impl().
EXODUS_EXPORT int ex_put_var_param (int exoid, const char * var_type, int num_vars)
Referenced by libMesh::ExodusII_IO_Helper::write_var_names_impl().
EXODUS_EXPORT int ex_put_var_tab (int exoid, const char * var_type, int num_blk, int num_var, int * var_tab)
EXODUS_EXPORT int ex_put_variable_name (int exoid, ex_entity_type obj_type, int var_num, const char * var_name)
EXODUS_EXPORT int ex_put_variable_names (int exoid, ex_entity_type obj_type, int num_vars, char * var_names[])
EXODUS_EXPORT int ex_put_variable_param (int exoid, ex_entity_type obj_type, int num_vars)
EXODUS_EXPORT int ex_set_int64_status (int exoid, int mode)
EXODUS_EXPORT int ex_set_max_name_length (int exoid, int length)
Note that the max name length setting is global at this time; not specific to a particular database; however, the exoid option is passed to give flexibility in the future to implement this on a database-by-database basis.
EXODUS_EXPORT int ex_set_option (int exoid, ex_option_type option, int option_value)
EXODUS_EXPORT int ex_update (int exoid)
Referenced by libMesh::Nemesis_IO::write(), libMesh::ExodusII_IO_Helper::write_element_values(), libMesh::ExodusII_IO_Helper::write_global_values(), libMesh::ExodusII_IO_Helper::write_information_records(), libMesh::ExodusII_IO_Helper::write_nodal_values(), libMesh::ExodusII_IO_Helper::write_timestep(), and libMesh::Nemesis_IO_Helper::~Nemesis_IO_Helper().
ex_entity_type ex_var_type_to_ex_entity_type (char var_type)
Variable Documentation
int exerrval
shared error return value
int exoptval
error reporting flag (default is quiet)