libMesh: libmesh_C_isnan.h File Reference
SomeWebsiteLogo
libmesh_C_isnan.h File Reference
Functions
int libmesh_C_isnan_float (float a)
int libmesh_C_isnan_double (double a)
int libmesh_C_isnan_longdouble (long double a)
Function Documentation
int libmesh_C_isnan_double (double a)
Definition at line 31 of file libmesh_isnan.c.
Referenced by libMesh::libmesh_isnan().
 { return (a != a); }
int libmesh_C_isnan_float (float a)
Definition at line 30 of file libmesh_isnan.c.
Referenced by libMesh::libmesh_isnan().
 { return (a != a); }
int libmesh_C_isnan_longdouble (long double a)
Definition at line 32 of file libmesh_isnan.c.
Referenced by libMesh::libmesh_isnan().
 { return (a != a); }