libMesh: libMesh Namespace Reference
SomeWebsiteLogo
libMesh Namespace Reference
Namespaces
boostcopy
DenseMatrices
FiniteElements
libMeshPrivateData
MacroFunctions
MeshTools
Nemesis
Parallel
Predicates
Quality
RBDataDeserialization
RBDataSerialization
ReferenceElem
SparsityPattern
TensorTools
Threads
Trees
TriangleWrapper
Utility
Classes
class AbaqusIO
class AdaptiveTimeSolver
class AdjointDofConstraintValues
class AdjointRefinementEstimator
class AdjointResidualErrorEstimator
class AnalyticFunction
class AutoPtr
A simple smart pointer providing strict ownership semantics.
struct AutoPtrRef
class AztecLinearSolver
class BasicOStreamProxy
class BoundaryInfo
class BoundaryMesh
class BoundaryProjectSolution
class BuildProjectionList
class Cell
class CentroidPartitioner
class CheckpointIO
struct CompareTypes
struct CompareTypes< std::complex< T >, T >
struct CompareTypes< T, std::complex< T > >
struct CompareTypes< T, T >
class CompositeFEMFunction
class CompositeFunction
class CondensedEigenSystem
class ConstCouplingAccessor
class ConstCouplingRow
class ConstCouplingRowConstIterator
class ConstFEMFunction
class ConstFunction
class ConstParameterProxy
class ConstTypeTensorColumn
class ContinuationSystem
class ConvergenceFailure
class CouplingAccessor
class CouplingMatrix
class DenseMatrix
class DenseMatrixBase
class DenseSubMatrix
class DenseSubVector
class DenseVector
class DenseVectorBase
class DGFEMContext
class DiffContext
class DifferentiablePhysics
class DifferentiableQoI
class DifferentiableSystem
class DiffSolver
class DirectSolutionTransfer
class DirichletBoundaries
class DirichletBoundary
class DiscontinuityMeasure
class DivaIO
class DofConstraints
class DofConstraintValueMap
class DofMap
class DofObject
class DTKAdapter
class DTKEvaluator
class DTKSolutionTransfer
class DynamicCastFailure
class Edge
class Edge2
class Edge3
class EigenPreconditioner
class EigenSolver
class EigenSparseLinearSolver
class EigenSparseMatrix
class EigenSparseVector
class EigenSystem
class EigenTimeSolver
class Elem
class ElemAssembly
class ElemCutter
struct ElemHashUtils
class EnsightIO
class EquationSystems
class ErrorEstimator
class ErrorVector
class Euler2Solver
class EulerSolver
class ExactErrorEstimator
class ExactSolution
class ExodusII_IO
class ExodusII_IO_Helper
class ExplicitSystem
class Face
class Factory
class FactoryImp
class FastPoolAllocator
class FE
class FEAbstract
class FEClough
class FEComputeData
class FEGenericBase
class FEHermite
class FEHierarchic
class FEInterface
class FEL2Hierarchic
class FEL2Lagrange
class FELagrange
class FELagrangeVec
class FEMap
class FEMContext
class FEMFunctionBase
class FEMFunctionWrapper
class FEMonomial
class FEMPhysics
class FEMSystem
class FENedelecOne
struct FEOutputType
struct FEOutputType< LAGRANGE_VEC >
struct FEOutputType< NEDELEC_ONE >
class FEScalar
class FESubdivision
class FETransformationBase
class FEType
class FEXYZ
class FEXYZMap
class FileError
class FirstOrderUnsteadySolver
class FloatingPointException
class FrequencySystem
class FroIO
class FunctionBase
class GenericProjector
class GmshIO
class GMVIO
class GnuPlotIO
class H1FETransformation
class HCurlFETransformation
class Hex
class HilbertSFCPartitioner
class HPCoarsenTest
class HPSelector
class HPSingularity
class ImplicitSystem
class InfCell
class InfEdge2
class InfElemBuilder
class InfFE
class InfHex
class InfPrism
class InfQuad
class InfQuad4
class InfQuad6
class InverseDistanceInterpolation
class JumpErrorEstimator
class KellyErrorEstimator
class LaplaceMeshSmoother
class LaplacianErrorEstimator
class LaspackLinearSolver
class LaspackVector
class LegacyXdrIO
class libmesh_final
class LibMeshInit
class LinearImplicitSystem
class LinearPartitioner
class LinearSolutionMonitor
class LinearSolver
class LocationMap
class LogicError
class mapvector
class MatlabIO
class MEDITIO
class MemorySolutionHistory
class Mesh
struct mesh_inserter_iterator
class MeshBase
class MeshCommunication
class MeshData
class MeshDataUnvHeader
class MeshfreeInterpolation
class MeshfreeSolutionTransfer
class MeshFunction
class MeshFunctionSolutionTransfer
class MeshInput
class MeshOutput
class MeshRefinement
class MeshSerializer
class MeshSmoother
class METIS_CSR_Graph
class MetisPartitioner
class MortonSFCPartitioner
struct myhash
class NameBasedIO
class Nemesis_IO
class Nemesis_IO_Helper
class NewmarkSolver
class NewmarkSystem
class NewtonSolver
class NloptOptimizationSolver
class Node
class NodeConstraints
class NodeElem
class NonlinearImplicitSystem
class NonlinearSolver
class NoSolutionHistory
class NotImplemented
class NoxNonlinearSolver
struct null_output_iterator
class NumericVector
class OFFIO
class OldSolutionValue
class OptimizationSolver
class OptimizationSystem
class OrderWrapper
class ParallelMesh
class ParallelObject
class ParameterAccessor
class ParameterMultiAccessor
class ParameterMultiPointer
class ParameterPointer
class ParameterProxy
class Parameters
class ParameterVector
class ParmetisHelper
class ParmetisPartitioner
class ParsedFEMFunction
class ParsedFEMFunctionParameter
class ParsedFunction
class ParsedFunctionParameter
class Partitioner
class Patch
class PatchRecoveryErrorEstimator
class PerfData
class PerfLog
class PerfMon
class PeriodicBoundaries
class PeriodicBoundary
class PeriodicBoundaryBase
class PetscDiffSolver
class PetscLinearSolver
class PetscMatrix
class PetscNonlinearSolver
class PetscPreconditioner
class PetscSolverException
class Plane
class PltLoader
class Point
class PointLocatorBase
class PointLocatorList
class PointLocatorTree
class PoolAllocator
class PostscriptIO
class Preconditioner
class Prism
class Problem_Interface
class Pyramid
class QBase
class QGauss
class QoISet
class QSimpson
class QTrap
class Quad
class Quad4
class Quad8
class Quad9
class RadialBasisInterpolation
class RawAccessor
class RawAccessor< TypeNTensor< N, ScalarType > >
struct RawFieldType
struct RawFieldType< Gradient >
struct RawFieldType< Number >
struct RawFieldType< Real >
struct RawFieldType< RealGradient >
struct RawFieldType< RealTensor >
struct RawFieldType< Tensor >
struct RawFieldType< TypeNTensor< 3, Number > >
struct RawFieldType< TypeNTensor< 3, Real > >
class RBAssemblyExpansion
class RBConstruction
class RBConstructionBase
class RBEIMAssembly
class RBEIMConstruction
class RBEIMEvaluation
class RBEIMTheta
class RBEvaluation
class RBParameters
class RBParametrized
class RBParametrizedFunction
class RBSCMConstruction
class RBSCMEvaluation
class RBTemporalDiscretization
class RBTheta
class RBThetaExpansion
class ReferenceCountedObject
class ReferenceCounter
class RefinementSelector
class RemoteElem
class safe_bool
class safe_bool_base
struct ScalarTraits
struct ScalarTraits< std::complex< T > >
class SecondOrderUnsteadySolver
class SensitivityData
class SerialMesh
class SFCPartitioner
class ShellMatrix
class Side
class SideEdge
class Singleton
class SlepcEigenSolver
class SolutionHistory
class SolutionTransfer
class SolverConfiguration
class SolverException
class SparseMatrix
class SparseShellMatrix
class Sphere
class StatisticsVector
class SteadySolver
class StoredRange
class SumShellMatrix
class Surface
struct SyncNodalPositions
class System
class SystemNorm
class SystemSubset
class SystemSubsetBySubdomain
class TaoOptimizationSolver
class TecplotIO
class TensorShellMatrix
class TensorValue
class TestClass
class Tet
class TetGenIO
class TetGenMeshInterface
class TetGenWrapper
class TimeSolver
class TopologyMap
class TransientRBAssemblyExpansion
class TransientRBConstruction
class TransientRBEvaluation
class TransientRBThetaExpansion
class TransientSystem
class Tree
class TreeBase
class TreeNode
class Tri
class Tri3
class Tri6
class TriangleInterface
class TrilinosPreconditioner
class TwostepTimeSolver
class TypeNTensor
struct TypesEqual
struct TypesEqual< T, T >
class TypeTensor
class TypeTensorColumn
class TypeVector
class UCDIO
class UniformRefinementEstimator
class UnsteadySolver
class UnstructuredMesh
class UNVIO
class Variable
class VariableGroup
class VariationalMeshSmoother
class vectormap
class VectorSetAction
class VectorValue
class VTKIO
class WeightedPatchRecoveryErrorEstimator
class WendlandRBF
class WrappedFunction
class WrappedFunctor
class Xdr
class XdrHEAD
class XdrIO
class XdrMESH
class XdrMGF
class XdrMHEAD
class XdrSHEAD
class XdrSOLN
class ZeroFunction
Typedefs
typedef std::vector< Point >::const_iterator const_list_iterator
template<typename T >
using UniquePtr = std::unique_ptr< T >
typedef std::map< dof_id_type, Real, std::less< dof_id_type >, Threads::scalable_allocator< std::pair< const dof_id_type, Real > > > DofConstraintRow
typedef std::map< const Node *, Real, std::less< const Node * >, Threads::scalable_allocator< std::pair< const Node *const, Real > > > NodeConstraintRow
typedef int32_t eigen_idx_type
typedef Eigen::SparseMatrix< Number, Eigen::RowMajor, eigen_idx_type > EigenSM
typedef Eigen::Matrix< Number, Eigen::Dynamic, 1 > EigenSV
typedef LIBMESH_BEST_UNORDERED_MULTISET< Elem *, ElemHashUtils, ElemHashUtils > unordered_multiset_elem
typedef StoredRange< MeshBase::element_iterator, Elem * > ElemRange
typedef StoredRange< MeshBase::const_element_iterator, const Elem * > ConstElemRange
typedef FEGenericBase< Real > FEBase
typedef TensorValue< Number > NumberTensorValue
typedef NumberTensorValue Tensor
typedef VectorValue< Number > NumberVectorValue
typedef NumberVectorValue Gradient
typedef FEGenericBase< RealGradient > FEVectorBase
typedef VectorValue< Real > RealVectorValue
typedef TensorValue< Real > RealTensorValue
typedef RealVectorValue RealGradient
typedef RealTensorValue RealTensor
typedef TestClass subdomain_id_type
typedef int8_t boundary_id_type
typedef uint8_t dof_id_type
typedef uint8_t unique_id_type
typedef dof_id_type numeric_index_type
typedef uint8_t processor_id_type
typedef uint64_t largest_id_type
typedef std::complex< Real > Complex
typedef std::complex< Real > COMPLEX
typedef Real Number
typedef ParallelMesh DefaultMesh
typedef Real REAL
typedef StoredRange< MeshBase::node_iterator, Node * > NodeRange
typedef StoredRange< MeshBase::const_node_iterator, const Node * > ConstNodeRange
typedef BasicOStreamProxy OStreamProxy
typedef LinearImplicitSystem SteadyLinearSystem
typedef TransientSystem< LinearImplicitSystem > TransientImplicitSystem
typedef TransientSystem< LinearImplicitSystem > TransientLinearImplicitSystem
typedef TransientSystem< NonlinearImplicitSystem > TransientNonlinearImplicitSystem
typedef TransientSystem< ExplicitSystem > TransientExplicitSystem
typedef TransientSystem< System > TransientBaseSystem
Enumerations
enum LinearConvergenceReason {
CONVERGED_RTOL_NORMAL = 1, CONVERGED_ATOL_NORMAL = 9, CONVERGED_RTOL = 2, CONVERGED_ATOL = 3,
CONVERGED_ITS = 4, CONVERGED_CG_NEG_CURVE = 5, CONVERGED_CG_CONSTRAINED = 6, CONVERGED_STEP_LENGTH = 7,
CONVERGED_HAPPY_BREAKDOWN = 8, DIVERGED_NULL = -2, DIVERGED_ITS = -3, DIVERGED_DTOL = -4,
DIVERGED_BREAKDOWN = -5, DIVERGED_BREAKDOWN_BICG = -6, DIVERGED_NONSYMMETRIC = -7, DIVERGED_INDEFINITE_PC = -8,
DIVERGED_NAN = -9, DIVERGED_INDEFINITE_MAT = -10, CONVERGED_ITERATING = 0, UNKNOWN_FLAG = -128
}
enum EigenSolverType {
POWER =0, LAPACK, SUBSPACE, ARNOLDI,
LANCZOS, KRYLOVSCHUR, INVALID_EIGENSOLVER
}
enum EigenProblemType {
NHEP =0, HEP, GNHEP, GHEP,
GHIEP, INVALID_EIGENPROBLEMTYPE
}
enum PositionOfSpectrum {
LARGEST_MAGNITUDE =0, SMALLEST_MAGNITUDE, LARGEST_REAL, SMALLEST_REAL,
LARGEST_IMAGINARY, SMALLEST_IMAGINARY, INVALID_Postion_of_Spectrum
}
enum ElemQuality {
ASPECT_RATIO =0, SKEW, SHEAR, SHAPE,
MAX_ANGLE, MIN_ANGLE, CONDITION, DISTORTION,
TAPER, WARP, STRETCH, DIAGONAL,
ASPECT_RATIO_BETA, ASPECT_RATIO_GAMMA, SIZE, JACOBIAN
}
enum ElemType {
EDGE2 =0, EDGE3, EDGE4, TRI3,
TRI6, QUAD4, QUAD8, QUAD9,
TET4, TET10, HEX8, HEX20,
HEX27, PRISM6, PRISM15, PRISM18,
PYRAMID5, PYRAMID13, PYRAMID14, INFEDGE2,
INFQUAD4, INFQUAD6, INFHEX8, INFHEX16,
INFHEX18, INFPRISM6, INFPRISM12, NODEELEM,
REMOTEELEM, TRI3SUBDIVISION, INVALID_ELEM
}
enum ErrorEstimatorType {
INVALID = -1, ADJOINT_REFINEMENT = 0, ADJOINT_RESIDUAL = 1, DISCONTINUITY_MEASURE = 2,
EXACT = 3, KELLY = 4, LAPLACIAN = 5, PATCH_RECOVERY = 6,
WEIGHTED_PATCH_RECOVERY = 7, UNIFORM_REFINEMENT = 8
}
enum FEFamily {
LAGRANGE = 0, HIERARCHIC = 1, MONOMIAL = 2, L2_HIERARCHIC = 6,
L2_LAGRANGE = 7, BERNSTEIN = 3, SZABAB = 4, XYZ = 5,
INFINITE_MAP = 11, JACOBI_20_00 = 12, JACOBI_30_00 = 13, LEGENDRE = 14,
CLOUGH = 21, HERMITE = 22, SUBDIVISION = 23, SCALAR = 31,
LAGRANGE_VEC = 41, NEDELEC_ONE = 42, INVALID_FE = 99
}
enum FEContinuity { DISCONTINUOUS, C_ZERO, C_ONE, H_CURL }
enum FEFieldType { TYPE_SCALAR = 0, TYPE_VECTOR }
enum InfMapType { CARTESIAN =0, SPHERICAL, ELLIPSOIDAL, INVALID_INF_MAP }
enum IOPackage {
TECPLOT, GMV, GMSH, VTK,
DIVA, TETGEN, UCD, LIBMESH,
INVALID_IO_PACKAGE
}
enum FEMNormType {
L2 = 0, H1 = 1, H2 = 2, HCURL = 3,
HDIV = 4, L1 = 5, L_INF = 6, H1_SEMINORM = 10,
H2_SEMINORM = 11, HCURL_SEMINORM = 12, HDIV_SEMINORM = 13, W1_INF_SEMINORM = 15,
W2_INF_SEMINORM = 16, DISCRETE_L1 = 20, DISCRETE_L2 = 21, DISCRETE_L_INF = 22,
H1_X_SEMINORM = 31, H1_Y_SEMINORM = 32, H1_Z_SEMINORM = 33, INVALID_NORM = 42
}
enum Order {
CONSTANT = 0, FIRST = 1, SECOND = 2, THIRD = 3,
FOURTH = 4, FIFTH = 5, SIXTH = 6, SEVENTH = 7,
EIGHTH = 8, NINTH = 9, TENTH = 10, ELEVENTH = 11,
TWELFTH = 12, THIRTEENTH = 13, FOURTEENTH = 14, FIFTEENTH = 15,
SIXTEENTH = 16, SEVENTEENTH = 17, EIGHTTEENTH = 18, NINTEENTH = 19,
NINETEENTH = 19, TWENTIETH = 20, TWENTYFIRST = 21, TWENTYSECOND = 22,
TWENTYTHIRD = 23, TWENTYFOURTH = 24, TWENTYFIFTH = 25, TWENTYSIXTH = 26,
TWENTYSEVENTH = 27, TWENTYEIGHTH = 28, TWENTYNINTH = 29, THIRTIETH = 30,
THIRTYFIRST = 31, THIRTYSECOND = 32, THIRTYTHIRD = 33, THIRTYFOURTH = 34,
THIRTYFIFTH = 35, THIRTYSIXTH = 36, THIRTYSEVENTH = 37, THIRTYEIGHTH = 38,
THIRTYNINTH = 39, FORTIETH = 40, FORTYFIRST = 41, FORTYSECOND = 42,
FORTYTHIRD = 43, INVALID_ORDER
}
enum ParallelType {
AUTOMATIC =0, SERIAL, PARALLEL, GHOSTED,
INVALID_PARALLELIZATION
}
enum PointLocatorType {
TREE = 0, TREE_ELEMENTS, TREE_LOCAL_ELEMENTS, LIST,
INVALID_LOCATOR
}
enum PreconditionerType {
IDENTITY_PRECOND =0, JACOBI_PRECOND, BLOCK_JACOBI_PRECOND, SOR_PRECOND,
SSOR_PRECOND, EISENSTAT_PRECOND, ASM_PRECOND, CHOLESKY_PRECOND,
ICC_PRECOND, ILU_PRECOND, LU_PRECOND, USER_PRECOND,
SHELL_PRECOND, AMG_PRECOND, INVALID_PRECONDITIONER
}
enum QuadratureType {
QGAUSS = 0, QJACOBI_1_0 = 1, QJACOBI_2_0 = 2, QSIMPSON = 3,
QTRAP = 4, QGRID = 5, QGRUNDMANN_MOLLER = 6, QMONOMIAL = 7,
QCONICAL = 8, QGAUSS_LOBATTO = 9, QCLOUGH = 21, QCOMPOSITE = 31,
INVALID_Q_RULE = 127
}
enum SolverPackage { PETSC_SOLVERS =0, SLEPC_SOLVERS, NLOPT_SOLVERS }
enum SolverType {
CG =0, CGN, CGS, CR,
QMR, TCQMR, TFQMR, BICG,
BICGSTAB, MINRES, GMRES, LSQR,
JACOBI, SOR_FORWARD, SOR_BACKWARD, SSOR,
RICHARDSON, CHEBYSHEV, SPARSELU, INVALID_SOLVER
}
enum SubsetSolveMode { SUBSET_ZERO = 0, SUBSET_COPY_RHS, SUBSET_DONT_TOUCH }
enum XdrMODE {
UNKNOWN = -1, ENCODE =0, DECODE, WRITE,
READ
}
Functions
bool warned_about_auto_ptr (false)
const Number imaginary (0., 1.)
bool initialized ()
bool closed ()
void libmesh_terminate_handler ()
if (libMesh::libMeshPrivateData::_n_threads!=1)
omp_set_num_threads (libMesh::libMeshPrivateData::_n_threads)
task_scheduler reset (new Threads::task_scheduler_init(libMesh::n_threads()))
libmesh_assert (remote_elem)
if (!libMesh::on_command_line("--disable-mpi"))
libmesh_assert_greater (libMeshPrivateData::_n_processors, 0)
libmesh_parallel_only (this->comm())
if (!libMesh::on_command_line("--disable-petsc")#if defined(LIBMESH_HAVE_MPI)&&!libMesh::on_command_line("--disable-mpi")#endif)
command_line parse_command_line (argc, argv)
if(!libMesh::on_command_line("--sync-with-stdio")) std if (libMesh::on_command_line("--separate-libmeshout"))
if (libMesh::on_command_line("--redirect-stdout"))
if (libMesh::global_processor_id()!=0)
void enableFPE (bool on)
void enableSEGV (bool on)
bool on_command_line (const std::string &arg)
template<typename T >
T command_line_value (const std::string &name, T value)
template<typename T >
T command_line_value (const std::vector< std::string > &name, T value)
template<typename T >
T command_line_next (const std::string &name, T value)
template<typename T >
void command_line_vector (const std::string &name, std::vector< T > &vec)
SolverPackage default_solver_package ()
template int command_line_value< int > (const std::string &, int)
template float command_line_value< float > (const std::string &, float)
template double command_line_value< double > (const std::string &, double)
template long double command_line_value< long double > (const std::string &, long double)
template std::string command_line_value< std::string > (const std::string &, std::string)
template int command_line_value< int > (const std::vector< std::string > &, int)
template float command_line_value< float > (const std::vector< std::string > &, float)
template double command_line_value< double > (const std::vector< std::string > &, double)
template long double command_line_value< long double > (const std::vector< std::string > &, long double)
template std::string command_line_value< std::string > (const std::vector< std::string > &, std::string)
template int command_line_next< int > (const std::string &, int)
template float command_line_next< float > (const std::string &, float)
template double command_line_next< double > (const std::string &, double)
template long double command_line_next< long double > (const std::string &, long double)
template std::string command_line_next< std::string > (const std::string &, std::string)
template void command_line_vector< int > (const std::string &, std::vector< int > &)
template void command_line_vector< float > (const std::string &, std::vector< float > &)
template void command_line_vector< double > (const std::string &, std::vector< double > &)
template void command_line_vector< long double > (const std::string &, std::vector< long double > &)
void print_trace (std::ostream &out_stream)
void write_traceout ()
std::string demangle (const char *name)
error_per_cell resize (mesh.max_elem_id())
if (solution_vector &&solution_vector!=system.solution.get())
for (unsigned int var=0;var< n_vars;var++)
this reduce_error (error_per_cell, system.comm())
START_LOG ("std::sqrt()","ExactErrorEstimator")
STOP_LOG ("std::sqrt()","ExactErrorEstimator")
INSTANTIATE_FE (0)
INSTANTIATE_FE (1)
INSTANTIATE_FE (2)
INSTANTIATE_FE (3)
std::ostream & operator<< (std::ostream &os, const FEAbstract &fe)
REINIT_ERROR (REINIT_ERROR(0, REINIT_ERROR(CLOUGH, reinit)
INSTANTIATE_ALL_MAPS (0)
INSTANTIATE_ALL_MAPS (1)
INSTANTIATE_ALL_MAPS (2)
INSTANTIATE_ALL_MAPS (3)
INSTANTIATE_INF_FE_MBRF (1, CARTESIAN, Elem *, Base::build_elem(const Elem *))
INSTANTIATE_INF_FE_MBRF (2, CARTESIAN, Elem *, Base::build_elem(const Elem *))
INSTANTIATE_INF_FE_MBRF (3, CARTESIAN, Elem *, Base::build_elem(const Elem *))
INSTANTIATE_INF_FE_MBRF (1, CARTESIAN, ElemType, Base::get_elem_type(const ElemType type))
INSTANTIATE_INF_FE_MBRF (2, CARTESIAN, ElemType, Base::get_elem_type(const ElemType type))
INSTANTIATE_INF_FE_MBRF (3, CARTESIAN, ElemType, Base::get_elem_type(const ElemType type))
INSTANTIATE_INF_FE_MBRF (1, CARTESIAN, unsigned int, Base::n_base_mapping_sf(const ElemType, const Order))
INSTANTIATE_INF_FE_MBRF (2, CARTESIAN, unsigned int, Base::n_base_mapping_sf(const ElemType, const Order))
INSTANTIATE_INF_FE_MBRF (3, CARTESIAN, unsigned int, Base::n_base_mapping_sf(const ElemType, const Order))
INSTANTIATE_INF_FE_MBRF (1, CARTESIAN, unsigned int, Radial::n_dofs_at_node(const Order, const unsigned int))
INSTANTIATE_INF_FE_MBRF (2, CARTESIAN, unsigned int, Radial::n_dofs_at_node(const Order, const unsigned int))
INSTANTIATE_INF_FE_MBRF (3, CARTESIAN, unsigned int, Radial::n_dofs_at_node(const Order, const unsigned int))
INSTANTIATE_INF_FE_MBRF (1, CARTESIAN, void, reinit(const Elem *, const unsigned int, const Real, const std::vector< Point > *const, const std::vector< Real > *const))
INSTANTIATE_INF_FE_MBRF (2, CARTESIAN, void, reinit(const Elem *, const unsigned int, const Real, const std::vector< Point > *const, const std::vector< Real > *const))
INSTANTIATE_INF_FE_MBRF (3, CARTESIAN, void, reinit(const Elem *, const unsigned int, const Real, const std::vector< Point > *const, const std::vector< Real > *const))
INSTANTIATE_INF_FE_MBRF (1, CARTESIAN, void, edge_reinit(const Elem *, const unsigned int, const Real, const std::vector< Point > *const, const std::vector< Real > *const))
INSTANTIATE_INF_FE_MBRF (2, CARTESIAN, void, edge_reinit(const Elem *, const unsigned int, const Real, const std::vector< Point > *const, const std::vector< Real > *const))
INSTANTIATE_INF_FE_MBRF (3, CARTESIAN, void, edge_reinit(const Elem *, const unsigned int, const Real, const std::vector< Point > *const, const std::vector< Real > *const))
INSTANTIATE_INF_FE_MBRF (1, CARTESIAN, void, init_face_shape_functions(const std::vector< Point > &, const Elem *))
INSTANTIATE_INF_FE_MBRF (2, CARTESIAN, void, init_face_shape_functions(const std::vector< Point > &, const Elem *))
INSTANTIATE_INF_FE_MBRF (3, CARTESIAN, void, init_face_shape_functions(const std::vector< Point > &, const Elem *))
INSTANTIATE_INF_FE_MBRF (1, CARTESIAN, Point, inverse_map(const Elem *, const Point &, const Real, const bool, const bool))
INSTANTIATE_INF_FE_MBRF (2, CARTESIAN, Point, inverse_map(const Elem *, const Point &, const Real, const bool, const bool))
INSTANTIATE_INF_FE_MBRF (3, CARTESIAN, Point, inverse_map(const Elem *, const Point &, const Real, const bool, const bool))
INSTANTIATE_INF_FE_MBRF (1, CARTESIAN, void, inverse_map(const Elem *, const std::vector< Point > &, std::vector< Point > &, const Real, const bool))
INSTANTIATE_INF_FE_MBRF (2, CARTESIAN, void, inverse_map(const Elem *, const std::vector< Point > &, std::vector< Point > &, const Real, const bool))
INSTANTIATE_INF_FE_MBRF (3, CARTESIAN, void, inverse_map(const Elem *, const std::vector< Point > &, std::vector< Point > &, const Real, const bool))
INSTANTIATE_INF_FE_MBRF (1, CARTESIAN, unsigned int, n_dofs(const FEType &, const ElemType))
INSTANTIATE_INF_FE_MBRF (2, CARTESIAN, unsigned int, n_dofs(const FEType &, const ElemType))
INSTANTIATE_INF_FE_MBRF (3, CARTESIAN, unsigned int, n_dofs(const FEType &, const ElemType))
INSTANTIATE_INF_FE_MBRF (1, CARTESIAN, unsigned int, n_dofs_per_elem(const FEType &, const ElemType))
INSTANTIATE_INF_FE_MBRF (2, CARTESIAN, unsigned int, n_dofs_per_elem(const FEType &, const ElemType))
INSTANTIATE_INF_FE_MBRF (3, CARTESIAN, unsigned int, n_dofs_per_elem(const FEType &, const ElemType))
INSTANTIATE_INF_FE_MBRF (1, CARTESIAN, unsigned int, n_dofs_at_node(const FEType &, const ElemType, const unsigned int))
INSTANTIATE_INF_FE_MBRF (2, CARTESIAN, unsigned int, n_dofs_at_node(const FEType &, const ElemType, const unsigned int))
INSTANTIATE_INF_FE_MBRF (3, CARTESIAN, unsigned int, n_dofs_at_node(const FEType &, const ElemType, const unsigned int))
INSTANTIATE_INF_FE_MBRF (1, CARTESIAN, void, compute_shape_indices(const FEType &, const ElemType, const unsigned int, unsigned int &, unsigned int &))
INSTANTIATE_INF_FE_MBRF (2, CARTESIAN, void, compute_shape_indices(const FEType &, const ElemType, const unsigned int, unsigned int &, unsigned int &))
INSTANTIATE_INF_FE_MBRF (3, CARTESIAN, void, compute_shape_indices(const FEType &, const ElemType, const unsigned int, unsigned int &, unsigned int &))
INSTANTIATE_INF_FE_MBRF (1, CARTESIAN, void, compute_node_indices(const ElemType, const unsigned int, unsigned int &, unsigned int &))
INSTANTIATE_INF_FE_MBRF (2, CARTESIAN, void, compute_node_indices(const ElemType, const unsigned int, unsigned int &, unsigned int &))
INSTANTIATE_INF_FE_MBRF (3, CARTESIAN, void, compute_node_indices(const ElemType, const unsigned int, unsigned int &, unsigned int &))
INSTANTIATE_INF_FE_MBRF (1, CARTESIAN, Real, shape(const FEType &, const Elem *, const unsigned int, const Point &p))
INSTANTIATE_INF_FE_MBRF (2, CARTESIAN, Real, shape(const FEType &, const Elem *, const unsigned int, const Point &p))
INSTANTIATE_INF_FE_MBRF (3, CARTESIAN, Real, shape(const FEType &, const Elem *, const unsigned int, const Point &p))
INSTANTIATE_INF_FE_MBRF (1, CARTESIAN, Real, shape(const FEType &, const ElemType, const unsigned int, const Point &))
INSTANTIATE_INF_FE_MBRF (2, CARTESIAN, Real, shape(const FEType &, const ElemType, const unsigned int, const Point &))
INSTANTIATE_INF_FE_MBRF (3, CARTESIAN, Real, shape(const FEType &, const ElemType, const unsigned int, const Point &))
INSTANTIATE_INF_FE_MBRF (1, CARTESIAN, void, compute_data(const FEType &, const Elem *, FEComputeData &))
INSTANTIATE_INF_FE_MBRF (2, CARTESIAN, void, compute_data(const FEType &, const Elem *, FEComputeData &))
INSTANTIATE_INF_FE_MBRF (3, CARTESIAN, void, compute_data(const FEType &, const Elem *, FEComputeData &))
INSTANTIATE_INF_FE_MBRF (1, CARTESIAN, void, nodal_soln(const FEType &, const Elem *, const std::vector< Number > &, std::vector< Number > &))
INSTANTIATE_INF_FE_MBRF (2, CARTESIAN, void, nodal_soln(const FEType &, const Elem *, const std::vector< Number > &, std::vector< Number > &))
INSTANTIATE_INF_FE_MBRF (3, CARTESIAN, void, nodal_soln(const FEType &, const Elem *, const std::vector< Number > &, std::vector< Number > &))
std::ostream & operator<< (std::ostream &os, const MeshBase &m)
template void MeshCommunication::find_global_indices< MeshBase::const_node_iterator > (const Parallel::Communicator &, const MeshTools::BoundingBox &, const MeshBase::const_node_iterator &, const MeshBase::const_node_iterator &, std::vector< dof_id_type > &) const
template void MeshCommunication::find_global_indices< MeshBase::const_element_iterator > (const Parallel::Communicator &, const MeshTools::BoundingBox &, const MeshBase::const_element_iterator &, const MeshBase::const_element_iterator &, std::vector< dof_id_type > &) const
template void MeshCommunication::find_global_indices< MeshBase::node_iterator > (const Parallel::Communicator &, const MeshTools::BoundingBox &, const MeshBase::node_iterator &, const MeshBase::node_iterator &, std::vector< dof_id_type > &) const
template void MeshCommunication::find_global_indices< MeshBase::element_iterator > (const Parallel::Communicator &, const MeshTools::BoundingBox &, const MeshBase::element_iterator &, const MeshBase::element_iterator &, std::vector< dof_id_type > &) const
std::ostream & operator<< (std::ostream &os, const MeshData &m)
bool is_between (Real min, Real check, Real max)
LIBMESH_VMA_INSTANTIATE (Real, int, Real)
LIBMESH_VMA_INSTANTIATE (Real, float, Real)
LIBMESH_VMA_INSTANTIATE (Real, double, Real)
LIBMESH_VMA_INSTANTIATE (Real, int, Complex)
LIBMESH_VMA_INSTANTIATE (Complex, int, Complex)
LIBMESH_VMA_INSTANTIATE (Complex, int, Real)
LIBMESH_VMA_INSTANTIATE (Real, float, Complex)
LIBMESH_VMA_INSTANTIATE (Complex, float, Complex)
LIBMESH_VMA_INSTANTIATE (Complex, float, Real)
LIBMESH_VMA_INSTANTIATE (Real, std::complex< float >, Complex)
LIBMESH_VMA_INSTANTIATE (Complex, std::complex< float >, Complex)
LIBMESH_VMA_INSTANTIATE (Complex, std::complex< float >, Real)
LIBMESH_VMA_INSTANTIATE (Real, double, Complex)
LIBMESH_VMA_INSTANTIATE (Complex, double, Complex)
LIBMESH_VMA_INSTANTIATE (Complex, double, Real)
LIBMESH_VMA_INSTANTIATE (Real, std::complex< double >, Complex)
LIBMESH_VMA_INSTANTIATE (Complex, std::complex< double >, Complex)
LIBMESH_VMA_INSTANTIATE (Complex, std::complex< double >, Real)
PetscObjectGetComm ((PetscObject) pc,&comm)
CHKERRABORT (comm, ierr)
std::ostream & operator<< (std::ostream &os, const QBase &q)
template<typename T >
T SIGN (T a, T b)
double __libmesh_nlopt_objective (unsigned n, const double *x, double *gradient, void *data)
void __libmesh_nlopt_equality_constraints (unsigned m, double *result, unsigned n, const double *x, double *gradient, void *data)
void __libmesh_nlopt_inequality_constraints (unsigned m, double *result, unsigned n, const double *x, double *gradient, void *data)
void petsc_auto_fieldsplit (PC my_pc, const System &sys)
PetscErrorCode __libmesh_petsc_diff_solver_monitor (SNES snes, PetscInt its, PetscReal fnorm, void *ctx)
PetscErrorCode __libmesh_petsc_diff_solver_residual (SNES, Vec x, Vec r, void *ctx)
PetscErrorCode __libmesh_petsc_diff_solver_jacobian (SNES, Vec x, Mat *libmesh_dbg_var(j), Mat *pc, MatStructure *msflag, void *ctx) PetscErrorCode __libmesh_petsc_diff_solver_jacobian(SNES
PetscErrorCode Vec Mat libmesh_dbg_var (j)
PetscErrorCode Vec Mat Mat void *ctx libmesh_assert (x)
libmesh_assert (j)
libmesh_assert (ctx)
PetscVector< Number > X_input (x, sys.comm())
PetscMatrix< Number > J_input * pc ()
PetscMatrix< Number > J_input (pc, sys.comm())
X_input swap (X_system)
J_input swap (J_system)
sys get_dof_map ()
DiffSolver::SolveResult convert_solve_result (SNESConvergedReason r)
PetscErrorCode __libmesh_petsc_preconditioner_setup (void *ctx)
PetscErrorCode __libmesh_petsc_preconditioner_apply (void *ctx, Vec x, Vec y)
PetscErrorCode __libmesh_petsc_preconditioner_setup (PC pc)
PetscErrorCode __libmesh_petsc_preconditioner_apply (PC pc, Vec x, Vec y)
PetscErrorCode __libmesh_petsc_snes_monitor (SNES, PetscInt its, PetscReal fnorm, void *)
PetscErrorCode __libmesh_petsc_snes_residual (SNES snes, Vec x, Vec r, void *ctx)
PetscErrorCode __libmesh_petsc_snes_jacobian (#if PETSC_RELEASE_LESS_THAN(3, 5, 0) SNES snes, Vec x, Mat *jac, Mat *pc, MatStructure *msflag, void *ctx#else SNES snes, Vec x, Mat jac, Mat pc, void *ctx#endif)
PetscErrorCode __libmesh_petsc_snes_postcheck (#if PETSC_VERSION_LESS_THAN(3, 3, 0) SNES, Vec x, Vec y, Vec w, void *context, PetscBool *changed_y, PetscBool *changed_w#else SNESLineSearch, Vec x, Vec y, Vec w, PetscBool *changed_y, PetscBool *changed_w, void *context#endif)
PetscErrorCode __libmesh_tao_objective (Tao, Vec x, PetscReal *objective, void *ctx)
PetscErrorCode __libmesh_tao_gradient (Tao, Vec x, Vec g, void *ctx)
PetscErrorCode __libmesh_tao_hessian (Tao, Vec x, Mat h, Mat pc, void *ctx)
PetscErrorCode __libmesh_tao_equality_constraints (Tao, Vec x, Vec ce, void *ctx)
PetscErrorCode __libmesh_tao_equality_constraints_jacobian (Tao, Vec x, Mat J, Mat Jpre, void *ctx)
PetscErrorCode __libmesh_tao_inequality_constraints (Tao, Vec x, Vec cineq, void *ctx)
PetscErrorCode __libmesh_tao_inequality_constraints_jacobian (Tao, Vec x, Mat J, Mat Jpre, void *ctx)
std::ostream & operator<< (std::ostream &os, const EquationSystems &es)
template void Xdr::data< std::complex< float > > (std::complex< float > &, const char *)
template void Xdr::data< std::complex< double > > (std::complex< double > &, const char *)
template void Xdr::data< std::complex< long double > > (std::complex< long double > &, const char *)
template void Xdr::data< std::string > (std::string &, const char *)
template void Xdr::data< std::vector< int > > (std::vector< int > &, const char *)
template void Xdr::data< std::vector< unsigned int > > (std::vector< unsigned int > &, const char *)
template void Xdr::data< std::vector< short int > > (std::vector< short int > &, const char *)
template void Xdr::data< std::vector< unsigned short int > > (std::vector< unsigned short int > &, const char *)
template void Xdr::data< std::vector< long int > > (std::vector< long int > &, const char *)
template void Xdr::data< std::vector< unsigned long int > > (std::vector< unsigned long int > &, const char *)
template void Xdr::data< std::vector< unsigned long long > > (std::vector< unsigned long long > &, const char *)
template void Xdr::data< std::vector< char > > (std::vector< char > &, const char *)
template void Xdr::data< std::vector< signed char > > (std::vector< signed char > &, const char *)
template void Xdr::data< std::vector< unsigned char > > (std::vector< unsigned char > &, const char *)
template void Xdr::data< std::vector< float > > (std::vector< float > &, const char *)
template void Xdr::data< std::vector< double > > (std::vector< double > &, const char *)
template void Xdr::data< std::vector< long double > > (std::vector< long double > &, const char *)
template void Xdr::data< std::vector< std::complex< float > > > (std::vector< std::complex< float > > &, const char *)
template void Xdr::data< std::vector< std::complex< double > > > (std::vector< std::complex< double > > &, const char *)
template void Xdr::data< std::vector< std::complex< long double > > > (std::vector< std::complex< long double > > &, const char *)
template void Xdr::data< std::vector< std::string > > (std::vector< std::string > &, const char *)
ScalarTraits_true (char)
ScalarTraits_true (short)
ScalarTraits_true (int)
ScalarTraits_true (long)
ScalarTraits_true (unsigned char)
ScalarTraits_true (float)
ScalarTraits_true (double)
SUPERTYPE (unsigned char, short)
SUPERTYPE (unsigned char, int)
SUPERTYPE (unsigned char, float)
SUPERTYPE (unsigned char, double)
SUPERTYPE (unsigned char, long double)
SUPERTYPE (char, short)
SUPERTYPE (char, int)
SUPERTYPE (char, float)
SUPERTYPE (char, double)
SUPERTYPE (char, long double)
SUPERTYPE (short, int)
SUPERTYPE (short, float)
SUPERTYPE (short, double)
SUPERTYPE (short, long double)
SUPERTYPE (int, float)
SUPERTYPE (int, double)
SUPERTYPE (int, long double)
SUPERTYPE (float, double)
SUPERTYPE (float, long double)
SUPERTYPE (double, long double)
std::ostream & operator<< (std::ostream &os, const Elem &e)
if (_elemlinks)
if (this->parent()!=libmesh_nullptr)
if (this->parent()) this-> set_p_level(this->parent() ->p_level())
bool operator== (const OrderWrapper &lhs, const OrderWrapper &rhs)
bool operator!= (const OrderWrapper &lhs, const OrderWrapper &rhs)
bool operator< (const OrderWrapper &lhs, const OrderWrapper &rhs)
bool operator> (const OrderWrapper &lhs, const OrderWrapper &rhs)
bool operator<= (const OrderWrapper &lhs, const OrderWrapper &rhs)
bool operator>= (const OrderWrapper &lhs, const OrderWrapper &rhs)
OrderWrapperOperators (int) OrderWrapperOperators(unsigned int) OrderWrapperOperators(std
bool operator== (const OrderWrapper &lhs, int rhs)
bool operator== (Order lhs, const OrderWrapper &rhs)
bool operator== (const OrderWrapper &lhs, Order rhs)
bool operator!= (int lhs, const OrderWrapper &rhs)
bool operator!= (const OrderWrapper &lhs, int rhs)
bool operator!= (Order lhs, const OrderWrapper &rhs)
bool operator!= (const OrderWrapper &lhs, Order rhs)
bool operator< (int lhs, const OrderWrapper &rhs)
bool operator< (const OrderWrapper &lhs, int rhs)
bool operator< (Order lhs, const OrderWrapper &rhs)
bool operator< (const OrderWrapper &lhs, Order rhs)
bool operator> (int lhs, const OrderWrapper &rhs)
bool operator> (const OrderWrapper &lhs, int rhs)
bool operator> (Order lhs, const OrderWrapper &rhs)
bool operator> (const OrderWrapper &lhs, Order rhs)
bool operator<= (int lhs, const OrderWrapper &rhs)
bool operator<= (const OrderWrapper &lhs, int rhs)
bool operator<= (Order lhs, const OrderWrapper &rhs)
bool operator<= (const OrderWrapper &lhs, Order rhs)
bool operator>= (int lhs, const OrderWrapper &rhs)
bool operator>= (const OrderWrapper &lhs, int rhs)
bool operator>= (Order lhs, const OrderWrapper &rhs)
bool operator>= (const OrderWrapper &lhs, Order rhs)
std::ostream & operator<< (std::ostream &os, const OrderWrapper &order)
INSTANTIATE_INF_FE (1, CARTESIAN)
INSTANTIATE_INF_FE (2, CARTESIAN)
INSTANTIATE_INF_FE (3, CARTESIAN)
processor_id_type n_processors ()
processor_id_type processor_id ()
processor_id_type global_n_processors ()
processor_id_type global_processor_id ()
unsigned int n_threads ()
template<typename T >
T libmesh_real (T a)
template<typename T >
T libmesh_conj (T a)
template<typename T >
T libmesh_real (std::complex< T > a)
template<typename T >
std::complex< T > libmesh_conj (std::complex< T > a)
bool libmesh_isnan (float a)
bool libmesh_isnan (double a)
bool libmesh_isnan (long double a)
template<typename T >
bool libmesh_isnan (std::complex< T > a)
template<class T >
void libmesh_ignore (const T &)
template<typename Tnew , typename Told >
Tnew cast_ref (Told &oldvar)
template<typename Tnew , typename Told >
Tnew libmesh_cast_ref (Told &oldvar)
template<typename Tnew , typename Told >
Tnew cast_ptr (Told *oldvar)
template<typename Tnew , typename Told >
Tnew libmesh_cast_ptr (Told *oldvar)
template<typename Tnew , typename Told >
Tnew cast_int (Told oldvar)
template<typename Tnew , typename Told >
Tnew libmesh_cast_int (Told oldvar)
void libmesh_version_stdout ()
int get_libmesh_version ()
std::string get_io_compatibility_version ()
std::ostream & operator<< (std::ostream &os, const Node &n)
template<typename P >
void print_helper (std::ostream &os, const P *param)
template<typename P >
void print_helper (std::ostream &os, const std::vector< P > *param)
template<typename P >
void print_helper (std::ostream &os, const std::vector< std::vector< P > > *param)
std::ostream & operator<< (std::ostream &os, const Parameters &p)
PetscErrorCode __libmesh_petsc_snes_jacobian (SNES, Vec x, Mat *jac, Mat *pc, MatStructure *msflag, void *ctx)
PetscErrorCode __libmesh_petsc_snes_jacobian (SNES, Vec x, Mat jac, Mat pc, void *ctx)
PetscInt * numeric_petsc_cast (const numeric_index_type *p)
template<typename T >
bool operator== (const safe_bool< T > &lhs, bool b)
template<typename T >
bool operator== (bool b, const safe_bool< T > &rhs)
template<typename T , typename U >
bool operator== (const safe_bool< T > &lhs, const safe_bool< U > &)
template<typename T , typename U >
bool operator!= (const safe_bool< T > &lhs, const safe_bool< U > &)
template<typename T >
std::ostream & operator<< (std::ostream &os, const SparseMatrix< T > &m)
template<typename T , typename Scalar >
boostcopy::enable_if_c< ScalarTraits< Scalar >::value, TypeTensor< typename CompareTypes< T, Scalar >::supertype > >::type operator* (const Scalar factor, const TypeTensor< T > &t)
template<typename T , typename Scalar >
boostcopy::enable_if_c< ScalarTraits< Scalar >::value, TypeVector< typename CompareTypes< T, Scalar >::supertype > >::type operator* (const Scalar factor, const TypeVector< T > &v)
template<typename T >
T triple_product (const TypeVector< T > &a, const TypeVector< T > &b, const TypeVector< T > &c)
Variables
DIE A HORRIBLE DEATH HERE typedef LIBMESH_DEFAULT_SCALAR_TYPE Real
DIE A HORRIBLE DEATH HERE typedef float ErrorVectorReal
MPI_Comm COMM_WORLD = MPI_COMM_NULL
MPI_Comm GLOBAL_COMM_WORLD = MPI_COMM_NULL
Parallel::FakeCommunicator CommWorld
OStreamProxy out (std::cout)
OStreamProxy err (std::cerr)
PerfLog perflog ("libMesh",#ifdef LIBMESH_ENABLE_PERFORMANCE_LOGGING true#else false#endif)
MPI_Errhandler libmesh_errhandler
TRILINOS_SOLVERS
EIGEN_SOLVERS
LASPACK_SOLVERS
INVALID_SOLVER_PACKAGE
std::terminate_handler old_terminate_handler
LibMeshInit::LibMeshInit(int argc, const char *const *argv) LibMeshInit command_lin reset)(new GetPot(argc, argv))
n_threads [0] = "--n_threads"
void ExactErrorEstimator::estimate_error(const System &system, ErrorVector &error_per_cell, const NumericVector< Number > *solution_vector, bool estimate_parent_error) void ExactErrorEstimator const unsigned in dim) = mesh.mesh_dimension()
const unsigned int n_vars = system.n_vars()
const DofMap & dof_map = system.get_dof_map()
INSTANTIATE_SUBDIVISION_FE
INSTANTIATE_SUBDIVISION_MAPS
Threads::spin_mutex parent_indices_mutex
Threads::spin_mutex parent_bracketing_nodes_mutex
const RemoteElem * remote_elem
ParallelMesh::ParallelMesh(const Parallel::Communicator &comm_in, unsigned char d) _partitioner = UniquePtr<Partitioner>(new ParmetisPartitioner())
template<typename T >
void PetscPreconditioner< T >::set_petsc_subpreconditioner_type(PCType type, PC &pc) void PetscPreconditioner< T > Parallel::communicator comm
Parallel::Communicator communicator (comm)
ierr = PCSetUp(pc)
KSP * subksps
PetscInt n_local
const unsigned int MIN_ELEM_PER_PROC = 4
PetscErrorCode Vec x
PetscErrorCode Vec Mat Mat pc
PetscDiffSolver & solver
ImplicitSystem & sys = solver.system()
if(solver.verbose) libMesh PetscVector< Number > & X_system
PetscMatrix< Number > & J_system
const unsigned char triangular_number_row []
const unsigned char triangular_number_column []
const unsigned char square_number_column []
const unsigned char square_number_row []
const unsigned char cube_number_column []
const unsigned char cube_number_row []
const unsigned char cube_number_page []
Elem::Elem(const unsigned int nn, const unsigned int ns, Elem *p, Elem **elemlinkdata, Node **nodelinkdata if)(_nodes)
const Number imaginary
const Real pi
const Number zero = 0.
const unsigned int invalid_uint = static_cast<unsigned int>(-1)
static const Real TOLERANCE = 1.e-8
bool warned_about_auto_ptr
Detailed Description
Sanity check, without prior inclusion of libmesh_config.h.
This file is no typical header file. It is only to be included at the end of an implementation file, so that the proper variations of the InfFE class are instantiated.
The libMesh namespace provides an interface to certain functionality in the library. It provides a uniform init() method that initializes any other dependent libraries (e.g. MPI or PETSC), and a close() method for closing those libraries. It also provides a centralized place for performance logging and other functionality.
SLEPc include files.
Trilinos include files.
Typedef Documentation
typedef int16_t libMesh::boundary_id_type
Definition at line 51 of file id_types.h.
typedef std::complex<Real> libMesh::Complex
Definition at line 155 of file libmesh_common.h.
typedef std::complex<Real> libMesh::COMPLEX
Definition at line 156 of file libmesh_common.h.
typedef std::vector<Point>::const_iterator libMesh::const_list_iterator
Definition at line 33 of file point_locator_list.C.
typedef StoredRange<MeshBase::const_element_iterator, const Elem *> libMesh::ConstElemRange
Definition at line 34 of file elem_range.h.
typedef StoredRange<MeshBase::const_node_iterator, const Node *> libMesh::ConstNodeRange
Definition at line 36 of file node_range.h.
typedef SerialMesh libMesh::DefaultMesh
Definition at line 27 of file mesh.h.
typedef uint32_t libMesh::dof_id_type
Definition at line 64 of file id_types.h.
typedef std::map<dof_id_type, Real, std::less<dof_id_type>, Threads::scalable_allocator<std::pair<const dof_id_type, Real> > > libMesh::DofConstraintRow
A row of the Dof constraint matrix.
Definition at line 86 of file dof_map.h.
typedef int32_t libMesh::eigen_idx_type
Definition at line 64 of file eigen_core_support.h.
typedef Eigen::SparseMatrix<Number, Eigen::RowMajor, eigen_idx_type> libMesh::EigenSM
Definition at line 76 of file eigen_core_support.h.
typedef Eigen::Matrix<Number, Eigen::Dynamic, 1> libMesh::EigenSV
Definition at line 77 of file eigen_core_support.h.
typedef StoredRange<MeshBase::element_iterator, Elem *> libMesh::ElemRange
Definition at line 31 of file elem_range.h.
typedef FEGenericBase< Real > libMesh::FEBase
Definition at line 37 of file exact_error_estimator.h.
typedef FEGenericBase<RealGradient> libMesh::FEVectorBase
Definition at line 676 of file fe_base.h.
typedef NumberVectorValue libMesh::Gradient
Definition at line 52 of file exact_error_estimator.h.
typedef uint8_t libMesh::largest_id_type
Definition at line 138 of file id_types.h.
typedef std::map<const Node *, Real, std::less<const Node *>, Threads::scalable_allocator<std::pair<const Node * const, Real> > > libMesh::NodeConstraintRow
A row of the Node constraint mapping. Currently this just stores the topology of the constrained Nodes, but for forward compatibility we also include coefficients, so we could add Lagrange-positioned-node constraints later.
Definition at line 134 of file dof_map.h.
typedef StoredRange<MeshBase::node_iterator, Node *> libMesh::NodeRange
Definition at line 33 of file node_range.h.
typedef Complex libMesh::Number
Definition at line 184 of file libmesh_common.h.
typedef TensorValue< Number > libMesh::NumberTensorValue
Definition at line 48 of file exact_error_estimator.h.
typedef VectorValue< Number > libMesh::NumberVectorValue
Definition at line 51 of file exact_error_estimator.h.
typedef dof_id_type libMesh::numeric_index_type
Definition at line 92 of file id_types.h.
typedef BasicOStreamProxy libMesh::OStreamProxy
Definition at line 231 of file ostream_proxy.h.
typedef uint16_t libMesh::processor_id_type
Definition at line 99 of file id_types.h.
typedef Real libMesh::REAL
Definition at line 36 of file mesh_triangle_wrapper.h.
typedef RealVectorValue libMesh::RealGradient
Definition at line 50 of file hp_coarsentest.h.
typedef RealTensorValue libMesh::RealTensor
Definition at line 51 of file hp_coarsentest.h.
typedef TensorValue< Real > libMesh::RealTensorValue
Useful typedefs to allow transparent switching between Real and Complex data types.
Definition at line 49 of file hp_coarsentest.h.
typedef VectorValue< Real > libMesh::RealVectorValue
Useful typedefs to allow transparent switching between Real and Complex data types.
Definition at line 47 of file hp_coarsentest.h.
typedef LinearImplicitSystem libMesh::SteadyLinearSystem
Definition at line 34 of file steady_system.h.
typedef uint16_t libMesh::subdomain_id_type
Note: subdomain_id_types are positive integers - however limitation in the exodusII API force us to use a signed integer here to represent subdomains. This gives us 2^31 possible unique blocks
Based on the 4-byte comment warning above, this probably doesn't work with exodusII at all...
Definition at line 43 of file id_types.h.
typedef NumberTensorValue libMesh::Tensor
Definition at line 50 of file exact_error_estimator.h.
typedef TransientSystem<System> libMesh::TransientBaseSystem
Definition at line 148 of file transient_system.h.
typedef TransientSystem<ExplicitSystem> libMesh::TransientExplicitSystem
Definition at line 147 of file transient_system.h.
typedef TransientSystem<LinearImplicitSystem> libMesh::TransientImplicitSystem
Definition at line 144 of file transient_system.h.
typedef TransientSystem<LinearImplicitSystem> libMesh::TransientLinearImplicitSystem
Definition at line 145 of file transient_system.h.
typedef TransientSystem<NonlinearImplicitSystem> libMesh::TransientNonlinearImplicitSystem
Definition at line 146 of file transient_system.h.
typedef uint64_t libMesh::unique_id_type
Definition at line 79 of file id_types.h.
template<typename T > using libMesh::UniquePtr = typedef std::unique_ptr<T>
Definition at line 46 of file auto_ptr.h.
typedef LIBMESH_BEST_UNORDERED_MULTISET<Elem *, ElemHashUtils, ElemHashUtils> libMesh::unordered_multiset_elem
Definition at line 63 of file elem_hash.h.
Enumeration Type Documentation
enum libMesh::EigenProblemType
Defines an enum for eigenproblem types. This can be Hermitian (HEP), generalized Hermitian (GHEP), non-Hermitian (NHEP), generalized non-Hermitian (GNHEP), or generalized indefinite Hermitian (GHIEP).
Enumerator
NHEP
HEP
GNHEP
GHEP
GHIEP
INVALID_EIGENPROBLEMTYPE
Definition at line 51 of file enum_eigen_solver_type.h.
                       {NHEP=0,
                        HEP,
                        GNHEP,
                        GHEP,
                        GHIEP,
                        INVALID_EIGENPROBLEMTYPE};
enum libMesh::EigenSolverType
Defines an enum for iterative eigenproblem solver types
Enumerator
POWER
LAPACK
SUBSPACE
ARNOLDI
LANCZOS
KRYLOVSCHUR
INVALID_EIGENSOLVER
Definition at line 30 of file enum_eigen_solver_type.h.
                      {POWER=0,
                       LAPACK,
                       SUBSPACE,
                       ARNOLDI,
                       LANCZOS,
                       KRYLOVSCHUR,
                       // SLEPc optional packages
                       // EPSARPACK,
                       // EPSLAPACK,
                       // EPSBLZPACK,
                       // EPSPLANSO,
                       // EPSTRLAN,
                       INVALID_EIGENSOLVER};
enum libMesh::ElemQuality
Defines an enum for element quality metrics.
Enumerator
ASPECT_RATIO
SKEW
SHEAR
SHAPE
MAX_ANGLE
MIN_ANGLE
CONDITION
DISTORTION
TAPER
WARP
STRETCH
DIAGONAL
ASPECT_RATIO_BETA
ASPECT_RATIO_GAMMA
SIZE
JACOBIAN
Definition at line 30 of file enum_elem_quality.h.
                  {ASPECT_RATIO=0,
                   SKEW,
                   SHEAR,
                   SHAPE,
                   MAX_ANGLE,
                   MIN_ANGLE,
                   CONDITION,
                   DISTORTION,
                   TAPER,
                   WARP,
                   STRETCH,
                   DIAGONAL,
                   ASPECT_RATIO_BETA,
                   ASPECT_RATIO_GAMMA,
                   SIZE,
                   JACOBIAN};
enum libMesh::ElemType
Defines an enum for geometric element types.
Enumerator
EDGE2
EDGE3
EDGE4
TRI3
TRI6
QUAD4
QUAD8
QUAD9
TET4
TET10
HEX8
HEX20
HEX27
PRISM6
PRISM15
PRISM18
PYRAMID5
PYRAMID13
PYRAMID14
INFEDGE2
INFQUAD4
INFQUAD6
INFHEX8
INFHEX16
INFHEX18
INFPRISM6
INFPRISM12
NODEELEM
REMOTEELEM
TRI3SUBDIVISION
INVALID_ELEM
Definition at line 30 of file enum_elem_type.h.
               {EDGE2=0,         // 0
                EDGE3,           // 1
                EDGE4,           // 2
                TRI3,            // 3
                TRI6,            // 4
                QUAD4,           // 5
                QUAD8,           // 6
                QUAD9,           // 7
                TET4,            // 8
                TET10,           // 9
                HEX8,            // 10
                HEX20,           // 11
                HEX27,           // 12
                PRISM6,          // 13
                PRISM15,         // 14
                PRISM18,         // 15
                PYRAMID5,        // 16
                PYRAMID13,       // 17
                PYRAMID14,       // 18
                INFEDGE2,        // 19
                INFQUAD4,        // 20
                INFQUAD6,        // 21
                INFHEX8,         // 22
                INFHEX16,        // 23
                INFHEX18,        // 24
                INFPRISM6,       // 25
                INFPRISM12,      // 26
                NODEELEM,        // 27
                REMOTEELEM,      // 28
                TRI3SUBDIVISION, // 29
                INVALID_ELEM};   // 30 - should always be last
enum libMesh::ErrorEstimatorType
Enumerator
INVALID
ADJOINT_REFINEMENT
ADJOINT_RESIDUAL
DISCONTINUITY_MEASURE
EXACT
KELLY
LAPLACIAN
PATCH_RECOVERY
WEIGHTED_PATCH_RECOVERY
UNIFORM_REFINEMENT
Definition at line 25 of file enum_error_estimator_type.h.
                         {INVALID                 = -1,
                          ADJOINT_REFINEMENT      =  0,
                          ADJOINT_RESIDUAL        =  1,
                          DISCONTINUITY_MEASURE   =  2,
                          EXACT                   =  3,
                          KELLY                   =  4,
                          LAPLACIAN               =  5,
                          PATCH_RECOVERY          =  6,
                          WEIGHTED_PATCH_RECOVERY =  7,
                          UNIFORM_REFINEMENT      =  8};
enum libMesh::FEContinuity
defines an enum for finite element types to libmesh_assert a certain level (or type? Hcurl?) of continuity.
Enumerator
DISCONTINUOUS
C_ZERO
C_ONE
H_CURL
Definition at line 72 of file enum_fe_family.h.
                   {DISCONTINUOUS,
                    C_ZERO,
                    C_ONE,
                    H_CURL};
enum libMesh::FEFamily
defines an enum for finite element families.
Enumerator
LAGRANGE
HIERARCHIC
MONOMIAL
L2_HIERARCHIC
L2_LAGRANGE
BERNSTEIN
SZABAB
XYZ
INFINITE_MAP
JACOBI_20_00
JACOBI_30_00
LEGENDRE
CLOUGH
HERMITE
SUBDIVISION
SCALAR
LAGRANGE_VEC
NEDELEC_ONE
INVALID_FE
Definition at line 32 of file enum_fe_family.h.
               {LAGRANGE     = 0,
                HIERARCHIC   = 1,
                // discontinuous, in local coordinates
                MONOMIAL      = 2,
                L2_HIERARCHIC = 6,
                L2_LAGRANGE   = 7,
                // higher-order
                BERNSTEIN    = 3,
                SZABAB       = 4,
                // discontinuous, in global coordinates
                XYZ          = 5,
                // infinite element stuff
                INFINITE_MAP = 11,     //   for 1/r-map
                JACOBI_20_00 = 12,     //   i_max = 19
                JACOBI_30_00 = 13,     //   i_max = 19
                LEGENDRE     = 14,     //   i_max = 19
                // C1 elements
                CLOUGH       = 21,
                HERMITE      = 22,
                SUBDIVISION  = 23,
                // A scalar variable that couples to
                // all other DOFs in the system
                SCALAR       = 31,
                // Vector-valued elements
                LAGRANGE_VEC = 41,
                NEDELEC_ONE  = 42,
                INVALID_FE   = 99};
enum libMesh::FEFieldType
defines an enum for finite element field types - i.e. is it a scalar element, vector, tensor, etc.
Enumerator
TYPE_SCALAR
TYPE_VECTOR
Definition at line 81 of file enum_fe_family.h.
                  {TYPE_SCALAR = 0,
                   TYPE_VECTOR};
enum libMesh::FEMNormType
defines an enum for norms defined on vectors of finite element coefficients
Enumerator
L2
H1
H2
HCURL
HDIV
L1
L_INF
H1_SEMINORM
H2_SEMINORM
HCURL_SEMINORM
HDIV_SEMINORM
W1_INF_SEMINORM
W2_INF_SEMINORM
DISCRETE_L1
DISCRETE_L2
DISCRETE_L_INF
H1_X_SEMINORM
H1_Y_SEMINORM
H1_Z_SEMINORM
INVALID_NORM
Definition at line 32 of file enum_norm_type.h.
                  {L2              = 0,
                   H1              = 1,
                   H2              = 2,
                   HCURL           = 3,
                   HDIV            = 4,
                   L1              = 5,
                   L_INF           = 6,
                   H1_SEMINORM     = 10,
                   H2_SEMINORM     = 11,
                   HCURL_SEMINORM  = 12,
                   HDIV_SEMINORM   = 13,
                   W1_INF_SEMINORM = 15,
                   W2_INF_SEMINORM = 16,
                   // discrete norms on coefficient vectors
                   DISCRETE_L1     = 20,
                   DISCRETE_L2     = 21,
                   DISCRETE_L_INF  = 22,
                   // Seminorms based on only individual gradient
                   // directional components
                   H1_X_SEMINORM    = 31,
                   H1_Y_SEMINORM    = 32,
                   H1_Z_SEMINORM    = 33,
                   INVALID_NORM    = 42};
enum libMesh::InfMapType
defines an enum for the types of coordinate mappings available in infinite elements.
Enumerator
CARTESIAN
SPHERICAL
ELLIPSOIDAL
INVALID_INF_MAP
Definition at line 31 of file enum_inf_map_type.h.
                 {CARTESIAN=0,
                  SPHERICAL,
                  ELLIPSOIDAL,
                  INVALID_INF_MAP};
enum libMesh::IOPackage
libMesh interfaces with several different software packages for the purposes of creating, reading, and writing mesh files. These enumerations give an easy way of selecting one or the other.
Enumerator
TECPLOT
GMV
GMSH
VTK
DIVA
TETGEN
UCD
LIBMESH
INVALID_IO_PACKAGE
Definition at line 34 of file enum_io_package.h.
   {
     TECPLOT,
     GMV,
     GMSH,
     VTK,
     DIVA,
     TETGEN,
     UCD,
     LIBMESH,
     INVALID_IO_PACKAGE
   };
enum libMesh::LinearConvergenceReason
Linear solver convergence flags (taken from the PETSc flags)
Enumerator
CONVERGED_RTOL_NORMAL
CONVERGED_ATOL_NORMAL
CONVERGED_RTOL
CONVERGED_ATOL
CONVERGED_ITS
CONVERGED_CG_NEG_CURVE
CONVERGED_CG_CONSTRAINED
CONVERGED_STEP_LENGTH
CONVERGED_HAPPY_BREAKDOWN
DIVERGED_NULL
DIVERGED_ITS
DIVERGED_DTOL
DIVERGED_BREAKDOWN
DIVERGED_BREAKDOWN_BICG
DIVERGED_NONSYMMETRIC
DIVERGED_INDEFINITE_PC
DIVERGED_NAN
DIVERGED_INDEFINITE_MAT
CONVERGED_ITERATING
UNKNOWN_FLAG
Definition at line 30 of file enum_convergence_flags.h.
{
   /* converged */
   CONVERGED_RTOL_NORMAL        =  1,
   CONVERGED_ATOL_NORMAL        =  9,
   CONVERGED_RTOL               =  2,
   CONVERGED_ATOL               =  3,
   CONVERGED_ITS                =  4,
   CONVERGED_CG_NEG_CURVE       =  5,
   CONVERGED_CG_CONSTRAINED     =  6,
   CONVERGED_STEP_LENGTH        =  7,
   CONVERGED_HAPPY_BREAKDOWN    =  8,
   /* diverged */
   DIVERGED_NULL                = -2,
   DIVERGED_ITS                 = -3,
   DIVERGED_DTOL                = -4,
   DIVERGED_BREAKDOWN           = -5,
   DIVERGED_BREAKDOWN_BICG      = -6,
   DIVERGED_NONSYMMETRIC        = -7,
   DIVERGED_INDEFINITE_PC       = -8,
   DIVERGED_NAN                 = -9,
   DIVERGED_INDEFINITE_MAT      = -10,
   CONVERGED_ITERATING          =  0,
   UNKNOWN_FLAG                 = -128};
enum libMesh::Order
defines an enum for polynomial orders. Fixing each label to a specific int, since InfFE and p refinement may cast between them
Enumerator
CONSTANT
FIRST
SECOND
THIRD
FOURTH
FIFTH
SIXTH
SEVENTH
EIGHTH
NINTH
TENTH
ELEVENTH
TWELFTH
THIRTEENTH
FOURTEENTH
FIFTEENTH
SIXTEENTH
SEVENTEENTH
EIGHTTEENTH
NINTEENTH
NINETEENTH
TWENTIETH
TWENTYFIRST
TWENTYSECOND
TWENTYTHIRD
TWENTYFOURTH
TWENTYFIFTH
TWENTYSIXTH
TWENTYSEVENTH
TWENTYEIGHTH
TWENTYNINTH
THIRTIETH
THIRTYFIRST
THIRTYSECOND
THIRTYTHIRD
THIRTYFOURTH
THIRTYFIFTH
THIRTYSIXTH
THIRTYSEVENTH
THIRTYEIGHTH
THIRTYNINTH
FORTIETH
FORTYFIRST
FORTYSECOND
FORTYTHIRD
INVALID_ORDER
Definition at line 32 of file enum_order.h.
            {CONSTANT     =  0,
             FIRST        =  1,
             SECOND       =  2,
             THIRD        =  3,
             FOURTH       =  4,
             FIFTH        =  5,
             SIXTH        =  6,
             SEVENTH      =  7,
             EIGHTH       =  8,
             NINTH        =  9,
             TENTH        = 10,
             ELEVENTH     = 11,
             TWELFTH      = 12,
             THIRTEENTH   = 13,
             FOURTEENTH   = 14,
             FIFTEENTH    = 15,
             SIXTEENTH    = 16,
             SEVENTEENTH  = 17,
             EIGHTTEENTH  = 18,
             NINTEENTH    = 19, // deprecated
             NINETEENTH   = 19,
             TWENTIETH    = 20,
             TWENTYFIRST   = 21,
             TWENTYSECOND  = 22,
             TWENTYTHIRD   = 23,
             TWENTYFOURTH  = 24,
             TWENTYFIFTH   = 25,
             TWENTYSIXTH   = 26,
             TWENTYSEVENTH = 27,
             TWENTYEIGHTH  = 28,
             TWENTYNINTH   = 29,
             THIRTIETH     = 30,
             THIRTYFIRST   = 31,
             THIRTYSECOND  = 32,
             THIRTYTHIRD   = 33,
             THIRTYFOURTH  = 34,
             THIRTYFIFTH   = 35,
             THIRTYSIXTH   = 36,
             THIRTYSEVENTH = 37,
             THIRTYEIGHTH  = 38,
             THIRTYNINTH   = 39,
             FORTIETH     = 40,
             FORTYFIRST   = 41,
             FORTYSECOND  = 42,
             FORTYTHIRD   = 43,
             INVALID_ORDER};
enum libMesh::ParallelType
Defines an enum for parallel data structure types
Enumerator
AUTOMATIC
SERIAL
PARALLEL
GHOSTED
INVALID_PARALLELIZATION
Definition at line 30 of file enum_parallel_type.h.
                   {AUTOMATIC=0,
                    SERIAL,
                    PARALLEL,
                    GHOSTED,
                    INVALID_PARALLELIZATION};
enum libMesh::PointLocatorType
defines an enum for the types of point locators (given a point with global coordinates, locate the corresponding element in space) available in libMesh.
Enumerator
TREE
TREE_ELEMENTS
TREE_LOCAL_ELEMENTS
LIST
INVALID_LOCATOR
Definition at line 32 of file enum_point_locator_type.h.
                       {TREE = 0,
                        TREE_ELEMENTS,
                        TREE_LOCAL_ELEMENTS,
                        LIST,
                        INVALID_LOCATOR};
enum libMesh::PositionOfSpectrum
Defines an enum for the position of the spectrum, i.e. the eigenvalues to be computed.
Enumerator
LARGEST_MAGNITUDE
SMALLEST_MAGNITUDE
LARGEST_REAL
SMALLEST_REAL
LARGEST_IMAGINARY
SMALLEST_IMAGINARY
INVALID_Postion_of_Spectrum
Definition at line 65 of file enum_eigen_solver_type.h.
                         {LARGEST_MAGNITUDE=0,
                          SMALLEST_MAGNITUDE,
                          LARGEST_REAL,
                          SMALLEST_REAL,
                          LARGEST_IMAGINARY,
                          SMALLEST_IMAGINARY,
                          INVALID_Postion_of_Spectrum};
enum libMesh::PreconditionerType
Defines an enum for preconditioner types
Enumerator
IDENTITY_PRECOND
JACOBI_PRECOND
BLOCK_JACOBI_PRECOND
SOR_PRECOND
SSOR_PRECOND
EISENSTAT_PRECOND
ASM_PRECOND
CHOLESKY_PRECOND
ICC_PRECOND
ILU_PRECOND
LU_PRECOND
USER_PRECOND
SHELL_PRECOND
AMG_PRECOND
INVALID_PRECONDITIONER
Definition at line 30 of file enum_preconditioner_type.h.
                         {IDENTITY_PRECOND =0,
                          JACOBI_PRECOND,
                          BLOCK_JACOBI_PRECOND,
                          SOR_PRECOND,
                          SSOR_PRECOND,
                          EISENSTAT_PRECOND,
                          ASM_PRECOND,
                          CHOLESKY_PRECOND,
                          ICC_PRECOND,
                          ILU_PRECOND,
                          LU_PRECOND,
                          USER_PRECOND,
                          SHELL_PRECOND,
                          AMG_PRECOND,
                          INVALID_PRECONDITIONER};
enum libMesh::QuadratureType
Defines an enum for currently available quadrature rules.
Enumerator
QGAUSS
QJACOBI_1_0
QJACOBI_2_0
QSIMPSON
QTRAP
QGRID
QGRUNDMANN_MOLLER
QMONOMIAL
QCONICAL
QGAUSS_LOBATTO
QCLOUGH
QCOMPOSITE
INVALID_Q_RULE
Definition at line 30 of file enum_quadrature_type.h.
                     {QGAUSS            = 0,
                      QJACOBI_1_0       = 1,
                      QJACOBI_2_0       = 2,
                      QSIMPSON          = 3,
                      QTRAP             = 4,
                      QGRID             = 5,
                      QGRUNDMANN_MOLLER = 6,
                      QMONOMIAL         = 7,
                      QCONICAL          = 8,
                      QGAUSS_LOBATTO    = 9,
                      QCLOUGH           = 21,
                      QCOMPOSITE        = 31,
                      INVALID_Q_RULE    = 127};
enum libMesh::SolverPackage
Defines an enum for various linear solver packages. This allows for run-time switching between solver packages
Enumerator
PETSC_SOLVERS
SLEPC_SOLVERS
NLOPT_SOLVERS
Definition at line 32 of file enum_solver_package.h.
   {
     PETSC_SOLVERS=0,
     TRILINOS_SOLVERS,
     LASPACK_SOLVERS,
     SLEPC_SOLVERS,
     EIGEN_SOLVERS,
     NLOPT_SOLVERS,
     INVALID_SOLVER_PACKAGE
   };
enum libMesh::SolverType
Defines an enum for iterative solver types
Enumerator
CG
CGN
CGS
CR
QMR
TCQMR
TFQMR
BICG
BICGSTAB
MINRES
GMRES
LSQR
JACOBI
SOR_FORWARD
SOR_BACKWARD
SSOR
RICHARDSON
CHEBYSHEV
SPARSELU
INVALID_SOLVER
Definition at line 30 of file enum_solver_type.h.
                 {CG=0,
                  CGN,
                  CGS,
                  CR,
                  QMR,
                  TCQMR,
                  TFQMR,
                  BICG,
                  BICGSTAB,
                  MINRES,
                  GMRES,
                  LSQR,
                  JACOBI,
                  SOR_FORWARD,
                  SOR_BACKWARD,
                  SSOR,
                  RICHARDSON,
                  CHEBYSHEV,
                  SPARSELU,
                  INVALID_SOLVER};
enum libMesh::SubsetSolveMode
defines an enum for the question what happens to the dofs outside the given subset when a system is solved on a subset.
Enumerator
SUBSET_ZERO
Set dofs outside the subset to zero.
SUBSET_COPY_RHS
Set dofs outside the subset to the value of the corresponding dofs of the right hand side.
SUBSET_DONT_TOUCH
Leaves dofs outside the subset unchanged. This is fastest, but also most confusing because it abandons the property that the solution vector is (theoretically) independent of the initial guess.
Definition at line 32 of file enum_subset_solve_mode.h.
                      {
   SUBSET_ZERO = 0,
   SUBSET_COPY_RHS,
   SUBSET_DONT_TOUCH
 };
enum libMesh::XdrMODE
Defines an enum for read/write mode in Xdr format. READ, WRITE perform reading and writing in ASCII format, and DECODE, ENCODE do the same in binary format.
Enumerator
UNKNOWN
ENCODE
DECODE
WRITE
READ
Definition at line 32 of file enum_xdr_mode.h.
   {
     UNKNOWN = -1, ENCODE=0, DECODE, WRITE, READ
   };
Function Documentation
void libMesh::__libmesh_nlopt_equality_constraints (unsigned m, double * result, unsigned n, const double * x, double * gradient, void * data)
Definition at line 111 of file nlopt_optimization_solver.C.
References data, libMesh::OptimizationSystem::ComputeEqualityConstraints::equality_constraints(), libMesh::OptimizationSystem::ComputeEqualityConstraintsJacobian::equality_constraints_jacobian(), libMesh::OptimizationSolver< T >::equality_constraints_jacobian_object, libMesh::OptimizationSolver< T >::equality_constraints_object, libmesh_assert(), solver, START_LOG(), STOP_LOG(), sys, and libMesh::OptimizationSolver< T >::system().
Referenced by libMesh::NloptOptimizationSolver< T >::solve().
 {
   START_LOG("equality_constraints()", "NloptOptimizationSolver");
   libmesh_assert(data);
   // data should be a pointer to the solver (it was passed in as void *)
   NloptOptimizationSolver<Number> * solver =
     static_cast<NloptOptimizationSolver<Number> *> (data);
   OptimizationSystem & sys = solver->system();
   // We'll use current_local_solution below, so let's ensure that it's consistent
   // with the vector x that was passed in.
   if (sys.solution->size() != n)
     libmesh_error_msg("Error: Input vector x has different length than sys.solution!");
   for(unsigned int i=sys.solution->first_local_index(); i<sys.solution->last_local_index(); i++)
     sys.solution->set(i, x[i]);
   sys.solution->close();
   // Impose constraints on the solution vector
   sys.get_dof_map().enforce_constraints_exactly(sys);
   // Update sys.current_local_solution based on the solution vector
   sys.update();
   // Call the user's equality constraints function if there is one.
   OptimizationSystem::ComputeEqualityConstraints * eco = solver->equality_constraints_object;
   if (eco)
     {
       eco->equality_constraints(*sys.current_local_solution,
                                 *sys.C_eq,
                                 sys);
       sys.C_eq->close();
       // Copy the values out of eq_constraints into 'result'.
       // TODO: Even better would be if we could use 'result' directly
       // as the storage of eq_constraints.  Perhaps a serial-only
       // NumericVector variant which supports this option?
       for (unsigned i=0; i<m; ++i)
         result[i] = (*sys.C_eq)(i);
       // If gradient != NULL, then the Jacobian matrix of the equality
       // constraints has been requested.  The incoming 'gradient'
       // array is of length m*n and d(c_i)/d(x_j) = gradient[n*i+j].
       if (gradient)
         {
           OptimizationSystem::ComputeEqualityConstraintsJacobian * eco_jac =
             solver->equality_constraints_jacobian_object;
           if (eco_jac)
             {
               eco_jac->equality_constraints_jacobian(*sys.current_local_solution,
                                                      *sys.C_eq_jac,
                                                      sys);
               sys.C_eq_jac->close();
               // copy the Jacobian data to the gradient array
               for(numeric_index_type i=0; i<m; i++)
                 {
                   std::set<numeric_index_type>::iterator it = sys.eq_constraint_jac_sparsity[i].begin();
                   std::set<numeric_index_type>::iterator it_end = sys.eq_constraint_jac_sparsity[i].end();
                   for( ; it != it_end; ++it)
                     {
                       numeric_index_type dof_index = *it;
                       gradient[n*i+dof_index] = (*sys.C_eq_jac)(i,dof_index);
                     }
                 }
             }
           else
             libmesh_error_msg("Jacobian function not defined in __libmesh_nlopt_equality_constraints");
         }
     }
   else
     libmesh_error_msg("Constraints function not defined in __libmesh_nlopt_equality_constraints");
   STOP_LOG("equality_constraints()", "NloptOptimizationSolver");
 }
void libMesh::__libmesh_nlopt_inequality_constraints (unsigned m, double * result, unsigned n, const double * x, double * gradient, void * data)
Definition at line 202 of file nlopt_optimization_solver.C.
References data, libMesh::OptimizationSystem::ComputeInequalityConstraints::inequality_constraints(), libMesh::OptimizationSystem::ComputeInequalityConstraintsJacobian::inequality_constraints_jacobian(), libMesh::OptimizationSolver< T >::inequality_constraints_jacobian_object, libMesh::OptimizationSolver< T >::inequality_constraints_object, libmesh_assert(), solver, START_LOG(), STOP_LOG(), sys, and libMesh::OptimizationSolver< T >::system().
Referenced by libMesh::NloptOptimizationSolver< T >::solve().
 {
   START_LOG("inequality_constraints()", "NloptOptimizationSolver");
   libmesh_assert(data);
   // data should be a pointer to the solver (it was passed in as void *)
   NloptOptimizationSolver<Number> * solver =
     static_cast<NloptOptimizationSolver<Number> *> (data);
   OptimizationSystem & sys = solver->system();
   // We'll use current_local_solution below, so let's ensure that it's consistent
   // with the vector x that was passed in.
   if (sys.solution->size() != n)
     libmesh_error_msg("Error: Input vector x has different length than sys.solution!");
   for(unsigned int i=sys.solution->first_local_index(); i<sys.solution->last_local_index(); i++)
     sys.solution->set(i, x[i]);
   sys.solution->close();
   // Impose constraints on the solution vector
   sys.get_dof_map().enforce_constraints_exactly(sys);
   // Update sys.current_local_solution based on the solution vector
   sys.update();
   // Call the user's inequality constraints function if there is one.
   OptimizationSystem::ComputeInequalityConstraints * ineco = solver->inequality_constraints_object;
   if (ineco)
     {
       ineco->inequality_constraints(*sys.current_local_solution,
                                     *sys.C_ineq,
                                     sys);
       sys.C_ineq->close();
       // Copy the values out of ineq_constraints into 'result'.
       // TODO: Even better would be if we could use 'result' directly
       // as the storage of ineq_constraints.  Perhaps a serial-only
       // NumericVector variant which supports this option?
       for (unsigned i=0; i<m; ++i)
         result[i] = (*sys.C_ineq)(i);
       // If gradient != NULL, then the Jacobian matrix of the equality
       // constraints has been requested.  The incoming 'gradient'
       // array is of length m*n and d(c_i)/d(x_j) = gradient[n*i+j].
       if (gradient)
         {
           OptimizationSystem::ComputeInequalityConstraintsJacobian * ineco_jac =
             solver->inequality_constraints_jacobian_object;
           if (ineco_jac)
             {
               ineco_jac->inequality_constraints_jacobian(*sys.current_local_solution,
                                                          *sys.C_ineq_jac,
                                                          sys);
               sys.C_ineq_jac->close();
               // copy the Jacobian data to the gradient array
               for(numeric_index_type i=0; i<m; i++)
                 {
                   std::set<numeric_index_type>::iterator it = sys.ineq_constraint_jac_sparsity[i].begin();
                   std::set<numeric_index_type>::iterator it_end = sys.ineq_constraint_jac_sparsity[i].end();
                   for( ; it != it_end; ++it)
                     {
                       numeric_index_type dof_index = *it;
                       gradient[n*i+dof_index] = (*sys.C_ineq_jac)(i,dof_index);
                     }
                 }
             }
           else
             libmesh_error_msg("Jacobian function not defined in __libmesh_nlopt_inequality_constraints");
         }
     }
   else
     libmesh_error_msg("Constraints function not defined in __libmesh_nlopt_inequality_constraints");
   STOP_LOG("inequality_constraints()", "NloptOptimizationSolver");
 }
double libMesh::__libmesh_nlopt_objective (unsigned n, const double * x, double * gradient, void * data)
Definition at line 36 of file nlopt_optimization_solver.C.
References data, libMesh::NloptOptimizationSolver< T >::get_iteration_count(), libMesh::OptimizationSystem::ComputeGradient::gradient(), libMesh::OptimizationSolver< T >::gradient_object, libmesh_assert(), libmesh_nullptr, libMesh::OptimizationSystem::ComputeObjective::objective(), libMesh::OptimizationSolver< T >::objective_object, out, Real, solver, START_LOG(), STOP_LOG(), sys, libMesh::OptimizationSolver< T >::system(), and libMesh::OptimizationSolver< T >::verbose.
Referenced by libMesh::NloptOptimizationSolver< T >::solve().
 {
   START_LOG("objective()", "NloptOptimizationSolver");
   // ctx should be a pointer to the solver (it was passed in as void *)
   NloptOptimizationSolver<Number> * solver =
     static_cast<NloptOptimizationSolver<Number> *> (data);
   OptimizationSystem & sys = solver->system();
   // We'll use current_local_solution below, so let's ensure that it's consistent
   // with the vector x that was passed in.
   for (unsigned int i=sys.solution->first_local_index();
        i<sys.solution->last_local_index(); i++)
     sys.solution->set(i, x[i]);
   // Make sure the solution vector is parallel-consistent
   sys.solution->close();
   // Impose constraints on X
   sys.get_dof_map().enforce_constraints_exactly(sys);
   // Update sys.current_local_solution based on X
   sys.update();
   Real objective;
   if (solver->objective_object != libmesh_nullptr)
     {
       objective =
         solver->objective_object->objective(
                                             *(sys.current_local_solution), sys);
     }
   else
     {
       libmesh_error_msg("Objective function not defined in __libmesh_nlopt_objective");
     }
   // If the gradient has been requested, fill it in
   if (gradient)
     {
       if (solver->gradient_object != libmesh_nullptr)
         {
           solver->gradient_object->gradient(
                                             *(sys.current_local_solution), *(sys.rhs), sys);
           // we've filled up sys.rhs with the gradient data, now copy it
           // to the nlopt data structure
           libmesh_assert(sys.rhs->size() == n);
           std::vector<double> grad;
           sys.rhs->localize_to_one(grad);
           for (unsigned i=0; i<n; ++i)
             gradient[i] = grad[i];
         }
       else
         libmesh_error_msg("Gradient function not defined in __libmesh_nlopt_objective");
     }
   STOP_LOG("objective()", "NloptOptimizationSolver");
   // Increment the iteration count.
   solver->get_iteration_count()++;
   // Possibly print the current value of the objective function
   if (solver->verbose)
     libMesh::out << objective << std::endl;
   return objective;
 }
PetscErrorCode libMesh::__libmesh_petsc_diff_solver_jacobian (SNES , Vec x, Mat * libmesh_dbg_varj, Mat * pc, MatStructure * msflag, void * ctx)
Referenced by libMesh::PetscDiffSolver::solve().
PetscErrorCode libMesh::__libmesh_petsc_diff_solver_monitor (SNES snes, PetscInt its, PetscReal fnorm, void * ctx)
Definition at line 43 of file petsc_diff_solver.C.
References CHKERRABORT(), libMesh::ParallelObject::comm(), libMesh::Parallel::Communicator::get(), ierr, libmesh_nullptr, libMesh::DiffSolver::linear_solution_monitor, out, solver, and libMesh::DiffSolver::verbose.
Referenced by libMesh::PetscDiffSolver::init().
   {
     PetscDiffSolver & solver =
       *(static_cast<PetscDiffSolver *> (ctx));
     if (solver.verbose)
       libMesh::out << "  PetscDiffSolver step " << its
                    << ", |residual|_2 = " << fnorm << std::endl;
     if (solver.linear_solution_monitor.get()) {
       int ierr = 0;
       Vec petsc_delta_u;
       ierr = SNESGetSolutionUpdate(snes, &petsc_delta_u);
       CHKERRABORT(solver.comm().get(), ierr);
       PetscVector<Number> delta_u(petsc_delta_u, solver.comm());
       delta_u.close();
       Vec petsc_u;
       ierr = SNESGetSolution(snes, &petsc_u);
       CHKERRABORT(solver.comm().get(), ierr);
       PetscVector<Number> u(petsc_u, solver.comm());
       u.close();
       Vec petsc_res;
       ierr = SNESGetFunction(snes, &petsc_res, libmesh_nullptr, libmesh_nullptr);
       CHKERRABORT(solver.comm().get(), ierr);
       PetscVector<Number> res(petsc_res, solver.comm());
       res.close();
       (*solver.linear_solution_monitor)(
                                         delta_u, delta_u.l2_norm(),
                                         u, u.l2_norm(),
                                         res, res.l2_norm(), its);
     }
     return 0;
   }
PetscErrorCode libMesh::__libmesh_petsc_diff_solver_residual (SNES , Vec x, Vec r, void * ctx)
Definition at line 86 of file petsc_diff_solver.C.
References libMesh::ImplicitSystem::assembly(), libMesh::ParallelObject::comm(), libMesh::DofMap::enforce_constraints_exactly(), libMesh::System::get_dof_map(), libmesh_assert(), out, libMesh::ExplicitSystem::rhs, libMesh::System::solution, solver, sys, libMesh::DiffSolver::system(), libMesh::System::update(), libMesh::DiffSolver::verbose, X_input(), and X_system.
Referenced by libMesh::PetscDiffSolver::solve().
   {
     libmesh_assert(x);
     libmesh_assert(r);
     libmesh_assert(ctx);
     PetscDiffSolver & solver =
       *(static_cast<PetscDiffSolver*> (ctx));
     ImplicitSystem & sys = solver.system();
     if (solver.verbose)
       libMesh::out << "Assembling the residual" << std::endl;
     PetscVector<Number> & X_system =
       *cast_ptr<PetscVector<Number> *>(sys.solution.get());
     PetscVector<Number> & R_system =
       *cast_ptr<PetscVector<Number> *>(sys.rhs);
     PetscVector<Number> X_input(x, sys.comm()), R_input(r, sys.comm());
     // DiffSystem assembles from the solution and into the rhs, so swap
     // those with our input vectors before assembling.  They'll probably
     // already be references to the same vectors, but PETSc might do
     // something tricky.
     X_input.swap(X_system);
     R_input.swap(R_system);
     // We may need to correct a non-conforming solution
     sys.get_dof_map().enforce_constraints_exactly(sys);
     // We may need to localize a parallel solution
     sys.update();
     // Do DiffSystem assembly
     sys.assembly(true, false);
     R_system.close();
     // Swap back
     X_input.swap(X_system);
     R_input.swap(R_system);
     // No errors, we hope
     return 0;
   }
PetscErrorCode libMesh::__libmesh_petsc_preconditioner_apply (void * ctx, Vec x, Vec y)
This function is called by PETSc to acctually apply the preconditioner. ctx will hold the Preconditioner.
Definition at line 58 of file petsc_linear_solver.C.
Referenced by libMesh::PetscNonlinearSolver< T >::init(), and libMesh::PetscLinearSolver< T >::init().
   {
     Preconditioner<Number> * preconditioner = static_cast<Preconditioner<Number> *>(ctx);
     PetscVector<Number> x_vec(x, preconditioner->comm());
     PetscVector<Number> y_vec(y, preconditioner->comm());
     preconditioner->apply(x_vec,y_vec);
     return 0;
   }
PetscErrorCode libMesh::__libmesh_petsc_preconditioner_apply (PC pc, Vec x, Vec y)
Definition at line 84 of file petsc_linear_solver.C.
References CHKERRQ(), and ierr.
   {
     void * ctx;
     PetscErrorCode ierr = PCShellGetContext(pc,&ctx);CHKERRQ(ierr);
     Preconditioner<Number> * preconditioner = static_cast<Preconditioner<Number> *>(ctx);
     PetscVector<Number> x_vec(x, preconditioner->comm());
     PetscVector<Number> y_vec(y, preconditioner->comm());
     preconditioner->apply(x_vec,y_vec);
     return 0;
   }
PetscErrorCode libMesh::__libmesh_petsc_preconditioner_setup (void * ctx)
This function is called by PETSc to initialize the preconditioner. ctx will hold the Preconditioner.
Definition at line 45 of file petsc_linear_solver.C.
Referenced by libMesh::PetscNonlinearSolver< T >::init(), and libMesh::PetscLinearSolver< T >::init().
   {
     Preconditioner<Number> * preconditioner = static_cast<Preconditioner<Number> *>(ctx);
     if (!preconditioner->initialized())
       libmesh_error_msg("Preconditioner not initialized!  Make sure you call init() before solve!");
     preconditioner->setup();
     return 0;
   }
PetscErrorCode libMesh::__libmesh_petsc_preconditioner_setup (PC pc)
Definition at line 70 of file petsc_linear_solver.C.
References CHKERRQ(), and ierr.
   {
     void * ctx;
     PetscErrorCode ierr = PCShellGetContext(pc,&ctx);CHKERRQ(ierr);
     Preconditioner<Number> * preconditioner = static_cast<Preconditioner<Number> *>(ctx);
     if (!preconditioner->initialized())
       libmesh_error_msg("Preconditioner not initialized!  Make sure you call init() before solve!");
     preconditioner->setup();
     return 0;
   }
PetscErrorCode libMesh::__libmesh_petsc_snes_jacobian (SNES , Vec x, Mat * jac, Mat * pc, MatStructure * msflag, void * ctx)
PetscErrorCode libMesh::__libmesh_petsc_snes_jacobian (SNES , Vec x, Mat jac, Mat pc, void * ctx)
PetscErrorCode libMesh::__libmesh_petsc_snes_jacobian (#if PETSC_RELEASE_LESS_THAN(3, 5, 0) SNES snes, Vec x, Mat * jac, Mat * pc, MatStructure * msflag, void *ctx#else SNES snes, Vec x, Mat jac, Mat pc, void *ctx# endif)
Definition at line 156 of file petsc_nonlinear_solver.C.
References libMesh::PetscNonlinearSolver< T >::_current_nonlinear_iteration_number, libMesh::PetscNonlinearSolver< T >::_zero_out_jacobian, CHKERRABORT(), libMesh::ParallelObject::comm(), libMesh::System::current_local_solution, libMesh::DofMap::enforce_constraints_exactly(), libMesh::Parallel::Communicator::get(), libMesh::System::get_dof_map(), ierr, libMesh::NonlinearImplicitSystem::ComputeJacobian::jacobian(), libMesh::NonlinearSolver< T >::jacobian, libMesh::NonlinearSolver< T >::jacobian_object, libmesh_assert(), libmesh_nullptr, libMesh::NonlinearSolver< T >::matvec, libMesh::NonlinearImplicitSystem::ComputeResidualandJacobian::residual_and_jacobian(), libMesh::NonlinearSolver< T >::residual_and_jacobian_object, libMesh::System::solution, solver, START_LOG(), STOP_LOG(), sys, libMesh::NonlinearSolver< T >::system(), and libMesh::System::update().
Referenced by libMesh::PetscNonlinearSolver< T >::solve().
   {
     START_LOG("jacobian()", "PetscNonlinearSolver");
     PetscErrorCode ierr=0;
     libmesh_assert(ctx);
     // No way to safety-check this cast, since we got a void *...
     PetscNonlinearSolver<Number> * solver =
       static_cast<PetscNonlinearSolver<Number> *> (ctx);
     // Get the current iteration number from the snes object,
     // store it in the PetscNonlinearSolver object for possible use
     // by the user's Jacobian function.
     {
       PetscInt n_iterations = 0;
       ierr = SNESGetIterationNumber(snes, &n_iterations);
       CHKERRABORT(solver->comm().get(),ierr);
       solver->_current_nonlinear_iteration_number = cast_int<unsigned>(n_iterations);
     }
     NonlinearImplicitSystem & sys = solver->system();
 #if PETSC_RELEASE_LESS_THAN(3,5,0)
     PetscMatrix<Number> PC(*pc, sys.comm());
     PetscMatrix<Number> Jac(*jac, sys.comm());
 #else
     PetscMatrix<Number> PC(pc, sys.comm());
     PetscMatrix<Number> Jac(jac, sys.comm());
 #endif
     PetscVector<Number> & X_sys = *cast_ptr<PetscVector<Number> *>(sys.solution.get());
     PetscVector<Number> X_global(x, sys.comm());
     // Set the dof maps
     PC.attach_dof_map(sys.get_dof_map());
     Jac.attach_dof_map(sys.get_dof_map());
     // Use the systems update() to get a good local version of the parallel solution
     X_global.swap(X_sys);
     sys.update();
     X_global.swap(X_sys);
     // Enforce constraints (if any) exactly on the
     // current_local_solution.  This is the solution vector that is
     // actually used in the computation of the residual below, and is
     // not locked by debug-enabled PETSc the way that "x" is.
     sys.get_dof_map().enforce_constraints_exactly(sys, sys.current_local_solution.get());
     if (solver->_zero_out_jacobian)
       PC.zero();
     //-----------------------------------------------------------------------------
     // if the user has provided both function pointers and objects only the pointer
     // will be used, so catch that as an error
     if (solver->jacobian && solver->jacobian_object)
       libmesh_error_msg("ERROR: cannot specify both a function and object to compute the Jacobian!");
     if (solver->matvec && solver->residual_and_jacobian_object)
       libmesh_error_msg("ERROR: cannot specify both a function and object to compute the combined Residual & Jacobian!");
     if (solver->jacobian != libmesh_nullptr)
       solver->jacobian(*sys.current_local_solution.get(), PC, sys);
     else if (solver->jacobian_object != libmesh_nullptr)
       solver->jacobian_object->jacobian(*sys.current_local_solution.get(), PC, sys);
     else if (solver->matvec != libmesh_nullptr)
       solver->matvec(*sys.current_local_solution.get(), libmesh_nullptr, &PC, sys);
     else if (solver->residual_and_jacobian_object != libmesh_nullptr)
       solver->residual_and_jacobian_object->residual_and_jacobian (*sys.current_local_solution.get(), libmesh_nullptr, &PC, sys);
     else
       libmesh_error_msg("Error! Unable to compute residual and/or Jacobian!");
     PC.close();
     Jac.close();
 #if PETSC_RELEASE_LESS_THAN(3,5,0)
     *msflag = SAME_NONZERO_PATTERN;
 #endif
     STOP_LOG("jacobian()", "PetscNonlinearSolver");
     return ierr;
   }
PetscErrorCode libMesh::__libmesh_petsc_snes_monitor (SNES , PetscInt its, PetscReal fnorm, void *)
Definition at line 54 of file petsc_nonlinear_solver.C.
References out.
Referenced by libMesh::PetscNonlinearSolver< T >::init().
   {
     //PetscErrorCode ierr=0;
     //if (its > 0)
     libMesh::out << "  NL step "
                  << std::setw(2) << its
                  << std::scientific
                  << ", |residual|_2 = " << fnorm
                  << std::endl;
     //return ierr;
     return 0;
   }
PetscErrorCode libMesh::__libmesh_petsc_snes_postcheck (#if PETSC_VERSION_LESS_THAN(3, 3, 0) SNES, Vec x, Vec y, Vec w, void * context, PetscBool * changed_y, PetscBool *changed_w#else SNESLineSearch, Vec x, Vec y, Vec w, PetscBool * changed_y, PetscBool * changed_w, void *context# endif)
Definition at line 257 of file petsc_nonlinear_solver.C.
References libMesh::ParallelObject::comm(), dof_map, libMesh::DofMap::enforce_constraints_exactly(), libMesh::System::get_dof_map(), ierr, libmesh_assert(), libMesh::DofMap::n_constrained_dofs(), libMesh::NonlinearImplicitSystem::ComputePostCheck::postcheck(), libMesh::NonlinearSolver< T >::postcheck, libMesh::NonlinearSolver< T >::postcheck_object, libMesh::System::solution, solver, START_LOG(), STOP_LOG(), sys, and libMesh::NonlinearSolver< T >::system().
Referenced by libMesh::PetscNonlinearSolver< T >::init().
   {
     START_LOG("postcheck()", "PetscNonlinearSolver");
     PetscErrorCode ierr = 0;
     // PETSc almost certainly initializes these to false already, but
     // it doesn't hurt to be explicit.
     *changed_w = PETSC_FALSE;
     *changed_y = PETSC_FALSE;
     libmesh_assert(context);
     // Cast the context to a NonlinearSolver object.
     PetscNonlinearSolver<Number> * solver =
       static_cast<PetscNonlinearSolver<Number> *> (context);
     // If the user has provided both postcheck function pointer and
     // object, this is ambiguous, so throw an error.
     if (solver->postcheck && solver->postcheck_object)
       libmesh_error_msg("ERROR: cannot specify both a function and object for performing the solve postcheck!");
     // It's also possible that we don't need to do anything at all, in
     // that case return early...
     NonlinearImplicitSystem & sys = solver->system();
     DofMap & dof_map = sys.get_dof_map();
     if (!dof_map.n_constrained_dofs() && !solver->postcheck && !solver->postcheck_object)
       return ierr;
     // We definitely need to wrap at least "w"
     PetscVector<Number> petsc_w(w, sys.comm());
     // The user sets these flags in his/her postcheck function to
     // indicate whether they changed something.
     bool
       changed_search_direction = false,
       changed_new_soln = false;
     if (solver->postcheck || solver->postcheck_object)
       {
         PetscVector<Number> petsc_x(x, sys.comm());
         PetscVector<Number> petsc_y(y, sys.comm());
         if (solver->postcheck)
           solver->postcheck(petsc_x,
                             petsc_y,
                             petsc_w,
                             changed_search_direction,
                             changed_new_soln,
                             sys);
         else if (solver->postcheck_object)
           solver->postcheck_object->postcheck(petsc_x,
                                               petsc_y,
                                               petsc_w,
                                               changed_search_direction,
                                               changed_new_soln,
                                               sys);
       }
     // Record whether the user changed the solution or the search direction.
     if (changed_search_direction)
       *changed_y = PETSC_TRUE;
     if (changed_new_soln)
       *changed_w = PETSC_TRUE;
     if (dof_map.n_constrained_dofs())
       {
         PetscVector<Number> & system_soln = *cast_ptr<PetscVector<Number> *>(sys.solution.get());
         // ... and swap it in before enforcing the constraints.
         petsc_w.swap(system_soln);
         dof_map.enforce_constraints_exactly(sys);
         // If we have constraints, we'll assume that we did change the
         // solution w (hopefully slightly).  Enforcing constraints
         // does not change the search direction, y, but the user may
         // have, so we leave it alone.
         *changed_w = PETSC_TRUE;
         // Swap back
         petsc_w.swap(system_soln);
       }
     STOP_LOG("postcheck()", "PetscNonlinearSolver");
     return ierr;
   }
PetscErrorCode libMesh::__libmesh_petsc_snes_residual (SNES snes, Vec x, Vec r, void * ctx)
Definition at line 74 of file petsc_nonlinear_solver.C.
References libMesh::PetscNonlinearSolver< T >::_current_nonlinear_iteration_number, libMesh::PetscNonlinearSolver< T >::_zero_out_residual, CHKERRABORT(), libMesh::ParallelObject::comm(), libMesh::System::current_local_solution, libMesh::DofMap::enforce_constraints_exactly(), libMesh::Parallel::Communicator::get(), libMesh::System::get_dof_map(), ierr, libmesh_assert(), libmesh_nullptr, libMesh::NonlinearSolver< T >::matvec, libMesh::NonlinearImplicitSystem::ComputeResidual::residual(), libMesh::NonlinearSolver< T >::residual, libMesh::NonlinearImplicitSystem::ComputeResidualandJacobian::residual_and_jacobian(), libMesh::NonlinearSolver< T >::residual_and_jacobian_object, libMesh::NonlinearSolver< T >::residual_object, libMesh::System::solution, solver, START_LOG(), STOP_LOG(), sys, libMesh::NonlinearSolver< T >::system(), and libMesh::System::update().
Referenced by libMesh::PetscNonlinearSolver< T >::solve().
   {
     START_LOG("residual()", "PetscNonlinearSolver");
     PetscErrorCode ierr=0;
     libmesh_assert(x);
     libmesh_assert(r);
     libmesh_assert(ctx);
     // No way to safety-check this cast, since we got a void *...
     PetscNonlinearSolver<Number> * solver =
       static_cast<PetscNonlinearSolver<Number> *> (ctx);
     // Get the current iteration number from the snes object,
     // store it in the PetscNonlinearSolver object for possible use
     // by the user's residual function.
     {
       PetscInt n_iterations = 0;
       ierr = SNESGetIterationNumber(snes, &n_iterations);
       CHKERRABORT(solver->comm().get(),ierr);
       solver->_current_nonlinear_iteration_number = cast_int<unsigned>(n_iterations);
     }
     NonlinearImplicitSystem & sys = solver->system();
     PetscVector<Number> & X_sys = *cast_ptr<PetscVector<Number> *>(sys.solution.get());
     PetscVector<Number> X_global(x, sys.comm()), R(r, sys.comm());
     // Use the system's update() to get a good local version of the
     // parallel solution.  This operation does not modify the incoming
     // "x" vector, it only localizes information from "x" into
     // sys.current_local_solution.
     X_global.swap(X_sys);
     sys.update();
     X_global.swap(X_sys);
     // Enforce constraints (if any) exactly on the
     // current_local_solution.  This is the solution vector that is
     // actually used in the computation of the residual below, and is
     // not locked by debug-enabled PETSc the way that "x" is.
     sys.get_dof_map().enforce_constraints_exactly(sys, sys.current_local_solution.get());
     if (solver->_zero_out_residual)
       R.zero();
     //-----------------------------------------------------------------------------
     // if the user has provided both function pointers and objects only the pointer
     // will be used, so catch that as an error
     if (solver->residual && solver->residual_object)
       libmesh_error_msg("ERROR: cannot specifiy both a function and object to compute the Residual!");
     if (solver->matvec && solver->residual_and_jacobian_object)
       libmesh_error_msg("ERROR: cannot specifiy both a function and object to compute the combined Residual & Jacobian!");
     if (solver->residual != libmesh_nullptr)
       solver->residual(*sys.current_local_solution.get(), R, sys);
     else if (solver->residual_object != libmesh_nullptr)
       solver->residual_object->residual(*sys.current_local_solution.get(), R, sys);
     else if (solver->matvec != libmesh_nullptr)
       solver->matvec (*sys.current_local_solution.get(), &R, libmesh_nullptr, sys);
     else if (solver->residual_and_jacobian_object != libmesh_nullptr)
       solver->residual_and_jacobian_object->residual_and_jacobian (*sys.current_local_solution.get(), &R, libmesh_nullptr, sys);
     else
       libmesh_error_msg("Error! Unable to compute residual and/or Jacobian!");
     R.close();
     STOP_LOG("residual()", "PetscNonlinearSolver");
     return ierr;
   }
PetscErrorCode libMesh::__libmesh_tao_equality_constraints (Tao , Vec x, Vec ce, void * ctx)
Definition at line 204 of file tao_optimization_solver.C.
References libMesh::ParallelObject::comm(), libMesh::OptimizationSystem::ComputeEqualityConstraints::equality_constraints(), libMesh::OptimizationSolver< T >::equality_constraints_object, ierr, libmesh_assert(), libmesh_nullptr, solver, START_LOG(), STOP_LOG(), sys, and libMesh::OptimizationSolver< T >::system().
Referenced by libMesh::TaoOptimizationSolver< T >::solve().
   {
     START_LOG("equality_constraints()", "TaoOptimizationSolver");
     PetscErrorCode ierr = 0;
     libmesh_assert(x);
     libmesh_assert(ce);
     libmesh_assert(ctx);
     // ctx should be a pointer to the solver (it was passed in as void *)
     TaoOptimizationSolver<Number> * solver =
       static_cast<TaoOptimizationSolver<Number> *> (ctx);
     OptimizationSystem & sys = solver->system();
     // We'll use current_local_solution below, so let's ensure that it's consistent
     // with the vector x that was passed in.
     PetscVector<Number> & X_sys = *cast_ptr<PetscVector<Number> *>(sys.solution.get());
     PetscVector<Number> X(x, sys.comm());
     // Perform a swap so that sys.solution points to X
     X.swap(X_sys);
     // Impose constraints on X
     sys.get_dof_map().enforce_constraints_exactly(sys);
     // Update sys.current_local_solution based on X
     sys.update();
     // Swap back
     X.swap(X_sys);
     // We'll also pass the constraints vector ce into the assembly routine
     // so let's make a PETSc vector for that too.
     PetscVector<Number> eq_constraints(ce, sys.comm());
     // Clear the gradient prior to assembly
     eq_constraints.zero();
     if (solver->equality_constraints_object != libmesh_nullptr)
       solver->equality_constraints_object->equality_constraints(*(sys.current_local_solution), eq_constraints, sys);
     else
       libmesh_error_msg("Constraints function not defined in __libmesh_tao_equality_constraints");
     eq_constraints.close();
     STOP_LOG("equality_constraints()", "TaoOptimizationSolver");
     return ierr;
   }
PetscErrorCode libMesh::__libmesh_tao_equality_constraints_jacobian (Tao , Vec x, Mat J, Mat Jpre, void * ctx)
Definition at line 257 of file tao_optimization_solver.C.
References libMesh::ParallelObject::comm(), libMesh::OptimizationSystem::ComputeEqualityConstraintsJacobian::equality_constraints_jacobian(), libMesh::OptimizationSolver< T >::equality_constraints_jacobian_object, ierr, libmesh_assert(), libmesh_nullptr, solver, START_LOG(), STOP_LOG(), sys, and libMesh::OptimizationSolver< T >::system().
Referenced by libMesh::TaoOptimizationSolver< T >::solve().
   {
     START_LOG("equality_constraints_jacobian()", "TaoOptimizationSolver");
     PetscErrorCode ierr = 0;
     libmesh_assert(x);
     libmesh_assert(J);
     libmesh_assert(Jpre);
     // ctx should be a pointer to the solver (it was passed in as void *)
     TaoOptimizationSolver<Number> * solver =
       static_cast<TaoOptimizationSolver<Number> *> (ctx);
     OptimizationSystem & sys = solver->system();
     // We'll use current_local_solution below, so let's ensure that it's consistent
     // with the vector x that was passed in.
     PetscVector<Number> & X_sys = *cast_ptr<PetscVector<Number> *>(sys.solution.get());
     PetscVector<Number> X(x, sys.comm());
     // Perform a swap so that sys.solution points to X
     X.swap(X_sys);
     // Impose constraints on X
     sys.get_dof_map().enforce_constraints_exactly(sys);
     // Update sys.current_local_solution based on X
     sys.update();
     // Swap back
     X.swap(X_sys);
     // Let's also wrap J and Jpre in PetscMatrix objects for convenience
     PetscMatrix<Number> J_petsc(J, sys.comm());
     PetscMatrix<Number> Jpre_petsc(Jpre, sys.comm());
     if (solver->equality_constraints_jacobian_object != libmesh_nullptr)
       solver->equality_constraints_jacobian_object->equality_constraints_jacobian(*(sys.current_local_solution), J_petsc, sys);
     else
       libmesh_error_msg("Constraints function not defined in __libmesh_tao_equality_constraints_jacobian");
     J_petsc.close();
     Jpre_petsc.close();
     STOP_LOG("equality_constraints_jacobian()", "TaoOptimizationSolver");
     return ierr;
   }
PetscErrorCode libMesh::__libmesh_tao_gradient (Tao , Vec x, Vec g, void * ctx)
Definition at line 94 of file tao_optimization_solver.C.
References libMesh::ParallelObject::comm(), libMesh::OptimizationSystem::ComputeGradient::gradient(), libMesh::OptimizationSolver< T >::gradient_object, ierr, libmesh_assert(), libmesh_nullptr, solver, START_LOG(), STOP_LOG(), sys, and libMesh::OptimizationSolver< T >::system().
Referenced by libMesh::TaoOptimizationSolver< T >::solve().
   {
     START_LOG("gradient()", "TaoOptimizationSolver");
     PetscErrorCode ierr = 0;
     libmesh_assert(x);
     libmesh_assert(g);
     libmesh_assert(ctx);
     // ctx should be a pointer to the solver (it was passed in as void *)
     TaoOptimizationSolver<Number> * solver =
       static_cast<TaoOptimizationSolver<Number> *> (ctx);
     OptimizationSystem & sys = solver->system();
     // We'll use current_local_solution below, so let's ensure that it's consistent
     // with the vector x that was passed in.
     PetscVector<Number> & X_sys = *cast_ptr<PetscVector<Number> *>(sys.solution.get());
     PetscVector<Number> X(x, sys.comm());
     // Perform a swap so that sys.solution points to X
     X.swap(X_sys);
     // Impose constraints on X
     sys.get_dof_map().enforce_constraints_exactly(sys);
     // Update sys.current_local_solution based on X
     sys.update();
     // Swap back
     X.swap(X_sys);
     // We'll also pass the gradient in to the assembly routine
     // so let's make a PETSc vector for that too.
     PetscVector<Number> gradient(g, sys.comm());
     // Clear the gradient prior to assembly
     gradient.zero();
     if (solver->gradient_object != libmesh_nullptr)
       solver->gradient_object->gradient(*(sys.current_local_solution), gradient, sys);
     else
       libmesh_error_msg("Gradient function not defined in __libmesh_tao_gradient");
     gradient.close();
     STOP_LOG("gradient()", "TaoOptimizationSolver");
     return ierr;
   }
PetscErrorCode libMesh::__libmesh_tao_hessian (Tao , Vec x, Mat h, Mat pc, void * ctx)
Definition at line 146 of file tao_optimization_solver.C.
References libMesh::ParallelObject::comm(), libMesh::OptimizationSystem::ComputeHessian::hessian(), libMesh::OptimizationSolver< T >::hessian_object, ierr, libmesh_assert(), libmesh_nullptr, solver, START_LOG(), STOP_LOG(), sys, and libMesh::OptimizationSolver< T >::system().
Referenced by libMesh::TaoOptimizationSolver< T >::solve().
   {
     START_LOG("hessian()", "TaoOptimizationSolver");
     PetscErrorCode ierr = 0;
     libmesh_assert(x);
     libmesh_assert(h);
     libmesh_assert(pc);
     libmesh_assert(ctx);
     // ctx should be a pointer to the solver (it was passed in as void *)
     TaoOptimizationSolver<Number> * solver =
       static_cast<TaoOptimizationSolver<Number> *> (ctx);
     OptimizationSystem & sys = solver->system();
     // We'll use current_local_solution below, so let's ensure that it's consistent
     // with the vector x that was passed in.
     PetscVector<Number> & X_sys = *cast_ptr<PetscVector<Number> *>(sys.solution.get());
     PetscVector<Number> X(x, sys.comm());
     // Perform a swap so that sys.solution points to X
     X.swap(X_sys);
     // Impose constraints on X
     sys.get_dof_map().enforce_constraints_exactly(sys);
     // Update sys.current_local_solution based on X
     sys.update();
     // Swap back
     X.swap(X_sys);
     // Let's also wrap pc and h in PetscMatrix objects for convenience
     PetscMatrix<Number> PC(pc, sys.comm());
     PetscMatrix<Number> hessian(h, sys.comm());
     PC.attach_dof_map(sys.get_dof_map());
     hessian.attach_dof_map(sys.get_dof_map());
     if (solver->hessian_object != libmesh_nullptr)
       {
         // Following PetscNonlinearSolver by passing in PC. It's not clear
         // why we pass in PC and not hessian though?
         solver->hessian_object->hessian(*(sys.current_local_solution), PC, sys);
       }
     else
       libmesh_error_msg("Hessian function not defined in __libmesh_tao_hessian");
     PC.close();
     hessian.close();
     STOP_LOG("hessian()", "TaoOptimizationSolver");
     return ierr;
   }
PetscErrorCode libMesh::__libmesh_tao_inequality_constraints (Tao , Vec x, Vec cineq, void * ctx)
Definition at line 307 of file tao_optimization_solver.C.
References libMesh::ParallelObject::comm(), ierr, libMesh::OptimizationSystem::ComputeInequalityConstraints::inequality_constraints(), libMesh::OptimizationSolver< T >::inequality_constraints_object, libmesh_assert(), libmesh_nullptr, solver, START_LOG(), STOP_LOG(), sys, and libMesh::OptimizationSolver< T >::system().
Referenced by libMesh::TaoOptimizationSolver< T >::solve().
   {
     START_LOG("inequality_constraints()", "TaoOptimizationSolver");
     PetscErrorCode ierr = 0;
     libmesh_assert(x);
     libmesh_assert(cineq);
     libmesh_assert(ctx);
     // ctx should be a pointer to the solver (it was passed in as void *)
     TaoOptimizationSolver<Number> * solver =
       static_cast<TaoOptimizationSolver<Number> *> (ctx);
     OptimizationSystem & sys = solver->system();
     // We'll use current_local_solution below, so let's ensure that it's consistent
     // with the vector x that was passed in.
     PetscVector<Number> & X_sys = *cast_ptr<PetscVector<Number> *>(sys.solution.get());
     PetscVector<Number> X(x, sys.comm());
     // Perform a swap so that sys.solution points to X
     X.swap(X_sys);
     // Impose constraints on X
     sys.get_dof_map().enforce_constraints_exactly(sys);
     // Update sys.current_local_solution based on X
     sys.update();
     // Swap back
     X.swap(X_sys);
     // We'll also pass the constraints vector ce into the assembly routine
     // so let's make a PETSc vector for that too.
     PetscVector<Number> ineq_constraints(cineq, sys.comm());
     // Clear the gradient prior to assembly
     ineq_constraints.zero();
     if (solver->inequality_constraints_object != libmesh_nullptr)
       solver->inequality_constraints_object->inequality_constraints(*(sys.current_local_solution), ineq_constraints, sys);
     else
       libmesh_error_msg("Constraints function not defined in __libmesh_tao_inequality_constraints");
     ineq_constraints.close();
     STOP_LOG("inequality_constraints()", "TaoOptimizationSolver");
     return ierr;
   }
PetscErrorCode libMesh::__libmesh_tao_inequality_constraints_jacobian (Tao , Vec x, Mat J, Mat Jpre, void * ctx)
Definition at line 360 of file tao_optimization_solver.C.
References libMesh::ParallelObject::comm(), ierr, libMesh::OptimizationSystem::ComputeInequalityConstraintsJacobian::inequality_constraints_jacobian(), libMesh::OptimizationSolver< T >::inequality_constraints_jacobian_object, libmesh_assert(), libmesh_nullptr, solver, START_LOG(), STOP_LOG(), sys, and libMesh::OptimizationSolver< T >::system().
Referenced by libMesh::TaoOptimizationSolver< T >::solve().
   {
     START_LOG("inequality_constraints_jacobian()", "TaoOptimizationSolver");
     PetscErrorCode ierr = 0;
     libmesh_assert(x);
     libmesh_assert(J);
     libmesh_assert(Jpre);
     // ctx should be a pointer to the solver (it was passed in as void *)
     TaoOptimizationSolver<Number> * solver =
       static_cast<TaoOptimizationSolver<Number> *> (ctx);
     OptimizationSystem & sys = solver->system();
     // We'll use current_local_solution below, so let's ensure that it's consistent
     // with the vector x that was passed in.
     PetscVector<Number> & X_sys = *cast_ptr<PetscVector<Number> *>(sys.solution.get());
     PetscVector<Number> X(x, sys.comm());
     // Perform a swap so that sys.solution points to X
     X.swap(X_sys);
     // Impose constraints on X
     sys.get_dof_map().enforce_constraints_exactly(sys);
     // Update sys.current_local_solution based on X
     sys.update();
     // Swap back
     X.swap(X_sys);
     // Let's also wrap J and Jpre in PetscMatrix objects for convenience
     PetscMatrix<Number> J_petsc(J, sys.comm());
     PetscMatrix<Number> Jpre_petsc(Jpre, sys.comm());
     if (solver->inequality_constraints_jacobian_object != libmesh_nullptr)
       solver->inequality_constraints_jacobian_object->inequality_constraints_jacobian(*(sys.current_local_solution), J_petsc, sys);
     else
       libmesh_error_msg("Constraints function not defined in __libmesh_tao_inequality_constraints_jacobian");
     J_petsc.close();
     Jpre_petsc.close();
     STOP_LOG("inequality_constraints_jacobian()", "TaoOptimizationSolver");
     return ierr;
   }
PetscErrorCode libMesh::__libmesh_tao_objective (Tao , Vec x, PetscReal * objective, void * ctx)
Definition at line 49 of file tao_optimization_solver.C.
References libMesh::ParallelObject::comm(), ierr, libmesh_assert(), libmesh_nullptr, libMesh::OptimizationSystem::ComputeObjective::objective(), libMesh::OptimizationSolver< T >::objective_object, solver, START_LOG(), STOP_LOG(), sys, and libMesh::OptimizationSolver< T >::system().
Referenced by libMesh::TaoOptimizationSolver< T >::solve().
   {
     START_LOG("objective()", "TaoOptimizationSolver");
     PetscErrorCode ierr = 0;
     libmesh_assert(x);
     libmesh_assert(objective);
     libmesh_assert(ctx);
     // ctx should be a pointer to the solver (it was passed in as void *)
     TaoOptimizationSolver<Number> * solver =
       static_cast<TaoOptimizationSolver<Number> *> (ctx);
     OptimizationSystem & sys = solver->system();
     // We'll use current_local_solution below, so let's ensure that it's consistent
     // with the vector x that was passed in.
     PetscVector<Number> & X_sys = *cast_ptr<PetscVector<Number> *>(sys.solution.get());
     PetscVector<Number> X(x, sys.comm());
     // Perform a swap so that sys.solution points to X
     X.swap(X_sys);
     // Impose constraints on X
     sys.get_dof_map().enforce_constraints_exactly(sys);
     // Update sys.current_local_solution based on X
     sys.update();
     // Swap back
     X.swap(X_sys);
     if (solver->objective_object != libmesh_nullptr)
       (*objective) = solver->objective_object->objective(*(sys.current_local_solution), sys);
     else
       libmesh_error_msg("Objective function not defined in __libmesh_tao_objective");
     STOP_LOG("objective()", "TaoOptimizationSolver");
     return ierr;
   }
template<typename Tnew , typename Told > Tnew libMesh::cast_int (Told oldvar) inline
Definition at line 541 of file libmesh_common.h.
 {
   libmesh_assert_equal_to
     (oldvar, static_cast<Told>(static_cast<Tnew>(oldvar)));
   return(static_cast<Tnew>(oldvar));
 }
template<typename Tnew , typename Told > Tnew libMesh::cast_ptr (Told * oldvar) inline
Definition at line 504 of file libmesh_common.h.
References err, and libMesh::Quality::name().
Referenced by libMesh::Parameters::have_parameter().
 {
 #if !defined(NDEBUG) && defined(LIBMESH_HAVE_RTTI)
   Tnew newvar = dynamic_cast<Tnew>(oldvar);
   if (!newvar)
     {
       libMesh::err << "Failed to convert " << typeid(Told).name()
                    << " pointer to " << typeid(Tnew).name()
                    << std::endl;
       libMesh::err << "The " << typeid(Told).name()
                    << " appears to be a "
                    << typeid(*oldvar).name() << std::endl;
       libmesh_error();
     }
   return newvar;
 #else
   return(static_cast<Tnew>(oldvar));
 #endif
 }
template<typename Tnew , typename Told > Tnew libMesh::cast_ref (Told & oldvar) inline
Definition at line 470 of file libmesh_common.h.
References err, and libMesh::Quality::name().
 {
 #if !defined(NDEBUG) && defined(LIBMESH_HAVE_RTTI) && defined(LIBMESH_ENABLE_EXCEPTIONS)
   try
     {
       Tnew newvar = dynamic_cast<Tnew>(oldvar);
       return newvar;
     }
   catch (std::bad_cast)
     {
       libMesh::err << "Failed to convert " << typeid(Told).name()
                    << " reference to " << typeid(Tnew).name()
                    << std::endl;
       libMesh::err << "The " << typeid(Told).name()
                    << " appears to be a "
                    << typeid(*(&oldvar)).name() << std::endl;
       libmesh_error();
     }
 #else
   return(static_cast<Tnew>(oldvar));
 #endif
 }
libMesh::CHKERRABORT (comm , ierr)
Referenced by __libmesh_petsc_diff_solver_monitor(), __libmesh_petsc_snes_jacobian(), __libmesh_petsc_snes_residual(), libMesh::PetscLinearSolver< T >::_petsc_shell_matrix_get_diagonal(), libMesh::SlepcEigenSolver< T >::_petsc_shell_matrix_get_diagonal(), libMesh::PetscLinearSolver< T >::_petsc_shell_matrix_mult(), libMesh::SlepcEigenSolver< T >::_petsc_shell_matrix_mult(), libMesh::PetscLinearSolver< T >::_petsc_shell_matrix_mult_add(), if(), and libMesh::PetscPreconditioner< T >::set_petsc_preconditioner_type().
bool libMesh::closed ()
Checks that the library has been closed. This should always return false when called from a library object. It is useful to libmesh_assert(!libMeshclosed()) in library object destructors.
Definition at line 268 of file libmesh.C.
References libMesh::libMeshPrivateData::_is_initialized.
Referenced by libMesh::MeshBase::~MeshBase(), libMesh::System::~System(), and libMesh::UnstructuredMesh::~UnstructuredMesh().
 {
   return !libMeshPrivateData::_is_initialized;
 }
template<typename T > T libMesh::command_line_next (const std::string & , T)
Use GetPot's search()/next() functions to get following arguments from the command line.
Definition at line 863 of file libmesh.C.
References libmesh_assert().
Referenced by libMesh::NloptOptimizationSolver< T >::init(), and libMesh::DofMap::use_coupled_neighbor_dofs().
 {
   // Make sure the command line parser is ready for use
   libmesh_assert(command_line.get());
   if (command_line->search(1, name.c_str()))
     value = command_line->next(value);
   return value;
 }
template double libMesh::command_line_next< double > (const std::string & , double)
template float libMesh::command_line_next< float > (const std::string & , float)
template int libMesh::command_line_next< int > (const std::string & , int)
template long double libMesh::command_line_next< long double > (const std::string & , long double)
template std::string libMesh::command_line_next< std::string > (const std::string & , std::string)
template<typename T > T libMesh::command_line_value (const std::string & , T)
Returns
the value associated with name on the command line if it is specified, otherwise return the default, provided value. A second template function is provided to support recognizing multiple variations of a given option
Definition at line 831 of file libmesh.C.
References libmesh_assert().
Referenced by petsc_auto_fieldsplit().
 {
   // Make sure the command line parser is ready for use
   libmesh_assert(command_line.get());
   // only if the variable exists in the file
   if (command_line->have_variable(name.c_str()))
     value = (*command_line)(name.c_str(), value);
   return value;
 }
template<typename T > T libMesh::command_line_value (const std::vector< std::string > & name, T value)
Definition at line 844 of file libmesh.C.
References libmesh_assert().
 {
   // Make sure the command line parser is ready for use
   libmesh_assert(command_line.get());
   // Check for multiple options (return the first that matches)
   for (std::vector<std::string>::const_iterator i=name.begin(); i != name.end(); ++i)
     if (command_line->have_variable(i->c_str()))
       {
         value = (*command_line)(i->c_str(), value);
         break;
       }
   return value;
 }
template double libMesh::command_line_value< double > (const std::string & , double)
template double libMesh::command_line_value< double > (const std::vector< std::string > & , double)
template float libMesh::command_line_value< float > (const std::string & , float)
template float libMesh::command_line_value< float > (const std::vector< std::string > & , float)
template int libMesh::command_line_value< int > (const std::string & , int)
template int libMesh::command_line_value< int > (const std::vector< std::string > & , int)
template long double libMesh::command_line_value< long double > (const std::string & , long double)
template long double libMesh::command_line_value< long double > (const std::vector< std::string > & , long double)
template std::string libMesh::command_line_value< std::string > (const std::string & , std::string)
template std::string libMesh::command_line_value< std::string > (const std::vector< std::string > & , std::string)
template<typename T > void libMesh::command_line_vector (const std::string & , std::vector< T > &)
Returns
the array of values associated with name on the command line if it is specified, otherwise return the default, provided array.
Definition at line 877 of file libmesh.C.
References libmesh_assert().
 {
   // Make sure the command line parser is ready for use
   libmesh_assert(command_line.get());
   // only if the variable exists on the command line
   if (command_line->have_variable(name.c_str()))
     {
       unsigned size = command_line->vector_variable_size(name.c_str());
       vec.resize(size);
       for (unsigned i=0; i<size; ++i)
         vec[i] = (*command_line)(name.c_str(), vec[i], i);
     }
 }
template void libMesh::command_line_vector< double > (const std::string & , std::vector< double > &)
template void libMesh::command_line_vector< float > (const std::string & , std::vector< float > &)
template void libMesh::command_line_vector< int > (const std::string & , std::vector< int > &)
template void libMesh::command_line_vector< long double > (const std::string & , std::vector< long double > &)
DiffSolver::SolveResult libMesh::convert_solve_result (SNESConvergedReason r)
Definition at line 283 of file petsc_diff_solver.C.
Referenced by libMesh::PetscDiffSolver::solve().
 {
   switch (r)
     {
     case SNES_CONVERGED_FNORM_ABS:
       return DiffSolver::CONVERGED_ABSOLUTE_RESIDUAL;
     case SNES_CONVERGED_FNORM_RELATIVE:
       return DiffSolver::CONVERGED_RELATIVE_RESIDUAL;
 #if PETSC_VERSION_LESS_THAN(3,2,1)
     case SNES_CONVERGED_PNORM_RELATIVE:
 #else
     case SNES_CONVERGED_SNORM_RELATIVE:
 #endif
       return DiffSolver::CONVERGED_RELATIVE_STEP;
     case SNES_CONVERGED_ITS:
     case SNES_CONVERGED_TR_DELTA:
       return DiffSolver::CONVERGED_NO_REASON;
     case SNES_DIVERGED_FUNCTION_DOMAIN:
     case SNES_DIVERGED_FUNCTION_COUNT:
     case SNES_DIVERGED_FNORM_NAN:
 #if !PETSC_VERSION_LESS_THAN(3,3,0)
     case SNES_DIVERGED_INNER:
 #endif
     case SNES_DIVERGED_LINEAR_SOLVE:
     case SNES_DIVERGED_LOCAL_MIN:
       return DiffSolver::DIVERGED_NO_REASON;
     case SNES_DIVERGED_MAX_IT:
       return DiffSolver::DIVERGED_MAX_NONLINEAR_ITERATIONS;
 #if PETSC_VERSION_LESS_THAN(3,2,0)
     case SNES_DIVERGED_LS_FAILURE:
 #else
     case SNES_DIVERGED_LINE_SEARCH:
 #endif
       return DiffSolver::DIVERGED_BACKTRACKING_FAILURE;
       // In PETSc, SNES_CONVERGED_ITERATING means
       // the solve is still iterating, but by the
       // time we get here, we must have either
       // converged or diverged, so
       // SNES_CONVERGED_ITERATING is invalid.
     case SNES_CONVERGED_ITERATING:
       return DiffSolver::INVALID_SOLVE_RESULT;
     default:
       break;
     }
   return DiffSolver::INVALID_SOLVE_RESULT;
 }
SolverPackage libMesh::default_solver_package ()
Returns
the default solver interface to use. The value depends on which solver packages were available when the library was configured. The command-line is also checked, allowing the user to override the compiled default. For example, –use-petsc will force the use of PETSc solvers, and –use-laspack will force the use of LASPACK solvers.
Definition at line 894 of file libmesh.C.
References libMesh::libMeshPrivateData::_solver_package, EIGEN_SOLVERS, initialized(), INVALID_SOLVER_PACKAGE, LASPACK_SOLVERS, libmesh_assert(), on_command_line(), PETSC_SOLVERS, and TRILINOS_SOLVERS.
 {
   libmesh_assert (libMesh::initialized());
   static bool called = false;
   // Check the command line.  Since the command line is
   // unchanging it is sufficient to do this only once.
   if (!called)
     {
       called = true;
 #ifdef LIBMESH_HAVE_PETSC
       if (libMesh::on_command_line ("--use-petsc"))
         libMeshPrivateData::_solver_package = PETSC_SOLVERS;
 #endif
 #ifdef LIBMESH_HAVE_TRILINOS
       if (libMesh::on_command_line ("--use-trilinos") ||
           libMesh::on_command_line ("--disable-petsc"))
         libMeshPrivateData::_solver_package = TRILINOS_SOLVERS;
 #endif
 #ifdef LIBMESH_HAVE_EIGEN
       if (libMesh::on_command_line ("--use-eigen"  ) ||
 #if defined(LIBMESH_HAVE_MPI)
           // If the user bypassed MPI, we disable PETSc and Trilinos
           // too
           libMesh::on_command_line ("--disable-mpi") ||
 #endif
           libMesh::on_command_line ("--disable-petsc"))
         libMeshPrivateData::_solver_package = EIGEN_SOLVERS;
 #endif
 #ifdef LIBMESH_HAVE_LASPACK
       if (libMesh::on_command_line ("--use-laspack"  ) ||
 #if defined(LIBMESH_HAVE_MPI)
           // If the user bypassed MPI, we disable PETSc and Trilinos
           // too
           libMesh::on_command_line ("--disable-mpi") ||
 #endif
           libMesh::on_command_line ("--disable-petsc"))
         libMeshPrivateData::_solver_package = LASPACK_SOLVERS;
 #endif
       if (libMesh::on_command_line ("--disable-laspack") &&
           libMesh::on_command_line ("--disable-trilinos") &&
           libMesh::on_command_line ("--disable-eigen") &&
           (
 #if defined(LIBMESH_HAVE_MPI)
            // If the user bypassed MPI, we disable PETSc too
            libMesh::on_command_line ("--disable-mpi") ||
 #endif
            libMesh::on_command_line ("--disable-petsc")))
         libMeshPrivateData::_solver_package = INVALID_SOLVER_PACKAGE;
     }
   return libMeshPrivateData::_solver_package;
 }
std::string libMesh::demangle (const char * name)
Mostly system independent demangler
Definition at line 233 of file print_trace.C.
References libMesh::Quality::name().
Referenced by libMesh::Parameters::get(), and libMesh::Parameters::Parameter< T >::type().
 {
   int status = 0;
   std::string ret = name;
   // Actually do the demangling
   char * demangled_name = abi::__cxa_demangle(name, 0, 0, &status);
   // If demangling returns non-NULL, save the result in a string.
   if (demangled_name)
     ret = demangled_name;
   // According to cxxabi.h docs, the caller is responsible for
   // deallocating memory.
   std::free(demangled_name);
   return ret;
 }
void libMesh::enableFPE (bool on)
Toggle floating point exceptions – courtesy of Cody Permann & MOOSE team
Toggle hardware trap floating point exceptions
Definition at line 749 of file libmesh.C.
References libmesh_nullptr.
 {
 #if !defined(LIBMESH_HAVE_FEENABLEEXCEPT) && defined(LIBMESH_HAVE_XMMINTRIN_H) && !defined(__SUNPRO_CC)
   static int flags = 0;
 #endif
   if (on)
     {
       struct sigaction new_action, old_action;
 #ifdef LIBMESH_HAVE_FEENABLEEXCEPT
       feenableexcept(FE_DIVBYZERO | FE_INVALID);
 #elif  LIBMESH_HAVE_XMMINTRIN_H
 #  ifndef __SUNPRO_CC
       flags = _MM_GET_EXCEPTION_MASK();           // store the flags
       _MM_SET_EXCEPTION_MASK(flags & ~_MM_MASK_INVALID);
 #  endif
 #endif
       // Set up the structure to specify the new action.
       new_action.sa_sigaction = libmesh_handleFPE;
       sigemptyset (&new_action.sa_mask);
       new_action.sa_flags = SA_SIGINFO;
       sigaction (SIGFPE, libmesh_nullptr, &old_action);
       if (old_action.sa_handler != SIG_IGN)
         sigaction (SIGFPE, &new_action, libmesh_nullptr);
     }
   else
     {
 #ifdef LIBMESH_HAVE_FEDISABLEEXCEPT
       fedisableexcept(FE_DIVBYZERO | FE_INVALID);
 #elif  LIBMESH_HAVE_XMMINTRIN_H
 #  ifndef __SUNPRO_CC
       _MM_SET_EXCEPTION_MASK(flags);
 #  endif
 #endif
       signal(SIGFPE, SIG_DFL);
     }
 }
void libMesh::enableSEGV (bool on)
Toggle libMesh reporting of segmentation faults
Definition at line 794 of file libmesh.C.
References libmesh_nullptr.
 {
   static struct sigaction old_action;
   static bool was_on = false;
   if (on)
     {
       struct sigaction new_action;
       was_on = true;
       // Set up the structure to specify the new action.
       new_action.sa_sigaction = libmesh_handleSEGV;
       sigemptyset (&new_action.sa_mask);
       new_action.sa_flags = SA_SIGINFO;
       sigaction (SIGSEGV, &new_action, &old_action);
     }
   else if (was_on)
     {
       was_on = false;
       sigaction (SIGSEGV, &old_action, libmesh_nullptr);
     }
 }
libMesh::for ()
Definition at line 241 of file exact_error_estimator.C.
References libMesh::Elem::active(), libMesh::MeshBase::active_local_elements_begin(), libMesh::MeshBase::active_local_elements_end(), libMesh::NumericVector< T >::build(), libMesh::FEGenericBase< OutputType >::build(), libMesh::Elem::child(), libMesh::FEGenericBase< OutputType >::coarsened_dof_values(), libMesh::ParallelObject::comm(), libMesh::System::current_local_solution, libMesh::System::current_solution(), libMesh::FEType::default_quadrature_rule(), libMesh::DofMap::dof_indices(), ErrorVectorReal, libMesh::System::get_dof_map(), libMesh::DofObject::id(), libMesh::Elem::n_children(), libMesh::System::name(), libMesh::Elem::parent(), SERIAL, libMesh::System::update_global_solution(), libMesh::System::variable_name(), libMesh::System::variable_number(), and libMesh::DofMap::variable_type().
Referenced by libMesh::DofMap::allgather_recursive_constraints(), libMesh::DofMap::get_local_constraints(), libMesh::DofMap::max_constraint_error(), libMesh::DofMap::process_constraints(), and libMesh::FEMContext::~FEMContext().
     {
       // Possibly skip this variable
       if (error_norm.weight(var) == 0.0) continue;
       // The (string) name of this variable
       const std::string & var_name = system.variable_name(var);
       // The type of finite element to use for this variable
       const FEType & fe_type = dof_map.variable_type (var);
       UniquePtr<FEBase> fe (FEBase::build (dim, fe_type));
       // Build an appropriate Gaussian quadrature rule
       UniquePtr<QBase> qrule =
         fe_type.default_quadrature_rule (dim,
                                          _extra_order);
       fe->attach_quadrature_rule (qrule.get());
       // Prepare a global solution and a MeshFunction of the fine system if we need one
       UniquePtr<MeshFunction> fine_values;
       UniquePtr<NumericVector<Number> > fine_soln = NumericVector<Number>::build(system.comm());
       if (_equation_systems_fine)
         {
           const System & fine_system = _equation_systems_fine->get_system(system.name());
           std::vector<Number> global_soln;
           // FIXME - we're assuming that the fine system solution gets
           // used even when a different vector is used for the coarse
           // system
           fine_system.update_global_solution(global_soln);
           fine_soln->init
             (cast_int<numeric_index_type>(global_soln.size()), true,
              SERIAL);
           (*fine_soln) = global_soln;
           fine_values = UniquePtr<MeshFunction>
             (new MeshFunction(*_equation_systems_fine,
                               *fine_soln,
                               fine_system.get_dof_map(),
                               fine_system.variable_number(var_name)));
           fine_values->init();
         } else {
         // Initialize functors if we're using them
         for (unsigned int i=0; i != _exact_values.size(); ++i)
           if (_exact_values[i])
             _exact_values[i]->init();
         for (unsigned int i=0; i != _exact_derivs.size(); ++i)
           if (_exact_derivs[i])
             _exact_derivs[i]->init();
         for (unsigned int i=0; i != _exact_hessians.size(); ++i)
           if (_exact_hessians[i])
             _exact_hessians[i]->init();
       }
       // Request the data we'll need to compute with
       fe->get_JxW();
       fe->get_phi();
       fe->get_dphi();
 #ifdef LIBMESH_ENABLE_SECOND_DERIVATIVES
       fe->get_d2phi();
 #endif
       fe->get_xyz();
 #ifdef LIBMESH_ENABLE_AMR
       // If we compute on parent elements, we'll want to do so only
       // once on each, so we need to keep track of which we've done.
       std::vector<bool> computed_var_on_parent;
       if (estimate_parent_error)
         computed_var_on_parent.resize(error_per_cell.size(), false);
 #endif
       // TODO: this ought to be threaded (and using subordinate
       // MeshFunction objects in each thread rather than a single
       // master)
       // Iterate over all the active elements in the mesh
       // that live on this processor.
       MeshBase::const_element_iterator
         elem_it  = mesh.active_local_elements_begin();
       const MeshBase::const_element_iterator
         elem_end = mesh.active_local_elements_end();
       for (;elem_it != elem_end; ++elem_it)
         {
           // e is necessarily an active element on the local processor
           const Elem * elem = *elem_it;
           const dof_id_type e_id = elem->id();
 #ifdef LIBMESH_ENABLE_AMR
           // See if the parent of element e has been examined yet;
           // if not, we may want to compute the estimator on it
           const Elem * parent = elem->parent();
           // We only can compute and only need to compute on
           // parents with all active children
           bool compute_on_parent = true;
           if (!parent || !estimate_parent_error)
             compute_on_parent = false;
           else
             for (unsigned int c=0; c != parent->n_children(); ++c)
               if (!parent->child(c)->active())
                 compute_on_parent = false;
           if (compute_on_parent &&
               !computed_var_on_parent[parent->id()])
             {
               computed_var_on_parent[parent->id()] = true;
               // Compute a projection onto the parent
               DenseVector<Number> Uparent;
               FEBase::coarsened_dof_values(*(system.current_local_solution),
                                            dof_map, parent, Uparent,
                                            var, false);
               error_per_cell[parent->id()] +=
                 static_cast<ErrorVectorReal>
                 (find_squared_element_error(system, var_name,
                                             parent, Uparent,
                                             fe.get(),
                                             fine_values.get()));
             }
 #endif
           // Get the local to global degree of freedom maps
           std::vector<dof_id_type> dof_indices;
           dof_map.dof_indices (elem, dof_indices, var);
           const unsigned int n_dofs =
             cast_int<unsigned int>(dof_indices.size());
           DenseVector<Number> Uelem(n_dofs);
           for (unsigned int i=0; i != n_dofs; ++i)
             Uelem(i) = system.current_solution(dof_indices[i]);
           error_per_cell[e_id] +=
             static_cast<ErrorVectorReal>
             (find_squared_element_error(system, var_name, elem,
                                         Uelem, fe.get(),
                                         fine_values.get()));
         } // End loop over active local elements
     } // End loop over variables
sys libMesh::get_dof_map ()
Definition at line 180 of file petsc_diff_solver.C.
Referenced by libMesh::TransientSystem< Base >::init_data(), libMesh::CondensedEigenSystem::initialize_condensed_dofs(), libMesh::TransientSystem< Base >::old_solution(), libMesh::TransientSystem< Base >::older_solution(), and libMesh::TransientSystem< Base >::re_update().
   : Parent(s)
 {
 }
std::string libMesh::get_io_compatibility_version ()
Specifier for I/O file compatibility features. This only needs to be changed when new restart file functionality is added.
Definition at line 77 of file libmesh_version.C.
Referenced by libMesh::EquationSystems::write().
 {
   std::string retval(LIBMESH_IO_COMPATIBILITY_VERSION);
   return retval;
 }
int libMesh::get_libmesh_version ()
Definition at line 43 of file libmesh_version.C.
Referenced by libmesh_version_stdout().
 {
   /* Note: return format follows the versioning convention xx.yy.zz where
      xx = major version number
      yy = minor version number
      zz = micro version number
      For example:
      v.   0.23  -> 002300 = 2300
      v   0.23.1 -> 002301 = 2301
      v. 10.23.2 -> 102302         */
   int major_version = 0;
   int minor_version = 0;
   int micro_version = 0;
 #ifdef LIBMESH_MAJOR_VERSION
   major_version = LIBMESH_MAJOR_VERSION;
 #endif
 #ifdef LIBMESH_MINOR_VERSION
   minor_version = LIBMESH_MINOR_VERSION;
 #endif
 #ifdef LIBMESH_MICRO_VERSION
   micro_version = LIBMESH_MICRO_VERSION;
 #endif
   return major_version*10000 + minor_version*100 + micro_version;
 }
libMesh::processor_id_type libMesh::global_n_processors () inline
Returns
the number of processors libMesh was initialized with.
Definition at line 104 of file libmesh_base.h.
References libMesh::libMeshPrivateData::_n_processors.
Referenced by libMesh::PerfLog::get_info_header(), n_processors(), libMesh::MacroFunctions::report_error(), and libMesh::MacroFunctions::stop().
 {
 #ifdef LIBMESH_HAVE_MPI
   return libMeshPrivateData::_n_processors;
 #else
   return 1;
 #endif
 }
libMesh::processor_id_type libMesh::global_processor_id () inline
Returns
the index of the local processor with respect to the original MPI pool libMesh was initialized with.
Definition at line 114 of file libmesh_base.h.
References libMesh::libMeshPrivateData::_processor_id.
Referenced by libMesh::PerfLog::get_info_header(), libMesh::MacroFunctions::here(), if(), processor_id(), and write_traceout().
 {
 #ifdef LIBMESH_HAVE_MPI
   return libMeshPrivateData::_processor_id;
 #else
   return 0;
 #endif
 }
libMesh::if (solution_vector &&solution_vector! = system.solution.get())
Definition at line 231 of file exact_error_estimator.C.
References libMesh::NumericVector< T >::swap(), and sys.
     {
       NumericVector<Number> * newsol =
         const_cast<NumericVector<Number> *>(solution_vector);
       System & sys = const_cast<System &>(system);
       newsol->swap(*sys.solution);
       sys.update();
     }
libMesh::if (libMesh::libMeshPrivateData::_n_threads! = 1)
Definition at line 364 of file libmesh.C.
       {
         libMesh::libMeshPrivateData::_n_threads = 1;
         libmesh_warning("Warning: You requested --n-threads>1 but no threading model is active!\n"
                         << "Forcing --n-threads==1 instead!");
       }
libMesh::if (!libMesh:: on_command_line"--disable-mpi")
Definition at line 390 of file libmesh.C.
References libMesh::libMeshPrivateData::_n_processors, libMesh::libMeshPrivateData::_processor_id, comm, COMM_WORLD, GLOBAL_COMM_WORLD, libMesh_MPI_Handler(), n_threads, and on_command_line().
     {
       // Check whether the calling program has already initialized
       // MPI, and avoid duplicate Init/Finalize
       int flag;
       MPI_Initialized (&flag);
       if (!flag)
         {
 #if MPI_VERSION > 1
           int mpi_thread_provided;
           const int mpi_thread_requested = libMesh::n_threads() > 1 ?
             MPI_THREAD_FUNNELED :
             MPI_THREAD_SINGLE;
           MPI_Init_thread (&argc, const_cast<char ***>(&argv),
                            mpi_thread_requested, &mpi_thread_provided);
           if ((libMesh::n_threads() > 1) &&
               (mpi_thread_provided < MPI_THREAD_FUNNELED))
             {
               libmesh_warning("Warning: MPI failed to guarantee MPI_THREAD_FUNNELED\n"
                               << "for a threaded run.\n"
                               << "Be sure your library is funneled-thread-safe..."
                               << std::endl);
               // Ideally, if an MPI stack tells us it's unsafe for us
               // to use threads, we shouldn't use threads.
               // In practice, we've encountered one MPI stack (an
               // mvapich2 configuration) that returned
               // MPI_THREAD_SINGLE as a proper warning, two stacks
               // that handle MPI_THREAD_FUNNELED properly, and two
               // current stacks plus a couple old stacks that return
               // MPI_THREAD_SINGLE but support libMesh threaded runs
               // anyway.
               // libMesh::libMeshPrivateData::_n_threads = 1;
               // task_scheduler.reset (new Threads::task_scheduler_init(libMesh::n_threads()));
             }
 #else
           if (libMesh::libMeshPrivateData::_n_threads > 1)
             {
               libmesh_warning("Warning: using MPI1 for threaded code.\n" <<
                               "Be sure your library is funneled-thread-safe..." <<
                               std::endl);
             }
           MPI_Init (&argc, const_cast<char ***>(&argv));
 #endif
           libmesh_initialized_mpi = true;
         }
       // Duplicate the input communicator for internal use
       // And get a Parallel::Communicator copy too, to use
       // as a default for that API
       this->_comm = COMM_WORLD_IN;
       libMesh::GLOBAL_COMM_WORLD = COMM_WORLD_IN;
 #ifndef LIBMESH_DISABLE_COMMWORLD
       libMesh::COMM_WORLD = COMM_WORLD_IN;
       Parallel::Communicator_World = COMM_WORLD_IN;
 #endif
       //MPI_Comm_set_name not supported in at least SGI MPT's MPI implementation
       //MPI_Comm_set_name (libMesh::COMM_WORLD, "libMesh::COMM_WORLD");
       libMeshPrivateData::_processor_id =
         cast_int<processor_id_type>(this->comm().rank());
       libMeshPrivateData::_n_processors =
         cast_int<processor_id_type>(this->comm().size());
       // Set up an MPI error handler if requested.  This helps us get
       // into a debugger with a proper stack when an MPI error occurs.
       if (libMesh::on_command_line ("--handle-mpi-errors"))
         {
 #if MPI_VERSION > 1
           MPI_Comm_create_errhandler(libMesh_MPI_Handler, &libmesh_errhandler);
           MPI_Comm_set_errhandler(libMesh::GLOBAL_COMM_WORLD, libmesh_errhandler);
           MPI_Comm_set_errhandler(MPI_COMM_WORLD, libmesh_errhandler);
 #else
           MPI_Errhandler_create(libMesh_MPI_Handler, &libmesh_errhandler);
           MPI_Errhandler_set(libMesh::GLOBAL_COMM_WORLD, libmesh_errhandler);
           MPI_Errhandler_set(MPI_COMM_WORLD, libmesh_errhandler);
 #endif // #if MPI_VERSION > 1
         }
     }
libMesh::if (!libMesh::on_command_line("--disable-petsc")#if defined(LIBMESH_HAVE_MPI)&&!libMesh::on_command_line("--disable-mpi")# endif)
Definition at line 492 of file libmesh.C.
References CHKERRABORT(), DMCreate_libMesh(), GLOBAL_COMM_WORLD, ierr, and libmesh_nullptr.
     {
       int ierr=0;
       PETSC_COMM_WORLD = libMesh::GLOBAL_COMM_WORLD;
       // Check whether the calling program has already initialized
       // PETSc, and avoid duplicate Initialize/Finalize
       PetscBool petsc_already_initialized;
       ierr = PetscInitialized(&petsc_already_initialized);
       CHKERRABORT(libMesh::GLOBAL_COMM_WORLD,ierr);
       if (petsc_already_initialized != PETSC_TRUE)
         libmesh_initialized_petsc = true;
 # if defined(LIBMESH_HAVE_SLEPC)
       // If SLEPc allows us to check whether the calling program
       // has already initialized it, we do that, and avoid
       // duplicate Initialize/Finalize.
       // We assume that SLEPc will handle PETSc appropriately,
       // which it does in the versions we've checked.
       if (!SlepcInitializeCalled)
         {
           ierr = SlepcInitialize  (&argc, const_cast<char ***>(&argv), libmesh_nullptr, libmesh_nullptr);
           CHKERRABORT(libMesh::GLOBAL_COMM_WORLD,ierr);
           libmesh_initialized_slepc = true;
         }
 # else
       if (libmesh_initialized_petsc)
         {
           ierr = PetscInitialize (&argc, const_cast<char ***>(&argv), libmesh_nullptr, libmesh_nullptr);
           CHKERRABORT(libMesh::GLOBAL_COMM_WORLD,ierr);
         }
 # endif
 #if !PETSC_RELEASE_LESS_THAN(3,3,0)
       // Register the reference implementation of DMlibMesh
 #if PETSC_RELEASE_LESS_THAN(3,4,0)
       ierr = DMRegister(DMLIBMESH, PETSC_NULL, "DMCreate_libMesh", DMCreate_libMesh); CHKERRABORT(libMesh::GLOBAL_COMM_WORLD,ierr);
 #else
       ierr = DMRegister(DMLIBMESH, DMCreate_libMesh); CHKERRABORT(libMesh::GLOBAL_COMM_WORLD,ierr);
 #endif
 #endif
     }
if (!libMesh::on_command_line ("--sync-with-stdio")) std libMesh::if (libMesh:: on_command_line"--separate-libmeshout")
Definition at line 563 of file libmesh.C.
References err, and out.
     {
       // Redirect.  We'll share streambufs with cout/cerr for now, but
       // presumably anyone using this option will want to replace the
       // bufs later.
       std::ostream * newout = new std::ostream(std::cout.rdbuf());
       libMesh::out = *newout;
       std::ostream * newerr = new std::ostream(std::cerr.rdbuf());
       libMesh::err = *newerr;
     }
libMesh::if (libMesh:: on_command_line"--redirect-stdout")
Definition at line 578 of file libmesh.C.
References err, global_processor_id(), out, and libMesh::BasicOStreamProxy< charT, traits >::rdbuf().
     {
       std::ostringstream filename;
       filename << "stdout.processor." << libMesh::global_processor_id();
       _ofstream.reset (new std::ofstream (filename.str().c_str()));
       // Redirect, saving the original streambufs!
       out_buf = libMesh::out.rdbuf (_ofstream->rdbuf());
       err_buf = libMesh::err.rdbuf (_ofstream->rdbuf());
     }
libMesh::if (libMesh::global_processor_id()! = 0)
Definition at line 591 of file libmesh.C.
 {
   // We can't delete, finalize, etc. more than once without
   // reinitializing in between
   libmesh_exceptionless_assert(!libMesh::closed());
   // Delete reference counted singleton(s)
   Singleton::cleanup();
   // Clear the thread task manager we started
   task_scheduler.reset();
   // Let's be sure we properly close on every processor at once:
   libmesh_parallel_only(this->comm());
   // Force the \p ReferenceCounter to print
   // its reference count information.  This allows
   // us to find memory leaks.  By default the
   // \p ReferenceCounter only prints its information
   // when the last created object has been destroyed.
   // That does no good if we are leaking memory!
   ReferenceCounter::print_info ();
   // Print an informative message if we detect a memory leak
   if (ReferenceCounter::n_objects() != 0)
     {
       libMesh::err << "Memory leak detected!"
                    << std::endl;
 #if !defined(LIBMESH_ENABLE_REFERENCE_COUNTING) || defined(NDEBUG)
       libMesh::err << "Compile in DEBUG mode with --enable-reference-counting"
                    << std::endl
                    << "for more information"
                    << std::endl;
 #endif
     }
   //  print the perflog to individual processor's file.
   libMesh::perflog.print_log();
   // Now clear the logging object, we don't want it to print
   // a second time during the PerfLog destructor.
   libMesh::perflog.clear();
   // Reconnect the output streams
   // (don't do this, or we will get messages from objects
   //  that go out of scope after the following return)
   //std::cout.rdbuf(std::cerr.rdbuf());
   // Set the initialized() flag to false
   libMeshPrivateData::_is_initialized = false;
   if (libMesh::on_command_line ("--redirect-stdout"))
     {
       // If stdout/stderr were redirected to files, reset them now.
       libMesh::out.rdbuf (out_buf);
       libMesh::err.rdbuf (err_buf);
     }
   // If we built our own output streams, we want to clean them up.
   if (libMesh::on_command_line ("--separate-libmeshout"))
     {
       delete libMesh::out.get();
       delete libMesh::err.get();
       libMesh::out.reset(std::cout);
       libMesh::err.reset(std::cerr);
     }
 #ifdef LIBMESH_ENABLE_EXCEPTIONS
   // Reset the old terminate handler; maybe the user code wants to
   // keep doing C++ stuff after closing libMesh stuff.
   std::set_terminate(old_terminate_handler);
 #endif
   if (libMesh::on_command_line("--enable-fpe"))
     libMesh::enableFPE(false);
 #if defined(LIBMESH_HAVE_PETSC)
   // Allow the user to bypass PETSc finalization
   if (!libMesh::on_command_line ("--disable-petsc")
 #if defined(LIBMESH_HAVE_MPI)
       && !libMesh::on_command_line ("--disable-mpi")
 #endif
       )
     {
 # if defined(LIBMESH_HAVE_SLEPC)
       if (libmesh_initialized_slepc)
         SlepcFinalize();
 # else
       if (libmesh_initialized_petsc)
         PetscFinalize();
 # endif
     }
 #endif
 #if defined(LIBMESH_HAVE_MPI)
   // Allow the user to bypass MPI finalization
   if (!libMesh::on_command_line ("--disable-mpi"))
     {
       this->_comm.clear();
 #ifndef LIBMESH_DISABLE_COMMWORLD
       Parallel::Communicator_World.clear();
 #endif
       if (libmesh_initialized_mpi)
         MPI_Finalize();
     }
 #endif
 }
libMesh::if (_elemlinks)
Definition at line 1429 of file elem.h.
References libmesh_nullptr.
     {
       _elemlinks[0] = p;
       for (unsigned int n=1; n<ns+1; n++)
         _elemlinks[n] = libmesh_nullptr;
     }
libMesh::if (this->parent()! = libmesh_nullptr)
Definition at line 1438 of file elem.h.
References processor_id().
     {
       this->subdomain_id() = this->parent()->subdomain_id();
       this->processor_id() = this->parent()->processor_id();
     }
libMesh::if (this-> parent()) -> set_p_level(this->parent() ->p_level())
const Number libMesh::imaginary (0. , 1.)
bool libMesh::initialized ()
Checks that library initialization has been done. If it hasn't an error message is printed and the code aborts. It is useful to libmesh_assert(libMesh::initialized()) in library object constructors.
Definition at line 261 of file libmesh.C.
References libMesh::libMeshPrivateData::_is_initialized.
Referenced by libMesh::EigenSparseLinearSolver< T >::clear(), libMesh::AztecLinearSolver< T >::clear(), libMesh::LaspackLinearSolver< T >::clear(), libMesh::SlepcEigenSolver< T >::clear(), libMesh::TaoOptimizationSolver< T >::clear(), libMesh::PetscNonlinearSolver< T >::clear(), libMesh::NloptOptimizationSolver< T >::clear(), libMesh::PetscLinearSolver< T >::clear(), libMesh::NumericVector< T >::compare(), default_solver_package(), libMesh::TaoOptimizationSolver< T >::get_converged_reason(), libMesh::PetscNonlinearSolver< T >::get_converged_reason(), libMesh::NumericVector< T >::global_relative_compare(), libMesh::EigenSparseLinearSolver< T >::init(), libMesh::AztecLinearSolver< T >::init(), libMesh::LaspackLinearSolver< T >::init(), libMesh::SlepcEigenSolver< T >::init(), libMesh::NoxNonlinearSolver< T >::init(), libMesh::TaoOptimizationSolver< T >::init(), libMesh::PetscNonlinearSolver< T >::init(), libMesh::NloptOptimizationSolver< T >::init(), libMesh::PetscLinearSolver< T >::init(), libMesh::NumericVector< T >::local_relative_compare(), libMesh::MeshBase::MeshBase(), libMesh::SparseMatrix< T >::print(), libMesh::NumericVector< T >::print(), libMesh::NumericVector< T >::print_global(), and libMesh::UnstructuredMesh::UnstructuredMesh().
 {
   return libMeshPrivateData::_is_initialized;
 }
libMesh::INSTANTIATE_ALL_MAPS (0)
libMesh::INSTANTIATE_ALL_MAPS (1)
libMesh::INSTANTIATE_ALL_MAPS (2)
libMesh::INSTANTIATE_ALL_MAPS (3)
libMesh::INSTANTIATE_FE (0)
libMesh::INSTANTIATE_FE (1)
libMesh::INSTANTIATE_FE (2)
libMesh::INSTANTIATE_FE (3)
libMesh::INSTANTIATE_INF_FE (1 , CARTESIAN)
Collect all 1D explicit instantiations for class InfFE
libMesh::INSTANTIATE_INF_FE (2 , CARTESIAN)
Collect all 2D explicit instantiations for class InfFE
libMesh::INSTANTIATE_INF_FE (3 , CARTESIAN)
Collect all 3D explicit instantiations for class InfFE
libMesh::INSTANTIATE_INF_FE_MBRF (1 , CARTESIAN , Elem * , Base:: build_elemconst Elem *)
libMesh::INSTANTIATE_INF_FE_MBRF (2 , CARTESIAN , Elem * , Base:: build_elemconst Elem *)
libMesh::INSTANTIATE_INF_FE_MBRF (3 , CARTESIAN , Elem * , Base:: build_elemconst Elem *)
libMesh::INSTANTIATE_INF_FE_MBRF (1 , CARTESIAN , ElemType , Base:: get_elem_typeconst ElemType type)
libMesh::INSTANTIATE_INF_FE_MBRF (2 , CARTESIAN , ElemType , Base:: get_elem_typeconst ElemType type)
libMesh::INSTANTIATE_INF_FE_MBRF (3 , CARTESIAN , ElemType , Base:: get_elem_typeconst ElemType type)
libMesh::INSTANTIATE_INF_FE_MBRF (1 , CARTESIAN , unsigned int, Base:: n_base_mapping_sfconst ElemType, const Order)
libMesh::INSTANTIATE_INF_FE_MBRF (2 , CARTESIAN , unsigned int, Base:: n_base_mapping_sfconst ElemType, const Order)
libMesh::INSTANTIATE_INF_FE_MBRF (3 , CARTESIAN , unsigned int, Base:: n_base_mapping_sfconst ElemType, const Order)
libMesh::INSTANTIATE_INF_FE_MBRF (1 , CARTESIAN , unsigned int, Radial:: n_dofs_at_nodeconst Order, const unsigned int)
libMesh::INSTANTIATE_INF_FE_MBRF (2 , CARTESIAN , unsigned int, Radial:: n_dofs_at_nodeconst Order, const unsigned int)
libMesh::INSTANTIATE_INF_FE_MBRF (3 , CARTESIAN , unsigned int, Radial:: n_dofs_at_nodeconst Order, const unsigned int)
libMesh::INSTANTIATE_INF_FE_MBRF (1 , CARTESIAN , void , reinit(const Elem *, const unsigned int, const Real, const std::vector< Point > *const, const std::vector< Real > *const))
libMesh::INSTANTIATE_INF_FE_MBRF (2 , CARTESIAN , void , reinit(const Elem *, const unsigned int, const Real, const std::vector< Point > *const, const std::vector< Real > *const))
libMesh::INSTANTIATE_INF_FE_MBRF (3 , CARTESIAN , void , reinit(const Elem *, const unsigned int, const Real, const std::vector< Point > *const, const std::vector< Real > *const))
libMesh::INSTANTIATE_INF_FE_MBRF (1 , CARTESIAN , void , edge_reinit(const Elem *, const unsigned int, const Real, const std::vector< Point > *const, const std::vector< Real > *const))
libMesh::INSTANTIATE_INF_FE_MBRF (2 , CARTESIAN , void , edge_reinit(const Elem *, const unsigned int, const Real, const std::vector< Point > *const, const std::vector< Real > *const))
libMesh::INSTANTIATE_INF_FE_MBRF (3 , CARTESIAN , void , edge_reinit(const Elem *, const unsigned int, const Real, const std::vector< Point > *const, const std::vector< Real > *const))
libMesh::INSTANTIATE_INF_FE_MBRF (1 , CARTESIAN , void , init_face_shape_functions(const std::vector< Point > &, const Elem *))
libMesh::INSTANTIATE_INF_FE_MBRF (2 , CARTESIAN , void , init_face_shape_functions(const std::vector< Point > &, const Elem *))
libMesh::INSTANTIATE_INF_FE_MBRF (3 , CARTESIAN , void , init_face_shape_functions(const std::vector< Point > &, const Elem *))
libMesh::INSTANTIATE_INF_FE_MBRF (1 , CARTESIAN , Point , inverse_map(const Elem *, const Point &, const Real, const bool, const bool))
libMesh::INSTANTIATE_INF_FE_MBRF (2 , CARTESIAN , Point , inverse_map(const Elem *, const Point &, const Real, const bool, const bool))
libMesh::INSTANTIATE_INF_FE_MBRF (3 , CARTESIAN , Point , inverse_map(const Elem *, const Point &, const Real, const bool, const bool))
libMesh::INSTANTIATE_INF_FE_MBRF (1 , CARTESIAN , void , inverse_map(const Elem *, const std::vector< Point > &, std::vector< Point > &, const Real, const bool))
libMesh::INSTANTIATE_INF_FE_MBRF (2 , CARTESIAN , void , inverse_map(const Elem *, const std::vector< Point > &, std::vector< Point > &, const Real, const bool))
libMesh::INSTANTIATE_INF_FE_MBRF (3 , CARTESIAN , void , inverse_map(const Elem *, const std::vector< Point > &, std::vector< Point > &, const Real, const bool))
libMesh::INSTANTIATE_INF_FE_MBRF (1 , CARTESIAN , unsigned int, n_dofs(const FEType &, const ElemType))
libMesh::INSTANTIATE_INF_FE_MBRF (2 , CARTESIAN , unsigned int, n_dofs(const FEType &, const ElemType))
libMesh::INSTANTIATE_INF_FE_MBRF (3 , CARTESIAN , unsigned int, n_dofs(const FEType &, const ElemType))
libMesh::INSTANTIATE_INF_FE_MBRF (1 , CARTESIAN , unsigned int, n_dofs_per_elem(const FEType &, const ElemType))
libMesh::INSTANTIATE_INF_FE_MBRF (2 , CARTESIAN , unsigned int, n_dofs_per_elem(const FEType &, const ElemType))
libMesh::INSTANTIATE_INF_FE_MBRF (3 , CARTESIAN , unsigned int, n_dofs_per_elem(const FEType &, const ElemType))
libMesh::INSTANTIATE_INF_FE_MBRF (1 , CARTESIAN , unsigned int, n_dofs_at_node(const FEType &, const ElemType, const unsigned int))
libMesh::INSTANTIATE_INF_FE_MBRF (2 , CARTESIAN , unsigned int, n_dofs_at_node(const FEType &, const ElemType, const unsigned int))
libMesh::INSTANTIATE_INF_FE_MBRF (3 , CARTESIAN , unsigned int, n_dofs_at_node(const FEType &, const ElemType, const unsigned int))
libMesh::INSTANTIATE_INF_FE_MBRF (1 , CARTESIAN , void , compute_shape_indices(const FEType &, const ElemType, const unsigned int, unsigned int &, unsigned int &))
libMesh::INSTANTIATE_INF_FE_MBRF (2 , CARTESIAN , void , compute_shape_indices(const FEType &, const ElemType, const unsigned int, unsigned int &, unsigned int &))
libMesh::INSTANTIATE_INF_FE_MBRF (3 , CARTESIAN , void , compute_shape_indices(const FEType &, const ElemType, const unsigned int, unsigned int &, unsigned int &))
libMesh::INSTANTIATE_INF_FE_MBRF (1 , CARTESIAN , void , compute_node_indices(const ElemType, const unsigned int, unsigned int &, unsigned int &))
libMesh::INSTANTIATE_INF_FE_MBRF (2 , CARTESIAN , void , compute_node_indices(const ElemType, const unsigned int, unsigned int &, unsigned int &))
libMesh::INSTANTIATE_INF_FE_MBRF (3 , CARTESIAN , void , compute_node_indices(const ElemType, const unsigned int, unsigned int &, unsigned int &))
libMesh::INSTANTIATE_INF_FE_MBRF (1 , CARTESIAN , Real , shape(const FEType &, const Elem *, const unsigned int, const Point &p))
libMesh::INSTANTIATE_INF_FE_MBRF (2 , CARTESIAN , Real , shape(const FEType &, const Elem *, const unsigned int, const Point &p))
libMesh::INSTANTIATE_INF_FE_MBRF (3 , CARTESIAN , Real , shape(const FEType &, const Elem *, const unsigned int, const Point &p))
libMesh::INSTANTIATE_INF_FE_MBRF (1 , CARTESIAN , Real , shape(const FEType &, const ElemType, const unsigned int, const Point &))
libMesh::INSTANTIATE_INF_FE_MBRF (2 , CARTESIAN , Real , shape(const FEType &, const ElemType, const unsigned int, const Point &))
libMesh::INSTANTIATE_INF_FE_MBRF (3 , CARTESIAN , Real , shape(const FEType &, const ElemType, const unsigned int, const Point &))
libMesh::INSTANTIATE_INF_FE_MBRF (1 , CARTESIAN , void , compute_data(const FEType &, const Elem *, FEComputeData &))
libMesh::INSTANTIATE_INF_FE_MBRF (2 , CARTESIAN , void , compute_data(const FEType &, const Elem *, FEComputeData &))
libMesh::INSTANTIATE_INF_FE_MBRF (3 , CARTESIAN , void , compute_data(const FEType &, const Elem *, FEComputeData &))
libMesh::INSTANTIATE_INF_FE_MBRF (1 , CARTESIAN , void , nodal_soln(const FEType &, const Elem *, const std::vector< Number > &, std::vector< Number > &))
libMesh::INSTANTIATE_INF_FE_MBRF (2 , CARTESIAN , void , nodal_soln(const FEType &, const Elem *, const std::vector< Number > &, std::vector< Number > &))
libMesh::INSTANTIATE_INF_FE_MBRF (3 , CARTESIAN , void , nodal_soln(const FEType &, const Elem *, const std::vector< Number > &, std::vector< Number > &))
bool libMesh::is_between (Real min, Real check, Real max)
Definition at line 239 of file mesh_tools.C.
References std::max().
Referenced by libMesh::MeshTools::BoundingBox::contains_point(), and libMesh::MeshTools::BoundingBox::intersect().
 {
   return min <= check && check <= max;
 }
PetscMatrix<Number> libMesh::J_input (pc , sys. comm())
PetscErrorCode Vec Mat Mat void* ctx libMesh::libmesh_assert (x)
libMesh::libmesh_assert (j)
libMesh::libmesh_assert (ctx)
libMesh::libmesh_assert (remote_elem)
Referenced by __libmesh_nlopt_equality_constraints(), __libmesh_nlopt_inequality_constraints(), __libmesh_nlopt_objective(), __libmesh_petsc_diff_solver_residual(), __libmesh_petsc_snes_jacobian(), __libmesh_petsc_snes_postcheck(), __libmesh_petsc_snes_residual(), __libmesh_tao_equality_constraints(), __libmesh_tao_equality_constraints_jacobian(), __libmesh_tao_gradient(), __libmesh_tao_hessian(), __libmesh_tao_inequality_constraints(), __libmesh_tao_inequality_constraints_jacobian(), __libmesh_tao_objective(), libMesh::MeshRefinement::_coarsen_elements(), libMesh::ExactSolution::_compute_error(), libMesh::PetscLinearSolver< T >::_create_complement_is(), libMesh::FEMContext::_do_elem_position_set(), libMesh::MetisPartitioner::_do_partition(), libMesh::DofMap::_dof_indices(), libMesh::UniformRefinementEstimator::_estimate_error(), libMesh::DenseMatrix< T >::_evd_lapack(), libMesh::BoundaryInfo::_find_id_maps(), libMesh::SteadySolver::_general_residual(), libMesh::EquationSystems::_read_impl(), libMesh::GMVIO::_read_one_cell(), libMesh::PetscLinearSolver< T >::_restrict_solve_to_is_local_size(), libMesh::Elem::active_family_tree(), libMesh::Elem::active_family_tree_by_neighbor(), libMesh::Elem::active_family_tree_by_side(), libMesh::MeshTools::Subdivision::add_boundary_ghosts(), libMesh::GMVIO::add_cell_centered_data(), libMesh::Elem::add_child(), libMesh::BoundaryInfo::add_edge(), libMesh::SerialMesh::add_elem(), libMesh::ParallelMesh::add_elem(), libMesh::MeshRefinement::add_elem(), libMesh::BoundaryInfo::add_elements(), libMesh::MeshData::add_foreign_elem_id(), libMesh::MeshData::add_foreign_node_id(), libMesh::SerialMesh::add_node(), libMesh::BoundaryInfo::add_node(), libMesh::ParallelMesh::add_node(), libMesh::MeshRefinement::add_node(), libMesh::DofMap::add_periodic_boundary(), libMesh::SerialMesh::add_point(), libMesh::ParallelMesh::add_point(), libMesh::Parallel::Request::add_prior_request(), libMesh::HPCoarsenTest::add_projection(), libMesh::EnsightIO::add_scalar(), libMesh::BoundaryInfo::add_side(), libMesh::ImplicitSystem::add_system_matrix(), libMesh::ExplicitSystem::add_system_rhs(), libMesh::System::add_variable(), libMesh::System::add_variables(), libMesh::EnsightIO::add_vector(), libMesh::NumericVector< T >::add_vector(), libMesh::EquationSystems::adjoint_solve(), libMesh::UnstructuredMesh::all_first_order(), libMesh::UnstructuredMesh::all_second_order(), libMesh::MeshTools::Modification::all_tri(), libMesh::Parallel::Communicator::allgather(), libMesh::Parallel::Communicator::allgather_packed_range(), libMesh::DofMap::allgather_recursive_constraints(), libMesh::Parallel::Communicator::alltoall(), libMesh::AnalyticFunction< Output >::AnalyticFunction(), libMesh::Elem::ancestor(), libMesh::Utility::do_pow< N, T >::apply(), libMesh::ImplicitSystem::assemble(), libMesh::FrequencySystem::assemble(), libMesh::FEMSystem::assembly(), libMesh::NonlinearImplicitSystem::assembly(), libMesh::MeshData::assign(), libMesh::MeshCommunication::assign_global_indices(), libMesh::ParmetisPartitioner::assign_partitioning(), libMesh::System::attach_assemble_function(), libMesh::System::attach_constraint_function(), libMesh::ExactSolution::attach_exact_deriv(), libMesh::ExactErrorEstimator::attach_exact_deriv(), libMesh::ExactSolution::attach_exact_hessian(), libMesh::ExactErrorEstimator::attach_exact_hessian(), libMesh::System::attach_init_function(), libMesh::DofMap::attach_matrix(), libMesh::System::attach_QOI_derivative(), libMesh::System::attach_QOI_function(), libMesh::FE< Dim, T >::attach_quadrature_rule(), libMesh::InfFE< Dim, T_radial, T_map >::attach_quadrature_rule(), libMesh::FESubdivision::attach_quadrature_rule(), libMesh::ExactSolution::attach_reference_solution(), libMesh::ExactErrorEstimator::attach_reference_solution(), libMesh::FrequencySystem::attach_solve_function(), libMesh::Parallel::BinSorter< KeyType, IdxType >::BinSorter(), libMesh::Threads::BoolAcquire::BoolAcquire(), libMesh::BoundaryInfo::boundary_ids(), libMesh::BoundaryProjectSolution::BoundaryProjectSolution(), libMesh::TreeNode< N >::bounds_node(), libMesh::Parallel::Communicator::broadcast(), libMesh::Patch::build_around_element(), libMesh::DofMap::build_constraint_matrix(), libMesh::DofMap::build_constraint_matrix_and_vector(), libMesh::FEMSystem::build_context(), libMesh::MeshTools::Generation::build_cube(), libMesh::EquationSystems::build_discontinuous_solution_vector(), libMesh::Nemesis_IO_Helper::build_element_and_node_maps(), libMesh::MeshTools::Generation::build_extrusion(), libMesh::ParmetisPartitioner::build_graph(), libMesh::FEMContext::build_new_fe(), libMesh::EquationSystems::build_solution_vector(), libMesh::DofMap::build_sparsity(), libMesh::System::calculate_norm(), libMesh::OldSolutionValue< Output, point_output >::check_old_context(), libMesh::Elem::child(), libMesh::Singleton::cleanup(), libMesh::Parallel::Request::cleanup(), libMesh::Parallel::Communicator::clear(), libMesh::DofObject::clear_dofs(), libMesh::DofMap::clear_sparsity(), libMesh::Parameters::Parameter< T >::clone(), libMesh::MeshData::close_foreign_id_maps(), libMesh::Elem::coarsen(), libMesh::MeshRefinement::coarsen_elements(), libMesh::FEGenericBase< OutputType >::coarsened_dof_values(), libMesh::InfFE< Dim, T_radial, T_map >::combine_base_radial(), command_line_next(), command_line_value(), command_line_vector(), libMesh::Xdr::comment(), libMesh::System::compare(), libMesh::NumericVector< T >::compare(), libMesh::WrappedFunction< Output >::component(), libMesh::FEMap::compute_affine_map(), libMesh::Nemesis_IO_Helper::compute_border_node_ids(), libMesh::FEInterface::compute_constraints(), libMesh::InfFE< Dim, T_radial, T_map >::compute_data(), libMesh::FEMap::compute_edge_map(), libMesh::ExactSolution::compute_error(), libMesh::FEXYZMap::compute_face_map(), libMesh::FEMap::compute_face_map(), libMesh::FEXYZ< Dim >::compute_face_values(), libMesh::Elem::compute_key(), libMesh::FEMap::compute_map(), libMesh::FEAbstract::compute_node_constraints(), libMesh::FEGenericBase< OutputType >::compute_periodic_constraints(), libMesh::FEAbstract::compute_periodic_node_constraints(), libMesh::FEGenericBase< OutputType >::compute_proj_constraints(), libMesh::InfFE< Dim, T_radial, T_map >::compute_shape_functions(), libMesh::FEXYZ< Dim >::compute_shape_functions(), libMesh::FEMap::compute_single_point_map(), libMesh::DofMap::constrain_element_dyad_matrix(), libMesh::DofMap::constrain_element_matrix(), libMesh::DofMap::constrain_element_matrix_and_vector(), libMesh::DofMap::constrain_element_vector(), libMesh::UnstructuredMesh::contract(), libMesh::Elem::contract(), libMesh::GMVIO::copy_nodal_solution(), libMesh::UnstructuredMesh::copy_nodes_and_elements(), libMesh::vectormap< dof_id_type, dof_id_type >::count(), libMesh::DofMap::create_dof_constraints(), libMesh::MeshRefinement::create_parent_error_vector(), libMesh::UnstructuredMesh::create_submesh(), libMesh::ElemCutter::cut_2D(), libMesh::ElemCutter::cut_3D(), libMesh::Xdr::data(), libMesh::Xdr::data_stream(), libMesh::XdrMGF::dataBlk(), libMesh::ParameterVector::deep_resize(), default_solver_package(), libMesh::SerialMesh::delete_elem(), libMesh::ParallelMesh::delete_elem(), libMesh::SerialMesh::delete_node(), libMesh::ParallelMesh::delete_node(), libMesh::MeshCommunication::delete_remote_elements(), libMesh::Parallel::Communicator::dereference_unique_tag(), libMesh::DGFEMContext::DGFEMContext(), libMesh::DirichletBoundary::DirichletBoundary(), libMesh::MeshFunction::disable_out_of_mesh_mode(), libMesh::MeshTools::Modification::distort(), libMesh::DofMap::distribute_dofs(), libMesh::DofMap::distribute_local_dofs_node_major(), libMesh::DofMap::distribute_local_dofs_var_major(), DMlibMeshFunction(), libMesh::Xdr::do_read(), libMesh::Xdr::do_write(), libMesh::DofMap::dof_indices(), libMesh::FE< Dim, T >::dofs_on_edge(), libMesh::FE< Dim, T >::dofs_on_side(), libMesh::BoundaryInfo::edge_boundary_ids(), libMesh::FE< Dim, T >::edge_reinit(), libMesh::SerialMesh::elem(), libMesh::ParallelMesh::elem(), libMesh::FEMContext::elem_fe_reinit(), libMesh::FEMContext::elem_position_get(), libMesh::MeshData::elem_to_foreign_id(), libMesh::TetGenIO::element_in(), libMesh::AdaptiveTimeSolver::element_residual(), libMesh::EigenTimeSolver::element_residual(), libMesh::UNVIO::elements_out(), libMesh::MeshRefinement::eliminate_unrefined_patches(), libMesh::MeshFunction::enable_out_of_mesh_mode(), libMesh::DofMap::enforce_adjoint_constraints_exactly(), libMesh::DofMap::enforce_constraints_exactly(), libMesh::ExactSolution::error_norm(), libMesh::AdaptiveTimeSolver::error_order(), libMesh::AdjointRefinementEstimator::estimate_error(), libMesh::AdjointResidualErrorEstimator::estimate_error(), libMesh::ParsedFEMFunction< Output >::eval_args(), libMesh::DofMap::extract_local_vector(), libMesh::Factory< Base >::Factory(), libMesh::Elem::family_tree(), libMesh::Elem::family_tree_by_neighbor(), libMesh::Elem::family_tree_by_side(), libMesh::Elem::family_tree_by_subneighbor(), libMesh::FEMContext::FEMContext(), libMesh::DofMap::find_connected_dofs(), libMesh::Elem::find_edge_neighbors(), libMesh::TreeNode< N >::find_element_in_children(), libMesh::MeshCommunication::find_global_indices(), libMesh::Elem::find_interior_neighbors(), libMesh::ElemCutter::find_intersection_points(), libMesh::UnstructuredMesh::find_neighbors(), libMesh::MeshTools::find_nodal_neighbors(), libMesh::MeshTools::Subdivision::find_one_ring(), libMesh::Elem::find_point_neighbors(), libMesh::MemorySolutionHistory::find_stored_entry(), libMesh::MeshRefinement::flag_elements_by_nelem_target(), libMesh::MeshData::foreign_id_to_elem(), libMesh::MeshData::foreign_id_to_node(), libMesh::Parallel::Communicator::gather(), libMesh::ParameterPointer< T >::get(), libMesh::ParameterMultiPointer< T >::get(), libMesh::ParameterMultiAccessor< T >::get(), libMesh::Parameters::get(), libMesh::ReferenceElem::get(), libMesh::FEGenericBase< FEOutputType< T >::type >::get_curl_phi(), libMesh::FEGenericBase< FEOutputType< T >::type >::get_d2phi(), libMesh::FEGenericBase< FEOutputType< T >::type >::get_d2phideta2(), libMesh::FEGenericBase< FEOutputType< T >::type >::get_d2phidetadzeta(), libMesh::FEGenericBase< FEOutputType< T >::type >::get_d2phidx2(), libMesh::FEGenericBase< FEOutputType< T >::type >::get_d2phidxdy(), libMesh::FEGenericBase< FEOutputType< T >::type >::get_d2phidxdz(), libMesh::FEGenericBase< FEOutputType< T >::type >::get_d2phidxi2(), libMesh::FEGenericBase< FEOutputType< T >::type >::get_d2phidxideta(), libMesh::FEGenericBase< FEOutputType< T >::type >::get_d2phidxidzeta(), libMesh::FEGenericBase< FEOutputType< T >::type >::get_d2phidy2(), libMesh::FEGenericBase< FEOutputType< T >::type >::get_d2phidydz(), libMesh::FEGenericBase< FEOutputType< T >::type >::get_d2phidz2(), libMesh::FEGenericBase< FEOutputType< T >::type >::get_d2phidzeta2(), libMesh::MeshData::get_data(), libMesh::DiffContext::get_deltat_value(), libMesh::FEGenericBase< FEOutputType< T >::type >::get_div_phi(), libMesh::FEGenericBase< FEOutputType< T >::type >::get_dphi(), libMesh::FEGenericBase< FEOutputType< T >::type >::get_dphideta(), libMesh::FEGenericBase< FEOutputType< T >::type >::get_dphidx(), libMesh::FEGenericBase< FEOutputType< T >::type >::get_dphidxi(), libMesh::FEGenericBase< FEOutputType< T >::type >::get_dphidy(), libMesh::FEGenericBase< FEOutputType< T >::type >::get_dphidz(), libMesh::FEGenericBase< FEOutputType< T >::type >::get_dphidzeta(), libMesh::CondensedEigenSystem::get_eigenpair(), libMesh::FEMContext::get_elem(), libMesh::DiffContext::get_elem_fixed_solution(), libMesh::DiffContext::get_elem_jacobian(), libMesh::DiffContext::get_elem_residual(), libMesh::DiffContext::get_elem_solution(), libMesh::DiffContext::get_elem_solution_accel(), libMesh::DiffContext::get_elem_solution_rate(), libMesh::TetGenWrapper::get_element_attribute(), libMesh::FEMContext::get_element_fe(), libMesh::FEMContext::get_element_qrule(), libMesh::DofMap::get_info(), libMesh::ParsedFunction< Output, OutputGradient >::get_inline_value(), libMesh::ParsedFEMFunction< Output >::get_inline_value(), libMesh::DifferentiableSystem::get_linear_solve_parameters(), libMesh::DifferentiableSystem::get_linear_solver(), libMesh::DiffContext::get_localized_subvector(), libMesh::DiffContext::get_localized_vector(), libMesh::EquationSystems::get_mesh_data(), libMesh::DofMap::get_n_nz(), libMesh::DofMap::get_n_oz(), libMesh::Elem::get_node(), libMesh::FEGenericBase< FEOutputType< T >::type >::get_phi(), libMesh::MeshFunction::get_point_locator(), libMesh::DenseMatrix< T >::get_principal_submatrix(), libMesh::DiffContext::get_qoi_derivatives(), libMesh::FEMContext::get_side_fe(), libMesh::FEMContext::get_side_qrule(), libMesh::EquationSystems::get_solution(), libMesh::DifferentiableSystem::get_time_solver(), libMesh::Parallel::Communicator::get_unique_tag(), libMesh::MeshData::get_unv_header(), libMesh::System::get_vector(), libMesh::NumericVector< T >::global_relative_compare(), libMesh::MeshFunction::gradient(), libMesh::MeshData::has_data(), libMesh::MeshRefinement::has_topological_neighbor(), libMesh::XdrSOLN::header(), libMesh::XdrMESH::header(), libMesh::MeshFunction::hessian(), libMesh::DofMap::heterogenously_constrain_element_matrix_and_vector(), libMesh::Parallel::Histogram< KeyType, IdxType >::Histogram(), libMesh::StatisticsVector< T >::histogram(), libMesh::DofObject::id(), libMesh::AdaptiveTimeSolver::init(), libMesh::AnalyticFunction< Output >::init(), libMesh::PointLocatorTree::init(), libMesh::PointLocatorList::init(), libMesh::MeshFunction::init(), libMesh::System::init(), libMesh::DifferentiableSystem::init_data(), libMesh::FEMap::init_edge_shape_functions(), libMesh::FEMap::init_face_shape_functions(), libMesh::InfFE< Dim, T_radial, T_map >::init_face_shape_functions(), libMesh::ImplicitSystem::init_matrices(), libMesh::InfFE< Dim, T_radial, T_map >::init_radial_shape_functions(), libMesh::InfFE< Dim, T_radial, T_map >::init_shape_functions(), libMesh::FESubdivision::init_shape_functions(), libMesh::FEXYZ< Dim >::init_shape_functions(), libMesh::ParmetisPartitioner::initialize(), libMesh::ContinuationSystem::initialize_tangent(), libMesh::TreeNode< N >::insert(), libMesh::NumericVector< T >::insert(), libMesh::MeshData::insert_elem_data(), libMesh::MeshData::insert_node_data(), libMesh::Elem::interior_parent(), libMesh::FE< Dim, T >::inverse_map(), libMesh::InfFE< Dim, T_radial, T_map >::inverse_map(), libMesh::ErrorVector::is_active_elem(), libMesh::SystemNorm::is_discrete(), libMesh::Xdr::is_eof(), libMesh::SparsityPattern::Build::join(), libMesh::DenseMatrix< T >::l1_norm(), libMesh::MeshTools::libmesh_assert_connected_nodes(), libMesh::MeshTools::libmesh_assert_no_links_to_elem(), libMesh::MeshTools::libmesh_assert_old_dof_objects(), libMesh::MeshTools::libmesh_assert_valid_amr_elem_ids(), libMesh::MeshTools::libmesh_assert_valid_amr_interior_parents(), libMesh::MeshTools::libmesh_assert_valid_elem_ids(), libMesh::MeshTools::libmesh_assert_valid_neighbors(), libMesh::Elem::libmesh_assert_valid_neighbors(), libMesh::MeshTools::libmesh_assert_valid_node_pointers(), libMesh::Elem::libmesh_assert_valid_node_pointers(), libMesh::ParallelMesh::libmesh_assert_valid_parallel_flags(), libMesh::ParallelMesh::libmesh_assert_valid_parallel_object_ids(), libMesh::ParallelMesh::libmesh_assert_valid_parallel_p_levels(), libMesh::MeshTools::libmesh_assert_valid_procids< Elem >(), libMesh::MeshTools::libmesh_assert_valid_procids< Node >(), libMesh::MeshTools::libmesh_assert_valid_refinement_flags(), libMesh::MeshTools::libmesh_assert_valid_refinement_tree(), libMesh::MeshTools::libmesh_assert_valid_remote_elems(), libMesh::MeshTools::libmesh_assert_valid_unique_ids(), libMesh::DenseMatrix< T >::linfty_norm(), libMesh::NumericVector< T >::local_relative_compare(), libMesh::DofMap::local_variable_indices(), libMesh::SumShellMatrix< T >::m(), libMesh::MeshRefinement::make_coarsening_compatible(), libMesh::Elem::make_links_to_me_local(), libMesh::Elem::make_links_to_me_remote(), libMesh::MeshRefinement::make_refinement_compatible(), libMesh::FE< Dim, T >::map(), libMesh::InfFE< Dim, T_radial, T_map >::map(), libMesh::FE< Dim, T >::map_eta(), libMesh::FE< Dim, T >::map_xi(), libMesh::FE< Dim, T >::map_zeta(), libMesh::libmesh_final< T >::mat(), libMesh::DenseSubVector< T >::max(), libMesh::DenseVector< T >::max(), libMesh::DenseMatrix< T >::max(), libMesh::Parallel::Communicator::max(), libMesh::DofMap::max_constraint_error(), libMesh::Elem::max_descendant_p_level(), libMesh::Parallel::Communicator::maxloc(), libMesh::MeshOutput< MT >::mesh(), libMesh::FEMSystem::mesh_position_set(), libMesh::MeshBase::MeshBase(), libMesh::DenseSubVector< T >::min(), libMesh::DenseVector< T >::min(), libMesh::DenseMatrix< T >::min(), libMesh::Parallel::Communicator::min(), libMesh::Elem::min_new_p_level_by_neighbor(), libMesh::Elem::min_p_level_by_neighbor(), libMesh::Parallel::Communicator::minloc(), libMesh::SumShellMatrix< T >::n(), libMesh::MeshData::n_elem_data(), libMesh::MeshBase::n_elem_on_proc(), libMesh::FrequencySystem::n_frequencies(), libMesh::MeshData::n_node_data(), libMesh::MeshBase::n_nodes_on_proc(), libMesh::QBase::n_points(), libMesh::FE< Dim, T >::n_quadrature_points(), libMesh::InfFE< Dim, T_radial, T_map >::n_quadrature_points(), libMesh::MeshData::n_val_per_elem(), libMesh::MeshData::n_val_per_node(), libMesh::PeriodicBoundaries::neighbor(), libMesh::InfFE< Dim, T_radial, T_map >::nodal_soln(), libMesh::FE< Dim, T >::nodal_soln(), libMesh::SerialMesh::node(), libMesh::Elem::node(), libMesh::ParallelMesh::node(), libMesh::TetGenIO::node_in(), libMesh::SerialMesh::node_ptr(), libMesh::ParallelMesh::node_ptr(), libMesh::MeshData::node_to_foreign_id(), libMesh::UNVIO::nodes_out(), libMesh::AdaptiveTimeSolver::nonlocal_residual(), libMesh::EigenTimeSolver::nonlocal_residual(), libMesh::DofMap::old_dof_indices(), on_command_line(), libMesh::Xdr::open(), libMesh::Predicates::abstract_multi_predicate< T >::operator()(), libMesh::WrappedFunction< Output >::operator()(), libMesh::GenericProjector< FFunctor, GFunctor, FValue, ProjectionAction >::operator()(), libMesh::PointLocatorList::operator()(), libMesh::AnalyticFunction< Output >::operator()(), libMesh::WeightedPatchRecoveryErrorEstimator::EstimateError::operator()(), libMesh::ElemCutter::operator()(), libMesh::SparsityPattern::Build::operator()(), libMesh::PointLocatorTree::operator()(), libMesh::MeshFunction::operator()(), libMesh::PatchRecoveryErrorEstimator::EstimateError::operator()(), libMesh::MeshData::operator()(), Pred< IterType, PredType >::operator()(), libMesh::BoundaryProjectSolution::operator()(), libMesh::Xdr::operator<<(), libMesh::ConstCouplingRow::operator==(), libMesh::ConstCouplingRowConstIterator::operator==(), libMesh::Xdr::operator>>(), libMesh::vectormap< dof_id_type, dof_id_type >::operator[](), libMesh::Hex::opposite_node(), libMesh::Edge::opposite_node(), libMesh::Quad::opposite_node(), libMesh::Parallel::Packing< const Node * >::pack(), libMesh::Parallel::Packing< const Elem * >::pack(), libMesh::XdrIO::pack_element(), libMesh::SparsityPattern::Build::parallel_sync(), libMesh::Elem::parent_bracketing_nodes(), libMesh::MeshBase::partition(), libMesh::Elem::point(), libMesh::SerialMesh::point(), libMesh::ParallelMesh::point(), libMesh::System::point_gradient(), libMesh::System::point_hessian(), libMesh::MeshBase::point_locator(), libMesh::System::point_value(), libMesh::METIS_CSR_Graph< IndexType >::prepare_for_use(), libMesh::MeshBase::prepare_for_use(), libMesh::MeshTools::Subdivision::prepare_subdivision_mesh(), libMesh::SparseMatrix< T >::print(), libMesh::NumericVector< T >::print(), libMesh::NumericVector< T >::print_global(), libMesh::QBase::print_info(), libMesh::DofMap::process_constraints(), libMesh::System::project_vector(), libMesh::ParameterVector::push_back(), libMesh::SerialMesh::query_elem(), libMesh::ParallelMesh::query_elem(), libMesh::SerialMesh::query_node_ptr(), libMesh::ParallelMesh::query_node_ptr(), libMesh::BoundaryInfo::raw_boundary_ids(), libMesh::BoundaryInfo::raw_edge_boundary_ids(), libMesh::AbaqusIO::read(), libMesh::Nemesis_IO::read(), libMesh::ExodusII_IO::read(), libMesh::MeshData::read(), libMesh::PltLoader::read_block_data(), libMesh::CheckpointIO::read_connectivity(), libMesh::PltLoader::read_data(), libMesh::PltLoader::read_feblock_data(), libMesh::PltLoader::read_fepoint_data(), libMesh::PltLoader::read_header(), libMesh::System::read_header(), libMesh::UCDIO::read_implementation(), libMesh::System::read_legacy_data(), libMesh::GmshIO::read_mesh(), libMesh::System::read_parallel_data(), libMesh::PltLoader::read_point_data(), libMesh::XdrIO::read_serialized_bcs(), libMesh::System::read_serialized_blocked_dof_objects(), libMesh::XdrIO::read_serialized_connectivity(), libMesh::XdrIO::read_serialized_nodes(), libMesh::XdrIO::read_serialized_nodesets(), libMesh::System::read_serialized_vector(), libMesh::System::read_serialized_vectors(), libMesh::OFFIO::read_stream(), libMesh::MatlabIO::read_stream(), libMesh::MeshData::read_unv(), libMesh::MeshData::read_unv_implementation(), libMesh::MeshData::read_xdr(), libMesh::MeshTools::Modification::redistribute(), libMesh::Parallel::Communicator::reference_unique_tag(), libMesh::TreeNode< N >::refine(), libMesh::Elem::refine(), libMesh::MeshRefinement::refine_and_coarsen_elements(), libMesh::MeshRefinement::refine_elements(), libMesh::AdaptiveTimeSolver::reinit(), libMesh::DifferentiableSystem::reinit(), libMesh::TimeSolver::reinit(), libMesh::FE< Dim, T >::reinit(), libMesh::InfFE< Dim, T_radial, T_map >::reinit(), libMesh::FEXYZ< Dim >::reinit(), libMesh::DofMap::reinit(), REINIT_ERROR(), libMesh::BoundaryInfo::remove(), libMesh::DofMap::remove_adjoint_dirichlet_boundary(), libMesh::DofMap::remove_dirichlet_boundary(), libMesh::BoundaryInfo::remove_edge(), libMesh::BoundaryInfo::remove_side(), libMesh::ParallelMesh::renumber_dof_objects(), libMesh::SerialMesh::renumber_elem(), libMesh::ParallelMesh::renumber_elem(), libMesh::SerialMesh::renumber_node(), libMesh::ParallelMesh::renumber_node(), libMesh::SerialMesh::renumber_nodes_and_elements(), libMesh::Elem::replace_child(), libMesh::ParameterVector::resize(), libMesh::DofMap::SCALAR_dof_indices(), libMesh::DofMap::scatter_constraints(), libMesh::HPCoarsenTest::select_refinement(), libMesh::EquationSystems::sensitivity_solve(), libMesh::ParameterPointer< T >::set(), libMesh::ParameterMultiPointer< T >::set(), libMesh::ParameterMultiAccessor< T >::set(), libMesh::Elem::set_child(), libMesh::DofObject::set_dof_number(), libMesh::FrequencySystem::set_frequencies(), libMesh::ParsedFunction< Output, OutputGradient >::set_inline_value(), libMesh::ParsedFEMFunction< Output >::set_inline_value(), libMesh::Elem::set_interior_parent(), libMesh::Partitioner::set_node_processor_ids(), libMesh::DofMap::set_nonlocal_dof_objects(), libMesh::SystemNorm::set_off_diagonal_weight(), libMesh::DofObject::set_old_dof_object(), libMesh::Partitioner::set_parent_processor_ids(), libMesh::SFCPartitioner::set_sfc_type(), libMesh::SystemNorm::set_type(), libMesh::MeshData::set_unv_header(), libMesh::SystemNorm::set_weight(), libMesh::Singleton::setup(), libMesh::FE< Dim, T >::shape(), libMesh::InfFE< Dim, T_radial, T_map >::shape(), libMesh::FE< Dim, T >::shape_deriv(), libMesh::FE< Dim, T >::shape_second_deriv(), libMesh::Side< SideType, ParentType >::Side(), libMesh::FEMContext::side_fe_reinit(), libMesh::AdaptiveTimeSolver::side_residual(), libMesh::EigenTimeSolver::side_residual(), libMesh::SideEdge< EdgeType, ParentType >::SideEdge(), libMesh::MeshData::slim(), libMesh::TwostepTimeSolver::solve(), libMesh::NewtonSolver::solve(), libMesh::EigenSystem::solve(), libMesh::TaoOptimizationSolver< T >::solve(), libMesh::CondensedEigenSystem::solve(), libMesh::TimeSolver::solve(), libMesh::NloptOptimizationSolver< T >::solve(), libMesh::FrequencySystem::solve(), libMesh::PetscLinearSolver< T >::solve(), libMesh::EquationSystems::solve(), libMesh::ContinuationSystem::solve_tangent(), libMesh::DofMap::stash_dof_constraints(), libMesh::MemorySolutionHistory::store(), libMesh::MeshBase::sub_point_locator(), libMesh::Parallel::Communicator::sum(), libMesh::BoundaryInfo::sync(), libMesh::Parallel::sync_dofobject_data_by_id(), libMesh::Parallel::sync_dofobject_data_by_xyz(), libMesh::Parallel::sync_element_data_by_parent_id(), libMesh::Parallel::sync_node_data_by_element_id(), libMesh::Parallel::Request::test(), libMesh::MeshRefinement::test_level_one(), libMesh::MeshRefinement::test_unflagged(), libMesh::Elem::top_parent(), libMesh::MeshRefinement::topological_neighbor(), libMesh::MeshData::translate(), libMesh::Tree< N >::Tree(), libMesh::TreeNode< N >::TreeNode(), libMesh::SystemNorm::type(), libMesh::DofObject::unique_id(), libMesh::Parallel::Packing< Node * >::unpack(), libMesh::Parallel::Packing< Elem * >::unpack(), libMesh::DofObject::unpack_indexing(), libMesh::Parallel::unpack_range(), libMesh::DofMap::unstash_dof_constraints(), libMesh::UnstructuredMesh::UnstructuredMesh(), libMesh::System::update(), libMesh::ContinuationSystem::update_solution(), libMesh::libmesh_final< T >::vec(), libMesh::System::vector_is_adjoint(), libMesh::System::vector_name(), libMesh::Edge3::volume(), libMesh::Parallel::Request::wait(), libMesh::SystemNorm::weight(), libMesh::SystemNorm::weight_sq(), libMesh::ImplicitSystem::weighted_sensitivity_adjoint_solve(), libMesh::Elem::which_child_am_i(), libMesh::Elem::which_neighbor_am_i(), libMesh::Elem::which_side_am_i(), libMesh::FroIO::write(), libMesh::ExodusII_IO::write(), libMesh::XdrIO::write(), libMesh::MeshData::write(), libMesh::EquationSystems::write(), libMesh::GMVIO::write_ascii_new_impl(), libMesh::CheckpointIO::write_bcs(), libMesh::GMVIO::write_binary(), libMesh::CheckpointIO::write_connectivity(), libMesh::Elem::write_connectivity(), libMesh::GMVIO::write_discontinuous_gmv(), libMesh::MeshOutput< MT >::write_equation_systems(), libMesh::UCDIO::write_header(), libMesh::System::write_header(), libMesh::UCDIO::write_implementation(), libMesh::UCDIO::write_interior_elems(), libMesh::GmshIO::write_mesh(), libMesh::LegacyXdrIO::write_mesh(), libMesh::UCDIO::write_nodal_data(), libMesh::UCDIO::write_nodes(), libMesh::CheckpointIO::write_nodesets(), libMesh::XdrIO::write_parallel(), libMesh::System::write_parallel_data(), libMesh::XdrIO::write_serialized_bcs(), libMesh::System::write_serialized_blocked_dof_objects(), libMesh::XdrIO::write_serialized_connectivity(), libMesh::XdrIO::write_serialized_nodesets(), libMesh::System::write_serialized_vector(), libMesh::System::write_serialized_vectors(), libMesh::Nemesis_IO_Helper::write_sidesets(), libMesh::UCDIO::write_soln(), libMesh::GnuPlotIO::write_solution(), libMesh::DivaIO::write_stream(), libMesh::TypeTensor< T >::write_unformatted(), libMesh::TypeVector< T >::write_unformatted(), libMesh::MeshData::write_unv(), libMesh::MeshData::write_unv_implementation(), and libMesh::MeshData::write_xdr().
libMesh::libmesh_assert_greater (libMeshPrivateData::_n_processors , 0)
Referenced by libMesh::MetisPartitioner::_do_partition(), libMesh::LinearPartitioner::_do_partition(), libMesh::SFCPartitioner::_do_partition(), libMesh::CentroidPartitioner::_do_partition(), libMesh::ParmetisPartitioner::_do_repartition(), libMesh::Sphere::above_surface(), libMesh::MeshTools::Subdivision::all_subdivision(), libMesh::Sphere::below_surface(), libMesh::Sphere::closest_point(), libMesh::FEMap::compute_edge_map(), libMesh::FEXYZMap::compute_face_map(), libMesh::FEMap::compute_face_map(), libMesh::DofMap::constrain_p_dofs(), libMesh::Sphere::create_from_center_radius(), libMesh::Sphere::distance(), libMesh::PltLoader::elem_type(), libMesh::MeshRefinement::eliminate_unrefined_patches(), libMesh::FEMContext::fixed_point_gradient(), libMesh::FEMContext::fixed_point_hessian(), libMesh::FEMContext::fixed_point_value(), libMesh::MeshRefinement::flag_elements_by_error_tolerance(), libMesh::DofMap::get_adjoint_dirichlet_boundaries(), libMesh::DiffContext::get_dof_indices(), libMesh::DiffContext::get_elem_fixed_solution(), libMesh::DiffContext::get_elem_jacobian(), libMesh::DiffContext::get_elem_residual(), libMesh::DiffContext::get_elem_solution(), libMesh::DiffContext::get_elem_solution_accel(), libMesh::DiffContext::get_elem_solution_rate(), libMesh::PerfLog::get_info_header(), libMesh::ParsedFunction< Output, OutputGradient >::get_inline_value(), libMesh::ParsedFEMFunction< Output >::get_inline_value(), libMesh::DiffContext::get_qoi_derivatives(), libMesh::MeshFunction::init(), libMesh::FrequencySystem::init_data(), libMesh::FESubdivision::init_shape_functions(), libMesh::FEMContext::interior_curl(), libMesh::FEMContext::interior_div(), libMesh::FEMContext::interior_gradients(), libMesh::FEMContext::interior_hessians(), libMesh::FEMContext::interior_values(), libMesh::FE< Dim, T >::inverse_map(), libMesh::InfFE< Dim, T_radial, T_map >::inverse_map(), libMesh::MeshTools::libmesh_assert_valid_refinement_tree(), libMesh::FESubdivision::loop_subdivision_mask(), libMesh::MeshRefinement::make_refinement_compatible(), libMesh::Tri3::min_and_max_angle(), libMesh::Elem::min_new_p_level_by_neighbor(), libMesh::PltLoader::n_elem(), libMesh::PltLoader::n_nodes(), libMesh::DofMap::old_dof_indices(), libMesh::Sphere::on_surface(), libMesh::ConstCouplingAccessor::operator bool(), libMesh::METIS_CSR_Graph< IndexType >::operator()(), libMesh::PatchRecoveryErrorEstimator::EstimateError::operator()(), libMesh::CouplingAccessor::operator=(), libMesh::ParameterVector::operator[](), libMesh::FEMContext::point_curl(), libMesh::FEMContext::point_gradient(), libMesh::FEMContext::point_hessian(), libMesh::Elem::point_test(), libMesh::FEMContext::point_value(), libMesh::MeshTools::Subdivision::prepare_subdivision_mesh(), libMesh::MatlabIO::read_stream(), libMesh::DofMap::remove_adjoint_dirichlet_boundary(), libMesh::QBase::scale(), libMesh::FrequencySystem::set_frequencies_by_range(), libMesh::ParsedFunction< Output, OutputGradient >::set_inline_value(), libMesh::ParsedFEMFunction< Output >::set_inline_value(), libMesh::FEMSystem::set_numerical_jacobian_h_for_var(), libMesh::FE< Dim, T >::shape(), libMesh::FE< Dim, T >::shape_deriv(), libMesh::FEMContext::side_gradient(), libMesh::FEMContext::side_gradients(), libMesh::FEMContext::side_hessians(), libMesh::FEMContext::side_values(), libMesh::VariationalMeshSmoother::smooth(), libMesh::FrequencySystem::solve(), libMesh::FEMContext::some_gradient(), libMesh::FEMContext::some_hessian(), libMesh::FEMContext::some_value(), libMesh::Sphere::Sphere(), libMesh::Sphere::unit_normal(), and libMesh::PostscriptIO::write().
template<typename Tnew , typename Told > Tnew libMesh::libmesh_cast_int (Told oldvar) inline
Definition at line 551 of file libmesh_common.h.
 {
   // we use the less redundantly named libMesh::cast_int now
   return cast_int<Tnew>(oldvar);
 }
template<typename Tnew , typename Told > Tnew libMesh::libmesh_cast_ptr (Told * oldvar) inline
Definition at line 526 of file libmesh_common.h.
 {
   // we use the less redundantly named libMesh::cast_ptr now
   return cast_ptr<Tnew>(oldvar);
 }
template<typename Tnew , typename Told > Tnew libMesh::libmesh_cast_ref (Told & oldvar) inline
Definition at line 494 of file libmesh_common.h.
 {
   // we use the less redundantly named libMesh::cast_ref now
   libmesh_deprecated();
   return cast_ref<Tnew>(oldvar);
 }
template<typename T > T libMesh::libmesh_conj (T a) inline
Definition at line 162 of file libmesh_common.h.
Referenced by libMesh::DenseVector< T >::dot().
 { return a; }
template<typename T > std::complex<T> libMesh::libmesh_conj (std::complex< T > a) inline
Definition at line 168 of file libmesh_common.h.
 { return std::conj(a); }
PetscErrorCode Vec Mat libMesh::libmesh_dbg_var (j)
template<class T > void libMesh::libmesh_ignore (const T &) inline
Definition at line 459 of file libmesh_common.h.
Referenced by libMesh::OptimizationSolver< T >::build(), and libMesh::Parallel::StandardType< Point >::StandardType().
 { }
bool libMesh::libmesh_isnan (float a) inline
Definition at line 172 of file libmesh_common.h.
References libmesh_C_isnan_float().
Referenced by libMesh::DofMap::allgather_recursive_constraints(), libmesh_isnan(), libMesh::NewtonSolver::line_search(), and libMesh::NewtonSolver::solve().
 { return libmesh_C_isnan_float(a); }
bool libMesh::libmesh_isnan (double a) inline
Definition at line 173 of file libmesh_common.h.
References libmesh_C_isnan_double().
 { return libmesh_C_isnan_double(a); }
bool libMesh::libmesh_isnan (long double a) inline
Definition at line 174 of file libmesh_common.h.
References libmesh_C_isnan_longdouble().
 { return libmesh_C_isnan_longdouble(a); }
template<typename T > bool libMesh::libmesh_isnan (std::complex< T > a) inline
Definition at line 177 of file libmesh_common.h.
References libmesh_isnan().
 { return (libmesh_isnan(std::real(a)) || libmesh_isnan(std::imag(a))); }
libMesh::libmesh_parallel_only (this-> comm())
Referenced by libMesh::ExactSolution::_compute_error(), libMesh::ParmetisPartitioner::_do_repartition(), libMesh::ParmetisPartitioner::assign_partitioning(), libMesh::MeshTools::bounding_box(), libMesh::MeshTools::correct_node_proc_ids(), DMlibMeshSetSystem_libMesh(), libMesh::LocationMap< T >::init(), libMesh::TopologyMap::init(), libMesh::MeshTools::libmesh_assert_valid_dof_ids(), libMesh::MeshTools::libmesh_assert_valid_neighbors(), libMesh::MeshTools::libmesh_assert_valid_procids< Elem >(), libMesh::MeshTools::libmesh_assert_valid_procids< Node >(), libMesh::MeshTools::libmesh_assert_valid_refinement_flags(), libMesh::MeshTools::libmesh_assert_valid_unique_ids(), libMesh::MeshCommunication::make_elems_parallel_consistent(), libMesh::MeshCommunication::make_node_ids_parallel_consistent(), libMesh::MeshCommunication::make_node_proc_ids_parallel_consistent(), libMesh::MeshCommunication::make_node_unique_ids_parallel_consistent(), libMesh::MeshCommunication::make_nodes_parallel_consistent(), libMesh::MeshCommunication::make_p_levels_parallel_consistent(), libMesh::MeshSerializer::MeshSerializer(), libMesh::MeshTools::n_active_levels(), libMesh::MeshTools::n_levels(), libMesh::MeshTools::n_p_levels(), libMesh::Partitioner::partition(), libMesh::Partitioner::set_node_processor_ids(), libMesh::Partitioner::set_parent_processor_ids(), libMesh::Parallel::sync_dofobject_data_by_id(), libMesh::Parallel::sync_dofobject_data_by_xyz(), libMesh::Parallel::sync_element_data_by_parent_id(), libMesh::Parallel::sync_node_data_by_element_id(), libMesh::MeshTools::total_weight(), and libMesh::LegacyXdrIO::write_mesh().
template<typename T > T libMesh::libmesh_real (T a) inline
Definition at line 161 of file libmesh_common.h.
Referenced by libMesh::FEMContext::_do_elem_position_set(), libMesh::ContinuationSystem::continuation_solve(), libMesh::DenseSubVector< T >::max(), libMesh::DenseVector< T >::max(), libMesh::DenseMatrix< T >::max(), libMesh::DenseSubVector< T >::min(), libMesh::DenseVector< T >::min(), libMesh::DenseMatrix< T >::min(), libMesh::FEMSystem::numerical_jacobian(), libMesh::ContinuationSystem::solve_tangent(), libMesh::GmshIO::write_post(), libMesh::EnsightIO::write_scalar_ascii(), and libMesh::EnsightIO::write_vector_ascii().
 { return a; }
template<typename T > T libMesh::libmesh_real (std::complex< T > a) inline
Definition at line 165 of file libmesh_common.h.
 { return std::real(a); }
void libMesh::libmesh_terminate_handler ()
Definition at line 277 of file libmesh.C.
References libMesh::PerfLog::clear(), GLOBAL_COMM_WORLD, old_terminate_handler, perflog, libMesh::PerfLog::print_log(), and write_traceout().
 {
   // If this got called then we're probably crashing; let's print a
   // stack trace.  The trace files that are ultimately written depend on:
   // 1.) Who throws the exception.
   // 2.) Whether the C++ runtime unwinds the stack before the
   //     terminate_handler is called (this is implementation defined).
   //
   // The various cases are summarized in the table below:
   //
   //                        | libmesh exception | other exception
   //                        -------------------------------------
   // stack unwinds          |        A          |       B
   // stack does not unwind  |        C          |       D
   //
   // Case A: There will be two stack traces in the file: one "useful"
   //         one, and one nearly empty one due to stack unwinding.
   // Case B: You will get one nearly empty stack trace (not great, Bob!)
   // Case C: You will get two nearly identical stack traces, ignore one of them.
   // Case D: You will get one useful stack trace.
   //
   // Cases A and B (where the stack unwinds when an exception leaves
   // main) appear to be non-existent in practice.  I don't have a
   // definitive list, but the stack does not unwind for GCC on either
   // Mac or Linux.  I think there's good reasons for this behavior too:
   // it's much easier to get a stack trace when the stack doesn't
   // unwind, for example.
   libMesh::write_traceout();
   // We may care about performance data pre-crash; it would be sad to
   // throw that away.
   libMesh::perflog.print_log();
   libMesh::perflog.clear();
   // If we have MPI and it has been initialized, we need to be sure
   // and call MPI_Abort instead of std::abort, so that the parallel
   // job can die nicely.
 #if defined(LIBMESH_HAVE_MPI)
   int mpi_initialized;
   MPI_Initialized (&mpi_initialized);
   if (mpi_initialized)
     MPI_Abort(libMesh::GLOBAL_COMM_WORLD, 1);
   else
 #endif
     // The system terminate_handler may do useful things like printing
     // uncaught exception information, or the user may have created
     // their own terminate handler that we want to call.
     old_terminate_handler();
 }
void libMesh::libmesh_version_stdout ()
Definition at line 20 of file libmesh_version.C.
References get_libmesh_version().
 {
   std::cout << "--------------------------------------------------------" << std::endl;
   std::cout << "libMesh Library: Version = " << LIBMESH_LIB_VERSION;
   std::cout << " (" << get_libmesh_version() << ")" << std::endl << std::endl;
   std::cout << LIBMESH_LIB_RELEASE << std::endl << std::endl;
   std::cout << "Build Date   = " << LIBMESH_BUILD_DATE     << std::endl;
   std::cout << "Build Host   = " << LIBMESH_BUILD_HOST     << std::endl;
   std::cout << "Build User   = " << LIBMESH_BUILD_USER     << std::endl;
   std::cout << "Build Arch   = " << LIBMESH_BUILD_ARCH     << std::endl;
   std::cout << "Build Rev    = " << LIBMESH_BUILD_VERSION  << std::endl << std::endl;
   // CXXFLAGS is ambiguous wth multiple methods - could add all three but why not libmesh-config?
   //std::cout << "C++ Config   = " << LIBMESH_CXX << " " << LIBMESH_CXXFLAGS << std::endl;
   std::cout << "--------------------------------------------------------" << std::endl;
   return;
 }
libMesh::LIBMESH_VMA_INSTANTIATE (Real , int , Real)
libMesh::LIBMESH_VMA_INSTANTIATE (Real , float , Real)
libMesh::LIBMESH_VMA_INSTANTIATE (Real , double , Real)
libMesh::LIBMESH_VMA_INSTANTIATE (Real , int , Complex)
libMesh::LIBMESH_VMA_INSTANTIATE (Complex , int , Complex)
libMesh::LIBMESH_VMA_INSTANTIATE (Complex , int , Real)
libMesh::LIBMESH_VMA_INSTANTIATE (Real , float , Complex)
libMesh::LIBMESH_VMA_INSTANTIATE (Complex , float , Complex)
libMesh::LIBMESH_VMA_INSTANTIATE (Complex , float , Real)
libMesh::LIBMESH_VMA_INSTANTIATE (Real , std::complex< float > , Complex)
libMesh::LIBMESH_VMA_INSTANTIATE (Complex , std::complex< float > , Complex)
libMesh::LIBMESH_VMA_INSTANTIATE (Complex , std::complex< float > , Real)
libMesh::LIBMESH_VMA_INSTANTIATE (Real , double , Complex)
libMesh::LIBMESH_VMA_INSTANTIATE (Complex , double , Complex)
libMesh::LIBMESH_VMA_INSTANTIATE (Complex , double , Real)
libMesh::LIBMESH_VMA_INSTANTIATE (Real , std::complex< double > , Complex)
libMesh::LIBMESH_VMA_INSTANTIATE (Complex , std::complex< double > , Complex)
libMesh::LIBMESH_VMA_INSTANTIATE (Complex , std::complex< double > , Real)
template void libMesh::MeshCommunication::find_global_indices< MeshBase::const_element_iterator > (const Parallel::Communicator & , const MeshTools::BoundingBox & , const MeshBase::const_element_iterator & , const MeshBase::const_element_iterator & , std::vector< dof_id_type > &) const
template void libMesh::MeshCommunication::find_global_indices< MeshBase::const_node_iterator > (const Parallel::Communicator & , const MeshTools::BoundingBox & , const MeshBase::const_node_iterator & , const MeshBase::const_node_iterator & , std::vector< dof_id_type > &) const
template void libMesh::MeshCommunication::find_global_indices< MeshBase::element_iterator > (const Parallel::Communicator & , const MeshTools::BoundingBox & , const MeshBase::element_iterator & , const MeshBase::element_iterator & , std::vector< dof_id_type > &) const
template void libMesh::MeshCommunication::find_global_indices< MeshBase::node_iterator > (const Parallel::Communicator & , const MeshTools::BoundingBox & , const MeshBase::node_iterator & , const MeshBase::node_iterator & , std::vector< dof_id_type > &) const
libMesh::processor_id_type libMesh::n_processors () inline
Returns
the number of processors used in the current simulation.
Definition at line 88 of file libmesh_base.h.
References global_n_processors().
Referenced by libMesh::DofMap::add_constraints_to_send_list(), libMesh::DofMap::allgather_recursive_constraints(), libMesh::AztecLinearSolver< T >::clear(), libMesh::PetscLinearSolver< T >::clear(), libMesh::SparsityPattern::Build::parallel_sync(), libMesh::SparseMatrix< T >::print(), libMesh::DofMap::print_dof_constraints(), libMesh::DofMap::scatter_constraints(), libMesh::Parallel::Sort< KeyType, IdxType >::sort(), libMesh::Parallel::Packing< Node * >::unpack(), libMesh::Parallel::Packing< Elem * >::unpack(), and libMesh::VTKIO::write_nodal_data().
 {
   return libMesh::global_n_processors();
 }
unsigned int libMesh::n_threads ()
Returns
the maximum number of threads used in the simulation.
PetscInt* libMesh::numeric_petsc_cast (const numeric_index_type * p) inline
Definition at line 1333 of file petsc_vector.h.
 {
   return reinterpret_cast<PetscInt *>(const_cast<numeric_index_type *>(p));
 }
libMesh::omp_set_num_threads (libMesh::libMeshPrivateData::_n_threads)
bool libMesh::on_command_line (const std::string & arg)
Returns
true if the argument arg was specified on the command line, false otherwise.
Definition at line 820 of file libmesh.C.
References libmesh_assert().
Referenced by libMesh::ContinuationSystem::ContinuationSystem(), default_solver_package(), libMesh::DofMap::distribute_dofs(), libMesh::ImplicitSystem::get_linear_solver(), if(), libMesh::NewtonSolver::init(), libMesh::PetscDiffSolver::init(), libMesh::NloptOptimizationSolver< T >::init(), libMesh::TimeSolver::init_data(), petsc_auto_fieldsplit(), print_trace(), libMesh::System::read_header(), libMesh::TimeSolver::reinit(), libMesh::MacroFunctions::report_error(), libMesh::LinearImplicitSystem::solve(), libMesh::NonlinearImplicitSystem::solve(), and libMesh::DofMap::use_coupled_neighbor_dofs().
 {
   // Make sure the command line parser is ready for use
   libmesh_assert(command_line.get());
   return command_line->search (arg);
 }
bool libMesh::operator!= (const OrderWrapper & lhs, const OrderWrapper & rhs) inline
Definition at line 97 of file fe_type.h.
 { return !(lhs == rhs); }
template<typename T , typename U > bool libMesh::operator!= (const safe_bool< T > & lhs, const safe_bool< U > &)
Definition at line 101 of file safe_bool.h.
References libMesh::safe_bool_base::this_type_does_not_support_comparisons().
 {
   lhs.this_type_does_not_support_comparisons();
   return false;
 }
bool libMesh::operator!= (int lhs, const OrderWrapper & rhs) inline
Definition at line 141 of file fe_type.h.
 { return !(lhs == rhs); }
bool libMesh::operator!= (const OrderWrapper & lhs, int rhs) inline
Definition at line 142 of file fe_type.h.
 { return !(lhs == rhs); }
bool libMesh::operator!= (Order lhs, const OrderWrapper & rhs) inline
Definition at line 143 of file fe_type.h.
 { return !(lhs == rhs); }
bool libMesh::operator!= (const OrderWrapper & lhs, Order rhs) inline
Definition at line 144 of file fe_type.h.
 { return !(lhs == rhs); }
template<typename T , typename Scalar > boostcopy::enable_if_c< ScalarTraits<Scalar>::value, TypeVector<typename CompareTypes<T, Scalar>::supertype> >::type libMesh::operator* (const Scalar factor, const TypeVector< T > & v) inline
Definition at line 742 of file type_vector.h.
 {
   return v * factor;
 }
template<typename T , typename Scalar > boostcopy::enable_if_c< ScalarTraits<Scalar>::value, TypeTensor<typename CompareTypes<T, Scalar>::supertype> >::type libMesh::operator* (const Scalar factor, const TypeTensor< T > & t) inline
Definition at line 890 of file type_tensor.h.
 {
   return t * factor;
 }
bool libMesh::operator< (const OrderWrapper & lhs, const OrderWrapper & rhs) inline
Definition at line 98 of file fe_type.h.
References libMesh::OrderWrapper::get_order().
 { return lhs.get_order() < rhs.get_order(); }
bool libMesh::operator< (int lhs, const OrderWrapper & rhs) inline
Definition at line 145 of file fe_type.h.
References libMesh::OrderWrapper::get_order().
 { return lhs < rhs.get_order(); }
bool libMesh::operator< (const OrderWrapper & lhs, int rhs) inline
Definition at line 146 of file fe_type.h.
References libMesh::OrderWrapper::get_order().
 { return lhs.get_order() < rhs; }
bool libMesh::operator< (Order lhs, const OrderWrapper & rhs) inline
Definition at line 147 of file fe_type.h.
References libMesh::OrderWrapper::get_order().
 { return lhs < rhs.get_order(); }
bool libMesh::operator< (const OrderWrapper & lhs, Order rhs) inline
Definition at line 148 of file fe_type.h.
References libMesh::OrderWrapper::get_order().
 { return lhs.get_order() < rhs; }
template<typename T > std::ostream & libMesh::operator<< (std::ostream & os, const SparseMatrix< T > & m)
Same as the print method above, but allows you to print to a stream in the standard syntax.
template <typename u>=""> friend std::ostream & operator << (std::ostream & os, const SparseMatrix<U> & m);
Obscure C++ note 1: the above syntax, which does not require any prior declaration of operator<<, declares any instantiation of SparseMatrix<X> is friend to any instantiation of operator<<(ostream &, SparseMatrix<Y> &). It would not happen in practice, but in principle it means that SparseMatrix<Complex> would be friend to operator<<(ostream &, SparseMatrix<Real>).
Obscure C++ note 2: The form below, which requires a previous declaration of the operator<<(stream &, SparseMatrix<T> &) function (see top of this file), means that any instantiation of SparseMatrix<T> is friend to the specialization operator<<(ostream &, SparseMatrix<T> &), but e.g. SparseMatrix<U> is not friend to the same function. So this is slightly different to the form above...
This method seems to be the "preferred" technique, see http://www.parashift.com/c++-faq-lite/template-friends.html
Definition at line 454 of file sparse_matrix.h.
 {
   m.print(os);
   return os;
 }
std::ostream& libMesh::operator<< (std::ostream & os, const OrderWrapper & order) inline
Overload stream operators.
Definition at line 165 of file fe_type.h.
References libMesh::OrderWrapper::get_order().
 {
   os << order.get_order();
   return os;
 }
std::ostream& libMesh::operator<< (std::ostream & os, const Node & n) inline
Definition at line 202 of file node.h.
References libMesh::Node::print_info().
 {
   n.print_info(os);
   return os;
 }
std::ostream& libMesh::operator<< (std::ostream & os, const QBase & q)
Same as above, but allows you to use the stream syntax.
Definition at line 208 of file quadrature.C.
References libMesh::QBase::print_info().
 {
   q.print_info(os);
   return os;
 }
std::ostream& libMesh::operator<< (std::ostream & os, const MeshData & m)
Same as above, but allows you to use the stream syntax.
Definition at line 365 of file mesh_data.C.
References libMesh::MeshData::print_info().
 {
   m.print_info(os);
   return os;
 }
std::ostream& libMesh::operator<< (std::ostream & os, const MeshBase & m)
Equivalent to calling print_info() above, but now you can write: Mesh mesh; libMesh::out << mesh << std::endl;
Definition at line 398 of file mesh_base.C.
References libMesh::MeshBase::print_info().
 {
   m.print_info(os);
   return os;
 }
std::ostream& libMesh::operator<< (std::ostream & os, const Parameters & p) inline
Definition at line 401 of file parameters.h.
References libMesh::Parameters::print().
 {
   p.print(os);
   return os;
 }
std::ostream& libMesh::operator<< (std::ostream & os, const FEAbstract & fe)
Same as above, but allows you to print to a stream.
Definition at line 777 of file fe_abstract.C.
References libMesh::FEAbstract::print_info().
 {
   fe.print_info(os);
   return os;
 }
std::ostream& libMesh::operator<< (std::ostream & os, const EquationSystems & es)
Same as above, but allows you to also use stream syntax.
Definition at line 1250 of file equation_systems.C.
References libMesh::EquationSystems::print_info().
 {
   es.print_info(os);
   return os;
 }
std::ostream& libMesh::operator<< (std::ostream & os, const Elem & e) inline
Definition at line 1389 of file elem.h.
References libMesh::Elem::print_info().
 {
   e.print_info(os);
   return os;
 }
bool libMesh::operator<= (const OrderWrapper & lhs, const OrderWrapper & rhs) inline
Definition at line 100 of file fe_type.h.
 { return !(lhs > rhs); }
bool libMesh::operator<= (int lhs, const OrderWrapper & rhs) inline
Definition at line 153 of file fe_type.h.
 { return !(lhs > rhs); }
bool libMesh::operator<= (const OrderWrapper & lhs, int rhs) inline
Definition at line 154 of file fe_type.h.
 { return !(lhs > rhs); }
bool libMesh::operator<= (Order lhs, const OrderWrapper & rhs) inline
Definition at line 155 of file fe_type.h.
 { return !(lhs > rhs); }
bool libMesh::operator<= (const OrderWrapper & lhs, Order rhs) inline
Definition at line 156 of file fe_type.h.
 { return !(lhs > rhs); }
template<typename T > bool libMesh::operator== (const safe_bool< T > & lhs, bool b)
Definition at line 78 of file safe_bool.h.
 {
   return b == static_cast<bool>(lhs);
 }
template<typename T > bool libMesh::operator== (bool b, const safe_bool< T > & rhs)
Definition at line 84 of file safe_bool.h.
 {
   return b == static_cast<bool>(rhs);
 }
template<typename T , typename U > bool libMesh::operator== (const safe_bool< T > & lhs, const safe_bool< U > &)
Definition at line 93 of file safe_bool.h.
References libMesh::safe_bool_base::this_type_does_not_support_comparisons().
 {
   lhs.this_type_does_not_support_comparisons();
   return false;
 }
bool libMesh::operator== (const OrderWrapper & lhs, const OrderWrapper & rhs) inline
Overload comparison operators for OrderWrapper.
Definition at line 96 of file fe_type.h.
References libMesh::OrderWrapper::get_order().
 { return lhs.get_order() == rhs.get_order(); }
bool libMesh::operator== (const OrderWrapper & lhs, int rhs) inline
Definition at line 138 of file fe_type.h.
References libMesh::OrderWrapper::get_order().
 { return lhs.get_order() == rhs; }
bool libMesh::operator== (Order lhs, const OrderWrapper & rhs) inline
Definition at line 139 of file fe_type.h.
References libMesh::OrderWrapper::get_order().
 { return lhs == rhs.get_order(); }
bool libMesh::operator== (const OrderWrapper & lhs, Order rhs) inline
Definition at line 140 of file fe_type.h.
References libMesh::OrderWrapper::get_order().
 { return lhs.get_order() == rhs; }
bool libMesh::operator> (const OrderWrapper & lhs, const OrderWrapper & rhs) inline
Definition at line 99 of file fe_type.h.
 { return rhs < lhs; }
bool libMesh::operator> (int lhs, const OrderWrapper & rhs) inline
Definition at line 149 of file fe_type.h.
 { return rhs < lhs; }
bool libMesh::operator> (const OrderWrapper & lhs, int rhs) inline
Definition at line 150 of file fe_type.h.
 { return rhs < lhs; }
bool libMesh::operator> (Order lhs, const OrderWrapper & rhs) inline
Definition at line 151 of file fe_type.h.
 { return rhs < lhs; }
bool libMesh::operator> (const OrderWrapper & lhs, Order rhs) inline
Definition at line 152 of file fe_type.h.
 { return rhs < lhs; }
bool libMesh::operator>= (const OrderWrapper & lhs, const OrderWrapper & rhs) inline
Definition at line 101 of file fe_type.h.
 { return !(lhs < rhs); }
bool libMesh::operator>= (int lhs, const OrderWrapper & rhs) inline
Definition at line 157 of file fe_type.h.
 { return !(lhs < rhs); }
bool libMesh::operator>= (const OrderWrapper & lhs, int rhs) inline
Definition at line 158 of file fe_type.h.
 { return !(lhs < rhs); }
bool libMesh::operator>= (Order lhs, const OrderWrapper & rhs) inline
Definition at line 159 of file fe_type.h.
 { return !(lhs < rhs); }
bool libMesh::operator>= (const OrderWrapper & lhs, Order rhs) inline
Definition at line 160 of file fe_type.h.
 { return !(lhs < rhs); }
libMesh::OrderWrapperOperators (int)
Definition at line 131 of file fe_type.h.
                                                         { return lhs == rhs.get_order(); }
command_line libMesh::parse_command_line (argc , argv)
PetscMatrix<Number> J_input* libMesh::pc ()
void libMesh::petsc_auto_fieldsplit (PC my_pc, const System & sys)
Definition at line 58 of file petsc_auto_fieldsplit.C.
References libMesh::ParallelObject::comm(), command_line_value(), libMesh::System::get_dof_map(), libMesh::System::get_mesh(), libMesh::DofMap::local_variable_indices(), libMesh::System::n_vars(), libMesh::System::name(), on_command_line(), and libMesh::System::variable_name().
Referenced by libMesh::PetscDiffSolver::init(), libMesh::PetscLinearSolver< T >::init_names(), and libMesh::PetscDiffSolver::reinit().
 {
   std::string sys_prefix = "--solver_group_";
   if (libMesh::on_command_line("--solver_system_names"))
     {
       sys_prefix = sys_prefix + sys.name() + "_";
     }
   std::map<std::string, std::vector<dof_id_type> > group_indices;
   if (libMesh::on_command_line("--solver_variable_names"))
     {
       for (unsigned int v = 0; v != sys.n_vars(); ++v)
         {
           const std::string & var_name = sys.variable_name(v);
           std::vector<dof_id_type> var_idx;
           sys.get_dof_map().local_variable_indices
             (var_idx, sys.get_mesh(), v);
           std::string group_command = sys_prefix + var_name;
           const std::string empty_string;
           std::string group_name = libMesh::command_line_value
             (group_command, empty_string);
           if (group_name != empty_string)
             {
               std::vector<dof_id_type> & indices =
                 group_indices[group_name];
               const bool prior_indices = !indices.empty();
               indices.insert(indices.end(), var_idx.begin(),
                              var_idx.end());
               if (prior_indices)
                 std::sort(indices.begin(), indices.end());
             }
           else
             {
               indices_to_fieldsplit (sys.comm(), var_idx, my_pc, var_name);
             }
         }
     }
   for (std::map<std::string, std::vector<dof_id_type> >::const_iterator
          i = group_indices.begin(); i != group_indices.end(); ++i)
     {
       indices_to_fieldsplit(sys.comm(), i->second, my_pc, i->first);
     }
 }
libMesh::PetscObjectGetComm ((PetscObject) pc, & comm)
Referenced by libMesh::SlepcEigenSolver< T >::_petsc_shell_matrix_get_diagonal(), libMesh::SlepcEigenSolver< T >::_petsc_shell_matrix_mult(), and libMesh::PetscPreconditioner< T >::set_petsc_preconditioner_type().
template<typename P > void libMesh::print_helper (std::ostream & os, const P * param)
Helper functions for printing scalar, vector and vector<vector> types. Called from Parameters::Parameter<T>::print(...).
Definition at line 539 of file parameters.h.
Referenced by libMesh::Parameters::Parameter< T >::print().
 {
   os << *param;
 }
template<typename P > void libMesh::print_helper (std::ostream & os, const std::vector< P > * param)
Definition at line 546 of file parameters.h.
 {
   for (unsigned int i=0; i<param->size(); ++i)
     os << (*param)[i] << " ";
 }
template<typename P > void libMesh::print_helper (std::ostream & os, const std::vector< std::vector< P > > * param)
Definition at line 554 of file parameters.h.
 {
   for (unsigned int i=0; i<param->size(); ++i)
     for (unsigned int j=0; j<(*param)[i].size(); ++j)
       os << (*param)[i][j] << " ";
 }
void libMesh::print_trace (std::ostream & out_stream = std::cerr)
Print a stack trace (for code compiled with gcc)
Definition at line 179 of file print_trace.C.
References on_command_line().
Referenced by libMesh::MacroFunctions::report_error(), and write_traceout().
 {
   // First try a GDB backtrace.  They are better than what you get
   // from calling backtrace() because you don't have to do any
   // demangling, and they include line numbers!  If the GDB backtrace
   // fails, for example if your system does not have GDB, fall back to
   // calling backtrace().
   bool gdb_worked = false;
   // Let the user disable GDB backtraces by configuring with
   // --without-gdb-command or with a command line option.
   if (std::string(LIBMESH_GDB_COMMAND) != std::string("no") &&
       !libMesh::on_command_line("--no-gdb-backtrace"))
     gdb_worked = gdb_backtrace(out_stream);
   // This part requires that your compiler at least supports
   // backtraces.  Demangling is also nice, but it will still run
   // without it.
 #if defined(LIBMESH_HAVE_GLIBC_BACKTRACE)
   if (!gdb_worked)
     {
       void * addresses[40];
       char ** strings;
       int size = backtrace(addresses, 40);
       strings = backtrace_symbols(addresses, size);
       out_stream << "Stack frames: " << size << std::endl;
       for(int i = 0; i < size; i++)
         out_stream << i << ": " << process_trace(strings[i]) << std::endl;
       std::free(strings);
     }
 #endif
 }
libMesh::processor_id_type libMesh::processor_id () inline
Returns
the index of the local processor.
Definition at line 96 of file libmesh_base.h.
References global_processor_id().
Referenced by libMesh::DofMap::allgather_recursive_constraints(), libMesh::DofMap::get_info(), libMesh::DofMap::get_local_constraints(), if(), libMesh::SparsityPattern::Build::join(), libMesh::MeshInput< MT >::MeshInput(), libMesh::MeshOutput< MT >::MeshOutput(), libMesh::SparsityPattern::Build::parallel_sync(), libMesh::SparseMatrix< T >::print(), libMesh::DofMap::print_dof_constraints(), libMesh::NumericVector< T >::print_global(), libMesh::TetGenIO::read(), libMesh::GMVIO::read(), libMesh::LegacyXdrIO::read(), libMesh::VTKIO::read(), libMesh::UCDIO::read_implementation(), libMesh::GmshIO::read_mesh(), libMesh::LegacyXdrIO::read_mesh(), libMesh::OFFIO::read_stream(), libMesh::MatlabIO::read_stream(), libMesh::DofMap::scatter_constraints(), libMesh::Partitioner::set_parent_processor_ids(), libMesh::VTKIO::system_vectors_to_vtk(), libMesh::Parallel::Packing< Node * >::unpack(), libMesh::Parallel::Packing< Elem * >::unpack(), libMesh::FroIO::write(), libMesh::TecplotIO::write(), libMesh::MEDITIO::write(), libMesh::PostscriptIO::write(), libMesh::GmshIO::write(), libMesh::TecplotIO::write_ascii(), libMesh::GMVIO::write_ascii_new_impl(), libMesh::GMVIO::write_ascii_old_impl(), libMesh::TecplotIO::write_binary(), libMesh::GMVIO::write_binary(), libMesh::TecplotIO::write_nodal_data(), libMesh::MEDITIO::write_nodal_data(), libMesh::VTKIO::write_nodal_data(), libMesh::GmshIO::write_nodal_data(), libMesh::GmshIO::write_post(), and libMesh::GnuPlotIO::write_solution().
 {
   return libMesh::global_processor_id();
 }
this libMesh::reduce_error (error_per_cell , system. comm())
libMesh::REINIT_ERROR (REINIT_ERROR(0, REINIT_ERROR(CLOUGH, reinit)
Definition at line 70 of file fe_boundary.C.
References libMesh::Elem::build_side(), libmesh_assert(), libmesh_nullptr, std::max(), libMesh::Elem::neighbor(), libMesh::Elem::p_level(), side, and libMesh::Elem::type().
 {
   libmesh_assert(elem);
   libmesh_assert (this->qrule != libmesh_nullptr || pts != libmesh_nullptr);
   // We now do this for 1D elements!
   // libmesh_assert_not_equal_to (Dim, 1);
   // Build the side of interest
   const UniquePtr<Elem> side(elem->build_side(s));
   // Find the max p_level to select
   // the right quadrature rule for side integration
   unsigned int side_p_level = elem->p_level();
   if (elem->neighbor(s) != libmesh_nullptr)
     side_p_level = std::max(side_p_level, elem->neighbor(s)->p_level());
   // Initialize the shape functions at the user-specified
   // points
   if (pts != libmesh_nullptr)
     {
       // The shape functions do not correspond to the qrule
       this->shapes_on_quadrature = false;
       // Initialize the face shape functions
       this->_fe_map->template init_face_shape_functions<Dim>(*pts, side.get());
       // Compute the Jacobian*Weight on the face for integration
       if (weights != libmesh_nullptr)
         {
           this->_fe_map->compute_face_map (Dim, *weights, side.get());
         }
       else
         {
           std::vector<Real> dummy_weights (pts->size(), 1.);
           this->_fe_map->compute_face_map (Dim, dummy_weights, side.get());
         }
     }
   // If there are no user specified points, we use the
   // quadrature rule
   else
     {
       // initialize quadrature rule
       this->qrule->init(side->type(), side_p_level);
       if(this->qrule->shapes_need_reinit())
         this->shapes_on_quadrature = false;
       // FIXME - could this break if the same FE object was used
       // for both volume and face integrals? - RHS
       // We might not need to reinitialize the shape functions
       if ((this->get_type() != elem->type())    ||
           (side->type() != last_side)           ||
           (this->get_p_level() != side_p_level) ||
           this->shapes_need_reinit()            ||
           !this->shapes_on_quadrature)
         {
           // Set the element type and p_level
           this->elem_type = elem->type();
           // Set the last_side
           last_side = side->type();
           // Set the last p level
           this->_p_level = side_p_level;
           // Initialize the face shape functions
           this->_fe_map->template init_face_shape_functions<Dim>(this->qrule->get_points(),  side.get());
         }
       // Compute the Jacobian*Weight on the face for integration
       this->_fe_map->compute_face_map (Dim, this->qrule->get_weights(), side.get());
       // The shape functions correspond to the qrule
       this->shapes_on_quadrature = true;
     }
   // make a copy of the Jacobian for integration
   const std::vector<Real> JxW_int(this->_fe_map->get_JxW());
   // make a copy of shape on quadrature info
   bool shapes_on_quadrature_side = this->shapes_on_quadrature;
   // Find where the integration points are located on the
   // full element.
   const std::vector<Point> * ref_qp;
   if (pts != libmesh_nullptr)
     ref_qp = pts;
   else
     ref_qp = &this->qrule->get_points();
   std::vector<Point> qp;
   this->side_map(elem, side.get(), s, *ref_qp, qp);
   // compute the shape function and derivative values
   // at the points qp
   this->reinit  (elem, &qp);
   this->shapes_on_quadrature = shapes_on_quadrature_side;
   // copy back old data
   this->_fe_map->get_JxW() = JxW_int;
 }
task_scheduler libMesh::reset (new Threads:: task_scheduler_initlibMesh::n_threads())
error_per_cell libMesh::resize (mesh. max_elem_id())
Referenced by libMesh::SensitivityData::allocate_hessian_data(), libMesh::TetGenIO::element_in(), libMesh::DenseMatrix< T >::left_multiply(), libMesh::DenseMatrix< T >::left_multiply_transpose(), libMesh::TetGenIO::node_in(), libMesh::DenseMatrix< T >::operator=(), libMesh::DenseMatrix< T >::right_multiply(), libMesh::DenseMatrix< T >::right_multiply_transpose(), libMesh::PltLoader::set_n_vars(), and libMesh::PltLoader::set_n_zones().
libMesh::ScalarTraits_true (char)
libMesh::ScalarTraits_true (short)
libMesh::ScalarTraits_true (int)
libMesh::ScalarTraits_true (long)
libMesh::ScalarTraits_true (unsigned char)
libMesh::ScalarTraits_true (float)
libMesh::ScalarTraits_true (double)
template<typename T > T libMesh::SIGN (T a, T b) inline
Definition at line 33 of file newton_solver.C.
References std::abs().
Referenced by libMesh::NewtonSolver::line_search().
 {
   return b >= 0 ? std::abs(a) : -std::abs(a);
 }
libMesh::START_LOG ("std::sqrt()" , "ExactErrorEstimator")
Referenced by __libmesh_nlopt_equality_constraints(), __libmesh_nlopt_inequality_constraints(), __libmesh_nlopt_objective(), __libmesh_petsc_snes_jacobian(), __libmesh_petsc_snes_postcheck(), __libmesh_petsc_snes_residual(), __libmesh_tao_equality_constraints(), __libmesh_tao_equality_constraints_jacobian(), __libmesh_tao_gradient(), __libmesh_tao_hessian(), __libmesh_tao_inequality_constraints(), __libmesh_tao_inequality_constraints_jacobian(), __libmesh_tao_objective(), libMesh::MeshRefinement::_coarsen_elements(), libMesh::MetisPartitioner::_do_partition(), libMesh::LinearPartitioner::_do_partition(), libMesh::SFCPartitioner::_do_partition(), libMesh::ParmetisPartitioner::_do_repartition(), libMesh::UniformRefinementEstimator::_estimate_error(), libMesh::EquationSystems::_read_impl(), libMesh::MeshRefinement::_refine_elements(), libMesh::SlepcEigenSolver< T >::_solve_generalized_helper(), libMesh::SlepcEigenSolver< T >::_solve_standard_helper(), libMesh::BoundaryInfo::add_elements(), libMesh::DofMap::add_neighbors_to_send_list(), libMesh::MeshRefinement::add_node(), libMesh::EigenSparseLinearSolver< T >::adjoint_solve(), libMesh::LaspackLinearSolver< T >::adjoint_solve(), libMesh::PetscLinearSolver< T >::adjoint_solve(), libMesh::LinearSolver< T >::adjoint_solve(), libMesh::ImplicitSystem::adjoint_solve(), libMesh::UnstructuredMesh::all_first_order(), libMesh::UnstructuredMesh::all_second_order(), libMesh::Parallel::Communicator::allgather(), libMesh::Parallel::Communicator::alltoall(), libMesh::FrequencySystem::assemble(), libMesh::System::assemble(), libMesh::FEMSystem::assemble_qoi(), libMesh::System::assemble_qoi(), libMesh::FEMSystem::assemble_qoi_derivative(), libMesh::System::assemble_qoi_derivative(), libMesh::FEMSystem::assembly(), libMesh::MeshCommunication::assign_global_indices(), libMesh::Parallel::Communicator::barrier(), libMesh::System::boundary_project_vector(), libMesh::Parallel::Communicator::broadcast(), libMesh::DofMap::build_constraint_matrix(), libMesh::DofMap::build_constraint_matrix_and_vector(), libMesh::MeshTools::Generation::build_cube(), libMesh::EquationSystems::build_discontinuous_solution_vector(), libMesh::MeshTools::Generation::build_extrusion(), libMesh::InfElemBuilder::build_inf_elem(), libMesh::EquationSystems::build_solution_vector(), libMesh::DofMap::build_sparsity(), libMesh::System::calculate_norm(), libMesh::MeshCommunication::check_for_duplicate_global_indices(), libMesh::OldSolutionValue< Output, point_output >::check_old_context(), libMesh::PetscDiffSolver::clear(), libMesh::InfFE< Dim, T_radial, T_map >::combine_base_radial(), libMesh::FEMap::compute_affine_map(), libMesh::FEMap::compute_edge_map(), libMesh::FEXYZMap::compute_face_map(), libMesh::FEMap::compute_face_map(), libMesh::FEXYZ< Dim >::compute_face_values(), libMesh::FEMap::compute_map(), libMesh::FEMap::compute_null_map(), libMesh::FEGenericBase< OutputType >::compute_shape_functions(), libMesh::InfFE< Dim, T_radial, T_map >::compute_shape_functions(), libMesh::FEXYZ< Dim >::compute_shape_functions(), libMesh::Problem_Interface::computeF(), libMesh::Problem_Interface::computeJacobian(), libMesh::Problem_Interface::computePreconditioner(), libMesh::DofMap::constrain_element_dyad_matrix(), libMesh::DofMap::constrain_element_matrix(), libMesh::DofMap::constrain_element_matrix_and_vector(), libMesh::DofMap::constrain_element_vector(), libMesh::UnstructuredMesh::contract(), libMesh::DofMap::create_dof_constraints(), libMesh::ErrorVector::cut_above(), libMesh::StatisticsVector< T >::cut_above(), libMesh::ErrorVector::cut_below(), libMesh::StatisticsVector< T >::cut_below(), libMesh::MeshCommunication::delete_remote_elements(), libMesh::MeshTools::Modification::distort(), libMesh::DofMap::distribute_dofs(), libMesh::DofMap::dof_indices(), libMesh::UNVIO::elements_in(), libMesh::DofMap::enforce_adjoint_constraints_exactly(), libMesh::DofMap::enforce_constraints_exactly(), libMesh::WeightedPatchRecoveryErrorEstimator::estimate_error(), libMesh::PatchRecoveryErrorEstimator::estimate_error(), libMesh::JumpErrorEstimator::estimate_error(), libMesh::UniformRefinementEstimator::estimate_error(), libMesh::AdjointResidualErrorEstimator::estimate_error(), libMesh::UniformRefinementEstimator::estimate_errors(), libMesh::OldSolutionValue< Output, point_output >::eval_at_node(), libMesh::OldSolutionValue< Output, point_output >::eval_at_point(), libMesh::OldSolutionValue< Output, point_output >::eval_old_dofs(), libMesh::LocationMap< T >::find(), libMesh::MeshCommunication::find_global_indices(), libMesh::UnstructuredMesh::find_neighbors(), libMesh::Parallel::Communicator::gather(), libMesh::TaoOptimizationSolver< T >::get_dual_variables(), libMesh::CondensedEigenSystem::get_eigenpair(), libMesh::BoundaryInfo::get_side_and_node_maps(), libMesh::DofMap::heterogenously_constrain_element_matrix_and_vector(), libMesh::DofMap::heterogenously_constrain_element_vector(), libMesh::StatisticsVector< T >::histogram(), libMesh::LocationMap< T >::init(), libMesh::PetscDiffSolver::init(), libMesh::TopologyMap::init(), libMesh::PointLocatorTree::init(), libMesh::PointLocatorList::init(), libMesh::FrequencySystem::init_data(), libMesh::FEMap::init_edge_shape_functions(), libMesh::FEMap::init_face_shape_functions(), libMesh::InfFE< Dim, T_radial, T_map >::init_radial_shape_functions(), libMesh::FEMap::init_reference_to_physical_map(), libMesh::FE< Dim, T >::init_shape_functions(), libMesh::InfFE< Dim, T_radial, T_map >::init_shape_functions(), libMesh::FESubdivision::init_shape_functions(), libMesh::FEXYZ< Dim >::init_shape_functions(), libMesh::NewmarkSystem::initial_conditions(), libMesh::FE< Dim, T >::inverse_map(), libMesh::InfFE< Dim, T_radial, T_map >::inverse_map(), libMesh::MeshRefinement::make_coarsening_compatible(), libMesh::MeshCommunication::make_elems_parallel_consistent(), libMesh::MeshRefinement::make_flags_parallel_consistent(), libMesh::MeshCommunication::make_node_ids_parallel_consistent(), libMesh::MeshCommunication::make_node_proc_ids_parallel_consistent(), libMesh::MeshCommunication::make_node_unique_ids_parallel_consistent(), libMesh::MeshCommunication::make_p_levels_parallel_consistent(), libMesh::MeshRefinement::make_refinement_compatible(), libMesh::Parallel::Communicator::max(), libMesh::StatisticsVector< T >::maximum(), libMesh::Parallel::Communicator::maxloc(), libMesh::ErrorVector::mean(), libMesh::StatisticsVector< T >::mean(), libMesh::StatisticsVector< T >::median(), libMesh::Parallel::Communicator::min(), libMesh::ErrorVector::minimum(), libMesh::StatisticsVector< T >::minimum(), libMesh::Parallel::Communicator::minloc(), libMesh::UNVIO::nodes_in(), libMesh::FEMSystem::numerical_elem_jacobian(), libMesh::FEMSystem::numerical_nonlocal_jacobian(), libMesh::FEMSystem::numerical_side_jacobian(), libMesh::DofMap::old_dof_indices(), libMesh::GenericProjector< FFunctor, GFunctor, FValue, ProjectionAction >::operator()(), libMesh::PointLocatorList::operator()(), libMesh::PointLocatorTree::operator()(), libMesh::PointLocatorTree::perform_linear_search(), libMesh::FEMSystem::postprocess(), libMesh::DofMap::prepare_send_list(), libMesh::Parallel::Communicator::probe(), libMesh::System::project_vector(), libMesh::NameBasedIO::read(), libMesh::Nemesis_IO::read(), libMesh::CheckpointIO::read(), libMesh::XdrIO::read(), libMesh::MeshData::read(), libMesh::LegacyXdrIO::read_mesh(), libMesh::Parallel::Communicator::receive(), libMesh::MeshTools::Modification::redistribute(), libMesh::DofMap::reinit(), libMesh::SerialMesh::renumber_nodes_and_elements(), libMesh::ParallelMesh::renumber_nodes_and_elements(), libMesh::DofMap::SCALAR_dof_indices(), libMesh::HPSingularity::select_refinement(), libMesh::HPCoarsenTest::select_refinement(), libMesh::Parallel::Communicator::send(), libMesh::Parallel::Communicator::send_receive(), libMesh::Parallel::Communicator::send_receive_packed_range(), libMesh::ImplicitSystem::sensitivity_solve(), libMesh::Partitioner::set_node_processor_ids(), libMesh::Partitioner::set_parent_processor_ids(), libMesh::Partitioner::single_partition(), libMesh::EigenSparseLinearSolver< T >::solve(), libMesh::NewtonSolver::solve(), libMesh::LaspackLinearSolver< T >::solve(), libMesh::PetscDiffSolver::solve(), libMesh::AztecLinearSolver< T >::solve(), libMesh::TaoOptimizationSolver< T >::solve(), libMesh::CondensedEigenSystem::solve(), libMesh::PetscNonlinearSolver< T >::solve(), libMesh::NloptOptimizationSolver< T >::solve(), libMesh::FrequencySystem::solve(), libMesh::PetscLinearSolver< T >::solve(), libMesh::NonlinearImplicitSystem::solve(), libMesh::OptimizationSystem::solve(), libMesh::SerialMesh::stitch_meshes(), libMesh::Parallel::Communicator::sum(), libMesh::BoundaryInfo::sync(), libMesh::MeshData::translate(), libMesh::EquationSystems::update(), libMesh::NewmarkSystem::update_rhs(), libMesh::NewmarkSystem::update_u_v_a(), libMesh::ErrorVector::variance(), libMesh::StatisticsVector< T >::variance(), libMesh::Parallel::Request::wait(), libMesh::ImplicitSystem::weighted_sensitivity_adjoint_solve(), libMesh::ImplicitSystem::weighted_sensitivity_solve(), libMesh::NameBasedIO::write(), libMesh::CheckpointIO::write(), libMesh::XdrIO::write(), libMesh::UnstructuredMesh::write(), libMesh::MeshData::write(), libMesh::EquationSystems::write(), libMesh::MeshOutput< MT >::write_equation_systems(), libMesh::LegacyXdrIO::write_mesh(), libMesh::TecplotIO::write_nodal_data(), libMesh::GnuPlotIO::write_nodal_data(), libMesh::MEDITIO::write_nodal_data(), libMesh::GmshIO::write_nodal_data(), libMesh::Nemesis_IO::write_nodal_data(), libMesh::GMVIO::write_nodal_data(), libMesh::ExodusII_IO::write_nodal_data(), and libMesh::ExodusII_IO::write_nodal_data_discontinuous().
libMesh::STOP_LOG ("std::sqrt()" , "ExactErrorEstimator")
Referenced by __libmesh_nlopt_equality_constraints(), __libmesh_nlopt_inequality_constraints(), __libmesh_nlopt_objective(), __libmesh_petsc_snes_jacobian(), __libmesh_petsc_snes_postcheck(), __libmesh_petsc_snes_residual(), __libmesh_tao_equality_constraints(), __libmesh_tao_equality_constraints_jacobian(), __libmesh_tao_gradient(), __libmesh_tao_hessian(), __libmesh_tao_inequality_constraints(), __libmesh_tao_inequality_constraints_jacobian(), __libmesh_tao_objective(), libMesh::MeshRefinement::_coarsen_elements(), libMesh::MetisPartitioner::_do_partition(), libMesh::LinearPartitioner::_do_partition(), libMesh::SFCPartitioner::_do_partition(), libMesh::ParmetisPartitioner::_do_repartition(), libMesh::UniformRefinementEstimator::_estimate_error(), libMesh::EquationSystems::_read_impl(), libMesh::MeshRefinement::_refine_elements(), libMesh::SlepcEigenSolver< T >::_solve_generalized_helper(), libMesh::SlepcEigenSolver< T >::_solve_standard_helper(), libMesh::BoundaryInfo::add_elements(), libMesh::DofMap::add_neighbors_to_send_list(), libMesh::MeshRefinement::add_node(), libMesh::EigenSparseLinearSolver< T >::adjoint_solve(), libMesh::LaspackLinearSolver< T >::adjoint_solve(), libMesh::PetscLinearSolver< T >::adjoint_solve(), libMesh::LinearSolver< T >::adjoint_solve(), libMesh::ImplicitSystem::adjoint_solve(), libMesh::UnstructuredMesh::all_first_order(), libMesh::UnstructuredMesh::all_second_order(), libMesh::Parallel::Communicator::allgather(), libMesh::Parallel::Communicator::alltoall(), libMesh::FrequencySystem::assemble(), libMesh::System::assemble(), libMesh::FEMSystem::assemble_qoi(), libMesh::System::assemble_qoi(), libMesh::FEMSystem::assemble_qoi_derivative(), libMesh::System::assemble_qoi_derivative(), libMesh::FEMSystem::assembly(), libMesh::MeshCommunication::assign_global_indices(), libMesh::Parallel::Communicator::barrier(), libMesh::System::boundary_project_vector(), libMesh::Parallel::Communicator::broadcast(), libMesh::DofMap::build_constraint_matrix(), libMesh::DofMap::build_constraint_matrix_and_vector(), libMesh::MeshTools::Generation::build_cube(), libMesh::EquationSystems::build_discontinuous_solution_vector(), libMesh::MeshTools::Generation::build_extrusion(), libMesh::InfElemBuilder::build_inf_elem(), libMesh::EquationSystems::build_solution_vector(), libMesh::DofMap::build_sparsity(), libMesh::System::calculate_norm(), libMesh::MeshCommunication::check_for_duplicate_global_indices(), libMesh::OldSolutionValue< Output, point_output >::check_old_context(), libMesh::PetscDiffSolver::clear(), libMesh::InfFE< Dim, T_radial, T_map >::combine_base_radial(), libMesh::FEMap::compute_affine_map(), libMesh::FEMap::compute_edge_map(), libMesh::FEXYZMap::compute_face_map(), libMesh::FEMap::compute_face_map(), libMesh::FEXYZ< Dim >::compute_face_values(), libMesh::FEMap::compute_map(), libMesh::FEMap::compute_null_map(), libMesh::FEGenericBase< OutputType >::compute_shape_functions(), libMesh::InfFE< Dim, T_radial, T_map >::compute_shape_functions(), libMesh::FEXYZ< Dim >::compute_shape_functions(), libMesh::Problem_Interface::computeF(), libMesh::Problem_Interface::computeJacobian(), libMesh::Problem_Interface::computePreconditioner(), libMesh::DofMap::constrain_element_dyad_matrix(), libMesh::DofMap::constrain_element_matrix(), libMesh::DofMap::constrain_element_matrix_and_vector(), libMesh::DofMap::constrain_element_vector(), libMesh::UnstructuredMesh::contract(), libMesh::DofMap::create_dof_constraints(), libMesh::ErrorVector::cut_above(), libMesh::StatisticsVector< T >::cut_above(), libMesh::ErrorVector::cut_below(), libMesh::StatisticsVector< T >::cut_below(), libMesh::MeshCommunication::delete_remote_elements(), libMesh::MeshTools::Modification::distort(), libMesh::DofMap::distribute_dofs(), libMesh::DofMap::dof_indices(), libMesh::UNVIO::elements_in(), libMesh::DofMap::enforce_adjoint_constraints_exactly(), libMesh::DofMap::enforce_constraints_exactly(), libMesh::WeightedPatchRecoveryErrorEstimator::estimate_error(), libMesh::PatchRecoveryErrorEstimator::estimate_error(), libMesh::JumpErrorEstimator::estimate_error(), libMesh::UniformRefinementEstimator::estimate_error(), libMesh::AdjointResidualErrorEstimator::estimate_error(), libMesh::UniformRefinementEstimator::estimate_errors(), libMesh::OldSolutionValue< Output, point_output >::eval_at_node(), libMesh::OldSolutionValue< Output, point_output >::eval_at_point(), libMesh::OldSolutionValue< Output, point_output >::eval_old_dofs(), libMesh::LocationMap< T >::find(), libMesh::MeshCommunication::find_global_indices(), libMesh::UnstructuredMesh::find_neighbors(), libMesh::Parallel::Communicator::gather(), libMesh::TaoOptimizationSolver< T >::get_dual_variables(), libMesh::CondensedEigenSystem::get_eigenpair(), libMesh::BoundaryInfo::get_side_and_node_maps(), libMesh::DofMap::heterogenously_constrain_element_matrix_and_vector(), libMesh::DofMap::heterogenously_constrain_element_vector(), libMesh::StatisticsVector< T >::histogram(), libMesh::LocationMap< T >::init(), libMesh::PetscDiffSolver::init(), libMesh::TopologyMap::init(), libMesh::PointLocatorTree::init(), libMesh::PointLocatorList::init(), libMesh::FrequencySystem::init_data(), libMesh::FEMap::init_edge_shape_functions(), libMesh::FEMap::init_face_shape_functions(), libMesh::InfFE< Dim, T_radial, T_map >::init_radial_shape_functions(), libMesh::FEMap::init_reference_to_physical_map(), libMesh::FE< Dim, T >::init_shape_functions(), libMesh::InfFE< Dim, T_radial, T_map >::init_shape_functions(), libMesh::FESubdivision::init_shape_functions(), libMesh::FEXYZ< Dim >::init_shape_functions(), libMesh::NewmarkSystem::initial_conditions(), libMesh::FE< Dim, T >::inverse_map(), libMesh::InfFE< Dim, T_radial, T_map >::inverse_map(), libMesh::MeshRefinement::make_coarsening_compatible(), libMesh::MeshCommunication::make_elems_parallel_consistent(), libMesh::MeshRefinement::make_flags_parallel_consistent(), libMesh::MeshCommunication::make_node_ids_parallel_consistent(), libMesh::MeshCommunication::make_node_proc_ids_parallel_consistent(), libMesh::MeshCommunication::make_node_unique_ids_parallel_consistent(), libMesh::MeshCommunication::make_p_levels_parallel_consistent(), libMesh::MeshRefinement::make_refinement_compatible(), libMesh::Parallel::Communicator::max(), libMesh::StatisticsVector< T >::maximum(), libMesh::Parallel::Communicator::maxloc(), libMesh::ErrorVector::mean(), libMesh::StatisticsVector< T >::mean(), libMesh::StatisticsVector< T >::median(), libMesh::Parallel::Communicator::min(), libMesh::ErrorVector::minimum(), libMesh::StatisticsVector< T >::minimum(), libMesh::Parallel::Communicator::minloc(), libMesh::UNVIO::nodes_in(), libMesh::FEMSystem::numerical_elem_jacobian(), libMesh::FEMSystem::numerical_nonlocal_jacobian(), libMesh::FEMSystem::numerical_side_jacobian(), libMesh::DofMap::old_dof_indices(), libMesh::GenericProjector< FFunctor, GFunctor, FValue, ProjectionAction >::operator()(), libMesh::PointLocatorList::operator()(), libMesh::PointLocatorTree::operator()(), libMesh::PointLocatorTree::perform_linear_search(), libMesh::FEMSystem::postprocess(), libMesh::DofMap::prepare_send_list(), libMesh::Parallel::Communicator::probe(), libMesh::System::project_vector(), libMesh::NameBasedIO::read(), libMesh::Nemesis_IO::read(), libMesh::CheckpointIO::read(), libMesh::XdrIO::read(), libMesh::MeshData::read(), libMesh::LegacyXdrIO::read_mesh(), libMesh::Parallel::Communicator::receive(), libMesh::MeshTools::Modification::redistribute(), libMesh::DofMap::reinit(), libMesh::SerialMesh::renumber_nodes_and_elements(), libMesh::ParallelMesh::renumber_nodes_and_elements(), libMesh::DofMap::SCALAR_dof_indices(), libMesh::HPSingularity::select_refinement(), libMesh::HPCoarsenTest::select_refinement(), libMesh::Parallel::Communicator::send(), libMesh::Parallel::Communicator::send_receive(), libMesh::Parallel::Communicator::send_receive_packed_range(), libMesh::ImplicitSystem::sensitivity_solve(), libMesh::Partitioner::set_node_processor_ids(), libMesh::Partitioner::set_parent_processor_ids(), libMesh::Partitioner::single_partition(), libMesh::EigenSparseLinearSolver< T >::solve(), libMesh::NewtonSolver::solve(), libMesh::LaspackLinearSolver< T >::solve(), libMesh::PetscDiffSolver::solve(), libMesh::AztecLinearSolver< T >::solve(), libMesh::TaoOptimizationSolver< T >::solve(), libMesh::CondensedEigenSystem::solve(), libMesh::PetscNonlinearSolver< T >::solve(), libMesh::NloptOptimizationSolver< T >::solve(), libMesh::FrequencySystem::solve(), libMesh::PetscLinearSolver< T >::solve(), libMesh::NonlinearImplicitSystem::solve(), libMesh::OptimizationSystem::solve(), libMesh::SerialMesh::stitch_meshes(), libMesh::Parallel::Communicator::sum(), libMesh::BoundaryInfo::sync(), libMesh::MeshData::translate(), libMesh::EquationSystems::update(), libMesh::NewmarkSystem::update_rhs(), libMesh::NewmarkSystem::update_u_v_a(), libMesh::ErrorVector::variance(), libMesh::StatisticsVector< T >::variance(), libMesh::Parallel::Request::wait(), libMesh::ImplicitSystem::weighted_sensitivity_adjoint_solve(), libMesh::ImplicitSystem::weighted_sensitivity_solve(), libMesh::NameBasedIO::write(), libMesh::CheckpointIO::write(), libMesh::XdrIO::write(), libMesh::UnstructuredMesh::write(), libMesh::MeshData::write(), libMesh::EquationSystems::write(), libMesh::MeshOutput< MT >::write_equation_systems(), libMesh::LegacyXdrIO::write_mesh(), libMesh::TecplotIO::write_nodal_data(), libMesh::GnuPlotIO::write_nodal_data(), libMesh::MEDITIO::write_nodal_data(), libMesh::GmshIO::write_nodal_data(), libMesh::Nemesis_IO::write_nodal_data(), libMesh::GMVIO::write_nodal_data(), libMesh::ExodusII_IO::write_nodal_data(), and libMesh::ExodusII_IO::write_nodal_data_discontinuous().
libMesh::SUPERTYPE (unsigned char, short)
libMesh::SUPERTYPE (unsigned char, int)
libMesh::SUPERTYPE (unsigned char, float)
libMesh::SUPERTYPE (unsigned char, double)
libMesh::SUPERTYPE (unsigned char, long double)
libMesh::SUPERTYPE (char , short)
libMesh::SUPERTYPE (char , int)
libMesh::SUPERTYPE (char , float)
libMesh::SUPERTYPE (char , double)
libMesh::SUPERTYPE (char , long double)
libMesh::SUPERTYPE (short , int)
libMesh::SUPERTYPE (short , float)
libMesh::SUPERTYPE (short , double)
libMesh::SUPERTYPE (short , long double)
libMesh::SUPERTYPE (int , float)
libMesh::SUPERTYPE (int , double)
libMesh::SUPERTYPE (int , long double)
libMesh::SUPERTYPE (float , double)
libMesh::SUPERTYPE (float , long double)
libMesh::SUPERTYPE (double , long double)
X_input libMesh::swap (X_system)
Referenced by libMesh::GmshIO::build_element_maps(), libMesh::Utility::deallocate(), libMesh::SystemSubsetBySubdomain::init(), libMesh::DofMap::prepare_send_list(), libMesh::TreeNode< N >::refine(), libMesh::TreeNode< N >::transform_nodes_to_elements(), and libMesh::BuildProjectionList::unique().
J_input libMesh::swap (J_system)
template<typename T > T libMesh::triple_product (const TypeVector< T > & a, const TypeVector< T > & b, const TypeVector< T > & c) inline
Definition at line 1026 of file type_vector.h.
 {
   // We only support cross products when LIBMESH_DIM==3, same goes for this.
   libmesh_assert_equal_to (LIBMESH_DIM, 3);
   return
     a(0)*(b(1)*c(2) - b(2)*c(1)) -
     a(1)*(b(0)*c(2) - b(2)*c(0)) +
     a(2)*(b(0)*c(1) - b(1)*c(0));
 }
bool libMesh::warned_about_auto_ptr (false)
void libMesh::write_traceout ()
Writes a stack trace to a uniquely named file if –enable-tracefiles has been set by configure, otherwise does nothing. Note that we append to the trace file rather than overwriting it. This allows multiple traces to be written to the same file.
Definition at line 216 of file print_trace.C.
References global_processor_id(), and print_trace().
Referenced by libmesh_terminate_handler(), and libMesh::MacroFunctions::report_error().
 {
 #ifdef LIBMESH_ENABLE_TRACEFILES
   std::stringstream outname;
   outname << "traceout_" << static_cast<std::size_t>(libMesh::global_processor_id()) << '_' << getpid() << ".txt";
   std::ofstream traceout(outname.str().c_str(), std::ofstream::app);
   libMesh::print_trace(traceout);
 #endif
 }
PetscVector<Number> libMesh::X_input (x , sys. comm())
Referenced by __libmesh_petsc_diff_solver_residual().
template void libMesh::Xdr::data< std::complex< double > > (std::complex< double > & , const char *)
template void libMesh::Xdr::data< std::complex< float > > (std::complex< float > & , const char *)
template void libMesh::Xdr::data< std::complex< long double > > (std::complex< long double > & , const char *)
template void libMesh::Xdr::data< std::string > (std::string & , const char *)
template void libMesh::Xdr::data< std::vector< char > > (std::vector< char > & , const char *)
template void libMesh::Xdr::data< std::vector< double > > (std::vector< double > & , const char *)
template void libMesh::Xdr::data< std::vector< float > > (std::vector< float > & , const char *)
template void libMesh::Xdr::data< std::vector< int > > (std::vector< int > & , const char *)
template void libMesh::Xdr::data< std::vector< long double > > (std::vector< long double > & , const char *)
template void libMesh::Xdr::data< std::vector< long int > > (std::vector< long int > & , const char *)
template void libMesh::Xdr::data< std::vector< short int > > (std::vector< short int > & , const char *)
template void libMesh::Xdr::data< std::vector< signed char > > (std::vector< signed char > & , const char *)
template void libMesh::Xdr::data< std::vector< std::complex< double > > > (std::vector< std::complex< double > > & , const char *)
template void libMesh::Xdr::data< std::vector< std::complex< float > > > (std::vector< std::complex< float > > & , const char *)
template void libMesh::Xdr::data< std::vector< std::complex< long double > > > (std::vector< std::complex< long double > > & , const char *)
template void libMesh::Xdr::data< std::vector< std::string > > (std::vector< std::string > & , const char *)
template void libMesh::Xdr::data< std::vector< unsigned char > > (std::vector< unsigned char > & , const char *)
template void libMesh::Xdr::data< std::vector< unsigned int > > (std::vector< unsigned int > & , const char *)
template void libMesh::Xdr::data< std::vector< unsigned long int > > (std::vector< unsigned long int > & , const char *)
template void libMesh::Xdr::data< std::vector< unsigned long long > > (std::vector< unsigned long long > & , const char *)
template void libMesh::Xdr::data< std::vector< unsigned short int > > (std::vector< unsigned short int > & , const char *)
Variable Documentation
ParallelMesh::ParallelMesh (unsigned char d) libMesh::_partitioner = UniquePtr<Partitioner>(new ParmetisPartitioner())
Definition at line 51 of file parallel_mesh.C.
template<typename T > void PetscPreconditioner<T>::set_petsc_subpreconditioner_type (PCType type, PC & pc) void PetscPreconditioner<T> Parallel::communicator libMesh::comm
Definition at line 254 of file petsc_preconditioner.C.
Referenced by libMesh::SlepcEigenSolver< T >::_petsc_shell_matrix_get_diagonal(), libMesh::SlepcEigenSolver< T >::_petsc_shell_matrix_mult(), libMesh::SlepcEigenSolver< T >::_solve_generalized_helper(), libMesh::SlepcEigenSolver< T >::_solve_standard_helper(), libMesh::DofMap::add_constraints_to_send_list(), libMesh::EigenSparseLinearSolver< T >::adjoint_solve(), libMesh::PetscLinearSolver< T >::adjoint_solve(), libMesh::DofMap::allgather_recursive_constraints(), libMesh::Parallel::Communicator::assign(), libMesh::Parallel::BinSorter< KeyType, IdxType >::binsort(), libMesh::Parallel::Sort< KeyType, IdxType >::binsort(), libMesh::EigenSolver< T >::build(), libMesh::Preconditioner< T >::build(), libMesh::LinearSolver< T >::build(), libMesh::SparseMatrix< T >::build(), libMesh::NumericVector< T >::build(), libMesh::Parallel::Histogram< KeyType, IdxType >::build_histogram(), libMesh::PetscNonlinearSolver< T >::build_mat_null_space(), libMesh::Parallel::Sort< KeyType, IdxType >::communicate_bins(), libMesh::NumericVector< T >::compare(), libMesh::DofMap::create_dof_constraints(), DMCreateDomainDecomposition_libMesh(), DMCreateDomainDecompositionDM_libMesh(), DMCreateFieldDecomposition_libMesh(), DMCreateFieldDecompositionDM_libMesh(), DMCreateGlobalVector_libMesh(), DMlibMeshCreateDomainDecompositionDM(), DMlibMeshCreateFieldDecompositionDM(), DMlibMeshGetBlocks(), DMlibMeshGetSystem_libMesh(), DMlibMeshGetVariables(), DMlibMeshParseDecompositionDescriptor_Private(), DMlibMeshSetSystem_libMesh(), DMSetUp_libMesh(), DMVariableBounds_libMesh(), DMView_libMesh(), libMesh::DofMap::enforce_adjoint_constraints_exactly(), libMesh::DofMap::enforce_constraints_exactly(), libMesh::DofMap::get_info(), libMesh::NumericVector< T >::global_relative_compare(), if(), libMesh::PetscDiffSolver::init(), libMesh::SlepcEigenSolver< T >::init(), libMesh::PetscPreconditioner< T >::init(), libMesh::TaoOptimizationSolver< T >::init(), libMesh::PetscNonlinearSolver< T >::init(), libMesh::PetscLinearSolver< T >::init(), libMesh::NumericVector< T >::local_relative_compare(), libMesh::DofMap::n_constrained_dofs(), libMesh::SparsityPattern::Build::parallel_sync(), libMesh::SparseMatrix< T >::print(), libMesh::DofMap::print_dof_constraints(), libMesh::PetscLinearSolver< T >::restrict_solve_to(), libMesh::DofMap::scatter_constraints(), libMesh::PetscPreconditioner< T >::set_petsc_preconditioner_type(), libMesh::PetscLinearSolver< T >::solve(), libMesh::SlepcEigenSolver< T >::solve_generalized(), libMesh::SlepcEigenSolver< T >::solve_standard(), libMesh::Parallel::Sort< KeyType, IdxType >::sort(), libMesh::NumericVector< T >::subset_l1_norm(), libMesh::NumericVector< T >::subset_l2_norm(), libMesh::NumericVector< T >::subset_linfty_norm(), libMesh::Parallel::sync_element_data_by_parent_id(), and libMesh::Parallel::sync_node_data_by_element_id().
int libMesh::COMM_WORLD = MPI_COMM_NULL
MPI Communicator to be used in the library.
Something to use with CHKERRABORT if we're just using PETSc's MPI "uni" stub.
Definition at line 184 of file libmesh.C.
Referenced by if().
Parallel::Communicator libMesh::communicator(comm)
Referenced by libMesh::ExactSolution::_compute_error(), libMesh::MeshCommunication::assign_global_indices(), and libMesh::PetscPreconditioner< T >::set_petsc_preconditioner_type().
Parallel::Communicator libMesh::CommWorld
The default libMesh communicator.
If this communicator is disabled, we also disable it as a default argument to functions which accept a default communicator argument. This should expose implicit uses of the default communicator as compile-time rather than run-time errors.
The macro LIBMESH_CAN_DEFAULT_TO_COMMWORLD effects this functionality; it is empty (and so leaves arguments with no default value) if the default is disabled, and it sets something equal to the default otherwise.
Definition at line 195 of file libmesh.C.
Referenced by libMesh::NumericVector< T >::build().
const unsigned char libMesh::cube_number_column
Definition at line 85 of file number_lookups.C.
const unsigned char libMesh::cube_number_page
Definition at line 309 of file number_lookups.C.
const unsigned char libMesh::cube_number_row
Definition at line 197 of file number_lookups.C.
void ExactErrorEstimator::estimate_error (const System & system, ErrorVector & error_per_cell, const NumericVector<Number> * solution_vector, bool estimate_parent_error) void ExactErrorEstimator const unsigned in libMesh::dim) = mesh.mesh_dimension()
Definition at line 216 of file exact_error_estimator.C.
Referenced by libMesh::ExactSolution::_compute_error(), libMesh::FEMContext::_do_elem_position_set(), libMesh::DofMap::_dof_indices(), libMesh::UniformRefinementEstimator::_estimate_error(), libMesh::EquationSystems::build_discontinuous_solution_vector(), libMesh::EquationSystems::build_solution_vector(), libMesh::EquationSystems::build_variable_names(), libMesh::System::calculate_norm(), libMesh::JumpErrorEstimator::coarse_n_flux_faces_increment(), libMesh::FEGenericBase< OutputType >::coarsened_dof_values(), libMesh::FEXYZ< Dim >::compute_face_values(), libMesh::FEGenericBase< OutputType >::compute_shape_functions(), libMesh::InfFE< Dim, T_radial, T_map >::compute_shape_functions(), libMesh::FEXYZ< Dim >::compute_shape_functions(), libMesh::FEMContext::elem_fe_reinit(), libMesh::FEMContext::elem_position_get(), libMesh::JumpErrorEstimator::estimate_error(), libMesh::FEMContext::FEMContext(), libMesh::MeshRefinement::flag_elements_by_elem_fraction(), libMesh::MeshRefinement::flag_elements_by_nelem_target(), libMesh::FEMContext::get_element_fe(), libMesh::FEMContext::get_element_qrule(), libMesh::FEMContext::get_side_fe(), libMesh::FEMContext::get_side_qrule(), libMesh::MeshFunction::gradient(), libMesh::MeshFunction::hessian(), libMesh::XdrMESH::init(), libMesh::LaplacianErrorEstimator::init_context(), libMesh::DiscontinuityMeasure::init_context(), libMesh::KellyErrorEstimator::init_context(), libMesh::OldSolutionValue< Output, point_output >::init_context(), libMesh::LaplacianErrorEstimator::internal_side_integration(), libMesh::Elem::level(), libMesh::DofMap::old_dof_indices(), libMesh::GenericProjector< FFunctor, GFunctor, FValue, ProjectionAction >::operator()(), libMesh::WeightedPatchRecoveryErrorEstimator::EstimateError::operator()(), libMesh::PatchRecoveryErrorEstimator::EstimateError::operator()(), libMesh::MeshFunction::operator()(), libMesh::BoundaryProjectSolution::operator()(), libMesh::FE< Dim, T >::reinit(), libMesh::InfFE< Dim, T_radial, T_map >::reinit(), libMesh::DofMap::reinit(), libMesh::JumpErrorEstimator::reinit_sides(), libMesh::HPCoarsenTest::select_refinement(), libMesh::Side< SideType, ParentType >::Side(), libMesh::FEMContext::side_fe_reinit(), libMesh::SideEdge< EdgeType, ParentType >::SideEdge(), libMesh::ExodusII_IO_Helper::write_as_dimension(), libMesh::EnsightIO::write_scalar_ascii(), and libMesh::EnsightIO::write_vector_ascii().
const DofMap& libMesh::dof_map = system.get_dof_map()
Definition at line 222 of file exact_error_estimator.C.
Referenced by __libmesh_petsc_snes_postcheck(), libMesh::UniformRefinementEstimator::_estimate_error(), libMesh::HPCoarsenTest::add_projection(), libMesh::EquationSystems::allgather(), libMesh::SparseMatrix< Number >::attach_dof_map(), libMesh::EquationSystems::build_solution_vector(), libMesh::JumpErrorEstimator::estimate_error(), libMesh::AdjointRefinementEstimator::estimate_error(), libMesh::EquationSystems::get_solution(), libMesh::SystemSubsetBySubdomain::init(), libMesh::EigenSystem::init_matrices(), libMesh::ImplicitSystem::init_matrices(), libMesh::CondensedEigenSystem::initialize_condensed_dofs(), libMesh::SparsityPattern::Build::join(), libMesh::GenericProjector< FFunctor, GFunctor, FValue, ProjectionAction >::operator()(), libMesh::WeightedPatchRecoveryErrorEstimator::EstimateError::operator()(), libMesh::PatchRecoveryErrorEstimator::EstimateError::operator()(), libMesh::SparsityPattern::Build::parallel_sync(), libMesh::System::point_gradient(), libMesh::System::point_hessian(), libMesh::System::point_value(), libMesh::System::project_vector(), libMesh::System::read_parallel_data(), libMesh::System::read_SCALAR_dofs(), libMesh::ImplicitSystem::reinit(), libMesh::EigenSystem::reinit(), libMesh::HPCoarsenTest::select_refinement(), libMesh::System::write_parallel_data(), libMesh::EnsightIO::write_scalar_ascii(), libMesh::System::write_SCALAR_dofs(), and libMesh::EnsightIO::write_vector_ascii().
libMesh::EIGEN_SOLVERS
Definition at line 249 of file libmesh.C.
Referenced by libMesh::Preconditioner< T >::build(), libMesh::LinearSolver< T >::build(), libMesh::SparseMatrix< T >::build(), libMesh::NumericVector< T >::build(), and default_solver_package().
OStreamProxy libMesh::err
Definition at line 235 of file libmesh_common.h.
Referenced by libMesh::ExactSolution::_compute_error(), libMesh::MetisPartitioner::_do_partition(), libMesh::SFCPartitioner::_do_partition(), libMesh::ParmetisPartitioner::_do_repartition(), libMesh::MeshData::activate(), libMesh::LaspackLinearSolver< T >::adjoint_solve(), libMesh::MeshTools::Modification::all_tri(), libMesh::FEMSystem::assembly(), libMesh::MeshCommunication::assign_global_indices(), libMesh::Factory< Base >::build(), libMesh::Patch::build_around_element(), cast_ptr(), cast_ref(), libMesh::ExodusII_IO_Helper::check_existing_vars(), libMesh::MeshCommunication::check_for_duplicate_global_indices(), libMesh::Elem::contains_point(), libMesh::GMVIO::copy_nodal_solution(), libMesh::ElemCutter::cut_2D(), libMesh::ElemCutter::cut_3D(), libMesh::MeshData::enable_compatibility_mode(), libMesh::ParsedFunction< Output, OutputGradient >::eval(), libMesh::ParsedFEMFunction< Output >::eval(), libMesh::UnstructuredMesh::find_neighbors(), libMesh::PetscLinearSolver< T >::get_converged_reason(), libMesh::PetscLinearSolver< T >::get_initial_residual(), libMesh::UNVIO::groups_in(), libMesh::MacroFunctions::here(), if(), libMesh::PointLocatorTree::init(), libMesh::PointLocatorList::init(), libMesh::InfFE< Dim, T_radial, T_map >::init_shape_functions(), libMesh::ExodusII_IO_Helper::initialize(), libMesh::FEInterface::inverse_map(), libMesh::FE< Dim, T >::inverse_map(), libMesh::InfFE< Dim, T_radial, T_map >::inverse_map(), libMesh::InfFE< Dim, T_radial, T_map >::nodal_soln(), libMesh::MeshDataUnvHeader::operator=(), libMesh::ErrorVector::plot_error(), libMesh::TetGenMeshInterface::process_hull_integrity_result(), libMesh::Elem::quality(), libMesh::Nemesis_IO::read(), libMesh::GMVIO::read(), libMesh::MeshData::read(), libMesh::LegacyXdrIO::read_binary(), libMesh::ExodusII_IO_Helper::read_elemental_var_values(), libMesh::PltLoader::read_header(), libMesh::GmshIO::read_mesh(), libMesh::ExodusII_IO_Helper::read_nodal_var_values(), libMesh::DofMap::reinit(), libMesh::MacroFunctions::report_error(), libMesh::LaspackLinearSolver< T >::set_laspack_preconditioner_type(), libMesh::PetscPreconditioner< T >::set_petsc_preconditioner_type(), libMesh::PetscLinearSolver< T >::set_petsc_solver_type(), libMesh::SlepcEigenSolver< T >::set_slepc_problem_type(), libMesh::SlepcEigenSolver< T >::set_slepc_solver_type(), libMesh::AztecLinearSolver< T >::set_solver_type(), libMesh::InfFE< Dim, T_radial, T_map >::shape(), libMesh::FE< Dim, T >::shape_second_deriv(), libMesh::MeshData::slim(), libMesh::EigenSparseLinearSolver< T >::solve(), libMesh::LaspackLinearSolver< T >::solve(), libMesh::VTKIO::system_vectors_to_vtk(), libMesh::NameBasedIO::write(), libMesh::MeshData::write(), libMesh::GMVIO::write_ascii_new_impl(), libMesh::GMVIO::write_ascii_old_impl(), libMesh::TecplotIO::write_binary(), libMesh::LegacyXdrIO::write_binary(), libMesh::GMVIO::write_binary(), libMesh::GMVIO::write_discontinuous_gmv(), libMesh::UNVIO::write_implementation(), libMesh::ExodusII_IO_Helper::write_information_records(), libMesh::VTKIO::write_nodal_data(), libMesh::NameBasedIO::write_nodal_data(), libMesh::GmshIO::write_post(), libMesh::DivaIO::write_stream(), and libMesh::MeshData::write_unv_implementation().
DIE A HORRIBLE DEATH HERE typedef float libMesh::ErrorVectorReal
Definition at line 195 of file libmesh_common.h.
Referenced by libMesh::UniformRefinementEstimator::_estimate_error(), libMesh::JumpErrorEstimator::estimate_error(), libMesh::AdjointRefinementEstimator::estimate_error(), libMesh::AdjointResidualErrorEstimator::estimate_error(), libMesh::MeshRefinement::flag_elements_by_elem_fraction(), libMesh::MeshRefinement::flag_elements_by_error_fraction(), libMesh::MeshRefinement::flag_elements_by_error_tolerance(), libMesh::MeshRefinement::flag_elements_by_mean_stddev(), for(), libMesh::ErrorVector::minimum(), libMesh::WeightedPatchRecoveryErrorEstimator::EstimateError::operator()(), libMesh::PatchRecoveryErrorEstimator::EstimateError::operator()(), and libMesh::HPCoarsenTest::select_refinement().
int libMesh::GLOBAL_COMM_WORLD = MPI_COMM_NULL
MPI Communicator used to initialize libMesh.
Something to use with CHKERRABORT if we're just using PETSc's MPI "uni" stub.
Definition at line 186 of file libmesh.C.
Referenced by if(), and libmesh_terminate_handler().
libMesh::ierr = PCSetUp(pc)
Definition at line 274 of file petsc_preconditioner.C.
Referenced by __libmesh_petsc_diff_solver_monitor(), __libmesh_petsc_preconditioner_apply(), __libmesh_petsc_preconditioner_setup(), __libmesh_petsc_snes_jacobian(), __libmesh_petsc_snes_postcheck(), __libmesh_petsc_snes_residual(), __libmesh_tao_equality_constraints(), __libmesh_tao_equality_constraints_jacobian(), __libmesh_tao_gradient(), __libmesh_tao_hessian(), __libmesh_tao_inequality_constraints(), __libmesh_tao_inequality_constraints_jacobian(), __libmesh_tao_objective(), libMesh::PetscLinearSolver< T >::_create_complement_is(), libMesh::PetscLinearSolver< T >::_petsc_shell_matrix_get_diagonal(), libMesh::SlepcEigenSolver< T >::_petsc_shell_matrix_get_diagonal(), libMesh::PetscLinearSolver< T >::_petsc_shell_matrix_mult(), libMesh::SlepcEigenSolver< T >::_petsc_shell_matrix_mult(), libMesh::PetscLinearSolver< T >::_petsc_shell_matrix_mult_add(), libMesh::PetscLinearSolver< T >::_restrict_solve_to_is_local_size(), libMesh::SlepcEigenSolver< T >::_solve_generalized_helper(), libMesh::SlepcEigenSolver< T >::_solve_standard_helper(), libMesh::PetscLinearSolver< T >::adjoint_solve(), libMesh::PetscPreconditioner< T >::apply(), libMesh::SlepcEigenSolver< T >::attach_deflation_space(), libMesh::PetscNonlinearSolver< T >::build_mat_null_space(), libMesh::SlepcEigenSolver< T >::clear(), libMesh::PetscPreconditioner< T >::clear(), libMesh::TaoOptimizationSolver< T >::clear(), libMesh::PetscNonlinearSolver< T >::clear(), libMesh::PetscLinearSolver< T >::clear(), DMCreate_libMesh(), DMCreateDomainDecomposition_libMesh(), DMCreateDomainDecompositionDM_libMesh(), DMCreateFieldDecomposition_libMesh(), DMCreateFieldDecompositionDM_libMesh(), DMCreateGlobalVector_libMesh(), DMDestroy_libMesh(), DMlibMeshCreateDomainDecompositionDM(), DMlibMeshCreateFieldDecompositionDM(), DMlibMeshFunction(), DMlibMeshGetBlocks(), DMlibMeshGetSystem_libMesh(), DMlibMeshGetVariables(), DMlibMeshJacobian(), DMlibMeshParseDecompositionDescriptor_Private(), DMlibMeshSetSystem_libMesh(), DMlibMeshSetUpName_Private(), DMSetUp_libMesh(), DMVariableBounds_libMesh(), DMView_libMesh(), libMesh::TaoOptimizationSolver< T >::get_converged_reason(), libMesh::PetscNonlinearSolver< T >::get_converged_reason(), libMesh::TaoOptimizationSolver< T >::get_dual_variables(), libMesh::SlepcEigenSolver< T >::get_eigenpair(), libMesh::SlepcEigenSolver< T >::get_eigenvalue(), libMesh::PetscLinearSolver< T >::get_initial_residual(), libMesh::SlepcEigenSolver< T >::get_relative_error(), libMesh::PetscLinearSolver< T >::get_residual_history(), if(), libMesh::SlepcEigenSolver< T >::init(), libMesh::PetscPreconditioner< T >::init(), libMesh::TaoOptimizationSolver< T >::init(), libMesh::PetscNonlinearSolver< T >::init(), libMesh::PetscLinearSolver< T >::init(), libMesh::GMVIO::read(), libMesh::PetscLinearSolver< T >::restrict_solve_to(), libMesh::PetscPreconditioner< T >::set_petsc_preconditioner_type(), libMesh::PetscLinearSolver< T >::set_petsc_solver_type(), libMesh::SlepcEigenSolver< T >::set_slepc_position_of_spectrum(), libMesh::SlepcEigenSolver< T >::set_slepc_problem_type(), libMesh::SlepcEigenSolver< T >::set_slepc_solver_type(), SNESFunction_DMlibMesh(), SNESJacobian_DMlibMesh(), libMesh::TaoOptimizationSolver< T >::solve(), libMesh::PetscNonlinearSolver< T >::solve(), libMesh::NloptOptimizationSolver< T >::solve(), libMesh::PetscLinearSolver< T >::solve(), libMesh::SlepcEigenSolver< T >::solve_generalized(), libMesh::SlepcEigenSolver< T >::solve_standard(), and libMesh::TecplotIO::write_binary().
libMesh::if inline
Definition at line 1420 of file elem.h.
     {
       for (unsigned int n=0; n<nn; n++)
         _nodes[n] = libmesh_nullptr;
     }
const Number libMesh::imaginary
The imaginary unit, .
libMesh::INSTANTIATE_SUBDIVISION_FE
Definition at line 596 of file fe.C.
libMesh::INSTANTIATE_SUBDIVISION_MAPS
Definition at line 1827 of file fe_map.C.
libMesh::INVALID_SOLVER_PACKAGE
Definition at line 253 of file libmesh.C.
Referenced by default_solver_package().
const unsigned int libMesh::invalid_uint = static_cast<unsigned int>(-1)
A number which is used quite often to represent an invalid or uninitialized value.
Definition at line 172 of file libmesh.h.
Referenced by libMesh::FEMContext::_do_elem_position_set(), libMesh::UniformRefinementEstimator::_estimate_error(), libMesh::MeshRefinement::add_node(), libMesh::Elem::as_parent_node(), libMesh::CompositeFunction< Output >::attach_subfunction(), libMesh::CompositeFEMFunction< Output >::attach_subfunction(), libMesh::CompositeFEMFunction< Output >::component(), libMesh::CompositeFunction< Output >::component(), libMesh::InfFE< Dim, T_radial, T_map >::compute_node_indices_fast(), libMesh::FEGenericBase< OutputType >::compute_periodic_constraints(), libMesh::FEAbstract::compute_periodic_node_constraints(), libMesh::InfFE< Dim, T_radial, T_map >::compute_shape_indices(), libMesh::Xdr::data_stream(), libMesh::FEMContext::elem_position_get(), libMesh::MeshTools::find_nodal_neighbors(), libMesh::MeshRefinement::flag_elements_by_elem_fraction(), libMesh::MeshRefinement::flag_elements_by_error_fraction(), libMesh::MeshRefinement::flag_elements_by_mean_stddev(), libMesh::Elem::get_node_index(), libMesh::DofObject::has_dofs(), libMesh::MeshTools::Generation::Private::idx(), libMesh::ParallelMesh::libmesh_assert_valid_parallel_flags(), libMesh::ParallelMesh::libmesh_assert_valid_parallel_p_levels(), libMesh::Elem::local_node(), libMesh::FEMSystem::mesh_position_get(), libMesh::DofObject::n_dofs(), libMesh::Quad9::n_second_order_adjacent_vertices(), libMesh::FEMSystem::numerical_jacobian(), libMesh::DofMap::old_dof_indices(), libMesh::Elem::parent_bracketing_nodes(), libMesh::MeshDataUnvHeader::read(), libMesh::System::read_serialized_blocked_dof_objects(), libMesh::FE< Dim, T >::shape_second_deriv(), libMesh::BoundaryInfo::side_with_boundary_id(), libMesh::Node::valence(), libMesh::Elem::which_child_am_i(), libMesh::Elem::which_neighbor_am_i(), libMesh::Elem::which_side_am_i(), and libMesh::System::write_serialized_blocked_dof_objects().
PetscMatrix<Number>& libMesh::J_system
Initial value:
=
      *cast_ptr<PetscMatrix<Number> *>(sys.matrix)
Definition at line 169 of file petsc_diff_solver.C.
libMesh::LASPACK_SOLVERS
Definition at line 251 of file libmesh.C.
Referenced by libMesh::LinearSolver< T >::build(), libMesh::SparseMatrix< T >::build(), libMesh::NumericVector< T >::build(), and default_solver_package().
MPI_Errhandler libMesh::libmesh_errhandler
Definition at line 236 of file libmesh.C.
const unsigned int libMesh::MIN_ELEM_PER_PROC = 4
Definition at line 61 of file parmetis_partitioner.C.
PetscInt libMesh::n_local
Definition at line 281 of file petsc_preconditioner.C.
Referenced by libMesh::CondensedEigenSystem::get_eigenpair(), libMesh::ParallelMesh::parallel_n_elem(), and libMesh::ParallelMesh::parallel_n_nodes().
unsigned int libMesh::n_threads = "--n_threads" inline
Definition at line 357 of file libmesh.C.
Referenced by libMesh::FEMContext::_do_elem_position_set(), libMesh::FEMContext::elem_position_get(), libMesh::FEMContext::elem_reinit(), libMesh::MeshBase::get_info(), if(), libMesh::Threads::num_pthreads(), libMesh::FE< Dim, T >::shape(), libMesh::FE< Dim, T >::shape_deriv(), and libMesh::FE< Dim, T >::shape_second_deriv().
const unsigned int libMesh::n_vars = system.n_vars()
Definition at line 219 of file exact_error_estimator.C.
Referenced by libMesh::UniformRefinementEstimator::_estimate_error(), libMesh::DofMap::add_neighbors_to_send_list(), libMesh::WrappedFunction< Output >::component(), libMesh::DofMap::dof_indices(), libMesh::JumpErrorEstimator::estimate_error(), libMesh::AdjointResidualErrorEstimator::estimate_error(), libMesh::ErrorEstimator::estimate_errors(), libMesh::LaplacianErrorEstimator::init_context(), libMesh::DiscontinuityMeasure::init_context(), libMesh::KellyErrorEstimator::init_context(), libMesh::DofMap::old_dof_indices(), libMesh::WrappedFunction< Output >::operator()(), libMesh::WeightedPatchRecoveryErrorEstimator::EstimateError::operator()(), libMesh::PatchRecoveryErrorEstimator::EstimateError::operator()(), libMesh::JumpErrorEstimator::reinit_sides(), libMesh::HPCoarsenTest::select_refinement(), libMesh::MEDITIO::write_ascii(), libMesh::TecplotIO::write_ascii(), libMesh::GMVIO::write_ascii_new_impl(), libMesh::GMVIO::write_ascii_old_impl(), libMesh::TecplotIO::write_binary(), libMesh::GMVIO::write_binary(), libMesh::GMVIO::write_discontinuous_gmv(), libMesh::GmshIO::write_post(), and libMesh::GnuPlotIO::write_solution().
std::terminate_handler libMesh::old_terminate_handler
Definition at line 275 of file libmesh.C.
Referenced by libmesh_terminate_handler().
OStreamProxy libMesh::out
Definition at line 234 of file libmesh_common.h.
Referenced by __libmesh_nlopt_objective(), __libmesh_petsc_diff_solver_monitor(), __libmesh_petsc_diff_solver_residual(), __libmesh_petsc_snes_monitor(), libMesh::FEMSystem::assembly(), libMesh::System::attach_assemble_function(), libMesh::System::attach_assemble_object(), libMesh::System::attach_constraint_function(), libMesh::System::attach_constraint_object(), libMesh::System::attach_init_function(), libMesh::System::attach_init_object(), libMesh::System::attach_QOI_derivative(), libMesh::System::attach_QOI_derivative_object(), libMesh::System::attach_QOI_function(), libMesh::System::attach_QOI_object(), libMesh::Parallel::Sort< KeyType, IdxType >::bin(), libMesh::QBase::build(), libMesh::Nemesis_IO_Helper::build_element_and_node_maps(), libMesh::InfElemBuilder::build_inf_elem(), libMesh::BoundaryInfo::build_side_list_from_node_list(), libMesh::DofMap::build_sparsity(), libMesh::ExodusII_IO_Helper::check_existing_vars(), libMesh::MeshRefinement::coarsen_elements(), libMesh::EquationSystems::compare(), libMesh::System::compare(), libMesh::Nemesis_IO_Helper::compute_border_node_ids(), libMesh::Nemesis_IO_Helper::compute_communication_map_parameters(), libMesh::Nemesis_IO_Helper::compute_internal_and_border_elems_and_internal_nodes(), libMesh::Nemesis_IO_Helper::compute_node_communication_maps(), libMesh::Nemesis_IO_Helper::compute_num_global_elem_blocks(), libMesh::Nemesis_IO_Helper::compute_num_global_nodesets(), libMesh::Nemesis_IO_Helper::compute_num_global_sidesets(), libMesh::Nemesis_IO_Helper::construct_nemesis_filename(), libMesh::ContinuationSystem::continuation_solve(), libMesh::ExodusII_IO_Helper::create(), libMesh::Nemesis_IO_Helper::create(), libMesh::UnstructuredMesh::create_pid_mesh(), libMesh::DofObject::debug_buffer(), libMesh::UNVIO::elements_in(), libMesh::UNVIO::elements_out(), libMesh::Nemesis_IO_Helper::get_cmap_params(), libMesh::Nemesis_IO_Helper::get_eb_info_global(), libMesh::Nemesis_IO_Helper::get_elem_cmap(), libMesh::Nemesis_IO_Helper::get_elem_map(), libMesh::Nemesis_IO_Helper::get_init_global(), libMesh::Nemesis_IO_Helper::get_init_info(), libMesh::Nemesis_IO_Helper::get_loadbal_param(), libMesh::Nemesis_IO_Helper::get_node_cmap(), libMesh::Nemesis_IO_Helper::get_node_map(), libMesh::Nemesis_IO_Helper::get_ns_param_global(), libMesh::Nemesis_IO_Helper::get_ss_param_global(), libMesh::Utility::get_timestamp(), libMesh::StatisticsVector< T >::histogram(), if(), libMesh::XdrMGF::init(), libMesh::ContinuationSystem::initialize_tangent(), libMesh::NewtonSolver::line_search(), libMesh::Parallel::Communicator::maxloc(), libMesh::MeshInput< MT >::MeshInput(), libMesh::MeshOutput< MT >::MeshOutput(), libMesh::ExodusII_IO_Helper::message(), libMesh::Parallel::Communicator::minloc(), libMesh::UNVIO::nodes_in(), libMesh::UNVIO::nodes_out(), libMesh::Xdr::open(), libMesh::ExodusII_IO_Helper::open(), libMesh::PointLocatorTree::operator()(), libMesh::DofMap::prepare_send_list(), libMesh::TaoOptimizationSolver< T >::print_converged_reason(), libMesh::NloptOptimizationSolver< T >::print_converged_reason(), libMesh::PetscNonlinearSolver< T >::print_converged_reason(), libMesh::LaspackLinearSolver< T >::print_converged_reason(), libMesh::LinearSolver< T >::print_converged_reason(), libMesh::NewtonSolver::print_convergence(), libMesh::ExodusII_IO_Helper::print_header(), libMesh::PerfLog::print_log(), libMesh::Nemesis_IO_Helper::put_node_cmap(), libMesh::Tet::qual_bounds(), libMesh::Hex::qual_bounds(), libMesh::Tri::qual_bounds(), libMesh::Quad::qual_bounds(), libMesh::InfQuad::qual_bounds(), libMesh::TetGenIO::read(), libMesh::Nemesis_IO::read(), libMesh::PltLoader::read(), libMesh::EquationSystems::read(), libMesh::PltLoader::read_data(), libMesh::ExodusII_IO_Helper::read_elem_in_block(), libMesh::ExodusII_IO_Helper::read_elem_num_map(), libMesh::PltLoader::read_header(), libMesh::System::read_header(), libMesh::UNVIO::read_implementation(), libMesh::ExodusII_IO_Helper::read_node_num_map(), libMesh::ExodusII_IO_Helper::read_qa_records(), libMesh::ExodusII_IO_Helper::read_var_names_impl(), libMesh::VariationalMeshSmoother::readgr(), libMesh::MeshRefinement::refine_and_coarsen_elements(), libMesh::MeshRefinement::refine_elements(), libMesh::TetGenWrapper::set_switches(), libMesh::ContinuationSystem::set_Theta(), libMesh::ContinuationSystem::set_Theta_LOCA(), libMesh::TwostepTimeSolver::solve(), libMesh::EigenSparseLinearSolver< T >::solve(), libMesh::NewtonSolver::solve(), libMesh::UnsteadySolver::solve(), libMesh::EigenTimeSolver::solve(), libMesh::NloptOptimizationSolver< T >::solve(), libMesh::ContinuationSystem::solve_tangent(), libMesh::SerialMesh::stitching_helper(), libMesh::MacroFunctions::stop(), libMesh::MeshRefinement::test_level_one(), libMesh::MeshRefinement::test_unflagged(), libMesh::ContinuationSystem::update_solution(), libMesh::Nemesis_IO::write(), libMesh::ExodusII_IO::write(), libMesh::XdrIO::write(), libMesh::TecplotIO::write_ascii(), libMesh::ExodusII_IO_Helper::write_elements(), libMesh::MeshOutput< MT >::write_equation_systems(), libMesh::Nemesis_IO::write_nodal_data(), libMesh::ExodusII_IO::write_nodal_data_common(), libMesh::Nemesis_IO_Helper::write_nodesets(), libMesh::GmshIO::write_post(), libMesh::Nemesis_IO_Helper::write_sidesets(), libMesh::ExodusII_IO_Helper::write_var_names_impl(), and libMesh::VariationalMeshSmoother::writegr().
Threads::spin_mutex libMesh::parent_bracketing_nodes_mutex
Definition at line 78 of file elem.C.
Threads::spin_mutex libMesh::parent_indices_mutex
Definition at line 77 of file elem.C.
PetscErrorCode Vec Mat Mat libMesh::pc
Definition at line 144 of file petsc_diff_solver.C.
Referenced by libMesh::PetscNonlinearSolver< T >::init(), libMesh::PetscLinearSolver< T >::init_names(), libMesh::ImplicitSystem::sensitivity_solve(), libMesh::TrilinosPreconditioner< T >::set_preconditioner_type(), and libMesh::NoxNonlinearSolver< T >::solve().
PerfLog libMesh::perflog
A PerfLog object to log performance. If the library is configured with –enable-perflog then it will log key functions.
Definition at line 39 of file libmesh_logging.h.
Referenced by libmesh_terminate_handler().
const Real libMesh::pi
Initial value:
=
  static_cast<Real>(3.1415926535897932384626433832795029L)
.
Definition at line 160 of file libmesh.h.
Referenced by libMesh::InfFE< Dim, T_radial, T_map >::compute_data(), libMesh::MeshTools::Generation::Private::GaussLobattoRedistributionFunction::GaussLobattoRedistributionFunction(), libMesh::FESubdivision::loop_subdivision_mask(), libMesh::Tri3::min_and_max_angle(), libMesh::TriangleInterface::PolygonHole::point(), libMesh::VariationalMeshSmoother::readgr(), libMesh::MeshTools::Modification::rotate(), and libMesh::Sphere::surface_coords().
DIE A HORRIBLE DEATH HERE typedef LIBMESH_DEFAULT_SCALAR_TYPE libMesh::Real
Definition at line 131 of file libmesh_common.h.
Referenced by __libmesh_nlopt_objective(), libMesh::ExactSolution::_compute_error(), libMesh::UniformRefinementEstimator::_estimate_error(), libMesh::NewmarkSolver::_general_residual(), libMesh::DenseMatrix< T >::_lu_decompose(), libMesh::DenseMatrix< T >::_svd_solve_lapack(), libMesh::FEMContext::_update_time_from_system(), libMesh::Plane::above_surface(), libMesh::MeshTools::Subdivision::add_boundary_ghosts(), libMesh::ImplicitSystem::adjoint_qoi_parameter_sensitivity(), libMesh::UnstructuredMesh::all_second_order(), libMesh::ContinuationSystem::apply_predictor(), libMesh::ImplicitSystem::assemble_residual_derivatives(), libMesh::FEMSystem::assembly(), libMesh::DiscontinuityMeasure::boundary_side_integration(), libMesh::KellyErrorEstimator::boundary_side_integration(), libMesh::MeshTools::bounding_sphere(), libMesh::TreeNode< N >::bounds_point(), libMesh::MeshTools::Generation::build_delaunay_square(), libMesh::InfElemBuilder::build_inf_elem(), libMesh::SystemNorm::calculate_norm(), libMesh::System::calculate_norm(), libMesh::OldSolutionValue< Output, point_output >::check_old_context(), libMesh::Tet::choose_diagonal(), libMesh::NewmarkSystem::clear(), libMesh::InfFE< Dim, T_radial, T_map >::compute_data(), libMesh::FEMap::compute_edge_map(), libMesh::FEXYZMap::compute_face_map(), libMesh::FEMap::compute_face_map(), libMesh::FEAbstract::compute_node_constraints(), libMesh::FEGenericBase< OutputType >::compute_periodic_constraints(), libMesh::FEAbstract::compute_periodic_node_constraints(), libMesh::FEGenericBase< OutputType >::compute_proj_constraints(), libMesh::FEMap::compute_single_point_map(), libMesh::MeshTools::BoundingBox::contains_point(), libMesh::InfQuad4::contains_point(), libMesh::ContinuationSystem::continuation_solve(), libMesh::ExodusII_IO_Helper::create(), libMesh::Nemesis_IO_Helper::create(), libMesh::TreeNode< N >::create_bounding_box(), libMesh::XdrMGF::dataBlk(), libMesh::DenseMatrix< T >::det(), libMesh::Sphere::distance(), libMesh::EquationSystems::EquationSystems(), libMesh::AdjointRefinementEstimator::estimate_error(), libMesh::AdjointResidualErrorEstimator::estimate_error(), libMesh::MeshCommunication::find_global_indices(), libMesh::ElemCutter::find_intersection_points(), libMesh::UnstructuredMesh::find_neighbors(), libMesh::ExactErrorEstimator::find_squared_element_error(), libMesh::MeshRefinement::flag_elements_by_elem_fraction(), libMesh::MeshRefinement::flag_elements_by_error_fraction(), libMesh::MeshRefinement::flag_elements_by_error_tolerance(), libMesh::MeshRefinement::flag_elements_by_mean_stddev(), libMesh::MeshRefinement::flag_elements_by_nelem_target(), libMesh::ImplicitSystem::forward_qoi_parameter_sensitivity(), libMesh::ParsedFunction< Output, OutputGradient >::get_inline_value(), libMesh::ParsedFEMFunction< Output >::get_inline_value(), libMesh::ImplicitSystem::get_linear_solve_parameters(), libMesh::PerfLog::get_perf_info(), libMesh::BoundaryInfo::get_side_and_node_maps(), libMesh::NumericVector< T >::global_relative_compare(), libMesh::FEHermite< Dim >::hermite_raw_shape(), libMesh::FEHermite< Dim >::hermite_raw_shape_deriv(), libMesh::FEHermite< Dim >::hermite_raw_shape_second_deriv(), libMesh::StatisticsVector< T >::histogram(), libMesh::Elem::hmax(), libMesh::Elem::hmin(), libMesh::PointLocatorTree::init(), libMesh::FEComputeData::init(), libMesh::QSimpson::init_1D(), libMesh::QSimpson::init_2D(), libMesh::QGauss::init_2D(), libMesh::QGauss::init_3D(), libMesh::QSimpson::init_3D(), libMesh::FESubdivision::init_shape_functions(), libMesh::ContinuationSystem::initialize_tangent(), libMesh::LaplacianErrorEstimator::internal_side_integration(), libMesh::DiscontinuityMeasure::internal_side_integration(), libMesh::KellyErrorEstimator::internal_side_integration(), libMesh::MeshTools::BoundingBox::intersect(), libMesh::FE< Dim, T >::inverse_map(), libMesh::InfFE< Dim, T_radial, T_map >::inverse_map(), libMesh::Tet::is_child_on_side_helper(), libMesh::ElemCutter::is_cut(), libMesh::QGauss::keast_rule(), libMesh::LocationMap< T >::key(), libMesh::DenseSubVector< T >::l1_norm(), libMesh::DenseVector< T >::l1_norm(), libMesh::DenseMatrix< T >::l1_norm(), libMesh::StatisticsVector< T >::l2_norm(), libMesh::DenseSubVector< T >::l2_norm(), libMesh::DenseVector< T >::l2_norm(), libMesh::NewtonSolver::line_search(), libMesh::DenseSubVector< T >::linfty_norm(), libMesh::DenseVector< T >::linfty_norm(), libMesh::DenseMatrix< T >::linfty_norm(), libMesh::FESubdivision::loop_subdivision_mask(), libMesh::InfFE< Dim, T_radial, T_map >::map(), libMesh::HCurlFETransformation< OutputShape >::map_curl(), libMesh::H1FETransformation< OutputShape >::map_curl(), libMesh::H1FETransformation< OutputShape >::map_div(), libMesh::libmesh_final< T >::master_point(), libMesh::DenseSubVector< T >::max(), libMesh::DenseVector< T >::max(), libMesh::DenseMatrix< T >::max(), libMesh::DofMap::max_constraint_error(), libMesh::ErrorVector::mean(), libMesh::StatisticsVector< T >::mean(), libMesh::StatisticsVector< T >::median(), libMesh::VariationalMeshSmoother::metr_data_gen(), libMesh::DenseSubVector< T >::min(), libMesh::DenseVector< T >::min(), libMesh::DenseMatrix< T >::min(), libMesh::Tri3::min_and_max_angle(), libMesh::NewmarkSystem::NewmarkSystem(), libMesh::TetGenIO::node_in(), libMesh::UNVIO::nodes_out(), libMesh::NonlinearImplicitSystem::NonlinearImplicitSystem(), libMesh::TypeTensor< T >::norm_sq(), libMesh::StatisticsVector< T >::normalize(), libMesh::FEMSystem::numerical_jacobian(), libMesh::FEMSystem::numerical_jacobian_h_for_var(), libMesh::FEAbstract::on_reference_element(), libMesh::Plane::on_surface(), libMesh::ExodusII_IO_Helper::open(), LIBMESH_DEFINE_HASH_POINTERS::FuzzyPointCompare::operator()(), libMesh::GenericProjector< FFunctor, GFunctor, FValue, ProjectionAction >::operator()(), libMesh::PointLocatorList::operator()(), libMesh::WeightedPatchRecoveryErrorEstimator::EstimateError::operator()(), libMesh::PatchRecoveryErrorEstimator::EstimateError::operator()(), libMesh::MeshTools::Generation::Private::GaussLobattoRedistributionFunction::operator()(), libMesh::Parallel::Packing< const Node * >::pack(), libMesh::Node::packed_size(), libMesh::ParsedFunction< Output, OutputGradient >::partial_reparse(), libMesh::ParsedFEMFunction< Output >::partial_reparse(), libMesh::TriangleInterface::PolygonHole::point(), libMesh::Elem::point_test(), libMesh::QBase::print_info(), libMesh::DofMap::process_constraints(), libMesh::MeshTools::processor_bounding_sphere(), libMesh::ImplicitSystem::qoi_parameter_hessian(), libMesh::ImplicitSystem::qoi_parameter_hessian_vector_product(), libMesh::InfHex::quality(), libMesh::Hex::quality(), libMesh::Tri::quality(), libMesh::Quad::quality(), libMesh::GmshIO::read_mesh(), libMesh::AbaqusIO::read_nodes(), libMesh::OFFIO::read_stream(), libMesh::MatlabIO::read_stream(), libMesh::MeshData::read_tetgen(), libMesh::MeshData::read_unv_implementation(), libMesh::VariationalMeshSmoother::readgr(), libMesh::FESubdivision::regular_shape(), libMesh::FESubdivision::regular_shape_deriv(), libMesh::FESubdivision::regular_shape_second_deriv(), libMesh::MemorySolutionHistory::retrieve(), libMesh::MeshTools::Modification::rotate(), libMesh::MeshTools::Modification::scale(), libMesh::QBase::scale(), libMesh::HPCoarsenTest::select_refinement(), libMesh::FrequencySystem::set_current_frequency(), libMesh::FrequencySystem::set_frequencies(), libMesh::FrequencySystem::set_frequencies_by_range(), libMesh::FrequencySystem::set_frequencies_by_steps(), libMesh::NewmarkSystem::set_newmark_parameters(), libMesh::FEMSystem::set_numerical_jacobian_h_for_var(), libMesh::NonlinearImplicitSystem::set_solver_parameters(), libMesh::FE< Dim, T >::shape(), libMesh::InfFE< Dim, T_radial, T_map >::shape(), libMesh::FE< Dim, T >::shape_deriv(), libMesh::FE< Dim, T >::shape_second_deriv(), libMesh::LaplaceMeshSmoother::smooth(), libMesh::MeshTools::Modification::smooth(), libMesh::TwostepTimeSolver::solve(), libMesh::NewtonSolver::solve(), libMesh::NoxNonlinearSolver< T >::solve(), libMesh::EigenSystem::solve(), libMesh::CondensedEigenSystem::solve(), libMesh::PetscNonlinearSolver< T >::solve(), libMesh::NloptOptimizationSolver< T >::solve(), libMesh::FrequencySystem::solve(), libMesh::LinearImplicitSystem::solve(), libMesh::ContinuationSystem::solve_tangent(), libMesh::PatchRecoveryErrorEstimator::specpoly(), libMesh::Sphere::Sphere(), libMesh::SerialMesh::stitching_helper(), libMesh::MeshTools::subdomain_bounding_sphere(), libMesh::NumericVector< T >::subset_l1_norm(), libMesh::NumericVector< T >::subset_l2_norm(), libMesh::NumericVector< T >::subset_linfty_norm(), libMesh::Sphere::surface_coords(), libMesh::TypeVector< T >::unit(), libMesh::Parallel::Packing< Node * >::unpack(), libMesh::ContinuationSystem::update_solution(), libMesh::ErrorVector::variance(), libMesh::StatisticsVector< T >::variance(), libMesh::Quad4::volume(), libMesh::Edge3::volume(), libMesh::Quad8::volume(), libMesh::Tri6::volume(), libMesh::Quad9::volume(), libMesh::Elem::volume(), libMesh::ImplicitSystem::weighted_sensitivity_adjoint_solve(), libMesh::ImplicitSystem::weighted_sensitivity_solve(), libMesh::Sphere::world_coords(), libMesh::PostscriptIO::write(), libMesh::GMVIO::write_ascii_new_impl(), libMesh::GMVIO::write_ascii_old_impl(), libMesh::GmshIO::write_mesh(), and libMesh::GnuPlotIO::write_solution().
const RemoteElem * libMesh::remote_elem
Definition at line 57 of file remote_elem.C.
Referenced by libMesh::Elem::active_family_tree_by_neighbor(), libMesh::Elem::add_child(), libMesh::BoundaryInfo::add_elements(), libMesh::UnstructuredMesh::all_first_order(), libMesh::UnstructuredMesh::all_second_order(), libMesh::MeshTools::Modification::all_tri(), libMesh::Elem::ancestor(), libMesh::Elem::coarsen(), libMesh::FEAbstract::compute_node_constraints(), libMesh::UnstructuredMesh::copy_nodes_and_elements(), libMesh::RemoteElem::create(), libMesh::MeshRefinement::eliminate_unrefined_patches(), libMesh::Elem::family_tree_by_neighbor(), libMesh::Elem::family_tree_by_subneighbor(), libMesh::Elem::find_edge_neighbors(), libMesh::UnstructuredMesh::find_neighbors(), libMesh::Elem::find_point_neighbors(), libMesh::MeshRefinement::flag_elements_by_nelem_target(), libMesh::MeshTools::Modification::flatten(), libMesh::Elem::interior_parent(), libMesh::MeshTools::libmesh_assert_valid_amr_interior_parents(), libMesh::MeshTools::libmesh_assert_valid_neighbors(), libMesh::Elem::libmesh_assert_valid_neighbors(), libMesh::MeshTools::libmesh_assert_valid_node_pointers(), libMesh::MeshTools::libmesh_assert_valid_procids< Elem >(), libMesh::MeshTools::libmesh_assert_valid_refinement_tree(), libMesh::MeshTools::libmesh_assert_valid_remote_elems(), libMesh::MeshRefinement::make_coarsening_compatible(), libMesh::Elem::make_links_to_me_local(), libMesh::Elem::make_links_to_me_remote(), libMesh::MeshRefinement::make_refinement_compatible(), libMesh::Elem::min_new_p_level_by_neighbor(), libMesh::Elem::min_p_level_by_neighbor(), libMesh::Elem::nullify_neighbors(), libMesh::Elem::set_interior_parent(), libMesh::MeshRefinement::test_level_one(), and libMesh::Parallel::Packing< Elem * >::unpack().
LibMeshInit::LibMeshInit (int argc, const char * const * argv) LibMeshInit command_lin libMesh::reset) (new GetPot(argc, argv))
Definition at line 342 of file libmesh.C.
PetscDiffSolver& libMesh::solver
Initial value:
=
      *(static_cast<PetscDiffSolver*> (ctx))
Definition at line 153 of file petsc_diff_solver.C.
Referenced by __libmesh_nlopt_equality_constraints(), __libmesh_nlopt_inequality_constraints(), __libmesh_nlopt_objective(), __libmesh_petsc_diff_solver_monitor(), __libmesh_petsc_diff_solver_residual(), __libmesh_petsc_snes_jacobian(), __libmesh_petsc_snes_postcheck(), __libmesh_petsc_snes_residual(), __libmesh_tao_equality_constraints(), __libmesh_tao_equality_constraints_jacobian(), __libmesh_tao_gradient(), __libmesh_tao_hessian(), __libmesh_tao_inequality_constraints(), __libmesh_tao_inequality_constraints_jacobian(), __libmesh_tao_objective(), libMesh::EigenSparseLinearSolver< T >::solve(), and libMesh::NoxNonlinearSolver< T >::solve().
const unsigned char libMesh::square_number_column
Initial value:
= {
  0,
  0, 1, 1,
  0, 1, 2, 2, 2,
  0, 1, 2, 3, 3, 3, 3,
  0, 1, 2, 3, 4, 4, 4, 4, 4,
  0, 1, 2, 3, 4, 5, 5, 5, 5, 5, 5,
  0, 1, 2, 3, 4, 5, 6, 6, 6, 6, 6, 6, 6,
  0, 1, 2, 3, 4, 5, 6, 7, 7, 7, 7, 7, 7, 7, 7,
  0, 1, 2, 3, 4, 5, 6, 7, 8, 8, 8, 8, 8, 8, 8, 8, 8,
  0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9
}
Definition at line 57 of file number_lookups.C.
Referenced by libMesh::FE< Dim, T >::shape(), and libMesh::FE< Dim, T >::shape_deriv().
const unsigned char libMesh::square_number_row
Initial value:
= {
  0,
  1, 1, 0,
  2, 2, 2, 1, 0,
  3, 3, 3, 3, 2, 1, 0,
  4, 4, 4, 4, 4, 3, 2, 1, 0,
  5, 5, 5, 5, 5, 5, 4, 3, 2, 1, 0,
  6, 6, 6, 6, 6, 6, 6, 5, 4, 3, 2, 1, 0,
  7, 7, 7, 7, 7, 7, 7, 7, 6, 5, 4, 3, 2, 1, 0,
  8, 8, 8, 8, 8, 8, 8, 8, 8, 7, 6, 5, 4, 3, 2, 1, 0,
  9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 8, 7, 6, 5, 4, 3, 2, 1, 0,
}
Definition at line 70 of file number_lookups.C.
Referenced by libMesh::FE< Dim, T >::shape(), and libMesh::FE< Dim, T >::shape_deriv().
KSP* libMesh::subksps
Definition at line 278 of file petsc_preconditioner.C.
ImplicitSystem& libMesh::sys = solver.system()
Definition at line 155 of file petsc_diff_solver.C.
Referenced by __libmesh_nlopt_equality_constraints(), __libmesh_nlopt_inequality_constraints(), __libmesh_nlopt_objective(), __libmesh_petsc_diff_solver_residual(), __libmesh_petsc_snes_jacobian(), __libmesh_petsc_snes_postcheck(), __libmesh_petsc_snes_residual(), __libmesh_tao_equality_constraints(), __libmesh_tao_equality_constraints_jacobian(), __libmesh_tao_gradient(), __libmesh_tao_hessian(), __libmesh_tao_inequality_constraints(), __libmesh_tao_inequality_constraints_jacobian(), __libmesh_tao_objective(), libMesh::UniformRefinementEstimator::_estimate_error(), libMesh::EquationSystems::_read_impl(), libMesh::EquationSystems::allgather(), libMesh::ExactSolution::attach_exact_deriv(), libMesh::ExactSolution::attach_exact_hessian(), libMesh::OldSolutionValue< Output, point_output >::check_old_context(), libMesh::EquationSystems::clear(), libMesh::ExactSolution::compute_error(), libMesh::Problem_Interface::computeF(), libMesh::Problem_Interface::computeJacobian(), libMesh::Problem_Interface::computePreconditioner(), libMesh::GMVIO::copy_nodal_solution(), libMesh::DiffContext::DiffContext(), DMCreateDomainDecomposition_libMesh(), DMCreateFieldDecomposition_libMesh(), DMlibMeshFunction(), DMlibMeshGetSystem(), DMlibMeshJacobian(), DMlibMeshSetSystem(), DMlibMeshSetSystem_libMesh(), DMVariableBounds_libMesh(), libMesh::WeightedPatchRecoveryErrorEstimator::estimate_error(), libMesh::JumpErrorEstimator::estimate_error(), libMesh::PatchRecoveryErrorEstimator::estimate_error(), libMesh::ErrorEstimator::estimate_errors(), libMesh::OldSolutionValue< Output, point_output >::eval_at_node(), libMesh::ExactSolution::ExactSolution(), if(), libMesh::OldSolutionValue< Output, point_output >::init_context(), libMesh::FEMContext::pre_fe_reinit(), libMesh::System::read_legacy_data(), libMesh::EquationSystems::reinit(), libMesh::DifferentiablePhysics::set_mesh_system(), libMesh::FEMContext::set_mesh_system(), libMesh::NoxNonlinearSolver< T >::solve(), and libMesh::VTKIO::system_vectors_to_vtk().
static const Real libMesh::TOLERANCE = 1.e-8 static
Definition at line 139 of file libmesh_common.h.
Referenced by libMesh::ImplicitSystem::adjoint_qoi_parameter_sensitivity(), libMesh::ImplicitSystem::assemble_residual_derivatives(), libMesh::MeshTools::Generation::build_delaunay_square(), libMesh::FEGenericBase< OutputType >::coarsened_dof_values(), libMesh::FEGenericBase< OutputType >::compute_periodic_constraints(), libMesh::FEGenericBase< OutputType >::compute_proj_constraints(), libMesh::Elem::contains_point(), libMesh::EquationSystems::EquationSystems(), libMesh::UnstructuredMesh::find_neighbors(), libMesh::MemorySolutionHistory::find_stored_entry(), libMesh::ImplicitSystem::forward_qoi_parameter_sensitivity(), libMesh::LocationMap< T >::key(), libMesh::GenericProjector< FFunctor, GFunctor, FValue, ProjectionAction >::operator()(), libMesh::MeshTools::Generation::Private::GaussLobattoRedistributionFunction::operator()(), libMesh::BoundaryProjectSolution::operator()(), libMesh::TypeTensor< T >::operator==(), libMesh::ImplicitSystem::qoi_parameter_hessian(), libMesh::ImplicitSystem::qoi_parameter_hessian_vector_product(), libMesh::MemorySolutionHistory::retrieve(), libMesh::FE< Dim, T >::shape(), libMesh::FE< Dim, T >::shape_deriv(), libMesh::FE< Dim, T >::shape_second_deriv(), libMesh::NewtonSolver::solve(), libMesh::SerialMesh::stitching_helper(), libMesh::MemorySolutionHistory::store(), libMesh::TriangleInterface::triangulate(), libMesh::Parallel::Packing< Node * >::unpack(), libMesh::PointLocatorBase::unset_close_to_point_tol(), libMesh::Edge3::volume(), libMesh::ImplicitSystem::weighted_sensitivity_adjoint_solve(), and libMesh::ImplicitSystem::weighted_sensitivity_solve().
const unsigned char libMesh::triangular_number_column
Initial value:
= {
  0,
  0, 1,
  0, 1, 2,
  0, 1, 2, 3,
  0, 1, 2, 3, 4,
  0, 1, 2, 3, 4, 5,
  0, 1, 2, 3, 4, 5, 6,
  0, 1, 2, 3, 4, 5, 6, 7,
  0, 1, 2, 3, 4, 5, 6, 7, 8,
  0, 1, 2, 3, 4, 5, 6, 7, 8, 9
}
Definition at line 42 of file number_lookups.C.
Referenced by libMesh::FE< Dim, T >::shape().
const unsigned char libMesh::triangular_number_row
Initial value:
= {
  0,
  1, 1,
  2, 2, 2,
  3, 3, 3, 3,
  4, 4, 4, 4, 4,
  5, 5, 5, 5, 5, 5,
  6, 6, 6, 6, 6, 6, 6,
  7, 7, 7, 7, 7, 7, 7, 7,
  8, 8, 8, 8, 8, 8, 8, 8, 8,
  9, 9, 9, 9, 9, 9, 9, 9, 9, 9
}
Definition at line 29 of file number_lookups.C.
Referenced by libMesh::FE< Dim, T >::shape().
libMesh::TRILINOS_SOLVERS
Definition at line 247 of file libmesh.C.
Referenced by libMesh::Preconditioner< T >::build(), libMesh::NonlinearSolver< T >::build(), libMesh::LinearSolver< T >::build(), libMesh::SparseMatrix< T >::build(), libMesh::NumericVector< T >::build(), and default_solver_package().
bool libMesh::warned_about_auto_ptr
Referenced by libMesh::AutoPtr< Tp >::~AutoPtr().
PetscErrorCode Vec libMesh::x
Definition at line 142 of file petsc_diff_solver.C.
Referenced by libMesh::DenseMatrix< T >::_cholesky_back_substitute(), GETPOT_NAMESPACE::GetPot::_DBE_expand(), libMesh::SFCPartitioner::_do_partition(), libMesh::DenseMatrix< T >::_lu_back_substitute(), libMesh::DenseMatrix< T >::_matvec_blas(), libMesh::DenseMatrix< T >::_svd_solve_lapack(), libMesh::VariationalMeshSmoother::adp_renew(), libMesh::PetscPreconditioner< T >::apply(), libMesh::Utility::do_pow< 6, T >::apply(), libMesh::Utility::do_pow< 1, T >::apply(), libMesh::VariationalMeshSmoother::gener(), libMesh::NewtonSolver::line_search(), libMesh::UNVIO::nodes_out(), libMesh::VariationalMeshSmoother::pcg_ic0(), libMesh::GmshIO::read_mesh(), libMesh::AbaqusIO::read_nodes(), libMesh::OFFIO::read_stream(), libMesh::MatlabIO::read_stream(), libMesh::VariationalMeshSmoother::readgr(), libMesh::MeshTools::Modification::rotate(), libMesh::TetGenWrapper::set_hole(), libMesh::TetGenWrapper::set_node(), libMesh::TetGenWrapper::set_region(), libMesh::FE< Dim, T >::shape(), libMesh::FE< Dim, T >::shape_deriv(), libMesh::FE< Dim, T >::shape_second_deriv(), libMesh::NoxNonlinearSolver< T >::solve(), libMesh::TaoOptimizationSolver< T >::solve(), libMesh::PetscNonlinearSolver< T >::solve(), libMesh::NloptOptimizationSolver< T >::solve(), libMesh::PatchRecoveryErrorEstimator::specpoly(), libMesh::TetGenMeshInterface::triangulate_conformingDelaunayMesh_carvehole(), and libMesh::TypeVector< T >::TypeVector().
if (solver.verbose) libMesh PetscVector<Number>& libMesh::X_system
Initial value:
=
      *cast_ptr<PetscVector<Number> *>(sys.solution.get())
Definition at line 160 of file petsc_diff_solver.C.
Referenced by __libmesh_petsc_diff_solver_residual().
const Number libMesh::zero = 0.
.
Definition at line 166 of file libmesh.h.
Referenced by libMesh::DenseMatrix< T >::_lu_decompose(), libMesh::HPCoarsenTest::add_projection(), libMesh::FEGenericBase< OutputType >::coarsened_dof_values(), libMesh::WeightedPatchRecoveryErrorEstimator::EstimateError::operator()(), libMesh::PatchRecoveryErrorEstimator::EstimateError::operator()(), libMesh::MeshData::operator()(), libMesh::System::read_legacy_data(), libMesh::DenseVector< T >::resize(), libMesh::DenseMatrix< T >::resize(), libMesh::HPCoarsenTest::select_refinement(), and libMesh::FE< Dim, T >::side_map().