libMesh: libMesh::MeshTools::Private Namespace Reference
SomeWebsiteLogo
libMesh::MeshTools::Private Namespace Reference
Functions
void globally_renumber_nodes_and_elements (MeshBase &)
Function Documentation
globally_renumber_nodes_and_elements()
void libMesh::MeshTools::Private::globally_renumber_nodes_and_elements (MeshBase & mesh)
There is no reason for a user to ever call this function.
This function determines partition-agnostic global indices for all nodes and elements in the mesh.
Note
After this function is called, the mesh will likely be in an inconsistent state, i.e. mesh.nodes(i)->id() != i in the nodes container. Direct node/element access via the mesh.node(n) or mesh.elem(e) functions will likely fail. The original numbering can (and should) be restored with a subsequent call to fix_node_and_element_numbering().
Definition at line 2424 of file mesh_tools.C.
References libMesh::MeshCommunication::assign_global_indices(), and mesh.
Referenced by libMesh::EquationSystems::_read_impl(), and libMesh::EquationSystems::write().
 {
   MeshCommunication().assign_global_indices(mesh);
 }