libMesh: std Namespace Reference
SomeWebsiteLogo
std Namespace Reference
Functions
long double max (long double a, double b)
long double min (long double a, double b)
long double max (double a, long double b)
long double min (double a, long double b)
double max (double a, float b)
double min (double a, float b)
double max (float a, double b)
double min (float a, double b)
long double max (long double a, float b)
long double min (long double a, float b)
long double max (float a, long double b)
long double min (float a, long double b)
double abs (double a)
double pow (double a, int b)
Function Documentation
abs()
double std::abs (double a) inline
Definition at line 59 of file libmesh_augment_std_namespace.h.
Referenced by GETPOT_NAMESPACE::GetPot::_DBE_expand(), libMesh::DenseMatrix< Number >::_lu_decompose(), libMesh::EigenSparseVector< T >::abs(), libMesh::DistributedVector< T >::abs(), libMesh::LaspackVector< T >::abs(), libMesh::TypeVector< Real >::absolute_fuzzy_equals(), libMesh::ImplicitSystem::adjoint_qoi_parameter_sensitivity(), libMesh::ImplicitSystem::assemble_residual_derivatives(), libMesh::InfElemBuilder::build_inf_elem(), libMesh::EquationSystems::build_parallel_solution_vector(), libMesh::System::calculate_norm(), libMesh::FEGenericBase< FEOutputType< T >::type >::coarsened_dof_values(), libMesh::NumericVector< Number >::compare(), libMesh::FEAbstract::compute_node_constraints(), libMesh::FEGenericBase< FEOutputType< T >::type >::compute_periodic_constraints(), libMesh::FEGenericBase< FEOutputType< T >::type >::compute_proj_constraints(), libMesh::Tri3::contains_point(), libMesh::ContinuationSystem::continuation_solve(), libMesh::AdjointRefinementEstimator::estimate_error(), libMesh::MemorySolutionHistory::find_stored_entry(), libMesh::ImplicitSystem::forward_qoi_parameter_sensitivity(), libMesh::VariationalMeshSmoother::full_smooth(), libMesh::NumericVector< Number >::global_relative_compare(), libMesh::PointLocatorTree::init(), libMesh::Tet::is_child_on_side_helper(), libMesh::LocationMap< T >::key(), libMesh::DenseSubVector< T >::l1_norm(), libMesh::EigenSparseMatrix< T >::l1_norm(), libMesh::DistributedVector< T >::l1_norm(), libMesh::DenseVector< Output >::l1_norm(), libMesh::DenseMatrix< Number >::l1_norm(), libMesh::NewtonSolver::line_search(), libMesh::EigenSparseMatrix< T >::linfty_norm(), libMesh::DistributedVector< T >::linfty_norm(), libMesh::DenseMatrix< Number >::linfty_norm(), libMesh::NumericVector< Number >::local_relative_compare(), libMesh::Edge4::loose_bounding_box(), libMesh::Edge3::loose_bounding_box(), libMesh::Quad8::loose_bounding_box(), libMesh::Tri6::loose_bounding_box(), libMesh::Quad9::loose_bounding_box(), libMesh::DofMap::max_constraint_error(), libMesh::VariationalMeshSmoother::metr_data_gen(), libMesh::VariationalMeshSmoother::minJ(), libMesh::VariationalMeshSmoother::minJ_BC(), libMesh::Plane::on_surface(), libMesh::Sphere::on_surface(), libMesh::GenericProjector< FFunctor, GFunctor, FValue, ProjectionAction >::operator()(), libMesh::WeightedPatchRecoveryErrorEstimator::EstimateError::operator()(), libMesh::PatchRecoveryErrorEstimator::EstimateError::operator()(), libMesh::BoundaryProjectSolution::operator()(), libMesh::MeshTools::Generation::Private::GaussLobattoRedistributionFunction::operator()(), libMesh::TypeTensor< T >::operator==(), libMesh::VariationalMeshSmoother::readgr(), libMesh::EpetraVector< T >::reciprocal(), libMesh::TypeVector< Real >::relative_fuzzy_equals(), libMesh::MemorySolutionHistory::retrieve(), libMesh::ContinuationSystem::set_Theta_LOCA(), libMesh::FE< Dim, LAGRANGE_VEC >::shape(), libMesh::FE< Dim, LAGRANGE_VEC >::shape_deriv(), libMesh::FE< Dim, LAGRANGE_VEC >::shape_second_deriv(), libMesh::SIGN(), libMesh::BoundingBox::signed_distance(), libMesh::Sphere::Sphere(), libMesh::MemorySolutionHistory::store(), libMesh::NumericVector< Number >::subset_l1_norm(), libMesh::NumericVector< Number >::subset_linfty_norm(), libMesh::ContinuationSystem::update_solution(), libMesh::TecplotIO::write_ascii(), libMesh::GMVIO::write_ascii_new_impl(), libMesh::GMVIO::write_ascii_old_impl(), libMesh::TecplotIO::write_binary(), libMesh::GMVIO::write_binary(), libMesh::GMVIO::write_discontinuous_gmv(), libMesh::ExodusII_IO::write_element_data(), libMesh::Nemesis_IO::write_global_data(), libMesh::ExodusII_IO::write_global_data(), libMesh::ExodusII_IO::write_nodal_data(), libMesh::ExodusII_IO::write_nodal_data_discontinuous(), and libMesh::Nemesis_IO_Helper::write_nodal_solution().
 { return ::fabs(a); }
max() [1/6]
long double std::max (long double a, double b) inline
Definition at line 27 of file libmesh_augment_std_namespace.h.
Referenced by GETPOT_NAMESPACE::GetPot::_DBE_expand(), libMesh::DenseMatrix< Number >::_svd_solve_lapack(), libMesh::VariationalMeshSmoother::adapt_minimum(), libMesh::DistributedMesh::add_elem(), libMesh::QoISet::add_indices(), libMesh::TopologyMap::add_node(), libMesh::DistributedMesh::add_node(), libMesh::ImplicitSystem::adjoint_qoi_parameter_sensitivity(), libMesh::ImplicitSystem::assemble_residual_derivatives(), libMesh::FEMSystem::assembly(), libMesh::Parallel::BinSorter< KeyType, IdxType >::binsort(), libMesh::Parallel::Sort< KeyType, IdxType >::binsort(), libMesh::TreeNode< N >::bounds_point(), libMesh::System::calculate_norm(), libMesh::Node::choose_processor_id(), libMesh::NumericVector< Number >::compare(), libMesh::ConstCouplingRow::ConstCouplingRow(), libMesh::ConstCouplingRowConstIterator::ConstCouplingRowConstIterator(), libMesh::InfPrism::contains_point(), libMesh::InfHex::contains_point(), libMesh::Tri3::contains_point(), libMesh::MeshRefinement::create_parent_error_vector(), libMesh::FEType::default_quadrature_rule(), libMesh::MeshTools::Modification::distort(), libMesh::ConstCouplingRow::end(), libMesh::TopologyMap::find(), libMesh::MeshCommunication::find_global_indices(), libMesh::MeshRefinement::flag_elements_by_error_fraction(), libMesh::MeshRefinement::flag_elements_by_mean_stddev(), libMesh::ImplicitSystem::forward_qoi_parameter_sensitivity(), libMesh::DofMap::get_info(), libMesh::NumericVector< Number >::global_relative_compare(), libMesh::QGrundmann_Moller::gm_rule(), libMesh::StatisticsVector< ErrorVectorReal >::histogram(), libMesh::Elem::hmax(), libMesh::Elem::hmin(), libMesh::LocationMap< T >::init(), libMesh::FESubdivision::init_shape_functions(), libMesh::BoundingBox::intersect_with(), libMesh::BoundingBox::invalidate(), libMesh::is_between(), libMesh::ElemCutter::is_cut(), libMesh::MeshTools::libmesh_assert_contiguous_dof_ids(), libMesh::MeshTools::libmesh_assert_parallel_consistent_procids< Elem >(), libMesh::MeshTools::libmesh_assert_parallel_consistent_procids< Node >(), libMesh::MeshTools::libmesh_assert_topology_consistent_procids< Node >(), libMesh::DistributedMesh::libmesh_assert_valid_parallel_object_ids(), libMesh::MeshRefinement::limit_level_mismatch_at_edge(), libMesh::MeshRefinement::limit_level_mismatch_at_node(), libMesh::NewtonSolver::line_search(), libMesh::EigenSparseMatrix< T >::linfty_norm(), libMesh::DistributedVector< T >::linfty_norm(), libMesh::NumericVector< Number >::local_relative_compare(), libMesh::Edge4::loose_bounding_box(), libMesh::Edge3::loose_bounding_box(), libMesh::Quad8::loose_bounding_box(), libMesh::Tri6::loose_bounding_box(), libMesh::Quad9::loose_bounding_box(), libMesh::MeshRefinement::make_coarsening_compatible(), libMesh::Parallel::Histogram< KeyType, IdxType >::make_histogram(), libMesh::DistributedVector< T >::max(), libMesh::EigenSparseVector< T >::max(), libMesh::LaspackVector< T >::max(), libMesh::DofMap::max_constraint_error(), libMesh::Elem::max_descendant_p_level(), libMesh::StatisticsVector< ErrorVectorReal >::maximum(), libMesh::DistributedVector< T >::min(), libMesh::EigenSparseVector< T >::min(), libMesh::LaspackVector< T >::min(), libMesh::Tri3::min_and_max_angle(), libMesh::ErrorVector::minimum(), libMesh::MeshTools::n_active_levels(), libMesh::CheckpointIO::n_active_levels_in(), libMesh::MeshTools::n_active_local_levels(), libMesh::MeshTools::n_levels(), libMesh::MeshTools::n_local_levels(), libMesh::MeshTools::n_p_levels(), libMesh::Parallel::Communicator::nonblocking_send_packed_range(), libMesh::StatisticsVector< ErrorVectorReal >::normalize(), libMesh::ConstCouplingAccessor::operator bool(), libMesh::WeightedPatchRecoveryErrorEstimator::EstimateError::operator()(), libMesh::PatchRecoveryErrorEstimator::EstimateError::operator()(), libMesh::ConstCouplingRowConstIterator::operator*(), libMesh::ConstCouplingRowConstIterator::operator++(), libMesh::CouplingAccessor::operator=(), libMesh::Parallel::Packing< T >::pack(), libMesh::DistributedMesh::parallel_max_unique_id(), libMesh::MeshTools::paranoid_n_levels(), libMesh::MetisPartitioner::partition_range(), libMesh::StatisticsVector< ErrorVectorReal >::plot_histogram(), libMesh::Partitioner::processor_pairs_to_interface_nodes(), libMesh::Hex::quality(), libMesh::InfHex::quality(), libMesh::Quad::quality(), libMesh::GmshIO::read_mesh(), libMesh::MeshBase::recalculate_n_partitions(), libMesh::FE< Dim, LAGRANGE_VEC >::reinit(), libMesh::DofMap::reinit(), libMesh::HPCoarsenTest::select_refinement(), libMesh::FE< Dim, LAGRANGE_VEC >::shape(), libMesh::FE< Dim, LAGRANGE_VEC >::shape_deriv(), libMesh::FE< Dim, LAGRANGE_VEC >::shape_second_deriv(), libMesh::FE< Dim, LAGRANGE_VEC >::side_map(), libMesh::BoundingBox::signed_distance(), libMesh::TwostepTimeSolver::solve(), libMesh::NewtonSolver::solve(), libMesh::ReplicatedMesh::stitching_helper(), libMesh::BoundingBox::union_with(), libMesh::Parallel::Packing< T >::unpack(), libMesh::Parallel::TypeVectorOpFunction< Point >::vector_max(), libMesh::GMVIO::write_ascii_new_impl(), libMesh::GMVIO::write_ascii_old_impl(), libMesh::TecplotIO::write_binary(), and libMesh::GMVIO::write_binary().
 { return (a>b?a:b); }
max() [2/6]
long double std::max (double a, long double b) inline
Definition at line 32 of file libmesh_augment_std_namespace.h.
 { return (a>b?a:b); }
max() [3/6]
double std::max (double a, float b) inline
Definition at line 37 of file libmesh_augment_std_namespace.h.
 { return (a>b?a:b); }
max() [4/6]
double std::max (float a, double b) inline
Definition at line 42 of file libmesh_augment_std_namespace.h.
 { return (a>b?a:b); }
max() [5/6]
long double std::max (long double a, float b) inline
Definition at line 47 of file libmesh_augment_std_namespace.h.
 { return (a>b?a:b); }
max() [6/6]
long double std::max (float a, long double b) inline
Definition at line 52 of file libmesh_augment_std_namespace.h.
 { return (a>b?a:b); }
min() [1/6]
long double std::min (long double a, double b) inline
Definition at line 29 of file libmesh_augment_std_namespace.h.
Referenced by GETPOT_NAMESPACE::GetPot::_DBE_expand(), libMesh::DenseMatrix< Number >::_lu_decompose_lapack(), libMesh::DenseMatrix< Number >::_svd_solve_lapack(), libMesh::VariationalMeshSmoother::adapt_minimum(), libMesh::TopologyMap::add_node(), libMesh::VariationalMeshSmoother::adjust_adapt_data(), libMesh::UnstructuredMesh::all_second_order(), libMesh::Parallel::BinSorter< KeyType, IdxType >::binsort(), libMesh::TreeNode< N >::bounds_point(), libMesh::Node::choose_processor_id(), libMesh::FEGenericBase< FEOutputType< T >::type >::compute_periodic_constraints(), libMesh::FEGenericBase< FEOutputType< T >::type >::compute_proj_constraints(), libMesh::InfQuad4::contains_point(), libMesh::InfPrism::contains_point(), libMesh::InfHex::contains_point(), libMesh::ContinuationSystem::continuation_solve(), libMesh::ExodusII_IO_Helper::create(), libMesh::Nemesis_IO_Helper::create(), libMesh::MeshRefinement::create_parent_error_vector(), libMesh::Xdr::data_stream(), libMesh::MeshTools::Modification::distort(), libMesh::TopologyMap::find(), libMesh::MeshRefinement::flag_elements_by_error_fraction(), libMesh::MeshRefinement::flag_elements_by_nelem_target(), libMesh::Nemesis_IO_Helper::get_elem_map(), libMesh::StatisticsVector< ErrorVectorReal >::histogram(), libMesh::Elem::hmin(), libMesh::LocationMap< T >::init(), libMesh::FESubdivision::init_shape_functions(), libMesh::ParmetisPartitioner::initialize(), libMesh::BoundingBox::intersect_with(), libMesh::is_between(), libMesh::ElemCutter::is_cut(), libMesh::SparsityPattern::Build::join(), libMesh::MeshTools::libmesh_assert_contiguous_dof_ids(), libMesh::MeshTools::libmesh_assert_parallel_consistent_procids< Elem >(), libMesh::NewtonSolver::line_search(), libMesh::Parallel::Histogram< KeyType, IdxType >::make_histogram(), libMesh::MeshCommunication::make_new_node_proc_ids_parallel_consistent(), libMesh::DistributedVector< T >::min(), libMesh::EigenSparseVector< T >::min(), libMesh::LaspackVector< T >::min(), libMesh::Tri3::min_and_max_angle(), libMesh::Elem::min_new_p_level_by_neighbor(), libMesh::Elem::min_p_level_by_neighbor(), libMesh::ErrorVector::minimum(), libMesh::StatisticsVector< ErrorVectorReal >::minimum(), libMesh::Threads::num_pthreads(), libMesh::ExodusII_IO_Helper::open(), libMesh::SparsityPattern::Build::parallel_sync(), libMesh::Partitioner::partition(), libMesh::CentroidPartitioner::partition_range(), libMesh::StatisticsVector< ErrorVectorReal >::plot_histogram(), libMesh::Partitioner::processor_pairs_to_interface_nodes(), libMesh::Hex::quality(), libMesh::InfHex::quality(), libMesh::Quad::quality(), libMesh::Nemesis_IO::read(), libMesh::ExodusII_IO_Helper::read_elem_num_map(), libMesh::GmshIO::read_mesh(), libMesh::ExodusII_IO_Helper::read_node_num_map(), libMesh::XdrIO::read_serialized_bcs_helper(), libMesh::System::read_serialized_blocked_dof_objects(), libMesh::XdrIO::read_serialized_connectivity(), libMesh::XdrIO::read_serialized_nodes(), libMesh::XdrIO::read_serialized_nodesets(), libMesh::EpetraVector< T >::reciprocal(), libMesh::Partitioner::repartition(), libMesh::Elem::set_p_level(), libMesh::Partitioner::set_parent_processor_ids(), libMesh::FE< Dim, LAGRANGE_VEC >::shape(), libMesh::BoundingBox::signed_distance(), libMesh::NewtonSolver::solve(), libMesh::ReplicatedMesh::stitching_helper(), libMesh::BoundingBox::union_with(), libMesh::EpetraMatrix< T >::update_sparsity_pattern(), libMesh::Parallel::TypeVectorOpFunction< Point >::vector_min(), libMesh::System::write_serialized_blocked_dof_objects(), and libMesh::XdrIO::write_serialized_nodes().
 { return (a<b?a:b); }
min() [2/6]
long double std::min (double a, long double b) inline
Definition at line 34 of file libmesh_augment_std_namespace.h.
 { return (a<b?a:b); }
min() [3/6]
double std::min (double a, float b) inline
Definition at line 39 of file libmesh_augment_std_namespace.h.
 { return (a<b?a:b); }
min() [4/6]
double std::min (float a, double b) inline
Definition at line 44 of file libmesh_augment_std_namespace.h.
 { return (a<b?a:b); }
min() [5/6]
long double std::min (long double a, float b) inline
Definition at line 49 of file libmesh_augment_std_namespace.h.
 { return (a<b?a:b); }
min() [6/6]
long double std::min (float a, long double b) inline
Definition at line 54 of file libmesh_augment_std_namespace.h.
 { return (a<b?a:b); }
pow()
double std::pow (double a, int b) inline
Definition at line 66 of file libmesh_augment_std_namespace.h.
Referenced by GETPOT_NAMESPACE::GetPot::_DBE_expand(), libMesh::ContinuationSystem::continuation_solve(), libMesh::FESubdivision::init_shape_functions(), libMesh::VariationalMeshSmoother::maxE(), libMesh::VariationalMeshSmoother::metr_data_gen(), libMesh::VariationalMeshSmoother::minJ(), libMesh::VariationalMeshSmoother::minJ_BC(), libMesh::FE< Dim, LAGRANGE_VEC >::shape(), libMesh::FE< Dim, LAGRANGE_VEC >::shape_deriv(), libMesh::FE< Dim, LAGRANGE_VEC >::shape_second_deriv(), libMesh::MeshTools::Modification::smooth(), libMesh::TwostepTimeSolver::solve(), and libMesh::VariationalMeshSmoother::vertex().
 { return std::pow(a, static_cast<double>(b)); }