libMesh: petscdmlibmesh.C File Reference
SomeWebsiteLogo
petscdmlibmesh.C File Reference
#include "libmesh/petsc_macro.h"
#include <petsc/private/petscimpl.h>
#include "libmesh/petscdmlibmesh.h"
Macros
#define __FUNCT__ "DMlibMeshSetSystem"
#define __FUNCT__ "DMlibMeshGetSystem"
Functions
PetscErrorCode DMlibMeshSetSystem (DM dm, libMesh::NonlinearImplicitSystem &sys)
PetscErrorCode DMlibMeshGetSystem (DM dm, libMesh::NonlinearImplicitSystem *&sys)
Macro Definition Documentation
#define __FUNCT__ "DMlibMeshSetSystem"
Definition at line 33 of file petscdmlibmesh.C.
#define __FUNCT__ "DMlibMeshGetSystem"
Definition at line 33 of file petscdmlibmesh.C.
Function Documentation
PetscErrorCode DMlibMeshGetSystem (DM dm, libMesh::NonlinearImplicitSystem *& sys)
Definition at line 34 of file petscdmlibmesh.C.
References libmesh_nullptr.
Referenced by DMlibMeshFunction(), DMlibMeshJacobian(), and DMVariableBounds_libMesh().
 {
   PetscErrorCode (*f)(DM,libMesh::NonlinearImplicitSystem *&) = libmesh_nullptr;
   PetscErrorCode ierr;
   PetscFunctionBegin;
   PetscValidHeaderSpecific(dm,DM_CLASSID,1);
 #if PETSC_RELEASE_LESS_THAN(3,4,0)
   ierr = PetscObjectQueryFunction((PetscObject)dm,"DMlibMeshGetSystem_C",(PetscVoidFunction*)&f);CHKERRQ(ierr);
 #else
   ierr = PetscObjectQueryFunction((PetscObject)dm,"DMlibMeshGetSystem_C",&f);CHKERRQ(ierr);
 #endif
   if(!f) SETERRQ(PETSC_COMM_SELF,PETSC_ERR_SUP, "DM has no implementation for DMlibMeshGetSystem");
   ierr = (*f)(dm,sys);CHKERRQ(ierr);
   PetscFunctionReturn(0);
 }
PetscErrorCode DMlibMeshSetSystem (DM , libMesh::NonlinearImplicitSystem &)
Any functional implementation of the DMlibMesh API must compose the following functions with the DM object. (See PETSc documentation on PetscObjectComposeFunction(), a polymorphism mechanism.) The following functions are called in PetscNonlinear Solver (others can be called by users): DMlibMeshSetSystem(), DMlibMeshGetSystem()
Any implementation needs to register its creation routine, DMCreate_libMesh, with PETSc using DMRegister().
Definition at line 15 of file petscdmlibmesh.C.
References libmesh_nullptr.
 {
   PetscErrorCode (*f)(DM,libMesh::NonlinearImplicitSystem &) = libmesh_nullptr;
   PetscErrorCode ierr;
   PetscFunctionBegin;
   PetscValidHeaderSpecific(dm,DM_CLASSID,1);
 #if PETSC_RELEASE_LESS_THAN(3,4,0)
   ierr = PetscObjectQueryFunction((PetscObject)dm,"DMlibMeshSetSystem_C",(PetscVoidFunction*)&f);CHKERRQ(ierr);
 #else
   ierr = PetscObjectQueryFunction((PetscObject)dm,"DMlibMeshSetSystem_C",&f);CHKERRQ(ierr);
 #endif
   if(!f) SETERRQ(PETSC_COMM_SELF,PETSC_ERR_SUP, "DM has no implementation for DMlibMeshSetSystem");
   ierr = (*f)(dm,sys);CHKERRQ(ierr);
   PetscFunctionReturn(0);
 }