libMesh: petscdmlibmesh.h File Reference
SomeWebsiteLogo
petscdmlibmesh.h File Reference
Functions
PetscErrorCode DMCreateLibMesh (MPI_Comm, libMesh::NonlinearImplicitSystem &, DM *)
PetscErrorCode DMLibMeshSetSystem (DM, libMesh::NonlinearImplicitSystem &)
PetscErrorCode DMLibMeshGetSystem (DM, libMesh::NonlinearImplicitSystem *&)
PetscErrorCode DMLibMeshGetBlocks (DM, PetscInt *, char ***)
PetscErrorCode DMLibMeshGetVariables (DM, PetscInt *, char ***)
PetscErrorCode DMLibMeshCreateFieldDecompositionDM (DM, PetscInt, PetscInt *, const char ***, DM *)
PetscErrorCode DMLibMeshCreateDomainDecompositionDM (DM, PetscInt, PetscInt *, const char ***, DM *)
Function Documentation
PetscErrorCode DMCreateLibMesh (MPI_Comm , libMesh::NonlinearImplicitSystem & , DM *)
Definition at line 1113 of file petscdmlibmesh.C.
References CHKERRQ(), DMLibMeshSetSystem(), libMesh::ierr, PetscFunctionBegin, and PetscFunctionReturn().
Referenced by libMesh::PetscDMNonlinearSolver< T >::init().
 {
   PetscErrorCode ierr;
   PetscFunctionBegin;
   ierr = DMCreate(comm, dm);           CHKERRQ(ierr);
   ierr = DMSetType(*dm, DMLIBMESH);    CHKERRQ(ierr);
   ierr = DMLibMeshSetSystem(*dm, sys); CHKERRQ(ierr);
   PetscFunctionReturn(0);
 }
PetscErrorCode DMLibMeshCreateDomainDecompositionDM (DM , PetscInt , PetscInt * , const char *** , DM *)
PetscErrorCode DMLibMeshCreateFieldDecompositionDM (DM , PetscInt , PetscInt * , const char *** , DM *)
PetscErrorCode DMLibMeshGetBlocks (DM , PetscInt * , char ***)
Definition at line 45 of file petscdmlibmesh.C.
References DM_libMesh::blockids, CHKERRQ(), libMesh::comm, dlm, libMesh::ierr, PetscBool, PetscFunctionBegin, and PetscFunctionReturn().
 {
   PetscErrorCode ierr;
   PetscInt i;
   PetscFunctionBegin;
   PetscValidHeaderSpecific(dm,DM_CLASSID,1);
   PetscBool islibmesh;
   ierr = PetscObjectTypeCompare((PetscObject)dm, DMLIBMESH,&islibmesh);
   if(!islibmesh) SETERRQ2(((PetscObject)dm)->comm, PETSC_ERR_ARG_WRONG, "Got DM oftype %s, not of type %s", ((PetscObject)dm)->type_name, DMLIBMESH);
   DM_libMesh *dlm = (DM_libMesh *)(dm->data);
   PetscValidPointer(n,2);
   *n = cast_int<PetscInt>(dlm->blockids->size());
   if(!blocknames) PetscFunctionReturn(0);
   ierr = PetscMalloc(*n*sizeof(char*), blocknames); CHKERRQ(ierr);
   i = 0;
   for(std::map<std::string, unsigned int>::const_iterator it = dlm->blockids->begin(); it != dlm->blockids->end(); ++it){
     ierr = PetscStrallocpy(it->first.c_str(), *blocknames+i); CHKERRQ(ierr);
     ++i;
   }
   PetscFunctionReturn(0);
 }
PetscErrorCode DMLibMeshGetSystem (DM , libMesh::NonlinearImplicitSystem *&)
Definition at line 205 of file petscdmlibmesh.C.
References CHKERRQ(), libMesh::comm, dlm, libMesh::ierr, PetscBool, PetscFunctionBegin, PetscFunctionReturn(), and DM_libMesh::sys.
Referenced by DMlibMeshFunction(), and DMVariableBounds_libMesh().
 {
   PetscErrorCode ierr;
   PetscFunctionBegin;
   PetscValidHeaderSpecific(dm,DM_CLASSID,1);
   PetscBool islibmesh;
   ierr = PetscObjectTypeCompare((PetscObject)dm, DMLIBMESH,&islibmesh); CHKERRQ(ierr);
   if(!islibmesh) SETERRQ2(((PetscObject)dm)->comm, PETSC_ERR_ARG_WRONG, "Got DM oftype %s, not of type %s", ((PetscObject)dm)->type_name, DMLIBMESH);
   DM_libMesh *dlm = (DM_libMesh *)(dm->data);
   sys = dlm->sys;
   PetscFunctionReturn(0);
 }
PetscErrorCode DMLibMeshGetVariables (DM , PetscInt * , char ***)
Definition at line 69 of file petscdmlibmesh.C.
References CHKERRQ(), libMesh::comm, dlm, libMesh::ierr, PetscBool, PetscFunctionBegin, PetscFunctionReturn(), and DM_libMesh::varids.
 {
   PetscErrorCode ierr;
   PetscFunctionBegin;
   PetscValidHeaderSpecific(dm,DM_CLASSID,1);
   PetscBool islibmesh;
   PetscInt i;
   ierr = PetscObjectTypeCompare((PetscObject)dm, DMLIBMESH,&islibmesh);
   if(!islibmesh) SETERRQ2(((PetscObject)dm)->comm, PETSC_ERR_ARG_WRONG, "Got DM oftype %s, not of type %s", ((PetscObject)dm)->type_name, DMLIBMESH);
   DM_libMesh *dlm = (DM_libMesh *)(dm->data);
   PetscValidPointer(n,2);
   *n = cast_int<PetscInt>(dlm->varids->size());
   if(!varnames) PetscFunctionReturn(0);
   ierr = PetscMalloc(*n*sizeof(char*), varnames); CHKERRQ(ierr);
   i = 0;
   for(std::map<std::string, unsigned int>::const_iterator it = dlm->varids->begin(); it != dlm->varids->end(); ++it){
     ierr = PetscStrallocpy(it->first.c_str(), *varnames+i); CHKERRQ(ierr);
     ++i;
   }
   PetscFunctionReturn(0);
 }
PetscErrorCode DMLibMeshSetSystem (DM , libMesh::NonlinearImplicitSystem &)
Definition at line 142 of file petscdmlibmesh.C.
References libMesh::MeshBase::active_elements_begin(), libMesh::MeshBase::active_elements_end(), DM_libMesh::blockids, DM_libMesh::blocknames, CHKERRQ(), libMesh::ParallelObject::comm(), libMesh::comm, dlm, DMLibMeshSetUpName_Private(), end, libMesh::System::get_dof_map(), libMesh::System::get_mesh(), libMesh::ierr, libMesh::libmesh_parallel_only(), mesh, libMesh::DofMap::n_variables(), libMesh::Variable::name(), PETSC_ERR_ARG_WRONGSTATE, PetscBool, PetscFunctionBegin, PetscFunctionReturn(), libMesh::MeshBase::subdomain_name(), DM_libMesh::sys, libMesh::sys, libMesh::DofMap::variable(), DM_libMesh::varids, and DM_libMesh::varnames.
Referenced by DMCreateLibMesh().
 {
   const Parallel::Communicator &comm(sys.comm());
   PetscErrorCode ierr;
   PetscFunctionBegin;
   PetscValidHeaderSpecific(dm,DM_CLASSID,1);
   PetscBool islibmesh;
   ierr = PetscObjectTypeCompare((PetscObject)dm, DMLIBMESH,&islibmesh);
   if(!islibmesh) SETERRQ2(((PetscObject)dm)->comm, PETSC_ERR_ARG_WRONG, "Got DM oftype %s, not of type %s", ((PetscObject)dm)->type_name, DMLIBMESH);
   if(dm->setupcalled) SETERRQ(((PetscObject)dm)->comm, PETSC_ERR_ARG_WRONGSTATE, "Cannot reset the libMesh system after DM has been set up.");
   DM_libMesh *dlm = (DM_libMesh *)(dm->data);
   dlm->sys =&sys;
   /* Initially populate the sets of active blockids and varids using all of the
      existing blocks/variables (only variables are supported at the moment). */
   DofMap& dofmap = dlm->sys->get_dof_map();
   dlm->varids->clear();
   dlm->varnames->clear();
   for(unsigned int v = 0; v < dofmap.n_variables(); ++v) {
     std::string vname = dofmap.variable(v).name();
     dlm->varids->insert(std::pair<std::string,unsigned int>(vname,v));
     dlm->varnames->insert(std::pair<unsigned int,std::string>(v,vname));
   }
   const MeshBase& mesh = dlm->sys->get_mesh();
   dlm->blockids->clear();
   dlm->blocknames->clear();
   std::set<subdomain_id_type> blocks;
   /* The following effectively is a verbatim copy of MeshBase::n_subdomains(). */
   // This requires an inspection on every processor
   libmesh_parallel_only(mesh.comm());
   MeshBase::const_element_iterator       el  = mesh.active_elements_begin();
   const MeshBase::const_element_iterator end = mesh.active_elements_end();
   for (; el!=end; ++el)
     blocks.insert((*el)->subdomain_id());
   // Some subdomains may only live on other processors
   comm.set_union(blocks);
   std::set<subdomain_id_type>::iterator bit = blocks.begin();
   std::set<subdomain_id_type>::iterator bend = blocks.end();
   if(bit == bend) SETERRQ(((PetscObject)dm)->comm, PETSC_ERR_PLIB, "No mesh blocks found.");
   for(; bit != bend; ++bit) {
     subdomain_id_type bid = *bit;
     std::string bname = mesh.subdomain_name(bid);
     if(!bname.length()) {
       /* Block names are currently implemented for Exodus II meshes
          only, so we might have to make up our own block names and
          maintain our own mapping of block ids to names.
       */
       std::ostringstream ss;
       ss << "dm" << bid;
       bname = ss.str();
     }
     dlm->blockids->insert(std::pair<std::string,unsigned int>(bname,bid));
     dlm->blocknames->insert(std::pair<unsigned int,std::string>(bid,bname));
   }
   ierr = DMLibMeshSetUpName_Private(dm); CHKERRQ(ierr);
   PetscFunctionReturn(0);
 }