libMesh: petsc_linear_solver.h File Reference
SomeWebsiteLogo
petsc_linear_solver.h File Reference
Classes
class libMesh::PetscMatrix< T >
SparseMatrix interface to PETSc Mat.
class libMesh::PetscLinearSolver< T >
Namespaces
libMesh
Functions
PetscErrorCode libmesh_petsc_preconditioner_setup (void *ctx)
PetscErrorCode libmesh_petsc_preconditioner_apply (void *ctx, Vec x, Vec y)
PetscErrorCode libmesh_petsc_preconditioner_setup (PC)
PetscErrorCode libmesh_petsc_preconditioner_apply (PC, Vec x, Vec y)
PetscErrorCode __libmesh_petsc_preconditioner_setup (void *ctx)
PetscErrorCode __libmesh_petsc_preconditioner_apply (void *ctx, Vec x, Vec y)
PetscErrorCode __libmesh_petsc_preconditioner_setup (PC)
PetscErrorCode __libmesh_petsc_preconditioner_apply (PC, Vec x, Vec y)
Function Documentation
__libmesh_petsc_preconditioner_apply() [1/2]
PetscErrorCode __libmesh_petsc_preconditioner_apply (void * ctx, Vec x, Vec y)
This function is called by PETSc to actually apply the preconditioner. ctx will hold the Preconditioner.
Definition at line 110 of file petsc_linear_solver.C.
References libMesh::libmesh_petsc_preconditioner_apply().
   {
     libmesh_deprecated();
     return libmesh_petsc_preconditioner_apply(ctx, x, y);
   }
__libmesh_petsc_preconditioner_apply() [2/2]
PetscErrorCode __libmesh_petsc_preconditioner_apply (PC , Vec x, Vec y)
Definition at line 123 of file petsc_linear_solver.C.
References libMesh::libmesh_petsc_preconditioner_apply().
   {
     libmesh_deprecated();
     return libmesh_petsc_preconditioner_apply(pc, x, y);
   }
__libmesh_petsc_preconditioner_setup() [1/2]
PetscErrorCode __libmesh_petsc_preconditioner_setup (void * ctx)
This function is called by PETSc to initialize the preconditioner. ctx will hold the Preconditioner.
Definition at line 104 of file petsc_linear_solver.C.
References libMesh::libmesh_petsc_preconditioner_setup().
   {
     libmesh_deprecated();
     return libmesh_petsc_preconditioner_setup(ctx);
   }
__libmesh_petsc_preconditioner_setup() [2/2]
PetscErrorCode __libmesh_petsc_preconditioner_setup (PC)
Definition at line 117 of file petsc_linear_solver.C.
References libMesh::libmesh_petsc_preconditioner_setup().
   {
     libmesh_deprecated();
     return libmesh_petsc_preconditioner_setup(pc);
   }
libmesh_petsc_preconditioner_apply() [1/2]
PetscErrorCode libmesh_petsc_preconditioner_apply (void * ctx, Vec x, Vec y)
This function is called by PETSc to actually apply the preconditioner. ctx will hold the Preconditioner.
Definition at line 61 of file petsc_linear_solver.C.
Referenced by __libmesh_petsc_preconditioner_apply(), libMesh::PetscNonlinearSolver< Number >::init(), and libMesh::PetscLinearSolver< T >::init().
   {
     Preconditioner<Number> * preconditioner = static_cast<Preconditioner<Number> *>(ctx);
     PetscVector<Number> x_vec(x, preconditioner->comm());
     PetscVector<Number> y_vec(y, preconditioner->comm());
     preconditioner->apply(x_vec,y_vec);
     return 0;
   }
libmesh_petsc_preconditioner_apply() [2/2]
PetscErrorCode libmesh_petsc_preconditioner_apply (PC , Vec x, Vec y)
Definition at line 87 of file petsc_linear_solver.C.
References CHKERRQ(), and ierr.
   {
     void * ctx;
     PetscErrorCode ierr = PCShellGetContext(pc,&ctx);CHKERRQ(ierr);
     Preconditioner<Number> * preconditioner = static_cast<Preconditioner<Number> *>(ctx);
     PetscVector<Number> x_vec(x, preconditioner->comm());
     PetscVector<Number> y_vec(y, preconditioner->comm());
     preconditioner->apply(x_vec,y_vec);
     return 0;
   }
libmesh_petsc_preconditioner_setup() [1/2]
PetscErrorCode libmesh_petsc_preconditioner_setup (void * ctx)
This function is called by PETSc to initialize the preconditioner. ctx will hold the Preconditioner.
Definition at line 48 of file petsc_linear_solver.C.
Referenced by __libmesh_petsc_preconditioner_setup(), libMesh::PetscNonlinearSolver< Number >::init(), and libMesh::PetscLinearSolver< T >::init().
   {
     Preconditioner<Number> * preconditioner = static_cast<Preconditioner<Number> *>(ctx);
     if (!preconditioner->initialized())
       libmesh_error_msg("Preconditioner not initialized!  Make sure you call init() before solve!");
     preconditioner->setup();
     return 0;
   }
libmesh_petsc_preconditioner_setup() [2/2]
PetscErrorCode libmesh_petsc_preconditioner_setup (PC)
Definition at line 73 of file petsc_linear_solver.C.
References CHKERRQ(), and ierr.
   {
     void * ctx;
     PetscErrorCode ierr = PCShellGetContext(pc,&ctx);CHKERRQ(ierr);
     Preconditioner<Number> * preconditioner = static_cast<Preconditioner<Number> *>(ctx);
     if (!preconditioner->initialized())
       libmesh_error_msg("Preconditioner not initialized!  Make sure you call init() before solve!");
     preconditioner->setup();
     return 0;
   }