libMesh: libMesh::VTKIO::ElementMaps Struct Reference
SomeWebsiteLogo
libMesh::VTKIO::ElementMaps Struct Reference
Public Member Functions
void associate (ElemType libmesh_type, vtkIdType vtk_type)
vtkIdType find (ElemType libmesh_type)
ElemType find (vtkIdType vtk_type)
Public Attributes
std::map< ElemType, vtkIdType > writing_map
std::map< vtkIdType, ElemType > reading_map
Detailed Description
Helper object that holds a map from VTK to libMesh element types and vice-versa.
Definition at line 168 of file vtk_io.h.
Member Function Documentation
void libMesh::VTKIO::ElementMaps::associate (ElemType libmesh_type, vtkIdType vtk_type) inline
Definition at line 171 of file vtk_io.h.
References reading_map, and writing_map.
Referenced by libMesh::VTKIO::build_element_maps().
     {
       writing_map[libmesh_type] = vtk_type;
       reading_map[vtk_type] = libmesh_type;
     }
vtkIdType libMesh::VTKIO::ElementMaps::find (ElemType libmesh_type) inline
Definition at line 178 of file vtk_io.h.
References writing_map.
Referenced by libMesh::VTKIO::cells_to_vtk(), and libMesh::VTKIO::read().
     {
       std::map<ElemType, vtkIdType>::iterator it = writing_map.find(libmesh_type);
       if (it == writing_map.end())
         libmesh_error_msg("Element type " << libmesh_type << " not available in VTK.");
       return it->second;
     }
ElemType libMesh::VTKIO::ElementMaps::find (vtkIdType vtk_type) inline
Definition at line 189 of file vtk_io.h.
References reading_map.
     {
       std::map<vtkIdType, ElemType>::iterator it = reading_map.find(vtk_type);
       if (it == reading_map.end())
         libmesh_error_msg("Element type " << vtk_type << " not available in libMesh.");
       return it->second;
     }
Member Data Documentation
std::map<vtkIdType, ElemType> libMesh::VTKIO::ElementMaps::reading_map
Definition at line 200 of file vtk_io.h.
Referenced by associate(), and find().
std::map<ElemType, vtkIdType> libMesh::VTKIO::ElementMaps::writing_map
Definition at line 199 of file vtk_io.h.
Referenced by associate(), libMesh::VTKIO::build_element_maps(), and find().
The documentation for this struct was generated from the following file:
vtk_io.h