libMesh: libMesh::mesh_inserter_iterator< T > Struct Template Reference
SomeWebsiteLogo
libMesh::mesh_inserter_iterator< T > Struct Template Reference
An output iterator for use with packed_range functions.
#include <mesh_inserter_iterator.h>
Public Member Functions
mesh_inserter_iterator (MeshBase &m)
void operator= (Elem *e)
void operator= (Node *n)
void operator= (Point *p)
mesh_inserter_iterator & operator++ ()
mesh_inserter_iterator operator++ (int)
mesh_inserter_iterator & operator* ()
Private Attributes
MeshBase & mesh
Detailed Description
template<typename T>
struct libMesh::mesh_inserter_iterator< T >
An output iterator for use with packed_range functions.
A class for templated methods that expect output iterator arguments, which adds objects to the Mesh. Although any mesh_inserter_iterator can add any object, we template it around object type so that type inference and iterator_traits will work.
Author
Roy Stogner
Date
2012
Definition at line 46 of file mesh_inserter_iterator.h.
Constructor & Destructor Documentation
mesh_inserter_iterator()
template<typename T > libMesh::mesh_inserter_iterator< T >::mesh_inserter_iterator (MeshBase & m) inline
Definition at line 49 of file mesh_inserter_iterator.h.
Referenced by libMesh::mesh_inserter_iterator< T >::operator++().
 : mesh(m) {}
Member Function Documentation
operator*()
template<typename T > mesh_inserter_iterator& libMesh::mesh_inserter_iterator< T >::operator* () inline
Definition at line 69 of file mesh_inserter_iterator.h.
 { return *this; }
operator++() [1/2]
template<typename T > mesh_inserter_iterator& libMesh::mesh_inserter_iterator< T >::operator++ () inline
Definition at line 57 of file mesh_inserter_iterator.h.
{
     return *this;
   }
operator++() [2/2]
template<typename T > mesh_inserter_iterator libMesh::mesh_inserter_iterator< T >::operator++ (int) inline
Definition at line 61 of file mesh_inserter_iterator.h.
References libMesh::mesh_inserter_iterator< T >::mesh_inserter_iterator().
{
     return mesh_inserter_iterator(*this);
   }
operator=() [1/3]
template<typename T > void libMesh::mesh_inserter_iterator< T >::operator= (Elem * e) inline
Definition at line 51 of file mesh_inserter_iterator.h.
References libMesh::MeshBase::add_elem(), and libMesh::mesh_inserter_iterator< T >::mesh.
 { mesh.add_elem(e); }
operator=() [2/3]
template<typename T > void libMesh::mesh_inserter_iterator< T >::operator= (Node * n) inline
Definition at line 53 of file mesh_inserter_iterator.h.
References libMesh::MeshBase::insert_node(), and libMesh::mesh_inserter_iterator< T >::mesh.
 { mesh.insert_node(n); }
operator=() [3/3]
template<typename T > void libMesh::mesh_inserter_iterator< T >::operator= (Point * p) inline
Definition at line 55 of file mesh_inserter_iterator.h.
References libMesh::MeshBase::add_point(), and libMesh::mesh_inserter_iterator< T >::mesh.
 { mesh.add_point(*p); }
Member Data Documentation
mesh
template<typename T > MeshBase& libMesh::mesh_inserter_iterator< T >::mesh private
Definition at line 72 of file mesh_inserter_iterator.h.
Referenced by libMesh::mesh_inserter_iterator< T >::operator=().
The documentation for this struct was generated from the following file:
mesh_inserter_iterator.h