libMesh: libMesh::Parallel::Attributes< unsigned long long > Struct Template Reference
SomeWebsiteLogo
libMesh::Parallel::Attributes< unsigned long long > Struct Template Reference
#include <parallel_implementation.h>
Static Public Member Functions
static void set_lowest (unsigned long long &x)
static void set_highest (unsigned long long &x)
Static Public Attributes
static const bool has_min_max = true
Detailed Description
template<>
struct libMesh::Parallel::Attributes< unsigned long long >
Definition at line 177 of file parallel_implementation.h.
Member Function Documentation
static void libMesh::Parallel::Attributes< unsigned long long >::set_highest (unsigned long long & x) inline static
Definition at line 181 of file parallel_implementation.h.
References libMesh::Parallel::LIBMESH_CONTAINER_TYPE(), libMesh::Parallel::LIBMESH_FLOAT_TYPE(), and libMesh::Parallel::max().
 { x = std::numeric_limits<unsigned long long>::max(); }
static void libMesh::Parallel::Attributes< unsigned long long >::set_lowest (unsigned long long & x) inline static
Definition at line 180 of file parallel_implementation.h.
References libMesh::Parallel::min().
 { x = std::numeric_limits<unsigned long long>::min(); }
Member Data Documentation
const bool libMesh::Parallel::Attributes< unsigned long long >::has_min_max = true static
Definition at line 179 of file parallel_implementation.h.
The documentation for this struct was generated from the following file:
parallel_implementation.h