libMesh: libMesh::CompareElemIdsByLevel Struct Reference
SomeWebsiteLogo
libMesh::CompareElemIdsByLevel Struct Reference
#include <compare_elems_by_level.h>
Public Member Functions
bool operator() (const Elem *a, const Elem *b) const
Detailed Description
Specific weak ordering for Elem *'s to be used in a set. We use the id, but first sort by level. This guarantees when traversing the set from beginning to end the lower level (parent) elements are encountered first.
Definition at line 42 of file compare_elems_by_level.h.
Member Function Documentation
bool libMesh::CompareElemIdsByLevel::operator() (const Elem * a, const Elem * b) const inline
Definition at line 44 of file compare_elems_by_level.h.
References libMesh::DofObject::id(), libMesh::Elem::level(), and libMesh::libmesh_assert().
   {
     libmesh_assert (a);
     libmesh_assert (b);
     const unsigned int
       al = a->level(), bl = b->level();
     const dof_id_type
       aid = a->id(),   bid = b->id();
     return (al == bl) ? aid < bid : al < bl;
   }
The documentation for this struct was generated from the following file:
compare_elems_by_level.h