libMesh: libMesh::Predicates::evaluable< T > Struct Template Reference
SomeWebsiteLogo
libMesh::Predicates::evaluable< T > Struct Template Reference
#include <single_predicates.h>
Public Member Functions
evaluable (const DofMap &dof_map, unsigned int var_num)
virtual ~evaluable ()
virtual bool operator() (const T &it) const libmesh_override
Protected Member Functions
virtual predicate< T > * clone () const libmesh_override
Protected Attributes
const DofMap & _dof_map
unsigned int _var_num
Detailed Description
template<typename T>
struct libMesh::Predicates::evaluable< T >
Returns
true if the pointer (which must be a local element) has degrees of freedom which can be evaluated for the specified DofMap and variable.
Definition at line 467 of file single_predicates.h.
Constructor & Destructor Documentation
template<typename T> libMesh::Predicates::evaluable< T >::evaluable (const DofMap & dof_map, unsigned int var_num) inline
Definition at line 469 of file single_predicates.h.
                                   :
     _dof_map(dof_map), _var_num(var_num) {}
template<typename T> virtual libMesh::Predicates::evaluable< T >::~evaluable () inline virtual
Definition at line 472 of file single_predicates.h.
References libMesh::Predicates::predicate< T >::operator()().
 {}
Member Function Documentation
template<typename T> virtual predicate<T>* libMesh::Predicates::evaluable< T >::clone () const inline protected virtual
Implements libMesh::Predicates::predicate< T >.
Definition at line 478 of file single_predicates.h.
 { return new evaluable<T>(*this); }
template<typename T > bool libMesh::Predicates::evaluable< T >::operator() (const T & it) const virtual
Implements libMesh::Predicates::predicate< T >.
Definition at line 50 of file single_predicates.C.
References libMesh::Predicates::INSTANTIATE_ELEM_PREDICATES(), and libMesh::Predicates::INSTANTIATE_NODAL_PREDICATES().
 {
   return _dof_map.is_evaluable(**it, _var_num);
 }
Member Data Documentation
template<typename T> const DofMap& libMesh::Predicates::evaluable< T >::_dof_map protected
Definition at line 479 of file single_predicates.h.
template<typename T> unsigned int libMesh::Predicates::evaluable< T >::_var_num protected
Definition at line 480 of file single_predicates.h.
The documentation for this struct was generated from the following files:
single_predicates.h
single_predicates.C