libMesh: libMesh::Predicates::predicate< T > Struct Template Reference
SomeWebsiteLogo
libMesh::Predicates::predicate< T > Struct Template Reference abstract
#include <single_predicates.h>
Public Member Functions
virtual ~predicate ()
virtual bool operator() (const T &it) const =0
Protected Member Functions
virtual predicate * clone () const =0
Friends
struct abstract_multi_predicate< T >
Detailed Description
template<typename T>
struct libMesh::Predicates::predicate< T >
Definition at line 60 of file single_predicates.h.
Constructor & Destructor Documentation
template<typename T> virtual libMesh::Predicates::predicate< T >::~predicate () inline virtual
Definition at line 62 of file single_predicates.h.
References libMesh::Predicates::predicate< T >::operator()().
 {}
Member Function Documentation
template<typename T> virtual predicate* libMesh::Predicates::predicate< T >::clone () const protected pure virtual
Implemented in libMesh::Predicates::evaluable< T >, libMesh::Predicates::subdomain_set< T >, libMesh::Predicates::subdomain< T >, libMesh::Predicates::boundary_side< T >, libMesh::Predicates::null_neighbor< T >, libMesh::Predicates::not_level< T >, libMesh::Predicates::level< T >, libMesh::Predicates::flagged< T >, libMesh::Predicates::elem_type< T >, libMesh::Predicates::not_pid< T >, libMesh::Predicates::facelocal_pid< T >, libMesh::Predicates::semilocal_pid< T >, libMesh::Predicates::bnd< T >, libMesh::Predicates::bid< T >, libMesh::Predicates::pid< T >, libMesh::Predicates::not_subactive< T >, libMesh::Predicates::subactive< T >, libMesh::Predicates::not_ancestor< T >, libMesh::Predicates::ancestor< T >, libMesh::Predicates::not_active< T >, libMesh::Predicates::active< T >, libMesh::Predicates::not_null< T >, and libMesh::Predicates::is_null< T >.
template<typename T> virtual bool libMesh::Predicates::predicate< T >::operator() (const T & it) const pure virtual
Implemented in libMesh::Predicates::evaluable< T >, libMesh::Predicates::subdomain_set< T >, libMesh::Predicates::subdomain< T >, libMesh::Predicates::boundary_side< T >, libMesh::Predicates::null_neighbor< T >, libMesh::Predicates::not_level< T >, libMesh::Predicates::level< T >, libMesh::Predicates::flagged< T >, libMesh::Predicates::elem_type< T >, libMesh::Predicates::not_pid< T >, libMesh::Predicates::facelocal_pid< T >, libMesh::Predicates::semilocal_pid< T >, libMesh::Predicates::bnd< T >, libMesh::Predicates::bid< T >, libMesh::Predicates::pid< T >, libMesh::Predicates::not_subactive< T >, libMesh::Predicates::subactive< T >, libMesh::Predicates::not_ancestor< T >, libMesh::Predicates::ancestor< T >, libMesh::Predicates::not_active< T >, libMesh::Predicates::active< T >, libMesh::Predicates::not_null< T >, and libMesh::Predicates::is_null< T >.
Referenced by libMesh::Predicates::bid< T >::~bid(), libMesh::Predicates::bnd< T >::~bnd(), libMesh::Predicates::evaluable< T >::~evaluable(), and libMesh::Predicates::predicate< T >::~predicate().
Friends And Related Function Documentation
template<typename T> friend struct abstract_multi_predicate< T > friend
Definition at line 66 of file single_predicates.h.
The documentation for this struct was generated from the following file:
single_predicates.h